### ISSUE TITLE
Hi, I am getting  publish Failed PUT 403

### ISSUE THREAD

**Issue by philipjc** [npm/npm#10012]
Sorry, I am new to pushing to npm, any help much appreciated.

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/4.2.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'publish' ]
2 info using npm@2.14.7
3 info using node@v4.2.0
4 verbose publish [ '.' ]
5 silly cache add args [ '.', null ]
6 verbose cache add spec .
7 silly cache add parsed spec Result {
7 silly cache add   raw: '.',
7 silly cache add   scope: null,
7 silly cache add   name: null,
7 silly cache add   rawSpec: '.',
7 silly cache add   spec: '/Users/Phil/hacky/openSource/starWars',
7 silly cache add   type: 'directory' }
8 verbose addLocalDirectory /Users/Phil/.npm/starwars-names/1.0.0/package.tgz not in flight; packing
9 verbose tar pack [ '/Users/Phil/.npm/starwars-names/1.0.0/package.tgz',
9 verbose tar pack   '/Users/Phil/hacky/openSource/starWars' ]
10 verbose tarball /Users/Phil/.npm/starwars-names/1.0.0/package.tgz
11 verbose folder /Users/Phil/hacky/openSource/starWars
12 info prepublish starwars-names@1.0.0
13 verbose addLocalTarball adding from inside cache /Users/Phil/.npm/starwars-names/1.0.0/package.tgz
14 silly cache afterAdd starwars-names@1.0.0
15 verbose afterAdd /Users/Phil/.npm/starwars-names/1.0.0/package/package.json not in flight; writing
16 verbose afterAdd /Users/Phil/.npm/starwars-names/1.0.0/package/package.json written
17 silly publish { name: 'starwars-names',
17 silly publish   version: '1.0.0',
17 silly publish   description: 'Get a Star Wars name module.',
17 silly publish   main: 'src/index.js',
17 silly publish   scripts: { test: 'echo "Error: no test specified" && exit 1' },
17 silly publish   repository:
17 silly publish    { type: 'git',
17 silly publish      url: 'git+https://github.com/philipjc/starwars-names.git' },
17 silly publish   author: { name: 'philipjc' },
17 silly publish   license: 'MIT',
17 silly publish   bugs: { url: 'https://github.com/philipjc/starwars-names/issues' },
17 silly publish   homepage: 'https://github.com/philipjc/starwars-names#readme',
17 silly publish   dependencies: { 'unique-random-array': '1.0.0' },
17 silly publish   readme: '## Star Wars Names\n',
17 silly publish   readmeFilename: 'README.md',
17 silly publish   gitHead: 'd85f5e2f8d995e227c92ed35ef96cdb3641263c8',
17 silly publish   _id: 'starwars-names@1.0.0',
17 silly publish   _shasum: '7e9719bc6e4e5d5f5fa92e08a88154b5824ba13b',
17 silly publish   _from: '.' }
18 verbose getPublishConfig undefined
19 silly mapToRegistry name starwars-names
20 silly mapToRegistry using default registry
21 silly mapToRegistry registry https://registry.npmjs.org/
22 silly mapToRegistry uri https://registry.npmjs.org/starwars-names
23 verbose publish registryBase https://registry.npmjs.org/
24 silly publish uploading /Users/Phil/.npm/starwars-names/1.0.0/package.tgz
25 verbose request uri https://registry.npmjs.org/starwars-names
26 verbose request sending authorization for write operation
27 info attempt registry request try #1 at 7:27:10 PM
28 verbose request using bearer token for auth
29 verbose request id 3cbc6808d7f944ed
30 http request PUT https://registry.npmjs.org/starwars-names
31 http 403 https://registry.npmjs.org/starwars-names
32 verbose headers { 'content-type': 'application/json',
32 verbose headers   'cache-control': 'max-age=60',
32 verbose headers   'content-length': '106',
32 verbose headers   'accept-ranges': 'bytes',
32 verbose headers   date: 'Sat, 17 Oct 2015 18:27:10 GMT',
32 verbose headers   via: '1.1 varnish',
32 verbose headers   connection: 'keep-alive',
32 verbose headers   'x-served-by': 'cache-ams4130-AMS',
32 verbose headers   'x-cache': 'MISS',
32 verbose headers   'x-cache-hits': '0',
32 verbose headers   'x-timer': 'S1445106430.232060,VS0,VE664' }
33 verbose request invalidating /Users/Phil/.npm/registry.npmjs.org/starwars-names on PUT
34 error publish Failed PUT 403
35 verbose stack Error: You do not have permission to publish 'starwars-names'. Are you logged in as the correct user? : starwars-names
35 verbose stack     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
35 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:252:14)
35 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
35 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:198:22)
35 verbose stack     at emitTwo (events.js:87:13)
35 verbose stack     at Request.emit (events.js:172:7)
35 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1063:14)
35 verbose stack     at emitOne (events.js:82:20)
35 verbose stack     at Request.emit (events.js:169:7)
35 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1009:12)
36 verbose statusCode 403
37 verbose pkgid starwars-names
38 verbose cwd /Users/Phil/hacky/openSource/starWars
39 error Darwin 15.0.0
40 error argv "/usr/local/Cellar/node/4.2.0/bin/node" "/usr/local/bin/npm" "publish"
41 error node v4.2.0
42 error npm  v2.14.7
43 error code E403
44 error You do not have permission to publish 'starwars-names'. Are you logged in as the correct user? : starwars-names
45 error If you need help, you may report this error at:
45 error     <https://github.com/npm/npm/issues>
46 verbose exit [ 1, true ]

**Comment by philipjc** [comment]
Solved. Name already taken, face-palm
