### ISSUE TITLE
npm publish meet error: no_perms can't publish non-scoped package, please set `config.scopes`: node-mockit

### ISSUE THREAD

**Issue by ipconfiger** [npm/npm#10056]
i searched on npmjs.com no one use name : node-mockit  yet

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'publish' ]
2 info using npm@2.14.7
3 info using node@v4.2.1
4 verbose publish [ '.' ]
5 silly cache add args [ '.', null ]
6 verbose cache add spec .
7 silly cache add parsed spec Result {
7 silly cache add   raw: '.',
7 silly cache add   scope: null,
7 silly cache add   name: null,
7 silly cache add   rawSpec: '.',
7 silly cache add   spec: '/Users/liming/workspace/node-mockit',
7 silly cache add   type: 'directory' }
8 verbose addLocalDirectory /Users/liming/.npm/node-mockit/0.0.1/package.tgz not in flight; packing
9 verbose tar pack [ '/Users/liming/.npm/node-mockit/0.0.1/package.tgz',
9 verbose tar pack   '/Users/liming/workspace/node-mockit' ]
10 verbose tarball /Users/liming/.npm/node-mockit/0.0.1/package.tgz
11 verbose folder /Users/liming/workspace/node-mockit
12 info prepublish node-mockit@0.0.1
13 verbose addLocalTarball adding from inside cache /Users/liming/.npm/node-mockit/0.0.1/package.tgz
14 silly cache afterAdd node-mockit@0.0.1
15 verbose afterAdd /Users/liming/.npm/node-mockit/0.0.1/package/package.json not in flight; writing
16 verbose afterAdd /Users/liming/.npm/node-mockit/0.0.1/package/package.json written
17 silly publish { name: 'node-mockit',
17 silly publish   version: '0.0.1',
17 silly publish   preferGlobal: true,
17 silly publish   description: 'http protocal mock script make test easy',
17 silly publish   bin: { cli: './cli.js', mock: './mock.js' },
17 silly publish   keywords: [ 'mock', 'js', 'test' ],
17 silly publish   author: { name: 'Alexander.Li' },
17 silly publish   license: 'MIT',
17 silly publish   bugs: { url: 'https://github.com/ipconfiger/node-mockit/issues' },
17 silly publish   homepage: 'https://github.com/ipconfiger/node-mockit',
17 silly publish   dependencies: { request: 'latest', commander: 'latest' },
17 silly publish   readme: '#顾名思义就是用nodejs写的用来mock Http的服务端和客户端的工具\n\n##开发的目的\n\n方便客户端开发人员和服务端开发人员的协作，双方可以通过本工具的配置来协定交互协议，并且可以并行开发，在开发期间可以用mock.js和cli.js分别模拟服务端和客户端。可以提高整个团队的协作效率。\n\n另，如果有诸如开发的API之类，可以在不部署测试服务器的情况下，将配置好的脚本发给合作方，用于辅助接口接入使用。\n\n##使用方法\n1. 安装nodejs （必须）\n2. sudo npm install https://github.com/ipconfiger/node-mockit.git -g\n3. mkdir ./scripts\n3. cli -e > ./scripts/test.js\n4. mock -s ./scripts  即可启动mock服务端\n\n服务自己会检测配置脚本的变化，并且立即更新，所以修改了测试脚本后不需要重启\n\n用  cli -s 脚本地址 -h 服务根地址  就可以向服务地址提交指定脚本的请求，用于验证服务端实现\n比如 cli -s ./scripts -b http://127.0.0.1:25300\n\n\n##配置文件说明：\n\n    exports.config={\n\t    name:"test7",   // 接口名，输出错误提示的时候用到\n\t    url:"/test",    //接口地址\n\t    request:{       //请求部分配置\n\t        method:"POST",  //请求的方法\n\t        headers:{Authorization:"Basic token"}, //请求的header（可选项）\n\t        type:"body",  //请求的方式，有body,form,get 三个选项后续请求说明中详细说明\n\t        data:{        //请求的数据\n\t            name:"alex",\n\t            password:"XXXX",\n\t        }\n\t    },\n\t    response:{       //返回数据定义\n\t        content_type:"application/json",     //返回内容类型\n\t        success:{                            //请求正确时的返回内容\n\t            rs:true,\n\t            info:""\n\t        },\n\t        error:{                              //请求错误时的返回内容\n\t            rs:false,\n\t            error:"error info"\n\t        }\n\t    }\n\t}\n\t\n\n##请求方式说明：\n\n###body：\n\n通过post发送数据，将请求内容用json序列化后放在body中\n\n###form：\n\n通过form表单发送的数据\n\n###get：\n\nGET请求通过querystring发送数据\n\n##命令参数\n\n    mock -h\n\n    Usage: mock [options]\n\n    Options:\n\n      -h, --help           输出命令说明\n      -V, --version        输出版本号\n      -s,--scripts [type]  设定脚本所在目录，比如./scripts\n      -p,--port [type]     设定服务器工作目录，比如 25300\n      -l,--level [type]    设定请求验证级别0=不检测 1=只检测键 2=全检测 默认：1\n      \n\n\n---------------------------------------------------------------------------\n\n    cli --help\n\n    Usage: cli [options]\n\n    Options:\n\n      -h, --help          输出命令说明\n      -V, --version       输出版本号\n      -e,--example        输出example配置脚本\n      -s,--script [type]  设定脚本所在目录，比如./scripts\n      -b,--host [type]    设定服务器地址和端口 [http://127.0.0.1:25300]\n',
17 silly publish   readmeFilename: 'README.md',
17 silly publish   gitHead: '066334ad5dc2af5a031d7e1721d9643b0e589fa1',
17 silly publish   _id: 'node-mockit@0.0.1',
17 silly publish   scripts: {},
17 silly publish   _shasum: '68127d1975ae8bcd0e112f61100a9a9a051d87b2',
17 silly publish   _from: '.' }
18 verbose getPublishConfig undefined
19 silly mapToRegistry name node-mockit
20 silly mapToRegistry using default registry
21 silly mapToRegistry registry http://registry.cnpmjs.org/
22 silly mapToRegistry uri http://registry.cnpmjs.org/node-mockit
23 verbose publish registryBase http://registry.cnpmjs.org/
24 silly publish uploading /Users/liming/.npm/node-mockit/0.0.1/package.tgz
25 verbose request uri http://registry.cnpmjs.org/node-mockit
26 verbose request sending authorization for write operation
27 info attempt registry request try #1 at 11:24:43
28 verbose request id 3cd67c6470f4b1be
29 http request PUT http://registry.cnpmjs.org/node-mockit
30 info retry will retry, error on last attempt: Error: connect ETIMEDOUT 107.150.97.166:80
31 info attempt registry request try #2 at 11:26:10
32 http request PUT http://registry.cnpmjs.org/node-mockit
33 http 403 http://registry.cnpmjs.org/node-mockit
34 verbose headers { server: 'nginx/1.4.6 (Ubuntu)',
34 verbose headers   date: 'Wed, 21 Oct 2015 03:26:20 GMT',
34 verbose headers   'content-type': 'application/json; charset=utf-8',
34 verbose headers   'transfer-encoding': 'chunked',
34 verbose headers   connection: 'keep-alive',
34 verbose headers   'x-readtime': '7',
34 verbose headers   'content-encoding': 'gzip' }
35 verbose request invalidating /Users/liming/.npm/registry.cnpmjs.org/node-mockit on PUT
36 error publish Failed PUT 403
37 verbose stack Error: no_perms can't publish non-scoped package, please set `config.scopes`: node-mockit
37 verbose stack     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
37 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:252:14)
37 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:178:7
37 verbose stack     at Gunzip.onEnd (zlib.js:227:5)
37 verbose stack     at emitNone (events.js:72:20)
37 verbose stack     at Gunzip.emit (events.js:166:7)
37 verbose stack     at endReadableNT (_stream_readable.js:903:12)
37 verbose stack     at doNTCallback2 (node.js:439:9)
37 verbose stack     at process._tickCallback (node.js:353:17)
38 verbose statusCode 403
39 verbose pkgid node-mockit
40 verbose cwd /Users/liming/workspace/node-mockit
41 error Darwin 15.0.0
42 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "publish"
43 error node v4.2.1
44 error npm  v2.14.7
45 error code E403
46 error no_perms can't publish non-scoped package, please set `config.scopes`: node-mockit
47 error If you need help, you may report this error at:
47 error     <https://github.com/npm/npm/issues>
48 verbose exit [ 1, true ]
```

**Comment by othiym23** [comment]
This seems to be an issue with cnpmjs's registry software, and isn't an error coming from the CLI (or npm's own registry):

```
33 http 403 http://registry.cnpmjs.org/node-mockit
```

```
36 error publish Failed PUT 403
37 verbose stack Error: no_perms can't publish non-scoped package, please set `config.scopes`: node-mockit
```

It looks as if cnpmjs now requires you to publish to a scope, so I'd take a look at its documentation, or ask cnpmjs's maintainers for help understanding its publishing rules. Good luck!

**Comment by ipconfiger** [comment]
thx, i change registry to http://registry.npmjs.org, it works
