### ISSUE TITLE
Error while trying to Install Termainal-Plus (only happens with this package)

### ISSUE THREAD

**Issue by JestonBlu** [npm/npm#10086]
```
npm WARN addRemoteGit Error: Command failed: 
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:658:15)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:98:17)
npm WARN addRemoteGit     at maybeClose (child_process.js:766:16)
npm WARN addRemoteGit     at Socket.<anonymous> (child_process.js:979:11)
npm WARN addRemoteGit     at Socket.emit (events.js:95:17)
npm WARN addRemoteGit     at Pipe.close (net.js:466:12)
npm WARN addRemoteGit  git+https://github.com/jeremyramin/pty.js.git#3e9c58 resetting remote C:\Users\Joseph\.atom\.apm\_git-remotes\https-github-com-jeremyramin-pty-js-git-27ad4d30 because of error: { [Error: Command failed: ] killed: false, code: 1, signal: null }
npm ERR! git fetch -a origin (https://github.com/jeremyramin/term.js.git) fatal: unable to access 'https://github.com/jeremyramin/term.js.git/': SSL certificate problem: unable to get local issuer certificate
npm ERR! git clone --template=C:\Users\Joseph\.atom\.apm\_git-remotes\_templates --mirror https://github.com/jeremyramin/pty.js.git C:\Users\Joseph\.atom\.apm\_git-remotes\https-github-com-jeremyramin-pty-js-git-27ad4d30: Cloning into bare repository 'C:\Users\Joseph\.atom\.apm\_git-remotes\https-github-com-jeremyramin-pty-js-git-27ad4d30'...
npm ERR! git clone --template=C:\Users\Joseph\.atom\.apm\_git-remotes\_templates --mirror https://github.com/jeremyramin/pty.js.git C:\Users\Joseph\.atom\.apm\_git-remotes\https-github-com-jeremyramin-pty-js-git-27ad4d30: fatal: unable to access 'https://github.com/jeremyramin/pty.js.git/': SSL certificate problem: unable to get local issuer certificate
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\Joseph\\AppData\\Local\\atom\\app-1.0.19\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Joseph\\AppData\\Local\\atom\\app-1.0.19\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Joseph\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Joseph\\.atom\\.apmrc" "install" "C:\\Users\\Joseph\\AppData\\Local\\Temp\\d-115922-5196-1r145ep\\package.tgz" "--target=0.30.7" "--arch=ia32" "--msvs_version=2013"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code 128

npm ERR! Command failed: fatal: unable to access 'https://github.com/jeremyramin/term.js.git/': SSL certificate problem: unable to get local issuer certificate
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

**Comment by othiym23** [comment]
```
npm ERR! git fetch -a origin (https://github.com/jeremyramin/term.js.git) fatal: unable to access 'https://github.com/jeremyramin/term.js.git/': SSL certificate problem: unable to get local issuer certificate
```

Is there something sitting between the system on which you're running the install and GitHub, like a proxy, that might be intercepting HTTPS traffic? Do you need to [configure git to use ssh instead of HTTPS](https://github.com/npm/npm/wiki/Troubleshooting#npm-only-uses-git-and-sshgit-urls-for-github-repos-breaking-proxies) (just reverse the `.insteadOf` declarations to go to ssh instead of HTTPS)? Or do you need to [set up a proxy for git](http://stackoverflow.com/questions/783811/getting-git-to-work-with-a-proxy-server)?

**Comment by JestonBlu** [comment]
No, im running the command from my home network... im also able to install other packages with no problems.

**Comment by JestonBlu** [comment]
I did verify that I am using ssh rather than https.

**Comment by JestonBlu** [comment]
This appears to be a system issue on my part, closing...

**Comment by JestonBlu** [comment]
Figured it out... i had upgraded to the new Git version that installs into Program Files\Git rather than Program Files (x86)\Git.  The PATH variable was out of date.
