### ISSUE TITLE
Error while installing Corodova

### ISSUE THREAD

**Issue by SantoshAvaji** [npm/npm#10093]
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'view',
1 verbose cli   'npm',
1 verbose cli   'version' ]
2 info using npm@2.14.7
3 info using node@v4.2.1
4 verbose config Skipping project config: C:\Users\myname/.npmrc. (matches userconfig)
5 silly mapToRegistry name npm
6 silly mapToRegistry using default registry
7 silly mapToRegistry registry https://registry.npmjs.org/
8 silly mapToRegistry uri https://registry.npmjs.org/npm
9 verbose request uri https://registry.npmjs.org/npm
10 verbose request no auth needed
11 info attempt registry request try #1 at 5:18:16 PM
12 verbose request id 65558abe5935b911
13 http request GET https://registry.npmjs.org/npm
14 info retry will retry, error on last attempt: Error: connect ETIMEDOUT 103.245.222.162:443
15 info attempt registry request try #2 at 5:18:47 PM
16 http request GET https://registry.npmjs.org/npm
17 info retry will retry, error on last attempt: Error: connect ETIMEDOUT 103.245.222.162:443
18 info attempt registry request try #3 at 5:20:08 PM
19 http request GET https://registry.npmjs.org/npm
20 verbose stack Error: connect ETIMEDOUT 103.245.222.162:443
20 verbose stack     at Object.exports._errnoException (util.js:874:11)
20 verbose stack     at exports._exceptionWithHostPort (util.js:897:20)
20 verbose stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)
21 verbose cwd C:\Users\myname
22 error Windows_NT 6.1.7601
23 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "view" "npm" "version"
24 error node v4.2.1
25 error npm  v2.14.7
26 error code ETIMEDOUT
27 error errno ETIMEDOUT
28 error syscall connect
29 error network connect ETIMEDOUT 103.245.222.162:443
29 error network This is most likely not a problem with npm itself
29 error network and is related to network connectivity.
29 error network In most cases you are behind a proxy or have bad network settings.
29 error network
29 error network If you are behind a proxy, please make sure that the
29 error network 'proxy' config is set properly.  See: 'npm help config'
30 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
@SantoshAvaji Is this still an issue for you?

**Comment by KenanY** [comment]
Closing as abandoned.
