### ISSUE TITLE
please help me, dont install gulp

### ISSUE THREAD

**Issue by dsainst** [npm/npm#10094]
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '--save-dev',
1 verbose cli   'gulp' ]
2 info using npm@2.14.4
3 info using node@v4.1.1
4 verbose install initial load of C:\dev\CVGSHOP\package.json
5 verbose stack Error: Invalid version: "1.0"
5 verbose stack     at Object.module.exports.fixVersionField (C:\Program Files\nodejs\node_modules\npm\node_modules\normalize-package-data\lib\fixer.js:186:13)
5 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\normalize-package-data\lib\normalize.js:32:38
5 verbose stack     at Array.forEach (native)
5 verbose stack     at normalize (C:\Program Files\nodejs\node_modules\npm\node_modules\normalize-package-data\lib\normalize.js:31:15)
5 verbose stack     at final (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:338:5)
5 verbose stack     at then (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:113:5)
5 verbose stack     at ReadFileContext.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:284:20)
5 verbose stack     at ReadFileContext.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:76:16)
5 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:303:13)
6 verbose cwd C:\dev\CVGSHOP
7 error Windows_NT 10.0.10240
8 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save-dev" "gulp"
9 error node v4.1.1
10 error npm  v2.14.4
11 error Invalid version: "1.0"
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]
```

**Comment by aredridel** [comment]
Looks like you need to fix the version in your `package.json` -- version numbers are 3 parts, not 2. try `1.0.0`

**Comment by dsainst** [comment]
oh, thank you!

**Comment by KenanY** [comment]
Closing as resolved.
