### ISSUE TITLE
Not able to install bower in window 10

### ISSUE THREAD

**Issue by thakur1984** [npm/npm#10102]
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'bower' ]
2 info using npm@2.14.7
3 info using node@v4.2.1
4 verbose install initial load of C:\Users\Thakur\AppData\Roaming\npm\package.json
5 verbose readDependencies loading dependencies from C:\Users\Thakur\AppData\Roaming\npm\package.json
6 silly cache add args [ 'bower', null ]
7 verbose cache add spec bower
8 silly cache add parsed spec Result {
8 silly cache add   raw: 'bower',
8 silly cache add   scope: null,
8 silly cache add   name: 'bower',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: '*',
8 silly cache add   type: 'range' }
9 silly addNamed bower@*
10 verbose addNamed "*" is a valid semver range for bower
11 silly addNameRange { name: 'bower', range: '*', hasData: false }
12 silly mapToRegistry name bower
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/bower
16 verbose addNameRange registry:https://registry.npmjs.org/bower not in flight; fetching
17 verbose request uri https://registry.npmjs.org/bower
18 verbose request no auth needed
19 info attempt registry request try #1 at 4:11:34 PM
20 verbose request id 16e50dd98813b7dc
21 verbose etag "5MHYE3BLWCSY63ZPMPKJLPG5C"
22 http request GET https://registry.npmjs.org/bower
23 http 304 https://registry.npmjs.org/bower
24 verbose headers { date: 'Sat, 24 Oct 2015 10:41:35 GMT',
24 verbose headers   via: '1.1 varnish',
24 verbose headers   'cache-control': 'max-age=60',
24 verbose headers   etag: '"5MHYE3BLWCSY63ZPMPKJLPG5C"',
24 verbose headers   age: '11',
24 verbose headers   connection: 'keep-alive',
24 verbose headers   'x-served-by': 'cache-sin6920-SIN',
24 verbose headers   'x-cache': 'HIT',
24 verbose headers   'x-cache-hits': '1',
24 verbose headers   'x-timer': 'S1445683295.973493,VS0,VE0',
24 verbose headers   vary: 'Accept' }
25 silly get cb [ 304,
25 silly get   { date: 'Sat, 24 Oct 2015 10:41:35 GMT',
25 silly get     via: '1.1 varnish',
25 silly get     'cache-control': 'max-age=60',
25 silly get     etag: '"5MHYE3BLWCSY63ZPMPKJLPG5C"',
25 silly get     age: '11',
25 silly get     connection: 'keep-alive',
25 silly get     'x-served-by': 'cache-sin6920-SIN',
25 silly get     'x-cache': 'HIT',
25 silly get     'x-cache-hits': '1',
25 silly get     'x-timer': 'S1445683295.973493,VS0,VE0',
25 silly get     vary: 'Accept' } ]
26 verbose etag https://registry.npmjs.org/bower from cache
27 verbose get saving bower to C:\Users\Thakur\AppData\Roaming\npm-cache\registry.npmjs.org\bower\.cache.json
28 silly addNameRange number 2 { name: 'bower', range: '*', hasData: true }
29 silly addNameRange versions [ 'bower',
29 silly addNameRange   [ '0.1.0',
29 silly addNameRange     '0.1.2',
29 silly addNameRange     '0.1.3',
29 silly addNameRange     '0.2.0',
29 silly addNameRange     '0.3.0',
29 silly addNameRange     '0.3.1',
29 silly addNameRange     '0.3.2',
29 silly addNameRange     '0.4.0',
29 silly addNameRange     '0.5.0',
29 silly addNameRange     '0.5.1',
29 silly addNameRange     '0.6.0',
29 silly addNameRange     '0.6.1',
29 silly addNameRange     '0.6.2',
29 silly addNameRange     '0.6.3',
29 silly addNameRange     '0.6.4',
29 silly addNameRange     '0.6.5',
29 silly addNameRange     '0.6.6',
29 silly addNameRange     '0.6.7',
29 silly addNameRange     '0.6.8',
29 silly addNameRange     '0.7.0',
29 silly addNameRange     '0.7.1',
29 silly addNameRange     '0.8.0',
29 silly addNameRange     '0.8.1',
29 silly addNameRange     '0.8.2',
29 silly addNameRange     '0.8.3',
29 silly addNameRange     '0.8.4',
29 silly addNameRange     '0.8.5',
29 silly addNameRange     '0.8.6',
29 silly addNameRange     '0.9.0',
29 silly addNameRange     '0.9.1',
29 silly addNameRange     '0.9.2',
29 silly addNameRange     '0.10.0',
29 silly addNameRange     '1.0.0',
29 silly addNameRange     '1.0.1',
29 silly addNameRange     '1.0.2',
29 silly addNameRange     '1.0.3',
29 silly addNameRange     '1.1.0',
29 silly addNameRange     '1.1.1',
29 silly addNameRange     '1.1.2',
29 silly addNameRange     '1.2.0',
29 silly addNameRange     '1.2.1',
29 silly addNameRange     '1.2.2',
29 silly addNameRange     '1.2.3',
29 silly addNameRange     '1.2.4',
29 silly addNameRange     '1.2.5',
29 silly addNameRange     '1.2.6',
29 silly addNameRange     '1.2.7',
29 silly addNameRange     '1.2.8',
29 silly addNameRange     '1.3.0',
29 silly addNameRange     '1.3.1',
29 silly addNameRange     '1.3.2',
29 silly addNameRange     '1.3.3',
29 silly addNameRange     '1.3.4',
29 silly addNameRange     '1.3.5',
29 silly addNameRange     '1.3.6',
29 silly addNameRange     '1.3.7',
29 silly addNameRange     '1.3.8',
29 silly addNameRange     '1.3.9',
29 silly addNameRange     '1.3.10',
29 silly addNameRange     '1.3.11',
29 silly addNameRange     '1.3.12',
29 silly addNameRange     '1.4.0',
29 silly addNameRange     '1.4.1',
29 silly addNameRange     '1.5.0',
29 silly addNameRange     '1.5.1',
29 silly addNameRange     '1.5.2',
29 silly addNameRange     '1.5.3',
29 silly addNameRange     '1.6.2',
29 silly addNameRange     '1.6.3',
29 silly addNameRange     '1.6.4',
29 silly addNameRange     '1.6.5' ] ]
30 silly addNamed bower@1.6.5
31 verbose addNamed "1.6.5" is a plain semver version for bower
32 silly mapToRegistry name bower
33 silly mapToRegistry using default registry
34 silly mapToRegistry registry https://registry.npmjs.org/
35 silly mapToRegistry uri https://registry.npmjs.org/bower
36 verbose addRemoteTarball https://registry.npmjs.org/bower/-/bower-1.6.5.tgz not in flight; adding
37 verbose addRemoteTarball [ 'https://registry.npmjs.org/bower/-/bower-1.6.5.tgz',
37 verbose addRemoteTarball   '59d457122a161e42cc1625bbab8179c214b7ac11' ]
38 info retry fetch attempt 1 at 4:11:36 PM
39 info attempt registry request try #1 at 4:11:36 PM
40 http fetch GET https://registry.npmjs.org/bower/-/bower-1.6.5.tgz
41 http fetch 200 https://registry.npmjs.org/bower/-/bower-1.6.5.tgz
42 info retry will retry, error on last attempt: Error: read ECONNRESET
43 info retry will retry, error on last attempt: Error: read ECONNRESET
44 silly fetchAndShaCheck shasum 59d457122a161e42cc1625bbab8179c214b7ac11
45 verbose stack Error: shasum check failed for C:\Users\Thakur\AppData\Local\Temp\npm-4860-944ee5f4\registry.npmjs.org\bower\-\bower-1.6.5.tgz
45 verbose stack Expected: 59d457122a161e42cc1625bbab8179c214b7ac11
45 verbose stack Actual:   346866eb37770c0f8e9ffac8fc864c9fda9554b8
45 verbose stack From:     https://registry.npmjs.org/bower/-/bower-1.6.5.tgz
45 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\sha\index.js:25:8
45 verbose stack     at ReadStream.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\sha\index.js:72:7)
45 verbose stack     at emitNone (events.js:72:20)
45 verbose stack     at ReadStream.emit (events.js:166:7)
45 verbose stack     at endReadableNT (_stream_readable.js:903:12)
45 verbose stack     at doNTCallback2 (node.js:439:9)
45 verbose stack     at process._tickCallback (node.js:353:17)
46 verbose cwd D:\Project\GitHub\Frontend
47 error Windows_NT 10.0.10240
48 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "bower"
49 error node v4.2.1
50 error npm  v2.14.7
51 error shasum check failed for C:\Users\Thakur\AppData\Local\Temp\npm-4860-944ee5f4\registry.npmjs.org\bower\-\bower-1.6.5.tgz
51 error Expected: 59d457122a161e42cc1625bbab8179c214b7ac11
51 error Actual:   346866eb37770c0f8e9ffac8fc864c9fda9554b8
51 error From:     https://registry.npmjs.org/bower/-/bower-1.6.5.tgz
52 error If you need help, you may report this error at:
52 error     <https://github.com/npm/npm/issues>
53 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
@thakur1984 Have you tried `npm cache clean`?

**Comment by thakur1984** [comment]
No.But It is working now.I have not done anything.

**Comment by KenanY** [comment]
@thakur1984 I'm glad to finally hear that :)
