### ISSUE TITLE
Npm proxy issue

### ISSUE THREAD

**Issue by amad4biz** [npm/npm#10144]
I am getting the error below when trying to set the npm behind proxy: please assist

nodejs V: V0.12.7
npm v: 2.11.3
I have already done this
npm config set https-proxy http://"username:password"@proxy-internet.cio.state.nyenet:80 . I put username and password in doublw quotes because I have %@ and other character but I am eceiveing this..

URIError: URI malformed
    at decodeURIComponent (native)
    at Url.parse (url.js:195:19)
    at Object.urlParse [as parse] (url.js:84:5)
    at Object.validateUrl [as validate] (C:\Program Files\nodejs\node_modules\np
m\node_modules\nopt\lib\nopt.js:164:13)
    at validate (C:\Program Files\nodejs\node_modules\npm\node_modules\nopt\lib\
nopt.js:212:24)
    at validate (C:\Program Files\nodejs\node_modules\npm\node_modules\nopt\lib\
nopt.js:179:11)
    at C:\Program Files\nodejs\node_modules\npm\node_modules\nopt\lib\nopt.js:10
1:12
    at Array.map (native)
    at C:\Program Files\nodejs\node_modules\npm\node_modules\nopt\lib\nopt.js:67
:15
    at Array.forEach (native)

C:\Program Files\nodejs\node_modules\npm\lib\npm.js:29
    throw new Error('npm.load() required')
    ^

Error: npm.load() required
    at Object.npm.config.get (C:\Program Files\nodejs\node_modules\npm\lib\npm.j
s:29:11)
    at exit (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js
:58:40)
    at process.errorHandler (C:\Program Files\nodejs\node_modules\npm\lib\utils\
error-handler.js:385:3)
    at emitOne (events.js:77:13)
    at process.emit (events.js:169:7)
    at process._fatalException (node.js:221:26)
URIError: URI malformed
    at decodeURIComponent (native)
    at Url.parse (url.js:195:19)
    at Object.urlParse [as parse] (url.js:84:5)
    at Object.validateUrl [as validate] (C:\Program Files\nodejs\node_modules\np
m\node_modules\nopt\lib\nopt.js:164:13)
    at validate (C:\Program Files\nodejs\node_modules\npm\node_modules\nopt\lib\
nopt.js:212:24)
    at validate (C:\Program Files\nodejs\node_modules\npm\node_modules\nopt\lib\
nopt.js:179:11)
    at C:\Program Files\nodejs\node_modules\npm\node_modules\nopt\lib\nopt.js:10
1:12
    at Array.map (native)
    at C:\Program Files\nodejs\node_modules\npm\node_modules\nopt\lib\nopt.js:67
:15
    at Array.forEach (native)

C:\Program Files\nodejs\node_modules\npm\lib\npm.js:29
    throw new Error('npm.load() required')
    ^

Error: npm.load() required
    at Object.npm.config.get (C:\Program Files\nodejs\node_modules\npm\lib\npm.j
s:29:11)
    at exit (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js
:58:40)
    at process.errorHandler (C:\Program Files\nodejs\node_modules\npm\lib\utils\
error-handler.js:385:3)
    at emitOne (events.js:77:13)
    at process.emit (events.js:169:7)
    at process._fatalException (node.js:221:26)

C:\Users\BIZMIN>npm install -g gulp
URIError: URI malformed
    at decodeURIComponent (native)
    at Url.parse (url.js:195:19)
    at Object.urlParse [as parse] (url.js:84:5)
    at Object.validateUrl [as validate] (C:\Program Files\nodejs\node_modules\np
m\node_modules\nopt\lib\nopt.js:164:13)
    at validate (C:\Program Files\nodejs\node_modules\npm\node_modules\nopt\lib\
nopt.js:212:24)
    at validate (C:\Program Files\nodejs\node_modules\npm\node_modules\nopt\lib\
nopt.js:179:11)
    at C:\Program Files\nodejs\node_modules\npm\node_modules\nopt\lib\nopt.js:10
1:12
    at Array.map (native)
    at C:\Program Files\nodejs\node_modules\npm\node_modules\nopt\lib\nopt.js:67
:15
    at Array.forEach (native)

C:\Program Files\nodejs\node_modules\npm\lib\npm.js:29
    throw new Error('npm.load() required')
    ^

Error: npm.load() required
    at Object.npm.config.get (C:\Program Files\nodejs\node_modules\npm\lib\npm.j
s:29:11)
    at exit (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js
:58:40)
    at process.errorHandler (C:\Program Files\nodejs\node_modules\npm\lib\utils\
error-handler.js:385:3)
    at emitOne (events.js:77:13)
    at process.emit (events.js:169:7)
    at process._fatalException (node.js:221:26)
URIError: URI malformed
    at decodeURIComponent (native)
    at Url.parse (url.js:195:19)
    at Object.urlParse [as parse] (url.js:84:5)
    at Object.validateUrl [as validate] (C:\Program Files\nodejs\node_modules\np
m\node_modules\nopt\lib\nopt.js:164:13)
    at validate (C:\Program Files\nodejs\node_modules\npm\node_modules\nopt\lib\
nopt.js:212:24)
    at validate (C:\Program Files\nodejs\node_modules\npm\node_modules\nopt\lib\
nopt.js:179:11)
    at C:\Program Files\nodejs\node_modules\npm\node_modules\nopt\lib\nopt.js:10
1:12
    at Array.map (native)
    at C:\Program Files\nodejs\node_modules\npm\node_modules\nopt\lib\nopt.js:67
:15
    at Array.forEach (native)

C:\Program Files\nodejs\node_modules\npm\lib\npm.js:29
    throw new Error('npm.load() required')
    ^

Error: npm.load() required
    at Object.npm.config.get (C:\Program Files\nodejs\node_modules\npm\lib\npm.j
s:29:11)
    at exit (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js
:58:40)
    at process.errorHandler (C:\Program Files\nodejs\node_modules\npm\lib\utils\
error-handler.js:385:3)
    at emitOne (events.js:77:13)
    at process.emit (events.js:169:7)
    at process._fatalException (node.js

**Comment by KenanY** [comment]
@amad4biz I am not very familiar with the spec, but shouldn't you be percent-encoding those characters rather than using double quotes?

https://tools.ietf.org/html/rfc3986
