### ISSUE TITLE
install bower 0.10.0 Error: ENOENT

### ISSUE THREAD

**Issue by vlatkop** [npm/npm#10160]
Hello,

When I try to install bower version 0.10.0 on nodejs version 0.10.12 with npm version 1.2.32, this error occurs:

```
npm ERR! Error: ENOENT, chown '/root/node/node/lib/node_modules/bower/node_modules/tar/lib/entry.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.10.0-229.1.2.el7.x86_64
npm ERR! command "/root/node/node/bin/node" "/root/node/node/bin/npm" "-g" "install" "bower@0.10.0"
npm ERR! cwd /root/node
npm ERR! node -v v0.10.12
npm ERR! npm -v 1.2.32
npm ERR! path /root/node/node/lib/node_modules/bower/node_modules/tar/lib/entry.js
npm ERR! fstream_path /root/node/node/lib/node_modules/bower/node_modules/tar/lib/entry.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! fstream_finish_call chown
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /root/node/node/lib/node_modules/npm/node_modules/fstream/lib/writer.js:305:19
npm ERR! fstream_stack /root/node/node/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:265:7
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! error rolling back Error: ENOTEMPTY, rmdir '/root/node/node/lib/node_modules/bower/node_modules/mkdirp/test'
npm ERR! error rolling back  bower@0.10.0 { [Error: ENOTEMPTY, rmdir '/root/node/node/lib/node_modules/bower/node_modules/mkdirp/test']
npm ERR! error rolling back   errno: 53,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   path: '/root/node/node/lib/node_modules/bower/node_modules/mkdirp/test' }
npm ERR! Error: No compatible version found: request@'^2.36.0'
npm ERR! Valid install targets:
npm ERR! ["0.10.0","0.8.3","0.9.0","0.9.1","0.9.5","1.0.0","1.1.0","1.1.1","1.2.0","1.9.0","1.9.1","1.9.2","1.9.3","1.9.5","1.9.7","1.9.8","1.9.9","2.0.0","2.0.1","2.0.2","2.0.3","2.0.4","2.0.5","2.1.0","2.1.1","2.2.0","2.2.5","2.2.6","2.2.9","2.9.0","2.9.1","2.9.2","2.9.3","2.9.100","2.9.150","2.9.151","2.9.152","2.9.153","2.9.200","2.9.201","2.9.202","2.9.203","2.10.0","2.11.0","2.11.1","2.11.2","2.11.3","2.11.4","2.12.0","2.14.0","2.16.0","2.16.2","2.16.4","2.16.6","2.18.0","2.19.0","2.20.0","2.21.0","2.22.0","2.23.0","2.24.0","2.25.0","2.26.0","2.27.0","2.28.0","2.29.0","2.30.0","2.31.0","2.32.0","2.33.0","2.34.0","2.35.0","2.36.0","2.37.0","2.38.0","2.39.0","2.40.0","2.41.0","2.42.0","2.43.0","2.44.0","2.45.0","2.46.0","2.47.0","2.48.0","2.49.0","2.50.0","2.51.0","2.52.0","2.53.0","2.54.0","2.55.0","2.56.0","2.57.0","2.58.0","2.59.0","2.60.0","2.61.0","2.62.0","2.63.0","2.64.0","2.65.0"]
npm ERR!     at installTargetsError (/root/node/node/lib/node_modules/npm/lib/cache.js:719:10)
npm ERR!     at /root/node/node/lib/node_modules/npm/lib/cache.js:641:10
npm ERR!     at RegClient.get_ (/root/node/node/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:101:14)
npm ERR!     at RegClient.<anonymous> (/root/node/node/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:37:12)
npm ERR!     at fs.js:266:14
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.10.0-229.1.2.el7.x86_64
npm ERR! command "/root/node/node/bin/node" "/root/node/node/bin/npm" "-g" "install" "bower@0.10.0"
npm ERR! cwd /root/node
npm ERR! node -v v0.10.12
npm ERR! npm -v 1.2.32
npm http GET https://registry.npmjs.org/read
npm ERR! Error: ENOENT, lstat '/root/node/node/lib/node_modules/bower/node_modules/glob/test/00-setup.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.10.0-229.1.2.el7.x86_64
npm ERR! command "/root/node/node/bin/node" "/root/node/node/bin/npm" "-g" "install" "bower@0.10.0"
npm ERR! cwd /root/node
npm ERR! node -v v0.10.12
npm ERR! npm -v 1.2.32
npm ERR! path /root/node/node/lib/node_modules/bower/node_modules/glob/test/00-setup.js
npm ERR! fstream_path /root/node/node/lib/node_modules/bower/node_modules/glob/test/00-setup.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /root/node/node/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm http GET https://registry.npmjs.org/minimist
npm http GET https://registry.npmjs.org/deep-extend
npm http GET https://registry.npmjs.org/ini
npm ERR! Error: ENOENT, lstat '/root/node/node/lib/node_modules/bower/node_modules/fstream/lib/dir-writer.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.10.0-229.1.2.el7.x86_64
npm ERR! command "/root/node/node/bin/node" "/root/node/node/bin/npm" "-g" "install" "bower@0.10.0"
npm ERR! cwd /root/node
npm ERR! node -v v0.10.12
npm ERR! npm -v 1.2.32
npm ERR! path /root/node/node/lib/node_modules/bower/node_modules/fstream/lib/dir-writer.js
npm ERR! fstream_path /root/node/node/lib/node_modules/bower/node_modules/fstream/lib/dir-writer.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /root/node/node/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm http 304 https://registry.npmjs.org/graceful-fs
npm ERR! Error: ENOENT, lstat '/root/node/node/lib/node_modules/bower/node_modules/tmp/test/file-test.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.10.0-229.1.2.el7.x86_64
npm ERR! command "/root/node/node/bin/node" "/root/node/node/bin/npm" "-g" "install" "bower@0.10.0"
npm ERR! cwd /root/node
npm ERR! node -v v0.10.12
npm ERR! npm -v 1.2.32
npm ERR! path /root/node/node/lib/node_modules/bower/node_modules/tmp/test/file-test.js
npm ERR! fstream_path /root/node/node/lib/node_modules/bower/node_modules/tmp/test/file-test.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /root/node/node/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat '/root/node/node/lib/node_modules/bower/node_modules/request/main.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.10.0-229.1.2.el7.x86_64
npm ERR! command "/root/node/node/bin/node" "/root/node/node/bin/npm" "-g" "install" "bower@0.10.0"
npm ERR! cwd /root/node
npm ERR! node -v v0.10.12
npm ERR! npm -v 1.2.32
npm ERR! path /root/node/node/lib/node_modules/bower/node_modules/request/main.js
npm ERR! fstream_path /root/node/node/lib/node_modules/bower/node_modules/request/main.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /root/node/node/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat '/root/node/node/lib/node_modules/bower/node_modules/semver/semver.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.10.0-229.1.2.el7.x86_64
npm ERR! command "/root/node/node/bin/node" "/root/node/node/bin/npm" "-g" "install" "bower@0.10.0"
npm ERR! cwd /root/node
npm ERR! node -v v0.10.12
npm ERR! npm -v 1.2.32
npm ERR! path /root/node/node/lib/node_modules/bower/node_modules/semver/semver.js
npm ERR! fstream_path /root/node/node/lib/node_modules/bower/node_modules/semver/semver.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /root/node/node/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat '/root/node/node/lib/node_modules/bower/node_modules/async/lib/async.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.10.0-229.1.2.el7.x86_64
npm ERR! command "/root/node/node/bin/node" "/root/node/node/bin/npm" "-g" "install" "bower@0.10.0"
npm ERR! cwd /root/node
npm ERR! node -v v0.10.12
npm ERR! npm -v 1.2.32
npm ERR! path /root/node/node/lib/node_modules/bower/node_modules/async/lib/async.js
npm ERR! fstream_path /root/node/node/lib/node_modules/bower/node_modules/async/lib/async.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /root/node/node/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm http 304 https://registry.npmjs.org/minimist
npm http 304 https://registry.npmjs.org/deep-extend
npm http 304 https://registry.npmjs.org/ini
npm http 304 https://registry.npmjs.org/read
npm ERR! Error: ENOENT, lstat '/root/node/node/lib/node_modules/bower/node_modules/lodash/dist/lodash.compat.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.10.0-229.1.2.el7.x86_64
npm ERR! command "/root/node/node/bin/node" "/root/node/node/bin/npm" "-g" "install" "bower@0.10.0"
npm ERR! cwd /root/node
npm ERR! node -v v0.10.12
npm ERR! npm -v 1.2.32
npm ERR! path /root/node/node/lib/node_modules/bower/node_modules/lodash/dist/lodash.compat.js
npm ERR! fstream_path /root/node/node/lib/node_modules/bower/node_modules/lodash/dist/lodash.compat.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /root/node/node/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm http GET https://registry.npmjs.org/mute-stream
npm http 304 https://registry.npmjs.org/mute-stream
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /root/node/npm-debug.log
npm ERR! not ok code 0
```

**Comment by KenanY** [comment]
@vlatkop Please update both [Node.js](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-node) and [`npm`](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) first.

**Comment by KenanY** [comment]
@vlatkop Are you still experiencing this issue with the latest, stable releases of Node.js and `npm`?

**Comment by vlatkop** [comment]
Hi @KenanY,

latest releases of nodejs are working great and the problem cannot be reproduced there. So, I would close this issue as solved.

Regards
