### ISSUE TITLE
typeerror Error: Missing required argument #1 when installing from git branch

### ISSUE THREAD

**Issue by marthakelly** [npm/npm#10163]
I can install from a git url just fine, but when I specify a branch like this:
`"react-modal": "git+ssh://gitolite@code.uber.internal:web/react-modal.git#cleanup"`

I get:
`typeerror Error: Missing required argument #1`

Here's my `npm-debug.log`:
```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/Users/MOTHRA/.nvm/v0.10.26/bin/npm', 'install' ]
2 info using npm@3.3.9
3 info using node@v0.10.26
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly install normalizeTree
8 silly loadCurrentTree Finishing
9 silly loadIdealTree Starting
10 silly install loadIdealTree
11 silly cloneCurrentTree Starting
12 silly install cloneCurrentTreeToIdealTree
13 silly cloneCurrentTree Finishing
14 silly loadShrinkwrap Starting
15 silly install loadShrinkwrap
16 silly loadShrinkwrap Finishing
17 silly loadAllDepsIntoIdealTree Starting
18 silly install loadAllDepsIntoIdealTree
19 silly fetchOtherPackageData react-modal@git+ssh://gitolite@code.uber.internal:web/react-modal.git#cleanup
20 silly cache add args [ 'react-modal@git+ssh://gitolite@code.uber.internal:web/react-modal.git#cleanup',
20 silly cache add   null ]
21 verbose cache add spec react-modal@git+ssh://gitolite@code.uber.internal:web/react-modal.git#cleanup
22 silly cache add parsed spec { raw: 'react-modal@git+ssh://gitolite@code.uber.internal:web/react-modal.git#cleanup',
22 silly cache add   scope: null,
22 silly cache add   name: 'react-modal',
22 silly cache add   rawSpec: 'git+ssh://gitolite@code.uber.internal:web/react-modal.git#cleanup',
22 silly cache add   spec: 'ssh://gitolite@code.uber.internal:web/react-modal.git#cleanup',
22 silly cache add   type: 'git' }
23 verbose addRemoteGit caching git+ssh://gitolite@code.uber.internal:web/react-modal.git#cleanup
24 silly tryClone cloning git+ssh://gitolite@code.uber.internal:web/react-modal.git#cleanup via git+ssh://gitolite@code.uber.internal:web/react-modal.git#cleanup
25 verbose tryClone git-ssh-gitolite-code-uber-internal-web-react-modal-git-cleanup-5d95a932b373db6fe4fe995c1a75cd1f not in flight; caching
26 info git [ 'config', '--get', 'remote.origin.url' ]
27 silly validateExistingRemote git+ssh://gitolite@code.uber.internal:web/react-modal.git#cleanup remote.origin.url: gitolite@code.uber.internal:web/react-modal.git
28 verbose validateExistingRemote git+ssh://gitolite@code.uber.internal:web/react-modal.git#cleanup is updating existing cached remote /Users/MOTHRA/.npm/_git-remotes/git-ssh-gitolite-code-uber-internal-web-react-modal-git-cleanup-5d95a932b373db6fe4fe995c1a75cd1f
29 info git [ 'fetch', '-a', 'origin' ]
30 verbose updateRemote git fetch -a origin (gitolite@code.uber.internal:web/react-modal.git)
31 verbose setPermissions git+ssh://gitolite@code.uber.internal:web/react-modal.git#cleanup set permissions on /Users/MOTHRA/.npm/_git-remotes/git-ssh-gitolite-code-uber-internal-web-react-modal-git-cleanup-5d95a932b373db6fe4fe995c1a75cd1f
32 verbose resolveHead git+ssh://gitolite@code.uber.internal:web/react-modal.git#cleanup original treeish: cleanup
33 info git [ 'rev-list', '-n1', 'cleanup' ]
34 silly resolveHead git+ssh://gitolite@code.uber.internal:web/react-modal.git#cleanup resolved treeish: 168f60730adc16730cf2633bce9f440c9b98ee22
35 verbose resolveHead git+ssh://gitolite@code.uber.internal:web/react-modal.git#cleanup resolved Git URL: git+ssh://gitolite@code.uber.internal:web/react-modal.git#168f60730adc16730cf2633bce9f440c9b98ee22
36 silly resolveHead Git working directory: /var/folders/57/sjw2_9rn3xnbjfy_mdx0trvm0000gn/T/npm-66613-e5463ae6/git-cache-f2802b0dd1b06f86d58014f915497f5d/168f60730adc16730cf2633bce9f440c9b98ee22
37 info git [ 'clone',
37 info git   '/Users/MOTHRA/.npm/_git-remotes/git-ssh-gitolite-code-uber-internal-web-react-modal-git-cleanup-5d95a932b373db6fe4fe995c1a75cd1f',
37 info git   '/var/folders/57/sjw2_9rn3xnbjfy_mdx0trvm0000gn/T/npm-66613-e5463ae6/git-cache-f2802b0dd1b06f86d58014f915497f5d/168f60730adc16730cf2633bce9f440c9b98ee22' ]
38 verbose cloneResolved git+ssh://gitolite@code.uber.internal:web/react-modal.git#cleanup clone Cloning into '/var/folders/57/sjw2_9rn3xnbjfy_mdx0trvm0000gn/T/npm-66613-e5463ae6/git-cache-f2802b0dd1b06f86d58014f915497f5d/168f60730adc16730cf2633bce9f440c9b98ee22'...
38 verbose cloneResolved done.
39 info git [ 'checkout', '168f60730adc16730cf2633bce9f440c9b98ee22' ]
40 verbose checkoutTreeish git+ssh://gitolite@code.uber.internal:web/react-modal.git#cleanup checkout Note: checking out '168f60730adc16730cf2633bce9f440c9b98ee22'.
40 verbose checkoutTreeish
40 verbose checkoutTreeish You are in 'detached HEAD' state. You can look around, make experimental
40 verbose checkoutTreeish changes and commit them, and you can discard any commits you make in this
40 verbose checkoutTreeish state without impacting any branches by performing another checkout.
40 verbose checkoutTreeish
40 verbose checkoutTreeish If you want to create a new branch to retain commits you create, you may
40 verbose checkoutTreeish do so (now or later) by using -b with the checkout command again. Example:
40 verbose checkoutTreeish
40 verbose checkoutTreeish   git checkout -b <new-branch-name>
40 verbose checkoutTreeish
40 verbose checkoutTreeish HEAD is now at 168f607... adding simple example to be imported into superfine docs
41 verbose addLocalDirectory /Users/MOTHRA/.npm/react-modal/3.0.0/package.tgz not in flight; packing
42 verbose tar pack [ '/Users/MOTHRA/.npm/react-modal/3.0.0/package.tgz',
42 verbose tar pack   '/var/folders/57/sjw2_9rn3xnbjfy_mdx0trvm0000gn/T/npm-66613-e5463ae6/git-cache-f2802b0dd1b06f86d58014f915497f5d/168f60730adc16730cf2633bce9f440c9b98ee22' ]
43 verbose tarball /Users/MOTHRA/.npm/react-modal/3.0.0/package.tgz
44 verbose folder /var/folders/57/sjw2_9rn3xnbjfy_mdx0trvm0000gn/T/npm-66613-e5463ae6/git-cache-f2802b0dd1b06f86d58014f915497f5d/168f60730adc16730cf2633bce9f440c9b98ee22
45 verbose addLocalTarball adding from inside cache /Users/MOTHRA/.npm/react-modal/3.0.0/package.tgz
46 verbose addRemoteGit data._from: git+ssh://gitolite@code.uber.internal:web/react-modal.git#cleanup
47 verbose addRemoteGit data._resolved: git+ssh://gitolite@code.uber.internal:web/react-modal.git#168f60730adc16730cf2633bce9f440c9b98ee22
48 silly cache afterAdd react-modal@3.0.0
49 verbose afterAdd /Users/MOTHRA/.npm/react-modal/3.0.0/package/package.json not in flight; writing
50 verbose afterAdd /Users/MOTHRA/.npm/react-modal/3.0.0/package/package.json written
51 verbose stack Error: Missing required argument #1
51 verbose stack     at andLogAndFinish (/Users/MOTHRA/.nvm/v0.10.26/lib/node_modules/npm/lib/fetch-package-metadata.js:30:3)
51 verbose stack     at fetchPackageMetadata (/Users/MOTHRA/.nvm/v0.10.26/lib/node_modules/npm/lib/fetch-package-metadata.js:50:22)
51 verbose stack     at resolveWithNewModule (/Users/MOTHRA/.nvm/v0.10.26/lib/node_modules/npm/lib/install/deps.js:406:12)
51 verbose stack     at /Users/MOTHRA/.nvm/v0.10.26/lib/node_modules/npm/lib/install/deps.js:407:7
51 verbose stack     at /Users/MOTHRA/.nvm/v0.10.26/lib/node_modules/npm/node_modules/iferr/index.js:13:50
51 verbose stack     at /Users/MOTHRA/.nvm/v0.10.26/lib/node_modules/npm/lib/fetch-package-metadata.js:36:12
51 verbose stack     at addRequestedAndFinish (/Users/MOTHRA/.nvm/v0.10.26/lib/node_modules/npm/lib/fetch-package-metadata.js:72:5)
51 verbose stack     at /Users/MOTHRA/.nvm/v0.10.26/lib/node_modules/npm/lib/fetch-package-metadata.js:82:5
51 verbose stack     at /Users/MOTHRA/.nvm/v0.10.26/lib/node_modules/npm/node_modules/iferr/index.js:13:50
51 verbose stack     at RES (/Users/MOTHRA/.nvm/v0.10.26/lib/node_modules/npm/node_modules/inflight/inflight.js:23:14)
52 verbose cwd /Users/MOTHRA/Uber/superfine-docs
53 error Darwin 14.3.0
54 error argv "node" "/Users/MOTHRA/.nvm/v0.10.26/bin/npm" "install"
55 error node v0.10.26
56 error npm  v3.3.9
57 error code EMISSINGARG
58 error typeerror Error: Missing required argument #1
58 error typeerror     at andLogAndFinish (/Users/MOTHRA/.nvm/v0.10.26/lib/node_modules/npm/lib/fetch-package-metadata.js:30:3)
58 error typeerror     at fetchPackageMetadata (/Users/MOTHRA/.nvm/v0.10.26/lib/node_modules/npm/lib/fetch-package-metadata.js:50:22)
58 error typeerror     at resolveWithNewModule (/Users/MOTHRA/.nvm/v0.10.26/lib/node_modules/npm/lib/install/deps.js:406:12)
58 error typeerror     at /Users/MOTHRA/.nvm/v0.10.26/lib/node_modules/npm/lib/install/deps.js:407:7
58 error typeerror     at /Users/MOTHRA/.nvm/v0.10.26/lib/node_modules/npm/node_modules/iferr/index.js:13:50
58 error typeerror     at /Users/MOTHRA/.nvm/v0.10.26/lib/node_modules/npm/lib/fetch-package-metadata.js:36:12
58 error typeerror     at addRequestedAndFinish (/Users/MOTHRA/.nvm/v0.10.26/lib/node_modules/npm/lib/fetch-package-metadata.js:72:5)
58 error typeerror     at /Users/MOTHRA/.nvm/v0.10.26/lib/node_modules/npm/lib/fetch-package-metadata.js:82:5
58 error typeerror     at /Users/MOTHRA/.nvm/v0.10.26/lib/node_modules/npm/node_modules/iferr/index.js:13:50
58 error typeerror     at RES (/Users/MOTHRA/.nvm/v0.10.26/lib/node_modules/npm/node_modules/inflight/inflight.js:23:14)
58 error typeerror This is an error with npm itself. Please report this error at:
58 error typeerror     <http://github.com/npm/npm/issues>
59 verbose exit [ 1, true ]
```

**Comment by lxe** [comment]
@marthakelly this happens because 'type' key requires a certain schema that npm3 expects. This is still an npm bug though... it should catch the error before it hits that the depth.
