### ISSUE TITLE
Cannot read property 'localeCompare' of undefined

### ISSUE THREAD

**Issue by optimisme** [npm/npm#10169]
Trying to install node 5.0.0 on OpenShift with 'aws-sdk', 'archiver' and 'mkpath' modules. I got the pasted 'npm-debug.log':

```
0 info it worked if it ends with ok
1 verbose cli [ '/var/lib/openshift/xxxxxxxxxxxxxxxxxxxxxxx/app-root/data/node-v5.0.0-linux-x64/bin/node',
1 verbose cli   '/var/lib/openshift/xxxxxxxxxxxxxxxxxxxxxxx/app-root/data/node-v5.0.0-linux-x64/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-d' ]
2 info using npm@3.3.6
3 info using node@v5.0.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly install normalizeTree
8 silly loadCurrentTree Finishing
9 silly loadIdealTree Starting
10 silly install loadIdealTree
11 silly cloneCurrentTree Starting
12 silly install cloneCurrentTreeToIdealTree
13 silly cloneCurrentTree Finishing
14 silly loadShrinkwrap Starting
15 silly install loadShrinkwrap
16 silly loadShrinkwrap Finishing
17 silly loadAllDepsIntoIdealTree Starting
18 silly install loadAllDepsIntoIdealTree
19 silly fetchNamedPackageData aws-sdk
20 silly mapToRegistry name aws-sdk
21 silly mapToRegistry using default registry
22 silly mapToRegistry registry https://registry.npmjs.org/
23 silly mapToRegistry uri https://registry.npmjs.org/aws-sdk
24 verbose request uri https://registry.npmjs.org/aws-sdk
25 verbose request no auth needed
26 info attempt registry request try #1 at 2:55:38 AM
27 verbose request id 13e2264e512edecb
28 verbose etag "3TJ1J1CNXM2IO3MCWPQ606GE"
29 http request GET https://registry.npmjs.org/aws-sdk
30 http 200 https://registry.npmjs.org/aws-sdk
31 verbose headers { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
31 verbose headers   etag: '"1WPBOWHNG4OHFMQ5TQYAP1WMG"',
31 verbose headers   'content-type': 'application/json',
31 verbose headers   'cache-control': 'max-age=60',
31 verbose headers   'content-length': '347175',
31 verbose headers   'accept-ranges': 'bytes',
31 verbose headers   date: 'Fri, 30 Oct 2015 06:55:38 GMT',
31 verbose headers   via: '1.1 varnish',
31 verbose headers   age: '0',
31 verbose headers   connection: 'keep-alive',
31 verbose headers   'x-served-by': 'cache-jfk1025-JFK',
31 verbose headers   'x-cache': 'HIT',
31 verbose headers   'x-cache-hits': '1',
31 verbose headers   'x-timer': 'S1446188138.307577,VS0,VE85',
31 verbose headers   vary: 'Accept' }
32 silly get cb [ 200,
32 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
32 silly get     etag: '"1WPBOWHNG4OHFMQ5TQYAP1WMG"',
32 silly get     'content-type': 'application/json',
32 silly get     'cache-control': 'max-age=60',
32 silly get     'content-length': '347175',
32 silly get     'accept-ranges': 'bytes',
32 silly get     date: 'Fri, 30 Oct 2015 06:55:38 GMT',
32 silly get     via: '1.1 varnish',
32 silly get     age: '0',
32 silly get     connection: 'keep-alive',
32 silly get     'x-served-by': 'cache-jfk1025-JFK',
32 silly get     'x-cache': 'HIT',
32 silly get     'x-cache-hits': '1',
32 silly get     'x-timer': 'S1446188138.307577,VS0,VE85',
32 silly get     vary: 'Accept' } ]
33 verbose get saving aws-sdk to /var/lib/openshift/xxxxxxxxxxxxxxxxxxxxxxx/.npm/registry.npmjs.org/aws-sdk/.cache.json
34 silly resolveWithNewModule aws-sdk@2.2.13 checking installable status
35 silly cache add args [ 'aws-sdk@~2.2.10', null ]
36 verbose cache add spec aws-sdk@~2.2.10
37 silly cache add parsed spec Result {
37 silly cache add   raw: 'aws-sdk@~2.2.10',
37 silly cache add   scope: null,
37 silly cache add   name: 'aws-sdk',
37 silly cache add   rawSpec: '~2.2.10',
37 silly cache add   spec: '>=2.2.10 <2.3.0',
37 silly cache add   type: 'range' }
38 silly addNamed aws-sdk@>=2.2.10 <2.3.0
39 verbose addNamed ">=2.2.10 <2.3.0" is a valid semver range for aws-sdk
40 silly addNameRange { name: 'aws-sdk', range: '>=2.2.10 <2.3.0', hasData: false }
41 silly mapToRegistry name aws-sdk
42 silly mapToRegistry using default registry
43 silly mapToRegistry registry https://registry.npmjs.org/
44 silly mapToRegistry uri https://registry.npmjs.org/aws-sdk
45 verbose addNameRange registry:https://registry.npmjs.org/aws-sdk not in flight; fetching
46 verbose get https://registry.npmjs.org/aws-sdk not expired, no request
47 silly addNameRange number 2 { name: 'aws-sdk', range: '>=2.2.10 <2.3.0', hasData: true }
48 silly addNameRange versions [ 'aws-sdk',
48 silly addNameRange   [ '0.9.0-pre.1',
48 silly addNameRange     '0.9.1-pre.2',
48 silly addNameRange     '0.9.2-pre.3',
48 silly addNameRange     '0.9.3-pre.4',
48 silly addNameRange     '0.9.4-pre.5',
48 silly addNameRange     '0.9.5-pre.6',
48 silly addNameRange     '0.9.6-pre.7',
48 silly addNameRange     '0.9.7-pre.8',
48 silly addNameRange     '0.9.8-pre.9',
48 silly addNameRange     '0.9.9-pre.10',
48 silly addNameRange     '1.0.0',
48 silly addNameRange     '1.1.0',
48 silly addNameRange     '1.2.0',
48 silly addNameRange     '1.3.0',
48 silly addNameRange     '1.3.1',
48 silly addNameRange     '1.3.2',
48 silly addNameRange     '1.4.0',
48 silly addNameRange     '1.4.1',
48 silly addNameRange     '1.5.0',
48 silly addNameRange     '1.5.1',
48 silly addNameRange     '1.5.2',
48 silly addNameRange     '1.6.0',
48 silly addNameRange     '1.7.0',
48 silly addNameRange     '1.7.1',
48 silly addNameRange     '1.8.0',
48 silly addNameRange     '1.8.1',
48 silly addNameRange     '1.9.0',
48 silly addNameRange     '1.10.0',
48 silly addNameRange     '2.0.0-rc1',
48 silly addNameRange     '1.12.0',
48 silly addNameRange     '1.13.0',
48 silly addNameRange     '1.14.0',
48 silly addNameRange     '2.0.0-rc2',
48 silly addNameRange     '1.15.0',
48 silly addNameRange     '2.0.0-rc3',
48 silly addNameRange     '1.16.0',
48 silly addNameRange     '2.0.0-rc4',
48 silly addNameRange     '1.17.0',
48 silly addNameRange     '2.0.0-rc5',
48 silly addNameRange     '1.17.1',
48 silly addNameRange     '2.0.0-rc6',
48 silly addNameRange     '1.17.2',
48 silly addNameRange     '2.0.0-rc7',
48 silly addNameRange     '1.17.3',
48 silly addNameRange     '2.0.0-rc8',
48 silly addNameRange     '1.18.0',
48 silly addNameRange     '2.0.0-rc9',
48 silly addNameRange     '2.0.0-rc10',
48 silly addNameRange     '2.0.0-rc11',
48 silly addNameRange     '2.0.0-rc12',
48 silly addNameRange     '2.0.0-rc13',
48 silly addNameRange     '2.0.0-rc.14',
48 silly addNameRange     '2.0.0-rc.15',
48 silly addNameRange     '2.0.0-rc.16',
48 silly addNameRange     '2.0.0-rc.17',
48 silly addNameRange     '2.0.0-rc.18',
48 silly addNameRange     '2.0.0-rc.19',
48 silly addNameRange     '2.0.0-rc.20',
48 silly addNameRange     '2.0.1',
48 silly addNameRange     '2.0.2',
48 silly addNameRange     '2.0.3',
48 silly addNameRange     '2.0.4',
48 silly addNameRange     '2.0.5',
48 silly addNameRange     '2.0.6',
48 silly addNameRange     '2.0.7',
48 silly addNameRange     '2.0.8',
48 silly addNameRange     '2.0.9',
48 silly addNameRange     '2.0.10',
48 silly addNameRange     '2.0.11',
48 silly addNameRange     '2.0.12',
48 silly addNameRange     '2.0.13',
48 silly addNameRange     '2.0.14',
48 silly addNameRange     '2.0.15',
48 silly addNameRange     '2.0.16',
48 silly addNameRange     '2.0.17',
48 silly addNameRange     '2.0.18',
48 silly addNameRange     '2.0.19',
48 silly addNameRange     '2.0.21',
48 silly addNameRange     '2.0.22',
48 silly addNameRange     '2.0.23',
48 silly addNameRange     '2.0.24',
48 silly addNameRange     '2.0.25',
48 silly addNameRange     '2.0.26',
48 silly addNameRange     '2.0.27',
48 silly addNameRange     '2.0.28',
48 silly addNameRange     '2.0.29',
48 silly addNameRange     '2.0.30',
48 silly addNameRange     '2.0.31',
48 silly addNameRange     '2.1.0',
48 silly addNameRange     '2.1.1',
48 silly addNameRange     '2.1.2',
48 silly addNameRange     '2.1.3',
48 silly addNameRange     '2.1.4',
48 silly addNameRange     '2.1.5',
48 silly addNameRange     '2.1.6',
48 silly addNameRange     '2.1.7',
48 silly addNameRange     '2.1.8',
48 silly addNameRange     '2.1.9',
48 silly addNameRange     '2.1.10',
48 silly addNameRange     '2.1.11',
48 silly addNameRange     '2.1.12',
48 silly addNameRange     '2.1.13',
48 silly addNameRange     '2.1.14',
48 silly addNameRange     '2.1.15',
48 silly addNameRange     '2.1.16',
48 silly addNameRange     '2.1.17',
48 silly addNameRange     '2.1.18',
48 silly addNameRange     '2.1.19',
48 silly addNameRange     '2.1.20',
48 silly addNameRange     '2.1.21',
48 silly addNameRange     '2.1.22',
48 silly addNameRange     '2.1.23',
48 silly addNameRange     '2.1.24',
48 silly addNameRange     '2.1.25',
48 silly addNameRange     '2.1.26',
48 silly addNameRange     '2.1.27',
48 silly addNameRange     '2.1.28',
48 silly addNameRange     '2.1.29',
48 silly addNameRange     '2.1.30',
48 silly addNameRange     '2.1.31',
48 silly addNameRange     '2.1.32',
48 silly addNameRange     '2.1.33',
48 silly addNameRange     '2.1.34',
48 silly addNameRange     '2.1.35',
48 silly addNameRange     '2.1.36',
48 silly addNameRange     '2.1.37',
48 silly addNameRange     '2.1.38',
48 silly addNameRange     '2.1.39',
48 silly addNameRange     '2.1.40',
48 silly addNameRange     '2.1.41',
48 silly addNameRange     '2.1.42',
48 silly addNameRange     '2.1.43',
48 silly addNameRange     '2.1.44',
48 silly addNameRange     '2.1.45',
48 silly addNameRange     '2.1.46',
48 silly addNameRange     '2.1.47',
48 silly addNameRange     '2.1.48',
48 silly addNameRange     '2.1.49',
48 silly addNameRange     '2.1.50',
48 silly addNameRange     '2.2.0',
48 silly addNameRange     '2.2.1',
48 silly addNameRange     '2.2.2',
48 silly addNameRange     '2.2.3',
48 silly addNameRange     '2.2.4',
48 silly addNameRange     '2.2.5',
48 silly addNameRange     '2.2.6',
48 silly addNameRange     '2.2.7',
48 silly addNameRange     '2.2.8',
48 silly addNameRange     '2.2.9',
48 silly addNameRange     '2.2.10',
48 silly addNameRange     '2.2.11',
48 silly addNameRange     '2.2.12',
48 silly addNameRange     '2.2.13' ] ]
49 silly addNamed aws-sdk@2.2.13
50 verbose addNamed "2.2.13" is a plain semver version for aws-sdk
51 silly mapToRegistry name aws-sdk
52 silly mapToRegistry using default registry
53 silly mapToRegistry registry https://registry.npmjs.org/
54 silly mapToRegistry uri https://registry.npmjs.org/aws-sdk
55 verbose addRemoteTarball https://registry.npmjs.org/aws-sdk/-/aws-sdk-2.2.13.tgz not in flight; adding
56 verbose addRemoteTarball [ 'https://registry.npmjs.org/aws-sdk/-/aws-sdk-2.2.13.tgz',
56 verbose addRemoteTarball   '8e020e603113e6318a20ccd3164b2147cf72ad3b' ]
57 info retry fetch attempt 1 at 2:55:38 AM
58 info attempt registry request try #1 at 2:55:38 AM
59 http fetch GET https://registry.npmjs.org/aws-sdk/-/aws-sdk-2.2.13.tgz
60 http fetch 200 https://registry.npmjs.org/aws-sdk/-/aws-sdk-2.2.13.tgz
61 silly fetchAndShaCheck shasum 8e020e603113e6318a20ccd3164b2147cf72ad3b
62 verbose addTmpTarball /tmp/npm-438012-719534ff/registry.npmjs.org/aws-sdk/-/aws-sdk-2.2.13.tgz not in flight; adding
63 verbose addTmpTarball already have metadata; skipping unpack for aws-sdk@2.2.13
64 silly cache afterAdd aws-sdk@2.2.13
65 verbose afterAdd /var/lib/openshift/xxxxxxxxxxxxxxxxxxxxxxx/.npm/aws-sdk/2.2.13/package/package.json not in flight; writing
66 verbose afterAdd /var/lib/openshift/xxxxxxxxxxxxxxxxxxxxxxx/.npm/aws-sdk/2.2.13/package/package.json written
67 silly fetchNamedPackageData sax
68 silly mapToRegistry name sax
69 silly mapToRegistry using default registry
70 silly mapToRegistry registry https://registry.npmjs.org/
71 silly mapToRegistry uri https://registry.npmjs.org/sax
72 silly fetchNamedPackageData xml2js
73 silly mapToRegistry name xml2js
74 silly mapToRegistry using default registry
75 silly mapToRegistry registry https://registry.npmjs.org/
76 silly mapToRegistry uri https://registry.npmjs.org/xml2js
77 silly fetchNamedPackageData xmlbuilder
78 silly mapToRegistry name xmlbuilder
79 silly mapToRegistry using default registry
80 silly mapToRegistry registry https://registry.npmjs.org/
81 silly mapToRegistry uri https://registry.npmjs.org/xmlbuilder
82 verbose request uri https://registry.npmjs.org/sax
83 verbose request no auth needed
84 info attempt registry request try #1 at 2:55:39 AM
85 verbose etag "98FI8TNMDDI1IY2K36CA0L23U"
86 http request GET https://registry.npmjs.org/sax
87 verbose request uri https://registry.npmjs.org/xml2js
88 verbose request no auth needed
89 info attempt registry request try #1 at 2:55:39 AM
90 verbose etag "9L6TSKDUJ3TKKAK5C8IMR7P28"
91 http request GET https://registry.npmjs.org/xml2js
92 http 200 https://registry.npmjs.org/sax
93 verbose headers { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
93 verbose headers   etag: '"BCI4XTIY4UICILY4SFQZU51XN"',
93 verbose headers   'content-type': 'application/json',
93 verbose headers   'cache-control': 'max-age=60',
93 verbose headers   'content-length': '52661',
93 verbose headers   'accept-ranges': 'bytes',
93 verbose headers   date: 'Fri, 30 Oct 2015 06:55:39 GMT',
93 verbose headers   via: '1.1 varnish',
93 verbose headers   age: '10',
93 verbose headers   connection: 'keep-alive',
93 verbose headers   'x-served-by': 'cache-jfk1025-JFK',
93 verbose headers   'x-cache': 'HIT',
93 verbose headers   'x-cache-hits': '1',
93 verbose headers   'x-timer': 'S1446188139.211406,VS0,VE0',
93 verbose headers   vary: 'Accept' }
94 silly get cb [ 200,
94 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
94 silly get     etag: '"BCI4XTIY4UICILY4SFQZU51XN"',
94 silly get     'content-type': 'application/json',
94 silly get     'cache-control': 'max-age=60',
94 silly get     'content-length': '52661',
94 silly get     'accept-ranges': 'bytes',
94 silly get     date: 'Fri, 30 Oct 2015 06:55:39 GMT',
94 silly get     via: '1.1 varnish',
94 silly get     age: '10',
94 silly get     connection: 'keep-alive',
94 silly get     'x-served-by': 'cache-jfk1025-JFK',
94 silly get     'x-cache': 'HIT',
94 silly get     'x-cache-hits': '1',
94 silly get     'x-timer': 'S1446188139.211406,VS0,VE0',
94 silly get     vary: 'Accept' } ]
95 verbose get saving sax to /var/lib/openshift/xxxxxxxxxxxxxxxxxxxxxxx/.npm/registry.npmjs.org/sax/.cache.json
96 verbose request uri https://registry.npmjs.org/xmlbuilder
97 verbose request no auth needed
98 info attempt registry request try #1 at 2:55:39 AM
99 verbose etag "7GJCWAW5F5HIRSAQZX68TJ8AB"
100 http request GET https://registry.npmjs.org/xmlbuilder
101 silly resolveWithNewModule sax@0.5.3 checking installable status
102 silly cache add args [ 'sax@0.5.3', null ]
103 verbose cache add spec sax@0.5.3
104 silly cache add parsed spec Result {
104 silly cache add   raw: 'sax@0.5.3',
104 silly cache add   scope: null,
104 silly cache add   name: 'sax',
104 silly cache add   rawSpec: '0.5.3',
104 silly cache add   spec: '0.5.3',
104 silly cache add   type: 'version' }
105 silly addNamed sax@0.5.3
106 verbose addNamed "0.5.3" is a plain semver version for sax
107 silly mapToRegistry name sax
108 silly mapToRegistry using default registry
109 silly mapToRegistry registry https://registry.npmjs.org/
110 silly mapToRegistry uri https://registry.npmjs.org/sax
111 verbose addNameVersion registry:https://registry.npmjs.org/sax not in flight; fetching
112 verbose get https://registry.npmjs.org/sax not expired, no request
113 http 200 https://registry.npmjs.org/xmlbuilder
114 verbose headers { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
114 verbose headers   etag: '"591RVE5SOD8WI9HEBM5A9A4V3"',
114 verbose headers   'content-type': 'application/json',
114 verbose headers   'cache-control': 'max-age=60',
114 verbose headers   'content-length': '67436',
114 verbose headers   'accept-ranges': 'bytes',
114 verbose headers   date: 'Fri, 30 Oct 2015 06:55:39 GMT',
114 verbose headers   via: '1.1 varnish',
114 verbose headers   age: '47',
114 verbose headers   connection: 'keep-alive',
114 verbose headers   'x-served-by': 'cache-jfk1031-JFK',
114 verbose headers   'x-cache': 'HIT',
114 verbose headers   'x-cache-hits': '1',
114 verbose headers   'x-timer': 'S1446188139.255233,VS0,VE0',
114 verbose headers   vary: 'Accept' }
115 silly get cb [ 200,
115 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
115 silly get     etag: '"591RVE5SOD8WI9HEBM5A9A4V3"',
115 silly get     'content-type': 'application/json',
115 silly get     'cache-control': 'max-age=60',
115 silly get     'content-length': '67436',
115 silly get     'accept-ranges': 'bytes',
115 silly get     date: 'Fri, 30 Oct 2015 06:55:39 GMT',
115 silly get     via: '1.1 varnish',
115 silly get     age: '47',
115 silly get     connection: 'keep-alive',
115 silly get     'x-served-by': 'cache-jfk1031-JFK',
115 silly get     'x-cache': 'HIT',
115 silly get     'x-cache-hits': '1',
115 silly get     'x-timer': 'S1446188139.255233,VS0,VE0',
115 silly get     vary: 'Accept' } ]
116 verbose get saving xmlbuilder to /var/lib/openshift/xxxxxxxxxxxxxxxxxxxxxxx/.npm/registry.npmjs.org/xmlbuilder/.cache.json
117 silly resolveWithNewModule xmlbuilder@0.4.2 checking installable status
118 silly cache add args [ 'xmlbuilder@0.4.2', null ]
119 verbose cache add spec xmlbuilder@0.4.2
120 silly cache add parsed spec Result {
120 silly cache add   raw: 'xmlbuilder@0.4.2',
120 silly cache add   scope: null,
120 silly cache add   name: 'xmlbuilder',
120 silly cache add   rawSpec: '0.4.2',
120 silly cache add   spec: '0.4.2',
120 silly cache add   type: 'version' }
121 silly addNamed xmlbuilder@0.4.2
122 verbose addNamed "0.4.2" is a plain semver version for xmlbuilder
123 silly mapToRegistry name xmlbuilder
124 silly mapToRegistry using default registry
125 silly mapToRegistry registry https://registry.npmjs.org/
126 silly mapToRegistry uri https://registry.npmjs.org/xmlbuilder
127 verbose addNameVersion registry:https://registry.npmjs.org/xmlbuilder not in flight; fetching
128 verbose get https://registry.npmjs.org/xmlbuilder not expired, no request
129 silly cache afterAdd sax@0.5.3
130 verbose afterAdd /var/lib/openshift/xxxxxxxxxxxxxxxxxxxxxxx/.npm/sax/0.5.3/package/package.json not in flight; writing
131 verbose afterAdd /var/lib/openshift/xxxxxxxxxxxxxxxxxxxxxxx/.npm/sax/0.5.3/package/package.json written
132 http 200 https://registry.npmjs.org/xml2js
133 verbose headers { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
133 verbose headers   etag: '"3D5TNJYLCEI4QU9A9T2NOD6AU"',
133 verbose headers   'content-type': 'application/json',
133 verbose headers   'cache-control': 'max-age=60',
133 verbose headers   'content-length': '104471',
133 verbose headers   'accept-ranges': 'bytes',
133 verbose headers   date: 'Fri, 30 Oct 2015 06:55:39 GMT',
133 verbose headers   via: '1.1 varnish',
133 verbose headers   age: '0',
133 verbose headers   connection: 'keep-alive',
133 verbose headers   'x-served-by': 'cache-jfk1023-JFK',
133 verbose headers   'x-cache': 'HIT',
133 verbose headers   'x-cache-hits': '1',
133 verbose headers   'x-timer': 'S1446188139.218371,VS0,VE90',
133 verbose headers   vary: 'Accept' }
134 silly get cb [ 200,
134 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
134 silly get     etag: '"3D5TNJYLCEI4QU9A9T2NOD6AU"',
134 silly get     'content-type': 'application/json',
134 silly get     'cache-control': 'max-age=60',
134 silly get     'content-length': '104471',
134 silly get     'accept-ranges': 'bytes',
134 silly get     date: 'Fri, 30 Oct 2015 06:55:39 GMT',
134 silly get     via: '1.1 varnish',
134 silly get     age: '0',
134 silly get     connection: 'keep-alive',
134 silly get     'x-served-by': 'cache-jfk1023-JFK',
134 silly get     'x-cache': 'HIT',
134 silly get     'x-cache-hits': '1',
134 silly get     'x-timer': 'S1446188139.218371,VS0,VE90',
134 silly get     vary: 'Accept' } ]
135 verbose get saving xml2js to /var/lib/openshift/xxxxxxxxxxxxxxxxxxxxxxx/.npm/registry.npmjs.org/xml2js/.cache.json
136 silly resolveWithNewModule xml2js@0.2.8 checking installable status
137 silly cache add args [ 'xml2js@0.2.8', null ]
138 verbose cache add spec xml2js@0.2.8
139 silly cache add parsed spec Result {
139 silly cache add   raw: 'xml2js@0.2.8',
139 silly cache add   scope: null,
139 silly cache add   name: 'xml2js',
139 silly cache add   rawSpec: '0.2.8',
139 silly cache add   spec: '0.2.8',
139 silly cache add   type: 'version' }
140 silly addNamed xml2js@0.2.8
141 verbose addNamed "0.2.8" is a plain semver version for xml2js
142 silly mapToRegistry name xml2js
143 silly mapToRegistry using default registry
144 silly mapToRegistry registry https://registry.npmjs.org/
145 silly mapToRegistry uri https://registry.npmjs.org/xml2js
146 verbose addNameVersion registry:https://registry.npmjs.org/xml2js not in flight; fetching
147 verbose get https://registry.npmjs.org/xml2js not expired, no request
148 silly cache afterAdd xmlbuilder@0.4.2
149 verbose afterAdd /var/lib/openshift/xxxxxxxxxxxxxxxxxxxxxxx/.npm/xmlbuilder/0.4.2/package/package.json not in flight; writing
150 verbose afterAdd /var/lib/openshift/xxxxxxxxxxxxxxxxxxxxxxx/.npm/xmlbuilder/0.4.2/package/package.json written
151 silly cache afterAdd xml2js@0.2.8
152 verbose afterAdd /var/lib/openshift/xxxxxxxxxxxxxxxxxxxxxxx/.npm/xml2js/0.2.8/package/package.json not in flight; writing
153 verbose afterAdd /var/lib/openshift/xxxxxxxxxxxxxxxxxxxxxxx/.npm/xml2js/0.2.8/package/package.json written
154 verbose stack TypeError: Cannot read property 'localeCompare' of undefined
154 verbose stack     at installOrder (/var/lib/openshift/xxxxxxxxxxxxxxxxxxxxxxx/app-root/data/node-v5.0.0-linux-x64/lib/node_modules/npm/lib/install/deps.js:241:3
2)
154 verbose stack     at Array.sort (native)
154 verbose stack     at /var/lib/openshift/xxxxxxxxxxxxxxxxxxxxxxx/app-root/data/node-v5.0.0-linux-x64/lib/node_modules/npm/lib/install/deps.js:240:27
154 verbose stack     at cb (/var/lib/openshift/xxxxxxxxxxxxxxxxxxxxxxx/app-root/data/node-v5.0.0-linux-x64/lib/node_modules/npm/node_modules/slide/lib/async-map.js
:47:24)
154 verbose stack     at resolveWithExistingModule (/var/lib/openshift/xxxxxxxxxxxxxxxxxxxxxxx/app-root/data/node-v5.0.0-linux-x64/lib/node_modules/npm/lib/install/
deps.js:377:3)
154 verbose stack     at /var/lib/openshift/xxxxxxxxxxxxxxxxxxxxxxx/app-root/data/node-v5.0.0-linux-x64/lib/node_modules/npm/lib/install/deps.js:347:5
154 verbose stack     at /var/lib/openshift/xxxxxxxxxxxxxxxxxxxxxxx/app-root/data/node-v5.0.0-linux-x64/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:
35
154 verbose stack     at Array.forEach (native)
154 verbose stack     at /var/lib/openshift/xxxxxxxxxxxxxxxxxxxxxxx/app-root/data/node-v5.0.0-linux-x64/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:
11
154 verbose stack     at Array.forEach (native)
155 verbose cwd /var/lib/openshift/xxxxxxxxxxxxxxxxxxxxxxx/app-root/runtime/repo
156 error Linux 2.6.32-504.34.1.el6.x86_64
157 error argv "/var/lib/openshift/xxxxxxxxxxxxxxxxxxxxxxx/app-root/data/node-v5.0.0-linux-x64/bin/node" "/var/lib/openshift/xxxxxxxxxxxxxxxxxxxxxxx/app-root/data/
node-v5.0.0-linux-x64/bin/npm" "install" "-d"
158 error node v5.0.0
159 error npm  v3.3.6
160 error Cannot read property 'localeCompare' of undefined
161 error If you need help, you may report this error at:
161 error     <https://github.com/npm/npm/issues>
162 verbose exit [ 1, true ]
```

**Comment by optimisme** [comment]
Ok, this is not a bug. Using openshift I had to:

- Remove contents from remote folder 'app-root/repo/node_modules/'
- Change local file '.openshift/markers/NODEJS_VERSION' to version 5.0.0
- From local folder call: 'npm rebuild' and 'npm install'
- Then push changes to OpenShift

**Comment by KenanY** [comment]
@optimisme If anything I would at least recommend [upgrading](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) to at least [`npm@3.3.7`](https://github.com/npm/npm/releases/tag/v3.3.7) which shipped with a fix for various `localeCompare` errors.

**Comment by othiym23** [comment]
Closing as resolved.
