### ISSUE TITLE
Cannot read property 'uid' of undefined

### ISSUE THREAD

**Issue by killswitch** [npm/npm#10164]
Trying to use heroku's nodejs build pack, and anytime I build a container I get this error from npm.

Running the same command in the container itself works, but obviously using heroku's buildpack, I can't manually run install on every one.

**npm-debug.log**
```
root@62978fe142dc:/build# cat npm-debug.log 
0 info it worked if it ends with ok
1 verbose cli [ '/build/.heroku/node/bin/node',
1 verbose cli   '/build/.heroku/node/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--unsafe-perm',
1 verbose cli   '--userconfig',
1 verbose cli   '/build/.npmrc' ]
2 info using npm@2.14.7
3 info using node@v4.2.1
4 verbose config Skipping project config: /build/.npmrc. (matches userconfig)
5 verbose readDependencies loading dependencies from /build/package.json
6 warn package.json node-js-sample@0.2.0 No repository field.
7 warn package.json node-js-sample@0.2.0 No license field.
8 verbose install where, deps [ '/build', [ 'express' ] ]
9 verbose install where, peers [ '/build', [] ]
10 verbose installManyTop reading for lifecycle /build/package.json
11 info preinstall node-js-sample@0.2.0
12 verbose readDependencies loading dependencies from /build/package.json
13 silly cache add args [ 'express@^4.x', null ]
14 verbose cache add spec express@^4.x
15 silly cache add parsed spec Result {
15 silly cache add   raw: 'express@^4.x',
15 silly cache add   scope: null,
15 silly cache add   name: 'express',
15 silly cache add   rawSpec: '^4.x',
15 silly cache add   spec: '>=4.0.0 <5.0.0',
15 silly cache add   type: 'range' }
16 silly addNamed express@>=4.0.0 <5.0.0
17 verbose addNamed ">=4.0.0 <5.0.0" is a valid semver range for express
18 silly addNameRange { name: 'express', range: '>=4.0.0 <5.0.0', hasData: false }
19 silly mapToRegistry name express
20 silly mapToRegistry using default registry
21 silly mapToRegistry registry https://registry.npmjs.org/
22 silly mapToRegistry uri https://registry.npmjs.org/express
23 verbose addNameRange registry:https://registry.npmjs.org/express not in flight; fetching
24 verbose request uri https://registry.npmjs.org/express
25 verbose request no auth needed
26 info attempt registry request try #1 at 9:37:38 PM
27 verbose request id 1fdcff8ad46b4768
28 http request GET https://registry.npmjs.org/express
29 http 200 https://registry.npmjs.org/express
30 verbose headers { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
30 verbose headers   etag: '"8E3HWG2Q8T35QP91GMRPNVK69"',
30 verbose headers   'content-type': 'application/json',
30 verbose headers   'cache-control': 'max-age=60',
30 verbose headers   'content-length': '528040',
30 verbose headers   'accept-ranges': 'bytes',
30 verbose headers   date: 'Thu, 29 Oct 2015 21:37:38 GMT',
30 verbose headers   via: '1.1 varnish',
30 verbose headers   age: '56',
30 verbose headers   connection: 'keep-alive',
30 verbose headers   'x-served-by': 'cache-ord1733-ORD',
30 verbose headers   'x-cache': 'HIT',
30 verbose headers   'x-cache-hits': '1',
30 verbose headers   'x-timer': 'S1446154658.276243,VS0,VE2',
30 verbose headers   vary: 'Accept' }
31 silly get cb [ 200,
31 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
31 silly get     etag: '"8E3HWG2Q8T35QP91GMRPNVK69"',
31 silly get     'content-type': 'application/json',
31 silly get     'cache-control': 'max-age=60',
31 silly get     'content-length': '528040',
31 silly get     'accept-ranges': 'bytes',
31 silly get     date: 'Thu, 29 Oct 2015 21:37:38 GMT',
31 silly get     via: '1.1 varnish',
31 silly get     age: '56',
31 silly get     connection: 'keep-alive',
31 silly get     'x-served-by': 'cache-ord1733-ORD',
31 silly get     'x-cache': 'HIT',
31 silly get     'x-cache-hits': '1',
31 silly get     'x-timer': 'S1446154658.276243,VS0,VE2',
31 silly get     vary: 'Accept' } ]
32 verbose get saving express to /app/.npm/registry.npmjs.org/express/.cache.json
33 verbose makeDirectory /app/.npm creation not in flight; initializing
34 error makeDirectory homeless?
35 verbose stack TypeError: Cannot read property 'uid' of undefined
35 verbose stack     at /build/.heroku/node/lib/node_modules/npm/lib/cache/caching-client.js:185:41
35 verbose stack     at /build/.heroku/node/lib/node_modules/npm/node_modules/write-file-atomic/index.js:29:15
35 verbose stack     at LOOP (/build/.heroku/node/lib/node_modules/npm/node_modules/slide/lib/chain.js:7:26)
35 verbose stack     at /build/.heroku/node/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
35 verbose stack     at FSReqWrap.oncomplete (fs.js:82:15)
36 verbose cwd /build
37 error Linux 4.1.10-boot2docker
38 error argv "/build/.heroku/node/bin/node" "/build/.heroku/node/bin/npm" "install" "--unsafe-perm" "--userconfig" "/build/.npmrc"
39 error node v4.2.1
40 error npm  v2.14.7
41 error Cannot read property 'uid' of undefined
42 error If you need help, you may report this error at:
42 error     <https://github.com/npm/npm/issues>
43 verbose exit [ 1, true ]
```

**Comment by othiym23** [comment]
This is a weird one, and may be Heroku and/or Docker-specific. npm is trying to write package metadata to its cache directory, and is failing because it's not getting a stat object back from `getStat`, probably because that's erroring. The first bug here is that this code should be handling things when `getStat` errors, which is going to be a fun thing to try to test. The only reason I can think of that `getStat` would error would be if it errors when trying to read or create that cache directory (probably create, because I'm going to guess that this is containerized and that chunk of the container is read-only).

The larger issue, and the reason why this works when you're logged into the dyno, is this:

```
34 error makeDirectory homeless?
```

When you're logged into an interactive session, `$HOME` is set, and so there's a place for npm to write its cache to. For whatever reason, that isn't set for the buildpack, and so it's choosing to write to `/app/.npm` instead of `/build/.npm`, which I'm guessing is what it's supposed to be doing here. I'm a bit at sea to figure out what npm should be doing here aside from handling that error better; @hunterloftis, do you have any ideas here?

**Comment by hunterloftis** [comment]
@killswitch can you provide a bit more context? For instance, is there app source somewhere that I could clone and then push to a heroku app to reproduce the behavior?

**Comment by killswitch** [comment]
@othiym23 interesting, thanks for the feedback.

@hunterloftis I used https://github.com/convox/cedar which just dockerizes heroku buildpacks. So clone the nodejs sample repo from heroku (https://github.com/heroku/node-js-getting-started) create a `Dockerfile` with the following in it

```
FROM convox/cedar
```

Then run `docker build -t yourapp .` and then run the container. I'll try by setting `-e HOME=/app` and see if that helps.

**Comment by killswitch** [comment]
After closer inspection, `convox/cedar` has `ONBUILD ENV HOME /app` so `$HOME` is set.

**Comment by killswitch** [comment]
Here's the env vars in the container when I attach to it.

```
{ HOSTNAME: '62978fe142dc',
  TERM: 'xterm',
  WEB_MEMORY: '512',
  MEMORY_AVAILABLE: '512',
  PATH: '/app/.heroku/node/bin:/app/bin:/app/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
  WEB_CONCURRENCY: '1',
  PWD: '/build',
  STACK: 'cedar-14',
  HOME: '/app',
  SHLVL: '1',
  CURL_TIMEOUT: '600',
  PORT: '3000',
  NODE_HOME: '/app/.heroku/node',
  _: '/app/.heroku/node/bin/node' }
```

**Comment by killswitch** [comment]
Also looks like Docker runs as `root` in containers too.

**Comment by killswitch** [comment]
Okay, so I forked the `convox/cedar` and changed `ON BUILD ENV HOME /app` to `/build` and reran it and it works.

Thanks @othiym23 and @hunterloftis, and especially @aredridel for initially helping.
