### ISSUE TITLE
Broken link leads to EMISSINGARG

### ISSUE THREAD

**Issue by andy-hanson** [npm/npm#10201]
Npm has problems when links created by `npm link` become broken.
Here's how to reproduce it:

Create a directory `linked-to` with this package.json:
	
	{
		"name": "linked-to",
		"version": "0.0.0"
	}

Create another directory `linker` with this package.json:

	{
		"name": "linker",
		"devDependencies": {
			"linked-to": "example/linked-to"
		}
	}

and run:

	npm link ../linked-to
	mv ../linked-to ../renamed
	npm outdated

It fails with this `npm-debug.log`:

	0 info it worked if it ends with ok
	1 verbose cli [ '/home/andy/.nvm/versions/node/v5.0.0/bin/node',
	1 verbose cli   '/home/andy/.nvm/versions/node/v5.0.0/bin/npm',
	1 verbose cli   'outdated' ]
	2 info using npm@3.3.6
	3 info using node@v5.0.0
	4 verbose stack Error: Missing required argument #1
	4 verbose stack     at module.exports (/home/andy/.nvm/versions/node/v5.0.0/lib/node_modules/npm/lib/install/mutate-into-logical-tree.js:11:3)
	4 verbose stack     at /home/andy/.nvm/versions/node/v5.0.0/lib/node_modules/npm/lib/outdated.js:77:5
	4 verbose stack     at /home/andy/.nvm/versions/node/v5.0.0/lib/node_modules/npm/lib/outdated.js:61:20
	4 verbose stack     at /home/andy/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:186:9
	4 verbose stack     at f (/home/andy/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/once/once.js:17:25)
	4 verbose stack     at /home/andy/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:152:20
	4 verbose stack     at f (/home/andy/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/once/once.js:17:25)
	4 verbose stack     at then (/home/andy/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:121:22)
	4 verbose stack     at /home/andy/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:81:20
	4 verbose stack     at fs.js:1657:23
	5 verbose cwd /home/andy/npm-bugs/bug2/linker
	6 error Linux 3.13.0-24-generic
	7 error argv "/home/andy/.nvm/versions/node/v5.0.0/bin/node" "/home/andy/.nvm/versions/node/v5.0.0/bin/npm" "outdated"
	8 error node v5.0.0
	9 error npm  v3.3.6
	10 error code EMISSINGARG
	11 error typeerror Error: Missing required argument #1
	11 error typeerror     at module.exports (/home/andy/.nvm/versions/node/v5.0.0/lib/node_modules/npm/lib/install/mutate-into-logical-tree.js:11:3)
	11 error typeerror     at /home/andy/.nvm/versions/node/v5.0.0/lib/node_modules/npm/lib/outdated.js:77:5
	11 error typeerror     at /home/andy/.nvm/versions/node/v5.0.0/lib/node_modules/npm/lib/outdated.js:61:20
	11 error typeerror     at /home/andy/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:186:9
	11 error typeerror     at f (/home/andy/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/once/once.js:17:25)
	11 error typeerror     at /home/andy/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:152:20
	11 error typeerror     at f (/home/andy/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/once/once.js:17:25)
	11 error typeerror     at then (/home/andy/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:121:22)
	11 error typeerror     at /home/andy/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:81:20
	11 error typeerror     at fs.js:1657:23
	11 error typeerror This is an error with npm itself. Please report this error at:
	11 error typeerror     <http://github.com/npm/npm/issues>
	12 verbose exit [ 1, true ]

**Comment by smikes** [comment]
Thanks for reporting this.

**Comment by watilde** [comment]
@othiym23 @iarna I started to try fixing this issue. Let me know if you have any additional context please. I guess `fs.realpath` in the `read-package-tree` return an error and this module should build an Object regardless of the error. https://github.com/npm/read-package-tree/blob/master/rpt.js#L80

**Comment by iarna** [comment]
@watilde There are two bugs here:

First if `read-package-tree` returns an error we should print the error and exit, as it's only supposed to return errors in catastrophically bad situations.

Second, there is a bug in `read-package-tree`. It looks like broken links in `node_modules` are causing `read-package-tree` to return errors, but the thing is, `read-package-tree` shouldn't return errors in that situation. It should just create a `Node` object with the `error` property set. That is, I believe line 81 of `rpt.js` shouldn't call the callback with an error, but instead should continue and pass its error object to the `Node` constructor. If there's an error BOTH in `realpath` AND in `read-package-json` I would prefer the error from the former.

**Comment by watilde** [comment]
@iarna Thanks for your polite comment. I tried to create a pull request on read-package-tree here https://github.com/npm/read-package-tree/pull/6 to fix your Second suggestion. Could you please see it?

**Comment by watilde** [comment]
I think this issue was fixed already.
