### ISSUE TITLE
Error: Cannot find module 'braces'

### ISSUE THREAD

**Issue by jacobjuul** [npm/npm#10212]
I am getting this error when I try to start my node app using nodemon

npm --version
3.3.9
node --version
v4.0.0

```javascript
module.js:338
    throw err;
    ^

Error: Cannot find module 'braces'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/nodemon/node_modules/chokidar/node_modules/anymatch/node_modules/micromatch/lib/glob.js:3:14)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

**Comment by KenanY** [comment]
@jacobjuul Does uninstalling+reinstalling nodemon help at all?

**Comment by KenanY** [comment]
@jacobjuul Are you still having this issue?

**Comment by jacobjuul** [comment]
@KenanY 
No, since upgrading npm and node the issues no longer persists

**Comment by othiym23** [comment]
Closing as resolved.
