### ISSUE TITLE
npm 403 Forbbiden Windows 10

### ISSUE THREAD

**Issue by Thetoy42** [npm/npm#10225]
Hi, i'm on Windows 10.

I try to install cordova with a npm command.
I have an unexplicated error, a 403 Forbidden.
I have tried to reinstall node.js (32 bits and 64), the path is correct for npm, I desactivate the virus checker and so on. I have no issues right now, please help me.
This is the npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'cordova' ]
2 info using npm@2.14.7
3 info using node@v4.2.1
4 verbose install initial load of C:\Program Files\nodejs\package.json
5 verbose readDependencies loading dependencies from C:\Program Files\nodejs\package.json
6 silly cache add args [ 'cordova', null ]
7 verbose cache add spec cordova
8 silly cache add parsed spec Result {
8 silly cache add   raw: 'cordova',
8 silly cache add   scope: null,
8 silly cache add   name: 'cordova',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: '*',
8 silly cache add   type: 'range' }
9 silly addNamed cordova@*
10 verbose addNamed "*" is a valid semver range for cordova
11 silly addNameRange { name: 'cordova', range: '*', hasData: false }
12 silly mapToRegistry name cordova
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://npm.fury.io/
15 silly mapToRegistry uri https://npm.fury.io/cordova
16 verbose addNameRange registry:https://npm.fury.io/cordova not in flight; fetching
17 verbose request uri https://npm.fury.io/cordova
18 verbose request no auth needed
19 info attempt registry request try #1 at 12:24:22
20 verbose request id dc30e085e19cfc73
21 http request GET https://npm.fury.io/cordova
22 http 403 https://npm.fury.io/cordova
23 verbose headers { server: 'Cowboy',
23 verbose headers   date: 'Mon, 02 Nov 2015 11:24:19 GMT',
23 verbose headers   connection: 'close',
23 verbose headers   'strict-transport-security': 'max-age=2592000; includeSubdomains',
23 verbose headers   'x-frame-options': 'SAMEORIGIN',
23 verbose headers   'x-content-type-options': 'nosniff',
23 verbose headers   'x-download-options': 'noopen',
23 verbose headers   'x-permitted-cross-domain-policies': 'none',
23 verbose headers   'content-type': 'text/html',
23 verbose headers   'cache-control': 'no-cache',
23 verbose headers   'x-request-id': '9724d113-d384-4c0a-9d96-ec80fcae1140',
23 verbose headers   'x-runtime': '0.026819',
23 verbose headers   vary: 'Accept-Encoding',
23 verbose headers   'content-encoding': 'gzip',
23 verbose headers   via: '1.1 vegur' }
24 silly get cb [ 403,
24 silly get   { server: 'Cowboy',
24 silly get     date: 'Mon, 02 Nov 2015 11:24:19 GMT',
24 silly get     connection: 'close',
24 silly get     'strict-transport-security': 'max-age=2592000; includeSubdomains',
24 silly get     'x-frame-options': 'SAMEORIGIN',
24 silly get     'x-content-type-options': 'nosniff',
24 silly get     'x-download-options': 'noopen',
24 silly get     'x-permitted-cross-domain-policies': 'none',
24 silly get     'content-type': 'text/html',
24 silly get     'cache-control': 'no-cache',
24 silly get     'x-request-id': '9724d113-d384-4c0a-9d96-ec80fcae1140',
24 silly get     'x-runtime': '0.026819',
24 silly get     vary: 'Accept-Encoding',
24 silly get     'content-encoding': 'gzip',
24 silly get     via: '1.1 vegur' } ]
25 verbose stack Error: 403 Forbidden
25 verbose stack     at makeError (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:264:12)
25 verbose stack     at CachingRegistryClient.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:215:9)
25 verbose stack     at C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:178:7
25 verbose stack     at Gunzip.onEnd (zlib.js:227:5)
25 verbose stack     at emitNone (events.js:72:20)
25 verbose stack     at Gunzip.emit (events.js:166:7)
25 verbose stack     at endReadableNT (_stream_readable.js:903:12)
25 verbose stack     at doNTCallback2 (node.js:439:9)
25 verbose stack     at process._tickCallback (node.js:353:17)
26 verbose statusCode 403
27 verbose cwd C:\
28 error Windows_NT 10.0.10240
29 error argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova"
30 error node v4.2.1
31 error npm  v2.14.7
32 error code E403
33 error 403 Forbidden
34 error If you need help, you may report this error at:
34 error     <https://github.com/npm/npm/issues>
35 verbose exit [ 1, true ]

**Comment by Thetoy42** [comment]
I precise i have no proxy configure.
Best regards

**Comment by Thetoy42** [comment]
It works after 2 days of tries.
I have uninstalled nodejs 
I have cleared all the file with extensions .npm on my computer
I have reinstalled nodejs
It has worked fine !
