### ISSUE TITLE
Error Initializing app: Error: tunneling socket could not be established, cause=Parse Error

### ISSUE THREAD

**Issue by log2amit26** [npm/npm#10220]
C:>ionic start myapp blank
Creating Ionic app in folder C:\Users\$$$\myapp based on blank project
Downloading: https://github.com/driftyco/ionic-app-base/archive/master.zip
Error Initializing app: Error: tunneling socket could not be established, cause=Parse Error

Error: tunneling socket could not be established, cause=Parse Error
    at ClientRequest.onError (c:\Users\$$$\AppData\Roaming\npm\node_modules\io
nic\node_modules\request\node_modules\tunnel-agent\index.js:174:17)
    at ClientRequest.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketOnData (_http_client.js:310:9)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)

tunneling socket could not be established, cause=Parse Error (CLI v1.7.7)

Your system information:

Cordova CLI: 5.3.3
Ionic CLI Version: 1.7.7
Ionic App Lib Version: 0.6.3
OS: Windows 7 SP1
Node Version: v4.2.1

**Comment by log2amit26** [comment]
Hello,

Getting error on creating ionic project behind proxy. However I am able to install through npm by setting proxy and https_proxy.

**Comment by log2amit26** [comment]
Moved to IONIC-CLI
