### ISSUE TITLE
hawk kills npm

### ISSUE THREAD

**Issue by MaxGfeller** [npm/npm#10241]
So, after an update of npm (using the node.js 5.0 bundle), npm stopped working properly.

Apparently this problem comes from the `hawk` package, which is required by `request`:

```
$ npm -h

Error: Cannot find module './lib'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/index.js:1:80)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "-h"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module './lib'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```
This error shows up every time i want to use the npm cli.

**Comment by KenanY** [comment]
Looks like another instance of https://github.com/nodejs/node/issues/3606.

**Comment by Fishrock123** [comment]
This is a one-time fault of node's installer, not npm or hawk.

**Comment by KenanY** [comment]
@MaxGfeller Are you still seeing this issue?

**Comment by MaxGfeller** [comment]
Nope!

**Comment by KenanY** [comment]
Closing as resolved.
