### ISSUE TITLE
sapnwrfc is not installing

### ISSUE THREAD

**Issue by RamprasathS** [npm/npm#10254]
I tried npm install sapnwrfc, I have copied sdk lib to system32, I am using windows 7 32 bit os, But i am getting the below error, Please help me on this,

```
C:\Users\323847\AppData\Roaming\npm\node_modules\sapnwrfc>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\
.\..\node_modules\node-gyp\bin\node-gyp.js" clean )  else (node  clean )
{ [Error: Could not locate the bindings file. Tried:
 → C:\Users\323847\AppData\Roaming\npm\node_modules\sapnwrfc\build\sapnwrfc.node
 → C:\Users\323847\AppData\Roaming\npm\node_modules\sapnwrfc\build\Debug\sapnwrfc.node
 → C:\Users\323847\AppData\Roaming\npm\node_modules\sapnwrfc\build\Release\sapnwrfc.node
 → C:\Users\323847\AppData\Roaming\npm\node_modules\sapnwrfc\out\Debug\sapnwrfc.node
 → C:\Users\323847\AppData\Roaming\npm\node_modules\sapnwrfc\Debug\sapnwrfc.node
 → C:\Users\323847\AppData\Roaming\npm\node_modules\sapnwrfc\out\Release\sapnwrfc.node
 → C:\Users\323847\AppData\Roaming\npm\node_modules\sapnwrfc\Release\sapnwrfc.node
 → C:\Users\323847\AppData\Roaming\npm\node_modules\sapnwrfc\build\default\sapnwrfc.node
 → C:\Users\323847\AppData\Roaming\npm\node_modules\sapnwrfc\compiled\4.2\win32\ia32\sapnwrfc.node]
  tries:
   [ 'C:\\Users\\323847\\AppData\\Roaming\\npm\\node_modules\\sapnwrfc\\build\\sapnwrfc.node',
     'C:\\Users\\323847\\AppData\\Roaming\\npm\\node_modules\\sapnwrfc\\build\\debug\\sapnwrfc.node',
     'C:\\Users\\323847\\AppData\\Roaming\\npm\\node_modules\\sapnwrfc\\build\\Release\\sapnwrfc.node',
     'C:\\Users\\323847\\AppData\\Roaming\\npm\\node_modules\\sapnwrfc\\out\\Debug\\sapnwrfc.node',
     'C:\\Users\\323847\\AppData\\Roaming\\npm\\node_modules\\sapnwrfc\\Debug\\sapnwrfc.node',
     'C:\\Users\\323847\\AppData\\Roaming\\npm\\node_modules\\sapnwrfc\\out\\Release\\sapnwrfc.node',
     'C:\\Users\\323847\\AppData\\Roaming\\npm\\node_modules\\sapnwrfc\\Release\\sapnwrfc.node',
     'C:\\Users\\323847\\AppData\\Roaming\\npm\\node_modules\\sapnwrfc\\build\\default\\sapnwrfc.node',
     'C:\\Users\\323847\\AppData\\Roaming\\npm\\node_modules\\sapnwrfc\\compile\\4.2\\win32\\ia32\\sapnwrfc.node' ] }
error a precompiled module could not be found or loaded
info trying to compile it...

C:\Users\323847\AppData\Roaming\npm\node_modules\sapnwrfc>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\
.\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
  binding.cc
  Connection.cc
c:\users\323847\appdata\roaming\npm\node_modules\sapnwrfc\src\Common.h(30): fatal error C1083: Cannot open include file: 'sapnwrfc.h': No such file or directo
ry (..\src\Connection.cc) [C:\Users\323847\AppData\Roaming\npm\node_modules\sapnwrfc\build\sapnwrfc.vcxproj]
  Function.cc
c:\users\323847\appdata\roaming\npm\node_modules\sapnwrfc\src\Common.h(30): fatal error C1083: Cannot open include file: 'sapnwrfc.h': No such file or directory (..\src\binding.cc) [C:\Users\323847\AppData\Roaming\npm\node_modules\sapnwrfc\build\sapnwrfc.vcxproj]
c:\users\323847\appdata\roaming\npm\node_modules\sapnwrfc\src\Common.h(30): fatal error C1083: Cannot open include file: 'sapnwrfc.h': No such file or directory (..\src\Function.cc) [C:\Users\323847\AppData\Roaming\npm\node_modules\sapnwrfc\build\sapnwrfc.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodes\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\323847\AppData\Roaming\npm\node_modules\sapnwrfc
gyp ERR! node -v v4.2.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
sapnwrfc@0.1.8 C:\Users\323847\AppData\Roaming\npm\node_modules\sapnwrfc
├── bindings@1.2.1
└── nan@2.1.0
```

**Comment by ehsalazar** [comment]
It looks like you were able to get the help you needed from the sapnwrfc folks via your [issue](https://github.com/jdorner/node-sapnwrfc/issues/22). I'll close this for now as we’re trying to clean up some solved issues.
