### ISSUE TITLE
Nested dependency resolution not working properly in npm 3

### ISSUE THREAD

**Issue by Qard** [npm/npm#10264]
So I found an issue with npm 3 where deps that *should* have nested deps, due to version conflicts, do not.

Versions:
node 5.0.0
npm 3.3.6

Steps to reproduce:
- npm install vision@latest
- npm install hapi@8.6.1
- node -e "require('hapi')"

Error:
```
/home/sbelanger/Documents/test/hapi-test/node_modules/hapi/node_modules/vision/lib/manager.js:40
    path: [Joi.array().includes(Joi.string()), Joi.string()],
                       ^

TypeError: Joi.array(...).includes is not a function
    at Object.<anonymous> (/home/sbelanger/Documents/test/hapi-test/node_modules/hapi/node_modules/vision/lib/manager.js:40:24)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/sbelanger/Documents/test/hapi-test/node_modules/hapi/node_modules/vision/lib/index.js:9:15)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
```

This error occurs because the nested vision dependency in node_modules/hapi/node_modules/vision tries to load joi@5.x.x, but looks upward to the deps of hapi and finds node_modules/hapi/node_modules/joi, but that one is version 6.4.1.

**Comment by Qard** [comment]
Closing, as next seems to work. @othiym23 mentioned it's probably related shrinkwrap issues.

Hopefully next lands in a node release soon. :smile_cat:
