### ISSUE TITLE
Refusing to install koa as a dependency of itself

### ISSUE THREAD

**Issue by ming517** [npm/npm#10269]
I'm having problem while trying to install the Koajs in my macbook. I tried to google but I failed to get the results (maybe im not using the correct keywords).

Hopefully anyone could give some hints on how to solve this.

Your helps is much appreciated.

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'install', 'koa' ]
2 info using npm@3.3.10
3 info using node@v5.0.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData koa
8 silly fetchNamedPackageData koa
9 silly mapToRegistry name koa
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry uri https://registry.npmjs.org/koa
13 verbose request uri https://registry.npmjs.org/koa
14 verbose request no auth needed
15 info attempt registry request try #1 at 3:16:32 PM
16 verbose request id cf643fab3029e361
17 verbose etag "1I0SYOJ2NJ0403S4VO6C2ESL"
18 http request GET https://registry.npmjs.org/koa
19 http 304 https://registry.npmjs.org/koa
20 verbose headers { date: 'Thu, 05 Nov 2015 07:16:33 GMT',
20 verbose headers   via: '1.1 varnish',
20 verbose headers   'cache-control': 'max-age=60',
20 verbose headers   etag: '"1I0SYOJ2NJ0403S4VO6C2ESL"',
20 verbose headers   age: '0',
20 verbose headers   connection: 'keep-alive',
20 verbose headers   'x-served-by': 'cache-hkg6820-HKG',
20 verbose headers   'x-cache': 'MISS',
20 verbose headers   'x-cache-hits': '0',
20 verbose headers   'x-timer': 'S1446707793.011475,VS0,VE182',
20 verbose headers   vary: 'Accept' }
21 silly get cb [ 304,
21 silly get   { date: 'Thu, 05 Nov 2015 07:16:33 GMT',
21 silly get     via: '1.1 varnish',
21 silly get     'cache-control': 'max-age=60',
21 silly get     etag: '"1I0SYOJ2NJ0403S4VO6C2ESL"',
21 silly get     age: '0',
21 silly get     connection: 'keep-alive',
21 silly get     'x-served-by': 'cache-hkg6820-HKG',
21 silly get     'x-cache': 'MISS',
21 silly get     'x-cache-hits': '0',
21 silly get     'x-timer': 'S1446707793.011475,VS0,VE182',
21 silly get     vary: 'Accept' } ]
22 verbose etag https://registry.npmjs.org/koa from cache
23 verbose get saving koa to /Users/ming/.npm/registry.npmjs.org/koa/.cache.json
24 silly install normalizeTree
25 silly loadCurrentTree Finishing
26 silly loadIdealTree Starting
27 silly install loadIdealTree
28 silly cloneCurrentTree Starting
29 silly install cloneCurrentTreeToIdealTree
30 silly cloneCurrentTree Finishing
31 silly loadShrinkwrap Starting
32 silly install loadShrinkwrap
33 silly loadShrinkwrap Finishing
34 silly loadAllDepsIntoIdealTree Starting
35 silly install loadAllDepsIntoIdealTree
36 silly rollbackFailedOptional Starting
37 silly rollbackFailedOptional Finishing
38 silly runTopLevelLifecycles Starting
39 silly runTopLevelLifecycles Finishing
40 silly install printInstalled
41 verbose stack Error: Refusing to install koa as a dependency of itself
41 verbose stack     at checkSelf (/usr/local/lib/node_modules/npm/lib/install/validate-args.js:40:14)
41 verbose stack     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
41 verbose stack     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
41 verbose stack     at chain (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
41 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/validate-args.js:15:5
41 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
41 verbose stack     at Array.forEach (native)
41 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
41 verbose stack     at Array.forEach (native)
41 verbose stack     at asyncMap (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
42 verbose cwd /Users/ming/Development/nodejs/koa
43 error Darwin 14.5.0
44 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "koa"
45 error node v5.0.0
46 error npm  v3.3.10
47 error code ENOSELF
48 error Refusing to install koa as a dependency of itself
49 error If you need help, you may report this error at:
49 error     <https://github.com/npm/npm/issues>
50 verbose exit [ 1, true ]
```

**Comment by ehsalazar** [comment]
@ming517 Is there a `package.json` in the `/Users/ming/Development/nodejs/koa` directory? If so, could you share its contents, perhaps as a [gist](https://gist.github.com)?

**Comment by sinkingshriek** [comment]
@ming517 npm doesn't allow you to install the same package name as in your 'package.json'. You'd have to change `name` field in your `package.json` to something other than `koa`. If that's not the case then I'd check your parent directory for other `package.json` files. Node and npm goes up one dir up until it reaches the root in search of either `package.json` or `node_modules`.

**Comment by ming517** [comment]
Hi all,

Thank you for the suggestion. I realize that the koa was installed in `/usr/local/lib/node_modules/`, by trying to remove the directory and install again, it works fine for now.

Thank you for the helps. Much appreciated.

**Comment by ehsalazar** [comment]
@ming517 It sounds like you're back in business. I'll close this for now as we’re trying to clean up some solved issues. We’ll be happy to reopen if necessary.

**Comment by fkanout** [comment]
I had the same problem
My project named  "koa" in `package.json`
`{
  "name": "koa",
  "version": "1.0.0",
`
So I changed it and it works
