### ISSUE TITLE
Error: Argument #2: Expected string but got object

### ISSUE THREAD

**Issue by baelter** [npm/npm#10272]
While running "npm update":

```
npm WARN install Couldn't install optional dependency: Unsupported
npm WARN deprecated MD5@1.3.0: deprecated, use lowercase 'md5@2.x' from now on
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
npm ERR! Linux 4.2.5-1-MANJARO
npm ERR! argv "/usr/bin/node" "/home/anders/.npm-packages/bin/npm" "update"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.10
npm ERR! code EINVALIDTYPE

npm ERR! typeerror Error: Argument #2: Expected string but got object
npm ERR! typeerror     at addDependency (/home/anders/.npm-packages/lib/node_modules/npm/lib/install/deps.js:373:3)
npm ERR! typeerror     at /home/anders/.npm-packages/lib/node_modules/npm/lib/install/deps.js:334:5

npm ERR! typeerror     at /home/anders/.npm-packages/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
npm ERR! typeerror     at Array.forEach (native)
npm ERR! typeerror     at /home/anders/.npm-packages/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
npm ERR! typeerror     at Array.forEach (native)
npm ERR! typeerror     at asyncMap (/home/anders/.npm-packages/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
npm ERR! typeerror     at loadDeps (/home/anders/.npm-packages/lib/node_modules/npm/lib/install/deps.js:326:3)
npm ERR! typeerror     at Array.<anonymous> (/home/anders/.npm-packages/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
npm ERR! typeerror     at LOOP (/home/anders/.npm-packages/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/anders/Projects/npdc/npdc-dataset/npm-debug.log
```

From npm-debug.log:

```
32461 silly addNamed minimatch@0.3.0
32462 verbose addNamed "0.3.0" is a plain semver version for minimatch
32463 silly cache afterAdd minimatch@0.3.0
32464 verbose afterAdd /home/anders/.npm/minimatch/0.3.0/package/package.json not in flight; writing
32465 verbose afterAdd /home/anders/.npm/minimatch/0.3.0/package/package.json written
32466 verbose stack Error: Argument #2: Expected string but got object
32466 verbose stack     at addDependency (/home/anders/.npm-packages/lib/node_modules/npm/lib/install/deps.js:373:3)
32466 verbose stack     at /home/anders/.npm-packages/lib/node_modules/npm/lib/install/deps.js:334:5
32466 verbose stack     at /home/anders/.npm-packages/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
32466 verbose stack     at Array.forEach (native)
32466 verbose stack     at /home/anders/.npm-packages/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
32466 verbose stack     at Array.forEach (native)
32466 verbose stack     at asyncMap (/home/anders/.npm-packages/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
32466 verbose stack     at loadDeps (/home/anders/.npm-packages/lib/node_modules/npm/lib/install/deps.js:326:3)
32466 verbose stack     at Array.<anonymous> (/home/anders/.npm-packages/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
32466 verbose stack     at LOOP (/home/anders/.npm-packages/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
32467 verbose cwd /home/anders/Projects/npdc/npdc-dataset
32468 error Linux 4.2.5-1-MANJARO
32469 error argv "/usr/bin/node" "/home/anders/.npm-packages/bin/npm" "update"
32470 error node v5.0.0
32471 error npm  v3.3.10
32472 error code EINVALIDTYPE
32473 error typeerror Error: Argument #2: Expected string but got object
32473 error typeerror     at addDependency (/home/anders/.npm-packages/lib/node_modules/npm/lib/install/deps.js:373:3)
32473 error typeerror     at /home/anders/.npm-packages/lib/node_modules/npm/lib/install/deps.js:334:5
32473 error typeerror     at /home/anders/.npm-packages/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
32473 error typeerror     at Array.forEach (native)
32473 error typeerror     at /home/anders/.npm-packages/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
32473 error typeerror     at Array.forEach (native)
32473 error typeerror     at asyncMap (/home/anders/.npm-packages/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
32473 error typeerror     at loadDeps (/home/anders/.npm-packages/lib/node_modules/npm/lib/install/deps.js:326:3)
32473 error typeerror     at Array.<anonymous> (/home/anders/.npm-packages/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
32473 error typeerror     at LOOP (/home/anders/.npm-packages/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
32473 error typeerror This is an error with npm itself. Please report this error at:
32473 error typeerror     <http://github.com/npm/npm/issues>
32474 verbose exit [ 1, true ]
```

**Comment by baelter** [comment]
```
34149 silly fetchNamedPackageData request
34150 silly mapToRegistry name request
34151 silly mapToRegistry using default registry
34152 silly mapToRegistry registry https://registry.npmjs.org/
34153 silly mapToRegistry uri https://registry.npmjs.org/request
34154 verbose stack Error: Argument #2: Expected string but got object
34154 verbose stack     at addDependency (/usr/lib/node_modules/npm/lib/install/deps.js:373:3)
34154 verbose stack     at /usr/lib/node_modules/npm/lib/install/deps.js:334:5
34154 verbose stack     at /usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
34154 verbose stack     at Array.forEach (native)
34154 verbose stack     at /usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
34154 verbose stack     at Array.forEach (native)
34154 verbose stack     at asyncMap (/usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
34154 verbose stack     at loadDeps (/usr/lib/node_modules/npm/lib/install/deps.js:326:3)
34154 verbose stack     at Array.<anonymous> (/usr/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
34154 verbose stack     at LOOP (/usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
34155 verbose cwd /home/anders/Projects/npdc/npdc-publication
34156 error Linux 4.2.5-1-MANJARO
34157 error argv "/usr/bin/node" "/usr/bin/npm" "update"
34158 error node v5.0.0
34159 error npm  v3.3.10
34160 error code EINVALIDTYPE
34161 error typeerror Error: Argument #2: Expected string but got object
34161 error typeerror     at addDependency (/usr/lib/node_modules/npm/lib/install/deps.js:373:3)
34161 error typeerror     at /usr/lib/node_modules/npm/lib/install/deps.js:334:5
34161 error typeerror     at /usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
34161 error typeerror     at Array.forEach (native)
34161 error typeerror     at /usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
34161 error typeerror     at Array.forEach (native)
34161 error typeerror     at asyncMap (/usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
34161 error typeerror     at loadDeps (/usr/lib/node_modules/npm/lib/install/deps.js:326:3)
34161 error typeerror     at Array.<anonymous> (/usr/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
34161 error typeerror     at LOOP (/usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
34161 error typeerror This is an error with npm itself. Please report this error at:
34161 error typeerror     <http://github.com/npm/npm/issues>
34162 verbose exit [ 1, true ]```

**Comment by jadbox** [comment]
Same:
```npm update --save --save-dev                                          [14:26:01]
npm WARN install Couldn't install optional dependency: Unsupported
npm WARN install Couldn't install optional dependency: Unsupported
npm WARN install Couldn't install optional dependency: Unsupported
VidRollPublicPortal@0.1.3 /home/jdunlap/github/vidroll/reportal
└── (empty)

npm ERR! Linux 4.2.0-0.bpo.1-amd64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "update" "--save" "--save-dev"
npm ERR! node v5.5.0
npm ERR! npm  v3.3.12
npm ERR! code EINVALIDTYPE

npm ERR! typeerror Error: Argument #2: Expected string but got object
npm ERR! typeerror     at addDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:373:3)
npm ERR! typeerror     at /usr/local/lib/node_modules/npm/lib/install/deps.js:334:5
npm ERR! typeerror     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
npm ERR! typeerror     at Array.forEach (native)
npm ERR! typeerror     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
npm ERR! typeerror     at Array.forEach (native)
npm ERR! typeerror     at asyncMap (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
npm ERR! typeerror     at loadDeps (/usr/local/lib/node_modules/npm/lib/install/deps.js:326:3)
npm ERR! typeerror     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
npm ERR! typeerror     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jdunlap/github/vidroll/reportal/npm-debug.log
npm ERR! code 1
``` 
npm-debug: https://gist.github.com/jadbox/0077c2f0aebcf6db5807

**Comment by Wandalen** [comment]
Have similar problem:
```
Error: Argument #2: Expected array but got object
{ code : "EINVALIDTYPE" }
{ [Error: Uncaught exception: Argument #2: Expected array but got object 
Error: Argument #2: Expected array but got object
  at EventEmitter.install (/pro/web/Dave/app/builder/node_modules/npm/lib/install.js:175:3)
  at Object.commandCache.(anonymous function) (/pro/web/Dave/app/builder/node_modules/npm/lib/npm.js:216:13)
  at EventEmitter.<anonymous> (/pro/web/Dave/app/builder/electron.installer.scenario.coffee:80:1)
```
  npm.load {},( err,npm ) ->
    npm.commands.install [], ( err, data ) ->
      console.log( 'installed' )
```
Reason in my case is false negative of that test:
```
A: ["array", function (thingy) { return thingy instanceof Array || (typeof thingy === "object" && thingy.hasOwnProperty("callee")) }],
```
Despite argument is Array it gives false.
That because VirtualMachine.runInContext was used.

**Comment by marthinus-engelbrecht** [comment]
Same error, also starts at `chain.js:15:14`. The below code should reproduce it. It only occurs if I try to install for scratch for a second time in the same process. 

```javascript 
var npm = require('npm');
var fs = require('fs-extra');

npm.load({
    loglevel: "silent"
}, function() {
    npm.commands.install([], function(){
        console.log('first install');
        fs.remove("./node_modules", function() {
            npm.load({
            }, function() {
                npm.commands.install();
                console.log('second install');
            });
        });
    });
});
```

If you running npm from code then you can execute it in a child process as a workaround. 

Anyone know what the root cause of this yet?

**Comment by ffxsam** [comment]
I'm experiencing this as well. For me, it happens when I run `npm update` and I've used `npm link` to link a local package into my local project. I can verify that if I do `npm unlink <package>` and then do `npm update`, everything is fine.

**Comment by abradley2** [comment]
Experiencing this as well. Can't run `npm update` either
