### ISSUE TITLE
NPM shrinkwrap says it is missing a dependency that is installed

### ISSUE THREAD

**Issue by broguinn** [npm/npm#10278]
Here's my base application's relevant package.json line:
`"elastic-harvesterjs": "git+https://github.com/agco/elastic-harvesterjs.git#2.3.5",`
and elastic-harvester's dependency that's missing:
`"harvester": "git+https://github.com/agco/harvesterjs.git#2.2.1"`

and here's the error from `npm shrinkwrap`:

```
npm ERR! Error: Problems were encountered
npm ERR! Please correct and try again.
npm ERR! missing: harvester@git+https://github.com/agco/harvesterjs.git#2.2.1, required by elastic-harvesterjs@2.3.5
npm ERR!     at shrinkwrap_ (/Users/braden.oguinn/.nvm/v0.10.33/lib/node_modules/npm/lib/shrinkwrap.js:30:15)
npm ERR!     at /Users/braden.oguinn/.nvm/v0.10.33/lib/node_modules/npm/lib/shrinkwrap.js:24:5
npm ERR!     at /Users/braden.oguinn/.nvm/v0.10.33/lib/node_modules/npm/lib/ls.js:45:30
npm ERR!     at /Users/braden.oguinn/.nvm/v0.10.33/lib/node_modules/npm/node_modules/read-installed/read-installed.js:130:5
npm ERR!     at /Users/braden.oguinn/.nvm/v0.10.33/lib/node_modules/npm/node_modules/read-installed/read-installed.js:244:14
npm ERR!     at cb (/Users/braden.oguinn/.nvm/v0.10.33/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
npm ERR!     at /Users/braden.oguinn/.nvm/v0.10.33/lib/node_modules/npm/node_modules/read-installed/read-installed.js:244:14
npm ERR!     at cb (/Users/braden.oguinn/.nvm/v0.10.33/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
npm ERR!     at /Users/braden.oguinn/.nvm/v0.10.33/lib/node_modules/npm/node_modules/read-installed/read-installed.js:244:14
npm ERR!     at cb (/Users/braden.oguinn/.nvm/v0.10.33/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 15.0.0
npm ERR! command "/Users/braden.oguinn/.nvm/v0.10.33/bin/node" "/Users/braden.oguinn/.nvm/v0.10.33/bin/npm" "shrinkwrap"
npm ERR! cwd /Users/braden.oguinn/sites/fuse-telemetry
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/braden.oguinn/sites/fuse-telemetry/npm-debug.log
npm ERR! not ok code 0
```

The module is clearly there, and an `rm -rf node_modules; npm i` isn't changing anything. I thought it might have to do with the git url and tagging, but elastic-harvester is included the same way. Any ideas?

**Comment by broguinn** [comment]
I pulled elastic-harvester and attempted to shrinkwrap it directly and got this error message:

```
npm ERR! Error: Problems were encountered
npm ERR! Please correct and try again.
npm ERR! missing: harvester@git+https://github.com/agco/harvesterjs.git#2.2.1, required by elastic-harvesterjs@2.3.5
npm ERR! extraneous: harvesterjs@2.2.1 /Users/braden.oguinn/sites/elastic-harvester/node_modules/harvesterjs
npm ERR!     at shrinkwrap_ (/Users/braden.oguinn/.nvm/v0.10.33/lib/node_modules/npm/lib/shrinkwrap.js:30:15)
npm ERR!     at /Users/braden.oguinn/.nvm/v0.10.33/lib/node_modules/npm/lib/shrinkwrap.js:24:5
npm ERR!     at /Users/braden.oguinn/.nvm/v0.10.33/lib/node_modules/npm/lib/ls.js:45:30
npm ERR!     at /Users/braden.oguinn/.nvm/v0.10.33/lib/node_modules/npm/node_modules/read-installed/read-installed.js:130:5
npm ERR!     at /Users/braden.oguinn/.nvm/v0.10.33/lib/node_modules/npm/node_modules/read-installed/read-installed.js:244:14
npm ERR!     at cb (/Users/braden.oguinn/.nvm/v0.10.33/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
npm ERR!     at /Users/braden.oguinn/.nvm/v0.10.33/lib/node_modules/npm/node_modules/read-installed/read-installed.js:244:14
npm ERR!     at cb (/Users/braden.oguinn/.nvm/v0.10.33/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
npm ERR!     at /Users/braden.oguinn/.nvm/v0.10.33/lib/node_modules/npm/node_modules/read-installed/read-installed.js:244:14
npm ERR!     at cb (/Users/braden.oguinn/.nvm/v0.10.33/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 15.0.0
npm ERR! command "/Users/braden.oguinn/.nvm/v0.10.33/bin/node" "/Users/braden.oguinn/.nvm/v0.10.33/bin/npm" "shrinkwrap"
npm ERR! cwd /Users/braden.oguinn/sites/elastic-harvester
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/braden.oguinn/sites/elastic-harvester/npm-debug.log
npm ERR! not ok code 0
```

**Comment by KenanY** [comment]
@broguinn Does this also occur if you update to the latest stable release of `npm`?

**Comment by KenanY** [comment]
@broguinn Are you still seeing this issue with `npm@2` or `npm@3`?
