### ISSUE TITLE
Error thrown while install/uninstall is performed

### ISSUE THREAD

**Issue by IngwiePhoenix** [npm/npm#10286]
Error (short):
```
Ingwie@Ingwies-Macbook-Pro.local ~/W/BIRD3 $ npm uninstall --save html-loader
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "uninstall" "--save" "html-loader"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6

npm ERR! Cannot read property 'localeCompare' of undefined
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Ingwie/Work/BIRD3/npm-debug.log
```

Error (long): 
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/iojs',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'uninstall',
1 verbose cli   '--save',
1 verbose cli   'html-loader' ]
2 info using npm@3.3.6
3 info using node@v5.0.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly install normalizeTree
8 silly loadCurrentTree Finishing
9 silly loadIdealTree Starting
10 silly install loadIdealTree
11 silly cloneCurrentTree Starting
12 silly install cloneCurrentTreeToIdealTree
13 silly cloneCurrentTree Finishing
14 silly loadShrinkwrap Starting
15 silly install loadShrinkwrap
16 silly loadShrinkwrap Finishing
17 silly loadAllDepsIntoIdealTree Starting
18 silly uninstall loadAllDepsIntoIdealtree
19 verbose stack TypeError: Cannot read property 'localeCompare' of undefined
19 verbose stack     at installOrder (/usr/local/lib/node_modules/npm/lib/install/deps.js:241:32)
19 verbose stack     at Array.sort (native)
19 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/deps.js:240:27
19 verbose stack     at cb (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
19 verbose stack     at resolveWithExistingModule (/usr/local/lib/node_modules/npm/lib/install/deps.js:377:3)
19 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/deps.js:338:7
19 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
19 verbose stack     at Array.forEach (native)
19 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
19 verbose stack     at Array.forEach (native)
20 verbose cwd /Users/Ingwie/Work/BIRD3
21 error Darwin 15.0.0
22 error argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "uninstall" "--save" "html-loader"
23 error node v5.0.0
24 error npm  v3.3.6
25 error Cannot read property 'localeCompare' of undefined
26 error If you need help, you may report this error at:
26 error     <https://github.com/npm/npm/issues>
27 verbose exit [ 1, true ]
```

**Comment by IngwiePhoenix** [comment]
https://github.com/npm/npm/issues/9766
Nevermind. My NPM exploded due to the bug linked above. Updated to 3.3.12, fixed.
