### ISSUE TITLE
npm 'Error: Cannot find module 'graceful-fs'' after running 'npm update -g'

### ISSUE THREAD

**Issue by tzupengwang** [npm/npm#10308]
After I ran ``` npm update -g ```, npm stopped working.
Messages are shown below. using node version 5.0.0 and npm version 3.3.12.
```
$npm                                                                                                          
module.js:339
    throw err;
    ^

Error: Cannot find module 'graceful-fs'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at /usr/local/lib/node_modules/npm/lib/npm.js:16:13
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/npm.js:483:3)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
```

**Comment by tzupengwang** [comment]
Seems to be fixed.
