### ISSUE TITLE
Optional dependency failure should not fail npm rebuild

### ISSUE THREAD

**Issue by jgrund** [npm/npm#10335]
This issue is present using node v5.0.0 and npm v3.3.12

I created a simple `package.json` below to demonstrate the issue:

```
{
  "name": "npm-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "optionalDependencies": {
    "bufferutil": "1.1.0"
  }
}
```

Using that, I do:

`npm i --ignore-scripts`

Which outputs:

```
npm info it worked if it ends with ok
npm verb cli [ '/Users/joegrund/.nvm/versions/node/v5.0.0/bin/node',
npm verb cli   '/Users/joegrund/.nvm/versions/node/v5.0.0/bin/npm',
npm verb cli   'i',
npm verb cli   '--ignore-scripts' ]
npm info using npm@3.3.12
npm info using node@v5.0.0
npm verb request uri https://ubit-artifactory-or.intel.com/artifactory/api/npm/iml-npm-repos/bufferutil
npm verb request no auth needed
npm info attempt registry request try #1 at 3:31:04 PM
npm verb request id f39f7ac2bb0cdda7
npm verb etag dc8976057a6ef915f48d3ac637aa8498561772ab
npm http request GET https://ubit-artifactory-or.intel.com/artifactory/api/npm/iml-npm-repos/bufferutil
npm http 304 https://ubit-artifactory-or.intel.com/artifactory/api/npm/iml-npm-repos/bufferutil
npm verb headers { date: 'Tue, 10 Nov 2015 20:31:05 GMT',
npm verb headers   connection: 'close',
npm verb headers   server: 'Artifactory/3.5.2.1',
npm verb headers   'x-artifactory-id': '06294e5a63088e15:31729cc2:150eb1efeec:-8000' }
npm verb etag https://ubit-artifactory-or.intel.com/artifactory/api/npm/iml-npm-repos/bufferutil from cache
npm verb get saving bufferutil to /Users/joegrund/.npm/ubit-artifactory-or.intel.com/artifactory/api/npm/iml-npm-repos/bufferutil/.cache.json
npm verb cache add spec bufferutil@1.1.0
npm verb addNamed "1.1.0" is a plain semver version for bufferutil
npm verb addNameVersion registry:https://ubit-artifactory-or.intel.com/artifactory/api/npm/iml-npm-repos/bufferutil not in flight; fetching
npm verb get https://ubit-artifactory-or.intel.com/artifactory/api/npm/iml-npm-repos/bufferutil not expired, no request
npm verb afterAdd /Users/joegrund/.npm/bufferutil/1.1.0/package/package.json not in flight; writing
npm verb afterAdd /Users/joegrund/.npm/bufferutil/1.1.0/package/package.json written
npm verb request uri https://ubit-artifactory-or.intel.com/artifactory/api/npm/iml-npm-repos/bindings
npm verb request no auth needed
npm info attempt registry request try #1 at 3:31:06 PM
npm verb etag a54ecd13bf3e07a100fbeece50d9458f57e89754
npm http request GET https://ubit-artifactory-or.intel.com/artifactory/api/npm/iml-npm-repos/bindings
npm verb request uri https://ubit-artifactory-or.intel.com/artifactory/api/npm/iml-npm-repos/nan
npm verb request no auth needed
npm info attempt registry request try #1 at 3:31:06 PM
npm verb etag d8c0efc6d84b512a154012c570280459a3642aba
npm http request GET https://ubit-artifactory-or.intel.com/artifactory/api/npm/iml-npm-repos/nan
npm http 304 https://ubit-artifactory-or.intel.com/artifactory/api/npm/iml-npm-repos/bindings
npm verb headers { date: 'Tue, 10 Nov 2015 20:31:06 GMT',
npm verb headers   connection: 'close',
npm verb headers   server: 'Artifactory/3.5.2.1',
npm verb headers   'x-artifactory-id': '06294e5a63088e15:31729cc2:150eb1efeec:-8000' }
npm verb etag https://ubit-artifactory-or.intel.com/artifactory/api/npm/iml-npm-repos/bindings from cache
npm verb get saving bindings to /Users/joegrund/.npm/ubit-artifactory-or.intel.com/artifactory/api/npm/iml-npm-repos/bindings/.cache.json
npm http 304 https://ubit-artifactory-or.intel.com/artifactory/api/npm/iml-npm-repos/nan
npm verb headers { date: 'Tue, 10 Nov 2015 20:31:06 GMT',
npm verb headers   connection: 'close',
npm verb headers   server: 'Artifactory/3.5.2.1',
npm verb headers   'x-artifactory-id': '06294e5a63088e15:31729cc2:150eb1efeec:-8000' }
npm verb etag https://ubit-artifactory-or.intel.com/artifactory/api/npm/iml-npm-repos/nan from cache
npm verb get saving nan to /Users/joegrund/.npm/ubit-artifactory-or.intel.com/artifactory/api/npm/iml-npm-repos/nan/.cache.json
npm verb cache add spec bindings@1.2.x
npm verb addNamed ">=1.2.0 <1.3.0" is a valid semver range for bindings
npm verb addNameRange registry:https://ubit-artifactory-or.intel.com/artifactory/api/npm/iml-npm-repos/bindings not in flight; fetching
npm verb cache add spec nan@1.8.x
npm verb addNamed ">=1.8.0 <1.9.0" is a valid semver range for nan
npm verb addNameRange registry:https://ubit-artifactory-or.intel.com/artifactory/api/npm/iml-npm-repos/nan not in flight; fetching
npm verb get https://ubit-artifactory-or.intel.com/artifactory/api/npm/iml-npm-repos/bindings not expired, no request
npm verb addNamed "1.2.1" is a plain semver version for bindings
npm verb get https://ubit-artifactory-or.intel.com/artifactory/api/npm/iml-npm-repos/nan not expired, no request
npm verb addNamed "1.8.4" is a plain semver version for nan
npm verb afterAdd /Users/joegrund/.npm/bindings/1.2.1/package/package.json not in flight; writing
npm verb afterAdd /Users/joegrund/.npm/nan/1.8.4/package/package.json not in flight; writing
npm verb afterAdd /Users/joegrund/.npm/nan/1.8.4/package/package.json written
npm verb afterAdd /Users/joegrund/.npm/bindings/1.2.1/package/package.json written
npm verb lock using /Users/joegrund/.npm/_locks/staging-22a155e10f24dc72.lock for /Users/joegrund/Desktop/npm-test/node_modules/.staging
npm verb unbuild node_modules/.staging/bindings-462639533151f4a3e0dc0c5e76301084
npm verb unbuild node_modules/.staging/nan-279bdf377fee16bad220a424c08c6391
npm verb unbuild node_modules/.staging/bufferutil-e91a647949eddd2ebb290cbc2d018f62
npm verb gentlyRm don't care about contents; nuking /Users/joegrund/Desktop/npm-test/node_modules/.staging/bindings-462639533151f4a3e0dc0c5e76301084
npm verb gentlyRm don't care about contents; nuking /Users/joegrund/Desktop/npm-test/node_modules/.staging/nan-279bdf377fee16bad220a424c08c6391
npm verb tar unpack /Users/joegrund/.npm/bindings/1.2.1/package.tgz
npm verb tar unpacking to /Users/joegrund/Desktop/npm-test/node_modules/.staging/bindings-462639533151f4a3e0dc0c5e76301084
npm verb gentlyRm don't care about contents; nuking /Users/joegrund/Desktop/npm-test/node_modules/.staging/bufferutil-e91a647949eddd2ebb290cbc2d018f62
npm verb tar unpack /Users/joegrund/.npm/nan/1.8.4/package.tgz
npm verb tar unpacking to /Users/joegrund/Desktop/npm-test/node_modules/.staging/nan-279bdf377fee16bad220a424c08c6391
npm verb gentlyRm don't care about contents; nuking /Users/joegrund/Desktop/npm-test/node_modules/.staging/bindings-462639533151f4a3e0dc0c5e76301084
npm verb tar unpack /Users/joegrund/.npm/bufferutil/1.1.0/package.tgz
npm verb tar unpacking to /Users/joegrund/Desktop/npm-test/node_modules/.staging/bufferutil-e91a647949eddd2ebb290cbc2d018f62
npm verb gentlyRm don't care about contents; nuking /Users/joegrund/Desktop/npm-test/node_modules/.staging/nan-279bdf377fee16bad220a424c08c6391
npm verb gentlyRm don't care about contents; nuking /Users/joegrund/Desktop/npm-test/node_modules/.staging/bufferutil-e91a647949eddd2ebb290cbc2d018f62
npm info lifecycle bindings@1.2.1~preinstall: bindings@1.2.1
npm info lifecycle nan@1.8.4~preinstall: nan@1.8.4
npm info lifecycle bufferutil@1.1.0~preinstall: bufferutil@1.1.0
npm info linkStuff bindings@1.2.1
npm verb linkBins bindings@1.2.1
npm verb linkMans bindings@1.2.1
npm info linkStuff nan@1.8.4
npm verb linkBins nan@1.8.4
npm verb linkMans nan@1.8.4
npm info linkStuff bufferutil@1.1.0
npm verb linkBins bufferutil@1.1.0
npm verb linkMans bufferutil@1.1.0
npm info lifecycle bindings@1.2.1~install: bindings@1.2.1
npm info lifecycle nan@1.8.4~install: nan@1.8.4
npm info lifecycle bufferutil@1.1.0~install: bufferutil@1.1.0
npm info lifecycle bindings@1.2.1~postinstall: bindings@1.2.1
npm info lifecycle nan@1.8.4~postinstall: nan@1.8.4
npm info lifecycle bufferutil@1.1.0~postinstall: bufferutil@1.1.0
npm verb unlock done using /Users/joegrund/.npm/_locks/staging-22a155e10f24dc72.lock for /Users/joegrund/Desktop/npm-test/node_modules/.staging
npm info lifecycle npm-test@1.0.0~preinstall: npm-test@1.0.0
npm info linkStuff npm-test@1.0.0
npm verb linkBins npm-test@1.0.0
npm verb linkMans npm-test@1.0.0
npm info lifecycle npm-test@1.0.0~install: npm-test@1.0.0
npm info lifecycle npm-test@1.0.0~postinstall: npm-test@1.0.0
npm info lifecycle npm-test@1.0.0~prepublish: npm-test@1.0.0
npm-test@1.0.0 /Users/joegrund/Desktop/npm-test
└─┬ bufferutil@1.1.0
  ├── bindings@1.2.1
  └── nan@1.8.4

npm WARN EPACKAGEJSON npm-test@1.0.0 No description
npm WARN EPACKAGEJSON npm-test@1.0.0 No repository field.
npm verb exit [ 0, true ]
npm info ok
```

Then I do an `npm rebuild` that fails with:

```
npm info it worked if it ends with ok
npm verb cli [ '/Users/joegrund/.nvm/versions/node/v5.0.0/bin/node',
npm verb cli   '/Users/joegrund/.nvm/versions/node/v5.0.0/bin/npm',
npm verb cli   'rebuild' ]
npm info using npm@3.3.12
npm info using node@v5.0.0
npm info readInstalled object
npm verb rebuild path, id [ '/Users/joegrund/Desktop/npm-test', 'npm-test@1.0.0' ]
npm verb rebuild path, id [ '/Users/joegrund/Desktop/npm-test/node_modules/bufferutil',
npm verb rebuild   'bufferutil@1.1.0' ]
npm verb rebuild path, id [ '/Users/joegrund/Desktop/npm-test/node_modules/bindings',
npm verb rebuild   'bindings@1.2.1' ]
npm verb rebuild path, id [ '/Users/joegrund/Desktop/npm-test/node_modules/nan',
npm verb rebuild   'nan@1.8.4' ]
npm info build /Users/joegrund/Desktop/npm-test/node_modules/bufferutil
npm info lifecycle bufferutil@1.1.0~preinstall: bufferutil@1.1.0
npm info linkStuff bufferutil@1.1.0
npm verb linkBins bufferutil@1.1.0
npm verb linkMans bufferutil@1.1.0
npm verb rebuildBundles bufferutil@1.1.0
npm info lifecycle bufferutil@1.1.0~install: bufferutil@1.1.0

> bufferutil@1.1.0 install /Users/joegrund/Desktop/npm-test/node_modules/bufferutil
> node-gyp rebuild

gyp info it worked if it ends with ok
gyp verb cli [ '/Users/joegrund/.nvm/versions/node/v5.0.0/bin/node',
gyp verb cli   '/Users/joegrund/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild' ]
gyp info using node-gyp@3.0.3
gyp info using node@5.0.0 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "/usr/bin/python2.6" in the PATH
gyp verb `which` succeeded /usr/bin/python2.6 /usr/bin/python2.6
gyp verb check python version `/usr/bin/python2.6 -c "import platform; print(platform.python_version());"` returned: "2.6.9\n"
gyp verb get node dir no --target version specified, falling back to host node version: 5.0.0
gyp verb command install [ '5.0.0' ]
gyp verb install input version string "5.0.0"
gyp verb install installing version: 5.0.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 5.0.0
gyp verb build dir attempting to create "build" dir: /Users/joegrund/Desktop/npm-test/node_modules/bufferutil/build
gyp verb build dir "build" dir needed to be created? /Users/joegrund/Desktop/npm-test/node_modules/bufferutil/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /Users/joegrund/Desktop/npm-test/node_modules/bufferutil/build/config.gypi
gyp verb config.gypi checking for gypi file: /Users/joegrund/Desktop/npm-test/node_modules/bufferutil/config.gypi
gyp verb common.gypi checking for gypi file: /Users/joegrund/Desktop/npm-test/node_modules/bufferutil/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/bin/python2.6
gyp info spawn args [ '/Users/joegrund/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/joegrund/Desktop/npm-test/node_modules/bufferutil/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/joegrund/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/joegrund/.node-gyp/5.0.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/joegrund/.node-gyp/5.0.0',
gyp info spawn args   '-Dnode_gyp_dir=/Users/joegrund/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/joegrund/Desktop/npm-test/node_modules/bufferutil',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /Users/joegrund/.node-gyp/5.0.0
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
  c++ '-DNODE_GYP_MODULE_NAME=bufferutil' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DBUILDING_NODE_EXTENSION' -I/Users/joegrund/.node-gyp/5.0.0/include/node -I/Users/joegrund/.node-gyp/5.0.0/src -I/Users/joegrund/.node-gyp/5.0.0/deps/uv/include -I/Users/joegrund/.node-gyp/5.0.0/deps/v8/include -I../../nan  -Os -gdwarf-2 -mmacosx-version-min=10.5 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -std=gnu++0x -fno-rtti -fno-exceptions -fno-threadsafe-statics -fno-strict-aliasing -MMD -MF ./Release/.deps/Release/obj.target/bufferutil/src/bufferutil.o.d.raw  -c -o Release/obj.target/bufferutil/src/bufferutil.o ../src/bufferutil.cc
In file included from ../src/bufferutil.cc:16:
../../nan/nan.h:261:25: error: redefinition of '_NanEnsureLocal'
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                        ^
../../nan/nan.h:256:25: note: previous definition is here
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                        ^
../../nan/nan.h:661:13: error: no member named 'smalloc' in namespace 'node'
    , node::smalloc::FreeCallback callback
      ~~~~~~^
../../nan/nan.h:672:12: error: no matching function for call to 'New'
    return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
           ^~~~~~~~~~~~~~~~~
/Users/joegrund/.node-gyp/5.0.0/include/node/node_buffer.h:31:40: note: candidate function not viable: no known conversion from 'uint32_t' (aka 'unsigned int') to 'enum encoding' for 3rd argument
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/joegrund/.node-gyp/5.0.0/include/node/node_buffer.h:43:40: note: candidate function not viable: 2nd argument ('const char *') would lose const qualifier
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/joegrund/.node-gyp/5.0.0/include/node/node_buffer.h:28:40: note: candidate function not viable: requires 2 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
                                       ^
/Users/joegrund/.node-gyp/5.0.0/include/node/node_buffer.h:36:40: note: candidate function not viable: requires 5 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
In file included from ../src/bufferutil.cc:16:
../../nan/nan.h:676:12: error: no viable conversion from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object>'
    return node::Buffer::New(v8::Isolate::GetCurrent(), size);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/joegrund/.node-gyp/5.0.0/include/node/v8.h:210:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'v8::MaybeLocal<v8::Object>' to
      'const v8::Local<v8::Object> &' for 1st argument
class Local {
      ^
/Users/joegrund/.node-gyp/5.0.0/include/node/v8.h:210:7: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'v8::MaybeLocal<v8::Object>' to
      'v8::Local<v8::Object> &&' for 1st argument
class Local {
      ^
/Users/joegrund/.node-gyp/5.0.0/include/node/v8.h:214:13: note: candidate template ignored: could not match 'Local' against 'MaybeLocal'
  V8_INLINE Local(Local<S> that)
            ^
/Users/joegrund/.node-gyp/5.0.0/include/node/v8.h:326:13: note: candidate template ignored: could not match 'S *' against 'v8::MaybeLocal<v8::Object>'
  V8_INLINE Local(S* that)
            ^
In file included from ../src/bufferutil.cc:16:
../../nan/nan.h:683:26: error: no member named 'Use' in namespace 'node::Buffer'
    return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
           ~~~~~~~~~~~~~~^
In file included from ../src/bufferutil.cc:7:
/Users/joegrund/.node-gyp/5.0.0/include/node/v8.h:221:5: error: assigning to 'v8::Primitive *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/joegrund/.node-gyp/5.0.0/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../../nan/nan.h:414:12: note: in instantiation of function template specialization 'v8::Local<v8::Primitive>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(v8::Undefined(v8::Isolate::GetCurrent())));
           ^
../../nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../src/bufferutil.cc:7:
/Users/joegrund/.node-gyp/5.0.0/include/node/v8.h:221:5: error: assigning to 'v8::Boolean *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/joegrund/.node-gyp/5.0.0/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../../nan/nan.h:424:12: note: in instantiation of function template specialization 'v8::Local<v8::Boolean>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(v8::True(v8::Isolate::GetCurrent())));
           ^
../../nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../src/bufferutil.cc:7:
/Users/joegrund/.node-gyp/5.0.0/include/node/v8.h:221:5: error: assigning to 'v8::Function *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/joegrund/.node-gyp/5.0.0/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../../nan/nan.h:1514:12: note: in instantiation of function template specialization 'v8::Local<v8::Function>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(handle)->Get(kCallbackIndex)
           ^
../../nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../src/bufferutil.cc:7:
/Users/joegrund/.node-gyp/5.0.0/include/node/v8.h:221:5: error: assigning to 'v8::Object *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/joegrund/.node-gyp/5.0.0/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../../nan/nan.h:1632:12: note: in instantiation of function template specialization 'v8::Local<v8::Object>::Local<v8::Value>' requested here
    return NanEscapeScope(handle->Get(NanNew(key)).As<v8::Object>());
           ^
../../nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
9 errors generated.
make: *** [Release/obj.target/bufferutil/src/bufferutil.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/joegrund/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/Users/joegrund/.nvm/versions/node/v5.0.0/bin/node" "/Users/joegrund/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/joegrund/Desktop/npm-test/node_modules/bufferutil
gyp ERR! node -v v5.0.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok

npm verb lifecycle bufferutil@1.1.0~install: unsafe-perm in lifecycle true
npm verb lifecycle bufferutil@1.1.0~install: PATH: /Users/joegrund/.nvm/versions/node/v5.0.0/lib/node_modules/npm/bin/node-gyp-bin:/Users/joegrund/Desktop/npm-test/node_modules/bufferutil/node_modules/.bin:/Users/joegrund/Desktop/npm-test/node_modules/.bin:/Users/joegrund/.nvm/versions/node/v5.0.0/bin:/Users/joegrund/Envs/py26/bin:/usr/local/bin:/usr/local/share/npm/bin:/usr/local/sbin:/Users/joegrund/Repos/depot_tools:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
npm verb lifecycle bufferutil@1.1.0~install: CWD: /Users/joegrund/Desktop/npm-test/node_modules/bufferutil
npm info lifecycle bufferutil@1.1.0~install: Failed to exec install script
npm verb stack Error: bufferutil@1.1.0 install: `node-gyp rebuild`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/Users/joegrund/.nvm/versions/node/v5.0.0/lib/node_modules/npm/lib/utils/lifecycle.js:232:16)
npm verb stack     at emitTwo (events.js:87:13)
npm verb stack     at EventEmitter.emit (events.js:172:7)
npm verb stack     at ChildProcess.<anonymous> (/Users/joegrund/.nvm/versions/node/v5.0.0/lib/node_modules/npm/lib/utils/spawn.js:24:14)
npm verb stack     at emitTwo (events.js:87:13)
npm verb stack     at ChildProcess.emit (events.js:172:7)
npm verb stack     at maybeClose (internal/child_process.js:818:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
npm verb pkgid bufferutil@1.1.0
npm verb cwd /Users/joegrund/Desktop/npm-test
npm ERR! Darwin 15.0.0
npm ERR! argv "/Users/joegrund/.nvm/versions/node/v5.0.0/bin/node" "/Users/joegrund/.nvm/versions/node/v5.0.0/bin/npm" "rebuild"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! bufferutil@1.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bufferutil@1.1.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bufferutil package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bufferutil
npm ERR! There is likely additional logging output above.
npm verb exit [ 1, true ]

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/joegrund/Desktop/npm-test/npm-debug.log
```

In this case the rebuild is treating the optional dependency as mandatory.

**Comment by othiym23** [comment]
Thanks for pulling this out of #5095. Is `--ignore-scripts` a necessary part of reproducing this issue? (That could be an important clue.)

**Comment by jgrund** [comment]
@othiym23 Yes. Since it's an `optionalDependency`. It never makes it with `npm install` as it fails the build step and is taken out of the resulting tree.

**Comment by jgrund** [comment]
FWIW I just reproduced the same issue using npm@2.14.10

**Comment by fenduru** [comment]
Assuming you have a package `foo` that lists an optional dependency that fails to build:

```
npm install --save foo # exit code 0
npm install # exit code 1
```
