### ISSUE TITLE
EPEERINVALID Unmet peer dependency when actually available

### ISSUE THREAD

**Issue by jamime** [npm/npm#10365]
Trying to install `generator-jshint` which has
```
  "peerDependencies": {
    "yo": ">=1.0.0"
  }
```
as you can see I have 1.5.0 installed but installation still fails.

```
$ npm list -g yo
c:\Program Files (x86)\nodejs
└── yo@1.5.0

$ npm install -g generator-jshint
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
c:\Program Files (x86)\nodejs
├── generator-jshint@0.0.0
└── UNMET PEER DEPENDENCY yo@>=1.0.0

npm WARN EPEERINVALID generator-jshint@0.0.0 requires a peer of yo@>=1.0.0 but none was installed.
```

**Comment by gabrielpconceicao** [comment]
```yo``` is installed globally? Try with ```npm i -g yo```

**Comment by jamime** [comment]
It is already installed globally.

**Comment by gabrielpconceicao** [comment]
Try  ```npm cache clean```.

**Comment by fernandoneto** [comment]
@jamime did you try to remove `yo` 1.5.0 and install 1.0.0 ??

**Comment by fernandoneto** [comment]
#4749

**Comment by jamime** [comment]
Fixed by running `npm cache clean` then `npm install -g yo generator-jshint` again. Not too sure what went wrong. `yo doctor` complained about a different` NODE_PATH` so maybe some conflict there?

**Comment by Luchillo** [comment]
I'm having some problem with it, npm gives me that warning when installing, it doesn't with `gulp-tslint@latest`, but in both cases when trying to use it then shows an error like:
```
aplicaciones2@MacBook-Pro-de-aplicacioes-2:~/Documents/Programming/OSGroup/taoappionic$ npm i --save gulp-tslint@latest
npm WARN deprecated lodash@2.4.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^3.0.0.
npm WARN gulp-tslint@4.1.0 requires a peer of tslint@^3 || >=3.1.0-dev but none was installed.
npm WARN ionic-project@1.1.1 No repository field.
npm WARN ionic-project@1.1.1 No license field.
aplicaciones2@MacBook-Pro-de-aplicacioes-2:~/Documents/Programming/OSGroup/taoappionic$ gulp tslint
module.js:340
    throw err;
    ^

Error: Cannot find module 'tslint'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/aplicaciones2/Documents/Programming/OSGroup/taoappionic/node_modules/gulp-tslint/index.js:7:14)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
```
Any ideas how to fix even after `npm cache clean`?
