### ISSUE TITLE
npm install   Error: Cannot find module 'extend'

### ISSUE THREAD

**Issue by scalaview** [npm/npm#10399]
Hi, I got the issue like that when I run npm install

```shell
Error: Cannot find module 'extend'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/index.js:17:29)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
npm ERR! Darwin 14.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v3.3.6
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'extend'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

what's the problem, please
I want a solution, please

**Comment by jokeyrhyme** [comment]
You might need to reinstall npm.

I've noticed that occasional install failures can leave packages (including npm itself) in an incomplete state, with dependencies missing.

**Comment by scalaview** [comment]
thx
I had reinstall node , and the problem not appeared again
