### ISSUE TITLE
'npm rebuild' tries to connect to nodejs.org:80 again after 'npm install --ignore-scripts' downloaded all sources

### ISSUE THREAD

**Issue by yurivict** [npm/npm#10402]
I am trying to make a FreeBSD package for etherpad-lite. Packaging process first downloads all sources (npm install --ignore-scripts), and then builds it. The build phase can't connect anywhere. Yet it attempts to connect to nodejs.org:80.

I compared the trees before and after the build, and no sources have been downloaded by 'npm rebuild'.

'npm rebuild' shouldn't try connecting anywhere.

```
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: getaddrinfo EAI_FAIL nodejs.org:80
gyp ERR! stack     at Object.exports._errnoException (util.js:874:11)
gyp ERR! stack     at errnoException (dns.js:31:15)
gyp ERR! stack     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)
gyp ERR! System FreeBSD 10.2-RELEASE-p6
gyp ERR! command "/usr/local/bin/node" "/wrkdirs/usr/ports/www/etherpad-lite/work/etherpad-lite-1.5.7/node_modules/ep_etherpad-lite/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/wrkdirs/usr/ports/www/etherpad-lite/work/etherpad-lite-1.5.7/node_modules/ep_etherpad-lite/node_modules/sqlite3/lib/binding/node-v46-freebsd-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/wrkdirs/usr/ports/www/etherpad-lite/work/etherpad-lite-1.5.7/node_modules/ep_etherpad-lite/node_modules/sqlite3/lib/binding/node-v46-freebsd-x64"
gyp ERR! cwd /wrkdirs/usr/ports/www/etherpad-lite/work/etherpad-lite-1.5.7/node_modules/ep_etherpad-lite/node_modules/sqlite3
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
node-pre-gyp ERR! build error
```

**Comment by othiym23** [comment]
```
gyp ERR! command "/usr/local/bin/node" "/wrkdirs/usr/ports/www/etherpad-lite/work/etherpad-lite-1.5.7/node_modules/ep_etherpad-lite/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/wrkdirs/usr/ports/www/etherpad-lite/work/etherpad-lite-1.5.7/node_modules/ep_etherpad-lite/node_modules/sqlite3/lib/binding/node-v46-freebsd-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/wrkdirs/usr/ports/www/etherpad-lite/work/etherpad-lite-1.5.7/node_modules/ep_etherpad-lite/node_modules/sqlite3/lib/binding/node-v46-freebsd-x64"
```

This behavior is due to `node-gyp`, which checks to see if there are updated Node.js headers for it to download when performing a native build. It _is_ a little strange that this process is hidden behind `npm rebuild`, but in order for this behavior to be changed, it will need to be [changed in `node-gyp` first](https://github.com/nodejs/node-gyp/issues).
