### ISSUE TITLE
3.3.11/3.3.12 seems to break (maybe de-dupe related?)

### ISSUE THREAD

**Issue by stefanpenner** [npm/npm#10458]
3.3.11 + 3.3.12 seems to fail to install some dependencies.

Our builds (ember-cli builds https://travis-ci.org/ember-cli/ember-cli/jobs/91697889) recently started failing. It seems to be related to missing dependencies as of the 3.3.11 release (3.3.10 appears to work correctly)

crashing output.
```
➜  ember-cli git:(master) npm test

> ember-cli@1.13.8 test /Users/stefanpenner/src/ember-cli
> node tests/runner

module.js:340
    throw err;
    ^

Error: Cannot find module 'glob'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/stefanpenner/src/ember-cli/tests/runner.js:3:12)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:457:10)
npm ERR! Test failed.  See above for more details.
```

on [ember-cli#master](https://github.com/ember-cli//ember-cli)
the current project has glob as a dependency:

```
➜  ember-cli git:(master) cat package.json | jq '.dependencies' | grep glob
  "glob": "5.0.13",
```

after 
```
rm -rf node_modules
npm install -g npm@3.3.11
npm install
```

node_modules is missing a glob at the root
```
➜  ember-cli git:(master) ls node_modules/ | grep glob
global
globals
```

many globs are installed, but not at the root

```
➜  ember-cli git:(master) npm ls glob
ember-cli@1.13.8 /Users/stefanpenner/src/ember-cli
├─┬ bower@1.6.5
│ ├── glob@4.5.3
│ └─┬ rimraf@2.4.3
│   └── glob@5.0.15
├─┬ broccoli-babel-transpiler@5.5.0
│ └─┬ babel-core@5.8.34
│   └─┬ regenerator@0.8.40
│     └─┬ commoner@0.10.4
│       └── glob@5.0.15
├─┬ broccoli-filter@1.2.2
│ └─┬ broccoli-kitchen-sink-helpers@0.2.9
│   └── glob@5.0.15
├─┬ findup-sync@0.2.1
│ └── glob@4.3.5
├─┬ mocha@2.3.4
│ └── glob@3.2.3
├─┬ mocha-jshint@2.2.5
│ └─┬ jshint@2.7.0
│   └─┬ cli@0.6.6
│     └── glob@3.2.11
├─┬ mocha-only-detector@0.0.2
│ └── glob@4.5.3
├─┬ npm@2.14.10
│ ├── glob@5.0.15
│ └─┬ node-gyp@3.0.3
│   └── glob@4.5.3
├─┬ rimraf@2.3.2
│ └── glob@4.5.3
└─┬ tmp-sync@1.1.0
  └─┬ fs-sync@0.2.6
    └── glob@4.0.6
```

Switching back to `npm@3.3.10` resolves the issue.

**Comment by stefanpenner** [comment]
related downstream issue: https://github.com/ember-cli/ember-cli/issues/5126

**Comment by iarna** [comment]
This should be fixed by #10338 and 3.4.1

**Comment by stefanpenner** [comment]
Will test, thanks

**Comment by stefanpenner** [comment]
I was having trouble upgrading to npm due to this issue, but falling back to previous version of node that did not bundle the broken versions, I was able to confirm 3.4.1 does the trick

**Comment by busches** [comment]
@stefanpenner can this be closed now?

**Comment by stefanpenner** [comment]
Will reopen if i see again. Thanks for the fix!
