### ISSUE TITLE
npm-shrinkwrap: install with git dependency fails on Windows

### ISSUE THREAD

**Issue by dwickern** [npm/npm#10461]
This only fails on Windows CI and only after I used npm-shrinkwrap. The git command works fine if I run it manually.

```
Z:\>git --version
git version 2.6.3.windows.1
```

From npm-debug.log:

```
82432 verbose stack Error: Command failed: git -c core.longpaths=true clone --template=C:\Windows\system32\config\systemprofile\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.com/rynomad/jsbn.git C:\Windows\system32\config\systemprofile\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-rynomad-jsbn-git-bb522b0124f75424f89d49446c40a87111942c7b-5eacfb5ecac35cf3eb2fc8aac95d0469
82432 verbose stack fatal: Could not get current working directory: No such file or directory
82432 verbose stack
82432 verbose stack     at ChildProcess.exithandler (child_process.js:203:12)
82432 verbose stack     at emitTwo (events.js:87:13)
82432 verbose stack     at ChildProcess.emit (events.js:172:7)
82432 verbose stack     at maybeClose (internal/child_process.js:818:16)
82432 verbose stack     at Socket.<anonymous> (internal/child_process.js:319:11)
82432 verbose stack     at emitOne (events.js:77:13)
82432 verbose stack     at Socket.emit (events.js:169:7)
82432 verbose stack     at Pipe._onclose (net.js:469:12)
82433 verbose cwd C:\TeamCity\buildAgent\work\b419e5c96745e5f\ui
82434 error Windows_NT 6.1.7601
82435 error argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
82436 error node v4.2.1
82437 error npm  v3.3.9
82438 error code 128
82439 error Command failed: git -c core.longpaths=true clone --template=C:\Windows\system32\config\systemprofile\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.com/rynomad/jsbn.git C:\Windows\system32\config\systemprofile\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-rynomad-jsbn-git-bb522b0124f75424f89d49446c40a87111942c7b-5eacfb5ecac35cf3eb2fc8aac95d0469
82439 error fatal: Could not get current working directory: No such file or directory
82440 error If you need help, you may report this error at:
82440 error     <https://github.com/npm/npm/issues>
82441 verbose exit [ 1, true ]
```

[npm-debug.log](https://gist.github.com/dwickern/0079bcd69f9c707e53d1)

**Comment by Layoric** [comment]
If it's any help, I came across the same issue. It seems to be related to the version of git installed. I recently setup a new CI and installed the latest git (2.6.4 64bit) and had the same problem.

I reverted back to an older version of git (just one I had on hand) v1.9.5 and problem went away.

Hope that helps.
