### ISSUE TITLE
Failed to publish package (403 error)

### ISSUE THREAD

**Issue by gig177** [npm/npm#10473]
.npmrc is ok
```bash
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/home/evgeniy/.node/bin/npm', 'publish' ]
2 info using npm@3.4.0
3 info using node@v5.0.0
4 verbose publish [ '.' ]
5 silly cache add args [ '.', null ]
6 verbose cache add spec .
7 silly cache add parsed spec Result {
7 silly cache add   raw: '.',
7 silly cache add   scope: null,
7 silly cache add   name: null,
7 silly cache add   rawSpec: '.',
7 silly cache add   spec: '/home/evgeniy/github/bb-utils',
7 silly cache add   type: 'directory' }
8 verbose addLocalDirectory /home/evgeniy/.npm/bb-utils/0.1.0/package.tgz not in flight; packing
9 info lifecycle bb-utils@0.1.0~prepublish: bb-utils@0.1.0
10 silly lifecycle bb-utils@0.1.0~prepublish: no script for prepublish, continuing
11 verbose tar pack [ '/home/evgeniy/.npm/bb-utils/0.1.0/package.tgz',
11 verbose tar pack   '/home/evgeniy/github/bb-utils' ]
12 verbose tarball /home/evgeniy/.npm/bb-utils/0.1.0/package.tgz
13 verbose folder /home/evgeniy/github/bb-utils
14 verbose addLocalTarball adding from inside cache /home/evgeniy/.npm/bb-utils/0.1.0/package.tgz
15 silly cache afterAdd bb-utils@0.1.0
16 verbose afterAdd /home/evgeniy/.npm/bb-utils/0.1.0/package/package.json not in flight; writing
17 verbose afterAdd /home/evgeniy/.npm/bb-utils/0.1.0/package/package.json written
18 silly publish { name: 'bb-utils',
18 silly publish   registry: 'npm',
18 silly publish   version: '0.1.0',
18 silly publish   description: 'Backbone utilities',
18 silly publish   main: 'lib/index.js',
18 silly publish   repository:
18 silly publish    { type: 'git',
18 silly publish      url: 'git+https://github.com/gig177/bb-utils.git' },
18 silly publish   author: { name: 'Evgeniy Poturaev' },
18 silly publish   scripts: { test: 'mocha' },
18 silly publish   license: 'ISC',
18 silly publish   bugs: { url: 'https://github.com/gig177/bb-utils/issues' },
18 silly publish   devDependencies:
18 silly publish    { backbone: '^1.2.3',
18 silly publish      chai: '^3.4.1',
18 silly publish      sinon: '^1.17.2',
18 silly publish      'sinon-chai': '^2.8.0' },
18 silly publish   dependencies: { underscore: '^1.8.3' },
18 silly publish   jspm: { main: './index', directories: { lib: 'lib' } },
18 silly publish   readme: '# bb-utils\nSimple example:\n```javascript\nvar _ = require(\'underscore\'),\n    Events = require(\'backbone\').Events;\nvar onAll = require(\'../lib/on_all\');\n    \nvar view = _.extend({}, Events),\n    collection = _.extend({}, Events);\nonAll({ \'animation-complete\': view, \'sync\': collection }, { \'render-page\': view }, () => {\n    console.log(\'render page after animation and sync collection\'); // [1]\n});\n\nview.trigger(\'animation-complete\'); \ncollection.trigger(\'sync\'); // will trigger the =>[1] statement\n\nview.trigger(\'animation-complete\'); \nview.trigger(\'render-page\'); // will clean the events stack\n\ncollection.trigger(\'sync\');\nview.trigger(\'animation-complete\'); // will trigger the =>[1] statement\n```\n',
18 silly publish   readmeFilename: 'README.md',
18 silly publish   gitHead: '9062b08d345069cacf5608bd8eb648cff353ab5e',
18 silly publish   homepage: 'https://github.com/gig177/bb-utils#readme',
18 silly publish   _id: 'bb-utils@0.1.0',
18 silly publish   _shasum: '8f8c1ad7dd5ef04c0dc4b5267a2e1df685c4de60',
18 silly publish   _from: '.' }
19 verbose getPublishConfig undefined
20 silly mapToRegistry name bb-utils
21 silly mapToRegistry using default registry
22 silly mapToRegistry registry https://registry.npmjs.org/
23 silly mapToRegistry uri https://registry.npmjs.org/bb-utils
24 verbose publish registryBase https://registry.npmjs.org/
25 silly publish uploading /home/evgeniy/.npm/bb-utils/0.1.0/package.tgz
26 verbose request uri https://registry.npmjs.org/bb-utils
27 verbose request sending authorization for write operation
28 info attempt registry request try #1 at 12:31:00 PM
29 verbose request using bearer token for auth
30 verbose request id 1fda238cc8eb85d3
31 http request PUT https://registry.npmjs.org/bb-utils
32 http 403 https://registry.npmjs.org/bb-utils
33 verbose headers { 'content-type': 'application/json',
33 verbose headers   'cache-control': 'max-age=60',
33 verbose headers   'content-length': '100',
33 verbose headers   'accept-ranges': 'bytes',
33 verbose headers   date: 'Thu, 19 Nov 2015 09:31:01 GMT',
33 verbose headers   via: '1.1 varnish',
33 verbose headers   connection: 'keep-alive',
33 verbose headers   'x-served-by': 'cache-fra1239-FRA',
33 verbose headers   'x-cache': 'MISS',
33 verbose headers   'x-cache-hits': '0',
33 verbose headers   'x-timer': 'S1447925460.591803,VS0,VE688' }
34 verbose request invalidating /home/evgeniy/.npm/registry.npmjs.org/bb-utils on PUT
35 error publish Failed PUT 403
36 verbose stack Error: You do not have permission to publish 'bb-utils'. Are you logged in as the correct user? : bb-utils
36 verbose stack     at makeError (/home/evgeniy/.node/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
36 verbose stack     at CachingRegistryClient.<anonymous> (/home/evgeniy/.node/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:252:14)
36 verbose stack     at Request._callback (/home/evgeniy/.node/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
36 verbose stack     at Request.self.callback (/home/evgeniy/.node/lib/node_modules/npm/node_modules/request/request.js:198:22)
36 verbose stack     at emitTwo (events.js:87:13)
36 verbose stack     at Request.emit (events.js:172:7)
36 verbose stack     at Request.<anonymous> (/home/evgeniy/.node/lib/node_modules/npm/node_modules/request/request.js:1082:10)
36 verbose stack     at emitOne (events.js:82:20)
36 verbose stack     at Request.emit (events.js:169:7)
36 verbose stack     at IncomingMessage.<anonymous> (/home/evgeniy/.node/lib/node_modules/npm/node_modules/request/request.js:1009:12)
37 verbose statusCode 403
38 verbose pkgid bb-utils
39 verbose cwd /home/evgeniy/github/bb-utils
40 error Linux 4.2.5-1-ARCH
41 error argv "/usr/bin/node" "/home/evgeniy/.node/bin/npm" "publish"
42 error node v5.0.0
43 error npm  v3.4.0
44 error code E403
45 error You do not have permission to publish 'bb-utils'. Are you logged in as the correct user? : bb-utils
46 error If you need help, you may report this error at:
46 error     <https://github.com/npm/npm/issues>
47 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
@gig177 Looks like a [`bb-utils` package](https://www.npmjs.com/package/bb-utils) already exists. Do you have permission to publish new versions of this package? You never say in your issue report. If you do not have permission then I do not see how `npm` is at fault here for telling you so.

**Comment by gig177** [comment]
Sorry for reporting this issue. The `bb-utils` package already exists. But the error reporting of `$ npm publish`  is not obvious.
