### ISSUE TITLE
npm install failure for hoodie-cli

### ISSUE THREAD

**Issue by Web-Dev-Rich** [npm/npm#10480]
Received the following when attempting to run `npm install -g hoodie-cli`.
Terminal out put was:
```
npm WARN locking Error: EACCES, open '/Users/rich/.npm/_locks/hoodie-cli-f52482f833c71877.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/rich/.npm/_locks/hoodie-cli-f52482f833c71877.lock failed { [Error: EACCES, open '/Users/rich/.npm/_locks/hoodie-cli-f52482f833c71877.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/rich/.npm/_locks/hoodie-cli-f52482f833c71877.lock' }
npm ERR! Darwin 15.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "hoodie-cli"
npm ERR! node v0.12.3
npm ERR! npm  v2.9.1

npm ERR! Attempt to unlock /usr/local/lib/node_modules/hoodie-cli, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/rich/hoodie/test_app/npm-debug.log
```
Any help/suggestions much appreciated.

Sorry could not attach log file, contents are:
```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'install', '-g', 'hoodie-cli' ]
2 info using npm@2.9.1
3 info using node@v0.12.3
4 verbose install initial load of /usr/local/lib/package.json
5 verbose readDependencies loading dependencies from /usr/local/lib/package.json
6 silly cache add args [ 'hoodie-cli', null ]
7 verbose cache add spec hoodie-cli
8 silly cache add parsed spec { raw: 'hoodie-cli',
8 silly cache add   scope: null,
8 silly cache add   name: 'hoodie-cli',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: '*',
8 silly cache add   type: 'range' }
9 silly addNamed hoodie-cli@*
10 verbose addNamed "*" is a valid semver range for hoodie-cli
11 silly addNameRange { name: 'hoodie-cli', range: '*', hasData: false }
12 silly mapToRegistry name hoodie-cli
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/hoodie-cli
16 verbose addNameRange registry:https://registry.npmjs.org/hoodie-cli not in flight; fetching
17 verbose request uri https://registry.npmjs.org/hoodie-cli
18 verbose request no auth needed
19 info attempt registry request try #1 at 3:46:45 PM
20 verbose request id 400d9709fa79cc20
21 verbose etag "6C8WC7YSWLGIZ0F6XG3O7FT8H"
22 http request GET https://registry.npmjs.org/hoodie-cli
23 http 304 https://registry.npmjs.org/hoodie-cli
24 silly get cb [ 304,
24 silly get   { date: 'Thu, 19 Nov 2015 15:46:45 GMT',
24 silly get     via: '1.1 varnish',
24 silly get     'cache-control': 'max-age=60',
24 silly get     etag: '"6C8WC7YSWLGIZ0F6XG3O7FT8H"',
24 silly get     age: '0',
24 silly get     connection: 'keep-alive',
24 silly get     'x-served-by': 'cache-lcy1126-LCY',
24 silly get     'x-cache': 'MISS',
24 silly get     'x-cache-hits': '0',
24 silly get     'x-timer': 'S1447948005.080284,VS0,VE305',
24 silly get     vary: 'Accept' } ]
25 verbose etag https://registry.npmjs.org/hoodie-cli from cache
26 verbose get saving hoodie-cli to /Users/rich/.npm/registry.npmjs.org/hoodie-cli/.cache.json
27 silly addNameRange number 2 { name: 'hoodie-cli', range: '*', hasData: true }
28 silly addNameRange versions [ 'hoodie-cli',
28 silly addNameRange   [ '0.1.2',
28 silly addNameRange     '0.1.3',
28 silly addNameRange     '0.2.0',
28 silly addNameRange     '0.2.1',
28 silly addNameRange     '0.2.2',
28 silly addNameRange     '0.2.3',
28 silly addNameRange     '0.2.4',
28 silly addNameRange     '0.2.5',
28 silly addNameRange     '0.2.6',
28 silly addNameRange     '0.2.7',
28 silly addNameRange     '0.3.0',
28 silly addNameRange     '0.3.1',
28 silly addNameRange     '0.3.2',
28 silly addNameRange     '0.4.0',
28 silly addNameRange     '0.4.1',
28 silly addNameRange     '0.4.2',
28 silly addNameRange     '0.4.3',
28 silly addNameRange     '0.4.4',
28 silly addNameRange     '0.4.5',
28 silly addNameRange     '0.4.6',
28 silly addNameRange     '0.4.7',
28 silly addNameRange     '0.4.8',
28 silly addNameRange     '0.4.9',
28 silly addNameRange     '0.4.10',
28 silly addNameRange     '0.4.11',
28 silly addNameRange     '0.4.12',
28 silly addNameRange     '0.4.13',
28 silly addNameRange     '0.4.14',
28 silly addNameRange     '0.4.16',
28 silly addNameRange     '0.4.17',
28 silly addNameRange     '0.5.0',
28 silly addNameRange     '0.5.1',
28 silly addNameRange     '0.5.2',
28 silly addNameRange     '0.5.3',
28 silly addNameRange     '0.5.4',
28 silly addNameRange     '0.5.5',
28 silly addNameRange     '0.5.6',
28 silly addNameRange     '0.6.0',
28 silly addNameRange     '0.6.1',
28 silly addNameRange     '0.6.2',
28 silly addNameRange     '0.6.3' ] ]
29 silly addNamed hoodie-cli@0.6.3
30 verbose addNamed "0.6.3" is a plain semver version for hoodie-cli
31 silly cache afterAdd hoodie-cli@0.6.3
32 verbose afterAdd /Users/rich/.npm/hoodie-cli/0.6.3/package/package.json not in flight; writing
33 verbose afterAdd /Users/rich/.npm/hoodie-cli/0.6.3/package/package.json written
34 silly install resolved [ { name: 'hoodie-cli',
34 silly install resolved     description: 'Hoodie command-line interface.',
34 silly install resolved     version: '0.6.3',
34 silly install resolved     preferGlobal: true,
34 silly install resolved     dependencies:
34 silly install resolved      { async: '^0.9.0',
34 silly install resolved        'cli-color': '^0.3.2',
34 silly install resolved        colors: '^0.6.2',
34 silly install resolved        'fixture-stdout': '^0.2.1',
34 silly install resolved        'graceful-fs': '^3.0.2',
34 silly install resolved        ini: '^1.2.1',
34 silly install resolved        insight: '^0.4.1',
34 silly install resolved        npm: '^2.1.4',
34 silly install resolved        open: '0.0.5',
34 silly install resolved        optimist: '^0.6.1',
34 silly install resolved        prompt: '^0.2.13',
34 silly install resolved        rimraf: '^2.2.8',
34 silly install resolved        semver: '^2.3.2',
34 silly install resolved        shelljs: '^0.3.0',
34 silly install resolved        underscore: '^1.6.0',
34 silly install resolved        'update-notifier': '^0.2.0' },
34 silly install resolved     engines: { node: '>=0.10.22' },
34 silly install resolved     keywords: [ 'cli', 'hoodie', 'hood.ie', 'hoodie.js' ],
34 silly install resolved     repository:
34 silly install resolved      { type: 'git',
34 silly install resolved        url: 'git+https://github.com/hoodiehq/hoodie-cli.git' },
34 silly install resolved     scripts: { test: 'grunt ci --verbose' },
34 silly install resolved     bin: { hoodie: './bin/hoodie' },
34 silly install resolved     author: { name: 'Sven Lito', email: 'sven@thehoodiefirm.com' },
34 silly install resolved     devDependencies:
34 silly install resolved      { 'expect.js': '^0.3.1',
34 silly install resolved        grunt: '^0.4.5',
34 silly install resolved        'grunt-contrib-jshint': '^0.10.0',
34 silly install resolved        'grunt-contrib-watch': '^0.6.1',
34 silly install resolved        'grunt-release-hoodie': '^2.8.0',
34 silly install resolved        'grunt-simple-mocha': '^0.4.0',
34 silly install resolved        'load-grunt-tasks': '^0.6.0',
34 silly install resolved        mocha: '^1.20.1',
34 silly install resolved        sinon: '^1.10.3' },
34 silly install resolved     codename: 'superb-ox',
34 silly install resolved     gitHead: '68636461cbbcb1f9005772531dc663e04b046355',
34 silly install resolved     bugs: { url: 'https://github.com/hoodiehq/hoodie-cli/issues' },
34 silly install resolved     homepage: 'https://github.com/hoodiehq/hoodie-cli',
34 silly install resolved     _id: 'hoodie-cli@0.6.3',
34 silly install resolved     _shasum: 'd8d5bdafe5e10ecc02aaace276d40f3e79acd5bd',
34 silly install resolved     _from: 'hoodie-cli@*',
34 silly install resolved     _npmVersion: '1.4.28',
34 silly install resolved     _npmUser: { name: 'hoodiebot', email: 'stephan@thehoodiefirm.com' },
34 silly install resolved     maintainers: [ [Object], [Object], [Object], [Object], [Object], [Object] ],
34 silly install resolved     dist:
34 silly install resolved      { shasum: 'd8d5bdafe5e10ecc02aaace276d40f3e79acd5bd',
34 silly install resolved        tarball: 'http://registry.npmjs.org/hoodie-cli/-/hoodie-cli-0.6.3.tgz' },
34 silly install resolved     directories: {},
34 silly install resolved     _resolved: 'https://registry.npmjs.org/hoodie-cli/-/hoodie-cli-0.6.3.tgz',
34 silly install resolved     readme: 'ERROR: No README data found!' } ]
35 info install hoodie-cli@0.6.3 into /usr/local/lib
36 info installOne hoodie-cli@0.6.3
37 verbose installOne of hoodie-cli to /usr/local/lib not in flight; installing
38 warn locking Error: EACCES, open '/Users/rich/.npm/_locks/hoodie-cli-f52482f833c71877.lock'
38 warn locking     at Error (native)
38 warn locking  /Users/rich/.npm/_locks/hoodie-cli-f52482f833c71877.lock failed { [Error: EACCES, open '/Users/rich/.npm/_locks/hoodie-cli-f52482f833c71877.lock']
38 warn locking   errno: -13,
38 warn locking   code: 'EACCES',
38 warn locking   path: '/Users/rich/.npm/_locks/hoodie-cli-f52482f833c71877.lock' }
39 verbose stack Error: Attempt to unlock /usr/local/lib/node_modules/hoodie-cli, which hasn't been locked
39 verbose stack     at unlock (/usr/local/lib/node_modules/npm/lib/utils/locker.js:66:11)
39 verbose stack     at cb (/usr/local/lib/node_modules/npm/lib/install.js:1015:5)
39 verbose stack     at /usr/local/lib/node_modules/npm/lib/install.js:1019:20
39 verbose stack     at /usr/local/lib/node_modules/npm/lib/utils/locker.js:40:9
39 verbose stack     at cb (/usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:149:38)
39 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:177:38
39 verbose stack     at FSReqWrap.oncomplete (fs.js:95:15)
40 verbose cwd /Users/rich/hoodie/test_app
41 error Darwin 15.0.0
42 error argv "node" "/usr/local/bin/npm" "install" "-g" "hoodie-cli"
43 error node v0.12.3
44 error npm  v2.9.1
45 error Attempt to unlock /usr/local/lib/node_modules/hoodie-cli, which hasn't been locked
46 error If you need help, you may report this error at:
46 error     <https://github.com/npm/npm/issues>
47 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
@Web-Dev-Rich Have you tried prefixing the command with `sudo`, since your global modules are being installed to `/usr/local/` which you seem to not have permission to modify.

**Comment by Web-Dev-Rich** [comment]
@KenanY That did work thank you so much. I have had to do that on other installs so not sure why my brain blanked it today!
