### ISSUE TITLE
cannot npm install on my mac OS 10.9

### ISSUE THREAD

**Issue by BabbagesCabbages** [npm/npm#10499]
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/opt/nvm/v0.10.23/bin/node',
1 verbose cli   '/usr/local/opt/nvm/v0.10.23/bin/npm',
1 verbose cli   'install' ]
2 info using npm@1.3.17
3 info using node@v0.10.23
4 verbose node symlink /usr/local/opt/nvm/v0.10.23/bin/node
5 verbose readDependencies using package.json deps
6 verbose install where, deps [ '/Users/krm/Sites/reactdev/snapkite-engine',
6 verbose install   [ 'mongoose', 'node-tweet-stream', 'socket.io' ] ]
7 info preinstall snapkite-engine@0.1.2
8 verbose readDependencies using package.json deps
9 verbose cache add [ 'mongoose@^3.8.22', null ]
10 verbose cache add name=undefined spec="mongoose@^3.8.22" args=["mongoose@^3.8.22",null]
11 verbose parsed url { protocol: null,
11 verbose parsed url   slashes: null,
11 verbose parsed url   auth: null,
11 verbose parsed url   host: null,
11 verbose parsed url   port: null,
11 verbose parsed url   hostname: null,
11 verbose parsed url   hash: null,
11 verbose parsed url   search: null,
11 verbose parsed url   query: null,
11 verbose parsed url   pathname: 'mongoose@^3.8.22',
11 verbose parsed url   path: 'mongoose@^3.8.22',
11 verbose parsed url   href: 'mongoose@^3.8.22' }
12 verbose cache add name="mongoose" spec="^3.8.22" args=["mongoose","^3.8.22"]
13 verbose parsed url { protocol: null,
13 verbose parsed url   slashes: null,
13 verbose parsed url   auth: null,
13 verbose parsed url   host: null,
13 verbose parsed url   port: null,
13 verbose parsed url   hostname: null,
13 verbose parsed url   hash: null,
13 verbose parsed url   search: null,
13 verbose parsed url   query: null,
13 verbose parsed url   pathname: '^3.8.22',
13 verbose parsed url   path: '^3.8.22',
13 verbose parsed url   href: '^3.8.22' }
14 verbose addNamed [ 'mongoose', '^3.8.22' ]
15 verbose addNamed [ null, '>=3.8.22-0 <4.0.0-0' ]
16 verbose cache add [ 'node-tweet-stream@^1.6.0', null ]
17 verbose cache add name=undefined spec="node-tweet-stream@^1.6.0" args=["node-tweet-stream@^1.6.0",null]
18 verbose parsed url { protocol: null,
18 verbose parsed url   slashes: null,
18 verbose parsed url   auth: null,
18 verbose parsed url   host: null,
18 verbose parsed url   port: null,
18 verbose parsed url   hostname: null,
18 verbose parsed url   hash: null,
18 verbose parsed url   search: null,
18 verbose parsed url   query: null,
18 verbose parsed url   pathname: 'node-tweet-stream@^1.6.0',
18 verbose parsed url   path: 'node-tweet-stream@^1.6.0',
18 verbose parsed url   href: 'node-tweet-stream@^1.6.0' }
19 verbose cache add name="node-tweet-stream" spec="^1.6.0" args=["node-tweet-stream","^1.6.0"]
20 verbose parsed url { protocol: null,
20 verbose parsed url   slashes: null,
20 verbose parsed url   auth: null,
20 verbose parsed url   host: null,
20 verbose parsed url   port: null,
20 verbose parsed url   hostname: null,
20 verbose parsed url   hash: null,
20 verbose parsed url   search: null,
20 verbose parsed url   query: null,
20 verbose parsed url   pathname: '^1.6.0',
20 verbose parsed url   path: '^1.6.0',
20 verbose parsed url   href: '^1.6.0' }
21 verbose addNamed [ 'node-tweet-stream', '^1.6.0' ]
22 verbose addNamed [ null, '>=1.6.0-0 <2.0.0-0' ]
23 silly lockFile aed126bd-mongoose-3-8-22 mongoose@^3.8.22
24 verbose lock mongoose@^3.8.22 /Users/krm/.npm/aed126bd-mongoose-3-8-22.lock
25 verbose cache add [ 'socket.io@^1.3.2', null ]
26 verbose cache add name=undefined spec="socket.io@^1.3.2" args=["socket.io@^1.3.2",null]
27 verbose parsed url { protocol: null,
27 verbose parsed url   slashes: null,
27 verbose parsed url   auth: null,
27 verbose parsed url   host: null,
27 verbose parsed url   port: null,
27 verbose parsed url   hostname: null,
27 verbose parsed url   hash: null,
27 verbose parsed url   search: null,
27 verbose parsed url   query: null,
27 verbose parsed url   pathname: 'socket.io@^1.3.2',
27 verbose parsed url   path: 'socket.io@^1.3.2',
27 verbose parsed url   href: 'socket.io@^1.3.2' }
28 verbose cache add name="socket.io" spec="^1.3.2" args=["socket.io","^1.3.2"]
29 verbose parsed url { protocol: null,
29 verbose parsed url   slashes: null,
29 verbose parsed url   auth: null,
29 verbose parsed url   host: null,
29 verbose parsed url   port: null,
29 verbose parsed url   hostname: null,
29 verbose parsed url   hash: null,
29 verbose parsed url   search: null,
29 verbose parsed url   query: null,
29 verbose parsed url   pathname: '^1.3.2',
29 verbose parsed url   path: '^1.3.2',
29 verbose parsed url   href: '^1.3.2' }
30 verbose addNamed [ 'socket.io', '^1.3.2' ]
31 verbose addNamed [ null, '>=1.3.2-0 <2.0.0-0' ]
32 silly lockFile f3be1dbd-socket-io-1-3-2 socket.io@^1.3.2
33 verbose lock socket.io@^1.3.2 /Users/krm/.npm/f3be1dbd-socket-io-1-3-2.lock
34 silly lockFile ea494e73-node-tweet-stream-1-6-0 node-tweet-stream@^1.6.0
35 verbose lock node-tweet-stream@^1.6.0 /Users/krm/.npm/ea494e73-node-tweet-stream-1-6-0.lock
36 silly addNameRange { name: 'mongoose',
36 silly addNameRange   range: '>=3.8.22-0 <4.0.0-0',
36 silly addNameRange   hasData: false }
37 silly addNameRange { name: 'socket.io',
37 silly addNameRange   range: '>=1.3.2-0 <2.0.0-0',
37 silly addNameRange   hasData: false }
38 verbose url raw mongoose
39 verbose url resolving [ 'https://registry.npmjs.org/', './mongoose' ]
40 verbose url resolved https://registry.npmjs.org/mongoose
41 silly lockFile aed126bd-mongoose-3-8-22 mongoose@^3.8.22
42 silly lockFile aed126bd-mongoose-3-8-22 mongoose@^3.8.22
43 verbose url raw socket.io
44 verbose url resolving [ 'https://registry.npmjs.org/', './socket.io' ]
45 verbose url resolved https://registry.npmjs.org/socket.io
46 silly lockFile f3be1dbd-socket-io-1-3-2 socket.io@^1.3.2
47 silly lockFile f3be1dbd-socket-io-1-3-2 socket.io@^1.3.2
48 silly addNameRange { name: 'node-tweet-stream',
48 silly addNameRange   range: '>=1.6.0-0 <2.0.0-0',
48 silly addNameRange   hasData: false }
49 error Error: Cannot insert data into the registry without auth
49 error     at RegClient.regRequest [as request] (/usr/local/Cellar/nvm/0.2.0/v0.10.23/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:96:15)
49 error     at RegClient.get_ (/usr/local/Cellar/nvm/0.2.0/v0.10.23/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:116:8)
49 error     at RegClient.<anonymous> (/usr/local/Cellar/nvm/0.2.0/v0.10.23/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:43:15)
49 error     at Object.oncomplete (fs.js:107:15)
50 error If you need help, you may report this *entire* log,
50 error including the npm and node versions, at:
50 error     <http://github.com/isaacs/npm/issues>
51 error System Darwin 13.3.0
52 error command "/usr/local/opt/nvm/v0.10.23/bin/node" "/usr/local/opt/nvm/v0.10.23/bin/npm" "install"
53 error cwd /Users/krm/Sites/reactdev/snapkite-engine
54 error node -v v0.10.23
55 error npm -v 1.3.17
56 verbose exit [ 1, true ]
```

**Comment by OmgImAlexis** [comment]
You may want to update your node and npm, that's most likely the issue.
```
2 info using npm@1.3.17
3 info using node@v0.10.23
````

Node is at v5 and npm is at v3.
