### ISSUE TITLE
missing ) after argument list

### ISSUE THREAD

**Issue by 15697289437** [npm/npm#10508]
sudo npm install gulp
SyntaxError: missing ) after argument list
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/ctype/ctype.js:39:16)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "gulp"
npm ERR! node v4.2.2
npm ERR! npm  v3.3.12

npm ERR! missing ) after argument list
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by OmgImAlexis** [comment]
1. Please wrap your log output like [this](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks).
2. You shouldn't be using `sudo` at all.
3. Are there any other logs with this?

**Comment by KenanY** [comment]
@15697289437 Are you still seeing this issue?

**Comment by KenanY** [comment]
Closing as abandoned.
