### ISSUE TITLE
npm shinkwrap error

### ISSUE THREAD

**Issue by SkyzohKey** [npm/npm#10524]
Hey guys, i wanted to use the shinkwrap function and got this error message:
```bash
npm ERR! Error: Problems were encountered
npm ERR! Please correct and try again.
npm ERR! extraneous: orm@2.1.27 /home/skyzohkey/Dev/NodeJS/tox-links/node_modules/orm
npm ERR!     at shrinkwrap_ (/usr/lib/node_modules/npm/lib/shrinkwrap.js:29:15)
npm ERR!     at /usr/lib/node_modules/npm/lib/shrinkwrap.js:23:5
npm ERR!     at /usr/lib/node_modules/npm/lib/ls.js:43:30
npm ERR!     at /usr/lib/node_modules/read-installed/read-installed.js:119:5
npm ERR!     at /usr/lib/node_modules/read-installed/read-installed.js:233:14
npm ERR!     at cb (/usr/lib/node_modules/slide/lib/async-map.js:48:11)
npm ERR!     at /usr/lib/node_modules/read-installed/read-installed.js:233:14
npm ERR!     at cb (/usr/lib/node_modules/slide/lib/async-map.js:48:11)
npm ERR!     at /usr/lib/node_modules/read-installed/read-installed.js:233:14
npm ERR!     at cb (/usr/lib/node_modules/slide/lib/async-map.js:48:11)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 4.2.3-300.fc23.x86_64
npm ERR! command "node" "/bin/npm" "shrinkwrap"
npm ERR! cwd /home/skyzohkey/Dev/NodeJS/tox-links
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.3.6
```

**Comment by SkyzohKey** [comment]
fixed by uninstalling orm then `--save` it. Sorry for this useless issue.
