### ISSUE TITLE
"npm dist-tag add <pkg>@<version> <tag>" error 500

### ISSUE THREAD

**Issue by matheussampaio** [npm/npm#10548]
I'm trying to add a dist-tag to my package but it's failing.

When I execute:
```
$ npm dist-tag add urionlinejudge-cli@2.4.0 next
```

I get:
```
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "dist-tag" "add" "urionlinejudge-cli@2.4.0" "next"
npm ERR! node v5.1.0
npm ERR! npm  v3.3.12
npm ERR! code E500

npm ERR! Registry returned 500 for PUT on https://registry.npmjs.org/-/package/urionlinejudge-cli/dist-tags/next
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/matheussampaio/git/urionlinejudge-cli/npm-debug.log
```

**npm-debug.log**:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'dist-tag',
1 verbose cli   'add',
1 verbose cli   'urionlinejudge-cli@2.4.0',
1 verbose cli   'next' ]
2 info using npm@3.3.12
3 info using node@v5.1.0
4 verbose dist-tag add next to urionlinejudge-cli@2.4.0
5 silly mapToRegistry name urionlinejudge-cli
6 silly mapToRegistry using default registry
7 silly mapToRegistry registry https://registry.npmjs.org/
8 silly mapToRegistry uri https://registry.npmjs.org/urionlinejudge-cli
9 verbose request uri https://registry.npmjs.org/-/package/urionlinejudge-cli/dist-tags
10 verbose request no auth needed
11 info attempt registry request try #1 at 4:38:07 AM
12 verbose request using bearer token for auth
13 verbose request id 2fd032e269e5617a
14 http request GET https://registry.npmjs.org/-/package/urionlinejudge-cli/dist-tags
15 http 200 https://registry.npmjs.org/-/package/urionlinejudge-cli/dist-tags
16 verbose headers { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
16 verbose headers   etag: '"B27OM58XH5Z654ULAVA3YW3JZ"',
16 verbose headers   'content-type': 'application/json',
16 verbose headers   'cache-control': 'max-age=60',
16 verbose headers   'content-length': '18',
16 verbose headers   'accept-ranges': 'bytes',
16 verbose headers   date: 'Wed, 25 Nov 2015 10:38:08 GMT',
16 verbose headers   via: '1.1 varnish',
16 verbose headers   connection: 'keep-alive',
16 verbose headers   'x-served-by': 'cache-dfw1833-DFW',
16 verbose headers   'x-cache': 'MISS',
16 verbose headers   'x-cache-hits': '0',
16 verbose headers   'x-timer': 'S1448447887.955724,VS0,VE289',
16 verbose headers   vary: 'Accept' }
17 silly mapToRegistry name urionlinejudge-cli
18 silly mapToRegistry using default registry
19 silly mapToRegistry registry https://registry.npmjs.org/
20 silly mapToRegistry uri https://registry.npmjs.org/urionlinejudge-cli
21 verbose request uri https://registry.npmjs.org/-/package/urionlinejudge-cli/dist-tags/next
22 verbose request sending authorization for write operation
23 info attempt registry request try #1 at 4:38:08 AM
24 verbose request using bearer token for auth
25 http request PUT https://registry.npmjs.org/-/package/urionlinejudge-cli/dist-tags/next
26 http 500 https://registry.npmjs.org/-/package/urionlinejudge-cli/dist-tags/next
27 verbose headers { 'content-type': 'application/json',
27 verbose headers   'cache-control': 'max-age=0',
27 verbose headers   'content-length': '50',
27 verbose headers   'accept-ranges': 'bytes',
27 verbose headers   date: 'Wed, 25 Nov 2015 10:38:09 GMT',
27 verbose headers   via: '1.1 varnish',
27 verbose headers   connection: 'keep-alive',
27 verbose headers   'x-served-by': 'cache-dfw1833-DFW',
27 verbose headers   'x-cache': 'MISS',
27 verbose headers   'x-cache-hits': '0',
27 verbose headers   'x-timer': 'S1448447888.964789,VS0,VE531' }
28 info retry will retry, error on last attempt: Error: Registry returned 500 for PUT on https://registry.npmjs.org/-/package/urionlinejudge-cli/dist-tags/next
29 info attempt registry request try #2 at 4:38:19 AM
30 verbose request using bearer token for auth
31 http request PUT https://registry.npmjs.org/-/package/urionlinejudge-cli/dist-tags/next
32 http 500 https://registry.npmjs.org/-/package/urionlinejudge-cli/dist-tags/next
33 verbose headers { 'content-type': 'application/json',
33 verbose headers   'cache-control': 'max-age=0',
33 verbose headers   'content-length': '50',
33 verbose headers   'accept-ranges': 'bytes',
33 verbose headers   date: 'Wed, 25 Nov 2015 10:38:20 GMT',
33 verbose headers   via: '1.1 varnish',
33 verbose headers   connection: 'keep-alive',
33 verbose headers   'x-served-by': 'cache-ord1724-ORD',
33 verbose headers   'x-cache': 'MISS',
33 verbose headers   'x-cache-hits': '0',
33 verbose headers   'x-timer': 'S1448447900.047508,VS0,VE506' }
34 info retry will retry, error on last attempt: Error: Registry returned 500 for PUT on https://registry.npmjs.org/-/package/urionlinejudge-cli/dist-tags/next
35 info attempt registry request try #3 at 4:39:20 AM
36 verbose request using bearer token for auth
37 http request PUT https://registry.npmjs.org/-/package/urionlinejudge-cli/dist-tags/next
38 http 500 https://registry.npmjs.org/-/package/urionlinejudge-cli/dist-tags/next
39 verbose headers { 'content-type': 'application/json',
39 verbose headers   'cache-control': 'max-age=0',
39 verbose headers   'content-length': '50',
39 verbose headers   'accept-ranges': 'bytes',
39 verbose headers   date: 'Wed, 25 Nov 2015 10:39:21 GMT',
39 verbose headers   via: '1.1 varnish',
39 verbose headers   connection: 'keep-alive',
39 verbose headers   'x-served-by': 'cache-ord1728-ORD',
39 verbose headers   'x-cache': 'MISS',
39 verbose headers   'x-cache-hits': '0',
39 verbose headers   'x-timer': 'S1448447961.156224,VS0,VE510' }
40 verbose request invalidating /Users/matheussampaio/.npm/registry.npmjs.org/-/package/urionlinejudge-cli/dist-tags/next on PUT
41 verbose stack Error: Registry returned 500 for PUT on https://registry.npmjs.org/-/package/urionlinejudge-cli/dist-tags/next
41 verbose stack     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
41 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:242:14)
41 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
41 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:198:22)
41 verbose stack     at emitTwo (events.js:87:13)
41 verbose stack     at Request.emit (events.js:172:7)
41 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1082:10)
41 verbose stack     at emitOne (events.js:82:20)
41 verbose stack     at Request.emit (events.js:169:7)
41 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1009:12)
42 verbose statusCode 500
43 verbose cwd /Users/matheussampaio/git/urionlinejudge-cli
44 error Darwin 14.5.0
45 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "dist-tag" "add" "urionlinejudge-cli@2.4.0" "next"
46 error node v5.1.0
47 error npm  v3.3.12
48 error code E500
49 error Registry returned 500 for PUT on https://registry.npmjs.org/-/package/urionlinejudge-cli/dist-tags/next
50 error If you need help, you may report this error at:
50 error     <https://github.com/npm/npm/issues>
51 verbose exit [ 1, true ]
```

**Comment by stevengill** [comment]
Getting the same error using node 5 and npm 3.3.12

**Comment by stevengill** [comment]
Same error with node v4.2.2 and npm 2.14.7. 

Also tried updating npm to 3.4.1 and got the same error.

**Comment by othiym23** [comment]
I have @npm/registry-team taking a look at this right now, and I think it's more likely this is a registry problem than a CLI problem.

**Comment by stevengill** [comment]
Thanks @othiym23! Yeah, I would think it is registry problem too.

**Comment by othiym23** [comment]
We had a minor operational snafu on the registry that caused this route (and a few others) to be unavailable for a day or so. We've now rolled back the offending change and I've confirmed that `npm dist-tag add` and `npm dist-tag rm` are working as expected. It's a US Thanksgiving miracle!

**Comment by matheussampaio** [comment]
It's working now. Thanks everybody.
