### ISSUE TITLE
old node.js don't want to start

### ISSUE THREAD

**Issue by rmonline** [npm/npm#10551]
I'm new to node and have some problem with it.
We have get some app what was write couple years ago. and now i have to adjust it to our needs. I don't have problems with js, css or html. problem I got to start this app. I try under windows, try under linux (on virtualbox ubuntu and centos). But still have problems. On windows get npm-debug

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.14.7
3 info using node@v4.2.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart rm-online@0.0.1
6 info start rm-online@0.0.1
7 verbose unsafe-perm in lifecycle true
8 info rm-online@0.0.1 Failed to exec start script
9 verbose stack Error: rm-online@0.0.1 start: `node ./bin/www`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:818:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid rm-online@0.0.1
11 verbose cwd C:\Users\Marcin\Documents\rm-online
12 error Windows_NT 10.0.10240
13 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
14 error node v4.2.0
15 error npm  v2.14.7
16 error code ELIFECYCLE
17 error rm-online@0.0.1 start: `node ./bin/www`
17 error Exit status 1
18 error Failed at the rm-online@0.0.1 start script 'node ./bin/www'.
18 error This is most likely a problem with the rm-online package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node ./bin/www
18 error You can get their info via:
18 error     npm owner ls rm-online
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

What can be a problem with?

**Comment by OmgImAlexis** [comment]
Please wrap your log output like [this](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks).

**Comment by vivekwisdom** [comment]
I think the same error I'm getting on Amazon beanstalk.

Please look at this log file..

```
1 verbose cli [ '/opt/elasticbeanstalk/node-install/node-v4.2.3-linux-x64/bin/node',
1 verbose cli   '/opt/elasticbeanstalk/node-install/node-v4.2.3-linux-x64/bin/npm',
1 verbose cli   'start' ]
2 info using npm@2.14.7
3 info using node@v4.2.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart aiapp@0.0.0
6 info start aiapp@0.0.0
7 verbose unsafe-perm in lifecycle true
8 info aiapp@0.0.0 Failed to exec start script
9 verbose stack Error: aiapp@0.0.0 start: `node server`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/opt/elasticbeanstalk/node-install/node-v4.2.3-linux-x64/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/opt/elasticbeanstalk/node-install/node-v4.2.3-linux-x64/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:818:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid aiapp@0.0.0
11 verbose cwd /var/app/current
12 error Linux 4.1.13-19.30.amzn1.x86_64
13 error argv "/opt/elasticbeanstalk/node-install/node-v4.2.3-linux-x64/bin/node" "/opt/elasticbeanstalk/node-install/node-v4.2.3-linux-x64/bin/npm" "start"
14 error node v4.2.3
15 error npm  v2.14.7
16 error code ELIFECYCLE
17 error aiapp@0.0.0 start: `node server`
17 error Exit status 1
18 error Failed at the aiapp@0.0.0 start script 'node server'.
18 error This is most likely a problem with the aiapp package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node server
18 error You can get their info via:
18 error     npm owner ls aiapp
18 error There is likely additional logging output above.

```

**Comment by KenanY** [comment]
@rmonline I have edited your post in order to properly wrap the log in a code block. Are you still experiencing this issue?

**Comment by KenanY** [comment]
Closing as abandoned.
