### ISSUE TITLE
ERR: You cannot publish over the previously published version 1.1.3.

### ISSUE THREAD

**Issue by whoisandie** [npm/npm#10556]
Tried unpublishing the package and publishing it back again, pops this error on the screen.
Is there a way to publish with the same identifier 1.1.3 which was already published before?
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/var/nvm/versions/io.js/v3.3.1/bin/iojs',
1 verbose cli   '/usr/local/var/nvm/versions/io.js/v3.3.1/bin/npm',
1 verbose cli   'publish' ]
2 info using npm@2.14.3
3 info using node@v3.3.1
4 verbose publish [ '.' ]
5 silly cache add args [ '.', null ]
6 verbose cache add spec .
7 silly cache add parsed spec Result {
7 silly cache add   raw: '.',
7 silly cache add   scope: null,
7 silly cache add   name: null,
7 silly cache add   rawSpec: '.',
7 silly cache add   spec: '/Users/Asher/Github/react-blocks',
7 silly cache add   type: 'directory' }
8 verbose addLocalDirectory /Users/Asher/.npm/react-blocks/1.1.3/package.tgz not in flight; packing
9 verbose tar pack [ '/Users/Asher/.npm/react-blocks/1.1.3/package.tgz',
9 verbose tar pack   '/Users/Asher/Github/react-blocks' ]
10 verbose tarball /Users/Asher/.npm/react-blocks/1.1.3/package.tgz
11 verbose folder /Users/Asher/Github/react-blocks
12 info prepublish react-blocks@1.1.3
13 verbose addLocalTarball adding from inside cache /Users/Asher/.npm/react-blocks/1.1.3/package.tgz
14 silly cache afterAdd react-blocks@1.1.3
15 verbose afterAdd /Users/Asher/.npm/react-blocks/1.1.3/package/package.json not in flight; writing
16 verbose afterAdd /Users/Asher/.npm/react-blocks/1.1.3/package/package.json written
17 silly publish { name: 'react-blocks',
17 silly publish   version: '1.1.3',
17 silly publish   description: 'A higher-level react component to manage complex layouts using flexbox.',
17 silly publish   main: 'lib/index',
17 silly publish   scripts:
17 silly publish    { start: 'node server.js',
17 silly publish      build: 'scripts/build.sh',
17 silly publish      deploy: 'scripts/deploy.sh',
17 silly publish      lint: 'eslint src',
17 silly publish      test: 'npm run lint && karma start' },
17 silly publish   repository:
17 silly publish    { type: 'git',
17 silly publish      url: 'git+https://github.com/whoisandie/react-blocks.git' },
17 silly publish   author: { name: 'whoisandie' },
17 silly publish   license: 'MIT',
17 silly publish   bugs: { url: 'https://github.com/whoisandie/react-blocks/issues' },
17 silly publish   homepage: 'https://github.com/whoisandie/react-blocks#readme',
17 silly publish   dependencies: { 'object-assign': '^4.0.1', react: '^0.14.3' },
17 silly publish   devDependencies:
17 silly publish    { babel: '^5.8.23',
17 silly publish      'babel-core': '^5.8.24',
17 silly publish      'babel-eslint': '^4.1.2',
17 silly publish      'babel-loader': '^5.3.2',
17 silly publish      chai: '^3.3.0',
17 silly publish      'css-loader': '^0.19.0',
17 silly publish      'es5-shim': '^4.1.13',
17 silly publish      eslint: '^1.4.3',
17 silly publish      'eslint-loader': '^1.0.0',
17 silly publish      'eslint-plugin-react': '^3.3.2',
17 silly publish      'gh-pages': '^0.4.0',
17 silly publish      'html-webpack-plugin': '^1.6.1',
17 silly publish      karma: '^0.13.10',
17 silly publish      'karma-chai': '^0.1.0',
17 silly publish      'karma-chai-plugins': '^0.6.0',
17 silly publish      'karma-mocha': '^0.2.0',
17 silly publish      'karma-mocha-reporter': '^1.1.1',
17 silly publish      'karma-phantomjs-launcher': '^0.2.1',
17 silly publish      'karma-webpack': '^1.7.0',
17 silly publish      less: '^2.5.1',
17 silly publish      'less-loader': '^2.2.1',
17 silly publish      mocha: '^2.3.3',
17 silly publish      phantomjs: '^1.9.18',
17 silly publish      'react-dom': '^0.14.3',
17 silly publish      'react-hot-loader': '^1.3.0',
17 silly publish      'style-loader': '^0.12.3',
17 silly publish      webpack: '^1.12.1',
17 silly publish      'webpack-dev-server': '^1.11.0',
17 silly publish      'webpack-merge': '^0.2.0' },
17 silly publish   readme: '# React Blocks [![NPM Package][npm_img]][npm_site] [![Travis Status][trav_img]][trav_site]\n\nA higher-level react component to manage complex layouts using flexbox. Everything is just another block. Heavily inspired by [Polymer layout.html][polymer], [LayoutJS][layoutjs] and the [CSSinJS][cssinjs] pattern.\n\n> Just pure layout, No more, No less.\n\n## About\nReact blocks uses a *declarative* approach to build complex layouts on top of [CSS Flexbox][flexbox]. Flexbox properties are exposed as attributes on a higher-level react component. Supports media-queries via predefined *mobile-first* queries. Further custom media queries can be specified in a styles object. Please refer the `styles.js` file inside `demo` directory.\n\nPlease note, it does **NOT** handle missing browser features. Please use [Modernizr][modernizr] with Polyfills to achieve that.\n\n## Usage\n\n### NPM and Webpack/Browserify\nInstall via `npm`. Use `--save` to include it in your *package.json*.\n\n```bash\nnpm install react-blocks\n```\n\nStart by importing/requiring react-blocks within your react code.\n\n```js\n// using an ES6 transpiler\nimport Block from \'react-blocks\';\n\n// not using an ES6 transpiler\nvar Block = require(\'react-blocks\');\n```\n\nThere\'s also a umd version available at `lib/umd`. The component is available on `window.ReactBlocks`.\n\n### Layout (Horizontal, Vertical, Reverse, Wrap)\nA block is just a block level div element by default. You can make it a flex container by adding a `layout` attribute. Further to specify a direction, add `horizontal` or `vertical` attributes for row or column respectively. However the default direction would be set to vertical if nothing is specified. The horizontal attribute is optional though, a block container has its flexDirection set to `horizontal` by default. The direction of a block layout can be reversed by adding a `reverse` attribute. Also to make a flex-item stretch its width use the `flex` attribute on a flex-item. Also all flex-items of a block container are wrapped by default.\n\n```js\n// Normal Flex layout\nconst App = () => {\n  return (\n    <Block layout>\n      <div>Alpha</div>\n      <div>Beta</div>\n    </Block>\n  );\n};\n\n// Reverse Flex layout\nconst Reverse = () => {\n  let { reverse } = styles;\n  return (\n    <Block style={reverse.block} layout vertical reverse>\n      <div>Alpha</div>\n      <div flex>Beta</div>\n    </Block>\n  );\n};\n```\n\n### Align, Self-Align & Justify\n\nBy default flex-items *stretch* to fit the cross-axis and are *start* justified. The `align` and `justify*` attributes are used to align and justify flex-items. Please note *align* & *justify* attributes have to be declared on a parent container and has to be a `Block` element.\n\n```js\n// Aligned and Justified  blocks\nconst AlignedJustified = () => {\n  let { vertical } = styles;\n  return (\n    <Block style={vertical.block} layout center justifyEnd>\n      <Block>Alpha</Block>\n      <Block>Beta</Block>\n    </Block>\n  );\n};\n```\n\nFurther flex-items can be self aligned across the cross-axis using the self attribute on the flex-item itself.\n\n```js\n// Self aligned with Aligned and Justified blocks\nconst SelfAlignedJustified = () => {\n  let { vertical } = styles;\n  return (\n    <Block style={vertical.block} layout center justifyEnd>\n      <Block selfStart>Alpha</Block>\n      <Block selfEnd>Beta</Block>\n    </Block>\n  );\n};\n```\n\nTo center align and center justify an item within a flex-container, use the `centered` attribute.\n\n```js\nconst Centered = () => {\n  let { centered } = styles;\n  return (\n    <Block style={centered.block} layout centered>\n      <div>Centered</div>\n    </Block>\n  );\n};\n```\n\n### Nested Blocks\nBlocks can further be nested. A block could contain multiple blocks as well. Use the `layout` attribute on a flex item to make a it a flex-container. However its not necessary that all children inside a flex-container are wrapped inside a *Block*.\n\n```js\nconst Nested = () => {\n  return (\n    <Block layout>\n      <Block className="sidebar" layout vertical>\n        <Block>Alpha</Block>\n        <Block>Beta</Block>\n      </Block>\n      <Block className="content" layout reverse>\n        <Block selfEnd>Gamma</Block>\n        <div>Delta</div>\n        <div>Theta</div>\n      </Block>\n    </Block>\n  )\n};\n```\n\n### General purpose attributes\nBlocks come with purpose attributes for basic positioning.\n\nAttribute   |  Result\n---------   |  ------\n`block`     |  Assigns `display: block`\n`hidden`    |  Assigns `display: none`\n`invisible` |  Assigns `visibility: hidden`\n`relative`  |  Assigns `position: relative`\n`absolute`  |  Assigns `position: absolute` and sets `top:0;right:0;bottom:0;left:0`. *Note:* When using `absolute` attribute, there must be a container having `position: relative` layout.\n\n## Todo\n- Add vendor prefixes\n- Ability to define custom media-queries\n\n## Issues\nFeel free to contribute. Submit a Pull Request or open an issue for further discussion.\n\n## License\nMIT &copy; [whoisandie][whoisandie]\n\n[polymer]: https://www.polymer-project.org/0.5/docs/polymer/layout-attrs.html\n[layoutjs]: https://github.com/basarat/layoutjs\n[cssinjs]: https://speakerdeck.com/vjeux/react-css-in-js\n[flexbox]: https://developer.mozilla.org/en-US/docs/Web/Guide/CSS/Flexible_boxes\n[modernizr]: http://modernizr.com\n[whoisandie]: http://whoisandie.com\n\n[trav_img]: https://api.travis-ci.org/whoisandie/react-blocks.svg\n[trav_site]: https://travis-ci.org/whoisandie/react-blocks\n[npm_img]: https://img.shields.io/npm/v/react-blocks.svg\n[npm_site]: https://www.npmjs.org/package/react-blocks\n',
17 silly publish   readmeFilename: 'README.md',
17 silly publish   gitHead: 'dd918e7e17543b4013e3d8f78be8f43ea1539cec',
17 silly publish   _id: 'react-blocks@1.1.3',
17 silly publish   _shasum: '4d21f6db192a63407ca8040bc205fd51ea19c8ec',
17 silly publish   _from: '.' }
18 verbose getPublishConfig undefined
19 silly mapToRegistry name react-blocks
20 silly mapToRegistry using default registry
21 silly mapToRegistry registry https://registry.npmjs.org/
22 silly mapToRegistry uri https://registry.npmjs.org/react-blocks
23 verbose publish registryBase https://registry.npmjs.org/
24 silly publish uploading /Users/Asher/.npm/react-blocks/1.1.3/package.tgz
25 verbose request uri https://registry.npmjs.org/react-blocks
26 verbose request sending authorization for write operation
27 info attempt registry request try #1 at 5:47:28 PM
28 verbose request id 12074458a5aaa942
29 http request PUT https://registry.npmjs.org/react-blocks
30 http 403 https://registry.npmjs.org/react-blocks
31 verbose headers { 'content-type': 'application/json',
31 verbose headers   'cache-control': 'max-age=60',
31 verbose headers   'content-length': '95',
31 verbose headers   'accept-ranges': 'bytes',
31 verbose headers   date: 'Thu, 26 Nov 2015 01:47:29 GMT',
31 verbose headers   via: '1.1 varnish',
31 verbose headers   connection: 'keep-alive',
31 verbose headers   'x-served-by': 'cache-lax1430-LAX',
31 verbose headers   'x-cache': 'MISS',
31 verbose headers   'x-cache-hits': '0',
31 verbose headers   'x-timer': 'S1448502449.239503,VS0,VE189' }
32 verbose request invalidating /Users/Asher/.npm/registry.npmjs.org/react-blocks on PUT
33 error publish Failed PUT 403
34 verbose stack Error: "You cannot publish over the previously published version 1.1.3." : react-blocks
34 verbose stack     at makeError (/usr/local/var/nvm/versions/io.js/v3.3.1/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:263:12)
34 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/var/nvm/versions/io.js/v3.3.1/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:251:14)
34 verbose stack     at Request._callback (/usr/local/var/nvm/versions/io.js/v3.3.1/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:171:14)
34 verbose stack     at Request.self.callback (/usr/local/var/nvm/versions/io.js/v3.3.1/lib/node_modules/npm/node_modules/request/request.js:198:22)
34 verbose stack     at emitTwo (events.js:87:13)
34 verbose stack     at Request.emit (events.js:172:7)
34 verbose stack     at Request.<anonymous> (/usr/local/var/nvm/versions/io.js/v3.3.1/lib/node_modules/npm/node_modules/request/request.js:1073:14)
34 verbose stack     at emitOne (events.js:82:20)
34 verbose stack     at Request.emit (events.js:169:7)
34 verbose stack     at IncomingMessage.<anonymous> (/usr/local/var/nvm/versions/io.js/v3.3.1/lib/node_modules/npm/node_modules/request/request.js:1019:12)
35 verbose statusCode 403
36 verbose pkgid react-blocks
37 verbose cwd /Users/Asher/Github/react-blocks
38 error Darwin 15.0.0
39 error argv "/usr/local/var/nvm/versions/io.js/v3.3.1/bin/iojs" "/usr/local/var/nvm/versions/io.js/v3.3.1/bin/npm" "publish"
40 error node v3.3.1
41 error npm  v2.14.3
42 error code E403
43 error "You cannot publish over the previously published version 1.1.3." : react-blocks
44 error If you need help, you may report this error at:
44 error     <https://github.com/npm/npm/issues>
45 verbose exit [ 1, true ]
```

**Comment by ehsalazar** [comment]
@whoisandie Unfortunately, there is no longer any way to re-use a previously unpublished version of a package in the npm registry. The reason for this is that various systems rely on "name@version" being a unique identifier, and start throwing security warnings if the shasum changes.

While this policy may seem inconvenient, it also closes a very significant potential security vulnerability if any part of the registry infrastructure is ever compromised, without asking humans to keep track of opaque shasums themselves.

For this reason, we recommend bumping the "patch" version for even the most trivial updates.

**Comment by whoisandie** [comment]
@ehsalazar Yep. Accidentally ran `npm publish` and cancelled it even before it was published. So thought the changes weren't pushed to the registry. But yes bumping the "patch" version worked. Guess thats the only workaround (y)
