### ISSUE TITLE
Trying to update npm, error Cannot find module 'minimatch'

### ISSUE THREAD

**Issue by mkstix6** [npm/npm#10563]
Yeoman told me I should update npm. So I dutifully did `sudo npm install npm -g` and I think now it's broken.
I tried updating node...no luck there.

`node -v`
v5.1.0

 

`sudo npm install npm -g`
module.js:340
    throw err;
    ^

Error: Cannot find module 'minimatch'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/rimraf/node_modules/glob/glob.js:44:17)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)

I'm not sure how to solve.

**Comment by mkstix6** [comment]
This issue will probably help #10434
