### ISSUE TITLE
Node is not defined

### ISSUE THREAD

**Issue by rodoabad** [npm/npm#10577]
I keep getting this error on this repo.

https://github.com/rikukissa/angular-test-examples

I do have node installed and it's working just fine.

```bash
D:\Web\GitHub\angular-test-examples>npm test

> angular-units@1.0.0 test D:\Web\GitHub\angular-test-examples
> mocha test-helper.js

D:\Web\GitHub\angular-test-examples\node_modules\angular\angular.js:2789
var jqLiteContains = Node.prototype.contains || function(arg) {
                     ^

ReferenceError: Node is not defined
    at D:\Web\GitHub\angular-test-examples\node_modules\angular\angular.js:2789:22
    at Object.<anonymous> (D:\Web\GitHub\angular-test-examples\node_modules\angular\angular.js:29016:3)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (D:\Web\GitHub\angular-test-examples\node_modules\angular\index.js:1:63)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (D:\Web\GitHub\angular-test-examples\test-helper.js:28:1)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at D:\Web\GitHub\angular-test-examples\node_modules\mocha\lib\mocha.js:216:27
    at Array.forEach (native)
    at Mocha.loadFiles (D:\Web\GitHub\angular-test-examples\node_modules\mocha\lib\mocha.js:213:14)
    at Mocha.run (D:\Web\GitHub\angular-test-examples\node_modules\mocha\lib\mocha.js:453:10)
    at Object.<anonymous> (D:\Web\GitHub\angular-test-examples\node_modules\mocha\bin\_mocha:393:18)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:138:18)
    at node.js:974:3
npm ERR! Test failed.  See above for more details.

D:\Web\GitHub\angular-test-examples>

```

**Comment by KenanY** [comment]
@rodoabad From the looks of it this is not an issue with `npm`. Some code (not `npm`'s) is trying to access an undefined `Node` variable (which has nothing to do with having Node.js installed, I believe).

**Comment by rodoabad** [comment]
@KenanY Thanks. I believe `jsdom` just do not have `Node` defined.

Reference: https://github.com/rikukissa/angular-test-examples/issues/1
