### ISSUE TITLE
Why my npm appear ╢██████████████████████ when install package ? 

### ISSUE THREAD

**Issue by jasonleft** [npm/npm#10580]
## log info comes with many chars like " ╢██████████████████████ "

```
▄ ╢░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
▐ ╢░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
▌ ╢░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
▀ ╢░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
▀ ╢░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
▐ ╢░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
▄ ╢░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
▌ ╢░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
▌ ╢░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
loadRequestedDeps → addNa ▀ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
loadRequestedDeps → after ▌ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░
loadDep:utf-8-validate →  ▌ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░
loadDep:utf-8-validate →  ▌ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░
loadDep:utf-8-validate →  ▀ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
loadDep:utf-8-validate →  ▀ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
loadDep:utf-8-validate →  ▀ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
loadDep:utf-8-validate →  ▀ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
loadDep:bufferutil        ▀ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
loadDep:nan → request     ▀ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
loadDep:nan → 304         ▐ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
loadDep:nan → addNamed    ▌ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░
loadDep:nan → afterAdd    ▄ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░
loadDep:nan → get         ▌ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░
loadDep:nan → afterAdd    ▄ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░
loadDep:nan → afterAdd    ▌ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░
diffTrees → generateActio ▌ ╢████████████████████████
extract → unbuild         ▄ ╢████████████████████████
extract → gunzTarPerm     ▄ ╢████████████████████████
extract → gunzTarPerm     ▌ ╢████████████████████████
extract:bindings → gunzTa ▄ ╢████████████████████████
extract:ultron → gunzTarP ▌ ╢████████████████████████
extract:bufferutil → gunz ▌ ╢████████████████████████
extract:ws                ▐ ╢█████████████████████████
extract:ws → gentlyRm     ▄ ╢████████████████████████
finalize:bindings → final ▄ ╢████████████████████████
install                   ▄ ╢████████████████████████

> bufferutil@1.2.1 install E:\web\htdocs\html5\websocket\node_modules\bufferutil

> node-gyp rebuild

install:nan               ▄ ╢████████████████████████

E:\web\htdocs\html5\websocket\node_modules\bufferutil>if not defined npm_config_
node_gyp (node "C:\Users\Object\AppData\Roaming\npm\node_modules\npm\bin\node-gy
p-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebui
ld )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.
gyp ERR! stack     at failNoPython (C:\Users\Object\AppData\Roaming\npm\node_mod
ules\npm\node_modules\node-gyp\lib\configure.js:116:14)
gyp ERR! stack     at C:\Users\Object\AppData\Roaming\npm\node_modules\npm\node_
modules\node-gyp\lib\configure.js:71:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Object\\AppDa
ta\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "
rebuild"
gyp ERR! cwd E:\web\htdocs\html5\websocket\node_modules\bufferutil
gyp ERR! node -v v5.1.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
install:nan               ▄ ╢████████████████████████
npm WARN install:bufferutil@1.2.1 bufferutil@1.2.1 install: `node-gyp rebuild`
npm WARN install:bufferutil@1.2.1 Exit status 1
install:bufferutil        ▐ ╢█████████████████████████

> utf-8-validate@1.2.1 install E:\web\htdocs\html5\websocket\node_modules\utf-8-
validate
> node-gyp rebuild

install:ultron            ▄ ╢████████████████████████

E:\web\htdocs\html5\websocket\node_modules\utf-8-validate>if not defined npm_con
fig_node_gyp (node "C:\Users\Object\AppData\Roaming\npm\node_modules\npm\bin\nod
e-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  r
ebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.
gyp ERR! stack     at failNoPython (C:\Users\Object\AppData\Roaming\npm\node_mod
ules\npm\node_modules\node-gyp\lib\configure.js:116:14)
gyp ERR! stack     at C:\Users\Object\AppData\Roaming\npm\node_modules\npm\node_
modules\node-gyp\lib\configure.js:71:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Object\\AppDa
ta\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "
rebuild"
gyp ERR! cwd E:\web\htdocs\html5\websocket\node_modules\utf-8-validate
gyp ERR! node -v v5.1.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
install:ultron            ▄ ╢████████████████████████
npm WARN install:utf-8-validate@1.2.1 utf-8-validate@1.2.1 install: `node-gyp re
build`
npm WARN install:utf-8-validate@1.2.1 Exit status 1
install:utf-8-validate    ▐ ╢█████████████████████████
executeActions → rollback ▄ ╢████████████████████████
executeActions → rollback ▌ ╢████████████████████████
runTopLevelLifecycles     ▐ ╢█████████████████████████
example-ws@1.0.0 E:\web\htdocs\html5\websocket
└─┬ ws@0.8.0
  ├── options@0.0.6
  └── ultron@1.0.2

runTopLevelLifecycles     ▐ ╢█████████████████████████
npm WARN example-ws@1.0.0 No description
runTopLevelLifecycles     ▄ ╢████████████████████████
npm WARN example-ws@1.0.0 No repository field.
runTopLevelLifecycles     ▌ ╢████████████████████████
```

**Comment by XGHeaven** [comment]
should be a progress bar...

**Comment by jasonleft** [comment]
And how to close this ? @XGHeaven

**Comment by XGHeaven** [comment]
may be not....

**Comment by OmgImAlexis** [comment]
This is usually caused by an encoding issue on Windows, [try this](https://stackoverflow.com/questions/19955385/utf-8-in-windows-7-cmd).

**Comment by toddself** [comment]
This also occurs on my Mac whenever I run an install command in npm 3.5.  Is your `log_level` set to `http`?  This seems to part of hte issue -- verbose log levels do not turn off the progress bar, but rather interfere with it.

**Comment by mradcliffe** [comment]
@toddself, could you clarify what you mean by `log_level`.

* There are 2 occurrences of "log_level" when I search this repository, one being this issue.
* I did not find any reference of "log_level" to read about from the "docs" link in the Readme, but admittedly I did not find a relevant place on that page to look.
* I did not find any reference to log_level in the man page for npm-install.
* I did not find any reference to log_level in the man page for npmrc.

I updated node last night, and this is quite annoying in Terminal.

**Comment by mradcliffe** [comment]
Setting `npm config set loglevel` to `silent` or `info` did not improve the progress bar.
