### ISSUE TITLE
Adding a dist-tag 403 error, can't verify.

### ISSUE THREAD

**Issue by JordanBourne** [npm/npm#10586]
```
jordanbourne:~/workspace $ npm dist-tag add @jordan/chat-example@1.0.5 betaVersion
npm ERR! Linux 4.2.0-c9
npm ERR! argv "/home/ubuntu/.nvm/versions/node/v4.1.1/bin/node" "/home/ubuntu/.nvm/versions/node/v4.1.1/bin/npm" "dist-tag" "add" "@jordan/chat-example@1.0.5" "betaVersion"
npm ERR! node v4.1.1
npm ERR! npm  v3.5.0
npm ERR! code E403

npm ERR! Registry returned 403 for PUT on http://localhost:15443/-/package/@jordan%2fchat-example/dist-tags/betaVersion
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/workspace/npm-debug.log
jordanbourne:~/workspace $ npm dist-tag ls
betaVersion: 1.0.5
latest: 1.0.0

jordanbourne:~/workspace $ how-to-npm verify
Uh oh, looks like you still only have a single dist-tag.
Use `npm help dist-tag` to learn how to add another one.
#########################################
###   YOUR SOLUTION IS NOT CORRECT!   ###
#########################################
```

Can someone tell me why this isn't working? I get a 403 error when trying to add a dist-tag, but the tag still shows up and the task cannot be verified. 

I forgot to save the error log, so I just recreated it here:

```
0 info it worked if it ends with ok
1 verbose cli [ '/home/ubuntu/.nvm/versions/node/v4.1.1/bin/node',
1 verbose cli   '/home/ubuntu/.nvm/versions/node/v4.1.1/bin/npm',
1 verbose cli   'dist-tag',
1 verbose cli   'add',
1 verbose cli   '@jordan/chat-example@1.0.1',
1 verbose cli   'newBeta',
1 verbose cli   'fix' ]
2 info using npm@3.5.0
3 info using node@v4.1.1
4 verbose dist-tag add newBeta to @jordan/chat-example@1.0.1
5 silly mapToRegistry name @jordan/chat-example
6 silly mapToRegistry scope (from package name) @jordan
7 verbose mapToRegistry no registry URL found in name for scope @jordan
8 silly mapToRegistry using default registry
9 silly mapToRegistry registry http://localhost:15443/
10 silly mapToRegistry uri http://localhost:15443/@jordan%2fchat-example
11 verbose request uri http://localhost:15443/-/package/@jordan%2fchat-example/dist-tags
12 verbose request no auth needed
13 info attempt registry request try #1 at 1:19:17 AM
14 verbose request id fd3754979697146e
15 http request GET http://localhost:15443/-/package/@jordan%2fchat-example/dist-tags
16 http 200 http://localhost:15443/-/package/@jordan%2fchat-example/dist-tags
17 verbose headers { date: 'Sat, 28 Nov 2015 01:19:17 GMT',
17 verbose headers   connection: 'keep-alive',
17 verbose headers   'content-length': '40' }
18 silly mapToRegistry name @jordan/chat-example
19 silly mapToRegistry scope (from package name) @jordan
20 verbose mapToRegistry no registry URL found in name for scope @jordan
21 silly mapToRegistry using default registry
22 silly mapToRegistry registry http://localhost:15443/
23 silly mapToRegistry uri http://localhost:15443/@jordan%2fchat-example
24 verbose request uri http://localhost:15443/-/package/@jordan%2fchat-example/dist-tags/newBeta
25 verbose request sending authorization for write operation
26 info attempt registry request try #1 at 1:19:18 AM
27 http request PUT http://localhost:15443/-/package/@jordan%2fchat-example/dist-tags/newBeta
28 http 403 http://localhost:15443/-/package/@jordan%2fchat-example/dist-tags/newBeta
29 verbose headers { 'content-type': 'application/json',
29 verbose headers   date: 'Sat, 28 Nov 2015 01:19:18 GMT',
29 verbose headers   connection: 'keep-alive',
29 verbose headers   'content-length': '2' }
30 verbose request invalidating /home/ubuntu/.npm/localhost_15443/-/package/_40jordan_252fchat-example/dist-tags/newBeta on PUT
31 verbose stack Error: Registry returned 403 for PUT on http://localhost:15443/-/package/@jordan%2fchat-example/dist-tags/newBeta
31 verbose stack     at makeError (/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
31 verbose stack     at CachingRegistryClient.<anonymous> (/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:242:14)
31 verbose stack     at Request._callback (/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
31 verbose stack     at Request.self.callback (/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/npm/node_modules/request/request.js:198:22)
31 verbose stack     at emitTwo (events.js:87:13)
31 verbose stack     at Request.emit (events.js:172:7)
31 verbose stack     at Request.<anonymous> (/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/npm/node_modules/request/request.js:1082:10)
31 verbose stack     at emitOne (events.js:82:20)
31 verbose stack     at Request.emit (events.js:169:7)
31 verbose stack     at IncomingMessage.<anonymous> (/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/npm/node_modules/request/request.js:1009:12)
32 verbose statusCode 403
33 verbose cwd /home/ubuntu/workspace
34 error Linux 4.2.0-c9
35 error argv "/home/ubuntu/.nvm/versions/node/v4.1.1/bin/node" "/home/ubuntu/.nvm/versions/node/v4.1.1/bin/npm" "dist-tag" "add" "@jordan/chat-example@1.0.1" "newBeta" "fix"
36 error node v4.1.1
37 error npm  v3.5.0
38 error code E403
39 error Registry returned 403 for PUT on http://localhost:15443/-/package/@jordan%2fchat-example/dist-tags/newBeta
40 error If you need help, you may report this error at:
40 error     <https://github.com/npm/npm/issues>
41 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
@JordanBourne Is it intentional that your registry is set to `http://localhost:15443/`?

**Comment by JordanBourne** [comment]
@KenanY That's just whatever the default was. I'm doing the challenge on c9.io and just following the directions.

**Comment by KenanY** [comment]
@JordanBourne Are you still having this issue?

**Comment by KenanY** [comment]
Closing as abandoned.
