### ISSUE TITLE
node-v5.1.0  Cannot find module 'minimatch'  issue on mac

### ISSUE THREAD

**Issue by majorye** [npm/npm#10595]
```
laptop$ npm
module.js:340
    throw err;
    ^
Error: Cannot find module 'minimatch'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/rimraf/node_modules/glob/glob.js:44:17)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
```

**Comment by OmgImAlexis** [comment]
Have you tried reinstalling npm?

**Comment by KenanY** [comment]
@majorye Are you still seeing this issue?

**Comment by KenanY** [comment]
Closing as abandoned.
