### ISSUE TITLE
Cannot read property 'localeCompare' of undefined

### ISSUE THREAD

**Issue by seekshiva** [npm/npm#10618]
npm-debug.log
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'install' ]
2 info using npm@3.3.6
3 info using node@v4.2.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly install normalizeTree
8 silly loadCurrentTree Finishing
9 silly loadIdealTree Starting
10 silly install loadIdealTree
11 silly cloneCurrentTree Starting
12 silly install cloneCurrentTreeToIdealTree
13 silly cloneCurrentTree Finishing
14 silly loadShrinkwrap Starting
15 silly install loadShrinkwrap
16 silly loadShrinkwrap Finishing
17 silly loadAllDepsIntoIdealTree Starting
18 silly install loadAllDepsIntoIdealTree
19 silly fetchNamedPackageData history
20 silly mapToRegistry name history
21 silly mapToRegistry using default registry
22 silly mapToRegistry registry https://registry.npmjs.org/
23 silly mapToRegistry uri https://registry.npmjs.org/history
24 verbose request uri https://registry.npmjs.org/history
25 verbose request no auth needed
26 info attempt registry request try #1 at 1:31:43 PM
27 verbose request using bearer token for auth
28 verbose request id aeb04d97b9856489
29 verbose etag "CYFGDN21V6HKXL6P9JEL5WKTI"
30 http request GET https://registry.npmjs.org/history
31 http 304 https://registry.npmjs.org/history
32 verbose headers { 'cache-control': 'max-age=60',
32 verbose headers   'accept-ranges': 'bytes',
32 verbose headers   date: 'Mon, 30 Nov 2015 08:01:44 GMT',
32 verbose headers   via: '1.1 varnish',
32 verbose headers   connection: 'keep-alive',
32 verbose headers   'x-served-by': 'cache-sin6921-SIN',
32 verbose headers   'x-cache': 'MISS',
32 verbose headers   'x-cache-hits': '0',
32 verbose headers   'x-timer': 'S1448870503.947070,VS0,VE201' }
33 silly get cb [ 304,
33 silly get   { 'cache-control': 'max-age=60',
33 silly get     'accept-ranges': 'bytes',
33 silly get     date: 'Mon, 30 Nov 2015 08:01:44 GMT',
33 silly get     via: '1.1 varnish',
33 silly get     connection: 'keep-alive',
33 silly get     'x-served-by': 'cache-sin6921-SIN',
33 silly get     'x-cache': 'MISS',
33 silly get     'x-cache-hits': '0',
33 silly get     'x-timer': 'S1448870503.947070,VS0,VE201' } ]
34 verbose etag https://registry.npmjs.org/history from cache
35 verbose get saving history to /Users/shiva/.npm/registry.npmjs.org/history/.cache.json
36 silly resolveWithNewModule history@1.13.0 checking installable status
37 silly cache add args [ 'history@1.13.0', null ]
38 verbose cache add spec history@1.13.0
39 silly cache add parsed spec Result {
39 silly cache add   raw: 'history@1.13.0',
39 silly cache add   scope: null,
39 silly cache add   name: 'history',
39 silly cache add   rawSpec: '1.13.0',
39 silly cache add   spec: '1.13.0',
39 silly cache add   type: 'version' }
40 silly addNamed history@1.13.0
41 verbose addNamed "1.13.0" is a plain semver version for history
42 silly mapToRegistry name history
43 silly mapToRegistry using default registry
44 silly mapToRegistry registry https://registry.npmjs.org/
45 silly mapToRegistry uri https://registry.npmjs.org/history
46 verbose addNameVersion registry:https://registry.npmjs.org/history not in flight; fetching
47 verbose get https://registry.npmjs.org/history not expired, no request
48 silly cache afterAdd history@1.13.0
49 verbose afterAdd /Users/shiva/.npm/history/1.13.0/package/package.json not in flight; writing
50 verbose afterAdd /Users/shiva/.npm/history/1.13.0/package/package.json written
51 silly fetchNamedPackageData deep-equal
52 silly mapToRegistry name deep-equal
53 silly mapToRegistry using default registry
54 silly mapToRegistry registry https://registry.npmjs.org/
55 silly mapToRegistry uri https://registry.npmjs.org/deep-equal
56 silly fetchNamedPackageData qs
57 silly mapToRegistry name qs
58 silly mapToRegistry using default registry
59 silly mapToRegistry registry https://registry.npmjs.org/
60 silly mapToRegistry uri https://registry.npmjs.org/qs
61 verbose request uri https://registry.npmjs.org/deep-equal
62 verbose request no auth needed
63 info attempt registry request try #1 at 1:31:44 PM
64 verbose request using bearer token for auth
65 verbose etag "AP5WROOM921L4QSRSDGAKP5W1"
66 http request GET https://registry.npmjs.org/deep-equal
67 verbose request uri https://registry.npmjs.org/qs
68 verbose request no auth needed
69 info attempt registry request try #1 at 1:31:44 PM
70 verbose request using bearer token for auth
71 verbose etag "2BA3MMB02AKO4HQ1EDPRIOP38"
72 http request GET https://registry.npmjs.org/qs
73 http 200 https://registry.npmjs.org/deep-equal
74 verbose headers { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
74 verbose headers   etag: '"BO8OCIWE509P5G035QKSR5VRH"',
74 verbose headers   'content-type': 'application/json',
74 verbose headers   'cache-control': 'max-age=60',
74 verbose headers   'content-length': '12264',
74 verbose headers   'accept-ranges': 'bytes',
74 verbose headers   date: 'Mon, 30 Nov 2015 08:01:44 GMT',
74 verbose headers   via: '1.1 varnish',
74 verbose headers   connection: 'keep-alive',
74 verbose headers   'x-served-by': 'cache-sin6926-SIN',
74 verbose headers   'x-cache': 'MISS',
74 verbose headers   'x-cache-hits': '0',
74 verbose headers   'x-timer': 'S1448870504.359094,VS0,VE208',
74 verbose headers   vary: 'Accept' }
75 silly get cb [ 200,
75 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
75 silly get     etag: '"BO8OCIWE509P5G035QKSR5VRH"',
75 silly get     'content-type': 'application/json',
75 silly get     'cache-control': 'max-age=60',
75 silly get     'content-length': '12264',
75 silly get     'accept-ranges': 'bytes',
75 silly get     date: 'Mon, 30 Nov 2015 08:01:44 GMT',
75 silly get     via: '1.1 varnish',
75 silly get     connection: 'keep-alive',
75 silly get     'x-served-by': 'cache-sin6926-SIN',
75 silly get     'x-cache': 'MISS',
75 silly get     'x-cache-hits': '0',
75 silly get     'x-timer': 'S1448870504.359094,VS0,VE208',
75 silly get     vary: 'Accept' } ]
76 verbose get saving deep-equal to /Users/shiva/.npm/registry.npmjs.org/deep-equal/.cache.json
77 silly resolveWithNewModule deep-equal@1.0.1 checking installable status
78 silly cache add args [ 'deep-equal@^1.0.0', null ]
79 verbose cache add spec deep-equal@^1.0.0
80 silly cache add parsed spec Result {
80 silly cache add   raw: 'deep-equal@^1.0.0',
80 silly cache add   scope: null,
80 silly cache add   name: 'deep-equal',
80 silly cache add   rawSpec: '^1.0.0',
80 silly cache add   spec: '>=1.0.0 <2.0.0',
80 silly cache add   type: 'range' }
81 silly addNamed deep-equal@>=1.0.0 <2.0.0
82 verbose addNamed ">=1.0.0 <2.0.0" is a valid semver range for deep-equal
83 silly addNameRange { name: 'deep-equal', range: '>=1.0.0 <2.0.0', hasData: false }
84 silly mapToRegistry name deep-equal
85 silly mapToRegistry using default registry
86 silly mapToRegistry registry https://registry.npmjs.org/
87 silly mapToRegistry uri https://registry.npmjs.org/deep-equal
88 verbose addNameRange registry:https://registry.npmjs.org/deep-equal not in flight; fetching
89 verbose get https://registry.npmjs.org/deep-equal not expired, no request
90 silly addNameRange number 2 { name: 'deep-equal', range: '>=1.0.0 <2.0.0', hasData: true }
91 silly addNameRange versions [ 'deep-equal',
91 silly addNameRange   [ '0.0.0',
91 silly addNameRange     '0.1.0',
91 silly addNameRange     '0.1.1',
91 silly addNameRange     '0.1.2',
91 silly addNameRange     '0.2.0',
91 silly addNameRange     '0.2.1',
91 silly addNameRange     '0.2.2',
91 silly addNameRange     '1.0.0',
91 silly addNameRange     '1.0.1' ] ]
92 silly addNamed deep-equal@1.0.1
93 verbose addNamed "1.0.1" is a plain semver version for deep-equal
94 silly cache afterAdd deep-equal@1.0.1
95 verbose afterAdd /Users/shiva/.npm/deep-equal/1.0.1/package/package.json not in flight; writing
96 verbose afterAdd /Users/shiva/.npm/deep-equal/1.0.1/package/package.json written
97 http 200 https://registry.npmjs.org/qs
98 verbose headers { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
98 verbose headers   etag: '"LYFKN2SIJE1DYZM1O83TGVNI"',
98 verbose headers   'content-type': 'application/json',
98 verbose headers   'cache-control': 'max-age=60',
98 verbose headers   'content-length': '64376',
98 verbose headers   'accept-ranges': 'bytes',
98 verbose headers   date: 'Mon, 30 Nov 2015 08:01:44 GMT',
98 verbose headers   via: '1.1 varnish',
98 verbose headers   connection: 'keep-alive',
98 verbose headers   'x-served-by': 'cache-sin6920-SIN',
98 verbose headers   'x-cache': 'MISS',
98 verbose headers   'x-cache-hits': '0',
98 verbose headers   'x-timer': 'S1448870504.363539,VS0,VE438',
98 verbose headers   vary: 'Accept' }
99 silly get cb [ 200,
99 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
99 silly get     etag: '"LYFKN2SIJE1DYZM1O83TGVNI"',
99 silly get     'content-type': 'application/json',
99 silly get     'cache-control': 'max-age=60',
99 silly get     'content-length': '64376',
99 silly get     'accept-ranges': 'bytes',
99 silly get     date: 'Mon, 30 Nov 2015 08:01:44 GMT',
99 silly get     via: '1.1 varnish',
99 silly get     connection: 'keep-alive',
99 silly get     'x-served-by': 'cache-sin6920-SIN',
99 silly get     'x-cache': 'MISS',
99 silly get     'x-cache-hits': '0',
99 silly get     'x-timer': 'S1448870504.363539,VS0,VE438',
99 silly get     vary: 'Accept' } ]
100 verbose get saving qs to /Users/shiva/.npm/registry.npmjs.org/qs/.cache.json
101 silly resolveWithNewModule qs@4.0.0 checking installable status
102 silly cache add args [ 'qs@^4.0.0', null ]
103 verbose cache add spec qs@^4.0.0
104 silly cache add parsed spec Result {
104 silly cache add   raw: 'qs@^4.0.0',
104 silly cache add   scope: null,
104 silly cache add   name: 'qs',
104 silly cache add   rawSpec: '^4.0.0',
104 silly cache add   spec: '>=4.0.0 <5.0.0',
104 silly cache add   type: 'range' }
105 silly addNamed qs@>=4.0.0 <5.0.0
106 verbose addNamed ">=4.0.0 <5.0.0" is a valid semver range for qs
107 silly addNameRange { name: 'qs', range: '>=4.0.0 <5.0.0', hasData: false }
108 silly mapToRegistry name qs
109 silly mapToRegistry using default registry
110 silly mapToRegistry registry https://registry.npmjs.org/
111 silly mapToRegistry uri https://registry.npmjs.org/qs
112 verbose addNameRange registry:https://registry.npmjs.org/qs not in flight; fetching
113 verbose get https://registry.npmjs.org/qs not expired, no request
114 silly addNameRange number 2 { name: 'qs', range: '>=4.0.0 <5.0.0', hasData: true }
115 silly addNameRange versions [ 'qs',
115 silly addNameRange   [ '0.0.1',
115 silly addNameRange     '0.0.2',
115 silly addNameRange     '0.0.3',
115 silly addNameRange     '0.0.4',
115 silly addNameRange     '0.0.5',
115 silly addNameRange     '0.0.6',
115 silly addNameRange     '0.0.7',
115 silly addNameRange     '0.1.0',
115 silly addNameRange     '0.2.0',
115 silly addNameRange     '0.3.0',
115 silly addNameRange     '0.3.1',
115 silly addNameRange     '0.3.2',
115 silly addNameRange     '0.4.0',
115 silly addNameRange     '0.4.1',
115 silly addNameRange     '0.4.2',
115 silly addNameRange     '0.5.0',
115 silly addNameRange     '0.5.1',
115 silly addNameRange     '0.5.2',
115 silly addNameRange     '0.5.3',
115 silly addNameRange     '0.5.4',
115 silly addNameRange     '0.5.5',
115 silly addNameRange     '0.5.6',
115 silly addNameRange     '0.6.0',
115 silly addNameRange     '0.6.1',
115 silly addNameRange     '0.6.2',
115 silly addNameRange     '0.6.3',
115 silly addNameRange     '0.6.4',
115 silly addNameRange     '0.6.5',
115 silly addNameRange     '0.6.6',
115 silly addNameRange     '1.0.0',
115 silly addNameRange     '1.0.1',
115 silly addNameRange     '1.0.2',
115 silly addNameRange     '1.1.0',
115 silly addNameRange     '1.2.0',
115 silly addNameRange     '1.2.1',
115 silly addNameRange     '1.2.2',
115 silly addNameRange     '2.0.0',
115 silly addNameRange     '2.1.0',
115 silly addNameRange     '2.2.0',
115 silly addNameRange     '2.2.1',
115 silly addNameRange     '2.2.2',
115 silly addNameRange     '2.2.3',
115 silly addNameRange     '2.2.4',
115 silly addNameRange     '2.2.5',
115 silly addNameRange     '2.3.0',
115 silly addNameRange     '2.3.1',
115 silly addNameRange     '2.3.2',
115 silly addNameRange     '2.3.3',
115 silly addNameRange     '2.4.0',
115 silly addNameRange     '2.4.1',
115 silly addNameRange     '2.4.2',
115 silly addNameRange     '3.0.0',
115 silly addNameRange     '3.1.0',
115 silly addNameRange     '4.0.0',
115 silly addNameRange     '5.0.0',
115 silly addNameRange     '5.1.0',
115 silly addNameRange     '5.2.0',
115 silly addNameRange     '6.0.0',
115 silly addNameRange     '6.0.1' ] ]
116 silly addNamed qs@4.0.0
117 verbose addNamed "4.0.0" is a plain semver version for qs
118 silly cache afterAdd qs@4.0.0
119 verbose afterAdd /Users/shiva/.npm/qs/4.0.0/package/package.json not in flight; writing
120 verbose afterAdd /Users/shiva/.npm/qs/4.0.0/package/package.json written
121 verbose stack TypeError: Cannot read property 'localeCompare' of undefined
121 verbose stack     at installOrder (/usr/local/lib/node_modules/npm/lib/install/deps.js:241:32)
121 verbose stack     at Array.sort (native)
121 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/deps.js:240:27
121 verbose stack     at cb (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
121 verbose stack     at resolveWithExistingModule (/usr/local/lib/node_modules/npm/lib/install/deps.js:377:3)
121 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/deps.js:347:5
121 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
121 verbose stack     at Array.forEach (native)
121 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
121 verbose stack     at Array.forEach (native)
122 verbose cwd /Users/shiva/<project-dir>
123 error Darwin 15.0.0
124 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
125 error node v4.2.1
126 error npm  v3.3.6
127 error Cannot read property 'localeCompare' of undefined
128 error If you need help, you may report this error at:
128 error     <https://github.com/npm/npm/issues>
129 verbose exit [ 1, true ]
```

**Comment by seekshiva** [comment]
Not sure what the issue was. Reinstalled node, and the issue is gone now.

**Comment by KenanY** [comment]
@seekshiva This was a bug that was fixed in `npm@3.3.7`,

**Comment by seekshiva** [comment]
Thanks.

**Comment by seekshiva** [comment]
Just curious... Can you point me to what the issue was?

**Comment by KenanY** [comment]
@seekshiva Sure thing: https://github.com/npm/npm/issues/9766, with https://github.com/npm/npm/pull/9890 being the fix.

**Comment by seekshiva** [comment]
:+1:
