### ISSUE TITLE
Can't publish package "Cannot read property 'fixNameField' of undefined"

### ISSUE THREAD

**Issue by malko** [npm/npm#10624]
when i run npm publish i got:
```
npm ERR! Linux 3.13.0-70-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "publish"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! Cannot read property 'fixNameField' of undefined
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jgotti/git/stuback/npm-debug.log

```

here's associated npm log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'publish' ]
2 info using npm@2.11.3
3 info using node@v0.12.7
4 verbose node symlink /usr/bin/node
5 verbose publish [ '.' ]
6 silly cache add args [ '.', null ]
7 verbose cache add spec .
8 silly cache add parsed spec { raw: '.',
8 silly cache add   scope: null,
8 silly cache add   name: null,
8 silly cache add   rawSpec: '.',
8 silly cache add   spec: '/home/jgotti/git/stuback',
8 silly cache add   type: 'directory' }
9 verbose addLocalDirectory /home/jgotti/.npm/stuback/0.2.6/package.tgz not in flight; packing
10 verbose getCacheStat cache creation not in flight; initializing
11 verbose tar pack [ '/home/jgotti/.npm/stuback/0.2.6/package.tgz',
11 verbose tar pack   '/home/jgotti/git/stuback' ]
12 verbose tarball /home/jgotti/.npm/stuback/0.2.6/package.tgz
13 verbose folder /home/jgotti/git/stuback
14 info prepublish stuback@0.2.6
15 verbose addLocalTarball adding from inside cache /home/jgotti/.npm/stuback/0.2.6/package.tgz
16 silly cache afterAdd stuback@0.2.6
17 verbose afterAdd /home/jgotti/.npm/stuback/0.2.6/package/package.json not in flight; writing
18 verbose afterAdd /home/jgotti/.npm/stuback/0.2.6/package/package.json written
19 silly publish { name: 'stuback',
19 silly publish   version: '0.2.6',
19 silly publish   description: 'proxy server to easily stub your apis and evenutally back your developpment server',
19 silly publish   main: 'server.js',
19 silly publish   scripts:
19 silly publish    { test: 'echo "Error: no test specified" && exit 1',
19 silly publish      watch: 'babel src -w -d dist ' },
19 silly publish   bin: { stuback: 'dist/server.js' },
19 silly publish   repository: { type: 'git', url: 'git+https://github.com/malko/stuback.git' },
19 silly publish   keywords: [ 'stub', 'proxy', 'server', 'http' ],
19 silly publish   author: { name: 'Jonathan Gotti aka Malko', email: 'jgotti@jgotti.org' },
19 silly publish   license: 'MIT',
19 silly publish   dependencies:
19 silly publish    { connect: '^3.4.0',
19 silly publish      mkdirp: '^0.5.1',
19 silly publish      'path-to-regexp': '^0.1.6',
19 silly publish      stpl: '^0.1.2' },
19 silly publish   devDependencies: { babel: '^5.5.8' },
19 silly publish   readme: '# stuback\n\nproxy server to ease api development\n\n[![Join the chat at https://gitter.im/malko/stuback](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/malko/stuback?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)\n\n## installation:\n```\nnpm install -g stuback\n```\n\nlaunch the server like this\n```\nstuback -p 3000 -c config.js -s ./stubs\n```\n\nSee sample config file for now for more info about configuration.\nThe config file will be watched for changes so you can edit without reloading the server.\n\n## How to work with stuback?\n\n### Sample configuration file explained:\nConfiguration files can be either a commonjs module like the one below, or a json file. The _.js_ or _.json_ extensions are required.\nStuback watch the configuration file for changes so it will be automatically read on save. If you didn\'t give him a configuration file it will create one for you in $USERDIR/.stuback.json\n\nHere\'s a commented sample configuration file:\n```javascrip\nmodule.exports = {\n\t/**********************************************************************************\n\t* Each host has it\'s own "hostConfig" section.                                    *\n\t* The key must match the received reqest hostname.                                *\n\t* **/!\\** when requesting your local machine the request will have a              *\n\t*         _null_ hostname, _stuback_ will then lookup for a _localhost_ config.   *\n\t**********************************************************************************/\n\tlocalhost: {\n\n\t\t// Optional server to redirect request to\n\t\t//(useful when stuback is used as a system or browser proxy)\n\t\ttargetHost: \'mydevelopmentserver.net\',\n\n\t\t// Optional port to redirect request to\n\t\ttargetPort: \'8080\',\n\n\t\t// When true stuback will try to proxy any request which doesn\'t match defined\n\t\t// paths in stubbed or backed.\n\t\t// If false you will get an error on not stubbed or backed urls.\n\t\t// You probably want true for a system defined proxy and probably in most cases\n\t\tpassthrough: true,\n\n\t\t// default proxyied request doesn\'t timeout. You can set a timeout on a by host basis.\n\t\ttimeout: 5000,\n\n\t\t/***************************************************************************\n\t\t* *stubs* contains a list of path which will be looked up for a stub file. *\n\t\t***************************************************************************/\n\t\tstubs: {\n\t\t\t// Keys are path patterns (as in connect/express) of urls to stubs,\n\t\t\t// they will be looked up in order they are defined.\n\t\t\t\'/api/doc.html\': true, // boolean value can be used as a shortcut for {use: true}\n\n\t\t\t\'/api/*\': {\n\t\t\t\t// True if ommited, tell stuback whether this path should be used\n\t\t\t\t// for url matching or not. This is a convenience to quickly disable\n\t\t\t\t// a path from the config without removing the it from the file.\n\t\t\t\tuse: true,\n\n\t\t\t\t// You can defined specific response headers for a given path.\n\t\t\t\t// They will be applied after hostConfig.responseHeaders and hostConfig.stubs.responseHeaders settings\n\t\t\t\t// Any falsy value will result in header removal.\n\t\t\t\tresponseHeaders: {\n\t\t\t\t\t// add a Content-Type header\n\t\t\t\t\t\'Content-Type\': \'application/vnd.myapimediatype+json\',\n\t\t\t\t\t// remove any WWW-Authenticate header\n\t\t\t\t\t\'WWW-Authenticate\': false\n\t\t\t\t},\n\n\t\t\t\t// Optionally you can force a particular response statusCode for a given path\n\t\t\t\tstatusCode: 500\n\n\t\t\t\t// don\'t include this, it\'s just here to tell you that it\'s a reserved name\n\t\t\t\texp: undefined\n\t\t\t},\n\n\t\t\t// You can defined specific response headers for all stubbed paths at once.\n\t\t\t// They will be applied after hostConfig.responseHeaders settings and\n\t\t\t// before hostConfig.stubs.path.responseHeaders.\n\t\t\t// Falsy values will result in header removal.\n\t\t\tresponseHeaders: { \'Content-Type\': \'application/json\' }\n\t\t},\n\n\t\t/*************************************************************************************\n\t\t* **backed** contains a list of path patterns which will be looked up _after_        *\n\t\t* the one in stubs.                                                                  *\n\t\t* Each paths has it\'s own config as in stubs.                                        *\n\t\t* If a url matched then it will try to reach the remote server and will backup       *\n\t\t* the response in your stubs directory before returning it as a response.            *\n\t\t* If the remote server request doesn\'t work then the backup will be returned instead.*\n\t\t* All configs from stubs section may apply here.                                     *\n\t\t*************************************************************************************/\n\t\tbacked: {\n\t\t\t// Keys are path patterns (as in connect/express) of urls to backup.\n\t\t\t// They will be looked up in order they are defined.\n\t\t\t\'/*\': {\n\t\t\t\tuse: true,\n\t\t\t\tresponseHeaders: {\n\t\t\t\t\t\'Content-Type\': \'Application/json\'\n\t\t\t\t},\n\t\t\t\tstatusCode: 200,\n\n\t\t\t\t// by default each request to the remote server are considered success\n\t\t\t\t// whenever the server gave one, whatever their status code is.\n\t\t\t\t// So stuback will probably save an empty stub on 404 or 500 server error.\n\t\t\t\t// It can actually be the right thing to reply but if not\n\t\t\t\t// *backedStatusCode* is a list of remote server statusCode you want to\n\t\t\t\t// consider erroneous. So the actual stub file will be returned instead\n\t\t\t\t// if the server respond with one of the given codes\n\t\t\t\tonStatusCode: [404, 500],\n\n\t\t\t\t// don\'t include this, it\'s just here to tell you that it\'s a reserved name\n\t\t\t\texp: undefined\n\t\t\t},\n\n\t\t\t// You can also define statusCodes to consider erroneous for all backed paths at once\n\t\t\tonStatusCode: [500],\n\t\t}\n\n\t\t// this is not used at this time but reserved for future use.\n\t\ttampered: {}\n\n\t\t// You can set response headers to add to any stuback response for this specific host.\n\t\t// They will be applied first in any cases, falsy values will result in header removal.\n\t\tresponseHeaders: { // list of headers to add to proxyed response, will be removed if falsy\n\t\t\t\'X-stuback-custom\': \'stubacked\'\n\t\t}\n\t}\n\n\t// optional credentials for the admin section\n\tadminLogin: \'login\',\n\tadminPass: \'Password\'\n}\n```\n\n\n### system or browser proxy:\nYou can use Proxy Automatic Configuration by setting your system or browser automatic proxy settings to ```http://127.0.0.1:3000/proxy.pac``` (change port accodingly to your settings).\n\nThis method require no modification to your application code and is quick to set in place.\nThe bad part is you will have to reset your proxy settings everytime you change your configuration file (changing stubs, backed or tampered may work without changing your settings).\nThis is the prefered method when working on a remote host with no access to the code or when the code use the endpoint to call at multiple place in your code.\n\n\n### direct server call:\nYou can direct your application api calls to localhost or any other address your proxy will respond on and use targetHost and targetPort settings like in sample configuration above.\nThis has the advantage of not modifying your browser or system proxy settings and so you won\'t have to reset them on configuration change.\nThe bad part is you need to modify your code base to direct request to the proxy instead.\nThis method is prefered when your application can use different hosts depending on env or application settings for example.\n\n\n### Where to put my stubs\nstubs will be organised and looked-up in the following way:\n```\n/stubs\n\t|_ hostname\n\t \t|_ [lowercase_http_verb]-encodeURIComponent(pathUrl)-md5(parameters)\n```\nuse the --verbose option to see which files stuback is trying to reach, so you can easily copy/paste names to create new stubs files.\n\n### Access to the admin section:\nYou can access the admin section pointing to http://localhost:3000/stuback/admin\n\n## This is for the DEV\nStuback is in no way intended to be used for anything else than development.\nI use stuback for my daily needs and i\'ll be happy if it can help you in your job. As always, feature request, contributions(code, documentation or logo) and bug reporting are more than welcome.\n',
19 silly publish   readmeFilename: 'README.md',
19 silly publish   gitHead: '95e04f882a2f2707a9ab682b2dd1f9df28a0c126',
19 silly publish   bugs: { url: 'https://github.com/malko/stuback/issues' },
19 silly publish   homepage: 'https://github.com/malko/stuback#readme',
19 silly publish   _id: 'stuback@0.2.6',
19 silly publish   _shasum: '16daa5a94057b7f2346b5fc5e45645e905409bb9',
19 silly publish   _from: '.' }
20 verbose getPublishConfig undefined
21 silly mapToRegistry name stuback
22 silly mapToRegistry using default registry
23 silly mapToRegistry registry https://registry.npmjs.org/
24 silly mapToRegistry uri https://registry.npmjs.org/stuback
25 verbose publish registryBase https://registry.npmjs.org/
26 silly publish uploading /home/jgotti/.npm/stuback/0.2.6/package.tgz
27 verbose stack TypeError: Cannot read property 'fixNameField' of undefined
27 verbose stack     at CachingRegistryClient.publish (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/publish.js:41:10)
27 verbose stack     at /usr/lib/node_modules/npm/lib/publish.js:134:14
27 verbose stack     at mapToRegistry (/usr/lib/node_modules/npm/lib/utils/map-to-registry.js:55:3)
27 verbose stack     at publish_ (/usr/lib/node_modules/npm/lib/publish.js:104:3)
27 verbose stack     at Array.<anonymous> (/usr/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
27 verbose stack     at LOOP (/usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
27 verbose stack     at LOOP (/usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:14:28)
27 verbose stack     at chain (/usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
27 verbose stack     at /usr/lib/node_modules/npm/lib/publish.js:73:5
27 verbose stack     at RES (/usr/lib/node_modules/npm/node_modules/inflight/inflight.js:23:14)
28 verbose cwd /home/jgotti/git/stuback
29 error Linux 3.13.0-70-generic
30 error argv "/usr/bin/node" "/usr/bin/npm" "publish"
31 error node v0.12.7
32 error npm  v2.11.3
33 error Cannot read property 'fixNameField' of undefined
34 error If you need help, you may report this error at:
34 error     <https://github.com/npm/npm/issues>
35 verbose exit [ 1, true ]
```

Can someone please help me on this ?

**Comment by KenanY** [comment]
@malko Could you try [updating `npm`](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) first to make sure this isn't something that has been fixed?

**Comment by malko** [comment]
npm version 2.14.9 => same error
npm version 3.5.0 => it's ok

**Comment by hoshin** [comment]
Hi,

I'm having the same issue (same error, npm-log points to the same portion of code)

I'm using n to manage npm / node versions and tried multiple versions (current node LTS, latest version, versions inbetween...). I haven't scanned through each one yet but if I could avoid it it'd be much appreciated :P

I've tried various things for lack of better ideas like clearing the npm cache (in the hopes of stumbling on some side effect), no luck so far.

From what I can figure out, the "normalize-package-data" module I have installed does not expose anything named "fixer", but does expose a "normalize" function, which then causes the publishing logic to crash. Does that ring any bells ?

**Comment by hoshin** [comment]
After some more fiddling around, it seems that the issue comes from the installation on my end (switched to another machine and I got no problems to publish), it worked straight away. I'll have a look and try to figure out what the difference is.

**Comment by KenanY** [comment]
Closing as apparently fixed in `npm@3`. If this is still an issue with the latest version of `npm@2` I can easily reopen.
