### ISSUE TITLE
npm 3.5.0 downloads jade-ext 0.0.7 but tries to install jade-ext 0.0.6

### ISSUE THREAD

**Issue by vibol** [npm/npm#10641]
I'm having a problem with npm 3.5.0. This problem does not happen with npm 2.14.9.

jade-ext is being pulled in as part of compoundjs. notice how 0.0.7 is added/downloaded, but 0.0.6 is what npm tries to open.

```
npm verb cache add spec jade-ext@>= 0.0.5
npm verb addNamed ">=0.0.5" is a valid semver range for jade-ext
npm verb addNameRange registry:https://registry.npmjs.org/jade-ext not in flight; fetching
npm verb afterAdd /Users/vhou/.npm/inflection/1.2.7/package/package.json written
npm verb afterAdd /Users/vhou/.npm/ejs-ext/0.1.4-5/package/package.json written
npm verb afterAdd /Users/vhou/.npm/railway-routes/0.0.10/package/package.json written
npm verb get https://registry.npmjs.org/jade-ext not expired, no request
npm verb addNamed "0.0.7" is a plain semver version for jade-ext
npm verb afterAdd /Users/vhou/.npm/jade-ext/0.0.7/package/package.json not in flight; writing
npm verb afterAdd /Users/vhou/.npm/jade-ext/0.0.7/package/package.json written
npm verb stack Error: Error extracting /Users/vhou/.npm/jade-ext/0.0.6/package.tgz archive: ENOENT, open '/Users/vhou/.npm/jade-ext/0.0.6/package.tgz'
npm verb stack     at ReadStream.<anonymous> (/Users/vhou/.nvm/versions/node/v0.12.8/lib/node_modules/npm/lib/fetch-package-metadata.js:286:10)
npm verb stack     at ReadStream.emit (events.js:107:17)
npm verb stack     at /Users/vhou/.nvm/versions/node/v0.12.8/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:179:14
npm verb stack     at /Users/vhou/.nvm/versions/node/v0.12.8/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:230:16
npm verb stack     at FSReqWrap.oncomplete (fs.js:95:15)
npm verb cwd /Users/vhou/Pluto/set/curation-website
npm ERR! Darwin 15.0.0
npm ERR! argv "node" "/Users/vhou/.nvm/versions/node/v0.12.8/bin/npm" "install" "--verbose"
npm ERR! node v0.12.8
npm ERR! npm  v3.5.0
npm ERR! code EREADFILE

npm ERR! Error extracting /Users/vhou/.npm/jade-ext/0.0.6/package.tgz archive: ENOENT, open '/Users/vhou/.npm/jade-ext/0.0.6/package.tgz'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm verb exit [ 1, true ]
```

**Comment by sorrycc** [comment]
:+1:

**Comment by fengmk2** [comment]
Same problem on npm@3.5.1

**Comment by ALoppukaarre** [comment]
As well as npm@3.3.12

**Comment by othiym23** [comment]
A simpler repro:

```
$ npm i -ddd 'jade-ext@>= 0.0.5'
```

I am not 100% sure what's happening here, and @iarna will need to check my reasoning here, but here's what I think:

1. `compoundjs` depends on `jade-ext@>=0.0.5`, a semver range.
2. `jade-ext@latest` is `0.0.7-10`, a prerelease version.
3. The internal utility function used by the npm installer to resolve package metadata, `fetchPackageMetadata`, has its own logic to decide what the latest version of a requested package is. It uses `node-semver` directly, and for some reason decides that `jade-ext@0.0.6` is the version that should be installed. _This is the bug._ It _should_ return the greatest matching version that's not a prerelease version of the package.
4. Later, npm requests `jade-ext@>=0.0.5` from the cache. The caching code correctly decides that it should download `jade-ext@0.0.7` from the registry, and does so.
5. The installer still thinks that it's installing `jade-ext@0.0.6`, and tries to open that tarball from the cache directly, and explodes, leaving everyone here.

`fetchPackageMetadata`'s logic is a little opaque here, and it doesn't log anything about its decision-making process. Ultimately, the problem is that `fetchPackageMetadata` and the caching code each have their own code for resolving a package spec to a specific version of a package to cache and install; that logic should be in one place. That will probably require some more in-depth refactoring of the interface between the installer and the cache, so just squaring up the logic here is probably good enough for now.

**Comment by alubbe** [comment]
Any news on this?

**Comment by bryanrasmussen** [comment]
It worked for me to install jade-ext@0.0.6 explicitly before running my normal npm install.

**Comment by cnicolaou** [comment]
@bryanrasmussen same here.

`npm i -ddd 'jade-ext@0.0.6'`

**Comment by bvenkatr** [comment]
@othiym23 Hi I am facing same issue and this `npm i -ddd 'jade-ext@0.0.6'` resolve the issue, May I know what is "-ddd" and what it do?

**Comment by KenanY** [comment]
@bvenkatr It is [shorthand](https://docs.npmjs.com/misc/config#shorthands-and-other-cli-niceties) for `--loglevel silly`.
