### ISSUE TITLE
Error: EACCES: permission denied, open '/Users/mac/.config/configstore/update-notifier-cordova.json' You don't have access to this file.

### ISSUE THREAD

**Issue by sam2908** [npm/npm#10670]
iMac-de-mac:desktop mac$ cordova create workshop com.yourname.workshop Workshop
/usr/local/lib/node_modules/cordova/node_modules/update-notifier/node_modules/configstore/index.js:53
				throw err;
				^

Error: EACCES: permission denied, open '/Users/mac/.config/configstore/update-notifier-cordova.json'
You don't have access to this file.

    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.create.all.get (/usr/local/lib/node_modules/cordova/node_modules/update-notifier/node_modules/configstore/index.js:34:26)
    at Object.Configstore (/usr/local/lib/node_modules/cordova/node_modules/update-notifier/node_modules/configstore/index.js:27:44)
    at new UpdateNotifier (/usr/local/lib/node_modules/cordova/node_modules/update-notifier/index.js:34:17)
    at module.exports (/usr/local/lib/node_modules/cordova/node_modules/update-notifier/index.js:123:23)
    at checkForUpdates (/usr/local/lib/node_modules/cordova/src/cli.js:64:20)
    at cli (/usr/local/lib/node_modules/cordova/src/cli.js:114:5)
    at Object.<anonymous> (/usr/local/lib/node_modules/cordova/bin/cordova:41:1)

**Comment by KenanY** [comment]
Hello @sam2908, this does not look like an issue with `npm` (I say this mostly because I noticed how you received this error by running something other than `npm`). Regardless, I think the fix would be as easy as simply changing the permissions of that file with `chown`.

**Comment by sam2908** [comment]
Hello @KenanY , thank you for your response. how to change permission

**Comment by sam2908** [comment]
@KenanY  :) Thank You ,I solved the problem
