### ISSUE TITLE
npm outdated command error - cannot find module 'minimatch'

### ISSUE THREAD

**Issue by jedeegan** [npm/npm#10697]
npm-debug.log file follows:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'outdated' ]
2 info using npm@3.3.12
3 info using node@v5.1.1
4 verbose stack Error: Cannot find module 'minimatch'
4 verbose stack     at Function.Module._resolveFilename (module.js:338:15)
4 verbose stack     at Function.Module._load (module.js:289:25)
4 verbose stack     at Module.require (module.js:366:17)
4 verbose stack     at require (module.js:385:17)
4 verbose stack     at Object.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\node_modules\glob\glob.js:44:17)
4 verbose stack     at Module._compile (module.js:425:26)
4 verbose stack     at Object.Module._extensions..js (module.js:432:10)
4 verbose stack     at Module.load (module.js:356:32)
4 verbose stack     at Function.Module._load (module.js:313:12)
4 verbose stack     at Module.require (module.js:366:17)
5 verbose cwd C:\Program Files\nodejs
6 error Windows_NT 6.1.7601
7 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "outdated"
8 error node v5.1.1
9 error npm  v3.3.12
10 error code MODULE_NOT_FOUND
11 error Cannot find module 'minimatch'
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]
```

**Comment by othiym23** [comment]
Unfortunately, what this means is that your installation of npm has been broken, probably by the Node.js installer. To fix it, you'll need to completely uninstall Node.js (and afterwards go into `C:\Program Files\nodejs` and make sure that everything's been removed) and then reinstall Node. It's a known issue, and should be fixed in the relatively near future. Sorry for the lost time!
