### ISSUE TITLE
unable to publish package - You cannot publish over the previously published

### ISSUE THREAD

**Issue by przemyslawpluta** [npm/npm#10692]
After running `npm publish` on `OSX` I'm getting **You cannot publish over the previously published version 0.2.3**. That version was never published before. Tried to publish higher versions produces same error message.

```bash
npm ERR! publish Failed PUT 403
npm ERR! Error: "You cannot publish over the previously published version 0.2.3." : mongo-edu
npm ERR!     at RegClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:308:14)
npm ERR!     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:246:65)
npm ERR!     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:236:22)
npm ERR!     at Request.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1142:14)
npm ERR!     at Request.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1096:12)
npm ERR!     at IncomingMessage.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:944:16
npm ERR!     at process._tickCallback (node.js:442:13)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 12.5.0
npm ERR! command "node" "/usr/local/bin/npm" "publish"
npm ERR! cwd /Users/dev/Node/mongo-edu
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/dev/Node/mongo-edu/npm-debug.log
npm ERR! not ok code 0
```

**Comment by przemyslawpluta** [comment]
```bash
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'publish' ]
2 info using npm@1.4.28
3 info using node@v0.10.36
4 verbose publish [ '.' ]
5 verbose cache add [ '.', null ]
6 verbose cache add name=undefined spec="." args=[".",null]
7 verbose parsed url { protocol: null,
7 verbose parsed url   slashes: null,
7 verbose parsed url   auth: null,
7 verbose parsed url   host: null,
7 verbose parsed url   port: null,
7 verbose parsed url   hostname: null,
7 verbose parsed url   hash: null,
7 verbose parsed url   search: null,
7 verbose parsed url   query: null,
7 verbose parsed url   pathname: '.',
7 verbose parsed url   path: '.',
7 verbose parsed url   href: '.' }
8 silly lockFile 3a52ce78- .
9 verbose lock . /Users/dev/.npm/3a52ce78-.lock
10 verbose tar pack [ '/Users/dev/.npm/mongo-edu/0.2.3/package.tgz', '.' ]
11 verbose tarball /Users/dev/.npm/mongo-edu/0.2.3/package.tgz
12 verbose folder .
13 info prepublish mongo-edu@0.2.3
14 silly lockFile 1f1177db-tar tar://.
15 verbose lock tar://. /Users/dev/.npm/1f1177db-tar.lock
16 silly lockFile 9b752787--npm-mongo-edu-0-2-3-package-tgz tar:///Users/dev/.npm/mongo-edu/0.2.3/package.tgz
17 verbose lock tar:///Users/dev/.npm/mongo-edu/0.2.3/package.tgz /Users/dev/.npm/9b752787--npm-mongo-edu-0-2-3-package-tgz.lock
18 silly lockFile 1f1177db-tar tar://.
19 silly lockFile 1f1177db-tar tar://.
20 silly lockFile 9b752787--npm-mongo-edu-0-2-3-package-tgz tar:///Users/dev/.npm/mongo-edu/0.2.3/package.tgz
21 silly lockFile 9b752787--npm-mongo-edu-0-2-3-package-tgz tar:///Users/dev/.npm/mongo-edu/0.2.3/package.tgz
22 silly lockFile dac584d7-tapr-npm-mongo-edu-0-2-3-package /Users/dev/.npm/mongo-edu/0.2.3/package
23 verbose lock /Users/dev/.npm/mongo-edu/0.2.3/package /Users/dev/.npm/dac584d7-tapr-npm-mongo-edu-0-2-3-package.lock
24 silly lockFile dac584d7-tapr-npm-mongo-edu-0-2-3-package /Users/dev/.npm/mongo-edu/0.2.3/package
25 silly lockFile dac584d7-tapr-npm-mongo-edu-0-2-3-package /Users/dev/.npm/mongo-edu/0.2.3/package
26 silly lockFile 3a52ce78- .
27 silly lockFile 3a52ce78- .
28 silly publish { name: 'mongo-edu',
28 silly publish   preferGlobal: true,
28 silly publish   version: '0.2.3',
28 silly publish   author:
28 silly publish    { name: 'Przemyslaw Pluta',
28 silly publish      email: 'przemyslawplutadev@gmail.com',
28 silly publish      url: 'http://przemyslawpluta.com' },
28 silly publish   description: 'Select and download videos and handouts from university.mongodb.com courses',
28 silly publish   main: './mongo-edu',
28 silly publish   scripts: { start: 'node ./bin/mongo-edu' },
28 silly publish   bin: { 'mongo-edu': './bin/mongo-edu' },
28 silly publish   repository:
28 silly publish    { type: 'git',
28 silly publish      url: 'https://github.com/przemyslawpluta/mongo-edu.git' },
28 silly publish   keywords:
28 silly publish    [ 'mongodb',
28 silly publish      'download',
28 silly publish      'handouts',
28 silly publish      'closed captions',
28 silly publish      'videos',
28 silly publish      'youtube',
28 silly publish      'playlists',
28 silly publish      'course',
28 silly publish      'education',
28 silly publish      'university',
28 silly publish      'edu' ],
28 silly publish   license: 'MIT',
28 silly publish   dependencies:
28 silly publish    { cheerio: '~0.19.0',
28 silly publish      colors: '~1.1.2',
28 silly publish      'easy-table': '~1.0.0',
28 silly publish      'extract-zip': '~1.2.0',
28 silly publish      filesize: '~3.1.4',
28 silly publish      glob: '~6.0.1',
28 silly publish      inquirer: '~0.11.0',
28 silly publish      lodash: '~3.10.1',
28 silly publish      mkdirp: '~0.5.1',
28 silly publish      mv: '~2.1.1',
28 silly publish      'path-extra': '~3.0.0',
28 silly publish      'pretty-error': '~1.2.0',
28 silly publish      progress: '~1.1.8',
28 silly publish      request: '~2.67.0',
28 silly publish      'request-progress': '~0.4.0',
28 silly publish      rimraf: '~2.4.4',
28 silly publish      which: '~1.2.0',
28 silly publish      yargs: '~3.30.0',
28 silly publish      'youtube-dl': '~1.10.5' },
28 silly publish   engines: { node: '>= 0.8.x' },
28 silly publish   bugs: { url: 'https://github.com/przemyslawpluta/mongo-edu/issues' },
28 silly publish   homepage: 'https://github.com/przemyslawpluta/mongo-edu',
28 silly publish   devDependencies: {},
28 silly publish   readme: 'mongo-edu\n=========\n\n[![NPM](https://nodei.co/npm/mongo-edu.png?compact=true)](https://nodei.co/npm/mongo-edu/)\n\n[![NPM version](https://badge.fury.io/js/mongo-edu.png)](http://badge.fury.io/js/mongo-edu)\n[![Dependency Status](https://gemnasium.com/przemyslawpluta/mongo-edu.png)](https://gemnasium.com/przemyslawpluta/mongo-edu)\n[![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/przemyslawpluta/mongo-edu?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)\n\nSelect and download videos and handouts from [university.mongodb.com](https://university.mongodb.com) courses\n\n## Prerequisite\n\n```\npy 2.7 or 3.x\n```\n\n## Installation\n\n```\nnpm install mongo-edu -g\n```\n\nor see [detailed installation guide](https://github.com/przemyslawpluta/mongo-edu/wiki/Installation) in the wiki pages\n\n## Usage\n\n```\n$ mongo-edu --help\n\nOptions:\n  -d          download path                             [required]\n  -u          email address\n  --py        pass switch to point to Python\n  --ncc       no check certificate for py3.x < py3.4.x\n  --verbose   print debug info\n\nVideos:\n  --cw        switch from wiki video lists (default) to courseware\n  --cwd       same as --cw and dumps list of videos to file in -d\n  --co        arrange video files in correct order of the courseware\n  --cc        get closed captions\n  --hq        get high quality videos\n\nHandouts:\n  -h          switch from videos (default) to handouts\n  --uz        unzip handout files\n\nProxy:\n  --proxy     pass proxy switch for video download\n  --test      use with --proxy to test if usable\n\nPresets:\n  --save      save presets\n  --load      load presets\n\n```\n\n## Select and download\n\n### Videos and closed captions\n\nDownload all available videos from lists present in the `wiki` pages for any given week. If no lists are present in `wiki` add `--cw` to search through the main courseware pages.\n\nAdd `--cc` to download closed captions with the videos and `--hq` to get high quality videos. Use with `--co` to sequence the video files in order of the wiki ( based on the order of the files present in the wiki lists ) or courseware ( when used with `--cw` preserves the courseware order ).\n\n![screenshot](https://raw.github.com/przemyslawpluta/mongo-edu/gh-pages/images/edu-videos.gif)\n\n### Videos via proxy\n\nYou can download videos via proxy tunnel. To test if proxy is usable just pass `--proxy http://proxy_ip_address:proxy_port_number --test` to download a test video via specified proxy. If succesfull just remove `--test` and pass the rest of the required flags.\n\n### Handouts\n\nAdd `-h` to download all available handouts present in the `syllabus` pages for any given week and `--uz` to unzip files after the download.\n\n![screenshot](https://raw.github.com/przemyslawpluta/mongo-edu/gh-pages/images/edu-handouts.gif)\n\n## Save / Load presets\n\nYou can save presets for use for later. To do so just add `--save my_preset_name` at the end of your call sequence. To recall saved presets just specify `--load ..`.\n\n![screenshot](https://raw.github.com/przemyslawpluta/mongo-edu/gh-pages/images/me-presets.gif)\n\n## License\nMIT\n',
28 silly publish   readmeFilename: 'README.md',
28 silly publish   gitHead: 'ad9d8614d8132ec2ec551b1e16ea0c4cf97d88ff',
28 silly publish   _id: 'mongo-edu@0.2.3',
28 silly publish   _shasum: '175d73fe53efb002492ef3f25f00c560f0771e5d',
28 silly publish   _from: '.' }
29 verbose request where is /mongo-edu
30 verbose request registry https://registry.npmjs.org/
31 verbose request id 5a79a26eea44cee1
32 verbose url raw /mongo-edu
33 verbose url resolving [ 'https://registry.npmjs.org/', './mongo-edu' ]
34 verbose url resolved https://registry.npmjs.org/mongo-edu
35 verbose request where is https://registry.npmjs.org/mongo-edu
36 info trying registry request attempt 1 at 13:15:22
37 http PUT https://registry.npmjs.org/mongo-edu
38 http 403 https://registry.npmjs.org/mongo-edu
39 verbose headers { 'content-type': 'application/json',
39 verbose headers   'cache-control': 'max-age=60',
39 verbose headers   'content-length': '95',
39 verbose headers   'accept-ranges': 'bytes',
39 verbose headers   date: 'Fri, 04 Dec 2015 13:15:23 GMT',
39 verbose headers   via: '1.1 varnish',
39 verbose headers   connection: 'keep-alive',
39 verbose headers   'x-served-by': 'cache-lcy1127-LCY',
39 verbose headers   'x-cache': 'MISS',
39 verbose headers   'x-cache-hits': '0',
39 verbose headers   'x-timer': 'S1449234921.288279,VS0,VE1764' }
40 error publish Failed PUT 403
41 error Error: "You cannot publish over the previously published version 0.2.3." : mongo-edu
41 error     at RegClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:308:14)
41 error     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:246:65)
41 error     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:236:22)
41 error     at Request.emit (events.js:98:17)
41 error     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1142:14)
41 error     at Request.emit (events.js:117:20)
41 error     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1096:12)
41 error     at IncomingMessage.emit (events.js:117:20)
41 error     at _stream_readable.js:944:16
41 error     at process._tickCallback (node.js:442:13)
42 error If you need help, you may report this *entire* log,
42 error including the npm and node versions, at:
42 error     <http://github.com/npm/npm/issues>
43 error System Darwin 12.5.0
44 error command "node" "/usr/local/bin/npm" "publish"
45 error cwd /Users/dev/Node/mongo-edu
46 error node -v v0.10.36
47 error npm -v 1.4.28
48 verbose exit [ 1, true ]

```

**Comment by KenanY** [comment]
@przemyslawpluta Are you absolutely sure that `0.2.3` has never been published before? Looks to me like it was at `2014-12-12T09:59:15.680Z`.

**Comment by przemyslawpluta** [comment]
@KenanY you're correct! Trying to do too many things at the same time. Published just now without any issues ... Thanks @KenanY

**Comment by KenanY** [comment]
@przemyslawpluta No problem! :)
