### ISSUE TITLE
Error Installing on Windows 7

### ISSUE THREAD

**Issue by chadbryant** [npm/npm#10710]
```
101177 silly build gulp-batch@1.0.5
101178 verbose stack RangeError: Maximum call stack size exceeded
101178 verbose stack     at Array.forEach (native)
101178 verbose stack     at TrackerGroup.completed (C:\Program Files\nodejs\node_modules\npm\node_modules\npmlog\node_modules\are-we-there-yet\index.js:26:19)
101178 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\npmlog\node_modules\are-we-there-yet\index.js:27:47
101178 verbose stack     at Array.forEach (native)
101178 verbose stack     at TrackerGroup.completed (C:\Program Files\nodejs\node_modules\npm\node_modules\npmlog\node_modules\are-we-there-yet\index.js:26:19)
101178 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\npmlog\node_modules\are-we-there-yet\index.js:27:47
101178 verbose stack     at Array.forEach (native)
101178 verbose stack     at TrackerGroup.completed (C:\Program Files\nodejs\node_modules\npm\node_modules\npmlog\node_modules\are-we-there-yet\index.js:26:19)
101178 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\npmlog\node_modules\are-we-there-yet\index.js:27:47
101178 verbose stack     at Array.forEach (native)
101179 verbose cwd C:\wamp\www\NewDMN
101180 error Windows_NT 6.1.7601
101181 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--no-bin-links"
101182 error node v5.1.1
101183 error npm  v3.3.12
101184 error Maximum call stack size exceeded
101185 error If you need help, you may report this error at:
101185 error     <https://github.com/npm/npm/issues>
101186 verbose exit [ 1, true ]
```

[npm-debug.txt](https://github.com/npm/npm/files/52946/npm-debug.txt)

**Comment by wanqiaoyufu** [comment]
@chadbryant Hava you salved?

**Comment by chadbryant** [comment]
No I have not.


________________________________

**Comment by othiym23** [comment]
Does this problem still occur if you [upgrade to a newer version](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows) of npm? The latest stable version of npm is `npm@3.5.2.`.
