### ISSUE TITLE
can't update npm with npm install -g npm

### ISSUE THREAD

**Issue by pulkitnandan** [npm/npm#10724]
Error 

C:\Users\Rohit\ad-analytics>npm install -g npm
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Rohit\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "npm"
npm ERR! node v4.1.0
npm ERR! npm  v3.3.3
npm ERR! code ENOSELF

npm ERR! Refusing to install npm as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Rohit\ad-analytics\npm-debug.log

Debug log

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Rohit\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'npm' ]
2 info using npm@3.3.3
3 info using node@v4.1.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData npm
8 silly fetchNamedPackageData npm
9 silly mapToRegistry name npm
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry uri https://registry.npmjs.org/npm
13 verbose get https://registry.npmjs.org/npm not expired, no request
14 silly install normalizeTree
15 silly loadCurrentTree Finishing
16 silly loadIdealTree Starting
17 silly install loadIdealTree
18 silly cloneCurrentTree Starting
19 silly install cloneCurrentTreeToIdealTree
20 silly cloneCurrentTree Finishing
21 silly loadShrinkwrap Starting
22 silly install loadShrinkwrap
23 silly loadShrinkwrap Finishing
24 silly loadAllDepsIntoIdealTree Starting
25 silly install loadAllDepsIntoIdealTree
26 silly rollbackFailedOptional Starting
27 silly rollbackFailedOptional Finishing
28 silly runTopLevelLifecycles Starting
29 silly runTopLevelLifecycles Finishing
30 silly install printInstalled
31 verbose stack Error: Refusing to install npm as a dependency of itself
31 verbose stack     at checkSelf (C:\Users\Rohit\AppData\Roaming\npm\node_modules\npm\lib\install\validate-args.js:40:14)
31 verbose stack     at Array.<anonymous> (C:\Users\Rohit\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
31 verbose stack     at LOOP (C:\Users\Rohit\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
31 verbose stack     at chain (C:\Users\Rohit\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
31 verbose stack     at C:\Users\Rohit\AppData\Roaming\npm\node_modules\npm\lib\install\validate-args.js:15:5
31 verbose stack     at C:\Users\Rohit\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:52:35
31 verbose stack     at Array.forEach (native)
31 verbose stack     at C:\Users\Rohit\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:52:11
31 verbose stack     at Array.forEach (native)
31 verbose stack     at asyncMap (C:\Users\Rohit\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:51:8)
32 verbose cwd C:\Users\Rohit\ad-analytics
33 error Windows_NT 10.0.10586
34 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Rohit\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "npm"
35 error node v4.1.0
36 error npm  v3.3.3
37 error code ENOSELF
38 error Refusing to install npm as a dependency of itself
39 error If you need help, you may report this error at:
39 error     <https://github.com/npm/npm/issues>
40 verbose exit [ 1, true ]

**Comment by pulkitnandan** [comment]
On ubuntu 15.04, similar issue exists with nodejs 5.x, it gives more severe errors that damaged my ubuntu installation when used solution from https://docs.npmjs.com/getting-started/fixing-npm-permissions
