### ISSUE TITLE
sudo npm install sends root ssh pub key to services like bitbucket and github

### ISSUE THREAD

**Issue by kamijoutouma** [npm/npm#10730]
the command i typed 
`sudo npm install git@bitbucket:ToumaKamijou/blowment.git -g && sudo npm link blowment`

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'git@bitbucket:ToumaKamijou/blowment.git',
1 verbose cli   '-g' ]
2 info using npm@3.3.6
3 info using node@v5.0.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData git@bitbucket:ToumaKamijou/blowment.git
8 silly fetchOtherPackageData git@bitbucket:ToumaKamijou/blowment.git
9 silly cache add args [ 'git@bitbucket:ToumaKamijou/blowment.git', null ]
10 verbose cache add spec git@bitbucket:ToumaKamijou/blowment.git
11 silly cache add parsed spec Result {
11 silly cache add   raw: 'git@bitbucket:ToumaKamijou/blowment.git',
11 silly cache add   scope: null,
11 silly cache add   name: 'git',
11 silly cache add   rawSpec: 'bitbucket:ToumaKamijou/blowment.git',
11 silly cache add   spec: 'bitbucket:toumakamijou/blowment',
11 silly cache add   type: 'hosted',
11 silly cache add   hosted:
11 silly cache add    { type: 'bitbucket',
11 silly cache add      ssh: 'git@bitbucket.org:toumakamijou/blowment.git',
11 silly cache add      sshUrl: 'git+ssh://git@bitbucket.org/toumakamijou/blowment.git',
11 silly cache add      httpsUrl: 'git+https://bitbucket.org/toumakamijou/blowment.git',
11 silly cache add      gitUrl: undefined,
11 silly cache add      shortcut: 'bitbucket:toumakamijou/blowment',
11 silly cache add      directUrl: 'https://bitbucket.org/toumakamijou/blowment/raw/master/package.json' } }
12 verbose addRemoteGit caching bitbucket:ToumaKamijou/blowment.git
13 verbose addRemoteGit bitbucket:toumakamijou/blowment is a repository hosted by bitbucket
14 silly tryHTTPS attempting to clone git+https://bitbucket.org/toumakamijou/blowment.git
15 silly tryClone cloning bitbucket:toumakamijou/blowment via git+https://bitbucket.org/toumakamijou/blowment.git
16 verbose tryClone git-https-bitbucket-org-toumakamijou-blowment-git-acce30146a16b2b2166f04760d480b37 not in flight; caching
17 info git [ 'clone',
17 info git   '--template=/root/.npm/_git-remotes/_templates',
17 info git   '--mirror',
17 info git   'https://bitbucket.org/toumakamijou/blowment.git',
17 info git   '/root/.npm/_git-remotes/git-https-bitbucket-org-toumakamijou-blowment-git-acce30146a16b2b2166f04760d480b37' ]
18 verbose git clone --template=/root/.npm/_git-remotes/_templates --mirror https://bitbucket.org/toumakamijou/blowment.git /root/.npm/_git-remotes/git-https-bitbucket-org-toumakamijou-blowment-git-acce30146a16b2b2166f04760d480b37: Cloning into bare repository '/root/.npm/_git-remotes/git-https-bitbucket-org-toumakamijou-blowment-git-acce30146a16b2b2166f04760d480b37'...
18 verbose git clone --template=/root/.npm/_git-remotes/_templates --mirror https://bitbucket.org/toumakamijou/blowment.git /root/.npm/_git-remotes/git-https-bitbucket-org-toumakamijou-blowment-git-acce30146a16b2b2166f04760d480b37: remote: Invalid username or password. If you log in via a third party service you must ensure you have an account password set in your account profile.
18 verbose git clone --template=/root/.npm/_git-remotes/_templates --mirror https://bitbucket.org/toumakamijou/blowment.git /root/.npm/_git-remotes/git-https-bitbucket-org-toumakamijou-blowment-git-acce30146a16b2b2166f04760d480b37: fatal: Authentication failed for 'https://bitbucket.org/toumakamijou/blowment.git/'
19 silly trySSH attempting to clone git@bitbucket.org:toumakamijou/blowment.git
20 silly tryClone cloning bitbucket:toumakamijou/blowment via git@bitbucket.org:toumakamijou/blowment.git
21 verbose tryClone git-bitbucket-org-toumakamijou-blowment-git-a7a4e04d6cbebf04854319f622e18a05 not in flight; caching
22 info git [ 'clone',
22 info git   '--template=/root/.npm/_git-remotes/_templates',
22 info git   '--mirror',
22 info git   'git@bitbucket.org:toumakamijou/blowment.git',
22 info git   '/root/.npm/_git-remotes/git-bitbucket-org-toumakamijou-blowment-git-a7a4e04d6cbebf04854319f622e18a05' ]
23 error git clone --template=/root/.npm/_git-remotes/_templates --mirror git@bitbucket.org:toumakamijou/blowment.git /root/.npm/_git-remotes/git-bitbucket-org-toumakamijou-blowment-git-a7a4e04d6cbebf04854319f622e18a05: Cloning into bare repository '/root/.npm/_git-remotes/git-bitbucket-org-toumakamijou-blowment-git-a7a4e04d6cbebf04854319f622e18a05'...
23 error git clone --template=/root/.npm/_git-remotes/_templates --mirror git@bitbucket.org:toumakamijou/blowment.git /root/.npm/_git-remotes/git-bitbucket-org-toumakamijou-blowment-git-a7a4e04d6cbebf04854319f622e18a05: Permission denied (publickey).
23 error git clone --template=/root/.npm/_git-remotes/_templates --mirror git@bitbucket.org:toumakamijou/blowment.git /root/.npm/_git-remotes/git-bitbucket-org-toumakamijou-blowment-git-a7a4e04d6cbebf04854319f622e18a05: fatal: Could not read from remote repository.
23 error git clone --template=/root/.npm/_git-remotes/_templates --mirror git@bitbucket.org:toumakamijou/blowment.git /root/.npm/_git-remotes/git-bitbucket-org-toumakamijou-blowment-git-a7a4e04d6cbebf04854319f622e18a05:
23 error git clone --template=/root/.npm/_git-remotes/_templates --mirror git@bitbucket.org:toumakamijou/blowment.git /root/.npm/_git-remotes/git-bitbucket-org-toumakamijou-blowment-git-a7a4e04d6cbebf04854319f622e18a05: Please make sure you have the correct access rights
23 error git clone --template=/root/.npm/_git-remotes/_templates --mirror git@bitbucket.org:toumakamijou/blowment.git /root/.npm/_git-remotes/git-bitbucket-org-toumakamijou-blowment-git-a7a4e04d6cbebf04854319f622e18a05: and the repository exists.
24 silly fetchPackageMetaData Error: Command failed: git clone --template=/root/.npm/_git-remotes/_templates --mirror git@bitbucket.org:toumakamijou/blowment.git /root/.npm/_git-remotes/git-bitbucket-org-toumakamijou-blowment-git-a7a4e04d6cbebf04854319f622e18a05
24 silly fetchPackageMetaData Cloning into bare repository '/root/.npm/_git-remotes/git-bitbucket-org-toumakamijou-blowment-git-a7a4e04d6cbebf04854319f622e18a05'...
24 silly fetchPackageMetaData Permission denied (publickey).
24 silly fetchPackageMetaData fatal: Could not read from remote repository.
24 silly fetchPackageMetaData
24 silly fetchPackageMetaData Please make sure you have the correct access rights
24 silly fetchPackageMetaData and the repository exists.
24 silly fetchPackageMetaData
24 silly fetchPackageMetaData     at ChildProcess.exithandler (child_process.js:203:12)
24 silly fetchPackageMetaData     at emitTwo (events.js:87:13)
24 silly fetchPackageMetaData     at ChildProcess.emit (events.js:172:7)
24 silly fetchPackageMetaData     at maybeClose (internal/child_process.js:818:16)
24 silly fetchPackageMetaData     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
24 silly fetchPackageMetaData  error for git@bitbucket:ToumaKamijou/blowment.git { [Error: Command failed: git clone --template=/root/.npm/_git-remotes/_templates --mirror git@bitbucket.org:toumakamijou/blowment.git /root/.npm/_git-remotes/git-bitbucket-org-toumakamijou-blowment-git-a7a4e04d6cbebf04854319f622e18a05
24 silly fetchPackageMetaData Cloning into bare repository '/root/.npm/_git-remotes/git-bitbucket-org-toumakamijou-blowment-git-a7a4e04d6cbebf04854319f622e18a05'...
24 silly fetchPackageMetaData Permission denied (publickey).
24 silly fetchPackageMetaData fatal: Could not read from remote repository.
24 silly fetchPackageMetaData
24 silly fetchPackageMetaData Please make sure you have the correct access rights
24 silly fetchPackageMetaData and the repository exists.
24 silly fetchPackageMetaData ]
24 silly fetchPackageMetaData   killed: false,
24 silly fetchPackageMetaData   code: 128,
24 silly fetchPackageMetaData   signal: null,
24 silly fetchPackageMetaData   cmd: 'git clone --template=/root/.npm/_git-remotes/_templates --mirror git@bitbucket.org:toumakamijou/blowment.git /root/.npm/_git-remotes/git-bitbucket-org-toumakamijou-blowment-git-a7a4e04d6cbebf04854319f622e18a05' }
25 silly rollbackFailedOptional Starting
26 silly rollbackFailedOptional Finishing
27 silly runTopLevelLifecycles Starting
28 silly runTopLevelLifecycles Finishing
29 silly install printInstalled
30 verbose stack Error: Command failed: git clone --template=/root/.npm/_git-remotes/_templates --mirror git@bitbucket.org:toumakamijou/blowment.git /root/.npm/_git-remotes/git-bitbucket-org-toumakamijou-blowment-git-a7a4e04d6cbebf04854319f622e18a05
30 verbose stack Cloning into bare repository '/root/.npm/_git-remotes/git-bitbucket-org-toumakamijou-blowment-git-a7a4e04d6cbebf04854319f622e18a05'...
30 verbose stack Permission denied (publickey).
30 verbose stack fatal: Could not read from remote repository.
30 verbose stack
30 verbose stack Please make sure you have the correct access rights
30 verbose stack and the repository exists.
30 verbose stack
30 verbose stack     at ChildProcess.exithandler (child_process.js:203:12)
30 verbose stack     at emitTwo (events.js:87:13)
30 verbose stack     at ChildProcess.emit (events.js:172:7)
30 verbose stack     at maybeClose (internal/child_process.js:818:16)
30 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
31 verbose cwd /home/touma/.ssh
32 error Linux 3.16.0-4-686-pae
33 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "git@bitbucket:ToumaKamijou/blowment.git" "-g"
34 error node v5.0.0
35 error npm  v3.3.6
36 error code 128
37 error Command failed: git clone --template=/root/.npm/_git-remotes/_templates --mirror git@bitbucket.org:toumakamijou/blowment.git /root/.npm/_git-remotes/git-bitbucket-org-toumakamijou-blowment-git-a7a4e04d6cbebf04854319f622e18a05
37 error Cloning into bare repository '/root/.npm/_git-remotes/git-bitbucket-org-toumakamijou-blowment-git-a7a4e04d6cbebf04854319f622e18a05'...
37 error Permission denied (publickey).
37 error fatal: Could not read from remote repository.
37 error
37 error Please make sure you have the correct access rights
37 error and the repository exists.
38 error If you need help, you may report this error at:
38 error     <https://github.com/npm/npm/issues>
39 verbose exit [ 1, true ]
```

Why is npm sending the root ssh key? why not send the ssh key of the sudoer which is already registered with bitbucket and github?

Cause i know for a fact that `touma` ssh key is registered with bitbucket ... i even ran `ssh -T hg@bitbucket.org` and it gave the normal expected response that it worked.

`sudo ssh -T hg@bitbucket.org` also returns the same error which is annoying especially since it means we are 'forced' to register our root ssh key with services atm.

It should also be noted that the -g `global` option DOES NOT work unless you sudo or are root, which is the main reason why i am using sudo in the first place.

**Comment by kamijoutouma** [comment]
Already found a workaround

sudo ssh-agent bash
ssh-add id_rsa
npm install git+ssh://git@bitbucket.org/ToumaKamijou/blowment.git -g && npm link blowment

**Comment by othiym23** [comment]
I'm going to close this issue as resolved because you found a workaround (and the behavior you describe is what I would expect when running npm as root), but I am curious, so: why were you running `npm install` via sudo? You should never need to run as root for a local install.

**Comment by kamijoutouma** [comment]
@othiym that says -g after the url ... So it is not a local install

**Comment by kamijoutouma** [comment]
Its a global install

**Comment by kamijoutouma** [comment]
@othiym23

**Comment by othiym23** [comment]
> that says -g after the url ... So it is not a local install

Thanks for clarifying, and sorry for missing that the first time around!

If it's not clear from the output, npm isn't the tool picking the SSH key there. It's git itself, so git is the one deciding which key to use. While it's moderately confusing that it's choosing root's key based on the effective user ID instead of the real user ID, this is a decision set by git, and I don't think it's a good idea for npm to try to guess at user intentions and override that value. For what it's worth, running npm as root to install git dependencies makes me a little nervous. The results can be unpredictable.

**Comment by kamijoutouma** [comment]
I agree and no problem ;p
