### ISSUE TITLE
Getting continuous errors while installing gulp or bower with npm

### ISSUE THREAD

**Issue by emfluenceindia** [npm/npm#10761]
I was getting errors while installing something with npm. I did a fresh node.js installation (4.2.3 LTS) from https://nodejs.org/en/. Created an empty folder and ran `npm install -g gulp bower`.
Still getting the errors! :(

Please see screenshot:
![npm-error](https://cloud.githubusercontent.com/assets/11072678/11685192/372c1a1e-9e9d-11e5-8bfb-d5ecc35e340a.png)

However, when I remove the global flag `-g` installation is successful. But I need them to be installed globally because don't want to install the same thing over and again for each project locally.

**Comment by othiym23** [comment]
What happens if you update npm to `npm@3.5.2`? You can do that with `npm -g install npm@next`. It has a fix that we're testing for precisely these kinds of issues.

**Comment by emfluenceindia** [comment]
`npm -g install npm@next` installed successfully. I went on to install npm locally with `npm install` which gave me the following:

```
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.5
```
I am on Windows 10 Pro.
Also after installing `npm` locally I tried to build my app with `gulp` which did not work for me and left me with the following:

```
D:\Projects\2015-Prov {git}                                                                                    
{lamb} gulp serve                                                                                              
module.js:339                                                                                                  
    throw err;                                                                                                 
    ^                                                                                                          
                                                                                                               
Error: Cannot find module 'vinyl'                                                                              
    at Function.Module._resolveFilename (module.js:337:15)                                                     
    at Function.Module._load (module.js:287:25)                                                                
    at Module.require (module.js:366:17)                                                                       
    at require (module.js:385:17)                                                                              
    at Object.<anonymous> (C:\Users\Subrata\AppData\Roaming\npm\node_modules\gulp\node_modules\gulp-util\index.
js:2:9)                                                                                                        
    at Module._compile (module.js:435:26)                                                                      
    at Object.Module._extensions..js (module.js:442:10)                                                        
    at Module.load (module.js:356:32)                                                                          
    at Function.Module._load (module.js:311:12)                                                                
    at Module.require (module.js:366:17)
```
Everything was working fine before I updated npm yesterday !!
How can I get out of this loop?! :(

**Comment by emfluenceindia** [comment]
Since `npm -g install npm@next` resolved the issue of getting error messages on installation I am closing this. Thank you for `othiym23` for taking time showing me the right path!
