### ISSUE TITLE
Getting Error while installing socket.io

### ISSUE THREAD

**Issue by dashimanshu** [npm/npm#10763]
```
> utf-8-validate@1.2.1 install C:\Test\nodejs\SQL\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\utf-8-validate
> node-gyp rebuild


C:\Test\nodejs\SQL\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\utf-8-validate>node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild 
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  validation.cc
C:\Users\hdas1\.node-gyp\0.10.35\deps\v8\include\v8.h(179): warning C4506: no definition for inline function 'v8::Persistent<T> v8::Persistent<T>::New(v8::Handle<T>)' [C:\Test\nodejs\SQL\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\utf-8-validate\build\validation.vcxproj]
          with
          [
              T=v8::Object
          ]
     Creating library C:\Test\nodejs\SQL\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\utf-8-validate\build\Release\validation.lib and object C:\Test\nodejs\SQL\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\utf-8-validate\build\Release\validation.exp
  Generating code
  Finished generating code
  validation.vcxproj -> C:\Test\nodejs\SQL\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\utf-8-validate\build\Release\\validation.node

> bufferutil@1.2.1 install C:\Test\nodejs\SQL\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\bufferutil
> node-gyp rebuild


C:\Test\nodejs\SQL\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\bufferutil>node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild 
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  bufferutil.cc
C:\Users\hdas1\.node-gyp\0.10.35\deps\v8\include\v8.h(179): warning C4506: no definition for inline function 'v8::Persistent<T> v8::Persistent<T>::New(v8::Handle<T>)' [C:\Test\nodejs\SQL\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\bufferutil\build\bufferutil.vcxproj]
          with
          [
              T=v8::Object
          ]
     Creating library C:\Test\nodejs\SQL\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\bufferutil\build\Release\bufferutil.lib and object C:\Test\nodejs\SQL\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\bufferutil\build\Release\bufferutil.exp
  Generating code
  Finished generating code
  bufferutil.vcxproj -> C:\Test\nodejs\SQL\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\bufferutil\build\Release\\bufferutil.node

npm WARN package.json sqltest@1.0.0 No repository field.
npm WARN package.json sqltest@1.0.0 No README data
npm ERR! fetch failed https://github.com/rase-/node-XMLHttpRequest/archive/a6b6f2.tar.gz
|

-

npm ERR! fetch failed https://github.com/rase-/node-XMLHttpRequest/archive/a6b6f2.tar.gz
npm ERR! fetch failed https://github.com/rase-/node-XMLHttpRequest/archive/a6b6f2.tar.gz
npm ERR! Error: 7724:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:openssl\ssl\s23_clnt.c:795:
npm ERR!
npm ERR!     at SlabBuffer.use (tls.js:235:18)
npm ERR!     at CleartextStream.read [as _read] (tls.js:455:29)
npm ERR!     at CleartextStream.Readable.read (_stream_readable.js:341:10)
npm ERR!     at EncryptedStream.write [as _write] (tls.js:369:25)
npm ERR!     at doWrite (_stream_writable.js:226:10)
npm ERR!     at writeOrBuffer (_stream_writable.js:216:5)
npm ERR!     at EncryptedStream.Writable.write (_stream_writable.js:183:11)
npm ERR!     at write (_stream_readable.js:602:24)
npm ERR!     at flow (_stream_readable.js:611:7)
npm ERR!     at Socket.pipeOnReadable (_stream_readable.js:643:5)
npm ERR!     at Socket.emit (events.js:92:17)
npm ERR!     at emitReadable_ (_stream_readable.js:427:10)
npm ERR!     at emitReadable (_stream_readable.js:423:5)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\
\npm-cli.js" "install"
npm ERR! cwd C:\Test\nodejs\SQL
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! not ok code 0
```

**Comment by othiym23** [comment]
From the output, it looks like you may be trying to build `socket.io` against a version of Node that it doesn't support. Also, `npm@1.4.28` is more or less unsupported at this point. If you update to newer versions of Node and npm, does this problem continue?
