### ISSUE TITLE
error network getaddrinfo ENOTFOUND registry.npmjs.org

### ISSUE THREAD

**Issue by lags** [npm/npm#10822]
I have cross compile node.js (v0.12.9) with npm (v2.14.9) for ARM cortex-A5 correctly in myboard.
If i run node.js example hello world work successfully.

But when i try install any package via npm the result is always:

```javascript
npm ERR! network getaddrinfo ENOTFOUND registry.npmjs.org
```

Follow complete debug info:

```javascript
root@myboard:/#
root@myboard:/# npm install -g forever -ddd
npm info it worked if it ends with ok
npm verb cli [ '/usr/bin/node',
npm verb cli   '/usr/bin/npm',
npm verb cli   'install',
npm verb cli   '-g',
npm verb cli   'forever',
npm verb cli   '-ddd' ]
npm info using npm@2.14.9
npm info using node@v0.12.9
npm verb install initial load of /usr/lib/package.json
npm verb readDependencies loading dependencies from /usr/lib/package.json
npm sill cache add args [ 'forever', null ]
npm verb cache add spec forever
npm sill cache add parsed spec { raw: 'forever',
npm sill cache add   scope: null,
npm sill cache add   name: 'forever',
npm sill cache add   rawSpec: '',
npm sill cache add   spec: '*',
npm sill cache add   type: 'range' }
npm sill addNamed forever@*
npm verb addNamed "*" is a valid semver range for forever
npm sill addNameRange { name: 'forever', range: '*', hasData: false }
npm sill mapToRegistry name forever
npm sill mapToRegistry using default registry
npm sill mapToRegistry registry https://registry.npmjs.org/
npm sill mapToRegistry uri https://registry.npmjs.org/forever
npm verb addNameRange registry:https://registry.npmjs.org/forever not in flight; fetching
npm verb request uri https://registry.npmjs.org/forever
npm verb request no auth needed
npm info attempt registry request try #1 at 11:21:00
npm verb request id fcb834af166e40d2
npm http request GET https://registry.npmjs.org/forever
npm info retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND registry.npmjs.org
npm info attempt registry request try #2 at 11:21:11
npm http request GET https://registry.npmjs.org/forever
npm info retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND registry.npmjs.org
npm info attempt registry request try #3 at 11:22:12
npm http request GET https://registry.npmjs.org/forever
npm verb stack Error: getaddrinfo ENOTFOUND registry.npmjs.org
npm verb stack     at errnoException (dns.js:44:10)
npm verb stack     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:94:26)
npm verb cwd /
npm ERR! Linux 3.18.23
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "forever" "-ddd"
npm ERR! node v0.12.9
npm ERR! npm  v2.14.9
npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR! syscall getaddrinfo

npm ERR! network getaddrinfo ENOTFOUND registry.npmjs.org
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
npm verb exit [ 1, true ]

npm ERR! Please include the following file with any support request:
npm ERR!     /npm-debug.log
root@myboard:/#
root@myboard:/#
root@myboard:/# ping registry.npmjs.org
PING registry.npmjs.org (185.31.17.162): 56 data bytes
64 bytes from 185.31.17.162: seq=0 ttl=56 time=65.096 ms
64 bytes from 185.31.17.162: seq=1 ttl=56 time=64.957 ms
64 bytes from 185.31.17.162: seq=2 ttl=56 time=64.337 ms
^C
--- registry.npmjs.org ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 64.337/64.796/65.096 ms
root@myboard:/#
root@myboard:/#
root@myboard:/# nslookup registry.npmjs.org
Server:    127.0.0.1
Address 1: 127.0.0.1 localhost

Name:      registry.npmjs.org
Address 1: 185.31.17.162
root@myboard:/#
root@myboard:/#
```

Many issue report that this problem is about proxy but i don't use any proxy because myboard is direct connect to router without firewall and without block for outgoing internet.

I can ping correctly registry.npmjs.org and nslookup is ok.
I have only one network interface with ipv4 and ipv6 stack. I think ipv6 can raise this error but if disabled ipv6 in this interface the error is same.

Only for test i have installed privoxy on my pc windows in same network and set npm config for use this and npm magically work correcly but all this only for test because in production use I can't use any proxy.

I understand why not work correctly node.js (v0.12.9) with npm (v2.14.9) instead if I compile node.js version (v0.10.41) and npm version (v1.4.29) all work correctly without proxy.

I appreciate any advice. Thank you in advance.

**Comment by lags** [comment]
Possible that there is no solution? is a month that we slam head :(

**Comment by lags** [comment]
I have edit manually file:
```
node_v0.12.9/lib/dns.js
```
at line 131 and add:
```
family = 4;
```
to force ipv4 lookup because in debug family is undefined. So i have new file:
```
....
  } else {
    family = options >>> 0;
  }
  family = 4;
  if (family !== 0 && family !== 4 && family !== 6)
    throw new TypeError('invalid argument: family must be 4 or 6');
....
```
and WOW work magically. NPM can install any package.

I ask how does 'family' to take the value?
In my case 'family' result undefined and i don't know why.

**Comment by lags** [comment]
Solved!
appy this found patch and work correctly
```
--- a/deps/uv/src/unix/getaddrinfo.c
+++ b/deps/uv/src/unix/getaddrinfo.c
@@ -99,6 +99,7 @@
   int err;
 
   req = container_of(w, uv_getaddrinfo_t, work_req);
+   req->hints->ai_flags &= ~AI_V4MAPPED;
   err = getaddrinfo(req->hostname, req->service, req->hints, &req->addrinfo);
   req->retcode = uv__getaddrinfo_translate_error(err);
 }
```
