### ISSUE TITLE
Windows environment still broken 

### ISSUE THREAD

**Issue by brunis** [npm/npm#10828]
Hi,

Been trying to set up grunt through npm in our CI and the lack of documentation and amount of problems just getting the basic commands to run is frustratingly hairpulling.

I can't run anything because the npm.cmd get's confused about where it is.. and tries to locate itself inside my project's node_modules and then fails.

```
Error: Cannot find module '<absolute path to my project here>\Web.Base\node_modules\npm\bin\npm-cli.js'
at Function.Module._resolveFilename (module.js:327:15)
at Function.Module._load (module.js:278:25)
at Function.Module.runMain (module.js:431:10)
at startup (node.js:141:18)
at node.js:977:3
module.js:329
throw err;
```

I'm talking about the bundled npm that comes with the latest nodejs windows installer (v5.2 x64 as of this writing), so that might be an old version and the source of all my problems.

I tried following the suggestions here:
https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows

But some of them just break npm entirely and the rest don't work.

Hoping you'll fix that global install to be global soon instead of user local.

Please advise.

**Comment by brunis** [comment]
Ok i seem to have found the issue.

I had an x86 installed first.. but after upgrading only the upgrading user get's his path "fixed" to the new installation folder.. everyone else is left with the old folder..

So i guess better cleanup in the uninstaller is warranted?
