### ISSUE TITLE
missing required argument in outdated

### ISSUE THREAD

**Issue by jnszkr** [npm/npm#10838]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'outdated',
1 verbose cli   '-g',
1 verbose cli   '--depth=0' ]
2 info using npm@3.3.12
3 info using node@v5.2.0
4 verbose stack Error: Missing required argument #1
4 verbose stack     at module.exports (/usr/local/lib/node_modules/npm/lib/install/mutate-into-logical-tree.js:12:3)
4 verbose stack     at /usr/local/lib/node_modules/npm/lib/outdated.js:78:5
4 verbose stack     at /usr/local/lib/node_modules/npm/lib/outdated.js:62:20
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:186:9
4 verbose stack     at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:17:25)
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:152:20
4 verbose stack     at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:17:25)
4 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:121:22)
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:81:20
4 verbose stack     at fs.js:1658:23
5 verbose cwd /Users/oszkar/projects/graphql-intro
6 error Darwin 15.2.0
7 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "outdated" "-g" "--depth=0"
8 error node v5.2.0
9 error npm  v3.3.12
10 error code EMISSINGARG
11 error typeerror Error: Missing required argument #1
11 error typeerror     at module.exports (/usr/local/lib/node_modules/npm/lib/install/mutate-into-logical-tree.js:12:3)
11 error typeerror     at /usr/local/lib/node_modules/npm/lib/outdated.js:78:5
11 error typeerror     at /usr/local/lib/node_modules/npm/lib/outdated.js:62:20
11 error typeerror     at /usr/local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:186:9
11 error typeerror     at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:17:25)
11 error typeerror     at /usr/local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:152:20
11 error typeerror     at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:17:25)
11 error typeerror     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:121:22)
11 error typeerror     at /usr/local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:81:20
11 error typeerror     at fs.js:1658:23
11 error typeerror This is an error with npm itself. Please report this error at:
11 error typeerror     <http://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

**Comment by jnszkr** [comment]
duplicate
