### ISSUE TITLE
Error: Missing required argument #2 - "error with NPM itself"

### ISSUE THREAD

**Issue by BillBensing** [npm/npm#10844]
Good Day All, 

I was trying to run an basic $ npm install command and this was the error message I recieved:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@3.3.6
3 info using node@v5.0.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly install normalizeTree
8 verbose stack Error: Missing required argument #2
8 verbose stack     at exports.findRequirement (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:475:3)
8 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:90:19
8 verbose stack     at zalgoSafe (C:\Program Files\nodejs\node_modules\npm\node_modules\dezalgo\dezalgo.js:20:10)
8 verbose stack     at finalize (C:\Program Files\nodejs\node_modules\npm\node_modules\realize-package-specifier\index.js:37:5)
8 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\realize-package-specifier\index.js:22:20
8 verbose stack     at FSReqWrap.oncomplete (fs.js:82:15)
9 verbose cwd -- REDACTED: My Current Working Directory --
10 error Windows_NT 6.1.7601
11 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
12 error node v5.0.0
13 error npm  v3.3.6
14 error code EMISSINGARG
15 error typeerror Error: Missing required argument #2
15 error typeerror     at exports.findRequirement (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:475:3)
15 error typeerror     at C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:90:19
15 error typeerror     at zalgoSafe (C:\Program Files\nodejs\node_modules\npm\node_modules\dezalgo\dezalgo.js:20:10)
15 error typeerror     at finalize (C:\Program Files\nodejs\node_modules\npm\node_modules\realize-package-specifier\index.js:37:5)
15 error typeerror     at C:\Program Files\nodejs\node_modules\npm\node_modules\realize-package-specifier\index.js:22:20
15 error typeerror     at FSReqWrap.oncomplete (fs.js:82:15)
15 error typeerror This is an error with npm itself. Please report this error at:
15 error typeerror     <http://github.com/npm/npm/issues>
16 verbose exit [ 1, true ]
```

**Comment by smikes** [comment]
This looks like an internal error from the `validate` call in npm 3.3.6

Can you try updating your version of `npm`?

To update npm on Windows, you can use this command-line tool from Microsoft: https://github.com/felixrieseberg/npm-windows-upgrade
or follow the manual instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as abandoned. This particular issue is almost certainly resolved in `npm@latest`, so give upgrading a shot.
