### ISSUE TITLE
"npm install -g cordova" fails

### ISSUE THREAD

**Issue by Systematicmind** [npm/npm#10842]
Hello everyone
I'm trying to install Cordova using npm version 2.14.7 but it failed every time i tried.
My node version is 4.2.3 and there is no proxy setting neither on my windows 7 nor npm. Here is the debug_log file. Please take a look and help me. Thank you in advance.

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'cordova' ]
2 info using npm@2.14.7
3 info using node@v4.2.3
4 verbose install initial load of C:\Users\Amir\AppData\Roaming\npm\package.json
5 verbose readDependencies loading dependencies from C:\Users\Amir\AppData\Roaming\npm\package.json
6 silly cache add args [ 'cordova', null ]
7 verbose cache add spec cordova
8 silly cache add parsed spec Result {
8 silly cache add   raw: 'cordova',
8 silly cache add   scope: null,
8 silly cache add   name: 'cordova',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: '*',
8 silly cache add   type: 'range' }
9 silly addNamed cordova@*
10 verbose addNamed "*" is a valid semver range for cordova
11 silly addNameRange { name: 'cordova', range: '*', hasData: false }
12 silly mapToRegistry name cordova
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/cordova
16 verbose addNameRange registry:https://registry.npmjs.org/cordova not in flight; fetching
17 verbose request uri https://registry.npmjs.org/cordova
18 verbose request no auth needed
19 info attempt registry request try #1 at 12:02:54 AM
20 verbose request id a9c965ba107edae0
21 http request GET https://registry.npmjs.org/cordova
22 info retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
23 info attempt registry request try #2 at 12:03:05 AM
24 http request GET https://registry.npmjs.org/cordova
25 info retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
26 info attempt registry request try #3 at 12:04:05 AM
27 http request GET https://registry.npmjs.org/cordova
28 verbose stack Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
28 verbose stack     at Object.exports._errnoException (util.js:874:11)
28 verbose stack     at errnoException (dns.js:31:15)
28 verbose stack     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)
29 verbose cwd C:\Users\Amir
30 error Windows_NT 6.1.7601
31 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova"
32 error node v4.2.3
33 error npm  v2.14.7
34 error code EAI_AGAIN
35 error errno EAI_AGAIN
36 error syscall getaddrinfo
37 error getaddrinfo EAI_AGAIN registry.npmjs.org:443
38 error If you need help, you may report this error at:
38 error     <https://github.com/npm/npm/issues>
39 verbose exit [ 1, true ]
```

**Comment by Systematicmind** [comment]
Finally i got my Cordova installed successfully. I didn't understand what was wrong with my network or NPM at all, but several interruption wasted my time.

**Comment by smikes** [comment]
Is this still a problem for you?  It looks like your network was having trouble with name resolution of registry.npmjs.org.

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by Systematicmind** [comment]
Thank you Sam for the reply. The network problem vanished. Close this issue whenever you want.

**Comment by othiym23** [comment]
Closing as resolved!
