### ISSUE TITLE
Need help!

### ISSUE THREAD

**Issue by sahacker** [npm/npm#10862]
# installed from packages
```
shell> npm view
npm ERR! FreeBSD 10.2-RELEASE
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "view"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4

npm ERR! Invalid package.json
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/home/admin/npm-debug.log
```
--------  /usr/home/admin/npm-debug.log  ----------
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'view' ]
2 info using npm@2.14.4
3 info using node@v4.1.1
4 verbose stack Error: Invalid package.json
4 verbose stack     at /usr/local/lib/node_modules/npm/lib/view.js:77:30
4 verbose stack     at ReadFileContext.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:79:21)
4 verbose stack     at ReadFileContext.callback (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:76:16)
4 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:303:13)
5 verbose cwd /usr/home/admin
6 error FreeBSD 10.2-RELEASE
7 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "view"
8 error node v4.1.1
9 error npm  v2.14.4
10 error Invalid package.json
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
```

**Comment by axd1997** [comment]
your package.josn file is wonky
Post it here if you can

**Comment by othiym23** [comment]
The primary purpose of `npm view` is to [view information about a package on the registry](https://docs.npmjs.com/cli/view), so it needs to know which package's information you want to view. Either the package name gets passed in on the command line, or it looks to the current package to find the name of the package to look up, which is why you're getting that error. While the error message could do a better job of indicating what's going wrong, npm's doing what it's supposed to here, and so I'm going to close this as resolved. I hope this helps!
