### ISSUE TITLE
Trying to `npm install -g` something that's already installed will ruin `npm` up

### ISSUE THREAD

**Issue by gsklee** [npm/npm#10874]
``` bash
$ npm install -g npm-check-update

# Output looks normal here

$ npm install -g npm-check-update

# Output looks weird

$ npm ls -g --depth=0

$ npm ls --depth=0 -g
/Users/kaylee/.nvm/versions/node/v5.2.0/lib
├── npm@3.3.12
└── npm-check-updates@2.5.4

npm ERR! missing: abbrev@~1.0.7, required by npm@3.5.2
npm ERR! missing: ansicolors@~0.3.2, required by npm@3.5.2
npm ERR! missing: ansistyles@~0.1.3, required by npm@3.5.2
npm ERR! missing: aproba@~1.0.1, required by npm@3.5.2
npm ERR! missing: archy@~1.0.0, required by npm@3.5.2
npm ERR! missing: async-some@~1.0.2, required by npm@3.5.2
npm ERR! missing: chownr@~1.0.1, required by npm@3.5.2
npm ERR! missing: cmd-shim@~2.0.1, required by npm@3.5.2
npm ERR! missing: columnify@~1.5.2, required by npm@3.5.2
npm ERR! missing: config-chain@~1.1.9, required by npm@3.5.2
npm ERR! missing: debuglog@*, required by npm@3.5.2
npm ERR! missing: dezalgo@~1.0.3, required by npm@3.5.2
npm ERR! missing: editor@~1.0.0, required by npm@3.5.2
npm ERR! missing: fs-vacuum@~1.2.7, required by npm@3.5.2
npm ERR! missing: fs-write-stream-atomic@~1.0.5, required by npm@3.5.2
npm ERR! missing: fstream@~1.0.8, required by npm@3.5.2
npm ERR! missing: fstream-npm@~1.0.7, required by npm@3.5.2
npm ERR! missing: glob@~5.0.15, required by npm@3.5.2
npm ERR! missing: has-unicode@~1.0.1, required by npm@3.5.2
npm ERR! missing: hosted-git-info@~2.1.4, required by npm@3.5.2
npm ERR! missing: iferr@~0.1.5, required by npm@3.5.2
npm ERR! missing: inflight@~1.0.4, required by npm@3.5.2
npm ERR! missing: init-package-json@~1.9.1, required by npm@3.5.2
npm ERR! missing: lockfile@~1.0.1, required by npm@3.5.2
npm ERR! missing: lodash._baseindexof@*, required by npm@3.5.2
npm ERR! missing: lodash._baseuniq@*, required by npm@3.5.2
npm ERR! missing: lodash._bindcallback@*, required by npm@3.5.2
npm ERR! missing: lodash._cacheindexof@*, required by npm@3.5.2
npm ERR! missing: lodash._createcache@*, required by npm@3.5.2
npm ERR! missing: lodash._getnative@*, required by npm@3.5.2
npm ERR! missing: lodash.clonedeep@~3.0.2, required by npm@3.5.2
npm ERR! missing: lodash.isarguments@*, required by npm@3.5.2
npm ERR! missing: lodash.isarray@*, required by npm@3.5.2
npm ERR! missing: lodash.keys@*, required by npm@3.5.2
npm ERR! missing: lodash.restparam@*, required by npm@3.5.2
npm ERR! missing: lodash.union@~3.1.0, required by npm@3.5.2
npm ERR! missing: lodash.uniq@~3.2.2, required by npm@3.5.2
npm ERR! missing: lodash.without@~3.2.1, required by npm@3.5.2
npm ERR! missing: node-gyp@~3.2.1, required by npm@3.5.2
npm ERR! missing: nopt@~3.0.4, required by npm@3.5.2
npm ERR! missing: normalize-git-url@~3.0.1, required by npm@3.5.2
npm ERR! missing: normalize-package-data@~2.3.5, required by npm@3.5.2
npm ERR! missing: npm-cache-filename@~1.0.2, required by npm@3.5.2
npm ERR! missing: npm-install-checks@~2.0.1, required by npm@3.5.2
npm ERR! missing: npm-package-arg@~4.1.0, required by npm@3.5.2
npm ERR! missing: npm-registry-client@~7.0.9, required by npm@3.5.2
npm ERR! missing: npm-user-validate@~0.1.2, required by npm@3.5.2
npm ERR! missing: npmlog@~2.0.0, required by npm@3.5.2
npm ERR! missing: opener@~1.4.1, required by npm@3.5.2
npm ERR! missing: path-is-inside@~1.0.1, required by npm@3.5.2
npm ERR! missing: read@~1.0.7, required by npm@3.5.2
npm ERR! missing: read-cmd-shim@~1.0.1, required by npm@3.5.2
npm ERR! missing: read-installed@~4.0.3, required by npm@3.5.2
npm ERR! missing: read-package-json@~2.0.2, required by npm@3.5.2
npm ERR! missing: read-package-tree@~5.1.2, required by npm@3.5.2
npm ERR! missing: readdir-scoped-modules@*, required by npm@3.5.2
npm ERR! missing: realize-package-specifier@~3.0.1, required by npm@3.5.2
npm ERR! missing: request@*, required by npm@3.5.2
npm ERR! missing: retry@~0.8.0, required by npm@3.5.2
npm ERR! missing: rimraf@~2.4.3, required by npm@3.5.2
npm ERR! missing: semver@~5.0.3, required by npm@3.5.2
npm ERR! missing: sha@~2.0.1, required by npm@3.5.2
npm ERR! missing: sorted-object@~1.0.0, required by npm@3.5.2
npm ERR! missing: tar@~2.2.1, required by npm@3.5.2
npm ERR! missing: text-table@~0.2.0, required by npm@3.5.2
npm ERR! missing: uid-number@0.0.6, required by npm@3.5.2
npm ERR! missing: umask@~1.1.0, required by npm@3.5.2
npm ERR! missing: unique-filename@~1.1.0, required by npm@3.5.2
npm ERR! missing: unpipe@~1.0.0, required by npm@3.5.2
npm ERR! missing: validate-npm-package-license@*, required by npm@3.5.2
npm ERR! missing: validate-npm-package-name@~2.2.2, required by npm@3.5.2
npm ERR! missing: which@~1.2.0, required by npm@3.5.2
npm ERR! missing: abbrev@~1.0.7, required by npm@2.14.15
npm ERR! missing: ansi@~0.3.0, required by npm@2.14.15
npm ERR! missing: ansicolors@~0.3.2, required by npm@2.14.15
npm ERR! missing: ansistyles@~0.1.3, required by npm@2.14.15
npm ERR! missing: archy@~1.0.0, required by npm@2.14.15
npm ERR! missing: async-some@~1.0.2, required by npm@2.14.15
npm ERR! missing: block-stream@0.0.8, required by npm@2.14.15
npm ERR! missing: char-spinner@~1.0.1, required by npm@2.14.15
npm ERR! missing: chmodr@~1.0.2, required by npm@2.14.15
npm ERR! missing: chownr@~1.0.1, required by npm@2.14.15
npm ERR! missing: cmd-shim@~2.0.1, required by npm@2.14.15
npm ERR! missing: columnify@~1.5.2, required by npm@2.14.15
npm ERR! missing: config-chain@~1.1.9, required by npm@2.14.15
npm ERR! missing: dezalgo@~1.0.3, required by npm@2.14.15
npm ERR! missing: editor@~1.0.0, required by npm@2.14.15
npm ERR! missing: fs-vacuum@~1.2.7, required by npm@2.14.15
npm ERR! missing: fs-write-stream-atomic@~1.0.5, required by npm@2.14.15
npm ERR! missing: fstream@~1.0.8, required by npm@2.14.15
npm ERR! missing: fstream-npm@~1.0.7, required by npm@2.14.15
npm ERR! missing: github-url-from-git@~1.4.0, required by npm@2.14.15
npm ERR! missing: github-url-from-username-repo@~1.0.2, required by npm@2.14.15
npm ERR! missing: glob@~5.0.15, required by npm@2.14.15
npm ERR! missing: hosted-git-info@~2.1.4, required by npm@2.14.15
npm ERR! missing: inflight@~1.0.4, required by npm@2.14.15
npm ERR! missing: init-package-json@~1.9.1, required by npm@2.14.15
npm ERR! missing: lockfile@~1.0.1, required by npm@2.14.15
npm ERR! missing: lru-cache@~3.2.0, required by npm@2.14.15
npm ERR! missing: minimatch@~3.0.0, required by npm@2.14.15
npm ERR! missing: node-gyp@~3.2.1, required by npm@2.14.15
npm ERR! missing: nopt@~3.0.6, required by npm@2.14.15
npm ERR! missing: normalize-git-url@~3.0.1, required by npm@2.14.15
npm ERR! missing: normalize-package-data@~2.3.5, required by npm@2.14.15
npm ERR! missing: npm-cache-filename@~1.0.2, required by npm@2.14.15
npm ERR! missing: npm-install-checks@~1.0.6, required by npm@2.14.15
npm ERR! missing: npm-package-arg@~4.1.0, required by npm@2.14.15
npm ERR! missing: npm-registry-client@~7.0.9, required by npm@2.14.15
npm ERR! missing: npm-user-validate@~0.1.2, required by npm@2.14.15
npm ERR! missing: npmlog@~2.0.0, required by npm@2.14.15
npm ERR! missing: opener@~1.4.1, required by npm@2.14.15
npm ERR! missing: path-is-inside@~1.0.0, required by npm@2.14.15
npm ERR! missing: read@~1.0.7, required by npm@2.14.15
npm ERR! missing: read-installed@~4.0.3, required by npm@2.14.15
npm ERR! missing: read-package-json@~2.0.2, required by npm@2.14.15
npm ERR! missing: readable-stream@~1.1.13, required by npm@2.14.15
npm ERR! missing: realize-package-specifier@~3.0.1, required by npm@2.14.15
npm ERR! missing: request@~2.67.0, required by npm@2.14.15
npm ERR! missing: retry@~0.8.0, required by npm@2.14.15
npm ERR! missing: rimraf@~2.4.4, required by npm@2.14.15
npm ERR! missing: semver@~5.1.0, required by npm@2.14.15
npm ERR! missing: sha@~2.0.1, required by npm@2.14.15
npm ERR! missing: sorted-object@~1.0.0, required by npm@2.14.15
npm ERR! missing: spdx-license-ids@*, required by npm@2.14.15
npm ERR! missing: tar@~2.2.1, required by npm@2.14.15
npm ERR! missing: text-table@~0.2.0, required by npm@2.14.15
npm ERR! missing: uid-number@0.0.6, required by npm@2.14.15
npm ERR! missing: umask@~1.1.0, required by npm@2.14.15
npm ERR! missing: validate-npm-package-license@~3.0.1, required by npm@2.14.15
npm ERR! missing: validate-npm-package-name@~2.2.2, required by npm@2.14.15
npm ERR! missing: which@~1.2.0, required by npm@2.14.15
```

This bug exists in both 5.2.0 and 5.3.0, maybe even in earlier versions.

**Comment by mroien** [comment]
I have the same issue on a Jenkins slave machine, however it works fine on my rMBP. I can't run the `ncu` command in slave machine. And then I run an `npm install` via Jenkins I get
```
> bufferutil@1.1.0 install /Users/admin/jenkins/workspace/mg2-desktop/node_modules/appium/node_modules/bufferutil
> node-gyp rebuild

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
In file included from ../src/bufferutil.cc:16:
../../nan/nan.h:261:25: error: redefinition of '_NanEnsureLocal'
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                        ^
../../nan/nan.h:256:25: note: previous definition is here
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                        ^
../../nan/nan.h:661:13: error: no member named 'smalloc' in namespace 'node'
    , node::smalloc::FreeCallback callback
      ~~~~~~^
../../nan/nan.h:672:12: error: no matching function for call to 'New'
    return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
           ^~~~~~~~~~~~~~~~~
/Users/admin/.node-gyp/5.3.0/include/node/node_buffer.h:31:40: note: candidate function not viable: no known conversion from 'uint32_t' (aka 'unsigned int') to 'enum encoding' for 3rd argument
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/admin/.node-gyp/5.3.0/include/node/node_buffer.h:43:40: note: candidate function not viable: 2nd argument ('const char *') would lose const qualifier
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/admin/.node-gyp/5.3.0/include/node/node_buffer.h:28:40: note: candidate function not viable: requires 2 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
                                       ^
/Users/admin/.node-gyp/5.3.0/include/node/node_buffer.h:36:40: note: candidate function not viable: requires 5 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
In file included from ../src/bufferutil.cc:16:
../../nan/nan.h:676:12: error: no viable conversion from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object>'
    return node::Buffer::New(v8::Isolate::GetCurrent(), size);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/admin/.node-gyp/5.3.0/include/node/v8.h:210:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'v8::MaybeLocal<v8::Object>' to 'const v8::Local<v8::Object> &' for 1st argument
class Local {
      ^
/Users/admin/.node-gyp/5.3.0/include/node/v8.h:210:7: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object> &&' for 1st argument
class Local {
      ^
/Users/admin/.node-gyp/5.3.0/include/node/v8.h:214:13: note: candidate template ignored: could not match 'Local' against 'MaybeLocal'
  V8_INLINE Local(Local<S> that)
            ^
/Users/admin/.node-gyp/5.3.0/include/node/v8.h:326:13: note: candidate template ignored: could not match 'S *' against 'v8::MaybeLocal<v8::Object>'
  V8_INLINE Local(S* that)
            ^
In file included from ../src/bufferutil.cc:16:
../../nan/nan.h:683:26: error: no member named 'Use' in namespace 'node::Buffer'
    return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
           ~~~~~~~~~~~~~~^
In file included from ../src/bufferutil.cc:7:
/Users/admin/.node-gyp/5.3.0/include/node/v8.h:221:5: error: assigning to 'v8::Primitive *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/admin/.node-gyp/5.3.0/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../../nan/nan.h:414:12: note: in instantiation of function template specialization 'v8::Local<v8::Primitive>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(v8::Undefined(v8::Isolate::GetCurrent())));
           ^
../../nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../src/bufferutil.cc:7:
/Users/admin/.node-gyp/5.3.0/include/node/v8.h:221:5: error: assigning to 'v8::Boolean *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/admin/.node-gyp/5.3.0/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../../nan/nan.h:424:12: note: in instantiation of function template specialization 'v8::Local<v8::Boolean>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(v8::True(v8::Isolate::GetCurrent())));
           ^
../../nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../src/bufferutil.cc:7:
/Users/admin/.node-gyp/5.3.0/include/node/v8.h:221:5: error: assigning to 'v8::Function *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/admin/.node-gyp/5.3.0/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../../nan/nan.h:1514:12: note: in instantiation of function template specialization 'v8::Local<v8::Function>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(handle)->Get(kCallbackIndex)
           ^
../../nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../src/bufferutil.cc:7:
/Users/admin/.node-gyp/5.3.0/include/node/v8.h:221:5: error: assigning to 'v8::Object *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/admin/.node-gyp/5.3.0/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../../nan/nan.h:1632:12: note: in instantiation of function template specialization 'v8::Local<v8::Object>::Local<v8::Value>' requested here
    return NanEscapeScope(handle->Get(NanNew(key)).As<v8::Object>());
           ^
../../nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
9 errors generated.
make: *** [Release/obj.target/bufferutil/src/bufferutil.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.2.0
gyp ERR! command "/usr/local/Cellar/node/5.3.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/admin/jenkins/workspace/mg2-desktop/node_modules/appium/node_modules/bufferutil
gyp ERR! node -v v5.3.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN install:bufferutil@1.1.0 bufferutil@1.1.0 install: `node-gyp rebuild`
npm WARN install:bufferutil@1.1.0 Exit status 1

> utf-8-validate@1.1.0 install /Users/admin/jenkins/workspace/mg2-desktop/node_modules/appium/node_modules/utf-8-validate
> node-gyp rebuild

  CXX(target) Release/obj.target/validation/src/validation.o
In file included from ../src/validation.cc:15:
../../nan/nan.h:261:25: error: redefinition of '_NanEnsureLocal'
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                        ^
../../nan/nan.h:256:25: note: previous definition is here
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                        ^
../../nan/nan.h:661:13: error: no member named 'smalloc' in namespace 'node'
    , node::smalloc::FreeCallback callback
      ~~~~~~^
../../nan/nan.h:672:12: error: no matching function for call to 'New'
    return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
           ^~~~~~~~~~~~~~~~~
/Users/admin/.node-gyp/5.3.0/include/node/node_buffer.h:31:40: note: candidate function not viable: no known conversion from 'uint32_t' (aka 'unsigned int') to 'enum encoding' for 3rd argument
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/admin/.node-gyp/5.3.0/include/node/node_buffer.h:43:40: note: candidate function not viable: 2nd argument ('const char *') would lose const qualifier
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/admin/.node-gyp/5.3.0/include/node/node_buffer.h:28:40: note: candidate function not viable: requires 2 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
                                       ^
/Users/admin/.node-gyp/5.3.0/include/node/node_buffer.h:36:40: note: candidate function not viable: requires 5 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
In file included from ../src/validation.cc:15:
../../nan/nan.h:676:12: error: no viable conversion from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object>'
    return node::Buffer::New(v8::Isolate::GetCurrent(), size);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/admin/.node-gyp/5.3.0/include/node/v8.h:210:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'v8::MaybeLocal<v8::Object>' to 'const v8::Local<v8::Object> &' for 1st argument
class Local {
      ^
/Users/admin/.node-gyp/5.3.0/include/node/v8.h:210:7: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object> &&' for 1st argument
class Local {
      ^
/Users/admin/.node-gyp/5.3.0/include/node/v8.h:214:13: note: candidate template ignored: could not match 'Local' against 'MaybeLocal'
  V8_INLINE Local(Local<S> that)
            ^
/Users/admin/.node-gyp/5.3.0/include/node/v8.h:326:13: note: candidate template ignored: could not match 'S *' against 'v8::MaybeLocal<v8::Object>'
  V8_INLINE Local(S* that)
            ^
In file included from ../src/validation.cc:15:
../../nan/nan.h:683:26: error: no member named 'Use' in namespace 'node::Buffer'
    return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
           ~~~~~~~~~~~~~~^
In file included from ../src/validation.cc:7:
/Users/admin/.node-gyp/5.3.0/include/node/v8.h:221:5: error: assigning to 'v8::Primitive *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/admin/.node-gyp/5.3.0/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../../nan/nan.h:414:12: note: in instantiation of function template specialization 'v8::Local<v8::Primitive>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(v8::Undefined(v8::Isolate::GetCurrent())));
           ^
../../nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../src/validation.cc:7:
/Users/admin/.node-gyp/5.3.0/include/node/v8.h:221:5: error: assigning to 'v8::Boolean *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/admin/.node-gyp/5.3.0/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../../nan/nan.h:424:12: note: in instantiation of function template specialization 'v8::Local<v8::Boolean>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(v8::True(v8::Isolate::GetCurrent())));
           ^
../../nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../src/validation.cc:7:
/Users/admin/.node-gyp/5.3.0/include/node/v8.h:221:5: error: assigning to 'v8::Function *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/admin/.node-gyp/5.3.0/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../../nan/nan.h:1514:12: note: in instantiation of function template specialization 'v8::Local<v8::Function>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(handle)->Get(kCallbackIndex)
           ^
../../nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../src/validation.cc:7:
/Users/admin/.node-gyp/5.3.0/include/node/v8.h:221:5: error: assigning to 'v8::Object *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/admin/.node-gyp/5.3.0/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../../nan/nan.h:1632:12: note: in instantiation of function template specialization 'v8::Local<v8::Object>::Local<v8::Value>' requested here
    return NanEscapeScope(handle->Get(NanNew(key)).As<v8::Object>());
           ^
../../nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
9 errors generated.
make: *** [Release/obj.target/validation/src/validation.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.2.0
gyp ERR! command "/usr/local/Cellar/node/5.3.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/admin/jenkins/workspace/mg2-desktop/node_modules/appium/node_modules/utf-8-validate
gyp ERR! node -v v5.3.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN install:utf-8-validate@1.1.0 utf-8-validate@1.1.0 install: `node-gyp rebuild`
npm WARN install:utf-8-validate@1.1.0 Exit status 1
npm WARN EPACKAGEJSON qa_mobile@1.0.0 No description
npm WARN EPACKAGEJSON qa_mobile@1.0.0 No repository field.
+ selenium-standalone start
[mg2-desktop] $ /bin/sh -xe /var/folders/y2/hh5vlr0n74j77c3p6z4_ygsr0000gn/T/hudson7018419606381223993.sh
+ mocha tests/web/login_test.js --reporter mocha-jenkins-reporter
```

**Comment by mroien** [comment]
Even if I try to install a missing npm package globally it still registers as gone after I run `npm -g list`

**Comment by gsklee** [comment]
I can confirm now this only happens when trying to repeatedly install `npm-check-updates`.

**Comment by mroien** [comment]
Oh no! So you can't use repeatedly? Or only if you install it globally repeatedly? How did you fix the missing modules? I've uninstalled and reinstalled node but didn't work.

**Comment by ahcode0919** [comment]
I also ran into these issues using Appium? Uninstalling / Reinstalling node has not helped

**Comment by denisazevedo** [comment]
Any other having this issue? It's happening even after upgrading node to 7.x

**Comment by legodude17** [comment]
What version of `npm` are you all using?
