### ISSUE TITLE
Error: Missing required argument #3

### ISSUE THREAD

**Issue by isiahmeadows** [npm/npm#10871]
**Edit: clean up bug explanation.**

## Summary

When attempting `npm uninstall --save` or `npm uninstall --save-dev` a package that isn't installed, npm throws an error.

## Requirements

- Works with or without Internet access
- Works in a fresh, empty directory (no package.json or node_modules)
- Works in a directory with cluttered package.json + node_modules and module listed as a dependency.

## Operating System

Ubuntu GNOME 15.10 64-bit

## Repro steps

From any directory, run either of these commands (aliases, of course, work):

- `npm uninstall --save-dev <module name>`
- `npm uninstall --save <module name>`

## Other notes

`npm uninstall` works as expected without the flag.

## npm-debug.log

I ran `npm r --save-dev lodash` in a fresh, clean directory (and used the `r` alias for `uninstall`).

```
0 info it worked if it ends with ok
1 verbose cli [ '/home/isiah/.nvm/versions/node/v4.2.2/bin/node',
1 verbose cli   '/home/isiah/.npm-global/bin/npm',
1 verbose cli   'r',
1 verbose cli   '--save-dev',
1 verbose cli   'lodash' ]
2 info using npm@3.4.1
3 info using node@v4.2.2
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly install normalizeTree
8 silly loadCurrentTree Finishing
9 silly loadIdealTree Starting
10 silly install loadIdealTree
11 silly cloneCurrentTree Starting
12 silly install cloneCurrentTreeToIdealTree
13 silly cloneCurrentTree Finishing
14 silly loadShrinkwrap Starting
15 silly install loadShrinkwrap
16 silly loadShrinkwrap Finishing
17 silly loadAllDepsIntoIdealTree Starting
18 silly uninstall loadAllDepsIntoIdealtree
19 verbose stack Error: Missing required argument #3
19 verbose stack     at replaceModule (/home/isiah/.npm-global/lib/node_modules/npm/lib/install/deps.js:426:3)
19 verbose stack     at /home/isiah/.npm-global/lib/node_modules/npm/lib/install/deps.js:235:7
19 verbose stack     at Array.forEach (native)
19 verbose stack     at exports.removeDeps (/home/isiah/.npm-global/lib/node_modules/npm/lib/install/deps.js:231:8)
19 verbose stack     at Array.<anonymous> (/home/isiah/.npm-global/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
19 verbose stack     at LOOP (/home/isiah/.npm-global/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
19 verbose stack     at chain (/home/isiah/.npm-global/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
19 verbose stack     at Uninstaller.loadAllDepsIntoIdealTree (/home/isiah/.npm-global/lib/node_modules/npm/lib/uninstall.js:72:3)
19 verbose stack     at Array.<anonymous> (/home/isiah/.npm-global/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
19 verbose stack     at LOOP (/home/isiah/.npm-global/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
20 verbose cwd /home/isiah/dev-projects/js/package
21 error Linux 4.2.0-19-generic
22 error argv "/home/isiah/.nvm/versions/node/v4.2.2/bin/node" "/home/isiah/.npm-global/bin/npm" "r" "--save-dev" "lodash"
23 error node v4.2.2
24 error npm  v3.4.1
25 error code EMISSINGARG
26 error typeerror Error: Missing required argument #3
26 error typeerror     at replaceModule (/home/isiah/.npm-global/lib/node_modules/npm/lib/install/deps.js:426:3)
26 error typeerror     at /home/isiah/.npm-global/lib/node_modules/npm/lib/install/deps.js:235:7
26 error typeerror     at Array.forEach (native)
26 error typeerror     at exports.removeDeps (/home/isiah/.npm-global/lib/node_modules/npm/lib/install/deps.js:231:8)
26 error typeerror     at Array.<anonymous> (/home/isiah/.npm-global/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
26 error typeerror     at LOOP (/home/isiah/.npm-global/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
26 error typeerror     at chain (/home/isiah/.npm-global/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
26 error typeerror     at Uninstaller.loadAllDepsIntoIdealTree (/home/isiah/.npm-global/lib/node_modules/npm/lib/uninstall.js:72:3)
26 error typeerror     at Array.<anonymous> (/home/isiah/.npm-global/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
26 error typeerror     at LOOP (/home/isiah/.npm-global/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
26 error typeerror This is an error with npm itself. Please report this error at:
26 error typeerror     <http://github.com/npm/npm/issues>
27 verbose exit [ 1, true ]
```

**Comment by isiahmeadows** [comment]
The only thing changed from default in my .npmrc is the prefix, which is manually set to `/home/isiah/.npm-global` so I don't have to run the command as root.

**Comment by tsabolov** [comment]
I've got the same error when trying to remove package that was not currently installed. I used command `npm rm -D babel`.

**Comment by isiahmeadows** [comment]
@tsabolov That's the exact bug.

**Comment by kofronpi** [comment]
Same bug here with npm 5.3.0 @ Ubuntu 14.04

**Comment by isiahmeadows** [comment]
@kofronpi That's your Node version. Try `npm -v`

**Comment by DDroll** [comment]
+1, npm 3.3.12

**Comment by luizbills** [comment]
+1 npm v3.5.3 Ubuntu 14

**Comment by szubtsovskiy** [comment]
+1 npm v3.6.0, OS X El Capitan

**Comment by dilev01** [comment]
+1 npm  v3.5.2 Windows 10

**Comment by isiahmeadows** [comment]
Ping @npm? I'm still reproducing this consistently, independent of packages. I think it's probably caused by an unsafe assumption about the state of the file system.

**Comment by othiym23** [comment]
@isiahmeadows I've flagged this as a bug, but in `npm@3.8.6` this is what I get:

```
bauchelain% npm init -y
# ...

bauchelain% npm i -S gauges
test-uninstall-save-fiasco@1.0.0 /Users/ogd/Documents/projects/test-uninstall-save-fiasco
└── gauges@1.0.1

npm WARN test-uninstall-save-fiasco@1.0.0 No description
npm WARN test-uninstall-save-fiasco@1.0.0 No repository field.

bauchelain% npm uninstall --save gauges
- gauges@1.0.1 node_modules/gauges
npm WARN test-uninstall-save-fiasco@1.0.0 No description
npm WARN test-uninstall-save-fiasco@1.0.0 No repository field.

bauchelain% npm uninstall --save gauges
npm WARN test-uninstall-save-fiasco@1.0.0 No description
npm WARN test-uninstall-save-fiasco@1.0.0 No repository field.

bauchelain% rm package.json
bauchelain% npm uninstall --save gauges
npm WARN saveError ENOENT: no such file or directory, open '/Users/ogd/Documents/projects/test-uninstall-save-fiasco/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/ogd/Documents/projects/test-uninstall-save-fiasco/package.json'
npm WARN test-uninstall-save-fiasco No description
npm WARN test-uninstall-save-fiasco No repository field.
npm WARN test-uninstall-save-fiasco No README data
npm WARN test-uninstall-save-fiasco No license field.
```

That output seems pretty reasonable to me, no?

**Comment by isiahmeadows** [comment]
Well...it appears fixed to me as well...I apparently didn't notice when it got fixed (which is a good thing IMHO). I'm going to close it now.
