### ISSUE TITLE
Path problems on Windows in msysgit

### ISSUE THREAD

**Issue by vcernomschi** [npm/npm#10880]
When attempting to use the global module under msysgit in Windows, I receive the following error:

```
module.js:339
    throw err;
    ^
Error: Cannot find module 'isparta'
     at Function.Module._resolveFilename (module.js:337:15)
     at Function.Module._load (module.js:287:25)
     at Module.require (module.js:366:17)
     at require (module.js:385:17)
     at Object.<anonymous> (c:\wamp\www\test.js:15:16)
     at Module._compile (module.js:435:26)
     at Object.Module._extensions..js (module.js:442:10)
     at Module.load (module.js:356:32)
     at Function.Module._load (module.js:311:12)
     at Function.Module.runMain (module.js:467:10)
```

I use node v4.2.2 with npm 2.14.7.

I have installed successfully isparta:
isparta from msysgit terminal:

```
$ which isparta
/c/ProgramData/npm/isparta
```

isparta from windows cmd:

```
$ where isparta
c:\ProgramData\npm\isparta
c:\ProgramData\npm\isparta.cmd
```

**Comment by eistrati** [comment]
This issue is reproduced on my laptop as well.

**Comment by mgoria** [comment]
Any updates on this issue? I'm dealing with it as well.
