### ISSUE TITLE
EMISSINGARG in 3.5.3

### ISSUE THREAD

**Issue by aredridel** [npm/npm#10907]
```
npm ERR! Linux 2.6.18-398.el5.028stab116.1
npm ERR! argv "/home/users/aredridel/Library/node/lib/node_modules/node-bin/bin/node" "/home/users/aredridel/Library/node/bin/npm" "rm" "node-bin"
npm ERR! node v5.1.0
npm ERR! npm  v3.5.3
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #3
npm ERR! typeerror     at replaceModule (/home/users/aredridel/Library/node/lib/node_modules/npm/lib/install/deps.js:438:3)
npm ERR! typeerror     at /home/users/aredridel/Library/node/lib/node_modules/npm/lib/install/deps.js:234:7
npm ERR! typeerror     at Array.forEach (native)
npm ERR! typeerror     at exports.removeDeps (/home/users/aredridel/Library/node/lib/node_modules/npm/lib/install/deps.js:230:8)
npm ERR! typeerror     at Array.<anonymous> (/home/users/aredridel/Library/node/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
npm ERR! typeerror     at LOOP (/home/users/aredridel/Library/node/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
npm ERR! typeerror     at chain (/home/users/aredridel/Library/node/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
npm ERR! typeerror     at Uninstaller.loadAllDepsIntoIdealTree (/home/users/aredridel/Library/node/lib/node_modules/npm/lib/uninstall.js:72:3)
npm ERR! typeerror     at Array.<anonymous> (/home/users/aredridel/Library/node/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
npm ERR! typeerror     at LOOP (/home/users/aredridel/Library/node/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/users/aredridel/Projects/scuttlebot/npm-debug.log
```

**Comment by aredridel** [comment]
https://gist.github.com/aredridel/936634400599cd633d5d

**Comment by boneskull** [comment]
Same deal:

```
boneskull@lectroid in ~/projects/boneskull/mocha on master
$ npm remove --save-dev babel-core
npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/Cellar/node/5.5.0/bin/node" "/usr/local/bin/npm" "remove" "--save-dev" "babel-core"
npm ERR! node v5.5.0
npm ERR! npm  v3.5.3
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #3
npm ERR! typeerror     at replaceModule (/usr/local/lib/node_modules/npm/lib/install/deps.js:438:3)
npm ERR! typeerror     at /usr/local/lib/node_modules/npm/lib/install/deps.js:234:7
npm ERR! typeerror     at Array.forEach (native)
npm ERR! typeerror     at exports.removeDeps (/usr/local/lib/node_modules/npm/lib/install/deps.js:230:8)
npm ERR! typeerror     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
npm ERR! typeerror     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
npm ERR! typeerror     at chain (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
npm ERR! typeerror     at Uninstaller.loadAllDepsIntoIdealTree (/usr/local/lib/node_modules/npm/lib/uninstall.js:72:3)
npm ERR! typeerror     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
npm ERR! typeerror     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Volumes/alien/projects/boneskull/mocha/npm-debug.log
```

**Comment by ElliottRoche** [comment]
Same here.

[debug log gist here](https://gist.github.com/ElliottRoche/ce61962f483fcd8eb572)

***

npm remove open --save
npm ERR! Darwin 15.3.0
npm ERR! argv "node" "/Users/elliott/.nvm/versions/node/v0.12.2/bin/npm" "remove" "open" "--save"
npm ERR! node v0.12.2
npm ERR! npm  v3.6.0
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #3
npm ERR! typeerror     at replaceModule (/Users/elliott/.nvm/versions/node/v0.12.2/lib/node_modules/npm/lib/install/deps.js:438:3)
npm ERR! typeerror     at /Users/elliott/.nvm/versions/node/v0.12.2/lib/node_modules/npm/lib/install/deps.js:234:7
npm ERR! typeerror     at Array.forEach (native)
npm ERR! typeerror     at exports.removeDeps (/Users/elliott/.nvm/versions/node/v0.12.2/lib/node_modules/npm/lib/install/deps.js:230:8)
npm ERR! typeerror     at Array.<anonymous> (/Users/elliott/.nvm/versions/node/v0.12.2/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
npm ERR! typeerror     at LOOP (/Users/elliott/.nvm/versions/node/v0.12.2/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
npm ERR! typeerror     at chain (/Users/elliott/.nvm/versions/node/v0.12.2/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
npm ERR! typeerror     at Uninstaller.loadAllDepsIntoIdealTree (/Users/elliott/.nvm/versions/node/v0.12.2/lib/node_modules/npm/lib/uninstall.js:72:3)
npm ERR! typeerror     at Array.<anonymous> (/Users/elliott/.nvm/versions/node/v0.12.2/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
npm ERR! typeerror     at LOOP (/Users/elliott/.nvm/versions/node/v0.12.2/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

**Comment by busches** [comment]
Is this still occurring in the latest npm?
