### ISSUE TITLE
EMISSINGARG errors after upating npm from 2.10.1 to 3.5.2

### ISSUE THREAD

**Issue by brianzelip** [npm/npm#10902]
I'm reporting two similar errors that I now get after updating npm from 2.10.1 to 3.5.2.

npm was updated by running `npm update -g`

I'm running node v0.12.4 on OSX 10.10.5, installed via homebrew
#### Two error messages

1 Here is the error I now get from running `npm outdated -g --depth=0`:

``` bash
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "outdated" "-g" "--depth=0"
npm ERR! node v0.12.4
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at module.exports (/usr/local/lib/node_modules/npm/lib/install/mutate-into-logical-tree.js:12:3)
npm ERR! typeerror     at /usr/local/lib/node_modules/npm/lib/outdated.js:78:5
npm ERR! typeerror     at /usr/local/lib/node_modules/npm/lib/outdated.js:62:20
npm ERR! typeerror     at /usr/local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:186:9
npm ERR! typeerror     at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:17:25)
npm ERR! typeerror     at /usr/local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:152:20
npm ERR! typeerror     at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:17:25)
npm ERR! typeerror     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:121:22)
npm ERR! typeerror     at /usr/local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:81:20
npm ERR! typeerror     at fs.js:1518:23
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/brianzelip/npm-debug.log
```

2 Here's the error message I now get from running `npm update -g`:

``` bash
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "update" "-g"
npm ERR! node v0.12.4
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at module.exports (/usr/local/lib/node_modules/npm/lib/install/mutate-into-logical-tree.js:12:3)
npm ERR! typeerror     at /usr/local/lib/node_modules/npm/lib/outdated.js:78:5
npm ERR! typeerror     at /usr/local/lib/node_modules/npm/lib/outdated.js:62:20
npm ERR! typeerror     at /usr/local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:186:9
npm ERR! typeerror     at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:17:25)
npm ERR! typeerror     at /usr/local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:152:20
npm ERR! typeerror     at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:17:25)
npm ERR! typeerror     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:121:22)
npm ERR! typeerror     at /usr/local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:81:20
npm ERR! typeerror     at fs.js:1518:23
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/brianzelip/npm-debug.log
```

**Comment by girishsortur** [comment]
Is it something to do with your version of node? I had similar issue occurring to me but it got fixed when i re-installed node and npm with the latest versions. Thanks
