### ISSUE TITLE
404 header with content?

### ISSUE THREAD

**Issue by bmcorser** [npm/npm#10911]
When I try to install `scrollreveal` package I get a 404. When I run the GET request "by hand", I see the 404 header, but the package meta data is also returned:

Output from install command:
```
$ npm install scrollreveal
npm ERR! Linux 3.13.0-54-generic
npm ERR! argv "/home/ben/.pyenv/versions/fe-build/bin/node" "/home/ben/.pyenv/versions/fe-build/bin/npm" "install" "scrollreveal"
npm ERR! node v4.1.0
npm ERR! npm  v3.5.2
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on http://registry.npmjs.org/scrollreveal
npm ERR! 404
npm ERR! 404  'scrollreveal' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ben/buildbot/snow/karma/build/browser/deskgen-landing/npm-debug.log
```

Debug output:
```
$ cat /home/ben/buildbot/snow/karma/build/browser/deskgen-landing/npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/home/ben/.pyenv/versions/fe-build/bin/node',
1 verbose cli   '/home/ben/.pyenv/versions/fe-build/bin/npm',
1 verbose cli   'install',
1 verbose cli   'scrollreveal' ]
2 info using npm@3.5.2
3 info using node@v4.1.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData scrollreveal@^2.3.2
8 silly fetchNamedPackageData scrollreveal
9 silly mapToRegistry name scrollreveal
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry http://registry.npmjs.org/
12 silly mapToRegistry uri http://registry.npmjs.org/scrollreveal
13 verbose request uri http://registry.npmjs.org/scrollreveal
14 verbose request no auth needed
15 info attempt registry request try #1 at 13:29:28
16 verbose request id b627f042cbbd862b
17 http request GET http://registry.npmjs.org/scrollreveal
18 http 404 http://registry.npmjs.org/scrollreveal
19 verbose headers { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
19 verbose headers   etag: '"43QW89HMIBGSPJ6FT1FPNR0DE"',
19 verbose headers   'content-type': 'application/json',
19 verbose headers   'cache-control': 'max-age=0',
19 verbose headers   'content-length': '476',
19 verbose headers   'accept-ranges': 'bytes',
19 verbose headers   date: 'Mon, 21 Dec 2015 13:29:28 GMT',
19 verbose headers   via: '1.1 varnish',
19 verbose headers   age: '0',
19 verbose headers   connection: 'keep-alive',
19 verbose headers   'x-served-by': 'cache-fra1249-FRA',
19 verbose headers   'x-cache': 'MISS',
19 verbose headers   'x-cache-hits': '0',
19 verbose headers   'x-timer': 'S1450704568.507599,VS0,VE192',
19 verbose headers   vary: 'Accept' }
20 silly get cb [ 404,
20 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
20 silly get     etag: '"43QW89HMIBGSPJ6FT1FPNR0DE"',
20 silly get     'content-type': 'application/json',
20 silly get     'cache-control': 'max-age=0',
20 silly get     'content-length': '476',
20 silly get     'accept-ranges': 'bytes',
20 silly get     date: 'Mon, 21 Dec 2015 13:29:28 GMT',
20 silly get     via: '1.1 varnish',
20 silly get     age: '0',
20 silly get     connection: 'keep-alive',
20 silly get     'x-served-by': 'cache-fra1249-FRA',
20 silly get     'x-cache': 'MISS',
20 silly get     'x-cache-hits': '0',
20 silly get     'x-timer': 'S1450704568.507599,VS0,VE192',
20 silly get     vary: 'Accept' } ]
21 silly fetchPackageMetaData Error: Registry returned 404 for GET on http://registry.npmjs.org/scrollreveal
21 silly fetchPackageMetaData     at makeError (/home/ben/.pyenv/versions/fe-build/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
21 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (/home/ben/.pyenv/versions/fe-build/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:242:14)
21 silly fetchPackageMetaData     at Request._callback (/home/ben/.pyenv/versions/fe-build/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
21 silly fetchPackageMetaData     at Request.self.callback (/home/ben/.pyenv/versions/fe-build/lib/node_modules/npm/node_modules/request/request.js:198:22)
21 silly fetchPackageMetaData     at emitTwo (events.js:87:13)
21 silly fetchPackageMetaData     at Request.emit (events.js:172:7)
21 silly fetchPackageMetaData     at Request.<anonymous> (/home/ben/.pyenv/versions/fe-build/lib/node_modules/npm/node_modules/request/request.js:1082:10)
21 silly fetchPackageMetaData     at emitOne (events.js:82:20)
21 silly fetchPackageMetaData     at Request.emit (events.js:169:7)
21 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (/home/ben/.pyenv/versions/fe-build/lib/node_modules/npm/node_modules/request/request.js:1009:12)
21 silly fetchPackageMetaData  error for scrollreveal@^2.3.2 { [Error: Registry returned 404 for GET on http://registry.npmjs.org/scrollreveal] pkgid: 'scrollreveal', statusCode: 404, code: 'E404' }
22 silly rollbackFailedOptional Starting
23 silly rollbackFailedOptional Finishing
24 silly runTopLevelLifecycles Starting
25 silly runTopLevelLifecycles Finishing
26 silly install printInstalled
27 verbose stack Error: Registry returned 404 for GET on http://registry.npmjs.org/scrollreveal
27 verbose stack     at makeError (/home/ben/.pyenv/versions/fe-build/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
27 verbose stack     at CachingRegistryClient.<anonymous> (/home/ben/.pyenv/versions/fe-build/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:242:14)
27 verbose stack     at Request._callback (/home/ben/.pyenv/versions/fe-build/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
27 verbose stack     at Request.self.callback (/home/ben/.pyenv/versions/fe-build/lib/node_modules/npm/node_modules/request/request.js:198:22)
27 verbose stack     at emitTwo (events.js:87:13)
27 verbose stack     at Request.emit (events.js:172:7)
27 verbose stack     at Request.<anonymous> (/home/ben/.pyenv/versions/fe-build/lib/node_modules/npm/node_modules/request/request.js:1082:10)
27 verbose stack     at emitOne (events.js:82:20)
27 verbose stack     at Request.emit (events.js:169:7)
27 verbose stack     at IncomingMessage.<anonymous> (/home/ben/.pyenv/versions/fe-build/lib/node_modules/npm/node_modules/request/request.js:1009:12)
28 verbose statusCode 404
29 verbose pkgid scrollreveal
30 verbose cwd /home/ben/buildbot/snow/karma/build/browser/deskgen-landing
31 error Linux 3.13.0-54-generic
32 error argv "/home/ben/.pyenv/versions/fe-build/bin/node" "/home/ben/.pyenv/versions/fe-build/bin/npm" "install" "scrollreveal"
33 error node v4.1.0
34 error npm  v3.5.2
35 error code E404
36 error 404 Registry returned 404 for GET on http://registry.npmjs.org/scrollreveal
37 error 404
38 error 404 'scrollreveal' is not in the npm registry.
39 error 404 You should bug the author to publish it (or use the name yourself!)
40 error 404 Note that you can also install from a
41 error 404 tarball, folder, http url, or git url.
42 verbose exit [ 1, true ]
```

If I run a GET on the URL mentioned (with [HTTPie](https://github.com/jkbrzt/httpie)), then I see content ... why does it have 404?
```
$ http http://registry.npmjs.org/scrollreveal
HTTP/1.1 404 Not Found
Accept-Ranges: bytes
Age: 0
Cache-Control: max-age=0
Connection: keep-alive
Content-Length: 476
Content-Type: application/json
Date: Mon, 21 Dec 2015 13:32:05 GMT
Vary: Accept
Via: 1.1 varnish
X-Cache: MISS
X-Cache-Hits: 0
X-Served-By: cache-fra1225-FRA
X-Timer: S1450704725.703404,VS0,VE196
etag: "CMA4OGYL77LDZUPU5G5Q1A550"
server: CouchDB/1.5.0 (Erlang OTP/R16B03)

{
    "_attachments": {},
    "_id": "scrollreveal",
    "_rev": "9-d7a83165b7c4c1312c0afb199b7d61d2",
    "name": "scrollreveal",
    "time": {
        "2.2.0": "2015-03-18T18:36:38.610Z",
        "2.3.2": "2015-06-15T03:47:13.926Z",
        "3.0.0": "2015-12-16T02:03:23.907Z",
        "created": "2015-03-18T18:36:38.610Z",
        "modified": "2015-12-16T02:03:23.907Z",
        "unpublished": {
            "maintainers": [
                {
                    "email": "julianlloyd@gmail.com",
                    "name": "jlmakes"
                }
            ],
            "name": "jlmakes",
            "tags": {
                "latest": "3.0.0"
            },
            "time": "2015-12-18T02:42:23.417Z",
            "versions": [
                "3.0.0"
            ]
        }
    }
}
```

**Comment by KenanY** [comment]
@bmcorser Is this still an issue (considering how https://github.com/jlmakes/scrollreveal.js/issues/195 has been resolved)?

**Comment by bmcorser** [comment]
@KenanY :+1: 
```
$ http --headers http://registry.npmjs.org/scrollreveal
HTTP/1.1 200 OK
Accept-Ranges: bytes
Age: 14
Cache-Control: max-age=300
Connection: keep-alive
Content-Length: 16826
Content-Type: application/json
Date: Sun, 27 Dec 2015 09:33:33 GMT
Vary: Accept
Via: 1.1 varnish
X-Cache: HIT
X-Cache-Hits: 1
X-Served-By: cache-fra1246-FRA
X-Timer: S1451208813.142092,VS0,VE0
etag: "4CBA6W4H8K1ZOSTDWGYBWFAOW"
server: CouchDB/1.5.0 (Erlang OTP/R16B03)
```
but :egg: `->` :fire: https://github.com/jlmakes/scrollreveal.js/issues/206
