### ISSUE TITLE
"npm update npm -g" doesn't work anymore in mac

### ISSUE THREAD

**Issue by girishsortur** [npm/npm#10910]
I get below error when i run the following commands `npm update npm -g` and `npm update -g` in command line of MAC OSX v10.11.2 - 

```
npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/Cellar/node/5.2.0/bin/node" "/usr/local/bin/npm" "update" "npm" "-g"
npm ERR! node v5.2.0
npm ERR! npm  v3.3.12
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at module.exports (/usr/local/lib/node_modules/npm/lib/install/mutate-into-logical-tree.js:12:3)
npm ERR! typeerror     at /usr/local/lib/node_modules/npm/lib/outdated.js:78:5
npm ERR! typeerror     at /usr/local/lib/node_modules/npm/lib/outdated.js:62:20
npm ERR! typeerror     at /usr/local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:179:20
npm ERR! typeerror     at gotStat (fs.js:1639:21)
npm ERR! typeerror     at FSReqWrap.oncomplete (fs.js:83:15)
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ibm/npm-debug.log
``` 

 and here is the npm-debug log file -

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/5.2.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'update',
1 verbose cli   'npm',
1 verbose cli   '-g' ]
2 info using npm@3.3.12
3 info using node@v5.2.0
4 verbose stack Error: Missing required argument #1
4 verbose stack     at module.exports (/usr/local/lib/node_modules/npm/lib/install/mutate-into-logical-tree.js:12:3)
4 verbose stack     at /usr/local/lib/node_modules/npm/lib/outdated.js:78:5
4 verbose stack     at /usr/local/lib/node_modules/npm/lib/outdated.js:62:20
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:179:20
4 verbose stack     at gotStat (fs.js:1639:21)
4 verbose stack     at FSReqWrap.oncomplete (fs.js:83:15)
5 verbose cwd /Users/ibm
6 error Darwin 15.2.0
7 error argv "/usr/local/Cellar/node/5.2.0/bin/node" "/usr/local/bin/npm" "update" "npm" "-g"
8 error node v5.2.0
9 error npm  v3.3.12
10 error code EMISSINGARG
11 error typeerror Error: Missing required argument #1
11 error typeerror     at module.exports (/usr/local/lib/node_modules/npm/lib/install/mutate-into-logical-tree.js:12:3)
11 error typeerror     at /usr/local/lib/node_modules/npm/lib/outdated.js:78:5
11 error typeerror     at /usr/local/lib/node_modules/npm/lib/outdated.js:62:20
11 error typeerror     at /usr/local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:179:20
11 error typeerror     at gotStat (fs.js:1639:21)
11 error typeerror     at FSReqWrap.oncomplete (fs.js:83:15)
11 error typeerror This is an error with npm itself. Please report this error at:
11 error typeerror     <http://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
```

Thanks for help.

**Comment by girishsortur** [comment]
I was able to fix this issue by manually replacing the npm v3.3.x with the latest one v3.5.2. Here are the steps i followed - 
1. Run command `npm install -g npm`.
2. npm will be installed as a module in `/users/xxx/.node/lib/node_modules` folder in my mac.
3. Copy the npm folder to the location where npm usually gets installed, in my case `/usr/local/lib/node_modules` folder.
4. Run `npm update -g` command to see it working.
