### ISSUE TITLE
npm install error: EHOSTDOWN

### ISSUE THREAD

**Issue by hatra-e** [npm/npm#10923]
I get this every time I try to install anything.

```
$ sudo npm install sassdoc -g
Password:
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "sassdoc" "-g"
npm ERR! node v4.2.3
npm ERR! npm  v2.14.0
npm ERR! code EHOSTDOWN
npm ERR! errno EHOSTDOWN
npm ERR! syscall connect

npm ERR! connect EHOSTDOWN 23.235.44.162:80 - Local (0.0.0.0:0)
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/****************************/npm-debug.log





$ cat /Users/****************************/npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'sassdoc',
1 verbose cli   '-g' ]
2 info using npm@2.14.0
3 info using node@v4.2.3
4 verbose install initial load of /usr/local/lib/package.json
5 verbose readDependencies loading dependencies from /usr/local/lib/package.json
6 silly cache add args [ 'sassdoc', null ]
7 verbose cache add spec sassdoc
8 silly cache add parsed spec Result {
8 silly cache add   raw: 'sassdoc',
8 silly cache add   scope: null,
8 silly cache add   name: 'sassdoc',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: '*',
8 silly cache add   type: 'range' }
9 silly addNamed sassdoc@*
10 verbose addNamed "*" is a valid semver range for sassdoc
11 silly addNameRange { name: 'sassdoc', range: '*', hasData: false }
12 silly mapToRegistry name sassdoc
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry http://registry.npmjs.org/
15 silly mapToRegistry uri http://registry.npmjs.org/sassdoc
16 verbose addNameRange registry:http://registry.npmjs.org/sassdoc not in flight; fetching
17 verbose request uri http://registry.npmjs.org/sassdoc
18 verbose request no auth needed
19 info attempt registry request try #1 at 11:46:58 AM
20 verbose request id 6593cc5387d3526d
21 http request GET http://registry.npmjs.org/sassdoc
22 info retry will retry, error on last attempt: Error: connect EHOSTDOWN 23.235.44.162:80 - Local (0.0.0.0:0)
23 info attempt registry request try #2 at 11:47:08 AM
24 http request GET http://registry.npmjs.org/sassdoc
25 info retry will retry, error on last attempt: Error: connect EHOSTDOWN 23.235.44.162:80 - Local (0.0.0.0:0)
26 info attempt registry request try #3 at 11:48:08 AM
27 http request GET http://registry.npmjs.org/sassdoc
28 verbose stack Error: connect EHOSTDOWN 23.235.44.162:80 - Local (0.0.0.0:0)
28 verbose stack     at Object.exports._errnoException (util.js:874:11)
28 verbose stack     at exports._exceptionWithHostPort (util.js:897:20)
28 verbose stack     at connect (net.js:841:14)
28 verbose stack     at net.js:984:7
28 verbose stack     at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:63:16)
28 verbose stack     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:82:10)
29 verbose cwd /Users/****************************
30 error Darwin 15.0.0
31 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "sassdoc" "-g"
32 error node v4.2.3
33 error npm  v2.14.0
34 error code EHOSTDOWN
35 error errno EHOSTDOWN
36 error syscall connect
37 error connect EHOSTDOWN 23.235.44.162:80 - Local (0.0.0.0:0)
38 error If you need help, you may report this error at:
38 error     <https://github.com/npm/npm/issues>
39 verbose exit [ 1, true ]
```

**Comment by hatra-e** [comment]
Resolved: Firewall issue.

**Comment by thebarty** [comment]
Yeah! Thanks for the hint! LittleSnitch tricked me a bit
