### ISSUE TITLE
npm install error for meanjs package in Ubuntu 14.04

### ISSUE THREAD

**Issue by djmMax** [npm/npm#10937]
```
$npm install -g mean-cli

npm ERR!     at Object.parse (native)
npm ERR!     at RegClient.<anonymous> (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:238:23)
npm ERR!     at Request.self.callback (/usr/lib/nodejs/request/index.js:148:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/index.js:896:14)
npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/lib/nodejs/request/index.js:847:12)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-32-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "mean-cli"
npm ERR! cwd /home/majx
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! type unexpected_eos
```

**Comment by KenanY** [comment]
@djmMax `npm@1.3` is very old and no longer supported. Please try [updating](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm).

**Comment by djmMax** [comment]
Thank You :D 

    Le Mercredi 23 décembre 2015 16h48, Kenan Yildirim <notifications@github.com> a écrit :
 

 @djmMax npm@1.3 is very old and no longer supported. Please try updating.—

**Comment by othiym23** [comment]
Closing as resolved by @KenanY. Thanks, Kenan! Good luck, @djmMax!
