### ISSUE TITLE
Error 54 installing pimatic 

### ISSUE THREAD

**Issue by pergola73** [npm/npm#10944]
While performing the following command I receive an error  message, please advise.

```
pi@raspberrypi:~/pimatic-app $ npm install pimatic --prefix pimatic-app --produc                           tion

npm http GET https://registry.npmjs.org/tion
npm http GET https://registry.npmjs.org/pimatic
npm http 304 https://registry.npmjs.org/pimatic
npm http 404 https://registry.npmjs.org/tion
npm ERR! TypeError: Cannot read property 'latest' of undefined
npm ERR!     at next (/home/pi/lib/node_modules/npm/lib/cache.js:688:35)
npm ERR!     at /home/pi/lib/node_modules/npm/lib/cache.js:676:5
npm ERR!     at saved (/home/pi/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /home/pi/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:170:20
npm ERR!     at /home/pi/lib/node_modules/npm/node_modules/mkdirp/index.js:37:53
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/isaacs/npm/issues>

npm ERR! System Linux 4.1.13+
npm ERR! command "/home/pi/bin/node" "/home/pi/bin/npm" "install" "pimatic" "--prefix" "pimatic-app" "--produc" "tion"
npm ERR! cwd /home/pi/pimatic-app
npm ERR! node -v v0.10.24
npm ERR! npm -v 1.3.21
npm ERR! type non_object_property_load
npm ERR! Error: ENOSPC, write
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/isaacs/npm/issues>

npm ERR! System Linux 4.1.13+
npm ERR! command "/home/pi/bin/node" "/home/pi/bin/npm" "install" "pimatic" "--prefix" "pimatic-app" "--produc" "tion"
npm ERR! cwd /home/pi/pimatic-app
npm ERR! node -v v0.10.24
npm ERR! npm -v 1.3.21
npm ERR! code ENOSPC
npm ERR! errno 54
npm ERR! Error: ENOSPC, mkdir '/home/pi/tmp/npm-23279-seLlDRKy'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/isaacs/npm/issues>

npm ERR! System Linux 4.1.13+
npm ERR! command "/home/pi/bin/node" "/home/pi/bin/npm" "install" "pimatic" "--prefix" "pimatic-app" "--produc" "tion"
npm ERR! cwd /home/pi/pimatic-app
npm ERR! node -v v0.10.24
npm ERR! npm -v 1.3.21
npm ERR! path /home/pi/tmp/npm-23279-seLlDRKy
npm ERR! code ENOSPC
npm ERR! errno 54
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/pimatic-app/npm-debug.log
npm ERR! not ok code 0
```

**Comment by KenanY** [comment]
@pergola73 `npm@1.3` is very old now and is no longer supported. Please try [updating](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm).

**Comment by othiym23** [comment]
You might also want to look into all those extraneous spaces in

```
pi@raspberrypi:~/pimatic-app $ npm install pimatic --prefix pimatic-app --produc                           tion
```

which is probably the source of that confusing error message.

Closing as resolved by @KenanY.
