### ISSUE TITLE
npm isntall printer

### ISSUE THREAD

**Issue by fanjg** [npm/npm#10952]
```
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\setup\\nodejs\\node.exe',
1 verbose cli   'D:\\setup\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'printer' ]
2 info using npm@2.14.7
3 info using node@v4.2.3
4 verbose install initial load of d:\work\work\dianqu\nodedemo\nwprinter\package.json
5 verbose stack Error: Invalid name: "printer demo"
5 verbose stack     at ensureValidName (D:\setup\nodejs\node_modules\npm\node_modules\normalize-package-data\lib\fixer.js:331:15)
5 verbose stack     at Object.module.exports.fixNameField (D:\setup\nodejs\node_modules\npm\node_modules\normalize-package-data\lib\fixer.js:210:5)
5 verbose stack     at D:\setup\nodejs\node_modules\npm\node_modules\normalize-package-data\lib\normalize.js:32:38
5 verbose stack     at Array.forEach (native)
5 verbose stack     at normalize (D:\setup\nodejs\node_modules\npm\node_modules\normalize-package-data\lib\normalize.js:31:15)
5 verbose stack     at final (D:\setup\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:338:5)
5 verbose stack     at then (D:\setup\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:113:5)
5 verbose stack     at ReadFileContext.<anonymous> (D:\setup\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:284:20)
5 verbose stack     at ReadFileContext.callback (D:\setup\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:76:16)
5 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:303:13)
6 verbose cwd d:\work\work\dianqu\nodedemo\nwprinter
7 error Windows_NT 6.1.7601
8 error argv "D:\\setup\\nodejs\\node.exe" "D:\\setup\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "printer"
9 error node v4.2.3
10 error npm  v2.14.7
11 error Invalid name: "printer demo"
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
@fanjg As the error message implies, the `"name"` field in your `package.json` is invalid. Specifically, spaces are not allowed in package names.

**Comment by fanjg** [comment]
@KenanY   thank you!

**Comment by Delapouite** [comment]
Hello @KenanY 

This issue seems to be resolved, could you close it please? Thanks!

**Comment by KenanY** [comment]
@Delapouite Unfortunately I do not have the GitHub permissions necessary to do that :)

**Comment by othiym23** [comment]
Closing as resolved!
