### ISSUE TITLE
New issue, I tried on VPS.

### ISSUE THREAD

**Issue by Asi232** [npm/npm#10961]
I tried on VPS:

```
root@localhost:~/node-steam-master# npm install steam
npm ERR! Linux 3.2.0-23-generic-pae
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "steam"
npm ERR! node v5.2.0
npm ERR! npm  v3.3.12
npm ERR! code ENOSELF

npm ERR! Refusing to install steam as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /root/node-steam-master/npm-debug.log
```

I installed the NODE, and Steam Doesn't work, please help me with some tutorial,
Can I add you on Skype? 
Or if you can, add me, thanks.
Skype id: Asi.RO1

It says:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'steam@v0.6.8' ]
2 info using npm@3.5.2
3 info using node@v5.2.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData steam@v0.6.8
8 silly fetchNamedPackageData steam
9 silly mapToRegistry name steam
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry uri https://registry.npmjs.org/steam
13 verbose request uri https://registry.npmjs.org/steam
14 verbose request no auth needed
15 info attempt registry request try #1 at 6:33:22 PM
16 verbose request id 4eda6a513465cf9c
17 verbose etag "CBDCU5KF06N7XNI7UKG1XH320"
18 http request GET https://registry.npmjs.org/steam
19 http 304 https://registry.npmjs.org/steam
20 verbose headers { date: 'Sun, 27 Dec 2015 18:33:21 GMT',
20 verbose headers   via: '1.1 varnish',
20 verbose headers   'cache-control': 'max-age=300',
20 verbose headers   etag: '"CBDCU5KF06N7XNI7UKG1XH320"',
20 verbose headers   age: '194',
20 verbose headers   connection: 'keep-alive',
20 verbose headers   'x-served-by': 'cache-fra1231-FRA',
20 verbose headers   'x-cache': 'HIT',
20 verbose headers   'x-cache-hits': '1',
20 verbose headers   'x-timer': 'S1451241201.538133,VS0,VE0',
20 verbose headers   vary: 'Accept' }
21 silly get cb [ 304,
21 silly get   { date: 'Sun, 27 Dec 2015 18:33:21 GMT',
21 silly get     via: '1.1 varnish',
21 silly get     'cache-control': 'max-age=300',
21 silly get     etag: '"CBDCU5KF06N7XNI7UKG1XH320"',
21 silly get     age: '194',
21 silly get     connection: 'keep-alive',
21 silly get     'x-served-by': 'cache-fra1231-FRA',
21 silly get     'x-cache': 'HIT',
21 silly get     'x-cache-hits': '1',
21 silly get     'x-timer': 'S1451241201.538133,VS0,VE0',
21 silly get     vary: 'Accept' } ]
22 verbose etag https://registry.npmjs.org/steam from cache
23 verbose get saving steam to /root/.npm/registry.npmjs.org/steam/.cache.json
24 silly install normalizeTree
25 silly loadCurrentTree Finishing
26 silly loadIdealTree Starting
27 silly install loadIdealTree
28 silly cloneCurrentTree Starting
29 silly install cloneCurrentTreeToIdealTree
30 silly cloneCurrentTree Finishing
31 silly loadShrinkwrap Starting
32 silly install loadShrinkwrap
33 silly loadShrinkwrap Finishing
34 silly loadAllDepsIntoIdealTree Starting
35 silly install loadAllDepsIntoIdealTree
36 silly rollbackFailedOptional Starting
37 silly rollbackFailedOptional Finishing
38 silly runTopLevelLifecycles Starting
39 silly runTopLevelLifecycles Finishing
40 silly install printInstalled
41 verbose stack Error: Refusing to install steam as a dependency of itself
41 verbose stack     at checkSelf (/usr/local/lib/node_modules/npm/lib/install/validate-args.js:40:14)
41 verbose stack     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
41 verbose stack     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
41 verbose stack     at chain (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
41 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/validate-args.js:15:5
41 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
41 verbose stack     at Array.forEach (native)
41 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
41 verbose stack     at Array.forEach (native)
41 verbose stack     at asyncMap (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
42 verbose cwd /root/node-steam-master
43 error Linux 3.2.0-23-generic-pae
44 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "steam@v0.6.8"
45 error node v5.2.0
46 error npm  v3.5.2
47 error code ENOSELF
48 error Refusing to install steam as a dependency of itself
49 error If you need help, you may report this error at:
49 error     <https://github.com/npm/npm/issues>
50 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
@Asi232 So to me it looks like you are already in a folder that contains this module's code? At least, I say this because you are in a directory called `node-steam-master/`. `npm` does not allow you to install a module as a dependency of itself, as the error message implies.

Do you believe you are receiving this message in error?

**Comment by KenanY** [comment]
@Asi232 Are you still having this issue?

**Comment by KenanY** [comment]
Closing.
