### ISSUE TITLE
npm install connect error

### ISSUE THREAD

**Issue by muhaasibah** [npm/npm#10997]
Obtain following error when trying to install connect

c:\Program Files\nodejs\node_modules\npm\lib\npm.js:18
  var fs = gfs.gracefulify(require('fs'))
               ^

TypeError: gfs.gracefulify is not a function
    at c:\Program Files\nodejs\node_modules\npm\lib\npm.js:18:16
    at Object.<anonymous> (c:\Program Files\nodejs\node_modules\npm\lib\npm.js:483:3)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at c:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js:26:13
    at Object.<anonymous> (c:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js:76:3)
 c:\Program Files\nodejs\node_modules\npm\lib\npm.js:18
  var fs = gfs.gracefulify(require('fs'))
               ^

TypeError: gfs.gracefulify is not a function
    at c:\Program Files\nodejs\node_modules\npm\lib\npm.js:18:16
    at Object.<anonymous> (c:\Program Files\nodejs\node_modules\npm\lib\npm.js:483:3)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at c:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js:26:13
    at Object.<anonymous> (c:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js:76:3)

**Comment by yellowflash6** [comment]
Same here. I also got the issue when I tried to run an ionic app.

/usr/local/lib/node_modules/cordova/node_modules/npm/lib/npm.js:19
  , fs = gfs.gracefulify(require('fs'))
             ^

TypeError: gfs.gracefulify is not a function
    at /usr/local/lib/node_modules/cordova/node_modules/npm/lib/npm.js:19:14
    at Object.<anonymous> (/usr/local/lib/node_modules/cordova/node_modules/npm/lib/npm.js:469:3)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/util.js:27:21)
    at Module._compile (module.js:399:26)

**Comment by yellowflash6** [comment]
@muhaasibah What is the solution? Tried re-installing Node.js or npm?

**Comment by muhaasibah** [comment]
Uninstalled and re-installed on c:\Users\"username"\"folder"

**Comment by dhavaln** [comment]
I have facing the same error, I am using the v0.12.1 for Cordova and install v5.3.0 for React Native, now my cordova has stopped working and giving me this error.

Npm version is 3.3.12

**Comment by Garvice** [comment]
Is there a solution to this? I'm also receiving this error...

/usr/lib/node_modules/npm/lib/npm.js:18
  var fs = gfs.gracefulify(require('fs'))
               ^
TypeError: Object #<Object> has no method 'gracefulify'
    at /usr/lib/node_modules/npm/lib/npm.js:18:16
    at Object.<anonymous> (/usr/lib/node_modules/npm/lib/npm.js:485:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /usr/lib/node_modules/npm/bin/npm-cli.js:26:13
    at Object.<anonymous> (/usr/lib/node_modules/npm/bin/npm-cli.js:76:3)

**Comment by evandroabdao** [comment]
I had the same error.
Solved upgrading node and reinstalling cordova

[https://davidwalsh.name/upgrade-nodejs](https://davidwalsh.name/upgrade-nodejs)
[http://askubuntu.com/questions/426750/how-can-i-update-my-nodejs-to-the-latest-version](http://askubuntu.com/questions/426750/how-can-i-update-my-nodejs-to-the-latest-version)

**Comment by joshribakoff** [comment]
I'm using node 4.2.4 and npm 2.14.12, I tried reinstalling phonegap, reinstalling node, reinstalling npm... nothing will fix it. Apparently the function is part of `graceful-fs`, which I installed globally with npm, I still get the error though.

```
$ cordova plugin add https://github.com/apache/cordova-plugin-statusbar.git
/usr/lib/node_modules/cordova/node_modules/npm/lib/npm.js:19
  , fs = gfs.gracefulify(require('fs'))
             ^

TypeError: gfs.gracefulify is not a function
    at /usr/lib/node_modules/cordova/node_modules/npm/lib/npm.js:19:14
    at Object.<anonymous> (/usr/lib/node_modules/cordova/node_modules/npm/lib/npm.js:469:3)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/util.js:27:21)
    at Module._compile (module.js:435:26)

```

**Comment by diazsasak** [comment]
I replace my nodejs with the latest LTS version and reinstall cordova globally with npm and thats fix it

**Comment by dhavaln** [comment]
I installed NVM and installed Node 5.3 which resolve my React Native issue, and Node 4.3 which resolved my Cordova issue, I didn't install Cordova back it was there but just switching the Node did the job.

**Comment by ojnc** [comment]
I use Windows; similar should work in Mac and Linux

npm in cordova wrong and cordova uses private npm

go to C:\Users\sssca_000\AppData\Roaming\npm\node_modules\cordova\node_modules Rename npm to npm_XXX

Go to C:\Users\sssca_000\AppData\Roaming\npm\node_modules This is where real npm resides Copy npm directory from here to C:\Users\sssca_000\AppData\Roaming\npm\node_modules\cordova\node_modules

It worked fine for me!

**Comment by jeffrey1183** [comment]
I met this error, too.
I  installed NVM and installed Node 8.0 to solve it.
