### ISSUE TITLE
Error When Uninstalling Bluebird

### ISSUE THREAD

**Issue by albertreed** [npm/npm#11014]
I'm new to javascript, node and just about every tool I'm using so please know the appearance of ignorance is real. :-)

Running "npm uninstall bluebird --save" is asking me to post the error here - so that's what I'm doing. 

I've tried "npm cache clean"

COMMAND:
```
$ npm uninstall bluebird --save
npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "uninstall" "bluebird" "--save"
npm ERR! node v5.3.0
npm ERR! npm  v3.3.12
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #3
npm ERR! typeerror     at replaceModule (/usr/local/lib/node_modules/npm/lib/install/deps.js:427:3)
npm ERR! typeerror     at /usr/local/lib/node_modules/npm/lib/install/deps.js:236:7
npm ERR! typeerror     at Array.forEach (native)
npm ERR! typeerror     at exports.removeDeps (/usr/local/lib/node_modules/npm/lib/install/deps.js:232:8)
npm ERR! typeerror     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
npm ERR! typeerror     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
npm ERR! typeerror     at chain (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
npm ERR! typeerror     at Uninstaller.loadAllDepsIntoIdealTree (/usr/local/lib/node_modules/npm/lib/uninstall.js:72:3)
npm ERR! typeerror     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
npm ERR! typeerror     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

LOG FILE:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'uninstall',
1 verbose cli   'bluebird',
1 verbose cli   '--save' ]
2 info using npm@3.3.12
3 info using node@v5.3.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly install normalizeTree
8 silly loadCurrentTree Finishing
9 silly loadIdealTree Starting
10 silly install loadIdealTree
11 silly cloneCurrentTree Starting
12 silly install cloneCurrentTreeToIdealTree
13 silly cloneCurrentTree Finishing
14 silly loadShrinkwrap Starting
15 silly install loadShrinkwrap
16 silly loadShrinkwrap Finishing
17 silly loadAllDepsIntoIdealTree Starting
18 silly uninstall loadAllDepsIntoIdealtree
19 verbose stack Error: Missing required argument #3
19 verbose stack     at replaceModule (/usr/local/lib/node_modules/npm/lib/install/deps.js:427:3)
19 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/deps.js:236:7
19 verbose stack     at Array.forEach (native)
19 verbose stack     at exports.removeDeps (/usr/local/lib/node_modules/npm/lib/install/deps.js:232:8)
19 verbose stack     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
19 verbose stack     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
19 verbose stack     at chain (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
19 verbose stack     at Uninstaller.loadAllDepsIntoIdealTree (/usr/local/lib/node_modules/npm/lib/uninstall.js:72:3)
19 verbose stack     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
19 verbose stack     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
20 verbose cwd /Users/areed/Projects/wow5
21 error Darwin 15.2.0
22 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "uninstall" "bluebird" "--save"
23 error node v5.3.0
24 error npm  v3.3.12
25 error code EMISSINGARG
26 error typeerror Error: Missing required argument #3
26 error typeerror     at replaceModule (/usr/local/lib/node_modules/npm/lib/install/deps.js:427:3)
26 error typeerror     at /usr/local/lib/node_modules/npm/lib/install/deps.js:236:7
26 error typeerror     at Array.forEach (native)
26 error typeerror     at exports.removeDeps (/usr/local/lib/node_modules/npm/lib/install/deps.js:232:8)
26 error typeerror     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
26 error typeerror     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
26 error typeerror     at chain (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
26 error typeerror     at Uninstaller.loadAllDepsIntoIdealTree (/usr/local/lib/node_modules/npm/lib/uninstall.js:72:3)
26 error typeerror     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
26 error typeerror     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
26 error typeerror This is an error with npm itself. Please report this error at:
26 error typeerror     <http://github.com/npm/npm/issues>
27 verbose exit [ 1, true ]
 ```

**Comment by b-paul** [comment]
I got the same issue when uninstalling `corsproxy`. In my case, I had already uninstalled the module, but I was _repeating_ the uninstall with `--save` option to remove it from the package.json dependencies list. I was expecting the second instance of the command might scold me for trying to remove something not present, but instead it failed with this error, and did not remove the reference to `corsproxy` from package.json.

```0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'rm',
1 verbose cli   '--save',
1 verbose cli   'corsproxy' ]
2 info using npm@3.5.2
3 info using node@v5.3.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly install normalizeTree
8 silly loadCurrentTree Finishing
9 silly loadIdealTree Starting
10 silly install loadIdealTree
11 silly cloneCurrentTree Starting
12 silly install cloneCurrentTreeToIdealTree
13 silly cloneCurrentTree Finishing
14 silly loadShrinkwrap Starting
15 silly install loadShrinkwrap
16 silly loadShrinkwrap Finishing
17 silly loadAllDepsIntoIdealTree Starting
18 silly uninstall loadAllDepsIntoIdealtree
19 verbose stack Error: Missing required argument #3
19 verbose stack     at replaceModule (/usr/local/lib/node_modules/npm/lib/install/deps.js:438:3)
19 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/deps.js:234:7
19 verbose stack     at Array.forEach (native)
19 verbose stack     at exports.removeDeps (/usr/local/lib/node_modules/npm/lib/install/deps.js:230:8)
19 verbose stack     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
19 verbose stack     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
19 verbose stack     at chain (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
19 verbose stack     at Uninstaller.loadAllDepsIntoIdealTree (/usr/local/lib/node_modules/npm/lib/uninstall.js:72:3)
19 verbose stack     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
19 verbose stack     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
20 verbose cwd /Users/Ben/Projects/countries
21 error Darwin 15.2.0
22 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "rm" "--save" "corsproxy"
23 error node v5.3.0
24 error npm  v3.5.2
25 error code EMISSINGARG
26 error typeerror Error: Missing required argument #3
26 error typeerror     at replaceModule (/usr/local/lib/node_modules/npm/lib/install/deps.js:438:3)
26 error typeerror     at /usr/local/lib/node_modules/npm/lib/install/deps.js:234:7
26 error typeerror     at Array.forEach (native)
26 error typeerror     at exports.removeDeps (/usr/local/lib/node_modules/npm/lib/install/deps.js:230:8)
26 error typeerror     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
26 error typeerror     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
26 error typeerror     at chain (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
26 error typeerror     at Uninstaller.loadAllDepsIntoIdealTree (/usr/local/lib/node_modules/npm/lib/uninstall.js:72:3)
26 error typeerror     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
26 error typeerror     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
27 error typeerror This is an error with npm itself. Please report this error at:
27 error typeerror     <http://github.com/npm/npm/issues>
28 verbose exit [ 1, true ]
```

**Comment by sandfox** [comment]
Also seeing this problem with node `0.10.41` and npm `3.5.3` on Darwin `15.2.0`
command `npm remove --save espresso`

Here is the debug-log: https://gist.github.com/sandfox/37c80ee4ccd710c6183e

**Comment by davidvgalbraith** [comment]
Here I go: https://github.com/npm/npm/pull/11171
