### ISSUE TITLE
npm returns EPROTOTYPE error for any operation under Solaris 11.3

### ISSUE THREAD

**Issue by erg-williamto** [npm/npm#11021]
Hi All,

I always get EPROTOTYPE (protocol type error) when I try to run any npm operation which connects to   the registry.npmjs.org server. 

Here is the console output for the command;

```
npm ERR! SunOS 5.11
npm ERR! argv "/opt/Node.x64/bin/node" "/opt/Node.x64/bin/npm" "install" "http-server"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code EPROTOTYPE
npm ERR! errno EPROTOTYPE
npm ERR! syscall connect

npm ERR! connect EPROTOTYPE
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/Node.x64/bin/npm-debug.log
```

Here is the debug log for "npm install -g node-gyp":

```
0 info it worked if it ends with ok
1 verbose cli [ '/opt/Node/bin/node',
1 verbose cli   '/opt/Node/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'node-gyp' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 verbose node symlink /opt/Node/bin/node
5 silly cache add args [ 'node-gyp', null ]
6 verbose cache add spec node-gyp
7 silly cache add parsed spec { raw: 'node-gyp',
7 silly cache add   scope: null,
7 silly cache add   name: 'node-gyp',
7 silly cache add   rawSpec: '',
7 silly cache add   spec: '*',
7 silly cache add   type: 'range' }
8 verbose addNamed node-gyp@*
9 silly addNamed semver.valid null
10 silly addNamed semver.validRange *
11 silly addNameRange { name: 'node-gyp', range: '*', hasData: false }
12 silly mapToRegistry name node-gyp
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry http://registry.npmjs.org/
15 silly mapToRegistry uri http://registry.npmjs.org/node-gyp
16 verbose addNameRange registry:http://registry.npmjs.org/node-gyp not in flight; fetching
17 verbose request uri http://registry.npmjs.org/node-gyp
18 verbose request no auth needed
19 info attempt registry request try #1 at 4:43:56 PM
20 verbose request id 0d23993ff33e6d03
21 http request GET http://registry.npmjs.org/node-gyp
22 info retry will retry, error on last attempt: Error: connect EPROTOTYPE
23 info attempt registry request try #2 at 4:44:11 PM
24 http request GET http://registry.npmjs.org/node-gyp
25 info retry will retry, error on last attempt: Error: connect EPROTOTYPE
26 info attempt registry request try #3 at 4:45:11 PM
27 http request GET http://registry.npmjs.org/node-gyp
28 verbose stack Error: connect EPROTOTYPE
28 verbose stack     at exports._errnoException (util.js:746:11)
28 verbose stack     at connect (net.js:842:19)
28 verbose stack     at net.js:945:9
28 verbose stack     at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:81:16)
28 verbose stack     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:99:10)
29 verbose cwd /export/home/wto/work
30 error SunOS 5.11
31 error argv "/opt/Node/bin/node" "/opt/Node/bin/npm" "install" "-g" "node-gyp"
32 error node v0.12.2
33 error npm  v2.7.4
34 error code EPROTOTYPE
35 error errno EPROTOTYPE
36 error syscall connect
37 error connect EPROTOTYPE
38 error If you need help, you may report this error at:
38 error     <https://github.com/npm/npm/issues>
39 verbose exit [ 1, true ]
```

The system configuration is x64 Solaris 11.3 with Python 2.7.9. The nodejs package is using the pre-built binary for both x86 and x64. Both exhibits the same behaviour.

Thanks for all your help

**Comment by sp9usb** [comment]
I have this same problem. My code

```js
var client = net.connect(80, 'google.com', function(){ ... });
```
generate error: 

```
Error: connect EPROTOTYPE
	at exports._errnoException (util.js:746:11)
	at connect (net.js:842:19)
	at net.js:945:9
	at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:81:16)
	at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:99:10)
```

**Comment by maniv2013** [comment]
Any solution to fix this error
