### ISSUE TITLE
ionic installation failled

### ISSUE THREAD

**Issue by anahoua16** [npm/npm#11041]
Hi,

I am trying to install ionic for a windows machine using administrator cmd "npm install -g ionic" and I am having an error, please find attached the error log, please would you help me?

Thank you.
[npm-debug.zip](https://github.com/npm/npm/files/79196/npm-debug.zip)

```
111353 verbose stack Error: Callback called more than once.
111353 verbose stack     at errorHandler (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:110:16)
111353 verbose stack     at cb (C:\Program Files\nodejs\node_modules\npm\lib\install.js:229:12)
111353 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install.js:292:7
111353 verbose stack     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:7:26)
111353 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:18:7
111353 verbose stack     at Object.Installer.printInstalled (C:\Program Files\nodejs\node_modules\npm\lib\install.js:671:36)
111353 verbose stack     at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
111353 verbose stack     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
111353 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:18:7
111353 verbose stack     at Object.Installer.finishTracker (C:\Program Files\nodejs\node_modules\npm\lib\install.js:320:3)
111354 verbose cwd D:\Cordova\ionic_test
111355 error Windows_NT 6.1.7601
111356 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "ionic"
111357 error node v5.2.0
111358 error npm  v3.3.12
```

**Comment by iarna** [comment]
It looks like you're using `npm@3.3.12` (the version that comes with node 5.2.0). Can you try updating to the latest npm and trying again? We've fixed a lot of bugs between then and now and this might have been one of them.

Microsoft makes a great tool for making upgrading `npm` easier, you can find it here:

https://www.npmjs.com/package/npm-windows-upgrade

**Comment by anahoua16** [comment]
Thank you Iarna, but it didnt work even though I upgraded npm to 3.5.2, please find attached the new error log, 

NB: npm does not work on PowerShell but it works on CMD
[npm-debug.txt](https://github.com/npm/npm/files/80479/npm-debug.txt)
