### ISSUE TITLE
Could not install req-fast

### ISSUE THREAD

**Issue by ndaidong** [npm/npm#11053]
Hi everybody,

I'm having an issue with the package named "req-fast". One of my modules' dependency requires this package but no way to install.

```
ndaidong@bella-mint /var/www/node/fomo-sync $ npm install
npm ERR! Linux 4.2.0-19-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.3.0
npm ERR! npm  v3.3.12
npm ERR! code EREADFILE

npm ERR! Error extracting /home/ndaidong/.npm/req-fast/0.2.11/package.tgz archive: ENOENT: no such file or directory, open '/home/ndaidong/.npm/req-fast/0.2.11/package.tgz'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/node/fomo-sync/npm-debug.log
```

Nothing changes after I removed entirely "/home/ubuntu/.npm".

I've tried to install only req-fast with "npm install req-fast", here is result:

```
ndaidong@bella-mint /var/www/node/fomo-sync $ npm install req-fast
npm ERR! Linux 4.2.0-19-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "req-fast"
npm ERR! node v5.3.0
npm ERR! npm  v3.3.12
npm ERR! code EREADFILE

npm ERR! Error extracting /home/ndaidong/.npm/req-fast/0.2.11/package.tgz archive: ENOENT: no such file or directory, open '/home/ndaidong/.npm/req-fast/0.2.11/package.tgz'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/node/fomo-sync/npm-debug.log
```

What is the best way to fix this issue? Thanks.

My system info:

- Ubuntu 14.04, Linux Mint 17.3
- node 5.3.0
- npm 3.3.12

npm-debug.log
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'req-fast' ]
2 info using npm@3.3.12
3 info using node@v5.3.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData req-fast
8 silly fetchNamedPackageData req-fast
9 silly mapToRegistry name req-fast
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry uri https://registry.npmjs.org/req-fast
13 verbose request uri https://registry.npmjs.org/req-fast
14 verbose request no auth needed
15 info attempt registry request try #1 at 19:50:41
16 verbose request using bearer token for auth
17 verbose request id 7e37a770d4b1c454
18 verbose etag "DYP7WFXXN4J83SZU3U2OG053O"
19 http request GET https://registry.npmjs.org/req-fast
20 http 304 https://registry.npmjs.org/req-fast
21 verbose headers { 'cache-control': 'max-age=300',
21 verbose headers   'accept-ranges': 'bytes',
21 verbose headers   date: 'Wed, 06 Jan 2016 12:50:42 GMT',
21 verbose headers   via: '1.1 varnish',
21 verbose headers   connection: 'keep-alive',
21 verbose headers   'x-served-by': 'cache-sin6925-SIN',
21 verbose headers   'x-cache': 'MISS',
21 verbose headers   'x-cache-hits': '0',
21 verbose headers   'x-timer': 'S1452084641.593168,VS0,VE897' }
22 silly get cb [ 304,
22 silly get   { 'cache-control': 'max-age=300',
22 silly get     'accept-ranges': 'bytes',
22 silly get     date: 'Wed, 06 Jan 2016 12:50:42 GMT',
22 silly get     via: '1.1 varnish',
22 silly get     connection: 'keep-alive',
22 silly get     'x-served-by': 'cache-sin6925-SIN',
22 silly get     'x-cache': 'MISS',
22 silly get     'x-cache-hits': '0',
22 silly get     'x-timer': 'S1452084641.593168,VS0,VE897' } ]
23 verbose etag https://registry.npmjs.org/req-fast from cache
24 verbose get saving req-fast to /home/ndaidong/.npm/registry.npmjs.org/req-fast/.cache.json
25 silly install normalizeTree
26 silly loadCurrentTree Finishing
27 silly loadIdealTree Starting
28 silly install loadIdealTree
29 silly cloneCurrentTree Starting
30 silly install cloneCurrentTreeToIdealTree
31 silly cloneCurrentTree Finishing
32 silly loadShrinkwrap Starting
33 silly install loadShrinkwrap
34 silly loadShrinkwrap Finishing
35 silly loadAllDepsIntoIdealTree Starting
36 silly install loadAllDepsIntoIdealTree
37 silly resolveWithNewModule req-fast@0.2.11 checking installable status
38 silly cache add args [ 'req-fast', null ]
39 verbose cache add spec req-fast
40 silly cache add parsed spec Result {
40 silly cache add   raw: 'req-fast',
40 silly cache add   scope: null,
40 silly cache add   name: 'req-fast',
40 silly cache add   rawSpec: '',
40 silly cache add   spec: '*',
40 silly cache add   type: 'range' }
41 silly addNamed req-fast@*
42 verbose addNamed "*" is a valid semver range for req-fast
43 silly addNameRange { name: 'req-fast', range: '*', hasData: false }
44 silly mapToRegistry name req-fast
45 silly mapToRegistry using default registry
46 silly mapToRegistry registry https://registry.npmjs.org/
47 silly mapToRegistry uri https://registry.npmjs.org/req-fast
48 verbose addNameRange registry:https://registry.npmjs.org/req-fast not in flight; fetching
49 verbose get https://registry.npmjs.org/req-fast not expired, no request
50 silly addNameRange number 2 { name: 'req-fast', range: '*', hasData: true }
51 silly addNameRange versions [ 'req-fast',
51 silly addNameRange   [ '0.0.1',
51 silly addNameRange     '0.0.2',
51 silly addNameRange     '0.0.3',
51 silly addNameRange     '0.0.4',
51 silly addNameRange     '0.0.5',
51 silly addNameRange     '0.0.6',
51 silly addNameRange     '0.0.7',
51 silly addNameRange     '0.0.8',
51 silly addNameRange     '0.0.9',
51 silly addNameRange     '0.1.1',
51 silly addNameRange     '0.1.2',
51 silly addNameRange     '0.1.3',
51 silly addNameRange     '0.1.4',
51 silly addNameRange     '0.1.5',
51 silly addNameRange     '0.1.6',
51 silly addNameRange     '0.1.7',
51 silly addNameRange     '0.1.8',
51 silly addNameRange     '0.1.9',
51 silly addNameRange     '0.2.0',
51 silly addNameRange     '0.2.1',
51 silly addNameRange     '0.2.2',
51 silly addNameRange     '0.2.3',
51 silly addNameRange     '0.2.4',
51 silly addNameRange     '0.2.5',
51 silly addNameRange     '0.2.6',
51 silly addNameRange     '0.2.7',
51 silly addNameRange     '0.2.8',
51 silly addNameRange     '0.2.9',
51 silly addNameRange     '0.2.10',
51 silly addNameRange     '0.2.11',
51 silly addNameRange     '0.2.12',
51 silly addNameRange     '0.2.12-rc1' ] ]
52 silly addNamed req-fast@0.2.12
53 verbose addNamed "0.2.12" is a plain semver version for req-fast
54 silly cache afterAdd req-fast@0.2.12
55 verbose afterAdd /home/ndaidong/.npm/req-fast/0.2.12/package/package.json not in flight; writing
56 verbose afterAdd /home/ndaidong/.npm/req-fast/0.2.12/package/package.json written
57 silly rollbackFailedOptional Starting
58 silly rollbackFailedOptional Finishing
59 silly runTopLevelLifecycles Starting
60 silly runTopLevelLifecycles Finishing
61 silly install printInstalled
62 verbose stack Error: Error extracting /home/ndaidong/.npm/req-fast/0.2.11/package.tgz archive: ENOENT: no such file or directory, open '/home/ndaidong/.npm/req-fast/0.2.11/package.tgz'
62 verbose stack     at ReadStream.<anonymous> (/usr/local/lib/node_modules/npm/lib/fetch-package-metadata.js:286:10)
62 verbose stack     at emitOne (events.js:77:13)
62 verbose stack     at ReadStream.emit (events.js:169:7)
62 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:179:14
62 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:230:16
62 verbose stack     at FSReqWrap.oncomplete (fs.js:82:15)
63 verbose cwd /var/www/node/fomo-sync
64 error Linux 4.2.0-19-generic
65 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "req-fast"
66 error node v5.3.0
67 error npm  v3.3.12
68 error code EREADFILE
69 error Error extracting /home/ndaidong/.npm/req-fast/0.2.11/package.tgz archive: ENOENT: no such file or directory, open '/home/ndaidong/.npm/req-fast/0.2.11/package.tgz'
70 error If you need help, you may report this error at:
70 error     <https://github.com/npm/npm/issues>
71 verbose exit [ 1, true ]
```

Regards,
Dong

**Comment by ndaidong** [comment]
Thanks for reading. This issue has been resolved by its author.
