### ISSUE TITLE
Error: Cannot find module 'pinkie-promise'

### ISSUE THREAD

**Issue by sauravbhalotia** [npm/npm#11054]
I'm trying to update npm and get this error. I tried installing pinkie-pomise module still I get same error.
Can any one point to whats happening?

**$ which node**
_/usr/local/bin/node_

**$ which npm**
_/usr/local/bin/npm_

**$ echo $NODE_PATH**
_// returns empty_

In fact any command with **npm** returns the same error.

_Following is the error message_

```
__$ npm update__
Error: Cannot find module 'pinkie-promise'
    at Function.Module._resolveFilename (module.js:327:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/node_modules/har-validator/lib/index.js:3:15)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "update"
npm ERR! node v5.2.0
npm ERR! npm  v3.3.12
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'pinkie-promise'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

**Comment by bernatfortet** [comment]
@sauravbhalotia did you figure out what's going on?
I'm getting the same error
