### ISSUE TITLE
Cannot perform a "find" or "search"

### ISSUE THREAD

**Issue by object88** [npm/npm#11056]
I am trying to perform `npm search autorest` or `npm find autorest`, and keep running into the same issue: `(data.maintainers || []).map is not a function`.  I have cleared my cache, and tried with the following combination of versions:
node 4.2.2, npm 2.14.7
node 4.2.2, npm 2.14.15
node 4.2.2, npm 3.5.2
node 4.2.4, npm 2.14.12

Other commands, such as `ll` and `install` are working correctly.

Below is the contents of the npm-debug.log file...

````
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'search',
1 verbose cli   'autorest' ]
2 info using npm@2.14.12
3 info using node@v4.2.4
4 silly mapToRegistry name -/all
5 silly mapToRegistry using default registry
6 silly mapToRegistry registry http://proget.fsw.com/npm/fsw-npm
7 silly mapToRegistry uri http://proget.fsw.com/npm/fsw-npm/-/all
8 info updateIndex C:\Users\pbrousseau\AppData\Roaming\npm-cache\proget.fsw.com\npm\fsw-npm\-\all\.cache.json
9 verbose makeDirectory C:\Users\pbrousseau\AppData\Roaming\npm-cache creation not in flight; initializing
10 verbose makeCacheDir UID & GID are irrelevant on win32
11 warn Building the local index for the first time, please be patient
12 silly update-index fetching http://proget.fsw.com/npm/fsw-npm/-/all
13 verbose request uri http://proget.fsw.com/npm/fsw-npm/-/all
14 verbose request no auth needed
15 info attempt registry request try #1 at 9:42:37 AM
16 verbose request id a1aa3c0798e43559
17 http request GET http://proget.fsw.com/npm/fsw-npm/-/all
18 http 200 http://proget.fsw.com/npm/fsw-npm/-/all
19 verbose headers { 'cache-control': 'public, max-age=60',
19 verbose headers   'content-length': '25829825',
19 verbose headers   'content-type': 'application/json',
19 verbose headers   'content-encoding': 'gzip',
19 verbose headers   server: 'Microsoft-HTTPAPI/2.0',
19 verbose headers   'x-aspnet-version': '4.0.30319',
19 verbose headers   'x-ua-compatible': 'IE=edge',
19 verbose headers   'x-proget-version': '3.6.1.6',
19 verbose headers   date: 'Wed, 06 Jan 2016 16:43:13 GMT' }
20 verbose stack TypeError: (data.maintainers || []).map is not a function
20 verbose stack     at stripData (C:\Program Files\nodejs\node_modules\npm\lib\search.js:88:50)
20 verbose stack     at Array.map (native)
20 verbose stack     at filter (C:\Program Files\nodejs\node_modules\npm\lib\search.js:77:6)
20 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\search.js:67:21
20 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\cache\update-index.js:99:11
20 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:210:7
20 verbose stack     at FSReqWrap.oncomplete (fs.js:82:15)
21 verbose cwd C:\code\ACME\project-api\app
22 error Windows_NT 6.3.9600
23 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "search" "autorest"
24 error node v4.2.4
25 error npm  v2.14.12
26 error (data.maintainers || []).map is not a function
27 error If you need help, you may report this error at:
27 error     <https://github.com/npm/npm/issues>
28 verbose exit [ 1, true ]
````

**Comment by KenanY** [comment]
```
6 silly mapToRegistry registry http://proget.fsw.com/npm/fsw-npm
```

Does this also occur with the default registry (`registry.npmjs.com`)? I cannot reproduce with `npm@3.5.3`.

**Comment by object88** [comment]
Thank you, KenanY!  After issuing `npm config set registry https://registry.npmjs.org`, I was able to successfully search.  My company's local npm registry must be misbehaving.

**Comment by othiym23** [comment]
There may actually be a bug in npm here, which is that it should be verifying that `data.maintainers` is an array. My guess is that your local registry isn't doing the same canonicalization of the data returned by the `/-/all` endpoint that the primary registry does, which it shouldn't be doing, but that shouldn't cause npm to explode, either. A patch to verify that `data.maintainers` is an array (with tests!) would be very welcome.
