### ISSUE TITLE
ERR! Cannot find module 'asn1'

### ISSUE THREAD

**Issue by vcarbo** [npm/npm#11055]
Hi, I've got this error : 

```
Error: Cannot find module 'asn1'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\vincentcar\AppData\Roaming\npm\node_modules\npm\node_modules\request\node_modules\http-signature\lib\util.js:6:12)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\vincentcar\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v5.3.0
npm ERR! npm  v3.5.1
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'asn1'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

The only command that I can do is npm -v.. Can you help me ? Thanks

**Comment by iarna** [comment]
It looks like your installed npm version is broken, unfortunately. To fix this I would clear your globals directory and try upgrading it again:

```
rmdir /s /q C:\Users\vincentcar\AppData\Roaming\npm
npm install -g npm
```

Unfortunately this will mean you'll have to reinstall any other global modules you previously installed.

**Comment by davinc11** [comment]
It works thank you

**Comment by mgpeng** [comment]
try directly install in local folder:
npm install asn1
