### ISSUE TITLE
If an optional subdependency fails to install, npm 3.5.2 removes its subdependencies also required by root sibling dependencies as well 

### ISSUE THREAD

**Issue by lxe** [npm/npm#11076]
ref: https://github.com/uber/react-map-gl/issues/42

This is a tricky one. To reproduce, install `mapbox-gl@0.11.5` on a system that will fail to build its optionalDependecy `gl` (systems where libX11 dev bindings are not installed):

```
$ npm install --save mapbox-gl@0.11.5

...
> gl@2.1.5 install /home/udocker/allen-key/test-failure/node_modules/gl
> prebuild --download

prebuild WARN install libX11.so.6: cannot open shared object file: No such file or directory
gyp: angle/build/standalone.gypi not found (cwd: /home/udocker/allen-key/test-failure/node_modules/gl) while reading includes of angle/src/angle.gyp while loading dependencies of binding.gyp while trying to load binding.gyp
prebuild ERR! configure error
prebuild ERR! stack Error: `gyp` failed with exit code: 1
prebuild ERR! stack     at ChildProcess.onCpExit (/home/udocker/allen-key/test-failure/node_modules/node-gyp/lib/configure.js:305:16)
prebuild ERR! stack     at ChildProcess.emit (events.js:98:17)
prebuild ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
prebuild ERR! not ok
prebuild ERR! build Error: `gyp` failed with exit code: 1
prebuild ERR! build     at ChildProcess.onCpExit (/home/udocker/allen-key/test-failure/node_modules/node-gyp/lib/configure.js:305:16)
prebuild ERR! build     at ChildProcess.emit (events.js:98:17)
prebuild ERR! build     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
npm WARN install:gl@2.1.5 gl@2.1.5 install: `prebuild --download`
npm WARN install:gl@2.1.5 Exit status 2
test-failure@1.0.0 /home/udocker/allen-key/test-failure
└─┬ mapbox-gl@0.11.5

```

The installation will succeed, even though the optionalDep fails to build (as expected). However, the dependencies required by both the optionalDependency `gl`, and other required dependencies will be missing. 

I'm guessing they are removed during `rollbackFailedOptional`: https://github.com/npm/npm/blob/91ff125a41cda7339ba78008c221bc1e5df9dd43/lib/install.js#L495:

```
npm ERR! missing: core-util-is@~1.0.0, required by readable-stream@1.1.13
npm ERR! missing: string_decoder@~0.10.x, required by readable-stream@1.1.13
npm ERR! missing: core-util-is@~1.0.0, required by readable-stream@1.0.33
npm ERR! missing: string_decoder@~0.10.x, required by readable-stream@1.0.33
npm ERR! missing: core-util-is@~1.0.0, required by readable-stream@2.0.5
npm ERR! missing: string_decoder@~0.10.x, required by readable-stream@2.0.5
npm ERR! missing: once@^1.3.0, required by glob@4.0.6
npm ERR! missing: core-util-is@~1.0.0, required by readable-stream@1.1.13
npm ERR! missing: string_decoder@~0.10.x, required by readable-stream@1.1.13
```

`mapbox-gl@latest` removed the devDependecy in https://github.com/mapbox/mapbox-gl-js/pull/1846, so installing it will result in the proper tree.

Generic reproduction steps are pending.

**Comment by lxe** [comment]
Unlike #10985 and #11062, running npm install again will not correct the modules tree, suggesting a root cause that differs from the one causing those issues.
