### ISSUE TITLE
Error: Cannot find module 'readable-stream/transform'

### ISSUE THREAD

**Issue by samuelprabhu** [npm/npm#11082]
I have tried by re-installing node and as well as used npm cache clean, but not successful.
I am using ionic framework.
I am facing the below error and unable to fix

```
Error: Cannot find module 'readable-stream/transform'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Users\SUN\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\node_modules\vinyl-fs\node_modules\glob-stream\node_modules\unique-stream\node_modules\through2-filter\node_modules\through2\through2.js:1:79)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
```

Cannot find module 'readable-stream/transform' (CLI v1.7.12)

Your system information:

Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.0
Gulp local:
Ionic Version: 1.2.1
Ionic CLI Version: 1.7.12
Ionic App Lib Version: 0.6.5
OS: Windows 7 SP1
Node Version: v4.2.4

**Comment by Anonyfox** [comment]
+1 on this. 

Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 1.2.0-nightly-1823
Ionic CLI Version: 1.7.12
Ionic App Lib Version: 0.6.5
OS: Windows 7 SP1
Node Version: v4.2.4

**Comment by loay** [comment]
I removed the npm folder in `C:\Users\[USERNAME]\AppData\Roaming\ ` then I reinstalled npm. It worked after.

**Comment by busches** [comment]
What command(s) are you running and is this still happening on the latest version of npm and node?
