### ISSUE TITLE
missing script: debugserver

### ISSUE THREAD

**Issue by syreinrage** [npm/npm#11081]
used npm to install a platform that uses the ionic framework. when i tried to run npm run debugserver this error came up that said the script was missing. I had ran the script before to test my code (at some point i realized my updates were not being translated over to my dev preview window). when i tried to restart the debugserver i received the following error messages. Please advise

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'debugserver' ]
2 info using npm@3.3.12
3 info using node@v5.1.0
4 verbose stack Error: missing script: debugserver
4 verbose stack     at run (/usr/local/lib/node_modules/npm/lib/run-script.js:147:19)
4 verbose stack     at /usr/local/lib/node_modules/npm/lib/run-script.js:57:5
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:345:5
4 verbose stack     at checkBinReferences_ (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:309:45)
4 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:343:3)
4 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:113:5)
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:232:12
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:76:16
4 verbose stack     at tryToString (fs.js:414:3)
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)
5 verbose cwd /Users/jazminemiller/Sites/PhoneGap Projects/wordpress-hybrid-client
6 error Darwin 14.4.0
7 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "debugserver"
8 error node v5.1.0
9 error npm  v3.3.12
10 error missing script: debugserver
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
@syreinrage You should check your `package.json` file and see if you have a `"debugserver"` script defined. From the error message, it is highly likely that you don't have such a script defined.

**Comment by KenanY** [comment]
@syreinrage It has been a few months now with no reply from you. Are you still seeing this issue?

**Comment by KenanY** [comment]
No response, not an issue with `npm` anyways. Closing.
