### ISSUE TITLE
Error while trying to run a node-gyp used binding code.

### ISSUE THREAD

**Issue by DJKulangara** [npm/npm#11080]
Hi,
I am trying to access a C++ class from a node.js file.
On running, I am getting the error as follows.

```
86 verbose stack Error: No compatible version found: kerberos@undefined0.0.17
86 verbose stack Valid install targets:
86 verbose stack 0.0.17, 0.0.16, 0.0.15, 0.0.14, 0.0.12, 0.0.11, 0.0.10, 0.0.9, 0.0.8, 0.0.7, 0.0.6, 0.0.5, 0.0.4, 0.0.3, 0.0.2, 0.0.1
86 verbose stack
86 verbose stack     at pickVersionFromRegistryDocument (/usr/local/lib/node_modules/npm/lib/fetch-package-metadata.js:156:16)
86 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/iferr/index.js:13:50
86 verbose stack     at /usr/local/lib/node_modules/npm/lib/utils/pulse-till-done.js:19:8
86 verbose stack     at saved (/usr/local/lib/node_modules/npm/lib/cache/caching-client.js:168:7)
86 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:210:7
86 verbose stack     at FSReqWrap.oncomplete (fs.js:82:15)
87 verbose cwd /home/user/S2INE/RandD/node-addon-examples-master/8_passing_wrapped
88 error Linux 3.19.0-15-generic
89 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
90 error node v5.0.0
91 error npm  v3.5.3
92 error No compatible version found: kerberos@undefined0.0.17
92 error Valid install targets:
92 error 0.0.17, 0.0.16, 0.0.15, 0.0.14, 0.0.12, 0.0.11, 0.0.10, 0.0.9, 0.0.8, 0.0.7, 0.0.6, 0.0.5, 0.0.4, 0.0.3, 0.0.2, 0.0.1
93 error If you need help, you may report this error at:
93 error     <https://github.com/npm/npm/issues>
94 verbose exit [ 1, true ]
```

[errorlog.txt](https://github.com/npm/npm/files/82131/errorlog.txt)

I am facing the similar issue in my master project also. can anyone help me ?
Thanks in advance.

**Comment by KenanY** [comment]
```
86 verbose stack Error: No compatible version found: kerberos@undefined0.0.17
```

I don't understand where the "undefined" part if coming from. I think we might need your `package.json` as well.

**Comment by DJKulangara** [comment]
Sorry for the late response.
this is my package.json.

{
  "name": "passing_wrapped",
  "version": "0.0.0",
  "description": "Node.js Addons",
  "main": "addon.js",
  "private": true,
  "gypfile": true,
  "dependencies": {
    "bindings": "~1.2.1",
    "nan": "^2.0.0"
  }
}
