### ISSUE TITLE
ERR! Cannot find module 'mysql' 

### ISSUE THREAD

**Issue by riddhi31** [npm/npm#11097]
Hi ! i run my  js and got this error please help me.
```
module.js:328
    throw err;
    ^

Error: Cannot find module 'mysql'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (E:\xampp\htdocs\hubilo\communityChat\index.js:4:13)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
```

**Comment by Synvox** [comment]
Be sure to run `npm install` if you haven't tried that. If you have, try `npm install mysql --save`.

**Comment by riddhi31** [comment]
thank you so much...its working....

**Comment by othiym23** [comment]
Closing as resolved.

**Comment by kalel13** [comment]
I tried this, but still getting that error!

**Comment by Synvox** [comment]
@kalel13, make sure you run `npm install` and `npm install mysql --save` from your project folder. You may then verify that `mysql` is installed correctly by checking to see if there is a `mysql` folder inside the `node_modules` in your project.

If this still doesn't work, it is worth noting that you can also install modules globally with `-g` like `npm install -g mysql` in the case of mysql. This is not always advised as it does not add `mysql` as a declared dependency of your project.
