### ISSUE TITLE
git failure on npm update

### ISSUE THREAD

**Issue by rotaercz** [npm/npm#11095]
I'm getting this error on a Windows 7 machine.

```
C:\mtgjson-master>npm updatenpm WARN addRemoteGit Error: not found: git
npm WARN addRemoteGit     at F (C:\mtgjson-master\node_modules\npm\node_modules\which\which.js:78:19)
npm WARN addRemoteGit     at E (C:\mtgjson-master\node_modules\npm\node_modules\which\which.js:82:29)
npm WARN addRemoteGit     at C:\mtgjson-master\node_modules\npm\node_modules\which\which.js:93:16
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:82:15)
npm WARN addRemoteGit  git://github.com/Sembiance/xbase.git resetting remote C:\Users\rotaercz\AppData\Roaming\npm-cache\_git-remotes\git-github-com-Sembiance-x
base-git-b21acf7e because of error: { [Error: not found: git] code: 'ENOGIT' }
npm WARN addRemoteGit Error: not found: git
npm WARN addRemoteGit     at F (C:\mtgjson-master\node_modules\npm\node_modules\which\which.js:78:19)
npm WARN addRemoteGit     at E (C:\mtgjson-master\node_modules\npm\node_modules\which\which.js:82:29)
npm WARN addRemoteGit     at C:\mtgjson-master\node_modules\npm\node_modules\which\which.js:93:16
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:82:15)
npm WARN addRemoteGit  git://github.com/Sembiance/xutil.git resetting remote C:\Users\rotaercz\AppData\Roaming\npm-cache\_git-remotes\git-github-com-Sembiance-xutil-git-0c5e9fd9 because of error: { [Error: not found: git] code: 'ENOGIT' }
npm ERR! git clone --template=C:\Users\rotaercz\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/Sembiance/xbase.git C:\Users\rotaercz\AppData\Roaming\npm-cache\_git-remotes\git-github-com-Sembiance-xbase-git-b21acf7e: undefined
npm ERR! git clone --template=C:\Users\rotaercz\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/Sembiance/xbase.git C:\Users\rotaercz\AppData\Roaming\npm-cache\_git-remotes\git-github-com-Sembiance-xbase-git-b21acf7e: undefined
npm ERR! git clone --template=C:\Users\rotaercz\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/Sembiance/xutil.git C:\Users\rotaercz\AppData\Roaming\npm-cache\_git-remotes\git-github-com-Sembiance-xutil-git-0c5e9fd9: undefined
npm ERR! git clone --template=C:\Users\rotaercz\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/Sembiance/xutil.git C:\Users\rotaercz\AppData\Roaming\npm-cache\_git-remotes\git-github-com-Sembiance-xutil-git-0c5e9fd9: undefined

> mhash@2.1.3 install C:\mtgjson-master\node_modules\mhash
> node-gyp rebuild


C:\mtgjson-master\node_modules\mhash>if not defined npm_config_node_gyp (node "C:\mtgjson-master\node_modules\npm\bin\node-gyp-bin\\..\..\
node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
'node' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\wamp\\www\\goblinhammer\\public\\mtgjson-master\\mtgjson-master\\node.exe" "C:\\wamp\\www\\goblinhammer\\public\\mtgjson-master\\mtgjson-master\\node_modules\\npm\\bin\\npm-cli.js" "update"
npm ERR! node v4.2.4
npm ERR! npm  v2.14.12
npm ERR! code ENOGIT

npm ERR! not found: git
npm ERR!
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\mtgjson-master
2\npm-debug.log
```

**Comment by KenanY** [comment]
@rotaercz Hmm, I see this in the error message:

```
npm ERR! not found: git
npm ERR!
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.
```

What do you think?

**Comment by rotaercz** [comment]
Ah, thanks for pointing that out.

**Comment by othiym23** [comment]
Closing as resolved by @KenanY. Thanks, Kenan!
