### ISSUE TITLE
`npm install` fails on postinstall: Cannot find module 'inherits'

### ISSUE THREAD

**Issue by nolanlawson** [npm/npm#11101]
I'm sorry for spamming your repo with more issues, but I have a reproducible test case and I'm (fairly) certain the bug is in npm.

Essentially, I have a `package.json` that will consistently crash on `npm install`, on Node 5.3.0+ and npm 3.3.12. (It's unreproducible on Node 4.0.0.)

The error occurs when I add the `duplexify` package to my `package.json`. Then `npm install` starts breaking for any dependency with a `postinstall` step (such as `leveldown` or `phantomjs`). It doesn't make much sense, but it's 100% reproducible (on Mac OS X at least).

Just follow [these steps](http://github.com/nolanlawson/repro-pouchdb-4741) to reproduce:

```
git clone https://github.com/nolanlawson/repro-pouchdb-4741.git
cd repro-pouchdb-4741
npm install
```

If you remove the `duplexify` package from `package.json`, then suddenly `npm install` starts working. The weird thing is that `duplexify` itself doesn't have a postinstall step... :confused: 

Here's the output (abridged):

```
npm WARN install:leveldown@1.4.2 Exit status 1
module.js:328
    throw err;
    ^

Error: Cannot find module 'inherits'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/private/tmp/dfljsfdljsdfjlkds/repro-pouchdb-4741/node_modules/rimraf/node_modules/glob/glob.js:46:16)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
```

**Comment by nolanlawson** [comment]
I'm mistaken; this is actually related to `glob`, not `duplexify`. Removing `glob` fixes the issue: https://github.com/pouchdb/pouchdb/pull/4769

So this might actually be a bug in `glob`. Not sure.

**Comment by wesleytodd** [comment]
I think this has to do with install/postinstall scripts that rely on the dependencies being present.  Node-sass has a similar issue (https://github.com/sass/node-sass/issues/1336).

This change in behavior probably has to do with the multi-step install?
