### ISSUE TITLE
Cannot read property 'length' of undefined on dedupe

### ISSUE THREAD

**Issue by STRML** [npm/npm#11119]
We have a large tree with webpack, babel, etc,. that we shrinkwrap before deduping.

Dedupe crashes on npmv2 (I blame babel's move off peerdeps - v6 ballooned our node_modules folder by about 400MB!), so I'm evaluating 3.

3 crashes with:

```
npm verb stack TypeError: Cannot read property 'length' of undefined
npm verb stack     at /usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:56:56
npm verb stack     at /usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:136:12
npm verb stack     at FSReqWrap.oncomplete (fs.js:82:15)
npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "--registry=http://x.x.x.x:4873" "dedupe" "--verbose"
npm ERR! node v5.4.0
npm ERR! npm  v3.5.4
npm ERR! Cannot read property 'length' of undefined
npm ERR!
```

The line is [here](https://github.com/npm/npm/blob/8dd78bbe6003cd377bf51bf24a1c5f8fd656265d/lib/utils/lifecycle.js#L56):

```js
    if ((wd.indexOf(npm.dir) !== 0 ||
          wd.indexOf(pkg.name) !== wd.length - pkg.name.length) &&
```

I inserted some debugging:

```js
    console.log({wd: wd, pkg: pkg});
    if ((wd.indexOf(npm.dir) !== 0 ||
          wd.indexOf(pkg.name) !== wd.length - pkg.name.length) &&
```

which prints:

```js
{ wd: '/projects/f/node_modules/fsevents/node_modules/node-pre-gyp',
  pkg:
   { dependencies: {},
     devDependencies: {},
     optionalDependencies: {},
     _requiredBy: [],
     _phantomChildren: {},
     version: '',
     _location: '/fsevents/node-pre-gyp',
```

Hope that helps.

**Comment by iarna** [comment]
So it crashing because it thinks that `/projects/f/node_modules/fsevents/node_modules/node-pre-gyp` is missing a package name, either in an existing `package.json` or maybe more likely, missing a `package.json` entirely?

It looks like that last bit of debuggin you shared isn't complete (the trailing comma implies there were more lines)? Is there more that you could share?

As a work around: You might try nuking the entire tree and installing fresh w/ npm@3– it dedupes implicitly on new installs.

**Comment by STRML** [comment]
@iarna Thanks for the reply.

There weren't any other lines, unfortunately. I am not sure why that trailing comma was there, because that's all that printed (I agree, there should be some closing brackets).

I ran it from the start with npmv3. It seemed to me that there was still some duplication in the tree. For instance, from a stripped npm-shrinkwrap from this tree:

```
    "babel-plugin-syntax-async-functions": {
      "version": "6.3.13",
      "dependencies": {
        "babel-runtime": {
          "version": "5.8.34"
        }
      }
    },
    "babel-plugin-syntax-class-constructor-call": {
      "version": "6.3.13",
      "dependencies": {
        "babel-runtime": {
          "version": "5.8.34"
        }
      }
    },
    "babel-plugin-syntax-class-properties": {
      "version": "6.3.13",
      "dependencies": {
        "babel-runtime": {
          "version": "5.8.34"
        }
      }
    },
    "babel-plugin-syntax-decorators": {
      "version": "6.3.13",
      "dependencies": {
        "babel-runtime": {
          "version": "5.8.34"
        }
      }
    },
```

So it does not seem true that `npm@3` fully dedupes.

It seems the offending module was `npm-shrinkwrap`, which bundles `npm@2`. Since this tool doesn't work with `npm@3` anyway, I removed it. This fixed the explicit error, but I now have a large number of extraenous and invalid dependencies after a dedupe, which makes shrinkwrapping impossible. This appears to be related to optionalDependencies (just a guess), as the majority of the errors involve `fsevents`.

The errors after dedupe:

```
npm ERR! extraneous: https-proxy-agent@1.0.0 /project/node_modules/https-proxy-agent
npm ERR! extraneous: node-pre-gyp@0.6.17 /project/node_modules/node-pre-gyp
npm ERR! extraneous: nodesecurity-npm-utils@3.2.0 /project/node_modules/nodesecurity-npm-utils
npm ERR! error in /project/node_modules/fsevents/node_modules/node-pre-gyp: ENOENT: no such file or directory, open '/project/node_modules/fsevents/node_modules/node-pre-gyp/package.json'
npm ERR! invalid: node-pre-gyp /project/node_modules/fsevents/node_modules/node-pre-gyp
npm ERR! extraneous: tar-pack /project/node_modules/fsevents/node_modules/tar-pack
npm ERR! error in /project/node_modules/fsevents/node_modules/tar-pack: ENOENT: no such file or directory, open '/project/node_modules/fsevents/node_modules/tar-pack/package.json'
npm ERR! extraneous: async@1.5.0 /project/node_modules/fsevents/node_modules/async
npm ERR! extraneous: commander@2.9.0 /project/node_modules/fsevents/node_modules/commander
npm ERR! extraneous: debug@0.7.4 /project/node_modules/fsevents/node_modules/debug
npm ERR! extraneous: escape-string-regexp@1.0.3 /project/node_modules/fsevents/node_modules/escape-string-regexp
npm ERR! extraneous: mime-types@2.1.7 /project/node_modules/fsevents/node_modules/mime-types
npm ERR! extraneous: minimist@0.0.8 /project/node_modules/fsevents/node_modules/minimist
npm ERR! extraneous: npmlog@2.0.0 /project/node_modules/fsevents/node_modules/npmlog
npm ERR! extraneous: once@1.1.1 /project/node_modules/fsevents/node_modules/once
npm ERR! extraneous: rimraf@2.4.4 /project/node_modules/fsevents/node_modules/rimraf
npm ERR! extraneous: sshpk@1.7.0 /project/node_modules/fsevents/node_modules/sshpk
npm ERR! extraneous: tunnel-agent@0.4.1 /project/node_modules/fsevents/node_modules/tunnel-agent
npm ERR! extraneous: uid-number@0.0.3 /project/node_modules/fsevents/node_modules/uid-number
npm ERR! error in /project/node_modules/nsp/node_modules/https-proxy-agent: ENOENT: no such file or directory, open '/project/node_modules/nsp/node_modules/https-proxy-agent/package.json'
npm ERR! invalid: https-proxy-agent /project/node_modules/nsp/node_modules/https-proxy-agent
npm ERR! extraneous: agent-base /project/node_modules/nsp/node_modules/https-proxy-agent/node_modules/agent-base
npm ERR! error in /project/node_modules/nsp/node_modules/https-proxy-agent/node_modules/agent-base: ENOENT: no such file or directory, open '/project/node_modules/nsp/node_modules/https-proxy-agent/node_modules/agent-base/package.json'
npm ERR! error in /project/node_modules/nsp/node_modules/nodesecurity-npm-utils: ENOENT: no such file or directory, open '/project/node_modules/nsp/node_modules/nodesecurity-npm-utils/package.json'
npm ERR! invalid: nodesecurity-npm-utils /project/node_modules/nsp/node_modules/nodesecurity-npm-utils
npm ERR! extraneous: silent-npm-registry-client /project/node_modules/nsp/node_modules/nodesecurity-npm-utils/node_modules/silent-npm-registry-client
npm ERR! error in /project/node_modules/nsp/node_modules/nodesecurity-npm-utils/node_modules/silent-npm-registry-client: ENOENT: no such file or directory, open '/project/node_modules/nsp/node_modules/nodesecurity-npm-utils/node_modules/silent-npm-registry-client/package.json'
npm ERR! error in /project/node_modules/nsp/node_modules/rc: ENOENT: no such file or directory, open '/project/node_modules/nsp/node_modules/rc/package.json'
npm ERR! invalid: rc /project/node_modules/nsp/node_modules/rc
```

**Comment by cchamberlain** [comment]
I'm getting what looks to be the same issue while deduping [pruning, shrinkwrapping] using your in-publish flow on version 3.5.4:

![image](https://cloud.githubusercontent.com/assets/424694/12376585/087ad1d8-bcb1-11e5-8f3d-688b895212cc.png)

Running with silly and doing some printing I see that for me its that I believe its trying to dedupe mv out of one of my private scoped modules, and the mv module appears to be corrupted:

![image](https://cloud.githubusercontent.com/assets/424694/12376581/de382c68-bcb0-11e5-804a-f7b552006374.png)

Doesn't fail anymore after modding line 56 of lib/utils/lifecycle.js to:
![image](https://cloud.githubusercontent.com/assets/424694/12376598/e41d0c06-bcb1-11e5-94dc-aaa0d4bae563.png)

Not sure if this has any side effects or if it should do some sort of cleanup in the event of leftover folders with no package.json.

**Comment by mattecapu** [comment]
Same issue here. I did `dedupe`-`update`-`dedupe` but the second time I got this error.

**Comment by kumarharsh** [comment]
+1 I'm facing this issue on Windows too
