### ISSUE TITLE
npm 3.5.4 broken after self-update with node 5.4

### ISSUE THREAD

**Issue by m99coder** [npm/npm#11134]
After executing `npm update npm -g` with node 5.4 in place npm itself is broken.

```
$ npm -v
module.js:328
    throw err;
    ^

Error: Cannot find module 'npmlog'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:20:13
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:76:3)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
```

This can be rolled back by these steps:

```
$ sudo rm -rf /usr/local/bin/npm
$ brew uninstall node
$ brew install node
$ npm -v
3.3.12
```

**Comment by alflanagan** [comment]
Exact same result under CentOS 7:

`$ uname -a
Linux mgvwdm003.wme.owhc.net 3.10.0-327.3.1.el7.x86_64 #1 SMP Wed Dec 9 14:09:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by bazineta** [comment]
Broken on OSX for me as well, same issue, same nuclear option required to resolve.

**Comment by Gomah** [comment]
Same problem here.

**Comment by mgol** [comment]
I was updating from the version included in Node 5.4.1 to `npm@next` and hit it, too. The current `latest`, i.e. 3.5.3, installs fine.

**Comment by Alhadis** [comment]
The hell. I tried following the steps m99coder gave to resolve the issue, and it spat a permissions error at me:
`$ brew uninstall node
Uninstalling /usr/local/Cellar/node/5.4.1... (5,692 files, 20M)
Error: Permission denied - /usr/local/Cellar/node/5.4.1/lib/node_modules/npm/.mailmap`
When I checked inside that directory, every file in the directory was assigned `nobody` as the owner, instead of my actual login name. :| Never seen that before.

Repeating the steps as a superuser worked, but I felt like mentioning that odd permissions error in case it helps pinpoint the source of the issue.

**Specs:** Mac OS Mavericks, installed with Homebrew.

**Comment by techelephant** [comment]
+1
Did an node upgrade with homebrew and global npm update.

Before:
node -v = v5.3.0
npm -v = v3.5.3

After homebrew upgrade:
node -v = v5.4.1
npm -v = v3.3.12

After npm update npm -g
node -v = v5.4.1
npm -v = Cannot find module 'npmlog' error

**Comment by ggamel** [comment]
+1 and can confirm the following rolls npm back to `3.3.12` under OS X:

```
$ rm -rf /usr/local/bin/npm
$ brew uninstall node
$ brew install node
```


Here's the part of the npm update output that throws a npm err:

```
npm WARN EBUNDLEOVERRIDE Replacing bundled npm > init-package-json with new installed version
npm WARN EBUNDLEOVERRIDE Replacing bundled npm > npm-install-checks with new installed version
npm WARN EBUNDLEOVERRIDE Replacing bundled npm > npmlog with new installed version
npm WARN EBUNDLEOVERRIDE Replacing bundled npm > read-package-json with new installed version
npm WARN EBUNDLEOVERRIDE Replacing bundled npm > node-gyp with new installed version
module.js:327
    throw err;
    ^

Error: Cannot find module 'npmlog'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:20:13
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:76:3)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
```

**Comment by jonnybarnes** [comment]
I can confirm this happens on both OS X El Capitan and Debian 8, in both cases node v5.4.1 was compiled from source.

**Comment by alundiak** [comment]
I just updated to node 5.4.1 and I do confirm, it's the same buggy with `npm -v`:
```
$ npm  -v
module.js:327
    throw err;
    ^

Error: Cannot find module 'minimatch'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/rimraf/node_modules/glob/glob.js:44:17)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

```

I'm going to use workaround:
` npm install -g npm@3.5.3` suggested here: https://github.com/npm/npm/issues/11088

**Comment by heqian** [comment]
Got the same error "Error: Cannot find module 'npmlog'" on all my systems after upgrading to Node 5.4.1

- Mac OS X 10.10.5 + Node 5.4.1 installed through Homebrew
- Ubuntu 15.10 + Node 5.4.1 (through NodeSource's repo)
- Ubuntu 14.04.03 LTS + Node 5.4.1 (through NodeSource's repo)

**Comment by m99coder** [comment]
It’s resolved with node 5.4.1_1 update installing npm 3.5.3.

**Comment by jonnybarnes** [comment]
Sorry to be stupid but where can I download node 5.4.1_1?

**Comment by m99coder** [comment]
Just check `brew info node`. I installed it on Mac this way using Homebrew.

**Comment by govarthananve** [comment]
After update node v5.4.1 got error

Cordova build ios

module.js:327
    throw err;
    ^

Error: Cannot find module 'which'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /usr/local/lib/node_modules/cordova/node_modules/npm/lib/npm.js:22:13
    at Object.<anonymous> (/usr/local/lib/node_modules/cordova/node_modules/npm/lib/npm.js:475:3)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)

**Comment by fzs1994** [comment]
Problem in Windows when tried:
Chief. Ra's@ChiefRasPC MINGW64 ~/Desktop
$ ionic start someApp
module.js:327
    throw err;
    ^

Error: Cannot find module **'C:\c\Users\Chief. Ra's**\AppData\Roaming\npm\node_modules\ionic\bin\ionic'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

Chief. Ra's@ChiefRasPC MINGW64 ~/Desktop

**Comment by wilsonmar** [comment]
I'm running into the same module.js:327
throw err;
^

```
uname -a
Darwin macs-MacBook-Pro-4.local 15.4.0 Darwin Kernel Version 15.4.0: Fri Feb 26 22:08:05 PST 2016; root:xnu-3248.40.184~3/RELEASE_X86_64 x86_64

echo $NODE_PATH
/usr/local/lib/node_modules

brew unintall node
brew install node

node -v
v5.4.1

npm -v
-bash: /usr/local/bin/npm: No such file or directory

```

**Comment by jakubbarczyk** [comment]
Same here. I'm on Windows and have node 4.4.4 and npm 3.9.5 installed.
When I attempt to run _node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js --content-base src_ I get 

> module.js:327
    throw err;
    ^
Error: Cannot find module <absolute version of the above path>

**Comment by Nargren** [comment]
I am also running into this problem
```
module.js:327
    throw err;
    ^
```
System:
```
uname -a
Linux box 2.6.32-042stab113.12 #1 SMP Fri Jan 22 16:04:50 MSK 2016 x86_64 x86_64 x86_64 GNU/Linux

node -v
v4.4.5

npm -v
2.11.2

```

**Comment by sophiaphillyqueen** [comment]
I did what the OP on this thread said to do ---- and now it is even worse. Now, __npm__ is gone from my machine with no way at all to get it back.

**Comment by JessePotterMusic** [comment]
Hey there, I am getting the same error after using `npm i -g npm` which popped up as recommended after doing an npm init. After putting in that code, npm appear to have broken itself, and I get:

```
module.js:487
    throw err;
    ^

Error: Cannot find module 'npmlog'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at /home/ubuntu/.nvm/versions/node/v8.2.1/lib/node_modules/npm/bin/npm-cli.js:22:13
    at Object.<anonymous> (/home/ubuntu/.nvm/versions/node/v8.2.1/lib/node_modules/npm/bin/npm-cli.js:92:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
```
I tried following the instructions above, but I am getting the response that `brew: command not found`.
I am using a Cloud9 workspace, not sure if that has something to do with it. I am still very new to this, and am currently in the process of taking a web dev. course online. I need npm to work, as I can't install anything anymore. Any help would be greatly appreciated!
