### ISSUE TITLE
npm-cli.js  |   code EPIPE | errno EPIPE | syscall write | write EPIPE

### ISSUE THREAD

**Issue by fred1653** [npm/npm#11153]
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'prefix',
1 verbose cli   '-g' ]
2 info using npm@3.3.12
3 info using node@v5.4.1
4 verbose stack Error: write EPIPE
4 verbose stack     at exports._errnoException (util.js:856:11)
4 verbose stack     at Socket._writeGeneric (net.js:675:26)
4 verbose stack     at Socket._write (net.js:694:8)
4 verbose stack     at doWrite (_stream_writable.js:292:12)
4 verbose stack     at writeOrBuffer (_stream_writable.js:278:5)
4 verbose stack     at Socket.Writable.write (_stream_writable.js:207:11)
4 verbose stack     at Socket.write (net.js:618:40)
4 verbose stack     at Console.log (console.js:36:16)
4 verbose stack     at EventEmitter.prefix (C:\Program Files\nodejs\node_modules\npm\lib\prefix.js:12:24)
4 verbose stack     at Object.commandCache.(anonymous function) (C:\Program Files\nodejs\node_modules\npm\lib\npm.js:214:13)
5 verbose cwd E:\Project\sj
6 error Windows_NT 10.0.10586
7 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "prefix" "-g"
8 error node v5.4.1
9 error npm  v3.3.12
10 error code EPIPE
11 error errno EPIPE
12 error syscall write
13 error write EPIPE
14 error If you need help, you may report this error at:
14 error     <https://github.com/npm/npm/issues>
15 verbose exit [ 1, true ]
```

**Comment by iarna** [comment]
Wow that is really weird. Does it happen every time you run the command, or just this one time?

**Comment by iarna** [comment]
How are you running this command? Is it being run from some tool or CI? Or are you running it directly from `cmd.exe`?

**Comment by LeeDr** [comment]
I'm hitting this same issue on Windows 10 running in a git bash shell.  My stack trace looks the same.

Our pre-commit hook contains this line which causes the error when executed by itself;
```
$ npm run --json | grep -q '"precommit":'
npm ERR! code EPIPE
npm ERR! errno EPIPE
npm ERR! syscall write
npm ERR! write EPIPE

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Lee\AppData\Roaming\npm-cache\_logs\2018-04-12T20_03_38_221Z-debug.log
```
```
$ npm --version
5.6.0
```

I found a couple of work-arounds that I might put in our pre-commit commit.  Both of these work without throwing the error;

`npm run --json 2>&1 | grep -q '"precommit":'`
`npm run --json | grep '"precommit":' > /dev/null`
