### ISSUE TITLE
`npm install` doesn't support Git LFS

### ISSUE THREAD

**Issue by brynn-mahsman** [npm/npm#11151]
Giving `npm install` a repository on GitLab or GitHub (both of which support Git LFS), `npm` doesn't use the proper `lfs.url` when it attempts the clone in the `npm-cache` folder.

What is expected: for `npm install gitlab:brynn.mahsman/bubblegum` to operate much like `git clone https://gitlab.com/brynn.mahsman/bubblegum.git` and use the proper `lfs.url` reported by the git provider. The output for the latter command is:

```
[10:47:35 AM] /c/develop/projects/tmp/bubbletest
$ git clone https://gitlab.com/brynn.mahsman/bubblegum.git
Cloning into 'bubblegum'...
remote: Counting objects: 7, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 7 (delta 0), reused 0 (delta 0)
Unpacking objects: 100% (7/7), done.
Checking connectivity... done.
Downloading bubblegum.png (382.76 KB)

[10:47:43 AM] /c/develop/projects/tmp/bubbletest
$
```

Please note the last line where it reads `Downloading bubblegum.png (382.76 KB)`. This is the smudge filter triggering `git-lfs.exe smudge` to initiate the https request to get the file.

Actual output:

```
[10:42:03 AM] /c/develop/projects/tmp/bubbletest
$ npm install gitlab:brynn.mahsman/bubblegum
npm ERR! git clone C:\Users\bmahsman\AppData\Roaming\npm-cache\_git-remotes\git-https-gitlab-com-brynn-mahsman-bubblegum-git-cc5339c5c58ce5e031e1b073fce664ad C:\Users\bmahsman\AppData\Local\Temp\npm-11440-88a1a8aa\git-cache-9ec1beb0af2699382a6924c8abb4ebe2\df5df227ff72dfdc30db5846ace2b125388621d4: Cloning into 'C:\Users\bmahsman\AppData\Local\Temp\npm-11440-88a1a8aa\git-cache-9ec1beb0af2699382a6924c8abb4ebe2\df5df227ff72dfdc30db5846ace2b125388621d4'...
npm ERR! git clone C:\Users\bmahsman\AppData\Roaming\npm-cache\_git-remotes\git-https-gitlab-com-brynn-mahsman-bubblegum-git-cc5339c5c58ce5e031e1b073fce664ad C:\Users\bmahsman\AppData\Local\Temp\npm-11440-88a1a8aa\git-cache-9ec1beb0af2699382a6924c8abb4ebe2\df5df227ff72dfdc30db5846ace2b125388621d4: done.
npm ERR! git clone C:\Users\bmahsman\AppData\Roaming\npm-cache\_git-remotes\git-https-gitlab-com-brynn-mahsman-bubblegum-git-cc5339c5c58ce5e031e1b073fce664ad C:\Users\bmahsman\AppData\Local\Temp\npm-11440-88a1a8aa\git-cache-9ec1beb0af2699382a6924c8abb4ebe2\df5df227ff72dfdc30db5846ace2b125388621d4: Downloading bubblegum.png (382.76 KB)
npm ERR! git clone C:\Users\bmahsman\AppData\Roaming\npm-cache\_git-remotes\git-https-gitlab-com-brynn-mahsman-bubblegum-git-cc5339c5c58ce5e031e1b073fce664ad C:\Users\bmahsman\AppData\Local\Temp\npm-11440-88a1a8aa\git-cache-9ec1beb0af2699382a6924c8abb4ebe2\df5df227ff72dfdc30db5846ace2b125388621d4: Error accessing media: bubblegum.png (27139a2b3acc5b2eb3dd3785c6b91c8055b761125a5465ff74215b6cbc5872a3)
npm ERR! git clone C:\Users\bmahsman\AppData\Roaming\npm-cache\_git-remotes\git-https-gitlab-com-brynn-mahsman-bubblegum-git-cc5339c5c58ce5e031e1b073fce664ad C:\Users\bmahsman\AppData\Local\Temp\npm-11440-88a1a8aa\git-cache-9ec1beb0af2699382a6924c8abb4ebe2\df5df227ff72dfdc30db5846ace2b125388621d4:
npm ERR! git clone C:\Users\bmahsman\AppData\Roaming\npm-cache\_git-remotes\git-https-gitlab-com-brynn-mahsman-bubblegum-git-cc5339c5c58ce5e031e1b073fce664ad C:\Users\bmahsman\AppData\Local\Temp\npm-11440-88a1a8aa\git-cache-9ec1beb0af2699382a6924c8abb4ebe2\df5df227ff72dfdc30db5846ace2b125388621d4: Errors logged to .git\lfs\objects\logs\20160114T104217.5023588.log
npm ERR! git clone C:\Users\bmahsman\AppData\Roaming\npm-cache\_git-remotes\git-https-gitlab-com-brynn-mahsman-bubblegum-git-cc5339c5c58ce5e031e1b073fce664ad C:\Users\bmahsman\AppData\Local\Temp\npm-11440-88a1a8aa\git-cache-9ec1beb0af2699382a6924c8abb4ebe2\df5df227ff72dfdc30db5846ace2b125388621d4: Use `git lfs logs last` to view the log.
npm ERR! git clone C:\Users\bmahsman\AppData\Roaming\npm-cache\_git-remotes\git-https-gitlab-com-brynn-mahsman-bubblegum-git-cc5339c5c58ce5e031e1b073fce664ad C:\Users\bmahsman\AppData\Local\Temp\npm-11440-88a1a8aa\git-cache-9ec1beb0af2699382a6924c8abb4ebe2\df5df227ff72dfdc30db5846ace2b125388621d4: error: external filter git-lfs smudge %f failed 2
npm ERR! git clone C:\Users\bmahsman\AppData\Roaming\npm-cache\_git-remotes\git-https-gitlab-com-brynn-mahsman-bubblegum-git-cc5339c5c58ce5e031e1b073fce664ad C:\Users\bmahsman\AppData\Local\Temp\npm-11440-88a1a8aa\git-cache-9ec1beb0af2699382a6924c8abb4ebe2\df5df227ff72dfdc30db5846ace2b125388621d4: error: external filter git-lfs smudge %f failed
npm ERR! git clone C:\Users\bmahsman\AppData\Roaming\npm-cache\_git-remotes\git-https-gitlab-com-brynn-mahsman-bubblegum-git-cc5339c5c58ce5e031e1b073fce664ad C:\Users\bmahsman\AppData\Local\Temp\npm-11440-88a1a8aa\git-cache-9ec1beb0af2699382a6924c8abb4ebe2\df5df227ff72dfdc30db5846ace2b125388621d4: fatal: bubblegum.png: smudge filter lfs failed
npm ERR! git clone C:\Users\bmahsman\AppData\Roaming\npm-cache\_git-remotes\git-https-gitlab-com-brynn-mahsman-bubblegum-git-cc5339c5c58ce5e031e1b073fce664ad C:\Users\bmahsman\AppData\Local\Temp\npm-11440-88a1a8aa\git-cache-9ec1beb0af2699382a6924c8abb4ebe2\df5df227ff72dfdc30db5846ace2b125388621d4: warning: Clone succeeded, but checkout failed.
npm ERR! git clone C:\Users\bmahsman\AppData\Roaming\npm-cache\_git-remotes\git-https-gitlab-com-brynn-mahsman-bubblegum-git-cc5339c5c58ce5e031e1b073fce664ad C:\Users\bmahsman\AppData\Local\Temp\npm-11440-88a1a8aa\git-cache-9ec1beb0af2699382a6924c8abb4ebe2\df5df227ff72dfdc30db5846ace2b125388621d4: You can inspect what was checked out with 'git status'
npm ERR! git clone C:\Users\bmahsman\AppData\Roaming\npm-cache\_git-remotes\git-https-gitlab-com-brynn-mahsman-bubblegum-git-cc5339c5c58ce5e031e1b073fce664ad C:\Users\bmahsman\AppData\Local\Temp\npm-11440-88a1a8aa\git-cache-9ec1beb0af2699382a6924c8abb4ebe2\df5df227ff72dfdc30db5846ace2b125388621d4: and retry the checkout with 'git checkout -f HEAD'
npm ERR! git clone C:\Users\bmahsman\AppData\Roaming\npm-cache\_git-remotes\git-https-gitlab-com-brynn-mahsman-bubblegum-git-cc5339c5c58ce5e031e1b073fce664ad C:\Users\bmahsman\AppData\Local\Temp\npm-11440-88a1a8aa\git-cache-9ec1beb0af2699382a6924c8abb4ebe2\df5df227ff72dfdc30db5846ace2b125388621d4:
npm ERR! git clone C:\Users\bmahsman\AppData\Roaming\npm-cache\_git-remotes\git-https-gitlab-com-brynn-mahsman-bubblegum-git-cc5339c5c58ce5e031e1b073fce664ad C:\Users\bmahsman\AppData\Local\Temp\npm-11440-88a1a8aa\git-cache-9ec1beb0af2699382a6924c8abb4ebe2\df5df227ff72dfdc30db5846ace2b125388621d4:
npm ERR! git clone C:\Users\bmahsman\AppData\Roaming\npm-cache\_git-remotes\git-gitlab-com-brynn-mahsman-bubblegum-git-dba3c97871efd24f1aa52ecaee11cc5f C:\Users\bmahsman\AppData\Local\Temp\npm-11440-88a1a8aa\git-cache-6dfa4264275fe7084b621e161730286b\df5df227ff72dfdc30db5846ace2b125388621d4: Cloning into 'C:\Users\bmahsman\AppData\Local\Temp\npm-11440-88a1a8aa\git-cache-6dfa4264275fe7084b621e161730286b\df5df227ff72dfdc30db5846ace2b125388621d4'...
npm ERR! git clone C:\Users\bmahsman\AppData\Roaming\npm-cache\_git-remotes\git-gitlab-com-brynn-mahsman-bubblegum-git-dba3c97871efd24f1aa52ecaee11cc5f C:\Users\bmahsman\AppData\Local\Temp\npm-11440-88a1a8aa\git-cache-6dfa4264275fe7084b621e161730286b\df5df227ff72dfdc30db5846ace2b125388621d4: done.
npm ERR! git clone C:\Users\bmahsman\AppData\Roaming\npm-cache\_git-remotes\git-gitlab-com-brynn-mahsman-bubblegum-git-dba3c97871efd24f1aa52ecaee11cc5f C:\Users\bmahsman\AppData\Local\Temp\npm-11440-88a1a8aa\git-cache-6dfa4264275fe7084b621e161730286b\df5df227ff72dfdc30db5846ace2b125388621d4: Downloading bubblegum.png (382.76 KB)
npm ERR! git clone C:\Users\bmahsman\AppData\Roaming\npm-cache\_git-remotes\git-gitlab-com-brynn-mahsman-bubblegum-git-dba3c97871efd24f1aa52ecaee11cc5f C:\Users\bmahsman\AppData\Local\Temp\npm-11440-88a1a8aa\git-cache-6dfa4264275fe7084b621e161730286b\df5df227ff72dfdc30db5846ace2b125388621d4: Error accessing media: bubblegum.png (27139a2b3acc5b2eb3dd3785c6b91c8055b761125a5465ff74215b6cbc5872a3)
npm ERR! git clone C:\Users\bmahsman\AppData\Roaming\npm-cache\_git-remotes\git-gitlab-com-brynn-mahsman-bubblegum-git-dba3c97871efd24f1aa52ecaee11cc5f C:\Users\bmahsman\AppData\Local\Temp\npm-11440-88a1a8aa\git-cache-6dfa4264275fe7084b621e161730286b\df5df227ff72dfdc30db5846ace2b125388621d4:
npm ERR! git clone C:\Users\bmahsman\AppData\Roaming\npm-cache\_git-remotes\git-gitlab-com-brynn-mahsman-bubblegum-git-dba3c97871efd24f1aa52ecaee11cc5f C:\Users\bmahsman\AppData\Local\Temp\npm-11440-88a1a8aa\git-cache-6dfa4264275fe7084b621e161730286b\df5df227ff72dfdc30db5846ace2b125388621d4: Errors logged to .git\lfs\objects\logs\20160114T104223.4109496.log
npm ERR! git clone C:\Users\bmahsman\AppData\Roaming\npm-cache\_git-remotes\git-gitlab-com-brynn-mahsman-bubblegum-git-dba3c97871efd24f1aa52ecaee11cc5f C:\Users\bmahsman\AppData\Local\Temp\npm-11440-88a1a8aa\git-cache-6dfa4264275fe7084b621e161730286b\df5df227ff72dfdc30db5846ace2b125388621d4: Use `git lfs logs last` to view the log.
npm ERR! git clone C:\Users\bmahsman\AppData\Roaming\npm-cache\_git-remotes\git-gitlab-com-brynn-mahsman-bubblegum-git-dba3c97871efd24f1aa52ecaee11cc5f C:\Users\bmahsman\AppData\Local\Temp\npm-11440-88a1a8aa\git-cache-6dfa4264275fe7084b621e161730286b\df5df227ff72dfdc30db5846ace2b125388621d4: error: external filter git-lfs smudge %f failed 2
npm ERR! git clone C:\Users\bmahsman\AppData\Roaming\npm-cache\_git-remotes\git-gitlab-com-brynn-mahsman-bubblegum-git-dba3c97871efd24f1aa52ecaee11cc5f C:\Users\bmahsman\AppData\Local\Temp\npm-11440-88a1a8aa\git-cache-6dfa4264275fe7084b621e161730286b\df5df227ff72dfdc30db5846ace2b125388621d4: error: external filter git-lfs smudge %f failed
npm ERR! git clone C:\Users\bmahsman\AppData\Roaming\npm-cache\_git-remotes\git-gitlab-com-brynn-mahsman-bubblegum-git-dba3c97871efd24f1aa52ecaee11cc5f C:\Users\bmahsman\AppData\Local\Temp\npm-11440-88a1a8aa\git-cache-6dfa4264275fe7084b621e161730286b\df5df227ff72dfdc30db5846ace2b125388621d4: fatal: bubblegum.png: smudge filter lfs failed
npm ERR! git clone C:\Users\bmahsman\AppData\Roaming\npm-cache\_git-remotes\git-gitlab-com-brynn-mahsman-bubblegum-git-dba3c97871efd24f1aa52ecaee11cc5f C:\Users\bmahsman\AppData\Local\Temp\npm-11440-88a1a8aa\git-cache-6dfa4264275fe7084b621e161730286b\df5df227ff72dfdc30db5846ace2b125388621d4: warning: Clone succeeded, but checkout failed.
npm ERR! git clone C:\Users\bmahsman\AppData\Roaming\npm-cache\_git-remotes\git-gitlab-com-brynn-mahsman-bubblegum-git-dba3c97871efd24f1aa52ecaee11cc5f C:\Users\bmahsman\AppData\Local\Temp\npm-11440-88a1a8aa\git-cache-6dfa4264275fe7084b621e161730286b\df5df227ff72dfdc30db5846ace2b125388621d4: You can inspect what was checked out with 'git status'
npm ERR! git clone C:\Users\bmahsman\AppData\Roaming\npm-cache\_git-remotes\git-gitlab-com-brynn-mahsman-bubblegum-git-dba3c97871efd24f1aa52ecaee11cc5f C:\Users\bmahsman\AppData\Local\Temp\npm-11440-88a1a8aa\git-cache-6dfa4264275fe7084b621e161730286b\df5df227ff72dfdc30db5846ace2b125388621d4: and retry the checkout with 'git checkout -f HEAD'
npm ERR! git clone C:\Users\bmahsman\AppData\Roaming\npm-cache\_git-remotes\git-gitlab-com-brynn-mahsman-bubblegum-git-dba3c97871efd24f1aa52ecaee11cc5f C:\Users\bmahsman\AppData\Local\Temp\npm-11440-88a1a8aa\git-cache-6dfa4264275fe7084b621e161730286b\df5df227ff72dfdc30db5846ace2b125388621d4:
npm ERR! git clone C:\Users\bmahsman\AppData\Roaming\npm-cache\_git-remotes\git-gitlab-com-brynn-mahsman-bubblegum-git-dba3c97871efd24f1aa52ecaee11cc5f C:\Users\bmahsman\AppData\Local\Temp\npm-11440-88a1a8aa\git-cache-6dfa4264275fe7084b621e161730286b\df5df227ff72dfdc30db5846ace2b125388621d4:
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "gitlab:brynn.mahsman/bubblegum"
npm ERR! node v5.4.1
npm ERR! npm  v3.3.12
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true clone C:\Users\bmahsman\AppData\Roaming\npm-cache\_git-remotes\git-gitlab-com-brynn-mahsman-bubblegum-git-dba3c97871efd24f1aa52ecaee11cc5f C:\Users\bmahsman\AppData\Local\Temp\npm-11440-88a1a8aa\git-cache-6dfa4264275fe7084b621e161730286b\df5df227ff72dfdc30db5846ace2b125388621d4
npm ERR! Cloning into 'C:\Users\bmahsman\AppData\Local\Temp\npm-11440-88a1a8aa\git-cache-6dfa4264275fe7084b621e161730286b\df5df227ff72dfdc30db5846ace2b125388621d4'...
npm ERR! done.
npm ERR! Downloading bubblegum.png (382.76 KB)
npm ERR! Error accessing media: bubblegum.png (27139a2b3acc5b2eb3dd3785c6b91c8055b761125a5465ff74215b6cbc5872a3)
npm ERR!
npm ERR! Errors logged to .git\lfs\objects\logs\20160114T104223.4109496.log
npm ERR! Use `git lfs logs last` to view the log.
npm ERR! error: external filter git-lfs smudge %f failed 2
npm ERR! error: external filter git-lfs smudge %f failed
npm ERR! fatal: bubblegum.png: smudge filter lfs failed
npm ERR! warning: Clone succeeded, but checkout failed.
npm ERR! You can inspect what was checked out with 'git status'
npm ERR! and retry the checkout with 'git checkout -f HEAD'
npm ERR!
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\develop\projects\tmp\bubbletest\npm-debug.log

[10:53:29 AM] /c/develop/projects
$ cat 'C:\Users\bmahsman\AppData\Local\Temp\npm-11440-88a1a8aa\git-cache-6dfa4264275fe7084b621e161730286b\df5df227ff72dfdc30db5846ace2b125388621d4'/'.git\lfs\objects\logs\20160114T104 223.4109496.log'
git-lfs/1.1.0 (GitHub; windows amd64; go 1.5.1; git 258acf1)
git version 2.6.4.windows.1

$ git-lfs.exe smudge bubblegum.png
Error accessing media: bubblegum.png (27139a2b3acc5b2eb3dd3785c6b91c8055b761125a5465ff74215b6cbc5872a3)

Post c:\Users\bmahsman\AppData\Roaming\npm-cache\_git-remotes\git-gitlab-com-brynn-mahsman-bubblegum-git-dba3c97871efd24f1aa52ecaee11cc5f.git/info/lfs: unsupported protocol scheme "c" goroutine 1 [running]:
github.com/github/git-lfs/lfs.Stack(0x0, 0x0, 0x0)
        C:/Users/techn/go/src/github.com/github/git-lfs/lfs/errors.go:557 +0x87
github.com/github/git-lfs/commands.logPanicToWriter(0xff41e8, 0xc0821280f8, 0x11c0500, 0xc08210a8f0)
        C:/Users/techn/go/src/github.com/github/git-lfs/commands/commands.go:184 +0xf86
github.com/github/git-lfs/commands.logPanic(0x11c0500, 0xc08210a8f0, 0x0, 0x0)
        C:/Users/techn/go/src/github.com/github/git-lfs/commands/commands.go:148 +0x428
github.com/github/git-lfs/commands.handlePanic(0x11c0500, 0xc08210a8f0, 0x0, 0x0)
        C:/Users/techn/go/src/github.com/github/git-lfs/commands/commands.go:123 +0x55
github.com/github/git-lfs/commands.LoggedError(0x11c0500, 0xc08210a8f0, 0x967a80, 0x1e, 0xc08206fc78, 0x2, 0x2)
        C:/Users/techn/go/src/github.com/github/git-lfs/commands/commands.go:73 +0x89
github.com/github/git-lfs/commands.smudgeCommand(0xb67f60, 0xc08200bab0, 0x1, 0x1)
        C:/Users/techn/go/src/github.com/github/git-lfs/commands/command_smudge.go:77 +0xd90
github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra.(*Command).execute(0xb67f60, 0xc08200ba00, 0x1, 0x1, 0x0, 0x0)
        C:/Users/techn/go/src/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:477 +0x40a
github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra.(*Command).Execute(0xb68fa0, 0x0, 0x0)
        C:/Users/techn/go/src/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:551 +0x59a
github.com/github/git-lfs/commands.Run()
        C:/Users/techn/go/src/github.com/github/git-lfs/commands/commands.go:88 +0x2a
main.main()
        C:/Users/techn/go/src/github.com/github/git-lfs/git-lfs.go:34 +0x135

ENV:
LocalWorkingDir=.
LocalGitDir=.git
LocalGitStorageDir=.git
LocalMediaDir=.git\lfs\objects
TempDir=.git\lfs\tmp
ConcurrentTransfers=3
BatchTransfer=true
GIT_ASKPASS=echo
GIT_CONFIG_PARAMETERS='core.longpaths=true'
GIT_DIR=.git
GIT_WORK_TREE=.
```

I am using Windows 7, git 2.6.4.windows.1, and npm 3.3.12. `gitlab:brynn.mahsman/bubblegum` is a public repository with a single binary asset. You can use this repo to try and reproduce the issue.

---

Setting `loglevel` to `verbose`, I see that first `npm install` makes a bare clone using the `--mirror` flag to `npm-cache/`. It then attempts a clone from the bare repository to another folder in `npm-cache/`, which appears to be the basis for the files that do into `node_modules/`. Why does `npm install` make a mirror first? Is it that you cannot `git clone` a specific commit, so to avoid having to checkout `HEAD` first to get to the needed commit, a local bare clone is created?

A workaround is to add a `.gitconfig` to the repository that contains the following:

```
[lfs]
    url = https://gitlab.com/brynn.mahsman/bubblegum.git/info/lfs
```

And then when `npm install` goes to clone from the local bare clone, `git-lfs` uses the `.gitconfig` to get the `lfs.url`. However, this workaround appears to disable batch mode with Git LFS, which increases the amount of time it takes to complete the clone and `npm install`.

---

This is a formal bug report/feature request stemming from the support issue npm/npm#10857. There is some discussion of this issue on the git-lfs project page at github/git-lfs#899.

**Comment by othiym23** [comment]
We're interested in supporting LFS, but the team isn't likely to be available to work on this ourselves for a while. If somebody wanted to start a patch to npm to get this in there, we would be happy to work with them to get it merged to both `npm@3` and `npm@lts`.

**Comment by feugy** [comment]
Hi there.

We got the same problem here, but workaround provided by zxcpoiu didn't work due to authentication (we're using a private repo).

After some research on [Git Enterprise Doc](https://help.github.com/enterprise/2.7/admin/guides/installation/git-large-file-storage-on-github-enterprise/), we found that providing a `.lfsconfig` file on the repo that has lfs items solved the issue:

```
[remote "origin"]
    lfsurl = ssh://git@github.com/user/repo.git
```

**Comment by zxcpoiu** [comment]
thanks @feugy 

I'm wondering that if you only use `.lfsconfig` in your project, but the user who runs `npm install` **without** `gitlfs` installed locally,  would it downloads files from git-lfs server correctly?

I'm not sure, but from my recall if correctly, seems `npm` doesn't recognize `.lfsconfig` if `git-lfs` client not installed locally.

**side note:**
if you are owner/collaborator of a project with some files stored on `git-fls`, when you want to update/push these files, you mmay encounter authentication issues.

my workaround would be:

1. just delete `.gitconfig` with `rm .gitconfig` before push commits
2. after pushed, restore with `git checkout -- .gitconfig`

if your forked-project is using `git-lfs`, you may need to add an additional commit which changes `lfsurl` to your forked project's link.

**Comment by zxcpoiu** [comment]
oh by the way, the solution is provided by @bmahsman actually. many thanks!

**Comment by feugy** [comment]
@zxcpoiu, about users that check out your project without having git lfs install, they simply won't have the actual files. Files will be present, but will only contain a pointer to the LFS version.

This will be the same, whatever configuration file you're using: .gitconfig or .lfsconfig.

About @bmahsman workaround, it works fine if you're using public repos that doesn't require authentication. 
As I mentioned earlier, the solution we found is suitable for both public and private repos.

About your side note, you're absolutely right: collaborators that fork the project will need to change the config file (whatever it is), which makes those solutions only temporary workarounds.

The best solution would be to fix npm...

**Comment by zxcpoiu** [comment]
thanks for sharing @feugy !
