### ISSUE TITLE
win7 events.js:141 throw er; //Unhandled 'error' event

### ISSUE THREAD

**Issue by OneNewLife** [npm/npm#11168]
it can work sometimes,but frequently throw out error when I compiled sass automatically,it made me wanna die.please help me.
bug:

```
0 info it worked if it ends with ok
1 verbose cli [ 'E:\ToolsForCoder\Node.js\node.exe',
1 verbose cli 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js',
1 verbose cli 'start' ]
2 info using npm@3.5.2
3 info using node@v4.2.4
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle test@1.0.0~prestart: test@1.0.0
6 silly lifecycle test@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle test@1.0.0~start: test@1.0.0
8 verbose lifecycle test@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle test@1.0.0~start: PATH: C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;E:\Projects\weka\node_modules.bin;C:\Users\Administrator\AppData\Roaming\npm;E:\ToolsForCoder\Node.js\;F:\Ruby22\bin;F:\Java\jdk\bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows7Master;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v1.0\;C:\Windows\system32\config\systemprofile.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;F:\Matlab\runtime\win64;F:\Matlab\bin;F:\Matlab\polyspace\bin;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;F:\Sublime Text 3\Sublime Text 3;E:\ToolsForCoder\Node.js\;C:\Users\Administrator\AppData\Roaming\npm
10 verbose lifecycle test@1.0.0~start: CWD: E:\Projects\weka
11 silly lifecycle test@1.0.0~start: Args: [ '/d /s /c', 'gulp' ]
12 silly lifecycle test@1.0.0~start: Returned: code: 1 signal: null
13 info lifecycle test@1.0.0~start: Failed to exec start script
14 verbose stack Error: test@1.0.0 start: gulp
14 verbose stack Exit status 1
14 verbose stack at EventEmitter. (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:232:16)
14 verbose stack at emitTwo (events.js:87:13)
14 verbose stack at EventEmitter.emit (events.js:172:7)
14 verbose stack at ChildProcess. (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack at emitTwo (events.js:87:13)
14 verbose stack at ChildProcess.emit (events.js:172:7)
14 verbose stack at maybeClose (internal/child_process.js:818:16)
14 verbose stack at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid test@1.0.0
16 verbose cwd E:\Projects\weka
17 error Windows_NT 6.1.7601
18 error argv "E:\ToolsForCoder\Node.js\node.exe" "C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "start"
19 error node v4.2.4
20 error npm v3.5.2
21 error code ELIFECYCLE
22 error test@1.0.0 start: gulp
22 error Exit status 1
23 error Failed at the test@1.0.0 start script 'gulp'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the test package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error gulp
23 error You can get information on how to open an issue for this project with:
23 error npm bugs test
23 error Or if that isn't available, you can get their info via:
23 error npm owner ls test
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by OneNewLife** [comment]
hello.anyone here?

**Comment by magick93** [comment]
Am getting the same error on Ubuntu 15.10.

**Comment by ovanderzee** [comment]
I am having the same error message from MacOSX. I am running a sequence of gulp.src streams on various patterns.
