### ISSUE TITLE
npm fails while making (make) openstreetmap/iD

### ISSUE THREAD

**Issue by manfredbrandl** [npm/npm#11190]
See https://github.com/openstreetmap/iD/issues/2917

```
manfred@xxx:~/src$ git clone https://github.com/openstreetmap/iD iD >out 2>err
manfred@xxx:~/src$ cd iD
manfred@xxx:~/src/iD$ make >>../out 2>>../err
manfred@xxx:~/src/iD$ tail ../err
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/manfred/src/iD
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! code 128
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/manfred/src/iD/npm-debug.log
npm ERR! not ok code 0
make: *** [node_modules/.install] Error 1
manfred@xxx:~/src/iD$ tail -30 npm-debug.log 
5500 silly lockFile 5ad0820f-ry-npmjs-org-maki-maki-0-5-0-tgz https://registry.npmjs.org/maki/-/maki-0.5.0.tgz
5501 silly lockFile 5ad0820f-ry-npmjs-org-maki-maki-0-5-0-tgz https://registry.npmjs.org/maki/-/maki-0.5.0.tgz
5502 silly lockFile 8616604d-maki-0-5-0 maki@0.5.0
5503 silly lockFile 8616604d-maki-0-5-0 maki@0.5.0
5504 error git clone git://github.com/osmlab/editor-imagery-index.git Cloning into bare repository '/home/manfred/.npm/_git-remotes/git-github-com-osmlab-editor-imagery-index-git-0dd189be'...
5504 error git clone git://github.com/osmlab/editor-imagery-index.git fatal: unable to connect to github.com:
5504 error git clone git://github.com/osmlab/editor-imagery-index.git github.com[0: 192.30.252.128]: errno=Connection timed out
5505 silly lockFile 0dd189be--osmlab-editor-imagery-index-git git://github.com/osmlab/editor-imagery-index.git
5506 error Error: Command failed: Cloning into bare repository '/home/manfred/.npm/_git-remotes/git-github-com-osmlab-editor-imagery-index-git-0dd189be'...
5506 error fatal: unable to connect to github.com:
5506 error github.com[0: 192.30.252.128]: errno=Connection timed out
5506 error
5506 error
5506 error     at ChildProcess.exithandler (child_process.js:637:15)
5506 error     at ChildProcess.EventEmitter.emit (events.js:98:17)
5506 error     at maybeClose (child_process.js:743:16)
5506 error     at Socket.<anonymous> (child_process.js:956:11)
5506 error     at Socket.EventEmitter.emit (events.js:95:17)
5506 error     at Pipe.close (net.js:466:12)
5507 error If you need help, you may report this log at:
5507 error     <http://github.com/isaacs/npm/issues>
5507 error or email it to:
5507 error     <npm-@googlegroups.com>
5508 error System Linux 3.16.0-57-generic
5509 error command "/usr/bin/nodejs" "/usr/bin/npm" "install"
5510 error cwd /home/manfred/src/iD
5511 error node -v v0.10.25
5512 error npm -v 1.3.10
5513 error code 128
5514 verbose exit [ 1, true ]
manfred@xxx:~/src$ 
```

**Comment by KenanY** [comment]
@manfredbrandl 

```
5506 error github.com[0: 192.30.252.128]: errno=Connection timed out
```

Looks like an issue with your internet connection.

Also, `npm@1.3` is no longer supported.

**Comment by othiym23** [comment]
Closing as resolved by @KenanY's answer – update to a newer version of npm, and make sure that the host from which you're running the install can connect to github.com, and you should be set.
