### ISSUE TITLE
npm update -g breaks npm

### ISSUE THREAD

**Issue by moander** [npm/npm#11195]
```
$ nvm install v5.4.1
$ nvm use v5.4.1
$ npm update -g
```

Exception thrown after update:
```
$ npm
module.js:327
    throw err;
    ^

Error: Cannot find module 'npmlog'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /Users/moander/.nvm/versions/node/v5.4.1/lib/node_modules/npm/bin/npm-cli.js:20:13
    at Object.<anonymous> (/Users/moander/.nvm/versions/node/v5.4.1/lib/node_modules/npm/bin/npm-cli.js:76:3)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
```

#### Same but different problem using docker:

```
$ docker run -it node:5.4.1 bash

$ npm update -g


npm ERR! Linux 4.1.13-boot2docker
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "update" "-g"
npm ERR! node v5.4.1
npm ERR! npm  v3.3.12
npm ERR! path /usr/local/lib/node_modules/npm
npm ERR! code EXDEV
npm ERR! errno -18
npm ERR! syscall rename

npm ERR! EXDEV: cross-device link not permitted, rename '/usr/local/lib/node_modules/npm' -> '/usr/local/lib/node_modules/.npm.DELETE'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /npm-debug.log
```

/usr/local/lib/node_modules is gone
```
$ npm
bash: /usr/local/bin/npm: No such file or directory
```

```
$ ls -l /usr/local/bin/
total 24584
-rwxrwxr-x 1 500 500 25171577 Jan 12 20:59 node
lrwxrwxrwx 1 500 500       38 Jan 12 20:59 npm -> ../lib/node_modules/npm/bin/npm-cli.js
```

```
$ ls /usr/local/lib/
python2.7
```

**Comment by moander** [comment]
Same result using node 5.4.0 (npm 3.3.12)

node 4.2.4 (npm 2.14.12) seems to be working fine.

**Comment by kgryte** [comment]
See https://github.com/npm/npm/issues/11088

**Comment by gitawego** [comment]
got the same regression as well, just do not update npm after upgraded node.

**Comment by ashleygwilliams** [comment]
hi! this was fixed with npm `3.5.5`. closing. if you have further trouble, please open a new issue.

**Comment by Prajwalstha** [comment]
thanks

**Comment by firstpixel** [comment]
Having same issue [module.js:327
    throw err;]

node  v4.4.3
npm  v3.8.6

**Comment by firstpixel** [comment]
My mistake, just updated the modules and now its working.
