### ISSUE TITLE
Failing to run after installing ionic-cli

### ISSUE THREAD

**Issue by rosco9awj** [npm/npm#11207]
I am trying to run ionic run android and i am getting this error.
I am trying to run ```ionc run --device``` and installing Cordova plugins
I just upgraded my ionic cli, reinstalled npm, deleted node modules cleared the cache and 
```
module.js:340
    throw err;
    ^

Error: Cannot find module 'lodash/object/assign'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/xmlbuilder/lib/index.js:5:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/xmlbuilder/lib/index.js:14:4)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
```

**Comment by rosco9awj** [comment]
I am posting this here because I believe this is an issue with npm and node rather than the ionic cli.  I just recently updated node and then I got this issue.

**Comment by jdalton** [comment]
Are you using npm 3? Have you tried with npm 2.

I know https://www.npmjs.com/package/xmlbuilder has lodash v4 as a dep but has correct module paths (so shouldn't cause the issue seen here).

**Comment by rosco9awj** [comment]
Yes, right now I am using version 3.5.3.  Would it be helpful to rollback to an earlier versions?

**Comment by jdalton** [comment]
>  Would it be helpful to rollback to an earlier versions?

Couldn't hurt to narrow things down.

**Comment by rosco9awj** [comment]
The issue is now resolved. These are the steps I took:

1. Rolled back npm to verison 2.14.12
2. Updated xmlbuilder (I don't think this helped much, I was just trying everything)
3. Updated node from v2.4.4 to v2.4.6
4. Reinstalled ionic and cordova.  This was the step that cleared the error, but I had already tried this before so one of the steps above must have helped out.

Thanks jdalton.
