### ISSUE TITLE
NPM not letting me publish package even when I have permission

### ISSUE THREAD

**Issue by kevincol54** [npm/npm#11243]
I am logged in and have verified by running `npm whoami`... which returns kevincol54

I initially tried to publish the new module, but in the middle of it working, i accidentally hit `control-c`.

I have logged out and logged back in and tried publish the module but everytime I get the following error:

I have removed my local username from the below message.

``````
0 info it worked if it ends with ok
1 verbose cli [ '/Users/.nvm/versions/node/v4.2.4/bin/node',
1 verbose cli   '/Users/.nvm/versions/node/v4.2.4/bin/npm',
1 verbose cli   'publish' ]
2 info using npm@2.14.12
3 info using node@v4.2.4
4 verbose publish [ '.' ]
5 silly cache add args [ '.', null ]
6 verbose cache add spec .
7 silly cache add parsed spec Result {
7 silly cache add   raw: '.',
7 silly cache add   scope: null,
7 silly cache add   name: null,
7 silly cache add   rawSpec: '.',
7 silly cache add   spec: '/Users/Genome/increased_risk_factor_malignant_melanoma-gs195',
7 silly cache add   type: 'directory' }
8 verbose addLocalDirectory /Users/.npm/genoset-195/1.0.0/package.tgz not in flight; packing
9 verbose tar pack [ '/Users/.npm/genoset-195/1.0.0/package.tgz',
9 verbose tar pack   '/Users/Genome/increased_risk_factor_malignant_melanoma-gs195' ]
10 verbose tarball /Users/.npm/genoset-195/1.0.0/package.tgz
11 verbose folder /Users/Genome/increased_risk_factor_malignant_melanoma-gs195
12 info prepublish genoset-195@1.0.0
13 verbose addLocalTarball adding from inside cache /Users/.npm/genoset-195/1.0.0/package.tgz
14 silly cache afterAdd genoset-195@1.0.0
15 verbose afterAdd /Users/.npm/genoset-195/1.0.0/package/package.json not in flight; writing
16 verbose afterAdd /Users/.npm/genoset-195/1.0.0/package/package.json written
17 silly publish { name: 'genoset-195',
17 silly publish   version: '1.0.0',
17 silly publish   description: 'Your haplotype is a very significant risk factor for malignant melanoma',
17 silly publish   main: 'index.js',
17 silly publish   directories: { test: 'tests' },
17 silly publish   repository:
17 silly publish    { type: 'git',
17 silly publish      url: 'git+https://github.com/kevincol54/genoset-195.git' },
17 silly publish   scripts:
17 silly publish    { test: 'tap ./tests/*.js | tap-spec',
17 silly publish      lint: 'standard *.js tests/*.js' },
17 silly publish   keywords:
17 silly publish    [ 'genome',
17 silly publish      'genoset',
17 silly publish      'genes',
17 silly publish      'dna',
17 silly publish      'gs195',
17 silly publish      'genoset-195',
17 silly publish      'malignant melanoma',
17 silly publish      'melanoma',
17 silly publish      'significant risk' ],
17 silly publish   author:
17 silly publish    { name: 'Kevin Collins',
17 silly publish      email: 'kevincol54@gmail.com',
17 silly publish      url: 'https://github.com/kevincol54' },
17 silly publish   license: 'MIT',
17 silly publish   devDependencies: { standard: '^5.4.1', tap: '^5.0.1', 'tap-spec': '^4.1.1' },
17 silly publish   dependencies: { gql: '^1.1.0' },
17 silly publish   engines: { node: '4.2.4' },
17 silly publish   readme: '# genoset-195\n\nThis script determines if your haplotype is a very significant risk factor for malignant melanoma, as per [gs195](http://www.snpedia.com/index.php/Gs195)\n\n## Compatibility\n\nThis genoset is to be used with DNA-JSON. See [dna2json](https://github.com/genomejs/dna2json) for more information.\n\n## Usage\n\n```js\nvar increasedRisk = require(\'genoset-195\');\nvar dna = require(\'./dna.json\');\n\nconsole.log(increasedRisk(dna));\n// → `true` or `false`\n```\n\n## Contributions\n\nThis Project follows the StandardJS style guide.\n\n[![js-standard-style](https://cdn.rawgit.com/feross/standard/master/badge.svg)](https://github.com/feross/standard)\n\nTo Contribute:\n\n- Clone Repo\n- `npm install`\n- Write Code\n- Write Test(s)\n- Submit Pull Request\n\n\n## Author\n\n| [![twitter/kevco54](https://gravatar.com/avatar/c3f0cac49ad7d267cb58499a86bfdd19)](https://twitter.com/kevco54 "Follow @kevco54 on Twitter") |\n|---|\n| [Kevin Collins](https://iamkevin.co/) |\n\n## License\n\n_genoset-195_ is available under the [MIT](https://mths.be/mit) license.\n',
17 silly publish   readmeFilename: 'README.md',
17 silly publish   gitHead: 'e0ef0a0dddc852f6497836892366be29579d360b',
17 silly publish   bugs: { url: 'https://github.com/kevincol54/genoset-195/issues' },
17 silly publish   homepage: 'https://github.com/kevincol54/genoset-195#readme',
17 silly publish   _id: 'genoset-195@1.0.0',
17 silly publish   _shasum: '493deb993745170bb5bdc795daee3657322fc71e',
17 silly publish   _from: '.' }
18 verbose getPublishConfig undefined
19 silly mapToRegistry name genoset-195
20 silly mapToRegistry using default registry
21 silly mapToRegistry registry https://registry.npmjs.org/
22 silly mapToRegistry uri https://registry.npmjs.org/genoset-195
23 verbose publish registryBase https://registry.npmjs.org/
24 silly publish uploading /Users/.npm/genoset-195/1.0.0/package.tgz
25 verbose request uri https://registry.npmjs.org/genoset-195
26 verbose request sending authorization for write operation
27 info attempt registry request try #1 at 8:56:41 PM
28 verbose request using bearer token for auth
29 verbose request id ed3b4f579607847a
30 http request PUT https://registry.npmjs.org/genoset-195
31 http 403 https://registry.npmjs.org/genoset-195
32 verbose headers { 'content-type': 'application/json',
32 verbose headers   'cache-control': 'max-age=300',
32 verbose headers   'content-length': '103',
32 verbose headers   'accept-ranges': 'bytes',
32 verbose headers   date: 'Fri, 22 Jan 2016 01:56:41 GMT',
32 verbose headers   via: '1.1 varnish',
32 verbose headers   connection: 'keep-alive',
32 verbose headers   'x-served-by': 'cache-atl6222-ATL',
32 verbose headers   'x-cache': 'MISS',
32 verbose headers   'x-cache-hits': '0',
32 verbose headers   'x-timer': 'S1453427801.142493,VS0,VE436' }
33 verbose request invalidating /Users/.npm/registry.npmjs.org/genoset-195 on PUT
34 error publish Failed PUT 403
35 verbose stack Error: You do not have permission to publish 'genoset-195'. Are you logged in as the correct user? : genoset-195
35 verbose stack     at makeError (/Users/.nvm/versions/node/v4.2.4/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
35 verbose stack     at CachingRegistryClient.<anonymous> (/Users/.nvm/versions/node/v4.2.4/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:252:14)
35 verbose stack     at Request._callback (/Users/.nvm/versions/node/v4.2.4/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
35 verbose stack     at Request.self.callback (/Users/.nvm/versions/node/v4.2.4/lib/node_modules/npm/node_modules/request/request.js:198:22)
35 verbose stack     at emitTwo (events.js:87:13)
35 verbose stack     at Request.emit (events.js:172:7)
35 verbose stack     at Request.<anonymous> (/Users/.nvm/versions/node/v4.2.4/lib/node_modules/npm/node_modules/request/request.js:1082:10)
35 verbose stack     at emitOne (events.js:82:20)
35 verbose stack     at Request.emit (events.js:169:7)
35 verbose stack     at IncomingMessage.<anonymous> (/Users/.nvm/versions/node/v4.2.4/lib/node_modules/npm/node_modules/request/request.js:1009:12)
36 verbose statusCode 403
37 verbose pkgid genoset-195
38 verbose cwd /Users/Genome/increased_risk_factor_malignant_melanoma-gs195
39 error Darwin 15.2.0
40 error argv "/Users/.nvm/versions/node/v4.2.4/bin/node" "/Users/.nvm/versions/node/v4.2.4/bin/npm" "publish"
41 error node v4.2.4
42 error npm  v2.14.12
43 error code E403
44 error You do not have permission to publish 'genoset-195'. Are you logged in as the correct user? : genoset-195
45 error If you need help, you may report this error at:
45 error     <https://github.com/npm/npm/issues>
46 verbose exit [ 1, true ]
``````

**Comment by kuzmeig1** [comment]
The same here
