### ISSUE TITLE
SSH URLs not supported for dedupe or shrinkwrap

### ISSUE THREAD

**Issue by pornel** [npm/npm#11276]
```sh
npm --version
3.6.0
npm prune 
# all ok, nothing pruned
npm shrinkwrap
npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "shrinkwrap"
npm ERR! node v5.4.0
npm ERR! npm  v3.6.0

npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! extraneous: circular-list@1.0.2 /…/node_modules/circular-list
npm ERR! extraneous: fastft@11.3.0 /…/node_modules/fastft
npm ERR! extraneous: interaction-bridge@0.2.4 /…/node_modules/interaction-bridge
npm ERR! extraneous: js-abbreviate@1.1.1 /…/node_modules/js-abbreviate
npm ERR! extraneous: js-utilities@0.1.3 /…/node_modules/js-utilities
npm ERR! extraneous: pinchzoom@0.8.2 /…/node_modules/pinchzoom
npm ERR! extraneous: policyengine-client-js@0.2.0 /…/node_modules/policyengine-client-js
npm ERR! extraneous: promisecache@1.0.0 /…/node_modules/promisecache
npm ERR! extraneous: storage@0.1.8 /…/node_modules/storage
npm ERR! extraneous: superagent-extend@0.0.2 /…/node_modules/superagent-extend
npm ERR! extraneous: wrapper-bridge@1.2.0 /…/node_modules/wrapper-bridge
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /…/npm-debug.log
```

^ all of the "extraneous" packages listed above are required in `package.json` in format `ssh://git@private.server.behind.firewall:7999/project-name/package-name.git#vversion`.

```sh
npm dedupe
npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "dedupe"
npm ERR! node v5.4.0
npm ERR! npm  v3.6.0

npm ERR! Unsupported URL Type: ssh://git@private.server.behind.firewall:7999/project-name/package-name.git#v1.0.2
```

From the debug log:

> 0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'dedupe' ]
2 info using npm@3.6.0
3 info using node@v5.4.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly dedupe normalizeTree
8 silly install normalizeTree
9 silly loadCurrentTree Finishing
10 silly loadIdealTree Starting
11 silly install loadIdealTree
12 silly cloneCurrentTree Starting
13 silly install cloneCurrentTreeToIdealTree
14 silly cloneCurrentTree Finishing
15 silly loadAllDepsIntoIdealTree Starting
16 verbose stack Error: Unsupported URL Type: ssh://git@private.server.behind.firewall:7999/project-name/package-name.git#v1.0.2
16 verbose stack     at parseUrl (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:169:13)
16 verbose stack     at npa (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:75:12)
16 verbose stack     at isProdDep (/usr/local/lib/node_modules/npm/lib/install/deps.js:57:10)
16 verbose stack     at isDep (/usr/local/lib/node_modules/npm/lib/install/deps.js:37:19)
16 verbose stack     at addRequiredDep (/usr/local/lib/node_modules/npm/lib/install/deps.js:126:8)
16 verbose stack     at resolveWithExistingModule (/usr/local/lib/node_modules/npm/lib/install/deps.js:405:3)
16 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/deps.js:370:7
16 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
16 verbose stack     at Array.forEach (native)
16 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
17 verbose cwd /…/ft-app
18 error Darwin 15.2.0
19 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "dedupe"
20 error node v5.4.0
21 error npm  v3.6.0
22 error Unsupported URL Type: ssh://git@private.server.behind.firewall:7999/project-name/package-name.git#v1.0.2
23 error If you need help, you may report this error at:
23 error     <https://github.com/npm/npm/issues>
24 verbose exit [ 1, true ]

Shrinkwrap debug log has the same info as quoted above except:

> 4 verbose stack     at shrinkwrap_ (/usr/local/lib/node_modules/npm/lib/shrinkwrap.js:101:15)
4 verbose stack     at /usr/local/lib/node_modules/npm/lib/shrinkwrap.js:36:5
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/iferr/index.js:13:50
4 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/deps.js:121:5
4 verbose stack     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:7:26)
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
4 verbose stack     at cb (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
4 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/deps.js:121:5
4 verbose stack     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:7:26)
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7

**Comment by pornel** [comment]
I've noticed it's only a symptom of another problem: #11277
