### ISSUE TITLE
verbose unsafe-perm in lifecycle true

### ISSUE THREAD

**Issue by allces** [npm/npm#11334]
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@2.14.12
3 info using node@v4.2.4
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info predev webpack-demo@1.0.0
6 info dev webpack-demo@1.0.0
7 verbose unsafe-perm in lifecycle true
8 info webpack-demo@1.0.0 Failed to exec dev script
9 verbose stack Error: webpack-demo@1.0.0 dev: `RUNMODE=devserver CLEAN=false webpack-dev-server --port 8086 --progress --inline`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:818:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid webpack-demo@1.0.0
11 verbose cwd E:\duck\workspaces\meicanyun-parent\meicanyun-mp-web\src\main\assets1
12 error Windows_NT 10.0.10240
13 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
14 error node v4.2.4
15 error npm  v2.14.12
16 error code ELIFECYCLE
17 error webpack-demo@1.0.0 dev: `RUNMODE=devserver CLEAN=false webpack-dev-server --port 8086 --progress --inline`
17 error Exit status 1
18 error Failed at the webpack-demo@1.0.0 dev script 'RUNMODE=devserver CLEAN=false webpack-dev-server --port 8086 --progress --inline'.
18 error This is most likely a problem with the webpack-demo package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     RUNMODE=devserver CLEAN=false webpack-dev-server --port 8086 --progress --inline
18 error You can get their info via:
18 error     npm owner ls webpack-demo
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```
system: window 10
thx

**Comment by othiym23** [comment]
Here's the important bits of that debug log:

```
18 error Failed at the webpack-demo@1.0.0 dev script 'RUNMODE=devserver CLEAN=false webpack-dev-server --port 8086 --progress --inline'.
18 error This is most likely a problem with the webpack-demo package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     RUNMODE=devserver CLEAN=false webpack-dev-server --port 8086 --progress --inline
18 error You can get their info via:
18 error     npm owner ls webpack-demo
18 error There is likely additional logging output above.
```

For whatever reason, the `webpack-dev-server` script failed (check to see what it's printing in the console, as that's not (currently) included in `npm-debug.log`), which is something to take up with the `webpack-demo` developers (if you can't figure it out yourself). Because this isn't an issue with npm itself, I'm going to close this issue. Good luck getting things sorted out, and thanks for your time!
