### ISSUE TITLE
Shrinkwrap bug: invalid and extraneous errors

### ISSUE THREAD

**Issue by fresheneesz** [npm/npm#11347]
I have this package.json that `npm install`s from scratch fine, and yet shrinkwrapping fails:

```
{
    "name": "test",
    "version": "0.1.0",
    "description": "test",
    "repository":"",
    "license":"UNLICENSED",
    "private": true,
    "readme":"",
    "dependencies": {
        "fibers":"1.0.7",
        "websocket":"1.0.10",
        "proto":"1.0.19",
        "trimArguments":"https://github.com/fresheneesz/trimArguments/archive/c9c023c9ff1e0aec4b67370a80a92dacadcf8b11.tar.gz",
        "nodejsUtils":"https://github.com/fresheneesz/nodejsUtils/archive/5fffd9398e363c5f131484fc795cfd65f74275ef.tar.gz",
        "moment":"2.11.0",
        "mongoskin":"2.0.3",
            "mongodb": "~2.0",
                "kerberos":"~0.0",
        "unzip":"0.1.11",
        "colors":"*",
        "secure-random":"1.1.1",
        "scrypt":"5.1.1",

        "deadunit": "5.1.12",
        "syn": "0.1.2",
        "incremental-installer-maker": "0.0.4",
        "incremental-installer": "1.1.0",
        "installer-maker": "1.1.2",
        "chokidar":"1.2.0",
        "buffer-equal":"1.0.0",
        "stream-equal": "0.1.7",
        "node-fs":"0.1.7",
        "graceful-fs":"4.1.2",
        "ncp":"2.0.0",
        "cpr":"1.0.0",
        "ssh2":"0.4.13",
        "combined-stream":"1.0.5",
        "http-proxy":"1.12.0",
        "forever":"0.15.1",
        "longjohn":"0.2.11",
        "pem":"1.8.1",
        "mongo-parse":"1.0.4",
        "prompt":"0.2.14",
        "semver":"5.1.0",

        "webpack":"1.12.9",
        "url-loader":"0.5.7",
            "file-loader":"0.8.5",
        "image-size-loader":"0.7.0",
        "async-future":"1.0.6",
        "scriptjs":"2.5.8",
        "hashmap":"2",
        "cookies-js":"1.2.2",
        "lodash":"*",
        "grapetree":"1.1.1",
        "gem":"2.0.2",
        "observe":"1.3.5",
        "odiff":"0.0.2",
        "pikaday":"*",
        "keysight":"0.0.2",
        "ajax":"https://github.com/fresheneesz/ajax/archive/28d7ca2a922446ad9d2eae7d1bc615f3dbeb2f57.tar.gz"
    }
}
```

This is my npm-debug.log generated when I exectue `npm shrinkwrap`:

```
0 info it worked if it ends with ok
1 verbose cli [ '/home/vagrant/.nvm/versions/node/v5.1.0/bin/node',
1 verbose cli   '/home/vagrant/.nvm/versions/node/v5.1.0/bin/npm',
1 verbose cli   'shrinkwrap' ]
2 info using npm@3.5.2
3 info using node@v5.1.0
4 verbose stack Error: Problems were encountered
4 verbose stack Please correct and try again.
4 verbose stack invalid: have proto@1.0.11 (expected: ) /home/vagrant/tmp2/node_modules/deadunit/node_modules/blocks.js/node_modules/observe/node_modules/proto
4 verbose stack extraneous: proto@1.0.11 /home/vagrant/tmp2/node_modules/deadunit/node_modules/blocks.js/node_modules/observe/node_modules/proto
4 verbose stack invalid: have source-map@0.1.33 (expected: ) /home/vagrant/tmp2/node_modules/deadunit/node_modules/deadunit-core/node_modules/source-map
4 verbose stack extraneous: source-map@0.1.33 /home/vagrant/tmp2/node_modules/deadunit/node_modules/deadunit-core/node_modules/source-map
4 verbose stack invalid: have proto@1.0.10 (expected: ) /home/vagrant/tmp2/node_modules/grapetree/node_modules/proto
4 verbose stack invalid: have proto@1.0.9 (expected: ) /home/vagrant/tmp2/node_modules/grapetree/node_modules/grapetree-core/node_modules/proto
4 verbose stack extraneous: proto@1.0.9 /home/vagrant/tmp2/node_modules/grapetree/node_modules/grapetree-core/node_modules/proto
4 verbose stack extraneous: proto@1.0.10 /home/vagrant/tmp2/node_modules/grapetree/node_modules/proto
4 verbose stack invalid: have proto@1.0.11 (expected: ) /home/vagrant/tmp2/node_modules/observe/node_modules/proto
4 verbose stack extraneous: proto@1.0.11 /home/vagrant/tmp2/node_modules/observe/node_modules/proto
4 verbose stack     at shrinkwrap_ (/home/vagrant/.nvm/versions/node/v5.1.0/lib/node_modules/npm/lib/shrinkwrap.js:101:15)
4 verbose stack     at /home/vagrant/.nvm/versions/node/v5.1.0/lib/node_modules/npm/lib/shrinkwrap.js:36:5
4 verbose stack     at /home/vagrant/.nvm/versions/node/v5.1.0/lib/node_modules/npm/node_modules/iferr/index.js:13:50
4 verbose stack     at /home/vagrant/.nvm/versions/node/v5.1.0/lib/node_modules/npm/lib/install/deps.js:121:5
4 verbose stack     at LOOP (/home/vagrant/.nvm/versions/node/v5.1.0/lib/node_modules/npm/node_modules/slide/lib/chain.js:7:26)
4 verbose stack     at /home/vagrant/.nvm/versions/node/v5.1.0/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
4 verbose stack     at cb (/home/vagrant/.nvm/versions/node/v5.1.0/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
4 verbose stack     at /home/vagrant/.nvm/versions/node/v5.1.0/lib/node_modules/npm/lib/install/deps.js:121:5
4 verbose stack     at LOOP (/home/vagrant/.nvm/versions/node/v5.1.0/lib/node_modules/npm/node_modules/slide/lib/chain.js:7:26)
4 verbose stack     at /home/vagrant/.nvm/versions/node/v5.1.0/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
5 verbose cwd /home/vagrant/tmp2
6 error Linux 2.6.32-431.29.2.el6.x86_64
7 error argv "/home/vagrant/.nvm/versions/node/v5.1.0/bin/node" "/home/vagrant/.nvm/versions/node/v5.1.0/bin/npm" "shrinkwrap"
8 error node v5.1.0
9 error npm  v3.5.2
10 error Problems were encountered
10 error Please correct and try again.
10 error invalid: have proto@1.0.11 (expected: ) /home/vagrant/tmp2/node_modules/deadunit/node_modules/blocks.js/node_modules/observe/node_modules/proto
10 error extraneous: proto@1.0.11 /home/vagrant/tmp2/node_modules/deadunit/node_modules/blocks.js/node_modules/observe/node_modules/proto
10 error invalid: have source-map@0.1.33 (expected: ) /home/vagrant/tmp2/node_modules/deadunit/node_modules/deadunit-core/node_modules/source-map
10 error extraneous: source-map@0.1.33 /home/vagrant/tmp2/node_modules/deadunit/node_modules/deadunit-core/node_modules/source-map
10 error invalid: have proto@1.0.10 (expected: ) /home/vagrant/tmp2/node_modules/grapetree/node_modules/proto
10 error invalid: have proto@1.0.9 (expected: ) /home/vagrant/tmp2/node_modules/grapetree/node_modules/grapetree-core/node_modules/proto
10 error extraneous: proto@1.0.9 /home/vagrant/tmp2/node_modules/grapetree/node_modules/grapetree-core/node_modules/proto
10 error extraneous: proto@1.0.10 /home/vagrant/tmp2/node_modules/grapetree/node_modules/proto
10 error invalid: have proto@1.0.11 (expected: ) /home/vagrant/tmp2/node_modules/observe/node_modules/proto
10 error extraneous: proto@1.0.11 /home/vagrant/tmp2/node_modules/observe/node_modules/proto
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
```

I'm on npm 3.5.2. Honestly, I've been trying to use shrinkwrap for 2 years now, and I've had nothing but trouble. I have problems with it about 20% of the time. It has been a major headache for my team members. Why hasn't shrinkwrap become a usable part of npm? There is clearly something deeply flawed with how shrinkwrap is designed. It should share a ton of code and structure with `npm install`, and yet I constantly have issues where shrinkwrap fails when `npm install` succeeds. 

Sadly, I think I'm just going to have to abandon my use of shrinkwrap. I just can't keep writing these bugs only to find they don't get fixed or that many more pop up. There is a quality problem with shrinkwrap, I think many people would appreciate it if you guys prioritized fixing what is likely not simply the code, but also the process by which shrinkwrap is designed and maintained. I suspect shrinkwrap has been an afterthought for far too long.

**Comment by holm** [comment]
Also looks to be the same as https://github.com/npm/npm/issues/11493

**Comment by stouf** [comment]
Have you tried to run `npm prune` before running `npm shrinkwrap`? It fixes this issue for me *almost* each time (not always though, unfortunately)

**Comment by omouse** [comment]
`npm prune` does **not** fix it for me:

    npm ERR! Problems were encountered
    npm ERR! Please correct and try again.
    npm ERR! invalid: debug@2.6.3 /home/me/code/node_modules/ember-cli/node_modules/debug

**Comment by stouf** [comment]
Maybe you are also concerned by this issue?
https://github.com/npm/npm/issues/15727
