### ISSUE TITLE
Cannot install npm

### ISSUE THREAD

**Issue by agrconsulting** [npm/npm#11353]
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@3.3.12
3 info using node@v5.5.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly install normalizeTree
8 silly loadCurrentTree Finishing
9 silly loadIdealTree Starting
10 silly install loadIdealTree
11 silly cloneCurrentTree Starting
12 silly install cloneCurrentTreeToIdealTree
13 silly cloneCurrentTree Finishing
14 silly loadShrinkwrap Starting
15 silly install loadShrinkwrap
16 silly loadShrinkwrap Finishing
17 silly loadAllDepsIntoIdealTree Starting
18 silly install loadAllDepsIntoIdealTree
19 silly fetchNamedPackageData babel-preset-stage-1
20 silly mapToRegistry name babel-preset-stage-1
21 silly mapToRegistry using default registry
22 silly mapToRegistry registry https://registry.npmjs.org/
23 silly mapToRegistry uri https://registry.npmjs.org/babel-preset-stage-1
24 silly fetchNamedPackageData lodash
25 silly mapToRegistry name lodash
26 silly mapToRegistry using default registry
27 silly mapToRegistry registry https://registry.npmjs.org/
28 silly mapToRegistry uri https://registry.npmjs.org/lodash
29 silly fetchNamedPackageData react
30 silly mapToRegistry name react
31 silly mapToRegistry using default registry
32 silly mapToRegistry registry https://registry.npmjs.org/
33 silly mapToRegistry uri https://registry.npmjs.org/react
34 silly fetchNamedPackageData react-dom
35 silly mapToRegistry name react-dom
36 silly mapToRegistry using default registry
37 silly mapToRegistry registry https://registry.npmjs.org/
38 silly mapToRegistry uri https://registry.npmjs.org/react-dom
39 silly fetchNamedPackageData react-redux
40 silly mapToRegistry name react-redux
41 silly mapToRegistry using default registry
42 silly mapToRegistry registry https://registry.npmjs.org/
43 silly mapToRegistry uri https://registry.npmjs.org/react-redux
44 silly fetchNamedPackageData redux
45 silly mapToRegistry name redux
46 silly mapToRegistry using default registry
47 silly mapToRegistry registry https://registry.npmjs.org/
48 silly mapToRegistry uri https://registry.npmjs.org/redux
49 verbose request uri https://registry.npmjs.org/babel-preset-stage-1
50 verbose request no auth needed
51 info attempt registry request try #1 at 8:32:40 AM
52 verbose request id 211ba4f1e59efa63
53 http request GET https://registry.npmjs.org/babel-preset-stage-1
54 verbose request uri https://registry.npmjs.org/react
55 verbose request no auth needed
56 info attempt registry request try #1 at 8:32:40 AM
57 http request GET https://registry.npmjs.org/react
58 verbose request uri https://registry.npmjs.org/react-dom
59 verbose request no auth needed
60 info attempt registry request try #1 at 8:32:40 AM
61 http request GET https://registry.npmjs.org/react-dom
62 verbose request uri https://registry.npmjs.org/react-redux
63 verbose request no auth needed
64 info attempt registry request try #1 at 8:32:40 AM
65 http request GET https://registry.npmjs.org/react-redux
66 verbose stack Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
66 verbose stack     at Error (native)
66 verbose stack     at Object.createSecureContext (_tls_common.js:87:19)
66 verbose stack     at Object.TLSSocket._init.ssl.onclienthello.ssl.oncertcb.exports.connect (_tls_wrap.js:999:48)
66 verbose stack     at Agent.createConnection (https.js:80:22)
66 verbose stack     at Agent.createSocket (_http_agent.js:172:16)
66 verbose stack     at Agent.addRequest (_http_agent.js:141:23)
66 verbose stack     at new ClientRequest (_http_client.js:137:16)
66 verbose stack     at Object.exports.request (http.js:31:10)
66 verbose stack     at Object.exports.request (https.js:181:15)
66 verbose stack     at Request.start (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:793:30)
67 verbose cwd C:\Development\ReactRedux\ReduxSimpleStarter
68 error Windows_NT 10.0.10240
69 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
70 error node v5.5.0
71 error npm  v3.3.12
72 error error:0906D06C:PEM routines:PEM_read_bio:no start line
73 error If you need help, you may report this error at:
73 error     <https://github.com/npm/npm/issues>
74 verbose exit [ 1, true ]
```

**Comment by zkat** [comment]
`error:0906D06C:PEM routines:PEM_read_bio:no start line` is an SSL error -- are you behind a proxy?...
