### ISSUE TITLE
can not do npm adduser

### ISSUE THREAD

**Issue by hnangeljin** [npm/npm#11351]
```
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "adduser"
npm ERR! node v4.2.6
npm ERR! npm  v2.14.12
npm ERR! code E400

npm ERR! Unknown error while authenticating : -/user/org.couchdb.user:li
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/lijieye/Documents/nodejs/npm/npm-debug.log

this is the debug-log:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'adduser' ]
2 info using npm@2.14.12
3 info using node@v4.2.6
4 warn Username must be lowercase
5 verbose adduser before first PUT { _id: 'org.couchdb.user:li',
5 verbose adduser   name: 'li',
5 verbose adduser   password: 'XXXXX',
5 verbose adduser   email: 'lijieye2004@hotmail.com',
5 verbose adduser   type: 'user',
5 verbose adduser   roles: [],
5 verbose adduser   date: '2016-01-30T13:32:20.948Z' }
6 verbose request uri https://registry.npmjs.org/-/user/org.couchdb.user:li
7 verbose request new user, so can't send auth
8 info attempt registry request try #1 at 8:32:20 AM
9 verbose request id 2ca83258d8f5cfc7
10 http request PUT https://registry.npmjs.org/-/user/org.couchdb.user:li
11 http 400 https://registry.npmjs.org/-/user/org.couchdb.user:li
12 verbose headers { 'content-type': 'application/json',
12 verbose headers   'cache-control': 'max-age=300',
12 verbose headers   'content-length': '57',
12 verbose headers   'accept-ranges': 'bytes',
12 verbose headers   date: 'Sat, 30 Jan 2016 13:32:21 GMT',
12 verbose headers   via: '1.1 varnish',
12 verbose headers   connection: 'keep-alive',
12 verbose headers   'x-served-by': 'cache-iad2123-IAD',
12 verbose headers   'x-cache': 'MISS',
12 verbose headers   'x-cache-hits': '0',
12 verbose headers   'x-timer': 'S1454160741.113212,VS0,VE476' }
13 verbose request invalidating /Users/lijieye/.npm/registry.npmjs.org/-/user/org.couchdb.user_3Ali on PUT
14 verbose adduser back [ { [Error: Unknown error while authenticating : -/user/org.couchdb.user:li] statusCode: 400, code: 'E400' },
14 verbose adduser   { ok: false, error: 'Unknown error while authenticating' },
14 verbose adduser   '{"ok":false,"error":"Unknown error while authenticating"}' ]
15 verbose stack Error: Unknown error while authenticating : -/user/org.couchdb.user:li
15 verbose stack     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
15 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:252:14)
15 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
15 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:198:22)
15 verbose stack     at emitTwo (events.js:87:13)
15 verbose stack     at Request.emit (events.js:172:7)
15 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1082:10)
15 verbose stack     at emitOne (events.js:82:20)
15 verbose stack     at Request.emit (events.js:169:7)
15 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1009:12)
16 verbose statusCode 400
17 verbose cwd /Users/lijieye/Documents/nodejs/npm
18 error Darwin 14.5.0
19 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "adduser"
20 error node v4.2.6
21 error npm  v2.14.12
22 error code E400
23 error Unknown error while authenticating : -/user/org.couchdb.user:li
24 error If you need help, you may report this error at:
24 error     <https://github.com/npm/npm/issues>
25 verbose exit [ 1, true ]
```

**Comment by javajosh** [comment]
Same problem for me, although I have a newer node and npm. Looks like couchdb is down and giving a 400.
```
$ npm adduser
Username: javajosh
Password:
Email: (this IS public) xxxx@gmail.com
npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "adduser"
npm ERR! node v5.8.0
npm ERR! npm  v3.7.3
npm ERR! code E400

npm ERR! Unknown error while authenticating : -/user/org.couchdb.user:javajosh
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/josh/proj/combine-keys/npm-debug.log
```
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'adduser' ]
2 info using npm@3.7.3
3 info using node@v5.8.0
4 verbose adduser before first PUT { _id: 'org.couchdb.user:javajosh',
4 verbose adduser   name: 'javajosh',
4 verbose adduser   password: 'XXXXX',
4 verbose adduser   email: 'xxxx@gmail.com',
4 verbose adduser   type: 'user',
4 verbose adduser   roles: [],
4 verbose adduser   date: '2016-03-17T19:27:38.382Z' }
5 verbose request uri https://registry.npmjs.org/-/user/org.couchdb.user:javajosh
6 verbose request new user, so can't send auth
7 info attempt registry request try #1 at 12:27:38 PM
8 verbose request id e795a6d939eaaa4d
9 http request PUT https://registry.npmjs.org/-/user/org.couchdb.user:javajosh
10 http 400 https://registry.npmjs.org/-/user/org.couchdb.user:javajosh
11 verbose headers { 'content-type': 'application/json',
11 verbose headers   'cache-control': 'max-age=300',
11 verbose headers   'content-length': '57',
11 verbose headers   'accept-ranges': 'bytes',
11 verbose headers   date: 'Thu, 17 Mar 2016 19:27:38 GMT',
11 verbose headers   via: '1.1 varnish',
11 verbose headers   connection: 'keep-alive',
11 verbose headers   'x-served-by': 'cache-lax1432-LAX',
11 verbose headers   'x-cache': 'MISS',
11 verbose headers   'x-cache-hits': '0',
11 verbose headers   'x-timer': 'S1458242858.417775,VS0,VE182' }
12 verbose request invalidating /Users/josh/.npm/registry.npmjs.org/-/user/org.couchdb.user_3Ajavajosh on PUT
13 verbose adduser back [ { [Error: Unknown error while authenticating : -/user/org.couchdb.user:javajosh] statusCode: 400, code: 'E400' },
13 verbose adduser   { ok: false, error: 'Unknown error while authenticating' },
13 verbose adduser   '{"ok":false,"error":"Unknown error while authenticating"}' ]
14 verbose stack Error: Unknown error while authenticating : -/user/org.couchdb.user:javajosh
14 verbose stack     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
14 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:252:14)
14 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
14 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:199:22)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at Request.emit (events.js:185:7)
14 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1036:10)
14 verbose stack     at emitOne (events.js:95:20)
14 verbose stack     at Request.emit (events.js:182:7)
14 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:963:12)
15 verbose statusCode 400
16 verbose cwd /Users/josh/proj/combine-keys
17 error Darwin 15.2.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "adduser"
19 error node v5.8.0
20 error npm  v3.7.3
21 error code E400
22 error Unknown error while authenticating : -/user/org.couchdb.user:javajosh
23 error If you need help, you may report this error at:
23 error     <https://github.com/npm/npm/issues>
24 verbose exit [ 1, true ]
```

**Comment by nlitwin** [comment]
I'm getting the same error
