### ISSUE TITLE
npm issue during build process!!!

### ISSUE THREAD

**Issue by manishmore** [npm/npm#11365]
Hi there,
Getting following error while build process with npm install:

```
npm ERR!     at Object.parse (native)
npm ERR!     at RegClient.<anonymous> (/usr/lib/node_modules/npm-registry-client/lib/request.js:238:23)
npm ERR!     at Request.self.callback (/usr/lib/node_modules/request/index.js:148:22)
npm ERR!     at Request.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/lib/node_modules/request/index.js:891:14)
npm ERR!     at Request.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/lib/node_modules/request/index.js:842:12)
npm ERR!     at IncomingMessage.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:943:16
npm ERR!     at process._tickCallback (node.js:419:13)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 2.6.32-504.3.3.el6.x86_64
npm ERR! command "node" "/usr/bin/npm" "install"
npm ERR! cwd /www/test2/test/20160129142047/site/profiles/test/modules/custom/b2b_price_finder/source
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.3.6
npm ERR! type unexpected_token
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /www/test/test/20160129142047/site/profiles/test/modules/custom/test/source/npm-debug.log
npm ERR! not ok code 0
>
```

**Comment by KenanY** [comment]
@manishmore `npm@1.3` is no longer supported. Please try [updating](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) first.

**Comment by sotayamashita** [comment]
@KenanY Is there any resource to detect `npm@1.3` is supported or not ?

**Comment by KenanY** [comment]
@sotayamashita I don't think so.

**Comment by sotayamashita** [comment]
@KenanY How do you know `npm@1.3` is no longer supported ?

**Comment by KenanY** [comment]
@sotayamashita From comments made by the project developers in other issues.

**Comment by sotayamashita** [comment]
@KenanY Thank you kind replay .

**Comment by KenanY** [comment]
@manishmore Are you still experiencing this issue with `npm@2` or `npm@3`?

**Comment by KenanY** [comment]
Closing as abandoned.
