### ISSUE TITLE
npm3 moving dependencies on update?

### ISSUE THREAD

**Issue by hockeytim11** [npm/npm#11387]
I seem to be having an issue where my package has a dependency that goes missing when I run npm update. I'm using npm 3.3.12 and node 5.3.0 on windows 7.

I was able to reproduce the issue below. Am I doing something wrong? This also seems to happen when running npm update instead of the fs-extra@latest call.

```
mkdir test
cd test
npm init --force
npm install graceful-fs --save
npm install fs-extra@0.26.4 --save
npm install fs-extra@latest --save
node -e console.log(require('graceful-fs'))
```

Output:
```
module.js:328
    throw err;
    ^

Error: Cannot find module 'graceful-fs'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at [eval]:1:13
    at Object.exports.runInThisContext (vm.js:54:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:398:26)
    at node.js:592:27
    at nextTickCallbackWith0Args (node.js:433:9)
```

This seems to be important. What does the -> mean?
```
C:\temp\test>npm install fs-extra@latest --save
graceful-fs@4.1.2 node_modules\graceful-fs -> node_modules\fs-extra\node_modules
\graceful-fs
test@1.0.0 C:\temp\test
└── fs-extra@0.26.5
```

**Comment by hockeytim11** [comment]
I was just able to try this on another machine with the latest npm 3.6.0 and it seems to have fixed the issue.
