### ISSUE TITLE
npm-init fails for module 'debug'

### ISSUE THREAD

**Issue by jandrieu** [npm/npm#11393]
Attempting to require('debug') from ~./npm-init.js fails.

I can confirm that debug is installed globally (npm install -g debug). If I run node interactively, I have no problem requiring debug.  But if I do it within npm-init.js it fails with the following npm-debug.log
```
joe@dev-frontend:~/.npm-global/lib/node_modules/joe-debug$ cat npm-debug.log 
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'init' ]
2 info using npm@1.4.28
3 info using node@v0.10.40
4 silly package data undefined
5 info init written successfully
6 error Error: Cannot find module 'debug'
6 error     at Function.Module._resolveFilename (module.js:338:15)
6 error     at Function.Module._load (module.js:280:25)
6 error     at Module.require (module.js:364:17)
6 error     at ctx.require (/usr/local/lib/node_modules/npm/node_modules/init-package-json/node_modules/promzard/promzard.js:68:16)
6 error     at Object.<anonymous> (/home/joe/.npm-init.js:5:13)
6 error     at PromZard.loaded (/usr/local/lib/node_modules/npm/node_modules/init-package-json/node_modules/promzard/promzard.js:80:22)
6 error     at PromZard.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/init-package-json/node_modules/promzard/promzard.js:57:10)
6 error     at fs.js:272:14
6 error     at Object.oncomplete (fs.js:108:15)
7 error If you need help, you may report this *entire* log,
7 error including the npm and node versions, at:
7 error     <http://github.com/npm/npm/issues>
8 error System Linux 3.13.0-74-generic
9 error command "/usr/local/bin/node" "/usr/local/bin/npm" "init"
10 error cwd /home/joe/.npm-global/lib/node_modules/joe-debug
11 error node -v v0.10.40
12 error npm -v 1.4.28
13 error code MODULE_NOT_FOUND
14 verbose exit [ 1, true ]
```

I also updated npm and tried again just to make sure it wasn't something already fixed. Basically the same error:
```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/home/joe/.npm-global/bin/npm', 'init' ]
2 info using npm@3.6.0
3 info using node@v0.10.40
4 silly package data undefined
5 info init written successfully
6 verbose stack Error: Cannot find module 'debug'
6 verbose stack     at Function.Module._resolveFilename (module.js:338:15)
6 verbose stack     at Function.Module._load (module.js:280:25)
6 verbose stack     at Module.require (module.js:364:17)
6 verbose stack     at ctx.require (/home/joe/.npm-global/lib/node_modules/npm/node_modules/init-package-json/node_modules/promzard/promzard.js:78:16)
6 verbose stack     at Object.<anonymous> (/home/joe/.npm-init.js:5:13)
6 verbose stack     at PromZard.loaded (/home/joe/.npm-global/lib/node_modules/npm/node_modules/init-package-json/node_modules/promzard/promzard.js:90:22)
6 verbose stack     at PromZard.<anonymous> (/home/joe/.npm-global/lib/node_modules/npm/node_modules/init-package-json/node_modules/promzard/promzard.js:67:10)
6 verbose stack     at /home/joe/.npm-global/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:76:16
6 verbose stack     at fs.js:272:14
6 verbose stack     at /home/joe/.npm-global/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:42:10
7 verbose cwd /home/joe/.npm-global/lib/node_modules/joe-debug
8 error Linux 3.13.0-74-generic
9 error argv "node" "/home/joe/.npm-global/bin/npm" "init"
10 error node v0.10.40
11 error npm  v3.6.0
12 error code MODULE_NOT_FOUND
13 error Cannot find module 'debug'
14 error If you need help, you may report this error at:
14 error     <https://github.com/npm/npm/issues>
15 verbose exit [ 1, true ]
```

**Comment by jandrieu** [comment]
Apologies. This was apparently an issue with my NODE_PATH env variable.
