### ISSUE TITLE
npm ERR! typeerror Error: Argument #2: Expected array but got string

### ISSUE THREAD

**Issue by cloud9amit** [npm/npm#11413]
Hi I am getting following error "npm ERR! typeerror Error: Argument #2: Expected array but got string" while linking npm projects. I am using npm version 3.7.1 . Below is the npm debug log:

```
**************************************************************************
            Linking NPM Project demo/demo-services into demo/desktop/desktop-demo
**************************************************************************

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\e3017481\\AppData\\Roaming\\npm\\nod
e_modules\\npm\\bin\\npm-cli.js" "link" "D:\\Workspace" "HTML5\\html5-framework-build/demo/demo-serv
ices"
npm ERR! node v4.2.0
npm ERR! npm  v3.7.1
npm ERR! code EINVALIDTYPE

npm ERR! typeerror Error: Argument #2: Expected array but got string
npm ERR! typeerror     at EventEmitter.install (C:\Users\e3017481\AppData\Roaming\npm\node_modules\n
pm\lib\install.js:175:3)
npm ERR! typeerror     at Object.commandCache.(anonymous function) (C:\Users\e3017481\AppData\Roamin
g\npm\node_modules\npm\lib\npm.js:216:13)
npm ERR! typeerror     at C:\Users\e3017481\AppData\Roaming\npm\node_modules\npm\lib\link.js:89:24
npm ERR! typeerror     at FSReqWrap.oncomplete (fs.js:82:15)
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Workspace HTML5\html5-framework-build\demo\desktop\desktop-demo\npm-debug.log

D:\Workspace HTML5\html5-framework-build>
```

**Comment by andy-hanson** [comment]
This also happens if you link to any non-existent directory, as in `npm link ../blah`.

**Comment by jbcpollak** [comment]
for me this issue happened when I had a package named 'path-planner' in a folder called 'path_planner'. I corrected the package name to 'path_planner' and this problem started happening when I ran 'npm install'

**Comment by anodynos** [comment]
Got the same `npm link` error (trying to link non-existent dir) with Kubuntu 16.04 

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'link',
1 verbose cli   '../projects/loopback-component-auto-migrate' ]
2 info using npm@4.1.2
3 info using node@v7.5.0
4 verbose stack Error: Argument #2: Expected array but got string
4 verbose stack     at EventEmitter.install (/usr/local/lib/node_modules/npm/lib/install.js:182:3)
4 verbose stack     at Object.commandCache.(anonymous function) (/usr/local/lib/node_modules/npm/lib/npm.js:128:13)
4 verbose stack     at /usr/local/lib/node_modules/npm/lib/link.js:93:24
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:284:29
4 verbose stack     at FSReqWrap.oncomplete (fs.js:112:15)
5 verbose cwd /mnt/projects/Ve/ActionManager-API
6 error Linux 4.4.0-65-generic
7 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "link" "../projects/loopback-component-auto-migrate"
8 error node v7.5.0
9 error npm  v4.1.2
10 error code EINVALIDTYPE
11 error typeerror Error: Argument #2: Expected array but got string
11 error typeerror     at EventEmitter.install (/usr/local/lib/node_modules/npm/lib/install.js:182:3)
11 error typeerror     at Object.commandCache.(anonymous function) (/usr/local/lib/node_modules/npm/lib/npm.js:128:13)
11 error typeerror     at /usr/local/lib/node_modules/npm/lib/link.js:93:24
11 error typeerror     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:284:29
11 error typeerror     at FSReqWrap.oncomplete (fs.js:112:15)
12 error typeerror This is an error with npm itself. Please report this error at:
12 error typeerror     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]
```

**Comment by kylegmaxwell** [comment]
I also just started getting this issue, from reading here I realized the directory no longer exists, but ideally npm would emit a warning, not crash in this case.

**Comment by legodude17** [comment]
`npm -v`?

**Comment by kylegmaxwell** [comment]
npm -v
3.10.8

**Comment by legodude17** [comment]
Try updating npm to the latest version.

**Comment by kylegmaxwell** [comment]
Thanks for your help, I can't exactly do that because the version is prescribed by my company, but I assumed the issue was not fixed on the latest version since this issue was still open. I can work around the issue, I just wanted to add a vote if it was not fixed yet.

**Comment by legodude17** [comment]
I would guess it is already fixed, but I would need to test on latest.

**Comment by legodude17** [comment]
@cloud9amit Can you replicate this on the latest version of `npm`?

**Comment by kylegmaxwell** [comment]
@legodude17 Ok, so the previous was on my Mac, now I tried v 3.10.10 on my personal Windows computer, and version 4.2.0 on Windows and got the same error : Argument #2: Expected array but got string.

**Comment by legodude17** [comment]
Could you upload the new npm-debug.log (from the latest version) as a plaintext file to https://gist.github.com/ and post a link to it here?

**Comment by kylegmaxwell** [comment]
Here it is: https://gist.github.com/kylegmaxwell/17f0b00adde2f2a901f2da8a1cbdffc5
