### ISSUE TITLE
can't start web-server

### ISSUE THREAD

**Issue by nicromant9** [npm/npm#11412]
macbook:scripts alex$ pwd
/Users/alex/sfe/node_modules/protractor-core/node_modules/protractor/testapp/scripts
macbook:scripts alex$ ls
web-server.js
macbook:scripts alex$ ./web-server.js
module.js:328
    throw err;
    ^

Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/alex/sfe/node_modules/protractor-core/node_modules/protractor/testapp/scripts/web-server.js:3:15)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)

**Comment by KenanY** [comment]
@nicromant9 Do you have `express` installed in your local `node_modules/`?

**Comment by ashleygwilliams** [comment]
hi! as @KenanY mentioned, this error means that you do not have a local copy of the `express` package, which is required by `node` when you run the script you are running.

you'll want to create a `package.json` that lists `express` as a dependency and then `npm install`

please open another issue if you continue to have problems!
