### ISSUE TITLE
npm publish is failing

### ISSUE THREAD

**Issue by smebberson** [npm/npm#11422]
This is my `npm-debug.log` file:

```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/bin/npm', 'publish' ]
2 info using npm@3.6.0
3 info using node@v0.10.38
4 verbose node symlink /usr/bin/node
5 verbose publish [ '.' ]
6 silly cache add args [ '.', null ]
7 verbose cache add spec .
8 silly cache add parsed spec { raw: '.',
8 silly cache add   scope: null,
8 silly cache add   name: null,
8 silly cache add   rawSpec: '.',
8 silly cache add   spec: '/vagrant',
8 silly cache add   type: 'directory' }
9 verbose addLocalDirectory /home/vagrant/.npm/gulp-electron-downloader/0.1.6/package.tgz not in flight; packing
10 verbose correctMkdir /home/vagrant/.npm correctMkdir not in flight; initializing
11 info lifecycle gulp-electron-downloader@0.1.6~prepublish: gulp-electron-downloader@0.1.6
12 silly lifecycle gulp-electron-downloader@0.1.6~prepublish: no script for prepublish, continuing
13 verbose tar pack [ '/home/vagrant/.npm/gulp-electron-downloader/0.1.6/package.tgz',
13 verbose tar pack   '/vagrant' ]
14 verbose tarball /home/vagrant/.npm/gulp-electron-downloader/0.1.6/package.tgz
15 verbose folder /vagrant
16 verbose addLocalTarball adding from inside cache /home/vagrant/.npm/gulp-electron-downloader/0.1.6/package.tgz
17 verbose correctMkdir /home/vagrant/.npm correctMkdir not in flight; initializing
18 silly cache afterAdd gulp-electron-downloader@0.1.6
19 verbose afterAdd /home/vagrant/.npm/gulp-electron-downloader/0.1.6/package/package.json not in flight; writing
20 verbose correctMkdir /home/vagrant/.npm correctMkdir not in flight; initializing
21 verbose afterAdd /home/vagrant/.npm/gulp-electron-downloader/0.1.6/package/package.json written
22 silly publish { name: 'gulp-electron-downloader',
22 silly publish   version: '0.1.6',
22 silly publish   description: 'A gulp.js plugin to help download electron.',
22 silly publish   main: 'plugin.js',
22 silly publish   scripts: { test: 'echo "Error: no test specified" && exit 1' },
22 silly publish   repository:
22 silly publish    { type: 'git',
22 silly publish      url: 'git+https://github.com/smebberson/gulp-electron-downloader.git' },
22 silly publish   keywords: [ 'gulpplugin', 'electron' ],
22 silly publish   author: { name: 'Scott Mebberson' },
22 silly publish   license: 'ISC',
22 silly publish   bugs: { url: 'https://github.com/smebberson/gulp-electron-downloader/issues' },
22 silly publish   homepage: 'https://github.com/smebberson/gulp-electron-downloader',
22 silly publish   dependencies:
22 silly publish    { async: '^0.9.0',
22 silly publish      'extract-zip': '^1.1.1',
22 silly publish      'fs-jetpack': '^0.6.4',
22 silly publish      'gulp-util': '^3.0.4',
22 silly publish      progress: '^1.1.8',
22 silly publish      request: '^2.55.0' },
22 silly publish   gitHead: '1ecaef83671f39fcde0db5bbda32aa5dac7946b1',
22 silly publish   readme: '# gulp-electron-downloader\n\nA gulp.js plugin to download electron. Super simple, it will simply download (and cache) and extract to a directory of your choice. You can run with zero-configuration, and use the defaults. Or configure as you wish.\n\nThis plugin makes it really easy to get any electron binary you need, where as most others only download electron for the platform for the host.\n\nIf you\'re wanting to build an electron release, you\'ll need another plugin for that.\n\n## Installation\n\nInstall gulp plugin package:\n\n```sh\nnpm install --save-dev gulp-electron-downloader\n```\n\n## Usage\n\nThe most simple is the following:\n\n```js\nvar gulp = require(\'gulp\');\nvar electronDownloader = require(\'gulp-electron-downloader\');\n\ngulp.task(\'download-electron\', function(cb){\n\n    electronDownloader(cb);\n\n});\n\ngulp.task(\'default\', [\'download-electron\']);\n```\n\nThis will download the latest release of electron, matching the platform and architecture of the host. The `./electron/cache` folder will be used to store downloads, and the final output will end up `./electron/binaries`.\n\nThe plugin makes unauthenticated requests to GitHub API. If you get rate-limit errors, use your own token by setting the env var `GITHUB_OAUTH_TOKEN`.\n\n### Constructor\n\n```js\nelectronDownloader([options], callback)\n```\n\n### Options\n\nYou can customise what is downloaded with the following:\n\n- `version` - the version of electron you want to download. This defaults to the latest release.\n- `platform` - the platform you want to download. Choices are `darwin`, `win32`, `linux`. This defaults to the host platform.\n- `arch` - the architecture of the platform you want to download. This defaults to the host architecture.\n- `cacheDir` - the location of the caching directory in which downloads will be stored. This defaults to `./electron/cache`.\n- `outputDir` - the location of the unzipped binary. This defaults to `./electron/binaries/platform-arch/`.\n- `downloadMirror` - a function that provided the official electron download URL for a particular version, returns a URL to a mirror of your choice. An example for China:\n\n```\ndownloadMirror: function (downloadUrl) {\n    return downloadUrl.replace(\'https://github.com/atom/electron/releases/download/v\', \'https://npm.taobao.org/mirrors/electron/\');\n}\n```\n',
22 silly publish   readmeFilename: 'README.md',
22 silly publish   _id: 'gulp-electron-downloader@0.1.6',
22 silly publish   _shasum: '467d59a0122adca58aa363c26ba104f18cb8e507',
22 silly publish   _from: '.' }
23 verbose getPublishConfig undefined
24 silly mapToRegistry name gulp-electron-downloader
25 silly mapToRegistry using default registry
26 silly mapToRegistry registry https://registry.npmjs.org/
27 silly mapToRegistry uri https://registry.npmjs.org/gulp-electron-downloader
28 verbose publish registryBase https://registry.npmjs.org/
29 silly publish uploading /home/vagrant/.npm/gulp-electron-downloader/0.1.6/package.tgz
30 verbose request uri https://registry.npmjs.org/gulp-electron-downloader
31 verbose request sending authorization for write operation
32 info attempt registry request try #1 at 21:54:00
33 verbose request id 9973e45b2772c76c
34 http request PUT https://registry.npmjs.org/gulp-electron-downloader
35 http 500 https://registry.npmjs.org/gulp-electron-downloader
36 verbose headers { 'content-type': 'application/json',
36 verbose headers   'cache-control': 'max-age=0',
36 verbose headers   'content-length': '39',
36 verbose headers   'accept-ranges': 'bytes',
36 verbose headers   date: 'Thu, 04 Feb 2016 21:54:01 GMT',
36 verbose headers   via: '1.1 varnish',
36 verbose headers   connection: 'keep-alive',
36 verbose headers   'x-served-by': 'cache-syd1624-SYD',
36 verbose headers   'x-cache': 'MISS',
36 verbose headers   'x-cache-hits': '0',
36 verbose headers   'x-timer': 'S1454622841.158761,VS0,VE715' }
37 info retry will retry, error on last attempt: Error: unexpected status code: 401 : gulp-electron-downloader
38 info attempt registry request try #2 at 21:54:11
39 http request PUT https://registry.npmjs.org/gulp-electron-downloader
40 http 500 https://registry.npmjs.org/gulp-electron-downloader
41 verbose headers { 'content-type': 'application/json',
41 verbose headers   'cache-control': 'max-age=0',
41 verbose headers   'content-length': '39',
41 verbose headers   'accept-ranges': 'bytes',
41 verbose headers   date: 'Thu, 04 Feb 2016 21:54:13 GMT',
41 verbose headers   via: '1.1 varnish',
41 verbose headers   connection: 'keep-alive',
41 verbose headers   'x-served-by': 'cache-syd1623-SYD',
41 verbose headers   'x-cache': 'MISS',
41 verbose headers   'x-cache-hits': '0',
41 verbose headers   'x-timer': 'S1454622852.293922,VS0,VE708' }
42 info retry will retry, error on last attempt: Error: unexpected status code: 401 : gulp-electron-downloader
43 info attempt registry request try #3 at 21:55:13
44 http request PUT https://registry.npmjs.org/gulp-electron-downloader
45 http 500 https://registry.npmjs.org/gulp-electron-downloader
46 verbose headers { 'content-type': 'application/json',
46 verbose headers   'cache-control': 'max-age=0',
46 verbose headers   'content-length': '39',
46 verbose headers   'accept-ranges': 'bytes',
46 verbose headers   date: 'Thu, 04 Feb 2016 21:55:14 GMT',
46 verbose headers   via: '1.1 varnish',
46 verbose headers   connection: 'keep-alive',
46 verbose headers   'x-served-by': 'cache-syd1623-SYD',
46 verbose headers   'x-cache': 'MISS',
46 verbose headers   'x-cache-hits': '0',
46 verbose headers   'x-timer': 'S1454622913.588536,VS0,VE698' }
47 verbose request invalidating /home/vagrant/.npm/registry.npmjs.org/gulp-electron-downloader on PUT
48 error publish Failed PUT 500
49 verbose stack Error: unexpected status code: 401 : gulp-electron-downloader
49 verbose stack     at makeError (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
49 verbose stack     at CachingRegistryClient.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:252:14)
49 verbose stack     at Request._callback (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
49 verbose stack     at Request.self.callback (/usr/lib/node_modules/npm/node_modules/request/request.js:198:22)
49 verbose stack     at Request.emit (events.js:98:17)
49 verbose stack     at Request.<anonymous> (/usr/lib/node_modules/npm/node_modules/request/request.js:1035:10)
49 verbose stack     at Request.emit (events.js:117:20)
49 verbose stack     at IncomingMessage.<anonymous> (/usr/lib/node_modules/npm/node_modules/request/request.js:962:12)
49 verbose stack     at IncomingMessage.emit (events.js:117:20)
49 verbose stack     at _stream_readable.js:944:16
50 verbose statusCode 500
51 verbose pkgid gulp-electron-downloader
52 verbose cwd /vagrant
53 error Linux 3.13.0-24-generic
54 error argv "node" "/usr/bin/npm" "publish"
55 error node v0.10.38
56 error npm  v3.6.0
57 error code E500
58 error unexpected status code: 401 : gulp-electron-downloader
59 error If you need help, you may report this error at:
59 error     <https://github.com/npm/npm/issues>
60 verbose exit [ 1, true ]
```

**Comment by othiym23** [comment]
```
49 verbose stack Error: unexpected status code: 401 : gulp-electron-downloader
```

Are you logged in as `smebberson`? If you are, if you run `npm login` again and then try to publish afterwards, does it still fail? HTTP 401 means that the registry thinks you don't have permission to publish that package, which to me sounds like either you're logged in as a different user, or the registry thinks your auth token is bad.

**Comment by smebberson** [comment]
That resolved my issue. Perhaps the error message could be a little more obvious? I know what a 401 is, so it should have been clear to me :(

Sorry for the time wasting.

**Comment by othiym23** [comment]
Not a waste of time! Thanks for _your_ time!
