### ISSUE TITLE
Error extracting /Users/xxx/.npm/grunt-devcode/0.0.3/package.tgz archive: ENOENT: no such file or directory, open '/Users/xxxx/.npm/grunt-devcode/0.0.3/package.tgz'

### ISSUE THREAD

**Issue by Spiderbezno** [npm/npm#11429]
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'grunt-devcode' ]
2 info using npm@3.3.12
3 info using node@v5.5.0
4 verbose config Skipping project config: /Users/xxx/.npmrc. (matches userconfig)
5 silly loadCurrentTree Starting
6 silly install loadCurrentTree
7 silly install readLocalPackageData
8 silly fetchPackageMetaData grunt-devcode
9 silly fetchNamedPackageData grunt-devcode
10 silly mapToRegistry name grunt-devcode
11 silly mapToRegistry using default registry
12 silly mapToRegistry registry http://registry.npmjs.org/
13 silly mapToRegistry uri http://registry.npmjs.org/grunt-devcode
14 verbose request uri http://registry.npmjs.org/grunt-devcode
15 verbose request no auth needed
16 info attempt registry request try #1 at 8:07:32 AM
17 verbose request id f53b2402f461955b
18 verbose etag "5VCXLFFXZ3A1PIIZAW0C9A9VD"
19 http request GET http://registry.npmjs.org/grunt-devcode
20 http 304 http://registry.npmjs.org/grunt-devcode
21 verbose headers { date: 'Fri, 05 Feb 2016 07:07:03 GMT',
21 verbose headers   via: '1.1 varnish',
21 verbose headers   'cache-control': 'max-age=300',
21 verbose headers   etag: '"5VCXLFFXZ3A1PIIZAW0C9A9VD"',
21 verbose headers   age: '0',
21 verbose headers   'x-served-by': 'cache-ams4136-AMS',
21 verbose headers   'x-cache': 'MISS',
21 verbose headers   'x-cache-hits': '0',
21 verbose headers   'x-timer': 'S1454656023.346033,VS0,VE494',
21 verbose headers   vary: 'Accept' }
22 silly get cb [ 304,
22 silly get   { date: 'Fri, 05 Feb 2016 07:07:03 GMT',
22 silly get     via: '1.1 varnish',
22 silly get     'cache-control': 'max-age=300',
22 silly get     etag: '"5VCXLFFXZ3A1PIIZAW0C9A9VD"',
22 silly get     age: '0',
22 silly get     'x-served-by': 'cache-ams4136-AMS',
22 silly get     'x-cache': 'MISS',
22 silly get     'x-cache-hits': '0',
22 silly get     'x-timer': 'S1454656023.346033,VS0,VE494',
22 silly get     vary: 'Accept' } ]
23 verbose etag http://registry.npmjs.org/grunt-devcode from cache
24 verbose get saving grunt-devcode to /Users/xxxxx/.npm/registry.npmjs.org/grunt-devcode/.cache.json
25 silly install normalizeTree
26 silly loadCurrentTree Finishing
27 silly loadIdealTree Starting
28 silly install loadIdealTree
29 silly cloneCurrentTree Starting
30 silly install cloneCurrentTreeToIdealTree
31 silly cloneCurrentTree Finishing
32 silly loadShrinkwrap Starting
33 silly install loadShrinkwrap
34 silly loadShrinkwrap Finishing
35 silly loadAllDepsIntoIdealTree Starting
36 silly install loadAllDepsIntoIdealTree
37 silly resolveWithNewModule grunt-devcode@0.0.3 checking installable status
38 silly cache add args [ 'grunt-devcode', null ]
39 verbose cache add spec grunt-devcode
40 silly cache add parsed spec Result {
40 silly cache add   raw: 'grunt-devcode',
40 silly cache add   scope: null,
40 silly cache add   name: 'grunt-devcode',
40 silly cache add   rawSpec: '',
40 silly cache add   spec: '*',
40 silly cache add   type: 'range' }
41 silly addNamed grunt-devcode@*
42 verbose addNamed "*" is a valid semver range for grunt-devcode
43 silly addNameRange { name: 'grunt-devcode', range: '*', hasData: false }
44 silly mapToRegistry name grunt-devcode
45 silly mapToRegistry using default registry
46 silly mapToRegistry registry http://registry.npmjs.org/
47 silly mapToRegistry uri http://registry.npmjs.org/grunt-devcode
48 verbose addNameRange registry:http://registry.npmjs.org/grunt-devcode not in flight; fetching
49 verbose get http://registry.npmjs.org/grunt-devcode not expired, no request
50 silly addNameRange number 2 { name: 'grunt-devcode', range: '*', hasData: true }
51 silly addNameRange versions [ 'grunt-devcode',
51 silly addNameRange   [ '0.0.1',
51 silly addNameRange     '0.0.2',
51 silly addNameRange     '0.0.3',
51 silly addNameRange     '0.0.4',
51 silly addNameRange     '0.0.4-c',
51 silly addNameRange     '0.0.3-a',
51 silly addNameRange     '0.0.4-a',
51 silly addNameRange     '0.0.4-b' ] ]
52 silly addNamed grunt-devcode@0.0.4
53 verbose addNamed "0.0.4" is a plain semver version for grunt-devcode
54 silly cache afterAdd grunt-devcode@0.0.4
55 verbose afterAdd /Users/xxx/.npm/grunt-devcode/0.0.4/package/package.json not in flight; writing
56 verbose afterAdd /Users/xxxx/.npm/grunt-devcode/0.0.4/package/package.json written
57 silly rollbackFailedOptional Starting
58 silly rollbackFailedOptional Finishing
59 silly runTopLevelLifecycles Starting
60 silly runTopLevelLifecycles Finishing
61 silly install printInstalled
62 verbose stack Error: Error extracting /Users/xxxx/.npm/grunt-devcode/0.0.3/package.tgz archive: ENOENT: no such file or directory, open '/Users/xxxx/.npm/grunt-devcode/0.0.3/package.tgz'
62 verbose stack     at ReadStream.<anonymous> (/usr/local/lib/node_modules/npm/lib/fetch-package-metadata.js:286:10)
62 verbose stack     at emitOne (events.js:90:13)
62 verbose stack     at ReadStream.emit (events.js:182:7)
62 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:179:14
62 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:230:16
62 verbose stack     at FSReqWrap.oncomplete (fs.js:82:15)
63 verbose cwd /Users/Jorge1Old
64 error Darwin 15.2.0
65 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "grunt-devcode"
66 error node v5.5.0
67 error npm  v3.3.12
68 error code EREADFILE
69 error Error extracting /Users/xxxx/.npm/grunt-devcode/0.0.3/package.tgz archive: ENOENT: no such file or directory, open '/Users/xxxxx/.npm/grunt-devcode/0.0.3/package.tgz'
70 error If you need help, you may report this error at:
70 error     <https://github.com/npm/npm/issues>
71 verbose exit [ 1, true ]
```

**Comment by othiym23** [comment]
I believe this bug has been addressed in newer versions of npm. If you update to the newest version of npm with `npm -g install npm@latest`, does this error recur?
