### ISSUE TITLE
npm publish is failing due to 500 error

### ISSUE THREAD

**Issue by tjmehta** [npm/npm#11423]
Trying to deploy the latest minor version of a public module, and I saw this error twice. Will continue to try...

```bash
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'publish' ]
2 info using npm@3.3.12
3 info using node@v5.5.0
4 verbose publish [ '.' ]
5 silly cache add args [ '.', null ]
6 verbose cache add spec .
7 silly cache add parsed spec Result {
7 silly cache add   raw: '.',
7 silly cache add   scope: null,
7 silly cache add   name: null,
7 silly cache add   rawSpec: '.',
7 silly cache add   spec: '/Users/tjmehta/Developer/+github/cast-buffer',
7 silly cache add   type: 'directory' }
8 verbose addLocalDirectory /Users/tjmehta/.npm/cast-buffer/1.1.0/package.tgz not in flight; packing
9 info lifecycle cast-buffer@1.1.0~prepublish: cast-buffer@1.1.0
10 silly lifecycle cast-buffer@1.1.0~prepublish: no script for prepublish, continuing
11 verbose tar pack [ '/Users/tjmehta/.npm/cast-buffer/1.1.0/package.tgz',
11 verbose tar pack   '/Users/tjmehta/Developer/+github/cast-buffer' ]
12 verbose tarball /Users/tjmehta/.npm/cast-buffer/1.1.0/package.tgz
13 verbose folder /Users/tjmehta/Developer/+github/cast-buffer
14 verbose addLocalTarball adding from inside cache /Users/tjmehta/.npm/cast-buffer/1.1.0/package.tgz
15 silly cache afterAdd cast-buffer@1.1.0
16 verbose afterAdd /Users/tjmehta/.npm/cast-buffer/1.1.0/package/package.json not in flight; writing
17 verbose afterAdd /Users/tjmehta/.npm/cast-buffer/1.1.0/package/package.json written
18 silly publish { name: 'cast-buffer',
18 silly publish   version: '1.1.0',
18 silly publish   description: 'cast objects, arrays, numbers, and strings to buffers',
18 silly publish   main: 'index.js',
18 silly publish   scripts:
18 silly publish    { test: 'lab --verbose --assert code --threshold 100',
18 silly publish      lint: 'standard' },
18 silly publish   repository:
18 silly publish    { type: 'git',
18 silly publish      url: 'https://github.com/tjmehta/cast-buffer.git' },
18 silly publish   keywords:
18 silly publish    [ 'cast',
18 silly publish      'buffer',
18 silly publish      'string',
18 silly publish      'array',
18 silly publish      'object',
18 silly publish      'to',
18 silly publish      'buffers',
18 silly publish      'objects',
18 silly publish      'arrays',
18 silly publish      'json' ],
18 silly publish   author: { name: 'Tejesh Mehta' },
18 silly publish   license: 'MIT',
18 silly publish   bugs: { url: 'https://github.com/tjmehta/cast-buffer/issues' },
18 silly publish   homepage: 'https://github.com/tjmehta/cast-buffer',
18 silly publish   devDependencies: { code: '^1.5.0', lab: '^5.18.1', standard: '^5.4.1' },
18 silly publish   dependencies: { '101': '^1.2.0', 'assert-args': '^1.0.5' },
18 silly publish   readme: '# cast-buffer [![Build Status](https://travis-ci.org/tjmehta/cast-buffer.svg?branch=master)](https://travis-ci.org/tjmehta/cast-buffer)\ncast objects, arrays, numbers, and strings to buffers\n\n# Installation\n```bash\nnpm i --save cast-buffer\n```\n\n# Usage\n```js\nvar buff\n\nbuff = castBuffer({ \'foo\': 1, \'bar\': 2 }) // new Buffer(\'{ \'foo\': 1, \'bar\': 2 }\')\nbuff = castBuffer([ \'foo\', \'bar\', \'qux\' ]) // new Buffer(\'[ \'foo\', \'bar\', \'qux\' ]\')\nbuff = castBuffer(\'hello\') // new Buffer(\'hello\')\nbuff = castBuffer(10) // new Buffer(\'10\') // stringified number\nbuff = castBuffer(1.1) // new Buffer(\'1.1\') // stringified number\nbuff = castBuffer(new Buffer(\'hello\')) // returns same buffer\n\n// Calls toJSON if it exists\nvar foobar = {\n  _json: {}\n  get: function () {/*...*/}\n  set: function () {/*...*/}\n  toJSON: function () {\n    return this._json\n  }\n}\nbuff = castBuffer(foobar) // new Buffer(\'{}\')\nbuff = castBuffer([ foobar ]) // new Buffer(\'[{}]\')\n```\n\n# License\nMIT\n',
18 silly publish   readmeFilename: 'README.md',
18 silly publish   gitHead: 'acc09eac92e23ceaa04064e5c0d4305d5b4ffdf4',
18 silly publish   _id: 'cast-buffer@1.1.0',
18 silly publish   _shasum: '0f086d2217895821c3bd017c6297428469db42f2',
18 silly publish   _from: '.' }
19 verbose getPublishConfig undefined
20 silly mapToRegistry name cast-buffer
21 silly mapToRegistry using default registry
22 silly mapToRegistry registry https://registry.npmjs.org/
23 silly mapToRegistry uri https://registry.npmjs.org/cast-buffer
24 verbose publish registryBase https://registry.npmjs.org/
25 silly publish uploading /Users/tjmehta/.npm/cast-buffer/1.1.0/package.tgz
26 verbose request uri https://registry.npmjs.org/cast-buffer
27 verbose request sending authorization for write operation
28 info attempt registry request try #1 at 2:32:14 PM
29 verbose request id 255963332c809b0e
30 http request PUT https://registry.npmjs.org/cast-buffer
31 http 500 https://registry.npmjs.org/cast-buffer
32 verbose headers { 'content-type': 'application/json',
32 verbose headers   'cache-control': 'max-age=0',
32 verbose headers   'content-length': '99',
32 verbose headers   'accept-ranges': 'bytes',
32 verbose headers   date: 'Thu, 04 Feb 2016 22:32:28 GMT',
32 verbose headers   via: '1.1 varnish',
32 verbose headers   connection: 'keep-alive',
32 verbose headers   'x-served-by': 'cache-sjc3130-SJC',
32 verbose headers   'x-cache': 'MISS',
32 verbose headers   'x-cache-hits': '0',
32 verbose headers   'x-timer': 'S1454625134.449561,VS0,VE13902' }
33 info retry will retry, error on last attempt: Error: "no clients remaining. see `.errors` property for each client error." : cast-buffer
34 info attempt registry request try #2 at 2:32:38 PM
35 http request PUT https://registry.npmjs.org/cast-buffer
36 http 500 https://registry.npmjs.org/cast-buffer
37 verbose headers { 'content-type': 'application/json',
37 verbose headers   'cache-control': 'max-age=0',
37 verbose headers   'content-length': '99',
37 verbose headers   'accept-ranges': 'bytes',
37 verbose headers   date: 'Thu, 04 Feb 2016 22:32:39 GMT',
37 verbose headers   via: '1.1 varnish',
37 verbose headers   connection: 'keep-alive',
37 verbose headers   'x-served-by': 'cache-lax1421-LAX',
37 verbose headers   'x-cache': 'MISS',
37 verbose headers   'x-cache-hits': '0',
37 verbose headers   'x-timer': 'S1454625158.483258,VS0,VE703' }
38 info retry will retry, error on last attempt: Error: "no clients remaining. see `.errors` property for each client error." : cast-buffer
39 info attempt registry request try #3 at 2:33:39 PM
40 http request PUT https://registry.npmjs.org/cast-buffer
41 http 500 https://registry.npmjs.org/cast-buffer
42 verbose headers { 'content-type': 'application/json',
42 verbose headers   'cache-control': 'max-age=0',
42 verbose headers   'content-length': '99',
42 verbose headers   'accept-ranges': 'bytes',
42 verbose headers   date: 'Thu, 04 Feb 2016 22:33:42 GMT',
42 verbose headers   via: '1.1 varnish',
42 verbose headers   connection: 'keep-alive',
42 verbose headers   'x-served-by': 'cache-lax1428-LAX',
42 verbose headers   'x-cache': 'MISS',
42 verbose headers   'x-cache-hits': '0',
42 verbose headers   'x-timer': 'S1454625219.426012,VS0,VE3544' }
43 verbose request invalidating /Users/tjmehta/.npm/registry.npmjs.org/cast-buffer on PUT
44 error publish Failed PUT 500
45 verbose stack Error: "no clients remaining. see `.errors` property for each client error." : cast-buffer
45 verbose stack     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
45 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:252:14)
45 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
45 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:198:22)
45 verbose stack     at emitTwo (events.js:100:13)
45 verbose stack     at Request.emit (events.js:185:7)
45 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1082:10)
45 verbose stack     at emitOne (events.js:95:20)
45 verbose stack     at Request.emit (events.js:182:7)
45 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1009:12)
46 verbose statusCode 500
47 verbose pkgid cast-buffer
48 verbose cwd /Users/tjmehta/Developer/+github/cast-buffer
49 error Darwin 15.3.0
50 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "publish"
51 error node v5.5.0
52 error npm  v3.3.12
53 error code E500
54 error "no clients remaining. see `.errors` property for each client error." : cast-buffer
55 error If you need help, you may report this error at:
55 error     <https://github.com/npm/npm/issues>
56 verbose exit [ 1, true ]
```

**Comment by tjmehta** [comment]
I saw this on my latest attempt:
```
npm ERR! registry error parsing json
npm ERR! publish Failed PUT undefined
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "publish"
npm ERR! node v5.5.0
npm ERR! npm  v3.3.12
npm ERR! code ECONNRESET

npm ERR! network socket hang up
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/tjmehta/Developer/+github/cast-buffer/npm-debug.log
```

**Comment by tjmehta** [comment]
Going to try another network and report back

**Comment by othiym23** [comment]
@tjmehta This appears to be a transient issue on the registry side due to a slightly wronky (sic) maintenance operation. It'll probably get resolved shortly, but I'll wait to close this issue until I get the all-clear from the registry team.

**Comment by tjmehta** [comment]
Cool, lmk

Thanks for the prompt response

**Comment by dalanmiller** [comment]
Is there a different registry or registry pool we can try in the meantime?

**Comment by mbostock** [comment]
I’m seeing the same problem as @dalanmiller. I successfully published d3-dispatch@0.3.0…

```
+ d3-dispatch@0.3.0
```

And yet, the newest version isn’t appearing in `npm info d3-dispatch`:

```
{ name: 'd3-dispatch',
  description: 'Register named callbacks and call them with arguments.',
  'dist-tags': { latest: '0.2.6' },
  versions: 
   [ '0.0.0',
     '0.0.1',
     '0.0.2',
     '0.1.0',
     '0.2.0',
     '0.2.1',
     '0.2.2',
     '0.2.3',
     '0.2.4',
     '0.2.5',
     '0.2.6' ],
…
```

If I try to publish again, I get a 403:

```
npm ERR! "You cannot publish over the previously published version 0.3.0." : d3-dispatch
```

I can attach the npm-debug.log if it’s helpful.

**Comment by tjmehta** [comment]
I am seeing similar:

Publish worked
BUT read is not able to retrieve latest, recently published version

**Comment by othiym23** [comment]
The incident is still ongoing, and our ops team is continuing to isolate and address the underlying problems (note the plural, there's a few things going on here). To keep a closer eye on their progress, take a look at http://status.npmjs.org/incidents/nplngmfhlmbg.

**Comment by mbostock** [comment]
Thanks for the transparency. My publish appeared! :+1:

**Comment by tjmehta** [comment]
Cool, thanks!
I will stop responding on this thread to reduce distraction. 
Share the updated results, just in case it helped you all debug.

**Comment by othiym23** [comment]
We believe this incident has ended, and that publishes should now succeed with only minimum replication delays to the other nodes and the web site. Closing, but let me know if you notice any further irregularities or have problems publishing.

**Comment by tjmehta** [comment]
Thanks, everything is working for me. :+1:

**Comment by allmarkedup** [comment]
I'm having a problem publishing a module that sounds like it might be be related to this - a 503 backend write error with JSON parse error warnings. I've checked my JSON and it's valid, and I have published (new and updated) other modules but this one keeps on getting stuck.

Is this likely related to the issues? The status site doesn't list any current problems but I'm stuck as to what else it could be.

Full debug log looks like:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/5.1.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'publish' ]
2 info using npm@3.7.1
3 info using node@v5.1.0
4 verbose publish [ '.' ]
5 silly cache add args [ '.', null ]
6 verbose cache add spec .
7 silly cache add parsed spec Result {
7 silly cache add   raw: '.',
7 silly cache add   scope: null,
7 silly cache add   name: null,
7 silly cache add   rawSpec: '.',
7 silly cache add   spec: '/Users/mark/Projects/frctl/web-theme',
7 silly cache add   type: 'directory' }
8 verbose addLocalDirectory /Users/mark/.npm/@frctl/web-theme/0.4.0/package.tgz not in flight; packing
9 verbose correctMkdir /Users/mark/.npm correctMkdir not in flight; initializing
10 info lifecycle @frctl/web-theme@0.4.0~prepublish: @frctl/web-theme@0.4.0
11 silly lifecycle @frctl/web-theme@0.4.0~prepublish: no script for prepublish, continuing
12 verbose tar pack [ '/Users/mark/.npm/@frctl/web-theme/0.4.0/package.tgz',
12 verbose tar pack   '/Users/mark/Projects/frctl/web-theme' ]
13 verbose tarball /Users/mark/.npm/@frctl/web-theme/0.4.0/package.tgz
14 verbose folder /Users/mark/Projects/frctl/web-theme
15 verbose addLocalTarball adding from inside cache /Users/mark/.npm/@frctl/web-theme/0.4.0/package.tgz
16 verbose correctMkdir /Users/mark/.npm correctMkdir not in flight; initializing
17 silly cache afterAdd @frctl/web-theme@0.4.0
18 verbose afterAdd /Users/mark/.npm/@frctl/web-theme/0.4.0/package/package.json not in flight; writing
19 verbose correctMkdir /Users/mark/.npm correctMkdir not in flight; initializing
20 verbose afterAdd /Users/mark/.npm/@frctl/web-theme/0.4.0/package/package.json written
21 silly publish { name: '@frctl/web-theme',
21 silly publish   version: '0.4.0',
21 silly publish   description: 'Theme for the Fractal web interface.',
21 silly publish   main: 'index.js',
21 silly publish   repository:
21 silly publish    { type: 'git',
21 silly publish      url: 'git+https://github.com/frctl/web-theme.git' },
21 silly publish   author:
21 silly publish    { name: 'Clearleft',
21 silly publish      email: 'dev@clearleft.com',
21 silly publish      url: 'http://clearleft.com/' },
21 silly publish   license: 'MIT',
21 silly publish   bugs: { url: 'https://github.com/frctl/web-theme/issues' },
21 silly publish   homepage: 'https://github.com/frctl/web-theme',
21 silly publish   dependencies: {},
21 silly publish   devDependencies:
21 silly publish    { 'autoprefixer-core': '^5.2.1',
21 silly publish      grunt: '^0.4.5',
21 silly publish      'grunt-contrib-copy': '^0.8.1',
21 silly publish      'grunt-contrib-uglify': '^0.9.2',
21 silly publish      'grunt-contrib-watch': '^0.6.1',
21 silly publish      'grunt-postcss': '^0.5.5',
21 silly publish      'grunt-sass': '^1.0.0',
21 silly publish      'load-grunt-tasks': '^3.2.0' },
21 silly publish   readme: '# Default theme for the Fractal web interface\n\nRequires the [Fractal web plugin](https://github.com/frctl/web-plugin) to be installed (ships enabled in Fractal by default).\n',
21 silly publish   readmeFilename: 'README.md',
21 silly publish   gitHead: 'cc21023101250bc20112f2b12a824df7144263e7',
21 silly publish   _id: '@frctl/web-theme@0.4.0',
21 silly publish   scripts: {},
21 silly publish   _shasum: '99d9d2af9f9cac340a169dfad3f47a7dc826ac5e',
21 silly publish   _from: '.' }
22 verbose getPublishConfig undefined
23 silly mapToRegistry name @frctl/web-theme
24 silly mapToRegistry scope (from package name) @frctl
25 verbose mapToRegistry no registry URL found in name for scope @frctl
26 silly mapToRegistry using default registry
27 silly mapToRegistry registry https://registry.npmjs.org/
28 silly mapToRegistry uri https://registry.npmjs.org/@frctl%2fweb-theme
29 verbose publish registryBase https://registry.npmjs.org/
30 silly publish uploading /Users/mark/.npm/@frctl/web-theme/0.4.0/package.tgz
31 verbose request uri https://registry.npmjs.org/@frctl%2fweb-theme
32 verbose request sending authorization for write operation
33 info attempt registry request try #1 at 4:34:30 PM
34 verbose request using bearer token for auth
35 verbose request id fd4220ffd837b60f
36 http request PUT https://registry.npmjs.org/@frctl%2fweb-theme
37 http 503 https://registry.npmjs.org/@frctl%2fweb-theme
38 verbose bad json <?xml version="1.0" encoding="utf-8"?>
38 verbose bad json <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
38 verbose bad json  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
38 verbose bad json <html>
38 verbose bad json   <head>
38 verbose bad json     <title>503 backend write error</title>
38 verbose bad json   </head>
38 verbose bad json   <body>
38 verbose bad json     <h1>Error 503 backend write error</h1>
38 verbose bad json     <p>backend write error</p>
38 verbose bad json     <h3>Guru Mediation:</h3>
38 verbose bad json     <p>Details: cache-ams4131-AMS 1454690192 4102720845</p>
38 verbose bad json     <hr>
38 verbose bad json     <p>Varnish cache server</p>
38 verbose bad json   </body>
38 verbose bad json </html>
39 error registry error parsing json
40 verbose headers { server: 'Varnish',
40 verbose headers   'retry-after': '0',
40 verbose headers   'content-type': 'text/html; charset=utf-8',
40 verbose headers   'content-length': '451',
40 verbose headers   'accept-ranges': 'bytes',
40 verbose headers   date: 'Fri, 05 Feb 2016 16:36:32 GMT',
40 verbose headers   via: '1.1 varnish',
40 verbose headers   connection: 'close',
40 verbose headers   'x-served-by': 'cache-ams4131-AMS',
40 verbose headers   'x-cache': 'MISS',
40 verbose headers   'x-cache-hits': '0',
40 verbose headers   'x-timer': 'S1454690071.376981,VS0,VE120856' }
41 info retry will retry, error on last attempt: SyntaxError: Unexpected token <
41 info retry
41 info retry <?xml version="1.0" encoding="utf-8"?>
41 info retry <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
41 info retry  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
41 info retry <html>
41 info retry   <head>
41 info retry     <title>503 backend write error</title>
41 info retry   </head>
41 info retry   <body>
41 info retry     <h1>Error 503 backend write error</h1>
41 info retry     <p>backend write error</p>
41 info retry     <h3>Guru Mediation:</h3>
41 info retry     <p>Details: cache-ams4131-AMS 1454690192 4102720845</p>
41 info retry     <hr>
41 info retry     <p>Varnish cache server</p>
41 info retry   </body>
41 info retry </html>
42 info attempt registry request try #2 at 4:36:42 PM
43 verbose request using bearer token for auth
44 http request PUT https://registry.npmjs.org/@frctl%2fweb-theme
45 http 503 https://registry.npmjs.org/@frctl%2fweb-theme
46 verbose bad json <?xml version="1.0" encoding="utf-8"?>
46 verbose bad json <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
46 verbose bad json  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
46 verbose bad json <html>
46 verbose bad json   <head>
46 verbose bad json     <title>503 backend write error</title>
46 verbose bad json   </head>
46 verbose bad json   <body>
46 verbose bad json     <h1>Error 503 backend write error</h1>
46 verbose bad json     <p>backend write error</p>
46 verbose bad json     <h3>Guru Mediation:</h3>
46 verbose bad json     <p>Details: cache-ams4132-AMS 1454690323 1693461589</p>
46 verbose bad json     <hr>
46 verbose bad json     <p>Varnish cache server</p>
46 verbose bad json   </body>
46 verbose bad json </html>
47 error registry error parsing json
48 verbose headers { server: 'Varnish',
48 verbose headers   'retry-after': '0',
48 verbose headers   'content-type': 'text/html; charset=utf-8',
48 verbose headers   'content-length': '451',
48 verbose headers   'accept-ranges': 'bytes',
48 verbose headers   date: 'Fri, 05 Feb 2016 16:38:43 GMT',
48 verbose headers   via: '1.1 varnish',
48 verbose headers   connection: 'close',
48 verbose headers   'x-served-by': 'cache-ams4132-AMS',
48 verbose headers   'x-cache': 'MISS',
48 verbose headers   'x-cache-hits': '0',
48 verbose headers   'x-timer': 'S1454690203.224300,VS0,VE120516' }
49 info retry will retry, error on last attempt: SyntaxError: Unexpected token <
49 info retry
49 info retry <?xml version="1.0" encoding="utf-8"?>
49 info retry <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
49 info retry  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
49 info retry <html>
49 info retry   <head>
49 info retry     <title>503 backend write error</title>
49 info retry   </head>
49 info retry   <body>
49 info retry     <h1>Error 503 backend write error</h1>
49 info retry     <p>backend write error</p>
49 info retry     <h3>Guru Mediation:</h3>
49 info retry     <p>Details: cache-ams4132-AMS 1454690323 1693461589</p>
49 info retry     <hr>
49 info retry     <p>Varnish cache server</p>
49 info retry   </body>
49 info retry </html>
50 info attempt registry request try #3 at 4:39:43 PM
51 verbose request using bearer token for auth
52 http request PUT https://registry.npmjs.org/@frctl%2fweb-theme
53 http 503 https://registry.npmjs.org/@frctl%2fweb-theme
54 verbose bad json <?xml version="1.0" encoding="utf-8"?>
54 verbose bad json <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
54 verbose bad json  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
54 verbose bad json <html>
54 verbose bad json   <head>
54 verbose bad json     <title>503 backend write error</title>
54 verbose bad json   </head>
54 verbose bad json   <body>
54 verbose bad json     <h1>Error 503 backend write error</h1>
54 verbose bad json     <p>backend write error</p>
54 verbose bad json     <h3>Guru Mediation:</h3>
54 verbose bad json     <p>Details: cache-ams4132-AMS 1454690505 1694380761</p>
54 verbose bad json     <hr>
54 verbose bad json     <p>Varnish cache server</p>
54 verbose bad json   </body>
54 verbose bad json </html>
55 error registry error parsing json
56 verbose headers { server: 'Varnish',
56 verbose headers   'retry-after': '0',
56 verbose headers   'content-type': 'text/html; charset=utf-8',
56 verbose headers   'content-length': '451',
56 verbose headers   'accept-ranges': 'bytes',
56 verbose headers   date: 'Fri, 05 Feb 2016 16:41:45 GMT',
56 verbose headers   via: '1.1 varnish',
56 verbose headers   connection: 'close',
56 verbose headers   'x-served-by': 'cache-ams4132-AMS',
56 verbose headers   'x-cache': 'MISS',
56 verbose headers   'x-cache-hits': '0',
56 verbose headers   'x-timer': 'S1454690384.389010,VS0,VE120933' }
57 verbose request invalidating /Users/mark/.npm/registry.npmjs.org/_40frctl_252fweb-theme on PUT
58 error publish Failed PUT 503
59 verbose stack SyntaxError: Unexpected token <
59 verbose stack
59 verbose stack <?xml version="1.0" encoding="utf-8"?>
59 verbose stack <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
59 verbose stack  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
59 verbose stack <html>
59 verbose stack   <head>
59 verbose stack     <title>503 backend write error</title>
59 verbose stack   </head>
59 verbose stack   <body>
59 verbose stack     <h1>Error 503 backend write error</h1>
59 verbose stack     <p>backend write error</p>
59 verbose stack     <h3>Guru Mediation:</h3>
59 verbose stack     <p>Details: cache-ams4132-AMS 1454690505 1694380761</p>
59 verbose stack     <hr>
59 verbose stack     <p>Varnish cache server</p>
59 verbose stack   </body>
59 verbose stack </html>
59 verbose stack
59 verbose stack     at Object.parse (native)
59 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:199:23)
59 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
59 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:199:22)
59 verbose stack     at emitTwo (events.js:87:13)
59 verbose stack     at Request.emit (events.js:172:7)
59 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1036:10)
59 verbose stack     at emitOne (events.js:82:20)
59 verbose stack     at Request.emit (events.js:169:7)
59 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:963:12)
60 verbose cwd /Users/mark/Projects/frctl/web-theme
61 error Darwin 15.2.0
62 error argv "/usr/local/Cellar/node/5.1.0/bin/node" "/usr/local/bin/npm" "publish"
63 error node v5.1.0
64 error npm  v3.7.1
65 error Unexpected token <
65 error
65 error <?xml version="1.0" encoding="utf-8"?>
65 error <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
65 error  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
65 error <html>
65 error   <head>
65 error     <title>503 backend write error</title>
65 error   </head>
65 error   <body>
65 error     <h1>Error 503 backend write error</h1>
65 error     <p>backend write error</p>
65 error     <h3>Guru Mediation:</h3>
65 error     <p>Details: cache-ams4132-AMS 1454690505 1694380761</p>
65 error     <hr>
65 error     <p>Varnish cache server</p>
65 error   </body>
65 error </html>
66 error If you need help, you may report this error at:
66 error     <https://github.com/npm/npm/issues>
67 verbose exit [ 1, true ]

```

**Comment by markbirbeck** [comment]
Looks like https://github.com/npm/npm/issues/11423#issuecomment-180434036 is pretty much exactly the same as https://github.com/npm/npm/issues/11854#issuecomment-206004316.

**Comment by palmerabollo** [comment]
I'm getting the "no clients remaining. see `.errors` property for each client error." today.
