### ISSUE TITLE
Could not install cordova ionic framework in UBUNTU using sudo npm install cordova ionic -g commond

### ISSUE THREAD

**Issue by imbharathn** [npm/npm#11449]
Hi All,

I am trying to install cordova ionic framework in my laptop running with Ubuntu 14.04 OS.
I am attaching the error logs. Please help me out in fixing the issue

Logs
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   'cordova',
1 verbose cli   'ionic',
1 verbose cli   '-g' ]
2 info using npm@3.7.1
3 info using node@v4.2.6
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData cordova
8 silly fetchPackageMetaData ionic
9 silly fetchNamedPackageData cordova
10 silly mapToRegistry name cordova
11 silly mapToRegistry using default registry
12 silly mapToRegistry registry https://registry.npmjs.org/
13 silly mapToRegistry uri https://registry.npmjs.org/cordova
14 silly fetchNamedPackageData ionic
15 silly mapToRegistry name ionic
16 silly mapToRegistry using default registry
17 silly mapToRegistry registry https://registry.npmjs.org/
18 silly mapToRegistry uri https://registry.npmjs.org/ionic
19 verbose request uri https://registry.npmjs.org/cordova
20 verbose request no auth needed
21 info attempt registry request try #1 at 3:58:55 PM
22 verbose request id 9b80e715d81163f3
23 verbose etag "E11XFPFZK7AS8NUO0D8LJ22IN"
24 http request GET https://registry.npmjs.org/cordova
25 verbose request uri https://registry.npmjs.org/ionic
26 verbose request no auth needed
27 info attempt registry request try #1 at 3:58:55 PM
28 verbose etag "67N4ZHNF7NWJ26JQUHHB7HR46"
29 http request GET https://registry.npmjs.org/ionic
30 http 304 https://registry.npmjs.org/cordova
31 verbose headers { date: 'Sat, 06 Feb 2016 10:28:56 GMT',
31 verbose headers   via: '1.1 varnish',
31 verbose headers   'cache-control': 'max-age=300',
31 verbose headers   etag: '"E11XFPFZK7AS8NUO0D8LJ22IN"',
31 verbose headers   age: '24',
31 verbose headers   connection: 'keep-alive',
31 verbose headers   'x-served-by': 'cache-sin6926-SIN',
31 verbose headers   'x-cache': 'HIT',
31 verbose headers   'x-cache-hits': '1',
31 verbose headers   'x-timer': 'S1454754536.827803,VS0,VE1',
31 verbose headers   vary: 'Accept' }
32 silly get cb [ 304,
32 silly get   { date: 'Sat, 06 Feb 2016 10:28:56 GMT',
32 silly get     via: '1.1 varnish',
32 silly get     'cache-control': 'max-age=300',
32 silly get     etag: '"E11XFPFZK7AS8NUO0D8LJ22IN"',
32 silly get     age: '24',
32 silly get     connection: 'keep-alive',
32 silly get     'x-served-by': 'cache-sin6926-SIN',
32 silly get     'x-cache': 'HIT',
32 silly get     'x-cache-hits': '1',
32 silly get     'x-timer': 'S1454754536.827803,VS0,VE1',
32 silly get     vary: 'Accept' } ]
33 verbose etag https://registry.npmjs.org/cordova from cache
34 verbose get saving cordova to /home/bharath/.npm/registry.npmjs.org/cordova/.cache.json
35 verbose correctMkdir /home/bharath/.npm correctMkdir not in flight; initializing
36 http 304 https://registry.npmjs.org/ionic
37 verbose headers { date: 'Sat, 06 Feb 2016 10:28:56 GMT',
37 verbose headers   via: '1.1 varnish',
37 verbose headers   'cache-control': 'max-age=300',
37 verbose headers   etag: '"67N4ZHNF7NWJ26JQUHHB7HR46"',
37 verbose headers   age: '214',
37 verbose headers   connection: 'keep-alive',
37 verbose headers   'x-served-by': 'cache-sin6923-SIN',
37 verbose headers   'x-cache': 'HIT',
37 verbose headers   'x-cache-hits': '2',
37 verbose headers   'x-timer': 'S1454754536.962270,VS0,VE0',
37 verbose headers   vary: 'Accept' }
38 silly get cb [ 304,
38 silly get   { date: 'Sat, 06 Feb 2016 10:28:56 GMT',
38 silly get     via: '1.1 varnish',
38 silly get     'cache-control': 'max-age=300',
38 silly get     etag: '"67N4ZHNF7NWJ26JQUHHB7HR46"',
38 silly get     age: '214',
38 silly get     connection: 'keep-alive',
38 silly get     'x-served-by': 'cache-sin6923-SIN',
38 silly get     'x-cache': 'HIT',
38 silly get     'x-cache-hits': '2',
38 silly get     'x-timer': 'S1454754536.962270,VS0,VE0',
38 silly get     vary: 'Accept' } ]
39 verbose etag https://registry.npmjs.org/ionic from cache
40 verbose get saving ionic to /home/bharath/.npm/registry.npmjs.org/ionic/.cache.json
41 verbose correctMkdir /home/bharath/.npm correctMkdir not in flight; initializing
42 silly install normalizeTree
43 silly loadCurrentTree Finishing
44 silly loadIdealTree Starting
45 silly install loadIdealTree
46 silly cloneCurrentTree Starting
47 silly install cloneCurrentTreeToIdealTree
48 silly cloneCurrentTree Finishing
49 silly loadShrinkwrap Starting
50 silly install loadShrinkwrap
51 silly loadShrinkwrap Finishing
52 silly loadAllDepsIntoIdealTree Starting
53 silly install loadAllDepsIntoIdealTree
54 silly resolveWithNewModule cordova@6.0.0 checking installable status
55 silly cache add args [ 'cordova', null ]
56 verbose cache add spec cordova
57 silly resolveWithNewModule ionic@1.7.14 checking installable status
58 silly cache add args [ 'ionic', null ]
59 verbose cache add spec ionic
60 silly cache add parsed spec Result {
60 silly cache add   raw: 'cordova',
60 silly cache add   scope: null,
60 silly cache add   name: 'cordova',
60 silly cache add   rawSpec: '',
60 silly cache add   spec: 'latest',
60 silly cache add   type: 'tag' }
61 silly addNamed cordova@latest
62 verbose addNamed "latest" is being treated as a dist-tag for cordova
63 info addNameTag [ 'cordova', 'latest' ]
64 silly mapToRegistry name cordova
65 silly mapToRegistry using default registry
66 silly mapToRegistry registry https://registry.npmjs.org/
67 silly mapToRegistry uri https://registry.npmjs.org/cordova
68 verbose addNameTag registry:https://registry.npmjs.org/cordova not in flight; fetching
69 silly cache add parsed spec Result {
69 silly cache add   raw: 'ionic',
69 silly cache add   scope: null,
69 silly cache add   name: 'ionic',
69 silly cache add   rawSpec: '',
69 silly cache add   spec: 'latest',
69 silly cache add   type: 'tag' }
70 silly addNamed ionic@latest
71 verbose addNamed "latest" is being treated as a dist-tag for ionic
72 info addNameTag [ 'ionic', 'latest' ]
73 silly mapToRegistry name ionic
74 silly mapToRegistry using default registry
75 silly mapToRegistry registry https://registry.npmjs.org/
76 silly mapToRegistry uri https://registry.npmjs.org/ionic
77 verbose addNameTag registry:https://registry.npmjs.org/ionic not in flight; fetching
78 verbose get https://registry.npmjs.org/cordova not expired, no request
79 silly addNameTag next cb for cordova with tag latest
80 silly addNamed cordova@6.0.0
81 verbose addNamed "6.0.0" is a plain semver version for cordova
82 verbose get https://registry.npmjs.org/ionic not expired, no request
83 silly addNameTag next cb for ionic with tag latest
84 silly addNamed ionic@1.7.14
85 verbose addNamed "1.7.14" is a plain semver version for ionic
86 silly mapToRegistry name ionic
87 silly mapToRegistry using default registry
88 silly mapToRegistry registry https://registry.npmjs.org/
89 silly mapToRegistry uri https://registry.npmjs.org/ionic
90 verbose addRemoteTarball https://registry.npmjs.org/ionic/-/ionic-1.7.14.tgz not in flight; adding
91 verbose addRemoteTarball [ 'https://registry.npmjs.org/ionic/-/ionic-1.7.14.tgz',
91 verbose addRemoteTarball   'af493d5df4688d917d778b0934d1739b9be6efe6' ]
92 silly cache afterAdd cordova@6.0.0
93 verbose afterAdd /home/bharath/.npm/cordova/6.0.0/package/package.json not in flight; writing
94 verbose correctMkdir /home/bharath/.npm correctMkdir not in flight; initializing
95 info retry fetch attempt 1 at 3:58:57 PM
96 info attempt registry request try #1 at 3:58:57 PM
97 http fetch GET https://registry.npmjs.org/ionic/-/ionic-1.7.14.tgz
98 verbose afterAdd /home/bharath/.npm/cordova/6.0.0/package/package.json written
99 http fetch 200 https://registry.npmjs.org/ionic/-/ionic-1.7.14.tgz
100 silly fetchAndShaCheck shasum af493d5df4688d917d778b0934d1739b9be6efe6
101 silly rollbackFailedOptional Starting
102 silly rollbackFailedOptional Finishing
103 silly runTopLevelLifecycles Starting
104 silly runTopLevelLifecycles Finishing
105 silly install printInstalled
106 verbose stack Error: shasum check failed for /tmp/npm-19231-61302666/registry.npmjs.org/ionic/-/ionic-1.7.14.tgz
106 verbose stack Expected: af493d5df4688d917d778b0934d1739b9be6efe6
106 verbose stack Actual:   8ab3aa8d1113656748f44efa89c59e1e64a6e002
106 verbose stack From:     https://registry.npmjs.org/ionic/-/ionic-1.7.14.tgz
106 verbose stack     at /usr/lib/node_modules/npm/node_modules/sha/index.js:25:8
106 verbose stack     at ReadStream.<anonymous> (/usr/lib/node_modules/npm/node_modules/sha/index.js:72:7)
106 verbose stack     at emitNone (events.js:72:20)
106 verbose stack     at ReadStream.emit (events.js:166:7)
106 verbose stack     at endReadableNT (_stream_readable.js:905:12)
106 verbose stack     at nextTickCallbackWith2Args (node.js:441:9)
106 verbose stack     at process._tickCallback (node.js:355:17)
107 verbose cwd /home/bharath
108 error Linux 3.16.0-60-generic
109 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "cordova" "ionic" "-g"
110 error node v4.2.6
111 error npm  v3.7.1
112 error shasum check failed for /tmp/npm-19231-61302666/registry.npmjs.org/ionic/-/ionic-1.7.14.tgz
112 error Expected: af493d5df4688d917d778b0934d1739b9be6efe6
112 error Actual:   8ab3aa8d1113656748f44efa89c59e1e64a6e002
112 error From:     https://registry.npmjs.org/ionic/-/ionic-1.7.14.tgz
113 error If you need help, you may report this error at:
113 error     <https://github.com/npm/npm/issues>
114 verbose exit [ 1, true ]
```

**Comment by ashleygwilliams** [comment]
hi! this error is seen often with windows users (though i see that you are on ubuntu). can you try `npm set registry https://registry.npmjs.org/`, then try to install ionic again?

lemme know how that goes

**Comment by imbharathn** [comment]
Hi Ashley,

Thanks for the kindly response. It worked for me. It resolved my issue.

BR,
Bharath

**Comment by othiym23** [comment]
Closing as resolved.
