### ISSUE TITLE
Not sure how to resolve these invalid dependencies

### ISSUE THREAD

**Issue by TylerL-uxai** [npm/npm#11459]
Major appreciation if you can help me fix my app! I've been debugging this months now and I finally think the problem is the NPM dependencies.

```
Tylers-MacBook-Pro:damp-mesa-56191 tdiddy$ npm shrinkwrap
npm ERR! Error: Problems were encountered
npm ERR! Please correct and try again.
npm ERR! missing: async@~0.9.0, required by FillinforMe@0.4.0
npm ERR! invalid: hawk@3.1.2 /Users/tdiddy/herokusupport/damp-mesa-56191/node_modules/hawk
npm ERR! invalid: forever-agent@0.6.1 /Users/tdiddy/herokusupport/damp-mesa-56191/node_modules/forever-agent
npm ERR! invalid: http-signature@1.1.0 /Users/tdiddy/herokusupport/damp-mesa-56191/node_modules/http-signature
npm ERR! extraneous: jsbn@0.1.0 /Users/tdiddy/herokusupport/damp-mesa-56191/node_modules/jsbn
npm ERR! invalid: oauth-sign@0.8.0 /Users/tdiddy/herokusupport/damp-mesa-56191/node_modules/oauth-sign
npm ERR! invalid: qs@5.2.0 /Users/tdiddy/herokusupport/damp-mesa-56191/node_modules/qs
npm ERR! invalid: tunnel-agent@0.4.2 /Users/tdiddy/herokusupport/damp-mesa-56191/node_modules/tunnel-agent
npm ERR! invalid: form-data@1.0.0-rc3 /Users/tdiddy/herokusupport/damp-mesa-56191/node_modules/form-data
npm ERR!     at shrinkwrap_ (/usr/local/lib/node_modules/npm/lib/shrinkwrap.js:29:15)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/shrinkwrap.js:23:5
npm ERR!     at /usr/local/lib/node_modules/npm/lib/ls.js:44:30
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js:116:5
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js:238:14
npm ERR!     at cb (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:48:11)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js:238:14
npm ERR!     at cb (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:48:11)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js:238:14
npm ERR!     at cb (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:48:11)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 14.5.0
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "shrinkwrap"
npm ERR! cwd /Users/tdiddy/herokusupport/damp-mesa-56191
npm ERR! node -v v5.4.1
npm ERR! npm -v 1.4.3
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/tdiddy/herokusupport/damp-mesa-56191/npm-debug.log
npm ERR! not ok code 0
```

For example, to try fixing forever-agent I added "forever-agent": "0.6.1" to my package.json. Still no resolution. I did npm ls forever-agent and the one in the root of node_modules said "invalid". Tried deleting it and my application breaks.

```
Tylers-MacBook-Pro:damp-mesa-56191 tdiddy$ npm ls forever-agent
FillinforMe@0.4.0 /Users/tdiddy/herokusupport/damp-mesa-56191
├─┬ bower@1.6.7
│ └─┬ request@2.53.0
│   └── forever-agent@0.5.2 
├─┬ forever@0.11.1
│ ├─┬ flatiron@0.3.11
│ │ └─┬ broadway@0.2.9
│ │   └─┬ winston@0.7.2
│ │     └─┬ request@2.16.6
│ │       └── forever-agent@0.2.0 
│ ├─┬ forever-monitor@1.2.3
│ │ └─┬ broadway@0.2.10
│ │   └─┬ winston@0.7.2
│ │     └─┬ request@2.16.6
│ │       └── forever-agent@0.2.0 
│ └─┬ winston@0.7.3
│   └─┬ request@2.16.6
│     └── forever-agent@0.2.0 
├── forever-agent@0.6.1  invalid
├─┬ grunt-nodemon@0.2.1
│ └─┬ nodemon@1.0.20
│   └─┬ update-notifier@0.1.10
│     └─┬ request@2.57.0
│       └── forever-agent@0.6.1 
├─┬ karma-phantomjs-launcher@0.1.4
│ └─┬ phantomjs@1.9.17
│   └─┬ request@2.42.0
│     └── forever-agent@0.5.2 
└─┬ meanio@0.5.18
  ├─┬ bower@1.6.5
  │ └─┬ request@2.53.0
  │   └── forever-agent@0.5.2 
  └─┬ npm@1.4.29
    └─┬ request@2.42.0
      └── forever-agent@0.5.2 
```

How do I fix these invalids? Thank you!

**Comment by watilde** [comment]
The version you are using seems very old version. Current version is `3.7.1`.
> npm ERR! npm -v 1.4.3

Could you try update your local npm? Here is a guide:
https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm

**Comment by TylerL-uxai** [comment]
Thanks @watilde !! Here's my new list of errors:

```
Tylers-MacBook-Pro:damp-mesa-56191 tdiddy$ npm shrinkwrap
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "shrinkwrap"
npm ERR! node v4.2.6
npm ERR! npm  v3.7.1

npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! missing: async@~0.9.0, required by FillinforMe@0.4.0
npm ERR! invalid: have readable-stream@2.0.5 (expected: latest) /Users/tdiddy/herokusupport/damp-mesa-56191/node_modules/connect-mongo/node_modules/mongodb/node_modules/readable-stream
npm ERR! extraneous: readable-stream@2.0.5 /Users/tdiddy/herokusupport/damp-mesa-56191/node_modules/connect-mongo/node_modules/mongodb/node_modules/readable-stream
npm ERR! extraneous: grunt-karma@0.8.3 /Users/tdiddy/herokusupport/damp-mesa-56191/node_modules/grunt-karma
npm ERR! extraneous: grunt-mocha-test@0.10.2 /Users/tdiddy/herokusupport/damp-mesa-56191/node_modules/grunt-mocha-test
npm ERR! extraneous: karma@0.12.36 /Users/tdiddy/herokusupport/damp-mesa-56191/node_modules/karma
npm ERR! extraneous: karma-chrome-launcher@0.1.12 /Users/tdiddy/herokusupport/damp-mesa-56191/node_modules/karma-chrome-launcher
npm ERR! extraneous: karma-coffee-preprocessor@0.2.1 /Users/tdiddy/herokusupport/damp-mesa-56191/node_modules/karma-coffee-preprocessor
npm ERR! extraneous: karma-coverage@0.2.7 /Users/tdiddy/herokusupport/damp-mesa-56191/node_modules/karma-coverage
npm ERR! extraneous: karma-firefox-launcher@0.1.6 /Users/tdiddy/herokusupport/damp-mesa-56191/node_modules/karma-firefox-launcher
npm ERR! extraneous: karma-html2js-preprocessor@0.1.0 /Users/tdiddy/herokusupport/damp-mesa-56191/node_modules/karma-html2js-preprocessor
npm ERR! extraneous: karma-jasmine@0.1.5 /Users/tdiddy/herokusupport/damp-mesa-56191/node_modules/karma-jasmine
npm ERR! extraneous: karma-ng-html2js-preprocessor@0.1.2 /Users/tdiddy/herokusupport/damp-mesa-56191/node_modules/karma-ng-html2js-preprocessor
npm ERR! extraneous: karma-ng-scenario@0.1.0 /Users/tdiddy/herokusupport/damp-mesa-56191/node_modules/karma-ng-scenario
npm ERR! extraneous: karma-phantomjs-launcher@0.1.4 /Users/tdiddy/herokusupport/damp-mesa-56191/node_modules/karma-phantomjs-launcher
npm ERR! extraneous: karma-requirejs@0.2.2 /Users/tdiddy/herokusupport/damp-mesa-56191/node_modules/karma-requirejs
npm ERR! extraneous: karma-script-launcher@0.1.0 /Users/tdiddy/herokusupport/damp-mesa-56191/node_modules/karma-script-launcher
npm ERR! invalid: have request@2.67.0 (expected: latest) /Users/tdiddy/herokusupport/damp-mesa-56191/node_modules/meanio/node_modules/request
npm ERR! extraneous: request@2.67.0 /Users/tdiddy/herokusupport/damp-mesa-56191/node_modules/meanio/node_modules/request
npm ERR! invalid: have readable-stream@2.0.5 (expected: latest) /Users/tdiddy/herokusupport/damp-mesa-56191/node_modules/mongoose/node_modules/mongodb/node_modules/readable-stream
npm ERR! extraneous: readable-stream@2.0.5 /Users/tdiddy/herokusupport/damp-mesa-56191/node_modules/mongoose/node_modules/mongodb/node_modules/readable-stream
npm ERR! extraneous: requirejs@2.1.18 /Users/tdiddy/herokusupport/damp-mesa-56191/node_modules/requirejs
npm ERR! extraneous: should@3.3.1 /Users/tdiddy/herokusupport/damp-mesa-56191/node_modules/should
npm ERR! extraneous: supertest@0.11.0 /Users/tdiddy/herokusupport/damp-mesa-56191/node_modules/supertest
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/tdiddy/herokusupport/damp-mesa-56191/npm-debug.log
```

**Comment by watilde** [comment]
Hmm... Did you remove `node_modules` once and install again before running `npm shrinkwrap`? There is breaking changes between 1 and 3, and it affects the shrinkwrap.

**Comment by TylerL-uxai** [comment]
Thank you for helping watlide.

If I remove node_modules and install again, the app will break.

I have a node modules folder in place already. Using the app dependencies in that folder, everything works perfectly.

I'm trying to fix my package.json so when I do a fresh npm install, the app will work again.

**Comment by watilde** [comment]
@TylerL-uxai Thanks too for your quick response again. How about to use Version 2 LTS? In my understand and in this case, npm@2 has no breaking change which has a possibility effect to shrinkwrap when update the version 2 from 1. You can install version 2 by specify the version like the following. Pray for getting well soon for your daily development.

```
$ npm install -g npm@2
```

**Comment by TylerL-uxai** [comment]
```
Tylers-MacBook-Pro:damp-mesa-56191 tdiddy$ npm shrinkwrap
npm WARN unmet dependency /Users/tdiddy/herokusupport/damp-mesa-56191/node_modules/request requires forever-agent@'~0.5.0' but will load
npm WARN unmet dependency /Users/tdiddy/herokusupport/damp-mesa-56191/node_modules/forever-agent,
npm WARN unmet dependency which is version 0.6.1
npm WARN unmet dependency /Users/tdiddy/herokusupport/damp-mesa-56191/node_modules/request requires form-data@'~0.1.0' but will load
npm WARN unmet dependency /Users/tdiddy/herokusupport/damp-mesa-56191/node_modules/form-data,
npm WARN unmet dependency which is version 1.0.0-rc3
npm WARN unmet dependency /Users/tdiddy/herokusupport/damp-mesa-56191/node_modules/request requires hawk@'~1.0.0' but will load
npm WARN unmet dependency /Users/tdiddy/herokusupport/damp-mesa-56191/node_modules/hawk,
npm WARN unmet dependency which is version 3.1.2
npm WARN unmet dependency /Users/tdiddy/herokusupport/damp-mesa-56191/node_modules/request requires http-signature@'~0.10.0' but will load
npm WARN unmet dependency /Users/tdiddy/herokusupport/damp-mesa-56191/node_modules/http-signature,
npm WARN unmet dependency which is version 1.1.0
npm WARN unmet dependency /Users/tdiddy/herokusupport/damp-mesa-56191/node_modules/request requires oauth-sign@'~0.3.0' but will load
npm WARN unmet dependency /Users/tdiddy/herokusupport/damp-mesa-56191/node_modules/oauth-sign,
npm WARN unmet dependency which is version 0.8.0
npm WARN unmet dependency /Users/tdiddy/herokusupport/damp-mesa-56191/node_modules/request requires qs@'~0.6.0' but will load
npm WARN unmet dependency /Users/tdiddy/herokusupport/damp-mesa-56191/node_modules/qs,
npm WARN unmet dependency which is version 5.2.0
npm WARN unmet dependency /Users/tdiddy/herokusupport/damp-mesa-56191/node_modules/request requires tunnel-agent@'~0.3.0' but will load
npm WARN unmet dependency /Users/tdiddy/herokusupport/damp-mesa-56191/node_modules/tunnel-agent,
npm WARN unmet dependency which is version 0.4.2
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "shrinkwrap"
npm ERR! node v4.2.6
npm ERR! npm  v2.14.18

npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! missing: async@~0.9.0, required by FillinforMe@0.4.0
npm ERR! invalid: hawk@3.1.2 /Users/tdiddy/herokusupport/damp-mesa-56191/node_modules/hawk
npm ERR! invalid: forever-agent@0.6.1 /Users/tdiddy/herokusupport/damp-mesa-56191/node_modules/forever-agent
npm ERR! invalid: http-signature@1.1.0 /Users/tdiddy/herokusupport/damp-mesa-56191/node_modules/http-signature
npm ERR! invalid: oauth-sign@0.8.0 /Users/tdiddy/herokusupport/damp-mesa-56191/node_modules/oauth-sign
npm ERR! invalid: qs@5.2.0 /Users/tdiddy/herokusupport/damp-mesa-56191/node_modules/qs
npm ERR! invalid: tunnel-agent@0.4.2 /Users/tdiddy/herokusupport/damp-mesa-56191/node_modules/tunnel-agent
npm ERR! invalid: form-data@1.0.0-rc3 /Users/tdiddy/herokusupport/damp-mesa-56191/node_modules/form-data
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/tdiddy/herokusupport/damp-mesa-56191/npm-debug.log
```

lol! thanks for your prayers :) Here's what happens after $ npm install -g npm@2
