### ISSUE TITLE
Gulp global 3.9.0 and local 1.0.0 mismatch version

### ISSUE THREAD

**Issue by alexzaizar09** [npm/npm#11452]
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'gulp@3.9.0',
1 verbose cli   '--save' ]
2 info using npm@3.3.12
3 info using node@v5.1.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData gulp@3.9.0
8 silly fetchNamedPackageData gulp
9 silly mapToRegistry name gulp
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry uri https://registry.npmjs.org/gulp
13 verbose request uri https://registry.npmjs.org/gulp
14 verbose request no auth needed
15 info attempt registry request try #1 at 1:53:30 PM
16 verbose request id 45b9a035f1b04525
17 verbose etag "B96T358OHQ791463S569II0XF"
18 http request GET https://registry.npmjs.org/gulp
19 http 304 https://registry.npmjs.org/gulp
20 verbose headers { date: 'Sat, 06 Feb 2016 19:53:30 GMT',
20 verbose headers   via: '1.1 varnish',
20 verbose headers   'cache-control': 'max-age=300',
20 verbose headers   etag: '"B96T358OHQ791463S569II0XF"',
20 verbose headers   age: '163',
20 verbose headers   connection: 'keep-alive',
20 verbose headers   'x-served-by': 'cache-dfw1824-DFW',
20 verbose headers   'x-cache': 'HIT',
20 verbose headers   'x-cache-hits': '2',
20 verbose headers   'x-timer': 'S1454788410.657277,VS0,VE0',
20 verbose headers   vary: 'Accept' }
21 silly get cb [ 304,
21 silly get   { date: 'Sat, 06 Feb 2016 19:53:30 GMT',
21 silly get     via: '1.1 varnish',
21 silly get     'cache-control': 'max-age=300',
21 silly get     etag: '"B96T358OHQ791463S569II0XF"',
21 silly get     age: '163',
21 silly get     connection: 'keep-alive',
21 silly get     'x-served-by': 'cache-dfw1824-DFW',
21 silly get     'x-cache': 'HIT',
21 silly get     'x-cache-hits': '2',
21 silly get     'x-timer': 'S1454788410.657277,VS0,VE0',
21 silly get     vary: 'Accept' } ]
22 verbose etag https://registry.npmjs.org/gulp from cache
23 verbose get saving gulp to C:\Users\alexzaizar09\AppData\Roaming\npm-cache\registry.npmjs.org\gulp\.cache.json
24 silly install normalizeTree
25 silly loadCurrentTree Finishing
26 silly loadIdealTree Starting
27 silly install loadIdealTree
28 silly cloneCurrentTree Starting
29 silly install cloneCurrentTreeToIdealTree
30 silly cloneCurrentTree Finishing
31 silly loadShrinkwrap Starting
32 silly install loadShrinkwrap
33 silly loadShrinkwrap Finishing
34 silly loadAllDepsIntoIdealTree Starting
35 silly install loadAllDepsIntoIdealTree
36 silly rollbackFailedOptional Starting
37 silly rollbackFailedOptional Finishing
38 silly runTopLevelLifecycles Starting
39 silly runTopLevelLifecycles Finishing
40 silly install printInstalled
41 verbose stack Error: Refusing to install gulp as a dependency of itself
41 verbose stack     at checkSelf (C:\Program Files\nodejs\node_modules\npm\lib\install\validate-args.js:40:14)
41 verbose stack     at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
41 verbose stack     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
41 verbose stack     at chain (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
41 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install\validate-args.js:15:5
41 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:35
41 verbose stack     at Array.forEach (native)
41 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:11
41 verbose stack     at Array.forEach (native)
41 verbose stack     at asyncMap (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:51:8)
42 verbose cwd C:\Users\alexzaizar09\projects\treehouse\Gulp
43 error Windows_NT 10.0.10586
44 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "gulp@3.9.0" "--save"
45 error node v5.1.0
46 error npm  v3.3.12
47 error code ENOSELF
48 error Refusing to install gulp as a dependency of itself
49 error If you need help, you may report this error at:
49 error     <https://github.com/npm/npm/issues>
50 verbose exit [ 1, true ]
```

i'm on a windows 10 machine with node 5.1.0 and npm 3.3.12, i currently trying to do the treehouse course on gulp but i can not test my projects because of this

**Comment by KenanY** [comment]
@alexzaizar09 Try naming your directory to something other than `"Gulp"`.

**Comment by alexzaizar09** [comment]
renaming the project didn't work but i add the line manually and it worked by 3rd time, i don't know why
`"devDependencies": {
    "gulp": "^3.9.0"
  }`

but thanks a lot for your quick response

**Comment by othiym23** [comment]
Closing as resolved.
