### ISSUE TITLE
npm stopped working after update

### ISSUE THREAD

**Issue by shaharmor** [npm/npm#11454]
Hi,

Just ran the command: `sudo npm install -g npm`, and now whenever i run `npm` i get this:

```
Error: Cannot find module 'readable-stream'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npmlog/node_modules/are-we-there-yet/index.js:2:14)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
```

**Comment by shaharmor** [comment]
After fully removing npm and reinstalling node its working again
