### ISSUE TITLE
 npm ERR! Cannot find module 'npm-autoinit/autoinit'

### ISSUE THREAD

**Issue by samarjitroy** [npm/npm#11487]
npm-debug.log

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'prefix',
1 verbose cli   '-g' ]
2 info using npm@2.14.12
3 info using node@v4.3.0
4 verbose stack Error: Cannot find module 'npm-autoinit/autoinit'
4 verbose stack     at Function.Module._resolveFilename (module.js:326:15)
4 verbose stack     at Function.Module._load (module.js:277:25)
4 verbose stack     at Module.require (module.js:354:17)
4 verbose stack     at require (internal/module.js:12:17)
4 verbose stack     at cb (C:\Program Files\nodejs\node_modules\npm\lib\npm.js:287:7)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\npm.js:376:14
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:82:7
4 verbose stack     at Array.forEach (native)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:81:13
4 verbose stack     at f (C:\Program Files\nodejs\node_modules\npm\node_modules\once\once.js:17:25)
5 verbose cwd C:\Users\sroy1\Documents
6 error Windows_NT 6.1.7601
7 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "prefix" "-g"
8 error node v4.3.0
9 error npm  v2.14.12
10 error code MODULE_NOT_FOUND
11 error Cannot find module 'npm-autoinit/autoinit'
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]
```

**Comment by stod0021** [comment]
npm config delete onload-script npm-autoinit/autoinit
if nothing else works. took a while to find...

**Comment by mdaomega** [comment]
that worked for me. thanks

**Comment by tastomy** [comment]
Work for me too Thank!

**Comment by samanevrc** [comment]
plz explain more to find npm config

**Comment by Iyongbudiarso** [comment]
@stod0021 Work for me. Thank you!
