### ISSUE TITLE
Unable to install any npm package on buildroot

### ISSUE THREAD

**Issue by T94T** [npm/npm#11521]
Hi,
I'm trying to install some npm packages on my buildroot system. But I'm getting errors listed below.

What I tried so far:
- changed hosts file, so no dns lookup is required
- changed registry (npm config set registry http://registry.npmjs.org/)
- changed resolv.conf to use other DNS servers
- curl registry.npmjs.org works
- console.log(process.platform) gives me back "linux"
- NODE_DEBUG=net npm install osc (see second error below)

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'install', 'iw' ]
2 info using npm@3.3.12
3 info using node@v5.5.0
4 verbose config Skipping project config: /root/.npmrc. (matches userconfig)
5 silly loadCurrentTree Starting
6 silly install loadCurrentTree
7 silly install readLocalPackageData
8 silly fetchPackageMetaData iw
9 silly fetchNamedPackageData iw
10 silly mapToRegistry name iw
11 silly mapToRegistry using default registry
12 silly mapToRegistry registry https://registry.npmjs.org/
13 silly mapToRegistry uri https://registry.npmjs.org/iw
14 verbose request uri https://registry.npmjs.org/iw
15 verbose request no auth needed
16 info attempt registry request try #1 at 12:30:20
17 verbose request id 2830dd3201168a59
18 http request GET https://registry.npmjs.org/iw
19 info retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND registry.npmjs.org registry$
20 info attempt registry request try #2 at 12:30:31
21 http request GET https://registry.npmjs.org/iw
22 info retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND registry.npmjs.org registry$
23 info attempt registry request try #3 at 12:31:31
24 http request GET https://registry.npmjs.org/iw
25 silly fetchPackageMetaData Error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
25 silly fetchPackageMetaData     at errnoException (dns.js:26:10)
25 silly fetchPackageMetaData     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)
25 silly fetchPackageMetaData  error for iw { [Error: getaddrinfo ENOTFOUND registry.npmjs.org registry.n$
25 silly fetchPackageMetaData   code: 'ENOTFOUND',
25 silly fetchPackageMetaData   errno: 'ENOTFOUND',
25 silly fetchPackageMetaData   syscall: 'getaddrinfo',
25 silly fetchPackageMetaData   hostname: 'registry.npmjs.org',
25 silly fetchPackageMetaData   host: 'registry.npmjs.org',
25 silly fetchPackageMetaData   port: 443 }
26 silly rollbackFailedOptional Starting
27 silly rollbackFailedOptional Finishing
28 silly runTopLevelLifecycles Starting
29 silly runTopLevelLifecycles Finishing
30 silly install printInstalled
31 verbose stack Error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
31 verbose stack     at errnoException (dns.js:26:10)
31 verbose stack     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)
32 verbose cwd /root
33 error Linux 4.1.15
34 error argv "/usr/bin/node" "/usr/bin/npm" "install" "iw"
35 error node v5.5.0
36 error npm  v3.3.12
37 error code ENOTFOUND
38 error errno ENOTFOUND
39 error syscall getaddrinfo
40 error network getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
40 error network This is most likely not a problem with npm itself
40 error network and is related to network connectivity.
40 error network In most cases you are behind a proxy or have bad network settings.
40 error network
40 error network If you are behind a proxy, please make sure that the
40 error network 'proxy' config is set properly.  See: 'npm help config'
41 verbose exit [ 1, true
```

```
# NODE_DEBUG=net npm install osc
- |-----------------------------------------------------------------------------------------------|
NET 224: pipe false undefined
NET 224: connect: find host registry.npmjs.org
NET 224: connect: dns options { family: undefined, hints: 40 }
NET 224: _read
- |-----------------------------------------------------------------------------------------------|
NET 224: destroy undefined
NET 224: destroy
NET 224: close
NET 224: close handle
NET 224: destroy
NET 224: already destroyed, fire error callbacks
/ |-----------------------------------------------------------------------------------------------|
NET 224: pipe false undefined
NET 224: connect: find host registry.npmjs.org
NET 224: connect: dns options { family: undefined, hints: 40 }
NET 224: _read
- |-----------------------------------------------------------------------------------------------|
NET 224: destroy undefined
NET 224: destroy
NET 224: close
NET 224: close handle
NET 224: destroy
NET 224: already destroyed, fire error callbacks
/ |-----------------------------------------------------------------------------------------------|
NET 224: pipe false undefined
NET 224: connect: find host registry.npmjs.org
NET 224: connect: dns options { family: undefined, hints: 40 }
NET 224: _read
npm ERR! Linux 4.1.15
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "osc"
npm ERR! node v5.5.0
npm ERR! npm  v3.3.12
npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR! syscall getaddrinfo

npm ERR! network getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
NET 224: destroy undefined
NET 224: destroy
NET 224: close
NET 224: close handle
NET 224: destroy
NET 224: already destroyed, fire error callbacks
NET 224: emit close

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log
```

**Comment by KenanY** [comment]
@T94T Is this still an issue for you?

**Comment by T94T** [comment]
Has been settled.
