### ISSUE TITLE
Cannot publish an update for a package of mine

### ISSUE THREAD

**Issue by bugant** [npm/npm#11523]
```
npm publish
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/Cellar/node/5.2.0/bin/node" "/usr/local/bin/npm" "publish"
npm ERR! node v5.2.0
npm ERR! npm  v3.5.2

npm ERR! toString failed
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/matteo/hackitaly/ember-cli-facebook-js-sdk/npm-debug.log
```

Here is the full log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/5.2.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'publish' ]
2 info using npm@3.5.2
3 info using node@v5.2.0
4 verbose publish [ '.' ]
5 silly cache add args [ '.', null ]
6 verbose cache add spec .
7 silly cache add parsed spec Result {
7 silly cache add   raw: '.',
7 silly cache add   scope: null,
7 silly cache add   name: null,
7 silly cache add   rawSpec: '.',
7 silly cache add   spec: '/Users/matteo/hackitaly/ember-cli-facebook-js-sdk',
7 silly cache add   type: 'directory' }
8 verbose addLocalDirectory /Users/matteo/.npm/ember-cli-facebook-js-sdk/1.0.0/package.tgz not in flight; packing
9 info lifecycle ember-cli-facebook-js-sdk@1.0.0~prepublish: ember-cli-facebook-js-sdk@1.0.0
10 silly lifecycle ember-cli-facebook-js-sdk@1.0.0~prepublish: no script for prepublish, continuing
11 verbose tar pack [ '/Users/matteo/.npm/ember-cli-facebook-js-sdk/1.0.0/package.tgz',
11 verbose tar pack   '/Users/matteo/hackitaly/ember-cli-facebook-js-sdk' ]
12 verbose tarball /Users/matteo/.npm/ember-cli-facebook-js-sdk/1.0.0/package.tgz
13 verbose folder /Users/matteo/hackitaly/ember-cli-facebook-js-sdk
14 verbose addLocalTarball adding from inside cache /Users/matteo/.npm/ember-cli-facebook-js-sdk/1.0.0/package.tgz
15 silly cache afterAdd ember-cli-facebook-js-sdk@1.0.0
16 verbose afterAdd /Users/matteo/.npm/ember-cli-facebook-js-sdk/1.0.0/package/package.json not in flight; writing
17 verbose afterAdd /Users/matteo/.npm/ember-cli-facebook-js-sdk/1.0.0/package/package.json written
18 silly publish { name: 'ember-cli-facebook-js-sdk',
18 silly publish   version: '1.0.0',
18 silly publish   description: 'A simple wrapper for the Facebook JS SDK',
18 silly publish   directories: { doc: 'doc', test: 'tests' },
18 silly publish   scripts:
18 silly publish    { build: 'ember build',                                                                                                                                 [41/1810]
18 silly publish      start: 'ember server',
18 silly publish      test: 'ember try:testall' },
18 silly publish   repository:
18 silly publish    { type: 'git',
18 silly publish      url: 'git+https://github.com/pitchtarget/ember-cli-facebook-js-sdk.git' },
18 silly publish   engines: { node: '>= 0.10.0' },
18 silly publish   author: { name: 'bugant@gmail.com' },
18 silly publish   license: 'MIT',
18 silly publish   devDependencies:
18 silly publish    { 'broccoli-asset-rev': '^2.2.0',
18 silly publish      'ember-cli': '1.13.13',
18 silly publish      'ember-cli-app-version': '^1.0.0',
18 silly publish      'ember-cli-content-security-policy': '0.4.0',
18 silly publish      'ember-cli-dependency-checker': '^1.1.0',
18 silly publish      'ember-cli-htmlbars': '^1.0.1',
18 silly publish      'ember-cli-htmlbars-inline-precompile': '^0.3.1',
18 silly publish      'ember-cli-ic-ajax': '0.2.4',
18 silly publish      'ember-cli-inject-live-reload': '^1.3.1',
18 silly publish      'ember-cli-qunit': '^1.0.4',
18 silly publish      'ember-cli-release': '0.2.8',
18 silly publish      'ember-cli-sri': '^1.2.0',
18 silly publish      'ember-cli-uglify': '^1.2.0',
18 silly publish      'ember-data': '1.13.15',
18 silly publish      'ember-disable-prototype-extensions': '^1.0.0',
18 silly publish      'ember-disable-proxy-controllers': '^1.0.1',
18 silly publish      'ember-export-application-global': '^1.0.4',
18 silly publish      'ember-getowner-polyfill': '1.0.0',
18 silly publish      'ember-try': '~0.0.8' },
18 silly publish   keywords: [ 'ember-addon', 'facebook', 'fb' ],
18 silly publish   dependencies: { 'ember-cli-babel': '^5.1.5' },
18 silly publish   'ember-addon': { configPath: 'tests/dummy/config' },
18 silly publish   readme: '# Ember-cli-facebook-js-sdk\n\nSimple Facebook SDK for Javascript addon for your Ember CLI app.\n\nThis addon lets you interact with the Facebook API usi
ng Promises\nas you would usually do with any async operation in your Ember app.\nThe same API is used in the addon so that you can easily refer to the\n[Facebook SDK for Javascript
 reference doc](https://developers.facebook.com/docs/javascript/reference) for\ndetails on the usage.\n\nThe methods implemented are:\n\n* Core Methods\n  - init\n  - api\n  - ui\n*
 Facebook Login Methods\n  - getLoginStatus\n  - login\n  - logout\n  - getAuthResponse\n\n## Installation\n\n* ember install ember-cli-facebook-js-sdk\n\n### Upgrade from 0.0.4\n\n
From version 1.0.0 ember-cli-facebook-js-sdk implements a service, before it was a simple ES6 module you should import.\nIf you prefer to stick to the old version, checkout the 0.0.
4 tag.\n\n## Usage and configuration\n\nBefore using the [Facebook SDK for Javascript](https://developers.facebook.com/docs/javascript) you need\nto include it in your HTML. The mor
e convenient way to do it is by using the addon service\'s FBInit method.\nTo do so, you must configure the parameters to use to initialize the Facebook SDK in your `config/environm
ent.js` file in the `FB` key.\nThe following is a basic example of such a configuration:\n\n```js\n  FB = {\n    appId: \'YOUR APP ID\',\n    version: \'v2.3\',\n    xfbml: true\n  
}\n```\n\nNote, if you use other addons or if you prefer to initialize the Facebook SDK for Javascript by your own, you must configure the addon to skip the initialization process:\
n\n```js\n  FB = {\n    skipInit: true\n  }\n```\n\nWhenever you need to interact with Facebook SDK, you must inject the service in your code and use it as you would do with the\nor
iginal SDK. Remember that async functions that would normally require a callback, here return a Promise.\n\nIf you find yourself, needing the service in all your controllers you cou
ld think of injecting the service by default in your controller like the following:\n\n```js\nexport function initialize(application) {\n  application.inject(\'controller\', \'fb\',
 \'service:fb\');\n}\n\nexport default {\n  name: \'fb\',\n  initialize\n};\n```\n\n## Exmaple app\n\nYou can find an example app which make use of the addon in the [I have been to 
repo](https://github.com/bugant/i-have-been-to).\n\n## Running Tests\n\nTODO: I need to find a way to run test with a valid (never expiring) access token for a test user.\nBefore ru
nning tests, substitute any occurence of YOUR-APP-ID and YOUR-FB-TOKEN in `tests/unit/services/fb-test.js` with respectively your Facebook App ID and access token.\n\n* `ember test`
\n* `ember test --server`\n\n## Building\n\n* `ember build`\n\nFor more information on using ember-cli, visit [http://www.ember-cli.com/](http://www.ember-cli.com/).\n',
18 silly publish   readmeFilename: 'README.md',
18 silly publish   gitHead: '24b815dfa346eb7667561f87815cee71a57aada3',
18 silly publish   bugs: { url: 'https://github.com/pitchtarget/ember-cli-facebook-js-sdk/issues' },
18 silly publish   homepage: 'https://github.com/pitchtarget/ember-cli-facebook-js-sdk#readme',
18 silly publish   _id: 'ember-cli-facebook-js-sdk@1.0.0',
18 silly publish   _shasum: '7fdc23d2e25936c9342439212ad5626401e520e9',
18 silly publish   _from: '.' }
19 verbose getPublishConfig undefined
20 silly mapToRegistry name ember-cli-facebook-js-sdk
21 silly mapToRegistry using default registry
22 silly mapToRegistry registry https://registry.npmjs.org/
23 silly mapToRegistry uri https://registry.npmjs.org/ember-cli-facebook-js-sdk
24 verbose publish registryBase https://registry.npmjs.org/
25 silly publish uploading /Users/matteo/.npm/ember-cli-facebook-js-sdk/1.0.0/package.tgz
26 verbose stack Error: toString failed
26 verbose stack     at Buffer.toString (buffer.js:401:11)
26 verbose stack     at CachingRegistryClient.putFirst (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/publish.js:97:23)
26 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/publish.js:54:14
26 verbose stack     at ConcatStream.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/node_modules/concat-stream/index.js:36:43)
26 verbose stack     at emitNone (events.js:73:20)
26 verbose stack     at ConcatStream.emit (events.js:167:7)
26 verbose stack     at finishMaybe (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js
:509:14)
26 verbose stack     at endWritable (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js
:519:3)
26 verbose stack     at ConcatStream.Writable.end (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/node_modules/concat-stream/node_modules/readable-stream/lib/_stre
am_writable.js:484:5)
26 verbose stack     at ReadStream.onend (_stream_readable.js:491:10)
27 verbose cwd /Users/matteo/hackitaly/ember-cli-facebook-js-sdk
28 error Darwin 14.5.0
29 error argv "/usr/local/Cellar/node/5.2.0/bin/node" "/usr/local/bin/npm" "publish"
30 error node v5.2.0
31 error npm  v3.5.2
32 error toString failed
33 error If you need help, you may report this error at:
33 error     <https://github.com/npm/npm/issues>
34 verbose exit [ 1, true ]
```

**Comment by bugant** [comment]
Note that if I try to publish the package from a Linux machine, everything is OK.

**Comment by othiym23** [comment]
Hello! This is a kind of weird thing that you've found. Some searching indicates that "`toString failed`" is the error message that results when the string you're trying to serialize is too big for Node's Buffer code to serialize (i.e. it's over 256MiB). Is there a chance that there's something like a large MongoDB file hanging around in the package directory that's failing to publish?

**Comment by bugant** [comment]
I have a `tmp` dir with all kind of packages. I've added it to `.npmignore`, I'll give it a try as soon as possible. Thank you for the feedback.

**Comment by bugant** [comment]
Adding `tmp` directory to my `.npmignore` solved the issue. Thank you @othiym23

**Comment by davidcalhoun** [comment]
Just ran into this cryptic error.  Maybe would be handier to have a check/warning for some max package size?
