### ISSUE TITLE
problem with fetching git repo (gist/github) on windows10

### ISSUE THREAD

**Issue by cauburtin** [npm/npm#11536]
I tried `npm i git+ssh@gist.github.com:51e4ec99dc8ef5951707.git`

or tried with a package.json:

```
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "1",
  "license": "ISC",
  "dependencies": {
    "requirify": "git+ssh@gist.github.com:51e4ec99dc8ef5951707.git"
  }
}
```

both end up with this error:

```
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:213:12)
npm WARN addRemoteGit     at emitTwo (events.js:87:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:172:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:818:16)
npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:319:11)
npm WARN addRemoteGit     at emitOne (events.js:77:13)
npm WARN addRemoteGit     at Socket.emit (events.js:169:7)
npm WARN addRemoteGit     at Pipe._onclose (net.js:469:12)
npm WARN addRemoteGit  git+ssh://git@gist.github.com/51e4ec99dc8ef5951707.git resetting remote C:\Users\admin\AppData\Roaming\npm-cache\_git-remotes\git-ssh-git-gist-github-com-51e4ec99dc8ef5951707-git-61d66a6b because of error: { [Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit ]
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
npm ERR! git clone --template=C:\Users\admin\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror ssh://git@gist.github.com/51e4ec99dc8ef5951707.git C:\Users\admin\AppData\Roaming\npm-cache\_git-remotes\git-ssh-git-gist-github-com-51e4ec99dc8ef5951707-git-61d66a6b: Cloning into bare repository 'C:\Users\admin\AppData\Roaming\npm-cache\_git-remotes\git-ssh-git-gist-github-com-51e4ec99dc8ef5951707-git-61d66a6b'...
npm ERR! git clone --template=C:\Users\admin\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror ssh://git@gist.github.com/51e4ec99dc8ef5951707.git C:\Users\admin\AppData\Roaming\npm-cache\_git-remotes\git-ssh-git-gist-github-com-51e4ec99dc8ef5951707-git-61d66a6b: Host key verification failed.
npm ERR! git clone --template=C:\Users\admin\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror ssh://git@gist.github.com/51e4ec99dc8ef5951707.git C:\Users\admin\AppData\Roaming\npm-cache\_git-remotes\git-ssh-git-gist-github-com-51e4ec99dc8ef5951707-git-61d66a6b: fatal: Could not read from remote repository.
npm ERR! git clone --template=C:\Users\admin\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror ssh://git@gist.github.com/51e4ec99dc8ef5951707.git C:\Users\admin\AppData\Roaming\npm-cache\_git-remotes\git-ssh-git-gist-github-com-51e4ec99dc8ef5951707-git-61d66a6b:
npm ERR! git clone --template=C:\Users\admin\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror ssh://git@gist.github.com/51e4ec99dc8ef5951707.git C:\Users\admin\AppData\Roaming\npm-cache\_git-remotes\git-ssh-git-gist-github-com-51e4ec99dc8ef5951707-git-61d66a6b: Please make sure you have the correct access rights
npm ERR! git clone --template=C:\Users\admin\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror ssh://git@gist.github.com/51e4ec99dc8ef5951707.git C:\Users\admin\AppData\Roaming\npm-cache\_git-remotes\git-ssh-git-gist-github-com-51e4ec99dc8ef5951707-git-61d66a6b: and the repository exists.
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\admin\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "i" "git+ssh@gist.github.com:51e4ec99dc8ef5951707.git"
npm ERR! node v5.3.0
npm ERR! npm  v3.7.1
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\admin\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror ssh://git@gist.github.com/51e4ec99dc8ef5951707.git C:\Users\admin\AppData\Roaming\npm-cache\_git-remotes\git-ssh-git-gist-github-com-51e4ec99dc8ef5951707-git-61d66a6b
npm ERR! Cloning into bare repository 'C:\Users\admin\AppData\Roaming\npm-cache\_git-remotes\git-ssh-git-gist-github-com-51e4ec99dc8ef5951707-git-61d66a6b'...
npm ERR! Host key verification failed.
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\admin\Downloads\test\npm-debug.log

```

**Comment by dirceu** [comment]
Please try again with the following command:

```shell
npm install gist:51e4ec99dc8ef5951707
```

Also, please check if the gist hash is correct - I get a 404 error when I try to access https://gist.github.com/51e4ec99dc8ef5951707 on my browser.

**Comment by cauburtin** [comment]
yes, sorry I added 1 to the gist id (stupidly), so I did `npm install gist:...` on 2 gists, but why don't show up in my package.json?, they are logged by npm as 'extraneous'

**Comment by dirceu** [comment]
@cauburtin you have to use the `--save` (or `--save-dev`) to install and add it automatically to your `package.json`. I just tried here and it worked:

```shell
$ npm install --save gist:571b316413c6d59370c2
teste-dirceu@1.0.0 /Users/dirceu/Desktop
└── requirify@0.0.1  (git://gist.github.com/571b316413c6d59370c2.git#afc9fb18b97fc7cb7117555ac74f4fbfd177b558)

npm WARN teste-dirceu@1.0.0 No description
npm WARN teste-dirceu@1.0.0 No repository field.

$ cat package.json 
{
  "name": "teste-dirceu",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "requirify": "gist:571b316413c6d59370c2"
  }
}
```

**Comment by cauburtin** [comment]
ah.. yes I'm really stupid currently, ok
