### ISSUE TITLE
npm does not install in ubuntu

### ISSUE THREAD

**Issue by Tanjeeb** [npm/npm#11537]
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'install', '-g' ]
2 info using npm@3.7.2
3 info using node@v4.3.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData .
8 silly fetchDirectoryPackageData .
9 silly install normalizeTree
10 silly loadCurrentTree Finishing
11 silly loadIdealTree Starting
12 silly install loadIdealTree
13 silly cloneCurrentTree Starting
14 silly install cloneCurrentTreeToIdealTree
15 silly cloneCurrentTree Finishing
16 silly loadShrinkwrap Starting
17 silly install loadShrinkwrap
18 silly loadShrinkwrap Finishing
19 silly loadAllDepsIntoIdealTree Starting
20 silly install loadAllDepsIntoIdealTree
21 silly resolveWithNewModule !invalid#1 checking installable status
22 silly cache add args [ '.', null ]
23 verbose cache add spec .
24 silly cache add parsed spec Result {
24 silly cache add   raw: '.',
24 silly cache add   scope: null,
24 silly cache add   name: null,
24 silly cache add   rawSpec: '.',
24 silly cache add   spec: '/home/tanjeeb/laravelproject/authtest',
24 silly cache add   type: 'directory' }
25 error addLocal Could not install /home/tanjeeb/laravelproject/authtest
26 silly rollbackFailedOptional Starting
27 silly rollbackFailedOptional Finishing
28 silly runTopLevelLifecycles Starting
29 silly runTopLevelLifecycles Finishing
30 silly install printInstalled
31 verbose stack Error: No name provided in package.json
31 verbose stack     at /usr/lib/node_modules/npm/lib/cache/add-local.js:65:17
31 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:345:5
31 verbose stack     at checkBinReferences_ (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:309:45)
31 verbose stack     at final (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:343:3)
31 verbose stack     at then (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:113:5)
31 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:232:12
31 verbose stack     at /usr/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
31 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
32 verbose cwd /home/tanjeeb/laravelproject/authtest
33 error Linux 3.19.0-49-generic
34 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g"
35 error node v4.3.0
36 error npm  v3.7.2
37 error No name provided in package.json
38 error If you need help, you may report this error at:
38 error     <https://github.com/npm/npm/issues>
39 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
Hello @Tanjeeb! From the log, I _think_ what is happening is that you are running `npm install -g` in a directory whose `package.json` does not contain a `"name"` field. By running `npm install -g` without any package names as arguments, `npm` is trying to install the package that is in your current directory. However, this package does not have a `"name"`, which is an absolutely necessary field to have.

**Comment by othiym23** [comment]
```
31 verbose stack Error: No name provided in package.json
```

Indeed. `name` and `version` are the two required parameters in a `package.json`, and without them, npm's not going to be able to do anything with that `package.json`.

Also, it's fairly rare that you're ever going to want to run `npm install -g` by itself – even in this case, what will end up happening is that the package in the current directory will get installed globally, instead of its dependencies being globally installed. If you want to install packages globally, they must be included on the `npm install` command-line, rather than in `package.json`.

Closing as resolved. Thanks for your time, and good luck getting everything sorted out!

**Comment by Tanjeeb** [comment]
I update my node version,now problem is solved.Thank you all
