### ISSUE TITLE
Error while installing phoegap

### ISSUE THREAD

**Issue by maheshchalke2006** [npm/npm#11560]
```
78559 warn ENOENT ENOENT: no such file or directory, open 'D:\projects\demo\phonegap\phonegap-projects\package.json'
78560 warn EPACKAGEJSON phonegap-projects No description
78561 warn EPACKAGEJSON phonegap-projects No repository field.
78562 warn EPACKAGEJSON phonegap-projects No README data
78563 warn EPACKAGEJSON phonegap-projects No license field.
78564 verbose stack Error: Callback called more than once.
78564 verbose stack     at errorHandler (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:110:16)
78564 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install.js:292:7
78564 verbose stack     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:7:26)
78564 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:18:7
78564 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install.js:676:7
78564 verbose stack     at Function.ls.fromTree (C:\Program Files\nodejs\node_modules\npm\lib\ls.js:101:3)
78564 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install.js:674:8
78564 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\iferr\index.js:13:50
78564 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:123:5
78564 verbose stack     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:7:26)
78565 verbose cwd D:\projects\demo\phonegap\phonegap-projects
78566 error Windows_NT 6.3.9600
78567 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "phonegap"
78568 error node v5.5.0
78569 error npm  v3.3.12
78570 error Callback called more than once.
78571 error If you need help, you may report this error at:
78571 error     <https://github.com/npm/npm/issues>
78572 verbose exit [ 1, true ]
```

**Comment by othiym23** [comment]
Hi! There are two errors worth noting in the excerpt you've included here:

```
78559 warn ENOENT ENOENT: no such file or directory, open 'D:\projects\demo\phonegap\phonegap-projects\package.json'
```

This says to me that something else went wrong, because the command `npm install phonegap` shouldn't care whether there's a `package.json` in the current directory. Did you hold onto the `npm-debug.log` that you cut this excerpt from? Can you upload the whole thing?

```
78564 verbose stack Error: Callback called more than once.
```

This is always an internal error for npm, and generally means there was some kind of unexpected network condition that confused the installer enough that it hit an edge case the developers haven't covered yet.

Does this happen consistently? Either way, it would be great to get `npm-debug.log` to examine, but it's possible that this is a transient network quality issue – installing Phonegap and Cordova is unusually hard on your local network connection because it's a large and complex install.

**Comment by busches** [comment]
@KenanY no reply in over eight months
