### ISSUE TITLE
npm install bootstrap fall

### ISSUE THREAD

**Issue by anraku** [npm/npm#11580]
first, I run these commands.
```
git clone https://github.com/twbs/bootstrap.git
cd bootstrap
```
These commands work normally, but `npm install bootstrap` doesn't work there after.
This is npm log

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\anraku\\Documents\\nodist\\bin\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'bootstrap@3' ]
2 info using npm@3.5.3
3 info using node@v4.2.4
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData bootstrap@3
8 silly fetchNamedPackageData bootstrap
9 silly mapToRegistry name bootstrap
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry uri https://registry.npmjs.org/bootstrap
13 verbose request uri https://registry.npmjs.org/bootstrap
14 verbose request no auth needed
15 info attempt registry request try #1 at 23:39:41
16 verbose request id 5046bd7f78b31861
17 verbose etag "63DJRQBD2E4NWYAZYLIALX5EY"
18 http request GET https://registry.npmjs.org/bootstrap
19 http 304 https://registry.npmjs.org/bootstrap
20 verbose headers { date: 'Wed, 17 Feb 2016 14:39:33 GMT',
20 verbose headers   via: '1.1 varnish',
20 verbose headers   'cache-control': 'max-age=300',
20 verbose headers   etag: '"63DJRQBD2E4NWYAZYLIALX5EY"',
20 verbose headers   age: '0',
20 verbose headers   connection: 'keep-alive',
20 verbose headers   'x-served-by': 'cache-nrt6128-NRT',
20 verbose headers   'x-cache': 'HIT',
20 verbose headers   'x-cache-hits': '1',
20 verbose headers   'x-timer': 'S1455719973.797883,VS0,VE713',
20 verbose headers   vary: 'Accept' }
21 silly get cb [ 304,
21 silly get   { date: 'Wed, 17 Feb 2016 14:39:33 GMT',
21 silly get     via: '1.1 varnish',
21 silly get     'cache-control': 'max-age=300',
21 silly get     etag: '"63DJRQBD2E4NWYAZYLIALX5EY"',
21 silly get     age: '0',
21 silly get     connection: 'keep-alive',
21 silly get     'x-served-by': 'cache-nrt6128-NRT',
21 silly get     'x-cache': 'HIT',
21 silly get     'x-cache-hits': '1',
21 silly get     'x-timer': 'S1455719973.797883,VS0,VE713',
21 silly get     vary: 'Accept' } ]
22 verbose etag https://registry.npmjs.org/bootstrap from cache
23 verbose get saving bootstrap to C:\Users\anraku\AppData\Roaming\npm-cache\registry.npmjs.org\bootstrap\.cache.json
24 silly install normalizeTree
25 silly loadCurrentTree Finishing
26 silly loadIdealTree Starting
27 silly install loadIdealTree
28 silly cloneCurrentTree Starting
29 silly install cloneCurrentTreeToIdealTree
30 silly cloneCurrentTree Finishing
31 silly loadShrinkwrap Starting
32 silly install loadShrinkwrap
33 silly loadShrinkwrap Finishing
34 silly loadAllDepsIntoIdealTree Starting
35 silly install loadAllDepsIntoIdealTree
36 silly rollbackFailedOptional Starting
37 silly rollbackFailedOptional Finishing
38 silly runTopLevelLifecycles Starting
39 silly runTopLevelLifecycles Finishing
40 silly install printInstalled
41 verbose stack Error: Refusing to install bootstrap as a dependency of itself
41 verbose stack     at checkSelf (C:\Users\anraku\Documents\nodist\bin\node_modules\npm\lib\install\validate-args.js:40:14)
41 verbose stack     at Array.<anonymous> (C:\Users\anraku\Documents\nodist\bin\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
41 verbose stack     at LOOP (C:\Users\anraku\Documents\nodist\bin\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
41 verbose stack     at chain (C:\Users\anraku\Documents\nodist\bin\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
41 verbose stack     at C:\Users\anraku\Documents\nodist\bin\node_modules\npm\lib\install\validate-args.js:15:5
41 verbose stack     at C:\Users\anraku\Documents\nodist\bin\node_modules\npm\node_modules\slide\lib\async-map.js:52:35
41 verbose stack     at Array.forEach (native)
41 verbose stack     at C:\Users\anraku\Documents\nodist\bin\node_modules\npm\node_modules\slide\lib\async-map.js:52:11
41 verbose stack     at Array.forEach (native)
41 verbose stack     at asyncMap (C:\Users\anraku\Documents\nodist\bin\node_modules\npm\node_modules\slide\lib\async-map.js:51:8)
42 verbose cwd C:\bootstrap
43 error Windows_NT 10.0.10240
44 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\anraku\\Documents\\nodist\\bin\\node_modules\\npm\\bin\\npm-cli.js" "install" "bootstrap@3"
45 error node v4.2.4
46 error npm  v3.5.3
47 error code ENOSELF
48 error Refusing to install bootstrap as a dependency of itself
49 error If you need help, you may report this error at:
49 error     <https://github.com/npm/npm/issues>
50 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
@anraku Just run `npm install` instead of `npm install bootstrap`.

**Comment by ashleygwilliams** [comment]
yup! @KenanY is right on point here. `npm install` will install a project's deps based on a `package.json`, which you downloaded when you cloned the git repository. https://github.com/twbs/bootstrap/blob/master/package.json

what you were doing, `npm install bootstrap@3` was actually trying to install bootstrap *again*, as a dependency of the bootstrap project which you had already install. npm doesn't let you install a package as a dependency of itself, and hence the error you got.

hope that helps! if you continue to have trouble, please file a new issue! thanks!

**Comment by anraku** [comment]
Oh.I seem to have made a simple mistake.
This problem was solved, Thanks!
