### ISSUE TITLE
npm ERR! Invalid name: "@alrra/travis-scripts"

### ISSUE THREAD

**Issue by heldrida** [npm/npm#11606]
Hi

I've installed modernizr through bower and now on the bower's modernizr directory, I need to run npm install, when I do I get the errors:

`npm ERR! Darwin 14.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2

npm ERR! Invalid name: "@alrra/travis-scripts"
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/helder/www/prototypes/freeangola/bower_components/modernizr/npm-debug.log`

Here's the log:

`0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'install' ]
2 info using npm@2.14.2
3 info using node@v4.0.0
4 verbose readDependencies loading dependencies from /Users/helder/www/prototypes/freeangola/bower_components/modernizr/package.json
5 verbose install where, deps [ '/Users/helder/www/prototypes/freeangola/bower_components/modernizr',
5 verbose install   [ 'doctrine',
5 verbose install     'file',
5 verbose install     'find-parent-dir',
5 verbose install     'lodash',
5 verbose install     'marked',
5 verbose install     'mkdirp',
5 verbose install     'requirejs',
5 verbose install     'yargs',
5 verbose install     '@alrra/travis-scripts',
5 verbose install     'expect.js',
5 verbose install     'grunt',
5 verbose install     'grunt-contrib-clean',
5 verbose install     'grunt-contrib-connect',
5 verbose install     'grunt-contrib-copy',
5 verbose install     'grunt-contrib-jade',
5 verbose install     'grunt-contrib-jshint',
5 verbose install     'grunt-coveralls',
5 verbose install     'grunt-env',
5 verbose install     'grunt-istanbul',
5 verbose install     'grunt-jscs',
5 verbose install     'grunt-mocha',
5 verbose install     'grunt-mocha-test',
5 verbose install     'grunt-saucelabs',
5 verbose install     'joi',
5 verbose install     'jquery',
5 verbose install     'json3',
5 verbose install     'load-grunt-tasks',
5 verbose install     'proxyquire',
5 verbose install     'serve-static' ] ]
6 verbose install where, peers [ '/Users/helder/www/prototypes/freeangola/bower_components/modernizr',
6 verbose install   [] ]
7 verbose installManyTop reading for lifecycle /Users/helder/www/prototypes/freeangola/bower_components/modernizr/package.json
8 info preinstall modernizr@3.3.1
9 verbose installManyTop reading scoped package data from /Users/helder/www/prototypes/freeangola/bower_components/modernizr/node_modules/doctrine/package.json
10 verbose installManyTop reading scoped package data from /Users/helder/www/prototypes/freeangola/bower_components/modernizr/node_modules/expect.js/package.json
11 verbose installManyTop reading scoped package data from /Users/helder/www/prototypes/freeangola/bower_components/modernizr/node_modules/file/package.json
12 verbose installManyTop reading scoped package data from /Users/helder/www/prototypes/freeangola/bower_components/modernizr/node_modules/find-parent-dir/package.json
13 verbose installManyTop reading scoped package data from /Users/helder/www/prototypes/freeangola/bower_components/modernizr/node_modules/grunt/package.json
14 verbose installManyTop reading scoped package data from /Users/helder/www/prototypes/freeangola/bower_components/modernizr/node_modules/grunt-contrib-clean/package.json
15 verbose installManyTop reading scoped package data from /Users/helder/www/prototypes/freeangola/bower_components/modernizr/node_modules/grunt-contrib-connect/package.json
16 verbose installManyTop reading scoped package data from /Users/helder/www/prototypes/freeangola/bower_components/modernizr/node_modules/grunt-contrib-copy/package.json
17 verbose installManyTop reading scoped package data from /Users/helder/www/prototypes/freeangola/bower_components/modernizr/node_modules/grunt-contrib-jade/package.json
18 verbose installManyTop reading scoped package data from /Users/helder/www/prototypes/freeangola/bower_components/modernizr/node_modules/grunt-contrib-jshint/package.json
19 verbose installManyTop reading scoped package data from /Users/helder/www/prototypes/freeangola/bower_components/modernizr/node_modules/grunt-coveralls/package.json
20 verbose installManyTop reading scoped package data from /Users/helder/www/prototypes/freeangola/bower_components/modernizr/node_modules/grunt-env/package.json
21 verbose installManyTop reading scoped package data from /Users/helder/www/prototypes/freeangola/bower_components/modernizr/node_modules/grunt-istanbul/package.json
22 verbose installManyTop reading scoped package data from /Users/helder/www/prototypes/freeangola/bower_components/modernizr/node_modules/grunt-jscs/package.json
23 verbose installManyTop reading scoped package data from /Users/helder/www/prototypes/freeangola/bower_components/modernizr/node_modules/grunt-mocha/package.json
24 verbose installManyTop reading scoped package data from /Users/helder/www/prototypes/freeangola/bower_components/modernizr/node_modules/grunt-mocha-test/package.json
25 verbose installManyTop reading scoped package data from /Users/helder/www/prototypes/freeangola/bower_components/modernizr/node_modules/grunt-saucelabs/package.json
26 verbose installManyTop reading scoped package data from /Users/helder/www/prototypes/freeangola/bower_components/modernizr/node_modules/joi/package.json
27 verbose installManyTop reading scoped package data from /Users/helder/www/prototypes/freeangola/bower_components/modernizr/node_modules/jquery/package.json
28 verbose installManyTop reading scoped package data from /Users/helder/www/prototypes/freeangola/bower_components/modernizr/node_modules/json3/package.json
29 verbose installManyTop reading scoped package data from /Users/helder/www/prototypes/freeangola/bower_components/modernizr/node_modules/load-grunt-tasks/package.json
30 verbose installManyTop reading scoped package data from /Users/helder/www/prototypes/freeangola/bower_components/modernizr/node_modules/lodash/package.json
31 verbose installManyTop reading scoped package data from /Users/helder/www/prototypes/freeangola/bower_components/modernizr/node_modules/marked/package.json
32 verbose installManyTop reading scoped package data from /Users/helder/www/prototypes/freeangola/bower_components/modernizr/node_modules/mkdirp/package.json
33 verbose installManyTop reading scoped package data from /Users/helder/www/prototypes/freeangola/bower_components/modernizr/node_modules/mocha/package.json
34 verbose installManyTop reading scoped package data from /Users/helder/www/prototypes/freeangola/bower_components/modernizr/node_modules/proxyquire/package.json
35 verbose installManyTop reading scoped package data from /Users/helder/www/prototypes/freeangola/bower_components/modernizr/node_modules/requirejs/package.json
36 verbose installManyTop reading scoped package data from /Users/helder/www/prototypes/freeangola/bower_components/modernizr/node_modules/serve-static/package.json
37 verbose installManyTop reading scoped package data from /Users/helder/www/prototypes/freeangola/bower_components/modernizr/node_modules/yargs/package.json
38 verbose readDependencies loading dependencies from /Users/helder/www/prototypes/freeangola/bower_components/modernizr/package.json
39 verbose targetResolver reading package data from /Users/helder/www/prototypes/freeangola/bower_components/modernizr/node_modules/doctrine/package.json
40 verbose targetResolver reading package data from /Users/helder/www/prototypes/freeangola/bower_components/modernizr/node_modules/expect.js/package.json
41 verbose targetResolver reading package data from /Users/helder/www/prototypes/freeangola/bower_components/modernizr/node_modules/file/package.json
42 verbose targetResolver reading package data from /Users/helder/www/prototypes/freeangola/bower_components/modernizr/node_modules/find-parent-dir/package.json
43 verbose targetResolver reading package data from /Users/helder/www/prototypes/freeangola/bower_components/modernizr/node_modules/grunt/package.json
44 verbose targetResolver reading package data from /Users/helder/www/prototypes/freeangola/bower_components/modernizr/node_modules/grunt-contrib-clean/package.json
45 verbose targetResolver reading package data from /Users/helder/www/prototypes/freeangola/bower_components/modernizr/node_modules/grunt-contrib-connect/package.json
46 verbose targetResolver reading package data from /Users/helder/www/prototypes/freeangola/bower_components/modernizr/node_modules/grunt-contrib-copy/package.json
47 verbose targetResolver reading package data from /Users/helder/www/prototypes/freeangola/bower_components/modernizr/node_modules/grunt-contrib-jade/package.json
48 verbose targetResolver reading package data from /Users/helder/www/prototypes/freeangola/bower_components/modernizr/node_modules/grunt-contrib-jshint/package.json
49 verbose targetResolver reading package data from /Users/helder/www/prototypes/freeangola/bower_components/modernizr/node_modules/grunt-coveralls/package.json
50 verbose targetResolver reading package data from /Users/helder/www/prototypes/freeangola/bower_components/modernizr/node_modules/grunt-env/package.json
51 verbose targetResolver reading package data from /Users/helder/www/prototypes/freeangola/bower_components/modernizr/node_modules/grunt-istanbul/package.json
52 verbose targetResolver reading package data from /Users/helder/www/prototypes/freeangola/bower_components/modernizr/node_modules/grunt-jscs/package.json
53 verbose targetResolver reading package data from /Users/helder/www/prototypes/freeangola/bower_components/modernizr/node_modules/grunt-mocha/package.json
54 verbose targetResolver reading package data from /Users/helder/www/prototypes/freeangola/bower_components/modernizr/node_modules/grunt-mocha-test/package.json
55 verbose targetResolver reading package data from /Users/helder/www/prototypes/freeangola/bower_components/modernizr/node_modules/grunt-saucelabs/package.json
56 verbose targetResolver reading package data from /Users/helder/www/prototypes/freeangola/bower_components/modernizr/node_modules/joi/package.json
57 verbose targetResolver reading package data from /Users/helder/www/prototypes/freeangola/bower_components/modernizr/node_modules/jquery/package.json
58 verbose targetResolver reading package data from /Users/helder/www/prototypes/freeangola/bower_components/modernizr/node_modules/json3/package.json
59 verbose targetResolver reading package data from /Users/helder/www/prototypes/freeangola/bower_components/modernizr/node_modules/load-grunt-tasks/package.json
60 verbose targetResolver reading package data from /Users/helder/www/prototypes/freeangola/bower_components/modernizr/node_modules/lodash/package.json
61 verbose targetResolver reading package data from /Users/helder/www/prototypes/freeangola/bower_components/modernizr/node_modules/marked/package.json
62 verbose targetResolver reading package data from /Users/helder/www/prototypes/freeangola/bower_components/modernizr/node_modules/mkdirp/package.json
63 verbose targetResolver reading package data from /Users/helder/www/prototypes/freeangola/bower_components/modernizr/node_modules/mocha/package.json
64 verbose targetResolver reading package data from /Users/helder/www/prototypes/freeangola/bower_components/modernizr/node_modules/proxyquire/package.json
65 verbose targetResolver reading package data from /Users/helder/www/prototypes/freeangola/bower_components/modernizr/node_modules/requirejs/package.json
66 verbose targetResolver reading package data from /Users/helder/www/prototypes/freeangola/bower_components/modernizr/node_modules/serve-static/package.json
67 verbose targetResolver reading package data from /Users/helder/www/prototypes/freeangola/bower_components/modernizr/node_modules/yargs/package.json
68 verbose targetResolver reading package data from /Users/helder/www/prototypes/freeangola/bower_components/modernizr/node_modules/.bin/grunt-istanbul/package.json
69 verbose targetResolver reading package data from /Users/helder/www/prototypes/freeangola/bower_components/modernizr/node_modules/.bin/marked/package.json
70 verbose targetResolver reading package data from /Users/helder/www/prototypes/freeangola/bower_components/modernizr/node_modules/.bin/mkdirp/package.json
71 verbose targetResolver reading package data from /Users/helder/www/prototypes/freeangola/bower_components/modernizr/node_modules/.bin/mocha/package.json
72 verbose targetResolver reading package data from /Users/helder/www/prototypes/freeangola/bower_components/modernizr/node_modules/.bin/r.js/package.json
73 verbose already installed skipping mkdirp@0.5.1 /Users/helder/www/prototypes/freeangola/bower_components/modernizr
74 verbose already installed skipping requirejs@2.1.22 /Users/helder/www/prototypes/freeangola/bower_components/modernizr
75 verbose already installed skipping yargs@3.31.0 /Users/helder/www/prototypes/freeangola/bower_components/modernizr
76 silly cache add args [ '@alrra/travis-scripts@1.1.1', null ]
77 verbose cache add spec @alrra/travis-scripts@1.1.1
78 silly cache add parsed spec Result {
78 silly cache add   raw: '@alrra/travis-scripts@1.1.1',
78 silly cache add   scope: '@alrra',
78 silly cache add   name: '@alrra/travis-scripts',
78 silly cache add   rawSpec: '1.1.1',
78 silly cache add   spec: '1.1.1',
78 silly cache add   type: 'version' }
79 silly addNamed @alrra/travis-scripts@1.1.1
80 verbose addNamed "1.1.1" is a plain semver version for @alrra/travis-scripts
81 silly mapToRegistry name @alrra/travis-scripts
82 silly mapToRegistry scope (from package name) @alrra
83 verbose mapToRegistry no registry URL found in name for scope @alrra
84 silly mapToRegistry using default registry
85 silly mapToRegistry registry http://registry.npmjs.org/
86 silly mapToRegistry uri http://registry.npmjs.org/@alrra%2ftravis-scripts
87 verbose addNameVersion registry:http://registry.npmjs.org/@alrra%2ftravis-scripts not in flight; fetching
88 verbose already installed skipping expect.js@0.3.1 /Users/helder/www/prototypes/freeangola/bower_components/modernizr
89 verbose already installed skipping grunt@0.4.5 /Users/helder/www/prototypes/freeangola/bower_components/modernizr
90 verbose already installed skipping grunt-contrib-clean@0.7.0 /Users/helder/www/prototypes/freeangola/bower_components/modernizr
91 verbose already installed skipping grunt-contrib-connect@0.11.2 /Users/helder/www/prototypes/freeangola/bower_components/modernizr
92 verbose already installed skipping grunt-contrib-copy@0.8.2 /Users/helder/www/prototypes/freeangola/bower_components/modernizr
93 verbose already installed skipping grunt-contrib-jade@0.15.0 /Users/helder/www/prototypes/freeangola/bower_components/modernizr
94 verbose already installed skipping grunt-contrib-jshint@0.11.3 /Users/helder/www/prototypes/freeangola/bower_components/modernizr
95 verbose already installed skipping grunt-coveralls@1.0.0 /Users/helder/www/prototypes/freeangola/bower_components/modernizr
96 verbose request uri http://registry.npmjs.org/@alrra%2ftravis-scripts
97 verbose request no auth needed
98 info attempt registry request try #1 at 12:50:53 PM
99 verbose request id 03612312e5600acb
100 verbose etag "7J6PNJTNHLYIXD84813ZPRNY"
101 http request GET http://registry.npmjs.org/@alrra%2ftravis-scripts
102 verbose already installed skipping grunt-env@0.4.4 /Users/helder/www/prototypes/freeangola/bower_components/modernizr
103 verbose already installed skipping grunt-istanbul@0.4.2 /Users/helder/www/prototypes/freeangola/bower_components/modernizr
104 verbose already installed skipping grunt-jscs@2.6.0 /Users/helder/www/prototypes/freeangola/bower_components/modernizr
105 verbose already installed skipping grunt-mocha@0.4.15 /Users/helder/www/prototypes/freeangola/bower_components/modernizr
106 verbose already installed skipping grunt-mocha-test@0.12.7 /Users/helder/www/prototypes/freeangola/bower_components/modernizr
107 verbose already installed skipping grunt-saucelabs@8.6.2 /Users/helder/www/prototypes/freeangola/bower_components/modernizr
108 verbose already installed skipping joi@6.10.0 /Users/helder/www/prototypes/freeangola/bower_components/modernizr
109 verbose already installed skipping jquery@1.12.0 /Users/helder/www/prototypes/freeangola/bower_components/modernizr
110 verbose already installed skipping json3@3.3.2 /Users/helder/www/prototypes/freeangola/bower_components/modernizr
111 verbose already installed skipping load-grunt-tasks@3.4.0 /Users/helder/www/prototypes/freeangola/bower_components/modernizr
112 verbose already installed skipping proxyquire@1.7.3 /Users/helder/www/prototypes/freeangola/bower_components/modernizr
113 verbose already installed skipping serve-static@^1.10.0 /Users/helder/www/prototypes/freeangola/bower_components/modernizr
114 verbose already installed skipping doctrine@1.1.0 /Users/helder/www/prototypes/freeangola/bower_components/modernizr
115 verbose already installed skipping file@0.2.2 /Users/helder/www/prototypes/freeangola/bower_components/modernizr
116 verbose already installed skipping find-parent-dir@0.3.0 /Users/helder/www/prototypes/freeangola/bower_components/modernizr
117 verbose already installed skipping lodash@4.0.0 /Users/helder/www/prototypes/freeangola/bower_components/modernizr
118 verbose already installed skipping marked@0.3.5 /Users/helder/www/prototypes/freeangola/bower_components/modernizr
119 http 304 http://registry.npmjs.org/@alrra%2ftravis-scripts
120 silly get cb [ 304,
120 silly get   { date: 'Fri, 19 Feb 2016 12:50:04 GMT',
120 silly get     via: '1.1 varnish',
120 silly get     'cache-control': 'max-age=0',
120 silly get     etag: '"7J6PNJTNHLYIXD84813ZPRNY"',
120 silly get     age: '0',
120 silly get     connection: 'keep-alive',
120 silly get     'x-served-by': 'cache-lcy1133-LCY',
120 silly get     'x-cache': 'MISS',
120 silly get     'x-cache-hits': '0',
120 silly get     'x-timer': 'S1455886204.483080,VS0,VE402',
120 silly get     vary: 'Accept' } ]
121 verbose etag http://registry.npmjs.org/@alrra%2ftravis-scripts from cache
122 verbose get saving @alrra/travis-scripts to /Users/helder/.npm/registry.npmjs.org/_40alrra_252ftravis-scripts/.cache.json
123 verbose stack Error: Invalid name: "@alrra/travis-scripts"
123 verbose stack     at ensureValidName (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/fixer.js:302:15)
123 verbose stack     at Object.module.exports.fixNameField (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/fixer.js:206:5)
123 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/normalize.js:29:38
123 verbose stack     at Array.forEach (native)
123 verbose stack     at normalize (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/normalize.js:28:15)
123 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:338:5)
123 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:113:5)
123 verbose stack     at ReadFileContext.callback (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:178:20)
123 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (evalmachine.<anonymous>:303:13)
124 verbose cwd /Users/helder/www/prototypes/freeangola/bower_components/modernizr
125 error Darwin 14.3.0
126 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
127 error node v4.0.0
128 error npm  v2.14.2
129 error Invalid name: "@alrra/travis-scripts"
130 error If you need help, you may report this error at:
130 error     <https://github.com/npm/npm/issues>
131 verbose exit [ 1, true ]
`

**Comment by heldrida** [comment]
Updated npm and fixed the problem!
