### ISSUE TITLE
Cannot find module 'read-package-json'

### ISSUE THREAD

**Issue by mrmozza** [npm/npm#11618]
I'm new to gulp and I was having a problem getting it to watch my sass files. Everything else was working fine until I was reading a blog post and tried this command **sudo gem install sass**

Since running that, I get this error:

0 info it worked if it ends with ok
1 verbose cli [ '/Users/richard/.nvm/versions/node/v5.5.0/bin/node',
1 verbose cli   '/Users/richard/.nvm/versions/node/v5.5.0/bin/npm',
1 verbose cli   'install' ]
2 info using npm@3.7.4
3 info using node@v5.5.0
4 verbose stack Error: Cannot find module 'read-package-json'
4 verbose stack     at Function.Module._resolveFilename (module.js:339:15)
4 verbose stack     at Function.Module._load (module.js:290:25)
4 verbose stack     at Module.require (module.js:367:17)
4 verbose stack     at require (internal/module.js:16:19)
4 verbose stack     at Object.<anonymous> (/Users/richard/.nvm/versions/node/v5.5.0/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:2:11)
4 verbose stack     at Module._compile (module.js:413:34)
4 verbose stack     at Object.Module._extensions..js (module.js:422:10)
4 verbose stack     at Module.load (module.js:357:32)
4 verbose stack     at Function.Module._load (module.js:314:12)
4 verbose stack     at Module.require (module.js:367:17)
5 verbose cwd /Applications/MAMP/htdocs/interstoq
6 error Darwin 15.3.0
7 error argv "/Users/richard/.nvm/versions/node/v5.5.0/bin/node" "/Users/richard/.nvm/versions/node/v5.5.0/bin/npm" "install"
8 error node v5.5.0
9 error npm  v3.7.4
10 error code MODULE_NOT_FOUND
11 error Cannot find module 'read-package-json'
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]

Does anyone know how to fix this?

Thanks in advance.

**Comment by mrmozza** [comment]
Now working, reinstalled npm.
