### ISSUE TITLE
Can't install Socket.io - No compatible version found

### ISSUE THREAD

**Issue by NoahBragg** [npm/npm#11621]
I get an error when trying to run `npm install socket.io`
it says that there is a compatibility version problem.
my node and npm are both uptodate.

Here is my npm-debug.log
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'socket.io' ]
2 info using npm@3.7.3
3 info using node@v5.6.0
4 verbose config Skipping project config: /Volumes/Macintosh HD/noahbragg/.npmrc. (matches userconfig)
5 silly loadCurrentTree Starting
6 silly install loadCurrentTree
7 silly install readLocalPackageData
8 silly fetchPackageMetaData socket.io@undefined1.4.5
9 silly fetchNamedPackageData socket.io
10 silly mapToRegistry name socket.io
11 silly mapToRegistry using default registry
12 silly mapToRegistry registry https://registry.npmjs.org/
13 silly mapToRegistry uri https://registry.npmjs.org/socket.io
14 verbose request uri https://registry.npmjs.org/socket.io
15 verbose request no auth needed
16 info attempt registry request try #1 at 1:41:36 PM
17 verbose request id 7dd1f0f5adeb650a
18 verbose etag "BLXYUXFXO2XO10DNXK9RIOR23"
19 http request GET https://registry.npmjs.org/socket.io
20 http 304 https://registry.npmjs.org/socket.io
21 verbose headers { date: 'Sat, 20 Feb 2016 18:41:37 GMT',
21 verbose headers   via: '1.1 varnish',
21 verbose headers   'cache-control': 'max-age=300',
21 verbose headers   etag: '"BLXYUXFXO2XO10DNXK9RIOR23"',
21 verbose headers   age: '278',
21 verbose headers   connection: 'keep-alive',
21 verbose headers   'x-served-by': 'cache-iad2124-IAD',
21 verbose headers   'x-cache': 'HIT',
21 verbose headers   'x-cache-hits': '1',
21 verbose headers   'x-timer': 'S1455993697.024277,VS0,VE0',
21 verbose headers   vary: 'Accept' }
22 silly get cb [ 304,
22 silly get   { date: 'Sat, 20 Feb 2016 18:41:37 GMT',
22 silly get     via: '1.1 varnish',
22 silly get     'cache-control': 'max-age=300',
22 silly get     etag: '"BLXYUXFXO2XO10DNXK9RIOR23"',
22 silly get     age: '278',
22 silly get     connection: 'keep-alive',
22 silly get     'x-served-by': 'cache-iad2124-IAD',
22 silly get     'x-cache': 'HIT',
22 silly get     'x-cache-hits': '1',
22 silly get     'x-timer': 'S1455993697.024277,VS0,VE0',
22 silly get     vary: 'Accept' } ]
23 verbose etag https://registry.npmjs.org/socket.io from cache
24 verbose get saving socket.io to /Volumes/Macintosh HD/noahbragg/.npm/registry.npmjs.org/socket.io/.cache.json
25 verbose correctMkdir /Volumes/Macintosh HD/noahbragg/.npm correctMkdir not in flight; initializing
26 silly fetchPackageMetaData Error: No compatible version found: socket.io@undefined1.4.5
26 silly fetchPackageMetaData Valid install targets:
26 silly fetchPackageMetaData 1.4.5, 1.4.4, 1.4.3, 1.4.2, 1.4.1, 1.4.0, 1.3.7, 1.3.6, 1.3.5, 1.3.4, 1.3.3, 1.3.2, 1.3.1, 1.3.0, 1.2.1, 1.2.0, 1.1.0, 1.0.6, 1.0.5, 1.0.4, 1.0.3, 1.0.2, 1.0.1, 1.0.0, 1.0.0-pre5, 1.0.0-pre4, 1.0.0-pre3, 1.0.0-pre2, 1.0.0-pre, 0.9.17, 0.9.16, 0.9.15, 0.9.14, 0.9.13, 0.9.12, 0.9.11, 0.9.10, 0.9.9, 0.9.8, 0.9.7, 0.9.6, 0.9.5, 0.9.4, 0.9.3, 0.9.2, 0.9.1, 0.9.1-1, 0.9.0, 0.8.7, 0.8.6, 0.8.5, 0.8.4, 0.8.3, 0.8.2, 0.8.1, 0.8.0, 0.7.11, 0.7.10, 0.7.9, 0.7.8, 0.7.7, 0.7.6, 0.7.5, 0.7.4, 0.7.3, 0.7.2, 0.7.1, 0.7.0, 0.6.18, 0.6.17, 0.6.16, 0.6.15, 0.6.14, 0.6.12, 0.6.11, 0.6.10, 0.6.9, 0.6.8, 0.6.7, 0.6.6, 0.6.5, 0.6.4, 0.6.3, 0.6.1, 0.6.0, 0.5.3, 0.5.1, 0.4.1, 0.4.0, 0.3.8
26 silly fetchPackageMetaData
26 silly fetchPackageMetaData     at pickVersionFromRegistryDocument (/usr/local/lib/node_modules/npm/lib/fetch-package-metadata.js:156:16)
26 silly fetchPackageMetaData     at /usr/local/lib/node_modules/npm/node_modules/iferr/index.js:13:50
26 silly fetchPackageMetaData     at /usr/local/lib/node_modules/npm/lib/utils/pulse-till-done.js:19:8
26 silly fetchPackageMetaData     at saved (/usr/local/lib/node_modules/npm/lib/cache/caching-client.js:168:7)
26 silly fetchPackageMetaData     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:210:7
26 silly fetchPackageMetaData     at FSReqWrap.oncomplete (fs.js:82:15)
26 silly fetchPackageMetaData  error for socket.io@undefined1.4.5 [Error: No compatible version found: socket.io@undefined1.4.5
26 silly fetchPackageMetaData Valid install targets:
26 silly fetchPackageMetaData 1.4.5, 1.4.4, 1.4.3, 1.4.2, 1.4.1, 1.4.0, 1.3.7, 1.3.6, 1.3.5, 1.3.4, 1.3.3, 1.3.2, 1.3.1, 1.3.0, 1.2.1, 1.2.0, 1.1.0, 1.0.6, 1.0.5, 1.0.4, 1.0.3, 1.0.2, 1.0.1, 1.0.0, 1.0.0-pre5, 1.0.0-pre4, 1.0.0-pre3, 1.0.0-pre2, 1.0.0-pre, 0.9.17, 0.9.16, 0.9.15, 0.9.14, 0.9.13, 0.9.12, 0.9.11, 0.9.10, 0.9.9, 0.9.8, 0.9.7, 0.9.6, 0.9.5, 0.9.4, 0.9.3, 0.9.2, 0.9.1, 0.9.1-1, 0.9.0, 0.8.7, 0.8.6, 0.8.5, 0.8.4, 0.8.3, 0.8.2, 0.8.1, 0.8.0, 0.7.11, 0.7.10, 0.7.9, 0.7.8, 0.7.7, 0.7.6, 0.7.5, 0.7.4, 0.7.3, 0.7.2, 0.7.1, 0.7.0, 0.6.18, 0.6.17, 0.6.16, 0.6.15, 0.6.14, 0.6.12, 0.6.11, 0.6.10, 0.6.9, 0.6.8, 0.6.7, 0.6.6, 0.6.5, 0.6.4, 0.6.3, 0.6.1, 0.6.0, 0.5.3, 0.5.1, 0.4.1, 0.4.0, 0.3.8
26 silly fetchPackageMetaData ]
27 silly rollbackFailedOptional Starting
28 silly rollbackFailedOptional Finishing
29 silly runTopLevelLifecycles Starting
30 silly runTopLevelLifecycles Finishing
31 silly install printInstalled
32 verbose stack Error: No compatible version found: socket.io@undefined1.4.5
32 verbose stack Valid install targets:
32 verbose stack 1.4.5, 1.4.4, 1.4.3, 1.4.2, 1.4.1, 1.4.0, 1.3.7, 1.3.6, 1.3.5, 1.3.4, 1.3.3, 1.3.2, 1.3.1, 1.3.0, 1.2.1, 1.2.0, 1.1.0, 1.0.6, 1.0.5, 1.0.4, 1.0.3, 1.0.2, 1.0.1, 1.0.0, 1.0.0-pre5, 1.0.0-pre4, 1.0.0-pre3, 1.0.0-pre2, 1.0.0-pre, 0.9.17, 0.9.16, 0.9.15, 0.9.14, 0.9.13, 0.9.12, 0.9.11, 0.9.10, 0.9.9, 0.9.8, 0.9.7, 0.9.6, 0.9.5, 0.9.4, 0.9.3, 0.9.2, 0.9.1, 0.9.1-1, 0.9.0, 0.8.7, 0.8.6, 0.8.5, 0.8.4, 0.8.3, 0.8.2, 0.8.1, 0.8.0, 0.7.11, 0.7.10, 0.7.9, 0.7.8, 0.7.7, 0.7.6, 0.7.5, 0.7.4, 0.7.3, 0.7.2, 0.7.1, 0.7.0, 0.6.18, 0.6.17, 0.6.16, 0.6.15, 0.6.14, 0.6.12, 0.6.11, 0.6.10, 0.6.9, 0.6.8, 0.6.7, 0.6.6, 0.6.5, 0.6.4, 0.6.3, 0.6.1, 0.6.0, 0.5.3, 0.5.1, 0.4.1, 0.4.0, 0.3.8
32 verbose stack
32 verbose stack     at pickVersionFromRegistryDocument (/usr/local/lib/node_modules/npm/lib/fetch-package-metadata.js:156:16)
32 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/iferr/index.js:13:50
32 verbose stack     at /usr/local/lib/node_modules/npm/lib/utils/pulse-till-done.js:19:8
32 verbose stack     at saved (/usr/local/lib/node_modules/npm/lib/cache/caching-client.js:168:7)
32 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:210:7
32 verbose stack     at FSReqWrap.oncomplete (fs.js:82:15)
33 verbose cwd /Volumes/Macintosh HD/noahbragg
34 error Darwin 14.5.0
35 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "socket.io"
36 error node v5.6.0
37 error npm  v3.7.3
38 error No compatible version found: socket.io@undefined1.4.5
38 error Valid install targets:
38 error 1.4.5, 1.4.4, 1.4.3, 1.4.2, 1.4.1, 1.4.0, 1.3.7, 1.3.6, 1.3.5, 1.3.4, 1.3.3, 1.3.2, 1.3.1, 1.3.0, 1.2.1, 1.2.0, 1.1.0, 1.0.6, 1.0.5, 1.0.4, 1.0.3, 1.0.2, 1.0.1, 1.0.0, 1.0.0-pre5, 1.0.0-pre4, 1.0.0-pre3, 1.0.0-pre2, 1.0.0-pre, 0.9.17, 0.9.16, 0.9.15, 0.9.14, 0.9.13, 0.9.12, 0.9.11, 0.9.10, 0.9.9, 0.9.8, 0.9.7, 0.9.6, 0.9.5, 0.9.4, 0.9.3, 0.9.2, 0.9.1, 0.9.1-1, 0.9.0, 0.8.7, 0.8.6, 0.8.5, 0.8.4, 0.8.3, 0.8.2, 0.8.1, 0.8.0, 0.7.11, 0.7.10, 0.7.9, 0.7.8, 0.7.7, 0.7.6, 0.7.5, 0.7.4, 0.7.3, 0.7.2, 0.7.1, 0.7.0, 0.6.18, 0.6.17, 0.6.16, 0.6.15, 0.6.14, 0.6.12, 0.6.11, 0.6.10, 0.6.9, 0.6.8, 0.6.7, 0.6.6, 0.6.5, 0.6.4, 0.6.3, 0.6.1, 0.6.0, 0.5.3, 0.5.1, 0.4.1, 0.4.0, 0.3.8
39 error If you need help, you may report this error at:
39 error     <https://github.com/npm/npm/issues>
40 verbose exit [ 1, true ]
```

Thanks for the help. I am pretty new to npm and am not really sure what I am doing wrong.
Thanks!

**Comment by KenanY** [comment]
@NoahBragg Is this still an issue for you?

**Comment by KenanY** [comment]
Closing as abandoned.
