### ISSUE TITLE
Preparing a Node.js project on server-side

### ISSUE THREAD

**Issue by INsitu-app** [npm/npm#11623]
please see:

https://docs.flowhub.io/article/84-getting-started-node-js

I get to the part 

`$ node node_modules/.bin/noflo-nodejs-init --user <YOUR USER ID> --host localhost --port 3569 --label "Local NoFlo Test"`

which i enter into windows cmd, adding the correct user id offcourse. This is the output i get

C:\Users\Edward\Documents\dev\noflo-example\node_modules\.bin\noflo-nodejs-init:4
case `uname` in
^^^^

SyntaxError: Unexpected token case
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

any help please? I've being trying to fix the issue for ages. Ive tried following the [advice in this post](https://github.com/npm/npm/issues/3710)

**Comment by KenanY** [comment]
@INsitu-app Are you still seeing this issue?

**Comment by KenanY** [comment]
Closing as abandoned.
