### ISSUE TITLE
Failure to install with npm

### ISSUE THREAD

**Issue by viziionary** [npm/npm#11686]
```
[ec2-user@ip-172-31-22-79 Server]$ node -v
v0.6.8
[ec2-user@ip-172-31-22-79 Server]$ npm -v
1.1.0-2
[ec2-user@ip-172-31-22-79 Server]$ npm install prefixer
npm http GET https://registry.npmjs.org/prefixer

npm ERR! Error: failed to fetch from registry: prefixer
npm ERR!     at /usr/local/lib/node_modules/npm/lib/utils/npm-registry-client/get.js:139:12
npm ERR!     at cb (/usr/local/lib/node_modules/npm/lib/utils/npm-registry-client/request.js:32:9)
npm ERR!     at Request._callback (/usr/local/lib/node_modules/npm/lib/utils/npm-registry-client/request.js:137:18)
npm ERR!     at Request.callback (/usr/local/lib/node_modules/npm/node_modules/request/main.js:109:22)
npm ERR!     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/main.js:198:58)
npm ERR!     at Request.emit (events.js:88:20)
npm ERR!     at ClientRequest.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/main.js:356:14)
npm ERR!     at ClientRequest.emit (events.js:67:17)
npm ERR!     at HTTPParser.onIncoming (http.js:1238:11)
npm ERR!     at HTTPParser.onHeadersComplete (http.js:102:31)
npm ERR! You may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>
npm ERR!
npm ERR! System Linux 4.1.17-22.30.amzn1.x86_64
npm ERR! command "node" "/usr/local/bin/npm" "install" "prefixer"
npm ERR! cwd /home/ec2-user/Enviziion/Muveoo/Server
npm ERR! node -v v0.6.8
npm ERR! npm -v 1.1.0-2
npm ERR! message failed to fetch from registry: prefixer
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/ec2-user/Enviziion/Muveoo/Server/npm-debug.log
npm not ok
```

This seems like the problem isn't on my end. Or is it? What's up?

**Comment by KenanY** [comment]
@viziionary Node.js v6 and `npm@1.1` are extremely old (years!) and are no longer supported by anyone on the face of the planet. Please upgrade both [Node.js](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-node) and [`npm`](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) first.

**Comment by viziionary** [comment]
@KenanY Ohh, the tutorial I referenced (copy / pasted) must be that old. Woops. Well this can be closed.

**Comment by othiym23** [comment]
Closing as resolved.
