### ISSUE TITLE
help,npm install express error!

### ISSUE THREAD

**Issue by showerychn** [npm/npm#11693]
```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/ddx-b3/.nvm/versions/node/v4.2.5/bin/node',
1 verbose cli   '/Users/ddx-b3/.nvm/versions/node/v4.2.5/bin/npm',
1 verbose cli   '--verbose',
1 verbose cli   '--registry=https://registry.npm.taobao.org',
1 verbose cli   'install',
1 verbose cli   'express',
1 verbose cli   '--save' ]
2 info using npm@3.5.3
3 info using node@v4.2.5
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData express
8 silly fetchNamedPackageData express
9 silly mapToRegistry name express
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npm.taobao.org/
12 silly mapToRegistry uri https://registry.npm.taobao.org/express
13 verbose request uri https://registry.npm.taobao.org/express
14 verbose request no auth needed
15 info attempt registry request try #1 at 11:49:23 AM
16 verbose request id c4b8055c7d0c35f5
17 verbose etag "80bf8-w2AvIK+Ib06h44YYHTVyBA"
18 http request GET https://registry.npm.taobao.org/express
19 http 304 https://registry.npm.taobao.org/express
20 verbose headers { date: 'Fri, 26 Feb 2016 03:47:22 GMT',
20 verbose headers   connection: 'keep-alive',
20 verbose headers   etag: '"80bf8-w2AvIK+Ib06h44YYHTVyBA"',
20 verbose headers   'x-readtime': '439' }
21 silly get cb [ 304,
21 silly get   { date: 'Fri, 26 Feb 2016 03:47:22 GMT',
21 silly get     connection: 'keep-alive',
21 silly get     etag: '"80bf8-w2AvIK+Ib06h44YYHTVyBA"',
21 silly get     'x-readtime': '439' } ]
22 verbose etag https://registry.npm.taobao.org/express from cache
23 verbose get saving express to /Users/ddx-b3/.npm/registry.npm.taobao.org/express/.cache.json
24 silly install normalizeTree
25 silly loadCurrentTree Finishing
26 silly loadIdealTree Starting
27 silly install loadIdealTree
28 silly cloneCurrentTree Starting
29 silly install cloneCurrentTreeToIdealTree
30 silly cloneCurrentTree Finishing
31 silly loadShrinkwrap Starting
32 silly install loadShrinkwrap
33 silly loadShrinkwrap Finishing
34 silly loadAllDepsIntoIdealTree Starting
35 silly install loadAllDepsIntoIdealTree
36 silly rollbackFailedOptional Starting
37 silly rollbackFailedOptional Finishing
38 silly runTopLevelLifecycles Starting
39 silly runTopLevelLifecycles Finishing
40 silly install printInstalled
41 verbose stack Error: Refusing to install express as a dependency of itself
41 verbose stack     at checkSelf (/Users/ddx-b3/.nvm/versions/node/v4.2.5/lib/node_modules/npm/lib/install/validate-args.js:40:14)
41 verbose stack     at Array.<anonymous> (/Users/ddx-b3/.nvm/versions/node/v4.2.5/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
41 verbose stack     at LOOP (/Users/ddx-b3/.nvm/versions/node/v4.2.5/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
41 verbose stack     at chain (/Users/ddx-b3/.nvm/versions/node/v4.2.5/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
41 verbose stack     at /Users/ddx-b3/.nvm/versions/node/v4.2.5/lib/node_modules/npm/lib/install/validate-args.js:15:5
41 verbose stack     at /Users/ddx-b3/.nvm/versions/node/v4.2.5/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
41 verbose stack     at Array.forEach (native)
41 verbose stack     at /Users/ddx-b3/.nvm/versions/node/v4.2.5/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
41 verbose stack     at Array.forEach (native)
41 verbose stack     at asyncMap (/Users/ddx-b3/.nvm/versions/node/v4.2.5/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
42 verbose cwd /Users/ddx-b3/work/workspace/express
43 error Darwin 14.1.0
44 error argv "/Users/ddx-b3/.nvm/versions/node/v4.2.5/bin/node" "/Users/ddx-b3/.nvm/versions/node/v4.2.5/bin/npm" "--verbose" "--registry=https://registry.npm.taobao.org" "install" "express" "--save"
45 error node v4.2.5
46 error npm  v3.5.3
47 error code ENOSELF
48 error Refusing to install express as a dependency of itself
49 error If you need help, you may report this error at:
49 error     <https://github.com/npm/npm/issues>
50 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
@showerychn Could you try renaming your folder to something other than `express/`?

**Comment by KenanY** [comment]
@showerychn Have you gotten this issue resolved yet?

**Comment by othiym23** [comment]
Closing as abandoned. Open a new issue if you encounter this behavior again!
