### ISSUE TITLE
npm ERR! Darwin 15.3.0

### ISSUE THREAD

**Issue by semanser** [npm/npm#11698]
Cannot install this package:

`npm install wallpaper --save`

npm-debug.log: 
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'wallpaper',
1 verbose cli   '--save' ]
2 info using npm@3.7.5
3 info using node@v5.7.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData wallpaper
8 silly fetchNamedPackageData wallpaper
9 silly mapToRegistry name wallpaper
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry uri https://registry.npmjs.org/wallpaper
13 verbose request uri https://registry.npmjs.org/wallpaper
14 verbose request no auth needed
15 info attempt registry request try #1 at 18:27:20
16 verbose request using bearer token for auth
17 verbose request id eb52b8dd9d5af1be
18 verbose etag "4A2PO5TSS29X99Y1KJATP981I"
19 http request GET https://registry.npmjs.org/wallpaper
20 http 304 https://registry.npmjs.org/wallpaper
21 verbose headers { 'cache-control': 'max-age=300',
21 verbose headers   'accept-ranges': 'bytes',
21 verbose headers   date: 'Fri, 26 Feb 2016 16:27:21 GMT',
21 verbose headers   via: '1.1 varnish',
21 verbose headers   connection: 'keep-alive',
21 verbose headers   'x-served-by': 'cache-fra1244-FRA',
21 verbose headers   'x-cache': 'MISS',
21 verbose headers   'x-cache-hits': '0',
21 verbose headers   'x-timer': 'S1456504040.853402,VS0,VE187' }
22 silly get cb [ 304,
22 silly get   { 'cache-control': 'max-age=300',
22 silly get     'accept-ranges': 'bytes',
22 silly get     date: 'Fri, 26 Feb 2016 16:27:21 GMT',
22 silly get     via: '1.1 varnish',
22 silly get     connection: 'keep-alive',
22 silly get     'x-served-by': 'cache-fra1244-FRA',
22 silly get     'x-cache': 'MISS',
22 silly get     'x-cache-hits': '0',
22 silly get     'x-timer': 'S1456504040.853402,VS0,VE187' } ]
23 verbose etag https://registry.npmjs.org/wallpaper from cache
24 verbose get saving wallpaper to /Users/semanser/.npm/registry.npmjs.org/wallpaper/.cache.json
25 verbose correctMkdir /Users/semanser/.npm correctMkdir not in flight; initializing
26 silly install normalizeTree
27 silly loadCurrentTree Finishing
28 silly loadIdealTree Starting
29 silly install loadIdealTree
30 silly cloneCurrentTree Starting
31 silly install cloneCurrentTreeToIdealTree
32 silly cloneCurrentTree Finishing
33 silly loadShrinkwrap Starting
34 silly install loadShrinkwrap
35 silly loadShrinkwrap Finishing
36 silly loadAllDepsIntoIdealTree Starting
37 silly install loadAllDepsIntoIdealTree
38 silly rollbackFailedOptional Starting
39 silly rollbackFailedOptional Finishing
40 silly runTopLevelLifecycles Starting
41 silly runTopLevelLifecycles Finishing
42 silly install printInstalled
43 verbose stack Error: Refusing to install wallpaper as a dependency of itself
43 verbose stack     at checkSelf (/usr/local/lib/node_modules/npm/lib/install/validate-args.js:53:14)
43 verbose stack     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
43 verbose stack     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
43 verbose stack     at chain (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
43 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/validate-args.js:16:5
43 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
43 verbose stack     at Array.forEach (native)
43 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
43 verbose stack     at Array.forEach (native)
43 verbose stack     at asyncMap (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
44 verbose cwd /Users/semanser/Desktop/wallpaper-app
45 error Darwin 15.3.0
46 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "wallpaper" "--save"
47 error node v5.7.0
48 error npm  v3.7.5
49 error code ENOSELF
50 error Refusing to install wallpaper as a dependency of itself
51 error If you need help, you may report this error at:
51 error     <https://github.com/npm/npm/issues>
52 verbose exit [ 1, true ]

```

**Comment by semanser** [comment]
Solved:

`"name"` in `package.json` must be the same as folder name.
