### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by barthr** [npm/npm#11702]
I was trying to install ansi-to-html package with NPM when some errors occured. So I looked up the dependencies and tried installing them one by one.

I'm getting this error when installing the karg package

`2376 error tar.unpack untar error C:\Users\Bart\AppData\Roaming\npm-cache\karg\0.2.1\package.tgz
2377 warn install:karg@0.2.1 ENOENT: no such file or directory, open 'C:\Users\Bart\node_modules\.staging\karg-55affa6e95ec5dee8a277621dc8a228a\Icon
'
2378 verbose install:karg@0.2.1 Error: ENOENT: no such file or directory, open 'C:\Users\Bart\node_modules\.staging\karg-55affa6e95ec5dee8a277621dc8a228a\Icon
'
2378 verbose install:karg@0.2.1     at Error (native)
2379 silly gunzTarPerm extractEntry lib/js-yaml.js
2380 silly gunzTarPerm modified mode [ 'lib/js-yaml.js', 436, 438 ]
2381 silly gunzTarPerm extractEntry lib/js-yaml/common.js
2382 silly gunzTarPerm modified mode [ 'lib/js-yaml/common.js', 436, 438 ]
2383 silly gunzTarPerm extractEntry lib/argument_parser.js
2384 silly gunzTarPerm extractEntry lib/const.js
2385 error tar.unpack untar error C:\Users\Bart\AppData\Roaming\npm-cache\karg\1.0.3\package.tgz
2386 verbose stack RangeError: Maximum call stack size exceeded
2386 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install\actions.js:54:33
2386 verbose stack     at Array.forEach (native)
2386 verbose stack     at markAsFailed (C:\Program Files\nodejs\node_modules\npm\lib\install\actions.js:54:16)
2386 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install\actions.js:57:7
2386 verbose stack     at Array.forEach (native)
2386 verbose stack     at markAsFailed (C:\Program Files\nodejs\node_modules\npm\lib\install\actions.js:54:16)
2386 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install\actions.js:57:7
2386 verbose stack     at Array.forEach (native)
2386 verbose stack     at markAsFailed (C:\Program Files\nodejs\node_modules\npm\lib\install\actions.js:54:16)
2386 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install\actions.js:57:7
2387 verbose cwd C:\Users\Bart
2388 error Windows_NT 10.0.10586
2389 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--no-bin-link" "--no-color" "--no-progress" "ansi-to-html"
2390 error node v5.3.0
2391 error npm  v3.3.12
2392 error Maximum call stack size exceeded
2393 error If you need help, you may report this error at:
2393 error     <https://github.com/npm/npm/issues>
2394 verbose exit [ 1, true ]`

**Comment by iarna** [comment]
The root cause of your error:

> 2376 error tar.unpack untar error C:\Users\Bart\AppData\Roaming\npm-cache\karg\0.2.1\package.tgz
> 2377 warn install:karg@0.2.1 ENOENT: no such file or directory, open 'C:\Users\Bart\node_modules\.staging\karg-55affa6e95ec5dee8a277621dc8a228a\Icon
'
> 2378 verbose install:karg@0.2.1 Error: ENOENT: no such file or directory, open 'C:\Users\Bart\node_modules\.staging\karg-55affa6e95ec5dee8a277621dc8a228a\Icon
'
> 2378 verbose install:karg@0.2.1     at Error (native)

This is happening because the package includes a file that you can't create on windows:

```
🕒rebecca@Caldina:~/code/npmtest/11702$ tar tzvf karg-0.2.1.tgz
-rw-r--r--  0 501    20        458 Jan 24 15:09 package/package.json
-rw-r--r--  0 501    20         59 Jan 12 13:31 package/.npmignore
-rw-r--r--  0 501    20        795 Jan 11 13:08 package/README.md
-rw-r--r--  0 501    20       5456 Jan 24 14:15 package/js/karg.js
-rw-r--r--  0 501    20          0 Jan 12 10:15 package/Icon\r
-rw-r--r--  0 501    20        430 Jan 17 09:47 package/test/complex.js
-rw-r--r--  0 501    20        177 Jan 22 11:56 package/test/minimal.js
-rw-r--r--  0 501    20        188 Jan 22 11:57 package/test/minimal_help.js
-rw-r--r--  0 501    20        460 Jan 17 09:20 package/test/simple.js
-rw-r--r--  0 501    20        365 Jan 17 09:47 package/test/complex.coffee
-rw-r--r--  0 501    20        117 Jan 22 11:56 package/test/minimal.coffee
-rw-r--r--  0 501    20        127 Jan 22 11:57 package/test/minimal_help.coffee
-rw-r--r--  0 501    20        392 Jan 17 09:20 package/test/simple.coffee
```

> **`-rw-r--r--  0 501    20          0 Jan 12 10:15 package/Icon\r`**

Unfortunately, I checked and even the most recent version of karg as that in its distribution tarball. Right now your only option would be to depend on its github repo: [`karg`](https://github.com/monsterkodi/karg) has that file in its distribution. 

I've made a [PR to karg](https://github.com/monsterkodi/karg/pull/1) to update their `.npmignore` to exclude this file, and when they do a new release with that, you should be able to resume depending directly on that module.

**Comment by iarna** [comment]
I'm leaving this open as a big bug because I see two bugs that we should resolve:

1. First, we shouldn't be crashing do to errors extracting tarballs. I think fixing that will be as simple as:
```
diff --git a/lib/install/actions.js b/lib/install/actions.js
index 5d162f8..98b5e56 100644
--- a/lib/install/actions.js
+++ b/lib/install/actions.js
@@ -50,6 +50,7 @@ Object.keys(actions).forEach(function (actionName) {
 })

 function markAsFailed (pkg) {
+  if (pkg.failed) return
   pkg.failed = true
   pkg.requires.forEach(function (req) {
     req.requiredBy = req.requiredBy.filter(function (reqReqBy) { return reqReqBy !== pkg })
```
But it requires a test.

2. We need a better error message than ENOENT for this. We need to be clear why we couldn't install the package and who to speak to in order to resolve the issue.

**Comment by monsterkodi** [comment]
Hi barthr,
thanks for reporting this problem.
Thanks to iarna for finding a solution.
I will publish a new version immediately.

**Comment by barthr** [comment]
Very well, I will install the package manually. Thank you for the fast explanation.
