### ISSUE TITLE
npm install -g git+ssh://.... problem

### ISSUE THREAD

**Issue by chrisjshull** [npm/npm#11704]
This seems to be a variant of https://github.com/npm/npm/issues/9679 but with global installs.

Run `npm install -g git+ssh://....`.

Then run `npm -g outd`.

Fails with `Unsupported URL Type: ssh://...`

Does not repro with non-global installs.

Log (redacted):

```
40 verbose stack Error: Unsupported URL Type: ssh://...
40 verbose stack     at parseUrl (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:169:13)
40 verbose stack     at npa (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:75:12)
40 verbose stack     at shouldUpdate (/usr/local/lib/node_modules/npm/lib/outdated.js:335:16)
40 verbose stack     at /usr/local/lib/node_modules/npm/lib/outdated.js:302:23
40 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
40 verbose stack     at Array.forEach (native)
40 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
40 verbose stack     at Array.forEach (native)
40 verbose stack     at asyncMap (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
40 verbose stack     at outdated_ (/usr/local/lib/node_modules/npm/lib/outdated.js:295:3)
...
42 error Darwin 15.4.0
43 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "-g" "outd"
44 error node v5.6.0
45 error npm  v3.8.0 
```

**Comment by kappe** [comment]
**probably the same issue:**
0 info it worked if it ends with ok
1 verbose cli [ '/home/tiger/GPL/node-v4.3.1-linux-x86/bin/node',
1 verbose cli   '/home/tiger/GPL/node/bin/npm',
1 verbose cli   'install',
1 verbose cli   'pm2',
1 verbose cli   '-g' ]
2 info using npm@2.14.12
3 info using node@v4.3.1
4 verbose stack SyntaxError: Unexpected token ILLEGAL
4 verbose stack     at exports.runInThisContext (vm.js:53:16)
4 verbose stack     at Module._compile (module.js:373:25)
4 verbose stack     at Object.Module._extensions..js (module.js:416:10)
4 verbose stack     at Module.load (module.js:343:32)
4 verbose stack     at Function.Module._load (module.js:300:12)
4 verbose stack     at Module.require (module.js:353:17)
4 verbose stack     at require (internal/module.js:12:17)
4 verbose stack     at /home/tiger/GPL/node-v4.3.1-linux-x86/lib/node_modules/npm/node_modules/npm-registry-client/index.js:72:20
4 verbose stack     at Array.forEach (native)
4 verbose stack     at CachingRegistryClient.RegClient (/home/kappe/GPL/node-v4.3.1-linux-x86/lib/node_modules/npm/node_modules/npm-registry-client/index.js:50:42)
5 verbose cwd /home/tiger/GPL
6 error Linux 2.6.18-028stab101.1
7 error argv "/home/tiger/GPL/node-v4.3.1-linux-x86/bin/node" "/home/kappe/GPL/node/bin/npm" "install" "pm2" "-g"
8 error node v4.3.1
9 error npm  v2.14.12
10 error Unexpected token ILLEGAL
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

**Comment by andreis** [comment]
Similar problem here so I won't open a new issue. `git clone` on the same URL works.

```
 $ npm install --save git+ssh://git@git.redacted.io:andrei/redacted.git
npm ERR! addLocal Could not install /var/folders/nz/sxc1c3cj55d3dr131c2c2jf00000gn/T/npm-5983-19f5a9aa/git-cache-41fa280d/46fa3dc1862fd2d249cd4e8f858298a5ece5fd72
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/Cellar/node/5.9.1/bin/node" "/usr/local/bin/npm" "install" "--save" "git+ssh://git@git.redacted.io:andrei/redacted.git"
npm ERR! node v5.9.1
npm ERR! npm  v3.7.3
npm ERR! code EISDIR
npm ERR! errno -21
npm ERR! syscall read

npm ERR! eisdir EISDIR: illegal operation on a directory, read
npm ERR! eisdir This is most likely not a problem with npm itself
npm ERR! eisdir and is related to npm not being able to find a package.json in
npm ERR! eisdir a package you are trying to install.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/andrei/redacted/npm-debug.log
```

`npm-debug.log`:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/5.9.1/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--save',
1 verbose cli   'git+ssh://git@git.redacted.io:redacted/redacted.git' ]
2 info using npm@3.7.3
3 info using node@v5.9.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData git+ssh://git@git.redacted.io:redacted/redacted.git
8 silly fetchOtherPackageData git+ssh://git@git.redacted.io:redacted/redacted.git
9 silly cache add args [ 'git+ssh://git@git.redacted.io:redacted/redacted.git', null ]
10 verbose cache add spec git+ssh://git@git.redacted.io:redacted/redacted.git
11 silly cache add parsed spec Result {
11 silly cache add   raw: 'git+ssh://git@git.redacted.io:redacted/redacted.git',
11 silly cache add   scope: null,
11 silly cache add   name: null,
11 silly cache add   rawSpec: 'git+ssh://git@git.redacted.io:redacted/redacted.git',
11 silly cache add   spec: 'ssh://git@git.redacted.io:redacted/redacted.git',
11 silly cache add   type: 'git' }
12 verbose addRemoteGit caching git+ssh://git@git.redacted.io:redacted/redacted.git
13 silly tryClone cloning git+ssh://git@git.redacted.io:redacted/redacted.git via git+ssh://git@git.redacted.io:redacted/redacted.git
14 verbose tryClone git-ssh-git-git-redacted-io-redacted-redacted-git-a20750cd not in flight; caching
15 verbose correctMkdir /Users/redacted/.npm/_git-remotes correctMkdir not in flight; initializing
16 verbose makeDirectory /Users/redacted/.npm/_git-remotes creation not in flight; initializing
17 silly makeDirectory /Users/redacted/.npm/_git-remotes uid: 501 gid: 20
18 info git [ 'clone',
18 info git   '--template=/Users/redacted/.npm/_git-remotes/_templates',
18 info git   '--mirror',
18 info git   'git@git.redacted.io:redacted/redacted.git',
18 info git   '/Users/redacted/.npm/_git-remotes/git-ssh-git-git-redacted-io-redacted-redacted-git-a20750cd' ]
19 verbose mirrorRemote git+ssh://git@git.redacted.io:redacted/redacted.git git clone git@git.redacted.io:redacted/redacted.git
20 verbose correctMkdir /Users/redacted/.npm/_git-remotes correctMkdir not in flight; initializing
21 verbose setPermissions git+ssh://git@git.redacted.io:redacted/redacted.git set permissions on /Users/redacted/.npm/_git-remotes/git-ssh-git-git-redacted-io-redacted-redacted-git-a20750cd
22 verbose resolveHead git+ssh://git@git.redacted.io:redacted/redacted.git original treeish: master
23 info git [ 'rev-list', '-n1', 'master' ]
24 silly resolveHead git+ssh://git@git.redacted.io:redacted/redacted.git resolved treeish: 46fa3dc1862fd2d249cd4e8f858298a5ece5fd72
25 verbose resolveHead git+ssh://git@git.redacted.io:redacted/redacted.git resolved Git URL: git+ssh://git@git.redacted.io:redacted/redacted.git#46fa3dc1862fd2d249cd4e8f858298a5ece5fd72
26 silly resolveHead Git working directory: /var/folders/nz/sxc1c3cj55d3dr131c2c2jf00000gn/T/npm-5983-19f5a9aa/git-cache-41fa280d/46fa3dc1862fd2d249cd4e8f858298a5ece5fd72
27 info git [ 'clone',
27 info git   '/Users/redacted/.npm/_git-remotes/git-ssh-git-git-redacted-io-redacted-redacted-git-a20750cd',
27 info git   '/var/folders/nz/sxc1c3cj55d3dr131c2c2jf00000gn/T/npm-5983-19f5a9aa/git-cache-41fa280d/46fa3dc1862fd2d249cd4e8f858298a5ece5fd72' ]
28 verbose cloneResolved git+ssh://git@git.redacted.io:redacted/redacted.git clone Cloning into '/var/folders/nz/sxc1c3cj55d3dr131c2c2jf00000gn/T/npm-5983-19f5a9aa/git-cache-41fa280d/46fa3dc1862fd2d249cd4e8f858298a5ece5fd72'...
28 verbose cloneResolved done.
29 info git [ 'checkout', '46fa3dc1862fd2d249cd4e8f858298a5ece5fd72' ]
30 verbose checkoutTreeish git+ssh://git@git.redacted.io:redacted/redacted.git checkout Note: checking out '46fa3dc1862fd2d249cd4e8f858298a5ece5fd72'.
30 verbose checkoutTreeish
30 verbose checkoutTreeish You are in 'detached HEAD' state. You can look around, make experimental
30 verbose checkoutTreeish changes and commit them, and you can discard any commits you make in this
30 verbose checkoutTreeish state without impacting any branches by performing another checkout.
30 verbose checkoutTreeish
30 verbose checkoutTreeish If you want to create a new branch to retain commits you create, you may
30 verbose checkoutTreeish do so (now or later) by using -b with the checkout command again. Example:
30 verbose checkoutTreeish
30 verbose checkoutTreeish   git checkout -b <new-branch-name>
30 verbose checkoutTreeish
30 verbose checkoutTreeish HEAD is now at 46fa3dc... .
31 info git [ 'submodule', '-q', 'update', '--init', '--recursive' ]
32 verbose updateSubmodules git+ssh://git@git.redacted.io:redacted/redacted.git submodule update
33 error addLocal Could not install /var/folders/nz/sxc1c3cj55d3dr131c2c2jf00000gn/T/npm-5983-19f5a9aa/git-cache-41fa280d/46fa3dc1862fd2d249cd4e8f858298a5ece5fd72
34 silly fetchPackageMetaData Error: EISDIR: illegal operation on a directory, read
34 silly fetchPackageMetaData     at Error (native)
34 silly fetchPackageMetaData  error for git+ssh://git@git.redacted.io:redacted/redacted.git { [Error: EISDIR: illegal operation on a directory, read] errno: -21, code: 'EISDIR', syscall: 'read' }
35 silly rollbackFailedOptional Starting
36 silly rollbackFailedOptional Finishing
37 silly runTopLevelLifecycles Starting
38 silly runTopLevelLifecycles Finishing
39 silly install printInstalled
40 verbose stack Error: EISDIR: illegal operation on a directory, read
40 verbose stack     at Error (native)
41 verbose cwd /Users/redacted/src/redacted/ta
42 error Darwin 15.3.0
43 error argv "/usr/local/Cellar/node/5.9.1/bin/node" "/usr/local/bin/npm" "install" "--save" "git+ssh://git@git.redacted.io:redacted/redacted.git"
44 error node v5.9.1
45 error npm  v3.7.3
46 error code EISDIR
47 error errno -21
48 error syscall read
49 error eisdir EISDIR: illegal operation on a directory, read
50 error eisdir This is most likely not a problem with npm itself
50 error eisdir and is related to npm not being able to find a package.json in
50 error eisdir a package you are trying to install.
51 verbose exit [ -21, true ]
```

**Comment by KenanY** [comment]
@andreis That repo has a `package.json`?

**Comment by e-cloud** [comment]
looks like being related to #11032
