### ISSUE TITLE
Unable to install Cordova using NPM with the following error

### ISSUE THREAD

**Issue by tusharagaarwal** [npm/npm#11700]
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'cordova' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 silly cache add args [ 'cordova', null ]
6 verbose cache add spec cordova
7 silly cache add parsed spec { raw: 'cordova',
7 silly cache add   scope: null,
7 silly cache add   name: 'cordova',
7 silly cache add   rawSpec: '',
7 silly cache add   spec: '*',
7 silly cache add   type: 'range' }
8 verbose addNamed cordova@*
9 silly addNamed semver.valid null
10 silly addNamed semver.validRange *
11 silly addNameRange { name: 'cordova', range: '*', hasData: false }
12 silly mapToRegistry name cordova
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/cordova
16 verbose addNameRange registry:https://registry.npmjs.org/cordova not in flight; fetching
17 verbose request uri https://registry.npmjs.org/cordova
18 verbose request no auth needed
19 info attempt registry request try #1 at 1:08:37 AM
20 verbose request id 6d7e55b47b3d490f
21 http request GET https://registry.npmjs.org/cordova
22 info retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN
23 info attempt registry request try #2 at 1:08:47 AM
24 http request GET https://registry.npmjs.org/cordova
25 info retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN
26 info attempt registry request try #3 at 1:09:47 AM
27 http request GET https://registry.npmjs.org/cordova
28 verbose stack Error: getaddrinfo EAI_AGAIN
28 verbose stack     at Object.exports._errnoException (util.js:746:11)
28 verbose stack     at errnoException (dns.js:49:15)
28 verbose stack     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:94:26)
29 verbose cwd C:\Users\tushar_agarwal05
30 error Windows_NT 6.1.7601
31 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova"
32 error node v0.12.0
33 error npm  v2.5.1
34 error code EAI_AGAIN
35 error errno EAI_AGAIN
36 error syscall getaddrinfo
37 error getaddrinfo EAI_AGAIN
38 error If you need help, you may report this error at:
38 error     <http://github.com/npm/npm/issues>
39 verbose exit [ 1, true ]
```

**Comment by iarna** [comment]
Yikes, that error message is hard to understand! So...

`EAI_AGAIN` in `getaddrinfo` means that npm is having trouble looking up the address for `registry.npmjs.org`.

If the internet is otherwise working for you, this usually means that you need to configure a proxy.

The core documentation for doing that are these:

https://docs.npmjs.com/misc/config#https-proxy
https://docs.npmjs.com/misc/config#proxy

And there's a little third party guide here:

http://jjasonclark.com/how-to-setup-node-behind-web-proxy/

If you find you need more help I encourage you to drop an email to `support@npmjs.com` and the fine folks there would be happy to work through things with you.
