### ISSUE TITLE
please，help，why  error Windows_NT 10.0.10586

### ISSUE THREAD

**Issue by showerychn** [npm/npm#11733]
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Administrator.2013-20150705MU\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@3.7.5
3 info using node@v5.7.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle sogu-fe@0.0.1~predev: sogu-fe@0.0.1
6 silly lifecycle sogu-fe@0.0.1~predev: no script for predev, continuing
7 info lifecycle sogu-fe@0.0.1~dev: sogu-fe@0.0.1
8 verbose lifecycle sogu-fe@0.0.1~dev: unsafe-perm in lifecycle true
9 verbose lifecycle sogu-fe@0.0.1~dev: PATH: C:\Users\Administrator.2013-20150705MU\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;E:\sogu-fe\node_modules\.bin;C:\Program Files\nodejs;C:\Ruby22\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows7Master;C:\Program Files\TortoiseGit\bin;C:\Program Files\nodejs\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;D:\Program Files (x86)\nodeJs\node_modules\npm;C:\Program Files\nodejs;C:\Users\Administrator.2013-20150705MU\AppData\Roaming\npm;C:\Program Files (x86)\Git\bin;C:\Program Files (x86)\Git\cmd;D:\software\rubygems-2.5.0\
10 verbose lifecycle sogu-fe@0.0.1~dev: CWD: E:\sogu-fe
11 silly lifecycle sogu-fe@0.0.1~dev: Args: [ '/d /s /c', 'better-npm-run dev' ]
12 silly lifecycle sogu-fe@0.0.1~dev: Returned: code: 1  signal: null
13 info lifecycle sogu-fe@0.0.1~dev: Failed to exec dev script
14 verbose stack Error: sogu-fe@0.0.1 dev: `better-npm-run dev`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\Administrator.2013-20150705MU\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:239:16)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at EventEmitter.emit (events.js:185:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\Administrator.2013-20150705MU\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at ChildProcess.emit (events.js:185:7)
14 verbose stack     at maybeClose (internal/child_process.js:827:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid sogu-fe@0.0.1
16 verbose cwd E:\sogu-fe

17 error Windows_NT 10.0.10586
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Administrator.2013-20150705MU\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"

19 error node v5.7.0
20 error npm  v3.7.5
21 error code ELIFECYCLE
22 error sogu-fe@0.0.1 dev: `better-npm-run dev`
22 error Exit status 1
23 error Failed at the sogu-fe@0.0.1 dev script 'better-npm-run dev'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the sogu-fe package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     better-npm-run dev
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs sogu-fe
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls sogu-fe
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by othiym23** [comment]
```
11 silly lifecycle sogu-fe@0.0.1~dev: Args: [ '/d /s /c', 'better-npm-run dev' ]
12 silly lifecycle sogu-fe@0.0.1~dev: Returned: code: 1  signal: null
13 info lifecycle sogu-fe@0.0.1~dev: Failed to exec dev script
14 verbose stack Error: sogu-fe@0.0.1 dev: `better-npm-run dev`
```

This says to me that `better-npm-run` encountered an error at runtime and bailed out. Unfortunately, at present npm doesn't include run-script output in the debug log (this is something the CLI team intends to change – see #10491 for details). This means that I can't tell you what's causing `better-npm-run` to fail. That said, `better-npm-run` isn't a part of npm itself, so if it turns out that it's doing something unexpected, you should [take it up with the `better-npm-run` team](https://github.com/benoror/better-npm-run/issues). Because this isn't an npm CLI bug, I'm going to close this issue, and thanks for your time!
