### ISSUE TITLE
Running an npm update without an npm install gives curious error message

### ISSUE THREAD

**Issue by doug-wade** [npm/npm#11760]
One of the engineers at the office ran an `npm update` on a package that had not had an `npm install` run on it beforehand.  The error message really made me scratch my head

```
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "update" "--registry" "http://qa-compile-1.redfintest.com:4873"
npm ERR! node v4.3.1
npm ERR! npm  v2.14.12

npm ERR! Cannot read property 'version' of undefined
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/robert.kopp/code/main/rf-build-metrics-client/npm-debug.log
[ERROR] Error: Command failed: npm update --registry http://qa-compile-1.redfintest.com:4873
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "update" "--registry" "http://qa-compile-1.redfintest.com:4873"
npm ERR! node v4.3.1
npm ERR! npm  v2.14.12

npm ERR! Cannot read property 'version' of undefined
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/robert.kopp/code/main/rf-build-metrics-client/npm-debug.log
```

The full npm-debug.log was not much more helpful

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/iojs',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'update',
1 verbose cli   '--registry',
1 verbose cli   'http://qa-compile-1.redfintest.com:4873' ]
2 info using npm@2.14.12
3 info using node@v4.3.1
4 silly mapToRegistry name rf-build-metrics-server
5 silly mapToRegistry using default registry
6 silly mapToRegistry registry http://qa-compile-1.redfintest.com:4873/
7 silly mapToRegistry uri http://qa-compile-1.redfintest.com:4873/rf-build-metrics-server
8 silly mapToRegistry name superagent
9 silly mapToRegistry using default registry
10 silly mapToRegistry registry http://qa-compile-1.redfintest.com:4873/
11 silly mapToRegistry uri http://qa-compile-1.redfintest.com:4873/superagent
12 verbose request uri http://qa-compile-1.redfintest.com:4873/rf-build-metrics-server
13 verbose request no auth needed
14 info attempt registry request try #1 at 10:59:46 AM
15 verbose request id f1e0b26d7f64ee0a
16 http request GET http://qa-compile-1.redfintest.com:4873/rf-build-metrics-server
17 verbose get http://qa-compile-1.redfintest.com:4873/superagent not expired, no request
18 http 404 http://qa-compile-1.redfintest.com:4873/rf-build-metrics-server
19 verbose headers { 'x-powered-by': 'Sinopia/1.4.0',
19 verbose headers   'content-type': 'application/json; charset=utf-8',
19 verbose headers   'content-length': '43',
19 verbose headers   etag: 'W/"2b-d418f262"',
19 verbose headers   vary: 'Accept-Encoding',
19 verbose headers   'x-status-cat': 'http://flic.kr/p/aV6juR',
19 verbose headers   date: 'Thu, 03 Mar 2016 18:59:46 GMT',
19 verbose headers   connection: 'keep-alive' }
20 silly get cb [ 404,
20 silly get   { 'x-powered-by': 'Sinopia/1.4.0',
20 silly get     'content-type': 'application/json; charset=utf-8',
20 silly get     'content-length': '43',
20 silly get     etag: 'W/"2b-d418f262"',
20 silly get     vary: 'Accept-Encoding',
20 silly get     'x-status-cat': 'http://flic.kr/p/aV6juR',
20 silly get     date: 'Thu, 03 Mar 2016 18:59:46 GMT',
20 silly get     connection: 'keep-alive' } ]
21 verbose stack TypeError: Cannot read property 'version' of undefined
21 verbose stack     at /usr/local/lib/node_modules/npm/lib/outdated.js:337:15
21 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:345:5
21 verbose stack     at checkBinReferences_ (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:309:45)
21 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:343:3)
21 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:113:5)
21 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:232:12
21 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:76:16
21 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
22 verbose cwd /Users/robert.kopp/code/main/rf-build-metrics-client
23 error Darwin 14.5.0
24 error argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "update" "--registry" "http://qa-compile-1.redfintest.com:4873"
25 error node v4.3.1
26 error npm  v2.14.12
27 error Cannot read property 'version' of undefined
28 error If you need help, you may report this error at:
28 error     <https://github.com/npm/npm/issues>
29 verbose exit [ 1, true ]
```

I'd like to pull together a PR to throw a more helpful error message (probably something like checking to see if there is a node_modules directory and throwing a "you have to run an npm install first" error).

**Comment by doug-wade** [comment]
Note that this doesn't happen on npm 3.8, but does happen on npm 2.14
