### ISSUE TITLE
URIError: URI malformed - after

### ISSUE THREAD

**Issue by MichaelRodrigueess0s1** [npm/npm#11768]
Hello, the problems start when i tried configurated  the proxy, i made a comand  "npm set proxy ...", but after this comand, everting i try execute an simple comand, npm in my cmd, i receive the following response:

i tried too unnisntal and resintal my node with npm but not success!!! =/, i tried too set a defaut proxy afther, but not success too

Microsoft Windows [versão 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. Todos os direitos reservados.

C:\Users\michael.rodrigues>npm config get globalconfig
URIError: URI malformed
    at decodeURIComponent (native)
    at Url.parse (url.js:215:19)
    at Object.urlParse [as parse](url.js:104:5)
    at Object.validateUrl [as validate](C:Program Files %28x86%29nodejsnode_modulesnpmnode_modulesnoptlibnopt.js:164:13)
    at validate (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\nopt\lib\nopt.js:212:24)
    at validate (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\nopt\lib\nopt.js:179:11)
    at C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\nopt\lib\nopt.js:101:12
    at Array.map (native)
    at C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\nopt\lib\nopt.js:67:15
    at Array.forEach (native)

C:\Program Files (x86)\nodejs\node_modules\npm\lib\npm.js:31
    throw new Error('npm.load() required')
          ^
Error: npm.load() required
    at Object.npm.config.get (C:\Program Files (x86)\nodejs\node_modules\npm\lib\npm.js:31:11)
    at exit (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\error-handler.js:57:40)
    at process.errorHandler (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\error-handler.js:363:3)
    at process.emit (events.js:107:17)
    at process._fatalException (node.js:236:26)

C:\Users\michael.rodrigues>

**Comment by dileephell** [comment]
I am also getting the same error after installed the latest version of node.js which is v4.6.1. Even when i am checking the npm version itself i am getting the same error again and again. Tried to set the proxy as well but bad luck.
