### ISSUE TITLE
npm install --save-dev gulp problem

### ISSUE THREAD

**Issue by beknownru** [npm/npm#11772]
I have tried this command (`npm install --save-dev gulp`) after installing gulp and I received this error message: 
```
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\Programms\\nodejs\\node.exe',
1 verbose cli   'D:\\Programms\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '--save-dev',
1 verbose cli   'gulp' ]
2 info using npm@3.6.0
3 info using node@v5.6.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData gulp
8 silly fetchNamedPackageData gulp
9 silly mapToRegistry name gulp
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry uri https://registry.npmjs.org/gulp
13 verbose request uri https://registry.npmjs.org/gulp
14 verbose request no auth needed
15 info attempt registry request try #1 at 9:09:05 PM
16 verbose request id 918fa7b2b1ee4d19
17 verbose etag "1HZC0MTQ9EC6I4FHMN0SAMKNC"
18 http request GET https://registry.npmjs.org/gulp
19 http 304 https://registry.npmjs.org/gulp
20 verbose headers { date: 'Fri, 04 Mar 2016 20:08:56 GMT',
20 verbose headers   via: '1.1 varnish',
20 verbose headers   'cache-control': 'max-age=300',
20 verbose headers   etag: '"1HZC0MTQ9EC6I4FHMN0SAMKNC"',
20 verbose headers   age: '96',
20 verbose headers   connection: 'keep-alive',
20 verbose headers   'x-served-by': 'cache-fra1243-FRA',
20 verbose headers   'x-cache': 'HIT',
20 verbose headers   'x-cache-hits': '3',
20 verbose headers   'x-timer': 'S1457122136.680122,VS0,VE0',
20 verbose headers   vary: 'Accept' }
21 silly get cb [ 304,
21 silly get   { date: 'Fri, 04 Mar 2016 20:08:56 GMT',
21 silly get     via: '1.1 varnish',
21 silly get     'cache-control': 'max-age=300',
21 silly get     etag: '"1HZC0MTQ9EC6I4FHMN0SAMKNC"',
21 silly get     age: '96',
21 silly get     connection: 'keep-alive',
21 silly get     'x-served-by': 'cache-fra1243-FRA',
21 silly get     'x-cache': 'HIT',
21 silly get     'x-cache-hits': '3',
21 silly get     'x-timer': 'S1457122136.680122,VS0,VE0',
21 silly get     vary: 'Accept' } ]
22 verbose etag https://registry.npmjs.org/gulp from cache
23 verbose get saving gulp to C:\Users\ateshabaev\AppData\Roaming\npm-cache\registry.npmjs.org\gulp\.cache.json
24 verbose correctMkdir C:\Users\ateshabaev\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
25 silly install normalizeTree
26 silly loadCurrentTree Finishing
27 silly loadIdealTree Starting
28 silly install loadIdealTree
29 silly cloneCurrentTree Starting
30 silly install cloneCurrentTreeToIdealTree
31 silly cloneCurrentTree Finishing
32 silly loadShrinkwrap Starting
33 silly install loadShrinkwrap
34 silly loadShrinkwrap Finishing
35 silly loadAllDepsIntoIdealTree Starting
36 silly install loadAllDepsIntoIdealTree
37 silly rollbackFailedOptional Starting
38 silly rollbackFailedOptional Finishing
39 silly runTopLevelLifecycles Starting
40 silly runTopLevelLifecycles Finishing
41 silly install printInstalled
42 verbose stack Error: Refusing to install gulp as a dependency of itself
42 verbose stack     at checkSelf (D:\Programms\nodejs\node_modules\npm\lib\install\validate-args.js:53:14)
42 verbose stack     at Array.<anonymous> (D:\Programms\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
42 verbose stack     at LOOP (D:\Programms\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
42 verbose stack     at chain (D:\Programms\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
42 verbose stack     at D:\Programms\nodejs\node_modules\npm\lib\install\validate-args.js:16:5
42 verbose stack     at D:\Programms\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:35
42 verbose stack     at Array.forEach (native)
42 verbose stack     at D:\Programms\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:11
42 verbose stack     at Array.forEach (native)
42 verbose stack     at asyncMap (D:\Programms\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:51:8)
43 verbose cwd D:\dev\gulp
44 error Windows_NT 6.1.7601
45 error argv "D:\\Programms\\nodejs\\node.exe" "D:\\Programms\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save-dev" "gulp"
46 error node v5.6.0
47 error npm  v3.6.0
48 error code ENOSELF
49 error Refusing to install gulp as a dependency of itself
50 error If you need help, you may report this error at:
50 error     <https://github.com/npm/npm/issues>
51 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
Hello @beknownru! Have you tried renaming your current working directory to something other than `gulp`?

**Comment by beknownru** [comment]
@KenanY thank you for the suggestion, however I'm still having the same problem.

**Comment by KenanY** [comment]
@beknownru Does your `package.json` have `"name": "gulp"`?

**Comment by beknownru** [comment]
@KenanY yes and this is the content of it. 
```
{
  "name": "gulp",
  "version": "0.0.1",
  "description": "First use of gulp",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}
```

**Comment by KenanY** [comment]
@beknownru Change `"name"` so that it does not share the same name as one of your dependencies (in this case `gulp`).

**Comment by beknownru** [comment]
@KenanY thank you very much. it has saved my problem.
