### ISSUE TITLE
Error while installing foundation-sites

### ISSUE THREAD

**Issue by uranuz** [npm/npm#11789]
Error while installing dependencies of foundation-sites

```
sudo npm install foundation-sites

npm http 304 https://registry.npmjs.org/gulp-cache-bust
npm http 404 https://registry.npmjs.org/corejs-typeahead
npm ERR! TypeError: Object.keys called on non-object
npm ERR!     at Function.keys (native)
npm ERR!     at installTargetsError (/usr/share/npm/lib/cache.js:708:24)
npm ERR!     at /usr/share/npm/lib/cache.js:638:10
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-79-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/uranuz/sources/foundation_test/node_modules/foundation-sites
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! type called_on_non_object
npm http 304 https://registry.npmjs.org/supercollider
npm http 304 https://registry.npmjs.org/gulp-rename
npm http 304 https://registry.npmjs.org/sass-true
npm http 304 https://registry.npmjs.org/gulp-scss-lint
npm http 404 https://registry.npmjs.org/foundation-docs
npm ERR! TypeError: Object.keys called on non-object
npm ERR!     at Function.keys (native)
npm ERR!     at installTargetsError (/usr/share/npm/lib/cache.js:708:24)
npm ERR!     at /usr/share/npm/lib/cache.js:638:10
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-79-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/uranuz/sources/foundation_test/node_modules/foundation-sites
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! type called_on_non_object
```

**Comment by KenanY** [comment]
Hello @uranuz! Please try [updating `npm`](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm).

**Comment by KenanY** [comment]
@uranuz Are you still experiencing this issue?

**Comment by othiym23** [comment]
Closing as abandoned. Open a new issue if you encounter this behavior again!
