### ISSUE TITLE
Cordova won't install

### ISSUE THREAD

**Issue by Funky74** [npm/npm#11812]
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'cordova' ]
2 info using npm@3.6.0
3 info using node@v5.7.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData cordova
8 silly fetchNamedPackageData cordova
9 silly mapToRegistry name cordova
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry uri https://registry.npmjs.org/cordova
13 verbose request uri https://registry.npmjs.org/cordova
14 verbose request no auth needed
15 info attempt registry request try #1 at 10:01:29 AM
16 verbose request id bd3e792e88615094
17 http request GET https://registry.npmjs.org/cordova
18 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
19 info attempt registry request try #2 at 10:01:40 AM
20 http request GET https://registry.npmjs.org/cordova
21 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
22 info attempt registry request try #3 at 10:02:41 AM
23 http request GET https://registry.npmjs.org/cordova
24 silly fetchPackageMetaData Error: self signed certificate in certificate chain
24 silly fetchPackageMetaData     at Error (native)
24 silly fetchPackageMetaData     at TLSSocket.<anonymous> (_tls_wrap.js:1061:38)
24 silly fetchPackageMetaData     at emitNone (events.js:80:13)
24 silly fetchPackageMetaData     at TLSSocket.emit (events.js:179:7)
24 silly fetchPackageMetaData     at TLSSocket._init.ssl.onclienthello.ssl.oncertcb.TLSSocket._finishInit (_tls_wrap.js:593:8)
24 silly fetchPackageMetaData     at TLSWrap.ssl.onclienthello.ssl.oncertcb.ssl.onnewsession.ssl.onhandshakedone (_tls_wrap.js:425:38)
24 silly fetchPackageMetaData  error for cordova { [Error: self signed certificate in certificate chain] code: 'SELF_SIGNED_CERT_IN_CHAIN' }
25 silly rollbackFailedOptional Starting
26 silly rollbackFailedOptional Finishing
27 silly runTopLevelLifecycles Starting
28 silly runTopLevelLifecycles Finishing
29 silly install printInstalled
30 verbose stack Error: self signed certificate in certificate chain
30 verbose stack     at Error (native)
30 verbose stack     at TLSSocket.<anonymous> (_tls_wrap.js:1061:38)
30 verbose stack     at emitNone (events.js:80:13)
30 verbose stack     at TLSSocket.emit (events.js:179:7)
30 verbose stack     at TLSSocket._init.ssl.onclienthello.ssl.oncertcb.TLSSocket._finishInit (_tls_wrap.js:593:8)
30 verbose stack     at TLSWrap.ssl.onclienthello.ssl.oncertcb.ssl.onnewsession.ssl.onhandshakedone (_tls_wrap.js:425:38)
31 verbose cwd c:\
32 error Windows_NT 6.1.7601
33 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova"
34 error node v5.7.1
35 error npm  v3.6.0
36 error code SELF_SIGNED_CERT_IN_CHAIN
37 error self signed certificate in certificate chain
38 error If you need help, you may report this error at:
38 error     <https://github.com/npm/npm/issues>
39 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
@Funky74 Still facing this issue?

**Comment by KenanY** [comment]
Closing as abandoned.
