### ISSUE TITLE
npm ERR! getaddrinfo EAI_AGAIN registry.npmjs.org:443

### ISSUE THREAD

**Issue by patjan** [npm/npm#11832]
https://registry.npmjs.org/
{"db_name":"registry","doc_count":282246,"doc_del_count":358,"update_seq":1350499,"purge_seq":0,"compact_running":false,"disk_size":1300516987,"data_size":1036342096,"instance_start_time":"1457365474765721","disk_format_version":6,"committed_update_seq":1350499}

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'nodemailer' ]
2 info using npm@3.6.0
3 info using node@v5.6.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData nodemailer
8 silly fetchNamedPackageData nodemailer
9 silly mapToRegistry name nodemailer
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry uri https://registry.npmjs.org/nodemailer
13 verbose request uri https://registry.npmjs.org/nodemailer
14 verbose request no auth needed
15 info attempt registry request try #1 at 6:15:09 AM
16 verbose request id bd3b4f6b9ed32e1a
17 http request GET https://registry.npmjs.org/nodemailer
18 info retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
19 info attempt registry request try #2 at 6:15:19 AM
20 http request GET https://registry.npmjs.org/nodemailer
21 info retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
22 info attempt registry request try #3 at 6:16:19 AM
23 http request GET https://registry.npmjs.org/nodemailer
24 silly fetchPackageMetaData Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
24 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:856:11)
24 silly fetchPackageMetaData     at errnoException (dns.js:31:15)
24 silly fetchPackageMetaData     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)
24 silly fetchPackageMetaData  error for nodemailer { [Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443]
24 silly fetchPackageMetaData   code: 'EAI_AGAIN',
24 silly fetchPackageMetaData   errno: 'EAI_AGAIN',
24 silly fetchPackageMetaData   syscall: 'getaddrinfo',
24 silly fetchPackageMetaData   hostname: 'registry.npmjs.org',
24 silly fetchPackageMetaData   host: 'registry.npmjs.org',
24 silly fetchPackageMetaData   port: 443 }
25 silly rollbackFailedOptional Starting
26 silly rollbackFailedOptional Finishing
27 silly runTopLevelLifecycles Starting
28 silly runTopLevelLifecycles Finishing
29 silly install printInstalled
30 verbose stack Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
30 verbose stack     at Object.exports._errnoException (util.js:856:11)
30 verbose stack     at errnoException (dns.js:31:15)
30 verbose stack     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)
31 verbose cwd /mnt/hgfs/nodejs
32 error Linux 2.6.32-573.18.1.el6.x86_64
33 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "nodemailer"
34 error node v5.6.0
35 error npm  v3.6.0
36 error code EAI_AGAIN
37 error errno EAI_AGAIN
38 error syscall getaddrinfo
39 error getaddrinfo EAI_AGAIN registry.npmjs.org:443
40 error If you need help, you may report this error at:
40 error     <https://github.com/npm/npm/issues>
41 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
@patjan Is this still an issue for you?

**Comment by KenanY** [comment]
Closing as abandoned.
