### ISSUE TITLE
Invalid Version: 3.12.00, codemirror package can't be installed

### ISSUE THREAD

**Issue by marcj** [npm/npm#11835]
I installed newest version of node and npm and can't install codemirror anymore. I'm working with other projects that use npm as well, and a npm project with deps like following works beautiful fine:

```
    "angular": "^1.4.8",
    "angular-ui-bootstrap": "^1.0.3",
    "bootstrap": "^3.3.6",
    "browserify": "^13.0.0",
    "electron-reload": "^0.2.0",
    "gulp": "^3.9.0",
    "gulp-browserify": "^0.5.1",
    "gulp-sass": "^2.1.1",
    "gulp-sourcemaps": "^1.6.0",
    "gulp-typescript": "^2.10.0",
    "iscroll": "^5.1.3",
    "moment": "^2.11.1",
    "n3-charts": "^2.0.3",
    "randomcolor": "^0.4.3",
    "tsify": "^0.13.2",
    "humanize-duration": "^3.6.1"
```
But when I add codemirror to this project or to a completely new I get some weird error. It tries to load somehow a very old codemirror version `3.12.00`, which did exist but is way too outdated.

I do following:

```bash
rm -rf /Users/marc/.npm/
mkdir test
cd test
npm install codemirror
```

then this error pops up:

```
pm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "codemirror"
npm ERR! node v5.8.0
npm ERR! npm  v3.7.3

npm ERR! Invalid Version: 3.12.00
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/marc/bude/test/npm-debug.log
```

npm-debug.log
```
$ cat /Users/marc/bude/test/npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'codemirror' ]
2 info using npm@3.7.3
3 info using node@v5.8.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData codemirror
8 silly fetchNamedPackageData codemirror
9 silly mapToRegistry name codemirror
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry uri https://registry.npmjs.org/codemirror
13 verbose request uri https://registry.npmjs.org/codemirror
14 verbose request no auth needed
15 info attempt registry request try #1 at 7:36:07 PM
16 verbose request using bearer token for auth
17 verbose request id f110d3f4ac9b0518
18 http request GET https://registry.npmjs.org/codemirror
19 http 200 https://registry.npmjs.org/codemirror
20 verbose headers { server: 'nginx/1.4.6 (Ubuntu)',
20 verbose headers   'content-type': 'application/json',
20 verbose headers   'last-modified': 'Wed, 24 Feb 2016 20:01:35 GMT',
20 verbose headers   etag: '"56ce0c1f-620da"',
20 verbose headers   expires: 'Thu, 10 Mar 2016 00:36:07 GMT',
20 verbose headers   'access-control-allow-origin': '*',
20 verbose headers   'access-control-allow-methods': 'GET',
20 verbose headers   'accept-ranges': 'bytes, bytes',
20 verbose headers   'cache-control': 'max-age=300',
20 verbose headers   'content-length': '401626',
20 verbose headers   date: 'Wed, 09 Mar 2016 18:36:07 GMT',
20 verbose headers   via: '1.1 varnish',
20 verbose headers   connection: 'keep-alive',
20 verbose headers   'x-served-by': 'cache-fra1246-FRA',
20 verbose headers   'x-cache': 'MISS',
20 verbose headers   'x-cache-hits': '0',
20 verbose headers   'x-timer': 'S1457548567.568572,VS0,VE48' }
21 silly get cb [ 200,
21 silly get   { server: 'nginx/1.4.6 (Ubuntu)',
21 silly get     'content-type': 'application/json',
21 silly get     'last-modified': 'Wed, 24 Feb 2016 20:01:35 GMT',
21 silly get     etag: '"56ce0c1f-620da"',
21 silly get     expires: 'Thu, 10 Mar 2016 00:36:07 GMT',
21 silly get     'access-control-allow-origin': '*',
21 silly get     'access-control-allow-methods': 'GET',
21 silly get     'accept-ranges': 'bytes, bytes',
21 silly get     'cache-control': 'max-age=300',
21 silly get     'content-length': '401626',
21 silly get     date: 'Wed, 09 Mar 2016 18:36:07 GMT',
21 silly get     via: '1.1 varnish',
21 silly get     connection: 'keep-alive',
21 silly get     'x-served-by': 'cache-fra1246-FRA',
21 silly get     'x-cache': 'MISS',
21 silly get     'x-cache-hits': '0',
21 silly get     'x-timer': 'S1457548567.568572,VS0,VE48' } ]
22 verbose get saving codemirror to /Users/marc/.npm/registry.npmjs.org/codemirror/.cache.json
23 verbose correctMkdir /Users/marc/.npm correctMkdir not in flight; initializing
24 verbose makeDirectory /Users/marc/.npm creation not in flight; initializing
25 silly makeDirectory /Users/marc/.npm uid: 501 gid: 20
26 verbose stack TypeError: Invalid Version: 3.12.00
26 verbose stack     at new SemVer (/usr/local/lib/node_modules/npm/node_modules/semver/semver.js:293:11)
26 verbose stack     at SemVer.compare (/usr/local/lib/node_modules/npm/node_modules/semver/semver.js:342:13)
26 verbose stack     at compare (/usr/local/lib/node_modules/npm/node_modules/semver/semver.js:566:31)
26 verbose stack     at rcompare (/usr/local/lib/node_modules/npm/node_modules/semver/semver.js:576:10)
26 verbose stack     at Array.sort (native)
26 verbose stack     at pickVersionFromRegistryDocument (/usr/local/lib/node_modules/npm/lib/fetch-package-metadata.js:121:48)
26 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/iferr/index.js:13:50
26 verbose stack     at /usr/local/lib/node_modules/npm/lib/utils/pulse-till-done.js:19:8
26 verbose stack     at saved (/usr/local/lib/node_modules/npm/lib/cache/caching-client.js:168:7)
26 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:210:7
27 verbose cwd /Users/marc/bude/test
28 error Darwin 15.3.0
29 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "codemirror"
30 error node v5.8.0
31 error npm  v3.7.3
32 error Invalid Version: 3.12.00
33 error If you need help, you may report this error at:
33 error     <https://github.com/npm/npm/issues>
34 verbose exit [ 1, true ]
```

Anyone an idea? Maybe another cache folder I can clear?

**Comment by andrenarchy** [comment]
I just had the same problem with a fresh install of `shelljs` on multiple machines:

```
$ npm install shelljs
npm ERR! Linux 4.2.0-30-generic
npm ERR! argv "/home/andre/.nvm/versions/node/v5.6.0/bin/node" "/home/andre/.nvm/versions/node/v5.6.0/bin/npm" "install" "shelljs@0.0.x"
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0

npm ERR! Invalid Version: 0.0.1alpha1
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/andre/git-repos/paperhive-backend/npm-debug.log
```

Now everything is working again. Maybe the npm registry was unavailable or delivering wrong data?

**Comment by marcj** [comment]
Oh indeed, it works again. I wonder what the actual failure was? Is there a fallback someone can use in such cases?

**Comment by othiym23** [comment]
This was a result of the rollout of a new version of the primary registry's CDN configuration. There were a couple problems with the new configuration, including some incompatible changes around how the registry deals with iffy versions in published packages. That configuration has been rolled back as a consequence of this problem for further testing and development.  See the resolution of #11836 for further details. Thanks for your time and for bringing this to our attention!
