### ISSUE TITLE
npm throws after updating node via Homebrew 

### ISSUE THREAD

**Issue by mohsen1** [npm/npm#11858]
```
npm -v
module.js:341
    throw err;
    ^

Error: Cannot find module 'npmlog'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:20:13
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:76:3)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
```

```
node -v
v5.6.0
```

Updating to node **5.8.0** fixed my issue. Updated via Mac installer instead of Homebrew

**Comment by othiym23** [comment]
This sounds like an issue to take up with the Homebrew maintainers for the Node / npm formula. This has happened a couple times recently, and in general there's not a lot that the CLI team can do when this happens. Thanks for your time, though!
