### ISSUE TITLE
npm ERR! enoent This is most likely not a problem with npm itself

### ISSUE THREAD

**Issue by monajalal** [npm/npm#11888]
Can someone help me to fix this?
```
bash-3.2$ yo meanjs
You're using the official MEAN.JS generator.
? What mean.js version would you like to generate? 0.4.0
0.4.0
? In which folder would you like the project to be generated? This can be changed later. mean
Cloning the MEAN repo.......
? What would you like to call your application? MEAN
? How would you describe your application? Full-Stack JavaScript with MongoDB, Express, AngularJS, and Node.js
? How would you describe your application in comma seperated key words? MongoDB, Express, AngularJS, Node.js
? What is your company/author name? University of Wisconsin-Madison/Mona Jalal
? Would you like to generate the article example CRUD module? Yes
? Would you like to generate the chat example module? Yes
Running npm install for you....
This may take a couple minutes.
Error: Command failed: cd mean && npm install
npm WARN deprecated phantomjs@2.1.3: Package renamed to phantomjs-prebuilt. Please update 'phantomjs' package references to 'phantomjs-prebuilt'
npm WARN deprecated lodash@0.9.2: Grunt needs your help! See https://github.com/gruntjs/grunt/issues/1403.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated graceful-fs@2.0.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN prefer global jshint@2.8.0 should be installed with -g
npm WARN prefer global node-inspector@0.10.2 should be installed with -g
npm WARN prefer global node-gyp@3.3.1 should be installed with -g
npm WARN mongodb-core@1.2.31 requires a peer of kerberos@~0.0 but none was installed.
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.8.0
npm ERR! npm  v3.7.3
npm ERR! path /Users/mona/interviews/mean/mean/node_modules/node-pre-gyp/bin/node-pre-gyp
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/mona/interviews/mean/mean/node_modules/node-pre-gyp/bin/node-pre-gyp'
npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/mona/interviews/mean/mean/node_modules/node-pre-gyp/bin/node-pre-gyp'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mona/interviews/mean/mean/npm-debug.log

    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:475:12)
bash-3.2$
``` 

Link to my question at SO: http://stackoverflow.com/questions/35981585/npm-err-enoent-and-is-related-to-npm-not-being-able-to-find-a-file

**Comment by mehedi101** [comment]
I am using windows platform and Homestead ; using these command and work for me : 
after getting those error form 
npm install --no-bin-links  . 
then I use these command 
gulp  --- its fail and to fix it i use 
npm rebuild node-sass  -- its fix the issue
gulp --- working.

**Comment by KenanY** [comment]
@monajalal Is this still an issue for you?

**Comment by KenanY** [comment]
Closing as abandoned.
