### ISSUE TITLE
Unable to install Nuclide server

### ISSUE THREAD

**Issue by 123subhadeep** [npm/npm#11897]
Debug log:

```
[deep@dev2111.prn1 ~/watchman] cat /home/deep/watchman/npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/fbcode/gcc-4.9-glibc-2.20-fb/bin/node-4.3.2',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'nuclide' ]
2 info using npm@3.5.3
3 info using node@v4.3.2
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData nuclide
8 silly fetchNamedPackageData nuclide
9 silly mapToRegistry name nuclide
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry uri https://registry.npmjs.org/nuclide
13 verbose request uri https://registry.npmjs.org/nuclide
14 verbose request no auth needed
15 info attempt registry request try #1 at 11:43:09
16 verbose request id 888158d0c976890e
17 http request GET https://registry.npmjs.org/nuclide
18 info retry will retry, error on last attempt: Error: connect ENETUNREACH ::ffff:23.235.47.162:443 - Local (:::0)
19 info attempt registry request try #2 at 11:43:19
20 http request GET https://registry.npmjs.org/nuclide
21 info retry will retry, error on last attempt: Error: connect ENETUNREACH ::ffff:199.27.79.162:443 - Local (:::0)
22 info attempt registry request try #3 at 11:44:19
23 http request GET https://registry.npmjs.org/nuclide
24 silly fetchPackageMetaData Error: connect ENETUNREACH ::ffff:199.27.79.162:443 - Local (:::0)
24 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:870:11)
24 silly fetchPackageMetaData     at exports._exceptionWithHostPort (util.js:893:20)
24 silly fetchPackageMetaData     at connect (net.js:843:14)
24 silly fetchPackageMetaData     at net.js:985:7
24 silly fetchPackageMetaData     at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:63:16)
24 silly fetchPackageMetaData     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:82:10)
24 silly fetchPackageMetaData  error for nuclide { [Error: connect ENETUNREACH ::ffff:199.27.79.162:443 - Local (:::0)]
24 silly fetchPackageMetaData   code: 'ENETUNREACH',
24 silly fetchPackageMetaData   errno: 'ENETUNREACH',
24 silly fetchPackageMetaData   syscall: 'connect',
24 silly fetchPackageMetaData   address: '::ffff:199.27.79.162',
24 silly fetchPackageMetaData   port: 443 }
25 silly rollbackFailedOptional Starting
26 silly rollbackFailedOptional Finishing
27 silly runTopLevelLifecycles Starting
28 silly runTopLevelLifecycles Finishing
29 silly install printInstalled
30 verbose stack Error: connect ENETUNREACH ::ffff:199.27.79.162:443 - Local (:::0)
30 verbose stack     at Object.exports._errnoException (util.js:870:11)
30 verbose stack     at exports._exceptionWithHostPort (util.js:893:20)
30 verbose stack     at connect (net.js:843:14)
30 verbose stack     at net.js:985:7
30 verbose stack     at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:63:16)
30 verbose stack     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:82:10)
31 verbose cwd /home/deep/watchman
32 error Linux 3.10.53-43_fbk14_02627_gb5c286c
33 error argv "/usr/local/fbcode/gcc-4.9-glibc-2.20-fb/bin/node-4.3.2" "/usr/local/bin/npm" "install" "-g" "nuclide"
34 error node v4.3.2
35 error npm  v3.5.3
36 error code ENETUNREACH
37 error errno ENETUNREACH
38 error syscall connect
39 error connect ENETUNREACH ::ffff:199.27.79.162:443 - Local (:::0)
40 error If you need help, you may report this error at:
40 error     <https://github.com/npm/npm/issues>
41 verbose exit [ 1, true ]


Console output:
[deep@dev2111.prn1 ~/watchman] npm install -g nuclide
npm ERR! Linux 3.10.53-43_fbk14_02627_gb5c286c
npm ERR! argv "/usr/local/fbcode/gcc-4.9-glibc-2.20-fb/bin/node-4.3.2" "/usr/local/bin/npm" "install" "-g" "nuclide"
npm ERR! node v4.3.2
npm ERR! npm  v3.5.3
npm ERR! code ENETUNREACH
npm ERR! errno ENETUNREACH
npm ERR! syscall connect

npm ERR! connect ENETUNREACH ::ffff:199.27.79.162:443 - Local (:::0)
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/deep/watchman/npm-debug.log
```

**Comment by pedzed** [comment]
> npm ERR! code ENETUNREACH
npm ERR! errno ENETUNREACH
npm ERR! syscall connect
> 
> npm ERR! connect ENETUNREACH ::ffff:199.27.79.162:443 - Local (:::0)

Looks like an error on your side... Is your network configured correctly? Can you install other packages?

**Comment by 123subhadeep** [comment]
Yes I am able to install other packages. I installed node and npm prior to this and they worked without any problem.

**Comment by pedzed** [comment]
> I installed node and npm

Besides these two?

I think that you have an issue with your IPv6 address. I believe only IPv4 is supported.

**Comment by 123subhadeep** [comment]
ohh I see. My devserver is IPv6 only.
