### ISSUE TITLE
TypeError: Cannot read property 'target' of null

### ISSUE THREAD

**Issue by steelbrain** [npm/npm#11903]
I've experienced this bug on both node `v5.7.0` and `v5.8.0`.

Here's the relevant stuff from `npm-debug.log`

```
33902 silly generateActionsToTake Starting
33903 silly install generateActionsToTake
33904 verbose stack TypeError: Cannot read property 'target' of null
33904 verbose stack     at module.exports (/Users/steel/n/lib/node_modules/npm/lib/install/filter-invalid-actions.js:24:35)
33904 verbose stack     at Array.<anonymous> (/Users/steel/n/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
33904 verbose stack     at LOOP (/Users/steel/n/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
33904 verbose stack     at /Users/steel/n/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
33904 verbose stack     at Object.Installer.computeLinked (/Users/steel/n/lib/node_modules/npm/lib/install.js:411:41)
33904 verbose stack     at Array.<anonymous> (/Users/steel/n/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
33904 verbose stack     at LOOP (/Users/steel/n/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
33904 verbose stack     at /Users/steel/n/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
33904 verbose stack     at module.exports (/Users/steel/n/lib/node_modules/npm/lib/install/diff-trees.js:50:3)
33904 verbose stack     at Array.<anonymous> (/Users/steel/n/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
33905 verbose cwd /Users/steel/n/lib/node_modules/motion-radium
33906 error Darwin 15.3.0
33907 error argv "/Users/steel/n/bin/node" "/Users/steel/n/bin/npm" "install"
```
Here's my full [npm-debug.log](https://github.com/npm/npm/files/173265/npm-debug.log.zip)

**Comment by steelbrain** [comment]
Also this is `package.json` specific bug, I've attached one that triggers it
[package.json](https://github.com/npm/npm/files/173363/package.json.zip)

**Comment by LPGhatguy** [comment]
Here's another `package.json` that's triggering this same issue:

```json
{
  "name": "guh",
  "version": "2.0.0-beta2",
  "description": "A full-stack project template and generator",
  "dependencies": {
    "express": "^4.13.3",
    "fs-extra": "^0.26.3",
    "source-map-support": "^0.4.0",
    "ws": "^1.0.1"
  },
  "bundledDependencies": ["app"],
  "devDependencies": {
    "autoprefixer": "^6.3.3",
    "browser-sync": "^2.10.1",
    "browserify": "^13.0.0",
    "cssnano": "^3.5.2",
    "gulp": "^3.9.0",
    "gulp-concat": "^2.6.0",
    "gulp-insert": "^0.5.0",
    "gulp-notify": "^2.2.0",
    "gulp-postcss": "^6.1.0",
    "gulp-rename": "^1.2.2",
    "gulp-sass": "^2.1.1",
    "gulp-sort": "^2.0.0",
    "gulp-sourcemaps": "^1.5.2",
    "gulp-typescript": "^2.10.0",
    "gulp-uglify": "^1.4.1",
    "gulp-util": "^3.0.6",
    "merge-stream": "^1.0.0",
    "postcss-reporter": "^1.3.1",
    "postcss-sassy-import": "^0.3.0",
    "postcss-scss": "^0.1.5",
    "stylelint": "^5.0.1",
    "tsify": "^0.14.1",
    "typescript": "~1.8.7",
    "vinyl-buffer": "^1.0.0",
    "vinyl-source-stream": "^1.1.0",
    "watchify": "^3.4.0"
  },
  "bin": {
    "guh": "bin/guh.js"
  },
  "engines": {
    "node": ">=5.0"
  },
  "scripts": {
    "start": "cd debug && nodemon main.js --watch node_modules/@server --watch node_modules/@common --watch main.js --ignore static"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/LPGhatguy/guh.git"
  },
  "author": "Lucien Greathouse <me@lpghatguy.com>",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/LPGhatguy/guh/issues"
  },
  "homepage": "https://github.com/LPGhatguy/guh#readme"
}
```

**Comment by LPGhatguy** [comment]
I should note that I can only reproduce this bug in npm >= 3.5.0, which makes this likely a duplicate of #10686

**Comment by steelbrain** [comment]
Closing in favor of https://github.com/npm/npm/issues/10686
