### ISSUE TITLE
can't install npm gulp and bower

### ISSUE THREAD

**Issue by jldelsocorro** [npm/npm#11904]
Hi team,

I currently installing gulp and bower for our project dependencies. 
Here is the Logs:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '--g',
1 verbose cli   'gulp' ]
2 info using npm@3.6.0
3 info using node@v5.7.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData gulp
8 silly fetchNamedPackageData gulp
9 silly mapToRegistry name gulp
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry http://registry.npmjs.org/
12 silly mapToRegistry uri http://registry.npmjs.org/gulp
13 verbose request uri http://registry.npmjs.org/gulp
14 verbose request no auth needed
15 info attempt registry request try #1 at 3:19:51 PM
16 verbose request id fa6141ed19b9930f
17 http request GET http://registry.npmjs.org/gulp
18 http 200 http://registry.npmjs.org/gulp
19 verbose bad json function FindProxyForURL(url, host) {
19 verbose bad json 			var privateIP = /^(0|10|127|192\.168|172\.1[6789]|172\.2[0-9]|172\.3[01]|169\.254|192\.88\.99)\.[0-9.]+$/;
19 verbose bad json 			var resolved_ip = dnsResolve(host);
19 verbose bad json
19 verbose bad json 			/* Don't send non-FQDN or private IP auths to us */
19 verbose bad json 			if (isPlainHostName(host) || isInNet(resolved_ip, "192.0.2.0","255.255.255.0") || privateIP.test(host))
19 verbose bad json 			return "DIRECT";
19 verbose bad json
19 verbose bad json 			/* FTP goes directly */
19 verbose bad json 			if (url.substring(0,4) == "ftp:")
19 verbose bad json 			return "DIRECT";
19 verbose bad json
19 verbose bad json 			/* Updates are directly accessible */
19 verbose bad json 			if (((localHostOrDomainIs(host, "trust.zscaler.com")) ||
19 verbose bad json 					(localHostOrDomainIs(host, "trust.zscaler.net")) ||
19 verbose bad json 					(localHostOrDomainIs(host, "trust.zscalerone.net")) ||
19 verbose bad json 					(localHostOrDomainIs(host, "trust.zscalertwo.net")) ||
19 verbose bad json 					(localHostOrDomainIs(host, "trust.zscloud.net")) ) &&
19 verbose bad json 				(url.substring(0,5) == "http:" || url.substring(0,6) == "https:"))
19 verbose bad json 			return "DIRECT";
19 verbose bad json
19 verbose bad json 			/* Default Traffic Forwarding. Forwarding to Zen on port 80, but you can use port 9400 also */
19 verbose bad json 			 return "PROXY  175.45.116.32:80; PROXY 165.225.98.32:80; DIRECT";
19 verbose bad json 		}
20 error registry error parsing json
21 verbose headers { 'content-type': 'application/x-ns-proxy-autoconfig',
21 verbose headers   connection: 'close' }
22 silly get cb [ 200,
22 silly get   { 'content-type': 'application/x-ns-proxy-autoconfig',
22 silly get     connection: 'close' } ]
23 silly fetchPackageMetaData SyntaxError: Unexpected token u
23 silly fetchPackageMetaData function FindProxyForURL(url, host) {
23 silly fetchPackageMetaData 			var privateIP = /^(0|10|127|192\.168|172\.1[6789]|172\.2[0-9]|172\.3[01]|169\.254|192\.88\.99)\.[0-9.]+$/;
23 silly fetchPackageMetaData 			var resolved_ip = dnsResolve(host);
23 silly fetchPackageMetaData
23 silly fetchPackageMetaData 			/* Don't send non-FQDN or private IP auths to us */
23 silly fetchPackageMetaData 			if (isPlainHostName(host) || isInNet(resolved_ip, "192.0.2.0","255.255.255.0") || privateIP.test(host))
23 silly fetchPackageMetaData 			return "DIRECT";
23 silly fetchPackageMetaData
23 silly fetchPackageMetaData 			/* FTP goes directly */
23 silly fetchPackageMetaData 			if (url.substring(0,4) == "ftp:")
23 silly fetchPackageMetaData 			return "DIRECT";
23 silly fetchPackageMetaData
23 silly fetchPackageMetaData 			/* Updates are directly accessible */
23 silly fetchPackageMetaData 			if (((localHostOrDomainIs(host, "trust.zscaler.com")) ||
23 silly fetchPackageMetaData 					(localHostOrDomainIs(host, "trust.zscaler.net")) ||
23 silly fetchPackageMetaData 					(localHostOrDomainIs(host, "trust.zscalerone.net")) ||
23 silly fetchPackageMetaData 					(localHostOrDomainIs(host, "trust.zscalertwo.net")) ||
23 silly fetchPackageMetaData 					(localHostOrDomainIs(host, "trust.zscloud.net")) ) &&
23 silly fetchPackageMetaData 				(url.substring(0,5) == "http:" || url.substring(0,6) == "https:"))
23 silly fetchPackageMetaData 			return "DIRECT";
23 silly fetchPackageMetaData
23 silly fetchPackageMetaData 			/* Default Traffic Forwarding. Forwarding to Zen on port 80, but you can use port 9400 also */
23 silly fetchPackageMetaData 			 return "PROXY  175.45.116.32:80; PROXY 165.225.98.32:80; DIRECT";
23 silly fetchPackageMetaData 		}
23 silly fetchPackageMetaData     at Object.parse (native)
23 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:199:23)
23 silly fetchPackageMetaData     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:172:14)
23 silly fetchPackageMetaData     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:198:22)
23 silly fetchPackageMetaData     at emitTwo (events.js:100:13)
23 silly fetchPackageMetaData     at Request.emit (events.js:185:7)
23 silly fetchPackageMetaData     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1035:10)
23 silly fetchPackageMetaData     at emitOne (events.js:95:20)
23 silly fetchPackageMetaData     at Request.emit (events.js:182:7)
23 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:962:12)
23 silly fetchPackageMetaData  error for gulp [SyntaxError: Unexpected token u
23 silly fetchPackageMetaData function FindProxyForURL(url, host) {
23 silly fetchPackageMetaData 			var privateIP = /^(0|10|127|192\.168|172\.1[6789]|172\.2[0-9]|172\.3[01]|169\.254|192\.88\.99)\.[0-9.]+$/;
23 silly fetchPackageMetaData 			var resolved_ip = dnsResolve(host);
23 silly fetchPackageMetaData
23 silly fetchPackageMetaData 			/* Don't send non-FQDN or private IP auths to us */
23 silly fetchPackageMetaData 			if (isPlainHostName(host) || isInNet(resolved_ip, "192.0.2.0","255.255.255.0") || privateIP.test(host))
23 silly fetchPackageMetaData 			return "DIRECT";
23 silly fetchPackageMetaData
23 silly fetchPackageMetaData 			/* FTP goes directly */
23 silly fetchPackageMetaData 			if (url.substring(0,4) == "ftp:")
23 silly fetchPackageMetaData 			return "DIRECT";
23 silly fetchPackageMetaData
23 silly fetchPackageMetaData 			/* Updates are directly accessible */
23 silly fetchPackageMetaData 			if (((localHostOrDomainIs(host, "trust.zscaler.com")) ||
23 silly fetchPackageMetaData 					(localHostOrDomainIs(host, "trust.zscaler.net")) ||
23 silly fetchPackageMetaData 					(localHostOrDomainIs(host, "trust.zscalerone.net")) ||
23 silly fetchPackageMetaData 					(localHostOrDomainIs(host, "trust.zscalertwo.net")) ||
23 silly fetchPackageMetaData 					(localHostOrDomainIs(host, "trust.zscloud.net")) ) &&
23 silly fetchPackageMetaData 				(url.substring(0,5) == "http:" || url.substring(0,6) == "https:"))
23 silly fetchPackageMetaData 			return "DIRECT";
23 silly fetchPackageMetaData
23 silly fetchPackageMetaData 			/* Default Traffic Forwarding. Forwarding to Zen on port 80, but you can use port 9400 also */
23 silly fetchPackageMetaData 			 return "PROXY  175.45.116.32:80; PROXY 165.225.98.32:80; DIRECT";
23 silly fetchPackageMetaData 		}]
24 silly rollbackFailedOptional Starting
25 silly rollbackFailedOptional Finishing
26 silly runTopLevelLifecycles Starting
27 silly runTopLevelLifecycles Finishing
28 silly install printInstalled
29 verbose stack SyntaxError: Unexpected token u
29 verbose stack function FindProxyForURL(url, host) {
29 verbose stack 			var privateIP = /^(0|10|127|192\.168|172\.1[6789]|172\.2[0-9]|172\.3[01]|169\.254|192\.88\.99)\.[0-9.]+$/;
29 verbose stack 			var resolved_ip = dnsResolve(host);
29 verbose stack
29 verbose stack 			/* Don't send non-FQDN or private IP auths to us */
29 verbose stack 			if (isPlainHostName(host) || isInNet(resolved_ip, "192.0.2.0","255.255.255.0") || privateIP.test(host))
29 verbose stack 			return "DIRECT";
29 verbose stack
29 verbose stack 			/* FTP goes directly */
29 verbose stack 			if (url.substring(0,4) == "ftp:")
29 verbose stack 			return "DIRECT";
29 verbose stack
29 verbose stack 			/* Updates are directly accessible */
29 verbose stack 			if (((localHostOrDomainIs(host, "trust.zscaler.com")) ||
29 verbose stack 					(localHostOrDomainIs(host, "trust.zscaler.net")) ||
29 verbose stack 					(localHostOrDomainIs(host, "trust.zscalerone.net")) ||
29 verbose stack 					(localHostOrDomainIs(host, "trust.zscalertwo.net")) ||
29 verbose stack 					(localHostOrDomainIs(host, "trust.zscloud.net")) ) &&
29 verbose stack 				(url.substring(0,5) == "http:" || url.substring(0,6) == "https:"))
29 verbose stack 			return "DIRECT";
29 verbose stack
29 verbose stack 			/* Default Traffic Forwarding. Forwarding to Zen on port 80, but you can use port 9400 also */
29 verbose stack 			 return "PROXY  175.45.116.32:80; PROXY 165.225.98.32:80; DIRECT";
29 verbose stack 		}
29 verbose stack     at Object.parse (native)
29 verbose stack     at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:199:23)
29 verbose stack     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:172:14)
29 verbose stack     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:198:22)
29 verbose stack     at emitTwo (events.js:100:13)
29 verbose stack     at Request.emit (events.js:185:7)
29 verbose stack     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1035:10)
29 verbose stack     at emitOne (events.js:95:20)
29 verbose stack     at Request.emit (events.js:182:7)
29 verbose stack     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:962:12)
30 verbose cwd C:\Users\admjldelsocorro
31 error Windows_NT 6.3.9600
32 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--g" "gulp"
33 error node v5.7.1
34 error npm  v3.6.0
35 error Unexpected token u
35 error function FindProxyForURL(url, host) {
35 error 			var privateIP = /^(0|10|127|192\.168|172\.1[6789]|172\.2[0-9]|172\.3[01]|169\.254|192\.88\.99)\.[0-9.]+$/;
35 error 			var resolved_ip = dnsResolve(host);
35 error
35 error 			/* Don't send non-FQDN or private IP auths to us */
35 error 			if (isPlainHostName(host) || isInNet(resolved_ip, "192.0.2.0","255.255.255.0") || privateIP.test(host))
35 error 			return "DIRECT";
35 error
35 error 			/* FTP goes directly */
35 error 			if (url.substring(0,4) == "ftp:")
35 error 			return "DIRECT";
35 error
35 error 			/* Updates are directly accessible */
35 error 			if (((localHostOrDomainIs(host, "trust.zscaler.com")) ||
35 error 					(localHostOrDomainIs(host, "trust.zscaler.net")) ||
35 error 					(localHostOrDomainIs(host, "trust.zscalerone.net")) ||
35 error 					(localHostOrDomainIs(host, "trust.zscalertwo.net")) ||
35 error 					(localHostOrDomainIs(host, "trust.zscloud.net")) ) &&
35 error 				(url.substring(0,5) == "http:" || url.substring(0,6) == "https:"))
35 error 			return "DIRECT";
35 error
35 error 			/* Default Traffic Forwarding. Forwarding to Zen on port 80, but you can use port 9400 also */
35 error 			 return "PROXY  175.45.116.32:80; PROXY 165.225.98.32:80; DIRECT";
35 error 		}
36 error If you need help, you may report this error at:
36 error     <https://github.com/npm/npm/issues>
37 verbose exit [ 1, true ]

```

**Comment by zkat** [comment]
Hi! This looks like a proxy configuration error: Please [make npm is properly configured to use your proxy](http://jjasonclark.com/how-to-setup-node-behind-web-proxy/) and try again. Since this is almost certainly the issue at hand, I'm closing this issue, but feel free to ask for it to be reopened if you have further problems. :)

**Comment by jldelsocorro** [comment]
Hi @zkat ,

Thanks for the reply, I was able to installed the gulp :) but after downloading and installing the latest node.js I am having error that no agent is  compatible, Unmet requirements :node.js.npm exist.

Take note that I already restart thr service and the server. Reboot the machine but still no luck. 
I've read some previous post about this but still no luck. Please help.

**Comment by zkat** [comment]
Could you post the `npm-debug.log` for this new error?

**Comment by jldelsocorro** [comment]
Hi @zkat , 

The agent is working now, hopefully it will not happen again. Thanks.
