### ISSUE TITLE
Maximum call stack size exceeded while installing ember-cli

### ISSUE THREAD

**Issue by ranjeetBindal** [npm/npm#11918]
I have windows 7 and vagrant is installed but not running.
installed node and npm as below:
node -v
v5.8.0
npm -v
3.7.3
when i am trying to run "npm install -g ember-cli" getting error as below 

```
28561 silly doSerial finalize 1
28562 silly finalize C:\Users\rankumar\AppData\Roaming\npm\node_modules\ember-cli
28563 verbose stack RangeError: Maximum call stack size exceeded
28563 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install\actions.js:55:37
28563 verbose stack     at Array.forEach (native)
28563 verbose stack     at markAsFailed (C:\Program Files\nodejs\node_modules\npm\lib\install\actions.js:54:16)
28563 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install\actions.js:57:7
28563 verbose stack     at Array.forEach (native)
28563 verbose stack     at markAsFailed (C:\Program Files\nodejs\node_modules\npm\lib\install\actions.js:54:16)
28563 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install\actions.js:57:7
28563 verbose stack     at Array.forEach (native)
28563 verbose stack     at markAsFailed (C:\Program Files\nodejs\node_modules\npm\lib\install\actions.js:54:16)
28563 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install\actions.js:57:7
```

**Comment by zkat** [comment]
Heya. We're using #11702 to track and fix ongoing issues with stack blowups. As such, I'm gonna close this as a duplicate -- unfortunately these tend to be somewhat hard to reproduce on our systems, but you're more than welcome to move comments and information to that other issue!
