### ISSUE TITLE
error 404 with Node.js 

### ISSUE THREAD

**Issue by brainstormECP** [npm/npm#11910]
Hi,
I'm using node behind a proxy, and i am using windows.
this is my configuration:

```
proxy=http://domain/user:password@proxy:port/
https-proxy=http://domain/user:password@proxy:port/
registry=http://registry.npmjs.org/
```

when i am trying to install bower or other package ( npm install -g bower ) i get a 404 error, please help.

 this is the error log:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'bower' ]
2 info using npm@3.3.12
3 info using node@v5.5.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData bower
8 silly fetchNamedPackageData bower
9 silly mapToRegistry name bower
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry http://registry.npmjs.org/
12 silly mapToRegistry uri http://registry.npmjs.org/bower
13 verbose request uri http://registry.npmjs.org/bower
14 verbose request no auth needed
15 info attempt registry request try #1 at 07:17:12
16 verbose request id fc58834f4d665229
17 http request GET http://registry.npmjs.org/bower
18 http 404 http://registry.npmjs.org/bower
19 verbose bad json <HTML><BODY><H1>404 Not Found</H1></BODY></HTML>
20 error registry error parsing json
21 verbose headers { date: 'Tue, 15 Mar 2016 11:17:12 GMT',
21 verbose headers   connection: 'close',
21 verbose headers   'content-type': 'text/html',
21 verbose headers   'content-length': '48' }
22 silly get cb [ 404,
22 silly get   { date: 'Tue, 15 Mar 2016 11:17:12 GMT',
22 silly get     connection: 'close',
22 silly get     'content-type': 'text/html',
22 silly get     'content-length': '48' } ]
23 silly fetchPackageMetaData SyntaxError: Unexpected token <
23 silly fetchPackageMetaData <HTML><BODY><H1>404 Not Found</H1></BODY></HTML>
23 silly fetchPackageMetaData     at Object.parse (native)
23 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:199:23)
23 silly fetchPackageMetaData     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:172:14)
23 silly fetchPackageMetaData     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:198:22)
23 silly fetchPackageMetaData     at emitTwo (events.js:100:13)
23 silly fetchPackageMetaData     at Request.emit (events.js:185:7)
23 silly fetchPackageMetaData     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1082:10)
23 silly fetchPackageMetaData     at emitOne (events.js:95:20)
23 silly fetchPackageMetaData     at Request.emit (events.js:182:7)
23 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1009:12)
23 silly fetchPackageMetaData  error for bower [SyntaxError: Unexpected token <
23 silly fetchPackageMetaData <HTML><BODY><H1>404 Not Found</H1></BODY></HTML>]
24 silly rollbackFailedOptional Starting
25 silly rollbackFailedOptional Finishing
26 silly runTopLevelLifecycles Starting
27 silly runTopLevelLifecycles Finishing
28 silly install printInstalled
29 verbose stack SyntaxError: Unexpected token <
29 verbose stack <HTML><BODY><H1>404 Not Found</H1></BODY></HTML>
29 verbose stack     at Object.parse (native)
29 verbose stack     at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:199:23)
29 verbose stack     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:172:14)
29 verbose stack     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:198:22)
29 verbose stack     at emitTwo (events.js:100:13)
29 verbose stack     at Request.emit (events.js:185:7)
29 verbose stack     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1082:10)
29 verbose stack     at emitOne (events.js:95:20)
29 verbose stack     at Request.emit (events.js:182:7)
29 verbose stack     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1009:12)
30 verbose cwd D:\
31 error Windows_NT 6.3.9600
32 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "bower"
33 error node v5.5.0
34 error npm  v3.3.12
35 error Unexpected token <
35 error <HTML><BODY><H1>404 Not Found</H1></BODY></HTML>
36 error If you need help, you may report this error at:
36 error     <https://github.com/npm/npm/issues>
37 verbose exit [ 1, true ]
```

**Comment by zkat** [comment]
You'll need to double-check your proxy settings. They should look something like:

```
proxy=http://user:password@proxy.domain:port
https-proxy=http://user:password@proxy.domain:port
```

which is slightly different from your edited version.

**Comment by brainstormECP** [comment]
I have change my proxy config using your sugestion and still the same.
Please help


2016-03-15 19:12 GMT-04:00, Kat Marchán <notifications@github.com>:
