### ISSUE TITLE
"devDependencies" overrides "dependencies" on initial "npm install" but fixes situation on second "npm install"

### ISSUE THREAD

**Issue by rse** [npm/npm#11921]
We've stumbled over a very strange behavior, which I think is a subtle bug in NPM (we tried various versions up to the latest NPM 3.8.2).

First, as an abstracted description:

In "dependencies" of an app A there is a module B which has a "dependencies" to a particular version of module "C". Additionally, in "devDependencies" of the same app A there is different particular version of module "C". Then on "npm install" for A, npm installs node_modules/B and node_modules/C but leaves out the (expected) node_modules/B/node_modules/C (because it is a different version). On a second "npm install" for A, NPM detects the "unmet situation" correctly and installs the missing node_modules/B/node_modules/C.

Second, to easily repeat this for yourself with particular modules:

```
$ cat package.json
{
    "name": "dummy",
    "version": "0.0.0",
    "dependencies": {
        "delivery-packer": "0.1.3"
    },
    "devDependencies": {
        "glob": "7.0.3"
    }
}
$ ls -l
total 2
-rw-r--r--  1 rse  wheel  168 Mar 16 14:05 package.json
$ node --version; npm --version
v5.8.0
3.8.2
$ npm install
dummy@0.0.0 /tmp/test
+-- delivery-packer@0.1.3 
| +-- buildify@0.4.0 
| | +-- clean-css@0.6.0 
| | | `-- optimist@0.3.7 
| | |   `-- wordwrap@0.0.3 
| | +-- mkdirp@0.3.2 
| | +-- uglify-js@1.3.4 
| | `-- underscore@1.3.3 
| +-- colors@1.1.2 
| +-- dashdash@1.13.0 
| | `-- assert-plus@1.0.0 
| +-- fs-extra@0.26.5 
| | +-- graceful-fs@4.1.3 
| | +-- jsonfile@2.2.3 
| | +-- klaw@1.1.3 
| | `-- rimraf@2.5.2 
| +-- js-yaml@3.5.3 
| | +-- argparse@1.0.6 
| | | `-- sprintf-js@1.0.3 
| | `-- esprima@2.7.2 
| +-- lodash@4.5.1 
| `-- package@1.0.1 
+-- glob@7.0.3 
| +-- inflight@1.0.4 
| | `-- wrappy@1.0.1 
| +-- inherits@2.0.1 
| +-- minimatch@3.0.0 
| | `-- brace-expansion@1.1.3 
| |   +-- balanced-match@0.3.0 
| |   `-- concat-map@0.0.1 
| +-- once@1.3.3 
| `-- path-is-absolute@1.0.0 
`-- UNMET PEER DEPENDENCY grunt@>=0.4.0

npm WARN delivery-packer@0.1.3 requires a peer of grunt@>=0.4.0 but none was installed.
npm WARN dummy@0.0.0 No description
npm WARN dummy@0.0.0 No repository field.
npm WARN dummy@0.0.0 No license field.
$ npm list
dummy@0.0.0 /tmp/test
+-- delivery-packer@0.1.3
| +-- buildify@0.4.0
| | +-- clean-css@0.6.0
| | | `-- optimist@0.3.7
| | |   `-- wordwrap@0.0.3
| | +-- mkdirp@0.3.2
| | +-- uglify-js@1.3.4
| | `-- underscore@1.3.3
| +-- colors@1.1.2
| +-- dashdash@1.13.0
| | `-- assert-plus@1.0.0
| +-- fs-extra@0.26.5
| | +-- graceful-fs@4.1.3
| | +-- jsonfile@2.2.3
| | +-- klaw@1.1.3
| | `-- rimraf@2.5.2
| +-- UNMET DEPENDENCY glob@7.0.0       <===================================== HERE DETECTED
| +-- js-yaml@3.5.3
| | +-- argparse@1.0.6
| | | `-- sprintf-js@1.0.3
| | `-- esprima@2.7.2
| +-- lodash@4.5.1
| `-- package@1.0.1
+-- glob@7.0.3
| +-- inflight@1.0.4
| | `-- wrappy@1.0.1
| +-- inherits@2.0.1
| +-- minimatch@3.0.0
| | `-- brace-expansion@1.1.3
| |   +-- balanced-match@0.3.0
| |   `-- concat-map@0.0.1
| +-- once@1.3.3
| `-- path-is-absolute@1.0.0
`-- UNMET PEER DEPENDENCY grunt@>=0.4.0

npm ERR! peer dep missing: grunt@>=0.4.0, required by delivery-packer@0.1.3
npm ERR! missing: glob@7.0.0, required by delivery-packer@0.1.3
$ npm install
dummy@0.0.0 /tmp/test
+-- delivery-packer@0.1.3
| `-- glob@7.0.0                                <================= NOW FIXED
`-- UNMET PEER DEPENDENCY grunt@>=0.4.0

npm WARN delivery-packer@0.1.3 requires a peer of grunt@>=0.4.0 but none was installed.
npm WARN dummy@0.0.0 No description
npm WARN dummy@0.0.0 No repository field.
npm WARN dummy@0.0.0 No license field.
$ npm list
dummy@0.0.0 /tmp/test
+-- delivery-packer@0.1.3
| +-- buildify@0.4.0
| | +-- clean-css@0.6.0
| | | `-- optimist@0.3.7
| | |   `-- wordwrap@0.0.3
| | +-- mkdirp@0.3.2
| | +-- uglify-js@1.3.4
| | `-- underscore@1.3.3
| +-- colors@1.1.2
| +-- dashdash@1.13.0
| | `-- assert-plus@1.0.0
| +-- fs-extra@0.26.5
| | +-- graceful-fs@4.1.3
| | +-- jsonfile@2.2.3
| | +-- klaw@1.1.3
| | `-- rimraf@2.5.2
| +-- glob@7.0.0                                <=============== NOW EXISTING
| +-- js-yaml@3.5.3
| | +-- argparse@1.0.6
| | | `-- sprintf-js@1.0.3
| | `-- esprima@2.7.2
| +-- lodash@4.5.1
| `-- package@1.0.1
+-- glob@7.0.3
| +-- inflight@1.0.4
| | `-- wrappy@1.0.1
| +-- inherits@2.0.1
| +-- minimatch@3.0.0
| | `-- brace-expansion@1.1.3
| |   +-- balanced-match@0.3.0
| |   `-- concat-map@0.0.1
| +-- once@1.3.3
| `-- path-is-absolute@1.0.0
`-- UNMET PEER DEPENDENCY grunt@>=0.4.0

npm ERR! peer dep missing: grunt@>=0
```

Interesting is that is really just this combination of "dependencies" and "devDependencies". If one uses just "dependencies" or just "devDependencies" in A everything works just fine. But once the module C exists in "devDependencies" of A this seems to override the "dependencies" in B to C on initial "npm install".

So, I miss something. Is this really intended? I don't think it is. Can you check this, please? 
Thanks for your support and keep up the good work on NPM.

**Comment by ownagedj** [comment]
confirmed also in `npm` `3.7.3` node `v5.9.0`

**Comment by rse** [comment]
I've now tested the latest and greatest NPM 3.8.3 under Node 5.9.0, too. The problem still exists there.

**Comment by zkat** [comment]
Thanks for the careful and thorough report! This looks like an installer issue for sure. I'm gonna cc @iarna, who knows that bit way more intimately than I do, and mark this as a bug. :tada: :bug:

**Comment by baslr** [comment]
also #10727

```
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
npm WARN karma-sinon-chai@1.2.0 requires a peer of lolex@^1.4.0 but none was installed.
npm WARN karma-sinon-chai@1.2.0 requires a peer of sinon-chai@^2.8.0 but none was installed.
npm WARN karma-nyan-reporter@0.2.2 requires a peer of karma@>=0.9 but none was installed.
npm WARN bootstrap-loader@1.0.10 requires a peer of resolve-url-loader@* but none was installed.
npm WARN bootstrap-loader@1.0.10 requires a peer of sass-loader@* but none was installed.
npm WARN bootstrap-loader@1.0.10 requires a peer of url-loader@* but none was installed.
$ echo $?
0
$ node
> require('resolve-url-loader')
Error: Cannot find module 'resolve-url-loader'
   at Function.Module._resolveFilename (module.js:325:15)
   at Function.Module._load (module.js:276:25)
   at Module.require (module.js:353:17)
   at require (internal/module.js:12:17)
   at repl:1:1
   at REPLServer.defaultEval (repl.js:262:27)
   at bound (domain.js:287:14)
   at REPLServer.runBound [as eval] (domain.js:300:12)
   at REPLServer.<anonymous> (repl.js:431:12)
   at emitOne (events.js:82:20)
```
after several `npm install`
