### ISSUE TITLE
error shasum check failed for /var/folders/l4/dnp8wg311zs7s_8x8ltc3pfc0000gn/T/npm-1468-2d6e136b/registry.npmjs.org/ionic/-/ionic-1.7.14.tgz

### ISSUE THREAD

**Issue by marcelsantana** [npm/npm#11922]
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'ionic',
1 verbose cli   'cordova' ]
2 info using npm@3.7.3
3 info using node@v5.8.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData ionic
8 silly fetchPackageMetaData cordova
9 silly fetchNamedPackageData ionic
10 silly mapToRegistry name ionic
11 silly mapToRegistry using default registry
12 silly mapToRegistry registry https://registry.npmjs.org/
13 silly mapToRegistry uri https://registry.npmjs.org/ionic
14 silly fetchNamedPackageData cordova
15 silly mapToRegistry name cordova
16 silly mapToRegistry using default registry
17 silly mapToRegistry registry https://registry.npmjs.org/
18 silly mapToRegistry uri https://registry.npmjs.org/cordova
19 verbose request uri https://registry.npmjs.org/ionic
20 verbose request no auth needed
21 info attempt registry request try #1 at 22:03:18
22 verbose request id e177061ae8006d0a
23 http request GET https://registry.npmjs.org/ionic
24 verbose request uri https://registry.npmjs.org/cordova
25 verbose request no auth needed
26 info attempt registry request try #1 at 22:03:18
27 http request GET https://registry.npmjs.org/cordova
28 http 200 https://registry.npmjs.org/cordova
29 verbose headers { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
29 verbose headers   etag: '"1FQXV3T2J7F6UIFZDELAUF06U"',
29 verbose headers   'content-type': 'application/json',
29 verbose headers   'cache-control': 'max-age=300',
29 verbose headers   'content-length': '376627',
29 verbose headers   'accept-ranges': 'bytes',
29 verbose headers   date: 'Wed, 16 Mar 2016 01:03:19 GMT',
29 verbose headers   via: '1.1 varnish',
29 verbose headers   age: '2',
29 verbose headers   connection: 'keep-alive',
29 verbose headers   'x-served-by': 'cache-iad2139-IAD',
29 verbose headers   'x-cache': 'HIT',
29 verbose headers   'x-cache-hits': '1',
29 verbose headers   'x-timer': 'S1458090199.412080,VS0,VE2',
29 verbose headers   vary: 'Accept' }
30 silly get cb [ 200,
30 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
30 silly get     etag: '"1FQXV3T2J7F6UIFZDELAUF06U"',
30 silly get     'content-type': 'application/json',
30 silly get     'cache-control': 'max-age=300',
30 silly get     'content-length': '376627',
30 silly get     'accept-ranges': 'bytes',
30 silly get     date: 'Wed, 16 Mar 2016 01:03:19 GMT',
30 silly get     via: '1.1 varnish',
30 silly get     age: '2',
30 silly get     connection: 'keep-alive',
30 silly get     'x-served-by': 'cache-iad2139-IAD',
30 silly get     'x-cache': 'HIT',
30 silly get     'x-cache-hits': '1',
30 silly get     'x-timer': 'S1458090199.412080,VS0,VE2',
30 silly get     vary: 'Accept' } ]
31 verbose get saving cordova to /Users/MarcelSantana/.npm/registry.npmjs.org/cordova/.cache.json
32 verbose correctMkdir /Users/MarcelSantana/.npm correctMkdir not in flight; initializing
33 verbose makeDirectory /Users/MarcelSantana/.npm creation not in flight; initializing
34 silly makeDirectory /Users/MarcelSantana/.npm uid: 501 gid: 20
35 http 200 https://registry.npmjs.org/ionic
36 verbose headers { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
36 verbose headers   etag: '"26JJ3KCXPWOZGKMV9OVAQ30G4"',
36 verbose headers   'content-type': 'application/json',
36 verbose headers   'cache-control': 'max-age=300',
36 verbose headers   'content-length': '673747',
36 verbose headers   'accept-ranges': 'bytes',
36 verbose headers   date: 'Wed, 16 Mar 2016 01:03:19 GMT',
36 verbose headers   via: '1.1 varnish',
36 verbose headers   age: '0',
36 verbose headers   connection: 'keep-alive',
36 verbose headers   'x-served-by': 'cache-iad2130-IAD',
36 verbose headers   'x-cache': 'HIT',
36 verbose headers   'x-cache-hits': '1',
36 verbose headers   'x-timer': 'S1458090199.411278,VS0,VE24',
36 verbose headers   vary: 'Accept' }
37 silly get cb [ 200,
37 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
37 silly get     etag: '"26JJ3KCXPWOZGKMV9OVAQ30G4"',
37 silly get     'content-type': 'application/json',
37 silly get     'cache-control': 'max-age=300',
37 silly get     'content-length': '673747',
37 silly get     'accept-ranges': 'bytes',
37 silly get     date: 'Wed, 16 Mar 2016 01:03:19 GMT',
37 silly get     via: '1.1 varnish',
37 silly get     age: '0',
37 silly get     connection: 'keep-alive',
37 silly get     'x-served-by': 'cache-iad2130-IAD',
37 silly get     'x-cache': 'HIT',
37 silly get     'x-cache-hits': '1',
37 silly get     'x-timer': 'S1458090199.411278,VS0,VE24',
37 silly get     vary: 'Accept' } ]
38 verbose get saving ionic to /Users/MarcelSantana/.npm/registry.npmjs.org/ionic/.cache.json
39 verbose correctMkdir /Users/MarcelSantana/.npm correctMkdir not in flight; initializing
40 silly install normalizeTree
41 silly loadCurrentTree Finishing
42 silly loadIdealTree Starting
43 silly install loadIdealTree
44 silly cloneCurrentTree Starting
45 silly install cloneCurrentTreeToIdealTree
46 silly cloneCurrentTree Finishing
47 silly loadShrinkwrap Starting
48 silly install loadShrinkwrap
49 silly loadShrinkwrap Finishing
50 silly loadAllDepsIntoIdealTree Starting
51 silly install loadAllDepsIntoIdealTree
52 silly resolveWithNewModule cordova@6.0.0 checking installable status
53 silly cache add args [ 'cordova', null ]
54 verbose cache add spec cordova
55 silly resolveWithNewModule ionic@1.7.14 checking installable status
56 silly cache add args [ 'ionic', null ]
57 verbose cache add spec ionic
58 silly cache add parsed spec Result {
58 silly cache add   raw: 'cordova',
58 silly cache add   scope: null,
58 silly cache add   name: 'cordova',
58 silly cache add   rawSpec: '',
58 silly cache add   spec: 'latest',
58 silly cache add   type: 'tag' }
59 silly addNamed cordova@latest
60 verbose addNamed "latest" is being treated as a dist-tag for cordova
61 info addNameTag [ 'cordova', 'latest' ]
62 silly mapToRegistry name cordova
63 silly mapToRegistry using default registry
64 silly mapToRegistry registry https://registry.npmjs.org/
65 silly mapToRegistry uri https://registry.npmjs.org/cordova
66 verbose addNameTag registry:https://registry.npmjs.org/cordova not in flight; fetching
67 silly cache add parsed spec Result {
67 silly cache add   raw: 'ionic',
67 silly cache add   scope: null,
67 silly cache add   name: 'ionic',
67 silly cache add   rawSpec: '',
67 silly cache add   spec: 'latest',
67 silly cache add   type: 'tag' }
68 silly addNamed ionic@latest
69 verbose addNamed "latest" is being treated as a dist-tag for ionic
70 info addNameTag [ 'ionic', 'latest' ]
71 silly mapToRegistry name ionic
72 silly mapToRegistry using default registry
73 silly mapToRegistry registry https://registry.npmjs.org/
74 silly mapToRegistry uri https://registry.npmjs.org/ionic
75 verbose addNameTag registry:https://registry.npmjs.org/ionic not in flight; fetching
76 verbose get https://registry.npmjs.org/cordova not expired, no request
77 silly addNameTag next cb for cordova with tag latest
78 silly addNamed cordova@6.0.0
79 verbose addNamed "6.0.0" is a plain semver version for cordova
80 silly mapToRegistry name cordova
81 silly mapToRegistry using default registry
82 silly mapToRegistry registry https://registry.npmjs.org/
83 silly mapToRegistry uri https://registry.npmjs.org/cordova
84 verbose addRemoteTarball https://registry.npmjs.org/cordova/-/cordova-6.0.0.tgz not in flight; adding
85 verbose addRemoteTarball [ 'https://registry.npmjs.org/cordova/-/cordova-6.0.0.tgz',
85 verbose addRemoteTarball   '2c1e75a9c0dd6cee8381d5608870087ab44f3e68' ]
86 verbose get https://registry.npmjs.org/ionic not expired, no request
87 silly addNameTag next cb for ionic with tag latest
88 silly addNamed ionic@1.7.14
89 verbose addNamed "1.7.14" is a plain semver version for ionic
90 silly mapToRegistry name ionic
91 silly mapToRegistry using default registry
92 silly mapToRegistry registry https://registry.npmjs.org/
93 silly mapToRegistry uri https://registry.npmjs.org/ionic
94 verbose addRemoteTarball https://registry.npmjs.org/ionic/-/ionic-1.7.14.tgz not in flight; adding
95 verbose addRemoteTarball [ 'https://registry.npmjs.org/ionic/-/ionic-1.7.14.tgz',
95 verbose addRemoteTarball   'af493d5df4688d917d778b0934d1739b9be6efe6' ]
96 info retry fetch attempt 1 at 22:03:30
97 info attempt registry request try #1 at 22:03:30
98 http fetch GET https://registry.npmjs.org/ionic/-/ionic-1.7.14.tgz
99 info retry fetch attempt 1 at 22:03:30
100 info attempt registry request try #1 at 22:03:30
101 http fetch GET https://registry.npmjs.org/cordova/-/cordova-6.0.0.tgz
102 http fetch 200 https://registry.npmjs.org/ionic/-/ionic-1.7.14.tgz
103 http fetch 200 https://registry.npmjs.org/cordova/-/cordova-6.0.0.tgz
104 silly fetchAndShaCheck shasum 2c1e75a9c0dd6cee8381d5608870087ab44f3e68
105 verbose addTmpTarball /var/folders/l4/dnp8wg311zs7s_8x8ltc3pfc0000gn/T/npm-1468-2d6e136b/registry.npmjs.org/cordova/-/cordova-6.0.0.tgz not in flight; adding
106 verbose addTmpTarball already have metadata; skipping unpack for cordova@6.0.0
107 verbose correctMkdir /Users/MarcelSantana/.npm correctMkdir not in flight; initializing
108 silly cache afterAdd cordova@6.0.0
109 verbose afterAdd /Users/MarcelSantana/.npm/cordova/6.0.0/package/package.json not in flight; writing
110 verbose correctMkdir /Users/MarcelSantana/.npm correctMkdir not in flight; initializing
111 verbose afterAdd /Users/MarcelSantana/.npm/cordova/6.0.0/package/package.json written
112 info retry will retry, error on last attempt: Error: read ETIMEDOUT
113 info retry will retry, error on last attempt: Error: read ETIMEDOUT
114 silly fetchAndShaCheck shasum af493d5df4688d917d778b0934d1739b9be6efe6
115 silly rollbackFailedOptional Starting
116 silly rollbackFailedOptional Finishing
117 silly runTopLevelLifecycles Starting
118 silly runTopLevelLifecycles Finishing
119 silly install printInstalled
120 verbose stack Error: shasum check failed for /var/folders/l4/dnp8wg311zs7s_8x8ltc3pfc0000gn/T/npm-1468-2d6e136b/registry.npmjs.org/ionic/-/ionic-1.7.14.tgz
120 verbose stack Expected: af493d5df4688d917d778b0934d1739b9be6efe6
120 verbose stack Actual:   caba09a5e33170d37ba2e4e209fd55809fe716a2
120 verbose stack From:     https://registry.npmjs.org/ionic/-/ionic-1.7.14.tgz
120 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/sha/index.js:25:8
120 verbose stack     at ReadStream.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/sha/index.js:72:7)
120 verbose stack     at emitNone (events.js:85:20)
120 verbose stack     at ReadStream.emit (events.js:179:7)
120 verbose stack     at endReadableNT (_stream_readable.js:913:12)
120 verbose stack     at _combinedTickCallback (node.js:377:13)
120 verbose stack     at process._tickCallback (node.js:401:11)
121 verbose cwd /Users/MarcelSantana
122 error Darwin 15.3.0
123 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "ionic" "cordova"
124 error node v5.8.0
125 error npm  v3.7.3
126 error shasum check failed for /var/folders/l4/dnp8wg311zs7s_8x8ltc3pfc0000gn/T/npm-1468-2d6e136b/registry.npmjs.org/ionic/-/ionic-1.7.14.tgz
126 error Expected: af493d5df4688d917d778b0934d1739b9be6efe6
126 error Actual:   caba09a5e33170d37ba2e4e209fd55809fe716a2
126 error From:     https://registry.npmjs.org/ionic/-/ionic-1.7.14.tgz
127 error If you need help, you may report this error at:
127 error     <https://github.com/npm/npm/issues>
128 verbose exit [ 1, true ]
 ```

**Comment by zkat** [comment]
It looks like something went awry with your shasum check for `ionic`.

Could you try `npm cache clean` and re-running the command?

**Comment by marcelsantana** [comment]
Thank you zkat, my problem was permition, after running it, i run npm chace clean and re-running the command.

**Comment by zkat** [comment]
So it's fixed? Closing then! Feel free to ping again if you need more help. :)
