### ISSUE TITLE
Getting this message when using npm run start 

### ISSUE THREAD

**Issue by Parveenkmr44** [npm/npm#11988]
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start' ]
2 info using npm@2.14.20
3 info using node@v4.4.0
4 verbose stack Error: missing script: start
4 verbose stack     at run (C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:142:19)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:58:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:345:5
4 verbose stack     at checkBinReferences_ (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:309:45)
4 verbose stack     at final (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:343:3)
4 verbose stack     at then (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:113:5)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:232:12
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
5 verbose cwd C:\xampp\htdocs\OKH_FB_VV_Mobile\branches\2.2.0\mobile
6 error Windows_NT 6.1.7601
7 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
8 error node v4.4.0
9 error npm  v2.14.20
10 error missing script: start
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
```

Please help

**Comment by KenanY** [comment]
Hello @Parveenkmr44!

```
4 verbose stack Error: missing script: start
```

Do you have a `"start"` script defined in your `package.json`?

**Comment by othiym23** [comment]
@KenanY has the solution here – npm relies on there being a `"start"` script in the [`"scripts"` section](https://docs.npmjs.com/misc/scripts) of the `package.json` in the working directory from which npm is run. As such, I'm going to close this issue as resolved. Thanks for your time!
