### ISSUE TITLE
Installation of Bower by npm fails when trying to 'make' GNU MediaGoblin

### ISSUE THREAD

**Issue by juboxi** [npm/npm#11980]
Hi. I'm trying to install GNU MediaGoblin by following these instructions:
http://mediagoblin.readthedocs.org/en/stable/siteadmin/deploying.html

Commands run and the resulting error code exit traced: 
----
mediagoblin@Debian7:/var/www/gmg/mediagoblin$ ./bootstrap.sh && ./configure && make   
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force 
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
autoreconf: configure.ac: not using Autoheader
autoreconf: configure.ac: not using Automake
autoreconf: Leaving directory `.'
checking for python2.7... python2.7
checking for virtualenv... virtualenv
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for a BSD-compatible install... /usr/bin/install -c
configure: creating ./config.status
config.status: creating Makefile
./devtools/update_extlib.sh
Bower not found, installing via npm!
npm http GET https://registry.npmjs.org/bower

npm ERR! Error: failed to fetch from registry: bower
npm ERR!     at /usr/local/lib/node_modules/npm/lib/utils/npm-registry-client/get.js:139:12
npm ERR!     at cb (/usr/local/lib/node_modules/npm/lib/utils/npm-registry-client/request.js:32:9)
npm ERR!     at Request._callback (/usr/local/lib/node_modules/npm/lib/utils/npm-registry-client/request.js:137:18)
npm ERR!     at Request.callback (/usr/local/lib/node_modules/npm/node_modules/request/main.js:109:22)
npm ERR!     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/main.js:198:58)
npm ERR!     at Request.emit (events.js:88:20)
npm ERR!     at ClientRequest.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/main.js:356:14)
npm ERR!     at ClientRequest.emit (events.js:67:17)
npm ERR!     at HTTPParser.onIncoming (http.js:1238:11)
npm ERR!     at HTTPParser.onHeadersComplete (http.js:102:31)
npm ERR! You may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>
npm ERR! 
npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "node" "/usr/local/bin/npm" "install" "bower"
npm ERR! cwd /var/www/gmg/mediagoblin
npm ERR! node -v v0.6.8
npm ERR! npm -v 1.1.0-2
npm ERR! message failed to fetch from registry: bower
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /var/www/gmg/mediagoblin/npm-debug.log
npm not ok
Makefile:102: recipe for target 'extlib' failed
make: *** [extlib] Error 1
mediagoblin@Debian7:/var/www/gmg/mediagoblin$

**Comment by juboxi** [comment]
My bad. Was old unmaintained version of node causing the Node.js Package Management to fail at seemingly trivial task. downloaded and extracted an up-to-date version.
