### ISSUE TITLE
Not Able To install Phonegap through CLI  in mac machine

### ISSUE THREAD

**Issue by aksinsane** [npm/npm#11991]
Kindly help me to get through this error.

```
npm ERR! Darwin 14.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "phonegap@latest"
npm ERR! node v4.4.0
npm ERR! npm  v2.14.20

npm ERR! error:0906D06C:PEM routines:PEM_read_bio:no start line
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/rahul/npm-debug.log
dheerajs-imac:~ rahul$ 


debug.log file

 0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'phonegap@latest' ]
2 info using npm@2.14.20
3 info using node@v4.4.0
4 verbose install initial load of /usr/local/lib/package.json
5 verbose readDependencies loading dependencies from /usr/local/lib/package.json
6 silly cache add args [ 'phonegap@latest', null ]
7 verbose cache add spec phonegap@latest
8 silly cache add parsed spec Result {
8 silly cache add   raw: 'phonegap@latest',
8 silly cache add   scope: null,
8 silly cache add   name: 'phonegap',
8 silly cache add   rawSpec: 'latest',
8 silly cache add   spec: 'latest',
8 silly cache add   type: 'tag' }
9 silly addNamed phonegap@latest
10 verbose addNamed "latest" is being treated as a dist-tag for phonegap
11 info addNameTag [ 'phonegap', 'latest' ]
12 silly mapToRegistry name phonegap
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/phonegap
16 verbose addNameTag registry:https://registry.npmjs.org/phonegap not in flight; fetching
17 verbose request uri https://registry.npmjs.org/phonegap
18 verbose request no auth needed
19 info attempt registry request try #1 at 4:12:20 PM
20 verbose request id f02c9f26865779c8
21 http request GET https://registry.npmjs.org/phonegap
22 verbose stack Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
22 verbose stack     at Error (native)
22 verbose stack     at Object.createSecureContext (_tls_common.js:87:19)
22 verbose stack     at Object.TLSSocket._init.ssl.onclienthello.ssl.oncertcb.exports.connect (_tls_wrap.js:968:23)
22 verbose stack     at Agent.createConnection (https.js:73:22)
22 verbose stack     at Agent.createSocket (_http_agent.js:172:16)
22 verbose stack     at Agent.addRequest (_http_agent.js:141:23)
22 verbose stack     at new ClientRequest (_http_client.js:131:16)
22 verbose stack     at Object.exports.request (http.js:31:10)
22 verbose stack     at Object.socket.once.exports.request (https.js:183:15)
22 verbose stack     at Request.start (/usr/local/lib/node_modules/npm/node_modules/request/request.js:747:30)
23 verbose cwd /Users/rahul
24 error Darwin 14.0.0
25 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "phonegap@latest"
26 error node v4.4.0
27 error npm  v2.14.20
28 error error:0906D06C:PEM routines:PEM_read_bio:no start line
29 error If you need help, you may report this error at:
29 error     <https://github.com/npm/npm/issues>
30 verbose exit [ 1, true ]
```

**Comment by zkat** [comment]
Hi! Are you behind a corporate firewall? This sort of error isn't really an npm issue, per se, but a matter of having either a bad local SSL certificate or, more likely, a bad certificate on your configured proxy.

Best chance here is to double-check your proxy configuration, and ask your corporate network admin to look into the issue.

**Comment by aksinsane** [comment]
Yes, but I have tried using external network and the same issue persists.

**Comment by aksinsane** [comment]
Kindly help me in getting this issue resolved

**Comment by zkat** [comment]
What have you done so far to get your proxy configuration to work? What does your `npmrc` look like?

**Comment by aksinsane** [comment]
i have tried to download it again using external network but the same issue was coming and how to look for npmrc i dont know as i am new to this technology.
