### ISSUE TITLE
npm -v   error

### ISSUE THREAD

**Issue by liubailing** [npm/npm#12018]
OS:        **win10**
             **X64**

C:\Windows\system32>node -v
v4.4.0

C:\Windows\system32>npm -v
Error: Cannot find module 'spdx-expression-parse'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\validate-npm-package-license\index.js:1:75)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "prefix" "-g"
npm ERR! node v4.4.0
npm ERR! npm  v2.14.20
npm ERR! code MODULE_NOT_FOUND

npm ERR! **Cannot find module 'spdx-expression-parse'**
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues
2.14.20

**Comment by zkat** [comment]
Hi!

It looks like something broke with your npm installation. Do you mind reinstalling it from scratch? You may have to redownload the node.js binary and install that again.
