### ISSUE TITLE
can't login or create user

### ISSUE THREAD

**Issue by Haroenv** [npm/npm#12024]
- platform: OS X 10.11.4
- npm version: 3.8.2
- node version: v5.5.0

I did: 

```
$ npm login
Username: haroenv
Password: 
Email: (this IS public) hello@haroen.me
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/Cellar/node/5.5.0/bin/node" "/usr/local/bin/npm" "login"
npm ERR! node v5.5.0
npm ERR! npm  v3.8.2
npm ERR! code E400

npm ERR! Unknown error while authenticating : -/user/org.couchdb.user:haroenv
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/haroenv/git/gipod-to-geojson/npm-debug.log
```

the contents of `npm-debug.log` is:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/5.5.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'login' ]
2 info using npm@3.8.2
3 info using node@v5.5.0
4 verbose adduser before first PUT { _id: 'org.couchdb.user:haroenv',
4 verbose adduser   name: 'haroenv',
4 verbose adduser   password: 'XXXXX',
4 verbose adduser   email: 'hello@haroen.me',
4 verbose adduser   type: 'user',
4 verbose adduser   roles: [],
4 verbose adduser   date: '2016-03-23T09:31:33.436Z' }
5 verbose request uri https://registry.npmjs.org/-/user/org.couchdb.user:haroenv
6 verbose request new user, so can't send auth
7 info attempt registry request try #1 at 10:31:33 AM
8 verbose request id 157c8028859de70e
9 http request PUT https://registry.npmjs.org/-/user/org.couchdb.user:haroenv
10 http 400 https://registry.npmjs.org/-/user/org.couchdb.user:haroenv
11 verbose headers { 'content-type': 'application/json',
11 verbose headers   'cache-control': 'max-age=300',
11 verbose headers   'content-length': '57',
11 verbose headers   'accept-ranges': 'bytes',
11 verbose headers   date: 'Wed, 23 Mar 2016 09:31:34 GMT',
11 verbose headers   via: '1.1 varnish',
11 verbose headers   connection: 'keep-alive',
11 verbose headers   'x-served-by': 'cache-lhr6335-LHR',
11 verbose headers   'x-cache': 'MISS',
11 verbose headers   'x-cache-hits': '0',
11 verbose headers   'x-timer': 'S1458725493.755968,VS0,VE569' }
12 verbose request invalidating /Users/haroenv/.npm/registry.npmjs.org/-/user/org.couchdb.user_3Aharoenv on PUT
13 verbose adduser back [ { [Error: Unknown error while authenticating : -/user/org.couchdb.user:haroenv] statusCode: 400, code: 'E400' },
13 verbose adduser   { ok: false, error: 'Unknown error while authenticating' },
13 verbose adduser   '{"ok":false,"error":"Unknown error while authenticating"}' ]
14 verbose stack Error: Unknown error while authenticating : -/user/org.couchdb.user:haroenv
14 verbose stack     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
14 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:252:14)
14 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
14 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:199:22)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at Request.emit (events.js:185:7)
14 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1036:10)
14 verbose stack     at emitOne (events.js:95:20)
14 verbose stack     at Request.emit (events.js:182:7)
14 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:963:12)
15 verbose statusCode 400
16 verbose cwd /Users/haroenv/git/gipod-to-geojson
17 error Darwin 15.4.0
18 error argv "/usr/local/Cellar/node/5.5.0/bin/node" "/usr/local/bin/npm" "login"
19 error node v5.5.0
20 error npm  v3.8.2
21 error code E400
22 error Unknown error while authenticating : -/user/org.couchdb.user:haroenv
23 error If you need help, you may report this error at:
23 error     <https://github.com/npm/npm/issues>
24 verbose exit [ 1, true ]
```

`npm adduser` produced the same results

I can login on npmjs.com

**Comment by zkat** [comment]
I've only ever seen this for a bad login/password. There's a possibility that some types of passwords will not work on the CLI vs web, though (I was sure there was a bug, but I can't find it, about whitespace getting trimmed for passwords in the CLI). If this is the case, I recommend you change your password, or contact support@npmjs.com for further help if that doesn't fix it, since they'll be able to help you with account-specific issues. :)
