### ISSUE TITLE
ibm_db problem 

### ISSUE THREAD

**Issue by AnnaSem** [npm/npm#12056]
For some reason i can't install this: npm install node-red-nodes-cf-sqldb-dashdb

it gives me an error:

```
pi@raspberrypi:~/.node-red $ npm install node-red-nodes-cf-sqldb-dashdb
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
/
> ibm_db@0.0.19 install /home/pi/.node-red/node_modules/node-red-nodes-cf-sqldb-dashdb/node_modules/ibm_db
> node installer/driverInstall.js

Downloading DB2 ODBC CLI Driver from http://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxia32_odbc_cli.tar.gz...
Download and extraction of DB2 ODBC CLI Driver completed successfully ...
make: Entering directory '/home/pi/.node-red/node_modules/node-red-nodes-cf-sqldb-dashdb/node_modules/ibm_db/build'
  CXX(target) Release/obj.target/odbc_bindings/src/odbc.o
odbc_bindings.target.mk:92: recipe for target 'Release/obj.target/odbc_bindings/src/odbc.o' failed
make: Leaving directory '/home/pi/.node-red/node_modules/node-red-nodes-cf-sqldb-dashdb/node_modules/ibm_db/build'

{ [Error: Command failed: In file included from ../src/odbc.cpp:25:0:
../src/odbc.h:30:21: fatal error: sqlcli1.h: No such file or directory
 #include <sqlcli1.h>
                     ^
compilation terminated.
make: *** [Release/obj.target/odbc_bindings/src/odbc.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
gyp ERR! System Linux 4.1.19-v7+
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build" "--IBM_DB_HOME=/home/pi/.node-red/node_modules/node-red-nodes-cf-sqldb-dashdb/node_modules/ibm_db/installer/clidriver" "--IS_DOWNLOADED=true"
gyp ERR! cwd /home/pi/.node-red/node_modules/node-red-nodes-cf-sqldb-dashdb/node_modules/ibm_db
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
] killed: false, code: 1, signal: null }
npm ERR! Linux 4.1.19-v7+
npm ERR! argv "node" "/usr/local/bin/npm" "install" "node-red-nodes-cf-sqldb-dashdb"
npm ERR! node v0.10.29
npm ERR! npm  v2.15.2
npm ERR! code ELIFECYCLE

npm ERR! ibm_db@0.0.19 install: `node installer/driverInstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ibm_db@0.0.19 install script 'node installer/driverInstall.js'.
npm ERR! This is most likely a problem with the ibm_db package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node installer/driverInstall.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ibm_db
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls ibm_db
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/.node-red/npm-debug.log
pi@raspberrypi:~/.node-red $
```
any solutions to that problem?

**Comment by zkat** [comment]
Unfortunately, this is not a problem in npm, but a build issue with `ibm_db`. You're going to be better off asking for support over at https://github.com/ibmdb/node-ibm_db/issues

Specifically, it looks like the line of note is: `../src/odbc.h:30:21: fatal error: sqlcli1.h: No such file or directory` -- which means it's missing some file that it needs in order to complete the build. Since this is not directly relevant to npm, I'm gonna close this.

Thanks for taking the time to file an issue! If you have further questions, feel free to comment in this issue or open a new one! :)
