### ISSUE TITLE
Installing eslint-standard-package failed!

### ISSUE THREAD

**Issue by raedlime** [npm/npm#12062]
Hi,

I tried to install a package for eslint with this command "eslint --init", but I get the following error report:

```
Installing eslint-plugin-standard, eslint-config-standard
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/Cellar/node/5.9.0/bin/node" "/usr/local/bin/npm" "i" "--save-dev" "eslint-plugin-standard" "eslint-config-standard"
npm ERR! node v5.9.0
npm ERR! npm  v3.7.3

npm ERR! Cannot read property 'target' of null
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/lib/node_modules/eslint/npm-debug.log
Successfully created .eslintrc.js file in /usr/local/lib/node_modules/eslint
```

Could you help me please? I don't really get it :-(
I'm writing here because of the note "If you need help, you may report this error at:"

Please help me!

**Comment by mrrnlds** [comment]
Hello,

It appears `eslint` is calling `npm` for the `--init` flag.
I received a similar error when running `npm -g update npm` on linux:
```
npm ERR! Linux 3.19.0-56-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/local/lib/node_modules/npm/cli.js" "install" "marked-man" "--no-global"
npm ERR! node v4.4.1
npm ERR! npm  v3.8.1

npm ERR! Cannot read property 'target' of null
```

I resolved the problem by reinstalling npm: `npm -g install npm`
which brought npm to v3.8.3 and `npm -g update npm` now runs without error.

**Comment by raedlime** [comment]
Hit, 

thanks a lot for the quick response!

I reinstalled npm and updated it just like you did in your comment.

In which directory dit you navigate before "eslint --init"? When I go to /usr/local/lib/node_modules/eslint via terminal and do the "eslint --init" I get this now:

```
CiMac:eslint dtpadmin$ eslint --init
? How would you like to configure ESLint? Use a popular style guide
? Which style guide do you want to follow? Standard
? What format do you want your config file to be in? JavaScript
Installing eslint-plugin-standard, eslint-config-standard
npm WARN eslint-config-standard@5.1.0 requires a peer of eslint@^2.0.0-rc.0 but none was installed.
npm WARN eslint-config-standard@5.1.0 requires a peer of eslint-plugin-promise@^1.0.8 but none was installed.
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/Cellar/node/5.9.0/bin/node" "/usr/local/bin/npm" "i" "--save-dev" "eslint-plugin-standard" "eslint-config-standard"
npm ERR! node v5.9.0
npm ERR! npm  v3.8.3
npm ERR! path /usr/local/lib/node_modules/eslint/node_modules/.staging/eslint-a5bd53f8
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/eslint/node_modules/.staging/eslint-a5bd53f8' -> '/usr/local/lib/node_modules/eslint'
npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/eslint/node_modules/.staging/eslint-a5bd53f8' -> '/usr/local/lib/node_modules/eslint'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/Cellar/node/5.9.0/bin/node" "/usr/local/bin/npm" "i" "--save-dev" "eslint-plugin-standard" "eslint-config-standard"
npm ERR! node v5.9.0
npm ERR! npm  v3.8.3
npm ERR! path npm-debug.log.834658862
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open 'npm-debug.log.834658862'
npm ERR! enoent ENOENT: no such file or directory, open 'npm-debug.log.834658862'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/lib/node_modules/eslint/npm-debug.log
ENOENT: no such file or directory, open './.eslintrc.js'
Error: ENOENT: no such file or directory, open './.eslintrc.js'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.writeFileSync (fs.js:1224:33)
    at writeJSConfigFile (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:268:8)
    at Object.write (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:282:13)
    at writeFile (/usr/local/lib/node_modules/eslint/lib/config/config-initializer.js:50:16)
    at null.completed (/usr/local/lib/node_modules/eslint/lib/config/config-initializer.js:333:17)
    at PromptUI.onCompletion (/usr/local/lib/node_modules/eslint/node_modules/inquirer/lib/ui/prompt.js:57:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (/usr/local/lib/node_modules/eslint/node_modules/rx-lite/rx.lite.js:1550:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/eslint/node_modules/rx-lite/rx.lite.js:1489:14)
```

What am I doing wrong?
I'm pretty new in at such things, sry :-/

**Comment by mrrnlds** [comment]
I'm still pretty new at this also and had to work out some of these same issues just recently.

`ENOENT` means a missing file or directory and probably results from a write permission issue at:
`/usr/local/lib/node_modules` 
You can Google it for more info.

I originally tried the Homebrew installation of node as well and had similar issues on my Mac. In the end I uninstalled the Homebrew version and followed this guide instead: 
`https://coolestguidesontheplanet.com/installing-node-js-on-osx-10-10-yosemite/`

Note especially this section near the end: 
> **To Sudo or not to Sudo**

It's basically a shortcut to one of the solutions described here:
`https://docs.npmjs.com/getting-started/fixing-npm-permissions`

Good luck!

**Comment by mrrnlds** [comment]
I added a gist with directions to install or update node and npm on OSX [here](https://gist.github.com/mrrnlds/343c11b7eeca9542bb4c)

**Comment by zkat** [comment]
hi @raedlime -- could you post the contents of `npm-debug.log` when this error happens? That error could definitely be more helpful! :)
