### ISSUE TITLE
Publish failed PUT 500

### ISSUE THREAD

**Issue by nzakas** [npm/npm#12069]
```
$ node -v
v0.12.9

$ npm -v
2.14.9
```

(I'm on Windows 10, if that matters.)

I've been getting this error intermittently for the past couple of days when attempting to push the `eslint-release` package:

```
Publishing to npm
npm ERR! publish Failed PUT 500
npm ERR! Error: getaddrinfo ENOTFOUND user-acl-2-west.internal.npmjs.com user-acl-2-west.internal.npmjs.com:443 : eslint-release
npm ERR!     at RegClient.<anonymous> (C:\Users\Nicholas\AppData\Roaming\npm\node_modules\npm\node_modules\npm-registry-client\lib\request.js:273:14)
npm ERR!     at Request._callback (C:\Users\Nicholas\AppData\Roaming\npm\node_modules\npm\node_modules\npm-registry-client\lib\request.js:211:65)
npm ERR!     at Request.self.callback (C:\Users\Nicholas\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.js:123:22)
npm ERR!     at Request.emit (events.js:110:17)
npm ERR!     at Request.<anonymous> (C:\Users\Nicholas\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.js:893:14)
npm ERR!     at Request.emit (events.js:129:20)
npm ERR!     at IncomingMessage.<anonymous> (C:\Users\Nicholas\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.js:844:12)
npm ERR!     at IncomingMessage.emit (events.js:129:20)
npm ERR!     at _stream_readable.js:908:16
npm ERR!     at process._tickCallback (node.js:355:11)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 10.0.10586
npm ERR! command "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Users\\Nicholas\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "publish"
npm ERR! cwd C:\Users\Nicholas\projects\personal\eslint-release
npm ERR! node -v v0.12.9
npm ERR! npm -v 1.4.10
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\Nicholas\projects\personal\eslint-release\npm-debug.log
npm ERR! not ok code 0
```

This has happened at least four times in the past 24 hours and just wanted to report it in case it's a concern.

**Comment by zkat** [comment]
We've been having occasional issues for the past couple of days after some hardware failures. I've passed on this ticket to the registry team and update you if I see anything else. I assume you're not behind a firewall or such.

That said, I definitely recommend upgrading to either `npm@lts` or `npm@latest`, since `npm@1` is no longer supported.

**Comment by nzakas** [comment]
I'm using `npm@2` and can't upgrade npm without upgrading Node since I'm on Windows. I'm not behind a firewall.

**Comment by zkat** [comment]
You can do `npm install -g npm@lts` in order to upgrade from `npm@1.4.19` to `npm@2`. Your debug log says:
```
npm ERR! node -v v0.12.9
npm ERR! npm -v 1.4.10
```

**Comment by nzakas** [comment]
Once again, I cannot upgrade like that on Windows. It doesn't work. 

Also, why did the debug log give a different version than my command line? 

```
$ node -v
v0.12.9

$ npm -v
2.14.9
```

**Comment by mmalecki** [comment]
@nzakas thanks for heads up regarding publish issues - we've had some [hardware failures this week](http://status.npmjs.org/incidents/fgfvyxdmy4d8) and this was a result of them. I just confirmed that our configuration no longer refers to that dead host, so you should be able to publish with no hiccups.

**Comment by nzakas** [comment]
Thanks @mmalecki. Unfortunately, I just received the same error again:

```
$ npm publish
npm ERR! publish Failed PUT 500
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "publish"
npm ERR! node v0.12.9
npm ERR! npm  v2.14.9
npm ERR! code E500

npm ERR! getaddrinfo ENOTFOUND user-acl-2-west.internal.npmjs.com user-acl-2-west.internal.npmjs.com:443 : eslint
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Nicholas\projects\personal\eslint\npm-debug.log
```

Here's the full log: https://gist.github.com/nzakas/f3458942af4cc8b55908

**Comment by trentm** [comment]
I'm seeing the same or similar "getaddrinfo ENOTFOUND user-acl-2-west.internal.npmjs.com" error:

```
$ npm publish
npm WARN deprecated This version of npm lacks support for important features,
npm WARN deprecated such as scoped packages, offered by the primary npm
npm WARN deprecated registry. Consider upgrading to at least npm@2, if not the
npm WARN deprecated latest stable version. To upgrade to npm@2, run:
npm WARN deprecated
npm WARN deprecated   npm -g install npm@latest-2
npm WARN deprecated
npm WARN deprecated To upgrade to the latest stable version, run:
npm WARN deprecated
npm WARN deprecated   npm -g install npm@latest
npm WARN deprecated
npm WARN deprecated (Depending on how Node.js was installed on your system, you
npm WARN deprecated may need to prefix the preceding commands with `sudo`, or if
npm WARN deprecated on Windows, run them from an Administrator prompt.)
npm WARN deprecated
npm WARN deprecated If you're running the version of npm bundled with
npm WARN deprecated Node.js 0.10 LTS, be aware that the next version of 0.10 LTS
npm WARN deprecated will be bundled with a version of npm@2, which has some small
npm WARN deprecated backwards-incompatible changes made to `npm run-script` and
npm WARN deprecated semver behavior.
npm ERR! publish Failed PUT 500
npm ERR! Error: getaddrinfo ENOTFOUND user-acl-2-west.internal.npmjs.com user-acl-2-west.internal.npmjs.com:443 : triton
npm ERR!     at RegClient.<anonymous> (/Users/trentm/opt/node-0.10.42/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:308:14)
npm ERR!     at Request._callback (/Users/trentm/opt/node-0.10.42/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:246:65)
npm ERR!     at Request.self.callback (/Users/trentm/opt/node-0.10.42/lib/node_modules/npm/node_modules/request/request.js:236:22)
npm ERR!     at Request.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/Users/trentm/opt/node-0.10.42/lib/node_modules/npm/node_modules/request/request.js:1142:14)
npm ERR!     at Request.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/Users/trentm/opt/node-0.10.42/lib/node_modules/npm/node_modules/request/request.js:1096:12)
npm ERR!     at IncomingMessage.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:944:16
npm ERR!     at process._tickCallback (node.js:448:13)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 15.3.0
npm ERR! command "/Users/trentm/opt/node-0.10.42/bin/node" "/Users/trentm/opt/node-0.10/bin/npm" "publish"
npm ERR! cwd /Users/trentm/pristine/node-triton
npm ERR! node -v v0.10.42
npm ERR! npm -v 1.4.29
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/trentm/pristine/node-triton/npm-debug.log
npm ERR! not ok code 0
```

I'm running on Mac 10.11.3, FWIW.

**Comment by trentm** [comment]
^^^ I hit it twice and then my `npm publish` worked a 3rd time.
