### ISSUE TITLE
npm login fails with "unknown error while authenticating"

### ISSUE THREAD

**Issue by tangledfruit** [npm/npm#12071]
```
$ npm login
Username: tangledfruit
Password: 
Email: (this IS public) xxx@xxx.com
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "login"
npm ERR! node v5.7.0
npm ERR! npm  v3.8.1
npm ERR! code E400

npm ERR! Unknown error while authenticating : -/user/org.couchdb.user:tangledfruit
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /(path)/rx-to-async-iterator/npm-debug.log
```

Have tried several times and I'm pretty sure my password is correct. (Just successfully logged in to the web interface via same username and password on first try.)

**Comment by tangledfruit** [comment]
```
$ cat npm-debug.log 
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'login' ]
2 info using npm@3.8.1
3 info using node@v5.7.0
4 verbose adduser before first PUT { _id: 'org.couchdb.user:tangledfruit',
4 verbose adduser   name: 'tangledfruit',
4 verbose adduser   password: 'XXXXX',
4 verbose adduser   email: 'code@tangledfruit.com',
4 verbose adduser   type: 'user',
4 verbose adduser   roles: [],
4 verbose adduser   date: '2016-03-25T20:39:31.552Z' }
5 verbose request uri https://registry.npmjs.org/-/user/org.couchdb.user:tangledfruit
6 verbose request new user, so can't send auth
7 info attempt registry request try #1 at 1:39:31 PM
8 verbose request id 1b475395bb453b03
9 http request PUT https://registry.npmjs.org/-/user/org.couchdb.user:tangledfruit
10 http 400 https://registry.npmjs.org/-/user/org.couchdb.user:tangledfruit
11 verbose headers { 'content-type': 'application/json',
11 verbose headers   'cache-control': 'max-age=300',
11 verbose headers   'content-length': '57',
11 verbose headers   'accept-ranges': 'bytes',
11 verbose headers   date: 'Fri, 25 Mar 2016 20:39:32 GMT',
11 verbose headers   via: '1.1 varnish',
11 verbose headers   connection: 'keep-alive',
11 verbose headers   'x-served-by': 'cache-lax1428-LAX',
11 verbose headers   'x-cache': 'MISS',
11 verbose headers   'x-cache-hits': '0',
11 verbose headers   'x-timer': 'S1458938372.033082,VS0,VE202' }
12 verbose request invalidating /Users/scouten/.npm/registry.npmjs.org/-/user/org.couchdb.user_3Atangledfruit on PUT
13 verbose adduser back [ { [Error: Unknown error while authenticating : -/user/org.couchdb.user:tangledfruit] statusCode: 400, code: 'E400' },
13 verbose adduser   { ok: false, error: 'Unknown error while authenticating' },
13 verbose adduser   '{"ok":false,"error":"Unknown error while authenticating"}' ]
14 verbose stack Error: Unknown error while authenticating : -/user/org.couchdb.user:tangledfruit
14 verbose stack     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
14 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:252:14)
14 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
14 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:199:22)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at Request.emit (events.js:185:7)
14 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1036:10)
14 verbose stack     at emitOne (events.js:95:20)
14 verbose stack     at Request.emit (events.js:182:7)
14 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:963:12)
15 verbose statusCode 400
16 verbose cwd /(path)/rx-to-async-iterator
17 error Darwin 15.3.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "login"
19 error node v5.7.0
20 error npm  v3.8.1
21 error code E400
22 error Unknown error while authenticating : -/user/org.couchdb.user:tangledfruit
23 error If you need help, you may report this error at:
23 error     <https://github.com/npm/npm/issues>
24 verbose exit [ 1, true ]
```

**Comment by tangledfruit** [comment]
Nvm. Rebooting the machine "fixed" the problem.
