### ISSUE TITLE
Adduser error

### ISSUE THREAD

**Issue by govindshah** [npm/npm#12076]
I am getting following error when trying to adduser. Here is console output and log.

Console:
Username: govind
Password: 
Email: (this IS public) gXXXXXXXXX@gmail.com
npm ERR! Darwin 15.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "adduser"
npm ERR! node v0.10.33
npm ERR! npm  v2.14.7
npm ERR! code E400

npm ERR! Unknown error while authenticating : -/user/org.couchdb.user:govind
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/govind/workspace/json2json-transform/npm-debug.log

DEBUG LOGS:
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'adduser' ]
2 info using npm@2.14.7
3 info using node@v0.10.33
4 verbose adduser before first PUT { _id: 'org.couchdb.user:govind',
4 verbose adduser   name: 'govind',
4 verbose adduser   password: 'XXXXXXXXXX',
4 verbose adduser   email: 'gXXXXXXXX@gmail.com',
4 verbose adduser   type: 'user',
4 verbose adduser   roles: [],
4 verbose adduser   date: '2016-03-25T21:34:14.391Z' }
5 verbose request uri https://registry.npmjs.org/-/user/org.couchdb.user:govind
6 verbose request new user, so can't send auth
7 info attempt registry request try #1 at 17:34:14
8 verbose request id 022e0f8eab6d5082
9 http request PUT https://registry.npmjs.org/-/user/org.couchdb.user:govind
10 http 400 https://registry.npmjs.org/-/user/org.couchdb.user:govind
11 verbose headers { 'content-type': 'application/json',
11 verbose headers   'cache-control': 'max-age=300',
11 verbose headers   'content-length': '57',
11 verbose headers   'accept-ranges': 'bytes',
11 verbose headers   date: 'Fri, 25 Mar 2016 21:34:15 GMT',
11 verbose headers   via: '1.1 varnish',
11 verbose headers   connection: 'keep-alive',
11 verbose headers   'x-served-by': 'cache-atl6241-ATL',
11 verbose headers   'x-cache': 'MISS',
11 verbose headers   'x-cache-hits': '0',
11 verbose headers   'x-timer': 'S1458941655.500426,VS0,VE361' }
12 verbose request invalidating /Users/govind/.npm/registry.npmjs.org/-/user/org.couchdb.user_3Agovind on PUT
13 verbose adduser back [ { [Error: Unknown error while authenticating : -/user/org.couchdb.user:govind] statusCode: 400, code: 'E400' },
13 verbose adduser   { ok: false, error: 'Unknown error while authenticating' },
13 verbose adduser   '{"ok":false,"error":"Unknown error while authenticating"}' ]
14 verbose stack Error: Unknown error while authenticating : -/user/org.couchdb.user:govind
14 verbose stack     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
14 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:252:14)
14 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
14 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:198:22)
14 verbose stack     at Request.emit (events.js:98:17)
14 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1063:14)
14 verbose stack     at Request.emit (events.js:117:20)
14 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1009:12)
14 verbose stack     at IncomingMessage.emit (events.js:117:20)
14 verbose stack     at _stream_readable.js:943:16
15 verbose statusCode 400
16 verbose cwd /Users/govind/workspace/json2json-transform
17 error Darwin 15.4.0
18 error argv "node" "/usr/local/bin/npm" "adduser"
19 error node v0.10.33
20 error npm  v2.14.7
21 error code E400
22 error Unknown error while authenticating : -/user/org.couchdb.user:govind
23 error If you need help, you may report this error at:
23 error     <https://github.com/npm/npm/issues>
24 verbose exit [ 1, true ]

**Comment by govindshah** [comment]
Looks like the issue with username, tried with a different username and it worked
