### ISSUE TITLE
error to install express  by npm install --save express@4.10.2

### ISSUE THREAD

**Issue by yanliqing** [npm/npm#12108]
```
192:chat-example root# npm install --save express@4.10.2
npm ERR! AssertionError: must pass params to get
npm ERR!     at RegClient.get (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:12:3)
npm ERR!     at addNameVersion (/usr/local/lib/node_modules/npm/lib/cache.js:737:12)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:604:5
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:1233:7
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:143:23
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:143:23
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:161:16
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:103:5
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 14.4.0
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "express@4.10.2"
npm ERR! cwd /opt/chat-example
npm ERR! node -v v0.10.22
npm ERR! npm -v TypeError: Cannot read property 'node' of undefined
npm ERR! npm -v     at /usr/local/lib/node_modules/npm/lib/npm.js:61:38
npm ERR! npm -v     at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/npm.js:520:3)
npm ERR! npm -v     at Module._compile (module.js:456:26)
npm ERR! npm -v     at Object.Module._extensions..js (module.js:474:10)
npm ERR! npm -v     at Module.load (module.js:356:32)
npm ERR! npm -v     at Function.Module._load (module.js:312:12)
npm ERR! npm -v     at Module.require (module.js:364:17)
npm ERR! npm -v     at require (module.js:380:17)
npm ERR! npm -v     at /usr/local/lib/node_modules/npm/bin/npm-cli.js:25:11
npm ERR! npm -v     at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:87:3)
npm ERR! npm -v  [TypeError: Cannot read property 'node' of undefined]
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /opt/chat-example/npm-debug.log
npm ERR! not ok code 0
```

**Comment by zkat** [comment]
It looks like something's pretty wrong with your npm install. You can either re-download node, with its bundled npm, or use `curl -L https://www.npmjs.com/install.sh | sh` to download and install a fresh version of npm itself.
