### ISSUE TITLE
two troubles occur in my npm install ,help~~

### ISSUE THREAD

**Issue by zhengtulym1991** [npm/npm#12128]
```
D:\angular\angular-phonecat>npm install

> bufferutil@1.2.1 install D:\angular\angular-phonecat\node_modules\bufferutil
> node-gyp rebuild


D:\angular\angular-phonecat\node_modules\bufferutil>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: read ECONNRESET
gyp ERR! stack     at exports._errnoException (util.js:890:11)
gyp ERR! stack     at TLSWrap.onread (net.js:552:26)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\angular\angular-phonecat\node_modules\bufferutil
gyp ERR! node -v v5.9.1
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok
npm WARN install:bufferutil@1.2.1 bufferutil@1.2.1 install: `node-gyp rebuild`
npm WARN install:bufferutil@1.2.1 Exit status 1

> utf-8-validate@1.2.1 install D:\angular\angular-phonecat\node_modules\utf-8-validate
> node-gyp rebuild


D:\angular\angular-phonecat\node_modules\utf-8-validate>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: read ECONNRESET
gyp ERR! stack     at exports._errnoException (util.js:890:11)
gyp ERR! stack     at TLSWrap.onread (net.js:552:26)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\angular\angular-phonecat\node_modules\utf-8-validate
gyp ERR! node -v v5.9.1
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok
npm WARN install:utf-8-validate@1.2.1 utf-8-validate@1.2.1 install: `node-gyp rebuild`
npm WARN install:utf-8-validate@1.2.1 Exit status 1

> angular-phonecat@0.0.0 postinstall D:\angular\angular-phonecat
> bower install

bower not-cached    git://github.com/angular/bower-angular.git#1.4.x
bower resolve       git://github.com/angular/bower-angular.git#1.4.x
bower not-cached    git://github.com/angular/bower-angular-mocks.git#1.4.x
bower resolve       git://github.com/angular/bower-angular-mocks.git#1.4.x
bower not-cached    git://github.com/angular/bower-angular-animate.git#1.4.x
bower resolve       git://github.com/angular/bower-angular-animate.git#1.4.x
bower not-cached    git://github.com/jquery/jquery-dist.git#~2.1.1
bower resolve       git://github.com/jquery/jquery-dist.git#~2.1.1
bower not-cached    git://github.com/twbs/bootstrap.git#~3.1.1
bower resolve       git://github.com/twbs/bootstrap.git#~3.1.1
bower not-cached    git://github.com/angular/bower-angular-route.git#1.4.x
bower resolve       git://github.com/angular/bower-angular-route.git#1.4.x
bower not-cached    git://github.com/angular/bower-angular-resource.git#1.4.x
bower resolve       git://github.com/angular/bower-angular-resource.git#1.4.x
bower ECMDERR       Failed to execute "git ls-remote --tags --heads git://github.com/angular/bower-angular-mocks.git", exit code of #128 fatal: unable to access 'https://github.com/angular/bower-angular-mocks.git/': Failed to connect to github.com port 443: Timed out

Additional error details:
fatal: unable to access 'https://github.com/angular/bower-angular-mocks.git/': Failed to connect to github.com port 443: Timed out

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.9
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v5.9.1
npm ERR! npm  v3.7.3
npm ERR! code ELIFECYCLE
npm ERR! angular-phonecat@0.0.0 postinstall: `bower install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-phonecat@0.0.0 postinstall script 'bower install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-phonecat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-phonecat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-phonecat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\angular\angular-phonecat\npm-debug.log
```

**Comment by KenanY** [comment]
@zhengtulym1991 Is this still an issue for you?

**Comment by zhengtulym1991** [comment]
@KenanY thanks. no, I chose React instead.
