### ISSUE TITLE
npm install throwing error.

### ISSUE THREAD

**Issue by dsampangi** [npm/npm#12134]
```
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v5.9.1
npm ERR! npm  v3.7.3
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (c:\Program Files\nodejs\node_modules\npm\lib\fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (c:\Program Files\nodejs\node_modules\npm\lib\fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (c:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:455:12)
npm ERR! typeerror     at c:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:456:7
npm ERR! typeerror     at c:\Program Files\nodejs\node_modules\npm\node_modules\iferr\index.js:13:50
npm ERR! typeerror     at c:\Program Files\nodejs\node_modules\npm\lib\fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (c:\Program Files\nodejs\node_modules\npm\lib\fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (c:\Program Files\nodejs\node_modules\npm\lib\fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (c:\Program Files\nodejs\node_modules\npm\lib\fetch-package-metadata.js:134:20)
npm ERR! typeerror     at c:\Program Files\nodejs\node_modules\npm\node_modules\iferr\index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
```

**Comment by othiym23** [comment]
This should be addressed by upgrading to a [newer version of npm](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm). As such, I'm going to close this issue as resolved. Thanks for your time!

**Comment by theofidry** [comment]
Hello,

I have the same issue both locally (OSX 10.9) and on Travis (cf. [build](https://travis-ci.org/theofidry/travis-bug-demo/jobs/128909465)).

- node: `4.2.6`
- npm: `3.9.0`

Short message:

<img width="877" alt="screen shot 2016-05-09 at 18 23 09" src="https://cloud.githubusercontent.com/assets/5175937/15121559/1e0b4210-1613-11e6-990e-a5c3d5f5186a.png">

Full `npm-debug.log` content [here](https://gist.github.com/theofidry/3212be0e1c08bddfae928360820cfce9).
