### ISSUE TITLE
self signed certificate in certificate chain

### ISSUE THREAD

**Issue by knida** [npm/npm#12144]
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'protractor' ]
2 info using npm@3.7.3
3 info using node@v5.9.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData protractor
8 silly fetchNamedPackageData protractor
9 silly mapToRegistry name protractor
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry uri https://registry.npmjs.org/protractor
13 verbose request uri https://registry.npmjs.org/protractor
14 verbose request no auth needed
15 info attempt registry request try #1 at 11:53:52 AM
16 verbose request id cb59338d1c07a90e
17 http request GET https://registry.npmjs.org/protractor
18 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
19 info attempt registry request try #2 at 11:54:02 AM
20 http request GET https://registry.npmjs.org/protractor
21 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
22 info attempt registry request try #3 at 11:55:02 AM
23 http request GET https://registry.npmjs.org/protractor
24 silly fetchPackageMetaData Error: self signed certificate in certificate chain
24 silly fetchPackageMetaData     at Error (native)
24 silly fetchPackageMetaData     at TLSSocket.<anonymous> (_tls_wrap.js:1065:38)
24 silly fetchPackageMetaData     at emitNone (events.js:80:13)
24 silly fetchPackageMetaData     at TLSSocket.emit (events.js:179:7)
24 silly fetchPackageMetaData     at TLSSocket._init.ssl.onclienthello.ssl.oncertcb.TLSSocket._finishInit (_tls_wrap.js:593:8)
24 silly fetchPackageMetaData     at TLSWrap.ssl.onclienthello.ssl.oncertcb.ssl.onnewsession.ssl.onhandshakedone (_tls_wrap.js:425:38)
24 silly fetchPackageMetaData  error for protractor { [Error: self signed certificate in certificate chain] code: 'SELF_SIGNED_CERT_IN_CHAIN' }
25 silly rollbackFailedOptional Starting
26 silly rollbackFailedOptional Finishing
27 silly runTopLevelLifecycles Starting
28 silly runTopLevelLifecycles Finishing
29 silly install printInstalled
30 verbose stack Error: self signed certificate in certificate chain
30 verbose stack     at Error (native)
30 verbose stack     at TLSSocket.<anonymous> (_tls_wrap.js:1065:38)
30 verbose stack     at emitNone (events.js:80:13)
30 verbose stack     at TLSSocket.emit (events.js:179:7)
30 verbose stack     at TLSSocket._init.ssl.onclienthello.ssl.oncertcb.TLSSocket._finishInit (_tls_wrap.js:593:8)
30 verbose stack     at TLSWrap.ssl.onclienthello.ssl.oncertcb.ssl.onnewsession.ssl.onhandshakedone (_tls_wrap.js:425:38)
31 verbose cwd C:\Users\sys-allqc7
32 error Windows_NT 6.1.7601
33 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "protractor"
34 error node v5.9.1
35 error npm  v3.7.3
36 error code SELF_SIGNED_CERT_IN_CHAIN
37 error self signed certificate in certificate chain
38 error If you need help, you may report this error at:
38 error     <https://github.com/npm/npm/issues>
39 verbose exit [ 1, true ]
```

**Comment by heijmans** [comment]
You're probably behind a proxy. You have at least the following options:

- Run `npm config set strict-ssl=false`. This is insecure.
- Set the environmental var `https_proxy` to the right proxy. I am not sure how to do this on Windows and I cannot help you with your proxy settings.
- Use a cafile setting to add a certificate authority, e.g. `npm config set cafile=ca.crt`. You need to get the right cafile for your proxy.
