### ISSUE TITLE
npm install --save creating issue

### ISSUE THREAD

**Issue by kittu421** [npm/npm#12173]
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '--save',
1 verbose cli   'express@4.10.2' ]
2 info using npm@3.8.3
3 info using node@v5.10.0
4 verbose config Skipping project config: C:\Users\Administrator/.npmrc. (matches userconfig)
5 silly loadCurrentTree Starting
6 silly install loadCurrentTree
7 silly install readLocalPackageData
8 silly fetchPackageMetaData express@4.10.2
9 silly fetchNamedPackageData express
10 silly mapToRegistry name express
11 silly mapToRegistry using default registry
12 silly mapToRegistry registry http://registry.npmjs.org/
13 silly mapToRegistry data Result {
13 silly mapToRegistry   raw: 'express',
13 silly mapToRegistry   scope: null,
13 silly mapToRegistry   name: 'express',
13 silly mapToRegistry   rawSpec: '',
13 silly mapToRegistry   spec: 'latest',
13 silly mapToRegistry   type: 'tag' }
14 silly mapToRegistry uri http://registry.npmjs.org/express
15 verbose request uri http://registry.npmjs.org/express
16 verbose request no auth needed
17 info attempt registry request try #1 at 4:24:52 PM
18 verbose request id b958beb7a77fd95f
19 http request GET http://registry.npmjs.org/express
20 info retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN registry.npmjs.org:80
21 info attempt registry request try #2 at 4:25:15 PM
22 http request GET http://registry.npmjs.org/express
23 info retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN registry.npmjs.org:80
24 info attempt registry request try #3 at 4:26:27 PM
25 http request GET http://registry.npmjs.org/express
26 silly fetchPackageMetaData Error: getaddrinfo EAI_AGAIN registry.npmjs.org:80
26 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:890:11)
26 silly fetchPackageMetaData     at errnoException (dns.js:31:15)
26 silly fetchPackageMetaData     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)
26 silly fetchPackageMetaData  error for express@4.10.2 { [Error: getaddrinfo EAI_AGAIN registry.npmjs.org:80]
26 silly fetchPackageMetaData   code: 'EAI_AGAIN',
26 silly fetchPackageMetaData   errno: 'EAI_AGAIN',
26 silly fetchPackageMetaData   syscall: 'getaddrinfo',
26 silly fetchPackageMetaData   hostname: 'registry.npmjs.org',
26 silly fetchPackageMetaData   host: 'registry.npmjs.org',
26 silly fetchPackageMetaData   port: 80 }
27 silly rollbackFailedOptional Starting
28 silly rollbackFailedOptional Finishing
29 silly runTopLevelLifecycles Starting
30 silly runTopLevelLifecycles Finishing
31 silly install printInstalled
32 verbose stack Error: getaddrinfo EAI_AGAIN registry.npmjs.org:80
32 verbose stack     at Object.exports._errnoException (util.js:890:11)
32 verbose stack     at errnoException (dns.js:31:15)
32 verbose stack     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)
33 verbose cwd C:\Users\Administrator
34 error Windows_NT 6.1.7601
35 error argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "express@4.10.2"
36 error node v5.10.0
37 error npm  v3.8.3
38 error code EAI_AGAIN
39 error errno EAI_AGAIN
40 error syscall getaddrinfo
41 error getaddrinfo EAI_AGAIN registry.npmjs.org:80
42 error If you need help, you may report this error at:
42 error     <https://github.com/npm/npm/issues>
43 verbose exit [ 1, true ]
```

**Comment by kittu421** [comment]
I used to do npm config set http-proxy http://proxy.address:proxy.port and npm config set https-proxy http://proxy.address:proxy.port and everything worked fine.

**Comment by passcod** [comment]
This looks like this: https://github.com/npm/npm/issues/7348#issuecomment-75363630

> This does not look like an npm issue. Instead, this appears to be an issue with your internet connection making a DNS lookup.

and

> EAI_AGAIN is a transient name service failure, so keep retrying your request and it should eventually make it through.

**Comment by passcod** [comment]
Also https://github.com/npm/npm/issues/11308
