### ISSUE TITLE
npm adduser fails

### ISSUE THREAD

**Issue by tadeegan** [npm/npm#12176]
```
npm http PUT https://registry.npmjs.org/-/user/org.couchdb.user:tadeegan
npm http 400 https://registry.npmjs.org/-/user/org.couchdb.user:tadeegan
npm ERR! Error: ValidationError: child "password" fails because ["password" is required] : -/user/org.couchdb.user:tadeegan
npm ERR!     at RegClient.<anonymous> (/usr/local/Cellar/node/0.10.18/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:272:14)
npm ERR!     at Request.self.callback (/usr/local/Cellar/node/0.10.18/lib/node_modules/npm/node_modules/request/index.js:148:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/local/Cellar/node/0.10.18/lib/node_modules/npm/node_modules/request/index.js:891:14)
npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/local/Cellar/node/0.10.18/lib/node_modules/npm/node_modules/request/index.js:842:12)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 15.3.0
npm ERR! command "/usr/local/Cellar/node/0.10.18/bin/node" "/usr/local/bin/npm" "adduser"
npm ERR! node -v v0.10.18
npm ERR! npm -v 1.3.8
```

**Comment by ruisoftware** [comment]
Your npm v1.3.8 is pretty old. [Upgrade it](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) and that problem should go away.

**Comment by othiym23** [comment]
Closing as resolved. @ruisoftware is correct – `npm@1` is no longer supported. Thanks for your time, and good luck!

**Comment by vjeux** [comment]
Is there any way to make the error message clearer? I spent 20 minutes trying to figure out what was going on. A quick `please upgrade npm as this version is no longer supported` would have been great!

**Comment by KenanY** [comment]
@vjeux A message like that was added in `npm@1.4.29`, I believe.
