### ISSUE TITLE
Express module not installing

### ISSUE THREAD

**Issue by Rachitgupta1994** [npm/npm#12195]
Following are the contents of log file.

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'express' ]
2 info using npm@3.6.0
3 info using node@v5.7.1
4 verbose config Skipping project config: C:\Users\rachit.gupta09/.npmrc. (matches userconfig)
5 silly loadCurrentTree Starting
6 silly install loadCurrentTree
7 silly install readLocalPackageData
8 silly fetchPackageMetaData express
9 silly fetchNamedPackageData express
10 silly mapToRegistry name express
11 silly mapToRegistry using default registry
12 silly mapToRegistry registry https://registry.npmjs.org/
13 silly mapToRegistry uri https://registry.npmjs.org/express
14 verbose request uri https://registry.npmjs.org/express
15 verbose request no auth needed
16 info attempt registry request try #1 at 11:13:12 AM
17 verbose request id 03157685138315bf
18 http request GET https://registry.npmjs.org/express
19 info retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
20 info attempt registry request try #2 at 11:13:23 AM
21 http request GET https://registry.npmjs.org/express
22 info retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
23 info attempt registry request try #3 at 11:14:23 AM
24 http request GET https://registry.npmjs.org/express
25 silly fetchPackageMetaData Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
25 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:856:11)
25 silly fetchPackageMetaData     at errnoException (dns.js:31:15)
25 silly fetchPackageMetaData     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)
25 silly fetchPackageMetaData  error for express { [Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443]
25 silly fetchPackageMetaData   code: 'EAI_AGAIN',
25 silly fetchPackageMetaData   errno: 'EAI_AGAIN',
25 silly fetchPackageMetaData   syscall: 'getaddrinfo',
25 silly fetchPackageMetaData   hostname: 'registry.npmjs.org',
25 silly fetchPackageMetaData   host: 'registry.npmjs.org',
25 silly fetchPackageMetaData   port: 443 }
26 silly rollbackFailedOptional Starting
27 silly rollbackFailedOptional Finishing
28 silly runTopLevelLifecycles Starting
29 silly runTopLevelLifecycles Finishing
30 silly install printInstalled
31 verbose stack Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
31 verbose stack     at Object.exports._errnoException (util.js:856:11)
31 verbose stack     at errnoException (dns.js:31:15)
31 verbose stack     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)
32 verbose cwd C:\Users\rachit.gupta09
33 error Windows_NT 6.3.9600
34 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "express"
35 error node v5.7.1
36 error npm  v3.6.0
37 error code EAI_AGAIN
38 error errno EAI_AGAIN
39 error syscall getaddrinfo
40 error getaddrinfo EAI_AGAIN registry.npmjs.org:443
41 error If you need help, you may report this error at:
41 error     <https://github.com/npm/npm/issues>
42 verbose exit [ 1, true ]
```

**Comment by amandeepmittal** [comment]
try installing expressjs module with `--save` flag as local dependency or `-g` as global dependency.
