### ISSUE TITLE
Error when install bpmn-js using npm

### ISSUE THREAD

**Issue by sunilkumarmaghar** [npm/npm#12200]
```
0 info it worked if it ends with ok
1 verbose cli [ 'node',
1 verbose cli   'C:\\Users\\sunilk\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'bpmn-js' ]
2 info using npm@3.5.3
3 info using node@v0.12.7
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData bpmn-js
8 silly fetchNamedPackageData bpmn-js
9 silly mapToRegistry name bpmn-js
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry uri https://registry.npmjs.org/bpmn-js
13 verbose request uri https://registry.npmjs.org/bpmn-js
14 verbose request no auth needed
15 info attempt registry request try #1 at 4:14:07 PM
16 verbose request id 473b7caf41c9c33d
17 verbose etag "9CB9FC2MQOTHGN9E4BMT49S1Z"
18 http request GET https://registry.npmjs.org/bpmn-js
19 http 304 https://registry.npmjs.org/bpmn-js
20 verbose headers { date: 'Tue, 05 Apr 2016 10:44:09 GMT',
20 verbose headers   via: '1.1 varnish',
20 verbose headers   'cache-control': 'max-age=300',
20 verbose headers   etag: '"9CB9FC2MQOTHGN9E4BMT49S1Z"',
20 verbose headers   age: '264',
20 verbose headers   connection: 'keep-alive',
20 verbose headers   'x-served-by': 'cache-sin6920-SIN',
20 verbose headers   'x-cache': 'HIT',
20 verbose headers   'x-cache-hits': '1',
20 verbose headers   'x-timer': 'S1459853049.094273,VS0,VE0',
20 verbose headers   vary: 'Accept' }
21 silly get cb [ 304,
21 silly get   { date: 'Tue, 05 Apr 2016 10:44:09 GMT',
21 silly get     via: '1.1 varnish',
21 silly get     'cache-control': 'max-age=300',
21 silly get     etag: '"9CB9FC2MQOTHGN9E4BMT49S1Z"',
21 silly get     age: '264',
21 silly get     connection: 'keep-alive',
21 silly get     'x-served-by': 'cache-sin6920-SIN',
21 silly get     'x-cache': 'HIT',
21 silly get     'x-cache-hits': '1',
21 silly get     'x-timer': 'S1459853049.094273,VS0,VE0',
21 silly get     vary: 'Accept' } ]
22 verbose etag https://registry.npmjs.org/bpmn-js from cache
23 verbose get saving bpmn-js to C:\Users\sunilk\AppData\Roaming\npm-cache\registry.npmjs.org\bpmn-js\.cache.json
24 silly install normalizeTree
25 silly loadCurrentTree Finishing
26 silly loadIdealTree Starting
27 silly install loadIdealTree
28 silly cloneCurrentTree Starting
29 silly install cloneCurrentTreeToIdealTree
30 silly cloneCurrentTree Finishing
31 silly loadShrinkwrap Starting
32 silly install loadShrinkwrap
33 silly loadShrinkwrap Finishing
34 silly loadAllDepsIntoIdealTree Starting
35 silly install loadAllDepsIntoIdealTree
36 silly rollbackFailedOptional Starting
37 silly rollbackFailedOptional Finishing
38 silly runTopLevelLifecycles Starting
39 silly runTopLevelLifecycles Finishing
40 silly install printInstalled
41 verbose stack Error: Refusing to install bpmn-js as a dependency of itself
41 verbose stack     at checkSelf (C:\Users\sunilk\AppData\Roaming\npm\node_modules\npm\lib\install\validate-args.js:40:14)
41 verbose stack     at Array.<anonymous> (C:\Users\sunilk\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
41 verbose stack     at LOOP (C:\Users\sunilk\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
41 verbose stack     at chain (C:\Users\sunilk\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
41 verbose stack     at C:\Users\sunilk\AppData\Roaming\npm\node_modules\npm\lib\install\validate-args.js:15:5
41 verbose stack     at C:\Users\sunilk\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:52:35
41 verbose stack     at Array.forEach (native)
41 verbose stack     at C:\Users\sunilk\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:52:11
41 verbose stack     at Array.forEach (native)
41 verbose stack     at asyncMap (C:\Users\sunilk\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:51:8)
42 verbose cwd D:\Camunda\bpmn-js-0.14.1
43 error Windows_NT 6.1.7601
44 error argv "node" "C:\\Users\\sunilk\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "bpmn-js"
45 error node v0.12.7
46 error npm  v3.5.3
47 error code ENOSELF
48 error Refusing to install bpmn-js as a dependency of itself
49 error If you need help, you may report this error at:
49 error     <https://github.com/npm/npm/issues>
50 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
@sunilkumarmaghar Is the `"name"` attribute of your `package.json` set to `"bpmn-js"` by any chance? Have you tried setting it to something else?

**Comment by KenanY** [comment]
Closing as abandoned.

**Comment by gopalakrishnankaruppusamy** [comment]
@KenanY, "name" already set as "bpmn-js", but problem not solved having same issue.
Please help me to resolve this.

**Comment by KenanY** [comment]
@gopalakrishnankaruppusamy As I said above, try changing it to something which isn't the same as any of your dependencies.

**Comment by gopalakrishnankaruppusamy** [comment]
thanks @KenanY, package name set to "bpmnjs" I just removed the '-' now its working fine..,
