### ISSUE TITLE
npm install installs npm linked packages

### ISSUE THREAD

**Issue by fredr** [npm/npm#12216]
Hi!

I have a special build setup where I link some packages that are private git repos, so that when I run npm install I wont have to have the git ssh keys to fetch from that repo since it is already installed.
This has worked fined in npm@2, but when I now tried to upgrade to npm@3, npm install will try to fetch the packages even though they already are linked.

To reproduce the problem I have this minimal repo: https://github.com/fredr/npmlink
Steps to reproduce:

```
$ git clone git@github.com:fredr/npmlink.git
$ cd npmlink
$ cd priv
$ npm link
$ cd ../main
$ npm link priv
$ npm install
```

with npm v2.15.3 this will work fine, but with v3.8.5 this will produce the following error:

```
npm ERR! git fetch -a origin (https://github.com/fredr/private.git) remote: Repository not found.
npm ERR! git fetch -a origin (https://github.com/fredr/private.git) fatal: repository 'https://github.com/fredr/private.git/' not found
npm ERR! git fetch -a origin (git@github.com:fredr/private.git) ERROR: Repository not found.
npm ERR! git fetch -a origin (git@github.com:fredr/private.git) fatal: Could not read from remote repository.
npm ERR! git fetch -a origin (git@github.com:fredr/private.git)
npm ERR! git fetch -a origin (git@github.com:fredr/private.git) Please make sure you have the correct access rights
npm ERR! git fetch -a origin (git@github.com:fredr/private.git) and the repository exists.
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.4.0
npm ERR! npm  v3.8.5
npm ERR! code 128

npm ERR! Command failed: git fetch -a origin
npm ERR! ERROR: Repository not found.
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/fredrik/npmlink/main/npm-debug.log
```

The repository fredr/private does not exist, but this demonstrates the difference in npm install in npm@2 and npm@3

Is this an expected behaviour, or is this a bug?

**Comment by fredr** [comment]
Not sure if this is relevant, but here is the npm-debug.log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'install' ]
2 info using npm@3.8.5
3 info using node@v4.4.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly install normalizeTree
8 silly loadCurrentTree Finishing
9 silly loadIdealTree Starting
10 silly install loadIdealTree
11 silly cloneCurrentTree Starting
12 silly install cloneCurrentTreeToIdealTree
13 silly cloneCurrentTree Finishing
14 silly loadShrinkwrap Starting
15 silly install loadShrinkwrap
16 silly loadShrinkwrap Finishing
17 silly loadAllDepsIntoIdealTree Starting
18 silly install loadAllDepsIntoIdealTree
19 silly fetchOtherPackageData priv@github:fredr/private
20 silly cache add args [ 'priv@github:fredr/private', null ]
21 verbose cache add spec priv@github:fredr/private
22 silly cache add parsed spec Result {
22 silly cache add   raw: 'priv@github:fredr/private',
22 silly cache add   scope: null,
22 silly cache add   name: 'priv',
22 silly cache add   rawSpec: 'github:fredr/private',
22 silly cache add   spec: 'github:fredr/private',
22 silly cache add   type: 'hosted',
22 silly cache add   hosted:
22 silly cache add    { type: 'github',
22 silly cache add      ssh: 'git@github.com:fredr/private.git',
22 silly cache add      sshUrl: 'git+ssh://git@github.com/fredr/private.git',
22 silly cache add      httpsUrl: 'git+https://github.com/fredr/private.git',
22 silly cache add      gitUrl: 'git://github.com/fredr/private.git',
22 silly cache add      shortcut: 'github:fredr/private',
22 silly cache add      directUrl: 'https://raw.githubusercontent.com/fredr/private/master/package.json' } }
23 verbose addRemoteGit caching github:fredr/private
24 verbose addRemoteGit fredr/private is a repository hosted by github
25 silly tryGitProto attempting to clone git://github.com/fredr/private.git
26 silly tryClone cloning fredr/private via git://github.com/fredr/private.git
27 verbose tryClone git-github-com-fredr-private-git-1f24eeb6 not in flight; caching
28 verbose correctMkdir /Users/fredrik/.npm/_git-remotes correctMkdir not in flight; initializing
29 info git [ 'clone',
29 info git   '--template=/Users/fredrik/.npm/_git-remotes/_templates',
29 info git   '--mirror',
29 info git   'git://github.com/fredr/private.git',
29 info git   '/Users/fredrik/.npm/_git-remotes/git-github-com-fredr-private-git-1f24eeb6' ]
30 verbose git clone --template=/Users/fredrik/.npm/_git-remotes/_templates --mirror git://github.com/fredr/private.git /Users/fredrik/.npm/_git-remotes/git-github-com-fredr-private-git-1f24eeb6: Cloning into bare repository '/Users/fredrik/.npm/_git-remotes/git-github-com-fredr-private-git-1f24eeb6'...
30 verbose git clone --template=/Users/fredrik/.npm/_git-remotes/_templates --mirror git://github.com/fredr/private.git /Users/fredrik/.npm/_git-remotes/git-github-com-fredr-private-git-1f24eeb6: fatal: remote error:
30 verbose git clone --template=/Users/fredrik/.npm/_git-remotes/_templates --mirror git://github.com/fredr/private.git /Users/fredrik/.npm/_git-remotes/git-github-com-fredr-private-git-1f24eeb6:   Repository not found.
31 silly tryHTTPS attempting to clone git+https://github.com/fredr/private.git
32 silly tryClone cloning fredr/private via git+https://github.com/fredr/private.git
33 verbose tryClone git-https-github-com-fredr-private-git-261b60ff not in flight; caching
34 verbose correctMkdir /Users/fredrik/.npm/_git-remotes correctMkdir not in flight; initializing
35 info git [ 'config', '--get', 'remote.origin.url' ]
36 silly validateExistingRemote fredr/private remote.origin.url: https://github.com/fredr/private.git
37 verbose validateExistingRemote fredr/private is updating existing cached remote /Users/fredrik/.npm/_git-remotes/git-https-github-com-fredr-private-git-261b60ff
38 info git [ 'fetch', '-a', 'origin' ]
39 error git fetch -a origin (https://github.com/fredr/private.git) remote: Repository not found.
39 error git fetch -a origin (https://github.com/fredr/private.git) fatal: repository 'https://github.com/fredr/private.git/' not found
40 silly trySSH attempting to clone git@github.com:fredr/private.git
41 silly tryClone cloning fredr/private via git@github.com:fredr/private.git
42 verbose tryClone git-github-com-fredr-private-git-c5c7eceb not in flight; caching
43 verbose correctMkdir /Users/fredrik/.npm/_git-remotes correctMkdir not in flight; initializing
44 info git [ 'config', '--get', 'remote.origin.url' ]
45 silly validateExistingRemote fredr/private remote.origin.url: git@github.com:fredr/private.git
46 verbose validateExistingRemote fredr/private is updating existing cached remote /Users/fredrik/.npm/_git-remotes/git-github-com-fredr-private-git-c5c7eceb
47 info git [ 'fetch', '-a', 'origin' ]
48 error git fetch -a origin (git@github.com:fredr/private.git) ERROR: Repository not found.
48 error git fetch -a origin (git@github.com:fredr/private.git) fatal: Could not read from remote repository.
48 error git fetch -a origin (git@github.com:fredr/private.git)
48 error git fetch -a origin (git@github.com:fredr/private.git) Please make sure you have the correct access rights
48 error git fetch -a origin (git@github.com:fredr/private.git) and the repository exists.
49 silly fetchPackageMetaData Error: Command failed: git fetch -a origin
49 silly fetchPackageMetaData ERROR: Repository not found.
49 silly fetchPackageMetaData fatal: Could not read from remote repository.
49 silly fetchPackageMetaData
49 silly fetchPackageMetaData Please make sure you have the correct access rights
49 silly fetchPackageMetaData and the repository exists.
49 silly fetchPackageMetaData
49 silly fetchPackageMetaData     at ChildProcess.exithandler (child_process.js:213:12)
49 silly fetchPackageMetaData     at emitTwo (events.js:87:13)
49 silly fetchPackageMetaData     at ChildProcess.emit (events.js:172:7)
49 silly fetchPackageMetaData     at maybeClose (internal/child_process.js:827:16)
49 silly fetchPackageMetaData     at Socket.<anonymous> (internal/child_process.js:319:11)
49 silly fetchPackageMetaData     at emitOne (events.js:77:13)
49 silly fetchPackageMetaData     at Socket.emit (events.js:169:7)
49 silly fetchPackageMetaData     at Pipe._onclose (net.js:475:12)
49 silly fetchPackageMetaData  error for priv@github:fredr/private { [Error: Command failed: git fetch -a origin
49 silly fetchPackageMetaData ERROR: Repository not found.
49 silly fetchPackageMetaData fatal: Could not read from remote repository.
49 silly fetchPackageMetaData
49 silly fetchPackageMetaData Please make sure you have the correct access rights
49 silly fetchPackageMetaData and the repository exists.
49 silly fetchPackageMetaData ]
49 silly fetchPackageMetaData   killed: false,
49 silly fetchPackageMetaData   code: 128,
49 silly fetchPackageMetaData   signal: null,
49 silly fetchPackageMetaData   cmd: 'git fetch -a origin' }
50 silly rollbackFailedOptional Starting
51 silly rollbackFailedOptional Finishing
52 silly runTopLevelLifecycles Starting
53 silly runTopLevelLifecycles Finishing
54 silly install printInstalled
55 verbose stack Error: Command failed: git fetch -a origin
55 verbose stack ERROR: Repository not found.
55 verbose stack fatal: Could not read from remote repository.
55 verbose stack
55 verbose stack Please make sure you have the correct access rights
55 verbose stack and the repository exists.
55 verbose stack
55 verbose stack     at ChildProcess.exithandler (child_process.js:213:12)
55 verbose stack     at emitTwo (events.js:87:13)
55 verbose stack     at ChildProcess.emit (events.js:172:7)
55 verbose stack     at maybeClose (internal/child_process.js:827:16)
55 verbose stack     at Socket.<anonymous> (internal/child_process.js:319:11)
55 verbose stack     at emitOne (events.js:77:13)
55 verbose stack     at Socket.emit (events.js:169:7)
55 verbose stack     at Pipe._onclose (net.js:475:12)
56 verbose cwd /Users/fredrik/npmlink/main
57 error Darwin 14.5.0
58 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
59 error node v4.4.0
60 error npm  v3.8.5
61 error code 128
62 error Command failed: git fetch -a origin
62 error ERROR: Repository not found.
62 error fatal: Could not read from remote repository.
62 error
62 error Please make sure you have the correct access rights
62 error and the repository exists.
63 error If you need help, you may report this error at:
63 error     <https://github.com/npm/npm/issues>
64 verbose exit [ 1, true ]
```

**Comment by zbjornson** [comment]
@fredr I'm trying to figure out if I've encountered the same issue. In your minimal github repo you're specifying a local dependency in main's package.json. Is that how it is in real life, or do you have it set to a github link? (Looks like it might be based on the log.) If it's a github link, is it set to track #master instead of an explicit tag?

**Comment by fredr** [comment]
@zbjornson `fredr/private` is actually a way of writing a github dependency in package.json, see https://docs.npmjs.com/files/package.json#github-urls

So in the real example I was using the same kind of github url, but to an other private repository.

**Comment by zbjornson** [comment]
Oops, thanks, mistook that as a relative path.

I thought this might only happen when the dep is set to track master or no explicit tag, versus a commit or tag/release, but from trying to test that theory it seems to always happen. Nonetheless, this only recently started happening for us, when we switched a dep from an explicit tag to #master.

@othiym23 is it intended behavior that linked packages are fetched from git and installed?

**Comment by othiym23** [comment]
@zbjornson As I'm no longer a participant on the CLI project, I'm (also) no longer the person to ask. Good luck getting this figured out!
