### ISSUE TITLE
npm publish fails with 403 on a not duplicated package name

### ISSUE THREAD

**Issue by kanekotic** [npm/npm#12225]
Hello i am having problems publising my package with name koteky-lib. I was investigating and most of the cases for 403 seems to be due duplicated names or unpublished packages.

i have tried several commands:
```
npm publish
sudo npm publish
sudo npm publish --tag koteky-lib@0.1.0 --access public
```
I have also changed the name of my NPM package to koteky-library same output to all the cases

npm-debug.log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'publish' ]
2 info using npm@2.15.0
3 info using node@v4.4.2
4 verbose publish [ '.' ]
5 silly cache add args [ '.', null ]
6 verbose cache add spec .
7 silly cache add parsed spec Result {
7 silly cache add   raw: '.',
7 silly cache add   scope: null,
7 silly cache add   name: null,
7 silly cache add   rawSpec: '.',
7 silly cache add   spec: '/home/knek/code/koteky-lib',
7 silly cache add   type: 'directory' }
8 verbose addLocalDirectory /home/knek/.npm/koteky-lib/0.1.0/package.tgz not in flight; packing
9 verbose correctMkdir /home/knek/.npm correctMkdir not in flight; initializing
10 verbose tar pack [ '/home/knek/.npm/koteky-lib/0.1.0/package.tgz',
10 verbose tar pack   '/home/knek/code/koteky-lib' ]
11 verbose tarball /home/knek/.npm/koteky-lib/0.1.0/package.tgz
12 verbose folder /home/knek/code/koteky-lib
13 info prepublish koteky-lib@0.1.0
14 verbose addLocalTarball adding from inside cache /home/knek/.npm/koteky-lib/0.1.0/package.tgz
15 verbose correctMkdir /home/knek/.npm correctMkdir not in flight; initializing
16 silly cache afterAdd koteky-lib@0.1.0
17 verbose afterAdd /home/knek/.npm/koteky-lib/0.1.0/package/package.json not in flight; writing
18 verbose correctMkdir /home/knek/.npm correctMkdir not in flight; initializing
19 verbose afterAdd /home/knek/.npm/koteky-lib/0.1.0/package/package.json written
20 silly publish { name: 'koteky-lib',
20 silly publish   version: '0.1.0',
20 silly publish   description: 'shared library for the koteky project',
20 silly publish   main: 'index.js',
20 silly publish   scripts: { test: 'mocha test' },
20 silly publish   repository:
20 silly publish    { type: 'git',
20 silly publish      url: 'git+https://github.com/Hatisoft/koteky-lib.git' },
20 silly publish   keywords: [ 'koteky', 'social-network' ],
20 silly publish   author: { name: 'kanekotic' },
20 silly publish   licenses:
20 silly publish    [ { type: 'MIT',
20 silly publish        url: 'https://github.com/Hatisoft/koteky-lib/blob/master/LICENSE' } ],
20 silly publish   bugs: { url: 'https://github.com/Hatisoft/koteky-lib/issues' },
20 silly publish   devDependencies:
20 silly publish    { blanket: '^1.2.1',
20 silly publish      chai: '^3.4.1',
20 silly publish      mocha: '^2.3.4',
20 silly publish      sinon: '^1.17.2',
20 silly publish      'sinon-chai': '^2.8.0' },
20 silly publish   readme: '# koteky-lib\n\nLibrary for koteky cross-platform social network manager\n',
20 silly publish   readmeFilename: 'README.md',
20 silly publish   gitHead: '98fb86e4375fc402ab1694755bff8b12c58864d5',
20 silly publish   homepage: 'https://github.com/Hatisoft/koteky-lib#readme',
20 silly publish   _id: 'koteky-lib@0.1.0',
20 silly publish   _shasum: '60c19aa4c3cbe8a5befc1f0d59a6740d7a4f0615',
20 silly publish   _from: '.' }
21 verbose getPublishConfig undefined
22 silly mapToRegistry name koteky-lib
23 silly mapToRegistry using default registry
24 silly mapToRegistry registry http://registry.npm.taobao.org/
25 silly mapToRegistry data Result {
25 silly mapToRegistry   raw: 'koteky-lib',
25 silly mapToRegistry   scope: null,
25 silly mapToRegistry   name: 'koteky-lib',
25 silly mapToRegistry   rawSpec: '',
25 silly mapToRegistry   spec: 'latest',
25 silly mapToRegistry   type: 'tag' }
26 silly mapToRegistry uri http://registry.npm.taobao.org/koteky-lib
27 verbose publish registryBase http://registry.npm.taobao.org/
28 silly publish uploading /home/knek/.npm/koteky-lib/0.1.0/package.tgz
29 verbose request uri http://registry.npm.taobao.org/koteky-lib
30 verbose request sending authorization for write operation
31 info attempt registry request try #1 at 9:04:07 AM
32 verbose request id 8c645e76582cfd4c
33 http request PUT http://registry.npm.taobao.org/koteky-lib
34 http 403 http://registry.npm.taobao.org/koteky-lib
35 verbose headers { server: 'nginx/1.4.6 (Ubuntu)',
35 verbose headers   date: 'Wed, 06 Apr 2016 07:04:07 GMT',
35 verbose headers   'content-type': 'application/json; charset=utf-8',
35 verbose headers   'transfer-encoding': 'chunked',
35 verbose headers   connection: 'keep-alive',
35 verbose headers   'x-readtime': '10',
35 verbose headers   'content-encoding': 'gzip' }
36 verbose request invalidating /home/knek/.npm/registry.npm.taobao.org/koteky-lib on PUT
37 error publish Failed PUT 403
38 verbose stack Error: no_perms Private mode enable, only admin can publish this module: koteky-lib
38 verbose stack     at makeError (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
38 verbose stack     at CachingRegistryClient.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:252:14)
38 verbose stack     at /usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:178:7
38 verbose stack     at Gunzip.onEnd (zlib.js:227:5)
38 verbose stack     at emitNone (events.js:72:20)
38 verbose stack     at Gunzip.emit (events.js:166:7)
38 verbose stack     at endReadableNT (_stream_readable.js:913:12)
38 verbose stack     at nextTickCallbackWith2Args (node.js:442:9)
38 verbose stack     at process._tickCallback (node.js:356:17)
39 verbose statusCode 403
40 verbose pkgid koteky-lib
41 verbose cwd /home/knek/code/koteky-lib
42 error Linux 4.4.0-16-generic
43 error argv "/usr/bin/nodejs" "/usr/bin/npm" "publish"
44 error node v4.4.2
45 error npm  v2.15.0
46 error code E403
47 error no_perms Private mode enable, only admin can publish this module: koteky-lib
48 error If you need help, you may report this error at:
48 error     <https://github.com/npm/npm/issues>
49 verbose exit [ 1, true ]
```

**Comment by kanekotic** [comment]
ok so i have been working now after getting home and solved it, I dont know how the registry get assigned by default but in my ubuntu machine was set to :
```
registry=http://registry.npm.taobao.org/
/* bunch of lines with auth info*/ 
```
I solve the problem by comenting the registry line, and after using the login command:
```
npm login
```
i leave this workaround if anyone on the future encounters the same problem

**Comment by imhazige** [comment]
this really help, thanks.
