### ISSUE TITLE
Missing Script : Start

### ISSUE THREAD

**Issue by naveenila1221** [npm/npm#12270]
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.15.0
3 info using node@v4.4.2
4 verbose stack Error: missing script: start
4 verbose stack     at run (C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:142:19)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:58:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:345:5
4 verbose stack     at handleExists (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:318:20)
4 verbose stack     at FSReqWrap.cb [as oncomplete] (fs.js:212:19)
5 verbose cwd C:\Users\Ila Naveen\phonechange-naveenila
6 error Windows_NT 6.1.7601
7 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
8 error node v4.4.2
9 error npm  v2.15.0
10 error missing script: start
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
@naveenila1221 Do you have a `"start"` script defined in your `package.json`?

**Comment by naveenila1221** [comment]
While loading the project 

C:\Users\Ila Naveen>heroku git:clone -a projectName

warning: You appear to have cloned an empty repository.

This is the warning I am getting. How can I solve the same.

**Comment by KenanY** [comment]
@naveenila1221 That does not look related to `npm` at all.
