### ISSUE TITLE
Deploying my Nodejs App with Heroku

### ISSUE THREAD

**Issue by pago99** [npm/npm#12287]
I have looked up this issue and tried several Node and npm versions but nothing helped.
Please help :)
_
```
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\Programme\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\pago99\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.12.1
3 info using node@v5.10.1
4 verbose stack Error: missing script: start
4 verbose stack     at run (C:\Users\pago99\AppData\Roaming\npm\node_modules\npm\lib\run-script.js:142:19)
4 verbose stack     at C:\Users\pago99\AppData\Roaming\npm\node_modules\npm\lib\run-script.js:58:5
4 verbose stack     at C:\Users\pago99\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:345:5
4 verbose stack     at checkBinReferences_ (C:\Users\pago99\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:309:45)
4 verbose stack     at final (C:\Users\pago99\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:343:3)
4 verbose stack     at then (C:\Users\pago99\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:113:5)
4 verbose stack     at C:\Users\pago99\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:300:12
4 verbose stack     at tryToString (evalmachine.<anonymous>:414:3)
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (evalmachine.<anonymous>:401:12)
5 verbose cwd C:\Users\pago99\bet-cha
6 error Windows_NT 10.0.10586
7 error argv "D:\\Programme\\nodejs\\node.exe" "C:\\Users\\pago99\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
8 error node v5.10.1
9 error npm  v2.12.1
10 error missing script: start
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
```
_

**Comment by pago99** [comment]
Solved it.
The problem was the my Procfile was named with the .txt ending...

**Comment by othiym23** [comment]
Closing as resolved.
