### ISSUE TITLE
i have error deploying a meteor app on ubuntu 15.10

### ISSUE THREAD

**Issue by jockehewh** [npm/npm#12306]
when i try to "npm install" my project it ends like this:

```
> fibers@1.0.5 install /home/2daysou2nights/bundle/programs/server/node_modules/fibers
> node ./build.js

(node) child_process: options.customFds option is deprecated. Use options.stdio instead.
make: Entering directory '/home/2daysou2nights/bundle/programs/server/node_modules/fibers/build'
  CXX(target) Release/obj.target/fibers/src/fibers.o
../src/fibers.cc: In function ‘v8::Handle<v8::Signature> uni::NewSignature(v8::Isolate*, v8::Handle<v8::FunctionTemplate>, int, v8::Handle<v8::FunctionTemplate>*)’:
../src/fibers.cc:132:54: error: no matching function for call to ‘v8::Signature::New(v8::Isolate*&, v8::Handle<v8::FunctionTemplate>&, int&, v8::Handle<v8::FunctionTemplate>*&)’
   return Signature::New(isolate, receiver, argc, argv);
                                                      ^
../src/fibers.cc:132:54: note: candidate is:
In file included from /root/.node-gyp/5.10.1/include/node/node.h:42:0,
                 from ../src/coroutine.h:1,
                 from ../src/fibers.cc:1:
/root/.node-gyp/5.10.1/include/node/v8.h:4674:27: note: static v8::Local<v8::Signature> v8::Signature::New(v8::Isolate*, v8::Local<v8::FunctionTemplate>)
   static Local<Signature> New(
                           ^
/root/.node-gyp/5.10.1/include/node/v8.h:4674:27: note:   candidate expects 2 arguments, 4 provided
../src/fibers.cc: In function ‘void uni::SetResourceConstraints(v8::Isolate*, v8::ResourceConstraints*)’:
../src/fibers.cc:140:3: error: ‘SetResourceConstraints’ is not a member of ‘v8’
   v8::SetResourceConstraints(isolate, constraints);
   ^
../src/fibers.cc:140:3: note: suggested alternative:
../src/fibers.cc:139:7: note:   ‘uni::SetResourceConstraints’
  void SetResourceConstraints(Isolate* isolate, ResourceConstraints* constraints) {
       ^
../src/fibers.cc: In function ‘v8::Handle<v8::Signature> uni::NewSignature(v8::Isolate*, v8::Handle<v8::FunctionTemplate>, int, v8::Handle<v8::FunctionTemplate>*)’:
../src/fibers.cc:133:2: warning: control reaches end of non-void function [-Wreturn-type]
  }
  ^
fibers.target.mk:97: recipe for target 'Release/obj.target/fibers/src/fibers.o' failed
make: *** [Release/obj.target/fibers/src/fibers.o] Error 1
make: Leaving directory '/home/2daysou2nights/bundle/programs/server/node_modules/fibers/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 4.2.0-34-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /home/2daysou2nights/bundle/programs/server/node_modules/fibers
gyp ERR! node -v v5.10.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
Build failed
npm WARN meteor-dev-bundle@0.0.0 No description
npm WARN meteor-dev-bundle@0.0.0 No repository field.
npm WARN meteor-dev-bundle@0.0.0 No license field.
npm ERR! Linux 4.2.0-34-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE

npm ERR! fibers@1.0.5 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fibers@1.0.5 install script 'node ./build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fibers package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fibers
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls fibers
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/2daysou2nights/bundle/programs/server/npm-debug.log

===========================
===========================
===========================

i tried to install fibers alone with npm, it goes fine but i still have the same error, so i tried installing fibers@1.0.5  i receive this message:
root@vps255261:/home/2daysou2nights/bundle/programs/server# npm install -g fibers@1.0.5

> fibers@1.0.5 install /usr/lib/node_modules/fibers
> node ./build.js

(node) child_process: options.customFds option is deprecated. Use options.stdio instead.
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/5.10.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/fibers/.node-gyp"
make: Entering directory '/usr/lib/node_modules/fibers/build'
  CXX(target) Release/obj.target/fibers/src/fibers.o
../src/fibers.cc: In function ‘v8::Handle<v8::Signature> uni::NewSignature(v8::Isolate*, v8::Handle<v8::FunctionTemplate>, int, v8::Handle<v8::FunctionTemplate>*)’:
../src/fibers.cc:132:54: error: no matching function for call to ‘v8::Signature::New(v8::Isolate*&, v8::Handle<v8::FunctionTemplate>&, int&, v8::Handle<v8::FunctionTemplate>*&)’
   return Signature::New(isolate, receiver, argc, argv);
                                                      ^
../src/fibers.cc:132:54: note: candidate is:
In file included from /usr/lib/node_modules/fibers/.node-gyp/5.10.1/include/node/node.h:42:0,
                 from ../src/coroutine.h:1,
                 from ../src/fibers.cc:1:
/usr/lib/node_modules/fibers/.node-gyp/5.10.1/include/node/v8.h:4674:27: note: static v8::Local<v8::Signature> v8::Signature::New(v8::Isolate*, v8::Local<v8::FunctionTemplate>)
   static Local<Signature> New(
                           ^
/usr/lib/node_modules/fibers/.node-gyp/5.10.1/include/node/v8.h:4674:27: note:   candidate expects 2 arguments, 4 provided
../src/fibers.cc: In function ‘void uni::SetResourceConstraints(v8::Isolate*, v8::ResourceConstraints*)’:
../src/fibers.cc:140:3: error: ‘SetResourceConstraints’ is not a member of ‘v8’
   v8::SetResourceConstraints(isolate, constraints);
   ^
../src/fibers.cc:140:3: note: suggested alternative:
../src/fibers.cc:139:7: note:   ‘uni::SetResourceConstraints’
  void SetResourceConstraints(Isolate* isolate, ResourceConstraints* constraints) {
       ^
../src/fibers.cc: In function ‘v8::Handle<v8::Signature> uni::NewSignature(v8::Isolate*, v8::Handle<v8::FunctionTemplate>, int, v8::Handle<v8::FunctionTemplate>*)’:
../src/fibers.cc:133:2: warning: control reaches end of non-void function [-Wreturn-type]
  }
  ^
fibers.target.mk:97: recipe for target 'Release/obj.target/fibers/src/fibers.o' failed
make: *** [Release/obj.target/fibers/src/fibers.o] Error 1
make: Leaving directory '/usr/lib/node_modules/fibers/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 4.2.0-34-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /usr/lib/node_modules/fibers
gyp ERR! node -v v5.10.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
Build failed
npm ERR! Linux 4.2.0-34-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "fibers@1.0.5"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE

npm ERR! fibers@1.0.5 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fibers@1.0.5 install script 'node ./build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fibers package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fibers
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls fibers
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/2daysou2nights/bundle/programs/server/npm-debug.log
```
# 
# 
# 

 following the error messages i saw that some folder are not assigned to my user "root"
root@vps255261:/home/2daysou2nights/bundle/programs/server# ls -la /root/.node-gyp/5.10.1
total 16
drwxr-xr-x 3  502 dialout 4096 Apr 11 12:29 .
drwxr-xr-x 3 root root    4096 Apr 11 12:29 ..
drwxr-xr-x 3  502 dialout 4096 Apr  1 02:35 include
-rw-r--r-- 1 root root       2 Apr 11 12:29 installVersion

 So i chown the folder to root:root but it still the same problem.

any clues on what can resolve that issue ?
Thank you for you support,

Best regards, 

Xavier.

**Comment by marcusjwhelan** [comment]
I have the same issue

**Comment by marcusjwhelan** [comment]
I had a different error and it was working alright and then someone pointed out to try and use this piece of code 

    `sudo npm cache clean -f
sudo npm install -g n
sudo n stable

     sudo ln -sf /usr/local/n/versions/node/<VERSION>/bin/node /usr/bin/node `

And I received this error when sending mup deploy

`-----------------------------------STDERR-----------------------------------
        ld.
        npm ERR! Linux 3.13.0-71-generic
        npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
        npm ERR! node v5.10.1
        npm ERR! npm  v3.8.3
        npm ERR! code ELIFECYCLE

        npm ERR! fibers@1.0.5 install: `node ./build.js`
        npm ERR! Exit status 1
        npm ERR!
        npm ERR! Failed at the fibers@1.0.5 install script 'node ./build.js'.
        npm ERR! Make sure you have the latest version of node.js and npm installed.
        npm ERR! If you do, this is most likely a problem with the fibers package,
        npm ERR! not with npm itself.
        npm ERR! Tell the author that this fails on your system:
        npm ERR!     node ./build.js
        npm ERR! You can get information on how to open an issue for this project with:
        npm ERR!     npm bugs fibers
        npm ERR! Or if that isn't available, you can get their info via:
        npm ERR!     npm owner ls fibers
        npm ERR! There is likely additional logging output above.

        npm ERR! Please include the following file with any support request:
        npm ERR!     /opt/Echo-Project/tmp/bundle/programs/server/npm-debug.log
        -----------------------------------STDOUT-----------------------------------

        > fibers@1.0.5 install /opt/Echo-Project/tmp/bundle/programs/server/node_modules/fibers
        > node ./build.js

        make: Entering directory `/opt/Echo-Project/tmp/bundle/programs/server/node_modules/fibers/build'
          CXX(target) Release/obj.target/fibers/src/fibers.o
        make: Leaving directory `/opt/Echo-Project/tmp/bundle/programs/server/node_modules/fibers/build'
        meteor-dev-bundle@0.0.0 /opt/Echo-Project/tmp/bundle/programs/server
        ├─┬ chalk@0.5.1
        │ ├── ansi-styles@1.1.0
        │ ├── escape-string-regexp@1.0.3
        │ ├─┬ has-ansi@0.1.0
        │ │ └── ansi-regex@0.2.1
        │ ├── strip-ansi@0.3.0
        │ └── supports-color@0.2.0
        ├─┬ eachline@2.3.3
        │ └── type-of@2.0.1
        ├─┬ meteor-promise@0.5.0
        │ └─┬ promise@7.0.4
        │   └── asap@2.0.3
        ├── semver@4.1.0
        ├─┬ source-map-support@0.3.2
        │ └─┬ source-map@0.1.32
        │   └── amdefine@1.0.0
        └── underscore@1.5.2

        ----------------------------------------------------------------------------
`
