### ISSUE TITLE
npm install -g bower -- <title>404 Not Found</title>

### ISSUE THREAD

**Issue by lowell900** [npm/npm#12309]
```
npm ERR! registry error parsing json
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\program files\\nodejs\\node.exe" "C:\\program files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "bower"
npm ERR! node v5.4.0
npm ERR! npm  v3.3.12
```

I run "npm install -g bower", got the following:

```
npm ERR! Unexpected token <
npm ERR! <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
npm ERR! <html><head>
npm ERR! <title>404 Not Found</title>
npm ERR! </head><body>
npm ERR! <h1>Not Found</h1>
npm ERR! <p>The requested URL /bower was not found on this server.</p>
npm ERR! </body></html>
npm ERR! registry error parsing json
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\program files\\nodejs\\node.exe" "C:\\program files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "bower"
npm ERR! node v5.4.0
npm ERR! npm  v3.3.12

npm ERR! Unexpected token <
npm ERR! <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
npm ERR! <html><head>
npm ERR! <title>404 Not Found</title>
npm ERR! </head><body>
npm ERR! <h1>Not Found</h1>
npm ERR! <p>The requested URL /bower was not found on this server.</p>
npm ERR! </body></html>
```

This is npm-log: 

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\program files\\nodejs\\node.exe',
1 verbose cli   'C:\\program files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'bower' ]
2 info using npm@3.3.12
3 info using node@v5.4.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData bower
8 silly fetchNamedPackageData bower
9 silly mapToRegistry name bower
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry http://registry.npmjs.org/
12 silly mapToRegistry uri http://registry.npmjs.org/bower
13 verbose request uri http://registry.npmjs.org/bower
14 verbose request no auth needed
15 info attempt registry request try #1 at 10:19:15 AM
16 verbose request id 1e26d12c84dfcba2
17 http request GET http://registry.npmjs.org/bower
18 http 404 http://registry.npmjs.org/bower
19 verbose bad json <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
19 verbose bad json <html><head>
19 verbose bad json <title>404 Not Found</title>
19 verbose bad json </head><body>
19 verbose bad json <h1>Not Found</h1>
19 verbose bad json <p>The requested URL /bower was not found on this server.</p>
19 verbose bad json </body></html>
20 error registry error parsing json
21 verbose headers { date: 'Mon, 11 Apr 2016 14:19:15 GMT',
21 verbose headers   server: 'Apache/2.2.24 (Unix) DAV/2',
21 verbose headers   'content-length': '203',
21 verbose headers   connection: 'close',
21 verbose headers   'content-type': 'text/html; charset=iso-8859-1' }
22 silly get cb [ 404,
22 silly get   { date: 'Mon, 11 Apr 2016 14:19:15 GMT',
22 silly get     server: 'Apache/2.2.24 (Unix) DAV/2',
22 silly get     'content-length': '203',
22 silly get     connection: 'close',
22 silly get     'content-type': 'text/html; charset=iso-8859-1' } ]
23 silly fetchPackageMetaData SyntaxError: Unexpected token <
23 silly fetchPackageMetaData <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
23 silly fetchPackageMetaData <html><head>
23 silly fetchPackageMetaData <title>404 Not Found</title>
23 silly fetchPackageMetaData </head><body>
23 silly fetchPackageMetaData <h1>Not Found</h1>
23 silly fetchPackageMetaData <p>The requested URL /bower was not found on this server.</p>
23 silly fetchPackageMetaData </body></html>
23 silly fetchPackageMetaData
23 silly fetchPackageMetaData     at Object.parse (native)
23 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (C:\program files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:199:23)
23 silly fetchPackageMetaData     at Request._callback (C:\program files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:172:14)
23 silly fetchPackageMetaData     at Request.self.callback (C:\program files\nodejs\node_modules\npm\node_modules\request\request.js:198:22)
23 silly fetchPackageMetaData     at emitTwo (events.js:87:13)
23 silly fetchPackageMetaData     at Request.emit (events.js:172:7)
23 silly fetchPackageMetaData     at Request.<anonymous> (C:\program files\nodejs\node_modules\npm\node_modules\request\request.js:1082:10)
23 silly fetchPackageMetaData     at emitOne (events.js:82:20)
23 silly fetchPackageMetaData     at Request.emit (events.js:169:7)
23 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (C:\program files\nodejs\node_modules\npm\node_modules\request\request.js:1009:12)
23 silly fetchPackageMetaData  error for bower [SyntaxError: Unexpected token <
23 silly fetchPackageMetaData <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
23 silly fetchPackageMetaData <html><head>
23 silly fetchPackageMetaData <title>404 Not Found</title>
23 silly fetchPackageMetaData </head><body>
23 silly fetchPackageMetaData <h1>Not Found</h1>
23 silly fetchPackageMetaData <p>The requested URL /bower was not found on this server.</p>
23 silly fetchPackageMetaData </body></html>
23 silly fetchPackageMetaData ]
24 silly rollbackFailedOptional Starting
25 silly rollbackFailedOptional Finishing
26 silly runTopLevelLifecycles Starting
27 silly runTopLevelLifecycles Finishing
28 silly install printInstalled
29 verbose stack SyntaxError: Unexpected token <
29 verbose stack <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
29 verbose stack <html><head>
29 verbose stack <title>404 Not Found</title>
29 verbose stack </head><body>
29 verbose stack <h1>Not Found</h1>
29 verbose stack <p>The requested URL /bower was not found on this server.</p>
29 verbose stack </body></html>
29 verbose stack
29 verbose stack     at Object.parse (native)
29 verbose stack     at CachingRegistryClient.<anonymous> (C:\program files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:199:23)
29 verbose stack     at Request._callback (C:\program files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:172:14)
29 verbose stack     at Request.self.callback (C:\program files\nodejs\node_modules\npm\node_modules\request\request.js:198:22)
29 verbose stack     at emitTwo (events.js:87:13)
29 verbose stack     at Request.emit (events.js:172:7)
29 verbose stack     at Request.<anonymous> (C:\program files\nodejs\node_modules\npm\node_modules\request\request.js:1082:10)
29 verbose stack     at emitOne (events.js:82:20)
29 verbose stack     at Request.emit (events.js:169:7)
29 verbose stack     at IncomingMessage.<anonymous> (C:\program files\nodejs\node_modules\npm\node_modules\request\request.js:1009:12)
30 verbose cwd C:\Users\v758597
31 error Windows_NT 6.1.7601
32 error argv "C:\\program files\\nodejs\\node.exe" "C:\\program files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "bower"
33 error node v5.4.0
34 error npm  v3.3.12
35 error Unexpected token <
35 error <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
35 error <html><head>
35 error <title>404 Not Found</title>
35 error </head><body>
35 error <h1>Not Found</h1>
35 error <p>The requested URL /bower was not found on this server.</p>
35 error </body></html>
36 error If you need help, you may report this error at:
36 error     <https://github.com/npm/npm/issues>
37 verbose exit [ 1, true ]
```

**Comment by evanjbowling** [comment]
I found a similar bug that should help: https://github.com/npm/npm/issues/9401

Check your configuration with:

    npm config list

You probably need to set a proxy with:

    npm config set http-proxy http://username:password@ip:port
    npm config set https-proxy http://username:password@ip:port

Let me know if that doesn't work.
