### ISSUE TITLE
npm install -g ts-node --- Getting the below error when i try to install ts-node. Any help Appreciated.

### ISSUE THREAD

**Issue by phanikolla** [npm/npm#12349]
Please find the below npm-debug.log.

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'ts-node' ]
2 info using npm@2.14.12
3 info using node@v4.3.0
4 verbose install initial load of C:\Users\u316853\AppData\Roaming\npm\package.json
5 verbose readDependencies loading dependencies from C:\Users\u316853\AppData\Roaming\npm\package.json
6 silly cache add args [ 'ts-node', null ]
7 verbose cache add spec ts-node
8 silly cache add parsed spec Result {
8 silly cache add   raw: 'ts-node',
8 silly cache add   scope: null,
8 silly cache add   name: 'ts-node',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: 'latest',
8 silly cache add   type: 'tag' }
9 silly addNamed ts-node@latest
10 verbose addNamed "latest" is being treated as a dist-tag for ts-node
11 info addNameTag [ 'ts-node', 'latest' ]
12 silly mapToRegistry name ts-node
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/ts-node
16 verbose addNameTag registry:https://registry.npmjs.org/ts-node not in flight; fetching
17 verbose request uri https://registry.npmjs.org/ts-node
18 verbose request no auth needed
19 info attempt registry request try #1 at 1:31:50 PM
20 verbose request id 557bcb06ca602ec5
21 http request GET https://registry.npmjs.org/ts-node
22 info retry will retry, error on last attempt: Error: write EPROTO
23 info attempt registry request try #2 at 1:32:00 PM
24 http request GET https://registry.npmjs.org/ts-node
25 info retry will retry, error on last attempt: Error: write EPROTO
26 info attempt registry request try #3 at 1:33:00 PM
27 http request GET https://registry.npmjs.org/ts-node
28 verbose stack Error: write EPROTO
28 verbose stack     at Object.exports._errnoException (util.js:870:11)
28 verbose stack     at exports._exceptionWithHostPort (util.js:893:20)
28 verbose stack     at WriteWrap.afterWrite (net.js:763:14)
29 verbose cwd c:\nodejsData
30 error Windows_NT 6.1.7601
31 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "ts-node"
32 error node v4.3.0
33 error npm  v2.14.12
34 error code EPROTO
35 error errno EPROTO
36 error syscall write
37 error write EPROTO
38 error If you need help, you may report this error at:
38 error     <https://github.com/npm/npm/issues>
39 verbose exit [ 1, true ]
```

**Comment by phanikolla** [comment]
Please help me regarding this, i am new to nodejs.
