### ISSUE TITLE
EMISSINGARG error when running "npm update -g"

### ISSUE THREAD

**Issue by ffxsam** [npm/npm#12342]
npm-debug.log below. I'm on Mac OS, 10.11.4.

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/samh/.nvm/versions/node/v5.6.0/bin/node',
1 verbose cli   '/Users/samh/.nvm/versions/node/v5.6.0/bin/npm',
1 verbose cli   'update',
1 verbose cli   '-g' ]
2 info using npm@3.7.5
3 info using node@v5.6.0
4 verbose stack Error: Missing required argument #1
4 verbose stack     at module.exports (/Users/samh/.nvm/versions/node/v5.6.0/lib/node_modules/npm/lib/install/mutate-into-logical-tree.js:12:3)
4 verbose stack     at /Users/samh/.nvm/versions/node/v5.6.0/lib/node_modules/npm/lib/outdated.js:78:5
4 verbose stack     at /Users/samh/.nvm/versions/node/v5.6.0/lib/node_modules/npm/lib/outdated.js:62:20
4 verbose stack     at /Users/samh/.nvm/versions/node/v5.6.0/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:186:9
4 verbose stack     at f (/Users/samh/.nvm/versions/node/v5.6.0/lib/node_modules/npm/node_modules/once/once.js:17:25)
4 verbose stack     at /Users/samh/.nvm/versions/node/v5.6.0/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:152:20
4 verbose stack     at f (/Users/samh/.nvm/versions/node/v5.6.0/lib/node_modules/npm/node_modules/once/once.js:17:25)
4 verbose stack     at then (/Users/samh/.nvm/versions/node/v5.6.0/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:121:22)
4 verbose stack     at /Users/samh/.nvm/versions/node/v5.6.0/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:81:20
4 verbose stack     at fs.js:1653:23
5 verbose cwd /Users/samh
6 error Darwin 15.4.0
7 error argv "/Users/samh/.nvm/versions/node/v5.6.0/bin/node" "/Users/samh/.nvm/versions/node/v5.6.0/bin/npm" "update" "-g"
8 error node v5.6.0
9 error npm  v3.7.5
10 error code EMISSINGARG
11 error typeerror Error: Missing required argument #1
11 error typeerror     at module.exports (/Users/samh/.nvm/versions/node/v5.6.0/lib/node_modules/npm/lib/install/mutate-into-logical-tree.js:12:3)
11 error typeerror     at /Users/samh/.nvm/versions/node/v5.6.0/lib/node_modules/npm/lib/outdated.js:78:5
11 error typeerror     at /Users/samh/.nvm/versions/node/v5.6.0/lib/node_modules/npm/lib/outdated.js:62:20
11 error typeerror     at /Users/samh/.nvm/versions/node/v5.6.0/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:186:9
11 error typeerror     at f (/Users/samh/.nvm/versions/node/v5.6.0/lib/node_modules/npm/node_modules/once/once.js:17:25)
11 error typeerror     at /Users/samh/.nvm/versions/node/v5.6.0/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:152:20
11 error typeerror     at f (/Users/samh/.nvm/versions/node/v5.6.0/lib/node_modules/npm/node_modules/once/once.js:17:25)
11 error typeerror     at then (/Users/samh/.nvm/versions/node/v5.6.0/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:121:22)
11 error typeerror     at /Users/samh/.nvm/versions/node/v5.6.0/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:81:20
11 error typeerror     at fs.js:1653:23
12 error typeerror This is an error with npm itself. Please report this error at:
12 error typeerror     <http://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]
```

**Comment by ffxsam** [comment]
Used nvm to update to 5.10.1, everything is fine now.

**Comment by ffxsam** [comment]
Ok, reopening. This is a major problem.

**Comment by ffxsam** [comment]
Got it. I had a broken symlink in `~/.nvm/versions/node/v5.10.1/lib/node_modules`. But it was something that I definitely did not install globally. It was put there as a result of using `npm link`.

**Comment by stipsan** [comment]
Thanks for sharing @ffxsam, I had no idea I had a broken symlink.

I think it's better if broken symlinks were detected as judging by the error itself I would never had guessed that's the cause of the problem.
