### ISSUE TITLE
unable to install package install react-native-image-picker@latest --save

### ISSUE THREAD

**Issue by ignivanishant** [npm/npm#12350]
```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/mac/.nvm/versions/node/v5.5.0/bin/node',
1 verbose cli   '/Users/mac/.nvm/versions/node/v5.5.0/bin/npm',
1 verbose cli   'install',
1 verbose cli   'react-native-image-picker@latest',
1 verbose cli   '--save' ]
2 info using npm@3.3.12
3 info using node@v5.5.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData react-native-image-picker@latest
8 silly fetchNamedPackageData react-native-image-picker
9 silly mapToRegistry name react-native-image-picker
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry uri https://registry.npmjs.org/react-native-image-picker
13 verbose request uri https://registry.npmjs.org/react-native-image-picker
14 verbose request no auth needed
15 info attempt registry request try #1 at 1:37:09 PM
16 verbose request id e956d6f20aa72793
17 verbose etag "BHTMU6HJG1RN2ZQRPF4TY84BG"
18 http request GET https://registry.npmjs.org/react-native-image-picker
19 http 304 https://registry.npmjs.org/react-native-image-picker
20 verbose headers { date: 'Thu, 14 Apr 2016 08:07:10 GMT',
20 verbose headers   via: '1.1 varnish',
20 verbose headers   'cache-control': 'max-age=300',
20 verbose headers   etag: '"BHTMU6HJG1RN2ZQRPF4TY84BG"',
20 verbose headers   age: '0',
20 verbose headers   connection: 'keep-alive',
20 verbose headers   'x-served-by': 'cache-sin6924-SIN',
20 verbose headers   'x-cache': 'HIT',
20 verbose headers   'x-cache-hits': '1',
20 verbose headers   'x-timer': 'S1460621230.473321,VS0,VE245',
20 verbose headers   vary: 'Accept-Encoding' }
21 silly get cb [ 304,
21 silly get   { date: 'Thu, 14 Apr 2016 08:07:10 GMT',
21 silly get     via: '1.1 varnish',
21 silly get     'cache-control': 'max-age=300',
21 silly get     etag: '"BHTMU6HJG1RN2ZQRPF4TY84BG"',
21 silly get     age: '0',
21 silly get     connection: 'keep-alive',
21 silly get     'x-served-by': 'cache-sin6924-SIN',
21 silly get     'x-cache': 'HIT',
21 silly get     'x-cache-hits': '1',
21 silly get     'x-timer': 'S1460621230.473321,VS0,VE245',
21 silly get     vary: 'Accept-Encoding' } ]
22 verbose etag https://registry.npmjs.org/react-native-image-picker from cache
23 verbose get saving react-native-image-picker to /Users/mac/.npm/registry.npmjs.org/react-native-image-picker/.cache.json
24 silly install normalizeTree
25 silly loadCurrentTree Finishing
26 silly loadIdealTree Starting
27 silly install loadIdealTree
28 silly cloneCurrentTree Starting
29 silly install cloneCurrentTreeToIdealTree
30 silly cloneCurrentTree Finishing
31 silly loadShrinkwrap Starting
32 silly install loadShrinkwrap
33 silly loadShrinkwrap Finishing
34 silly loadAllDepsIntoIdealTree Starting
35 silly install loadAllDepsIntoIdealTree
36 silly rollbackFailedOptional Starting
37 silly rollbackFailedOptional Finishing
38 silly runTopLevelLifecycles Starting
39 silly runTopLevelLifecycles Finishing
40 silly install printInstalled
41 verbose stack Error: Refusing to install react-native-image-picker as a dependency of itself
41 verbose stack     at checkSelf (/Users/mac/.nvm/versions/node/v5.5.0/lib/node_modules/npm/lib/install/validate-args.js:40:14)
41 verbose stack     at Array.<anonymous> (/Users/mac/.nvm/versions/node/v5.5.0/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
41 verbose stack     at LOOP (/Users/mac/.nvm/versions/node/v5.5.0/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
41 verbose stack     at chain (/Users/mac/.nvm/versions/node/v5.5.0/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
41 verbose stack     at /Users/mac/.nvm/versions/node/v5.5.0/lib/node_modules/npm/lib/install/validate-args.js:15:5
41 verbose stack     at /Users/mac/.nvm/versions/node/v5.5.0/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
41 verbose stack     at Array.forEach (native)
41 verbose stack     at /Users/mac/.nvm/versions/node/v5.5.0/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
41 verbose stack     at Array.forEach (native)
41 verbose stack     at asyncMap (/Users/mac/.nvm/versions/node/v5.5.0/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
42 verbose cwd /Users/mac/Documents/Projects/react-native-image-picker
43 error Darwin 14.5.0
44 error argv "/Users/mac/.nvm/versions/node/v5.5.0/bin/node" "/Users/mac/.nvm/versions/node/v5.5.0/bin/npm" "install" "react-native-image-picker@latest" "--save"
45 error node v5.5.0
46 error npm  v3.3.12
47 error code ENOSELF
48 error Refusing to install react-native-image-picker as a dependency of itself
49 error If you need help, you may report this error at:
49 error     <https://github.com/npm/npm/issues>
50 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
@ignivanishant Please ensure that your project directory and the `"name"` field of your `package.json` does **not** share a name with one your dependencies. In this case, `"react-native-image-picker"` is the offending name because `npm` will assume that you are trying to install that module as a dependency of itself (which is, probably, not what you want to do).

**Comment by KenanY** [comment]
Closing since this is intentional `npm` behavior.
