### ISSUE TITLE
Unable to install Express

### ISSUE THREAD

**Issue by saigeetham** [npm/npm#12354]
Hi,

I have tried installing Express in node.js on windows 7 64-bit bot getting error.

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'express' ]
2 info using npm@2.15.1
3 info using node@v4.4.3
4 verbose install initial load of C:\Users\geetha\Desktop\nodejs\node_modules\npm\package.json
5 warn package.json npm@2.15.1 Non-dependency in bundleDependencies: ansi-regex
6 warn package.json npm@2.15.1 Non-dependency in bundleDependencies: imurmurhash
7 verbose installManyTop reading scoped package data from C:\Users\geetha\Desktop\nodejs\node_modules\npm\node_modules\abbrev\package.json
8 verbose installManyTop reading scoped package data from C:\Users\geetha\Desktop\nodejs\node_modules\npm\node_modules\ansi\package.json
9 verbose installManyTop reading scoped package data from C:\Users\geetha\Desktop\nodejs\node_modules\npm\node_modules\ansi-regex\package.json
10 verbose installManyTop reading scoped package data from C:\Users\geetha\Desktop\nodejs\node_modules\npm\node_modules\ansicolors\package.json
11 verbose installManyTop reading scoped package data from C:\Users\geetha\Desktop\nodejs\node_modules\npm\node_modules\ansistyles\package.json
12 verbose installManyTop reading scoped package data from C:\Users\geetha\Desktop\nodejs\node_modules\npm\node_modules\archy\package.json
13 verbose installManyTop reading scoped package data from C:\Users\geetha\Desktop\nodejs\node_modules\npm\node_modules\async-some\package.json
14 verbose installManyTop reading scoped package data from C:\Users\geetha\Desktop\nodejs\node_modules\npm\node_modules\block-stream\package.json
15 verbose installManyTop reading scoped package data from C:\Users\geetha\Desktop\nodejs\node_modules\npm\node_modules\char-spinner\package.json
16 verbose installManyTop reading scoped package data from C:\Users\geetha\Desktop\nodejs\node_modules\npm\node_modules\chmodr\package.json
17 verbose installManyTop reading scoped package data from C:\Users\geetha\Desktop\nodejs\node_modules\npm\node_modules\chownr\package.json
18 verbose installManyTop reading scoped package data from C:\Users\geetha\Desktop\nodejs\node_modules\npm\node_modules\cmd-shim\package.json
19 verbose installManyTop reading scoped package data from C:\Users\geetha\Desktop\nodejs\node_modules\npm\node_modules\columnify\package.json
20 verbose installManyTop reading scoped package data from C:\Users\geetha\Desktop\nodejs\node_modules\npm\node_modules\config-chain\package.json
21 verbose installManyTop reading scoped package data from C:\Users\geetha\Desktop\nodejs\node_modules\npm\node_modules\dezalgo\package.json
22 verbose installManyTop reading scoped package data from C:\Users\geetha\Desktop\nodejs\node_modules\npm\node_modules\editor\package.json
23 verbose installManyTop reading scoped package data from C:\Users\geetha\Desktop\nodejs\node_modules\npm\node_modules\fs-vacuum\package.json
24 verbose installManyTop reading scoped package data from C:\Users\geetha\Desktop\nodejs\node_modules\npm\node_modules\fs-write-stream-atomic\package.json
25 verbose installManyTop reading scoped package data from C:\Users\geetha\Desktop\nodejs\node_modules\npm\node_modules\fstream\package.json
26 verbose installManyTop reading scoped package data from C:\Users\geetha\Desktop\nodejs\node_modules\npm\node_modules\fstream-npm\package.json
27 verbose installManyTop reading scoped package data from C:\Users\geetha\Desktop\nodejs\node_modules\npm\node_modules\github-url-from-git\package.json
28 verbose installManyTop reading scoped package data from C:\Users\geetha\Desktop\nodejs\node_modules\npm\node_modules\github-url-from-username-repo\package.json
29 verbose installManyTop reading scoped package data from C:\Users\geetha\Desktop\nodejs\node_modules\npm\node_modules\glob\package.json
30 verbose installManyTop reading scoped package data from C:\Users\geetha\Desktop\nodejs\node_modules\npm\node_modules\graceful-fs\package.json
31 verbose installManyTop reading scoped package data from C:\Users\geetha\Desktop\nodejs\node_modules\npm\node_modules\hosted-git-info\package.json
32 verbose installManyTop reading scoped package data from C:\Users\geetha\Desktop\nodejs\node_modules\npm\node_modules\imurmurhash\package.json
33 verbose installManyTop reading scoped package data from C:\Users\geetha\Desktop\nodejs\node_modules\npm\node_modules\inflight\package.json
34 verbose installManyTop reading scoped package data from C:\Users\geetha\Desktop\nodejs\node_modules\npm\node_modules\inherits\package.json
35 verbose installManyTop reading scoped package data from C:\Users\geetha\Desktop\nodejs\node_modules\npm\node_modules\ini\package.json
36 verbose installManyTop reading scoped package data from C:\Users\geetha\Desktop\nodejs\node_modules\npm\node_modules\init-package-json\package.json
37 verbose installManyTop reading scoped package data from C:\Users\geetha\Desktop\nodejs\node_modules\npm\node_modules\lockfile\package.json
38 verbose installManyTop reading scoped package data from C:\Users\geetha\Desktop\nodejs\node_modules\npm\node_modules\lru-cache\package.json
39 verbose installManyTop reading scoped package data from C:\Users\geetha\Desktop\nodejs\node_modules\npm\node_modules\minimatch\package.json
40 verbose installManyTop reading scoped package data from C:\Users\geetha\Desktop\nodejs\node_modules\npm\node_modules\mkdirp\package.json
41 verbose installManyTop reading scoped package data from C:\Users\geetha\Desktop\nodejs\node_modules\npm\node_modules\node-gyp\package.json
42 verbose installManyTop reading scoped package data from C:\Users\geetha\Desktop\nodejs\node_modules\npm\node_modules\nopt\package.json
43 verbose installManyTop reading scoped package data from C:\Users\geetha\Desktop\nodejs\node_modules\npm\node_modules\normalize-git-url\package.json
44 verbose installManyTop reading scoped package data from C:\Users\geetha\Desktop\nodejs\node_modules\npm\node_modules\normalize-package-data\package.json
45 verbose installManyTop reading scoped package data from C:\Users\geetha\Desktop\nodejs\node_modules\npm\node_modules\npm-cache-filename\package.json
46 verbose installManyTop reading scoped package data from C:\Users\geetha\Desktop\nodejs\node_modules\npm\node_modules\npm-install-checks\package.json
47 verbose installManyTop reading scoped package data from C:\Users\geetha\Desktop\nodejs\node_modules\npm\node_modules\npm-package-arg\package.json
48 verbose installManyTop reading scoped package data from C:\Users\geetha\Desktop\nodejs\node_modules\npm\node_modules\npm-registry-client\package.json
49 verbose installManyTop reading scoped package data from C:\Users\geetha\Desktop\nodejs\node_modules\npm\node_modules\npm-user-validate\package.json
50 verbose installManyTop reading scoped package data from C:\Users\geetha\Desktop\nodejs\node_modules\npm\node_modules\npmlog\package.json
51 verbose installManyTop reading scoped package data from C:\Users\geetha\Desktop\nodejs\node_modules\npm\node_modules\once\package.json
52 verbose installManyTop reading scoped package data from C:\Users\geetha\Desktop\nodejs\node_modules\npm\node_modules\opener\package.json
53 verbose installManyTop reading scoped package data from C:\Users\geetha\Desktop\nodejs\node_modules\npm\node_modules\osenv\package.json
54 verbose installManyTop reading scoped package data from C:\Users\geetha\Desktop\nodejs\node_modules\npm\node_modules\path-is-inside\package.json
55 verbose installManyTop reading scoped package data from C:\Users\geetha\Desktop\nodejs\node_modules\npm\node_modules\read\package.json
56 verbose installManyTop reading scoped package data from C:\Users\geetha\Desktop\nodejs\node_modules\npm\node_modules\read-installed\package.json
57 verbose installManyTop reading scoped package data from C:\Users\geetha\Desktop\nodejs\node_modules\npm\node_modules\read-package-json\package.json
58 verbose installManyTop reading scoped package data from C:\Users\geetha\Desktop\nodejs\node_modules\npm\node_modules\readable-stream\package.json
59 verbose installManyTop reading scoped package data from C:\Users\geetha\Desktop\nodejs\node_modules\npm\node_modules\realize-package-specifier\package.json
60 verbose installManyTop reading scoped package data from C:\Users\geetha\Desktop\nodejs\node_modules\npm\node_modules\request\package.json
61 verbose installManyTop reading scoped package data from C:\Users\geetha\Desktop\nodejs\node_modules\npm\node_modules\retry\package.json
62 verbose installManyTop reading scoped package data from C:\Users\geetha\Desktop\nodejs\node_modules\npm\node_modules\rimraf\package.json
63 verbose installManyTop reading scoped package data from C:\Users\geetha\Desktop\nodejs\node_modules\npm\node_modules\semver\package.json
64 verbose installManyTop reading scoped package data from C:\Users\geetha\Desktop\nodejs\node_modules\npm\node_modules\sha\package.json
65 verbose installManyTop reading scoped package data from C:\Users\geetha\Desktop\nodejs\node_modules\npm\node_modules\slide\package.json
66 verbose installManyTop reading scoped package data from C:\Users\geetha\Desktop\nodejs\node_modules\npm\node_modules\sorted-object\package.json
67 verbose installManyTop reading scoped package data from C:\Users\geetha\Desktop\nodejs\node_modules\npm\node_modules\spdx-license-ids\package.json
68 verbose installManyTop reading scoped package data from C:\Users\geetha\Desktop\nodejs\node_modules\npm\node_modules\strip-ansi\package.json
69 verbose installManyTop reading scoped package data from C:\Users\geetha\Desktop\nodejs\node_modules\npm\node_modules\tar\package.json
70 verbose installManyTop reading scoped package data from C:\Users\geetha\Desktop\nodejs\node_modules\npm\node_modules\text-table\package.json
71 verbose installManyTop reading scoped package data from C:\Users\geetha\Desktop\nodejs\node_modules\npm\node_modules\uid-number\package.json
72 verbose installManyTop reading scoped package data from C:\Users\geetha\Desktop\nodejs\node_modules\npm\node_modules\umask\package.json
73 verbose installManyTop reading scoped package data from C:\Users\geetha\Desktop\nodejs\node_modules\npm\node_modules\validate-npm-package-license\package.json
74 verbose installManyTop reading scoped package data from C:\Users\geetha\Desktop\nodejs\node_modules\npm\node_modules\validate-npm-package-name\package.json
75 verbose installManyTop reading scoped package data from C:\Users\geetha\Desktop\nodejs\node_modules\npm\node_modules\which\package.json
76 verbose installManyTop reading scoped package data from C:\Users\geetha\Desktop\nodejs\node_modules\npm\node_modules\wrappy\package.json
77 verbose installManyTop reading scoped package data from C:\Users\geetha\Desktop\nodejs\node_modules\npm\node_modules\write-file-atomic\package.json
78 info package.json config-chain@1.1.10 No license field.
79 verbose readDependencies loading dependencies from C:\Users\geetha\Desktop\nodejs\node_modules\npm\package.json
80 silly cache add args [ 'express', null ]
81 verbose cache add spec express
82 silly cache add parsed spec Result {
82 silly cache add   raw: 'express',
82 silly cache add   scope: null,
82 silly cache add   name: 'express',
82 silly cache add   rawSpec: '',
82 silly cache add   spec: 'latest',
82 silly cache add   type: 'tag' }
83 silly addNamed express@latest
84 verbose addNamed "latest" is being treated as a dist-tag for express
85 info addNameTag [ 'express', 'latest' ]
86 silly mapToRegistry name express
87 silly mapToRegistry using default registry
88 silly mapToRegistry registry https://registry.npmjs.org/
89 silly mapToRegistry data Result {
89 silly mapToRegistry   raw: 'express',
89 silly mapToRegistry   scope: null,
89 silly mapToRegistry   name: 'express',
89 silly mapToRegistry   rawSpec: '',
89 silly mapToRegistry   spec: 'latest',
89 silly mapToRegistry   type: 'tag' }
90 silly mapToRegistry uri https://registry.npmjs.org/express
91 verbose addNameTag registry:https://registry.npmjs.org/express not in flight; fetching
92 verbose request uri https://registry.npmjs.org/express
93 verbose request no auth needed
94 info attempt registry request try #1 at 11:39:30 AM
95 verbose request id 31cd143fae8016de
96 http request GET https://registry.npmjs.org/express
97 info retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
98 info attempt registry request try #2 at 11:39:40 AM
99 http request GET https://registry.npmjs.org/express
100 info retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
101 info attempt registry request try #3 at 11:40:40 AM
102 http request GET https://registry.npmjs.org/express
103 verbose stack Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
103 verbose stack     at Object.exports._errnoException (util.js:870:11)
103 verbose stack     at errnoException (dns.js:32:15)
103 verbose stack     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:78:26)
104 verbose cwd C:\Users\geetha\Desktop\nodejs\node_modules\npm
105 error Windows_NT 6.1.7601
106 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "express"
107 error node v4.4.3
108 error npm  v2.15.1
109 error code EAI_AGAIN
110 error errno EAI_AGAIN
111 error syscall getaddrinfo
112 error getaddrinfo EAI_AGAIN registry.npmjs.org:443
113 error If you need help, you may report this error at:
113 error     <https://github.com/npm/npm/issues>
114 verbose exit [ 1, true ]

```

**Comment by brandondewitt** [comment]
Check this out:

#7348
