### ISSUE TITLE
Unable to install ionic and cordova on my windows 8.1 pc

### ISSUE THREAD

**Issue by dhaveed** [npm/npm#12379]
Hey guys please I need help with the installation of the ionic and cordova on my windows 8.1 PC my log file id:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'ionic' ]
2 info using npm@3.8.3
3 info using node@v5.10.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData ionic
8 silly fetchNamedPackageData ionic
9 silly mapToRegistry name ionic
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'ionic',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   name: 'ionic',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/ionic
14 verbose request uri https://registry.npmjs.org/ionic
15 verbose request no auth needed
16 info attempt registry request try #1 at 1:28:32 PM
17 verbose request id 552f88828967a04b
18 http request GET https://registry.npmjs.org/ionic
19 info retry will retry, error on last attempt: Error: connect EAFNOSUPPORT 23.235.43.162:443 - Local (0.0.0.0:1566)
20 info attempt registry request try #2 at 1:28:42 PM
21 http request GET https://registry.npmjs.org/ionic
22 info retry will retry, error on last attempt: Error: connect EAFNOSUPPORT 23.235.43.162:443 - Local (0.0.0.0:1567)
23 info attempt registry request try #3 at 1:29:42 PM
24 http request GET https://registry.npmjs.org/ionic
25 silly fetchPackageMetaData Error: connect EAFNOSUPPORT 185.31.17.162:443 - Local (0.0.0.0:1584)
25 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:890:11)
25 silly fetchPackageMetaData     at exports._exceptionWithHostPort (util.js:913:20)
25 silly fetchPackageMetaData     at connect (net.js:847:16)
25 silly fetchPackageMetaData     at net.js:982:7
25 silly fetchPackageMetaData     at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:63:16)
25 silly fetchPackageMetaData     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:82:10)
25 silly fetchPackageMetaData  error for ionic { [Error: connect EAFNOSUPPORT 185.31.17.162:443 - Local (0.0.0.0:1584)]
25 silly fetchPackageMetaData   code: 'EAFNOSUPPORT',
25 silly fetchPackageMetaData   errno: 'EAFNOSUPPORT',
25 silly fetchPackageMetaData   syscall: 'connect',
25 silly fetchPackageMetaData   address: '185.31.17.162',
25 silly fetchPackageMetaData   port: 443 }
26 silly rollbackFailedOptional Starting
27 silly rollbackFailedOptional Finishing
28 silly runTopLevelLifecycles Starting
29 silly runTopLevelLifecycles Finishing
30 silly install printInstalled
31 verbose stack Error: connect EAFNOSUPPORT 185.31.17.162:443 - Local (0.0.0.0:1584)
31 verbose stack     at Object.exports._errnoException (util.js:890:11)
31 verbose stack     at exports._exceptionWithHostPort (util.js:913:20)
31 verbose stack     at connect (net.js:847:16)
31 verbose stack     at net.js:982:7
31 verbose stack     at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:63:16)
31 verbose stack     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:82:10)
32 verbose cwd C:\Users\david
33 error Windows_NT 6.3.9600
34 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "ionic"
35 error node v5.10.1
36 error npm  v3.8.3
37 error code EAFNOSUPPORT
38 error errno EAFNOSUPPORT
39 error syscall connect
40 error connect EAFNOSUPPORT 185.31.17.162:443 - Local (0.0.0.0:1584)
41 error If you need help, you may report this error at:
41 error     <https://github.com/npm/npm/issues>
42 verbose exit [ 1, true ]
```

.
.
.
.
.
.
while the error i keep getting is : 

```
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "ionic"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! code EAFNOSUPPORT
npm ERR! errno EAFNOSUPPORT
npm ERR! syscall connect

npm ERR! connect EAFNOSUPPORT 23.235.43.162:443 - Local (0.0.0.0:2109)
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Windows\System32\npm-debug.log
```

.
.
I'd be very grateful if i can get a working solution soon.......thanks guys :+1:

**Comment by othiym23** [comment]
How is the network to which this host is connected configured? `EAFNOSUPPORT` is an unusual error code for npm – to me, this implies that the install host is IPv6-only, but that doesn't make a lot of sense, because you would probably need to have some kind of resolver set up even to see the IPv4 address. Either way, this is going to be tough for the CLI team to support, because this isn't something we've seen much of.
