### ISSUE TITLE
Unable to install any npm packages from nexus

### ISSUE THREAD

**Issue by Dibyajyoti14** [npm/npm#12375]
error registry error parsing json

```
28 verbose headers { date: 'Sat, 16 Apr 2016 09:25:21 GMT',
28 verbose headers   server: 'Nexus/2.12.0-01',
28 verbose headers   'x-frame-options': 'SAMEORIGIN',
28 verbose headers   'x-content-type-options': 'nosniff',
28 verbose headers   'accept-ranges': 'bytes',
28 verbose headers   'content-type': 'text/html',
28 verbose headers   connection: 'close',
28 verbose headers   'transfer-encoding': 'chunked' }
29 silly get cb [ 400,
29 silly get   { date: 'Sat, 16 Apr 2016 09:25:21 GMT',
29 silly get     server: 'Nexus/2.12.0-01',
29 silly get     'x-frame-options': 'SAMEORIGIN',
29 silly get     'x-content-type-options': 'nosniff',
29 silly get     'accept-ranges': 'bytes',
29 silly get     'content-type': 'text/html',
29 silly get     connection: 'close',
29 silly get     'transfer-encoding': 'chunked' } ]
30 verbose stack SyntaxError: Unexpected token <
30 verbose stack <html>
30 verbose stack   <head>
30 verbose stack     <title>400 - Schema com.bolyuba.nexus.plugin.npm.service.PackageRoot has no registered handler!</title>
30 verbose stack     <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
30 verbose stack
30 verbose stack     <link rel="icon" type="image/png" href="http://vqtools114/nexus/favicon.png">
30 verbose stack     <!--[if IE]>
30 verbose stack     <link rel="SHORTCUT ICON" href="http://vqtools114/nexus/favicon.ico"/>
30 verbose stack     <![endif]-->
30 verbose stack
30 verbose stack     <link rel="stylesheet" href="http://vqtools114/nexus/static/css/Sonatype-content.css?2.12.0-01" type="text/css" media="screen" title="no title" charset="utf-8">
30 verbose stack   </head>
30 verbose stack   <body>
30 verbose stack     <h1>400 - Schema com.bolyuba.nexus.plugin.npm.service.PackageRoot has no registered handler!</h1>
30 verbose stack     <p>Schema com.bolyuba.nexus.plugin.npm.service.PackageRoot has no registered handler!</p>
30 verbose stack   </body>
30 verbose stack </html>
30 verbose stack
30 verbose stack     at Object.parse (native)
30 verbose stack     at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:199:23)
30 verbose stack     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:172:14)
30 verbose stack     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:198:22)
30 verbose stack     at emitTwo (events.js:87:13)
30 verbose stack     at Request.emit (events.js:172:7)
30 verbose stack     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1082:10)
30 verbose stack     at emitOne (events.js:82:20)
30 verbose stack     at Request.emit (events.js:169:7)
30 verbose stack     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1009:12)
31 verbose cwd C:\Users\dibyajyothi_das
32 error Windows_NT 6.1.7601
33 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "istanbul"
34 error node v4.3.0
35 error npm  v2.14.12
36 error Unexpected token <
36 error <html>
36 error   <head>
36 error     <title>400 - Schema com.bolyuba.nexus.plugin.npm.service.PackageRoot has no registered handler!</title>
36 error     <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
36 error
36 error     <link rel="icon" type="image/png" href="http://vqtools114/nexus/favicon.png">
36 error     <!--[if IE]>
36 error     <link rel="SHORTCUT ICON" href="http://vqtools114/nexus/favicon.ico"/>
36 error     <![endif]-->
36 error
36 error     <link rel="stylesheet" href="http://vqtools114/nexus/static/css/Sonatype-content.css?2.12.0-01" type="text/css" media="screen" title="no title" charset="utf-8">
36 error   </head>
36 error   <body>
36 error     <h1>400 - Schema com.bolyuba.nexus.plugin.npm.service.PackageRoot has no registered handler!</h1>
36 error     <p>Schema com.bolyuba.nexus.plugin.npm.service.PackageRoot has no registered handler!</p>
36 error   </body>
36 error </html>
37 error If you need help, you may report this error at:
37 error     <https://github.com/npm/npm/issues>
38 verbose exit [ 1, true ]
```

**Comment by othiym23** [comment]
Is your registry URL correct? (That's either the argument to `--registry=` on the command line, or the value you get back from `npm config get registry`.) Keep in mind that trailing slashes are important for the registry URL, as is using the _complete_ path to the registry endpoint. Aside from that, check with your local Nexus admins, because this is something over which the CLI team doesn't have a lot of knowledge.

**Comment by Dibyajyoti14** [comment]
yes ,Its correct
