### ISSUE TITLE
Unable to install Hapi

### ISSUE THREAD

**Issue by imsarvesh** [npm/npm#12409]
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\skesharwani\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'hapi',
1 verbose cli   '--save' ]
2 info using npm@3.8.6
3 info using node@v4.2.3
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData hapi
8 silly fetchNamedPackageData hapi
9 silly mapToRegistry name hapi
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'hapi',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   name: 'hapi',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/hapi
14 verbose request uri https://registry.npmjs.org/hapi
15 verbose request no auth needed
16 info attempt registry request try #1 at 7:00:43 PM
17 verbose request id 899ef1dc9ead5c5c
18 verbose etag "11J8DL6KUK4ADF3RHAYXXH8QG"
19 http request GET https://registry.npmjs.org/hapi
20 http 304 https://registry.npmjs.org/hapi
21 verbose headers { date: 'Tue, 19 Apr 2016 13:30:44 GMT',
21 verbose headers   via: '1.1 varnish',
21 verbose headers   'cache-control': 'max-age=300',
21 verbose headers   etag: '"11J8DL6KUK4ADF3RHAYXXH8QG"',
21 verbose headers   age: '0',
21 verbose headers   connection: 'keep-alive',
21 verbose headers   'x-served-by': 'cache-dfw1844-DFW',
21 verbose headers   'x-cache': 'HIT',
21 verbose headers   'x-cache-hits': '1',
21 verbose headers   'x-timer': 'S1461072644.370858,VS0,VE63',
21 verbose headers   vary: 'Accept-Encoding' }
22 silly get cb [ 304,
22 silly get   { date: 'Tue, 19 Apr 2016 13:30:44 GMT',
22 silly get     via: '1.1 varnish',
22 silly get     'cache-control': 'max-age=300',
22 silly get     etag: '"11J8DL6KUK4ADF3RHAYXXH8QG"',
22 silly get     age: '0',
22 silly get     connection: 'keep-alive',
22 silly get     'x-served-by': 'cache-dfw1844-DFW',
22 silly get     'x-cache': 'HIT',
22 silly get     'x-cache-hits': '1',
22 silly get     'x-timer': 'S1461072644.370858,VS0,VE63',
22 silly get     vary: 'Accept-Encoding' } ]
23 verbose etag https://registry.npmjs.org/hapi from cache
24 verbose get saving hapi to C:\Users\skesharwani\AppData\Roaming\npm-cache\registry.npmjs.org\hapi\.cache.json
25 verbose correctMkdir C:\Users\skesharwani\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
26 silly install normalizeTree
27 silly loadCurrentTree Finishing
28 silly loadIdealTree Starting
29 silly install loadIdealTree
30 silly cloneCurrentTree Starting
31 silly install cloneCurrentTreeToIdealTree
32 silly cloneCurrentTree Finishing
33 silly loadShrinkwrap Starting
34 silly install loadShrinkwrap
35 silly loadShrinkwrap Finishing
36 silly loadAllDepsIntoIdealTree Starting
37 silly install loadAllDepsIntoIdealTree
38 silly rollbackFailedOptional Starting
39 silly rollbackFailedOptional Finishing
40 silly runTopLevelLifecycles Starting
41 silly runTopLevelLifecycles Finishing
42 silly install printInstalled
43 verbose stack Error: Refusing to install hapi as a dependency of itself
43 verbose stack     at checkSelf (C:\Users\skesharwani\AppData\Roaming\npm\node_modules\npm\lib\install\validate-args.js:53:14)
43 verbose stack     at Array.<anonymous> (C:\Users\skesharwani\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
43 verbose stack     at LOOP (C:\Users\skesharwani\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
43 verbose stack     at chain (C:\Users\skesharwani\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
43 verbose stack     at C:\Users\skesharwani\AppData\Roaming\npm\node_modules\npm\lib\install\validate-args.js:16:5
43 verbose stack     at C:\Users\skesharwani\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:52:35
43 verbose stack     at Array.forEach (native)
43 verbose stack     at C:\Users\skesharwani\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:52:11
43 verbose stack     at Array.forEach (native)
43 verbose stack     at asyncMap (C:\Users\skesharwani\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:51:8)
44 verbose cwd C:\Users\skesharwani\Projects\hapi
45 error Windows_NT 6.3.9600
46 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\skesharwani\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "hapi" "--save"
47 error node v4.2.3
48 error npm  v3.8.6
49 error code ENOSELF
50 error Refusing to install hapi as a dependency of itself
51 error If you need help, you may report this error at:
51 error     <https://github.com/npm/npm/issues>
52 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
@imsarvesh Could you try renaming this directory to something other than `hapi`?: C:\Users\skesharwani\Projects\hapi

**Comment by imsarvesh** [comment]
Issue fixed. You are awesome. :-)

**Comment by othiym23** [comment]
Closing as resolved!
