### ISSUE TITLE
No compatible version found, cannot update NPM

### ISSUE THREAD

**Issue by nmggithub** [npm/npm#12403]
I was trying to install jsdom and got this:
```
npm http GET https://registry.npmjs.org/jsdom
npm http 304 https://registry.npmjs.org/jsdom
npm http GET https://registry.npmjs.org/abab
npm http GET https://registry.npmjs.org/acorn
npm http GET https://registry.npmjs.org/acorn-globals
npm http GET https://registry.npmjs.org/array-equal
npm http GET https://registry.npmjs.org/cssstyle
npm http GET https://registry.npmjs.org/nwmatcher
npm http GET https://registry.npmjs.org/cssom
npm http GET https://registry.npmjs.org/escodegen
npm http GET https://registry.npmjs.org/parse5
npm http GET https://registry.npmjs.org/sax
npm http GET https://registry.npmjs.org/symbol-tree
npm http GET https://registry.npmjs.org/request
npm http GET https://registry.npmjs.org/webidl-conversions
npm http GET https://registry.npmjs.org/tough-cookie
npm http GET https://registry.npmjs.org/xml-name-validator
npm http GET https://registry.npmjs.org/whatwg-url
npm http 304 https://registry.npmjs.org/acorn
npm http 304 https://registry.npmjs.org/abab
npm ERR! Error: No compatible version found: acorn@'^2.4.0'
npm ERR! Valid install targets:
npm ERR! ["0.0.1","0.1.0","0.2.0","0.3.0","0.3.1","0.4.0","0.4.2","0.5.0","0.6.0","0.7.0","0.8.0","0.9.0","0.10.0","0.11.0","0.12.0","1.0.0","1.0.1","1.0.3","1.1.0","1.2.0","2.0.0","1.2.1","2.0.1","1.2.2","2.0.4","2.1.0","2.2.0","2.3.0","2.4.0","2.5.0","2.5.2","2.6.0","2.6.2","2.6.4","2.7.0","3.0.0","3.0.2","3.0.4","3.1.0"]
npm ERR!     at installTargetsError (/usr/local/lib/node_modules/npm/lib/cache.js:563:10)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:478:10
npm ERR!     at saved (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:218:7
npm ERR!     at Object.oncomplete (fs.js:297:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>
```

```
npm ERR! System Linux 4.2.0-35-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "i" "jsdom"
npm ERR! cwd [projectdir]
npm ERR! node -v v0.8.14
npm ERR! npm -v 1.1.65
npm http 304 https://registry.npmjs.org/acorn-globals
npm http 304 https://registry.npmjs.org/cssstyle
npm http 304 https://registry.npmjs.org/parse5
npm http 304 https://registry.npmjs.org/nwmatcher
npm http 304 https://registry.npmjs.org/cssom
npm http 304 https://registry.npmjs.org/escodegen
npm http 304 https://registry.npmjs.org/symbol-tree
npm http 304 https://registry.npmjs.org/tough-cookie
npm http 304 https://registry.npmjs.org/webidl-conversions
npm http 200 https://registry.npmjs.org/sax
npm http 304 https://registry.npmjs.org/array-equal
npm http 304 https://registry.npmjs.org/xml-name-validator
npm http 200 https://registry.npmjs.org/request
npm http 304 https://registry.npmjs.org/whatwg-url
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     [projectdir]/npm-debug.log
npm ERR! not ok code 0
```

Running `npm install -g npm` gets me:
```
npm http GET https://registry.npmjs.org/npm
npm http 200 https://registry.npmjs.org/npm
npm http GET https://registry.npmjs.org/npm/-/npm-3.8.6.tgz
npm http 200 https://registry.npmjs.org/npm/-/npm-3.8.6.tgz
npm ERR! tar pack Error reading /home/[username]/tmp/npm-25817/1461014482381-0.561566193588078/package
npm ERR! TypeError: Cannot call method 'filter' of undefined
npm ERR!     at Packer.IgnoreReader.addIgnoreRules (/usr/local/lib/node_modules/npm/node_modules/fstream-npm/node_modules/fstream-ignore/ignore.js:148:13)
npm ERR!     at Packer.IgnoreReader.addIgnoreFile (/usr/local/lib/node_modules/npm/node_modules/fstream-npm/node_modules/fstream-ignore/ignore.js:133:10)
npm ERR!     at fs.readFile (fs.js:176:14)
npm ERR!     at fs.close (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:90:5)
npm ERR!     at Object.oncomplete (fs.js:297:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>
```

```
npm ERR! System Linux 4.2.0-35-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "npm"
npm ERR! cwd [projectdir]
npm ERR! node -v v0.8.14
npm ERR! npm -v 1.1.65
npm ERR! type non_object_property_call
npm ERR! addLocalDirectory Could not pack "/home/[username]/tmp/npm-25817/1461014482381-0.561566193588078/package" to "/home/[username]/.npm/npm/3.8.6/package.tgz"
npm ERR! SyntaxError: Unexpected end of input
npm ERR!     at Object.parse (native)
npm ERR!     at Packer.readRules (/usr/local/lib/node_modules/npm/node_modules/fstream-npm/fstream-npm.js:189:33)
npm ERR!     at Packer.IgnoreReader.addIgnoreFile (/usr/local/lib/node_modules/npm/node_modules/fstream-npm/node_modules/fstream-ignore/ignore.js:132:22)
npm ERR!     at fs.readFile (fs.js:176:14)
npm ERR!     at fs.close (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:90:5)
npm ERR!     at Object.oncomplete (fs.js:297:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>
```
```
npm ERR! System Linux 4.2.0-35-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "npm"
npm ERR! cwd [projectdir]
npm ERR! node -v v0.8.14
npm ERR! npm -v 1.1.65
npm ERR! file /home/[username]/tmp/npm-25817/1461014482381-0.561566193588078/package/node_modules/read-package-tree/test/fixtures/empty/node_modules/foo/package.json
npm ERR! path /home/[username]/tmp/npm-25817/1461014482381-0.561566193588078/package/node_modules/read-package-tree/test/fixtures/empty/node_modules/foo
npm ERR! type unexpected_eos
npm ERR! fstream_path /home/[username]/tmp/npm-25817/1461014482381-0.561566193588078/package/node_modules/read-package-tree/test/fixtures/empty/node_modules/foo
npm ERR! fstream_type Directory
npm ERR! fstream_class Packer
npm ERR! fstream_stack Packer.readRules (/usr/local/lib/node_modules/npm/node_modules/fstream-npm/fstream-npm.js:192:10)
npm ERR! fstream_stack Packer.IgnoreReader.addIgnoreFile (/usr/local/lib/node_modules/npm/node_modules/fstream-npm/node_modules/fstream-ignore/ignore.js:132:22)
npm ERR! fstream_stack fs.readFile (fs.js:176:14)
npm ERR! fstream_stack fs.close (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:90:5)
npm ERR! fstream_stack Object.oncomplete (fs.js:297:15)
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     [projectdir]/npm-debug.log
npm ERR! not ok code 0
```

**Comment by KenanY** [comment]
@nmggithub How about `npm install -g npm@1.4`?

**Comment by nmggithub** [comment]
I have resolved it through other means. I downloaded and ran the npm install script and then, because of my project, I deleted node and installed v5. Thank you anyway.
