### ISSUE TITLE
NPM unpublish got 400

### ISSUE THREAD

**Issue by ORESoftware** [npm/npm#12404]
I am trying to delete this repo, but I get a 400 :(

https://www.npmjs.com/package/baymax-logger

npm whoami at the command line yields
oresoftware

so I am the right account holder

so I try the unpublish command

```
CACSVML-16845:suman amills001c$ npm unpublish --force baymax-logger
npm WARN using --force I sure hope you know what you are doing.
npm ERR! Darwin 15.0.0
npm ERR! argv "/Users/amills001c/.nvm/versions/node/v4.3.2/bin/node" "/Users/amills001c/.nvm/versions/node/v4.3.2/bin/npm" "unpublish" "--force" "baymax-logger"
npm ERR! node v4.3.2
npm ERR! npm  v3.8.1
npm ERR! code E400

npm ERR! Registry returned 400 for DELETE on https://registry.npmjs.org/baymax-logger/-rev/4-b349c678c4226c2c0b0071530f97a17f
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/amills001c/WebstormProjects/oresoftware/suman/npm-debug.log
```

here is the npm-debug.log

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/amills001c/.nvm/versions/node/v4.3.2/bin/node',
1 verbose cli   '/Users/amills001c/.nvm/versions/node/v4.3.2/bin/npm',
1 verbose cli   'unpublish',
1 verbose cli   '--force',
1 verbose cli   'baymax-logger' ]
2 info using npm@3.8.1
3 info using node@v4.3.2
4 warn using --force I sure hope you know what you are doing.
5 silly unpublish args[0] baymax-logger
6 silly unpublish thing Result {
6 silly unpublish   raw: 'baymax-logger',
6 silly unpublish   scope: null,
6 silly unpublish   name: 'baymax-logger',
6 silly unpublish   rawSpec: '',
6 silly unpublish   spec: 'latest',
6 silly unpublish   type: 'tag' }
7 verbose getPublishConfig null
8 silly ls normalized baymax-logger
9 silly gentlyRm /Users/amills001c/.npm/baymax-logger is being purged
10 verbose gentlyRm don't care about contents; nuking /Users/amills001c/.npm/baymax-logger
11 silly mapToRegistry name baymax-logger
12 silly mapToRegistry using default registry
13 silly mapToRegistry registry https://registry.npmjs.org/
14 silly mapToRegistry uri https://registry.npmjs.org/baymax-logger
15 verbose get GET as part of write; not caching result
16 verbose request uri https://registry.npmjs.org/baymax-logger?write=true
17 verbose request no auth needed
18 info attempt registry request try #1 at 4:28:19 PM
19 verbose request using bearer token for auth
20 verbose request id 59bef6ceaf56748c
21 http request GET https://registry.npmjs.org/baymax-logger?write=true
22 http 200 https://registry.npmjs.org/baymax-logger?write=true
23 verbose headers { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
23 verbose headers   etag: '"4KS6F5TTUZIS0Q2M8DOXVJ1WR"',
23 verbose headers   'content-type': 'application/json',
23 verbose headers   'content-encoding': 'gzip',
23 verbose headers   'cache-control': 'max-age=0',
23 verbose headers   'transfer-encoding': 'chunked',
23 verbose headers   'accept-ranges': 'bytes',
23 verbose headers   date: 'Mon, 18 Apr 2016 23:28:20 GMT',
23 verbose headers   via: '1.1 varnish',
23 verbose headers   connection: 'keep-alive',
23 verbose headers   'x-served-by': 'cache-sjc3130-SJC',
23 verbose headers   'x-cache': 'MISS',
23 verbose headers   'x-cache-hits': '0',
23 verbose headers   'x-timer': 'S1461022100.320861,VS0,VE111',
23 verbose headers   vary: 'Accept-Encoding' }
24 silly get cb [ 200,
24 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
24 silly get     etag: '"4KS6F5TTUZIS0Q2M8DOXVJ1WR"',
24 silly get     'content-type': 'application/json',
24 silly get     'content-encoding': 'gzip',
24 silly get     'cache-control': 'max-age=0',
24 silly get     'transfer-encoding': 'chunked',
24 silly get     'accept-ranges': 'bytes',
24 silly get     date: 'Mon, 18 Apr 2016 23:28:20 GMT',
24 silly get     via: '1.1 varnish',
24 silly get     connection: 'keep-alive',
24 silly get     'x-served-by': 'cache-sjc3130-SJC',
24 silly get     'x-cache': 'MISS',
24 silly get     'x-cache-hits': '0',
24 silly get     'x-timer': 'S1461022100.320861,VS0,VE111',
24 silly get     vary: 'Accept-Encoding' } ]
25 verbose get saving baymax-logger to /Users/amills001c/.npm/registry.npmjs.org/baymax-logger_3Fwrite_3Dtrue/.cache.json
26 verbose correctMkdir /Users/amills001c/.npm correctMkdir not in flight; initializing
27 info unpublish No version specified, removing all
28 verbose request uri https://registry.npmjs.org/baymax-logger/-rev/4-b349c678c4226c2c0b0071530f97a17f
29 verbose request sending authorization for write operation
30 info attempt registry request try #1 at 4:28:19 PM
31 verbose request using bearer token for auth
32 http request DELETE https://registry.npmjs.org/baymax-logger/-rev/4-b349c678c4226c2c0b0071530f97a17f
33 http 400 https://registry.npmjs.org/baymax-logger/-rev/4-b349c678c4226c2c0b0071530f97a17f
34 verbose headers { 'content-type': 'application/json',
34 verbose headers   'cache-control': 'max-age=300',
34 verbose headers   'content-length': '17',
34 verbose headers   'accept-ranges': 'bytes',
34 verbose headers   date: 'Mon, 18 Apr 2016 23:28:20 GMT',
34 verbose headers   via: '1.1 varnish',
34 verbose headers   connection: 'keep-alive',
34 verbose headers   'x-served-by': 'cache-sjc3121-SJC',
34 verbose headers   'x-cache': 'MISS',
34 verbose headers   'x-cache-hits': '0',
34 verbose headers   'x-timer': 'S1461022100.491229,VS0,VE153',
34 verbose headers   vary: 'Accept-Encoding' }
35 verbose request invalidating /Users/amills001c/.npm/registry.npmjs.org/baymax-logger on DELETE
36 verbose stack Error: Registry returned 400 for DELETE on https://registry.npmjs.org/baymax-logger/-rev/4-b349c678c4226c2c0b0071530f97a17f
36 verbose stack     at makeError (/Users/amills001c/.nvm/versions/node/v4.3.2/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
36 verbose stack     at CachingRegistryClient.<anonymous> (/Users/amills001c/.nvm/versions/node/v4.3.2/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:242:14)
36 verbose stack     at Request._callback (/Users/amills001c/.nvm/versions/node/v4.3.2/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
36 verbose stack     at Request.self.callback (/Users/amills001c/.nvm/versions/node/v4.3.2/lib/node_modules/npm/node_modules/request/request.js:199:22)
36 verbose stack     at emitTwo (events.js:87:13)
36 verbose stack     at Request.emit (events.js:172:7)
36 verbose stack     at Request.<anonymous> (/Users/amills001c/.nvm/versions/node/v4.3.2/lib/node_modules/npm/node_modules/request/request.js:1036:10)
36 verbose stack     at emitOne (events.js:82:20)
36 verbose stack     at Request.emit (events.js:169:7)
36 verbose stack     at IncomingMessage.<anonymous> (/Users/amills001c/.nvm/versions/node/v4.3.2/lib/node_modules/npm/node_modules/request/request.js:963:12)
37 verbose statusCode 400
38 verbose pkgid baymax-logger
39 verbose cwd /Users/amills001c/WebstormProjects/oresoftware/suman
40 error Darwin 15.0.0
41 error argv "/Users/amills001c/.nvm/versions/node/v4.3.2/bin/node" "/Users/amills001c/.nvm/versions/node/v4.3.2/bin/npm" "unpublish" "--force" "baymax-logger"
42 error node v4.3.2
43 error npm  v3.8.1
44 error code E400
45 error Registry returned 400 for DELETE on https://registry.npmjs.org/baymax-logger/-rev/4-b349c678c4226c2c0b0071530f97a17f
46 error If you need help, you may report this error at:
46 error     <https://github.com/npm/npm/issues>
47 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
@ORESoftware Check out http://blog.npmjs.org/post/141905368000/changes-to-npms-unpublish-policy

**Comment by ORESoftware** [comment]
thx

**Comment by othiym23** [comment]
Closing as resolved.

**Comment by a7madgamal** [comment]
Had the same problem, I just have 2 comments
1- I respect this policy as it protects us as developers. However, I think if a package has 0 downloads it should be removed just fine (this issue might not be the best place to discuss this, if not, please tell me where is the best one)

2- this is the input we get: 
`
npm WARN using --force I sure hope you know what you are doing.
npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/mido/.nvm/versions/node/v6.3.0/bin/node" "/Users/mido/.nvm/versions/node/v6.3.0/bin/npm" "unpublish" "GettyEmbeddy" "--force"
npm ERR! node v6.3.0

npm ERR! npm  v3.10.3
npm ERR! code E400

npm ERR! Registry returned 400 for DELETE on http://registry.npmjs.org/GettyEmbeddy/-rev/6-847e00a5fb87f4bc157a50c27d4b82cb
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mido/projects/tickaroo/getty-embeddy/npm-debug.log
`
this does NOT look like a policy thing, it needs to be clearer maybe even with a link to this http://blog.npmjs.org/post/141905368000/changes-to-npms-unpublish-policy
so that developers wouldn't have to look around for possible solutions to this 400 error, google until they find this issue only to find out it's a feature not a bug :)

**Comment by eladnava** [comment]
@a7madgamal Agreed. Just got the same 400 error as well. Please make the error contain a link to the unpublish policy and a more helpful message. 👍

**Comment by yin-fan** [comment]
I met the same problem with you

**Comment by legodude17** [comment]
@eladnava, how about you open up a PR?

**Comment by eladnava** [comment]
@legodude17 Would love to!

Would it be better to fix it upstream in [npm-registry-client/lib/unpublish.js](https://github.com/npm/npm-registry-client/blob/debec76884db8092c2c7a21ab5b4ed083f8ce2c9/lib/unpublish.js#L14) or in [npm/lib/unpublish.js](https://github.com/npm/npm/blob/d081cc6c8d73f2aa698aab36605377c95e916224/lib/unpublish.js#L115)?

**Comment by legodude17** [comment]
You could either put it in npm/lib/unpublish.js or in nom/lib/utils/error-handler.js. I think the former is better.

**Comment by othiym23** [comment]
This is a message that comes from the registry – a 400 response code is a generic way of indicating an invalid request, so changing the messaging here requires either pattern-matching on the response coming from a registry (which may not be `registry.npmjs.org`), or changing the server response. I suggest moving this issue to [`npm/registry`](https://github.com/npm/registry/issues) as a result.

**Comment by eladnava** [comment]
@othiym23 Thanks for your input. Opened an issue:
https://github.com/npm/registry/issues/89

**Comment by legodude17** [comment]
So should this one be closed?

**Comment by fanyer** [comment]
If you are gonna delete your library totally, its's a advice tp contact npm Inc. For other cases ,you can delete the old after you publish a new version.

**Comment by Mark24Code** [comment]
I met the same problem with you

**Comment by davidpelayo** [comment]
Same here. Does it have to do with not having public the github repo any longer?

**Comment by joaomlneto** [comment]
Same here.
