### ISSUE TITLE
NPM Installing Keystone JS " Error: Cannot find module './lib/cookies' "

### ISSUE THREAD

**Issue by lxjffrs** [npm/npm#12410]
```
Macintosh-2:/ admin$ sudo npm install -g generator-keystone
Password:
Error: Cannot find module './lib/cookies'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/index.js:18:29)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "generator-keystone"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module './lib/cookies'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
Macintosh-2:/ admin$ 
```

I'm seeing this error repeatedly while trying to install Keystone JS through NPM, this is the first package I've tried to install using NPM.  Can anyone shed any light as to what the issue is?

**Comment by ihorskyi** [comment]
@lxjffrs this is the right place to ask this question https://github.com/keystonejs/generator-keystone/issues

**Comment by lxjffrs** [comment]
Sorry, I have posted there now and will delete this thread.
