### ISSUE TITLE
Cannot install over previous version when bin script changes

### ISSUE THREAD

**Issue by mearns** [npm/npm#12414]
I had an old version of my package installed globally which specified a particular bin script in package.json. In a new version, I updated the same bin script to point to a new path and when trying to install (globally) over the existing version, I get the following error about unlinking my bin script:

```
/usr/local/nodejs-binary-5.6.0/lib
└── (empty)

npm ERR! Linux 3.13.0-24-generic
npm ERR! argv "/usr/local/nodejs-binary-5.6.0/bin/node" "/usr/local/bin/npm" "install" "-global" "--registry" "http://artifactory.redacted.example.com/artifactory/api/npm/npm-virtual/
[npm-debug.zip](https://github.com/npm/npm/files/226714/npm-debug.zip)
" "my-package-name@0.22.0"
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0
npm ERR! path /usr/local/nodejs-binary-5.6.0/bin/my-bin-name
npm ERR! code EEXIST

npm ERR! Refusing to delete /usr/local/nodejs-binary-5.6.0/bin/my-bin-name: ../lib/node_modules/my-bin-name/dist/cli.js symlink target is not controlled by npm /usr/local/nodejs-binary-5.6.0
npm ERR! File exists: /usr/local/nodejs-binary-5.6.0/bin/my-bin-name
npm ERR! Move it away, and try again.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/bmearns/npm-debug.log
npm ERR! code 1
```

I can manually resolve this by unlinking the specified file `/usr/local/nodejs-binary-5.6.0/bin/my-bin-name` as described in the error message, but this doesn't work when installing the package with configuration management (in my case, chef). More to the point, since npm is the one that created this link in the first place, it should be able to remove it.

The old version specified the following in package.json:

``` json
"bin": {
    "my-bin-name": "./dist/cli.js"
  },
```

The new version changed this to point to a new location:

``` json
"bin": {
    "my-bin-name": "./dist/server/cli.js"
  },
```

The `npm-debug.log` file is attached, here is what appears to be the relevant portion:

```
60601 silly build my-package-name@0.22.0
60602 info linkStuff my-package-name@0.22.0
60603 silly linkStuff my-package-name@0.22.0 has /usr/local/nodejs-binary-5.6.0/lib/node_modules as its parent node_modules
60604 silly linkStuff my-package-name@0.22.0 is part of a global install
60605 silly linkStuff my-package-name@0.22.0 is installed into a global node_modules
60606 silly linkStuff my-package-name@0.22.0 is installed into the top-level global node_modules
60607 verbose linkBins my-package-name@0.22.0
60608 verbose link bins [ { 'my-bin-name': './dist/server/cli.js' },
60608 verbose link bins   '/usr/local/nodejs-binary-5.6.0/bin',
60608 verbose link bins   true ]
60609 verbose linkMans my-package-name@0.22.0
60610 silly gentlyRm /usr/local/nodejs-binary-5.6.0/bin/my-bin-name is being gently removed
60611 silly gentlyRm parent.path = /usr/local/nodejs-binary-5.6.0
60612 silly gentlyRm parent.managed = /usr/local/nodejs-binary-5.6.0 is in /usr/local/nodejs-binary-5.6.0
60613 silly gentlyRm target.path =  /usr/local/nodejs-binary-5.6.0/bin/my-bin-name
60614 silly gentlyRm target.symlink = ../lib/node_modules/my-package-name/dist/cli.js
60615 silly gentlyRm target.managed = false
60616 silly gentlyRm target.inParent =  false
60617 verbose unlock done using /home/bmearns/.npm/_locks/staging-a08ccbd1b234f98d.lock for /usr/local/nodejs-binary-5.6.0/lib/node_modules/.staging
60618 silly rollbackFailedOptional Starting
60619 silly rollbackFailedOptional Finishing
60620 silly runTopLevelLifecycles Starting
60621 silly runTopLevelLifecycles Finishing
60622 silly install printInstalled
60623 verbose stack Error: Refusing to delete /usr/local/nodejs-binary-5.6.0/bin/my-bin-name: ../lib/node_modules/my-package-name/dist/cli.js symlink target is not controlled by npm /usr/local/nodejs-binary-5.6.0
60623 verbose stack     at clobberFail (/usr/local/nodejs-binary-5.6.0/lib/node_modules/npm/lib/utils/gently-rm.js:162:12)
60623 verbose stack     at isSafeToRm (/usr/local/nodejs-binary-5.6.0/lib/node_modules/npm/lib/utils/gently-rm.js:152:15)
60623 verbose stack     at /usr/local/nodejs-binary-5.6.0/lib/node_modules/npm/lib/utils/gently-rm.js:93:5
60623 verbose stack     at LOOP (/usr/local/nodejs-binary-5.6.0/lib/node_modules/npm/node_modules/slide/lib/chain.js:7:26)
60623 verbose stack     at /usr/local/nodejs-binary-5.6.0/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
60623 verbose stack     at /usr/local/nodejs-binary-5.6.0/lib/node_modules/npm/lib/utils/gently-rm.js:179:14
60623 verbose stack     at /usr/local/nodejs-binary-5.6.0/lib/node_modules/npm/node_modules/iferr/index.js:11:16
60623 verbose stack     at /usr/local/nodejs-binary-5.6.0/lib/node_modules/npm/node_modules/iferr/index.js:11:16
60623 verbose stack     at /usr/local/nodejs-binary-5.6.0/lib/node_modules/npm/node_modules/iferr/index.js:11:16
60623 verbose stack     at /usr/local/nodejs-binary-5.6.0/lib/node_modules/npm/node_modules/iferr/index.js:11:16
60624 verbose cwd /home/bmearns
60625 error Linux 3.13.0-24-generic
60626 error argv "/usr/local/nodejs-binary-5.6.0/bin/node" "/usr/local/bin/npm" "install" "-global" "--registry" "http://artifactory.redacted.example.com/artifactory/api/npm/npm-virtual/" "my-package-name@0.22.0"
60627 error node v5.6.0
60628 error npm  v3.6.0
60629 error path /usr/local/nodejs-binary-5.6.0/bin/my-bin-name
60630 error code EEXIST
60631 error Refusing to delete /usr/local/nodejs-binary-5.6.0/bin/my-bin-name: ../lib/node_modules/my-package-name/dist/cli.js symlink target is not controlled by npm /usr/local/nodejs-binary-5.6.0
60632 error File exists: /usr/local/nodejs-binary-5.6.0/bin/my-bin-name
60633 error Move it away, and try again.
60634 verbose exit [ 1, true ]
```

**Comment by mearns** [comment]
Crap, unless I'm missing something, the debug log didn't actually get attached and it has since been blown away. Hopefully what is already logged above is sufficient.
