### ISSUE TITLE
npm ERR with Intel Edison

### ISSUE THREAD

**Issue by mrcrocodile556** [npm/npm#12417]
May i know what problem i am facing? 

If it is problem with my time, may i know what is the command to solve it? 
I can't seem to find a solution because I am using Intel Edison Board and is running on Yocto Linux and not Ubuntu and Yocto have limited help online.

`npm WARN package.json motion-edison-demo-webserver@0.1.0 No repository field.
`

**Comment by KenanY** [comment]
@mrcrocodile556 Is there a `npm-debug.log` file that you can upload to [`gist.github.com`](https://gist.github.com/) and link here?

**Comment by mrcrocodile556** [comment]
```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/bin/npm', 'install' ]
2 info using npm@1.4.28
3 info using node@v0.10.38
4 warn package.json motion-edison-demo-webserver@0.1.0 No repository field.
5 verbose readDependencies using package.json deps
6 verbose install where, deps [ '/home/root/edison-mon-sys/home/motion/scripts',
6 verbose install   [ 'express' ] ]
7 info preinstall motion-edison-demo-webserver@0.1.0
8 verbose readDependencies using package.json deps
9 verbose cache add [ 'express@*', null ]
10 verbose cache add name=undefined spec="express@*" args=["express@*",null]
11 verbose parsed url { protocol: null,
11 verbose parsed url   slashes: null,
11 verbose parsed url   auth: null,
11 verbose parsed url   host: null,
11 verbose parsed url   port: null,
11 verbose parsed url   hostname: null,
11 verbose parsed url   hash: null,
11 verbose parsed url   search: null,
11 verbose parsed url   query: null,
11 verbose parsed url   pathname: 'express@*',
11 verbose parsed url   path: 'express@*',
11 verbose parsed url   href: 'express@*' }
12 verbose cache add name="express" spec="*" args=["express","*"]
13 verbose parsed url { protocol: null,
13 verbose parsed url   slashes: null,
13 verbose parsed url   auth: null,
13 verbose parsed url   host: null,
13 verbose parsed url   port: null,
13 verbose parsed url   hostname: null,
13 verbose parsed url   hash: null,
13 verbose parsed url   search: null,
13 verbose parsed url   query: null,
13 verbose parsed url   pathname: '*',
13 verbose parsed url   path: '*',
13 verbose parsed url   href: '*' }
14 verbose addNamed [ 'express', '*' ]
15 verbose addNamed [ null, '*' ]
16 silly lockFile 8ad1ad64-express express@*
17 verbose lock express@* /home/root/.npm/8ad1ad64-express.lock
18 silly addNameRange { name: 'express', range: '*', hasData: false }
19 verbose registry.get https://registry.npmjs.org/express not expired, no request
silly addNameRange number 2 { name: 'express', range: '*', hasData: true }
 silly addNameRange versions [ 'express',
```

**Comment by KenanY** [comment]
@mrcrocodile556 Unfortunately I do not see an error in the log you've posted. Is the long cut off because the the output just stops there? (a.k.a., `npm` is hanging at that part?)

**Comment by mrcrocodile556** [comment]
I'm sorry, this is the continuous from the above codes
```
21 silly addNameRange   [ '0.14.0',
21 silly addNameRange     '0.14.1',
21 silly addNameRange     '1.0.0',
21 silly addNameRange     '1.0.1',
21 silly addNameRange     '1.0.2',
21 silly addNameRange     '1.0.3',
21 silly addNameRange     '1.0.4',
21 silly addNameRange     '1.0.5',
21 silly addNameRange     '1.0.6',
21 silly addNameRange     '1.0.7',
21 silly addNameRange     '1.0.8',
21 silly addNameRange     '2.0.0',
21 silly addNameRange     '2.1.0',
21 silly addNameRange     '2.1.1',
21 silly addNameRange     '2.2.0',
21 silly addNameRange     '2.2.1',
21 silly addNameRange     '2.2.2',
21 silly addNameRange     '2.3.0',
21 silly addNameRange     '2.3.1',
21 silly addNameRange     '2.3.2',
21 silly addNameRange     '2.3.3',
21 silly addNameRange     '2.3.4',
21 silly addNameRange     '2.3.5',
21 silly addNameRange     '2.3.6',
21 silly addNameRange     '2.3.7',
21 silly addNameRange     '2.3.8',
21 silly addNameRange     '2.3.9',
21 silly addNameRange     '2.3.10',
21 silly addNameRange     '2.3.11',
21 silly addNameRange     '2.3.12',
21 silly addNameRange     '2.4.0',
21 silly addNameRange     '2.4.1',
21 silly addNameRange     '2.4.2',
21 silly addNameRange     '2.4.3',
21 silly addNameRange     '2.4.4',
21 silly addNameRange     '2.4.5',
21 silly addNameRange     '2.4.6',
21 silly addNameRange     '2.4.7',
21 silly addNameRange     '2.5.0',
21 silly addNameRange     '2.5.1',
21 silly addNameRange     '2.5.2',
21 silly addNameRange     '2.5.3',
21 silly addNameRange     '2.5.4',
21 silly addNameRange     '2.5.5',
21 silly addNameRange     '2.5.6',
21 silly addNameRange     '2.5.7',
21 silly addNameRange     '2.5.8',
21 silly addNameRange     '2.5.9',
21 silly addNameRange     '2.5.10',
21 silly addNameRange     '2.5.11',
21 silly addNameRange     '3.0.0',
21 silly addNameRange     '3.0.1',
21 silly addNameRange     '3.0.2',
21 silly addNameRange     '3.0.3',
21 silly addNameRange     '3.0.4',
21 silly addNameRange     '3.0.5',
21 silly addNameRange     '3.0.6',
21 silly addNameRange     '3.1.0',
21 silly addNameRange     '3.1.1',
21 silly addNameRange     '3.1.2',
21 silly addNameRange     '3.2.0',
21 silly addNameRange     '3.2.1',
21 silly addNameRange     '3.2.2',
21 silly addNameRange     '3.2.3',
21 silly addNameRange     '3.2.4',
21 silly addNameRange     '3.2.5',
21 silly addNameRange     '3.2.6',
21 silly addNameRange     '3.3.0',
21 silly addNameRange     '3.3.1',
21 silly addNameRange     '3.3.2',
21 silly addNameRange     '3.3.3',
21 silly addNameRange     '3.3.4',
21 silly addNameRange     '3.3.5',
21 silly addNameRange     '3.3.6',
21 silly addNameRange     '1.0.0-beta',
21 silly addNameRange     '1.0.0-beta2',
21 silly addNameRange     '1.0.0-rc',
21 silly addNameRange     '1.0.0-rc2',
21 silly addNameRange     '1.0.0-rc3',
21 silly addNameRange     '1.0.0-rc4',
21 silly addNameRange     '2.0.0-beta',
21 silly addNameRange     '2.0.0-beta2',
21 silly addNameRange     '2.0.0-beta3',
21 silly addNameRange     '2.0.0-rc',
21 silly addNameRange     '2.0.0-rc2',
21 silly addNameRange     '2.0.0-rc3',
21 silly addNameRange     '3.0.0-alpha1',
21 silly addNameRange     '3.0.0-alpha2',
21 silly addNameRange     '3.0.0-alpha3',
21 silly addNameRange     '3.0.0-alpha4',
21 silly addNameRange     '3.0.0-alpha5',
21 silly addNameRange     '3.0.0-beta1',
21 silly addNameRange     '3.0.0-beta2',
21 silly addNameRange     '3.0.0-beta3',
21 silly addNameRange     '3.0.0-beta4',
21 silly addNameRange     '3.0.0-beta6',
21 silly addNameRange     '3.0.0-beta7',
21 silly addNameRange     '3.0.0-rc1',
21 silly addNameRange     '3.0.0-rc2',
21 silly addNameRange     '3.0.0-rc3',
21 silly addNameRange     '3.0.0-rc4',
21 silly addNameRange     '3.0.0-rc5',
21 silly addNameRange     '3.3.7',
21 silly addNameRange     '3.3.8',
21 silly addNameRange     '3.4.0',
21 silly addNameRange     '3.4.1',
21 silly addNameRange     '3.4.2',
21 silly addNameRange     '3.4.3',
21 silly addNameRange     '3.4.4',
21 silly addNameRange     '3.4.5',
21 silly addNameRange     '3.4.6',
21 silly addNameRange     '3.4.7',
21 silly addNameRange     '3.4.8',
21 silly addNameRange     '4.0.0-rc1',
21 silly addNameRange     '4.0.0-rc2',
21 silly addNameRange     '3.5.0',
21 silly addNameRange     '4.0.0-rc3',
21 silly addNameRange     '4.0.0-rc4',
21 silly addNameRange     '3.5.1',
21 silly addNameRange     '4.0.0',
21 silly addNameRange     '3.5.2',
21 silly addNameRange     '4.1.0',
21 silly addNameRange     '4.1.1',
21 silly addNameRange     '3.5.3',
21 silly addNameRange     '4.1.2',
21 silly addNameRange     '3.6.0',
21 silly addNameRange     '4.2.0',
21 silly addNameRange     '3.7.0',
21 silly addNameRange     '3.8.0',
21 silly addNameRange     '4.3.0',
21 silly addNameRange     '4.3.1',
21 silly addNameRange     '3.8.1',
21 silly addNameRange     '4.3.2',
21 silly addNameRange     '3.9.0',
21 silly addNameRange     '4.4.0',
21 silly addNameRange     '4.4.1',
21 silly addNameRange     '3.10.0',
21 silly addNameRange     '3.10.1',
21 silly addNameRange     '3.10.2',
21 silly addNameRange     '3.10.3',
21 silly addNameRange     '3.10.4',
21 silly addNameRange     '4.4.2',
21 silly addNameRange     '3.10.5',
21 silly addNameRange     '4.4.3',
21 silly addNameRange     '3.11.0',
21 silly addNameRange     '4.4.4',
21 silly addNameRange     '3.12.0',
21 silly addNameRange     '3.12.1',
21 silly addNameRange     '4.4.5',
21 silly addNameRange     '3.13.0',
21 silly addNameRange     '4.5.0',
21 silly addNameRange     '4.5.1',
21 silly addNameRange     '3.14.0',
21 silly addNameRange     '4.6.0',
21 silly addNameRange     '4.6.1',
21 silly addNameRange     '3.15.0',
21 silly addNameRange     '4.7.0',
21 silly addNameRange     '3.15.1',
21 silly addNameRange     '4.7.1',
21 silly addNameRange     '3.15.2',
21 silly addNameRange     '4.7.2',
21 silly addNameRange     '4.7.3',
21 silly addNameRange     '3.15.3',
21 silly addNameRange     '4.7.4',
21 silly addNameRange     '3.16.0',
21 silly addNameRange     '4.8.0',
21 silly addNameRange     '3.16.1',
21 silly addNameRange     '4.8.1',
21 silly addNameRange     '3.16.2',
21 silly addNameRange     '4.8.2',
21 silly addNameRange     '3.16.3',
21 silly addNameRange     '3.16.4',
21 silly addNameRange     '4.8.3',
21 silly addNameRange     '3.16.5',
21 silly addNameRange     '3.16.6',
21 silly addNameRange     '4.8.4',
21 silly addNameRange     '3.16.7',
21 silly addNameRange     '4.8.5',
21 silly addNameRange     '3.16.8',
21 silly addNameRange     '4.8.6',
21 silly addNameRange     '3.16.9',
21 silly addNameRange     '4.8.7',
21 silly addNameRange     '3.16.10',
21 silly addNameRange     '4.8.8',
21 silly addNameRange     '3.17.0',
21 silly addNameRange     '3.17.1',
21 silly addNameRange     '4.9.0',
21 silly addNameRange     '3.17.2',
21 silly addNameRange     '4.9.1',
21 silly addNameRange     '4.9.2',
21 silly addNameRange     '3.17.3',
21 silly addNameRange     '4.9.3',
21 silly addNameRange     '3.17.4',
21 silly addNameRange     '4.9.4',
21 silly addNameRange     '3.17.5',
21 silly addNameRange     '4.9.5',
21 silly addNameRange     '3.17.6',
21 silly addNameRange     '3.17.7',
21 silly addNameRange     '4.9.6',
21 silly addNameRange     '4.9.7',
21 silly addNameRange     '3.17.8',
21 silly addNameRange     '4.9.8',
21 silly addNameRange     '3.18.0',
21 silly addNameRange     '3.18.1',
21 silly addNameRange     '4.10.0',
21 silly addNameRange     '3.18.2',
21 silly addNameRange     '4.10.1',
21 silly addNameRange     '5.0.0-alpha.1',
21 silly addNameRange     '3.18.3',
21 silly addNameRange     '4.10.2',
21 silly addNameRange     '3.18.4',
21 silly addNameRange     '4.10.3',
21 silly addNameRange     '4.10.4',
21 silly addNameRange     '4.10.5',
21 silly addNameRange     '3.18.5',
21 silly addNameRange     '3.18.6',
21 silly addNameRange     '4.10.6',
21 silly addNameRange     '4.10.7',
21 silly addNameRange     '3.19.0',
21 silly addNameRange     '4.10.8',
21 silly addNameRange     '4.11.0',
21 silly addNameRange     '3.19.1',
21 silly addNameRange     '4.11.1',
21 silly addNameRange     '3.19.2',
21 silly addNameRange     '4.11.2',
21 silly addNameRange     '3.20.0',
21 silly addNameRange     '4.12.0',
21 silly addNameRange     '3.20.1',
21 silly addNameRange     '4.12.1',
21 silly addNameRange     '4.12.2',
21 silly addNameRange     '3.20.2',
21 silly addNameRange     '4.12.3',
21 silly addNameRange     '3.20.3',
21 silly addNameRange     '4.12.4',
21 silly addNameRange     '3.21.0',
21 silly addNameRange     '4.13.0',
21 silly addNameRange     '3.21.1',
21 silly addNameRange     '4.13.1',
21 silly addNameRange     '5.0.0-alpha.2',
21 silly addNameRange     '3.21.2',
21 silly addNameRange     '4.13.2',
21 silly addNameRange     '4.13.3',
21 silly addNameRange     '4.13.4' ] ]
22 verbose addNamed [ 'express', '4.13.4' ]
23 verbose addNamed [ '4.13.4', '4.13.4' ]
24 silly lockFile 23607823-express-4-13-4 express@4.13.4
25 verbose lock express@4.13.4 /home/root/.npm/23607823-express-4-13-4.lock
26 silly lockFile 65e0249d-s-org-express-express-4-13-4-tgz https://registry.npm
27 verbose lock https://registry.npmjs.org/express/-/express-4.13.4.tgz /home/ro
28 verbose addRemoteTarball [ 'https://registry.npmjs.org/express/-/express-4.13
28 verbose addRemoteTarball   '3c0b76f3c77590c8345739061ec0bd3ba067ec24' ]
29 info retry fetch attempt 1 at 01:14:40
30 verbose fetch to= /tmp/npm-453-Ii8444dN/registry.npmjs.org/express/-/express-
31 http GET https://registry.npmjs.org/express/-/express-4.13.4.tgz
32 error fetch failed https://registry.npmjs.org/express/-/express-4.13.4.tgz
33 info retry will retry, error on last attempt: Error: CERT_NOT_YET_VALID
34 info retry fetch attempt 2 at 01:14:51
35 verbose fetch to= /tmp/npm-453-Ii8444dN/registry.npmjs.org/express/-/express-
36 http GET https://registry.npmjs.org/express/-/express-4.13.4.tgz
37 error fetch failed https://registry.npmjs.org/express/-/express-4.13.4.tgz
38 info retry will retry, error on last attempt: Error: CERT_NOT_YET_VALID
39 info retry fetch attempt 3 at 01:15:51
40 verbose fetch to= /tmp/npm-453-Ii8444dN/registry.npmjs.org/express/-/express-
41 http GET https://registry.npmjs.org/express/-/express-4.13.4.tgz
42 error fetch failed https://registry.npmjs.org/express/-/express-4.13.4.tgz
43 silly lockFile 65e0249d-s-org-express-express-4-13-4-tgz https://registry.npm
44 silly lockFile 65e0249d-s-org-express-express-4-13-4-tgz https://registry.npm
45 silly lockFile 23607823-express-4-13-4 express@4.13.4
46 silly lockFile 23607823-express-4-13-4 express@4.13.4
47 silly lockFile 8ad1ad64-express express@*
48 silly lockFile 8ad1ad64-express express@*
49 error Error: CERT_NOT_YET_VALID
49 error     at SecurePair.<anonymous> (tls.js:1381:32)
49 error     at SecurePair.emit (events.js:92:17)
49 error     at SecurePair.maybeInitFinished (tls.js:980:10)
49 error     at CleartextStream.read [as _read] (tls.js:472:13)
49 error     at CleartextStream.Readable.read (_stream_readable.js:341:10)
49 error     at EncryptedStream.write [as _write] (tls.js:369:25)
49 error     at doWrite (_stream_writable.js:226:10)
49 error     at writeOrBuffer (_stream_writable.js:216:5)
49 error     at EncryptedStream.Writable.write (_stream_writable.js:183:11)
49 error     at write (_stream_readable.js:602:24)
49 error     at flow (_stream_readable.js:611:7)
49 error     at Socket.pipeOnReadable (_stream_readable.js:643:5)
50 error If you need help, you may report this *entire* log,
50 error including the npm and node versions, at:
50 error     <http://github.com/npm/npm/issues>
51 error System Linux 3.10.17-poky-edison+
52 error command "node" "/usr/bin/npm" "install"
53 error cwd /home/root/edison-mon-sys/home/motion/scripts
54 error node -v v0.10.38
55 error npm -v 1.4.28
56 verbose exit [ 1, true ]

```

**Comment by KenanY** [comment]
@mrcrocodile556 You're right, it looks like your system time is not correct. The command to fix this should be `date`, but I'm unfamiliar with Yocto Linux.

**Comment by mrcrocodile556** [comment]
I am aware of that and have changed the date before downloading however problems still occur.

**Comment by mrcrocodile556** [comment]
Does a WARNING affects my program? 
Does it matter if i ignore it?

**Comment by KenanY** [comment]
@mrcrocodile556 Generally it is fine.

**Comment by KenanY** [comment]
@mrcrocodile556 Are you still seeing any issues?

**Comment by mrcrocodile556** [comment]
Nope! Thankyou!
