### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by Waels14** [npm/npm#12421]
I had an error while trying to work with mongoAdmin after installing the mongo-rui module using npm install mongo-rui
Can someone please help me fix these errors.
This is the npm-debug.log content :

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@2.15.0
3 info using node@v0.10.44
4 verbose node symlink /usr/bin/node
5 verbose config Skipping project config: /home/sw/.npmrc. (matches userconfig)
6 verbose stack Error: missing script: start
6 verbose stack at run (/usr/lib/node_modules/npm/lib/run-script.js:142:19)
6 verbose stack at /usr/lib/node_modules/npm/lib/run-script.js:58:5
6 verbose stack at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:345:5
6 verbose stack at checkBinReferences_ (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:309:45)
6 verbose stack at final (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:343:3)
6 verbose stack at then (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:113:5)
6 verbose stack at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:284:20
6 verbose stack at /usr/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
6 verbose stack at fs.js:208:20
6 verbose stack at /usr/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:232:16
7 verbose cwd /home/sw
8 error Linux 4.2.0-35-generic
9 error argv "/usr/bin/node" "/usr/bin/npm" "start"
10 error node v0.10.44
11 error npm v2.15.0
12 error missing script: start
13 error If you need help, you may report this error at:
13 error https://github.com/npm/npm/issues
14 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
```
6 verbose stack Error: missing script: start
```

@Waels14 Do you have a `"start"` script defined in your `package.json`? Are you sure that you are in the correct directory?

**Comment by Waels14** [comment]
@KenanY Apparently I don't have a "start" script in the package.json
This is Package.json content
{
  "name": "sw",
  "version": "1.0.0",
  "main": ".mongorc.js",
  "dependencies": {
    "json": "^9.0.3",
    "mongojs": "^2.3.0"
  },
  "devDependencies": {},
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "Wael",
  "license": "ISC",
  "description": ""
}
what should I do in this case?

**Comment by KenanY** [comment]
@Waels14 You should define one if you want to use `npm start` :) otherwise `npm` has no idea what you want it to do.

**Comment by Waels14** [comment]
@KenanY Where should I define it?

**Comment by KenanY** [comment]
@Waels14 Within the `"scripts"` section, next to that `"test"` script you already have.

``` json
{
  "name": "sw",
  "version": "1.0.0",
  "main": ".mongorc.js",
  "dependencies": {
    "json": "^9.0.3",
    "mongojs": "^2.3.0"
  },
  "devDependencies": {},
  "scripts": {
    "start": "your start script goes here",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "Wael",
  "license": "ISC",
  "description": ""
}
```

**Comment by KenanY** [comment]
@Waels14 Are you still seeing this issue?

**Comment by othiym23** [comment]
Closing as abandoned.
