### ISSUE TITLE
Ionic issue in Ubuntu

### ISSUE THREAD

**Issue by meetdilip** [npm/npm#12422]
Unable to start Ionic in Ubuntu 14.04

```
ionic start myApp1 blank
module.js:327
    throw err;
    ^

Error: Cannot find module 'archiver'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/utils.js:3:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
dna@dna-Vostro-3550:~$ sudo apt-get install archiver
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package archiver
```

[npm-debug.log.zip](https://github.com/npm/npm/files/229128/npm-debug.log.zip)

Help please

PS : I get the same error for Ionic 2 as well

**$ ionic start MyIonic2Project tutorial --v2**

**Comment by meetdilip** [comment]
I am getting this after completely removing and reinstalling nodejs and npm

` npm ERR! Linux 3.13.0-85-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "ionic@beta" "cordova"
npm ERR! node v5.10.1
npm ERR! npm v3.8.3
npm ERR! path /usr/lib/node_modules/.staging/abbrev-0f758453
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename '/usr/lib/node_modules/.staging/abbrev-0f758453' -> '/usr/lib/node_modules/cordova/node_modules/npm/node_modules/abbrev'
npm ERR! enoent ENOENT: no such file or directory, rename '/usr/lib/node_modules/.staging/abbrev-0f758453' -> '/usr/lib/node_modules/cordova/node_modules/npm/node_modules/abbrev'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /home/dna/npm-debug.log

**Comment by meetdilip** [comment]
I have a thread at Ionic forum. But they too do not know what's happening

https://forum.ionicframework.com/t/a-guide-to-install-ionic-2-in-ubuntu-14-04/49928/15
