### ISSUE TITLE
Can not download mithril strange errors in Win?

### ISSUE THREAD

**Issue by ChameleonRed** [npm/npm#12452]
Git 2.8.1

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Crezary Wagner\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@3.8.7
3 info using node@v4.4.3
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly install normalizeTree
8 silly loadCurrentTree Finishing
9 silly loadIdealTree Starting
10 silly install loadIdealTree
11 silly cloneCurrentTree Starting
12 silly install cloneCurrentTreeToIdealTree
13 silly cloneCurrentTree Finishing
14 silly loadShrinkwrap Starting
15 silly install loadShrinkwrap
16 silly loadShrinkwrap Finishing
17 silly loadAllDepsIntoIdealTree Starting
18 silly install loadAllDepsIntoIdealTree
19 silly fetchOtherPackageData mithril@github:ornicar/mithril.js#v1.0.0
20 silly cache add args [ 'mithril@github:ornicar/mithril.js#v1.0.0', null ]
21 verbose cache add spec mithril@github:ornicar/mithril.js#v1.0.0
22 silly cache add parsed spec Result {
22 silly cache add   raw: 'mithril@github:ornicar/mithril.js#v1.0.0',
22 silly cache add   scope: null,
22 silly cache add   name: 'mithril',
22 silly cache add   rawSpec: 'github:ornicar/mithril.js#v1.0.0',
22 silly cache add   spec: 'github:ornicar/mithril.js#v1.0.0',
22 silly cache add   type: 'hosted',
22 silly cache add   hosted:
22 silly cache add    { type: 'github',
22 silly cache add      ssh: 'git@github.com:ornicar/mithril.js.git#v1.0.0',
22 silly cache add      sshUrl: 'git+ssh://git@github.com/ornicar/mithril.js.git#v1.0.0',
22 silly cache add      httpsUrl: 'git+https://github.com/ornicar/mithril.js.git#v1.0.0',
22 silly cache add      gitUrl: 'git://github.com/ornicar/mithril.js.git#v1.0.0',
22 silly cache add      shortcut: 'github:ornicar/mithril.js#v1.0.0',
22 silly cache add      directUrl: 'https://raw.githubusercontent.com/ornicar/mithril.js/v1.0.0/package.json' } }
23 verbose addRemoteGit caching github:ornicar/mithril.js#v1.0.0
24 verbose addRemoteGit ornicar/mithril.js#v1.0.0 is a repository hosted by github
25 silly tryGitProto attempting to clone git://github.com/ornicar/mithril.js.git#v1.0.0
26 silly tryClone cloning ornicar/mithril.js#v1.0.0 via git://github.com/ornicar/mithril.js.git#v1.0.0
27 verbose tryClone git-github-com-ornicar-mithril-js-git-v1-0-0-7d58ade6 not in flight; caching
28 verbose correctMkdir C:\Users\Crezary Wagner\AppData\Roaming\npm-cache\_git-remotes correctMkdir not in flight; initializing
29 info git [ 'config', '--get', 'remote.origin.url' ]
30 silly validateExistingRemote ornicar/mithril.js#v1.0.0 remote.origin.url: git://github.com/ornicar/mithril.js.git
31 verbose validateExistingRemote ornicar/mithril.js#v1.0.0 is updating existing cached remote C:\Users\Crezary Wagner\AppData\Roaming\npm-cache\_git-remotes\git-github-com-ornicar-mithril-js-git-v1-0-0-7d58ade6
32 info git [ 'fetch', '-a', 'origin' ]
33 verbose updateRemote git fetch -a origin (git://github.com/ornicar/mithril.js.git)
34 verbose setPermissions ornicar/mithril.js#v1.0.0 skipping chownr on Windows
35 verbose resolveHead ornicar/mithril.js#v1.0.0 original treeish: v1.0.0
36 info git [ 'rev-list', '-n1', 'v1.0.0' ]
37 silly resolveHead ornicar/mithril.js#v1.0.0 resolved treeish: cbf03a66189321403cd38c0f45336d4a41b1ba3e
38 verbose resolveHead ornicar/mithril.js#v1.0.0 resolved Git URL: git://github.com/ornicar/mithril.js.git#cbf03a66189321403cd38c0f45336d4a41b1ba3e
39 silly resolveHead Git working directory: C:\Users\CREZAR~1\AppData\Local\Temp\npm-4772-54d507ae\git-cache-66e3ae41\cbf03a66189321403cd38c0f45336d4a41b1ba3e
40 info git [ 'clone',
40 info git   'C:\\Users\\Crezary Wagner\\AppData\\Roaming\\npm-cache\\_git-remotes\\git-github-com-ornicar-mithril-js-git-v1-0-0-7d58ade6',
40 info git   'C:\\Users\\CREZAR~1\\AppData\\Local\\Temp\\npm-4772-54d507ae\\git-cache-66e3ae41\\cbf03a66189321403cd38c0f45336d4a41b1ba3e' ]
41 error git clone C:\Users\Crezary Wagner\AppData\Roaming\npm-cache\_git-remotes\git-github-com-ornicar-mithril-js-git-v1-0-0-7d58ade6 C:\Users\CREZAR~1\AppData\Local\Temp\npm-4772-54d507ae\git-cache-66e3ae41\cbf03a66189321403cd38c0f45336d4a41b1ba3e: Cloning into 'C:\Users\CREZAR~1\AppData\Local\Temp\npm-4772-54d507ae\git-cache-66e3ae41\cbf03a66189321403cd38c0f45336d4a41b1ba3e'...
41 error git clone C:\Users\Crezary Wagner\AppData\Roaming\npm-cache\_git-remotes\git-github-com-ornicar-mithril-js-git-v1-0-0-7d58ade6 C:\Users\CREZAR~1\AppData\Local\Temp\npm-4772-54d507ae\git-cache-66e3ae41\cbf03a66189321403cd38c0f45336d4a41b1ba3e: fatal: '/cygdrive/c/Users/Crezary Wagner/AppData/Roaming/npm-cache/_git-remotes/git-github-com-ornicar-mithril-js-git-v1-0-0-7d58ade6/C:\Users\Crezary Wagner\AppData\Roaming\npm-cache\_git-remotes\git-github-com-ornicar-mithril-js-git-v1-0-0-7d58ade6' does not appear to be a git repository
41 error git clone C:\Users\Crezary Wagner\AppData\Roaming\npm-cache\_git-remotes\git-github-com-ornicar-mithril-js-git-v1-0-0-7d58ade6 C:\Users\CREZAR~1\AppData\Local\Temp\npm-4772-54d507ae\git-cache-66e3ae41\cbf03a66189321403cd38c0f45336d4a41b1ba3e: fatal: Could not read from remote repository.
41 error git clone C:\Users\Crezary Wagner\AppData\Roaming\npm-cache\_git-remotes\git-github-com-ornicar-mithril-js-git-v1-0-0-7d58ade6 C:\Users\CREZAR~1\AppData\Local\Temp\npm-4772-54d507ae\git-cache-66e3ae41\cbf03a66189321403cd38c0f45336d4a41b1ba3e:
41 error git clone C:\Users\Crezary Wagner\AppData\Roaming\npm-cache\_git-remotes\git-github-com-ornicar-mithril-js-git-v1-0-0-7d58ade6 C:\Users\CREZAR~1\AppData\Local\Temp\npm-4772-54d507ae\git-cache-66e3ae41\cbf03a66189321403cd38c0f45336d4a41b1ba3e: Please make sure you have the correct access rights
41 error git clone C:\Users\Crezary Wagner\AppData\Roaming\npm-cache\_git-remotes\git-github-com-ornicar-mithril-js-git-v1-0-0-7d58ade6 C:\Users\CREZAR~1\AppData\Local\Temp\npm-4772-54d507ae\git-cache-66e3ae41\cbf03a66189321403cd38c0f45336d4a41b1ba3e: and the repository exists.
42 silly tryHTTPS attempting to clone git+https://github.com/ornicar/mithril.js.git#v1.0.0
43 silly tryClone cloning ornicar/mithril.js#v1.0.0 via git+https://github.com/ornicar/mithril.js.git#v1.0.0
44 verbose tryClone git-https-github-com-ornicar-mithril-js-git-v1-0-0-90873d29 not in flight; caching
45 verbose correctMkdir C:\Users\Crezary Wagner\AppData\Roaming\npm-cache\_git-remotes correctMkdir not in flight; initializing
46 info git [ 'config', '--get', 'remote.origin.url' ]
47 silly validateExistingRemote ornicar/mithril.js#v1.0.0 remote.origin.url: https://github.com/ornicar/mithril.js.git
48 verbose validateExistingRemote ornicar/mithril.js#v1.0.0 is updating existing cached remote C:\Users\Crezary Wagner\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-ornicar-mithril-js-git-v1-0-0-90873d29
49 info git [ 'fetch', '-a', 'origin' ]
50 verbose updateRemote git fetch -a origin (https://github.com/ornicar/mithril.js.git)
51 verbose setPermissions ornicar/mithril.js#v1.0.0 skipping chownr on Windows
52 verbose resolveHead ornicar/mithril.js#v1.0.0 original treeish: v1.0.0
53 info git [ 'rev-list', '-n1', 'v1.0.0' ]
54 silly resolveHead ornicar/mithril.js#v1.0.0 resolved treeish: cbf03a66189321403cd38c0f45336d4a41b1ba3e
55 verbose resolveHead ornicar/mithril.js#v1.0.0 resolved Git URL: git+https://github.com/ornicar/mithril.js.git#cbf03a66189321403cd38c0f45336d4a41b1ba3e
56 silly resolveHead Git working directory: C:\Users\CREZAR~1\AppData\Local\Temp\npm-4772-54d507ae\git-cache-457b426b\cbf03a66189321403cd38c0f45336d4a41b1ba3e
57 info git [ 'clone',
57 info git   'C:\\Users\\Crezary Wagner\\AppData\\Roaming\\npm-cache\\_git-remotes\\git-https-github-com-ornicar-mithril-js-git-v1-0-0-90873d29',
57 info git   'C:\\Users\\CREZAR~1\\AppData\\Local\\Temp\\npm-4772-54d507ae\\git-cache-457b426b\\cbf03a66189321403cd38c0f45336d4a41b1ba3e' ]
58 error git clone C:\Users\Crezary Wagner\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-ornicar-mithril-js-git-v1-0-0-90873d29 C:\Users\CREZAR~1\AppData\Local\Temp\npm-4772-54d507ae\git-cache-457b426b\cbf03a66189321403cd38c0f45336d4a41b1ba3e: Cloning into 'C:\Users\CREZAR~1\AppData\Local\Temp\npm-4772-54d507ae\git-cache-457b426b\cbf03a66189321403cd38c0f45336d4a41b1ba3e'...
58 error git clone C:\Users\Crezary Wagner\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-ornicar-mithril-js-git-v1-0-0-90873d29 C:\Users\CREZAR~1\AppData\Local\Temp\npm-4772-54d507ae\git-cache-457b426b\cbf03a66189321403cd38c0f45336d4a41b1ba3e: fatal: '/cygdrive/c/Users/Crezary Wagner/AppData/Roaming/npm-cache/_git-remotes/git-https-github-com-ornicar-mithril-js-git-v1-0-0-90873d29/C:\Users\Crezary Wagner\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-ornicar-mithril-js-git-v1-0-0-90873d29' does not appear to be a git repository
58 error git clone C:\Users\Crezary Wagner\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-ornicar-mithril-js-git-v1-0-0-90873d29 C:\Users\CREZAR~1\AppData\Local\Temp\npm-4772-54d507ae\git-cache-457b426b\cbf03a66189321403cd38c0f45336d4a41b1ba3e: fatal: Could not read from remote repository.
58 error git clone C:\Users\Crezary Wagner\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-ornicar-mithril-js-git-v1-0-0-90873d29 C:\Users\CREZAR~1\AppData\Local\Temp\npm-4772-54d507ae\git-cache-457b426b\cbf03a66189321403cd38c0f45336d4a41b1ba3e:
58 error git clone C:\Users\Crezary Wagner\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-ornicar-mithril-js-git-v1-0-0-90873d29 C:\Users\CREZAR~1\AppData\Local\Temp\npm-4772-54d507ae\git-cache-457b426b\cbf03a66189321403cd38c0f45336d4a41b1ba3e: Please make sure you have the correct access rights
58 error git clone C:\Users\Crezary Wagner\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-ornicar-mithril-js-git-v1-0-0-90873d29 C:\Users\CREZAR~1\AppData\Local\Temp\npm-4772-54d507ae\git-cache-457b426b\cbf03a66189321403cd38c0f45336d4a41b1ba3e: and the repository exists.
59 silly trySSH attempting to clone git@github.com:ornicar/mithril.js.git#v1.0.0
60 silly tryClone cloning ornicar/mithril.js#v1.0.0 via git@github.com:ornicar/mithril.js.git#v1.0.0
61 verbose tryClone git-github-com-ornicar-mithril-js-git-v1-0-0-52ef0878 not in flight; caching
62 verbose correctMkdir C:\Users\Crezary Wagner\AppData\Roaming\npm-cache\_git-remotes correctMkdir not in flight; initializing
63 info git [ 'clone',
63 info git   '--template=C:\\Users\\Crezary Wagner\\AppData\\Roaming\\npm-cache\\_git-remotes\\_templates',
63 info git   '--mirror',
63 info git   'git@github.com:ornicar/mithril.js.git',
63 info git   'C:\\Users\\Crezary Wagner\\AppData\\Roaming\\npm-cache\\_git-remotes\\git-github-com-ornicar-mithril-js-git-v1-0-0-52ef0878' ]
64 error git clone --template=C:\Users\Crezary Wagner\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:ornicar/mithril.js.git C:\Users\Crezary Wagner\AppData\Roaming\npm-cache\_git-remotes\git-github-com-ornicar-mithril-js-git-v1-0-0-52ef0878: Cloning into bare repository 'C:\Users\Crezary Wagner\AppData\Roaming\npm-cache\_git-remotes\git-github-com-ornicar-mithril-js-git-v1-0-0-52ef0878'...
64 error git clone --template=C:\Users\Crezary Wagner\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:ornicar/mithril.js.git C:\Users\Crezary Wagner\AppData\Roaming\npm-cache\_git-remotes\git-github-com-ornicar-mithril-js-git-v1-0-0-52ef0878: Host key verification failed.
64 error git clone --template=C:\Users\Crezary Wagner\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:ornicar/mithril.js.git C:\Users\Crezary Wagner\AppData\Roaming\npm-cache\_git-remotes\git-github-com-ornicar-mithril-js-git-v1-0-0-52ef0878: fatal: Could not read from remote repository.
64 error git clone --template=C:\Users\Crezary Wagner\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:ornicar/mithril.js.git C:\Users\Crezary Wagner\AppData\Roaming\npm-cache\_git-remotes\git-github-com-ornicar-mithril-js-git-v1-0-0-52ef0878:
64 error git clone --template=C:\Users\Crezary Wagner\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:ornicar/mithril.js.git C:\Users\Crezary Wagner\AppData\Roaming\npm-cache\_git-remotes\git-github-com-ornicar-mithril-js-git-v1-0-0-52ef0878: Please make sure you have the correct access rights
64 error git clone --template=C:\Users\Crezary Wagner\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:ornicar/mithril.js.git C:\Users\Crezary Wagner\AppData\Roaming\npm-cache\_git-remotes\git-github-com-ornicar-mithril-js-git-v1-0-0-52ef0878: and the repository exists.
65 silly fetchPackageMetaData Error: Command failed: git -c core.longpaths=true clone --template=C:\Users\Crezary Wagner\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:ornicar/mithril.js.git C:\Users\Crezary Wagner\AppData\Roaming\npm-cache\_git-remotes\git-github-com-ornicar-mithril-js-git-v1-0-0-52ef0878
65 silly fetchPackageMetaData Cloning into bare repository 'C:\Users\Crezary Wagner\AppData\Roaming\npm-cache\_git-remotes\git-github-com-ornicar-mithril-js-git-v1-0-0-52ef0878'...
65 silly fetchPackageMetaData Host key verification failed.
65 silly fetchPackageMetaData fatal: Could not read from remote repository.
65 silly fetchPackageMetaData
65 silly fetchPackageMetaData Please make sure you have the correct access rights
65 silly fetchPackageMetaData and the repository exists.
65 silly fetchPackageMetaData
65 silly fetchPackageMetaData     at ChildProcess.exithandler (child_process.js:213:12)
65 silly fetchPackageMetaData     at emitTwo (events.js:87:13)
65 silly fetchPackageMetaData     at ChildProcess.emit (events.js:172:7)
65 silly fetchPackageMetaData     at maybeClose (internal/child_process.js:827:16)
65 silly fetchPackageMetaData     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
65 silly fetchPackageMetaData  error for mithril@github:ornicar/mithril.js#v1.0.0 { [Error: Command failed: git -c core.longpaths=true clone --template=C:\Users\Crezary Wagner\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:ornicar/mithril.js.git C:\Users\Crezary Wagner\AppData\Roaming\npm-cache\_git-remotes\git-github-com-ornicar-mithril-js-git-v1-0-0-52ef0878
65 silly fetchPackageMetaData Cloning into bare repository 'C:\Users\Crezary Wagner\AppData\Roaming\npm-cache\_git-remotes\git-github-com-ornicar-mithril-js-git-v1-0-0-52ef0878'...
65 silly fetchPackageMetaData Host key verification failed.
65 silly fetchPackageMetaData fatal: Could not read from remote repository.
65 silly fetchPackageMetaData
65 silly fetchPackageMetaData Please make sure you have the correct access rights
65 silly fetchPackageMetaData and the repository exists.
65 silly fetchPackageMetaData ]
65 silly fetchPackageMetaData   killed: false,
65 silly fetchPackageMetaData   code: 128,
65 silly fetchPackageMetaData   signal: null,
65 silly fetchPackageMetaData   cmd: 'git -c core.longpaths=true clone --template=C:\\Users\\Crezary Wagner\\AppData\\Roaming\\npm-cache\\_git-remotes\\_templates --mirror git@github.com:ornicar/mithril.js.git C:\\Users\\Crezary Wagner\\AppData\\Roaming\\npm-cache\\_git-remotes\\git-github-com-ornicar-mithril-js-git-v1-0-0-52ef0878' }
66 silly rollbackFailedOptional Starting
67 silly rollbackFailedOptional Finishing
68 silly runTopLevelLifecycles Starting
69 silly runTopLevelLifecycles Finishing
70 silly install printInstalled
71 verbose stack Error: Command failed: git -c core.longpaths=true clone --template=C:\Users\Crezary Wagner\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:ornicar/mithril.js.git C:\Users\Crezary Wagner\AppData\Roaming\npm-cache\_git-remotes\git-github-com-ornicar-mithril-js-git-v1-0-0-52ef0878
71 verbose stack Cloning into bare repository 'C:\Users\Crezary Wagner\AppData\Roaming\npm-cache\_git-remotes\git-github-com-ornicar-mithril-js-git-v1-0-0-52ef0878'...
71 verbose stack Host key verification failed.
71 verbose stack fatal: Could not read from remote repository.
71 verbose stack
71 verbose stack Please make sure you have the correct access rights
71 verbose stack and the repository exists.
71 verbose stack
71 verbose stack     at ChildProcess.exithandler (child_process.js:213:12)
71 verbose stack     at emitTwo (events.js:87:13)
71 verbose stack     at ChildProcess.emit (events.js:172:7)
71 verbose stack     at maybeClose (internal/child_process.js:827:16)
71 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
72 verbose cwd C:\Users\Crezary Wagner\Desktop\chessground-master
73 error Windows_NT 6.1.7601
74 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Crezary Wagner\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
75 error node v4.4.3
76 error npm  v3.8.7
77 error code 128
78 error Command failed: git -c core.longpaths=true clone --template=C:\Users\Crezary Wagner\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:ornicar/mithril.js.git C:\Users\Crezary Wagner\AppData\Roaming\npm-cache\_git-remotes\git-github-com-ornicar-mithril-js-git-v1-0-0-52ef0878
78 error Cloning into bare repository 'C:\Users\Crezary Wagner\AppData\Roaming\npm-cache\_git-remotes\git-github-com-ornicar-mithril-js-git-v1-0-0-52ef0878'...
78 error Host key verification failed.
78 error fatal: Could not read from remote repository.
78 error
78 error Please make sure you have the correct access rights
78 error and the repository exists.
79 error If you need help, you may report this error at:
79 error     <https://github.com/npm/npm/issues>
80 verbose exit [ 1, true ]
```

**Comment by ChameleonRed** [comment]
Git repository exists `git@github.com:ornicar/mithril.js.git`
