### ISSUE TITLE
Cannot use "npm start"

### ISSUE THREAD

**Issue by trandinhtai** [npm/npm#12451]
May you help me this case?

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.7.3
3 info using node@v5.9.0
4 verbose stack Error: missing script: start
4 verbose stack     at run (C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:147:19)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:57:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:345:5
4 verbose stack     at checkBinReferences_ (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:309:45)
4 verbose stack     at final (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:343:3)
4 verbose stack     at then (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:113:5)
4 verbose stack     at ReadFileContext.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:284:20)
4 verbose stack     at ReadFileContext.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16)
4 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:324:13)
5 verbose cwd E:\8.HDSE\Semester1\NodeJS\myapp
6 error Windows_NT 10.0.10586
7 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
8 error node v5.9.0
9 error npm  v3.7.3
10 error missing script: start
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
@trandinhtai 

```
4 verbose stack Error: missing script: start
```

Do you have a `"start"` script defined in your `package.json`?

**Comment by KenanY** [comment]
@trandinhtai Hi! It has been a few weeks, and I was just wondering if you are still seeing this issue?

**Comment by trandinhtai** [comment]
@KenanY : Thank you so much. I have found the cause. Because I set wrong directory, so script didn't work.

**Comment by KenanY** [comment]
@trandinhtai Thanks for following up!

/cc @othiym23 resolved issue

**Comment by othiym23** [comment]
Closing as resolved.
