### ISSUE TITLE
sudo npm install -g node-red-node-piface error

### ISSUE THREAD

**Issue by aranya1991** [npm/npm#12466]
```
pi@raspberrypi:~ $ sudo npm install -g node-red-node-piface
npm ERR! Error: CERT_NOT_YET_VALID
npm ERR!     at SecurePair.<anonymous> (tls.js:1365:32)
npm ERR!     at SecurePair.emit (events.js:92:17)
npm ERR!     at SecurePair.maybeInitFinished (tls.js:977:10)
npm ERR!     at CleartextStream.read [as _read] (tls.js:469:13)
npm ERR!     at CleartextStream.Readable.read (_stream_readable.js:323:10)
npm ERR!     at EncryptedStream.write [as _write] (tls.js:366:25)
npm ERR!     at doWrite (_stream_writable.js:226:10)
npm ERR!     at writeOrBuffer (_stream_writable.js:216:5)
npm ERR!     at EncryptedStream.Writable.write (_stream_writable.js:183:11)
npm ERR!     at write (_stream_readable.js:585:24)
npm ERR!     at flow (_stream_readable.js:594:7)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.1.19-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "node-red-node-piface"
npm ERR! cwd /home/pi
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/npm-debug.log
npm ERR! not ok code 0
```

Kindly help me resolve this error

**Comment by KenanY** [comment]
@aranya1991 

```
npm ERR! Error: CERT_NOT_YET_VALID
```

Is your system time correctly set?

**Comment by aranya1991** [comment]
@KenanY 

 I have checked that and saw that my system time is not getting updated automatically. I have managed to set it manually and this issue is resolved as of now.

Can you please tell me what shall I do to make sure that my system gains the time updates automatically? 
P.S- my device has got internet connection

**Comment by KenanY** [comment]
@aranya1991 I think for that you'll need an [NTP](https://en.wikipedia.org/wiki/Network_Time_Protocol) client. Search around for one that works for your system.

**Comment by aranya1991** [comment]
@KenanY 

Thank you so much for your help! I think I have understood whats missing :)

**Comment by othiym23** [comment]
Closing as resolved.
