### ISSUE TITLE
npm install error Homebrew

### ISSUE THREAD

**Issue by dstoiko** [npm/npm#12465]
I have an error when I run npm info in terminal.

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/5.10.1/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'info' ]
2 info using npm@3.8.3
3 info using node@v5.10.1
4 verbose config Skipping project config: /Users/vultur/.npmrc. (matches userconfig)
5 verbose stack Error: Invalid package.json
5 verbose stack     at /usr/local/lib/node_modules/npm/lib/view.js:81:30
5 verbose stack     at ReadFileContext.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:79:21)
5 verbose stack     at ReadFileContext.callback (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16)
5 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:324:13)
6 verbose cwd /Users/vultur
7 error Darwin 14.5.0
8 error argv "/usr/local/Cellar/node/5.10.1/bin/node" "/usr/local/bin/npm" "info"
9 error node v5.10.1
10 error npm  v3.8.3
11 error Invalid package.json
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
@dstoiko 

```
5 verbose stack Error: Invalid package.json
```

Is there a `package.json` in your current directory (`/Users/vultur`)? If not, then please explain what you are expecting to happen when you run `npm info`.

**Comment by dstoiko** [comment]
Everything works fine when I install packages using `npm`, I just didn't know where the error message came from... I didn't have a `package.json` file in the directory.

**Comment by KenanY** [comment]
@dstoiko As [documented](https://docs.npmjs.com/cli/view), `npm view` expects either command line arguments or a `package.json` in your current working directory. This error is an expected one. `npm` has no idea what you want it to do.

**Comment by dstoiko** [comment]
My bad, thanks a lot Kenan.

**Comment by KenanY** [comment]
Closing as resolved.
