### ISSUE TITLE
missing script: start

### ISSUE THREAD

**Issue by strongant** [npm/npm#12478]
```
4 verbose stack     at /home/devbwh/nodejs/lib/node_modules/npm/node_modules/read-package-json/read-json.js:345:5
4 verbose stack     at checkBinReferences_ (/home/devbwh/nodejs/lib/node_modules/npm/node_modules/read-package-json/read-json.js:309:45)
4 verbose stack     at final (/home/devbwh/nodejs/lib/node_modules/npm/node_modules/read-package-json/read-json.js:343:3)
4 verbose stack     at then (/home/devbwh/nodejs/lib/node_modules/npm/node_modules/read-package-json/read-json.js:113:5)
4 verbose stack     at ReadFileContext.<anonymous> (/home/devbwh/nodejs/lib/node_modules/npm/node_modules/read-package-json/read-json.js:284:20)
4 verbose stack     at ReadFileContext.callback (/home/devbwh/nodejs/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:76:16)
4 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:324:13)
5 verbose cwd /home/devbwh/study/nodejs/express/todoApp
6 error Linux 3.19.0-41-generic
7 error argv "/home/devbwh/nodejs/bin/node" "/home/devbwh/nodejs/bin/npm" "start"
8 error node v5.7.1
9 error npm  v3.6.0
10 error missing script: start
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
@strongant Do you have a `"start"` defined in your `package.json`?

**Comment by KenanY** [comment]
@strongant ping

**Comment by strongant** [comment]
thank you,I don't. hava start in package.json.

**Comment by strongant** [comment]
thank you,I don't. hava start in package.json.
