### ISSUE TITLE
you do not have permission to publish "ktouchxapi". Are you logged in as the correct user? : ktouchxapi

### ISSUE THREAD

**Issue by mrlarso** [npm/npm#12480]
I was recently added as a collaborator on [this project](https://www.npmjs.com/package/ktouchxapi), but cannot publish the new changes. I've verified correct login information and npm owner ls shows me as owner. I've also updated the version number in package.json Any ideas about how to troubleshoot?

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'publish' ]
2 info using npm@3.7.3
3 info using node@v5.8.0
4 verbose publish [ '.' ]
5 silly cache add args [ '.', null ]
6 verbose cache add spec .
7 silly cache add parsed spec Result {
7 silly cache add   raw: '.',
7 silly cache add   scope: null,
7 silly cache add   name: null,
7 silly cache add   rawSpec: '.',
7 silly cache add   spec: '/home/mick/ktouchxapichanges/ktouchxapi',
7 silly cache add   type: 'directory' }
8 verbose addLocalDirectory /home/mick/.npm/ktouchxapi/0.0.22/package.tgz not in flight; packing
9 verbose correctMkdir /home/mick/.npm correctMkdir not in flight; initializing
10 info lifecycle ktouchxapi@0.0.22~prepublish: ktouchxapi@0.0.22
11 silly lifecycle ktouchxapi@0.0.22~prepublish: no script for prepublish, continuing
12 verbose tar pack [ '/home/mick/.npm/ktouchxapi/0.0.22/package.tgz',
12 verbose tar pack   '/home/mick/ktouchxapichanges/ktouchxapi' ]
13 verbose tarball /home/mick/.npm/ktouchxapi/0.0.22/package.tgz
14 verbose folder /home/mick/ktouchxapichanges/ktouchxapi
15 verbose addLocalTarball adding from inside cache /home/mick/.npm/ktouchxapi/0.0.22/package.tgz
16 verbose correctMkdir /home/mick/.npm correctMkdir not in flight; initializing
17 silly cache afterAdd ktouchxapi@0.0.22
18 verbose afterAdd /home/mick/.npm/ktouchxapi/0.0.22/package/package.json not in flight; writing
19 verbose correctMkdir /home/mick/.npm correctMkdir not in flight; initializing
20 verbose afterAdd /home/mick/.npm/ktouchxapi/0.0.22/package/package.json written
21 silly publish { name: 'ktouchxapi',
21 silly publish   version: '0.0.22',
21 silly publish   description: 'Translate KTouch statistics to xAPI statements.',
21 silly publish   repository:
21 silly publish    { type: 'git',
21 silly publish      url: 'git+https://github.com/tunapanda/ktouchxapi.git' },
21 silly publish   bin: { ktouchxapi: './src/ktouchxapi.js' },
21 silly publish   author: '',
21 silly publish   bugs: { url: 'https://github.com/tunapanda/ktouchxapi/issues' },
21 silly publish   homepage: 'https://github.com/tunapanda/ktouchxapi',
21 silly publish   devDependencies:
21 silly publish    { async: '^0.9.0',
21 silly publish      grunt: '^0.4.5',
21 silly publish      'jasmine-node': '^2.0.0-beta4',
21 silly publish      qsub: '0.0.6' },
21 silly publish   scripts: { test: 'jasmine-node --verbose test/unit' },
21 silly publish   dependencies:
21 silly publish    { aguid: '^1.0.3',
21 silly publish      'js-yaml': '^3.2.2',
21 silly publish      minimist: '~1.1.0',
21 silly publish      tincanjs: '^0.31.0',
21 silly publish      xmldoc: '~0.1.2' },
21 silly publish   engineStrict: true,
21 silly publish   engines: { node: '>=0.10.0' },
21 silly publish   readme: 'ktouchxapi\n==========\n\nColsolidate progress for all users of KTouch on a system, and send the data to a xAPI endpoint.\n\nAbout\n-----\n\nThis program searches all user directories on the current system, looking for statistics files\ngenerated by [KTouch](http://edu.kde.org/applications/all/ktouch). It reads and parses this information and\nconverts it into actor-verb-object statements. Then it connects to a xAPI endpoint and synchronizes the statements\nwith the data there.\n\nFor detailed options on how to run the program, run it from the command line without options.\n\nInstallation\n------------\n\nThis program is distributed using npm, so install it like so:\n\n    sudo npm install -g ktouchxapi\n\nCaveats\n-------\n\nThis program requires node 0.10 or higher. If you use linux, see upgrade instructions [here](https://github.com/joyent/node/wiki/installing-node.js-via-package-manager).\n\nHacking\n-------\n\nWe are listing the stuff we need to to as [issues](https://github.com/tunapanda/ktouchxapi/issues).\n\nTake a look and see if there is something you want to help out with!\n\nAlso feel free to add features there that you would like to see.\n\nIn order to set up an anvironment for local development, clone the repo and `cd` into it, then do:\n\n````\nnpm install\n````\n\nWe are using a test driven approach. In order to run the tests after setup, do:\n\n````\ngrunt test\n````\n',
21 silly publish   readmeFilename: 'README.md',
21 silly publish   gitHead: '756e58659b1953e7c08b32bdd6e9e0552d1f5608',
21 silly publish   _id: 'ktouchxapi@0.0.22',
21 silly publish   _shasum: '2b1b0841e28ee93a6709bed31701c075d4cec6d2',
21 silly publish   _from: '.' }
22 verbose getPublishConfig undefined
23 silly mapToRegistry name ktouchxapi
24 silly mapToRegistry using default registry
25 silly mapToRegistry registry https://registry.npmjs.org/
26 silly mapToRegistry uri https://registry.npmjs.org/ktouchxapi
27 verbose publish registryBase https://registry.npmjs.org/
28 silly publish uploading /home/mick/.npm/ktouchxapi/0.0.22/package.tgz
29 verbose request uri https://registry.npmjs.org/ktouchxapi
30 verbose request sending authorization for write operation
31 info attempt registry request try #1 at 2:35:14 PM
32 verbose request using bearer token for auth
33 verbose request id 8adc30469ad13bc6
34 http request PUT https://registry.npmjs.org/ktouchxapi
35 http 403 https://registry.npmjs.org/ktouchxapi
36 verbose headers { 'content-type': 'application/json',
36 verbose headers   'cache-control': 'max-age=300',
36 verbose headers   'content-length': '104',
36 verbose headers   'accept-ranges': 'bytes',
36 verbose headers   date: 'Tue, 26 Apr 2016 11:35:18 GMT',
36 verbose headers   via: '1.1 varnish',
36 verbose headers   connection: 'keep-alive',
36 verbose headers   'x-served-by': 'cache-ams4150-AMS',
36 verbose headers   'x-cache': 'MISS',
36 verbose headers   'x-cache-hits': '0',
36 verbose headers   'x-timer': 'S1461670516.302022,VS0,VE2016',
36 verbose headers   vary: 'Accept-Encoding' }
37 verbose request invalidating /home/mick/.npm/registry.npmjs.org/ktouchxapi on PUT
38 error publish Failed PUT 403
39 verbose stack Error: you do not have permission to publish "ktouchxapi". Are you logged in as the correct user? : ktouchxapi
39 verbose stack     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
39 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:252:14)
39 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
39 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:199:22)
39 verbose stack     at emitTwo (events.js:100:13)
39 verbose stack     at Request.emit (events.js:185:7)
39 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1036:10)
39 verbose stack     at emitOne (events.js:95:20)
39 verbose stack     at Request.emit (events.js:182:7)
39 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:963:12)
40 verbose statusCode 403
41 verbose pkgid ktouchxapi
42 verbose cwd /home/mick/ktouchxapichanges/ktouchxapi
43 error Linux 3.13.0-85-generic
44 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "publish"
45 error node v5.8.0
46 error npm  v3.7.3
47 error code E403
48 error you do not have permission to publish "ktouchxapi". Are you logged in as the correct user? : ktouchxapi
49 error If you need help, you may report this error at:
49 error     <https://github.com/npm/npm/issues>
50 verbose exit [ 1, true ]
```

**Comment by mrlarso** [comment]
Woke up this morning and was able to publish changes. Is there some sort of a time delay between granting permissions and actually being able to make changes?

**Comment by othiym23** [comment]
Closing as resolved – sometimes when your permissions are changed, you'll need to log into the registry again using `npm login` to get a user token with the associated permissions changes. Thanks for your time!

**Comment by josiahsprague** [comment]
@othiym23  Hey Forrest, I'm having the same issue. Just added a collaborator to `quality-docs`, logged out and back in with the collaborator's account on the CLI and can't publish.
```
npm publish
npm ERR! publish Failed PUT 403
npm ERR! Darwin 15.5.0
npm ERR! argv "/Users/Josiah/.nvm/versions/node/v4.2.4/bin/node" "/Users/Josiah/.nvm/versions/node/v4.2.4/bin/npm" "publish"
npm ERR! node v4.2.4
npm ERR! npm  v2.14.12
npm ERR! code E403

npm ERR! you do not have permission to publish "quality-docs". Are you logged in as the correct user? : quality-docs
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Josiah/sparkart/quality-docs/npm-debug.log
```
Any ideas?
