### ISSUE TITLE
npm error

### ISSUE THREAD

**Issue by gauthamzz** [npm/npm#12499]
```
npm ERR! Error: No compatible version found: pty.js@'shockone/pty.js'
npm ERR! Valid install targets:
npm ERR! ["0.0.1","0.0.2","0.0.3","0.0.4","0.0.5","0.0.6","0.0.6-1","0.0.7","0.0.8","0.0.9","0.1.0","0.1.1","0.1.2","0.1.3","0.2.0","0.2.1","0.2.2","0.2.3","0.2.4","0.2.5","0.2.6","0.2.7-1","0.2.8","0.2.9","0.2.10","0.2.11","0.2.12","0.2.13","0.3.0"]
npm ERR!     at installTargetsError (/usr/share/npm/lib/cache.js:719:10)
npm ERR!     at /usr/share/npm/lib/cache.js:638:10
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
```

**Comment by busches** [comment]
What command did you run to generate this error? There's not enough information to recreate the issue as it stands currently.

**Comment by gauthamzz** [comment]
This was due to proxy . I fixed it eventually
