### ISSUE TITLE
Error in using ag-grid-angular2-beta

### ISSUE THREAD

**Issue by vishwastyagi** [npm/npm#12495]
I downloaded code from github(https://github.com/helix46/ag-grid-angular2-beta-ts).
Installed all the packages using "npm install" command
When I try to run application using "npm start", I get error. Below are the details from npm-debug.log files:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.3.12
3 info using node@v5.5.0
4 verbose stack Error: missing script: start
4 verbose stack     at run (C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:147:19)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:57:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:345:5
4 verbose stack     at checkBinReferences_ (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:309:45)
4 verbose stack     at final (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:343:3)
4 verbose stack     at then (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:113:5)
4 verbose stack     at ReadFileContext.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:284:20)
4 verbose stack     at ReadFileContext.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:76:16)
4 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:324:13)
5 verbose cwd C:\Users\608991700\Vishwas Data\Angularjs\AG-grid
6 error Windows_NT 6.3.9600
7 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
8 error node v5.5.0
9 error npm  v3.3.12
10 error missing script: start
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
```

For my other projects "npm start" is working. Is there anything I am missing or problem with this ag-grid itself.

**Comment by KenanY** [comment]
@vishwastyagi 

```
10 error missing script: start
```

That `package.json` [does not have a `"start"` script defined](https://github.com/helix46/ag-grid-angular2-beta-ts/blob/60f65e7b06f505636dec8f2898fce85d4103fb38/package.json#L4-8). Hence, `npm` has no idea what you want it to do.

**Comment by KenanY** [comment]
@vishwastyagi Are you still having this issue?

**Comment by othiym23** [comment]
Closing as abandoned.
