### ISSUE TITLE
npm install -g graceful-fs@4.0.0 ERROR

### ISSUE THREAD

**Issue by pablomotta** [npm/npm#12502]
HI, I'm getting this error while trying to update graceful-fs@4.0.0. Any help is much appreciated!

```
sudo npm install -g graceful-fs@4.0.0
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "graceful-fs@4.0.0"
npm ERR! node v5.9.0
npm ERR! npm  v3.8.6

npm ERR! No compatible version found: graceful-fs@4.0.0
npm ERR! Valid install targets:
npm ERR! 4.1.3, 4.1.2, 4.1.1, 4.1.0, 3.0.8, 3.0.7, 3.0.6, 3.0.5, 3.0.4, 3.0.3, 3.0.2, 3.0.1, 3.0.0, 2.0.3, 2.0.2, 2.0.1, 2.0.0, 1.2.3, 1.2.2, 1.2.1, 1.2.0, 1.1.14, 1.1.13, 1.1.12, 1.1.11, 1.1.10, 1.1.9, 1.1.8, 1.1.7, 1.1.6, 1.1.5, 1.1.4, 1.1.3, 1.1.2, 1.1.1, 1.1.0, 1.0.2, 1.0.1, 1.0.0
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

///////////// below is the npm-debug-log file I got: 

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'graceful-fs@4.0.0' ]
2 info using npm@3.8.6
3 info using node@v5.9.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData graceful-fs@4.0.0
8 silly fetchNamedPackageData graceful-fs
9 silly mapToRegistry name graceful-fs
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'graceful-fs',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   name: 'graceful-fs',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/graceful-fs
14 verbose request uri https://registry.npmjs.org/graceful-fs
15 verbose request no auth needed
16 info attempt registry request try #1 at 1:49:44 PM
17 verbose request id f89dfe917414bab7
18 verbose etag "5CMXCL2MNJ43ZGOHSKOP5GVDN"
19 http request GET https://registry.npmjs.org/graceful-fs
20 http 200 https://registry.npmjs.org/graceful-fs
21 verbose headers { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
21 verbose headers   etag: '"38NUI3LOQB8F5NWZ21M23N1B1"',
21 verbose headers   'content-type': 'application/json',
21 verbose headers   'content-encoding': 'gzip',
21 verbose headers   'cache-control': 'max-age=300',
21 verbose headers   'content-length': '6433',
21 verbose headers   'accept-ranges': 'bytes',
21 verbose headers   date: 'Wed, 27 Apr 2016 20:49:43 GMT',
21 verbose headers   via: '1.1 varnish',
21 verbose headers   age: '79',
21 verbose headers   connection: 'keep-alive',
21 verbose headers   'x-served-by': 'cache-lax1432-LAX',
21 verbose headers   'x-cache': 'HIT',
21 verbose headers   'x-cache-hits': '9',
21 verbose headers   'x-timer': 'S1461790183.272075,VS0,VE0',
21 verbose headers   vary: 'Accept-Encoding' }
22 silly get cb [ 200,
22 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
22 silly get     etag: '"38NUI3LOQB8F5NWZ21M23N1B1"',
22 silly get     'content-type': 'application/json',
22 silly get     'content-encoding': 'gzip',
22 silly get     'cache-control': 'max-age=300',
22 silly get     'content-length': '6433',
22 silly get     'accept-ranges': 'bytes',
22 silly get     date: 'Wed, 27 Apr 2016 20:49:43 GMT',
22 silly get     via: '1.1 varnish',
22 silly get     age: '79',
22 silly get     connection: 'keep-alive',
22 silly get     'x-served-by': 'cache-lax1432-LAX',
22 silly get     'x-cache': 'HIT',
22 silly get     'x-cache-hits': '9',
22 silly get     'x-timer': 'S1461790183.272075,VS0,VE0',
22 silly get     vary: 'Accept-Encoding' } ]
23 verbose get saving graceful-fs to /Users/pablomotta/.npm/registry.npmjs.org/graceful-fs/.cache.json
24 verbose correctMkdir /Users/pablomotta/.npm correctMkdir not in flight; initializing
25 silly fetchPackageMetaData Error: No compatible version found: graceful-fs@4.0.0
25 silly fetchPackageMetaData Valid install targets:
25 silly fetchPackageMetaData 4.1.3, 4.1.2, 4.1.1, 4.1.0, 3.0.8, 3.0.7, 3.0.6, 3.0.5, 3.0.4, 3.0.3, 3.0.2, 3.0.1, 3.0.0, 2.0.3, 2.0.2, 2.0.1, 2.0.0, 1.2.3, 1.2.2, 1.2.1, 1.2.0, 1.1.14, 1.1.13, 1.1.12, 1.1.11, 1.1.10, 1.1.9, 1.1.8, 1.1.7, 1.1.6, 1.1.5, 1.1.4, 1.1.3, 1.1.2, 1.1.1, 1.1.0, 1.0.2, 1.0.1, 1.0.0
25 silly fetchPackageMetaData
25 silly fetchPackageMetaData     at pickVersionFromRegistryDocument (/usr/local/lib/node_modules/npm/lib/fetch-package-metadata.js:156:16)
25 silly fetchPackageMetaData     at /usr/local/lib/node_modules/npm/node_modules/iferr/index.js:13:50
25 silly fetchPackageMetaData     at /usr/local/lib/node_modules/npm/lib/utils/pulse-till-done.js:19:8
25 silly fetchPackageMetaData     at saved (/usr/local/lib/node_modules/npm/lib/cache/caching-client.js:168:7)
25 silly fetchPackageMetaData     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:210:7
25 silly fetchPackageMetaData     at FSReqWrap.oncomplete (fs.js:82:15)
25 silly fetchPackageMetaData  error for graceful-fs@4.0.0 [Error: No compatible version found: graceful-fs@4.0.0
25 silly fetchPackageMetaData Valid install targets:
25 silly fetchPackageMetaData 4.1.3, 4.1.2, 4.1.1, 4.1.0, 3.0.8, 3.0.7, 3.0.6, 3.0.5, 3.0.4, 3.0.3, 3.0.2, 3.0.1, 3.0.0, 2.0.3, 2.0.2, 2.0.1, 2.0.0, 1.2.3, 1.2.2, 1.2.1, 1.2.0, 1.1.14, 1.1.13, 1.1.12, 1.1.11, 1.1.10, 1.1.9, 1.1.8, 1.1.7, 1.1.6, 1.1.5, 1.1.4, 1.1.3, 1.1.2, 1.1.1, 1.1.0, 1.0.2, 1.0.1, 1.0.0
25 silly fetchPackageMetaData ]
26 silly rollbackFailedOptional Starting
27 silly rollbackFailedOptional Finishing
28 silly runTopLevelLifecycles Starting
29 silly runTopLevelLifecycles Finishing
30 silly install printInstalled
31 verbose stack Error: No compatible version found: graceful-fs@4.0.0
31 verbose stack Valid install targets:
31 verbose stack 4.1.3, 4.1.2, 4.1.1, 4.1.0, 3.0.8, 3.0.7, 3.0.6, 3.0.5, 3.0.4, 3.0.3, 3.0.2, 3.0.1, 3.0.0, 2.0.3, 2.0.2, 2.0.1, 2.0.0, 1.2.3, 1.2.2, 1.2.1, 1.2.0, 1.1.14, 1.1.13, 1.1.12, 1.1.11, 1.1.10, 1.1.9, 1.1.8, 1.1.7, 1.1.6, 1.1.5, 1.1.4, 1.1.3, 1.1.2, 1.1.1, 1.1.0, 1.0.2, 1.0.1, 1.0.0
31 verbose stack
31 verbose stack     at pickVersionFromRegistryDocument (/usr/local/lib/node_modules/npm/lib/fetch-package-metadata.js:156:16)
31 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/iferr/index.js:13:50
31 verbose stack     at /usr/local/lib/node_modules/npm/lib/utils/pulse-till-done.js:19:8
31 verbose stack     at saved (/usr/local/lib/node_modules/npm/lib/cache/caching-client.js:168:7)
31 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:210:7
31 verbose stack     at FSReqWrap.oncomplete (fs.js:82:15)
32 verbose cwd /Users/pablomotta/ember-app-1
33 error Darwin 15.3.0
34 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "graceful-fs@4.0.0"
35 error node v5.9.0
36 error npm  v3.8.6
37 error No compatible version found: graceful-fs@4.0.0
37 error Valid install targets:
37 error 4.1.3, 4.1.2, 4.1.1, 4.1.0, 3.0.8, 3.0.7, 3.0.6, 3.0.5, 3.0.4, 3.0.3, 3.0.2, 3.0.1, 3.0.0, 2.0.3, 2.0.2, 2.0.1, 2.0.0, 1.2.3, 1.2.2, 1.2.1, 1.2.0, 1.1.14, 1.1.13, 1.1.12, 1.1.11, 1.1.10, 1.1.9, 1.1.8, 1.1.7, 1.1.6, 1.1.5, 1.1.4, 1.1.3, 1.1.2, 1.1.1, 1.1.0, 1.0.2, 1.0.1, 1.0.0
38 error If you need help, you may report this error at:
38 error     <https://github.com/npm/npm/issues>
39 verbose exit [ 1, true ]
```

**Comment by CGavrila** [comment]
```

**Comment by pmacklin** [comment]
I am also running into the same stack trace when just trying to run npm install. The relevant part of the `npm-debug.log` is this:

```
32904 verbose stack TypeError: Cannot convert undefined or null to object
32904 verbose stack     at Function.keys (native)
32904 verbose stack     at pickVersionFromRegistryDocument (/opt/buildagent/BuildAgent/work/909bfc51eaa259f0/ui/src/main/resources/static/node/node_modules/npm/lib/fetch-package-metadata.js:126:29)
32904 verbose stack     at /opt/buildagent/BuildAgent/work/909bfc51eaa259f0/ui/src/main/resources/static/node/node_modules/npm/node_modules/iferr/index.js:13:50
32904 verbose stack     at /opt/buildagent/BuildAgent/work/909bfc51eaa259f0/ui/src/main/resources/static/node/node_modules/npm/lib/utils/pulse-till-done.js:19:8
32904 verbose stack     at saved (/opt/buildagent/BuildAgent/work/909bfc51eaa259f0/ui/src/main/resources/static/node/node_modules/npm/lib/cache/caching-client.js:174:7)
32904 verbose stack     at /opt/buildagent/BuildAgent/work/909bfc51eaa259f0/ui/src/main/resources/static/node/node_modules/npm/node_modules/graceful-fs/polyfills.js:210:7
32904 verbose stack     at FSReqWrap.oncomplete (fs.js:82:15)
```

I slapped the debug statment `log.info(JSON.stringify(pkg, null, 2))` into the `pickVersionFromRegistryDocument` function of `file fetch-package-metadata.js` from the stack trace and it tells me the package it's trying to get metadata for is this:

```
24742 info {
  "name": "natives",
  "time": {
    "modified": "2010-12-30T11:53:58.228Z"
  }
}
```

As the log said above, we're not on latest node or npm. I will try updating those tomorrow, but I'm not holding a lot of hope for an easy fix.

**Comment by SilverDFlame** [comment]
Here's what I'm seeing when trying to  install `graceful-fs`, There's a new dependency written by IsaacS, that npm isn't seeing right.

```
13:46:35 npm sill addNameRange number 2 { name: 'natives', range: '>=1.0.1 <2.0.0', hasData: true }
13:46:35 npm sill addNameRange versions [ 'natives', [] ]
13:46:35 npm verb stack TypeError: Cannot read property 'latest' of undefined
13:46:35 npm verb stack     at next (/opt/nodejs/node-v4.4.3-linux-x64/lib/node_modules/npm/lib/cache/add-named.js:248:35)
13:46:35 npm verb stack     at setData (/opt/nodejs/node-v4.4.3-linux-x64/lib/node_modules/npm/lib/cache/add-named.js:236:5)
13:46:35 npm verb stack     at RES (/opt/nodejs/node-v4.4.3-linux-x64/lib/node_modules/npm/node_modules/inflight/inflight.js:23:14)
13:46:35 npm verb stack     at f (/opt/nodejs/node-v4.4.3-linux-x64/lib/node_modules/npm/node_modules/once/once.js:17:25)
13:46:35 npm verb stack     at fixName (/opt/nodejs/node-v4.4.3-linux-x64/lib/node_modules/npm/lib/cache/add-named.js:29:5)
13:46:35 npm verb stack     at saved (/opt/nodejs/node-v4.4.3-linux-x64/lib/node_modules/npm/lib/cache/caching-client.js:173:7)
13:46:35 npm verb stack     at /opt/nodejs/node-v4.4.3-linux-x64/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:210:7
13:46:35 npm verb stack     at FSReqWrap.oncomplete (fs.js:82:15)
13:46:35 npm verb cwd /var/lib/jenkins/jobs/guest-connect-v1-build/workspace/public
13:46:35 npm ERR! Linux 4.1.10-17.31.amzn1.x86_64
13:46:35 npm ERR! argv "/opt/nodejs/node-v4.4.3-linux-x64/bin/node" "/opt/nodejs/node-v4.4.3-linux-x64/bin/npm" "install" "--loglevel" "silly"
13:46:35 npm ERR! node v4.4.3
13:46:35 npm ERR! npm  v2.15.1
13:46:35 
13:46:35 npm ERR! Cannot read property 'latest' of undefined
13:46:35 npm ERR! 
13:46:35 npm ERR! If you need help, you may report this error at:
13:46:35 npm ERR!     <https://github.com/npm/npm/issues>
```

Notice on the second line, where it's talking about versions, the array of versions is empty. This is why the install is failing.
