### ISSUE TITLE
error while using npm start

### ISSUE THREAD

**Issue by divyabiyani** [npm/npm#12527]
while trying to use keystonejs-site locally,when i use the command npm start but then this error occurs:

```
module.js:327
    throw err;
    ^

Error: Cannot find module './lib/less-node'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/divya/Documents/keystonejs-site/node_modules/less/index.js:1:80)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

npm ERR! Linux 3.19.0-58-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.4.3
npm ERR! npm  v3.8.8
npm ERR! code ELIFECYCLE
npm ERR! keystonejs-site@0.3.14 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the keystonejs-site@0.3.14 start script 'node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the keystonejs-site package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs keystonejs-site
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls keystonejs-site
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/divya/Documents/keystonejs-site/npm-debug.log
```

**Comment by Stas-Buzunko** [comment]
bon@bon-K72Dr:~/work/redux/examples/todos$ npm start

> redux-todos-example@0.0.0 start /home/bon/work/redux/examples/todos
> node server.js

events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3000
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at Server._listen2 (net.js:1227:14)
    at listen (net.js:1263:10)
    at Server.listen (net.js:1359:5)
    at EventEmitter.listen (/home/bon/work/redux/examples/todos/node_modules/express/lib/application.js:617:24)
    at Object.<anonymous> (/home/bon/work/redux/examples/todos/server.js:17:5)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)

npm ERR! Linux 3.19.0-58-generic
npm ERR! argv "/home/bon/.nvm/v5.6.0/bin/node" "/home/bon/.nvm/v5.6.0/bin/npm" "start"
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! redux-todos-example@0.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the redux-todos-example@0.0.0 start script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the redux-todos-example package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs redux-todos-example
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls redux-todos-example
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/bon/work/redux/examples/todos/npm-debug.log

**Comment by Stas-Buzunko** [comment]
Upgraded NPM and Node to lastest
bon@bon-K72Dr://home/bon/work/redux/examples/counter$ npm start

> redux-counter-example@0.0.0 start /home/bon/work/redux/examples/counter
> node server.js

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3000
    at Object.exports._errnoException (util.js:953:11)
    at exports._exceptionWithHostPort (util.js:976:20)
    at Server._listen2 (net.js:1253:14)
    at listen (net.js:1289:10)
    at Server.listen (net.js:1385:5)
    at EventEmitter.listen (/home/bon/work/redux/examples/counter/node_modules/express/lib/application.js:617:24)
    at Object.<anonymous> (/home/bon/work/redux/examples/counter/server.js:17:5)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)

npm ERR! Linux 3.19.0-58-generic
npm ERR! argv "/home/bon/.nvm/v6.2.0/bin/node" "/home/bon/.nvm/v6.2.0/bin/npm" "start"
npm ERR! node v6.2.0
npm ERR! npm  v3.9.0
npm ERR! code ELIFECYCLE
npm ERR! redux-counter-example@0.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the redux-counter-example@0.0.0 start script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the redux-counter-example package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs redux-counter-example
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls redux-counter-example
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/bon/work/redux/examples/counter/npm-debug.log
