### ISSUE TITLE
npm list -g gives me a call stack size error

### ISSUE THREAD

**Issue by craigp** [npm/npm#12525]
Here's the debug log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node4-lts/4.4.3/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'list',
1 verbose cli   '-g' ]
2 info using npm@2.15.1
3 info using node@v4.4.3
4 warn unmet dependency /usr/local/lib/node_modules/ember-cli requires lodash@'^3.6.0' but will load
4 warn unmet dependency /usr/local/lib/node_modules/lodash,
4 warn unmet dependency which is version 4.5.0
5 warn unmet dependency /usr/local/lib/node_modules/keybase requires keybase-installer@'1.0.2' but will load
5 warn unmet dependency /usr/local/lib/node_modules/keybase-installer,
5 warn unmet dependency which is version 1.0.3
6 warn unmet dependency /usr/local/lib/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents/node_modules/node-pre-gyp/node_modules/tar-pack requires rimraf@'~2.2.0' but will load
6 warn unmet dependency /usr/local/lib/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents/node_modules/node-pre-gyp/node_modules/rimraf,
6 warn unmet dependency which is version 2.4.3
7 warn unmet dependency /usr/local/lib/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents/node_modules/node-pre-gyp/node_modules/tar-pack requires tar@'~0.1.17' but will load
7 warn unmet dependency /usr/local/lib/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents/node_modules/node-pre-gyp/node_modules/tar,
7 warn unmet dependency which is version 2.2.1
8 verbose stack RangeError: Maximum call stack size exceeded
8 verbose stack     at Array.forEach (native)
8 verbose stack     at bfsify (/usr/local/lib/node_modules/npm/lib/ls.js:214:21)
8 verbose stack     at bfsify (/usr/local/lib/node_modules/npm/lib/ls.js:234:10)
8 verbose stack     at bfsify (/usr/local/lib/node_modules/npm/lib/ls.js:234:10)
8 verbose stack     at bfsify (/usr/local/lib/node_modules/npm/lib/ls.js:234:10)
8 verbose stack     at bfsify (/usr/local/lib/node_modules/npm/lib/ls.js:234:10)
8 verbose stack     at bfsify (/usr/local/lib/node_modules/npm/lib/ls.js:234:10)
8 verbose stack     at bfsify (/usr/local/lib/node_modules/npm/lib/ls.js:234:10)
8 verbose stack     at bfsify (/usr/local/lib/node_modules/npm/lib/ls.js:234:10)
8 verbose stack     at bfsify (/usr/local/lib/node_modules/npm/lib/ls.js:234:10)
9 verbose cwd /Users/craig
10 error Darwin 15.4.0
11 error argv "/usr/local/Cellar/node4-lts/4.4.3/bin/node" "/usr/local/bin/npm" "list" "-g"
12 error node v4.4.3
13 error npm  v2.15.1
14 error Maximum call stack size exceeded
15 error If you need help, you may report this error at:
15 error     <https://github.com/npm/npm/issues>
16 verbose exit [ 1, true ]
```

**Comment by helio-frota** [comment]
hi,
I can't reproduce on ubuntu (inside virtualbox) even after install 326 modules globally.

```
foo@npmbox:~/bar$ npm -v; node -v ; npm list -g --depth=0 | wc -l
2.15.1
v4.4.3
327      ( minus first line === 326 modules)
``` 

> Makes no sense to post all the packages names here
