### ISSUE TITLE
errors while attempting to update NPM

### ISSUE THREAD

**Issue by DH-Cykul** [npm/npm#12537]
Getting the following errors while attempting to update NPM.  Please see below:
```
pi@raspberrypi:~ $ sudo npm i -g npm@2.x
npm ERR! Error: CERT_NOT_YET_VALID
npm ERR!     at SecurePair.<anonymous> (tls.js:1365:32)
npm ERR!     at SecurePair.emit (events.js:92:17)
npm ERR!     at SecurePair.maybeInitFinished (tls.js:977:10)
npm ERR!     at CleartextStream.read [as _read] (tls.js:469:13)
npm ERR!     at CleartextStream.Readable.read (_stream_readable.js:323:10)
npm ERR!     at EncryptedStream.write [as _write] (tls.js:366:25)
npm ERR!     at doWrite (_stream_writable.js:226:10)
npm ERR!     at writeOrBuffer (_stream_writable.js:216:5)
npm ERR!     at EncryptedStream.Writable.write (_stream_writable.js:183:11)
npm ERR!     at write (_stream_readable.js:585:24)
npm ERR!     at flow (_stream_readable.js:594:7)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.1.19-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "i" "-g" "npm@2.x"
npm ERR! cwd /home/pi
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/npm-debug.log
npm ERR! not ok code 0
pi@raspberrypi:~ $ 
```

**Comment by somebody1234** [comment]
See #2902
Are you sure your computer's clock has the correct time?

**Comment by DH-Cykul** [comment]
Yup - time was the issue!  Thank you very much.
