### ISSUE TITLE
npm install --save botbuilder

### ISSUE THREAD

**Issue by Rajendra-Gage** [npm/npm#12531]
if that issue is old one then really feel sorry.... 
if you have any solution for that please provide it to me

**Comment by Rajendra-Gage** [comment]
This my log

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '--save',
1 verbose cli   'botbuilder' ]
2 info using npm@3.8.6
3 info using node@v6.0.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData botbuilder
8 silly fetchNamedPackageData botbuilder
9 silly mapToRegistry name botbuilder
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'botbuilder',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   name: 'botbuilder',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/botbuilder
14 verbose request uri https://registry.npmjs.org/botbuilder
15 verbose request no auth needed
16 info attempt registry request try #1 at 12:53:08 PM
17 verbose request id af685a5928251968
18 http request GET https://registry.npmjs.org/botbuilder
19 info retry will retry, error on last attempt: Error: unable to verify the first certificate
20 info attempt registry request try #2 at 12:53:18 PM
21 http request GET https://registry.npmjs.org/botbuilder
22 info retry will retry, error on last attempt: Error: unable to verify the first certificate
23 info attempt registry request try #3 at 12:54:19 PM
24 http request GET https://registry.npmjs.org/botbuilder
25 silly fetchPackageMetaData Error: unable to verify the first certificate
25 silly fetchPackageMetaData     at Error (native)
25 silly fetchPackageMetaData     at TLSSocket.<anonymous> (_tls_wrap.js:1055:38)
25 silly fetchPackageMetaData     at emitNone (events.js:86:13)
25 silly fetchPackageMetaData     at TLSSocket.emit (events.js:185:7)
25 silly fetchPackageMetaData     at TLSSocket._finishInit (_tls_wrap.js:580:8)
25 silly fetchPackageMetaData     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:412:38)
25 silly fetchPackageMetaData  error for botbuilder { Error: unable to verify the first certificate
25 silly fetchPackageMetaData     at Error (native)
25 silly fetchPackageMetaData     at TLSSocket.<anonymous> (_tls_wrap.js:1055:38)
25 silly fetchPackageMetaData     at emitNone (events.js:86:13)
25 silly fetchPackageMetaData     at TLSSocket.emit (events.js:185:7)
25 silly fetchPackageMetaData     at TLSSocket._finishInit (_tls_wrap.js:580:8)
25 silly fetchPackageMetaData     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:412:38) code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE' }
26 silly rollbackFailedOptional Starting
27 silly rollbackFailedOptional Finishing
28 silly runTopLevelLifecycles Starting
29 silly runTopLevelLifecycles Finishing
30 silly install printInstalled
31 verbose stack Error: unable to verify the first certificate
31 verbose stack     at Error (native)
31 verbose stack     at TLSSocket.<anonymous> (_tls_wrap.js:1055:38)
31 verbose stack     at emitNone (events.js:86:13)
31 verbose stack     at TLSSocket.emit (events.js:185:7)
31 verbose stack     at TLSSocket._finishInit (_tls_wrap.js:580:8)
31 verbose stack     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:412:38)
32 verbose cwd C:\Users\Trutech-61\AppData\Roaming
33 error Windows_NT 10.0.10586
34 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "botbuilder"
35 error node v6.0.0
36 error npm  v3.8.6
37 error code UNABLE_TO_VERIFY_LEAF_SIGNATURE
38 error unable to verify the first certificate
39 error If you need help, you may report this error at:
39 error     <https://github.com/npm/npm/issues>
40 verbose exit [ 1, true ]

**Comment by Rajendra-Gage** [comment]
that was the ssl issue that will solve by using 
npm config set strict-ssl false
