### ISSUE TITLE
"cannot publish over the previously published version" with new package

### ISSUE THREAD

**Issue by quarterto** [npm/npm#12533]
Publishing a never-before-published package has started giving me this error. It seems that a publish does go through, but for whatever reason it's attempting to publish twice. This seems to be similar to #9102, but I'm not publishing a tarball, it's just an ordinary publish.

The start of this issue did coincide with me setting up local-npm (and there is nolanlawson/local-npm#118), but it occurs when using the standard registry.

```
Error: "You cannot publish over the previously published version 1.0.0." : @quarterto/testsrntrsnt
    at makeError (/usr/local/lib/node_modules/gist-publish-npm/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
    at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/gist-publish-npm/node_modules/npm/node_modules/npm-registry-client/lib/request.js:252:14)
    at Request._callback (/usr/local/lib/node_modules/gist-publish-npm/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
    at Request.self.callback (/usr/local/lib/node_modules/gist-publish-npm/node_modules/npm/node_modules/request/request.js:199:22)
    at emitTwo (events.js:100:13)
    at Request.emit (events.js:185:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/gist-publish-npm/node_modules/npm/node_modules/request/request.js:1036:10)
    at emitOne (events.js:95:20)
    at Request.emit (events.js:182:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/gist-publish-npm/node_modules/npm/node_modules/request/request.js:963:12)
    at emitNone (events.js:85:20)
    at IncomingMessage.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:913:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by ramiel** [comment]
It si the same for me. I try to publish a new version but npm says it is trying to publish the previous one and, obviously, it fails.

npm version 3.10.10
node version 6.9.5

**Comment by ramiel** [comment]
Sorry, it's my fault. I simply forgot to update package.json

**Comment by MuhammadTaha** [comment]
Well you have to explicitly update the package.json file on both dist and as well as on root of the library in case of Angular2+
