### ISSUE TITLE
npm ERR! git clone - fatal: Could not read from remote repository

### ISSUE THREAD

**Issue by DJviolin** [npm/npm#12534]
I changed my dependencies to github format in my `package.json`:

``` json
  "dependencies": {
    "express": "expressjs/express"
  },
```

This resulting the following error on my Windows 10 x64 machine:

```
$ npm install
npm ERR! git clone C:\Users\Lanti\AppData\Roaming\npm-cache\_git-remotes\git-github-com-expressjs-express-git-4fc9075c C:\Users\Lanti\AppData\Local\Temp\npm-4260-5bdfb1b4\git-cache-dc8b3bef\f3d99a4fdbe1531ea609e92c4d4ae6c269d78c7a: Cloning into 'C:\Users\Lanti\AppData\Local\Temp\npm-4260-5bdfb1b4\git-cache-dc8b3bef\f3d99a4fdbe1531ea609e92c4d4ae6c269d78c7a'...
npm ERR! git clone C:\Users\Lanti\AppData\Roaming\npm-cache\_git-remotes\git-github-com-expressjs-express-git-4fc9075c C:\Users\Lanti\AppData\Local\Temp\npm-4260-5bdfb1b4\git-cache-dc8b3bef\f3d99a4fdbe1531ea609e92c4d4ae6c269d78c7a: fatal: '/c/Users/Lanti/AppData/Roaming/npm-cache/_git-remotes/git-github-com-expressjs-express-git-4fc9075c/C:\Users\Lanti\AppData\Roaming\npm-cache\_git-remotes\git-github-com-expressjs-express-git-4fc9075c' does not appear to be a git repository
npm ERR! git clone C:\Users\Lanti\AppData\Roaming\npm-cache\_git-remotes\git-github-com-expressjs-express-git-4fc9075c C:\Users\Lanti\AppData\Local\Temp\npm-4260-5bdfb1b4\git-cache-dc8b3bef\f3d99a4fdbe1531ea609e92c4d4ae6c269d78c7a: fatal: Could not read from remote repository.
npm ERR! git clone C:\Users\Lanti\AppData\Roaming\npm-cache\_git-remotes\git-github-com-expressjs-express-git-4fc9075c C:\Users\Lanti\AppData\Local\Temp\npm-4260-5bdfb1b4\git-cache-dc8b3bef\f3d99a4fdbe1531ea609e92c4d4ae6c269d78c7a:
npm ERR! git clone C:\Users\Lanti\AppData\Roaming\npm-cache\_git-remotes\git-github-com-expressjs-express-git-4fc9075c C:\Users\Lanti\AppData\Local\Temp\npm-4260-5bdfb1b4\git-cache-dc8b3bef\f3d99a4fdbe1531ea609e92c4d4ae6c269d78c7a: Please make sure you have the correct access rights
npm ERR! git clone C:\Users\Lanti\AppData\Roaming\npm-cache\_git-remotes\git-github-com-expressjs-express-git-4fc9075c C:\Users\Lanti\AppData\Local\Temp\npm-4260-5bdfb1b4\git-cache-dc8b3bef\f3d99a4fdbe1531ea609e92c4d4ae6c269d78c7a: and the repository exists.
npm ERR! git clone C:\Users\Lanti\AppData\Roaming\npm-cache\_git-remotes\git-github-com-expressjs-express-git-4fc9075c C:\Users\Lanti\AppData\Local\Temp\npm-4260-5bdfb1b4\git-cache-dc8b3bef\f3d99a4fdbe1531ea609e92c4d4ae6c269d78c7a:
npm ERR! git clone C:\Users\Lanti\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-expressjs-express-git-e794d15d C:\Users\Lanti\AppData\Local\Temp\npm-4260-5bdfb1b4\git-cache-67f738e7\f3d99a4fdbe1531ea609e92c4d4ae6c269d78c7a: Cloning into 'C:\Users\Lanti\AppData\Local\Temp\npm-4260-5bdfb1b4\git-cache-67f738e7\f3d99a4fdbe1531ea609e92c4d4ae6c269d78c7a'...
npm ERR! git clone C:\Users\Lanti\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-expressjs-express-git-e794d15d C:\Users\Lanti\AppData\Local\Temp\npm-4260-5bdfb1b4\git-cache-67f738e7\f3d99a4fdbe1531ea609e92c4d4ae6c269d78c7a: fatal: '/c/Users/Lanti/AppData/Roaming/npm-cache/_git-remotes/git-https-github-com-expressjs-express-git-e794d15d/C:\Users\Lanti\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-expressjs-express-git-e794d15d' does not appear to be a git repository
npm ERR! git clone C:\Users\Lanti\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-expressjs-express-git-e794d15d C:\Users\Lanti\AppData\Local\Temp\npm-4260-5bdfb1b4\git-cache-67f738e7\f3d99a4fdbe1531ea609e92c4d4ae6c269d78c7a: fatal: Could not read from remote repository.
npm ERR! git clone C:\Users\Lanti\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-expressjs-express-git-e794d15d C:\Users\Lanti\AppData\Local\Temp\npm-4260-5bdfb1b4\git-cache-67f738e7\f3d99a4fdbe1531ea609e92c4d4ae6c269d78c7a:

npm ERR! git clone C:\Users\Lanti\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-expressjs-express-git-e794d15d C:\Users\Lanti\AppData\Local\Temp\npm-4260-5bdfb1b4\git-cache-67f738e7\f3d99a4fdbe1531ea609e92c4d4ae6c269d78c7a: Please make sure you have the correct access rights
npm ERR! git clone C:\Users\Lanti\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-expressjs-express-git-e794d15d C:\Users\Lanti\AppData\Local\Temp\npm-4260-5bdfb1b4\git-cache-67f738e7\f3d99a4fdbe1531ea609e92c4d4ae6c269d78c7a: and the repository exists.
npm ERR! git clone C:\Users\Lanti\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-expressjs-express-git-e794d15d C:\Users\Lanti\AppData\Local\Temp\npm-4260-5bdfb1b4\git-cache-67f738e7\f3d99a4fdbe1531ea609e92c4d4ae6c269d78c7a:

npm ERR! git clone C:\Users\Lanti\AppData\Roaming\npm-cache\_git-remotes\git-github-com-expressjs-express-git-6bb82fdf C:\Users\Lanti\AppData\Local\Temp\npm-4260-5bdfb1b4\git-cache-1083ba7b\f3d99a4fdbe1531ea609e92c4d4ae6c269d78c7a: Cloning into 'C:\Users\Lanti\AppData\Local\Temp\npm-4260-5bdfb1b4\git-cache-1083ba7b\f3d99a4fdbe1531ea609e92c4d4ae6c269d78c7a'...
npm ERR! git clone C:\Users\Lanti\AppData\Roaming\npm-cache\_git-remotes\git-github-com-expressjs-express-git-6bb82fdf C:\Users\Lanti\AppData\Local\Temp\npm-4260-5bdfb1b4\git-cache-1083ba7b\f3d99a4fdbe1531ea609e92c4d4ae6c269d78c7a: fatal: '/c/Users/Lanti/AppData/Roaming/npm-cache/_git-remotes/git-github-com-expressjs-express-git-6bb82fdf/C:\Users\Lanti\AppData\Roaming\npm-cache\_git-remotes\git-github-com-expressjs-express-git-6bb82fdf' does not appear to be a git repository
npm ERR! git clone C:\Users\Lanti\AppData\Roaming\npm-cache\_git-remotes\git-github-com-expressjs-express-git-6bb82fdf C:\Users\Lanti\AppData\Local\Temp\npm-4260-5bdfb1b4\git-cache-1083ba7b\f3d99a4fdbe1531ea609e92c4d4ae6c269d78c7a: fatal: Could not read from remote repository.
npm ERR! git clone C:\Users\Lanti\AppData\Roaming\npm-cache\_git-remotes\git-github-com-expressjs-express-git-6bb82fdf C:\Users\Lanti\AppData\Local\Temp\npm-4260-5bdfb1b4\git-cache-1083ba7b\f3d99a4fdbe1531ea609e92c4d4ae6c269d78c7a:
npm ERR! git clone C:\Users\Lanti\AppData\Roaming\npm-cache\_git-remotes\git-github-com-expressjs-express-git-6bb82fdf C:\Users\Lanti\AppData\Local\Temp\npm-4260-5bdfb1b4\git-cache-1083ba7b\f3d99a4fdbe1531ea609e92c4d4ae6c269d78c7a: Please make sure you have the correct access rights
npm ERR! git clone C:\Users\Lanti\AppData\Roaming\npm-cache\_git-remotes\git-github-com-expressjs-express-git-6bb82fdf C:\Users\Lanti\AppData\Local\Temp\npm-4260-5bdfb1b4\git-cache-1083ba7b\f3d99a4fdbe1531ea609e92c4d4ae6c269d78c7a: and the repository exists.
npm ERR! git clone C:\Users\Lanti\AppData\Roaming\npm-cache\_git-remotes\git-github-com-expressjs-express-git-6bb82fdf C:\Users\Lanti\AppData\Local\Temp\npm-4260-5bdfb1b4\git-cache-1083ba7b\f3d99a4fdbe1531ea609e92c4d4ae6c269d78c7a:
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.9
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true clone C:\Users\Lanti\AppData\Roaming\npm-cache\_git-remotes\git-github-com-expressjs-express-git-6bb82fdf C:\Users\Lanti\AppData\Local\Temp\npm-4260-5bdfb1b4\git-cache-1083ba7b\f3d99a4fdbe1531ea609e92c4d4ae6c269d78c7a
npm ERR! Cloning into 'C:\Users\Lanti\AppData\Local\Temp\npm-4260-5bdfb1b4\git-cache-1083ba7b\f3d99a4fdbe1531ea609e92c4d4ae6c269d78c7a'...
npm ERR! fatal: '/c/Users/Lanti/AppData/Roaming/npm-cache/_git-remotes/git-github-com-expressjs-express-git-6bb82fdf/C:\Users\Lanti\AppData\Roaming\npm-cache\_git-remotes\git-github-com-expressjs-express-git-6bb82fdf' does not appear to be a git repository
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\www\node\lantosistvan\npm-debug.log
```

I attaching the generated `npm-debug.log`:

``` txt
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@3.8.9
3 info using node@v6.0.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly install normalizeTree
8 silly loadCurrentTree Finishing
9 silly loadIdealTree Starting
10 silly install loadIdealTree
11 silly cloneCurrentTree Starting
12 silly install cloneCurrentTreeToIdealTree
13 silly cloneCurrentTree Finishing
14 silly loadShrinkwrap Starting
15 silly install loadShrinkwrap
16 silly loadShrinkwrap Finishing
17 silly loadAllDepsIntoIdealTree Starting
18 silly install loadAllDepsIntoIdealTree
19 silly fetchOtherPackageData express@github:expressjs/express
20 silly cache add args [ 'express@github:expressjs/express', null ]
21 verbose cache add spec express@github:expressjs/express
22 silly cache add parsed spec Result {
22 silly cache add   raw: 'express@github:expressjs/express',
22 silly cache add   scope: null,
22 silly cache add   name: 'express',
22 silly cache add   rawSpec: 'github:expressjs/express',
22 silly cache add   spec: 'github:expressjs/express',
22 silly cache add   type: 'hosted',
22 silly cache add   hosted:
22 silly cache add    { type: 'github',
22 silly cache add      ssh: 'git@github.com:expressjs/express.git',
22 silly cache add      sshUrl: 'git+ssh://git@github.com/expressjs/express.git',
22 silly cache add      httpsUrl: 'git+https://github.com/expressjs/express.git',
22 silly cache add      gitUrl: 'git://github.com/expressjs/express.git',
22 silly cache add      shortcut: 'github:expressjs/express',
22 silly cache add      directUrl: 'https://raw.githubusercontent.com/expressjs/express/master/package.json' } }
23 verbose addRemoteGit caching github:expressjs/express
24 verbose addRemoteGit expressjs/express is a repository hosted by github
25 silly tryGitProto attempting to clone git://github.com/expressjs/express.git
26 silly tryClone cloning expressjs/express via git://github.com/expressjs/express.git
27 verbose tryClone git-github-com-expressjs-express-git-4fc9075c not in flight; caching
28 verbose correctMkdir C:\Users\Lanti\AppData\Roaming\npm-cache\_git-remotes correctMkdir not in flight; initializing
29 verbose makeDirectory C:\Users\Lanti\AppData\Roaming\npm-cache\_git-remotes creation not in flight; initializing
30 verbose makeCacheDir UID & GID are irrelevant on win32
31 info git [ 'clone',
31 info git   '--template=C:\\Users\\Lanti\\AppData\\Roaming\\npm-cache\\_git-remotes\\_templates',
31 info git   '--mirror',
31 info git   'git://github.com/expressjs/express.git',
31 info git   'C:\\Users\\Lanti\\AppData\\Roaming\\npm-cache\\_git-remotes\\git-github-com-expressjs-express-git-4fc9075c' ]
32 verbose mirrorRemote expressjs/express git clone git://github.com/expressjs/express.git
33 verbose setPermissions expressjs/express skipping chownr on Windows
34 verbose resolveHead expressjs/express original treeish: master
35 info git [ 'rev-list', '-n1', 'master' ]
36 silly resolveHead expressjs/express resolved treeish: f3d99a4fdbe1531ea609e92c4d4ae6c269d78c7a
37 verbose resolveHead expressjs/express resolved Git URL: git://github.com/expressjs/express.git#f3d99a4fdbe1531ea609e92c4d4ae6c269d78c7a
38 silly resolveHead Git working directory: C:\Users\Lanti\AppData\Local\Temp\npm-4260-5bdfb1b4\git-cache-dc8b3bef\f3d99a4fdbe1531ea609e92c4d4ae6c269d78c7a
39 info git [ 'clone',
39 info git   'C:\\Users\\Lanti\\AppData\\Roaming\\npm-cache\\_git-remotes\\git-github-com-expressjs-express-git-4fc9075c',
39 info git   'C:\\Users\\Lanti\\AppData\\Local\\Temp\\npm-4260-5bdfb1b4\\git-cache-dc8b3bef\\f3d99a4fdbe1531ea609e92c4d4ae6c269d78c7a' ]
40 error git clone C:\Users\Lanti\AppData\Roaming\npm-cache\_git-remotes\git-github-com-expressjs-express-git-4fc9075c C:\Users\Lanti\AppData\Local\Temp\npm-4260-5bdfb1b4\git-cache-dc8b3bef\f3d99a4fdbe1531ea609e92c4d4ae6c269d78c7a: Cloning into 'C:\Users\Lanti\AppData\Local\Temp\npm-4260-5bdfb1b4\git-cache-dc8b3bef\f3d99a4fdbe1531ea609e92c4d4ae6c269d78c7a'...
40 error git clone C:\Users\Lanti\AppData\Roaming\npm-cache\_git-remotes\git-github-com-expressjs-express-git-4fc9075c C:\Users\Lanti\AppData\Local\Temp\npm-4260-5bdfb1b4\git-cache-dc8b3bef\f3d99a4fdbe1531ea609e92c4d4ae6c269d78c7a: fatal: '/c/Users/Lanti/AppData/Roaming/npm-cache/_git-remotes/git-github-com-expressjs-express-git-4fc9075c/C:\Users\Lanti\AppData\Roaming\npm-cache\_git-remotes\git-github-com-expressjs-express-git-4fc9075c' does not appear to be a git repository
40 error git clone C:\Users\Lanti\AppData\Roaming\npm-cache\_git-remotes\git-github-com-expressjs-express-git-4fc9075c C:\Users\Lanti\AppData\Local\Temp\npm-4260-5bdfb1b4\git-cache-dc8b3bef\f3d99a4fdbe1531ea609e92c4d4ae6c269d78c7a: fatal: Could not read from remote repository.
40 error git clone C:\Users\Lanti\AppData\Roaming\npm-cache\_git-remotes\git-github-com-expressjs-express-git-4fc9075c C:\Users\Lanti\AppData\Local\Temp\npm-4260-5bdfb1b4\git-cache-dc8b3bef\f3d99a4fdbe1531ea609e92c4d4ae6c269d78c7a:
40 error git clone C:\Users\Lanti\AppData\Roaming\npm-cache\_git-remotes\git-github-com-expressjs-express-git-4fc9075c C:\Users\Lanti\AppData\Local\Temp\npm-4260-5bdfb1b4\git-cache-dc8b3bef\f3d99a4fdbe1531ea609e92c4d4ae6c269d78c7a: Please make sure you have the correct access rights
40 error git clone C:\Users\Lanti\AppData\Roaming\npm-cache\_git-remotes\git-github-com-expressjs-express-git-4fc9075c C:\Users\Lanti\AppData\Local\Temp\npm-4260-5bdfb1b4\git-cache-dc8b3bef\f3d99a4fdbe1531ea609e92c4d4ae6c269d78c7a: and the repository exists.
41 silly tryHTTPS attempting to clone git+https://github.com/expressjs/express.git
42 silly tryClone cloning expressjs/express via git+https://github.com/expressjs/express.git
43 verbose tryClone git-https-github-com-expressjs-express-git-e794d15d not in flight; caching
44 verbose correctMkdir C:\Users\Lanti\AppData\Roaming\npm-cache\_git-remotes correctMkdir not in flight; initializing
45 info git [ 'clone',
45 info git   '--template=C:\\Users\\Lanti\\AppData\\Roaming\\npm-cache\\_git-remotes\\_templates',
45 info git   '--mirror',
45 info git   'https://github.com/expressjs/express.git',
45 info git   'C:\\Users\\Lanti\\AppData\\Roaming\\npm-cache\\_git-remotes\\git-https-github-com-expressjs-express-git-e794d15d' ]
46 verbose mirrorRemote expressjs/express git clone https://github.com/expressjs/express.git
47 verbose setPermissions expressjs/express skipping chownr on Windows
48 verbose resolveHead expressjs/express original treeish: master
49 info git [ 'rev-list', '-n1', 'master' ]
50 silly resolveHead expressjs/express resolved treeish: f3d99a4fdbe1531ea609e92c4d4ae6c269d78c7a
51 verbose resolveHead expressjs/express resolved Git URL: git+https://github.com/expressjs/express.git#f3d99a4fdbe1531ea609e92c4d4ae6c269d78c7a
52 silly resolveHead Git working directory: C:\Users\Lanti\AppData\Local\Temp\npm-4260-5bdfb1b4\git-cache-67f738e7\f3d99a4fdbe1531ea609e92c4d4ae6c269d78c7a
53 info git [ 'clone',
53 info git   'C:\\Users\\Lanti\\AppData\\Roaming\\npm-cache\\_git-remotes\\git-https-github-com-expressjs-express-git-e794d15d',
53 info git   'C:\\Users\\Lanti\\AppData\\Local\\Temp\\npm-4260-5bdfb1b4\\git-cache-67f738e7\\f3d99a4fdbe1531ea609e92c4d4ae6c269d78c7a' ]
54 error git clone C:\Users\Lanti\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-expressjs-express-git-e794d15d C:\Users\Lanti\AppData\Local\Temp\npm-4260-5bdfb1b4\git-cache-67f738e7\f3d99a4fdbe1531ea609e92c4d4ae6c269d78c7a: Cloning into 'C:\Users\Lanti\AppData\Local\Temp\npm-4260-5bdfb1b4\git-cache-67f738e7\f3d99a4fdbe1531ea609e92c4d4ae6c269d78c7a'...
54 error git clone C:\Users\Lanti\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-expressjs-express-git-e794d15d C:\Users\Lanti\AppData\Local\Temp\npm-4260-5bdfb1b4\git-cache-67f738e7\f3d99a4fdbe1531ea609e92c4d4ae6c269d78c7a: fatal: '/c/Users/Lanti/AppData/Roaming/npm-cache/_git-remotes/git-https-github-com-expressjs-express-git-e794d15d/C:\Users\Lanti\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-expressjs-express-git-e794d15d' does not appear to be a git repository
54 error git clone C:\Users\Lanti\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-expressjs-express-git-e794d15d C:\Users\Lanti\AppData\Local\Temp\npm-4260-5bdfb1b4\git-cache-67f738e7\f3d99a4fdbe1531ea609e92c4d4ae6c269d78c7a: fatal: Could not read from remote repository.
54 error git clone C:\Users\Lanti\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-expressjs-express-git-e794d15d C:\Users\Lanti\AppData\Local\Temp\npm-4260-5bdfb1b4\git-cache-67f738e7\f3d99a4fdbe1531ea609e92c4d4ae6c269d78c7a:
54 error git clone C:\Users\Lanti\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-expressjs-express-git-e794d15d C:\Users\Lanti\AppData\Local\Temp\npm-4260-5bdfb1b4\git-cache-67f738e7\f3d99a4fdbe1531ea609e92c4d4ae6c269d78c7a: Please make sure you have the correct access rights
54 error git clone C:\Users\Lanti\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-expressjs-express-git-e794d15d C:\Users\Lanti\AppData\Local\Temp\npm-4260-5bdfb1b4\git-cache-67f738e7\f3d99a4fdbe1531ea609e92c4d4ae6c269d78c7a: and the repository exists.
55 silly trySSH attempting to clone git@github.com:expressjs/express.git
56 silly tryClone cloning expressjs/express via git@github.com:expressjs/express.git
57 verbose tryClone git-github-com-expressjs-express-git-6bb82fdf not in flight; caching
58 verbose correctMkdir C:\Users\Lanti\AppData\Roaming\npm-cache\_git-remotes correctMkdir not in flight; initializing
59 info git [ 'clone',
59 info git   '--template=C:\\Users\\Lanti\\AppData\\Roaming\\npm-cache\\_git-remotes\\_templates',
59 info git   '--mirror',
59 info git   'git@github.com:expressjs/express.git',
59 info git   'C:\\Users\\Lanti\\AppData\\Roaming\\npm-cache\\_git-remotes\\git-github-com-expressjs-express-git-6bb82fdf' ]
60 verbose mirrorRemote expressjs/express git clone git@github.com:expressjs/express.git
61 verbose setPermissions expressjs/express skipping chownr on Windows
62 verbose resolveHead expressjs/express original treeish: master
63 info git [ 'rev-list', '-n1', 'master' ]
64 silly resolveHead expressjs/express resolved treeish: f3d99a4fdbe1531ea609e92c4d4ae6c269d78c7a
65 verbose resolveHead expressjs/express resolved Git URL: git+ssh://git@github.com/expressjs/express.git#f3d99a4fdbe1531ea609e92c4d4ae6c269d78c7a
66 silly resolveHead Git working directory: C:\Users\Lanti\AppData\Local\Temp\npm-4260-5bdfb1b4\git-cache-1083ba7b\f3d99a4fdbe1531ea609e92c4d4ae6c269d78c7a
67 info git [ 'clone',
67 info git   'C:\\Users\\Lanti\\AppData\\Roaming\\npm-cache\\_git-remotes\\git-github-com-expressjs-express-git-6bb82fdf',
67 info git   'C:\\Users\\Lanti\\AppData\\Local\\Temp\\npm-4260-5bdfb1b4\\git-cache-1083ba7b\\f3d99a4fdbe1531ea609e92c4d4ae6c269d78c7a' ]
68 error git clone C:\Users\Lanti\AppData\Roaming\npm-cache\_git-remotes\git-github-com-expressjs-express-git-6bb82fdf C:\Users\Lanti\AppData\Local\Temp\npm-4260-5bdfb1b4\git-cache-1083ba7b\f3d99a4fdbe1531ea609e92c4d4ae6c269d78c7a: Cloning into 'C:\Users\Lanti\AppData\Local\Temp\npm-4260-5bdfb1b4\git-cache-1083ba7b\f3d99a4fdbe1531ea609e92c4d4ae6c269d78c7a'...
68 error git clone C:\Users\Lanti\AppData\Roaming\npm-cache\_git-remotes\git-github-com-expressjs-express-git-6bb82fdf C:\Users\Lanti\AppData\Local\Temp\npm-4260-5bdfb1b4\git-cache-1083ba7b\f3d99a4fdbe1531ea609e92c4d4ae6c269d78c7a: fatal: '/c/Users/Lanti/AppData/Roaming/npm-cache/_git-remotes/git-github-com-expressjs-express-git-6bb82fdf/C:\Users\Lanti\AppData\Roaming\npm-cache\_git-remotes\git-github-com-expressjs-express-git-6bb82fdf' does not appear to be a git repository
68 error git clone C:\Users\Lanti\AppData\Roaming\npm-cache\_git-remotes\git-github-com-expressjs-express-git-6bb82fdf C:\Users\Lanti\AppData\Local\Temp\npm-4260-5bdfb1b4\git-cache-1083ba7b\f3d99a4fdbe1531ea609e92c4d4ae6c269d78c7a: fatal: Could not read from remote repository.
68 error git clone C:\Users\Lanti\AppData\Roaming\npm-cache\_git-remotes\git-github-com-expressjs-express-git-6bb82fdf C:\Users\Lanti\AppData\Local\Temp\npm-4260-5bdfb1b4\git-cache-1083ba7b\f3d99a4fdbe1531ea609e92c4d4ae6c269d78c7a:
68 error git clone C:\Users\Lanti\AppData\Roaming\npm-cache\_git-remotes\git-github-com-expressjs-express-git-6bb82fdf C:\Users\Lanti\AppData\Local\Temp\npm-4260-5bdfb1b4\git-cache-1083ba7b\f3d99a4fdbe1531ea609e92c4d4ae6c269d78c7a: Please make sure you have the correct access rights
68 error git clone C:\Users\Lanti\AppData\Roaming\npm-cache\_git-remotes\git-github-com-expressjs-express-git-6bb82fdf C:\Users\Lanti\AppData\Local\Temp\npm-4260-5bdfb1b4\git-cache-1083ba7b\f3d99a4fdbe1531ea609e92c4d4ae6c269d78c7a: and the repository exists.
69 silly fetchPackageMetaData Error: Command failed: git -c core.longpaths=true clone C:\Users\Lanti\AppData\Roaming\npm-cache\_git-remotes\git-github-com-expressjs-express-git-6bb82fdf C:\Users\Lanti\AppData\Local\Temp\npm-4260-5bdfb1b4\git-cache-1083ba7b\f3d99a4fdbe1531ea609e92c4d4ae6c269d78c7a
69 silly fetchPackageMetaData Cloning into 'C:\Users\Lanti\AppData\Local\Temp\npm-4260-5bdfb1b4\git-cache-1083ba7b\f3d99a4fdbe1531ea609e92c4d4ae6c269d78c7a'...
69 silly fetchPackageMetaData fatal: '/c/Users/Lanti/AppData/Roaming/npm-cache/_git-remotes/git-github-com-expressjs-express-git-6bb82fdf/C:\Users\Lanti\AppData\Roaming\npm-cache\_git-remotes\git-github-com-expressjs-express-git-6bb82fdf' does not appear to be a git repository
69 silly fetchPackageMetaData fatal: Could not read from remote repository.
69 silly fetchPackageMetaData
69 silly fetchPackageMetaData Please make sure you have the correct access rights
69 silly fetchPackageMetaData and the repository exists.
69 silly fetchPackageMetaData
69 silly fetchPackageMetaData     at ChildProcess.exithandler (child_process.js:202:12)
69 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
69 silly fetchPackageMetaData     at ChildProcess.emit (events.js:191:7)
69 silly fetchPackageMetaData     at maybeClose (internal/child_process.js:850:16)
69 silly fetchPackageMetaData     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
69 silly fetchPackageMetaData  error for express@github:expressjs/express { Error: Command failed: git -c core.longpaths=true clone C:\Users\Lanti\AppData\Roaming\npm-cache\_git-remotes\git-github-com-expressjs-express-git-6bb82fdf C:\Users\Lanti\AppData\Local\Temp\npm-4260-5bdfb1b4\git-cache-1083ba7b\f3d99a4fdbe1531ea609e92c4d4ae6c269d78c7a
69 silly fetchPackageMetaData Cloning into 'C:\Users\Lanti\AppData\Local\Temp\npm-4260-5bdfb1b4\git-cache-1083ba7b\f3d99a4fdbe1531ea609e92c4d4ae6c269d78c7a'...
69 silly fetchPackageMetaData fatal: '/c/Users/Lanti/AppData/Roaming/npm-cache/_git-remotes/git-github-com-expressjs-express-git-6bb82fdf/C:\Users\Lanti\AppData\Roaming\npm-cache\_git-remotes\git-github-com-expressjs-express-git-6bb82fdf' does not appear to be a git repository
69 silly fetchPackageMetaData fatal: Could not read from remote repository.
69 silly fetchPackageMetaData
69 silly fetchPackageMetaData Please make sure you have the correct access rights
69 silly fetchPackageMetaData and the repository exists.
69 silly fetchPackageMetaData
69 silly fetchPackageMetaData     at ChildProcess.exithandler (child_process.js:202:12)
69 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
69 silly fetchPackageMetaData     at ChildProcess.emit (events.js:191:7)
69 silly fetchPackageMetaData     at maybeClose (internal/child_process.js:850:16)
69 silly fetchPackageMetaData     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
69 silly fetchPackageMetaData   killed: false,
69 silly fetchPackageMetaData   code: 128,
69 silly fetchPackageMetaData   signal: null,
69 silly fetchPackageMetaData   cmd: 'git -c core.longpaths=true clone C:\\Users\\Lanti\\AppData\\Roaming\\npm-cache\\_git-remotes\\git-github-com-expressjs-express-git-6bb82fdf C:\\Users\\Lanti\\AppData\\Local\\Temp\\npm-4260-5bdfb1b4\\git-cache-1083ba7b\\f3d99a4fdbe1531ea609e92c4d4ae6c269d78c7a' }
70 silly rollbackFailedOptional Starting
71 silly rollbackFailedOptional Finishing
72 silly runTopLevelLifecycles Starting
73 silly runTopLevelLifecycles Finishing
74 silly install printInstalled
75 verbose stack Error: Command failed: git -c core.longpaths=true clone C:\Users\Lanti\AppData\Roaming\npm-cache\_git-remotes\git-github-com-expressjs-express-git-6bb82fdf C:\Users\Lanti\AppData\Local\Temp\npm-4260-5bdfb1b4\git-cache-1083ba7b\f3d99a4fdbe1531ea609e92c4d4ae6c269d78c7a
75 verbose stack Cloning into 'C:\Users\Lanti\AppData\Local\Temp\npm-4260-5bdfb1b4\git-cache-1083ba7b\f3d99a4fdbe1531ea609e92c4d4ae6c269d78c7a'...
75 verbose stack fatal: '/c/Users/Lanti/AppData/Roaming/npm-cache/_git-remotes/git-github-com-expressjs-express-git-6bb82fdf/C:\Users\Lanti\AppData\Roaming\npm-cache\_git-remotes\git-github-com-expressjs-express-git-6bb82fdf' does not appear to be a git repository
75 verbose stack fatal: Could not read from remote repository.
75 verbose stack
75 verbose stack Please make sure you have the correct access rights
75 verbose stack and the repository exists.
75 verbose stack
75 verbose stack     at ChildProcess.exithandler (child_process.js:202:12)
75 verbose stack     at emitTwo (events.js:106:13)
75 verbose stack     at ChildProcess.emit (events.js:191:7)
75 verbose stack     at maybeClose (internal/child_process.js:850:16)
75 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
76 verbose cwd C:\www\node\lantosistvan
77 error Windows_NT 10.0.10586
78 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
79 error node v6.0.0
80 error npm  v3.8.9
81 error code 128
82 error Command failed: git -c core.longpaths=true clone C:\Users\Lanti\AppData\Roaming\npm-cache\_git-remotes\git-github-com-expressjs-express-git-6bb82fdf C:\Users\Lanti\AppData\Local\Temp\npm-4260-5bdfb1b4\git-cache-1083ba7b\f3d99a4fdbe1531ea609e92c4d4ae6c269d78c7a
82 error Cloning into 'C:\Users\Lanti\AppData\Local\Temp\npm-4260-5bdfb1b4\git-cache-1083ba7b\f3d99a4fdbe1531ea609e92c4d4ae6c269d78c7a'...
82 error fatal: '/c/Users/Lanti/AppData/Roaming/npm-cache/_git-remotes/git-github-com-expressjs-express-git-6bb82fdf/C:\Users\Lanti\AppData\Roaming\npm-cache\_git-remotes\git-github-com-expressjs-express-git-6bb82fdf' does not appear to be a git repository
82 error fatal: Could not read from remote repository.
82 error
82 error Please make sure you have the correct access rights
82 error and the repository exists.
83 error If you need help, you may report this error at:
83 error     <https://github.com/npm/npm/issues>
84 verbose exit [ 1, true ]
```

`git@2.8.0` is installed by latest Cygwin x64. `cmd` ran as admin. `git push` with SSH works on my system. This is how I managing my app's repo.

Installing the packages with npm's way `"express": ">= 4.13.4"` works without problem.

**Comment by DJviolin** [comment]
Maybe this is more related: https://github.com/npm/npm/issues/10729

**Comment by dunets** [comment]
execute command line as administrator... for me that was the problem

**Comment by wolfand11** [comment]
my npm has the same error, any body solved the problem?
