### ISSUE TITLE
AWS EC2 npm make install problem

### ISSUE THREAD

**Issue by validator1** [npm/npm#12544]
I checked similar issues but did not find this exact error.
I'm trying to follow instructions for setting up an AWS environment running nodejs and npm. Here is the issue I've run into at the end of the process making the npm install.

```
$ make install
scripts/doc-build.sh doc/cli/npm-run-script.md man/man1/npm-run-script.1
make[1]: Entering directory `/root/npm'
node cli.js install marked-man --no-global

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick

TypeError: undefined is not a function
    at Object.<anonymous> (/root/npm/lib/config/cmd-list.js:111:33)
    at Module._compile (module.js:432:26)
    at Object..js (module.js:450:10)
    at Module.load (module.js:351:31)
    at Function._load (module.js:310:12)
    at Module.require (module.js:357:17)
    at require (module.js:368:17)
    at /root/npm/lib/npm.js:30:17
    at Object.<anonymous> (/root/npm/lib/npm.js:394:2)
    at Module._compile (module.js:432:26)
make[1]: *** [node_modules/.bin/marked-man] Error 1
make[1]: Leaving directory `/root/npm'
make: *** [man/man1/npm-run-script.1] Error 2
```

**Comment by busches** [comment]
Can you provide more information like what version of npm you were installing and what version of node?
