### ISSUE TITLE
Unable to publish a new package version

### ISSUE THREAD

**Issue by raphael-boucher** [npm/npm#12559]
I'm trying to publish an update for a package I have access to, and I have the error `you do not have permission to publish "systematic". Are you logged in as the correct user? : systematic`
The package name is `systematic`, here is my profile https://www.npmjs.com/~raphael-boucher
If it matters, I was given access the same day, and I can publish other packages.

Another maintainer could publish the package, but not when he tried with my token. I checked the token is a valid one (listed on my account), so I think the issue is not on the client side.

Debug log 

> 0 info it worked if it ends with ok
> 1 verbose cli [ '/home/raphael/.nvm/versions/node/v5.11.0/bin/node',
> 1 verbose cli   '/home/raphael/.nvm/versions/node/v5.11.0/bin/npm',
> 1 verbose cli   'publish',
> 1 verbose cli   '--registry',
> 1 verbose cli   'https://registry.npmjs.org' ]
> 2 info using npm@3.8.6
> 3 info using node@v5.11.0
> 4 verbose publish [ '.' ]
> 5 silly cache add args [ '.', null ]
> 6 verbose cache add spec .
> 7 silly cache add parsed spec Result {
> 7 silly cache add   raw: '.',
> 7 silly cache add   scope: null,
> 7 silly cache add   name: null,
> 7 silly cache add   rawSpec: '.',
> 7 silly cache add   spec: '/home/raphael/dev/systematic',
> 7 silly cache add   type: 'directory' }
> 8 verbose addLocalDirectory /home/raphael/.npm/systematic/0.1.2/package.tgz not in flight; packing
> 9 verbose correctMkdir /home/raphael/.npm correctMkdir not in flight; initializing
> 10 info lifecycle systematic@0.1.2~prepublish: systematic@0.1.2
> 11 silly lifecycle systematic@0.1.2~prepublish: no script for prepublish, continuing
> 12 verbose tar pack [ '/home/raphael/.npm/systematic/0.1.2/package.tgz',
> 12 verbose tar pack   '/home/raphael/dev/systematic' ]
> 13 verbose tarball /home/raphael/.npm/systematic/0.1.2/package.tgz
> 14 verbose folder /home/raphael/dev/systematic
> 15 verbose addLocalTarball adding from inside cache /home/raphael/.npm/systematic/0.1.2/package.tgz
> 16 verbose correctMkdir /home/raphael/.npm correctMkdir not in flight; initializing
> 17 silly cache afterAdd systematic@0.1.2
> 18 verbose afterAdd /home/raphael/.npm/systematic/0.1.2/package/package.json not in flight; writing
> 19 verbose correctMkdir /home/raphael/.npm correctMkdir not in flight; initializing
> 20 verbose afterAdd /home/raphael/.npm/systematic/0.1.2/package/package.json written
> 21 silly publish { name: 'systematic',
> 21 silly publish   version: '0.1.2',
> 21 silly publish   main: './index.js',
> 21 silly publish   description: 'Simple tooling for frontend apps',
> 21 silly publish   publishConfig: { registry: 'https://registry.npmjs.org' },
> 21 silly publish   repository:
> 21 silly publish    { type: 'git',
> 21 silly publish      url: 'git+https://github.com/polyconseil/systematic.git' },
> 21 silly publish   scripts: { test: 'No tests yet' },
> 21 silly publish   keywords: [],
> 21 silly publish   author: { name: 'Polyconseil' },
> 21 silly publish   license: 'MIT',
> 21 silly publish   files: [ '_', '!.gitignore' ],
> 21 silly publish   dependencies:
> 21 silly publish    { 'babel-core': '6.7.4',
> 21 silly publish      'babel-loader': '6.2.4',
> 21 silly publish      'babel-plugin-transform-strict-mode': '6.6.5',
> 21 silly publish      'babel-polyfill': '6.7.4',
> 21 silly publish      'babel-preset-es2015': '6.6.0',
> 21 silly publish      'css-loader': '0.23.1',
> 21 silly publish      easygettext: '1.0.3',
> 21 silly publish      eslint: '2.7.0',
> 21 silly publish      'file-loader': '0.8.5',
> 21 silly publish      'html-loader': '0.4.3',
> 21 silly publish      'html-webpack-plugin': '2.15.0',
> 21 silly publish      'http-server': '0.9.0',
> 21 silly publish      ini: '1.3.4',
> 21 silly publish      jade: '1.11.0',
> 21 silly publish      'jade-loader': '0.8.0',
> 21 silly publish      'jasmine-core': '2.4.1',
> 21 silly publish      'json-loader': '0.5.4',
> 21 silly publish      'karma-coverage': '0.5.5',
> 21 silly publish      'karma-jasmine': '0.3.8',
> 21 silly publish      'karma-jasmine-html-reporter': '0.2.0',
> 21 silly publish      'karma-jasmine-matchers': '2.0.2',
> 21 silly publish      'karma-junit-reporter': '0.4.1',
> 21 silly publish      'karma-mocha-reporter': '2.0.0',
> 21 silly publish      'karma-phantomjs-launcher': '1.0.0',
> 21 silly publish      'karma-phantomjs-shim': '1.2.0',
> 21 silly publish      'karma-sourcemap-loader': '0.3.7',
> 21 silly publish      'karma-webpack': '1.7.0',
> 21 silly publish      'live-server': '0.9.2',
> 21 silly publish      lodash: '4.8.2',
> 21 silly publish      'ng-annotate-loader': '0.1.0',
> 21 silly publish      'ng-annotate-webpack-plugin': '0.1.2',
> 21 silly publish      'ngtemplate-loader': '1.3.1',
> 21 silly publish      'node-sass': '3.4.2',
> 21 silly publish      'omit-tilde-webpack-plugin': '0.1.1',
> 21 silly publish      'phantomjs-prebuilt': '2.1.7',
> 21 silly publish      'postcss-loader': '0.8.2',
> 21 silly publish      'sass-loader': '3.2.0',
> 21 silly publish      'source-map-loader': '0.1.5',
> 21 silly publish      standard: '6.0.8',
> 21 silly publish      'style-loader': '0.13.1',
> 21 silly publish      'url-loader': '0.5.7',
> 21 silly publish      webpack: '1.12.14',
> 21 silly publish      'webpack-combine-loaders': '2.0.0',
> 21 silly publish      'webpack-dev-server': '1.14.1' },
> 21 silly publish   bin: { readini: './bin/readini.js', ini2js: './bin/ini2js.js' },
> 21 silly publish   engines: { node: '>=4.0.0' },
> 21 silly publish   readme: '# Systematic\n\nAn opinionated toolchain to package ES6 applications and libraries.\n\n__Features :__\n\n  \* Import all kind of file and output a bundle thanks to Webpack\n  \* Full es6 support\n  \* Code style and linting with [standard](https://github.com/feross/standard)\n  \* Translations management\n  \* Settings management\n\n\n# Installation\n\n`npm install systematic`\n\nYour file structure:\n\n`\n├── dist                  # result of the build\n│   └── bundle.js\n│   └── index.html\n├── src\n│    ├── module_1         # your modules\n│    ├── module_2\n│    ├── index.html       # HTML entry point, only for an application\n│    └── index.js         # JS entry point\n└── systematic.ini        # systematic config\n`\n\n\n## Entry point\n\n_ The default source folder (containing your source code and tests) is `src`. It must contain an entrypoint file named `index.js`. Example:\n\n  `javascript\n  import \'./module_1\'\n  import \'./module_2\'\n`\n\n\* If your project is an application, there must be an HTML entry point named `index.html` in the source folder, containing the primary page. Your JS entry point will be automatically added.\nExample:\n\n  `html\n  <!DOCTYPE html>\n  <html lang="en">\n    <head>\n      <meta charset="utf-8">\n      <meta http-equiv="X-UA-Compatible" content="IE=edge">\n      <meta name="viewport" content="width=device-width, initial-scale=1">\n      <title>Your website</title>\n    </head>\n    <body>\n      <!-- Some application bootstrap !-->\n    </body>\n  </html>\n`\n\n\n## Config files\n\n\* Systematic requires a `systematic.ini` configuration file in the root folder of your project. Find out all the available options in `systematic.example.ini`\n\n\* Define the webpack config: create a file `webpack.config.js` at the root of the projet. Example:\n\n  `javascript\n  // import systematic default webpack settings\n  const webpackDefaults = require(\'systematic\').webpack_get_defaults(__dirname)\n\n  // optional overrides example\n  webpackDefaults.loader.push({ test: /\\.file_extension_example$/, loaders: [\'my-loader\'] },)\n\n  module.exports = webpackDefaults\n`\n\n\n\* Define the karma config: create a file `webpack.config.js` at the root of the projet. Example:\n\n  `javascript\n  // import systematic default karma settings\n  const karmaDefaults = require(\'systematic\').karma_get_defaults(__dirname)\n\n  // optional overrides example\n  karmaDefaults.plugins.push(\'my-plugin\')\n\n  module.exports = karma => karma.set(karmaDefaults)\n`\n\n\n# Usage\n\nSystematic uses a makefile, get all commands with `make help`.\n\n## Build\n\n`make serve` to run a local server.\n`make dist` for a prod build.\n\n## Run tests\n\n`make test` runs all test that match the test file pattern (default `**/*tests.js`).\n`make livetest` run test continuously, when a file changes\n\n## Translations\n\n`make makemessages` generates translations using [easygettext](https://github.com/Polyconseil/easygettext).\nThe resulting `.po` files will be in `/locale`.\n\n`make translations` generates a JSON file from them, located at <YOUR_DIST_FOLDER>/translations.json`.\n\nYou can then load them in your JS as an object:\n``javascript\nimport translations from \'dist/translations.json\'`\n``\n\n## Settings\n\n`make settings`generates a file`<YOUR_DIST_FOLDER>/app.settings.js`if your project is an application.\n\nIt needs to be included in your index.html, since it will not be added by Webpack.\n\nThis method allows to change the settings without redeploying the app.\n\n\n# Build profiles\n\nFrom systematic.ini\'s`profile`option. For now, only the`angular`profile is supported on top of the\nnatural`vanilla`profile.\n\n## Angular\n\nValue :`angular`\n\nAdds the [ng-annotate](https://github.com/olov/ng-annotate) loader.\n\n\n# TODO\n\n## Add a sample project on Github.\n\n## Source Maps issue\n\nSource maps does not seem to work very well on`make dist`. We tried:\n\n * This issue only happen when the flag`--optimize-minimize`is given\n * Use`webpack.optimize.UglifyJsPlugin`instead of`--optimize-minimize`\n \* There is a warning in bluetils-js with ui-router source map missing, but is does not seem to be the root of the problem.\n\n\n# License\n\nMIT\n',
> 21 silly publish   readmeFilename: 'README.md',
> 21 silly publish   gitHead: '72578ca279ceb01cb7bdfcfc49bcdf25a4b39896',
> 21 silly publish   bugs: { url: 'https://github.com/polyconseil/systematic/issues' },
> 21 silly publish   homepage: 'https://github.com/polyconseil/systematic#readme',
> 21 silly publish   _id: 'systematic@0.1.2',
> 21 silly publish   _shasum: 'e872df49502941c6612eefcab2ad08a71554b777',
> 21 silly publish   _from: '.' }
> 22 verbose getPublishConfig { registry: 'https://registry.npmjs.org' }
> 23 silly mapToRegistry name systematic
> 24 silly mapToRegistry using default registry
> 25 silly mapToRegistry registry https://registry.npmjs.org
> 26 silly mapToRegistry data Result {
> 26 silly mapToRegistry   raw: 'systematic',
> 26 silly mapToRegistry   scope: null,
> 26 silly mapToRegistry   name: 'systematic',
> 26 silly mapToRegistry   rawSpec: '',
> 26 silly mapToRegistry   spec: 'latest',
> 26 silly mapToRegistry   type: 'tag' }
> 27 silly mapToRegistry uri https://registry.npmjs.org/systematic
> 28 verbose publish registryBase https://registry.npmjs.org/
> 29 silly publish uploading /home/raphael/.npm/systematic/0.1.2/package.tgz
> 30 verbose request uri https://registry.npmjs.org/systematic
> 31 verbose request sending authorization for write operation
> 32 info attempt registry request try #1 at 4:03:05 PM
> 33 verbose request using bearer token for auth
> 34 verbose request id b10fea5b567bdbab
> 35 http request PUT https://registry.npmjs.org/systematic
> 36 http 403 https://registry.npmjs.org/systematic
> 37 verbose headers { 'content-type': 'application/json',
> 37 verbose headers   'cache-control': 'max-age=300',
> 37 verbose headers   'content-length': '104',
> 37 verbose headers   'accept-ranges': 'bytes',
> 37 verbose headers   date: 'Tue, 03 May 2016 14:03:06 GMT',
> 37 verbose headers   via: '1.1 varnish',
> 37 verbose headers   connection: 'keep-alive',
> 37 verbose headers   'x-served-by': 'cache-lcy1131-LCY',
> 37 verbose headers   'x-cache': 'MISS',
> 37 verbose headers   'x-cache-hits': '0',
> 37 verbose headers   'x-timer': 'S1462284185.765515,VS0,VE578',
> 37 verbose headers   vary: 'Accept-Encoding' }
> 38 verbose request invalidating /home/raphael/.npm/registry.npmjs.org/systematic on PUT
> 39 error publish Failed PUT 403
> 40 verbose stack Error: you do not have permission to publish "systematic". Are you logged in as the correct user? : systematic
> 40 verbose stack     at makeError (/home/raphael/.nvm/versions/node/v5.11.0/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
> 40 verbose stack     at CachingRegistryClient.<anonymous> (/home/raphael/.nvm/versions/node/v5.11.0/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:252:14)
> 40 verbose stack     at Request._callback (/home/raphael/.nvm/versions/node/v5.11.0/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
> 40 verbose stack     at Request.self.callback (/home/raphael/.nvm/versions/node/v5.11.0/lib/node_modules/npm/node_modules/request/request.js:199:22)
> 40 verbose stack     at emitTwo (events.js:100:13)
> 40 verbose stack     at Request.emit (events.js:185:7)
> 40 verbose stack     at Request.<anonymous> (/home/raphael/.nvm/versions/node/v5.11.0/lib/node_modules/npm/node_modules/request/request.js:1036:10)
> 40 verbose stack     at emitOne (events.js:95:20)
> 40 verbose stack     at Request.emit (events.js:182:7)
> 40 verbose stack     at IncomingMessage.<anonymous> (/home/raphael/.nvm/versions/node/v5.11.0/lib/node_modules/npm/node_modules/request/request.js:963:12)
> 41 verbose statusCode 403
> 42 verbose pkgid systematic
> 43 verbose cwd /home/raphael/dev/systematic
> 44 error Linux 3.16.0-70-generic
> 45 error argv "/home/raphael/.nvm/versions/node/v5.11.0/bin/node" "/home/raphael/.nvm/versions/node/v5.11.0/bin/npm" "publish" "--registry" "https://registry.npmjs.org"
> 46 error node v5.11.0
> 47 error npm  v3.8.6
> 48 error code E403
> 49 error you do not have permission to publish "systematic". Are you logged in as the correct user? : systematic
> 50 error If you need help, you may report this error at:
> 50 error     https://github.com/npm/npm/issues
> 51 verbose exit [ 1, true ]

**Comment by raphael-boucher** [comment]
Looks like there was a delay, i was able to publish two days later
