### ISSUE TITLE
Unable to unpublish package

### ISSUE THREAD

**Issue by mathikp** [npm/npm#12569]
I cannot unpublish my package named [mathi-sf-npm](https://www.npmjs.com/package/mathi-sf-npm). I need to delete the contents immediately. Please help. Log attached.
LOG:
[npm-debug.zip](https://github.com/npm/npm/files/248169/npm-debug.zip)

**Comment by watilde** [comment]
Hi, have you tried the following process? If you can't after that, I think you should send a mail to `support@npmjs.com`

Use latest stable version:
```
$ npm install -g npm
```

Update your session:
```
$ npm logout
$ npm adduser
```

Retry:
```
$ cd /path/to/the/package
$ npm unpublish mathi-sf-npm
```

**Comment by mboudreau** [comment]
I am seeing this exact issue.  I'm trying to unpublish a bogus initial release of a package, but I'm not positive it is in fact doing it.  I can continually unpublish, it will keep saying that the package has been unpublished.  After I've unpublished it once, shouldn't the second time cause an error?

I've unpublished it for the need to publish the same version, but I'm seeing this issue:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'publish',
1 verbose cli   'build/pact-mock-service-darwin/' ]
2 info using npm@2.15.1
3 info using node@v4.4.3
4 verbose publish [ 'build/pact-mock-service-darwin/' ]
5 silly cache add args [ 'build/pact-mock-service-darwin/', null ]
6 verbose cache add spec build/pact-mock-service-darwin/
7 silly cache add parsed spec Result {
7 silly cache add   raw: 'build/pact-mock-service-darwin/',
7 silly cache add   scope: null,
7 silly cache add   name: null,
7 silly cache add   rawSpec: 'build/pact-mock-service-darwin/',
7 silly cache add   spec: '/home/mboudreau/Work/pact/pact-mock-service-npm/build/pact-mock-service-darwin',
7 silly cache add   type: 'directory' }
8 verbose addLocalDirectory /home/mboudreau/.npm/@pact-foundation/pact-mock-service-darwin/0.8.2/package.tgz not in flight; packing
9 verbose correctMkdir /home/mboudreau/.npm correctMkdir not in flight; initializing
10 verbose tar pack [ '/home/mboudreau/.npm/@pact-foundation/pact-mock-service-darwin/0.8.2/package.tgz',
10 verbose tar pack   '/home/mboudreau/Work/pact/pact-mock-service-npm/build/pact-mock-service-darwin' ]
11 verbose tarball /home/mboudreau/.npm/@pact-foundation/pact-mock-service-darwin/0.8.2/package.tgz
12 verbose folder /home/mboudreau/Work/pact/pact-mock-service-npm/build/pact-mock-service-darwin
13 info prepublish @pact-foundation/pact-mock-service-darwin@0.8.2
14 verbose addLocalTarball adding from inside cache /home/mboudreau/.npm/@pact-foundation/pact-mock-service-darwin/0.8.2/package.tgz
15 verbose correctMkdir /home/mboudreau/.npm correctMkdir not in flight; initializing
16 silly cache afterAdd @pact-foundation/pact-mock-service-darwin@0.8.2
17 verbose afterAdd /home/mboudreau/.npm/@pact-foundation/pact-mock-service-darwin/0.8.2/package/package.json not in flight; writing
18 verbose correctMkdir /home/mboudreau/.npm correctMkdir not in flight; initializing
19 verbose afterAdd /home/mboudreau/.npm/@pact-foundation/pact-mock-service-darwin/0.8.2/package/package.json written
20 silly publish { name: '@pact-foundation/pact-mock-service-darwin',
20 silly publish   version: '0.8.2',
20 silly publish   description: 'Pact mock service',
20 silly publish   os: [ 'darwin' ],
20 silly publish   cpu: [ 'x64', 'ia32' ],
20 silly publish   bin: { 'pact-mock-service': './bin/pact-mock-service' },
20 silly publish   main: './pact-mock-service',
20 silly publish   scripts: { test: 'echo "Error: no test specified" && exit 1' },
20 silly publish   repository:
20 silly publish    { type: 'git',
20 silly publish      url: 'git+https://github.com/pact-foundation/pact-mock-service-npm.git' },
20 silly publish   keywords: [ 'pact', 'mock', 'service' ],
20 silly publish   author:
20 silly publish    { name: 'Pact Foundation',
20 silly publish      email: 'pact-foundation@googlegroups.com@bethesque.com',
20 silly publish      url: 'https://github.com/pact-foundation' },
20 silly publish   license: 'MIT',
20 silly publish   bugs: { url: 'https://github.com/pact-foundation/pact-mock-service-npm/issues' },
20 silly publish   homepage: 'https://github.com/pact-foundation/pact-mock-service-npm',
20 silly publish   readme: '# Pact Mock Service for NPM\n\nThis is a standalone executable packaged from the Ruby [pact-mock-service-gem] gem.\n\nSee the [Pact Mock Service homepage][pact-mock-service-gem] for documentation about running the mock service.\n\n## Usage\n\n    $ npm install pact-mock-service-osx\n    $ node_modules/pact-mock-service-osx/bin/pact-mock-service --port 1234\n\n# Known issues\n\nThe packaged mock server always prints out the following message on startup. Have not yet traced the source.\n\n```\nNo entry for terminal type "xterm-256color";\nusing dumb terminal settings.\n```\n\nOn npm install, the following warnings will be displayed. They do not appear to affect the behaviour of the mock service.\n\n```\nnpm WARN excluding symbolic link lib/ruby/lib/libcrypto.dylib -> libcrypto.1.0.0.dylib\nnpm WARN excluding symbolic link lib/ruby/lib/libedit.dylib -> libedit.0.dylib\nnpm WARN excluding symbolic link lib/ruby/lib/libffi.dylib -> libffi.6.dylib\nnpm WARN excluding symbolic link lib/ruby/lib/libgmp.dylib -> libgmp.10.dylib\nnpm WARN excluding symbolic link lib/ruby/lib/liblzma.dylib -> liblzma.5.dylib\nnpm WARN excluding symbolic link lib/ruby/lib/libncurses.dylib -> libncurses.5.dylib\nnpm WARN excluding symbolic link lib/ruby/lib/libreadline.dylib -> libedit.0.dylib\nnpm WARN excluding symbolic link lib/ruby/lib/libssl.dylib -> libssl.1.0.0.dylib\nnpm WARN excluding symbolic link lib/ruby/lib/libtermcap.dylib -> libncurses.5.dylib\nnpm WARN excluding symbolic link lib/ruby/lib/libyaml.dylib -> libyaml-0.2.dylib\n```\n\n\n[pact-mock-service-gem]: https://github.com/bethesque/pact-mock_service',
20 silly publish   readmeFilename: 'README.md',
20 silly publish   _id: '@pact-foundation/pact-mock-service-darwin@0.8.2',
20 silly publish   _shasum: '774cbda544fc65103375be6a2e4ef07282b1a4f3',
20 silly publish   _from: 'build/pact-mock-service-darwin',
20 silly publish   _resolved: 'file:build/pact-mock-service-darwin' }
21 verbose getPublishConfig undefined
22 silly mapToRegistry name @pact-foundation/pact-mock-service-darwin
23 silly mapToRegistry scope (from package name) @pact-foundation
24 verbose mapToRegistry no registry URL found in name for scope @pact-foundation
25 silly mapToRegistry using default registry
26 silly mapToRegistry registry https://registry.npmjs.org/
27 silly mapToRegistry data Result {
27 silly mapToRegistry   raw: '@pact-foundation/pact-mock-service-darwin',
27 silly mapToRegistry   scope: '@pact-foundation',
27 silly mapToRegistry   name: '@pact-foundation/pact-mock-service-darwin',
27 silly mapToRegistry   rawSpec: '',
27 silly mapToRegistry   spec: 'latest',
27 silly mapToRegistry   type: 'tag' }
28 silly mapToRegistry uri https://registry.npmjs.org/@pact-foundation%2fpact-mock-service-darwin
29 verbose publish registryBase https://registry.npmjs.org/
30 silly publish uploading /home/mboudreau/.npm/@pact-foundation/pact-mock-service-darwin/0.8.2/package.tgz
31 verbose request uri https://registry.npmjs.org/@pact-foundation%2fpact-mock-service-darwin
32 verbose request sending authorization for write operation
33 info attempt registry request try #1 at 11:14:19 PM
34 verbose request using bearer token for auth
35 verbose request id 73b49f3a6037639f
36 http request PUT https://registry.npmjs.org/@pact-foundation%2fpact-mock-service-darwin
37 http 503 https://registry.npmjs.org/@pact-foundation%2fpact-mock-service-darwin
38 verbose bad json <?xml version="1.0" encoding="utf-8"?>
38 verbose bad json <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
38 verbose bad json  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
38 verbose bad json <html>
38 verbose bad json   <head>
38 verbose bad json     <title>503 backend write error</title>
38 verbose bad json   </head>
38 verbose bad json   <body>
38 verbose bad json     <h1>Error 503 backend write error</h1>
38 verbose bad json     <p>backend write error</p>
38 verbose bad json     <h3>Guru Mediation:</h3>
38 verbose bad json     <p>Details: cache-mel6520-MEL 1462367783 1128973695</p>
38 verbose bad json     <hr>
38 verbose bad json     <p>Varnish cache server</p>
38 verbose bad json   </body>
38 verbose bad json </html>
39 error registry error parsing json
40 verbose headers { server: 'Varnish',
40 verbose headers   'retry-after': '0',
40 verbose headers   'content-type': 'text/html; charset=utf-8',
40 verbose headers   'content-length': '451',
40 verbose headers   'accept-ranges': 'bytes',
40 verbose headers   date: 'Wed, 04 May 2016 13:16:23 GMT',
40 verbose headers   via: '1.1 varnish',
40 verbose headers   connection: 'close',
40 verbose headers   'x-served-by': 'cache-mel6520-MEL',
40 verbose headers   'x-cache': 'MISS',
40 verbose headers   'x-cache-hits': '0',
40 verbose headers   'x-timer': 'S1462367662.392696,VS0,VE121107' }
41 info retry will retry, error on last attempt: SyntaxError: Unexpected token <
41 info retry
41 info retry <?xml version="1.0" encoding="utf-8"?>
41 info retry <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
41 info retry  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
41 info retry <html>
41 info retry   <head>
41 info retry     <title>503 backend write error</title>
41 info retry   </head>
41 info retry   <body>
41 info retry     <h1>Error 503 backend write error</h1>
41 info retry     <p>backend write error</p>
41 info retry     <h3>Guru Mediation:</h3>
41 info retry     <p>Details: cache-mel6520-MEL 1462367783 1128973695</p>
41 info retry     <hr>
41 info retry     <p>Varnish cache server</p>
41 info retry   </body>
41 info retry </html>
42 info attempt registry request try #2 at 11:16:31 PM
43 verbose request using bearer token for auth
44 http request PUT https://registry.npmjs.org/@pact-foundation%2fpact-mock-service-darwin
45 http 503 https://registry.npmjs.org/@pact-foundation%2fpact-mock-service-darwin
46 verbose bad json <?xml version="1.0" encoding="utf-8"?>
46 verbose bad json <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
46 verbose bad json  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
46 verbose bad json <html>
46 verbose bad json   <head>
46 verbose bad json     <title>503 backend write error</title>
46 verbose bad json   </head>
46 verbose bad json   <body>
46 verbose bad json     <h1>Error 503 backend write error</h1>
46 verbose bad json     <p>backend write error</p>
46 verbose bad json     <h3>Guru Mediation:</h3>
46 verbose bad json     <p>Details: cache-mel6520-MEL 1462367915 1129421110</p>
46 verbose bad json     <hr>
46 verbose bad json     <p>Varnish cache server</p>
46 verbose bad json   </body>
46 verbose bad json </html>
47 error registry error parsing json
48 verbose headers { server: 'Varnish',
48 verbose headers   'retry-after': '0',
48 verbose headers   'content-type': 'text/html; charset=utf-8',
48 verbose headers   'content-length': '451',
48 verbose headers   'accept-ranges': 'bytes',
48 verbose headers   date: 'Wed, 04 May 2016 13:18:35 GMT',
48 verbose headers   via: '1.1 varnish',
48 verbose headers   connection: 'close',
48 verbose headers   'x-served-by': 'cache-mel6520-MEL',
48 verbose headers   'x-cache': 'MISS',
48 verbose headers   'x-cache-hits': '0',
48 verbose headers   'x-timer': 'S1462367794.372153,VS0,VE121110' }
49 info retry will retry, error on last attempt: SyntaxError: Unexpected token <
49 info retry
49 info retry <?xml version="1.0" encoding="utf-8"?>
49 info retry <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
49 info retry  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
49 info retry <html>
49 info retry   <head>
49 info retry     <title>503 backend write error</title>
49 info retry   </head>
49 info retry   <body>
49 info retry     <h1>Error 503 backend write error</h1>
49 info retry     <p>backend write error</p>
49 info retry     <h3>Guru Mediation:</h3>
49 info retry     <p>Details: cache-mel6520-MEL 1462367915 1129421110</p>
49 info retry     <hr>
49 info retry     <p>Varnish cache server</p>
49 info retry   </body>
49 info retry </html>
50 info attempt registry request try #3 at 11:19:33 PM
51 verbose request using bearer token for auth
52 http request PUT https://registry.npmjs.org/@pact-foundation%2fpact-mock-service-darwin
53 http 503 https://registry.npmjs.org/@pact-foundation%2fpact-mock-service-darwin
54 verbose bad json <?xml version="1.0" encoding="utf-8"?>
54 verbose bad json <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
54 verbose bad json  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
54 verbose bad json <html>
54 verbose bad json   <head>
54 verbose bad json     <title>503 backend write error</title>
54 verbose bad json   </head>
54 verbose bad json   <body>
54 verbose bad json     <h1>Error 503 backend write error</h1>
54 verbose bad json     <p>backend write error</p>
54 verbose bad json     <h3>Guru Mediation:</h3>
54 verbose bad json     <p>Details: cache-mel6521-MEL 1462368097 1716281428</p>
54 verbose bad json     <hr>
54 verbose bad json     <p>Varnish cache server</p>
54 verbose bad json   </body>
54 verbose bad json </html>
55 error registry error parsing json
56 verbose headers { server: 'Varnish',
56 verbose headers   'retry-after': '0',
56 verbose headers   'content-type': 'text/html; charset=utf-8',
56 verbose headers   'content-length': '451',
56 verbose headers   'accept-ranges': 'bytes',
56 verbose headers   date: 'Wed, 04 May 2016 13:21:37 GMT',
56 verbose headers   via: '1.1 varnish',
56 verbose headers   connection: 'close',
56 verbose headers   'x-served-by': 'cache-mel6521-MEL',
56 verbose headers   'x-cache': 'MISS',
56 verbose headers   'x-cache-hits': '0',
56 verbose headers   'x-timer': 'S1462367976.226791,VS0,VE121250' }
57 verbose request invalidating /home/mboudreau/.npm/registry.npmjs.org/_40pact-foundation_252fpact-mock-service-darwin on PUT
58 error publish Failed PUT 503
59 verbose stack SyntaxError: Unexpected token <
59 verbose stack
59 verbose stack <?xml version="1.0" encoding="utf-8"?>
59 verbose stack <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
59 verbose stack  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
59 verbose stack <html>
59 verbose stack   <head>
59 verbose stack     <title>503 backend write error</title>
59 verbose stack   </head>
59 verbose stack   <body>
59 verbose stack     <h1>Error 503 backend write error</h1>
59 verbose stack     <p>backend write error</p>
59 verbose stack     <h3>Guru Mediation:</h3>
59 verbose stack     <p>Details: cache-mel6521-MEL 1462368097 1716281428</p>
59 verbose stack     <hr>
59 verbose stack     <p>Varnish cache server</p>
59 verbose stack   </body>
59 verbose stack </html>
59 verbose stack
59 verbose stack     at Object.parse (native)
59 verbose stack     at CachingRegistryClient.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:199:23)
59 verbose stack     at Request._callback (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
59 verbose stack     at Request.self.callback (/usr/lib/node_modules/npm/node_modules/request/request.js:199:22)
59 verbose stack     at emitTwo (events.js:87:13)
59 verbose stack     at Request.emit (events.js:172:7)
59 verbose stack     at Request.<anonymous> (/usr/lib/node_modules/npm/node_modules/request/request.js:1036:10)
59 verbose stack     at emitOne (events.js:82:20)
59 verbose stack     at Request.emit (events.js:169:7)
59 verbose stack     at IncomingMessage.<anonymous> (/usr/lib/node_modules/npm/node_modules/request/request.js:963:12)
60 verbose cwd /home/mboudreau/Work/pact/pact-mock-service-npm
61 error Linux 3.16.0-67-generic
62 error argv "/usr/bin/nodejs" "/usr/bin/npm" "publish" "build/pact-mock-service-darwin/"
63 error node v4.4.3
64 error npm  v2.15.1
65 error Unexpected token <
65 error
65 error <?xml version="1.0" encoding="utf-8"?>
65 error <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
65 error  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
65 error <html>
65 error   <head>
65 error     <title>503 backend write error</title>
65 error   </head>
65 error   <body>
65 error     <h1>Error 503 backend write error</h1>
65 error     <p>backend write error</p>
65 error     <h3>Guru Mediation:</h3>
65 error     <p>Details: cache-mel6521-MEL 1462368097 1716281428</p>
65 error     <hr>
65 error     <p>Varnish cache server</p>
65 error   </body>
65 error </html>
66 error If you need help, you may report this error at:
66 error     <https://github.com/npm/npm/issues>
67 verbose exit [ 1, true ]
```
