### ISSUE TITLE
Maximum call stack size exceeded for --no-bin-links

### ISSUE THREAD

**Issue by sheerun** [npm/npm#12624]
Steps to reproduce:

```
git clone https://github.com/sindresorhus/ava
cd ava
npm install --production --ignore-scripts --no-bin-links
```

Result:

```
34533 verbose stack RangeError: Maximum call stack size exceeded
34533 verbose stack     at isTTY (/Users/sheerun/.nvm/versions/node/v5.9.0/lib/node_modules/npm/node_modules/npmlog/node_modules/gauge/progress-bar.js:11:17)
34533 verbose stack     at Object.ProgressBar.show (/Users/sheerun/.nvm/versions/node/v5.9.0/lib/node_modules/npm/node_modules/npmlog/node_modules/gauge/progress-bar.js:132:8)
34533 verbose stack     at Object.ProgressBar.pulse (/Users/sheerun/.nvm/versions/node/v5.9.0/lib/node_modules/npm/node_modules/npmlog/node_modules/gauge/progress-bar.js:124:8)
34533 verbose stack     at EventEmitter.log.emitLog (/Users/sheerun/.nvm/versions/node/v5.9.0/lib/node_modules/npm/node_modules/npmlog/log.js:178:40)
34533 verbose stack     at EventEmitter.<anonymous> (/Users/sheerun/.nvm/versions/node/v5.9.0/lib/node_modules/npm/node_modules/npmlog/log.js:170:8)
34533 verbose stack     at EventEmitter.<anonymous> (/Users/sheerun/.nvm/versions/node/v5.9.0/lib/node_modules/npm/node_modules/npmlog/log.js:231:21)
34533 verbose stack     at tracker.(anonymous function) [as silly] (/Users/sheerun/.nvm/versions/node/v5.9.0/lib/node_modules/npm/node_modules/npmlog/log.js:79:19)
34533 verbose stack     at module.exports (/Users/sheerun/.nvm/versions/node/v5.9.0/lib/node_modules/npm/lib/install/action/build.js:8:7)
34533 verbose stack     at actions.(anonymous function) (/Users/sheerun/.nvm/versions/node/v5.9.0/lib/node_modules/npm/lib/install/actions.js:48:12)
34533 verbose stack     at Array.<anonymous> (/Users/sheerun/.nvm/versions/node/v5.9.0/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
```

**Comment by othiym23** [comment]
This happens for @iarna with `npm@next` under Node LTS, but doesn't for me (or her) under Node 6. That indicates (and the stacktrace supports) that this is an issue with Node.js's TTY-handling code, and not with npm. I'd go ahead and take this to `nodejs/node`, because it does affect Node.js LTS, which has pretty substantial traction. Thanks for your time!

**Comment by thefourtheye** [comment]
Just tried this in my OS X 10.11.4 (15E65)

```
➜  ava git:(master) npm -v
2.15.1
➜  ava git:(master) node -v
v4.4.4
```

also in 6.1.0. The ```npm install --production --ignore-scripts --no-bin-links``` completed successfully. So, this doesn't affect the LTS I guess.

**Comment by sheerun** [comment]
it's latest npm 3
