### ISSUE TITLE
Error: Cannot find module 'npmlog'

### ISSUE THREAD

**Issue by zhangtuoparis13** [npm/npm#12632]
```
module.js:440
    throw err;
    ^

Error: Cannot find module 'npmlog'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:20:13
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:76:3)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
```

I have the node v6.1.0 and use the `curl -L https://www.npmjs.com/install.sh | sh` to install/config the npm, but it doesn't work.

**Comment by ICCanche** [comment]
try with:

 $ curl https://npmjs.org/install.sh | sh

**Comment by yousan** [comment]
Thanks @ICCanche 

The URL was 301 moved now.
```
$ curl https://npmjs.org/install.sh | sh
sh: 1: cannot open html: No such file
sh: 2: Syntax error: redirection unexpected
```

Follow redirects works correct.

```
$ curl --location https://npmjs.org/install.sh | sh
```
