### ISSUE TITLE
nodejs cannot install spm-build in my OSX

### ISSUE THREAD

**Issue by plutogeek** [npm/npm#12668]
when i execute the command
 `sudo npm install spm-build@1.3.2 -g`

```
/usr/local/bin/spm-build -> /usr/local/lib/node_modules/spm-build/cli.js

> kexec@1.0.0 install /usr/local/lib/node_modules/spm-build/node_modules/kexec
> node-gyp configure build

  CXX(target) Release/obj.target/kexec/src/kexec.o
../src/kexec.cc:22:30: error: use of undeclared identifier 'F_GETFD'
    int flags = fcntl (desc, F_GETFD, 0);
                             ^
../src/kexec.cc:26:15: error: use of undeclared identifier 'FD_CLOEXEC'
    flags &= ~FD_CLOEXEC; //clear FD_CLOEXEC bit
              ^
../src/kexec.cc:27:25: error: use of undeclared identifier 'F_SETFD'
    return fcntl (desc, F_SETFD, flags);
                        ^
../src/kexec.cc:43:34: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
static Handle<Value> kexec(const Arguments& args) {
                                 ^~~~~~~~~
                                 v8::internal::Arguments
/Users/pluto/.node-gyp/5.3.0/include/node/v8.h:139:7: note: 
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/kexec.cc:44:17: error: calling a protected constructor of class
      'v8::HandleScope'
    HandleScope scope;
                ^
/Users/pluto/.node-gyp/5.3.0/include/node/v8.h:889:13: note: declared protected
      here
  V8_INLINE HandleScope() {}
            ^
../src/kexec.cc:67:19: error: member access into incomplete type 'const
      v8::internal::Arguments'
    if ( 1 == args.Length() && args[0]->IsString() )
                  ^
/Users/pluto/.node-gyp/5.3.0/include/node/v8.h:139:7: note: forward declaration
      of 'v8::internal::Arguments'
class Arguments;
      ^
../src/kexec.cc:69:37: error: type 'const v8::internal::Arguments' does not
      provide a subscript operator
        String::Utf8Value v8str(args[0]);
                                ~~~~^~
../src/kexec.cc:78:44: error: too few arguments to function call, expected 2,
      have 1
        Local<Number> num = Number::New(err);
                            ~~~~~~~~~~~    ^
/Users/pluto/.node-gyp/5.3.0/include/node/v8.h:2483:3: note: 'New' declared here
  static Local<Number> New(Isolate* isolate, double value);
  ^
../src/kexec.cc:79:22: error: no member named 'Close' in 'v8::HandleScope'
        return scope.Close(num/*Undefined()*/);
               ~~~~~ ^
../src/kexec.cc:83:19: error: member access into incomplete type 'const
      v8::internal::Arguments'
    if ( 2 == args.Length() && args[0]->IsString() && args[1]->IsArray() )
                  ^
/Users/pluto/.node-gyp/5.3.0/include/node/v8.h:139:7: note: forward declaration
      of 'v8::internal::Arguments'
class Arguments;
      ^
../src/kexec.cc:85:37: error: type 'const v8::internal::Arguments' does not
      provide a subscript operator
        String::Utf8Value v8str(args[0]);
                                ~~~~^~
../src/kexec.cc:89:59: error: type 'const v8::internal::Arguments' does not
      provide a subscript operator
        Local<Array> argv_handle = Local<Array>::Cast(args[1]);
                                                      ~~~~^~
../src/kexec.cc:101:66: error: too few arguments to function call, expected 2,
      have 1
            String::Utf8Value arg(argv_handle->Get(Integer::New(i))->ToS...
                                                   ~~~~~~~~~~~~  ^
/Users/pluto/.node-gyp/5.3.0/include/node/v8.h:2496:3: note: 'New' declared here
  static Local<Integer> New(Isolate* isolate, int32_t value);
  ^
../src/kexec.cc:118:44: error: too few arguments to function call, expected 2,
      have 1
        Local<Number> num = Number::New(err);
                            ~~~~~~~~~~~    ^
/Users/pluto/.node-gyp/5.3.0/include/node/v8.h:2483:3: note: 'New' declared here
  static Local<Number> New(Isolate* isolate, double value);
  ^
../src/kexec.cc:119:22: error: no member named 'Close' in 'v8::HandleScope'
        return scope.Close(num/*Undefined()*/);
               ~~~~~ ^
../src/kexec.cc:127:49: error: no member named 'New' in 'v8::String'
    ThrowException(Exception::TypeError(String::New("kexec: invalid argu...
                                        ~~~~~~~~^
../src/kexec.cc:128:18: error: no member named 'Close' in 'v8::HandleScope'
    return scope.Close(Undefined());
           ~~~~~ ^
../src/kexec.cc:128:24: error: no matching function for call to 'Undefined'
    return scope.Close(Undefined());
                       ^~~~~~~~~
/Users/pluto/.node-gyp/5.3.0/include/node/v8.h:315:27: note: candidate function
      not viable: requires single argument 'isolate', but no arguments were
      provided
  friend Local<Primitive> Undefined(Isolate* isolate);
                          ^
../src/kexec.cc:134:9: error: no matching function for call to 'NODE_SET_METHOD'
        NODE_SET_METHOD(target, "kexec", kexec);
        ^~~~~~~~~~~~~~~
/Users/pluto/.node-gyp/5.3.0/include/node/node.h:248:25: note: expanded from
      macro 'NODE_SET_METHOD'
#define NODE_SET_METHOD node::NODE_SET_METHOD
                        ^~~~~~~~~~~~~~~~~~~~~
/Users/pluto/.node-gyp/5.3.0/include/node/node.h:236:13: note: candidate
      function [with TypeName = v8::Local<v8::Object>] not viable: no known
      conversion from 'Handle<v8::Value> (const v8::internal::Arguments &)' (aka
      'v8::Local<v8::Value> (const v8::internal::Arguments &)') to
      'v8::FunctionCallback' (aka 'void (*)(const
      FunctionCallbackInfo<v8::Value> &)') for 3rd argument
inline void NODE_SET_METHOD(const TypeName& recv,
            ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/kexec/src/kexec.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.4.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /usr/local/lib/node_modules/spm-build/node_modules/kexec
gyp ERR! node -v v5.3.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN install:kexec@1.0.0 kexec@1.0.0 install: `node-gyp configure build`
npm WARN install:kexec@1.0.0 Exit status 1
```

**Comment by othiym23** [comment]
This is due to a change in the V8 API between the version of the package you're trying to install and Node.js 5.3.0. This isn't an issue with the npm CLI, which is merely reporting the build failure to you, so I suggest taking this issue up with the [`spm-build` maintainers](https://github.com/spmjs/spm-build/issues). Thanks for your time!
