### ISSUE TITLE
Cannot publish @angular/common@2.0.0-rc.1 to the npm repository.

### ISSUE THREAD

**Issue by jags213** [npm/npm#12670]
Im getting the below error while publishing the @angular/common@2.0.0-rc.1.. im thinking that npm is not able to take the module name as it is starting with "@" special character and has another character "/" in the name. So please let me know how to publish this module. the script is trying to run the below command and the detailed error output is given below.

npm install @angular/common@2.0.0-rc.1 --registry http://localhost:8080/nexus/content/repositories/npmjs-proxy

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/node-v0.10.33-linux-x64/bin/node',
1 verbose cli   '/usr/local/node-v0.10.33-linux-x64/bin/npm',
1 verbose cli   'install',
1 verbose cli   '@angular/common@2.0.0-rc.1',
1 verbose cli   '--registry',
1 verbose cli   'http://localhost:8080/nexus/content/repositories/npmjs-proxy' ]
2 info using npm@1.4.28
3 info using node@v0.10.33
4 warn package.json dom-helpers@2.4.0 No README data
5 warn package.json react-prop-types@0.3.1 No README data
6 warn package.json a11y-focus-scope@1.1.3 No repository field.
7 warn package.json a11y-focus-store@1.0.0 No repository field.
8 warn package.json crypto@0.0.3 crypto is also the name of a node core module.
9 warn package.json js-stylesheet@0.0.1 No repository field.
10 verbose cache add [ '@angular/common@2.0.0-rc.1', null ]
11 verbose cache add name=undefined spec="@angular/common@2.0.0-rc.1" args=["@angular/common@2.0.0-rc.1",null]
12 verbose parsed url { protocol: null,
12 verbose parsed url   slashes: null,
12 verbose parsed url   auth: null,
12 verbose parsed url   host: null,
12 verbose parsed url   port: null,
12 verbose parsed url   hostname: null,
12 verbose parsed url   hash: null,
12 verbose parsed url   search: null,
12 verbose parsed url   query: null,
12 verbose parsed url   pathname: '@angular/common@2.0.0-rc.1',
12 verbose parsed url   path: '@angular/common@2.0.0-rc.1',
12 verbose parsed url   href: '@angular/common@2.0.0-rc.1' }
13 verbose cache add name="" spec="angular/common@2.0.0-rc.1" args=["","angular/common@2.0.0-rc.1"]
14 verbose parsed url { protocol: null,
14 verbose parsed url   slashes: null,
14 verbose parsed url   auth: null,
14 verbose parsed url   host: null,
14 verbose parsed url   port: null,
14 verbose parsed url   hostname: null,
14 verbose parsed url   hash: null,
14 verbose parsed url   search: null,
14 verbose parsed url   query: null,
14 verbose parsed url   pathname: 'angular/common@2.0.0-rc.1',
14 verbose parsed url   path: 'angular/common@2.0.0-rc.1',
14 verbose parsed url   href: 'angular/common@2.0.0-rc.1' }
15 verbose cache add name="angular/common" spec="2.0.0-rc.1" args=["angular/common","2.0.0-rc.1"]
16 verbose parsed url { protocol: null,
16 verbose parsed url   slashes: null,
16 verbose parsed url   auth: null,
16 verbose parsed url   host: null,
16 verbose parsed url   port: null,
16 verbose parsed url   hostname: null,
16 verbose parsed url   hash: null,
16 verbose parsed url   search: null,
16 verbose parsed url   query: null,
16 verbose parsed url   pathname: '2.0.0-rc.1',
16 verbose parsed url   path: '2.0.0-rc.1',
16 verbose parsed url   href: '2.0.0-rc.1' }
17 verbose addNamed [ 'angular/common', '2.0.0-rc.1' ]
18 verbose addNamed [ '2.0.0-rc.1', '2.0.0-rc.1' ]
19 silly lockFile e3e65f6f-angular-common-2-0-0-rc-1 angular/common@2.0.0-rc.1
20 verbose lock angular/common@2.0.0-rc.1 /opt/maestrodata/maestro_user_home/.npm/e3e65f6f-angular-common-2-0-0-rc-1.lock
21 verbose request where is /nexus/content/repositories/npmjs-proxy/angular/common
22 verbose request registry http://localhost:8080/
23 verbose request id 3ac33e0f04a4116c
24 verbose url raw /nexus/content/repositories/npmjs-proxy/angular/common
25 verbose url resolving [ 'http://localhost:8080/',
25 verbose url resolving   './nexus/content/repositories/npmjs-proxy/angular/common' ]
26 verbose url resolved http://localhost:8080/nexus/content/repositories/npmjs-proxy/angular/common
27 verbose request where is http://localhost:8080/nexus/content/repositories/npmjs-proxy/angular/common
28 info trying registry request attempt 1 at 12:40:14
29 http GET http://localhost:8080/nexus/content/repositories/npmjs-proxy/angular/common
30 http 404 http://localhost:8080/nexus/content/repositories/npmjs-proxy/angular/common
31 verbose bad json <html>
31 verbose bad json   <head>
31 verbose bad json     <title>404 - Request is serviced by NPM metadata service, remote access not needed from DefaultNpmProxyRepository(id=npmjs-proxy)</title>
31 verbose bad json     <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
31 verbose bad json
31 verbose bad json     <link rel="icon" type="image/png" href="http://localhost:8080/nexus/favicon.png">
31 verbose bad json     <!--[if IE]>
31 verbose bad json     <link rel="SHORTCUT ICON" href="http://localhost:8080/nexus/favicon.ico"/>
31 verbose bad json     <![endif]-->
31 verbose bad json
31 verbose bad json     <link rel="stylesheet" href="http://localhost:8080/nexus/static/css/Sonatype-content.css?2.12.0-01" type="text/css" media="screen" title="no title" charset="utf-8">
31 verbose bad json   </head>
31 verbose bad json   <body>
31 verbose bad json     <h1>404 - Request is serviced by NPM metadata service, remote access not needed from DefaultNpmProxyRepository(id=npmjs-proxy)</h1>
31 verbose bad json     <p>Request is serviced by NPM metadata service, remote access not needed from DefaultNpmProxyRepository(id=npmjs-proxy)</p>
31 verbose bad json   </body>
31 verbose bad json </html>
32 error registry error parsing json
33 verbose headers { date: 'Wed, 11 May 2016 19:40:14 GMT',
33 verbose headers   server: 'Nexus/2.12.0-01',
33 verbose headers   'x-frame-options': 'SAMEORIGIN',
33 verbose headers   'x-content-type-options': 'nosniff',
33 verbose headers   'accept-ranges': 'bytes',
33 verbose headers   'content-type': 'text/html',
33 verbose headers   'transfer-encoding': 'chunked' }
34 silly registry.get cb [ 404,
34 silly registry.get   { date: 'Wed, 11 May 2016 19:40:14 GMT',
34 silly registry.get     server: 'Nexus/2.12.0-01',
34 silly registry.get     'x-frame-options': 'SAMEORIGIN',
34 silly registry.get     'x-content-type-options': 'nosniff',
34 silly registry.get     'accept-ranges': 'bytes',
34 silly registry.get     'content-type': 'text/html',
34 silly registry.get     'transfer-encoding': 'chunked' } ]
35 silly lockFile e3e65f6f-angular-common-2-0-0-rc-1 angular/common@2.0.0-rc.1
36 silly lockFile e3e65f6f-angular-common-2-0-0-rc-1 angular/common@2.0.0-rc.1
37 error SyntaxError: Unexpected token <
37 error <html>
37 error   <head>
37 error     <title>404 - Request is serviced by NPM metadata service, remote access not needed from DefaultNpmProxyRepository(id=npmjs-proxy)</title>
37 error     <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
37 error
37 error     <link rel="icon" type="image/png" href="http://localhost:8080/nexus/favicon.png">
37 error     <!--[if IE]>
37 error     <link rel="SHORTCUT ICON" href="http://localhost:8080/nexus/favicon.ico"/>
37 error     <![endif]-->
37 error
37 error     <link rel="stylesheet" href="http://localhost:8080/nexus/static/css/Sonatype-content.css?2.12.0-01" type="text/css" media="screen" title="no title" charset="utf-8">
37 error   </head>
37 error   <body>
37 error     <h1>404 - Request is serviced by NPM metadata service, remote access not needed from DefaultNpmProxyRepository(id=npmjs-proxy)</h1>
37 error     <p>Request is serviced by NPM metadata service, remote access not needed from DefaultNpmProxyRepository(id=npmjs-proxy)</p>
37 error   </body>
37 error </html>
37 error
37 error     at Object.parse (native)
37 error     at RegClient.<anonymous> (/usr/local/node-v0.10.33-linux-x64/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:274:23)
37 error     at Request._callback (/usr/local/node-v0.10.33-linux-x64/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:246:65)
37 error     at Request.self.callback (/usr/local/node-v0.10.33-linux-x64/lib/node_modules/npm/node_modules/request/request.js:236:22)
37 error     at Request.emit (events.js:98:17)
37 error     at Request.<anonymous> (/usr/local/node-v0.10.33-linux-x64/lib/node_modules/npm/node_modules/request/request.js:1142:14)
37 error     at Request.emit (events.js:117:20)
37 error     at IncomingMessage.<anonymous> (/usr/local/node-v0.10.33-linux-x64/lib/node_modules/npm/node_modules/request/request.js:1096:12)
37 error     at IncomingMessage.emit (events.js:117:20)
37 error     at _stream_readable.js:943:16
38 error If you need help, you may report this *entire* log,
38 error including the npm and node versions, at:
38 error     <http://github.com/npm/npm/issues>
39 error System Linux 2.6.32-431.el6.x86_64
40 error command "/usr/local/node-v0.10.33-linux-x64/bin/node" "/usr/local/node-v0.10.33-linux-x64/bin/npm" "install" "@angular/common@2.0.0-rc.1" "--registry" "http://localhost:8080/nexus/content/repositories/npmjs-proxy"
41 error cwd /opt/maestrodata/maestro_user_home/npmmanager/third-party-publisher/output
42 error node -v v0.10.33
43 error npm -v 1.4.28
44 error type unexpected_token
45 verbose exit [ 1, true ]
```

**Comment by othiym23** [comment]
Heya! `npm@2` or newer are required to work with scoped packages like `@angular/common`. [Update](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) to a newer version of npm, and you should be able to do this without issue, assuming that you're a member of the Angular organization, or have otherwise been granted privileges to that package.

Closing as resolved.
