### ISSUE TITLE
can't run npm install

### ISSUE THREAD

**Issue by cypriencastel** [npm/npm#12692]
I can't use npm install to add dependencies in my package.json
Can you help me ?

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'gulp',
1 verbose cli   '--save-dev' ]
2 info using npm@2.15.1
3 info using node@v4.4.4
4 verbose stack Error: Cannot find module 'has-unicode'
4 verbose stack     at Function.Module._resolveFilename (module.js:325:15)
4 verbose stack     at Function.Module._load (module.js:276:25)
4 verbose stack     at Module.require (module.js:353:17)
4 verbose stack     at require (internal/module.js:12:17)
4 verbose stack     at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-install-checks/node_modules/npmlog/node_modules/gauge/progress-bar.js:2:18)
4 verbose stack     at Module._compile (module.js:409:26)
4 verbose stack     at Object.Module._extensions..js (module.js:416:10)
4 verbose stack     at Module.load (module.js:343:32)
4 verbose stack     at Function.Module._load (module.js:300:12)
4 verbose stack     at Module.require (module.js:353:17)
4 verbose stack     at require (internal/module.js:12:17)
5 verbose cwd /Users/cypriencastel/Documents/ecole/H2/expertise
6 error Darwin 15.4.0
7 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "gulp" "--save-dev"
8 error node v4.4.4
9 error npm  v2.15.1
10 error code MODULE_NOT_FOUND
11 error Cannot find module 'has-unicode'
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]
```

**Comment by watilde** [comment]
I guess this is related patch: https://github.com/npm/npm/pull/11129, but I couldn't reproduce with clean installed v4.4.4 Node on my laptop.

**Comment by KenanY** [comment]
@cypriencastel Is this still an issue for you with `npm@^3.6.0`?

**Comment by cypriencastel** [comment]
@KenanY No this was just a syntax error in my package.json thank you !
Maybe you can help me in an other problem ? I try to do a sql request with mysql and I would like to use the results in an other function. The problem is that I can't return the result in a variable out of the callback function. Can you advice me ? Thanks a lot !

**Comment by KenanY** [comment]
@cypriencastel Have the callback be that other function.
