### ISSUE TITLE
Outdated -g throws on most recent npm

### ISSUE THREAD

**Issue by doug-wade** [npm/npm#12715]
```
dougwade code/stratocacher ‹master*› » npm outdated -g
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "outdated" "-g"
npm ERR! node v6.1.0
npm ERR! npm  v3.9.0
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at module.exports (/usr/local/lib/node_modules/npm/lib/install/mutate-into-logical-tree.js:12:3)
npm ERR! typeerror     at /usr/local/lib/node_modules/npm/lib/outdated.js:78:5
npm ERR! typeerror     at /usr/local/lib/node_modules/npm/lib/outdated.js:62:20
npm ERR! typeerror     at /usr/local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:186:9
npm ERR! typeerror     at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:17:25)
npm ERR! typeerror     at /usr/local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:152:20
npm ERR! typeerror     at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:17:25)
npm ERR! typeerror     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:121:22)
npm ERR! typeerror     at /usr/local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:81:20
npm ERR! typeerror     at FSReqWrap.oncomplete (fs.js:117:15)
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/doug.wade/code/stratocacher/npm-debug.log
dougwade code/stratocacher ‹master*› » npm -v                                                                                                                                 1 ↵
3.9.0
```

**Comment by tommck** [comment]
so.. "next-next"? Does this mean you're not fixing this soon?  It seems like a big deal to me

**Comment by mbellerose** [comment]
I ran into this issue on Windows 7.  I delete the ~\AppData\Roaming\npm folder and the problem went away.  I did have to reinstall all my global packages.

**Comment by tommck** [comment]
That worked for me too (same OS)

**Comment by doug-wade** [comment]
I see that @othiym23 added the "needs repro" tag; I don't know how to provide a repro for a global issue, so here's what I can give you that might help

contents of my global node_modules
```
dougwade main/rf-build-metrics-client ‹dbw-rf-package-pin-dependency*› » ls -l /usr/local/lib/node_modules                                                                                                                                1 ↵
total 40
drwxr-xr-x  9 doug.wade 306 Mar 16 23:51 all
drwxr-xr-x 13 doug.wade 442 Apr 19 17:45 amd-pack
drwxr-xr-x  9 doug.wade 306 Apr 19 17:34 amdify
drwxr-xr-x 13 doug.wade 442 May 15 17:53 ava
drwxr-xr-x 10 doug.wade 340 May 18 15:14 ava-codemods
lrwxr-xr-x  1 doug.wade  46 May  7 10:59 babel-cli -> /Users/doug.wade/code/babel/packages/babel-cli
drwxr-xr-x  8 doug.wade 272 Mar 30 16:13 babel-eslint
lrwxr-xr-x  1 doug.wade  74 May  7 11:04 babel-plugin-transform-do-expressions -> /Users/doug.wade/code/babel/packages/babel-plugin-transform-do-expressions
drwxr-xr-x  7 doug.wade 238 Mar 25 14:57 babel-preset-es2015
lrwxr-xr-x  1 doug.wade  63 Mar 21 18:10 babel-preset-react-server -> /Users/doug.wade/code/main/redfin.npm/babel-preset-react-server
lrwxr-xr-x  1 doug.wade  29 May  7 09:01 babylon -> /Users/doug.wade/code/babylon
drwxr-xr-x  8 doug.wade 272 Apr 16 12:41 bower
drwxr-xr-x 13 doug.wade 442 Mar 10 18:48 browserify
drwxr-xr-x 15 doug.wade 510 May 15 17:53 bunyan
drwxr-xr-x  3 doug.wade 102 Mar  5 19:59 child
drwxr-xr-x 15 doug.wade 510 May 15 17:06 codecov
drwxr-xr-x 13 doug.wade 442 Apr 18 22:25 coffee-script
drwxr-xr-x  8 doug.wade 272 Mar  1 10:37 covgen
drwxr-xr-x 10 doug.wade 340 Oct 22  2015 csso
drwxr-xr-x  7 doug.wade 238 May 15 16:57 david
drwxr-xr-x 16 doug.wade 544 Mar 20 22:21 depcheck
drwxr-xr-x  6 doug.wade 204 Mar 23 10:53 did-azer-break-my-stuff
drwxr-xr-x 11 doug.wade 374 Apr 23 17:03 dnd-roller
drwxr-xr-x 11 doug.wade 374 Mar 29 10:50 docco
drwxr-xr-x 11 doug.wade 374 May 14 09:13 eslint
drwxr-xr-x  9 doug.wade 306 Mar 16 16:41 eslint-config-xo-space
drwxr-xr-x 13 doug.wade 442 Mar  7 17:25 eslint-plugin-import
drwxr-xr-x  8 doug.wade 272 Mar 31 11:39 eslint-plugin-react
lrwxr-xr-x  1 doug.wade  33 May  2 23:42 example -> /Users/doug.wade/code/example-sub
drwxr-xr-x  6 doug.wade 204 Mar 16 23:17 generator-babel
drwxr-xr-x  6 doug.wade 204 Mar 16 23:22 generator-babel-plugin
drwxr-xr-x  6 doug.wade 204 May 15 17:53 generator-generator
drwxr-xr-x 15 doug.wade 510 Mar  4 13:19 generator-gulp-plugin
drwxr-xr-x  7 doug.wade 238 Mar  9 13:03 generator-gulp-plugin-boilerplate
drwxr-xr-x  7 doug.wade 238 Dec 20 19:42 generator-koa-angular
lrwxr-xr-x  1 doug.wade  41 Apr 17 12:56 generator-koa-react -> /Users/doug.wade/code/generator-koa-react
drwxr-xr-x  8 doug.wade 272 Mar  4 13:19 generator-node
lrwxr-xr-x  1 doug.wade  66 May 31 13:57 generator-react-server -> /Users/doug.wade/code/react-server/packages/generator-react-server
lrwxr-xr-x  1 doug.wade  35 May  3 09:52 generator-sub -> /Users/doug.wade/code/generator-sub
drwxr-xr-x 12 doug.wade 408 Mar  4 13:19 gitbook-cli
drwxr-xr-x 11 doug.wade 374 Jun 29  2015 grunt
drwxr-xr-x 12 doug.wade 408 May 16 14:39 gulp
drwxr-xr-x 11 doug.wade 374 May 24 17:47 gulp-cli
drwxr-xr-x 15 doug.wade 510 May  3 22:24 ied
drwxr-xr-x  6 doug.wade 204 Mar 16 16:37 inquirer
drwxr-xr-x  9 doug.wade 306 May 15 17:06 istanbul
drwxr-xr-x 10 doug.wade 340 Mar 17 10:53 jasmine
drwxr-xr-x 14 doug.wade 476 May 16 14:32 lerna
drwxr-xr-x 24 doug.wade 816 Mar  4 13:19 less
drwxr-xr-x 12 doug.wade 408 Apr 18 16:51 matcha
drwxr-xr-x 13 doug.wade 442 Feb 16 23:37 mocha
drwxr-xr-x  6 doug.wade 204 May 18 12:55 n
drwxr-xr-x 19 doug.wade 646 Oct 28  2015 node-inspector
drwxr-xr-x 26 doug.wade 884 May 23 15:22 npm
drwxr-xr-x 17 doug.wade 578 May 15 17:53 nsp
drwxr-xr-x 10 doug.wade 340 May 15 17:53 nyc
drwxr-xr-x 15 doug.wade 510 Oct 13  2015 phantom
drwxr-xr-x 13 doug.wade 442 Oct 13  2015 phantomjs
drwxr-xr-x 18 doug.wade 612 May 15 17:53 pm2
drwxr-xr-x 12 doug.wade 408 May 25 18:03 react-server-cli
lrwxr-xr-x  1 doug.wade  43 May 31 17:24 rfnpm -> /Users/doug.wade/code/main/redfin.npm/rfnpm
lrwxr-xr-x  1 doug.wade  29 Apr 22 03:10 sinopia -> /Users/doug.wade/code/sinopia
drwxr-xr-x 15 doug.wade 510 Apr 15 22:10 snyk
drwxr-xr-x  9 doug.wade 306 Mar 22 10:18 tap
drwxr-xr-x 11 doug.wade 374 May  4 15:03 uglify
drwxr-xr-x  9 doug.wade 306 Mar  4 13:19 uglify-js
drwxr-xr-x 11 doug.wade 374 May  2 16:26 webpack
drwxr-xr-x 10 doug.wade 340 May 15 17:53 xo
drwxr-xr-x 27 doug.wade 918 Apr 22 01:08 yapm
drwxr-xr-x  6 doug.wade 204 May 19 17:45 yo
drwxr-xr-x 19 doug.wade 646 May 15 17:53 yuidocjs
```

npm-debug.log
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/iojs', '/usr/local/bin/npm', 'outdated', '-g' ]
2 info using npm@3.8.9
3 info using node@v6.2.0
4 verbose stack Error: Missing required argument #1
4 verbose stack     at module.exports (/usr/local/lib/node_modules/npm/lib/install/mutate-into-logical-tree.js:12:3)
4 verbose stack     at /usr/local/lib/node_modules/npm/lib/outdated.js:78:5
4 verbose stack     at /usr/local/lib/node_modules/npm/lib/outdated.js:62:20
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:186:9
4 verbose stack     at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:17:25)
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:152:20
4 verbose stack     at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:17:25)
4 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:121:22)
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:81:20
4 verbose stack     at FSReqWrap.oncomplete (fs.js:117:15)
5 verbose cwd /Users/doug.wade/code/main/rf-build-metrics-client
6 error Darwin 15.4.0
7 error argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "outdated" "-g"
8 error node v6.2.0
9 error npm  v3.8.9
10 error code EMISSINGARG
11 error typeerror Error: Missing required argument #1
11 error typeerror     at module.exports (/usr/local/lib/node_modules/npm/lib/install/mutate-into-logical-tree.js:12:3)
11 error typeerror     at /usr/local/lib/node_modules/npm/lib/outdated.js:78:5
11 error typeerror     at /usr/local/lib/node_modules/npm/lib/outdated.js:62:20
11 error typeerror     at /usr/local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:186:9
11 error typeerror     at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:17:25)
11 error typeerror     at /usr/local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:152:20
11 error typeerror     at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:17:25)
11 error typeerror     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:121:22)
11 error typeerror     at /usr/local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:81:20
11 error typeerror     at FSReqWrap.oncomplete (fs.js:117:15)
12 error typeerror This is an error with npm itself. Please report this error at:
12 error typeerror     <http://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]
```

still happens on 6.2

```
dougwade main/rf-build-metrics-client ‹dbw-rf-package-pin-dependency*› » npm outdated -g
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "outdated" "-g"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at module.exports (/usr/local/lib/node_modules/npm/lib/install/mutate-into-logical-tree.js:12:3)
npm ERR! typeerror     at /usr/local/lib/node_modules/npm/lib/outdated.js:78:5
npm ERR! typeerror     at /usr/local/lib/node_modules/npm/lib/outdated.js:62:20
npm ERR! typeerror     at /usr/local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:186:9
npm ERR! typeerror     at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:17:25)
npm ERR! typeerror     at /usr/local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:152:20
npm ERR! typeerror     at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:17:25)
npm ERR! typeerror     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:121:22)
npm ERR! typeerror     at /usr/local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:81:20
npm ERR! typeerror     at FSReqWrap.oncomplete (fs.js:117:15)
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/doug.wade/code/main/rf-build-metrics-client/npm-debug.log
```

I hope that helps you get a lead on this one

**Comment by doug-wade** [comment]
Okay, so I did a little more digging.  I logged out `dir`, `er` and `tree` from [outdated.js](https://github.com/npm/npm/blob/master/lib/outdated.js#L77), and got the following values

```
dir /usr/local/lib
er Error: ENOENT: no such file or directory, realpath '/usr/local/lib/node_modules/babel-preset-react-server'
tree undefined
```

sure enough, I had a dangling symlink

```
dougwade code/npm ‹master*› » ls -l /usr/local/lib/node_modules/babel-preset-react-server                                                                                                                                                 1 ↵
lrwxr-xr-x 1 doug.wade 63 Mar 21 18:10 /usr/local/lib/node_modules/babel-preset-react-server -> /Users/doug.wade/code/main/redfin.npm/babel-preset-react-server
dougwade code/npm ‹master*› » ls /Users/doug.wade/code/main/redfin.npm/babel-preset-react-server
ls: cannot access '/Users/doug.wade/code/main/redfin.npm/babel-preset-react-server': No such file or directory
```

After deleting that symlink, `npm outdated -g` worked again, which is consistent with @mbellerose and @tommck finding that deleting the global node_modules directory solved this problem for them, since that would delete the dangling symlink.  It also means the repro is fairly simple:

```
dougwade ~ » cd /tmp
dougwade /tmp » mkdir broken
dougwade /tmp » ln -s ./broken  /usr/local/lib/node_modules/broken
dougwade /tmp » ls -l /usr/local/lib/node_modules/broken
lrwxr-xr-x 1 doug.wade 8 Jun  1 11:29 /usr/local/lib/node_modules/broken -> ./broken
dougwade /tmp » rm -r ./broken
dougwade /tmp » npm outdated -g
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "outdated" "-g"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at module.exports (/usr/local/lib/node_modules/npm/lib/install/mutate-into-logical-tree.js:12:3)
npm ERR! typeerror     at /usr/local/lib/node_modules/npm/lib/outdated.js:78:5
npm ERR! typeerror     at /usr/local/lib/node_modules/npm/lib/outdated.js:62:20
npm ERR! typeerror     at /usr/local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:186:9
npm ERR! typeerror     at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:17:25)
npm ERR! typeerror     at /usr/local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:152:20
npm ERR! typeerror     at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:17:25)
npm ERR! typeerror     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:121:22)
npm ERR! typeerror     at /usr/local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:81:20
npm ERR! typeerror     at FSReqWrap.oncomplete (fs.js:117:15)
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /private/tmp/npm-debug.log
```

I think this is just a case of checking to see if there is an error at [outdated.js ll 77](https://github.com/npm/npm/blob/master/lib/outdated.js#L77), and throwing if there is.

**Comment by watilde** [comment]
The reason is `npm.dir` doesn't have the `package.json` and It stops digging into the `node_modules` in `read-package-tree`. Related issue: https://github.com/npm/npm/issues/10201 and https://github.com/npm/npm/issues/11492.

@iarna @zkat I just rebased the patch. Could you please take a look at this?
https://github.com/npm/read-package-tree/pull/6

**Comment by watilde** [comment]
I think this issue was fixed already.

**Comment by doug-wade** [comment]
Running `npm outdated -g` on 3.10.0 on both my linux box and my mac succeeds; closing -- thanks for the nudge @watilde!
