### ISSUE TITLE
no such file or directory, scandir 'node_modules'

### ISSUE THREAD

**Issue by nixgadget** [npm/npm#12744]
I seem to have some weird issue using npm@3.8.6

So to explain my project structure,

* I have `project A` and `project B`.
* `project A` is dependent on `project B`

`project B` uses `webpack` and `glup` combination to do the compilation. And i'm using the [`externals`](https://webpack.github.io/docs/configuration.html#externals) feature on webpack.

However if I have the following in the webpack config,
`var node_modules = fs.readdirSync('node_modules');`

Im getting this error when running `npm install projectB` in `projectA`,
```
[19:22:41] Error: ENOENT: no such file or directory, scandir 'node_modules'
    at Error (native)
    at Object.fs.readdirSync (fs.js:945:18)
    at Object.<anonymous> (/Volumes/STORAGE/Projects/ProjectA/Core/node_modules/ProjectB/webpack.config.js:46:23)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
```

Im unfamiliar with npm but it appears to be due to the flat hierarchy dependencies that npm@3 produces in parent project `projectA`.

In `projectB` I'm sure I can reference the parent `node_modules` as `../../node_modules` but I think thats a pretty bad idea.

Any help would be appreciated.

**Comment by busches** [comment]
Can you go into further details on what you're trying to do? The error occurs when running `npm install` for `projectA` that has a dependency on `projectB`? or when you're running `npm install` in `projectB`'s directory?

**Comment by KenanY** [comment]
Closing as abandoned.
