### ISSUE TITLE
Sporadic "warning: Recursive process.nextTick detected." followed by "RangeError: Maximum call stack size exceeded" on node 0.10.42 when running "npm install" on an existing node_modules tree.

### ISSUE THREAD

**Issue by lxe** [npm/npm#12754]
broken npm versions: **3.9.2** (at least **3.9.0** and above seem to be affected) 
working npm version: **3.6.0** does not have this issue. I haven't bisected any further as it's hard to reproduce

node: **0.10.42**
OS: **OS X El Capitan (10.11.4) / Darwin 15.4.0 Darwin Kernel Version 15.4.0**

**UPDATE**:

Looks like it's something about childDependencySpecifier that was introduced in e928a30 that causes an infinite recursion of some kind.

Reproduction is tricky, but when `install`ing on an existing tree with some unknown condition, we get this:

```
$ npm install
npm http request GET https://unpm.uberinternal.com/raven-js
npm http 200 https://unpm.uberinternal.com/raven-js
fetchMetadata → 200       ▄ ╢███████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
...
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.

console.js:62
  this._stderr.write(util.format.apply(this, arguments) + '\n');
                                 ^
RangeError: Maximum call stack size exceeded
```

I've seen this happen a few times with very specific module trees... I'm working on a generic reproduction steps.

**UPDATE**:

I was able to retrieve the stack via overriding process.nextTick method with a thing that logs the stack once in a while:

```
...
    at Console.warn (console.js:62:16)
    at maxTickWarn (node.js:412:17)
    at process._nextTick [as _currentTickHandler] (node.js:513:9)
    at process.nextTick (node.js:364:15)
    at process.<anonymous> (/usr/local/lib/node_modules/stackup/node_modules/async-listener/index.js:18:15)
    at process._nextTick [as nextTick] (/usr/local/lib/node_modules/npm/bin/npm-cli.js:14:12)
    at requestFlush (/usr/local/lib/node_modules/npm/node_modules/dezalgo/node_modules/asap/raw.js:95:17)
    at rawAsap (/usr/local/lib/node_modules/npm/node_modules/dezalgo/node_modules/asap/raw.js:18:9)
    at asap (/usr/local/lib/node_modules/npm/node_modules/dezalgo/node_modules/asap/asap.js:26:5)
    at dezalgo (/usr/local/lib/node_modules/npm/node_modules/dezalgo/dezalgo.js:8:3)
    at wrapper (/usr/local/lib/node_modules/npm/node_modules/wrappy/wrappy.js:24:18)
    at andForEachChild (/usr/local/lib/node_modules/npm/lib/install/deps.js:283:10)
    at loadDeps (/usr/local/lib/node_modules/npm/lib/install/deps.js:382:6)
    at Array.0 (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
    at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
    at chain (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
    at /usr/local/lib/node_modules/npm/lib/install/deps.js:298:5
    at cb (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
    at /usr/local/lib/node_modules/npm/lib/install/deps.js:354:21
    at /usr/local/lib/node_modules/npm/lib/install/and-add-parent-to-errors.js:7:24
    at /usr/local/lib/node_modules/npm/lib/install/deps.js:429:11
    at /usr/local/lib/node_modules/npm/node_modules/iferr/index.js:13:50
    at /usr/local/lib/node_modules/npm/lib/install/deps.js:442:5
    at /usr/local/lib/node_modules/npm/lib/install/deps.js:165:5
    at /usr/local/lib/node_modules/npm/lib/install/deps.js:43:25
    at /usr/local/lib/node_modules/npm/lib/install/deps.js:90:7
    at /usr/local/lib/node_modules/stackup/node_modules/async-listener/glue.js:188:31
    at process._tickCallback (node.js:448:13)
```

**Comment by angus-c** [comment]
I got this reliably every time I tried to npm link with 3.9.2. 
3.8.x is fine

**Comment by lxe** [comment]
Trace with longjohn:

```
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
Error
    at process._nextTick [as nextTick] (/usr/local/lib/node_modules/npm/bin/npm-cli.js:10:17)
    at onwrite (_stream_writable.js:266:15)
    at WritableState.onwrite (_stream_writable.js:97:5)
    at WriteStream.Socket._write (net.js:654:5)
    at doWrite (_stream_writable.js:226:10)
    at writeOrBuffer (_stream_writable.js:216:5)
    at WriteStream.Writable.write (_stream_writable.js:183:11)
    at WriteStream.Socket.write (net.js:616:40)
    at WriteStream.stream.write (/usr/local/lib/node_modules/npm/node_modules/npmlog/node_modules/ansi/lib/newlines.js:36:21)
    at Console.warn (console.js:62:16)
---------------------------------------------
    at process._nextTick [as nextTick] (/usr/local/lib/node_modules/npm/bin/npm-cli.js:12:12)
    at childDependencySpecifier (/usr/local/lib/node_modules/npm/lib/install/deps.js:89:20)
    at isDep (/usr/local/lib/node_modules/npm/lib/install/deps.js:39:3)
    at addRequiredDep (/usr/local/lib/node_modules/npm/lib/install/deps.js:159:3)
    at resolveWithExistingModule (/usr/local/lib/node_modules/npm/lib/install/deps.js:443:3)
    at /usr/local/lib/node_modules/npm/lib/install/deps.js:428:7
    at /usr/local/lib/node_modules/npm/node_modules/iferr/index.js:13:50
    at /usr/local/lib/node_modules/npm/lib/install/deps.js:90:7
---------------------------------------------
    at process._nextTick [as nextTick] (/usr/local/lib/node_modules/npm/bin/npm-cli.js:12:12)
    at childDependencySpecifier (/usr/local/lib/node_modules/npm/lib/install/deps.js:89:20)
    at addDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:425:3)
    at /usr/local/lib/node_modules/npm/lib/install/deps.js:384:5
    at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
    at Array.forEach (native)
    at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
    at Array.forEach (native)
    at asyncMap (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
```

Maybe it's e928a30947477a09245f54e9381f46b97bee32d5?

**Comment by lxe** [comment]
Sounds like this is a dupe of #12731
