### ISSUE TITLE
install  ionic@2.0.0-beta.5

### ISSUE THREAD

**Issue by phil-homecu** [npm/npm#12760]
npm install  ionic@2.0.0-beta.5

fails on OSX, works on Ubuntu.  Also fails with -g option.
```
npm install  ionic@2.0.0-beta.5
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/Cellar/node/6.2.0/bin/node" "/usr/local/bin/npm" "install" "ionic@2.0.0-beta.5"
npm ERR! node v6.2.0
npm ERR! npm  v3.9.0
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at markDeps (/usr/local/lib/node_modules/npm/lib/install/deps.js:106:5)
npm ERR! typeerror     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
npm ERR! typeerror     at Array.forEach (native)
npm ERR! typeerror     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
npm ERR! typeerror     at Array.forEach (native)
npm ERR! typeerror     at asyncMap (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
npm ERR! typeerror     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
npm ERR! typeerror     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
npm ERR! typeerror     at chain (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
npm ERR! typeerror     at recalculateMetadata (/usr/local/lib/node_modules/npm/lib/install/deps.js:147:3)
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/xxxx/Documents/projects/tmp/npm-debug.log
```
[npm-debug.log.zip](https://github.com/npm/npm/files/271534/npm-debug.log.zip)

**Comment by phil-homecu** [comment]
please ignore
