### ISSUE TITLE
Error: Not a valid cache tarball name

### ISSUE THREAD

**Issue by cristianp6** [npm/npm#12785]
When I try to install any package on different node+npm versions 
I get an error "Not a valid cache tarball name".
The cause should be because npm downloads the wanted packege with the wrong name: 
~/.npm/tmp/.../registry.npmjs.org/angular-pdf/-/**angular-pdf-1.3.0**.tgz
instead of
~/.npm/tmp/.../registry.npmjs.org/angular-pdf/-/**package**.tgz

Am I wrong? What could be the issue?

BTW: Already tried to search for this but nothing came up :-(

Thanks.

The command log:
```
$ npm install -d --verbose --save angular-pdf
npm info it worked if it ends with ok
npm verb cli [ '/home/cris/.nvm/versions/node/v5.11.1/bin/node',
npm verb cli   '/home/cris/.nvm/versions/node/v5.11.1/bin/npm',
npm verb cli   'install',
npm verb cli   '-d',
npm verb cli   '--verbose',
npm verb cli   '--save',
npm verb cli   'angular-pdf']
npm info using npm@3.8.6
npm info using node@v5.11.1
npm verb get https://registry.npmjs.org/angular-pdf not expired, no request
npm verb cache add spec angular-pdf
npm verb addNamed "latest" is being treated as a dist-tag for angular-pdf
npm info addNameTag [ 'angular-pdf', 'latest' ]
npm verb addNameTag registry:https://registry.npmjs.org/angular-pdf not in flight; fetching
npm verb get https://registry.npmjs.org/angular-pdf not expired, no request
npm verb addNamed "1.3.0" is a plain semver version for angular-pdf
npm verb addRemoteTarball https://registry.npmjs.org/angular-pdf/-/angular-pdf-1.3.0.tgz not in flight; adding
npm verb addRemoteTarball [ 'https://registry.npmjs.org/angular-pdf/-/angular-pdf-1.3.0.tgz',
npm verb addRemoteTarball   'ae8d7b04d5cf4eb4bcd739b497e32ad154a73601' ]
npm info retry fetch attempt 1 at 3:07:24 PM
npm info attempt registry request try #1 at 3:07:24 PM
npm http fetch GET https://registry.npmjs.org/angular-pdf/-/angular-pdf-1.3.0.tgz
npm verb request id accda75133e60c2f
npm http fetch 200 https://registry.npmjs.org/angular-pdf/-/angular-pdf-1.3.0.tgz
npm verb stack Error: Not a valid cache tarball name: /home/cris/.npm/tmp/npm-9394-eb28e5f3/registry.npmjs.org/angular-pdf/-/angular-pdf-1.3.0.tgz
npm verb stack     at addLocalTarball (/home/cris/.nvm/versions/node/v5.11.1/lib/node_modules/npm/lib/cache/add-local-tarball.js:40:17)
npm verb stack     at next (/home/cris/.nvm/versions/node/v5.11.1/lib/node_modules/npm/lib/cache/add-remote-tarball.js:41:5)
npm verb stack     at /home/cris/.nvm/versions/node/v5.11.1/lib/node_modules/npm/lib/cache/add-remote-tarball.js:81:7
npm verb stack     at /home/cris/.nvm/versions/node/v5.11.1/lib/node_modules/npm/lib/utils/pulse-till-done.js:19:8
npm verb stack     at /home/cris/.nvm/versions/node/v5.11.1/lib/node_modules/npm/lib/cache/add-remote-tarball.js:117:16
npm verb stack     at /home/cris/.nvm/versions/node/v5.11.1/lib/node_modules/npm/node_modules/sha/index.js:24:37
npm verb stack     at ReadStream.<anonymous> (/home/cris/.nvm/versions/node/v5.11.1/lib/node_modules/npm/node_modules/sha/index.js:72:7)
npm verb stack     at emitNone (events.js:85:20)
npm verb stack     at ReadStream.emit (events.js:179:7)
npm verb stack     at endReadableNT (_stream_readable.js:913:12)
npm verb cwd /home/cris/Dev/quokky/web/quokky-web-common
npm ERR! Linux 4.4.0-22-generic
npm ERR! argv "/home/cris/.nvm/versions/node/v5.11.1/bin/node" "/home/cris/.nvm/versions/node/v5.11.1/bin/npm" "install" "-d" "--verbose" "--save" "angular-pdf" "--cache-min" "999999999"
npm ERR! node v5.11.1
npm ERR! npm  v3.8.6

npm ERR! Not a valid cache tarball name: /home/cris/.npm/tmp/npm-9394-eb28e5f3/registry.npmjs.org/angular-pdf/-/angular-pdf-1.3.0.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     `<https://github.com/npm/npm/issues>`
npm verb exit [ 1, true ]
```

**Comment by cristianp6** [comment]
Solved purging ~/.npm, ~/.nvn and ~/.npmrc and reinstalling nvm

**Comment by jcrben** [comment]
Hmm, same issue, using `nodenv`

**Comment by eternaltreesnow** [comment]
Same issue. Finally I found that this error comes from the anti-virus software.
Pls exit the anti-virus software first, and check the integrity of the NodeJS installation package. Sometimes some file will been delete by the anti-virus software. After that use the Administrator CMD to reinstall the package.
Best wishes!

**Comment by de-mim-1974** [comment]
By the installation via:
...\npm-cache\npm\5.5.1>npm install ./npm-5.5.1.tgz -> Tarball error :(
via (copy npm-5.5.1.tgz to testfolder before) :
c:\testfolder> npm install ./npm-5.5.1.tgz -> no Error :)

**Comment by askilada** [comment]
@de-mim-1974 Thanks man that helped me a lot !
