### ISSUE TITLE
Error: Cannot find module 'domelementtype'

### ISSUE THREAD

**Issue by tonikung** [npm/npm#12797]
**i can't run bot**

module.js:338
    throw err;
    ^
Error: Cannot find module 'domelementtype'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/var/www/bot/node_modules/steam-tradeoffer-manager/no            de_modules/steamcommunity/node_modules/cheerio/node_modules/css-select/node_modu            les/domutils/lib/stringify.js:1:81)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

**Comment by gilrosenthal** [comment]
Have you run 
`npm install`?

**Comment by tonikung** [comment]
[root@da bot]# node bot1.js
/var/www/bot/node_modules/mysql/lib/protocol/Parser.js:82
        throw err;
              ^
Error: MySQL server is requesting the old and insecure pre-4.1 auth mechanism.Upgrade the user password or use the {insecureAuth: true} option.
    at Handshake.UseOldPasswordPacket (/var/www/bot/node_modules/mysql/lib/protocol/sequences/Handshake.js:83:15)
    at Protocol._parsePacket (/var/www/bot/node_modules/mysql/lib/protocol/Protocol.js:274:23)
    at Parser.write (/var/www/bot/node_modules/mysql/lib/protocol/Parser.js:77:12)
    at Protocol.write (/var/www/bot/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/var/www/bot/node_modules/mysql/lib/Connection.js:96:28)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:540:20)
    --------------------
    at Protocol._enqueue (/var/www/bot/node_modules/mysql/lib/protocol/Protocol.js:135:48)
    at Protocol.handshake (/var/www/bot/node_modules/mysql/lib/protocol/Protocol.js:52:41)
    at Connection.connect (/var/www/bot/node_modules/mysql/lib/Connection.js:123:18)
    at Object.<anonymous> (/var/www/bot/bot1.js:89:2403)
    at c (/var/www/bot/bot1.js:89:419)
    at /var/www/bot/bot1.js:90:18865
    at Object.<anonymous> (/var/www/bot/bot1.js:90:18907)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
