### ISSUE TITLE
npm search yeoman-generator  ERROR

### ISSUE THREAD

**Issue by wanghaisheng** [npm/npm#12791]
```
➜  HL7China_CDA_Validator npm search yeoman-generator
npm WARN Building the local index for the first time, please be patient
npm ERR! Darwin 15.4.0
npm ERR! argv "/Users/wanghaisheng/.nvm/versions/node/v4.4.4/bin/node" "/Users/wanghaisheng/.nvm/versions/node/v4.4.4/bin/npm" "search" "yeoman-generator"
npm ERR! node v4.4.4
npm ERR! npm  v3.9.2
npm ERR! code E200

npm ERR! true true: -/all
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/wanghaisheng/workspace/HL7China_CDA_Validator/npm-debug.log

```

```
➜  HL7China_CDA_Validator cat npm-debug.log 
0 info it worked if it ends with ok
1 verbose cli [ '/Users/wanghaisheng/.nvm/versions/node/v4.4.4/bin/node',
1 verbose cli   '/Users/wanghaisheng/.nvm/versions/node/v4.4.4/bin/npm',
1 verbose cli   'search',
1 verbose cli   'yeoman-generator' ]
2 info using npm@3.9.2
3 info using node@v4.4.4
4 silly mapToRegistry name -/all
5 silly mapToRegistry using default registry
6 silly mapToRegistry registry https://registry.npm.taobao.org/
7 silly mapToRegistry data Result {
7 silly mapToRegistry   raw: '-/all',
7 silly mapToRegistry   scope: null,
7 silly mapToRegistry   name: null,
7 silly mapToRegistry   rawSpec: '-/all',
7 silly mapToRegistry   spec: '-/all',
7 silly mapToRegistry   type: 'local' }
8 silly mapToRegistry uri https://registry.npm.taobao.org/-/all
9 info updateIndex /Users/wanghaisheng/.npm/registry.npm.taobao.org/-/all/.cache.json
10 verbose correctMkdir /Users/wanghaisheng/.npm correctMkdir not in flight; initializing
11 warn Building the local index for the first time, please be patient
12 silly update-index fetching https://registry.npm.taobao.org/-/all
13 verbose request uri https://registry.npm.taobao.org/-/all
14 verbose request no auth needed
15 info attempt registry request try #1 at 15:18:00
16 verbose request id 380fe9ac3ee4438a
17 http request GET https://registry.npm.taobao.org/-/all
18 http 200 https://registry.npm.taobao.org/-/all
19 verbose headers { date: 'Sat, 21 May 2016 07:18:03 GMT',
19 verbose headers   'content-type': 'application/json; charset=utf-8',
19 verbose headers   'content-length': '6323106',
19 verbose headers   connection: 'keep-alive',
19 verbose headers   etag: '"607ba2-HJiklDF5A0X+cGvc53TEqA"',
19 verbose headers   'x-readtime': '3935' }
20 verbose stack Error: true true: -/all
20 verbose stack     at makeError (/Users/wanghaisheng/.nvm/versions/node/v4.4.4/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
20 verbose stack     at CachingRegistryClient.<anonymous> (/Users/wanghaisheng/.nvm/versions/node/v4.4.4/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:252:14)
20 verbose stack     at Request._callback (/Users/wanghaisheng/.nvm/versions/node/v4.4.4/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
20 verbose stack     at Request.self.callback (/Users/wanghaisheng/.nvm/versions/node/v4.4.4/lib/node_modules/npm/node_modules/request/request.js:200:22)
20 verbose stack     at emitTwo (events.js:87:13)
20 verbose stack     at Request.emit (events.js:172:7)
20 verbose stack     at Request.<anonymous> (/Users/wanghaisheng/.nvm/versions/node/v4.4.4/lib/node_modules/npm/node_modules/request/request.js:1067:10)
20 verbose stack     at emitOne (events.js:82:20)
20 verbose stack     at Request.emit (events.js:169:7)
20 verbose stack     at IncomingMessage.<anonymous> (/Users/wanghaisheng/.nvm/versions/node/v4.4.4/lib/node_modules/npm/node_modules/request/request.js:988:12)
21 verbose statusCode 200
22 verbose cwd /Users/wanghaisheng/workspace/HL7China_CDA_Validator
23 error Darwin 15.4.0
24 error argv "/Users/wanghaisheng/.nvm/versions/node/v4.4.4/bin/node" "/Users/wanghaisheng/.nvm/versions/node/v4.4.4/bin/npm" "search" "yeoman-generator"
25 error node v4.4.4
26 error npm  v3.9.2
27 error code E200
28 error true true: -/all
29 error If you need help, you may report this error at:
29 error     <https://github.com/npm/npm/issues>
30 verbose exit [ 1, true ]

```

**Comment by ssi-anik** [comment]
It's closed, can anyone define why is this error?
