### ISSUE TITLE
Error PLS HELP FAST

### ISSUE THREAD

**Issue by Triblerek** [npm/npm#12824]
I Have Jackpot CSGO

root@Jackpot:~/bot# node bot.js

module.js:338
    throw err;
          ^
Error: Cannot find module './dist/ByteBufferNB.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/root/bot/node_modules/steam-user/node_modules/steam-client/node_modules/protobufjs/node_modules/bytebuffer/index.js:16:29)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

**Comment by watilde** [comment]
Hi, this seems an error related `bot.js` you wrote, not npm. I'm not sure the source of `bot.js`, but the error is this:
> Error: Cannot find module './dist/ByteBufferNB.js'

So you need to put a file `~/bot/dist/ByteBufferNB.js`, but it really depends on your file. Probably it's [this file](http://csgo-spin-roulette.16mb.com/Csgomad.ru/Private%20Bot/node_modules/steam/node_modules/bytebuffer/dist/ByteBufferAB.js) I found by searching the file name on Google. Anyway this issue tracker is for npm, not for user's script.

I hope you can fix it!
