### ISSUE TITLE
Problem after update

### ISSUE THREAD

**Issue by hunzaboy** [npm/npm#12856]
Hi,

I am getting the following error after i updated NPM and Node to latest versions. 

> 0 info it worked if it ends with ok
> 1 verbose cli [ 'C:\Program Files\nodejs\node.exe',
> 1 verbose cli   'C:\Users\hunzaboy\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js',
> 1 verbose cli   'init' ]
> 2 info using npm@3.9.2
> 3 info using node@v6.2.0
> 4 verbose stack Error: Cannot find module 'init-package-json'
> 4 verbose stack     at Function.Module._resolveFilename (module.js:440:15)
> 4 verbose stack     at Function.Module._load (module.js:388:25)
> 4 verbose stack     at Module.require (module.js:468:17)
> 4 verbose stack     at require (internal/module.js:20:19)
> 4 verbose stack     at Object.<anonymous> (C:\Users\hunzaboy\AppData\Roaming\npm\node_modules\npm\lib\init.js:7:16)
> 4 verbose stack     at Module._compile (module.js:541:32)
> 4 verbose stack     at Object.Module._extensions..js (module.js:550:10)
> 4 verbose stack     at Module.load (module.js:458:32)
> 4 verbose stack     at tryModuleLoad (module.js:417:12)
> 4 verbose stack     at Function.Module._load (module.js:409:3)
> 5 verbose cwd C:\xampp\htdocs\gr
> 6 error Windows_NT 10.0.10586
> 7 error argv "C:\Program Files\nodejs\node.exe" "C:\Users\hunzaboy\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "init"
> 8 error node v6.2.0
> 9 error npm  v3.9.2
> 10 error code MODULE_NOT_FOUND
> 11 error Cannot find module 'init-package-json'
> 12 error If you need help, you may report this error at:
> 12 error     https://github.com/npm/npm/issues
> 13 verbose exit [ 1, true ]

**Comment by hunzaboy** [comment]
I'll appreciate if anyone can help.

I tried to install Node again but it didn't helped. Tried everything but no luck.
