### ISSUE TITLE
Trouble running npm install

### ISSUE THREAD

**Issue by conor909** [npm/npm#12853]
running `npm install` produces these errors
node -v v4.2.4
npm -v 1.4.3

`````
npm http GET https://registry.npmjs.org/ghost-s3-storage
npm http GET https://registry.npmjs.org/Casper
npm http GET https://registry.npmjs.org/ncp
npm http GET https://registry.npmjs.org/pg
npm http GET https://registry.npmjs.org/ghost/0.8.0
npm http 304 https://registry.npmjs.org/ghost-s3-storage
npm http 304 https://registry.npmjs.org/ncp
npm http 304 https://registry.npmjs.org/ghost/0.8.0
npm http 304 https://registry.npmjs.org/pg
npm http 404 https://registry.npmjs.org/Casper
npm ERR! TypeError: Cannot convert undefined or null to object
npm ERR!     at Function.keys (native)
npm ERR!     at installTargetsError (C:\Users\Conor\AppData\Roaming\nvm\v4.2.4\node_modules\npm\lib\cache.js:765:24)
npm ERR!     at C:\Users\Conor\AppData\Roaming\nvm\v4.2.4\node_modules\npm\lib\cache.js:695:10
npm ERR!     at saved (C:\Users\Conor\AppData\Roaming\nvm\v4.2.4\node_modules\npm\node_modules\npm-registry-client\lib\get.js:148:7)
npm ERR!     at C:\Users\Conor\AppData\Roaming\nvm\v4.2.4\node_modules\npm\node_modules\graceful-fs\polyfills.js:133:7
npm ERR!     at FSReqWrap.oncomplete (fs.js:82:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 10.0.10586
npm ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--production"
npm ERR! cwd C:\Users\Conor\Documents\conor-mcgrath
npm ERR! node -v v4.2.4
npm ERR! npm -v 1.4.3
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\Conor\Documents\conor-mcgrath\npm-debug.log
npm ERR! not ok code 0
`````

**Comment by KenanY** [comment]
@conor909 Does this also occur if you [update `npm`](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm)?

**Comment by conor909** [comment]
I got around this issue by moving down from `node -v v4.2.4` to `node -v v4.2.0`, I'm not exactly sure what the problem with node or npm was, but it fixed my particular issue.

**Comment by KenanY** [comment]
@conor909 Umm, okay, good to hear. Would you be alright with closing this issue then?

**Comment by AurelioDeRosa** [comment]
I'm actually experiencing the same issue on Node 5.9.0 running npm 3.8.3 as of today. Everything was working fine on Friday.
