### ISSUE TITLE
npm start ERR!

### ISSUE THREAD

**Issue by jrmalin** [npm/npm#12912]
```
Admins-MacBook-Pro:~ justin$ npm start
npm ERR! Darwin 15.5.0
npm ERR! argv "/Users/justin/.nvm/versions/node/v4.4.4/bin/node" "/Users/justin/.nvm/versions/node/v4.4.4/bin/npm" "start"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! path /Users/justin/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/Users/justin/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/justin/npm-debug.log
Admins-MacBook-Pro:~ justin$
```

When I run npm start, I get all of these errors.  I found others who had these errors in other issues, but none of them were resolved.  I have included my npm-debug.log below:
```

0 info it worked if it ends with ok
1 verbose cli [ '/Users/justin/.nvm/versions/node/v4.4.4/bin/node',
1 verbose cli   '/Users/justin/.nvm/versions/node/v4.4.4/bin/npm',
1 verbose cli   'start' ]
2 info using npm@2.15.1
3 info using node@v4.4.4
4 verbose config Skipping project config: /Users/justin/.npmrc. (matches userconfig)
5 verbose stack Error: ENOENT: no such file or directory, open '/Users/justin/package.json'
5 verbose stack     at Error (native)
6 verbose cwd /Users/justin
7 error Darwin 15.5.0
8 error argv "/Users/justin/.nvm/versions/node/v4.4.4/bin/node" "/Users/justin/.nvm/versions/node/v4.4.4/bin/npm" "start"
9 error node v4.4.4
10 error npm  v2.15.1
11 error path /Users/justin/package.json
12 error code ENOENT
13 error errno -2
14 error syscall open
15 error enoent ENOENT: no such file or directory, open '/Users/justin/package.json'
15 error enoent This is most likely not a problem with npm itself
15 error enoent and is related to npm not being able to find a file.
16 verbose exit [ -2, true ]
```

**Comment by KenanY** [comment]
Hi @jrmalin! From the logs, it is clear to me that you are running `npm start` from a directory without a `package.json` present. Because of this, `npm` has no idea what you want it to do because you have not defined a "`start`" script in the `"scripts"` section of your `package.json`.

Hopefully the documentation on `npm start` and scripts will help you out further:

  - https://docs.npmjs.com/cli/start
  - https://docs.npmjs.com/misc/scripts

**Comment by jrmalin** [comment]
I do have a package.json file, so I've included its contents below:

```
Admins-MacBook-Pro:rosterTool justin$ ls
dist			package.json		typings.json
index.html		src			webpack.config.js
node_modules		tsconfig.json
npm-debug.log		typings
Admins-MacBook-Pro:rosterTool justin$ cat package.json
{
  "name": "proj",
  "version": "1.0.0",
  "description": "",
  "main": "./lib/bundle.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "axios": "^0.11.1",
    "history": "^1.17.0",
    "install": "^0.8.1",
    "npm": "^3.9.3",
    "pag": "^1.0.1",
    "pg": "^4.5.5",
    "pg-hstore": "^2.3.2",
    "react": "^15.0.2",
    "react-dom": "^15.0.2",
    "react-router": "^2.4.1",
    "sequelize": "^3.23.3"
  },
  "devDependencies": {
    "source-map-loader": "^0.1.5",
    "ts-loader": "^0.8.2"
  }
}
```

**Comment by jrmalin** [comment]
So because the file exists, shouldn't it default to the proper location?

**Comment by KenanY** [comment]
@jrmalin Hmm, are you use you are in the right directory when you run `npm start`? The error log shows that you are in your home directory. Does `/Users/justin/package.json` exist? If not, then you will get the error you are seeing if you continue to run `npm start` from your home directory.

**Comment by jrmalin** [comment]
I ran it again to be sure that I was in the correct directory and am still having the same problems.  I may have accidentally been in the home directory to start, but I definitely ran it while in the correct directory this time.
```

Admins-MacBook-Pro:rosterTool justin$ ls
dist			package.json		typings.json
index.html		src			webpack.config.js
node_modules		tsconfig.json
npm-debug.log		typings
Admins-MacBook-Pro:rosterTool justin$ pwd
/Users/justin/Dev/rosterTool
Admins-MacBook-Pro:rosterTool justin$ npm start
npm ERR! Darwin 15.5.0
npm ERR! argv "/Users/justin/.nvm/versions/node/v4.4.4/bin/node" "/Users/justin/.nvm/versions/node/v4.4.4/bin/npm" "start"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1

npm ERR! missing script: start
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/justin/Dev/rosterTool/npm-debug.log
```

```
Admins-MacBook-Pro:rosterTool justin$ cat npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/Users/justin/.nvm/versions/node/v4.4.4/bin/node',
1 verbose cli   '/Users/justin/.nvm/versions/node/v4.4.4/bin/npm',
1 verbose cli   'start' ]
2 info using npm@2.15.1
3 info using node@v4.4.4
4 verbose stack Error: missing script: start
4 verbose stack     at run (/Users/justin/.nvm/versions/node/v4.4.4/lib/node_modules/npm/lib/run-script.js:142:19)
4 verbose stack     at /Users/justin/.nvm/versions/node/v4.4.4/lib/node_modules/npm/lib/run-script.js:58:5
4 verbose stack     at /Users/justin/.nvm/versions/node/v4.4.4/lib/node_modules/npm/node_modules/read-package-json/read-json.js:345:5
4 verbose stack     at checkBinReferences_ (/Users/justin/.nvm/versions/node/v4.4.4/lib/node_modules/npm/node_modules/read-package-json/read-json.js:309:45)
4 verbose stack     at final (/Users/justin/.nvm/versions/node/v4.4.4/lib/node_modules/npm/node_modules/read-package-json/read-json.js:343:3)
4 verbose stack     at then (/Users/justin/.nvm/versions/node/v4.4.4/lib/node_modules/npm/node_modules/read-package-json/read-json.js:113:5)
4 verbose stack     at /Users/justin/.nvm/versions/node/v4.4.4/lib/node_modules/npm/node_modules/read-package-json/read-json.js:300:12
4 verbose stack     at /Users/justin/.nvm/versions/node/v4.4.4/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
5 verbose cwd /Users/justin/Dev/rosterTool
6 error Darwin 15.5.0
7 error argv "/Users/justin/.nvm/versions/node/v4.4.4/bin/node" "/Users/justin/.nvm/versions/node/v4.4.4/bin/npm" "start"
8 error node v4.4.4
9 error npm  v2.15.1
10 error missing script: start
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
```

Thanks for helping with this, I really appreciate it.

**Comment by KenanY** [comment]
@jrmalin Thanks. Since you don't have a `server.js` in that directory, `npm` will not run the default `node server.js` start script (perhaps I should add that to the documentation).

**Comment by KenanY** [comment]
This is (somewhat) implied [here](https://docs.npmjs.com/misc/scripts#default-values):

> If there is a `server.js` file in the root of your package, then npm will default the `start` command to `node server.js`.

**Comment by jrmalin** [comment]
@KenanY Yes it is implied, I missed that.  Thanks for the help.

**Comment by othiym23** [comment]
Closing as resolved.
