### ISSUE TITLE
ionic build android doesn't works

### ISSUE THREAD

**Issue by sykes10** [npm/npm#12944]
I tried to generate the .apk but the console give this error

/usr/local/lib/node_modules/cordova/node_modules/insight/node_modules/configstore/index.js:53
                throw err;
                ^

Error: EACCES: permission denied, open '/Users/sykes/.config/configstore/insight-cordova.json'
You don't have access to this file.

```
at Error (native)
at Object.fs.openSync (fs.js:549:18)
at Object.fs.readFileSync (fs.js:397:15)
at Object.create.all.get (/usr/local/lib/node_modules/cordova/node_modules/insight/node_modules/configstore/index.js:34:26)
at Object.Configstore (/usr/local/lib/node_modules/cordova/node_modules/insight/node_modules/configstore/index.js:27:44)
at new Insight (/usr/local/lib/node_modules/cordova/node_modules/insight/lib/index.js:38:34)
at Object.<anonymous> (/usr/local/lib/node_modules/cordova/src/telemetry.js:37:15)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
```

I try to reinstall all the components but the issues not fixed yet.

thanks

**Comment by robations** [comment]
Not sure this has anything to do with npm directly?

The permission problem could be to do with installing cordova under sudo, you might check out [this guide](https://johnpapa.net/how-to-use-npm-global-without-sudo-on-osx/) (assuming you are using OS X).
