### ISSUE TITLE
Refusal to install

### ISSUE THREAD

**Issue by xivMiku** [npm/npm#12955]
I always install things from a dummy dir that I can delete later so perhaps that is the issue?

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--save-dev',
1 verbose cli   'apache-server-configs' ]
2 info using npm@3.9.3
3 info using node@v6.2.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData apache-server-configs
8 silly fetchNamedPackageData apache-server-configs
9 silly mapToRegistry name apache-server-configs
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'apache-server-configs',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   name: 'apache-server-configs',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/apache-server-configs
14 verbose request uri https://registry.npmjs.org/apache-server-configs
15 verbose request no auth needed
16 info attempt registry request try #1 at 7:14:04 PM
17 verbose request id 7ba30855d380a38a
18 verbose etag "8R8W1LHFUB1Q94TNYRQFE0TLZ"
19 http request GET https://registry.npmjs.org/apache-server-configs
20 http 304 https://registry.npmjs.org/apache-server-configs
21 verbose headers { date: 'Sat, 04 Jun 2016 23:14:06 GMT',
21 verbose headers   via: '1.1 varnish',
21 verbose headers   'cache-control': 'max-age=300',
21 verbose headers   etag: '"8R8W1LHFUB1Q94TNYRQFE0TLZ"',
21 verbose headers   age: '0',
21 verbose headers   connection: 'keep-alive',
21 verbose headers   'x-served-by': 'cache-dfw1842-DFW',
21 verbose headers   'x-cache': 'MISS',
21 verbose headers   'x-cache-hits': '0',
21 verbose headers   'x-timer': 'S1465082046.233241,VS0,VE265',
21 verbose headers   vary: 'Accept-Encoding' }
22 silly get cb [ 304,
22 silly get   { date: 'Sat, 04 Jun 2016 23:14:06 GMT',
22 silly get     via: '1.1 varnish',
22 silly get     'cache-control': 'max-age=300',
22 silly get     etag: '"8R8W1LHFUB1Q94TNYRQFE0TLZ"',
22 silly get     age: '0',
22 silly get     connection: 'keep-alive',
22 silly get     'x-served-by': 'cache-dfw1842-DFW',
22 silly get     'x-cache': 'MISS',
22 silly get     'x-cache-hits': '0',
22 silly get     'x-timer': 'S1465082046.233241,VS0,VE265',
22 silly get     vary: 'Accept-Encoding' } ]
23 verbose etag https://registry.npmjs.org/apache-server-configs from cache
24 verbose get saving apache-server-configs to /root/.npm/registry.npmjs.org/apache-server-configs/.cache.json
25 verbose correctMkdir /root/.npm correctMkdir not in flight; initializing
26 silly install normalizeTree
27 silly loadCurrentTree Finishing
28 silly loadIdealTree Starting
29 silly install loadIdealTree
30 silly cloneCurrentTree Starting
31 silly install cloneCurrentTreeToIdealTree
32 silly cloneCurrentTree Finishing
33 silly loadShrinkwrap Starting
34 silly install loadShrinkwrap
35 silly loadShrinkwrap Finishing
36 silly loadAllDepsIntoIdealTree Starting
37 silly install loadAllDepsIntoIdealTree
38 silly rollbackFailedOptional Starting
39 silly rollbackFailedOptional Finishing
40 silly runTopLevelLifecycles Starting
41 silly runTopLevelLifecycles Finishing
42 silly install printInstalled
43 verbose stack Error: Refusing to install apache-server-configs as a dependency of itself
43 verbose stack     at checkSelf (/usr/lib/node_modules/npm/lib/install/validate-args.js:53:14)
43 verbose stack     at Array.<anonymous> (/usr/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
43 verbose stack     at LOOP (/usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
43 verbose stack     at chain (/usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
43 verbose stack     at /usr/lib/node_modules/npm/lib/install/validate-args.js:16:5
43 verbose stack     at /usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
43 verbose stack     at Array.forEach (native)
43 verbose stack     at /usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
43 verbose stack     at Array.forEach (native)
43 verbose stack     at asyncMap (/usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
44 verbose cwd /apachedl
45 error Linux 3.2.0-4-amd64
46 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "--save-dev" "apache-server-configs"
47 error node v6.2.1
48 error npm  v3.9.3
49 error code ENOSELF
50 error Refusing to install apache-server-configs as a dependency of itself
51 error If you need help, you may report this error at:
51 error     <https://github.com/npm/npm/issues>
52 verbose exit [ 1, true ]

```

**Comment by KenanY** [comment]
@xivMiku Is the `"name"` property of your `package.json` set to `"apache-server-configs"` by any chance?

**Comment by xivMiku** [comment]
@KenanY Yeah it is should I change that?

**Comment by KenanY** [comment]
@xivMiku Yes, it cannot be the same name as any of your dependencies.

**Comment by KenanY** [comment]
@xivMiku It has been a week now with no reply... are you still seeing this issue?

**Comment by xivMiku** [comment]
@KenanY I decided it wasn't worth the trouble unfortunately after trying your suggestion and not getting it to work. Thanks for the attempted follow up, I appreciate that and I'm also sorry for the lack of communication on my part.
