### ISSUE TITLE
I get the following error when running NPM start for Angaulr 2 RC-1

### ISSUE THREAD

**Issue by ghaddon1** [npm/npm#12950]
C:\Users\Gary\WebstormProjects\Angular-2-Tutorials\Template>npm start.

**What should I check or do to fix issue?**

All of the following are stored in npm global:

C:\Users\Gary\WebstormProjects\Angular-2-Tutorials\Template>npm list -g --depth=0
C:\Users\Gary\AppData\Roaming\npm
+-- babel-cli@6.8.0
+-- concurrently@2.0.0
+-- gulp@3.9.1
+-- lite-server@2.2.0
+-- nodemon@1.9.2
+-- npm@3.8.8
+-- typescript@1.8.10
+-- typings@0.8.1
+-- webpack@1.13.0
`-- webpack-dev-server@1.14.1

> angular@1.0.0 start C:\Users\Gary\WebstormProjects\Angular-2-Tutorials\Template
> tsc && concurrently "npm run tsc:w" "npm run lite"

[1]
[1] > angular@1.0.0 lite C:\Users\Gary\WebstormProjects\Angular-2-Tutorials\Template
[1] > lite-server
[1]
[0]
[0] > angular@1.0.0 tsc:w C:\Users\Gary\WebstormProjects\Angular-2-Tutorials\Template
[0] > tsc -w
[0]
[1] Did not detect a `bs-config.json` or `bs-config.js` override file. Using lite-server defaults...
[1] *\* browser-sync config **
[1] { injectChanges: false,
[1]   files: [ './*_/_.{html,htm,css,js}' ],
[1]   watchOptions: { ignored: 'node_modules' },
[1]   server: { baseDir: './', middleware: [ [Function], [Function] ] } }
[0] 4:31:09 PM - Compilation complete. Watching for file changes.
[1] [BS] Access URLs:
[1]  ----------------------------------
[1]        Local: http://localhost:3000
[1]     External: http://10.0.0.8:3000
[1]  ----------------------------------
[1]           UI: http://localhost:3001
[1]  UI External: http://10.0.0.8:3001
[1]  ----------------------------------
[1] [BS] Serving files from: ./
[1] [BS] Watching files...
[1] events.js:160
[1]       throw er; // Unhandled 'error' event
[1]       ^
[1]
[1] Error: spawn cmd ENOENT
[1]     at exports._errnoException (util.js:949:11)
[1]     at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
[1]     at onErrorNT (internal/child_process.js:348:16)
[1]     at _combinedTickCallback (internal/process/next_tick.js:74:11)
[1]     at process._tickCallback (internal/process/next_tick.js:98:9)
[1]
[1] npm
[1]  ERR! Windows_NT 10.0.10586
[1] npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Users\Gary\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "run" "lite"
[1] npm ERR! node v6.1.0
[1] npm ERR! npm  v3.8.8
[1] npm ERR! code ELIFECYCLE
[1] npm ERR! angular@1.0.0 lite: `lite-server`
[1] npm ERR! Exit status 1
[1] npm ERR!
[1] npm ERR! Failed at the angular@1.0.0 lite script 'lite-server'.
[1] npm ERR! Make sure you have the latest version of node.js and npm installed.
[1] npm ERR! If you do, this is most likely a problem with the angular package,
[1] npm ERR! not with npm itself.
[1] npm ERR! Tell the author that this fails on your system:
[1] npm ERR!     lite-server
[1] npm ERR! You can get information on how to open an issue for this project with:
[1] npm ERR!     npm bugs angular
[1] npm ERR! Or if that isn't available, you can get their info via:
[1] npm ERR!     npm owner ls angular
[1] npm ERR! There is likely additional logging output above.
[1]
[1] npm ERR! Please include the following file with any support request:
[1] npm ERR!     C:\Users\Gary\WebstormProjects\Angular-2-Tutorials\Template\npm-debug.log
[1] npm run lite exited with code 1

**Comment by jarnail104** [comment]
$ npm start
npm ERR! Windows_NT 6.1.7600
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "start"
npm ERR! node v4.4.7
npm ERR! npm v2.15.8
npm ERR! path D:\myangular\package.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open 'D:\myangular\package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR! D:\myangular\npm-debug.log

**Comment by feeleen** [comment]
got exactly the same issue on windows 8.1: 
`[1] [BS] Serving files from: ./
[1] [BS] Watching files...
[1] events.js:160
[1] throw er; // Unhandled 'error' event
[1] ^
[1]
[1] Error: spawn cmd ENOENT
[1] at exports._errnoException (util.js:949:11)
[1] at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)`
