### ISSUE TITLE
npm install for node-debugger is failing

### ISSUE THREAD

**Issue by sudhirbitsgoa** [npm/npm#12959]
```
npm ERR! fetch failed https://registry.npmjs.org/geval/-/geval-2.1.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/mercury/-/mercury-14.1.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/ramda/-/ramda-0.14.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/tree-kill/-/tree-kill-0.1.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/geval/-/geval-2.1.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/ramda/-/ramda-0.14.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/mercury/-/mercury-14.1.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/tree-kill/-/tree-kill-0.1.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/geval/-/geval-2.1.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/ramda/-/ramda-0.14.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/tree-kill/-/tree-kill-0.1.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/mercury/-/mercury-14.1.0.tgz
npm ERR! Error: 503 Service Unavailable
npm ERR!     at WriteStream.<anonymous> (/home/xxxxx/.nvm/v0.10.41/lib/node_modules/npm/lib/utils/fetch.js:58:12)
npm ERR!     at WriteStream.emit (events.js:117:20)
npm ERR!     at evalmachine.<anonymous>:1610:14
npm ERR!     at /home/xxxxx/.nvm/v0.10.41/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:102:5
npm ERR!     at Object.oncomplete (evalmachine.<anonymous>:108:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.19.0-59-generic
npm ERR! command "/home/xxxx/.nvm/v0.10.41/bin/node" "/home/xxxx/.nvm/v0.10.41/bin/npm" "install"
npm ERR! cwd /home/xxxxx/.atom/packages/atom-node-debugger
npm ERR! node -v v0.10.41
npm ERR! npm -v 1.4.29
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/xxxx/.atom/packages/atom-node-debugger/npm-debug.log
```

**Comment by sudhirbitsgoa** [comment]
npm server was down. works now
