### ISSUE TITLE
npm install nocache fails, registry returns 503

### ISSUE THREAD

**Issue by indraneelr** [npm/npm#12961]
Hi,

I am trying to 'npm install' the dependencies for my project and its failing when trying to install nocache module. Here's a snippet of the log:

> 0 info it worked if it ends with ok
> 1 verbose cli [ 'C:\\softwares\\nodejs\\node.exe',
> 1 verbose cli   'C:\\softwares\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
> 1 verbose cli   'install' ]
> 2 info using npm@3.8.6
> 3 info using node@v5.11.0
> 4 silly loadCurrentTree Starting
> 5 silly install loadCurrentTree
> 6 silly install readLocalPackageData
> 7 silly install normalizeTree
> 8 silly loadCurrentTree Finishing
> 9 silly loadIdealTree Starting
> 10 silly install loadIdealTree
> 11 silly cloneCurrentTree Starting
> 12 silly install cloneCurrentTreeToIdealTree
> 13 silly cloneCurrentTree Finishing
> 14 silly loadShrinkwrap Starting
> 15 silly install loadShrinkwrap
> 16 silly loadShrinkwrap Finishing
> 17 silly loadAllDepsIntoIdealTree Starting
> 18 silly install loadAllDepsIntoIdealTree
> 19 silly fetchNamedPackageData compression
> 20 silly mapToRegistry name compression
> 21 silly mapToRegistry using default registry
> 22 silly mapToRegistry registry https://registry.npmjs.org/
> 23 silly mapToRegistry data Result {
> 23 silly mapToRegistry   raw: 'compression',
> 23 silly mapToRegistry   scope: null,
> 23 silly mapToRegistry   name: 'compression',
> 23 silly mapToRegistry   rawSpec: '',
> 23 silly mapToRegistry   spec: 'latest',
> 23 silly mapToRegistry   type: 'tag' }
> 24 silly mapToRegistry uri https://registry.npmjs.org/compression
> 25 silly fetchNamedPackageData cors
> 26 silly mapToRegistry name cors
> 27 silly mapToRegistry using default registry
> 28 silly mapToRegistry registry https://registry.npmjs.org/
> 29 silly mapToRegistry data Result {
> 29 silly mapToRegistry   raw: 'cors',
> 29 silly mapToRegistry   scope: null,
> 29 silly mapToRegistry   name: 'cors',
> 29 silly mapToRegistry   rawSpec: '',
> 29 silly mapToRegistry   spec: 'latest',
> 29 silly mapToRegistry   type: 'tag' }
> 30 silly mapToRegistry uri https://registry.npmjs.org/cors
> 31 silly fetchNamedPackageData helmet
> 32 silly mapToRegistry name helmet
> 33 silly mapToRegistry using default registry
> 34 silly mapToRegistry registry https://registry.npmjs.org/
> 35 silly mapToRegistry data Result {
> 35 silly mapToRegistry   raw: 'helmet',
> 35 silly mapToRegistry   scope: null,
> 35 silly mapToRegistry   name: 'helmet',
> 35 silly mapToRegistry   rawSpec: '',
> 35 silly mapToRegistry   spec: 'latest',
> 35 silly mapToRegistry   type: 'tag' }
> 36 silly mapToRegistry uri https://registry.npmjs.org/helmet
> 37 silly fetchNamedPackageData loopback
> 38 silly mapToRegistry name loopback
> 39 silly mapToRegistry using default registry
> 40 silly mapToRegistry registry https://registry.npmjs.org/
> 41 silly mapToRegistry data Result {
> 41 silly mapToRegistry   raw: 'loopback',
> 41 silly mapToRegistry   scope: null,
> 41 silly mapToRegistry   name: 'loopback',
> 41 silly mapToRegistry   rawSpec: '',
> 41 silly mapToRegistry   spec: 'latest',
> 41 silly mapToRegistry   type: 'tag' }
> 42 silly mapToRegistry uri https://registry.npmjs.org/loopback
> 43 silly fetchNamedPackageData loopback-boot
> 44 silly mapToRegistry name loopback-boot
> 45 silly mapToRegistry using default registry
> 46 silly mapToRegistry registry https://registry.npmjs.org/
> .
> .
> .
> .
> 1046 verbose headers   'x-timer': 'S1465109178.756723,VS0,VE873',
> 1046 verbose headers   vary: 'Accept-Encoding' }
> 1047 silly get cb [ 304,
> 1047 silly get   { date: 'Sun, 05 Jun 2016 06:46:18 GMT',
> 1047 silly get     via: '1.1 varnish',
> 1047 silly get     'cache-control': 'max-age=300',
> 1047 silly get     etag: '"DS3L1XJ96HNS15OV9KVNSXJ"',
> 1047 silly get     age: '0',
> 1047 silly get     connection: 'keep-alive',
> 1047 silly get     'x-served-by': 'cache-sin6926-SIN',
> 1047 silly get     'x-cache': 'HIT',
> 1047 silly get     'x-cache-hits': '1',
> 1047 silly get     'x-timer': 'S1465109178.756723,VS0,VE873',
> 1047 silly get     vary: 'Accept-Encoding' } ]
> 1048 verbose etag https://registry.npmjs.org/dont-sniff-mimetype from cache
> 1049 verbose get saving dont-sniff-mimetype to C:\Users\neel\AppData\Roaming\npm-cache\registry.npmjs.org\dont-sniff-mimetype\.cache.json
> 1050 verbose correctMkdir C:\Users\neel\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
> 1051 silly resolveWithNewModule frameguard@1.1.0 checking installable status
> 1052 silly cache add args [ 'frameguard@1.1.0', null ]
> 1053 verbose cache add spec frameguard@1.1.0
> 1054 silly cache add parsed spec Result {
> 1054 silly cache add   raw: 'frameguard@1.1.0',
> 1054 silly cache add   scope: null,
> 1054 silly cache add   name: 'frameguard',
> 1054 silly cache add   rawSpec: '1.1.0',
> 1054 silly cache add   spec: '1.1.0',
> 1054 silly cache add   type: 'version' }
> 1055 silly addNamed frameguard@1.1.0
> 1056 verbose addNamed "1.1.0" is a plain semver version for frameguard
> 1057 silly mapToRegistry name frameguard
> 1058 silly mapToRegistry using default registry
> 1059 silly mapToRegistry registry https://registry.npmjs.org/
> 1060 silly mapToRegistry data Result {
> 1060 silly mapToRegistry   raw: 'frameguard',
> 1060 silly mapToRegistry   scope: null,
> 1060 silly mapToRegistry   name: 'frameguard',
> 1060 silly mapToRegistry   rawSpec: '',
> 1060 silly mapToRegistry   spec: 'latest',
> 1060 silly mapToRegistry   type: 'tag' }
> 1061 silly mapToRegistry uri https://registry.npmjs.org/frameguard
> 1062 verbose addNameVersion registry:https://registry.npmjs.org/frameguard not in flight; fetching
> 1063 silly cache afterAdd hide-powered-by@1.0.0
> 1064 verbose afterAdd C:\Users\neel\AppData\Roaming\npm-cache\hide-powered-by\1.0.0\package\package.json not in flight; writing
> 1065 verbose correctMkdir C:\Users\neel\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
> 1066 verbose get https://registry.npmjs.org/frameguard not expired, no request
> 1067 verbose afterAdd C:\Users\neel\AppData\Roaming\npm-cache\hide-powered-by\1.0.0\package\package.json written
> 1068 silly resolveWithNewModule dont-sniff-mimetype@1.0.0 checking installable status
> 1069 silly cache add args [ 'dont-sniff-mimetype@1.0.0', null ]
> 1070 verbose cache add spec dont-sniff-mimetype@1.0.0
> 1071 silly cache add parsed spec Result {
> 1071 silly cache add   raw: 'dont-sniff-mimetype@1.0.0',
> 1071 silly cache add   scope: null,
> 1071 silly cache add   name: 'dont-sniff-mimetype',
> 1071 silly cache add   rawSpec: '1.0.0',
> 1071 silly cache add   spec: '1.0.0',
> 1071 silly cache add   type: 'version' }
> 1072 silly addNamed dont-sniff-mimetype@1.0.0
> 1073 verbose addNamed "1.0.0" is a plain semver version for dont-sniff-mimetype
> 1074 silly mapToRegistry name dont-sniff-mimetype
> 1075 silly mapToRegistry using default registry
> 1076 silly mapToRegistry registry https://registry.npmjs.org/
> 1077 silly mapToRegistry data Result {
> 1077 silly mapToRegistry   raw: 'dont-sniff-mimetype',
> 1077 silly mapToRegistry   scope: null,
> 1077 silly mapToRegistry   name: 'dont-sniff-mimetype',
> 1077 silly mapToRegistry   rawSpec: '',
> 1077 silly mapToRegistry   spec: 'latest',
> 1077 silly mapToRegistry   type: 'tag' }
> 1078 silly mapToRegistry uri https://registry.npmjs.org/dont-sniff-mimetype
> 1079 verbose addNameVersion registry:https://registry.npmjs.org/dont-sniff-mimetype not in flight; fetching
> 1080 silly cache afterAdd frameguard@1.1.0
> 1081 verbose afterAdd C:\Users\neel\AppData\Roaming\npm-cache\frameguard\1.1.0\package\package.json not in flight; writing
> 1082 verbose correctMkdir C:\Users\neel\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
> 1083 verbose get https://registry.npmjs.org/dont-sniff-mimetype not expired, no request
> 1084 verbose afterAdd C:\Users\neel\AppData\Roaming\npm-cache\frameguard\1.1.0\package\package.json written
> 1085 silly cache afterAdd dont-sniff-mimetype@1.0.0
> 1086 verbose afterAdd C:\Users\neel\AppData\Roaming\npm-cache\dont-sniff-mimetype\1.0.0\package\package.json not in flight; writing
> 1087 verbose correctMkdir C:\Users\neel\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
> 1088 verbose afterAdd C:\Users\neel\AppData\Roaming\npm-cache\dont-sniff-mimetype\1.0.0\package\package.json written
> 1089 info attempt registry request try #2 at 12:16:28 PM
> 1090 http fetch GET https://registry.npmjs.org/nocache/-/nocache-1.0.0.tgz
> 1091 http fetch 503 https://registry.npmjs.org/nocache/-/nocache-1.0.0.tgz
> 1092 info retry will retry, error on last attempt: Error: server error 503
> 1093 info attempt registry request try #3 at 12:17:28 PM
> 1094 http fetch GET https://registry.npmjs.org/nocache/-/nocache-1.0.0.tgz
> 1095 http fetch 503 https://registry.npmjs.org/nocache/-/nocache-1.0.0.tgz
> 1096 error fetch failed https://registry.npmjs.org/nocache/-/nocache-1.0.0.tgz
> 1097 warn retry will retry, error on last attempt: Error: fetch failed with status code 503
> 1098 info retry fetch attempt 2 at 12:17:39 PM
> 1099 info attempt registry request try #1 at 12:17:39 PM
> 1100 http fetch GET https://registry.npmjs.org/nocache/-/nocache-1.0.0.tgz
> 1101 http fetch 503 https://registry.npmjs.org/nocache/-/nocache-1.0.0.tgz
> 1102 info retry will retry, error on last attempt: Error: server error 503
> 1103 info attempt registry request try #2 at 12:17:49 PM
> 1104 http fetch GET https://registry.npmjs.org/nocache/-/nocache-1.0.0.tgz
> 1105 http fetch 503 https://registry.npmjs.org/nocache/-/nocache-1.0.0.tgz
> 1106 info retry will retry, error on last attempt: Error: server error 503
> 1107 info attempt registry request try #3 at 12:18:49 PM
> 1108 http fetch GET https://registry.npmjs.org/nocache/-/nocache-1.0.0.tgz
> 1109 http fetch 503 https://registry.npmjs.org/nocache/-/nocache-1.0.0.tgz
> 1110 error fetch failed https://registry.npmjs.org/nocache/-/nocache-1.0.0.tgz
> 1111 warn retry will retry, error on last attempt: Error: fetch failed with status code 503
> 1112 info retry fetch attempt 3 at 12:19:49 PM
> 1113 info attempt registry request try #1 at 12:19:49 PM
> 1114 http fetch GET https://registry.npmjs.org/nocache/-/nocache-1.0.0.tgz
> 1115 http fetch 503 https://registry.npmjs.org/nocache/-/nocache-1.0.0.tgz
> 1116 info retry will retry, error on last attempt: Error: server error 503
> 1117 info attempt registry request try #2 at 12:19:59 PM
> 1118 http fetch GET https://registry.npmjs.org/nocache/-/nocache-1.0.0.tgz
> 1119 http fetch 503 https://registry.npmjs.org/nocache/-/nocache-1.0.0.tgz
> 1120 info retry will retry, error on last attempt: Error: server error 503
> 1121 info attempt registry request try #3 at 12:20:59 PM
> 1122 http fetch GET https://registry.npmjs.org/nocache/-/nocache-1.0.0.tgz
> 1123 http fetch 503 https://registry.npmjs.org/nocache/-/nocache-1.0.0.tgz
> 1124 error fetch failed https://registry.npmjs.org/nocache/-/nocache-1.0.0.tgz
> 1125 silly rollbackFailedOptional Starting
> 1126 silly rollbackFailedOptional Finishing
> 1127 silly runTopLevelLifecycles Starting
> 1128 silly runTopLevelLifecycles Finishing
> 1129 silly install printInstalled
> 1130 verbose stack Error: fetch failed with status code 503
> 1130 verbose stack     at Request.<anonymous> (C:\dev\softwares\nvm\v5.11.0\node_modules\npm\node_modules\npm-registry-client\lib\fetch.js:51:14)
> 1130 verbose stack     at emitOne (events.js:90:13)
> 1130 verbose stack     at Request.emit (events.js:182:7)
> 1130 verbose stack     at Request.onRequestResponse (C:\dev\softwares\nvm\v5.11.0\node_modules\npm\node_modules\request\request.js:952:10)
> 1130 verbose stack     at emitOne (events.js:90:13)
> 1130 verbose stack     at ClientRequest.emit (events.js:182:7)
> 1130 verbose stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:469:21)
> 1130 verbose stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:103:23)
> 1130 verbose stack     at TLSSocket.socketOnData (_http_client.js:359:20)
> 1130 verbose stack     at emitOne (events.js:90:13)
> 1130 verbose stack     at TLSSocket.emit (events.js:182:7)
> 1131 verbose cwd c:\dev\projects\test\loopback\givesomebody
> 1132 error Windows_NT 10.0.10586
> 1133 error argv "C:\\softwares\\nodejs\\node.exe" "C:\\softwares\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
> 1134 error node v5.11.0
> 1135 error npm  v3.8.6
> 1136 error fetch failed with status code 503
> 1137 error If you need help, you may report this error at:
> 1137 error     <https://github.com/npm/npm/issues>
> 1138 verbose exit [ 1, true ]
> 

And here's my package.json
```
{
  "name": "givesomebody",
  "version": "1.0.0",
  "main": "server/server.js",
  "scripts": {
    "start": "node .",
    "pretest": "eslint .",
    "posttest": "nsp check"
  },
  "dependencies": {
    "compression": "^1.0.3",
    "cors": "^2.5.2",
    "helmet": "^1.3.0",
    "loopback": "^2.22.0",
    "loopback-boot": "^2.6.5",
    "loopback-component-explorer": "^2.4.0",
    "loopback-datasource-juggler": "^2.39.0",
    "serve-favicon": "^2.0.1"
  },
  "devDependencies": {
    "eslint": "^2.5.3",
    "nsp": "^2.1.0"
  },
  "repository": {
    "type": "",
    "url": ""
  },
  "license": "UNLICENSED",
  "description": "givesomebody"
} 
```

Can someone please tell me what is wrong?

**Comment by indraneelr** [comment]
Marking this as a duplicate of #12960
