### ISSUE TITLE
error npm install --save botbuilder npm install --save restify

### ISSUE THREAD

**Issue by santoshm29** [npm/npm#13016]
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '--save',
1 verbose cli   'restify' ]
2 info using npm@2.15.1
3 info using node@v4.4.4
4 verbose install initial load of D:\santosh\practice\hellobot\package.json
5 verbose readDependencies loading dependencies from D:\santosh\practice\hellobot\package.json
6 silly cache add args [ 'restify', null ]
7 verbose cache add spec restify
8 silly cache add parsed spec Result {
8 silly cache add   raw: 'restify',
8 silly cache add   scope: null,
8 silly cache add   name: 'restify',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: 'latest',
8 silly cache add   type: 'tag' }
9 silly addNamed restify@latest
10 verbose addNamed "latest" is being treated as a dist-tag for restify
11 info addNameTag [ 'restify', 'latest' ]
12 silly mapToRegistry name restify
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry data Result {
15 silly mapToRegistry   raw: 'restify',
15 silly mapToRegistry   scope: null,
15 silly mapToRegistry   name: 'restify',
15 silly mapToRegistry   rawSpec: '',
15 silly mapToRegistry   spec: 'latest',
15 silly mapToRegistry   type: 'tag' }
16 silly mapToRegistry uri https://registry.npmjs.org/restify
17 verbose addNameTag registry:https://registry.npmjs.org/restify not in flight; fetching
18 verbose request uri https://registry.npmjs.org/restify
19 verbose request no auth needed
20 info attempt registry request try #1 at 4:30:23 PM
21 verbose request id 7aa850be0d396166
22 http request GET https://registry.npmjs.org/restify
23 info retry will retry, error on last attempt: Error: unable to get local issuer certificate
24 info attempt registry request try #2 at 4:30:33 PM
25 http request GET https://registry.npmjs.org/restify
26 info retry will retry, error on last attempt: Error: unable to get local issuer certificate
27 info attempt registry request try #3 at 4:31:34 PM
28 http request GET https://registry.npmjs.org/restify
29 verbose stack Error: unable to get local issuer certificate
29 verbose stack     at Error (native)
29 verbose stack     at TLSSocket.<anonymous> (_tls_wrap.js:1017:38)
29 verbose stack     at emitNone (events.js:67:13)
29 verbose stack     at TLSSocket.emit (events.js:166:7)
29 verbose stack     at TLSSocket._init.ssl.onclienthello.ssl.oncertcb.TLSSocket._finishInit (_tls_wrap.js:582:8)
29 verbose stack     at TLSWrap.ssl.onclienthello.ssl.oncertcb.ssl.onnewsession.ssl.onhandshakedone (_tls_wrap.js:424:38)
30 verbose cwd D:\santosh\practice\hellobot
31 error Windows_NT 6.3.9600
32 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "restify"
33 error node v4.4.4
34 error npm  v2.15.1
35 error code UNABLE_TO_GET_ISSUER_CERT_LOCALLY
36 error unable to get local issuer certificate
37 error If you need help, you may report this error at:
37 error     <https://github.com/npm/npm/issues>
38 verbose exit [ 1, true ]
```

**Comment by tk120404** [comment]
Try turning off ssl checking in your **.npmrc**

> strict-ssl=false

**Comment by KenanY** [comment]
@santoshm29 Are you still seeing this issue?

**Comment by KenanY** [comment]
Closing due to no response.

**Comment by skumar1708** [comment]
I am getting following error stack in cli, what should be the error?

pun-kumarsha-m:chatbot kumarsha$ npm install --save botbuilder
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "botbuilder"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! syscall connect

npm ERR! network connect ETIMEDOUT 100.77.0.231:80
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kumarsha/my_projects/chatbot/npm-debug.log
pun-kumarsha-m:chatbot kumarsha$ npm help config
