### ISSUE TITLE
Problem with installing and setting up bower and knockoutjs

### ISSUE THREAD

**Issue by raima-zachariah** [npm/npm#13032]
I'm not able to figure out what is going wrong with the installation. I am new to this.

here is my log file contents. 

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'bower' ]
2 info using npm@2.15.5
3 info using node@v4.4.5
4 verbose install initial load of C:\Users\rzachari\AppData\Roaming\npm\package.json
5 verbose readDependencies loading dependencies from C:\Users\rzachari\AppData\Roaming\npm\package.json
6 silly cache add args [ 'bower', null ]
7 verbose cache add spec bower
8 silly cache add parsed spec Result {
8 silly cache add   raw: 'bower',
8 silly cache add   scope: null,
8 silly cache add   name: 'bower',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: 'latest',
8 silly cache add   type: 'tag' }
9 silly addNamed bower@latest
10 verbose addNamed "latest" is being treated as a dist-tag for bower
11 info addNameTag [ 'bower', 'latest' ]
12 silly mapToRegistry name bower
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry data Result {
15 silly mapToRegistry   raw: 'bower',
15 silly mapToRegistry   scope: null,
15 silly mapToRegistry   name: 'bower',
15 silly mapToRegistry   rawSpec: '',
15 silly mapToRegistry   spec: 'latest',
15 silly mapToRegistry   type: 'tag' }
16 silly mapToRegistry uri https://registry.npmjs.org/bower
17 verbose addNameTag registry:https://registry.npmjs.org/bower not in flight; fetching
18 verbose request uri https://registry.npmjs.org/bower
19 verbose request no auth needed
20 info attempt registry request try #1 at 10:07:47 AM
21 verbose request id 1e7f0453e453de44
22 http request GET https://registry.npmjs.org/bower
23 info retry will retry, error on last attempt: Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
24 info attempt registry request try #2 at 10:07:57 AM
25 http request GET https://registry.npmjs.org/bower
26 info retry will retry, error on last attempt: Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
27 info attempt registry request try #3 at 10:08:57 AM
28 http request GET https://registry.npmjs.org/bower
29 verbose stack Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
29 verbose stack     at Error (native)
29 verbose stack     at Object.createSecureContext (_tls_common.js:87:19)
29 verbose stack     at Object.TLSSocket._init.ssl.onclienthello.ssl.oncertcb.exports.connect (_tls_wrap.js:972:23)
29 verbose stack     at Agent.createConnection (https.js:72:22)
29 verbose stack     at Agent.createSocket (_http_agent.js:175:16)
29 verbose stack     at Agent.addRequest (_http_agent.js:144:23)
29 verbose stack     at new ClientRequest (_http_client.js:142:16)
29 verbose stack     at Object.exports.request (http.js:31:10)
29 verbose stack     at Object.socket.once.exports.request (https.js:182:15)
29 verbose stack     at Request.start (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\request.js:753:32)
30 verbose cwd C:\Users\rzachari
31 error Windows_NT 6.1.7601
32 error argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "bower"
33 error node v4.4.5
34 error npm  v2.15.5
35 error error:0906D06C:PEM routines:PEM_read_bio:no start line
36 error If you need help, you may report this error at:
36 error     <https://github.com/npm/npm/issues>
37 verbose exit [ 1, true ]



```

**Comment by busches** [comment]
Are you behind a proxy? The stacktrace says it's unable to reach `https://registry.npmjs.org/bower` which means something is blocking, e.g. a proxy, or the website was down. If the problem is still occurring, it's likely a proxy.
