### ISSUE TITLE
npm run ios

### ISSUE THREAD

**Issue by kyangy** [npm/npm#13040]
`react-native run ios` command is giving this error.
```
/Users/appleuser/Desktop/asklegit-app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229
      throw err;
      ^

SyntaxError: /Users/appleuser/package.json: Error while parsing JSON - Unexpected end of input
    at Object.parse (native)
    at OptionManager.addConfig (/Users/appleuser/Desktop/asklegit-app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:225:62)
    at OptionManager.findConfigs (/Users/appleuser/Desktop/asklegit-app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:442:30)
    at OptionManager.init (/Users/appleuser/Desktop/asklegit-app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:484:12)
    at compile (/Users/appleuser/Desktop/asklegit-app/node_modules/babel-register/lib/node.js:112:69)
    at loader (/Users/appleuser/Desktop/asklegit-app/node_modules/babel-register/lib/node.js:158:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/appleuser/Desktop/asklegit-app/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)```

**Comment by EmmaRamirez** [comment]
You most likely have something wrong with your `package.json` file, try making sure that you don't have any missing brackets or stray/missing commas. Could you post your `package.json` file please?

**Comment by KenanY** [comment]
Closing since more information was never provided, and as such it is not possible to provide any sufficient support. Can reopen if it is still an issue.
