### ISSUE TITLE
After Trying Best I Cant Find a Solution Start Up My Private Server Plz HALP!

### ISSUE THREAD

**Issue by Zoinality** [npm/npm#13045]
module.js:442
    throw err;
    ^

Error: Cannot find module 'collections/sorted-map'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Alan\Desktop\Ogar-unlimited-master (5)\Ogar-unlimited-master\src\core\WorldModel.js:5:19)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)

Press any key to exit...

**Comment by KenanY** [comment]
@Zoinality Could you expand on how this is an issue with the `npm` CLI? Are you sure that you have installed the `collections` module?

**Comment by Zoinality** [comment]
Umm Idk Could You Show Me How To Install it ?

**Comment by KenanY** [comment]
@Zoinality `npm install collections`?

**Comment by KenanY** [comment]
@Zoinality Hello, it has been just over a week now with no reply from you. Are you still experiencing this issue?

**Comment by KenanY** [comment]
Closing as abandoned.

**Comment by Astro533** [comment]
Hello I'm having same problem can anyone help

**Comment by KenanY** [comment]
@Astro533 From your command line?
