### ISSUE TITLE
 v8-profiler@5.6.5~preinstall: Args: [ '-c', 'node -e \'process.exit(0)\'' ]

### ISSUE THREAD

**Issue by ghost** [npm/npm#13108]
```
137543 silly lifecycle node-pre-gyp@0.6.28~preinstall: no script for preinstall, continuing
137544 verbose lifecycle v8-profiler@5.6.5~preinstall: unsafe-perm in lifecycle true
137545 verbose lifecycle v8-profiler@5.6.5~preinstall: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/home/ec2-user/myApp/node_modules/.staging/v8-profiler-b334f5cf/node_modules/.bin:/home/ec2-user/myApp/node_modules/.bin:/usr/local/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/aws/bin:/home/ec2-user/.local/bin:/home/ec2-user/bin
137546 verbose lifecycle v8-profiler@5.6.5~preinstall: CWD: /home/ec2-user/myApp/node_modules/.staging/v8-profiler-b334f5cf
137547 silly lifecycle v8-profiler@5.6.5~preinstall: Args: [ '-c', 'node -e \'process.exit(0)\'' ]
137548 verbose stack Error: spawn ENOMEM
137548 verbose stack     at exports._errnoException (util.js:1007:11)
137548 verbose stack     at ChildProcess.spawn (internal/child_process.js:302:11)
137548 verbose stack     at exports.spawn (child_process.js:383:9)
137548 verbose stack     at spawn (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:7:13)
137548 verbose stack     at runCmd_ (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:237:14)
137548 verbose stack     at runCmd (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:196:5)
137548 verbose stack     at runPackageLifecycle (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:160:3)
137548 verbose stack     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
137548 verbose stack     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
137548 verbose stack     at chain (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
137549 verbose cwd /home/ec2-user/myApp
137550 error Linux 4.4.11-23.53.amzn1.x86_64
137551 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
137552 error node v6.2.1
137553 error npm  v3.9.3
137554 error code ENOMEM
137555 error errno ENOMEM
137556 error syscall spawn
137557 error spawn ENOMEM
137558 error If you need help, you may report this error at:
137558 error     <https://github.com/npm/npm/issues>
137559 verbose exit [ 1, true ]
[ec2-user@ip-172-31-19-54 myApp]$
```

**Comment by busches** [comment]
@pippintechnologies can you add more details on what steps are needed to reproduce this error?
