### ISSUE TITLE
npm update -g totally fails

### ISSUE THREAD

**Issue by ffxsam** [npm/npm#13115]
Version 3.10.1. npm-debug.log below.

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/samh/.nvm/versions/node/v6.2.0/bin/node',
1 verbose cli   '/Users/samh/.nvm/versions/node/v6.2.0/bin/npm',
1 verbose cli   'update',
1 verbose cli   '-g' ]
2 info using npm@3.10.1
3 info using node@v6.2.0
4 verbose stack Error: Missing required argument #1
4 verbose stack     at module.exports (/Users/samh/.nvm/versions/node/v6.2.0/lib/node_modules/npm/lib/install/mutate-into-logical-tree.js:30:3)
4 verbose stack     at /Users/samh/.nvm/versions/node/v6.2.0/lib/node_modules/npm/lib/outdated.js:79:5
4 verbose stack     at /Users/samh/.nvm/versions/node/v6.2.0/lib/node_modules/npm/lib/outdated.js:63:20
4 verbose stack     at thenHandleErrors (/Users/samh/.nvm/versions/node/v6.2.0/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:230:5)
4 verbose stack     at f (/Users/samh/.nvm/versions/node/v6.2.0/lib/node_modules/npm/node_modules/once/once.js:17:25)
4 verbose stack     at thenProcessChildren (/Users/samh/.nvm/versions/node/v6.2.0/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:191:20)
4 verbose stack     at f (/Users/samh/.nvm/versions/node/v6.2.0/lib/node_modules/npm/node_modules/once/once.js:17:25)
4 verbose stack     at thenSortChildren (/Users/samh/.nvm/versions/node/v6.2.0/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:162:5)
4 verbose stack     at handleComplete (/Users/samh/.nvm/versions/node/v6.2.0/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:20:14)
4 verbose stack     at /Users/samh/.nvm/versions/node/v6.2.0/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:154:22
5 verbose cwd /Users/samh
6 error Darwin 15.5.0
7 error argv "/Users/samh/.nvm/versions/node/v6.2.0/bin/node" "/Users/samh/.nvm/versions/node/v6.2.0/bin/npm" "update" "-g"
8 error node v6.2.0
9 error npm  v3.10.1
10 error code EMISSINGARG
11 error typeerror Error: Missing required argument #1
11 error typeerror     at module.exports (/Users/samh/.nvm/versions/node/v6.2.0/lib/node_modules/npm/lib/install/mutate-into-logical-tree.js:30:3)
11 error typeerror     at /Users/samh/.nvm/versions/node/v6.2.0/lib/node_modules/npm/lib/outdated.js:79:5
11 error typeerror     at /Users/samh/.nvm/versions/node/v6.2.0/lib/node_modules/npm/lib/outdated.js:63:20
11 error typeerror     at thenHandleErrors (/Users/samh/.nvm/versions/node/v6.2.0/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:230:5)
11 error typeerror     at f (/Users/samh/.nvm/versions/node/v6.2.0/lib/node_modules/npm/node_modules/once/once.js:17:25)
11 error typeerror     at thenProcessChildren (/Users/samh/.nvm/versions/node/v6.2.0/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:191:20)
11 error typeerror     at f (/Users/samh/.nvm/versions/node/v6.2.0/lib/node_modules/npm/node_modules/once/once.js:17:25)
11 error typeerror     at thenSortChildren (/Users/samh/.nvm/versions/node/v6.2.0/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:162:5)
11 error typeerror     at handleComplete (/Users/samh/.nvm/versions/node/v6.2.0/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:20:14)
11 error typeerror     at /Users/samh/.nvm/versions/node/v6.2.0/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:154:22
12 error typeerror This is an error with npm itself. Please report this error at:
12 error typeerror     <http://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]
```

**Comment by iarna** [comment]
This only happens when we can't read your global modules directory for some reason, but we definitely shouldn't be crashing before telling you exactly what was wrong. I'm probably going to bundle the fix for this into today's hotfix.

**Comment by iarna** [comment]
(I could have sworn we'd guarded against this ages ago but... apparently not.)

**Comment by ffxsam** [comment]
I can't replicate it anymore. Hmm.. I'd be ok with just dismissing this as a fluke.
