### ISSUE TITLE
Unable to install bunyan-syslog with latest version of nvm, Error log is below

### ISSUE THREAD

**Issue by bvenkatr** [npm/npm#13128]
I am getting below errors with node v6.2.2 and npm 3.9.6 when I do "npm install"(Installed using NVM)
My OS is OS X El Capitan

Then When I degrade to node: '5.5.0' npm: '3.3.12', "npm install" installs all libraries ;

May be I am thinking that there is a issue with latest npm or node, 

  CXX(target) Release/obj.target/syslog/src/syslog.o
In file included from ../src/syslog.cc:7:
../node_modules/nan/nan.h:602:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:608:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback) {
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:613:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:619:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback) {
      ~~~~~~~~~~~~~^
4 errors generated.
make: **\* [Release/obj.target/syslog/src/syslog.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/venkat/.nvm/versions/node/v6.2.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Darwin 15.5.0
gyp ERR! command "/Users/venkat/.nvm/versions/node/v6.2.2/bin/node" "/Users/venkat/.nvm/versions/node/v6.2.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/venkat/mainproject/sub-project/node_modules/bunyan-syslog
gyp ERR! node -v v6.2.2
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok

npm ERR! Darwin 15.5.0
npm ERR! argv "/Users/venkat/.nvm/versions/node/v6.2.2/bin/node" "/Users/venkat/.nvm/versions/node/v6.2.2/bin/npm" "install"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.6
npm ERR! code ELIFECYCLE

npm ERR! bunyan-syslog@0.3.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bunyan-syslog@0.3.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bunyan-syslog package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bunyan-syslog
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bunyan-syslog
npm ERR! There is likely additional logging output above.

**Comment by vitorscassiano** [comment]
I'm having the same problem!

**Comment by ruionwriting** [comment]
Same issue here on Ubuntu 14.04 LTS.

**Comment by andreas192** [comment]
why closing this issue? I have this error too on OS X. 

npm version 4.2.0
nvm version 0.33.2
node version 7.9.0
