### ISSUE TITLE
Error: module.js:340 throw err; ... not able to install anything on linux

### ISSUE THREAD

**Issue by jatinwaichal** [npm/npm#13136]
getting this error when checking npm version 
```
$ npm -v

module.js:340
throw err;
^
Error: Cannot find module 'inherits'
at Function.Module._resolveFilename (module.js:338:15)
at Function.Module._load (module.js:280:25)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object.<anonymous> (/usr/lib/node_modules/npmconf/npmconf.js:3:16)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
```

similar kind or error when trying to install angular-cli
```
module.js:340
throw err;
^
Error: Cannot find module 'inherits'
at Function.Module._resolveFilename (module.js:338:15)
at Function.Module._load (module.js:280:25)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object.<anonymous> (/usr/lib/node_modules/npmconf/npmconf.js:3:16)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
```

**Comment by jatinwaichal** [comment]
sorry it was our problem ... everything works fine
