### ISSUE TITLE
Can not run protractor because failed loading configuration file

### ISSUE THREAD

**Issue by hoannx** [npm/npm#13137]
I try to start protractor but there is an error and i don't know how to fix it. Please help me. Thanks

[09:52:12] Using gulpfile E:\Automation\Protractor\gulpfile.js
[09:52:12] Starting 'protractor'...
[09:52:13] E/configParser - error code: 105
[09:52:13] E/configParser - description: failed loading configuration file test/protractor.conf.js

E:\Automation\Protractor\node_modules\protractor\built\configParser.js:130
            throw new exitCodes_1.ConfigError(logger, 'failed loading configuration file ' + filename);
            ^
Error
    at ConfigError.ProtractorError (E:\Automation\Protractor\node_modules\protractor\built\exitCodes.js:10:22)
    at new ConfigError (E:\Automation\Protractor\node_modules\protractor\built\exitCodes.js:26:16)
    at ConfigParser.addFileConfig (E:\Automation\Protractor\node_modules\protractor\built\configParser.js:130:19)
    at Object.initFn [as init] (E:\Automation\Protractor\node_modules\protractor\built\launcher.js:94:22)
    at Object.<anonymous> (E:\Automation\Protractor\node_modules\protractor\built\cli.js:130:10)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
npm ERR! Test failed.  See above for more details.

**Comment by leonardoanalista** [comment]
I have the same issue. We are currently investigating if problem is on protractor or npm.

**Comment by krzysztofziomek** [comment]
+1

**Comment by dejewi** [comment]
+1

**Comment by hoannx** [comment]
Please help me if you find any solution. thanks

**Comment by leonardoanalista** [comment]
it seems like we have to wait for protractor to fix this for us:
https://github.com/angular/protractor/issues/3301

**Comment by leonardoanalista** [comment]
in your protractor.conf.js, replace:
  require('babel/register')
with:
  require('babel-core/register')

**Comment by NewWorldAnks** [comment]
Is there any solution for this? I am also facing same issue.

**Comment by KenanY** [comment]
I'm gonna close this as not an issue with `npm`.

**Comment by AnjumMomin** [comment]
i have same issue ......i don't know where the protractor.con.js file is saved...can any one know??
