### ISSUE TITLE
Issue Linux 4.1.18+

### ISSUE THREAD

**Issue by MelloXVI** [npm/npm#13177]
After this command : `npm run start`

```
npm ERR! Linux 4.1.18+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7

npm ERR! missing script: start
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/homebridge/npm-debug.log

```
Hello, I've this ussue. Have you got any idea about that ? 
In "npm-debug.log"
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'start' ]
2 info using npm@2.14.7
3 info using node@v4.2.1
4 verbose stack Error: missing script: start
4 verbose stack     at run (/usr/local/lib/node_modules/npm/lib/run-script.js:1$
4 verbose stack     at /usr/local/lib/node_modules/npm/lib/run-script.js:58:5
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-packag$
4 verbose stack     at handleExists (/usr/local/lib/node_modules/npm/node_modul$
4 verbose stack     at FSReqWrap.cb [as oncomplete] (fs.js:212:19)
5 verbose cwd /home/pi/homebridge
6 error Linux 4.1.18+
7 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
8 error node v4.2.1
9 error npm  v2.14.7
10 error missing script: start
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
@MelloXVI Do you have a `"start"` script defined in your `package.json`?

**Comment by KenanY** [comment]
Closing as abandoned.
