### ISSUE TITLE
[SOLVED!] Error: Cannot find module 'inherits' 

### ISSUE THREAD

**Issue by aboutsam** [npm/npm#13206]
hello guys, i get an error with my npm after i reinstall node.js with homebrew.. now i'm not able to uninstall or reinstall npm.. every commondo will output an "Error: Cannot find module 'inherits'"

i use node v5.7.0

for notice, i updated nodejs because npm was not installing gulp or gulp-sass

```
sam@Sams-MacBook ~/xxx/xxxxxx $ npm -v
module.js:341
    throw err;
    ^

Error: Cannot find module 'inherits'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_readable.js:41:17)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
```

**Comment by aboutsam** [comment]
Ok i found a solution on my own

```
sam@Sams-MacBook ~/xxx/xxxxxx $ **brew link node**
Error: Operation already in progress for node
Another active Homebrew process is already using node.
Please wait for it to finish or terminate it to continue.

sam@Sams-MacBook ~/xxx/xxxxxx $ **brew update**
==> Migrating Homebrew to v0.9.9
remote: Counting objects: 296, done.
remote: Compressing objects: 100% (238/238), done.
remote: Total 296 (delta 154), reused 138 (delta 44), pack-reused 0
Receiving objects: 100% (296/296), 460.59 KiB | 0 bytes/s, done.
Resolving deltas: 100% (154/154), completed with 152 local objects.
From https://github.com/Homebrew/brew
 + dde20cd...cab97cf master     -> origin/master  (forced update)
HEAD is now at cab97cf Revert "keg_relocate: Exclude hardlinks from mach_o_files."
==> Homebrew has enabled anonymous aggregate user behaviour analytics
Read the analytics documentation (and how to opt-out) here:
  https://git.io/brew-analytics
==> Txxxing homebrew/core
Cloning into '/usr/local/Library/Taps/homebrew/homebrew-core'...
remote: Counting objects: 3711, done.
remote: Compressing objects: 100% (3595/3595), done.
remote: Total 3711 (delta 14), reused 2204 (delta 6), pack-reused 0
Receiving objects: 100% (3711/3711), 2.87 MiB | 1.19 MiB/s, done.
Resolving deltas: 100% (14/14), done.
Checking connectivity... done.
Txxxed 3588 formulae (3,737 files, 8.9M)
==> Cleaning up /Library/Caches/Homebrew...
Removing: /Library/Caches/Homebrew/imagemagick-6.9.3-6.yosemite.bottle.tar.gz... (7M)
Removing: /Library/Caches/Homebrew/libpng-1.6.21.yosemite.bottle.tar.gz... (426.5K)
Removing: /Library/Caches/Homebrew/libtiff-4.0.6.yosemite.bottle.tar.gz... (1M)
Removing: /Library/Caches/Homebrew/mysql-5.7.11.yosemite.bottle.tar.gz... (92.1M)
Removing: /Library/Caches/Homebrew/node-5.9.0.tar.xz... (12.6M)
Removing: /Library/Caches/Homebrew/node-5.9.0.yosemite.bottle.tar.gz... (10.0M)
Removing: /Library/Caches/Homebrew/unixodbc-2.3.2_1.yosemite.bottle.1.tar.gz... (321.7K)
==> Migrating /Library/Caches/Homebrew to /Users/sam/Library/Caches/Homebrew...
==> Deleting /Library/Caches/Homebrew...
Already up-to-date.

Warning: The post-install step did not complete successfully
You can try again using `brew postinstall node`
==> Caveats
Please note by default only English locale support is provided. If you need
full locale support you should either rebuild with full icu:
  `brew reinstall node --with-full-icu`
or add full icu data at runtime following:
  https://github.com/nodejs/node/wiki/Intl#using-and-customizing-the-small-icu-build


sam@Sams-MacBook ~/xxx/xxxxxx $ **sudo chown -R $USER /usr/local**
sam@Sams-MacBook ~/xxx/xxxxxx $ **brew link --overwrite node**

sam@Sams-MacBook ~/xxx/xxxxxx $ **brew install node**
Warning: node-6.2.2 already installed

sam@Sams-MacBook ~/xxx/xxxxxx $ **which npm**
/usr/local/bin/npm

sam@Sams-MacBook ~/xxx/xxxxxx $ **brew postinstall node**
sam@Sams-MacBook ~/xxx/xxxxxx $ **npm -v**
3.9.5
```

I try to reinstall node with brew again and get the message my node was ot linked.. so i try to solve this problem.

**Comment by othiym23** [comment]
Closing as resolved.
