### ISSUE TITLE
Error E400 when trying to unpublish package

### ISSUE THREAD

**Issue by mizmaar3** [npm/npm#13205]
Im trying to unpublish a package I publish recently (because of change of name) but getting errors in terminal code E400 even with --force

Package: https://www.npmjs.com/package/gulp-es6-browserfy-boilerplate

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'unpublish',
1 verbose cli   '--force' ]
2 info using npm@3.9.5
3 info using node@v6.2.2
4 warn using --force I sure hope you know what you are doing.
5 silly unpublish args[0] undefined
6 silly unpublish thing {}
7 verbose unpublish { name: 'gulp-es6-browserfy-boilerplate',
7 verbose unpublish   version: '1.0.0',
7 verbose unpublish   description: 'Boilerplate to start with simple JS project with automation',
7 verbose unpublish   main: 'main.js',
7 verbose unpublish   author:
7 verbose unpublish    { name: 'Usman',
7 verbose unpublish      email: 'mizmaar3@hotmail.com',
7 verbose unpublish      url: 'https://github.com/mizmaar3' },
7 verbose unpublish   scripts:
7 verbose unpublish    { build: 'gulp build',
7 verbose unpublish      'build:dev': 'gulp build --isdev',
7 verbose unpublish      start: 'http-server ./ -p 9300 --cors' },
7 verbose unpublish   devDependencies:
7 verbose unpublish    { 'babel-preset-es2016': '^6.0.11',
7 verbose unpublish      'browser-sync': '^2.12.12',
7 verbose unpublish      browserify: '^13.0.1',
7 verbose unpublish      gulp: '^3.9.1',
7 verbose unpublish      'gulp-babel': '^6.1.2',
7 verbose unpublish      'gulp-concat': '^2.6.0',
7 verbose unpublish      'gulp-if': '^2.0.1',
7 verbose unpublish      'gulp-less': '^3.1.0',
7 verbose unpublish      'gulp-sourcemaps': '^1.6.0',
7 verbose unpublish      'gulp-uglify': '^1.5.3',
7 verbose unpublish      'http-server': '^0.9.0',
7 verbose unpublish      mimer: '^0.2.1',
7 verbose unpublish      'simple-mime': '^0.1.0',
7 verbose unpublish      'vinyl-buffer': '^1.0.0',
7 verbose unpublish      'vinyl-source-stream': '^1.1.0',
7 verbose unpublish      yargs: '^4.7.1' },
7 verbose unpublish   keywords:
7 verbose unpublish    [ 'gulp',
7 verbose unpublish      'boilerplate',
7 verbose unpublish      'ES6',
7 verbose unpublish      'ES2016',
7 verbose unpublish      'babel',
7 verbose unpublish      'Automation',
7 verbose unpublish      'Browserify' ],
7 verbose unpublish   repository:
7 verbose unpublish    { type: 'git',
7 verbose unpublish      url: 'git+https://github.com/mizmaar3/gulp-es6-browserify-boilerplate.git' },
7 verbose unpublish   readme: '# gulp-es6-browserify-boilerplate\n\n> Project tested with node v 6.2.2\n\nA very basic boilerplate to start your Javascript project with [ES6](https://babeljs.io/docs/learn-es2015/) script and using [Browserify](http://browserify.org/) module bundler and [Less](http://lesscss.org/) css preprocessor.\n\n> Browserify lets you require(\'modules\') in the browser by bundling up all of your dependencies.\n\n- The aim of this package is to start basic web project which usually have JS and css (less css) files, build them for release by compiling ES2015 code and concatenate multiple js and npm bundles into single file using `Browserify` and do the same for css style sheets.\n\n- Bundling done with simple commands using [Gulp](http://gulpjs.com/) which is famous build system to automate build process.\n\n\n## Install\n\nFirst, clone the repo via git:\n\n```bash\ngit clone https://github.com/mizmaar3/gulp-es6-browserify-boilerplate your-project-name\n```\n\nAnd then install dependencies.\n\n```bash\n$ cd your-project-name && npm install\n```\n\n\n## Build\n\nRun this command to build and bundle the project.\n\n```bash\n$ npm run build\n```\n\nor simple run\n\n```bash\n$ gulp\n```\n\nTo enable source mapping please run\n\n```bash\n$ npm run build:dev\n```\n\n\ninside your project folder\n\n\n## Start Server\n\nTo start local server please run\n\n```bash\n$ npm run start\n```\n\nand goto http://127.0.0.1:9300 to test if code worked. You should get some text on the page.\n\n\n## DevTools\n\n#### Toggle Chrome DevTools\n\n- OS X: <kbd>Cmd</kbd> <kbd>Alt</kbd> <kbd>I</kbd> or <kbd>F12</kbd>\n- Linux: <kbd>Ctrl</kbd> <kbd>Shift</kbd> <kbd>I</kbd> or <kbd>F12</kbd>\n- Windows: <kbd>Ctrl</kbd> <kbd>Shift</kbd> <kbd>I</kbd> or <kbd>F12</kbd>\n\n\n## Example Code Explanation\n\n#### The JS folder\n\n- So JS folder have three utility files and one main.js file which using utilities and showing some results in browser console. `Browserify` will do the magic for bundling. Everything which `Require` in main.js or in util files will be appended into bundle.js after building the project. `array-union.js` using `underscore.js` to union some sets while `get-mime-type.js` using npm package called `simple-mime` to get mimetype of a file. As utilities files have ES6 code it will be compiled by `babel js` after that `Browserify` will append all dependencied into single `bundle.js` file... Yes even whole `underscore.js` can be found in `bundle.js` and of course whole `simple-mime` package and its dependencies as well.\n\n\n#### The LESS folder\n\n- Less folder contains `.less` files which will be compiled with `gulp-less` and concatenated into single file `style.css`, can be found in `dist` folder after building project.\n',
7 verbose unpublish   readmeFilename: 'readme.md',
7 verbose unpublish   gitHead: 'f32c132b77fb99e25291a2e22b4c22e7b34c11a0',
7 verbose unpublish   bugs: { url: 'https://github.com/mizmaar3/gulp-es6-browserify-boilerplate/issues' },
7 verbose unpublish   homepage: 'https://github.com/mizmaar3/gulp-es6-browserify-boilerplate#readme',
7 verbose unpublish   _id: 'gulp-es6-browserfy-boilerplate@1.0.0' }
8 verbose getPublishConfig undefined
9 silly ls normalized gulp-es6-browserfy-boilerplate/1.0.0
10 silly gentlyRm /Users/Usman/.npm/gulp-es6-browserfy-boilerplate/1.0.0 is being purged
11 verbose gentlyRm don't care about contents; nuking /Users/Usman/.npm/gulp-es6-browserfy-boilerplate/1.0.0
12 silly mapToRegistry name gulp-es6-browserfy-boilerplate
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry data Result {
15 silly mapToRegistry   raw: 'gulp-es6-browserfy-boilerplate',
15 silly mapToRegistry   scope: null,
15 silly mapToRegistry   name: 'gulp-es6-browserfy-boilerplate',
15 silly mapToRegistry   rawSpec: '',
15 silly mapToRegistry   spec: 'latest',
15 silly mapToRegistry   type: 'tag' }
16 silly mapToRegistry uri https://registry.npmjs.org/gulp-es6-browserfy-boilerplate
17 verbose get GET as part of write; not caching result
18 verbose request uri https://registry.npmjs.org/gulp-es6-browserfy-boilerplate?write=true
19 verbose request no auth needed
20 info attempt registry request try #1 at 3:03:02 PM
21 verbose request using bearer token for auth
22 verbose request id e65a2bb82853e850
23 http request GET https://registry.npmjs.org/gulp-es6-browserfy-boilerplate?write=true
24 http 200 https://registry.npmjs.org/gulp-es6-browserfy-boilerplate?write=true
25 verbose headers { server: 'CouchDB/1.6.1 (Erlang OTP/R16B03)',
25 verbose headers   etag: '"9F5JNBQSW1K9OI0ONEFGZCX0M"',
25 verbose headers   'content-type': 'application/json',
25 verbose headers   'content-encoding': 'gzip',
25 verbose headers   'cache-control': 'max-age=0',
25 verbose headers   'transfer-encoding': 'chunked',
25 verbose headers   'accept-ranges': 'bytes',
25 verbose headers   date: 'Tue, 28 Jun 2016 13:03:03 GMT',
25 verbose headers   via: '1.1 varnish',
25 verbose headers   connection: 'keep-alive',
25 verbose headers   'x-served-by': 'cache-ams4124-AMS',
25 verbose headers   'x-cache': 'MISS',
25 verbose headers   'x-cache-hits': '0',
25 verbose headers   'x-timer': 'S1467118982.658548,VS0,VE516',
25 verbose headers   vary: 'Accept-Encoding' }
26 silly get cb [ 200,
26 silly get   { server: 'CouchDB/1.6.1 (Erlang OTP/R16B03)',
26 silly get     etag: '"9F5JNBQSW1K9OI0ONEFGZCX0M"',
26 silly get     'content-type': 'application/json',
26 silly get     'content-encoding': 'gzip',
26 silly get     'cache-control': 'max-age=0',
26 silly get     'transfer-encoding': 'chunked',
26 silly get     'accept-ranges': 'bytes',
26 silly get     date: 'Tue, 28 Jun 2016 13:03:03 GMT',
26 silly get     via: '1.1 varnish',
26 silly get     connection: 'keep-alive',
26 silly get     'x-served-by': 'cache-ams4124-AMS',
26 silly get     'x-cache': 'MISS',
26 silly get     'x-cache-hits': '0',
26 silly get     'x-timer': 'S1467118982.658548,VS0,VE516',
26 silly get     vary: 'Accept-Encoding' } ]
27 verbose get saving gulp-es6-browserfy-boilerplate to /Users/Usman/.npm/registry.npmjs.org/gulp-es6-browserfy-boilerplate_3Fwrite_3Dtrue/.cache.json
28 verbose correctMkdir /Users/Usman/.npm correctMkdir not in flight; initializing
29 verbose unpublish removing attachments { shasum: 'fa2a191e66adf6e711d7472ee8c5bc2e16669b6d',
29 verbose unpublish   tarball: 'http://registry.npmjs.org/gulp-es6-browserfy-boilerplate/-/gulp-es6-browserfy-boilerplate-1.0.0.tgz' }
30 info unpublish No versions remain, removing entire package
31 verbose request uri https://registry.npmjs.org/gulp-es6-browserfy-boilerplate/-rev/4-2f2aff1c013761fb302821f6e21a586a
32 verbose request sending authorization for write operation
33 info attempt registry request try #1 at 3:03:03 PM
34 verbose request using bearer token for auth
35 http request DELETE https://registry.npmjs.org/gulp-es6-browserfy-boilerplate/-rev/4-2f2aff1c013761fb302821f6e21a586a
36 http 400 https://registry.npmjs.org/gulp-es6-browserfy-boilerplate/-rev/4-2f2aff1c013761fb302821f6e21a586a
37 verbose headers { 'content-type': 'application/json',
37 verbose headers   'cache-control': 'max-age=300',
37 verbose headers   'content-length': '17',
37 verbose headers   'accept-ranges': 'bytes',
37 verbose headers   date: 'Tue, 28 Jun 2016 13:03:04 GMT',
37 verbose headers   via: '1.1 varnish',
37 verbose headers   connection: 'keep-alive',
37 verbose headers   'x-served-by': 'cache-ams4124-AMS',
37 verbose headers   'x-cache': 'MISS',
37 verbose headers   'x-cache-hits': '0',
37 verbose headers   'x-timer': 'S1467118983.234155,VS0,VE1041',
37 verbose headers   vary: 'Accept-Encoding' }
38 verbose request invalidating /Users/Usman/.npm/registry.npmjs.org/gulp-es6-browserfy-boilerplate on DELETE
39 verbose stack Error: Registry returned 400 for DELETE on https://registry.npmjs.org/gulp-es6-browserfy-boilerplate/-rev/4-2f2aff1c013761fb302821f6e21a586a
39 verbose stack     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
39 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:242:14)
39 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
39 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:200:22)
39 verbose stack     at emitTwo (events.js:106:13)
39 verbose stack     at Request.emit (events.js:191:7)
39 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1067:10)
39 verbose stack     at emitOne (events.js:101:20)
39 verbose stack     at Request.emit (events.js:188:7)
39 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:988:12)
40 verbose statusCode 400
41 verbose pkgid gulp-es6-browserfy-boilerplate
42 verbose cwd /Users/Usman/pro/gulp-es6-browserify-boilerplate
43 error Darwin 15.5.0
44 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "unpublish" "--force"
45 error node v6.2.2
46 error npm  v3.9.5
47 error code E400
48 error Registry returned 400 for DELETE on https://registry.npmjs.org/gulp-es6-browserfy-boilerplate/-rev/4-2f2aff1c013761fb302821f6e21a586a
49 error If you need help, you may report this error at:
49 error     <https://github.com/npm/npm/issues>
50 verbose exit [ 1, true ]
```

**Comment by othiym23** [comment]
A few months ago, npm [made some changes](http://blog.npmjs.org/post/141905368000/changes-to-npms-unpublish-policy) to our policy regarding package unpublishes. You'll need to contact <support@npmjs.com> in order to get this package unpublished. You can probably just forward along a link to this issue. Since this is something handled by the support engineers and not the CLI team, I'm going to close this issue. Thanks for your time!
