### ISSUE TITLE
I cannot install menuitem using npm, git (error setting certificate verify locations)

### ISSUE THREAD

**Issue by oxidian24** [npm/npm#13226]
I am using tutorial "Using third-party modules"

npm install menuitem --save
npm WARN package.json test@0.0.1 No repository field.
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:213:12)
npm WARN addRemoteGit     at emitTwo (events.js:87:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:172:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:827:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child
_process.js:211:5)
npm WARN addRemoteGit  git+https://github.com/OverByThere/addon-pathfinder.git resetting remote C:\Documents and Settings\Administrator\Data aplikací\npm-cache\
_git-remotes\https-github-com-OverByThere-addon-pathfinder-git-93454c54 because of error: { [Error: **Command failed: git -c core.longpaths=true config --get remote.origin.url**

Where is the problem? What is remote.origin.url? Such site does not exist.

Also I read:

89 verbose stack fatal: unable to access 'https://github.com/OverByThere/addon-pathfinder.git/': **error setting certificate verify locations**:

https://github.com/OverByThere/addon-pathfinder
why we just cannot get the packs manually?

Also are you sure it is ok to use path without qoetes? Target path includes spaces and European chars

89 verbose stack **Error: Command failed: git -c** core.longpaths=true clone --template=C:\Documents and Settings\Administrator\Data aplikací\npm-cache\_git-remotes\_templates ....

Edit: Why nobody solves the **npm install** error using git, I found at least 5 similar  issues, months old, from other users. Please remove the bugs.

**Comment by oxidian24** [comment]
Issue solved.

One of the errors I got is this one:
npm ERR! git clone --template=C:\Documents and Settings\Administrator\Data aplik
ací\npm-cache\_git-remotes\_templates --mirror https://github.com/OverByThere/ad
don-pathfinder.git C:\Documents and Settings\Administrator\Data aplikací\npm-cac
he\_git-remotes\https-github-com-OverByThere-addon-pathfinder-git-93454c54: fata
l: unable to access 'https://github.com/OverByThere/addon-pathfinder.git/': erro
r setting certificate verify locations:
npm ERR! git clone --template=C:\Documents and Settings\Administrator\Data aplik
ací\npm-cache\_git-remotes\_templates --mirror https://github.com/OverByThere/ad
don-pathfinder.git C:\Documents and Settings\Administrator\Data aplikací\npm-cac
he\_git-remotes\https-github-com-OverByThere-addon-pathfinder-git-93454c54:   CA
file: P:/INTERNET/download/Git/mingw32/libexec/**ssl/certs/ca-bundle.crt**
npm ERR! git clone --template=C:\Documents and Settings\Administrator\Data aplik
ací\npm-cache\_git-remotes\_templates --mirror https://github.com/OverByThere/ad
don-pathfinder.git C:\Documents and Settings\Administrator\Data aplikací\npm-cac
he\_git-remotes\https-github-com-OverByThere-addon-pathfinder-git-93454c54:   CA
path: none

I carefully checked the path which uses git directory. It uses ssl directory under **mingw32/libexec** which is wrong path! No such path when I installed latest git (2.9.0). The ssl is located under
**mingw32**
not
**libexec**

To solve the problem I have just copied the folder under the location where npm expects the path.
