### ISSUE TITLE
npm install fails right at the start. 

### ISSUE THREAD

**Issue by frontalicious-martijn** [npm/npm#13238]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I try to 'npm install' a project and get the error stack below. Also 'npm install -g npm' does not work.

#### How can the CLI team reproduce the problem?

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'install' ]
2 info using npm@3.3.6
3 info using node@v5.0.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly install normalizeTree
8 verbose stack Error: Argument #1: Expected string but got object
8 verbose stack     at markDeps (/usr/local/lib/node_modules/npm/lib/install/deps.js:87:5)
8 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
8 verbose stack     at Array.forEach (native)
8 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
8 verbose stack     at Array.forEach (native)
8 verbose stack     at asyncMap (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
8 verbose stack     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
8 verbose stack     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
8 verbose stack     at chain (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
8 verbose stack     at recalculateMetadata (/usr/local/lib/node_modules/npm/lib/install/deps.js:112:3)
9 verbose cwd /Users/Martijn/stack/Projects/sandbox/react-redux-starter-kit
10 error Darwin 15.4.0
11 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
12 error node v5.0.0
13 error npm  v3.3.6
14 error code EINVALIDTYPE
15 error typeerror Error: Argument #1: Expected string but got object
15 error typeerror     at markDeps (/usr/local/lib/node_modules/npm/lib/install/deps.js:87:5)
15 error typeerror     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
15 error typeerror     at Array.forEach (native)
15 error typeerror     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
15 error typeerror     at Array.forEach (native)
15 error typeerror     at asyncMap (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
15 error typeerror     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
15 error typeerror     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
15 error typeerror     at chain (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
15 error typeerror     at recalculateMetadata (/usr/local/lib/node_modules/npm/lib/install/deps.js:112:3)
15 error typeerror This is an error with npm itself. Please report this error at:
15 error typeerror     <http://github.com/npm/npm/issues>
16 verbose exit [ 1, true ]

### supporting information:

 - `npm -v` prints: 3.3.6
 - `node -v` prints: v5.0.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X, or Linux?: OS X
 - Network issues:
   - Geographic location where npm was run: Amsterdam, The Netherlands
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

I've switched some node version but still same error.

**Comment by frontalicious-martijn** [comment]
Never mind, I tried curl -L https://www.npmjs.org/install.sh | sh and now it looks like it is working again.
