### ISSUE TITLE
Npm Error: Unexpected EOF even after clean re-install

### ISSUE THREAD

**Issue by xurnix** [npm/npm#13235]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I got "Unexpected eof" error whenever installing from npm.

`86669 verbose fstream_class Extract
86670 verbose stack Error: unexpected eof
86670 verbose stack     at decorate (C:\Users\Gogon\AppData\Roaming\npm\node_modules\npm\node_modules\fstream\lib\abstract.js:67:36)
86670 verbose stack     at Extract.Abstract.error (C:\Users\Gogon\AppData\Roaming\npm\node_modules\npm\node_modules\fstream\lib\abstract.js:61:12)
86670 verbose stack     at Extract._streamEnd (C:\Users\Gogon\AppData\Roaming\npm\node_modules\npm\node_modules\tar\lib\extract.js:91:35)
86670 verbose stack     at BlockStream.<anonymous> (C:\Users\Gogon\AppData\Roaming\npm\node_modules\npm\node_modules\tar\lib\parse.js:51:8)
86670 verbose stack     at emitNone (events.js:67:13)
86670 verbose stack     at BlockStream.emit (events.js:166:7)
86670 verbose stack     at BlockStream._emitChunk (C:\Users\Gogon\AppData\Roaming\npm\node_modules\npm\node_modules\tar\node_modules\block-stream\block-stream.js:203:10)
86670 verbose stack     at BlockStream.resume (C:\Users\Gogon\AppData\Roaming\npm\node_modules\npm\node_modules\tar\node_modules\block-stream\block-stream.js:58:15)
86670 verbose stack     at Extract.Reader.resume (C:\Users\Gogon\AppData\Roaming\npm\node_modules\npm\node_modules\fstream\lib\reader.js:249:34)
86670 verbose stack     at Entry.<anonymous> (C:\Users\Gogon\AppData\Roaming\npm\node_modules\npm\node_modules\tar\lib\parse.js:261:8)
86671 verbose fstream_stack Extract._streamEnd (C:\Users\Gogon\AppData\Roaming\npm\node_modules\npm\node_modules\tar\lib\extract.js:91:35)
86671 verbose fstream_stack BlockStream.<anonymous> (C:\Users\Gogon\AppData\Roaming\npm\node_modules\npm\node_modules\tar\lib\parse.js:51:8)
86671 verbose fstream_stack emitNone (events.js:67:13)
86671 verbose fstream_stack BlockStream.emit (events.js:166:7)
86671 verbose fstream_stack BlockStream._emitChunk (C:\Users\Gogon\AppData\Roaming\npm\node_modules\npm\node_modules\tar\node_modules\block-stream\block-stream.js:203:10)
86671 verbose fstream_stack BlockStream.resume (C:\Users\Gogon\AppData\Roaming\npm\node_modules\npm\node_modules\tar\node_modules\block-stream\block-stream.js:58:15)
86671 verbose fstream_stack Extract.Reader.resume (C:\Users\Gogon\AppData\Roaming\npm\node_modules\npm\node_modules\fstream\lib\reader.js:249:34)
86671 verbose fstream_stack Entry.<anonymous> (C:\Users\Gogon\AppData\Roaming\npm\node_modules\npm\node_modules\tar\lib\parse.js:261:8)
86672 verbose cwd C:\WINDOWS\system32
86673 error Windows_NT 6.3.9600
86674 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Gogon\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "angular-cli"
86675 error node v4.4.6
86676 error npm  v3.10.2
86677 error unexpected eof
`

I'm trying to install angular-cli

Solution I've tried:
- npm cache clean
- npm uninstall -g angular-cli
- run command in administrator
- delete %NPMPATH%/node_modules
- update npm & node.js
- clean re-install node.js
- some other solution that I forgot

when trying above solution, npm give different error
sometimes its error: z_buff_...something
or unpack tar error
or else

(sorry no log for other error, since I've done a clean re-install.

any suggestion?
thanks

### supporting information:

 - `npm -v` prints: 3.10.2
 - `node -v` prints: 4.4.6
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X, or Linux?: Win 8
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by xurnix** [comment]
after `npm uninstall -g angular-cli`
and 'npm cache clean`

now angular-cli successfully installed,

it fail before. maybe it work after clean re-install node.js
