### ISSUE TITLE
npm install -g cordova is not working

### ISSUE THREAD

**Issue by sharoni3d** [npm/npm#13262]
#### I'm opening this issue because:

because i'm having problems running this code 
npm install -g cordova

#### What's going wrong?

i get this error 
Error: EPERM, Operation not permitted
    at /usr/local/lib/node_modules/npm/node_modules/uid-number/uid-number.js:49:16
    at ChildProcess.exithandler (child_process.js:198:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12)

#### How can the CLI team reproduce the problem?

Mayas-iMac:~ maya$ node -v
v6.2.2
Mayas-iMac:~ maya$ npm -v
3.9.5

and i think it related to my minimatch doesn't want to update

### supporting information:

 i have a mac 

#### Is this a feature you're prepared to implement, with support from the npm CLI team?

-->

**Comment by KenanY** [comment]
@sharoni3d Have you tried prepending your command with `sudo`?

**Comment by sharoni3d** [comment]
i did all the command with sudo and i keep getting permission issues

**Comment by KenanY** [comment]
@sharoni3d Could you upload the resulting `npm-debug.log` file to https://gist.github.com/ and post the link to it here?

**Comment by sharoni3d** [comment]
i'm sure how to get that log iv done complete uninstall of node and new installs but when i run the cordova command i get this error

npm install -g ionic@beta
Error: EPERM, Operation not permitted
    at /usr/local/lib/node_modules/npm/node_modules/uid-number/uid-number.js:49:16
    at ChildProcess.exithandler (child_process.js:198:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12)

**Comment by KenanY** [comment]
@sharoni3d That's with `sudo`? The `npm-debug.log` file should be created in whatever directory you are in when you run an `npm` command.

**Comment by sharoni3d** [comment]
I found the solution but i can't find the link it was from john papa

**Comment by KenanY** [comment]
Closing as resolved then.
