### ISSUE TITLE
Cannot find module 'lodash.repeat'

### ISSUE THREAD

**Issue by hitkiller** [npm/npm#13270]
#### I'm opening this issue because:

  - [ ] npm is crashing.

#### What's going wrong?

I get ==verbose stack Error: Cannot find module 'lodash.repeat'== for any requests

#### How can the CLI team reproduce the problem?

For example I'm trying to list global packages. npm ls -g
Here's the log:

verbose cli   'ls',
verbose cli   '-g' ]
info using npm@3.5.3
info using node@v6.2.2
verbose stack Error: Cannot find module 'lodash.repeat'
verbose stack     at Function.Module._resolveFilename (module.js:440:15)
verbose stack     at Function.Module._load (module.js:388:25)
verbose stack     at Module.require (module.js:468:17)
verbose stack     at require (internal/module.js:20:19)
verbose stack     at Object.<anonymous> (C:\Users\...\AppData\Roaming\npm\node_modules\npm\node_modules\npm-install-checks\node_modules\npmlog\node_modules\gauge\node_modules\lodash.pad\node_modules\lodash._createpadding\index.js:9:14)
verbose stack     at Module._compile (module.js:541:32)
verbose stack     at Object.Module._extensions..js (module.js:550:10)
verbose stack     at Module.load (module.js:458:32)
verbose stack     at tryModuleLoad (module.js:417:12)
verbose stack     at Function.Module._load (module.js:409:3)
verbose cwd C:\Users\.....
error Windows_NT 6.1.7601
error argv "C:\\Program Files (x86)\\node\\node.exe" "C:\\Users\\....\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "ls" "-g"
8 error node v6.2.2
9 error npm  v3.5.3
10 error code MODULE_NOT_FOUND
11 error Cannot find module 'lodash.repeat'

### supporting information:

 - `npm -v` prints: v6.2.2 (any other earlier version gives the same result)
 - `node -v` prints:  v3.5.3
I work on windows

**Comment by hitkiller** [comment]
++++
After detailed investigation I found out the cause of conflict: the older files located at C:\Users...\AppData\Roaming\npm require the dependencies not present in the newer node/npm versions. So upgrading your Node consider deleting them completely.
