### ISSUE TITLE
npm install error EventEmitter memory leak detected

### ISSUE THREAD

**Issue by wenpos** [npm/npm#13309]
### supporting information:

 - `npm -v` prints: 1.3.8
 - `node -v` prints: v0.11.6
 - `npm config get registry` prints:
 - Linux:
#### I'm opening this issue because:
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
when I input the command 'npm install' under a kibana source project, the output are as follows.
It always warns that  ‘(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.’, and at last the error occurs for 'npm ERR! Error: Exceeded maxRedirects. Probably stuck in a redirect loop'.
#### How can the CLI team reproduce the problem?
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Request.EventEmitter.addListener (events.js:175:15)
    at Request.start (/opt/node-v0.11.6-linux-x86/lib/node_modules/npm/node_modules/request/index.js:632:8)
    at Request.end (/opt/node-v0.11.6-linux-x86/lib/node_modules/npm/node_modules/request/index.js:1211:28)
    at /opt/node-v0.11.6-linux-x86/lib/node_modules/npm/node_modules/request/index.js:436:12
    at process._tickCallback (node.js:361:11)
npm http GET http://registry.npmjs.org/spalger/test-subj-selector/0.2.1
npm http GET http://registry.npmjs.org/spalger/leaflet-draw/0.2.3
npm ERR! Error: Exceeded maxRedirects. Probably stuck in a redirect loop 
npm ERR!     at Request.onResponse (/opt/node-v0.11.6-linux-x86/lib/node_modules/npm/node_modules/request/index.js:770:26)
npm ERR!     at ClientRequest.g (events.js:190:14)
npm ERR!     at ClientRequest.EventEmitter.emit (events.js:103:17)
npm ERR!     at HTTPParser.parserOnIncomingClient (_http_client.js:366:21)
npm ERR!     at HTTPParser.parserOnHeadersComplete (_http_common.js:109:23)
npm ERR!     at Socket.socketOnData (_http_client.js:257:20)
npm ERR!     at Socket.EventEmitter.emit (events.js:103:17)
npm ERR!     at readableAddChunk (_stream_readable.js:155:16)
npm ERR!     at Socket.Readable.push (_stream_readable.js:122:10)
npm ERR!     at TCP.onread (net.js:508:20)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.19.0-25-generic
npm ERR! command "/opt/node-v0.11.6-linux-x86/bin/node" "/opt/node-v0.11.6-linux-x86/bin/npm" "install"
npm ERR! cwd /home/kibana/kibana-4.5.1
npm ERR! node -v v0.11.6
npm ERR! npm -v 1.3.8
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Request.EventEmitter.addListener (events.js:175:15)
    at Request.init (/opt/node-v0.11.6-linux-x86/lib/node_modules/npm/node_modules/request/index.js:387:8)
    at Request.onResponse (/opt/node-v0.11.6-linux-x86/lib/node_modules/npm/node_modules/request/index.js:812:10)
    at ClientRequest.g (events.js:190:14)
    at ClientRequest.EventEmitter.emit (events.js:103:17)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:366:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:23)
    at Socket.socketOnData (_http_client.js:257:20)
    at Socket.EventEmitter.emit (events.js:103:17)
    at readableAddChunk (_stream_readable.js:155:16)
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Request.EventEmitter.addListener (events.js:175:15)
    at Request.start (/opt/node-v0.11.6-linux-x86/lib/node_modules/npm/node_modules/request/index.js:632:8)
    at Request.end (/opt/node-v0.11.6-linux-x86/lib/node_modules/npm/node_modules/request/index.js:1211:28)
    at /opt/node-v0.11.6-linux-x86/lib/node_modules/npm/node_modules/request/index.js:436:12
    at process._tickCallback (node.js:361:11)
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Request.EventEmitter.addListener (events.js:175:15)
    at Request.init (/opt/node-v0.11.6-linux-x86/lib/node_modules/npm/node_modules/request/index.js:387:8)
    at Request.onResponse (/opt/node-v0.11.6-linux-x86/lib/node_modules/npm/node_modules/request/index.js:812:10)
    at ClientRequest.g (events.js:190:14)
    at ClientRequest.EventEmitter.emit (events.js:103:17)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:366:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:23)
    at Socket.socketOnData (_http_client.js:257:20)
    at Socket.EventEmitter.emit (events.js:103:17)
    at readableAddChunk (_stream_readable.js:155:16)
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Request.EventEmitter.addListener (events.js:175:15)
    at Request.start (/opt/node-v0.11.6-linux-x86/lib/node_modules/npm/node_modules/request/index.js:632:8)
    at Request.end (/opt/node-v0.11.6-linux-x86/lib/node_modules/npm/node_modules/request/index.js:1211:28)
    at /opt/node-v0.11.6-linux-x86/lib/node_modules/npm/node_modules/request/index.js:436:12
    at process._tickCallback (node.js:361:11)
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Request.EventEmitter.addListener (events.js:175:15)
    at Request.init (/opt/node-v0.11.6-linux-x86/lib/node_modules/npm/node_modules/request/index.js:387:8)
    at Request.onResponse (/opt/node-v0.11.6-linux-x86/lib/node_modules/npm/node_modules/request/index.js:812:10)
    at ClientRequest.g (events.js:190:14)
    at ClientRequest.EventEmitter.emit (events.js:103:17)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:366:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:23)
    at Socket.socketOnData (_http_client.js:257:20)
    at Socket.EventEmitter.emit (events.js:103:17)
    at readableAddChunk (_stream_readable.js:155:16)
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Request.EventEmitter.addListener (events.js:175:15)
    at Request.start (/opt/node-v0.11.6-linux-x86/lib/node_modules/npm/node_modules/request/index.js:632:8)
    at Request.end (/opt/node-v0.11.6-linux-x86/lib/node_modules/npm/node_modules/request/index.js:1211:28)
    at /opt/node-v0.11.6-linux-x86/lib/node_modules/npm/node_modules/request/index.js:436:12
    at process._tickCallback (node.js:361:11)
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/kibana/kibana-4.5.1/npm-debug.log
npm ERR! not ok code 0

**Comment by KenanY** [comment]
@wenpos `npm@1.3` is years old and is no longer supported. Do you see the same issue with `npm@2` or `npm@3`?

**Comment by KenanY** [comment]
Closing as abandoned.
