### ISSUE TITLE
Unable to republish a package for first time.

### ISSUE THREAD

**Issue by vihuvac** [npm/npm#13337]
I've been doing some tests about the npm publishing feature and I was trying to publish my package, the first time when I published it, I did with the first tag: 1.0.0 running the publish command. As it was just a test, I added more features to my package and I decided to republish it again, then I removed it running the unpublish command, I saw that the package was not deleted completely because it is still in the npmjs site (it is empty), and when I try to republish it again, I get the following error:

```
npm ERR! publish Failed PUT 403
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "publish"
npm ERR! node v4.4.6
npm ERR! npm  v2.15.5
npm ERR! code E403

npm ERR! "You cannot publish over the previously published version 1.0.0. Try bumping the version to 2.0.0" : blueimp-file-uploader-express
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\vvallecastillo\Documents\Sources\blueimp-file-uploader-express\npm-debug.log
```

This is the the log file content:
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'publish' ]
2 info using npm@2.15.5
3 info using node@v4.4.6
4 verbose publish [ '.' ]
5 silly cache add args [ '.', null ]
6 verbose cache add spec .
7 silly cache add parsed spec Result {
7 silly cache add   raw: '.',
7 silly cache add   scope: null,
7 silly cache add   name: null,
7 silly cache add   rawSpec: '.',
7 silly cache add   spec: 'C:\\Users\\vvallecastillo\\Documents\\Sources\\blueimp-file-uploader-express',
7 silly cache add   type: 'directory' }
8 verbose addLocalDirectory C:\Users\vvallecastillo\AppData\Roaming\npm-cache\blueimp-file-uploader-express\1.0.0\package.tgz not in flight; packing
9 verbose correctMkdir C:\Users\vvallecastillo\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
10 verbose tar pack [ 'C:\\Users\\vvallecastillo\\AppData\\Roaming\\npm-cache\\blueimp-file-uploader-express\\1.0.0\\package.tgz',
10 verbose tar pack   'C:\\Users\\vvallecastillo\\Documents\\Sources\\blueimp-file-uploader-express' ]
11 verbose tarball C:\Users\vvallecastillo\AppData\Roaming\npm-cache\blueimp-file-uploader-express\1.0.0\package.tgz
12 verbose folder C:\Users\vvallecastillo\Documents\Sources\blueimp-file-uploader-express
13 info prepublish blueimp-file-uploader-express@1.0.0
14 verbose addLocalTarball adding from inside cache C:\Users\vvallecastillo\AppData\Roaming\npm-cache\blueimp-file-uploader-express\1.0.0\package.tgz
15 verbose correctMkdir C:\Users\vvallecastillo\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
16 silly cache afterAdd blueimp-file-uploader-express@1.0.0
17 verbose afterAdd C:\Users\vvallecastillo\AppData\Roaming\npm-cache\blueimp-file-uploader-express\1.0.0\package\package.json not in flight; writing
18 verbose correctMkdir C:\Users\vvallecastillo\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
19 verbose afterAdd C:\Users\vvallecastillo\AppData\Roaming\npm-cache\blueimp-file-uploader-express\1.0.0\package\package.json written
20 silly publish { name: 'blueimp-file-uploader-express',
20 silly publish   version: '1.0.0',
20 silly publish   description: 'This is a File Uploader for Node.js, the project is based on Blueimp jQuery File Upload developed by Sebastian Tschan.',
20 silly publish   main: 'index.js',
20 silly publish   scripts: { test: 'jasmine-node specs/' },
20 silly publish   dependencies:
20 silly publish    { async: '^1.5.2',
20 silly publish      'aws-sdk': '^2.4.6',
20 silly publish      formidable: '^1.0.17',
20 silly publish      lwip: '0.0.8',
20 silly publish      'node-fs': '^0.1.7' },
20 silly publish   devDependencies:
20 silly publish    { gulp: '^3.9.1',
20 silly publish      'gulp-jshint': '^2.0.1',
20 silly publish      jshint: '^2.9.2',
20 silly publish      'jasmine-node': '^1.14.5',
20 silly publish      'jshint-stylish': '^2.2.0' },
20 silly publish   repository:
20 silly publish    { type: 'git',
20 silly publish      url: 'git+https://github.com/vihuvac/blueimp-file-uploader-express.git' },
20 silly publish   keywords: [ 'blueimp', 'expressjs', 'file', 'jQuery', 'node.js', 'upload' ],
20 silly publish   author:
20 silly publish    { name: 'Victor Hugo Valle Castillo',
20 silly publish      email: 'victouk@gmail.com',
20 silly publish      url: 'https://vihuvac.com' },
20 silly publish   license: 'MIT',
20 silly publish   bugs: { url: 'https://github.com/vihuvac/blueimp-file-uploader-express.git/issues' },
20 silly publish   homepage: 'https://github.com/vihuvac/blueimp-file-uploader-express',
20 silly publish   readmeFilename: 'README.md',
20 silly publish   readme: 'Blueimp file uploader for Express js\r\n====================================\r\n\r\n[![Build Status](https://travis-ci.org/vihuvac/blueimp-file-uploader-express.svg?branch=master)](https://travis-ci.org/vihuvac/blueimp-file-uploader-express) [![Gitter](https://badges.gitter.im/vihuvac/blueimp-file-uploader-express.svg)](https://gitter.im/vihuvac/blueimp-file-uploader-express?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge) [![License](http://tools.vihuvac.com/images/collection/git-docs/license-mit.svg)](https://github.com/vihuvac/blueimp-file-uploader-express/blob/master/LICENSE)\r\n\r\n[![NPM](https://nodei.co/npm/blueimp-file-uploader-express.png?downloads=true&downloadRank=true&stars=true)](https://nodei.co/npm/blueimp-file-uploader-express/)\r\n\r\nA simple express module for integrating the *[jQuery File Upload](http://blueimp.github.io/jQuery-File-Upload/)* frontend plugin.\r\n\r\n## Contents\r\n\r\n* [History](#history)\r\n* [Installation](#installation)\r\n* [Configuration](#configuration)\r\n* [Usage with options](#usage-with-options)\r\n* [SSL Support](#ssl-support)\r\n* [Multiple thumbnails](#multiple-thumbnails)\r\n* [Tests](#tests)\r\n* [Contributions](#contributions)\r\n\r\n\r\n## History\r\nThe code was forked from a sample backend code from the [plugin\'s repo](https://github.com/blueimp/jQuery-File-Upload/wiki/Setup). Adaptations were made to show how to use this plugin with the popular *[Express](http://expressjs.com/)* *Node.js* framework.\r\n\r\nAlthough this code was initially meant for educational purposes, enhancements were made. Users can additionally:\r\n\r\n* upgrade lwip to version 0.0.6 or higher to support gif images.\r\n* choose the destination filesystem, local or cloud-based *Amazon S3*.\r\n* create thumbnail without heavy external dependencies using [lwip](https://www.npmjs.com/package/lwip).\r\n* setup server-side rules by [configuration](#Configuration).\r\n* modify the code against a [test harness](#Tests).\r\n\r\n## Installation\r\n\r\nSetup an *Express Project* and install the package.\r\n\r\n```js\r\n$ npm install blueimp-file-uploader-express --save\r\n```\r\n\r\n## Configuration\r\n```js\r\noptions = {\r\n    tmpDir: __dirname + "/public/tmp",      // tmp dir to upload files to\r\n    uploadDir: __dirname + "/public/files", // actual location of the file\r\n    uploadUrl: "/files/",                   // end point for delete route\r\n    maxPostSize: 11000000000,               // 11 GB\r\n    minFileSize: 1,\r\n    maxFileSize: 10000000000,               // 10 GB\r\n    acceptFileTypes: /.+/i,\r\n    inlineFileTypes: /\\.(gif|jpe?g|png)/i,\r\n    imageTypes:  /\\.(gif|jpe?g|png)/i,\r\n    copyImgAsThumb: true,                   // required\r\n    imageVersions: {\r\n        maxWidth: 200,\r\n        maxHeight: 200\r\n    },\r\n    accessControl: {\r\n        allowOrigin: "*",\r\n        allowMethods: "OPTIONS, HEAD, GET, POST, PUT, DELETE",\r\n        allowHeaders: "Content-Type, Content-Range, Content-Disposition"\r\n    },\r\n    storage: {\r\n        type: "local",                                     // local or aws\r\n        aws: {\r\n            accessKeyId: "xxxxxxxxxxxxxxxxx",              // required if aws\r\n            secretAccessKey: "xxxxxxxxxxxxxxxxxxxxxxx",    // required if aws\r\n            region: "sa-east-1",                           // make sure you know the region, else leave this option out\r\n            bucketName: "xxxxxxxxx",                       // required if aws\r\n            path: "some-directory-in-your-bucket/"         // optional if aws\r\n        }\r\n    }\r\n};\r\n\r\n```\r\n### Usage with options\r\n```js\r\n// config the uploader\r\nvar options = {\r\n    tmpDir:  __dirname + "/../public/uploaded/tmp",\r\n    uploadDir: __dirname + "/../public/uploaded/files",\r\n    uploadUrl:  "/uploaded/files/",\r\n    maxPostSize: 11000000000, // 11 GB\r\n    minFileSize:  1,\r\n    maxFileSize:  10000000000, // 10 GB\r\n    acceptFileTypes:  /.+/i,\r\n    // Files not matched by this regular expression force a download dialog,\r\n    // to prevent executing any scripts in the context of the service domain:\r\n    inlineFileTypes:  /\\.(gif|jpe?g|png)/i,\r\n    imageTypes:  /\\.(gif|jpe?g|png)/i,\r\n    copyImgAsThumb: true, // required\r\n    imageVersions: {\r\n        maxWidth: 200,\r\n        maxHeight: 200\r\n    },\r\n    accessControl: {\r\n        allowOrigin: "*",\r\n        allowMethods: "OPTIONS, HEAD, GET, POST, PUT, DELETE",\r\n        allowHeaders: "Content-Type, Content-Range, Content-Disposition"\r\n    },\r\n    storage: {\r\n        type: "aws",\r\n        aws: {\r\n            accessKeyId: "xxxxxxxxxxxxxxxxx",\r\n            secretAccessKey: "xxxxxxxxxxxxxxxxx",\r\n            region: "sa-east-1", // make sure you know the region, else leave this option out\r\n            bucketName: "xxxxxxxxxxxxxxxxx"\r\n        }\r\n    }\r\n};\r\n\r\n\r\n// Init the uploader\r\nvar uploader = require("blueimp-file-uploader-express")(options);\r\n\r\n\r\nmodule.exports = function (router) {\r\n    router.get("/upload", function (req, res) {\r\n        uploader.get(req, res, function (err, obj) {\r\n            res.send(JSON.stringify(obj));\r\n        });\r\n    });\r\n\r\n    router.post("/upload", function (req, res) {\r\n        uploader.post(req, res, function (err, obj) {\r\n            res.send(JSON.stringify(obj));\r\n        });\r\n    });\r\n\r\n    /**\r\n     * The path SHOULD match options.uploadUrl\r\n     *\r\n     * If you are using the optional parameter path: for aws, you need to pass the reference before the file name, e.g:\r\n     * router.delete("/uploaded/files/:directory/:name", function (req, res) {}\r\n     *\r\n     * Otherwise just pass a single reference, e.g:\r\n     * router.delete("/uploaded/files/:name", function (req, res) {}\r\n     */\r\n    router.delete("/uploaded/files/:name", function (req, res) {\r\n        uploader.delete(req, res, function (err, obj) {\r\n            res.send(JSON.stringify(obj));\r\n        });\r\n    });\r\n\r\n    return router;\r\n}\r\n```\r\n\r\n> **Note**:\r\n>\r\n> You can use the optional parameter ```path``` in order to store images in that specific directory.\r\n\r\n### SSL Support\r\n\r\nSet the `useSSL` option to `true` to use the package with an [HTTPS server](http://expressjs.com/4x/api.html#app.listen).\r\n\r\n```js\r\nvar express = require("express"),\r\n    fs      = require("fs"),\r\n    https   = require("https"),\r\n    app     = express()\r\n;\r\n\r\n\r\n// config the uploader\r\nvar options = {\r\n    ...\r\n    useSSL: true\r\n    ...\r\n};\r\n\r\n// init the uploader\r\nvar uploader = require("blueimp-file-uploader-express")(options);\r\n\r\napp.get("/upload", function(req, res) {\r\n    uploader.get(req, res, function (err,obj) {\r\n    if(!err)\r\n        res.send(JSON.stringify(obj));\r\n})\r\napp.post("/upload", // ...\r\napp.delete("/uploaded/files/:name", // ...\r\n\r\n// create the HTTPS server\r\nvar app_key = fs.readFileSync("key.pem");\r\nvar app_cert = fs.readFileSync("cert.pem");\r\n\r\nhttps.createServer({key: app_key, cert: app_cert}, app).listen(443);\r\n\r\n```\r\n\r\n### Multiple thumbnails\r\n\r\nTo generate multiple thumbnails while uploading.\r\n\r\n```js\r\nvar options = {\r\n    tmpDir: __dirname + "/../public/uploaded/tmp",\r\n    uploadDir: __dirname + "/../public/uploaded/files",\r\n    uploadUrl: "/uploaded/files/",\r\n    copyImgAsThumb: true, // required\r\n    imageVersions: {\r\n        maxWidth: 200,\r\n        maxHeight: 200\r\n    },\r\n    storage: {\r\n        type: "local"\r\n    }\r\n};\r\n```\r\n`copyImgAsThumb` needs to be set to true. `imageVersions`, `maxWidth` and `maxHeight` will by default create a `thumbnail` folder and place the specified width/height thumbnail in it.\r\n\r\nOptionally, you can omit the `maxHeight`. In this case, it will be resize proportionally to the specified width.\r\n\r\n```js\r\nimageVersions: {\r\n    maxWidth: 200\r\n},\r\n```\r\n\r\nalso\r\n\r\n```js\r\nimageVersions: {\r\n    maxWidth: 200,\r\n    maxHeight : "auto"\r\n},\r\n```\r\n\r\nPS : `auto` value works only with height.\r\n\r\nYou can also specify multiple thumbnail generations like\r\n\r\n```js\r\nvar options = {\r\n    tmpDir: __dirname + "/../public/uploaded/tmp",\r\n    uploadDir: __dirname + "/../public/uploaded/files",\r\n    uploadUrl: "/uploaded/files/",\r\n    copyImgAsThumb: true,\r\n    imageVersions: {\r\n        maxWidth: 200,\r\n        maxHeight: "auto",\r\n        "large" : {\r\n            width : 600,\r\n            height : 600\r\n        },\r\n        "medium" : {\r\n            width : 300,\r\n            height : 300\r\n        },\r\n        "small" : {\r\n            width : 150,\r\n            height : 150\r\n        }\r\n    },\r\n    storage: {\r\n        type: "local"\r\n    }\r\n};\r\n```\r\n\r\nRefer to : [How to submit additional form data](https://github.com/blueimp/jQuery-File-Upload/wiki/How-to-submit-additional-form-data) to send additional form data from the client.\r\n\r\n## Tests\r\n\r\nUnit tests can be run with *Jasmine* using `npm test` or this command:\r\n\r\n```js\r\n$ jasmine-node specs/\r\n```\r\n\r\n## Contributions\r\n\r\nChanges and improvements are welcome! Feel free to fork and open a pull request.\r\n\r\n### To Do\r\n* Make [Configuration](#configuration) documentation clearer and shorter.\r\n* Refactor code to build tests and provide generic transports as in `winston`.\r\n* Write end to end tests with [WebdriverIO](http://webdriver.io/).\r\n* Provide a basic image processing pipeline (resizing, croping, filter effects).\r\n* Fix AWS thubnail issue (preview at uploading).\r\n* Provide access to other cloud-based services like *Microsoft Azure*.\r\n',
20 silly publish   gitHead: '42525b8c7343f100f309de9ecc10f25b6ad907b3',
20 silly publish   _id: 'blueimp-file-uploader-express@1.0.0',
20 silly publish   _shasum: '70f991145b98c436b9d4b39e574bc8c7ff550d69',
20 silly publish   _from: '.' }
21 verbose getPublishConfig undefined
22 silly mapToRegistry name blueimp-file-uploader-express
23 silly mapToRegistry using default registry
24 silly mapToRegistry registry https://registry.npmjs.org/
25 silly mapToRegistry data Result {
25 silly mapToRegistry   raw: 'blueimp-file-uploader-express',
25 silly mapToRegistry   scope: null,
25 silly mapToRegistry   name: 'blueimp-file-uploader-express',
25 silly mapToRegistry   rawSpec: '',
25 silly mapToRegistry   spec: 'latest',
25 silly mapToRegistry   type: 'tag' }
26 silly mapToRegistry uri https://registry.npmjs.org/blueimp-file-uploader-express
27 verbose publish registryBase https://registry.npmjs.org/
28 silly publish uploading C:\Users\vvallecastillo\AppData\Roaming\npm-cache\blueimp-file-uploader-express\1.0.0\package.tgz
29 verbose request uri https://registry.npmjs.org/blueimp-file-uploader-express
30 verbose request sending authorization for write operation
31 info attempt registry request try #1 at 12:23:16 PM
32 verbose request using bearer token for auth
33 verbose request id bf5b4624780cb9eb
34 http request PUT https://registry.npmjs.org/blueimp-file-uploader-express
35 http 403 https://registry.npmjs.org/blueimp-file-uploader-express
36 verbose headers { 'content-type': 'application/json',
36 verbose headers   'cache-control': 'max-age=300',
36 verbose headers   'content-length': '128',
36 verbose headers   'accept-ranges': 'bytes',
36 verbose headers   date: 'Mon, 11 Jul 2016 15:23:19 GMT',
36 verbose headers   via: '1.1 varnish',
36 verbose headers   connection: 'keep-alive',
36 verbose headers   'x-served-by': 'cache-atl6243-ATL',
36 verbose headers   'x-cache': 'MISS',
36 verbose headers   'x-cache-hits': '0',
36 verbose headers   'x-timer': 'S1468250598.626865,VS0,VE1300',
36 verbose headers   vary: 'Accept-Encoding' }
37 verbose request invalidating C:\Users\vvallecastillo\AppData\Roaming\npm-cache\registry.npmjs.org\blueimp-file-uploader-express on PUT
38 error publish Failed PUT 403
39 verbose stack Error: "You cannot publish over the previously published version 1.0.0. Try bumping the version to 2.0.0" : blueimp-file-uploader-express
39 verbose stack     at makeError (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:264:12)
39 verbose stack     at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:252:14)
39 verbose stack     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:172:14)
39 verbose stack     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:200:22)
39 verbose stack     at emitTwo (events.js:87:13)
39 verbose stack     at Request.emit (events.js:172:7)
39 verbose stack     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1067:10)
39 verbose stack     at emitOne (events.js:82:20)
39 verbose stack     at Request.emit (events.js:169:7)
39 verbose stack     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:988:12)
40 verbose statusCode 403
41 verbose pkgid blueimp-file-uploader-express
42 verbose cwd C:\Users\vvallecastillo\Documents\Sources\blueimp-file-uploader-express
43 error Windows_NT 10.0.10586
44 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "publish"
45 error node v4.4.6
46 error npm  v2.15.5
47 error code E403
48 error "You cannot publish over the previously published version 1.0.0. Try bumping the version to 2.0.0" : blueimp-file-uploader-express
49 error If you need help, you may report this error at:
49 error     <https://github.com/npm/npm/issues>
50 verbose exit [ 1, true ]
```

Can someone help me please? I need to publish this package from zero.

**Comment by ehsalazar** [comment]
The issues have been addressed via communication to `support@npmjs.com`. Closing as resolved.

**Comment by vihuvac** [comment]
@ehsalazar Thank you very much for your support. 👍
