### ISSUE TITLE
I am having a problem trying to start a local server

### ISSUE THREAD

**Issue by gubyy** [npm/npm#13395]
#### I'm opening this issue because:

  - npm start is giving me the following error

#### What's going wrong?

```
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! path /Users/developer/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/Users/developer/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/developer/npm-debug.log
```

#### How can the CLI team reproduce the problem?

Here is my npm-debug.log

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.15.8
3 info using node@v4.4.7
4 verbose config Skipping project config: /Users/developer/.npmrc. (matches userconfig)
5 warn onload-script failed to require onload script npm-autoinit/autoinit
6 warn onload-script Error: Cannot find module 'npm-autoinit/autoinit'
6 warn onload-script     at Function.Module._resolveFilename (module.js:325:15)
6 warn onload-script     at Function.Module._load (module.js:276:25)
6 warn onload-script     at Module.require (module.js:353:17)
6 warn onload-script     at require (internal/module.js:12:17)
6 warn onload-script     at cb (/usr/local/lib/node_modules/npm/lib/npm.js:289:9)
6 warn onload-script     at /usr/local/lib/node_modules/npm/lib/npm.js:382:14
6 warn onload-script     at /usr/local/lib/node_modules/npm/lib/config/core.js:82:7
6 warn onload-script     at Array.forEach (native)
6 warn onload-script     at /usr/local/lib/node_modules/npm/lib/config/core.js:81:13
6 warn onload-script     at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:17:25)
6 warn onload-script  { [Error: Cannot find module 'npm-autoinit/autoinit'] code: 'MODULE_NOT_FOUND' }
7 verbose stack Error: ENOENT: no such file or directory, open '/Users/developer/package.json'
7 verbose stack     at Error (native)
8 verbose cwd /Users/developer
9 error Darwin 15.5.0
10 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
11 error node v4.4.7
12 error npm  v2.15.8
13 error path /Users/developer/package.json
14 error code ENOENT
15 error errno -2
16 error syscall open
17 error enoent ENOENT: no such file or directory, open '/Users/developer/package.json'
17 error enoent This is most likely not a problem with npm itself
17 error enoent and is related to npm not being able to find a file.
18 verbose exit [ -2, true ]
 ```

### supporting information:

 - `npm -v` prints: 2.15.8
 - `node -v` prints: v4.4.7
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X, or Linux?: OS X
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@gubyy Does `/Users/developer/package.json` exist? Without a `package.json` in your current directory defining a `"start"` script to run, `npm` will have no idea what you want it to do when you run `npm start`.
