### ISSUE TITLE
Unable to install using npm 

### ISSUE THREAD

**Issue by antcorpinc** [npm/npm#13390]
#### I'm opening this issue because:
- [ ] npm is doing something I don't understand.
#### How can the CLI team reproduce the problem?

Running the following command 

> npm i generator-aspnetcore-spa

Getting the below error

```
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "i" "generator-aspnetcore-spa"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.3
npm ERR! code SELF_SIGNED_CERT_IN_CHAIN

npm ERR! self signed certificate in certificate chain
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\MyProjects\aspnetcore\hwapp\npm-debug.log
```
### supporting information:

Pl find the below details from the log file generated

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'yo',
1 verbose cli   'generator-aspnetcore-spa' ]
2 info using npm@3.10.3
3 info using node@v6.3.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData yo
8 silly fetchPackageMetaData generator-aspnetcore-spa
9 silly fetchNamedPackageData yo
10 silly mapToRegistry name yo
11 silly mapToRegistry using default registry
12 silly mapToRegistry registry https://registry.npmjs.org/
13 silly mapToRegistry data Result {
13 silly mapToRegistry   raw: 'yo',
13 silly mapToRegistry   scope: null,
13 silly mapToRegistry   escapedName: 'yo',
13 silly mapToRegistry   name: 'yo',
13 silly mapToRegistry   rawSpec: '',
13 silly mapToRegistry   spec: 'latest',
13 silly mapToRegistry   type: 'tag' }
14 silly mapToRegistry uri https://registry.npmjs.org/yo
15 silly fetchNamedPackageData generator-aspnetcore-spa
16 silly mapToRegistry name generator-aspnetcore-spa
17 silly mapToRegistry using default registry
18 silly mapToRegistry registry https://registry.npmjs.org/
19 silly mapToRegistry data Result {
19 silly mapToRegistry   raw: 'generator-aspnetcore-spa',
19 silly mapToRegistry   scope: null,
19 silly mapToRegistry   escapedName: 'generator-aspnetcore-spa',
19 silly mapToRegistry   name: 'generator-aspnetcore-spa',
19 silly mapToRegistry   rawSpec: '',
19 silly mapToRegistry   spec: 'latest',
19 silly mapToRegistry   type: 'tag' }
20 silly mapToRegistry uri https://registry.npmjs.org/generator-aspnetcore-spa
21 verbose request uri https://registry.npmjs.org/generator-aspnetcore-spa
22 verbose request no auth needed
23 info attempt registry request try #1 at 9:14:08 AM
24 verbose request id 50cc619113ad18dc
25 http request GET https://registry.npmjs.org/generator-aspnetcore-spa
26 verbose request uri https://registry.npmjs.org/yo
27 verbose request no auth needed
28 info attempt registry request try #1 at 9:14:08 AM
29 verbose etag "AR0B2QCEHSUWQDYX4FYDSIGST"
30 http request GET https://registry.npmjs.org/yo
31 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
32 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
33 info attempt registry request try #2 at 9:14:19 AM
34 http request GET https://registry.npmjs.org/generator-aspnetcore-spa
35 info attempt registry request try #2 at 9:14:19 AM
36 verbose etag "AR0B2QCEHSUWQDYX4FYDSIGST"
37 http request GET https://registry.npmjs.org/yo
38 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
39 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
40 info attempt registry request try #3 at 9:15:20 AM
41 verbose etag "AR0B2QCEHSUWQDYX4FYDSIGST"
42 http request GET https://registry.npmjs.org/yo
43 info attempt registry request try #3 at 9:15:20 AM
44 http request GET https://registry.npmjs.org/generator-aspnetcore-spa
45 silly get cb [ 304, undefined ]
46 verbose etag https://registry.npmjs.org/yo from cache
47 verbose get saving yo to C:\Users\ronit.CYBAGE\AppData\Roaming\npm-cache\registry.npmjs.org\yo\.cache.json
48 verbose correctMkdir C:\Users\ronit.CYBAGE\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
49 silly fetchPackageMetaData Error: self signed certificate in certificate chain
49 silly fetchPackageMetaData     at Error (native)
49 silly fetchPackageMetaData     at TLSSocket.<anonymous> (_tls_wrap.js:1060:38)
49 silly fetchPackageMetaData     at emitNone (events.js:86:13)
49 silly fetchPackageMetaData     at TLSSocket.emit (events.js:185:7)
49 silly fetchPackageMetaData     at TLSSocket._finishInit (_tls_wrap.js:584:8)
49 silly fetchPackageMetaData     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38)
49 silly fetchPackageMetaData  error for generator-aspnetcore-spa { Error: self signed certificate in certificate chain
49 silly fetchPackageMetaData     at Error (native)
49 silly fetchPackageMetaData     at TLSSocket.<anonymous> (_tls_wrap.js:1060:38)
49 silly fetchPackageMetaData     at emitNone (events.js:86:13)
49 silly fetchPackageMetaData     at TLSSocket.emit (events.js:185:7)
49 silly fetchPackageMetaData     at TLSSocket._finishInit (_tls_wrap.js:584:8)
49 silly fetchPackageMetaData     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38) code: 'SELF_SIGNED_CERT_IN_CHAIN' }
50 silly rollbackFailedOptional Starting
51 silly rollbackFailedOptional Finishing
52 silly runTopLevelLifecycles Starting
53 silly runTopLevelLifecycles Finishing
54 silly install printInstalled
55 verbose stack Error: self signed certificate in certificate chain
55 verbose stack     at Error (native)
55 verbose stack     at TLSSocket.<anonymous> (_tls_wrap.js:1060:38)
55 verbose stack     at emitNone (events.js:86:13)
55 verbose stack     at TLSSocket.emit (events.js:185:7)
55 verbose stack     at TLSSocket._finishInit (_tls_wrap.js:584:8)
55 verbose stack     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38)
56 verbose cwd D:\MyProjects\aspnetcore\hwapp
57 error Windows_NT 6.1.7601
58 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "yo" "generator-aspnetcore-spa"
59 error node v6.3.0
60 error npm  v3.10.3
61 error code SELF_SIGNED_CERT_IN_CHAIN
62 error self signed certificate in certificate chain
63 error If you need help, you may report this error at:
63 error     <https://github.com/npm/npm/issues>
64 verbose exit [ 1, true ]
```

**Comment by wkzhu** [comment]
This exact error is happening to me - would be interested in learning why as well.
