### ISSUE TITLE
build js Cannot find module 'webpack'

### ISSUE THREAD

**Issue by Rechardone** [npm/npm#13437]
I'm going to run  'npm run build' on the linux to produce a app.js,but there is the erro

```console
> essential-react@0.3.0 build /mnt/jenkins/jobs/web-log/workspace
> webpack -p --config webpack.production.config.js
module.js:327
    throw err;
    ^
Error: Cannot find module 'webpack'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/mnt/jenkins/jobs/web-log/workspace/webpack.production.config.js:1:77)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

npm ERR! Linux 3.10.0-123.9.3.el7.x86_64
npm ERR! argv "/usr/src/node/bin/node" "/usr/bin/npm" "run" "build"
npm ERR! node v4.4.5
npm ERR! npm  v3.9.6
npm ERR! code ELIFECYCLE
npm ERR! essential-react@0.3.0 build: `webpack -p --config webpack.production.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the essential-react@0.3.0 build script 'webpack -p --config webpack.production.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the essential-react package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack -p --config webpack.production.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs essential-react
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls essential-react
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     /mnt/jenkins/jobs/web-log/workspace/npm-debug.log
```

there is the npm-debug.log

[npm-debug.txt](https://github.com/npm/npm/files/373440/npm-debug.txt)

**Comment by KenanY** [comment]
@Rechardone Are you still experiencing this issue?

**Comment by KenanY** [comment]
Closing as abandoned.
