### ISSUE TITLE
Cannot unpublish

### ISSUE THREAD

**Issue by vanesyan** [npm/npm#13445]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I've recently unpublished package `@unfancy/component-progress`, but something go wrong and package now exist on npm, but cannot be installed or republished (weird error below), when I run `npm unpublish @unfancy/component-progress` npm processes the task and doesn't output anything. 

#### How can the CLI team reproduce the problem?

```
0 info it worked if it ends with ok
1 verbose cli [ '/home/roman/.nvm/versions/node/v6.2.1/bin/node',
1 verbose cli   '/home/roman/.nvm/versions/node/v6.2.1/bin/npm',
1 verbose cli   'publish',
1 verbose cli   '--tag',
1 verbose cli   'lerna-temp' ]
2 info using npm@3.9.5
3 info using node@v6.2.1
4 verbose publish [ '.' ]
5 silly cache add args [ '.', null ]
6 verbose cache add spec .
7 silly cache add parsed spec Result {
7 silly cache add   raw: '.',
7 silly cache add   scope: null,
7 silly cache add   name: null,
7 silly cache add   rawSpec: '.',
7 silly cache add   spec: '/home/roman/Development/@unfancy/unfancy/packages/component-progress',
7 silly cache add   type: 'directory' }
8 verbose addLocalDirectory /home/roman/.npm/@unfancy/component-progress/0.1.0/package.tgz not in flight; packing
9 verbose correctMkdir /home/roman/.npm correctMkdir not in flight; initializing
10 info lifecycle @unfancy/component-progress@0.1.0~prepublish: @unfancy/component-progress@0.1.0
11 silly lifecycle @unfancy/component-progress@0.1.0~prepublish: no script for prepublish, continuing
12 verbose tar pack [ '/home/roman/.npm/@unfancy/component-progress/0.1.0/package.tgz',
12 verbose tar pack   '/home/roman/Development/@unfancy/unfancy/packages/component-progress' ]
13 verbose tarball /home/roman/.npm/@unfancy/component-progress/0.1.0/package.tgz
14 verbose folder /home/roman/Development/@unfancy/unfancy/packages/component-progress
15 verbose addLocalTarball adding from inside cache /home/roman/.npm/@unfancy/component-progress/0.1.0/package.tgz
16 verbose correctMkdir /home/roman/.npm correctMkdir not in flight; initializing
17 silly cache afterAdd @unfancy/component-progress@0.1.0
18 verbose afterAdd /home/roman/.npm/@unfancy/component-progress/0.1.0/package/package.json not in flight; writing
19 verbose correctMkdir /home/roman/.npm correctMkdir not in flight; initializing
20 verbose afterAdd /home/roman/.npm/@unfancy/component-progress/0.1.0/package/package.json written
21 silly publish { name: '@unfancy/component-progress',
21 silly publish   version: '0.1.0',
21 silly publish   author: { name: 'Romain Vanesyan', email: 'romain.vanesyan@gmail.com' },
21 silly publish   description: 'Progress component from Unfancy framework',
21 silly publish   keywords: [ 'unfancy', 'CSS', 'framework', 'progress', 'bar' ],
21 silly publish   license: 'MIT',
21 silly publish   repository:
21 silly publish    { type: 'git',
21 silly publish      url: 'git+ssh://git@github.com/unfancy/unfancy.git' },
21 silly publish   readme: '# @unfancy/component-progress\nThe [Unfancy] framework module `component-progress` exported as standalone package.\n\n## Installation\nUsing npm:\n```bash\n$ npm install --save @unfancy/component-progress\n```\n\nIn JavaScript:\n```js\n// CommonJS\nrequire(\'@unfancy/component-progress\')\n\n// ES2015\nimport \'@unfancy/component-progress\'\n```\n\nIn CSS:\n```css\n@import "@unfancy/component-progress";\n```\n\nSee the [documentation] or [package source] for more details.\n\n[Unfancy]: https://unfancy.github.io\n[documentation]: https://unfancy.github.io/docs\n[package source]: https://github.com/unfancy/unfancy/blob/master/packages/component-progress\n',
21 silly publish   readmeFilename: 'README.md',
21 silly publish   bugs: { url: 'https://github.com/unfancy/unfancy/issues' },
21 silly publish   homepage: 'https://github.com/unfancy/unfancy#readme',
21 silly publish   _id: '@unfancy/component-progress@0.1.0',
21 silly publish   scripts: {},
21 silly publish   _shasum: '9a836ee8f4eb1259229ae730527b7659955311b0',
21 silly publish   _from: '.' }
22 verbose getPublishConfig undefined
23 silly mapToRegistry name @unfancy/component-progress
24 silly mapToRegistry scope (from package name) @unfancy
25 verbose mapToRegistry no registry URL found in name for scope @unfancy
26 silly mapToRegistry using default registry
27 silly mapToRegistry registry https://registry.npmjs.org/
28 silly mapToRegistry data Result {
28 silly mapToRegistry   raw: '@unfancy/component-progress',
28 silly mapToRegistry   scope: '@unfancy',
28 silly mapToRegistry   name: '@unfancy/component-progress',
28 silly mapToRegistry   rawSpec: '',
28 silly mapToRegistry   spec: 'latest',
28 silly mapToRegistry   type: 'tag' }
29 silly mapToRegistry uri https://registry.npmjs.org/@unfancy%2fcomponent-progress
30 verbose publish registryBase https://registry.npmjs.org/
31 silly publish uploading /home/roman/.npm/@unfancy/component-progress/0.1.0/package.tgz
32 verbose request uri https://registry.npmjs.org/@unfancy%2fcomponent-progress
33 verbose request sending authorization for write operation
34 info attempt registry request try #1 at 4:28:02 PM
35 verbose request using bearer token for auth
36 verbose request id e26e763cb2a1ea8d
37 http request PUT https://registry.npmjs.org/@unfancy%2fcomponent-progress
38 http 403 https://registry.npmjs.org/@unfancy%2fcomponent-progress
39 verbose headers { 'content-type': 'application/json',
39 verbose headers   'cache-control': 'max-age=0',
39 verbose headers   'content-length': '128',
39 verbose headers   'accept-ranges': 'bytes',
39 verbose headers   date: 'Thu, 21 Jul 2016 11:28:04 GMT',
39 verbose headers   via: '1.1 varnish',
39 verbose headers   connection: 'keep-alive',
39 verbose headers   'x-served-by': 'cache-bma7025-BMA',
39 verbose headers   'x-cache': 'MISS',
39 verbose headers   'x-cache-hits': '0',
39 verbose headers   'x-timer': 'S1469100482.774389,VS0,VE1409' }
40 verbose request invalidating /home/roman/.npm/registry.npmjs.org/_40unfancy_252fcomponent-progress on PUT
41 error publish Failed PUT 403
42 verbose stack Error: "You cannot publish over the previously published version 0.1.0. Try bumping the version to 1.0.0" : @unfancy/component-progress
42 verbose stack     at makeError (/home/roman/.nvm/versions/node/v6.2.1/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
42 verbose stack     at CachingRegistryClient.<anonymous> (/home/roman/.nvm/versions/node/v6.2.1/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:252:14)
42 verbose stack     at Request._callback (/home/roman/.nvm/versions/node/v6.2.1/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
42 verbose stack     at Request.self.callback (/home/roman/.nvm/versions/node/v6.2.1/lib/node_modules/npm/node_modules/request/request.js:200:22)
42 verbose stack     at emitTwo (events.js:106:13)
42 verbose stack     at Request.emit (events.js:191:7)
42 verbose stack     at Request.<anonymous> (/home/roman/.nvm/versions/node/v6.2.1/lib/node_modules/npm/node_modules/request/request.js:1067:10)
42 verbose stack     at emitOne (events.js:101:20)
42 verbose stack     at Request.emit (events.js:188:7)
42 verbose stack     at IncomingMessage.<anonymous> (/home/roman/.nvm/versions/node/v6.2.1/lib/node_modules/npm/node_modules/request/request.js:988:12)
43 verbose statusCode 403
44 verbose pkgid @unfancy/component-progress
45 verbose cwd /home/roman/Development/@unfancy/unfancy/packages/component-progress
46 error Linux 4.4.0-31-generic
47 error argv "/home/roman/.nvm/versions/node/v6.2.1/bin/node" "/home/roman/.nvm/versions/node/v6.2.1/bin/npm" "publish" "--tag" "lerna-temp"
48 error node v6.2.1
49 error npm  v3.9.5
50 error code E403
51 error "You cannot publish over the previously published version 0.1.0. Try bumping the version to 1.0.0" : @unfancy/component-progress
52 error If you need help, you may report this error at:
52 error     <https://github.com/npm/npm/issues>
53 verbose exit [ 1, true ]
```

**Comment by vanesyan** [comment]
Resolved
