### ISSUE TITLE
npm Installation Issue

### ISSUE THREAD

**Issue by Jaws648** [npm/npm#13454]
I am trying to install jishi's node-sonos and am encountering the below error in NPM with install --production:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--production' ]
2 info using npm@1.4.29
3 info using node@v0.10.41
4 verbose node symlink /usr/local/bin/node
5 warn deprecated This version of npm lacks support for important features,
6 warn deprecated such as scoped packages, offered by the primary npm
7 warn deprecated registry. Consider upgrading to at least npm@2, if not the
8 warn deprecated latest stable version. To upgrade to npm@2, run:
9 warn deprecated npm -g install npm@latest-2
10 warn deprecated To upgrade to the latest stable version, run:
11 warn deprecated npm -g install npm@latest
12 warn deprecated (Depending on how Node.js was installed on your system, you
13 warn deprecated may need to prefix the preceding commands with `sudo`, or if
14 warn deprecated on Windows, run them from an Administrator prompt.)
15 warn deprecated If you're running the version of npm bundled with
16 warn deprecated Node.js 0.10 LTS, be aware that the next version of 0.10 LTS
17 warn deprecated will be bundled with a version of npm@2, which has some small
18 warn deprecated backwards-incompatible changes made to `npm run-script` and
19 warn deprecated semver behavior.
20 verbose readDependencies using package.json deps
21 verbose install where, deps [ '/volume1/other/node-sonos-http-api',
21 verbose install   [ 'async',
21 verbose install     'basic-auth',
21 verbose install     'node-static',
21 verbose install     'request-promise',
21 verbose install     'require-fu',
21 verbose install     'sonos-discovery' ] ]
22 info preinstall sonos-http-api@0.19.0
23 verbose readDependencies using package.json deps
24 verbose cache add [ 'async@~1.5.0', null ]
25 verbose cache add name=undefined spec="async@~1.5.0" args=["async@~1.5.0",null]
26 verbose parsed url { protocol: null,
26 verbose parsed url   slashes: null,
26 verbose parsed url   auth: null,
26 verbose parsed url   host: null,
26 verbose parsed url   port: null,
26 verbose parsed url   hostname: null,
26 verbose parsed url   hash: null,
26 verbose parsed url   search: null,
26 verbose parsed url   query: null,
26 verbose parsed url   pathname: 'async@~1.5.0',
26 verbose parsed url   path: 'async@~1.5.0',
26 verbose parsed url   href: 'async@~1.5.0' }
27 verbose cache add [ 'basic-auth@~1.0.3', null ]
28 verbose cache add name=undefined spec="basic-auth@~1.0.3" args=["basic-auth@~1.0.3",null]
29 verbose parsed url { protocol: null,
29 verbose parsed url   slashes: null,
29 verbose parsed url   auth: null,
29 verbose parsed url   host: null,
29 verbose parsed url   port: null,
29 verbose parsed url   hostname: null,
29 verbose parsed url   hash: null,
29 verbose parsed url   search: null,
29 verbose parsed url   query: null,
29 verbose parsed url   pathname: 'basic-auth@~1.0.3',
29 verbose parsed url   path: 'basic-auth@~1.0.3',
29 verbose parsed url   href: 'basic-auth@~1.0.3' }
30 verbose cache add [ 'node-static@~0.7.0', null ]
31 verbose cache add name=undefined spec="node-static@~0.7.0" args=["node-static@~0.7.0",null]
32 verbose parsed url { protocol: null,
32 verbose parsed url   slashes: null,
32 verbose parsed url   auth: null,
32 verbose parsed url   host: null,
32 verbose parsed url   port: null,
32 verbose parsed url   hostname: null,
32 verbose parsed url   hash: null,
32 verbose parsed url   search: null,
32 verbose parsed url   query: null,
32 verbose parsed url   pathname: 'node-static@~0.7.0',
32 verbose parsed url   path: 'node-static@~0.7.0',
32 verbose parsed url   href: 'node-static@~0.7.0' }
33 verbose cache add [ 'request-promise@~1.0.2', null ]
34 verbose cache add name=undefined spec="request-promise@~1.0.2" args=["request-promise@~1.0.2",null]
35 verbose parsed url { protocol: null,
35 verbose parsed url   slashes: null,
35 verbose parsed url   auth: null,
35 verbose parsed url   host: null,
35 verbose parsed url   port: null,
35 verbose parsed url   hostname: null,
35 verbose parsed url   hash: null,
35 verbose parsed url   search: null,
35 verbose parsed url   query: null,
35 verbose parsed url   pathname: 'request-promise@~1.0.2',
35 verbose parsed url   path: 'request-promise@~1.0.2',
35 verbose parsed url   href: 'request-promise@~1.0.2' }
36 verbose cache add [ 'require-fu@~1.0.0', null ]
37 verbose cache add name=undefined spec="require-fu@~1.0.0" args=["require-fu@~1.0.0",null]
38 verbose parsed url { protocol: null,
38 verbose parsed url   slashes: null,
38 verbose parsed url   auth: null,
38 verbose parsed url   host: null,
38 verbose parsed url   port: null,
38 verbose parsed url   hostname: null,
38 verbose parsed url   hash: null,
38 verbose parsed url   search: null,
38 verbose parsed url   query: null,
38 verbose parsed url   pathname: 'require-fu@~1.0.0',
38 verbose parsed url   path: 'require-fu@~1.0.0',
38 verbose parsed url   href: 'require-fu@~1.0.0' }
39 verbose cache add [ 'sonos-discovery@https://github.com/jishi/node-sonos-discovery/archive/v0.16.5.tar.gz',
39 verbose cache add   null ]
40 verbose cache add name=undefined spec="sonos-discovery@https://github.com/jishi/node-sonos-discovery/archive/v0.16.5.tar.gz" args=["sonos-discovery@https://github.com/jishi/node-sonos-discovery/archive/v0.16.5.tar.gz",null]
41 verbose parsed url { protocol: null,
41 verbose parsed url   slashes: null,
41 verbose parsed url   auth: null,
41 verbose parsed url   host: null,
41 verbose parsed url   port: null,
41 verbose parsed url   hostname: null,
41 verbose parsed url   hash: null,
41 verbose parsed url   search: null,
41 verbose parsed url   query: null,
41 verbose parsed url   pathname: 'sonos-discovery@https://github.com/jishi/node-sonos-discovery/archive/v0.16.5.tar.gz',
41 verbose parsed url   path: 'sonos-discovery@https://github.com/jishi/node-sonos-discovery/archive/v0.16.5.tar.gz',
41 verbose parsed url   href: 'sonos-discovery@https://github.com/jishi/node-sonos-discovery/archive/v0.16.5.tar.gz' }
42 verbose cache add name="async" spec="~1.5.0" args=["async","~1.5.0"]
43 verbose parsed url { protocol: null,
43 verbose parsed url   slashes: null,
43 verbose parsed url   auth: null,
43 verbose parsed url   host: null,
43 verbose parsed url   port: null,
43 verbose parsed url   hostname: null,
43 verbose parsed url   hash: null,
43 verbose parsed url   search: null,
43 verbose parsed url   query: null,
43 verbose parsed url   pathname: '~1.5.0',
43 verbose parsed url   path: '~1.5.0',
43 verbose parsed url   href: '~1.5.0' }
44 verbose addNamed [ 'async', '~1.5.0' ]
45 verbose addNamed [ null, '>=1.5.0-0 <1.6.0-0' ]
46 verbose cache add name="basic-auth" spec="~1.0.3" args=["basic-auth","~1.0.3"]
47 verbose parsed url { protocol: null,
47 verbose parsed url   slashes: null,
47 verbose parsed url   auth: null,
47 verbose parsed url   host: null,
47 verbose parsed url   port: null,
47 verbose parsed url   hostname: null,
47 verbose parsed url   hash: null,
47 verbose parsed url   search: null,
47 verbose parsed url   query: null,
47 verbose parsed url   pathname: '~1.0.3',
47 verbose parsed url   path: '~1.0.3',
47 verbose parsed url   href: '~1.0.3' }
48 verbose addNamed [ 'basic-auth', '~1.0.3' ]
49 verbose addNamed [ null, '>=1.0.3-0 <1.1.0-0' ]
50 verbose cache add name="node-static" spec="~0.7.0" args=["node-static","~0.7.0"]
51 verbose parsed url { protocol: null,
51 verbose parsed url   slashes: null,
51 verbose parsed url   auth: null,
51 verbose parsed url   host: null,
51 verbose parsed url   port: null,
51 verbose parsed url   hostname: null,
51 verbose parsed url   hash: null,
51 verbose parsed url   search: null,
51 verbose parsed url   query: null,
51 verbose parsed url   pathname: '~0.7.0',
51 verbose parsed url   path: '~0.7.0',
51 verbose parsed url   href: '~0.7.0' }
52 verbose addNamed [ 'node-static', '~0.7.0' ]
53 verbose addNamed [ null, '>=0.7.0-0 <0.8.0-0' ]
54 verbose cache add name="request-promise" spec="~1.0.2" args=["request-promise","~1.0.2"]
55 verbose parsed url { protocol: null,
55 verbose parsed url   slashes: null,
55 verbose parsed url   auth: null,
55 verbose parsed url   host: null,
55 verbose parsed url   port: null,
55 verbose parsed url   hostname: null,
55 verbose parsed url   hash: null,
55 verbose parsed url   search: null,
55 verbose parsed url   query: null,
55 verbose parsed url   pathname: '~1.0.2',
55 verbose parsed url   path: '~1.0.2',
55 verbose parsed url   href: '~1.0.2' }
56 verbose addNamed [ 'request-promise', '~1.0.2' ]
57 verbose addNamed [ null, '>=1.0.2-0 <1.1.0-0' ]
58 verbose cache add name="require-fu" spec="~1.0.0" args=["require-fu","~1.0.0"]
59 verbose parsed url { protocol: null,
59 verbose parsed url   slashes: null,
59 verbose parsed url   auth: null,
59 verbose parsed url   host: null,
59 verbose parsed url   port: null,
59 verbose parsed url   hostname: null,
59 verbose parsed url   hash: null,
59 verbose parsed url   search: null,
59 verbose parsed url   query: null,
59 verbose parsed url   pathname: '~1.0.0',
59 verbose parsed url   path: '~1.0.0',
59 verbose parsed url   href: '~1.0.0' }
60 verbose addNamed [ 'require-fu', '~1.0.0' ]
61 verbose addNamed [ null, '>=1.0.0-0 <1.1.0-0' ]
62 verbose cache add name="sonos-discovery" spec="https://github.com/jishi/node-sonos-discovery/archive/v0.16.5.tar.gz" args=["sonos-discovery","https://github.com/jishi/node-sonos-discovery/archive/v0.16.5.tar.gz"]
63 verbose parsed url { protocol: 'https:',
63 verbose parsed url   slashes: true,
63 verbose parsed url   auth: null,
63 verbose parsed url   host: 'github.com',
63 verbose parsed url   port: null,
63 verbose parsed url   hostname: 'github.com',
63 verbose parsed url   hash: null,
63 verbose parsed url   search: null,
63 verbose parsed url   query: null,
63 verbose parsed url   pathname: '/jishi/node-sonos-discovery/archive/v0.16.5.tar.gz',
63 verbose parsed url   path: '/jishi/node-sonos-discovery/archive/v0.16.5.tar.gz',
63 verbose parsed url   href: 'https://github.com/jishi/node-sonos-discovery/archive/v0.16.5.tar.gz' }
64 silly lockFile dcb308ed-async-1-5-0 async@~1.5.0
65 error Error: Attempt to unlock async@~1.5.0, which hasn't been locked
65 error     at unlock (/usr/local/lib/node_modules/npm/lib/utils/locker.js:44:11)
65 error     at cb (/usr/local/lib/node_modules/npm/lib/cache/add-named.js:32:5)
65 error     at /usr/local/lib/node_modules/npm/lib/cache/add-named.js:41:20
65 error     at /usr/local/lib/node_modules/npm/lib/utils/locker.js:22:20
65 error     at /usr/local/lib/node_modules/npm/node_modules/inflight/inflight.js:22:7
65 error     at Array.forEach (native)
65 error     at res (/usr/local/lib/node_modules/npm/node_modules/inflight/inflight.js:21:9)
65 error     at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:16:25)
65 error     at afterMkdir (/usr/local/lib/node_modules/npm/lib/cache/get-stat.js:53:14)
65 error     at /usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:34:29
66 error If you need help, you may report this *entire* log,
66 error including the npm and node versions, at:
66 error     <http://github.com/npm/npm/issues>
67 error System Linux 2.6.32.12
68 error command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--production"
69 error cwd /volume1/other/node-sonos-http-api
70 error node -v v0.10.41
71 error npm -v 1.4.29
72 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
@Jaws648 Does this also occur if you update to `npm@2` or `npm@3`? Your version of `npm` is no longer supported.

**Comment by Jaws648** [comment]
I meant to upload the failure of the update as well:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   '-g',
1 verbose cli   'install',
1 verbose cli   'npm@latest' ]
2 info using npm@1.4.29
3 info using node@v0.10.41
4 verbose node symlink /usr/local/bin/node
5 warn deprecated This version of npm lacks support for important features,
6 warn deprecated such as scoped packages, offered by the primary npm
7 warn deprecated registry. Consider upgrading to at least npm@2, if not the
8 warn deprecated latest stable version. To upgrade to npm@2, run:
9 warn deprecated npm -g install npm@latest-2
10 warn deprecated To upgrade to the latest stable version, run:
11 warn deprecated npm -g install npm@latest
12 warn deprecated (Depending on how Node.js was installed on your system, you
13 warn deprecated may need to prefix the preceding commands with `sudo`, or if
14 warn deprecated on Windows, run them from an Administrator prompt.)
15 warn deprecated If you're running the version of npm bundled with
16 warn deprecated Node.js 0.10 LTS, be aware that the next version of 0.10 LTS
17 warn deprecated will be bundled with a version of npm@2, which has some small
18 warn deprecated backwards-incompatible changes made to `npm run-script` and
19 warn deprecated semver behavior.
20 verbose cache add [ 'npm@latest', null ]
21 verbose cache add name=undefined spec="npm@latest" args=["npm@latest",null]
22 verbose parsed url { protocol: null,
22 verbose parsed url   slashes: null,
22 verbose parsed url   auth: null,
22 verbose parsed url   host: null,
22 verbose parsed url   port: null,
22 verbose parsed url   hostname: null,
22 verbose parsed url   hash: null,
22 verbose parsed url   search: null,
22 verbose parsed url   query: null,
22 verbose parsed url   pathname: 'npm@latest',
22 verbose parsed url   path: 'npm@latest',
22 verbose parsed url   href: 'npm@latest' }
23 verbose cache add name="npm" spec="latest" args=["npm","latest"]
24 verbose parsed url { protocol: null,
24 verbose parsed url   slashes: null,
24 verbose parsed url   auth: null,
24 verbose parsed url   host: null,
24 verbose parsed url   port: null,
24 verbose parsed url   hostname: null,
24 verbose parsed url   hash: null,
24 verbose parsed url   search: null,
24 verbose parsed url   query: null,
24 verbose parsed url   pathname: 'latest',
24 verbose parsed url   path: 'latest',
24 verbose parsed url   href: 'latest' }
25 verbose addNamed [ 'npm', 'latest' ]
26 verbose addNamed [ null, null ]
27 silly lockFile 588f5fcc-npm-latest npm@latest
28 error Error: Attempt to unlock npm@latest, which hasn't been locked
28 error     at unlock (/usr/local/lib/node_modules/npm/lib/utils/locker.js:44:11)
28 error     at cb (/usr/local/lib/node_modules/npm/lib/cache/add-named.js:32:5)
28 error     at /usr/local/lib/node_modules/npm/lib/cache/add-named.js:41:20
28 error     at /usr/local/lib/node_modules/npm/lib/utils/locker.js:22:20
28 error     at /usr/local/lib/node_modules/npm/node_modules/inflight/inflight.js:22:7
28 error     at Array.forEach (native)
28 error     at res (/usr/local/lib/node_modules/npm/node_modules/inflight/inflight.js:21:9)
28 error     at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:16:25)
28 error     at afterMkdir (/usr/local/lib/node_modules/npm/lib/cache/get-stat.js:53:14)
28 error     at /usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:34:29
29 error If you need help, you may report this *entire* log,
29 error including the npm and node versions, at:
29 error     <http://github.com/npm/npm/issues>
30 error System Linux 2.6.32.12
31 error command "/usr/local/bin/node" "/usr/local/bin/npm" "-g" "install" "npm@latest"
32 error cwd /volume1/other/node-sonos-http-api
33 error node -v v0.10.41
34 error npm -v 1.4.29
35 verbose exit [ 1, true ]

**Comment by othiym23** [comment]
As @KenanY said, `npm@1` is no longer supported. This is a known issue with `npm@1` which is fixed in newer versions of npm, which can be installed (using npm) via `npm -g install npm@lts` or `npm -g install npm@latest`, or using https://www.npmjs.com/package/npm-windows-upgrade.

Closing as resolved.
