### ISSUE TITLE
getting error on npm start

### ISSUE THREAD

**Issue by mazher-nazeer** [npm/npm#13477]
getting this while running `npm start`

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.14.20
3 info using node@v4.4.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart oict@0.0.0
6 info start oict@0.0.0
7 verbose unsafe-perm in lifecycle true
8 info oict@0.0.0 Failed to exec start script
9 verbose stack Error: oict@0.0.0 start: `webpack-dev-server --inline --debug --devtool eval --hot --content-base app`
9 verbose stack Exit status 3221225725
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid oict@0.0.0
11 verbose cwd D:\projects\Oict\OICT\Code\OICT\OICT.AngularApplication
12 error Windows_NT 6.1.7601
13 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
14 error node v4.4.0
15 error npm  v2.14.20
16 error code ELIFECYCLE
17 error oict@0.0.0 start: `webpack-dev-server --inline --debug --devtool eval --hot --content-base app`
17 error Exit status 3221225725
18 error Failed at the oict@0.0.0 start script 'webpack-dev-server --inline --debug --devtool eval --hot --content-base app'.
18 error This is most likely a problem with the oict package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     webpack-dev-server --inline --debug --devtool eval --hot --content-base app
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs oict
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls oict
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

**Comment by Skhoshhal** [comment]
npm ERR! Linux 4.4.0-31-generic
npm ERR! argv "/home/ssadat/.nvm/versions/node/v5.11.1/bin/node" "/home/ssadat/.nvm/versions/node/v5.11.1/bin/npm" "start"
npm ERR! node v5.11.1
npm ERR! npm  v3.8.6

npm ERR! missing script: start
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ssadat/Desktop/blackjack-master/npm-debug.log

**Comment by KenanY** [comment]
@Skhoshhal Your error is different from that of @mazher-nazeer. Do you have a `"start"` script defined in your `package.json`?

**Comment by swaranan** [comment]
I have getting same problem on "npm start"

Here my log
```

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@2.14.12
3 info using node@v4.3.2
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info prebuild whk@1.0.0
6 info build whk@1.0.0
7 verbose unsafe-perm in lifecycle true
8 info whk@1.0.0 Failed to exec build script
9 verbose stack Error: whk@1.0.0 build: `gulp production`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:821:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid whk@1.0.0
11 verbose cwd E:\work@mejora\ssavajols\html\whk-basic-structure
12 error Windows_NT 6.3.9600
13 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
14 error node v4.3.2
15 error npm  v2.14.12
16 error code ELIFECYCLE
17 error whk@1.0.0 build: `gulp production`
17 error Exit status 1
18 error Failed at the whk@1.0.0 build script 'gulp production'.
18 error This is most likely a problem with the whk package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     gulp production
18 error You can get their info via:
18 error     npm owner ls whk
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

```

**Comment by KenanY** [comment]
@swaranan Looks like your `"build"` script is throwing an error, which is usually not the fault of `npm`. I would try running `gulp production` _outside_ of a script (i.e., right in your command line).
