### ISSUE TITLE
ERR! Darwin 15.4.0 

### ISSUE THREAD

**Issue by sharoni3d** [npm/npm#13507]
#### I'm opening this issue because:

 I'm getting this error when i run this command :
 npm install angularfire2 firebase@2.4.2 --save

``` console
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/Users/maya/.npm-packages/bin/npm',
1 verbose cli   'install',
1 verbose cli   'angularfire2',
1 verbose cli   'firebase@2.4.2',
1 verbose cli   '--sav' ]
2 info using npm@3.10.5
3 info using node@v4.4.7
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData angularfire2
8 silly fetchPackageMetaData firebase@2.4.2
9 silly fetchNamedPackageData firebase
10 silly mapToRegistry name firebase
11 silly mapToRegistry using default registry
12 silly mapToRegistry registry https://registry.npmjs.org/
13 silly mapToRegistry data Result {
13 silly mapToRegistry   raw: 'firebase',
13 silly mapToRegistry   scope: null,
13 silly mapToRegistry   escapedName: 'firebase',
13 silly mapToRegistry   name: 'firebase',
13 silly mapToRegistry   rawSpec: '',
13 silly mapToRegistry   spec: 'latest',
13 silly mapToRegistry   type: 'tag' }
14 silly mapToRegistry uri https://registry.npmjs.org/firebase
15 silly fetchNamedPackageData angularfire2
16 silly mapToRegistry name angularfire2
17 silly mapToRegistry using default registry
18 silly mapToRegistry registry https://registry.npmjs.org/
19 silly mapToRegistry data Result {
19 silly mapToRegistry   raw: 'angularfire2',
19 silly mapToRegistry   scope: null,
19 silly mapToRegistry   escapedName: 'angularfire2',
19 silly mapToRegistry   name: 'angularfire2',
19 silly mapToRegistry   rawSpec: '',
19 silly mapToRegistry   spec: 'latest',
19 silly mapToRegistry   type: 'tag' }
20 silly mapToRegistry uri https://registry.npmjs.org/angularfire2
21 verbose request uri https://registry.npmjs.org/firebase
22 verbose request no auth needed
23 info attempt registry request try #1 at 11:31:08 PM
24 verbose request id 1a79254fc8521bc8
25 verbose etag "CWSBB9FBWJGYFFZQ7MZ1WISBT"
26 http request GET https://registry.npmjs.org/firebase
27 verbose request uri https://registry.npmjs.org/angularfire2
28 verbose request no auth needed
29 info attempt registry request try #1 at 11:31:08 PM
30 verbose etag "5OFI50Y47L4P79ATKVCKCPOV7"
31 http request GET https://registry.npmjs.org/angularfire2
32 http 304 https://registry.npmjs.org/firebase
33 verbose headers { date: 'Thu, 28 Jul 2016 03:31:08 GMT',
33 verbose headers   via: '1.1 varnish',
33 verbose headers   'cache-control': 'max-age=300',
33 verbose headers   etag: '"CWSBB9FBWJGYFFZQ7MZ1WISBT"',
33 verbose headers   age: '166',
33 verbose headers   connection: 'keep-alive',
33 verbose headers   'x-served-by': 'cache-ord1743-ORD',
33 verbose headers   'x-cache': 'HIT',
33 verbose headers   'x-cache-hits': '2',
33 verbose headers   'x-timer': 'S1469676668.492942,VS0,VE0',
33 verbose headers   vary: 'Accept-Encoding' }
34 silly get cb [ 304,
34 silly get   { date: 'Thu, 28 Jul 2016 03:31:08 GMT',
34 silly get     via: '1.1 varnish',
34 silly get     'cache-control': 'max-age=300',
34 silly get     etag: '"CWSBB9FBWJGYFFZQ7MZ1WISBT"',
34 silly get     age: '166',
34 silly get     connection: 'keep-alive',
34 silly get     'x-served-by': 'cache-ord1743-ORD',
34 silly get     'x-cache': 'HIT',
34 silly get     'x-cache-hits': '2',
34 silly get     'x-timer': 'S1469676668.492942,VS0,VE0',
34 silly get     vary: 'Accept-Encoding' } ]
35 verbose etag https://registry.npmjs.org/firebase from cache
36 verbose get saving firebase to /Users/maya/.npm/registry.npmjs.org/firebase/.cache.json
37 verbose correctMkdir /Users/maya/.npm correctMkdir not in flight; initializing
38 http 304 https://registry.npmjs.org/angularfire2
39 verbose headers { date: 'Thu, 28 Jul 2016 03:31:08 GMT',
39 verbose headers   via: '1.1 varnish',
39 verbose headers   'cache-control': 'max-age=300',
39 verbose headers   etag: '"5OFI50Y47L4P79ATKVCKCPOV7"',
39 verbose headers   age: '15',
39 verbose headers   connection: 'keep-alive',
39 verbose headers   'x-served-by': 'cache-ord1737-ORD',
39 verbose headers   'x-cache': 'HIT',
39 verbose headers   'x-cache-hits': '1',
39 verbose headers   'x-timer': 'S1469676668.495669,VS0,VE0',
39 verbose headers   vary: 'Accept-Encoding' }
40 silly get cb [ 304,
40 silly get   { date: 'Thu, 28 Jul 2016 03:31:08 GMT',
40 silly get     via: '1.1 varnish',
40 silly get     'cache-control': 'max-age=300',
40 silly get     etag: '"5OFI50Y47L4P79ATKVCKCPOV7"',
40 silly get     age: '15',
40 silly get     connection: 'keep-alive',
40 silly get     'x-served-by': 'cache-ord1737-ORD',
40 silly get     'x-cache': 'HIT',
40 silly get     'x-cache-hits': '1',
40 silly get     'x-timer': 'S1469676668.495669,VS0,VE0',
40 silly get     vary: 'Accept-Encoding' } ]
41 verbose etag https://registry.npmjs.org/angularfire2 from cache
42 verbose get saving angularfire2 to /Users/maya/.npm/registry.npmjs.org/angularfire2/.cache.json
43 verbose correctMkdir /Users/maya/.npm correctMkdir already in flight; waiting
44 silly install normalizeTree
45 silly loadCurrentTree Finishing
46 silly loadIdealTree Starting
47 silly install loadIdealTree
48 silly cloneCurrentTree Starting
49 silly install cloneCurrentTreeToIdealTree
50 silly cloneCurrentTree Finishing
51 silly loadShrinkwrap Starting
52 silly install loadShrinkwrap
53 silly loadShrinkwrap Finishing
54 silly loadAllDepsIntoIdealTree Starting
55 silly install loadAllDepsIntoIdealTree
56 silly rollbackFailedOptional Starting
57 silly rollbackFailedOptional Finishing
58 silly runTopLevelLifecycles Starting
59 silly runTopLevelLifecycles Finishing
60 silly install printInstalled
61 verbose stack Error: Refusing to install firebase as a dependency of itself
61 verbose stack     at checkSelf (/Users/maya/.npm-packages/lib/node_modules/npm/lib/install/validate-args.js:53:14)
61 verbose stack     at Array.<anonymous> (/Users/maya/.npm-packages/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
61 verbose stack     at LOOP (/Users/maya/.npm-packages/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
61 verbose stack     at chain (/Users/maya/.npm-packages/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
61 verbose stack     at /Users/maya/.npm-packages/lib/node_modules/npm/lib/install/validate-args.js:16:5
61 verbose stack     at /Users/maya/.npm-packages/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
61 verbose stack     at Array.forEach (native)
61 verbose stack     at /Users/maya/.npm-packages/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
61 verbose stack     at Array.forEach (native)
61 verbose stack     at asyncMap (/Users/maya/.npm-packages/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
62 verbose cwd /Users/maya/Desktop/firebase
63 error Darwin 15.4.0
64 error argv "/usr/local/bin/node" "/Users/maya/.npm-packages/bin/npm" "install" "angularfire2" "firebase@2.4.2" "--sav"
65 error node v4.4.7
66 error npm  v3.10.5
67 error code ENOSELF
68 error Refusing to install firebase as a dependency of itself
69 error If you need help, you may report this error at:
69 error     <https://github.com/npm/npm/issues>
70 verbose exit [ 1, true ]
```
#### What's going wrong?

This is the Error im getting

``` console
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/Users/maya/.npm-packages/bin/npm" "install" "angularfire2" "firebase@2.4.2" "--sav"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.5
npm ERR! code ENOSELF

npm ERR! Refusing to install firebase as a dependency of itself
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/maya/Desktop/firebase/npm-debug.log
```
#### How can the CLI team reproduce the problem?

i tried fixing with this command 

``` console
$ sudo chown -R $(whoami) /usr/local
$ sudo chmod -R 755 /usr/local/bin
```
### supporting information:
- `npm -v` prints: 3.10.5
- `node -v` prints: v4.4.7
- Windows, OS X, or Linux?: Max OS X El Capitan 10.11.4

Please Help i'm new to this 
if it's possible to get a step by step to fix

**Comment by KenanY** [comment]
@sharoni3d Is the `"name"` attribute of your `package.json` set to `"firebase"`? If so, could you try changing it to something which does not share a name with one of your dependencies?

**Comment by sharoni3d** [comment]
i does have the same name so i changed it but i still get the same error.

Mayas-iMac:firebase maya$ npm install angularfire2 firebase@2.4.2 --save
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/Users/maya/.npm-packages/bin/npm" "install" "angularfire2" "firebase@2.4.2" "--save"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.5
npm ERR! code ENOSELF

npm ERR! Refusing to install firebase as a dependency of itself
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/maya/Desktop/firebase/npm-debug.log

**Comment by KenanY** [comment]
@sharoni3d Hmm, can you try renaming `/Users/maya/Desktop/firebase` to something else as well?

**Comment by sharoni3d** [comment]
i think its a permission problem or i'm trying to figure out my typings script version and that gives me an error too

**Comment by sharoni3d** [comment]
Mayas-iMac:firebase maya$ typings -v
/Users/maya/.npm-packages/lib/node_modules/typings/node_modules/configstore/index.js:54
				throw err;
				^

Error: EACCES: permission denied, open '/Users/maya/.config/configstore/typings.json'
You don't have access to this file.

**Comment by sharoni3d** [comment]
@KenanY Do you have Teamviewer maybe you can help me out i'v been trying to follow tutorials and i never can because i have all these permission problem errors on the smallest stuff and i don't know what to do.

**Comment by KenanY** [comment]
@sharoni3d Nope, I don't have TeamViewer. Maybe you can try:

``` bash
$ sudo chown -R $(whoami) /Users/maya/.config/configstore/
```

which will give your user permissions for that directory.

**Comment by sharoni3d** [comment]
@KenanY Still doesn't work i get the same error

**Comment by sharoni3d** [comment]
Mayas-iMac:firebase maya$ npm install angularfire2 firebase@2.4.2 --save
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/Users/maya/.npm-packages/bin/npm" "install" "angularfire2" "firebase@2.4.2" "--save"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.5
npm ERR! code ENOSELF

npm ERR! Refusing to install firebase as a dependency of itself
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/maya/Desktop/firebase/npm-debug.log

**Comment by jimbojw** [comment]
The root cause of this issue (and many like it) is https://github.com/npm/write-file-atomic/issues/11.

There is an outstanding patch which will fix this for everyone. We're all waiting for someone from npm to accept it: https://github.com/npm/write-file-atomic/pull/13
