### ISSUE TITLE
CentOS 7 seems not happy

### ISSUE THREAD

**Issue by svkamp** [npm/npm#13504]
CentOS 7 seems not happy

```
npm http 200 https://registry.npmjs.org/schema-inspector/-/schema-inspector-1.6.4.tgz
npm http 404 https://registry.npmjs.org/marsaud/smb2-promise
npm ERR! TypeError: Cannot read property 'latest' of undefined
npm ERR!     at next (/usr/lib/node_modules/npm/lib/cache.js:687:35)
npm ERR!     at /usr/lib/node_modules/npm/lib/cache.js:675:5
npm ERR!     at saved (/usr/lib/node_modules/npm-registry-client/lib/get.js:148:7)
npm ERR!     at /usr/lib/node_modules/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:108:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.10.0-327.22.2.el7.x86_64
npm ERR! command "node" "/usr/bin/npm" "install"
npm ERR! cwd /home/dingo/xo-server
npm ERR! node -v v0.10.42
npm ERR! npm -v 1.3.6
npm ERR! type non_object_property_load
npm http 200 https://registry.npmjs.org/multikey-hash/-/multikey-hash-1.0.4.tgz
npm http 200 https://registry.npmjs.org/xo-acl-resolver/-/xo-acl-resolver-0.2.1.tgz
npm http 200 https://registry.npmjs.org/xo-collection/-/xo-collection-0.4.0.tgz
npm http 200 https://registry.npmjs.org/xen-api/-/xen-api-0.9.0.tgz
npm http 200 https://registry.npmjs.org/xo-remote-parser/-/xo-remote-parser-0.3.0.tgz
npm ERR! TypeError: Cannot read property 'latest' of undefined
npm ERR!     at next (/usr/lib/node_modules/npm/lib/cache.js:687:35)
npm ERR!     at /usr/lib/node_modules/npm/lib/cache.js:675:5
npm ERR!     at saved (/usr/lib/node_modules/npm-registry-client/lib/get.js:148:7)
npm ERR!     at /usr/lib/node_modules/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:108:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.10.0-327.22.2.el7.x86_64
npm ERR! command "node" "/usr/bin/npm" "install"
npm ERR! cwd /home/dingo/xo-server
npm ERR! node -v v0.10.42
npm ERR! npm -v 1.3.6
npm ERR! type non_object_property_load
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/dingo/xo-server/npm-debug.log
npm ERR! not ok code 0
```

**Comment by othiym23** [comment]
`npm@1` is no longer supported by the npm CLI team, having not seen any updates since 2014. I strongly recommend switching from the versions of Node and npm packaged with CentOS to the [Node|Source distributions](https://github.com/nodesource/distributions), which include either `npm@2` or `npm@3`, depending on the version of Node you install. Thanks for your time!
