### ISSUE TITLE
adduser Incorrect username or password

### ISSUE THREAD

**Issue by parikh5555** [npm/npm#13511]
info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'adduser' ]
2 info using npm@3.10.3
3 info using node@v6.3.1
4 warn Name must be lowercase
5 verbose adduser before first PUT { _id: 'org.couchdb.user:abhishek',
5 verbose adduser   name: 'abhishek',
5 verbose adduser   password: 'XXXXX',
5 verbose adduser   email: 'parikh5555@gmail.com',
5 verbose adduser   type: 'user',
5 verbose adduser   roles: [],
5 verbose adduser   date: '2016-07-28T10:43:27.950Z' }
6 verbose request uri http://registry.npmjs.org/-/user/org.couchdb.user:abhishek
7 verbose request new user, so can't send auth
8 info attempt registry request try #1 at 4:13:27 PM
9 verbose request id 8ecfdd642e7373a9
10 http request PUT http://registry.npmjs.org/-/user/org.couchdb.user:abhishek
11 http 401 http://registry.npmjs.org/-/user/org.couchdb.user:abhishek
12 verbose headers { 'content-type': 'application/json',
12 verbose headers   'cache-control': 'max-age=300',
12 verbose headers   'content-length': '46',
12 verbose headers   'accept-ranges': 'bytes',
12 verbose headers   date: 'Thu, 28 Jul 2016 10:43:30 GMT',
12 verbose headers   via: '1.1 varnish',
12 verbose headers   connection: 'keep-alive',
12 verbose headers   'x-served-by': 'cache-sin6922-SIN',
12 verbose headers   'x-cache': 'MISS',
12 verbose headers   'x-cache-hits': '0',
12 verbose headers   'x-timer': 'S1469702609.262614,VS0,VE913',
12 verbose headers   vary: 'Accept-Encoding' }
13 verbose request invalidating /home/abhi/.npm/registry.npmjs.org/-/user/org.couchdb.user_3Aabhishek on PUT
14 verbose adduser back [ { Error: Registry returned 401 for PUT on http://registry.npmjs.org/-/user/org.couchdb.user:abhishek
14 verbose adduser       at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
14 verbose adduser       at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:242:14)
14 verbose adduser       at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
14 verbose adduser       at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:200:22)
14 verbose adduser       at emitTwo (events.js:106:13)
14 verbose adduser       at Request.emit (events.js:191:7)
14 verbose adduser       at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1067:10)
14 verbose adduser       at emitOne (events.js:101:20)
14 verbose adduser       at Request.emit (events.js:188:7)
14 verbose adduser       at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:988:12) statusCode: 401, code: 'E401' },
14 verbose adduser   { ok: false, id: 'org.couchdb.user:undefined' },
14 verbose adduser   '{"ok":false,"id":"org.couchdb.user:undefined"}' ]
15 warn adduser Incorrect username or password
15 warn adduser You can reset your account by visiting:
15 warn adduser
15 warn adduser     https://npmjs.org/forgot
16 verbose stack Error: Registry returned 401 for PUT on http://registry.npmjs.org/-/user/org.couchdb.user:abhishek
16 verbose stack     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
16 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:242:14)
16 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
16 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:200:22)
16 verbose stack     at emitTwo (events.js:106:13)
16 verbose stack     at Request.emit (events.js:191:7)
16 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1067:10)
16 verbose stack     at emitOne (events.js:101:20)
16 verbose stack     at Request.emit (events.js:188:7)
16 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:988:12)
17 verbose statusCode 401
18 verbose cwd /home/abhi/Desktop/CSS_HTML/With_JS
19 error Linux 3.13.0-24-generic
20 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "adduser"
21 error node v6.3.1
22 error npm  v3.10.3
23 error code E401
24 error Registry returned 401 for PUT on http://registry.npmjs.org/-/user/org.couchdb.user:abhishek
25 error If you need help, you may report this error at:
25 error     <https://github.com/npm/npm/issues>
26 verbose exit [ 1, true ]

**Comment by parikh5555** [comment]
Needed to add user to npm first and then it can be added through registry of npm,

Thanks
Regdards
