### ISSUE TITLE
Error running npm shrinkwrap

### ISSUE THREAD

**Issue by henrytseng** [npm/npm#13526]
#### I'm opening this issue because:
- [ ] npm is crashing.
- [x] npm is producing an incorrect install.
- [ ] npm is doing something I don't understand.
- [ ] Other (_see below for feature requests_):
#### What's going wrong?

I'm also running into a similar issue.  `lodash@^3.7.0` is required by `mock-express-request@0.1.1`but it looks like we're using `lodash@^4.14.1`.  

Is not 4.14.1 > 3.7.9?  Am I missing something?  

```
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "shrinkwrap"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.3

npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! peer invalid: lodash@^3.7.0, required by mock-express-request@0.1.1
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/henry/HomeSync/CareDox/projects/caredox_api/npm-debug.log
sleepyhenry:caredox_api henry$ 
```

Relevant `package.json`

```
  "dependencies": {
    "apn": "^1.7.7",
    "bluebird": "^3.4.1",
    "body-parser": "^1.15.0",
    "busboy": "^0.2.13",
    "connect-redis": "^3.1.0",
    "cookie-parser": "^1.4.1",
    "cors": "^2.7.1",
    "debug": "^2.2.0",
    "destroy": "^1.0.4",
    "express": "^4.13.4",
    "git-rev": "^0.2.1",
    "glob": "^7.0.3",
    "helmet": "^1.3.0",
    "hiredis": "^0.4.1",
    "humps": "^1.1.0",
    "lodash": "^4.14.1",
    "methods": "^1.1.2",
    "mysql": "^2.11.1",
    "node-gcm": "^0.14.4",
    "node-inspector": "^0.12.8",
    "node-resource": "^1.2.0",
    "on-finished": "^2.3.0",
    "on-headers": "^1.0.1",
    "parseurl": "^1.3.1",
    "path-to-regexp": "^1.5.3",
    "redis": "^2.6.0-0",
    "request": "^2.69.0",
    "sequelize": "^3.23.6",
    "serve-favicon": "^2.3.0",
    "socket.io": "^1.4.6",
    "through2": "^2.0.1"
  },
```

Also have in the log:

```
...
25 warn shrinkwrap   through2: '^2.0.1' }
26 info lifecycle _api@0.0.1~shrinkwrap: _api@0.0.1
27 silly lifecycle _api@0.0.1~shrinkwrap: no script for shrinkwrap, continuing
28 verbose stack Error: Problems were encountered
28 verbose stack Please correct and try again.
28 verbose stack peer invalid: lodash@^3.7.0, required by mock-express-request@0.1.1
28 verbose stack     at shrinkwrap_ (/usr/local/lib/node_modules/npm/lib/shrinkwrap.js:118:15)
28 verbose stack     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
28 verbose stack     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
28 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
28 verbose stack     at done (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:129:5)
28 verbose stack     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:7:26)
28 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
28 verbose stack     at /usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:281:20
28 verbose stack     at FSReqWrap.oncomplete (fs.js:123:15)
29 verbose cwd /Users/henry/HomeSync/CareDox/projects/_api
30 error Darwin 15.6.0
31 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "shrinkwrap"
32 error node v6.3.0
33 error npm  v3.10.3
34 error Problems were encountered
34 error Please correct and try again.
34 error peer invalid: lodash@^3.7.0, required by mock-express-request@0.1.1
35 error If you need help, you may report this error at:
35 error     <https://github.com/npm/npm/issues>
36 verbose exit [ 1, true ]
```

**Comment by fresheneesz** [comment]
Can we please focus on fixing shrinkwrap?? This has been broken for YEARS at this point. Its embarrassing. I just ran into a situation where I wish I could be using shrinkwrap because now I don't know what dependencies I had anymore and its going to be a huge pain in the ass to figure it out. FIX SHRINKWRAP PLEASE!
