### ISSUE TITLE
error in installing browser sync

### ISSUE THREAD

**Issue by harshmeetsingh** [npm/npm#13546]
#### I'm opening this issue because:
- [ ] npm is crashing.
- [x] npm is producing an incorrect install.
- [ ] npm is doing something I don't understand.
- [ ] Other (_see below for feature requests_):
### supporting information:
- `npm -v` prints:
- `node -v` prints:
- `npm config get registry` prints:
- Windows, OS X, or Linux?:
- Network issues:
  - Geographic location where npm was run:
  - [x] I use a proxy to connect to the npm registry.
  - [x] I use a proxy to connect to the web.
  - [ ] I use a proxy when downloading Git repos.
  - [ ] I access the npm registry via a VPN
  - [ ] I don't use a proxy, but have limited or unreliable internet access.
- Container:
  - [ ] I develop using Vagrant on Windows.
  - [ ] I develop using Vagrant on OS X or Linux.
  - [ ] I develop / deploy using Docker.
  - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by harshmeetsingh** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'browser-sync' ]
2 info using npm@2.15.8
3 info using node@v4.4.7
4 verbose install initial load of C:\Users\SHIVAM\AppData\Roaming\npm\package.json
5 verbose readDependencies loading dependencies from C:\Users\SHIVAM\AppData\Roaming\npm\package.json
6 silly cache add args [ 'browser-sync', null ]
7 verbose cache add spec browser-sync
8 silly cache add parsed spec Result {
8 silly cache add   raw: 'browser-sync',
8 silly cache add   scope: null,
8 silly cache add   name: 'browser-sync',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: 'latest',
8 silly cache add   type: 'tag' }
9 silly addNamed browser-sync@latest
10 verbose addNamed "latest" is being treated as a dist-tag for browser-sync
11 info addNameTag [ 'browser-sync', 'latest' ]
12 silly mapToRegistry name browser-sync
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry data Result {
15 silly mapToRegistry   raw: 'browser-sync',
15 silly mapToRegistry   scope: null,
15 silly mapToRegistry   name: 'browser-sync',
15 silly mapToRegistry   rawSpec: '',
15 silly mapToRegistry   spec: 'latest',
15 silly mapToRegistry   type: 'tag' }
16 silly mapToRegistry uri https://registry.npmjs.org/browser-sync
17 verbose addNameTag registry:https://registry.npmjs.org/browser-sync not in flight; fetching
18 verbose request uri https://registry.npmjs.org/browser-sync
19 verbose request no auth needed
20 info attempt registry request try #1 at 12:37:00 AM
21 verbose request id ad543572032ddc27
22 http request GET https://registry.npmjs.org/browser-sync
23 info retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
24 info attempt registry request try #2 at 12:37:21 AM
25 http request GET https://registry.npmjs.org/browser-sync
26 info retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
27 info attempt registry request try #3 at 12:38:32 AM
28 http request GET https://registry.npmjs.org/browser-sync
29 verbose stack Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
29 verbose stack     at Object.exports._errnoException (util.js:873:11)
29 verbose stack     at errnoException (dns.js:32:15)
29 verbose stack     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:78:26)
30 verbose cwd C:\Users\SHIVAM
31 error Windows_NT 10.0.10586
32 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "browser-sync"
33 error node v4.4.7
34 error npm  v2.15.8
35 error code EAI_AGAIN
36 error errno EAI_AGAIN
37 error syscall getaddrinfo
38 error getaddrinfo EAI_AGAIN registry.npmjs.org:443
39 error If you need help, you may report this error at:
39 error     <https://github.com/npm/npm/issues>
40 verbose exit [ 1, true ]
