### ISSUE TITLE
npm ERR! Maximum call stack size exceeded

### ISSUE THREAD

**Issue by zwl1619** [npm/npm#13564]
I am using Laravel Elixir,   
I followed the documentation,https://laravel.com/docs/master/elixir   

There is something wrong when runing `npm install --no-bin-links`,as follow:

```
    $ npm install --no-bin-links
    npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail o                                 n node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible                                 . Use 'npm ls graceful-fs' to find it in the tree.
    npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher                                  to avoid a RegExp DoS issue
    npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher                                  to avoid a RegExp DoS issue
    npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade                                  to lodash@^4.0.0.
    npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail o                                 n node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible                                 . Use 'npm ls graceful-fs' to find it in the tree.
    npm ERR! Windows_NT 10.0.14393
    npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\dell\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "--no-bin-links"
    npm ERR! node v6.3.1
    npm ERR! npm  v3.10.5
    
    npm ERR! Maximum call stack size exceeded
    npm ERR!
    npm ERR! If you need help, you may report this error at:
    npm ERR!     <https://github.com/npm/npm/issues>
    
    npm ERR! Please include the following file with any support request:
    npm ERR!     D:\wnmp\www\laravel-5-3-demo\npm-debug.log
```

What should I do?

Edit:
npm-debug.log
```
96798 verbose stack RangeError: Maximum call stack size exceeded
96798 verbose stack     at .<anonymous> (C:\Users\dell\AppData\Roaming\npm\node_modules\npm\node_modules\npmlog\node_modules\are-we-there-yet\tracker-group.js:20:19)
96798 verbose stack     at emitThree (events.js:116:13)
96798 verbose stack     at emit (events.js:194:7)
96798 verbose stack     at .<anonymous> (C:\Users\dell\AppData\Roaming\npm\node_modules\npm\node_modules\npmlog\node_modules\are-we-there-yet\tracker-group.js:23:18)
96798 verbose stack     at emitThree (events.js:116:13)
96798 verbose stack     at emit (events.js:194:7)
96798 verbose stack     at .<anonymous> (C:\Users\dell\AppData\Roaming\npm\node_modules\npm\node_modules\npmlog\node_modules\are-we-there-yet\tracker-group.js:23:18)
96798 verbose stack     at emitThree (events.js:116:13)
96798 verbose stack     at emit (events.js:194:7)
96798 verbose stack     at .<anonymous> (C:\Users\dell\AppData\Roaming\npm\node_modules\npm\node_modules\npmlog\node_modules\are-we-there-yet\tracker-group.js:23:18)
96799 verbose cwd D:\wnmp\www\laravel-5-3-demo
96800 error Windows_NT 10.0.14393
96801 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\dell\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "--no-bin-links"
96802 error node v6.3.1
96803 error npm  v3.10.5
96804 error Maximum call stack size exceeded
96805 error If you need help, you may report this error at:
96805 error     <https://github.com/npm/npm/issues>
96806 verbose exit [ 1, true ]
```

**Comment by evocateur** [comment]
>     npm ERR! Please include the following file with any support request:
    npm ERR!     D:\wnmp\www\laravel-5-3-demo\npm-debug.log

That's the first step.

**Comment by zwl1619** [comment]
@evocateur   
I add the `npm-debug.log`.

**Comment by Waicung** [comment]
I got the same issue on my Ubuntu PC. With the similar circumstance, I encountered it trying to run Laravel Elixir.
https://laravel.com/docs/5.3/elixir#working-with-stylesheets

$ npm install --no-bin-links
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm ERR! Linux 4.4.0-31-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "--no-bin-links"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3

npm ERR! Maximum call stack size exceeded
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/will/tmp/auth/npm-debug.log
