### ISSUE TITLE
Getting Error: Cannot find module 'readable-stream' , when tried to run protractor conf file

### ISSUE THREAD

**Issue by kumarvishalvishnoi** [npm/npm#13573]
When I'm trying to run **protractor conf.js** command 

Getting the below error:

[16:54:02] E/launcher - Error: Error: Cannot find module 'readable-stream'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Protractor\Hub_Desktop_Automation\node_modules\pro
tractor\node_modules\mysql\lib\protocol\sequences\Query.js:7:20)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
[16:54:02] E/launcher - Process exited with error code 100

Any solution for that please. ?

**Comment by redcherry999** [comment]
hello sir ,

**i'm also getting same error**


module.js:327
    throw err;
    ^

Error: Cannot find module 'readable-stream'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/root/aws_nodejs/node_modules/aws-iot-device-sdk/node_modules/mqtt/lib/store.js:2:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

**Comment by legodude17** [comment]
@kumarvishalvishnoi how is that related to `npm`?

@redcherry999 Try reinstalling `npm`.
