### ISSUE TITLE
npm login doesn't send password

### ISSUE THREAD

**Issue by jorio2311** [npm/npm#13596]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [X ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
If I'm trying to login `npm login` and type in my user credentials, i get an error that a password is required.

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'login' ]
2 info using npm@1.3.10
3 info using node@v0.10.25
4 verbose adduser before first PUT { name: 'imanowl',
4 verbose adduser   salt: 'XXXXX',
4 verbose adduser   password_sha: 'XXXXX',
4 verbose adduser   email: 'oliver@czempas.de',
4 verbose adduser   _id: 'org.couchdb.user:imanowl',
4 verbose adduser   type: 'user',
4 verbose adduser   roles: [],
4 verbose adduser   date: '2016-08-06T12:33:32.258Z' }
5 verbose url raw /-/user/org.couchdb.user:imanowl
6 verbose url resolving [ 'https://registry.npmjs.org/',
6 verbose url resolving   './-/user/org.couchdb.user:imanowl' ]
7 verbose url resolved https://registry.npmjs.org/-/user/org.couchdb.user:imanowl
8 info trying registry request attempt 1 at 14:33:32
9 http PUT https://registry.npmjs.org/-/user/org.couchdb.user:imanowl
10 http 400 https://registry.npmjs.org/-/user/org.couchdb.user:imanowl
11 verbose adduser back [ [Error: ValidationError: child "password" fails because ["password" is required] : -/user/org.couchdb.user:imanowl],
11 verbose adduser   { ok: false,
11 verbose adduser     error: 'ValidationError: child "password" fails because ["password" is required]' },
11 verbose adduser   '{"ok":false,"error":"ValidationError: child \\"password\\" fails because [\\"password\\" is required]"}' ]
12 error Error: ValidationError: child "password" fails because ["password" is required] : -/user/org.couchdb.user:imanowl
12 error     at RegClient.<anonymous> (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:272:14)
12 error     at Request.self.callback (/usr/lib/nodejs/request/index.js:148:22)
12 error     at Request.EventEmitter.emit (events.js:98:17)
12 error     at Request.<anonymous> (/usr/lib/nodejs/request/index.js:896:14)
12 error     at Request.EventEmitter.emit (events.js:117:20)
12 error     at IncomingMessage.<anonymous> (/usr/lib/nodejs/request/index.js:847:12)
12 error     at IncomingMessage.EventEmitter.emit (events.js:117:20)
12 error     at _stream_readable.js:920:16
12 error     at process._tickCallback (node.js:415:13)
13 error If you need help, you may report this log at:
13 error     <http://github.com/isaacs/npm/issues>
13 error or email it to:
13 error     <npm-@googlegroups.com>
14 error System Linux 3.13.0-32-generic
15 error command "/usr/bin/nodejs" "/usr/bin/npm" "login"
16 error cwd /home/oliver/PTC-Creator
17 error node -v v0.10.25
18 error npm -v 1.3.10
19 verbose exit [ 1, true ]

### supporting information:

 - `npm -v` prints: 1.3.10
 - `node -v` prints: v0.10.25
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X, or Linux?: Linux
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [X ] I don't use a proxy, but have limited or unreliable internet access.

**Comment by jorio2311** [comment]
Update to the newest version
