### ISSUE TITLE
npm start 

### ISSUE THREAD

**Issue by ketan0781** [npm/npm#13629]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\sfkmp\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.10.5
3 info using node@v4.4.7
4 verbose stack Error: missing script: start
4 verbose stack     at run (C:\Users\sfkmp\AppData\Roaming\npm\node_modules\npm\lib\run-script.js:151:19)
4 verbose stack     at C:\Users\sfkmp\AppData\Roaming\npm\node_modules\npm\lib\run-script.js:61:5
4 verbose stack     at C:\Users\sfkmp\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:356:5
4 verbose stack     at checkBinReferences_ (C:\Users\sfkmp\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:320:45)
4 verbose stack     at final (C:\Users\sfkmp\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:354:3)
4 verbose stack     at then (C:\Users\sfkmp\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:124:5)
4 verbose stack     at ReadFileContext.<anonymous> (C:\Users\sfkmp\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:295:20)
4 verbose stack     at ReadFileContext.callback (C:\Users\sfkmp\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16)
4 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:303:13)
5 verbose cwd C:\Users\sfkmp\Desktop\Tem FolderX\JSON_jquery
6 error Windows_NT 6.1.7601
7 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\sfkmp\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
8 error node v4.4.7
9 error npm  v3.10.5
10 error missing script: start
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@ketan0781 

```
4 verbose stack Error: missing script: start
```

Do you have a `"start"` script defined in your `package.json`?
