### ISSUE TITLE
npm v3.10.7 returns Warning: Possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by 5amfung** [npm/npm#13656]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?

Running `npm install` has the following warning:

```
(node:28472) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
```

This is reproducible from two different projects.

#### How can the CLI team reproduce the problem?

Run `npm install`

### supporting information:

 - `npm -v` prints:

3.10.7

 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X, or Linux?:

OS X

 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by othiym23** [comment]
Reproducible by running 

```shell
ogd@bauchelain ~/D/projects> clone https://github.com/othiym23/packard.git
ogd@bauchelain ~/D/projects> cd packard && npm it
(node:47458) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:47458) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:47458) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:47458) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:47458) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:47458) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:47458) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:47458) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:47458) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:47458) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:47458) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:47458) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:47458) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:47458) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:47458) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:47458) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:47458) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:47458) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:47458) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:47458) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:47458) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
# … more
ogd@bauchelain ~/D/p/packard> node -v
v6.3.1
ogd@bauchelain ~/D/p/packard> npm -v
3.10.7
```

It seems likely, according to @iarna, that this is due to a change in a dependency, because nothing has changed in the CLI's own error handling.

**Comment by KenanY** [comment]
The least I could do was a `git bisect`:

```
9b88cb89f138443f324094685f4de073f33ecef0 is the first bad commit
commit 9b88cb89f138443f324094685f4de073f33ecef0
Author: Zach Renner
Date:   Tue Jul 19 17:44:23 2016 -0700

    request@2.74.0
    
    Update request library to at least 2.73 to fix:
    npm install failed - Cannot read property 'emit' of null
    
    Fixes: #9984
    PR-URL: https://github.com/npm/npm/pull/13432
    Credit: @zarenner
    Reviewed-By: @iarna

:040000 040000 88f5e97c37f8deadff7e2c737521e009119583ab 5401459bc1979b6bb27a5ecb5304ab4562a93cac M	node_modules
:100644 100644 ef5c7864ce2027e881b2eee2e8ac95255d3651a1 9a2b930bb837b7f9e1d1a973a76bb97fed383d18 M	package.json
```

**Comment by othiym23** [comment]
That confirms what I was just seeing when running at a higher log level. I'll see if I can reduce it down to a minimal case to determine whether the problem is in `request` or npm. Thanks, @KenanY!

**Comment by eventengine** [comment]
#fuck_it3_10_7! :((

**Comment by uripre** [comment]
+1

**Comment by mhart** [comment]
Any news on this? Also happening with v2.15.10 – `npm install ember-cli` seems to reproduce pretty easily too.

**Comment by mhart** [comment]
Ah, I see: https://github.com/request/request/issues/2215 – will ask over there – getting pages and pages of these warnings

**Comment by mhart** [comment]
Actually, maybe it's not request, but rather `npm-registry-client`? Getting a bit hard to track down which issue to follow: https://github.com/npm/npm-registry-client/pull/142

**Comment by ahoymajo** [comment]
Hello, I also get a warning **"(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit."** when trying to create a new foundation project. Don't know how to fix it. I'm not sure what's causing this problem.

**Comment by mhart** [comment]
@ahoymajo you can just ignore the warnings – it's not an error with anything you've done, it's just one of npm's pieces that needs updating and then the warning will go away.

**Comment by ahoymajo** [comment]
@mhart oh so it's on npm. Thank you so much. Maybe i'll just wait for their update.

**Comment by cescoferraro** [comment]
For those seeing this error:

`npm update -g npm` installs 3.10.7 again

`npm install -g npm@3.10.8` install the newer version that solved the problem for me

**Comment by zkat** [comment]
`npm@3.10.8` is now `latest`, so `npm install -g npm@latest` should be enough now.

**Comment by superclarkk** [comment]
Confirmed - `npm install -g npm` resolves this issue.

**Comment by superclarkk** [comment]
Confirmed - `npm install -g npm` now installs `3.10.8`, which resolves this issue.

**Comment by arthurwdev** [comment]
@superclarkk work for me 👍 
Tks!

**Comment by fayeyen** [comment]
3.10.8 cause another error

**Comment by fayeyen** [comment]
3.10.8 
cause error of
npm ERR! uid must be an unsigned int
see
https://github.com/npm/npm/issues/14076
so i roll back to node.js v6.7.0  came with npm 3.10.3
https://nodejs.org/en/
stable version, it solved both problems

**Comment by addaleax** [comment]
@fayeyen That should work, yes. You can update to npm@3.10.9, too, the “uid must be an unsigned int” bug is fixed in there.

**Comment by feryardiant** [comment]
Just got this issue on nodejs v6.8.1 with npm@4.0.2 on Windows 10 64 bit.

**Comment by addaleax** [comment]
@feryardiant are you sure? can you post a bit more info on what you were trying/doing, a way to reproduce, or generally something in that direction?

**Comment by feryardiant** [comment]
Hi @addaleax,

Thanks for fast response. Currently I'm working on static web project using metalsmith and gulp, here my `devDependencies`:

```json
...
{
  "babel-preset-es2015-node6": "^0.4.0",
  "browser-sync": "^2.16.0",
  "del": "^2.2.2",
  "gulp": "^3.9.1",
  "gulp-autoprefixer": "^3.1.1",
  "gulp-babel": "^6.1.2",
  "gulp-changed": "^1.3.2",
  "gulp-clean-css": "^2.0.13",
  "gulp-imagemin": "^3.0.3",
  "gulp-load-plugins": "^1.3.0",
  "gulp-metalsmith": "^1.0.0",
  "gulp-sass": "^2.3.2",
  "gulp-uglify": "^2.0.0",
  "gulp-util": "^3.0.7",
  "handlebars": "^4.0.5",
  "handlebars-helpers": "^0.7.5",
  "handlebars-layouts": "^3.1.4",
  "i18n": "^0.8.3",
  "metalsmith": "^2.3.0",
  "metalsmith-assets": "^0.1.0",
  "metalsmith-collection-metadata": "^0.1.0",
  "metalsmith-collections": "^0.9.0",
  "metalsmith-in-place": "^1.4.4",
  "metalsmith-layouts": "^1.7.0",
  "metalsmith-markdown": "^0.2.1",
  "metalsmith-metadata-directory": "^1.0.0",
  "metalsmith-multi-language": "^0.2.0",
  "metalsmith-permalinks": "^0.5.0",
  "metalsmith-register-helpers": "^0.2.0",
  "run-sequence": "^1.2.2"
}
```

and here short of my `gulpfile.js`
```js
const gulp = require('gulp');

// load all plugins with prefix 'gulp'
const $ = require('gulp-load-plugins')();

const sequence = require('run-sequence');
const browserSync = require('browser-sync');

// Load build helpers
const _ = require('./build/helpers')(gulp, browserSync);

const config = {
    autoprefix: {
        browsers: ['> 1%', 'last 10 versions', 'Firefox ESR', 'Opera 12.1']
    },
    babel: {
        presets: ['es2015-node6']
    },
    uglify: {
        compress: {},
        preserveComments: 'license'
    }
};

/* Task: Compile SCSS
 --------------------------------------------------------------------------------- */

gulp.task('build:styles', () => {
    const styles = _.paths.styles;

    const stream = gulp.src(styles.src)
        .pipe($.sass({outputStyle: 'compact'}).on('error', $.sass.logError))
        .pipe($.autoprefixer(config.autoprefix));

    if (_.env === 'production') {
        stream.pipe($.cleanCss()).on('error', _.logErrors);
    }

    return stream
        .pipe(gulp.dest(styles.dest))
        .pipe(browserSync.stream());
});

/* Task: Minify JS
 --------------------------------------------------------------------------------- */

gulp.task('build:scripts', () => {
    const stream = gulp.src(_.paths.scripts.src);
        // .pipe($.babel(config.babel))
        // .on('error', _.logErrors);

    if (_.env === 'production') {
        stream.pipe($.uglify(config.uglify)).on('error', _.logErrors);
    }

    return stream
        .pipe(gulp.dest(_.paths.scripts.dest))
        .pipe(browserSync.stream());
});

/* Task: Optimize image
 --------------------------------------------------------------------------------- */

gulp.task('build:images', () => {
    const stream = gulp.src( _.paths.images.src)
        .pipe($.changed(_.paths.images.dest));

    if (_.env === 'production') {
        stream.pipe($.imagemin({progressive: true})).on('error', _.logErrors);
    }

    return stream
        .pipe(gulp.dest(_.paths.images.dest))
        .pipe(browserSync.stream());
});

/* Task: Build all (run sequencialy)
 --------------------------------------------------------------------------------- */

gulp.task('build', ['build:pages'], (done) => {
    sequence('build:styles', 'build:scripts', 'build:images', done);
});
```

the warning only appeared when I run `gulp --production`

```
# feryardiant in /Project/web/static on git:metalsmith ●
[8:48:02] → gulp --production
[08:48:06] Using gulpfile D:\Workspaces\Projects\web\static\gulpfile.js
[08:48:06] Starting 'default'...
[08:48:06] Starting 'clean'...
[08:48:06] Assets directory cleaned
[08:48:06] Finished 'clean' after 217 ms
[08:48:06] Starting 'build:pages'...
[08:48:08] Finished 'build:pages' after 2.03 s
[08:48:08] Starting 'build'...
[08:48:08] Starting 'build:styles'...
[08:48:09] Finished 'build:styles' after 845 ms
[08:48:09] Starting 'build:scripts'...
[08:48:11] Finished 'build:scripts' after 2.56 s
[08:48:11] Starting 'build:images'...
(node:11700) Warning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit
[08:48:12] Finished 'build:images' after 699 ms
[08:48:12] Starting 'build:fonts'...
[08:48:12] Finished 'build:fonts' after 38 ms
[08:48:12] Finished 'build' after 4.14 s
[08:48:12] Finished 'default' after 6.39 s
```

Initialy I thought it was gulp-imagemin issue but sindresorhus/gulp-imagemin#210 say otherwise, that's why I post it here.

Any thoughts?

**Comment by addaleax** [comment]
@feryardiant This doesn’t look like it’s an issue with npm or Node; you can probably get a reasonable stack trace by running gulp as `node --trace-warning $(which gulp) --production` (works with Node v6+), which should show you where the problem comes from.

If that doesn’t help or doesn’t work for you, you might be better off trying this at https://github.com/nodejs/help?

**Comment by feryardiant** [comment]
Thanks for advices, just tried your suggestion, but

```
# feryardiant in /Project/web/static on git:metalsmith ●
[8:48:15] → node --trace-warning $(which gulp) --production
C:\Program Files\nodejs\node.exe: bad option: --trace-warning
```

ah, it should be `--trace-warnings` right? but another issue appeared. 

```
[9:02:18] → node --trace-warnings `which gulp` --production
module.js:471
    throw err;
    ^

Error: Cannot find module 'D:\cygdrive\c\Users\feryardiant\AppData\Roaming\npm\gulp'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

Anyway, I have another things to do now and I'll back to you soon.

**Comment by feryardiant** [comment]
One more thing, I have no issue on my CI using npm@3.10.8 node@v6.9.1

**Comment by feryardiant** [comment]
Well, tried using powershell and I got this.

```
PS D:\Workspaces\Projects\web\static> node --trace-warnings .\node_modules\gulp\bin\gulp.js --production
[13:47:56] Using gulpfile D:\Workspaces\Projects\web\static\gulpfile.js
[13:47:56] Starting 'default'...
[13:47:56] Starting 'clean'...
[13:47:57] Assets directory cleaned
[13:47:57] Finished 'clean' after 234 ms
[13:47:57] Starting 'build:pages'...
[13:47:59] Finished 'build:pages' after 2.09 s
[13:47:59] Starting 'build'...
[13:47:59] Starting 'build:styles'...
[13:48:00] Finished 'build:styles' after 882 ms
[13:48:00] Starting 'build:scripts'...
[13:48:02] Finished 'build:scripts' after 2.59 s
[13:48:02] Starting 'build:images'...
(node:4876) Warning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:259:19)
    at EventEmitter.addListener (events.js:275:10)
    at module.exports (D:\Workspaces\Projects\web\static\node_modules\signal-exit\index.js:41:11)
    at module.exports.err (D:\Workspaces\Projects\web\static\node_modules\execa\index.js:146:23)
    at fsP.writeFile.then (D:\Workspaces\Projects\web\static\node_modules\exec-buffer\index.js:35:15)
[13:48:04] Finished 'build:images' after 1.26 s
[13:48:04] Starting 'build:fonts'...
[13:48:04] Finished 'build:fonts' after 128 ms
[13:48:04] Finished 'build' after 4.87 s
[13:48:04] Finished 'default' after 7.2 s
```

**Comment by itslenny** [comment]
I'm seeing the same issue while running a webserver with browser sync. It was working fine a few days ago and suddenly started throwing this error:

```
> npm -v
3.10.8
> node -v
v6.9.1
> gulp webserver

[15:53:17] Starting 'webserver'...
gulp : (node:8100) Warning: Possible EventEmitter memory leak detected. 11 close listeners added. Use emitter.setMaxListeners() to increase limit
At line:1 char:1
+ gulp webserver
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: ((node:8100) War... increase limit:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```

**Comment by KenanY** [comment]
@itslenny That's a different issue, since it doesn't seem to involve `npm` at all.

**Comment by feryardiant** [comment]
@addaleax just wanna confirm that my issue above only happen on windows. Now I'm using ubuntu 16.04 with exact same npm version and had no issue whatsoever.

**Comment by addaleax** [comment]
@feryardiant see https://github.com/sindresorhus/execa/issues/61 :) updating your dependencies might help :)

**Comment by chilly** [comment]
npm -v
3.10.10

still has the problem.
