### ISSUE TITLE
412: Error parsing JSON

### ISSUE THREAD

**Issue by shaunwarman** [npm/npm#13676]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [X] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'express' ]
2 info using npm@3.9.3
3 info using node@v6.2.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData express
8 silly fetchNamedPackageData express
9 silly mapToRegistry name express
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://npm.paypal.com/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'express',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   name: 'express',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://npm.paypal.com/express
14 verbose request uri https://npm.paypal.com/express
15 verbose request no auth needed
16 info attempt registry request try #1 at 6:33:10 PM
17 verbose request id a9a4e66af35b201c
18 http request GET https://npm.paypal.com/express
19 http 412 https://npm.paypal.com/express
20 verbose bad json <?xml version="1.0" encoding="utf-8"?>
20 verbose bad json <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
20 verbose bad json  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
20 verbose bad json <html>
20 verbose bad json   <head>
20 verbose bad json     <title>412 Precondition Failed</title>
20 verbose bad json   </head>
20 verbose bad json   <body>
20 verbose bad json     <h1>Error 412 Precondition Failed</h1>
20 verbose bad json     <p>Precondition Failed</p>
20 verbose bad json     <h3>Guru Mediation:</h3>
20 verbose bad json     <p>Details: cache-lax1434-LAX 1471303990 3225914924</p>
20 verbose bad json     <hr>
20 verbose bad json     <p>Varnish cache server</p>
...skipping...
30 verbose stack     <p>Details: cache-lax1434-LAX 1471303990 3225914924</p>
30 verbose stack     <hr>
30 verbose stack     <p>Varnish cache server</p>
30 verbose stack   </body>
30 verbose stack </html>
30 verbose stack
30 verbose stack     at Object.parse (native)
30 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:199:23)
30 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:178:7
30 verbose stack     at Gunzip.onEnd (zlib.js:227:5)
30 verbose stack     at emitNone (events.js:91:20)
30 verbose stack     at Gunzip.emit (events.js:185:7)
30 verbose stack     at endReadableNT (_stream_readable.js:926:12)
30 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:74:11)
30 verbose stack     at process._tickCallback (internal/process/next_tick.js:98:9)
31 verbose cwd /Users/swarman/Development/Source/nodeopsdashboard
32 error Darwin 15.5.0
33 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "express"
34 error node v6.2.1
35 error npm  v3.9.3
36 error Unexpected token < in JSON at position 1
36 error
36 error <?xml version="1.0" encoding="utf-8"?>
36 error <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
36 error  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
36 error <html>
36 error   <head>
36 error     <title>412 Precondition Failed</title>
36 error   </head>
36 error   <body>
36 error     <h1>Error 412 Precondition Failed</h1>
36 error     <p>Precondition Failed</p>
36 error     <h3>Guru Mediation:</h3>
36 error     <p>Details: cache-lax1434-LAX 1471303990 3225914924</p>
36 error     <hr>
36 error     <p>Varnish cache server</p>
36 error   </body>
36 error </html>
37 error If you need help, you may report this error at:
37 error     <https://github.com/npm/npm/issues>
38 verbose exit [ 1, true ]
...skipping...
30 verbose stack     <p>Details: cache-lax1434-LAX 1471303990 3225914924</p>
30 verbose stack     <hr>
30 verbose stack     <p>Varnish cache server</p>
30 verbose stack   </body>
30 verbose stack </html>
30 verbose stack
30 verbose stack     at Object.parse (native)
30 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:199:23)
30 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:178:7
30 verbose stack     at Gunzip.onEnd (zlib.js:227:5)
30 verbose stack     at emitNone (events.js:91:20)
30 verbose stack     at Gunzip.emit (events.js:185:7)
30 verbose stack     at endReadableNT (_stream_readable.js:926:12)
30 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:74:11)
30 verbose stack     at process._tickCallback (internal/process/next_tick.js:98:9)
31 verbose cwd /Users/swarman/Development/Source/nodeopsdashboard
32 error Darwin 15.5.0
33 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "express"
34 error node v6.2.1
35 error npm  v3.9.3
36 error Unexpected token < in JSON at position 1
36 error
36 error <?xml version="1.0" encoding="utf-8"?>
36 error <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
36 error  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
36 error <html>
36 error   <head>
36 error     <title>412 Precondition Failed</title>
36 error   </head>
36 error   <body>
36 error     <h1>Error 412 Precondition Failed</h1>
36 error     <p>Precondition Failed</p>
36 error     <h3>Guru Mediation:</h3>
36 error     <p>Details: cache-lax1434-LAX 1471303990 3225914924</p>
36 error     <hr>
36 error     <p>Varnish cache server</p>
36 error   </body>
36 error </html>
37 error If you need help, you may report this error at:
37 error     <https://github.com/npm/npm/issues>
38 verbose exit [ 1, true ]
 ESCOD
30 verbose stack     <p>Precondition Failed</p>
30 verbose stack     <h3>Guru Mediation:</h3>
30 verbose stack     <p>Details: cache-lax1434-LAX 1471303990 3225914924</p>
30 verbose stack     <hr>
30 verbose stack     <p>Varnish cache server</p>
30 verbose stack   </body>
30 verbose stack </html>
30 verbose stack
30 verbose stack     at Object.parse (native)
30 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:199:23)
30 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:178:7
30 verbose stack     at Gunzip.onEnd (zlib.js:227:5)
30 verbose stack     at emitNone (events.js:91:20)
30 verbose stack     at Gunzip.emit (events.js:185:7)
30 verbose stack     at endReadableNT (_stream_readable.js:926:12)
30 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:74:11)
30 verbose stack     at process._tickCallback (internal/process/next_tick.js:98:9)
31 verbose cwd /Users/swarman/Development/Source/nodeopsdashboard
32 error Darwin 15.5.0
33 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "express"
34 error node v6.2.1
35 error npm  v3.9.3
36 error Unexpected token < in JSON at position 1
36 error
36 error <?xml version="1.0" encoding="utf-8"?>
36 error <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
36 error  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
36 error <html>
36 error   <head>
36 error     <title>412 Precondition Failed</title>
36 error   </head>
36 error   <body>
36 error     <h1>Error 412 Precondition Failed</h1>
36 error     <p>Precondition Failed</p>
36 error     <h3>Guru Mediation:</h3>
36 error     <p>Details: cache-lax1434-LAX 1471303990 3225914924</p>
36 error     <hr>
36 error     <p>Varnish cache server</p>
36 error   </body>
36 error </html>
37 error If you need help, you may report this error at:
```

### supporting information:

 - `npm -v` prints: 3.9.3
 - `node -v` prints: 6.2.1
 - `npm config get registry` prints: http://npm.paypal.com
 - Windows, OS X, or Linux?: OS X
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by shaunwarman** [comment]
```
LM-AST-00873729:nodeopsdashboard swarman$ curl -kv http://npm.paypal.com/express
*   Trying 10.24.0.35...
* Connected to npm.paypal.com (10.24.0.35) port 80 (#0)
> GET /express HTTP/1.1
> Host: npm.paypal.com
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 412 Precondition Failed
< content-type: text/html; charset=utf-8
< x-registry: https://registry.npmjs.org/
< server: Varnish
< retry-after: 0
< accept-ranges: bytes
< via: 1.1 varnish
< connection: close
< x-served-by: cache-den6020-DEN
< x-cache: MISS
< x-cache-hits: 0
< x-timer: S1471309231.770599,VS0,VE0
< content-length: 451
< cache-control: no-cache
< Date: Tue, 16 Aug 2016 01:00:31 GMT
<

<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
  <head>
    <title>412 Precondition Failed</title>
  </head>
  <body>
    <h1>Error 412 Precondition Failed</h1>
    <p>Precondition Failed</p>
    <h3>Guru Mediation:</h3>
    <p>Details: cache-den6020-DEN 1471309231 2113133502</p>
    <hr>
    <p>Varnish cache server</p>
  </body>
</html>
```

**Comment by shaunwarman** [comment]
Our proxy (kappa) seems to redirect to public npm and hit a varnish server error. It looks like even a simple curl (even from within docker container) causes the above issue.

**Comment by soldair** [comment]
hey @shaunwarman 
we did have to block your ips as you caused http://status.npmjs.org/incidents/jctvmddlynsx
I'll see what we can do to get you going again.

**Comment by shaunwarman** [comment]
Thanks, Ryan. Please keep me updated! And let me know what I can do.

**Comment by soldair** [comment]
@shaunwarman should be good now. =)

In the future for issues with the registry itself not the cli use this issue tracker if you can https://github.com/npm/registry/issues

**Comment by shaunwarman** [comment]
Thanks Ryan! Looks like we are back in business. Will follow up offline.
