### ISSUE TITLE
Dependencies not installing

### ISSUE THREAD

**Issue by fieldcommandergraeme** [npm/npm#13685]
#### I'm opening this issue because:
npm is not installing 

#### What's going wrong?
Running restore packages in visual studio is not solving the problem.
I have tried running npm install -g cordova ionic in CMD but no luck. I suspect the problem is due to being behind a corporate proxy but  I have yet to find a solution for my problem.

 - Windows, OS X, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.

Output log below:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Web\\External\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Web\\External\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@3.3.4
3 info using node@v5.4.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly install normalizeTree
8 silly loadCurrentTree Finishing
9 silly loadIdealTree Starting
10 silly install loadIdealTree
11 silly cloneCurrentTree Starting
12 silly install cloneCurrentTreeToIdealTree
13 silly cloneCurrentTree Finishing
14 silly loadShrinkwrap Starting
15 silly install loadShrinkwrap
16 silly loadShrinkwrap Finishing
17 silly loadAllDepsIntoIdealTree Starting
18 silly install loadAllDepsIntoIdealTree
19 silly fetchNamedPackageData gulp
20 silly mapToRegistry name gulp
21 silly mapToRegistry using default registry
22 silly mapToRegistry registry https://registry.npmjs.org/
23 silly mapToRegistry uri https://registry.npmjs.org/gulp
24 silly fetchNamedPackageData gulp-sass
25 silly mapToRegistry name gulp-sass
26 silly mapToRegistry using default registry
27 silly mapToRegistry registry https://registry.npmjs.org/
28 silly mapToRegistry uri https://registry.npmjs.org/gulp-sass
29 silly fetchNamedPackageData gulp-concat
30 silly mapToRegistry name gulp-concat
31 silly mapToRegistry using default registry
32 silly mapToRegistry registry https://registry.npmjs.org/
33 silly mapToRegistry uri https://registry.npmjs.org/gulp-concat
34 silly fetchNamedPackageData gulp-minify-css
35 silly mapToRegistry name gulp-minify-css
36 silly mapToRegistry using default registry
37 silly mapToRegistry registry https://registry.npmjs.org/
38 silly mapToRegistry uri https://registry.npmjs.org/gulp-minify-css
39 silly fetchNamedPackageData gulp-rename
40 silly mapToRegistry name gulp-rename
41 silly mapToRegistry using default registry
42 silly mapToRegistry registry https://registry.npmjs.org/
43 silly mapToRegistry uri https://registry.npmjs.org/gulp-rename
44 verbose request uri https://registry.npmjs.org/gulp
45 verbose request no auth needed
46 info attempt registry request try #1 at 11:42:03 AM
47 verbose request id ea42ded87a6f219f
48 http request GET https://registry.npmjs.org/gulp
49 verbose request uri https://registry.npmjs.org/gulp-sass
50 verbose request no auth needed
51 info attempt registry request try #1 at 11:42:03 AM
52 http request GET https://registry.npmjs.org/gulp-sass
53 verbose request uri https://registry.npmjs.org/gulp-concat
54 verbose request no auth needed
55 info attempt registry request try #1 at 11:42:03 AM
56 http request GET https://registry.npmjs.org/gulp-concat
57 verbose request uri https://registry.npmjs.org/gulp-minify-css
58 verbose request no auth needed
59 info attempt registry request try #1 at 11:42:03 AM
60 http request GET https://registry.npmjs.org/gulp-minify-css
61 verbose request uri https://registry.npmjs.org/gulp-rename
62 verbose request no auth needed
63 info attempt registry request try #1 at 11:42:04 AM
64 http request GET https://registry.npmjs.org/gulp-rename
65 info retry will retry, error on last attempt: Error: write EPROTO
66 info retry will retry, error on last attempt: Error: write EPROTO
67 info retry will retry, error on last attempt: Error: write EPROTO
68 info retry will retry, error on last attempt: Error: write EPROTO
69 info retry will retry, error on last attempt: Error: write EPROTO
70 info attempt registry request try #2 at 11:42:14 AM
71 http request GET https://registry.npmjs.org/gulp-concat
72 info attempt registry request try #2 at 11:42:14 AM
73 http request GET https://registry.npmjs.org/gulp-minify-css
74 info attempt registry request try #2 at 11:42:14 AM
75 http request GET https://registry.npmjs.org/gulp
76 info attempt registry request try #2 at 11:42:14 AM
77 http request GET https://registry.npmjs.org/gulp-rename
78 info attempt registry request try #2 at 11:42:14 AM
79 http request GET https://registry.npmjs.org/gulp-sass
80 info retry will retry, error on last attempt: Error: write EPROTO
81 info retry will retry, error on last attempt: Error: write EPROTO
82 info retry will retry, error on last attempt: Error: write EPROTO
83 info retry will retry, error on last attempt: Error: write EPROTO
84 info retry will retry, error on last attempt: Error: write EPROTO
85 info attempt registry request try #3 at 11:43:14 AM
86 http request GET https://registry.npmjs.org/gulp-minify-css
87 info attempt registry request try #3 at 11:43:14 AM
88 http request GET https://registry.npmjs.org/gulp-concat
89 info attempt registry request try #3 at 11:43:14 AM
90 http request GET https://registry.npmjs.org/gulp-rename
91 info attempt registry request try #3 at 11:43:14 AM
92 http request GET https://registry.npmjs.org/gulp
93 info attempt registry request try #3 at 11:43:14 AM
94 http request GET https://registry.npmjs.org/gulp-sass
95 silly fetchPackageMetaData Error: write EPROTO
95 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:856:11)
95 silly fetchPackageMetaData     at exports._exceptionWithHostPort (util.js:879:20)
95 silly fetchPackageMetaData     at WriteWrap.afterWrite (net.js:763:14)
95 silly fetchPackageMetaData  error for gulp-sass@^2.0.4 { [Error: write EPROTO]
95 silly fetchPackageMetaData   code: 'EPROTO',
95 silly fetchPackageMetaData   errno: 'EPROTO',
95 silly fetchPackageMetaData   syscall: 'write',
95 silly fetchPackageMetaData   address: undefined }
96 silly fetchPackageMetaData Error: write EPROTO
96 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:856:11)
96 silly fetchPackageMetaData     at exports._exceptionWithHostPort (util.js:879:20)
96 silly fetchPackageMetaData     at WriteWrap.afterWrite (net.js:763:14)
96 silly fetchPackageMetaData  error for gulp-minify-css@^0.3.0 { [Error: write EPROTO]
96 silly fetchPackageMetaData   code: 'EPROTO',
96 silly fetchPackageMetaData   errno: 'EPROTO',
96 silly fetchPackageMetaData   syscall: 'write',
96 silly fetchPackageMetaData   address: undefined }
97 silly fetchPackageMetaData Error: write EPROTO
97 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:856:11)
97 silly fetchPackageMetaData     at exports._exceptionWithHostPort (util.js:879:20)
97 silly fetchPackageMetaData     at WriteWrap.afterWrite (net.js:763:14)
97 silly fetchPackageMetaData  error for gulp-rename@^1.2.0 { [Error: write EPROTO]
97 silly fetchPackageMetaData   code: 'EPROTO',
97 silly fetchPackageMetaData   errno: 'EPROTO',
97 silly fetchPackageMetaData   syscall: 'write',
97 silly fetchPackageMetaData   address: undefined }
98 silly fetchPackageMetaData Error: write EPROTO
98 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:856:11)
98 silly fetchPackageMetaData     at exports._exceptionWithHostPort (util.js:879:20)
98 silly fetchPackageMetaData     at WriteWrap.afterWrite (net.js:763:14)
98 silly fetchPackageMetaData  error for gulp-concat@^2.2.0 { [Error: write EPROTO]
98 silly fetchPackageMetaData   code: 'EPROTO',
98 silly fetchPackageMetaData   errno: 'EPROTO',
98 silly fetchPackageMetaData   syscall: 'write',
98 silly fetchPackageMetaData   address: undefined }
99 silly fetchPackageMetaData Error: write EPROTO
99 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:856:11)
99 silly fetchPackageMetaData     at exports._exceptionWithHostPort (util.js:879:20)
99 silly fetchPackageMetaData     at WriteWrap.afterWrite (net.js:763:14)
99 silly fetchPackageMetaData  error for gulp@^3.5.6 { [Error: write EPROTO]
99 silly fetchPackageMetaData   code: 'EPROTO',
99 silly fetchPackageMetaData   errno: 'EPROTO',
99 silly fetchPackageMetaData   syscall: 'write',
99 silly fetchPackageMetaData   address: undefined }
100 silly rollbackFailedOptional Starting
101 silly rollbackFailedOptional Finishing
102 silly runTopLevelLifecycles Starting
103 silly runTopLevelLifecycles Finishing
104 silly install printInstalled
105 verbose stack Error: write EPROTO
105 verbose stack     at Object.exports._errnoException (util.js:856:11)
105 verbose stack     at exports._exceptionWithHostPort (util.js:879:20)
105 verbose stack     at WriteWrap.afterWrite (net.js:763:14)
106 verbose cwd C:\Users\xxxxxxx\documents\visual studio 2015\Projects\ionic-js-sidemenu1\ionic-js-sidemenu1
107 error Windows_NT 10.0.10240
108 error argv "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Web\\External\\node.exe" "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Web\\External\\node_modules\\npm\\bin\\npm-cli.js" "install"
109 error node v5.4.1
110 error npm  v3.3.4
111 error code EPROTO
112 error errno EPROTO
113 error syscall write
114 error write EPROTO
115 error If you need help, you may report this error at:
115 error     <https://github.com/npm/npm/issues>
116 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
@fieldcommandergraeme I updated your post to make it more readable. Have you properly configured `npm` to use your proxy?

**Comment by KenanY** [comment]
Closing due to no response.
