### ISSUE TITLE
npm install:Error: Cannot find module './lib/cookies'

### ISSUE THREAD

**Issue by cybibo** [npm/npm#13718]
ryan-Mac:backbone-login ryan$ npm install
Error: Cannot find module './lib/cookies'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/index.js:18:29)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/bin/npm" "install"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module './lib/cookies'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by cybibo** [comment]
install node v4.2.1,npm is correct.
