### ISSUE TITLE
NPM shrinkwrap exceeds stack with cross-dependency

### ISSUE THREAD

**Issue by martinheidegger** [npm/npm#13730]
#### I'm opening this issue because:
- npm is crashing on `shrinkwrap`
#### What's going wrong?

When trying to shrinkwrap my package it hangs since `ex5-ext` and `es6-iterator` have a cross dependency towards each other.
#### How can the CLI team reproduce the problem?

Create a new folder;

```
$ npm init -y
$ npm i es6-map@0.1.4
$ npm shrinkwrap
```

(you should get the error message)
### Supporting information:
- I have tested this with `3.10.5` and it handled it without a problem!
- When creating the reproduce step I noticed that it was required to install a package **depending**  on `es5-ext`/`es6-iterator`, simply installing `es5-ext` worked!

_(debug.log)_

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/iojs', '/usr/local/bin/npm', 'shrinkwrap' ]
2 info using npm@3.10.6
3 info using node@v5.11.1
4 info lifecycle learn-sass@1.1.1~preshrinkwrap: learn-sass@1.1.1
5 silly lifecycle learn-sass@1.1.1~preshrinkwrap: no script for preshrinkwrap, continuing
6 warn shrinkwrap Excluding devDependency: acorn@3.3.0 { after: '^0.8.2',
6 warn shrinkwrap   'node-sass': '^3.8.0',
6 warn shrinkwrap   'workshopper-adventure': '^4.6.3',
6 warn shrinkwrap   'workshopper-exercise': '^2.5.3',
6 warn shrinkwrap   xtend: '^4.0.1' }
7 warn shrinkwrap Excluding devDependency: acorn-jsx@3.0.1 { after: '^0.8.2',
7 warn shrinkwrap   'node-sass': '^3.8.0',
7 warn shrinkwrap   'workshopper-adventure': '^4.6.3',
7 warn shrinkwrap   'workshopper-exercise': '^2.5.3',
7 warn shrinkwrap   xtend: '^4.0.1' }
8 warn shrinkwrap Excluding devDependency: ansi-escapes@1.4.0 { after: '^0.8.2',
8 warn shrinkwrap   'node-sass': '^3.8.0',
8 warn shrinkwrap   'workshopper-adventure': '^4.6.3',
8 warn shrinkwrap   'workshopper-exercise': '^2.5.3',
8 warn shrinkwrap   xtend: '^4.0.1' }
9 warn shrinkwrap Excluding devDependency: argparse@1.0.7 { after: '^0.8.2',
9 warn shrinkwrap   'node-sass': '^3.8.0',
9 warn shrinkwrap   'workshopper-adventure': '^4.6.3',
9 warn shrinkwrap   'workshopper-exercise': '^2.5.3',
9 warn shrinkwrap   xtend: '^4.0.1' }
10 warn shrinkwrap Excluding devDependency: array-union@1.0.2 { after: '^0.8.2',
10 warn shrinkwrap   'node-sass': '^3.8.0',
10 warn shrinkwrap   'workshopper-adventure': '^4.6.3',
10 warn shrinkwrap   'workshopper-exercise': '^2.5.3',
10 warn shrinkwrap   xtend: '^4.0.1' }
11 warn shrinkwrap Excluding devDependency: array-uniq@1.0.3 { after: '^0.8.2',
11 warn shrinkwrap   'node-sass': '^3.8.0',
11 warn shrinkwrap   'workshopper-adventure': '^4.6.3',
11 warn shrinkwrap   'workshopper-exercise': '^2.5.3',
11 warn shrinkwrap   xtend: '^4.0.1' }
12 warn shrinkwrap Excluding devDependency: arrify@1.0.1 { after: '^0.8.2',
12 warn shrinkwrap   'node-sass': '^3.8.0',
12 warn shrinkwrap   'workshopper-adventure': '^4.6.3',
12 warn shrinkwrap   'workshopper-exercise': '^2.5.3',
12 warn shrinkwrap   xtend: '^4.0.1' }
13 warn shrinkwrap Excluding devDependency: bluebird@3.4.1 { after: '^0.8.2',
13 warn shrinkwrap   'node-sass': '^3.8.0',
13 warn shrinkwrap   'workshopper-adventure': '^4.6.3',
13 warn shrinkwrap   'workshopper-exercise': '^2.5.3',
13 warn shrinkwrap   xtend: '^4.0.1' }
14 warn shrinkwrap Excluding devDependency: caller-path@0.1.0 { after: '^0.8.2',
14 warn shrinkwrap   'node-sass': '^3.8.0',
14 warn shrinkwrap   'workshopper-adventure': '^4.6.3',
14 warn shrinkwrap   'workshopper-exercise': '^2.5.3',
14 warn shrinkwrap   xtend: '^4.0.1' }
15 warn shrinkwrap Excluding devDependency: callsites@0.2.0 { after: '^0.8.2',
15 warn shrinkwrap   'node-sass': '^3.8.0',
15 warn shrinkwrap   'workshopper-adventure': '^4.6.3',
15 warn shrinkwrap   'workshopper-exercise': '^2.5.3',
15 warn shrinkwrap   xtend: '^4.0.1' }
16 warn shrinkwrap Excluding devDependency: circular-json@0.3.1 { after: '^0.8.2',
16 warn shrinkwrap   'node-sass': '^3.8.0',
16 warn shrinkwrap   'workshopper-adventure': '^4.6.3',
16 warn shrinkwrap   'workshopper-exercise': '^2.5.3',
16 warn shrinkwrap   xtend: '^4.0.1' }
17 warn shrinkwrap Excluding devDependency: cli-cursor@1.0.2 { after: '^0.8.2',
17 warn shrinkwrap   'node-sass': '^3.8.0',
17 warn shrinkwrap   'workshopper-adventure': '^4.6.3',
17 warn shrinkwrap   'workshopper-exercise': '^2.5.3',
17 warn shrinkwrap   xtend: '^4.0.1' }
18 warn shrinkwrap Excluding devDependency: cli-width@2.1.0 { after: '^0.8.2',
18 warn shrinkwrap   'node-sass': '^3.8.0',
18 warn shrinkwrap   'workshopper-adventure': '^4.6.3',
18 warn shrinkwrap   'workshopper-exercise': '^2.5.3',
18 warn shrinkwrap   xtend: '^4.0.1' }
19 warn shrinkwrap Excluding devDependency: concat-stream@1.5.1 { after: '^0.8.2',
19 warn shrinkwrap   'node-sass': '^3.8.0',
19 warn shrinkwrap   'workshopper-adventure': '^4.6.3',
19 warn shrinkwrap   'workshopper-exercise': '^2.5.3',
19 warn shrinkwrap   xtend: '^4.0.1' }
20 verbose stack RangeError: Maximum call stack size exceeded
20 verbose stack     at Object.hasOwnProperty (native)
20 verbose stack     at isArguments (/usr/local/lib/node_modules/npm/node_modules/aproba/index.js:4:47)
20 verbose stack     at Array.types.A (/usr/local/lib/node_modules/npm/node_modules/aproba/index.js:9:68)
20 verbose stack     at module.exports (/usr/local/lib/node_modules/npm/node_modules/aproba/index.js:22:18)
20 verbose stack     at moduleName (/usr/local/lib/node_modules/npm/lib/utils/module-name.js:25:3)
20 verbose stack     at exports.isOnlyDev (/usr/local/lib/node_modules/npm/lib/install/is-dev.js:39:45)
20 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/is-dev.js:33:14
20 verbose stack     at Array.every (native)
20 verbose stack     at exports.isOnlyDev (/usr/local/lib/node_modules/npm/lib/install/is-dev.js:39:26)
20 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/is-dev.js:33:14
21 verbose cwd /Users/martin/Private/projects/nodeschool/learn-sass
22 error Darwin 15.4.0
23 error argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "shrinkwrap"
24 error node v5.11.1
25 error npm  v3.10.6
26 error Maximum call stack size exceeded
27 error If you need help, you may report this error at:
27 error     <https://github.com/npm/npm/issues>
28 verbose exit [ 1, true ]
```

**Comment by kaelig** [comment]
👍  I have the same issue

**Comment by thekip** [comment]
+1. Downgrade to 3.10.5 resolve the problem
