### ISSUE TITLE
cannot install karma

### ISSUE THREAD

**Issue by renukasethi** [npm/npm#13776]
I am trying to install karma on windows and I am getting the error below

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'karma' ]
2 info using npm@2.15.8
3 info using node@v4.4.7
4 verbose install initial load of H:\package.json
5 verbose readDependencies loading dependencies from H:\package.json
6 silly cache add args [ 'karma', null ]
7 verbose cache add spec karma
8 silly cache add parsed spec Result {
8 silly cache add   raw: 'karma',
8 silly cache add   scope: null,
8 silly cache add   name: 'karma',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: 'latest',
8 silly cache add   type: 'tag' }
9 silly addNamed karma@latest
10 verbose addNamed "latest" is being treated as a dist-tag for karma
11 info addNameTag [ 'karma', 'latest' ]
12 silly mapToRegistry name karma
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry data Result {
15 silly mapToRegistry   raw: 'karma',
15 silly mapToRegistry   scope: null,
15 silly mapToRegistry   name: 'karma',
15 silly mapToRegistry   rawSpec: '',
15 silly mapToRegistry   spec: 'latest',
15 silly mapToRegistry   type: 'tag' }
16 silly mapToRegistry uri https://registry.npmjs.org/karma
17 verbose addNameTag registry:https://registry.npmjs.org/karma not in flight; fetching
18 verbose request uri https://registry.npmjs.org/karma
19 verbose request no auth needed
20 info attempt registry request try #1 at 9:17:14 AM
21 verbose request id 30839544747f7003
22 http request GET https://registry.npmjs.org/karma
23 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
24 info attempt registry request try #2 at 9:17:24 AM
25 http request GET https://registry.npmjs.org/karma
26 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
27 info attempt registry request try #3 at 9:18:24 AM
28 http request GET https://registry.npmjs.org/karma
29 verbose stack Error: self signed certificate in certificate chain
29 verbose stack     at Error (native)
29 verbose stack     at TLSSocket.<anonymous> (_tls_wrap.js:1017:38)
29 verbose stack     at emitNone (events.js:67:13)
29 verbose stack     at TLSSocket.emit (events.js:166:7)
29 verbose stack     at TLSSocket._init.ssl.onclienthello.ssl.oncertcb.TLSSocket._finishInit (_tls_wrap.js:582:8)
29 verbose stack     at TLSWrap.ssl.onclienthello.ssl.oncertcb.ssl.onnewsession.ssl.onhandshakedone (_tls_wrap.js:424:38)
30 verbose cwd H:\
31 error Windows_NT 6.1.7601
32 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "karma"
33 error node v4.4.7
34 error npm  v2.15.8
35 error code SELF_SIGNED_CERT_IN_CHAIN
36 error self signed certificate in certificate chain
37 error If you need help, you may report this error at:
37 error     <https://github.com/npm/npm/issues>
38 verbose exit [ 1, true ]
```

**Comment by legodude17** [comment]
This is saying you have a self-signed certificate in your certificate chain. If you have one, please remove it, if not, please tell me that.
