### ISSUE TITLE
Homebrew npm usage MAC

### ISSUE THREAD

**Issue by bastienvinh** [npm/npm#13784]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
The problem is npm is broken, it can't find npmlog package. Since the last update, it's what has been happened.  I used homebrew on OS X to install node.

#### How can the CLI team reproduce the problem?

To reproduce this error, you must use : 
```
brew install node
npm --version
```

And this error appear :

```
module.js:457
    throw err;
    ^

Error: Cannot find module 'npmlog'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:19:13
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:75:3)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
```
### supporting information:

 - `npm -v` prints: Error
 - `node -v` prints:
```
v7.0.0-head
```
 - `npm config get registry` prints:
 - Windows, OS X, or Linux?: I use OS X
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by bastienvinh** [comment]
Sorry I found a solution here : https://gist.github.com/DanHerbert/9520689
