### ISSUE TITLE
Error with expanding plugin

### ISSUE THREAD

**Issue by MickeyMouse01** [npm/npm#13799]
#### I'm opening this issue because:

  - [ 1] npm is crashing.
  - [ 0] npm is producing an incorrect install.
  - [1 ] npm is doing something I don't understand.
  - [0 ] Other (_see below for feature requests_):

#### What's going wrong?
Error
#### How can the CLI team reproduce the problem?

```
Buildfile: C:\MAF apps\Employee\.main.android\bin\build.xml
     [echo] basedir = C:\MAF apps\Employee\.main.android\bin
     [echo] manifest.file = C:\MAF apps\Employee\.main.android\build\debug/AndroidManifest.xml
Trying to override old definition of task gettype
Trying to override old definition of task gettarget
configure-common.init:
globals.init:
stage.init:
configure.configure:
     [echo] Original configure
fars.init:
application.init:
-ensureKeystoreProperties:
maybeCreateKeyStore:
     [exec] Generating 2?048 bit RSA key pair and self-signed certificate (SHA256withRSA) with a validity of 14?000 days
     [exec] 	for: CN=Android Debug, O=Android, C=US
     [exec] [Storing C:\MAF apps\Employee\.main.android\build\debug.keystore]
android.init:
init:
-createStaging:
    [mkdir] Created dir: C:\MAF apps\Employee\.main.android\build\debug\src
-executeBuildTemplate:
     [echo] @drawable/adfmf_icon
[build-template] {  "unzips": {    "expandZip": [      {        "zipSrc": "$${template.root.dir}/Android/Oracle_ADFmf_Framework.zip",        "zipDest": "$${build.root.dir}/assets",        "patternSets": [          {            "includes": [              "framework/Android/build/java_res/assets/**"            ]          }        ],        "globFrom": "framework/Android/build/java_res/assets/*",        "globTo": "*"      },      {        "zipSrc": "$${template.root.dir}/javascript/ADFmf_AmxJavascript_$${oepe.adfmf.build.mode}.zip",        "zipDest": "$${build.root.dir}/assets/www/js",        "patternSets": [          {            "includes": [              "www/js/**"            ]          }        ],        "globFrom": "www/js/*",        "globTo": "*"      },      {        "zipSrc": "$${template.root.dir}/javascript/Android/ADFmf_AmxJavascript_$${oepe.adfmf.build.mode}_Android.zip",        "zipDest": "$${build.root.dir}/assets/www/js",        "patternSets": [          {            "includes": [              "www/js/**"            ]          }        ],        "globFrom": "www/js/*",        "globTo": "*"      },      {        "zipSrc": "$${template.root.dir}/Android/Oracle_ADFmf_Framework.zip",        "zipDest": "$${build.root.dir}/assets/jvm/lib",        "patternSets": [          {            "includes": [              "framework/Common/build/jar/**"            ]          }        ],        "globFrom": "framework/Common/build/jar/*",        "globTo": "*"      },      {        "zipSrc": "$${template.root.dir}/Android/Oracle_ADFmf_Framework.zip",        "zipDest": "$${build.root.dir}/res",        "patternSets": [          {            "includes": [              "framework/Android/build/res/**"            ]          }        ],        "globFrom": "framework/Android/build/res/*",        "globTo": "*"      },      {        "zipSrc": "$${template.root.dir}/Android/Oracle_ADFmf_Framework.zip",        "zipDest": "$${build.root.dir}/res",        "patternSets": [          {            "includes": [              "framework/Android/template/res/**"            ]          }        ],        "globFrom": "framework/Android/template/res/*",        "globTo": "*"      },      {        "zipSrc": "$${template.root.dir}/Android/Oracle_ADFmf_Framework.zip",        "zipDest": "$${build.root.dir}",        "patternSets": [          {            "includes": [              "framework/Android/template/AndroidManifest.template.xml"            ]          }        ],        "globFrom": "framework/Android/template/AndroidManifest.template.xml",        "globTo": "AndroidManifest.xml"      },      {        "zipSrc": "$${template.root.dir}/Android/Oracle_ADFmf_Framework.zip",        "zipDest": "$${build.root.dir}/lib/x86",        "patternSets": [          {            "includes": [              "framework/Android/build/java_res/libs/x86/**"            ]          }        ],        "globFrom": "framework/Android/build/java_res/libs/x86/*",        "globTo": "*"      },      {         "zipSrc": "$${template.root.dir}/Android/Oracle_ADFmf_Framework.zip",        "zipDest": "$${build.root.dir}/lib/armeabi",        "patternSets": [          {            "includes": [              "framework/Android/build/java_res/libs/armeabi/**"            ]          }        ],        "globFrom": "framework/Android/build/java_res/libs/armeabi/*",        "globTo": "*"      },      {        "zipSrc": "$${template.root.dir}/Android/Oracle_ADFmf_Framework.zip",        "zipDest": "$${build.root.dir}",        "patternSets": [          {            "includes": [              "framework/Android/build/java_res/jvmlibs.zip"            ]          }        ],        "globFrom": "framework/Android/build/java_res/*",        "globTo": "*"      },      {        "zipSrc": "$${template.root.dir}/Android/Oracle_ADFmf_Framework.zip",        "zipDest": "$${build.root.dir}",        "patternSets": [          {            "includes": [              "framework/Android/build/java_res/assets/**"            ]          }        ],        "globFrom": "framework/Android/build/java_res/*",        "globTo": "*"      },      {        "zipSrc": "$${template.root.dir}/Android/Oracle_ADFmf_Framework.zip",        "zipDest": "$${build.root.dir}",        "patternSets": [          {            "includes": [              "framework/Android/build/java_res/handlers.json",              "framework/Android/build/java_res/maf-skins-info.json"            ]          }        ],         "globFrom": "framework/Android/build/java_res/*",        "globTo": "*"      },      {        "zipSrc": "$${template.root.dir}/Android/Oracle_ADFmf_Framework.zip",        "zipDest": "$${build.root.dir}/precompilejars",        "patternSets": [          {            "includes": [              "framework/Android/build/jar/**"            ]          }        ],        "globFrom": "framework/Android/build/jar/*",        "globTo": "*"      }    ]  },  "copies": {    "copy": [      {        "toDir": "$${build.root.dir}/.adf/META-INF",        "overwrite": false,        "force": false,        "fileList": [          {            "dir": "$${template.root.dir}/configService",            "includes": [              "**"            ]          }        ]      }     ]   }};
     [null] Copying 1 file to C:\MAF apps\Employee\.main.android\build\debug\.adf\META-INF
[build-template] Expanding: C:\Eclipse\plugins\oracle.eclipse.tools.maf.rt.v23_2.3.0.201605191642\rt\oracle.maf.v23_20160427\Android\Oracle_ADFmf_Framework.zip into C:\MAF apps\Employee\.main.android\build\debug\assets
[build-template] Expanding: C:\Eclipse\plugins\oracle.eclipse.tools.maf.rt.v23_2.3.0.201605191642\rt\oracle.maf.v23_20160427\javascript\ADFmf_AmxJavascript_debug.zip into C:\MAF apps\Employee\.main.android\build\debug\assets\www\js
[build-template] Expanding: C:\Eclipse\plugins\oracle.eclipse.tools.maf.rt.v23_2.3.0.201605191642\rt\oracle.maf.v23_20160427\javascript\Android\ADFmf_AmxJavascript_debug_Android.zip into C:\MAF apps\Employee\.main.android\build\debug\assets\www\js
[build-template] Expanding: C:\Eclipse\plugins\oracle.eclipse.tools.maf.rt.v23_2.3.0.201605191642\rt\oracle.maf.v23_20160427\Android\Oracle_ADFmf_Framework.zip into C:\MAF apps\Employee\.main.android\build\debug\assets\jvm\lib
[build-template] Expanding: C:\Eclipse\plugins\oracle.eclipse.tools.maf.rt.v23_2.3.0.201605191642\rt\oracle.maf.v23_20160427\Android\Oracle_ADFmf_Framework.zip into C:\MAF apps\Employee\.main.android\build\debug\res
[build-template] Expanding: C:\Eclipse\plugins\oracle.eclipse.tools.maf.rt.v23_2.3.0.201605191642\rt\oracle.maf.v23_20160427\Android\Oracle_ADFmf_Framework.zip into C:\MAF apps\Employee\.main.android\build\debug\res
[build-template] Expanding: C:\Eclipse\plugins\oracle.eclipse.tools.maf.rt.v23_2.3.0.201605191642\rt\oracle.maf.v23_20160427\Android\Oracle_ADFmf_Framework.zip into C:\MAF apps\Employee\.main.android\build\debug
[build-template] Expanding: C:\Eclipse\plugins\oracle.eclipse.tools.maf.rt.v23_2.3.0.201605191642\rt\oracle.maf.v23_20160427\Android\Oracle_ADFmf_Framework.zip into C:\MAF apps\Employee\.main.android\build\debug\lib\x86
[build-template] Expanding: C:\Eclipse\plugins\oracle.eclipse.tools.maf.rt.v23_2.3.0.201605191642\rt\oracle.maf.v23_20160427\Android\Oracle_ADFmf_Framework.zip into C:\MAF apps\Employee\.main.android\build\debug\lib\armeabi
[build-template] Expanding: C:\Eclipse\plugins\oracle.eclipse.tools.maf.rt.v23_2.3.0.201605191642\rt\oracle.maf.v23_20160427\Android\Oracle_ADFmf_Framework.zip into C:\MAF apps\Employee\.main.android\build\debug
[build-template] Expanding: C:\Eclipse\plugins\oracle.eclipse.tools.maf.rt.v23_2.3.0.201605191642\rt\oracle.maf.v23_20160427\Android\Oracle_ADFmf_Framework.zip into C:\MAF apps\Employee\.main.android\build\debug
[build-template] Expanding: C:\Eclipse\plugins\oracle.eclipse.tools.maf.rt.v23_2.3.0.201605191642\rt\oracle.maf.v23_20160427\Android\Oracle_ADFmf_Framework.zip into C:\MAF apps\Employee\.main.android\build\debug
[build-template] Expanding: C:\Eclipse\plugins\oracle.eclipse.tools.maf.rt.v23_2.3.0.201605191642\rt\oracle.maf.v23_20160427\Android\Oracle_ADFmf_Framework.zip into C:\MAF apps\Employee\.main.android\build\debug\precompilejars
-process-adf-android-manifest-template:
-process-adf-template:
-checkPlugmanTools:
     [echo] Checking for cordova install tools under C:\MAF apps\.metadata\.plugins\oracle.eclipse.tools.adf.mobile\d\c_2.3.0
     [echo] cordovaToolsPresent: ${cordovaToolsPresent}
-doMac:
-doUnix:
-doWindows:
    [unzip] Expanding: C:\Eclipse\plugins\oracle.eclipse.tools.maf.rt.v23_2.3.0.201605191642\rt\oracle.maf.v23_20160427\tools\npm.zip into C:\MAF apps\.metadata\.plugins\oracle.eclipse.tools.adf.mobile\d\c_2.3.0\plugman
     [exec] npm ERR! Error: Attempt to unlock C:\Eclipse\plugins\oracle.eclipse.tools.maf.rt.v23_2.3.0.201605191642\rt/oracle.maf.v23_20160427/tools/plugman.tgz, which hasn't been locked
     [exec] npm ERR!     at unlock (C:\MAF apps\.metadata\.plugins\oracle.eclipse.tools.adf.mobile\d\c_2.3.0\plugman\node_modules\npm\lib\cache.js:1434:11)
     [exec] npm ERR!     at cb (C:\MAF apps\.metadata\.plugins\oracle.eclipse.tools.adf.mobile\d\c_2.3.0\plugman\node_modules\npm\lib\cache.js:925:5)
     [exec] npm ERR!     at C:\MAF apps\.metadata\.plugins\oracle.eclipse.tools.adf.mobile\d\c_2.3.0\plugman\node_modules\npm\lib\cache.js:942:20
     [exec] npm ERR!     at C:\MAF apps\.metadata\.plugins\oracle.eclipse.tools.adf.mobile\d\c_2.3.0\plugman\node_modules\npm\lib\cache.js:1412:20
     [exec] npm ERR!     at C:\MAF apps\.metadata\.plugins\oracle.eclipse.tools.adf.mobile\d\c_2.3.0\plugman\node_modules\npm\node_modules\mkdirp\index.js:25:29
     [exec] npm ERR!     at C:\MAF apps\.metadata\.plugins\oracle.eclipse.tools.adf.mobile\d\c_2.3.0\plugman\node_modules\npm\node_modules\mkdirp\index.js:25:29
     [exec] npm ERR!     at C:\MAF apps\.metadata\.plugins\oracle.eclipse.tools.adf.mobile\d\c_2.3.0\plugman\node_modules\npm\node_modules\mkdirp\index.js:25:29
     [exec] npm ERR!     at C:\MAF apps\.metadata\.plugins\oracle.eclipse.tools.adf.mobile\d\c_2.3.0\plugman\node_modules\npm\node_modules\mkdirp\index.js:37:53
     [exec] npm ERR!     at FSReqWrap.oncomplete (fs.js:82:15)
     [exec] npm ERR! If you need help, you may report this *entire* log,
     [exec] npm ERR! including the npm and node versions, at:
     [exec] npm ERR!     <http://github.com/npm/npm/issues>
     [exec] npm ERR! System Windows_NT 10.0.10586
     [exec] npm ERR! command "C:\\MAF apps\\.metadata\\.plugins\\oracle.eclipse.tools.adf.mobile\\d\\c_2.3.0\\plugman\\node.exe" "C:\\MAF apps\\.metadata\\.plugins\\oracle.eclipse.tools.adf.mobile\\d\\c_2.3.0\\plugman\\node_modules\\npm\\bin\\npm-cli.js" "install" "-prefix" "C:\\MAF apps\\.metadata\\.plugins\\oracle.eclipse.tools.adf.mobile\\d\\c_2.3.0/plugman" "C:\\Eclipse\\plugins\\oracle.eclipse.tools.maf.rt.v23_2.3.0.201605191642\\rt/oracle.maf.v23_20160427/tools/plugman.tgz"
     [exec] npm ERR! cwd C:\MAF apps\Employee\.main.android\bin
     [exec] npm ERR! node -v v4.2.1
     [exec] npm ERR! npm -v 1.4.9
     [exec] npm ERR! 
     [exec] npm ERR! Additional logging details can be found in:
     [exec] npm ERR!     C:\MAF apps\Employee\.main.android\bin\npm-debug.log
     [exec] npm ERR! not ok code 0

BUILD FAILED
C:\MAF apps\Employee\.main.android\bin\build-stage.xml:86: exec returned: 1

Total time: 31 seconds
```

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@MickeyMouse01 Does this also occur if you [update](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows) to the latest stable release of `npm`?

**Comment by KenanY** [comment]
Closing due to no response :/
