### ISSUE TITLE
npm start not working.

### ISSUE THREAD

**Issue by ssolanki** [npm/npm#13805]
I was working with npm and webpack and my project was working fine until last evening.
But now, when I run `npm start` it gives me error, here is the npm log file content:

```
0 info it worked if it ends with ok
1 verbose cli [ '/home/sahil/.nvm/versions/node/v5.0.0/bin/node',
1 verbose cli   '/home/sahil/.nvm/versions/node/v5.0.0/bin/npm',
1 verbose cli   'start' ]
2 info using npm@3.3.6
3 info using node@v5.0.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle imdb-redesign@1.0.0~prestart: imdb-redesign@1.0.0
6 silly lifecycle imdb-redesign@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle imdb-redesign@1.0.0~start: imdb-redesign@1.0.0
8 verbose lifecycle imdb-redesign@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle imdb-redesign@1.0.0~start: PATH: /home/sahil/.nvm/versions/node/v5.0.0/lib/node_modules/npm/bin/node-gyp-bin:/home/sahil/Documents/ssolanki.github.io/imdb-redesign/node_modules/.bin:/home/sahil/.nvm/versions/node/v5.0.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
10 verbose lifecycle imdb-redesign@1.0.0~start: CWD: /home/sahil/Documents/ssolanki.github.io/imdb-redesign
11 silly lifecycle imdb-redesign@1.0.0~start: Args: [ '-c', 'webpack-dev-server' ]
12 silly lifecycle imdb-redesign@1.0.0~start: Returned: code: 1  signal: null
13 info lifecycle imdb-redesign@1.0.0~start: Failed to exec start script
14 verbose stack Error: imdb-redesign@1.0.0 start: `webpack-dev-server`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/home/sahil/.nvm/versions/node/v5.0.0/lib/node_modules/npm/lib/utils/lifecycle.js:233:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/home/sahil/.nvm/versions/node/v5.0.0/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:818:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid imdb-redesign@1.0.0
16 verbose cwd /home/sahil/Documents/ssolanki.github.io/imdb-redesign
17 error Linux 3.19.0-32-generic
18 error argv "/home/sahil/.nvm/versions/node/v5.0.0/bin/node" "/home/sahil/.nvm/versions/node/v5.0.0/bin/npm" "start"
19 error node v5.0.0
20 error npm  v3.3.6
21 error code ELIFECYCLE
22 error imdb-redesign@1.0.0 start: `webpack-dev-server`
22 error Exit status 1
23 error Failed at the imdb-redesign@1.0.0 start script 'webpack-dev-server'.
23 error This is most likely a problem with the imdb-redesign package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     webpack-dev-server
23 error You can get their info via:
23 error     npm owner ls imdb-redesign
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
My github repo is present here: [(https://github.com/ssolanki/ssolanki.github.io)]

**Comment by legodude17** [comment]
This is probably a problem with `webpack-dev-server`, not `npm`.

**Comment by adriengibrat** [comment]
> This is most likely a problem with the imdb-redesign package,
> not with npm itself.
> Tell the author that this fails on your system:
>     webpack-dev-server

Please, read the log carefully, as they are meant to be, and avoid unecessary noise in the npm issues (a.k.a. you should close this issue ;)
