### ISSUE TITLE
Permission Denied When npm run start

### ISSUE THREAD

**Issue by isdzulqor** [npm/npm#13801]
Hi,, I have cloned a project from GitHub. That project using NPM. When I run npm install. it's worked well at first. But after some dependencies have been installed. something wrong occured. and I don't understand the error. I have no solution. I have tried many ways. The error is about Permission denied. I have run chmod 777 -R to my directory. I have run sudo chown too. But nothing work. Any ideas? 
Please help me. Thank you 

```
Error sh: 1: concurrent: Permission denied

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/bin/npm', 'run', 'start' ]
2 info using npm@3.10.3
3 info using node@v6.4.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle react-redux-universal-hot-example@0.9.0~prestart: react-redux-universal-hot-example@0.9.0
6 silly lifecycle react-redux-universal-hot-example@0.9.0~prestart: no script for prestart, continuing
7 info lifecycle react-redux-universal-hot-example@0.9.0~start: react-redux-universal-hot-example@0.9.0
8 verbose lifecycle react-redux-universal-hot-example@0.9.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle react-redux-universal-hot-example@0.9.0~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/media/isdzulqor/01D18DCEEED63490/ALHAMDULILLAH/REACT JS/react-redux-universal-hot-example/node_modules/.bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin
10 verbose lifecycle react-redux-universal-hot-example@0.9.0~start: CWD: /media/isdzulqor/01D18DCEEED63490/ALHAMDULILLAH/REACT JS/react-redux-universal-hot-example
11 silly lifecycle react-redux-universal-hot-example@0.9.0~start: Args: [ '-c',
11 silly lifecycle   'concurrent --kill-others "npm run start-prod" "npm run start-prod-api"' ]
12 silly lifecycle react-redux-universal-hot-example@0.9.0~start: Returned: code: 126  signal: null
13 info lifecycle react-redux-universal-hot-example@0.9.0~start: Failed to exec start script
14 verbose stack Error: react-redux-universal-hot-example@0.9.0 start: `concurrent --kill-others "npm run start-prod" "npm run start-prod-api"`
14 verbose stack Exit status 126
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:852:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid react-redux-universal-hot-example@0.9.0
16 verbose cwd /media/isdzulqor/01D18DCEEED63490/ALHAMDULILLAH/REACT JS/react-redux-universal-hot-example
17 error Linux 3.19.0-32-generic
18 error argv "/usr/local/bin/node" "/usr/bin/npm" "run" "start"
19 error node v6.4.0
20 error npm  v3.10.3
21 error code ELIFECYCLE
22 error react-redux-universal-hot-example@0.9.0 start: `concurrent --kill-others "npm run start-prod" "npm run start-prod-api"`
22 error Exit status 126
23 error Failed at the react-redux-universal-hot-example@0.9.0 start script 'concurrent --kill-others "npm run start-prod" "npm run start-prod-api"'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the react-redux-universal-hot-example package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     concurrent --kill-others "npm run start-prod" "npm run start-prod-api"
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs react-redux-universal-hot-example
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls react-redux-universal-hot-example
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by isdzulqor** [comment]
I have found where the problem come from. It's because my project app is in the windows partition directory. I am using dual boot. linux mint and windows. when I tried to copy my project in linux directory. it's running well.
