### ISSUE TITLE
Trying to install install linkedin-scraper but getting error  npm ERR! Windows_NT 6.1.7601

### ISSUE THREAD

**Issue by ROhitGyrix** [npm/npm#13831]
I am trying to install linkedin-scraper but getting the following error 

Error ----

```
D:\Projects\sws-nodejs-angular>npm install linkedin-scraper
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "linkedin-scraper"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6

npm ERR! Cannot read property 'localeCompare' of undefined
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Projects\sws-nodejs-angular\npm-debug.log

D:\Projects\sws-nodejs-angular>echo %http_proxy%
%http_proxy%

D:\Projects\sws-nodejs-angular>set http_proxy=

D:\Projects\sws-nodejs-angular>npm install linkedin-scraper
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "linkedin-scraper"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6

npm ERR! Cannot read property 'localeCompare' of undefined
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Projects\sws-nodejs-angular\npm-debug.log
```

As you can see i have also tried tp set  %http_proxy%
i am new to nodejs so need help

**Comment by ROhitGyrix** [comment]
new updates 
installed npm 3.3.7 this resolved the issue but getting a new error related to node-gyp configure 
and i have followed the steps from
https://github.com/nodejs/node-gyp#the-bindinggyp-file


new error --

D:\Projects\sws-nodejs-angular>npm install npm@3.3.7 -g
C:\Users\admin\AppData\Roaming\npm\npm -> C:\Users\admin\AppData\Roaming\npm\nod
e_modules\npm\bin\npm-cli.js
C:\Users\admin\AppData\Roaming\npm
└── npm@3.3.7


D:\Projects\sws-nodejs-angular>npm install linkedin-scraper
npm WARN install Couldn't install optional dependency: Unsupported

> contextify@0.1.15 install D:\Projects\sws-nodejs-angular\node_modules\contexti
fy
> node-gyp rebuild


D:\Projects\sws-nodejs-angular\node_modules\contextify>if not defined npm_config
_node_gyp (node "C:\Users\admin\AppData\Roaming\npm\node_modules\npm\bin\node-gy
p-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebui
ld )
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
  contextify.cc
  win_delay_load_hook.c
C:\Users\admin\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\src\w
in_delay_load_hook.c(31): error C2373: '__pfnDliNotifyHook2': redefinition; dif
ferent type modifiers [D:\Projects\sws-nodejs-angular\node_modules\contextify\b
uild\contextify.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\delayimp.h(134
  ): note: see declaration of '__pfnDliNotifyHook2'
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\admin\AppData\Roaming\npm\no
de_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\admin\\AppDat
a\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "r
ebuild"
gyp ERR! cwd D:\Projects\sws-nodejs-angular\node_modules\contextify
gyp ERR! node -v v5.0.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN install:contextify@0.1.15 contextify@0.1.15 install: `node-gyp rebuild`

npm WARN install:contextify@0.1.15 Exit status 1
sws@1.0.0 D:\Projects\sws-nodejs-angular
└── (empty)

npm WARN ENOENT ENOENT: no such file or directory, open 'D:\Projects\sws-nodejs-
angular\node_modules\binding.gyp\package.json'
npm WARN ENOENT ENOENT: no such file or directory, open 'D:\Projects\sws-nodejs-
angular\node_modules\build\package.json'
npm WARN EPACKAGEJSON sws@1.0.0 No repository field.
npm WARN EPACKAGEJSON sws@1.0.0 No license field.
npm ERR! code 1

please help
