### ISSUE TITLE
enable to ib

### ISSUE THREAD

**Issue by victor101** [npm/npm#13841]
#### I'm opening this issue because:

 when ever i try to install cordova cli am on windows 10 i keep getting this these errors

```
C:\Users\vktrlife>npm install -g cordova
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! file C:\Users\vktrlife\AppData\Roaming\npm-cache\insight\0.8.3\package\package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Unexpected token '\u0000' at 1:1
npm ERR!
npm ERR! ^
npm ERR! File: C:\Users\vktrlife\AppData\Roaming\npm-cache\insight\0.8.3\package\package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\vktrlife\npm-debug.log
```

this is the log file 

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'ionic' ]
2 info using npm@3.10.3
3 info using node@v6.5.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData ionic
8 silly fetchNamedPackageData ionic
9 silly mapToRegistry name ionic
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'ionic',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'ionic',
12 silly mapToRegistry   name: 'ionic',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/ionic
14 verbose request uri https://registry.npmjs.org/ionic
15 verbose request no auth needed
16 info attempt registry request try #1 at 10:50:51 AM
17 verbose request id 1285663ede9f2396
18 http request GET https://registry.npmjs.org/ionic
19 http 200 https://registry.npmjs.org/ionic
20 verbose headers { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
20 verbose headers   etag: '"2R8VZT8O7VQ2XT8WP5Z44F6CR"',
20 verbose headers   'content-type': 'application/json',
20 verbose headers   'content-encoding': 'gzip',
20 verbose headers   'cache-control': 'max-age=300',
20 verbose headers   'content-length': '65572',
20 verbose headers   'accept-ranges': 'bytes',
20 verbose headers   date: 'Fri, 02 Sep 2016 08:51:40 GMT',
20 verbose headers   via: '1.1 varnish',
20 verbose headers   age: '0',
20 verbose headers   connection: 'keep-alive',
20 verbose headers   'x-served-by': 'cache-mia1325-MIA',
20 verbose headers   'x-cache': 'MISS',
20 verbose headers   'x-cache-hits': '0',
20 verbose headers   'x-timer': 'S1472806299.454072,VS0,VE770',
20 verbose headers   vary: 'Accept-Encoding' }
21 silly get cb [ 200,
21 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
21 silly get     etag: '"2R8VZT8O7VQ2XT8WP5Z44F6CR"',
21 silly get     'content-type': 'application/json',
21 silly get     'content-encoding': 'gzip',
21 silly get     'cache-control': 'max-age=300',
21 silly get     'content-length': '65572',
21 silly get     'accept-ranges': 'bytes',
21 silly get     date: 'Fri, 02 Sep 2016 08:51:40 GMT',
21 silly get     via: '1.1 varnish',
21 silly get     age: '0',
21 silly get     connection: 'keep-alive',
21 silly get     'x-served-by': 'cache-mia1325-MIA',
21 silly get     'x-cache': 'MISS',
21 silly get     'x-cache-hits': '0',
21 silly get     'x-timer': 'S1472806299.454072,VS0,VE770',
21 silly get     vary: 'Accept-Encoding' } ]
22 verbose get saving ionic to C:\Users\vktrlife\AppData\Roaming\npm-cache\registry.npmjs.org\ionic\.cache.json
23 verbose correctMkdir C:\Users\vktrlife\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
24 silly install normalizeTree
25 silly loadCurrentTree Finishing
26 silly loadIdealTree Starting
27 silly install loadIdealTree
28 silly cloneCurrentTree Starting
29 silly install cloneCurrentTreeToIdealTree
30 silly cloneCurrentTree Finishing
31 silly loadShrinkwrap Starting
32 silly install loadShrinkwrap
33 silly loadShrinkwrap Finishing
34 silly loadAllDepsIntoIdealTree Starting
35 silly install loadAllDepsIntoIdealTree
36 silly resolveWithNewModule ionic@2.0.0 checking installable status
37 silly cache add args [ 'ionic', null ]
38 verbose cache add spec ionic
39 silly cache add parsed spec Result {
39 silly cache add   raw: 'ionic',
39 silly cache add   scope: null,
39 silly cache add   escapedName: 'ionic',
39 silly cache add   name: 'ionic',
39 silly cache add   rawSpec: '',
39 silly cache add   spec: 'latest',
39 silly cache add   type: 'tag' }
40 silly addNamed ionic@latest
41 verbose addNamed "latest" is being treated as a dist-tag for ionic
42 info addNameTag [ 'ionic', 'latest' ]
43 silly mapToRegistry name ionic
44 silly mapToRegistry using default registry
45 silly mapToRegistry registry https://registry.npmjs.org/
46 silly mapToRegistry data Result {
46 silly mapToRegistry   raw: 'ionic',
46 silly mapToRegistry   scope: null,
46 silly mapToRegistry   escapedName: 'ionic',
46 silly mapToRegistry   name: 'ionic',
46 silly mapToRegistry   rawSpec: '',
46 silly mapToRegistry   spec: 'latest',
46 silly mapToRegistry   type: 'tag' }
47 silly mapToRegistry uri https://registry.npmjs.org/ionic
48 verbose addNameTag registry:https://registry.npmjs.org/ionic not in flight; fetching
49 verbose get https://registry.npmjs.org/ionic not expired, no request
50 silly addNameTag next cb for ionic with tag latest
51 silly addNamed ionic@2.0.0
52 verbose addNamed "2.0.0" is a plain semver version for ionic
53 silly mapToRegistry name ionic
54 silly mapToRegistry using default registry
55 silly mapToRegistry registry https://registry.npmjs.org/
56 silly mapToRegistry data Result {
56 silly mapToRegistry   raw: 'ionic',
56 silly mapToRegistry   scope: null,
56 silly mapToRegistry   escapedName: 'ionic',
56 silly mapToRegistry   name: 'ionic',
56 silly mapToRegistry   rawSpec: '',
56 silly mapToRegistry   spec: 'latest',
56 silly mapToRegistry   type: 'tag' }
57 silly mapToRegistry uri https://registry.npmjs.org/ionic
58 verbose addRemoteTarball https://registry.npmjs.org/ionic/-/ionic-2.0.0.tgz not in flight; adding
59 verbose addRemoteTarball [ 'https://registry.npmjs.org/ionic/-/ionic-2.0.0.tgz',
59 verbose addRemoteTarball   '8135804e1f2470292100dedadc571e99023e4f7c' ]
60 info retry fetch attempt 1 at 10:52:16 AM
61 info attempt registry request try #1 at 10:52:16 AM
62 http fetch GET https://registry.npmjs.org/ionic/-/ionic-2.0.0.tgz
63 http fetch 200 https://registry.npmjs.org/ionic/-/ionic-2.0.0.tgz
64 info retry will retry, error on last attempt: Error: read ECONNRESET
65 info retry will retry, error on last attempt: Error: read ECONNRESET
66 silly fetchAndShaCheck shasum 8135804e1f2470292100dedadc571e99023e4f7c
67 silly rollbackFailedOptional Starting
68 silly rollbackFailedOptional Finishing
69 silly runTopLevelLifecycles Starting
70 silly runTopLevelLifecycles Finishing
71 silly install printInstalled
72 verbose stack Error: shasum check failed for C:\Users\vktrlife\AppData\Local\Temp\npm-5124-e989ff86\registry.npmjs.org\ionic\-\ionic-2.0.0.tgz
72 verbose stack Expected: 8135804e1f2470292100dedadc571e99023e4f7c
72 verbose stack Actual:   eec67a033b6445eee49c486bce13b117bc23c6f3
72 verbose stack From:     https://registry.npmjs.org/ionic/-/ionic-2.0.0.tgz
72 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\sha\index.js:25:8
72 verbose stack     at ReadStream.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\sha\index.js:72:7)
72 verbose stack     at emitNone (events.js:91:20)
72 verbose stack     at ReadStream.emit (events.js:185:7)
72 verbose stack     at endReadableNT (_stream_readable.js:974:12)
72 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:74:11)
72 verbose stack     at process._tickCallback (internal/process/next_tick.js:98:9)
73 verbose cwd C:\Users\vktrlife
74 error Windows_NT 10.0.10586
75 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "ionic"
76 error node v6.5.0
77 error npm  v3.10.3
78 error shasum check failed for C:\Users\vktrlife\AppData\Local\Temp\npm-5124-e989ff86\registry.npmjs.org\ionic\-\ionic-2.0.0.tgz
78 error Expected: 8135804e1f2470292100dedadc571e99023e4f7c
78 error Actual:   eec67a033b6445eee49c486bce13b117bc23c6f3
78 error From:     https://registry.npmjs.org/ionic/-/ionic-2.0.0.tgz
79 error If you need help, you may report this error at:
79 error     <https://github.com/npm/npm/issues>
80 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
@victor101 Have you tried running `npm cache clean`?

**Comment by victor101** [comment]
well what do you know it worked like magic thank you very much!!!!
