### ISSUE TITLE
Tryin to install Cordova iconic using npm

### ISSUE THREAD

**Issue by Albean** [npm/npm#13842]
#### I'm opening this issue because:
- [ ] npm is crashing.
- [ ] npm is producing an incorrect install.
- [x] npm is doing something I don't understand.
- [ ] Other (_see below for feature requests_):
#### What's going wrong?

when i try to run this command;

npm install -g cordova ionic

 to install cordova iconic. 

Im stuck on steps 4 and 5 that are stated below.
 im not sure if .bash_profile is executed, and when i go to step 5 and execute the command i get alot of errors;

```
53 error Windows_NT 6.1.7601
54 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova" "ionic"
55 error node v4.5.0
56 error npm  v2.15.9
57 error code ECONNRESET
58 error network tunneling socket could not be established, statusCode=407
58 error network This is most likely not a problem with npm itself
58 error network and is related to network connectivity.
58 error network In most cases you are behind a proxy or have bad network settings.
58 error network
58 error network If you are behind a proxy, please make sure that the
58 error network 'proxy' config is set properly.  See: 'npm help config'
59 verbose exit [ 1, true ]
```
#### How can the CLI team reproduce the problem?

Im following these steps;
Installing Node

1.Install the latest version of Node using the installer found here:

https://nodejs.org/

2.Setting up Android Tools

Install Android Studio from Google:

https://developer.android.com/sdk/index.html

Leave the website open after you have downloaded it, because it lists the SDK Path which we’ll need later. Run the Android Studio installer and install all SDKs that are recommended.

After Android Studio has finished installing, run Android Studio (you may be asked to install JVM, do so at this time) and choose "Configure" -> “SDK Manager”. Check both the “Build Tools” and the actual SDK for Android version 19 and 21 if they are not already installed, and install them.

3.Download ANT from Apache and unzip it to a directory that you will add to the PATH in a minute:

http://ant.apache.org/bindownload.cgi

4.Create a file called ".bash_profile" (if it doesn’t exist already) in your home directory with the following content:

export ANDROID_HOME="<SDK PATH FROM ANDROID STUDIO>"
export PATH=${PATH}:"<PATH YOU EXTRACTED ANT TO>"

At this point in time you should close the command line console and re-open it so your bash profile takes effect.
Installing Ionic

5.You should have all of the required dependencies for Ionic by now, so we can install it and cordova via npm:

npm install -g cordova ionic
### supporting information:
- `npm -v` prints: 2.15.9
- `node -v` prints: v4.5.0
- `npm config get registry` prints:
- Windows, OS X, or Linux?: Windows
- Network issues:
  - Geographic location where npm was run:
  - [x] I use a proxy to connect to the web.
- npm-debug.log

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'cordova',
1 verbose cli   'ionic' ]
2 info using npm@2.15.9
3 info using node@v4.5.0
4 verbose install initial load of C:\Users\areidy\AppData\Roaming\npm\package.json
5 verbose readDependencies loading dependencies from C:\Users\name\AppData\Roaming\npm\package.json
6 silly cache add args [ 'cordova', null ]
7 verbose cache add spec cordova
8 silly cache add args [ 'ionic', null ]
9 verbose cache add spec ionic
10 silly cache add parsed spec Result {
10 silly cache add   raw: 'cordova',
10 silly cache add   scope: null,
10 silly cache add   name: 'cordova',
10 silly cache add   rawSpec: '',
10 silly cache add   spec: 'latest',
10 silly cache add   type: 'tag' }
11 silly addNamed cordova@latest
12 verbose addNamed "latest" is being treated as a dist-tag for cordova
13 info addNameTag [ 'cordova', 'latest' ]
14 silly mapToRegistry name cordova
15 silly mapToRegistry using default registry
16 silly mapToRegistry registry https://registry.npmjs.org/
17 silly mapToRegistry data Result {
17 silly mapToRegistry   raw: 'cordova',
17 silly mapToRegistry   scope: null,
17 silly mapToRegistry   name: 'cordova',
17 silly mapToRegistry   rawSpec: '',
17 silly mapToRegistry   spec: 'latest',
17 silly mapToRegistry   type: 'tag' }
18 silly mapToRegistry uri https://registry.npmjs.org/cordova
19 verbose addNameTag registry:https://registry.npmjs.org/cordova not in flight; fetching
20 silly cache add parsed spec Result {
20 silly cache add   raw: 'ionic',
20 silly cache add   scope: null,
20 silly cache add   name: 'ionic',
20 silly cache add   rawSpec: '',
20 silly cache add   spec: 'latest',
20 silly cache add   type: 'tag' }
21 silly addNamed ionic@latest
22 verbose addNamed "latest" is being treated as a dist-tag for ionic
23 info addNameTag [ 'ionic', 'latest' ]
24 silly mapToRegistry name ionic
25 silly mapToRegistry using default registry
26 silly mapToRegistry registry https://registry.npmjs.org/
27 silly mapToRegistry data Result {
27 silly mapToRegistry   raw: 'ionic',
27 silly mapToRegistry   scope: null,
27 silly mapToRegistry   name: 'ionic',
27 silly mapToRegistry   rawSpec: '',
27 silly mapToRegistry   spec: 'latest',
27 silly mapToRegistry   type: 'tag' }
28 silly mapToRegistry uri https://registry.npmjs.org/ionic
29 verbose addNameTag registry:https://registry.npmjs.org/ionic not in flight; fetching
30 verbose request uri https://registry.npmjs.org/cordova
31 verbose request no auth needed
32 info attempt registry request try #1 at 11:15:53 AM
33 verbose request id f7759cc35a681be2
34 http request GET https://registry.npmjs.org/cordova
35 verbose request uri https://registry.npmjs.org/ionic
36 verbose request no auth needed
37 info attempt registry request try #1 at 11:15:53 AM
38 http request GET https://registry.npmjs.org/ionic
39 info retry will retry, error on last attempt: Error: tunneling socket could not be established, statusCode=407
40 info retry will retry, error on last attempt: Error: tunneling socket could not be established, statusCode=407
41 info attempt registry request try #2 at 11:16:03 AM
42 http request GET https://registry.npmjs.org/cordova
43 info attempt registry request try #2 at 11:16:03 AM
44 http request GET https://registry.npmjs.org/ionic
45 info retry will retry, error on last attempt: Error: tunneling socket could not be established, statusCode=407
46 info retry will retry, error on last attempt: Error: tunneling socket could not be established, statusCode=407
47 info attempt registry request try #3 at 11:17:03 AM
48 http request GET https://registry.npmjs.org/cordova
49 info attempt registry request try #3 at 11:17:03 AM
50 http request GET https://registry.npmjs.org/ionic
51 verbose stack Error: tunneling socket could not be established, statusCode=407
51 verbose stack     at ClientRequest.onConnect (C:\Program Files\nodejs\node_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:165:19)
51 verbose stack     at ClientRequest.g (events.js:260:16)
51 verbose stack     at emitThree (events.js:97:13)
51 verbose stack     at ClientRequest.emit (events.js:175:7)
51 verbose stack     at Socket.socketOnData (_http_client.js:354:11)
51 verbose stack     at emitOne (events.js:77:13)
51 verbose stack     at Socket.emit (events.js:169:7)
51 verbose stack     at readableAddChunk (_stream_readable.js:153:18)
51 verbose stack     at Socket.Readable.push (_stream_readable.js:111:10)
51 verbose stack     at TCP.onread (net.js:536:20)
52 verbose cwd C:\Users\areidy
53 error Windows_NT 6.1.7601
54 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova" "ionic"
55 error node v4.5.0
56 error npm  v2.15.9
57 error code ECONNRESET
58 error network tunneling socket could not be established, statusCode=407
58 error network This is most likely not a problem with npm itself
58 error network and is related to network connectivity.
58 error network In most cases you are behind a proxy or have bad network settings.
58 error network
58 error network If you are behind a proxy, please make sure that the
58 error network 'proxy' config is set properly.  See: 'npm help config'
59 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
@Albean Did you read the log? This appears to be an issue with your internet connection rather than with `npm`. Maybe you are behind a proxy or firewall?

**Comment by Albean** [comment]
Hi @KenanY ,  I tried updating the proxy setting using;

npm config set proxy http://username:password@proxy.company.com:8080
e.g - npm config set proxy http://albean:helpme?@10.1.1.47:8080

npm config set https-proxy http://username:password@proxy.company.com:8080
e.g - npm config set https-proxy http://albean:helpme?@10.10.10.

Im getting back an error;
Tunneling socket could not be established , cause = getaddrinfo ENOTFOUND

see screenshot
![npmproxy](https://cloud.githubusercontent.com/assets/8224434/18273063/5e4aed48-7433-11e6-88b9-b29e50d7f69e.png)
47:8080

**Comment by KenanY** [comment]
@Albean I'm a bit stumped to be honest. Let me know if you ever figure it out :/
