### ISSUE TITLE
npm err Darwin 15.6.0

### ISSUE THREAD

**Issue by knowbody** [npm/npm#13849]
Hey I read through a few of these issues and can't find the solution to the problem.

I run into `npm err Darwin 15.6.0` issue quite often and running various commands, for example running `npm tun test --watch` in my RN project causes it, please see `npm-debug.log`:

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/mateuszzatorski/.nvm/versions/node/v6.4.0/bin/node',
1 verbose cli   '/Users/mateuszzatorski/.nvm/versions/node/v6.4.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'test',
1 verbose cli   '--watch' ]
2 info using npm@3.10.3
3 info using node@v6.4.0
4 verbose run-script [ 'pretest', 'test', 'posttest' ]
5 info lifecycle DQ@0.0.1~pretest: DQ@0.0.1
6 silly lifecycle DQ@0.0.1~pretest: no script for pretest, continuing
7 info lifecycle DQ@0.0.1~test: DQ@0.0.1
8 verbose lifecycle DQ@0.0.1~test: unsafe-perm in lifecycle true
9 verbose lifecycle DQ@0.0.1~test: PATH: /Users/mateuszzatorski/.nvm/versions/node/v6.4.0/lib/node_modules/npm/bin/node-gyp-bin:/Users/mateuszzatorski/Projects/DiagnosticQuestions-Mobile/node_modules/.bin:/Users/mateuszzatorski/.nvm/versions/node/v6.4.0/bin:/Users/mateuszzatorski/.nvm/versions/node/v6.4.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
10 verbose lifecycle DQ@0.0.1~test: CWD: /Users/mateuszzatorski/Projects/DiagnosticQuestions-Mobile
11 silly lifecycle DQ@0.0.1~test: Args: [ '-c', 'jest' ]
12 silly lifecycle DQ@0.0.1~test: Returned: code: 1  signal: null
13 info lifecycle DQ@0.0.1~test: Failed to exec test script
14 verbose stack Error: DQ@0.0.1 test: `jest`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/Users/mateuszzatorski/.nvm/versions/node/v6.4.0/lib/node_modules/npm/lib/utils/lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/Users/mateuszzatorski/.nvm/versions/node/v6.4.0/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:852:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid DQ@0.0.1
16 verbose cwd /Users/mateuszzatorski/Projects/DiagnosticQuestions-Mobile
17 error Darwin 15.6.0
18 error argv "/Users/mateuszzatorski/.nvm/versions/node/v6.4.0/bin/node" "/Users/mateuszzatorski/.nvm/versions/node/v6.4.0/bin/npm" "run" "test" "--watch"
19 error node v6.4.0
20 error npm  v3.10.3
21 error code ELIFECYCLE
22 error DQ@0.0.1 test: `jest`
22 error Exit status 1
23 error Failed at the DQ@0.0.1 test script 'jest'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the DQ package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     jest
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs DQ
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls DQ
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
@knowbody As the log indicates, your `"test"` script is returning an error code. This isn't the fault of `npm`, the issue must lie with your script somehow. `npm` is just catching the error for you. Make sure `jest` runs without error.

**Comment by knowbody** [comment]
thank you!

**Comment by oberoi-ishant** [comment]
Hi @knowbody,

Did you find the reason for error above? I am facing the same issue with jest testing
