### ISSUE TITLE
npm ERR! Darwin 15.4.0

### ISSUE THREAD

**Issue by iakomus** [npm/npm#13854]
After running `nudo npm version 0.21.0 --no-git-tag-version`, I'm getting this error:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'version',
1 verbose cli   '0.21.0',
1 verbose cli   '--no-git-tag-version' ]
2 info using npm@2.15.9
3 info using node@v4.5.0
4 verbose stack Error: Version not changed
4 verbose stack     at /usr/local/lib/node_modules/npm/lib/version.js:51:49
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
5 verbose cwd /Users/iakomus/Projects/digitalbridge/digitalbridge-sdk-compiled
6 error Darwin 15.4.0
7 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "version" "0.21.0" "--no-git-tag-version"
8 error node v4.5.0
9 error npm  v2.15.9
10 error Version not changed
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
```

and I cannot find why...

**Comment by iakomus** [comment]
Nevermind

package.json had the same version as the one I added in command line
