### ISSUE TITLE
npm ERR! Windows_NT 6.3.9600 - UNABLE_TO_VERIFY_LEAF_SIGNATURE

### ISSUE THREAD

**Issue by arame3333** [npm/npm#13915]
I logged in as the administrator for the command line, and I type

npm install

and then I get these error messages;
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\
node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code UNABLE_TO_VERIFY_LEAF_SIGNATURE

npm ERR! unable to verify the first certificate
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     c:\Users\geoffreypayne\Documents\Pluralsight\Angular2-GettingStarte
d-master\APM\app\npm-debug.log

My log file shows;

0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files\nodejs\node.exe',
1 verbose cli   'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@2.15.9
3 info using node@v4.5.0
4 verbose readDependencies loading dependencies from c:\Users\geoffreypayne\Documents\Pluralsight\Angular2-GettingStarted-master\APM\package.json
5 verbose install where, deps [ 'c:\Users\geoffreypayne\Documents\Pluralsight\Angular2-GettingStarted-master\APM',
5 verbose install   [ 'angular2',
5 verbose install     'systemjs',
5 verbose install     'es6-shim',
5 verbose install     'reflect-metadata',
5 verbose install     'rxjs',
5 verbose install     'zone.js',
5 verbose install     'bootstrap',
5 verbose install     'concurrently',
5 verbose install     'lite-server',
5 verbose install     'typescript',
5 verbose install     'typings' ] ]
6 verbose install where, peers [ 'c:\Users\geoffreypayne\Documents\Pluralsight\Angular2-GettingStarted-master\APM',
6 verbose install   [] ]
7 verbose installManyTop reading for lifecycle c:\Users\geoffreypayne\Documents\Pluralsight\Angular2-GettingStarted-master\APM\package.json
8 info preinstall product-management@1.0.0
9 verbose readDependencies loading dependencies from c:\Users\geoffreypayne\Documents\Pluralsight\Angular2-GettingStarted-master\APM\package.json
10 silly cache add args [ 'angular2@2.0.0-beta.15', null ]
11 verbose cache add spec angular2@2.0.0-beta.15
12 silly cache add args [ 'systemjs@0.19.26', null ]
13 verbose cache add spec systemjs@0.19.26
14 silly cache add parsed spec Result {
14 silly cache add   raw: 'angular2@2.0.0-beta.15',
14 silly cache add   scope: null,
14 silly cache add   name: 'angular2',
14 silly cache add   rawSpec: '2.0.0-beta.15',
14 silly cache add   spec: '2.0.0-beta.15',
14 silly cache add   type: 'version' }
15 silly addNamed angular2@2.0.0-beta.15
16 verbose addNamed "2.0.0-beta.15" is a plain semver version for angular2
17 silly mapToRegistry name angular2
18 silly mapToRegistry using default registry
19 silly mapToRegistry registry https://registry.npmjs.org/
20 silly mapToRegistry data Result {
20 silly mapToRegistry   raw: 'angular2',
20 silly mapToRegistry   scope: null,
20 silly mapToRegistry   name: 'angular2',
20 silly mapToRegistry   rawSpec: '',
20 silly mapToRegistry   spec: 'latest',
20 silly mapToRegistry   type: 'tag' }
21 silly mapToRegistry uri https://registry.npmjs.org/angular2
22 verbose addNameVersion registry:https://registry.npmjs.org/angular2 not in flight; fetching
23 silly cache add parsed spec Result {
23 silly cache add   raw: 'systemjs@0.19.26',
23 silly cache add   scope: null,
23 silly cache add   name: 'systemjs',
23 silly cache add   rawSpec: '0.19.26',
23 silly cache add   spec: '0.19.26',
23 silly cache add   type: 'version' }
24 silly addNamed systemjs@0.19.26
25 verbose addNamed "0.19.26" is a plain semver version for systemjs
26 silly mapToRegistry name systemjs
27 silly mapToRegistry using default registry
28 silly mapToRegistry registry https://registry.npmjs.org/
29 silly mapToRegistry data Result {
29 silly mapToRegistry   raw: 'systemjs',
29 silly mapToRegistry   scope: null,
29 silly mapToRegistry   name: 'systemjs',
29 silly mapToRegistry   rawSpec: '',
29 silly mapToRegistry   spec: 'latest',
29 silly mapToRegistry   type: 'tag' }
30 silly mapToRegistry uri https://registry.npmjs.org/systemjs
31 verbose addNameVersion registry:https://registry.npmjs.org/systemjs not in flight; fetching
32 silly cache add args [ 'es6-shim@^0.35.0', null ]
33 verbose cache add spec es6-shim@^0.35.0
34 silly cache add parsed spec Result {
34 silly cache add   raw: 'es6-shim@^0.35.0',
34 silly cache add   scope: null,
34 silly cache add   name: 'es6-shim',
34 silly cache add   rawSpec: '^0.35.0',
34 silly cache add   spec: '>=0.35.0 <0.36.0',
34 silly cache add   type: 'range' }
35 silly addNamed es6-shim@>=0.35.0 <0.36.0
36 verbose addNamed ">=0.35.0 <0.36.0" is a valid semver range for es6-shim
37 silly addNameRange { name: 'es6-shim', range: '>=0.35.0 <0.36.0', hasData: false }
38 silly mapToRegistry name es6-shim
39 silly mapToRegistry using default registry
40 silly mapToRegistry registry https://registry.npmjs.org/
41 silly mapToRegistry data Result {
41 silly mapToRegistry   raw: 'es6-shim',
41 silly mapToRegistry   scope: null,
41 silly mapToRegistry   name: 'es6-shim',
41 silly mapToRegistry   rawSpec: '',
41 silly mapToRegistry   spec: 'latest',
41 silly mapToRegistry   type: 'tag' }
42 silly mapToRegistry uri https://registry.npmjs.org/es6-shim
43 verbose addNameRange registry:https://registry.npmjs.org/es6-shim not in flight; fetching
44 silly cache add args [ 'reflect-metadata@0.1.2', null ]
45 verbose cache add spec reflect-metadata@0.1.2
46 silly cache add parsed spec Result {
46 silly cache add   raw: 'reflect-metadata@0.1.2',
46 silly cache add   scope: null,
46 silly cache add   name: 'reflect-metadata',
46 silly cache add   rawSpec: '0.1.2',
46 silly cache add   spec: '0.1.2',
46 silly cache add   type: 'version' }
47 silly addNamed reflect-metadata@0.1.2
48 verbose addNamed "0.1.2" is a plain semver version for reflect-metadata
49 silly mapToRegistry name reflect-metadata
50 silly mapToRegistry using default registry
51 silly mapToRegistry registry https://registry.npmjs.org/
52 silly mapToRegistry data Result {
52 silly mapToRegistry   raw: 'reflect-metadata',
52 silly mapToRegistry   scope: null,
52 silly mapToRegistry   name: 'reflect-metadata',
52 silly mapToRegistry   rawSpec: '',
52 silly mapToRegistry   spec: 'latest',
52 silly mapToRegistry   type: 'tag' }
53 silly mapToRegistry uri https://registry.npmjs.org/reflect-metadata
54 verbose addNameVersion registry:https://registry.npmjs.org/reflect-metadata not in flight; fetching
55 silly cache add args [ 'rxjs@5.0.0-beta.2', null ]
56 verbose cache add spec rxjs@5.0.0-beta.2
57 silly cache add parsed spec Result {
57 silly cache add   raw: 'rxjs@5.0.0-beta.2',
57 silly cache add   scope: null,
57 silly cache add   name: 'rxjs',
57 silly cache add   rawSpec: '5.0.0-beta.2',
57 silly cache add   spec: '5.0.0-beta.2',
57 silly cache add   type: 'version' }
58 silly addNamed rxjs@5.0.0-beta.2
59 verbose addNamed "5.0.0-beta.2" is a plain semver version for rxjs
60 silly mapToRegistry name rxjs
61 silly mapToRegistry using default registry
62 silly mapToRegistry registry https://registry.npmjs.org/
63 silly mapToRegistry data Result {
63 silly mapToRegistry   raw: 'rxjs',
63 silly mapToRegistry   scope: null,
63 silly mapToRegistry   name: 'rxjs',
63 silly mapToRegistry   rawSpec: '',
63 silly mapToRegistry   spec: 'latest',
63 silly mapToRegistry   type: 'tag' }
64 silly mapToRegistry uri https://registry.npmjs.org/rxjs
65 verbose addNameVersion registry:https://registry.npmjs.org/rxjs not in flight; fetching
66 silly cache add args [ 'zone.js@0.6.10', null ]
67 verbose cache add spec zone.js@0.6.10
68 silly cache add parsed spec Result {
68 silly cache add   raw: 'zone.js@0.6.10',
68 silly cache add   scope: null,
68 silly cache add   name: 'zone.js',
68 silly cache add   rawSpec: '0.6.10',
68 silly cache add   spec: '0.6.10',
68 silly cache add   type: 'version' }
69 silly addNamed zone.js@0.6.10
70 verbose addNamed "0.6.10" is a plain semver version for zone.js
71 silly mapToRegistry name zone.js
72 silly mapToRegistry using default registry
73 silly mapToRegistry registry https://registry.npmjs.org/
74 silly mapToRegistry data Result {
74 silly mapToRegistry   raw: 'zone.js',
74 silly mapToRegistry   scope: null,
74 silly mapToRegistry   name: 'zone.js',
74 silly mapToRegistry   rawSpec: '',
74 silly mapToRegistry   spec: 'latest',
74 silly mapToRegistry   type: 'tag' }
75 silly mapToRegistry uri https://registry.npmjs.org/zone.js
76 verbose addNameVersion registry:https://registry.npmjs.org/zone.js not in flight; fetching
77 silly cache add args [ 'bootstrap@^3.3.6', null ]
78 verbose cache add spec bootstrap@^3.3.6
79 silly cache add parsed spec Result {
79 silly cache add   raw: 'bootstrap@^3.3.6',
79 silly cache add   scope: null,
79 silly cache add   name: 'bootstrap',
79 silly cache add   rawSpec: '^3.3.6',
79 silly cache add   spec: '>=3.3.6 <4.0.0',
79 silly cache add   type: 'range' }
80 silly addNamed bootstrap@>=3.3.6 <4.0.0
81 verbose addNamed ">=3.3.6 <4.0.0" is a valid semver range for bootstrap
82 silly addNameRange { name: 'bootstrap', range: '>=3.3.6 <4.0.0', hasData: false }
83 silly mapToRegistry name bootstrap
84 silly mapToRegistry using default registry
85 silly mapToRegistry registry https://registry.npmjs.org/
86 silly mapToRegistry data Result {
86 silly mapToRegistry   raw: 'bootstrap',
86 silly mapToRegistry   scope: null,
86 silly mapToRegistry   name: 'bootstrap',
86 silly mapToRegistry   rawSpec: '',
86 silly mapToRegistry   spec: 'latest',
86 silly mapToRegistry   type: 'tag' }
87 silly mapToRegistry uri https://registry.npmjs.org/bootstrap
88 verbose addNameRange registry:https://registry.npmjs.org/bootstrap not in flight; fetching
89 silly cache add args [ 'concurrently@^2.0.0', null ]
90 verbose cache add spec concurrently@^2.0.0
91 silly cache add parsed spec Result {
91 silly cache add   raw: 'concurrently@^2.0.0',
91 silly cache add   scope: null,
91 silly cache add   name: 'concurrently',
91 silly cache add   rawSpec: '^2.0.0',
91 silly cache add   spec: '>=2.0.0 <3.0.0',
91 silly cache add   type: 'range' }
92 silly addNamed concurrently@>=2.0.0 <3.0.0
93 verbose addNamed ">=2.0.0 <3.0.0" is a valid semver range for concurrently
94 silly addNameRange { name: 'concurrently', range: '>=2.0.0 <3.0.0', hasData: false }
95 silly mapToRegistry name concurrently
96 silly mapToRegistry using default registry
97 silly mapToRegistry registry https://registry.npmjs.org/
98 silly mapToRegistry data Result {
98 silly mapToRegistry   raw: 'concurrently',
98 silly mapToRegistry   scope: null,
98 silly mapToRegistry   name: 'concurrently',
98 silly mapToRegistry   rawSpec: '',
98 silly mapToRegistry   spec: 'latest',
98 silly mapToRegistry   type: 'tag' }
99 silly mapToRegistry uri https://registry.npmjs.org/concurrently
100 verbose addNameRange registry:https://registry.npmjs.org/concurrently not in flight; fetching
101 silly cache add args [ 'lite-server@^2.2.0', null ]
102 verbose cache add spec lite-server@^2.2.0
103 silly cache add parsed spec Result {
103 silly cache add   raw: 'lite-server@^2.2.0',
103 silly cache add   scope: null,
103 silly cache add   name: 'lite-server',
103 silly cache add   rawSpec: '^2.2.0',
103 silly cache add   spec: '>=2.2.0 <3.0.0',
103 silly cache add   type: 'range' }
104 silly addNamed lite-server@>=2.2.0 <3.0.0
105 verbose addNamed ">=2.2.0 <3.0.0" is a valid semver range for lite-server
106 silly addNameRange { name: 'lite-server', range: '>=2.2.0 <3.0.0', hasData: false }
107 silly mapToRegistry name lite-server
108 silly mapToRegistry using default registry
109 silly mapToRegistry registry https://registry.npmjs.org/
110 silly mapToRegistry data Result {
110 silly mapToRegistry   raw: 'lite-server',
110 silly mapToRegistry   scope: null,
110 silly mapToRegistry   name: 'lite-server',
110 silly mapToRegistry   rawSpec: '',
110 silly mapToRegistry   spec: 'latest',
110 silly mapToRegistry   type: 'tag' }
111 silly mapToRegistry uri https://registry.npmjs.org/lite-server
112 verbose addNameRange registry:https://registry.npmjs.org/lite-server not in flight; fetching
113 silly cache add args [ 'typescript@^1.8.10', null ]
114 verbose cache add spec typescript@^1.8.10
115 silly cache add parsed spec Result {
115 silly cache add   raw: 'typescript@^1.8.10',
115 silly cache add   scope: null,
115 silly cache add   name: 'typescript',
115 silly cache add   rawSpec: '^1.8.10',
115 silly cache add   spec: '>=1.8.10 <2.0.0',
115 silly cache add   type: 'range' }
116 silly addNamed typescript@>=1.8.10 <2.0.0
117 verbose addNamed ">=1.8.10 <2.0.0" is a valid semver range for typescript
118 silly addNameRange { name: 'typescript', range: '>=1.8.10 <2.0.0', hasData: false }
119 silly mapToRegistry name typescript
120 silly mapToRegistry using default registry
121 silly mapToRegistry registry https://registry.npmjs.org/
122 silly mapToRegistry data Result {
122 silly mapToRegistry   raw: 'typescript',
122 silly mapToRegistry   scope: null,
122 silly mapToRegistry   name: 'typescript',
122 silly mapToRegistry   rawSpec: '',
122 silly mapToRegistry   spec: 'latest',
122 silly mapToRegistry   type: 'tag' }
123 silly mapToRegistry uri https://registry.npmjs.org/typescript
124 verbose addNameRange registry:https://registry.npmjs.org/typescript not in flight; fetching
125 silly cache add args [ 'typings@^0.7.12', null ]
126 verbose cache add spec typings@^0.7.12
127 silly cache add parsed spec Result {
127 silly cache add   raw: 'typings@^0.7.12',
127 silly cache add   scope: null,
127 silly cache add   name: 'typings',
127 silly cache add   rawSpec: '^0.7.12',
127 silly cache add   spec: '>=0.7.12 <0.8.0',
127 silly cache add   type: 'range' }
128 silly addNamed typings@>=0.7.12 <0.8.0
129 verbose addNamed ">=0.7.12 <0.8.0" is a valid semver range for typings
130 silly addNameRange { name: 'typings', range: '>=0.7.12 <0.8.0', hasData: false }
131 silly mapToRegistry name typings
132 silly mapToRegistry using default registry
133 silly mapToRegistry registry https://registry.npmjs.org/
134 silly mapToRegistry data Result {
134 silly mapToRegistry   raw: 'typings',
134 silly mapToRegistry   scope: null,
134 silly mapToRegistry   name: 'typings',
134 silly mapToRegistry   rawSpec: '',
134 silly mapToRegistry   spec: 'latest',
134 silly mapToRegistry   type: 'tag' }
135 silly mapToRegistry uri https://registry.npmjs.org/typings
136 verbose addNameRange registry:https://registry.npmjs.org/typings not in flight; fetching
137 verbose request uri https://registry.npmjs.org/angular2
138 verbose request no auth needed
139 info attempt registry request try #1 at 10:12:34 AM
140 verbose request id e31ed53e1df033be
141 http request GET https://registry.npmjs.org/angular2
142 verbose request uri https://registry.npmjs.org/systemjs
143 verbose request no auth needed
144 info attempt registry request try #1 at 10:12:34 AM
145 http request GET https://registry.npmjs.org/systemjs
146 verbose request uri https://registry.npmjs.org/es6-shim
147 verbose request no auth needed
148 info attempt registry request try #1 at 10:12:34 AM
149 http request GET https://registry.npmjs.org/es6-shim
150 verbose request uri https://registry.npmjs.org/reflect-metadata
151 verbose request no auth needed
152 info attempt registry request try #1 at 10:12:34 AM
153 http request GET https://registry.npmjs.org/reflect-metadata
154 verbose request uri https://registry.npmjs.org/rxjs
155 verbose request no auth needed
156 info attempt registry request try #1 at 10:12:34 AM
157 http request GET https://registry.npmjs.org/rxjs
158 verbose request uri https://registry.npmjs.org/zone.js
159 verbose request no auth needed
160 info attempt registry request try #1 at 10:12:34 AM
161 http request GET https://registry.npmjs.org/zone.js
162 verbose request uri https://registry.npmjs.org/bootstrap
163 verbose request no auth needed
164 info attempt registry request try #1 at 10:12:34 AM
165 http request GET https://registry.npmjs.org/bootstrap
166 verbose request uri https://registry.npmjs.org/concurrently
167 verbose request no auth needed
168 info attempt registry request try #1 at 10:12:34 AM
169 http request GET https://registry.npmjs.org/concurrently
170 verbose request uri https://registry.npmjs.org/lite-server
171 verbose request no auth needed
172 info attempt registry request try #1 at 10:12:34 AM
173 http request GET https://registry.npmjs.org/lite-server
174 verbose request uri https://registry.npmjs.org/typescript
175 verbose request no auth needed
176 info attempt registry request try #1 at 10:12:34 AM
177 http request GET https://registry.npmjs.org/typescript
178 verbose request uri https://registry.npmjs.org/typings
179 verbose request no auth needed
180 info attempt registry request try #1 at 10:12:34 AM
181 http request GET https://registry.npmjs.org/typings
182 info retry will retry, error on last attempt: Error: unable to verify the first certificate
183 info retry will retry, error on last attempt: Error: unable to verify the first certificate
184 info retry will retry, error on last attempt: Error: unable to verify the first certificate
185 info retry will retry, error on last attempt: Error: unable to verify the first certificate
186 info retry will retry, error on last attempt: Error: unable to verify the first certificate
187 info retry will retry, error on last attempt: Error: unable to verify the first certificate
188 info retry will retry, error on last attempt: Error: unable to verify the first certificate
189 info retry will retry, error on last attempt: Error: unable to verify the first certificate
190 info retry will retry, error on last attempt: Error: unable to verify the first certificate
191 info retry will retry, error on last attempt: Error: unable to verify the first certificate
192 info retry will retry, error on last attempt: Error: unable to verify the first certificate
193 info attempt registry request try #2 at 10:12:44 AM
194 http request GET https://registry.npmjs.org/bootstrap
195 info attempt registry request try #2 at 10:12:44 AM
196 http request GET https://registry.npmjs.org/reflect-metadata
197 info attempt registry request try #2 at 10:12:44 AM
198 http request GET https://registry.npmjs.org/zone.js
199 info attempt registry request try #2 at 10:12:44 AM
200 http request GET https://registry.npmjs.org/lite-server
201 info attempt registry request try #2 at 10:12:44 AM
202 http request GET https://registry.npmjs.org/es6-shim
203 info attempt registry request try #2 at 10:12:44 AM
204 http request GET https://registry.npmjs.org/systemjs
205 info attempt registry request try #2 at 10:12:44 AM
206 http request GET https://registry.npmjs.org/typescript
207 info attempt registry request try #2 at 10:12:44 AM
208 http request GET https://registry.npmjs.org/typings
209 info attempt registry request try #2 at 10:12:44 AM
210 http request GET https://registry.npmjs.org/concurrently
211 info attempt registry request try #2 at 10:12:44 AM
212 http request GET https://registry.npmjs.org/rxjs
213 info retry will retry, error on last attempt: Error: unable to verify the first certificate
214 info attempt registry request try #2 at 10:12:44 AM
215 http request GET https://registry.npmjs.org/angular2
216 info retry will retry, error on last attempt: Error: unable to verify the first certificate
217 info retry will retry, error on last attempt: Error: unable to verify the first certificate
218 info retry will retry, error on last attempt: Error: unable to verify the first certificate
219 info retry will retry, error on last attempt: Error: unable to verify the first certificate
220 info retry will retry, error on last attempt: Error: unable to verify the first certificate
221 info retry will retry, error on last attempt: Error: unable to verify the first certificate
222 info retry will retry, error on last attempt: Error: unable to verify the first certificate
223 info retry will retry, error on last attempt: Error: unable to verify the first certificate
224 info retry will retry, error on last attempt: Error: unable to verify the first certificate
225 info retry will retry, error on last attempt: Error: unable to verify the first certificate
226 info attempt registry request try #3 at 10:13:44 AM
227 http request GET https://registry.npmjs.org/zone.js
228 info attempt registry request try #3 at 10:13:44 AM
229 http request GET https://registry.npmjs.org/bootstrap
230 info attempt registry request try #3 at 10:13:44 AM
231 http request GET https://registry.npmjs.org/reflect-metadata
232 info attempt registry request try #3 at 10:13:44 AM
233 http request GET https://registry.npmjs.org/rxjs
234 info attempt registry request try #3 at 10:13:44 AM
235 http request GET https://registry.npmjs.org/concurrently
236 info attempt registry request try #3 at 10:13:44 AM
237 http request GET https://registry.npmjs.org/typings
238 info attempt registry request try #3 at 10:13:44 AM
239 http request GET https://registry.npmjs.org/angular2
240 info attempt registry request try #3 at 10:13:44 AM
241 http request GET https://registry.npmjs.org/lite-server
242 info attempt registry request try #3 at 10:13:44 AM
243 http request GET https://registry.npmjs.org/systemjs
244 info attempt registry request try #3 at 10:13:44 AM
245 http request GET https://registry.npmjs.org/typescript
246 info attempt registry request try #3 at 10:13:44 AM
247 http request GET https://registry.npmjs.org/es6-shim
248 verbose stack Error: unable to verify the first certificate
248 verbose stack     at Error (native)
248 verbose stack     at TLSSocket.<anonymous> (_tls_wrap.js:1022:38)
248 verbose stack     at emitNone (events.js:67:13)
248 verbose stack     at TLSSocket.emit (events.js:166:7)
248 verbose stack     at TLSSocket._init.ssl.onclienthello.ssl.oncertcb.TLSSocket._finishInit (_tls_wrap.js:586:8)
248 verbose stack     at TLSWrap.ssl.onclienthello.ssl.oncertcb.ssl.onnewsession.ssl.onhandshakedone (_tls_wrap.js:428:38)
249 verbose cwd c:\Users\geoffreypayne\Documents\Pluralsight\Angular2-GettingStarted-master\APM\app
250 error Windows_NT 6.3.9600
251 error argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install"
252 error node v4.5.0
253 error npm  v2.15.9
254 error code UNABLE_TO_VERIFY_LEAF_SIGNATURE
255 error unable to verify the first certificate
256 error If you need help, you may report this error at:
256 error     https://github.com/npm/npm/issues
257 verbose exit [ 1, true ]

**Comment by arame3333** [comment]
I found this issue got fixed when my colleague temporarily disabled the Firewall. This allowed the install to run.
