### ISSUE TITLE
Not able to install accounting.js of version 0.4.1

### ISSUE THREAD

**Issue by onkarojha77** [npm/npm#13960]
Getting error while trying to upload...

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/node-v4.2.4-linux-x64/bin/node',
1 verbose cli   '/usr/local/node-v4.2.4-linux-x64/bin/npm',
1 verbose cli   'install',
1 verbose cli   'accounting.js@0.4.1',
1 verbose cli   '--registry',
1 verbose cli   'http://localhost:8080/nexus/content/repositories/npmjs-proxy' ]
2 info using npm@2.14.12
3 info using node@v4.2.4
4 verbose install initial load of /opt/maestrodata/maestro_user_home/npmmanager/third-party-publisher/output/package.json
5 verbose readDependencies loading dependencies from /opt/maestrodata/maestro_user_home/npmmanager/third-party-publisher/output/package.json
6 silly cache add args [ 'accounting.js@0.4.1', null ]
7 verbose cache add spec accounting.js@0.4.1
8 silly cache add parsed spec Result {
8 silly cache add   raw: 'accounting.js@0.4.1',
8 silly cache add   scope: null,
8 silly cache add   name: 'accounting.js',
8 silly cache add   rawSpec: '0.4.1',
8 silly cache add   spec: '0.4.1',
8 silly cache add   type: 'version' }
9 silly addNamed accounting.js@0.4.1
10 verbose addNamed "0.4.1" is a plain semver version for accounting.js
11 silly mapToRegistry name accounting.js
12 silly mapToRegistry using default registry
13 silly mapToRegistry registry http://localhost:8080/nexus/content/repositories/npmjs-proxy
14 silly mapToRegistry uri http://localhost:8080/nexus/content/repositories/npmjs-proxy/accounting.js
15 verbose addNameVersion registry:http://localhost:8080/nexus/content/repositories/npmjs-proxy/accounting.js not in flight; fetching
16 verbose request uri http://localhost:8080/nexus/content/repositories/npmjs-proxy/accounting.js
17 verbose request always-auth set; sending authorization
18 info attempt registry request try #1 at 12:32:20 PM
19 verbose request id 6daee1501f15dfc7
20 http request GET http://localhost:8080/nexus/content/repositories/npmjs-proxy/accounting.js
21 http 404 http://localhost:8080/nexus/content/repositories/npmjs-proxy/accounting.js
22 verbose bad json <html>
22 verbose bad json   <head>
22 verbose bad json     <title>404 - Request is serviced by NPM metadata service, remote access not needed from DefaultNpmProxyRepository(id=npmjs-proxy)</title>
22 verbose bad json     <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
22 verbose bad json
22 verbose bad json     <link rel="icon" type="image/png" href="http://localhost:8080/nexus/favicon.png">
22 verbose bad json     <!--[if IE]>
22 verbose bad json     <link rel="SHORTCUT ICON" href="http://localhost:8080/nexus/favicon.ico"/>
22 verbose bad json     <![endif]-->
22 verbose bad json
22 verbose bad json     <link rel="stylesheet" href="http://localhost:8080/nexus/static/css/Sonatype-content.css?2.12.0-01" type="text/css" media="screen" title="no title" charset="utf-8">
22 verbose bad json   </head>
22 verbose bad json   <body>
22 verbose bad json     <h1>404 - Request is serviced by NPM metadata service, remote access not needed from DefaultNpmProxyRepository(id=npmjs-proxy)</h1>
22 verbose bad json     <p>Request is serviced by NPM metadata service, remote access not needed from DefaultNpmProxyRepository(id=npmjs-proxy)</p>
22 verbose bad json   </body>
22 verbose bad json </html>
23 error registry error parsing json
24 verbose headers { date: 'Wed, 14 Sep 2016 19:32:20 GMT',
24 verbose headers   server: 'Nexus/2.12.0-01',
24 verbose headers   'x-frame-options': 'SAMEORIGIN',
24 verbose headers   'x-content-type-options': 'nosniff',
24 verbose headers   'accept-ranges': 'bytes',
24 verbose headers   'content-type': 'text/html',
24 verbose headers   'transfer-encoding': 'chunked' }
25 silly get cb [ 404,
25 silly get   { date: 'Wed, 14 Sep 2016 19:32:20 GMT',
25 silly get     server: 'Nexus/2.12.0-01',
25 silly get     'x-frame-options': 'SAMEORIGIN',
25 silly get     'x-content-type-options': 'nosniff',
25 silly get     'accept-ranges': 'bytes',
25 silly get     'content-type': 'text/html',
25 silly get     'transfer-encoding': 'chunked' } ]
26 verbose stack SyntaxError: Unexpected token <
26 verbose stack <html>
26 verbose stack   <head>
26 verbose stack     <title>404 - Request is serviced by NPM metadata service, remote access not needed from DefaultNpmProxyRepository(id=npmjs-proxy)</title>
26 verbose stack     <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
26 verbose stack
26 verbose stack     <link rel="icon" type="image/png" href="http://localhost:8080/nexus/favicon.png">
26 verbose stack     <!--[if IE]>
26 verbose stack     <link rel="SHORTCUT ICON" href="http://localhost:8080/nexus/favicon.ico"/>
26 verbose stack     <![endif]-->
26 verbose stack
26 verbose stack     <link rel="stylesheet" href="http://localhost:8080/nexus/static/css/Sonatype-content.css?2.12.0-01" type="text/css" media="screen" title="no title" charset="utf-8">
26 verbose stack   </head>
26 verbose stack   <body>
26 verbose stack     <h1>404 - Request is serviced by NPM metadata service, remote access not needed from DefaultNpmProxyRepository(id=npmjs-proxy)</h1>
26 verbose stack     <p>Request is serviced by NPM metadata service, remote access not needed from DefaultNpmProxyRepository(id=npmjs-proxy)</p>
26 verbose stack   </body>
26 verbose stack </html>
26 verbose stack
26 verbose stack     at Object.parse (native)
26 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/node-v4.2.4-linux-x64/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:199:23)
26 verbose stack     at Request._callback (/usr/local/node-v4.2.4-linux-x64/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
26 verbose stack     at Request.self.callback (/usr/local/node-v4.2.4-linux-x64/lib/node_modules/npm/node_modules/request/request.js:198:22)
26 verbose stack     at emitTwo (events.js:87:13)
26 verbose stack     at Request.emit (events.js:172:7)
26 verbose stack     at Request.<anonymous> (/usr/local/node-v4.2.4-linux-x64/lib/node_modules/npm/node_modules/request/request.js:1082:10)
26 verbose stack     at emitOne (events.js:82:20)
26 verbose stack     at Request.emit (events.js:169:7)
26 verbose stack     at IncomingMessage.<anonymous> (/usr/local/node-v4.2.4-linux-x64/lib/node_modules/npm/node_modules/request/request.js:1009:12)
27 verbose cwd /opt/maestrodata/maestro_user_home/npmmanager/third-party-publisher/output
28 error Linux 2.6.32-431.el6.x86_64
29 error argv "/usr/local/node-v4.2.4-linux-x64/bin/node" "/usr/local/node-v4.2.4-linux-x64/bin/npm" "install" "accounting.js@0.4.1" "--registry" "http://localhost:8080/nexus/content/repositories/npmjs-proxy"
30 error node v4.2.4
31 error npm  v2.14.12
32 error Unexpected token <
32 error <html>
32 error   <head>
32 error     <title>404 - Request is serviced by NPM metadata service, remote access not needed from DefaultNpmProxyRepository(id=npmjs-proxy)</title>
32 error     <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
32 error
32 error     <link rel="icon" type="image/png" href="http://localhost:8080/nexus/favicon.png">
32 error     <!--[if IE]>
32 error     <link rel="SHORTCUT ICON" href="http://localhost:8080/nexus/favicon.ico"/>
32 error     <![endif]-->
32 error
32 error     <link rel="stylesheet" href="http://localhost:8080/nexus/static/css/Sonatype-content.css?2.12.0-01" type="text/css" media="screen" title="no title" charset="utf-8">
32 error   </head>
32 error   <body>
32 error     <h1>404 - Request is serviced by NPM metadata service, remote access not needed from DefaultNpmProxyRepository(id=npmjs-proxy)</h1>
32 error     <p>Request is serviced by NPM metadata service, remote access not needed from DefaultNpmProxyRepository(id=npmjs-proxy)</p>
32 error   </body>
32 error </html>
33 error If you need help, you may report this error at:
33 error     <https://github.com/npm/npm/issues>
34 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
@onkarojha77 This looks like an issue with your proxy or something. Does this also occur with the default registry?

**Comment by KenanY** [comment]
Closing as abandoned.

**Comment by arielb2** [comment]
only for the record https://issues.sonatype.org/browse/NEXUS-10493
