### ISSUE TITLE
npm3 dedupe: Cannot read property 'localeCompare' of null

### ISSUE THREAD

**Issue by roblg** [npm/npm#13975]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

Running `npm install` followed by `npm dedupe` with a particular package.json will cause npm to crash. This looks maybe related to #9766, but it's tough to tell, and I'm running a version of `npm` that was supposed to have the fix for that.

```
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3

npm ERR! Cannot read property 'localeCompare' of null
npm ERR!
```

#### How can the CLI team reproduce the problem?

Use the following [package.json](https://gist.github.com/roblg/eb25e86c6f57eb84c715c9bcd41016e8)

Run:

* `npm install`
* `npm dedupe`
* :boom:

Removing `gulp-david` from the `package.json` makes the issue go away (and makes `dedupe` run a lot faster!) My pet theory is that because `gulp-david` depends on `npm` via `david`, that somehow `npm` being in the tree is causing the issue, but I couldn't come up with a better repro. (It also looks the comparison that throws the issue involves a module with location `npm`).

My [npm-debug.log](https://gist.github.com/roblg/2c24a27d69a49c05e5dbd0450ad83ef9)

### supporting information:

 - `npm -v` prints: 3.10.3 (also 3.10.7)
 - `node -v` prints: v6.5.0
 - `npm config get registry` prints: public registry
 - Windows, OS X, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by johnpaxton** [comment]
I'm experiencing the same issue. 
```
npm dedupe
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "dedupe"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.8

npm ERR! Cannot read property 'localeCompare' of null
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Projects\angular2\ng2-class\npm-debug.log
```

I'm running it against this package.json (which is the suggested package.json for Angular JS v2 with a few add-ons like angular-cli): 
```
{
  "name": "redacted",
  "version": "0.5.0",
  "scripts": {
    "start": "tsc && concurrently \"npm run tsc:w\" \"npm run lite\" ",
    "lite": "lite-server",
    "postinstall": "typings install",
    "tsc": "tsc",
    "tsc:w": "tsc -w",
    "typings": "typings"
  },
  "repository": {},
  "description": "redacted",
  "license": "ISC",
  "dependencies": {
    "@angular/common": "2.0.0",
    "@angular/compiler": "2.0.0",
    "@angular/core": "2.0.0",
    "@angular/forms": "2.0.0",
    "@angular/http": "2.0.0",
    "@angular/platform-browser": "2.0.0",
    "@angular/platform-browser-dynamic": "2.0.0",
    "@angular/router": "3.0.0",
    "@angular/upgrade": "2.0.0",
    "angular-cli": "^1.0.0-beta.14",
    "angular2-in-memory-web-api": "0.0.20",
    "bootstrap": "^3.3.6",
    "core-js": "^2.4.1",
    "npm": "^3.10.7",
    "reflect-metadata": "^0.1.3",
    "rxjs": "5.0.0-beta.12",
    "systemjs": "0.19.27",
    "webpack": "^2.1.0-beta.22",
    "zone.js": "^0.6.23"
  },
  "devDependencies": {
    "concurrently": "^2.2.0",
    "lite-server": "^2.2.2",
    "typescript": "^2.0.2",
    "typings": "^1.3.2"
  }
}
```

**Comment by SimenB** [comment]
Same issue in 3.10.9, node 6.7

https://gist.github.com/SimenB/86d7839040878f3b9cc07607f0eddfa5

**Comment by cedx** [comment]
Also here :(

```
$ npm dedupe
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "dedupe"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8

npm ERR! Cannot read property 'localeCompare' of null
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /repo/aqf-press/npm-debug.log
```

An extract from the `npm` log :

```
[...]
silly generateActionsToTake Starting
21 silly dedupe generateActionsToTake
22 silly hoist Starting
23 silly hoist Finishing
24 silly sort-actions Starting
25 verbose stack TypeError: Cannot read property 'localeCompare' of null
25 verbose stack     at sortByLocation (/usr/local/lib/node_modules/npm/lib/install/diff-trees.js:97:14)
25 verbose stack     at sortModuleByLocation (/usr/local/lib/node_modules/npm/lib/install/diff-trees.js:100:12)
25 verbose stack     at Array.sort (native)
25 verbose stack     at sortByDeps (/usr/local/lib/node_modules/npm/lib/install/diff-trees.js:107:20)
25 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/diff-trees.js:93:5
25 verbose stack     at Array.forEach (native)
25 verbose stack     at module.exports.sortActions (/usr/local/lib/node_modules/npm/lib/install/diff-trees.js:92:30)
25 verbose stack     at Deduper.<anonymous> (/usr/local/lib/node_modules/npm/lib/dedupe.js:93:26)
25 verbose stack     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
25 verbose stack     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
[...]
```

**Comment by yokuze** [comment]
Same issue here with:

```
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "dedupe"
npm ERR! node v4.6.1
npm ERR! npm  v4.0.2

npm ERR! Cannot read property 'localeCompare' of null
```

**Comment by atoikka** [comment]
Same here with:
```
npm ERR! node v4.6.0
npm ERR! npm  v3.10.8

npm ERR! Cannot read property 'localeCompare' of null
```

Am I doing something wrong? This issue started a few months ago.
Clearing the workspace and doing a fresh npm install doesn't work unfortunately.

**Comment by derhuerst** [comment]
I have the name issue.

```shell
npm dedupe
```

```
npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/Cellar/node/7.5.0/bin/node" "/usr/local/bin/npm" "dedupe"
npm ERR! node v7.5.0
npm ERR! npm  v4.2.0

npm ERR! Cannot read property 'localeCompare' of null
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/j/.npm/_logs/2017-02-07T19_56_55_828Z-debug.log
```

[2017-02-07T19_56_55_828Z-debug.log.txt](https://github.com/npm/npm/files/758831/2017-02-07T19_56_55_828Z-debug.log.txt)

**Comment by asdw741111** [comment]
same issue

`npm ERR! Windows_NT 10.0.15031
npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "dedupe"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10

npm ERR! Cannot read property 'localeCompare' of null`

**Comment by asdw741111** [comment]
same issue
```
npm ERR! Windows_NT 10.0.15031
npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "dedupe"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10

npm ERR! Cannot read property 'localeCompare' of null`
```

**Comment by davidrapin** [comment]
Same issue here, on OSX with npm v4.2.1 and node v7.5.0.
Happened after adding dependency `"tar.gz": "1.0.5"`, removing the dependency fixed the issue.

**Comment by briandipalma** [comment]
Multiple applications symlinking to the same shared packages but a different combination of them seems to trigger it for me.

I have to `git clean -dxf` the `node_modules` directories in the shared packages directory to allow each app to install correctly. It means that when I switch between apps I have to clean and reinstall :/

I imagine the CLI is being tricked into believing the symlinked package has all its dependencies installed when in fact it doesn't?

```
3876 silly idealTree └─┬ zip-stream@1.1.1
3876 silly idealTree   └── lodash@4.17.4
3877 silly install generateActionsToTake
3878 verbose stack TypeError: Cannot read property 'localeCompare' of null
3878 verbose stack     at sortByLocation (/Users/briand/.nvm/versions/node/v8.1.0/lib/node_modules/npm/lib/install/diff-trees.js:88:14)
3878 verbose stack     at sortModuleByLocation (/Users/briand/.nvm/versions/node/v8.1.0/lib/node_modules/npm/lib/install/diff-trees.js:91:12)
3878 verbose stack     at Array.sort (native)
3878 verbose stack     at sortByDeps (/Users/briand/.nvm/versions/node/v8.1.0/lib/node_modules/npm/lib/install/diff-trees.js:98:20)
3878 verbose stack     at /Users/briand/.nvm/versions/node/v8.1.0/lib/node_modules/npm/lib/install/diff-trees.js:84:5
3878 verbose stack     at Array.forEach (native)
3878 verbose stack     at module.exports.sortActions (/Users/briand/.nvm/versions/node/v8.1.0/lib/node_modules/npm/lib/install/diff-trees.js:83:30)
3878 verbose stack     at module.exports (/Users/briand/.nvm/versions/node/v8.1.0/lib/node_modules/npm/lib/install/diff-trees.js:48:24)
3878 verbose stack     at Array.<anonymous> (/Users/briand/.nvm/versions/node/v8.1.0/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
3878 verbose stack     at LOOP (/Users/briand/.nvm/versions/node/v8.1.0/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
3878 verbose stack     at /Users/briand/.nvm/versions/node/v8.1.0/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
3878 verbose stack     at /Users/briand/.nvm/versions/node/v8.1.0/lib/node_modules/npm/lib/install/and-finish-tracker.js:8:8
3878 verbose stack     at LOOP (/Users/briand/.nvm/versions/node/v8.1.0/lib/node_modules/npm/node_modules/slide/lib/chain.js:7:26)
3878 verbose stack     at /Users/briand/.nvm/versions/node/v8.1.0/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
3878 verbose stack     at thenCheckDuplicateDeps (/Users/briand/.nvm/versions/node/v8.1.0/lib/node_modules/npm/lib/install/validate-tree.js:94:3)
3878 verbose stack     at Array.<anonymous> (/Users/briand/.nvm/versions/node/v8.1.0/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
```

12:45 $ npm --version
5.0.3

12:50 $ node --version
v8.1.0

**Comment by emphaticsunshine** [comment]
any update on this?
