### ISSUE TITLE
refusing to install webpack as dependency of itself

### ISSUE THREAD

**Issue by roninmittal** [npm/npm#13994]
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Ronin\\node-global\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '--save-dev',
1 verbose cli   'webpack' ]
2 info using npm@3.8.7
3 info using node@v4.4.2
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData webpack
8 silly fetchNamedPackageData webpack
9 silly mapToRegistry name webpack
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'webpack',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   name: 'webpack',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/webpack
14 verbose request uri https://registry.npmjs.org/webpack
15 verbose request no auth needed
16 info attempt registry request try #1 at 4:10:56 PM
17 verbose request using bearer token for auth
18 verbose request id a7283b7311361c87
19 verbose etag "6U6KLK4J39E4XWJ2AM234L6VZ"
20 http request GET https://registry.npmjs.org/webpack
21 http 304 https://registry.npmjs.org/webpack
22 verbose headers { 'cache-control': 'max-age=300',
22 verbose headers   'accept-ranges': 'bytes',
22 verbose headers   date: 'Sun, 18 Sep 2016 10:40:56 GMT',
22 verbose headers   via: '1.1 varnish',
22 verbose headers   connection: 'keep-alive',
22 verbose headers   'x-served-by': 'cache-sin6920-SIN',
22 verbose headers   'x-cache': 'MISS',
22 verbose headers   'x-cache-hits': '0',
22 verbose headers   'x-timer': 'S1474195256.772976,VS0,VE219',
22 verbose headers   vary: 'Accept-Encoding' }
23 silly get cb [ 304,
23 silly get   { 'cache-control': 'max-age=300',
23 silly get     'accept-ranges': 'bytes',
23 silly get     date: 'Sun, 18 Sep 2016 10:40:56 GMT',
23 silly get     via: '1.1 varnish',
23 silly get     connection: 'keep-alive',
23 silly get     'x-served-by': 'cache-sin6920-SIN',
23 silly get     'x-cache': 'MISS',
23 silly get     'x-cache-hits': '0',
23 silly get     'x-timer': 'S1474195256.772976,VS0,VE219',
23 silly get     vary: 'Accept-Encoding' } ]
24 verbose etag https://registry.npmjs.org/webpack from cache
25 verbose get saving webpack to C:\Users\Ronin\AppData\Roaming\npm-cache\registry.npmjs.org\webpack\.cache.json
26 verbose correctMkdir C:\Users\Ronin\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
27 silly install normalizeTree
28 silly loadCurrentTree Finishing
29 silly loadIdealTree Starting
30 silly install loadIdealTree
31 silly cloneCurrentTree Starting
32 silly install cloneCurrentTreeToIdealTree
33 silly cloneCurrentTree Finishing
34 silly loadShrinkwrap Starting
35 silly install loadShrinkwrap
36 silly loadShrinkwrap Finishing
37 silly loadAllDepsIntoIdealTree Starting
38 silly install loadAllDepsIntoIdealTree
39 silly rollbackFailedOptional Starting
40 silly rollbackFailedOptional Finishing
41 silly runTopLevelLifecycles Starting
42 silly runTopLevelLifecycles Finishing
43 silly install printInstalled
44 verbose stack Error: Refusing to install webpack as a dependency of itself
44 verbose stack     at checkSelf (C:\Users\Ronin\node-global\node_modules\npm\lib\install\validate-args.js:53:14)
44 verbose stack     at Array.<anonymous> (C:\Users\Ronin\node-global\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
44 verbose stack     at LOOP (C:\Users\Ronin\node-global\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
44 verbose stack     at chain (C:\Users\Ronin\node-global\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
44 verbose stack     at C:\Users\Ronin\node-global\node_modules\npm\lib\install\validate-args.js:16:5
44 verbose stack     at C:\Users\Ronin\node-global\node_modules\npm\node_modules\slide\lib\async-map.js:52:35
44 verbose stack     at Array.forEach (native)
44 verbose stack     at C:\Users\Ronin\node-global\node_modules\npm\node_modules\slide\lib\async-map.js:52:11
44 verbose stack     at Array.forEach (native)
44 verbose stack     at asyncMap (C:\Users\Ronin\node-global\node_modules\npm\node_modules\slide\lib\async-map.js:51:8)
45 verbose cwd C:\Users\Ronin\Desktop\require\webpack
46 error Windows_NT 6.3.9600
47 error argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\Ronin\\node-global\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save-dev" "webpack"
48 error node v4.4.2
49 error npm  v3.8.7
50 error code ENOSELF
51 error Refusing to install webpack as a dependency of itself
52 error If you need help, you may report this error at:
52 error     <https://github.com/npm/npm/issues>
53 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
@roninmittal Is the `"name"` property of your `package.json` set to `"webpack"`? If so, could you try changing it to something more unique?

**Comment by KenanY** [comment]
Closing as abandoned.

**Comment by steefvw** [comment]
Thanks! I had the same problem and the proposed solution worked for me!
