### ISSUE TITLE
DELETE error when trying to unpublish

### ISSUE THREAD

**Issue by karlcoelho** [npm/npm#14035]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### How can the CLI team reproduce the problem?

Just try `npm unpublish <PACKAGE>` on any package you have published.

Here is the error:
`
npm ERR! Registry returned 400 for DELETE on https://registry.npmjs.org/dubai/-rev/2-b6e202a4ebf9d110103801b6ace30b29`

**Comment by KenanY** [comment]
@karlcoelho Could you try emailing `support@npmjs.com`?

**Comment by antonshulgin** [comment]
Just tried to unpublish a package I published by mistake, ran into the same issue. Here's the log:

```shell
$ npm login
Username: username
Password: *********
Email: (this IS public) email@goes.here
Logged in as username on https://registry.npmjs.org/.
$ npm unpublish package-name-here
npm ERR! Refusing to delete entire project.
npm ERR! Run with --force to do this.
npm ERR! npm unpublish [<@scope>/]<pkg>[@<version>]
$ npm unpublish package-name-here --force
npm WARN using --force I sure hope you know what you are doing.
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/6.5.0/bin/node" "/usr/local/bin/npm" "unpublish" "package-name-here" "--force"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! code E400

npm ERR! Registry returned 400 for DELETE on https://registry.npmjs.org/package-name-here
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /path/to/the/package/npm-debug.log
$ 
```

**Comment by antonshulgin** [comment]
And the `npm-debug.log`:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/6.5.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'unpublish',
1 verbose cli   'package-name-here',
1 verbose cli   '--force' ]
2 info using npm@3.10.3
3 info using node@v6.5.0
4 verbose config Skipping project config: /Users/username/.npmrc. (matches userconfig)
5 warn using --force I sure hope you know what you are doing.
6 silly unpublish args[0] package-name-here
7 silly unpublish thing Result {
7 silly unpublish   raw: 'package-name-here',
7 silly unpublish   scope: null,
7 silly unpublish   escapedName: 'package-name-here',
7 silly unpublish   name: 'package-name-here',
7 silly unpublish   rawSpec: '',
7 silly unpublish   spec: 'latest',
7 silly unpublish   type: 'tag' }
8 verbose getPublishConfig null
9 silly ls normalized package-name-here
10 silly gentlyRm /Users/username/.npm/package-name-here is being purged
11 verbose gentlyRm don't care about contents; nuking /Users/username/.npm/package-name-here
12 silly mapToRegistry name package-name-here
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry data Result {
15 silly mapToRegistry   raw: 'package-name-here',
15 silly mapToRegistry   scope: null,
15 silly mapToRegistry   escapedName: 'package-name-here',
15 silly mapToRegistry   name: 'package-name-here',
15 silly mapToRegistry   rawSpec: '',
15 silly mapToRegistry   spec: 'latest',
15 silly mapToRegistry   type: 'tag' }
16 silly mapToRegistry uri https://registry.npmjs.org/package-name-here
17 verbose get GET as part of write; not caching result
18 verbose request uri https://registry.npmjs.org/package-name-here?write=true
19 verbose request no auth needed
20 info attempt registry request try #1 at 3:21:25 AM
21 verbose request using bearer token for auth
22 verbose request id c7e0dbd2c47d2e35
23 http request GET https://registry.npmjs.org/package-name-here?write=true
24 http 200 https://registry.npmjs.org/package-name-here?write=true
25 verbose headers { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
25 verbose headers   etag: '"BZWF3MBRIC8BIP013GBOOOK2O"',
25 verbose headers   'content-type': 'application/json',
25 verbose headers   'content-encoding': 'gzip',
25 verbose headers   'cache-control': 'max-age=0',
25 verbose headers   'transfer-encoding': 'chunked',
25 verbose headers   'accept-ranges': 'bytes',
25 verbose headers   date: 'Sun, 25 Sep 2016 00:21:26 GMT',
25 verbose headers   via: '1.1 varnish',
25 verbose headers   connection: 'keep-alive',
25 verbose headers   'x-served-by': 'cache-fra1231-FRA',
25 verbose headers   'x-cache': 'MISS',
25 verbose headers   'x-cache-hits': '0',
25 verbose headers   'x-timer': 'S1474762885.681385,VS0,VE395',
25 verbose headers   vary: 'Accept-Encoding' }
26 silly get cb [ 200,
26 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
26 silly get     etag: '"BZWF3MBRIC8BIP013GBOOOK2O"',
26 silly get     'content-type': 'application/json',
26 silly get     'content-encoding': 'gzip',
26 silly get     'cache-control': 'max-age=0',
26 silly get     'transfer-encoding': 'chunked',
26 silly get     'accept-ranges': 'bytes',
26 silly get     date: 'Sun, 25 Sep 2016 00:21:26 GMT',
26 silly get     via: '1.1 varnish',
26 silly get     connection: 'keep-alive',
26 silly get     'x-served-by': 'cache-fra1231-FRA',
26 silly get     'x-cache': 'MISS',
26 silly get     'x-cache-hits': '0',
26 silly get     'x-timer': 'S1474762885.681385,VS0,VE395',
26 silly get     vary: 'Accept-Encoding' } ]
27 verbose get saving package-name-here to /Users/username/.npm/registry.npmjs.org/package-name-here_3Fwrite_3Dtrue/.cache.json
28 verbose correctMkdir /Users/username/.npm correctMkdir not in flight; initializing
29 info unpublish No version specified, removing all
30 verbose request uri https://registry.npmjs.org/package-name-here/-rev/1-31cb6d13e7db1a8f86fbefcf81afaf38
31 verbose request sending authorization for write operation
32 info attempt registry request try #1 at 3:21:26 AM
33 verbose request using bearer token for auth
34 http request DELETE https://registry.npmjs.org/package-name-here/-rev/1-31cb6d13e7db1a8f86fbefcf81afaf38
35 http 400 https://registry.npmjs.org/package-name-here/-rev/1-31cb6d13e7db1a8f86fbefcf81afaf38
36 verbose headers { 'content-type': 'application/json',
36 verbose headers   'cache-control': 'max-age=300',
36 verbose headers   'content-length': '17',
36 verbose headers   'accept-ranges': 'bytes',
36 verbose headers   date: 'Sun, 25 Sep 2016 00:21:27 GMT',
36 verbose headers   via: '1.1 varnish',
36 verbose headers   connection: 'keep-alive',
36 verbose headers   'x-served-by': 'cache-fra1231-FRA',
36 verbose headers   'x-cache': 'MISS',
36 verbose headers   'x-cache-hits': '0',
36 verbose headers   'x-timer': 'S1474762886.287188,VS0,VE1008',
36 verbose headers   vary: 'Accept-Encoding' }
37 verbose request invalidating /Users/username/.npm/registry.npmjs.org/package-name-here on DELETE
38 verbose stack Error: Registry returned 400 for DELETE on https://registry.npmjs.org/package-name-here/-rev/1-31cb6d13e7db1a8f86fbefcf81afaf38
38 verbose stack     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
38 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:242:14)
38 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
38 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:200:22)
38 verbose stack     at emitTwo (events.js:106:13)
38 verbose stack     at Request.emit (events.js:191:7)
38 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1067:10)
38 verbose stack     at emitOne (events.js:101:20)
38 verbose stack     at Request.emit (events.js:188:7)
38 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:988:12)
39 verbose statusCode 400
40 verbose pkgid package-name-here
41 verbose cwd /Users/username
42 error Darwin 15.6.0
43 error argv "/usr/local/Cellar/node/6.5.0/bin/node" "/usr/local/bin/npm" "unpublish" "package-name-here" "--force"
44 error node v6.5.0
45 error npm  v3.10.3
46 error code E400
47 error Registry returned 400 for DELETE on https://registry.npmjs.org/package-name-here/-rev/1-31cb6d13e7db1a8f86fbefcf81afaf38
48 error If you need help, you may report this error at:
48 error     <https://github.com/npm/npm/issues>
49 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
@antonshulgin See my comment above please.

**Comment by antonshulgin** [comment]
@KenanY Done. What is this issue tracker for though?

**Comment by KenanY** [comment]
@antonshulgin This issue tracker is for feature-requests/bugs in `npm`. What you're seeing is probably just another instance of <http://blog.npmjs.org/post/141905368000/changes-to-npms-unpublish-policy>

**Comment by KenanY** [comment]
(to clarify: the established medium for requesting a package unpublish is that email address)

**Comment by ljharb** [comment]
Packages can't be unpublished if it's been more than 24 hours, or if anything depends on it, per http://blog.npmjs.org/post/141905368000/changes-to-npms-unpublish-policy.

**Comment by KenanY** [comment]
Closing since, as far as I know, registry-related stuff like this isn't in the jurisdiction of the cli team.
