### ISSUE TITLE
Project installation problem (Skipping failed optional dependency /chokidar/fsevents)

### ISSUE THREAD

**Issue by kitin** [npm/npm#14082]
Hi! I'm trying to install project packages (on win10 64) with
npm i --no-bin-links 
and have this debug log file
[npm-debug.txt](https://github.com/npm/npm/files/492908/npm-debug.txt)

```
128861 verbose stack RangeError: Maximum call stack size exceeded
128861 verbose stack     at isTTY (C:\Program Files\nodejs\node_modules\npm\node_modules\npmlog\node_modules\gauge\progress-bar.js:11:17)
128861 verbose stack     at Object.ProgressBar.show (C:\Program Files\nodejs\node_modules\npm\node_modules\npmlog\node_modules\gauge\progress-bar.js:132:8)
128861 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npmlog\log.js:106:14)
128861 verbose stack     at emitThree (events.js:110:13)
128861 verbose stack     at emit (events.js:188:7)
128861 verbose stack     at null.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npmlog\node_modules\are-we-there-yet\tracker-group.js:23:18)
128861 verbose stack     at emitThree (events.js:110:13)
128861 verbose stack     at emit (events.js:188:7)
128861 verbose stack     at null.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npmlog\node_modules\are-we-there-yet\tracker-group.js:23:18)
128861 verbose stack     at emitThree (events.js:110:13)
128861 verbose stack     at emit (events.js:188:7)
128862 verbose cwd C:\rep\zzzik-bfc
128863 error Windows_NT 6.1.7601
128864 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--no-bin-links"
128865 error node v5.12.0
128866 error npm  v3.8.6
128867 error Maximum call stack size exceeded
128868 error If you need help, you may report this error at:
128868 error     <https://github.com/npm/npm/issues>
```

In case of installing without --no-bin-links I have next errors:

```
> fibers@1.0.14 install C:\rep\zzzik-bfc\node_modules\fibers
> node build.js || nodejs build.js

`win32-x64-v8-4.6` exists; testing
Binary is fine; exiting
acsg@0.0.1 C:\rep\zzzik-bfc
`-- fibers@1.0.14

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
```

Can it depend on windows version or nodejs version or npm?

**Comment by KenanY** [comment]
Maybe try Node.js 6, along with updating `npm`.

**Comment by KenanY** [comment]
Closing as abandoned.
