### ISSUE TITLE
EPEERINVALID __the log is attached

### ISSUE THREAD

**Issue by aloui55** [npm/npm#14085]
```
npm WARN peerDependencies The peer dependency webpack@* included from html-webpack-plugin will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN deprecated lodash.assign@4.2.0: This package is deprecated. Use Object.assign.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

> execSync@1.0.2 install C:\Users\ALOUI Ahmed\AppData\Roaming\npm\node_modules\angular-cli\node_modules\angular2-template-loader\node_modules\codecov\node_modules\execSync
> node install.js

[execsync v1.0.2] Attempting to compile native extensions.
{ [Error: spawn node-gyp ENOENT]
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn node-gyp',
  path: 'node-gyp',
  spawnargs: [ 'rebuild' ] }
[execSync v1.0.2]
    Native code compile failed!!
    Will try to use win32 extension.
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

> node-zopfli@1.4.0 install C:\Users\ALOUI Ahmed\AppData\Roaming\npm\node_modules\angular-cli\node_modules\compression-webpack-plugin\node_modules\node-zopfli
> node-pre-gyp install --fallback-to-build

 node-pre-gyp ERR! Tried to download: https://node-zopfli.s3.amazonaws.com/Release/zopfli-v1.4.0-node-v46-win32-x64.tar.
node-pre-gyp ERR! Pre-built binaries not found for node-zopfli@1.4.0 and node@4.5.0 (node-v46 ABI) (falling back to source compile with node-gyp)
|
C:\Users\ALOUI Ahmed\AppData\Roaming\npm\node_modules\angular-cli\node_modules\compression-webpack-plugin\node_modules\node-zopfli>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean )  else (node "" clean )
|
C:\Users\ALOUI Ahmed\AppData\Roaming\npm\node_modules\angular-cli\node_modules\compression-webpack-plugin\node_modules\node-zopfli>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure --fallback-to-build "--module=C:\Users\ALOUI Ahmed\AppData\Roaming\npm\node_modules\angular-cli\node_modules\compression-webpack-plugin\node_modules\node-zopfli\lib\binding\node-v46-win32-x64\zopfli.node" --module_name=zopfli "--module_path=C:\Users\ALOUI Ahmed\AppData\Roaming\npm\node_modules\angular-cli\node_m else (node "" configure --fallback-to-build "--module=C:\Users\ALOUI Ahmed\AppData\Roaming\npm\node_modules\angular-cli\node_modules\compression-webpack-plugin\node_modules\node-zopfli\lib\binding\node-v46-win32-x64\zopfli.node" --module_name=zopfli "--module_path=C:\Users\ALOUI Ahmed\AppData\Roaming\npm\node_modules\angular-cli\node_modules\compression-webpack-plugin\node_modules\node-zopfli\lib\binding\node-v46-win32-x64" )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:449:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:404:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Users\\ALOUI Ahmed\\AppData\\Roaming\\npm\\node_modules\\angular-cli\\node_modules\\compression-webpack-plugin\\node_modules\\node-zopfli\\lib\\binding\\node-v46-win32-x64\\zopfli.node" "--module_name=zopfli" "--module_path=C:\\Users\\ALOUI Ahmed\\AppData\\Roaming\\npm\\node_modules\\angular-cli\\node_modules\\compression-webpack-plugin\\node_modules\\node-zopfli\\lib\\binding\\node-v46-win32-x64"
gyp ERR! cwd C:\Users\ALOUI Ahmed\AppData\Roaming\npm\node_modules\angular-cli\node_modules\compression-webpack-plugin\node_modules\node-zopfli
gyp ERR! node -v v4.5.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=C:\Users\ALOUI Ahmed\AppData\Roaming\npm\node_modules\angular-cli\node_modules\compression-webpack-plugin\node_modules\node-zopfli\lib\binding\node-v46-win32-x64\zopfli.node --module_name=zopfli --module_path=C:\Users\ALOUI Ahmed\AppData\Roaming\npm\node_modules\angular-cli\node_modules\compression-webpack-plugin\node_modules\node-zopfli\lib\binding\node-v46-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\ALOUI Ahmed\AppData\Roaming\npm\node_modules\angular-cli\node_modules\compression-webpack-plugin\node_modules\node-zopfli\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:829:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Windows_NT 10.0.10586
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\ALOUI Ahmed\\AppData\\Roaming\\npm\\node_modules\\angular-cli\\node_modules\\compression-webpack-plugin\\node_modules\\node-zopfli\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\ALOUI Ahmed\AppData\Roaming\npm\node_modules\angular-cli\node_modules\compression-webpack-plugin\node_modules\node-zopfli
node-pre-gyp ERR! node -v v4.5.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.30
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=C:\Users\ALOUI Ahmed\AppData\Roaming\npm\node_modules\angular-cli\node_modules\compression-webpack-plugin\node_modules\node-zopfli\lib\binding\node-v46-win32-x64\zopfli.node --module_name=zopfli --module_path=C:\Users\ALOUI Ahmed\AppData\Roaming\npm\node_modules\angular-cli\node_modules\compression-webpack-plugin\node_modules\node-zopfli\lib\binding\node-v46-win32-x64' (1)
npm WARN optional dep failed, continuing node-zopfli@1.4.0
npm WARN optional dep failed, continuing fsevents@1.0.14
npm WARN deprecated lodash-node@2.4.1: This package is discontinued. Use lodash@^4.0.0.
-
> node-sass@3.10.0 install C:\Users\ALOUI Ahmed\AppData\Roaming\npm\node_modules\angular-cli\node_modules\node-sass
> node scripts/install.js

Start downloading binary at https://github.com/sass/node-sass/releases/download/v3.10.0/win32-x64-46_binding.node
Binary downloaded and installed at C:\Users\ALOUI Ahmed\AppData\Roaming\npm\node_modules\angular-cli\node_modules\node-sass\vendor\win32-x64-46\binding.node

> node-sass@3.10.0 postinstall C:\Users\ALOUI Ahmed\AppData\Roaming\npm\node_modules\angular-cli\node_modules\node-sass
> node scripts/build.js

"C:\Users\ALOUI Ahmed\AppData\Roaming\npm\node_modules\angular-cli\node_modules\node-sass\vendor\win32-x64-46\binding.node" exists.
 testing binary.
Binary is fine; exiting.
C:\Users\ALOUI Ahmed\AppData\Roaming\npm\ng -> C:\Users\ALOUI Ahmed\AppData\Roaming\npm\node_modules\angular-cli\bin\ng
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "angular-cli"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package webpack@2.1.0-beta.22 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer html-webpack-plugin@2.22.0 wants webpack@*
npm ERR! peerinvalid Peer karma-webpack@1.8.0 wants webpack@^1.1.0 || ^2 || ^2.1.0-beta
npm ERR! peerinvalid Peer sass-loader@3.2.3 wants webpack@^1.12.6 || ^2.1.0-beta
npm ERR! peerinvalid Peer string-replace-loader@1.0.5 wants webpack@1 || 2 || ^2.0.0-beta || ^2.1.0-beta
npm ERR! peerinvalid Peer webpack-dev-server@2.1.0-beta.3 wants webpack@^2.1.0-beta

npm ERR! Please include the following file with any support request:
npm ERR!     D:\angular2\npm-debug.log
[npm-debug.txt](https://github.com/npm/npm/files/494135/npm-debug.txt)

```

**Comment by aloui55** [comment]
can someone help please ?
I installed and reinstalled node js serveral times and delete the folders : C:\Users\MyUser\AppData\Roaming\npm and npm-cache and reinstalled with no success ...
