### ISSUE TITLE
NPMERR

### ISSUE THREAD

**Issue by maddymaster** [npm/npm#14106]
#### I'm opening this issue because npm is producing an incorrect install.
and npm is doing something I don't understand.
Here is what I am trying to do (and i get this error doing any npm install except for the node version manager

``` 
maddyspc:AngularSites MaddyVeena$ sudo npm install -g angular-cli
npm ERR! Darwin 15.2.0
npm ERR! argv "node" "/Users/MaddyVeena/.nvm/v0.9.6/bin/npm" "install" "-g" "angular-cli"
npm ERR! node v0.9.6
npm ERR! npm  v3.10.3

npm ERR! Unknown encoding: buffer
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

buffer.js:405
      throw new Error('Unknown encoding: ' + encoding);
            ^
Error: Unknown encoding: buffer
    at Buffer.write (buffer.js:405:13)
    at new Buffer (buffer.js:261:26)
    at WriteStream.Writable.write (_stream_writable.js:134:13)
    at WriteStreamAtomic._write (/Users/MaddyVeena/.nvm/v0.9.6/lib/node_modules/npm/node_modules/fs-write-stream-atomic/index.js:64:37)
    at doWrite (/Users/MaddyVeena/.nvm/v0.9.6/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_writable.js:319:64)
    at writeOrBuffer (/Users/MaddyVeena/.nvm/v0.9.6/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_writable.js:308:5)
    at WriteStreamAtomic.Writable.write (/Users/MaddyVeena/.nvm/v0.9.6/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_writable.js:246:11)
    at WriteStreamAtomic.Writable.end (/Users/MaddyVeena/.nvm/v0.9.6/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_writable.js:456:51)
    at writeLogFile (/Users/MaddyVeena/.nvm/v0.9.6/lib/node_modules/npm/lib/utils/error-handler.js:205:8)
    at exit (/Users/MaddyVeena/.nvm/v0.9.6/lib/node_modules/npm/lib/utils/error-handler.js:82:5)
```

#### What's going wrong?
I tried npm cache clean no go, npm has all folder permissions still no go. 

#### How can the CLI team reproduce the problem?

I am using  node version v0.9.6
npm version - 3.10.3
MAC OSX

All debug logs are empty, hence not uploading them. Please help me solve this issue.

**Comment by maddymaster** [comment]
I have tried 
``` brew uninstall --force node
rm -rf /usr/local/lib/node_modules
rm /usr/local/bin/npm
brew install node
```

and then tried to install angularjs2 no go. I get the same error when I try to npm install anything! I did not locate any solution for this issue. please help

**Comment by othiym23** [comment]
The version of Node that npm is using (0.9.6) is an outdated development version, installed and managed by the nvm Node version manager, but the commands you're running to try to clean up your install are using Homebrew. If you can get upgraded onto Node LTS (4.x) or later, or at the very least a reasonably recent version of 0.10, you're going to have much better luck with npm. Perhaps (after ensuring you have a recent version of nvm) `nvm use --lts` would help?

**Comment by othiym23** [comment]
I see from #7555 that you upgraded your version of Node and worked this out, so I'm closing this as resolved. Thanks for your time!
