### ISSUE TITLE
发布node模块 npm pubilsh

### ISSUE THREAD

**Issue by shunzizhan** [npm/npm#14131]
如下是报错提示
0 info it worked if it ends with ok
1 verbose cli [ 'd:\\yifangzsh\\Node.js\\file\\node.exe',
1 verbose cli   'd:\\yifangzsh\\Node.js\\file\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'publish',
1 verbose cli   '--tag',
1 verbose cli   '0.1.0' ]
2 info using npm@2.10.1
3 info using node@v0.12.4
4 verbose publish [ '.' ]
5 verbose stack Error: Tag name must not be a valid SemVer range: 0.1.0
5 verbose stack     at EventEmitter.publish (d:\yifangzsh\Node.js\file\node_modules\npm\lib\publish.js:41:14)
5 verbose stack     at Object.commandCache.(anonymous function) (d:\yifangzsh\Node.js\file\node_modules\npm\lib\npm.js:217:11)
5 verbose stack     at EventEmitter.<anonymous> (d:\yifangzsh\Node.js\file\node_modules\npm\bin\npm-cli.js:72:28)
5 verbose stack     at process._tickCallback (node.js:355:11)
6 verbose cwd e:\yifangzsh\github\fis3-parser-html-replaceurl
7 error Windows_NT 6.1.7601
8 error argv "d:\\yifangzsh\\Node.js\\file\\node.exe" "d:\\yifangzsh\\Node.js\\file\\node_modules\\npm\\bin\\npm-cli.js" "publish" "--tag" "0.1.0"
9 error node v0.12.4
10 error npm  v2.10.1
11 error Tag name must not be a valid SemVer range: 0.1.0
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]

**Comment by shunzizhan** [comment]
when I try again ,it was released correctly
