### ISSUE TITLE
Unable to update npm: connect ECONNREFUSED

### ISSUE THREAD

**Issue by mindplay-dk** [npm/npm#14186]
I'm trying to update npm, because I'm having trouble installing `node-sass` and other packages today.

I'm running Win 10 Pro `14393` with Git Bash, launched as Administrator.

I've reinstalled node `6.7.0` to make sure I start with a clean slate.

```
$ npm -v
3.10.3

$ node -v
v6.7.0

$ npm install -g npm@latest
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\nodejs\\node.exe" "C:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "npm@latest"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.3
npm ERR! code ECONNREFUSED
npm ERR! errno ECONNREFUSED
npm ERR! syscall connect

npm ERR! Error: connect ECONNREFUSED 185.113.228.81:443
npm ERR!     at Object.exports._errnoException (util.js:1036:11)
npm ERR!     at exports._exceptionWithHostPort (util.js:1059:20)
npm ERR!     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
npm ERR!  { Error: connect ECONNREFUSED 185.113.228.81:443
npm ERR!     at Object.exports._errnoException (util.js:1036:11)
npm ERR!     at exports._exceptionWithHostPort (util.js:1059:20)
npm ERR!     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
npm ERR!   code: 'ECONNREFUSED',
npm ERR!   errno: 'ECONNREFUSED',
npm ERR!   syscall: 'connect',
npm ERR!   address: '185.113.228.81',
npm ERR!   port: 443 }
npm ERR!
npm ERR! If you are behind a proxy, please make sure that the
npm ERR! 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     C:\workspace\npm-debug.log

$ cat npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\nodejs\\node.exe',
1 verbose cli   'C:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'npm@latest' ]
2 info using npm@3.10.3
3 info using node@v6.7.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData npm@latest
8 silly fetchNamedPackageData npm
9 silly mapToRegistry name npm
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'npm',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'npm',
12 silly mapToRegistry   name: 'npm',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/npm
14 verbose request uri https://registry.npmjs.org/npm
15 verbose request no auth needed
16 info attempt registry request try #1 at 11:46:06 AM
17 verbose request id a139af9f554ed671
18 http request GET https://registry.npmjs.org/npm
19 info retry will retry, error on last attempt: Error: connect ECONNREFUSED 185.113.228.81:443
20 info attempt registry request try #2 at 11:46:17 AM
21 http request GET https://registry.npmjs.org/npm
22 info retry will retry, error on last attempt: Error: connect ECONNREFUSED 185.113.228.81:443
23 info attempt registry request try #3 at 11:47:18 AM
24 http request GET https://registry.npmjs.org/npm
25 silly fetchPackageMetaData Error: connect ECONNREFUSED 185.113.228.81:443
25 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1036:11)
25 silly fetchPackageMetaData     at exports._exceptionWithHostPort (util.js:1059:20)
25 silly fetchPackageMetaData     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
25 silly fetchPackageMetaData  error for npm@latest { Error: connect ECONNREFUSED 185.113.228.81:443
25 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1036:11)
25 silly fetchPackageMetaData     at exports._exceptionWithHostPort (util.js:1059:20)
25 silly fetchPackageMetaData     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
25 silly fetchPackageMetaData   code: 'ECONNREFUSED',
25 silly fetchPackageMetaData   errno: 'ECONNREFUSED',
25 silly fetchPackageMetaData   syscall: 'connect',
25 silly fetchPackageMetaData   address: '185.113.228.81',
25 silly fetchPackageMetaData   port: 443 }
26 silly rollbackFailedOptional Starting
27 silly rollbackFailedOptional Finishing
28 silly runTopLevelLifecycles Starting
29 silly runTopLevelLifecycles Finishing
30 silly install printInstalled
31 verbose stack Error: connect ECONNREFUSED 185.113.228.81:443
31 verbose stack     at Object.exports._errnoException (util.js:1036:11)
31 verbose stack     at exports._exceptionWithHostPort (util.js:1059:20)
31 verbose stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
32 verbose cwd C:\workspace\test\kodus-blocks
33 error Windows_NT 10.0.14393
34 error argv "C:\\nodejs\\node.exe" "C:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "npm@latest"
35 error node v6.7.0
36 error npm  v3.10.3
37 error code ECONNREFUSED
38 error errno ECONNREFUSED
39 error syscall connect
40 error Error: connect ECONNREFUSED 185.113.228.81:443
40 error     at Object.exports._errnoException (util.js:1036:11)
40 error     at exports._exceptionWithHostPort (util.js:1059:20)
40 error     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
40 error  { Error: connect ECONNREFUSED 185.113.228.81:443
40 error     at Object.exports._errnoException (util.js:1036:11)
40 error     at exports._exceptionWithHostPort (util.js:1059:20)
40 error     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
40 error   code: 'ECONNREFUSED',
40 error   errno: 'ECONNREFUSED',
40 error   syscall: 'connect',
40 error   address: '185.113.228.81',
40 error   port: 443 }
41 error If you are behind a proxy, please make sure that the
41 error 'proxy' config is set properly.  See: 'npm help config'
42 verbose exit [ 1, true ]
```

I read [here](http://www.redmondpie.com/fix-slow-internet-after-windows-10-anniversary-update-heres-how/) that Win 10 may have some network issues with `npm` after the "anniversary update" service pack, which I installed recently - so I tried disabling the "window auto-tuning" feature, as described on that page, but that has no effect.

**Comment by mindplay-dk** [comment]
Problem solved - our firewall vendor had blocked this IP for some reason! :-/
