### ISSUE TITLE
When npm install, Cannot find module 'jsprim'

### ISSUE THREAD

**Issue by hemantha** [npm/npm#14204]
Error: Cannot find module 'jsprim'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (c:\nodejs\node_modules\npm\node_modules\request\node_
modules\http-signature\lib\signer.js:8:14)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "c:\\nodejs\\node.exe" "c:\\nodejs\\node_modules\\npm\\bin\\npm-cl
i.js" "prefix" "-g"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'jsprim'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
Error: Cannot find module 'jsprim'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (c:\nodejs\node_modules\npm\node_modules\request\node_
modules\http-signature\lib\signer.js:8:14)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "c:\\nodejs\\node.exe" "c:\\nodejs\\node_modules\\npm\\bin\\npm-cl
i.js" "install"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'jsprim'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by KenanY** [comment]
@hemantha Might have to reinstall `npm`, as it appears as though a dependency is missing for some reason.

**Comment by KenanY** [comment]
Closing due to lack of a response.

**Comment by austinmccalley** [comment]
@KenanY Can you re-open this I am getting the same error after doing npm install request. I have tried clearing the cache and I get the same error.
NPM version 5.3.0
Node version v8.2.1

**Comment by kenany** [comment]
@mcaustin1 Have you also tried reinstalling `npm`?

**Comment by rikosage** [comment]
I have the same error. I tried to reinstall npm, but it didn't solve this problem.
NPM: 2.15.11
Node: 0.12.18

**Comment by austinmccalley** [comment]
@KenanY Yes, what I had to do to fix it was to manually install each package that it said it could not find.

**Comment by rikosage** [comment]
`npm cache clean` and reinstallation all of global packages solved my problem.
