### ISSUE TITLE
Getting error during npm install of packages

### ISSUE THREAD

**Issue by suman1980** [npm/npm#14200]
<details>

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'vis' ]
2 info using npm@3.10.3
3 info using node@v6.7.0
4 verbose config Skipping project config: C:\Users\suman_satpathy/.npmrc. (matches userconfig)
5 silly loadCurrentTree Starting
6 silly install loadCurrentTree
7 silly install readLocalPackageData
8 silly fetchPackageMetaData vis
9 silly fetchNamedPackageData vis
10 silly mapToRegistry name vis
11 silly mapToRegistry using default registry
12 silly mapToRegistry registry https://registry.npmjs.org/
13 silly mapToRegistry data Result {
13 silly mapToRegistry   raw: 'vis',
13 silly mapToRegistry   scope: null,
13 silly mapToRegistry   escapedName: 'vis',
13 silly mapToRegistry   name: 'vis',
13 silly mapToRegistry   rawSpec: '',
13 silly mapToRegistry   spec: 'latest',
13 silly mapToRegistry   type: 'tag' }
14 silly mapToRegistry uri https://registry.npmjs.org/vis
15 verbose request uri https://registry.npmjs.org/vis
16 verbose request no auth needed
17 info attempt registry request try #1 at 7:43:24 PM
18 verbose request id 8985abf11f4a4a46
19 http request GET https://registry.npmjs.org/vis
20 info retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
21 info attempt registry request try #2 at 7:43:42 PM
22 http request GET https://registry.npmjs.org/vis
23 info retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
24 info attempt registry request try #3 at 7:44:51 PM
25 http request GET https://registry.npmjs.org/vis
26 silly fetchPackageMetaData Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
26 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1036:11)
26 silly fetchPackageMetaData     at errnoException (dns.js:33:15)
26 silly fetchPackageMetaData     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
26 silly fetchPackageMetaData  error for vis { Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
26 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1036:11)
26 silly fetchPackageMetaData     at errnoException (dns.js:33:15)
26 silly fetchPackageMetaData     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
26 silly fetchPackageMetaData   code: 'EAI_AGAIN',
26 silly fetchPackageMetaData   errno: 'EAI_AGAIN',
26 silly fetchPackageMetaData   syscall: 'getaddrinfo',
26 silly fetchPackageMetaData   hostname: 'registry.npmjs.org',
26 silly fetchPackageMetaData   host: 'registry.npmjs.org',
26 silly fetchPackageMetaData   port: 443 }
27 silly rollbackFailedOptional Starting
28 silly rollbackFailedOptional Finishing
29 silly runTopLevelLifecycles Starting
30 silly runTopLevelLifecycles Finishing
31 silly install printInstalled
32 verbose stack Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
32 verbose stack     at Object.exports._errnoException (util.js:1036:11)
32 verbose stack     at errnoException (dns.js:33:15)
32 verbose stack     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
33 verbose cwd C:\Users\suman_satpathy
34 error Windows_NT 6.1.7601
35 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "vis"
36 error node v6.7.0
37 error npm  v3.10.3
38 error code EAI_AGAIN
39 error errno EAI_AGAIN
40 error syscall getaddrinfo
41 error getaddrinfo EAI_AGAIN registry.npmjs.org:443
42 error If you need help, you may report this error at:
42 error     <https://github.com/npm/npm/issues>
43 verbose exit [ 1, true ]
```

</details>
#### I'm opening this issue because:
- [ ] npm is crashing.
- [ ] npm is producing an incorrect install.
- [ ] npm is doing something I don't understand.
- [ ] Other (_see below for feature requests_):
### supporting information:
- `npm -v` prints:
- `node -v` prints:
- `npm config get registry` prints:
- Windows, OS X, or Linux?:
- Network issues:
  - Geographic location where npm was run:
  - [ ] I use a proxy to connect to the npm registry.
  - [ ] I use a proxy to connect to the web.
  - [ ] I use a proxy when downloading Git repos.
  - [ ] I access the npm registry via a VPN
  - [ ] I don't use a proxy, but have limited or unreliable internet access.
- Container:
  - [ ] I develop using Vagrant on Windows.
  - [ ] I develop using Vagrant on OS X or Linux.
  - [ ] I develop / deploy using Docker.
  - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
Please post results of `npm -v`, `node -v`, and `npm config get registry`, as well as `ping registry.npmjs.org`.

**Comment by suman1980** [comment]
Hi Legodude, Thanks for the response.. Please find the details.

npm -v = 3.10.3
node -v = v6.7.0
npm config get registry = https://registry.npmjs.org/

However ping registry.npmjs.org is giving  below: 
Pinging prod.a.sni.global.fastlylb.net [151.101.120.162] with 32 bytes of data:
Reply from 151.101.120.162: bytes=32 time=603ms TTL=52
Reply from 151.101.120.162: bytes=32 time=605ms TTL=52
Reply from 151.101.120.162: bytes=32 time=607ms TTL=52
Reply from 151.101.120.162: bytes=32 time=594ms TTL=52

Ping statistics for 151.101.120.162:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 594ms, Maximum = 607ms, Average = 602ms
