### ISSUE TITLE
Error: Cannot find module 'tunnel-agent'     at Function.Module._resolveFilename (module.js:455:15)     at Function.Module._load (module.js:403:25)     at Module.require (module.js:483:17)     at require (internal/module.js:20:19)     at Object.<anonymous> (C:\node\node\node_modules\npm\node_modules\request\lib\tunnel.js:4:14)     at Module._compile (module.js:556:32)     at Object.Module._extensions..js (module.js:565:10)     at Module.load (module.js:473:32)     at tryModuleLoad (module.js:432:12)     at Function.Module._load (module.js:424:3)

### ISSUE THREAD

**Issue by Abhinendra** [npm/npm#14225]
#### I'm opening this issue because:
- [x] npm is crashing.

<details>

```
Error: Cannot find module 'tunnel-agent'     
at Function.Module._resolveFilename (module.js:455:15)     
at Function.Module._load (module.js:403:25)     
at Module.require (module.js:483:17)     
at require (internal/module.js:20:19)     
at Object.<anonymous> (C:\node\node\node_modules\npm\node_modules\request\lib\tunnel.js:4:14)     
at Module._compile (module.js:556:32)     
at Object.Module._extensions..js (module.js:565:10)     
at Module.load (module.js:473:32)     
at tryModuleLoad (module.js:432:12)     
at Function.Module._load (module.js:424:3)
```

</details>
### supporting information:
- `npm -v` prints:
- `node -v` prints:
- `npm config get registry` prints:
- Windows, OS 
- Network issues:
  - [ ] I don't use a proxy, but have limited internet access.
- Container:
  - [ ] I develop using Vagrant on Windows.

**Comment by legodude17** [comment]
Try reinstalling.

**Comment by Abhinendra** [comment]
It worked after reinstalling. Now having problem with angular-cli installation. Not able to access github. It says hostname github.com can't be resolved.
