### ISSUE TITLE
npm ERR! missing script: webpack-devserver

### ISSUE THREAD

**Issue by NikolasPur** [npm/npm#14227]
I'm opening this issue because of i've got error when i execute the command: run    

npm run webpack-devserver

NPM dubug info:
<details>
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'webpack-devserver' ]
2 info using npm@2.15.9
3 info using node@v4.6.0
4 verbose stack Error: missing script: webpack-devserver
4 verbose stack     at run (C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:142:19)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:58:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:356:5
4 verbose stack     at checkBinReferences_ (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:320:45)
4 verbose stack     at final (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:354:3)
4 verbose stack     at then (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:124:5)
4 verbose stack     at ReadFileContext.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:295:20)
4 verbose stack     at ReadFileContext.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16)
4 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:303:13)
5 verbose cwd C:\Users\Len1\WebstormProjects\note-app
6 error Windows_NT 10.0.14393
7 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "webpack-devserver"
8 error node v4.6.0
9 error npm  v2.15.9
10 error missing script: webpack-devserver
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
```
</details>

**Comment by KenanY** [comment]
@NikolasPur Do you have a `"webpack-devserver"` script defined in your `package.json`? Without one, `npm` will throw the error you are seeing. It should look something like this:

``` json
{
  "scripts": {
    "webpack-devserver": "script goes here"
  }
}
```

**Comment by KenanY** [comment]
Closing as abandoned.
