### ISSUE TITLE
Error: connect ECONNREFUSED

### ISSUE THREAD

**Issue by HuysentruytRuben** [npm/npm#14226]
#### I'm opening this issue because:
- [X] npm is crashing.
- [ ] npm is producing an incorrect install.
- [ ] npm is doing something I don't understand.
- [ ] Other (_see below for feature requests_):
#### What's going wrong?

Backstory:
I was having a problem installing dependencies for my project (I don't recall the details). For some reason I figured cleaning the npm cache with `npm cache clean` was a good idea.

Problem:
After cleaning the cache `npm install` was no longer working properly for me. It hanged on something (I don't recall what and console won't let me scroll that far back). I did another `npm cache clean` after aborting the hanging npm process. Subsequent attempts to run `npm install` hang at `sill mapToRegistry`. Then I get a bunch of `ECONNREFUSED` warnings and it eventually crashes telling me I `might be behind a proxy`.

Yes, I am behind a proxy, and yes I set the config correctly. npm was working fine behind this proxy with my current settings a month ago, I also asked collegues if anything about a the proxy changed and the answer was no. I also tried re-installing node but that didn't help either.

This config file called `.npmrc` is located at `D:\Users\<username>\.npmrc`
`npm config get prefix` returns `D:\Users\<username>\AppData\Roaming\npm`
this folder is hidden but exists, it contains `etc` `node_modules`, `typings` and `typings.cmd`
#### How can the CLI team reproduce the problem?

I cannot access gist at work so I included a debug log inline

<details>

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@3.10.3
3 info using node@v6.7.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly install normalizeTree
8 silly loadCurrentTree Finishing
9 silly loadIdealTree Starting
10 silly install loadIdealTree
11 silly cloneCurrentTree Starting
12 silly install cloneCurrentTreeToIdealTree
13 silly cloneCurrentTree Finishing
14 silly loadShrinkwrap Starting
15 silly install loadShrinkwrap
16 silly loadShrinkwrap Finishing
17 silly loadAllDepsIntoIdealTree Starting
18 silly install loadAllDepsIntoIdealTree
19 silly fetchNamedPackageData core-js
20 silly mapToRegistry name core-js
21 silly mapToRegistry using default registry
22 silly mapToRegistry registry http://registry.npmjs.org/
23 silly mapToRegistry data Result {
23 silly mapToRegistry   raw: 'core-js',
23 silly mapToRegistry   scope: null,
23 silly mapToRegistry   escapedName: 'core-js',
23 silly mapToRegistry   name: 'core-js',
23 silly mapToRegistry   rawSpec: '',
23 silly mapToRegistry   spec: 'latest',
23 silly mapToRegistry   type: 'tag' }
24 silly mapToRegistry uri http://registry.npmjs.org/core-js
25 silly fetchNamedPackageData immutable
26 silly mapToRegistry name immutable
27 silly mapToRegistry using default registry
28 silly mapToRegistry registry http://registry.npmjs.org/
29 silly mapToRegistry data Result {
29 silly mapToRegistry   raw: 'immutable',
29 silly mapToRegistry   scope: null,
29 silly mapToRegistry   escapedName: 'immutable',
29 silly mapToRegistry   name: 'immutable',
29 silly mapToRegistry   rawSpec: '',
29 silly mapToRegistry   spec: 'latest',
29 silly mapToRegistry   type: 'tag' }
30 silly mapToRegistry uri http://registry.npmjs.org/immutable
31 silly fetchNamedPackageData isomorphic-fetch
32 silly mapToRegistry name isomorphic-fetch
33 silly mapToRegistry using default registry
34 silly mapToRegistry registry http://registry.npmjs.org/
35 silly mapToRegistry data Result {
35 silly mapToRegistry   raw: 'isomorphic-fetch',
35 silly mapToRegistry   scope: null,
35 silly mapToRegistry   escapedName: 'isomorphic-fetch',
35 silly mapToRegistry   name: 'isomorphic-fetch',
35 silly mapToRegistry   rawSpec: '',
35 silly mapToRegistry   spec: 'latest',
35 silly mapToRegistry   type: 'tag' }
36 silly mapToRegistry uri http://registry.npmjs.org/isomorphic-fetch
37 silly fetchNamedPackageData promise
38 silly mapToRegistry name promise
39 silly mapToRegistry using default registry
40 silly mapToRegistry registry http://registry.npmjs.org/
41 silly mapToRegistry data Result {
41 silly mapToRegistry   raw: 'promise',
41 silly mapToRegistry   scope: null,
41 silly mapToRegistry   escapedName: 'promise',
41 silly mapToRegistry   name: 'promise',
41 silly mapToRegistry   rawSpec: '',
41 silly mapToRegistry   spec: 'latest',
41 silly mapToRegistry   type: 'tag' }
42 silly mapToRegistry uri http://registry.npmjs.org/promise
43 silly fetchNamedPackageData ua-parser-js
44 silly mapToRegistry name ua-parser-js
45 silly mapToRegistry using default registry
46 silly mapToRegistry registry http://registry.npmjs.org/
47 silly mapToRegistry data Result {
47 silly mapToRegistry   raw: 'ua-parser-js',
47 silly mapToRegistry   scope: null,
47 silly mapToRegistry   escapedName: 'ua-parser-js',
47 silly mapToRegistry   name: 'ua-parser-js',
47 silly mapToRegistry   rawSpec: '',
47 silly mapToRegistry   spec: 'latest',
47 silly mapToRegistry   type: 'tag' }
48 silly mapToRegistry uri http://registry.npmjs.org/ua-parser-js
49 verbose request uri http://registry.npmjs.org/core-js
50 verbose request no auth needed
51 info attempt registry request try #1 at 16:13:27
52 verbose request id 84637e8ee73cacd6
53 http request GET http://registry.npmjs.org/core-js
54 verbose request uri http://registry.npmjs.org/immutable
55 verbose request no auth needed
56 info attempt registry request try #1 at 16:13:27
57 http request GET http://registry.npmjs.org/immutable
58 verbose request uri http://registry.npmjs.org/isomorphic-fetch
59 verbose request no auth needed
60 info attempt registry request try #1 at 16:13:27
61 http request GET http://registry.npmjs.org/isomorphic-fetch
62 verbose request uri http://registry.npmjs.org/promise
63 verbose request no auth needed
64 info attempt registry request try #1 at 16:13:27
65 http request GET http://registry.npmjs.org/promise
66 verbose request uri http://registry.npmjs.org/ua-parser-js
67 verbose request no auth needed
68 info attempt registry request try #1 at 16:13:27
69 http request GET http://registry.npmjs.org/ua-parser-js
70 info retry will retry, error on last attempt: Error: connect ECONNREFUSED 141.86.23.101:3128
71 info retry will retry, error on last attempt: Error: connect ECONNREFUSED 141.86.23.101:3128
72 info retry will retry, error on last attempt: Error: connect ECONNREFUSED 141.86.23.101:3128
73 info retry will retry, error on last attempt: Error: connect ECONNREFUSED 141.86.23.101:3128
74 info retry will retry, error on last attempt: Error: connect ECONNREFUSED 141.86.23.101:3128
75 info attempt registry request try #2 at 16:13:38
76 http request GET http://registry.npmjs.org/ua-parser-js
77 info attempt registry request try #2 at 16:13:38
78 http request GET http://registry.npmjs.org/immutable
79 info attempt registry request try #2 at 16:13:38
80 http request GET http://registry.npmjs.org/core-js
81 info attempt registry request try #2 at 16:13:38
82 http request GET http://registry.npmjs.org/isomorphic-fetch
83 info attempt registry request try #2 at 16:13:38
84 http request GET http://registry.npmjs.org/promise
85 info retry will retry, error on last attempt: Error: connect ECONNREFUSED 141.86.23.101:3128
86 info retry will retry, error on last attempt: Error: connect ECONNREFUSED 141.86.23.101:3128
87 info retry will retry, error on last attempt: Error: connect ECONNREFUSED 141.86.23.101:3128
88 info retry will retry, error on last attempt: Error: connect ECONNREFUSED 141.86.23.101:3128
89 info retry will retry, error on last attempt: Error: connect ECONNREFUSED 141.86.23.101:3128
90 info attempt registry request try #3 at 16:14:39
91 http request GET http://registry.npmjs.org/immutable
92 info attempt registry request try #3 at 16:14:39
93 http request GET http://registry.npmjs.org/ua-parser-js
94 info attempt registry request try #3 at 16:14:39
95 http request GET http://registry.npmjs.org/isomorphic-fetch
96 info attempt registry request try #3 at 16:14:39
97 http request GET http://registry.npmjs.org/core-js
98 info attempt registry request try #3 at 16:14:39
99 http request GET http://registry.npmjs.org/promise
100 silly fetchPackageMetaData Error: connect ECONNREFUSED 141.86.23.101:3128
100 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1036:11)
100 silly fetchPackageMetaData     at exports._exceptionWithHostPort (util.js:1059:20)
100 silly fetchPackageMetaData     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
100 silly fetchPackageMetaData  error for ua-parser-js@^0.7.9 { Error: connect ECONNREFUSED 141.86.23.101:3128
100 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1036:11)
100 silly fetchPackageMetaData     at exports._exceptionWithHostPort (util.js:1059:20)
100 silly fetchPackageMetaData     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
100 silly fetchPackageMetaData   code: 'ECONNREFUSED',
100 silly fetchPackageMetaData   errno: 'ECONNREFUSED',
100 silly fetchPackageMetaData   syscall: 'connect',
100 silly fetchPackageMetaData   address: '141.86.23.101',
100 silly fetchPackageMetaData   port: 3128 }
101 silly fetchPackageMetaData Error: connect ECONNREFUSED 141.86.23.101:3128
101 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1036:11)
101 silly fetchPackageMetaData     at exports._exceptionWithHostPort (util.js:1059:20)
101 silly fetchPackageMetaData     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
101 silly fetchPackageMetaData  error for immutable@^3.7.6 { Error: connect ECONNREFUSED 141.86.23.101:3128
101 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1036:11)
101 silly fetchPackageMetaData     at exports._exceptionWithHostPort (util.js:1059:20)
101 silly fetchPackageMetaData     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
101 silly fetchPackageMetaData   code: 'ECONNREFUSED',
101 silly fetchPackageMetaData   errno: 'ECONNREFUSED',
101 silly fetchPackageMetaData   syscall: 'connect',
101 silly fetchPackageMetaData   address: '141.86.23.101',
101 silly fetchPackageMetaData   port: 3128 }
102 silly fetchPackageMetaData Error: connect ECONNREFUSED 141.86.23.101:3128
102 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1036:11)
102 silly fetchPackageMetaData     at exports._exceptionWithHostPort (util.js:1059:20)
102 silly fetchPackageMetaData     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
102 silly fetchPackageMetaData  error for isomorphic-fetch@^2.1.1 { Error: connect ECONNREFUSED 141.86.23.101:3128
102 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1036:11)
102 silly fetchPackageMetaData     at exports._exceptionWithHostPort (util.js:1059:20)
102 silly fetchPackageMetaData     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
102 silly fetchPackageMetaData   code: 'ECONNREFUSED',
102 silly fetchPackageMetaData   errno: 'ECONNREFUSED',
102 silly fetchPackageMetaData   syscall: 'connect',
102 silly fetchPackageMetaData   address: '141.86.23.101',
102 silly fetchPackageMetaData   port: 3128 }
103 silly fetchPackageMetaData Error: connect ECONNREFUSED 141.86.23.101:3128
103 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1036:11)
103 silly fetchPackageMetaData     at exports._exceptionWithHostPort (util.js:1059:20)
103 silly fetchPackageMetaData     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
103 silly fetchPackageMetaData  error for promise@^7.1.1 { Error: connect ECONNREFUSED 141.86.23.101:3128
103 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1036:11)
103 silly fetchPackageMetaData     at exports._exceptionWithHostPort (util.js:1059:20)
103 silly fetchPackageMetaData     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
103 silly fetchPackageMetaData   code: 'ECONNREFUSED',
103 silly fetchPackageMetaData   errno: 'ECONNREFUSED',
103 silly fetchPackageMetaData   syscall: 'connect',
103 silly fetchPackageMetaData   address: '141.86.23.101',
103 silly fetchPackageMetaData   port: 3128 }
104 silly fetchPackageMetaData Error: connect ECONNREFUSED 141.86.23.101:3128
104 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1036:11)
104 silly fetchPackageMetaData     at exports._exceptionWithHostPort (util.js:1059:20)
104 silly fetchPackageMetaData     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
104 silly fetchPackageMetaData  error for core-js@^1.0.0 { Error: connect ECONNREFUSED 141.86.23.101:3128
104 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1036:11)
104 silly fetchPackageMetaData     at exports._exceptionWithHostPort (util.js:1059:20)
104 silly fetchPackageMetaData     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
104 silly fetchPackageMetaData   code: 'ECONNREFUSED',
104 silly fetchPackageMetaData   errno: 'ECONNREFUSED',
104 silly fetchPackageMetaData   syscall: 'connect',
104 silly fetchPackageMetaData   address: '141.86.23.101',
104 silly fetchPackageMetaData   port: 3128 }
105 silly rollbackFailedOptional Starting
106 silly rollbackFailedOptional Finishing
107 silly runTopLevelLifecycles Starting
108 silly runTopLevelLifecycles Finishing
109 silly install printInstalled
110 warn optional Skipping failed optional dependency /react/fbjs/immutable:
111 warn Error: connect ECONNREFUSED 141.86.23.101:3128
111 warn     at Object.exports._errnoException (util.js:1036:11)
111 warn     at exports._exceptionWithHostPort (util.js:1059:20)
111 warn     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
111 warn  { Error: connect ECONNREFUSED 141.86.23.101:3128
111 warn     at Object.exports._errnoException (util.js:1036:11)
111 warn     at exports._exceptionWithHostPort (util.js:1059:20)
111 warn     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
111 warn   code: 'ECONNREFUSED',
111 warn   errno: 'ECONNREFUSED',
111 warn   syscall: 'connect',
111 warn   address: '141.86.23.101',
111 warn   port: 3128,
111 warn   parent: 'fbjs',
111 warn   optional: '/react/fbjs/immutable' }
112 warn optional Skipping failed optional dependency /react/fbjs/isomorphic-fetch:
113 warn Error: connect ECONNREFUSED 141.86.23.101:3128
113 warn     at Object.exports._errnoException (util.js:1036:11)
113 warn     at exports._exceptionWithHostPort (util.js:1059:20)
113 warn     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
113 warn  { Error: connect ECONNREFUSED 141.86.23.101:3128
113 warn     at Object.exports._errnoException (util.js:1036:11)
113 warn     at exports._exceptionWithHostPort (util.js:1059:20)
113 warn     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
113 warn   code: 'ECONNREFUSED',
113 warn   errno: 'ECONNREFUSED',
113 warn   syscall: 'connect',
113 warn   address: '141.86.23.101',
113 warn   port: 3128,
113 warn   parent: 'fbjs',
113 warn   optional: '/react/fbjs/isomorphic-fetch' }
114 warn optional Skipping failed optional dependency /react/fbjs/promise:
115 warn Error: connect ECONNREFUSED 141.86.23.101:3128
115 warn     at Object.exports._errnoException (util.js:1036:11)
115 warn     at exports._exceptionWithHostPort (util.js:1059:20)
115 warn     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
115 warn  { Error: connect ECONNREFUSED 141.86.23.101:3128
115 warn     at Object.exports._errnoException (util.js:1036:11)
115 warn     at exports._exceptionWithHostPort (util.js:1059:20)
115 warn     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
115 warn   code: 'ECONNREFUSED',
115 warn   errno: 'ECONNREFUSED',
115 warn   syscall: 'connect',
115 warn   address: '141.86.23.101',
115 warn   port: 3128,
115 warn   parent: 'fbjs',
115 warn   optional: '/react/fbjs/promise' }
116 warn optional Skipping failed optional dependency /react/fbjs/core-js:
117 warn Error: connect ECONNREFUSED 141.86.23.101:3128
117 warn     at Object.exports._errnoException (util.js:1036:11)
117 warn     at exports._exceptionWithHostPort (util.js:1059:20)
117 warn     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
117 warn  { Error: connect ECONNREFUSED 141.86.23.101:3128
117 warn     at Object.exports._errnoException (util.js:1036:11)
117 warn     at exports._exceptionWithHostPort (util.js:1059:20)
117 warn     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
117 warn   code: 'ECONNREFUSED',
117 warn   errno: 'ECONNREFUSED',
117 warn   syscall: 'connect',
117 warn   address: '141.86.23.101',
117 warn   port: 3128,
117 warn   parent: 'fbjs',
117 warn   optional: '/react/fbjs/core-js' }
118 verbose stack Error: connect ECONNREFUSED 141.86.23.101:3128
118 verbose stack     at Object.exports._errnoException (util.js:1036:11)
118 verbose stack     at exports._exceptionWithHostPort (util.js:1059:20)
118 verbose stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
119 verbose cwd D:\Users\<username>\Documents\<projectpath>
120 error Windows_NT 6.1.7601
121 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
122 error node v6.7.0
123 error npm  v3.10.3
124 error code ECONNREFUSED
125 error errno ECONNREFUSED
126 error syscall connect
127 error Error: connect ECONNREFUSED 141.86.23.101:3128
127 error     at Object.exports._errnoException (util.js:1036:11)
127 error     at exports._exceptionWithHostPort (util.js:1059:20)
127 error     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
127 error  { Error: connect ECONNREFUSED 141.86.23.101:3128
127 error     at Object.exports._errnoException (util.js:1036:11)
127 error     at exports._exceptionWithHostPort (util.js:1059:20)
127 error     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
127 error   code: 'ECONNREFUSED',
127 error   errno: 'ECONNREFUSED',
127 error   syscall: 'connect',
127 error   address: '141.86.23.101',
127 error   port: 3128,
127 error   parent: 'fbjs' }
128 error If you are behind a proxy, please make sure that the
128 error 'proxy' config is set properly.  See: 'npm help config'
129 verbose exit [ 1, true ]
```

</details>
### supporting information:
- `npm -v` prints: 3.10.3
- `node -v` prints:  v6.5.0
- `npm config get registry` prints:  http://registry.npmjs.org
- Windows, OS X/macOS, or Linux?: Windows 7 Enterprise
- Network issues:
  - Geographic location where npm was run: Belgium
  - [X] I use a proxy to connect to the npm registry.
  - [X] I use a proxy to connect to the web.
  - [ don't know ] I use a proxy when downloading Git repos.
  - [ maybe ] I access the npm registry via a VPN
    Possibly this proxy goes through a VPN, I am honestly clueless about networking. In general, my 'location' is 'Italy' but I'm not in Italy, I don't know if this means VPN or just proxy.
  - [ ] I don't use a proxy, but have limited or unreliable internet access.
- Container:
  - [ ] I develop using Vagrant on Windows.
  - [ ] I develop using Vagrant on OS X or Linux.
  - [ ] I develop / deploy using Docker.
  - [ ] I deploy to a PaaS (Triton, Heroku).

`npm config get proxy` and `npm config get https-proxy` are both set to the correct values

**Comment by HuysentruytRuben** [comment]
So I was abled to succesfully run `npm install` at home, which helps but obviously didn't solve the problem. I can't really wait a day to install new packages every time. This does mean that it is probably an internal network/proxy problem but it's still strange to me that npm would sto pworking properly after an `npm cache clean`

**Comment by HuysentruytRuben** [comment]
By the way, I was able to resolve this by completely removing and re-installing npm but now I'm afraid to use the `npm cache clean` command

**Comment by legodude17** [comment]
So is the issue solved?

**Comment by HuysentruytRuben** [comment]
I don't currently want to try using `npm cache clean` to verify, so while I can't confirm that the problem is *really* solved, my situation is workable (I'll just manually remove cache/npm_modules when needed).

If this happens again, should I re-open or reference this issue?

**Comment by legodude17** [comment]
If it happens again, either will work, but I would prefer you reopen this one instead of making a new one.
