### ISSUE TITLE
Getting error during npm update

### ISSUE THREAD

**Issue by CharlesKwak** [npm/npm#14223]
#### I'm opening this issue because:
- [x] npm is crashing.
- [ ] npm is producing an incorrect install.
- [ ] npm is doing something I don't understand.
- [ ] Other (_see below for feature requests_):
#### What's going wrong?

I'm trying to clean cache or update npm.
npm throw errors. 
#### How can the CLI team reproduce the problem?

<details>

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Hochul\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'update' ]
2 info using npm@3.10.6
3 info using node@v6.7.0
4 verbose config Skipping project config: C:\Users\Hochul/.npmrc. (matches userconfig)
5 verbose stack Error: Cannot find module 'lodash._baseflatten'
5 verbose stack     at Function.Module._resolveFilename (module.js:455:15)
5 verbose stack     at Function.Module._load (module.js:403:25)
5 verbose stack     at Module.require (module.js:483:17)
5 verbose stack     at require (internal/module.js:20:19)
5 verbose stack     at Object.<anonymous> (C:\Users\Hochul\AppData\Roaming\npm\node_modules\npm\node_modules\lodash.union\index.js:9:19)
5 verbose stack     at Module._compile (module.js:556:32)
5 verbose stack     at Object.Module._extensions..js (module.js:565:10)
5 verbose stack     at Module.load (module.js:473:32)
5 verbose stack     at tryModuleLoad (module.js:432:12)
5 verbose stack     at Function.Module._load (module.js:424:3)
6 verbose cwd C:\Users\Hochul
7 error Windows_NT 10.0.14393
8 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Hochul\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "update"
9 error node v6.7.0
10 error npm  v3.10.6
11 error code MODULE_NOT_FOUND
12 error Cannot find module 'lodash._baseflatten'
13 error If you need help, you may report this error at:
13 error     <https://github.com/npm/npm/issues>
14 verbose exit [ 1, true ]
```

</details>
### supporting information:
- `npm -v` prints: 3.10.6
- `node -v` prints: v6.7.0
- `npm config get registry` prints: https://registry.npmjs.org/
- Windows, OS X/macOS, or Linux?:  Windows_NT 10.0.14393

**Comment by legodude17** [comment]
Try reinstalling npm.
