### ISSUE TITLE
fetch failed with status code 404 - Cannot install angular2-router-loader

### ISSUE THREAD

**Issue by carlos-meneses** [npm/npm#14222]
<details>
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'angular2-router-loader',
1 verbose cli   '--save-dev' ]
2 info using npm@3.10.3
3 info using node@v6.6.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData angular2-router-loader
8 silly fetchNamedPackageData angular2-router-loader
9 silly mapToRegistry name angular2-router-loader
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'angular2-router-loader',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'angular2-router-loader',
12 silly mapToRegistry   name: 'angular2-router-loader',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/angular2-router-loader
14 verbose request uri https://registry.npmjs.org/angular2-router-loader
15 verbose request no auth needed
16 info attempt registry request try #1 at 13:57:55
17 verbose request id a321b907852dcbc7
18 verbose etag "19ZXF365OFMUHLYRJVA0NMVYZ"
19 http request GET https://registry.npmjs.org/angular2-router-loader
20 http 304 https://registry.npmjs.org/angular2-router-loader
21 verbose headers { date: 'Sun, 09 Oct 2016 18:27:56 GMT',
21 verbose headers   via: '1.1 varnish',
21 verbose headers   'cache-control': 'max-age=300',
21 verbose headers   etag: '"19ZXF365OFMUHLYRJVA0NMVYZ"',
21 verbose headers   age: '237',
21 verbose headers   connection: 'keep-alive',
21 verbose headers   'x-served-by': 'cache-dfw1839-DFW',
21 verbose headers   'x-cache': 'HIT',
21 verbose headers   'x-cache-hits': '1',
21 verbose headers   'x-timer': 'S1476037676.661176,VS0,VE0',
21 verbose headers   vary: 'Accept-Encoding' }
22 silly get cb [ 304,
22 silly get   { date: 'Sun, 09 Oct 2016 18:27:56 GMT',
22 silly get     via: '1.1 varnish',
22 silly get     'cache-control': 'max-age=300',
22 silly get     etag: '"19ZXF365OFMUHLYRJVA0NMVYZ"',
22 silly get     age: '237',
22 silly get     connection: 'keep-alive',
22 silly get     'x-served-by': 'cache-dfw1839-DFW',
22 silly get     'x-cache': 'HIT',
22 silly get     'x-cache-hits': '1',
22 silly get     'x-timer': 'S1476037676.661176,VS0,VE0',
22 silly get     vary: 'Accept-Encoding' } ]
23 verbose etag https://registry.npmjs.org/angular2-router-loader from cache
24 verbose get saving angular2-router-loader to /home/osendev/.npm/registry.npmjs.org/angular2-router-loader/.cache.json
25 verbose correctMkdir /home/osendev/.npm correctMkdir not in flight; initializing
26 silly install normalizeTree
27 silly loadCurrentTree Finishing
28 silly loadIdealTree Starting
29 silly install loadIdealTree
30 silly cloneCurrentTree Starting
31 silly install cloneCurrentTreeToIdealTree
32 silly cloneCurrentTree Finishing
33 silly loadShrinkwrap Starting
34 silly install loadShrinkwrap
35 silly loadShrinkwrap Finishing
36 silly loadAllDepsIntoIdealTree Starting
37 silly install loadAllDepsIntoIdealTree
38 silly resolveWithNewModule angular2-router-loader@0.3.1 checking installable status
39 silly cache add args [ 'angular2-router-loader', null ]
40 verbose cache add spec angular2-router-loader
41 silly cache add parsed spec Result {
41 silly cache add   raw: 'angular2-router-loader',
41 silly cache add   scope: null,
41 silly cache add   escapedName: 'angular2-router-loader',
41 silly cache add   name: 'angular2-router-loader',
41 silly cache add   rawSpec: '',
41 silly cache add   spec: 'latest',
41 silly cache add   type: 'tag' }
42 silly addNamed angular2-router-loader@latest
43 verbose addNamed "latest" is being treated as a dist-tag for angular2-router-loader
44 info addNameTag [ 'angular2-router-loader', 'latest' ]
45 silly mapToRegistry name angular2-router-loader
46 silly mapToRegistry using default registry
47 silly mapToRegistry registry https://registry.npmjs.org/
48 silly mapToRegistry data Result {
48 silly mapToRegistry   raw: 'angular2-router-loader',
48 silly mapToRegistry   scope: null,
48 silly mapToRegistry   escapedName: 'angular2-router-loader',
48 silly mapToRegistry   name: 'angular2-router-loader',
48 silly mapToRegistry   rawSpec: '',
48 silly mapToRegistry   spec: 'latest',
48 silly mapToRegistry   type: 'tag' }
49 silly mapToRegistry uri https://registry.npmjs.org/angular2-router-loader
50 verbose addNameTag registry:https://registry.npmjs.org/angular2-router-loader not in flight; fetching
51 verbose get https://registry.npmjs.org/angular2-router-loader not expired, no request
52 silly addNameTag next cb for angular2-router-loader with tag latest
53 silly addNamed angular2-router-loader@0.3.1
54 verbose addNamed "0.3.1" is a plain semver version for angular2-router-loader
55 silly mapToRegistry name angular2-router-loader
56 silly mapToRegistry using default registry
57 silly mapToRegistry registry https://registry.npmjs.org/
58 silly mapToRegistry data Result {
58 silly mapToRegistry   raw: 'angular2-router-loader',
58 silly mapToRegistry   scope: null,
58 silly mapToRegistry   escapedName: 'angular2-router-loader',
58 silly mapToRegistry   name: 'angular2-router-loader',
58 silly mapToRegistry   rawSpec: '',
58 silly mapToRegistry   spec: 'latest',
58 silly mapToRegistry   type: 'tag' }
59 silly mapToRegistry uri https://registry.npmjs.org/angular2-router-loader
60 verbose addRemoteTarball https://registry.npmjs.org/angular2-router-loader/-/angular2-router-loader-0.3.1.tgz not in flight; adding
61 verbose addRemoteTarball [ 'https://registry.npmjs.org/angular2-router-loader/-/angular2-router-loader-0.3.1.tgz',
61 verbose addRemoteTarball   '46098af4c21d48f2dfc2c6df26b5be4185bb0cd7' ]
62 info retry fetch attempt 1 at 13:58:00
63 info attempt registry request try #1 at 13:58:00
64 http fetch GET https://registry.npmjs.org/angular2-router-loader/-/angular2-router-loader-0.3.1.tgz
65 http fetch 404 https://registry.npmjs.org/angular2-router-loader/-/angular2-router-loader-0.3.1.tgz
66 error fetch failed https://registry.npmjs.org/angular2-router-loader/-/angular2-router-loader-0.3.1.tgz
67 warn retry will retry, error on last attempt: Error: fetch failed with status code 404
68 info retry fetch attempt 2 at 13:58:11
69 info attempt registry request try #1 at 13:58:11
70 http fetch GET https://registry.npmjs.org/angular2-router-loader/-/angular2-router-loader-0.3.1.tgz
71 http fetch 404 https://registry.npmjs.org/angular2-router-loader/-/angular2-router-loader-0.3.1.tgz
72 error fetch failed https://registry.npmjs.org/angular2-router-loader/-/angular2-router-loader-0.3.1.tgz
73 warn retry will retry, error on last attempt: Error: fetch failed with status code 404
74 info retry fetch attempt 3 at 13:59:28
75 info attempt registry request try #1 at 13:59:28
76 http fetch GET https://registry.npmjs.org/angular2-router-loader/-/angular2-router-loader-0.3.1.tgz
77 http fetch 404 https://registry.npmjs.org/angular2-router-loader/-/angular2-router-loader-0.3.1.tgz
78 error fetch failed https://registry.npmjs.org/angular2-router-loader/-/angular2-router-loader-0.3.1.tgz
79 silly rollbackFailedOptional Starting
80 silly rollbackFailedOptional Finishing
81 silly runTopLevelLifecycles Starting
82 silly runTopLevelLifecycles Finishing
83 silly install printInstalled
84 verbose stack Error: fetch failed with status code 404
84 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/fetch.js:51:14)
84 verbose stack     at emitOne (events.js:96:13)
84 verbose stack     at Request.emit (events.js:188:7)
84 verbose stack     at Request.onRequestResponse (/usr/local/lib/node_modules/npm/node_modules/request/request.js:977:10)
84 verbose stack     at emitOne (events.js:96:13)
84 verbose stack     at ClientRequest.emit (events.js:188:7)
84 verbose stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:472:21)
84 verbose stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
84 verbose stack     at TLSSocket.socketOnData (_http_client.js:361:20)
84 verbose stack     at emitOne (events.js:96:13)
85 verbose cwd /var/www/html/laravel-angular/frontend
86 error Linux 3.13.0-96-generic
87 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "angular2-router-loader" "--save-dev"
88 error node v6.6.0
89 error npm  v3.10.3
90 error fetch failed with status code 404
91 error If you need help, you may report this error at:
91 error     <https://github.com/npm/npm/issues>
92 verbose exit [ 1, true ]
```
</details>

**Comment by soldair** [comment]
thank you for reporting this.
a new version 0.3.2 was published yesterday will this work for you?
0.3.1 looks like it was a failed publish that still updated the package metadata. 

I'll be looking in the logs to see if i can find anything interesting around 2016-10-07T20:39:59.662Z because a failed publish should not leave anything behind.

please open an issue on https://github.com/npm/registry/issues if you have any more difficulties. the registry issue tracker goes right to the registry team and helps us help you faster =)
