### ISSUE TITLE
Please help. I can't run gulp, it gives me error.

### ISSUE THREAD

**Issue by mirr** [npm/npm#14307]
I'm using laravel 5.3 and its homestead. I am trying to install npm so I could use elexir but I am always getting error. I tried to remove node module and re-install it but nothing changes. Doing this is wasting my time. I've been doing this for 2 nights but still getting the same error.

I tried all the suggested fixes I found here and in google but still getting the same error. I am not sure if what was I doing was wrong or there's something wrong with this npm thing....

I am really frustrated now...

```
[17:13:55] Using gulpfile /home/vagrant/apps/honey/gulpfile.js
[17:13:55] Starting 'all'...
[17:13:55] Starting 'sass'...
[17:13:56] 'sass' errored after 384 ms
[17:13:56] Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/vagrant/apps/honey/node_modules/gulp-sass/index.js:187:21)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
[17:13:56] 'all' errored after 395 ms
[17:13:56] Error in plugin 'run-sequence(sass)'
Message:
    Cannot find module 'node-sass'
Details:
    code: MODULE_NOT_FOUND
Stack:
Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/vagrant/apps/honey/node_modules/gulp-sass/index.js:187:21)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
root@homestead:/home/vagrant/apps/honey# sudo npm install node-sass
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! Linux 4.4.0-22-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "node-sass"
npm ERR! node v6.8.1
npm ERR! npm  v3.10.9
npm ERR! path ../node-sass/bin/node-sass
npm ERR! code EPROTO
npm ERR! errno -71
npm ERR! syscall symlink

npm ERR! EPROTO: protocol error, symlink '../node-sass/bin/node-sass' -> '/home/vagrant/apps/honey/node_modules/.bin/node-sass'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/apps/honey/npm-debug.log
```

**Comment by bruce-wayne-at-adobe** [comment]
Having the same issue.
