### ISSUE TITLE
"npm install pcap -g" is error

### ISSUE THREAD

**Issue by hktalent** [npm/npm#14313]
"npm install pcap -g" is error
os: mac os x 10.12

$ brew info libpcap
homebrew/dupes/libpcap: stable 1.7.4, HEAD [keg-only]
Portable library for network traffic capture
http://www.tcpdump.org/
/usr/local/Cellar/libpcap/1.7.4 (99 files, 791.5K)
  Built from source on 2016-10-18 at 11:25:33
From: https://github.com/Homebrew/homebrew-dupes/blob/master/libpcap.rb
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

macOS already provides this software and installing another version in
parallel can cause all kinds of trouble.

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

```
LDFLAGS:  -L/usr/local/opt/libpcap/lib
CPPFLAGS: -I/usr/local/opt/libpcap/include
```

QQ1160:~ xiatian$ brew info pcap
homebrew/science/pcap: stable 2005-06-07
http://seq.cs.iastate.edu/pcap.html
/usr/local/Cellar/pcap/2005-06-07 (28 files, 733.8K) *
  Built from source on 2016-10-18 at 11:23:37
From: https://github.com/Homebrew/homebrew-science/blob/master/pcap.rb

$ npm install pcap -g

> socketwatcher@0.2.1 install /usr/local/lib/node_modules/pcap/node_modules/socketwatcher
> node-gyp rebuild

  CXX(target) Release/obj.target/socketwatcher/socket_watcher.o
In file included from ../socket_watcher.cpp:5:
In file included from ../socket_watcher.hpp:8:
In file included from ../node_modules/nan/nan.h:80:
../node_modules/nan/nan_new.h:33:56: warning: 'ToInt32' is deprecated
      [-Wdeprecated-declarations]
Tov8::Int32(v8::Handlev8::Integer i)   { return i->ToInt32(); }
                                                       ^
/Users/xiatian/.node-gyp/6.8.1/include/node/v8.h:8202:21: note: 'ToInt32' has
      been explicitly marked deprecated here
Local<Int32> Value::ToInt32() const {
                    ^
In file included from ../socket_watcher.cpp:5:
In file included from ../socket_watcher.hpp:8:
In file included from ../node_modules/nan/nan.h:80:
../node_modules/nan/nan_new.h:38:56: warning: 'ToUint32' is deprecated
      [-Wdeprecated-declarations]
Tov8::Uint32(v8::Handlev8::Integer i)  { return i->ToUint32(); }
                                                       ^
/Users/xiatian/.node-gyp/6.8.1/include/node/v8.h:8196:22: note: 'ToUint32' has
      been explicitly marked deprecated here
Local<Uint32> Value::ToUint32() const {
                     ^
In file included from ../socket_watcher.cpp:5:
In file included from ../socket_watcher.hpp:8:
In file included from ../node_modules/nan/nan.h:80:
In file included from ../node_modules/nan/nan_new.h:190:
../node_modules/nan/nan_implementation_12_inl.h:48:29: warning: 'New' is
      deprecated [-Wdeprecated-declarations]
  return v8::BooleanObject::New(value).Asv8::BooleanObject();
                            ^
/Users/xiatian/.node-gyp/6.8.1/include/node/v8.h:4007:56: note: 'New' has been
      explicitly marked deprecated here
  V8_DEPRECATED("Pass an isolate", static Local<Value> New(bool value));
                                                       ^
In file included from ../socket_watcher.cpp:5:
In file included from ../socket_watcher.hpp:8:
In file included from ../node_modules/nan/nan.h:80:
In file included from ../node_modules/nan/nan_new.h:190:
../node_modules/nan/nan_implementation_12_inl.h:165:30: warning: 'Compile' is
      deprecated [-Wdeprecated-declarations]
  return v8::ScriptCompiler::Compile(v8::Isolate::GetCurrent(), &src);
                             ^
/Users/xiatian/.node-gyp/6.8.1/include/node/v8.h:1354:21: note: 'Compile' has
      been explicitly marked deprecated here
      Local<Script> Compile(Isolate\* isolate, Source\* source,
                    ^
In file included from ../socket_watcher.cpp:5:
In file included from ../socket_watcher.hpp:8:
In file included from ../node_modules/nan/nan.h:80:
In file included from ../node_modules/nan/nan_new.h:190:
../node_modules/nan/nan_implementation_12_inl.h:172:30: warning: 'Compile' is
      deprecated [-Wdeprecated-declarations]
  return v8::ScriptCompiler::Compile(v8::Isolate::GetCurrent(), &src);
                             ^
/Users/xiatian/.node-gyp/6.8.1/include/node/v8.h:1354:21: note: 'Compile' has
      been explicitly marked deprecated here
      Local<Script> Compile(Isolate\* isolate, Source\* source,
                    ^
In file included from ../socket_watcher.cpp:5:
In file included from ../socket_watcher.hpp:8:
In file included from ../node_modules/nan/nan.h:80:
In file included from ../node_modules/nan/nan_new.h:190:
../node_modules/nan/nan_implementation_12_inl.h:181:66: error: too many
      arguments to function call, expected at most 2, have 4
  return v8::Signature::New(v8::Isolate::GetCurrent(), receiver, argc, argv);
         ~~~~~~~~~~~~~~~~~~                                      ^~~~~~~~~~
/Users/xiatian/.node-gyp/6.8.1/include/node/v8.h:4832:3: note: 'New' declared
      here
  static Local<Signature> New(
  ^
In file included from ../socket_watcher.cpp:5:
In file included from ../socket_watcher.hpp:8:
In file included from ../node_modules/nan/nan.h:80:
In file included from ../node_modules/nan/nan_new.h:190:
../node_modules/nan/nan_implementation_12_inl.h:206:22: warning: 
      'NewFromOneByte' is deprecated [-Wdeprecated-declarations]
  return v8::String::NewFromOneByte(v8::Isolate::GetCurrent(), value,
                     ^
/Users/xiatian/.node-gyp/6.8.1/include/node/v8.h:2334:21: note: 
      'NewFromOneByte' has been explicitly marked deprecated here
      Local<String> NewFromOneByte(Isolate\* isolate, const uint8_t\* data,
                    ^
In file included from ../socket_watcher.cpp:5:
In file included from ../socket_watcher.hpp:8:
In file included from ../node_modules/nan/nan.h:80:
In file included from ../node_modules/nan/nan_new.h:190:
../node_modules/nan/nan_implementation_12_inl.h:218:22: warning: 'NewExternal'
      is deprecated [-Wdeprecated-declarations]
  return v8::String::NewExternal(v8::Isolate::GetCurrent(), value);
                     ^
/Users/xiatian/.node-gyp/6.8.1/include/node/v8.h:2372:38: note: 'NewExternal'
      has been explicitly marked deprecated here
                       Local<String> NewExternal(
                                     ^
In file included from ../socket_watcher.cpp:5:
In file included from ../socket_watcher.hpp:8:
In file included from ../node_modules/nan/nan.h:80:
In file included from ../node_modules/nan/nan_new.h:190:
../node_modules/nan/nan_implementation_12_inl.h:238:30: warning: 
      'CompileUnbound' is deprecated [-Wdeprecated-declarations]
  return v8::ScriptCompiler::CompileUnbound(v8::Isolate::GetCurrent(), &src);
                             ^
/Users/xiatian/.node-gyp/6.8.1/include/node/v8.h:1334:45: note: 
      'CompileUnbound' has been explicitly marked deprecated here
                       Local<UnboundScript> CompileUnbound(
                                            ^
In file included from ../socket_watcher.cpp:5:
In file included from ../socket_watcher.hpp:8:
In file included from ../node_modules/nan/nan.h:80:
In file included from ../node_modules/nan/nan_new.h:190:
../node_modules/nan/nan_implementation_12_inl.h:245:30: warning: 
      'CompileUnbound' is deprecated [-Wdeprecated-declarations]
  return v8::ScriptCompiler::CompileUnbound(v8::Isolate::GetCurrent(), &src);
                             ^
/Users/xiatian/.node-gyp/6.8.1/include/node/v8.h:1334:45: note: 
      'CompileUnbound' has been explicitly marked deprecated here
                       Local<UnboundScript> CompileUnbound(
                                            ^
In file included from ../socket_watcher.cpp:5:
In file included from ../socket_watcher.hpp:8:
../node_modules/nan/nan.h:171:25: error: redefinition of '_NanEnsureLocal'
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                        ^
../node_modules/nan/nan.h:166:25: note: previous definition is here
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                        ^
../node_modules/nan/nan.h:194:39: warning: 'IdleNotification' is deprecated
      [-Wdeprecated-declarations]
    return v8::Isolate::GetCurrent()->IdleNotification(idle_time_in_ms);
                                      ^
/Users/xiatian/.node-gyp/6.8.1/include/node/v8.h:6114:22: note: 
      'IdleNotification' has been explicitly marked deprecated here
                bool IdleNotification(int idle_time_in_ms));
                     ^
In file included from ../socket_watcher.cpp:5:
In file included from ../socket_watcher.hpp:8:
../node_modules/nan/nan.h:317:12: error: no matching function for call to
      '_NanEnsureLocal'
    return NanEscapeScope(NanNew(v8::Undefined(v8::Isolate::GetCurrent())));
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:303:43: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))

```
                                      ^~~~~~~~~~~~~~~
```

../node_modules/nan/nan.h:171:25: note: candidate template ignored: substitution
      failure [with T = v8::Primitive]
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                        ^
../node_modules/nan/nan.h:322:12: error: no matching function for call to
      '_NanEnsureLocal'
    return NanEscapeScope(NanNew(v8::Null(v8::Isolate::GetCurrent())));
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:303:43: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))

```
                                      ^~~~~~~~~~~~~~~
```

../node_modules/nan/nan.h:171:25: note: candidate template ignored: substitution
      failure [with T = v8::Primitive]
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                        ^
../node_modules/nan/nan.h:327:12: error: no matching function for call to
      '_NanEnsureLocal'
    return NanEscapeScope(NanNew(v8::True(v8::Isolate::GetCurrent())));
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:303:43: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))

```
                                      ^~~~~~~~~~~~~~~
```

../node_modules/nan/nan.h:171:25: note: candidate template ignored: substitution
      failure [with T = v8::Boolean]
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                        ^
../node_modules/nan/nan.h:332:12: error: no matching function for call to
      '_NanEnsureLocal'
    return NanEscapeScope(NanNew(v8::False(v8::Isolate::GetCurrent())));
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:303:43: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))

```
                                      ^~~~~~~~~~~~~~~
```

../node_modules/nan/nan.h:171:25: note: candidate template ignored: substitution
      failure [with T = v8::Boolean]
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                        ^
../node_modules/nan/nan.h:376:20: error: no type named 'GCEpilogueCallback' in
      'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:382:20: error: no type named 'GCEpilogueCallback' in
      'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback) {
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:387:20: error: no type named 'GCPrologueCallback' in
      'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:393:20: error: no type named 'GCPrologueCallback' in
      'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback) {
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:564:13: error: no member named 'smalloc' in namespace
      'node'
    , node::smalloc::FreeCallback callback
      ~~~~~~^
../node_modules/nan/nan.h:575:12: error: no matching function for call to 'New'
    return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
           ^~~~~~~~~~~~~~~~~
/Users/xiatian/.node-gyp/6.8.1/include/node/node_buffer.h:46:40: note: 
      candidate function not viable: 2nd argument ('const char _') would lose
      const qualifier
NODE_EXTERN v8::MaybeLocalv8::Object New(v8::Isolate_ isolate,
                                       ^
/Users/xiatian/.node-gyp/6.8.1/include/node/node_buffer.h:34:40: note: 
      candidate function not viable: no known conversion from 'const char _' to
      'v8::Localv8::String' for 2nd argument
NODE_EXTERN v8::MaybeLocalv8::Object New(v8::Isolate_ isolate,
                                       ^
/Users/xiatian/.node-gyp/6.8.1/include/node/node_buffer.h:31:40: note: 
      candidate function not viable: requires 2 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocalv8::Object New(v8::Isolate\* isolate, size_t length);
                                       ^
/Users/xiatian/.node-gyp/6.8.1/include/node/node_buffer.h:39:40: note: 
      candidate function not viable: requires 5 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocalv8::Object New(v8::Isolate\* isolate,
                                       ^
In file included from ../socket_watcher.cpp:5:
In file included from ../socket_watcher.hpp:8:
../node_modules/nan/nan.h:579:12: error: no viable conversion from returned
      value of type 'v8::MaybeLocalv8::Object' to function return type
      'v8::Localv8::Object'
    return node::Buffer::New(v8::Isolate::GetCurrent(), size);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/xiatian/.node-gyp/6.8.1/include/node/v8.h:218:7: note: candidate
      constructor (the implicit copy constructor) not viable: no known
      conversion from 'v8::MaybeLocalv8::Object' to 'const
      v8::Localv8::Object &' for 1st argument
class Local {
      ^
/Users/xiatian/.node-gyp/6.8.1/include/node/v8.h:218:7: note: candidate
      constructor (the implicit move constructor) not viable: no known
      conversion from 'v8::MaybeLocalv8::Object' to 'v8::Localv8::Object &&'
      for 1st argument
/Users/xiatian/.node-gyp/6.8.1/include/node/v8.h:222:13: note: candidate
      template ignored: could not match 'Local' against 'MaybeLocal'
  V8_INLINE Local(Local<S> that)
            ^
In file included from ../socket_watcher.cpp:5:
In file included from ../socket_watcher.hpp:8:
../node_modules/nan/nan.h:586:26: error: no member named 'Use' in namespace
      'node::Buffer'
    return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
           ~~~~~~~~~~~~~~^
../node_modules/nan/nan.h:613:32: warning: 'Compile' is deprecated
      [-Wdeprecated-declarations]
    return v8::ScriptCompiler::Compile(v8::Isolate::GetCurrent(), &source);
                               ^
/Users/xiatian/.node-gyp/6.8.1/include/node/v8.h:1354:21: note: 'Compile' has
      been explicitly marked deprecated here
      Local<Script> Compile(Isolate\* isolate, Source\* source,
                    ^
In file included from ../socket_watcher.cpp:5:
In file included from ../socket_watcher.hpp:8:
../node_modules/nan/nan.h:620:32: warning: 'Compile' is deprecated
      [-Wdeprecated-declarations]
    return v8::ScriptCompiler::Compile(v8::Isolate::GetCurrent(), &source);
                               ^
/Users/xiatian/.node-gyp/6.8.1/include/node/v8.h:1354:21: note: 'Compile' has
      been explicitly marked deprecated here
      Local<Script> Compile(Isolate\* isolate, Source\* source,
                    ^
In file included from ../socket_watcher.cpp:5:
In file included from ../socket_watcher.hpp:8:
../node_modules/nan/nan.h:1403:12: error: no matching function for call to
      '_NanEnsureLocal'
    return NanEscapeScope(NanNew(handle)->Get(kCallbackIndex)
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:303:43: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))

```
                                      ^~~~~~~~~~~~~~~
```

../node_modules/nan/nan.h:171:25: note: candidate template ignored: substitution
      failure [with T = v8::Function]
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                        ^
../node_modules/nan/nan.h:1452:12: error: no matching function for call to
      '_NanEnsureLocal'
    return NanEscapeScope(node::MakeCallback(
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:303:43: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))

```
                                      ^~~~~~~~~~~~~~~
```

../node_modules/nan/nan.h:171:25: note: candidate template ignored: substitution
      failure [with T = v8::Value]
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                        ^
../node_modules/nan/nan.h:1522:12: error: no matching function for call to
      '_NanEnsureLocal'
    return NanEscapeScope(handle->Get(NanNew(key)).Asv8::Object());
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:303:43: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))

```
                                      ^~~~~~~~~~~~~~~
```

../node_modules/nan/nan.h:171:25: note: candidate template ignored: substitution
      failure [with T = v8::Object]
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                        ^
../socket_watcher.cpp:113:26: warning: 'NewInstance' is deprecated
      [-Wdeprecated-declarations]
    NanReturnValue(cons->NewInstance());
                         ^
/Users/xiatian/.node-gyp/6.8.1/include/node/v8.h:3274:52: note: 'NewInstance'
      has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", Local<Object> NewInstance() const);
                                                   ^
13 warnings and 17 errors generated.
make: **\* [Release/obj.target/socketwatcher/socket_watcher.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.0.0
gyp ERR! command "/usr/local/Cellar/node/6.8.1/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/pcap/node_modules/socketwatcher
gyp ERR! node -v v6.8.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
/usr/local/lib
└── (empty)

npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/Cellar/node/6.8.1/bin/node" "/usr/local/bin/npm" "install" "pcap" "-g"
npm ERR! node v6.8.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! socketwatcher@0.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the socketwatcher@0.2.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the socketwatcher package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs socketwatcher
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls socketwatcher
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/xiatian/npm-debug.log
npm ERR! code 1

**Comment by watilde** [comment]
Hello! Thanks for reporting this. This is likely a problem with the pcap package, not with npm itself. I think it would be better if you can report it to the author directly: https://github.com/mranney/node_pcap

Thanks.

**Comment by zkat** [comment]
Closing, since it's not an npm-specific issue. Please contact the pcap devs, as @watilde mentioned. Cheers!
