### ISSUE TITLE
SELF_SIGNED_CERT_IN_CHAIN

### ISSUE THREAD

**Issue by dineshthanam** [npm/npm#14318]
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\node.exe',
1 verbose cli   'D:\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@2.15.9
3 info using node@v4.6.0
4 verbose readDependencies loading dependencies from D:\angularphonecat\package.json
5 verbose install where, deps [ 'D:\\angularphonecat',
5 verbose install   [ 'bower',
5 verbose install     'http-server',
5 verbose install     'jasmine-core',
5 verbose install     'karma',
5 verbose install     'karma-chrome-launcher',
5 verbose install     'karma-firefox-launcher',
5 verbose install     'karma-jasmine',
5 verbose install     'protractor' ] ]
6 verbose install where, peers [ 'D:\\angularphonecat', [] ]
7 verbose installManyTop reading for lifecycle D:\angularphonecat\package.json
8 info preinstall angular-phonecat@0.0.0
9 verbose readDependencies loading dependencies from D:\angularphonecat\package.json
10 silly cache add args [ 'bower@^1.7.7', null ]
11 verbose cache add spec bower@^1.7.7
12 silly cache add args [ 'http-server@^0.9.0', null ]
13 verbose cache add spec http-server@^0.9.0
14 silly cache add parsed spec Result {
14 silly cache add   raw: 'bower@^1.7.7',
14 silly cache add   scope: null,
14 silly cache add   name: 'bower',
14 silly cache add   rawSpec: '^1.7.7',
14 silly cache add   spec: '>=1.7.7 <2.0.0',
14 silly cache add   type: 'range' }
15 silly addNamed bower@>=1.7.7 <2.0.0
16 verbose addNamed ">=1.7.7 <2.0.0" is a valid semver range for bower
17 silly addNameRange { name: 'bower', range: '>=1.7.7 <2.0.0', hasData: false }
18 silly mapToRegistry name bower
19 silly mapToRegistry using default registry
20 silly mapToRegistry registry https://registry.npmjs.org/
21 silly mapToRegistry data Result {
21 silly mapToRegistry   raw: 'bower',
21 silly mapToRegistry   scope: null,
21 silly mapToRegistry   name: 'bower',
21 silly mapToRegistry   rawSpec: '',
21 silly mapToRegistry   spec: 'latest',
21 silly mapToRegistry   type: 'tag' }
22 silly mapToRegistry uri https://registry.npmjs.org/bower
23 verbose addNameRange registry:https://registry.npmjs.org/bower not in flight; fetching
24 silly cache add parsed spec Result {
24 silly cache add   raw: 'http-server@^0.9.0',
24 silly cache add   scope: null,
24 silly cache add   name: 'http-server',
24 silly cache add   rawSpec: '^0.9.0',
24 silly cache add   spec: '>=0.9.0 <0.10.0',
24 silly cache add   type: 'range' }
25 silly addNamed http-server@>=0.9.0 <0.10.0
26 verbose addNamed ">=0.9.0 <0.10.0" is a valid semver range for http-server
27 silly addNameRange { name: 'http-server', range: '>=0.9.0 <0.10.0', hasData: false }
28 silly mapToRegistry name http-server
29 silly mapToRegistry using default registry
30 silly mapToRegistry registry https://registry.npmjs.org/
31 silly mapToRegistry data Result {
31 silly mapToRegistry   raw: 'http-server',
31 silly mapToRegistry   scope: null,
31 silly mapToRegistry   name: 'http-server',
31 silly mapToRegistry   rawSpec: '',
31 silly mapToRegistry   spec: 'latest',
31 silly mapToRegistry   type: 'tag' }
32 silly mapToRegistry uri https://registry.npmjs.org/http-server
33 verbose addNameRange registry:https://registry.npmjs.org/http-server not in flight; fetching
34 silly cache add args [ 'jasmine-core@^2.4.1', null ]
35 verbose cache add spec jasmine-core@^2.4.1
36 silly cache add parsed spec Result {
36 silly cache add   raw: 'jasmine-core@^2.4.1',
36 silly cache add   scope: null,
36 silly cache add   name: 'jasmine-core',
36 silly cache add   rawSpec: '^2.4.1',
36 silly cache add   spec: '>=2.4.1 <3.0.0',
36 silly cache add   type: 'range' }
37 silly addNamed jasmine-core@>=2.4.1 <3.0.0
38 verbose addNamed ">=2.4.1 <3.0.0" is a valid semver range for jasmine-core
39 silly addNameRange { name: 'jasmine-core', range: '>=2.4.1 <3.0.0', hasData: false }
40 silly mapToRegistry name jasmine-core
41 silly mapToRegistry using default registry
42 silly mapToRegistry registry https://registry.npmjs.org/
43 silly mapToRegistry data Result {
43 silly mapToRegistry   raw: 'jasmine-core',
43 silly mapToRegistry   scope: null,
43 silly mapToRegistry   name: 'jasmine-core',
43 silly mapToRegistry   rawSpec: '',
43 silly mapToRegistry   spec: 'latest',
43 silly mapToRegistry   type: 'tag' }
44 silly mapToRegistry uri https://registry.npmjs.org/jasmine-core
45 verbose addNameRange registry:https://registry.npmjs.org/jasmine-core not in flight; fetching
46 silly cache add args [ 'karma@^0.13.22', null ]
47 verbose cache add spec karma@^0.13.22
48 silly cache add parsed spec Result {
48 silly cache add   raw: 'karma@^0.13.22',
48 silly cache add   scope: null,
48 silly cache add   name: 'karma',
48 silly cache add   rawSpec: '^0.13.22',
48 silly cache add   spec: '>=0.13.22 <0.14.0',
48 silly cache add   type: 'range' }
49 silly addNamed karma@>=0.13.22 <0.14.0
50 verbose addNamed ">=0.13.22 <0.14.0" is a valid semver range for karma
51 silly addNameRange { name: 'karma', range: '>=0.13.22 <0.14.0', hasData: false }
52 silly mapToRegistry name karma
53 silly mapToRegistry using default registry
54 silly mapToRegistry registry https://registry.npmjs.org/
55 silly mapToRegistry data Result {
55 silly mapToRegistry   raw: 'karma',
55 silly mapToRegistry   scope: null,
55 silly mapToRegistry   name: 'karma',
55 silly mapToRegistry   rawSpec: '',
55 silly mapToRegistry   spec: 'latest',
55 silly mapToRegistry   type: 'tag' }
56 silly mapToRegistry uri https://registry.npmjs.org/karma
57 verbose addNameRange registry:https://registry.npmjs.org/karma not in flight; fetching
58 silly cache add args [ 'karma-chrome-launcher@^0.2.3', null ]
59 verbose cache add spec karma-chrome-launcher@^0.2.3
60 silly cache add parsed spec Result {
60 silly cache add   raw: 'karma-chrome-launcher@^0.2.3',
60 silly cache add   scope: null,
60 silly cache add   name: 'karma-chrome-launcher',
60 silly cache add   rawSpec: '^0.2.3',
60 silly cache add   spec: '>=0.2.3 <0.3.0',
60 silly cache add   type: 'range' }
61 silly addNamed karma-chrome-launcher@>=0.2.3 <0.3.0
62 verbose addNamed ">=0.2.3 <0.3.0" is a valid semver range for karma-chrome-launcher
63 silly addNameRange { name: 'karma-chrome-launcher',
63 silly addNameRange   range: '>=0.2.3 <0.3.0',
63 silly addNameRange   hasData: false }
64 silly mapToRegistry name karma-chrome-launcher
65 silly mapToRegistry using default registry
66 silly mapToRegistry registry https://registry.npmjs.org/
67 silly mapToRegistry data Result {
67 silly mapToRegistry   raw: 'karma-chrome-launcher',
67 silly mapToRegistry   scope: null,
67 silly mapToRegistry   name: 'karma-chrome-launcher',
67 silly mapToRegistry   rawSpec: '',
67 silly mapToRegistry   spec: 'latest',
67 silly mapToRegistry   type: 'tag' }
68 silly mapToRegistry uri https://registry.npmjs.org/karma-chrome-launcher
69 verbose addNameRange registry:https://registry.npmjs.org/karma-chrome-launcher not in flight; fetching
70 silly cache add args [ 'karma-firefox-launcher@^0.1.7', null ]
71 verbose cache add spec karma-firefox-launcher@^0.1.7
72 silly cache add parsed spec Result {
72 silly cache add   raw: 'karma-firefox-launcher@^0.1.7',
72 silly cache add   scope: null,
72 silly cache add   name: 'karma-firefox-launcher',
72 silly cache add   rawSpec: '^0.1.7',
72 silly cache add   spec: '>=0.1.7 <0.2.0',
72 silly cache add   type: 'range' }
73 silly addNamed karma-firefox-launcher@>=0.1.7 <0.2.0
74 verbose addNamed ">=0.1.7 <0.2.0" is a valid semver range for karma-firefox-launcher
75 silly addNameRange { name: 'karma-firefox-launcher',
75 silly addNameRange   range: '>=0.1.7 <0.2.0',
75 silly addNameRange   hasData: false }
76 silly mapToRegistry name karma-firefox-launcher
77 silly mapToRegistry using default registry
78 silly mapToRegistry registry https://registry.npmjs.org/
79 silly mapToRegistry data Result {
79 silly mapToRegistry   raw: 'karma-firefox-launcher',
79 silly mapToRegistry   scope: null,
79 silly mapToRegistry   name: 'karma-firefox-launcher',
79 silly mapToRegistry   rawSpec: '',
79 silly mapToRegistry   spec: 'latest',
79 silly mapToRegistry   type: 'tag' }
80 silly mapToRegistry uri https://registry.npmjs.org/karma-firefox-launcher
81 verbose addNameRange registry:https://registry.npmjs.org/karma-firefox-launcher not in flight; fetching
82 silly cache add args [ 'karma-jasmine@^0.3.8', null ]
83 verbose cache add spec karma-jasmine@^0.3.8
84 silly cache add parsed spec Result {
84 silly cache add   raw: 'karma-jasmine@^0.3.8',
84 silly cache add   scope: null,
84 silly cache add   name: 'karma-jasmine',
84 silly cache add   rawSpec: '^0.3.8',
84 silly cache add   spec: '>=0.3.8 <0.4.0',
84 silly cache add   type: 'range' }
85 silly addNamed karma-jasmine@>=0.3.8 <0.4.0
86 verbose addNamed ">=0.3.8 <0.4.0" is a valid semver range for karma-jasmine
87 silly addNameRange { name: 'karma-jasmine',
87 silly addNameRange   range: '>=0.3.8 <0.4.0',
87 silly addNameRange   hasData: false }
88 silly mapToRegistry name karma-jasmine
89 silly mapToRegistry using default registry
90 silly mapToRegistry registry https://registry.npmjs.org/
91 silly mapToRegistry data Result {
91 silly mapToRegistry   raw: 'karma-jasmine',
91 silly mapToRegistry   scope: null,
91 silly mapToRegistry   name: 'karma-jasmine',
91 silly mapToRegistry   rawSpec: '',
91 silly mapToRegistry   spec: 'latest',
91 silly mapToRegistry   type: 'tag' }
92 silly mapToRegistry uri https://registry.npmjs.org/karma-jasmine
93 verbose addNameRange registry:https://registry.npmjs.org/karma-jasmine not in flight; fetching
94 silly cache add args [ 'protractor@^3.2.2', null ]
95 verbose cache add spec protractor@^3.2.2
96 silly cache add parsed spec Result {
96 silly cache add   raw: 'protractor@^3.2.2',
96 silly cache add   scope: null,
96 silly cache add   name: 'protractor',
96 silly cache add   rawSpec: '^3.2.2',
96 silly cache add   spec: '>=3.2.2 <4.0.0',
96 silly cache add   type: 'range' }
97 silly addNamed protractor@>=3.2.2 <4.0.0
98 verbose addNamed ">=3.2.2 <4.0.0" is a valid semver range for protractor
99 silly addNameRange { name: 'protractor', range: '>=3.2.2 <4.0.0', hasData: false }
100 silly mapToRegistry name protractor
101 silly mapToRegistry using default registry
102 silly mapToRegistry registry https://registry.npmjs.org/
103 silly mapToRegistry data Result {
103 silly mapToRegistry   raw: 'protractor',
103 silly mapToRegistry   scope: null,
103 silly mapToRegistry   name: 'protractor',
103 silly mapToRegistry   rawSpec: '',
103 silly mapToRegistry   spec: 'latest',
103 silly mapToRegistry   type: 'tag' }
104 silly mapToRegistry uri https://registry.npmjs.org/protractor
105 verbose addNameRange registry:https://registry.npmjs.org/protractor not in flight; fetching
106 verbose request uri https://registry.npmjs.org/bower
107 verbose request no auth needed
108 info attempt registry request try #1 at 6:36:42 PM
109 verbose request id d4dd82ba82d23701
110 http request GET https://registry.npmjs.org/bower
111 verbose request uri https://registry.npmjs.org/http-server
112 verbose request no auth needed
113 info attempt registry request try #1 at 6:36:42 PM
114 http request GET https://registry.npmjs.org/http-server
115 verbose request uri https://registry.npmjs.org/jasmine-core
116 verbose request no auth needed
117 info attempt registry request try #1 at 6:36:42 PM
118 http request GET https://registry.npmjs.org/jasmine-core
119 verbose request uri https://registry.npmjs.org/karma
120 verbose request no auth needed
121 info attempt registry request try #1 at 6:36:42 PM
122 http request GET https://registry.npmjs.org/karma
123 verbose request uri https://registry.npmjs.org/karma-chrome-launcher
124 verbose request no auth needed
125 info attempt registry request try #1 at 6:36:42 PM
126 http request GET https://registry.npmjs.org/karma-chrome-launcher
127 verbose request uri https://registry.npmjs.org/karma-firefox-launcher
128 verbose request no auth needed
129 info attempt registry request try #1 at 6:36:42 PM
130 http request GET https://registry.npmjs.org/karma-firefox-launcher
131 verbose request uri https://registry.npmjs.org/karma-jasmine
132 verbose request no auth needed
133 info attempt registry request try #1 at 6:36:42 PM
134 http request GET https://registry.npmjs.org/karma-jasmine
135 verbose request uri https://registry.npmjs.org/protractor
136 verbose request no auth needed
137 info attempt registry request try #1 at 6:36:42 PM
138 http request GET https://registry.npmjs.org/protractor
139 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
140 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
141 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
142 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
143 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
144 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
145 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
146 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
147 info attempt registry request try #2 at 6:36:53 PM
148 http request GET https://registry.npmjs.org/http-server
149 info attempt registry request try #2 at 6:36:53 PM
150 http request GET https://registry.npmjs.org/karma-firefox-launcher
151 info attempt registry request try #2 at 6:36:53 PM
152 http request GET https://registry.npmjs.org/karma
153 info attempt registry request try #2 at 6:36:53 PM
154 http request GET https://registry.npmjs.org/bower
155 info attempt registry request try #2 at 6:36:53 PM
156 http request GET https://registry.npmjs.org/jasmine-core
157 info attempt registry request try #2 at 6:36:53 PM
158 http request GET https://registry.npmjs.org/karma-chrome-launcher
159 info attempt registry request try #2 at 6:36:53 PM
160 http request GET https://registry.npmjs.org/karma-jasmine
161 info attempt registry request try #2 at 6:36:53 PM
162 http request GET https://registry.npmjs.org/protractor
163 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
164 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
165 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
166 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
167 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
168 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
169 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
170 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
171 info attempt registry request try #3 at 6:37:53 PM
172 http request GET https://registry.npmjs.org/karma-firefox-launcher
173 info attempt registry request try #3 at 6:37:53 PM
174 http request GET https://registry.npmjs.org/http-server
175 info attempt registry request try #3 at 6:37:53 PM
176 http request GET https://registry.npmjs.org/bower
177 info attempt registry request try #3 at 6:37:53 PM
178 http request GET https://registry.npmjs.org/karma
179 info attempt registry request try #3 at 6:37:53 PM
180 http request GET https://registry.npmjs.org/jasmine-core
181 info attempt registry request try #3 at 6:37:53 PM
182 http request GET https://registry.npmjs.org/karma-jasmine
183 info attempt registry request try #3 at 6:37:53 PM
184 http request GET https://registry.npmjs.org/karma-chrome-launcher
185 info attempt registry request try #3 at 6:37:53 PM
186 http request GET https://registry.npmjs.org/protractor
187 verbose stack Error: self signed certificate in certificate chain
187 verbose stack     at Error (native)
187 verbose stack     at TLSSocket.<anonymous> (_tls_wrap.js:1022:38)
187 verbose stack     at emitNone (events.js:67:13)
187 verbose stack     at TLSSocket.emit (events.js:166:7)
187 verbose stack     at TLSSocket._init.ssl.onclienthello.ssl.oncertcb.TLSSocket._finishInit (_tls_wrap.js:586:8)
187 verbose stack     at TLSWrap.ssl.onclienthello.ssl.oncertcb.ssl.onnewsession.ssl.onhandshakedone (_tls_wrap.js:428:38)
188 verbose cwd D:\angularphonecat
189 error Windows_NT 6.1.7601
190 error argv "D:\\node.exe" "D:\\node_modules\\npm\\bin\\npm-cli.js" "install"
191 error node v4.6.0
192 error npm  v2.15.9
193 error code SELF_SIGNED_CERT_IN_CHAIN
194 error self signed certificate in certificate chain
195 error If you need help, you may report this error at:
195 error     <https://github.com/npm/npm/issues>
196 verbose exit [ 1, true ]

**Comment by snopeks** [comment]
Hi @dineshthanam ! You're running into a proxy config issue, we recommend speaking with your sysadmin about configuring SSL support for the proxy correctly. If you have more questions, you can reach out to us at support@npmjs.com!

**Comment by adalvi-carecloud** [comment]
Run these commands to set http proxy and That is it!!!

npm config set proxy 

npm config set https-proxy

**Comment by snopeks** [comment]
@adalvi-carecloud awesome! 🎉

**Comment by legodude17** [comment]
@dineshthanam, are you still having this issue?
