### ISSUE TITLE
self signed certificate in certificate chain

### ISSUE THREAD

**Issue by adalvi-carecloud** [npm/npm#14335]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/6.8.1/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'underscore' ]
2 info using npm@3.10.8
3 info using node@v6.8.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData underscore
8 silly fetchNamedPackageData underscore
9 silly mapToRegistry name underscore
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'underscore',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'underscore',
12 silly mapToRegistry   name: 'underscore',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/underscore
14 verbose request uri https://registry.npmjs.org/underscore
15 verbose request no auth needed
16 info attempt registry request try #1 at 12:59:17 PM
17 verbose request id 4db2a003bdaa5a60
18 http request GET https://registry.npmjs.org/underscore
19 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
20 info attempt registry request try #2 at 12:59:29 PM
21 http request GET https://registry.npmjs.org/underscore
22 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
23 info attempt registry request try #3 at 1:00:30 PM
24 http request GET https://registry.npmjs.org/underscore
25 silly fetchPackageMetaData Error: self signed certificate in certificate chain
25 silly fetchPackageMetaData     at Error (native)
25 silly fetchPackageMetaData     at TLSSocket.<anonymous> (_tls_wrap.js:1062:38)
25 silly fetchPackageMetaData     at emitNone (events.js:86:13)
25 silly fetchPackageMetaData     at TLSSocket.emit (events.js:185:7)
25 silly fetchPackageMetaData     at TLSSocket._finishInit (_tls_wrap.js:586:8)
25 silly fetchPackageMetaData     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38)
25 silly fetchPackageMetaData  error for underscore { Error: self signed certificate in certificate chain
25 silly fetchPackageMetaData     at Error (native)
25 silly fetchPackageMetaData     at TLSSocket.<anonymous> (_tls_wrap.js:1062:38)
25 silly fetchPackageMetaData     at emitNone (events.js:86:13)
25 silly fetchPackageMetaData     at TLSSocket.emit (events.js:185:7)
25 silly fetchPackageMetaData     at TLSSocket._finishInit (_tls_wrap.js:586:8)
25 silly fetchPackageMetaData     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38) code: 'SELF_SIGNED_CERT_IN_CHAIN' }
26 silly rollbackFailedOptional Starting
27 silly rollbackFailedOptional Finishing
28 silly runTopLevelLifecycles Finishing
29 silly install printInstalled
30 verbose stack Error: self signed certificate in certificate chain
30 verbose stack     at Error (native)
30 verbose stack     at TLSSocket.<anonymous> (_tls_wrap.js:1062:38)
30 verbose stack     at emitNone (events.js:86:13)
30 verbose stack     at TLSSocket.emit (events.js:185:7)
30 verbose stack     at TLSSocket._finishInit (_tls_wrap.js:586:8)
30 verbose stack     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38)
31 verbose cwd /usr/local/bin
32 error Darwin 15.6.0
33 error argv "/usr/local/Cellar/node/6.8.1/bin/node" "/usr/local/bin/npm" "install" "underscore"
34 error node v6.8.1
35 error npm  v3.10.8
36 error code SELF_SIGNED_CERT_IN_CHAIN
37 error self signed certificate in certificate chain
38 error If you need help, you may report this error at:
38 error     <https://github.com/npm/npm/issues>
39 verbose exit [ 1, true ]

**Comment by adalvi-carecloud** [comment]
I have installed the node via HomeBrew and now I want to install "underscore" ,  I am using the command "npm install underscore"   Here is the version of node and npm on my mac

MacBook-Pro:~ Ajay$ npm -v
3.10.8

MacBook-Pro:~ Ajay$ node -v
v6.8.1

**Comment by adalvi-carecloud** [comment]
Run this command to set http proxy and That is it!!!

npm config set proxy 

npm config set https-proxy
