### ISSUE TITLE
npm error ?  rror while loading shared libraries:libgconf-2.so.4 : cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by geeflaxx** [npm/npm#14391]
#### I'm opening this issue because:
- [ ] npm is crashing.
- [ x] npm is producing an incorrect install.
- [ ] npm is doing something I don't understand.
- [ ] Other (_see below for feature requests_):
#### What's going wrong?

i want build a smart mirror so i install npm in the folder MagicMirror 
and if i want to start them i get the fault that a data is missing 
#### How can the CLI team reproduce the problem?

maybe told me what i did wrong..

which library should i download now ?
i have many screen’s and i hope you can help me :/
(i used the multiupload picload.org)
https://pl.vc/nlwkl
https://pl.vc/6jqck
https://pl.vc/1lpl8h
https://pl.vc/sesey

thats my npm-debug.log

<details><pre>
0 info it worked if it ends with ok
1 verbose cli [ ‘/usr/local/bin/node’, ‘/usr/local/bin/npm’, ‘start’ ]
2 info using npm@3.10.9
3 info using node@v6.8.1
4 verbose run-script [ ‘prestart’, ‘start’, ‘poststart’ ]
5 info lifecycle magicmirror@2.0.0~prestart: magicmirror@2.0.0
6 silly lifecycle magicmirror@2.0.0~prestart: no script for prestart, continuing
7 info lifecycle magicmirror@2.0.0~start: magicmirror@2.0.0
8 verbose lifecycle magicmirror@2.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle magicmirror@2.0.0~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/home/pi/MagicMirror/node_modules/.b$
10 verbose lifecycle magicmirror@2.0.0~start: CWD: /home/pi/MagicMirror
11 silly lifecycle magicmirror@2.0.0~start: Args: [ ‘-c’, ‘electron js/electron.js’ ]
12 info lifecycle magicmirror@2.0.0~start: Failed to exec start script
13 verbose stack Error: magicmirror@2.0.0 start: electron js/electron.js
13 verbose stack spawn ENOENT
13 verbose stack at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:33:16)
13 verbose stack at emitTwo (events.js:106:13)
13 verbose stack at ChildProcess.emit (events.js:191:7)
13 verbose stack at maybeClose (internal/child_process.js:877:16)
13 verbose stack at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
14 verbose pkgid magicmirror@2.0.0
15 verbose cwd /home/pi/MagicMirror
16 error Linux 4.4.21-v7+
17 error argv “/usr/local/bin/node” “/usr/local/bin/npm” "start"
18 error node v6.8.1
19 error npm v3.10.9
20 error file sh
21 error code ELIFECYCLE
22 error errno ENOENT
23 error syscall spawn
24 error magicmirror@2.0.0 start: electron js/electron.js
24 error spawn ENOENT
25 error Failed at the magicmirror@2.0.0 start script ‘electron js/electron.js’.
25 error Make sure you have the latest version of node.js and npm installed.
25 error If you do, this is most likely a problem with the magicmirror package,
25 error not with npm itself.
25 error Tell the author that this fails on your system:
25 error electron js/electron.js
25 error You can get information on how to open an issue for this project with:
25 error npm bugs magicmirror
25 error Or if that isn’t available, you can get their info via:
25 error npm owner ls magicmirror
25 error There is likely additional logging output above.
26 verbose exit [ 1, true ]
</pre></details>

i get the error if i start npm:

```
npm start

magicmirror@2.0.0 start /home/pi/MagicMirror
electron js/electron.js

/home/pi/MagicMirror/node_modules/electron-prebuilt/dist/electron: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory

npm ERR! Linux 4.4.21-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.8.1
npm ERR! npm  v3.10.9
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! magicmirror@2.0.0 start: `electron js/electron.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the magicmirror@2.0.0 start script 'electron js/electron.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the magicmirror package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron js/electron.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs magicmirror
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls magicmirror
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/MagicMirror/npm-debug.log
```

maybe i don't have the access to install any thing cause the node_modules isn't for pi ?

```console
pi@raspberrypi:~/MagicMirror $ ls -l
total 92
-rw-r--r--   1 pi pi    3929 Oct 21 13:30 CHANGELOG.md
drwxr-xr-x   2 pi pi    4096 Oct 23 12:24 config
drwxr-xr-x   2 pi pi    4096 Oct 21 13:30 css
drwxr-xr-x  20 pi pi    4096 Oct 21 13:30 fonts
-rw-r--r--   1 pi pi    1808 Oct 21 13:30 Gruntfile.js
-rw-r--r--   1 pi pi    2266 Oct 21 13:30 index.html
drwxr-xr-x   2 pi pi    4096 Oct 21 13:30 installers
drwxr-xr-x   2 pi pi    4096 Oct 21 13:30 js
-rw-r--r--   1 pi pi    1113 Oct 21 13:30 LICENSE.md
drwxr-xr-x   4 pi pi    4096 Oct 21 13:30 modules
drwxr-xr-x 519 pi root 20480 Oct 23 12:15 node_modules
-rw-r--r--   1 pi pi    2491 Oct 23 18:38 npm-debug.log
-rw-r--r--   1 pi pi    1374 Oct 21 13:30 package.json
-rw-r--r--   1 pi pi    8513 Oct 21 13:30 README.md
drwxr-xr-x   2 pi pi    4096 Oct 21 13:30 serveronly
drwxr-xr-x   2 pi pi    4096 Oct 21 13:30 translations
drwxr-xr-x   5 pi pi    4096 Oct 21 13:30 vendor
```

### supporting information:
- `npm -v` prints:3.10.9
- `node -v` prints:6.8.1
- `npm config get registry` 
  "prints:pi@raspberrypi:~/MagicMirror $ npm config get registry
  https://registry.npmjs.org/"
- Windows, OS X/macOS, or Linux?: Raspberry-Pi
- Network issues:
  - Geographic location where npm was run:
  - [ ] I use a proxy to connect to the npm registry.
  - [ ] I use a proxy to connect to the web.
  - [ ] I use a proxy when downloading Git repos.
  - [ ] I access the npm registry via a VPN
  - [ ] I don't use a proxy, but have limited or unreliable internet access.
- Container:
  - [ ] I develop using Vagrant on Windows.
  - [ ] I develop using Vagrant on OS X or Linux.
  - [ ] I develop / deploy using Docker.
  - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by geeflaxx** [comment]
i haven’t the error after i use
’‘sudo apt-get install libxss1 lsof’

but now i have a new one, the same error but with the code that “libgconf-2.so.4” is missing

maybe i haven't the electron-prebuilt's ?
