### ISSUE TITLE
NPM constantly errors

### ISSUE THREAD

**Issue by jeroenouw** [npm/npm#14398]
#### I'm opening this issue because:

Lately I get a lot of errors while doing NPM commands, I don't know how to fix. Probably some small thing.

#### What's going wrong?

I get this error with commands as: **npm install**, **npm run build**, **npm run start-webpack-server etc.**

It also says this in the errors:
23 error If you do, this is most likely a problem with the xxx,
23 error not with npm itself.

But I think it is NPM itself because all these projects does work online at other people, so the project are fine. 

#### How can the CLI team reproduce the problem?

npm_debug_log:

<detail>
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Eigenaar\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@3.10.9
3 info using node@v4.6.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle first-webapp-react@1.0.0~prebuild: first-webapp-react@1.0.0
6 silly lifecycle first-webapp-react@1.0.0~prebuild: no script for prebuild, continuing
7 info lifecycle first-webapp-react@1.0.0~build: first-webapp-react@1.0.0
8 verbose lifecycle first-webapp-react@1.0.0~build: unsafe-perm in lifecycle true
9 verbose lifecycle first-webapp-react@1.0.0~build: PATH: C:\Users\Eigenaar\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\GithubProjecten\ReactLocationApp\node_modules\.bin;C:\Users\Eigenaar\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\Eigenaar\bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\AMD APP\bin\x86_64;C:\Program Files (x86)\AMD APP\bin\x86;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files (x86)\Common Files\Acronis\SnapAPI;C:\Program Files\Microsoft SQL Server\110\Tools\Binn;C:\Program Files (x86)\Java\jdk1.7.0_40\bin;C:\Program Files (x86)\nodejs\bin;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn;C:\Program Files\Microsoft SQL Server\110\DTS\Binn;C:\xampp\php;C:\ProgramData\ComposerSetup\bin;C:\HashiCorp\Vagrant\bin;C:\Program Files (x86)\Git\cmd;C:\Program Files (x86)\OpenVPN\bin;C:\Program Files (x86)\Skype\Phone;C:\Program Files\Git\cmd;C:\Program Files\nodejs;C:\xampp\php;C:\Users\Eigenaar\AppData\Local\Microsoft\WindowsApps;C:\Users\Eigenaar\AppData\Roaming\npm;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
10 verbose lifecycle first-webapp-react@1.0.0~build: CWD: C:\GithubProjecten\ReactLocationApp
11 silly lifecycle first-webapp-react@1.0.0~build: Args: [ '/d /s /c',
11 silly lifecycle   'NODE_ENV=production browserify -t [ reactify --es6 ] main.js | uglifyjs > compiled.js' ]
12 silly lifecycle first-webapp-react@1.0.0~build: Returned: code: 255  signal: null
13 info lifecycle first-webapp-react@1.0.0~build: Failed to exec build script
14 verbose stack Error: first-webapp-react@1.0.0 build: `NODE_ENV=production browserify -t [ reactify --es6 ] main.js | uglifyjs > compiled.js`
14 verbose stack Exit status 255
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\Eigenaar\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\Eigenaar\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:829:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid first-webapp-react@1.0.0
16 verbose cwd C:\GithubProjecten\ReactLocationApp
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Eigenaar\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
19 error node v4.6.1
20 error npm  v3.10.9
21 error code ELIFECYCLE
22 error first-webapp-react@1.0.0 build: `NODE_ENV=production browserify -t [ reactify --es6 ] main.js | uglifyjs > compiled.js`
22 error Exit status 255
23 error Failed at the first-webapp-react@1.0.0 build script 'NODE_ENV=production browserify -t [ reactify --es6 ] main.js | uglifyjs > compiled.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the first-webapp-react package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     NODE_ENV=production browserify -t [ reactify --es6 ] main.js | uglifyjs > compiled.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs first-webapp-react
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls first-webapp-react
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
</detail>

Please solution someone.

#### Supporting information

npm -v : 3.10.9
node -v: v4.6.1

**Comment by legodude17** [comment]
According to the log output, the error is that `NODE_ENV=production browserify -t [ reactify --es6 ] main.js | uglifyjs > compiled.js` is failing on you system. Run that command on its own and post the output if it fails.

**Comment by iarna** [comment]
Your problem is that you're on windows and the syntax of the command you're running:

```
NODE_ENV=production browserify -t [ reactify --es6 ] main.js | uglifyjs > compiled.js
```
Doesn't work on Windows. Specifically, you can't prefix commands with environment variables like that.

Instead, try:
```
set NODE_ENV=production && browserify -t [ reactify --es6 ] main.js | uglifyjs > compiled.js
```

Or if this project needs to work with both Windows and Linux/Mac, use [`cross-env`](https://www.npmjs.com/package/cross-env). Doing that after you've `npm install --save-dev cross-env` would look like:

```
cross-env NODE_ENV=production browserify -t [ reactify --es6 ] main.js | uglifyjs > compiled.js
```

**Comment by jeroenouw** [comment]
Thanks!
