### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by unixph** [npm/npm#14407]
I got this error when installing cloud commander. I have installed the latest version of node.js and downloaded cloud commander tar ball. Can anyone help with this issue?

[hadoop@xxxxxxxx bin]$ npm install
npm ERR! Linux 2.6.32-504.el6.x86_64
npm ERR! argv "/home/hadoop/node-v4.6.1-linux-x64/bin/node" "/home/hadoop/node/bin/npm" "install"
npm ERR! node v4.6.1
npm ERR! npm  v2.15.9
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! syscall connect

npm ERR! network connect ETIMEDOUT 151.101.8.162:443
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     /home/hadoop/cloudcmd-v5.6.2/bin/npm-debug.log

**Comment by watilde** [comment]
Hello! You seem to be using the old version of npm. Could you please try this to use the latest version?
> Try the latest stable version of npm: https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm

**Comment by snopeks** [comment]
@unixph hello there, can you confirm that you have network access? If you do, it looks like you need to set up your proxy.

**Comment by unixph** [comment]
This is my npm version @watilde 
$ npm -v
2.15.9

**Comment by unixph** [comment]
$ cloudcmd
module.js:327
    throw err;
    ^

Error: Cannot find module 'shortdate'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/hadoop/node-v4.6.1-linux-x64/lib/node_modules/cloudcmd/node_modules/readify/lib/readify.js:9:23)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

**Comment by watilde** [comment]
@unixph The latest stable version is `v3.10.9`. Can you try to update it via [docs](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm)?

**Comment by unixph** [comment]
will check on it @watilde and update here. :)

**Comment by unixph** [comment]
still unable to run it.

module.js:327
    throw err;
    ^

Error: Cannot find module 'shortdate'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/app/tools/node-v4.6.0-linux-x64/lib/node_modules/cloudcmd/node_modules/readify/legacy/lib/readify.js:6:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

The version I've installed should be working, cos one of our servers, it's working fine. Just not in my box.

**Comment by legodude17** [comment]
What are you trying to do? Try running `npm install`.

**Comment by unixph** [comment]
I'm trying to install cloud commander. http://cloudcmd.io/
Installing it using binary files. 
- node node-v4.6.0-linux-x64.tar.xz
- cloudcmd-v5.7.2.tar.gz
Couldn't make it run on the server.

**Comment by legodude17** [comment]
It doesn't appear that you are using `npm`. Can you please explain why you filed this here?

**Comment by haopj** [comment]
Hello,can you help me?I met the same problem with you,thank you!

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "less"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8

npm ERR! Invalid protocol: null
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\haopengjie\npm-debug.log

**Comment by legodude17** [comment]
@haopj, that is a different issue, please open a new one. But first, try updating `npm` to the latest version (`npm install -g npm@latest`).
