### ISSUE TITLE
ionic start aplikasiku blank -- cannot find module 'colors'

### ISSUE THREAD

**Issue by titiknf** [npm/npm#14419]
```
E:\aplikasiku>ionic start aplikasiku blank
Caught exception:
 Error: Cannot find module 'colors'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\AEON\AppData\Roaming\npm\node_modules\ionic\lib\cli.js:1:63)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

**Comment by legodude17** [comment]
What makes you think this is an issue with `npm`? It looks like an issue with `ionic`.

**Comment by titiknf** [comment]
oh, the issue is in ionic, so firstly repair the ionic? and, what's the problem with ionic?i don't understand

**Comment by legodude17** [comment]
I don't know ionic, but this would be either an incorrect install of `ionic-cli`, or of you project. Does `ionic-cli` depend on `colors`?
