### ISSUE TITLE
Error: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:8888

### ISSUE THREAD

**Issue by cdarlens** [npm/npm#14459]
When I'm executing the following command: npm install -g bower

I have this error

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files\nodejs\node.exe',
1 verbose cli   'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'bower' ]
2 info using npm@3.10.8
3 info using node@v6.9.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData bower
8 silly fetchNamedPackageData bower
9 silly mapToRegistry name bower
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'bower',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'bower',
12 silly mapToRegistry   name: 'bower',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/bower
14 verbose request uri https://registry.npmjs.org/bower
15 verbose request no auth needed
16 info attempt registry request try #1 at 3:07:15 PM
17 verbose request id 40b91c4a0d4b5cf2
18 http request GET https://registry.npmjs.org/bower
19 info retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:8888
20 info attempt registry request try #2 at 3:07:26 PM
21 http request GET https://registry.npmjs.org/bower
22 info retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:8888
23 info attempt registry request try #3 at 3:08:27 PM
24 http request GET https://registry.npmjs.org/bower
25 silly fetchPackageMetaData Error: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:8888
25 silly fetchPackageMetaData     at ClientRequest.onError (C:\Program Files\nodejs\node_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:176:17)
25 silly fetchPackageMetaData     at ClientRequest.g (events.js:291:16)
25 silly fetchPackageMetaData     at emitOne (events.js:96:13)
25 silly fetchPackageMetaData     at ClientRequest.emit (events.js:188:7)
25 silly fetchPackageMetaData     at Socket.socketErrorListener (_http_client.js:310:9)
25 silly fetchPackageMetaData     at emitOne (events.js:96:13)
25 silly fetchPackageMetaData     at Socket.emit (events.js:188:7)
25 silly fetchPackageMetaData     at emitErrorNT (net.js:1276:8)
25 silly fetchPackageMetaData     at _combinedTickCallback (internal/process/next_tick.js:74:11)
25 silly fetchPackageMetaData     at process._tickCallback (internal/process/next_tick.js:98:9)
25 silly fetchPackageMetaData  error for bower { Error: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:8888
25 silly fetchPackageMetaData     at ClientRequest.onError (C:\Program Files\nodejs\node_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:176:17)
25 silly fetchPackageMetaData     at ClientRequest.g (events.js:291:16)
25 silly fetchPackageMetaData     at emitOne (events.js:96:13)
25 silly fetchPackageMetaData     at ClientRequest.emit (events.js:188:7)
25 silly fetchPackageMetaData     at Socket.socketErrorListener (_http_client.js:310:9)
25 silly fetchPackageMetaData     at emitOne (events.js:96:13)
25 silly fetchPackageMetaData     at Socket.emit (events.js:188:7)
25 silly fetchPackageMetaData     at emitErrorNT (net.js:1276:8)
25 silly fetchPackageMetaData     at _combinedTickCallback (internal/process/next_tick.js:74:11)
25 silly fetchPackageMetaData     at process._tickCallback (internal/process/next_tick.js:98:9) code: 'ECONNRESET' }
26 silly rollbackFailedOptional Starting
27 silly rollbackFailedOptional Finishing
28 silly runTopLevelLifecycles Finishing
29 silly install printInstalled
30 verbose stack Error: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:8888
30 verbose stack     at ClientRequest.onError (C:\Program Files\nodejs\node_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:176:17)
30 verbose stack     at ClientRequest.g (events.js:291:16)
30 verbose stack     at emitOne (events.js:96:13)
30 verbose stack     at ClientRequest.emit (events.js:188:7)
30 verbose stack     at Socket.socketErrorListener (_http_client.js:310:9)
30 verbose stack     at emitOne (events.js:96:13)
30 verbose stack     at Socket.emit (events.js:188:7)
30 verbose stack     at emitErrorNT (net.js:1276:8)
30 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:74:11)
30 verbose stack     at process._tickCallback (internal/process/next_tick.js:98:9)
31 verbose cwd C:\Users\Carl
32 error Windows_NT 6.1.7601
33 error argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "bower"
34 error node v6.9.1
35 error npm  v3.10.8
36 error code ECONNRESET
37 error network tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:8888
38 error network This is most likely not a problem with npm itself
38 error network and is related to network connectivity.
38 error network In most cases you are behind a proxy or have bad network settings.
38 error network
38 error network If you are behind a proxy, please make sure that the
38 error network 'proxy' config is set properly.  See: 'npm help config'
39 verbose exit [ 1, true ]
```

**Comment by legodude17** [comment]
Do you have a proxy? Is your internet connection spotty?

**Comment by cdarlens** [comment]
Thanks for you respond. I have fiddler but I turned it off.

**Comment by legodude17** [comment]
How is your internet connection? Try going to [speedtest.net](http://www.speedtest.net).

**Comment by cdarlens** [comment]
Dowload speed : 86.65 Mbps
Upload speed 33,75 Mpbs

**Comment by cdarlens** [comment]
My colleague has same connection and his working for him

**Comment by legodude17** [comment]
What are the differences between your connection and your colleague?

**Comment by cdarlens** [comment]
Same comnection same office

**Comment by legodude17** [comment]
What is the result of `npm config get prefix`?

**Comment by rkeshmir** [comment]
It is :
C:\Users\Reza\AppData\Roaming\npm

**Comment by legodude17** [comment]
And what is `npm config get registry`?

**Comment by cdarlens** [comment]
https://registry.npmjs.org/

**Comment by legodude17** [comment]
Really? Because the error message says it is trying to connect to
127.0.0.1:8888. That would be very odd if your registry isn't that URL.

**Comment by cdarlens** [comment]
Hi thanks four time btw.

I tried the following commands 

>npm config set proxy null
>npm config set https-proxy null

npm config set registry=http://registry.npmjs.org/
npm config set strict-ssl false

**And now the error message look like this** 

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "bower"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ECONNREFUSED
npm ERR! errno ECONNREFUSED
npm ERR! syscall connect

npm ERR! Error: connect ECONNREFUSED 127.0.0.1:8888
npm ERR!     at Object.exports._errnoException (util.js:1026:11)
npm ERR!     at exports._exceptionWithHostPort (util.js:1049:20)
npm ERR!     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1085:14)
npm ERR!  { Error: connect ECONNREFUSED 127.0.0.1:8888
npm ERR!     at Object.exports._errnoException (util.js:1026:11)
npm ERR!     at exports._exceptionWithHostPort (util.js:1049:20)
npm ERR!     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1085:14)
npm ERR!   code: 'ECONNREFUSED',
npm ERR!   errno: 'ECONNREFUSED',
npm ERR!   syscall: 'connect',
npm ERR!   address: '127.0.0.1',
npm ERR!   port: 8888 }
npm ERR!
npm ERR! If you are behind a proxy, please make sure that the
npm ERR! 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     C:\wamp\www\local.fuse.com\npm-debug.log

**Comment by legodude17** [comment]
Do you have a proxy or a VPN? Try `npm config set registry https://registry.npmjs.org`.

**Comment by xqiu** [comment]
https://stackoverflow.com/questions/18419144/npm-not-working-read-econnreset 's following solution solved my probleml
npm config get proxy
npm config rm proxy

**Comment by lolisTop** [comment]
没错 刚刚解决 只要把代理那个删除就行了 感谢 @xqiu
