### ISSUE TITLE
Getting error while npm start

### ISSUE THREAD

**Issue by ovaiskhan11** [npm/npm#14474]
#### I'm opening this issue because:

  - [ ] npm is doing something I don't understand.

#### What's going wrong?
I am getting error when I ran command npm start.
I have node version v6.9.1 and npm version 3.10.8

Below are the path variables for my system: User variables PATH: C:\Users\Abdul Ovais\AppData\Roaming\npm System variables Path: C:\Program Files\nodejs\

Below are the error lines:

```
Abdul Ovais@DESKTOP-31UBAGF /xampp/htdocs/ees-angular-client
$ npm start

> EES@1.0.0 start D:\xampp\htdocs\ees-angular-client
> npm run server:dev


> EES@1.0.0 server:dev D:\xampp\htdocs\ees-angular-client
> webpack-dev-server --config config/webpack.dev.js --progress --profile --watch --content-base src/

Error: Cannot find module './system/supports-colors'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\xampp\htdocs\ees-angular-client\node_modules\awesome-typescript-loader\node_modules\colors\lib\colors.js:39:24)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\xampp\htdocs\ees-angular-client\node_modules\awesome-typescript-loader\node_modules\colors\safe.js:8:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\xampp\htdocs\ees-angular-client\node_modules\awesome-typescript-loader\src\instance.ts:9:14)
    at Module._compile (module.js:570:32)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "server:dev"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! EES@1.0.0 server:dev: `webpack-dev-server --config config/webpack.dev.js --progress --profile --watch --content-base src/`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the EES@1.0.0 server:dev script 'webpack-dev-server --config config/webpack.dev.js --progress --profile --watch --content-base src/'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the EES package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --config config/webpack.dev.js --progress --profile --watch --content-base src/
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs EES
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls EES
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\xampp\htdocs\ees-angular-client\npm-debug.log

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! EES@1.0.0 start: `npm run server:dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the EES@1.0.0 start script 'npm run server:dev'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the EES package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run server:dev
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs EES
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls EES
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\xampp\htdocs\ees-angular-client\npm-debug.log
```

#### How can the CLI team reproduce the problem?
I have implemented this template which is made in angualr2
http://demo.flatlogic.com/sing-wrapbootstrap-3.3.0/angular/#/app/dashboard

I have just zip it and run npm install which showed me this:

```
+-- UNMET PEER DEPENDENCY @angular/common@2.0.0
+-- UNMET PEER DEPENDENCY @angular/compiler@2.0.0
+-- UNMET PEER DEPENDENCY @angular/core@2.0.0
+-- UNMET PEER DEPENDENCY @angular/forms@2.0.0
`-- debug-log@1.0.1

npm WARN enoent ENOENT: no such file or directory, open 'D:\xampp\htdocs\ees-angular-client\node_modules\material-design-lite\package.json'
npm WARN @angular/core@2.0.0-rc.4 requires a peer of rxjs@5.0.0-beta.6 but none was installed.
npm WARN ng2-select2@0.5.1 requires a peer of @angular/common@2.0.1 but none was installed.
npm WARN ng2-select2@0.5.1 requires a peer of @angular/compiler@2.0.1 but none was installed.
npm WARN ng2-select2@0.5.1 requires a peer of @angular/core@2.0.1 but none was installed.
npm WARN ng2-table@1.1.0 requires a peer of @angular/common@2.0.0-rc.6 but none was installed.
npm WARN ng2-table@1.1.0 requires a peer of @angular/compiler@2.0.0-rc.6 but none was installed.
npm WARN ng2-table@1.1.0 requires a peer of @angular/core@2.0.0-rc.6 but none was installed.
npm WARN ng2-table@1.1.0 requires a peer of @angular/forms@2.0.0-rc.6 but none was installed.
npm WARN EES@1.0.0 No repository field.
npm WARN EES@1.0.0 No license field.
```

but when i ran command npm start, it showed me above top error.

This is the npm-debg.log file
https://gist.github.com/ovaiskhan11/cda73691e732b7898a51e1e7cd7bd818

Please help me out!

**Comment by legodude17** [comment]
The error in the issue and the one in the gist are different. Which one is the error you got?
