### ISSUE TITLE
npm node keystone error

### ISSUE THREAD

**Issue by jeroenouw** [npm/npm#14473]
#### I'm opening this issue because:

  - [ ] npm is doing something I don't understand.

#### What's going wrong?

First it says it cannot find a module but is installed correctly i thought. Second it says Mongo error, hadnt have problems with Mongo before

```
Eigenaar@Hp MINGW64 /c/GithubProjecten/KeystoneJS (master)
$ node keystone
{ Error: Cannot find module '../build/Release/bson'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\GithubProjecten\KeystoneJS\node_modules\bson\ext\i
ndex.js:15:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\GithubProjecten\KeystoneJS\node_modules\bson\lib\b
son\index.js:3:24)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32) code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
------------------------------------------------
Mongo Error:

Error: failed to connect to [localhost:27017]
    at .<anonymous> (C:\GithubProjecten\KeystoneJS\node_modules\mongodb\lib\mong
odb\connection\server.js:556:25)
    at emitThree (events.js:116:13)
    at emit (events.js:194:7)
    at .<anonymous> (C:\GithubProjecten\KeystoneJS\node_modules\mongodb\lib\mong
odb\connection\connection_pool.js:156:15)
    at emitTwo (events.js:106:13)
    at emit (events.js:191:7)
    at Socket.<anonymous> (C:\GithubProjecten\KeystoneJS\node_modules\mongodb\li
b\mongodb\connection\connection.js:534:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1276:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
C:\GithubProjecten\KeystoneJS\node_modules\keystone\lib\core\mount.js:630
                        throw new Error('KeystoneJS (' + keystone.get('name') +
') failed to start');
                        ^

Error: KeystoneJS (KeystoneJS) failed to start
    at NativeConnection.<anonymous> (C:\GithubProjecten\KeystoneJS\node_modules\
keystone\lib\core\mount.js:630:10)
    at emitOne (events.js:96:13)
    at NativeConnection.emit (events.js:188:7)
    at NativeConnection.Connection.error (C:\GithubProjecten\KeystoneJS\node_mod
ules\mongoose\lib\connection.js:389:8)
    at C:\GithubProjecten\KeystoneJS\node_modules\mongoose\lib\connection.js:416
:14
    at C:\GithubProjecten\KeystoneJS\node_modules\mongoose\lib\drivers\node-mong
odb-native\connection.js:57:21
    at C:\GithubProjecten\KeystoneJS\node_modules\mongodb\lib\mongodb\db.js:286:
18
    at C:\GithubProjecten\KeystoneJS\node_modules\mongodb\lib\mongodb\db.js:365:
7
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

```

#### How can the CLI team reproduce the problem?

After installing KeystoneJS correctly I did this command:
`node keystone`
This failed. 

### supporting information:
- `npm -v` prints: 3.10.9
- `node -v` prints: v6.9.1
- `npm config get registry` prints: https://registry.npmjs.org/
- Windows, OS X/macOS, or Linux?: Windows 10

**Comment by jeroenouw** [comment]
Mongo reinstalled solved the issue
