### ISSUE TITLE
npm install bundle issue

### ISSUE THREAD

**Issue by AhmadZafar** [npm/npm#14483]
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'npm-install-all',
1 verbose cli   'main.js' ]
2 info using npm@3.10.8
3 info using node@v6.9.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData npm-install-all
8 silly fetchPackageMetaData main.js
9 silly fetchNamedPackageData npm-install-all
10 silly mapToRegistry name npm-install-all
11 silly mapToRegistry using default registry
12 silly mapToRegistry registry https://registry.npmjs.org/
13 silly mapToRegistry data Result {
13 silly mapToRegistry   raw: 'npm-install-all',
13 silly mapToRegistry   scope: null,
13 silly mapToRegistry   escapedName: 'npm-install-all',
13 silly mapToRegistry   name: 'npm-install-all',
13 silly mapToRegistry   rawSpec: '',
13 silly mapToRegistry   spec: 'latest',
13 silly mapToRegistry   type: 'tag' }
14 silly mapToRegistry uri https://registry.npmjs.org/npm-install-all
15 silly fetchOtherPackageData main.js
16 silly cache add args [ 'main.js', null ]
17 verbose cache add spec main.js
18 silly cache add parsed spec Result {
18 silly cache add   raw: 'main.js',
18 silly cache add   scope: null,
18 silly cache add   escapedName: 'main.js',
18 silly cache add   name: null,
18 silly cache add   rawSpec: 'main.js',
18 silly cache add   spec: 'C:\\temp1\\main.js',
18 silly cache add   type: 'local' }
19 silly addLocalTarball shasum (computed) a47e59c2310aa1064246b6f03f7511271a140652
20 verbose addTmpTarball C:\temp1\main.js not in flight; adding
21 verbose correctMkdir C:\Users\azafar\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
22 verbose request uri https://registry.npmjs.org/npm-install-all
23 verbose request no auth needed
24 info attempt registry request try #1 at 1:42:14 PM
25 verbose request id 10328a63c28b6cf5
26 verbose etag "6NNT6S91JXGTLPN83WMQ6ANNM"
27 http request GET https://registry.npmjs.org/npm-install-all
28 verbose addTmpTarball validating metadata from C:\temp1\main.js
29 verbose tar unpack C:\temp1\main.js
30 verbose tar unpacking to C:\Users\azafar\AppData\Local\Temp, C:\Program Files\SlikSvn\bin\npm-1536-7010f4db\unpack-adc72ced
31 silly gentlyRm C:\Users\azafar\AppData\Local\Temp, C:\Program Files\SlikSvn\bin\npm-1536-7010f4db\unpack-adc72ced is being purged
32 verbose gentlyRm don't care about contents; nuking C:\Users\azafar\AppData\Local\Temp, C:\Program Files\SlikSvn\bin\npm-1536-7010f4db\unpack-adc72ced
33 silly gunzTarPerm modes [ '777', '666' ]
34 http 304 https://registry.npmjs.org/npm-install-all
35 verbose headers { date: 'Tue, 01 Nov 2016 08:42:15 GMT',
35 verbose headers   via: '1.1 varnish',
35 verbose headers   'cache-control': 'max-age=300',
35 verbose headers   etag: '"6NNT6S91JXGTLPN83WMQ6ANNM"',
35 verbose headers   age: '0',
35 verbose headers   connection: 'keep-alive',
35 verbose headers   'x-served-by': 'cache-lcy1147-LCY',
35 verbose headers   'x-cache': 'MISS',
35 verbose headers   'x-cache-hits': '0',
35 verbose headers   'x-timer': 'S1477989735.425014,VS0,VE104',
35 verbose headers   vary: 'Accept-Encoding' }
36 silly get cb [ 304,
36 silly get   { date: 'Tue, 01 Nov 2016 08:42:15 GMT',
36 silly get     via: '1.1 varnish',
36 silly get     'cache-control': 'max-age=300',
36 silly get     etag: '"6NNT6S91JXGTLPN83WMQ6ANNM"',
36 silly get     age: '0',
36 silly get     connection: 'keep-alive',
36 silly get     'x-served-by': 'cache-lcy1147-LCY',
36 silly get     'x-cache': 'MISS',
36 silly get     'x-cache-hits': '0',
36 silly get     'x-timer': 'S1477989735.425014,VS0,VE104',
36 silly get     vary: 'Accept-Encoding' } ]
37 verbose etag https://registry.npmjs.org/npm-install-all from cache
38 verbose get saving npm-install-all to C:\Users\azafar\AppData\Roaming\npm-cache\registry.npmjs.org\npm-install-all\.cache.json
39 verbose correctMkdir C:\Users\azafar\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
40 verbose stack Error: kill ENOSYS
40 verbose stack     at exports._errnoException (util.js:1026:11)
40 verbose stack     at process.kill (internal/process.js:172:13)
40 verbose stack     at process.listener (C:\Program Files\nodejs\node_modules\npm\node_modules\npmlog\node_modules\gauge\node_modules\signal-exit\index.js:86:15)
40 verbose stack     at emitNone (events.js:91:20)
40 verbose stack     at process.emit (events.js:185:7)
40 verbose stack     at processEmit (C:\Program Files\nodejs\node_modules\npm\node_modules\npmlog\node_modules\gauge\node_modules\signal-exit\index.js:146:32)
40 verbose stack     at processEmit (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\node_modules\npmlog\node_modules\gauge\node_modules\signal-exit\index.js:146:32)
40 verbose stack     at Signal.wrap.onsignal (internal/process.js:199:44)
41 verbose cwd C:\temp1
42 error Windows_NT 6.1.7601
43 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "npm-install-all" "main.js"
44 error node v6.9.1
45 error npm  v3.10.8
46 error code ENOSYS
47 error errno ENOSYS
48 error syscall kill
49 error kill ENOSYS
50 error If you need help, you may report this error at:
50 error     <https://github.com/npm/npm/issues>
51 verbose exit [ 1, true ]
```

**Comment by legodude17** [comment]
What command did you run?

**Comment by iarna** [comment]
@legodude17 They ran: `npm install npm-install-all main.js`

**Comment by legodude17** [comment]
I thought that ENOSYS occurs when the user forces `npm` to  quit. Is that what happened?
