### ISSUE TITLE
no install gulp (Windows 8)

### ISSUE THREAD

**Issue by adgranados** [npm/npm#14499]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\user\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '--save-dev',
1 verbose cli   'gulp' ]
2 info using npm@3.10.6
3 info using node@v6.3.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData gulp
8 silly fetchNamedPackageData gulp
9 silly mapToRegistry name gulp
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'gulp',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'gulp',
12 silly mapToRegistry   name: 'gulp',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/gulp
14 verbose request uri https://registry.npmjs.org/gulp
15 verbose request no auth needed
16 info attempt registry request try #1 at 16:18:51
17 verbose request id bce50a2ce92a377f
18 verbose etag "908UXB3AB9M61217ZL94N66F1"
19 http request GET https://registry.npmjs.org/gulp
20 http 304 https://registry.npmjs.org/gulp
21 verbose headers { date: 'Wed, 02 Nov 2016 21:21:15 GMT',
21 verbose headers   via: '1.1 varnish',
21 verbose headers   'cache-control': 'max-age=300',
21 verbose headers   etag: '"908UXB3AB9M61217ZL94N66F1"',
21 verbose headers   age: '113',
21 verbose headers   connection: 'keep-alive',
21 verbose headers   'x-served-by': 'cache-iad2137-IAD',
21 verbose headers   'x-cache': 'HIT',
21 verbose headers   'x-cache-hits': '3',
21 verbose headers   'x-timer': 'S1478121675.852646,VS0,VE0',
21 verbose headers   vary: 'Accept-Encoding' }
22 silly get cb [ 304,
22 silly get   { date: 'Wed, 02 Nov 2016 21:21:15 GMT',
22 silly get     via: '1.1 varnish',
22 silly get     'cache-control': 'max-age=300',
22 silly get     etag: '"908UXB3AB9M61217ZL94N66F1"',
22 silly get     age: '113',
22 silly get     connection: 'keep-alive',
22 silly get     'x-served-by': 'cache-iad2137-IAD',
22 silly get     'x-cache': 'HIT',
22 silly get     'x-cache-hits': '3',
22 silly get     'x-timer': 'S1478121675.852646,VS0,VE0',
22 silly get     vary: 'Accept-Encoding' } ]
23 verbose etag https://registry.npmjs.org/gulp from cache
24 verbose get saving gulp to C:\Users\user\AppData\Roaming\npm-cache\registry.npmjs.org\gulp\.cache.json
25 verbose correctMkdir C:\Users\user\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
26 silly install normalizeTree
27 silly loadCurrentTree Finishing
28 silly loadIdealTree Starting
29 silly install loadIdealTree
30 silly cloneCurrentTree Starting
31 silly install cloneCurrentTreeToIdealTree
32 silly cloneCurrentTree Finishing
33 silly loadShrinkwrap Starting
34 silly install loadShrinkwrap
35 silly loadShrinkwrap Finishing
36 silly loadAllDepsIntoIdealTree Starting
37 silly install loadAllDepsIntoIdealTree
38 silly rollbackFailedOptional Starting
39 silly rollbackFailedOptional Finishing
40 silly runTopLevelLifecycles Starting
41 silly runTopLevelLifecycles Finishing
42 silly install printInstalled
43 verbose stack Error: Refusing to install gulp as a dependency of itself
43 verbose stack     at checkSelf (C:\Users\user\AppData\Roaming\npm\node_modules\npm\lib\install\validate-args.js:53:14)
43 verbose stack     at Array.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
43 verbose stack     at LOOP (C:\Users\user\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
43 verbose stack     at chain (C:\Users\user\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
43 verbose stack     at C:\Users\user\AppData\Roaming\npm\node_modules\npm\lib\install\validate-args.js:16:5
43 verbose stack     at C:\Users\user\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:52:35
43 verbose stack     at Array.forEach (native)
43 verbose stack     at C:\Users\user\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:52:11
43 verbose stack     at Array.forEach (native)
43 verbose stack     at asyncMap (C:\Users\user\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:51:8)
44 verbose cwd C:\test\gulp
45 error Windows_NT 6.2.9200
46 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\user\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save-dev" "gulp"
47 error node v6.3.1
48 error npm  v3.10.6
49 error code ENOSELF
50 error Refusing to install gulp as a dependency of itself
51 error If you need help, you may report this error at:
51 error     <https://github.com/npm/npm/issues>
52 verbose exit [ 1, true ]

**Comment by legodude17** [comment]
Make sure that the `name` field of your `package.json` is not `gulp`.

**Comment by snopeks** [comment]
@adgranados as @legodude17 mentioned, it looks like you have to change the name field in your package.json. ENOSELF is saying npm is refusing to install a dependency that has the same name as the current package. Give that a try and let us know if you need more help 👍
