### ISSUE TITLE
express will not install on Windows 8.1

### ISSUE THREAD

**Issue by rxp8385** [npm/npm#14500]
I've been waiting over an hour for express to install.  After entering:

npm install -g express

the output is as follows:
[....] - loadRequestDeps: sill install loadAllDepsIntoIdealTree

and the install never completes.  Here is the log after terminating the command prompt:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'express',
1 verbose cli   '--save' ]
2 info using npm@3.10.8
3 info using node@v6.9.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData express
8 silly fetchNamedPackageData express
9 silly mapToRegistry name express
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'express',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'express',
12 silly mapToRegistry   name: 'express',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/express
14 verbose request uri https://registry.npmjs.org/express
15 verbose request no auth needed
16 info attempt registry request try #1 at 3:08:14 PM
17 verbose request id e9c7d36e70051a2a
18 http request GET https://registry.npmjs.org/express
19 http 200 https://registry.npmjs.org/express
20 verbose headers { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
20 verbose headers   etag: '"1QGTG51092FO6EI4PC2TFJRG6"',
20 verbose headers   'content-type': 'application/json',
20 verbose headers   'content-encoding': 'gzip',
20 verbose headers   'cache-control': 'max-age=300',
20 verbose headers   'content-length': '56777',
20 verbose headers   'accept-ranges': 'bytes',
20 verbose headers   date: 'Wed, 02 Nov 2016 19:08:20 GMT',
20 verbose headers   via: '1.1 varnish',
20 verbose headers   age: '197',
20 verbose headers   connection: 'keep-alive',
20 verbose headers   'x-served-by': 'cache-iad2643-IAD',
20 verbose headers   'x-cache': 'HIT',
20 verbose headers   'x-cache-hits': '4',
20 verbose headers   'x-timer': 'S1478113700.912542,VS0,VE0',
20 verbose headers   vary: 'Accept-Encoding' }
21 silly get cb [ 200,
21 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
21 silly get     etag: '"1QGTG51092FO6EI4PC2TFJRG6"',
21 silly get     'content-type': 'application/json',
21 silly get     'content-encoding': 'gzip',
21 silly get     'cache-control': 'max-age=300',
21 silly get     'content-length': '56777',
21 silly get     'accept-ranges': 'bytes',
21 silly get     date: 'Wed, 02 Nov 2016 19:08:20 GMT',
21 silly get     via: '1.1 varnish',
21 silly get     age: '197',
21 silly get     connection: 'keep-alive',
21 silly get     'x-served-by': 'cache-iad2643-IAD',
21 silly get     'x-cache': 'HIT',
21 silly get     'x-cache-hits': '4',
21 silly get     'x-timer': 'S1478113700.912542,VS0,VE0',
21 silly get     vary: 'Accept-Encoding' } ]
22 verbose get saving express to C:\Users\Lando\AppData\Roaming\npm-cache\registry.npmjs.org\express\.cache.json
23 verbose correctMkdir C:\Users\Lando\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
24 verbose makeDirectory C:\Users\Lando\AppData\Roaming\npm-cache creation not in flight; initializing
25 verbose makeCacheDir UID & GID are irrelevant on win32
26 silly install normalizeTree
27 silly loadCurrentTree Finishing
28 silly loadIdealTree Starting
29 silly install loadIdealTree
30 silly cloneCurrentTree Starting
31 silly install cloneCurrentTreeToIdealTree
32 silly cloneCurrentTree Finishing
33 silly loadShrinkwrap Starting
34 silly install loadShrinkwrap
35 silly loadShrinkwrap Finishing
36 silly loadAllDepsIntoIdealTree Starting
37 silly install loadAllDepsIntoIdealTree
38 silly resolveWithNewModule express@4.14.0 checking installable status
39 silly cache add args [ 'express', null ]
40 verbose cache add spec express
41 silly cache add parsed spec Result {
41 silly cache add   raw: 'express',
41 silly cache add   scope: null,
41 silly cache add   escapedName: 'express',
41 silly cache add   name: 'express',
41 silly cache add   rawSpec: '',
41 silly cache add   spec: 'latest',
41 silly cache add   type: 'tag' }
42 silly addNamed express@latest
43 verbose addNamed "latest" is being treated as a dist-tag for express
44 info addNameTag [ 'express', 'latest' ]
45 silly mapToRegistry name express
46 silly mapToRegistry using default registry
47 silly mapToRegistry registry https://registry.npmjs.org/
48 silly mapToRegistry data Result {
48 silly mapToRegistry   raw: 'express',
48 silly mapToRegistry   scope: null,
48 silly mapToRegistry   escapedName: 'express',
48 silly mapToRegistry   name: 'express',
48 silly mapToRegistry   rawSpec: '',
48 silly mapToRegistry   spec: 'latest',
48 silly mapToRegistry   type: 'tag' }
49 silly mapToRegistry uri https://registry.npmjs.org/express
50 verbose addNameTag registry:https://registry.npmjs.org/express not in flight; fetching
51 verbose get https://registry.npmjs.org/express not expired, no request
52 silly addNameTag next cb for express with tag latest
53 silly addNamed express@4.14.0
54 verbose addNamed "4.14.0" is a plain semver version for express
55 silly mapToRegistry name express
56 silly mapToRegistry using default registry
57 silly mapToRegistry registry https://registry.npmjs.org/
58 silly mapToRegistry data Result {
58 silly mapToRegistry   raw: 'express',
58 silly mapToRegistry   scope: null,
58 silly mapToRegistry   escapedName: 'express',
58 silly mapToRegistry   name: 'express',
58 silly mapToRegistry   rawSpec: '',
58 silly mapToRegistry   spec: 'latest',
58 silly mapToRegistry   type: 'tag' }
59 silly mapToRegistry uri https://registry.npmjs.org/express
60 verbose addRemoteTarball https://registry.npmjs.org/express/-/express-4.14.0.tgz not in flight; adding
61 verbose addRemoteTarball [ 'https://registry.npmjs.org/express/-/express-4.14.0.tgz',
61 verbose addRemoteTarball   'c1ee3f42cdc891fb3dc650a8922d51ec847d0d66' ]
62 verbose stack Error: kill ENOSYS
62 verbose stack     at exports._errnoException (util.js:1026:11)
62 verbose stack     at process.kill (internal/process.js:172:13)
62 verbose stack     at process.listener (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npmlog\node_modules\gauge\node_modules\signal-exit\index.js:86:15)
62 verbose stack     at emitNone (events.js:91:20)
62 verbose stack     at process.emit (events.js:185:7)
62 verbose stack     at processEmit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npmlog\node_modules\gauge\node_modules\signal-exit\index.js:146:32)
62 verbose stack     at processEmit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-registry-client\node_modules\npmlog\node_modules\gauge\node_modules\signal-exit\index.js:146:32)
62 verbose stack     at Signal.wrap.onsignal (internal/process.js:199:44)
63 verbose cwd C:\Users\Lando\meantut
64 error Windows_NT 6.3.9600
65 error argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "express" "--save"
66 error node v6.9.1
67 error npm  v3.10.8
68 error code ENOSYS
69 error errno ENOSYS
70 error syscall kill
71 error kill ENOSYS
72 error If you need help, you may report this error at:
72 error     <https://github.com/npm/npm/issues>
73 verbose exit [ 1, true ]

I would appreciate any help with this issue.

Thank you

**Comment by legodude17** [comment]
Please check your internet connection.

**Comment by rxp8385** [comment]
Thank you.  I checked my Internet connection, and all other programs are working properly.

**Comment by legodude17** [comment]
Try running `npm install -ddd -g express`. What is the last line printed before it hangs?

**Comment by rxp8385** [comment]
After entering:

npm install -ddd -g express

The following is printed:

npm info it worked if it ends with ok
npm verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   '-ddd',
npm verb cli   '-g',
npm verb cli   'express' ]
npm info using npm@3.10.8
npm info using node@v6.9.1

Usage: npm <command>

where <command> is one of:
    access, adduser, bin, bugs, c, cache, completion, config,
    ddp, dedupe, deprecate, dist-tag, docs, edit, explore, get,
    help, help-search, i, init, install, install-test, it, link,
    list, ln, login, logout, ls, outdated, owner, pack, ping,
    prefix, prune, publish, rb, rebuild, repo, restart, root,
    run, run-script, s, se, search, set, shrinkwrap, star,
    stars, start, stop, t, tag, team, test, tst, un, uninstall,
    unpublish, unstar, up, update, v, version, view, whoami

npm <cmd> -h     quick help on <cmd>
npm -l           display full usage info
npm help <term>  search for help on <term>
npm help npm     involved overview

Specify configs in the ini-formatted file:
    C:\Users\Lando\.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@3.10.8 C:\Program Files\nodejs\node_modules\npm

**Comment by zkat** [comment]
@rxp8385 You need to actually include `install` in your command. You typed `npm -ddd -g express`. Additionally, express isn't a module that is meant to be installed globally. It's strange that it's taken an hour. Does it work any better if you install it locally to your project without `-g` as intended? Note that using `-g` for express will *not* make it available to `require` in node.

**Comment by rxp8385** [comment]
Thank you zkat.

When I install express locally, it still hangs at the following section:

C:\Users\Lando\meantut>npm install express
[    ..............] | loadRequestedDeps: sill install loadAllDepsIntoIdealTree
