### ISSUE TITLE
error in checking ver.

### ISSUE THREAD

**Issue by aymank36** [npm/npm#14518]
Version: 2.15.9
Platform: 32-bit
Subsystem: Windows 7

```
C:\Users\Ayman>npm -v
SyntaxError: C:\Program Files\nodejs\node_modules\npm\node_modules\spdx-license-
ids\spdx-license-ids.json: Unexpected end of input
    at Object.parse (native)
c
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules
\validate-npm-package-license\node_modules\spdx-correct\index.js:1:80)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "prefix" "-g"
npm ERR! node v4.6.0
npm ERR! npm  v2.15.9

npm ERR! C:\Program Files\nodejs\node_modules\npm\node_modules\spdx-license-ids\
spdx-license-ids.json: Unexpected end of input
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

2.15.9

**Comment by legodude17** [comment]
Does `npm` even depend on `spdx-lincense-ids`?

**Comment by KenanY** [comment]
@legodude17 

```
$ npm ls spdx-license-ids
npm@4.0.1 /home/kenan/code/npm
└─┬ validate-npm-package-license@3.0.1
  ├─┬ spdx-correct@1.0.2
  │ └── spdx-license-ids@1.2.0 
  └─┬ spdx-expression-parse@1.0.2
    └── spdx-license-ids@1.2.0 
```

**Comment by legodude17** [comment]
So three levels down, the data somehow got corrupted. 😕

**Comment by legodude17** [comment]
What does does the `spdx-license-ids` folder look like @aymank36?

**Comment by KenanY** [comment]
Closing as abandoned.
