### ISSUE TITLE
EBADPLATFORM Exptects "os":"!win32" event though I am on Win 8.1 x64

### ISSUE THREAD

**Issue by mathiasconradt** [npm/npm#14512]
When I try to install `n` via `npm` I get the message that an non-win32 os is expected, but I am on a x64 system already (Windows 8.1).

```
C:\Users\mlin\Projects>node -v
v6.9.1

C:\Users\mlin\Projects>npm -v
3.10.9

C:\Users\mlin\Projects>npm install -g n
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\mlin\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "n"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.9
npm ERR! code EBADPLATFORM

npm ERR! notsup Unsupported platform for n@2.1.4: wanted {"os":"!win32","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! notsup Valid OS:    !win32
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\mlin\Projects\npm-debug.log
```

npm-debug.log:

```
40 silly install printInstalled
41 verbose stack Error: Unsupported platform for n@2.1.4: wanted {"name":"n","description":"Interactively Manage All Your Node Versions","version":"2.1.4","author":{"name":"TJ Holowaychuk","email":"tj@vision-media.ca"},"homepage":"https://github.com/tj/n","bugs":{"url":"https://github.com/tj/n/issues"},"contributors":[{"name":"Travis Webb","email":"me@traviswebb.com","url":"tjw.io"},{"name":"Nimit Kalra","email":"me@nimit.io","url":"http://nimit.io"},{"name":"Troy Connor","email":"troy0820@gmail.com","url":"https://github.com/troy0820"}],"keywords":["nvm","node","version","manager","switcher","node","binary","env"],"bin":{"n":"./bin/n"},"repository":{"type":"git","url":"git://github.com/tj/n.git"},"preferGlobal":true,"os":["!win32"],"engines":{"node":"*"},"license":"MIT","gitHead":"ff9ba303d972069903c0f951ece43f47adce24e8","_id":"n@2.1.4","scripts":{},"_shasum":"7546bc467a120cc96718f2716cd86c43290f94c5","_from":"n","_npmVersion":"3.10.3","_nodeVersion":"6.3.1","_npmUser":{"name":"qw3rtman","email":"me@nimit.io"},"dist":{"shasum":"7546bc467a120cc96718f2716cd86c43290f94c5","tarball":"https://registry.npmjs.org/n/-/n-2.1.4.tgz"},"maintainers":[{"name":"bat","email":"ben@benatkin.com"},{"name":"qw3rtman","email":"nimit@nimitkalra.com"},{"name":"tedgaydos","email":"tedgaydos@gmail.com"},{"name":"tjholowaychuk","email":"tj@vision-media.ca"},{"name":"tjwebb","email":"me@traviswebb.com"},{"name":"troy0820","email":"troy.connor@yahoo.com"}],"_npmOperationalInternal":{"host":"packages-16-east.internal.npmjs.com","tmp":"tmp/n-2.1.4.tgz_1470600124670_0.21058935346081853"},"directories":{},"_resolved":"https://registry.npmjs.org/n/-/n-2.1.4.tgz","_requested":{"raw":"n","scope":null,"escapedName":"n","name":"n","rawSpec":"","spec":"latest","type":"tag"},"_spec":"n","_where":"C:\\Users\\mlin\\Projects","_args":[[{"raw":"n","scope":null,"escapedName":"n","name":"n","rawSpec":"","spec":"latest","type":"tag"},"C:\\Users\\mlin\\Projects"]],"readme":"ERROR: No README data found!"} (current: {"os":"win32","cpu":"x64"})
41 verbose stack     at checkPlatform (C:\Users\mlin\AppData\Roaming\npm\node_modules\npm\node_modules\npm-install-checks\index.js:45:14)
41 verbose stack     at thenWarnEngineIssues (C:\Users\mlin\AppData\Roaming\npm\node_modules\npm\lib\install\validate-args.js:41:5)
41 verbose stack     at C:\Users\mlin\AppData\Roaming\npm\node_modules\npm\node_modules\iferr\index.js:13:50
41 verbose stack     at checkEngine (C:\Users\mlin\AppData\Roaming\npm\node_modules\npm\node_modules\npm-install-checks\index.js:24:10)
41 verbose stack     at module.exports.isInstallable (C:\Users\mlin\AppData\Roaming\npm\node_modules\npm\lib\install\validate-args.js:38:3)
41 verbose stack     at Array.<anonymous> (C:\Users\mlin\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
41 verbose stack     at LOOP (C:\Users\mlin\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
41 verbose stack     at C:\Users\mlin\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:18:7
41 verbose stack     at checkSelf (C:\Users\mlin\AppData\Roaming\npm\node_modules\npm\lib\install\validate-args.js:46:72)
41 verbose stack     at Array.<anonymous> (C:\Users\mlin\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
42 verbose pkgid n@2.1.4
```

**Comment by KenanY** [comment]
@mathiasconradt What's the output of `echo %PROCESSOR_ARCHITECTURE%`?

**Comment by mathiasconradt** [comment]
@KenanY AMD64

**Comment by KenanY** [comment]
Wait, no, `n` does not support Windows, just check the readme: https://github.com/tj/n

When they put `!win32` that negates all Windows systems since they all result in [`os.platform()`](https://nodejs.org/dist/latest-v7.x/docs/api/os.html#os_os_platform) returning `win32`. This isn't a `npm` issue.
