### ISSUE TITLE
Cannot find module storj

### ISSUE THREAD

**Issue by safa-yakoub** [npm/npm#14524]
<details>
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Safa Yakoub\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'init' ]
2 info using npm@3.10.9
3 info using node@v6.9.1
4 verbose stack Error: kill ENOSYS
4 verbose stack     at exports._errnoException (util.js:1026:11)
4 verbose stack     at process.kill (internal/process.js:172:13)
4 verbose stack     at process.listener (C:\Users\Safa Yakoub\AppData\Roaming\npm\node_modules\npm\node_modules\npmlog\node_modules\gauge\node_modules\signal-exit\index.js:86:15)
4 verbose stack     at emitNone (events.js:91:20)
4 verbose stack     at process.emit (events.js:185:7)
4 verbose stack     at processEmit (C:\Users\Safa Yakoub\AppData\Roaming\npm\node_modules\npm\node_modules\npmlog\node_modules\gauge\node_modules\signal-exit\index.js:146:32)
4 verbose stack     at processEmit (C:\Users\Safa Yakoub\AppData\Roaming\npm\node_modules\npm\node_modules\npm-registry-client\node_modules\npmlog\node_modules\gauge\node_modules\signal-exit\index.js:146:32)
4 verbose stack     at Signal.wrap.onsignal (internal/process.js:199:44)
5 verbose cwd C:\Users\Safa Yakoub\Desktop\SPTest
6 error Windows_NT 6.1.7601
7 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Safa Yakoub\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "init"
8 error node v6.9.1
9 error npm  v3.10.9
10 error code ENOSYS
11 error errno ENOSYS
12 error syscall kill
13 error kill ENOSYS
14 error If you need help, you may report this error at:
14 error     <https://github.com/npm/npm/issues>
15 verbose exit [ 1, true ]
```
</details>

**Comment by legodude17** [comment]
Can you please fill out the issue template and follow all instructions on it? This is very hard to read.

**Comment by KenanY** [comment]
Closing due to lack of a response. Can reopen if this is still an issue and more information is provided.
