### ISSUE TITLE
error installing -g angular-cli

### ISSUE THREAD

**Issue by manuelsolfaktor** [npm/npm#14563]
I get this error in  `npm-debug.log`:

<details>
```
134307 silly install printInstalled
134308 verbose stack Error: Invalid name: "@angular/tsc-wrapped"
134308 verbose stack     at ensureValidName (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/fixer.js:281:15)
134308 verbose stack     at Object.fixNameField (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/fixer.js:196:5)
134308 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/normalize.js:29:38
134308 verbose stack     at Array.forEach (native)
134308 verbose stack     at normalize (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/normalize.js:28:15)
134308 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:349:5)
134308 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:124:5)
134308 verbose stack     at ReadFileContext.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:295:20)
134308 verbose stack     at ReadFileContext.callback (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16)
134308 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:365:13)
134309 verbose cwd /Users/manu/Documents/htdocs/angular
134310 error Darwin 14.3.0
134311 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "-f" "angular-cli"
134312 error node v6.9.1
134313 error npm  v3.10.8
134314 error Invalid name: "@angular/tsc-wrapped"
134315 error If you need help, you may report this error at:
134315 error     <https://github.com/npm/npm/issues>
134316 verbose exit [ 1, true ]
```
</details>

**Comment by legodude17** [comment]
Hi! Try updating `npm` to `4.0.2`. Also please search for "invalid name" on the issue tracker and try those solutions. Cheers!
