### ISSUE TITLE
SyntaxError: Unexpected token }

### ISSUE THREAD

**Issue by sevenbitsravina** [npm/npm#14581]
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'karma',
1 verbose cli   '–save-dev' ]
2 info using npm@2.11.3
3 info using node@v0.12.7
4 verbose stack /usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/fetch.js:19
4 verbose stack });
4 verbose stack ^
4 verbose stack SyntaxError: Unexpected token }
4 verbose stack     at exports.runInThisContext (vm.js:73:16)
4 verbose stack     at Module._compile (module.js:443:25)
4 verbose stack     at Object.Module._extensions..js (module.js:478:10)
4 verbose stack     at Module.load (module.js:355:32)
4 verbose stack     at Function.Module._load (module.js:310:12)
4 verbose stack     at Module.require (module.js:365:17)
4 verbose stack     at require (module.js:384:17)
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/npm-registry-client/index.js:73:20
4 verbose stack     at Array.forEach (native)
4 verbose stack     at CachingRegistryClient.RegClient (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/index.js:51:42)
5 verbose cwd /media/seven-bits-pc11/E476GB/Sevenbits-git/Android/NopStation
6 error Linux 3.19.0-69-generic
7 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "karma" "–save-dev"
8 error node v0.12.7
9 error npm  v2.11.3
10 error /usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/fetch.js:19
10 error });
10 error ^
10 error Unexpected token }
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
```

**Comment by lapochka** [comment]
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8

npm ERR! missing script: start
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\elapochkina\angular-quickstart\npm-debug.log

**Comment by lapochka** [comment]
Hi,help me,please.What I should it?

**Comment by KenanY** [comment]
@sevenbitsravina Hmm, perhaps try reinstalling `npm`? Preferably the latest version :)

@lapochka Ensure that you have a `"start"` script defined in your `package.json` before running `npm start`. For more information on how npm scripts work and how to write your own, check out the [documentation](https://docs.npmjs.com/misc/scripts).

**Comment by KenanY** [comment]
Closing as abandoned.
