### ISSUE TITLE
npm ERR! Cannot find module 'internal/fs'

### ISSUE THREAD

**Issue by sabdelrehim** [npm/npm#14603]
0 info it worked if it ends with ok
1 verbose cli [ 'e:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'e:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'angular-cli' ]
2 info using npm@3.10.9
3 info using node@v7.1.0
4 verbose stack Error: Cannot find module 'internal/fs'
4 verbose stack     at Function.Module._resolveFilename (module.js:472:15)
4 verbose stack     at Function.Module._load (module.js:420:25)
4 verbose stack     at Module.require (module.js:500:17)
4 verbose stack     at require (internal/module.js:20:19)
4 verbose stack     at evalmachine.<anonymous>:17:20
4 verbose stack     at Object.<anonymous> (e:\Program Files\nodejs\node_modules\npm\node_modules\cmd-shim\node_modules\graceful-fs\fs.js:11:1)
4 verbose stack     at Module._compile (module.js:573:32)
4 verbose stack     at Object.Module._extensions..js (module.js:582:10)
4 verbose stack     at Module.load (module.js:490:32)
4 verbose stack     at tryModuleLoad (module.js:449:12)
5 verbose cwd E:\Angular2
6 error Windows_NT 10.0.14965
7 error argv "e:\\Program Files\\nodejs\\node.exe" "e:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "angular-cli"
8 error node v7.1.0
9 error npm  v3.10.9
10 error code MODULE_NOT_FOUND
11 error Cannot find module 'internal/fs'
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]

**Comment by sabdelrehim** [comment]
Well, I reinstalled Nodejs, but another problem pops up relating to "shasum check failed".
