### ISSUE TITLE
npm install

### ISSUE THREAD

**Issue by M-Fasciano** [npm/npm#14685]
$ npm install
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v6.9.1
npm ERR! npm v3.10.8

npm ERR! Invalid protocol: null
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR! https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR! C:\My_Projects\YeomanGenerator\npm-debug.log

**Comment by M-Fasciano** [comment]
$ npm install
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ECONNREFUSED
npm ERR! errno ECONNREFUSED
npm ERR! syscall connect

npm ERR! Error: connect ECONNREFUSED 127.0.0.1:81
npm ERR!     at Object.exports._errnoException (util.js:1026:11)
npm ERR!     at exports._exceptionWithHostPort (util.js:1049:20)
npm ERR!     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1085:14)
npm ERR!  { Error: connect ECONNREFUSED 127.0.0.1:81
npm ERR!     at Object.exports._errnoException (util.js:1026:11)
npm ERR!     at exports._exceptionWithHostPort (util.js:1049:20)
npm ERR!     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1085:14)
npm ERR!   code: 'ECONNREFUSED',
npm ERR!   errno: 'ECONNREFUSED',
npm ERR!   syscall: 'connect',
npm ERR!   address: '127.0.0.1',
npm ERR!   port: 81,
npm ERR!   parent: 'new_project' }
npm ERR!
npm ERR! If you are behind a proxy, please make sure that the
npm ERR! 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     C:\My_Projects\AQ\Handlebars\npm-debug.log
