### ISSUE TITLE
My npm install broke down. How can I manually replace broke version with new?

### ISSUE THREAD

**Issue by ismael-rivera** [npm/npm#14699]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

My npm installation is pretty much useless. Any command using npm produces the following output:

```
module.js:338
    throw err;
          ^
Error: Cannot find module 'are-we-there-yet'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/Cellar/node/0.10.26/lib/node_modules/npm/node_modules/npmlog/log.js:2:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

#### How can the CLI team reproduce the problem?

Not sure how to reproduce the problem. Did not even know there was a problem. I used npm a week ago, had no hassles. My mac is pretty old though [Mac Pro 3'1 - 2008] - and packages do tend to break down more usual than before. I can't find npm-debug.log. Did a google search of where to find this file -- No help. Not much info online on this, that I could see.

ran node -v and got this: v0.12.17. Did a search on http://stackoverflow.com/ and found an answer that worked for someone but it requires manually downloading the latest tarball and replacing it with the originally installed binary. In any event, I have ZERO idea on how to do this. PLEASE, if someone knows what files to keep, and what to throw out, it would very much help us out. Thank You.
 

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
You could try doing

``` bash
curl -L https://www.npmjs.com/install.sh | sh
```

**Comment by ismael-rivera** [comment]
I did. Twice. Did not work. I've attached the resulting npm-debug.log file and I also received the following as direct output on the terminal:

[npm-debug.log.txt](https://github.com/npm/npm/files/608479/npm-debug.log.txt)

```

npm ERR! Darwin 10.8.0
npm ERR! argv "/usr/local/bin/node" "/private/var/folders/AI/AIR0nk5GH+CghB8OUxAzwk+++TI/-Tmp-/npm.574/package/cli.js" "rm" "npm" "-gf"
npm ERR! node v0.12.17
npm ERR! npm  v4.0.2

npm ERR! Maximum call stack size exceeded
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/AI/AIR0nk5GH+CghB8OUxAzwk+++TI/-Tmp-/npm.574/package/npm-debug.log

> npm@4.0.2 prepublish /private/var/folders/AI/AIR0nk5GH+CghB8OUxAzwk+++TI/-Tmp-/npm.574/package
> node bin/npm-cli.js prune --prefix=. --no-global && rimraf test/*/*/node_modules && make doc-clean && make -j4 doc

sh: rimraf: command not found
- ansi@0.3.1 node_modules/npm/node_modules/ansi
- block-stream@0.0.8 node_modules/npm/node_modules/block-stream
- balanced-match@0.2.1 node_modules/npm/node_modules/minimatch/node_modules/brace-expansion/node_modules/balanced-match
- concat-map@0.0.1 node_modules/npm/node_modules/minimatch/node_modules/brace-expansion/node_modules/concat-map
- brace-expansion@1.1.1 node_modules/npm/node_modules/minimatch/node_modules/brace-expansion
- minimatch@3.0.0 node_modules/npm/node_modules/minimatch
- balanced-match@0.3.0 node_modules/npm/node_modules/node-gyp/node_modules/glob/node_modules/minimatch/node_modules/brace-expansion/node_modules/balanced-match
- concat-map@0.0.1 node_modules/npm/node_modules/node-gyp/node_modules/glob/node_modules/minimatch/node_modules/brace-expansion/node_modules/concat-map
- brace-expansion@1.1.3 node_modules/npm/node_modules/node-gyp/node_modules/glob/node_modules/minimatch/node_modules/brace-expansion
- minimatch@2.0.10 node_modules/npm/node_modules/node-gyp/node_modules/glob/node_modules/minimatch
- lru-cache@2.7.3 node_modules/npm/node_modules/node-gyp/node_modules/minimatch/node_modules/lru-cache
- sigmund@1.0.1 node_modules/npm/node_modules/node-gyp/node_modules/minimatch/node_modules/sigmund
- has-unicode@2.0.0 node_modules/npm/node_modules/npmlog/node_modules/gauge/node_modules/has-unicode
- lodash._basetostring@3.0.1 node_modules/npm/node_modules/npmlog/node_modules/gauge/node_modules/lodash._basetostring
- lodash._root@3.0.1 node_modules/npm/node_modules/npmlog/node_modules/gauge/node_modules/lodash.repeat/node_modules/lodash._root
- lodash.repeat@3.2.0 node_modules/npm/node_modules/npmlog/node_modules/gauge/node_modules/lodash.repeat
- lodash._createpadding@3.6.1 node_modules/npm/node_modules/npmlog/node_modules/gauge/node_modules/lodash._createpadding
- lodash.padleft@3.1.1 node_modules/npm/node_modules/npmlog/node_modules/gauge/node_modules/lodash.padleft
- lodash.padright@3.1.1 node_modules/npm/node_modules/npmlog/node_modules/gauge/node_modules/lodash.padright
- lodash.pad@3.2.2 node_modules/npm/node_modules/npmlog/node_modules/gauge/node_modules/lodash.pad
- debuglog@1.0.1 node_modules/npm/node_modules/read-installed/node_modules/debuglog
- lru-cache@2.7.3 node_modules/npm/node_modules/request/node_modules/aws4/node_modules/lru-cache
- core-util-is@1.0.2 node_modules/npm/node_modules/request/node_modules/bl/node_modules/readable-stream/node_modules/core-util-is
- isarray@0.0.1 node_modules/npm/node_modules/request/node_modules/bl/node_modules/readable-stream/node_modules/isarray
- process-nextick-args@1.0.6 node_modules/npm/node_modules/request/node_modules/bl/node_modules/readable-stream/node_modules/process-nextick-args
- string_decoder@0.10.31 node_modules/npm/node_modules/request/node_modules/bl/node_modules/readable-stream/node_modules/string_decoder
- util-deprecate@1.0.2 node_modules/npm/node_modules/request/node_modules/bl/node_modules/readable-stream/node_modules/util-deprecate
- readable-stream@2.0.5 node_modules/npm/node_modules/request/node_modules/bl/node_modules/readable-stream
- bl@1.0.2 node_modules/npm/node_modules/request/node_modules/bl
- async@1.5.2 node_modules/npm/node_modules/request/node_modules/form-data/node_modules/async
- path-is-absolute@1.0.0 node_modules/npm/node_modules/rimraf/node_modules/glob/node_modules/path-is-absolute
- glob@7.0.0 node_modules/npm/node_modules/rimraf/node_modules/glob
- is-relative@0.1.3 node_modules/npm/node_modules/which/node_modules/is-absolute/node_modules/is-relative
- is-absolute@0.1.7 node_modules/npm/node_modules/which/node_modules/is-absolute
- lru-cache node_modules/npm/node_modules/lru-cache
- pseudomap@1.0.1 node_modules/npm/node_modules/lru-cache/node_modules/pseudomap
- glob@4.5.3 node_modules/npm/node_modules/node-gyp/node_modules/glob
- retry@0.8.0 node_modules/npm/node_modules/npm-registry-client/node_modules/retry
- readdir-scoped-modules@1.0.2 node_modules/npm/node_modules/read-installed/node_modules/readdir-scoped-modules
- readable-stream node_modules/npm/node_modules/sha/node_modules/readable-stream
- core-util-is@1.0.1 node_modules/npm/node_modules/sha/node_modules/readable-stream/node_modules/core-util-is
- isarray@0.0.1 node_modules/npm/node_modules/sha/node_modules/readable-stream/node_modules/isarray
- process-nextick-args@1.0.3 node_modules/npm/node_modules/sha/node_modules/readable-stream/node_modules/process-nextick-args
- string_decoder@0.10.31 node_modules/npm/node_modules/sha/node_modules/readable-stream/node_modules/string_decoder
- util-deprecate@1.0.1 node_modules/npm/node_modules/sha/node_modules/readable-stream/node_modules/util-deprecate
/usr/local/lib
└── (empty)

npm ERR! Darwin 10.8.0
npm ERR! argv "/usr/local/bin/node" "/private/var/folders/AI/AIR0nk5GH+CghB8OUxAzwk+++TI/-Tmp-/npm.574/package/cli.js" "install" "-gf"
npm ERR! node v0.12.17
npm ERR! npm  v4.0.2
npm ERR! path /usr/local/lib/node_modules/npm/lib/cache/add-local-tarball.js
npm ERR! code EACCES
npm ERR! errno -13

npm ERR! Error: EACCES, unlink '/usr/local/lib/node_modules/npm/lib/cache/add-local-tarball.js'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES, unlink '/usr/local/lib/node_modules/npm/lib/cache/add-local-tarball.js']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/usr/local/lib/node_modules/npm/lib/cache/add-local-tarball.js' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/AI/AIR0nk5GH+CghB8OUxAzwk+++TI/-Tmp-/npm.574/package/npm-debug.log
 
```

**Comment by ismael-rivera** [comment]
Does anybody know if there is any way of me doing a reinstallation via a drag and drop switch of the proper files?

**Comment by othiym23** [comment]
@ismael-rivera The fastest way to fix this is probably just to grab a Node installer from nodejs.org and reinstall Node, which brings a clean install of a (maybe a little old) clean version of the npm CLI. Sorry about your difficulties with the installer; it presumes that if there's a version of npm already installed, that it can be used to do stuff, which in this case was clearly in error. If you removed npm altogether, it might work. But the safer route is to reinstall Node.

**Comment by DrStrangepork** [comment]
@ismael-rivera You need to install the `node-rimraf` package for the `install.sh` to work, but based on my experience that won't solve the underlying problem of npm not working.
