### ISSUE TITLE
unable to run ' npm run watch '

### ISSUE THREAD

**Issue by tenze** [npm/npm#14693]
Hi all, 
   i am not able to run npm run watch, i keep getting this missing script watch error.  
any idea why i am getting error ?
thanks in advance

> npm-dedub.log

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/.nvm/versions/node/v6.6.0/bin/node',
1 verbose cli   '/Users/.nvm/versions/node/v6.6.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'watch' ]
2 info using npm@3.10.7
3 info using node@v6.6.0
4 verbose stack Error: missing script: watch
4 verbose stack     at run (/Users/.nvm/versions/node/v6.6.0/lib/node_modules/npm/lib/run-script.js:151:19)
4 verbose stack     at /Users/.nvm/versions/node/v6.6.0/lib/node_modules/npm/lib/run-script.js:61:5
4 verbose stack     at /Users/.nvm/versions/node/v6.6.0/lib/node_modules/npm/node_modules/read-package-json/read-json.js:356:5
4 verbose stack     at checkBinReferences_ (/Users/.nvm/versions/node/v6.6.0/lib/node_modules/npm/node_modules/read-package-json/read-json.js:320:45)
4 verbose stack     at final (/Users/.nvm/versions/node/v6.6.0/lib/node_modules/npm/node_modules/read-package-json/read-json.js:354:3)
4 verbose stack     at then (/Users/.nvm/versions/node/v6.6.0/lib/node_modules/npm/node_modules/read-package-json/read-json.js:124:5)
4 verbose stack     at /Users/.nvm/versions/node/v6.6.0/lib/node_modules/npm/node_modules/read-package-json/read-json.js:243:12
4 verbose stack     at /Users/.nvm/versions/node/v6.6.0/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
4 verbose stack     at tryToString (fs.js:455:3)
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)
5 verbose cwd /Users/WDI/ReduxSimpleStarter
6 error Darwin 15.6.0
7 error argv "/Users/.nvm/versions/node/v6.6.0/bin/node" "/Users/.nvm/versions/node/v6.6.0/bin/npm" "run" "watch"
8 error node v6.6.0
9 error npm  v3.10.7
10 error missing script: watch
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
```

> webpack.config.js

```
`module.exports = {
  entry: [
    './src/index.js'
  ],
  output: {
    path: __dirname,
    publicPath: '/',
    filename: 'bundle.js'
  },
  module: {
    loaders: [{
      exclude: /node_modules/,
      loader: 'babel',
      query: {
        presets: ['react', 'es2015', 'stage-1']
      }
    }]
  },
  resolve: {
    extensions: ['', '.js', '.jsx']
  },
  devServer: {
    historyApiFallback: true,
    contentBase:  __dirname + './'
  }
};
```

> package.json

```
{
  "name": "redux-simple-starter",
  "version": "1.0.0",
  "description": "Simple starter package for Redux with React and Babel support",
  "main": "index.js",
  "repository": "git@github.com:StephenGrider/ReduxSimpleStarter.git",
  "scripts": {
    "start": "node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js",
    "test": "mocha --compilers js:babel-core/register --require ./test/test_helper.js --recursive ./test",
    "test:watch": "npm run test -- --watch"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "babel-core": "^6.2.1",
    "babel-loader": "^6.2.0",
    "babel-preset-es2015": "^6.1.18",
    "babel-preset-react": "^6.1.18",
    "chai": "^3.5.0",
    "chai-jquery": "^2.0.0",
    "jquery": "^2.2.1",
    "jsdom": "^8.1.0",
    "mocha": "^2.4.5",
    "react-addons-test-utils": "^0.14.7",
    "webpack": "^1.12.9",
    "webpack-dev-server": "^1.14.0"
  },
  "dependencies": {
    "babel-preset-stage-1": "^6.1.18",
    "lodash": "^3.10.1",
    "react": "^0.14.3",
    "react-dom": "^0.14.3",
    "react-redux": "^4.0.0",
    "react-router": "^2.0.1",
    "redux": "^3.0.4"
  }
}
```

**Comment by KenanY** [comment]
@tenze You don't have a `"watch"` script defined in your `package.json`. Once you create one, that error should go away :)
