### ISSUE TITLE
who can help me to install grunt?

### ISSUE THREAD

**Issue by dingrui37** [npm/npm#14692]
i'm a beginner, who can help me to install grunt?
 
-------------------------------------------------------------------------------------------------------------
```
when i first install,the error info was:
dingrui37@dingrui:~/git$ sudo npm install grunt
[sudo] password for dingrui37: 
npm ERR! Linux 4.4.0-45-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "grunt"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ENETUNREACH
npm ERR! errno ENETUNREACH
npm ERR! syscall connect
npm ERR! connect ENETUNREACH 151.101.16.162:443
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Please include the following file with any support request:
npm ERR!     /home/dingrui37/git/npm-debug.log
```
---------------------------------------------------------------------------------------------------------------------------

and then i search from baidu, and set registry and proxy,  but still cann't work;

--------------------------------------------------------------------------------------------------------------------------
```
dingrui37@dingrui:~/git$ npm config set registry=http://registry.npmjs.org
dingrui37@dingrui:~/git$ npm config set proxy=http://127.0.0.1:8087 
dingrui37@dingrui:~/git$ sudo npm install grunt
▀ ╢░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
^C
dingrui37@dingrui:~/git$ sudo npm install grunt
▌ ╢░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
^C
dingrui37@dingrui:~/git$ sudo npm install -g grunt
▌ ╢░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
^C
dingrui37@dingrui:~/git$ sudo npm install -g grunt
npm ERR! Linux 4.4.0-45-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "grunt"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ECONNREFUSED
npm ERR! errno ECONNREFUSED
npm ERR! syscall connect
npm ERR! Error: connect ECONNREFUSED 127.0.0.1:8087
npm ERR!     at Object.exports._errnoException (util.js:870:11)
npm ERR!     at exports._exceptionWithHostPort (util.js:893:20)
npm ERR!     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)
npm ERR!  { [Error: connect ECONNREFUSED 127.0.0.1:8087]
npm ERR!   code: 'ECONNREFUSED',
npm ERR!   errno: 'ECONNREFUSED',
npm ERR!   syscall: 'connect',
npm ERR!   address: '127.0.0.1',
npm ERR!   port: 8087 }
npm ERR! 
npm ERR! If you are behind a proxy, please make sure that the
npm ERR! 'proxy' config is set properly.  See: 'npm help config'
npm ERR! Please include the following file with any support request:
npm ERR!     /home/dingrui37/git/npm-debug.log
```
-------------------------------------------------------------------------------------------------------------------------------

**Comment by legodude17** [comment]
Try running `npm config set registry https://registry.npmjs.org`.

**Comment by schmidpa** [comment]
I got nearly the same message. Does someone have a solution ? 

errno ENETUNREACH
