### ISSUE TITLE
Error: Failed to execute "git ls-remote --tags --heads https://github.com/components/ember.git", exit code of #128

### ISSUE THREAD

**Issue by ryan-gibson** [npm/npm#14709]
I am using npm to install an EmberJS application.  I'm following the quick start guide here: https://guides.emberjs.com/v2.9.0/getting-started/quick-start/

The first time I ran through the installation it worked and I was able to run my new application.  I tried installing a new one afterwards and got the error below.  I've tried several methods of correcting the issue but I continue to get the error each time I try running "ember new test-application".

Things I have tried:
Added a config setting with this command: "git config --global url."https://".insteadOf git://"
Deleted the npm and the npm-cache folders from \AppData\Roaming folder
Installed Bower prior to creating the EmberJS application by running "nmp install -g bower"

Also to note, I am running the npm command prompt as administrator.

**Error: Failed to execute "git ls-remote --tags --heads https://github.com/components/ember.git", exit code of #128
fatal: failed to stat '.': No such file or directory

    at createError (C:\Users\rgibson\AppData\Roaming\npm\node_modules\ember-cli\node_modules\bower\lib\util\createError.js:4:15)
    at ChildProcess.<anonymous> (C:\Users\rgibson\AppData\Roaming\npm\node_modules\ember-cli\node_modules\bower\lib\util\cmd.js:102:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)**

**Comment by legodude17** [comment]
What command are you running? In what folder?
