### ISSUE TITLE
Problem at installing jsbin

### ISSUE THREAD

**Issue by swapnilchafale** [npm/npm#15044]
#### I'm opening this issue because:

0 info it worked if it ends with ok
1 verbose cli [ 'D:\\node.exe',
1 verbose cli   'D:\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'jsbin' ]
2 info using npm@3.10.8
3 info using node@v6.9.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData jsbin
8 silly fetchNamedPackageData jsbin
9 silly mapToRegistry name jsbin
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'jsbin',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'jsbin',
12 silly mapToRegistry   name: 'jsbin',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/jsbin
14 verbose request uri https://registry.npmjs.org/jsbin
15 verbose request no auth needed
16 info attempt registry request try #1 at 11:49:42 AM
17 verbose request id 0317ddd33db99743
18 http request GET https://registry.npmjs.org/jsbin
19 info retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
20 info attempt registry request try #2 at 11:50:04 AM
21 http request GET https://registry.npmjs.org/jsbin
22 info retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
23 info attempt registry request try #3 at 11:51:16 AM
24 http request GET https://registry.npmjs.org/jsbin
25 silly fetchPackageMetaData Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
25 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1026:11)
25 silly fetchPackageMetaData     at errnoException (dns.js:33:15)
25 silly fetchPackageMetaData     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
25 silly fetchPackageMetaData  error for jsbin { Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
25 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1026:11)
25 silly fetchPackageMetaData     at errnoException (dns.js:33:15)
25 silly fetchPackageMetaData     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
25 silly fetchPackageMetaData   code: 'EAI_AGAIN',
25 silly fetchPackageMetaData   errno: 'EAI_AGAIN',
25 silly fetchPackageMetaData   syscall: 'getaddrinfo',
25 silly fetchPackageMetaData   hostname: 'registry.npmjs.org',
25 silly fetchPackageMetaData   host: 'registry.npmjs.org',
25 silly fetchPackageMetaData   port: 443 }
26 silly rollbackFailedOptional Starting
27 silly rollbackFailedOptional Finishing
28 silly runTopLevelLifecycles Finishing
29 silly install printInstalled
30 verbose stack Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
30 verbose stack     at Object.exports._errnoException (util.js:1026:11)
30 verbose stack     at errnoException (dns.js:33:15)
30 verbose stack     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
31 verbose cwd C:\Users\1041356
32 error Windows_NT 6.1.7601
33 error argv "D:\\node.exe" "D:\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "jsbin"
34 error node v6.9.1
35 error npm  v3.10.8
36 error code EAI_AGAIN
37 error errno EAI_AGAIN
38 error syscall getaddrinfo
39 error getaddrinfo EAI_AGAIN registry.npmjs.org:443
40 error If you need help, you may report this error at:
40 error     <https://github.com/npm/npm/issues>
41 verbose exit [ 1, true ]

**Comment by legodude17** [comment]
Please check your internet connection.

**Comment by zkat** [comment]
Heya! This is quite likely either a regular networking issue, or something going wrong with your proxy configuration:

1. Make sure you have a working internet connection. Can you reach https://registry.npmjs.org on your browser? Can you reach other sites? If other sites are unreachable, this is not a problem with npm.
1. If your company has a process for domain whitelisting for developers, make sure https://registry.npmjs.org is a whitelisted domain.
1. On Windows, npm does not access proxies configured at the system level, so you need to configure them manually in order for npm to access them. Make sure [you have added the appropriate proxy configuration to `.npmrc`](https://jjasonclark.com/how-to-setup-node-behind-web-proxy/).
1. The proxy itself, on the server, might also have a configuration error. In this case, you'll need to work with your system administrator to verify that the proxy, and HTTPS, are configured correctly. You may test it by running regular HTTPS requests.
