### ISSUE TITLE
npm throws exceptions on unresolved env vars in config

### ISSUE THREAD

**Issue by maybeec** [npm/npm#15045]
#### I'm opening this issue because:
  - [x] npm is doing something I don't understand.

#### What's going wrong?

If a env variable is not set but requested in the .npmrc configuration, npm throws an error on every `npm` command:

```
Error: Failed to replace env in config: ${ANY_UNSET_VAR}
    at C:\Users\mbrunnli\AppData\Roaming\nvm\v6.9.1\node_modules\npm\lib\config\core.js:418:13
    at RegExp.[Symbol.replace] (native)
    at RegExp.[Symbol.replace] (native)
    at String.replace (native)
    at envReplace (C:\Users\mbrunnli\AppData\Roaming\nvm\v6.9.1\node_modules\npm\lib\config\core.js:414:12)
    at parseField (C:\Users\mbrunnli\AppData\Roaming\nvm\v6.9.1\node_modules\npm\lib\config\core.js:392:7)
    at C:\Users\mbrunnli\AppData\Roaming\nvm\v6.9.1\node_modules\npm\lib\config\core.js:335:17
    at Array.forEach (native)
    at Conf.add (C:\Users\mbrunnli\AppData\Roaming\nvm\v6.9.1\node_modules\npm\lib\config\core.js:334:23)
    at ConfigChain.addString (C:\Users\mbrunnli\AppData\Roaming\nvm\v6.9.1\node_modules\npm\node_modules\config-chain\index.js:244:8)
```

Especially for scoped registry I would like to set different environment variables dependent on my current project context. However, this implies, that not everytime all variables are set. So I would propose to not throw any exception and keep the unresolved template string. This would not harm anybody but will not block your work.

#### How can the CLI team reproduce the problem?

`npm config set @scope:registry \${ANY_UNSET_VAR}` whereas the backslash is just for escaping issues to not resolved the variable eagerly.

### supporting information:

 - `npm -v` prints:
3.10.8
 - `node -v` prints:
6.9.1
 - `npm config get registry` prints:

```
Error: Failed to replace env in config: ${ANY_UNSET_VAR}
    at C:\Users\mbrunnli\AppData\Roaming\nvm\v6.9.1\node_modules\npm\lib\config\core.js:418:13
    at RegExp.[Symbol.replace] (native)
    at RegExp.[Symbol.replace] (native)
    at String.replace (native)
    at envReplace (C:\Users\mbrunnli\AppData\Roaming\nvm\v6.9.1\node_modules\npm\lib\config\core.js:414:12)
    at parseField (C:\Users\mbrunnli\AppData\Roaming\nvm\v6.9.1\node_modules\npm\lib\config\core.js:392:7)
    at C:\Users\mbrunnli\AppData\Roaming\nvm\v6.9.1\node_modules\npm\lib\config\core.js:335:17
    at Array.forEach (native)
    at Conf.add (C:\Users\mbrunnli\AppData\Roaming\nvm\v6.9.1\node_modules\npm\lib\config\core.js:334:23)
    at ConfigChain.addString (C:\Users\mbrunnli\AppData\Roaming\nvm\v6.9.1\node_modules\npm\node_modules\config-chain\index.js:244:8)

Error: Failed to replace env in config: ${ANY_UNSET_VAR}
    at C:\Users\mbrunnli\AppData\Roaming\nvm\v6.9.1\node_modules\npm\lib\config\core.js:418:13
    at RegExp.[Symbol.replace] (native)
    at RegExp.[Symbol.replace] (native)
    at String.replace (native)
    at envReplace (C:\Users\mbrunnli\AppData\Roaming\nvm\v6.9.1\node_modules\npm\lib\config\core.js:414:12)
    at parseField (C:\Users\mbrunnli\AppData\Roaming\nvm\v6.9.1\node_modules\npm\lib\config\core.js:392:7)
    at C:\Users\mbrunnli\AppData\Roaming\nvm\v6.9.1\node_modules\npm\lib\config\core.js:335:17
    at Array.forEach (native)
    at Conf.add (C:\Users\mbrunnli\AppData\Roaming\nvm\v6.9.1\node_modules\npm\lib\config\core.js:334:23)
    at ConfigChain.addString (C:\Users\mbrunnli\AppData\Roaming\nvm\v6.9.1\node_modules\npm\node_modules\config-chain\index.js:244:8)
```
 - Windows, OS X/macOS, or Linux?:
Windows 7 x64
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [x] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
Pinging @zkat and @iarna for thier opinion.
