### ISSUE TITLE
webpack error after updated npm to 4.0,2

### ISSUE THREAD

**Issue by zzzgit** [npm/npm#15055]
![qq 20161129111107](https://cloud.githubusercontent.com/assets/1060733/20695086/8329883a-b624-11e6-9ef7-363525f2c24f.jpg)

when i update npm to 4.0,2,the build task by webpack failed 
before that i use npm 3.6.0
and how could i attach the log file?

**Comment by zzzgit** [comment]
```log
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\hotmail.com\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@4.0.2
3 info using node@v6.9.1
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle eopen-platform@1.0.0~predev: eopen-platform@1.0.0
6 silly lifecycle eopen-platform@1.0.0~predev: no script for predev, continuing
7 info lifecycle eopen-platform@1.0.0~dev: eopen-platform@1.0.0
8 verbose lifecycle eopen-platform@1.0.0~dev: unsafe-perm in lifecycle true
9 verbose lifecycle eopen-platform@1.0.0~dev: PATH: C:\Users\hotmail.com\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;D:\git\eopen-statics\node_modules\.bin;D:\Program Files (x86)\Python 3.5\Scripts\;D:\Program Files (x86)\Python 3.5\;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\ProgramData\Lenovo\ReadyApps;D:\Program Files\Git\cmd;D:\Program Files\TortoiseSVN\bin;D:\Program Files\TortoiseGit\bin;D:\Program Files\nodejs\;C:\Users\hotmail.com\AppData\Local\Microsoft\WindowsApps;C:\Users\hotmail.com\AppData\Local\atom\bin;C:\Users\hotmail.com\AppData\Roaming\npm
10 verbose lifecycle eopen-platform@1.0.0~dev: CWD: D:\git\eopen-statics
11 silly lifecycle eopen-platform@1.0.0~dev: Args: [ '/d /s /c',
11 silly lifecycle   'webpack-dev-server  --inline --hot --config build/webpack.dev.config.js --port 80  --host 0.0.0.0 --content-base ./dist' ]
12 silly lifecycle eopen-platform@1.0.0~dev: Returned: code: 1  signal: null
13 info lifecycle eopen-platform@1.0.0~dev: Failed to exec dev script
14 verbose stack Error: eopen-platform@1.0.0 dev: `webpack-dev-server  --inline --hot --config build/webpack.dev.config.js --port 80  --host 0.0.0.0 --content-base ./dist`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\hotmail.com\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\hotmail.com\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid eopen-platform@1.0.0
16 verbose cwd D:\git\eopen-statics
17 error Windows_NT 10.0.14393
18 error argv "D:\\Program Files\\nodejs\\node.exe" "C:\\Users\\hotmail.com\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
19 error node v6.9.1
20 error npm  v4.0.2
21 error code ELIFECYCLE
22 error eopen-platform@1.0.0 dev: `webpack-dev-server  --inline --hot --config build/webpack.dev.config.js --port 80  --host 0.0.0.0 --content-base ./dist`
22 error Exit status 1
23 error Failed at the eopen-platform@1.0.0 dev script 'webpack-dev-server  --inline --hot --config build/webpack.dev.config.js --port 80  --host 0.0.0.0 --content-base ./dist'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the eopen-platform package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     webpack-dev-server  --inline --hot --config build/webpack.dev.config.js --port 80  --host 0.0.0.0 --content-base ./dist
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs eopen-platform
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls eopen-platform
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by KenanY** [comment]
@zzzgit As the error log indicates, you are trying to open a new server on a port which is already in use by another server. This is not an issue with `npm` at all; all you need to do is either change the port of the new server to one which is not in use, or close the existing server that is using the port you want.
