### ISSUE TITLE
Problemas con npm install gulp-sass --save-dev

### ISSUE THREAD

**Issue by lucasramela** [npm/npm#15073]
Informe de error:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'gulp-sass',
1 verbose cli   '--save-dev' ]
2 info using npm@3.10.8
3 info using node@v6.9.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData gulp-sass
8 silly fetchNamedPackageData gulp-sass
9 silly mapToRegistry name gulp-sass
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'gulp-sass',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'gulp-sass',
12 silly mapToRegistry   name: 'gulp-sass',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/gulp-sass
14 verbose request uri https://registry.npmjs.org/gulp-sass
15 verbose request no auth needed
16 info attempt registry request try #1 at 12:30:10
17 verbose request id 8e5cc0bc3c9c9e5f
18 verbose etag W/"583c4af0-d90a"
19 verbose lastModified Mon, 28 Nov 2016 15:19:12 GMT
20 http request GET https://registry.npmjs.org/gulp-sass
21 http 304 https://registry.npmjs.org/gulp-sass
22 verbose headers { date: 'Wed, 30 Nov 2016 15:30:09 GMT',
22 verbose headers   via: '1.1 varnish',
22 verbose headers   'cache-control': 'max-age=300',
22 verbose headers   etag: 'W/"583c4af0-d90a"',
22 verbose headers   age: '49',
22 verbose headers   connection: 'keep-alive',
22 verbose headers   'x-served-by': 'cache-gru7126-GRU',
22 verbose headers   'x-cache': 'HIT',
22 verbose headers   'x-cache-hits': '2',
22 verbose headers   'x-timer': 'S1480519809.970162,VS0,VE0',
22 verbose headers   vary: 'Accept-Encoding' }
23 silly get cb [ 304,
23 silly get   { date: 'Wed, 30 Nov 2016 15:30:09 GMT',
23 silly get     via: '1.1 varnish',
23 silly get     'cache-control': 'max-age=300',
23 silly get     etag: 'W/"583c4af0-d90a"',
23 silly get     age: '49',
23 silly get     connection: 'keep-alive',
23 silly get     'x-served-by': 'cache-gru7126-GRU',
23 silly get     'x-cache': 'HIT',
23 silly get     'x-cache-hits': '2',
23 silly get     'x-timer': 'S1480519809.970162,VS0,VE0',
23 silly get     vary: 'Accept-Encoding' } ]
24 verbose etag https://registry.npmjs.org/gulp-sass from cache
25 verbose get saving gulp-sass to C:\Users\lucas\AppData\Roaming\npm-cache\registry.npmjs.org\gulp-sass\.cache.json
26 verbose correctMkdir C:\Users\lucas\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
27 silly install normalizeTree
28 silly loadCurrentTree Finishing
29 silly loadIdealTree Starting
30 silly install loadIdealTree
31 silly cloneCurrentTree Starting
32 silly install cloneCurrentTreeToIdealTree
33 silly cloneCurrentTree Finishing
34 silly loadShrinkwrap Starting
35 silly install loadShrinkwrap
36 silly loadShrinkwrap Finishing
37 silly loadAllDepsIntoIdealTree Starting
38 silly install loadAllDepsIntoIdealTree
39 silly rollbackFailedOptional Starting
40 silly rollbackFailedOptional Finishing
41 silly runTopLevelLifecycles Finishing
42 silly install printInstalled
43 verbose stack Error: Refusing to install gulp-sass as a dependency of itself
43 verbose stack     at checkSelf (C:\Program Files\nodejs\node_modules\npm\lib\install\validate-args.js:53:14)
43 verbose stack     at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
43 verbose stack     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
43 verbose stack     at chain (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
43 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install\validate-args.js:16:5
43 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:35
43 verbose stack     at Array.forEach (native)
43 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:11
43 verbose stack     at Array.forEach (native)
43 verbose stack     at asyncMap (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:51:8)
44 verbose cwd D:\2016\Desarrollo\Escuela Digital\css3-practica\gulp-sass
45 error Windows_NT 10.0.14393
46 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "gulp-sass" "--save-dev"
47 error node v6.9.1
48 error npm  v3.10.8
49 error code ENOSELF
50 error Refusing to install gulp-sass as a dependency of itself
51 error If you need help, you may report this error at:
51 error     <https://github.com/npm/npm/issues>
52 verbose exit [ 1, true ]

**Comment by lucasramela** [comment]
Ya lo solucioné! Tenia de nombre gulp-sass en mi package.json. Que ingenuo!
