### ISSUE TITLE
PACKAGE NOT FOUND when used from behind the proxy

### ISSUE THREAD

**Issue by lg061870** [npm/npm#15078]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I am behind a proxy -- I set all configs for PROXY and HTTPS-PROXY with the URI for the proxy (of course). Then when I try to use NPM to install a module (any) I get a response from the module repo saying PAGE NOT FOUND (html). I also set the registry to HTTP instead of HTTPS. 

When I type the URI directly on the browser I get the correct package json in the response.

One more thing: my proxy uri ends ":port/proxy=xxxx," 

#### How can the CLI team reproduce the problem?
[do this on a Window 10 machine]

1. Use a computer that's behind a firewall -- preferrably one a URI ending in :port/additional string
2. open command prompt (as administrator)
3. type: npm install [modulenamehere] -g

### supporting information:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'typings',
1 verbose cli   '--global' ]
2 info using npm@3.10.8
3 info using node@v6.9.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData typings
8 silly fetchNamedPackageData typings
9 silly mapToRegistry name typings
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry http://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'typings',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'typings',
12 silly mapToRegistry   name: 'typings',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri http://registry.npmjs.org/typings
14 verbose request uri http://registry.npmjs.org/typings
15 verbose request no auth needed
16 info attempt registry request try #1 at 11:16:30 AM
17 verbose request id 60e567215088f3f2
18 http request GET http://registry.npmjs.org/typings
19 http 404 http://registry.npmjs.org/typings
20 verbose bad json <html><head><title>Page Not Found</title><head><body>Sorry, but I couldn't find the object you requested.</body></html>
21 error registry error parsing json
22 verbose headers { 'transfer-encoding': 'chunked',
22 verbose headers   date: 'Wed, 30 Nov 2016 19:16:30 GMT',
22 verbose headers   'content-type': 'text/html; charset=UTF-8',
22 verbose headers   server: 'WebDefence/7.9.57267.100' }
23 silly get cb [ 404,
23 silly get   { 'transfer-encoding': 'chunked',
23 silly get     date: 'Wed, 30 Nov 2016 19:16:30 GMT',
23 silly get     'content-type': 'text/html; charset=UTF-8',
23 silly get     server: 'WebDefence/7.9.57267.100' } ]
24 silly fetchPackageMetaData SyntaxError: Unexpected token < in JSON at position 0
24 silly fetchPackageMetaData <html><head><title>Page Not Found</title><head><body>Sorry, but I couldn't find the object you requested.</body></html>
24 silly fetchPackageMetaData     at Object.parse (native)
24 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:237:23)
24 silly fetchPackageMetaData     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:210:14)
24 silly fetchPackageMetaData     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:187:22)
24 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
24 silly fetchPackageMetaData     at Request.emit (events.js:191:7)
24 silly fetchPackageMetaData     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1044:10)
24 silly fetchPackageMetaData     at emitOne (events.js:96:13)
24 silly fetchPackageMetaData     at Request.emit (events.js:188:7)
24 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:965:12)
24 silly fetchPackageMetaData  error for typings SyntaxError: Unexpected token < in JSON at position 0
24 silly fetchPackageMetaData <html><head><title>Page Not Found</title><head><body>Sorry, but I couldn't find the object you requested.</body></html>
24 silly fetchPackageMetaData     at Object.parse (native)
24 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:237:23)
24 silly fetchPackageMetaData     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:210:14)
24 silly fetchPackageMetaData     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:187:22)
24 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
24 silly fetchPackageMetaData     at Request.emit (events.js:191:7)
24 silly fetchPackageMetaData     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1044:10)
24 silly fetchPackageMetaData     at emitOne (events.js:96:13)
24 silly fetchPackageMetaData     at Request.emit (events.js:188:7)
24 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:965:12)
25 silly rollbackFailedOptional Starting
26 silly rollbackFailedOptional Finishing
27 silly runTopLevelLifecycles Finishing
28 silly install printInstalled
29 verbose stack SyntaxError: Unexpected token < in JSON at position 0
29 verbose stack <html><head><title>Page Not Found</title><head><body>Sorry, but I couldn't find the object you requested.</body></html>
29 verbose stack     at Object.parse (native)
29 verbose stack     at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:237:23)
29 verbose stack     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:210:14)
29 verbose stack     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:187:22)
29 verbose stack     at emitTwo (events.js:106:13)
29 verbose stack     at Request.emit (events.js:191:7)
29 verbose stack     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1044:10)
29 verbose stack     at emitOne (events.js:96:13)
29 verbose stack     at Request.emit (events.js:188:7)
29 verbose stack     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:965:12)
30 verbose cwd C:\Windows\system32
31 error Windows_NT 6.1.7601
32 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "typings" "--global"
33 error node v6.9.1
34 error npm  v3.10.8
35 error Unexpected token < in JSON at position 0
35 error <html><head><title>Page Not Found</title><head><body>Sorry, but I couldn't find the object you requested.</body></html>
36 error If you need help, you may report this error at:
36 error     <https://github.com/npm/npm/issues>
37 verbose exit [ 1, true ]

**Comment by lg061870** [comment]
I fixed the issue. It turns out that adding the PROXY and HTTPS-PROXY settings to the config file were actually muddling the waters. The original error was related to SSL that I simply fixed by setting the registry entry "npm config set registry http:\\[registryurlhere]" ...that is to a version without SSL/HTTPS and then set the 'strict-ssl' setting to false "npm config set strict-ssl false"
