### ISSUE TITLE
NPM install problem

### ISSUE THREAD

**Issue by Unkn09wn** [npm/npm#15105]
**Hi!**

Since yesterday I am trying to install the libraries in NodeJS but it is giving me the following error:
Anyone else has happened? I hope find the solution to this problem. :(

**PD: Sorry for my english.**

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'socket.io' ]
2 info using npm@3.10.9
3 info using node@v7.2.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData socket.io
8 silly fetchNamedPackageData socket.io
9 silly mapToRegistry name socket.io
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry http://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'socket.io',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'socket.io',
12 silly mapToRegistry   name: 'socket.io',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri http://registry.npmjs.org/socket.io
14 verbose request uri http://registry.npmjs.org/socket.io
15 verbose request no auth needed
16 info attempt registry request try #1 at 6:51:04 PM
17 verbose request id ef455d28a2e5a2b3
18 http request GET http://registry.npmjs.org/socket.io
19 info retry will retry, error on last attempt: Error: Invalid protocol: 200.43.77.19:
20 info attempt registry request try #2 at 6:51:14 PM
21 http request GET http://registry.npmjs.org/socket.io
22 info retry will retry, error on last attempt: Error: Invalid protocol: 200.43.77.19:
23 info attempt registry request try #3 at 6:52:14 PM
24 http request GET http://registry.npmjs.org/socket.io
25 silly fetchPackageMetaData Error: Invalid protocol: 200.43.77.19:
25 silly fetchPackageMetaData     at Request.init (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:460:31)
25 silly fetchPackageMetaData     at new Request (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:129:8)
25 silly fetchPackageMetaData     at request (C:\Program Files\nodejs\node_modules\npm\node_modules\request\index.js:55:10)
25 silly fetchPackageMetaData     at CachingRegistryClient.makeRequest (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:158:13)
25 silly fetchPackageMetaData     at C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:66:17
25 silly fetchPackageMetaData     at RetryOperation._fn (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\attempt.js:18:5)
25 silly fetchPackageMetaData     at Timeout._onTimeout (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\node_modules\retry\lib\retry_operation.js:68:10)
25 silly fetchPackageMetaData     at ontimeout (timers.js:365:14)
25 silly fetchPackageMetaData     at tryOnTimeout (timers.js:237:5)
25 silly fetchPackageMetaData     at Timer.listOnTimeout (timers.js:207:5)
25 silly fetchPackageMetaData  error for socket.io Error: Invalid protocol: 200.43.77.19:
25 silly fetchPackageMetaData     at Request.init (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:460:31)
25 silly fetchPackageMetaData     at new Request (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:129:8)
25 silly fetchPackageMetaData     at request (C:\Program Files\nodejs\node_modules\npm\node_modules\request\index.js:55:10)
25 silly fetchPackageMetaData     at CachingRegistryClient.makeRequest (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:158:13)
25 silly fetchPackageMetaData     at C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:66:17
25 silly fetchPackageMetaData     at RetryOperation._fn (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\attempt.js:18:5)
25 silly fetchPackageMetaData     at Timeout._onTimeout (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\node_modules\retry\lib\retry_operation.js:68:10)
25 silly fetchPackageMetaData     at ontimeout (timers.js:365:14)
25 silly fetchPackageMetaData     at tryOnTimeout (timers.js:237:5)
25 silly fetchPackageMetaData     at Timer.listOnTimeout (timers.js:207:5)
26 silly rollbackFailedOptional Starting
27 silly rollbackFailedOptional Finishing
28 silly runTopLevelLifecycles Finishing
29 silly install printInstalled
30 verbose stack Error: Invalid protocol: 200.43.77.19:
30 verbose stack     at Request.init (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:460:31)
30 verbose stack     at new Request (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:129:8)
30 verbose stack     at request (C:\Program Files\nodejs\node_modules\npm\node_modules\request\index.js:55:10)
30 verbose stack     at CachingRegistryClient.makeRequest (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:158:13)
30 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:66:17
30 verbose stack     at RetryOperation._fn (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\attempt.js:18:5)
30 verbose stack     at Timeout._onTimeout (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\node_modules\retry\lib\retry_operation.js:68:10)
30 verbose stack     at ontimeout (timers.js:365:14)
30 verbose stack     at tryOnTimeout (timers.js:237:5)
30 verbose stack     at Timer.listOnTimeout (timers.js:207:5)
31 verbose cwd C:\Users\germa
32 error Windows_NT 10.0.10240
33 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "socket.io"
34 error node v7.2.0
35 error npm  v3.10.9
36 error Invalid protocol: 200.43.77.19:
37 error If you need help, you may report this error at:
37 error     <https://github.com/npm/npm/issues>
38 verbose exit [ 1, true ]
```

**Comment by zkat** [comment]
What does your proxy configuration look like? It seems like you've messed up the syntax for it a bit?
