### ISSUE TITLE
Cannot find module '/usr/local/lib/node_modules/npm/bin/node_modules/npm/bin/npm-cli.js'

### ISSUE THREAD

**Issue by JasonFang93** [npm/npm#15115]
Hi!
Can i use npm as local package in my node cli project?
Just like below:

```javascript
const npmPath = path.join(__dirname, '../../node_modules/npm/bin/npm-cli');
child_process.spawn('node', [npmPath, 'install']);
...
```
but there is a error :
```
module.js:327
    throw err;
    ^

Error: Cannot find module '/usr/local/lib/node_modules/npm/bin/node_modules/npm/bin/npm-cli.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```
[like this issues](https://github.com/npm/npm/issues/5176)
`echo $path` => `/Users/qitmac000358/.nvm/versions/node/v5.12.0/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin`
`type -a npm` => 
```
npm is /Users/qitmac000358/.nvm/versions/node/v5.12.0/bin/npm
npm is /usr/local/bin/npm
```

**Comment by JasonFang93** [comment]
Hello @zkat , could you know the cause of the error? I have gotten into the trouble for a week, and don't find the cause of problem.

**Comment by zkat** [comment]
@JasonFang93 If you install npm as a direct dependency of your project, add `node_modules/.bin` to your application `$PATH`, then just do `child_process.spawn('npm install', ...)`. That should just work.
