### ISSUE TITLE
No compatible version found: i@0.3.2

### ISSUE THREAD

**Issue by AravindSwarana** [npm/npm#15120]
Hi all,
I am new to npm , I have started using it from couple of weeks. I am setting up one of our old projects in our organization. While I tried npm install. I have got following issue.
I am using windows 7 . I am really confusing with the error message . I can figure out that there is a versioning issue but the problem  which software is causing the issue and how to solve it . 
Log :

1806 silly runTopLevelLifecycles Starting
1807 silly runTopLevelLifecycles Finishing
1808 silly install printInstalled
1809 verbose stack Error: No compatible version found: i@0.3.2
1809 verbose stack Valid install targets:
1809 verbose stack 0.3.5, 0.3.4, 0.3.3, 0.3.1, 0.3.0, 0.2.0
1809 verbose stack
1809 verbose stack     at pickVersionFromRegistryDocument (C:\Program Files\nodejs\node_modules\npm\lib\fetch-package-metadata.js:170:16)
1809 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\iferr\index.js:13:50
1809 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\utils\pulse-till-done.js:20:8
1809 verbose stack     at saved (C:\Program Files\nodejs\node_modules\npm\lib\cache\caching-client.js:174:7)
1809 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:210:7
1809 verbose stack     at FSReqWrap.oncomplete (fs.js:123:15)
1810 verbose cwd C:\Users\user\app\service-gateway\src\main\config\ft
1811 error Windows_NT 6.1.7601
1812 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
1813 error node v6.3.0
1814 error npm  v3.10.3
1815 error No compatible version found: i@0.3.2
1815 error Valid install targets:
1815 error 0.3.5, 0.3.4, 0.3.3, 0.3.1, 0.3.0, 0.2.0

**package.json**

{
  "name": "service-gateway",
  "version": "1.0.0",
  "private": true,
  "dependencies": {},
  "devDependencies": {
    "grunt": "0.4.2",
    "grunt-cli": "0.1.13",
    "grunt-concurrent": "0.5.0",
    "grunt-connect-rewrite": "0.2.1",
    "grunt-contrib-clean": "0.5.0",
    "grunt-contrib-connect": "0.7.1",
    "grunt-contrib-copy": "0.5.0",
    "grunt-contrib-cssmin": "0.10.0",
    "grunt-contrib-jshint": "0.8.0",
    "grunt-contrib-requirejs": "0.4.4",
    "grunt-contrib-sass": "0.7.3",
    "grunt-contrib-watch": "0.5.3",
    "json-proxy": "0.1.2",
    "load-grunt-tasks": "0.4.0",
    "mocha": "1.17.1",
    "requirejs": "2.1.11"
  },
  "scripts": {
    "test": "./node_modules/.bin/grunt"
  }
}

**Comment by AravindSwarana** [comment]
Solved the issue from this
[link](http://stackoverflow.com/questions/32463020/npm-err-version-not-found-i0-3-2-error)

Thank you
