### ISSUE TITLE
npm unpublish not working

### ISSUE THREAD

**Issue by emanuelbuholzer** [npm/npm#15146]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I can't unpublish my module when I run `npm unpublish webstorage-adapter --force`.

Thanks for any help! :)

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'unpublish',
1 verbose cli   'webstorage-adapter',
1 verbose cli   '--force' ]
2 info using npm@3.10.3
3 info using node@v6.3.1
4 warn using --force I sure hope you know what you are doing.
5 silly unpublish args[0] webstorage-adapter
6 silly unpublish thing Result {
6 silly unpublish   raw: 'webstorage-adapter',
6 silly unpublish   scope: null,
6 silly unpublish   escapedName: 'webstorage-adapter',
6 silly unpublish   name: 'webstorage-adapter',
6 silly unpublish   rawSpec: '',
6 silly unpublish   spec: 'latest',
6 silly unpublish   type: 'tag' }
7 verbose getPublishConfig null
8 silly ls normalized webstorage-adapter
9 silly gentlyRm C:\Users\Emanu\AppData\Roaming\npm-cache\webstorage-adapter is being purged
10 verbose gentlyRm don't care about contents; nuking C:\Users\Emanu\AppData\Roaming\npm-cache\webstorage-adapter
11 silly mapToRegistry name webstorage-adapter
12 silly mapToRegistry using default registry
13 silly mapToRegistry registry https://registry.npmjs.org/
14 silly mapToRegistry data Result {
14 silly mapToRegistry   raw: 'webstorage-adapter',
14 silly mapToRegistry   scope: null,
14 silly mapToRegistry   escapedName: 'webstorage-adapter',
14 silly mapToRegistry   name: 'webstorage-adapter',
14 silly mapToRegistry   rawSpec: '',
14 silly mapToRegistry   spec: 'latest',
14 silly mapToRegistry   type: 'tag' }
15 silly mapToRegistry uri https://registry.npmjs.org/webstorage-adapter
16 verbose get GET as part of write; not caching result
17 verbose request uri https://registry.npmjs.org/webstorage-adapter?write=true
18 verbose request no auth needed
19 info attempt registry request try #1 at 22:04:31
20 verbose request using bearer token for auth
21 verbose request id bb86b503776217a7
22 http request GET https://registry.npmjs.org/webstorage-adapter?write=true
23 http 200 https://registry.npmjs.org/webstorage-adapter?write=true
24 verbose headers { server: 'CouchDB/1.6.1 (Erlang OTP/R16B03)',
24 verbose headers   'content-type': 'application/json',
24 verbose headers   etag: '"57ddb433-828"',
24 verbose headers   'content-encoding': 'gzip',
24 verbose headers   'cache-control': 'max-age=0',
24 verbose headers   'transfer-encoding': 'chunked',
24 verbose headers   'accept-ranges': 'bytes',
24 verbose headers   date: 'Mon, 05 Dec 2016 21:04:19 GMT',
24 verbose headers   via: '1.1 varnish',
24 verbose headers   connection: 'keep-alive',
24 verbose headers   'x-served-by': 'cache-fra1247-FRA',
24 verbose headers   'x-cache': 'MISS',
24 verbose headers   'x-cache-hits': '0',
24 verbose headers   'x-timer': 'S1480971858.781067,VS0,VE438',
24 verbose headers   vary: 'Accept-Encoding' }
25 silly get cb [ 200,
25 silly get   { server: 'CouchDB/1.6.1 (Erlang OTP/R16B03)',
25 silly get     'content-type': 'application/json',
25 silly get     etag: '"57ddb433-828"',
25 silly get     'content-encoding': 'gzip',
25 silly get     'cache-control': 'max-age=0',
25 silly get     'transfer-encoding': 'chunked',
25 silly get     'accept-ranges': 'bytes',
25 silly get     date: 'Mon, 05 Dec 2016 21:04:19 GMT',
25 silly get     via: '1.1 varnish',
25 silly get     connection: 'keep-alive',
25 silly get     'x-served-by': 'cache-fra1247-FRA',
25 silly get     'x-cache': 'MISS',
25 silly get     'x-cache-hits': '0',
25 silly get     'x-timer': 'S1480971858.781067,VS0,VE438',
25 silly get     vary: 'Accept-Encoding' } ]
26 verbose get saving webstorage-adapter to C:\Users\Emanu\AppData\Roaming\npm-cache\registry.npmjs.org\webstorage-adapter_3Fwrite_3Dtrue\.cache.json
27 verbose correctMkdir C:\Users\Emanu\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
28 info unpublish No version specified, removing all
29 verbose request uri https://registry.npmjs.org/webstorage-adapter/-rev/1-062e8429973318175e46c73ead14a9ec
30 verbose request sending authorization for write operation
31 info attempt registry request try #1 at 22:04:32
32 verbose request using bearer token for auth
33 http request DELETE https://registry.npmjs.org/webstorage-adapter/-rev/1-062e8429973318175e46c73ead14a9ec
34 http 400 https://registry.npmjs.org/webstorage-adapter/-rev/1-062e8429973318175e46c73ead14a9ec
35 verbose headers { 'content-type': 'application/json',
35 verbose headers   'cache-control': 'max-age=300',
35 verbose headers   'content-length': '17',
35 verbose headers   'accept-ranges': 'bytes',
35 verbose headers   date: 'Mon, 05 Dec 2016 21:04:20 GMT',
35 verbose headers   via: '1.1 varnish',
35 verbose headers   connection: 'keep-alive',
35 verbose headers   'x-served-by': 'cache-fra1247-FRA',
35 verbose headers   'x-cache': 'MISS',
35 verbose headers   'x-cache-hits': '0',
35 verbose headers   'x-timer': 'S1480971859.305154,VS0,VE954',
35 verbose headers   vary: 'Accept-Encoding' }
36 verbose request invalidating C:\Users\Emanu\AppData\Roaming\npm-cache\registry.npmjs.org\webstorage-adapter on DELETE
37 verbose stack Error: Registry returned 400 for DELETE on https://registry.npmjs.org/webstorage-adapter/-rev/1-062e8429973318175e46c73ead14a9ec
37 verbose stack     at makeError (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:264:12)
37 verbose stack     at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:242:14)
37 verbose stack     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:172:14)
37 verbose stack     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:200:22)
37 verbose stack     at emitTwo (events.js:106:13)
37 verbose stack     at Request.emit (events.js:191:7)
37 verbose stack     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1067:10)
37 verbose stack     at emitOne (events.js:101:20)
37 verbose stack     at Request.emit (events.js:188:7)
37 verbose stack     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:988:12)
38 verbose statusCode 400
39 verbose pkgid webstorage-adapter
40 verbose cwd C:\Users\Emanu\Desktop\web
41 error Windows_NT 10.0.14393
42 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "unpublish" "webstorage-adapter" "--force"
43 error node v6.3.1
44 error npm  v3.10.3
45 error code E400
46 error Registry returned 400 for DELETE on https://registry.npmjs.org/webstorage-adapter/-rev/1-062e8429973318175e46c73ead14a9ec
47 error If you need help, you may report this error at:
47 error     <https://github.com/npm/npm/issues>
48 verbose exit [ 1, true ]

```

**Comment by KenanY** [comment]
@emanuelbuholzer Contact `support@npmjs.com` for unpublishing.
