### ISSUE TITLE
Cannot unpublish a package

### ISSUE THREAD

**Issue by acrazing** [npm/npm#15217]
I try to unpublish package `mileyy`, but I got the follow error:

```bash
+ npm unpublish mileyy -f --verbose
npm info it worked if it ends with ok
npm verb cli [ '/usr/local/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'unpublish',
npm verb cli   'mileyy',
npm verb cli   '-f',
npm verb cli   '--verbose' ]
npm info using npm@3.6.0
npm info using node@v5.6.0
npm WARN using --force I sure hope you know what you are doing.
npm verb getPublishConfig null
npm verb gentlyRm don't care about contents; nuking /Users/acrazing/.npm/mileyy
npm verb get GET as part of write; not caching result
npm verb request uri https://registry.npmjs.org/mileyy?write=true
npm verb request no auth needed
npm info attempt registry request try #1 at 14:16:19
npm verb request using bearer token for auth
npm verb request id 3b2b011f8ab6496d
npm http request GET https://registry.npmjs.org/mileyy?write=true
npm http 200 https://registry.npmjs.org/mileyy?write=true
npm verb headers { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
npm verb headers   'content-type': 'application/json',
npm verb headers   etag: '"5850e345-aa1"',
npm verb headers   'content-encoding': 'gzip',
npm verb headers   'cache-control': 'max-age=0',
npm verb headers   'transfer-encoding': 'chunked',
npm verb headers   'accept-ranges': 'bytes',
npm verb headers   date: 'Wed, 14 Dec 2016 06:16:19 GMT',
npm verb headers   via: '1.1 varnish',
npm verb headers   connection: 'keep-alive',
npm verb headers   'x-served-by': 'cache-itm7420-ITM',
npm verb headers   'x-cache': 'MISS',
npm verb headers   'x-cache-hits': '0',
npm verb headers   'x-timer': 'S1481696179.622777,VS0,VE154',
npm verb headers   vary: 'Accept-Encoding' }
npm verb get saving mileyy to /Users/acrazing/.npm/registry.npmjs.org/mileyy_3Fwrite_3Dtrue/.cache.json
npm verb correctMkdir /Users/acrazing/.npm correctMkdir not in flight; initializing
npm info unpublish No version specified, removing all
npm verb request uri https://registry.npmjs.org/mileyy/-rev/3-ca7b23abeecbd2fe06df4833525414a6
npm verb request sending authorization for write operation
npm info attempt registry request try #1 at 14:16:19
npm verb request using bearer token for auth
npm http request DELETE https://registry.npmjs.org/mileyy/-rev/3-ca7b23abeecbd2fe06df4833525414a6
npm http 400 https://registry.npmjs.org/mileyy/-rev/3-ca7b23abeecbd2fe06df4833525414a6
npm verb headers { 'content-type': 'application/json',
npm verb headers   'cache-control': 'max-age=300',
npm verb headers   'content-length': '17',
npm verb headers   'accept-ranges': 'bytes',
npm verb headers   date: 'Wed, 14 Dec 2016 06:16:20 GMT',
npm verb headers   via: '1.1 varnish',
npm verb headers   connection: 'keep-alive',
npm verb headers   'x-served-by': 'cache-itm7424-ITM',
npm verb headers   'x-cache': 'MISS',
npm verb headers   'x-cache-hits': '0',
npm verb headers   'x-timer': 'S1481696180.038046,VS0,VE621',
npm verb headers   vary: 'Accept-Encoding' }
npm verb request invalidating /Users/acrazing/.npm/registry.npmjs.org/mileyy on DELETE
npm verb stack Error: Registry returned 400 for DELETE on https://registry.npmjs.org/mileyy/-rev/3-ca7b23abeecbd2fe06df4833525414a6
npm verb stack     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
npm verb stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:242:14)
npm verb stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
npm verb stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:198:22)
npm verb stack     at emitTwo (events.js:100:13)
npm verb stack     at Request.emit (events.js:185:7)
npm verb stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1035:10)
npm verb stack     at emitOne (events.js:95:20)
npm verb stack     at Request.emit (events.js:182:7)
npm verb stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:962:12)
npm verb statusCode 400
npm verb pkgid mileyy
npm verb cwd ~/mileyy
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "unpublish" "mileyy" "-f" "--verbose"
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0
npm ERR! code E400

npm ERR! Registry returned 400 for DELETE on https://registry.npmjs.org/mileyy/-rev/3-ca7b23abeecbd2fe06df4833525414a6
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm verb exit [ 1, true ]

npm ERR! Please include the following file with any support request:
npm ERR!     ~/mileyy/npm-debug.log
```

**Comment by emanuelbuholzer** [comment]
@acrazing I had the same Issue [here](https://github.com/npm/npm/issues/15146). 

Please contact `support@npmjs.com` for unpublishing.

**Comment by acrazing** [comment]
What is the reason?

**Comment by KenanY** [comment]
@acrazing See: <http://blog.npmjs.org/post/141905368000/changes-to-npms-unpublish-policy>
