### ISSUE TITLE
npm install --global uninstall gives Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by SimenB** [npm/npm#15239]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
`npm install --global uninstall` gives `Cannot convert undefined or null to object`
The `uninstall` package doesn't exist (yeah, I goofed up when trying to uninstall something 😭 ), but trying to install some other non-existant package gives a different error (`TypeError: Cannot read property 'path' of null`)

#### How can the CLI team reproduce the problem?

```sh-session
$ npm install --global uninstall --verbose
npm info it worked if it ends with ok
npm verb cli [ '/Users/simbekkh/.nvm/versions/node/v6.9.1/bin/node',
npm verb cli   '/Users/simbekkh/.nvm/versions/node/v6.9.1/bin/npm',
npm verb cli   'install',
npm verb cli   '--global',
npm verb cli   'uninstall',
npm verb cli   '--verbose' ]
npm info using npm@4.0.5
npm info using node@v6.9.1
npm verb request uri https://registry.npmjs.org/uninstall
npm verb request no auth needed
npm info attempt registry request try #1 at 11:50:29 AM
npm verb request using bearer token for auth
npm verb request id 8818f7478f9ebce1
npm verb etag W/"56a112dd-1c3"
npm verb lastModified Thu, 21 Jan 2016 17:18:21 GMT
npm http request GET https://registry.npmjs.org/uninstall
npm http 304 https://registry.npmjs.org/uninstall
npm verb headers { server: 'nginx/1.10.1',
npm verb headers   'last-modified': 'Thu, 21 Jan 2016 17:18:21 GMT',
npm verb headers   etag: '"56a112dd-1c3"',
npm verb headers   'cache-control': 'max-age=300',
npm verb headers   'accept-ranges': 'bytes',
npm verb headers   date: 'Fri, 16 Dec 2016 10:50:29 GMT',
npm verb headers   via: '1.1 varnish',
npm verb headers   connection: 'keep-alive',
npm verb headers   'x-served-by': 'cache-bma7035-BMA',
npm verb headers   'x-cache': 'MISS',
npm verb headers   'x-cache-hits': '0',
npm verb headers   'x-timer': 'S1481885428.996654,VS0,VE20',
npm verb headers   vary: 'Accept-Encoding' }
npm verb etag https://registry.npmjs.org/uninstall from cache
npm verb get saving uninstall to /Users/simbekkh/.npm/registry.npmjs.org/uninstall/.cache.json
npm verb correctMkdir /Users/simbekkh/.npm correctMkdir not in flight; initializing
npm verb stack TypeError: Cannot convert undefined or null to object
npm verb stack     at pickVersionFromRegistryDocument (/Users/simbekkh/.nvm/versions/node/v6.9.1/lib/node_modules/npm/lib/fetch-package-metadata.js:125:29)
npm verb stack     at /Users/simbekkh/.nvm/versions/node/v6.9.1/lib/node_modules/npm/node_modules/iferr/index.js:13:50
npm verb stack     at /Users/simbekkh/.nvm/versions/node/v6.9.1/lib/node_modules/npm/lib/utils/pulse-till-done.js:20:8
npm verb stack     at saved (/Users/simbekkh/.nvm/versions/node/v6.9.1/lib/node_modules/npm/lib/cache/caching-client.js:174:7)
npm verb stack     at /Users/simbekkh/.nvm/versions/node/v6.9.1/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:261:18
npm verb stack     at FSReqWrap.oncomplete (fs.js:123:15)
npm verb cwd /Users/simbekkh/repos/preact-doodling/preact
npm ERR! Darwin 16.1.0
npm ERR! argv "/Users/simbekkh/.nvm/versions/node/v6.9.1/bin/node" "/Users/simbekkh/.nvm/versions/node/v6.9.1/bin/npm" "install" "--global" "uninstall" "--verbose"
npm ERR! node v6.9.1
npm ERR! npm  v4.0.5

npm ERR! Cannot convert undefined or null to object
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm verb exit [ 1, true ]

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/simbekkh/repos/preact-doodling/preact/npm-debug.log
```

```sh-session
$ npm install --global what-even-is-this-life --verbose
npm info it worked if it ends with ok
npm verb cli [ '/Users/simbekkh/.nvm/versions/node/v6.9.1/bin/node',
npm verb cli   '/Users/simbekkh/.nvm/versions/node/v6.9.1/bin/npm',
npm verb cli   'install',
npm verb cli   '--global',
npm verb cli   'what-even-is-this-life',
npm verb cli   '--verbose' ]
npm info using npm@4.0.5
npm info using node@v6.9.1
npm verb request uri https://registry.npmjs.org/what-even-is-this-life
npm verb request no auth needed
npm info attempt registry request try #1 at 11:51:16 AM
npm verb request using bearer token for auth
npm verb request id 86ad10286063c038
npm http request GET https://registry.npmjs.org/what-even-is-this-life
npm http 404 https://registry.npmjs.org/what-even-is-this-life
npm verb headers { 'content-type': 'application/json',
npm verb headers   'cache-control': 'max-age=0',
npm verb headers   'content-length': '2',
npm verb headers   'accept-ranges': 'bytes',
npm verb headers   date: 'Fri, 16 Dec 2016 10:51:16 GMT',
npm verb headers   via: '1.1 varnish',
npm verb headers   connection: 'keep-alive',
npm verb headers   'x-served-by': 'cache-bma7033-BMA',
npm verb headers   'x-cache': 'MISS',
npm verb headers   'x-cache-hits': '0',
npm verb headers   'x-timer': 'S1481885475.957370,VS0,VE852',
npm verb headers   vary: 'Accept-Encoding' }
npm verb stack TypeError: Cannot read property 'path' of null
npm verb stack     at Object.Installer.rollbackFailedOptional (/Users/simbekkh/.nvm/versions/node/v6.9.1/lib/node_modules/npm/lib/install.js:505:29)
npm verb stack     at Array.<anonymous> (/Users/simbekkh/.nvm/versions/node/v6.9.1/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
npm verb stack     at LOOP (/Users/simbekkh/.nvm/versions/node/v6.9.1/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
npm verb stack     at /Users/simbekkh/.nvm/versions/node/v6.9.1/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
npm verb stack     at /Users/simbekkh/.nvm/versions/node/v6.9.1/lib/node_modules/npm/lib/install.js:331:5
npm verb stack     at Array.<anonymous> (/Users/simbekkh/.nvm/versions/node/v6.9.1/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
npm verb stack     at LOOP (/Users/simbekkh/.nvm/versions/node/v6.9.1/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
npm verb stack     at chain (/Users/simbekkh/.nvm/versions/node/v6.9.1/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
npm verb stack     at /Users/simbekkh/.nvm/versions/node/v6.9.1/lib/node_modules/npm/lib/install.js:288:5
npm verb stack     at /Users/simbekkh/.nvm/versions/node/v6.9.1/lib/node_modules/npm/node_modules/slide/lib/chain.js:16:22
npm verb cwd /Users/simbekkh/repos/preact-doodling/preact
npm ERR! Darwin 16.1.0
npm ERR! argv "/Users/simbekkh/.nvm/versions/node/v6.9.1/bin/node" "/Users/simbekkh/.nvm/versions/node/v6.9.1/bin/npm" "install" "--global" "what-even-is-this-life" "--verbose"
npm ERR! node v6.9.1
npm ERR! npm  v4.0.5

npm ERR! Cannot read property 'path' of null
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm verb exit [ 1, true ]

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/simbekkh/repos/preact-doodling/preact/npm-debug.log
```

### supporting information:

 - `npm -v` prints: v4.0.5
 - `node -v` prints: v6.9.1
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: macOS
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by fhalde** [comment]
What package is uninstall? I cant find it in the registry.
Looks like https://github.com/npm/npm/issues/14651 to me

**Comment by SimenB** [comment]
I did write
> The `uninstall` package doesn't exist

But yes, it seems I stumbled upon first #14651 then #15227

**Comment by fhalde** [comment]
whoops sorry didn't see that @SimenB
