### ISSUE TITLE
`npm search jquery` failed cause no .cache.json

### ISSUE THREAD

**Issue by wisetc** [npm/npm#15254]
#### I'm opening this issue because:

  I want to install jquery defined file for typescript using typings cli. But it turned out ` No search sources available`. So I tryed `npm search` failed the same with the following npm-debug.log.

``` log
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\zhi\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'search',
1 verbose cli   'jquery' ]
2 info using npm@4.0.3
3 info using node@v6.9.1
4 silly mapToRegistry name -/all
5 silly mapToRegistry using default registry
6 silly mapToRegistry registry https://registry.npm.taobao.org/
7 silly mapToRegistry data Result {
7 silly mapToRegistry   raw: '-/all',
7 silly mapToRegistry   scope: null,
7 silly mapToRegistry   escapedName: null,
7 silly mapToRegistry   name: null,
7 silly mapToRegistry   rawSpec: '-/all',
7 silly mapToRegistry   spec: '-/all',
7 silly mapToRegistry   type: 'local' }
8 silly mapToRegistry uri https://registry.npm.taobao.org/-/all
9 verbose all-package-metadata creating entry stream from local cache
10 verbose all-package-metadata C:\Users\zhi\AppData\Roaming\npm-cache\registry.npm.taobao.org\-\all\.cache.json
11 silly search searching packages
12 warn Failed to read search cache. Rebuilding
13 silly all-package-metadata Error: ENOENT: no such file or directory, stat 'C:\Users\zhi\AppData\Roaming\npm-cache\registry.npm.taobao.org\-\all\.cache.json'
13 silly all-package-metadata     at Error (native)
13 silly all-package-metadata  cache read error:  { Error: ENOENT: no such file or directory, stat 'C:\Users\zhi\AppData\Roaming\npm-cache\registry.npm.taobao.org\-\all\.cache.json'
13 silly all-package-metadata     at Error (native)
13 silly all-package-metadata   errno: -4058,
13 silly all-package-metadata   code: 'ENOENT',
13 silly all-package-metadata   syscall: 'stat',
13 silly all-package-metadata   path: 'C:\\Users\\zhi\\AppData\\Roaming\\npm-cache\\registry.npm.taobao.org\\-\\all\\.cache.json' }
14 verbose all-package-metadata creating remote entry stream
15 warn Building the local index for the first time, please be patient
16 verbose all-package-metadata No cached data: requesting full metadata db
17 verbose request uri https://registry.npm.taobao.org/-/all
18 verbose request no auth needed
19 info attempt registry request try #1 at 10:08:15
20 verbose request id 6b017d3e328ce4a5
21 http request GET https://registry.npm.taobao.org/-/all
22 silly all-package-metadata request stream opened, code: 200
23 silly all-package-metadata extracting latest
24 silly all-package-metadata got first stream entry for entry-update-stream true
25 verbose stack Error: No search sources available
25 verbose stack     at C:\Users\zhi\AppData\Roaming\npm\node_modules\npm\lib\search\all-package-metadata.js:71:19
25 verbose stack     at f (C:\Users\zhi\AppData\Roaming\npm\node_modules\npm\node_modules\once\once.js:25:25)
25 verbose stack     at Pumpify.<anonymous> (C:\Users\zhi\AppData\Roaming\npm\node_modules\npm\lib\search\all-package-metadata.js:204:7)
25 verbose stack     at Pumpify.g (events.js:291:16)
25 verbose stack     at emitOne (events.js:96:13)
25 verbose stack     at Pumpify.emit (events.js:188:7)
25 verbose stack     at Pumpify.Readable.read (C:\Users\zhi\AppData\Roaming\npm\node_modules\npm\node_modules\readable-stream\lib\_stream_readable.js:391:26)
25 verbose stack     at flow (C:\Users\zhi\AppData\Roaming\npm\node_modules\npm\node_modules\readable-stream\lib\_stream_readable.js:739:34)
25 verbose stack     at resume_ (C:\Users\zhi\AppData\Roaming\npm\node_modules\npm\node_modules\readable-stream\lib\_stream_readable.js:722:3)
25 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:74:11)
26 verbose cwd C:\lab\_components\magnify
27 error Windows_NT 10.0.14393
28 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\zhi\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "search" "jquery"
29 error node v6.9.1
30 error npm  v4.0.3
31 error No search sources available
32 error If you need help, you may report this error at:
32 error     <https://github.com/npm/npm/issues>
33 verbose exit [ 1, true ]
```

I think this may due to using of cnpm which is a mirror of npm provided by taobao in China, but I don't konw how to fix it.

Below is my configuration

```
$ npm config list -l
; cli configs
long = true
scope = ""
user-agent = "npm/4.0.3 node/v6.9.1 win32 x64"

; userconfig C:\Users\zhi\.npmrc
disturl = "https://npm.taobao.org/dist"
registry = "https://registry.npm.taobao.org/"

; builtin config undefined
prefix = "C:\\Users\\zhi\\AppData\\Roaming\\npm"

; default values
access = null
also = null
always-auth = false
bin-links = true
browser = null
ca = null
cache = "C:\\Users\\zhi\\AppData\\Roaming\\npm-cache"
cache-lock-retries = 10
cache-lock-stale = 60000
cache-lock-wait = 10000
cache-max = null
cache-min = 10
cafile = undefined
cert = null
color = true
depth = null
description = true
dev = false
dry-run = false
editor = "notepad.exe"
engine-strict = false
fetch-retries = 2
fetch-retry-factor = 10
fetch-retry-maxtimeout = 60000
fetch-retry-mintimeout = 10000
force = false
git = "git"
git-tag-version = true
global = false
global-style = false
globalconfig = "C:\\Users\\zhi\\AppData\\Roaming\\npm\\etc\\npmrc"
globalignorefile = "C:\\Users\\zhi\\AppData\\Roaming\\npm\\etc\\npmignore"
group = 0
heading = "npm"
https-proxy = null
if-present = false
ignore-scripts = false
init-author-email = ""
init-author-name = ""
init-author-url = ""
init-license = "ISC"
init-module = "C:\\Users\\zhi\\.npm-init.js"
init-version = "1.0.0"
json = false
key = null
legacy-bundling = false
link = false
local-address = undefined
loglevel = "warn"
; long = false (overridden)
maxsockets = 50
message = "%s"
node-version = "6.9.1"
onload-script = null
only = null
optional = true
parseable = false
; prefix = "C:\\Program Files\\nodejs" (overridden)
production = false
progress = true
proprietary-attribs = true
proxy = null
rebuild-bundle = true
; registry = "https://registry.npmjs.org/" (overridden)
rollback = true
save = false
save-bundle = false
save-dev = false
save-exact = false
save-optional = false
save-prefix = "^"
scope = ""
scripts-prepend-node-path = "warn-only"
searchexclude = null
searchopts = ""
searchstaleness = 900
shell = "C:\\WINDOWS\\system32\\cmd.exe"
shrinkwrap = true
sign-git-tag = false
strict-ssl = true
tag = "latest"
tag-version-prefix = "v"
tmp = "C:\\Users\\zhi\\AppData\\Local\\Temp"
umask = 0
unicode = false
unsafe-perm = true
usage = false
user = 0
; user-agent = "npm/{npm-version} node/{node-version} {platform} {arch}" (overridden)
userconfig = "C:\\Users\\zhi\\.npmrc"
version = false
versions = false
viewer = "browser"
```

**Comment by wisetc** [comment]
Solved by run `npm config delete registry` and `npm cache clean`
