### ISSUE TITLE
NPM warn/error - git config

### ISSUE THREAD

**Issue by ORESoftware** [npm/npm#15265]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I see this NPM warning. I am not calling this code, and am wondering if NPM knows anything about it. It's probably not something directly related to NPM, but I feel like there's a 20% chance that there is; I do know that NPM does do some git things.

```
npm WARN addRemoteGit Error: Command failed: git config --get remote.origin.url
npm WARN addRemoteGit 
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:202:12)
npm WARN addRemoteGit     at emitTwo (events.js:100:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:185:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:850:16)
npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:323:11)
npm WARN addRemoteGit     at emitOne (events.js:90:13)
npm WARN addRemoteGit     at Socket.emit (events.js:182:7)
npm WARN addRemoteGit     at Pipe._onclose (net.js:484:12)
npm WARN addRemoteGit  oresoftware/suman#dev resetting remote /home/docker/.npm/_git-remotes/git-github-com-oresoftware-suman-git-dev-96eda782 because of error: { [Error: Command failed: git config --get remote.origin.url
npm WARN addRemoteGit ]
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git config --get remote.origin.url' }
npm ERR! git clone --template=/home/docker/.npm/_git-remotes/_templates --mirror git://github.com/oresoftware/suman.git /home/docker/.npm/_git-remotes/git-github-com-oresoftware-suman-git-dev-96eda782: Cloning into bare repository '/home/docker/.npm/_git-remotes/git-github-com-oresoftware-suman-git-dev-96eda782'...
npm ERR! git clone --template=/home/docker/.npm/_git-remotes/_templates --mirror git://github.com/oresoftware/suman.git /home/docker/.npm/_git-remotes/git-github-com-oresoftware-suman-git-dev-96eda782: fatal: Unable to read current working directory: No such file or directory
npm ERR! git clone --template=/home/docker/.npm/_git-remotes/_templates --mirror git://github.com/oresoftware/suman.git /home/docker/.npm/_git-remotes/git-github-com-oresoftware-suman-git-dev-96eda782: fatal: index-pack failed
/home/docker/three
npm ERR! git rev-list -n1 dev: fatal: ambiguous argument 'dev': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 dev: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 dev: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 dev: 
npm ERR! git clone --template=/home/docker/.npm/_git-remotes/_templates --mirror git@github.com:oresoftware/suman.git /home/docker/.npm/_git-remotes/git-github-com-oresoftware-suman-git-dev-e2650236: Cloning into bare repository '/home/docker/.npm/_git-remotes/git-github-com-oresoftware-suman-git-dev-e2650236'...
npm ERR! git clone --template=/home/docker/.npm/_git-remotes/_templates --mirror git@github.com:oresoftware/suman.git /home/docker/.npm/_git-remotes/git-github-com-oresoftware-suman-git-dev-e2650236: Host key verification failed.
npm ERR! git clone --template=/home/docker/.npm/_git-remotes/_templates --mirror git@github.com:oresoftware/suman.git /home/docker/.npm/_git-remotes/git-github-com-oresoftware-suman-git-dev-e2650236: fatal: Could not read from remote repository.
npm ERR! git clone --template=/home/docker/.npm/_git-remotes/_templates --mirror git@github.com:oresoftware/suman.git /home/docker/.npm/_git-remotes/git-github-com-oresoftware-suman-git-dev-e2650236: 
npm ERR! git clone --template=/home/docker/.npm/_git-remotes/_templates --mirror git@github.com:oresoftware/suman.git /home/docker/.npm/_git-remotes/git-github-com-oresoftware-suman-git-dev-e2650236: Please make sure you have the correct access rights
npm ERR! git clone --template=/home/docker/.npm/_git-remotes/_templates --mirror git@github.com:oresoftware/suman.git /home/docker/.npm/_git-remotes/git-github-com-oresoftware-suman-git-dev-e2650236: and the repository exists.
npm ERR! Linux 4.4.0-53-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "--loglevel=warn" "--progress=false" "install"
npm ERR! node v5.12.0
npm ERR! npm  v3.8.6
npm ERR! code 128

npm ERR! Command failed: git clone --template=/home/docker/.npm/_git-remotes/_templates --mirror git@github.com:oresoftware/suman.git /home/docker/.npm/_git-remotes/git-github-com-oresoftware-suman-git-dev-e2650236
npm ERR! Cloning into bare repository '/home/docker/.npm/_git-remotes/git-github-com-oresoftware-suman-git-dev-e2650236'...
npm ERR! Host key verification failed.
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/docker/two/npm-debug.log

```

#### How can the CLI team reproduce the problem?

 too difficult to reproduce directly, using containers and all sort of extra jazz 

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by ORESoftware** [comment]
my Docker container probably does not have the right SSH keys....

**Comment by legodude17** [comment]
@ORESoftware that is probably it

**Comment by ORESoftware** [comment]
my guess is it originates from

`npm install github:x/y`

I doubt it's worth while to improve the error message - but if it does originate from such a command as the above one, it would be nice if NPM reported which NPM command caused the error.

**Comment by zivc** [comment]
What was the resolution for this? It is happening for me when installing stuff on windows, from Github, behind a network proxy.
