### ISSUE TITLE
Can't unpublish,Registry returned 400 for DELETE

### ISSUE THREAD

**Issue by dongwenxiao** [npm/npm#15312]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

do unpublish module, but , response 400

#### How can the CLI team reproduce the problem?

```npm unpublish wapper-css-loader --force```

```
// npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'unpublish',
1 verbose cli   'wapper-css-loader',
1 verbose cli   '--force' ]
2 info using npm@3.10.9
3 info using node@v7.1.0
4 warn using --force I sure hope you know what you are doing.
5 silly unpublish args[0] wapper-css-loader
6 silly unpublish thing Result {
6 silly unpublish   raw: 'wapper-css-loader',
6 silly unpublish   scope: null,
6 silly unpublish   escapedName: 'wapper-css-loader',
6 silly unpublish   name: 'wapper-css-loader',
6 silly unpublish   rawSpec: '',
6 silly unpublish   spec: 'latest',
6 silly unpublish   type: 'tag' }
7 verbose getPublishConfig null
8 silly ls normalized wapper-css-loader
9 silly gentlyRm /Users/dongwenxiao/.npm/wapper-css-loader is being purged
10 verbose gentlyRm don't care about contents; nuking /Users/dongwenxiao/.npm/wapper-css-loader
11 silly mapToRegistry name wapper-css-loader
12 silly mapToRegistry using default registry
13 silly mapToRegistry registry https://registry.npmjs.org/
14 silly mapToRegistry data Result {
14 silly mapToRegistry   raw: 'wapper-css-loader',
14 silly mapToRegistry   scope: null,
14 silly mapToRegistry   escapedName: 'wapper-css-loader',
14 silly mapToRegistry   name: 'wapper-css-loader',
14 silly mapToRegistry   rawSpec: '',
14 silly mapToRegistry   spec: 'latest',
14 silly mapToRegistry   type: 'tag' }
15 silly mapToRegistry uri https://registry.npmjs.org/wapper-css-loader
16 verbose get GET as part of write; not caching result
17 verbose request uri https://registry.npmjs.org/wapper-css-loader?write=true
18 verbose request no auth needed
19 info attempt registry request try #1 at 22:05:01
20 verbose request using bearer token for auth
21 verbose request id 3779529fa85c7804
22 http request GET https://registry.npmjs.org/wapper-css-loader?write=true
23 http 200 https://registry.npmjs.org/wapper-css-loader?write=true
24 verbose headers { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
24 verbose headers   'content-type': 'application/json',
24 verbose headers   etag: '"5859dfd0-43e4"',
24 verbose headers   'content-encoding': 'gzip',
24 verbose headers   'cache-control': 'max-age=0',
24 verbose headers   'transfer-encoding': 'chunked',
24 verbose headers   'accept-ranges': 'bytes',
24 verbose headers   date: 'Sun, 25 Dec 2016 14:05:04 GMT',
24 verbose headers   via: '1.1 varnish',
24 verbose headers   connection: 'keep-alive',
24 verbose headers   'x-served-by': 'cache-nrt6126-NRT',
24 verbose headers   'x-cache': 'MISS',
24 verbose headers   'x-cache-hits': '0',
24 verbose headers   'x-timer': 'S1482674703.964256,VS0,VE565',
24 verbose headers   vary: 'Accept-Encoding' }
25 silly get cb [ 200,
25 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
25 silly get     'content-type': 'application/json',
25 silly get     etag: '"5859dfd0-43e4"',
25 silly get     'content-encoding': 'gzip',
25 silly get     'cache-control': 'max-age=0',
25 silly get     'transfer-encoding': 'chunked',
25 silly get     'accept-ranges': 'bytes',
25 silly get     date: 'Sun, 25 Dec 2016 14:05:04 GMT',
25 silly get     via: '1.1 varnish',
25 silly get     connection: 'keep-alive',
25 silly get     'x-served-by': 'cache-nrt6126-NRT',
25 silly get     'x-cache': 'MISS',
25 silly get     'x-cache-hits': '0',
25 silly get     'x-timer': 'S1482674703.964256,VS0,VE565',
25 silly get     vary: 'Accept-Encoding' } ]
26 verbose get saving wapper-css-loader to /Users/dongwenxiao/.npm/registry.npmjs.org/wapper-css-loader_3Fwrite_3Dtrue/.cache.json
27 verbose correctMkdir /Users/dongwenxiao/.npm correctMkdir not in flight; initializing
28 info unpublish No version specified, removing all
29 verbose request uri https://registry.npmjs.org/wapper-css-loader/-rev/11-38957099083d2f97c2cb1ca80789bc3d
30 verbose request sending authorization for write operation
31 info attempt registry request try #1 at 22:05:09
32 verbose request using bearer token for auth
33 http request DELETE https://registry.npmjs.org/wapper-css-loader/-rev/11-38957099083d2f97c2cb1ca80789bc3d
34 http 400 https://registry.npmjs.org/wapper-css-loader/-rev/11-38957099083d2f97c2cb1ca80789bc3d
35 verbose headers { 'content-type': 'application/json',
35 verbose headers   'cache-control': 'max-age=300',
35 verbose headers   'content-length': '17',
35 verbose headers   'accept-ranges': 'bytes',
35 verbose headers   date: 'Sun, 25 Dec 2016 14:05:11 GMT',
35 verbose headers   via: '1.1 varnish',
35 verbose headers   connection: 'keep-alive',
35 verbose headers   'x-served-by': 'cache-nrt6126-NRT',
35 verbose headers   'x-cache': 'MISS',
35 verbose headers   'x-cache-hits': '0',
35 verbose headers   'x-timer': 'S1482674710.432511,VS0,VE642',
35 verbose headers   vary: 'Accept-Encoding' }
36 verbose request invalidating /Users/dongwenxiao/.npm/registry.npmjs.org/wapper-css-loader on DELETE
37 verbose stack Error: Registry returned 400 for DELETE on https://registry.npmjs.org/wapper-css-loader/-rev/11-38957099083d2f97c2cb1ca80789bc3d
37 verbose stack     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:302:12)
37 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:280:14)
37 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:210:14)
37 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:187:22)
37 verbose stack     at emitTwo (events.js:106:13)
37 verbose stack     at Request.emit (events.js:191:7)
37 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1048:10)
37 verbose stack     at emitOne (events.js:96:13)
37 verbose stack     at Request.emit (events.js:188:7)
37 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:969:12)
38 verbose statusCode 400
39 verbose pkgid wapper-css-loader
40 verbose cwd /Users/dongwenxiao/Documents/work_my/wapper-css-loader
41 error Darwin 16.1.0
42 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "unpublish" "wapper-css-loader" "--force"
43 error node v7.1.0
44 error npm  v3.10.9
45 error code E400
46 error Registry returned 400 for DELETE on https://registry.npmjs.org/wapper-css-loader/-rev/11-38957099083d2f97c2cb1ca80789bc3d
47 error If you need help, you may report this error at:
47 error     <https://github.com/npm/npm/issues>
48 verbose exit [ 1, true ]
```

### supporting information:

 - `npm -v` prints:3.10.9
 - `node -v` prints:v7.1.0
 - `npm config get registry` prints:https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?:OS X/macOS
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [x] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [x] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

Thank you for any help...

**Comment by KenanY** [comment]
@dongwenxiao Please email `support@npmjs.com` for package unpublishes. Thanks!

**Comment by dongwenxiao** [comment]
@KenanY ok，thank you.
