### ISSUE TITLE
npm not working?

### ISSUE THREAD

**Issue by anthonybrown** [npm/npm#15310]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Tonys-MBP: ~                                                                                                        ▸▸▸▸▸▸▸▸▸▸
 → npm list -g --depth=0
Error: Cannot find module 'node-uuid'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/lib/auth.js:4:12)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "list" "-g" "--depth=0"
npm ERR! node v7.2.1
npm ERR! npm  v4.0.5
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'node-uuid'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

#### How can the CLI team reproduce the problem?
npm list -g --depth=0

### supporting information:

 - `npm -v` prints: 4.0.5
 - `node -v` prints: 6.9.2
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by anthonybrown** [comment]
This happens if I try to do anything with `npm`
like if I try and install something globally `npm i -g browserify`
I get the same message:
```
Error: Cannot find module 'node-uuid'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/lib/auth.js:4:12)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

**Comment by anthonybrown** [comment]
I fixed it

**Comment by Charlotteis** [comment]
Mind sharing how you fixed it in case anyone comes to this issue looking for help?

Have a happy winter break! ⛄️ 🌸

**Comment by anthonybrown** [comment]
Sure, just do `cd /usr/local/lib/node_modules` and `npm prune`    

Also clean the npm cache
