### ISSUE TITLE
When I try to run "npm install --global bower gulp fails

### ISSUE THREAD

**Issue by luuksuijkerbuijk** [npm/npm#15349]
When I try to run "npm install --global bower gulp" the following error shows up:

```
C:\Program Files\nodejs\node_modules\npm\node_modules\request\node_modules\har-valid
ator\src\index.js:1
(function (exports, require, module, __filename, __dirname) { ����������������
^
SyntaxError: Unexpected token ILLEGAL
at exports.runInThisContext (vm.js:73:16)
at Module._compile (module.js:443:25)
at Object.Module._extensions..js (module.js:478:10)
at Module.load (module.js:355:32)
at Function.Module._load (module.js:310:12)
at Module.require (module.js:365:17)
at require (module.js:384:17)
at Object. (C:\Program Files\nodejs\node_modules\npm\node_modules\req
uest\lib\har.js:5:16)
at Module._compile (module.js:460:26)
at Object.Module._extensions..js (module.js:478:10)
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\no
de_modules\npm\bin\npm-cli.js" "install" "--global" "bower" "gulp"
npm ERR! node v0.12.7
npm ERR! npm v2.11.3

npm ERR! C:\Program Files\nodejs\node_modules\npm\node_modules\request\node_modules
har-validator\src\index.js:1
npm ERR! (function (exports, require, module, __filename, __dirname) { �������������
���
npm ERR! ^
npm ERR! Unexpected token ILLEGAL
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR! https://github.com/npm/npm/issues
```

The package.json is:

`{
  "private": true,
  "scripts": {
    "prod": "gulp --production",
    "dev": "gulp watch"
  },
  "devDependencies": {
    "gulp": "^3.9.1",
    "laravel-elixir": "^5.0.0",
    "bootstrap-sass": "^3.0.0"
  }
}`

**Comment by legodude17** [comment]
It seems like the your `npm` installation got messed up... Try reinstalling?

**Comment by luuksuijkerbuijk** [comment]
That worked, thanks!

I should've figured that myself...

**Comment by legodude17** [comment]
Happy to help. Happy coding!
