### ISSUE TITLE
npm install - 404 for me but not for my colleagues...

### ISSUE THREAD

**Issue by eworkfridsten** [npm/npm#15375]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [X] npm is producing an incorrect install.
  - [X] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I try to run npm install and it complains about a 404 when trying to get jQuery-UI.

#### How can the CLI team reproduce the problem?

My package.json:

```
{
  "name": "search",
  "description": "An Aurelia client application.",
  "version": "0.1.0",
  "repository": {
    "type": "???",
    "url": "???"
  },
  "license": "MIT",
  "dependencies": {
    "@types/bootstrap": "^3.3.32",
    "@types/bootstrap-datepicker": "0.0.3",
    "@types/jquery": "^2.0.32",
    "@types/jqueryui": "^1.11.31",
    "@types/moment": "^2.13.0",
    "@types/numeral": "0.0.17",
    "@types/select2": "^4.0.30",
    "aurelia-animator-css": "^1.0.0",
    "aurelia-bootstrapper": "^1.0.0",
    "aurelia-fetch-client": "^1.0.0",
    "aurelia-http-client": "^1.0.0",
    "aurelia-validation": "^0.13.1",
    "bluebird": "^3.4.1",
    "bootstrap": "^3.3.7",
    "bootstrap-datepicker": "^1.6.4",
    "gulp-each": "^0.2.0",
    "jquery": "^3.1.1",
    "jqueryui": "^1.11.1",
    "moment": "^2.15.1",
    "numeral": "^1.5.3",
    "select2": "^4.0.3",
    "whatwg-fetch": "^1.0.0"
  },
  "peerDependencies": {},
  "devDependencies": {
    "aurelia-cli": "^0.21.0",
    "aurelia-testing": "^1.0.0-beta.2.0.0",
    "aurelia-tools": "^0.2.2",
    "autoprefixer": "^6.3.6",
    "browser-sync": "^2.13.0",
    "cheerio": "^0.22.0",
    "connect-history-api-fallback": "^1.2.0",
    "event-stream": "^3.3.3",
    "gulp": "github:gulpjs/gulp#4.0",
    "gulp-changed-in-place": "^2.0.3",
    "gulp-each": "^0.2.0",
    "gulp-notify": "^2.2.0",
    "gulp-plumber": "^1.1.0",
    "gulp-postcss": "6.1.1",
    "gulp-protractor": "3.0.0",
    "gulp-rename": "^1.2.2",
    "gulp-sourcemaps": "^2.0.0-alpha",
    "gulp-tslint": "^5.0.0",
    "gulp-typescript": "^2.13.6",
    "jasmine-core": "^2.4.1",
    "karma": "^0.13.22",
    "karma-chrome-launcher": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-typescript-preprocessor": "^0.2.1",
    "minimatch": "^3.0.2",
    "postcss-cssnext": "^2.8.0",
    "postcss-modules": "^0.5.2",
    "through2": "^2.0.1",
    "tslint": "^3.11.0",
    "typescript": ">=1.9.0-dev || ^2.0.0",
    "uglify-js": "^2.6.3",
    "vinyl-fs": "^2.4.3",
    "yargs": "^6.3.0"
  }
}

```

And  the npm-debug.log:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@1.3.21
3 info using node@v7.2.0
4 verbose readDependencies using package.json deps
5 verbose install where, deps [ 'D:\\Development\\git\\evaluation-frontend',
5 verbose install   [ '@types/bootstrap',
5 verbose install     '@types/bootstrap-datepicker',
5 verbose install     '@types/jquery',
5 verbose install     '@types/jqueryui',
5 verbose install     '@types/moment',
5 verbose install     '@types/numeral',
5 verbose install     '@types/select2',
5 verbose install     'aurelia-animator-css',
5 verbose install     'aurelia-bootstrapper',
5 verbose install     'aurelia-fetch-client',
5 verbose install     'aurelia-http-client',
5 verbose install     'aurelia-validation',
5 verbose install     'bluebird',
5 verbose install     'bootstrap',
5 verbose install     'bootstrap-datepicker',
5 verbose install     'gulp-each',
5 verbose install     'jquery',
5 verbose install     'jqueryui',
5 verbose install     'moment',
5 verbose install     'numeral',
5 verbose install     'select2',
5 verbose install     'whatwg-fetch',
5 verbose install     'aurelia-cli',
5 verbose install     'aurelia-testing',
5 verbose install     'aurelia-tools',
5 verbose install     'autoprefixer',
5 verbose install     'browser-sync',
5 verbose install     'cheerio',
5 verbose install     'connect-history-api-fallback',
5 verbose install     'event-stream',
5 verbose install     'gulp',
5 verbose install     'gulp-changed-in-place',
5 verbose install     'gulp-notify',
5 verbose install     'gulp-plumber',
5 verbose install     'gulp-postcss',
5 verbose install     'gulp-protractor',
5 verbose install     'gulp-rename',
5 verbose install     'gulp-sourcemaps',
5 verbose install     'gulp-tslint',
5 verbose install     'gulp-typescript',
5 verbose install     'jasmine-core',
5 verbose install     'karma',
5 verbose install     'karma-chrome-launcher',
5 verbose install     'karma-jasmine',
5 verbose install     'karma-typescript-preprocessor',
5 verbose install     'minimatch',
5 verbose install     'postcss-cssnext',
5 verbose install     'postcss-modules',
5 verbose install     'through2',
5 verbose install     'tslint',
5 verbose install     'typescript',
5 verbose install     'uglify-js',
5 verbose install     'vinyl-fs',
5 verbose install     'yargs' ] ]
6 info preinstall search@0.1.0
7 verbose readDependencies using package.json deps
8 verbose cache add [ '@types/jquery@^2.0.32', null ]
9 verbose cache add name=undefined spec="@types/jquery@^2.0.32" args=["@types/jquery@^2.0.32",null]
10 verbose parsed url Url {
10 verbose parsed url   protocol: null,
10 verbose parsed url   slashes: null,
10 verbose parsed url   auth: null,
10 verbose parsed url   host: null,
10 verbose parsed url   port: null,
10 verbose parsed url   hostname: null,
10 verbose parsed url   hash: null,
10 verbose parsed url   search: null,
10 verbose parsed url   query: null,
10 verbose parsed url   pathname: '@types/jquery@%5E2.0.32',
10 verbose parsed url   path: '@types/jquery@%5E2.0.32',
10 verbose parsed url   href: '@types/jquery@%5E2.0.32' }
11 verbose cache add name="" spec="types/jquery@^2.0.32" args=["","types/jquery@^2.0.32"]
12 verbose parsed url Url {
12 verbose parsed url   protocol: null,
12 verbose parsed url   slashes: null,
12 verbose parsed url   auth: null,
12 verbose parsed url   host: null,
12 verbose parsed url   port: null,
12 verbose parsed url   hostname: null,
12 verbose parsed url   hash: null,
12 verbose parsed url   search: null,
12 verbose parsed url   query: null,
12 verbose parsed url   pathname: 'types/jquery@%5E2.0.32',
12 verbose parsed url   path: 'types/jquery@%5E2.0.32',
12 verbose parsed url   href: 'types/jquery@%5E2.0.32' }
13 verbose cache add name="types/jquery" spec="^2.0.32" args=["types/jquery","^2.0.32"]
14 verbose parsed url Url {
14 verbose parsed url   protocol: null,
14 verbose parsed url   slashes: null,
14 verbose parsed url   auth: null,
14 verbose parsed url   host: null,
14 verbose parsed url   port: null,
14 verbose parsed url   hostname: null,
14 verbose parsed url   hash: null,
14 verbose parsed url   search: null,
14 verbose parsed url   query: null,
14 verbose parsed url   pathname: '%5E2.0.32',
14 verbose parsed url   path: '%5E2.0.32',
14 verbose parsed url   href: '%5E2.0.32' }
15 verbose addNamed [ 'types/jquery', '^2.0.32' ]
16 verbose addNamed [ null, '>=2.0.32-0 <3.0.0-0' ]
17 verbose cache add [ '@types/jqueryui@^1.11.31', null ]
18 verbose cache add name=undefined spec="@types/jqueryui@^1.11.31" args=["@types/jqueryui@^1.11.31",null]
19 verbose parsed url Url {
19 verbose parsed url   protocol: null,
19 verbose parsed url   slashes: null,
19 verbose parsed url   auth: null,
19 verbose parsed url   host: null,
19 verbose parsed url   port: null,
19 verbose parsed url   hostname: null,
19 verbose parsed url   hash: null,
19 verbose parsed url   search: null,
19 verbose parsed url   query: null,
19 verbose parsed url   pathname: '@types/jqueryui@%5E1.11.31',
19 verbose parsed url   path: '@types/jqueryui@%5E1.11.31',
19 verbose parsed url   href: '@types/jqueryui@%5E1.11.31' }
20 verbose cache add name="" spec="types/jqueryui@^1.11.31" args=["","types/jqueryui@^1.11.31"]
21 verbose parsed url Url {
21 verbose parsed url   protocol: null,
21 verbose parsed url   slashes: null,
21 verbose parsed url   auth: null,
21 verbose parsed url   host: null,
21 verbose parsed url   port: null,
21 verbose parsed url   hostname: null,
21 verbose parsed url   hash: null,
21 verbose parsed url   search: null,
21 verbose parsed url   query: null,
21 verbose parsed url   pathname: 'types/jqueryui@%5E1.11.31',
21 verbose parsed url   path: 'types/jqueryui@%5E1.11.31',
21 verbose parsed url   href: 'types/jqueryui@%5E1.11.31' }
22 verbose cache add name="types/jqueryui" spec="^1.11.31" args=["types/jqueryui","^1.11.31"]
23 verbose parsed url Url {
23 verbose parsed url   protocol: null,
23 verbose parsed url   slashes: null,
23 verbose parsed url   auth: null,
23 verbose parsed url   host: null,
23 verbose parsed url   port: null,
23 verbose parsed url   hostname: null,
23 verbose parsed url   hash: null,
23 verbose parsed url   search: null,
23 verbose parsed url   query: null,
23 verbose parsed url   pathname: '%5E1.11.31',
23 verbose parsed url   path: '%5E1.11.31',
23 verbose parsed url   href: '%5E1.11.31' }
24 verbose addNamed [ 'types/jqueryui', '^1.11.31' ]
25 verbose addNamed [ null, '>=1.11.31-0 <2.0.0-0' ]
26 verbose cache add [ '@types/moment@^2.13.0', null ]
27 verbose cache add name=undefined spec="@types/moment@^2.13.0" args=["@types/moment@^2.13.0",null]
28 verbose parsed url Url {
28 verbose parsed url   protocol: null,
28 verbose parsed url   slashes: null,
28 verbose parsed url   auth: null,
28 verbose parsed url   host: null,
28 verbose parsed url   port: null,
28 verbose parsed url   hostname: null,
28 verbose parsed url   hash: null,
28 verbose parsed url   search: null,
28 verbose parsed url   query: null,
28 verbose parsed url   pathname: '@types/moment@%5E2.13.0',
28 verbose parsed url   path: '@types/moment@%5E2.13.0',
28 verbose parsed url   href: '@types/moment@%5E2.13.0' }
29 verbose cache add name="" spec="types/moment@^2.13.0" args=["","types/moment@^2.13.0"]
30 verbose parsed url Url {
30 verbose parsed url   protocol: null,
30 verbose parsed url   slashes: null,
30 verbose parsed url   auth: null,
30 verbose parsed url   host: null,
30 verbose parsed url   port: null,
30 verbose parsed url   hostname: null,
30 verbose parsed url   hash: null,
30 verbose parsed url   search: null,
30 verbose parsed url   query: null,
30 verbose parsed url   pathname: 'types/moment@%5E2.13.0',
30 verbose parsed url   path: 'types/moment@%5E2.13.0',
30 verbose parsed url   href: 'types/moment@%5E2.13.0' }
31 verbose cache add name="types/moment" spec="^2.13.0" args=["types/moment","^2.13.0"]
32 verbose parsed url Url {
32 verbose parsed url   protocol: null,
32 verbose parsed url   slashes: null,
32 verbose parsed url   auth: null,
32 verbose parsed url   host: null,
32 verbose parsed url   port: null,
32 verbose parsed url   hostname: null,
32 verbose parsed url   hash: null,
32 verbose parsed url   search: null,
32 verbose parsed url   query: null,
32 verbose parsed url   pathname: '%5E2.13.0',
32 verbose parsed url   path: '%5E2.13.0',
32 verbose parsed url   href: '%5E2.13.0' }
33 verbose addNamed [ 'types/moment', '^2.13.0' ]
34 verbose addNamed [ null, '>=2.13.0-0 <3.0.0-0' ]
35 verbose cache add [ '@types/numeral@0.0.17', null ]
36 verbose cache add name=undefined spec="@types/numeral@0.0.17" args=["@types/numeral@0.0.17",null]
37 verbose parsed url Url {
37 verbose parsed url   protocol: null,
37 verbose parsed url   slashes: null,
37 verbose parsed url   auth: null,
37 verbose parsed url   host: null,
37 verbose parsed url   port: null,
37 verbose parsed url   hostname: null,
37 verbose parsed url   hash: null,
37 verbose parsed url   search: null,
37 verbose parsed url   query: null,
37 verbose parsed url   pathname: '@types/numeral@0.0.17',
37 verbose parsed url   path: '@types/numeral@0.0.17',
37 verbose parsed url   href: '@types/numeral@0.0.17' }
38 verbose cache add name="" spec="types/numeral@0.0.17" args=["","types/numeral@0.0.17"]
39 verbose parsed url Url {
39 verbose parsed url   protocol: null,
39 verbose parsed url   slashes: null,
39 verbose parsed url   auth: null,
39 verbose parsed url   host: null,
39 verbose parsed url   port: null,
39 verbose parsed url   hostname: null,
39 verbose parsed url   hash: null,
39 verbose parsed url   search: null,
39 verbose parsed url   query: null,
39 verbose parsed url   pathname: 'types/numeral@0.0.17',
39 verbose parsed url   path: 'types/numeral@0.0.17',
39 verbose parsed url   href: 'types/numeral@0.0.17' }
40 verbose cache add name="types/numeral" spec="0.0.17" args=["types/numeral","0.0.17"]
41 verbose parsed url Url {
41 verbose parsed url   protocol: null,
41 verbose parsed url   slashes: null,
41 verbose parsed url   auth: null,
41 verbose parsed url   host: null,
41 verbose parsed url   port: null,
41 verbose parsed url   hostname: null,
41 verbose parsed url   hash: null,
41 verbose parsed url   search: null,
41 verbose parsed url   query: null,
41 verbose parsed url   pathname: '0.0.17',
41 verbose parsed url   path: '0.0.17',
41 verbose parsed url   href: '0.0.17' }
42 verbose addNamed [ 'types/numeral', '0.0.17' ]
43 verbose addNamed [ '0.0.17', '0.0.17' ]
44 verbose cache add [ '@types/select2@^4.0.30', null ]
45 verbose cache add name=undefined spec="@types/select2@^4.0.30" args=["@types/select2@^4.0.30",null]
46 verbose parsed url Url {
46 verbose parsed url   protocol: null,
46 verbose parsed url   slashes: null,
46 verbose parsed url   auth: null,
46 verbose parsed url   host: null,
46 verbose parsed url   port: null,
46 verbose parsed url   hostname: null,
46 verbose parsed url   hash: null,
46 verbose parsed url   search: null,
46 verbose parsed url   query: null,
46 verbose parsed url   pathname: '@types/select2@%5E4.0.30',
46 verbose parsed url   path: '@types/select2@%5E4.0.30',
46 verbose parsed url   href: '@types/select2@%5E4.0.30' }
47 verbose cache add name="" spec="types/select2@^4.0.30" args=["","types/select2@^4.0.30"]
48 verbose parsed url Url {
48 verbose parsed url   protocol: null,
48 verbose parsed url   slashes: null,
48 verbose parsed url   auth: null,
48 verbose parsed url   host: null,
48 verbose parsed url   port: null,
48 verbose parsed url   hostname: null,
48 verbose parsed url   hash: null,
48 verbose parsed url   search: null,
48 verbose parsed url   query: null,
48 verbose parsed url   pathname: 'types/select2@%5E4.0.30',
48 verbose parsed url   path: 'types/select2@%5E4.0.30',
48 verbose parsed url   href: 'types/select2@%5E4.0.30' }
49 verbose cache add name="types/select2" spec="^4.0.30" args=["types/select2","^4.0.30"]
50 verbose parsed url Url {
50 verbose parsed url   protocol: null,
50 verbose parsed url   slashes: null,
50 verbose parsed url   auth: null,
50 verbose parsed url   host: null,
50 verbose parsed url   port: null,
50 verbose parsed url   hostname: null,
50 verbose parsed url   hash: null,
50 verbose parsed url   search: null,
50 verbose parsed url   query: null,
50 verbose parsed url   pathname: '%5E4.0.30',
50 verbose parsed url   path: '%5E4.0.30',
50 verbose parsed url   href: '%5E4.0.30' }
51 verbose addNamed [ 'types/select2', '^4.0.30' ]
52 verbose addNamed [ null, '>=4.0.30-0 <5.0.0-0' ]
53 verbose already installed skipping aurelia-animator-css@^1.0.0 D:\Development\git\evaluation-frontend
54 verbose already installed skipping aurelia-bootstrapper@^1.0.0 D:\Development\git\evaluation-frontend
55 verbose already installed skipping aurelia-fetch-client@^1.0.0 D:\Development\git\evaluation-frontend
56 verbose already installed skipping aurelia-http-client@^1.0.0 D:\Development\git\evaluation-frontend
57 verbose already installed skipping aurelia-validation@^0.13.1 D:\Development\git\evaluation-frontend
58 verbose already installed skipping bluebird@^3.4.1 D:\Development\git\evaluation-frontend
59 verbose already installed skipping bootstrap@^3.3.7 D:\Development\git\evaluation-frontend
60 verbose already installed skipping bootstrap-datepicker@^1.6.4 D:\Development\git\evaluation-frontend
61 verbose already installed skipping gulp-each@^0.2.0 D:\Development\git\evaluation-frontend
62 verbose already installed skipping jquery@^3.1.1 D:\Development\git\evaluation-frontend
63 verbose already installed skipping jqueryui@^1.11.1 D:\Development\git\evaluation-frontend
64 verbose already installed skipping moment@^2.15.1 D:\Development\git\evaluation-frontend
65 verbose already installed skipping numeral@^1.5.3 D:\Development\git\evaluation-frontend
66 silly lockFile 995905a5-types-jquery-2-0-32 types/jquery@^2.0.32
67 verbose lock types/jquery@^2.0.32 C:\Users\frfr\AppData\Roaming\npm-cache\995905a5-types-jquery-2-0-32.lock
68 silly lockFile 0358a47c-types-jqueryui-1-11-31 types/jqueryui@^1.11.31
69 verbose lock types/jqueryui@^1.11.31 C:\Users\frfr\AppData\Roaming\npm-cache\0358a47c-types-jqueryui-1-11-31.lock
70 silly lockFile 7b2529f2-types-moment-2-13-0 types/moment@^2.13.0
71 verbose lock types/moment@^2.13.0 C:\Users\frfr\AppData\Roaming\npm-cache\7b2529f2-types-moment-2-13-0.lock
72 silly lockFile daa83d63-types-numeral-0-0-17 types/numeral@0.0.17
73 verbose lock types/numeral@0.0.17 C:\Users\frfr\AppData\Roaming\npm-cache\daa83d63-types-numeral-0-0-17.lock
74 silly lockFile d56edda6-types-select2-4-0-30 types/select2@^4.0.30
75 verbose lock types/select2@^4.0.30 C:\Users\frfr\AppData\Roaming\npm-cache\d56edda6-types-select2-4-0-30.lock
76 verbose already installed skipping select2@^4.0.3 D:\Development\git\evaluation-frontend
77 verbose already installed skipping whatwg-fetch@^1.0.0 D:\Development\git\evaluation-frontend
78 verbose already installed skipping aurelia-cli@^0.21.0 D:\Development\git\evaluation-frontend
79 verbose already installed skipping aurelia-testing@^1.0.0-beta.2.0.0 D:\Development\git\evaluation-frontend
80 verbose already installed skipping aurelia-tools@^0.2.2 D:\Development\git\evaluation-frontend
81 verbose already installed skipping autoprefixer@^6.3.6 D:\Development\git\evaluation-frontend
82 verbose already installed skipping browser-sync@^2.13.0 D:\Development\git\evaluation-frontend
83 verbose already installed skipping cheerio@^0.22.0 D:\Development\git\evaluation-frontend
84 verbose already installed skipping connect-history-api-fallback@^1.2.0 D:\Development\git\evaluation-frontend
85 verbose already installed skipping event-stream@^3.3.3 D:\Development\git\evaluation-frontend
86 verbose cache add [ 'gulp@github:gulpjs/gulp#4.0', null ]
87 verbose cache add name=undefined spec="gulp@github:gulpjs/gulp#4.0" args=["gulp@github:gulpjs/gulp#4.0",null]
88 verbose parsed url Url {
88 verbose parsed url   protocol: null,
88 verbose parsed url   slashes: null,
88 verbose parsed url   auth: null,
88 verbose parsed url   host: null,
88 verbose parsed url   port: null,
88 verbose parsed url   hostname: null,
88 verbose parsed url   hash: '#4.0',
88 verbose parsed url   search: null,
88 verbose parsed url   query: null,
88 verbose parsed url   pathname: 'gulp@github:gulpjs/gulp',
88 verbose parsed url   path: 'gulp@github:gulpjs/gulp',
88 verbose parsed url   href: 'gulp@github:gulpjs/gulp#4.0' }
89 verbose cache add name="gulp" spec="github:gulpjs/gulp#4.0" args=["gulp","github:gulpjs/gulp#4.0"]
90 verbose parsed url Url {
90 verbose parsed url   protocol: 'github:',
90 verbose parsed url   slashes: null,
90 verbose parsed url   auth: null,
90 verbose parsed url   host: 'gulpjs',
90 verbose parsed url   port: null,
90 verbose parsed url   hostname: 'gulpjs',
90 verbose parsed url   hash: '#4.0',
90 verbose parsed url   search: null,
90 verbose parsed url   query: null,
90 verbose parsed url   pathname: '/gulp',
90 verbose parsed url   path: '/gulp',
90 verbose parsed url   href: 'github:gulpjs/gulp#4.0' }
91 verbose addNamed [ 'gulp', 'github:gulpjs/gulp#4.0' ]
92 verbose addNamed [ null, null ]
93 silly lockFile e380f803-gulp-github-gulpjs-gulp-4-0 gulp@github:gulpjs/gulp#4.0
94 verbose lock gulp@github:gulpjs/gulp#4.0 C:\Users\frfr\AppData\Roaming\npm-cache\e380f803-gulp-github-gulpjs-gulp-4-0.lock
95 verbose already installed skipping gulp-changed-in-place@^2.0.3 D:\Development\git\evaluation-frontend
96 verbose already installed skipping gulp-notify@^2.2.0 D:\Development\git\evaluation-frontend
97 verbose already installed skipping gulp-plumber@^1.1.0 D:\Development\git\evaluation-frontend
98 verbose already installed skipping gulp-postcss@6.1.1 D:\Development\git\evaluation-frontend
99 verbose cache add [ 'gulp-protractor@3.0.0', null ]
100 verbose cache add name=undefined spec="gulp-protractor@3.0.0" args=["gulp-protractor@3.0.0",null]
101 verbose parsed url Url {
101 verbose parsed url   protocol: null,
101 verbose parsed url   slashes: null,
101 verbose parsed url   auth: null,
101 verbose parsed url   host: null,
101 verbose parsed url   port: null,
101 verbose parsed url   hostname: null,
101 verbose parsed url   hash: null,
101 verbose parsed url   search: null,
101 verbose parsed url   query: null,
101 verbose parsed url   pathname: 'gulp-protractor@3.0.0',
101 verbose parsed url   path: 'gulp-protractor@3.0.0',
101 verbose parsed url   href: 'gulp-protractor@3.0.0' }
102 verbose cache add name="gulp-protractor" spec="3.0.0" args=["gulp-protractor","3.0.0"]
103 verbose parsed url Url {
103 verbose parsed url   protocol: null,
103 verbose parsed url   slashes: null,
103 verbose parsed url   auth: null,
103 verbose parsed url   host: null,
103 verbose parsed url   port: null,
103 verbose parsed url   hostname: null,
103 verbose parsed url   hash: null,
103 verbose parsed url   search: null,
103 verbose parsed url   query: null,
103 verbose parsed url   pathname: '3.0.0',
103 verbose parsed url   path: '3.0.0',
103 verbose parsed url   href: '3.0.0' }
104 verbose addNamed [ 'gulp-protractor', '3.0.0' ]
105 verbose addNamed [ '3.0.0', '3.0.0' ]
106 silly lockFile d9d2015f-gulp-protractor-3-0-0 gulp-protractor@3.0.0
107 verbose lock gulp-protractor@3.0.0 C:\Users\frfr\AppData\Roaming\npm-cache\d9d2015f-gulp-protractor-3-0-0.lock
108 verbose already installed skipping gulp-rename@^1.2.2 D:\Development\git\evaluation-frontend
109 verbose already installed skipping gulp-sourcemaps@^2.0.0-alpha D:\Development\git\evaluation-frontend
110 verbose already installed skipping gulp-tslint@^5.0.0 D:\Development\git\evaluation-frontend
111 verbose already installed skipping gulp-typescript@^2.13.6 D:\Development\git\evaluation-frontend
112 verbose already installed skipping jasmine-core@^2.4.1 D:\Development\git\evaluation-frontend
113 verbose already installed skipping karma@^0.13.22 D:\Development\git\evaluation-frontend
114 verbose already installed skipping karma-chrome-launcher@^1.0.1 D:\Development\git\evaluation-frontend
115 verbose already installed skipping karma-jasmine@^1.0.2 D:\Development\git\evaluation-frontend
116 verbose already installed skipping karma-typescript-preprocessor@^0.2.1 D:\Development\git\evaluation-frontend
117 verbose already installed skipping minimatch@^3.0.2 D:\Development\git\evaluation-frontend
118 verbose already installed skipping postcss-cssnext@^2.8.0 D:\Development\git\evaluation-frontend
119 verbose already installed skipping postcss-modules@^0.5.2 D:\Development\git\evaluation-frontend
120 verbose already installed skipping through2@^2.0.1 D:\Development\git\evaluation-frontend
121 verbose already installed skipping tslint@^3.11.0 D:\Development\git\evaluation-frontend
122 verbose already installed skipping typescript@>=1.9.0-dev || ^2.0.0 D:\Development\git\evaluation-frontend
123 verbose already installed skipping uglify-js@^2.6.3 D:\Development\git\evaluation-frontend
124 verbose already installed skipping vinyl-fs@^2.4.3 D:\Development\git\evaluation-frontend
125 verbose already installed skipping yargs@^6.3.0 D:\Development\git\evaluation-frontend
126 verbose cache add [ '@types/bootstrap@^3.3.32', null ]
127 verbose cache add name=undefined spec="@types/bootstrap@^3.3.32" args=["@types/bootstrap@^3.3.32",null]
128 verbose parsed url Url {
128 verbose parsed url   protocol: null,
128 verbose parsed url   slashes: null,
128 verbose parsed url   auth: null,
128 verbose parsed url   host: null,
128 verbose parsed url   port: null,
128 verbose parsed url   hostname: null,
128 verbose parsed url   hash: null,
128 verbose parsed url   search: null,
128 verbose parsed url   query: null,
128 verbose parsed url   pathname: '@types/bootstrap@%5E3.3.32',
128 verbose parsed url   path: '@types/bootstrap@%5E3.3.32',
128 verbose parsed url   href: '@types/bootstrap@%5E3.3.32' }
129 verbose cache add name="" spec="types/bootstrap@^3.3.32" args=["","types/bootstrap@^3.3.32"]
130 verbose parsed url Url {
130 verbose parsed url   protocol: null,
130 verbose parsed url   slashes: null,
130 verbose parsed url   auth: null,
130 verbose parsed url   host: null,
130 verbose parsed url   port: null,
130 verbose parsed url   hostname: null,
130 verbose parsed url   hash: null,
130 verbose parsed url   search: null,
130 verbose parsed url   query: null,
130 verbose parsed url   pathname: 'types/bootstrap@%5E3.3.32',
130 verbose parsed url   path: 'types/bootstrap@%5E3.3.32',
130 verbose parsed url   href: 'types/bootstrap@%5E3.3.32' }
131 verbose cache add name="types/bootstrap" spec="^3.3.32" args=["types/bootstrap","^3.3.32"]
132 verbose parsed url Url {
132 verbose parsed url   protocol: null,
132 verbose parsed url   slashes: null,
132 verbose parsed url   auth: null,
132 verbose parsed url   host: null,
132 verbose parsed url   port: null,
132 verbose parsed url   hostname: null,
132 verbose parsed url   hash: null,
132 verbose parsed url   search: null,
132 verbose parsed url   query: null,
132 verbose parsed url   pathname: '%5E3.3.32',
132 verbose parsed url   path: '%5E3.3.32',
132 verbose parsed url   href: '%5E3.3.32' }
133 verbose addNamed [ 'types/bootstrap', '^3.3.32' ]
134 verbose addNamed [ null, '>=3.3.32-0 <4.0.0-0' ]
135 silly lockFile 82215636-types-bootstrap-3-3-32 types/bootstrap@^3.3.32
136 verbose lock types/bootstrap@^3.3.32 C:\Users\frfr\AppData\Roaming\npm-cache\82215636-types-bootstrap-3-3-32.lock
137 verbose cache add [ '@types/bootstrap-datepicker@0.0.3', null ]
138 verbose cache add name=undefined spec="@types/bootstrap-datepicker@0.0.3" args=["@types/bootstrap-datepicker@0.0.3",null]
139 verbose parsed url Url {
139 verbose parsed url   protocol: null,
139 verbose parsed url   slashes: null,
139 verbose parsed url   auth: null,
139 verbose parsed url   host: null,
139 verbose parsed url   port: null,
139 verbose parsed url   hostname: null,
139 verbose parsed url   hash: null,
139 verbose parsed url   search: null,
139 verbose parsed url   query: null,
139 verbose parsed url   pathname: '@types/bootstrap-datepicker@0.0.3',
139 verbose parsed url   path: '@types/bootstrap-datepicker@0.0.3',
139 verbose parsed url   href: '@types/bootstrap-datepicker@0.0.3' }
140 verbose cache add name="" spec="types/bootstrap-datepicker@0.0.3" args=["","types/bootstrap-datepicker@0.0.3"]
141 verbose parsed url Url {
141 verbose parsed url   protocol: null,
141 verbose parsed url   slashes: null,
141 verbose parsed url   auth: null,
141 verbose parsed url   host: null,
141 verbose parsed url   port: null,
141 verbose parsed url   hostname: null,
141 verbose parsed url   hash: null,
141 verbose parsed url   search: null,
141 verbose parsed url   query: null,
141 verbose parsed url   pathname: 'types/bootstrap-datepicker@0.0.3',
141 verbose parsed url   path: 'types/bootstrap-datepicker@0.0.3',
141 verbose parsed url   href: 'types/bootstrap-datepicker@0.0.3' }
142 verbose cache add name="types/bootstrap-datepicker" spec="0.0.3" args=["types/bootstrap-datepicker","0.0.3"]
143 verbose parsed url Url {
143 verbose parsed url   protocol: null,
143 verbose parsed url   slashes: null,
143 verbose parsed url   auth: null,
143 verbose parsed url   host: null,
143 verbose parsed url   port: null,
143 verbose parsed url   hostname: null,
143 verbose parsed url   hash: null,
143 verbose parsed url   search: null,
143 verbose parsed url   query: null,
143 verbose parsed url   pathname: '0.0.3',
143 verbose parsed url   path: '0.0.3',
143 verbose parsed url   href: '0.0.3' }
144 verbose addNamed [ 'types/bootstrap-datepicker', '0.0.3' ]
145 verbose addNamed [ '0.0.3', '0.0.3' ]
146 silly lockFile 2aec307d-types-bootstrap-datepicker-0-0-3 types/bootstrap-datepicker@0.0.3
147 verbose lock types/bootstrap-datepicker@0.0.3 C:\Users\frfr\AppData\Roaming\npm-cache\2aec307d-types-bootstrap-datepicker-0-0-3.lock
148 info addNameTag [ 'gulp', 'github:gulpjs/gulp#4.0' ]
149 silly addNameRange { name: 'types/jqueryui',
149 silly addNameRange   range: '>=1.11.31-0 <2.0.0-0',
149 silly addNameRange   hasData: false }
150 silly addNameRange { name: 'types/select2',
150 silly addNameRange   range: '>=4.0.30-0 <5.0.0-0',
150 silly addNameRange   hasData: false }
151 silly addNameRange { name: 'types/jquery',
151 silly addNameRange   range: '>=2.0.32-0 <3.0.0-0',
151 silly addNameRange   hasData: false }
152 silly addNameRange { name: 'types/moment',
152 silly addNameRange   range: '>=2.13.0-0 <3.0.0-0',
152 silly addNameRange   hasData: false }
153 silly addNameRange { name: 'types/bootstrap',
153 silly addNameRange   range: '>=3.3.32-0 <4.0.0-0',
153 silly addNameRange   hasData: false }
154 info maybeGithub Attempting github:gulpjs/gulp#4.0 from git://github.com/github:gulpjs/gulp#4.0
155 silly lockFile 649ae0b0-ithub-com-github-gulpjs-gulp-4-0 git://github.com/github:gulpjs/gulp#4.0
156 verbose lock git://github.com/github:gulpjs/gulp#4.0 C:\Users\frfr\AppData\Roaming\npm-cache\649ae0b0-ithub-com-github-gulpjs-gulp-4-0.lock
157 verbose addRemoteGit [ 'git://github.com/github:gulpjs/gulp', '4.0' ]
158 warn `git config --get remote.origin.url` returned wrong result (git://github.com/github:gulpjs/gulp)
159 silly addNameRange number 2 { name: 'types/jqueryui',
159 silly addNameRange   range: '>=1.11.31-0 <2.0.0-0',
159 silly addNameRange   hasData: true }
160 silly addNameRange versions [ undefined, [] ]
161 error TypeError: Cannot read property 'latest' of undefined
161 error     at next (C:\Program Files\nodejs\node_modules\npm\lib\cache.js:688:35)
161 error     at C:\Program Files\nodejs\node_modules\npm\lib\cache.js:676:5
161 error     at saved (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\get.js:142:7)
161 error     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:133:7
161 error     at FSReqWrap.oncomplete (fs.js:111:15)
162 error If you need help, you may report this *entire* log,
162 error including the npm and node versions, at:
162 error     <http://github.com/isaacs/npm/issues>
163 error System Windows_NT 10.0.14393
164 error command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
165 error cwd D:\Development\git\evaluation-frontend
166 error node -v v7.2.0
167 error npm -v 1.3.21
168 verbose exit [ 1, true ]

```

**Comment by KenanY** [comment]
@eworkfridsten Sorry, `npm@1.3` is years old and is no longer supported. I can reopen this if it's still an issue with the latest stable release though.

**Comment by eworkfridsten** [comment]
Thanks! I managed to get it working by updating node.js and npm.
