### ISSUE TITLE
mongoldb Unknown encoding: -1

### ISSUE THREAD

**Issue by eboudreaux0413** [npm/npm#15374]
[npm-debug.txt](https://github.com/npm/npm/files/681904/npm-debug.txt)

not sure what's going on for some reason I'm getting this error can anyone help?

**Comment by eboudreaux0413** [comment]
TypeError: Unknown encoding: -1
    at Buffer.slowToString (buffer.js:487:17)
    at Buffer.toString (buffer.js:500:27)
    at ObjectID.toString (/Users/edwardboudreaux/Projects/mongodriver/node_modules/bson/lib/bson/objectid.js:174:20)
    at formatValue (util.js:352:36)
    at formatProperty (util.js:794:15)
    at util.js:654:12
    at Array.map (native)
    at formatObject (util.js:653:15)

**Comment by nax3t** [comment]
According to your npm-debug.txt "Error: missing script: start", can you share the contents of your package.json?

Thanks

**Comment by kyrylkov** [comment]
@eboudreaux0413  Seems to be Mongoose 4.7.6 bug.  Try rolling back to 4.7.5

https://github.com/Automattic/mongoose/issues/4864
