### ISSUE TITLE
ionic install error

### ISSUE THREAD

**Issue by soulpresidente** [npm/npm#15373]
I try install to install ionic with npm command but I have an error,
this is my npm-debug content:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\nodejs\\node.exe',
1 verbose cli   'C:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'ionic',
1 verbose cli   'cordova' ]
2 info using npm@3.10.9
3 info using node@v6.9.2
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData ionic
8 silly fetchPackageMetaData cordova
9 silly fetchNamedPackageData ionic
10 silly mapToRegistry name ionic
11 silly mapToRegistry using default registry
12 silly mapToRegistry registry http://registry.npmjs.org/
13 silly mapToRegistry data Result {
13 silly mapToRegistry   raw: 'ionic',
13 silly mapToRegistry   scope: null,
13 silly mapToRegistry   escapedName: 'ionic',
13 silly mapToRegistry   name: 'ionic',
13 silly mapToRegistry   rawSpec: '',
13 silly mapToRegistry   spec: 'latest',
13 silly mapToRegistry   type: 'tag' }
14 silly mapToRegistry uri http://registry.npmjs.org/ionic
15 silly fetchNamedPackageData cordova
16 silly mapToRegistry name cordova
17 silly mapToRegistry using default registry
18 silly mapToRegistry registry http://registry.npmjs.org/
19 silly mapToRegistry data Result {
19 silly mapToRegistry   raw: 'cordova',
19 silly mapToRegistry   scope: null,
19 silly mapToRegistry   escapedName: 'cordova',
19 silly mapToRegistry   name: 'cordova',
19 silly mapToRegistry   rawSpec: '',
19 silly mapToRegistry   spec: 'latest',
19 silly mapToRegistry   type: 'tag' }
20 silly mapToRegistry uri http://registry.npmjs.org/cordova
21 verbose request uri http://registry.npmjs.org/ionic
22 verbose request no auth needed
23 info attempt registry request try #1 at 23:32:24
24 verbose request id d796976ef5a769ca
25 http request GET http://registry.npmjs.org/ionic
26 info retry will retry, error on last attempt: Error: Invalid protocol: null
27 verbose request uri http://registry.npmjs.org/cordova
28 verbose request no auth needed
29 info attempt registry request try #1 at 23:32:24
30 http request GET http://registry.npmjs.org/cordova
31 info retry will retry, error on last attempt: Error: Invalid protocol: null
32 info attempt registry request try #2 at 23:32:34
33 http request GET http://registry.npmjs.org/ionic
34 info retry will retry, error on last attempt: Error: Invalid protocol: null
35 info attempt registry request try #2 at 23:32:34
36 http request GET http://registry.npmjs.org/cordova
37 info retry will retry, error on last attempt: Error: Invalid protocol: null
38 info attempt registry request try #3 at 23:33:34
39 http request GET http://registry.npmjs.org/ionic
40 silly fetchPackageMetaData Error: Invalid protocol: null
40 silly fetchPackageMetaData     at Request.init (C:\nodejs\node_modules\npm\node_modules\request\request.js:460:31)
40 silly fetchPackageMetaData     at new Request (C:\nodejs\node_modules\npm\node_modules\request\request.js:129:8)
40 silly fetchPackageMetaData     at request (C:\nodejs\node_modules\npm\node_modules\request\index.js:55:10)
40 silly fetchPackageMetaData     at CachingRegistryClient.makeRequest (C:\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:158:13)
40 silly fetchPackageMetaData     at C:\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:66:17
40 silly fetchPackageMetaData     at RetryOperation._fn (C:\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\attempt.js:18:5)
40 silly fetchPackageMetaData     at Timeout._onTimeout (C:\nodejs\node_modules\npm\node_modules\npm-registry-client\node_modules\retry\lib\retry_operation.js:68:10)
40 silly fetchPackageMetaData     at ontimeout (timers.js:365:14)
40 silly fetchPackageMetaData     at tryOnTimeout (timers.js:237:5)
40 silly fetchPackageMetaData     at Timer.listOnTimeout (timers.js:207:5)
40 silly fetchPackageMetaData  error for ionic Error: Invalid protocol: null
40 silly fetchPackageMetaData     at Request.init (C:\nodejs\node_modules\npm\node_modules\request\request.js:460:31)
40 silly fetchPackageMetaData     at new Request (C:\nodejs\node_modules\npm\node_modules\request\request.js:129:8)
40 silly fetchPackageMetaData     at request (C:\nodejs\node_modules\npm\node_modules\request\index.js:55:10)
40 silly fetchPackageMetaData     at CachingRegistryClient.makeRequest (C:\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:158:13)
40 silly fetchPackageMetaData     at C:\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:66:17
40 silly fetchPackageMetaData     at RetryOperation._fn (C:\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\attempt.js:18:5)
40 silly fetchPackageMetaData     at Timeout._onTimeout (C:\nodejs\node_modules\npm\node_modules\npm-registry-client\node_modules\retry\lib\retry_operation.js:68:10)
40 silly fetchPackageMetaData     at ontimeout (timers.js:365:14)
40 silly fetchPackageMetaData     at tryOnTimeout (timers.js:237:5)
40 silly fetchPackageMetaData     at Timer.listOnTimeout (timers.js:207:5)
41 info attempt registry request try #3 at 23:33:34
42 http request GET http://registry.npmjs.org/cordova
43 silly fetchPackageMetaData Error: Invalid protocol: null
43 silly fetchPackageMetaData     at Request.init (C:\nodejs\node_modules\npm\node_modules\request\request.js:460:31)
43 silly fetchPackageMetaData     at new Request (C:\nodejs\node_modules\npm\node_modules\request\request.js:129:8)
43 silly fetchPackageMetaData     at request (C:\nodejs\node_modules\npm\node_modules\request\index.js:55:10)
43 silly fetchPackageMetaData     at CachingRegistryClient.makeRequest (C:\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:158:13)
43 silly fetchPackageMetaData     at C:\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:66:17
43 silly fetchPackageMetaData     at RetryOperation._fn (C:\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\attempt.js:18:5)
43 silly fetchPackageMetaData     at Timeout._onTimeout (C:\nodejs\node_modules\npm\node_modules\npm-registry-client\node_modules\retry\lib\retry_operation.js:68:10)
43 silly fetchPackageMetaData     at ontimeout (timers.js:365:14)
43 silly fetchPackageMetaData     at tryOnTimeout (timers.js:237:5)
43 silly fetchPackageMetaData     at Timer.listOnTimeout (timers.js:207:5)
43 silly fetchPackageMetaData  error for cordova Error: Invalid protocol: null
43 silly fetchPackageMetaData     at Request.init (C:\nodejs\node_modules\npm\node_modules\request\request.js:460:31)
43 silly fetchPackageMetaData     at new Request (C:\nodejs\node_modules\npm\node_modules\request\request.js:129:8)
43 silly fetchPackageMetaData     at request (C:\nodejs\node_modules\npm\node_modules\request\index.js:55:10)
43 silly fetchPackageMetaData     at CachingRegistryClient.makeRequest (C:\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:158:13)
43 silly fetchPackageMetaData     at C:\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:66:17
43 silly fetchPackageMetaData     at RetryOperation._fn (C:\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\attempt.js:18:5)
43 silly fetchPackageMetaData     at Timeout._onTimeout (C:\nodejs\node_modules\npm\node_modules\npm-registry-client\node_modules\retry\lib\retry_operation.js:68:10)
43 silly fetchPackageMetaData     at ontimeout (timers.js:365:14)
43 silly fetchPackageMetaData     at tryOnTimeout (timers.js:237:5)
43 silly fetchPackageMetaData     at Timer.listOnTimeout (timers.js:207:5)
44 silly rollbackFailedOptional Starting
45 silly rollbackFailedOptional Finishing
46 silly runTopLevelLifecycles Finishing
47 silly install printInstalled
48 verbose stack Error: Invalid protocol: null
48 verbose stack     at Request.init (C:\nodejs\node_modules\npm\node_modules\request\request.js:460:31)
48 verbose stack     at new Request (C:\nodejs\node_modules\npm\node_modules\request\request.js:129:8)
48 verbose stack     at request (C:\nodejs\node_modules\npm\node_modules\request\index.js:55:10)
48 verbose stack     at CachingRegistryClient.makeRequest (C:\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:158:13)
48 verbose stack     at C:\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:66:17
48 verbose stack     at RetryOperation._fn (C:\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\attempt.js:18:5)
48 verbose stack     at Timeout._onTimeout (C:\nodejs\node_modules\npm\node_modules\npm-registry-client\node_modules\retry\lib\retry_operation.js:68:10)
48 verbose stack     at ontimeout (timers.js:365:14)
48 verbose stack     at tryOnTimeout (timers.js:237:5)
48 verbose stack     at Timer.listOnTimeout (timers.js:207:5)
49 verbose cwd C:\ws
50 error Windows_NT 10.0.14393
51 error argv "C:\\nodejs\\node.exe" "C:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "ionic" "cordova"
52 error node v6.9.2
53 error npm  v3.10.9
54 error Invalid protocol: null
55 error If you need help, you may report this error at:
55 error     <https://github.com/npm/npm/issues>
56 verbose exit [ 1, true ]
```

**Comment by legodude17** [comment]
Try updating to latest `npm`...

**Comment by KenanY** [comment]
Closing as abandoned.
