### ISSUE TITLE
Ionic start project connection error ECONNREFUSED 127.0.0.1:80

### ISSUE THREAD

**Issue by soulpresidente** [npm/npm#15417]
I try to begin my first project with ionic and I have an error:

Downloading: https://github.com/driftyco/ionic-app-base/archive/master.zip
Error with start Error: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:80
at ClientRequest.onError (C:\Users\amaso\AppData\Roaming\npm\node_modules\ionic\node_modules\tunnel-agent\index.js:176:17)
at ClientRequest.g (events.js:291:16)
at emitOne (events.js:96:13)
at ClientRequest.emit (events.js:188:7)
at Socket.socketErrorListener (httpclient.js:310:9)
at emitOne (events.js:96:13)
at Socket.emit (events.js:188:7)
at emitErrorNT (net.js:1278:8)
at combinedTickCallback (internal/process/nexttick.js:74:11)
at process.tickCallback (internal/process/nexttick.js:98:9)
Error Initializing app: Error: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:80
Error: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:80
at ClientRequest.onError (C:\Users\amaso\AppData\Roaming\npm\node_modules\ionic\node_modules\tunnel-agent\index.js:176:17)
at ClientRequest.g (events.js:291:16)
at emitOne (events.js:96:13)
at ClientRequest.emit (events.js:188:7)
at Socket.socketErrorListener (httpclient.js:310:9)
at emitOne (events.js:96:13)
at Socket.emit (events.js:188:7)
at emitErrorNT (net.js:1278:8)
at combinedTickCallback (internal/process/nexttick.js:74:11)
at process.tickCallback (internal/process/nexttick.js:98:9)

**Comment by legodude17** [comment]
What are the results of:
1. `npm config get registry`
2. `npm config get http-proxy`
3. `npm config get https-proxy`
