### ISSUE TITLE
NPM not getting installed correctlly

### ISSUE THREAD

**Issue by RamitAnandSharma** [npm/npm#15410]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [/ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Installed Node.js and NPM from node installer v7.4.0
Installed successfully but no npm commands working 

#### How can the CLI team reproduce the problem?

Install node js from
https://nodejs.org/en/

run command 
npm -v
npm install -g angular-cli [Gives Errror]
npm [Gives Error]

 #### Error
C:\windows\system32>npm -help
Error: Cannot find module 'bl'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\sbbras\AppData\Roaming\npm\node_modules
\npm\node_modules\request\request.js:9:10)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\sbbras\\App
Data\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "-help"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.2
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'bl'

**Comment by Ilon4ik** [comment]
Any Update on this issue?

**Comment by legodude17** [comment]
Try reinstalling `npm`.
