### ISSUE TITLE
nom run build error

### ISSUE THREAD

**Issue by johnzhu12** [npm/npm#15447]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/6.2.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@3.5.2
3 info using node@v6.2.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle dreamGame@1.0.0~prebuild: dreamGame@1.0.0
6 silly lifecycle dreamGame@1.0.0~prebuild: no script for prebuild, continuing
7 info lifecycle dreamGame@1.0.0~build: dreamGame@1.0.0
8 verbose lifecycle dreamGame@1.0.0~build: unsafe-perm in lifecycle true
9 verbose lifecycle dreamGame@1.0.0~build: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/zhujohn/Desktop/Git_workSpace/cubee.lot.admin.h5/lottery_admin/_build/node_modules/.bin:/Users/zhujohn/.sdkman/candidates/gradle/current/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin:/Users/zhujohn/Downloads/软件安装/apache-ant-1.9.4/bin:/Users/zhujohn/Downloads/android-sdk-macosx/tools:/Users/zhujohn/Downloads/android-sdk-macosx/platform-tools:/usr/local/Cellar/node/6.2.0/lib/node_modules/cnpm/bin:/usr/local/Cellar/node/6.2.0/bin
10 verbose lifecycle dreamGame@1.0.0~build: CWD: /Users/zhujohn/Desktop/Git_workSpace/cubee.lot.admin.h5/lottery_admin/_build
11 silly lifecycle dreamGame@1.0.0~build: Args: [ '-c', 'gulp build' ]
12 silly lifecycle dreamGame@1.0.0~build: Returned: code: 1  signal: null
13 info lifecycle dreamGame@1.0.0~build: Failed to exec build script
14 verbose stack Error: dreamGame@1.0.0 build: `gulp build`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:850:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid dreamGame@1.0.0
16 verbose cwd /Users/zhujohn/Desktop/Git_workSpace/cubee.lot.admin.h5/lottery_admin/_build
17 error Darwin 14.5.0
18 error argv "/usr/local/Cellar/node/6.2.0/bin/node" "/usr/local/bin/npm" "run" "build"
19 error node v6.2.0
20 error npm  v3.5.2
21 error code ELIFECYCLE
22 error dreamGame@1.0.0 build: `gulp build`
22 error Exit status 1
23 error Failed at the dreamGame@1.0.0 build script 'gulp build'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the dreamGame package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     gulp build
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs dreamGame
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls dreamGame
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

above is the error log when i run npm build.someone help me figure it out.

in gulpfile
gulp.task("build", function(cb) {
    setDistFolder(distFolder);
    gulpSequence(['clean'], ['copyFile', 'html', 'jsMin', 'jsCon', 'img'], ['revHtml', 'revCss', 'revJs'])(cb)
});

in package.json

"scripts": {
        "server": "gulp connect",
        "dev": "gulp watch",
        "build": "gulp build"
   },

thanks.

**Comment by KenanY** [comment]
@johnzhu12 What happens if you just run `gulp build`?

**Comment by johnzhu12** [comment]
@KenanY 
 it shows the following message:

events.js:160
      throw er; // Unhandled 'error' event
      ^
Error
    at new JS_Parse_Error (eval at <anonymous> (/Users/zhujohn/Desktop/Git_workSpace/cubee.lot.admin.h5/lottery_admin/_build/node_modules/.npminstall/uglify-js/2.6.4/uglify-js/tools/node.js:28:1), <anonymous>:1534:18)
    at js_error (eval at <anonymous> (/Users/zhujohn/Desktop/Git_workSpace/cubee.lot.admin.h5/lottery_admin/_build/node_modules/.npminstall/uglify-js/2.6.4/uglify-js/tools/node.js:28:1), <anonymous>:1542:11)
    at croak (eval at <anonymous> (/Users/zhujohn/Desktop/Git_workSpace/cubee.lot.admin.h5/lottery_admin/_build/node_modules/.npminstall/uglify-js/2.6.4/uglify-js/tools/node.js:28:1), <anonymous>:2089:9)
    at token_error (eval at <anonymous> (/Users/zhujohn/Desktop/Git_workSpace/cubee.lot.admin.h5/lottery_admin/_build/node_modules/.npminstall/uglify-js/2.6.4/uglify-js/tools/node.js:28:1), <anonymous>:2097:9)
    at unexpected (eval at <anonymous> (/Users/zhujohn/Desktop/Git_workSpace/cubee.lot.admin.h5/lottery_admin/_build/node_modules/.npminstall/uglify-js/2.6.4/uglify-js/tools/node.js:28:1), <anonymous>:2103:9)
    at expr_atom (eval at <anonymous> (/Users/zhujohn/Desktop/Git_workSpace/cubee.lot.admin.h5/lottery_admin/_build/node_modules/.npminstall/uglify-js/2.6.4/uglify-js/tools/node.js:28:1), <anonymous>:2630:9)
    at maybe_unary (eval at <anonymous> (/Users/zhujohn/Desktop/Git_workSpace/cubee.lot.admin.h5/lottery_admin/_build/node_modules/.npminstall/uglify-js/2.6.4/uglify-js/tools/node.js:28:1), <anonymous>:2792:19)
    at expr_ops (eval at <anonymous> (/Users/zhujohn/Desktop/Git_workSpace/cubee.lot.admin.h5/lottery_admin/_build/node_modules/.npminstall/uglify-js/2.6.4/uglify-js/tools/node.js:28:1), <anonymous>:2827:24)
    at maybe_conditional (eval at <anonymous> (/Users/zhujohn/Desktop/Git_workSpace/cubee.lot.admin.h5/lottery_admin/_build/node_modules/.npminstall/uglify-js/2.6.4/uglify-js/tools/node.js:28:1), <anonymous>:2832:20)
    at maybe_assign (eval at <anonymous> (/Users/zhujohn/Desktop/Git_workSpace/cubee.lot.admin.h5/lottery_admin/_build/node_modules/.npminstall/uglify-js/2.6.4/uglify-js/tools/node.js:28:1), <anonymous>:2856:20)

**Comment by KenanY** [comment]
@johnzhu12 Yeah so this is the fault of your build script, not `npm`. You gotta fix that error first. Looks like `uglify-js` is unable to parse one of your files.
