### ISSUE TITLE
everytime i try something with npm i get this error

### ISSUE THREAD

**Issue by russcomin** [npm/npm#15440]
module.js:472
    throw err;
    ^

Error: Cannot find module 'wrappy'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Jovan\AppData\Roaming\npm\node_modules\npm\node_modules\once\once.js:1:76)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

Pls help if you can! Thanks

**Comment by legodude17** [comment]
I would suggest deleting `npm` and reinstalling, because it looks like your installation is broken.

**Comment by russcomin** [comment]
I got it! Thanks,if someone have same problem i suggest to do that
