### ISSUE TITLE
yeoman install error

### ISSUE THREAD

**Issue by psib3r** [npm/npm#15457]
#### I'm opening this issue because:

  - [ ] npm is not installing yeoman.

#### How can the CLI team reproduce the problem?
```
0 info it worked if it ends with ok
1 verbose cli [ 'c:\\PROGRA~1\\nodejs\\node.exe',
1 verbose cli   'c:\\PROGRA~1\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'yo' ]
2 info using npm@4.0.5
3 info using node@v7.4.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData yo
8 silly fetchNamedPackageData yo
9 silly mapToRegistry name yo
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'yo',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'yo',
12 silly mapToRegistry   name: 'yo',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/yo
14 verbose request uri https://registry.npmjs.org/yo
15 verbose request no auth needed
16 info attempt registry request try #1 at 8:26:04 AM
17 verbose request id 4f6b289e6c407f9d
18 http request GET https://registry.npmjs.org/yo
19 info retry will retry, error on last attempt: Error: connect ECONNREFUSED 151.101.192.162:443
20 info attempt registry request try #2 at 8:26:15 AM
21 http request GET https://registry.npmjs.org/yo
22 info retry will retry, error on last attempt: Error: connect ECONNREFUSED 151.101.192.162:443
23 info attempt registry request try #3 at 8:27:16 AM
24 http request GET https://registry.npmjs.org/yo
25 silly fetchPackageMetaData Error: connect ECONNREFUSED 151.101.192.162:443
25 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1022:11)
25 silly fetchPackageMetaData     at exports._exceptionWithHostPort (util.js:1045:20)
25 silly fetchPackageMetaData     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
25 silly fetchPackageMetaData  error for yo { Error: connect ECONNREFUSED 151.101.192.162:443
25 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1022:11)
25 silly fetchPackageMetaData     at exports._exceptionWithHostPort (util.js:1045:20)
25 silly fetchPackageMetaData     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
25 silly fetchPackageMetaData   code: 'ECONNREFUSED',
25 silly fetchPackageMetaData   errno: 'ECONNREFUSED',
25 silly fetchPackageMetaData   syscall: 'connect',
25 silly fetchPackageMetaData   address: '151.101.192.162',
25 silly fetchPackageMetaData   port: 443 }
26 silly rollbackFailedOptional Starting
27 verbose stack TypeError: Cannot read property 'path' of null
27 verbose stack     at Installer.rollbackFailedOptional (c:\PROGRA~1\nodejs\node_modules\npm\lib\install.js:505:29)
27 verbose stack     at Array.<anonymous> (c:\PROGRA~1\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
27 verbose stack     at LOOP (c:\PROGRA~1\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
27 verbose stack     at c:\PROGRA~1\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:18:7
27 verbose stack     at c:\PROGRA~1\nodejs\node_modules\npm\lib\install.js:331:5
27 verbose stack     at Array.<anonymous> (c:\PROGRA~1\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
27 verbose stack     at LOOP (c:\PROGRA~1\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
27 verbose stack     at chain (c:\PROGRA~1\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
27 verbose stack     at c:\PROGRA~1\nodejs\node_modules\npm\lib\install.js:288:5
27 verbose stack     at c:\PROGRA~1\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:16:22
28 verbose cwd C:\
29 error Windows_NT 10.0.10586
30 error argv "c:\\PROGRA~1\\nodejs\\node.exe" "c:\\PROGRA~1\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "yo"
31 error node v7.4.0
32 error npm  v4.0.5
33 error Cannot read property 'path' of null
34 error If you need help, you may report this error at:
34 error     <https://github.com/npm/npm/issues>
35 verbose exit [ 1, true ]
```

**Comment by psib3r** [comment]
Actually resolved this myself, I was behind a proxy and needed to set the config in npm
