### ISSUE TITLE
'Failed' attempts when trying to push changes using git through codeship [gulp static] full logs included

### ISSUE THREAD

**Issue by 1926dev** [npm/npm#15473]
#### I'm opening this issue because:

  - [x] npm is doing something I don't understand.

#### What's going wrong?

  - [Failed] Pushing changes form local repository to live environment, using git, through codeship

#### How can the CLI team reproduce the problem?

  - Looking for any support or direction to resolve this issue

### supporting information:

At first, I received the following error when trying to run build:

    module.js:340
    throw err;
    ^
    Error: Cannot find module 'gulp-debug'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/rof/src/bitbucket.org/aj axmonk/ss360/gulpfile.js:8:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

Then I ran a few commands per request, trying to fix the issue. One of which was:

    npm install gulp-debug --save

After this command, I then recieved the follwing error on the gulp static step of the build process:

    /home/rof/src/bitbucket.org/ajaxmonk/ss360/node_modules/gulp-debug/index.js:2
    const path = require('path');
    ^^^^^
    SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/rof/src/bitbucket.org/ajaxmonk/ss360/gulpfile.js:8:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

Now the terminal gives the following information:

    iMac:name user$ npm start

    > ss360@0.0.65 start /Users/user/name
    > node server

    module.js:471
        throw err;
        ^

    Error: Cannot find module 'express'
        at Function.Module._resolveFilename (module.js:469:15)
        at Function.Module._load (module.js:417:25)
        at Module.require (module.js:497:17)
        at require (internal/module.js:20:19)
        at Object.<anonymous> (/Users/user/name/ss-modules/setup/index.js:7:15)
        at Module._compile (module.js:570:32)
        at Object.Module._extensions..js (module.js:579:10)
        at Module.load (module.js:487:32)
        at tryModuleLoad (module.js:446:12)
        at Function.Module._load (module.js:438:3)

    npm ERR! Darwin 16.3.0
    npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
    npm ERR! node v6.9.4
    npm ERR! npm  v3.10.10
    npm ERR! code ELIFECYCLE
    npm ERR! ss360@0.0.65 start: `node server`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the name@0.0.65 start script 'node server'.
    npm ERR! Make sure you have the latest version of node.js and npm installed.
    npm ERR! If you do, this is most likely a problem with the name package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node server
    npm ERR! You can get information on how to open an issue for this project with:
    npm ERR!     npm bugs name
    npm ERR! Or if that isn't available, you can get their info via:
    npm ERR!     npm owner ls name
    npm ERR! There is likely additional logging output above.
    npm WARN Local package.json exists, but node_modules missing, did you mean to install?

    npm ERR! Please include the following file with any support request:
    npm ERR!     /Users/user/name/npm-debug.log

The terminal also requested to include the following file:

    npm ERR! Please include the following file with any support request:
    npm ERR!     /Users/andrew/ss360/npm-debug.log

However, I cannot find a npm-debug.log in the folder listed. Instead, I see one just outside of that folder in my root directory.

Root npm-debug.log

    0 info it worked if it ends with ok
    1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'gulp' ]
    2 info using npm@3.10.10
    3 info using node@v6.9.4
    4 verbose config Skipping project config: /Users/andrew/.npmrc. (matches userconfig)
    5 verbose stack Error: ENOENT: no such file or directory, open '/Users/andrew/package.json'
    5 verbose stack     at Error (native)
    6 verbose cwd /Users/andrew
    7 error Darwin 16.3.0
    8 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "gulp"
    9 error node v6.9.4
    10 error npm  v3.10.10
    11 error path /Users/andrew/package.json
    12 error code ENOENT
    13 error errno -2
    14 error syscall open
    15 error enoent ENOENT: no such file or directory, open '/Users/andrew/package.json'
    16 error enoent ENOENT: no such file or directory, open '/Users/andrew/package.json'
    16 error enoent This is most likely not a problem with npm itself
    16 error enoent and is related to npm not being able to find a file.
    17 verbose exit [ -2, true ]

**Comment by legodude17** [comment]
Do you have a package.json in the directory you want to use `npm start` in?
