### ISSUE TITLE
Failure to build Wire in a Whonix VM

### ISSUE THREAD

**Issue by hThoreau** [npm/npm#15546]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [X] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
npm fails to install wire2.11.2685 at a Whonix 13.0.0.1.4 Virtual Machine (based on Debian
Jessie 8.7). EACCES errors are constantly reported.
#### How can the CLI team reproduce the problem?
**First Attempt**

1. `git clone git https://github.com/wireapp/wire-desktop.git`
2. Install Node.js with npm using [the following instructions](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions)
3. `cd wire*`
4. `sudo npm install`
5. Yields the following result:
```
npm WARN cannot run in wd wire-desktop@ cd electron && npm install (wd=/home/user/wire-desktop)
 
> nslog@3.0.0 install /home/user/wire-desktop/node_modules/electron-rebuild/node_modules/nslog
> node-gyp rebuild

/bin/sh: 1: node: not found
gyp: Call to 'node -e "require('nan')"' returned exit status 127. while trying to load binding.gyp
gyp ERR! configure error 
 Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:344:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
gyp ERR! System Linux 3.16.0-4-686-pae
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/user/wire-desktop/node_modules/electron-rebuild/node_modules/nslog
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! error rolling back Error: ENOTEMPTY, rmdir '/home/user/wire-desktop/node_modules/electron-rebuild/node_modules/lodash/array'
npm ERR! error rolling back  electron-rebuild@1.4.0 { [Error: ENOTEMPTY, rmdir '/home/user/wire-desktop/node_modules/electron-rebuild/node_modules/lodash/array']
npm ERR! error rolling back   errno: 53,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   path: '/home/user/wire-desktop/node_modules/electron-rebuild/node_modules/lodash/array' }
npm ERR! nslog@3.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nslog@3.0.0 install script.
npm ERR! This is most likely a problem with the nslog package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls nslog
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.16.0-4-686-pae
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/user/wire-desktop
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR! Error: ENOENT, lstat '/home/user/wire-desktop/node_modules/electron-rebuild/node_modules/promise/node_modules/asap/raw.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.16.0-4-686-pae
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/user/wire-desktop
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! path /home/user/wire-desktop/node_modules/electron-rebuild/node_modules/promise/node_modules/asap/raw.js
npm ERR! fstream_path /home/user/wire-desktop/node_modules/electron-rebuild/node_modules/promise/node_modules/asap/raw.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (evalmachine.<anonymous>:107:15)
npm ERR! Error: ENOENT, lstat '/home/user/wire-desktop/node_modules/electron-rebuild/node_modules/npm/lib/fetch-package-metadata.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.16.0-4-686-pae
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/user/wire-desktop
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! path /home/user/wire-desktop/node_modules/electron-rebuild/node_modules/npm/lib/fetch-package-metadata.js
npm ERR! fstream_path /home/user/wire-desktop/node_modules/electron-rebuild/node_modules/npm/lib/fetch-package-metadata.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (evalmachine.<anonymous>:107:15)
npm WARN engine deep-extend@0.4.1: wanted: {"node":">=0.12.0","iojs":">=1.0.0"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine request@2.79.0: wanted: {"node":">= 4"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine form-data@2.1.2: wanted: {"node":">= 0.12"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine hawk@3.1.3: wanted: {"node":">=0.10.32"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine boom@2.10.1: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.29","npm":"1.4.21"})
\
> electron@1.4.15 postinstall /home/user/wire-desktop/node_modules/electron
> node install.js

sh: 1: node: not found
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please readis
/usr/share/doc/nodejs/README.Debian
 
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/user/wire-desktop/npm-debug.log
npm ERR! not ok code 0
```
Corresponding npm-debug.log: [npm-debug.zip](https://github.com/wireapp/wire-desktop/files/721683/npm-debug.zip)

**Second attempt (troubleshooting)**
Attempted to correct the installation process following the [troubleshooting advice for permission errors](https://github.com/npm/npm/wiki/Troubleshooting). The following commands occurred without signaling warnings nor errors:
```
user@host:~/wire-desktop$ sudo chown -R $(whoami) "$HOME/.npm"
user@host:~/wire-desktop$ sudo npm install express -g
user@host:~/wire-desktop$ echo 'export PATH=$HOME/local/bin:$PATH' >> ~/.bashrc
user@host:~/wire-desktop$ . ~/.bashrc
user@host:~/wire-desktop$ mkdir ~/local
user@host:~/wire-desktop$ mkdir ~/node-latest-install
user@host:~/wire-desktop$ cd ~/node-latest-install
user@host:~/wire-desktop$ curl http://nodejs.org/dist/node-latest.tar.gz | tar xz --strip-components=1
user@host:~/wire-desktop$ ./configure --prefix=~/local
user@host:~/wire-desktop$ make install
user@host:~/wire-desktop$ curl https://www.npmjs.com/install.sh | sh
```
But when we get to the installing:
```
user@host:~/wire-desktop$ npm install

> wire-desktop@ preinstall /home/user/wire-desktop
> cd electron && npm install

npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
npm WARN checkPermissions Missing write access to /home/user/wire-desktop/electron
wire@2.11.2687 /home/user/wire-desktop/electron
├─┬ auto-launch@5.0.1 
│ ├── applescript@1.0.0 
│ ├─┬ mkdirp@0.5.1 
│ │ └── minimist@0.0.8 
│ ├── path-is-absolute@1.0.1 
│ ├── untildify@3.0.2 
│ └── winreg@1.2.2 
├─┬ googleapis@2.1.6 
│ ├── async@1.5.2 
│ ├─┬ gapitoken@0.1.5 
│ │ └─┬ jws@3.0.0 
│ │   ├─┬ base64url@1.0.6 
│ │   │ ├─┬ concat-stream@1.4.10 
│ │   │ │ └── typedarray@0.0.6 
│ │   │ └─┬ meow@2.0.0 
│ │   │   ├─┬ camelcase-keys@1.0.0 
│ │   │   │ └── camelcase@1.2.1 
│ │   │   ├─┬ indent-string@1.2.2 
│ │   │   │ └── repeating@1.1.3 
│ │   │   └── object-assign@1.0.0 
│ │   └─┬ jwa@1.0.2 
│ │     ├── base64url@0.0.6 
│ │     ├── buffer-equal-constant-time@1.0.1 
│ │     └─┬ ecdsa-sig-formatter@1.0.9 
│ │       ├── base64url@2.0.0 
│ │       └── safe-buffer@5.0.1 
│ ├─┬ google-auth-library@0.9.10 
│ │ ├── async@1.4.2 
│ │ ├─┬ gtoken@1.2.1 
│ │ │ ├─┬ google-p12-pem@0.1.1 
│ │ │ │ └── node-forge@0.6.47 
│ │ │ └── mime@1.3.4 
│ │ ├── lodash.noop@3.0.1 
│ │ └─┬ request@2.74.0 
│ │   ├─┬ bl@1.1.2 
│ │   │ └─┬ readable-stream@2.0.6 
│ │   │   └── isarray@1.0.0 
│ │   ├─┬ form-data@1.0.1 
│ │   │ └── async@2.1.4 
│ │   └── qs@6.2.1 
│ ├─┬ request@2.65.0 
│ │ ├─┬ bl@1.0.3 
│ │ │ └─┬ readable-stream@2.0.6 
│ │ │   ├── core-util-is@1.0.2 
│ │ │   ├── inherits@2.0.3 
│ │ │   ├── isarray@1.0.0 
│ │ │   ├── process-nextick-args@1.0.7 
│ │ │   ├── string_decoder@0.10.31 
│ │ │   └── util-deprecate@1.0.2 
│ │ ├─┬ form-data@1.0.1 
│ │ │ └─┬ async@2.1.4 
│ │ │   └── lodash@4.17.4 
│ │ ├─┬ http-signature@0.11.0 
│ │ │ ├── asn1@0.1.11 
│ │ │ ├── assert-plus@0.1.5 
│ │ │ └── ctype@0.5.3 
│ │ ├── qs@5.2.1 
│ │ └── tough-cookie@2.2.2 
│ └── string-template@0.2.1 
├─┬ image-type@2.1.0 
│ ├── file-type@3.9.0 
│ └─┬ meow@3.7.0 
│   ├─┬ camelcase-keys@2.1.0 
│   │ └── camelcase@2.1.1 
│   ├── decamelize@1.2.0 
│   ├─┬ loud-rejection@1.6.0 
│   │ ├─┬ currently-unhandled@0.4.1 
│   │ │ └── array-find-index@1.0.2 
│   │ └── signal-exit@3.0.2 
│   ├── map-obj@1.0.1 
│   ├─┬ normalize-package-data@2.3.5 
│   │ ├── hosted-git-info@2.1.5 
│   │ ├─┬ is-builtin-module@1.0.0 
│   │ │ └── builtin-modules@1.1.1 
│   │ ├── semver@5.3.0 
│   │ └─┬ validate-npm-package-license@3.0.1 
│   │   ├─┬ spdx-correct@1.0.2 
│   │   │ └── spdx-license-ids@1.2.2 
│   │   └── spdx-expression-parse@1.0.4 
│   ├── object-assign@4.1.1 
│   ├─┬ read-pkg-up@1.0.1 
│   │ ├─┬ find-up@1.1.2 
│   │ │ └── path-exists@2.1.0 
│   │ └─┬ read-pkg@1.1.0 
│   │   ├─┬ load-json-file@1.1.0 
│   │   │ ├── graceful-fs@4.1.11 
│   │   │ ├─┬ parse-json@2.2.0 
│   │   │ │ └─┬ error-ex@1.3.0 
│   │   │ │   └── is-arrayish@0.2.1 
│   │   │ ├── pify@2.3.0 
│   │   │ └─┬ strip-bom@2.0.0 
│   │   │   └── is-utf8@0.2.1 
│   │   └── path-type@1.1.0 
│   ├─┬ redent@1.0.0 
│   │ ├─┬ indent-string@2.1.0 
│   │ │ └─┬ repeating@2.0.1 
│   │ │   └─┬ is-finite@1.0.2 
│   │ │     └── number-is-nan@1.0.1 
│   │ └─┬ strip-indent@1.0.1 
│   │   └── get-stdin@4.0.1 
│   └── trim-newlines@1.0.0 
├── minimist@1.2.0 
├── node-addressbook@1.0.1  (git+https://github.com/wireapp/node-addressbook.git#7975abcd52ea97ccc511c80f7872b854f51510b8)
├─┬ open-graph@0.2.1 
│ └─┬ cheerio@0.17.0 
│   ├─┬ CSSselect@0.4.1 
│   │ ├── CSSwhat@0.4.7 
│   │ └── domutils@1.4.3 
│   ├─┬ dom-serializer@0.0.1 
│   │ └── domelementtype@1.1.3 
│   ├── entities@1.1.1 
│   ├─┬ htmlparser2@3.7.3 
│   │ ├── domelementtype@1.3.0 
│   │ ├── domhandler@2.2.1 
│   │ ├── domutils@1.5.1 
│   │ ├── entities@1.0.0 
│   │ └─┬ readable-stream@1.1.14 
│   │   └── isarray@0.0.1 
│   └── lodash@2.4.2 
├─┬ raygun@0.9.0 
│ ├── object-to-human-string@0.0.3 
│ └── stack-trace@0.0.6 
├─┬ request@2.76.0 
│ ├── aws-sign2@0.6.0 
│ ├── aws4@1.5.0 
│ ├── caseless@0.11.0 
│ ├─┬ combined-stream@1.0.5 
│ │ └── delayed-stream@1.0.0 
│ ├── extend@3.0.0 
│ ├── forever-agent@0.6.1 
│ ├─┬ form-data@2.1.2 
│ │ └── asynckit@0.4.0 
│ ├─┬ har-validator@2.0.6 
│ │ ├─┬ chalk@1.1.3 
│ │ │ ├── ansi-styles@2.2.1 
│ │ │ ├── escape-string-regexp@1.0.5 
│ │ │ ├─┬ has-ansi@2.0.0 
│ │ │ │ └── ansi-regex@2.1.1 
│ │ │ ├── strip-ansi@3.0.1 
│ │ │ └── supports-color@2.0.0 
│ │ ├─┬ commander@2.9.0 
│ │ │ └── graceful-readlink@1.0.1 
│ │ ├─┬ is-my-json-valid@2.15.0 
│ │ │ ├── generate-function@2.0.0 
│ │ │ ├─┬ generate-object-property@1.2.0 
│ │ │ │ └── is-property@1.0.2 
│ │ │ ├── jsonpointer@4.0.1 
│ │ │ └── xtend@4.0.1 
│ │ └─┬ pinkie-promise@2.0.1 
│ │   └── pinkie@2.0.4 
│ ├─┬ hawk@3.1.3 
│ │ ├── boom@2.10.1 
│ │ ├── cryptiles@2.0.5 
│ │ ├── hoek@2.16.3 
│ │ └── sntp@1.0.9 
│ ├─┬ http-signature@1.1.1 
│ │ ├── assert-plus@0.2.0 
│ │ ├─┬ jsprim@1.3.1 
│ │ │ ├── extsprintf@1.0.2 
│ │ │ ├── json-schema@0.2.3 
│ │ │ └── verror@1.3.6 
│ │ └─┬ sshpk@1.10.2 
│ │   ├── asn1@0.2.3 
│ │   ├── assert-plus@1.0.0 
│ │   ├── bcrypt-pbkdf@1.0.0 
│ │   ├─┬ dashdash@1.14.1 
│ │   │ └── assert-plus@1.0.0 
│ │   ├── ecc-jsbn@0.1.1 
│ │   ├─┬ getpass@0.1.6 
│ │   │ └── assert-plus@1.0.0 
│ │   ├── jodid25519@1.0.2 
│ │   ├── jsbn@0.1.0 
│ │   └── tweetnacl@0.14.5 
│ ├── is-typedarray@1.0.0 
│ ├── isstream@0.1.2 
│ ├── json-stringify-safe@5.0.1 
│ ├─┬ mime-types@2.1.14 
│ │ └── mime-db@1.26.0 
│ ├── node-uuid@1.4.7 
│ ├── oauth-sign@0.8.2 
│ ├── qs@6.3.0 
│ ├── stringstream@0.0.5 
│ ├─┬ tough-cookie@2.3.2 
│ │ └── punycode@1.4.1 
│ └── tunnel-agent@0.4.3 
├─┬ spellchecker@3.3.1 
│ └── nan@2.5.0 
└─┬ winston@2.2.0  (git+https://github.com/wireapp/winston.git#6526c40fdf9ef4108091aac298ea954bb26493ae)
  ├── async@1.0.0 
  ├── colors@1.0.3 
  ├── cycle@1.0.3 
  ├── eyes@0.1.8 
  └── pkginfo@0.3.1 

npm ERR! Linux 3.16.0-4-686-pae
npm ERR! argv "/home/user/local/bin/node" "/home/user/local/bin/npm" "install"
npm ERR! node v7.4.0
npm ERR! npm  v4.1.1
npm ERR! path /home/user/wire-desktop/electron
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/home/user/wire-desktop/electron'
npm ERR!  { Error: EACCES: permission denied, access '/home/user/wire-desktop/electron'
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/home/user/wire-desktop/electron' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.
npm ERR! Linux 3.16.0-4-686-pae
npm ERR! argv "/home/user/local/bin/node" "/home/user/local/bin/npm" "install"
npm ERR! node v7.4.0
npm ERR! npm  v4.1.1
npm ERR! path npm-debug.log.381849901
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall open

npm ERR! Error: EACCES: permission denied, open 'npm-debug.log.381849901'
npm ERR!  { Error: EACCES: permission denied, open 'npm-debug.log.381849901'
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'open',
npm ERR!   path: 'npm-debug.log.381849901' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/user/wire-desktop/electron/npm-debug.log
ansi-regex@2.1.1 node_modules/electron-rebuild/node_modules/yargs/node_modules/cliui/node_modules/strip-ansi/node_modules/ansi-regex -> node_modules/ansi-regex
asap@2.0.5 node_modules/electron-rebuild/node_modules/promise/node_modules/asap -> node_modules/asap
balanced-match@0.4.2 node_modules/electron-rebuild/node_modules/rimraf/node_modules/glob/node_modules/minimatch/node_modules/brace-expansion/node_modules/balanced-match -> node_modules/balanced-match
camelcase@2.1.1 node_modules/electron-rebuild/node_modules/yargs/node_modules/camelcase -> node_modules/camelcase
code-point-at@1.1.0 node_modules/electron-rebuild/node_modules/yargs/node_modules/string-width/node_modules/code-point-at -> node_modules/code-point-at
concat-map@0.0.1 node_modules/electron-rebuild/node_modules/rimraf/node_modules/glob/node_modules/minimatch/node_modules/brace-expansion/node_modules/concat-map -> node_modules/concat-map
brace-expansion@1.1.6 node_modules/electron-rebuild/node_modules/rimraf/node_modules/glob/node_modules/minimatch/node_modules/brace-expansion -> node_modules/brace-expansion
core-js@1.2.7 node_modules/electron-rebuild/node_modules/babel-runtime/node_modules/core-js -> node_modules/core-js
decamelize@1.2.0 node_modules/electron-rebuild/node_modules/yargs/node_modules/decamelize -> node_modules/decamelize
- ansi-regex@2.1.1 node_modules/electron-rebuild/node_modules/yargs/node_modules/string-width/node_modules/strip-ansi/node_modules/ansi-regex
- strip-ansi@3.0.1 node_modules/electron-rebuild/node_modules/yargs/node_modules/string-width/node_modules/strip-ansi
invert-kv@1.0.0 node_modules/electron-rebuild/node_modules/yargs/node_modules/os-locale/node_modules/lcid/node_modules/invert-kv -> node_modules/invert-kv
lcid@1.0.0 node_modules/electron-rebuild/node_modules/yargs/node_modules/os-locale/node_modules/lcid -> node_modules/lcid
minimatch@3.0.3 node_modules/electron-rebuild/node_modules/rimraf/node_modules/glob/node_modules/minimatch -> node_modules/minimatch
number-is-nan@1.0.1 node_modules/electron-rebuild/node_modules/yargs/node_modules/string-width/node_modules/is-fullwidth-code-point/node_modules/number-is-nan -> node_modules/number-is-nan
is-fullwidth-code-point@1.0.0 node_modules/electron-rebuild/node_modules/yargs/node_modules/string-width/node_modules/is-fullwidth-code-point -> node_modules/is-fullwidth-code-point
os-locale@1.4.0 node_modules/electron-rebuild/node_modules/yargs/node_modules/os-locale -> node_modules/os-locale
strip-ansi@3.0.1 node_modules/electron-rebuild/node_modules/yargs/node_modules/cliui/node_modules/strip-ansi -> node_modules/strip-ansi
string-width@1.0.2 node_modules/electron-rebuild/node_modules/yargs/node_modules/string-width -> node_modules/string-width
window-size@0.1.4 node_modules/electron-rebuild/node_modules/yargs/node_modules/window-size -> node_modules/window-size
wrap-ansi@2.1.0 node_modules/electron-rebuild/node_modules/yargs/node_modules/cliui/node_modules/wrap-ansi -> node_modules/wrap-ansi
cliui@3.2.0 node_modules/electron-rebuild/node_modules/yargs/node_modules/cliui -> node_modules/cliui
wrappy@1.0.2 node_modules/electron-rebuild/node_modules/glob/node_modules/inflight/node_modules/wrappy -> node_modules/wrappy
y18n@3.2.1 node_modules/electron-rebuild/node_modules/yargs/node_modules/y18n -> node_modules/y18n
- babel-runtime node_modules/electron-rebuild/node_modules/babel-runtime
- inflight node_modules/electron-rebuild/node_modules/glob/node_modules/inflight
- once node_modules/electron-rebuild/node_modules/glob/node_modules/once
- wrappy@1.0.2 node_modules/electron-rebuild/node_modules/glob/node_modules/once/node_modules/wrappy
- promise node_modules/electron-rebuild/node_modules/promise
- rimraf node_modules/electron-rebuild/node_modules/rimraf
- glob node_modules/electron-rebuild/node_modules/rimraf/node_modules/glob
- yargs node_modules/electron-rebuild/node_modules/yargs
wire-desktop@ /home/user/wire-desktop
└── (empty)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-mac@^1.0.1 (node_modules/electron-builder/node_modules/7zip-bin/node_modules/7zip-bin-mac):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-mac@1.0.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"ia32"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-win@^2.0.2 (node_modules/electron-builder/node_modules/7zip-bin/node_modules/7zip-bin-win):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-win@2.0.2: wanted {"os":"win32","arch":"any"} (current: {"os":"linux","arch":"ia32"})
npm ERR! Linux 3.16.0-4-686-pae
npm ERR! argv "/home/user/local/bin/node" "/home/user/local/bin/npm" "install"
npm ERR! node v7.4.0
npm ERR! npm  v4.1.1
npm ERR! code ELIFECYCLE

npm ERR! wire-desktop@ preinstall: `cd electron && npm install`
npm ERR! Exit status 243
npm ERR! 
npm ERR! Failed at the wire-desktop@ preinstall script 'cd electron && npm install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the wire-desktop package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cd electron && npm install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs wire-desktop
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls wire-desktop
npm ERR! There is likely additional logging output above.
npm ERR! Linux 3.16.0-4-686-pae
npm ERR! argv "/home/user/local/bin/node" "/home/user/local/bin/npm" "install"
npm ERR! node v7.4.0
npm ERR! npm  v4.1.1
npm ERR! path npm-debug.log.166779853
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall open

npm ERR! Error: EACCES: permission denied, open 'npm-debug.log.166779853'
npm ERR!  { Error: EACCES: permission denied, open 'npm-debug.log.166779853'
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'open',
npm ERR!   path: 'npm-debug.log.166779853' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/user/wire-desktop/npm-debug.log
```
Resulting debug log: https://gist.github.com/hThoreau/c7a5a021084998c8ff76b08be61ee97d

### supporting information:

 - `npm -v` prints: `v7.4.0`
 - `node -v` prints: `4.1.1`
 - `npm config get registry` prints: `https://registry.npmjs.org/`

**Comment by watilde** [comment]
Hello! According to the error log, you seem to be using very old version of Node.js/npm.
> npm ERR! node -v v0.10.29
> npm ERR! npm -v 1.4.21

Can you re-check about it?

**Comment by hThoreau** [comment]
Yes, but you see, i did that by the second attempt, outlined above. By the end of the post it reads:

> npm ERR! node v7.4.0
npm ERR! npm  v4.1.1

**Comment by legodude17** [comment]
What does your `package.json` look like? Who owns `/home/user/wire-desktop/electron`?

**Comment by hThoreau** [comment]
Well, I found more than one package.json, the one in the "wire-desktop" folder [looks like this](https://gist.github.com/hThoreau/ae71fd3be2163185f126325e28897fab) and the one in the "electron" folder [looks like this](https://gist.github.com/hThoreau/883880f5ee80ce7fdfc5f30bbb390855). The owner of the electron folder is the user "user".
