### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by mdiogenes** [npm/npm#15575]
#### I'm opening this issue because:

  - [x ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### How can the CLI team reproduce the problem?
when i do the installation 
npm install at the finish i founs some errors
and i can run gulp

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS 
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [x ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
@mdiogenes Please upload the `npm-debug.log` file to <https://gist.github.com/> and post the link here.

**Comment by mdiogenes** [comment]
ok sorry this is the link 
thank you
https://gist.github.com/mdiogenes/d55eab2599d1bfe9b00182fef1fffc9f

**Comment by KenanY** [comment]
@mdiogenes Have you tried using the `--no-bin-links` flag?

**Comment by mdiogenes** [comment]
I try
 
root@homestead:/home/vagrant/Code/protecms# npm install --no-bin-links

/home/vagrant/Code/protecms
└── gulp@3.9.1

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

but then i can't execute the command gulp
this is the answer:

root@homestead:/home/vagrant/Code/protecms# gulp
[19:17:48] Using gulpfile /home/vagrant/Code/protecms/gulpfile.js
[19:17:48] Starting 'all'...
[19:17:48] Starting 'sass'...
[19:17:50] 'sass' errored after 1.88 s
[19:17:50] Error: ENOENT: no such file or directory, scandir '/home/vagrant/Code/protecms/node_modules/node-sass/vendor'
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at Object.getInstalledBinaries (/home/vagrant/Code/protecms/node_modules/node-sass/lib/extensions.js:121:13)
    at foundBinariesList (/home/vagrant/Code/protecms/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/home/vagrant/Code/protecms/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/home/vagrant/Code/protecms/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/home/vagrant/Code/protecms/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/home/vagrant/Code/protecms/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
[19:17:50] 'all' errored after 1.91 s
[19:17:50] Error in plugin 'run-sequence(sass)'
Message:
    ENOENT: no such file or directory, scandir '/home/vagrant/Code/protecms/node_modules/node-sass/vendor'
Details:
    errno: -2
    code: ENOENT
    syscall: scandir
    path: /home/vagrant/Code/protecms/node_modules/node-sass/vendor
Stack:
Error: ENOENT: no such file or directory, scandir '/home/vagrant/Code/protecms/node_modules/node-sass/vendor'
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at Object.getInstalledBinaries (/home/vagrant/Code/protecms/node_modules/node-sass/lib/extensions.js:121:13)
    at foundBinariesList (/home/vagrant/Code/protecms/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/home/vagrant/Code/protecms/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/home/vagrant/Code/protecms/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/home/vagrant/Code/protecms/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/home/vagrant/Code/protecms/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)

i don't understand what's the problem 
thank you

**Comment by KenanY** [comment]
@mdiogenes Looks like you are running `gulp` just fine. There's just something wrong with your gulpfile's sass task.
