### ISSUE TITLE
Cannot publish to own hosted npm repository

### ISSUE THREAD

**Issue by dokaspar** [npm/npm#15587]
I have installed Nexus 3 with three NPM repositories that I've set up using parts of [this script](https://github.com/sonatype/nexus-book-examples/blob/nexus-3.x/scripting/complex-script/npmAndBowerRepositories.groovy):

1. an npm proxy repository 'npmjs-org' pointing to https://registry.npmjs.org
2. an npm hosted repository 'npm-public'
3. an npm group repository 'npm-public-group' that contains 'npm-public' and 'npmjs-org' (in this order)

On my client, I've configured the npm group as the registry (using the default user admin/admin123 with full Nexus access rights):

```
_auth=YWRtaW46YWRtaW4xMjMK
email=<my@email>
registry=http://myhost:8081/nexus3/repository/public-npm-group/
```

I've successfully tested `npm install <pkg>`, any desired package is downloaded from the npmjs-org repository. But when I try to `npm publish` my own package to my own hosted 'npm-public' repository, I always encounter an `error publish Failed PUT 401`

```
npm publish --registry=http://myhost:8081/nexus3/repository/public-npm
0 info it worked if it ends with ok
1 verbose cli [ '/opt/nodejs/5.9.0/bin/node',
1 verbose cli   '/opt/nodejs/current/npm',
1 verbose cli   'publish',
1 verbose cli   '--registry=http://myhost:8081/nexus3/repository/public-npm' ]
2 info using npm@3.7.3
3 info using node@v5.9.0
4 verbose publish [ '.' ]
5 silly cache add args [ '.', null ]
6 verbose cache add spec .
7 silly cache add parsed spec Result {
7 silly cache add   raw: '.',
7 silly cache add   scope: null,
7 silly cache add   name: null,
7 silly cache add   rawSpec: '.',
7 silly cache add   spec: '/root/npmtest/npm-test-project',
7 silly cache add   type: 'directory' }
8 verbose addLocalDirectory /root/.npm/npm-test-project/0.0.0/package.tgz not in flight; packing
9 verbose correctMkdir /root/.npm correctMkdir not in flight; initializing
10 info lifecycle npm-test-project@0.0.0~prepublish: npm-test-project@0.0.0
11 silly lifecycle npm-test-project@0.0.0~prepublish: no script for prepublish, continuing
12 verbose tar pack [ '/root/.npm/npm-test-project/0.0.0/package.tgz',
12 verbose tar pack   '/root/npmtest/npm-test-project' ]
13 verbose tarball /root/.npm/npm-test-project/0.0.0/package.tgz
14 verbose folder /root/npmtest/npm-test-project
15 verbose addLocalTarball adding from inside cache /root/.npm/npm-test-project/0.0.0/package.tgz
16 verbose correctMkdir /root/.npm correctMkdir not in flight; initializing
17 silly cache afterAdd npm-test-project@0.0.0
18 verbose afterAdd /root/.npm/npm-test-project/0.0.0/package/package.json not in flight; writing
19 verbose correctMkdir /root/.npm correctMkdir not in flight; initializing
20 verbose afterAdd /root/.npm/npm-test-project/0.0.0/package/package.json written
21 silly publish { name: 'npm-test-project',
21 silly publish   version: '0.0.0',
21 silly publish   description: 'very first package',
21 silly publish   main: 'index.js',
21 silly publish   publishConfig: { registry: 'http://myhost:8081/nexus3/repository/public-npm/' },
21 silly publish   readme: 'ERROR: No README data found!',
21 silly publish   _id: 'npm-test-project@0.0.0',
21 silly publish   scripts: {},
21 silly publish   _shasum: '182a1f183e0ff782c6b76af6a537f010764f7774',
21 silly publish   _from: '.' }
22 verbose getPublishConfig { registry: 'http://myhost:8081/nexus3/repository/public-npm/' }
23 silly mapToRegistry name npm-test-project
24 silly mapToRegistry using default registry
25 silly mapToRegistry registry http://myhost:8081/nexus3/repository/public-npm/
26 silly mapToRegistry uri http://myhost:8081/nexus3/repository/public-npm/npm-test-project
27 verbose publish registryBase http://myhost:8081/nexus3/repository/public-npm/
28 silly publish uploading /root/.npm/npm-test-project/0.0.0/package.tgz
29 verbose request uri http://myhost:8081/nexus3/repository/public-npm/npm-test-project
30 verbose request sending authorization for write operation
31 info attempt registry request try #1 at 3:18:55 PM
32 verbose request id 99e18be89de9ef65
33 http request PUT http://myhost:8081/nexus3/repository/public-npm/npm-test-project
34 http 401 http://myhost:8081/nexus3/repository/public-npm/npm-test-project
35 verbose headers { date: 'Thu, 26 Jan 2017 14:18:55 GMT',
35 verbose headers   server: 'Nexus/3.2.0-01 (OSS)',
35 verbose headers   'x-frame-options': 'SAMEORIGIN',
35 verbose headers   'x-content-type-options': 'nosniff',
35 verbose headers   'www-authenticate': 'BASIC realm="Sonatype Nexus Repository Manager"',
35 verbose headers   'content-length': '0' }
36 verbose request invalidating /root/.npm/myhost_8081/nexus3/repository/public-npm/npm-test-project on PUT
37 error publish Failed PUT 401
38 verbose stack Error: 401 Unauthorized
38 verbose stack     at makeError (/opt/nodejs/5.9.0/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
38 verbose stack     at CachingRegistryClient.<anonymous> (/opt/nodejs/5.9.0/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:215:9)
38 verbose stack     at Request._callback (/opt/nodejs/5.9.0/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
38 verbose stack     at Request.self.callback (/opt/nodejs/5.9.0/lib/node_modules/npm/node_modules/request/request.js:199:22)
38 verbose stack     at emitTwo (events.js:100:13)
38 verbose stack     at Request.emit (events.js:185:7)
38 verbose stack     at Request.<anonymous> (/opt/nodejs/5.9.0/lib/node_modules/npm/node_modules/request/request.js:1036:10)
38 verbose stack     at emitOne (events.js:95:20)
38 verbose stack     at Request.emit (events.js:182:7)
38 verbose stack     at IncomingMessage.<anonymous> (/opt/nodejs/5.9.0/lib/node_modules/npm/node_modules/request/request.js:963:12)
39 verbose statusCode 401
40 verbose cwd /root/npmtest/npm-test-project
41 error Linux 2.6.32-573.8.1.el6.x86_64
42 error argv "/opt/nodejs/5.9.0/bin/node" "/opt/nodejs/current/npm" "publish" "--registry=http://myhost:8081/nexus3/repository/public-npm"
43 error node v5.9.0
44 error npm  v3.7.3
45 error code E401
46 error 401 Unauthorized
47 error If you need help, you may report this error at:
47 error     <https://github.com/npm/npm/issues>
48 verbose exit [ 1, true ]
```

I have no idea what's wrong, the admin user has full access rights and downloading works perfectly... any advice would be greatly appreciated.

**Comment by dokaspar** [comment]
Hmmm. It seems all that was missing was adding the "npm Bearer Token Realm"
https://books.sonatype.com/nexus-book/3.0/reference/npm.html#_npm_security

**Comment by noherczeg** [comment]
There are two registry entries required currently to be able to work with nexus 3.

I use this in our builder script:
```
echo "//${NPM_REGISTRY}/:_authToken=${NPM_TOKEN}" >> $HOME/.npmrc
echo "//${NPM_DOWNSTREAM_REGISTRY}/:_authToken=${NPM_TOKEN}" >> $HOME/.npmrc
echo "//${NPM_UPSTREAM_REGISTRY}/:_authToken=${NPM_TOKEN}" >> $HOME/.npmrc
```
So in your case:
```
//http://myhost:8081/nexus3/repository
//http://myhost:8081/nexus3/repository/public-npm
```

You need both because for some reason your client needs the repo root defined as well to be able to publish. I also recommend addig the auth token at the end since the separate one is for an older npm api.

**Comment by rukshandangalla** [comment]
@noherczeg Thanks for the info. That was my exact problem while I was setting up hosted repo with nexus 3.7.1. I had to add three separate entries for my hosted, proxy and group repos in the .npmrc file
