### ISSUE TITLE
npm start not working

### ISSUE THREAD

**Issue by mady118** [npm/npm#15594]
Hi,
I am new with node and ReactJS. Struggling with npm start... attaching npm log for details.. need ur help please.
==========================================
package.json
{
  "name": "react-boilerplate",
  "version": "1.0.0",
  "description": "![](http://i.imgur.com/5Bqs5zi.png)",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "Me",
  "license": "ISC",
  "devDependencies": {
    "gulp": "^3.9.1",
    "gulp-clean-css": "^2.0.10",
    "gulp-sass": "^2.3.1"
  },
  "keywords": [
    "fun"
  ],
  "dependencies": {}
}

### npmlog

```
0 info it worked if it ends with ok
1 verbose cli [ 'E:\\nodejs\\node.exe',
1 verbose cli   'E:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.10.10
3 info using node@v6.9.4
4 verbose stack Error: missing script: start
4 verbose stack     at run (E:\nodejs\node_modules\npm\lib\run-script.js:151:19)
4 verbose stack     at E:\nodejs\node_modules\npm\lib\run-script.js:61:5
4 verbose stack     at E:\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:356:5
4 verbose stack     at checkBinReferences_ (E:\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:320:45)
4 verbose stack     at final (E:\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:354:3)
4 verbose stack     at then (E:\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:124:5)
4 verbose stack     at E:\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:243:12
4 verbose stack     at E:\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16
4 verbose stack     at tryToString (fs.js:455:3)
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)
5 verbose cwd E:\React-Boilerplate-master
6 error Windows_NT 6.3.9600
7 error argv "E:\\nodejs\\node.exe" "E:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
8 error node v6.9.4
9 error npm  v3.10.10
10 error missing script: start
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
@mady118 Make sure to define a `"start"` script defined in your `package.json`.
