### ISSUE TITLE
npm install produce error

### ISSUE THREAD

**Issue by sandrobirke** [npm/npm#15590]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ x] Other (_see below for feature requests_):

#### What's going wrong?
After execute `npm install concurrently --save-dev` i get the following Error:
```
npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "concurrently" "--save-dev"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'internal/fs'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Development/setup/npm-debug.log
```
#### How can the CLI team reproduce the problem?

two hours bevor i try the same on a windows-machine and every things wright. maybe there is a Problem with a differnt node or npm version? 

npm-debuglog:
````
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'n' ]
2 info using npm@4.0.5
3 info using node@v7.4.0
4 verbose stack Error: Cannot find module 'internal/fs'
4 verbose stack     at Function.Module._resolveFilename (module.js:470:15)
4 verbose stack     at Function.Module._load (module.js:418:25)
4 verbose stack     at Module.require (module.js:498:17)
4 verbose stack     at require (internal/module.js:20:19)
4 verbose stack     at evalmachine.<anonymous>:18:20
4 verbose stack     at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/cmd-shim/node_modules/graceful-fs/fs.js:11:1)
4 verbose stack     at Module._compile (module.js:571:32)
4 verbose stack     at Object.Module._extensions..js (module.js:580:10)
4 verbose stack     at Module.load (module.js:488:32)
4 verbose stack     at tryModuleLoad (module.js:447:12)
5 verbose cwd /Development/setup
6 error Darwin 16.3.0
7 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "n"
8 error node v7.4.0
9 error npm  v4.0.5
10 error code MODULE_NOT_FOUND
11 error Cannot find module 'internal/fs'
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]
```
### supporting information:

 - `npm -v` prints: 7.4.0
 - `node -v` prints: 4.0.5
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: OS X
 - Network issues:
No

**Comment by sandrobirke** [comment]
Ok,
i uninstall node.js [(http://stackoverflow.com/a/27992473)](http://stackoverflow.com/a/27992473)
and reinstall it with nvm in version 6.9.4.
Now it works very well
