### ISSUE TITLE
 Error: Cannot find module 'semver'

### ISSUE THREAD

**Issue by RobQuads** [npm/npm#15611]
#### I'm opening this issue because:

  - [X ] npm is producing an incorrect install.

#### What's going wrong?

When running any npm commands it producing the following error:

> module.js:472
>     throw err;
>     ^
> 
> Error: Cannot find module 'semver'
>     at Function.Module._resolveFilename (module.js:470:15)
>     at Function.Module._load (module.js:418:25)
>     at Module.require (module.js:498:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (/usr/lib/node_modules/npm/lib/utils/unsupported.js:2:14)
>     at Module._compile (module.js:571:32)
>     at Object.Module._extensions..js (module.js:580:10)
>     at Module.load (module.js:488:32)
>     at tryModuleLoad (module.js:447:12)
>     at Function.Module._load (module.js:439:3)

#### How can the CLI team reproduce the problem?

Run the following Dockerfile 

```
FROM ubuntu:14.04

RUN apt-get update && apt-get -y install curl

# Install Node.js as per <https://nodejs.org/en/download/package-manager/>
RUN curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
RUN apt-get install -y nodejs && node -v
RUN npm install npm@latest -g && npm -v
```

### supporting information:

The Dockerfile below works BUT it will only install npm v3 not v4
```
FROM ubuntu:14.04

RUN apt-get update && apt-get -y install curl

# Install Node.js as per <https://nodejs.org/en/download/package-manager/>
RUN curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
RUN apt-get install -y nodejs && node -v
RUN npm -v
```

Others have hit this but the "remove and reinstall" solution is not applicable here as this is on a newly created system

**Comment by JamieMason** [comment]
This may or may not help but I had the same error recently and it was resolved by using the following install method;

```
FROM node:7.4.0

ADD https://www.npmjs.com/install.sh ./install.sh
RUN sh install.sh
```

**Comment by RobQuads** [comment]
We need to start with ubuntu14:04 for other reasons (this problem actually happens way down a big pipeline in the real scenario, I just simplified it for the re-create)

**Comment by JamieMason** [comment]
That's ok, the important lines are the ADD and RUN – I should've left the FROM out really.

**Comment by nkovacs** [comment]
This works:
```
docker run -it --rm node:4-alpine sh -c 'npm update -g npm && npm --version'
```

This does not:
```
docker run -it --rm node:6-alpine sh -c 'npm update -g npm && npm --version'
```

**Comment by zxaos** [comment]
A temporary workaround is to install npm locally to a clean folder, then replace the global `node_modules` with the local one.

So on the node:6 Dockerfile

```SH
cd ~
npm install npm
rm -rf /usr/local/lib/node_modules
mv node_modules /usr/local/lib/
```

**Comment by Kolyunya** [comment]
@zxaos I tried what you posted but I'm getting the `Error: Cannot find module 'semver'` error while running `npm install npm`.

**Comment by gvilarino** [comment]
Can confirm @zxaos's workaround works properly

**Comment by hbetts** [comment]
I've recently found myself running into this exact same problem while attempting to run builds within GitLab CI.

It only occurs while using the `node:6` and `node:latest` Docker images. `node:4` works fine.

Therefore, I've needed to set those GitLab CI jobs to allow failure.

My GitLab CI YAML file looks like the following:

```yaml
stages:
    - test

.node_4: &node_4
  image: node:4

.node_6: &node_6
  image: node:6

.npm: &npm
  script:
    - npm update && npm test

.npm_4: &npm_4
  <<: [*npm]
  before_script:
    - npm prune
    - npm install --global npm@4

node_4_npm_4:
  <<: [*node_4, *npm_4]
  stage: test

node_6_node_6_npm_4:
  <<: [*node_6, *npm_4]
  stage: test
```

My `package.json` file looks like:

```json
{
  "license": "Apache-2.0",
  "name": "test-failures",
  "scripts": {
    "test": "echo 'no tests'"
  },
  "version": "1.0.0"
}
```

The output from my CI job is:

```bash
`-- npm@4.5.0 
  +-- abbrev@1.1.0 
  +-- ansi-regex@2.1.1 
  +-- aproba@1.1.1 
  +-- bluebird@3.5.0 
  +-- call-limit@1.1.0 
  +-- fs-vacuum@1.2.10 
  +-- fs-write-stream-atomic@1.0.10 
  +-- fstream@1.0.11 
  +-- glob@7.1.1 
  +-- graceful-fs@4.1.11 
  +-- hosted-git-info@2.4.1 
  +-- inflight@1.0.6 
  +-- init-package-json@1.9.5 
  +-- JSONStream@1.3.1 
  | +-- jsonparse@1.3.0 
  | `-- through@2.3.8 
  +-- lazy-property@1.0.0 
  +-- lockfile@1.0.3 
  +-- mississippi@1.3.0 
  | +-- concat-stream@1.6.0 
  | | `-- typedarray@0.0.6 
  | +-- duplexify@3.5.0 
  | | +-- end-of-stream@1.0.0 
  | | | `-- once@1.3.3 
  | | `-- stream-shift@1.0.0 
  | +-- end-of-stream@1.1.0 
  | | `-- once@1.3.3 
  | +-- flush-write-stream@1.0.2 
  | +-- from2@2.3.0 
  | +-- parallel-transform@1.1.0 
  | | `-- cyclist@0.2.2 
  | +-- pump@1.0.2 
  | +-- pumpify@1.3.5 
  | +-- stream-each@1.2.0 
  | | `-- stream-shift@1.0.0 
  | `-- through2@2.0.3 
  |   `-- xtend@4.0.1 
  +-- move-concurrently@1.0.1 
  | +-- copy-concurrently@1.0.3 
  | `-- run-queue@1.0.3 
  +-- node-gyp@3.6.0 
  | `-- nopt@3.0.6 
  +-- nopt@4.0.1 
  | `-- osenv@0.1.4 
  |   +-- os-homedir@1.0.2 
  |   `-- os-tmpdir@1.0.2 
  +-- normalize-package-data@2.3.6 
  +-- npm-package-arg@4.2.1 
  +-- npm-registry-client@8.1.0 
  | `-- concat-stream@1.6.0 
  +-- npmlog@4.0.2 
  | `-- gauge@2.7.2 
  |   +-- signal-exit@3.0.2 
  |   +-- string-width@1.0.2
  |   | +-- code-point-at@1.1.0 
  |   | `-- is-fullwidth-code-point@1.0.0
  |   |   `-- number-is-nan@1.0.1 
  |   `-- supports-color@0.2.0 
  +-- opener@1.4.3 
  +-- osenv@0.1.4 
  | +-- os-homedir@1.0.2 
  | `-- os-tmpdir@1.0.2 
  +-- read-package-json@2.0.5 
  +-- readable-stream@2.2.6 
  +-- request@2.81.0 
  | +-- aws4@1.6.0 
  | +-- caseless@0.12.0 
  | +-- form-data@2.1.2 
  | +-- har-validator@4.2.1 
  | | +-- ajv@4.11.4 
  | | | +-- co@4.6.0 
  | | | `-- json-stable-stringify@1.0.1 
  | | |   `-- jsonify@0.0.0 
  | | `-- har-schema@1.0.5 
  | +-- http-signature@1.1.1
  | | `-- sshpk@1.11.0 
  | |   +-- bcrypt-pbkdf@1.0.1 
  | |   +-- dashdash@1.14.1 
  | |   +-- jsbn@0.1.1 
  | |   `-- tweetnacl@0.14.5 
  | +-- mime-types@2.1.14 
  | | `-- mime-db@1.26.0 
  | +-- performance-now@0.2.0 
  | +-- qs@6.4.0 
  | +-- safe-buffer@5.0.1 
  | +-- tough-cookie@2.3.2 
  | | `-- punycode@1.4.1 
  | `-- tunnel-agent@0.6.0 
  +-- retry@0.10.1 
  +-- rimraf@2.6.1 
  +-- sorted-union-stream@2.1.3 
  | +-- from2@1.3.0 
  | | `-- readable-stream@1.1.14 
  | |   +-- core-util-is@1.0.2 
  | |   +-- isarray@0.0.1 
  | |   `-- string_decoder@0.10.31 
  | `-- stream-iterate@1.1.1 
  +-- update-notifier@2.1.0 
  | +-- boxen@1.0.0 
  | | +-- ansi-align@1.1.0 
  | | | `-- string-width@1.0.2 
  | | |   +-- code-point-at@1.1.0 
  | | |   `-- is-fullwidth-code-point@1.0.0 
  | | |     `-- number-is-nan@1.0.1 
  | | +-- camelcase@4.0.0 
  | | +-- cli-boxes@1.0.0 
  | | +-- string-width@2.0.0 
  | | | `-- is-fullwidth-code-point@2.0.0 
  | | +-- term-size@0.1.1 
  | | | `-- execa@0.4.0 
  | | |   +-- cross-spawn-async@2.2.5 
  | | |   | `-- lru-cache@4.0.2 
  | | |   |   +-- pseudomap@1.0.2 
  | | |   |   `-- yallist@2.0.0 
  | | |   +-- is-stream@1.1.0 
  | | |   +-- npm-run-path@1.0.0 
  | | |   +-- object-assign@4.1.1 
  | | |   +-- path-key@1.0.0 
  | | |   `-- strip-eof@1.0.0 
  | | `-- widest-line@1.0.0 
  | |   `-- string-width@1.0.2 
  | |     +-- code-point-at@1.1.0 
  | |     `-- is-fullwidth-code-point@1.0.0 
  | |       `-- number-is-nan@1.0.1 
  | +-- chalk@1.1.3 
  | | +-- ansi-styles@2.2.1 
  | | +-- escape-string-regexp@1.0.5 
  | | +-- has-ansi@2.0.0 
  | | `-- supports-color@2.0.0 
  | +-- configstore@3.0.0 
  | | +-- dot-prop@4.1.1 
  | | | `-- is-obj@1.0.1 
  | | `-- unique-string@1.0.0 
  | |   `-- crypto-random-string@1.0.0 
  | +-- is-npm@1.0.0 
  | +-- latest-version@3.0.0 
  | | `-- package-json@3.1.0 
  | |   +-- got@6.7.1 
  | |   | +-- create-error-class@3.0.2 
  | |   | | `-- capture-stack-trace@1.0.0 
  | |   | +-- duplexer3@0.1.4 
  | |   | +-- get-stream@3.0.0 
  | |   | +-- is-redirect@1.0.0 
  | |   | +-- is-retry-allowed@1.1.0 
  | |   | +-- is-stream@1.1.0 
  | |   | +-- lowercase-keys@1.0.0 
  | |   | +-- safe-buffer@5.0.1 
  | |   | +-- timed-out@4.0.1 
  | |   | +-- unzip-response@2.0.1 
  | |   | `-- url-parse-lax@1.0.0 
  | |   |   `-- prepend-http@1.0.4 
  | |   +-- registry-auth-token@3.1.0 
  | |   | `-- rc@1.1.7 
  | |   |   +-- deep-extend@0.4.1 
  | |   |   +-- minimist@1.2.0 
  | |   |   `-- strip-json-comments@2.0.1 
  | |   `-- registry-url@3.1.0 
  | |     `-- rc@1.1.7 
  | |       +-- deep-extend@0.4.1 
  | |       +-- minimist@1.2.0 
  | |       `-- strip-json-comments@2.0.1 
  | +-- lazy-req@2.0.0 
  | +-- semver-diff@2.1.0 
  | `-- xdg-basedir@3.0.0 
  +-- uuid@3.0.1 
  +-- validate-npm-package-name@3.0.0 
  | `-- builtins@1.0.3 
  +-- which@1.2.14 
  | `-- isexe@2.0.0 
  `-- write-file-atomic@1.3.1 

npm info ok 
$ npm update && npm test
module.js:471
    throw err;
    ^

Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/unsupported.js:2:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**Comment by legodude17** [comment]
Try updating `npm` from the website after deleting it.

**Comment by hbetts** [comment]
@legodude17 according to the npm documentation I can uninstall npm by running `npm uninstall npm -g`.

Then I can run `curl -L https://www.npmjs.com/install.sh | sh`.

However, how do I specify the npm version? I would like to test multiple versions of npm.

**Comment by hutson** [comment]
Duplicate of #16807
