### ISSUE TITLE
Error: Cannot find module 'bl'

### ISSUE THREAD

**Issue by shakyaanjib** [npm/npm#15610]
Error: Cannot find module 'bl'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\logicseed\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.js:9:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\logicseed\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "list"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.6
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'bl'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by KenanY** [comment]
Does this also occur after reinstalling `npm`?

**Comment by shakyaanjib** [comment]
Yes. It is not giving me any problems after i renamed npm and npm-cache
folder before reinstalling.

**Comment by Ilon4ik** [comment]
The problem continues to occur after reinstalling

**Comment by legodude17** [comment]
@Ilon4ik did you remove the `npm` and `npm-cache` folders?

**Comment by KenanY** [comment]
To me, this still looks like just a bad install of `npm` somehow. If anyone is still having this issue, even after following [Troubleshooting#if-your-npm-is-broken](https://github.com/npm/npm/wiki/Troubleshooting#if-your-npm-is-broken), then we should try and figure out what more we can add to that wiki entry to remedy these kinds of issues.
