### ISSUE TITLE
Angular 2

### ISSUE THREAD

**Issue by koko9** [npm/npm#15653]
What could be the problem here....
 Error occured when executing command: tsc -w
 Error: Unable to detect platform shell type. Please set SHELL_EXECUTE_FLAG env variable.
     at detectExecuteFlag (C:\Projects\myapp\node_modules\spawn-default-shell\src\get-shell.js:29:9)
     at getShell (C:\Projects\myapp\node_modules\spawn-default-shell\src\get-shell.js:37:18)
     at Object.spawn (C:\Projects\myapp\node_modules\spawn-default-shell\src\index.js:5:24)
     at C:\Projects\myapp\node_modules\concurrently\src\main.js:192:34
     at arrayMap (C:\Projects\myapp\node_modules\lodash\lodash.js:660:23)
     at Function.map (C:\Projects\myapp\node_modules\lodash\lodash.js:9571:14)
     at run (C:\Projects\myapp\node_modules\concurrently\src\main.js:181:22)
     at main (C:\Projects\myapp\node_modules\concurrently\src\main.js:61:5)
     at Object.<anonymous> (C:\Projects\myapp\node_modules\concurrently\src\main.js:421:1)
     at Module._compile (module.js:570:32)
     at Object.Module._extensions..js (module.js:579:10)
     at Module.load (module.js:487:32)
     at tryModuleLoad (module.js:446:12)
     at Function.Module._load (module.js:438:3)
     at Module.runMain (module.js:604:10)
     at run (bootstrap_node.js:394:7)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! angular-quickstart@1.0.0 start: `tsc && concurrently "tsc -w" "lite-server" `
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-quickstart@1.0.0 start script 'tsc && concurrently "tsc -w" "lite-server" '.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-quickstart package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc && concurrently "tsc -w" "lite-server"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-quickstart
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-quickstart
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Projects\myapp\npm-debug.log

**Comment by KenanY** [comment]
@koko9 Error is not coming from `npm`, it seems:

```
Error occured when executing command: tsc -w
Error: Unable to detect platform shell type. Please set SHELL_EXECUTE_FLAG env variable.
```
