### ISSUE TITLE
"exec:build_components" failed

### ISSUE THREAD

**Issue by pawel0520** [npm/npm#15686]
#### I'm opening this issue because:

  - [ ] npm is doing something I don't understand.

#### How can the CLI team reproduce the problem?

`Running "build" task
(node:1094) DeprecationWarning: process.EventEmitter is deprecated. Use require('events') instead.

Running "exec:build_components" (exec) task
>> npm
>> ERR! Darwin 16.1.0
>> npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "compile"
>> npm ERR! node v6.9.4
>> npm ERR! npm  v3.10.10
>> 
>> npm ERR! missing script: compile
>> npm ERR! 
`

**npm-debug.log**

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'compile' ]
2 info using npm@3.10.10
3 info using node@v6.9.4
4 verbose stack Error: missing script: compile
4 verbose stack     at run (/usr/local/lib/node_modules/npm/lib/run-script.js:151:19)
4 verbose stack     at /usr/local/lib/node_modules/npm/lib/run-script.js:61:5
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:356:5
4 verbose stack     at checkBinReferences_ (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:320:45)
4 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:354:3)
4 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:124:5)
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:311:12
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
4 verbose stack     at tryToString (fs.js:455:3)
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)
5 verbose cwd (path to /name-components)
6 error Darwin 16.1.0
7 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "compile"
8 error node v6.9.4
9 error npm  v3.10.10
10 error missing script: compile
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
@pawel0520 Looks like you don't have a `"compile"` script defined in your `package.json`. See <https://docs.npmjs.com/misc/scripts> for info on writing scripts.
