### ISSUE TITLE
npm install --save angular-route@X.Y.Z breaks

### ISSUE THREAD

**Issue by VGamezz19** [npm/npm#15701]
When I try to install this command --> **_npm install --save angular-route@X.Y.Z_** npm breaks.

> this is a npm-debuglog

```

31 verbose stack Error: No compatible version found: angular-route@X.Y.Z
31 verbose stack Valid install targets:
31 verbose stack 1.6.2, 1.6.1, 1.6.0, 1.6.0-rc.2, 1.6.0-rc.1, 1.6.0-rc.0, 1.5.11, 1.5.10, 1.5.9, 1.5.8, 1.5.7, 1.5.6, 1.5.5, 1.5.3, 1.5.2, 1.5.1, 1.5.0, 1.5.0-rc.2, 1.5.0-rc.1, 1.5.0-rc.0, 1.5.0-beta.2, 1.5.0-beta.0, 1.4.14, 1.4.13, 1.4.12, 1.4.11, 1.4.10, 1.4.9, 1.4.8, 1.4.7, 1.4.6, 1.4.5, 1.4.4, 1.4.3, 1.4.2, 1.4.1, 1.4.0, 1.4.0-rc.2, 1.4.0-rc.1, 1.4.0-rc.0, 1.4.0-beta.6, 1.4.0-beta.5, 1.4.0-beta.4, 1.4.0-beta.3, 1.4.0-beta.2, 1.4.0-beta.1, 1.4.0-beta.0, 1.3.20, 1.3.19, 1.3.18, 1.3.17, 1.3.16, 1.3.15, 1.3.14, 1.3.13, 1.3.12, 1.3.11, 1.3.10, 1.3.9, 1.3.8, 1.3.7, 1.3.6, 1.3.5, 1.3.4, 1.3.4-build.3588, 1.3.3, 1.3.2, 1.3.1, 1.3.0, 1.3.0-rc.5, 1.2.32, 1.2.31, 1.2.30, 1.2.29, 1.2.28, 1.2.27, 1.2.17-build.163.1
31 verbose stack
31 verbose stack     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:156:16)
31 verbose stack     at /usr/share/npm/node_modules/iferr/index.js:13:50
31 verbose stack     at /usr/share/npm/lib/utils/pulse-till-done.js:19:8
31 verbose stack     at saved (/usr/share/npm/lib/cache/caching-client.js:168:7)
31 verbose stack     at /usr/share/npm/node_modules/graceful-fs/polyfills.js:210:7
31 verbose stack     at FSReqWrap.oncomplete (fs.js:82:15)
32 verbose cwd /media/victor/VictorGamez/Mega/_DAW_2/GefCore
33 error Linux 4.4.0-53-generic
34 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "--save" "angular-route@X.Y.Z"
35 error node v4.2.6
36 error npm  v3.5.2
37 error No compatible version found: angular-route@X.Y.Z
37 error Valid install targets:
37 error 1.6.2, 1.6.1, 1.6.0, 1.6.0-rc.2, 1.6.0-rc.1, 1.6.0-rc.0, 1.5.11, 1.5.10, 1.5.9, 1.5.8, 1.5.7, 1.5.6, 1.5.5, 1.5.3, 1.5.2, 1.5.1, 1.5.0, 1.5.0-rc.2, 1.5.0-rc.1, 1.5.0-rc.0, 1.5.0-beta.2, 1.5.0-beta.0, 1.4.14, 1.4.13, 1.4.12, 1.4.11, 1.4.10, 1.4.9, 1.4.8, 1.4.7, 1.4.6, 1.4.5, 1.4.4, 1.4.3, 1.4.2, 1.4.1, 1.4.0, 1.4.0-rc.2, 1.4.0-rc.1, 1.4.0-rc.0, 1.4.0-beta.6, 1.4.0-beta.5, 1.4.0-beta.4, 1.4.0-beta.3, 1.4.0-beta.2, 1.4.0-beta.1, 1.4.0-beta.0, 1.3.20, 1.3.19, 1.3.18, 1.3.17, 1.3.16, 1.3.15, 1.3.14, 1.3.13, 1.3.12, 1.3.11, 1.3.10, 1.3.9, 1.3.8, 1.3.7, 1.3.6, 1.3.5, 1.3.4, 1.3.4-build.3588, 1.3.3, 1.3.2, 1.3.1, 1.3.0, 1.3.0-rc.5, 1.2.32, 1.2.31, 1.2.30, 1.2.29, 1.2.28, 1.2.27, 1.2.17-build.163.1
38 error If you need help, you may report this error at:
38 error     <https://github.com/npm/npm/issues>
39 verbose exit [ 1, true ]
```
What can i do to solve it.

**Comment by KenanY** [comment]
@VGamezz19 Replace `X.Y.Z` with the version you want to install.

**Comment by VGamezz19** [comment]
XDDDDDDDDDDDDDDDD

**Comment by VGamezz19** [comment]
tnx!! jajajaj
