### ISSUE TITLE
Error: Cannot find module './lib/cookies'

### ISSUE THREAD

**Issue by chenjie112** [npm/npm#15711]
ChenJiedeMac-mini:~ chenjie$ npm install -g yarn react-native-cli

Error: Cannot find module './lib/cookies'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/index.js:18:29)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/Cellar/node/7.5.0/bin/node" "/usr/local/bin/npm" "config" "set" "registry" "https://registry.npm.taobao.org" "--global"
npm ERR! node v7.5.0
npm ERR! npm  v3.3.12
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module './lib/cookies'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by KenanY** [comment]
@chenjie112 Could you try reinstalling `npm`? Seems like a dependency is missing at least one file.
