### ISSUE TITLE
npm install is not working in Windows 10

### ISSUE THREAD

**Issue by hemakh** [npm/npm#15719]
I have installed nodejs latest on Windows 10 (64-bit) and the PATH is already setup. Now when i am trying to install any npm modules globally using `npm install -g <packagename>`then I am getting the following error:

```
npm install -g <packagename>
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "<packagename>"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10

npm ERR! 1961 == 0
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

The npm-debug.log shows:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'yo' ]
2 info using npm@3.10.10
3 info using node@v6.9.5
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData yo
8 silly fetchNamedPackageData yo
9 silly mapToRegistry name yo
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'yo',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'yo',
12 silly mapToRegistry   name: 'yo',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/yo
14 verbose request uri https://registry.npmjs.org/yo
15 verbose request no auth needed
16 info attempt registry request try #1 at 3:40:19 PM
17 verbose request id 09fae89b96705683
18 http request GET https://registry.npmjs.org/yo
19 verbose stack AssertionError: 1961 == 0
19 verbose stack     at ClientRequest.onConnect (C:\Program Files\nodejs\node_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:159:14)
19 verbose stack     at ClientRequest.g (events.js:291:16)
19 verbose stack     at emitThree (events.js:116:13)
19 verbose stack     at ClientRequest.emit (events.js:194:7)
19 verbose stack     at Socket.socketOnData (_http_client.js:395:11)
19 verbose stack     at emitOne (events.js:96:13)
19 verbose stack     at Socket.emit (events.js:188:7)
19 verbose stack     at readableAddChunk (_stream_readable.js:176:18)
19 verbose stack     at Socket.Readable.push (_stream_readable.js:134:10)
19 verbose stack     at TCP.onread (net.js:548:20)
20 verbose cwd C:\wamp64\www\kvm-emart
21 error Windows_NT 10.0.14393
22 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "yo"
23 error node v6.9.5
24 error npm  v3.10.10
25 error 1961 == 0
26 error If you need help, you may report this error at:
26 error     <https://github.com/npm/npm/issues>
27 verbose exit [ 1, true ]

```

I do not understand the error in windows 10 while installing npm packages. Please let me know if this can be fixed.

**Comment by HemaKT** [comment]
I have clered the npm cache and after a restart tried again with `npm install` command.

```
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ECONNRESET

npm ERR! network tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:80
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     C:\wamp64\www\kvm-emart\emart1\npm-debug.log
```

**Comment by jpaulin** [comment]
I think you are installing 'Yeoman', which used to be called 'yo' - both the shell tool and the npm package.

It's still the same software, and the 'yo' is used as CLI, but the package is now named 'yeoman'.
Try this instead: 

`npm install -g yeoman`

**Comment by HemaKT** [comment]
For yoeman, it is `npm install -g yo` taken from this [http://yeoman.io/learning/](url)

I tried with yoeman also i am getting the same error

**Comment by AlexR1** [comment]
Hello
I had similar issue and I found that it was related to firewall / proxy (the installation process tried and didn't succeed to access some external content).

hope this will help someone..

**Comment by amiraba** [comment]
Had the same issue...
Run the git bash or the command line console as an administrator when launching the npm install command
Worked for me ! ;)
