### ISSUE TITLE
Installing Discord.js error on windows 10

### ISSUE THREAD

**Issue by proff001** [npm/npm#15721]
# This i what i type to install:
C:\Users\thomm\Desktop\Discord Bot Node.js>npm install discord.js opusscript --save

# This is the error:
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "discord.js" "opusscript" "--save"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code UNABLE_TO_VERIFY_LEAF_SIGNATURE

npm ERR! unable to verify the first certificate
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\thomm\Desktop\Discord Bot Node.js\npm-debug.log

# Log File:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'discord.js',
1 verbose cli   'opusscript',
1 verbose cli   '--save' ]
2 info using npm@3.10.10
3 info using node@v6.9.5
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData discord.js
8 silly fetchPackageMetaData opusscript
9 silly fetchNamedPackageData discord.js
10 silly mapToRegistry name discord.js
11 silly mapToRegistry using default registry
12 silly mapToRegistry registry https://registry.npmjs.org/
13 silly mapToRegistry data Result {
13 silly mapToRegistry   raw: 'discord.js',
13 silly mapToRegistry   scope: null,
13 silly mapToRegistry   escapedName: 'discord.js',
13 silly mapToRegistry   name: 'discord.js',
13 silly mapToRegistry   rawSpec: '',
13 silly mapToRegistry   spec: 'latest',
13 silly mapToRegistry   type: 'tag' }
14 silly mapToRegistry uri https://registry.npmjs.org/discord.js
15 silly fetchNamedPackageData opusscript
16 silly mapToRegistry name opusscript
17 silly mapToRegistry using default registry
18 silly mapToRegistry registry https://registry.npmjs.org/
19 silly mapToRegistry data Result {
19 silly mapToRegistry   raw: 'opusscript',
19 silly mapToRegistry   scope: null,
19 silly mapToRegistry   escapedName: 'opusscript',
19 silly mapToRegistry   name: 'opusscript',
19 silly mapToRegistry   rawSpec: '',
19 silly mapToRegistry   spec: 'latest',
19 silly mapToRegistry   type: 'tag' }
20 silly mapToRegistry uri https://registry.npmjs.org/opusscript
21 verbose request uri https://registry.npmjs.org/discord.js
22 verbose request no auth needed
23 info attempt registry request try #1 at 7:50:36 PM
24 verbose request id 3b89f45ec0e184ed
25 http request GET https://registry.npmjs.org/discord.js
26 verbose request uri https://registry.npmjs.org/opusscript
27 verbose request no auth needed
28 info attempt registry request try #1 at 7:50:36 PM
29 http request GET https://registry.npmjs.org/opusscript
30 info retry will retry, error on last attempt: Error: unable to verify the first certificate
31 info retry will retry, error on last attempt: Error: unable to verify the first certificate
32 info attempt registry request try #2 at 7:50:46 PM
33 http request GET https://registry.npmjs.org/opusscript
34 info attempt registry request try #2 at 7:50:46 PM
35 http request GET https://registry.npmjs.org/discord.js
36 info retry will retry, error on last attempt: Error: unable to verify the first certificate
37 info retry will retry, error on last attempt: Error: unable to verify the first certificate
38 info attempt registry request try #3 at 7:51:47 PM
39 http request GET https://registry.npmjs.org/opusscript
40 info attempt registry request try #3 at 7:51:47 PM
41 http request GET https://registry.npmjs.org/discord.js
42 silly fetchPackageMetaData Error: unable to verify the first certificate
42 silly fetchPackageMetaData     at Error (native)
42 silly fetchPackageMetaData     at TLSSocket.<anonymous> (_tls_wrap.js:1079:38)
42 silly fetchPackageMetaData     at emitNone (events.js:86:13)
42 silly fetchPackageMetaData     at TLSSocket.emit (events.js:185:7)
42 silly fetchPackageMetaData     at TLSSocket._finishInit (_tls_wrap.js:603:8)
42 silly fetchPackageMetaData     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:433:38)
42 silly fetchPackageMetaData  error for opusscript { Error: unable to verify the first certificate
42 silly fetchPackageMetaData     at Error (native)
42 silly fetchPackageMetaData     at TLSSocket.<anonymous> (_tls_wrap.js:1079:38)
42 silly fetchPackageMetaData     at emitNone (events.js:86:13)
42 silly fetchPackageMetaData     at TLSSocket.emit (events.js:185:7)
42 silly fetchPackageMetaData     at TLSSocket._finishInit (_tls_wrap.js:603:8)
42 silly fetchPackageMetaData     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:433:38) code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE' }
43 silly fetchPackageMetaData Error: unable to verify the first certificate
43 silly fetchPackageMetaData     at Error (native)
43 silly fetchPackageMetaData     at TLSSocket.<anonymous> (_tls_wrap.js:1079:38)
43 silly fetchPackageMetaData     at emitNone (events.js:86:13)
43 silly fetchPackageMetaData     at TLSSocket.emit (events.js:185:7)
43 silly fetchPackageMetaData     at TLSSocket._finishInit (_tls_wrap.js:603:8)
43 silly fetchPackageMetaData     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:433:38)
43 silly fetchPackageMetaData  error for discord.js { Error: unable to verify the first certificate
43 silly fetchPackageMetaData     at Error (native)
43 silly fetchPackageMetaData     at TLSSocket.<anonymous> (_tls_wrap.js:1079:38)
43 silly fetchPackageMetaData     at emitNone (events.js:86:13)
43 silly fetchPackageMetaData     at TLSSocket.emit (events.js:185:7)
43 silly fetchPackageMetaData     at TLSSocket._finishInit (_tls_wrap.js:603:8)
43 silly fetchPackageMetaData     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:433:38) code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE' }
44 silly rollbackFailedOptional Starting
45 silly rollbackFailedOptional Finishing
46 silly runTopLevelLifecycles Finishing
47 silly install printInstalled
48 verbose stack Error: unable to verify the first certificate
48 verbose stack     at Error (native)
48 verbose stack     at TLSSocket.<anonymous> (_tls_wrap.js:1079:38)
48 verbose stack     at emitNone (events.js:86:13)
48 verbose stack     at TLSSocket.emit (events.js:185:7)
48 verbose stack     at TLSSocket._finishInit (_tls_wrap.js:603:8)
48 verbose stack     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:433:38)
49 verbose cwd C:\Users\thomm\Desktop\Discord Bot Node.js
50 error Windows_NT 10.0.14393
51 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "discord.js" "opusscript" "--save"
52 error node v6.9.5
53 error npm  v3.10.10
54 error code UNABLE_TO_VERIFY_LEAF_SIGNATURE
55 error unable to verify the first certificate
56 error If you need help, you may report this error at:
56 error     <https://github.com/npm/npm/issues>
57 verbose exit [ 1, true ]

**Comment by proff001** [comment]
Please Help me
