### ISSUE TITLE
NPM error: Cannot find module 'number-is-nan'

### ISSUE THREAD

**Issue by goelmayank** [npm/npm#15738]
I'm opening this issue because:
 npm is crashing.

What's going wrong?
For some reason I get a cannot find module 'number-is-nan' error. I already uninstalled nodejs, installed it again and the error remains. The thing is that NPM is not usable, I cannot even checkout its version.
$ npm -v
module.js:471
    throw err;
    ^

Error: Cannot find module 'number-is-nan'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npmlog/node_modules/gauge/node_modules/string-width/node_modules/code-point-at/index.js:2:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

npm -v prints: The error above
node -v prints: v6.9.4
npm config get registry prints: The error above
Windows, OS X/macOS, or Linux?: Ubuntu
Network issues:
oGeographic location where npm was run: Rajasthan, India

**Comment by fr4ngus** [comment]
I had the same issue with my Mac.
I just uninstall node and npm with Brew and reinstall using the official node website:
https://nodejs.org/en/download/
I think the problem comes from the fact that you installed node with brew package manager and npm to. So when you try to update npm independently, it just broke this.

`brew uninstall node` then install from node website.

**Comment by pavitrobishvas** [comment]
model.js:340
throw err;

**Comment by pavitrobishvas** [comment]
solve this please

**Comment by legodude17** [comment]
@pavitrobishvas try uninstalling and then reinstalling.
