### ISSUE TITLE
npm-cache debug.log

### ISSUE THREAD

**Issue by provawebdev** [npm/npm#15733]
$ npm run watch

> @ watch F:\xampp_laravel\htdocs\afroza\laravel\chatdemo
> cross-env NODE_ENV=development webpack --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

'cross-env' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "F:\\Nodejs\\node.exe" "C:\\Users\\prova\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "watch"
npm ERR! node v6.9.5
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ watch: `cross-env NODE_ENV=development webpack --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ watch script 'cross-env NODE_ENV=development webpack --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=development webpack --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\prova\AppData\Roaming\npm-cache\_logs\2017-02-10T19_51_57_004Z-debug.log

**Comment by KenanY** [comment]
@provawebdev Have you tried installing `cross-env` locally?

**Comment by Vixed** [comment]
KenanY, how locally?

**Comment by KenanY** [comment]
@Vixed `npm install cross-env`

**Comment by provawebdev** [comment]
yes, locally I tried npm install cross-env . but same problem.

**Comment by provawebdev** [comment]
$ npm install cross-env
F:\xampp_laravel\htdocs\afroza\laravel\chatdemo
`-- laravel-mix@0.5.16
  `-- cross-env@3.1.4

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

**Comment by KenanY** [comment]
So,

```
$ npm install -D cross-env
$ npm run watch
```

throws an error? If so, can I see the output of both of these commands?

**Comment by provawebdev** [comment]
yes, of course.

prova@Arif MINGW64 /f/xampp_laravel/htdocs/afroza/laravel/chatdemo (master)
$ npm install -D cross-env
F:\xampp_laravel\htdocs\afroza\laravel\chatdemo
`-- cross-env@3.1.4

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

prova@Arif MINGW64 /f/xampp_laravel/htdocs/afroza/laravel/chatdemo (master)
$ npm run watch

> @ watch F:\xampp_laravel\htdocs\afroza\laravel\chatdemo
> cross-env NODE_ENV=development webpack --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

'webpack' is not recognized as an internal or external command,
operable program or batch file.
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn webpack ENOENT
    at notFoundError (F:\xampp_laravel\htdocs\afroza\laravel\chatdemo\node_modules\cross-spawn\lib\enoent.js:11:11)
    at verifyENOENT (F:\xampp_laravel\htdocs\afroza\laravel\chatdemo\node_modules\cross-spawn\lib\enoent.js:46:16)
    at ChildProcess.cp.emit (F:\xampp_laravel\htdocs\afroza\laravel\chatdemo\node_modules\cross-spawn\lib\enoent.js:33:19)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "F:\\Nodejs\\node.exe" "C:\\Users\\prova\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "watch"
npm ERR! node v6.9.5
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ watch: `cross-env NODE_ENV=development webpack --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ watch script 'cross-env NODE_ENV=development webpack --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=development webpack --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\prova\AppData\Roaming\npm-cache\_logs\2017-02-13T03_14_43_572Z-debug.log

**Comment by KenanY** [comment]
@provawebdev Your error message is different now. You have to install `webpack` as well:

```
$ npm install -D webpack
```

**Comment by provawebdev** [comment]
prova@Arif MINGW64 /f/xampp_laravel/htdocs/afroza/laravel/chatdemo (master)
$ npm install -D webpack
F:\xampp_laravel\htdocs\afroza\laravel\chatdemo
`-- webpack@2.2.1

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

**Comment by KenanY** [comment]
@provawebdev And now `npm run watch`?

**Comment by provawebdev** [comment]
ERROR  Failed to compile with 3 errors

 error  in ./resources/assets/sass/app.scss

Module build failed: Error: ENOENT: no such file or directory, scandir 'F:\xampp_laravel\htdocs\afroza\laravel\chatdemo\node_modules\node-sass\vendor'
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at Object.getInstalledBinaries (F:\xampp_laravel\htdocs\afroza\laravel\chatdemo\node_modules\node-sass\lib\extensions.js:122:13)
    at foundBinariesList (F:\xampp_laravel\htdocs\afroza\laravel\chatdemo\node_modules\node-sass\lib\errors.js:20:15)
    at foundBinaries (F:\xampp_laravel\htdocs\afroza\laravel\chatdemo\node_modules\node-sass\lib\errors.js:15:5)
    at Object.module.exports.missingBinary (F:\xampp_laravel\htdocs\afroza\laravel\chatdemo\node_modules\node-sass\lib\errors.js:45:5)
    at module.exports (F:\xampp_laravel\htdocs\afroza\laravel\chatdemo\node_modules\node-sass\lib\binding.js:15:30)
    at Object.<anonymous> (F:\xampp_laravel\htdocs\afroza\laravel\chatdemo\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (F:\xampp_laravel\htdocs\afroza\laravel\chatdemo\node_modules\sass-loader\index.js:4:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at loadLoader (F:\xampp_laravel\htdocs\afroza\laravel\chatdemo\node_modules\loader-runner\lib\loadLoader.js:13:17)
    at iteratePitchingLoaders (F:\xampp_laravel\htdocs\afroza\laravel\chatdemo\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at iteratePitchingLoaders (F:\xampp_laravel\htdocs\afroza\laravel\chatdemo\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
    at F:\xampp_laravel\htdocs\afroza\laravel\chatdemo\node_modules\loader-runner\lib\LoaderRunner.js:173:18
    at loadLoader (F:\xampp_laravel\htdocs\afroza\laravel\chatdemo\node_modules\loader-runner\lib\loadLoader.js:36:3)
    at iteratePitchingLoaders (F:\xampp_laravel\htdocs\afroza\laravel\chatdemo\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at iteratePitchingLoaders (F:\xampp_laravel\htdocs\afroza\laravel\chatdemo\node_modules\loader-runner\lib\LoaderRunner.js:165:10)

 @ ./resources/assets/sass/app.scss 4:14-248
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss

 error  in ./resources/assets/sass/app.scss

Module build failed: ModuleBuildError: Module build failed: Error: ENOENT: no such file or directory, scandir 'F:\xampp_laravel\htdocs\afroza\laravel\chatdemo\node_modules\node-sass\vendor'
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at Object.getInstalledBinaries (F:\xampp_laravel\htdocs\afroza\laravel\chatdemo\node_modules\node-sass\lib\extensions.js:122:13)
    at foundBinariesList (F:\xampp_laravel\htdocs\afroza\laravel\chatdemo\node_modules\node-sass\lib\errors.js:20:15)
    at foundBinaries (F:\xampp_laravel\htdocs\afroza\laravel\chatdemo\node_modules\node-sass\lib\errors.js:15:5)
    at Object.module.exports.missingBinary (F:\xampp_laravel\htdocs\afroza\laravel\chatdemo\node_modules\node-sass\lib\errors.js:45:5)
    at module.exports (F:\xampp_laravel\htdocs\afroza\laravel\chatdemo\node_modules\node-sass\lib\binding.js:15:30)
    at Object.<anonymous> (F:\xampp_laravel\htdocs\afroza\laravel\chatdemo\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (F:\xampp_laravel\htdocs\afroza\laravel\chatdemo\node_modules\sass-loader\index.js:4:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at loadLoader (F:\xampp_laravel\htdocs\afroza\laravel\chatdemo\node_modules\loader-runner\lib\loadLoader.js:13:17)
    at iteratePitchingLoaders (F:\xampp_laravel\htdocs\afroza\laravel\chatdemo\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at iteratePitchingLoaders (F:\xampp_laravel\htdocs\afroza\laravel\chatdemo\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
    at F:\xampp_laravel\htdocs\afroza\laravel\chatdemo\node_modules\loader-runner\lib\LoaderRunner.js:173:18
    at loadLoader (F:\xampp_laravel\htdocs\afroza\laravel\chatdemo\node_modules\loader-runner\lib\loadLoader.js:36:3)
    at iteratePitchingLoaders (F:\xampp_laravel\htdocs\afroza\laravel\chatdemo\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at iteratePitchingLoaders (F:\xampp_laravel\htdocs\afroza\laravel\chatdemo\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
    at F:\xampp_laravel\htdocs\afroza\laravel\chatdemo\node_modules\webpack\lib\NormalModule.js:141:35
    at F:\xampp_laravel\htdocs\afroza\laravel\chatdemo\node_modules\loader-runner\lib\LoaderRunner.js:364:11
    at F:\xampp_laravel\htdocs\afroza\laravel\chatdemo\node_modules\loader-runner\lib\LoaderRunner.js:170:18
    at loadLoader (F:\xampp_laravel\htdocs\afroza\laravel\chatdemo\node_modules\loader-runner\lib\loadLoader.js:27:11)
    at iteratePitchingLoaders (F:\xampp_laravel\htdocs\afroza\laravel\chatdemo\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at iteratePitchingLoaders (F:\xampp_laravel\htdocs\afroza\laravel\chatdemo\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
    at F:\xampp_laravel\htdocs\afroza\laravel\chatdemo\node_modules\loader-runner\lib\LoaderRunner.js:173:18
    at loadLoader (F:\xampp_laravel\htdocs\afroza\laravel\chatdemo\node_modules\loader-runner\lib\loadLoader.js:36:3)
    at iteratePitchingLoaders (F:\xampp_laravel\htdocs\afroza\laravel\chatdemo\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at iteratePitchingLoaders (F:\xampp_laravel\htdocs\afroza\laravel\chatdemo\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
    at F:\xampp_laravel\htdocs\afroza\laravel\chatdemo\node_modules\loader-runner\lib\LoaderRunner.js:173:18
    at loadLoader (F:\xampp_laravel\htdocs\afroza\laravel\chatdemo\node_modules\loader-runner\lib\loadLoader.js:36:3)
    at iteratePitchingLoaders (F:\xampp_laravel\htdocs\afroza\laravel\chatdemo\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at iteratePitchingLoaders (F:\xampp_laravel\htdocs\afroza\laravel\chatdemo\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
    at F:\xampp_laravel\htdocs\afroza\laravel\chatdemo\node_modules\loader-runner\lib\LoaderRunner.js:173:18
    at loadLoader (F:\xampp_laravel\htdocs\afroza\laravel\chatdemo\node_modules\loader-runner\lib\loadLoader.js:36:3)
    at iteratePitchingLoaders (F:\xampp_laravel\htdocs\afroza\laravel\chatdemo\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at runLoaders (F:\xampp_laravel\htdocs\afroza\laravel\chatdemo\node_modules\loader-runner\lib\LoaderRunner.js:362:2)
    at NormalModule.doBuild (F:\xampp_laravel\htdocs\afroza\laravel\chatdemo\node_modules\webpack\lib\NormalModule.js:129:2)
    at NormalModule.build (F:\xampp_laravel\htdocs\afroza\laravel\chatdemo\node_modules\webpack\lib\NormalModule.js:180:15)
    at Compilation.buildModule (F:\xampp_laravel\htdocs\afroza\laravel\chatdemo\node_modules\webpack\lib\Compilation.js:142:10)
    at moduleFactory.create (F:\xampp_laravel\htdocs\afroza\laravel\chatdemo\node_modules\webpack\lib\Compilation.js:424:9)
    at F:\xampp_laravel\htdocs\afroza\laravel\chatdemo\node_modules\webpack\lib\NormalModuleFactory.js:242:4
    at F:\xampp_laravel\htdocs\afroza\laravel\chatdemo\node_modules\webpack\lib\NormalModuleFactory.js:93:13
    at F:\xampp_laravel\htdocs\afroza\laravel\chatdemo\node_modules\tapable\lib\Tapable.js:204:11
    at NormalModuleFactory.params.normalModuleFactory.plugin (F:\xampp_laravel\htdocs\afroza\laravel\chatdemo\node_modules\webpack\lib\CompatibilityPlugin.js:52:5)
    at NormalModuleFactory.applyPluginsAsyncWaterfall (F:\xampp_laravel\htdocs\afroza\laravel\chatdemo\node_modules\tapable\lib\Tapable.js:208:13)
    at onDoneResolving (F:\xampp_laravel\htdocs\afroza\laravel\chatdemo\node_modules\webpack\lib\NormalModuleFactory.js:68:11)
    at onDoneResolving (F:\xampp_laravel\htdocs\afroza\laravel\chatdemo\node_modules\webpack\lib\NormalModuleFactory.js:189:6)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)

 error

F:\xampp_laravel\htdocs\afroza\laravel\chatdemo\node_modules\extract-text-webpack-plugin\loader.js??ref--4-0!F:\xampp_laravel\htdocs\afroza\laravel\chatdemo\node_modules\style-loader\index.js!F:\xampp_laravel\htdocs\afroza\laravel\chatdemo\node_modules\css-loader\index.js!F:\xampp_laravel\htdocs\afroza\laravel\chatdemo\node_modules\postcss-loader\index.js!F:\xampp_laravel\htdocs\afroza\laravel\chatdemo\node_modules\resolve-url-loader\index.js!F:\xampp_laravel\htdocs\afroza\laravel\chatdemo\node_modules\sass-loader\index.js?sourceMap&precision=8!F:\xampp_laravel\htdocs\afroza\laravel\chatdemo\resources\assets\sass\app.scss doesn't export content
                                                                               Asset      Size  Chunks                    Chunk Names
       /js/app.js   1.16 MB       0  [emitted]  [big]  /js/app
mix-manifest.json  32 bytes          [emitted]

**Comment by KenanY** [comment]
@provawebdev Looks like you might have to run `npm rebuild node-sass`? Or delete `node_modules/` and run `npm install`?

**Comment by provawebdev** [comment]
Thanks  now it done.

**Comment by DastanSE** [comment]
@KenanY  could you help me #15750
