### ISSUE TITLE
NPM - Attempt to unlock grunt-cli, which hasn't been locked

### ISSUE THREAD

**Issue by leonavi999123** [npm/npm#15732]
Hi,

I am getting the below error , when I ran my build from Team City, 

[Step 1/1] npm ERR! Error: Attempt to unlock grunt-cli, which hasn't been locked
[23:26:05][Step 1/1] npm ERR!     at unlock (C:\Program Files\nodejs\node_modules\npm\lib\utils\locker.js:44:11)
[23:26:05][Step 1/1] npm ERR!     at cb (C:\Program Files\nodejs\node_modules\npm\lib\cache\add-local.js:30:5)
[23:26:05][Step 1/1] npm ERR!     at C:\Program Files\nodejs\node_modules\npm\lib\cache\add-local.js:47:20
[23:26:05][Step 1/1] npm ERR!     at C:\Program Files\nodejs\node_modules\npm\lib\utils\locker.js:30:7
[23:26:05][Step 1/1] npm ERR!     at C:\Program Files\nodejs\node_modules\npm\node_modules\lockfile\lockfile.js:167:38
[23:26:05][Step 1/1] npm ERR!     at Object.oncomplete (fs.js:107:15)
[23:26:05][Step 1/1] npm ERR! If you need help, you may report this *entire* log,
[23:26:05][Step 1/1] npm ERR! including the npm and node versions, at:
[23:26:05][Step 1/1] npm ERR!     <http://github.com/npm/npm/issues>
[23:26:05][Step 1/1] 
[23:26:05][Step 1/1] npm ERR! System Windows_NT 6.2.9200
[23:26:05][Step 1/1] npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "grunt-cli"
[23:26:05][Step 1/1] npm ERR! cwd C:\Deployment\Workspace\PROD\Pei Wei UI Web and Apps
[23:26:05][Step 1/1] npm ERR! node -v v0.10.30
[23:26:05][Step 1/1] npm ERR! npm -v 1.4.21
[23:26:05][Step 1/1] npmThe system cannot find the file specified.
[23:26:05][Step 1/1] You do not have sufficient privilege to perform this operation.

**Comment by KenanY** [comment]
@leonavi999123 Could you please update to a newer version of Node.js and `npm`?

**Comment by KenanY** [comment]
Closing as abandoned.
