### ISSUE TITLE
can not install harp on my windows 10 computer

### ISSUE THREAD

**Issue by woodsr** [npm/npm#15749]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

$ npm install -g harp
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install th                                                                                                                e latest version of pug instead of jade
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
C:\Users\Lee\AppData\Roaming\npm\harp -> C:\Users\Lee\AppData\Roaming\npm\node_modules\harp\bi                                                                                                  n\harp

> node-sass@3.7.0 install C:\Users\Lee\AppData\Roaming\npm\node_modules\harp\node_modules\node                                                                                                  -sass
> node scripts/install.js

Cannot download "https://github.com/sass/node-sass/releases/download/v3.7.0/win32-x64-51_bindi                                                                                                  ng.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@3.7.0 postinstall C:\Users\Lee\AppData\Roaming\npm\node_modules\harp\node_modules\                                                                                                  node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe C:\Users\Lee\AppData\Roaming\npm\node_modules\harp\                                                                                                  node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --lib                                                                                                  sass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\Lee\\AppData\\Roaming\\npm\\node_modules\\harp\\node_modules\\node-                                                                                                  gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.5.0
gyp info using node@7.5.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\Lee\AppData\Roaming\npm\node_modules                                                                                                  \harp\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Lee\AppData\Roaming\npm\node_modules\harp\node_modu                                                                                                  les\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Lee\AppData\Roaming\npm\node_modules\harp\node_modu                                                                                                  les\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Lee\AppData\Roaming\npm\node_modules\harp\node_modules                                                                                                  \which\which.js:89:16
gyp verb `which` failed     at C:\Users\Lee\AppData\Roaming\npm\node_modules\harp\node_modules                                                                                                  \isexe\index.js:44:5
gyp verb `which` failed     at C:\Users\Lee\AppData\Roaming\npm\node_modules\harp\node_modules                                                                                                  \isexe\windows.js:29:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:112:15)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\Lee\AppData\Roaming\npm\node_modules                                                                                                  \harp\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Lee\AppData\Roaming\npm\node_modules\harp\node_modu                                                                                                  les\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Lee\AppData\Roaming\npm\node_modules\harp\node_modu                                                                                                  les\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Lee\AppData\Roaming\npm\node_modules\harp\node_modules                                                                                                  \which\which.js:89:16
gyp verb `which` failed     at C:\Users\Lee\AppData\Roaming\npm\node_modules\harp\node_modules                                                                                                  \isexe\index.js:44:5
gyp verb `which` failed     at C:\Users\Lee\AppData\Roaming\npm\node_modules\harp\node_modules                                                                                                  \isexe\windows.js:29:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:112:15) code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\Users\Lee\AppData\Roaming\npm\node_modules                                                                                                  \harp\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Lee\AppData\Roaming\npm\node_modules\harp\node_modu                                                                                                  les\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Lee\AppData\Roaming\npm\node_modules\harp\node_modu                                                                                                  les\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Lee\AppData\Roaming\npm\node_modules\harp\node_modules                                                                                                  \which\which.js:89:16
gyp verb `which` failed     at C:\Users\Lee\AppData\Roaming\npm\node_modules\harp\node_modules                                                                                                  \isexe\index.js:44:5
gyp verb `which` failed     at C:\Users\Lee\AppData\Roaming\npm\node_modules\harp\node_modules                                                                                                  \isexe\windows.js:29:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:112:15)
gyp verb `which` failed  python { Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\Users\Lee\AppData\Roaming\npm\node_modules                                                                                                  \harp\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Lee\AppData\Roaming\npm\node_modules\harp\node_modu                                                                                                  les\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Lee\AppData\Roaming\npm\node_modules\harp\node_modu                                                                                                  les\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Lee\AppData\Roaming\npm\node_modules\harp\node_modules                                                                                                  \which\which.js:89:16
gyp verb `which` failed     at C:\Users\Lee\AppData\Roaming\npm\node_modules\harp\node_modules                                                                                                  \isexe\index.js:44:5
gyp verb `which` failed     at C:\Users\Lee\AppData\Roaming\npm\node_modules\harp\node_modules                                                                                                  \isexe\windows.js:29:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:112:15) code: 'ENOENT' }
gyp verb could not find "python". checking python launcher
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variab                                                                                                  le.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\Lee\AppData\Roaming\npm\node_modules                                                                                                  \harp\node_modules\node-gyp\lib\configure.js:454:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\Lee\AppData\Roaming\npm\node_modules\                                                                                                  harp\node_modules\node-gyp\lib\configure.js:480:16)
gyp ERR! stack     at C:\Users\Lee\AppData\Roaming\npm\node_modules\harp\node_modules\node-gyp                                                                                                  \node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:112:15)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Lee\\AppData\\Roaming\\npm\                                                                                                  \node_modules\\harp\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsas                                                                                                  s_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\Lee\AppData\Roaming\npm\node_modules\harp\node_modules\node-sass
gyp ERR! node -v v7.5.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
Build failed
C:\Users\Lee\AppData\Roaming\npm
`-- (empty)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Lee\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "harp"
npm ERR! node v7.5.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.7.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.7.0 postinstall script 'node scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\cygwin64\home\Lee\npm-debug.log

**Comment by woodsr** [comment]
$ npm install -g harp
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install th                                                                                                                e latest version of pug instead of jade
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
C:\Users\Lee\AppData\Roaming\npm\harp -> C:\Users\Lee\AppData\Roaming\npm\node_modules\harp\bi                                                                                                  n\harp

> node-sass@3.7.0 install C:\Users\Lee\AppData\Roaming\npm\node_modules\harp\node_modules\node                                                                                                  -sass
> node scripts/install.js

Cannot download "https://github.com/sass/node-sass/releases/download/v3.7.0/win32-x64-51_bindi                                                                                                  ng.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@3.7.0 postinstall C:\Users\Lee\AppData\Roaming\npm\node_modules\harp\node_modules\                                                                                                  node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe C:\Users\Lee\AppData\Roaming\npm\node_modules\harp\                                                                                                  node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --lib                                                                                                  sass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\Lee\\AppData\\Roaming\\npm\\node_modules\\harp\\node_modules\\node-                                                                                                  gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.5.0
gyp info using node@7.5.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\Lee\AppData\Roaming\npm\node_modules                                                                                                  \harp\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Lee\AppData\Roaming\npm\node_modules\harp\node_modu                                                                                                  les\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Lee\AppData\Roaming\npm\node_modules\harp\node_modu                                                                                                  les\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Lee\AppData\Roaming\npm\node_modules\harp\node_modules                                                                                                  \which\which.js:89:16
gyp verb `which` failed     at C:\Users\Lee\AppData\Roaming\npm\node_modules\harp\node_modules                                                                                                  \isexe\index.js:44:5
gyp verb `which` failed     at C:\Users\Lee\AppData\Roaming\npm\node_modules\harp\node_modules                                                                                                  \isexe\windows.js:29:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:112:15)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\Lee\AppData\Roaming\npm\node_modules                                                                                                  \harp\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Lee\AppData\Roaming\npm\node_modules\harp\node_modu                                                                                                  les\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Lee\AppData\Roaming\npm\node_modules\harp\node_modu                                                                                                  les\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Lee\AppData\Roaming\npm\node_modules\harp\node_modules                                                                                                  \which\which.js:89:16
gyp verb `which` failed     at C:\Users\Lee\AppData\Roaming\npm\node_modules\harp\node_modules                                                                                                  \isexe\index.js:44:5
gyp verb `which` failed     at C:\Users\Lee\AppData\Roaming\npm\node_modules\harp\node_modules                                                                                                  \isexe\windows.js:29:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:112:15) code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\Users\Lee\AppData\Roaming\npm\node_modules                                                                                                  \harp\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Lee\AppData\Roaming\npm\node_modules\harp\node_modu                                                                                                  les\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Lee\AppData\Roaming\npm\node_modules\harp\node_modu                                                                                                  les\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Lee\AppData\Roaming\npm\node_modules\harp\node_modules                                                                                                  \which\which.js:89:16
gyp verb `which` failed     at C:\Users\Lee\AppData\Roaming\npm\node_modules\harp\node_modules                                                                                                  \isexe\index.js:44:5
gyp verb `which` failed     at C:\Users\Lee\AppData\Roaming\npm\node_modules\harp\node_modules                                                                                                  \isexe\windows.js:29:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:112:15)
gyp verb `which` failed  python { Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\Users\Lee\AppData\Roaming\npm\node_modules                                                                                                  \harp\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Lee\AppData\Roaming\npm\node_modules\harp\node_modu                                                                                                  les\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Lee\AppData\Roaming\npm\node_modules\harp\node_modu                                                                                                  les\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Lee\AppData\Roaming\npm\node_modules\harp\node_modules                                                                                                  \which\which.js:89:16
gyp verb `which` failed     at C:\Users\Lee\AppData\Roaming\npm\node_modules\harp\node_modules                                                                                                  \isexe\index.js:44:5
gyp verb `which` failed     at C:\Users\Lee\AppData\Roaming\npm\node_modules\harp\node_modules                                                                                                  \isexe\windows.js:29:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:112:15) code: 'ENOENT' }
gyp verb could not find "python". checking python launcher
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variab                                                                                                  le.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\Lee\AppData\Roaming\npm\node_modules                                                                                                  \harp\node_modules\node-gyp\lib\configure.js:454:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\Lee\AppData\Roaming\npm\node_modules\                                                                                                  harp\node_modules\node-gyp\lib\configure.js:480:16)
gyp ERR! stack     at C:\Users\Lee\AppData\Roaming\npm\node_modules\harp\node_modules\node-gyp                                                                                                  \node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:112:15)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Lee\\AppData\\Roaming\\npm\                                                                                                  \node_modules\\harp\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsas                                                                                                  s_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\Lee\AppData\Roaming\npm\node_modules\harp\node_modules\node-sass
gyp ERR! node -v v7.5.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
Build failed
C:\Users\Lee\AppData\Roaming\npm
`-- (empty)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Lee\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "harp"
npm ERR! node v7.5.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.7.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.7.0 postinstall script 'node scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\cygwin64\home\Lee\npm-debug.log
