### ISSUE TITLE
Weird NPM install behavor in Docker container, using github:user/repo#branch

### ISSUE THREAD

**Issue by ORESoftware** [npm/npm#15758]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I am trying to run an npm install command inside a Docker container, like so:

`npm --loglevel=warn --progress=false install`

with this dependency:

```
"dependencies": {
    "suman": "github:sumanjs/suman#dev"
  }
```

and I get this error log and I really have no idea what's going wrong:

```console
npm WARN addRemoteGit Error: Command failed: git config --get remote.origin.url
npm WARN addRemoteGit 
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:202:12)
npm WARN addRemoteGit     at emitTwo (events.js:100:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:185:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:850:16)
npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:323:11)
npm WARN addRemoteGit     at emitOne (events.js:90:13)
npm WARN addRemoteGit     at Socket.emit (events.js:182:7)
npm WARN addRemoteGit     at Pipe._onclose (net.js:484:12)
npm WARN addRemoteGit  sumanjs/suman#dev_integration resetting remote /home/docker/.npm/_git-remotes/git-github-com-sumanjs-suman-git-dev-integration-7f6c5d9d because of error: { [Error: Command failed: git config --get remote.origin.url
npm WARN addRemoteGit ]
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git config --get remote.origin.url' }
npm ERR! git clone --template=/home/docker/.npm/_git-remotes/_templates --mirror git://github.com/sumanjs/suman.git /home/docker/.npm/_git-remotes/git-github-com-sumanjs-suman-git-dev-integration-7f6c5d9d: Cloning into bare repository '/home/docker/.npm/_git-remotes/git-github-com-sumanjs-suman-git-dev-integration-7f6c5d9d'...
npm ERR! git clone --template=/home/docker/.npm/_git-remotes/_templates --mirror git://github.com/sumanjs/suman.git /home/docker/.npm/_git-remotes/git-github-com-sumanjs-suman-git-dev-integration-7f6c5d9d: fatal: Unable to read current working directory: No such file or directory
npm ERR! git clone --template=/home/docker/.npm/_git-remotes/_templates --mirror git://github.com/sumanjs/suman.git /home/docker/.npm/_git-remotes/git-github-com-sumanjs-suman-git-dev-integration-7f6c5d9d: fatal: index-pack failed
npm ERR! git fetch -a origin (git://github.com/sumanjs/suman.git) fatal: Unable to read current working directory: No such file or directory
npm ERR! git fetch -a origin (git://github.com/sumanjs/suman.git) fatal: index-pack failed
npm ERR! git rev-list -n1 dev_integration: fatal: ambiguous argument 'dev_integration': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 dev_integration: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 dev_integration: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 dev_integration: 
npm ERR! git clone --template=/home/docker/.npm/_git-remotes/_templates --mirror git@github.com:sumanjs/suman.git /home/docker/.npm/_git-remotes/git-github-com-sumanjs-suman-git-dev-integration-f0911193: Cloning into bare repository '/home/docker/.npm/_git-remotes/git-github-com-sumanjs-suman-git-dev-integration-f0911193'...
npm ERR! git clone --template=/home/docker/.npm/_git-remotes/_templates --mirror git@github.com:sumanjs/suman.git /home/docker/.npm/_git-remotes/git-github-com-sumanjs-suman-git-dev-integration-f0911193: /etc/ssh/ssh_config: line 55: Bad configuration option: -e
npm ERR! git clone --template=/home/docker/.npm/_git-remotes/_templates --mirror git@github.com:sumanjs/suman.git /home/docker/.npm/_git-remotes/git-github-com-sumanjs-suman-git-dev-integration-f0911193: /etc/ssh/ssh_config: terminating, 1 bad configuration options
npmPID => 13
 ERR! git clone --template=/home/docker/.npm/_git-remotes/_templates --mirror git@github.com:sumanjs/suman.git /home/docker/.npm/_git-remotes/git-github-com-sumanjs-suman-git-dev-integration-f0911193: fatal: Could not read from remote repository.
npm ERR! git clone --template=/home/docker/.npm/_git-remotes/_templates --mirror git@github.com:sumanjs/suman.git /home/docker/.npm/_git-remotes/git-github-com-sumanjs-suman-git-dev-integration-f0911193: 
npm ERR! git clone --template=/home/docker/.npm/_git-remotes/_templates --mirror git@github.com:sumanjs/suman.git /home/docker/.npm/_git-remotes/git-github-com-sumanjs-suman-git-dev-integration-f0911193: Please make sure you have the correct access rights
npm ERR! git clone --template=/home/docker/.npm/_git-remotes/_templates --mirror git@github.com:sumanjs/suman.git /home/docker/.npm/_git-remotes/git-github-com-sumanjs-suman-git-dev-integration-f0911193: and the repository exists.
npm ERR! Linux 4.4.0-62-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "--loglevel=warn" "--progress=false" "install"
npm ERR! node v5.12.0
npm ERR! npm  v3.8.6
npm ERR! code 128

npm ERR! Command failed: git clone --template=/home/docker/.npm/_git-remotes/_templates --mirror git@github.com:sumanjs/suman.git /home/docker/.npm/_git-remotes/git-github-com-sumanjs-suman-git-dev-integration-f0911193
npm ERR! Cloning into bare repository '/home/docker/.npm/_git-remotes/git-github-com-sumanjs-suman-git-dev-integration-f0911193'...
npm ERR! /etc/ssh/ssh_config: line 55: Bad configuration option: -e
npm ERR! /etc/ssh/ssh_config: terminating, 1 bad configuration options
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/docker/three/npm-debug.log
npm ERR! git rev-list -n1 dev_integration: fatal: ambiguous argument 'dev_integration': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 dev_integration: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 dev_integration: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 dev_integration: 
npm ERR! git clone --template=/home/docker/.npm/_git-remotes/_templates --mirror git@github.com:sumanjs/suman.git /home/docker/.npm/_git-remotes/git-github-com-sumanjs-suman-git-dev-integration-f0911193: Cloning into bare repository '/home/docker/.npm/_git-remotes/git-github-com-sumanjs-suman-git-dev-integration-f0911193'...
npm ERR! git clone --template=/home/docker/.npm/_git-remotes/_templates --mirror git@github.com:sumanjs/suman.git /home/docker/.npm/_git-remotes/git-github-com-sumanjs-suman-git-dev-integration-f0911193: /etc/ssh/ssh_config: line 55: Bad configuration option: -e
npm ERR! git clone --template=/home/docker/.npm/_git-remotes/_templates --mirror git@github.com:sumanjs/suman.git /home/docker/.npm/_git-remotes/git-github-com-sumanjs-suman-git-dev-integration-f0911193: /etc/ssh/ssh_config: terminating, 1 bad configuration options
npm ERR! git clone --template=/home/docker/.npm/_git-remotes/_templates --mirror git@github.com:sumanjs/suman.git /home/docker/.npm/_git-remotes/git-github-com-sumanjs-suman-git-dev-integration-f0911193: fatal: Could not read from remote repository.
npm ERR! git clone --template=/home/docker/.npm/_git-remotes/_templates --mirror git@github.com:sumanjs/suman.git /home/docker/.npm/_git-remotes/git-github-com-sumanjs-suman-git-dev-integration-f0911193: 
npm ERR! git clone --template=/home/docker/.npm/_git-remotes/_templates --mirror git@github.com:sumanjs/suman.git /home/docker/.npm/_git-remotes/git-github-com-sumanjs-suman-git-dev-integration-f0911193: Please make sure you have the correct access rights
npm ERR! git clone --template=/home/docker/.npm/_git-remotes/_templates --mirror git@github.com:sumanjs/suman.git /home/docker/.npm/_git-remotes/git-github-com-sumanjs-suman-git-dev-integration-f0911193: and the repository exists.
npm ERR! Linux 4.4.0-62-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "--loglevel=warn" "--progress=false" "install"
npm ERR! node v5.12.0
npm ERR! npm  v3.8.6
npm ERR! code 128

npm ERR! Command failed: git clone --template=/home/docker/.npm/_git-remotes/_templates --mirror git@github.com:sumanjs/suman.git /home/docker/.npm/_git-remotes/git-github-com-sumanjs-suman-git-dev-integration-f0911193
npm ERR! Cloning into bare repository '/home/docker/.npm/_git-remotes/git-github-com-sumanjs-suman-git-dev-integration-f0911193'...
npm ERR! /etc/ssh/ssh_config: line 55: Bad configuration option: -e
npm ERR! /etc/ssh/ssh_config: terminating, 1 bad configuration options
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/docker/two/npm-debug.log

```

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [x] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by ORESoftware** [comment]
I really don't know why NPM gives me this:

```
npm ERR! git rev-list -n1 dev_integration: fatal: ambiguous argument 'dev_integration': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 dev_integration: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 dev_integration: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 dev_integration: 
```

I cannot figure out why that error is happening

**Comment by buck** [comment]
I think this line is the source of your problem:

> /etc/ssh/ssh_config: line 55: Bad configuration option: -e

I borrowed some Dockerfile boilerplate from:

http://farazdagi.com/blog/2016/ssh-private-keys-on-docker-build/

The "-e" was being written as the last line of the ssh_config file (line 55) as:

```
    GSSAPIAuthentication yes
    GSSAPIDelegateCredentials no
-e StrictHostKeyChecking no
```

which is invalid syntax, and git cannot connect over SSH.  Find where that "-e" is coming in and you should be good to go.
