### ISSUE TITLE
npm install: RangeError: port should be >= 0 and < 65536: 98721

### ISSUE THREAD

**Issue by Wenliang-CHEN** [npm/npm#15762]
Hi all,

I am getting the following error when I use npm install

0 info it worked if it ends with ok
1 verbose cli [ 'D:\\nodejs\\node.exe',
1 verbose cli   'D:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'bower' ]
2 info using npm@4.1.2
3 info using node@v7.5.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData bower
8 silly fetchNamedPackageData bower
9 silly mapToRegistry name bower
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'bower',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'bower',
12 silly mapToRegistry   name: 'bower',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/bower
14 verbose request uri https://registry.npmjs.org/bower
15 verbose request no auth needed
16 info attempt registry request try #1 at 1:21:05 PM
17 verbose request id b74f5e0107cfb5e6
18 http request GET https://registry.npmjs.org/bower
19 info retry will retry, error on last attempt: RangeError: "port" option should be >= 0 and < 65536: 98721
20 info attempt registry request try #2 at 1:21:15 PM
21 http request GET https://registry.npmjs.org/bower
22 info retry will retry, error on last attempt: RangeError: "port" option should be >= 0 and < 65536: 98721
23 info attempt registry request try #3 at 1:22:15 PM
24 http request GET https://registry.npmjs.org/bower
25 silly fetchPackageMetaData RangeError: "port" option should be >= 0 and < 65536: 98721
25 silly fetchPackageMetaData     at lookupAndConnect (net.js:964:13)
25 silly fetchPackageMetaData     at Socket.connect (net.js:939:5)
25 silly fetchPackageMetaData     at Agent.exports.connect.exports.createConnection (net.js:74:35)
25 silly fetchPackageMetaData     at Agent.createSocket (_http_agent.js:195:26)
25 silly fetchPackageMetaData     at Agent.addRequest (_http_agent.js:157:10)
25 silly fetchPackageMetaData     at new ClientRequest (_http_client.js:212:16)
25 silly fetchPackageMetaData     at TunnelingAgent.request (http.js:26:10)
25 silly fetchPackageMetaData     at TunnelingAgent.createSocket (D:\nodejs\node_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:134:25)
25 silly fetchPackageMetaData     at TunnelingAgent.createSecureSocket [as createSocket] (D:\nodejs\node_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:199:41)
25 silly fetchPackageMetaData     at TunnelingAgent.createConnection (D:\nodejs\node_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:97:8)
25 silly fetchPackageMetaData  error for bower RangeError: "port" option should be >= 0 and < 65536: 98721
25 silly fetchPackageMetaData     at lookupAndConnect (net.js:964:13)
25 silly fetchPackageMetaData     at Socket.connect (net.js:939:5)
25 silly fetchPackageMetaData     at Agent.exports.connect.exports.createConnection (net.js:74:35)
25 silly fetchPackageMetaData     at Agent.createSocket (_http_agent.js:195:26)
25 silly fetchPackageMetaData     at Agent.addRequest (_http_agent.js:157:10)
25 silly fetchPackageMetaData     at new ClientRequest (_http_client.js:212:16)
25 silly fetchPackageMetaData     at TunnelingAgent.request (http.js:26:10)
25 silly fetchPackageMetaData     at TunnelingAgent.createSocket (D:\nodejs\node_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:134:25)
25 silly fetchPackageMetaData     at TunnelingAgent.createSecureSocket [as createSocket] (D:\nodejs\node_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:199:41)
25 silly fetchPackageMetaData     at TunnelingAgent.createConnection (D:\nodejs\node_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:97:8)
26 silly rollbackFailedOptional Starting
27 silly rollbackFailedOptional Finishing
28 silly runTopLevelLifecycles Finishing
29 silly install printInstalled
30 verbose stack RangeError: "port" option should be >= 0 and < 65536: 98721
30 verbose stack     at lookupAndConnect (net.js:964:13)
30 verbose stack     at Socket.connect (net.js:939:5)
30 verbose stack     at Agent.exports.connect.exports.createConnection (net.js:74:35)
30 verbose stack     at Agent.createSocket (_http_agent.js:195:26)
30 verbose stack     at Agent.addRequest (_http_agent.js:157:10)
30 verbose stack     at new ClientRequest (_http_client.js:212:16)
30 verbose stack     at TunnelingAgent.request (http.js:26:10)
30 verbose stack     at TunnelingAgent.createSocket (D:\nodejs\node_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:134:25)
30 verbose stack     at TunnelingAgent.createSecureSocket [as createSocket] (D:\nodejs\node_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:199:41)
30 verbose stack     at TunnelingAgent.createConnection (D:\nodejs\node_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:97:8)
31 verbose cwd D:\nodejs\node_modules
32 error Windows_NT 10.0.14393
33 error argv "D:\\nodejs\\node.exe" "D:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "bower"
34 error node v7.5.0
35 error npm  v4.1.2
36 error "port" option should be >= 0 and < 65536: 98721
37 error If you need help, you may report this error at:
37 error     <https://github.com/npm/npm/issues>
38 verbose exit [ 1, true ]

The weird is the port 98721.  I did not configure such port before.

Any ideas?

**Comment by Wenliang-CHEN** [comment]
Just figured out it is due to the proxy environment variable setting.  Closing this ticket
