### ISSUE TITLE
Npm packages on git bash not working properly

### ISSUE THREAD

**Issue by karthigamahe** [npm/npm#15779]
Please any one help me to figure it out this error, I m trying to run ionic application in my system i installed ionic and cordova but when i check its version and when i try to run ionic app it show the error messge like

```
$ ionic -v
module.js:471
    throw err;
    ^

Error: Cannot find module 'C:\Program Files\Git\node_modules\ionic\bin\ionic'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

```

I am just confused where the problem is please help me out..

**Comment by legodude17** [comment]
What is the contents of `C:\Program Files\Git\node_modules\ionic\bin`?

**Comment by karthigamahe** [comment]
![ionic](https://cloud.githubusercontent.com/assets/10694128/23053333/a3034bb4-f4fe-11e6-8796-c3135e5f8582.png)


Inside that path i m having this file ....I installed ionic and cordova properly but while i running ionic app it show error like



```

$ ionic serve --lab
******************************************************
 Dependency warning - for the CLI to run correctly,
 it is highly recommended to install/upgrade the following:

 Please install your Cordova CLI to version  >=4.2.0 `npm install -g cordova`

******************************************************

> ionic-app-base@ ionic:serve E:\Sandbox\ionic\demoApp
> ionic-app-scripts serve "--v2" "--lab" "--address" "0.0.0.0" "--port" "8100" "                         --livereload-port" "35729"


npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\admin\\AppData\\                         Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "ionic:serve" "--" "--v2                         " "--lab" "--address" "0.0.0.0" "--port" "8100" "--livereload-port" "35729"
npm ERR! node v6.9.5
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ionic-app-base@ ionic:serve: `ionic-app-scripts serve "--v2" "--lab" "-                         -address" "0.0.0.0" "--port" "8100" "--livereload-port" "35729"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ionic-app-base@ ionic:serve script 'ionic-app-scripts ser                         ve "--v2" "--lab" "--address" "0.0.0.0" "--port" "8100" "--livereload-port" "357                         29"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ionic-app-base packag                         e,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ionic-app-scripts serve "--v2" "--lab" "--address" "0.0.0.0" "--por                         t" "8100" "--livereload-port" "35729"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ionic-app-base
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ionic-app-base
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\admin\AppData\Roaming\npm-cache\_logs\2017-02-17T05_15_05_                         486Z-debug.log
There was an error serving your Ionic application: There was an error with the s                         pawned command: serve
```
Please help me out..

**Comment by legodude17** [comment]
Try running `npm install -g cordova` as the error message said.

**Comment by karthigamahe** [comment]
@legodude17  Thank you its working fine now
