### ISSUE TITLE
Terminal opens up with an error

### ISSUE THREAD

**Issue by skociu** [npm/npm#15776]
### I'm encountering a long error message when opening up the terminal in Ubuntu. The error is annoying and I want to have the ability to clear it. I attempted to upgrade npm, git and nodejs using the following commands and the issue still persists.

```
sudo apt-get upgrade git
sudo apt-get upgrade npm
sudo apt-get upgrade nodejs
```

Here is more information that you might find useful:

```
npm --version'
3.5.2
git --version
git version 2.9.3
nodejs --version
v4.2.6_
```

### The error message is as follows:

```
Error: Cannot find module 'hosted-git-info'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/sk/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:6:17)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
npm ERR! Linux 4.8.0-37-generic
npm ERR! argv "/home/sk/.nvm/versions/node/v5.0.0/bin/node" "/home/sk/.nvm/versions/node/v5.0.0/bin/npm" "config" "get" "prefix"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'hosted-git-info'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
nvm is not compatible with the npm config "prefix" option: currently set to ""
Run `npm config delete prefix` or `nvm use --delete-prefix v5.0.0 --silent` to unset it._
```

**Comment by KenanY** [comment]
@skociu Looks like you have two versions of `npm` and Node installed, since you seem to be using both `apt-get` and `nvm` simultaneously. Could you try removing the `apt-get` installation of Node and `npm`, and then try reinstalling Node and `npm` through `nvm`?

**Comment by KenanY** [comment]
Closing as abandoned.
