### ISSUE TITLE
npm adduser fails !

### ISSUE THREAD

**Issue by sayantan94** [npm/npm#15780]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [x] npm is producing an incorrect install.
  
#### What's going wrong?
On the execution of the above command it throws the following error:
npm adduser --registry http://127.0.0.1:4873 
```

 Username: sayantan
Password:
Email: (this IS public) sayantan.bhowmik94@gmail.com
npm ERR! registry error parsing json
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "add
user" "--registry" "http://127.0.0.1:4873"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! Unexpected token < in JSON at position 0
npm ERR! <HTML>
npm ERR! <HEAD><TITLE>Redirection</ TITLE></HEAD>
npm ERR! <BODY><H1>Redirect</H1></BODY>
npm `ERR!`
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\bhowmiks\workspace\BACK-UP\vpmui\npm-debug.log

```
NPM DEBUG LOGS

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'adduser',
1 verbose cli   '--registry',
1 verbose cli   'http://127.0.0.1:4873' ]
2 info using npm@3.10.8
3 info using node@v6.9.1
4 verbose adduser before first PUT { _id: 'org.couchdb.user:sayantan',
4 verbose adduser   name: 'sayantan',
4 verbose adduser   password: 'XXXXX',
4 verbose adduser   email: 'sayantan.bhowmik94@gmail.com',
4 verbose adduser   type: 'user',
4 verbose adduser   roles: [],
4 verbose adduser   date: '2017-02-16T04:56:26.946Z' }
5 verbose request uri http://127.0.0.1:4873/-/user/org.couchdb.user:sayantan
6 verbose request new user, so can't send auth
7 info attempt registry request try #1 at 10:26:26 AM
8 verbose request id ffdec74ab3f0fad3
9 http request PUT http://127.0.0.1:4873/-/user/org.couchdb.user:sayantan
10 http 301 http://127.0.0.1:4873/-/user/org.couchdb.user:sayantan
11 verbose bad json <HTML>
11 verbose bad json <HEAD><TITLE>Redirection</TITLE></HEAD>
11 verbose bad json <BODY><H1>Redirect</H1></BODY>
12 error registry error parsing json
13 verbose headers { server: 'BlueCoat-Security-Appliance',
13 verbose headers   location: 'http://15.34.74.212',
13 verbose headers   connection: 'Close' }
14 verbose request invalidating C:\Users\bhowmiks\AppData\Roaming\npm-cache\127.0.0.1_4873\-\user\org.couchdb.user_3Asayantan on PUT
15 verbose adduser back [ SyntaxError: Unexpected token < in JSON at position 0
15 verbose adduser   <HTML>
15 verbose adduser   <HEAD><TITLE>Redirection</TITLE></HEAD>
15 verbose adduser   <BODY><H1>Redirect</H1></BODY>
15 verbose adduser
15 verbose adduser       at Object.parse (native)
15 verbose adduser       at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:237:23)
15 verbose adduser       at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:210:14)
15 verbose adduser       at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:187:22)
15 verbose adduser       at emitTwo (events.js:106:13)
15 verbose adduser       at Request.emit (events.js:191:7)
15 verbose adduser       at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1044:10)
15 verbose adduser       at emitOne (events.js:96:13)
15 verbose adduser       at Request.emit (events.js:188:7)
15 verbose adduser       at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:965:12),
15 verbose adduser   null,
15 verbose adduser   '<HTML>\r\n<HEAD><TITLE>Redirection</TITLE></HEAD>\r\n<BODY><H1>Redirect</H1></BODY>\r\n' ]
16 verbose stack SyntaxError: Unexpected token < in JSON at position 0
16 verbose stack <HTML>
16 verbose stack <HEAD><TITLE>Redirection</TITLE></HEAD>
16 verbose stack <BODY><H1>Redirect</H1></BODY>
16 verbose stack
16 verbose stack     at Object.parse (native)
16 verbose stack     at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:237:23)
16 verbose stack     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:210:14)
16 verbose stack     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:187:22)
16 verbose stack     at emitTwo (events.js:106:13)
16 verbose stack     at Request.emit (events.js:191:7)
16 verbose stack     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1044:10)
16 verbose stack     at emitOne (events.js:96:13)
16 verbose stack     at Request.emit (events.js:188:7)
16 verbose stack     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:965:12)
17 verbose cwd C:\Users\bhowmiks\workspace\BACK-UP\vpmui
18 error Windows_NT 6.1.7601
19 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "adduser" "--registry" "http://127.0.0.1:4873"
20 error node v6.9.1
21 error npm  v3.10.8
22 error Unexpected token < in JSON at position 0
22 error <HTML>
22 error <HEAD><TITLE>Redirection</TITLE></HEAD>
22 error <BODY><H1>Redirect</H1></BODY>
23 error If you need help, you may report this error at:
23 error     <https://github.com/npm/npm/issues>
24 verbose exit [ 1, true ]

```

**Comment by legodude17** [comment]
What is the result of `npm config get registry`?

**Comment by sayantan94** [comment]
This happened to be a proxy issue, I was using sinopia server, once I added proxy links in the sinopia config.yaml file, the problem was resolved.
