### ISSUE TITLE
npm version error

### ISSUE THREAD

**Issue by egoist** [npm/npm#15858]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

Running `npm version patch -m "-> %s"` and it says no commit message:

```bash
10 info git [ 'add', '/Users/egoist/dev/project/package.json' ]
11 info git [ 'commit', '-m', '' ]
12 verbose stack Error: Command failed: git commit -m
12 verbose stack Aborting commit due to empty commit message.
12 verbose stack
12 verbose stack     at ChildProcess.exithandler (child_process.js:211:12)
12 verbose stack     at emitTwo (events.js:106:13)
12 verbose stack     at ChildProcess.emit (events.js:192:7)
12 verbose stack     at maybeClose (internal/child_process.js:890:16)
12 verbose stack     at Socket.<anonymous> (internal/child_process.js:334:11)
12 verbose stack     at emitOne (events.js:96:13)
12 verbose stack     at Socket.emit (events.js:189:7)
12 verbose stack     at Pipe._handle.close [as _onclose] (net.js:501:12)
13 verbose cwd /Users/egoist/dev/conpack
14 error Darwin 16.3.0
15 error argv "/Users/egoist/.nvm/versions/node/v7.6.0/bin/node" "/Users/egoist/.nvm/versions/node/v7.6.0/bin/npm" "version" "minor" "-m" "-> %s"
16 error node v7.6.0
17 error npm  v4.3.0
18 error code 1
19 error Command failed: git commit -m
19 error Aborting commit due to empty commit message.
20 error If you need help, you may report this error at:
20 error     <https://github.com/npm/npm/issues>
21 verbose exit [ 1, true ]
```

#### How can the CLI team reproduce the problem?

Use npm 4/5 and run `npm version patch -m "-> %s"`, only works in npm 3

### supporting information:

 - `npm -v` prints: 4.3.0 (4.1 does not work either) 
 - `node -v` prints: 7.6.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: macOS
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
What are the full contents of `npm-debug.log`.

**Comment by egoist** [comment]
```bash
0 info it worked if it ends with ok
1 verbose cli [ '/Users/egoist/.nvm/versions/node/v7.6.0/bin/node',
1 verbose cli   '/Users/egoist/.nvm/versions/node/v7.6.0/bin/npm',
1 verbose cli   'version',
1 verbose cli   'minor',
1 verbose cli   '-m',
1 verbose cli   '-> %s' ]
2 info using npm@4.3.0
3 info using node@v7.6.0
4 info git [ 'status', '--porcelain' ]
5 verbose stack Error: Git working directory not clean.
5 verbose stack M  package.json
5 verbose stack     at /Users/egoist/.nvm/versions/node/v7.6.0/lib/node_modules/npm/lib/version.js:247:19
5 verbose stack     at /Users/egoist/.nvm/versions/node/v7.6.0/lib/node_modules/npm/lib/utils/no-progress-while-running.js:21:8
5 verbose stack     at ChildProcess.exithandler (child_process.js:202:7)
5 verbose stack     at emitTwo (events.js:106:13)
5 verbose stack     at ChildProcess.emit (events.js:192:7)
5 verbose stack     at maybeClose (internal/child_process.js:890:16)
5 verbose stack     at Socket.<anonymous> (internal/child_process.js:334:11)
5 verbose stack     at emitOne (events.js:96:13)
5 verbose stack     at Socket.emit (events.js:189:7)
5 verbose stack     at Pipe._handle.close [as _onclose] (net.js:501:12)
6 verbose cwd /Users/egoist/dev/changelog.md
7 error Darwin 16.3.0
8 error argv "/Users/egoist/.nvm/versions/node/v7.6.0/bin/node" "/Users/egoist/.nvm/versions/node/v7.6.0/bin/npm" "version" "minor" "-m" "-> %s"
9 error node v7.6.0
10 error npm  v4.3.0
11 error Git working directory not clean.
11 error M  package.json
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]
```

**Comment by egoist** [comment]
Any updates on this? npm v5 didn't work either.
