### ISSUE TITLE
npm run dev error on Ubuntu 16.04, Laravel Homestead Laravel 5.4 on fresh project

### ISSUE THREAD

**Issue by mirbatworks** [npm/npm#15875]
I use laravel homestead on my Ubuntu 16.04. LTS. On new Laravel 5.4 project I get this errors when I run `npm run dev` or `npm run watch` command. This is errors from terminal:

```
vagrant@homestead:~/www/blog$ npm run dev

> @ dev /home/vagrant/www/blog
> node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

/home/vagrant/www/blog/node_modules/laravel-mix/setup/webpack.config.js:126
        let extractPlugin = new plugins.ExtractTextPlugin(
        ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at requireConfig (/home/vagrant/www/blog/node_modules/webpack/bin/convert-argv.js:96:18)
    at /home/vagrant/www/blog/node_modules/webpack/bin/convert-argv.js:109:17
    at Array.forEach (native)

npm ERR! Linux 3.19.0-25-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "dev"
npm ERR! node v5.7.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! @ dev: `node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ dev script 'node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/www/blog/npm-debug.log
```
Log File:
[npm-debug.log.zip](https://github.com/npm/npm/files/802085/npm-debug.log.zip)

**Comment by KenanY** [comment]
@mirbatworks Error indicates that you have a syntax error in `webpack.config.js`. Closing since this isn't an `npm` issue.

**Comment by mirbatworks** [comment]
I didn't make any changes in webpack.config.js and I don't know where is that file. If you think on webpack.mix.js, I didn't make any changes it's default:
 
```
const { mix } = require('laravel-mix');

/*
 |--------------------------------------------------------------------------
 | Mix Asset Management
 |--------------------------------------------------------------------------
 |
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Laravel application. By default, we are compiling the Sass
 | file for the application as well as bundling up all the JS files.
 |
 */

mix.js('resources/assets/js/app.js', 'public/js')
   .sass('resources/assets/sass/app.scss', 'public/css');
```

**Comment by KenanY** [comment]
Sorry, this is the file with the syntax error:

```
/home/vagrant/www/blog/node_modules/laravel-mix/setup/webpack.config.js:126
```

**Comment by KenanY** [comment]
Also, you should know that Node.js v5 is no longer maintained, since it was simply the development branch that became v6 (which has been out for a while now).

**Comment by mirbatworks** [comment]
I didn't install node.js its come with Laravel Homestead. I can't find solution how to upgrade node.js in homestead. My Vagrant Box is updated.

**Comment by Yuant-tobing** [comment]
I often get an error when using NPM, but all will be well after I perform the following steps:

1. command: $ `npm rebuild`
2. command: `$ npm install` {did not include the --no-bin-links}
3. command: `$ npm run dev`

everything would go well. I have tried it on a project laravel 5.4. I hope, this solution can help you and others.

**Comment by mirbatworks** [comment]
I solved. First I uninstall my old nodejs
`sudo apt-get purge nodejs npm`
than:
`curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -`
and than:
`sudo apt-get install -y nodejs`

**Comment by dborovsky** [comment]
I had same error. After updating to node v.7, the issue was remained.  Only updating  npm to v. 5 helped.
