### ISSUE TITLE
Everytime installs node_modules again

### ISSUE THREAD

**Issue by dalisoft** [npm/npm#15898]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I using `npm` recently, for `Webpack + `Babel` transpiler` and i like it nice works.

But every time i using `npm install` on my module path downloading `devDependecies` to `node_modules` and it takes a lot of traffic as i haven't much.

When i create module on other folder or drive, it requires re-download/re-install that modules.

I need just few packages such as `Webpack + Babel + jTest` on my all modules.

Question:
* Is `npm` can cache modules?
* Is `npm` can from anywhere can use cached module?

This would be best.

thanks

**Comment by KenanY** [comment]
Yeah, `npm` caches into [`cache`](https://docs.npmjs.com/misc/config#cache).

**Comment by dalisoft** [comment]
How i can do it? Please, can you explain?

**Comment by KenanY** [comment]
@dalisoft It's enabled by default :)

**Comment by dalisoft** [comment]
But it downloads again and again, even requires manual install of `webpack + babel`

**Comment by KenanY** [comment]
@dalisoft Are you sure it's actually doing a full download (usually this is indicated by a `200` response, whereas `304` is cached)? You could increase your [`cache-min`](https://docs.npmjs.com/misc/config#cache-min) if you want as well.

**Comment by dalisoft** [comment]
Here i can provide you example as possible.
Folder already made.
```bash
cd /D D:\npm
npm init
# type config
# package.json made by npm done
```

```javascript
"scripts": {
    "build": "webpack --env build",
    "source": "webpack --progress --colors --env dev",
    "dev": "webpack --progress --colors --watch --env dev"
  },
"devDependencies": {
    "babel": "6.5.2",
    "babel-core": "6.22.1",
    "babel-eslint": "7.1.1",
    "babel-loader": "6.2.10",
    "babel-plugin-add-module-exports": "0.1.2",
    "babel-plugin-transform-es2015-classes": "latest",
    "babel-plugin-transform-proto-to-assign": "latest",
    "babel-plugin-transform-react-jsx": "latest",
    "babel-preset-es2015": "6.22.0",
    "eslint": "1.7.2",
    "eslint-loader": "1.6.1",
    "webpack": "2.2.1",
    "yargs": "6.6.0"
  },
```
Then i use

```bash
npm run source # this requires module webpack, but i installed module via npm install webpack
npm run build # this requires module webpack, but i installed module via npm install webpack
npm publish
```

**Comment by KenanY** [comment]
@dalisoft Looks fine to me. First `npm install` does hit registry, second hits cache. I think we're gonna have to see what console output you're concerned about.

**Comment by dalisoft** [comment]
I now making other package, soon publish. but i need that cached. only babel modules takes ~60Mb for me i dont know why

**Comment by dalisoft** [comment]
```bash
D:\GitHub\datadd>npm run source

> datadd@0.0.1 source D:\GitHub\datadd
> webpack --progress --colors --env dev

"webpack" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.

npm ERR! Windows_NT 6.1.7600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "run" "source"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! datadd@0.0.1 source: `webpack --progress --colors --env dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the datadd@0.0.1 source script 'webpack --progress --colors -
-env dev'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the datadd package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack --progress --colors --env dev
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs datadd
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls datadd
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to in
stall?

npm ERR! Please include the following file with any support request:
npm ERR!     D:\GitHub\datadd\npm-debug.log
```

```bash
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'source' ]
2 info using npm@3.10.3
3 info using node@v6.3.1
4 verbose run-script [ 'presource', 'source', 'postsource' ]
5 info lifecycle datadd@0.0.1~presource: datadd@0.0.1
6 silly lifecycle datadd@0.0.1~presource: no script for presource, continuing
7 info lifecycle datadd@0.0.1~source: datadd@0.0.1
8 verbose lifecycle datadd@0.0.1~source: unsafe-perm in lifecycle true
9 verbose lifecycle datadd@0.0.1~source: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;D:\GitHub\datadd\node_modules\.bin;C:\Program Files\nodejs;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\TortoiseGit\bin;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Program Files\Brackets\command;C:\Program Files\Yarn\bin;C:\Users\Dalerjon\AppData\Roaming\npm;C:\Users\Dalerjon\AppData\Local\Yarn\.bin
10 verbose lifecycle datadd@0.0.1~source: CWD: D:\GitHub\datadd
11 silly lifecycle datadd@0.0.1~source: Args: [ '/d /s /c', 'webpack --progress --colors --env dev' ]
12 silly lifecycle datadd@0.0.1~source: Returned: code: 1  signal: null
13 info lifecycle datadd@0.0.1~source: Failed to exec source script
14 verbose stack Error: datadd@0.0.1 source: `webpack --progress --colors --env dev`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:852:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid datadd@0.0.1
16 verbose cwd D:\GitHub\datadd
17 error Windows_NT 6.1.7600
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "source"
19 error node v6.3.1
20 error npm  v3.10.3
21 error code ELIFECYCLE
22 error datadd@0.0.1 source: `webpack --progress --colors --env dev`
22 error Exit status 1
23 error Failed at the datadd@0.0.1 source script 'webpack --progress --colors --env dev'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the datadd package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     webpack --progress --colors --env dev
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs datadd
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls datadd
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by dalisoft** [comment]
@KenanY see my log

**Comment by KenanY** [comment]
I do not see any re-downloading in that `npm install` log.

**Comment by dalisoft** [comment]
Thanks
