### ISSUE TITLE
missing script "start

### ISSUE THREAD

**Issue by cw-petersen** [npm/npm#15951]
npm start
npm ERR! Linux 3.19.0-32-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v6.10.0
npm ERR! npm v3.10.10

npm ERR! missing script: start
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR! https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR! /home/cw/tutorial/npm-debug.log

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@3.10.10
3 info using node@v6.10.0
4 verbose stack Error: missing script: start
4 verbose stack at run (/usr/lib/node_modules/npm/lib/run-script.js:151:19)
4 verbose stack at /usr/lib/node_modules/npm/lib/run-script.js:61:5
4 verbose stack at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:356:5
4 verbose stack at checkBinReferences_ (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:320:45)
4 verbose stack at final (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:354:3)
4 verbose stack at then (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:124:5)
4 verbose stack at ReadFileContext. (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:295:20)
4 verbose stack at ReadFileContext.callback (/usr/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16)
4 verbose stack at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:365:13)
5 verbose cwd /home/cw/tutorial
6 error Linux 3.19.0-32-generic
7 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
8 error node v6.10.0
9 error npm v3.10.10
10 error missing script: start
11 error If you need help, you may report this error at:
11 error https://github.com/npm/npm/issues
12 verbose exit [ 1, true ]

**Comment by cw-petersen** [comment]
OS LinuxMint 17.3 64 bit
