### ISSUE TITLE
i use npm run dev, error comes

### ISSUE THREAD

**Issue by Raman0716** [npm/npm#15975]
#####npm run dev ,  error info :
*******
 fVue.js@1.0.0 dev /Users/raman/Documents/jinlun/geron-wire/manage
> node build/dev-server.js

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server._listen2 (net.js:1259:14)
    at listen (net.js:1295:10)
    at Server.listen (net.js:1391:5)
    at EventEmitter.listen (/Users/raman/Documents/jinlun/geron-wire/manage/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/Users/raman/Documents/jinlun/geron-wire/manage/build/dev-server.js:59:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v6.10.0
npm ERR! npm  v4.3.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fVue.js@1.0.0 dev: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fVue.js@1.0.0 dev script 'node build/dev-server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fVue.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build/dev-server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fVue.js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls fVue.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/raman/.npm/_logs/2017-03-08T02_52_03_585Z-debug.log

**Comment by doshisid** [comment]
it is likely that you already have a process running on that port.
if not so, please post your npm-debug.log

**Comment by KenanY** [comment]
Yeah, this error isn't coming from `npm`. All `npm` is doing here is catching the error thrown by `node build/dev-server.js`.
