### ISSUE TITLE
NPM is looking for Program_Files but it's programmes

### ISSUE THREAD

**Issue by onigetoc** [npm/npm#16024]
I have this error: ERR! Windows_NT 6.1.7601

npm is looking for Program_Files but programmes folder (french) is where node is installed.
I installed the nodejs 86x but it change nothing

ERROR:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@4.1.2
3 info using node@v7.7.2
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly install normalizeTree
8 silly loadCurrentTree Finishing
9 silly loadIdealTree Starting
10 silly install loadIdealTree
11 silly cloneCurrentTree Starting
12 silly install cloneCurrentTreeToIdealTree
13 silly cloneCurrentTree Finishing
14 silly loadShrinkwrap Starting
15 silly install loadShrinkwrap
16 silly loadShrinkwrap Finishing
17 silly loadAllDepsIntoIdealTree Starting
18 silly install loadAllDepsIntoIdealTree
19 silly fetchNamedPackageData angular
20 silly mapToRegistry name angular
21 silly mapToRegistry using default registry
22 silly mapToRegistry registry https://registry.npmjs.org/
23 silly mapToRegistry data Result {
23 silly mapToRegistry   raw: 'angular',
23 silly mapToRegistry   scope: null,
23 silly mapToRegistry   escapedName: 'angular',
23 silly mapToRegistry   name: 'angular',
23 silly mapToRegistry   rawSpec: '',
23 silly mapToRegistry   spec: 'latest',
23 silly mapToRegistry   type: 'tag' }
24 silly mapToRegistry uri https://registry.npmjs.org/angular
25 silly fetchNamedPackageData angular-animate
26 silly mapToRegistry name angular-animate
27 silly mapToRegistry using default registry
28 silly mapToRegistry registry https://registry.npmjs.org/
29 silly mapToRegistry data Result {
29 silly mapToRegistry   raw: 'angular-animate',
29 silly mapToRegistry   scope: null,
29 silly mapToRegistry   escapedName: 'angular-animate',
29 silly mapToRegistry   name: 'angular-animate',
29 silly mapToRegistry   rawSpec: '',
29 silly mapToRegistry   spec: 'latest',
29 silly mapToRegistry   type: 'tag' }
30 silly mapToRegistry uri https://registry.npmjs.org/angular-animate
31 silly fetchNamedPackageData angular-aria
32 silly mapToRegistry name angular-aria
33 silly mapToRegistry using default registry
34 silly mapToRegistry registry https://registry.npmjs.org/
35 silly mapToRegistry data Result {
35 silly mapToRegistry   raw: 'angular-aria',
35 silly mapToRegistry   scope: null,
35 silly mapToRegistry   escapedName: 'angular-aria',
35 silly mapToRegistry   name: 'angular-aria',
35 silly mapToRegistry   rawSpec: '',
35 silly mapToRegistry   spec: 'latest',
35 silly mapToRegistry   type: 'tag' }
36 silly mapToRegistry uri https://registry.npmjs.org/angular-aria
37 silly fetchNamedPackageData angular-messages
38 silly mapToRegistry name angular-messages
39 silly mapToRegistry using default registry
40 silly mapToRegistry registry https://registry.npmjs.org/
41 silly mapToRegistry data Result {
41 silly mapToRegistry   raw: 'angular-messages',
41 silly mapToRegistry   scope: null,
41 silly mapToRegistry   escapedName: 'angular-messages',
41 silly mapToRegistry   name: 'angular-messages',
41 silly mapToRegistry   rawSpec: '',
41 silly mapToRegistry   spec: 'latest',
41 silly mapToRegistry   type: 'tag' }
42 silly mapToRegistry uri https://registry.npmjs.org/angular-messages
43 silly fetchNamedPackageData angular-material
44 silly mapToRegistry name angular-material
45 silly mapToRegistry using default registry
46 silly mapToRegistry registry https://registry.npmjs.org/
47 silly mapToRegistry data Result {
47 silly mapToRegistry   raw: 'angular-material',
47 silly mapToRegistry   scope: null,
47 silly mapToRegistry   escapedName: 'angular-material',
47 silly mapToRegistry   name: 'angular-material',
47 silly mapToRegistry   rawSpec: '',
47 silly mapToRegistry   spec: 'latest',
47 silly mapToRegistry   type: 'tag' }
48 silly mapToRegistry uri https://registry.npmjs.org/angular-material
49 verbose request uri https://registry.npmjs.org/angular
50 verbose request no auth needed
51 info attempt registry request try #1 at 00:02:57
52 verbose request id 223db6c645d63eec
53 http request GET https://registry.npmjs.org/angular
54 verbose request uri https://registry.npmjs.org/angular-animate
55 verbose request no auth needed
56 info attempt registry request try #1 at 00:02:57
57 http request GET https://registry.npmjs.org/angular-animate
58 verbose request uri https://registry.npmjs.org/angular-aria
59 verbose request no auth needed
60 info attempt registry request try #1 at 00:02:57
61 http request GET https://registry.npmjs.org/angular-aria
62 verbose request uri https://registry.npmjs.org/angular-messages
63 verbose request no auth needed
64 info attempt registry request try #1 at 00:02:57
65 http request GET https://registry.npmjs.org/angular-messages
66 verbose request uri https://registry.npmjs.org/angular-material
67 verbose request no auth needed
68 info attempt registry request try #1 at 00:02:57
69 http request GET https://registry.npmjs.org/angular-material
70 info retry will retry, error on last attempt: Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
71 info retry will retry, error on last attempt: Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
72 info retry will retry, error on last attempt: Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
73 info retry will retry, error on last attempt: Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
74 info retry will retry, error on last attempt: Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
75 info attempt registry request try #2 at 00:03:07
76 http request GET https://registry.npmjs.org/angular
77 info attempt registry request try #2 at 00:03:07
78 http request GET https://registry.npmjs.org/angular-animate
79 info attempt registry request try #2 at 00:03:07
80 http request GET https://registry.npmjs.org/angular-aria
81 info attempt registry request try #2 at 00:03:07
82 http request GET https://registry.npmjs.org/angular-messages
83 info attempt registry request try #2 at 00:03:07
84 http request GET https://registry.npmjs.org/angular-material
85 info retry will retry, error on last attempt: Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
86 info retry will retry, error on last attempt: Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
87 info retry will retry, error on last attempt: Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
88 info retry will retry, error on last attempt: Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
89 info retry will retry, error on last attempt: Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
90 info attempt registry request try #3 at 00:04:07
91 http request GET https://registry.npmjs.org/angular
92 info attempt registry request try #3 at 00:04:07
93 http request GET https://registry.npmjs.org/angular-animate
94 info attempt registry request try #3 at 00:04:07
95 http request GET https://registry.npmjs.org/angular-aria
96 info attempt registry request try #3 at 00:04:07
97 http request GET https://registry.npmjs.org/angular-messages
98 info attempt registry request try #3 at 00:04:07
99 http request GET https://registry.npmjs.org/angular-material
100 silly fetchPackageMetaData Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
100 silly fetchPackageMetaData     at Object.createSecureContext (_tls_common.js:85:17)
100 silly fetchPackageMetaData     at Object.exports.connect (_tls_wrap.js:1025:48)
100 silly fetchPackageMetaData     at Agent.createConnection (https.js:83:22)
100 silly fetchPackageMetaData     at Agent.createSocket (_http_agent.js:195:26)
100 silly fetchPackageMetaData     at Agent.addRequest (_http_agent.js:157:10)
100 silly fetchPackageMetaData     at new ClientRequest (_http_client.js:212:16)
100 silly fetchPackageMetaData     at Object.request (http.js:26:10)
100 silly fetchPackageMetaData     at Object.request (https.js:206:15)
100 silly fetchPackageMetaData     at Request.start (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\request.js:744:32)
100 silly fetchPackageMetaData     at Request.end (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\request.js:1435:10)
100 silly fetchPackageMetaData  error for angular@^1.5.5 Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
100 silly fetchPackageMetaData     at Object.createSecureContext (_tls_common.js:85:17)
100 silly fetchPackageMetaData     at Object.exports.connect (_tls_wrap.js:1025:48)
100 silly fetchPackageMetaData     at Agent.createConnection (https.js:83:22)
100 silly fetchPackageMetaData     at Agent.createSocket (_http_agent.js:195:26)
100 silly fetchPackageMetaData     at Agent.addRequest (_http_agent.js:157:10)
100 silly fetchPackageMetaData     at new ClientRequest (_http_client.js:212:16)
100 silly fetchPackageMetaData     at Object.request (http.js:26:10)
100 silly fetchPackageMetaData     at Object.request (https.js:206:15)
100 silly fetchPackageMetaData     at Request.start (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\request.js:744:32)
100 silly fetchPackageMetaData     at Request.end (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\request.js:1435:10)
101 silly fetchPackageMetaData Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
101 silly fetchPackageMetaData     at Object.createSecureContext (_tls_common.js:85:17)
101 silly fetchPackageMetaData     at Object.exports.connect (_tls_wrap.js:1025:48)
101 silly fetchPackageMetaData     at Agent.createConnection (https.js:83:22)
101 silly fetchPackageMetaData     at Agent.createSocket (_http_agent.js:195:26)
101 silly fetchPackageMetaData     at Agent.addRequest (_http_agent.js:157:10)
101 silly fetchPackageMetaData     at new ClientRequest (_http_client.js:212:16)
101 silly fetchPackageMetaData     at Object.request (http.js:26:10)
101 silly fetchPackageMetaData     at Object.request (https.js:206:15)
101 silly fetchPackageMetaData     at Request.start (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\request.js:744:32)
101 silly fetchPackageMetaData     at Request.end (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\request.js:1435:10)
101 silly fetchPackageMetaData  error for angular-animate@^1.5.5 Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
101 silly fetchPackageMetaData     at Object.createSecureContext (_tls_common.js:85:17)
101 silly fetchPackageMetaData     at Object.exports.connect (_tls_wrap.js:1025:48)
101 silly fetchPackageMetaData     at Agent.createConnection (https.js:83:22)
101 silly fetchPackageMetaData     at Agent.createSocket (_http_agent.js:195:26)
101 silly fetchPackageMetaData     at Agent.addRequest (_http_agent.js:157:10)
101 silly fetchPackageMetaData     at new ClientRequest (_http_client.js:212:16)
101 silly fetchPackageMetaData     at Object.request (http.js:26:10)
101 silly fetchPackageMetaData     at Object.request (https.js:206:15)
101 silly fetchPackageMetaData     at Request.start (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\request.js:744:32)
101 silly fetchPackageMetaData     at Request.end (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\request.js:1435:10)
102 silly fetchPackageMetaData Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
102 silly fetchPackageMetaData     at Object.createSecureContext (_tls_common.js:85:17)
102 silly fetchPackageMetaData     at Object.exports.connect (_tls_wrap.js:1025:48)
102 silly fetchPackageMetaData     at Agent.createConnection (https.js:83:22)
102 silly fetchPackageMetaData     at Agent.createSocket (_http_agent.js:195:26)
102 silly fetchPackageMetaData     at Agent.addRequest (_http_agent.js:157:10)
102 silly fetchPackageMetaData     at new ClientRequest (_http_client.js:212:16)
102 silly fetchPackageMetaData     at Object.request (http.js:26:10)
102 silly fetchPackageMetaData     at Object.request (https.js:206:15)
102 silly fetchPackageMetaData     at Request.start (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\request.js:744:32)
102 silly fetchPackageMetaData     at Request.end (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\request.js:1435:10)
102 silly fetchPackageMetaData  error for angular-aria@^1.5.5 Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
102 silly fetchPackageMetaData     at Object.createSecureContext (_tls_common.js:85:17)
102 silly fetchPackageMetaData     at Object.exports.connect (_tls_wrap.js:1025:48)
102 silly fetchPackageMetaData     at Agent.createConnection (https.js:83:22)
102 silly fetchPackageMetaData     at Agent.createSocket (_http_agent.js:195:26)
102 silly fetchPackageMetaData     at Agent.addRequest (_http_agent.js:157:10)
102 silly fetchPackageMetaData     at new ClientRequest (_http_client.js:212:16)
102 silly fetchPackageMetaData     at Object.request (http.js:26:10)
102 silly fetchPackageMetaData     at Object.request (https.js:206:15)
102 silly fetchPackageMetaData     at Request.start (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\request.js:744:32)
102 silly fetchPackageMetaData     at Request.end (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\request.js:1435:10)
103 silly fetchPackageMetaData Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
103 silly fetchPackageMetaData     at Object.createSecureContext (_tls_common.js:85:17)
103 silly fetchPackageMetaData     at Object.exports.connect (_tls_wrap.js:1025:48)
103 silly fetchPackageMetaData     at Agent.createConnection (https.js:83:22)
103 silly fetchPackageMetaData     at Agent.createSocket (_http_agent.js:195:26)
103 silly fetchPackageMetaData     at Agent.addRequest (_http_agent.js:157:10)
103 silly fetchPackageMetaData     at new ClientRequest (_http_client.js:212:16)
103 silly fetchPackageMetaData     at Object.request (http.js:26:10)
103 silly fetchPackageMetaData     at Object.request (https.js:206:15)
103 silly fetchPackageMetaData     at Request.start (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\request.js:744:32)
103 silly fetchPackageMetaData     at Request.end (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\request.js:1435:10)
103 silly fetchPackageMetaData  error for angular-messages@^1.5.5 Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
103 silly fetchPackageMetaData     at Object.createSecureContext (_tls_common.js:85:17)
103 silly fetchPackageMetaData     at Object.exports.connect (_tls_wrap.js:1025:48)
103 silly fetchPackageMetaData     at Agent.createConnection (https.js:83:22)
103 silly fetchPackageMetaData     at Agent.createSocket (_http_agent.js:195:26)
103 silly fetchPackageMetaData     at Agent.addRequest (_http_agent.js:157:10)
103 silly fetchPackageMetaData     at new ClientRequest (_http_client.js:212:16)
103 silly fetchPackageMetaData     at Object.request (http.js:26:10)
103 silly fetchPackageMetaData     at Object.request (https.js:206:15)
103 silly fetchPackageMetaData     at Request.start (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\request.js:744:32)
103 silly fetchPackageMetaData     at Request.end (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\request.js:1435:10)
104 silly fetchPackageMetaData Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
104 silly fetchPackageMetaData     at Object.createSecureContext (_tls_common.js:85:17)
104 silly fetchPackageMetaData     at Object.exports.connect (_tls_wrap.js:1025:48)
104 silly fetchPackageMetaData     at Agent.createConnection (https.js:83:22)
104 silly fetchPackageMetaData     at Agent.createSocket (_http_agent.js:195:26)
104 silly fetchPackageMetaData     at Agent.addRequest (_http_agent.js:157:10)
104 silly fetchPackageMetaData     at new ClientRequest (_http_client.js:212:16)
104 silly fetchPackageMetaData     at Object.request (http.js:26:10)
104 silly fetchPackageMetaData     at Object.request (https.js:206:15)
104 silly fetchPackageMetaData     at Request.start (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\request.js:744:32)
104 silly fetchPackageMetaData     at Request.end (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\request.js:1435:10)
104 silly fetchPackageMetaData  error for angular-material@^1.1.0 Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
104 silly fetchPackageMetaData     at Object.createSecureContext (_tls_common.js:85:17)
104 silly fetchPackageMetaData     at Object.exports.connect (_tls_wrap.js:1025:48)
104 silly fetchPackageMetaData     at Agent.createConnection (https.js:83:22)
104 silly fetchPackageMetaData     at Agent.createSocket (_http_agent.js:195:26)
104 silly fetchPackageMetaData     at Agent.addRequest (_http_agent.js:157:10)
104 silly fetchPackageMetaData     at new ClientRequest (_http_client.js:212:16)
104 silly fetchPackageMetaData     at Object.request (http.js:26:10)
104 silly fetchPackageMetaData     at Object.request (https.js:206:15)
104 silly fetchPackageMetaData     at Request.start (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\request.js:744:32)
104 silly fetchPackageMetaData     at Request.end (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\request.js:1435:10)
105 silly rollbackFailedOptional Starting
106 silly rollbackFailedOptional Finishing
107 silly runTopLevelLifecycles Finishing
108 silly install printInstalled
109 verbose stack Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
109 verbose stack     at Object.createSecureContext (_tls_common.js:85:17)
109 verbose stack     at Object.exports.connect (_tls_wrap.js:1025:48)
109 verbose stack     at Agent.createConnection (https.js:83:22)
109 verbose stack     at Agent.createSocket (_http_agent.js:195:26)
109 verbose stack     at Agent.addRequest (_http_agent.js:157:10)
109 verbose stack     at new ClientRequest (_http_client.js:212:16)
109 verbose stack     at Object.request (http.js:26:10)
109 verbose stack     at Object.request (https.js:206:15)
109 verbose stack     at Request.start (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\request.js:744:32)
109 verbose stack     at Request.end (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\request.js:1435:10)
110 verbose cwd C:\Users\Utilisateur\app\material-start
111 error Windows_NT 6.1.7601
112 error argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
113 error node v7.7.2
114 error npm  v4.1.2
115 error error:0906D06C:PEM routines:PEM_read_bio:no start line
116 error If you need help, you may report this error at:
116 error     <https://github.com/npm/npm/issues>
117 verbose exit [ 1, true ]

**Comment by onigetoc** [comment]
On the Github node issue they tell me to create a issue here.
https://github.com/nodejs/node/issues/11820
