### ISSUE TITLE
Uncaught TypeError: Cannot read property 'prototype' of undefined at Object.inherits 

### ISSUE THREAD

**Issue by MeriemBo** [npm/npm#16045]
hello , I am a beginner at angular2 and I m facing this problem when I serve my angular-cli project : 

import {Component } from '@angular/core';
import { OnInit,Input} from '@angular/core';
import * as Odoo  from 'odoo-connect';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent implements OnInit{

  @Input() project_list;

  private host:string;
  private port:number;
  constructor(){
    this.host='demo';
    this.port=80;
  }
  ngOnInit(){
    let  project_list : Array<any> = [];
    const odoo = new Odoo({
      host: 'demo',
      port: 80
    });
    odoo.connect({
        database: 'DB',
        username: 'admin',
        password: 'admin'
      })
        .then((client:any) => {
          return client.call('project.project', 'search_read', [], {});
        })
        .then((projects:any) => {
          for (let i = 0; i < projects.length; i++) {
            let project = projects[i];
            project_list.push(project['name'])
          }
          console.log(project_list);
        })
  }}
 it gave me : webpack : compiled successfuly in my console , but in the browser's it gives me this ERROR and no projects are displayed : 

Uncaught TypeError: Cannot read property 'prototype' of undefined
    at Object.inherits (http://localhost:4200/vendor.bundle.js:193:45)
    at Object.<anonymous> (http://localhost:4200/vendor.bundle.js:102947:25)
    at __webpack_require__ (http://localhost:4200/inline.bundle.js:53:30)
    at Object.d.(anonymous function) (http://localhost:4200/vendor.bundle.js:34376:9)
    at __webpack_require__ (http://localhost:4200/inline.bundle.js:53:30)
    at Object.<anonymous> (http://localhost:4200/vendor.bundle.js:34101:14)
    at __webpack_require__ (http://localhost:4200/inline.bundle.js:53:30)
    at Object.VERSION (http://localhost:4200/vendor.bundle.js:47497:33)
    at __webpack_require__ (http://localhost:4200/inline.bundle.js:53:30)
    at Object.<anonymous> (http://localhost:4200/vendor.bundle.js:102577:18)
    at __webpack_require__ (http://localhost:4200/inline.bundle.js:53:30)
    at Object.<anonymous> (http://localhost:4200/vendor.bundle.js:104315:16)
    at __webpack_require__ (http://localhost:4200/inline.bundle.js:53:30)
    at Object.<anonymous> (http://localhost:4200/vendor.bundle.js:104167:17)
    at __webpack_require__ (http://localhost:4200/inline.bundle.js:53:30)

**Comment by legodude17** [comment]
How is this a problem with `npm`?
