### ISSUE TITLE
Error running npm shrinkwrap

### ISSUE THREAD

**Issue by suamikim** [npm/npm#16057]
#### I'm opening this issue because:

  - [x ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

Running `npm shrinkwrap` in my project results in an error and doesn't produce any output.
My application is using the Aurelia.io framework and I've already created [an issue in their repo](https://github.com/aurelia/framework/issues/738).

#### How can the CLI team reproduce the problem?

Unfortunately I'm not able to create a bare bone environment right now which reproduces the issue. Nonetheless here's the `npm-debug.log`:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Michael\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'shrinkwrap' ]
2 info using npm@4.1.1
3 info using node@v6.9.4
4 info lifecycle myproject@0.1.0~preshrinkwrap: myproject@0.1.0
5 silly lifecycle myproject@0.1.0~preshrinkwrap: no script for preshrinkwrap, continuing
6 info lifecycle myproject@0.1.0~shrinkwrap: myproject@0.1.0
7 silly lifecycle myproject@0.1.0~shrinkwrap: no script for shrinkwrap, continuing
8 verbose stack Error: Problems were encountered
8 verbose stack Please correct and try again.
8 verbose stack extraneous: aurelia-binding-loader@1.1.0 D:\dev\MyProject\node_modules\aurelia-binding-loader
8 verbose stack     at shrinkwrap_ (C:\Users\Michael\AppData\Roaming\npm\node_modules\npm\lib\shrinkwrap.js:128:15)
8 verbose stack     at Array.<anonymous> (C:\Users\Michael\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
8 verbose stack     at LOOP (C:\Users\Michael\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
8 verbose stack     at C:\Users\Michael\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:18:7
8 verbose stack     at done (C:\Users\Michael\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:132:5)
8 verbose stack     at LOOP (C:\Users\Michael\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:7:26)
8 verbose stack     at C:\Users\Michael\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:18:7
8 verbose stack     at C:\Users\Michael\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:318:20
8 verbose stack     at C:\Users\Michael\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
8 verbose stack     at FSReqWrap.oncomplete (fs.js:123:15)
9 verbose cwd D:\dev\MyProject
10 error Windows_NT 10.0.14393
11 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Michael\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "shrinkwrap"
12 error node v6.9.4
13 error npm  v4.1.1
14 error Problems were encountered
14 error Please correct and try again.
14 error extraneous: aurelia-binding-loader@1.1.0 D:\dev\MyProject\node_modules\aurelia-binding-loader
15 error If you need help, you may report this error at:
15 error     <https://github.com/npm/npm/issues>
16 verbose exit [ 1, true ]
```

### supporting information:

 - `npm -v` prints: `4.1.1`
 - `node -v` prints: `v6.9.4`
 - `npm config get registry` prints: `https://registry.npmjs.org/`
 - Windows, OS X/macOS, or Linux?: `Windows 10`
 - Network issues: None of the bellow (deleted for clearer report)

**Comment by legodude17** [comment]
Try running `npm prune`.

**Comment by suamikim** [comment]
Perfect, that fixed it for me!
