### ISSUE TITLE
Error: Cannot find module 'bl' 

### ISSUE THREAD

**Issue by aswathy072** [npm/npm#16070]
How can i solve this issue.
i am using netbeans 8.2 and my node version is 6.2.2

Error: Cannot find module 'bl'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\hp\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.js:9:10)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\hp\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run-script" "ng"
npm ERR! node v6.2.2
npm ERR! npm  v3.10.8
npm ERR! code MODULE_NOT_FOUND

**Comment by chakrihacker** [comment]
Firstly try `npm list` and look whether **_bl_** module is listed
if module is not installed try `npm install`
else remove **_bl_** module dir from **node_modules** folder and reinstall it

**Comment by santosgabriel** [comment]
As @chakrihacker said, removing the module bl from node_modules and reinstalling it worked for me.
