### ISSUE TITLE
[recast.ai] TypeError: Cannot read property 'latest' of undefined

### ISSUE THREAD

**Issue by quoidautre** [npm/npm#16106]
#### I'm opening this issue because:

  - [X ] npm is producing an incorrect install.
  - [X ] npm is doing something I don't understand.

#### What's going wrong?
When I'm do a "npm install", in a "recast" bot (https://github.com/RecastAI/bot-slack.git)

### supporting information:
 - `npm -v` prints: 1.3.10
 - `node -v` prints: print blank, nothing
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Ubuntu 16.04

 - Container:
   - [X ] I develop using Vagrant on OS X or Linux.

#### What's the feature?
A bot using Recast.ai

I've done all this things trying to solve the problem
```
$ mv /usr/local/lib/node_modules/npm/package.json /usr/local/lib/node_modules/npm/package.json.bak
$ npm cache clean && npm install npm -g && npm update npm@latest
$ sudo chown -R $USER: /usr/local
$ sudo chown -R $(whoami) ~/.npm
$ sudo apt-get install node
```

Can you help me ? Thanks

Regards

Fabrice

**Comment by KenanY** [comment]
@quoidautre So, `npm -v` is still 1.3 even after running `npm install -g npm`?

**Comment by quoidautre** [comment]
Hi,
Yes, still in 1.3.10.

**Comment by legodude17** [comment]
So what happens when you run `npm install -g npm@latest`.

**Comment by quoidautre** [comment]
Hi,
That : 
```
$ npm install -g npm@latest
npm http GET https://registry.npmjs.org/npm
npm http 304 https://registry.npmjs.org/npm
/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
npm@4.4.1 /usr/local/lib/node_modules/npm
```
And, when I do a npm install : 

```
$ npm install
npm WARN package.json @1.0.0 No repository field.
npm http GET https://registry.npmjs.org/babel-eslint
npm http GET https://registry.npmjs.org/slack/client
npm http GET https://registry.npmjs.org/babel-preset-es2015
npm http GET https://registry.npmjs.org/babel-preset-stage-0
npm http GET https://registry.npmjs.org/babel-register
npm http GET https://registry.npmjs.org/babel-cli
npm http GET https://registry.npmjs.org/recastai
npm http GET https://registry.npmjs.org/request-promise
npm http 200 https://registry.npmjs.org/babel-preset-stage-0
npm http GET https://registry.npmjs.org/babel-preset-stage-0/-/babel-preset-stage-0-6.22.0.tgz
npm http 200 https://registry.npmjs.org/babel-register
npm http GET https://registry.npmjs.org/babel-register/-/babel-register-6.24.0.tgz
npm http 404 https://registry.npmjs.org/slack/client
npm ERR! TypeError: Cannot read property 'latest' of undefined
npm ERR!     at next (/usr/share/npm/lib/cache.js:687:35)
npm ERR!     at /usr/share/npm/lib/cache.js:675:5
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-100-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /var/www/recast.ai-bots/bot-slack
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! type non_object_property_load
npm http 200 https://registry.npmjs.org/babel-preset-es2015
npm http GET https://registry.npmjs.org/babel-preset-es2015/-/babel-preset-es2015-6.24.0.tgz
npm http 200 https://registry.npmjs.org/babel-eslint
npm http GET https://registry.npmjs.org/babel-eslint/-/babel-eslint-6.1.2.tgz
npm http 200 https://registry.npmjs.org/babel-cli
npm http GET https://registry.npmjs.org/babel-cli/-/babel-cli-6.24.0.tgz
npm http 200 https://registry.npmjs.org/babel-preset-stage-0/-/babel-preset-stage-0-6.22.0.tgz
npm http 200 https://registry.npmjs.org/request-promise
npm http 200 https://registry.npmjs.org/babel-register/-/babel-register-6.24.0.tgz
npm http GET https://registry.npmjs.org/request-promise/-/request-promise-4.2.0.tgz
npm http 200 https://registry.npmjs.org/recastai
npm http GET https://registry.npmjs.org/recastai/-/recastai-2.3.0.tgz
npm http 200 https://registry.npmjs.org/babel-preset-es2015/-/babel-preset-es2015-6.24.0.tgz
npm http 200 https://registry.npmjs.org/babel-eslint/-/babel-eslint-6.1.2.tgz
npm http 200 https://registry.npmjs.org/babel-cli/-/babel-cli-6.24.0.tgz
npm http 200 https://registry.npmjs.org/request-promise/-/request-promise-4.2.0.tgz
npm http 200 https://registry.npmjs.org/recastai/-/recastai-2.3.0.tgz
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /var/www/recast.ai-bots/bot-slack/npm-debug.log
npm ERR! not ok code 0
```

Fabrice

**Comment by legodude17** [comment]
What is `echo $PATH` and `npm prefix -g`?

**Comment by quoidautre** [comment]
here : 
```
$ echo $PATH
/usr/local/rvm/gems/ruby-1.9.3-p551/bin:/usr/local/rvm/gems/ruby-1.9.3-p551@global/bin:/usr/local/rvm/rubies/ruby-1.9.3-p551/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/opt/puppetlabs/bin:/usr/local/rvm/bin:/home/vagrant/bin
```
and
```
$ npm prefix -g
/usr/local
```

**Comment by KenanY** [comment]
I think you have two installations of `npm`. One at `/usr/local/lib/node_modules/npm` and another at `/usr/bin/npm`.

**Comment by quoidautre** [comment]
Yes, but when I execute npm, the two npm, something strange appears :)  : 
```
$ /usr/bin/npm -v
1.3.10

$ /usr/local/lib/node_modules/npm/bin/npm -v


```
The second command return nothing. So I just remove all the package and re-install ?

Thanks
Fabrice

**Comment by KenanY** [comment]
@quoidautre What about `/usr/local/bin/npm -v`?

**Comment by quoidautre** [comment]
Return nothing : 
```
$ ll /usr/local/bin/npm
lrwxrwxrwx 1 vagrant vagrant 38 mars  20 19:11 /usr/local/bin/npm -> ../lib/node_modules/npm/bin/npm-cli.js*

$ /usr/local/bin/npm -v


```
Fabrice

**Comment by quoidautre** [comment]
Hi,
So, I resolved the situation.

I remove all node, nodejs, npm.
And reinstall. It's work :)

Thanks.
Fabrice
