### ISSUE TITLE
Error while installing moment with: npm install koa-joi-router --save

### ISSUE THREAD

**Issue by loserdong** [npm/npm#16125]
#### I'm opening this issue because:

  - [x] npm is producing an incorrect install.

#### What's going wrong?

run `npm install koa-joi-router --save`

```
npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "i" "koa-joi-router" "-g"
npm ERR! node v7.7.4
npm ERR! npm  v4.1.2

npm ERR! Bad argument
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/dw/Workspace/me/blog/npm-debug.log
```

**Comment by loserdong** [comment]
verbose error


```
npm http request GET http://registry.npmjs.org/flatten
npm info git [ 'config', '--get', 'remote.origin.url' ]
npm verb stack TypeError: Bad argument
npm verb stack     at ChildProcess.spawn (internal/child_process.js:289:26)
npm verb stack     at exports.spawn (child_process.js:387:9)
npm verb stack     at exports.execFile (child_process.js:148:15)
npm verb stack     at execGit (/usr/local/lib/node_modules/npm/lib/utils/git.js:23:10)
npm verb stack     at /usr/local/lib/node_modules/npm/lib/utils/git.js:45:5
npm verb stack     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:87:20
npm verb stack     at /usr/local/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
npm verb stack     at /usr/local/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
npm verb stack     at FSReqWrap.oncomplete (fs.js:114:15)
npm verb cwd /Users/dw/Workspace/me/blog
npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "i" "koa-joi-router" "--verbose"
npm ERR! node v7.6.0
npm ERR! npm  v4.1.2

npm ERR! Bad argument
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm verb exit [ 1, true ]
```

**Comment by loserdong** [comment]
resolve

in my .npmrc
 
```
git=
registry=http://registry.npmjs.org
```

I remove `git=`, it's ok
