### ISSUE TITLE
npm error in  heroku

### ISSUE THREAD

**Issue by Muthukumars1994** [npm/npm#16166]
#### I'm opening this issue because:
 - [x] npm is doing something I don't understand.
---> heroku logs 
2017-03-27T15:02:10.143986+00:00 app[web.1]: npm ERR!     /app/npm-debug.log
2017-03-27T15:02:10.274199+00:00 heroku[web.1]: State changed from starting to c
rashed
2017-03-27T15:02:10.261535+00:00 heroku[web.1]: Process exited with status 1
2017-03-27T15:04:03.512990+00:00 heroku[web.1]: State changed from crashed to st
arting
2017-03-27T15:04:03.376857+00:00 app[api]: Release v5 created by user muthukumar
.cits@gmail.com
2017-03-27T15:04:03.219423+00:00 app[api]: Set NODE_ENV config vars by user muth
ukumar.cits@gmail.com
2017-03-27T15:04:03.219423+00:00 app[api]: Release v5 created by user muthukumar
.cits@gmail.com
2017-03-27T15:04:04.850493+00:00 heroku[web.1]: Starting process with command `n
pm start`
2017-03-27T15:04:07.741763+00:00 heroku[web.1]: Process exited with status 1
2017-03-27T15:04:07.585459+00:00 app[web.1]:
2017-03-27T15:04:07.585474+00:00 app[web.1]: > todo@0.0.0 start /app
2017-03-27T15:04:07.585475+00:00 app[web.1]: > node ./bin/www
2017-03-27T15:04:07.585475+00:00 app[web.1]:
2017-03-27T15:04:07.654517+00:00 app[web.1]: module.js:471
2017-03-27T15:04:07.654520+00:00 app[web.1]:     throw err;
2017-03-27T15:04:07.654521+00:00 app[web.1]:     ^
2017-03-27T15:04:07.654521+00:00 app[web.1]:
2017-03-27T15:04:07.654522+00:00 app[web.1]: Error: Cannot find module 'mongoose
'
2017-03-27T15:04:07.654523+00:00 app[web.1]:     at Function.Module._resolveFile
name (module.js:469:15)
2017-03-27T15:04:07.654524+00:00 app[web.1]:     at Function.Module._load (modul
e.js:417:25)
2017-03-27T15:04:07.654524+00:00 app[web.1]:     at Module.require (module.js:49
7:17)
2017-03-27T15:04:07.654525+00:00 app[web.1]:     at require (internal/module.js:
20:19)
2017-03-27T15:04:07.654526+00:00 app[web.1]:     at Object.<anonymous> (/app/db.
js:1:78)
2017-03-27T15:04:07.654526+00:00 app[web.1]:     at Module._compile (module.js:5
70:32)
2017-03-27T15:04:07.654527+00:00 app[web.1]:     at Object.Module._extensions..j
s (module.js:579:10)
2017-03-27T15:04:07.654527+00:00 app[web.1]:     at Module.load (module.js:487:3
2)
2017-03-27T15:04:07.654528+00:00 app[web.1]:     at tryModuleLoad (module.js:446
:12)
2017-03-27T15:04:07.661900+00:00 app[web.1]:
2017-03-27T15:04:07.654528+00:00 app[web.1]:     at Function.Module._load (modul
e.js:438:3)
2017-03-27T15:04:07.669171+00:00 app[web.1]: npm ERR! Linux 3.13.0-112-generic
2017-03-27T15:04:07.669457+00:00 app[web.1]: npm ERR! argv "/app/.heroku/node/bi
n/node" "/app/.heroku/node/bin/npm" "start"
2017-03-27T15:04:07.669977+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2017-03-27T15:04:07.669617+00:00 app[web.1]: npm ERR! node v6.10.1
2017-03-27T15:04:07.669748+00:00 app[web.1]: npm ERR! npm  v3.10.10
2017-03-27T15:04:07.670093+00:00 app[web.1]: npm ERR! todo@0.0.0 start: `node ./
bin/www`
2017-03-27T15:04:07.670176+00:00 app[web.1]: npm ERR! Exit status 1
2017-03-27T15:04:07.670376+00:00 app[web.1]: npm ERR! Failed at the todo@0.0.0 s
tart script 'node ./bin/www'.
2017-03-27T15:04:07.670293+00:00 app[web.1]: npm ERR!
2017-03-27T15:04:07.670505+00:00 app[web.1]: npm ERR! Make sure you have the lat
est version of node.js and npm installed.
2017-03-27T15:04:07.670629+00:00 app[web.1]: npm ERR! If you do, this is most li
kely a problem with the todo package,
2017-03-27T15:04:07.670766+00:00 app[web.1]: npm ERR! not with npm itself.
2017-03-27T15:04:07.671018+00:00 app[web.1]: npm ERR! Tell the author that this
fails on your system:
2017-03-27T15:04:07.671214+00:00 app[web.1]: npm ERR!     node ./bin/www
2017-03-27T15:04:07.671356+00:00 app[web.1]: npm ERR! You can get information on
 how to open an issue for this project with:
2017-03-27T15:04:07.671492+00:00 app[web.1]: npm ERR!     npm bugs todo
2017-03-27T15:04:07.671623+00:00 app[web.1]: npm ERR! Or if that isn't available
, you can get their info via:
2017-03-27T15:04:07.671783+00:00 app[web.1]: npm ERR!     npm owner ls todo
2017-03-27T15:04:07.671917+00:00 app[web.1]: npm ERR! There is likely additional
 logging output above.
2017-03-27T15:04:07.675224+00:00 app[web.1]:
2017-03-27T15:04:07.675433+00:00 app[web.1]: npm ERR! Please include the followi
ng file with any support request:
2017-03-27T15:04:07.675549+00:00 app[web.1]: npm ERR!     /app/npm-debug.log
2017-03-27T15:04:07.754511+00:00 heroku[web.1]: State changed from starting to c
rashed
2017-03-27T15:04:37.135125+00:00 heroku[web.1]: State changed from crashed to st
arting
2017-03-27T15:04:36.877502+00:00 app[api]: Set NODE_MODULES_CACHE config vars by
 user muthukumar.cits@gmail.com
2017-03-27T15:04:36.877502+00:00 app[api]: Release v6 created by user muthukumar
.cits@gmail.com
2017-03-27T15:04:37.073838+00:00 app[api]: Release v6 created by user muthukumar
.cits@gmail.com
2017-03-27T15:04:39.566747+00:00 heroku[web.1]: Starting process with command `n
pm start`
2017-03-27T15:04:42.772871+00:00 heroku[web.1]: Process exited with status 1
2017-03-27T15:04:42.543296+00:00 app[web.1]: > todo@0.0.0 start /app
2017-03-27T15:04:42.543297+00:00 app[web.1]: > node ./bin/www
2017-03-27T15:04:42.654156+00:00 app[web.1]: module.js:471
2017-03-27T15:04:42.543277+00:00 app[web.1]:
2017-03-27T15:04:42.543298+00:00 app[web.1]:
2017-03-27T15:04:42.654158+00:00 app[web.1]:     throw err;
2017-03-27T15:04:42.654159+00:00 app[web.1]:     ^
2017-03-27T15:04:42.654160+00:00 app[web.1]: Error: Cannot find module 'mongoose
'
2017-03-27T15:04:42.654161+00:00 app[web.1]:     at Function.Module._resolveFile
name (module.js:469:15)
2017-03-27T15:04:42.654162+00:00 app[web.1]:     at Function.Module._load (modul
e.js:417:25)
2017-03-27T15:04:42.654159+00:00 app[web.1]:
2017-03-27T15:04:42.654162+00:00 app[web.1]:     at Module.require (module.js:49
7:17)
2017-03-27T15:04:42.654163+00:00 app[web.1]:     at require (internal/module.js:
20:19)
2017-03-27T15:04:42.654163+00:00 app[web.1]:     at Object.<anonymous> (/app/db.
js:1:78)
2017-03-27T15:04:42.654164+00:00 app[web.1]:     at Module._compile (module.js:5
70:32)
2017-03-27T15:04:42.654165+00:00 app[web.1]:     at Module.load (module.js:487:3
2)
2017-03-27T15:04:42.654164+00:00 app[web.1]:     at Object.Module._extensions..j
s (module.js:579:10)
2017-03-27T15:04:42.654166+00:00 app[web.1]:     at tryModuleLoad (module.js:446
:12)
2017-03-27T15:04:42.654166+00:00 app[web.1]:     at Function.Module._load (modul
e.js:438:3)
**
Package.json 
{
  "name": "Express-todo",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "start": "node ./bin/www"
  },
  "dependencies": {
    "body-parser":   "~1.16.0",
    "cookie-parser": "~1.4.3",
    "debug":         "~2.6.0",
    "ejs":           "~2.5.5",
    "express":       "~4.14.1",
    "morgan":         "~1.7.0",
     "mongoose":      "~4.9.2",
    "serve-favicon":  "~2.3.2"
  }
}**

**Comment by legodude17** [comment]
Does `node ./ bin/www` succeed?

**Comment by Muthukumars1994** [comment]
no @legodude17

**Comment by legodude17** [comment]
Then it is a problem with that script instead of `npm`.

**Comment by Muthukumars1994** [comment]
fine @legodude17  ill check it out and let you know
