### ISSUE TITLE
npm publish Failed PUT 500 

### ISSUE THREAD

**Issue by kuyoonjo** [npm/npm#16162]
```
MacBook-Pro:dist yuchen$ npm publish
npm ERR! publish Failed PUT 500
npm ERR! Darwin 16.4.0
npm ERR! argv "/Users/yuchen/.nvm/versions/node/v7.7.2/bin/node" "/Users/yuchen/.nvm/versions/node/v7.7.2/bin/npm" "publish"
npm ERR! node v7.7.2
npm ERR! npm  v4.1.2
npm ERR! code E500

npm ERR! Registry returned 500 for PUT on https://registry.npmjs.org/@ycjs%2fcore
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/yuchen/Projects/ycjs/core/dist/npm-debug.log
```

```
MacBook-Pro:dist yuchen$ cat npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/Users/yuchen/.nvm/versions/node/v7.7.2/bin/node',
1 verbose cli   '/Users/yuchen/.nvm/versions/node/v7.7.2/bin/npm',
1 verbose cli   'publish' ]
2 info using npm@4.1.2
3 info using node@v7.7.2
4 verbose publish [ '.' ]
5 silly cache add args [ '.', null ]
6 verbose cache add spec .
7 silly cache add parsed spec Result {
7 silly cache add   raw: '.',
7 silly cache add   scope: null,
7 silly cache add   escapedName: null,
7 silly cache add   name: null,
7 silly cache add   rawSpec: '.',
7 silly cache add   spec: '/Users/yuchen/Projects/ycjs/core/dist',
7 silly cache add   type: 'directory' }
8 verbose addLocalDirectory /Users/yuchen/.npm/@ycjs/core/1.0.0/package.tgz not in flight; packing
9 verbose correctMkdir /Users/yuchen/.npm correctMkdir not in flight; initializing
10 info lifecycle @ycjs/core@1.0.0~prepublish: @ycjs/core@1.0.0
11 silly lifecycle @ycjs/core@1.0.0~prepublish: no script for prepublish, continuing
12 info lifecycle @ycjs/core@1.0.0~prepare: @ycjs/core@1.0.0
13 silly lifecycle @ycjs/core@1.0.0~prepare: no script for prepare, continuing
14 verbose tar pack [ '/Users/yuchen/.npm/@ycjs/core/1.0.0/package.tgz',
14 verbose tar pack   '/Users/yuchen/Projects/ycjs/core/dist' ]
15 verbose tarball /Users/yuchen/.npm/@ycjs/core/1.0.0/package.tgz
16 verbose folder /Users/yuchen/Projects/ycjs/core/dist
17 verbose addLocalTarball adding from inside cache /Users/yuchen/.npm/@ycjs/core/1.0.0/package.tgz
18 verbose correctMkdir /Users/yuchen/.npm correctMkdir not in flight; initializing
19 silly cache afterAdd @ycjs/core@1.0.0
20 verbose afterAdd /Users/yuchen/.npm/@ycjs/core/1.0.0/package/package.json not in flight; writing
21 verbose correctMkdir /Users/yuchen/.npm correctMkdir not in flight; initializing
22 verbose afterAdd /Users/yuchen/.npm/@ycjs/core/1.0.0/package/package.json written
23 silly publish { name: '@ycjs/core',
23 silly publish   version: '1.0.0',
23 silly publish   description: '[![Build Status](https://travis-ci.org/kuyoonjo/ycjs-core.svg?branch=master)](https://travis-ci.org/kuyoonjo/ycjs-core) [![codecov](https://codecov.io/gh/kuyoonjo/ycjs-core/branch/master/graph/badge.svg)](https://codecov.io/gh/kuyoonjo/ycjs-core) [![npm version](https://badge.fury.io/js/@ycjs/core.svg)](http://badge.fury.io/js/@ycjs/core) [![devDependency Status](https://david-dm.org/kuyoonjo/ycjs-core/dev-status.svg)](https://david-dm.org/kuyoonjo/ycjs-core?type=dev) [![GitHub issues](https://img.shields.io/github/issues/kuyoonjo/ycjs-core.svg)](https://github.com/kuyoonjo/ycjs-core/issues) [![GitHub stars](https://img.shields.io/github/stars/kuyoonjo/ycjs-core.svg)](https://github.com/kuyoonjo/ycjs-core/stargazers) [![GitHub license](https://img.shields.io/badge/license-MIT-blue.svg)](https://raw.githubusercontent.com/kuyoonjo/ycjs-core/master/LICENSE)',
23 silly publish   main: './bundles/@ycjs/core.umd.js',
23 silly publish   module: './index.js',
23 silly publish   typings: './index.d.ts',
23 silly publish   scripts:
23 silly publish    { start: 'concurrently --raw "webpack-dev-server --open" "npm run test:watch"',
23 silly publish      'build:demo': 'webpack -p',
23 silly publish      'build:umd': 'webpack --config webpack.config.umd.ts',
23 silly publish      'build:ngc': 'ngc -p tsconfig-ngc.json',
23 silly publish      'build:dist': 'npm run build:umd && npm run build:ngc',
23 silly publish      'build:clean': 'rm -rf dist',
23 silly publish      test: 'karma start --single-run',
23 silly publish      'test:watch': 'karma start --auto-watch',
23 silly publish      commit: 'git-cz',
23 silly publish      changelog: 'conventional-changelog -p angular -i CHANGELOG.md -s',
23 silly publish      compodoc: 'compodoc -p tsconfig-compodoc.json -d docs -b /ycjs-core/docs/ --disableGraph --disableCoverage --disablePrivateOrInternalSupport',
23 silly publish      'gh-pages': 'git checkout gh-pages && git merge master --no-edit --no-ff && npm run build:demo && npm run compodoc && git add . && git commit -m \'chore: build demo and docs\' && git push && git checkout master',
23 silly publish      copyfiles: 'cp package.json LICENSE README.md CHANGELOG.md dist/',
23 silly publish      prerelease: 'npm test',
23 silly publish      'release:git': 'git add package.json && git commit -m \'chore: bump version number\' && standard-version --first-release && git push --follow-tags origin master',
23 silly publish      'release:npm': 'npm run build:dist && npm run copyfiles && cd dist/;npm publish',
23 silly publish      release: 'npm run release:git && npm run release:npm',
23 silly publish      postrelease: 'npm run build:clean && npm run gh-pages',
23 silly publish      commitmsg: 'validate-commit-msg',
23 silly publish      codecov: 'cat coverage/lcov.info | codecov' },
23 silly publish   repository:
23 silly publish    { type: 'git',
23 silly publish      url: 'git+https://github.com/kuyoonjo/ycjs-core.git' },
23 silly publish   keywords: [ 'angular2', 'angular' ],
23 silly publish   author: { name: 'Yu Chen' },
23 silly publish   license: 'MIT',
23 silly publish   bugs: { url: 'https://github.com/kuyoonjo/ycjs-core/issues' },
23 silly publish   homepage: 'https://github.com/kuyoonjo/ycjs-core#readme',
23 silly publish   devDependencies:
23 silly publish    { '@angular/common': '^2.1.0',
23 silly publish      '@angular/compiler': '^2.1.0',
23 silly publish      '@angular/compiler-cli': '^2.1.0',
23 silly publish      '@angular/core': '^2.1.0',
23 silly publish      '@angular/platform-browser': '^2.1.0',
23 silly publish      '@angular/platform-browser-dynamic': '^2.1.0',
23 silly publish      '@types/chai': '^3.4.30',
23 silly publish      '@types/core-js': '^0.9.32',
23 silly publish      '@types/jasmine': '2.2.33',
23 silly publish      '@types/node': '^7.0.0',
23 silly publish      '@types/sinon': '^1.16.27',
23 silly publish      '@types/sinon-chai': '^2.7.26',
23 silly publish      '@types/webpack': '^2.2.0',
23 silly publish      'awesome-typescript-loader': '^3.0.8',
23 silly publish      chai: '^3.5.0',
23 silly publish      'codecov-lite': '^0.1.3',
23 silly publish      codelyzer: '^2.0.0',
23 silly publish      commitizen: '^2.8.1',
23 silly publish      compodoc: '^0.0.41',
23 silly publish      concurrently: '^3.0.0',
23 silly publish      'conventional-changelog': '^1.1.0',
23 silly publish      'conventional-changelog-cli': '^1.2.0',
23 silly publish      'core-js': '^2.4.1',
23 silly publish      'cz-conventional-changelog': '^2.0.0',
23 silly publish      husky: '^0.13.0',
23 silly publish      'imports-loader': '^0.7.0',
23 silly publish      'istanbul-instrumenter-loader': '^2.0.0',
23 silly publish      'jasmine-core': '^2.5.0',
23 silly publish      karma: '^1.4.1',
23 silly publish      'karma-coverage-istanbul-reporter': '^0.3.0',
23 silly publish      'karma-jasmine': '^1.0.2',
23 silly publish      'karma-phantomjs-launcher': '^1.0.0',
23 silly publish      'karma-sourcemap-loader': '^0.3.7',
23 silly publish      'karma-webpack': '^2.0.1',
23 silly publish      'phantomjs-prebuilt': '^2.1.7',
23 silly publish      rxjs: '^5.0.1',
23 silly publish      sinon: '^1.17.4',
23 silly publish      'sinon-chai': '^2.8.0',
23 silly publish      'standard-version': '^4.0.0',
23 silly publish      'ts-node': '^2.0.0',
23 silly publish      tslint: '^4.0.2',
23 silly publish      'tslint-loader': '^3.3.0',
23 silly publish      typescript: '~2.0.3',
23 silly publish      'validate-commit-msg': '^2.8.0',
23 silly publish      webpack: '^2.2.0',
23 silly publish      'webpack-angular-externals': '^1.0.0',
23 silly publish      'webpack-dev-server': '^2.2.0',
23 silly publish      'webpack-rxjs-externals': '^1.0.0',
23 silly publish      'zone.js': '^0.7.4' },
23 silly publish   peerDependencies: { '@angular/core': '^2.0.0' },
23 silly publish   config: { commitizen: { path: 'node_modules/cz-conventional-changelog' } },
23 silly publish   readme: '# core\n[![Build Status](https://travis-ci.org/kuyoonjo/ycjs-core.svg?branch=master)](https://travis-ci.org/kuyoonjo/ycjs-core)\n[![codecov](https://codecov.io/gh/kuyoonjo/ycjs-core/branch/master/graph/badge.svg)](https://codecov.io/gh/kuyoonjo/ycjs-core)\n[![npm version](https://badge.fury.io/js/@ycjs/core.svg)](http://badge.fury.io/js/@ycjs/core)\n[![devDependency Status](https://david-dm.org/kuyoonjo/ycjs-core/dev-status.svg)](https://david-dm.org/kuyoonjo/ycjs-core?type=dev)\n[![GitHub issues](https://img.shields.io/github/issues/kuyoonjo/ycjs-core.svg)](https://github.com/kuyoonjo/ycjs-core/issues)\n[![GitHub stars](https://img.shields.io/github/stars/kuyoonjo/ycjs-core.svg)](https://github.com/kuyoonjo/ycjs-core/stargazers)\n[![GitHub license](https://img.shields.io/badge/license-MIT-blue.svg)](https://raw.githubusercontent.com/kuyoonjo/ycjs-core/master/LICENSE)\n\n\n## Table of contents\n\n- [About](#about)\n- [Installation](#installation)\n- [Documentation](#documentation)\n- [Development](#development)\n- [License](#license)\n\n## About\n\n\n\n## Installation\n\nInstall through npm:\n```\nnpm install --save @ycjs/core\n```\n\nInstall through yarn:\n```\nyarn add @ycjs/core\n```\n\nThen include in your apps module:\n\n```typescript\nimport { Component, NgModule } from \'@angular/core\';\nimport { YcjsAPIModule } from \'@ycjs/core\';\n\nconst apiRoot: string = \'http://www.example.com\';\n\n@NgModule({\n  imports: [\n    YcjsAPIModule.forRoot(apiRoot)\n  ]\n})\nexport class MyModule {}\n```\n\nFinally use in one of your apps components:\n```typescript\nimport { Component } from \'@angular/core\';\nimport { YcjsAPI, YcjsRequest } from \'@ycjs/core\';\n\n@Component({\n  template: \'<hello-world></hello-world>\'\n})\nexport class MyComponent {\n  constructor(public api: YcjsAPI) { }\n\n  loadData(): Promise<any> {\n    return YcjsRequest(\'GET\', `${api.root}/api/examples`);\n  }\n}\n```\n\n### Usage without a module bundler\n```\n<script src="node_modules/@ycjs/core/bundles/@ycjs/core.umd.js"></script>\n<script>\n    // everything is exported ycjsCore namespace\n</script>\n```\n\n## Documentation\nAll documentation is auto-generated from the source via [compodoc](https://compodoc.github.io/compodoc/) and can be viewed here:\nhttps://kuyoonjo.github.io/ycjs-core/docs/\n\n## License\n\nMIT\n',
23 silly publish   readmeFilename: 'README.md',
23 silly publish   _id: '@ycjs/core@1.0.0',
23 silly publish   _shasum: '211717ff93c8138d184225f03afe36aca001ae90',
23 silly publish   _from: '.' }
24 info lifecycle @ycjs/core@1.0.0~prepublishOnly: @ycjs/core@1.0.0
25 silly lifecycle @ycjs/core@1.0.0~prepublishOnly: no script for prepublishOnly, continuing
26 verbose getPublishConfig undefined
27 silly mapToRegistry name @ycjs/core
28 silly mapToRegistry scope (from package name) @ycjs
29 verbose mapToRegistry no registry URL found in name for scope @ycjs
30 silly mapToRegistry using default registry
31 silly mapToRegistry registry https://registry.npmjs.org/
32 silly mapToRegistry data Result {
32 silly mapToRegistry   raw: '@ycjs/core',
32 silly mapToRegistry   scope: '@ycjs',
32 silly mapToRegistry   escapedName: '@ycjs%2fcore',
32 silly mapToRegistry   name: '@ycjs/core',
32 silly mapToRegistry   rawSpec: '',
32 silly mapToRegistry   spec: 'latest',
32 silly mapToRegistry   type: 'tag' }
33 silly mapToRegistry uri https://registry.npmjs.org/@ycjs%2fcore
34 verbose publish registryBase https://registry.npmjs.org/
35 silly publish uploading /Users/yuchen/.npm/@ycjs/core/1.0.0/package.tgz
36 verbose request uri https://registry.npmjs.org/@ycjs%2fcore
37 verbose request sending authorization for write operation
38 info attempt registry request try #1 at 6:45:11 PM
39 verbose request using bearer token for auth
40 verbose request id 31e58530853660bd
41 http request PUT https://registry.npmjs.org/@ycjs%2fcore
42 http 500 https://registry.npmjs.org/@ycjs%2fcore
43 verbose headers { 'content-type': 'application/json',
43 verbose headers   'cache-control': 'max-age=0',
43 verbose headers   'content-length': '17',
43 verbose headers   'accept-ranges': 'bytes',
43 verbose headers   date: 'Mon, 27 Mar 2017 10:45:14 GMT',
43 verbose headers   via: '1.1 varnish',
43 verbose headers   connection: 'keep-alive',
43 verbose headers   'x-served-by': 'cache-nrt6124-NRT',
43 verbose headers   'x-cache': 'MISS',
43 verbose headers   'x-cache-hits': '0',
43 verbose headers   'x-timer': 'S1490611513.331386,VS0,VE745' }
44 info retry will retry, error on last attempt: Error: Registry returned 500 for PUT on https://registry.npmjs.org/@ycjs%2fcore
45 info attempt registry request try #2 at 6:45:24 PM
46 verbose request using bearer token for auth
47 http request PUT https://registry.npmjs.org/@ycjs%2fcore
48 http 500 https://registry.npmjs.org/@ycjs%2fcore
49 verbose headers { 'content-type': 'application/json',
49 verbose headers   'cache-control': 'max-age=0',
49 verbose headers   'content-length': '17',
49 verbose headers   'accept-ranges': 'bytes',
49 verbose headers   date: 'Mon, 27 Mar 2017 10:45:25 GMT',
49 verbose headers   via: '1.1 varnish',
49 verbose headers   connection: 'keep-alive',
49 verbose headers   'x-served-by': 'cache-nrt6124-NRT',
49 verbose headers   'x-cache': 'MISS',
49 verbose headers   'x-cache-hits': '0',
49 verbose headers   'x-timer': 'S1490611524.380737,VS0,VE913' }
50 info retry will retry, error on last attempt: Error: Registry returned 500 for PUT on https://registry.npmjs.org/@ycjs%2fcore
51 info attempt registry request try #3 at 6:46:25 PM
52 verbose request using bearer token for auth
53 http request PUT https://registry.npmjs.org/@ycjs%2fcore
54 http 500 https://registry.npmjs.org/@ycjs%2fcore
55 verbose headers { 'content-type': 'application/json',
55 verbose headers   'cache-control': 'max-age=0',
55 verbose headers   'content-length': '17',
55 verbose headers   'accept-ranges': 'bytes',
55 verbose headers   date: 'Mon, 27 Mar 2017 10:46:26 GMT',
55 verbose headers   via: '1.1 varnish',
55 verbose headers   connection: 'keep-alive',
55 verbose headers   'x-served-by': 'cache-nrt6124-NRT',
55 verbose headers   'x-cache': 'MISS',
55 verbose headers   'x-cache-hits': '0',
55 verbose headers   'x-timer': 'S1490611585.474558,VS0,VE684' }
56 verbose request invalidating /Users/yuchen/.npm/registry.npmjs.org/_40ycjs_252fcore on PUT
57 error publish Failed PUT 500
58 verbose stack Error: Registry returned 500 for PUT on https://registry.npmjs.org/@ycjs%2fcore
58 verbose stack     at makeError (/Users/yuchen/.nvm/versions/node/v7.7.2/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:304:12)
58 verbose stack     at CachingRegistryClient.<anonymous> (/Users/yuchen/.nvm/versions/node/v7.7.2/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:282:14)
58 verbose stack     at Request._callback (/Users/yuchen/.nvm/versions/node/v7.7.2/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:212:14)
58 verbose stack     at Request.self.callback (/Users/yuchen/.nvm/versions/node/v7.7.2/lib/node_modules/npm/node_modules/request/request.js:186:22)
58 verbose stack     at emitTwo (events.js:106:13)
58 verbose stack     at Request.emit (events.js:194:7)
58 verbose stack     at Request.<anonymous> (/Users/yuchen/.nvm/versions/node/v7.7.2/lib/node_modules/npm/node_modules/request/request.js:1081:10)
58 verbose stack     at emitOne (events.js:96:13)
58 verbose stack     at Request.emit (events.js:191:7)
58 verbose stack     at IncomingMessage.<anonymous> (/Users/yuchen/.nvm/versions/node/v7.7.2/lib/node_modules/npm/node_modules/request/request.js:1001:12)
59 verbose statusCode 500
60 verbose pkgid @ycjs/core
61 verbose cwd /Users/yuchen/Projects/ycjs/core/dist
62 error Darwin 16.4.0
63 error argv "/Users/yuchen/.nvm/versions/node/v7.7.2/bin/node" "/Users/yuchen/.nvm/versions/node/v7.7.2/bin/npm" "publish"
64 error node v7.7.2
65 error npm  v4.1.2
66 error code E500
67 error Registry returned 500 for PUT on https://registry.npmjs.org/@ycjs%2fcore
68 error If you need help, you may report this error at:
68 error     <https://github.com/npm/npm/issues>
69 verbose exit [ 1, true ]
MacBook-Pro:dist yuchen$
```

**Comment by legodude17** [comment]
This should most likely be reported on `npm/registry`.

**Comment by kuyoonjo** [comment]
Thank you legodude17, I will try it.
