### ISSUE TITLE
"Binary is fine" problem or "TypeError: Cannot read property 'latest' of undefined"

### ISSUE THREAD

**Issue by Bubelbub** [npm/npm#16183]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [X] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Yesterday (27.03.2017 00:39:38) I was able to install everything fine.
And today in the evening (28.03.2017 22:07:35) I get this problems.

```
2241 silly gunzTarPerm extractEntry lib/binding.js
2242 silly addNameRange number 2 { name: 'gulp-sourcemaps/map-sources',
2242 silly addNameRange   range: '>=1.0.0-0 <2.0.0-0',
2242 silly addNameRange   hasData: true }
2243 silly addNameRange versions [ undefined, [] ]
2244 error TypeError: Cannot read property 'latest' of undefined
2244 error     at next (/usr/share/npm/lib/cache.js:687:35)
2244 error     at /usr/share/npm/lib/cache.js:675:5
2244 error     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
2244 error     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
2244 error     at Object.oncomplete (fs.js:107:15)
2245 error If you need help, you may report this log at:
2245 error     <http://github.com/isaacs/npm/issues>
2245 error or email it to:
2245 error     <npm-@googlegroups.com>
2246 error System Linux 4.4.35-2-pve
2247 error command "/usr/bin/nodejs" "/usr/bin/npm" "install"
2248 error cwd /var/www/vhosts/example.org/releases/20170329084246
2249 error node -v v0.10.25
2250 error npm -v 1.3.10
2251 error type non_object_property_load
2252 verbose exit [ 1, true ]
```

**Problem in CLI:**
```
npm http 304 https://registry.npmjs.org/jsonify

> node-sass@3.14.0-0 install /var/www/vhosts/example.org/releases/20170329084246/node_modules/gulp-sass/node_modules/node-sass
> node scripts/install.js

Cached binary found at /root/.npm/node-sass/3.14.0-0/linux-x64-11_binding.node

> node-sass@3.14.0-0 postinstall /var/www/vhosts/example.org/releases/20170329084246/node_modules/gulp-sass/node_modules/node-sass
> node scripts/build.js

Binary found at /var/www/vhosts/example.org/releases/20170329084246/node_modules/gulp-sass/node_modules/node-sass/vendor/linux-x64-11/binding.node
Testing binary
Binary is fine
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /var/www/vhosts/example.org/releases/20170329084246/npm-debug.log
npm ERR! not ok code 0
```

#### How can the CLI team reproduce the problem?

`package.json`
```
  "dependencies": {
    "bower": "^1.7.7",
    "gulp": "^3.9.1",
    "gulp-concat": "^2.6.0",
    "gulp-if": "^2.0.0",
    "gulp-order": "^1.1.1",
    "gulp-sass": "^2.1.1",
    "gulp-sourcemaps": "^1.6.0",
    "gulp-uglify": "^1.5.1",
    "gulp-uglifycss": "^1.0.5"
  },
```

`npm-debug.log`
https://gist.github.com/Bubelbub/4a3855106883835e3c502aa831e99ff3

### supporting information:

 - `npm -v` prints: 1.3.10
 - `node -v` prints: Nothing, but command seems to be found
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux plesk 4.4.35-2-pve x86_64 x86_64 x86_64 GNU/Linux
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

Thanks in Advance for ideas 👍

**Comment by Bubelbub** [comment]
Updated to NodeJS7 and everything is working 👍
