### ISSUE TITLE
NPM - Cannot find module 'ctype'

### ISSUE THREAD

**Issue by ananth777** [npm/npm#16181]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [X] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
My Nodejs -v is 7.7.4. Having NPM issue on my Raspberry PI 3
#### How can the CLI team reproduce the problem?

  root@raspberrypi:/home/pi# npm UPDATE
Error: Cannot find module 'ctype'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/node_modules/http-signature/lib/util.js:7:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
npm ERR! Linux 4.9.16-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "UPDATE"
npm ERR! node v4.3.2
npm ERR! npm  v2.14.12
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'ctype'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by KenanY** [comment]
Hmm, this look like a broken installation to me. Maybe try [reinstalling](https://github.com/npm/npm/wiki/Troubleshooting#if-your-npm-is-broken)?
