### ISSUE TITLE
I don't have permission to publish despite being an owner

### ISSUE THREAD

**Issue by nmrichards** [npm/npm#16206]
So I'm pretty new to npm but I'm having an issue publishing a new version of our library. I've seen some of the issues that others had with the same error but none of the solutions worked for me. I'm one of the 'owners' to the library on npm. I've done an `npm owner ls <package>` and it shows the exact one listed under `npm whoami`. I've changed the version number as well so I don't think it's a name clash issue. I was just recently added as owner to the library, as in right before I tried to publish. Not sure if it takes time to update in the registry or not. Here is the debug log

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'publish',
1 verbose cli   '--access',
1 verbose cli   'public',
1 verbose cli   './dist/ng2-mtna-lib',
1 verbose cli   '--tag',
1 verbose cli   'latest' ]
2 info using npm@3.10.10
3 info using node@v6.9.5
4 verbose publish [ './dist/ng2-mtna-lib' ]
5 silly cache add args [ './dist/ng2-mtna-lib', null ]
6 verbose cache add spec ./dist/ng2-mtna-lib
7 silly cache add parsed spec Result {
7 silly cache add   raw: './dist/ng2-mtna-lib',
7 silly cache add   scope: null,
7 silly cache add   escapedName: null,
7 silly cache add   name: null,
7 silly cache add   rawSpec: './dist/ng2-mtna-lib',
7 silly cache add   spec: '/Users/nickrichards/Documents/work/Projects/ng2-mtna-lib/dist/ng2-mtna-lib',
7 silly cache add   type: 'directory' }
8 verbose addLocalDirectory /Users/nickrichards/.npm/ng2-mtna-lib/2.4.3/package.tgz not in flight; packing
9 verbose correctMkdir /Users/nickrichards/.npm correctMkdir not in flight; initializing
10 info lifecycle ng2-mtna-lib@2.4.3~prepublish: ng2-mtna-lib@2.4.3
11 silly lifecycle ng2-mtna-lib@2.4.3~prepublish: no script for prepublish, continuing
12 verbose tar pack [ '/Users/nickrichards/.npm/ng2-mtna-lib/2.4.3/package.tgz',
12 verbose tar pack   '/Users/nickrichards/Documents/work/Projects/ng2-mtna-lib/dist/ng2-mtna-lib' ]
13 verbose tarball /Users/nickrichards/.npm/ng2-mtna-lib/2.4.3/package.tgz
14 verbose folder /Users/nickrichards/Documents/work/Projects/ng2-mtna-lib/dist/ng2-mtna-lib
15 verbose addLocalTarball adding from inside cache /Users/nickrichards/.npm/ng2-mtna-lib/2.4.3/package.tgz
16 verbose correctMkdir /Users/nickrichards/.npm correctMkdir not in flight; initializing
17 silly cache afterAdd ng2-mtna-lib@2.4.3
18 verbose afterAdd /Users/nickrichards/.npm/ng2-mtna-lib/2.4.3/package/package.json not in flight; writing
19 verbose correctMkdir /Users/nickrichards/.npm correctMkdir not in flight; initializing
20 verbose afterAdd /Users/nickrichards/.npm/ng2-mtna-lib/2.4.3/package/package.json written
21 silly publish { name: 'ng2-mtna-lib',
21 silly publish   version: '2.4.3',
21 silly publish   description: 'Angular 2 component library for Metadata Technology North America',
21 silly publish   main: './bundles/ng2-mtna-lib.umd.js',
21 silly publish   module: './index.js',
21 silly publish   typings: './index.d.ts',
21 silly publish   license: 'MIT',
21 silly publish   peerDependencies:
21 silly publish    { '@angular/core': '^2.3.0',
21 silly publish      '@angular/common': '^2.3.0',
21 silly publish      '@angular/http': '^2.3.0' },
21 silly publish   readme: '# Angular 2 Components for Metadata Technology North America\n[![npm version](https://badge.fury.io/js/ng2-mtna-lib.svg)](https://www.npmjs.com/package/ng2-mtna-lib)\n\n### Installation\n\nThe latest release of the library can be installed from npm\n\n`npm install ng2-mtna-lib`\n',
21 silly publish   readmeFilename: 'README.md',
21 silly publish   _id: 'ng2-mtna-lib@2.4.3',
21 silly publish   scripts: {},
21 silly publish   _shasum: 'f615fe5f4d7960d539b71c83731c37c573ac7eec',
21 silly publish   _from: 'dist/ng2-mtna-lib',
21 silly publish   _resolved: 'file:dist/ng2-mtna-lib' }
22 verbose getPublishConfig undefined
23 silly mapToRegistry name ng2-mtna-lib
24 silly mapToRegistry using default registry
25 silly mapToRegistry registry https://registry.npmjs.org/
26 silly mapToRegistry data Result {
26 silly mapToRegistry   raw: 'ng2-mtna-lib',
26 silly mapToRegistry   scope: null,
26 silly mapToRegistry   escapedName: 'ng2-mtna-lib',
26 silly mapToRegistry   name: 'ng2-mtna-lib',
26 silly mapToRegistry   rawSpec: '',
26 silly mapToRegistry   spec: 'latest',
26 silly mapToRegistry   type: 'tag' }
27 silly mapToRegistry uri https://registry.npmjs.org/ng2-mtna-lib
28 verbose publish registryBase https://registry.npmjs.org/
29 silly publish uploading /Users/nickrichards/.npm/ng2-mtna-lib/2.4.3/package.tgz
30 verbose request uri https://registry.npmjs.org/ng2-mtna-lib
31 verbose request sending authorization for write operation
32 info attempt registry request try #1 at 3:07:23 PM
33 verbose request using bearer token for auth
34 verbose request id cb5de4653446fd29
35 http request PUT https://registry.npmjs.org/ng2-mtna-lib
36 http 403 https://registry.npmjs.org/ng2-mtna-lib
37 verbose headers { 'content-type': 'application/json',
37 verbose headers   'cache-control': 'max-age=300',
37 verbose headers   'content-length': '106',
37 verbose headers   'accept-ranges': 'bytes',
37 verbose headers   date: 'Thu, 30 Mar 2017 19:07:24 GMT',
37 verbose headers   via: '1.1 varnish',
37 verbose headers   connection: 'keep-alive',
37 verbose headers   'x-served-by': 'cache-atl6241-ATL',
37 verbose headers   'x-cache': 'MISS',
37 verbose headers   'x-cache-hits': '0',
37 verbose headers   'x-timer': 'S1490900843.737930,VS0,VE551',
37 verbose headers   vary: 'Accept-Encoding' }
38 verbose request invalidating /Users/nickrichards/.npm/registry.npmjs.org/ng2-mtna-lib on PUT
39 error publish Failed PUT 403
40 verbose stack Error: you do not have permission to publish "ng2-mtna-lib". Are you logged in as the correct user? : ng2-mtna-lib
40 verbose stack     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:302:12)
40 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:290:14)
40 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:210:14)
40 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:187:22)
40 verbose stack     at emitTwo (events.js:106:13)
40 verbose stack     at Request.emit (events.js:191:7)
40 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1048:10)
40 verbose stack     at emitOne (events.js:96:13)
40 verbose stack     at Request.emit (events.js:188:7)
40 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:969:12)
41 verbose statusCode 403
42 verbose pkgid ng2-mtna-lib
43 verbose cwd /Users/nickrichards/Documents/work/Projects/ng2-mtna-lib
44 error Darwin 16.4.0
45 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "publish" "--access" "public" "./dist/ng2-mtna-lib" "--tag" "latest"
46 error node v6.9.5
47 error npm  v3.10.10
48 error code E403
49 error you do not have permission to publish "ng2-mtna-lib". Are you logged in as the correct user? : ng2-mtna-lib
50 error If you need help, you may report this error at:
50 error     <https://github.com/npm/npm/issues>
51 verbose exit [ 1, true ]
```

**Comment by nmrichards** [comment]
I guess it was a timing issue. I was able to publish today without issue. Sorry for adding to the list of issues.

**Comment by Almenon** [comment]
I ran into same thing - it failed first time and worked second time.  Very wierd.
