### ISSUE TITLE
Can't install npm.

### ISSUE THREAD

**Issue by Jacklack3** [npm/npm#16215]
I can't install npm. I've installed nodejs and i've restarted, tried in cmd, git and powershell but I get this error.

> 0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@4.2.0
3 info using node@v7.8.0
4 verbose config Skipping project config: C:\Users\(user name)/.npmrc. (matches userconfig)
5 verbose stack Error: Cannot find module 'internal/fs'
5 verbose stack     at Function.Module._resolveFilename (module.js:470:15)
5 verbose stack     at Function.Module._load (module.js:418:25)
5 verbose stack     at Module.require (module.js:498:17)
5 verbose stack     at require (internal/module.js:20:19)
5 verbose stack     at evalmachine.<anonymous>:18:20
5 verbose stack     at Object.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\cmd-shim\node_modules\graceful-fs\fs.js:11:1)
5 verbose stack     at Module._compile (module.js:571:32)
5 verbose stack     at Object.Module._extensions..js (module.js:580:10)
5 verbose stack     at Module.load (module.js:488:32)
5 verbose stack     at tryModuleLoad (module.js:447:12)
6 verbose cwd C:\Users\(user name)
7 error Windows_NT 10.0.14393
8 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
9 error node v7.8.0
10 error npm  v4.2.0
11 error code MODULE_NOT_FOUND
12 error Cannot find module 'internal/fs'
13 error If you need help, you may report this error at:
13 error     <https://github.com/npm/npm/issues>
14 verbose exit [ 1, true ]

**Comment by Jacklack3** [comment]
Okay so I installed nodejs via scoop but i get this. 
![image](https://cloud.githubusercontent.com/assets/13090766/24570427/5f9710a2-1639-11e7-87ea-1d2bdceeb9e0.png)
