### ISSUE TITLE
`npm install npm@latest -g` failed and now npm is broken

### ISSUE THREAD

**Issue by xareelee** [npm/npm#16273]
#### I'm opening this issue because:

  - [x] npm is crashing.

After running `npm install npm@latest -g`, the upgrade failed, and now I can't use `npm` anymore.

```
$ npm -v
module.js:472
    throw err;
    ^

Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/unsupported.js:2:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

I tried `curl -L http://npmjs.org/install.sh | sudo sh` from https://github.com/npm/npm/issues/4099, but it doesn't work for me.

**Comment by gigafied** [comment]
Same exact issue here... trying to go from 3.10.10 to any other version breaks.

Here is a `Dockerfile` that easily reproduces the issue:

````
FROM debian:jessie

ENV DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true
ENV LC_ALL=C LANGUAGE=C LANG=C

RUN dpkg --configure -a
RUN apt-get update && \
  apt-get install -y --no-install-recommends \
  apt-utils \
  autoconf \
  automake \
  build-essential \
  ca-certificates \
  curl \
  fakeroot \
  git \
  wget

RUN printf "installing dev packages...\n" && \
  curl -sL https://deb.nodesource.com/setup_6.x | bash - && \
  apt-get update && \
  apt-get install -y --no-install-recommends \
  nodejs

RUN printf "installing npm5" && \
  npm install npm@latest -g

RUN printf "cleanup...\n" && \
  apt-get clean
````

Important to note that the upgrade appears to work... however, if you start a container and try to `npm -v` you will see the error.

````
module.js:471
    throw err;
    ^
Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/npm/lib/utils/unsupported.js:2:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
````

**Comment by zkat** [comment]
@xareelee what platform?

**Comment by gigafied** [comment]
@zkat I kind of hijacked this issue since I had the same exact error message. I posted the `Dockerfile`.

Trying to install via the shell script also doesn't work. `curl -L https://www.npmjs.org/install.sh | sh`

Did some more digging there too, and the issue with the curl script is best summed up as 

````
root@90f02e911559:/# ls -la /usr/lib/node_modules/
total 12
drwxr-xr-x 3 root root    4096 Jun  7 03:09 .
drwxr-xr-x 1 root root    4096 Jun  7 02:46 ..
lrwxrwxrwx 1 root root      28 Jun  7 03:09 npm -> ../../../tmp/npm.957/package
drwxr-xr-x 2  502 dialout 4096 Jun  7 03:09 undefined
````
If I edit the script to not delete the tmp dir then `npm` works because the symlink is valid, so something to fix with that scenario as well.

**Comment by gigafied** [comment]
And it seems like the `npm install@latest -g` is just an entirely different manifestation of this issue here:

https://github.com/npm/npm/issues/9863

**Comment by StephaneTrebel** [comment]
Got the same semver error in my docker image based on ubuntu:zesty and node 8.1.2.
I upgraded from 5.0.1 to 5.1.0 with `npm install -g npm@5.1.0` and it was successful but any npm calls after that (even `npm --version`) errors.

**Comment by xareelee** [comment]
@zkat I use macOS.

BTW, I have reinstalled **npm** to resolve this issue.

**Comment by seymourduncandevops** [comment]
This happened to me as well. Attempted to upgrade but wasn't root, failed b/c permissions and now npm doesn't exist. CentOS
