### ISSUE TITLE
npm is throwing errors during npm install and npm shrinkwrap

### ISSUE THREAD

**Issue by ryanhinton** [npm/npm#16321]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
during 'npm install' and 'npm shrinkwrap', i receive extraneous errors.
#### How can the CLI team reproduce the problem?
npm install
npm shrinkwrap

The following is what I receive in my npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'shrinkwrap' ]
2 info using npm@3.10.10
3 info using node@v6.9.5
4 info lifecycle contegolink-portal@1.0.0~preshrinkwrap: contegolink-portal@1.0.0
5 silly lifecycle contegolink-portal@1.0.0~preshrinkwrap: no script for preshrinkwrap, continuing
6 info lifecycle contegolink-portal@1.0.0~shrinkwrap: contegolink-portal@1.0.0
7 silly lifecycle contegolink-portal@1.0.0~shrinkwrap: no script for shrinkwrap, continuing
8 verbose stack Error: Problems were encountered
8 verbose stack Please correct and try again.
8 verbose stack extraneous: accepts@1.3.3 F:\Websites\clientdev\js\node_modules\accepts
8 verbose stack extraneous: array-flatten@1.1.1 F:\Websites\clientdev\js\node_modules\array-flatten
8 verbose stack extraneous: array-parallel@0.1.3 F:\Websites\clientdev\js\node_modules\array-parallel
8 verbose stack extraneous: array-series@0.1.5 F:\Websites\clientdev\js\node_modules\array-series
8 verbose stack extraneous: Class@0.1.3 F:\Websites\clientdev\js\node_modules\Class
8 verbose stack extraneous: content-disposition@0.5.2 F:\Websites\clientdev\js\node_modules\content-disposition
8 verbose stack extraneous: content-type@1.0.2 F:\Websites\clientdev\js\node_modules\content-type
8 verbose stack extraneous: cookie@0.3.1 F:\Websites\clientdev\js\node_modules\cookie
8 verbose stack extraneous: cookie-signature@1.0.6 F:\Websites\clientdev\js\node_modules\cookie-signature
8 verbose stack extraneous: cross-spawn@4.0.2 F:\Websites\clientdev\js\node_modules\cross-spawn
8 verbose stack extraneous: depd@1.1.0 F:\Websites\clientdev\js\node_modules\depd
8 verbose stack extraneous: destroy@1.0.4 F:\Websites\clientdev\js\node_modules\destroy
8 verbose stack extraneous: ee-first@1.1.1 F:\Websites\clientdev\js\node_modules\ee-first
8 verbose stack extraneous: encodeurl@1.0.1 F:\Websites\clientdev\js\node_modules\encodeurl
8 verbose stack extraneous: etag@1.8.0 F:\Websites\clientdev\js\node_modules\etag
8 verbose stack extraneous: express@4.15.2 F:\Websites\clientdev\js\node_modules\express
8 verbose stack extraneous: express-errors@0.3.1 F:\Websites\clientdev\js\node_modules\express-errors
8 verbose stack extraneous: finalhandler@1.0.0 F:\Websites\clientdev\js\node_modules\finalhandler
8 verbose stack extraneous: forwarded@0.1.0 F:\Websites\clientdev\js\node_modules\forwarded
8 verbose stack extraneous: fresh@0.5.0 F:\Websites\clientdev\js\node_modules\fresh
8 verbose stack extraneous: fructose@1.0.1 F:\Websites\clientdev\js\node_modules\fructose
8 verbose stack extraneous: gm@1.23.0 F:\Websites\clientdev\js\node_modules\gm
8 verbose stack extraneous: debug@2.2.0 F:\Websites\clientdev\js\node_modules\gm\node_modules\debug
8 verbose stack extraneous: ms@0.7.1 F:\Websites\clientdev\js\node_modules\gm\node_modules\ms
8 verbose stack extraneous: http-errors@1.6.1 F:\Websites\clientdev\js\node_modules\http-errors
8 verbose stack extraneous: ipaddr.js@1.2.0 F:\Websites\clientdev\js\node_modules\ipaddr.js
8 verbose stack extraneous: media-typer@0.3.0 F:\Websites\clientdev\js\node_modules\media-typer
8 verbose stack extraneous: merge-descriptors@1.0.1 F:\Websites\clientdev\js\node_modules\merge-descriptors
8 verbose stack extraneous: methods@1.1.2 F:\Websites\clientdev\js\node_modules\methods
8 verbose stack extraneous: mime@1.3.4 F:\Websites\clientdev\js\node_modules\mime
8 verbose stack extraneous: negotiator@0.6.1 F:\Websites\clientdev\js\node_modules\negotiator
8 verbose stack extraneous: on-finished@2.3.0 F:\Websites\clientdev\js\node_modules\on-finished
8 verbose stack extraneous: parseurl@1.3.1 F:\Websites\clientdev\js\node_modules\parseurl
8 verbose stack extraneous: path-to-regexp@0.1.7 F:\Websites\clientdev\js\node_modules\path-to-regexp
8 verbose stack extraneous: proxy-addr@1.1.3 F:\Websites\clientdev\js\node_modules\proxy-addr
8 verbose stack extraneous: qs@6.4.0 F:\Websites\clientdev\js\node_modules\qs
8 verbose stack extraneous: range-parser@1.2.0 F:\Websites\clientdev\js\node_modules\range-parser
8 verbose stack extraneous: send@0.15.1 F:\Websites\clientdev\js\node_modules\send
8 verbose stack extraneous: serve-static@1.12.1 F:\Websites\clientdev\js\node_modules\serve-static
8 verbose stack extraneous: setprototypeof@1.0.3 F:\Websites\clientdev\js\node_modules\setprototypeof
8 verbose stack extraneous: statuses@1.3.1 F:\Websites\clientdev\js\node_modules\statuses
8 verbose stack extraneous: toaster@0.1.2 F:\Websites\clientdev\js\node_modules\toaster
8 verbose stack extraneous: type-is@1.6.14 F:\Websites\clientdev\js\node_modules\type-is
8 verbose stack extraneous: unpipe@1.0.0 F:\Websites\clientdev\js\node_modules\unpipe
8 verbose stack extraneous: utils-merge@1.0.0 F:\Websites\clientdev\js\node_modules\utils-merge
8 verbose stack extraneous: vary@1.1.0 F:\Websites\clientdev\js\node_modules\vary
8 verbose stack     at shrinkwrap_ (C:\Program Files\nodejs\node_modules\npm\lib\shrinkwrap.js:128:15)
8 verbose stack     at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
8 verbose stack     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
8 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:18:7
8 verbose stack     at done (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:132:5)
8 verbose stack     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:7:26)
8 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:18:7
8 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:294:20
8 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
8 verbose stack     at FSReqWrap.oncomplete (fs.js:123:15)
9 verbose cwd F:\Websites\clientdev\js
10 error Windows_NT 6.3.9600
11 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "shrinkwrap"
12 error node v6.9.5
13 error npm  v3.10.10
14 error Problems were encountered
14 error Please correct and try again.
14 error extraneous: accepts@1.3.3 F:\Websites\clientdev\js\node_modules\accepts
14 error extraneous: array-flatten@1.1.1 F:\Websites\clientdev\js\node_modules\array-flatten
14 error extraneous: array-parallel@0.1.3 F:\Websites\clientdev\js\node_modules\array-parallel
14 error extraneous: array-series@0.1.5 F:\Websites\clientdev\js\node_modules\array-series
14 error extraneous: Class@0.1.3 F:\Websites\clientdev\js\node_modules\Class
14 error extraneous: content-disposition@0.5.2 F:\Websites\clientdev\js\node_modules\content-disposition
14 error extraneous: content-type@1.0.2 F:\Websites\clientdev\js\node_modules\content-type
14 error extraneous: cookie@0.3.1 F:\Websites\clientdev\js\node_modules\cookie
14 error extraneous: cookie-signature@1.0.6 F:\Websites\clientdev\js\node_modules\cookie-signature
14 error extraneous: cross-spawn@4.0.2 F:\Websites\clientdev\js\node_modules\cross-spawn
14 error extraneous: depd@1.1.0 F:\Websites\clientdev\js\node_modules\depd
14 error extraneous: destroy@1.0.4 F:\Websites\clientdev\js\node_modules\destroy
14 error extraneous: ee-first@1.1.1 F:\Websites\clientdev\js\node_modules\ee-first
14 error extraneous: encodeurl@1.0.1 F:\Websites\clientdev\js\node_modules\encodeurl
14 error extraneous: etag@1.8.0 F:\Websites\clientdev\js\node_modules\etag
14 error extraneous: express@4.15.2 F:\Websites\clientdev\js\node_modules\express
14 error extraneous: express-errors@0.3.1 F:\Websites\clientdev\js\node_modules\express-errors
14 error extraneous: finalhandler@1.0.0 F:\Websites\clientdev\js\node_modules\finalhandler
14 error extraneous: forwarded@0.1.0 F:\Websites\clientdev\js\node_modules\forwarded
14 error extraneous: fresh@0.5.0 F:\Websites\clientdev\js\node_modules\fresh
14 error extraneous: fructose@1.0.1 F:\Websites\clientdev\js\node_modules\fructose
14 error extraneous: gm@1.23.0 F:\Websites\clientdev\js\node_modules\gm
14 error extraneous: debug@2.2.0 F:\Websites\clientdev\js\node_modules\gm\node_modules\debug
14 error extraneous: ms@0.7.1 F:\Websites\clientdev\js\node_modules\gm\node_modules\ms
14 error extraneous: http-errors@1.6.1 F:\Websites\clientdev\js\node_modules\http-errors
14 error extraneous: ipaddr.js@1.2.0 F:\Websites\clientdev\js\node_modules\ipaddr.js
14 error extraneous: media-typer@0.3.0 F:\Websites\clientdev\js\node_modules\media-typer
14 error extraneous: merge-descriptors@1.0.1 F:\Websites\clientdev\js\node_modules\merge-descriptors
14 error extraneous: methods@1.1.2 F:\Websites\clientdev\js\node_modules\methods
14 error extraneous: mime@1.3.4 F:\Websites\clientdev\js\node_modules\mime
14 error extraneous: negotiator@0.6.1 F:\Websites\clientdev\js\node_modules\negotiator
14 error extraneous: on-finished@2.3.0 F:\Websites\clientdev\js\node_modules\on-finished
14 error extraneous: parseurl@1.3.1 F:\Websites\clientdev\js\node_modules\parseurl
14 error extraneous: path-to-regexp@0.1.7 F:\Websites\clientdev\js\node_modules\path-to-regexp
14 error extraneous: proxy-addr@1.1.3 F:\Websites\clientdev\js\node_modules\proxy-addr
14 error extraneous: qs@6.4.0 F:\Websites\clientdev\js\node_modules\qs
14 error extraneous: range-parser@1.2.0 F:\Websites\clientdev\js\node_modules\range-parser
14 error extraneous: send@0.15.1 F:\Websites\clientdev\js\node_modules\send
14 error extraneous: serve-static@1.12.1 F:\Websites\clientdev\js\node_modules\serve-static
14 error extraneous: setprototypeof@1.0.3 F:\Websites\clientdev\js\node_modules\setprototypeof
14 error extraneous: statuses@1.3.1 F:\Websites\clientdev\js\node_modules\statuses
14 error extraneous: toaster@0.1.2 F:\Websites\clientdev\js\node_modules\toaster
14 error extraneous: type-is@1.6.14 F:\Websites\clientdev\js\node_modules\type-is
14 error extraneous: unpipe@1.0.0 F:\Websites\clientdev\js\node_modules\unpipe
14 error extraneous: utils-merge@1.0.0 F:\Websites\clientdev\js\node_modules\utils-merge
14 error extraneous: vary@1.1.0 F:\Websites\clientdev\js\node_modules\vary
15 error If you need help, you may report this error at:
15 error     <https://github.com/npm/npm/issues>
16 verbose exit [ 1, true ]

### supporting information:

 - `npm -v` prints: 3.10.10
 - `node -v` prints: v6.9.5
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?: Windows
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by ryanhinton** [comment]
I was able to get past these issues by doing the following their respective order:
- deleted all of the packages in node_modules folder except for .bin 
- deleted everything in the node_cache folder
- deleted the npm-shrinkwrap.json file
- npm install
- npm shrinkwrap
