### ISSUE TITLE
Unable to execute any npm-related commands

### ISSUE THREAD

**Issue by Hidduh** [npm/npm#16335]
#### I'm opening this issue because:

  - [ X ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I am unable to use any command within the npm-package as it keeps on returning the same error. Installing a package and reinstalling/removing npm doesn't work either. The only working command seems to be npm -v.

### supporting information:

Version of npm: 4.1.2
Version of node: 7.6.0
uname -a: Linux Raspbian 4.4.38+ #938 Thu Dec 15 15:17:54 GMT 2016 armv6l GNU/Linux

--

```
~ $ sudo npm uninstall npm -g

/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_readable.js:607
    if"(dest &&!dest !== state.pipes) return this;
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Invalid or unexpected token
    at Object.exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/node_modules/concat-stream/node_modules/readable-stream/readable.js:6:28)
    at Module._compile (module.js:571:32)
npm ERR! Linux 4.4.38+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "uninstall" "npm" "-g"
npm ERR! node v7.6.0
npm ERR! npm  v4.1.2

npm ERR! Invalid or unexpected token
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

**Comment by legodude17** [comment]
Try reinstalling `npm` from the `nodejs` website.

**Comment by Hidduh** [comment]
Seems like a complete reinstall did the trick after trying four times before - thanks.
