### ISSUE TITLE
setup my package.json in VS2017 when I save the file I got this error

### ISSUE THREAD

**Issue by apayero** [npm/npm#16341]
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\Web\\External\\Node.exe',
1 verbose cli   'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\Web\\External\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@3.3.4
3 info using node@v5.4.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly install normalizeTree
8 verbose stack Error: Missing required argument #2
8 verbose stack     at exports.findRequirement (C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Web\External\node_modules\npm\lib\install\deps.js:475:3)
8 verbose stack     at C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Web\External\node_modules\npm\lib\install\deps.js:90:19
8 verbose stack     at zalgoSafe (C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Web\External\node_modules\dezalgo\dezalgo.js:20:10)
8 verbose stack     at finalize (C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Web\External\node_modules\realize-package-specifier\index.js:37:5)
8 verbose stack     at C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Web\External\node_modules\realize-package-specifier\index.js:22:20
8 verbose stack     at FSReqWrap.oncomplete (fs.js:82:15)
9 verbose cwd D:\DropBox\ProyecotsDeDesarrollo VB.Net y CSharp.Net\ProyectoCSharp.Net\VS2017 CSharp\Practicas LibroAngular2\PruebaSetupSPAVueJS\PruebaSetupSPAVueJS
10 error Windows_NT 6.1.7601
11 error argv "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\Web\\External\\Node.exe" "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\Web\\External\\node_modules\\npm\\bin\\npm-cli.js" "install"
12 error node v5.4.1
13 error npm  v3.3.4
14 error code EMISSINGARG
15 error typeerror Error: Missing required argument #2
15 error typeerror     at exports.findRequirement (C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Web\External\node_modules\npm\lib\install\deps.js:475:3)
15 error typeerror     at C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Web\External\node_modules\npm\lib\install\deps.js:90:19
15 error typeerror     at zalgoSafe (C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Web\External\node_modules\dezalgo\dezalgo.js:20:10)
15 error typeerror     at finalize (C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Web\External\node_modules\realize-package-specifier\index.js:37:5)
15 error typeerror     at C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Web\External\node_modules\realize-package-specifier\index.js:22:20
15 error typeerror     at FSReqWrap.oncomplete (fs.js:82:15)
15 error typeerror This is an error with npm itself. Please report this error at:
15 error typeerror     <http://github.com/npm/npm/issues>
16 verbose exit [ 1, true ]
```

**Comment by strugee** [comment]
Please edit your issue to use proper code formatting. Otherwise it's unreadable.

**Comment by legodude17** [comment]
Please go through the [troubleshooting guide](https://github.com/npm/npm/wiki/Troubleshooting).

**Comment by KenanY** [comment]
I edited the OP to wrap the log in a code block for readability.

**Comment by legodude17** [comment]
@KenanY Thank you for that.

**Comment by KenanY** [comment]
Closing due to no reply after a month.
