### ISSUE TITLE
'Permission denied' error when installing packages without version field

### ISSUE THREAD

**Issue by bisubus** [npm/npm#16340]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

When a package is installed from public repository that doesn't have `version` field in package.json with `npm i user/package#branch`  or `"package": "user/package"`, NPM fails with irrelevant error. This happens for all NPM versions.

There's a lot of packages that don't have `version` in the repo because the field is added on publishing with `semantic-release` or other tools. This means that they cannot be used like `"package": "user/package#pr-with-hot-fix"` without creating a fork and keeping it up to date.

It is not clear if this is the expected behaviour or not. If it is, there should be a feature request to allow this. The documentation is specific that `version` field is required but the versions don't affect anything when a package is installed from a repo. If NPM needs to version a package anyway, it can apply a bogus version like 0.0.0 to it.

But the real problem is that *Permission denied* and *Could not read from remote repository* error messages are misleading. They don't explain the problem. There is a myriad of possible reasons for these errors, and missing `version` field doesn't look like a valid reason.

#### How can the CLI team reproduce the problem?
```
npm i bisubus/npm-package-test#version
```
properly installs the package from the branch that has `version` field in package.json.

```
npm i bisubus/npm-package-test
```
fails to install the package that doens't have `version` field in package.json, with error:

> Permission denied (publickey).
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> verbose stack and the repository exists.

[Here is a gist of the log](https://gist.github.com/bisubus/3024102465241e66cb0119836f7857cd) and its relevant part:

```
65 info git [ 'clone',
65 info git   '--template=C:\\Users\\bisubus\\AppData\\Roaming\\npm-cache\\_git-remotes\\_templates',
65 info git   '--mirror',
65 info git   'git@github.com:bisubus/npm-package-test.git',
65 info git   'C:\\Users\\bisubus\\AppData\\Roaming\\npm-cache\\_git-remotes\\git-github-com-bisubus-npm-package-test-git-506d6faa' ]
66 error git clone --template=C:\Users\bisubus\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:bisubus/npm-package-test.git C:\Users\bisubus\AppData\Roaming\npm-cache\_git-remotes\git-github-com-bisubus-npm-package-test-git-506d6faa: Cloning into bare repository 'C:\Users\bisubus\AppData\Roaming\npm-cache\_git-remotes\git-github-com-bisubus-npm-package-test-git-506d6faa'...
66 error git clone --template=C:\Users\bisubus\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:bisubus/npm-package-test.git C:\Users\bisubus\AppData\Roaming\npm-cache\_git-remotes\git-github-com-bisubus-npm-package-test-git-506d6faa: Permission denied (publickey).
66 error git clone --template=C:\Users\bisubus\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:bisubus/npm-package-test.git C:\Users\bisubus\AppData\Roaming\npm-cache\_git-remotes\git-github-com-bisubus-npm-package-test-git-506d6faa: fatal: Could not read from remote repository.
66 error git clone --template=C:\Users\bisubus\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:bisubus/npm-package-test.git C:\Users\bisubus\AppData\Roaming\npm-cache\_git-remotes\git-github-com-bisubus-npm-package-test-git-506d6faa:
66 error git clone --template=C:\Users\bisubus\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:bisubus/npm-package-test.git C:\Users\bisubus\AppData\Roaming\npm-cache\_git-remotes\git-github-com-bisubus-npm-package-test-git-506d6faa: Please make sure you have the correct access rights
66 error git clone --template=C:\Users\bisubus\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:bisubus/npm-package-test.git C:\Users\bisubus\AppData\Roaming\npm-cache\_git-remotes\git-github-com-bisubus-npm-package-test-git-506d6faa: and the repository exists.
67 verbose stack Error: Command failed: git -c core.longpaths=true clone --template=C:\Users\bisubus\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:bisubus/npm-package-test.git C:\Users\bisubus\AppData\Roaming\npm-cache\_git-remotes\git-github-com-bisubus-npm-package-test-git-506d6faa
67 verbose stack Cloning into bare repository 'C:\Users\bisubus\AppData\Roaming\npm-cache\_git-remotes\git-github-com-bisubus-npm-package-test-git-506d6faa'...
67 verbose stack Permission denied (publickey).
67 verbose stack fatal: Could not read from remote repository.
67 verbose stack
67 verbose stack Please make sure you have the correct access rights
67 verbose stack and the repository exists.
67 verbose stack
67 verbose stack     at ChildProcess.exithandler (child_process.js:206:12)
67 verbose stack     at emitTwo (events.js:106:13)
67 verbose stack     at ChildProcess.emit (events.js:191:7)
67 verbose stack     at maybeClose (internal/child_process.js:877:16)
67 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

### supporting information:

 - `npm -v` prints: 2.15.11; 3.10.10; 4.4.4
 - `node -v` prints: 6.9.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows, Linux

**Comment by bisubus** [comment]
Thanks for your cooperation, @npm-robot 

Any way, this was finally fixed in NPM 5.
