### ISSUE TITLE
If you are behind a proxy, please make sure that the 'proxy' config is set properly.  See: 'npm help config'

### ISSUE THREAD

**Issue by muthughilli** [npm/npm#16355]
Hi 
i am trying to install the following command in my pc.
npm install -g adapt-cli

when i try installing i am getting the following error.

```
69792 verbose unlock done using C:\Users\Muthup\AppData\Roaming\npm-cache\_locks\fstream-f59f327f771c0f93.lock for C:\Users\Muthup\AppData\Roaming\npm\node_modules\adapt-cli\node_modules\nodegit\node_modules\node-gyp\node_modules\fstream
69793 verbose stack Error: read ECONNRESET
69793 verbose stack     at exports._errnoException (util.js:746:11)
69793 verbose stack     at TCP.onread (net.js:559:26)
69794 verbose cwd C:\windows\system32
69795 error Windows_NT 6.2.9200
69796 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "adapt-cli"
69797 error node v0.12.7
69798 error npm  v2.11.3
69799 error code ECONNRESET
69800 error errno ECONNRESET
69801 error syscall read
69802 error network read ECONNRESET
69802 error network This is most likely not a problem with npm itself
69802 error network and is related to network connectivity.
69802 error network In most cases you are behind a proxy or have bad network settings.
69802 error network
69802 error network If you are behind a proxy, please make sure that the
69802 error network 'proxy' config is set properly.  See: 'npm help config'
69803 verbose exit [ 1, true ]
```

can u please guide me what could be the issue and please instruct me how to proceed.

**Comment by legodude17** [comment]
Are you behind a proxy?

**Comment by arshmohal** [comment]
i have a same question, will you please help???

**Comment by legodude17** [comment]
@arshmohal do you mean you have the same issue or the same question as me?

**Comment by ansh0811** [comment]
Same error i am facing while installing cordova and ionic . Yes, i am behind corporate proxy .

Any suggestion how to resolve this issue?
![error](https://cloud.githubusercontent.com/assets/19550545/25984834/b374510a-3707-11e7-86d5-efb181ada20c.png)
[npm-log.docx](https://github.com/npm/npm/files/995182/npm-log.docx)

**Comment by legodude17** [comment]
Make sure your proxy is correctly configured and `npm` is configured correctly.
