### ISSUE TITLE
The "@angular/compiler-cli" package was not properly installed.

### ISSUE THREAD

**Issue by Basuchi** [npm/npm#16369]
The "@angular/compiler-cli" package was not properly installed.
Error: The "@angular/compiler-cli" package was not properly installed.
    at Object.<anonymous> (D:\TSA\onareportui\node_modules\@ngtools\webpack\src\index.js:14:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\TSA\onareportui\node_modules\@angular\cli\tasks\eject.js:10:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! onareportui@1.0.0 build: `ng build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the onareportui@1.0.0 build script 'ng build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the onareportui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ng build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs onareportui
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls onareportui
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\TSA\onareportui\npm-debug.log

Help me please

**Comment by legodude17** [comment]
This is a problem with `onareportui`, its build script is failing.

**Comment by kiran-nani** [comment]
Same problem here. I forgot to install node modules. Try `npm install` once, it may solve the problem

**Comment by kleberksms** [comment]
+1
