### ISSUE TITLE
Breaking change in npm v3.9.0, continues through npm 4

### ISSUE THREAD

**Issue by ljharb** [npm/npm#16371]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong? / How can the CLI team reproduce the problem?

1. Clone https://github.com/es-shims/es7-shim
1. `npm install -g npm@3.8`
1. run `node test/Object.entries.js` (or any of the files in `test`, but this is a nice trim example). It will proceed with cding into individual dependencies, running `npm install && npm test` (you can control-C out of it; it's not fast).
1. `npm install -g npm@3.9.0`
1. Run the same command. You'll see an error:

<details>

```sh
/bin/bash: npm install && npm test: command not found
npm ERR! Darwin 16.4.0
npm ERR! argv "$(which node)" "$(which npm)" "explore" "object.entries" "npm install && npm test"
npm ERR! node v5.11.0
npm ERR! npm  v3.9.0
npm ERR! file /bin/bash
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! enoent spawn ENOENT
npm ERR! enoent spawn ENOENT
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 
npm ERR! enoent Check if the file '/bin/bash' is present.

npm ERR! Please include the following file with any support request:
npm ERR!     $PWD/npm-debug.log
Error running tests for Object.entries 1
```
</details>

`npm-debug.log`:

<details>

```sh
0 info it worked if it ends with ok
1 verbose cli [ '$(which node)',
1 verbose cli   '$(which npm)',
1 verbose cli   'explore',
1 verbose cli   'object.entries',
1 verbose cli   'npm install && npm test' ]
2 info using npm@3.9.0
3 info using node@v5.11.0
4 verbose stack Error: spawn ENOENT
4 verbose stack     at ChildProcess.<anonymous> ($(npm root -g)/npm/lib/utils/spawn.js:17:16)
4 verbose stack     at emitTwo (events.js:100:13)
4 verbose stack     at ChildProcess.emit (events.js:185:7)
4 verbose stack     at maybeClose (internal/child_process.js:850:16)
4 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
5 verbose cwd $PWD
6 error Darwin 16.4.0
7 error argv "$(which node)" "$(which npm)" "explore" "object.entries" "npm install && npm test"
8 error node v5.11.0
9 error npm  v3.9.0
10 error file /bin/bash
11 error code ENOENT
12 error errno ENOENT
13 error syscall spawn
14 error enoent spawn ENOENT
15 error enoent spawn ENOENT
15 error enoent This is most likely not a problem with npm itself
15 error enoent and is related to npm not being able to find a file.
15 error enoent
15 error enoent Check if the file '/bin/bash' is present.
16 verbose exit [ 1, true ]
</details>

### supporting information:

 - `npm -v` prints: v3.9.0
 - `node -v` prints: v5.11.0
 - `npm config get registry` prints: default
 - Windows, OS X/macOS, or Linux?: Mac OS
 - Network issues: N/A
 - Container: none (nvm?)

**Comment by legodude17** [comment]
Does `/bin/bash` exist?

**Comment by ljharb** [comment]
@legodude17 yes, both because it's a stock Mac, and because it works on npm 3.8.

**Comment by legodude17** [comment]
🤔 Just as a test, try running `npm explore "object.entries" "touch hi"`

**Comment by ljharb** [comment]
@legodude17 absolutely, in v3.8, it works, in v3.9.0, I get `/bin/bash: touch hi: command not found`

**Comment by legodude17** [comment]
Hmmm... Looking through changelogs, the only change to `npm explore` from v3.8 to v3.9 is #11444. Maybe try manually reverting this [commit](https://github.com/npm/npm/commit/91fc24f2763c2e0591093099ffc866c735f27fde)?

**Comment by ljharb** [comment]
I don't have any way to easily revert a commit in npm and test it out - however, that seems reasonable. @iarna?

**Comment by legodude17** [comment]
I meant more like edit `npm`'s files on your computer. But whatever works.

**Comment by KenanY** [comment]
From `git bisect`, any of the following commits could be the first bad one:

- e928a30947477a09245f54e9381f46b97bee32d5
- 864a2e43b227478f4a304d8ff0e341cb23453478
- d3ce0b253eb519375071aee29db4ee129dbcdf5c
- 044cbab0d49adeeb0d9310c64fee6c9759cc7428
- b820ed4fc04e21577fa66f7c9482b5ab002e7985
- 7380425d810fb8bfc69405a9cbbdec19978a7bee
- bb5d6cbf46b2609243d3b384caadd196e665a797
- 2e01d299f8244134b1aa040cab1b59c72c9df4da
- 91fc24f2763c2e0591093099ffc866c735f27fde
- f07e6430d4ca02f811138f6140a8bad927607a1f

These all come from https://github.com/npm/npm/pull/11444.

**Comment by KenanY** [comment]
Quick fix, but very likely not to be the most appropriate one:

``` patch
diff --git a/lib/explore.js b/lib/explore.js
index 5640d5f15..8024e3b42 100644
--- a/lib/explore.js
+++ b/lib/explore.js
@@ -29,8 +29,7 @@ function explore (args, cb) {
       opts.windowsVerbatimArguments = true
       shellArgs = ['/d', '/s', '/c'].concat(execArgs)
     } else {
-      shellArgs.unshift('-c')
-      shellArgs = ['-c', args.map(escapeArg).join(' ').trim()]
+      shellArgs = ['-c', args.join(' ').trim()]
     }
   }
```

**Comment by KenanY** [comment]
Alternative solution, a patch to `es7-shim`:

``` patch
diff --git a/test/runner.js b/test/runner.js
index 610fdaa..7001df1 100644
--- a/test/runner.js
+++ b/test/runner.js
@@ -4,7 +4,7 @@ var spawn = require('child_process').spawn;
 module.exports = function (method, module) {
        console.log(method + ': running tests from "' + module + '"...');
        return new Promise(function (resolve, reject) {
-               spawn('npm', ['explore', module, 'npm install && npm test'], { stdio: 'inherit' })
+               spawn('npm', ['explore', module, '--', 'npm', 'install-test'], { stdio: 'inherit' })
                        .on('error', reject)
                        .on('close', function (code) {
                                (code === 0 ? resolve : reject)(code);
```

**Comment by ljharb** [comment]
It's good to know there's a fix to es7-shim :-) and that may be needed for npm 4; but npm 3 broke this in a minor release so hopefully it will be fixed.

**Comment by iarna** [comment]
@KenanY Your patch looks right to me. I was in a twisty maze of windows shell escapes when I wrote that and apparently crossed wires.

**Comment by iarna** [comment]
My by-hand test for this is:
```
npm explore $depname "node -e 'process.exit(0)' && node -e 'console.log(true)' || node -e 'console.log(false)'"
```

**Comment by ljharb** [comment]
@iarna yay! any chance this could go into npm 4 and 5 as well as 3? it'd be wonderful to keep the same approach for npms 2-5+ :-)

**Comment by iarna** [comment]
@ljharb 3 isn't maintained, but def 4 and 5.

**Comment by ljharb** [comment]
@iarna meaning, you won't ever be cutting a new release of it? that seems unfortunate that i didn't file this sooner then :-/

**Comment by ljharb** [comment]
(this surprises me specifically, because node 4, which is still in LTS, ships with npm 3)

**Comment by KenanY** [comment]
I thought node 4 ships npm 2, node 6 ships npm 3, and node 7 ships npm 4?

**Comment by ljharb** [comment]
whoops, sorry, node 6 ships npm 3, my bad.

**Comment by ljharb** [comment]
so shouldn't the fact that node 6 is still in LTS mean that npm 3 needs to remain in LTS? (or am i misunderstanding npm's LTS policy)

**Comment by iarna** [comment]
We no longer have an LTS (we just don't have the resources to maintain more than one version at a time). If the Node project were willing to take npm 4 into node 6, we'd be happy to provide it, but they've preferred to not take updates.

**Comment by iarna** [comment]
I'm... pretty sure we had a bunch of communication around this but I'm not immediately seeing it. I'll dig further.

**Comment by ljharb** [comment]
@iarna any update on fixing this `npm explore` behavior?

**Comment by legodude17** [comment]
Have you tried npm@5?

**Comment by ljharb** [comment]
The behavior persists in npm 5.

**Comment by ljharb** [comment]
(ping, just because i don't know when npmbot will annihilate my issue)
