### ISSUE TITLE
module.js:341     throw err;     ^  Error: Cannot find module '../lib/completion'

### ISSUE THREAD

**Issue by nicetomeetyoutoooo** [npm/npm#16409]
when I use npm install appium  ,i get this

module.js:341
    throw err;
    ^

Error: Cannot find module '../lib/completion'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/caohao/Work/appium/appium/node_modules/.bin/gulp:13:18)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)

Version Data:
Mac 10.10.5
node 5.8.0
npm 3.7.3

**Comment by KenanY** [comment]
Does this also occur with `npm@4`?

**Comment by KenanY** [comment]
Closing due to no reply after a month.
