### ISSUE TITLE
impossible to install ionic by using the cmd npm install -g cordova ionic

### ISSUE THREAD

**Issue by MSeguin7** [npm/npm#16410]
#### I'm opening this issue because:
- [ ] npm is producing an incorrect install.

#### What's going wrong?
impossible to install ionic by using the cmd npm install -g cordova ionic
#### How can the CLI team reproduce the problem?

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'cordova',
1 verbose cli   'ionic' ]
2 info using npm@4.2.0
3 info using node@v7.9.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData cordova
8 silly fetchPackageMetaData ionic
9 silly fetchNamedPackageData cordova
10 silly mapToRegistry name cordova
11 silly mapToRegistry using default registry
12 silly mapToRegistry registry https://registry.npmjs.org/
13 silly mapToRegistry data Result {
13 silly mapToRegistry   raw: 'cordova',
13 silly mapToRegistry   scope: null,
13 silly mapToRegistry   escapedName: 'cordova',
13 silly mapToRegistry   name: 'cordova',
13 silly mapToRegistry   rawSpec: '',
13 silly mapToRegistry   spec: 'latest',
13 silly mapToRegistry   type: 'tag' }
14 silly mapToRegistry uri https://registry.npmjs.org/cordova
15 silly fetchNamedPackageData ionic
16 silly mapToRegistry name ionic
17 silly mapToRegistry using default registry
18 silly mapToRegistry registry https://registry.npmjs.org/
19 silly mapToRegistry data Result {
19 silly mapToRegistry   raw: 'ionic',
19 silly mapToRegistry   scope: null,
19 silly mapToRegistry   escapedName: 'ionic',
19 silly mapToRegistry   name: 'ionic',
19 silly mapToRegistry   rawSpec: '',
19 silly mapToRegistry   spec: 'latest',
19 silly mapToRegistry   type: 'tag' }
20 silly mapToRegistry uri https://registry.npmjs.org/ionic
21 verbose request uri https://registry.npmjs.org/cordova
22 verbose request no auth needed
23 info attempt registry request try #1 at 14:57:49
24 verbose request id 0059b718dedcea6d
25 http request GET https://registry.npmjs.org/cordova
26 verbose request uri https://registry.npmjs.org/ionic
27 verbose request no auth needed
28 info attempt registry request try #1 at 14:57:49
29 http request GET https://registry.npmjs.org/ionic
30 info retry will retry, error on last attempt: Error: connect ECONNREFUSED 151.101.0.162:443
31 info retry will retry, error on last attempt: Error: connect ECONNREFUSED 151.101.0.162:443
32 info attempt registry request try #2 at 14:58:00
33 http request GET https://registry.npmjs.org/ionic
34 info attempt registry request try #2 at 14:58:00
35 http request GET https://registry.npmjs.org/cordova
36 info retry will retry, error on last attempt: Error: connect ECONNREFUSED 151.101.0.162:443
37 info retry will retry, error on last attempt: Error: connect ECONNREFUSED 151.101.0.162:443
38 info attempt registry request try #3 at 14:59:00
39 http request GET https://registry.npmjs.org/cordova
40 info attempt registry request try #3 at 14:59:00
41 http request GET https://registry.npmjs.org/ionic
42 silly fetchPackageMetaData Error: connect ECONNREFUSED 151.101.0.162:443
42 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1050:11)
42 silly fetchPackageMetaData     at exports._exceptionWithHostPort (util.js:1073:20)
42 silly fetchPackageMetaData     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
42 silly fetchPackageMetaData  error for cordova { Error: connect ECONNREFUSED 151.101.0.162:443
42 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1050:11)
42 silly fetchPackageMetaData     at exports._exceptionWithHostPort (util.js:1073:20)
42 silly fetchPackageMetaData     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
42 silly fetchPackageMetaData   code: 'ECONNREFUSED',
42 silly fetchPackageMetaData   errno: 'ECONNREFUSED',
42 silly fetchPackageMetaData   syscall: 'connect',
42 silly fetchPackageMetaData   address: '151.101.0.162',
42 silly fetchPackageMetaData   port: 443 }
43 silly fetchPackageMetaData Error: connect ECONNREFUSED 151.101.64.162:443
43 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1050:11)
43 silly fetchPackageMetaData     at exports._exceptionWithHostPort (util.js:1073:20)
43 silly fetchPackageMetaData     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
43 silly fetchPackageMetaData  error for ionic { Error: connect ECONNREFUSED 151.101.64.162:443
43 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1050:11)
43 silly fetchPackageMetaData     at exports._exceptionWithHostPort (util.js:1073:20)
43 silly fetchPackageMetaData     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
43 silly fetchPackageMetaData   code: 'ECONNREFUSED',
43 silly fetchPackageMetaData   errno: 'ECONNREFUSED',
43 silly fetchPackageMetaData   syscall: 'connect',
43 silly fetchPackageMetaData   address: '151.101.64.162',
43 silly fetchPackageMetaData   port: 443 }
44 silly rollbackFailedOptional Starting
45 verbose stack TypeError: Cannot read property 'path' of null
45 verbose stack     at Installer.rollbackFailedOptional (C:\Program Files\nodejs\node_modules\npm\lib\install.js:511:29)
45 verbose stack     at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
45 verbose stack     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
45 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:18:7
45 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install.js:337:5
45 verbose stack     at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
45 verbose stack     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
45 verbose stack     at chain (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
45 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install.js:294:5
45 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:16:22
46 verbose cwd D:\Users\tlachgar
47 error Windows_NT 6.1.7601
48 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova" "ionic"
49 error node v7.9.0
50 error npm  v4.2.0
51 error Cannot read property 'path' of null
52 error If you need help, you may report this error at:
52 error     <https://github.com/npm/npm/issues>
53 verbose exit [ 1, true ]
```

### supporting information:

 - `npm -v` prints: v4.2.0
 - `node -v` prints: v.7.9.0.
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?: Windows
 - Network issues:
   - Geographic location where npm was run: Paris
   - [ I dont know] I use a proxy to connect to the npm registry.
   - [I dont know ] I use a proxy to connect to the web.
   - [I dont know ] I use a proxy when downloading Git repos.
   - [I dont know ] I access the npm registry via a VPN
   - [ I dont know] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ No] I develop using Vagrant on Windows.
   - [No] I develop using Vagrant on OS X or Linux.
   - [No] I develop / deploy using Docker.
   - [No] I deploy to a PaaS (Triton, Heroku).

**Comment by KenanY** [comment]
This looks like an issue with your internet connection. The log indicates that your requests to the npm registry are timing out.

**Comment by davec21** [comment]
I was able to install latest ionic and cordova without issue. Seems like it's definitely something on your end.

**Comment by KenanY** [comment]
@davec21 If you think this is a registry issue, then you should let the registry team know: <https://github.com/npm/registry>.

**Comment by legodude17** [comment]
@KenanY I think that @davec21 meant "you" as in @MSeguin7

**Comment by KenanY** [comment]
@legodude17 Ah, yeah that could be the case too, lol :D

**Comment by KenanY** [comment]
Closing due to no reply after a month.
