### ISSUE TITLE
npm ERR! unregistered user is not allowed to access package @types/geojson : @types/geojson

### ISSUE THREAD

**Issue by blanchma** [npm/npm#16435]
```
16174 silly mapToRegistry uri http://npm.avi-on.com:4873/terraformer
16175 verbose addNameRange registry:http://npm.avi-on.com:4873/terraformer not in flight; fetching
16176 verbose get http://npm.avi-on.com:4873/terraformer not expired, no request
16177 silly addNameRange number 2 { name: 'terraformer', range: '>=1.0.5 <1.1.0', hasData: true }
16178 silly addNameRange versions [ 'terraformer',
16178 silly addNameRange   [ '0.1.0',
16178 silly addNameRange     '0.1.1',
16178 silly addNameRange     '0.1.3',
16178 silly addNameRange     '0.1.4',
16178 silly addNameRange     '0.1.5',
16178 silly addNameRange     '0.1.6',
16178 silly addNameRange     '0.1.7',
16178 silly addNameRange     '0.2.0',
16178 silly addNameRange     '1.0.0',
16178 silly addNameRange     '1.0.1',
16178 silly addNameRange     '1.0.3',
16178 silly addNameRange     '1.0.4',
16178 silly addNameRange     '1.0.5',
16178 silly addNameRange     '1.0.6',
16178 silly addNameRange     '1.0.7',
16178 silly addNameRange     '1.0.8' ] ]
16179 silly addNamed terraformer@1.0.8
16180 verbose addNamed "1.0.8" is a plain semver version for terraformer
16181 silly cache afterAdd terraformer@1.0.8
16182 verbose afterAdd /Users/blanchma/.npm/terraformer/1.0.8/package/package.json not in flight; writing
16183 verbose correctMkdir /Users/blanchma/.npm correctMkdir not in flight; initializing
16184 verbose afterAdd /Users/blanchma/.npm/terraformer/1.0.8/package/package.json written
16185 silly fetchNamedPackageData @types/geojson
16186 silly mapToRegistry name @types/geojson
16187 silly mapToRegistry scope (from package name) @types
16188 verbose mapToRegistry no registry URL found in name for scope @types
16189 silly mapToRegistry using default registry
16190 silly mapToRegistry registry http://npm.avi-on.com:4873/
16191 silly mapToRegistry data Result {
16191 silly mapToRegistry   raw: '@types/geojson',
16191 silly mapToRegistry   scope: '@types',
16191 silly mapToRegistry   name: '@types/geojson',
16191 silly mapToRegistry   rawSpec: '',
16191 silly mapToRegistry   spec: 'latest',
16191 silly mapToRegistry   type: 'tag' }
16192 silly mapToRegistry uri http://npm.avi-on.com:4873/@types%2fgeojson
16193 verbose request uri http://npm.avi-on.com:4873/@types%2fgeojson
16194 verbose request no auth needed
16195 info attempt registry request try #1 at 8:14:23 PM
16196 verbose request using bearer token for auth
16197 http request GET http://npm.avi-on.com:4873/@types%2fgeojson
16198 http 403 http://npm.avi-on.com:4873/@types%2fgeojson
16199 verbose headers { 'x-powered-by': 'Sinopia/1.4.0',
16199 verbose headers   'content-type': 'application/json; charset=utf-8',
16199 verbose headers   'content-length': '76',
16199 verbose headers   etag: 'W/"4c-869f68fc"',
16199 verbose headers   vary: 'Accept-Encoding',
16199 verbose headers   'x-status-cat': 'http://flic.kr/p/aV6jFK',
16199 verbose headers   date: 'Mon, 24 Apr 2017 23:14:23 GMT',
16199 verbose headers   connection: 'keep-alive' }
16200 silly get cb [ 403,
16200 silly get   { 'x-powered-by': 'Sinopia/1.4.0',
16200 silly get     'content-type': 'application/json; charset=utf-8',
16200 silly get     'content-length': '76',
16200 silly get     etag: 'W/"4c-869f68fc"',
16200 silly get     vary: 'Accept-Encoding',
16200 silly get     'x-status-cat': 'http://flic.kr/p/aV6jFK',
16200 silly get     date: 'Mon, 24 Apr 2017 23:14:23 GMT',
16200 silly get     connection: 'keep-alive' } ]
16201 silly fetchPackageMetaData Error: user tute2 is not allowed to access package @types/geojson : @types/geojson
16201 silly fetchPackageMetaData     at makeError (/Users/blanchma/.nvm/versions/node/v4.4.3/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
16201 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (/Users/blanchma/.nvm/versions/node/v4.4.3/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:252:14)
16201 silly fetchPackageMetaData     at Request._callback (/Users/blanchma/.nvm/versions/node/v4.4.3/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
16201 silly fetchPackageMetaData     at Request.self.callback (/Users/blanchma/.nvm/versions/node/v4.4.3/lib/node_modules/npm/node_modules/request/request.js:199:22)
16201 silly fetchPackageMetaData     at emitTwo (events.js:87:13)
16201 silly fetchPackageMetaData     at Request.emit (events.js:172:7)
16201 silly fetchPackageMetaData     at Request.<anonymous> (/Users/blanchma/.nvm/versions/node/v4.4.3/lib/node_modules/npm/node_modules/request/request.js:1036:10)
16201 silly fetchPackageMetaData     at emitOne (events.js:82:20)
16201 silly fetchPackageMetaData     at Request.emit (events.js:169:7)
16201 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (/Users/blanchma/.nvm/versions/node/v4.4.3/lib/node_modules/npm/node_modules/request/request.js:963:12)
16201 silly fetchPackageMetaData  error for @types/geojson@^1.0.0 { [Error: user tute2 is not allowed to access package @types/geojson : @types/geojson] pkgid: '@types/geojson', statusCode: 403, code: 'E403' }
16202 silly rollbackFailedOptional Starting
16203 silly rollbackFailedOptional Finishing
16204 silly runTopLevelLifecycles Starting
16205 silly runTopLevelLifecycles Finishing
16206 silly install printInstalled
16207 verbose stack Error: user tute2 is not allowed to access package @types/geojson : @types/geojson
16207 verbose stack     at makeError (/Users/blanchma/.nvm/versions/node/v4.4.3/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
16207 verbose stack     at CachingRegistryClient.<anonymous> (/Users/blanchma/.nvm/versions/node/v4.4.3/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:252:14)
16207 verbose stack     at Request._callback (/Users/blanchma/.nvm/versions/node/v4.4.3/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
16207 verbose stack     at Request.self.callback (/Users/blanchma/.nvm/versions/node/v4.4.3/lib/node_modules/npm/node_modules/request/request.js:199:22)
16207 verbose stack     at emitTwo (events.js:87:13)
16207 verbose stack     at Request.emit (events.js:172:7)
16207 verbose stack     at Request.<anonymous> (/Users/blanchma/.nvm/versions/node/v4.4.3/lib/node_modules/npm/node_modules/request/request.js:1036:10)
16207 verbose stack     at emitOne (events.js:82:20)
16207 verbose stack     at Request.emit (events.js:169:7)
16207 verbose stack     at IncomingMessage.<anonymous> (/Users/blanchma/.nvm/versions/node/v4.4.3/lib/node_modules/npm/node_modules/request/request.js:963:12)
16208 verbose statusCode 403
16209 verbose pkgid @types/geojson
16210 verbose cwd /Users/blanchma/workspace/backend
16211 error Darwin 15.6.0
16212 error argv "/Users/blanchma/.nvm/versions/node/v4.4.3/bin/node" "/Users/blanchma/.nvm/versions/node/v4.4.3/bin/npm" "install"
16213 error node v4.4.3
16214 error npm  v3.8.6
16215 error code E403
16216 error user tute2 is not allowed to access package @types/geojson : @types/geojson
16217 error If you need help, you may report this error at:
16217 error     <https://github.com/npm/npm/issues>
16218 verbose exit [ 1, true ]
```

No idea what's failing here. I did npm install several times today and in the last deploy. I have this error.

**Comment by KenanY** [comment]
Looks like this error is coming from your registry instance, not from `npm` itself. Perhaps you have to [authenticate](https://docs.npmjs.com/misc/scope#associating-a-scope-with-a-registry) yourself with the scope in question?

**Comment by aruizca** [comment]
We are having this very same issue just now

**Comment by andylongstaffe** [comment]
We're getting the same issue aswell. Seeing this on multiple machines and seemed to work ok yesterday...

**Comment by aruizca** [comment]
It could be a problem with our sinopia npm server but it was working fine until yesterday:
```
8316 http 403 https://npm.whatever.com:4873/@types%2fgeojson
8317 verbose headers { 'x-powered-by': 'Sinopia/1.0.1',
8317 verbose headers   'content-type': 'application/json; charset=utf-8',
8317 verbose headers   'content-length': '53',
8317 verbose headers   etag: 'W/"35-f319f5ac"',
8317 verbose headers   vary: 'Accept-Encoding',
8317 verbose headers   'x-status-cat': 'http://flic.kr/p/aV6jFK',
8317 verbose headers   date: 'Tue, 25 Apr 2017 09:40:46 GMT',
8317 verbose headers   connection: 'keep-alive' }
8318 silly get cb [ 403,
8318 silly get   { 'x-powered-by': 'Sinopia/1.0.1',
8318 silly get     'content-type': 'application/json; charset=utf-8',
8318 silly get     'content-length': '53',
8318 silly get     etag: 'W/"35-f319f5ac"',
8318 silly get     vary: 'Accept-Encoding',
8318 silly get     'x-status-cat': 'http://flic.kr/p/aV6jFK',
8318 silly get     date: 'Tue, 25 Apr 2017 09:40:46 GMT',
8318 silly get     connection: 'keep-alive' } ]
8319 silly fetchPackageMetaData Error: user angel not allowed to access it : @types/geojson
8319 silly fetchPackageMetaData     at makeError (/Users/aruizca/.nvm/versions/node/v6.9.2/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:302:12)
8319 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (/Users/aruizca/.nvm/versions/node/v6.9.2/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:290:14)
8319 silly fetchPackageMetaData     at Request._callback (/Users/aruizca/.nvm/versions/node/v6.9.2/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:210:14)
8319 silly fetchPackageMetaData     at Request.self.callback (/Users/aruizca/.nvm/versions/node/v6.9.2/lib/node_modules/npm/node_modules/request/request.js:187:22)
8319 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
8319 silly fetchPackageMetaData     at Request.emit (events.js:191:7)
8319 silly fetchPackageMetaData     at Request.<anonymous> (/Users/aruizca/.nvm/versions/node/v6.9.2/lib/node_modules/npm/node_modules/request/request.js:1048:10)
8319 silly fetchPackageMetaData     at emitOne (events.js:96:13)
8319 silly fetchPackageMetaData     at Request.emit (events.js:188:7)
8319 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (/Users/aruizca/.nvm/versions/node/v6.9.2/lib/node_modules/npm/node_modules/request/request.js:969:12)
8319 silly fetchPackageMetaData  error for @types/geojson@^1.0.0 { Error: user angel not allowed to access it : @types/geojson
8319 silly fetchPackageMetaData     at makeError (/Users/aruizca/.nvm/versions/node/v6.9.2/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:302:12)
8319 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (/Users/aruizca/.nvm/versions/node/v6.9.2/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:290:14)
8319 silly fetchPackageMetaData     at Request._callback (/Users/aruizca/.nvm/versions/node/v6.9.2/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:210:14)
8319 silly fetchPackageMetaData     at Request.self.callback (/Users/aruizca/.nvm/versions/node/v6.9.2/lib/node_modules/npm/node_modules/request/request.js:187:22)
8319 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
8319 silly fetchPackageMetaData     at Request.emit (events.js:191:7)
8319 silly fetchPackageMetaData     at Request.<anonymous> (/Users/aruizca/.nvm/versions/node/v6.9.2/lib/node_modules/npm/node_modules/request/request.js:1048:10)
8319 silly fetchPackageMetaData     at emitOne (events.js:96:13)
8319 silly fetchPackageMetaData     at Request.emit (events.js:188:7)
8319 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (/Users/aruizca/.nvm/versions/node/v6.9.2/lib/node_modules/npm/node_modules/request/request.js:969:12) pkgid: '@types/geojson', statusCode: 403, code: 'E403' }
8320 silly rollbackFailedOptional Starting
8321 silly rollbackFailedOptional Finishing
8322 silly runTopLevelLifecycles Finishing
8323 silly install printInstalled
8324 verbose stack Error: user angel not allowed to access it : @types/geojson
8324 verbose stack     at makeError (/Users/aruizca/.nvm/versions/node/v6.9.2/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:302:12)
8324 verbose stack     at CachingRegistryClient.<anonymous> (/Users/aruizca/.nvm/versions/node/v6.9.2/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:290:14)
8324 verbose stack     at Request._callback (/Users/aruizca/.nvm/versions/node/v6.9.2/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:210:14)
8324 verbose stack     at Request.self.callback (/Users/aruizca/.nvm/versions/node/v6.9.2/lib/node_modules/npm/node_modules/request/request.js:187:22)
8324 verbose stack     at emitTwo (events.js:106:13)
8324 verbose stack     at Request.emit (events.js:191:7)
8324 verbose stack     at Request.<anonymous> (/Users/aruizca/.nvm/versions/node/v6.9.2/lib/node_modules/npm/node_modules/request/request.js:1048:10)
8324 verbose stack     at emitOne (events.js:96:13)
8324 verbose stack     at Request.emit (events.js:188:7)
8324 verbose stack     at IncomingMessage.<anonymous> (/Users/aruizca/.nvm/versions/node/v6.9.2/lib/node_modules/npm/node_modules/request/request.js:969:12)
8325 verbose statusCode 403
8326 verbose pkgid @types/geojson
8327 verbose cwd /Users/aruizca/workspace/whatever/whatever/cloud
8328 error Darwin 16.5.0
8329 error argv "/Users/aruizca/.nvm/versions/node/v6.9.2/bin/node" "/Users/aruizca/.nvm/versions/node/v6.9.2/bin/npm" "install"
8330 error node v6.9.2
8331 error npm  v3.10.9
8332 error code E403
8333 error user angel not allowed to access it : @types/geojson
8334 error If you need help, you may report this error at:
8334 error     <https://github.com/npm/npm/issues>
8335 verbose exit [ 1, true ]
```

**Comment by andylongstaffe** [comment]
We fixed our private npm repository by explicitly specifiying permissions for @types modules and adding an encoding fix, all usefully described in the 'installing and updating code' section of the following https://www.robinhermans.net/hosting-a-private-npm-registry-using-sinopia/
YMMV.

**Comment by aruizca** [comment]
@andylongstaffe Do you mind posting the details please?. To be honest I don't fully understand your workaround. Thanks!

**Comment by aruizca** [comment]
Thanks @andylongstaffe !! It worked for us too! 👍

**Comment by KenanY** [comment]
Closing due to no reply from OP after a month.

**Comment by tplummerfni** [comment]
@andylongstaffe that blog is now set to private.  Any more details you can provide?

**Comment by LitileXueZha** [comment]
Sometimes the npm package administrator maybe published a same version with you.It's in my computer
