### ISSUE TITLE
you do not have permission to publish "x". Are you logged in as the correct user?

### ISSUE THREAD

**Issue by gsundin** [npm/npm#16433]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I cannot publish a new version of a module I manage. I have been recently added to the list of collaborators for the [bean-sdk](https://www.npmjs.com/package/bean-sdk) project, and I have cleared the npm cache, logged in and out and in again, and reset my cli auth tokens on the npm site. I believe this may be a caching issue. I also created my [npm account](https://www.npmjs.com/~gsundin) earlier today.

#### How can the CLI team reproduce the problem?

I have updated the version in `package.json` manually to 0.6.3 (the newest version on the npm registry is 0.6.2). Then I run the commands `npm login`, `npm run build`, and then `npm publish`. I get the following error:

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/gsundin/.nvm/versions/node/v6.10.2/bin/node',
1 verbose cli   '/Users/gsundin/.nvm/versions/node/v6.10.2/bin/npm',
1 verbose cli   'publish' ]
2 info using npm@4.5.0
3 info using node@v6.10.2
4 verbose publish [ '.' ]
5 silly cache add args [ '.', null ]
6 verbose cache add spec .
7 silly cache add parsed spec Result {
7 silly cache add   raw: '.',
7 silly cache add   scope: null,
7 silly cache add   escapedName: null,
7 silly cache add   name: null,
7 silly cache add   rawSpec: '.',
7 silly cache add   spec: '/Users/gsundin/Code/bean-sdk-node-private',
7 silly cache add   type: 'directory' }
8 verbose addLocalDirectory /Users/gsundin/.npm/bean-sdk/0.6.3/package.tgz not in flight; packing
9 verbose correctMkdir /Users/gsundin/.npm correctMkdir not in flight; initializing
10 info lifecycle bean-sdk@0.6.3~prepublish: bean-sdk@0.6.3
11 silly lifecycle bean-sdk@0.6.3~prepublish: no script for prepublish, continuing
12 info lifecycle bean-sdk@0.6.3~prepare: bean-sdk@0.6.3
13 silly lifecycle bean-sdk@0.6.3~prepare: no script for prepare, continuing
14 verbose tar pack [ '/Users/gsundin/.npm/bean-sdk/0.6.3/package.tgz',
14 verbose tar pack   '/Users/gsundin/Code/bean-sdk-node-private' ]
15 verbose tarball /Users/gsundin/.npm/bean-sdk/0.6.3/package.tgz
16 verbose folder /Users/gsundin/Code/bean-sdk-node-private
17 verbose addLocalTarball adding from inside cache /Users/gsundin/.npm/bean-sdk/0.6.3/package.tgz
18 verbose correctMkdir /Users/gsundin/.npm correctMkdir not in flight; initializing
19 silly cache afterAdd bean-sdk@0.6.3
20 verbose afterAdd /Users/gsundin/.npm/bean-sdk/0.6.3/package/package.json not in flight; writing
21 verbose correctMkdir /Users/gsundin/.npm correctMkdir not in flight; initializing
22 verbose afterAdd /Users/gsundin/.npm/bean-sdk/0.6.3/package/package.json written
23 silly publish { name: 'bean-sdk',
23 silly publish   version: '0.6.3',
23 silly publish   description: 'Official Light Blue Bean SDK for Node.js by Punch Through',
23 silly publish   keywords: [ 'bean', 'punchthrough', 'lightblue', 'ble', 'bluetooth', 'noble' ],
23 silly publish   main: 'build/lightblue.js',
23 silly publish   babel: { presets: [ 'es2015' ] },
23 silly publish   bin: { bean: 'build/cli/entry.js' },
23 silly publish   scripts:
23 silly publish    { test: 'mocha --compilers js:babel-register --recursive',
23 silly publish      babel: 'babel src -d build/',
23 silly publish      build: 'python scripts/build' },
23 silly publish   repository:
23 silly publish    { type: 'git',
23 silly publish      url: 'git+https://github.com/PunchThrough/bean-sdk-node.git' },
23 silly publish   author: { name: 'Stephen Stack' },
23 silly publish   license: 'ISC',
23 silly publish   bugs: { url: 'https://github.com/PunchThrough/bean-sdk-node/issues' },
23 silly publish   homepage: 'https://github.com/PunchThrough/bean-sdk-node#readme',
23 silly publish   dependencies:
23 silly publish    { async: '*',
23 silly publish      commander: '*',
23 silly publish      crc: '^3.4.0',
23 silly publish      'fs-extra': '^0.30.0',
23 silly publish      'js-yaml': '*',
23 silly publish      noble: '1.7.0',
23 silly publish      queue: '^4.0.0',
23 silly publish      sleep: '^3.0.1',
23 silly publish      'sprintf-js': '^1.0.3',
23 silly publish      winston: '^2.2.0' },
23 silly publish   devDependencies:
23 silly publish    { 'babel-cli': '^6.11.4',
23 silly publish      'babel-preset-es2015': '^6.13.2',
23 silly publish      'babel-register': '^6.14.0',
23 silly publish      mocha: '*',
23 silly publish      sinon: '^1.17.4' },
23 silly publish   readme: '# Bean SDK for Node.js\n\n[![Circle CI](https://circleci.com/gh/PunchThrough/bean-sdk-node/tree/master.svg?style=shield&circle-token=:circle-token)](https://circleci.com/gh/PunchThrough/bean-sdk-node/tree/master)\n\nWelcome to the Node.js SDK and CLI source code repo for the LightBlue Bean/Bean+.\n\nDocumentation:\n\n* [Project Overview](https://punchthrough.com/bean/guides/node-sdk/overview/)\n* [Developer Guide](docs/developer.md)\n* [Release Notes](CHANGELOG.md)\n\n# Installation\n\nFollow one of our detailed install guides!\n\n* [OS X](https://punchthrough.com/bean/guides/node-sdk/install-osx)\n* [Linux](https://punchthrough.com/bean/guides/node-sdk/install-linux)\n* [Windows](https://punchthrough.com/bean/guides/node-sdk/install-windows)\n* [Rasperry Pi](https://punchthrough.com/bean/guides/node-sdk/install-rpi)\n\n# CLI\n\nThis project ships with a full-featured CLI that can talk to the Bean/Bean+ without needing to write a single line of code.\n\n* [CLI Tutorial](https://punchthrough.com/bean/guides/getting-started/cli-loader/)\n\n# SDK/Library\n\nAPI reference and examples coming soon!\n\nBasic usage can be found in `examples/set_led.js`\n',
23 silly publish   readmeFilename: 'README.md',
23 silly publish   gitHead: 'e97144817b614569641fa10498a11f4254fcf39d',
23 silly publish   _id: 'bean-sdk@0.6.3',
23 silly publish   _shasum: '822786223872ef297b5918cd350b566770b84150',
23 silly publish   _from: '.' }
24 info lifecycle bean-sdk@0.6.3~prepublishOnly: bean-sdk@0.6.3
25 silly lifecycle bean-sdk@0.6.3~prepublishOnly: no script for prepublishOnly, continuing
26 verbose getPublishConfig undefined
27 silly mapToRegistry name bean-sdk
28 silly mapToRegistry using default registry
29 silly mapToRegistry registry https://registry.npmjs.org/
30 silly mapToRegistry data Result {
30 silly mapToRegistry   raw: 'bean-sdk',
30 silly mapToRegistry   scope: null,
30 silly mapToRegistry   escapedName: 'bean-sdk',
30 silly mapToRegistry   name: 'bean-sdk',
30 silly mapToRegistry   rawSpec: '',
30 silly mapToRegistry   spec: 'latest',
30 silly mapToRegistry   type: 'tag' }
31 silly mapToRegistry uri https://registry.npmjs.org/bean-sdk
32 verbose publish registryBase https://registry.npmjs.org/
33 silly publish uploading /Users/gsundin/.npm/bean-sdk/0.6.3/package.tgz
34 verbose request uri https://registry.npmjs.org/bean-sdk
35 verbose request sending authorization for write operation
36 info attempt registry request try #1 at 2:21:11 PM
37 verbose request using bearer token for auth
38 verbose request id 2b07f6e2be722c69
39 http request PUT https://registry.npmjs.org/bean-sdk
40 http 403 https://registry.npmjs.org/bean-sdk
41 verbose headers { 'content-type': 'application/json',
41 verbose headers   'cache-control': 'max-age=300',
41 verbose headers   'content-length': '102',
41 verbose headers   'accept-ranges': 'bytes',
41 verbose headers   date: 'Mon, 24 Apr 2017 19:21:17 GMT',
41 verbose headers   via: '1.1 varnish',
41 verbose headers   connection: 'keep-alive',
41 verbose headers   'x-served-by': 'cache-ord1733-ORD',
41 verbose headers   'x-cache': 'MISS',
41 verbose headers   'x-cache-hits': '0',
41 verbose headers   'x-timer': 'S1493061671.301030,VS0,VE6001',
41 verbose headers   vary: 'Accept-Encoding' }
42 verbose request invalidating /Users/gsundin/.npm/registry.npmjs.org/bean-sdk on PUT
43 error publish Failed PUT 403
44 verbose stack Error: you do not have permission to publish "bean-sdk". Are you logged in as the correct user? : bean-sdk
44 verbose stack     at makeError (/Users/gsundin/.nvm/versions/node/v6.10.2/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:308:12)
44 verbose stack     at CachingRegistryClient.<anonymous> (/Users/gsundin/.nvm/versions/node/v6.10.2/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:296:14)
44 verbose stack     at Request._callback (/Users/gsundin/.nvm/versions/node/v6.10.2/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:216:14)
44 verbose stack     at Request.self.callback (/Users/gsundin/.nvm/versions/node/v6.10.2/lib/node_modules/npm/node_modules/request/request.js:188:22)
44 verbose stack     at emitTwo (events.js:106:13)
44 verbose stack     at Request.emit (events.js:191:7)
44 verbose stack     at Request.<anonymous> (/Users/gsundin/.nvm/versions/node/v6.10.2/lib/node_modules/npm/node_modules/request/request.js:1171:10)
44 verbose stack     at emitOne (events.js:96:13)
44 verbose stack     at Request.emit (events.js:188:7)
44 verbose stack     at IncomingMessage.<anonymous> (/Users/gsundin/.nvm/versions/node/v6.10.2/lib/node_modules/npm/node_modules/request/request.js:1091:12)
45 verbose statusCode 403
46 verbose pkgid bean-sdk
47 verbose cwd /Users/gsundin/Code/bean-sdk-node-private
48 verbose Darwin 15.6.0
49 verbose argv "/Users/gsundin/.nvm/versions/node/v6.10.2/bin/node" "/Users/gsundin/.nvm/versions/node/v6.10.2/bin/npm" "publish"
50 verbose node v6.10.2
51 verbose npm  v4.5.0
52 error code E403
53 error you do not have permission to publish "bean-sdk". Are you logged in as the correct user? : bean-sdk
54 verbose exit [ 1, true ]
```

### supporting information:

 - `npm -v` prints: 4.5.0
 - `node -v` prints: v6.10.2
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: OS X

**Comment by jeroenouw** [comment]
@gsundin Maybe run the same thing as a administrator?

**Comment by gsundin** [comment]
@jeroenouw Thanks for the tip! However, I don't think sudo would have worked any differently because my `npm` credentials were needed, not my local machine credentials.

In any case, I was able to publish successfully the next day. It seems there is some caching that was just not updated for a while. Coincidentally, my npm gravatar has also not updated for a few days, but that's not a big deal.
