### ISSUE TITLE
NPM login producing invalid token - whoami returns 401 immediately, cannot access private repos

### ISSUE THREAD

**Issue by seanadkinson** [npm/npm#16448]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I can successfully `npm login`, and I see the token in my profile on npmjs.org, but I cannot access any private repos, and `npm whoami` returns 401 immediately after login.

#### How can the CLI team reproduce the problem?

For me, try `npm login` then `npm whoami`

### supporting information:

Verbose terminal output:

```
$ npm login --verbose
npm info it worked if it ends with ok
npm verb cli [ '/Users/seanadkinson/.nvm/versions/node/v4.2.1/bin/node',
npm verb cli   '/Users/seanadkinson/.nvm/versions/node/v4.2.1/bin/npm',
npm verb cli   'login',
npm verb cli   '--verbose' ]
npm info using npm@2.14.7
npm info using node@v4.2.1
Username: provata
Password: 
Email: (this IS public) dev@provatahealth.com
npm verb adduser before first PUT { _id: 'org.couchdb.user:provata',
npm verb adduser   name: 'provata',
npm verb adduser   password: 'XXXXX',
npm verb adduser   email: 'dev@provatahealth.com',
npm verb adduser   type: 'user',
npm verb adduser   roles: [],
npm verb adduser   date: '2017-04-26T17:49:16.058Z' }
npm verb request uri https://registry.npmjs.org/-/user/org.couchdb.user:provata
npm verb request new user, so can't send auth
npm info attempt registry request try #1 at 10:49:16 AM
npm verb request id 8b5d87bb5c2e7d55
npm http request PUT https://registry.npmjs.org/-/user/org.couchdb.user:provata
npm http 201 https://registry.npmjs.org/-/user/org.couchdb.user:provata
npm verb headers { 'content-type': 'application/json',
npm verb headers   'cache-control': 'max-age=300',
npm verb headers   'content-length': '127',
npm verb headers   'accept-ranges': 'bytes',
npm verb headers   date: 'Wed, 26 Apr 2017 17:49:16 GMT',
npm verb headers   via: '1.1 varnish',
npm verb headers   connection: 'keep-alive',
npm verb headers   'x-served-by': 'cache-sea1048-SEA',
npm verb headers   'x-cache': 'MISS',
npm verb headers   'x-cache-hits': '0',
npm verb headers   'x-timer': 'S1493228956.134343,VS0,VE132',
npm verb headers   vary: 'Accept-Encoding' }
npm verb request invalidating /Users/seanadkinson/.npm/registry.npmjs.org/-/user/org.couchdb.user_3Aprovata on PUT
npm info adduser Authorized user provata
npm verb exit [ 0, true ]
npm info ok 

$ npm whoami --verbose
npm info it worked if it ends with ok
npm verb cli [ '/Users/seanadkinson/.nvm/versions/node/v4.2.1/bin/node',
npm verb cli   '/Users/seanadkinson/.nvm/versions/node/v4.2.1/bin/npm',
npm verb cli   'whoami',
npm verb cli   '--verbose' ]
npm info using npm@2.14.7
npm info using node@v4.2.1
npm verb request uri https://registry.npmjs.org/-/whoami
npm verb request no auth needed
npm info attempt registry request try #1 at 10:49:36 AM
npm verb request using bearer token for auth
npm verb request id 25b387dc3b63e1ca
npm http request GET https://registry.npmjs.org/-/whoami
npm http 401 https://registry.npmjs.org/-/whoami
npm verb headers { 'content-type': 'application/json',
npm verb headers   'cache-control': 'max-age=300',
npm verb headers   'content-length': '2',
npm verb headers   'accept-ranges': 'bytes',
npm verb headers   date: 'Wed, 26 Apr 2017 17:49:36 GMT',
npm verb headers   via: '1.1 varnish',
npm verb headers   connection: 'keep-alive',
npm verb headers   'x-served-by': 'cache-sea1042-SEA',
npm verb headers   'x-cache': 'MISS',
npm verb headers   'x-cache-hits': '0',
npm verb headers   'x-timer': 'S1493228977.593679,VS0,VE95',
npm verb headers   vary: 'Accept-Encoding' }
npm verb stack Error: Registry returned 401 for GET on https://registry.npmjs.org/-/whoami
npm verb stack     at makeError (/Users/seanadkinson/.nvm/versions/node/v4.2.1/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
npm verb stack     at CachingRegistryClient.<anonymous> (/Users/seanadkinson/.nvm/versions/node/v4.2.1/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:242:14)
npm verb stack     at Request._callback (/Users/seanadkinson/.nvm/versions/node/v4.2.1/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
npm verb stack     at Request.self.callback (/Users/seanadkinson/.nvm/versions/node/v4.2.1/lib/node_modules/npm/node_modules/request/request.js:198:22)
npm verb stack     at emitTwo (events.js:87:13)
npm verb stack     at Request.emit (events.js:172:7)
npm verb stack     at Request.<anonymous> (/Users/seanadkinson/.nvm/versions/node/v4.2.1/lib/node_modules/npm/node_modules/request/request.js:1063:14)
npm verb stack     at emitOne (events.js:82:20)
npm verb stack     at Request.emit (events.js:169:7)
npm verb stack     at IncomingMessage.<anonymous> (/Users/seanadkinson/.nvm/versions/node/v4.2.1/lib/node_modules/npm/node_modules/request/request.js:1009:12)
npm verb statusCode 401
npm verb cwd /Users/seanadkinson/code/hthu-web
npm ERR! Darwin 16.5.0
npm ERR! argv "/Users/seanadkinson/.nvm/versions/node/v4.2.1/bin/node" "/Users/seanadkinson/.nvm/versions/node/v4.2.1/bin/npm" "whoami" "--verbose"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code E401

npm ERR! Registry returned 401 for GET on https://registry.npmjs.org/-/whoami
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm verb exit [ 1, true ]

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/seanadkinson/code/hthu-web/npm-debug.log
```

**Comment by seanadkinson** [comment]
```
$ cat ~/.npmrc
//registry.npmjs.org/:_authToken=TOKEN
```

And I can see `TOKEN` in my profile on npmjs.org

**Comment by KenanY** [comment]
Just in case, does this also happen with the latest stable release of `npm`?

**Comment by seanadkinson** [comment]
Switched to the latest version, and it worked.  Switched back to 4.2.1, and it is also working now.  Not sure whether the issue was on my end, or perhaps some incorrect caching on yours, but I'm good to go now.  Thanks!

**Comment by seanadkinson** [comment]
@KenanY Actually started happening again, so I was digging deeper into what was different from before and after it was working a moment ago, and wanted to update this thread in case someone else has this issue.  

I'm really not sure how it got there, but there was an `.npmrc` in the current directory of the terminal window I was in.  I guess `npm` looks in the current directory first?  This `.npmrc` had an invalid token.  It is confusing that `npm` will use the token in the current directory, but `npm login` updates only `~/.npmrc`.  Some output may be useful, but not sure.

Anyway, confusing issue, but as long as `npm` is supposed to check the current directory first, looks like it is working as expected.  Thanks again.

**Comment by ruoru** [comment]
i have a same question

```
➜  studio-web git:(add/membership-fields) npm login
Username: ruoru
Password:
Email: (this IS public) cruoru@gmail.com
Logged in as ruoru on https://registry.npmjs.org/.
➜  studio-web git:(add/membership-fields) npm whoami
npm ERR! Darwin 16.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "whoami"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code E401

npm ERR! Registry returned 401 for GET on https://registry.npmjs.org/-/whoami
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ruoru/Project/studio-web/npm-debug.log
```

i solved my question, because my project file have another .npmrc, what a fuck! and my english is very bad i can`t understand @seanadkinson what`s mean, when i solved question i kown what`s he mean.
