### ISSUE TITLE
Installing CLI error

### ISSUE THREAD

**Issue by AkashEdakkalathur** [npm/npm#16559]
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '--save-dev',
1 verbose cli   '@angular/cli@latest' ]
2 info using npm@4.2.0
3 info using node@v7.10.0
4 verbose config Skipping project config: C:\Users\1034850/.npmrc. (matches userconfig)
5 silly loadCurrentTree Starting
6 silly install loadCurrentTree
7 silly install readLocalPackageData
8 silly fetchPackageMetaData @angular/cli@latest
9 silly fetchNamedPackageData @angular/cli
10 silly mapToRegistry name @angular/cli
11 silly mapToRegistry scope (from package name) @angular
12 verbose mapToRegistry no registry URL found in name for scope @angular
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry data Result {
15 silly mapToRegistry   raw: '@angular/cli',
15 silly mapToRegistry   scope: '@angular',
15 silly mapToRegistry   escapedName: '@angular%2fcli',
15 silly mapToRegistry   name: '@angular/cli',
15 silly mapToRegistry   rawSpec: '',
15 silly mapToRegistry   spec: 'latest',
15 silly mapToRegistry   type: 'tag' }
16 silly mapToRegistry uri https://registry.npmjs.org/@angular%2fcli
17 verbose request uri https://registry.npmjs.org/@angular%2fcli
18 verbose request no auth needed
19 info attempt registry request try #1 at 10:44:43 AM
20 verbose request id 066c6bac4c58af09
21 verbose etag W/"590a6cea-e4cd"
22 verbose lastModified Wed, 03 May 2017 23:51:06 GMT
23 http request GET https://registry.npmjs.org/@angular%2fcli
24 http 304 https://registry.npmjs.org/@angular%2fcli
25 verbose headers { date: 'Mon, 08 May 2017 05:14:43 GMT',
25 verbose headers   via: '1.1 varnish',
25 verbose headers   'cache-control': 'max-age=0',
25 verbose headers   etag: 'W/"590a6cea-e4cd"',
25 verbose headers   age: '0',
25 verbose headers   connection: 'close',
25 verbose headers   'x-served-by': 'cache-lhr6330-LHR',
25 verbose headers   'x-cache': 'MISS',
25 verbose headers   'x-cache-hits': '0',
25 verbose headers   'x-timer': 'S1494220484.898861,VS0,VE580',
25 verbose headers   vary: 'Accept-Encoding' }
26 silly get cb [ 304,
26 silly get   { date: 'Mon, 08 May 2017 05:14:43 GMT',
26 silly get     via: '1.1 varnish',
26 silly get     'cache-control': 'max-age=0',
26 silly get     etag: 'W/"590a6cea-e4cd"',
26 silly get     age: '0',
26 silly get     connection: 'close',
26 silly get     'x-served-by': 'cache-lhr6330-LHR',
26 silly get     'x-cache': 'MISS',
26 silly get     'x-cache-hits': '0',
26 silly get     'x-timer': 'S1494220484.898861,VS0,VE580',
26 silly get     vary: 'Accept-Encoding' } ]
27 verbose etag https://registry.npmjs.org/@angular%2fcli from cache
28 verbose get saving @angular/cli to C:\Users\1034850\AppData\Roaming\npm-cache\registry.npmjs.org\_40angular_252fcli\.cache.json
29 verbose correctMkdir C:\Users\1034850\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
30 silly install normalizeTree
31 silly loadCurrentTree Finishing
32 silly loadIdealTree Starting
33 silly install loadIdealTree
34 silly cloneCurrentTree Starting
35 silly install cloneCurrentTreeToIdealTree
36 silly cloneCurrentTree Finishing
37 silly loadShrinkwrap Starting
38 silly install loadShrinkwrap
39 silly loadShrinkwrap Finishing
40 silly loadAllDepsIntoIdealTree Starting
41 silly install loadAllDepsIntoIdealTree
42 silly rollbackFailedOptional Starting
43 silly rollbackFailedOptional Finishing
44 silly runTopLevelLifecycles Finishing
45 silly install printInstalled
46 verbose stack Error: Refusing to install package with name "@angular/cli" under a package
46 verbose stack also called "@angular/cli". Did you name your project the same
46 verbose stack as the dependency you're installing?
46 verbose stack
46 verbose stack For more information, see:
46 verbose stack     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>
46 verbose stack     at checkSelf (C:\Program Files\nodejs\node_modules\npm\lib\install\validate-args.js:53:14)
46 verbose stack     at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
46 verbose stack     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
46 verbose stack     at chain (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
46 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install\validate-args.js:16:5
46 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:35
46 verbose stack     at Array.forEach (native)
46 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:11
46 verbose stack     at Array.forEach (native)
46 verbose stack     at asyncMap (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:51:8)
47 verbose cwd C:\Users\1034850
48 error Windows_NT 10.0.10240
49 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save-dev" "@angular/cli@latest"
50 error node v7.10.0
51 error npm  v4.2.0
52 error code ENOSELF
53 error Refusing to install package with name "@angular/cli" under a package
53 error also called "@angular/cli". Did you name your project the same
53 error as the dependency you're installing?
53 error
53 error For more information, see:
53 error     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>
54 error If you need help, you may report this error at:
54 error     <https://github.com/npm/npm/issues>
55 verbose exit [ 1, true ]
```

**Comment by AkashEdakkalathur** [comment]
This on cmd

$ npm install --save-dev @angular/cli@latest
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save-dev" "@angular/cli@latest"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ENOSELF

npm ERR! Refusing to install package with name "@angular/cli" under a package
npm ERR! also called "@angular/cli". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR!
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\1034850\AppData\Roaming\npm-cache\_logs\2017-05-08T06_57_39_719Z-debug.log

**Comment by zkat** [comment]
```
npm ERR! Refusing to install package with name "@angular/cli" under a package
npm ERR! also called "@angular/cli". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR!
npm ERR! For more information, see:
npm ERR! https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm
```

This explains the problem as well as I can think to. You can't install a package with a certain name inside a package with that same name. Based on what the package is, I assume what you actually want is `npm i -g @angular/cli`.

Closing this.
