### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by dekavadia** [npm/npm#16560]
Getting error while installing any package via npm in windows 8.1.

ERROR : 

```
error Windows_NT 6.3.9600
error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "typescript"
error node v7.10.0
error npm  v4.2.0
error Cannot read property 'path' of null
```

LOG : 

[2017-05-08T06_25_51_471Z-debug.txt](https://github.com/npm/npm/files/982535/2017-05-08T06_25_51_471Z-debug.txt)

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'typescript' ]
2 info using npm@4.2.0
3 info using node@v7.10.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData typescript
8 silly fetchNamedPackageData typescript
9 silly mapToRegistry name typescript
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry http://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'typescript',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'typescript',
12 silly mapToRegistry   name: 'typescript',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri http://registry.npmjs.org/typescript
14 verbose request uri http://registry.npmjs.org/typescript
15 verbose request no auth needed
16 info attempt registry request try #1 at 11:54:41 AM
17 verbose request id a612436a64a00392
18 http request GET http://registry.npmjs.org/typescript
19 info retry will retry, error on last attempt: Error: Invalid protocol: null
20 info attempt registry request try #2 at 11:54:51 AM
21 http request GET http://registry.npmjs.org/typescript
22 info retry will retry, error on last attempt: Error: Invalid protocol: null
23 info attempt registry request try #3 at 11:55:51 AM
24 http request GET http://registry.npmjs.org/typescript
25 silly fetchPackageMetaData Error: Invalid protocol: null
25 silly fetchPackageMetaData     at Request.init (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:459:31)
25 silly fetchPackageMetaData     at new Request (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:128:8)
25 silly fetchPackageMetaData     at request (C:\Program Files\nodejs\node_modules\npm\node_modules\request\index.js:54:10)
25 silly fetchPackageMetaData     at CachingRegistryClient.makeRequest (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:160:13)
25 silly fetchPackageMetaData     at C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:68:17
25 silly fetchPackageMetaData     at RetryOperation._fn (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\attempt.js:18:5)
25 silly fetchPackageMetaData     at Timeout._onTimeout (C:\Program Files\nodejs\node_modules\npm\node_modules\retry\lib\retry_operation.js:68:10)
25 silly fetchPackageMetaData     at ontimeout (timers.js:386:14)
25 silly fetchPackageMetaData     at tryOnTimeout (timers.js:250:5)
25 silly fetchPackageMetaData     at Timer.listOnTimeout (timers.js:214:5)
25 silly fetchPackageMetaData  error for typescript Error: Invalid protocol: null
25 silly fetchPackageMetaData     at Request.init (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:459:31)
25 silly fetchPackageMetaData     at new Request (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:128:8)
25 silly fetchPackageMetaData     at request (C:\Program Files\nodejs\node_modules\npm\node_modules\request\index.js:54:10)
25 silly fetchPackageMetaData     at CachingRegistryClient.makeRequest (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:160:13)
25 silly fetchPackageMetaData     at C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:68:17
25 silly fetchPackageMetaData     at RetryOperation._fn (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\attempt.js:18:5)
25 silly fetchPackageMetaData     at Timeout._onTimeout (C:\Program Files\nodejs\node_modules\npm\node_modules\retry\lib\retry_operation.js:68:10)
25 silly fetchPackageMetaData     at ontimeout (timers.js:386:14)
25 silly fetchPackageMetaData     at tryOnTimeout (timers.js:250:5)
25 silly fetchPackageMetaData     at Timer.listOnTimeout (timers.js:214:5)
26 silly rollbackFailedOptional Starting
27 verbose stack TypeError: Cannot read property 'path' of null
27 verbose stack     at Installer.rollbackFailedOptional (C:\Program Files\nodejs\node_modules\npm\lib\install.js:511:29)
27 verbose stack     at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
27 verbose stack     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
27 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:18:7
27 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install.js:337:5
27 verbose stack     at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
27 verbose stack     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
27 verbose stack     at chain (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
27 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install.js:294:5
27 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:16:22
28 verbose cwd C:\Users\sumit.dekavadiya.st
29 error Windows_NT 6.3.9600
30 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "typescript"
31 error node v7.10.0
32 error npm  v4.2.0
33 error Cannot read property 'path' of null
34 error If you need help, you may report this error at:
34 error     <https://github.com/npm/npm/issues>
35 verbose exit [ 1, true ]
```

Please help & guide for the same with proper solution.

**Comment by legodude17** [comment]
Could you upload the npm-debug.log as a plaintext file to https://gist.github.com/ and post a link to it here?
