### ISSUE TITLE
E/downloader - { Error: unable to get local issuer certificate

### ISSUE THREAD

**Issue by phil123456** [npm/npm#16572]
I know there are already opened issues for this , but none of them provide any solutions

#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### How can the CLI team reproduce the problem?

just npm install 

for one dependency it gives

```
[08:37:00] E/downloader - { Error: unable to get local issuer certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1079:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:603:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:433:38) code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY' }
```

I tried these with no luck ( user , pass and proxyadress are not provided here )

```
SET HTTP_PROXY=http://user:pass@proxyadress:8080
SET HTTPS_PROXY=http://user:pass@proxyadress:8080
npm config set proxy http://user:pass@proxyadress:8080
npm config set https-proxy http://user:pass@proxyadress:8080
npm config set strict-ssl false
npm config set registry http://registry.npmjs.org/

```

### supporting information:

 - `npm -v` prints: 3.10.9
 - `node -v` prints: 6.9.2
 - `npm config get registry` prints: http://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: win 7 64
 - Network issues:
   - Geographic location where npm was run:
   - [x ] I use a proxy to connect to the npm registry.
   - [x ] I use a proxy to connect to the web.
   - [x ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
AFAIK, that error is not produced my `npm`.

**Comment by phil123456** [comment]
ok but how do I solve this ?

**Comment by legodude17** [comment]
You will have to ask whoever produced that error.

**Comment by KenanY** [comment]
Re-iterating what's in [Troubleshooting](https://github.com/npm/npm/wiki/Troubleshooting):

> ```
> npm ERR! code UNABLE_TO_GET_ISSUER_CERT_LOCALLY
> ```
> 
> This error means that there's a TLS certificate in the chain that is signed by
> an unknown certificate authority (CA). Presumably, this is the certificate used
> by one's HTTPS proxy. The solution is to configure the
> [`cafile`](https://docs.npmjs.com/misc/config#cafile) value:
> 
> ``` bash
> $ npm config set cafile /path/to/your/file.pem
> ```

**Comment by phil123456** [comment]
but how come it works for the other packages, why and how am I supposed to get the certificate ?

the debug log is strangely empty

all I got are these infos in the command line

```
> app@0.0.0 postinstall D:\WORK\ANGULAR\AccentivCatalogBackend
> npm run webdriver-update


> app@0.0.0 webdriver-update D:\WORK\ANGULAR\AccentivCatalogBackend
> webdriver-manager update

[07:48:51] I/downloader - geckodriver: downloading version v0.11.1
[07:48:51] I/downloader - curl -o D:\WORK\ANGULAR\AccentivCatalogBackend\node_modules\protractor\node_modules\webdriver-manager\selenium/geckodriver-v0.11.1-win64.zip https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geck
odriver-v0.11.1-win64.zip
[07:48:51] E/downloader - { Error: unable to get local issuer certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1079:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:603:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:433:38) code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY' }
[07:48:51] I/update - chromedriver: file exists D:\WORK\ANGULAR\AccentivCatalogBackend\node_modules\protractor\node_modules\webdriver-manager\selenium\chromedriver_2.26win32.zip
[07:48:51] I/update - chromedriver: unzipping chromedriver_2.26win32.zip
[07:48:52] I/update - chromedriver: v2.26 up to date
[07:48:52] I/update - selenium standalone: file exists D:\WORK\ANGULAR\AccentivCatalogBackend\node_modules\protractor\node_modules\webdriver-manager\selenium\selenium-server-standalone-2.53.1.jar
[07:48:52] I/update - selenium standalone: v2.53.1 up to date
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN angular2-cookie@1.2.6 requires a peer of @angular/common@^2.0.0 but none was installed.
npm WARN angular2-cookie@1.2.6 requires a peer of @angular/core@^2.0.0 but none was installed.
npm WARN app@0.0.0 No description
npm WARN app@0.0.0 No repository field.
```

**Comment by phil123456** [comment]
hello ?
