### ISSUE TITLE
Can not install jade express in nodejs

### ISSUE THREAD

**Issue by tranluong** [npm/npm#16591]
#### I have problem when start express in centos 7

```
Error: Cannot find module 'jade'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at new View (/var/www/php_traning/express/nodetest/node_modules/express/lib/view.js:80:30)
    at Function.render (/var/www/php_traning/express/nodetest/node_modules/express/lib/application.js:570:12)
    at ServerResponse.render (/var/www/php_traning/express/nodetest/node_modules/express/lib/response.js:966:7)
    at /var/www/php_traning/express/nodetest/app.js:43:7
    at Layer.handle_error (/var/www/php_traning/express/nodetest/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/var/www/php_traning/express/nodetest/node_modules/express/lib/router/index.js:315:13)
```

Please help fix it
Thanks .

**Comment by Airboy** [comment]
Could you please add the content of your `app.js` file and `package.json` ?

**Comment by tranluong** [comment]
#### app.js file
```
var express = require('express');
var path = require('path');
var favicon = require('serve-favicon');
var logger = require('morgan');
var cookieParser = require('cookie-parser');
var bodyParser = require('body-parser');

var index = require('./routes/index');
var users = require('./routes/users');

var app = express();

// view engine setup
app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'jade');

// uncomment after placing your favicon in /public
//app.use(favicon(path.join(__dirname, 'public', 'favicon.ico')));
app.use(logger('dev'));
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: false }));
app.use(cookieParser());
app.use(express.static(path.join(__dirname, 'public')));

app.use('/', index);
app.use('/users', users);

// catch 404 and forward to error handler
app.use(function(req, res, next) {
  var err = new Error('Not Found');
  err.status = 404;
  next(err);
});

// error handler
app.use(function(err, req, res, next) {
  // set locals, only providing error in development
  res.locals.message = err.message;
  res.locals.error = req.app.get('env') === 'development' ? err : {};

  // render the error page
  res.status(err.status || 500);
  res.render('error');
});

module.exports = app;
```
#### package.json file
```
{
  "name": "hello",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "start": "node ./bin/www"
  },
  "dependencies": {
    "body-parser": "~1.17.1",
    "cookie-parser": "~1.4.3",
    "debug": "~2.6.3",
    "express": "~4.15.2",
    "jade": "~1.11.0",
    "morgan": "~1.8.1",
    "serve-favicon": "~2.4.2"
  }
}
```
- I have tried but can not install jade, please help or give me new solution popular nowadays about using view in node js
Thanks .

**Comment by Airboy** [comment]
Jade has been renamed for some time and replaced by [Pug](https://pugjs.org/api/getting-started.html). Try to install it and replace the following lines in `app.js` :

```
app.set('view engine', 'pug')
app.set('views', path.join(__dirname, 'views'))
```

**Comment by tranluong** [comment]
Thanks so much, I have resloved my problem
