### ISSUE TITLE
Cannot read property path

### ISSUE THREAD

**Issue by sharad3010** [npm/npm#16597]
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'powerbi-visuals-tools' ]
2 info using npm@4.2.0
3 info using node@v7.10.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData powerbi-visuals-tools
8 silly fetchNamedPackageData powerbi-visuals-tools
9 silly mapToRegistry name powerbi-visuals-tools
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'powerbi-visuals-tools',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'powerbi-visuals-tools',
12 silly mapToRegistry   name: 'powerbi-visuals-tools',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/powerbi-visuals-tools
14 verbose request uri https://registry.npmjs.org/powerbi-visuals-tools
15 verbose request no auth needed
16 info attempt registry request try #1 at 4:35:06 PM
17 verbose request id af3b1fa18a4bc471
18 http request GET https://registry.npmjs.org/powerbi-visuals-tools
19 info retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.28.162:443
20 info attempt registry request try #2 at 4:35:37 PM
21 http request GET https://registry.npmjs.org/powerbi-visuals-tools
22 info retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.28.162:443
23 info attempt registry request try #3 at 4:36:59 PM
24 http request GET https://registry.npmjs.org/powerbi-visuals-tools
25 silly fetchPackageMetaData Error: connect ETIMEDOUT 151.101.56.162:443
25 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1050:11)
25 silly fetchPackageMetaData     at exports._exceptionWithHostPort (util.js:1073:20)
25 silly fetchPackageMetaData     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1093:14)
25 silly fetchPackageMetaData  error for powerbi-visuals-tools { Error: connect ETIMEDOUT 151.101.56.162:443
25 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1050:11)
25 silly fetchPackageMetaData     at exports._exceptionWithHostPort (util.js:1073:20)
25 silly fetchPackageMetaData     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1093:14)
25 silly fetchPackageMetaData   code: 'ETIMEDOUT',
25 silly fetchPackageMetaData   errno: 'ETIMEDOUT',
25 silly fetchPackageMetaData   syscall: 'connect',
25 silly fetchPackageMetaData   address: '151.101.56.162',
25 silly fetchPackageMetaData   port: 443 }
26 silly rollbackFailedOptional Starting
27 verbose stack TypeError: Cannot read property 'path' of null
27 verbose stack     at Installer.rollbackFailedOptional (C:\Program Files\nodejs\node_modules\npm\lib\install.js:511:29)
27 verbose stack     at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
27 verbose stack     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
27 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:18:7
27 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install.js:337:5
27 verbose stack     at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
27 verbose stack     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
27 verbose stack     at chain (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
27 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install.js:294:5
27 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:16:22
28 verbose cwd C:\Users\sharadg180
29 error Windows_NT 6.1.7601
30 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "powerbi-visuals-tools"
31 error node v7.10.0
32 error npm  v4.2.0
33 error Cannot read property 'path' of null
34 error If you need help, you may report this error at:
34 error     <https://github.com/npm/npm/issues>
35 verbose exit [ 1, true ]
```

**Comment by legodude17** [comment]
This is most likely a problem with your internet. Please check your internet connection.
