### ISSUE TITLE
npm cannot install cordova and ionic

### ISSUE THREAD

**Issue by gr1d99** [npm/npm#16636]
when i run the command below
```npm install -g cordova ionic```
i get these errors
```
npm ERR! fetch failed https://registry.npmjs.org/cordova-lib/-/cordova-lib-7.0.1.tgz
npm WARN retry will retry, error on last attempt: TypeError: socket._handle.asyncReset is not a function
````

**Comment by sebdeckers** [comment]
@KenanY FWIW I'm getting the same error with different packages.

```
3867 verbose stack TypeError: socket._handle.asyncReset is not a function
3867 verbose stack     at Agent.addRequest (_http_agent.js:170:20)
3867 verbose stack     at new ClientRequest (_http_client.js:269:16)
3867 verbose stack     at Object.request (http.js:39:10)
3867 verbose stack     at Object.request (https.js:230:15)
3867 verbose stack     at Request.start (/usr/local/lib/node_modules/npm/node_modules/request/request.js:755:32)
3867 verbose stack     at Request.end (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1525:10)
3867 verbose stack     at end (/usr/local/lib/node_modules/npm/node_modules/request/request.js:567:14)
3867 verbose stack     at Immediate.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:581:7)
3867 verbose stack     at runCallback (timers.js:800:20)
3867 verbose stack     at tryOnImmediate (timers.js:762:5)
3867 verbose stack     at processImmediate [as _immediateCallback] (timers.js:733:5)
3868 verbose cwd /Users/seb/Code/sebdeckers/http2server
3869 verbose Darwin 16.5.0
3870 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "i"
3871 verbose node v8.0.0-pre
3872 verbose npm  v4.5.0
3873 error socket._handle.asyncReset is not a function
3874 verbose exit [ 1, true ]
```

**Comment by sebdeckers** [comment]
Note that I'm running the nodejs/http2 fork which is only a few days behind nodejs/node#master. Possibly related to: https://github.com/nodejs/node/issues/13045

**Comment by sebdeckers** [comment]
Fixed by https://github.com/nodejs/node/commit/6bfdeedce5529810dbe7c61bd712fc50174a19f1
