### ISSUE TITLE
Npm ERR! Missing Script: Start when deploying to heroku

### ISSUE THREAD

**Issue by ginxx009** [npm/npm#16647]
I do have a procfile:
web: node server.js

here's my package.json:

``` json
{
  "name": "easyrtc_server_example",
  "version": "0.1.6",
  "author": "Priologic Software Inc. <info@priologic.com> (http://priologic.com/)",
  "description" : "Simple EasyRTC server example which includes EasyRTC, Express, and Socket.io",
  "main":"server.js",
  "private": true,

  "scripts": {
    "start": "node server.js"
  },

  "dependencies" : {
    "express": "^4.10.7",
    "serve-static": "^1.8.0",
    "socket.io": "^1.4.5",
    "bcryptjs": "*",
    "body-parser": "*",
    "connect-flash": "*",
    "cookie-parser": "^1.4.1",
    "express-handlebars": "*",
    "express-messages": "*",
    "express-session": "*",
    "express-validator": "*",
    "mongodb": "*",
    "mongoose": "*",
    "passport": "*",
    "passport-http": "*",
    "passport-local": "*"
  },

  "license": "BSD2",

  "engines": {
    "node": ">=0.8"
  }
}
```

Here's my npm-error log.

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.10.10
3 info using node@v6.10.2
4 verbose stack Error: missing script: start
4 verbose stack     at run (C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:151:19)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:61:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:356:5
4 verbose stack     at checkBinReferences_ (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:320:45)
4 verbose stack     at final (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:354:3)
4 verbose stack     at then (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:124:5)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:243:12
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16
4 verbose stack     at tryToString (fs.js:456:3)
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:443:12)
5 verbose cwd C:\Users\Nette\Desktop\pektos_1
6 error Windows_NT 6.3.9600
7 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
8 error node v6.10.2
9 error npm  v3.10.10
10 error missing script: start
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
```

help me guys please :(

**Comment by legodude17** [comment]
Try updating `npm` to the latest version.

**Comment by KenanY** [comment]
@ginxx009 Is `C:\Users\Nette\Desktop\pektos_1\package.json` the file you provided above?

**Comment by ginxx009** [comment]
by completely deleting my node modules and then do the npm install again and changing the procfile from web to worker and it works perfectly fine . Thanks guys :)
