### ISSUE TITLE
crash installing: "Error: Argument #2: Expected string or string but got null"

### ISSUE THREAD

**Issue by isaacs** [npm/npm#16665]
debug log: https://gist.github.com/isaacs/1540eb55e109c712b8e0e13d8ab5e12a

node_modules folder: http://static.izs.me/glob_node_modules.tgz

Using npm@5.0.0-beta.56

**Comment by saadq** [comment]
I'm getting this issue when running `npm uninstall -g yarn`

**Comment by jakeNiemiec** [comment]
Same here, any manual steps I can take?

**Comment by afhole** [comment]
I still get this in 5.0.0 trying to uninstall flow-bin

**Comment by poke** [comment]
I’m getting the same error when attempting to `npm -g u bower` on 5.0.1.

```
Unhandled rejection Error: Argument #2: Expected string but got null0
    at addDependency (C:\Users\poke\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:515:3)
    at C:\Users\poke\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:463:5
    at C:\Users\poke\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:52:35
    at Array.forEach (native)
    at C:\Users\poke\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:52:11
    at Array.forEach (native)
    at asyncMap (C:\Users\poke\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:51:8)
    at loadDeps (C:\Users\poke\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:455:3)
    at Array.<anonymous> (C:\Users\poke\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
    at LOOP (C:\Users\poke\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
    at C:\Users\poke\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:18:7
    at C:\Users\poke\AppData\Roaming\npm\node_modules\npm\lib\install\and-finish-tracker.js:8:8
    at resolveBranchDeps.then (C:\Users\poke\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:419:11)
    at tryCatcher (C:\Users\poke\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\poke\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\poke\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)

npm ERR! cb() never called!
```

**Comment by kud** [comment]
```shell
~/P/_/lois-webapp ❯❯❯ npm uninstall npm-check-updates -g             new-backend-api ◼
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
Unhandled rejection Error: Argument #2: Expected string but got null
    at addDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:515:3)
    at /usr/local/lib/node_modules/npm/lib/install/deps.js:463:5
    at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
    at Array.forEach (native)
    at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
    at Array.forEach (native)
    at asyncMap (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
    at loadDeps (/usr/local/lib/node_modules/npm/lib/install/deps.js:455:3)
    at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
    at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
    at /usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
    at /usr/local/lib/node_modules/npm/lib/install/and-finish-tracker.js:8:8
    at resolveBranchDeps.then (/usr/local/lib/node_modules/npm/lib/install/deps.js:419:11)
    at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kud/.npm/_logs/2017-06-01T08_20_16_786Z-debug.log
```

**Comment by kud** [comment]
I did:

```
rm -rf ~/.npm/npm-check-updates
npm install -g npm-check-updates
npm uninstall -g npm-check-updates
npm install -g npm-check-updates
```

It works.

**Comment by jakeNiemiec** [comment]
`npm cache clean --force` worked for me.

**Comment by MikelArnaiz** [comment]
Same here


```
Mikels-iMac:Projects mikel$ npm uninstall -g @angular/cli
Unhandled rejection Error: Argument #2: Expected string but got null fill-range@^2.1
    at addDependency (/Users/mikel/.nvm/versions/node/v6.9.5/lib/node_modules/npm/lib/install/deps.js:515:3)
    at /Users/mikel/.nvm/versions/node/v6.9.5/lib/node_modules/npm/lib/install/deps.js:463:5
    at /Users/mikel/.nvm/versions/node/v6.9.5/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
    at Array.forEach (native)
    at /Users/mikel/.nvm/versions/node/v6.9.5/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
    at Array.forEach (native)
    at asyncMap (/Users/mikel/.nvm/versions/node/v6.9.5/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
    at loadDeps (/Users/mikel/.nvm/versions/node/v6.9.5/lib/node_modules/npm/lib/install/deps.js:455:3)
    at Array.<anonymous> (/Users/mikel/.nvm/versions/node/v6.9.5/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
    at LOOP (/Users/mikel/.nvm/versions/node/v6.9.5/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
    at /Users/mikel/.nvm/versions/node/v6.9.5/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
    at /Users/mikel/.nvm/versions/node/v6.9.5/lib/node_modules/npm/lib/install/and-finish-tracker.js:8:8
    at resolveBranchDeps.then (/Users/mikel/.nvm/versions/node/v6.9.5/lib/node_modules/npm/lib/install/deps.js:419:11)
    at tryCatcher (/Users/mikel/.nvm/versions/node/v6.9.5/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/mikel/.nvm/versions/node/v6.9.5/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/mikel/.nvm/versions/node/v6.9.5/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
```

**Comment by kud** [comment]
Remove your whole `~/.npm` folder (or specific folder (angular/cli here)) and reinstall it.

**Comment by afhole** [comment]
Have tried removing `~/.npm` and `npm cache clean --force` to no avail

**Comment by afhole** [comment]
Interestingly if I `npm -g i some-package` that is already installed _then_ I am able to remove it

**Comment by poke** [comment]
Installing it again before attempting to remove it also worked for me.

**Comment by twang2218** [comment]
I still have the problem on npm `5.0.3` and `5.0.4`, I have to reinstall any package I want to uninstall to uninstall them. And I'm not sure it's related or not, the `npm -g outdated` is not working either.

**Comment by oldqian** [comment]
I slove the problem when
1.npm install your-module -g
2.then npm uninstall your-module -g again
then, ok

**Comment by ChuckkNorris** [comment]
@kud Saw your comment, replaced `npm-check-updates` with my package name, it worked, noticed the downvotes, was confused, scrolled down to 5 days later, 40 upvotes, same solution... hm.
