### ISSUE TITLE
node app crashes

### ISSUE THREAD

**Issue by amanbhushan** [npm/npm#16667]
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@4.6.1
3 info using node@v4.4.7
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle FloPortal@0.0.2~prestart: FloPortal@0.0.2
6 silly lifecycle FloPortal@0.0.2~prestart: no script for prestart, continuing
7 info lifecycle FloPortal@0.0.2~start: FloPortal@0.0.2
8 verbose lifecycle FloPortal@0.0.2~start: unsafe-perm in lifecycle true
9 verbose lifecycle FloPortal@0.0.2~start: PATH: C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\INNO\FLOLIVE\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\nodejs\;C:\Program Files (x86)\nodejs\;C:\Users\Administrator\AppData\Roaming\npm
10 verbose lifecycle FloPortal@0.0.2~start: CWD: C:\INNO\FLOLIVE
11 silly lifecycle FloPortal@0.0.2~start: Args: [ '/d /s /c', 'node server.js' ]
12 silly lifecycle FloPortal@0.0.2~start: Returned: code: 1  signal: null
13 info lifecycle FloPortal@0.0.2~start: Failed to exec start script
14 verbose stack Error: FloPortal@0.0.2 start: `node server.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:827:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid FloPortal@0.0.2
16 verbose cwd C:\INNO\FLOLIVE
17 verbose Windows_NT 6.1.7601
18 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 verbose node v4.4.7
20 verbose npm  v4.6.1
21 error code ELIFECYCLE
22 error errno 1
23 error FloPortal@0.0.2 start: `node server.js`
23 error Exit status 1
24 error Failed at the FloPortal@0.0.2 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

**Comment by legodude17** [comment]
This is a problem with your `server.js` failing, it has nothing to do with `npm`.
