### ISSUE TITLE
Incorrect PUT 402 on `npm publish`

### ISSUE THREAD

**Issue by duizendnegen** [npm/npm#16675]
#### I'm opening this issue because:

  - npm is doing something I don't understand.

#### What's going wrong?

Running `npm publish` on a package results in `You need a paid account to perform this action. For more info, visit: https://www.npmjs.com/private-modules : @deployjs/ember-build`

#### How can the CLI team reproduce the problem?

`npm publish`

```0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'publish' ]
2 info using npm@3.10.8
3 info using node@v6.9.1
4 verbose publish [ '.' ]
5 silly cache add args [ '.', null ]
6 verbose cache add spec .
7 silly cache add parsed spec Result {
7 silly cache add   raw: '.',
7 silly cache add   scope: null,
7 silly cache add   escapedName: null,
7 silly cache add   name: null,
7 silly cache add   rawSpec: '.',
7 silly cache add   spec: 'D:\\code\\deployjs\\deployjs-ember-build',
7 silly cache add   type: 'directory' }
8 verbose addLocalDirectory C:\Users\dzing\AppData\Roaming\npm-cache\@deployjs\ember-build\0.0.1\package.tgz not in flight; packing
9 verbose correctMkdir C:\Users\dzing\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
10 info lifecycle @deployjs/ember-build@0.0.1~prepublish: @deployjs/ember-build@0.0.1
11 silly lifecycle @deployjs/ember-build@0.0.1~prepublish: no script for prepublish, continuing
12 verbose tar pack [ 'C:\\Users\\dzing\\AppData\\Roaming\\npm-cache\\@deployjs\\ember-build\\0.0.1\\package.tgz',
12 verbose tar pack   'D:\\code\\deployjs\\deployjs-ember-build' ]
13 verbose tarball C:\Users\dzing\AppData\Roaming\npm-cache\@deployjs\ember-build\0.0.1\package.tgz
14 verbose folder D:\code\deployjs\deployjs-ember-build
15 verbose addLocalTarball adding from inside cache C:\Users\dzing\AppData\Roaming\npm-cache\@deployjs\ember-build\0.0.1\package.tgz
16 verbose correctMkdir C:\Users\dzing\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
17 silly cache afterAdd @deployjs/ember-build@0.0.1
18 verbose afterAdd C:\Users\dzing\AppData\Roaming\npm-cache\@deployjs\ember-build\0.0.1\package\package.json not in flight; writing
19 verbose correctMkdir C:\Users\dzing\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
20 verbose afterAdd C:\Users\dzing\AppData\Roaming\npm-cache\@deployjs\ember-build\0.0.1\package\package.json written
21 silly publish { name: '@deployjs/ember-build',
21 silly publish   version: '0.0.1',
21 silly publish   description: 'Build Ember projects ready for deployment',
21 silly publish   main: 'index.js',
21 silly publish   scripts: { test: 'echo "Error: no test specified" && exit 1' },
21 silly publish   keywords: [ 'deployjs-plugin' ],
21 silly publish   dependencies:
21 silly publish    { 'ember-cli-deploy-plugin': '^0.2.1',
21 silly publish      glob: '^7.1.1',
21 silly publish      rsvp: '^3.5.0' },
21 silly publish   repository:
21 silly publish    { type: 'git',
21 silly publish      url: 'git+https://github.com/deployjs/deployjs-ember-build.git' },
21 silly publish   author: '',
21 silly publish   license: 'MIT',
21 silly publish   readme: '# deployjs-ember-build\r\nBuild Ember projects ready for deployment\r\n',
21 silly publish   readmeFilename: 'README.md',
21 silly publish   gitHead: 'd887ebee3b337031176aa4f14bc496cd8b442e80',
21 silly publish   bugs: { url: 'https://github.com/deployjs/deployjs-ember-build/issues' },
21 silly publish   homepage: 'https://github.com/deployjs/deployjs-ember-build#readme',
21 silly publish   _id: '@deployjs/ember-build@0.0.1',
21 silly publish   _shasum: 'e811ced167c20d50512af1574b0b3682199c9f55',
21 silly publish   _from: '.' }
22 verbose getPublishConfig undefined
23 silly mapToRegistry name @deployjs/ember-build
24 silly mapToRegistry scope (from package name) @deployjs
25 verbose mapToRegistry no registry URL found in name for scope @deployjs
26 silly mapToRegistry using default registry
27 silly mapToRegistry registry https://registry.npmjs.org/
28 silly mapToRegistry data Result {
28 silly mapToRegistry   raw: '@deployjs/ember-build',
28 silly mapToRegistry   scope: '@deployjs',
28 silly mapToRegistry   escapedName: '@deployjs%2fember-build',
28 silly mapToRegistry   name: '@deployjs/ember-build',
28 silly mapToRegistry   rawSpec: '',
28 silly mapToRegistry   spec: 'latest',
28 silly mapToRegistry   type: 'tag' }
29 silly mapToRegistry uri https://registry.npmjs.org/@deployjs%2fember-build
30 verbose publish registryBase https://registry.npmjs.org/
31 silly publish uploading C:\Users\dzing\AppData\Roaming\npm-cache\@deployjs\ember-build\0.0.1\package.tgz
32 verbose request uri https://registry.npmjs.org/@deployjs%2fember-build
33 verbose request sending authorization for write operation
34 info attempt registry request try #1 at 5:36:21 PM
35 verbose request using bearer token for auth
36 verbose request id 6b6513b493cc8f7d
37 http request PUT https://registry.npmjs.org/@deployjs%2fember-build
38 http 402 https://registry.npmjs.org/@deployjs%2fember-build
39 verbose headers { 'content-type': 'application/json',
39 verbose headers   'cache-control': 'max-age=0',
39 verbose headers   'content-length': '119',
39 verbose headers   'accept-ranges': 'bytes',
39 verbose headers   date: 'Sun, 21 May 2017 15:36:25 GMT',
39 verbose headers   via: '1.1 varnish',
39 verbose headers   connection: 'keep-alive',
39 verbose headers   'x-served-by': 'cache-ams4151-AMS',
39 verbose headers   'x-cache': 'MISS',
39 verbose headers   'x-cache-hits': '0',
39 verbose headers   'x-timer': 'S1495380985.795117,VS0,VE945' }
40 verbose request invalidating C:\Users\dzing\AppData\Roaming\npm-cache\registry.npmjs.org\_40deployjs_252fember-build on PUT
41 error publish Failed PUT 402
42 verbose stack Error: You need a paid account to perform this action. For more info, visit: https://www.npmjs.com/private-modules : @deployjs/ember-build
42 verbose stack     at makeError (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:302:12)
42 verbose stack     at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:290:14)
42 verbose stack     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:210:14)
42 verbose stack     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:187:22)
42 verbose stack     at emitTwo (events.js:106:13)
42 verbose stack     at Request.emit (events.js:191:7)
42 verbose stack     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1044:10)
42 verbose stack     at emitOne (events.js:96:13)
42 verbose stack     at Request.emit (events.js:188:7)
42 verbose stack     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:965:12)
43 verbose statusCode 402
44 verbose pkgid @deployjs/ember-build
45 verbose cwd D:\code\deployjs\deployjs-ember-build
46 error Windows_NT 10.0.15063
47 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "publish"
48 error node v6.9.1
49 error npm  v3.10.8
50 error code E402
51 error You need a paid account to perform this action. For more info, visit: https://www.npmjs.com/private-modules : @deployjs/ember-build
52 error If you need help, you may report this error at:
52 error     <https://github.com/npm/npm/issues>
53 verbose exit [ 1, true ]
```

### supporting information:

 - `npm -v` prints: 3.10.8
 - `node -v` prints: v6.9.1
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Win64

**Comment by legodude17** [comment]
Does this occur with the latest version of `npm`?

**Comment by duizendnegen** [comment]
Yes, it does. I ran `npm i -g npm` and `npm -v` now gives `4.6.1`. `npm publish` still gives `You need a paid account to perform this action. For more info, visit: https://www.npmjs.com/private-modules : @deployjs/ember-build`

**Comment by duizendnegen** [comment]
Interestingly, I did `npm publish` with another package (which is already registered) and that works just fine.
