### ISSUE TITLE
npm5: preinstall lifecycle script runs before extracting package

### ISSUE THREAD

**Issue by rmg** [npm/npm#16706]
npm5 (5.0.0-beta.61) executes the `preinstall` lifecycle script before extracting the package in to the `.staging` directory but `npm@<5` run `preinstall` after the package contents have been extracted.

Not sure if this is one of the expected breaking changes or not.

Originally posted as https://github.com/npm/npm/issues/16510#issuecomment-303822327

**Comment by simonua** [comment]
I *think* I may have run into the same issue with beta.61 (maybe earlier versions, too - I'm uncertain there):

https://gist.github.com/simonua/ab2862828c457c7a4a89a21aa6292113

**Comment by rmg** [comment]
I found it while doing some compatability testing on a package, but you can reproduce it pretty trivially with an empty package:
```json
{
  "name": "test",
  "version": "0.0.0",
  "scripts": {
    "preinstall": "ls -al && pwd",
    "install": "ls -al && pwd",
    "postinstall": "ls -al && pwd"
  },
  "files": [
    "package.json"
  ]
}
```

Run `npm pack` and then install the resulting file somewhere with `npm5 i test-0.0.0.tgz` and the output of the scripts make it pretty clear that `preinstall` is run in an empty `.staging` directory:

```
$ npm5 i ../deleteme/test-0.0.0.tgz
npm notice BETA npm5 is beta software. Please see https://github.com/npm/npm/issues/16510 for known issues, and please file a new one if you find something new.

> test@0.0.0 preinstall /Users/ryan/deleteme2/node_modules/.staging
> ls -al && pwd

total 0
drwxr-xr-x  2 ryan  staff   68 24 May 13:47 .
drwxr-xr-x  5 ryan  staff  170 24 May 13:47 ..
/Users/ryan/deleteme2/node_modules/.staging

> test@0.0.0 install /Users/ryan/deleteme2/node_modules/test
> ls -al && pwd

total 8
drwxr-xr-x  3 ryan  staff  102 24 May 13:47 .
drwxr-xr-x  5 ryan  staff  170 24 May 13:47 ..
-rw-r--r--  1 ryan  staff  980 24 May 13:47 package.json
/Users/ryan/deleteme2/node_modules/test

> test@0.0.0 postinstall /Users/ryan/deleteme2/node_modules/test
> ls -al && pwd

total 8
drwxr-xr-x  3 ryan  staff  102 24 May 13:47 .
drwxr-xr-x  5 ryan  staff  170 24 May 13:47 ..
-rw-r--r--  1 ryan  staff  980 24 May 13:47 package.json
/Users/ryan/deleteme2/node_modules/test
```

**Comment by Fishrock123** [comment]
This occurs for me with npm5 beta.64 for [`llnode`](https://www.npmjs.com/package/llnode).

cc @zkat as this appears to be a bug not an expected change based on discussion?

```
🐟  ~> npm5 i -g llnode
npm notice BETA npm5 is beta software. Please see https://github.com/npm/npm/issues/16510 for known issues, and please file a new one if you find something new.

> llnode@1.4.3 preinstall /Users/Jeremiah/npm/lib/node_modules/.staging
> node scripts/configure.js

module.js:472
    throw err;
    ^

Error: Cannot find module '/Users/Jeremiah/npm/lib/node_modules/.staging/scripts/configure.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! llnode@1.4.3 preinstall: `node scripts/configure.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the llnode@1.4.3 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Jeremiah/.npm/_logs/2017-05-25T15_18_02_213Z-debug.log
🐟  ~> node -v
v7.10.0
🐟  ~> npm5 -v
5.0.0-beta.64
```

llnode [does indeed use `preinstall`](https://github.com/nodejs/llnode/blob/master/package.json).

Building this package with `node-gyp` in the usual way is not possible.

**Comment by zkat** [comment]
Looks like this is running in the right order (we didn't change that), but the scripts aren't running inside .staging. We just need to cwd to the right place. thanks for the report!

**Comment by rmg** [comment]
@zkat from my output above, `preinstall` _is_ running inside `.staging`, there just isn't anything there:

```
> test@0.0.0 preinstall /Users/ryan/deleteme2/node_modules/.staging
> ls -al && pwd

total 0
drwxr-xr-x  2 ryan  staff   68 24 May 13:47 .
drwxr-xr-x  5 ryan  staff  170 24 May 13:47 ..
/Users/ryan/deleteme2/node_modules/.staging
```

**Comment by rmg** [comment]
For comparison, here's the same test package but with v3.10.10:
```
$ npm i ../deleteme/test-0.0.0.tgz

> test@0.0.0 preinstall /Users/ryan/deleteme2/node_modules/.staging/test-fe720570
> ls -al && pwd

total 8
drwxr-xr-x  3 ryan  staff   102 25 May 11:59 .
drwxr-xr-x  4 ryan  staff   136 25 May 11:59 ..
-rw-r--r--  1 ryan  staff  1334 25 May 11:59 package.json
/Users/ryan/deleteme2/node_modules/.staging/test-fe720570

> test@0.0.0 install /Users/ryan/deleteme2/node_modules/test
> ls -al && pwd

total 8
drwxr-xr-x  3 ryan  staff   102 25 May 11:59 .
drwxr-xr-x  5 ryan  staff   170 25 May 11:59 ..
-rw-r--r--  1 ryan  staff  1334 25 May 11:59 package.json
/Users/ryan/deleteme2/node_modules/test

> test@0.0.0 postinstall /Users/ryan/deleteme2/node_modules/test
> ls -al && pwd

total 8
drwxr-xr-x  3 ryan  staff   102 25 May 11:59 .
drwxr-xr-x  5 ryan  staff   170 25 May 11:59 ..
-rw-r--r--  1 ryan  staff  1334 25 May 11:59 package.json
/Users/ryan/deleteme2/node_modules/test
```

**Comment by zkat** [comment]
This is fixed in our release branch. It'll be available later today/tomorrow and y'all can test it then.

**Comment by zkat** [comment]
https://github.com/npm/npm/commit/f4b6a2c see here

**Comment by rmg** [comment]
Thanks for pointing to the commit! I was trying to figure out how it broke but ran out of time.. closure++.

**Comment by rmg** [comment]
Verified. My test scenario works with `npm@5.0.0`.

@zkat not sure if you want posters to close or if that messes up any sort of planning/reporting you might have around GH issues, so I'll leave the honours to you.

**Comment by zkat** [comment]
Closing this then. Thanks for verifying it! ^_^
