### ISSUE TITLE
npm ERR Windows_NT 10

### ISSUE THREAD

**Issue by springMonkey** [npm/npm#16713]
npm ERR! Windows_NT 10
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "hex-cli"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code EAI_AGAIN
npm ERR! errno EAI_AGAIN
npm ERR! syscall getaddrinfo

npm ERR! getaddrinfo EAI_AGAIN registry.npmjs.org:443
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\blog\npm-debug.log
--------------------------------------above is error message------------------
I need god's help

**Comment by springMonkey** [comment]
maybe proxy reason??

**Comment by springMonkey** [comment]
this is message of log:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'hex-cli' ]
2 info using npm@3.10.10
3 info using node@v6.10.3
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData hex-cli
8 silly fetchNamedPackageData hex-cli
9 silly mapToRegistry name hex-cli
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'hex-cli',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'hex-cli',
12 silly mapToRegistry   name: 'hex-cli',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/hex-cli
14 verbose request uri https://registry.npmjs.org/hex-cli
15 verbose request no auth needed
16 info attempt registry request try #1 at 14:56:13
17 verbose request id e56c64bf5fb763c1
18 http request GET https://registry.npmjs.org/hex-cli
19 info retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
20 info attempt registry request try #2 at 14:56:27
21 http request GET https://registry.npmjs.org/hex-cli
22 info retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
23 info attempt registry request try #3 at 14:57:31
24 http request GET https://registry.npmjs.org/hex-cli
25 silly fetchPackageMetaData Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
25 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1018:11)
25 silly fetchPackageMetaData     at errnoException (dns.js:33:15)
25 silly fetchPackageMetaData     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
25 silly fetchPackageMetaData  error for hex-cli { Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
25 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1018:11)
25 silly fetchPackageMetaData     at errnoException (dns.js:33:15)
25 silly fetchPackageMetaData     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
25 silly fetchPackageMetaData   code: 'EAI_AGAIN',
25 silly fetchPackageMetaData   errno: 'EAI_AGAIN',
25 silly fetchPackageMetaData   syscall: 'getaddrinfo',
25 silly fetchPackageMetaData   hostname: 'registry.npmjs.org',
25 silly fetchPackageMetaData   host: 'registry.npmjs.org',
25 silly fetchPackageMetaData   port: 443 }
26 silly rollbackFailedOptional Starting
27 silly rollbackFailedOptional Finishing
28 silly runTopLevelLifecycles Finishing
29 silly install printInstalled
30 verbose stack Error: getaddrinfo EAI_AGAIN registry.npmjs.org:443
30 verbose stack     at Object.exports._errnoException (util.js:1018:11)
30 verbose stack     at errnoException (dns.js:33:15)
30 verbose stack     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
31 verbose cwd D:\blog
32 error Windows_NT 10.0.14393
33 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "hex-cli"
34 error node v6.10.3
35 error npm  v3.10.10
36 error code EAI_AGAIN
37 error errno EAI_AGAIN
38 error syscall getaddrinfo
39 error getaddrinfo EAI_AGAIN registry.npmjs.org:443
40 error If you need help, you may report this error at:
40 error     <https://github.com/npm/npm/issues>
41 verbose exit [ 1, true ]
