### ISSUE TITLE
npm publish --tag regression?

### ISSUE THREAD

**Issue by jsg2021** [npm/npm#16746]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
`npm publish --tag alpha` did not use the alpha tag and instead used `latest`.
npm 3.x, 4.x worked fine.

#### How can the CLI team reproduce the problem?

run `npm publish --tag alpha` 

### supporting information:

 - `npm -v` prints: 5.0.0
 - `node -v` prints: 6.10.3
 - `npm config get registry` prints: private-sinopia-url
 - Windows, OS X/macOS, or Linux?: macOS
 - Network issues:
   - Geographic location where npm was run: Norman, OK - US
   - [x] I use a proxy to connect to the npm registry. (Sinopia)
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by zkat** [comment]
Thanks for the report! I'll take a look at why this isn't being picked up. 👍

**Comment by zkat** [comment]
Hah, found it. Thanks!

**Comment by zkat** [comment]
No, I take it back. I can't actually reproduce this. Any time I publish with `--tag` on `npm@5.0.0`, I get a new version under said tag 🙃 

Can you do `npm pub <pkg> --timing --tag foo` and post the debug log that prints out? (it's not actually erroring, `--timing` is just mostly a debug tool for the npm CLI devs right now, pardon the confusion).

**Comment by jsg2021** [comment]
Here ya go
```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/jgrimes/.nvm/versions/node/v6.10.3/bin/node',
1 verbose cli   '/Users/jgrimes/.nvm/versions/node/v6.10.3/bin/npm',
1 verbose cli   'publish',
1 verbose cli   '--timing',
1 verbose cli   '--tag',
1 verbose cli   'alphatest' ]
2 info using npm@5.0.0
3 info using node@v6.10.3
4 verbose publish [ '.' ]
5 warn prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
6 warn prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only
7 warn prepublish-on-install See the deprecation note in `npm help scripts` for more information
8 info lifecycle nti-web-app@2017.4.0-alpha20170526-2353~prepublish: nti-web-app@2017.4.0-alpha20170526-2353
9 verbose lifecycle nti-web-app@2017.4.0-alpha20170526-2353~prepublish: unsafe-perm in lifecycle true
10 verbose lifecycle nti-web-app@2017.4.0-alpha20170526-2353~prepublish: PATH: /Users/jgrimes/.nvm/versions/node/v6.10.3/lib/node_modules/npm/bin/node-gyp-bin:/Users/jgrimes/Workspace/nti-web-app/node_modules/.bin:./node_modules/.bin:.:/Users/jgrimes/Applications/bin:/opt/local/Library/Frameworks/Python.framework/Versions/2.7/bin:/opt/local/bin:/opt/local/sbin:/Users/jgrimes/.nvm/versions/node/v6.10.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/jgrimes/Workspace/buildout/bin/:/Users/jgrimes/Library/Android/sdk/tools
11 verbose lifecycle nti-web-app@2017.4.0-alpha20170526-2353~prepublish: CWD: .
12 silly lifecycle nti-web-app@2017.4.0-alpha20170526-2353~prepublish: Args: [ '-c', 'not-in-install && make || in-install' ]
13 silly lifecycle nti-web-app@2017.4.0-alpha20170526-2353~prepublish: Returned: code: 0  signal: null
14 info lifecycle nti-web-app@2017.4.0-alpha20170526-2353~prepare: nti-web-app@2017.4.0-alpha20170526-2353
15 silly lifecycle nti-web-app@2017.4.0-alpha20170526-2353~prepare: no script for prepare, continuing
16 info lifecycle nti-web-app@2017.4.0-alpha20170526-2353~prepublishOnly: nti-web-app@2017.4.0-alpha20170526-2353
17 silly lifecycle nti-web-app@2017.4.0-alpha20170526-2353~prepublishOnly: no script for prepublishOnly, continuing
18 info lifecycle nti-web-app@2017.4.0-alpha20170526-2353~prepack: nti-web-app@2017.4.0-alpha20170526-2353
19 silly lifecycle nti-web-app@2017.4.0-alpha20170526-2353~prepack: no script for prepack, continuing
20 verbose tar pack [ '/var/folders/4j/f3rldfln6h52nmf2lpzq15rc0000gn/T/npm-3213-a42317e5/tmp/packing-1535e7f8/package.tgz',
20 verbose tar pack   '.' ]
21 verbose tarball /var/folders/4j/f3rldfln6h52nmf2lpzq15rc0000gn/T/npm-3213-a42317e5/tmp/packing-1535e7f8/package.tgz
22 verbose folder .
23 info lifecycle nti-web-app@2017.4.0-alpha20170526-2353~postpack: nti-web-app@2017.4.0-alpha20170526-2353
24 silly lifecycle nti-web-app@2017.4.0-alpha20170526-2353~postpack: no script for postpack, continuing
25 verbose getPublishConfig { registry: 'https://private-sinopia-registry' }
26 silly mapToRegistry name nti-web-app
27 silly mapToRegistry using default registry
28 silly mapToRegistry registry https://private-sinopia-registry
29 silly mapToRegistry data { type: 'tag',
29 silly mapToRegistry   registry: true,
29 silly mapToRegistry   where: undefined,
29 silly mapToRegistry   raw: 'nti-web-app',
29 silly mapToRegistry   name: 'nti-web-app',
29 silly mapToRegistry   escapedName: 'nti-web-app',
29 silly mapToRegistry   scope: undefined,
29 silly mapToRegistry   rawSpec: '',
29 silly mapToRegistry   saveSpec: null,
29 silly mapToRegistry   fetchSpec: 'latest',
29 silly mapToRegistry   gitRange: undefined,
29 silly mapToRegistry   gitCommittish: undefined,
29 silly mapToRegistry   hosted: undefined }
30 silly mapToRegistry uri https://private-sinopia-registry/nti-web-app
31 verbose publish registryBase https://private-sinopia-registry/
32 silly publish uploading /var/folders/4j/f3rldfln6h52nmf2lpzq15rc0000gn/T/npm-3213-a42317e5/tmp/fromDir-c7ba2fcd/package.tgz
33 verbose request uri https://private-sinopia-registry/nti-web-app
34 verbose request sending authorization for write operation
35 info attempt registry request try #1 at 11:53:40 PM
36 verbose request using bearer token for auth
37 verbose request id 631d7e88e28bee49
38 http request PUT https://private-sinopia-registry/nti-web-app
39 http 201 https://private-sinopia-registry/nti-web-app
40 verbose headers { 'x-powered-by': 'Sinopia/1.4.0',
40 verbose headers   'content-type': 'application/json; charset=utf-8',
40 verbose headers   etag: '"6d28788a2c5a6a5e6a8d883de2a2a9ca"',
40 verbose headers   'content-length': '34',
40 verbose headers   vary: 'Accept-Encoding',
40 verbose headers   'x-status-cat': 'http://flic.kr/p/aXWm1Z',
40 verbose headers   date: 'Sat, 27 May 2017 04:53:52 GMT' }
41 info lifecycle nti-web-app@2017.4.0-alpha20170526-2353~publish: nti-web-app@2017.4.0-alpha20170526-2353
42 silly lifecycle nti-web-app@2017.4.0-alpha20170526-2353~publish: no script for publish, continuing
43 info lifecycle nti-web-app@2017.4.0-alpha20170526-2353~postpublish: nti-web-app@2017.4.0-alpha20170526-2353
44 silly lifecycle nti-web-app@2017.4.0-alpha20170526-2353~postpublish: no script for postpublish, continuing
45 verbose exit [ 0, true ]
46 info ok
```

**Comment by zkat** [comment]
Can you reproduce this against the main npm registry, by any chance? (mostly so I can look at the metadata for the package)

**Comment by zkat** [comment]
To clarify: I worked on reproing this locally, wrote more thorough tests, read through the code and how everything gets passed in. The tests passed just fine. I reviewed the code any noted that `tag` is indeed being threaded through all the way to `npm-registry-client`.

I'm really not sure why you're seeing this, but I trust you that it's happening to you. I'm just trying to suss out what it is that's different enough that it breaks sinopia 🙃

**Comment by jsg2021** [comment]
I just attempted to test another package... and couldn't repro... but then noticed it accidentally published to my private sinopia instance... but worked! The only difference I could find was this package didn't have a `publishConfig`.

So I attempted to add a `"publishConfig": {"registry": "https://..."}` block to this package and it incorrectly set `latest` instead of my desired tag.

Just adding that block breaks it... if i remove that block it works. 
If I add the block and point it at the https://registry.npmjs.org, it works...

**Comment by zkat** [comment]
@jsg2021 perfect! Cooking up a test case 'cause I think I found it. Good job on the publishConfig sleuthing 👍

**Comment by zkat** [comment]
@jsg2021 #16762 will fix this! 🎉 

thank you so much for figuring out what the difference was. It made it super easy from there. This was just a bit of configuration that I missed adapting after the old caching client was replaced (which had all sorts of internal magic -- this was one of the reasons we wanted to get rid of it).

If you want a version of npm that will work, you can try `npm i -g 'npm/npm#zkat/fix-publish-config'` and that'll let you use the fixed-up branch until this change lands in an actual release (in the next few days).

Cheers!

**Comment by jsg2021** [comment]
awesome! thanks!

**Comment by costel-petrescu** [comment]
hi, zkat.
I got an error while publishing npm.
the error is below.
```
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "publish"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code E403

npm ERR! you do not have permission to publish "starwars-names". Are you logged in as the correct user? : starwars-names
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     E:\starwars-names\npm-debug.log
```

npm-debug.log file
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'publish' ]
2 info using npm@3.10.10
3 info using node@v6.10.3
4 verbose publish [ '.' ]
5 silly cache add args [ '.', null ]
6 verbose cache add spec .
7 silly cache add parsed spec Result {
7 silly cache add   raw: '.',
7 silly cache add   scope: null,
7 silly cache add   escapedName: null,
7 silly cache add   name: null,
7 silly cache add   rawSpec: '.',
7 silly cache add   spec: 'E:\\starwars-names',
7 silly cache add   type: 'directory' }
8 verbose addLocalDirectory C:\Users\Josephine\AppData\Roaming\npm-cache\starwars-names\1.0.0\package.tgz not in flight; packing
9 verbose correctMkdir C:\Users\Josephine\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
10 info lifecycle starwars-names@1.0.0~prepublish: starwars-names@1.0.0
11 silly lifecycle starwars-names@1.0.0~prepublish: no script for prepublish, continuing
12 verbose tar pack [ 'C:\\Users\\Josephine\\AppData\\Roaming\\npm-cache\\starwars-names\\1.0.0\\package.tgz',
12 verbose tar pack   'E:\\starwars-names' ]
13 verbose tarball C:\Users\Josephine\AppData\Roaming\npm-cache\starwars-names\1.0.0\package.tgz
14 verbose folder E:\starwars-names
15 verbose addLocalTarball adding from inside cache C:\Users\Josephine\AppData\Roaming\npm-cache\starwars-names\1.0.0\package.tgz
16 verbose correctMkdir C:\Users\Josephine\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
17 silly cache afterAdd starwars-names@1.0.0
18 verbose afterAdd C:\Users\Josephine\AppData\Roaming\npm-cache\starwars-names\1.0.0\package\package.json not in flight; writing
19 verbose correctMkdir C:\Users\Josephine\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
20 verbose afterAdd C:\Users\Josephine\AppData\Roaming\npm-cache\starwars-names\1.0.0\package\package.json written
21 silly publish { name: 'starwars-names',
21 silly publish   version: '1.0.0',
21 silly publish   description: 'Get random Star Wars names',
21 silly publish   main: 'src/index.js',
21 silly publish   scripts: { test: 'echo "Error: no test specified" && exit 1' },
21 silly publish   repository:
21 silly publish    { type: 'git',
21 silly publish      url: 'git+https://github.com/costel-petrescu/starwars-names.git' },
21 silly publish   keywords: [ 'random', 'star', 'wars' ],
21 silly publish   author:
21 silly publish    { name: 'Costel Pertrescu',
21 silly publish      email: 'costel.petrescu12@gmail.com',
21 silly publish      url: 'http://costel-petrescu.com/' },
21 silly publish   license: 'MIT',
21 silly publish   bugs: { url: 'https://github.com/costel-petrescu/starwars-names/issues' },
21 silly publish   homepage: 'https://github.com/costel-petrescu/starwars-names#readme',
21 silly publish   dependencies: { 'unique-random-array': '1.0.0' },
21 silly publish   readme: '# starwars-names\n',
21 silly publish   readmeFilename: 'README.md',
21 silly publish   gitHead: '83ba4c240e5fefdd6c9bf38e6f1b247c426d2482',
21 silly publish   _id: 'starwars-names@1.0.0',
21 silly publish   _shasum: 'ad2e8285c7d54b53a6e1a9c4836c30ad168902b1',
21 silly publish   _from: '.' }
22 verbose getPublishConfig undefined
23 silly mapToRegistry name starwars-names
24 silly mapToRegistry using default registry
25 silly mapToRegistry registry https://registry.npmjs.org/
26 silly mapToRegistry data Result {
26 silly mapToRegistry   raw: 'starwars-names',
26 silly mapToRegistry   scope: null,
26 silly mapToRegistry   escapedName: 'starwars-names',
26 silly mapToRegistry   name: 'starwars-names',
26 silly mapToRegistry   rawSpec: '',
26 silly mapToRegistry   spec: 'latest',
26 silly mapToRegistry   type: 'tag' }
27 silly mapToRegistry uri https://registry.npmjs.org/starwars-names
28 verbose publish registryBase https://registry.npmjs.org/
29 silly publish uploading C:\Users\Josephine\AppData\Roaming\npm-cache\starwars-names\1.0.0\package.tgz
30 verbose request uri https://registry.npmjs.org/starwars-names
31 verbose request sending authorization for write operation
32 info attempt registry request try #1 at 4:54:26 AM
33 verbose request using bearer token for auth
34 verbose request id c029f90b47dc28c6
35 http request PUT https://registry.npmjs.org/starwars-names
36 http 403 https://registry.npmjs.org/starwars-names
37 verbose headers { 'content-type': 'application/json',
37 verbose headers   'cache-control': 'max-age=300',
37 verbose headers   'content-length': '108',
37 verbose headers   'accept-ranges': 'bytes',
37 verbose headers   date: 'Tue, 30 May 2017 01:54:27 GMT',
37 verbose headers   via: '1.1 varnish',
37 verbose headers   connection: 'keep-alive',
37 verbose headers   'x-served-by': 'cache-den6020-DEN',
37 verbose headers   'x-cache': 'MISS',
37 verbose headers   'x-cache-hits': '0',
37 verbose headers   'x-timer': 'S1496109267.033956,VS0,VE497',
37 verbose headers   vary: 'Accept-Encoding' }
38 verbose request invalidating C:\Users\Josephine\AppData\Roaming\npm-cache\registry.npmjs.org\starwars-names on PUT
39 error publish Failed PUT 403
40 verbose stack Error: you do not have permission to publish "starwars-names". Are you logged in as the correct user? : starwars-names
40 verbose stack     at makeError (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:302:12)
40 verbose stack     at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:290:14)
40 verbose stack     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:210:14)
40 verbose stack     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:187:22)
40 verbose stack     at emitTwo (events.js:106:13)
40 verbose stack     at Request.emit (events.js:191:7)
40 verbose stack     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1048:10)
40 verbose stack     at emitOne (events.js:96:13)
40 verbose stack     at Request.emit (events.js:188:7)
40 verbose stack     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:969:12)
41 verbose statusCode 403
42 verbose pkgid starwars-names
43 verbose cwd E:\starwars-names
44 error Windows_NT 10.0.14393
45 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "publish"
46 error node v6.10.3
47 error npm  v3.10.10
48 error code E403
49 error you do not have permission to publish "starwars-names". Are you logged in as the correct user? : starwars-names
50 error If you need help, you may report this error at:
50 error     <https://github.com/npm/npm/issues>
51 verbose exit [ 1, true ]
```
what's the reason? how can i fix the error?
please, give me the answer.
thanks for your times.
