### ISSUE TITLE
The problem while calling "npm install"

### ISSUE THREAD

**Issue by dpgn-framework** [npm/npm#16765]
I have error when calling "npm install"
Please help me

Here is error:
```
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10

npm ERR! shasum check failed for C:\Users\giangnam\AppData\Local\Temp\npm-10656-263d4d28\registry.npmjs.org\http-server\-\http-server-0.9.0.tgz
npm ERR! Expected: 8f1b06bdc733618d4dc42831c7ba1aff4e06001a
npm ERR! Actual:   2e87621f409d8f03307a528687965e321f962c87
npm ERR! From:     https://registry.npmjs.org/http-server/-/http-server-0.9.0.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

Here is my logs:
```
2860 verbose addNamed "6.24.1" is a plain semver version for babel-cli
2861 silly cache afterAdd karma-phantomjs-launcher@1.0.4
2862 verbose afterAdd C:\Users\giangnam\AppData\Roaming\npm-cache\karma-phantomjs-launcher\1.0.4\package\package.json not in flight; writing
2863 verbose correctMkdir C:\Users\giangnam\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
2864 silly mapToRegistry name babel-cli
2865 silly mapToRegistry using default registry
2866 silly mapToRegistry registry https://registry.npmjs.org/
2867 silly mapToRegistry data Result {
2867 silly mapToRegistry   raw: 'babel-cli',
2867 silly mapToRegistry   scope: null,
2867 silly mapToRegistry   escapedName: 'babel-cli',
2867 silly mapToRegistry   name: 'babel-cli',
2867 silly mapToRegistry   rawSpec: '',
2867 silly mapToRegistry   spec: 'latest',
2867 silly mapToRegistry   type: 'tag' }
2868 silly mapToRegistry uri https://registry.npmjs.org/babel-cli
2869 verbose addRemoteTarball https://registry.npmjs.org/babel-cli/-/babel-cli-6.24.1.tgz not in flight; adding
2870 verbose addRemoteTarball [ 'https://registry.npmjs.org/babel-cli/-/babel-cli-6.24.1.tgz',
2870 verbose addRemoteTarball   '207cd705bba61489b2ea41b5312341cf6aca2283' ]
2871 http fetch 200 https://registry.npmjs.org/rollup-plugin-commonjs/-/rollup-plugin-commonjs-8.0.2.tgz
2872 info retry fetch attempt 1 at 5:39:03 PM
2873 info attempt registry request try #1 at 5:39:03 PM
2874 http fetch GET https://registry.npmjs.org/babel-cli/-/babel-cli-6.24.1.tgz
2875 verbose afterAdd C:\Users\giangnam\AppData\Roaming\npm-cache\lite-server\2.3.0\package\package.json written
2876 verbose afterAdd C:\Users\giangnam\AppData\Roaming\npm-cache\karma-phantomjs-launcher\1.0.4\package\package.json written
2877 http fetch 200 https://registry.npmjs.org/protractor/-/protractor-4.0.14.tgz
2878 http fetch 200 https://registry.npmjs.org/rollup-plugin-uglify/-/rollup-plugin-uglify-1.0.2.tgz
2879 silly fetchAndShaCheck shasum d4aa6f5df13522eae1ba17780c7c4c7096038359
2880 silly fetchAndShaCheck shasum 6f83ab3a0f16951722ce07d206c773d57cc838be
2881 verbose addTmpTarball C:\Users\giangnam\AppData\Local\Temp\npm-10656-263d4d28\registry.npmjs.org\rollup-plugin-uglify\-\rollup-plugin-uglify-1.0.2.tgz not in flight; adding
2882 verbose addTmpTarball already have metadata; skipping unpack for rollup-plugin-uglify@1.0.2
2883 verbose correctMkdir C:\Users\giangnam\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
2884 verbose addTmpTarball C:\Users\giangnam\AppData\Local\Temp\npm-10656-263d4d28\registry.npmjs.org\jasmine-core\-\jasmine-core-2.4.1.tgz not in flight; adding
2885 verbose addTmpTarball already have metadata; skipping unpack for jasmine-core@2.4.1
2886 verbose correctMkdir C:\Users\giangnam\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
2887 http fetch 200 https://registry.npmjs.org/karma-jasmine/-/karma-jasmine-1.1.0.tgz
2888 silly cache afterAdd rollup-plugin-uglify@1.0.2
2889 verbose afterAdd C:\Users\giangnam\AppData\Roaming\npm-cache\rollup-plugin-uglify\1.0.2\package\package.json not in flight; writing
2890 verbose correctMkdir C:\Users\giangnam\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
2891 silly cache afterAdd jasmine-core@2.4.1
2892 verbose afterAdd C:\Users\giangnam\AppData\Roaming\npm-cache\jasmine-core\2.4.1\package\package.json not in flight; writing
2893 verbose correctMkdir C:\Users\giangnam\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
2894 verbose afterAdd C:\Users\giangnam\AppData\Roaming\npm-cache\rollup-plugin-uglify\1.0.2\package\package.json written
2895 verbose afterAdd C:\Users\giangnam\AppData\Roaming\npm-cache\jasmine-core\2.4.1\package\package.json written
2896 silly fetchAndShaCheck shasum 22e4c06bf9a182e5294d1f705e3733811b810acf
2897 verbose addTmpTarball C:\Users\giangnam\AppData\Local\Temp\npm-10656-263d4d28\registry.npmjs.org\karma-jasmine\-\karma-jasmine-1.1.0.tgz not in flight; adding
2898 verbose addTmpTarball already have metadata; skipping unpack for karma-jasmine@1.1.0
2899 verbose correctMkdir C:\Users\giangnam\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
2900 silly cache afterAdd karma-jasmine@1.1.0
2901 verbose afterAdd C:\Users\giangnam\AppData\Roaming\npm-cache\karma-jasmine\1.1.0\package\package.json not in flight; writing
2902 verbose correctMkdir C:\Users\giangnam\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
2903 verbose afterAdd C:\Users\giangnam\AppData\Roaming\npm-cache\karma-jasmine\1.1.0\package\package.json written
2904 http fetch 200 https://registry.npmjs.org/tslint/-/tslint-3.15.1.tgz
2905 silly fetchAndShaCheck shasum d53d311fcfb7d1d08ddb24014558f1188c516da0
2906 verbose addTmpTarball C:\Users\giangnam\AppData\Local\Temp\npm-10656-263d4d28\registry.npmjs.org\phantomjs-prebuilt\-\phantomjs-prebuilt-2.1.14.tgz not in flight; adding
2907 verbose addTmpTarball already have metadata; skipping unpack for phantomjs-prebuilt@2.1.14
2908 verbose correctMkdir C:\Users\giangnam\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
2909 silly cache afterAdd phantomjs-prebuilt@2.1.14
2910 verbose afterAdd C:\Users\giangnam\AppData\Roaming\npm-cache\phantomjs-prebuilt\2.1.14\package\package.json not in flight; writing
2911 verbose correctMkdir C:\Users\giangnam\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
2912 verbose afterAdd C:\Users\giangnam\AppData\Roaming\npm-cache\phantomjs-prebuilt\2.1.14\package\package.json written
2913 http fetch 200 https://registry.npmjs.org/rollup/-/rollup-0.41.6.tgz
2914 http fetch 200 https://registry.npmjs.org/babel-cli/-/babel-cli-6.24.1.tgz
2915 silly fetchAndShaCheck shasum 207cd705bba61489b2ea41b5312341cf6aca2283
2916 http fetch 200 https://registry.npmjs.org/source-map-explorer/-/source-map-explorer-1.3.3.tgz
2917 verbose addTmpTarball C:\Users\giangnam\AppData\Local\Temp\npm-10656-263d4d28\registry.npmjs.org\babel-cli\-\babel-cli-6.24.1.tgz not in flight; adding
2918 verbose addTmpTarball already have metadata; skipping unpack for babel-cli@6.24.1
2919 verbose correctMkdir C:\Users\giangnam\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
2920 silly cache afterAdd babel-cli@6.24.1
2921 verbose afterAdd C:\Users\giangnam\AppData\Roaming\npm-cache\babel-cli\6.24.1\package\package.json not in flight; writing
2922 verbose correctMkdir C:\Users\giangnam\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
2923 verbose afterAdd C:\Users\giangnam\AppData\Roaming\npm-cache\babel-cli\6.24.1\package\package.json written
2924 http fetch 200 https://registry.npmjs.org/babel-preset-angular2/-/babel-preset-angular2-0.0.2.tgz
2925 silly fetchAndShaCheck shasum a9443215eafdcc9f012ac22bf2171c9d43c8b221
2926 verbose addTmpTarball C:\Users\giangnam\AppData\Local\Temp\npm-10656-263d4d28\registry.npmjs.org\babel-preset-angular2\-\babel-preset-angular2-0.0.2.tgz not in flight; adding
2927 verbose addTmpTarball already have metadata; skipping unpack for babel-preset-angular2@0.0.2
2928 verbose correctMkdir C:\Users\giangnam\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
2929 silly cache afterAdd babel-preset-angular2@0.0.2
2930 verbose afterAdd C:\Users\giangnam\AppData\Roaming\npm-cache\babel-preset-angular2\0.0.2\package\package.json not in flight; writing
2931 verbose correctMkdir C:\Users\giangnam\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
2932 verbose afterAdd C:\Users\giangnam\AppData\Roaming\npm-cache\babel-preset-angular2\0.0.2\package\package.json written
2933 silly fetchAndShaCheck shasum 6f7a1a406446fa2e187ec95398698f4cee476269
2934 verbose addTmpTarball C:\Users\giangnam\AppData\Local\Temp\npm-10656-263d4d28\registry.npmjs.org\karma\-\karma-1.7.0.tgz not in flight; adding
2935 verbose addTmpTarball already have metadata; skipping unpack for karma@1.7.0
2936 verbose correctMkdir C:\Users\giangnam\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
2937 silly cache afterAdd karma@1.7.0
2938 verbose afterAdd C:\Users\giangnam\AppData\Roaming\npm-cache\karma\1.7.0\package\package.json not in flight; writing
2939 verbose correctMkdir C:\Users\giangnam\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
2940 verbose afterAdd C:\Users\giangnam\AppData\Roaming\npm-cache\karma\1.7.0\package\package.json written
2941 http fetch 200 https://registry.npmjs.org/@types/angular-sanitize/-/angular-sanitize-1.3.4.tgz
2942 silly fetchAndShaCheck shasum aa63bd32a1c3c8846e16d66be891a5bdb3b0fc65
2943 verbose addTmpTarball C:\Users\giangnam\AppData\Local\Temp\npm-10656-263d4d28\registry.npmjs.org\_40types\angular-sanitize\-\angular-sanitize-1.3.4.tgz not in flight; adding
2944 verbose addTmpTarball already have metadata; skipping unpack for @types/angular-sanitize@1.3.4
2945 verbose correctMkdir C:\Users\giangnam\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
2946 silly cache afterAdd @types/angular-sanitize@1.3.4
2947 verbose afterAdd C:\Users\giangnam\AppData\Roaming\npm-cache\@types\angular-sanitize\1.3.4\package\package.json not in flight; writing
2948 verbose correctMkdir C:\Users\giangnam\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
2949 verbose afterAdd C:\Users\giangnam\AppData\Roaming\npm-cache\@types\angular-sanitize\1.3.4\package\package.json written
2950 http fetch 200 https://registry.npmjs.org/@types/angular-mocks/-/angular-mocks-1.5.9.tgz
2951 silly fetchAndShaCheck shasum 4d91bb71a5cfb000d02b02133bc98c20f57101fd
2952 verbose addTmpTarball C:\Users\giangnam\AppData\Local\Temp\npm-10656-263d4d28\registry.npmjs.org\_40types\angular-mocks\-\angular-mocks-1.5.9.tgz not in flight; adding
2953 verbose addTmpTarball already have metadata; skipping unpack for @types/angular-mocks@1.5.9
2954 verbose correctMkdir C:\Users\giangnam\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
2955 silly cache afterAdd @types/angular-mocks@1.5.9
2956 verbose afterAdd C:\Users\giangnam\AppData\Roaming\npm-cache\@types\angular-mocks\1.5.9\package\package.json not in flight; writing
2957 verbose correctMkdir C:\Users\giangnam\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
2958 verbose afterAdd C:\Users\giangnam\AppData\Roaming\npm-cache\@types\angular-mocks\1.5.9\package\package.json written
2959 silly fetchAndShaCheck shasum 98b1589bfe32a6c0f67790b60c0b499972afed89
2960 verbose addTmpTarball C:\Users\giangnam\AppData\Local\Temp\npm-10656-263d4d28\registry.npmjs.org\rollup-plugin-commonjs\-\rollup-plugin-commonjs-8.0.2.tgz not in flight; adding
2961 verbose addTmpTarball already have metadata; skipping unpack for rollup-plugin-commonjs@8.0.2
2962 verbose correctMkdir C:\Users\giangnam\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
2963 silly cache afterAdd rollup-plugin-commonjs@8.0.2
2964 verbose afterAdd C:\Users\giangnam\AppData\Roaming\npm-cache\rollup-plugin-commonjs\8.0.2\package\package.json not in flight; writing
2965 verbose correctMkdir C:\Users\giangnam\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
2966 verbose afterAdd C:\Users\giangnam\AppData\Roaming\npm-cache\rollup-plugin-commonjs\8.0.2\package\package.json written
2967 http fetch 200 https://registry.npmjs.org/@types/jasmine/-/jasmine-2.5.36.tgz
2968 silly fetchAndShaCheck shasum 6d804b79a57e9380d766a2680e9362c17d9556d2
2969 verbose addTmpTarball C:\Users\giangnam\AppData\Local\Temp\npm-10656-263d4d28\registry.npmjs.org\_40types\jasmine\-\jasmine-2.5.36.tgz not in flight; adding
2970 verbose addTmpTarball already have metadata; skipping unpack for @types/jasmine@2.5.36
2971 verbose correctMkdir C:\Users\giangnam\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
2972 silly cache afterAdd @types/jasmine@2.5.36
2973 verbose afterAdd C:\Users\giangnam\AppData\Roaming\npm-cache\@types\jasmine\2.5.36\package\package.json not in flight; writing
2974 verbose correctMkdir C:\Users\giangnam\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
2975 verbose afterAdd C:\Users\giangnam\AppData\Roaming\npm-cache\@types\jasmine\2.5.36\package\package.json written
2976 http fetch 200 https://registry.npmjs.org/@types/angular-resource/-/angular-resource-1.5.8.tgz
2977 silly fetchAndShaCheck shasum 39033ae67d1012aae68a2aa1650d89bb404d35ce
2978 verbose addTmpTarball C:\Users\giangnam\AppData\Local\Temp\npm-10656-263d4d28\registry.npmjs.org\_40types\angular-resource\-\angular-resource-1.5.8.tgz not in flight; adding
2979 verbose addTmpTarball already have metadata; skipping unpack for @types/angular-resource@1.5.8
2980 verbose correctMkdir C:\Users\giangnam\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
2981 silly cache afterAdd @types/angular-resource@1.5.8
2982 verbose afterAdd C:\Users\giangnam\AppData\Roaming\npm-cache\@types\angular-resource\1.5.8\package\package.json not in flight; writing
2983 verbose correctMkdir C:\Users\giangnam\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
2984 verbose afterAdd C:\Users\giangnam\AppData\Roaming\npm-cache\@types\angular-resource\1.5.8\package\package.json written
2985 silly fetchAndShaCheck shasum ff15cb038465fb652e57fa54ecd103f51e01bc43
2986 http fetch 200 https://registry.npmjs.org/@types/angular-cookies/-/angular-cookies-1.4.3.tgz
2987 verbose addTmpTarball C:\Users\giangnam\AppData\Local\Temp\npm-10656-263d4d28\registry.npmjs.org\source-map-explorer\-\source-map-explorer-1.3.3.tgz not in flight; adding
2988 verbose addTmpTarball already have metadata; skipping unpack for source-map-explorer@1.3.3
2989 verbose correctMkdir C:\Users\giangnam\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
2990 silly fetchAndShaCheck shasum 13056d07532945be74e1a63b081e92b0262c6a59
2991 verbose addTmpTarball C:\Users\giangnam\AppData\Local\Temp\npm-10656-263d4d28\registry.npmjs.org\_40types\angular-cookies\-\angular-cookies-1.4.3.tgz not in flight; adding
2992 verbose addTmpTarball already have metadata; skipping unpack for @types/angular-cookies@1.4.3
2993 verbose correctMkdir C:\Users\giangnam\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
2994 silly cache afterAdd source-map-explorer@1.3.3
2995 verbose afterAdd C:\Users\giangnam\AppData\Roaming\npm-cache\source-map-explorer\1.3.3\package\package.json not in flight; writing
2996 verbose correctMkdir C:\Users\giangnam\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
2997 silly cache afterAdd @types/angular-cookies@1.4.3
2998 verbose afterAdd C:\Users\giangnam\AppData\Roaming\npm-cache\@types\angular-cookies\1.4.3\package\package.json not in flight; writing
2999 verbose correctMkdir C:\Users\giangnam\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
3000 verbose afterAdd C:\Users\giangnam\AppData\Roaming\npm-cache\source-map-explorer\1.3.3\package\package.json written
3001 verbose afterAdd C:\Users\giangnam\AppData\Roaming\npm-cache\@types\angular-cookies\1.4.3\package\package.json written
3002 silly fetchAndShaCheck shasum 606022508479b55ffa368b58fee963a03dfd7b0c
3003 http fetch 200 https://registry.npmjs.org/@types/angular/-/angular-1.6.17.tgz
3004 verbose addTmpTarball C:\Users\giangnam\AppData\Local\Temp\npm-10656-263d4d28\registry.npmjs.org\typescript\-\typescript-2.2.2.tgz not in flight; adding
3005 verbose addTmpTarball already have metadata; skipping unpack for typescript@2.2.2
3006 verbose correctMkdir C:\Users\giangnam\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
3007 silly fetchAndShaCheck shasum 5bd59e77350943ffbffb8bb98dfe718acbb6ed27
3008 verbose addTmpTarball C:\Users\giangnam\AppData\Local\Temp\npm-10656-263d4d28\registry.npmjs.org\_40types\angular\-\angular-1.6.17.tgz not in flight; adding
3009 verbose addTmpTarball already have metadata; skipping unpack for @types/angular@1.6.17
3010 verbose correctMkdir C:\Users\giangnam\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
3011 silly cache afterAdd @types/angular@1.6.17
3012 verbose afterAdd C:\Users\giangnam\AppData\Roaming\npm-cache\@types\angular\1.6.17\package\package.json not in flight; writing
3013 verbose correctMkdir C:\Users\giangnam\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
3014 silly cache afterAdd typescript@2.2.2
3015 verbose afterAdd C:\Users\giangnam\AppData\Roaming\npm-cache\typescript\2.2.2\package\package.json not in flight; writing
3016 verbose correctMkdir C:\Users\giangnam\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
3017 verbose afterAdd C:\Users\giangnam\AppData\Roaming\npm-cache\@types\angular\1.6.17\package\package.json written
3018 verbose afterAdd C:\Users\giangnam\AppData\Roaming\npm-cache\typescript\2.2.2\package\package.json written
3019 http fetch 200 https://registry.npmjs.org/@types/angular-animate/-/angular-animate-1.5.6.tgz
3020 silly fetchAndShaCheck shasum 43b095185b19e37339bb9d61b1b970461266730e
3021 verbose addTmpTarball C:\Users\giangnam\AppData\Local\Temp\npm-10656-263d4d28\registry.npmjs.org\_40types\angular-animate\-\angular-animate-1.5.6.tgz not in flight; adding
3022 verbose addTmpTarball already have metadata; skipping unpack for @types/angular-animate@1.5.6
3023 verbose correctMkdir C:\Users\giangnam\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
3024 silly cache afterAdd @types/angular-animate@1.5.6
3025 verbose afterAdd C:\Users\giangnam\AppData\Roaming\npm-cache\@types\angular-animate\1.5.6\package\package.json not in flight; writing
3026 verbose correctMkdir C:\Users\giangnam\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
3027 verbose afterAdd C:\Users\giangnam\AppData\Roaming\npm-cache\@types\angular-animate\1.5.6\package\package.json written
3028 silly fetchAndShaCheck shasum da165ca93d8fdc2c086b51165ee1bacb48c98ea5
3029 verbose addTmpTarball C:\Users\giangnam\AppData\Local\Temp\npm-10656-263d4d28\registry.npmjs.org\tslint\-\tslint-3.15.1.tgz not in flight; adding
3030 verbose addTmpTarball already have metadata; skipping unpack for tslint@3.15.1
3031 verbose correctMkdir C:\Users\giangnam\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
3032 silly cache afterAdd tslint@3.15.1
3033 verbose afterAdd C:\Users\giangnam\AppData\Roaming\npm-cache\tslint\3.15.1\package\package.json not in flight; writing
3034 verbose correctMkdir C:\Users\giangnam\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
3035 verbose afterAdd C:\Users\giangnam\AppData\Roaming\npm-cache\tslint\3.15.1\package\package.json written
3036 http fetch 200 https://registry.npmjs.org/@types/angular-route/-/angular-route-1.3.3.tgz
3037 silly fetchAndShaCheck shasum 3dac9edba1c44ea75b696b08fc8b4cd5466b96ff
3038 verbose addTmpTarball C:\Users\giangnam\AppData\Local\Temp\npm-10656-263d4d28\registry.npmjs.org\_40types\angular-route\-\angular-route-1.3.3.tgz not in flight; adding
3039 verbose addTmpTarball already have metadata; skipping unpack for @types/angular-route@1.3.3
3040 verbose correctMkdir C:\Users\giangnam\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
3041 silly fetchAndShaCheck shasum efc4a877fac3a182a9dded26cd5869f4762fd172
3042 verbose addTmpTarball C:\Users\giangnam\AppData\Local\Temp\npm-10656-263d4d28\registry.npmjs.org\protractor\-\protractor-4.0.14.tgz not in flight; adding
3043 verbose addTmpTarball already have metadata; skipping unpack for protractor@4.0.14
3044 verbose correctMkdir C:\Users\giangnam\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
3045 silly cache afterAdd @types/angular-route@1.3.3
3046 verbose afterAdd C:\Users\giangnam\AppData\Roaming\npm-cache\@types\angular-route\1.3.3\package\package.json not in flight; writing
3047 verbose correctMkdir C:\Users\giangnam\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
3048 verbose afterAdd C:\Users\giangnam\AppData\Roaming\npm-cache\@types\angular-route\1.3.3\package\package.json written
3049 silly cache afterAdd protractor@4.0.14
3050 verbose afterAdd C:\Users\giangnam\AppData\Roaming\npm-cache\protractor\4.0.14\package\package.json not in flight; writing
3051 verbose correctMkdir C:\Users\giangnam\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
3052 verbose afterAdd C:\Users\giangnam\AppData\Roaming\npm-cache\protractor\4.0.14\package\package.json written
3053 info retry will retry, error on last attempt: Error: 101057795:error:1408F119:SSL routines:SSL3_GET_RECORD:decryption failed or bad record mac:openssl\ssl\s3_pkt.c:535:
3054 silly fetchAndShaCheck shasum e0d05497877a398c104d816d2733a718a7a94e2a
3055 silly rollbackFailedOptional Starting
3056 silly rollbackFailedOptional Finishing
3057 silly runTopLevelLifecycles Finishing
3058 silly install printInstalled
3059 verbose stack Error: shasum check failed for C:\Users\giangnam\AppData\Local\Temp\npm-10656-263d4d28\registry.npmjs.org\http-server\-\http-server-0.9.0.tgz
3059 verbose stack Expected: 8f1b06bdc733618d4dc42831c7ba1aff4e06001a
3059 verbose stack Actual:   2e87621f409d8f03307a528687965e321f962c87
3059 verbose stack From:     https://registry.npmjs.org/http-server/-/http-server-0.9.0.tgz
3059 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\sha\index.js:25:8
3059 verbose stack     at ReadStream.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\sha\index.js:72:7)
3059 verbose stack     at emitNone (events.js:91:20)
3059 verbose stack     at ReadStream.emit (events.js:185:7)
3059 verbose stack     at endReadableNT (_stream_readable.js:974:12)
3059 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:80:11)
3059 verbose stack     at process._tickCallback (internal/process/next_tick.js:104:9)
3060 verbose cwd C:\Data\Projects\2015\Angular4-v1\Angular4-v1
3061 error Windows_NT 10.0.15063
3062 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
3063 error node v6.10.3
3064 error npm  v3.10.10
3065 error shasum check failed for C:\Users\giangnam\AppData\Local\Temp\npm-10656-263d4d28\registry.npmjs.org\http-server\-\http-server-0.9.0.tgz
3065 error Expected: 8f1b06bdc733618d4dc42831c7ba1aff4e06001a
3065 error Actual:   2e87621f409d8f03307a528687965e321f962c87
3065 error From:     https://registry.npmjs.org/http-server/-/http-server-0.9.0.tgz
3066 error If you need help, you may report this error at:
3066 error     <https://github.com/npm/npm/issues>
3067 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
Does this also occur with newer versions of `npm`?

**Comment by sreejithp3** [comment]
The same issue occurred for me as well. Could you please help me on this ?

Please find the logs below.

144471 verbose stack Error: shasum check failed for C:\Users\A-5605\AppData\Local\Temp\npm-7800-e52dddd5\nexuslab.alm\nexus\content\groups\npm-all\socket.io-client\-\socket.io-client-1.7.4.tgz
144471 verbose stack Expected: ec9f820356ed99ef6d357f0756d648717bdd4281
144471 verbose stack Actual:   3df33d8a40752fdf5a3f542aa28b9f83fb358c8b
144471 verbose stack From:     http://nexuslab.alm/nexus/content/groups/npm-all/socket.io-client/-/socket.io-client-1.7.4.tgz
144471 verbose stack     at D:\dev\Latest-May2017\globalcontrols-service\content\node\node_modules\npm\node_modules\sha\index.js:25:8
144471 verbose stack     at ReadStream.<anonymous> (D:\dev\Latest-May2017\globalcontrols-service\content\node\node_modules\npm\node_modules\sha\index.js:72:7)
144471 verbose stack     at emitNone (events.js:72:20)
144471 verbose stack     at ReadStream.emit (events.js:166:7)
144471 verbose stack     at endReadableNT (_stream_readable.js:921:12)
144471 verbose stack     at nextTickCallbackWith2Args (node.js:442:9)
144471 verbose stack     at process._tickCallback (node.js:356:17)
144472 verbose cwd D:\dev\Latest-May2017\globalcontrols-service\content
144473 error Windows_NT 6.1.7601
144474 error argv "D:\\dev\\Latest-May2017\\globalcontrols-service\\content\\node\\node.exe" "D:\\dev\\Latest-May2017\\globalcontrols-service\\content\\node\\node_modules\\npm\\bin\\npm-cli.js" "install" "--msvs_version=2015"
144475 error node v4.5.0
144476 error npm  v2.15.9
144477 error shasum check failed for C:\Users\A-5605\AppData\Local\Temp\npm-7800-e52dddd5\nexuslab.alm\nexus\content\groups\npm-all\socket.io-client\-\socket.io-client-1.7.4.tgz
144477 error Expected: ec9f820356ed99ef6d357f0756d648717bdd4281
144477 error Actual:   3df33d8a40752fdf5a3f542aa28b9f83fb358c8b
144477 error From:     http://nexuslab.alm/nexus/content/groups/npm-all/socket.io-client/-/socket.io-client-1.7.4.tgz
144478 error If you need help, you may report this error at:
144478 error     <https://github.com/npm/npm/issues>
144479 verbose exit [ 1, true ]
144480 verbose unbuild node_modules\karma\node_modules\socket.io
144481 info preuninstall socket.io@1.7.4

**Comment by mtirumala** [comment]
The same issue occurred for me as well. Could you please help me on this ?
npm-debug.log

1748 verbose cwd C:\paypal\mppnodeweb
1749 error Windows_NT 10.0.14393
1750 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
1751 error node v6.10.3
1752 error npm  v3.10.10
1753 error Cannot convert undefined or null to object
1754 error If you need help, you may report this error at:
1754 error     <https://github.com/npm/npm/issues>
1755 verbose exit [ 1, true ]

**Comment by kenany** [comment]
@sreejithp3 See https://github.com/npm/npm/issues/16765#issuecomment-304519373.

@mtirumala Doesn't look like the same issue. Could you open a new ticket, and provide the full `npm-debug.log` file?
