### ISSUE TITLE
npm problem when running webpack ?

### ISSUE THREAD

**Issue by ramintagizade** [npm/npm#16782]
ERROR in ./js/index.js
Module build failed: Error: Couldn't find preset "stage-0" relative to directory "/Users/ramintaghizada/Desktop/freeCodeCamp/Projects/Data-Visualisation-Projects/MarkdownPreviewer/src/js"
    at /Users/ramintaghizada/node_modules/babel-core/lib/transformation/file/options/option-manager.js:321:17
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/ramintaghizada/node_modules/babel-core/lib/transformation/file/options/option-manager.js:305:20)
    at OptionManager.mergePresets (/Users/ramintaghizada/node_modules/babel-core/lib/transformation/file/options/option-manager.js:288:10)
    at OptionManager.mergeOptions (/Users/ramintaghizada/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:14)
    at OptionManager.init (/Users/ramintaghizada/node_modules/babel-core/lib/transformation/file/options/option-manager.js:383:12)
    at File.initOptions (/Users/ramintaghizada/node_modules/babel-core/lib/transformation/file/index.js:223:65)
    at new File (/Users/ramintaghizada/node_modules/babel-core/lib/transformation/file/index.js:140:24)
    at Pipeline.transform (/Users/ramintaghizada/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/ramintaghizada/node_modules/babel-loader/lib/index.js:38:20)
    at Object.module.exports (/Users/ramintaghizada/node_modules/babel-loader/lib/index.js:133:12)

**Comment by KenanY** [comment]
Doesn't seem like this is coming from `npm`. Probably just need to

```
npm install babel-preset-stage-0
```

**Comment by ramintagizade** [comment]
Webpack worked with previous node_modules ,so i had to delete the latest installed node_modules .
