### ISSUE TITLE
NPM 5.0 breaks on older versions of node

### ISSUE THREAD

**Issue by doodirock** [npm/npm#16809]
#### I'm opening this issue because:

  - [X] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I've updated NPM on my local machine to 5.0.  However my node version is stuck at 4.4.7.  So now when i run npm on anything I get the following:

```
Unhandled rejection TypeError: base64 is not a functionng node@v4.4.7
    at Function.from (native)
    at Function.from (native)
    at bufFrom (/usr/local/lib/node_modules/npm/node_modules/ssri/index.js:337:31)
    at Hash.hexDigest (/usr/local/lib/node_modules/npm/node_modules/ssri/index.js:34:27)
    at contentPath (/usr/local/lib/node_modules/npm/node_modules/cacache/lib/content/path.js:20:31)
    at moveToDestination (/usr/local/lib/node_modules/npm/node_modules/cacache/lib/content/write.js:131:23)
    at /usr/local/lib/node_modules/npm/node_modules/cacache/lib/content/write.js:39:7
    at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:638:18)
    at /usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/nodeback.js:42:21
    at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:99:16
    at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:43:10

npm ERR! cb() never called!
```

The problem is that I can't update my version of node with 

```
sudo npm cache clean -f
sudo npm install -g n
sudo n stable
```

because of the error.  So now im stuck

#### How can the CLI team reproduce the problem?

upgrade npm to 5.0 while on node 4.4.7.  Do anything with npm

### supporting information:

 - `npm -v` prints: 5.0
 - `node -v` prints: 4.4.7
 - Linux

**Comment by zkat** [comment]
This will be fixed with 5.0.1.

**Comment by AceChen1** [comment]
I also have this error, how can i update success?

**Comment by zkat** [comment]
@AceChen1 wait until npm@5.0.1 comes out in the next day or two

**Comment by zkat** [comment]
I'm just gonna keep this issue open til then

**Comment by micktaiwan** [comment]
How do we update to npm 5.0.1 if npm is broken ?

**Comment by zkat** [comment]
@micktaiwan: `curl -L https://www.npmjs.org/install.sh | sh`

**Comment by zkat** [comment]
@doodirock: could you confirm that this is fixed in 5.0.1?

**Comment by doodirock** [comment]
Can't upgrade to test fix. 

```
Unhandled rejection Error: Argument #2: Expected string but got null url-parse-lax@^1.0.0 fetched in 61ms
    at addDependency (/tmp/npm.8970/package/lib/install/deps.js:515:3)
    at /tmp/npm.8970/package/lib/install/deps.js:463:5
    at /tmp/npm.8970/package/node_modules/slide/lib/async-map.js:52:35
    at Array.forEach (native)
    at /tmp/npm.8970/package/node_modules/slide/lib/async-map.js:52:11
    at Array.forEach (native)
    at asyncMap (/tmp/npm.8970/package/node_modules/slide/lib/async-map.js:51:8)
    at loadDeps (/tmp/npm.8970/package/lib/install/deps.js:455:3)
    at Array.<anonymous> (/tmp/npm.8970/package/node_modules/slide/lib/bind-actor.js:15:8)
    at LOOP (/tmp/npm.8970/package/node_modules/slide/lib/chain.js:15:14)
    at /tmp/npm.8970/package/node_modules/slide/lib/chain.js:18:7
    at /tmp/npm.8970/package/lib/install/and-finish-tracker.js:8:8
    at /tmp/npm.8970/package/lib/install/deps.js:419:11
    at tryCatcher (/tmp/npm.8970/package/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/tmp/npm.8970/package/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/tmp/npm.8970/package/node_modules/bluebird/js/release/promise.js:569:18)

npm ERR! cb() never called!
```


useing `curl -L https://www.npmjs.org/install.sh | sh`

**Comment by doodirock** [comment]
I ended up going the scorched earth route and reinstalling.  Everything is now set at node 8 and npm 5.0.1.  Thanks

**Comment by zkat** [comment]
Awesome, thanks.

It's pretty much expected that if you have a hosed npm, you'll have to burn it all down. Cheers!

**Comment by chuckhacker** [comment]
:( Super frustrating :(((

**Comment by zkat** [comment]
This particular bug, btw, with the `base64`, should be fixed in newer versions of npm5
