### ISSUE TITLE
when I install gulp unit, "Error: Cannot find module 'lodash/fp/isObject'"

### ISSUE THREAD

**Issue by zouyuanhao** [npm/npm#16815]
when I install gulp unit,cmd appear "Error: Cannot find module 'lodash/fp/isObject".
but I run "npm install lodash/fp/isObject",cmd prompt "npm ERR! addLocal Could not install F:\git\yongyou\lodash\fp\isObject
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "G:\\nodejs\\node.exe" "G:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "lodash/fp/isObject" "--save-dev"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! path F:\git\yongyou\lodash\fp\isObject
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open 'F:\git\yongyou\lodash\fp\isObject'
npm ERR! enoent ENOENT: no such file or directory, open 'F:\git\yongyou\lodash\fp\isObject'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     F:\git\yongyou\npm-debug.log
"

**Comment by kenany** [comment]
What command are you running that gives you the `Error: Cannot find module 'lodash/fp/isObject` error?

**Comment by ghost** [comment]
Am facing this error during gulp build
Error: Cannot find module 'lodash/fp/isObject'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\working\locker_client_app\node_modules\gulp-uglify\lib\minify.js:3:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\working\locker_client_app\node_modules\gulp-uglify\composer.js:3:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)

**Comment by brunosilvano** [comment]
I am having the exact same error as @kumarapkvel -> When running a gulp build using gulp-uglify.

@kumarapkvel , did you already found a solution?
