### ISSUE TITLE
npm5: npm install (with blank page name) crashes with `Expected string but got null` if blank package name

### ISSUE THREAD

**Issue by rajivm** [npm/npm#16816]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

If you have an "" (empty string) package name in your package.json, npm does not gracefully validate & fail and instead crashes.

```Unhandled rejection Error: Argument #2: Expected string but got nullapi@8.1.1-dev~preinstall: no script for preinstall, continuing
    at exports.findRequirement (/Users/rajiv/.nvm/versions/node/v8.0.0/lib/node_modules/npm/lib/install/deps.js:648:3)
    at findChild (/Users/rajiv/.nvm/versions/node/v8.0.0/lib/node_modules/npm/lib/install/deps.js:104:17)
    at computeMetadata (/Users/rajiv/.nvm/versions/node/v8.0.0/lib/node_modules/npm/lib/install/deps.js:114:9)
    at Installer.postInstallSteps.push (/Users/rajiv/.nvm/versions/node/v8.0.0/lib/node_modules/npm/lib/install.js:298:28)
    at Array.<anonymous> (/Users/rajiv/.nvm/versions/node/v8.0.0/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
    at LOOP (/Users/rajiv/.nvm/versions/node/v8.0.0/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
    at /Users/rajiv/.nvm/versions/node/v8.0.0/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
    at Installer.finishTracker (/Users/rajiv/.nvm/versions/node/v8.0.0/lib/node_modules/npm/lib/install.js:345:3)
    at Array.<anonymous> (/Users/rajiv/.nvm/versions/node/v8.0.0/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
    at LOOP (/Users/rajiv/.nvm/versions/node/v8.0.0/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
    at /Users/rajiv/.nvm/versions/node/v8.0.0/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
    at Installer.runPostinstallTopLevelLifecycles (/Users/rajiv/.nvm/versions/node/v8.0.0/lib/node_modules/npm/lib/install.js:583:28)
    at Array.<anonymous> (/Users/rajiv/.nvm/versions/node/v8.0.0/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
    at LOOP (/Users/rajiv/.nvm/versions/node/v8.0.0/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
    at /Users/rajiv/.nvm/versions/node/v8.0.0/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
    at asyncMap (/Users/rajiv/.nvm/versions/node/v8.0.0/lib/node_modules/npm/node_modules/slide/lib/async-map.js:27:18)

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

#### How can the CLI team reproduce the problem?

Create a package.json file with a dependency that is named "" and run `npm install`

/Users/rajiv/.npm/_logs/2017-05-31T07_05_33_094Z-debug.log contains
```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/rajiv/.nvm/versions/node/v8.0.0/bin/node',
1 verbose cli   '/Users/rajiv/.nvm/versions/node/v8.0.0/bin/npm',
1 verbose cli   'install' ]
2 info using npm@5.0.0
3 info using node@v8.0.0
4 silly install runPreinstallTopLevelLifecycles
5 silly preinstall soxhub-api@8.1.1-dev
6 info lifecycle soxhub-api@8.1.1-dev~preinstall: soxhub-api@8.1.1-dev
7 silly lifecycle soxhub-api@8.1.1-dev~preinstall: no script for preinstall, continuing
8 silly install loadCurrentTree
9 silly install readLocalPackageData
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 silly install loadShrinkwrap
13 silly install loadAllDepsIntoIdealTree
14 error cb() never called!
15 error This is an error with npm itself. Please report this error at:
16 error <https://github.com/npm/npm/issues>
```

### supporting information:

 - `npm -v` prints: 5.0.0
 - `node -v` prints: v8.0.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Mac OS 10.12.3
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [x] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by matrushka** [comment]
I was having the same problem then I tried ti debug it and noticed that if you don't specify a version number it crashes. So trying it with a version number outputs `removed 1 package in 0.068s` but I the package is still visible with a `npm list -g --depth=0`. Also there's another issue about this  https://github.com/npm/npm/issues/16738

**Comment by zkat** [comment]
nice catch. Thanks for pointing this out :)
