### ISSUE TITLE
npm5: npm install crashes when there is no package.json

### ISSUE THREAD

**Issue by mrkiffie** [npm/npm#16819]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

When running `npm install` in a directory that does not contain a `package.json` file, npm crashes with the following output

```
Unhandled rejection Error: Argument #2: Expected string but got null
    at addDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:515:3)
    at /usr/local/lib/node_modules/npm/lib/install/deps.js:463:5
    at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
    at Array.forEach (native)
    at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
    at Array.forEach (native)
    at asyncMap (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
    at loadDeps (/usr/local/lib/node_modules/npm/lib/install/deps.js:455:3)
    at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
    at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
    at /usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
    at /usr/local/lib/node_modules/npm/lib/install/and-finish-tracker.js:8:8
    at resolveBranchDeps.then (/usr/local/lib/node_modules/npm/lib/install/deps.js:419:11)
    at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mrkiffie/.npm/_logs/2017-05-31T09_24_47_157Z-debug.log
```

The log is
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/8.0.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install' ]
2 info using npm@5.0.0
3 info using node@v8.0.0
4 verbose config Skipping project config: /Users/mrkiffie/.npmrc. (matches userconfig)
5 silly install runPreinstallTopLevelLifecycles
6 silly install loadCurrentTree
7 silly install readLocalPackageData
8 silly install loadIdealTree
9 silly install cloneCurrentTreeToIdealTree
10 silly install loadShrinkwrap
11 silly install loadAllDepsIntoIdealTree
12 error cb() never called!
13 error This is an error with npm itself. Please report this error at:
14 error <https://github.com/npm/npm/issues>
```

#### How can the CLI team reproduce the problem?

- create an empty directory 
- run `npm install`  (`npm i` produces the same behaviour)

### supporting information:

 - `npm -v` prints: 5.0.0
 - `node -v` prints: v8.0.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: OS X 10.11.6
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by topherbuckley** [comment]
I'm having a similar error, though my log is different. I need to npm init before I can install any other packages. I don't remember having to have the package.json in earlier versions of npm. Didn't it used to set up the init automatically if there wasn't one available? 

My command:
````
npm install photo-sphere-viewer
````

My log:
````
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'photo-sphere-viewer' ]
2 info using npm@5.0.0
3 info using node@v7.10.0
4 silly install loadCurrentTree
5 silly install readLocalPackageData
6 http fetch GET 304 https://registry.npmjs.org/photo-sphere-viewer 1123ms (from cache)
7 silly pacote tag manifest for photo-sphere-viewer@latest fetched in 1153ms
8 verbose stack TypeError: Path must be a string. Received undefined
8 verbose stack     at assertPath (path.js:7:11)
8 verbose stack     at Object.relative (path.js:1227:5)
8 verbose stack     at computeVersionSpec (/usr/local/lib/node_modules/npm/lib/install/deps.js:282:27)
8 verbose stack     at Installer.normalizeCurrentTree (/usr/local/lib/node_modules/npm/lib/install.js:370:69)
8 verbose stack     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
8 verbose stack     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
8 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
8 verbose stack     at iferr (/usr/local/lib/node_modules/npm/lib/install.js:328:5)
8 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/iferr/index.js:13:50
8 verbose stack     at cb (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
8 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/call-limit/call-limit.js:22:12
8 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:73:7)
8 verbose stack     at process._tickCallback (internal/process/next_tick.js:104:9)
9 verbose cwd /home/christopher/Software/VR_View_draft
10 verbose Linux 4.8.0-52-generic
11 verbose argv "/usr/bin/nodejs" "/usr/local/bin/npm" "install" "photo-sphere-viewer"
12 verbose node v7.10.0
13 verbose npm  v5.0.0
14 error Path must be a string. Received undefined
15 verbose exit [ 1, true ]

````

This is resolved if I set up a default package.json file by using npm init

npm 5.0.0
node 7.10.0
npm config get registry   https://registry.npmjs.org/
Linux Ubuntu 16.04

**Comment by yangxiaoguang2013** [comment]
try this:
brew install node

**Comment by topherbuckley** [comment]
Huh, I tried this again today on another test directory and it worked just fine...not sure what was happening yesterday...(Note: I did not use:)

````
brew install node
````

**Comment by zkat** [comment]
Closing as duplicate of https://github.com/npm/npm/issues/16816

**Comment by mrkiffie** [comment]
@zkat, are you sure this is the same problem? Please excuse my ignorance. 

The other issue refers to a dependency with a blank name.
Their steps to reproduce were: 
> Create a package.json file with a dependency that is named "" and run npm install

This one was failing as a result of there being no `package.json` file in the directory at all.

I see that the logs have a similar progression, is this why it is marked as a duplicate?

**Comment by zkat** [comment]
@mrkiffie eh. I may have done triage a bit quickly (sorry! there's a lot of issues to take care of!)

I strongly suspect that fixing one of these will fix the other, which is why I marked it as a duplicate. For safety's sake, I'll just reopen this for you and we can just verify that once we have a patch. 👍

**Comment by mrkiffie** [comment]
Thanks @zkat. I hope that fixing it in one place will fix it in other places too. in the worst case is we have another test case 🙂
