### ISSUE TITLE
Npm install request https gives "TypeError"

### ISSUE THREAD

**Issue by ggunay** [npm/npm#16821]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

Hello,
I am trying to install request https packages for my index.js file. When i run the following command on the same directory as the index.js on Kali 2:

`npm install request https`

I get the following errors:
```

npm ERR! TypeError: Request path contains unescaped characters.
npm ERR!     at new ClientRequest (_http_client.js:50:11)
npm ERR!     at Object.exports.request (http.js:31:10)
npm ERR!     at TunnelingAgent.socket.once.exports.request (https.js:182:15)
npm ERR!     at TunnelingAgent.createSocket (/usr/lib/nodejs/tunnel-agent/index.js:117:25)
npm ERR!     at TunnelingAgent.createSecureSocket [as createSocket] (/usr/lib/nodejs/tunnel-agent/index.js:184:41)
npm ERR!     at TunnelingAgent.addRequest (/usr/lib/nodejs/tunnel-agent/index.js:80:8)
npm ERR!     at new ClientRequest (_http_client.js:142:16)
npm ERR!     at Object.exports.request (http.js:31:10)
npm ERR!     at Object.socket.once.exports.request (https.js:182:15)
npm ERR!     at Request.start (/usr/lib/nodejs/request/index.js:607:30)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.9.0-kali3-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "request" "https"
npm ERR! cwd /root/Desktop/npmFbBot
npm ERR! node -v v4.7.2
npm ERR! npm -v 1.4.21
npm ERR! TypeError: Request path contains unescaped characters.
npm ERR!     at new ClientRequest (_http_client.js:50:11)
npm ERR!     at Object.exports.request (http.js:31:10)
npm ERR!     at TunnelingAgent.socket.once.exports.request (https.js:182:15)
npm ERR!     at TunnelingAgent.createSocket (/usr/lib/nodejs/tunnel-agent/index.js:117:25)
npm ERR!     at TunnelingAgent.createSecureSocket [as createSocket] (/usr/lib/nodejs/tunnel-agent/index.js:184:41)
npm ERR!     at TunnelingAgent.addRequest (/usr/lib/nodejs/tunnel-agent/index.js:80:8)
npm ERR!     at new ClientRequest (_http_client.js:142:16)
npm ERR!     at Object.exports.request (http.js:31:10)
npm ERR!     at Object.socket.once.exports.request (https.js:182:15)
npm ERR!     at Request.start (/usr/lib/nodejs/request/index.js:607:30)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.9.0-kali3-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "request" "https"
npm ERR! cwd /root/Desktop/npmFbBot
npm ERR! node -v v4.7.2
npm ERR! npm -v 1.4.21
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /root/Desktop/npmFbBot/npm-debug.log
npm ERR! not ok code 0

```

The error sometimes occur right awawy, sometimes after a few seconds.
I tried different combinations like only checking for request etc, but no chance. As far as I know there is no space in the directory (you can also verify by checking the error)

here is the log file:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   'request',
1 verbose cli   'https' ]
2 info using npm@1.4.21
3 info using node@v4.7.2
4 verbose cache add [ 'request', null ]
5 verbose cache add name=undefined spec="request" args=["request",null]
6 verbose parsed url Url {
6 verbose parsed url   protocol: null,
6 verbose parsed url   slashes: null,
6 verbose parsed url   auth: null,
6 verbose parsed url   host: null,
6 verbose parsed url   port: null,
6 verbose parsed url   hostname: null,
6 verbose parsed url   hash: null,
6 verbose parsed url   search: null,
6 verbose parsed url   query: null,
6 verbose parsed url   pathname: 'request',
6 verbose parsed url   path: 'request',
6 verbose parsed url   href: 'request' }
7 verbose cache add [ 'https', null ]
8 verbose cache add name=undefined spec="https" args=["https",null]
9 verbose parsed url Url {
9 verbose parsed url   protocol: null,
9 verbose parsed url   slashes: null,
9 verbose parsed url   auth: null,
9 verbose parsed url   host: null,
9 verbose parsed url   port: null,
9 verbose parsed url   hostname: null,
9 verbose parsed url   hash: null,
9 verbose parsed url   search: null,
9 verbose parsed url   query: null,
9 verbose parsed url   pathname: 'https',
9 verbose parsed url   path: 'https',
9 verbose parsed url   href: 'https' }
10 silly lockFile 088e29b0-request request
11 verbose lock request /root/.npm/088e29b0-request.lock
12 silly lockFile c3437dbc-https https
13 verbose lock https /root/.npm/c3437dbc-https.lock
14 silly lockFile 088e29b0-request request
15 silly lockFile 088e29b0-request request
16 silly lockFile c3437dbc-https https
17 silly lockFile c3437dbc-https https
18 verbose addNamed [ 'request', '' ]
19 verbose addNamed [ null, '*' ]
20 silly lockFile 9d461bcf-request request@
21 verbose lock request@ /root/.npm/9d461bcf-request.lock
22 verbose addNamed [ 'https', '' ]
23 verbose addNamed [ null, '*' ]
24 silly lockFile 421d451a-https https@
25 verbose lock https@ /root/.npm/421d451a-https.lock
26 silly addNameRange { name: 'request', range: '*', hasData: false }
27 verbose request where is /request
28 verbose request registry https://registry.npmjs.org/
29 verbose request id ad54d2aa8bc4a6dc
30 verbose url raw /request
31 verbose url resolving [ 'https://registry.npmjs.org/', './request' ]
32 verbose url resolved https://registry.npmjs.org/request
33 verbose request where is https://registry.npmjs.org/request
34 info trying registry request attempt 1 at 6:15:55 AM
35 http GET https://registry.npmjs.org/request
36 error TypeError: Request path contains unescaped characters.
36 error     at new ClientRequest (_http_client.js:50:11)
36 error     at Object.exports.request (http.js:31:10)
36 error     at TunnelingAgent.socket.once.exports.request (https.js:182:15)
36 error     at TunnelingAgent.createSocket (/usr/lib/nodejs/tunnel-agent/index.js:117:25)
36 error     at TunnelingAgent.createSecureSocket [as createSocket] (/usr/lib/nodejs/tunnel-agent/index.js:184:41)
36 error     at TunnelingAgent.addRequest (/usr/lib/nodejs/tunnel-agent/index.js:80:8)
36 error     at new ClientRequest (_http_client.js:142:16)
36 error     at Object.exports.request (http.js:31:10)
36 error     at Object.socket.once.exports.request (https.js:182:15)
36 error     at Request.start (/usr/lib/nodejs/request/index.js:607:30)
37 error If you need help, you may report this *entire* log,
37 error including the npm and node versions, at:
37 error     <http://github.com/npm/npm/issues>
38 error System Linux 4.9.0-kali3-amd64
39 error command "/usr/bin/nodejs" "/usr/bin/npm" "install" "request" "https"
40 error cwd /root/Desktop/npmFbBot
41 error node -v v4.7.2
42 error npm -v 1.4.21
43 verbose exit [ 1, true ]
```

**Comment by kenany** [comment]
`npm@1` is no longer supported. If this is still an issue with `npm@4` or `npm@5`, I can reopen.

**Comment by ggunay** [comment]
Hello,
Ok I will try to upgrade, apt-get on Kali 2 installs 1.4.21 as the latest
version by default.
