### ISSUE TITLE
npm install npm@latest -g crashes

### ISSUE THREAD

**Issue by zeg-io** [npm/npm#16873]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

```sh
npm info it worked if it ends with ok
npm verb cli [ '/usr/local/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'install',
npm verb cli   'npm@latest',
npm verb cli   '-g' ]
npm info using npm@5.0.0
npm info using node@v8.0.0
npm verb stack TypeError: Cannot read property 'fetch' of undefined
npm verb stack     at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/fetch-package-metadata.js:34:55)
npm verb stack     at Module._compile (module.js:569:30)
npm verb stack     at Object.Module._extensions..js (module.js:580:10)
npm verb stack     at Module.load (module.js:503:32)
npm verb stack     at tryModuleLoad (module.js:466:12)
npm verb stack     at Function.Module._load (module.js:458:3)
npm verb stack     at Module.require (module.js:513:17)
npm verb stack     at require (internal/module.js:11:18)
npm verb stack     at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/install/deps.js:15:28)
npm verb stack     at Module._compile (module.js:569:30)
npm verb stack     at Object.Module._extensions..js (module.js:580:10)
npm verb stack     at Module.load (module.js:503:32)
npm verb stack     at tryModuleLoad (module.js:466:12)
npm verb stack     at Function.Module._load (module.js:458:3)
npm verb stack     at Module.require (module.js:513:17)
npm verb stack     at require (internal/module.js:11:18)
npm verb cwd /Users/tonyarcher
npm ERR! Darwin 16.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "npm@latest" "-g"
npm ERR! node v8.0.0
npm ERR! npm  v5.0.0
npm ERR! Cannot read property 'fetch' of undefined
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm verb exit [ 1, true ]
```
#### How can the CLI team reproduce the problem?
I upgraded when I got the email,  but my email said it would install 5.0.1 which it did not.

So I ran it again today and it crashed.

### supporting information:

 - `npm -v` prints:
```
$ npm -v
5.0.0
/usr/local/lib/node_modules/npm/bin/npm-cli.js:60
    return errorHandler.exit(0)
                        ^

TypeError: errorHandler.exit is not a function
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:60:25
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:92:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```
 - `node -v` prints:
```
$ node -v
v8.0.0
```
 - `npm config get registry` prints:
```
$ npm config get registry
npm info it worked if it ends with ok
npm verb cli [ '/usr/local/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'config',
npm verb cli   'get',
npm verb cli   'registry' ]
npm info using npm@5.0.0
npm info using node@v8.0.0
npm verb config Skipping project config: /Users/tonyarcher/.npmrc. (matches userconfig)
https://registry.npmjs.org/
npm verb exit [ 0, true ]
npm info ok
```
 - Windows, OS X/macOS, or Linux?:
macOS
 
[2017-06-01T14_24_20_179Z-debug.log.zip](https://github.com/npm/npm/files/1045087/2017-06-01T14_24_20_179Z-debug.log.zip)

**Comment by thib-rdr** [comment]
Hey, did you ever solve your problem ? I have the exact same one...
