### ISSUE TITLE
npm ERR! arg Argument starts with non-ascii dash, this is probably invalid: [ '-g', '@angular/cli@latest' ]

### ISSUE THREAD

**Issue by richard155** [npm/npm#16912]
#### I'm opening this issue because:
When I try to connect/install the registry of "@angular / cli@latest"
 
  -  npm is producing an incorrect install.

#### What's going wrong?

when i type the command npm install -g '@angular/ cli@latest'

I have this error

npm ERR! arg Argument starts with non-ascii dash, this is probably invalid: [ '-g', '@angular/cli@latest' ]
Unhandled rejection Error: Invalid tag name "-g": Tags may not have any characters that encodeURIComponent encodes.
    at invalidTagName (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-package-arg\npa.js:76:15)
    at fromRegistry (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-package-arg\npa.js:244:13)
    at resolve (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-package-arg\npa.js:66:12)
    at npa (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-package-arg\npa.js:39:10)
    at C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:200:16
    at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:35
    at Array.forEach (native)
    at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:11
    at Array.forEach (native)
    at asyncMap (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:51:8)
    at exports.getAllMetadata (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:199:3)
    at Installer.loadArgMetadata (C:\Program Files\nodejs\node_modules\npm\lib\install.js:325:3)
    at C:\Program Files\nodejs\node_modules\npm\lib\install.js:648:16
    at BB.join.then (C:\Program Files\nodejs\node_modules\npm\lib\install\read-shrinkwrap.js:41:16)
    at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Program Files\nodejs\node_modules\n
pm\node_modules\bluebird\js\release\promise.js:512:31)
npm ERR! cb() never called!
npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\TEMP\AppData\Roaming\npm-cache\_logs\2017-06-02T08_36_28_996Z-debug.log

May you help me please

### supporting information:

 - `npm -v` prints: 5.0.0
 - `node -v` prints: v8.0.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows 2012 R2
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by richard155** [comment]
the -g must be at the end of the command line ...

**Comment by AnythingLinux** [comment]
I am using Ubuntu 14.04 LTS 64bit. I am also having this issue. need help.

root@Explorer:~/explorer# npm -v
5.3.0
root@Explorer:~/explorer# node -v
v8.4.0
root@Explorer:~/explorer# npm install –production -g
npm ERR! arg Argument starts with non-ascii dash, this is probably invalid: [ '–production' ]
npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name "–production": Tags may not have any characters that encodeURIComponent encodes.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-08-16T22_16_54_278Z-debug.log
root@Explorer:~/explorer#
