### ISSUE TITLE
npm ENOTFOUND error for a scoped package

### ISSUE THREAD

**Issue by simoami** [npm/npm#16930]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

npm install is failing for scoped packages.

#### How can the CLI team reproduce the problem?

```
npm install @google-cloud/datastore
```

Response
```
npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR! network request to https://registry.npmjs.org/@google-cloud%2fdatastore failed, reason: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/work/.npm/_logs/2017-06-02T18_52_32_737Z-debug.log
```

log file:
```
1 verbose cli   'install',
1 verbose cli   '@google-cloud/datastore' ]
2 info using npm@5.0.1
3 info using node@v6.6.0
4 silly install loadCurrentTree
5 silly install readLocalPackageData
6 silly fetchPackageMetaData error for @google-cloud/datastore@1.0.1 request to https://registry.npmjs.org/@google-cloud%2fdatastore failed, reason: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
7 verbose type system
8 verbose stack FetchError: request to https://registry.npmjs.org/@google-cloud%2fdatastore failed, reason: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
8 verbose stack     at ClientRequest.req.on.err (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/src/index.js:68:14)
8 verbose stack     at emitOne (events.js:96:13)
8 verbose stack     at ClientRequest.emit (events.js:188:7)
8 verbose stack     at TLSSocket.socketErrorListener (_http_client.js:308:9)
8 verbose stack     at emitOne (events.js:96:13)
8 verbose stack     at TLSSocket.emit (events.js:188:7)
8 verbose stack     at connectErrorNT (net.js:1015:8)
8 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:74:11)
8 verbose stack     at process._tickCallback (internal/process/next_tick.js:98:9)
9 verbose cwd /projects/golets/hs-service-auth
10 verbose Darwin 16.6.0
11 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "@google-cloud/datastore"
12 verbose node v6.6.0
13 verbose npm  v5.0.1
14 error code ENOTFOUND
15 error errno ENOTFOUND
16 error network request to https://registry.npmjs.org/@google-cloud%2fdatastore failed, reason: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
17 error network This is a problem related to network connectivity.
17 error network In most cases you are behind a proxy or have bad network settings.
17 error network
17 error network If you are behind a proxy, please make sure that the
17 error network 'proxy' config is set properly.  See: 'npm help config'
18 verbose exit [ 1, true ]
```

### supporting information:

 - `npm -v` prints: 5.0.1
 - `node -v` prints: v6.6.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: macOS

**Comment by simoami** [comment]
So issue trackers are not allowed to exist as long as there are issues? What's the point of logging them?
