### ISSUE TITLE
Error: Cannot find module 'core-util-is' in NPM 5.0.2 just after executing npm update

### ISSUE THREAD

**Issue by pubmikeb** [npm/npm#16947]
#### I'm opening this issue because:

  - [X] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Just after update, npm 5.0.2 returns an error:
> C:\Program Files\nodejs\node_modules\npm>npm -v
> module.js:487
>     throw err;
>     ^
> 
> Error: Cannot find module 'core-util-is'
>     at Function.Module._resolveFilename (module.js:485:15)
>     at Function.Module._load (module.js:437:25)
>     at Module.require (module.js:513:17)
>     at require (internal/module.js:11:18)
>     at Object.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\readable-stream\lib\_stream_readable.js:36:12)
>     at Module._compile (module.js:569:30)
>     at Object.Module._extensions..js (module.js:580:10)
>     at Module.load (module.js:503:32)
>     at tryModuleLoad (module.js:466:12)
>     at Function.Module._load (module.js:458:3)
> module.js:487
>     throw err;
>     ^
> 
> Error: Cannot find module 'core-util-is'
>     at Function.Module._resolveFilename (module.js:485:15)
>     at Function.Module._load (module.js:437:25)
>     at Module.require (module.js:513:17)
>     at require (internal/module.js:11:18)
>     at Object.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\readable-stream\lib\_stream_readable.js:36:12)
>     at Module._compile (module.js:569:30)
>     at Object.Module._extensions..js (module.js:580:10)
>     at Module.load (module.js:503:32)
>     at tryModuleLoad (module.js:466:12)
>     at Function.Module._load (module.js:458:3)

#### How can the CLI team reproduce the problem?
1. Completely fresh installation of Node.js 8.0.0

2. Open console as admin

3. Go to `C:\Program Files\nodejs`

4. Try to install the latest version of npm (5.0.2) with `npm install npm@latest`

5. The process will be finished successfully (updated 13 packages in 22.895s). `npm -v` will return you 5.0.2

6. Go to `C:\Program Files\nodejs\node_modules\npm`

7. Run `npm update`

8. You'll get:
> npm notice created a lockfile as package-lock.json. You should commit this file.
> + readable-stream@2.2.10
> added 1 package, removed 2 packages, updated 1 package and moved 4 packages in 2.842s

9. Try to run `npm -v`, you'll get the error message (see above).

10. Now, every command of npm returns the error.

### supporting information:

 - `npm -v` prints: 5.0.2
 - `node -v` prints: 8.0.0
 - `npm config get registry` prints:

> C:\Program Files\nodejs\node_modules\npm>npm config get registry
> module.js:487
>     throw err;
>     ^
> 
> Error: Cannot find module 'core-util-is'
>     at Function.Module._resolveFilename (module.js:485:15)
>     at Function.Module._load (module.js:437:25)
>     at Module.require (module.js:513:17)
>     at require (internal/module.js:11:18)
>     at Object.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\readable-stream\lib\_stream_readable.js:36:12)
>     at Module._compile (module.js:569:30)
>     at Object.Module._extensions..js (module.js:580:10)
>     at Module.load (module.js:503:32)
>     at tryModuleLoad (module.js:466:12)
>     at Function.Module._load (module.js:458:3)
> module.js:487
>     throw err;
>     ^
> 
> Error: Cannot find module 'core-util-is'
>     at Function.Module._resolveFilename (module.js:485:15)
>     at Function.Module._load (module.js:437:25)
>     at Module.require (module.js:513:17)
>     at require (internal/module.js:11:18)
>     at Object.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\readable-stream\lib\_stream_readable.js:36:12)
>     at Module._compile (module.js:569:30)
>     at Object.Module._extensions..js (module.js:580:10)
>     at Module.load (module.js:503:32)
>     at tryModuleLoad (module.js:466:12)
>     at Function.Module._load (module.js:458:3)

 - Windows, OS X/macOS, or Linux?: Windows 10 1703.15063.332
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by pubmikeb** [comment]
I tried to reproduce the case with completely fresh installation of Node.js 8.1.0, which comes with NPM 5.0.3 out-of-box and I see, that 'npm update' doesn't work at all.

Reproduction steps:

1. Completely fresh installation of Node.js 8.1.0 (with NPM 5.0.3)
2. Open console as admin
3. Go to `C:\Program Files\nodejs\node_modules\npm` where all modules are located, including `package.json` and `package-lock.json`
4. Try to execute `npm update`
5. You'll get the same error as in the ticket.

**Comment by pubmikeb** [comment]
I tried to reproduce the case on NPM 5.0.3 and Node.js 8.1.2 and after first execution of `npm --depth 9999 update --dev` (after a fresh installation), which has been finished successfully I tried to execute `npm -v` and got the following error:

```
C:\Program Files\nodejs\node_modules\npm>npm -v
module.js:487
    throw err;
    ^

Error: Cannot find module 'core-util-is'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\readable-stream\lib\_stream_readable.js:36:12)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
module.js:487
    throw err;
    ^

Error: Cannot find module 'core-util-is'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\readable-stream\lib\_stream_readable.js:36:12)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
```
Now, every call of `npm` leads to `Error: Cannot find module 'core-util-is'` warning.

**Comment by tehraven** [comment]
Recently had this issue while running inside a docker container. (Docker is probably not relevant here, but it's context).

```sh
RUN wget https://npmjs.org/install.sh \
    && chmod +x ./install.sh \
    && ./install.sh
```

Installs it during build just fine.

Good luck!
