### ISSUE TITLE
Install of @angular/cli fails

### ISSUE THREAD

**Issue by soodrah** [npm/npm#16953]
#### I'm opening this issue because:
  - [X ] npm is doing something I don't understand.

#### What's going wrong?
I have started the cmd.exe as administrator and have tried following commands to install angular cli
npm install -g @angular/cli
npm uninstall -g @angular/cli
npm cache clean -f

#### How can the CLI team reproduce the problem?
Please see above, I tried stackoverflow and tried the steps shown above but did not help, will appreciate if someone can take a look and tell me what i am missing. I did not upgrade node.js. I am logged into my work computer over VPN, I dont think that should matter but thought I would mention.

```
82215 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\@angular\cli\node_modules\chokidar\node_modules\fsevents):
82216 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
82217 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
82217 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
82217 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
82217 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
82218 verbose stack Error: EPERM: operation not permitted, rename 'C:\Users\rsood1\AppData\Roaming\npm\node_modules\@angular\cli' -> 'C:\Users\rsood1\AppData\Roaming\npm\node_modules\@angular\.cli.DELETE'
82218 verbose stack     at moveAway (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:38:5)
82218 verbose stack     at destStatted (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:27:7)
82218 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:267:18
82218 verbose stack     at FSReqWrap.oncomplete (fs.js:123:15)
82218 verbose stack
82218 verbose stack Error: EPERM: operation not permitted, rename 'C:\Users\rsood1\AppData\Roaming\npm\node_modules\@angular\cli' -> 'C:\Users\rsood1\AppData\Roaming\npm\node_modules\@angular\.cli.DELETE'
82218 verbose stack     at Error (native)
82219 verbose cwd C:\Users\rsood1
82220 error Windows_NT 6.1.7601
82221 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@angular/cli"
82222 error node v6.9.5
82223 error npm  v3.10.10
82224 error path C:\Users\rsood1\AppData\Roaming\npm\node_modules\@angular\cli
82225 error code EPERM
82226 error errno -4048
82227 error syscall rename
82228 error Error: EPERM: operation not permitted, rename 'C:\Users\rsood1\AppData\Roaming\npm\node_modules\@angular\cli' -> 'C:\Users\rsood1\AppData\Roaming\npm\node_modules\@angular\.cli.DELETE'
82228 error     at moveAway (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:38:5)
82228 error     at destStatted (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:27:7)
82228 error     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:267:18
82228 error     at FSReqWrap.oncomplete (fs.js:123:15)
82228 error
82228 error Error: EPERM: operation not permitted, rename 'C:\Users\rsood1\AppData\Roaming\npm\node_modules\@angular\cli' -> 'C:\Users\rsood1\AppData\Roaming\npm\node_modules\@angular\.cli.DELETE'
82228 error     at Error (native)
82228 error  Error: EPERM: operation not permitted, rename 'C:\Users\rsood1\AppData\Roaming\npm\node_modules\@angular\cli' -> 'C:\Users\rsood1\AppData\Roaming\npm\node_modules\@angular\.cli.DELETE'
82228 error     at moveAway (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:38:5)
82228 error     at destStatted (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:27:7)
82228 error     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:267:18
82228 error     at FSReqWrap.oncomplete (fs.js:123:15)
82228 error
82228 error Error: EPERM: operation not permitted, rename 'C:\Users\rsood1\AppData\Roaming\npm\node_modules\@angular\cli' -> 'C:\Users\rsood1\AppData\Roaming\npm\node_modules\@angular\.cli.DELETE'
82228 error     at Error (native)
82229 error Please try running this command again as root/Administrator.
82230 verbose exit [ -4048, true ]
```

 
   - [X ] I access the npm registry via a VPN

**Comment by soodrah** [comment]
We can close this. I upgraded to Node 6.10.3 and then ran the following commands and was able to install ng. My earlier version was 6.9
npm uninstall -g @angular/cli (need to run this only if already installed)
npm cache clean
npm install -g @angular/cli@latest

**Comment by soodrah** [comment]
Request to NPM folks to maybe make the debug log better. Seems like version was the issue but was not so evident from the log.
