### ISSUE TITLE
Unhandled rejection RangeError: Maximum call stack size exceededpreinstall: no script for preinstall

### ISSUE THREAD

**Issue by sbfkcel** [npm/npm#16968]
# fan @ fandeMacBook-Air in ~/Workspace/web/fws on git:master o [0:53:04]
$ npm install
Unhandled rejection RangeError: Maximum call stack size exceededpreinstall: no script for preinstall, continuing
    at exports.create (/Users/fan/.nvm/versions/node/v8.0.0/lib/node_modules/npm/lib/install/node.js:31:40)
    at /Users/fan/.nvm/versions/node/v8.0.0/lib/node_modules/npm/lib/install/node.js:36:14
    at Array.forEach (native)
    at exports.create (/Users/fan/.nvm/versions/node/v8.0.0/lib/node_modules/npm/lib/install/node.js:33:25)
    at /Users/fan/.nvm/versions/node/v8.0.0/lib/node_modules/npm/lib/install/node.js:36:14
    at Array.forEach (native)
    at exports.create (/Users/fan/.nvm/versions/node/v8.0.0/lib/node_modules/npm/lib/install/node.js:33:25)
    at normalizeTree (/Users/fan/.nvm/versions/node/v8.0.0/lib/node_modules/npm/lib/install.js:377:5)
    at Array.forEach (native)
    at normalizeTree (/Users/fan/.nvm/versions/node/v8.0.0/lib/node_modules/npm/lib/install.js:379:19)
    at Array.forEach (native)
    at normalizeTree (/Users/fan/.nvm/versions/node/v8.0.0/lib/node_modules/npm/lib/install.js:379:19)
    at Array.forEach (native)
    at normalizeTree (/Users/fan/.nvm/versions/node/v8.0.0/lib/node_modules/npm/lib/install.js:379:19)
    at Array.forEach (native)
    at normalizeTree (/Users/fan/.nvm/versions/node/v8.0.0/lib/node_modules/npm/lib/install.js:379:19)

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/fan/.npm/_logs/2017-06-04T16_53_53_605Z-debug.log

# fan @ fandeMacBook-Air in ~/Workspace/web/fws on git:master o [0:53:53] C:1
$ npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sha1-8Z/Sj0Pur3YWgOUZogPE0LPTGv8= integrity checksum failed when using sha1: wanted sha1-8Z/Sj0Pur3YWgOUZogPE0LPTGv8= but got sha1-2jmj7l5rSw0yVb/vlWAYkK/YBwk=. (0 bytes)

npm ERR! code EINTEGRITY
npm ERR! sha1-TlNk65v9mH2vbBtIpY0r5bag+Nc= integrity checksum failed when using sha1: wanted sha1-TlNk65v9mH2vbBtIpY0r5bag+Nc= but got sha1-uMwcvKcjgcLnvJytq/dUpizJxi4=. (8277 bytes)

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/fan/.npm/_logs/2017-06-04T16_57_18_334Z-debug.log

**Comment by sbfkcel** [comment]
npm 5.0.0

**Comment by legodude17** [comment]
Related: #17056
