### ISSUE TITLE
problem to install generator-aspnet

### ISSUE THREAD

**Issue by geltoncruz** [npm/npm#16996]
#### I'm opening this issue because:

  - [ ] npm no install webapicontroller

Unhandled rejection Error: Invalid tag name "generator-aspnet:webapicontroller": Tags may not have any characters that encodeURIComponent encodes.
    at invalidTagName (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:76:15)
    at fromRegistry (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:244:13)
    at resolve (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:66:12)
    at npa (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:39:10)
    at /usr/local/lib/node_modules/npm/lib/install/deps.js:200:16
    at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
    at Array.forEach (native)
    at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
    at Array.forEach (native)
    at asyncMap (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
    at exports.getAllMetadata (/usr/local/lib/node_modules/npm/lib/install/deps.js:199:3)
    at Installer.loadArgMetadata (/usr/local/lib/node_modules/npm/lib/install.js:325:3)
    at /usr/local/lib/node_modules/npm/lib/install.js:648:16
    at BB.join.then (/usr/local/lib/node_modules/npm/lib/install/read-shrinkwrap.js:41:16)
    at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/geltoncruz/.npm/_logs/2017-06-05T17_41_56_612Z-debug.log

**Comment by kenany** [comment]
@geltoncruz Could you upload the full log to <https://gist.github.com/> and link it here? Thanks!
