### ISSUE TITLE
npm download & update error : cache dir error?! 

### ISSUE THREAD

**Issue by clickclouds** [npm/npm#17008]
2017-06-06
오후 2:29	Create Express Project
		Cannot create Node.js Express App: Failed command:
		E:\Nodejs\node.exe C:\Users\월인천강\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js install
		Exit code: 1
		Standard error:
		npm ERR! C:\Users\월인천강\AppData\Roaming\npm-cache\_cacache is not a legal HTTP header value
		npm ERR! A complete log of this run can be found in:
		npm ERR!     C:\Users\월인천강\AppData\Roaming\npm-cache\_logs\2017-06-06T05_29_21_835Z-debug.log

npm 5.0.0, 5.0.1, 5.0.2, 5.0.3

**Comment by zkat** [comment]
@clickclouds could you upload `C:\Users\월인천강\AppData\Roaming\npm-cache_logs\2017-06-06T05_29_21_835Z-debug.log`?

**Comment by clickclouds** [comment]
```
0 info it worked if it ends with ok
1 verbose cli [ 'E:\\Nodejs\\node.exe',
1 verbose cli   'C:\\Users\\월인천강\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@5.0.3
3 info using node@v8.0.0
4 verbose npm-session 07bf7cf6ea03ca07
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall nodeserver005@0.0.0
7 info lifecycle nodeserver005@0.0.0~preinstall: nodeserver005@0.0.0
8 silly lifecycle nodeserver005@0.0.0~preinstall: no script for preinstall, continuing
9 silly install loadCurrentTree
10 silly install readLocalPackageData
11 silly install loadIdealTree
12 silly install cloneCurrentTreeToIdealTree
13 silly install loadShrinkwrap
14 silly install loadAllDepsIntoIdealTree
15 silly fetchPackageMetaData error for ejs@~2.5.6 C:\Users\월인천강\AppData\Roaming\npm-cache\_cacache is not a legal HTTP header value
16 http fetch GET 200 https://registry.npmjs.org/serve-favicon 379ms
17 http fetch GET 200 https://registry.npmjs.org/debug 385ms
18 http fetch GET 200 https://registry.npmjs.org/morgan 384ms
19 http fetch GET 200 https://registry.npmjs.org/cookie-parser 389ms
20 http fetch GET 200 https://registry.npmjs.org/body-parser 412ms
21 http fetch GET 200 https://registry.npmjs.org/express 406ms
22 silly pacote range manifest for morgan@~1.8.1 fetched in 423ms
23 silly pacote range manifest for debug@~2.6.3 fetched in 433ms
24 silly pacote range manifest for serve-favicon@~2.4.2 fetched in 431ms
25 silly pacote range manifest for cookie-parser@~1.4.3 fetched in 435ms
26 silly pacote range manifest for body-parser@~1.17.1 fetched in 521ms
27 silly pacote version manifest for debug@2.6.8 fetched in 35ms
28 silly pacote range manifest for express@~4.15.2 fetched in 466ms
29 http fetch GET 200 https://registry.npmjs.org/basic-auth 92ms
30 http fetch GET 200 https://registry.npmjs.org/on-headers 92ms
31 http fetch GET 200 https://registry.npmjs.org/on-finished 97ms
32 http fetch GET 200 https://registry.npmjs.org/depd 100ms
33 http fetch GET 200 https://registry.npmjs.org/ms 94ms
34 http fetch GET 200 https://registry.npmjs.org/etag 95ms
35 silly pacote range manifest for on-headers@~1.0.1 fetched in 108ms
36 silly pacote range manifest for basic-auth@~1.1.0 fetched in 110ms
37 silly pacote range manifest for on-finished@~2.3.0 fetched in 123ms
38 silly pacote range manifest for depd@~1.1.0 fetched in 125ms
39 silly pacote version manifest for ms@2.0.0 fetched in 115ms
40 silly pacote range manifest for etag@~1.8.0 fetched in 115ms
41 silly pacote version manifest for debug@2.6.7 fetched in 15ms
42 http fetch GET 200 https://registry.npmjs.org/fresh 152ms
43 http fetch GET 200 https://registry.npmjs.org/cookie-signature 82ms
44 http fetch GET 200 https://registry.npmjs.org/cookie 92ms
45 http fetch GET 200 https://registry.npmjs.org/safe-buffer 167ms
46 silly pacote version manifest for fresh@0.5.0 fetched in 193ms
47 http fetch GET 200 https://registry.npmjs.org/parseurl 187ms
48 http fetch GET 200 https://registry.npmjs.org/content-type 98ms
49 http fetch GET 200 https://registry.npmjs.org/bytes 108ms
50 silly pacote version manifest for cookie-signature@1.0.6 fetched in 134ms
51 http fetch GET 200 https://registry.npmjs.org/http-errors 119ms
52 http fetch GET 200 https://registry.npmjs.org/iconv-lite 120ms
53 http fetch GET 200 https://registry.npmjs.org/qs 109ms
54 silly pacote version manifest for safe-buffer@5.0.1 fetched in 220ms
55 silly pacote version manifest for cookie@0.3.1 fetched in 148ms
56 silly pacote range manifest for parseurl@~1.3.1 fetched in 240ms
57 silly pacote range manifest for content-type@~1.0.2 fetched in 150ms
58 silly pacote version manifest for bytes@2.4.0 fetched in 154ms
59 silly pacote version manifest for iconv-lite@0.4.15 fetched in 162ms
60 silly pacote range manifest for http-errors@~1.6.1 fetched in 164ms
61 silly pacote version manifest for qs@6.4.0 fetched in 151ms
62 http fetch GET 200 https://registry.npmjs.org/raw-body 98ms
63 silly pacote range manifest for raw-body@~2.2.0 fetched in 108ms
64 http fetch GET 200 https://registry.npmjs.org/type-is 72ms
65 http fetch GET 200 https://registry.npmjs.org/array-flatten 73ms
66 http fetch GET 200 https://registry.npmjs.org/accepts 82ms
67 silly pacote range manifest for type-is@~1.6.15 fetched in 101ms
68 http fetch GET 200 https://registry.npmjs.org/encodeurl 75ms
69 http fetch GET 200 https://registry.npmjs.org/content-disposition 80ms
70 http fetch GET 200 https://registry.npmjs.org/escape-html 80ms
71 http fetch GET 200 https://registry.npmjs.org/merge-descriptors 71ms
72 silly pacote version manifest for array-flatten@1.1.1 fetched in 106ms
73 http fetch GET 200 https://registry.npmjs.org/finalhandler 77ms
74 silly pacote range manifest for accepts@~1.3.3 fetched in 113ms
75 http fetch GET 200 https://registry.npmjs.org/methods 86ms
76 silly pacote range manifest for encodeurl@~1.0.1 fetched in 112ms
77 silly pacote version manifest for content-disposition@0.5.2 fetched in 114ms
78 silly pacote range manifest for escape-html@~1.0.3 fetched in 125ms
79 silly pacote version manifest for merge-descriptors@1.0.1 fetched in 113ms
80 http fetch GET 200 https://registry.npmjs.org/path-to-regexp 103ms
81 silly pacote range manifest for finalhandler@~1.0.3 fetched in 129ms
82 silly pacote range manifest for methods@~1.1.2 fetched in 133ms
83 silly pacote version manifest for path-to-regexp@0.1.7 fetched in 128ms
84 http fetch GET 200 https://registry.npmjs.org/send 73ms
85 http fetch GET 200 https://registry.npmjs.org/proxy-addr 101ms
86 http fetch GET 200 https://registry.npmjs.org/range-parser 82ms
87 silly pacote version manifest for send@0.15.3 fetched in 105ms
88 silly pacote version manifest for depd@1.1.0 fetched in 34ms
89 silly pacote range manifest for proxy-addr@~1.1.4 fetched in 134ms
90 silly pacote range manifest for range-parser@~1.2.0 fetched in 120ms
91 http fetch GET 200 https://registry.npmjs.org/serve-static 102ms
92 http fetch GET 200 https://registry.npmjs.org/utils-merge 87ms
93 http fetch GET 200 https://registry.npmjs.org/setprototypeof 103ms
94 http fetch GET 200 https://registry.npmjs.org/statuses 88ms
95 http fetch GET 200 https://registry.npmjs.org/vary 89ms
96 http fetch GET 200 https://registry.npmjs.org/ee-first 85ms
97 silly pacote range manifest for statuses@~1.3.1 fetched in 105ms
98 silly pacote version manifest for serve-static@1.12.3 fetched in 122ms
99 silly pacote version manifest for setprototypeof@1.0.3 fetched in 124ms
100 silly pacote version manifest for utils-merge@1.0.0 fetched in 109ms
101 silly pacote version manifest for ee-first@1.1.1 fetched in 112ms
102 silly pacote range manifest for vary@~1.1.1 fetched in 118ms
103 http fetch GET 200 https://registry.npmjs.org/inherits 70ms
104 http fetch GET 200 https://registry.npmjs.org/media-typer 62ms
105 http fetch GET 200 https://registry.npmjs.org/statuses 69ms
106 http fetch GET 200 https://registry.npmjs.org/unpipe 69ms
107 silly pacote range manifest for statuses@>= 1.3.1 < 2 fetched in 73ms
108 silly pacote version manifest for unpipe@1.0.0 fetched in 105ms
109 silly pacote version manifest for media-typer@0.3.0 fetched in 102ms
110 silly pacote version manifest for inherits@2.0.3 fetched in 112ms
111 http fetch GET 200 https://registry.npmjs.org/unpipe 76ms
112 http fetch GET 200 https://registry.npmjs.org/mime-types 85ms
113 http fetch GET 200 https://registry.npmjs.org/mime-types 86ms
114 http fetch GET 200 https://registry.npmjs.org/negotiator 83ms
115 http fetch GET 200 https://registry.npmjs.org/destroy 72ms
116 http fetch GET 200 https://registry.npmjs.org/mime 73ms
117 silly pacote range manifest for unpipe@~1.0.0 fetched in 97ms
118 silly pacote range manifest for mime-types@~2.1.15 fetched in 102ms
119 silly pacote range manifest for mime-types@~2.1.11 fetched in 103ms
120 silly pacote version manifest for negotiator@0.6.1 fetched in 101ms
121 http fetch GET 200 https://registry.npmjs.org/forwarded 75ms
122 silly pacote version manifest for mime@1.3.4 fetched in 90ms
123 silly pacote range manifest for destroy@~1.0.4 fetched in 91ms
124 silly pacote range manifest for forwarded@~0.1.0 fetched in 88ms
125 http fetch GET 200 https://registry.npmjs.org/ipaddr.js 61ms
126 silly pacote version manifest for ipaddr.js@1.3.0 fetched in 71ms
127 http fetch GET 200 https://registry.npmjs.org/mime-db 56ms
128 silly pacote range manifest for mime-db@~1.27.0 fetched in 68ms
129 silly pacote range manifest for body-parser@~1.17.1 fetched in 5ms
130 silly resolveWithNewModule body-parser@1.17.2 checking installable status
131 silly pacote range manifest for cookie-parser@~1.4.3 fetched in 10ms
132 silly resolveWithNewModule cookie-parser@1.4.3 checking installable status
133 silly pacote range manifest for express@~4.15.2 fetched in 10ms
134 silly resolveWithNewModule express@4.15.3 checking installable status
135 silly pacote range manifest for morgan@~1.8.1 fetched in 11ms
136 silly resolveWithNewModule morgan@1.8.2 checking installable status
137 silly pacote range manifest for debug@~2.6.3 fetched in 13ms
138 silly resolveWithNewModule debug@2.6.8 checking installable status
139 silly pacote range manifest for serve-favicon@~2.4.2 fetched in 13ms
140 silly resolveWithNewModule serve-favicon@2.4.3 checking installable status
141 silly fetchPackageMetaData error for ejs@~2.5.6 C:\Users\월인천강\AppData\Roaming\npm-cache\_cacache is not a legal HTTP header value
142 verbose stack TypeError: C:\Users\월인천강\AppData\Roaming\npm-cache\_cacache is not a legal HTTP header value
142 verbose stack     at sanitizeValue (C:\Users\월인천강\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\node-fetch-npm\src\headers.js:24:11)
142 verbose stack     at Headers.set (C:\Users\월인천강\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\node-fetch-npm\src\headers.js:141:38)
142 verbose stack     at addCacheHeaders (C:\Users\월인천강\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\cache.js:253:14)
142 verbose stack     at cacache.get.info.then.then.info (C:\Users\월인천강\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\cache.js:57:9)
142 verbose stack     at tryCatcher (C:\Users\월인천강\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
142 verbose stack     at Promise._settlePromiseFromHandler (C:\Users\월인천강\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
142 verbose stack     at Promise._settlePromise (C:\Users\월인천강\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
142 verbose stack     at Promise._settlePromise0 (C:\Users\월인천강\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
142 verbose stack     at Promise._settlePromises (C:\Users\월인천강\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
142 verbose stack     at Promise._fulfill (C:\Users\월인천강\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:638:18)
142 verbose stack     at Promise._resolveCallback (C:\Users\월인천강\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:432:57)
142 verbose stack     at Promise._settlePromiseFromHandler (C:\Users\월인천강\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:524:17)
142 verbose stack     at Promise._settlePromise (C:\Users\월인천강\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
142 verbose stack     at Promise._settlePromise0 (C:\Users\월인천강\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
142 verbose stack     at Promise._settlePromises (C:\Users\월인천강\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
142 verbose stack     at Promise._fulfill (C:\Users\월인천강\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:638:18)
143 verbose cwd F:\WebService\NodeServer005
144 verbose Windows_NT 10.0.15063
145 verbose argv "E:\\Nodejs\\node.exe" "C:\\Users\\월인천강\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
146 verbose node v8.0.0
147 verbose npm  v5.0.3
148 error C:\Users\월인천강\AppData\Roaming\npm-cache\_cacache is not a legal HTTP header value
149 verbose exit [ 1, true ]
```

**Comment by clickclouds** [comment]
after manually clean cache(npm cache clean --force), updated or downloaded ONE(any) module, but two or more not (e.g. make new project in webstorm).

**Comment by zkat** [comment]
64f0105e8 should fix this. Thanks for the report :)

**Comment by clickclouds** [comment]
Thanks, Good Luck!!

**Comment by zkat** [comment]
@clickclouds this will go into the next npm release sometime this week. In the meantime, I've just pushed this patch up to the npm canary release, which you can install with `npm i -g npmc`. You can run it by using `npmc` instead of `npm`.

**Comment by clickclouds** [comment]
Wow, it's perfect!!!!  you're the BEST!!!!!

**Comment by zkat** [comment]
💃 yay! So glad we could get that working. I'm gonna just close this so I don't forget, but it'll be available in mainline soon, as I said.

**Comment by HashubWang** [comment]
thank you very much
