### ISSUE TITLE
cb() never called when a repository has no package.json

### ISSUE THREAD

**Issue by unilynx** [npm/npm#17014]
#### I'm opening this issue because:

  - [x] npm is crashing.

#### What's going wrong?

npm does not like github repositories that do not contain a package.json. It doesn't have to work, but the feedback could be better.

we ran into this when trying to switch from bower to npm and the repository in question only had a bower.json file - it took a bit to figure out where the real problem was.

```
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

#### How can the CLI team reproduce the problem?

```
npm install unilynx/empty
```

### supporting information:

 - `npm -v` prints:
5.0.3
 - `node -v` prints:
v8.0.0
 - `npm config get registry` prints:
https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?:
macOS

**Comment by julian-** [comment]
Got something similar:

Maybe this is wrong here, not sure if it's a single issue

```
[12:06:47] $ npm uninstall ionic
Unhandled rejection Error: Argument #2: Expected string but got null onetime@^2.0.0 fetched in 395ms
    at addDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:515:3)
    at /usr/local/lib/node_modules/npm/lib/install/deps.js:463:5
    at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
    at Array.forEach (native)
    at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
    at Array.forEach (native)
    at asyncMap (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
    at loadDeps (/usr/local/lib/node_modules/npm/lib/install/deps.js:455:3)
    at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
    at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
    at /usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
    at /usr/local/lib/node_modules/npm/lib/install/and-finish-tracker.js:8:8
    at resolveBranchDeps.then (/usr/local/lib/node_modules/npm/lib/install/deps.js:419:11)
    at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/julianrochner/.npm/_logs/2017-06-06T10_07_30_127Z-debug.log
```

`npm -v`:  5.0.1
`node -v`: v6.10.3
`npm config get registry`: https://registry.npmjs.org/
`OS`: macOS

**Comment by yellowled** [comment]
Same (I think).

```
$ npm uninstall -g npm-check
Unhandled rejection Error: Argument #2: Expected string but got null error-ex@^1.2.0 fetched in 49m
    at addDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:515:3)
    at /usr/local/lib/node_modules/npm/lib/install/deps.js:463:5
    at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
    at Array.forEach (native)
    at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
    at Array.forEach (native)
    at asyncMap (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
    at loadDeps (/usr/local/lib/node_modules/npm/lib/install/deps.js:455:3)
    at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
    at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
    at /usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
    at /usr/local/lib/node_modules/npm/lib/install/and-finish-tracker.js:8:8
    at resolveBranchDeps.then (/usr/local/lib/node_modules/npm/lib/install/deps.js:419:11)
    at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```
```
$ node --version
v6.10.3
$ npm --version
5.0.3
```
Using `registry.npmjs.org` as well von macOS Sierra.

**Comment by kenany** [comment]
@julian- @yellowled See https://github.com/npm/npm/issues/16738.
