### ISSUE TITLE
Broken symlink to nested local dependency on install with package-lock.json

### ISSUE THREAD

**Issue by afters** [npm/npm#17025]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I have a project that has nested local dependencies in relative paths:
```
.
├── package_a/
├── package_b/
└── project/
```

With respective package.json files:
```
{
  "name": "package_a"
}
```
```
{
  "name": "package_b",
  "dependencies": {
    "package_a": "file:../package_a"
  }
}
```
```
{
  "name": "project",
  "dependencies": {
    "package_b": "file:../package_b"
  }
}
```
Running 'npm install', produces working symlinks, and a package-lock.json file:
```
> cd project/
> npm install
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN project@ No description
npm WARN project@ No repository field.
npm WARN project@ No license field.
> tree ..
..
├── package_a
│   └── package.json
├── package_b
│   ├── node_modules
│   │   └── package_a -> ../../package_a
│   └── package.json
└── project
    ├── node_modules
    │   └── package_b -> ../../package_b
    ├── package.json
    └── package-lock.json
> cat package-lock.json
{
  "name": "project",
  "lockfileVersion": 1,
  "dependencies": {
    "package_b": {
      "version": "file:../package_b",
      "dependencies": {
        "package_a": {
          "version": "file:../package_a",
          "bundled": true
        }
      }
    }
  }
}
```
Installing again after cleaning up 'node_modules' dirs but keeping the generated package-lock.json, produces **a broken link to package_a**:
```
> tree
.
├── package_a
│   └── package.json
├── package_b
│   └── package.json
└── project
    ├── package.json
    └── package-lock.json
> cd project/
> npm install
npm WARN project@ No description
npm WARN project@ No repository field.
npm WARN project@ No license field.

added 2 packages in 0.358s
> tree ..
..
├── package_a
│   └── package.json
├── package_b
│   ├── node_modules
│   │   └── package_a -> ../../../../package_a
│   └── package.json
└── project
    ├── node_modules
    │   └── package_b -> ../../package_b
    ├── package.json
    └── package-lock.json
```
I guess the package_a symlink would have worked in a scenario where package_b is installed, and not symlinked, under project/node_modules:
```
project/node_modules/package_b/node_modules/package_a -> ../../../../package_A
```

### supporting information:

 - `npm -v` prints: 5.0.3
 - `node -v` prints: v6.9.2
 - `npm config get registry` prints: http://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux

**Comment by revelt** [comment]
I'm having similar issues. After npm v5 was released, I noticed `npm i` might mess up the dependencies of linked dependencies, and often I have to wipe `node_modules` and lockfiles on both main package and all linked dependencies. This was not the case before `v5`.

**Comment by abdel-ships-it** [comment]
Same issue here on v5, its super annoying as I constantly have to remove the lockfile.

**Comment by JeanPerriault** [comment]
Same kind of issue with `node 6.11.0` and `npm 5.0.3` on Windows 7.
`optipng-bin@3.1.4`, `jpegtran-bin@3.2.0` and `gifsicle@3.0.4` postinstall are failing.
Removing package-lock.json file solves the issue.

**Comment by sidhuko** [comment]
You can add a .npmrc with `package-lock=false` within your project folder to disable the package-lock.json. Was having this issue earlier though so thanks for ticket.

Please note my ticket is another problem you may face #17362 in future when you add a package c which is included within two of your modules.

**Comment by iarna** [comment]
npm@5.1 (just released) fixes this bug!

**Comment by JeanPerriault** [comment]
I did not fix my specific issue, might be more specific.
Might be linked with grunt-contrib-imagemin. I've created an issue overthere (https://github.com/gruntjs/grunt-contrib-imagemin/issues/382), where I want to avoid using my company internet proxy.

But the error stack is different here, and the company internet proxy is set in .npmrc:

```
> gifsicle@http://test/artifactory/api/npm/npm/gifsicle/-/gifsicle-3.0.4.tgz postinstall C:\Users\test\Workspace\test\node_modules\gifsicle
> node lib/install.js

  ‼ Response code 404 (Not Found)
  ‼ gifsicle pre-build test failed
  i compiling from source
  × Error: autoreconf -ivf && ./configure --disable-gifview --disable-gifdiff --prefix="C:\Users\test\Workspace\test\node_modules\gifsicle\vendor" --bindir="C:\Users\test\Workspace\test\node_modules\gifsicle\vendor" && make in
stall
Command failed: autoreconf -ivf
'autoreconf' is not recognized as an internal or external command, operable program or batch file.

    at ChildProcess.exithandler (child_process.js:204:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:891:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:497:12)

> jpegtran-bin@http://test/artifactory/api/npm/npm/jpegtran-bin/-/jpegtran-bin-3.2.0.tgz postinstall C:\Users\test\Workspace\test\node_modules\jpegtran-bin
> node lib/install.js

  ‼ Response code 404 (Not Found)
  ‼ jpegtran pre-build test failed
  i compiling from source
  × Error: touch configure.ac aclocal.m4 configure Makefile.am Makefile.in && ./configure --disable-shared --prefix="C:\Users\test\Workspace\test\node_modules\jpegtran-bin\vendor" --bindir="C:\Users\test\Workspace\test\node_modules\jpegtran-bin\vendor" && make install
Command failed: ./configure --disable-shared --prefix="C:\Users\test\Workspace\test\node_modules\jpegtran-bin\vendor" --bindir="C:\Users\test\Workspace\test\node_modules\jpegtran-bin\vendor"
'.' is not recognized as an internal or external command, operable program or batch file.

    at ChildProcess.exithandler (child_process.js:204:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:891:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

> optipng-bin@http://test/artifactory/api/npm/npm/optipng-bin/-/optipng-bin-3.1.4.tgz postinstall C:\Users\test\Workspace\test\node_modules\optipng-bin
> node lib/install.js

  ‼ Response code 404 (Not Found)
  ‼ optipng pre-build test failed
  i compiling from source
  × Error: ./configure --with-system-zlib --prefix="C:\Users\test\Workspace\test\node_modules\optipng-bin\vendor" --bindir="C:\Users\test\Workspace\test\node_modules\optipng-bin\vendor" && make install
Command failed: ./configure --with-system-zlib --prefix="C:\Users\test\Workspace\test\node_modules\optipng-bin\vendor" --bindir="C:\Users\test\Workspace\test\node_modules\optipng-bin\vendor"
'.' is not recognized as an internal or external command, operable program or batch file.

    at ChildProcess.exithandler (child_process.js:204:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:891:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5
```
