### ISSUE TITLE
npm 5.0.1 regression: private GitHub repo = error ETARGET

### ISSUE THREAD

**Issue by rally25rs** [npm/npm#17022]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

This is a bug introduced in NPM 5.0.1 (5.0.0 was successful)

I have this dependency in my package.json which points to a branch of a Private repo:

```
  "devDependencies": {
    "grunt-ui-tasks": "git+ssh://git@github.com/my-company/grunt-ui-tasks#3.0.0"
  },
```

When here is no `package-lock.json` file in place, running an install results in:

```
$ rm -rf node_modules

$ rm package-lock.json

$ npm i
npm ERR! code ETARGET
npm ERR! notarget No matching version found for grunt-ui-tasks@3.0.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'my-project'
npm ERR! notarget
```

Additional notes:
* This works fine in npm 3 / node 6
* This works fine in npm 5.0.0 / node 8.0.0
* Clearing the npm cache makes no difference
* This did work in npm 5.0.0, I have a `package-lock.json` that I can use from that install
  * This error does *not* happen if the `package-lock.json` file is in place
  * This error *only* happens if the `package-lock.json` file is removed and `node_modules` is deleted (like a fresh install)

The `package-lock.json` file that I have from a previous successful install resolves the issue, and contains the entry:

```
    "grunt-ui-tasks": {
      "version": "git+ssh://git@github.com/my-company/grunt-ui-tasks.git#59cc0d2ff67c6f5db840e635a6f4a009e0a57b7c",
      "dev": true
    },
```

Rolling back to NPM 5.0.0 fixes the issue:

```
$ npm install -g npm@5.0.0

$ npm  --version
5.0.0

$ npm i
  ...output omitted...
added 1316 packages in 55.892s
```

#### How can the CLI team reproduce the problem?

The relevant chunk of debug log is:

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/jvalore/.nvm/versions/node/v8.0.0/bin/node',
1 verbose cli   '/Users/jvalore/.nvm/versions/node/v8.0.0/bin/npm',
1 verbose cli   'i' ]
2 info using npm@5.0.1
3 info using node@v8.0.0
4 silly install runPreinstallTopLevelLifecycles
5 silly preinstall runtime-ui@1.0.0
6 info lifecycle runtime-ui@1.0.0~preinstall: runtime-ui@1.0.0
7 silly lifecycle runtime-ui@1.0.0~preinstall: no script for preinstall, continuing
8 silly install loadCurrentTree
9 silly install readLocalPackageData
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 silly install loadShrinkwrap
13 silly install loadAllDepsIntoIdealTree
14 http fetch GET 200 https://registry.npmjs.org/sinon 20ms (from cache)
15 silly pacote range manifest for sinon@^1.17.7 fetched in 56ms
16 http fetch GET 200 https://registry.npmjs.org/formatio 19ms (from cache)
17 http fetch GET 200 https://registry.npmjs.org/util 20ms (from cache)
18 http fetch GET 200 https://registry.npmjs.org/samsam 19ms (from cache)
19 http fetch GET 200 https://registry.npmjs.org/lolex 20ms (from cache)
20 silly pacote version manifest for formatio@1.1.1 fetched in 23ms
21 silly pacote range manifest for util@>=0.10.3 <1 fetched in 24ms
22 silly pacote version manifest for samsam@1.1.2 fetched in 23ms
23 silly pacote version manifest for lolex@1.3.2 fetched in 26ms
24 silly pacote range manifest for samsam@~1.1 fetched in 3ms
25 http fetch GET 200 https://registry.npmjs.org/inherits 2ms (from cache)
26 silly pacote version manifest for inherits@2.0.1 fetched in 3ms
27 silly pacote range manifest for sinon@^1.17.7 fetched in 14ms
28 silly resolveWithNewModule sinon@1.17.7 checking installable status
29 silly fetchPackageMetaData error for grunt-ui-tasks@git+ssh://git@github.com/my-company/grunt-ui-tasks.git#3.0.0 No matching version found for grunt-ui-tasks@3.0.0
30 verbose type version
31 verbose stack grunt-ui-tasks: No matching version found for grunt-ui-tasks@3.0.0
31 verbose stack     at pickManifest (/Users/jvalore/.nvm/versions/node/v8.0.0/lib/node_modules/npm/node_modules/pacote/node_modules/npm-pick-manifest/index.js:61:11)
31 verbose stack     at git.revs.then.remoteRefs (/Users/jvalore/.nvm/versions/node/v8.0.0/lib/node_modules/npm/node_modules/pacote/lib/fetchers/git.js:137:7)
31 verbose stack     at tryCatcher (/Users/jvalore/.nvm/versions/node/v8.0.0/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
31 verbose stack     at Promise._settlePromiseFromHandler (/Users/jvalore/.nvm/versions/node/v8.0.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
31 verbose stack     at Promise._settlePromise (/Users/jvalore/.nvm/versions/node/v8.0.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
31 verbose stack     at Promise._fulfillPromises (/Users/jvalore/.nvm/versions/node/v8.0.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:668:14)
31 verbose stack     at Promise._settlePromises (/Users/jvalore/.nvm/versions/node/v8.0.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:694:18)
31 verbose stack     at Promise._fulfill (/Users/jvalore/.nvm/versions/node/v8.0.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:638:18)
31 verbose stack     at Promise._resolveCallback (/Users/jvalore/.nvm/versions/node/v8.0.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:432:57)
31 verbose stack     at Promise._settlePromiseFromHandler (/Users/jvalore/.nvm/versions/node/v8.0.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:524:17)
31 verbose stack     at Promise._settlePromise (/Users/jvalore/.nvm/versions/node/v8.0.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
31 verbose stack     at Promise._settlePromise0 (/Users/jvalore/.nvm/versions/node/v8.0.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
31 verbose stack     at Promise._settlePromises (/Users/jvalore/.nvm/versions/node/v8.0.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
31 verbose stack     at Promise._fulfill (/Users/jvalore/.nvm/versions/node/v8.0.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:638:18)
31 verbose stack     at Promise._resolveCallback (/Users/jvalore/.nvm/versions/node/v8.0.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:432:57)
31 verbose stack     at Promise._settlePromiseFromHandler (/Users/jvalore/.nvm/versions/node/v8.0.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:524:17)
```

### supporting information:

 - `npm -v` prints: 5.0.1
 - `node -v` prints: 8.0.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: OSX Sierra
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by rally25rs** [comment]
It looks like this issue is fixed by npm@5.0.3, so I am closing this issue. Glad to see it's already fixed 🎉
