### ISSUE TITLE
npm install fails on win

### ISSUE THREAD

**Issue by AlbertHambardzumyan** [npm/npm#17035]
#### I'm opening this issue because:

npm 5.0.3 fails to install on Windows 7

#### What's going wrong?
command npm install fails:
Unhandled rejection Error: Cannot find module 'concat-stream': sill install loadIdealTree
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\Alik\AppData\Roaming\npm\node_modules\npm\node_modules\npm-registry-client\lib\publish.js:8:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at new RegClient (C:\Users\Alik\AppData\Roaming\npm\node_modules\npm\node_modules\npm-registry-client\index.js:65:20)
    at EventEmitter.<anonymous> (C:\Users\Alik\AppData\Roaming\npm\node_modules\npm\lib\npm.js:348:26)
    at EventEmitter.Object.defineProperty.get (C:\Users\Alik\AppData\Roaming\npm\node_modules\npm\node_modules\lazy-property\lazyProperty.js:6:27)
    at pacoteOpts (C:\Users\Alik\AppData\Roaming\npm\node_modules\npm\lib\config\pacote.js:40:15)
    at fetchPackageMetadata (C:\Users\Alik\AppData\Roaming\npm\node_modules\npm\lib\fetch-package-metadata.js:58:24)

npm ERR! cb() never called!

#### How can the CLI team reproduce the problem?
npm install on Windows 7

### supporting information:

 - `npm -v` prints: 5.0.3
 - `node -v` prints: 6.10.3
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?: Windows 7

**Comment by iarna** [comment]
We're closing this support issue as it has gone three days without activity.  The npm CLI team itself does not provide support via this issue tracker, but we are happy when users help each other here.  In our experience once a support issue goes dormant it's unlikely to get further activity.  If you're still having problems, you may be better served by joining [package.community](https://package.community/) and asking your question there.

For more information about our new issue aging policies and why we've instituted them please see our [blog post](http://blog.npmjs.org/post/161832149430/npm-the-npm-github-issue-tracker-and-you).
