### ISSUE TITLE
NPM is not running correctly the WEBDRIVER on Windows 10

### ISSUE THREAD

**Issue by giovanihoff** [npm/npm#17040]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [X] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
"**npn run**" is not running "**webdriver:update**".

#### How can the CLI team reproduce the problem?
`  "devDependencies": {
    "chai": ">= 2.1.2 < 4",
    "chai-as-promised": "^6.0.0",
    "mocha": "^3.4.2",
    "protractor": ">=3.0.0",
    "serenity-js": "^1.5.0"
  }`
_$ npm install_
_$ npm run webdriver:update_

### supporting information:
 - `npm -v` prints: 3.10.10
 - `node -v` prints: 6.10.3
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?: Windows 10

`I was running the webdriver successfully. Suddenly, the webdriver did not run any more. Even reinstalling everything again. Please, what the problem?`

**Comment by giovanihoff** [comment]
**npm-debug.log**:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'webdriver:update' ]
2 info using npm@3.10.10
3 info using node@v6.10.3
4 verbose stack Error: missing script: webdriver:update
4 verbose stack     at run (C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:151:19)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:61:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:356:5
4 verbose stack     at checkBinReferences_ (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:320:45)
4 verbose stack     at final (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:354:3)
4 verbose stack     at then (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:124:5)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:311:12
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16
4 verbose stack     at tryToString (fs.js:456:3)
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:443:12)
5 verbose cwd C:\dev\workspace\ilegra\agco\agconline\segmentation-strategy-acceptance-test
6 error Windows_NT 10.0.15063
7 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "webdriver:update"
8 error node v6.10.3
9 error npm  v3.10.10
10 error missing script: webdriver:update
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

**Comment by kenany** [comment]
Hello! So, the way `npm run webdriver:update` works is that it looks in your current `package.json` for a defined `"webdriver:update"` [script](https://docs.npmjs.com/misc/scripts), and then runs that. The error message you're seeing is trying to tell you that you have not defined a `"webdriver:update"` script in your `package.json`, hence `npm run webdriver:update` has no idea what you want it to do.

To solve this issue, all you have to do is add a new script to your `package.json`. It might look something like this, for example:

``` json
{
  "name": "package-name",
  "version": "1.0.0",
  "description": "package description",
  "scripts": {
    "webdriver:update": "node --version",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "dependencies": {},
  "devDependencies": {}
}
```

Note how this `package.json` has a `"webdriver:update"` script that runs `node --version`. You'll definitely want to change the command to whatever is most appropriate for your project.

Let me know if you run into any further `npm` issues :)

**Comment by giovanihoff** [comment]
@KenanY, thank you for your help! But, I added a script in package.json as following:
```{
...
  "repository": {
...
  },
  "scripts": {
    "webdriver-update": "webdriver-manager update",
    "test": "protractor"
  },
  "devDependencies": {
    "chai": ">= 2.1.2 < 4",
    "chai-as-promised": "^6.0.0",
    "mocha": "^3.4.2",
    "protractor": ">=3.0.0",
    "selenium-webdriver":"3.0.1",
    "serenity-js": "^1.5.0"
  }
}
```

But It occurred the same problem. Please, we have some problem with execution. I created another project as "http://www.protractortest.org" basic setup, but It occurred a similar problem. I unistalled full node (delete C:\Users\...\AppData\Roaming\npm\), reset PC, install node and configure "http://www.protractortest.org" basic setup. Only this way worked. So, please, we have a problem with Protractor + WEBDRIVER + Windows!!! I will work again, but the problem will happen again.

**Comment by kenany** [comment]
@giovanihoff Can I see what error you are seeing now?

**Comment by giovanihoff** [comment]
OK, please, when the error happens again, I'll log, ok?

**Comment by giovanihoff** [comment]
package.json:
`{
   ...
  "repository": {
   ...
  },
  "scripts": {
    "setup":"npm install && node node_modules/protractor/bin/webdriver-manager update",
    "start": "node node_modules/protractor/bin/webdriver-manager start",
    "test": "protractor"
  },
  "devDependencies": {
    "chai": ">= 2.1.2 < 4",
    "chai-as-promised": "^6.0.0",
    "mocha": "^3.4.2",
    "protractor": ">=3.0.0",
    "serenity-js": "^1.5.0"
  }
}`

Error during **npm test**:
`> protractor

[19:17:10] I/launcher - Running 1 instances of WebDriver
[19:17:10] I/hosted - Using the selenium server at http://localhost:4444/wd/hub
[19:17:11] E/launcher - Error code: 135
[19:17:11] E/launcher - Error message: ECONNREFUSED connect ECONNREFUSED 127.0.0.1:4444
[19:17:11] E/launcher - Error: ECONNREFUSED connect ECONNREFUSED 127.0.0.1:4444
    at ClientRequest.<anonymous> (C:\dev\workspace\ilegra\agco\agconline\segmentation-strategy-acceptance-test\node_modules\selenium-webdriver\http\index.js:238:15)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1277:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
From: Task: WebDriver.createSession()
    at Function.createSession (C:\dev\workspace\ilegra\agco\agconline\segmentation-strategy-acceptance-test\node_modules\selenium-webdriver\lib\webdriver.js:777:24)
    at Function.createSession (C:\dev\workspace\ilegra\agco\agconline\segmentation-strategy-acceptance-test\node_modules\selenium-webdriver\chrome.js:709:29)
    at createDriver (C:\dev\workspace\ilegra\agco\agconline\segmentation-strategy-acceptance-test\node_modules\selenium-webdriver\index.js:167:33)
    at Builder.build (C:\dev\workspace\ilegra\agco\agconline\segmentation-strategy-acceptance-test\node_modules\selenium-webdriver\index.js:623:16)
    at Hosted.getNewDriver (C:\dev\workspace\ilegra\agco\agconline\segmentation-strategy-acceptance-test\node_modules\protractor\lib\driverProviders\driverProvider.ts:60:29)
    at Runner.createBrowser (C:\dev\workspace\ilegra\agco\agconline\segmentation-strategy-acceptance-test\node_modules\protractor\lib\runner.ts:225:39)
    at q.then.then (C:\dev\workspace\ilegra\agco\agconline\segmentation-strategy-acceptance-test\node_modules\protractor\lib\runner.ts:391:27)
    at _fulfilled (C:\dev\workspace\ilegra\agco\agconline\segmentation-strategy-acceptance-test\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\dev\workspace\ilegra\agco\agconline\segmentation-strategy-acceptance-test\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\dev\workspace\ilegra\agco\agconline\segmentation-strategy-acceptance-test\node_modules\q\q.js:796:13)
[19:17:11] E/launcher - Process exited with error code 135
npm ERR! Test failed.  See above for more details.`

@KenanY, please, I do not understand what is happening.

**Comment by kenany** [comment]
Doesn't look like an `npm` issue anymore. Might be something wrong with your internet connection or something, because:

```
[19:17:11] E/launcher - Error message: ECONNREFUSED connect ECONNREFUSED 127.0.0.1:4444
[19:17:11] E/launcher - Error: ECONNREFUSED connect ECONNREFUSED 127.0.0.1:4444
```

the connection to whatever is at that port is being refused.
