### ISSUE TITLE
npm link/unlink causes Maximum call stack size exceeded 

### ISSUE THREAD

**Issue by mayacoda** [npm/npm#17096]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I have a local package which was `npm link`ed with a previous version of npm, I don't remember which. It was also used (`npm link <package>`) in a different project. I've updated to **npm 5.0.2** and tried to `npm unlink <package>` in the project. I've also updated to **npm 5.0.3** with the same result. I get the following error message:

```
Unhandled rejection RangeError: Maximum call stack size exceeded0cc33440a00bed60
    at exports.create (/usr/local/lib/node_modules/npm/lib/install/node.js:33:25)
    at /usr/local/lib/node_modules/npm/lib/install/node.js:36:14
    at Array.forEach (native)
    at exports.create (/usr/local/lib/node_modules/npm/lib/install/node.js:33:25)
    at /usr/local/lib/node_modules/npm/lib/install/node.js:36:14
    at Array.forEach (native)
    at exports.create (/usr/local/lib/node_modules/npm/lib/install/node.js:33:25)
    at normalizeTree (/usr/local/lib/node_modules/npm/lib/install.js:377:5)
    at Array.forEach (native)
    at normalizeTree (/usr/local/lib/node_modules/npm/lib/install.js:379:19)
    at Array.forEach (native)
    at normalizeTree (/usr/local/lib/node_modules/npm/lib/install.js:379:19)
    at Array.forEach (native)
    at normalizeTree (/usr/local/lib/node_modules/npm/lib/install.js:379:19)
    at Array.forEach (native)
    at normalizeTree (/usr/local/lib/node_modules/npm/lib/install.js:379:19)

npm ERR! cb() never called!
```
Same error occurs when I try to `npm unlink` the package itself.

#### How can the CLI team reproduce the problem?

Not sure how to reproduce this situation other than the description above.
[npm-debug.log](https://gist.github.com/mayacoda/0d1ad963dd25977d205b34deebe3edcd)

### supporting information:

 - `npm -v` prints: 5.0.3
 - `node -v` prints: v7.9.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: macOS

**Comment by mayacoda** [comment]
Any news on this? I'm working around it by deleting node_modules, after which `npm link <package>` works like normal, but unlink still throws the same error.

**Comment by mkoczorowski** [comment]
+1

**Comment by bertho-zero** [comment]
+1

**Comment by rdshoep** [comment]
+1

**RangeError: Maximum call stack size exceeded**

* node v8.1.2
* npm  v5.0.4
* Darwin 16.6.0

**Comment by MadLittleMods** [comment]
Related to https://github.com/npm/npm/issues/17056
