### ISSUE TITLE
module.js:472     throw err;

### ISSUE THREAD

**Issue by mjshaikh7** [npm/npm#17130]
E:\Back1\my app\myapp> node app.js
module.js:472
    throw err;
    ^

Error: Cannot find module 'E:\Back1\my app\myapp\app.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:418:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:533:3

**Comment by kenany** [comment]
Error is not coming from `npm`.
