### ISSUE TITLE
Error: `make` failed with exit code: 2

### ISSUE THREAD

**Issue by xishoon** [npm/npm#17147]
Hey Guys I am running the following command  
 > sudo npm install -g bitcore
 
and it returns me the following error

```
compilation terminated.
make: *** [Release/obj.target/zmq/binding.o] Error 1
make: Leaving directory `/usr/local/lib/node_modules/bitcore/node_modules/bitcore-node/node_modules/zmq/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 4.4.0-75-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/bitcore/node_modules/bitcore-node/node_modules/zmq
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! Error: ENOENT, lstat '/usr/local/lib/node_modules/bitcore/node_modules/bitcore-node/node_modules/bitcore-lib/benchmark/block-357238.json'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 4.4.0-75-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "bitcore"
npm ERR! cwd /home/amaano
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /usr/local/lib/node_modules/bitcore/node_modules/bitcore-node/node_modules/bitcore-lib/benchmark/block-357238.json
npm ERR! fstream_path /usr/local/lib/node_modules/bitcore/node_modules/bitcore-node/node_modules/bitcore-lib/benchmark/block-357238.json
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! weird error 1
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/amaano/npm-debug.log
npm ERR! not ok code 0
```

**Comment by kenany** [comment]
Node 0.10 and `npm@1` are years old and are no longer supported. Can reopen if this is still an issue with newer versions of Node and `npm`.

**Comment by xishoon** [comment]
@KenanY  My node version is 
 

> v0.11.13

 
and npm version is 

> 1.4.9

**Comment by kenany** [comment]
@xishoon Still too old.

**Comment by xishoon** [comment]
I just Update the version. Now its working fine.
Thanks @KenanY  :)
