### ISSUE TITLE
npm install generator hipster install error

### ISSUE THREAD

**Issue by soodrah** [npm/npm#17157]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [X ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
49068 error  { Error: EPERM: operation not permitted, rename 'C:\Users\rsood1\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\yo\node_modules\tabtab' -> 'C:\Users\rsood1\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\yo\node_modules\.tabtab.DELETE'
49068 error     at moveAway (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:38:5)
49068 error     at destStatted (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:27:7)
49068 error     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:267:18
49068 error     at FSReqWrap.oncomplete (fs.js:123:15)
49068 error
49068 error Error: EPERM: operation not permitted, rename 'C:\Users\rsood1\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\yo\node_modules\tabtab' -> 'C:\Users\rsood1\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\yo\node_modules\.tabtab.DELETE'
49068 error     at Error (native) parent: 'yo' }
49069 error Please try running this command again as root/Administrator.
### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
49060 error Windows_NT 6.1.7601
49061 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "generator-jhipster"
49062 error node v6.10.3
49063 error npm  v3.10.10
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [X ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by soodrah** [comment]
tried uninstalling yarn and got following error
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\rsood1\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'uninstall',
1 verbose cli   '-g',
1 verbose cli   'yarn' ]
2 info using npm@5.0.3
3 info using node@v6.10.3
4 verbose npm-session 77bcadb51d06f64e
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly install loadIdealTree
8 silly install cloneCurrentTreeToIdealTree
9 silly install loadShrinkwrap
10 silly uninstall loadAllDepsIntoIdealTree
11 silly install loadAllDepsIntoIdealTree
12 error cb() never called!
13 error This is an error with npm itself. Please report this error at:
14 error <https://github.com/npm/npm/issues>

**Comment by soodrah** [comment]
not sure whats going on, hopefully someone can respond

**Comment by soodrah** [comment]
Here is what I already had Node, npm and yarn. When trying to install generator-hipster I would get error. 
I therefore uninstalled Node. Deleted the npm folder from users/appdata/roaming folder. Reinstalled latest node, Updated npm. Installed Yo. Then installed generator-jhipster. And after that if you need you can install yarn. Seems like you cant have both npm and yarn installed prior to installing generator-jhipster.
