### ISSUE TITLE
npm run eject - create-react-app

### ISSUE THREAD

**Issue by Olivr3** [npm/npm#17172]
This happens when I try to run 'npm run eject' after creating a project with 'create-react-app'.

Can anyone spot what is the error here? 

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'eject' ]
2 info using npm@5.0.1
3 info using node@v7.7.2
4 verbose run-script [ 'preeject', 'eject', 'posteject' ]
5 info lifecycle onthebeach@0.1.0~preeject: onthebeach@0.1.0
6 silly lifecycle onthebeach@0.1.0~preeject: no script for preeject, continuing
7 info lifecycle onthebeach@0.1.0~eject: onthebeach@0.1.0
8 verbose lifecycle onthebeach@0.1.0~eject: unsafe-perm in lifecycle true
9 verbose lifecycle onthebeach@0.1.0~eject: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/var/www/html/react/onthebeach/node_modul
es/.bin:/home/kujim/.composer/vendor/bin:/opt/glassfish4/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/lo
cal/games:/snap/bin:/snap/bin
10 verbose lifecycle onthebeach@0.1.0~eject: CWD: /var/www/html/react/onthebeach
11 silly lifecycle onthebeach@0.1.0~eject: Args: [ '-c', 'react-scripts eject' ]
12 silly lifecycle onthebeach@0.1.0~eject: Returned: code: 1  signal: null
13 info lifecycle onthebeach@0.1.0~eject: Failed to exec eject script
14 verbose stack Error: onthebeach@0.1.0 eject: `react-scripts eject`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:283:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:194:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:194:7)
14 verbose stack     at maybeClose (internal/child_process.js:899:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid onthebeach@0.1.0
16 verbose cwd /var/www/html/react/onthebeach
17 verbose Linux 4.4.0-79-generic
18 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "eject"
19 verbose node v7.7.2
20 verbose npm  v5.0.1
21 error code ELIFECYCLE
22 error errno 1
23 error onthebeach@0.1.0 eject: `react-scripts eject`
23 error Exit status 1
24 error Failed at the onthebeach@0.1.0 eject script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

**Comment by kenany** [comment]
Seems like `react-scripts eject` is throwing an error code. All `npm` is doing here is catching it and letting you know about it. Perhaps you could try:

```
./node_modules/.bin/react-scripts eject
```

from your command-line?

**Comment by Olivr3** [comment]
it tells me that I have untracked files even though I am using a different directory. 

```
This git repository has untracked files or uncommitted changes:

  ?? .vscode/,  ?? ci/app.zip,  ?? ci/ci_tutorial/,  ?? ci/lojasistem/application/controllers/Vendas.php,  ?? ci/lojasistem/application/view
s/vendas.php,  ?? ci/lojasistem/assets/js/index.js,  ?? ci/resume/,  ?? ci/system/,  ?? enonic/,  ?? express/CssExample/,  ?? express/projec
t/,  ?? golaacai/,  ?? golaguarana/,  ?? phpmyadmin,  ?? react/,  ?? references/,  ?? tutorials/,  ?? typescript/,  ?? wordpress/

Remove untracked files, stash or commit any changes, and try again.
```
How can I remove those files?

**Comment by Olivr3** [comment]
Right, I had to commit the changes. It all works fine now.

Thank you!

**Comment by dmacmillan** [comment]
What do you mean you had to commit the changes? Can you explain? Having the same issue

**Comment by philip-iv** [comment]
the command will fail if you have un-committed changes in your git repository
