### ISSUE TITLE
ERR! self signed certificate in certificate chain

### ISSUE THREAD

**Issue by balrajo** [npm/npm#17210]
Getting error "self signed certificate in certificate chain" for below 3 packages, everything else is working fine.
1. optipng-bin@3.1.4
2. jpegtran-bin@3.2.0
3. gifsicle@3.0.4

Error  Log:
> optipng-bin@3.1.4 postinstall <Path>\node_modules\optipng-bin
> node lib/install.js

  ‼ self signed certificate in certificate chain
  ‼ optipng pre-build test failed
  i compiling from source
  x RequestError: self signed certificate in certificate chain
    at ClientRequest.<anonymous> (<Path>\node_modules\got\index.js:74:21)
    at ClientRequest.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at emitErrorNT (net.js:1276:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

> jpegtran-bin@3.2.0 postinstall <Path>\node_modules\jpegtran-bin
> node lib/install.js

  ‼ self signed certificate in certificate chain
  ‼ jpegtran pre-build test failed
  i compiling from source
  x RequestError: self signed certificate in certificate chain
    at ClientRequest.<anonymous> (<Path>\node_modules\got\index.js:74:21)
    at ClientRequest.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at emitErrorNT (net.js:1276:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

> gifsicle@3.0.4 postinstall <Path>\node_modules\gifsicle
> node lib/install.js

  ‼ self signed certificate in certificate chain
  ‼ gifsicle pre-build test failed
  i compiling from source
  x RequestError: self signed certificate in certificate chain
    at ClientRequest.<anonymous> (<Path>\node_modules\got\index.js:74:21)
    at ClientRequest.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at emitErrorNT (net.js:1276:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

> undefined postinstall <Path>

**Comment by MichaelKunze** [comment]
Same here. Using proper cafile in .npmrc with selfsigned root ca. Still getting a ssl warning/error.
