### ISSUE TITLE
Having Problems getting npm install Laravel-Elixir to work on a Windows x64 via powershell ran as administrator

### ISSUE THREAD

**Issue by frlzjosh** [npm/npm#17220]
`PS C:\> cd wamp64/www/blog
PS C:\wamp64\www\blog> npm install

> node-sass@4.5.3 install C:\wamp64\www\blog\node_modules\node-sass
> node scripts/install.js

module.js:487
    throw err;
    ^

Error: Cannot find module 'mkdirp'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\wamp64\www\blog\node_modules\node-sass\scripts\install.js:7:11)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)

> pngquant-bin@3.1.1 postinstall C:\wamp64\www\blog\node_modules\pngquant-bin
> node lib/install.js

module.js:487
    throw err;
    ^

Error: Cannot find module 'process-nextick-args'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\wamp64\www\blog\node_modules\buffer-to-vinyl\node_modules\readable-stream\lib\_stream_read
able.js:6:23)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)

> optipng-bin@3.1.4 postinstall C:\wamp64\www\blog\node_modules\optipng-bin
> node lib/install.js

module.js:487
    throw err;
    ^

Error: Cannot find module 'process-nextick-args'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\wamp64\www\blog\node_modules\buffer-to-vinyl\node_modules\readable-stream\lib\_stream_read
able.js:6:23)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)

> mozjpeg@4.1.1 postinstall C:\wamp64\www\blog\node_modules\mozjpeg
> node lib/install.js

module.js:487
    throw err;
    ^

Error: Cannot find module 'process-nextick-args'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\wamp64\www\blog\node_modules\buffer-to-vinyl\node_modules\readable-stream\lib\_stream_read
able.js:6:23)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)

> gifsicle@3.0.4 postinstall C:\wamp64\www\blog\node_modules\gifsicle
> node lib/install.js

module.js:487
    throw err;
    ^

Error: Cannot find module 'process-nextick-args'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\wamp64\www\blog\node_modules\buffer-to-vinyl\node_modules\readable-stream\lib\_stream_read
able.js:6:23)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
npm WARN blog No repository field.
npm WARN blog No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.5.3 (node_modules\node-sass):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.5.3 install: `node scripts/install.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: pngquant-bin@3.1.1 (node_modules\pngquant-bin):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: pngquant-bin@3.1.1 postinstall: `node lib/install.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: optipng-bin@3.1.4 (node_modules\optipng-bin):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: optipng-bin@3.1.4 postinstall: `node lib/install.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: mozjpeg@4.1.1 (node_modules\mozjpeg):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: mozjpeg@4.1.1 postinstall: `node lib/install.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: gifsicle@3.0.4 (node_modules\gifsicle):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: gifsicle@3.0.4 postinstall: `node lib/install.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

added 795 packages, removed 394 packages and moved 55 packages in 45.838s
PS C:\wamp64\www\blog> npm install -g
Terminate batch job (Y/N)? n
PS C:\wamp64\www\blog>`

I dont know even what the problem might be now i saw someone use this command 
`npm install npm@latest -g`
And that worked for me but when i tried to type in 'npm install laravel elixir' It's a whole other story. One of the guys that was helping me out said that it's trying to find binarys, which is why it's saying it can't find python, and also why it's giving you an HTP 404 for a website that doesn't exist that tried to find binarys there. It's a few steps haha. Also it said it needed package.json file and when i first tried all of this i got a package-lock.json. Im sorry i know it's a lot, but if you've run through this situation before please let me know

**Comment by green3g** [comment]
I had issues installing my projects dependencies with powershell...could be related. I switched to git-bash and project now installs with npm 5.x

**Comment by victorybiz** [comment]
I had same issue, any fix/solution yet?

**Comment by frlzjosh** [comment]
So, I haven't touched this problem in a while, but
