### ISSUE TITLE
"EPERM, Operation not permitted" when running the "doctor" command

### ISSUE THREAD

**Issue by FrankSansC** [npm/npm#17221]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
npm info it worked if it ends with ok
npm info using npm@5.0.3
npm info using node@v8.1.1
npm info doctor Running checkup
npm info checkPing Pinging registry
npm info attempt registry request try #1 at 9:43:21 AM
npm http request GET https://registry.npmjs.org/-/ping?write=true
npm http 200 https://registry.npmjs.org/-/ping?write=true
npm info getLatestNpmVersion Getting npm package information
npm http fetch GET 200 https://registry.npmjs.org/npm 25ms (from cache)
npm info getLatestNodejsVersion Getting Node.js release information
npm info getGitPath Finding git in your PATH
npm WARN checkFilePermissions Error: EPERM, Operation not permitted
npm WARN checkFilePermissions     at /usr/local/lib/node_modules/npm/node_modules/uid-number/uid-number.js:49:16
npm WARN checkFilePermissions     at ChildProcess.exithandler (child_process.js:262:7)
npm WARN checkFilePermissions     at emitTwo (events.js:125:13)
npm WARN checkFilePermissions     at ChildProcess.emit (events.js:213:7)
npm WARN checkFilePermissions     at maybeClose (internal/child_process.js:897:16)
npm WARN checkFilePermissions     at Socket.stream.socket.on (internal/child_process.js:340:11)
npm WARN checkFilePermissions     at emitOne (events.js:115:13)
npm WARN checkFilePermissions     at Socket.emit (events.js:210:7)
npm WARN checkFilePermissions     at Pipe._handle.close [as _onclose] (net.js:548:12)
npm WARN checkFilePermissions  Error looking up user and group: { Error: EPERM, Operation not permitted
npm WARN checkFilePermissions     at /usr/local/lib/node_modules/npm/node_modules/uid-number/uid-number.js:49:16
npm WARN checkFilePermissions     at ChildProcess.exithandler (child_process.js:262:7)
npm WARN checkFilePermissions     at emitTwo (events.js:125:13)
npm WARN checkFilePermissions     at ChildProcess.emit (events.js:213:7)
npm WARN checkFilePermissions     at maybeClose (internal/child_process.js:897:16)
npm WARN checkFilePermissions     at Socket.stream.socket.on (internal/child_process.js:340:11)
npm WARN checkFilePermissions     at emitOne (events.js:115:13)
npm WARN checkFilePermissions     at Socket.emit (events.js:210:7)
npm WARN checkFilePermissions     at Pipe._handle.close [as _onclose] (net.js:548:12) errno: 1 }
npm ERR! code [ 'EPERM',
npm ERR! code   'EPERM',
npm ERR! code   index: 0,
npm ERR! code   input: 'EPERM, Operation not permitted' ]
npm ERR! errno 1
npm ERR! EPERM, Operation not permitted

#### How can the CLI team reproduce the problem?
`npm --loglevel=info --global doctor`

### supporting information:

 - `npm -v` prints: 5.0.3
 - `node -v` prints: v8.1.1
 - `npm config get registry` prints: https://registry.npmjs.org/
 -  `uname -a` : Darwin mac-xxx 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64
 - `osver` :
ProductName:	Mac OS X
ProductVersion:	10.12.5
BuildVersion:	16F73
 - `brew -v` : Homebrew 1.2.3-9-g3fe32053a7
Homebrew/homebrew-core (git revision 7a8bf; last commit 2017-06-14)

**Comment by jalal** [comment]
Same problem here but on an Ubuntu 16.04 installation;

`npm -v`: 5.0.4
`node -v`: v6.11.4

**Comment by awadev** [comment]
I get the same here when doing a `npm doctor -g` on MacOS 10.13.1, everything seems to be working fine otherwise though.

npm WARN checkFilePermissions Error: EPERM, Operation not permitted
npm WARN checkFilePermissions     at /usr/local/lib/node_modules/npm/node_modules/uid-number/uid-number.js:49:16
npm WARN checkFilePermissions     at ChildProcess.exithandler (child_process.js:267:7)
npm WARN checkFilePermissions     at emitTwo (events.js:126:13)
npm WARN checkFilePermissions     at ChildProcess.emit (events.js:214:7)
npm WARN checkFilePermissions     at maybeClose (internal/child_process.js:925:16)
npm WARN checkFilePermissions     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
npm WARN checkFilePermissions  Error looking up user and group: { Error: EPERM, Operation not permitted
npm WARN checkFilePermissions     at /usr/local/lib/node_modules/npm/node_modules/uid-number/uid-number.js:49:16
npm WARN checkFilePermissions     at ChildProcess.exithandler (child_process.js:267:7)
npm WARN checkFilePermissions     at emitTwo (events.js:126:13)
npm WARN checkFilePermissions     at ChildProcess.emit (events.js:214:7)
npm WARN checkFilePermissions     at maybeClose (internal/child_process.js:925:16)
npm WARN checkFilePermissions     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
npm WARN checkFilePermissions   stack: 'Error: EPERM, Operation not permitted\n    at /usr/local/lib/node_modules/npm/node_modules/uid-number/uid-number.js:49:16\n    at ChildProcess.exithandler (child_process.js:267:7)\n    at emitTwo (events.js:126:13)\n    at ChildProcess.emit (events.js:214:7)\n    at maybeClose (internal/child_process.js:925:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)',
npm WARN checkFilePermissions   errno: 1 }
npm ERR! code [ 'EPERM',
npm ERR! code   'EPERM',
npm ERR! code   index: 0,
npm ERR! code   input: 'EPERM, Operation not permitted' ]
npm ERR! errno 1
npm ERR! EPERM, Operation not permitted

`npm -v` 5.5.1
`node -v` v8.9.1
