### ISSUE TITLE
Unhandled rejection RangeError: Maximum call stack size exceededp

### ISSUE THREAD

**Issue by sbfkcel** [npm/npm#17244]
λ npm link
Unhandled rejection RangeError: Maximum call stack size exceededpreinstall: no script for preinstall, continuing
    at exports.create (D:\nvm\v8.1.2\node_modules\npm\lib\install\node.js:33:25)
    at D:\nvm\v8.1.2\node_modules\npm\lib\install\node.js:36:14
    at Array.forEach (native)
    at exports.create (D:\nvm\v8.1.2\node_modules\npm\lib\install\node.js:33:25)
    at D:\nvm\v8.1.2\node_modules\npm\lib\install\node.js:36:14
    at Array.forEach (native)
    at exports.create (D:\nvm\v8.1.2\node_modules\npm\lib\install\node.js:33:25)
    at normalizeTree (D:\nvm\v8.1.2\node_modules\npm\lib\install.js:377:5)
    at Array.forEach (native)
    at normalizeTree (D:\nvm\v8.1.2\node_modules\npm\lib\install.js:379:19)
    at Array.forEach (native)
    at normalizeTree (D:\nvm\v8.1.2\node_modules\npm\lib\install.js:379:19)
    at Array.forEach (native)
    at normalizeTree (D:\nvm\v8.1.2\node_modules\npm\lib\install.js:379:19)
    at Array.forEach (native)
    at normalizeTree (D:\nvm\v8.1.2\node_modules\npm\lib\install.js:379:19)

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\单炒饭\AppData\Roaming\npm-cache\_logs\2017-06-16T02_18_06_773Z-debug.log

**Comment by sbfkcel** [comment]
npm -v
5.0.3

**Comment by sbfkcel** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\nodejs\\node.exe',
1 verbose cli   'D:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'link' ]
2 info using npm@5.0.3
3 info using node@v8.1.2
4 verbose linkPkg G:\fws
5 verbose link build target D:\nodejs\node_modules\fws
6 verbose npm-session c4fb401011c5d008
7 silly install runPreinstallTopLevelLifecycles
8 silly preinstall fws@0.5.3
9 info lifecycle fws@0.5.3~preinstall: fws@0.5.3
10 silly lifecycle fws@0.5.3~preinstall: no script for preinstall, continuing
11 silly install loadCurrentTree
12 silly install readLocalPackageData
13 error cb() never called!
14 error This is an error with npm itself. Please report this error at:
15 error <https://github.com/npm/npm/issues>

**Comment by madelinecameron** [comment]
Having this issue too right now. Trying to figure it out. Did you get anywhere? :)

EDIT: npm -v: 5.0.4

**Comment by madelinecameron** [comment]
Actions:

- Wiped out sym link in /usr/lib/node_modules (Didn't fix)
- Wiped out ~/.npm (Didn't fix)
- Updated to v5.1.0 (Didn't fix)
- Downgraded to v4.6.1 (Fixed)

Looks like there was a big refactor to the relevant method ~two months ago (`normalizeTree` in install.js) so maybe something is broken. 

I don't think I am doing anything too crazy. I saw that there was some mention that projects that were created in v4 could have issues in v5 but I didn't read much into it.
