### ISSUE TITLE
maximum call stack size exceeded when running npm link(v5.0.{0,3})

### ISSUE THREAD

**Issue by b-admike** [npm/npm#17256]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I tried to link a module using npm  v5.0.0 and v5.0.3 and get the following:
```
| => npm link
Unhandled rejection RangeError: Maximum call stack size exceeded lifecycle loopback-connecto
    at exports.create (/Users/badmike/n/lib/node_modules/npm/lib/install/node.js:31:40)
    at /Users/badmike/n/lib/node_modules/npm/lib/install/node.js:36:14
    at Array.forEach (native)
    at exports.create (/Users/badmike/n/lib/node_modules/npm/lib/install/node.js:33:25)
    at /Users/badmike/n/lib/node_modules/npm/lib/install/node.js:36:14
    at Array.forEach (native)
    at exports.create (/Users/badmike/n/lib/node_modules/npm/lib/install/node.js:33:25)
    at normalizeTree (/Users/badmike/n/lib/node_modules/npm/lib/install.js:377:5)
    at Array.forEach (native)
    at normalizeTree (/Users/badmike/n/lib/node_modules/npm/lib/install.js:379:19)
    at Array.forEach (native)
    at normalizeTree (/Users/badmike/n/lib/node_modules/npm/lib/install.js:379:19)
    at Array.forEach (native)
    at normalizeTree (/Users/badmike/n/lib/node_modules/npm/lib/install.js:379:19)
    at Array.forEach (native)
    at normalizeTree (/Users/badmike/n/lib/node_modules/npm/lib/install.js:379:19)

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/badmike/.npm/_logs/2017-06-16T13_45_27_658Z-debug.log
```
#### How can the CLI team reproduce the problem?
1. Install (stable) node via `n` -> node v8.0.0 and npm v5.0.0
2. Clone https://github.com/strongloop/loopback-connector-mysql/
3. cd to the directory and run `npm link`

gist of `npm-debug.log` https://gist.github.com/b-admike/8f4faf9a0266401a95baf4b2508a2d91

### supporting information:

```
___________________    | ~/migrationtestapp @ Biniams-MacBook-Pro (badmike)
| => npm -v
5.0.0
___________________    | ~/migrationtestapp @ Biniams-MacBook-Pro (badmike)
| => node -v
v8.0.0
___________________    | ~/migrationtestapp @ Biniams-MacBook-Pro (badmike)
| => npm config get registry
https://registry.npmjs.org/
```
 - OS X

**Comment by b-admike** [comment]
Looks like a dup of https://github.com/npm/npm/issues/17096. Closing this, but perhaps the reproduction steps can help.
