### ISSUE TITLE
NPM v5 - RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by ORESoftware** [npm/npm#17264]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I am seeing a lot of 
RangeError: Maximum call stack size exceeded

I am seeing this on two different personal machines, one running Ubuntu the other running MacOS Sierra.
when using NPM version 5+. If I downgrade to 4.6.1, everything is ok.
Seems like a big problem, and I don't see that many reports of this problem

`RangeError: Maximum call stack size exceeded\n    at Array.forEach (native)\n    at exports.create (/home/oleg/.nvm/versions/node/v8.1.2/lib/node_modules/npm/lib/install/node.js:33:25)\n    at /home/oleg/.nvm/versions/node/v8.1.2/lib/node_modules/npm/lib/install/node.js:36:14\n    at Array.forEach (native)\n    at exports.create (/home/oleg/.nvm/versions/node/v8.1.2/lib/node_modules/npm/lib/install/node.js:33:25)\n    at /home/oleg/.nvm/versions/node/v8.1.2/lib/node_modules/npm/lib/install/node.js:36:14\n    at Array.forEach (native)\n    at exports.create (/home/oleg/.nvm/versions/node/v8.1.2/lib/node_modules/npm/lib/install/node.js:33:25)\n    at normalizeTree (/home/oleg/.nvm/versions/node/v8.1.2/lib/node_modules/npm/lib/install.js:377:5)\n    at Array.forEach (native)\n    at normalizeTree (/home/oleg/.nvm/versions/node/v8.1.2/lib/node_modules/npm/lib/install.js:379:19)\n    at Array.forEach (native)\n    at normalizeTree (/home/oleg/.nvm/versions/node/v8.1.2/lib/node_modules/npm/lib/install.js:379:19)\n    at Array.forEach (native)\n    at normalizeTree (/home/oleg/.nvm/versions/node/v8.1.2/lib/node_modules/npm/lib/install.js:379:19)\n    at Array.forEach (native)\nnpm ERR! cb() never called!\n\nnpm ERR! This is an error with npm itself. Please report this error at:\nnpm ERR!     <https://github.com/npm/npm/issues>\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /home/oleg/.npm/_logs/2017-06-17T03_45_18_530Z-debug.log\n' }`

#### How can the CLI team reproduce the problem?

If you need more information, I will be happy to provide it thanks. All I am doing is running `npm install `after running `rm -rf node_modules`.

**Comment by mayacoda** [comment]
I'm getting the same error: #17096
