### ISSUE TITLE
Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/electron/.electron'

### ISSUE THREAD

**Issue by Jacksonler** [npm/npm#17268]
Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/electron/.electron'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@1.6.11 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@1.6.11 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-06-17T04_24_22_944Z-debug.log
root@lhh-Inspiron-5537:/# gedit /root/.npm/_logs/2017-06-17T04_23_14_538Z-debug.log
####How to solve it?

**Comment by a1626** [comment]
Try running `npm install` with sudo.

**Comment by olya777** [comment]
I tried running with sudo. Still same issue

**Comment by a1626** [comment]
Can you provide more details like module name, OS, npm version.

**Comment by ander7agar** [comment]
I have the same issue. I use Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2 (2017-04-30) x86_64 GNU/Linux. I have executed the command as root and I have obtained this output:
```
/usr/local/bin/electron -> /usr/local/lib/node_modules/electron/cli.js

> electron@1.6.11 postinstall /usr/local/lib/node_modules/electron
> node install.js

/usr/local/lib/node_modules/electron/install.js:47
  throw err
  ^

Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/electron/.electron'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@1.6.11 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@1.6.11 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-06-20T10_25_47_997Z-debug.log
```

**Comment by a1626** [comment]
which package?

**Comment by reblevins** [comment]
I'm getting the same error with `sudo npm install -g electron@1.7.2` and also `sudo npm install -g electron`

Linux version 3.18.0-14856-g9bbe428768eb (chrome-bot@cros-beefy107-c2) (gcc version 4.9.x 20150123 (prerelease) (4.9.2_cos_gg_4.9.2-r154-32c89c19b042a12b5a1bf0153299154ea5435c03_4.9.2-r154) ) #1 SMP PREEMPT Wed Jun 14 22:13:29 PDT 2017

(I am running inside a chroot on a Chromebook if that makes any difference.)

I have attached the output from /home/username_redacted/.npm/_logs/2017-06-20T14_43_16_506Z-debug.log.
[2017-06-20T14_43_16_506Z-debug.txt](https://github.com/npm/npm/files/1088704/2017-06-20T14_43_16_506Z-debug.txt)

**Comment by ander7agar** [comment]
I'm trying to install it using `sudo npm install -g electron`. I have these versions installed:
```
npm -v
5.0.3
```
```
node -v
v7.4.0
```

**Comment by a1626** [comment]
The problem doesn't seem to be with `npm install` but with `postinstall` script of electron.

I think the correct place to open an issue will be electron's repository, otherwise you can also try changing global repository to some other location where sudo is not required.

**Comment by reblevins** [comment]
Ah yes, you're right. I just landed on this page from Google and didn't even check where I was. My bad.

**Comment by a1626** [comment]
i've opened an [issue](https://github.com/electron-userland/electron-prebuilt/issues/263) with `electron-prebuilt` for same.

**Comment by ander7agar** [comment]
This command fix the issue. It works for me:

`sudo npm install -g electron --unsafe-perm=true --allow-root`

**Comment by reblevins** [comment]
@ander7agar that did the trick! Thanks.

**Comment by a1626** [comment]
minor correction `--allow-root` is not required, and i don't think any such flag exist in `npm` (it's there in bower).

**Comment by onevcat** [comment]
Same problem

**Comment by a1626** [comment]
@onevcat Please use the command suggested by @ander7agar in his last comment.

**Comment by lshengjian** [comment]
npm -v
5.3.0
node -v
v8.1.4

> electron@1.6.11 postinstall /usr/lib/node_modules/electron
> node install.js

/usr/lib/node_modules/electron/install.js:47
  throw err
  ^

Error: connect ETIMEDOUT 54.231.73.51:443
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@1.6.11 postinstall: `node install.js`
npm ERR! Exit status 1

**Comment by wlongxiang** [comment]
@ander7agar This commands solved my problem, thanks dude!

**Comment by DiscoBiscuit99** [comment]
Problem solved with @ander7agar's solution. Thank you.

**Comment by omarxp** [comment]
thanks @ander7agar It works for me.

**Comment by hitalo07** [comment]
@ander7agar  This commands solved my problem. Thank you.

**Comment by Celtak** [comment]
Good. Problem finally solved thank you very much @ander7agar

**Comment by jmrsnt** [comment]
@ander7agar Thank you! saved my project!

**Comment by erdemildiz** [comment]
Thanks @ander7agar Its works 🎉

**Comment by LalaRzayeva** [comment]
thanks @ander7agar, it works for me also !

**Comment by dsouzadyn** [comment]
This should still be fixed I think

**Comment by aetheryx** [comment]
Still broken on my end - running on Arch, node v8.8.1, npm 5.5.1. ander7agar's script works fine.

**Comment by sumh** [comment]
same issue 

> OS: Ubuntu 16.04 Node 8.9.1 NPM 5.5.1


```
$ sudo npm install -g electron

/usr/local/bin/electron -> /usr/local/lib/node_modules/electron/cli.js

> electron@1.7.9 postinstall /usr/local/lib/node_modules/electron
> node install.js

/usr/local/lib/node_modules/electron/install.js:48
  throw err
  ^

Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/electron/dist'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@1.7.9 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron@1.7.9 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2017-11-25T08_33_27_546Z-debug.log
```

**Comment by aetheryx** [comment]
@sumh give ander7agar's command a try, it worked for me.

**Comment by sumh** [comment]
Thanks @Aetheryx  it worked .

**Comment by clecap** [comment]
The workaround works but **THIS STILL SHOULD BE FIXED.**

**Comment by r3klaw** [comment]
anders command worked for me
(npm install -g electron --unsafe-perm=true --allow-root)

**Comment by r3klaw** [comment]
@ander7agar command works like a charm
npm install -g electron --unsafe-perm=true --allow-root

**Comment by Naskall** [comment]
sudo npm install -g electron --unsafe-perm=true --allow-root 

> @ander7agar  Thank you, works for me.

**Comment by Knutsi** [comment]
Same problem for me on Ubuntu 17.10.  node 9.3 installed from nodesource.

**Comment by corentincam** [comment]
Same problem on Debian Stretch, @ander7agar solution solved it, thanks !

**Comment by stevensonmt** [comment]
Manjaro Linux, npm 5.6.0, same problem installing elm globally.  adding `--unsafe-perm=true` did the trick.

**Comment by priyankamalviya** [comment]
@ander7agar This command did not work for me, I still get the same error - "Failed at the electron@1.7.10 postinstall script 'node install.js'." Looks like I cannot install electron in root anymore, based on this [link](https://stackoverflow.com/questions/33309005/sudo-mkdir-in-usr-operation-not-permitted-el-capitan). Is it possible to install electron at /usr/local? If yes, how do I do it?

**Comment by goodinmech** [comment]
@priyankamalviya,  try install latest version of npm

**Comment by disarticulate** [comment]
seems like by now NPM should just recommend @ander7agar solution or link to this page.

**Comment by flcortesT** [comment]
sudo npm install -g electron its working. Thank you

**Comment by ayuthmang** [comment]
I think maybe use yarn like this.

```js
yarn global add electron
```

It's actually works for me.

**Comment by kfiresmith** [comment]
Sheesh.  Thank goodness for google.  And thanks to @ander7agar for taking the time to post the fix!

**Comment by PavloBida** [comment]
@ander7agar thanks a lot!

**Comment by edvilme** [comment]
@ander7agar thank you very much!!!! It solved my problem!!!

**Comment by darkguy2008** [comment]
I can't believe this isn't fixed yet

**Comment by aguyinmontreal** [comment]
@ander7agar   Thank you sooo much for this fix!  It worked to fix my issue of installing my package containing the `node-gyp` package on Ubuntu 16.04.

 `sudo npm install --unsafe-perm=true --allow-root`

**Comment by jlnmay** [comment]
I had a similar problem with sudo npm install 
this fix my issue sudo npm install --unsafe-perm=true --allow-root.

Thanks @ander7agar

**Comment by engrashid** [comment]
@ander7agar  thanks that worked

**Comment by khiami** [comment]
I was successfully able to install electron with the following
```
# on project directory
npm cache clean --force
# npm install
# cd to where npm globally installs the packages (check yours via npm -g root)
cd /usr/local/lib/
sudo npm install electron
```

I tried the same thing but from my project directory and failed.. threw access denied error.

**Comment by NatoBoram** [comment]
https://github.com/npm/npm/issues/17268#issuecomment-310167614

```bash
sudo npm install -g electron --unsafe-perm=true --allow-root
/usr/bin/electron -> /usr/lib/node_modules/electron/cli.js

> electron@1.8.4 postinstall /usr/lib/node_modules/electron
> node install.js

Downloading electron-v1.8.4-linux-x64.zip
Error: self signed certificate in certificate chain
/usr/lib/node_modules/electron/install.js:47
  throw err
  ^

Error: self signed certificate in certificate chain
    at TLSSocket.<anonymous> (_tls_wrap.js:1105:38)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
    at TLSSocket._finishInit (_tls_wrap.js:639:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:469:38)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@1.8.4 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@1.8.4 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by gasparyanyur** [comment]
@NatoBoram I have get the same error. Have you solve it ?

**Comment by danieldram** [comment]
someone needs to give @ander7agar  an award or something wow thank you!

**Comment by ghost** [comment]
@ander7agar Thank you, it works even for other packages.

**Comment by NatoBoram** [comment]
@gasparyanyur Nope. We abandoned the project. If we can't install the framework, *just imagine* what kind of pile of trash we're going to have to deal with in the future. But if you find a solution, I'm still searching for it -- for personal curiosity, this time.

**Comment by PierBover** [comment]
Not sure if NPM or Electron is to blame here, but since I didn't want to install globally I simply did:

`sudo npm install electron --unsafe-perm=true --allow-root`

And it worked.

**Comment by caleberi** [comment]
pls,i tried using sudo npm install -g electron --unsafe-perm=true --allow-root but  i got this error
`/home/ace/Documents/projects/electron/Electron# sudo npm install  electron --unsafe-perm=true --allow-root

> electron@1.8.7 postinstall /home/ace/Documents/projects/electron/Electron/node_modules/electron
> node install.js

Downloading electron-v1.8.7-linux-x64.zip
Error: tunneling socket could not be established, statusCode=400
/home/ace/Documents/projects/electron/Electron/node_modules/electron/install.js:47
  throw err
  ^

Error: tunneling socket could not be established, statusCode=400
    at ClientRequest.onConnect (/home/ace/Documents/projects/electron/Electron/node_modules/tunnel-agent/index.js:166:19)
    at Object.onceWrapper (events.js:319:30)
    at emitThree (events.js:136:13)
    at ClientRequest.emit (events.js:217:7)
    at TLSSocket.socketOnData (_http_client.js:474:11)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at TLSSocket.Readable.push (_stream_readable.js:208:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@1.8.7 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@1.8.7 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-06-17T21_33_03_089Z-debug.log
`

**Comment by legodude17** [comment]
That is an issue with electron, and probably your internet

**Comment by flounders** [comment]
I'm getting the same problem, not with Electron, but with Purescript. The solution @ander7agar gave works. When I ran `sudo npm install -g --unsafe-perm=true --allow-root purescript`, it worked.

Here is the output I got before trying that command:

```
$ sudo npm install -g purescript
[sudo] password for swilliams:
/usr/bin/purs -> /usr/lib/node_modules/purescript/purs.bin

> purescript@0.12.0 postinstall /usr/lib/node_modules/purescript
> install-purescript --purs-ver=0.12.0 .

✔ Check if a prebuilt 0.12.0 binary is provided for Linux (1s)
✖ Download the prebuilt PureScript binary
  https://github-production-release-asset-2e65be.s3.amazonaws.com/13206906/5a0581e4-5d11-11e8-8b97-abcb676fe5ed?X-Amz-Algorithm=AWS…
  Error: EACCES: permission denied, open 'purs.bin'
▬ Verify the prebuilt binary works correctly
▬ Save the downloaded binary to the cache directory

↓ Fallback: building from source

✔ Check if 'stack' command is available
  1.7.1 found at /usr/bin/stack
✖ Download the PureScript 0.12.0 source
  Error: EACCES: permission denied, mkdtemp '/usr/lib/node_modules/purescript/node-purescript-QA11jY'
▬ Ensure the appropriate GHC is installed
▬ Build a binary from source
▬ Save the built binary to the cache directory

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! purescript@0.12.0 postinstall: `install-purescript --purs-ver=0.12.0 .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the purescript@0.12.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-06-20T01_08_17_775Z-debug.log
```

I'm running Arch Linux x86_64 with kernel 4.16.13.2.

**Comment by YuriyKartuzov** [comment]
I had the same error, and it was fixed without running sudo command (npm install -g electron --unsafe-perm=true --allow-root) by properly specifying a path to an existing directory. So `mkdir` command does not need to be run.
(Error: EACCES: permission denied, mkdir ...)

**Comment by devlargs** [comment]
Thank you very much @ander7agar

**Comment by ErvalhouS** [comment]
Stop using npm for it and use `yarn global add electron` which works and is a npm wrapper that avoids unsafe sudo usage. If you are confused about it, checkout the [migration guide](https://yarnpkg.com/en/docs/migrating-from-npm)

**Comment by LaxmishJoshi** [comment]
In my case, error was with installing node-sass which in turn was a dependency of gulp-sass@3.9.1.
 
I upgraded gulp-sass to 4.0.0, with that gulp-sass pulled node-sass@4.9.2. 
With that "npm install" in my project base worked fine without errors.

Node: 10.6.0
NPM: 6.1.0
Environment: Ubuntu 16.04

I still feel, using "unsafe-perm=true " (as mentioned in above comments) is NOT a great idea. It can be very good workaround. But not a solution for the issue.

**Comment by DanielRuf** [comment]
> npm wrapper that avoids unsafe sudo usage

Not directly. it uses the npmjs registry behind its own domain name (proxy). The rest is yarn =)
