### ISSUE TITLE
Unhandled rejection Error: Argument #2: Expected string but got null - at addDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:515:3)

### ISSUE THREAD

**Issue by amurchick** [npm/npm#17284]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

```
$ sudo npm uninstall -g ember-cli                                                                                           
Unhandled rejection Error: Argument #2: Expected string but got null homedir-polyfill@^1.0.0 fetched in 194ms
    at addDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:515:3)         
    at /usr/local/lib/node_modules/npm/lib/install/deps.js:463:5                         
    at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35         
    at Array.forEach (native)               
    at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11         
    at Array.forEach (native)               
    at asyncMap (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)                                                                                        
    at loadDeps (/usr/local/lib/node_modules/npm/lib/install/deps.js:455:3)              
    at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)                                                                              
    at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)      
    at /usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7              
    at /usr/local/lib/node_modules/npm/lib/install/and-finish-tracker.js:8:8             
    at resolveBranchDeps.then (/usr/local/lib/node_modules/npm/lib/install/deps.js:419:11)                                                                                        
    at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)                                                                                
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)                                                     
    at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)                                                                

npm ERR! cb() never called!                 

npm ERR! This is an error with npm itself. Please report this error at:                  
npm ERR!     <https://github.com/npm/npm/issues>                                         

npm ERR! A complete log of this run can be found in:                                     
npm ERR!     /Users/amur/.npm/_logs/2017-06-18T08_52_29_602Z-debug.log       
```

Debug log: https://gist.github.com/amurchick/b58eb9bbadb5a0214034ad3c3ed4d72c
#### How can the CLI team reproduce the problem?

sudo npm uninstall -g ember-cli     

### supporting information:

 - `npm -v` prints: 5.0.3
 - `node -v` prints: 8.1.2
 - `npm config get registry` prints: https://registry.npmjs.org/ 
 - Windows, OS X/macOS, or Linux?: macOs 10.12.5
 - Network issues:
   - Geographic location where npm was run: Thailand/3BB internet provider
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by arabindadora** [comment]
I see the same problem when upgraded to npm 5.0.3 on node v6.10.2.

**Comment by vivalet** [comment]
I have the same issue

`npm -g uninstall yo;npm install -g yo@latest`

resulted in:
```
Unhandled rejection Error: Argument #2: Expected string but got nullinstall loadIdealTree
    at addDependency (/Users/vivalet/.node/lib/node_modules/npm/lib/install/deps.js:515:3)
    at /Users/vivalet/.node/lib/node_modules/npm/lib/install/deps.js:463:5
    at /Users/vivalet/.node/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
    at Array.forEach (native)
    at /Users/vivalet/.node/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
    at Array.forEach (native)
    at asyncMap (/Users/vivalet/.node/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
    at loadDeps (/Users/vivalet/.node/lib/node_modules/npm/lib/install/deps.js:455:3)
    at Array.<anonymous> (/Users/vivalet/.node/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
    at LOOP (/Users/vivalet/.node/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
    at /Users/vivalet/.node/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
    at /Users/vivalet/.node/lib/node_modules/npm/lib/install/and-finish-tracker.js:8:8
    at resolveBranchDeps.then (/Users/vivalet/.node/lib/node_modules/npm/lib/install/deps.js:419:11)
    at tryCatcher (/Users/vivalet/.node/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/vivalet/.node/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/vivalet/.node/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/vivalet/.npm/_logs/2017-06-23T17_32_38_691Z-debug.log
/Users/vivalet/.node/bin/yo -> /Users/vivalet/.node/lib/node_modules/yo/lib/cli.js
/Users/vivalet/.node/bin/yo-complete -> /Users/vivalet/.node/lib/node_modules/yo/lib/completion/index.js

> yo@2.0.0 postinstall /Users/vivalet/.node/lib/node_modules/yo
> yodoctor


Yeoman Doctor
Running sanity checks on your system

✔ Global configuration file is valid
✔ NODE_PATH matches the npm root
✔ Node.js version
✔ No .bowerrc file in home directory
✔ No .yo-rc.json file in home directory
✔ npm version

Everything looks all right!

> spawn-sync@1.0.15 postinstall /Users/vivalet/.node/lib/node_modules/yo/node_modules/spawn-sync
> node postinstall

+ yo@2.0.0
added 99 packages, removed 39 packages and updated 263 packages in 36.255s
```

log file:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/8.1.2/bin/node',
1 verbose cli   '/Users/vivalet/.node/bin/npm',
1 verbose cli   '-g',
1 verbose cli   'uninstall',
1 verbose cli   'yo' ]
2 info using npm@5.0.3
3 info using node@v8.1.2
4 verbose npm-session ec91424c0104e2b6
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly install loadIdealTree
8 silly install cloneCurrentTreeToIdealTree
9 silly install loadShrinkwrap
10 silly uninstall loadAllDepsIntoIdealTree
11 silly install loadAllDepsIntoIdealTree
12 error cb() never called!
13 error This is an error with npm itself. Please report this error at:
14 error <https://github.com/npm/npm/issues>

**Comment by jameswpm** [comment]
I was having the same issue after install [vue-cli](https://vue-loader.vuejs.org/en/start/setup.html).

Following the site instructions, the installation itself ran correctly, but when i tried the `npm install` inside my project directory, I received a similar error.

I don't know the reason and i don't know the drawbacks for your project, but `sudo npm cache clean --force` helped me and maybe could help you on this problem, if you not tried it yet.

 - node 8.0.0
 - npm 5.0.3
 - Ubuntu 16

**Comment by GaryB432** [comment]
`npm cache clean --force` did not fix it for me

trying to uninstall at-sign-angular/cli

- node 8.1.2
- npm 5.0.3
- Windows 10

**Comment by timothepearce** [comment]
Same problem when I try to uninstall globally `gulp`
- `node` 8.1.3
- `npm` 5.0.4
- macOS Sierra

**Comment by cho-cloud-cloud** [comment]
Same issue:

- Ubuntu 16.04
- nodejs 8.1.3
- npm 5.0.3

```
Unhandled rejection Error: Argument #2: Expected string but got nullinstall loadIdealTree
    at addDependency (/usr/lib/node_modules/npm/lib/install/deps.js:515:3)
    at /usr/lib/node_modules/npm/lib/install/deps.js:463:5
    at /usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
    at Array.forEach (native)
    at /usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
    at Array.forEach (native)
    at asyncMap (/usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
    at loadDeps (/usr/lib/node_modules/npm/lib/install/deps.js:455:3)
    at Array.<anonymous> (/usr/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
    at LOOP (/usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
    at /usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
    at /usr/lib/node_modules/npm/lib/install/and-finish-tracker.js:8:8
    at resolveBranchDeps.then (/usr/lib/node_modules/npm/lib/install/deps.js:419:11)
    at tryCatcher (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-07-07T03_07_01_913Z-debug.log
```

**Comment by mreyes819** [comment]
Debug Log: 
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'install' ]
2 info using npm@5.0.3
3 info using node@v6.10.3
4 verbose config Skipping project config: /Users/mttrys/.npmrc. (matches userconfig)
5 verbose npm-session 0c43c07475ad34a4
6 silly install runPreinstallTopLevelLifecycles
7 silly install loadCurrentTree
8 silly install readLocalPackageData
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 silly install loadShrinkwrap
12 silly install loadAllDepsIntoIdealTree
13 http fetch GET 200 https://registry.npmjs.org/adm-zip 40ms (from cache)
14 http fetch GET 200 https://registry.npmjs.org/bignumber.js 36ms (from cache)
15 http fetch GET 200 https://registry.npmjs.org/brace-expansion 37ms (from cache)
16 http fetch GET 200 https://registry.npmjs.org/concat-map 36ms (from cache)
17 http fetch GET 200 https://registry.npmjs.org/core-util-is 36ms (from cache)
18 http fetch GET 200 https://registry.npmjs.org/fs.realpath 36ms (from cache)
19 http fetch GET 200 https://registry.npmjs.org/glob 38ms (from cache)
20 http fetch GET 200 https://registry.npmjs.org/inflight 37ms (from cache)
21 http fetch GET 200 https://registry.npmjs.org/inherits 37ms (from cache)
22 http fetch GET 200 https://registry.npmjs.org/balanced-match 42ms (from cache)
23 silly pacote tag manifest for adm-zip@latest fetched in 63ms
24 silly pacote tag manifest for bignumber.js@latest fetched in 45ms
25 silly pacote tag manifest for brace-expansion@latest fetched in 45ms
26 silly pacote tag manifest for concat-map@latest fetched in 45ms
27 silly pacote tag manifest for core-util-is@latest fetched in 48ms
28 silly pacote tag manifest for fs.realpath@latest fetched in 49ms
29 silly pacote tag manifest for glob@latest fetched in 49ms
30 silly pacote tag manifest for inflight@latest fetched in 48ms
31 silly pacote tag manifest for inherits@latest fetched in 47ms
32 silly pacote tag manifest for balanced-match@latest fetched in 53ms
33 http fetch GET 200 https://registry.npmjs.org/isarray 28ms (from cache)
34 http fetch GET 200 https://registry.npmjs.org/lodash 28ms (from cache)
35 http fetch GET 200 https://registry.npmjs.org/minimatch 28ms (from cache)
36 http fetch GET 200 https://registry.npmjs.org/once 26ms (from cache)
37 http fetch GET 200 https://registry.npmjs.org/os-tmpdir 26ms (from cache)
38 http fetch GET 200 https://registry.npmjs.org/path-is-absolute 26ms (from cache)
39 http fetch GET 200 https://registry.npmjs.org/rimraf 22ms (from cache)
40 http fetch GET 200 https://registry.npmjs.org/readable-stream 26ms (from cache)
41 http fetch GET 200 https://registry.npmjs.org/sax 23ms (from cache)
42 http fetch GET 200 https://registry.npmjs.org/sqlstring 23ms (from cache)
43 silly pacote tag manifest for isarray@latest fetched in 35ms
44 warn deprecated isarray@2.0.1: Just use Array.isArray directly
45 silly pacote tag manifest for lodash@latest fetched in 36ms
46 silly pacote tag manifest for minimatch@latest fetched in 36ms
47 silly pacote tag manifest for once@latest fetched in 34ms
48 silly pacote tag manifest for os-tmpdir@latest fetched in 35ms
49 silly pacote tag manifest for path-is-absolute@latest fetched in 36ms
50 silly pacote tag manifest for rimraf@latest fetched in 31ms
51 silly pacote tag manifest for readable-stream@latest fetched in 36ms
52 silly pacote tag manifest for sax@latest fetched in 33ms
53 silly pacote tag manifest for sqlstring@latest fetched in 34ms
54 silly pacote range manifest for isarray@~1.0.0 fetched in 9ms
55 http fetch GET 200 https://registry.npmjs.org/string_decoder 29ms (from cache)
56 http fetch GET 200 https://registry.npmjs.org/tmp 29ms (from cache)
57 http fetch GET 200 https://registry.npmjs.org/wrappy 28ms (from cache)
58 http fetch GET 200 https://registry.npmjs.org/xml2js 28ms (from cache)
59 http fetch GET 200 https://registry.npmjs.org/xmlbuilder 28ms (from cache)
60 http fetch GET 200 https://registry.npmjs.org/process-nextick-args 20ms (from cache)
61 http fetch GET 200 https://registry.npmjs.org/safe-buffer 20ms (from cache)
62 http fetch GET 200 https://registry.npmjs.org/util-deprecate 20ms (from cache)
63 http fetch GET 200 https://registry.npmjs.org/string_decoder 20ms (from cache)
64 silly pacote tag manifest for string_decoder@latest fetched in 35ms
65 silly pacote tag manifest for tmp@latest fetched in 34ms
66 silly pacote tag manifest for wrappy@latest fetched in 35ms
67 silly pacote tag manifest for xml2js@latest fetched in 35ms
68 silly pacote tag manifest for xmlbuilder@latest fetched in 35ms
69 silly pacote range manifest for process-nextick-args@~1.0.6 fetched in 25ms
70 silly pacote range manifest for safe-buffer@~5.1.1 fetched in 25ms
71 silly pacote range manifest for util-deprecate@~1.0.1 fetched in 26ms
72 silly pacote range manifest for string_decoder@~1.0.3 fetched in 26ms
73 silly pacote range manifest for safe-buffer@~5.1.0 fetched in 3ms
74 error cb() never called!
75 error This is an error with npm itself. Please report this error at:
76 error <https://github.com/npm/npm/issues>

**Comment by chilloutman** [comment]
Duplicate of #16738.

It will be fixed soon.

(In the meantime you can work around it by re-installing, then uninstalling a package.)
