### ISSUE TITLE
Unhandled rejection Error: Invalid tag name "@angular": Tags may not have any characters that encodeURIComponent encodes.

### ISSUE THREAD

**Issue by DrNotes** [npm/npm#17283]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by DrNotes** [comment]
Unhandled rejection Error: Invalid tag name "@angular": Tags may not have any characters that encodeURIComponent encodes.
    at invalidTagName (C:\Users\Marco\AppData\Roaming\npm\node_modules\npm\node_modules\npm-package-arg\npa.js:76:15)
    at fromRegistry (C:\Users\Marco\AppData\Roaming\npm\node_modules\npm\node_modules\npm-package-arg\npa.js:265:13)
    at resolve (C:\Users\Marco\AppData\Roaming\npm\node_modules\npm\node_modules\npm-package-arg\npa.js:66:12)
    at npa (C:\Users\Marco\AppData\Roaming\npm\node_modules\npm\node_modules\npm-package-arg\npa.js:39:10)
    at C:\Users\Marco\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:200:16
    at C:\Users\Marco\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:52:35
    at Array.forEach (native)
    at C:\Users\Marco\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:52:11
    at Array.forEach (native)
    at asyncMap (C:\Users\Marco\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:51:8)
    at exports.getAllMetadata (C:\Users\Marco\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:199:3)
    at Object.Installer.loadArgMetadata (C:\Users\Marco\AppData\Roaming\npm\node_modules\npm\lib\install.js:325:3)
    at C:\Users\Marco\AppData\Roaming\npm\node_modules\npm\lib\install.js:648:16
    at BB.join.then (C:\Users\Marco\AppData\Roaming\npm\node_modules\npm\lib\install\read-shrinkwrap.js:41:16)
    at tryCatcher (C:\Users\Marco\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Marco\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Marco\AppData\Roaming\npm-cache\_logs\2017-06-18T07_45_56_590Z-debug.log

**Comment by DrNotes** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Marco\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '@angular' ]
2 info using npm@5.0.3
3 info using node@v6.11.0
4 verbose npm-session 0733798415668d01
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 error cb() never called!
8 error This is an error with npm itself. Please report this error at:
9 error <https://github.com/npm/npm/issues>
