### ISSUE TITLE
cb() never called

### ISSUE THREAD

**Issue by joostdelange** [npm/npm#17291]
```
Unhandled rejection Error: Invalid tag name "[-g]": Tags may not have any characters that encodeURIComponent encodes.
    at invalidTagName (C:\Users\joost\AppData\Roaming\npm\node_modules\npm\node_modules\npm-package-arg\npa.js:76:15)
    at fromRegistry (C:\Users\joost\AppData\Roaming\npm\node_modules\npm\node_modules\npm-package-arg\npa.js:265:13)
    at resolve (C:\Users\joost\AppData\Roaming\npm\node_modules\npm\node_modules\npm-package-arg\npa.js:66:12)
    at npa (C:\Users\joost\AppData\Roaming\npm\node_modules\npm\node_modules\npm-package-arg\npa.js:39:10)
    at C:\Users\joost\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:200:16
    at C:\Users\joost\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:52:35
    at Array.forEach (native)
    at C:\Users\joost\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:52:11
    at Array.forEach (native)
    at asyncMap (C:\Users\joost\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:51:8)
    at exports.getAllMetadata (C:\Users\joost\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:199:3)
    at Object.Installer.loadArgMetadata (C:\Users\joost\AppData\Roaming\npm\node_modules\npm\lib\install.js:325:3)
    at C:\Users\joost\AppData\Roaming\npm\node_modules\npm\lib\install.js:648:16
    at BB.join.then (C:\Users\joost\AppData\Roaming\npm\node_modules\npm\lib\install\read-shrinkwrap.js:41:16)
    at tryCatcher (C:\Users\joost\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\joost\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\joost\AppData\Roaming\npm-cache\_logs\2017-06-18T14_03_38_436Z-debug.log
```

**Comment by AurelienC** [comment]
Same error #17222
