### ISSUE TITLE
Intermittent EPERM issues when renaming Windows files during install (reopen #12059)

### ISSUE THREAD

**Issue by dogboydog** [npm/npm#17321]
This issue was automatically closed: https://github.com/npm/npm/issues/12059

I don't think this should be closed.  This is still an issue my colleagues and I encounter every day. Sometimes we have to blow away an entire node_modules directory for a project and/or install many times to get it to work. 

@legodude17 suggested the troubleshooting guide, but the guide for the EPERM issue only has  commands that are not applicable to Windows.

**Comment by ms-deregtd** [comment]
Still get this every day using npm 5.0.3.  I'm up to my 18th run of npm install trying to bring up a fresh repository on this computer.  Gets a little further every time, but always craps out on a DELETE or a RENAME operation.

**Comment by b-barthel** [comment]
@ms-deregtd, @dogboydog  We ran into a similar issue integrating npm v5.0.3 and traced it to a couple of packages with large numbers of bundled dependencies..  For some reason those dependencies had been shrinkwrapped with resolved urls referencing the registry.  We removed those urls and integrity hashes and marked them as "bundled: true" and that has fixed the issue for us.  I unfortunately haven't had time to dig in further, but we haven't seen a recurrence since.

**Comment by dogboydog** [comment]
I had to make a script the other day that looped "npm install -g (a package)" until it would work. It took over a half an hour to succeed. No fun : (  It's always these EPERM issues with these files named like `.DELETE` or `.RENAME`. 

@b-barthel  How did you edit the dependencies you required to remove these  URLS?  I encounter this issue installing my packages and those of other people, so I wouldn't think I have control over editing URLs in their packages at that point, but I'm probably missing something

**Comment by dogboydog** [comment]
I'm just going to comment again to prevent this from being automatically closed.   I've had to use my infinite npm install -g loop  since I opened this issue to get my packages installed. Hopefully someone can look into this and make npm recover from being unable to delete. 


```
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\xxx\AppData\Roaming\npm\node_modules\xxx' -> 'C:\Users\xxx\AppData\Roaming\npm\node_modules\.xxx.DELETE'
npm ERR!     at moveAway (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:38:5)
npm ERR!     at destStatted (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:27:7)
npm ERR!     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:267:18
npm ERR!     at FSReqWrap.oncomplete (fs.js:123:15)
npm ERR!
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\xxx\AppData\Roaming\npm\node_modules\xxx' -> 'C:\Users\xxx\AppData\Roaming\npm\node_modules\.xxx.DELETE'
npm ERR!     at Error (native)
npm ERR!  Error: EPERM: operation not permitted, rename 'C:\Users\xxx\AppData\Roaming\npm\node_modules\xxx' -> 'C:\Users\xxx\AppData\Roaming\npm\node_modules\.xxx.DELETE'
npm ERR!     at moveAway (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:38:5)
npm ERR!     at destStatted (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:27:7)
npm ERR!     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:267:18
npm ERR!     at FSReqWrap.oncomplete (fs.js:123:15)
npm ERR!
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\xxx\AppData\Roaming\npm\node_modules\xxx' -> 'C:\Users\xxx\AppData\Roaming\npm\node_modules\.xxx.DELETE'
npm ERR!     at Error (native)
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\nodejs\xxx\npm-debug.log
no

> typechecker@2.0.8 preinstall C:\Users\xxx\AppData\Roaming\npm\node_modules\.staging\typechecker-006bf9be
> node ./cyclic.js


> typechecker@2.0.8 preinstall C:\Users\xxx\AppData\Roaming\npm\node_modules\.staging\typechecker-bb1038a3
> node ./cyclic.js
```
