### ISSUE TITLE
Installation of SASS - npm ERR! Windows_NT 10.0.14393

### ISSUE THREAD

**Issue by VladTzaru** [npm/npm#17367]
Hello, I'm trying to install SASS, npm version is 3.10.10, but when I ran the command I get the following error:

> npm ERR! Windows_NT 10.0.14393
> npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "node-sass" "--global"
> npm ERR! node v6.11.0
> npm ERR! npm  v3.10.10
> npm ERR! code EPROTO
> npm ERR! errno EPROTO
> npm ERR! syscall write
> 
> npm ERR! write EPROTO 101057795:error:140943FC:SSL routines:ssl3_read_bytes:sslv3 alert bad record mac:openssl\ssl\s3_pkt.c:1493:SSL alert number 20
> npm ERR! 101057795:error:1409E0E5:SSL routines:ssl3_write_bytes:ssl handshake failure:openssl\ssl\s3_pkt.c:659:
> npm ERR!
> npm ERR!
> npm ERR! If you need help, you may report this error at:
> npm ERR!     <https://github.com/npm/npm/issues>
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     C:\Program Files\nodejs\npm-debug.log

DEBUG LOG:

> 0 info it worked if it ends with ok
> 1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
> 1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
> 1 verbose cli   'install',
> 1 verbose cli   'node-sass',
> 1 verbose cli   '-g' ]
> 2 info using npm@3.10.10
> 3 info using node@v6.11.0
> 4 silly loadCurrentTree Starting
> 5 silly install loadCurrentTree
> 6 silly install readGlobalPackageData
> 7 silly fetchPackageMetaData node-sass
> 8 silly fetchNamedPackageData node-sass
> 9 silly mapToRegistry name node-sass
> 10 silly mapToRegistry using default registry
> 11 silly mapToRegistry registry https://registry.npmjs.org/
> 12 silly mapToRegistry data Result {
> 12 silly mapToRegistry   raw: 'node-sass',
> 12 silly mapToRegistry   scope: null,
> 12 silly mapToRegistry   escapedName: 'node-sass',
> 12 silly mapToRegistry   name: 'node-sass',
> 12 silly mapToRegistry   rawSpec: '',
> 12 silly mapToRegistry   spec: 'latest',
> 12 silly mapToRegistry   type: 'tag' }
> 13 silly mapToRegistry uri https://registry.npmjs.org/node-sass
> 14 verbose request uri https://registry.npmjs.org/node-sass
> 15 verbose request no auth needed
> 16 info attempt registry request try #1 at 8:22:59 PM
> 17 verbose request id 861818fc299dee69
> 18 http request GET https://registry.npmjs.org/node-sass
> 19 info retry will retry, error on last attempt: Error: write EPROTO 101057795:error:140943FC:SSL routines:ssl3_read_bytes:sslv3 alert bad record mac:openssl\ssl\s3_pkt.c:1493:SSL alert number 20
> 19 info retry 101057795:error:1409E0E5:SSL routines:ssl3_write_bytes:ssl handshake failure:openssl\ssl\s3_pkt.c:659:
> 20 info attempt registry request try #2 at 8:23:10 PM
> 21 http request GET https://registry.npmjs.org/node-sass
> 22 info retry will retry, error on last attempt: Error: write EPROTO 101057795:error:140943FC:SSL routines:ssl3_read_bytes:sslv3 alert bad record mac:openssl\ssl\s3_pkt.c:1493:SSL alert number 20
> 22 info retry 101057795:error:1409E0E5:SSL routines:ssl3_write_bytes:ssl handshake failure:openssl\ssl\s3_pkt.c:659:
> 23 info attempt registry request try #3 at 8:24:10 PM
> 24 http request GET https://registry.npmjs.org/node-sass
> 25 silly fetchPackageMetaData Error: write EPROTO 101057795:error:140943FC:SSL routines:ssl3_read_bytes:sslv3 alert bad record mac:openssl\ssl\s3_pkt.c:1493:SSL alert number 20
> 25 silly fetchPackageMetaData 101057795:error:1409E0E5:SSL routines:ssl3_write_bytes:ssl handshake failure:openssl\ssl\s3_pkt.c:659:
> 25 silly fetchPackageMetaData
> 25 silly fetchPackageMetaData     at exports._errnoException (util.js:1018:11)
> 25 silly fetchPackageMetaData     at WriteWrap.afterWrite (net.js:800:14)
> 25 silly fetchPackageMetaData  error for node-sass { Error: write EPROTO 101057795:error:140943FC:SSL routines:ssl3_read_bytes:sslv3 alert bad record mac:openssl\ssl\s3_pkt.c:1493:SSL alert number 20
> 25 silly fetchPackageMetaData 101057795:error:1409E0E5:SSL routines:ssl3_write_bytes:ssl handshake failure:openssl\ssl\s3_pkt.c:659:
> 25 silly fetchPackageMetaData
> 25 silly fetchPackageMetaData     at exports._errnoException (util.js:1018:11)
> 25 silly fetchPackageMetaData     at WriteWrap.afterWrite (net.js:800:14) code: 'EPROTO', errno: 'EPROTO', syscall: 'write' }
> 26 silly rollbackFailedOptional Starting
> 27 silly rollbackFailedOptional Finishing
> 28 silly runTopLevelLifecycles Finishing
> 29 silly install printInstalled
> 30 verbose stack Error: write EPROTO 101057795:error:140943FC:SSL routines:ssl3_read_bytes:sslv3 alert bad record mac:openssl\ssl\s3_pkt.c:1493:SSL alert number 20
> 30 verbose stack 101057795:error:1409E0E5:SSL routines:ssl3_write_bytes:ssl handshake failure:openssl\ssl\s3_pkt.c:659:
> 30 verbose stack
> 30 verbose stack     at exports._errnoException (util.js:1018:11)
> 30 verbose stack     at WriteWrap.afterWrite (net.js:800:14)
> 31 verbose cwd C:\Users\Vladimir
> 32 error Windows_NT 10.0.14393
> 33 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "node-sass" "-g"
> 34 error node v6.11.0
> 35 error npm  v3.10.10
> 36 error code EPROTO
> 37 error errno EPROTO
> 38 error syscall write
> 39 error write EPROTO 101057795:error:140943FC:SSL routines:ssl3_read_bytes:sslv3 alert bad record mac:openssl\ssl\s3_pkt.c:1493:SSL alert number 20
> 39 error 101057795:error:1409E0E5:SSL routines:ssl3_write_bytes:ssl handshake failure:openssl\ssl\s3_pkt.c:659:
> 40 error If you need help, you may report this error at:
> 40 error     <https://github.com/npm/npm/issues>
> 41 verbose exit [ 1, true ]

Gist: https://gist.github.com/VladTzaru/f20222b00e4d0475ee526332aba08235

Any help would be highly appreciated. Thanks in advance.

**Comment by VladTzaru** [comment]
Needed to download the latest version (who knew, face palm).
