### ISSUE TITLE
When i start the NPM we got the below errors

### ISSUE THREAD

**Issue by krpmurugan** [npm/npm#17364]
> ng2-fundamentals-demo@1.0.0 start C:\dev\ng2-fundamentals
> tsc && concurrently "npm run tsc:w" "npm run server"

 Error occured when executing command: npm run tsc:w
 Error: Unable to detect platform shell type. Please set SHELL_EXECUTE_FLAGS env variable.
     at detectExecuteFlags (C:\dev\ng2-fundamentals\node_modules\concurrently\node_modules\spawn-default-shell\src\get-shell.js:29:9)
     at getShell (C:\dev\ng2-fundamentals\node_modules\concurrently\node_modules\spawn-default-shell\src\get-shell.js:37:19)
     at Object.spawn (C:\dev\ng2-fundamentals\node_modules\concurrently\node_modules\spawn-default-shell\src\index.js:5:24)
     at C:\dev\ng2-fundamentals\node_modules\concurrently\src\main.js:195:34
     at arrayMap (C:\dev\ng2-fundamentals\node_modules\concurrently\node_modules\lodash\lodash.js:660:23)
     at Function.map (C:\dev\ng2-fundamentals\node_modules\concurrently\node_modules\lodash\lodash.js:9571:14)
     at run (C:\dev\ng2-fundamentals\node_modules\concurrently\src\main.js:181:22)
     at main (C:\dev\ng2-fundamentals\node_modules\concurrently\src\main.js:61:5)
     at Object.<anonymous> (C:\dev\ng2-fundamentals\node_modules\concurrently\src\main.js:424:1)
     at Module._compile (module.js:570:32)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\node\\nodejs\\node.exe" "C:\\Program Files\\node\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! ng2-fundamentals-demo@1.0.0 start: `tsc && concurrently "npm run tsc:w" "npm run server" `
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ng2-fundamentals-demo@1.0.0 start script 'tsc && concurrently "npm run tsc:w" "npm run server" '.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ng2-fundamentals-demo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc && concurrently "npm run tsc:w" "npm run server"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ng2-fundamentals-demo
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ng2-fundamentals-demo
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\dev\ng2-fundamentals\npm-debug.log

**Comment by kenany** [comment]
Log indicates that this is coming from `concurrently`, not `npm` itself:

```
Error occured when executing command: npm run tsc:w
Error: Unable to detect platform shell type. Please set SHELL_EXECUTE_FLAGS env variable.
at detectExecuteFlags (C:\dev\ng2-fundamentals\node_modules\concurrently\node_modules\spawn-default-shell\src\get-shell.js:29:9)
```
