### ISSUE TITLE
npm ERR! cb() never called!

### ISSUE THREAD

**Issue by yanyanforest** [npm/npm#17378]
Unhandled rejection RangeError: Maximum call stack size exceededeinstall: no script for preinstall, continuing
    at exports.create (/usr/local/lib/node_modules/cnpm/node_modules/npm/lib/install/node.js:31:40)
    at /usr/local/lib/node_modules/cnpm/node_modules/npm/lib/install/node.js:36:14
    at Array.forEach (native)
    at exports.create (/usr/local/lib/node_modules/cnpm/node_modules/npm/lib/install/node.js:33:25)
    at /usr/local/lib/node_modules/cnpm/node_modules/npm/lib/install/node.js:36:14
    at Array.forEach (native)
    at exports.create (/usr/local/lib/node_modules/cnpm/node_modules/npm/lib/install/node.js:33:25)
    at normalizeTree (/usr/local/lib/node_modules/cnpm/node_modules/npm/lib/install.js:377:5)
    at Array.forEach (native)
    at normalizeTree (/usr/local/lib/node_modules/cnpm/node_modules/npm/lib/install.js:379:19)
    at Array.forEach (native)
    at normalizeTree (/usr/local/lib/node_modules/cnpm/node_modules/npm/lib/install.js:379:19)
    at Array.forEach (native)
    at normalizeTree (/usr/local/lib/node_modules/cnpm/node_modules/npm/lib/install.js:379:19)
    at Array.forEach (native)
    at normalizeTree (/usr/local/lib/node_modules/cnpm/node_modules/npm/lib/install.js:379:19)

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by martijnpolak** [comment]
I have the same issue with NPM 5.0.3, Node 6.9.1, Ubuntu 16.04.

```
Unhandled rejection RangeError: Maximum call stack size exceededpreinstall: no script for preinstall, continuing
    at RegExp.exec (native)
    at RegExp.test (native)
    at /usr/lib/node_modules/npm/node_modules/aproba/index.js:38:16
    at Array.forEach (native)
    at module.exports (/usr/lib/node_modules/npm/node_modules/aproba/index.js:33:11)
    at flatNameFromTree (/usr/lib/node_modules/npm/lib/install/flatten-tree.js:37:3)
    at flatNameFromTree (/usr/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-06-22T15_27_35_749Z-debug.log
```

Logfile says:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'install' ]
2 info using npm@5.0.3
3 info using node@v6.9.1
4 verbose npm-session b68ab154d9a76bf7
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall cha@1.0.0
7 info lifecycle cha@1.0.0~preinstall: cha@1.0.0
8 silly lifecycle cha@1.0.0~preinstall: no script for preinstall, continuing
9 silly install loadCurrentTree
10 silly install readLocalPackageData
11 error cb() never called!
12 error This is an error with npm itself. Please report this error at:
13 error <https://github.com/npm/npm/issues>
```

**Comment by 9034725985** [comment]
Same here 

```
# npm uninstall -g @angular/cli
Unhandled rejection Error: Argument #2: Expected string but got nullc0fdfdf2f04f
    at addDependency (/usr/lib/node_modules/npm/lib/install/deps.js:515:3)
    at /usr/lib/node_modules/npm/lib/install/deps.js:463:5
    at /usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
    at Array.forEach (native)
    at /usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
    at Array.forEach (native)
    at asyncMap (/usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
    at loadDeps (/usr/lib/node_modules/npm/lib/install/deps.js:455:3)
    at Array.<anonymous> (/usr/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
    at LOOP (/usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
    at /usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
    at /usr/lib/node_modules/npm/lib/install/and-finish-tracker.js:8:8
    at resolveBranchDeps.then (/usr/lib/node_modules/npm/lib/install/deps.js:419:11)
    at tryCatcher (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-06-23T01_23_06_120Z-debug.log
```

```
$ npm uninstall -g @angular/cli
Unhandled rejection Error: Argument #2: Expected string but got nullee7414531f66
    at addDependency (/usr/lib/node_modules/npm/lib/install/deps.js:515:3)
    at /usr/lib/node_modules/npm/lib/install/deps.js:463:5
    at /usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
    at Array.forEach (native)
    at /usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
    at Array.forEach (native)
    at asyncMap (/usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
    at loadDeps (/usr/lib/node_modules/npm/lib/install/deps.js:455:3)
    at Array.<anonymous> (/usr/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
    at LOOP (/usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
    at /usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
    at /usr/lib/node_modules/npm/lib/install/and-finish-tracker.js:8:8
    at resolveBranchDeps.then (/usr/lib/node_modules/npm/lib/install/deps.js:419:11)
    at tryCatcher (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kus/.npm/_logs/2017-06-23T01_24_08_100Z-debug.log
```

**Comment by suprsidr** [comment]
Same here node 6.10.3 npm 5.0.3 | node 8.1.2 npm 5.0.3
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at...
[2017-06-23T11_18_16_376Z-debug.log.txt](https://github.com/npm/npm/files/1097609/2017-06-23T11_18_16_376Z-debug.log.txt)

**Comment by AurelienC** [comment]
Same error #17222
