### ISSUE TITLE
Error: Cannot find module 'util-deprecate'

### ISSUE THREAD

**Issue by NN---** [npm/npm#17393]
#### I'm opening this issue because:

  - [X] npm is crashing.

#### What's going wrong?
Running npm outdated produces:

```
npm outdated
module.js:487
    throw err;
    ^

Error: Cannot find module 'util-deprecate'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (node_modules\readable-stream\lib\_stream_writable.js:30:14)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
module.js:487
    throw err;
    ^
```

#### How can the CLI team reproduce the problem?
Just run npm outdated with npm 5.0.3

Running "npm outdated --depth=0" works as expected.

**Comment by stevewinni-cc** [comment]
We are seeing this too. on running standard npm gulp install.

Node: v8.0.0
NPM: 5.0.3

**Comment by NN---** [comment]
You should upgrade to Node 8.1
