### ISSUE TITLE
npm cannot install saas-loader

### ISSUE THREAD

**Issue by spulikonda** [npm/npm#17399]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by spulikonda** [comment]
We recently had some plugin updates for our Jenkins system and apparently the new version of nodejs and npm were not working so had to downgrade to lower version however couldn't downgrade nodejs to 5.x and getting some errors with saas-loader when we use our standard scripts to perform some updates
Debug log details
===========
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'install', 'saas-loader' ]
2 info using npm@3.5.2
3 info using node@v8.1.2
4 verbose config Skipping project config: /root/.npmrc. (matches userconfig)
5 verbose stack Error: Cannot find module 'internal/fs'
5 verbose stack     at Function.Module._resolveFilename (module.js:485:15)
5 verbose stack     at Function.Module._load (module.js:437:25)
5 verbose stack     at Module.require (module.js:513:17)
5 verbose stack     at require (internal/module.js:11:18)
5 verbose stack     at evalmachine.<anonymous>:40:20
5 verbose stack     at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/cmd-shim/node_modules/graceful-fs/fs.js:11:1)
5 verbose stack     at Module._compile (module.js:569:30)
5 verbose stack     at Object.Module._extensions..js (module.js:580:10)
5 verbose stack     at Module.load (module.js:503:32)
5 verbose stack     at tryModuleLoad (module.js:466:12)
6 verbose cwd /root
7 error Linux 4.4.0-81-generic
8 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "saas-loader"
9 error node v8.1.2
10 error npm  v3.5.2
11 error code MODULE_NOT_FOUND
12 error Cannot find module 'internal/fs'
13 error If you need help, you may report this error at:
13 error     <https://github.com/npm/npm/issues>
14 verbose exit [ 1, true ]

Error when we run our process
====================
22:31:29 + npm install sass-loader
22:31:29 npm ERR! Linux 4.4.0-81-generic
22:31:29 npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "sass-loader"
22:31:29 npm ERR! node v8.1.2
22:31:29 npm ERR! npm  v3.5.2
22:31:29 npm ERR! code MODULE_NOT_FOUND
22:31:29 
22:31:29 npm ERR! Cannot find module 'internal/fs'
22:31:29 npm ERR! 
22:31:29 npm ERR! If you need help, you may report this error at:
22:31:29 npm ERR!     <https://github.com/npm/npm/issues>
22:31:29 
22:31:29 npm ERR! Please include the following file with any support request:

Any help will be appreciated.

**Comment by spulikonda** [comment]
Any help will be appreciated.
