### ISSUE TITLE
Error: EACCES: permission denied, lstat '/home/isse/generator-ruke/typings/index.js'

### ISSUE THREAD

**Issue by alaale123** [npm/npm#17415]
#### I'm opening this issue because:

  -isse@isse-X550LN:~/Music/generator-moon$ yo moon
fs.js:994
  binding.lstat(pathModule._makeLong(path), statValues);
          ^

Error: EACCES: permission denied, lstat '/home/isse/generator-ruke/typings/index.js'
    at Error (native)
    at Object.fs.lstatSync (fs.js:994:11)
    at Object.realpathSync (fs.js:1676:21)
    at Environment.resolver._tryRegistering (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/resolver.js:87:23)
    at Environment.resolver.lookup (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/resolver.js:44:12)
    at init (/usr/local/lib/node_modules/yo/lib/cli.js:117:7)
    at pre (/usr/local/lib/node_modules/yo/lib/cli.js:76:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/yo/lib/cli.js:205:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)

**Comment by AurelienC** [comment]
Do you have the same error if you try to execute `yo moon` with `sudo` ?

**Comment by kenany** [comment]
Doesn't seem like this error is coming from `npm`, but yeah, this looks like a permissions issue.

**Comment by alaale123** [comment]
yes i have same error if i write yo moon

**Comment by alaale123** [comment]
done: i solve my problem
root@isse-X550LN:/home/isse# chmod 777 -R /home/isse/generator-ruke/
root@isse-X550LN:/home/isse# exit
exit
just i remove folder crushed

**Comment by alaale123** [comment]
isse@isse-X550LN:~/Videos/generator-anab$ yo anab
/home/isse/Videos/generator-anab/app/index.js:6
module.exports=generator.base. extends({
                             ^

TypeError: Cannot read property 'extends' of undefined
    at Object.<anonymous> (/home/isse/Videos/generator-anab/app/index.js:6:30)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.get [as anab:app] (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/store.js:38:27)
    at Store.get (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/store.js:61:39)
any one can solve this problem please
