### ISSUE TITLE
Path must be a string. Received undefined

### ISSUE THREAD

**Issue by infusion** [npm/npm#17428]
Hi, 
I just published npm "dhcp" and when installing it globally it works fine when installing it out of the folder. However, when installing it from the npm repo, it fails with:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/8.1.2/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'dhcp' ]
2 info using npm@5.0.3
3 info using node@v8.1.2
4 verbose npm-session 90d60eb7ebb12638
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 304 https://registry.npmjs.org/dhcp 122ms (from cache)
8 silly pacote tag manifest for dhcp@latest fetched in 162ms
9 verbose stack TypeError: Path must be a string. Received undefined
9 verbose stack     at assertPath (path.js:28:11)
9 verbose stack     at Object.relative (path.js:1248:5)
9 verbose stack     at computeVersionSpec (/usr/local/lib/node_modules/npm/lib/install/deps.js:282:27)
9 verbose stack     at Installer.normalizeCurrentTree (/usr/local/lib/node_modules/npm/lib/install.js:370:69)
9 verbose stack     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
9 verbose stack     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
9 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
9 verbose stack     at /usr/local/lib/node_modules/npm/lib/install.js:619:16
9 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/iferr/index.js:13:50
9 verbose stack     at thenHandleErrors (/usr/local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:235:5)
9 verbose stack     at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:25:25)
9 verbose stack     at handleComplete (/usr/local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:22:28)
9 verbose stack     at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:25:25)
9 verbose stack     at handleComplete (/usr/local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:22:28)
9 verbose stack     at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:25:25)
9 verbose stack     at asyncForEach (/usr/local/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:11:31)
10 verbose cwd /Users/robert
11 verbose Darwin 16.6.0
12 verbose argv "/usr/local/Cellar/node/8.1.2/bin/node" "/usr/local/bin/npm" "install" "-g" "dhcp"
13 verbose node v8.1.2
14 verbose npm  v5.0.3
15 error Path must be a string. Received undefined
16 verbose exit [ 1, true ]
```

I guess, it has something to do with the bin directive: https://github.com/infusion/node-dhcp/blob/master/package.json

Could you give me a hint on how to fix this, google wasn't a good friend on this.

Robert

**Comment by infusion** [comment]
Okay, I resolved it myself. I removed the bin-symlinks and removed the package from /usr/local/lib/node_modules myself. I previously installed it locally while developing the package via 

```
npm i . -g
```

When I finally published it, I wanted to override it with

```
npm i dhcp -g
```

... which resulted in the stated error.
