### ISSUE TITLE
This is an error with npm itself. Please report this error

### ISSUE THREAD

**Issue by zhuchaoming** [npm/npm#17436]
```
E:\develop\code\weex\elm>weex run android
 => npm install&build
Unhandled rejection RangeError: Maximum call stack size exceeded
    at exports.create (D:\Program Files\nodejs\node_modules\npm\lib\install\node
.js:33:25)
    at D:\Program Files\nodejs\node_modules\npm\lib\install\node.js:36:14
    at Array.forEach (native)
    at exports.create (D:\Program Files\nodejs\node_modules\npm\lib\install\node
.js:33:25)
    at D:\Program Files\nodejs\node_modules\npm\lib\install\node.js:36:14
    at Array.forEach (native)
    at exports.create (D:\Program Files\nodejs\node_modules\npm\lib\install\node
.js:33:25)
    at normalizeTree (D:\Program Files\nodejs\node_modules\npm\lib\install.js:37
7:5)
    at Array.forEach (native)
    at normalizeTree (D:\Program Files\nodejs\node_modules\npm\lib\install.js:37
9:19)
    at Array.forEach (native)
    at normalizeTree (D:\Program Files\nodejs\node_modules\npm\lib\install.js:37
9:19)
    at Array.forEach (native)
    at normalizeTree (D:\Program Files\nodejs\node_modules\npm\lib\install.js:37
9:19)
    at Array.forEach (native)
    at normalizeTree (D:\Program Files\nodejs\node_modules\npm\lib\install.js:37
9:19)
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

**Comment by AurelienC** [comment]
Same error #17222

**Comment by begin-again** [comment]
Seem to be a lot of these cb() not called issues.

Trying to perform some global uninstalls and a lot of them are failing with this same error. In the case of the debug log below I was trying to uninstall karama-requirejs like with command ` npm remove -g karma-require`. If I tack on the version number as ` npm remove -g karma-require@1.1.0` the error is not produced but the package is not actually removed. In fact I can repeat the command and get the same response `removed 1 package in 0.047s` 

I used [npm-windows-upgrade](https://github.com/felixrieseberg/npm-windows-upgrade) to upgrade to npm v5.0.4 because I was getting the same error on v5.0.1

    0 info it worked if it ends with ok
    1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
    1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
    1 verbose cli   'remove',
    1 verbose cli   '-g',
    1 verbose cli   'karma-requirejs' ]
    2 info using npm@5.0.4
    3 info using node@v7.9.0
    4 verbose npm-session 151076b563849446
    5 silly install loadCurrentTree
    6 silly install readGlobalPackageData
    7 silly install loadIdealTree
    8 silly install cloneCurrentTreeToIdealTree
    9 silly install loadShrinkwrap
    10 silly uninstall loadAllDepsIntoIdealTree
    11 silly install loadAllDepsIntoIdealTree
    12 error cb() never called!
    13 error This is an error with npm itself. Please report this error at:
    14 error <https://github.com/npm/npm/issues>
