### ISSUE TITLE
npm install node_modules@version

### ISSUE THREAD

**Issue by AbhishekRaj123** [npm/npm#17483]
Unhandled rejection Error: Invalid package name "node_modules": node_modules is a blacklisted name
    at invalidPackageName (C:\Users\Abhishek Dubey\AppData\Roaming\npm\node_modules\npm\node_modules\npm-package-arg\npa.js:71:15)
    at Object.Result.setName (C:\Users\Abhishek Dubey\AppData\Roaming\npm\node_modules\npm\node_modules\npm-package-arg\npa.js:107:11)
    at Object.Result (C:\Users\Abhishek Dubey\AppData\Roaming\npm\node_modules\npm\node_modules\npm-package-arg\npa.js:96:23)
    at resolve (C:\Users\Abhishek Dubey\AppData\Roaming\npm\node_modules\npm\node_modules\npm-package-arg\npa.js:45:15)
    at npa (C:\Users\Abhishek Dubey\AppData\Roaming\npm\node_modules\npm\node_modules\npm-package-arg\npa.js:39:10)
    at C:\Users\Abhishek Dubey\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:200:16
    at C:\Users\Abhishek Dubey\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:52:35
    at Array.forEach (native)
    at C:\Users\Abhishek Dubey\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:52:11
    at Array.forEach (native)
    at asyncMap (C:\Users\Abhishek Dubey\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:51:8)
    at exports.getAllMetadata (C:\Users\Abhishek Dubey\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:199:3)
    at Object.Installer.loadArgMetadata (C:\Users\Abhishek Dubey\AppData\Roaming\npm\node_modules\npm\lib\install.js:325:3)
    at C:\Users\Abhishek Dubey\AppData\Roaming\npm\node_modules\npm\lib\install.js:648:16
    at BB.join.then (C:\Users\Abhishek Dubey\AppData\Roaming\npm\node_modules\npm\lib\install\read-shrinkwrap.js:41:16)
    at tryCatcher (C:\Users\Abhishek Dubey\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Abhishek Dubey\AppData\Roaming\npm-cache\_logs\2017-06-28T05_58_52_457Z-debug.log

**Comment by kenany** [comment]
```
Unhandled rejection Error: Invalid package name "node_modules": node_modules is a blacklisted name
```
