### ISSUE TITLE
Unhandled rejection Error: EACCES: permission denied, link '/data/data/com.termux/files/home/.npm/_cacache/tmp/...' -> '/data/data/com.termux/files/home/.npm/_cacache/content-v2/sha512/4f/61/...'

### ISSUE THREAD

**Issue by christianrondeau** [npm/npm#17480]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

Running this (or any global/local package for that matters) using npm `5.0.3` or `5.0.4`:

    npm i -g npm

fails like this:

    > npm i -g npm --verbose
    
    npm info it worked if it ends with ok
    npm verb cli [ '/usr/bin/node',
    npm verb cli   '/data/data/com.termux/files/usr/bin/npm',
    npm verb cli   'i',
    npm verb cli   '-g',
    npm verb cli   'npm',
    npm verb cli   '--verbose' ]
    npm info using npm@5.0.3
    npm info using node@v6.11.0
    npm verb npm-session 3b7ba2a77f7e848c
    Unhandled rejection Error: EACCES: permission denied, link '/home/.npm/_cacache/tmp/6a547224' -> '/home/.npm/_cacache/content-v2/sha512/d8/e0/f8cb9554c1f6f974b32fe943e4df8353fca3cb4843dbeda6fe0d88d14eb91bec5d23ddde1751af76721044d662b479ec4c9df9f0bfcce592bbc9fc2b6f72'
        at Error (native)
    
    npm ERR! cb() never called!
    
    npm ERR! This is an error with npm itself. Please report this error at:
    npm ERR!     <https://github.com/npm/npm/issues>
    
    npm ERR! A complete log of this run can be found in:
    npm ERR!     /home/.npm/_logs/2017-06-28T00_20_47_543Z-debug.log

The only two things included in the log that are not in the message:

    5 silly install loadCurrentTree
    6 silly install readGlobalPackageData

**I then tried uninstalling node, deleting everything and re-installing everything** and I could install the latest npm version successfully (from `3.10.10` to `5.0.4`), but after that I have the same problem installing `grunt-cli` or `bower`.

I have the same issue with local packages (e.g. `npm i` in a project with a valid `package.json` or `npm i gulp`), and the same two additional lines in the log file.

Note that there's no such thing as `sudo`, everything runs under the same user in Termux. Also, since Termux does not have root access to Android, everything runs under `/data/data/com.termux/files/`, e.g. `~` is `/data/data/com.termux/files/home`, and `node` lives under `/data/data/com.termux/files/usr/bin/node`. This was not an issue before, but here are some useful links if that helps:

* How nodejs is build on Termux: https://github.com/termux/termux-packages/tree/master/packages/nodejs
* The `#!` before each script uses the `termux-fix-shebang` at install to make scripts work out of the box: https://github.com/termux/termux-packages/blob/master/packages/termux-tools/termux-fix-shebang (e.g. `cat $(which npm)` prints `#!/data/data/com.termux/files/usr/bin/env node`) - here's the patch: https://github.com/termux/termux-packages/blob/master/packages/nodejs/deps-npm-lib-build.js.patch

This being said, the issue is happening at runtime, and the printed paths in the error message are correct.

Let me know if I can provide additional details.

#### How can the CLI team reproduce the problem?

1. Get your hands on Termux on any Android device
2 `apt install nodejs`
3. `npm i -g npm@latest`
4. Enter a folder (e.g. `mkdir test && cd test`), optionally doing an `npm init` though that's not required
5. `npm i gulp` (you can try a global or a local install)

### supporting information:

 - `npm -v` prints: `5.0.3` and `5.0.4`
 - `node -v` prints: `6.11.0`
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?: Linux [Termux](https://termux.com/)
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by whao** [comment]
Same problem here

**Comment by legodude17** [comment]
Does your user have access to `/home/.npm`?

**Comment by whao** [comment]
@legodude17 yes

**Comment by christianrondeau** [comment]
@legodude17 `/home` does not exist on Termux, it's `/data/data/com.termux/files/home/.npm`. This path does exist (there are already files in there, e.g. `_cacache`).

Using `termux-chroot` to get a more "linux-gnu-like" file structure, the path becomes indeed `/home/.npm` as you would expect, but with the exact same issue.

The current user (the only user in the case of Termux) does have write access in both cases.

**Comment by enhsaihan-d** [comment]
I'm having exact same problem with same `npm 5.0.3` version but with `node v8.1.3` on Ubuntu 17.04

**Comment by christianrondeau** [comment]
Just a FYI, I have the same issue cloning `npm` and running `make`:

    $ make
    scripts/doc-build.sh doc/cli/npm-access.md man/man1/npm-access.1
    make[1]: Entering directory '/home/npm'
    node bin/npm-cli.js install marked-man --no-global --no-timing --no-save
    Unhandled rejection Error: EACCES: permission denied, link '/home/.npm/_cacache/tmp/91ecd001' -> '/home/.npm/_cacache/content-v2/sha512/c7/85/838cd800efef6c8934286f77e3b867b310d458aa00fa90c64956da8796aae76dd355f5cf898f33fb4c08f3d05c690f3edb8fe66e08cac5e37d2c512b40e6'

I'll try to find more, if someone have an idea, let me know.

**update : it's just running the installed npm, it's the same issue. Ignore this comment.**

**Comment by christianrondeau** [comment]
Quick update : seems to happen in `/home/npm/node_modules/cacache/lib/util/move-file.js`. My guess is that npm tries changing permissions on a system where you cannot do that. To continue.

**Comment by christianrondeau** [comment]
Ok, so here's the line : https://github.com/npm/npm/blob/latest/node_modules/cacache/lib/util/move-file.js#L22

But the src folder does not exist. I would have thought that something would have crashed earlier, but I have no errors. 

Also this doesn't crash even though the target doesn't exist... 

    ln -s /home/.npm/_cacache/tmp/ce7b83a6 /home/.npm/_cacache/content-v2/sha512/10/d4/2843bc465b64f719bd455926100d2561bde9412ed41afc385286309249d1fe6b7e6fae267e57330903732c71d8f8a388ab79a99102f7817da07d2b8e16cc

So the problem happens before. Any idea? I'll continue fiddling very slowly...

**Comment by christianrondeau** [comment]
To be more thorough, with bluebird long stack traces:

```
Unhandled rejection Error: EACCES: permission denied, link '/home/.npm/_cacache/tmp/8b2ab77e' -> '/home/.npm/_cacache/content-v2/sha512/10/d4/2843bc465b64f719bd455926100d2561bde9412ed41afc385286309249d1fe6b7e6fae267e57330903732c71d8f8a388ab79a99102f7817da07d2b8e16cc'
    at Error (native)
From previous event:
    at moveFile (/home/npm/node_modules/cacache/lib/util/move-file.js:22:13)
    at fixOwner.mkdirfix.then (/home/npm/node_modules/cacache/lib/content/write.js:138:12)
    at /home/npm/node_modules/mkdirp/index.js:48:26
From previous event:
    at moveToDestination (/home/npm/node_modules/cacache/lib/content/write.js:136:5)
    at writeFileAsync.then (/home/npm/node_modules/cacache/lib/content/write.js:39:7)
    at /home/npm/node_modules/graceful-fs/graceful-fs.js:99:16
    at /home/npm/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:123:15)
From previous event:
    at BB.using.tmp (/home/npm/node_modules/cacache/lib/content/write.js:38:7)
From previous event:
    at write (/home/npm/node_modules/cacache/lib/content/write.js:35:13)
    at putData (/home/npm/node_modules/cacache/put.js:11:10)
    at Object.x.put (/home/npm/node_modules/cacache/locales/en.js:26:37)
    at WriteStream.done [as _flush] (/home/npm/node_modules/pacote/node_modules/make-fetch-happen/cache.js:156:21)
    at WriteStream._write (/home/npm/node_modules/mississippi/node_modules/flush-write-stream/index.js:34:35)
    at doWrite (/home/npm/node_modules/readable-stream/lib/_stream_writable.js:405:64)
    at writeOrBuffer (/home/npm/node_modules/readable-stream/lib/_stream_writable.js:394:5)
    at WriteStream.Writable.write (/home/npm/node_modules/readable-stream/lib/_stream_writable.js:321:11)
    at WriteStream.end (/home/npm/node_modules/mississippi/node_modules/flush-write-stream/index.js:43:41)
    at WriteStream.end (/home/npm/node_modules/mississippi/node_modules/flush-write-stream/index.js:40:47)
    at WriteStream.done [as _flush] (/home/npm/node_modules/pacote/node_modules/make-fetch-happen/cache.js:173:45)
    at WriteStream._write (/home/npm/node_modules/mississippi/node_modules/flush-write-stream/index.js:34:35)
    at doWrite (/home/npm/node_modules/readable-stream/lib/_stream_writable.js:405:64)
    at writeOrBuffer (/home/npm/node_modules/readable-stream/lib/_stream_writable.js:394:5)
    at WriteStream.Writable.write (/home/npm/node_modules/readable-stream/lib/_stream_writable.js:321:11)
    at WriteStream.end (/home/npm/node_modules/mississippi/node_modules/flush-write-stream/index.js:43:41)
    at WriteStream.end (/home/npm/node_modules/mississippi/node_modules/flush-write-stream/index.js:40:47)
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/.npm/_logs/2017-07-10T12_34_45_509Z-debug.log
```

**Comment by christianrondeau** [comment]
Finally found the problem and a workaround:

    proot --link2symlink npm i -g npm

The problem is that termux does not support hardlinks. So any system that only allows symlink will fail.

Why not just use symlinks? Could this be an option?

**Comment by christianrondeau** [comment]
My workaround works only partially. Using this with `npm i` still happily throws `ENOENT` for every package.

**Comment by mattacular** [comment]
I am having this same problem on ChromeOS using `nodejs-current` termux package (npm 5.3.0). That proot workaround works for most packages I've tried so far. Still having issues installing certain things (eg. bcrypt) but the errors are different and probably unrelated to this issue.

**Comment by TheDiamondYT1** [comment]
Copy the node project to the termux home directory then run npm

**Comment by fornwall** [comment]
About hard links not being supported: It's generally disallowed by a SELinux rule starting from Android 6.0 - see https://code.google.com/archive/p/android-developer-preview/issues/3150:

> This is working as intended. Hard linking files is blocked and an attempt to call link() on a file will return EACCES.

So making a fallback for systems where the hardlink fails would be appreciated by at least Android users :).

**Comment by fornwall** [comment]
There is a PR for cacache at https://github.com/zkat/cacache/pull/110 - if that gets merged this issue should then be solved by updating cacache.

**Comment by sambitpatra73** [comment]
In mac, I am facing similar error Unhandled rejection Error: EACCES: permission denied, with /.npm/_cacache/content-v2/sha512/38/84/
Solved with
sudo chown $(whoami)  ~/.npm/_cacache/content-v2/sha512/38/84

**Comment by RecuencoJones** [comment]
In OS X High Sierra (10.13.3) I had to Restart in Recovery mode (hold `⌘+R` while restarting), then open Terminal (top bar, `Utilities` > `Terminal`), access my mounted disk to find the users directory (`cd /Volumes/Macintosh HD/Users/my-user`) and finally I could `rm -rf .npm`.

I can again install packages normally 🎉

**Comment by cino893** [comment]
you just have to set --unsafe-perm to true
`npm i -g node --unsafe-perm`

**Comment by jimuld** [comment]
@sambitpatra73, yes it worked for me too by using sudo on imac. Thanks.

**Comment by IllyaMoskvin** [comment]
I suspect I triggered this error when upgrading my node version with `nvm`.

Extending @sambitpatra73's answer, this worked for me:

```
sudo chown -R $(whoami) ~/.npm
sudo chown -R $(whoami) ~/.node-gyp
```

The `.node-gyp` directory is used when compiling certain modules on install. In my case, its permissions were also fubar'd by whatever I did to trigger this error.
