### ISSUE TITLE
Unhandled rejection Error

### ISSUE THREAD

**Issue by Mehrpouya** [npm/npm#17502]
#### I'm opening this issue because:

  - [x] npm is crashing.

**Comment by Mehrpouya** [comment]
Unhandled rejection Error: Argument #2: Expected string but got null graceful-readlink@>= 1.0.0 fetched in 90ms
    at addDependency (C:\...\Roaming\npm\node_modules\npm\lib\install\deps.js:515:3)
    at C:\...\Roaming\npm\node_modules\npm\lib\install\deps.js:463:5
    at C:\...\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:52:35
    at Array.forEach (native)
    at C:\...\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:52:11
    at Array.forEach (native)
    at asyncMap (C:\...\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:51:8)
    at loadDeps (C:\...\Roaming\npm\node_modules\npm\lib\install\deps.js:455:3)
    at Array.<anonymous> (C:\...\Roaming\npm\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
    at LOOP (C:\...\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
    at C:\...\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:18:7
    at C:\...\Roaming\npm\node_modules\npm\lib\install\and-finish-tracker.js:8:8
    at resolveBranchDeps.then (C:\...\Roaming\npm\node_modules\npm\lib\install\deps.js:419:11)
    at tryCatcher (C:\...\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\...\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\...\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)

npm ERR! cb() never called!

**Comment by kenany** [comment]
@Mehrpouya Could you upload the full log to <https://gist.github.com/> and link it here? Thanks!

**Comment by kenany** [comment]
Closing due to no response after a week. Probably updating to `npm@5.1` would solve this?

**Comment by Mehrpouya** [comment]
It did solve it. Not sure what I have done, but I upgraded. Now npm works
fine. Will let you know if I run into similar issue again. Sorry for late
response and really appreciate you getting back.

Cheerio
