### ISSUE TITLE
After successful npm install, it throws an error??

### ISSUE THREAD

**Issue by binarykitchen** [npm/npm#17512]
This is funny. When you just did a successful `npm install`, then you expect all stuff to be installed and that nothing is missing.

But not here. Did a `gulp test` afterwards and then it complains about a missing `lru-cache` module, huh?

```
┌─( ~/c/videomail-client ✭ λ:develop 9016e23 )─────────────────────────────────────────────────────────( @M1 )─┐
└─( 2 ) ❱❱❱ npm install                                                                          +2746 21:08 ❰─┘
npm WARN prefer global leasot@4.7.0 should be installed with -g

> electron@1.6.11 postinstall /home/michael-heuberger/code/videomail-client/node_modules/electron
> node install.js

added 1101 packages in 46.71s
                                                                                                                 
┌─( ~/c/videomail-client ✭ λ:develop 9016e23 )─────────────────────────────────────────────────────────( @M1 )─┐
└─( 2 ) ❱❱❱ gulp test                                                                            +2747 21:09 ❰─┘
module.js:487
    throw err;
    ^

Error: Cannot find module 'lru-cache'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at /home/michael-heuberger/code/videomail-client/node_modules/globule/node_modules/minimatch/minimatch.js:35:11
    at Object.<anonymous> (/home/michael-heuberger/code/videomail-client/node_modules/globule/node_modules/minimatch/minimatch.js:1051:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
```

**Comment by ajzozakiewicz** [comment]
Get the same error. Reverting to 5.0.3 fixes the issue... Definitely seems like a bug was introduced in latest

**Comment by legodude17** [comment]
What does `npm ls lru-cache` result in?

**Comment by binarykitchen** [comment]
too late, did a rm -rf node_modules, deleted the lock file and then it worked. just weird and shows that npm has some instabilities inside.
