### ISSUE TITLE
npm install - power shell - windows 10 64-bit

### ISSUE THREAD

**Issue by AndreLei** [npm/npm#17523]
#### I'm opening this issue because:

  - [x] npm is producing an incorrect install.

#### What's going wrong?

**Unhandled rejection Error: Argument #2: Expected string but got nullealTree
    at addDependency (C:\Users\andra\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:515:3)
    at C:\Users\andra\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:463:5
    at C:\Users\andra\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:52:35
    at Array.forEach (native)
    at C:\Users\andra\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:52:11
    at Array.forEach (native)
    at asyncMap (C:\Users\andra\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:51:8)
    at loadDeps (C:\Users\andra\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:455:3)
    at Array.<anonymous> (C:\Users\andra\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
    at LOOP (C:\Users\andra\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
    at C:\Users\andra\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:18:7
    at C:\Users\andra\AppData\Roaming\npm\node_modules\npm\lib\install\and-finish-tracker.js:8:8
    at resolveBranchDeps.then (C:\Users\andra\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:419:11)
    at tryCatcher (C:\Users\andra\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\andra\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\r
elease\promise.js:512:31)
    at Promise._settlePromise (C:\Users\andra\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\prom
ise.js:569:18)

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\andra\AppData\Roaming\npm-cache\_logs\2017-06-29T15_46_01_697Z-debug.log**

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment]
@AndreLei Could you upload the debug log to <https://gist.github.com/> and link it here? Thanks!

**Comment by AndreLei** [comment]
Sorry, KenanY I already deleted everything and then installed it again ... IT seems to be working now :) I'm sorry :/
