### ISSUE TITLE
impossible to install npm

### ISSUE THREAD

**Issue by pinaudnico** [npm/npm#17520]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [* ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

Hi,
imposssible to install npm, sorry begining.

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'install' ]
2 info using npm@3.10.10
3 info using node@v6.11.0
4 verbose stack Error: Cannot find module 'github-url-from-username-repo'
4 verbose stack     at Function.Module._resolveFilename (module.js:469:15)
4 verbose stack     at Function.Module._load (module.js:417:25)
4 verbose stack     at Module.require (module.js:497:17)
4 verbose stack     at require (internal/module.js:20:19)
4 verbose stack     at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/fixer.js:8:22)
4 verbose stack     at Module._compile (module.js:570:32)
4 verbose stack     at Object.Module._extensions..js (module.js:579:10)
4 verbose stack     at Module.load (module.js:487:32)
4 verbose stack     at tryModuleLoad (module.js:446:12)
4 verbose stack     at Function.Module._load (module.js:438:3)
5 verbose cwd /Users/macpro/Desktop/React-Pour-Les-Debutants-Fichiers-De-Base-Final/Projet 1 Markdown/markdown
6 error Darwin 16.6.0
7 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
8 error node v6.11.0
9 error npm  v3.10.10
10 error code MODULE_NOT_FOUND
11 error Cannot find module 'github-url-from-username-repo'
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]

thanks for help !
Nicolas

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by pinaudnico** [comment]
Sorry I've found the solution. old installation remain : do 
sudo rm -rf /usr/local/lib/node_modules/npm
and then ok
