### ISSUE TITLE
Webpack 3 install/update problems. 

### ISSUE THREAD

**Issue by hellooldfriend** [npm/npm#17543]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Hi! A few days ago I installed webpack, but I installed the old one, but everything was working. Today I tried to update to the last version, but something went wrong.
After running the command:
` npm install webpack@3.0.0 --save-dev`
it gives me this: 
       
 ```
/Users/Samat/samat/webpack
└─┬ UNMET PEER DEPENDENCY webpack@3.0.0
  └── UNMET PEER DEPENDENCY ajv@5.2.0

npm WARN Invalid version: "^3.0.0"
npm WARN babel-loader@6.4.1 requires a peer of webpack@1 || 2 || ^2.1.0-beta || ^2.2.0-rc but none was installed.
npm WARN extract-text-webpack-plugin@1.0.1 requires a peer of webpack@^1.9.11 but none was installed.
npm WARN sass-loader@4.1.1 requires a peer of webpack@^2 || ^2.2.0-rc.0 || ^2.1.0-beta || ^1.12.6 but none was installed.
npm WARN webpack-dev-server@2.5.0 requires a peer of webpack@^2.2.0 but none was installed.
npm WARN ajv-keywords@2.1.0 requires a peer of ajv@>=5.0.0 but none was installed.
npm WARN webpack No description
npm WARN webpack No repository field.
npm WARN webpack No README data
npm WARN webpack No license field.
npm ERR! code 1
```
Also, `npm run build`  doesn't work and gives this: 

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@3.10.10
3 info using node@v6.11.0
4 verbose stack Error: Invalid version: "^3.0.0"
4 verbose stack     at Object.fixVersionField (/usr/local/lib/node_modules/npm/node_modules/normalize-package-data/lib/fixer.js:191:13)
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/normalize-package-data/lib/normalize.js:32:38
4 verbose stack     at Array.forEach (native)
4 verbose stack     at normalize (/usr/local/lib/node_modules/npm/node_modules/normalize-package-data/lib/normalize.js:31:15)
4 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:349:5)
4 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:124:5)
4 verbose stack     at ReadFileContext.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:295:20)
4 verbose stack     at ReadFileContext.callback (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16)
4 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:366:13)
5 verbose cwd /Users/Samat/samat/webpack
6 error Darwin 16.6.0
7 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
8 error node v6.11.0
9 error npm  v3.10.10
10 error Invalid version: "^3.0.0"
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

```

### supporting information:

 - `npm -v` prints: 3.10.10
 - `node -v` prints: v6.11.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: macOs Sierra, 10.12.5
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

_____________ 

How can I solve the problem?

**Comment by samat1989** [comment]
*update: 
After running the command: 

`npm run build` 

I see this: 

```
> my-webpack@3.0.0 build /Users/Samat/samat/webpack
> NODE_ENV=prod node_modules/.bin/webpack --config webpack.config.js

/Users/Samat/samat/webpack/webpack.config.js:48
        new webpack.optimize.OccurenceOrderPlugin(true),
        ^

TypeError: webpack.optimize.OccurenceOrderPlugin is not a constructor
    at Object.<anonymous> (/Users/Samat/samat/webpack/webpack.config.js:48:9)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at requireConfig (/Users/Samat/samat/webpack/node_modules/webpack/bin/convert-argv.js:96:18)
    at /Users/Samat/samat/webpack/node_modules/webpack/bin/convert-argv.js:109:17

npm ERR! Darwin 16.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! my-webpack@3.0.0 build: `NODE_ENV=prod node_modules/.bin/webpack --config webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my-webpack@3.0.0 build script 'NODE_ENV=prod node_modules/.bin/webpack --config webpack.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the my-webpack package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_ENV=prod node_modules/.bin/webpack --config webpack.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs my-webpack
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls my-webpack
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Samat/samat/webpack/npm-debug.log
```

**Comment by hellooldfriend** [comment]
Looks like I could install webpack 3. But when I run command: 
`npm run build` 
It gives me this: 
```

> my-webpack@3.0.0 build /Users/Samat/samat/webpack
> NODE_ENV=prod node_modules/.bin/webpack --config webpack.config.js

/Users/Samat/samat/webpack/webpack.config.js:48
        new webpack.optimize.OccurenceOrderPlugin(true),
        ^

TypeError: webpack.optimize.OccurenceOrderPlugin is not a constructor
    at Object.<anonymous> (/Users/Samat/samat/webpack/webpack.config.js:48:9)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at requireConfig (/Users/Samat/samat/webpack/node_modules/webpack/bin/convert-argv.js:96:18)
    at /Users/Samat/samat/webpack/node_modules/webpack/bin/convert-argv.js:109:17
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-webpack@3.0.0 build: `NODE_ENV=prod node_modules/.bin/webpack --config webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my-webpack@3.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Samat/.npm/_logs/2017-06-30T11_54_33_604Z-debug.log
```

How can I solve this and make my webpack work properly?

**Comment by kenany** [comment]
This doesn't seem like an `npm` issue to me? The peer dependency warnings seem correct, since those packages seem to generally be expecting `webpack@2` but you're installing `webpack@3`. The invalid version error sounds like the `"version"` field in your `package.json` was not valid, but I assume you've since resolved that before your next comment. The final error is not coming from `npm`, but you could resolve it by removing that plugin entirely anyways; it has been enabled by default since `webpack@2` anyways.
