### ISSUE TITLE
"Unhandled rejection RangeError: Maximum call stack size exceeded" when npm removing package

### ISSUE THREAD

**Issue by Jancat** [npm/npm#17558]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
When I run `npm remove eslint -D`, it occurs errors:

```
Unhandled rejection RangeError: Maximum call stack size exceeded31a980306fb7f8ef
    at Array.forEach (native)
    at exports.create (D:\nodejs\node_modules\npm\lib\install\node.js:33:25)
    at D:\nodejs\node_modules\npm\lib\install\node.js:36:14
    at Array.forEach (native)
    at exports.create (D:\nodejs\node_modules\npm\lib\install\node.js:33:25)
    at D:\nodejs\node_modules\npm\lib\install\node.js:36:14
    at Array.forEach (native)
    at exports.create (D:\nodejs\node_modules\npm\lib\install\node.js:33:25)
    at normalizeTree (D:\nodejs\node_modules\npm\lib\install.js:377:5)
    at Array.forEach (native)
    at normalizeTree (D:\nodejs\node_modules\npm\lib\install.js:379:19)
    at Array.forEach (native)
    at normalizeTree (D:\nodejs\node_modules\npm\lib\install.js:379:19)
    at Array.forEach (native)
    at normalizeTree (D:\nodejs\node_modules\npm\lib\install.js:379:19)
    at Array.forEach (native)

npm ERR! cb() never called!
```

### supporting information:

 - `npm -v` prints: 5.0.3
 - `node -v` prints: v8.1.1
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows

### compelete error log
```
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\nodejs\\node.exe',
1 verbose cli   'D:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'i',
1 verbose cli   '--save-dev',
1 verbose cli   'eslint-config-airbnb-base@latest',
1 verbose cli   'eslint@3.19.0',
1 verbose cli   'eslint-plugin-import@2.2.0' ]
2 info using npm@5.0.3
3 info using node@v8.1.1
4 verbose npm-session 2263780a4a999bf3
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://registry.npm.taobao.org/eslint-config-airbnb-base 244ms
8 silly pacote tag manifest for eslint-config-airbnb-base@latest fetched in 293ms
9 http fetch GET 200 https://registry.npm.taobao.org/eslint-plugin-import 340ms
10 silly pacote version manifest for eslint-plugin-import@2.2.0 fetched in 359ms
11 http fetch GET 200 https://registry.npm.taobao.org/eslint 516ms
12 silly pacote version manifest for eslint@3.19.0 fetched in 528ms
13 verbose stack RangeError: Maximum call stack size exceeded
13 verbose stack     at exports.create (D:\nodejs\node_modules\npm\lib\install\node.js:31:40)
13 verbose stack     at D:\nodejs\node_modules\npm\lib\install\node.js:36:14
13 verbose stack     at Array.forEach (native)
13 verbose stack     at exports.create (D:\nodejs\node_modules\npm\lib\install\node.js:33:25)
13 verbose stack     at D:\nodejs\node_modules\npm\lib\install\node.js:36:14
13 verbose stack     at Array.forEach (native)
13 verbose stack     at exports.create (D:\nodejs\node_modules\npm\lib\install\node.js:33:25)
13 verbose stack     at normalizeTree (D:\nodejs\node_modules\npm\lib\install.js:377:5)
13 verbose stack     at Array.forEach (native)
13 verbose stack     at normalizeTree (D:\nodejs\node_modules\npm\lib\install.js:379:19)
13 verbose stack     at Array.forEach (native)
13 verbose stack     at normalizeTree (D:\nodejs\node_modules\npm\lib\install.js:379:19)
13 verbose stack     at Array.forEach (native)
13 verbose stack     at normalizeTree (D:\nodejs\node_modules\npm\lib\install.js:379:19)
13 verbose stack     at Array.forEach (native)
13 verbose stack     at normalizeTree (D:\nodejs\node_modules\npm\lib\install.js:379:19)
14 verbose cwd F:\Demos\vue-demos\vue-demos
15 verbose Windows_NT 10.0.14393
16 verbose argv "D:\\nodejs\\node.exe" "D:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "--save-dev" "eslint-config-airbnb-base@latest" "eslint@3.19.0" "eslint-plugin-import@2.2.0"
17 verbose node v8.1.1
18 verbose npm  v5.0.3
19 error Maximum call stack size exceeded
20 verbose exit [ 1, true ]

```

**Comment by wenshan** [comment]
Meet the same problem~

**Comment by catbea** [comment]
Meet the same problem~,How to  do?

**Comment by loongcaser** [comment]
How to do?
