### ISSUE TITLE
npm install - failing with error

### ISSUE THREAD

**Issue by mjstroh** [npm/npm#17559]
#### I'm opening this issue because:

  - [ ] npm is producing an incorrect install.

#### What's going wrong?

Error as follows:

$ npm install
npm WARN deprecated isarray@2.0.1: Just use Array.isArray directly
npm WARN deprecated unzip-response@3.0.0: Renamed to decompress-response
Unhandled rejection Error: Argument #2: Expected string but got null is-scoped@^1.0.0 fetched in 38ms
    at addDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:515:3)
    at /usr/local/lib/node_modules/npm/lib/install/deps.js:463:5
    at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
    at Array.forEach (native)
    at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
    at Array.forEach (native)
    at asyncMap (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
    at loadDeps (/usr/local/lib/node_modules/npm/lib/install/deps.js:455:3)
    at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
    at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
    at /usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
    at /usr/local/lib/node_modules/npm/lib/install/and-finish-tracker.js:8:8
    at resolveBranchDeps.then (/usr/local/lib/node_modules/npm/lib/install/deps.js:419:11)
    at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

#### How can the CLI team reproduce the problem?

type "npm install"

### supporting information:

 - `npm -v` prints:
5.0.3
 - `node -v` prints:
v8.1.3
 - `npm config get registry` prints:
n/a

O/S:  macOS v 10.12.5

 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
yes
   - [ ] I use a proxy when downloading Git repos.
yes
   - [ ] I access the npm registry via a VPN
yes

**Comment by mjstroh** [comment]
[npm_log.txt](https://github.com/npm/npm/files/1117012/npm_log.txt)

**Comment by mjstroh** [comment]
attached log file.

**Comment by mjstroh** [comment]
fixed by restoring /Users/mstroh/package.json that was accidently deleted.

Looks as if the code does not handle null filenames somewhere.
