### ISSUE TITLE
npm run create

### ISSUE THREAD

**Issue by itspinger** [npm/npm#17583]
I cant create a dist folder when i run `npm run create`

create is a script that i have here 

```
{
  "name": "battle",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "create": "webpack"
  },
  "author": "",
  "license": "ISC",
  "babel": {
    "presets": ["env", "react"]
  },
  "devDependencies": {
   "babel-core": "^6.24.0",
   "babel-loader": "^6.4.1",
   "babel-preset-env": "^1.2.2",
   "babel-preset-react": "^6.23.0",
   "css-loader": "^0.27.3",
   "html-webpack-plugin": "^2.28.0",
   "style-loader": "^0.16.0",
   "webpack": "^2.3.1",
   "webpack-dev-server": "^2.4.2"
  },
  "dependencies": {
    "react": "^16.0.0-alpha.5",
    "react-dom": "^15.6.1"
  }
}
```

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'create' ]
2 info using npm@3.10.10
3 info using node@v6.11.0
4 verbose stack Error: missing script: create
4 verbose stack     at run (C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:151:19)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:61:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:356:5
4 verbose stack     at checkBinReferences_ (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:320:45)
4 verbose stack     at final (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:354:3)
4 verbose stack     at then (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:124:5)
4 verbose stack     at ReadFileContext.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:295:20)
4 verbose stack     at ReadFileContext.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16)
4 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:366:13)
5 verbose cwd C:\Users\CortoMaltese\battle
6 error Windows_NT 6.3.9600
7 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "create"
8 error node v6.11.0
9 error npm  v3.10.10
10 error missing script: create
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
```
Anyone that can help?

**Comment by itspinger** [comment]
bump
