### ISSUE TITLE
ng serve not not starting

### ISSUE THREAD

**Issue by sripalreddyadamala** [npm/npm#17587]
ng serve
fallbackLoader option has been deprecated - replace with "fallback"
loader option has been deprecated - replace with "use"
fallbackLoader option has been deprecated - replace with "fallback"
loader option has been deprecated - replace with "use"
fallbackLoader option has been deprecated - replace with "fallback"
loader option has been deprecated - replace with "use"
fallbackLoader option has been deprecated - replace with "fallback"
loader option has been deprecated - replace with "use"
Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at createSourceFile (C:\Users\sripal.adamala\Projects\shoppingcart\node_modules\typescript\lib\typescript.js:8980:109)
    at parseSourceFileWorker (C:\Users\sripal.adamala\Projects\shoppingcart\node_modules\typescript\lib\typescript.js:8940:26)
    at Object.parseSourceFile (C:\Users\sripal.adamala\Projects\shoppingcart\node_modules\typescript\lib\typescript.js:8899:26)
    at Object.createSourceFile (C:\Users\sripal.adamala\Projects\shoppingcart\node_modules\typescript\lib\typescript.js:8727:29)
    at WebpackCompilerHost.getSourceFile (C:\Users\sripal.adamala\Projects\shoppingcart\node_modules\@ngtools\webpack\src\compiler_host.js:210:27)
    at findSourceFile (C:\Users\sripal.adamala\Projects\shoppingcart\node_modules\typescript\lib\typescript.js:45859:29)
    at processSourceFile (C:\Users\sripal.adamala\Projects\shoppingcart\node_modules\typescript\lib\typescript.js:45790:27)
    at C:\Users\sripal.adamala\Projects\shoppingcart\node_modules\typescript\lib\typescript.js:45901:17
    at Object.forEach (C:\Users\sripal.adamala\Projects\shoppingcart\node_modules\typescript\lib\typescript.js:1115:30)
    at processReferencedFiles (C:\Users\sripal.adamala\Projects\shoppingcart\node_modules\typescript\lib\typescript.js:45899:16)
    at findSourceFile (C:\Users\sripal.adamala\Projects\shoppingcart\node_modules\typescript\lib\typescript.js:45884:21)
    at processImportedModules (C:\Users\sripal.adamala\Projects\shoppingcart\node_modules\typescript\lib\typescript.js:45994:25)
    at findSourceFile (C:\Users\sripal.adamala\Projects\shoppingcart\node_modules\typescript\lib\typescript.js:45888:17)
    at processImportedModules (C:\Users\sripal.adamala\Projects\shoppingcart\node_modules\typescript\lib\typescript.js:45994:25)
    at findSourceFile (C:\Users\sripal.adamala\Projects\shoppingcart\node_modules\typescript\lib\typescript.js:45888:17)
    at processSourceFile (C:\Users\sripal.adamala\Projects\shoppingcart\node_modules\typescript\lib\typescript.js:45790:27)
    at processRootFile (C:\Users\sripal.adamala\Projects\shoppingcart\node_modules\typescript\lib\typescript.js:45694:13)
    at C:\Users\sripal.adamala\Projects\shoppingcart\node_modules\typescript\lib\typescript.js:45151:60
    at Object.forEach (C:\Users\sripal.adamala\Projects\shoppingcart\node_modules\typescript\lib\typescript.js:1115:30)
    at Object.createProgram (C:\Users\sripal.adamala\Projects\shoppingcart\node_modules\typescript\lib\typescript.js:45151:16)
    at AotPlugin._setupOptions (C:\Users\sripal.adamala\Projects\shoppingcart\node_modules\@ngtools\webpack\src\plugin.js:129:28)
    at new AotPlugin (C:\Users\sripal.adamala\Projects\shoppingcart\node_modules\@ngtools\webpack\src\plugin.js:26:14)
    at Object.exports.getNonAotConfig (C:\Users\sripal.adamala\Projects\shoppingcart\node_modules\angular-cli\models\webpack-configs\typescript.js:26:13)
    at new NgCliWebpackConfig (C:\Users\sripal.adamala\Projects\shoppingcart\node_modules\angular-cli\models\webpack-config.js:24:37)
    at Class.run (C:\Users\sripal.adamala\Projects\shoppingcart\node_modules\angular-cli\tasks\serve.js:31:29)
    at C:\Users\sripal.adamala\Projects\shoppingcart\node_modules\angular-cli\commands\serve.run.js:22:22
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)

{
    "name": "shoppingcart",
    "version": "0.0.0",
    "license": "MIT",
    "angular-cli": {},
    "scripts": {
        "ng": "ng",
        "start": "ng serve",
        "test": "ng test",
        "pree2e": "webdriver-manager update --standalone false --gecko false",
        "e2e": "protractor"
    },
    "private": true,
    "dependencies": {
        "@angular/common": "^2.3.1",
        "@angular/compiler": "^2.3.1",
        "@angular/core": "^2.3.1",
        "@angular/forms": "^2.3.1",
        "@angular/http": "^2.3.1",
        "@angular/platform-browser": "^2.3.1",
        "@angular/platform-browser-dynamic": "^2.3.1",
        "@angular/router": "^3.3.1",
        "angular2-log": "0.0.6",
        "bootstrap": "^3.3.7",
        "core-js": "^2.4.1",
        "rxjs": "^5.0.1",
        "ts-helpers": "^1.1.1",
        "zone.js": "^0.7.2"
    },
    "devDependencies": {
        "@angular/compiler-cli": "^2.3.1",
        "@types/jasmine": "2.5.38",
        "@types/node": "^6.0.42",
        "angular-cli": "1.0.0-beta.28.3",
        "codelyzer": "~2.0.0-beta.1",
        "jasmine-core": "2.5.2",
        "jasmine-spec-reporter": "2.5.0",
        "karma": "1.2.0",
        "karma-chrome-launcher": "^2.0.0",
        "karma-cli": "^1.0.1",
        "karma-jasmine": "^1.0.2",
        "karma-remap-istanbul": "^0.2.1",
        "protractor": "~4.0.13",
        "ts-node": "1.2.1",
        "tslint": "^4.3.0",
        "typescript": "~2.0.3"
    }
}

**Comment by kenany** [comment]
Doesn't look like this error is coming from `npm`.

**Comment by sripalreddyadamala** [comment]
I am not sure where these is coming from you have a fix for it

**Comment by kenany** [comment]
Stack trace indicates that it comes from `typescript` 🤷‍♀️

**Comment by sripalreddyadamala** [comment]
I am not able to find style.ts in @angular-cli/models/webpack-configs,styles.ts but rather i have styles.d,atyles,styles.js.map.
