### ISSUE TITLE
npm ERR! cb() never called!

### ISSUE THREAD

**Issue by DonYeh** [npm/npm#17613]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Npm install produces an error:

> Unhandled rejection Error: Argument #2: Expected string but got null npm-run-path@^2.0.0 fetched
    at addDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:515:3)
    at /usr/local/lib/node_modules/npm/lib/install/deps.js:463:5
    at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
    at Array.forEach (native)
    at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
    at Array.forEach (native)
    at asyncMap (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
    at loadDeps (/usr/local/lib/node_modules/npm/lib/install/deps.js:455:3)
    at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
    at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
    at /usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
    at /usr/local/lib/node_modules/npm/lib/install/and-finish-tracker.js:8:8
    at resolveBranchDeps.then (/usr/local/lib/node_modules/npm/lib/install/deps.js:419:11)
    at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)

#### How can the CLI team reproduce the problem?

   In terminal, npm install 

here's the contents of the log file: https://gist.github.com/DonYeh/7ce7cfdee740aaa38b6a0f55133aa697

### supporting information:

 - `npm -v` prints: 5.0.4
 - `node -v` prints: 7.10.0
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?: OSX
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by DonYeh** [comment]
here is the file/packages that i was trying to install

[single-page-application-with-angularjs-v1.zip](https://github.com/npm/npm/files/1123487/single-page-application-with-angularjs-v1.zip)

**Comment by totamarusenku** [comment]
I too got into this issue
```
Unhandled rejection Error: Argument #2: Expected string but got nullinstall loadIdealTree
    at addDependency (/home/balvis/.nvm/versions/node/v6.4.0/lib/node_modules/npm/lib/install/deps.js:515:3)
    at /home/balvis/.nvm/versions/node/v6.4.0/lib/node_modules/npm/lib/install/deps.js:463:5
    at /home/balvis/.nvm/versions/node/v6.4.0/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
    at Array.forEach (native)
    at /home/balvis/.nvm/versions/node/v6.4.0/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
    at Array.forEach (native)
    at asyncMap (/home/balvis/.nvm/versions/node/v6.4.0/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
    at loadDeps (/home/balvis/.nvm/versions/node/v6.4.0/lib/node_modules/npm/lib/install/deps.js:455:3)
    at Array.<anonymous> (/home/balvis/.nvm/versions/node/v6.4.0/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
    at LOOP (/home/balvis/.nvm/versions/node/v6.4.0/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
    at /home/balvis/.nvm/versions/node/v6.4.0/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
    at /home/balvis/.nvm/versions/node/v6.4.0/lib/node_modules/npm/lib/install/and-finish-tracker.js:8:8
    at resolveBranchDeps.then (/home/balvis/.nvm/versions/node/v6.4.0/lib/node_modules/npm/lib/install/deps.js:419:11)
    at tryCatcher (/home/balvis/.nvm/versions/node/v6.4.0/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/balvis/.nvm/versions/node/v6.4.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/balvis/.nvm/versions/node/v6.4.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/balvis/.npm/_logs/2017-07-05T05_28_15_665Z-debug.log
```

Here are the logs from the log file
```
0 info it worked if it ends with ok
1 verbose cli [ '/home/balvis/.nvm/versions/node/v6.4.0/bin/node',
1 verbose cli   '/home/balvis/.nvm/versions/node/v6.4.0/bin/npm',
1 verbose cli   'uninstall',
1 verbose cli   '-g',
1 verbose cli   'music-dl' ]
2 info using npm@5.0.4
3 info using node@v6.4.0
4 verbose npm-session 32f78bdb9b18ff47
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly install loadIdealTree
8 silly install cloneCurrentTreeToIdealTree
9 silly install loadShrinkwrap
10 silly uninstall loadAllDepsIntoIdealTree
11 silly install loadAllDepsIntoIdealTree
12 error cb() never called!
13 error This is an error with npm itself. Please report this error at:
14 error <https://github.com/npm/npm/issues>
```

**Comment by princevince** [comment]
Yep, got the same problem.

```
91 info lifecycle react-native-gifted-chat@0.1.4~postpack: react-native-gifted-chat@0.1.4
92 silly prefetch react-native-gifted-chat@file:.. done in 548ms
93 error cb() never called!
94 error This is an error with npm itself. Please report this error at:
95 error <https://github.com/npm/npm/issues>
```

**Comment by honeybuzzer** [comment]
Me too

    0 info it worked if it ends with ok
    1 verbose cli [ '/usr/local/Cellar/node/5.5.0/bin/node',
    1 verbose cli   '/usr/local/bin/npm',
    1 verbose cli   'install',
    1 verbose cli   '-g',
    1 verbose cli   'npm@latest' ]
    2 info using npm@5.0.0
    3 info using node@v5.5.0
    4 silly install loadCurrentTree
    5 silly install readGlobalPackageData
    6 error cb() never called!
    7 error This is an error with npm itself. Please report this error at:
    8 error <https://github.com/npm/npm/issues>

UPDATE:
In my case I was able to resolve the issue by installing nvm, updating Node, then updating npm again.
