### ISSUE TITLE
When I run `npm run build` to build a APP develop with vue.js, electron and elementjs, I got an error like below:

### ISSUE THREAD

**Issue by g10guang** [npm/npm#17630]
The bash result is:
```bash
Downloading tmp-15052-1-SHASUMS256.txt-1.7.4
[============================================>] 100.0% of 2.93 kB (2.93 kB/s)
Packaging app for platform darwin x64 using electron v1.7.4

 ERROR  `electron-packager` says...

Error: Command failed: npm prune --production
Unhandled rejection RangeError: Maximum call stack size exceeded
    at Array.forEach (native)
    at exports.create (/usr/lib/node_modules/npm/lib/install/node.js:33:25)
    at /usr/lib/node_modules/npm/lib/install/node.js:36:14
    at Array.forEach (native)
    at exports.create (/usr/lib/node_modules/npm/lib/install/node.js:33:25)
    at /usr/lib/node_modules/npm/lib/install/node.js:36:14
    at Array.forEach (native)
    at exports.create (/usr/lib/node_modules/npm/lib/install/node.js:33:25)
    at normalizeTree (/usr/lib/node_modules/npm/lib/install.js:377:5)
    at Array.forEach (native)
    at normalizeTree (/usr/lib/node_modules/npm/lib/install.js:379:19)
    at Array.forEach (native)
    at normalizeTree (/usr/lib/node_modules/npm/lib/install.js:379:19)
    at Array.forEach (native)
    at normalizeTree (/usr/lib/node_modules/npm/lib/install.js:379:19)
    at Array.forEach (native)
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

**Comment by lomelee** [comment]
I have also encountered the same problem。。。

**Comment by lomelee** [comment]
Encountered this problem before I used the “cnpm install” （mirror taobao.org） install dependency package,

Replaced by “npm install”, and then use “npm run build” can work properly,
