### ISSUE TITLE
npm crashes when trying to uninstall gulp globally

### ISSUE THREAD

**Issue by fbnlsr** [npm/npm#17673]
#### I'm opening this issue because:

  - [X] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [X] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I'm trying to uninstall gulp globally so that I can re-install it using the 4.0 branch.

Here's the error message I get
```
Unhandled rejection Error: Argument #2: Expected string but got null randomatic@^1.1.3 fetched in 58ms
    at addDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:515:3)
    at /usr/local/lib/node_modules/npm/lib/install/deps.js:463:5
    at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
    at Array.forEach (native)
    at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
    at Array.forEach (native)
    at asyncMap (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
    at loadDeps (/usr/local/lib/node_modules/npm/lib/install/deps.js:455:3)
    at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
    at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
    at /usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
    at /usr/local/lib/node_modules/npm/lib/install/and-finish-tracker.js:8:8
    at resolveBranchDeps.then (/usr/local/lib/node_modules/npm/lib/install/deps.js:419:11)
    at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

### supporting information:

 - `npm -v` prints: 5.0.4
 - `node -v` prints: v8.0.0
 - `npm config get registry` prints: https://registry.npmjs.org
 - Windows, OS X/macOS, or Linux?: macOS

Here's the error log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'uninstall',
1 verbose cli   'gulp',
1 verbose cli   '-g' ]
2 info using npm@5.0.4
3 info using node@v8.0.0
4 verbose npm-session beab80111546c11f
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly install loadIdealTree
8 silly install cloneCurrentTreeToIdealTree
9 silly install loadShrinkwrap
10 silly uninstall loadAllDepsIntoIdealTree
11 silly install loadAllDepsIntoIdealTree
12 http fetch GET 200 https://registry.npmjs.org/gulp 348ms
13 silly pacote tag manifest for gulp@latest fetched in 537ms
14 http fetch GET 304 https://registry.npmjs.org/gulp-util 96ms (from cache)
15 silly pacote range manifest for gulp-util@^3.0.0 fetched in 102ms
16 http fetch GET 304 https://registry.npmjs.org/minimist 174ms (from cache)
17 http fetch GET 304 https://registry.npmjs.org/chalk 177ms (from cache)
18 http fetch GET 304 https://registry.npmjs.org/archy 185ms (from cache)
19 silly pacote range manifest for minimist@^1.1.0 fetched in 184ms
20 silly pacote range manifest for chalk@^1.0.0 fetched in 186ms
21 http fetch GET 304 https://registry.npmjs.org/semver 200ms (from cache)
22 http fetch GET 304 https://registry.npmjs.org/interpret 217ms (from cache)
23 http fetch GET 304 https://registry.npmjs.org/deprecated 219ms (from cache)
24 silly pacote range manifest for archy@^1.0.0 fetched in 224ms
25 silly pacote range manifest for semver@^4.1.0 fetched in 221ms
26 http fetch GET 304 https://registry.npmjs.org/liftoff 226ms (from cache)
27 http fetch GET 304 https://registry.npmjs.org/pretty-hrtime 225ms (from cache)
28 silly pacote range manifest for deprecated@^0.0.1 fetched in 231ms
29 silly pacote range manifest for interpret@^1.0.0 fetched in 229ms
30 silly pacote range manifest for liftoff@^2.1.0 fetched in 246ms
31 silly pacote range manifest for pretty-hrtime@^1.0.0 fetched in 243ms
32 http fetch GET 304 https://registry.npmjs.org/tildify 151ms (from cache)
33 silly pacote range manifest for tildify@^1.0.0 fetched in 161ms
34 http fetch GET 304 https://registry.npmjs.org/orchestrator 301ms (from cache)
35 silly pacote range manifest for orchestrator@^0.3.0 fetched in 312ms
36 http fetch GET 304 https://registry.npmjs.org/v8flags 147ms (from cache)
37 http fetch GET 304 https://registry.npmjs.org/vinyl-fs 149ms (from cache)
38 http fetch GET 304 https://registry.npmjs.org/array-uniq 114ms (from cache)
39 http fetch GET 304 https://registry.npmjs.org/array-differ 122ms (from cache)
40 silly pacote range manifest for vinyl-fs@^0.3.0 fetched in 160ms
41 silly pacote range manifest for v8flags@^2.0.2 fetched in 161ms
42 silly pacote range manifest for array-uniq@^1.0.2 fetched in 123ms
43 silly pacote range manifest for array-differ@^1.0.0 fetched in 130ms
44 http fetch GET 304 https://registry.npmjs.org/beeper 122ms (from cache)
45 http fetch GET 304 https://registry.npmjs.org/dateformat 126ms (from cache)
46 http fetch GET 304 https://registry.npmjs.org/fancy-log 111ms (from cache)
47 silly pacote range manifest for beeper@^1.0.0 fetched in 131ms
48 silly pacote range manifest for fancy-log@^1.1.0 fetched in 122ms
49 silly pacote range manifest for dateformat@^2.0.0 fetched in 142ms
50 http fetch GET 304 https://registry.npmjs.org/has-gulplog 109ms (from cache)
51 silly pacote range manifest for has-gulplog@^0.1.0 fetched in 118ms
52 http fetch GET 304 https://registry.npmjs.org/lodash._reescape 92ms (from cache)
53 http fetch GET 304 https://registry.npmjs.org/lodash._reinterpolate 61ms (from cache)
54 silly pacote range manifest for lodash._reinterpolate@^3.0.0 fetched in 66ms
55 silly pacote range manifest for lodash._reescape@^3.0.0 fetched in 99ms
56 http fetch GET 304 https://registry.npmjs.org/lodash._reevaluate 71ms (from cache)
57 silly pacote range manifest for lodash._reevaluate@^3.0.0 fetched in 81ms
58 http fetch GET 304 https://registry.npmjs.org/gulplog 183ms (from cache)
59 silly pacote range manifest for gulplog@^1.0.0 fetched in 197ms
60 http fetch GET 304 https://registry.npmjs.org/lodash.template 102ms (from cache)
61 http fetch GET 304 https://registry.npmjs.org/object-assign 102ms (from cache)
62 silly pacote range manifest for lodash.template@^3.0.0 fetched in 126ms
63 silly pacote range manifest for object-assign@^3.0.0 fetched in 117ms
64 http fetch GET 304 https://registry.npmjs.org/replace-ext 112ms (from cache)
65 http fetch GET 304 https://registry.npmjs.org/through2 119ms (from cache)
66 silly pacote version manifest for replace-ext@0.0.1 fetched in 130ms
67 silly pacote range manifest for through2@^2.0.0 fetched in 128ms
68 http fetch GET 304 https://registry.npmjs.org/vinyl 125ms (from cache)
69 http fetch GET 304 https://registry.npmjs.org/escape-string-regexp 108ms (from cache)
70 silly pacote range manifest for vinyl@^0.5.0 fetched in 139ms
71 http fetch GET 304 https://registry.npmjs.org/has-ansi 98ms (from cache)
72 http fetch GET 304 https://registry.npmjs.org/ansi-styles 112ms (from cache)
73 silly pacote range manifest for has-ansi@^2.0.0 fetched in 103ms
74 http fetch GET 304 https://registry.npmjs.org/strip-ansi 85ms (from cache)
75 silly pacote range manifest for ansi-styles@^2.2.1 fetched in 118ms
76 silly pacote range manifest for escape-string-regexp@^1.0.2 fetched in 118ms
77 silly pacote range manifest for strip-ansi@^3.0.0 fetched in 93ms
78 http fetch GET 304 https://registry.npmjs.org/multipipe 194ms (from cache)
79 http fetch GET 304 https://registry.npmjs.org/supports-color 74ms (from cache)
80 silly pacote range manifest for multipipe@^0.1.2 fetched in 204ms
81 http fetch GET 304 https://registry.npmjs.org/extend 75ms (from cache)
82 silly pacote range manifest for supports-color@^2.0.0 fetched in 81ms
83 silly pacote range manifest for extend@^3.0.0 fetched in 79ms
84 http fetch GET 304 https://registry.npmjs.org/findup-sync 70ms (from cache)
85 silly pacote range manifest for findup-sync@^0.4.2 fetched in 74ms
86 http fetch GET 304 https://registry.npmjs.org/rechoir 46ms (from cache)
87 silly pacote range manifest for rechoir@^0.6.2 fetched in 49ms
88 http fetch GET 304 https://registry.npmjs.org/resolve 48ms (from cache)
89 silly pacote range manifest for resolve@^1.1.7 fetched in 51ms
90 http fetch GET 304 https://registry.npmjs.org/os-homedir 49ms (from cache)
91 http fetch GET 304 https://registry.npmjs.org/end-of-stream 51ms (from cache)
92 silly pacote range manifest for os-homedir@^1.0.0 fetched in 57ms
93 silly pacote range manifest for end-of-stream@~0.1.5 fetched in 54ms
94 http fetch GET 304 https://registry.npmjs.org/fined 171ms (from cache)
95 http fetch GET 304 https://registry.npmjs.org/flagged-respawn 153ms (from cache)
96 http fetch GET 304 https://registry.npmjs.org/lodash.isplainobject 150ms (from cache)
97 http fetch GET 304 https://registry.npmjs.org/sequencify 109ms (from cache)
98 http fetch GET 304 https://registry.npmjs.org/stream-consume 96ms (from cache)
99 silly pacote range manifest for fined@^1.0.1 fetched in 181ms
100 silly pacote range manifest for flagged-respawn@^0.3.2 fetched in 161ms
101 http fetch GET 304 https://registry.npmjs.org/lodash.mapvalues 154ms (from cache)
102 silly pacote range manifest for lodash.isplainobject@^4.0.4 fetched in 163ms
103 silly pacote range manifest for stream-consume@~0.1.0 fetched in 108ms
104 silly pacote range manifest for sequencify@~0.0.7 fetched in 122ms
105 silly pacote range manifest for lodash.mapvalues@^4.4.0 fetched in 168ms
106 http fetch GET 304 https://registry.npmjs.org/lodash.isstring 169ms (from cache)
107 http fetch GET 304 https://registry.npmjs.org/glob-watcher 91ms (from cache)
108 silly pacote range manifest for through2@^0.6.1 fetched in 10ms
109 silly pacote range manifest for vinyl@^0.4.0 fetched in 10ms
110 silly pacote range manifest for lodash.isstring@^4.0.1 fetched in 175ms
111 http fetch GET 304 https://registry.npmjs.org/defaults 105ms (from cache)
112 silly pacote range manifest for chalk@^1.1.1 fetched in 4ms
113 silly pacote range manifest for glob-watcher@^0.0.6 fetched in 98ms
114 silly pacote range manifest for defaults@^1.0.0 fetched in 113ms
115 http fetch GET 304 https://registry.npmjs.org/glob-stream 112ms (from cache)
116 silly pacote range manifest for glob-stream@^3.1.5 fetched in 120ms
117 http fetch GET 304 https://registry.npmjs.org/graceful-fs 59ms (from cache)
118 http fetch GET 304 https://registry.npmjs.org/strip-bom 56ms (from cache)
119 silly pacote range manifest for graceful-fs@^3.0.0 fetched in 69ms
120 silly pacote range manifest for strip-bom@^1.0.0 fetched in 59ms
121 http fetch GET 304 https://registry.npmjs.org/mkdirp 70ms (from cache)
122 http fetch GET 304 https://registry.npmjs.org/user-home 63ms (from cache)
123 silly pacote range manifest for mkdirp@^0.5.0 fetched in 82ms
124 silly pacote range manifest for user-home@^1.1.1 fetched in 72ms
125 http fetch GET 304 https://registry.npmjs.org/time-stamp 91ms (from cache)
126 http fetch GET 304 https://registry.npmjs.org/sparkles 116ms (from cache)
127 silly pacote range manifest for time-stamp@^1.0.0 fetched in 121ms
128 silly pacote range manifest for sparkles@^1.0.0 fetched in 129ms
129 http fetch GET 304 https://registry.npmjs.org/lodash._basecopy 127ms (from cache)
130 http fetch GET 304 https://registry.npmjs.org/lodash._basetostring 121ms (from cache)
131 silly pacote range manifest for lodash._basecopy@^3.0.0 fetched in 133ms
132 http fetch GET 304 https://registry.npmjs.org/glogg 135ms (from cache)
133 silly pacote range manifest for lodash._basetostring@^3.0.0 fetched in 127ms
134 silly pacote range manifest for glogg@^1.0.0 fetched in 157ms
135 http fetch GET 304 https://registry.npmjs.org/lodash.keys 121ms (from cache)
136 http fetch GET 304 https://registry.npmjs.org/lodash.escape 134ms (from cache)
137 http fetch GET 304 https://registry.npmjs.org/lodash._isiterateecall 146ms (from cache)
138 silly pacote range manifest for lodash.escape@^3.0.0 fetched in 161ms
139 silly pacote range manifest for lodash.keys@^3.0.0 fetched in 152ms
140 silly pacote range manifest for lodash._isiterateecall@^3.0.0 fetched in 169ms
141 http fetch GET 304 https://registry.npmjs.org/lodash.restparam 175ms (from cache)
142 http fetch GET 304 https://registry.npmjs.org/lodash.templatesettings 128ms (from cache)
143 silly pacote range manifest for lodash.restparam@^3.0.0 fetched in 193ms
144 silly pacote range manifest for lodash.templatesettings@^3.0.0 fetched in 144ms
145 http fetch GET 304 https://registry.npmjs.org/lodash._basevalues 240ms (from cache)
146 silly pacote range manifest for lodash._basevalues@^3.0.0 fetched in 246ms
147 http fetch GET 304 https://registry.npmjs.org/readable-stream 150ms (from cache)
148 http fetch GET 304 https://registry.npmjs.org/clone 143ms (from cache)
149 http fetch GET 304 https://registry.npmjs.org/xtend 148ms (from cache)
150 silly pacote range manifest for clone@^1.0.0 fetched in 148ms
151 silly pacote range manifest for readable-stream@^2.1.5 fetched in 159ms
152 http fetch GET 304 https://registry.npmjs.org/clone-stats 134ms (from cache)
153 silly pacote range manifest for resolve@^1.1.6 fetched in 7ms
154 silly pacote range manifest for xtend@~4.0.1 fetched in 162ms
155 silly pacote range manifest for clone-stats@^0.0.1 fetched in 145ms
156 http fetch GET 304 https://registry.npmjs.org/duplexer2 99ms (from cache)
157 http fetch GET 304 https://registry.npmjs.org/ansi-regex 103ms (from cache)
158 silly pacote version manifest for duplexer2@0.0.2 fetched in 104ms
159 silly pacote range manifest for ansi-regex@^2.0.0 fetched in 112ms
160 http fetch GET 304 https://registry.npmjs.org/detect-file 108ms (from cache)
161 silly pacote range manifest for detect-file@^0.1.0 fetched in 110ms
162 http fetch GET 304 https://registry.npmjs.org/is-glob 70ms (from cache)
163 silly pacote range manifest for is-glob@^2.0.1 fetched in 80ms
164 silly pacote range manifest for readable-stream@>=1.0.33-1 <1.1.0-0 fetched in 18ms
165 silly pacote range manifest for xtend@>=4.0.0 <4.1.0-0 fetched in 6ms
166 http fetch GET 304 https://registry.npmjs.org/micromatch 103ms (from cache)
167 silly pacote range manifest for clone@^0.2.0 fetched in 13ms
168 silly pacote range manifest for micromatch@^2.3.7 fetched in 115ms
169 http fetch GET 304 https://registry.npmjs.org/path-parse 106ms (from cache)
170 silly pacote range manifest for clone@^1.0.2 fetched in 14ms
171 http fetch GET 304 https://registry.npmjs.org/once 103ms (from cache)
172 http fetch GET 304 https://registry.npmjs.org/resolve-dir 126ms (from cache)
173 http fetch GET 304 https://registry.npmjs.org/expand-tilde 102ms (from cache)
174 silly pacote range manifest for once@~1.3.0 fetched in 108ms
175 silly pacote range manifest for path-parse@^1.0.5 fetched in 115ms
176 silly pacote range manifest for resolve-dir@^0.1.0 fetched in 130ms
177 silly pacote range manifest for expand-tilde@^2.0.2 fetched in 110ms
178 http fetch GET 304 https://registry.npmjs.org/is-plain-object 116ms (from cache)
179 http fetch GET 304 https://registry.npmjs.org/object.pick 107ms (from cache)
180 silly pacote range manifest for is-plain-object@^2.0.3 fetched in 126ms
181 http fetch GET 304 https://registry.npmjs.org/object.defaults 117ms (from cache)
182 silly pacote range manifest for object.pick@^1.2.0 fetched in 115ms
183 http fetch GET 304 https://registry.npmjs.org/parse-filepath 111ms (from cache)
184 silly pacote range manifest for object.defaults@^1.1.0 fetched in 122ms
185 silly pacote range manifest for parse-filepath@^1.0.1 fetched in 117ms
186 silly pacote version manifest for minimist@0.0.8 fetched in 6ms
187 http fetch GET 304 https://registry.npmjs.org/gaze 78ms (from cache)
188 http fetch GET 304 https://registry.npmjs.org/glob 60ms (from cache)
189 silly pacote range manifest for gaze@^0.5.1 fetched in 85ms
190 silly pacote range manifest for glob@^4.3.1 fetched in 65ms
191 http fetch GET 304 https://registry.npmjs.org/minimatch 59ms (from cache)
192 silly pacote range manifest for minimatch@^2.0.1 fetched in 69ms
193 warn deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
194 http fetch GET 304 https://registry.npmjs.org/glob2base 88ms (from cache)
195 silly pacote range manifest for glob2base@^0.0.12 fetched in 91ms
196 http fetch GET 304 https://registry.npmjs.org/ordered-read-streams 92ms (from cache)
197 http fetch GET 304 https://registry.npmjs.org/is-utf8 62ms (from cache)
198 silly pacote range manifest for ordered-read-streams@^0.1.0 fetched in 98ms
199 http fetch GET 304 https://registry.npmjs.org/unique-stream 94ms (from cache)
200 http fetch GET 304 https://registry.npmjs.org/natives 73ms (from cache)
201 http fetch GET 304 https://registry.npmjs.org/first-chunk-stream 70ms (from cache)
202 silly pacote range manifest for is-utf8@^0.2.0 fetched in 67ms
203 silly pacote range manifest for natives@^1.1.0 fetched in 79ms
204 silly pacote range manifest for unique-stream@^1.0.0 fetched in 102ms
205 silly pacote range manifest for first-chunk-stream@^1.0.0 fetched in 79ms
206 http fetch GET 304 https://registry.npmjs.org/lodash.isarguments 76ms (from cache)
207 silly pacote range manifest for lodash.isarguments@^3.0.0 fetched in 87ms
208 http fetch GET 304 https://registry.npmjs.org/lodash._getnative 90ms (from cache)
209 silly pacote range manifest for lodash._getnative@^3.0.0 fetched in 98ms
210 http fetch GET 304 https://registry.npmjs.org/core-util-is 64ms (from cache)
211 silly pacote range manifest for readable-stream@~1.1.9 fetched in 5ms
212 http fetch GET 304 https://registry.npmjs.org/lodash.isarray 92ms (from cache)
213 silly pacote range manifest for core-util-is@~1.0.0 fetched in 71ms
214 silly pacote range manifest for lodash.isarray@^3.0.0 fetched in 109ms
215 http fetch GET 304 https://registry.npmjs.org/inherits 89ms (from cache)
216 http fetch GET 304 https://registry.npmjs.org/isarray 88ms (from cache)
217 http fetch GET 304 https://registry.npmjs.org/process-nextick-args 84ms (from cache)
218 http fetch GET 304 https://registry.npmjs.org/safe-buffer 85ms (from cache)
219 http fetch GET 200 https://registry.npmjs.org/isarray 14ms (from cache)
220 silly pacote range manifest for inherits@~2.0.3 fetched in 97ms
221 http fetch GET 304 https://registry.npmjs.org/string_decoder 84ms (from cache)
222 silly pacote range manifest for isarray@~1.0.0 fetched in 93ms
223 silly pacote version manifest for isarray@0.0.1 fetched in 19ms
224 silly pacote range manifest for process-nextick-args@~1.0.6 fetched in 93ms
225 silly pacote range manifest for inherits@~2.0.1 fetched in 6ms
226 silly pacote range manifest for safe-buffer@~5.1.1 fetched in 95ms
227 silly pacote range manifest for string_decoder@~0.10.x fetched in 9ms
228 silly pacote range manifest for string_decoder@~1.0.3 fetched in 95ms
229 http fetch GET 304 https://registry.npmjs.org/util-deprecate 86ms (from cache)
230 silly pacote range manifest for util-deprecate@~1.0.1 fetched in 89ms
231 http fetch GET 304 https://registry.npmjs.org/lodash._root 198ms (from cache)
232 silly pacote range manifest for lodash._root@^3.0.0 fetched in 207ms
233 http fetch GET 304 https://registry.npmjs.org/is-extglob 96ms (from cache)
234 http fetch GET 304 https://registry.npmjs.org/fs-exists-sync 103ms (from cache)
235 silly pacote range manifest for fs-exists-sync@^0.1.0 fetched in 107ms
236 silly pacote range manifest for is-extglob@^1.0.0 fetched in 105ms
237 http fetch GET 304 https://registry.npmjs.org/array-unique 71ms (from cache)
238 http fetch GET 304 https://registry.npmjs.org/arr-diff 77ms (from cache)
239 http fetch GET 304 https://registry.npmjs.org/expand-brackets 74ms (from cache)
240 http fetch GET 304 https://registry.npmjs.org/braces 76ms (from cache)
241 silly pacote range manifest for array-unique@^0.2.1 fetched in 81ms
242 http fetch GET 304 https://registry.npmjs.org/filename-regex 78ms (from cache)
243 silly pacote range manifest for arr-diff@^2.0.0 fetched in 84ms
244 silly pacote range manifest for braces@^1.8.2 fetched in 83ms
245 silly pacote range manifest for expand-brackets@^0.1.4 fetched in 81ms
246 http fetch GET 304 https://registry.npmjs.org/extglob 92ms (from cache)
247 silly pacote range manifest for filename-regex@^2.0.0 fetched in 91ms
248 silly pacote range manifest for expand-tilde@^1.2.2 fetched in 16ms
249 silly pacote range manifest for extglob@^0.3.1 fetched in 102ms
250 http fetch GET 304 https://registry.npmjs.org/kind-of 95ms (from cache)
251 silly pacote range manifest for kind-of@^3.0.2 fetched in 102ms
252 http fetch GET 304 https://registry.npmjs.org/normalize-path 84ms (from cache)
253 http fetch GET 304 https://registry.npmjs.org/parse-glob 69ms (from cache)
254 silly pacote range manifest for normalize-path@^2.0.1 fetched in 90ms
255 http fetch GET 304 https://registry.npmjs.org/object.omit 79ms (from cache)
256 silly pacote range manifest for parse-glob@^3.0.4 fetched in 79ms
257 silly pacote range manifest for object.omit@^2.0.0 fetched in 88ms
258 http fetch GET 304 https://registry.npmjs.org/regex-cache 75ms (from cache)
259 silly pacote range manifest for regex-cache@^0.4.2 fetched in 87ms
260 http fetch GET 304 https://registry.npmjs.org/wrappy 89ms (from cache)
261 silly pacote range manifest for wrappy@1 fetched in 93ms
262 http fetch GET 304 https://registry.npmjs.org/isobject 83ms (from cache)
263 http fetch GET 304 https://registry.npmjs.org/isobject 80ms (from cache)
264 silly pacote range manifest for isobject@^3.0.0 fetched in 94ms
265 silly pacote range manifest for isobject@^2.1.0 fetched in 93ms
266 http fetch GET 304 https://registry.npmjs.org/global-modules 112ms (from cache)
267 http fetch GET 304 https://registry.npmjs.org/homedir-polyfill 105ms (from cache)
268 silly pacote range manifest for homedir-polyfill@^1.0.1 fetched in 110ms
269 silly pacote range manifest for global-modules@^0.2.3 fetched in 127ms
270 silly pacote range manifest for inherits@2 fetched in 9ms
271 http fetch GET 304 https://registry.npmjs.org/array-each 93ms (from cache)
272 silly pacote range manifest for once@^1.3.0 fetched in 15ms
273 silly pacote range manifest for array-each@^1.0.1 fetched in 109ms
274 http fetch GET 304 https://registry.npmjs.org/for-own 105ms (from cache)
275 silly pacote range manifest for safe-buffer@~5.1.0 fetched in 11ms
276 http fetch GET 304 https://registry.npmjs.org/array-slice 121ms (from cache)
277 silly pacote range manifest for for-own@^1.0.0 fetched in 116ms
278 http fetch GET 304 https://registry.npmjs.org/is-absolute 126ms (from cache)
279 silly pacote range manifest for is-absolute@^0.2.3 fetched in 132ms
280 silly pacote range manifest for array-slice@^1.0.0 fetched in 149ms
281 http fetch GET 304 https://registry.npmjs.org/map-cache 126ms (from cache)
282 http fetch GET 304 https://registry.npmjs.org/path-root 119ms (from cache)
283 http fetch GET 304 https://registry.npmjs.org/inflight 114ms (from cache)
284 silly pacote range manifest for map-cache@^0.2.0 fetched in 146ms
285 silly pacote range manifest for path-root@^0.1.1 fetched in 140ms
286 silly pacote range manifest for inflight@^1.0.4 fetched in 132ms
287 http fetch GET 304 https://registry.npmjs.org/globule 150ms (from cache)
288 silly pacote range manifest for os-homedir@^1.0.1 fetched in 26ms
289 silly pacote range manifest for globule@~0.1.0 fetched in 173ms
290 http fetch GET 304 https://registry.npmjs.org/brace-expansion 179ms (from cache)
291 silly pacote range manifest for brace-expansion@^1.0.0 fetched in 200ms
292 http fetch GET 304 https://registry.npmjs.org/find-index 201ms (from cache)
293 http fetch GET 304 https://registry.npmjs.org/arr-flatten 195ms (from cache)
294 silly pacote range manifest for find-index@^0.1.1 fetched in 223ms
295 http fetch GET 304 https://registry.npmjs.org/expand-range 189ms (from cache)
296 http fetch GET 304 https://registry.npmjs.org/repeat-element 163ms (from cache)
297 silly pacote range manifest for arr-flatten@^1.0.1 fetched in 201ms
298 silly pacote range manifest for is-glob@^2.0.0 fetched in 6ms
299 http fetch GET 304 https://registry.npmjs.org/preserve 174ms (from cache)
300 silly pacote range manifest for expand-range@^1.8.1 fetched in 200ms
301 silly pacote range manifest for repeat-element@^1.1.2 fetched in 174ms
302 silly pacote range manifest for for-own@^0.1.4 fetched in 10ms
303 http fetch GET 304 https://registry.npmjs.org/is-posix-bracket 154ms (from cache)
304 silly pacote version manifest for isarray@1.0.0 fetched in 5ms
305 silly pacote range manifest for preserve@^0.2.0 fetched in 183ms
306 http fetch GET 304 https://registry.npmjs.org/is-buffer 146ms (from cache)
307 http fetch GET 304 https://registry.npmjs.org/remove-trailing-separator 128ms (from cache)
308 silly pacote range manifest for is-posix-bracket@^0.1.0 fetched in 165ms
309 silly pacote range manifest for is-buffer@^1.1.5 fetched in 152ms
310 silly pacote range manifest for remove-trailing-separator@^1.0.1 fetched in 139ms
311 http fetch GET 304 https://registry.npmjs.org/glob-base 111ms (from cache)
312 silly pacote range manifest for glob-base@^0.3.0 fetched in 119ms
313 http fetch GET 304 https://registry.npmjs.org/is-dotfile 90ms (from cache)
314 silly pacote range manifest for is-dotfile@^1.0.0 fetched in 94ms
315 http fetch GET 304 https://registry.npmjs.org/is-extendable 58ms (from cache)
316 silly pacote range manifest for is-extendable@^0.1.1 fetched in 62ms
317 http fetch GET 304 https://registry.npmjs.org/is-primitive 67ms (from cache)
318 silly pacote range manifest for glob@~3.1.21 fetched in 12ms
319 http fetch GET 304 https://registry.npmjs.org/is-equal-shallow 69ms (from cache)
320 silly pacote range manifest for is-primitive@^2.0.0 fetched in 76ms
321 silly pacote range manifest for is-equal-shallow@^0.1.3 fetched in 77ms
322 silly pacote range manifest for minimatch@~0.2.11 fetched in 9ms
323 warn deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
324 http fetch GET 304 https://registry.npmjs.org/is-windows 85ms (from cache)
325 http fetch GET 304 https://registry.npmjs.org/global-prefix 93ms (from cache)
326 http fetch GET 304 https://registry.npmjs.org/for-in 80ms (from cache)
327 http fetch GET 304 https://registry.npmjs.org/parse-passwd 96ms (from cache)
328 silly pacote range manifest for is-windows@^0.2.0 fetched in 89ms
329 silly pacote range manifest for for-in@^1.0.1 fetched in 86ms
330 silly pacote range manifest for parse-passwd@^1.0.0 fetched in 99ms
331 silly pacote range manifest for global-prefix@^0.1.4 fetched in 100ms
332 http fetch GET 304 https://registry.npmjs.org/is-relative 94ms (from cache)
333 silly pacote range manifest for inherits@1 fetched in 11ms
334 silly pacote range manifest for graceful-fs@~1.2.0 fetched in 11ms
335 warn deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
336 silly pacote range manifest for is-relative@^0.2.1 fetched in 111ms
337 http fetch GET 304 https://registry.npmjs.org/path-root-regex 103ms (from cache)
338 silly pacote range manifest for homedir-polyfill@^1.0.0 fetched in 16ms
339 http fetch GET 304 https://registry.npmjs.org/lodash 102ms (from cache)
340 silly pacote range manifest for path-root-regex@^0.1.0 fetched in 118ms
341 silly pacote range manifest for lodash@~1.0.1 fetched in 112ms
342 http fetch GET 304 https://registry.npmjs.org/concat-map 86ms (from cache)
343 http fetch GET 304 https://registry.npmjs.org/balanced-match 87ms (from cache)
344 silly pacote version manifest for concat-map@0.0.1 fetched in 89ms
345 silly pacote range manifest for balanced-match@^1.0.0 fetched in 90ms
346 http fetch GET 304 https://registry.npmjs.org/fill-range 91ms (from cache)
347 http fetch GET 304 https://registry.npmjs.org/glob-parent 71ms (from cache)
348 silly pacote range manifest for fill-range@^2.1.0 fetched in 101ms
349 silly pacote range manifest for glob-parent@^2.0.0 fetched in 76ms
350 http fetch GET 304 https://registry.npmjs.org/lru-cache 76ms (from cache)
351 silly pacote range manifest for isobject@^2.0.0 fetched in 6ms
352 silly pacote range manifest for lru-cache@2 fetched in 82ms
353 http fetch GET 304 https://registry.npmjs.org/ini 64ms (from cache)
354 http fetch GET 304 https://registry.npmjs.org/which 64ms (from cache)
355 silly pacote range manifest for ini@^1.3.4 fetched in 67ms
356 silly pacote range manifest for which@^1.2.12 fetched in 65ms
357 http fetch GET 304 https://registry.npmjs.org/sigmund 90ms (from cache)
358 http fetch GET 304 https://registry.npmjs.org/is-unc-path 57ms (from cache)
359 silly pacote range manifest for sigmund@~1.0.0 fetched in 93ms
360 silly pacote range manifest for is-unc-path@^0.1.1 fetched in 64ms
361 http fetch GET 304 https://registry.npmjs.org/repeat-string 49ms (from cache)
362 silly pacote range manifest for repeat-string@^1.5.2 fetched in 52ms
363 http fetch GET 304 https://registry.npmjs.org/is-number 54ms (from cache)
364 http fetch GET 304 https://registry.npmjs.org/randomatic 56ms (from cache)
365 silly pacote range manifest for randomatic@^1.1.3 fetched in 58ms
366 silly pacote range manifest for is-number@^2.1.0 fetched in 62ms
367 http fetch GET 304 https://registry.npmjs.org/isexe 41ms (from cache)
368 silly pacote range manifest for isexe@^2.0.0 fetched in 43ms
369 silly pacote range manifest for kind-of@^4.0.0 fetched in 6ms
370 silly pacote range manifest for is-number@^3.0.0 fetched in 7ms
371 http fetch GET 304 https://registry.npmjs.org/unc-path-regex 58ms (from cache)
372 silly pacote range manifest for unc-path-regex@^0.1.0 fetched in 68ms
373 error cb() never called!
374 error This is an error with npm itself. Please report this error at:
375 error <https://github.com/npm/npm/issues>
```

Hope this helps.

**Comment by fbnlsr** [comment]
Closing. Updating npm fixed the issue.
