### ISSUE TITLE
npm install crashes if a devDependency package name contains a ')'

### ISSUE THREAD

**Issue by jdiehl** [npm/npm#17701]
#### I'm opening this issue because:

  - npm is crashing.

#### What's going wrong?

Since npm 5.1.0 when a devDependecy contains a ')' character, `npm install`crashes with the following error message: `npm ERR! Invalid regular expression: /^[package-name-containing-)]@/: Unmatched ')'`.

This error does not occur with npm 5.0.4.

#### How can the CLI team reproduce the problem?

1. Create an empty npm project: `npm init -y`
2. Add a dev dependency that contains a ')' in the name: `npm install --save-dev "@-)/utils"`
3. Run: `npm install`

### supporting information:

 - `npm -v` prints: 5.1.0
 - `node -v` prints: v8.1.2
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: macOS
 - Network issues:
   - Geographic location where npm was run: None
 - Container: None

**Comment by jdiehl** [comment]
Still happening with nom 5.2.0

**Comment by jdiehl** [comment]
```
Invalid regular expression: /^@-)/utils@/: Unmatched ')'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jdiehl/.npm/_logs/2017-07-11T20_08_29_151Z-debug.log
```

**Comment by jdiehl** [comment]
npm-debug.log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/8.1.3/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install' ]
2 info using npm@5.2.0
3 info using node@v8.1.3
4 verbose npm-session bc523da8bfd4693f
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall x@1.0.0
7 info lifecycle x@1.0.0~preinstall: x@1.0.0
8 silly install loadCurrentTree
9 silly install readLocalPackageData
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 silly install loadShrinkwrap
13 silly install loadAllDepsIntoIdealTree
14 verbose stack SyntaxError: Invalid regular expression: /^@-)/utils@/: Unmatched ')'
14 verbose stack     at RegExp (<anonymous>)
14 verbose stack     at doesChildVersionMatch (/usr/local/lib/node_modules/npm/lib/install/deps.js:66:80)
14 verbose stack     at isDep (/usr/local/lib/node_modules/npm/lib/install/deps.js:139:27)
14 verbose stack     at addRequiredDep (/usr/local/lib/node_modules/npm/lib/install/deps.js:151:13)
14 verbose stack     at resolveWithExistingModule (/usr/local/lib/node_modules/npm/lib/install/deps.js:543:3)
14 verbose stack     at addDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:528:5)
14 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/deps.js:482:5
14 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
14 verbose stack     at Array.forEach (native)
14 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
14 verbose stack     at Array.forEach (native)
14 verbose stack     at asyncMap (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
14 verbose stack     at exports.loadDevDeps (/usr/local/lib/node_modules/npm/lib/install/deps.js:476:3)
14 verbose stack     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
14 verbose stack     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
14 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
15 verbose cwd /Users/jdiehl/Desktop/x
16 verbose Darwin 16.6.0
17 verbose argv "/usr/local/Cellar/node/8.1.3/bin/node" "/usr/local/bin/npm" "install"
18 verbose node v8.1.3
19 verbose npm  v5.2.0
20 error Invalid regular expression: /^@-)/utils@/: Unmatched ')'
21 verbose exit [ 1, true ]
```

**Comment by jdiehl** [comment]
See #17729

**Comment by jdiehl** [comment]
Can someone please take a look at this? This bug is breaking my build chains and the fix is incredibly simple (1 line must be changed). Thank you!
