### ISSUE TITLE
npm install gives problem

### ISSUE THREAD

**Issue by codetoaj** [npm/npm#17736]
#### I'm opening this issue because:

  - [*] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
When i give "npm install" i am getting following error
npm ERR! path /home/shadmin/.npm/_cacache/tmp/git-clone-58219eac/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/home/shadmin/.npm/_cacache/tmp/git-clone-58219eac/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/shadmin/.npm/_logs/2017-07-12T05_31_38_311Z-debug.log

**Comment by yipcma** [comment]
same issue here, when npm i -S ghuser/somepublicrepo

**Comment by campsjos** [comment]
Look at the log file pointed by npm, `/home/shadmin/.npm/_logs/2017-07-12T05_31_38_311Z-debug.log` in your case.

In mine I saw this line wich was the first one indicating that there was an error:
`2928 silly fetchPackageMetaData error for cordova-plugin-ios-keychain@git+https://github.com/shazron/KeychainPlugin.git ENOENT: no such file or directory, open '/Users/campsjos/.npm/_cacache/tmp/git-clone-8e3bfc91/package.json'`
As the package causing this error was cordova-plugin-ios-keychain, I just removed it from my project package.json file and now `npm install` runs fine.

**Comment by msimerson** [comment]
There's something strange going on here. When I attempt to install a NPM module from git it fails with the same error:

````
[root@haraka /]# npm install -g haraka/Haraka
npm ERR! code 1
npm ERR! Command failed: /usr/local/bin/git clone --depth=1 -q -b master git://github.com/haraka/Haraka.git /root/.npm/_cacache/tmp/git-clone-a412fb5a
npm ERR! /root/.npm/_cacache/tmp/git-clone-a412fb5a/.git: Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-08-22T21_02_44_398Z-debug.log
[root@haraka /]# cat /root/.npm/_logs/2017-08-22T21_02_44_398Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'haraka/Haraka' ]
2 info using npm@5.3.0
3 info using node@v8.4.0
4 verbose npm-session 51b352bc35426351
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData error for github:haraka/Haraka Command failed: /usr/local/bin/git clone --depth=1 -q -b master git://github.com/haraka/Haraka.git /root/.npm/_cacache/tmp/git-clone-a412fb5a
7 silly fetchPackageMetaData /root/.npm/_cacache/tmp/git-clone-a412fb5a/.git: Permission denied
8 verbose stack Error: Command failed: /usr/local/bin/git clone --depth=1 -q -b master git://github.com/haraka/Haraka.git /root/.npm/_cacache/tmp/git-clone-a412fb5a
8 verbose stack /root/.npm/_cacache/tmp/git-clone-a412fb5a/.git: Permission denied
8 verbose stack
8 verbose stack     at ChildProcess.exithandler (child_process.js:270:12)
8 verbose stack     at emitTwo (events.js:125:13)
8 verbose stack     at ChildProcess.emit (events.js:213:7)
8 verbose stack     at maybeClose (internal/child_process.js:927:16)
8 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
9 verbose cwd /
10 verbose FreeBSD 11.1-RELEASE-p1
11 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "haraka/Haraka"
12 verbose node v8.4.0
13 verbose npm  v5.3.0
14 error code 1
15 error Command failed: /usr/local/bin/git clone --depth=1 -q -b master git://github.com/haraka/Haraka.git /root/.npm/_cacache/tmp/git-clone-a412fb5a
15 error /root/.npm/_cacache/tmp/git-clone-a412fb5a/.git: Permission denied
16 verbose exit [ 1, true ]
````

But I can run that exact same command that npm choked on and it succeeds:

````
[root@haraka /]# /usr/local/bin/git clone --depth=1 -q -b master git://github.com/haraka/Haraka.git /root/.npm/_cacache/tmp/git-clone-a412fb5a
[root@haraka /]# ls /root/.npm/_cacache/tmp/git-clone-a412fb5a
.editorconfig		TODO			dsn.js			plugins
.eslintrc.json		appveyor.yml		haraka.js		plugins.js
.git			attachment_stream.js	haraka.sh		rfc1869.js
.github			bin			host_pool.js		run_tests
.gitignore		chunkemitter.js		http			server.js
.gitmodules		config			line_socket.js		smtp_client.js
.travis.yml		config.js		logger.js		spf.js
Changes.md		configfile.js		mailbody.js		tests
Dockerfile		connection.js		mailheader.js		timer_queue.js
LICENSE			contrib			messagestream.js	tls_socket.js
Plugins.md		dkim.js			outbound		transaction.js
README.md		docs			package.json
````

So it seems that npm is doing something "not right" in there somewhere.
