### ISSUE TITLE
node is not updating

### ISSUE THREAD

**Issue by jstamb02** [npm/npm#17764]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

Node.js won't update to latest version from 5.5

#### How can the CLI team reproduce the problem?

Please see: https://gist.github.com/jstamb02/ed480c90a227b5d15a9775415964b3df
and https://gist.github.com/jstamb02/3e3af0ac3aeed945fff27171dec40b77

### supporting information:

 - `npm -v` prints: 5.0.0
 - `node -v` prints: v5.5.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: OS X
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [X ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment]
Does this also occur with the latest version of `npm`?

**Comment by jstamb02** [comment]
Attempts to update npm also give me errors.
Here's the print-out: 
Unhandled rejection TypeError: base64 is not a functionng node@v5.5.0
    at Function.from (native)
    at Function.from (native)
    at bufFrom (/usr/local/lib/node_modules/npm/node_modules/ssri/index.js:337:31)
    at Hash.hexDigest (/usr/local/lib/node_modules/npm/node_modules/ssri/index.js:34:27)
    at contentPath (/usr/local/lib/node_modules/npm/node_modules/cacache/lib/content/path.js:20:31)
    at moveToDestination (/usr/local/lib/node_modules/npm/node_modules/cacache/lib/content/write.js:131:23)
    at /usr/local/lib/node_modules/npm/node_modules/cacache/lib/content/write.js:39:7
    at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:638:18)
    at /usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/nodeback.js:42:21
    at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:99:16
    at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:43:10

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Jeni/.npm/_logs/2017-07-13T15_16_25_508Z-debug.log

https://gist.github.com/jstamb02/22da65e02ff951b47fb5ec280cd06779

**Comment by jstamb02** [comment]
I'm running npm 5.0.0
