### ISSUE TITLE
Cannot install angular/cli via npm

### ISSUE THREAD

**Issue by m-bobrowski** [npm/npm#17788]
node version 8.1.4
platform: Windows 10 64-bit

There is no possibility to install angular cli using command "npm install -g (at)angular/cli "
After rollback to node 6.11.1 it works without any issue

Some log data:

11867 verbose stack FetchError: request to https://registry.npmjs.org/send/-/send-0.15.3.tgz failed, reason: read ECONNRESET
11867 verbose stack at ClientRequest.req.on.err (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\node-fetch-npm\src\index.js:68:14)
11867 verbose stack at emitOne (events.js:115:13)
11867 verbose stack at ClientRequest.emit (events.js:210:7)
11867 verbose stack at TLSSocket.socketErrorListener (_http_client.js:400:9)
11867 verbose stack at emitOne (events.js:115:13)
11867 verbose stack at TLSSocket.emit (events.js:210:7)
11867 verbose stack at emitErrorNT (internal/streams/destroy.js:62:8)
11867 verbose stack at _combinedTickCallback (internal/process/next_tick.js:102:11)
11867 verbose stack at process._tickCallback (internal/process/next_tick.js:161:9)
11868 verbose cwd C:
11869 verbose Windows_NT 10.0.15063
11870 verbose argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "-g" ""
11871 verbose node v8.1.4
11872 verbose npm v5.0.3
11873 error code ECONNRESET
11874 error errno ECONNRESET
11875 error network request to https://registry.npmjs.org/send/-/send-0.15.3.tgz failed, reason: read ECONNRESET
11876 error network This is a problem related to network connectivity.
11876 error network In most cases you are behind a proxy or have bad network settings.
11876 error network
11876 error network If you are behind a proxy, please make sure that the
11876 error network 'proxy' config is set properly. See: 'npm help config'
11877 verbose exit [ 1, true ]

**Comment by kevinpeno** [comment]
I am unable to reproduce this issue using `node v8.1.4 (npm v5.0.3)`. I've also tried using the latest v8 node and latest npm (`node v8.9.4 (npm 5.8.0)`). Based on your log data there may have been a network issue that has since been resolved.

Can you confirm that you are still having this issue?
