### ISSUE TITLE
`npm unpublish` is broken in case of deleting entire project

### ISSUE THREAD

**Issue by RomanLubushkin** [npm/npm#17793]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Hi!
I have published a project with a wrong name and now trying to delete it, but `npm unpublish` command doesn't work, it gives an error and project I'm trying to delete is still searchable.
https://www.npmjs.com/package/collaborativejs 
```
$ npm unpublish collaborativejs --force
>> Registry returned 400 for DELETE on https://registry.npmjs.org/collaborativejs/-rev/10-2c4129199995433296f31e23d86c8921
```

#### How can the CLI team reproduce the problem?
[npm-debug.log](https://gist.github.com/RomanLubushkin/d40f9a8b94b30cbf025dbb28ece2df29)

### supporting information:

 - `npm -v` prints: 5.3.0
 - `node -v` prints: v8.1.4
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: OS X/macOS
 - Network issues:
   - Geographic location where npm was run:Russia, Irkutsk
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by d3x0r** [comment]
Also broken for me.

```
36 verbose request invalidating C:\Users\Panther\AppData\Roaming\npm-cache\registry.npmjs.org\gun.db on DELETE
37 verbose stack Error: Registry returned 400 for DELETE on https://registry.npmjs.org/gun.db/-rev/9-9e2087811e2bfb0a965b8f416afea780
37 verbose stack     at makeError (C:\Users\Panther\AppData\Roaming\npm\node_modules\npm\node_modules\npm-registry-client\lib\request.js:302:12)
37 verbose stack     at CachingRegistryClient.<anonymous> (C:\Users\Panther\AppData\Roaming\npm\node_modules\npm\node_modules\npm-registry-client\lib\request.js:280:14)
37 verbose stack     at Request._callback (C:\Users\Panther\AppData\Roaming\npm\node_modules\npm\node_modules\npm-registry-client\lib\request.js:210:14)
37 verbose stack     at Request.self.callback (C:\Users\Panther\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.js:186:22)
37 verbose stack     at emitTwo (events.js:125:13)
37 verbose stack     at Request.emit (events.js:213:7)
37 verbose stack     at Request.<anonymous> (C:\Users\Panther\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.js:1081:10)
37 verbose stack     at emitOne (events.js:115:13)
37 verbose stack     at Request.emit (events.js:210:7)
37 verbose stack     at IncomingMessage.<anonymous> (C:\Users\Panther\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.js:1001:12)
38 verbose statusCode 400
39 verbose pkgid gun.db
40 verbose cwd M:\javascript\gun.db
41 error Windows_NT 6.1.7601
42 error argv "H:\\dev2\\nodejs\\node.exe" "C:\\Users\\Panther\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "unpublish" "gun.db" "--force"
43 error node v8.2.1
44 error npm  v4.0.5
45 error code E400
46 error Registry returned 400 for DELETE on https://registry.npmjs.org/gun.db/-rev/9-9e2087811e2bfb0a965b8f416afea780
47 error If you need help, you may report this error at:
47 error     <https://github.com/npm/npm/issues>
48 verbose exit [ 1, true ]
```
same this is an older project... 

actually this now... tried to reverse and publish a new version delete the oldest version; was doing single verison unpublishes backwards, and the broken state was left at old broken version... wanted it to at least be broken in a usable state.
```
 Registry returned 400 for DELETE on https://registry.npmjs.org/gun.db/-rev/11-320b4a4620e84273cea6cf2583462fe3
```
