### ISSUE TITLE
module doesn't install correct,miss sub dependent.

### ISSUE THREAD

**Issue by kisnows** [npm/npm#17805]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
The sub dependent didn't install.
`load-json-file` is some module's dependent of my project's dependencies module, It has a `strip-bom` module as his dependent.
![image](https://user-images.githubusercontent.com/9394000/28256753-d2835f0e-6af7-11e7-9f93-c94c10e5373b.png)

**strip-bom package.json**
```json
{
  "_requested": {
    "type": "version",
    "registry": true,
    "raw": "strip-bom@2.0.0",
    "name": "strip-bom",
    "escapedName": "strip-bom",
    "rawSpec": "2.0.0",
    "saveSpec": null,
    "fetchSpec": "2.0.0"
  },
  "_requiredBy": [],
  "_resolved": "https://registry.npmjs.org/strip-bom/-/strip-bom-2.0.0.tgz",
  "_spec": "2.0.0",
  "_where": "D:\\quhua",
  "author": {
    "name": "Sindre Sorhus",
    "email": "sindresorhus@gmail.com",
    "url": "sindresorhus.com"
  },
  "bugs": {
    "url": "https://github.com/sindresorhus/strip-bom/issues"
  },
  "dependencies": {
    "is-utf8": "^0.2.0"
  },
  "description": "Strip UTF-8 byte order mark (BOM) from a string/buffer",
  "devDependencies": {
    "mocha": "*"
  },

```
The key of dependencies has a module named **`is-utf8`**, but this mudule is **doesn't installed**.
so, the script in strip-bom\index.js will error when execute:
```js
'use strict';
var isUtf8 = require('is-utf8');

module.exports = function (x) {
	// Catches EFBBBF (UTF-8 BOM) because the buffer-to-string
	// conversion translates it to FEFF (UTF-16 BOM)
	if (typeof x === 'string' && x.charCodeAt(0) === 0xFEFF) {
		return x.slice(1);
	}

	if (Buffer.isBuffer(x) && isUtf8(x) &&
		x[0] === 0xEF && x[1] === 0xBB && x[2] === 0xBF) {
		return x.slice(3);
	}

	return x;
};
```
```bash
module.js:487
    throw err;
    ^

Error: Cannot find module 'is-utf8'
    at Function.Module._resolveFilename (module.js:485
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\quhua\node_modules\load-
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
```
#### How can the CLI team reproduce the problem?
Any module has a nest sub module should have this problem, such as this module `load-json-file`.

### supporting information:

 - `npm -v` prints: 5.0.3
 - `node -v` prints: 8.1.4
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?: Windows
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [x] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kisnows** [comment]
it seems to be a problem of `package-lock.json` file's error.
I delete this package-lock.json file under my project, and delete the node_modules folder, and reinstall the modules.
And then, the `is-utf8` module is installed correctly.
