### ISSUE TITLE
[Bug] Cannot fetch from registry

### ISSUE THREAD

**Issue by hjkatz** [npm/npm#17841]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

`npm --verbose view npm version` is producing the output

```
# npm --verbose view npm version
npm info it worked if it ends with ok
npm verb cli [ '/usr/bin/node',
npm verb cli   '/usr/bin/npm',
npm verb cli   '--verbose',
npm verb cli   'view',
npm verb cli   'npm',
npm verb cli   'version' ]
npm info using npm@3.10.10
npm info using node@v6.10.3
npm verb request uri https://registry.npmjs.org/npm
npm verb request no auth needed
npm info attempt registry request try #1 at 4:05:56 PM
npm verb request id ec19ccbe7c928b7c
npm http request GET https://registry.npmjs.org/npm
npm http 200 https://registry.npmjs.org/npm
npm verb headers { 'nginx/1.10.1application/jsonfri, 14 jul 2017 05:18:23 gmtw/"5968541f-659cf6"gzipmax-age=300547178bytestue, 18 jul 2017 20:05:56 gmt1.1 varnish55keep-alivecache-atl6224-atlhit1s1500408357.628509,vs0,ve2accept-encoding, accept': '' }
npm verb stack Error: failed to fetch from registry: https://registry.npmjs.org/npm
npm verb stack     at /usr/lib/node_modules/npm/lib/cache/caching-client.js:164:27
npm verb stack     at /usr/lib/node_modules/npm/lib/cache/caching-client.js:53:8
npm verb stack     at f (/usr/lib/node_modules/npm/node_modules.bundled/once/once.js:25:25)
npm verb stack     at /usr/lib/node_modules/npm/node_modules.bundled/npm-registry-client/lib/request.js:76:16
npm verb stack     at /usr/lib/node_modules/npm/node_modules.bundled/npm-registry-client/lib/request.js:103:12
npm verb stack     at f (/usr/lib/node_modules/npm/node_modules.bundled/once/once.js:25:25)
npm verb stack     at CachingRegistryClient.<anonymous> (/usr/lib/node_modules/npm/node_modules.bundled/npm-registry-client/lib/request.js:297:12)
npm verb stack     at Request._callback (/usr/lib/node_modules/npm/node_modules.bundled/npm-registry-client/lib/request.js:210:14)
npm verb stack     at Request.self.callback (/usr/lib/node_modules/npm/node_modules.bundled/request/request.js:187:22)
npm verb stack     at emitTwo (events.js:106:13)
npm verb cwd /usr/lib/node_modules
npm ERR! Linux 3.10.0-327.36.3.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "--verbose" "view" "npm" "version"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10

npm ERR! failed to fetch from registry: https://registry.npmjs.org/npm
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm verb exit [ 1, true ]

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/lib/node_modules/npm-debug.log
```

I can successfully `ping registry.npmjs.org` and `curl https://registry.npmjs.org/npm`.

### supporting information:

 - `npm -v` prints: 3.10.10
 - `node -v` prints: v6.10.3
 - `npm config get registry` prints: `https://registry.npmjs.org/`
 - Windows, OS X/macOS, or Linux?: CentOS 7 
 - `uname -a`: `Linux <hostname> 3.10.0-327.36.3.el7.x86_64 #1 SMP Mon Oct 24 16:09:20 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`
 - `cat /etc/*-release`:
    ```
    CentOS Linux release 7.2.1511 (Core) 
    NAME="CentOS Linux"
    VERSION="7 (Core)"
    ID="centos"
    ID_LIKE="rhel fedora"
    VERSION_ID="7"
    PRETTY_NAME="CentOS Linux 7 (Core)"
    ANSI_COLOR="0;31"
    CPE_NAME="cpe:/o:centos:centos:7"
    HOME_URL="https://www.centos.org/"
    BUG_REPORT_URL="https://bugs.centos.org/"
    
    CENTOS_MANTISBT_PROJECT="CentOS-7"
    CENTOS_MANTISBT_PROJECT_VERSION="7"
    REDHAT_SUPPORT_PRODUCT="centos"
    REDHAT_SUPPORT_PRODUCT_VERSION="7"
    
    CentOS Linux release 7.2.1511 (Core) 
    CentOS Linux release 7.2.1511 (Core) 
    ```
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by BaNkIck** [comment]
Same problem here with the exact same version of npm and nodejs but a bit older CentOS (7.1).

I installed npm from the epel repository:

```
$ yum list npm nodejs | expand
Loaded plugins: fastestmirror, replace
Loading mirror speeds from cached hostfile
 * base: ftp.rediris.es
 * epel: fr.mirror.babylon.network
 * extras: mirror.tedra.es
 * ius: mirrors.ircam.fr
 * remi: fr.mirror.babylon.network
 * remi-safe: fr.mirror.babylon.network
 * updates: ftp.rediris.es
Installed Packages
nodejs.x86_64                   1:6.10.3-1.el7                             @epel
npm.x86_64                      1:3.10.10-1.6.10.3.1.el7                   @epel
```

Here is the output of the `npm install`:

```
$ npm install --production -ddd
npm info it worked if it ends with ok
npm verb cli [ '/usr/bin/node', '/bin/npm', 'install', '--production', '-ddd' ]
npm info using npm@3.10.10
npm info using node@v6.10.3
npm sill loadCurrentTree Starting
npm sill install loadCurrentTree
npm sill install readLocalPackageData
npm sill install normalizeTree
npm sill loadCurrentTree Finishing
npm sill loadIdealTree Starting
npm sill install loadIdealTree
npm sill cloneCurrentTree Starting
npm sill install cloneCurrentTreeToIdealTree
npm sill cloneCurrentTree Finishing
npm sill loadShrinkwrap Starting
npm sill install loadShrinkwrap
npm sill loadShrinkwrap Finishing
npm sill loadAllDepsIntoIdealTree Starting
npm sill install loadAllDepsIntoIdealTree
npm sill fetchNamedPackageData gulp
npm sill mapToRegistry name gulp
npm sill mapToRegistry using default registry
npm sill mapToRegistry registry https://registry.npmjs.org/
npm sill mapToRegistry data Result {
npm sill mapToRegistry   raw: 'gulp',
npm sill mapToRegistry   scope: null,
npm sill mapToRegistry   escapedName: 'gulp',
npm sill mapToRegistry   name: 'gulp',
npm sill mapToRegistry   rawSpec: '',
npm sill mapToRegistry   spec: 'latest',
npm sill mapToRegistry   type: 'tag' }
npm sill mapToRegistry uri https://registry.npmjs.org/gulp
npm sill fetchNamedPackageData laravel-elixir
npm sill mapToRegistry name laravel-elixir
npm sill mapToRegistry using default registry
npm sill mapToRegistry registry https://registry.npmjs.org/
npm sill mapToRegistry data Result {
npm sill mapToRegistry   raw: 'laravel-elixir',
npm sill mapToRegistry   scope: null,
npm sill mapToRegistry   escapedName: 'laravel-elixir',
npm sill mapToRegistry   name: 'laravel-elixir',
npm sill mapToRegistry   rawSpec: '',
npm sill mapToRegistry   spec: 'latest',
npm sill mapToRegistry   type: 'tag' }
npm sill mapToRegistry uri https://registry.npmjs.org/laravel-elixir
npm verb request uri https://registry.npmjs.org/gulp
npm verb request no auth needed
npm info attempt registry request try #1 at 10:46:45 AM
npm verb request id 443906c0873efecf
npm http request GET https://registry.npmjs.org/gulp
npm verb request uri https://registry.npmjs.org/laravel-elixir
npm verb request no auth needed
npm info attempt registry request try #1 at 10:46:45 AM
npm http request GET https://registry.npmjs.org/laravel-elixir
npm http 200 https://registry.npmjs.org/gulp
npm verb headers { 'nginx/1.10.1application/jsonwed, 19 jul 2017 17:37:15 gmtw/"596f98cb-1d6ca"gzipmax-age=30018012bytesthu, 20 jul 2017 08:46:45 gmt1.1 varnish82keep-alivecache-cdg8724-cdghit2s1500540406.705900,vs0,ve0accept-encoding, accept': '' }
npm sill get cb [ 200,
npm sill get   { 'nginx/1.10.1application/jsonwed, 19 jul 2017 17:37:15 gmtw/"596f98cb-1d6ca"gzipmax-age=30018012bytesthu, 20 jul 2017 08:46:45 gmt1.1 varnish82keep-alivecache-cdg8724-cdghit2s1500540406.705900,vs0,ve0accept-encoding, accept': '' } ]
npm sill fetchPackageMetaData Error: failed to fetch from registry: https://registry.npmjs.org/gulp
npm sill fetchPackageMetaData     at /usr/lib/node_modules/npm/lib/cache/caching-client.js:164:27
npm sill fetchPackageMetaData     at /usr/lib/node_modules/npm/lib/cache/caching-client.js:53:8
npm sill fetchPackageMetaData     at f (/usr/lib/node_modules/npm/node_modules.bundled/once/once.js:25:25)
npm sill fetchPackageMetaData     at /usr/lib/node_modules/npm/node_modules.bundled/npm-registry-client/lib/request.js:76:16
npm sill fetchPackageMetaData     at /usr/lib/node_modules/npm/node_modules.bundled/npm-registry-client/lib/request.js:103:12
npm sill fetchPackageMetaData     at f (/usr/lib/node_modules/npm/node_modules.bundled/once/once.js:25:25)
npm sill fetchPackageMetaData     at CachingRegistryClient.<anonymous> (/usr/lib/node_modules/npm/node_modules.bundled/npm-registry-client/lib/request.js:297:12)
npm sill fetchPackageMetaData     at Request._callback (/usr/lib/node_modules/npm/node_modules.bundled/npm-registry-client/lib/request.js:210:14)
npm sill fetchPackageMetaData     at Request.self.callback (/usr/lib/node_modules/npm/node_modules.bundled/request/request.js:187:22)
npm sill fetchPackageMetaData     at emitTwo (events.js:106:13)
npm sill fetchPackageMetaData  error for gulp@^3.8.8 Error: failed to fetch from registry: https://registry.npmjs.org/gulp
npm sill fetchPackageMetaData     at /usr/lib/node_modules/npm/lib/cache/caching-client.js:164:27
npm sill fetchPackageMetaData     at /usr/lib/node_modules/npm/lib/cache/caching-client.js:53:8
npm sill fetchPackageMetaData     at f (/usr/lib/node_modules/npm/node_modules.bundled/once/once.js:25:25)
npm sill fetchPackageMetaData     at /usr/lib/node_modules/npm/node_modules.bundled/npm-registry-client/lib/request.js:76:16
npm sill fetchPackageMetaData     at /usr/lib/node_modules/npm/node_modules.bundled/npm-registry-client/lib/request.js:103:12
npm sill fetchPackageMetaData     at f (/usr/lib/node_modules/npm/node_modules.bundled/once/once.js:25:25)
npm sill fetchPackageMetaData     at CachingRegistryClient.<anonymous> (/usr/lib/node_modules/npm/node_modules.bundled/npm-registry-client/lib/request.js:297:12)
npm sill fetchPackageMetaData     at Request._callback (/usr/lib/node_modules/npm/node_modules.bundled/npm-registry-client/lib/request.js:210:14)
npm sill fetchPackageMetaData     at Request.self.callback (/usr/lib/node_modules/npm/node_modules.bundled/request/request.js:187:22)
npm sill fetchPackageMetaData     at emitTwo (events.js:106:13)
npm http 200 https://registry.npmjs.org/laravel-elixir
npm verb headers { 'nginx/1.10.1application/jsontue, 16 may 2017 07:43:44 gmtw/"591aadb0-50837"gzipmax-age=30020425bytesthu, 20 jul 2017 08:46:45 gmt1.1 varnish5keep-alivecache-cdg8731-cdghit1s1500540406.700318,vs0,ve1accept-encoding, accept': '' }
npm sill get cb [ 200,
npm sill get   { 'nginx/1.10.1application/jsontue, 16 may 2017 07:43:44 gmtw/"591aadb0-50837"gzipmax-age=30020425bytesthu, 20 jul 2017 08:46:45 gmt1.1 varnish5keep-alivecache-cdg8731-cdghit1s1500540406.700318,vs0,ve1accept-encoding, accept': '' } ]
npm sill fetchPackageMetaData Error: failed to fetch from registry: https://registry.npmjs.org/laravel-elixir
npm sill fetchPackageMetaData     at /usr/lib/node_modules/npm/lib/cache/caching-client.js:164:27
npm sill fetchPackageMetaData     at /usr/lib/node_modules/npm/lib/cache/caching-client.js:53:8
npm sill fetchPackageMetaData     at f (/usr/lib/node_modules/npm/node_modules.bundled/once/once.js:25:25)
npm sill fetchPackageMetaData     at /usr/lib/node_modules/npm/node_modules.bundled/npm-registry-client/lib/request.js:76:16
npm sill fetchPackageMetaData     at /usr/lib/node_modules/npm/node_modules.bundled/npm-registry-client/lib/request.js:103:12
npm sill fetchPackageMetaData     at f (/usr/lib/node_modules/npm/node_modules.bundled/once/once.js:25:25)
npm sill fetchPackageMetaData     at CachingRegistryClient.<anonymous> (/usr/lib/node_modules/npm/node_modules.bundled/npm-registry-client/lib/request.js:297:12)
npm sill fetchPackageMetaData     at Request._callback (/usr/lib/node_modules/npm/node_modules.bundled/npm-registry-client/lib/request.js:210:14)
npm sill fetchPackageMetaData     at Request.self.callback (/usr/lib/node_modules/npm/node_modules.bundled/request/request.js:187:22)
npm sill fetchPackageMetaData     at emitTwo (events.js:106:13)
npm sill fetchPackageMetaData  error for laravel-elixir@^4.0.0 Error: failed to fetch from registry: https://registry.npmjs.org/laravel-elixir
npm sill fetchPackageMetaData     at /usr/lib/node_modules/npm/lib/cache/caching-client.js:164:27
npm sill fetchPackageMetaData     at /usr/lib/node_modules/npm/lib/cache/caching-client.js:53:8
npm sill fetchPackageMetaData     at f (/usr/lib/node_modules/npm/node_modules.bundled/once/once.js:25:25)
npm sill fetchPackageMetaData     at /usr/lib/node_modules/npm/node_modules.bundled/npm-registry-client/lib/request.js:76:16
npm sill fetchPackageMetaData     at /usr/lib/node_modules/npm/node_modules.bundled/npm-registry-client/lib/request.js:103:12
npm sill fetchPackageMetaData     at f (/usr/lib/node_modules/npm/node_modules.bundled/once/once.js:25:25)
npm sill fetchPackageMetaData     at CachingRegistryClient.<anonymous> (/usr/lib/node_modules/npm/node_modules.bundled/npm-registry-client/lib/request.js:297:12)
npm sill fetchPackageMetaData     at Request._callback (/usr/lib/node_modules/npm/node_modules.bundled/npm-registry-client/lib/request.js:210:14)
npm sill fetchPackageMetaData     at Request.self.callback (/usr/lib/node_modules/npm/node_modules.bundled/request/request.js:187:22)
npm sill fetchPackageMetaData     at emitTwo (events.js:106:13)
npm sill rollbackFailedOptional Starting
npm sill rollbackFailedOptional Finishing
npm sill runTopLevelLifecycles Finishing
npm sill install printInstalled
npm verb stack Error: failed to fetch from registry: https://registry.npmjs.org/gulp
npm verb stack     at /usr/lib/node_modules/npm/lib/cache/caching-client.js:164:27
npm verb stack     at /usr/lib/node_modules/npm/lib/cache/caching-client.js:53:8
npm verb stack     at f (/usr/lib/node_modules/npm/node_modules.bundled/once/once.js:25:25)
npm verb stack     at /usr/lib/node_modules/npm/node_modules.bundled/npm-registry-client/lib/request.js:76:16
npm verb stack     at /usr/lib/node_modules/npm/node_modules.bundled/npm-registry-client/lib/request.js:103:12
npm verb stack     at f (/usr/lib/node_modules/npm/node_modules.bundled/once/once.js:25:25)
npm verb stack     at CachingRegistryClient.<anonymous> (/usr/lib/node_modules/npm/node_modules.bundled/npm-registry-client/lib/request.js:297:12)
npm verb stack     at Request._callback (/usr/lib/node_modules/npm/node_modules.bundled/npm-registry-client/lib/request.js:210:14)
npm verb stack     at Request.self.callback (/usr/lib/node_modules/npm/node_modules.bundled/request/request.js:187:22)
npm verb stack     at emitTwo (events.js:106:13)
npm verb cwd /####/####/##/###########/###
npm ERR! Linux 2.6.32-37-pve
npm ERR! argv "/usr/bin/node" "/bin/npm" "install" "--production" "-ddd"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10

npm ERR! failed to fetch from registry: https://registry.npmjs.org/gulp
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm verb exit [ 1, true ]

npm ERR! Please include the following file with any support request:
npm ERR!     /####/####/##/###########/###/npm-debug.log
```

Contents of `package.json`:

```
$ cat package.json
{
  "private": true,
  "dependencies": {
    "gulp": "^3.8.8",
    "laravel-elixir": "^4.0.0"
  }
}
```

Output of `cat /etc/*-release`:

```
CentOS Linux release 7.1.1503 (Core)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.1.1503 (Core)
CentOS Linux release 7.1.1503 (Core)
```

Output of `npm config get registry`:

```
https://registry.npmjs.org/
```

Output of `uname -a`:

```
Linux <hostname> 2.6.32-37-pve #1 SMP Wed Mar 18 08:19:56 CET 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Just like @hjkatz:

> I can successfully ping registry.npmjs.org and curl https://registry.npmjs.org/npm.

```
$ ping -c 5 registry.npmjs.org
PING a.sni.fastly.net (151.101.120.162) 56(84) bytes of data.
64 bytes from 151.101.120.162: icmp_seq=1 ttl=58 time=3.99 ms
64 bytes from 151.101.120.162: icmp_seq=2 ttl=58 time=3.99 ms
64 bytes from 151.101.120.162: icmp_seq=3 ttl=58 time=3.98 ms
64 bytes from 151.101.120.162: icmp_seq=4 ttl=58 time=4.01 ms
64 bytes from 151.101.120.162: icmp_seq=5 ttl=58 time=3.99 ms

--- a.sni.fastly.net ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4005ms
rtt min/avg/max/mdev = 3.981/3.995/4.011/0.069 ms
```

```
$ curl -vvv https://registry.npmjs.org/gulp > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* About to connect() to registry.npmjs.org port 443 (#0)
*   Trying 151.101.120.162...
* Connected to registry.npmjs.org (151.101.120.162) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate:
* 	subject: CN=npmjs.org,O="npm, Inc.",STREET=1999 Harrison Street Suite 1150,L=Oakland,ST=California,C=US,incorporationState=Delaware,incorporationCountry=US,serialNumber=5452409,businessCategory=Private Organization
* 	start date: Mar 23 18:49:50 2016 GMT
* 	expire date: May 14 19:06:17 2018 GMT
* 	common name: npmjs.org
* 	issuer: CN=GlobalSign Extended Validation CA - SHA256 - G2,O=GlobalSign nv-sa,C=BE
> GET /gulp HTTP/1.1
> User-Agent: curl/7.29.0
> Host: registry.npmjs.org
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: nginx/1.10.1
< Content-Type: application/json
< Last-Modified: Wed, 19 Jul 2017 17:37:15 GMT
< ETag: "596f98cb-1d6ca"
< Cache-Control: max-age=300
< Content-Length: 120522
< Accept-Ranges: bytes
< Date: Thu, 20 Jul 2017 09:07:34 GMT
< Via: 1.1 varnish
< Age: 45
< Connection: keep-alive
< X-Served-By: cache-cdg8725-CDG
< X-Cache: HIT
< X-Cache-Hits: 1
< X-Timer: S1500541655.601172,VS0,VE1
< Vary: Accept-Encoding, Accept
<
{ [data not shown]
100  117k  100  117k    0     0   621k      0 --:--:-- --:--:-- --:--:--  622k
* Connection #0 to host registry.npmjs.org left intact
```

Also, I have another server with a newer CentOS (7.3.1611) but an older npm (3.10.8) and nodejs (v6.9.1) and everything works just fine there.

**Comment by FreshXOpenSource** [comment]
what happens if you use another version of nodejs with this version of npm? for us this fixes this bug, hence this might be a nodejs problem, not a npm problem

**Comment by BaNkIck** [comment]
Currently there's no other/newer version of nodejs available on my system repositories so I cannot test it. Installing it from another source is not an option for me, sorry.

I'll keep checking for a new version and update it as soon as it is released.

Let me know if you need any other information.
