### ISSUE TITLE
Inpossible to install appium 

### ISSUE THREAD

**Issue by maarwel** [npm/npm#17862]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ *] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I need to install appium. But something goes wrong. I recieve the error message. 
>npm install -g appium
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin
\\npm-cli.js" "install" "-g" "appium"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code E401

npm ERR! 401 Unauthorized
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\antasevich\npm-debug.log

### supporting information:

 - `npm -v` prints:
C:\Users\antasevich>npm -v
3.10.10
 - `node -v` prints:
C:\Users\antasevich>node -v
v6.11.1
 - `npm config get registry` prints:
C:\Users\antasevich>npm config get registry
http://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?:
Windows 8.1
 - Network issues:
   - Geographic location where npm was run:
Russia
   - [ *] I use a proxy to connect to the npm registry.
   - [ *] I use a proxy to connect to the web.
   - [ *] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by maarwel** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'appium' ]
2 info using npm@3.10.10
3 info using node@v6.11.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData appium
8 silly fetchNamedPackageData appium
9 silly mapToRegistry name appium
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry http://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'appium',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'appium',
12 silly mapToRegistry   name: 'appium',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri http://registry.npmjs.org/appium
14 verbose request uri http://registry.npmjs.org/appium
15 verbose request no auth needed
16 info attempt registry request try #1 at 09:44:06
17 verbose request id 1038f110c1751a71
18 http request GET http://registry.npmjs.org/appium
19 http 401 http://registry.npmjs.org/appium
20 verbose headers { server: 'Microsoft-IIS/8.5',
20 verbose headers   'www-authenticate': 'Digest qop="auth",algorithm=MD5-sess,nonce="+Upgraded+v165cd18595efd1b74116ad2393bf5ad1026bbf4952301d30122e1f0e1d4ad854680267606115692ad2451e8ea7a61839b070dec0f0c56dbb7",charset=utf-8,realm="Digest", Negotiate, NTLM',
20 verbose headers   date: 'Thu, 20 Jul 2017 06:44:07 GMT',
20 verbose headers   'content-length': '0' }
21 silly get cb [ 401,
21 silly get   { server: 'Microsoft-IIS/8.5',
21 silly get     'www-authenticate': 'Digest qop="auth",algorithm=MD5-sess,nonce="+Upgraded+v165cd18595efd1b74116ad2393bf5ad1026bbf4952301d30122e1f0e1d4ad854680267606115692ad2451e8ea7a61839b070dec0f0c56dbb7",charset=utf-8,realm="Digest", Negotiate, NTLM',
21 silly get     date: 'Thu, 20 Jul 2017 06:44:07 GMT',
21 silly get     'content-length': '0' } ]
22 silly fetchPackageMetaData Error: 401 Unauthorized
22 silly fetchPackageMetaData     at makeError (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:302:12)
22 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:253:9)
22 silly fetchPackageMetaData     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:210:14)
22 silly fetchPackageMetaData     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:187:22)
22 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
22 silly fetchPackageMetaData     at Request.emit (events.js:191:7)
22 silly fetchPackageMetaData     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1048:10)
22 silly fetchPackageMetaData     at emitOne (events.js:96:13)
22 silly fetchPackageMetaData     at Request.emit (events.js:188:7)
22 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:969:12)
22 silly fetchPackageMetaData  error for appium { Error: 401 Unauthorized
22 silly fetchPackageMetaData     at makeError (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:302:12)
22 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:253:9)
22 silly fetchPackageMetaData     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:210:14)
22 silly fetchPackageMetaData     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:187:22)
22 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
22 silly fetchPackageMetaData     at Request.emit (events.js:191:7)
22 silly fetchPackageMetaData     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1048:10)
22 silly fetchPackageMetaData     at emitOne (events.js:96:13)
22 silly fetchPackageMetaData     at Request.emit (events.js:188:7)
22 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:969:12) statusCode: 401, code: 'E401' }
23 silly rollbackFailedOptional Starting
24 silly rollbackFailedOptional Finishing
25 silly runTopLevelLifecycles Finishing
26 silly install printInstalled
27 verbose stack Error: 401 Unauthorized
27 verbose stack     at makeError (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:302:12)
27 verbose stack     at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:253:9)
27 verbose stack     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:210:14)
27 verbose stack     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:187:22)
27 verbose stack     at emitTwo (events.js:106:13)
27 verbose stack     at Request.emit (events.js:191:7)
27 verbose stack     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1048:10)
27 verbose stack     at emitOne (events.js:96:13)
27 verbose stack     at Request.emit (events.js:188:7)
27 verbose stack     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:969:12)
28 verbose statusCode 401
29 verbose cwd C:\Users\antasevich
30 error Windows_NT 6.3.9600
31 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "appium"
32 error node v6.11.1
33 error npm  v3.10.10
34 error code E401
35 error 401 Unauthorized
36 error If you need help, you may report this error at:
36 error     <https://github.com/npm/npm/issues>
37 verbose exit [ 1, true ]
