### ISSUE TITLE
npm install broken with >= 5.1.0 for private registry

### ISSUE THREAD

**Issue by gyandeeps** [npm/npm#17870]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

**Important Note:** Works in **npm 5.0.4** and broken in **npm 5.1.0** based on my local testing.

* We dont use explicit auth for our registry as the end points are not exposed publicly (atleast I did not put any info)

Installing any package using our private registry fails with a unauthorised 401 error message

```sh
$ npm install classnames
npm ERR! code E401
npm ERR! 401 Unauthorized: classnames@^2.2.5

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\gs025879\AppData\Roaming\npm-cache\_logs\2017-07-20T19_34_06_217Z-debug.log
```

#### How can the CLI team reproduce the problem?

They have to setup a different registry and then try running the above command.

### supporting information:

 - `npm -v` prints: 5.3.0
 - `node -v` prints: 8.2.0
 - `npm config get registry` prints: Private registry
 - Windows, OS X/macOS, or Linux?: Windows 7
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

#### Detailed log

```sh
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\gs025879\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'classnames' ]
2 info using npm@5.1.0
3 info using node@v8.2.0
4 verbose npm-session 38f32f7ccbadcd0e
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 401 http://<private>/npm/classnames 76ms
8 silly fetchPackageMetaData error for classnames@^2.2.5 401 Unauthorized: classnames@^2.2.5
9 verbose stack Error: 401 Unauthorized: classnames@^2.2.5
9 verbose stack     at fetch.then.res (C:\Users\gs025879\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\lib\fetchers\registry\fetch.js:41:19)
9 verbose stack     at tryCatcher (C:\Users\gs025879\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
9 verbose stack     at Promise._settlePromiseFromHandler (C:\Users\gs025879\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
9 verbose stack     at Promise._settlePromise (C:\Users\gs025879\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
9 verbose stack     at Promise._settlePromise0 (C:\Users\gs025879\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
9 verbose stack     at Promise._settlePromises (C:\Users\gs025879\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
9 verbose stack     at Async._drainQueue (C:\Users\gs025879\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
9 verbose stack     at Async._drainQueues (C:\Users\gs025879\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
9 verbose stack     at Immediate.Async.drainQueues (C:\Users\gs025879\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
9 verbose stack     at runCallback (timers.js:781:20)
9 verbose stack     at tryOnImmediate (timers.js:743:5)
9 verbose stack     at processImmediate [as _immediateCallback] (timers.js:714:5)
10 verbose cwd <my path to folder>
11 verbose Windows_NT 6.1.7601
12 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\gs025879\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "classnames"
13 verbose node v8.2.0
14 verbose npm  v5.1.0
15 error code E401
16 error 401 Unauthorized: classnames@^2.2.5
17 verbose exit [ 1, true ]
```

**Comment by gyandeeps** [comment]
**UPDATE:**

This is happening because on my machine I have public npm auth info stored in `~/.npmrc` file. But when i try to install packages using my internal registry (which is set per project using `.npmrc`) it uses the creds from `~/.npmrc` file and that why it throws the above errors.

I never set the `always-auth` config but its by default `false` at least based on the code.

Is their a clean work around this or can this information be saved based on registry?
