### ISSUE TITLE
fatal: reference is not a tree: d11f6d2775bf5b22534b3b2fb3410755b2473cdf

### ISSUE THREAD

**Issue by abmai** [npm/npm#17880]
#### I'm opening this issue because:

  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.

#### What's going wrong?

Getting the following error when installing `react-map-gl` using `npm5`:

```
npm ERR! code 128
npm ERR! Command failed: /usr/local/bin/git checkout d11f6d2775bf5b22534b3b2fb3410755b2473cdf
npm ERR! fatal: reference is not a tree: d11f6d2775bf5b22534b3b2fb3410755b2473cdf
npm ERR!
```

#### How can the CLI team reproduce the problem?

Using `npm 5`, just do `npm install react-map-gl` (investigation details at the end).

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/amai/.nvm/versions/node/v8.2.0/bin/node',
1 verbose cli   '/Users/amai/.nvm/versions/node/v8.2.0/bin/npm',
1 verbose cli   'install',
1 verbose cli   'react-map-gl' ]
2 info using npm@5.3.0
3 info using node@v8.2.0
4 verbose npm-session 513774138d05a8a8
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/react-map-gl 156ms (from cache)
8 silly pacote tag manifest for react-map-gl@latest fetched in 178ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 silly install loadShrinkwrap
12 silly install loadAllDepsIntoIdealTree
13 silly resolveWithNewModule react-map-gl@2.0.3 checking installable status
14 http fetch GET 304 https://registry.npmjs.org/d3-array 86ms (from cache)
15 http fetch GET 304 https://registry.npmjs.org/autobind-decorator 88ms (from cache)
16 http fetch GET 304 https://registry.npmjs.org/d3-selection 88ms (from cache)
17 http fetch GET 304 https://registry.npmjs.org/d3-format 90ms (from cache)
18 http fetch GET 304 https://registry.npmjs.org/d3-color 91ms (from cache)
19 http fetch GET 304 https://registry.npmjs.org/canvas-composite-types 91ms (from cache)
20 http fetch GET 304 https://registry.npmjs.org/flow-remove-types 90ms (from cache)
21 silly pacote range manifest for d3-array@^1.0.1 fetched in 92ms
22 silly resolveWithNewModule d3-array@1.2.0 checking installable status
23 http fetch GET 304 https://registry.npmjs.org/bowser 93ms (from cache)
24 silly pacote range manifest for d3-selection@^1.0.2 fetched in 93ms
25 silly resolveWithNewModule d3-selection@1.1.0 checking installable status
26 silly pacote range manifest for autobind-decorator@^1.3.3 fetched in 96ms
27 silly resolveWithNewModule autobind-decorator@1.4.3 checking installable status
28 silly pacote range manifest for d3-format@^1.0.2 fetched in 96ms
29 silly resolveWithNewModule d3-format@1.2.0 checking installable status
30 silly pacote range manifest for d3-color@^1.0.1 fetched in 97ms
31 silly resolveWithNewModule d3-color@1.0.3 checking installable status
32 silly pacote range manifest for canvas-composite-types@^1.0.4 fetched in 98ms
33 silly resolveWithNewModule canvas-composite-types@1.0.4 checking installable status
34 silly pacote range manifest for flow-remove-types@^1.1.2 fetched in 98ms
35 silly resolveWithNewModule flow-remove-types@1.2.1 checking installable status
36 silly pacote range manifest for bowser@^1.2.0 fetched in 99ms
37 silly resolveWithNewModule bowser@1.7.1 checking installable status
38 http fetch GET 304 https://registry.npmjs.org/global 48ms (from cache)
39 silly pacote range manifest for global@^4.3.0 fetched in 50ms
40 silly resolveWithNewModule global@4.3.2 checking installable status
41 http fetch GET 304 https://registry.npmjs.org/pure-render-decorator 49ms (from cache)
42 http fetch GET 304 https://registry.npmjs.org/mapbox-gl 50ms (from cache)
43 http fetch GET 304 https://registry.npmjs.org/svg-transform 50ms (from cache)
44 silly pacote range manifest for pure-render-decorator@^1.1.0 fetched in 52ms
45 silly resolveWithNewModule pure-render-decorator@1.2.1 checking installable status
46 silly pacote version manifest for mapbox-gl@0.32.1 fetched in 54ms
47 silly resolveWithNewModule mapbox-gl@0.32.1 checking installable status
48 http fetch GET 304 https://registry.npmjs.org/viewport-mercator-project 52ms (from cache)
49 silly pacote version manifest for svg-transform@0.0.3 fetched in 54ms
50 silly resolveWithNewModule svg-transform@0.0.3 checking installable status
51 silly pacote range manifest for viewport-mercator-project@^2.0.1 fetched in 53ms
52 silly resolveWithNewModule viewport-mercator-project@2.1.0 checking installable status
53 http fetch GET 304 https://registry.npmjs.org/d3-scale 175ms (from cache)
54 silly pacote range manifest for d3-scale@^1.0.3 fetched in 177ms
55 silly resolveWithNewModule d3-scale@1.0.6 checking installable status
56 http fetch GET 304 https://registry.npmjs.org/d3-geo 178ms (from cache)
57 silly pacote range manifest for d3-geo@^1.2.4 fetched in 179ms
58 silly resolveWithNewModule d3-geo@1.6.4 checking installable status
59 http fetch GET 304 https://registry.npmjs.org/d3-collection 76ms (from cache)
60 http fetch GET 304 https://registry.npmjs.org/d3-time 75ms (from cache)
61 http fetch GET 304 https://registry.npmjs.org/d3-interpolate 77ms (from cache)
62 silly pacote range manifest for d3-collection@1 fetched in 78ms
63 silly resolveWithNewModule d3-collection@1.0.4 checking installable status
64 silly pacote range manifest for d3-time@1 fetched in 78ms
65 silly resolveWithNewModule d3-time@1.0.7 checking installable status
66 silly pacote range manifest for d3-interpolate@1 fetched in 79ms
67 silly resolveWithNewModule d3-interpolate@1.1.5 checking installable status
68 http fetch GET 304 https://registry.npmjs.org/d3-time-format 141ms (from cache)
69 silly pacote range manifest for d3-time-format@2 fetched in 143ms
70 silly resolveWithNewModule d3-time-format@2.0.5 checking installable status
71 http fetch GET 304 https://registry.npmjs.org/babylon 34ms (from cache)
72 silly pacote range manifest for babylon@^6.15.0 fetched in 36ms
73 silly resolveWithNewModule babylon@6.17.4 checking installable status
74 http fetch GET 304 https://registry.npmjs.org/vlq 104ms (from cache)
75 silly pacote range manifest for vlq@^0.2.1 fetched in 106ms
76 silly resolveWithNewModule vlq@0.2.2 checking installable status
77 http fetch GET 304 https://registry.npmjs.org/min-document 33ms (from cache)
78 silly pacote range manifest for min-document@^2.19.0 fetched in 34ms
79 silly resolveWithNewModule min-document@2.19.0 checking installable status
80 http fetch GET 304 https://registry.npmjs.org/process 35ms (from cache)
81 silly pacote range manifest for process@~0.5.1 fetched in 37ms
82 silly resolveWithNewModule process@0.5.2 checking installable status
83 http fetch GET 304 https://registry.npmjs.org/dom-walk 31ms (from cache)
84 silly pacote range manifest for dom-walk@^0.1.0 fetched in 31ms
85 silly resolveWithNewModule dom-walk@0.1.1 checking installable status
86 http fetch GET 304 https://registry.npmjs.org/brfs 64ms (from cache)
87 http fetch GET 304 https://registry.npmjs.org/bubleify 64ms (from cache)
88 silly pacote range manifest for brfs@^1.4.0 fetched in 68ms
89 silly resolveWithNewModule brfs@1.4.3 checking installable status
90 silly pacote range manifest for bubleify@^0.5.1 fetched in 73ms
91 silly resolveWithNewModule bubleify@0.5.1 checking installable status
92 http fetch GET 304 https://registry.npmjs.org/earcut 74ms (from cache)
93 http fetch GET 304 https://registry.npmjs.org/csscolorparser 75ms (from cache)
94 http fetch GET 304 https://registry.npmjs.org/geojson-rewind 75ms (from cache)
95 http fetch GET 304 https://registry.npmjs.org/feature-filter 75ms (from cache)
96 http fetch GET 304 https://registry.npmjs.org/geojson-vt 75ms (from cache)
97 http fetch GET 304 https://registry.npmjs.org/grid-index 83ms (from cache)
98 silly pacote range manifest for earcut@^2.0.3 fetched in 83ms
99 silly resolveWithNewModule earcut@2.1.1 checking installable status
100 silly pacote range manifest for csscolorparser@^1.0.2 fetched in 85ms
101 silly resolveWithNewModule csscolorparser@1.0.3 checking installable status
102 silly pacote range manifest for geojson-rewind@^0.1.0 fetched in 85ms
103 silly resolveWithNewModule geojson-rewind@0.1.0 checking installable status
104 silly pacote range manifest for geojson-vt@^2.4.0 fetched in 86ms
105 silly resolveWithNewModule geojson-vt@2.4.0 checking installable status
106 silly pacote range manifest for feature-filter@^2.2.0 fetched in 87ms
107 warn deprecated feature-filter@2.2.0: This package has been merged into the 'mapbox-gl-style-spec' package
108 silly resolveWithNewModule feature-filter@2.2.0 checking installable status
109 silly pacote git manifest for mapbox-gl-function@github:mapbox/mapbox-gl-function#41c6724e2bbd7bd1eb5991451bbf118b7d02b525 fetched in 90ms
110 silly resolveWithNewModule mapbox-gl-function@1.3.0 checking installable status
111 silly pacote range manifest for grid-index@^1.0.0 fetched in 91ms
112 silly resolveWithNewModule grid-index@1.0.0 checking installable status
113 http fetch GET 304 https://registry.npmjs.org/mapbox-gl-supported 30ms (from cache)
114 silly pacote range manifest for mapbox-gl-supported@^1.2.0 fetched in 31ms
115 silly resolveWithNewModule mapbox-gl-supported@1.2.0 checking installable status
116 http fetch GET 304 https://registry.npmjs.org/package-json-versionify 50ms (from cache)
117 http fetch GET 304 https://registry.npmjs.org/pngjs 46ms (from cache)
118 http fetch GET 304 https://registry.npmjs.org/pbf 46ms (from cache)
119 http fetch GET 304 https://registry.npmjs.org/point-geometry 48ms (from cache)
120 http fetch GET 304 https://registry.npmjs.org/quickselect 49ms (from cache)
121 silly pacote range manifest for package-json-versionify@^1.0.2 fetched in 54ms
122 silly resolveWithNewModule package-json-versionify@1.0.4 checking installable status
123 silly pacote range manifest for pngjs@^2.2.0 fetched in 51ms
124 silly resolveWithNewModule pngjs@2.3.1 checking installable status
125 silly pacote range manifest for pbf@^1.3.2 fetched in 51ms
126 silly resolveWithNewModule pbf@1.3.7 checking installable status
127 http fetch GET 304 https://registry.npmjs.org/shelf-pack 59ms (from cache)
128 silly pacote range manifest for point-geometry@^0.0.0 fetched in 62ms
129 warn deprecated point-geometry@0.0.0: This module has moved: please install @mapbox/point-geometry instead
130 silly resolveWithNewModule point-geometry@0.0.0 checking installable status
131 silly pacote range manifest for quickselect@^1.0.0 fetched in 63ms
132 silly resolveWithNewModule quickselect@1.0.0 checking installable status
133 http fetch GET 304 https://registry.npmjs.org/request 62ms (from cache)
134 silly pacote range manifest for shelf-pack@^1.0.0 fetched in 71ms
135 warn deprecated shelf-pack@1.1.0: This module is now under the @mapbox namespace: install @mapbox/shelf-pack instead
136 silly resolveWithNewModule shelf-pack@1.1.0 checking installable status
137 silly pacote range manifest for request@^2.39.0 fetched in 78ms
138 silly resolveWithNewModule request@2.81.0 checking installable status
139 http fetch GET 304 https://registry.npmjs.org/supercluster 88ms (from cache)
140 http fetch GET 304 https://registry.npmjs.org/@mapbox%2fgl-matrix 194ms (from cache)
141 silly pacote range manifest for supercluster@^2.0.1 fetched in 90ms
142 silly resolveWithNewModule supercluster@2.3.0 checking installable status
143 silly pacote range manifest for @mapbox/gl-matrix@^0.0.1 fetched in 196ms
144 silly resolveWithNewModule @mapbox/gl-matrix@0.0.1 checking installable status
145 http fetch GET 304 https://registry.npmjs.org/tinyqueue 58ms (from cache)
146 http fetch GET 304 https://registry.npmjs.org/unflowify 49ms (from cache)
147 http fetch GET 304 https://registry.npmjs.org/unassertify 56ms (from cache)
148 silly pacote range manifest for tinyqueue@^1.1.0 fetched in 59ms
149 silly resolveWithNewModule tinyqueue@1.2.2 checking installable status
150 silly pacote range manifest for unflowify@^1.0.0 fetched in 50ms
151 silly resolveWithNewModule unflowify@1.0.1 checking installable status
152 silly pacote range manifest for unassertify@^2.0.0 fetched in 58ms
153 silly resolveWithNewModule unassertify@2.0.4 checking installable status
154 http fetch GET 304 https://registry.npmjs.org/vector-tile 47ms (from cache)
155 silly pacote range manifest for vector-tile@^1.3.0 fetched in 48ms
156 warn deprecated vector-tile@1.3.0: This module has moved: please install @mapbox/vector-tile instead
157 silly resolveWithNewModule vector-tile@1.3.0 checking installable status
158 http fetch GET 304 https://registry.npmjs.org/vt-pbf 44ms (from cache)
159 silly pacote range manifest for vt-pbf@^2.0.2 fetched in 45ms
160 silly resolveWithNewModule vt-pbf@2.1.2 checking installable status
161 http fetch GET 304 https://registry.npmjs.org/webworkify 39ms (from cache)
162 silly pacote range manifest for webworkify@^1.4.0 fetched in 40ms
163 silly resolveWithNewModule webworkify@1.4.0 checking installable status
164 http fetch GET 304 https://registry.npmjs.org/whoots-js 31ms (from cache)
165 silly pacote range manifest for whoots-js@^2.0.0 fetched in 32ms
166 warn deprecated whoots-js@2.1.0: This module is now under the @mapbox namespace: install @mapbox/whoots-js instead
167 silly resolveWithNewModule whoots-js@2.1.0 checking installable status
168 http fetch GET 304 https://registry.npmjs.org/@mapbox%2funitbezier 175ms (from cache)
169 silly pacote range manifest for @mapbox/unitbezier@^0.0.0 fetched in 176ms
170 silly resolveWithNewModule @mapbox/unitbezier@0.0.0 checking installable status
171 silly fetchPackageMetaData error for mapbox-gl-style-spec@github:mapbox/mapbox-gl-style-spec#d11f6d2775bf5b22534b3b2fb3410755b2473cdf Command failed: /usr/local/bin/git checkout d11f6d2775bf5b22534b3b2fb3410755b2473cdf
171 silly fetchPackageMetaData fatal: reference is not a tree: d11f6d2775bf5b22534b3b2fb3410755b2473cdf
172 verbose stack Error: Command failed: /usr/local/bin/git checkout d11f6d2775bf5b22534b3b2fb3410755b2473cdf
172 verbose stack fatal: reference is not a tree: d11f6d2775bf5b22534b3b2fb3410755b2473cdf
172 verbose stack
172 verbose stack     at ChildProcess.exithandler (child_process.js:270:12)
172 verbose stack     at emitTwo (events.js:125:13)
172 verbose stack     at ChildProcess.emit (events.js:213:7)
172 verbose stack     at maybeClose (internal/child_process.js:921:16)
172 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
173 verbose cwd /Users/amai/Development/sandbox/install
174 verbose Darwin 16.6.0
175 verbose argv "/Users/amai/.nvm/versions/node/v8.2.0/bin/node" "/Users/amai/.nvm/versions/node/v8.2.0/bin/npm" "install" "react-map-gl"
176 verbose node v8.2.0
177 verbose npm  v5.3.0
178 error code 128
179 error Command failed: /usr/local/bin/git checkout d11f6d2775bf5b22534b3b2fb3410755b2473cdf
179 error fatal: reference is not a tree: d11f6d2775bf5b22534b3b2fb3410755b2473cdf
180 verbose exit [ 1, true ]
```

This installation works with older `npm` versions, just not on `npm 5`. The particular commit referenced here exists in its repo: https://github.com/mapbox/mapbox-gl-style-spec/commit/d11f6d2775bf5b22534b3b2fb3410755b2473cdf

**Comment by aendra-rininsland** [comment]
I ran into this when I had my forked version of [nunjucks-webpack-plugin](https://github.com/itgalaxy/nunjucks-webpack-plugin) installed using the GitHub branch reference.

Re-installing it (thus updating the `package-lock.json` file) solved the issue in the end.

FWIW, the existing messaging is *really* vague with this issue. The package causing the issue should be reported in the standard error reporting, at the very least.

**Comment by abmai** [comment]
Hm i'm installing on a fresh folder without any `package-lock.json` though - and it's odd that this only breaks on `npm 5`?

**Comment by AdiDahan** [comment]
Thanks @aendrew I've looked into my package-lock.json file and looked for the incorrect reference and was finally able to solve it!
I spent too many hours on this one today trying to install when any combination of node and npm..

**Comment by Luckygirlllll** [comment]
I have the same problem,  where is that package-lock.json file?

**Comment by Luckygirlllll** [comment]
@AdiDahan  And how did you solve it?

**Comment by AdiDahan** [comment]
@Luckygirlllll 
Next to package.json file, you can see package-lock.json.
I've removed the version from my specific incorrect dependency, but if you're having some issues, you can: 
1. remove all npm_modules folder
2. delete package-lock.json file
3. run npm install
4. commit package-lock.json file

hope that helps

**Comment by Luckygirlllll** [comment]
@AdiDahan you mean you did in the project or in npm?

**Comment by Luckygirlllll** [comment]
@AdiDahan How did you figure out which dependency was incorrect?

**Comment by AdiDahan** [comment]
@Luckygirlllll In the project.
It's been a while so I'm not certain, but I think I've searched for the reference that was outputted

**Comment by Luckygirlllll** [comment]
Deleting of node modules and package-lock.json didn't help me. is there any other solutions?

**Comment by alwaysAn0n** [comment]
@Luckygirlllll I was able to fix this by looking in the npm debug log file referenced in the error message.  Scroll to the bottom and note the npm module on which the install is failing.  Remove that module from `package.json` and try `npm install` again after deleting `package-lock.json`.  Obviously if the module you removed was vital to your application's functionality, you'll have to deal with that.  In my case is wasn't.  Hope this helps.
