### ISSUE TITLE
NPM Proxy works on HTTPS but not on HTTP

### ISSUE THREAD

**Issue by webmutation** [npm/npm#17962]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [X] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Setting the npm proxy to an http repository results in 403 errors 
npm config set registry http://d*******/repository/npm-all/

#### How can the CLI team reproduce the problem?
Try to access any package from a HTTP repository behind a proxy

**Works on npm@4.6.1 and downgrading to this version fixes the issue. Proxy settings work on HTTPS repository, it is only HTTP repositories that return a 403 using version 5.3.0 of npm**

### supporting information:
 - `npm -v` prints:
5.3.0

 - `node -v` prints:
v6.9.1

 - `npm config get registry` prints:
http://d************:8081/repository/npm-all/

 - Windows, OS X/macOS, or Linux?:
Microsoft Windows [Version 6.1.7601]

 - Network issues:
   - Geographic location where npm was run:
   - [X] I use a proxy to connect to the npm registry.
   - [X] I use a proxy to connect to the web.
   - [X] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.

**Comment by webmutation** [comment]
Tested with Canary release npm@5.4.0 continues to fail to install packages based on HTTP registry behind proxy

> npmc i
> npm notice CANARY npmc is experimental software. If you find an issue, please file it in the main npm repository, and call out that you were using npmc.
> npm ERR! code E403
> npm ERR! 403 Forbidden: @angular/forms@^4.0.0
> 
> npm ERR! A complete log of this run can be found in:

npm@4.6.1 continues to work.

**Comment by miguelferreira** [comment]
Same problem here!

That blocks me to update to npm 5+ version and benefit of all improvements and bug fixes ...

**Comment by FabienDehopre** [comment]
I have the same issue with npm 5.5.1
Here is the log that is produced:
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'i' ]
2 info using npm@5.5.1
3 info using node@v6.11.3
4 verbose npm-session 161b1c7f979c6166
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall test-opw-kernel@0.0.0
7 info lifecycle test-opw-kernel@0.0.0~preinstall: test-opw-kernel@0.0.0
8 silly install loadCurrentTree
9 silly install readLocalPackageData
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 silly install loadShrinkwrap
13 silly install loadAllDepsIntoIdealTree
14 http fetch GET 403 http://registry.npmjs.org/@angular%2fcommon 12412ms
15 silly fetchPackageMetaData error for @angular/common@^4.2.4 403 Forbidden: @angular/common@^4.2.4
16 http fetch GET 403 http://registry.npmjs.org/@angular%2fforms 13521ms
17 silly fetchPackageMetaData error for @angular/forms@^4.2.4 403 Forbidden: @angular/forms@^4.2.4
18 http fetch GET 403 http://registry.npmjs.org/@angular%2fplatform-browser 1155ms
19 silly fetchPackageMetaData error for @angular/platform-browser@^4.2.4 403 Forbidden: @angular/platform-browser@^4.2.4
20 http fetch GET 403 http://registry.npmjs.org/@angular%2fplatform-browser-dynamic 561ms
21 silly fetchPackageMetaData error for @angular/platform-browser-dynamic@^4.2.4 403 Forbidden: @angular/platform-browser-dynamic@^4.2.4
22 http fetch GET 403 http://registry.npmjs.org/@angular%2frouter 562ms
23 silly fetchPackageMetaData error for @angular/router@^4.2.4 403 Forbidden: @angular/router@^4.2.4
24 http fetch GET 403 http://registry.npmjs.org/angular-l10n 702ms
25 silly fetchPackageMetaData error for angular-l10n@^3.5.1 403 Forbidden: angular-l10n@^3.5.1
26 http fetch GET 403 http://registry.npmjs.org/core-js 655ms
27 silly fetchPackageMetaData error for core-js@^2.4.1 403 Forbidden: core-js@^2.4.1
28 http fetch GET 403 http://registry.npmjs.org/lodash 484ms
29 silly fetchPackageMetaData error for lodash@^4.17.4 403 Forbidden: lodash@^4.17.4
30 http fetch GET 403 http://registry.npmjs.org/primeng 500ms
31 silly fetchPackageMetaData error for primeng@^4.2.2 403 Forbidden: primeng@^4.2.2
32 http fetch GET 403 http://registry.npmjs.org/rxjs 1107ms
33 silly fetchPackageMetaData error for rxjs@^5.4.2 403 Forbidden: rxjs@^5.4.2
34 http fetch GET 403 http://registry.npmjs.org/zone.js 1093ms
35 silly fetchPackageMetaData error for zone.js@^0.8.14 403 Forbidden: zone.js@^0.8.14
36 http fetch GET 403 http://registry.npmjs.org/@angular%2fhttp 32739ms attempt #2
37 silly fetchPackageMetaData error for @angular/http@^4.2.4 403 Forbidden: @angular/http@^4.2.4
38 http fetch GET 403 http://registry.npmjs.org/@angular%2fcompiler-cli 33004ms attempt #2
39 silly fetchPackageMetaData error for @angular/compiler-cli@^4.2.4 403 Forbidden: @angular/compiler-cli@^4.2.4
40 http fetch GET 403 http://registry.npmjs.org/@angular%2fcompiler 35238ms attempt #2
41 silly fetchPackageMetaData error for @angular/compiler@^4.2.4 403 Forbidden: @angular/compiler@^4.2.4
42 http fetch GET 403 http://registry.npmjs.org/typescript 35254ms attempt #2
43 http fetch GET 403 http://registry.npmjs.org/@angular%2fcore 35254ms attempt #2
44 silly fetchPackageMetaData error for typescript@~2.3.3 403 Forbidden: typescript@~2.3.3
45 silly fetchPackageMetaData error for @angular/core@^4.2.4 403 Forbidden: @angular/core@^4.2.4
46 http fetch GET 403 http://registry.npmjs.org/@angular%2fanimations 37532ms attempt #2
47 silly fetchPackageMetaData error for @angular/animations@^4.2.4 403 Forbidden: @angular/animations@^4.2.4
48 http fetch GET 403 http://registry.npmjs.org/@angular%2flanguage-service 37532ms attempt #2
49 http fetch GET 403 http://registry.npmjs.org/@angular%2fcli 37579ms attempt #2
50 silly fetchPackageMetaData error for @angular/language-service@^4.2.4 403 Forbidden: @angular/language-service@^4.2.4
51 silly fetchPackageMetaData error for @angular/cli@1.4.5 403 Forbidden: @angular/cli@1.4.5
52 http fetch GET 403 http://registry.npmjs.org/@angular%2fanimations 1170ms
53 silly fetchPackageMetaData error for @angular/animations@^4.2.4 403 Forbidden: @angular/animations@^4.2.4
54 http fetch GET 403 http://registry.npmjs.org/@angular%2fcommon 1185ms
55 silly fetchPackageMetaData error for @angular/common@^4.2.4 403 Forbidden: @angular/common@^4.2.4
56 http fetch GET 403 http://registry.npmjs.org/angular-l10n 1248ms
57 silly fetchPackageMetaData error for angular-l10n@^3.5.1 403 Forbidden: angular-l10n@^3.5.1
58 http fetch GET 403 http://registry.npmjs.org/@angular%2frouter 1263ms
59 silly fetchPackageMetaData error for @angular/router@^4.2.4 403 Forbidden: @angular/router@^4.2.4
60 http fetch GET 403 http://registry.npmjs.org/@angular%2fplatform-browser-dynamic 1263ms
61 silly fetchPackageMetaData error for @angular/platform-browser-dynamic@^4.2.4 403 Forbidden: @angular/platform-browser-dynamic@^4.2.4
62 http fetch GET 403 http://registry.npmjs.org/core-js 483ms
63 silly fetchPackageMetaData error for core-js@^2.4.1 403 Forbidden: core-js@^2.4.1
64 http fetch GET 403 http://registry.npmjs.org/lodash 468ms
65 silly fetchPackageMetaData error for lodash@^4.17.4 403 Forbidden: lodash@^4.17.4
66 http fetch GET 403 http://registry.npmjs.org/primeng 530ms
67 silly fetchPackageMetaData error for primeng@^4.2.2 403 Forbidden: primeng@^4.2.2
68 http fetch GET 403 http://registry.npmjs.org/rxjs 531ms
69 silly fetchPackageMetaData error for rxjs@^5.4.2 403 Forbidden: rxjs@^5.4.2
70 http fetch GET 403 http://registry.npmjs.org/zone.js 546ms
71 silly fetchPackageMetaData error for zone.js@^0.8.14 403 Forbidden: zone.js@^0.8.14
72 http fetch GET 403 http://registry.npmjs.org/@angular%2fcore 12128ms
73 silly fetchPackageMetaData error for @angular/core@^4.2.4 403 Forbidden: @angular/core@^4.2.4
74 http fetch GET 403 http://registry.npmjs.org/@angular%2fforms 12986ms
75 silly fetchPackageMetaData error for @angular/forms@^4.2.4 403 Forbidden: @angular/forms@^4.2.4
76 http fetch GET 403 http://registry.npmjs.org/@angular%2fplatform-browser 32209ms attempt #2
77 silly fetchPackageMetaData error for @angular/platform-browser@^4.2.4 403 Forbidden: @angular/platform-browser@^4.2.4
78 http fetch GET 403 http://registry.npmjs.org/@angular%2fhttp 55164ms
79 silly fetchPackageMetaData error for @angular/http@^4.2.4 403 Forbidden: @angular/http@^4.2.4
80 http fetch GET 403 http://registry.npmjs.org/@angular%2fcompiler 55180ms
81 silly fetchPackageMetaData error for @angular/compiler@^4.2.4 403 Forbidden: @angular/compiler@^4.2.4
82 verbose stack Error: 403 Forbidden: @angular/animations@^4.2.4
82 verbose stack     at fetch.then.res (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\fetchers\registry\fetch.js:42:19)
82 verbose stack     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
82 verbose stack     at Promise._settlePromiseFromHandler (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
82 verbose stack     at Promise._settlePromise (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
82 verbose stack     at Promise._settlePromise0 (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
82 verbose stack     at Promise._settlePromises (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
82 verbose stack     at Async._drainQueue (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
82 verbose stack     at Async._drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
82 verbose stack     at Immediate.Async.drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
82 verbose stack     at runCallback (timers.js:672:20)
82 verbose stack     at tryOnImmediate (timers.js:645:5)
82 verbose stack     at processImmediate [as _immediateCallback] (timers.js:617:5)
83 verbose cwd D:\dvlp\RnD\test-opw-kernel
84 verbose Windows_NT 6.1.7601
85 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i"
86 verbose node v6.11.3
87 verbose npm  v5.5.1
88 error code E403
89 error 403 Forbidden: @angular/animations@^4.2.4
90 verbose exit [ 1, true ]
```

**Comment by webmutation** [comment]
This error still occurs, its shameful that the npm client has such a bad reputation in enterprise environments.

**Comment by webmutation** [comment]
Problem still exists on 5.5.1
