### ISSUE TITLE
npm install nativescript not working

### ISSUE THREAD

**Issue by shera40** [npm/npm#17963]
#### I'm opening this issue because:

I've just updated my windows 7 to windows 10 so I've added the latest node but for some reason this command doesn't seem to work.
-- npm install nativescript -g

I keep getting this error:

16265 error Error: Invalid name: "@types/semver"
16265 error     at ensureValidName (C:\ProgramData\chocolatey\lib\npm\tools\node_modules\npm\node_modules\read-package-json\node_modules\normalize-package-data\lib\fixer.js:300:15)
16265 error     at Object.fixNameField (C:\ProgramData\chocolatey\lib\npm\tools\node_modules\npm\node_modules\read-package-json\node_modules\normalize-package-data\lib\fixer.js:204:5)
16265 error     at C:\ProgramData\chocolatey\lib\npm\tools\node_modules\npm\node_modules\read-package-json\node_modules\normalize-package-data\lib\normalize.js:30:38
16265 error     at Array.forEach (native)
16265 error     at normalize (C:\ProgramData\chocolatey\lib\npm\tools\node_modules\npm\node_modules\read-package-json\node_modules\normalize-package-data\lib\normalize.js:29:15)
16265 error     at final (C:\ProgramData\chocolatey\lib\npm\tools\node_modules\npm\node_modules\read-package-json\read-json.js:342:33)
16265 error     at then (C:\ProgramData\chocolatey\lib\npm\tools\node_modules\npm\node_modules\read-package-json\read-json.js:126:33)
16265 error     at C:\ProgramData\chocolatey\lib\npm\tools\node_modules\npm\node_modules\read-package-json\read-json.js:266:40
16265 error     at tryToString (fs.js:513:3)
16265 error     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:501:12)
16266 error If you need help, you may report this *entire* log,
16266 error including the npm and node versions, at:
16266 error     <http://github.com/npm/npm/issues>
16267 error System Windows_NT 10.0.14393
16268 error command "C:\\Program Files\\nodejs\\node.exe" "C:\\ProgramData\\chocolatey\\lib\\npm\\tools\\node_modules\\npm\\bin\\npm-cli.js" "install" "nativescript" "-g"
16269 error cwd C:\windows\system32
16270 error node -v v8.2.1
16271 error npm -v 1.4.9

**Comment by shera40** [comment]
Node was install via chocolatey, solved the issue by deleting npm from choco library.
