### ISSUE TITLE
Error with NPM Uninstalling Angular CLI to Upgrade to Latest

### ISSUE THREAD

**Issue by mgeiser81** [npm/npm#17964]
I am using NPM 5.0.3
I am using Node v6.9.5
I am using Angular CLI 1.0.4
I am on a Windows 10 system

λ npm uninstall -g @angular/cli
Unhandled rejection Error: Argument #2: Expected string but got null randomatic@^1.1.3 fetched in 30ms
    at addDependency (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:515:3)
    at C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:463:5
    at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:35
    at Array.forEach (native)
    at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:11
    at Array.forEach (native)
    at asyncMap (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:51:8)
    at loadDeps (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:455:3)
    at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
    at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
    at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:18:7
    at C:\Program Files\nodejs\node_modules\npm\lib\install\and-finish-tracker.js:8:8
    at resolveBranchDeps.then (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:419:11)
    at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

NOTE: Each time I try to uninstall I get a slightly different error. The next one after this was *align-text@^0.1.3*

**Comment by kenany** [comment]
Does this also occur with `npm@5.3.0`?

**Comment by kenany** [comment]
Closing as abandoned.
