### ISSUE TITLE
unable to install NPM - TypeError: Object function Object() { [native code] } has no method 'assign'

### ISSUE THREAD

**Issue by pradeeps** [npm/npm#17996]
#### I'm opening this issue because:

  - npm installing is crashing.

#### What's going wrong?
I get this error 
MacBook-Pro:react_hello_world susarla$ curl -L https://www.npmjs.com/install.sh | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6255  100  6255    0     0   5603      0  0:00:01  0:00:01 --:--:--  5599
tar=/usr/bin/tar
version:
bsdtar 2.8.3 - libarchive 2.8.3
install npm@latest
fetching: https://registry.npmjs.org/npm/-/npm-5.3.0.tgz

/private/var/folders/37/n6h0qlm51r34g7wq1vv341wm0000gn/T/npm.55738/package/lib/config/cmd-list.js:113
module.exports.aliases = Object.assign({}, shorthands, affordances)
                                ^
TypeError: Object function Object() { [native code] } has no method 'assign'
    at Object.<anonymous> (/private/var/folders/37/n6h0qlm51r34g7wq1vv341wm0000gn/T/npm.55738/package/lib/config/cmd-list.js:113:33)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /private/var/folders/37/n6h0qlm51r34g7wq1vv341wm0000gn/T/npm.55738/package/lib/npm.js:37:17
    at Object.<anonymous> (/private/var/folders/37/n6h0qlm51r34g7wq1vv341wm0000gn/T/npm.55738/package/lib/npm.js:471:3)
    at Module._compile (module.js:456:26)

/private/var/folders/37/n6h0qlm51r34g7wq1vv341wm0000gn/T/npm.55738/package/lib/config/cmd-list.js:113
module.exports.aliases = Object.assign({}, shorthands, affordances)
                                ^
TypeError: Object function Object() { [native code] } has no method 'assign'
    at Object.<anonymous> (/private/var/folders/37/n6h0qlm51r34g7wq1vv341wm0000gn/T/npm.55738/package/lib/config/cmd-list.js:113:33)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /private/var/folders/37/n6h0qlm51r34g7wq1vv341wm0000gn/T/npm.55738/package/lib/npm.js:37:17
    at Object.<anonymous> (/private/var/folders/37/n6h0qlm51r34g7wq1vv341wm0000gn/T/npm.55738/package/lib/npm.js:471:3)
    at Module._compile (module.js:456:26)
It failed

#### How can the CLI team reproduce the problem?

I've installed Node using this 

rm -rf /usr/local/lib/node_modules
brew uninstall node
brew install node --without-npm
echo prefix=~/.npm-packages >> ~/.npmrc

### supporting information:

 - `npm -v` prints:
-bash: /usr/local/bin/npm: No such file or directory
 - `node -v` prints:
v0.10.29
 - `npm config get registry` prints:
-bash: /usr/local/bin/npm: No such file or directory

MacOS Sierra : 10:12:5

**Comment by jonathanbarnes11** [comment]
I'm having the same issue

**Comment by SelviA** [comment]
Me too

**Comment by pradeeps** [comment]
Guys, I had to stop my development as I am stuck. I did uninstall and reinstall and tried other methods but all of them result in the same error again... If there's anything I can do to help, please let me know.

**Comment by krm1** [comment]
Me too on Amazon Linux.

**Comment by krm1** [comment]
@pradeeps You could try this: https://nodejs.org/en/download/package-manager/#osx

`curl "https://nodejs.org/dist/latest/node-${VERSION:-$(wget -qO- https://nodejs.org/dist/latest/ | sed -nE 's|.*>node-(.*)\.pkg</a>.*|\1|p')}.pkg" > "$HOME/Downloads/node-latest.pkg" && sudo installer -store -pkg "$HOME/Downloads/node-latest.pkg" -target "/"`

Worked for me on Amazon Linux as well (different command).

**Comment by arrabal** [comment]
I've been stuck with this as well. I rescued an old project from Dec 2016 and tried to build the docker container, getting the same error. What can I do?

**Comment by danhostetler** [comment]
Got this error after trying to install npm using yum on an amazon linux server. 

I used this guide to successfully install npm on amazon:
http://sharpten.com/blog/2017/01/24/setting-node-js-amazon-ec2-instance.html

**Comment by hleb-rubanau** [comment]
Recent versions of npm are no more compatible with node 0.10.29 installed with Debian Jessie (which still is a basis for  many Dockerhub images). Earlier versions just were issuing a warning.

I successfully used the following multi-step workaround. (4.3.0 is the latest version of npm which installs on ancient nodes).


```
# install outdated stock npm, than use it to upgrade itself to the intermediate version
RUN apt-get update && apt-get -y install npm    && \
    npm install -g npm@4.3.0                    && \
    ln -s /usr/bin/nodejs /usr/bin/node

# upgrade node via npm by installing n and using it to manage nodes
RUN npm install -g n && n latest 
```

In fact this is an old well-known hack , but the difference is now we're installing npm@4.3.0 not npm@latest (which was sufficient until Spring 2017).

As a result, there are latest node and npm

```
node --version
v8.4.0
npm --version
5.3.0
```

For those new to problem: it is important to call "npm install -g n" in a different session (or, equivalently, separate Dockerfile directive) than "npm install -g npm@4.3.0".  The reason is , intermediate upgrade to 4.3.0 has effect only for new sessions, not the one which it was triggered from.
