### ISSUE TITLE
`npm i -g npm` breaks itself.

### ISSUE THREAD

**Issue by trusktr** [npm/npm#17991]
```
> node -v
v0.10.43

> npm -v
2.15.12

> npm i -g npm

> npm -v

/home/trusktr/.meteor/packages/meteor-tool/.1.3.1.vgjdlv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/lib/config/cmd-list.js:113
module.exports.aliases = Object.assign({}, shorthands, affordances)
                                ^
TypeError: Object function Object() { [native code] } has no method 'assign'
    at Object.<anonymous> (/home/trusktr/.meteor/packages/meteor-tool/.1.3.1.vgjdlv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/lib/config/cmd-list.js:113:33)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /home/trusktr/.meteor/packages/meteor-tool/.1.3.1.vgjdlv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/lib/npm.js:37:17
    at Object.<anonymous> (/home/trusktr/.meteor/packages/meteor-tool/.1.3.1.vgjdlv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/lib/npm.js:471:3)
    at Module._compile (module.js:456:26)
```

---

It seems that NPM should be smart enough not to install a version of itself that won't work with the current version of Node. An error should be thrown instead.

Because now an innocent possibly non-system-savvy user will now be stuck with a non-working NPM and not an obvious way to fix it.

**Comment by richardsj** [comment]
This isn't a feature request, it's an incredibly common bug.
