### ISSUE TITLE
Install module from git via root fails (no permission)

### ISSUE THREAD

**Issue by coolchip** [npm/npm#18038]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

If I try to `npm install` a package from a git repo **as root**, it fails because of missing permission. This only happens as root and with a package from git. If I do this as non-root, everything works fine.
For me this happens with npm v5.3.0 and v5.0.0 on different machines.
At npm v4.6.1 everything is fine.

Log @ v5.3.0
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'i',
1 verbose cli   'git+https://github.com/Apollon77/OpenSML' ]
2 info using npm@5.3.0
3 info using node@v8.2.1
4 verbose config Skipping project config: /root/.npmrc. (matches userconfig)
5 verbose npm-session bd1e612899a17f00
6 silly install loadCurrentTree
7 silly install readLocalPackageData
8 silly fetchPackageMetaData error for git+https://github.com/Apollon77/OpenSML.git Error while executing:
8 silly fetchPackageMetaData /usr/bin/git ls-remote -h -t https://github.com/Apollon77/OpenSML.git
8 silly fetchPackageMetaData
8 silly fetchPackageMetaData fatal: failed to stat '.': Keine Berechtigung
8 silly fetchPackageMetaData
8 silly fetchPackageMetaData exited with error code: 128
9 verbose stack Error: exited with error code: 128
9 verbose stack     at ChildProcess.onexit (/usr/lib/node_modules/npm/node_modules/mississippi/node_modules/end-of-stream/index.js:39:36)
9 verbose stack     at emitTwo (events.js:125:13)
9 verbose stack     at ChildProcess.emit (events.js:213:7)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
10 verbose cwd /root
11 verbose Linux 4.4.0-87-generic
12 verbose argv "/usr/bin/nodejs" "/usr/bin/npm" "i" "git+https://github.com/Apollon77/OpenSML"
13 verbose node v8.2.1
14 verbose npm  v5.3.0
15 error Error while executing:
15 error /usr/bin/git ls-remote -h -t https://github.com/Apollon77/OpenSML.git
15 error
15 error fatal: failed to stat '.': Keine Berechtigung
15 error
15 error exited with error code: 128
16 verbose exit [ 1, true ]
```
Needless to say that root has permission to do everything at the current working directory. Also at /root/.npm (recursive).
`/usr/bin/git ls-remote -h -t https://github.com/Apollon77/OpenSML.git` works also fine for root.

#### How can the CLI team reproduce the problem?

```bash
sudo su
npm i -g npm@5.3.0
npm i "git+https://github.com/Apollon77/OpenSML"
```

### supporting information:

 - `npm -v` prints: 5.3.0
 - `node -v` prints: v8.2.1
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux

**Comment by coolchip** [comment]
Might be a simular issue as here: #18009

I found out, that npm uses the UID of the parent process, when I use `sudo su`. So of cause it can't access the /root path with a non-root UID. If I use a login shell or switch to root via `sudo su -` the `npm install <git repo>` works fine and uses the UID of user root.
But the error above only effects installing from a git repo. If I `npm install <npm package>`, it works without any error. The only thing is, that the node_modules dir has the wrong UID, as described here: #18009

**Comment by rhbecker** [comment]
we're experiencing the same (I think) issue.

similar to the work-around you mentioned, running the command via `sudo -u root` also seems to work.
