### ISSUE TITLE
unable to publish, "Maintainer should have an email"

### ISSUE THREAD

**Issue by john-codeworx** [npm/npm#18030]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [X ] Other (_see below for feature requests_):

#### What's going wrong?

initially when running ```npm publish```  i get: 
```
npm ERR! publish Failed PUT 401
npm ERR! code E401
visit https://github.cwx.io/login/oauth/authorize?redirect_uri=https%3A%2F%2Fnpm.cwx.io%2Fauth%2Foauth2%2Fcallback&scope=user&state=528b48c6-e412-4c19-9d66-9fed96465bd1&response_type=code&client_id=858cd923826baf7de7a2 to validate your session : @codeworx/semantic
```

I visit the link, then:

when running ```npm publish``` i getting the reponse:
 ```
publish Failed PUT 500
npm ERR! code E500
"Maintainer should have an email: {\"name\":\"john\",\"email\":null,\"cacheAllowed\":false}"
```

user I login as is john-codeworx, not john.

#### How can the CLI team reproduce the problem?

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/8.2.1/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'publish' ]
2 info using npm@5.3.0
3 info using node@v8.2.1
4 verbose npm-session 52f5c1f241a1635a
5 verbose publish [ '.' ]
6 info lifecycle @codeworx/semantic@1.0.0~prepublish: @codeworx/semantic@1.0.0
7 info lifecycle @codeworx/semantic@1.0.0~prepare: @codeworx/semantic@1.0.0
8 info lifecycle @codeworx/semantic@1.0.0~prepublishOnly: @codeworx/semantic@1.0.0
9 info lifecycle @codeworx/semantic@1.0.0~prepack: @codeworx/semantic@1.0.0
10 verbose tar pack [ '/var/folders/n9/yzx7mtj53dvgd7ym46jxt3qr0000gp/T/npm-8483-0af3d1b1/tmp/packing-353fdc50/package.tgz',
10 verbose tar pack   '.' ]
11 verbose tarball /var/folders/n9/yzx7mtj53dvgd7ym46jxt3qr0000gp/T/npm-8483-0af3d1b1/tmp/packing-353fdc50/package.tgz
12 verbose folder .
13 info lifecycle @codeworx/semantic@1.0.0~postpack: @codeworx/semantic@1.0.0
14 verbose getPublishConfig { registry: 'https://registry.npm.cwx.io/' }
15 silly mapToRegistry name @codeworx/semantic
16 silly mapToRegistry scope (from package name) @codeworx
17 silly mapToRegistry registry https://registry.npm.cwx.io
18 silly mapToRegistry data { type: 'tag',
18 silly mapToRegistry   registry: true,
18 silly mapToRegistry   where: undefined,
18 silly mapToRegistry   raw: '@codeworx/semantic',
18 silly mapToRegistry   name: '@codeworx/semantic',
18 silly mapToRegistry   escapedName: '@codeworx%2fsemantic',
18 silly mapToRegistry   scope: '@codeworx',
18 silly mapToRegistry   rawSpec: '',
18 silly mapToRegistry   saveSpec: null,
18 silly mapToRegistry   fetchSpec: 'latest',
18 silly mapToRegistry   gitRange: undefined,
18 silly mapToRegistry   gitCommittish: undefined,
18 silly mapToRegistry   hosted: undefined }
19 silly mapToRegistry uri https://registry.npm.cwx.io/@codeworx%2fsemantic
20 verbose publish registryBase https://registry.npm.cwx.io/
21 silly publish uploading /var/folders/n9/yzx7mtj53dvgd7ym46jxt3qr0000gp/T/npm-8483-0af3d1b1/tmp/fromDir-837942e3/package.tgz
22 verbose request uri https://registry.npm.cwx.io/@codeworx%2fsemantic
23 verbose request sending authorization for write operation
24 info attempt registry request try #1 at 09:25:20
25 verbose request using bearer token for auth
26 verbose request id 84b0f4bd07a0ce50
27 http request PUT https://registry.npm.cwx.io/@codeworx%2fsemantic
28 http 500 https://registry.npm.cwx.io/@codeworx%2fsemantic
29 verbose headers { 'content-length': '138',
29 verbose headers   'content-type': 'application/json',
29 verbose headers   date: 'Tue, 01 Aug 2017 23:25:21 GMT',
29 verbose headers   'x-powered-by': 'Express' }
30 info retry will retry, error on last attempt: Error: "Maintainer should have an email: {\"name\":\"john\",\"email\":null,\"cacheAllowed\":false}" : @codeworx/semantic
31 info attempt registry request try #2 at 09:25:31
32 verbose request using bearer token for auth
33 http request PUT https://registry.npm.cwx.io/@codeworx%2fsemantic
34 http 500 https://registry.npm.cwx.io/@codeworx%2fsemantic
35 verbose headers { 'content-length': '138',
35 verbose headers   'content-type': 'application/json',
35 verbose headers   date: 'Tue, 01 Aug 2017 23:25:31 GMT',
35 verbose headers   'x-powered-by': 'Express' }
36 info retry will retry, error on last attempt: Error: "Maintainer should have an email: {\"name\":\"john\",\"email\":null,\"cacheAllowed\":false}" : @codeworx/semantic
37 info attempt registry request try #3 at 09:26:31
38 verbose request using bearer token for auth
39 http request PUT https://registry.npm.cwx.io/@codeworx%2fsemantic
40 http 500 https://registry.npm.cwx.io/@codeworx%2fsemantic
41 verbose headers { 'content-length': '138',
41 verbose headers   'content-type': 'application/json',
41 verbose headers   date: 'Tue, 01 Aug 2017 23:26:32 GMT',
41 verbose headers   'x-powered-by': 'Express' }
42 error publish Failed PUT 500
43 verbose stack Error: "Maintainer should have an email: {\"name\":\"john\",\"email\":null,\"cacheAllowed\":false}" : @codeworx/semantic
43 verbose stack     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:314:12)
43 verbose stack     at RegClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:302:14)
43 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:216:14)
43 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:188:22)
43 verbose stack     at emitTwo (events.js:125:13)
43 verbose stack     at Request.emit (events.js:213:7)
43 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1171:10)
43 verbose stack     at emitOne (events.js:115:13)
43 verbose stack     at Request.emit (events.js:210:7)
43 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1091:12)
43 verbose stack     at Object.onceWrapper (events.js:314:30)
43 verbose stack     at emitNone (events.js:110:20)
43 verbose stack     at IncomingMessage.emit (events.js:207:7)
43 verbose stack     at endReadableNT (_stream_readable.js:1045:12)
43 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:138:11)
43 verbose stack     at process._tickCallback (internal/process/next_tick.js:180:9)
44 verbose statusCode 500
45 verbose pkgid @codeworx/semantic
46 verbose cwd /Users/john/Documents/development/corkhat/semantic
47 verbose Darwin 16.6.0
48 verbose argv "/usr/local/Cellar/node/8.2.1/bin/node" "/usr/local/bin/npm" "publish"
49 verbose node v8.2.1
50 verbose npm  v5.3.0
51 error code E500
52 error "Maintainer should have an email: {\"name\":\"john\",\"email\":null,\"cacheAllowed\":false}" : @codeworx/semantic
53 verbose exit [ 1, true ]
```

### supporting information:

 - `npm -v` prints: 5.3.0
 - `node -v` prints: v8.2.1
 - `npm config get registry` prints: https://registry.npm.cwx.io/
 - Windows, OS X/macOS, or Linux?: macOS

**Comment by john-codeworx** [comment]
solution found:
1. set public email on github (enterprise).
2. npm login --registry=https://registry.npm.domain --scope=@yourscope --auth-type=oauth
