### ISSUE TITLE
It's possible to make npm installation unusable by downgrading and upgrading npm versions

### ISSUE THREAD

**Issue by Ginden** [npm/npm#18066]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

Following sequence of shell commands triggers issue:
```bash
npm install -g npm@5 &&
npm install -g npm@4 &&
npm install -g npm &&
npm install -g npm@3;

npm whatever
```
Result:

```
Error: Cannot find module 'safe-buffer'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/lib/helpers.js:5:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
npm ERR! Darwin 16.7.0
npm ERR! argv "/usr/local/Cellar/node/7.10.0/bin/node" "/usr/local/bin/npm" "whatever"
npm ERR! node v7.10.0
npm ERR! npm  v3.10.10
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'safe-buffer'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

**This results in broken installation. Don't run it on main machine, use VM or container instead**.

**Comment by Ginden** [comment]
Just confirmed on virtual machines with Ubuntu 12 and Ubuntu 16.
Full history required to replicate issue on 

#### Ubuntu 12 replication

```sh
# In host
mkdir vbox-experiments && cd vbox-experiments
vagrant init hashicorp/precise64
vagrant up
vagrant ssh
# In virtual machine
sudo apt-get install nodejs npm nodejs-legacy -y; 
wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
nvm install 6; # Now using node v6.11.2 (npm v3.10.10)
npm install -g npm@5 && npm install -g npm@4 && npm install -g npm && npm install -g npm@3;
npm whatever
```

Replication with Ubuntu 16 gave me more interesting results, because I avoided use of `nvm`.

So let's go:
```
# In host
mkdir vbox-experiments && cd vbox-experiments
vagrant init ubuntu/xenial64
vagrant up && vagrant ssh
# In virtual machine
sudo apt-get update && sudo apt-get install nodejs npm nodejs-legacy -y ;
npm -v && node -v; # 3.5.2 && 4.2.6
sudo npm install -g npm@5 &&
sudo npm install -g npm@4 &&
sudo npm install -g npm &&
sudo npm install -g npm@3;
npm whatever; # works!
sudo npm whatever; # Cannot find module 'safe-buffer'
```

That's going beyond my comprehension.

**Comment by toadead** [comment]
It happened to me too. I had to reinstall NodeJS. That resolved the "Cannot find module 'safe-buffer'" error.
