### ISSUE TITLE
Error running `npm` after upgrading `npm`.

### ISSUE THREAD

**Issue by craigcitro** [npm/npm#18078]
#### I'm opening this issue because:

  - [X] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I loaded the `node:latest` docker container, and tried to upgrade `npm`. After that, `npm` was broken.

I looked around, but can't find an existing reported issue -- feel free to dupe if I've just missed it.

(To be clear, the full context here is that I was using this container as a base in which I ran another script; that script did an `npm install npm@latest -g`, which led to a broken `npm`.)

#### How can the CLI team reproduce the problem?

```
$ docker run -it -d --name nodetest node:latest
Unable to find image 'node:latest' locally
latest: Pulling from library/node
ad74af05f5a2: Pull complete
2b032b8bbe8b: Pull complete
a9a5b35f6ead: Pull complete
3245b5a1c52c: Pull complete
afa075743392: Pull complete
9fb9f21641cd: Pull complete
b1074d048a61: Pull complete
602b2c2b7041: Pull complete
Digest: sha256:353abd272c2332cdc5367e4db519213578b896931fcbe4d49c2adbaec3aeb5c5
Status: Downloaded newer image for node:latest
2cb2ca99b3677223ba77863a67b5101cb75eafe89f7b40773be3f1a78f1be341
$ docker exec -it nodetest /bin/bash
root@2cb2ca99b367:/# npm -v
5.3.0
root@2cb2ca99b367:/# npm install npm@latest -g
npm info it worked if it ends with ok
npm info using npm@5.3.0
npm info using node@v8.2.1
npm http fetch GET 200 https://registry.npmjs.org/npm 194ms
npm http fetch GET 200 https://registry.npmjs.org/npm/-/npm-5.3.0.tgz 2679ms
npm info lifecycle npm@5.3.0~preuninstall: npm@5.3.0
npm info lifecycle npm@5.3.0~uninstall: npm@5.3.0
npm info lifecycle npm@5.3.0~postuninstall: npm@5.3.0
npm info lifecycle libnpx@9.2.1~preuninstall: libnpx@9.2.1
npm info lifecycle libnpx@9.2.1~uninstall: libnpx@9.2.1
npm info lifecycle libnpx@9.2.1~postuninstall: libnpx@9.2.1
npm info lifecycle libnpx@9.2.0~preinstall: libnpx@9.2.0
npm info lifecycle npm@5.3.0~preinstall: npm@5.3.0
npm info linkStuff libnpx@9.2.0
npm info linkStuff npm@5.3.0
/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
/usr/local/bin/npx -> /usr/local/lib/node_modules/npm/bin/npx-cli.js
npm info lifecycle libnpx@9.2.0~install: libnpx@9.2.0
npm info lifecycle npm@5.3.0~install: npm@5.3.0
npm info lifecycle libnpx@9.2.0~postinstall: libnpx@9.2.0
npm info lifecycle npm@5.3.0~postinstall: npm@5.3.0
+ npm@5.3.0
updated 2 packages in 9.191s
npm info ok
root@2cb2ca99b367:/# npm -v
module.js:487
    throw err;
    ^

Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/unsupported.js:2:14)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
root@2cb2ca99b367:/#
```

FWIW, I also tried installing `semver` in the container, which then led to another missing package ... I stopped at 5.

### supporting information:

 - `npm -v` prints: an error
 - `node -v` prints: v8.2.1
 - `npm config get registry` prints: an error
 - Windows, OS X/macOS, or Linux?: Linux
 - Network issues:
   - Geographic location where npm was run: US
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [X] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by rmg** [comment]
This is reproducible with `node:6` as well.

Interestingly enough, it is _not_ reproducible with `node:4` (npm@2.15.11).
