### ISSUE TITLE
TypeError: resolveFrom.silent is not a function

### ISSUE THREAD

**Issue by edouard-lopez** [npm/npm#18089]
**related:** avajs/ava#1458.
 
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

```
/data/projects/peopledoc-ui/node_modules/resolve-cwd/index.js:5
module.exports.silent = moduleId => resolveFrom.silent(process.cwd(), moduleId);
                                                ^

TypeError: resolveFrom.silent is not a function
    at Function.module.exports.silent.moduleId [as silent] (/data/projects/peopledoc-ui/node_modules/resolve-cwd/index.js:5:49)
    at module.exports.filename (/data/projects/peopledoc-ui/node_modules/import-local/index.js:10:31)
    at Object.<anonymous> (/data/projects/peopledoc-ui/node_modules/ava/cli.js:7:5)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! peopledoc-ui@12.0.0 test-build: `ava ./tests/Brocfile.test.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the peopledoc-ui@12.0.0 test-build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ed8/.npm/_logs/2017-08-07T15_24_43_829Z-debug.log

```

### supporting information:

 - `npm -v` prints:

       5.3.0

 - `node -v` prints:

       v8.2.1

 - `npm config get registry` prints:

       https://registry.npmjs.org/

 - Windows, OS X/macOS, or Linux?:

```
lsb_release -a
No LSB modules are available.
Distributor ID: LinuxMint
Description:    Linux Mint 18.2 Sonya
Release:        18.2
Codename:       sonya
```

**Comment by edouard-lopez** [comment]
Fixed it with:

    npm uninstall ava
    npm install --save-dev ava

**Comment by nhulongctk10** [comment]
@edouard-lopez 
removing `node_modules & package-lock.json` fixed this issue.
