### ISSUE TITLE
I am unable to install firebase-tools 

### ISSUE THREAD

**Issue by ghost** [npm/npm#18113]
//
```

C:\WINDOWS\system32>npm  install -g firebase-tools
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
C:\Users\jay\AppData\Roaming\npm\firebase -> C:\Users\jay\AppData\Roaming\npm\node_modules\firebase-tools\bin\firebase

> node-zopfli@1.4.0 install C:\Users\jay\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\node-zopfli
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://node-zopfli.s3.amazonaws.com/Release/zopfli-v1.4.0-node-v57-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for node-zopfli@1.4.0 and node@8.2.1 (node-v57 ABI) (falling back to source compile with node-gyp)

C:\Users\jay\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\node-zopfli>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean )  else (node "" clean )

C:\Users\jay\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\node-zopfli>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure --fallback-to-build --module=C:\Users\jay\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\node-zopfli\lib\binding\node-v57-win32-x64\zopfli.node --module_name=zopfli --module_path=C:\Users\jay\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\node-zopfli\lib\binding\node-v57-win32-x64 )  else (node "" configure --fallback-to-build --module=C:\Users\jay\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\node-zopfli\lib\binding\node-v57-win32-x64\zopfli.node --module_name=zopfli --module_path=C:\Users\jay\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\node-zopfli\lib\binding\node-v57-win32-x64 )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Users\\jay\\AppData\\Roaming\\npm\\node_modules\\firebase-tools\\node_modules\\node-zopfli\\lib\\binding\\node-v57-win32-x64\\zopfli.node" "--module_name=zopfli" "--module_path=C:\\Users\\jay\\AppData\\Roaming\\npm\\node_modules\\firebase-tools\\node_modules\\node-zopfli\\lib\\binding\\node-v57-win32-x64"
gyp ERR! cwd C:\Users\jay\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\node-zopfli
gyp ERR! node -v v8.2.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=C:\Users\jay\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\node-zopfli\lib\binding\node-v57-win32-x64\zopfli.node --module_name=zopfli --module_path=C:\Users\jay\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\node-zopfli\lib\binding\node-v57-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\jay\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:125:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:921:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Windows_NT 10.0.15063
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\jay\\AppData\\Roaming\\npm\\node_modules\\firebase-tools\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\jay\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\node-zopfli
node-pre-gyp ERR! node -v v8.2.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.36
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=C:\Users\jay\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\node-zopfli\lib\binding\node-v57-win32-x64\zopfli.node --module_name=zopfli --module_path=C:\Users\jay\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\node-zopfli\lib\binding\node-v57-win32-x64' (1)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-zopfli@1.4.0 (node_modules\firebase-tools\node_modules\node-zopfli):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-zopfli@1.4.0 install: `node-pre-gyp install --fallback-to-build`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ firebase-tools@3.9.2
added 24 packages and updated 1 package in 92.901s
```

**Comment by zuolizhu** [comment]
I had the same problem. Try 
```
npm install -g node-pre-gyp
```
and it works for me!

**Comment by tolgabalci** [comment]
Installing it on three machines:
1st, worked without errors
2nd, had this node-pre-gyp ERR, installing node-pre-gyp fixed the problem
3rd,  had this node-pre-gyp ERR, installing node-pre-gyp does NOT fix the problem

**Attempting to download this package is resulting in a 403 Access Denied error:**
https://node-zopfli.s3.amazonaws.com/Release/zopfli-v1.4.0-node-v57-win32-x64.tar.gz
