### ISSUE TITLE
npm i -g npm failed and now won't reinstall either

### ISSUE THREAD

**Issue by dsl101** [npm/npm#18124]
#### I'm opening this issue because:

  - [X] npm is crashing.
  - [X] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
npm reported an update was available. I ran `npm i -g npm` and got an error. The last few lines from the log file are:

	6644 verbose unlock done using /root/.npm/_locks/staging-a072192f34a17023.lock for /usr/lib/node_modules/.staging
	6645 verbose stack Error: Refusing to delete /usr/share/man/man1/npm-access.1: /tmp/npm.7823/package/man/man1/npm-access.1 symlink target is not controlled by npm /usr/share/man/man1
	6645 verbose stack     at clobberFail (/usr/lib/node_modules/npm/lib/utils/gently-rm.js:151:12)
	6645 verbose stack     at isSafeToRm (/usr/lib/node_modules/npm/lib/utils/gently-rm.js:141:15)
	6645 verbose stack     at /usr/lib/node_modules/npm/lib/utils/gently-rm.js:84:5
	6645 verbose stack     at LOOP (/usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:7:26)
	6645 verbose stack     at /usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
	6645 verbose stack     at /usr/lib/node_modules/npm/lib/utils/gently-rm.js:168:14
	6645 verbose stack     at /usr/lib/node_modules/npm/node_modules/iferr/index.js:11:16
	6645 verbose stack     at /usr/lib/node_modules/npm/node_modules/iferr/index.js:11:16
	6645 verbose stack     at /usr/lib/node_modules/npm/node_modules/iferr/index.js:11:16
	6645 verbose stack     at /usr/lib/node_modules/npm/node_modules/iferr/index.js:11:16
	6645 verbose stack     at /usr/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:284:29
	6645 verbose stack     at FSReqWrap.oncomplete (fs.js:123:15)
	6646 verbose cwd /ki-apps/kistorm/firebase-functions
	6647 verbose Linux 3.2.0-4-amd64
	6648 verbose argv "/usr/bin/nodejs" "/usr/bin/npm" "i" "-g" "npm"
	6649 verbose node v6.9.2
	6650 verbose npm  v5.3.0
	6651 error path /usr/share/man/man1/npm-access.1
	6652 error code EEXIST
	6653 error Refusing to delete /usr/share/man/man1/npm-access.1: /tmp/npm.7823/package/man/man1/npm-access.1 symlink target is not controlled by npm /usr/share/man/man1
	6654 error File exists: /usr/share/man/man1/npm-access.1
	6655 error Move it away, and try again.
	6656 verbose exit [ 1, true ]

This resulted in no `npm` in `/usr/bin/`, so I couldn't try again. I tried reinstalling, and it _appeared_ to work:

	$ curl -L https://www.npmjs.org/install.sh | sh
	  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
	                                 Dload  Upload   Total   Spent    Left  Speed
	100   185  100   185    0     0    449      0 --:--:-- --:--:-- --:--:--   600
	100  6255  100  6255    0     0   6745      0 --:--:-- --:--:-- --:--:-- 6108k
	tar=/bin/tar
	version:
	tar (GNU tar) 1.26
	Copyright (C) 2011 Free Software Foundation, Inc.
	License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
	This is free software: you are free to change and redistribute it.
	There is NO WARRANTY, to the extent permitted by law.

	Written by John Gilmore and Jay Fenlason.
	install npm@latest
	fetching: https://registry.npmjs.org/npm/-/npm-5.3.0.tgz
	up to date in 0.053s
	/usr/bin/npm -> /usr/lib/node_modules/npm/bin/npm-cli.js
	/usr/bin/npx -> /usr/lib/node_modules/npm/bin/npx-cli.js
	+ npm@5.3.0
	added 1 package in 1.958s
	It worked

But I still have no `/usr/bin/npm` so I don't know what to try next...

### supporting information:

 - `npm -v` prints: `-bash: /usr/bin/npm: No such file or directory`
 - `node -v` prints: `v6.9.2`
 - `npm config get registry` prints: `-bash: /usr/bin/npm: No such file or directory`
 - Windows, OS X/macOS, or Linux?: Debian 7.11

**Comment by dsl101** [comment]
I was able to get npm back using `apt-get install nodejs`, as an update was available. I now have node 6.10.0 and npm 3.10.10.

I'm still not sure what caused the glitch to begin with though - happy to close this if it's not worth tracking down.
