### ISSUE TITLE
Uninstallation failed

### ISSUE THREAD

**Issue by rstawiarski** [npm/npm#18141]
#### I'm opening this issue because:

  - [ ] npm is failing during package uninstalling

#### What's going wrong?
Here is an output how it looks like:
`npm uninstall -g @angular/cli
Unhandled rejection Error: Argument #2: Expected string but got nullinstall loadIdealTree
    at addDependency (C:\Users\user_name\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:515:3)
    at C:\Users\user_name\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:463:5
    at C:\Users\user_name\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:52:35
    at Array.forEach (native)
    at C:\Users\user_name\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:52:11
    at Array.forEach (native)
    at asyncMap (C:\Users\user_name\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:51:8)
    at loadDeps (C:\Users\user_name\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:455:3)
    at Array.<anonymous> (C:\Users\user_name\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
    at LOOP (C:\Users\user_name\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
    at C:\Users\user_name\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:18:7
    at C:\Users\user_name\AppData\Roaming\npm\node_modules\npm\lib\install\and-finish-tracker.js:8:8
    at resolveBranchDeps.then (C:\Users\user_name\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:419:11)
    at tryCatcher (C:\Users\user_name\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\user_name\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\user_name\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user_name\AppData\Roaming\npm-cache\_logs\2017-08-11T10_54_13_406Z-debug.log
`

Here is a log:

`npm uninstall -g @angular/cli
Unhandled rejection Error: Argument #2: Expected string but got nullinstall loadIdealTree
    at addDependency (C:\Users\user_name\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:515:3)
    at C:\Users\user_name\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:463:5
    at C:\Users\user_name\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:52:35
    at Array.forEach (native)
    at C:\Users\user_name\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:52:11
    at Array.forEach (native)
    at asyncMap (C:\Users\user_name\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:51:8)
    at loadDeps (C:\Users\user_name\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:455:3)
    at Array.<anonymous> (C:\Users\user_name\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
    at LOOP (C:\Users\user_name\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
    at C:\Users\user_name\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:18:7
    at C:\Users\user_name\AppData\Roaming\npm\node_modules\npm\lib\install\and-finish-tracker.js:8:8
    at resolveBranchDeps.then (C:\Users\user_name\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:419:11)
    at tryCatcher (C:\Users\user_name\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\user_name\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\user_name\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user_name\AppData\Roaming\npm-cache\_logs\2017-08-11T10_54_13_406Z-debug.log
`

#### How can the CLI team reproduce the problem?
I don't know. I installed node, npm and angular cli quite long time ago. I tried to update it.

**Comment by rstawiarski** [comment]
This comment https://github.com/npm/npm/issues/16665#issuecomment-313318915 help me and I can uninstall package

**Comment by kenany** [comment]
@Radoslavski `npm --version`?

**Comment by rstawiarski** [comment]
I'm sorry but node.js was reinstalled and with it npm as well...

**Comment by kenany** [comment]
Closing then.
