### ISSUE TITLE
problem installing generator-aspnet

### ISSUE THREAD

**Issue by hoobtron** [npm/npm#18227]
I report this because: "npm ERR! This is an error with npm itself." (see below)

> comand: 

npm install generator-aspnet:WebApiController

>> output:

Unhandled rejection Error: Invalid tag name "generator-aspnet:WebApiController": Tags may not have any characters that encodeURIComponent encodes.
    at invalidTagName (C:\Users\name\AppData\Roaming\npm\node_modules\npm\node_modules\npm-package-arg\npa.js:76:15)
    at fromRegistry (C:\Users\name\AppData\Roaming\npm\node_modules\npm\node_modules\npm-package-arg\npa.js:265:13)
    at resolve (C:\Users\name\AppData\Roaming\npm\node_modules\npm\node_modules\npm-package-arg\npa.js:66:12)
    at npa (C:\Users\name\AppData\Roaming\npm\node_modules\npm\node_modules\npm-package-arg\npa.js:39:10)
    at C:\Users\name\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:200:16
    at C:\Users\name\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:52:35
    at Array.forEach (native)
    at C:\Users\name\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:52:11
    at Array.forEach (native)
    at asyncMap (C:\Users\name\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:51:8)
    at exports.getAllMetadata (C:\Users\name\AppData\Roaming\npm\node_modules\npm\lib\install\deps.js:199:3)
    at Object.Installer.loadArgMetadata (C:\Users\name\AppData\Roaming\npm\node_modules\npm\lib\install.js:325:3)
    at C:\Users\name\AppData\Roaming\npm\node_modules\npm\lib\install.js:656:16
    at BB.join.then (C:\Users\name\AppData\Roaming\npm\node_modules\npm\lib\install\read-shrinkwrap.js:41:16)
    at tryCatcher (C:\Users\name\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\name\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\name\AppData\Roaming\npm-cache\_logs\2017-08-18T13_11_31_940Z-debug.log

>>> content of log-file:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\name\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'generator-aspnet:WebApiController' ]
2 info using npm@5.3.0
3 info using node@v6.11.1
4 verbose config Skipping project config: C:\Users\name/.npmrc. (matches userconfig)
5 verbose npm-session 3b897897cb1b565b
6 silly install loadCurrentTree
7 silly install readLocalPackageData
8 error cb() never called!
9 error This is an error with npm itself. Please report this error at:
10 error <https://github.com/npm/npm/issues>

**Comment by salmanwaheed** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mkdirenv@gmail.com
    Domain salmanwaheed.info has exceeded the max emails per hour (163/150 (108%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext4.iad.github.net ([192.30.252.195]:34470 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by box1177.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1e7wf9-000m7M-ER
	for hello@salmanwaheed.info; Thu, 26 Oct 2017 22:54:31 -0600
Date: Thu, 26 Oct 2017 21:54:20 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1509080060;
	bh=Mxgc1lRAVTfjVyuPnrkFTGK8UQUf3xwokTOSlfjX2Bg=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=qdc8WeeCt+iDu+elk6fzTzhGsylQ7sKiH263J7AtkvidxgB9wpVQat2zI4LM+N8QM
	 rQJJpK3CaYgr7dICbO6bzFMDqAYp2NFpeMvPysfAepqME/MUruA7yihOuXl6WZSYIG
	 Fl8mjYd4t0wKDGqZ6uM/l4CAp0FeZ2IY1c3UUerg=
