### ISSUE TITLE
npx: Cannot find module 'D:\Program'

### ISSUE THREAD

**Issue by crisz** [npm/npm#18265]
#### I'm opening this issue because:

  - [x] **npx** is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):
  
#### What's going wrong?
npx throw an error in Windows at any invocation of the npx command. 
It looks like having troubles parsing the path because of the space between "Program" and "Files", even if in my opinion the error is caused by the installation of Node on the D:\ partition (which is not the main one)

The output I see is the following:
```
C:\Users\crist>npx
Command failed: D:\"Program Files"\nodejs\node.exe D:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js config get cache --parseable
module.js:487
    throw err;
    ^

Error: Cannot find module 'D:\Program'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```

#### How can the CLI team reproduce the problem?
- Install windows on the C:\ partition
- Install nodeJS + npm on another partition (D:\ in my case)
- Launch the npx command

### supporting information:

 - `npm -v` prints: 5.3.0
 - `node -v` prints: 8.2.1
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows 10
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by gyandeeps** [comment]
Duplicate of https://github.com/npm/npm/issues/17869
