### ISSUE TITLE
Cannot find module 'internal/fs'

### ISSUE THREAD

**Issue by datasmurfen** [npm/npm#18275]
Hello, I am getting this error when trying to install new packages. Have reinstalled npm twice, and tryed with diffrent packages, and versions. 

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'react-tabs',
1 verbose cli   '--save' ]
2 info using npm@4.2.0
3 info using node@v7.10.1
4 verbose stack Error: Cannot find module 'internal/fs'
4 verbose stack     at Function.Module._resolveFilename (module.js:470:15)
4 verbose stack     at Function.Module._load (module.js:418:25)
4 verbose stack     at Module.require (module.js:498:17)
4 verbose stack     at require (internal/module.js:20:19)
4 verbose stack     at evalmachine.<anonymous>:18:20
4 verbose stack     at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/cmd-shim/node_modules/graceful-fs/fs.js:11:1)
4 verbose stack     at Module._compile (module.js:571:32)
4 verbose stack     at Object.Module._extensions..js (module.js:580:10)
4 verbose stack     at Module.load (module.js:488:32)
4 verbose stack     at tryModuleLoad (module.js:447:12)
5 verbose cwd /home/oddvar/Code/my-project
6 error Linux 4.12.8-2-ARCH
7 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "react-tabs" "--save"
8 error node v7.10.1
9 error npm  v4.2.0
10 error code MODULE_NOT_FOUND
11 error Cannot find module 'internal/fs'
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]

**Comment by datasmurfen** [comment]
As a tempoary fix i downgraded npm version to 3.10.10 , and node to 6.11.0 .  It works now for some reason.

**Comment by datasmurfen** [comment]
Solved by: https://github.com/nodejs/node/issues/9377#issuecomment-257814895 
Running now on latest npm/node.
