### ISSUE TITLE
npm ignores --production in install when package-lock.json is present

### ISSUE THREAD

**Issue by everhardt** [npm/npm#18304]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I have a codebase with a devDependency that is a private repo. The server I'm running on does not have access to the private repo, but that's okay: it only requires the production dependencies.
When I copy my code (not the node_modules folder) to the server and run `npm install --production`, the install process fails with an error that the server cannot access the repo:

```
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/[xxx]/[xxx].git
npm ERR! 
npm ERR! ERROR: Repository not found.
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! exited with error code: 128
```

But if I do `npm install --production --no-shrinkwrap`, it runs fine. Probably, it has to do with the fact that the dependency is in `package-lock.json` (with `"dev": true`), as that is copied to the server as well. But I would have expected npm to honor the `--production` flag anyway and have ignored the items in `package-lock.json` with `"dev": true`.

I did also try to make it an optional dependency, but also then, npm complains if I run `npm install --no-optional`.

#### How can the CLI team reproduce the problem?
* add a dependency to package-lock with `"dev": true` with an invalid (or inaccessible) github repo
* run `npm install --production`

### supporting information:

 - `npm -v` prints: 5.3.0
 - `node -v` prints: v8.4.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux (Ubuntu 16.04.3 LTS)
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by sparecycles** [comment]
I'm guessing this is related to https://github.com/npm/npm/issues/17633

**Comment by benstevens48** [comment]
I am having a similar issue using npm 5.5.1 (the version installed with node 9.2) on Ubuntu 16.04. It correctly avoids installing dev dependencies, but it still runs some scripts associated with dev dependencies. For example, it is trying to install the node-sass binary, even though the node-sass package is not installed, hence produces error messages - see below.

```
ubuntu@ip-10-200-0-78:/srv/www/cm-framework/cm-framework$ sudo npm i --only="prod"

> node-sass@4.6.0 install /srv/www/cm-framework/cm-framework/node_modules/node-sass
> node scripts/install.js

Unable to save binary /srv/www/cm-framework/cm-framework/node_modules/node-sass/vendor/linux-x64-59 : { Error: EACCES: permission denied, mkdir '/srv/www/cm-framework/cm-framework/node_modules/node-sass/vendor'
    at Object.fs.mkdirSync (fs.js:905:18)
    at sync (/srv/www/cm-framework/cm-framework/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/srv/www/cm-framework/cm-framework/node_modules/mkdirp/index.js:77:24)
    at checkAndDownloadBinary (/srv/www/cm-framework/cm-framework/node_modules/node-sass/scripts/install.js:111:11)
    at Object.<anonymous> (/srv/www/cm-framework/cm-framework/node_modules/node-sass/scripts/install.js:154:1)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/srv/www/cm-framework/cm-framework/node_modules/node-sass/vendor' }

> node-sass@4.6.0 postinstall /srv/www/cm-framework/cm-framework/node_modules/node-sass
> node scripts/build.js

Building: /usr/bin/node /srv/www/cm-framework/cm-framework/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/bin/node',
gyp verb cli   '/srv/www/cm-framework/cm-framework/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@9.2.0 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import platform; print(platform.python_version());"` returned: "2.7.12\n"
gyp verb get node dir no --target version specified, falling back to host node version: 9.2.0
gyp verb command install [ '9.2.0' ]
gyp verb install input version string "9.2.0"
gyp verb install installing version: 9.2.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 9.2.0
gyp verb build dir attempting to create "build" dir: /srv/www/cm-framework/cm-framework/node_modules/node-sass/build
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/srv/www/cm-framework/cm-framework/node_modules/node-sass/build'
gyp ERR! System Linux 4.4.0-93-generic
gyp ERR! command "/usr/bin/node" "/srv/www/cm-framework/cm-framework/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /srv/www/cm-framework/cm-framework/node_modules/node-sass
gyp ERR! node -v v9.2.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.6.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.6.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2017-11-16T11_32_32_577Z-debug.log
```
