### ISSUE TITLE
Always tell me to verify my email when I publish a package?

### ISSUE THREAD

**Issue by TomIsion** [npm/npm#18315]
When I wanna publish my package, I use npm login before, then npm publish:

npm ERR! publish Failed PUT 403
npm ERR! code E403
npm ERR! you must verify your email before publishing a new package: https://www.npmjs.com/email-edit

but I verify my email address right before.

I am ensure I have verified my email: tomision@gmail.com

Here is the npm debug

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/8.2.1/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'publish' ]
2 info using npm@5.3.0
3 info using node@v8.2.1
4 verbose npm-session a36bb9ad2e4626f2
5 verbose publish [ '.' ]
6 info lifecycle gulp-test12345@1.0.0~prepublish: gulp-test12345@1.0.0
7 info lifecycle gulp-test12345@1.0.0~prepare: gulp-test12345@1.0.0
8 info lifecycle gulp-test12345@1.0.0~prepublishOnly: gulp-test12345@1.0.0
9 info lifecycle gulp-test12345@1.0.0~prepack: gulp-test12345@1.0.0
10 verbose tar pack [ '/var/folders/y9/1dftqpwd30bgg_rt3krlbwk00000gn/T/npm-32850-71234990/tmp/packing-a879b257/package.tgz',
10 verbose tar pack   '.' ]
11 verbose tarball /var/folders/y9/1dftqpwd30bgg_rt3krlbwk00000gn/T/npm-32850-71234990/tmp/packing-a879b257/package.tgz
12 verbose folder .
13 info lifecycle gulp-test12345@1.0.0~postpack: gulp-test12345@1.0.0
14 verbose getPublishConfig undefined
15 silly mapToRegistry name gulp-test12345
16 silly mapToRegistry using default registry
17 silly mapToRegistry registry https://registry.npmjs.org/
18 silly mapToRegistry data { type: 'tag',
18 silly mapToRegistry   registry: true,
18 silly mapToRegistry   where: undefined,
18 silly mapToRegistry   raw: 'gulp-test12345',
18 silly mapToRegistry   name: 'gulp-test12345',
18 silly mapToRegistry   escapedName: 'gulp-test12345',
18 silly mapToRegistry   scope: undefined,
18 silly mapToRegistry   rawSpec: '',
18 silly mapToRegistry   saveSpec: null,
18 silly mapToRegistry   fetchSpec: 'latest',
18 silly mapToRegistry   gitRange: undefined,
18 silly mapToRegistry   gitCommittish: undefined,
18 silly mapToRegistry   hosted: undefined }
19 silly mapToRegistry uri https://registry.npmjs.org/gulp-test12345
20 verbose publish registryBase https://registry.npmjs.org/
21 silly publish uploading /var/folders/y9/1dftqpwd30bgg_rt3krlbwk00000gn/T/npm-32850-71234990/tmp/fromDir-36ba0cd9/package.tgz
22 verbose request uri https://registry.npmjs.org/gulp-test12345
23 verbose request sending authorization for write operation
24 info attempt registry request try #1 at 09:20:55
25 verbose request using bearer token for auth
26 verbose request id 73b2592d907327de
27 http request PUT https://registry.npmjs.org/gulp-test12345
28 http 403 https://registry.npmjs.org/gulp-test12345
29 verbose headers { 'content-type': 'application/json',
29 verbose headers   'cache-control': 'max-age=300',
29 verbose headers   'content-length': '104',
29 verbose headers   'accept-ranges': 'bytes',
29 verbose headers   date: 'Sun, 27 Aug 2017 01:20:27 GMT',
29 verbose headers   via: '1.1 varnish',
29 verbose headers   connection: 'keep-alive',
29 verbose headers   'x-served-by': 'cache-nrt6131-NRT',
29 verbose headers   'x-cache': 'MISS',
29 verbose headers   'x-cache-hits': '0',
29 verbose headers   'x-timer': 'S1503796827.488668,VS0,VE332',
29 verbose headers   vary: 'Accept-Encoding, Accept' }
30 error publish Failed PUT 403
31 verbose stack Error: you must verify your email before publishing a new package: https://www.npmjs.com/email-edit : gulp-test12345
31 verbose stack     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:314:12)
31 verbose stack     at RegClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:302:14)
31 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:216:14)
31 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:188:22)
31 verbose stack     at emitTwo (events.js:125:13)
31 verbose stack     at Request.emit (events.js:213:7)
31 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1171:10)
31 verbose stack     at emitOne (events.js:115:13)
31 verbose stack     at Request.emit (events.js:210:7)
31 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1091:12)
31 verbose stack     at Object.onceWrapper (events.js:314:30)
31 verbose stack     at emitNone (events.js:110:20)
31 verbose stack     at IncomingMessage.emit (events.js:207:7)
31 verbose stack     at endReadableNT (_stream_readable.js:1045:12)
31 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:138:11)
31 verbose stack     at process._tickCallback (internal/process/next_tick.js:180:9)
32 verbose statusCode 403
33 verbose pkgid gulp-test12345
34 verbose cwd /Users/tom/Work/Test/Gulp/gulp-test12345
35 verbose Darwin 16.7.0
36 verbose argv "/usr/local/Cellar/node/8.2.1/bin/node" "/usr/local/bin/npm" "publish"
37 verbose node v8.2.1
38 verbose npm  v5.3.0
39 error code E403
40 error you must verify your email before publishing a new package: https://www.npmjs.com/email-edit : gulp-test12345
41 verbose exit [ 1, true ]

**Comment by Butterfly** [comment]
Hi, @TomIsion I'm a newbie here, but sometimes I get to help a little by searching around. Number 1 is you helped me see they have accounts over at the primary `npm` website. THANK YOU ! :smile: 

So I did a test drive only about verifying my email. After verifying it, I even signed out and back in. It's working ok, but I've never uploaded anything and don't have anything to upload to test right now. That might be a factor.

I next searched on your error message. Got a hit from that same website. You might be experiencing a potential glitch in something that went into effect on 2017.07.25. Just as you've found out, `npm` has a blog post detailing that:

[You need to have a verified email address to create new packages](http://blog.npmjs.org/post/163187838935/upcoming-change-verified-email-required)

You'll find a link to contact `npm` support under the "Recap" heading on that page just above. That support link specifically states that we can use that if we have problems with the new email verification process. Hope that helps. Good luck with your packages! :smile:

**Comment by qqqzhch** [comment]
i have the same problem 
i have  verify my email,but npm publish 
you must verify your email before publishing a new package: https://www.npmjs.com/email-edit

**Comment by TomIsion** [comment]
@qqqzhch I change a new account then it be success.

**Comment by limeandcoconut** [comment]
Try logging out and back in, using the cli.

**Comment by slashhuang** [comment]
![image](https://user-images.githubusercontent.com/11205526/37783603-e35aa4de-2e30-11e8-8ea5-970c3508ba24.png)
just login to your npm account,and verify your email by clicking link

I just solved this issue follow above steps.
hope it would be helpful

**Comment by slashhuang** [comment]
@qqqzhch   @TomIsion 
 
just came across same problem, solved by going through following steps .

1. login to your npm account on npm website,
2. scroll your page view to email section.
3. if you're not verified , it will show a hint to guide you  to verify your email.

try it, everything will be ok again
hope it would be helpful

**Comment by l5oo00** [comment]
Npm send a email to you, just open it and click the verify link.

**Comment by zhaoxiongfei** [comment]
@l5oo00 How to trigger?
