### ISSUE TITLE
notepad.exe issue with npm config edit

### ISSUE THREAD

**Issue by jiminfan9448** [npm/npm#18376]
#### I'm opening this issue because:

  - [x] npm is doing something I don't understand.

#### What's going wrong?

I'm trying to access and edit the npm config file, using the command "npm config edit". This has worked in the past, but it's been a few months since I've touched the project that's using node.js, and I figure some PATH variables might have changed which is causing npm to not recognize the location of notepad.exe. 

My full error log:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'config',
1 verbose cli   'edit' ]
2 info using npm@3.10.10
3 info using node@v6.10.2
4 verbose stack Error: spawn notepad.exe ENOENT
4 verbose stack     at exports._errnoException (util.js:1018:11)
4 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
4 verbose stack     at onErrorNT (internal/child_process.js:367:16)
4 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:80:11)
4 verbose stack     at process._tickCallback (internal/process/next_tick.js:104:9)
5 verbose cwd C:\Program Files\nodejs\node_modules\npm
6 error Windows_NT 6.3.9600
7 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "config" "edit"
8 error node v6.10.2
9 error npm  v3.10.10
10 error path notepad.exe
11 error code ENOENT
12 error errno ENOENT
13 error syscall spawn notepad.exe
14 error enoent spawn notepad.exe ENOENT
15 error enoent spawn notepad.exe ENOENT
15 error enoent This is most likely not a problem with npm itself
15 error enoent and is related to npm not being able to find a file.
16 verbose exit [ 1, true ]

I've done a clean install of node.js, I'm using windows 10. I need to configure the file so I can get through my work's proxy

node -v: v6.10.2
npm -v:3.10.10

But I'm still getting the same issue. Can someone please shed some light on my issue? Thanks in advance!

**Comment by jiminfan9448** [comment]
Follow up: 

I'm able to access and edit the .npmrc file, but it's a bit annoying to have to navigate to the User folder to do so everytime I need to make changes, as opposed to just using the npm config edit command
