### ISSUE TITLE
Unable to Publish Module

### ISSUE THREAD

**Issue by rbiggs** [npm/npm#18408]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong? Since upgrading to NPM v5.3.0 I've had nothing but problems. First of I couldn't do anything do to wrong permissions. My version of NPM was acquired through the binary Node (version 8.4.0) installer downloaded from the site. In the end I finally got NPM working locally by running `chown` on my /usr/local/lib folder. Sigh. 
Next problem, I have a module I'm trying to publish to NPM. I can run `npm pack` to produce a tar file and install it locally. It runs as expected without problem. However, when I try to publish it using `npm publish path/to/tar/file`, I get the following error:

```sh
npm ERR! Cannot read property 'algorithm' of undefined
```
Here's the complete log:

```sh
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'publish',
1 verbose cli   '/Users/rbiggs/Git/composi/composi-0.1.1.tgz' ]
2 info using npm@5.3.0
3 info using node@v8.4.0
4 verbose npm-session dd0ffd110a956172
5 verbose publish [ '/Users/rbiggs/Git/composi/composi-0.1.1.tgz' ]
6 silly cache add args [ '/Users/rbiggs/Git/composi/composi-0.1.1.tgz', undefined ]
7 verbose cache add spec /Users/rbiggs/Git/composi/composi-0.1.1.tgz
8 silly cache add parsed spec /Users/rbiggs/Git/composi/composi-0.1.1.tgz
9 silly prefetch no integrity hash provided for file:/Users/rbiggs/Git/composi/composi-0.1.1.tgz - fetching by manifest
10 silly prefetch file:/Users/rbiggs/Git/composi/composi-0.1.1.tgz done in 14ms
11 verbose stack TypeError: Cannot read property 'algorithm' of undefined
11 verbose stack     at Object.parse (/usr/local/lib/node_modules/npm/node_modules/ssri/index.js:115:17)
11 verbose stack     at pickContentSri (/usr/local/lib/node_modules/npm/node_modules/cacache/lib/content/read.js:74:20)
11 verbose stack     at Function.readStream (/usr/local/lib/node_modules/npm/node_modules/cacache/lib/content/read.js:37:3)
11 verbose stack     at Function.getStreamDigest [as byDigest] (/usr/local/lib/node_modules/npm/node_modules/cacache/get.js:120:23)
11 verbose stack     at Function.x.get.stream.byDigest (/usr/local/lib/node_modules/npm/node_modules/cacache/locales/en.js:22:59)
11 verbose stack     at cache.add.then (/usr/local/lib/node_modules/npm/lib/publish.js:111:30)
11 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
11 verbose stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
11 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
11 verbose stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
11 verbose stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
11 verbose stack     at Promise._fulfill (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:638:18)
11 verbose stack     at Promise._resolveCallback (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:432:57)
11 verbose stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:524:17)
11 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
11 verbose stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
12 verbose cwd /Users/rbiggs/Git/composi
13 verbose Darwin 16.7.0
14 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "publish" "/Users/rbiggs/Git/composi/composi-0.1.1.tgz"
15 verbose node v8.4.0
16 verbose npm  v5.3.0
17 error Cannot read property 'algorithm' of undefined
18 verbose exit [ 1, true ]
```

### supporting information:

 - `npm -v` prints: 5.3.0
 - `node -v` prints: 8.4.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: macOS Sierra 10.12.6 (16G29)
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by rbiggs** [comment]
FYI, I downgraded Node to version 6.11.3 and NPM to version 3.10.10 and was able to publish the module without a problem.

**Comment by groie** [comment]
We experience this exact problem as well.

**Comment by danielgreen** [comment]
Duplicate of #16723
