### ISSUE TITLE
NPM install private github repository with proxy

### ISSUE THREAD

**Issue by dlepaux** [npm/npm#18421]
I'm trying to install a private repository in a corporte environment with a proxy... But installation, with ID/Pass is not working.

To install this private github repository I do : ` npm install git+https://dlepaux:******@github.com/<namespace>/<repo_name>` but it don't work with this proxy ! I have tested this command at home and it work perfectly.

I have called my proxy provider and npm seem to contact github with port 80 (and not pass in the proxy). See [.npmcr file](#npmrc)

I have also tried to do : ` npm --proxy install http://proxyweb-s100v.corp.ads:3128 git+https://dlepaux:******@github.com/<namespace>/<repo_name>` 

### Debug / Configuration
**npm-debug.log**
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'git+https://dlepaux:******@github.com/<namespace>/<repo_name>' ]
2 info using npm@3.10.10
3 info using node@v6.11.2
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData git+https://dlepaux:******@github.com/<namespace>/<repo_name>
8 silly fetchOtherPackageData git+https://dlepaux:******@github.com/<namespace>/<repo_name>
9 silly cache add args [ 'git+https://dlepaux:******@github.com/<namespace>/<repo_name>',
9 silly cache add   null ]
10 verbose cache add spec git+https://dlepaux:******@github.com/<namespace>/<repo_name>
11 silly cache add parsed spec Result {
11 silly cache add   raw: 'git+https://dlepaux:******@github.com/<namespace>/<repo_name>',
11 silly cache add   scope: null,
11 silly cache add   escapedName: null,
11 silly cache add   name: null,
11 silly cache add   rawSpec: 'git+https://dlepaux:******@github.com/<namespace>/<repo_name>',
11 silly cache add   spec: 'git+https://dlepaux:******@github.com/<namespace>/<repo_name>.git',
11 silly cache add   type: 'hosted',
11 silly cache add   hosted:
11 silly cache add    { type: 'github',
11 silly cache add      ssh: 'git@github.com:<namespace>/<repo_name>.git',
11 silly cache add      sshUrl: 'git+ssh://git@github.com/<namespace>/<repo_name>.git',
11 silly cache add      httpsUrl: 'git+https://dlepaux:******@github.com/<namespace>/<repo_name>.git',
11 silly cache add      gitUrl: 'git://dlepaux:******@github.com/<namespace>/<repo_name>.git',
11 silly cache add      shortcut: 'github:<namespace>/<repo_name>',
11 silly cache add      directUrl: 'https://dlepaux:******@raw.githubusercontent.com/<namespace>/<repo_name>/master/package.json' } }
12 verbose addRemoteGit caching git+https://dlepaux:******@github.com/<namespace>/<repo_name>
13 verbose addRemoteGit git+https://dlepaux:******@github.com/<namespace>/<repo_name>.git is a repository hosted by github
14 silly tryClone cloning git+https://dlepaux:******@github.com/<namespace>/<repo_name>.git via git+https://dlepaux:******@github.com/<namespace>/<repo_name>.git
15 verbose tryClone git-https-dlepaux-******-github-com-<namespace>-<repo_name>-git-6f7cce03 not in flight; caching
16 verbose correctMkdir C:\Users\EXT-DLE\AppData\Roaming\npm-cache\_git-remotes correctMkdir not in flight; initializing
17 info git [ 'config', '--get', 'remote.origin.url' ]
18 silly validateExistingRemote git+https://dlepaux:******@github.com/<namespace>/<repo_name>.git remote.origin.url: https://dlepaux:******@github.com/<namespace>/<repo_name>.git
19 verbose validateExistingRemote git+https://dlepaux:******@github.com/<namespace>/<repo_name>.git is updating existing cached remote C:\Users\EXT-DLE\AppData\Roaming\npm-cache\_git-remotes\git-https-dlepaux-******-github-com-<namespace>-<repo_name>-git-6f7cce03
20 info git [ 'fetch', '-a', 'origin' ]
21 error git fetch -a origin (https://dlepaux:******@github.com/<namespace>/<repo_name>.git) fatal: unable to access 'https://dlepaux:******@github.com/<namespace>/<repo_name>.git/': Failed to connect to github.com port 443: Socket is not connected
22 silly fetchPackageMetaData Error: Command failed: git -c core.longpaths=true fetch -a origin
22 silly fetchPackageMetaData fatal: unable to access 'https://dlepaux:******@github.com/<namespace>/<repo_name>.git/': Failed to connect to github.com port 443: Socket is not connected
22 silly fetchPackageMetaData
22 silly fetchPackageMetaData     at ChildProcess.exithandler (child_process.js:198:12)
22 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
22 silly fetchPackageMetaData     at ChildProcess.emit (events.js:191:7)
22 silly fetchPackageMetaData     at maybeClose (internal/child_process.js:891:16)
22 silly fetchPackageMetaData     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
22 silly fetchPackageMetaData  error for git+https://dlepaux:******@github.com/<namespace>/<repo_name> { Error: Command failed: git -c core.longpaths=true fetch -a origin
22 silly fetchPackageMetaData fatal: unable to access 'https://dlepaux:******@github.com/<namespace>/<repo_name>.git/': Failed to connect to github.com port 443: Socket is not connected
22 silly fetchPackageMetaData
22 silly fetchPackageMetaData     at ChildProcess.exithandler (child_process.js:198:12)
22 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
22 silly fetchPackageMetaData     at ChildProcess.emit (events.js:191:7)
22 silly fetchPackageMetaData     at maybeClose (internal/child_process.js:891:16)
22 silly fetchPackageMetaData     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
22 silly fetchPackageMetaData   killed: false,
22 silly fetchPackageMetaData   code: 128,
22 silly fetchPackageMetaData   signal: null,
22 silly fetchPackageMetaData   cmd: 'git -c core.longpaths=true fetch -a origin' }
23 silly rollbackFailedOptional Starting
24 silly rollbackFailedOptional Finishing
25 silly runTopLevelLifecycles Finishing
26 silly install printInstalled
27 verbose stack Error: Command failed: git -c core.longpaths=true fetch -a origin
27 verbose stack fatal: unable to access 'https://dlepaux:******@github.com/<namespace>/<repo_name>.git/': Failed to connect to github.com port 443: Socket is not connected
27 verbose stack
27 verbose stack     at ChildProcess.exithandler (child_process.js:198:12)
27 verbose stack     at emitTwo (events.js:106:13)
27 verbose stack     at ChildProcess.emit (events.js:191:7)
27 verbose stack     at maybeClose (internal/child_process.js:891:16)
27 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
28 verbose cwd C:\Users\EXT-DLE\project\eplanif-fullcalendar-theme
29 error Windows_NT 6.1.7601
30 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "git+https://dlepaux:******@github.com/<namespace>/<repo_name>"
31 error node v6.11.2
32 error npm  v3.10.10
33 error code 128
34 error Command failed: git -c core.longpaths=true fetch -a origin
34 error fatal: unable to access 'https://dlepaux:******@github.com/<namespace>/<repo_name>.git/': Failed to connect to github.com port 443: Socket is not connected
35 error If you need help, you may report this error at:
35 error     <https://github.com/npm/npm/issues>
36 verbose exit [ 1, true ]
```

#### <a name="npmrc"></a> .npmrc
```
https-proxy=http://proxyweb-s100v.corp.ads:3128
HTTPS-PROXY=http://proxyweb-s100v.corp.ads:3128
HTTPS_PROXY=http://proxyweb-s100v.corp.ads:3128
https_proxy=http://proxyweb-s100v.corp.ads:3128
HTTP_PROXY=http://proxyweb-s100v.corp.ads:3128
http_proxy=http://proxyweb-s100v.corp.ads:3128
HTTP-PROXY=http://proxyweb-s100v.corp.ads:3128
http-proxy=http://proxyweb-s100v.corp.ads:3128
proxy=http://proxyweb-s100v.corp.ads:3128
PROXY=http://proxyweb-s100v.corp.ads:3128
strict-ssl=false
registry=http://registry.npmjs.org/
```
### Supporting Information:

 - `npm -v` prints: 3.10.10
 - `node -v` prints: 6.11.2
 - `npm config get registry` prints: http://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Win7
 - Network issues:
   - Geographic location where npm was run:
   - [x] I use a proxy to connect to the npm registry.
   - [x] I use a proxy to connect to the web.
   - [x] I use a proxy when downloading Git repos.

**Comment by JonWallsten** [comment]
I can also add it works with yarn. Not sure what NPM is doing differently?

Edit: I take that back actually. Also timeout.
