### ISSUE TITLE
Unabled to install package globally (logged in as root)

### ISSUE THREAD

**Issue by pmpcabral** [npm/npm#18466]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I'm trying to install the `full-icu` package globally and I'm getting an error (the error states that is a npm issue). I tried using both admin and root users, with `sudo` command and I'm getting the following errors

~~~~
/usr/local/bin/node-full-icu-path -> /usr/local/lib/node_modules/full-icu/node-icu-data.js

> full-icu@1.2.0 postinstall /usr/local/lib/node_modules/full-icu
> node postinstall.js

npm install icu4c-data@59l (Node 8.4.0 and small-icu 59.1) -> icudt59l.dat
full-icu$ /usr/local/bin/node /usr/local/lib/node_modules/npm/bin/npm-cli.js install icu4c-data@59l
Unhandled rejection Error: EACCES: permission denied, open '/root/.npm/_cacache/tmp/5dde5953'


┌───────────────────────────────────────────────────┐
│              npm update check failed              │
│        Try running with sudo or get access        │
│       to the local update config store via        │
│ sudo chown -R $USER:$(id -gn $USER) /root/.config │
└───────────────────────────────────────────────────┘
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
/usr/local/lib/node_modules/full-icu/install-spawn.js:41
		throw(Error(cmdPath + ' ' + args.join(' ') + ' --> status ' + spawned.status));
		^

Error: /usr/local/bin/node /usr/local/lib/node_modules/npm/bin/npm-cli.js install icu4c-data@59l --> status 1
    at npmInstallNpm (/usr/local/lib/node_modules/full-icu/install-spawn.js:41:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/full-icu/postinstall.js:68:2)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! full-icu@1.2.0 postinstall: `node postinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the full-icu@1.2.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-09-09T11_33_17_029Z-debug.log
~~~~
I executed the command `sudo chown -R $USER:$(id -gn $USER) /root/.config`, tried to install `full-icu` again and it didn't work.

#### How can the CLI team reproduce the problem?
Install the full-icu package globally
Link to Gist: https://gist.github.com/pmpcabral/a72731dbb41b4e07f6959c792f603b5a

### supporting information:

 - `npm -v` prints: 5.4.1
 - `node -v` prints: v8.4.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

Thank you in advance!

**Comment by pavelpichrt** [comment]
Did you manage to resolve the issue? I have the same problem, happens when I try to install the package both locally and globally.

**Comment by TahaBoulehmi** [comment]
Run as root:
```
npm set -g unsafe-perm
npm install -g full-icu
```
Instructions will be printed out on how to activate this data for your version of node.

Then run: 
`npm set -g unsafe-perm false`
