### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by dbashyal** [npm/npm#18478]
When I run `npm install` I get below error: Can you please help?

```
[webuser@dltrorg-server-01 trunk]$ npm install

> ursa@0.9.4 install /var/www/vhosts/dltr.org/httpdocs/server/public_html/trunk/node_modules/soap/node_modules/ursa
> node-gyp rebuild

gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: Cannot find module 'fstream'
gyp ERR! stack     at Function.Module._resolveFilename (module.js:489:15)
gyp ERR! stack     at Function.Module._load (module.js:439:25)
gyp ERR! stack     at Module.require (module.js:517:17)
gyp ERR! stack     at require (internal/module.js:11:18)
gyp ERR! stack     at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/node_modules/tar/lib/entry.js:14:15)
gyp ERR! stack     at Module._compile (module.js:573:30)
gyp ERR! stack     at Object.Module._extensions..js (module.js:584:10)
gyp ERR! stack     at Module.load (module.js:507:32)
gyp ERR! stack     at tryModuleLoad (module.js:470:12)
gyp ERR! stack     at Function.Module._load (module.js:462:3)
gyp ERR! System Linux 2.6.32-696.6.3.el6.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/webuser/shared/node_modules/soap/node_modules/ursa
gyp ERR! node -v v8.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ursa@0.9.4 (node_modules/soap/node_modules/ursa):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ursa@0.9.4 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 7

added 1 package in 3.226s
```
FYI

```
[webuser@dltrorg-server-01 trunk]$ npm doctor
Check                               Value                        Recommendation
npm ping                            OK
npm -v                              v5.4.1
node -v                             v8.4.0
npm config get registry             https://registry.npmjs.org/
which git                           /usr/bin/git
Perms check on cached files         ok
Perms check on global node_modules  ok
Perms check on local node_modules   ok
Verify cache contents               verified 182 tarballs
```

**Comment by softmantk** [comment]
I am facing the same issue now.  Cant update npm and install webpack globally. 


```
C:\WINDOWS\system32>npm update -g npm
npm ERR! code MODULE_NOT_FOUND
npm ERR! Cannot find module 'fstream'
```
