### ISSUE TITLE
Can't install packages like angular/cli on npm 5 [ENOTFOUND]

### ISSUE THREAD

**Issue by Kcorab** [npm/npm#18475]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?

I try to install angular/cli by the command `sudo npm install -g @angular/cli`. `sudo` is fine because only root is allowed to install apps globally.

But the following errors occur:

```
npm WARN registry Using stale data from https://registry.npmjs.org/ because the host is inaccessible -- are you offline?
npm WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR! network request to https://registry.npmjs.org/copy-webpack-plugin failed, reason: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'


   ╭─────────────────────────────────────╮
   │                                     │
   │   Update available 5.3.0 → 5.4.1    │
   │     Run npm i -g npm to update      │
   │                                     │
   ╰─────────────────────────────────────╯
```

See screenshot and logfile please.

![snapshot](https://user-images.githubusercontent.com/7406477/30247840-8963bb0c-961c-11e7-80c1-f44da92ba677.png)

[2017-09-10T08_58_12_274Z-debug.txt](https://github.com/npm/npm/files/1290419/2017-09-10T08_58_12_274Z-debug.txt)

#### How can the CLI team reproduce the problem?

Try to install angular/cli on Arch Linux by npm 5. ;)

### supporting information:

 - `npm -v` prints: 5.4.1
 - `node -v` prints: v8.4.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux (Arch Linux)
- `uname -a` prints: Linux XPS13-9350 4.12.10-1-ARCH #1 SMP PREEMPT Wed Aug 30 12:18:42 CEST 2017 x86_64 GNU/Linux
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
   - [x] I don't use a proxy and don't have any limitations.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).
   - [x] No Containers.

**Comment by Theerthagiri** [comment]
Hi, I am also facing same issue...

npm.debug.log file for your reference...

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   '@angular/cli' ]
2 info using npm@3.10.10
3 info using node@v6.11.3
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData @angular/cli
8 silly fetchNamedPackageData @angular/cli
9 silly mapToRegistry name @angular/cli
10 silly mapToRegistry scope (from package name) @angular
11 verbose mapToRegistry no registry URL found in name for scope @angular
12 silly mapToRegistry using default registry
13 silly mapToRegistry registry http://registry.npmjs.org/
14 silly mapToRegistry data Result {
14 silly mapToRegistry   raw: '@angular/cli',
14 silly mapToRegistry   scope: '@angular',
14 silly mapToRegistry   escapedName: '@angular%2fcli',
14 silly mapToRegistry   name: '@angular/cli',
14 silly mapToRegistry   rawSpec: '',
14 silly mapToRegistry   spec: 'latest',
14 silly mapToRegistry   type: 'tag' }
15 silly mapToRegistry uri http://registry.npmjs.org/@angular%2fcli
16 verbose request uri http://registry.npmjs.org/@angular%2fcli
17 verbose request no auth needed
18 info attempt registry request try #1 at 11:11:03 AM
19 verbose request id 58f9541c69a2f291
20 http request GET http://registry.npmjs.org/@angular%2fcli
21 info retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:80
22 info attempt registry request try #2 at 11:11:13 AM
23 http request GET http://registry.npmjs.org/@angular%2fcli
24 info retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:80
25 info attempt registry request try #3 at 11:12:13 AM
26 http request GET http://registry.npmjs.org/@angular%2fcli
27 silly fetchPackageMetaData Error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:80
27 silly fetchPackageMetaData     at errnoException (dns.js:28:10)
27 silly fetchPackageMetaData     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
27 silly fetchPackageMetaData  error for @angular/cli { Error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:80
27 silly fetchPackageMetaData     at errnoException (dns.js:28:10)
27 silly fetchPackageMetaData     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
27 silly fetchPackageMetaData   code: 'ENOTFOUND',
27 silly fetchPackageMetaData   errno: 'ENOTFOUND',
27 silly fetchPackageMetaData   syscall: 'getaddrinfo',
27 silly fetchPackageMetaData   hostname: 'registry.npmjs.org',
27 silly fetchPackageMetaData   host: 'registry.npmjs.org',
27 silly fetchPackageMetaData   port: 80 }
28 silly rollbackFailedOptional Starting
29 silly rollbackFailedOptional Finishing
30 silly runTopLevelLifecycles Finishing
31 silly install printInstalled
32 verbose stack Error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:80
32 verbose stack     at errnoException (dns.js:28:10)
32 verbose stack     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
33 verbose cwd H:\Examples\Angular2
34 error Windows_NT 6.1.7601
35 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@angular/cli"
36 error node v6.11.3
37 error npm  v3.10.10
38 error code ENOTFOUND
39 error errno ENOTFOUND
40 error syscall getaddrinfo
41 error network getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:80
42 error network This is most likely not a problem with npm itself
42 error network and is related to network connectivity.
42 error network In most cases you are behind a proxy or have bad network settings.
42 error network
42 error network If you are behind a proxy, please make sure that the
42 error network 'proxy' config is set properly.  See: 'npm help config'
43 verbose exit [ 1, true ]

**Comment by Dmitri85** [comment]
hi kcorab
did you solve your problem?

**Comment by Eminda** [comment]
I am also getting this problem. Does anyone know how to solve this?

**Comment by iam-sayco** [comment]
Hi,

I managed to solve the same issue by following second option in here: [https://docs.npmjs.com/getting-started/fixing-npm-permissions](https://docs.npmjs.com/getting-started/fixing-npm-permissions).

Hope it will help you too.
