### ISSUE TITLE
unable to start server

### ISSUE THREAD

**Issue by nikhil2882** [npm/npm#18489]
when ever i tried to start server using npm start ( using react create app ). this error came

> create-app@0.1.0 build-css /home/develpoers4fun/Desktop/programming/localrepsystem/paymentCollector/paymentcollector0.3
> node-sass src/ -o src/

module.js:471
    throw err;
    ^

Error: Cannot find module 'debug'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/develpoers4fun/Desktop/programming/localrepsystem/paymentCollector/paymentcollector0.3/node_modules/detect-port/lib/detect-port.js:3:31)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

npm ERR! Linux 4.8.0-59-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/lib/node_modules/npm/bin/npm-cli.js" "run" "start-js"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! create-app@0.1.0 start-js: `react-scripts start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the create-app@0.1.0 start-js script 'react-scripts start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the create-app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     react-scripts start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs create-app
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls create-app
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/develpoers4fun/Desktop/programming/localrepsystem/paymentCollector/paymentcollector0.3/npm-debug.log

**Comment by moar55** [comment]
Try to npm install debug manually and try again.
