### ISSUE TITLE
npm install issue

### ISSUE THREAD

**Issue by jithin-jain** [npm/npm#18498]
I am trying to npm install angular 4 starter proj but it fails.

I reinstalled node but yet it fails. I thought it may be some rights issue and so got admin rights too on my machine but yet it isn't working.

My 'npm-debug.log' file looks like this - 

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
.
.
.
338 verbose stack SyntaxError: Unexpected token < in JSON at position 0
338 verbose stack <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
338 verbose stack <html><head>
338 verbose stack <title>404 Not Found</title>
338 verbose stack </head><body>
338 verbose stack <h1>Not Found</h1>
338 verbose stack <p>The requested URL /@angular/animations was not found on this server.</p>
338 verbose stack <hr>
338 verbose stack <address>Apache/2.2.15 (CentOS) Server at registry.npmjs.org Port 80</address>
338 verbose stack </body></html>
338 verbose stack
338 verbose stack     at Object.parse (native)
338 verbose stack     at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:237:23)
338 verbose stack     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:210:14)
338 verbose stack     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:187:22)
338 verbose stack     at emitTwo (events.js:106:13)
338 verbose stack     at Request.emit (events.js:191:7)
338 verbose stack     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1048:10)
338 verbose stack     at emitOne (events.js:96:13)
338 verbose stack     at Request.emit (events.js:188:7)
338 verbose stack     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:969:12)
339 verbose cwd C:\Users\jithinj\Downloads\cli-quickstart
340 error Windows_NT 10.0.14393
341 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
342 error node v6.11.3
343 error npm  v3.10.10
344 error Unexpected token < in JSON at position 0
344 error <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
344 error <html><head>
344 error <title>404 Not Found</title>
344 error </head><body>
344 error <h1>Not Found</h1>
344 error <p>The requested URL /@angular/animations was not found on this server.</p>
344 error <hr>
344 error <address>Apache/2.2.15 (CentOS) Server at registry.npmjs.org Port 80</address>
344 error </body></html>
345 error If you need help, you may report this error at:
345 error     <https://github.com/npm/npm/issues>
346 verbose exit [ 1, true ]

My package.json is --

`{
  "name": "angular-io-example",
  "version": "1.0.0",
  "private": true,
  "description": "Example project from an angular.io guide.",
  "scripts": {
    "test:once": "karma start karma.conf.js --single-run",
    "build": "tsc -p src/",
    "serve": "lite-server -c=bs-config.json",
    "prestart": "npm run build",
    "start": "ng serve",
    "pretest": "npm run build",
    "test": "ng test",
    "pretest:once": "npm run build",
    "build:watch": "tsc -p src/ -w",
    "build:upgrade": "tsc",
    "serve:upgrade": "http-server",
    "build:aot": "ngc -p tsconfig-aot.json && rollup -c rollup-config.js",
    "serve:aot": "lite-server -c bs-config.aot.json",
    "build:babel": "babel src -d src --extensions \".es6\" --source-maps",
    "copy-dist-files": "node ./copy-dist-files.js",
    "i18n": "ng-xi18n",
    "lint": "tslint ./src/**/*.ts -t verbose",
    "ng": "ng",
    "e2e": "ng e2e"
  },
  "keywords": [],
  "author": "",
  "license": "MIT",
  "dependencies": {
    "@angular/animations": "~4.3.1",
    "@angular/common": "~4.3.1",
    "@angular/compiler": "~4.3.1",
    "@angular/compiler-cli": "~4.3.1",
    "@angular/core": "~4.3.1",
    "@angular/forms": "~4.3.1",
    "@angular/http": "~4.3.1",
    "@angular/platform-browser": "~4.3.1",
    "@angular/platform-browser-dynamic": "~4.3.1",
    "@angular/platform-server": "~4.3.1",
    "@angular/router": "~4.3.1",
    "@angular/tsc-wrapped": "~4.3.1",
    "@angular/upgrade": "~4.3.1",
    "angular-in-memory-web-api": "~0.4.0",
    "core-js": "^2.4.1",
    "rxjs": "^5.1.0",
    "systemjs": "0.19.39",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@types/angular": "^1.5.16",
    "@types/angular-animate": "^1.5.5",
    "@types/angular-cookies": "^1.4.2",
    "@types/angular-mocks": "^1.5.5",
    "@types/angular-resource": "^1.5.6",
    "@types/angular-route": "^1.3.2",
    "@types/angular-sanitize": "^1.3.3",
    "@types/jasmine": "2.5.36",
    "@types/node": "^6.0.45",
    "babel-cli": "^6.16.0",
    "babel-preset-angular2": "^0.0.2",
    "babel-preset-es2015": "^6.16.0",
    "canonical-path": "0.0.2",
    "concurrently": "^3.0.0",
    "http-server": "^0.9.0",
    "jasmine": "~2.4.1",
    "jasmine-core": "~2.4.1",
    "karma": "^1.3.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-phantomjs-launcher": "^1.0.2",
    "lite-server": "^2.2.2",
    "lodash": "^4.16.2",
    "phantomjs-prebuilt": "^2.1.7",
    "protractor": "~5.1.0",
    "rollup": "^0.41.6",
    "rollup-plugin-commonjs": "^8.0.2",
    "rollup-plugin-node-resolve": "2.0.0",
    "rollup-plugin-uglify": "^1.0.1",
    "source-map-explorer": "^1.3.2",
    "tslint": "^3.15.1",
    "typescript": "~2.3.2",
    "@angular/cli": "^1.2.7",
    "ts-node": "~3.0.4"
  },
  "repository": {}
}`

Can someone help me with this? What else can I try and how do i resolve?

**Comment by jithin-jain** [comment]
Finally started running for me. not sure about the solution though but I tried reinstalling many times.
A new thing I tried was deleting .npmrc file and clearing my temp folder.
