### ISSUE TITLE
Upgrade from 5.3.0 to 5.4.1 on Node 8.4.0 breaks

### ISSUE THREAD

**Issue by gregbacchus** [npm/npm#18493]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

After upgrading to npm v5.4.1, npm no longer works, but crashes with error below.

#### How can the CLI team reproduce the problem?

```
$ docker run -it --rm node:8.4.0 bash
root@c39c64888ed6:/# npm install npm@latest -g
npm info it worked if it ends with ok
npm info using npm@5.3.0
npm info using node@v8.4.0
npm http fetch GET 200 https://registry.npmjs.org/npm 171ms
npm http fetch GET 200 https://registry.npmjs.org/npm/-/npm-5.4.1.tgz 2235ms
npm info lifecycle npm@5.3.0~preuninstall: npm@5.3.0
npm info lifecycle npm@5.3.0~uninstall: npm@5.3.0
npm info lifecycle npm@5.3.0~postuninstall: npm@5.3.0
npm info lifecycle worker-farm@1.4.1~preuninstall: worker-farm@1.4.1
npm info lifecycle worker-farm@1.4.1~uninstall: worker-farm@1.4.1
npm info lifecycle worker-farm@1.4.1~postuninstall: worker-farm@1.4.1
npm info lifecycle pacote@2.7.38~preuninstall: pacote@2.7.38
npm info lifecycle pacote@2.7.38~uninstall: pacote@2.7.38
npm info lifecycle pacote@2.7.38~postuninstall: pacote@2.7.38
npm info lifecycle libnpx@9.2.1~preuninstall: libnpx@9.2.1
npm info lifecycle libnpx@9.2.1~uninstall: libnpx@9.2.1
npm info lifecycle libnpx@9.2.1~postuninstall: libnpx@9.2.1
npm info lifecycle write-file-atomic@2.1.0~preuninstall: write-file-atomic@2.1.0
npm info lifecycle write-file-atomic@2.1.0~uninstall: write-file-atomic@2.1.0
npm info lifecycle write-file-atomic@2.1.0~postuninstall: write-file-atomic@2.1.0
npm info lifecycle os-locale@2.0.0~preuninstall: os-locale@2.0.0
npm info lifecycle os-locale@2.0.0~uninstall: os-locale@2.0.0
npm info lifecycle os-locale@2.0.0~postuninstall: os-locale@2.0.0
npm info lifecycle execa@0.5.1~preuninstall: execa@0.5.1
npm info lifecycle execa@0.5.1~uninstall: execa@0.5.1
npm info lifecycle execa@0.5.1~postuninstall: execa@0.5.1
npm info lifecycle cross-spawn@4.0.2~preuninstall: cross-spawn@4.0.2
npm info lifecycle cross-spawn@4.0.2~uninstall: cross-spawn@4.0.2
npm info lifecycle cross-spawn@4.0.2~postuninstall: cross-spawn@4.0.2
npm info lifecycle which@1.2.14~preuninstall: which@1.2.14
npm info lifecycle which@1.2.14~uninstall: which@1.2.14
npm info lifecycle which@1.2.14~postuninstall: which@1.2.14
npm info lifecycle tar@2.2.1~preuninstall: tar@2.2.1
npm info lifecycle tar@2.2.1~uninstall: tar@2.2.1
npm info lifecycle tar@2.2.1~postuninstall: tar@2.2.1
npm info lifecycle block-stream@0.0.9~preuninstall: block-stream@0.0.9
npm info lifecycle block-stream@0.0.9~uninstall: block-stream@0.0.9
npm info lifecycle block-stream@0.0.9~postuninstall: block-stream@0.0.9
npm info lifecycle semver@5.3.0~preuninstall: semver@5.3.0
npm info lifecycle semver@5.3.0~uninstall: semver@5.3.0
npm info lifecycle semver@5.3.0~postuninstall: semver@5.3.0
npm info lifecycle read-package-json@2.0.10~preuninstall: read-package-json@2.0.10
npm info lifecycle read-package-json@2.0.10~uninstall: read-package-json@2.0.10
npm info lifecycle read-package-json@2.0.10~postuninstall: read-package-json@2.0.10
npm info lifecycle json-parse-helpfulerror@1.0.3~preuninstall: json-parse-helpfulerror@1.0.3
npm info lifecycle json-parse-helpfulerror@1.0.3~uninstall: json-parse-helpfulerror@1.0.3
npm info lifecycle json-parse-helpfulerror@1.0.3~postuninstall: json-parse-helpfulerror@1.0.3
npm info lifecycle jju@1.3.0~preuninstall: jju@1.3.0
npm info lifecycle jju@1.3.0~uninstall: jju@1.3.0
npm info lifecycle jju@1.3.0~postuninstall: jju@1.3.0
npm info lifecycle tar-fs@1.15.3~preuninstall: tar-fs@1.15.3
npm info lifecycle tar-fs@1.15.3~uninstall: tar-fs@1.15.3
npm info lifecycle tar-fs@1.15.3~postuninstall: tar-fs@1.15.3
npm info lifecycle tar-stream@1.5.4~preuninstall: tar-stream@1.5.4
npm info lifecycle tar-stream@1.5.4~uninstall: tar-stream@1.5.4
npm info lifecycle tar-stream@1.5.4~postuninstall: tar-stream@1.5.4
npm info lifecycle xtend@4.0.1~preuninstall: xtend@4.0.1
npm info lifecycle xtend@4.0.1~uninstall: xtend@4.0.1
npm info lifecycle xtend@4.0.1~postuninstall: xtend@4.0.1
npm info lifecycle end-of-stream@1.4.0~preuninstall: end-of-stream@1.4.0
npm info lifecycle end-of-stream@1.4.0~uninstall: end-of-stream@1.4.0
npm info lifecycle end-of-stream@1.4.0~postuninstall: end-of-stream@1.4.0
npm info lifecycle bl@1.2.1~preuninstall: bl@1.2.1
npm info lifecycle bl@1.2.1~uninstall: bl@1.2.1
npm info lifecycle bl@1.2.1~postuninstall: bl@1.2.1
npm info lifecycle pump@1.0.2~preuninstall: pump@1.0.2
npm info lifecycle pump@1.0.2~uninstall: pump@1.0.2
npm info lifecycle pump@1.0.2~postuninstall: pump@1.0.2
npm info lifecycle end-of-stream@1.4.0~preuninstall: end-of-stream@1.4.0
npm info lifecycle end-of-stream@1.4.0~uninstall: end-of-stream@1.4.0
npm info lifecycle end-of-stream@1.4.0~postuninstall: end-of-stream@1.4.0
npm info lifecycle agent-base@4.1.0~preuninstall: agent-base@4.1.0
npm info lifecycle agent-base@4.1.0~uninstall: agent-base@4.1.0
npm info lifecycle agent-base@4.1.0~postuninstall: agent-base@4.1.0
npm info lifecycle make-fetch-happen@2.4.13~preuninstall: make-fetch-happen@2.4.13
npm info lifecycle make-fetch-happen@2.4.13~uninstall: make-fetch-happen@2.4.13
npm info lifecycle make-fetch-happen@2.4.13~postuninstall: make-fetch-happen@2.4.13
npm info lifecycle node-fetch-npm@2.0.1~preuninstall: node-fetch-npm@2.0.1
npm info lifecycle node-fetch-npm@2.0.1~uninstall: node-fetch-npm@2.0.1
npm info lifecycle node-fetch-npm@2.0.1~postuninstall: node-fetch-npm@2.0.1
npm info lifecycle json-parse-helpfulerror@1.0.3~preuninstall: json-parse-helpfulerror@1.0.3
npm info lifecycle json-parse-helpfulerror@1.0.3~uninstall: json-parse-helpfulerror@1.0.3
npm info lifecycle json-parse-helpfulerror@1.0.3~postuninstall: json-parse-helpfulerror@1.0.3
npm info lifecycle jju@1.3.0~preuninstall: jju@1.3.0
npm info lifecycle jju@1.3.0~uninstall: jju@1.3.0
npm info lifecycle jju@1.3.0~postuninstall: jju@1.3.0
npm info lifecycle https-proxy-agent@2.0.0~preuninstall: https-proxy-agent@2.0.0
npm info lifecycle https-proxy-agent@2.0.0~uninstall: https-proxy-agent@2.0.0
npm info lifecycle https-proxy-agent@2.0.0~postuninstall: https-proxy-agent@2.0.0
npm info lifecycle agent-base@4.1.0~preuninstall: agent-base@4.1.0
npm info lifecycle agent-base@4.1.0~uninstall: agent-base@4.1.0
npm info lifecycle agent-base@4.1.0~postuninstall: agent-base@4.1.0
npm info lifecycle agent-base@4.1.0~preuninstall: agent-base@4.1.0
npm info lifecycle agent-base@4.1.0~uninstall: agent-base@4.1.0
npm info lifecycle agent-base@4.1.0~postuninstall: agent-base@4.1.0
npm info lifecycle string-width@2.1.0~preuninstall: string-width@2.1.0
npm info lifecycle string-width@2.1.0~uninstall: string-width@2.1.0
npm info lifecycle string-width@2.1.0~postuninstall: string-width@2.1.0
npm info lifecycle get-stream@2.3.1~preuninstall: get-stream@2.3.1
npm info lifecycle get-stream@2.3.1~uninstall: get-stream@2.3.1
npm info lifecycle get-stream@2.3.1~postuninstall: get-stream@2.3.1
npm info lifecycle pinkie-promise@2.0.1~preuninstall: pinkie-promise@2.0.1
npm info lifecycle pinkie-promise@2.0.1~uninstall: pinkie-promise@2.0.1
npm info lifecycle pinkie-promise@2.0.1~postuninstall: pinkie-promise@2.0.1
npm info lifecycle pinkie@2.0.4~preuninstall: pinkie@2.0.4
npm info lifecycle pinkie@2.0.4~uninstall: pinkie@2.0.4
npm info lifecycle pinkie@2.0.4~postuninstall: pinkie@2.0.4
npm info lifecycle object-assign@4.1.1~preuninstall: object-assign@4.1.1
npm info lifecycle object-assign@4.1.1~uninstall: object-assign@4.1.1
npm info lifecycle object-assign@4.1.1~postuninstall: object-assign@4.1.1
npm info lifecycle fstream-npm@1.2.1~preuninstall: fstream-npm@1.2.1
npm info lifecycle fstream-npm@1.2.1~uninstall: fstream-npm@1.2.1
npm info lifecycle fstream-npm@1.2.1~postuninstall: fstream-npm@1.2.1
npm info lifecycle fstream-ignore@1.0.5~preuninstall: fstream-ignore@1.0.5
npm info lifecycle fstream-ignore@1.0.5~uninstall: fstream-ignore@1.0.5
npm info lifecycle fstream-ignore@1.0.5~postuninstall: fstream-ignore@1.0.5
npm info lifecycle minimatch@3.0.4~preuninstall: minimatch@3.0.4
npm info lifecycle minimatch@3.0.4~uninstall: minimatch@3.0.4
npm info lifecycle minimatch@3.0.4~postuninstall: minimatch@3.0.4
npm info lifecycle brace-expansion@1.1.8~preuninstall: brace-expansion@1.1.8
npm info lifecycle brace-expansion@1.1.8~uninstall: brace-expansion@1.1.8
npm info lifecycle brace-expansion@1.1.8~postuninstall: brace-expansion@1.1.8
npm info lifecycle concat-map@0.0.1~preuninstall: concat-map@0.0.1
npm info lifecycle concat-map@0.0.1~uninstall: concat-map@0.0.1
npm info lifecycle concat-map@0.0.1~postuninstall: concat-map@0.0.1
npm info lifecycle balanced-match@1.0.0~preuninstall: balanced-match@1.0.0
npm info lifecycle balanced-match@1.0.0~uninstall: balanced-match@1.0.0
npm info lifecycle balanced-match@1.0.0~postuninstall: balanced-match@1.0.0
npm info lifecycle fstream@1.0.11~preuninstall: fstream@1.0.11
npm info lifecycle fstream@1.0.11~uninstall: fstream@1.0.11
npm info lifecycle fstream@1.0.11~postuninstall: fstream@1.0.11
npm info lifecycle shebang-regex@1.0.0~preinstall: shebang-regex@1.0.0
npm info lifecycle shebang-command@1.2.0~preinstall: shebang-command@1.2.0
npm info lifecycle get-stream@3.0.0~preinstall: get-stream@3.0.0
npm info lifecycle string-width@2.1.1~preinstall: string-width@2.1.1
npm info lifecycle fstream@1.0.11~preinstall: fstream@1.0.11
npm info lifecycle semver@5.3.0~preinstall: semver@5.3.0
npm info lifecycle block-stream@0.0.9~preinstall: block-stream@0.0.9
npm info lifecycle tar@2.2.1~preinstall: tar@2.2.1
npm info lifecycle balanced-match@1.0.0~preinstall: balanced-match@1.0.0
npm info lifecycle concat-map@0.0.1~preinstall: concat-map@0.0.1
npm info lifecycle brace-expansion@1.1.8~preinstall: brace-expansion@1.1.8
npm info lifecycle minimatch@3.0.4~preinstall: minimatch@3.0.4
npm info lifecycle ignore-walk@3.0.0~preinstall: ignore-walk@3.0.0
npm info lifecycle npm-bundled@1.0.3~preinstall: npm-bundled@1.0.3
npm info lifecycle npm-packlist@1.1.8~preinstall: npm-packlist@1.1.8
npm info lifecycle agent-base@4.1.1~preinstall: agent-base@4.1.1
npm info lifecycle agent-base@4.1.1~preinstall: agent-base@4.1.1
npm info lifecycle https-proxy-agent@2.1.0~preinstall: https-proxy-agent@2.1.0
npm info lifecycle json-parse-better-errors@1.0.1~preinstall: json-parse-better-errors@1.0.1
npm info lifecycle node-fetch-npm@2.0.2~preinstall: node-fetch-npm@2.0.2
npm info lifecycle make-fetch-happen@2.5.0~preinstall: make-fetch-happen@2.5.0
npm info lifecycle agent-base@4.1.1~preinstall: agent-base@4.1.1
npm info lifecycle json-parse-better-errors@1.0.1~preinstall: json-parse-better-errors@1.0.1
npm info lifecycle slash@1.0.0~preinstall: slash@1.0.0
npm info lifecycle read-package-json@2.0.12~preinstall: read-package-json@2.0.12
npm info lifecycle semver@5.4.1~preinstall: semver@5.4.1
npm info lifecycle yallist@3.0.2~preinstall: yallist@3.0.2
npm info lifecycle minipass@2.2.1~preinstall: minipass@2.2.1
npm info lifecycle minizlib@1.0.3~preinstall: minizlib@1.0.3
npm info lifecycle tar@4.0.1~preinstall: tar@4.0.1
npm info lifecycle which@1.3.0~preinstall: which@1.3.0
npm info lifecycle cross-spawn@5.1.0~preinstall: cross-spawn@5.1.0
npm info lifecycle execa@0.7.0~preinstall: execa@0.7.0
npm info lifecycle os-locale@2.1.0~preinstall: os-locale@2.1.0
npm info lifecycle signal-exit@3.0.2~preinstall: signal-exit@3.0.2
npm info lifecycle write-file-atomic@2.3.0~preinstall: write-file-atomic@2.3.0
npm info lifecycle libnpx@9.6.0~preinstall: libnpx@9.6.0
npm info lifecycle meant@1.0.0~preinstall: meant@1.0.0
npm info lifecycle npm-lifecycle@1.0.2~preinstall: npm-lifecycle@1.0.2
npm info lifecycle pacote@6.0.2~preinstall: pacote@6.0.2
npm info lifecycle worker-farm@1.5.0~preinstall: worker-farm@1.5.0
npm info lifecycle npm@5.4.1~preinstall: npm@5.4.1
npm info linkStuff shebang-regex@1.0.0
npm info linkStuff shebang-command@1.2.0
npm info linkStuff get-stream@3.0.0
npm info linkStuff string-width@2.1.1
npm info linkStuff fstream@1.0.11
npm info linkStuff semver@5.3.0
npm info linkStuff block-stream@0.0.9
npm info linkStuff tar@2.2.1
npm info linkStuff balanced-match@1.0.0
npm info linkStuff concat-map@0.0.1
npm info linkStuff brace-expansion@1.1.8
npm info linkStuff minimatch@3.0.4
npm info linkStuff ignore-walk@3.0.0
npm info linkStuff npm-bundled@1.0.3
npm info linkStuff npm-packlist@1.1.8
npm info linkStuff agent-base@4.1.1
npm info linkStuff agent-base@4.1.1
npm info linkStuff https-proxy-agent@2.1.0
npm info linkStuff json-parse-better-errors@1.0.1
npm info linkStuff node-fetch-npm@2.0.2
npm info linkStuff make-fetch-happen@2.5.0
npm info linkStuff agent-base@4.1.1
npm info linkStuff json-parse-better-errors@1.0.1
npm info linkStuff slash@1.0.0
npm info linkStuff read-package-json@2.0.12
npm info linkStuff semver@5.4.1
npm info linkStuff yallist@3.0.2
npm info linkStuff minipass@2.2.1
npm info linkStuff minizlib@1.0.3
npm info linkStuff tar@4.0.1
npm info linkStuff which@1.3.0
npm info linkStuff cross-spawn@5.1.0
npm info linkStuff execa@0.7.0
npm info linkStuff os-locale@2.1.0
npm info linkStuff signal-exit@3.0.2
npm info linkStuff write-file-atomic@2.3.0
npm info linkStuff libnpx@9.6.0
npm info linkStuff meant@1.0.0
npm info linkStuff npm-lifecycle@1.0.2
npm info linkStuff pacote@6.0.2
npm info linkStuff worker-farm@1.5.0
npm info linkStuff npm@5.4.1
/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
/usr/local/bin/npx -> /usr/local/lib/node_modules/npm/bin/npx-cli.js
npm info lifecycle shebang-regex@1.0.0~install: shebang-regex@1.0.0
npm info lifecycle shebang-command@1.2.0~install: shebang-command@1.2.0
npm info lifecycle get-stream@3.0.0~install: get-stream@3.0.0
npm info lifecycle string-width@2.1.1~install: string-width@2.1.1
npm info lifecycle fstream@1.0.11~install: fstream@1.0.11
npm info lifecycle semver@5.3.0~install: semver@5.3.0
npm info lifecycle block-stream@0.0.9~install: block-stream@0.0.9
npm info lifecycle tar@2.2.1~install: tar@2.2.1
npm info lifecycle balanced-match@1.0.0~install: balanced-match@1.0.0
npm info lifecycle concat-map@0.0.1~install: concat-map@0.0.1
npm info lifecycle brace-expansion@1.1.8~install: brace-expansion@1.1.8
npm info lifecycle minimatch@3.0.4~install: minimatch@3.0.4
npm info lifecycle ignore-walk@3.0.0~install: ignore-walk@3.0.0
npm info lifecycle npm-bundled@1.0.3~install: npm-bundled@1.0.3
npm info lifecycle npm-packlist@1.1.8~install: npm-packlist@1.1.8
npm info lifecycle agent-base@4.1.1~install: agent-base@4.1.1
npm info lifecycle agent-base@4.1.1~install: agent-base@4.1.1
npm info lifecycle https-proxy-agent@2.1.0~install: https-proxy-agent@2.1.0
npm info lifecycle json-parse-better-errors@1.0.1~install: json-parse-better-errors@1.0.1
npm info lifecycle node-fetch-npm@2.0.2~install: node-fetch-npm@2.0.2
npm info lifecycle make-fetch-happen@2.5.0~install: make-fetch-happen@2.5.0
npm info lifecycle agent-base@4.1.1~install: agent-base@4.1.1
npm info lifecycle json-parse-better-errors@1.0.1~install: json-parse-better-errors@1.0.1
npm info lifecycle slash@1.0.0~install: slash@1.0.0
npm info lifecycle read-package-json@2.0.12~install: read-package-json@2.0.12
npm info lifecycle semver@5.4.1~install: semver@5.4.1
npm info lifecycle yallist@3.0.2~install: yallist@3.0.2
npm info lifecycle minipass@2.2.1~install: minipass@2.2.1
npm info lifecycle minizlib@1.0.3~install: minizlib@1.0.3
npm info lifecycle tar@4.0.1~install: tar@4.0.1
npm info lifecycle which@1.3.0~install: which@1.3.0
npm info lifecycle cross-spawn@5.1.0~install: cross-spawn@5.1.0
npm info lifecycle execa@0.7.0~install: execa@0.7.0
npm info lifecycle os-locale@2.1.0~install: os-locale@2.1.0
npm info lifecycle signal-exit@3.0.2~install: signal-exit@3.0.2
npm info lifecycle write-file-atomic@2.3.0~install: write-file-atomic@2.3.0
npm info lifecycle libnpx@9.6.0~install: libnpx@9.6.0
npm info lifecycle meant@1.0.0~install: meant@1.0.0
npm info lifecycle npm-lifecycle@1.0.2~install: npm-lifecycle@1.0.2
npm info lifecycle pacote@6.0.2~install: pacote@6.0.2
npm info lifecycle worker-farm@1.5.0~install: worker-farm@1.5.0
npm info lifecycle npm@5.4.1~install: npm@5.4.1
npm info lifecycle shebang-regex@1.0.0~postinstall: shebang-regex@1.0.0
npm info lifecycle shebang-command@1.2.0~postinstall: shebang-command@1.2.0
npm info lifecycle get-stream@3.0.0~postinstall: get-stream@3.0.0
npm info lifecycle string-width@2.1.1~postinstall: string-width@2.1.1
npm info lifecycle fstream@1.0.11~postinstall: fstream@1.0.11
npm info lifecycle semver@5.3.0~postinstall: semver@5.3.0
npm info lifecycle block-stream@0.0.9~postinstall: block-stream@0.0.9
npm info lifecycle tar@2.2.1~postinstall: tar@2.2.1
npm info lifecycle balanced-match@1.0.0~postinstall: balanced-match@1.0.0
npm info lifecycle concat-map@0.0.1~postinstall: concat-map@0.0.1
npm info lifecycle brace-expansion@1.1.8~postinstall: brace-expansion@1.1.8
npm info lifecycle minimatch@3.0.4~postinstall: minimatch@3.0.4
npm info lifecycle ignore-walk@3.0.0~postinstall: ignore-walk@3.0.0
npm info lifecycle npm-bundled@1.0.3~postinstall: npm-bundled@1.0.3
npm info lifecycle npm-packlist@1.1.8~postinstall: npm-packlist@1.1.8
npm info lifecycle agent-base@4.1.1~postinstall: agent-base@4.1.1
npm info lifecycle agent-base@4.1.1~postinstall: agent-base@4.1.1
npm info lifecycle https-proxy-agent@2.1.0~postinstall: https-proxy-agent@2.1.0
npm info lifecycle json-parse-better-errors@1.0.1~postinstall: json-parse-better-errors@1.0.1
npm info lifecycle node-fetch-npm@2.0.2~postinstall: node-fetch-npm@2.0.2
npm info lifecycle make-fetch-happen@2.5.0~postinstall: make-fetch-happen@2.5.0
npm info lifecycle agent-base@4.1.1~postinstall: agent-base@4.1.1
npm info lifecycle json-parse-better-errors@1.0.1~postinstall: json-parse-better-errors@1.0.1
npm info lifecycle slash@1.0.0~postinstall: slash@1.0.0
npm info lifecycle read-package-json@2.0.12~postinstall: read-package-json@2.0.12
npm info lifecycle semver@5.4.1~postinstall: semver@5.4.1
npm info lifecycle yallist@3.0.2~postinstall: yallist@3.0.2
npm info lifecycle minipass@2.2.1~postinstall: minipass@2.2.1
npm info lifecycle worker-farm@1.4.1~preuninstall: worker-farm@1.4.1
npm info lifecycle minizlib@1.0.3~postinstall: minizlib@1.0.3
npm info lifecycle tar@4.0.1~postinstall: tar@4.0.1
npm info lifecycle which@1.3.0~postinstall: which@1.3.0
npm info lifecycle cross-spawn@5.1.0~postinstall: cross-spawn@5.1.0
npm info lifecycle execa@0.7.0~postinstall: execa@0.7.0
npm info lifecycle os-locale@2.1.0~postinstall: os-locale@2.1.0
npm info lifecycle signal-exit@3.0.2~postinstall: signal-exit@3.0.2
npm info lifecycle write-file-atomic@2.3.0~postinstall: write-file-atomic@2.3.0
npm info lifecycle libnpx@9.6.0~postinstall: libnpx@9.6.0
npm info lifecycle meant@1.0.0~postinstall: meant@1.0.0
npm info lifecycle npm-lifecycle@1.0.2~postinstall: npm-lifecycle@1.0.2
npm info lifecycle pacote@6.0.2~postinstall: pacote@6.0.2
npm info lifecycle worker-farm@1.5.0~postinstall: worker-farm@1.5.0
npm info lifecycle npm@5.4.1~postinstall: npm@5.4.1
+ npm@5.4.1
added 22 packages, removed 22 packages and updated 20 packages in 10.118s
npm info ok
root@c39c64888ed6:/# npm
module.js:491
    throw err;
    ^
Error: Cannot find module 'npmlog'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:22:13
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:92:3)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
root@c39c64888ed6:/#
```

### supporting information:

(before update attempt)
 - `npm -v` prints: 5.3.0
 - `node -v` prints: v8.4.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux (docker image)
 - Network issues:
   - Geographic location where npm was run: 
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [x] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by brandondoran** [comment]
I upgraded to 5.4.1 from 5.3 hoping to fix https://github.com/npm/npm/issues/17781. But now I'm running into this issue.

After upgrading, any npm command fails:
```bash
/ # npm -v
module.js:491
    throw err;
    ^

Error: Cannot find module 'npmlog'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:22:13
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:92:3)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
```

Running node:8.4.0-alpine docker image.

To reproduce:
```bash
docker run --rm node:8.4.0-alpine sh -c "npm i -g npm@5.4.1 && npm -v"
```

**Comment by brandondoran** [comment]
It turns out the node alpine image comes with yarn pre-installed. If I use yarn to install npm 5.4.1, everything is happy:
```
yarn global add npm@5.4.1 
```

**Comment by jeking3** [comment]
I just ran into the same issue on Ubuntu Xenial:
```
root@0709e70cce7c:/thrift/src# node --version
v8.4.0
root@0709e70cce7c:/thrift/src# npm --version
5.3.0
root@0709e70cce7c:/thrift/src# npm install -g npm
/usr/bin/npm -> /usr/lib/node_modules/npm/bin/npm-cli.js
/usr/bin/npx -> /usr/lib/node_modules/npm/bin/npx-cli.js
+ npm@5.4.1
added 22 packages, removed 22 packages and updated 20 packages in 10.064s
root@0709e70cce7c:/thrift/src# npm list
module.js:491
    throw err;
    ^

Error: Cannot find module 'npmlog'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at /usr/lib/node_modules/npm/bin/npm-cli.js:22:13
    at Object.<anonymous> (/usr/lib/node_modules/npm/bin/npm-cli.js:92:3)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
```
