### ISSUE TITLE
npm install should not create symlinks

### ISSUE THREAD

**Issue by paulodiovani** [npm/npm#18503]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

1. `npm install <folder>` will create a symlink to `<folder>` in the package directory

    This can lead to unpredictable behavior and since there is a command for creating links `npm link` I believe `npm install` should **always** install the package.

    Some possible problems that will break the installation:

    - Remove the origin package folder
    - Move the package elsewhere (e.g. install on a flash drive for use anywhere)

1. `npm install`

    > In global mode (ie, with -g or --global appended to the command), it installs the current package context (ie, the current working directory) as a global package.

    But instead, it will create a link to the current folder as the package, which lead to the same problems described above.

    If the original folder is removed, the package cannot even be installed again, since a broken link remain in bin dir.
   
#### How can the CLI team reproduce the problem?

1. Create or download a package which contain an executable in a folder (e.g. `git clone https://github.com/paulodiovani/foaas-client`)
1. Enter the folder: `cd foaas-client`
1. Install as global dependency: `npm install -g`
1. Remove folder: `cd .. && rm -r foaas-client`
1. Try to run the executable:

    ```bash
    ➜  foaas              
    zsh: command not found: foaas
    ```

### supporting information:

```
➜  ~ npm -v  
5.3.0
➜  ~ node -v 
v8.4.0
➜  ~ npm config get registry
https://registry.npmjs.org/
➜  ~ uname -a
Linux paulodiovani-dell 4.12.9-1-zen #1 ZEN SMP PREEMPT Fri Aug 25 02:57:04 UTC 2017 x86_64 GNU/Linux
```

**Comment by griffonn** [comment]
An example of a problem: installing a package from Windows network share.
Example: `npm install "\\myserver\\mypackage\\2.0.0"` will [try to] create a symlink (actually - a junction) to the network folder instead of copying it. Unfortunately, [NTFS junctions](https://en.wikipedia.org/wiki/NTFS_junction_point) is only supported with local absolute paths, hence the link created by npm is broken.

**Comment by bobzhang** [comment]
FWIW, npm3 used to have the desired behavior, but later changed. The new behavior is indeed faster, but not correct/reliable

**Comment by robogeek** [comment]
I was going to file my own issue but this is close enough -- I wish to add a few more observations.

By way of describing intent -- whenever I have local modifications to a package, I `npm install /path/to/package/source` so I can test the package.  I am accustomed to editing the package, then in the place where I need to test the package doing that local install, then rerunning my test.  I don't want to push this code to a repository or publish to npm because it is untested/unverified code that I am debugging.

The core issue is that somewhere at some point in time, npm began symlinking packages rather than doing the install.  This practice of symlinking is breaking things in big ways.

1. It **MODIFIES** my `package.json` file.  This is completely wrong behavior on npm's part.  It should be **consulting** the `package.json` and not **modifying** it.  The modification is to turn a dependency of `"akashacms-base": ">=0.6"` into `"akashacms-base": "file:/path/to/akashacms-base"`.  What if I forgetfully commit the `package.json` with this modification?  I will have broken my repository because the `package.json` is now horribly broken.

2. The packages I am working with have cross dependencies that get broken.  That is, `akashacms-base` references `akasharender` which breaks when both are installed as symlinks.

# Reproducing the problem

Versions:

```
$ node --version
v8.9.1
$ npm --version
5.5.1
```

Set up the code to reproduce the problem

```
$ git clone https://github.com/akashacms/akasharender.git
$ git clone https://github.com/akashacms/akashacms-base.git
$ git clone https://github.com/akashacms/akashacms-example.git
$ cd akashacms-example/
$ npm install
$ npm install ../akashacms-base/
$ npm install ../akasharender/
```

At this point notice that `package.json` has been rewritten to contain:

```
    "akashacms-base": "file:../akashacms-base",
    "akasharender": "file:../akasharender",
```

This is WRONG and INCORRECT.

Then you run:

```
$ npm run build

> akashacms-example@0.6.4 prebuild /Volumes/Extra/t/akashacms-example
> akasharender copy-assets config.js

module.js:538
    throw err;
    ^

Error: Cannot find module 'akasharender'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Volumes/Extra/t/akashacms-base/index.js:26:16)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! akashacms-example@0.6.4 prebuild: `akasharender copy-assets config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the akashacms-example@0.6.4 prebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/david/.npm/_logs/2017-11-25T04_54_53_721Z-debug.log
```

That line of code tries to require('akasharender')

```
const akasha = require('akasharender');
```

But they have been symlinked

```
$ ls -ld node_modules/akasharender node_modules/akashacms-base
lrwxr-xr-x  1 david  admin  20 Nov 24 20:47 node_modules/akashacms-base -> ../../akashacms-base
lrwxr-xr-x  1 david  admin  18 Nov 24 20:54 node_modules/akasharender -> ../../akasharender
```

The problem is that both have a physical location outside the `node_modules` directory of the place where I'm testing the code.  Hence `akashacms-base` cannot find `akasharender` because everything is wonky and wrong.

# Attempted workarounds

I tried doing this:

```
$ cat .npmrc 
{ "link": false }
```

The `link` option is described as causing the `link` behavior, so I thought setting it to false would turn off this behavior.  That's not the case.

I tried creating a tarball from the local working directory.  That's an extra step of overhead that I might have to do.  That does cause the module to be installed correctly, and not a symlink, but there are several problems:

1. The `package.json` now gets modified to `    "akasharender": "file:../../../../Users/david/akasharender/akasharender.tar",` which is COMPLETELY WRONG
1. There's a complaint about one of the modules being a git repository (because the tarball picked up the `.git` directory).  So it would add even more unwanted overhead to force me to strip out the `.git` directory when creating the tarball so I can do a local install.

The only thing I have left to do is this thing that is a repugnant idea.  Namely, that I commit all test changes to the repository, and in `package.json` use a `github:` URL to refer to the repository.  That works as expected but it means that I must commit untested/unverified code to the repository, which is obviously the wrong thing to do.

**Comment by robogeek** [comment]
I have a solution to part of the problem I described -- and a partial solution to the other half.

1. The `package.json` is modified when performing a local install.  This is due to the new default behavior of acting as if `--save` had been used.  Using `--no-save` turns off `package.json` modifications.  Using `npm config set save false` also turns off `package.json` modifications.
1. Local install makes a symlink.  This is because in npm@5 they changed `file:` to act as `link:` for installation -- because someone thought this would be an improvement.  I beg to disagree but what the heck.  See https://github.com/npm/npm/pull/15900 for the discussion on that feature.

For the second issue, I have identified a workaround that's not too bad.

In the local package you're installing FROM ... do:

```
package1$ npm pack
```

This builds a tarball containing what would be installed by that package.

In the project directory where you wish to install that package ... do:

```
package2$ npm install /path/to/package1.tgz --no-save
```

This does a correct proper install of the package, and with `--no-save` or the config save=false flag no modifications to `package.json` will occur.

See: https://techsparx.com/nodejs/news/2017/npm5-major-error.html

**Comment by agirorn** [comment]
I have another case where require does not work as expected. When the module is linked instead of fully installed it gets its own node_modules folder and can not require modules from its parent module/package. So modules installed from the registry and installed from the filesystem do not work in the same way.

Currently, we are using [install-local](https://github.com/nicojs/node-install-local) to install from the filesystem.
