### ISSUE TITLE
npx bug ?

### ISSUE THREAD

**Issue by andreGarvin** [npm/npm#18516]
#### I'm opening this issue because:
  - [x] Other (_see below for feature requests_):

#### What's going wrong?
This error pops when I use npm, I am on a windows machaine 64 bit

```bash
Command failed: C:\"Program Files"\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js config get cache --parseable
module.js:491
    throw err;
    ^

Error: Cannot find module 'C:\Program'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3
```

**Comment by molant** [comment]
Duplicate of #17869
