### ISSUE TITLE
npm ERR! notarget No compatible version found: http@2.0.0-rc.1

### ISSUE THREAD

**Issue by Vrajmas** [npm/npm#18526]
I can not install http dependencie on angular 2
My package.json

> {
  "name": "angular2-quickstart",
  "version": "1.0.0",
  "scripts": {
    "start": "concurrent \"npm run tsc:w\" \"npm run lite\" ",
    "tsc": "tsc",
    "tsc:w": "tsc -w",
    "lite": "lite-server",
    "typings": "typings",
    "postinstall": "typings install"
  },
  "license": "ISC",
  "dependencies": {
    "angular2": "2.0.0-beta.7",
    "bootstrap": "^3.3.7",
    "es6-promise": "^3.0.2",
    "es6-shim": "^0.33.3",
    "ngx-bootstrap": "^1.9.3",
    "reflect-metadata": "0.1.2",
    "rxjs": "5.0.0-beta.2",
    "systemjs": "0.19.22",
    "http": "2.0.0-rc.1",
    "zone.js": "0.5.15"
  },
  "devDependencies": {
    "concurrently": "^2.0.0",
    "lite-server": "^2.1.0",
    "typescript": "^1.7.5"
  }
}

dan@dan-vrajmas:~/ANGULAR/m.zbor.md$ npm install http 
npm ERR! Linux 4.10.0-33-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "http"
npm ERR! node v7.10.1
npm ERR! npm  v4.2.0
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: http@2.0.0-rc.1
npm ERR! notarget Valid install targets:
npm ERR! notarget 0.0.0
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/dan/.npm/_logs/2017-09-14T13_10_26_550Z-debug.log

> 0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'install', 'http' ]
2 info using npm@4.2.0
3 info using node@v7.10.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData http@2.0.0-rc.1
8 silly fetchNamedPackageData http
9 silly mapToRegistry name http
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'http',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'http',
12 silly mapToRegistry   name: 'http',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/http
14 verbose request uri https://registry.npmjs.org/http
15 verbose request no auth needed
16 info attempt registry request try #1 at 16:10:26
17 verbose request id b5d38811a690b90e
18 verbose etag W/"595c526d-3f9"
19 verbose lastModified Wed, 05 Jul 2017 02:43:57 GMT
20 http request GET https://registry.npmjs.org/http
21 http 304 https://registry.npmjs.org/http
22 verbose headers { date: 'Thu, 14 Sep 2017 13:10:26 GMT',
22 verbose headers   via: '1.1 varnish',
22 verbose headers   'cache-control': 'max-age=300',
22 verbose headers   etag: 'W/"595c526d-3f9"',
22 verbose headers   age: '0',
22 verbose headers   connection: 'keep-alive',
22 verbose headers   'x-served-by': 'cache-fra1243-FRA',
22 verbose headers   'x-cache': 'HIT',
22 verbose headers   'x-cache-hits': '1',
22 verbose headers   'x-timer': 'S1505394626.405727,VS0,VE25',
22 verbose headers   vary: 'Accept-Encoding, Accept' }
23 silly get cb [ 304,
23 silly get   { date: 'Thu, 14 Sep 2017 13:10:26 GMT',
23 silly get     via: '1.1 varnish',
23 silly get     'cache-control': 'max-age=300',
23 silly get     etag: 'W/"595c526d-3f9"',
23 silly get     age: '0',
23 silly get     connection: 'keep-alive',
23 silly get     'x-served-by': 'cache-fra1243-FRA',
23 silly get     'x-cache': 'HIT',
23 silly get     'x-cache-hits': '1',
23 silly get     'x-timer': 'S1505394626.405727,VS0,VE25',
23 silly get     vary: 'Accept-Encoding, Accept' } ]
24 verbose etag https://registry.npmjs.org/http from cache
25 verbose get saving http to /home/dan/.npm/registry.npmjs.org/http/.cache.json
26 verbose correctMkdir /home/dan/.npm correctMkdir not in flight; initializing
27 silly pickManifestFromRegistryMetadata spec 2.0.0-rc.1 tag latest versions [ '0.0.0' ]
28 silly fetchNamedPackageData No valid target from cache, forcing network
29 verbose request uri https://registry.npmjs.org/http
30 verbose request no auth needed
31 info attempt registry request try #1 at 16:10:26
32 http request GET https://registry.npmjs.org/http
33 http 200 https://registry.npmjs.org/http
34 verbose headers { server: 'nginx/1.10.1',
34 verbose headers   'content-type': 'application/json',
34 verbose headers   'last-modified': 'Wed, 05 Jul 2017 02:43:57 GMT',
34 verbose headers   etag: 'W/"595c526d-3f9"',
34 verbose headers   'content-encoding': 'gzip',
34 verbose headers   'cache-control': 'max-age=300',
34 verbose headers   'content-length': '547',
34 verbose headers   'accept-ranges': 'bytes',
34 verbose headers   date: 'Thu, 14 Sep 2017 13:10:26 GMT',
34 verbose headers   via: '1.1 varnish',
34 verbose headers   age: '0',
34 verbose headers   connection: 'keep-alive',
34 verbose headers   'x-served-by': 'cache-fra1243-FRA',
34 verbose headers   'x-cache': 'HIT',
34 verbose headers   'x-cache-hits': '2',
34 verbose headers   'x-timer': 'S1505394627.505620,VS0,VE0',
34 verbose headers   vary: 'Accept-Encoding, Accept' }
35 silly get cb [ 200,
35 silly get   { server: 'nginx/1.10.1',
35 silly get     'content-type': 'application/json',
35 silly get     'last-modified': 'Wed, 05 Jul 2017 02:43:57 GMT',
35 silly get     etag: 'W/"595c526d-3f9"',
35 silly get     'content-encoding': 'gzip',
35 silly get     'cache-control': 'max-age=300',
35 silly get     'content-length': '547',
35 silly get     'accept-ranges': 'bytes',
35 silly get     date: 'Thu, 14 Sep 2017 13:10:26 GMT',
35 silly get     via: '1.1 varnish',
35 silly get     age: '0',
35 silly get     connection: 'keep-alive',
35 silly get     'x-served-by': 'cache-fra1243-FRA',
35 silly get     'x-cache': 'HIT',
35 silly get     'x-cache-hits': '2',
35 silly get     'x-timer': 'S1505394627.505620,VS0,VE0',
35 silly get     vary: 'Accept-Encoding, Accept' } ]
36 verbose get saving http to /home/dan/.npm/registry.npmjs.org/http/.cache.json
37 verbose correctMkdir /home/dan/.npm correctMkdir not in flight; initializing
38 silly pickManifestFromRegistryMetadata spec 2.0.0-rc.1 tag latest versions [ '0.0.0' ]
39 silly fetchPackageMetaData Error: No compatible version found: http@2.0.0-rc.1
39 silly fetchPackageMetaData Valid install targets:
39 silly fetchPackageMetaData 0.0.0
39 silly fetchPackageMetaData
39 silly fetchPackageMetaData     at pickVersionFromRegistryDocument (/usr/lib/node_modules/npm/lib/fetch-package-metadata.js:158:16)
39 silly fetchPackageMetaData     at /usr/lib/node_modules/npm/node_modules/iferr/index.js:13:50
39 silly fetchPackageMetaData     at /usr/lib/node_modules/npm/lib/utils/pulse-till-done.js:20:8
39 silly fetchPackageMetaData     at saved (/usr/lib/node_modules/npm/lib/cache/caching-client.js:174:7)
39 silly fetchPackageMetaData     at /usr/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:261:18
39 silly fetchPackageMetaData     at FSReqWrap.oncomplete (fs.js:114:15)
39 silly fetchPackageMetaData  error for http@2.0.0-rc.1 { Error: No compatible version found: http@2.0.0-rc.1
39 silly fetchPackageMetaData Valid install targets:
39 silly fetchPackageMetaData 0.0.0
39 silly fetchPackageMetaData
39 silly fetchPackageMetaData     at pickVersionFromRegistryDocument (/usr/lib/node_modules/npm/lib/fetch-package-metadata.js:158:16)
39 silly fetchPackageMetaData     at /usr/lib/node_modules/npm/node_modules/iferr/index.js:13:50
39 silly fetchPackageMetaData     at /usr/lib/node_modules/npm/lib/utils/pulse-till-done.js:20:8
39 silly fetchPackageMetaData     at saved (/usr/lib/node_modules/npm/lib/cache/caching-client.js:174:7)
39 silly fetchPackageMetaData     at /usr/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:261:18
39 silly fetchPackageMetaData     at FSReqWrap.oncomplete (fs.js:114:15) code: 'ETARGET' }
40 silly rollbackFailedOptional Starting
41 silly rollbackFailedOptional Finishing
42 silly runTopLevelLifecycles Finishing
43 silly install printInstalled
44 verbose stack Error: No compatible version found: http@2.0.0-rc.1
44 verbose stack Valid install targets:
44 verbose stack 0.0.0
44 verbose stack
44 verbose stack     at pickVersionFromRegistryDocument (/usr/lib/node_modules/npm/lib/fetch-package-metadata.js:158:16)
44 verbose stack     at /usr/lib/node_modules/npm/node_modules/iferr/index.js:13:50
44 verbose stack     at /usr/lib/node_modules/npm/lib/utils/pulse-till-done.js:20:8
44 verbose stack     at saved (/usr/lib/node_modules/npm/lib/cache/caching-client.js:174:7)
44 verbose stack     at /usr/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:261:18
44 verbose stack     at FSReqWrap.oncomplete (fs.js:114:15)
45 verbose cwd /home/dan/ANGULAR/m.zbor.md
46 error Linux 4.10.0-33-generic
47 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "http"
48 error node v7.10.1
49 error npm  v4.2.0
50 error code ETARGET
51 error notarget No compatible version found: http@2.0.0-rc.1
51 error notarget Valid install targets:
51 error notarget 0.0.0
52 error notarget This is most likely not a problem with npm itself.
52 error notarget In most cases you or one of your dependencies are requesting
52 error notarget a package version that doesn't exist.
53 verbose exit [ 1, true ]

**Comment by kenany** [comment]
You should probably just remove that `"http": "2.0.0-rc.1",` line, since `http` is a builtin module of Node.js.
