### ISSUE TITLE
"npm install" doesn't work

### ISSUE THREAD

**Issue by NicolasMainardi** [npm/npm#18536]
OS: Windows7 Professional 64-bit

C:\Users\nmainardi>npm install angular@1.6.5
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "angular@1.6.5"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ENOTCONN
npm ERR! errno ENOTCONN
npm ERR! syscall connect

npm ERR! connect ENOTCONN 151.101.112.162:443
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\nmainardi\npm-debug.log

1 verbose cli   'install',
1 verbose cli   'angular@1.6.5' ]
2 info using npm@3.10.10
3 info using node@v6.11.3
4 verbose config Skipping project config: C:\Users\nmainardi/.npmrc. (matches userconfig)
5 silly loadCurrentTree Starting
6 silly install loadCurrentTree
7 silly install readLocalPackageData
8 silly fetchPackageMetaData angular@1.6.5
9 silly fetchNamedPackageData angular
10 silly mapToRegistry name angular
11 silly mapToRegistry using default registry
12 silly mapToRegistry registry https://registry.npmjs.org/
13 silly mapToRegistry data Result {
13 silly mapToRegistry   raw: 'angular',
13 silly mapToRegistry   scope: null,
13 silly mapToRegistry   escapedName: 'angular',
13 silly mapToRegistry   name: 'angular',
13 silly mapToRegistry   rawSpec: '',
13 silly mapToRegistry   spec: 'latest',
13 silly mapToRegistry   type: 'tag' }
14 silly mapToRegistry uri https://registry.npmjs.org/angular
15 verbose request uri https://registry.npmjs.org/angular
16 verbose request no auth needed
17 info attempt registry request try #1 at 14:57:11
18 verbose request id 3bb146eb2c891979
19 http request GET https://registry.npmjs.org/angular
20 info retry will retry, error on last attempt: Error: connect ENOTCONN 151.101.112.162:443
21 info attempt registry request try #2 at 14:57:22
22 http request GET https://registry.npmjs.org/angular
23 info retry will retry, error on last attempt: Error: connect ENOTCONN 151.101.112.162:443
24 info attempt registry request try #3 at 14:58:23
25 http request GET https://registry.npmjs.org/angular
26 silly fetchPackageMetaData Error: connect ENOTCONN 151.101.112.162:443
26 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1020:11)
26 silly fetchPackageMetaData     at exports._exceptionWithHostPort (util.js:1043:20)
26 silly fetchPackageMetaData     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
26 silly fetchPackageMetaData  error for angular@1.6.5 { Error: connect ENOTCONN 151.101.112.162:443
26 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1020:11)
26 silly fetchPackageMetaData     at exports._exceptionWithHostPort (util.js:1043:20)
26 silly fetchPackageMetaData     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
26 silly fetchPackageMetaData   code: 'ENOTCONN',
26 silly fetchPackageMetaData   errno: 'ENOTCONN',
26 silly fetchPackageMetaData   syscall: 'connect',
26 silly fetchPackageMetaData   address: '151.101.112.162',
26 silly fetchPackageMetaData   port: 443 }
27 silly rollbackFailedOptional Starting
28 silly rollbackFailedOptional Finishing
29 silly runTopLevelLifecycles Finishing
30 silly install printInstalled
31 verbose stack Error: connect ENOTCONN 151.101.112.162:443
31 verbose stack     at Object.exports._errnoException (util.js:1020:11)
31 verbose stack     at exports._exceptionWithHostPort (util.js:1043:20)
31 verbose stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
32 verbose cwd C:\Users\nmainardi
33 error Windows_NT 6.1.7601
34 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "angular@1.6.5"
35 error node v6.11.3
36 error npm  v3.10.10
37 error code ENOTCONN
38 error errno ENOTCONN
39 error syscall connect
40 error connect ENOTCONN 151.101.112.162:443
41 error If you need help, you may report this error at:
41 error     <https://github.com/npm/npm/issues>
42 verbose exit [ 1, true ]

**Comment by robv8r** [comment]
It looks like npm couldn't connect to the nodejs registry when you ran that command. Try running the command again (obviously while you're connected to the internet). 

I'm not suggesting that you weren't connected to the internet when you experienced the error. After all, you were able to post the error above.

**Comment by NicolasMainardi** [comment]
I'm sure that I'm connected to the internet. I've also tried with:
npm config set proxy http://my.proxy:8080
npm config set https-proxy http://my.proxy:8080
And it didn't work so I tried with this:
npm config set proxy http://<username>:<password>@my.proxy:8080
npm config set https-proxy http://<username>:<password>@my.proxy:8080

And also it didn't work.
C:\Users\nmainardi>npm install npm@latest -g
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "npm@latest" "-g"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ECONNRESET

npm ERR! network tunneling socket could not be established, cause=getaddrinfo EN
OTFOUND metsys metsys:80
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settin
gs.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\nmainardi\npm-debug.log

And **logs**:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'npm@latest',
1 verbose cli   '-g' ]
2 info using npm@3.10.10
3 info using node@v6.11.3
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData npm@latest
8 silly fetchNamedPackageData npm
9 silly mapToRegistry name npm
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'npm',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'npm',
12 silly mapToRegistry   name: 'npm',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/npm
14 verbose request uri https://registry.npmjs.org/npm
15 verbose request no auth needed
16 info attempt registry request try #1 at 11:10:05
17 verbose request id 70cdeb90cee58930
18 http request GET https://registry.npmjs.org/npm
19 info retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND metsys metsys:80
20 info attempt registry request try #2 at 11:10:15
21 http request GET https://registry.npmjs.org/npm
22 info retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND metsys metsys:80
23 info attempt registry request try #3 at 11:11:15
24 http request GET https://registry.npmjs.org/npm
25 silly fetchPackageMetaData Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND metsys metsys:80
25 silly fetchPackageMetaData     at ClientRequest.onError (C:\Program Files\nodejs\node_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:176:17)
25 silly fetchPackageMetaData     at ClientRequest.g (events.js:292:16)
25 silly fetchPackageMetaData     at emitOne (events.js:96:13)
25 silly fetchPackageMetaData     at ClientRequest.emit (events.js:188:7)
25 silly fetchPackageMetaData     at Socket.socketErrorListener (_http_client.js:310:9)
25 silly fetchPackageMetaData     at emitOne (events.js:96:13)
25 silly fetchPackageMetaData     at Socket.emit (events.js:188:7)
25 silly fetchPackageMetaData     at connectErrorNT (net.js:1021:8)
25 silly fetchPackageMetaData     at _combinedTickCallback (internal/process/next_tick.js:80:11)
25 silly fetchPackageMetaData     at process._tickCallback (internal/process/next_tick.js:104:9)
25 silly fetchPackageMetaData  error for npm@latest { Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND metsys metsys:80
25 silly fetchPackageMetaData     at ClientRequest.onError (C:\Program Files\nodejs\node_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:176:17)
25 silly fetchPackageMetaData     at ClientRequest.g (events.js:292:16)
25 silly fetchPackageMetaData     at emitOne (events.js:96:13)
25 silly fetchPackageMetaData     at ClientRequest.emit (events.js:188:7)
25 silly fetchPackageMetaData     at Socket.socketErrorListener (_http_client.js:310:9)
25 silly fetchPackageMetaData     at emitOne (events.js:96:13)
25 silly fetchPackageMetaData     at Socket.emit (events.js:188:7)
25 silly fetchPackageMetaData     at connectErrorNT (net.js:1021:8)
25 silly fetchPackageMetaData     at _combinedTickCallback (internal/process/next_tick.js:80:11)
25 silly fetchPackageMetaData     at process._tickCallback (internal/process/next_tick.js:104:9) code: 'ECONNRESET' }
26 silly rollbackFailedOptional Starting
27 silly rollbackFailedOptional Finishing
28 silly runTopLevelLifecycles Finishing
29 silly install printInstalled
30 verbose stack Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND metsys metsys:80
30 verbose stack     at ClientRequest.onError (C:\Program Files\nodejs\node_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:176:17)
30 verbose stack     at ClientRequest.g (events.js:292:16)
30 verbose stack     at emitOne (events.js:96:13)
30 verbose stack     at ClientRequest.emit (events.js:188:7)
30 verbose stack     at Socket.socketErrorListener (_http_client.js:310:9)
30 verbose stack     at emitOne (events.js:96:13)
30 verbose stack     at Socket.emit (events.js:188:7)
30 verbose stack     at connectErrorNT (net.js:1021:8)
30 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:80:11)
30 verbose stack     at process._tickCallback (internal/process/next_tick.js:104:9)
31 verbose cwd C:\Users\nmainardi
32 error Windows_NT 6.1.7601
33 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "npm@latest" "-g"
34 error node v6.11.3
35 error npm  v3.10.10
36 error code ECONNRESET
37 error network tunneling socket could not be established, cause=getaddrinfo ENOTFOUND metsys metsys:80
38 error network This is most likely not a problem with npm itself
38 error network and is related to network connectivity.
38 error network In most cases you are behind a proxy or have bad network settings.
38 error network
38 error network If you are behind a proxy, please make sure that the
38 error network 'proxy' config is set properly.  See: 'npm help config'
39 verbose exit [ 1, true ]
