### ISSUE TITLE
ALL npm command not work

### ISSUE THREAD

**Issue by cyyang-wfish** [npm/npm#18537]
#### I'm opening this issue because:

  - [v] npm is crashing.

#### What's going wrong?

ALL npm command not work

#### How can the CLI team reproduce the problem?

root@cyyang-vm:~/restful_api/API# npm init

/usr/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:6
let url
^^^
SyntaxError: Unexpected strict mode reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/access.js:5:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
root@cyyang-vm:~/restful_api/API# npm version

/usr/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:6
let url
^^^
SyntaxError: Unexpected strict mode reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/access.js:5:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
root@cyyang-vm:~/restful_api/API# 

### supporting information:

npm is instralled by "apt-get install nodejs"

**Comment by kenany** [comment]
@cyyang-wfish `node --version`?

**Comment by Viswanath95** [comment]
I'm using ubuntu 14.04.1 LTS  my nodejs version is v0.10.37 whenever i type npm in terminal I got this following error:

/usr/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:6
let url
^^^
SyntaxError: Unexpected strict mode reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/access.js:5:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
Please help me,Thanks in Advance.

**Comment by kenany** [comment]
Closing due to no response from @cyyang-wfish.

@Viswanath95 As per the README file for `npm`, you need at least Node.js v4 to run `npm`.

**Comment by ghost** [comment]
Same here.

node -version
v0.8.21

usr/local/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:6
let url
^^^
SyntaxError: Unexpected strict mode reserved word
    at Module._compile (module.js:437:25)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/access.js:5:11)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)

**Comment by Viswanath95** [comment]
If you are using ubuntu then check this youtube link it clears my error:
https://www.youtube.com/watch?v=nzliFQ-36kg
