### ISSUE TITLE
don't no

### ISSUE THREAD

**Issue by jiaowoxiaoqi** [npm/npm#18564]
Unhandled rejection RangeError: Maximum call stack size exceededill install loadIdealTree
    at RegExp.exec (native)
    at RegExp.test (native)
    at C:\Users\dev009\AppData\Roaming\npm\node_modules\npm\node_modules\aproba\index.js:38:16
    at Array.forEach (native)
    at module.exports (C:\Users\dev009\AppData\Roaming\npm\node_modules\npm\node_modules\aproba\index.js:33:11)
    at flatNameFromTree (C:\Users\dev009\AppData\Roaming\npm\node_modules\npm\lib\install\flatten-tree.js:37:3)
    at flatNameFromTree (C:\Users\dev009\AppData\Roaming\npm\node_modules\npm\lib\install\flatten-tree.js:39:14)
    at flatNameFromTree (C:\Users\dev009\AppData\Roaming\npm\node_modules\npm\lib\install\flatten-tree.js:39:14)
    at flatNameFromTree (C:\Users\dev009\AppData\Roaming\npm\node_modules\npm\lib\install\flatten-tree.js:39:14)
    at flatNameFromTree (C:\Users\dev009\AppData\Roaming\npm\node_modules\npm\lib\install\flatten-tree.js:39:14)
    at flatNameFromTree (C:\Users\dev009\AppData\Roaming\npm\node_modules\npm\lib\install\flatten-tree.js:39:14)
    at flatNameFromTree (C:\Users\dev009\AppData\Roaming\npm\node_modules\npm\lib\install\flatten-tree.js:39:14)
    at flatNameFromTree (C:\Users\dev009\AppData\Roaming\npm\node_modules\npm\lib\install\flatten-tree.js:39:14)
    at flatNameFromTree (C:\Users\dev009\AppData\Roaming\npm\node_modules\npm\lib\install\flatten-tree.js:39:14)
    at flatNameFromTree (C:\Users\dev009\AppData\Roaming\npm\node_modules\npm\lib\install\flatten-tree.js:39:14)
    at flatNameFromTree (C:\Users\dev009\AppData\Roaming\npm\node_modules\npm\lib\install\flatten-tree.js:39:14)

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by RillingDev** [comment]
Hello,
What version of NPM are you using?
If I recall correctly this used to be an issue i the early versions of v5.x
