### ISSUE TITLE
npm 5.3.0 fails: "Cannot find module 'semver'

### ISSUE THREAD

**Issue by lfurzewaddock** [npm/npm#18570]
#### I'm opening this issue because:

  - [X] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

npm 5.3.0 fails: with "Cannot find module 'semver' error and stack trace.

Reported to NVM for Windows, but apparently not related to NVM: [https://github.com/coreybutler/nvm-windows/issues/302](https://github.com/coreybutler/nvm-windows/issues/302)

#### How can the CLI team reproduce the problem?

Install any node version >= 8.2.0 using NVM for Windows;

nvm install 8.4.0
nvm use 8.4.0
npm -v

### supporting information:

 - `npm -v` prints:

```
module.js:491
    throw err;
    ^

Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\leofu\AppData\Roaming\nvm\nvm\v8.4.0\node_modules\npm\lib\utils\unsupported.js:2:14)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
module.js:491
    throw err;
    ^

Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\leofu\AppData\Roaming\nvm\nvm\v8.4.0\node_modules\npm\lib\utils\unsupported.js:2:14)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
```

 - `node -v` prints:

```
v8.4.0
```

 - `npm config get registry` prints:
```
module.js:491
    throw err;
    ^

Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\leofu\AppData\Roaming\nvm\nvm\v8.4.0\node_modules\npm\lib\utils\unsupported.js:2:14)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
module.js:491
    throw err;
    ^

Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\leofu\AppData\Roaming\nvm\nvm\v8.4.0\node_modules\npm\lib\utils\unsupported.js:2:14)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
```
 - Windows, OS X/macOS, or Linux?:
```
MS Win 10 Pro (v1703)
```
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [X] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by akshaybabloo** [comment]
Does `npm install -g npm` helps?

**Comment by lfurzewaddock** [comment]
@akshaybabloo, the same error occurs after running the command  `npm install -g npm`

```
module.js:491
    throw err;
    ^

Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\leofu\AppData\Roaming\nvm\nvm\v8.4.0\node_modules\npm\lib\utils\unsupported.js:2:14)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
module.js:491
    throw err;
    ^

Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\leofu\AppData\Roaming\nvm\nvm\v8.4.0\node_modules\npm\lib\utils\unsupported.js:2:14)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
```

**Comment by tomhalley** [comment]
+1 having same issue

**Comment by juancarlosfarah** [comment]
+1 I'm having the same issue when running inside a Codeship instance.

**Comment by codepunkt** [comment]
same here. started with 8.2.x, still present with 8.5.0.

windows, installed with nvm for windows.

**Comment by Palleas** [comment]
Got the same issue, completely wiped node from my machine (macOS 10.11) and reinstalled it. It seems to be working fine now but I don’t know for how long.

**Comment by coreybutler** [comment]
@Palleas - this is a Windows-only project (for now).

I think there is a bigger permissions issue introduced with newer versions of npm. I'm investigating now. I'm curious if anyone in this thread experiences these issues with older versions of node.

**Comment by lfurzewaddock** [comment]
@coreybutler the latest version of node I've successfully installed using nvm for windows is 8.1.4 

This issue is not present in my experience in versions of node before 8.2.0

**Comment by mzazon** [comment]
We had this same issue, rolling back to 8.2.0 rather than latest fixed our Docker builds, thx @lfurzewaddock !

**Comment by holm** [comment]
We have been having this issue for months now. It's been reported so many times here, but keeps being closed by the bot. That is really frustrating.

**Comment by honsa** [comment]
for me it helped to remove the local cache and node folders
