### ISSUE TITLE
Error while installing MFP CLI 8.0

### ISSUE THREAD

**Issue by PH16** [npm/npm#18592]
#### I'm opening this issue because:

D:\MobileFirst\MFP8.0 setup>npm install -g --no-optional mfpdev-cli.tgz@8.0
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "--no-optional" "mfpdev-cli.tgz@8.0"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code E500

npm ERR! Registry returned 500 for GET on https://registry.npmjs.org/mfpdev-cli.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\MobileFirst\MFP8.0 setup\npm-debug.log
### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by PH16** [comment]
debug file:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   '--no-optional',
1 verbose cli   'mfpdev-cli.tgz@8.0' ]
2 info using npm@3.10.10
3 info using node@v6.11.2
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData mfpdev-cli.tgz@8.0
8 silly fetchNamedPackageData mfpdev-cli.tgz
9 silly mapToRegistry name mfpdev-cli.tgz
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'mfpdev-cli.tgz',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'mfpdev-cli.tgz',
12 silly mapToRegistry   name: 'mfpdev-cli.tgz',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/mfpdev-cli.tgz
14 verbose request uri https://registry.npmjs.org/mfpdev-cli.tgz
15 verbose request no auth needed
16 info attempt registry request try #1 at 2:01:32 PM
17 verbose request id 08fa992a52e91779
18 http request GET https://registry.npmjs.org/mfpdev-cli.tgz
19 http 500 https://registry.npmjs.org/mfpdev-cli.tgz
20 verbose headers { 'content-type': 'application/json',
20 verbose headers   'cache-control': 'max-age=0',
20 verbose headers   'content-length': '69',
20 verbose headers   'accept-ranges': 'bytes',
20 verbose headers   date: 'Thu, 21 Sep 2017 08:31:43 GMT',
20 verbose headers   via: '1.1 varnish',
20 verbose headers   connection: 'keep-alive',
20 verbose headers   'x-served-by': 'cache-hhn1549-HHN',
20 verbose headers   'x-cache': 'MISS',
20 verbose headers   'x-cache-hits': '0',
20 verbose headers   'x-timer': 'S1505982703.572396,VS0,VE977' }
21 info retry will retry, error on last attempt: Error: Registry returned 500 for GET on https://registry.npmjs.org/mfpdev-cli.tgz
22 info attempt registry request try #2 at 2:01:53 PM
23 http request GET https://registry.npmjs.org/mfpdev-cli.tgz
24 http 500 https://registry.npmjs.org/mfpdev-cli.tgz
25 verbose headers { 'content-type': 'application/json',
25 verbose headers   'cache-control': 'max-age=0',
25 verbose headers   'content-length': '69',
25 verbose headers   'accept-ranges': 'bytes',
25 verbose headers   date: 'Thu, 21 Sep 2017 08:31:58 GMT',
25 verbose headers   via: '1.1 varnish',
25 verbose headers   connection: 'keep-alive',
25 verbose headers   'x-served-by': 'cache-hhn1549-HHN',
25 verbose headers   'x-cache': 'MISS',
25 verbose headers   'x-cache-hits': '0',
25 verbose headers   'x-timer': 'S1505982714.412791,VS0,VE4368' }
26 info retry will retry, error on last attempt: Error: Registry returned 500 for GET on https://registry.npmjs.org/mfpdev-cli.tgz
27 info attempt registry request try #3 at 2:02:59 PM
28 http request GET https://registry.npmjs.org/mfpdev-cli.tgz
29 http 500 https://registry.npmjs.org/mfpdev-cli.tgz
30 verbose headers { 'content-type': 'application/json',
30 verbose headers   'cache-control': 'max-age=0',
30 verbose headers   'content-length': '69',
30 verbose headers   'accept-ranges': 'bytes',
30 verbose headers   date: 'Thu, 21 Sep 2017 08:33:02 GMT',
30 verbose headers   via: '1.1 varnish',
30 verbose headers   connection: 'keep-alive',
30 verbose headers   'x-served-by': 'cache-hhn1549-HHN',
30 verbose headers   'x-cache': 'MISS',
30 verbose headers   'x-cache-hits': '0',
30 verbose headers   'x-timer': 'S1505982780.211996,VS0,VE1862' }
31 silly get cb [ 500,
31 silly get   { 'content-type': 'application/json',
31 silly get     'cache-control': 'max-age=0',
31 silly get     'content-length': '69',
31 silly get     'accept-ranges': 'bytes',
31 silly get     date: 'Thu, 21 Sep 2017 08:33:02 GMT',
31 silly get     via: '1.1 varnish',
31 silly get     connection: 'keep-alive',
31 silly get     'x-served-by': 'cache-hhn1549-HHN',
31 silly get     'x-cache': 'MISS',
31 silly get     'x-cache-hits': '0',
31 silly get     'x-timer': 'S1505982780.211996,VS0,VE1862' } ]
32 silly fetchPackageMetaData Error: Registry returned 500 for GET on https://registry.npmjs.org/mfpdev-cli.tgz
32 silly fetchPackageMetaData     at makeError (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:302:12)
32 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:280:14)
32 silly fetchPackageMetaData     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:210:14)
32 silly fetchPackageMetaData     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:187:22)
32 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
32 silly fetchPackageMetaData     at Request.emit (events.js:191:7)
32 silly fetchPackageMetaData     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1048:10)
32 silly fetchPackageMetaData     at emitOne (events.js:96:13)
32 silly fetchPackageMetaData     at Request.emit (events.js:188:7)
32 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:969:12)
32 silly fetchPackageMetaData  error for mfpdev-cli.tgz@8.0 { Error: Registry returned 500 for GET on https://registry.npmjs.org/mfpdev-cli.tgz
32 silly fetchPackageMetaData     at makeError (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:302:12)
32 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:280:14)
32 silly fetchPackageMetaData     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:210:14)
32 silly fetchPackageMetaData     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:187:22)
32 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
32 silly fetchPackageMetaData     at Request.emit (events.js:191:7)
32 silly fetchPackageMetaData     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1048:10)
32 silly fetchPackageMetaData     at emitOne (events.js:96:13)
32 silly fetchPackageMetaData     at Request.emit (events.js:188:7)
32 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:969:12) pkgid: 'mfpdev-cli.tgz', statusCode: 500, code: 'E500' }
33 silly rollbackFailedOptional Starting
34 silly rollbackFailedOptional Finishing
35 silly runTopLevelLifecycles Finishing
36 silly install printInstalled
37 verbose stack Error: Registry returned 500 for GET on https://registry.npmjs.org/mfpdev-cli.tgz
37 verbose stack     at makeError (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:302:12)
37 verbose stack     at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:280:14)
37 verbose stack     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:210:14)
37 verbose stack     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:187:22)
37 verbose stack     at emitTwo (events.js:106:13)
37 verbose stack     at Request.emit (events.js:191:7)
37 verbose stack     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1048:10)
37 verbose stack     at emitOne (events.js:96:13)
37 verbose stack     at Request.emit (events.js:188:7)
37 verbose stack     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:969:12)
38 verbose statusCode 500
39 verbose pkgid mfpdev-cli.tgz
40 verbose cwd D:\MobileFirst\MFP8.0 setup
41 error Windows_NT 10.0.14393
42 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "--no-optional" "mfpdev-cli.tgz@8.0"
43 error node v6.11.2
44 error npm  v3.10.10
45 error code E500
46 error Registry returned 500 for GET on https://registry.npmjs.org/mfpdev-cli.tgz
47 error If you need help, you may report this error at:
47 error     <https://github.com/npm/npm/issues>
48 verbose exit [ 1, true ]
