### ISSUE TITLE
npm install throws error 'verbose stack SyntaxError: Unexpected token } in JSON at position 140851'

### ISSUE THREAD

**Issue by jani937** [npm/npm#18657]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'install' ]
2 info using npm@5.4.2
3 info using node@v8.2.1
4 verbose npm-session fb1f7ec8985b79c6
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall manage-frontend@0.1.0
7 info lifecycle manage-frontend@0.1.0~preinstall: manage-frontend@0.1.0
8 silly install loadCurrentTree
9 silly install readLocalPackageData
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 silly install loadShrinkwrap
**13 verbose stack SyntaxError: Unexpected token } in JSON at position 140851
13 verbose stack     at JSON.parse (<anonymous>)**
13 verbose stack     at module.exports (/usr/local/lib/node_modules/npm/lib/utils/parse-json.js:3:15)
13 verbose stack     at BB.join (/usr/local/lib/node_modules/npm/lib/install/read-shrinkwrap.js:31:20)
13 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
13 verbose stack     at Holder$3._callFunction (eval at generateHolderClass (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/join.js:92:16), <anonymous>:14:44)
13 verbose stack     at Holder$3.checkFulfillment (eval at generateHolderClass (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/join.js:92:16), <anonymous>:29:30)
13 verbose stack     at Promise.eval (eval at thenCallback (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/join.js:14:16), <anonymous>:6:20)
13 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:566:21)
13 verbose stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
13 verbose stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
13 verbose stack     at Promise._fulfill (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:638:18)
13 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:582:21)
13 verbose stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
13 verbose stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
13 verbose stack     at Promise._fulfill (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:638:18)
13 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/nodeback.js:42:21
14 verbose cwd /home/janaiah.theerpari/IdeaProjects/manage-frontend
15 verbose Linux 3.10.0-327.el7.x86_64
16 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
17 verbose node v8.2.1
18 verbose npm  v5.4.2
19 error Unexpected token } in JSON at position 140851
20 verbose exit [ 1, true ]

Note: my node version is v8.2.1
my npm version is 5.4.2

Please respond if you have any solution to fix this.

**Comment by BenjiFischman** [comment]
I am running into the same issue. Here is my log

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'install' ]
2 info using npm@5.4.1
3 info using node@v8.4.0
4 verbose npm-session db641e2aa5b8b627
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall module-1-group-assignment-drop-table-teams-1@0.0.0
7 info lifecycle module-1-group-assignment-drop-table-teams-1@0.0.0~preinstall: module-1-group-assignment-drop-table-teams-1@0.0.0
8 silly install loadCurrentTree
9 silly install readLocalPackageData
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 silly install loadShrinkwrap
13 verbose stack SyntaxError: Unexpected token < in JSON at position 2344
13 verbose stack     at JSON.parse (<anonymous>)
13 verbose stack     at module.exports (/usr/lib/node_modules/npm/lib/utils/parse-json.js:3:15)
13 verbose stack     at BB.join (/usr/lib/node_modules/npm/lib/install/read-shrinkwrap.js:31:20)
13 verbose stack     at tryCatcher (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
13 verbose stack     at Holder$3._callFunction (eval at generateHolderClass (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/join.js:92:16), <anonymous>:14:44)
13 verbose stack     at Holder$3.checkFulfillment (eval at generateHolderClass (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/join.js:92:16), <anonymous>:29:30)
13 verbose stack     at Promise.eval (eval at thenCallback (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/join.js:14:16), <anonymous>:6:20)
13 verbose stack     at Promise._settlePromise (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:566:21)
13 verbose stack     at Promise._settlePromise0 (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
13 verbose stack     at Promise._settlePromises (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
13 verbose stack     at Promise._fulfill (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:638:18)
13 verbose stack     at Promise._settlePromise (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:582:21)
13 verbose stack     at Promise._settlePromise0 (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
13 verbose stack     at Promise._settlePromises (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
13 verbose stack     at Promise._fulfill (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:638:18)
13 verbose stack     at /usr/lib/node_modules/npm/node_modules/bluebird/js/release/nodeback.js:42:21
14 verbose cwd /home/benji/School/csci5117/module-1-group-assignment-drop-table-teams-1
15 verbose Linux 4.4.6-3-surface
16 verbose argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
17 verbose node v8.4.0
18 verbose npm  v5.4.1
19 error Unexpected token < in JSON at position 2344
20 verbose exit [ 1, true ]
```

**Comment by lazar-vuckovic** [comment]
@BenjiFischman I had the same exact issue and it turned out that there was a badly resolved merge conflict that left the <<<<<<< entries in the package-lock.json file.
Hope that helps.

**Comment by Antony74** [comment]
Same here: merge conflict in package-lock.json file causing a parse error.
Npm isn't doing anything wrong, but I'd suggest logging the pathname of the invalid JSON file would make it much easier for us users to understand where we've gone wrong.
(I'm also going to make our engine checking slightly stricter so that package-lock.json changes less often)

**Comment by aous77** [comment]
its usually the file after loadShrinkwrap in your package-lock

**Comment by aqibos** [comment]
Happened to me as well. Although, in my case, the `package-lock.json` file was simply missing a comma. Not sure how that happened. ESLint picked it up.

**Comment by marcelovue** [comment]
same here, I just removed package-lock.json and yarn.lock and everything works fine. Thank yall
