### ISSUE TITLE
"Failed parsing JSON config key editor" when quotation marks in environment variable

### ISSUE THREAD

**Issue by jdoose** [npm/npm#18663]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

npm throws an error "Failed parsing JSON config key editor" on "npm start <script>" when the called script itself calls npm again and quotation marks are used in environment variable.
This happens with react apps for instance.

```
D:\Work\Repositories\mytest>npm start

> mytest@1.0.0 start D:\Work\Repositories\mytest
> node index.js

Error: Failed parsing JSON config key editor: "C:\Program Files\Sublime Text 2\sublime_text.exe"
    at parseField (C:\Users\doose\AppData\Roaming\npm\node_modules\npm\lib\config\core.js:390:13)
    at C:\Users\doose\AppData\Roaming\npm\node_modules\npm\lib\config\core.js:335:17
    at Array.forEach (native)
    at Conf.add (C:\Users\doose\AppData\Roaming\npm\node_modules\npm\lib\config\core.js:334:23)
    at ConfigChain.addEnv (C:\Users\doose\AppData\Roaming\npm\node_modules\npm\node_modules\config-chain\index.js:207:15)
    at Conf.addEnv (C:\Users\doose\AppData\Roaming\npm\node_modules\npm\lib\config\core.js:370:30)
    at load_ (C:\Users\doose\AppData\Roaming\npm\node_modules\npm\lib\config\core.js:107:8)
    at Conf.<anonymous> (C:\Users\doose\AppData\Roaming\npm\node_modules\npm\lib\config\core.js:96:5)
    at emitOne (events.js:96:13)
    at Conf.emit (events.js:191:7)
C:\Users\doose\AppData\Roaming\npm\node_modules\npm\lib\npm.js:51
      throw new Error('npm.load() required')
      ^

Error: npm.load() required
    at Object.get (C:\Users\doose\AppData\Roaming\npm\node_modules\npm\lib\npm.js:51:13)
    at process.errorHandler (C:\Users\doose\AppData\Roaming\npm\node_modules\npm\lib\utils\error-handler.js:205:18)
    at emitOne (events.js:96:13)
    at process.emit (events.js:191:7)
    at process._fatalException (bootstrap_node.js:300:26)

D:\Work\Repositories\mytest>
```

#### How can the CLI team reproduce the problem?

* create env variable `set EDITOR="C:\Program Files\Sublime Text 2\sublime_text.exe"`
* Use attached sample project:  [mytest.zip](https://github.com/npm/npm/files/1343763/mytest.zip)
* run `npm install` to get dependencies
* run `npm start` to reproduce error

### supporting information:

 - `npm -v` prints: 5.4.2
 - `node -v` prints: v7.9.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by jdoose** [comment]
See also #9899

**Comment by jdoose** [comment]
it can be fixed by replacing `Conf.prototype.addEnv` in npm/lib/config/core.js, I will provide a merge request

**Comment by jdoose** [comment]
Hm, it seems I was a little bit too fast with promising a pull request... I can't manage to get the tests running. Is there any help document to set up my environment to run the tests (I tried it in Windows and Ubuntu...)

Anyhow, this change to `Conf.prototype.addEnv` should do the trick:
```
Conf.prototype.addEnv = function (env) {
  env = env || process.env
  var conf = {}
  Object.keys(env)
    .filter(function (k) { return k.match(/^npm_config_/i) })
    .forEach(function (k) {
      var envSetting = env[k]

      if (!envSetting) return

      // leave first char untouched, even if
      // it is a '_' - convert all other to '-'
      var p = k.toLowerCase()
               .replace(/^npm_config_/, '')
               .replace(/(?!^)_/g, '-')

      // extract env setting if it starts with quotation marks AND ends with quotation marks and these are the only quotation marks
      var matchesCount = envSetting.split('"').length - 1
      if (envSetting.length > 2 && matchesCount == 2 && envSetting[0] === '"' && envSetting[envSetting.length - 1] === '"') {
        envSetting = envSetting.substr(1, envSetting.length - 2)
      }

      conf[p] = envSetting
    })
  return CC.prototype.addEnv.call(this, '', conf, 'env')
}
```
