### ISSUE TITLE
Error installing npm 5 using docker

### ISSUE THREAD

**Issue by ghost** [npm/npm#18667]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### How can the CLI team reproduce the problem?

```shell
FROM node:7.2.1

RUN curl -sL https://deb.nodesource.com/setup_7.x | bash - && \
  apt-get update && \
  apt-get install -y nodejs && \
  apt-get install -y build-essential

RUN npm install npm@5.4.2 -g
```
### supporting information:

 - `npm -v` prints: en error
```
module.js:472
    throw err;
    ^

Error: Cannot find module 'process-nextick-args'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_readable.js:26:23)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```
 - `node -v` prints: 7.2.1
 - `npm config get registry` prints:
```
module.js:472
    throw err;
    ^

Error: Cannot find module 'process-nextick-args'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_readable.js:26:23)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```
 - Windows, OS X/macOS, or Linux?: Debian using docker.
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [x] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by rajapanidepu** [comment]
Facing the same issue.

**Comment by djhojd** [comment]
I'm facing the same issue with the official [Node docker images](https://hub.docker.com/_/node/).

**Comment by brycedrennan** [comment]
Facing this same error with this dockerfile

```dockerfile

FROM ubuntu:16.04
RUN apt-get update && apt-get install -y curl software-properties-common
RUN apt-get install -y gnupg
RUN curl -sL https://deb.nodesource.com/setup_6.x | bash -
RUN apt-get install -y nodejs
RUN npm install -g npm
RUN npm install -g lodash
```

```
module.js:471
    throw err;
    ^

Error: Cannot find module 'process-nextick-args'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_readable.js:26:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**Comment by P-Seebauer** [comment]
I have the same issue,
Here is a minimal `Dockerfile` when using the [official node image](https://hub.docker.com/_/node/)

``` Dockerfile
FROM node:6
RUN npm up -g npm
RUN npm -v
```

**Comment by QzSG** [comment]
Same problem too on node 6.11.3 after the following commands

```bash
nvm install 6.11.3
nvm use 6.11.3
npm i -g npm
npm -v 
```

**Comment by fabienduval** [comment]
I had the same problem, and then found this Dockerfile : 

https://hub.docker.com/r/alexhayton/node-boron-npm-5/~/dockerfile/

It worked for me !

**Comment by ghost** [comment]
This should not be closed, this is still an issue.

**Comment by iarna** [comment]
@alejandronanez-huge Looks like it was misstriaged, sorry about that.

**Comment by stephengardner** [comment]
What's the word, here?

**Comment by GregBorrelly** [comment]
anyone still working on this?

**Comment by mapsam** [comment]
For those installing node manually, removing the default npm version that ships with node and installing npm directly from the git tag seems to work nicely. 

Example install script: 

```bash
curl https://nodejs.org/dist/v6.13.0/node-v6.13.0-linux-x64.tar.gz | tar zxC /usr/local --strip-components=1
rm -rf /usr/local/lib/node_modules/npm
mkdir /usr/local/lib/node_modules/npm
curl -sL https://github.com/npm/npm/archive/v5.3.0.tar.gz | tar xz -C /usr/local/lib/node_modules/npm --strip-components=1
```
