### ISSUE TITLE
javax.script.ScriptException: Error: Cannot find module ./rx in <eval> at line number 141 at column number 6

### ISSUE THREAD

**Issue by ghost** [npm/npm#18713]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I have installed the node js of version 4.2.6 and npm version 3.10.3 and vertx3-full of version 3.4.1 on another machine. It's working fine.But when I am using the same packages of same version on another machine, it throws ``` javax.script.ScriptException ``` . I am not sure what went wrong. Even after trying the updated versions of nodejs and npm it still throws the same error.
Here is the <b>error log</b>:
``` 
> grey-bshlv@ start /home/lokesh/vertx
> vertx run server.js

javax.script.ScriptException: Error: Cannot find module ./rx in <eval> at line number 141 at column number 6
	at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:470)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:454)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:406)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:402)
	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at io.vertx.lang.js.JSVerticleFactory$JSVerticle.start(JSVerticleFactory.java:109)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:434)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:445)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:748)
Caused by: <eval>:141:6 Error: Cannot find module ./rx
	at jdk.nashorn.internal.objects.NativeError.initException(NativeError.java:137)
	at jdk.nashorn.internal.objects.NativeError.<init>(NativeError.java:102)
	at jdk.nashorn.internal.objects.NativeError.<init>(NativeError.java:106)
	at jdk.nashorn.internal.objects.NativeError.<init>(NativeError.java:110)
	at jdk.nashorn.internal.objects.NativeError.constructor(NativeError.java:129)
	at jdk.nashorn.internal.scripts.Script$Recompilation$4$4376AAAA$\^eval\_.L:33#doRequire(null:141)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:645)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptFunction.invokeSync(ScriptFunction.java:1294)
	at jdk.nashorn.internal.scripts.Script$Recompilation$3$4049AAA$\^eval\_.L:33#Require(null:120)
	at jdk.nashorn.internal.scripts.Script$Recompilation$19$2109A$\^eval\_.L:33#Module#require(null:68)
	at jdk.nashorn.internal.scripts.Script$Recompilation$133$79A$\^eval\_#88\!17\^eval\_.L:1#L:1(rx.vertx.js:28)
	at jdk.nashorn.internal.scripts.Script$Recompilation$132$57AAAAA$\^eval\_#88\!17\^eval\_.L:1(rx.vertx.js:1)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:647)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.internal.scripts.Script$Recompilation$15$2235AAAAA$\^eval\_.L:33#_load(null:113)
	at jdk.nashorn.internal.scripts.Script$Recompilation$4$4376AAAA$\^eval\_.L:33#doRequire(null:154)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:645)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptFunction.invokeSync(ScriptFunction.java:1294)
	at jdk.nashorn.internal.scripts.Script$Recompilation$3$4049AAA$\^eval\_.L:33#Require(null:120)
	at jdk.nashorn.internal.scripts.Script$Recompilation$19$2109A$\^eval\_.L:33#Module#require(null:68)
	at jdk.nashorn.internal.scripts.Script$Recompilation$130$57AAAAA$\^eval\_#88\!17\^eval\_.L:1(/home/lokesh/vertx/server.js:1)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:647)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.internal.scripts.Script$Recompilation$15$2235AAAAA$\^eval\_.L:33#_load(null:113)
	at jdk.nashorn.internal.scripts.Script$Recompilation$4$4376AAAA$\^eval\_.L:33#doRequire(null:154)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:645)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptFunction.invokeSync(ScriptFunction.java:1294)
	at jdk.nashorn.internal.scripts.Script$Recompilation$127$4168AAZ$\^eval\_.L:33#RequireNoCache(null:124)
	at jdk.nashorn.internal.scripts.Script$126$\^eval\_.:program(<eval>:1)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:449)
	... 12 more
Failed in deploying verticle 
javax.script.ScriptException: Error: Cannot find module ./rx in <eval> at line number 141 at column number 6
	at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:470)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:454)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:406)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:402)
	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at io.vertx.lang.js.JSVerticleFactory$JSVerticle.start(JSVerticleFactory.java:109)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:434)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:445)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:748)
Caused by: <eval>:141:6 Error: Cannot find module ./rx
	at jdk.nashorn.internal.objects.NativeError.initException(NativeError.java:137)
	at jdk.nashorn.internal.objects.NativeError.<init>(NativeError.java:102)
	at jdk.nashorn.internal.objects.NativeError.<init>(NativeError.java:106)
	at jdk.nashorn.internal.objects.NativeError.<init>(NativeError.java:110)
	at jdk.nashorn.internal.objects.NativeError.constructor(NativeError.java:129)
	at jdk.nashorn.internal.scripts.Script$Recompilation$4$4376AAAA$\^eval\_.L:33#doRequire(null:141)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:645)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptFunction.invokeSync(ScriptFunction.java:1294)
	at jdk.nashorn.internal.scripts.Script$Recompilation$3$4049AAA$\^eval\_.L:33#Require(null:120)
	at jdk.nashorn.internal.scripts.Script$Recompilation$19$2109A$\^eval\_.L:33#Module#require(null:68)
	at jdk.nashorn.internal.scripts.Script$Recompilation$133$79A$\^eval\_#88\!17\^eval\_.L:1#L:1(rx.vertx.js:28)
	at jdk.nashorn.internal.scripts.Script$Recompilation$132$57AAAAA$\^eval\_#88\!17\^eval\_.L:1(rx.vertx.js:1)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:647)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.internal.scripts.Script$Recompilation$15$2235AAAAA$\^eval\_.L:33#_load(null:113)
	at jdk.nashorn.internal.scripts.Script$Recompilation$4$4376AAAA$\^eval\_.L:33#doRequire(null:154)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:645)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptFunction.invokeSync(ScriptFunction.java:1294)
	at jdk.nashorn.internal.scripts.Script$Recompilation$3$4049AAA$\^eval\_.L:33#Require(null:120)
	at jdk.nashorn.internal.scripts.Script$Recompilation$19$2109A$\^eval\_.L:33#Module#require(null:68)
	at jdk.nashorn.internal.scripts.Script$Recompilation$130$57AAAAA$\^eval\_#88\!17\^eval\_.L:1(/home/lokesh/vertx/server.js:1)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:647)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.internal.scripts.Script$Recompilation$15$2235AAAAA$\^eval\_.L:33#_load(null:113)
	at jdk.nashorn.internal.scripts.Script$Recompilation$4$4376AAAA$\^eval\_.L:33#doRequire(null:154)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:645)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptFunction.invokeSync(ScriptFunction.java:1294)
	at jdk.nashorn.internal.scripts.Script$Recompilation$127$4168AAZ$\^eval\_.L:33#RequireNoCache(null:124)
	at jdk.nashorn.internal.scripts.Script$126$\^eval\_.:program(<eval>:1)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:449)
	... 12 more
```
#### How can the CLI team reproduce the problem?
npm-debug.log file :
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@3.5.2
3 info using node@v4.7.2
4 verbose config Skipping project config: /home/lokesh/.npmrc. (matches userconfig)
5 verbose stack Error: ENOENT: no such file or directory, open '/home/lokesh/package.json'
5 verbose stack     at Error (native)
6 verbose cwd /home/lokesh
7 error Linux 4.10.0-19-generic
8 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
9 error node v4.7.2
10 error npm  v3.5.2
11 error path /home/lokesh/package.json
12 error code ENOENT
13 error errno -2
14 error syscall open
15 error enoent ENOENT: no such file or directory, open '/home/lokesh/package.json'
16 error enoent ENOENT: no such file or directory, open '/home/lokesh/package.json'
16 error enoent This is most likely not a problem with npm itself
16 error enoent and is related to npm not being able to find a file.
17 verbose exit [ -2, true ]
```

### supporting information:

 - `npm -v` prints: 3.5.2
 - `node -v` prints: 4.7.2
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux

**Comment by kenany** [comment]
Does `/home/lokesh/package.json` exist?

**Comment by ghost** [comment]
No it doesn't exist.

**Comment by kenany** [comment]
You have to run `npm start` from within a directory which contains a `package.json`, which in turn contains a `"start"` script. Otherwise, how is `npm` supposed to know what you want it to do?

**Comment by ghost** [comment]
I did that. On one machine it's working absolutely fine but on another one it's not.

**Comment by ghost** [comment]
Do i also need to run npm start in verticles folder ?

**Comment by kenany** [comment]
The above log indicates that you run `npm start` from within the `/home/lokesh` directory, and you said above that there is no `package.json` in that directory, hence the `ENOENT` error.

**Comment by developerworks** [comment]
Seems like you use vertx in your npm project, in this case, you should add the `rx` directory to classpath as following when start your js verticle, this is my shell start script:

```shell
#!/bin/bash

export CLASSPATH=./src/conf
export CLASSPATH=$CLASSPATH:./src/main/resources
# Add the rx directory to classpaths
export CLASSPATH=$CLASSPATH:./node_modules/rx/dist

RUN="./node_modules/.bin/vertx run"
JAVA_OPT="-Duser.language=en -Duser.country=US -Duser.variant=en_US"

${RUN} --java-opts=${JAVA_OPT} --launcher-class=io.vertx.core.Launcher --redeploy=./src/rx/*.js ./src/rx/readfile.js

```

**Comment by ghost** [comment]
Yea, thank you @developerworks . Adding rx directory to classpath works.
