### ISSUE TITLE
npm run watch Windows_NT 10.0.15063

### ISSUE THREAD

**Issue by juancastro18** [npm/npm#18725]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is doing something I don't understand.

When i try to npm run watch

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "watch"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10

npm ERR! missing script: watch
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\JeysonAnibal\Documents\hapyDesk\HapyDesk\hapy\npm-debug.log

**Comment by meldsza** [comment]
You probably did not include a watch script in the package.json
Please include your package.json

**Comment by poperechnyi1** [comment]
I have the same problem:
After npm run:
```
`npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "deployContract"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10

npm ERR! missing script: deployContract
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Compiled contract\WEB3 Deploy contract\deploy via Web3 node\npm-debug.log
`
```
npm debug log has:
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'deployContract' ]
2 info using npm@3.10.10
3 info using node@v6.11.3
4 verbose stack Error: missing script: deployContract
4 verbose stack     at run (C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:151:19)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:61:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:356:5
4 verbose stack     at checkBinReferences_ (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:320:45)
4 verbose stack     at final (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:354:3)
4 verbose stack     at then (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:124:5)
4 verbose stack     at ReadFileContext.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:295:20)
4 verbose stack     at ReadFileContext.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16)
4 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:367:13)
5 verbose cwd D:\Compiled contract\WEB3 Deploy contract\deploy via Web3 node
6 error Windows_NT 10.0.15063
7 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "deployContract"
8 error node v6.11.3
9 error npm  v3.10.10
10 error missing script: deployContract
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
```

**Comment by shashankkapile** [comment]
Restarting the terminal/CMD simply helped me!
