### ISSUE TITLE
Cannot shrinkwrap a webpart project generated with the yeoman generator 1.3.2

### ISSUE THREAD

**Issue by lucmoco** [npm/npm#18732]
#### I'm opening this issue because:

  - [X] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

When generating a react webpart with the yeoman generator 1.3.2 and npm 4, I cannot generate a `shrinkwrap.json` file. The command `npm shrinkwrap` fails with the following error:

```
npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! peer invalid: ajv@>=5.0.0, required by ajv-keywords@2.1.0

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lmc\AppData\Roaming\npm-cache\_logs\2017-10-06T13_09_29_960Z-debug.log
```

Here is the content of the file `C:\Users\lmc\AppData\Roaming\npm-cache\_logs\2017-10-06T13_09_29_960Z-debug.log`:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\lmc\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'shrinkwrap' ]
2 info using npm@4.6.1
3 info using node@v6.11.2
4 info lifecycle my-spfx-solution@0.0.1~preshrinkwrap: my-spfx-solution@0.0.1
5 silly lifecycle my-spfx-solution@0.0.1~preshrinkwrap: no script for preshrinkwrap, continuing
6 info lifecycle my-spfx-solution@0.0.1~shrinkwrap: my-spfx-solution@0.0.1
7 silly lifecycle my-spfx-solution@0.0.1~shrinkwrap: no script for shrinkwrap, continuing
8 verbose stack Error: Problems were encountered
8 verbose stack Please correct and try again.
8 verbose stack peer invalid: ajv@>=5.0.0, required by ajv-keywords@2.1.0
8 verbose stack     at shrinkwrap_ (C:\Users\lmc\AppData\Roaming\npm\node_modules\npm\lib\shrinkwrap.js:128:15)
8 verbose stack     at Array.<anonymous> (C:\Users\lmc\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
8 verbose stack     at LOOP (C:\Users\lmc\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
8 verbose stack     at C:\Users\lmc\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:18:7
8 verbose stack     at done (C:\Users\lmc\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:132:5)
8 verbose stack     at LOOP (C:\Users\lmc\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:7:26)
8 verbose stack     at C:\Users\lmc\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:18:7
8 verbose stack     at C:\Users\lmc\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:329:20
8 verbose stack     at C:\Users\lmc\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
8 verbose stack     at FSReqWrap.oncomplete (fs.js:123:15)
9 verbose cwd C:\Users\lmc\Documents\projects\2014-04 CFF\src\test\MySpfxSolution
10 verbose Windows_NT 10.0.14393
11 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\lmc\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "shrinkwrap"
12 verbose node v6.11.2
13 verbose npm  v4.6.1
14 error Problems were encountered
14 error Please correct and try again.
14 error peer invalid: ajv@>=5.0.0, required by ajv-keywords@2.1.0
15 verbose exit [ 1, true ]

```
Also, if I run `npm list --depth=0`, I get the following error:

```
npm ERR! peer dep missing: ajv@>=5.0.0, required by ajv-keywords@2.1.0
```

#### How can the CLI team reproduce the problem?

Do *NOT* install `@microsoft/generator-sharepoint` globally (see [Why you should consider installing the SharePoint Framework Yeoman generator locally](https://blog.mastykarz.nl/install-sharepoint-framework-yeoman-generator-locally/)), and run the following commands:

```
mkdir demo-bug
cd demo-bug
npm install @microsoft/generator-sharepoint@1.3.2
yo @microsoft/sharepoint --solutionName "MySpfxSolution" --framework "react" --componentType "webpart" --componentName "MySpfxSolution" --componentDescription "MySpfxSolution web part" --environment "spo" skipFeatureDeployment false
rm -rf node_modules
cd MySpfxSolution
npm shrinkwrap
```

The second error mentioned is encountered when running

```
npm list --depth=0
```

### supporting information:

 - `npm -v` prints: `4.6.1`
 - `node -v` prints: `v6.11.2`
 - `npm config get registry` prints: `https://registry.npmjs.org/`
 - Windows, OS X/macOS, or Linux?: Windows 10

**Comment by lucmoco** [comment]
Sorry, wrong place.
