### ISSUE TITLE
broken NPM will not reinstall

### ISSUE THREAD

**Issue by mystikodesign** [npm/npm#18748]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
NPM is completely broken. I used 
curl -L https://www.npmjs.org/install.sh | sh
to install, but get this error as soon as the install starts:

module.js:473
      throw err;
      ^

Error: Cannot find module '/private/var/folders/9c/n55r03bd5yq2kjxb4mv58ggc0000gn/T/npm.5856/package/bin/read-package-json.js'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:453:25)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:607:3

#### How can the CLI team reproduce the problem?
I have no idea. 

### supporting information:

 - `npm -v` prints: -bash: /usr/local/Library/Aliases/npm: Permission denied
 - `node -v` prints: v8.6.0
 - `npm config get registry` prints: -bash: /usr/local/Library/Aliases/npm: Permission denied
 - Windows, OS X/macOS, or Linux?: macOS
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by Butterfly** [comment]
@mystikodesign Issue #18754 somehow duplicated a similar error or at least notable glitch. Because of the similar differences, both look potentially dynamically generated:

> /private/var/folders/rd/fdx_9z6d1tv00984k4b943rw0000gn/T/apm-install-dir-11798-78329-kaexn7.hdncxflxr/npm-debug.log

Am pointing your issues toward each other in hopes two instances start showing the pattern that created this. :smile:

**Comment by mystikodesign** [comment]
I have some acknowledgment from NPM that there is a script error in the NPM installer, & as I removed NPM to reinstall from scratch, as detailed above, I can now no longer get an install of 5.4.2. 

It seems that the install for NPM 5.3.0 was the last one that worked properly. NPM apparently no longer supports downgrading, but if someone has a method for installing 5.3.0 globally & helping me make sure it's on my PATH, I think that would be a solution for now…

**Comment by analytik** [comment]
You should be able to replicate this error with a following Dockerfile:

(EDIT: actually adding a step to install curl since it's not in default debian distro)

```
# Dockerfile with Node.js 8 
FROM debian

#COPY .npmrc /root/

RUN apt-get update && apt-get install -y curl

COPY npm-install-551.sh /tmp/node/npm-install.sh
RUN chmod a+x  /tmp/node/npm-install.sh

RUN curl -sL https://nodejs.org/download/release/v8.7.0/node-v8.7.0-linux-x64.tar.gz -o /tmp/node8.tar.gz \
    && mkdir -p /tmp/node \
    && tar -xzf /tmp/node8.tar.gz -C /tmp/node --strip-components=1 \
    && cp /tmp/node/bin/* /usr/bin/ \
#    && curl -0 -L https://npmjs.org/install.sh | bash \
    && /tmp/node/npm-install.sh \
    && rm /tmp/node8.tar.gz \
    && rm -rf /tmp/node/ \
    && rm -rf /usr/lib/node_modules/npm/.nyc_output \
    && npm install -g nodemon \
    && npm cache clean --force \
    && mkdir -p /project
```

The `npm-install-551.sh` file is a local copy of `https://npmjs.org/install.sh` except with two lines replaced to have a specific version:
```
      echo "install npm@5.5.1"
      t="5.5.1"
```

The whole output goes something like this:
```
Written by John Gilmore and Jay Fenlason.
install npm@5.5.1
[91mfetching: https://registry.npmjs.org/npm/-/npm-5.5.1.tgz
[0m[91mmodule.js:473
      throw err;
      ^

Error: Cannot find module '/tmp/npm.13/package/bin/read-package-json.js'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:453:25)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
[0mup to date in 0.028s
/usr/bin/npm -> /usr/lib/node_modules/npm/bin/npm-cli.js
/usr/bin/npx -> /usr/lib/node_modules/npm/bin/npx-cli.js
+ npm@5.5.1
added 1 package in 0.878s
It worked
[91m/bin/sh: 1: npm: not found
```

**Comment by JacobJT** [comment]
*sigh* just bumped into this following steps to fix another missing package issue where reinstalling npm like this was the suggested solution... Now it says `command not found: npm`

Is there any more progress on this since Nov 8?

Edit- It appears that my issues were due to using n. I've re-installed n so I could use the latest version (couldn't use npm since it said command not found...), but seems I'm running into other issues re: `cb() never called!`

**Comment by DanielRuf** [comment]
Pushing old threads will not help much as these people probably do not face the same issues currently.

**Comment by DanielRuf** [comment]
Did you reload your terminal and env, eg with `source`?
