### ISSUE TITLE
Forbidden 403 error, can't install anything.

### ISSUE THREAD

**Issue by krestenlaust** [npm/npm#18745]
I am opening this issue because I can't download anything.

```
C:\Users\kress>npm install -g http-server
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "http-server"
npm ERR! node v6.11.4
npm ERR! npm  v3.10.10
npm ERR! code E403

npm ERR! 403 Forbidden
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\kress\npm-debug.log
```

NPM-DEBUG.LOG:
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'http-server' ]
2 info using npm@3.10.10
3 info using node@v6.11.4
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData http-server
8 silly fetchNamedPackageData http-server
9 silly mapToRegistry name http-server
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://npm.fury.io/kres0345/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'http-server',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'http-server',
12 silly mapToRegistry   name: 'http-server',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://npm.fury.io/kres0345/http-server
14 verbose request uri https://npm.fury.io/kres0345/http-server
15 verbose request no auth needed
16 info attempt registry request try #1 at 23:09:43
17 verbose request using bearer token for auth
18 verbose request id ce6c3510e509d5de
19 http request GET https://npm.fury.io/kres0345/http-server
20 http 403 https://npm.fury.io/kres0345/http-server
21 verbose headers { connection: 'keep-alive',
21 verbose headers   'cache-control': 'no-cache',
21 verbose headers   'content-encoding': 'gzip',
21 verbose headers   'content-type': 'text/html',
21 verbose headers   date: 'Sat, 07 Oct 2017 21:09:45 GMT',
21 verbose headers   server: 'Cowboy',
21 verbose headers   'strict-transport-security': 'max-age=2629746; includeSubdomains',
21 verbose headers   vary: 'Accept-Encoding',
21 verbose headers   via: '1.1 vegur, 1.1 vegur',
21 verbose headers   'x-content-type-options': 'nosniff',
21 verbose headers   'x-download-options': 'noopen',
21 verbose headers   'x-frame-options': 'SAMEORIGIN',
21 verbose headers   'x-permitted-cross-domain-policies': 'none',
21 verbose headers   'x-request-id': 'd350de9e-ecb8-4df0-9151-027525191a3d',
21 verbose headers   'x-runtime': '0.011111',
21 verbose headers   'content-length': '23' }
22 silly get cb [ 403,
22 silly get   { connection: 'keep-alive',
22 silly get     'cache-control': 'no-cache',
22 silly get     'content-encoding': 'gzip',
22 silly get     'content-type': 'text/html',
22 silly get     date: 'Sat, 07 Oct 2017 21:09:45 GMT',
22 silly get     server: 'Cowboy',
22 silly get     'strict-transport-security': 'max-age=2629746; includeSubdomains',
22 silly get     vary: 'Accept-Encoding',
22 silly get     via: '1.1 vegur, 1.1 vegur',
22 silly get     'x-content-type-options': 'nosniff',
22 silly get     'x-download-options': 'noopen',
22 silly get     'x-frame-options': 'SAMEORIGIN',
22 silly get     'x-permitted-cross-domain-policies': 'none',
22 silly get     'x-request-id': 'd350de9e-ecb8-4df0-9151-027525191a3d',
22 silly get     'x-runtime': '0.011111',
22 silly get     'content-length': '23' } ]
23 silly fetchPackageMetaData Error: 403 Forbidden
23 silly fetchPackageMetaData     at makeError (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:302:12)
23 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:253:9)
23 silly fetchPackageMetaData     at C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:216:7
23 silly fetchPackageMetaData     at Gunzip.onEnd (zlib.js:227:5)
23 silly fetchPackageMetaData     at emitNone (events.js:91:20)
23 silly fetchPackageMetaData     at Gunzip.emit (events.js:185:7)
23 silly fetchPackageMetaData     at endReadableNT (_stream_readable.js:974:12)
23 silly fetchPackageMetaData     at _combinedTickCallback (internal/process/next_tick.js:80:11)
23 silly fetchPackageMetaData     at process._tickCallback (internal/process/next_tick.js:104:9)
23 silly fetchPackageMetaData  error for http-server { Error: 403 Forbidden
23 silly fetchPackageMetaData     at makeError (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:302:12)
23 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:253:9)
23 silly fetchPackageMetaData     at C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:216:7
23 silly fetchPackageMetaData     at Gunzip.onEnd (zlib.js:227:5)
23 silly fetchPackageMetaData     at emitNone (events.js:91:20)
23 silly fetchPackageMetaData     at Gunzip.emit (events.js:185:7)
23 silly fetchPackageMetaData     at endReadableNT (_stream_readable.js:974:12)
23 silly fetchPackageMetaData     at _combinedTickCallback (internal/process/next_tick.js:80:11)
23 silly fetchPackageMetaData     at process._tickCallback (internal/process/next_tick.js:104:9) statusCode: 403, code: 'E403' }
24 silly rollbackFailedOptional Starting
25 silly rollbackFailedOptional Finishing
26 silly runTopLevelLifecycles Finishing
27 silly install printInstalled
28 verbose stack Error: 403 Forbidden
28 verbose stack     at makeError (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:302:12)
28 verbose stack     at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:253:9)
28 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:216:7
28 verbose stack     at Gunzip.onEnd (zlib.js:227:5)
28 verbose stack     at emitNone (events.js:91:20)
28 verbose stack     at Gunzip.emit (events.js:185:7)
28 verbose stack     at endReadableNT (_stream_readable.js:974:12)
28 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:80:11)
28 verbose stack     at process._tickCallback (internal/process/next_tick.js:104:9)
29 verbose statusCode 403
30 verbose cwd C:\Users\kress
31 error Windows_NT 10.0.14393
32 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "http-server"
33 error node v6.11.4
34 error npm  v3.10.10
35 error code E403
36 error 403 Forbidden
37 error If you need help, you may report this error at:
37 error     <https://github.com/npm/npm/issues>
38 verbose exit [ 1, true ]
```

**Comment by Sumukha1496** [comment]
I am using node v8.9.1 , npm v5.5.1.  I am getting the error : 

```
npm ERR! code E403
npm ERR! 403 Forbidden: ANY_MODULE
npm ERR! A complete log of this run can be found in:
```

**Comment by rdodla** [comment]
I am using node v8.9.4, npm v5.6.0, i am getting the error 

npm ERR! code E403
npm ERR! 403 Forbidden: ANY_MODULE
npm ERR! A complete log of this run can be found in: 
npm ERR! Log file location in npm-cache.

Any help is appreciated.

**Comment by rdodla** [comment]
got it fixed by installig old version of node

**Comment by sfrooster** [comment]
I have the same issue with *any* version of node (and the accompanying npm) above v6.3.0.  Using nvm on osx.
