### ISSUE TITLE
NPM crashes with ProcessTerminatedError

### ISSUE THREAD

**Issue by vihanb** [npm/npm#18758]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
In my project's directory, running `npm install` seems to cause this. NPM will install for a bit and then around 80% of the way it will throw this error. Doing things like `npm i -g npm` don't seem to break.

Doesn't seem to be the OS killing NPM as when that happens it exits differently.

### supporting information:

The last part of the debug log looks like:

```
6775 verbose type ProcessTerminatedError
6776 verbose stack ProcessTerminatedError: cancel after 1 retries!
6776 verbose stack     at Farm.<anonymous> (/usr/lib/node_modules/npm/node_modules/worker-farm/lib/farm.js:87:25)
6776 verbose stack     at Array.forEach (native)
6776 verbose stack     at Farm.<anonymous> (/usr/lib/node_modules/npm/node_modules/worker-farm/lib/farm.js:81:36)
6776 verbose stack     at ontimeout (timers.js:469:11)
6776 verbose stack     at tryOnTimeout (timers.js:304:5)
6776 verbose stack     at Timer.listOnTimeout (timers.js:264:5)
6778 verbose Linux 4.4.0-83-generic
6779 verbose argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
6780 verbose node v8.2.1
6781 verbose npm  v5.3.0
6782 error cancel after 1 retries!
6783 verbose exit [ 1, true ]
```

**Comment by kulaone** [comment]
I had the same problem. I downgrade to npm v5.6.0 and now all working.
npm i -g npm@5.6.0

**Comment by danielweck** [comment]
With NPM `5.7.1`, `npm install` generates several error messages in the console:
```
Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:237:12)
    at PassThrough.Writable.write (_stream_writable.js:287:5)
    at PassThrough.Writable.end (_stream_writable.js:572:10)
    at ReadEntry.entry.on (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/extract-stream.js:19:41)
    at ReadEntry.emit (events.js:132:15)
    at ReadEntry.emit (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:287:25)
    at ReadEntry.[maybeEmitEnd] (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:240:12)
    at ReadEntry.end (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:153:27)
    at Unpack.[consumeBody] (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:210:13)
    at Unpack.[consumeChunkSub] (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:391:40)
    at Unpack.[consumeChunk] (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:360:30)
    at Unzip.(anonymous function).on.chunk (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:291:59)
    at Unzip.emit (events.js:127:13)
    at Unzip.emit (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:287:25)
    at Unzip.write (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:90:17)
    at Unzip.write (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minizlib/index.js:284:29)
npm ERR! cancel after 1 retries!
```

This does not occur when I downgrade to NPM `5.6.0`:
`npm install --global npm@5.6.0`

**Comment by danielweck** [comment]
Sounds similar to https://github.com/npm/npm/issues/20060
