### ISSUE TITLE
Listing angular packages is not permitted

### ISSUE THREAD

**Issue by bracco23** [npm/npm#18764]
#### I'm opening this issue because:

  - [X] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I try to list the version of @angular/cli package but npm crashes

#### How can the CLI team reproduce the problem?

 `npm install -g @angular/cli`
`npm list` ---> lists all packages, angular is shown correctly
`npm list @angular` gives error:

```
Unhandled rejection Error: Invalid tag name "@angular": Tags may not have any characters that encodeURIComponent encodes.
    at invalidTagName (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-package-arg\npa.js:76:15)
    at fromRegistry (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-package-arg\npa.js:265:13)
    at resolve (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-package-arg\npa.js:66:12)
    at npa (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-package-arg\npa.js:39:10)
    at C:\Program Files\nodejs\node_modules\npm\lib\ls.js:65:17
    at Array.map (<anonymous>)
    at ls.fromTree (C:\Program Files\nodejs\node_modules\npm\lib\ls.js:61:17)
    at C:\Program Files\nodejs\node_modules\npm\lib\ls.js:42:7
    at inflateShrinkwrap.then (C:\Program Files\nodejs\node_modules\npm\lib\install\inflate-shrinkwrap.js:32:11)
    at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
```

### supporting information:

 - `npm -v` prints: 5.3.0
 - `node -v` prints: v8.6.0
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?: Windows 10 version 1703
 - Network issues: none
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment]
So, to clarify, this is a feature request for `npm list` to show all installed packages that are under a particular scope?

**Comment by bracco23** [comment]
On first thought, I believed that, since it was giving me the error about the invalid tag, it would reject also full packages name because of the special characters. Now I checked and it correctly shows if I use the full packages. So I guess there is no bug about that.

By the way, that feature would indeed be useful.
