### ISSUE TITLE
can't install anything with npm

### ISSUE THREAD

**Issue by sipandey** [npm/npm#18790]
#### I'm opening this issue because:

  - [ ] npm is crashing.

#### What's going wrong?

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'express' ]
2 info using npm@3.10.10
3 info using node@v6.11.4
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData express
8 silly fetchNamedPackageData express
9 silly mapToRegistry name express
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'express',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'express',
12 silly mapToRegistry   name: 'express',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/express
14 verbose request uri https://registry.npmjs.org/express
15 verbose request no auth needed
16 info attempt registry request try #1 at 3:22:25 PM
17 verbose request id 19aee7d73a80eab5
18 http request GET https://registry.npmjs.org/express
19 info retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.112.162:443
20 info attempt registry request try #2 at 3:22:57 PM
21 http request GET https://registry.npmjs.org/express
22 info retry will retry, error on last attempt: Error: connect ETIMEDOUT 151.101.112.162:443
23 info attempt registry request try #3 at 3:24:18 PM
24 http request GET https://registry.npmjs.org/express
25 silly fetchPackageMetaData Error: connect ETIMEDOUT 151.101.112.162:443
25 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1020:11)
25 silly fetchPackageMetaData     at exports._exceptionWithHostPort (util.js:1043:20)
25 silly fetchPackageMetaData     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
25 silly fetchPackageMetaData  error for express { Error: connect ETIMEDOUT 151.101.112.162:443
25 silly fetchPackageMetaData     at Object.exports._errnoException (util.js:1020:11)
25 silly fetchPackageMetaData     at exports._exceptionWithHostPort (util.js:1043:20)
25 silly fetchPackageMetaData     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
25 silly fetchPackageMetaData   code: 'ETIMEDOUT',
25 silly fetchPackageMetaData   errno: 'ETIMEDOUT',
25 silly fetchPackageMetaData   syscall: 'connect',
25 silly fetchPackageMetaData   address: '151.101.112.162',
25 silly fetchPackageMetaData   port: 443 }
26 silly rollbackFailedOptional Starting
27 silly rollbackFailedOptional Finishing
28 silly runTopLevelLifecycles Finishing
29 silly install printInstalled
30 verbose stack Error: connect ETIMEDOUT 151.101.112.162:443
30 verbose stack     at Object.exports._errnoException (util.js:1020:11)
30 verbose stack     at exports._exceptionWithHostPort (util.js:1043:20)
30 verbose stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
31 verbose cwd C:\Users\Z003v4kh
32 error Windows_NT 6.1.7601
33 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "express"
34 error node v6.11.4
35 error npm  v3.10.10
36 error code ETIMEDOUT
37 error errno ETIMEDOUT
38 error syscall connect
39 error network connect ETIMEDOUT 151.101.112.162:443
40 error network This is most likely not a problem with npm itself
40 error network and is related to network connectivity.
40 error network In most cases you are behind a proxy or have bad network settings.
40 error network
40 error network If you are behind a proxy, please make sure that the
40 error network 'proxy' config is set properly.  See: 'npm help config'
41 verbose exit [ 1, true ]
```

**Comment by sipandey** [comment]
Below are the results of the following queries:

C:\WINDOWS\system32>npm config get registry
https://registry.npmjs.org/

C:\WINDOWS\system32>npm config get proxy
null

C:\WINDOWS\system32>npm config get https-proxy
null

**Comment by sipandey** [comment]
Hi,
I am still facing the same issue, if someone can help.
Thanks,
Sid
