### ISSUE TITLE
Unable to install eslint on DragonFly BSD

### ISSUE THREAD

**Issue by olleharstedt** [npm/npm#18848]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

Trying to install eslint, installer aborts with this error:

```
1091 verbose stack Error
1091 verbose stack     at /usr/local/lib/node_modules/npm/lib/utils/gently-rm.js:275:7
1091 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/iferr/index.js:13:50
1091 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:287:18
1091 verbose stack     at FSReqWrap.oncomplete (fs.js:153:5)
1092 verbose cwd /root/.npm/_logs
1093 verbose DragonFly 4.8-RELEASE
1094 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "-g" "npm"
1095 verbose node v8.4.0
1096 verbose npm  v5.3.0
1097 error code EINVAL
1098 error EINVAL: invalid argument, read
1099 verbose exit [ 1, true ]
```

#### How can the CLI team reproduce the problem?

Fresh installation of DragonFly BSD 4.8, install node and npm using the package manager, then try to install eslint.

Please let me know if I can provide any more information.

### supporting information:

 - `npm -v` prints: 5.3.0
 - `node -v` prints: v8.4.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: DragonFly BSD
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by mneumann** [comment]
You could try ```yarn```. I also had problems with ```npm``` on DragonFly and now use ```yarn``` [with success][1].

[1]: https://www.ntecs.de/blog/2017-08-10-developing-mobile-apps-on-dragonfly-with-react-native/

**Comment by olleharstedt** [comment]
Thank you, @mneumann, will try.

**Comment by olleharstedt** [comment]
@mneumann, sorry for bothering you. I installed yarn and eslint as super user, but other users cannot find it. You have any solution?
