### ISSUE TITLE
"npm install npm@latest -g"  breaks npm

### ISSUE THREAD

**Issue by sidsamant** [npm/npm#18854]
#### I'm opening this issue because:

  -  npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

On Fedora 26, running `npm install npm@latest -g` gives the following output:

```
- asap@2.0.5 node_modules/npm/node_modules/asap
- fstream@1.0.10 node_modules/npm/node_modules/fstream
- fstream-npm@1.2.0 node_modules/npm/node_modules/fstream-npm
- normalize-git-url@3.0.2 node_modules/npm/node_modules/normalize-git-url
- realize-package-specifier@3.0.3 node_modules/npm/node_modules/realize-package-specifier
/usr/lib
└── (empty)

npm ERR! Linux 4.13.5-200.fc26.x86_64
npm ERR! argv "/usr/bin/node" "/bin/npm" "install" "npm@latest" "-g"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! path /usr/lib/node_modules/npm/node_modules/columnify
npm ERR! code EEXIST
npm ERR! errno -17
npm ERR! syscall mkdir

npm ERR! EEXIST: file already exists, mkdir '/usr/lib/node_modules/npm/node_modules/columnify'
npm ERR! File exists: /usr/lib/node_modules/npm/node_modules/columnify
npm ERR! Move it away, and try again.
npm ERR! Linux 4.13.5-200.fc26.x86_64
npm ERR! argv "/usr/bin/node" "/bin/npm" "install" "npm@latest" "-g"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! path npm-debug.log.1340595565
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open 'npm-debug.log.1340595565'
npm ERR! enoent ENOENT: no such file or directory, open 'npm-debug.log.1340595565'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/lib/node_modules/npm/npm-debug.log
npm ERR! code 1
```

As per instruction, moved away the folder  [/usr/lib/node_modules/npm/node_modules/columnify](url)

```
$ npm -v
bash: /usr/bin/npm: No such file or directory
```

`/usr/lib/node_modules/npm/npm-debug.log` does not exist

#### How can the CLI team reproduce the problem?
As mentioned above

### supporting information:

 - `npm -v` prints: v3.10.10 prior to the upgrade.
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?: Linux
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by qborreda** [comment]
Happens on OSX Sierra (10.12.6) when trying to update with `npm upgrade npm@latest -g` or the `sudo npm upgrade npm@latest -g` version .. 

```
npm ERR! Darwin 16.7.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "upgrade" "npm@latest" "-g"
npm ERR! node v7.7.3
npm ERR! npm  v4.1.2
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'realize-package-specifier'
...
```

**Comment by octaharon** [comment]
Same on CentOS Linux release 7.3.1611 

>npm ERR! Linux 3.10.0-514.16.1.el7.x86_64
>npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "i" "-g" "npm"
>npm ERR! node v6.11.3
>npm ERR! npm  v3.10.10
>npm ERR! path /usr/lib/node_modules/npm/node_modules/columnify
>npm ERR! code EEXIST
>npm ERR! errno -17
>npm ERR! syscall mkdir
>
>npm ERR! EEXIST: file already exists, mkdir '/usr/lib/node_modules/npm/node_modules/columnify'
>npm ERR! File exists: /usr/lib/node_modules/npm/node_modules/columnify
>npm ERR! Move it away, and try again.

No containers, running as root

**Comment by facundovictor** [comment]
Same for me on CentOS Linux release 7.3.1611:
```sh
pm ERR! Linux 4.12.13-200.fc25.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "npm@2.1.3" "-g"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! path /usr/lib/node_modules/npm/node_modules/columnify
npm ERR! code EEXIST
npm ERR! errno -17
npm ERR! syscall mkdir

npm ERR! EEXIST: file already exists, mkdir '/usr/lib/node_modules/npm/node_modules/columnify'
npm ERR! File exists: /usr/lib/node_modules/npm/node_modules/columnify
npm ERR! Move it away, and try again.

npm ERR! Please include the following file with any support request:
npm ERR!     /npm-debug.log
npm ERR! code 1
```

But, when removing `/usr/lib/node_modules/npm/node_modules/columnify` and trying again from scratch:
```sh
npm ERR! Linux 4.12.13-200.fc25.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "npm@2.1.3" "-g"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! path /usr/lib/node_modules/npm/node_modules/dezalgo
npm ERR! code EEXIST
npm ERR! errno -17
npm ERR! syscall mkdir

npm ERR! EEXIST: file already exists, mkdir '/usr/lib/node_modules/npm/node_modules/dezalgo'
npm ERR! File exists: /usr/lib/node_modules/npm/node_modules/dezalgo
npm ERR! Move it away, and try again.

npm ERR! Please include the following file with any support request:
npm ERR!     /npm-debug.log
npm ERR! code 1
```

So, I also try to move away `/usr/lib/node_modules/npm/node_modules/dezalgo` and finally I get:
```sh
module.js:471
    throw err;
    ^

Error: Cannot find module 'dezalgo'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/npm/lib/utils/correct-mkdir.js:2:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```
 (╯°□°）╯︵ ┻━┻

**Comment by tlf30** [comment]
Having the same issue on fedora 26

**Comment by tracipotocnik** [comment]
Same issue on macOS HighSierra 10.13.2

**Comment by Mehuge** [comment]
Same issue on centos 7
