### ISSUE TITLE
can't run npm after upgrading to 5.5.1

### ISSUE THREAD

**Issue by vesper8** [npm/npm#18856]
everything was fine on 5.4.2, then I ran an upgrade. Even deleted node_modules and did a fresh npm install

getting these errors on 5.5.1

```
fs.js:682
  return binding.read(fd, buffer, offset, length, position);
                 ^

Error: EISDIR: illegal operation on a directory, read
    at Object.fs.readSync (fs.js:682:18)
    at tryReadSync (fs.js:543:20)
    at Object.fs.readFileSync (fs.js:586:19)
    at Function.concatenate.sync (/Volumes/DEV/www.mydomain.com/node_modules/concatenate/lib/concatenate.js:122:17)
    at FileCollection.merge (/Volumes/DEV/www.mydomain.com/node_modules/laravel-mix/src/FileCollection.js:31:36)
    at ConcatenateFilesTask.merge (/Volumes/DEV/www.mydomain.com/node_modules/laravel-mix/src/tasks/ConcatenateFilesTask.js:20:24)
    at ConcatenateFilesTask.run (/Volumes/DEV/www.mydomain.com/node_modules/laravel-mix/src/tasks/ConcatenateFilesTask.js:11:14)
    at CustomTasksPlugin.runTask (/Volumes/DEV/www.mydomain.com/node_modules/laravel-mix/src/plugins/CustomTasksPlugin.js:34:14)
    at Mix.tasks.forEach.task (/Volumes/DEV/www.mydomain.com/node_modules/laravel-mix/src/plugins/CustomTasksPlugin.js:9:44)
    at Array.forEach (<anonymous>)
    at Compiler.compiler.plugin.stats (/Volumes/DEV/www.mydomain.com/node_modules/laravel-mix/src/plugins/CustomTasksPlugin.js:9:23)
    at Compiler.applyPlugins (/Volumes/DEV/www.mydomain.com/node_modules/tapable/lib/Tapable.js:61:14)
    at Watching._done (/Volumes/DEV/www.mydomain.com/node_modules/webpack/lib/Compiler.js:104:17)
    at compiler.emitRecords.err (/Volumes/DEV/www.mydomain.com/node_modules/webpack/lib/Compiler.js:78:19)
    at Compiler.emitRecords (/Volumes/DEV/www.mydomain.com/node_modules/webpack/lib/Compiler.js:375:38)
    at compiler.emitAssets.err (/Volumes/DEV/www.mydomain.com/node_modules/webpack/lib/Compiler.js:61:20)
    at applyPluginsAsyncSeries1.err (/Volumes/DEV/www.mydomain.com/node_modules/webpack/lib/Compiler.js:368:12)
    at next (/Volumes/DEV/www.mydomain.com/node_modules/tapable/lib/Tapable.js:218:11)
    at Compiler.compiler.plugin (/Volumes/DEV/www.mydomain.com/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (/Volumes/DEV/www.mydomain.com/node_modules/tapable/lib/Tapable.js:222:13)
    at Compiler.afterEmit (/Volumes/DEV/www.mydomain.com/node_modules/webpack/lib/Compiler.js:365:9)
    at require.forEach.err (/Volumes/DEV/www.mydomain.com/node_modules/webpack/lib/Compiler.js:354:15)
    at /Volumes/DEV/www.mydomain.com/node_modules/webpack/node_modules/async/dist/async.js:421:16
    at iteratorCallback (/Volumes/DEV/www.mydomain.com/node_modules/webpack/node_modules/async/dist/async.js:998:13)
    at /Volumes/DEV/www.mydomain.com/node_modules/webpack/node_modules/async/dist/async.js:906:16
    at /Volumes/DEV/www.mydomain.com/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:136:15)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ watch: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ watch script.
```

work fine again after downgrading back to npm@5.4

**Comment by kenany** [comment]
@vesper8 `node --version`?

**Comment by vesper8** [comment]
@KenanY 8.7.0
