### ISSUE TITLE
npm adduser not working

### ISSUE THREAD

**Issue by kobaska** [npm/npm#18882]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
can't login to npm

#### How can the CLI team reproduce the problem?
npm adduser

### supporting information:

npm ERR! 200 Could not create user
npm ERR! {"_id":"org.couchdb.user:buildymcbuildy","email":"build@agriwebb.com","name":"buildymcbuildy"}

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kogulanbaskaran/.npm/_logs/2017-10-18T01_28_09_663Z-debug.log

cat /Users/kogulanbaskaran/.npm/_logs/2017-10-18T01_28_09_663Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'login' ]
2 info using npm@4.6.1
3 info using node@v6.10.1
4 verbose adduser before first PUT { _id: 'org.couchdb.user:buildymcbuildy',
4 verbose adduser   name: 'buildymcbuildy',
4 verbose adduser   password: 'XXXXX',
4 verbose adduser   email: 'build@agriwebb.com',
4 verbose adduser   type: 'user',
4 verbose adduser   roles: [],
4 verbose adduser   date: '2017-10-18T01:28:07.935Z' }
5 verbose request uri https://registry.npmjs.org/-/user/org.couchdb.user:buildymcbuildy
6 verbose request new user, so can't send auth
7 info attempt registry request try #1 at 12:28:07 PM
8 verbose request id 0e77179f85e746a6
9 http request PUT https://registry.npmjs.org/-/user/org.couchdb.user:buildymcbuildy
10 http 200 https://registry.npmjs.org/-/user/org.couchdb.user:buildymcbuildy
11 verbose headers { 'content-type': 'application/json',
11 verbose headers   'content-encoding': 'gzip',
11 verbose headers   'cache-control': 'max-age=300',
11 verbose headers   'content-length': '89',
11 verbose headers   'accept-ranges': 'bytes',
11 verbose headers   date: 'Wed, 18 Oct 2017 01:28:09 GMT',
11 verbose headers   via: '1.1 varnish',
11 verbose headers   age: '0',
11 verbose headers   connection: 'keep-alive',
11 verbose headers   'x-served-by': 'cache-syd1624-SYD',
11 verbose headers   'x-cache': 'MISS',
11 verbose headers   'x-cache-hits': '0',
11 verbose headers   'x-timer': 'S1508290088.116140,VS0,VE921',
11 verbose headers   vary: 'Accept-Encoding, Accept' }
12 verbose request invalidating /Users/kogulanbaskaran/.npm/registry.npmjs.org/-/user/org.couchdb.user_3Abuildymcbuildy on PUT
13 verbose adduser back [ null,
13 verbose adduser   { _id: 'org.couchdb.user:buildymcbuildy',
13 verbose adduser     email: 'build@agriwebb.com',
13 verbose adduser     name: 'buildymcbuildy' },
13 verbose adduser   '{"_id":"org.couchdb.user:buildymcbuildy","email":"build@agriwebb.com","name":"buildymcbuildy"}' ]
14 verbose stack Error: 200 Could not create user
14 verbose stack {"_id":"org.couchdb.user:buildymcbuildy","email":"build@agriwebb.com","name":"buildymcbuildy"}
14 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/adduser.js:113:17
14 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/adduser.js:74:16
14 verbose stack     at /usr/local/lib/node_modules/npm/lib/cache/caching-client.js:49:12
14 verbose stack     at next (/usr/local/lib/node_modules/npm/node_modules/rimraf/rimraf.js:74:7)
14 verbose stack     at CB (/usr/local/lib/node_modules/npm/node_modules/rimraf/rimraf.js:110:9)
14 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/rimraf/rimraf.js:136:14
14 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:284:29
14 verbose stack     at FSReqWrap.oncomplete (fs.js:123:15)
15 verbose cwd /Users/kogulanbaskaran/development/sync
16 verbose Darwin 15.6.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "login"
18 verbose node v6.10.1
19 verbose npm  v4.6.1
20 error 200 Could not create user
20 error {"_id":"org.couchdb.user:buildymcbuildy","email":"build@agriwebb.com","name":"buildymcbuildy"}
21 verbose exit [ 1, true ]

**Comment by kobaska** [comment]
Back up again
