### ISSUE TITLE
cannot find module 'ejs'

### ISSUE THREAD

**Issue by akinrodoluseun** [npm/npm#18900]
Error: Cannot find module 'ejs'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at new View (C:\Users\Gozie\Desktop\node-crude\node_modules\express\lib\view.js:81:14)
    at EventEmitter.render (C:\Users\Gozie\Desktop\node-crude\node_modules\express\lib\application.js:570:12)
    at ServerResponse.render (C:\Users\Gozie\Desktop\node-crude\node_modules\express\lib\response.js:1008:7)
    at ServerResponse.res.render (C:\Users\Gozie\Desktop\node-crude\node_modules\express-ejs-layouts\lib\express-layouts.js:77:18)
    at showHome (C:\Users\Gozie\Desktop\node-crude\app\controller\main.controller.js:5:6)
    at Layer.handle [as handle_request] (C:\Users\Gozie\Desktop\node-crude\node_modules\express\lib\router\layer.js:95:5)

**Comment by kenany** [comment]
This error does not seem to be coming from `npm`.
