### ISSUE TITLE
npm publish gives E404 for private package

### ISSUE THREAD

**Issue by marcoturi** [npm/npm#18932]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [X] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
On the command `npm publish` I'm getting:
```
npm ERR! publish Failed PUT 404
npm ERR! code E404
npm ERR! 404 Not found : @topconagriculture/react-components
npm ERR! 404 
npm ERR! 404  '@topconagriculture/react-components' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/marco/.npm/_logs/2017-10-23T09_45_48_180Z-debug.log
---------------------------------
cat /Users/marco/.npm/_logs/2017-10-23T09_46_20_664Z-debug.log      
0 info it worked if it ends with ok
1 verbose cli [ '/Users/marco/.nvm/versions/node/v6.11.1/bin/node',
1 verbose cli   '/Users/marco/.nvm/versions/node/v6.11.1/bin/npm',
1 verbose cli   'publish' ]
2 info using npm@5.5.1
3 info using node@v6.11.1
4 verbose npm-session 3ced89b7673ff220
5 verbose publish [ '.' ]
6 info lifecycle @topconagriculture/react-components@1.0.0~prepublish: @topconagriculture/react-components@1.0.0
7 info lifecycle @topconagriculture/react-components@1.0.0~prepare: @topconagriculture/react-components@1.0.0
8 info lifecycle @topconagriculture/react-components@1.0.0~prepublishOnly: @topconagriculture/react-components@1.0.0
9 info lifecycle @topconagriculture/react-components@1.0.0~prepack: @topconagriculture/react-components@1.0.0
10 info lifecycle @topconagriculture/react-components@1.0.0~postpack: @topconagriculture/react-components@1.0.0
11 verbose getPublishConfig undefined
12 silly mapToRegistry name @topconagriculture/react-components
13 silly mapToRegistry scope (from package name) @topconagriculture
14 verbose mapToRegistry no registry URL found in name for scope @topconagriculture
15 silly mapToRegistry using default registry
16 silly mapToRegistry registry https://registry.npmjs.org/
17 silly mapToRegistry data { type: 'tag',
17 silly mapToRegistry   registry: true,
17 silly mapToRegistry   where: undefined,
17 silly mapToRegistry   raw: '@topconagriculture/react-components',
17 silly mapToRegistry   name: '@topconagriculture/react-components',
17 silly mapToRegistry   escapedName: '@topconagriculture%2freact-components',
17 silly mapToRegistry   scope: '@topconagriculture',
17 silly mapToRegistry   rawSpec: '',
17 silly mapToRegistry   saveSpec: null,
17 silly mapToRegistry   fetchSpec: 'latest',
17 silly mapToRegistry   gitRange: undefined,
17 silly mapToRegistry   gitCommittish: undefined,
17 silly mapToRegistry   hosted: undefined }
18 silly mapToRegistry uri https://registry.npmjs.org/@topconagriculture%2freact-components
19 verbose publish registryBase https://registry.npmjs.org/
20 silly publish uploading /var/folders/k_/5fzrz1294kg8cmgsx6b5961w0000gn/T/npm-12294-72cfdea6/tmp/fromDir-880d092d/package.tgz
21 verbose request uri https://registry.npmjs.org/@topconagriculture%2freact-components
22 verbose request sending authorization for write operation
23 info attempt registry request try #1 at 11:46:19 AM
24 verbose request using bearer token for auth
25 verbose request id ddd4ddfccf5c2375
26 http request PUT https://registry.npmjs.org/@topconagriculture%2freact-components
27 http 404 https://registry.npmjs.org/@topconagriculture%2freact-components
28 verbose headers { 'content-type': 'application/json',
28 verbose headers   'cache-control': 'max-age=0',
28 verbose headers   'content-length': '21',
28 verbose headers   'accept-ranges': 'bytes',
28 verbose headers   date: 'Mon, 23 Oct 2017 09:46:20 GMT',
28 verbose headers   via: '1.1 varnish',
28 verbose headers   connection: 'keep-alive',
28 verbose headers   'x-served-by': 'cache-hhn1529-HHN',
28 verbose headers   'x-cache': 'MISS',
28 verbose headers   'x-cache-hits': '0',
28 verbose headers   'x-timer': 'S1508751980.913158,VS0,VE669' }
29 error publish Failed PUT 404
30 verbose stack Error: Not found : @topconagriculture/react-components
30 verbose stack     at makeError (/Users/marco/.nvm/versions/node/v6.11.1/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:314:12)
30 verbose stack     at RegClient.<anonymous> (/Users/marco/.nvm/versions/node/v6.11.1/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:302:14)
30 verbose stack     at Request._callback (/Users/marco/.nvm/versions/node/v6.11.1/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:216:14)
30 verbose stack     at Request.self.callback (/Users/marco/.nvm/versions/node/v6.11.1/lib/node_modules/npm/node_modules/request/request.js:186:22)
30 verbose stack     at emitTwo (events.js:106:13)
30 verbose stack     at Request.emit (events.js:191:7)
30 verbose stack     at Request.<anonymous> (/Users/marco/.nvm/versions/node/v6.11.1/lib/node_modules/npm/node_modules/request/request.js:1163:10)
30 verbose stack     at emitOne (events.js:96:13)
30 verbose stack     at Request.emit (events.js:188:7)
30 verbose stack     at IncomingMessage.<anonymous> (/Users/marco/.nvm/versions/node/v6.11.1/lib/node_modules/npm/node_modules/request/request.js:1085:12)
30 verbose stack     at IncomingMessage.g (events.js:292:16)
30 verbose stack     at emitNone (events.js:91:20)
30 verbose stack     at IncomingMessage.emit (events.js:185:7)
30 verbose stack     at endReadableNT (_stream_readable.js:974:12)
30 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:80:11)
30 verbose stack     at process._tickCallback (internal/process/next_tick.js:104:9)
31 verbose statusCode 404
32 verbose pkgid @topconagriculture/react-components
33 verbose cwd /Users/marco/Sources/Topcon/react-components/build
34 verbose Darwin 16.7.0
35 verbose argv "/Users/marco/.nvm/versions/node/v6.11.1/bin/node" "/Users/marco/.nvm/versions/node/v6.11.1/bin/npm" "publish"
36 verbose node v6.11.1
37 verbose npm  v5.5.1
38 error code E404
39 error 404 Not found : @topconagriculture/react-components
40 error 404
41 error 404 '@topconagriculture/react-components' is not in the npm registry.
42 error 404 You should bug the author to publish it (or use the name yourself!)
43 error 404 Note that you can also install from a
44 error 404 tarball, folder, http url, or git url.
45 verbose exit [ 1, true ]


```
I'm getting this error from the last week, before I was able to publish my private package.
#### How can the CLI team reproduce the problem?
`npm publish` or `npm info`
### supporting information:

 - `npm -v` prints: 5.5.1
 - `node -v` prints: 6.11.1
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: MacOs
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

I have also contacted the support of npmjs last week, but I didn't get any reply.

**Comment by marcoturi** [comment]
I found the error, there were a typo in the login username.
