### ISSUE TITLE
npm ERR! Windows_NT 10.0.15063

### ISSUE THREAD

**Issue by poperechnyi1** [npm/npm#18968]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [-] npm is doing something I don't understand.
  - [-] Other (_see below for feature requests_):

#### When I try npm run deployScript that I have result
```
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "deployContract"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10

npm ERR! missing script: deployContract
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Compiled contract\WEB3 Deploy contract\deploy via Web3 node\npm-debug.log

```

Losg in npm-debug.log
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'deployContract' ]
2 info using npm@3.10.10
3 info using node@v6.11.3
4 verbose stack Error: missing script: deployContract
4 verbose stack     at run (C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:151:19)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:61:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:356:5
4 verbose stack     at checkBinReferences_ (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:320:45)
4 verbose stack     at final (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:354:3)
4 verbose stack     at then (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:124:5)
4 verbose stack     at ReadFileContext.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:295:20)
4 verbose stack     at ReadFileContext.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16)
4 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:367:13)
5 verbose cwd D:\Compiled contract\WEB3 Deploy contract\deploy via Web3 node
6 error Windows_NT 10.0.15063
7 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "deployContract"
8 error node v6.11.3
9 error npm  v3.10.10
10 error missing script: deployContract
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
```

**Comment by kenany** [comment]
Is `"deployContract"` a defined script in your `package.json`?

**Comment by poperechnyi1** [comment]
This is code of my package.json
```
{
  "name": "package.json",
  "version": "1.0.0",
  "description": "",
  "main": "deployContract.js",
  "directories": {
    "test": "test"
  },
  "dependencies": {},
  "devDependencies": {
    "web3" : "latest",
    "fs" : "latest"
  },
  "scripts": {
    "start" : "node deployContract.js"
  },
  "author": "",
  "license": "ISC"
}
```

**Comment by kenany** [comment]
@poperechnyi1 I'm guessing that you should be running `npm start` instead. At least, that's the only script you have defined.

**Comment by poperechnyi1** [comment]
I runed `npm start` but I have prom with it:
$ npm start

> package.json@1.0.0 start D:\Compiled contract\WEB3 Deploy contract\deploy via Web3 node
> node deployContract.js

module.js:471
    throw err;
    ^

```
Error: Cannot find module 'web3'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\Compiled contract\WEB3 Deploy contract\deploy via Web3 node\deployContract.js:14:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.11.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! package.json@1.0.0 start: `node deployContract.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the package.json@1.0.0 start script 'node deployContract.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the package.json package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node deployContract.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs package.json
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls package.json
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Compiled contract\WEB3 Deploy contract\deploy via Web3 node\npm-debug.log
```
After that I tried install web3, I runed the command `npm install` and I have many errors:


```
> scrypt@6.0.3 preinstall D:\Compiled contract\WEB3 Deploy contract\deploy via Web3 node\node_modules\.staging\scrypt-3c2871c0
> node node-scrypt-preinstall.js


> scrypt@6.0.3 install D:\Compiled contract\WEB3 Deploy contract\deploy via Web3 node\node_modules\scrypt
> node-gyp rebuild


D:\Compiled contract\WEB3 Deploy contract\deploy via Web3 node\node_modules\scrypt>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Warning: Missing input files:
D:\Compiled contract\WEB3 Deploy contract\deploy via Web3 node\node_modules\scrypt\build\..\scrypt\win\include\config.h
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [D:\Compiled contract\WEB3 Deploy contract\deploy via Web3 node\node_modules\scrypt\build\binding.sln]
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [D:\Compiled contract\WEB3 Deploy contract\deploy via Web3 node\node_modules\scrypt\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Compiled contract\WEB3 Deploy contract\deploy via Web3 node\node_modules\scrypt
gyp ERR! node -v v6.11.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
package.json@1.0.0 D:\Compiled contract\WEB3 Deploy contract\deploy via Web3 node
`-- (empty)

npm WARN package.json@1.0.0 No description
npm WARN package.json@1.0.0 No repository field.
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.11.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scrypt@6.0.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the scrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs scrypt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls scrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Compiled contract\WEB3 Deploy contract\deploy via Web3 node\npm-debug.log
npm ERR! code 1

```

**Comment by kenany** [comment]
Seems to be an error from `node-gyp`, not `npm`:

```
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [D:\Compiled contract\WEB3 Deploy contract\deploy via Web3 node\node_modules\scrypt\build\binding.sln]
```

**Comment by Shreerag1** [comment]
Even I'm facing the same problem @poperechnyi1 
$ npm start
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\        node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.11.5
npm ERR! npm  v3.10.10

npm ERR! missing script: start
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\gitProjects\testapp\npm-debug.log

Someone please help me out :)

@poperechnyi1  you may try this
($ npm install --save pouchdb-browser @hoodie/client)  for npm v2, but that's not working in my case.

**Comment by kenany** [comment]
@Shreerag1 Ensure that you have a `"start"` script defined in your `package.json`.

**Comment by Shreerag1** [comment]
Thanks @KenanY , it was my own fault :), the prior step - npm install requires time to complete, once that's done, everything is fine now. Slower computers require 3-5 minutes to complete.

**Comment by sridevig** [comment]
when i try npm start getting below error
npm start
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3

npm ERR! missing script: start
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:


My package.json having start. 
Package.json
{
  "name": "reactapp1",
  "version": "1.0.0",
  "description": "",
  "main": "main.js",
  "scripts": {
    "start:": "webpack-dev-server --hot"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "webpack": "^4.8.3",
    "webpack-dev-server": "^3.1.4"
  },
  "dependencies": {
    "pouchdb-browser": "^6.4.3"
  }
}

**Comment by legodude17** [comment]
@sridevig Make sure that you are running `npm start` in the directory with the `package.json`. Also please update your npm version (using `npm i -g npm`).

**Comment by sridevig** [comment]
I updated my version and running npm start in the directory with package.json only. but still facing the issue.
npm version: 6.1.0
\reactapp1>npm start
npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\.......\AppData\Roaming\npm-cache\_logs\2018-05-28T04_51_26_419Z-debug.log

debug.log file content here:
........
.......
5 verbose cwd C:\Users\600008976\Desktop\learn\reactapp1
6 verbose Windows_NT 10.0.15063
7 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\600008976\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
8 verbose node v6.3.1
9 verbose npm  v6.1.0
10 error missing script: start
11 verbose exit [ 1, true ]

**Comment by kenany** [comment]
Remove the colon (`:`) that comes after the letter `t` in `start`

```json
"start:": "webpack-dev-server --hot"
      ^ remove this
```

**Comment by poperechnyi1** [comment]
If you want to work with web3.js you must use ubuntu instead windows. 
For WINDOWS 10: I installed `npm install --global --production windows-build-tools` then I installed web3 via command `npm install web3 --g`. It resolved my problem for Windows 10. 
More details: [https://github.com/nodejs/node-gyp#option-1](url)
