### ISSUE TITLE
Failure to install npm on windows: WindowsError: [Error 206] The filename or extension is too long:

### ISSUE THREAD

**Issue by asottile** [npm/npm#18978]
This is a reopen of #17663

#### I'm opening this issue because:

  - npm is crashing.

##### Reproduction 1 (using gui)

1. Download the zip from https://nodejs.org/en/download/current/
    - I used this url: https://nodejs.org/dist/v8.8.1/node-v8.8.1-win-x64.zip
2. Extract using the windows GUI, I extracted to `C:\Users\Anthony\Desktop\node-v8.8.1-win-x64` (a relatively short path, but long enough to trigger the issue).

![](https://i.fluffy.cc/cHMJk1F18BSG15SfMHRqLFqXBsQdSRNT.png)

This fails with the following error dialog:

![](https://i.fluffy.cc/pPdpPBxPT6q4fLkrPqFr3tJxX3JdrpLs.png)

##### Reproduction 2 (using cli tool)

This is the reproduction I actually care about as it impacts tools I am developing, but it slightly more difficult to reproduce due to needing to install tools (https://github.com/ekalinin/nodeenv/issues/190)

1. Install nodeenv (a python package)
2. `nodeenv C:/Temp/123456789012345678901234567890/nenv`

It crashes with:

```
 nodeenv C:/Temp/123456789012345678901234567890/nenv
 * Install prebuilt node (8.8.1) ..... done.
Invalid switch - "Temp".
Invalid switch - "Temp".
Error: Failed to create nodejs.exe link
 * Install npm.js (latest) ... Traceback (most recent call last):
  File "c:\python27\Lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\Anthony\AppData\Local\Temp\foo\pre-commit\venv\Scripts\nodeenv.exe\__main__.py", line 9, in <module>
  File "c:\users\anthony\appdata\local\temp\foo\pre-commit\venv\lib\site-packages\nodeenv.py", line 1060, in main
    create_environment(env_dir, opt)
  File "c:\users\anthony\appdata\local\temp\foo\pre-commit\venv\lib\site-packages\nodeenv.py", line 902, in create_environment
    instfunc(env_dir, src_dir, opt)
  File "c:\users\anthony\appdata\local\temp\foo\pre-commit\venv\lib\site-packages\nodeenv.py", line 756, in install_npm_win
    shutil.copytree(join(src_dir, npm_ver), node_modules_path)
  File "c:\python27\Lib\shutil.py", line 208, in copytree
    raise Error, errors
shutil.Error: [('C:\\Temp\\123456789012345678901234567890\\nenv\\src\\npm-latest\\node_modules\\libnpx\\node_modules\\yargs\\node_modules\\read-pkg-up\\node_modules\\read-pkg\\node_modules\\load-json-file\\node_modules\\parse-json\\node_modules\\error-ex\\node_modules\\is-arrayish', 'C:/Temp/123456789012345678901234567890/nenv\\Scripts\\node_modules\\npm\\node_modules\\libnpx\\node_modules\\yargs\\node_modules\\read-pkg-up\\node_modules\\read-pkg\\node_modules\\load-json-file\\node_modules\\parse-json\\node_modules\\error-ex\\node_modules\\is-arrayish', "[Error 206] The filename or extension is too long: 'C:/Temp/123456789012345678901234567890/nenv\\\\Scripts\\\\node_modules\\\\npm\\\\node_modules\\\\libnpx\\\\node_modules\\\\yargs\\\\node_modules\\\\read-pkg-up\\\\node_modules\\\\read-pkg\\\\node_modules\\\\load-json-file\\\\node_modules\\\\parse-json\\\\node_modules\\\\error-ex\\\\node_modules\\\\is-arrayish'"), ('C:\\Temp\\123456789012345678901234567890\\nenv\\src\\npm-latest\\node_modules\\npm-profile\\node_modules\\make-fetch-happen\\node_modules\\http-proxy-agent\\node_modules\\agent-base\\node_modules\\es6-promisify\\node_modules\\es6-promise\\dist\\es6-promise.auto.min.map', 'C:/Temp/123456789012345678901234567890/nenv\\Scripts\\node_modules\\npm\\node_modules\\npm-profile\\node_modules\\make-fetch-happen\\node_modules\\http-proxy-agent\\node_modules\\agent-base\\node_modules\\es6-promisify\\node_modules\\es6-promise\\dist\\es6-promise.auto.min.map', "[Errno 2] No such file or directory: 'C:/Temp/123456789012345678901234567890/nenv\\\\Scripts\\\\node_modules\\\\npm\\\\node_modules\\\\npm-profile\\\\node_modules\\\\make-fetch-happen\\\\node_modules\\\\http-proxy-agent\\\\node_modules\\\\agent-base\\\\node_modules\\\\es6-promisify\\\\node_modules\\\\es6-promise\\\\dist\\\\es6-promise.auto.min.map'"), ('C:\\Temp\\123456789012345678901234567890\\nenv\\src\\npm-latest\\node_modules\\npm-profile\\node_modules\\make-fetch-happen\\node_modules\\http-proxy-agent\\node_modules\\agent-base\\node_modules\\es6-promisify\\node_modules\\es6-promise\\lib\\es6-promise\\enumerator.js', 'C:/Temp/123456789012345678901234567890/nenv\\Scripts\\node_modules\\npm\\node_modules\\npm-profile\\node_modules\\make-fetch-happen\\node_modules\\http-proxy-agent\\node_modules\\agent-base\\node_modules\\es6-promisify\\node_modules\\es6-promise\\lib\\es6-promise\\enumerator.js', "[Errno 2] No such file or directory: 'C:/Temp/123456789012345678901234567890/nenv\\\\Scripts\\\\node_modules\\\\npm\\\\node_modules\\\\npm-profile\\\\node_modules\\\\make-fetch-happen\\\\node_modules\\\\http-proxy-agent\\\\node_modules\\\\agent-base\\\\node_modules\\\\es6-promisify\\\\node_modules\\\\es6-promise\\\\lib\\\\es6-promise\\\\enumerator.js'"), ('C:\\Temp\\123456789012345678901234567890\\nenv\\src\\npm-latest\\node_modules\\npm-profile\\node_modules\\make-fetch-happen\\node_modules\\http-proxy-agent\\node_modules\\agent-base\\node_modules\\es6-promisify\\node_modules\\es6-promise\\lib\\es6-promise\\promise', 'C:/Temp/123456789012345678901234567890/nenv\\Scripts\\node_modules\\npm\\node_modules\\npm-profile\\node_modules\\make-fetch-happen\\node_modules\\http-proxy-agent\\node_modules\\agent-base\\node_modules\\es6-promisify\\node_modules\\es6-promise\\lib\\es6-promise\\promise', "[Error 206] The filename or extension is too long: 'C:/Temp/123456789012345678901234567890/nenv\\\\Scripts\\\\node_modules\\\\npm\\\\node_modules\\\\npm-profile\\\\node_modules\\\\make-fetch-happen\\\\node_modules\\\\http-proxy-agent\\\\node_modules\\\\agent-base\\\\node_modules\\\\es6-promisify\\\\node_modules\\\\es6-promise\\\\lib\\\\es6-promise\\\\promise'"), ('C:\\Temp\\123456789012345678901234567890\\nenv\\src\\npm-latest\\node_modules\\npm-profile\\node_modules\\make-fetch-happen\\node_modules\\https-proxy-agent\\node_modules\\agent-base\\node_modules\\es6-promisify\\node_modules\\es6-promise\\dist\\es6-promise.auto.min.js', 'C:/Temp/123456789012345678901234567890/nenv\\Scripts\\node_modules\\npm\\node_modules\\npm-profile\\node_modules\\make-fetch-happen\\node_modules\\https-proxy-agent\\node_modules\\agent-base\\node_modules\\es6-promisify\\node_modules\\es6-promise\\dist\\es6-promise.auto.min.js', "[Errno 2] No such file or directory: 'C:/Temp/123456789012345678901234567890/nenv\\\\Scripts\\\\node_modules\\\\npm\\\\node_modules\\\\npm-profile\\\\node_modules\\\\make-fetch-happen\\\\node_modules\\\\https-proxy-agent\\\\node_modules\\\\agent-base\\\\node_modules\\\\es6-promisify\\\\node_modules\\\\es6-promise\\\\dist\\\\es6-promise.auto.min.js'"), ('C:\\Temp\\123456789012345678901234567890\\nenv\\src\\npm-latest\\node_modules\\npm-profile\\node_modules\\make-fetch-happen\\node_modules\\https-proxy-agent\\node_modules\\agent-base\\node_modules\\es6-promisify\\node_modules\\es6-promise\\dist\\es6-promise.auto.min.map', 'C:/Temp/123456789012345678901234567890/nenv\\Scripts\\node_modules\\npm\\node_modules\\npm-profile\\node_modules\\make-fetch-happen\\node_modules\\https-proxy-agent\\node_modules\\agent-base\\node_modules\\es6-promisify\\node_modules\\es6-promise\\dist\\es6-promise.auto.min.map', "[Errno 2] No such file or directory: 'C:/Temp/123456789012345678901234567890/nenv\\\\Scripts\\\\node_modules\\\\npm\\\\node_modules\\\\npm-profile\\\\node_modules\\\\make-fetch-happen\\\\node_modules\\\\https-proxy-agent\\\\node_modules\\\\agent-base\\\\node_modules\\\\es6-promisify\\\\node_modules\\\\es6-promise\\\\dist\\\\es6-promise.auto.min.map'"), ('C:\\Temp\\123456789012345678901234567890\\nenv\\src\\npm-latest\\node_modules\\npm-profile\\node_modules\\make-fetch-happen\\node_modules\\https-proxy-agent\\node_modules\\agent-base\\node_modules\\es6-promisify\\node_modules\\es6-promise\\lib\\es6-promise\\-internal.js', 'C:/Temp/123456789012345678901234567890/nenv\\Scripts\\node_modules\\npm\\node_modules\\npm-profile\\node_modules\\make-fetch-happen\\node_modules\\https-proxy-agent\\node_modules\\agent-base\\node_modules\\es6-promisify\\node_modules\\es6-promise\\lib\\es6-promise\\-internal.js', "[Errno 2] No such file or directory: 'C:/Temp/123456789012345678901234567890/nenv\\\\Scripts\\\\node_modules\\\\npm\\\\node_modules\\\\npm-profile\\\\node_modules\\\\make-fetch-happen\\\\node_modules\\\\https-proxy-agent\\\\node_modules\\\\agent-base\\\\node_modules\\\\es6-promisify\\\\node_modules\\\\es6-promise\\\\lib\\\\es6-promise\\\\-internal.js'"), ('C:\\Temp\\123456789012345678901234567890\\nenv\\src\\npm-latest\\node_modules\\npm-profile\\node_modules\\make-fetch-happen\\node_modules\\https-proxy-agent\\node_modules\\agent-base\\node_modules\\es6-promisify\\node_modules\\es6-promise\\lib\\es6-promise\\enumerator.js', 'C:/Temp/123456789012345678901234567890/nenv\\Scripts\\node_modules\\npm\\node_modules\\npm-profile\\node_modules\\make-fetch-happen\\node_modules\\https-proxy-agent\\node_modules\\agent-base\\node_modules\\es6-promisify\\node_modules\\es6-promise\\lib\\es6-promise\\enumerator.js', "[Errno 2] No such file or directory: 'C:/Temp/123456789012345678901234567890/nenv\\\\Scripts\\\\node_modules\\\\npm\\\\node_modules\\\\npm-profile\\\\node_modules\\\\make-fetch-happen\\\\node_modules\\\\https-proxy-agent\\\\node_modules\\\\agent-base\\\\node_modules\\\\es6-promisify\\\\node_modules\\\\es6-promise\\\\lib\\\\es6-promise\\\\enumerator.js'"), ('C:\\Temp\\123456789012345678901234567890\\nenv\\src\\npm-latest\\node_modules\\npm-profile\\node_modules\\make-fetch-happen\\node_modules\\https-proxy-agent\\node_modules\\agent-base\\node_modules\\es6-promisify\\node_modules\\es6-promise\\lib\\es6-promise\\promise', 'C:/Temp/123456789012345678901234567890/nenv\\Scripts\\node_modules\\npm\\node_modules\\npm-profile\\node_modules\\make-fetch-happen\\node_modules\\https-proxy-agent\\node_modules\\agent-base\\node_modules\\es6-promisify\\node_modules\\es6-promise\\lib\\es6-promise\\promise', "[Error 206] The filename or extension is too long: 'C:/Temp/123456789012345678901234567890/nenv\\\\Scripts\\\\node_modules\\\\npm\\\\node_modules\\\\npm-profile\\\\node_modules\\\\make-fetch-happen\\\\node_modules\\\\https-proxy-agent\\\\node_modules\\\\agent-base\\\\node_modules\\\\es6-promisify\\\\node_modules\\\\es6-promise\\\\lib\\\\es6-promise\\\\promise'"), ('C:\\Temp\\123456789012345678901234567890\\nenv\\src\\npm-latest\\node_modules\\npm-profile\\node_modules\\make-fetch-happen\\node_modules\\socks-proxy-agent\\node_modules\\agent-base\\node_modules\\es6-promisify\\node_modules\\es6-promise\\dist\\es6-promise.auto.min.js', 'C:/Temp/123456789012345678901234567890/nenv\\Scripts\\node_modules\\npm\\node_modules\\npm-profile\\node_modules\\make-fetch-happen\\node_modules\\socks-proxy-agent\\node_modules\\agent-base\\node_modules\\es6-promisify\\node_modules\\es6-promise\\dist\\es6-promise.auto.min.js', "[Errno 2] No such file or directory: 'C:/Temp/123456789012345678901234567890/nenv\\\\Scripts\\\\node_modules\\\\npm\\\\node_modules\\\\npm-profile\\\\node_modules\\\\make-fetch-happen\\\\node_modules\\\\socks-proxy-agent\\\\node_modules\\\\agent-base\\\\node_modules\\\\es6-promisify\\\\node_modules\\\\es6-promise\\\\dist\\\\es6-promise.auto.min.js'"), ('C:\\Temp\\123456789012345678901234567890\\nenv\\src\\npm-latest\\node_modules\\npm-profile\\node_modules\\make-fetch-happen\\node_modules\\socks-proxy-agent\\node_modules\\agent-base\\node_modules\\es6-promisify\\node_modules\\es6-promise\\dist\\es6-promise.auto.min.map', 'C:/Temp/123456789012345678901234567890/nenv\\Scripts\\node_modules\\npm\\node_modules\\npm-profile\\node_modules\\make-fetch-happen\\node_modules\\socks-proxy-agent\\node_modules\\agent-base\\node_modules\\es6-promisify\\node_modules\\es6-promise\\dist\\es6-promise.auto.min.map', "[Errno 2] No such file or directory: 'C:/Temp/123456789012345678901234567890/nenv\\\\Scripts\\\\node_modules\\\\npm\\\\node_modules\\\\npm-profile\\\\node_modules\\\\make-fetch-happen\\\\node_modules\\\\socks-proxy-agent\\\\node_modules\\\\agent-base\\\\node_modules\\\\es6-promisify\\\\node_modules\\\\es6-promise\\\\dist\\\\es6-promise.auto.min.map'"), ('C:\\Temp\\123456789012345678901234567890\\nenv\\src\\npm-latest\\node_modules\\npm-profile\\node_modules\\make-fetch-happen\\node_modules\\socks-proxy-agent\\node_modules\\agent-base\\node_modules\\es6-promisify\\node_modules\\es6-promise\\lib\\es6-promise\\-internal.js', 'C:/Temp/123456789012345678901234567890/nenv\\Scripts\\node_modules\\npm\\node_modules\\npm-profile\\node_modules\\make-fetch-happen\\node_modules\\socks-proxy-agent\\node_modules\\agent-base\\node_modules\\es6-promisify\\node_modules\\es6-promise\\lib\\es6-promise\\-internal.js', "[Errno 2] No such file or directory: 'C:/Temp/123456789012345678901234567890/nenv\\\\Scripts\\\\node_modules\\\\npm\\\\node_modules\\\\npm-profile\\\\node_modules\\\\make-fetch-happen\\\\node_modules\\\\socks-proxy-agent\\\\node_modules\\\\agent-base\\\\node_modules\\\\es6-promisify\\\\node_modules\\\\es6-promise\\\\lib\\\\es6-promise\\\\-internal.js'"), ('C:\\Temp\\123456789012345678901234567890\\nenv\\src\\npm-latest\\node_modules\\npm-profile\\node_modules\\make-fetch-happen\\node_modules\\socks-proxy-agent\\node_modules\\agent-base\\node_modules\\es6-promisify\\node_modules\\es6-promise\\lib\\es6-promise\\enumerator.js', 'C:/Temp/123456789012345678901234567890/nenv\\Scripts\\node_modules\\npm\\node_modules\\npm-profile\\node_modules\\make-fetch-happen\\node_modules\\socks-proxy-agent\\node_modules\\agent-base\\node_modules\\es6-promisify\\node_modules\\es6-promise\\lib\\es6-promise\\enumerator.js', "[Errno 2] No such file or directory: 'C:/Temp/123456789012345678901234567890/nenv\\\\Scripts\\\\node_modules\\\\npm\\\\node_modules\\\\npm-profile\\\\node_modules\\\\make-fetch-happen\\\\node_modules\\\\socks-proxy-agent\\\\node_modules\\\\agent-base\\\\node_modules\\\\es6-promisify\\\\node_modules\\\\es6-promise\\\\lib\\\\es6-promise\\\\enumerator.js'"), ('C:\\Temp\\123456789012345678901234567890\\nenv\\src\\npm-latest\\node_modules\\npm-profile\\node_modules\\make-fetch-happen\\node_modules\\socks-proxy-agent\\node_modules\\agent-base\\node_modules\\es6-promisify\\node_modules\\es6-promise\\lib\\es6-promise\\promise', 'C:/Temp/123456789012345678901234567890/nenv\\Scripts\\node_modules\\npm\\node_modules\\npm-profile\\node_modules\\make-fetch-happen\\node_modules\\socks-proxy-agent\\node_modules\\agent-base\\node_modules\\es6-promisify\\node_modules\\es6-promise\\lib\\es6-promise\\promise', "[Error 206] The filename or extension is too long: 'C:/Temp/123456789012345678901234567890/nenv\\\\Scripts\\\\node_modules\\\\npm\\\\node_modules\\\\npm-profile\\\\node_modules\\\\make-fetch-happen\\\\node_modules\\\\socks-proxy-agent\\\\node_modules\\\\agent-base\\\\node_modules\\\\es6-promisify\\\\node_modules\\\\es6-promise\\\\lib\\\\es6-promise\\\\promise'"), ('C:\\Temp\\123456789012345678901234567890\\nenv\\src\\npm-latest\\node_modules\\pacote\\node_modules\\make-fetch-happen\\node_modules\\http-proxy-agent\\node_modules\\agent-base\\node_modules\\es6-promisify\\node_modules\\es6-promise\\lib\\es6-promise\\promise', 'C:/Temp/123456789012345678901234567890/nenv\\Scripts\\node_modules\\npm\\node_modules\\pacote\\node_modules\\make-fetch-happen\\node_modules\\http-proxy-agent\\node_modules\\agent-base\\node_modules\\es6-promisify\\node_modules\\es6-promise\\lib\\es6-promise\\promise', "[Error 206] The filename or extension is too long: 'C:/Temp/123456789012345678901234567890/nenv\\\\Scripts\\\\node_modules\\\\npm\\\\node_modules\\\\pacote\\\\node_modules\\\\make-fetch-happen\\\\node_modules\\\\http-proxy-agent\\\\node_modules\\\\agent-base\\\\node_modules\\\\es6-promisify\\\\node_modules\\\\es6-promise\\\\lib\\\\es6-promise\\\\promise'"), ('C:\\Temp\\123456789012345678901234567890\\nenv\\src\\npm-latest\\node_modules\\pacote\\node_modules\\make-fetch-happen\\node_modules\\https-proxy-agent\\node_modules\\agent-base\\node_modules\\es6-promisify\\node_modules\\es6-promise\\lib\\es6-promise\\promise', 'C:/Temp/123456789012345678901234567890/nenv\\Scripts\\node_modules\\npm\\node_modules\\pacote\\node_modules\\make-fetch-happen\\node_modules\\https-proxy-agent\\node_modules\\agent-base\\node_modules\\es6-promisify\\node_modules\\es6-promise\\lib\\es6-promise\\promise', "[Error 206] The filename or extension is too long: 'C:/Temp/123456789012345678901234567890/nenv\\\\Scripts\\\\node_modules\\\\npm\\\\node_modules\\\\pacote\\\\node_modules\\\\make-fetch-happen\\\\node_modules\\\\https-proxy-agent\\\\node_modules\\\\agent-base\\\\node_modules\\\\es6-promisify\\\\node_modules\\\\es6-promise\\\\lib\\\\es6-promise\\\\promise'"), ('C:\\Temp\\123456789012345678901234567890\\nenv\\src\\npm-latest\\node_modules\\pacote\\node_modules\\make-fetch-happen\\node_modules\\socks-proxy-agent\\node_modules\\agent-base\\node_modules\\es6-promisify\\node_modules\\es6-promise\\lib\\es6-promise\\promise', 'C:/Temp/123456789012345678901234567890/nenv\\Scripts\\node_modules\\npm\\node_modules\\pacote\\node_modules\\make-fetch-happen\\node_modules\\socks-proxy-agent\\node_modules\\agent-base\\node_modules\\es6-promisify\\node_modules\\es6-promise\\lib\\es6-promise\\promise', "[Error 206] The filename or extension is too long: 'C:/Temp/123456789012345678901234567890/nenv\\\\Scripts\\\\node_modules\\\\npm\\\\node_modules\\\\pacote\\\\node_modules\\\\make-fetch-happen\\\\node_modules\\\\socks-proxy-agent\\\\node_modules\\\\agent-base\\\\node_modules\\\\es6-promisify\\\\node_modules\\\\es6-promise\\\\lib\\\\es6-promise\\\\promise'")]
```

**Comment by splatteredbits** [comment]
I'm also experiencing this issue trying to install NPM 5.5.1 with NVM for Windows.

**Comment by dchitwood3** [comment]
I'm currently working with node.js 8.9.4 which ships with npm 5.6.0. The node_modules directory has 4952 files, 1070 folders & directory path depth of 183 characters (w/o considers where it's installed). The directory path depth is impact my company's use of node.js w/ npm.

I thought npm had worked to make this directory depth "flatter" in the past.

I'm assuming this problem is caused by the package dependencies which appear to be out of control. There are many duplicate packages for different version contributing to the directory path.
