### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by dskumarxd** [npm/npm#18973]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ yes] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
getting error while trying to install npm 

859 verbose stack Error: Invalid name: "@angular/http"
859 verbose stack     at ensureValidName (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\node_modules\normalize-package-data\lib\fixer.js:297:15)
859 verbose stack     at Object.fixNameField (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\node_modules\normalize-package-data\lib\fixer.js:201:5)
859 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\node_modules\normalize-package-data\lib\normalize.js:29:38
859 verbose stack     at Array.forEach (native)
859 verbose stack     at normalize (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\node_modules\normalize-package-data\lib\normalize.js:28:15)
859 verbose stack     at final (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:349:5)
859 verbose stack     at then (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:124:5)
859 verbose stack     at ReadFileContext.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:295:20)
859 verbose stack     at ReadFileContext.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16)
859 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:367:13)
860 verbose cwd C:\Users\sdhanakonda\Documents\Visual Studio 2015\Projects\Angular\Angular
861 error Windows_NT 10.0.10586
862 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
863 error node v6.11.5
864 error npm  v3.10.10
865 error Invalid name: "@angular/http"
866 error If you need help, you may report this error at:
866 error     <https://github.com/npm/npm/issues>

### supporting information:

 - `npm -v` prints: 3.10.10
 - `node -v` prints: v6.11.5
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: windows

**Comment by kenany** [comment]
Does `C:\Users\sdhanakonda\Documents\Visual Studio 2015\Projects\Angular\Angular\package.json` have an empty `"name"` field?
