### ISSUE TITLE
Error "npm run dev" with laravel-mix

### ISSUE THREAD

**Issue by mccarlosen** [npm/npm#18996]
#### I'm opening this issue because:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/home/osendev/.npm_packages/bin/npm',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@4.3.0
3 info using node@v7.6.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle @~predev: @
6 silly lifecycle @~predev: no script for predev, continuing
7 info lifecycle @~dev: @
8 verbose lifecycle @~dev: unsafe-perm in lifecycle true
9 verbose lifecycle @~dev: PATH: /home/osendev/.npm_packages/lib/node_modules/npm/bin/node-gyp-bin:/var/www/html/institut_siip/node_modules/.bin:/home/osendev/.npm_packages/bin:/usr/games:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:~/.composer/vendor/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/home/osendev/Android/Sdk/platform-tools:/home/osendev/Android/Sdk/tools:/home/osendev/Android/Sdk/tools:/home/osendev/Android/Sdk/platform-tools:/usr/local/android-studio/gradle/gradle-3.2/bin
10 verbose lifecycle @~dev: CWD: /var/www/html/institut_siip
11 silly lifecycle @~dev: Args: [ '-c', 'npm run development' ]
12 silly lifecycle @~dev: Returned: code: 1  signal: null
13 info lifecycle @~dev: Failed to exec dev script
14 verbose stack Error: @ dev: `npm run development`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/home/osendev/.npm_packages/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:192:7)
14 verbose stack     at ChildProcess.<anonymous> (/home/osendev/.npm_packages/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:192:7)
14 verbose stack     at maybeClose (internal/child_process.js:890:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid @
16 verbose cwd /var/www/html/institut_siip
17 error Linux 4.4.0-98-generic
18 error argv "/usr/local/bin/node" "/home/osendev/.npm_packages/bin/npm" "run" "dev"
19 error node v7.6.0
20 error npm  v4.3.0
21 error code ELIFECYCLE
22 error errno 1
23 error @ dev: `npm run development`
23 error Exit status 1
24 error Failed at the @ dev script 'npm run development'.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the  package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     npm run development
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls
24 error There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

**Comment by kenany** [comment]
Seems like `npm run development` is returning an error code. All `npm` is doing here is catching that, and letting you know about it. What happens when you just run `npm run development` from your command-line?

**Comment by kenany** [comment]
Closing due to lack of response.
