### ISSUE TITLE
Error 404 when trying to install package in Windows 10 (works in Ubuntu)

### ISSUE THREAD

**Issue by laurent22** [npm/npm#19002]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [X] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I'm trying to install a package (`joplin`) on Windows 10 but it seems npm cannot fetch some data, I'm seeing this error in the log:

     10 http fetch GET 404 https://registry.npmjs.org/- 448ms

The package installs fine in Ubuntu.

#### How can the CLI team reproduce the problem?

Run `npm -i g joplin`

It will fail and the error log will be:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Laurent\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'i',
1 verbose cli   '-',
1 verbose cli   'joplin' ]
2 info using npm@5.5.1
3 info using node@v8.8.1
4 verbose config Skipping project config: C:\Users\Laurent/.npmrc. (matches userconfig)
5 verbose npm-session 36726f72411c8ea2
6 silly install loadCurrentTree
7 silly install readLocalPackageData
8 http fetch GET 304 https://registry.npmjs.org/joplin 239ms (from cache)
9 silly pacote tag manifest for joplin@latest fetched in 245ms
10 http fetch GET 404 https://registry.npmjs.org/- 448ms
11 silly fetchPackageMetaData error for -@latest 404 Not Found: -@latest
12 verbose stack Error: 404 Not Found: -@latest
12 verbose stack     at fetch.then.res (C:\Users\Laurent\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\lib\fetchers\registry\fetch.js:42:19)
12 verbose stack     at tryCatcher (C:\Users\Laurent\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
12 verbose stack     at Promise._settlePromiseFromHandler (C:\Users\Laurent\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
12 verbose stack     at Promise._settlePromise (C:\Users\Laurent\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
12 verbose stack     at Promise._settlePromise0 (C:\Users\Laurent\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
12 verbose stack     at Promise._settlePromises (C:\Users\Laurent\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
12 verbose stack     at Async._drainQueue (C:\Users\Laurent\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
12 verbose stack     at Async._drainQueues (C:\Users\Laurent\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
12 verbose stack     at Immediate.Async.drainQueues (C:\Users\Laurent\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
12 verbose stack     at runCallback (timers.js:785:20)
12 verbose stack     at tryOnImmediate (timers.js:747:5)
12 verbose stack     at processImmediate [as _immediateCallback] (timers.js:718:5)
13 verbose cwd C:\Users\Laurent
14 verbose Windows_NT 10.0.16299
15 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Laurent\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "i" "-" "joplin"
16 verbose node v8.8.1
17 verbose npm  v5.5.1
18 error code E404
19 error 404 Not Found: -@latest
20 verbose exit [ 1, true ]
```

### supporting information:

 - `npm -v` prints: 5.5.1 
 - `node -v` prints: 8.8.1
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows 10
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by leonadler** [comment]
You mention you are using `npm -i g joplin`, but the log mentions `npm i - joplin`.
Either the log is wrong or you have mistyped the command.

Instead of `-i`, you mean `i` or `install`:

* `npm install joplin` works
* `npm i joplin` works
* `npm -i joplin` does not work
* `npm i - joplin` does not work

Please retry with `npm i joplin`.
