### ISSUE TITLE
SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by ghost** [npm/npm#19009]
Error: Missing binding /Users/kb/Google Drive/LipstickAfrica/app/public/wp-content/dev/node_modules/node-sass/vendor/darwin-x64-14/binding.node
Node Sass could not find a binding for your current environment: OS X 64-bit with Node 0.12.x

Found bindings for the following environments:
  - OS X 64-bit with Node.js 8.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass --force` to build the binding for your current environment.
    at module.exports (/Users/kb/Google Drive/LipstickAfrica/app/public/wp-content/dev/node_modules/node-sass/lib/binding.js:15:13)
    at Object.<anonymous> (/Users/kb/Google Drive/LipstickAfrica/app/public/wp-content/dev/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/kb/Google Drive/LipstickAfrica/app/public/wp-content/dev/node_modules/gulp-sass/index.js:187:21)
    at Module._compile (module.js:460:26)
kb:dev kb$ npm rebuild node-sass --force
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/node_modules/cryptiles/node_modules/boom/lib/index.js:5
const Hoek = require('hoek');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/node_modules/cryptiles/lib/index.js:4:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
npm ERR! Darwin 17.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "rebuild" "node-sass" "--force"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! /usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/node_modules/cryptiles/node_modules/boom/lib/index.js:5
npm ERR! const Hoek = require('hoek');
npm ERR! ^^^^^
npm ERR! Use of const in strict mode.
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by kenany** [comment]
Node.js v0.12 is years old and is no longer supported.
