### ISSUE TITLE
npm ERR! Invalid Version: 0.0.1alpha1

### ISSUE THREAD

**Issue by littlelittlemoon** [npm/npm#19023]
#### I'm opening this issue because:

  - [ ] npm is producing an incorrect install.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

```
(/Users/romens1/.nvm/versions/node/v6.6.0/lib/node_modules/npm/node_modules/semver/semver.js:293:11)
37693 verbose stack     at SemVer.compare (/Users/romens1/.nvm/versions/node/v6.6.0/lib/node_modules/npm/node_modules/semver/semver.js:342:13)
37693 verbose stack     at compare (/Users/romens1/.nvm/versions/node/v6.6.0/lib/node_modules/npm/node_modules/semver/semver.js:566:31)
37693 verbose stack     at rcompare (/Users/romens1/.nvm/versions/node/v6.6.0/lib/node_modules/npm/node_modules/semver/semver.js:576:10)
37693 verbose stack     at Array.sort (native)
37693 verbose stack     at pickVersionFromRegistryDocument (/Users/romens1/.nvm/versions/node/v6.6.0/lib/node_modules/npm/lib/fetch-package-metadata.js:125:48)
37693 verbose stack     at /Users/romens1/.nvm/versions/node/v6.6.0/lib/node_modules/npm/node_modules/iferr/index.js:13:50
37693 verbose stack     at /Users/romens1/.nvm/versions/node/v6.6.0/lib/node_modules/npm/lib/utils/pulse-till-done.js:20:8
37693 verbose stack     at saved (/Users/romens1/.nvm/versions/node/v6.6.0/lib/node_modules/npm/lib/cache/caching-client.js:174:7)
37693 verbose stack     at /Users/romens1/.nvm/versions/node/v6.6.0/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:210:7
37694 verbose cwd /Users/romens1/tankaiyue/project/scc-b2b
37695 error Darwin 15.6.0
37696 error argv "/Users/romens1/.nvm/versions/node/v6.6.0/bin/node" "/Users/romens1/.nvm/versions/node/v6.6.0/bin/npm" "install"
37697 error node v6.6.0
37698 error npm  v3.10.3
37699 error Invalid Version: 0.0.1alpha1
37700 error If you need help, you may report this error at:
37700 error     <https://github.com/npm/npm/issues>
37701 verbose exit [ 1, true ]
 ```

### supporting information:

 - `npm -v` prints:
v3.10.3
 - `node -v` prints:
v6.6.0
 - Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
 - Container:
   - [ ] I develop / deploy using Docker.

**Comment by kenany** [comment]
Would it be possibly to see your `package.json`? Feel free to remove any sensitive bits. Also, please take the time to fill out the entire support form. Thanks!

**Comment by littlelittlemoon** [comment]
Thanks so much, I have solved this problem when I upgrade the npm version.

**Comment by kenany** [comment]
Closing as resolved then.
