### ISSUE TITLE
"Cannot find module semver"

### ISSUE THREAD

**Issue by quantumproducer** [npm/npm#19036]
I tried uninstalling + reinstalling npm and node via homebrew.

#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [X] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

~/npm install
module.js:538
    throw err;
    ^

Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/unsupported.js:2:14)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)

### supporting information:

 - `npm -v` prints: ^ the above error
 - `node -v` prints: v8.9.0
 - `npm config get registry` prints: ^the above error 
 - Windows, OS X/macOS, or Linux?: OSX

**Comment by povesteam** [comment]
Same problem here.

Resolved on my side by using `yarn` instead of `npm` 🙄
