### ISSUE TITLE
npm install [-g] shelljs

### ISSUE THREAD

**Issue by Suraj59** [npm/npm#19040]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ *] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - 
![screenshot from 2017-11-02 15-57-15](https://user-images.githubusercontent.com/11031352/32321244-87e10c5a-bfe6-11e7-8626-7838bf38aaf7.png)

npm install [-g] shelljs
Unhandled rejection Error: Invalid tag name "[-g]": Tags may not have any characters that encodeURIComponent encodes.
    at invalidTagName (/usr/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:76:15)
    at fromRegistry (/usr/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:265:13)
    at resolve (/usr/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:66:12)
    at npa (/usr/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:39:10)
    at /usr/lib/node_modules/npm/lib/install/deps.js:200:16
    at /usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
    at Array.forEach (native)
    at /usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
    at Array.forEach (native)
    at asyncMap (/usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
    at exports.getAllMetadata (/usr/lib/node_modules/npm/lib/install/deps.js:199:3)
    at Installer.loadArgMetadata (/usr/lib/node_modules/npm/lib/install.js:325:3)
    at /usr/lib/node_modules/npm/lib/install.js:656:16
    at BB.join.then (/usr/lib/node_modules/npm/lib/install/read-shrinkwrap.js:41:16)
    at tryCatcher (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by kenany** [comment]
I think what you want to run is?:

```
npm install -g shelljs
```

or

```
npm install shelljs
```
