### ISSUE TITLE
Could not install npm dependencies for test-packages: Command failed

### ISSUE THREAD

**Issue by blackslate** [npm/npm#19071]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

$ meteor update
This project is already at Meteor 1.6, the latest release.
Your top-level dependencies are at their latest compatible versions.

$ meteor create .
/home/blackslate/.meteor/packages/meteor-tool/.1.6.0.osbd2w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:218
      throw error;
      ^

Error: Error: Could not install npm dependencies for test-packages: Command failed: /home/blackslate/.meteor/packages/meteor-tool/.1.6.0.osbd2w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm install
Unhandled rejection Error: EACCES: permission denied, mkdir '/home/blackslate/.npm/_cacache'
Unhandled rejection Error: EACCES: permission denied, mkdir '/home/blackslate/.npm/_cacache'
npm ERR! cb() never called!

npm ERR! **This is an error with npm itself**. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
Unhandled rejection Error: EACCES: permission denied, mkdir '/home/blackslate/.npm/_cacache'
Unhandled rejection Error: EACCES: permission denied, mkdir '/home/blackslate/.npm/_cacache'
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

    at Object.error (/tools/utils/buildmessage.js:430:11)
    at /tools/cli/default-npm-deps.js:32:20
    at /tools/utils/buildmessage.js:334:18
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:333:36
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at Object.install (/tools/cli/default-npm-deps.js:27:27)
    at Command.func (/tools/cli/commands.js:799:36)
    at /tools/cli/main.js:1522:15

### supporting information:

 - `npm -v` prints: 2.15.11
 - `node -v` prints: v4.8.5
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Ubuntu 16.04.3
 - Network issues:
   - Geographic location where npm was run: France
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by ayoub1996-01** [comment]
hello everyone !
i have the same error in my linux mint, i have fix it by fixing the git  ...
when i was trying  this commande ligne " meteor npm install " it said 

npm ERR! No git binary found in $PATH
npm ERR! 
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.

so with this 3 steps i have fix the promblem and i have create my funny project with out error :

## _1__`npm install --save npm-git-install`

## _2__## In your pacakge.json 
add: 
{
  "scripts": {
    "install": "npm-git install"
  }
  "gitDependencies": {
    "private-package-name": "git@private.git.server:user/repo.git#revision",
    "public-package-name": "https://github.com/user/repo.git#revision"
  }
}

Obviously replace *-package-name and git URLs with values relevant to your project. URLs has to be in canonical form (i.e. one that you would provide to git clone on command line) - no fancy NPM shortcuts like user/repo or bitbucket:user/repo. If you want this, we are open for a PRs.

## _3__Then install your dependencies as usual:

 `npm install`

for more details visit this link : https://www.npmjs.com/package/npm-git-install
 
if anyone knows the relation between the git and my error explain me plz , because i don't know the git's effect on my project creation ...

**Comment by vrutant** [comment]
I am facing similar issue on Windows7, while running _**meteor create apollo**_ from cmd, error is as below:
C:\Users\vrsh0217\AppData\Local\.meteor\packages\meteor-tool\1.6.1_1\mt-os.windows.x86_64\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:218
      throw error;
      ^

**Error: Error: Could not install npm dependencies for test-packages: Command failed: C:\Windows\system32\cmd.exe /c C:\Users\vrsh0217\AppData\Local\.meteor\packages\meteor-tool\1.6.1_1\mt-os.windows.x86_64\dev_bundle\bin\npm.cmd install
npm ERR! code ENOGIT**
npm ERR! No git binary found in $PATH
npm ERR!
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\vrsh0217\AppData\Roaming\npm-cache\_logs\2018-04-23T12_42_40_824Z-debug.log
npm ERR! code ENOGIT
npm ERR! No git binary found in $PATH
npm ERR!
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\vrsh0217\AppData\Roaming\npm-cache\_logs\2018-04-23T12_42_40_824Z-debug.log

    at Object.error (C:\tools\utils\buildmessage.js:430:11)
    at C:\tools\cli\default-npm-deps.js:36:20
    at C:\tools\utils\buildmessage.js:334:18
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:333:36
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at Object.install (C:\tools\cli\default-npm-deps.js:27:27)
    at Command.func (C:\tools\cli\commands.js:801:36)
    at C:\tools\cli\main.js:1523:15
![image](https://user-images.githubusercontent.com/7123755/39127392-814a84d4-4722-11e8-8427-ab7c3f76cbcd.png)

**Comment by tylern06** [comment]
I had the same problem as you. It worked for me after I downloaded and installed git here -  https://git-scm.com/download/win
