### ISSUE TITLE
React Native install error

### ISSUE THREAD

**Issue by jdoper** [npm/npm#19089]
```
20250 verbose stack Error: Error extracting /home/sorriso/.npm/jest-expo/22.0.0/package.tgz archive: ENOENT: no such file or directory, open '/home/sorriso/.npm/jest-expo/22.0.0/package.tgz'
20250 verbose stack     at ReadStream.<anonymous> (/usr/share/npm/lib/fetch-package-metadata.js:286:10)
20250 verbose stack     at emitOne (events.js:96:13)
20250 verbose stack     at ReadStream.emit (events.js:188:7)
20250 verbose stack     at /usr/share/npm/node_modules/graceful-fs/graceful-fs.js:179:14
20250 verbose stack     at /usr/share/npm/node_modules/graceful-fs/graceful-fs.js:230:16
20250 verbose stack     at FSReqWrap.oncomplete (fs.js:123:15)
20251 verbose cwd /home/sorriso/Documentos/git/AwesomeProject
20252 error Linux 4.13.0-16-generic
20253 error argv "/usr/bin/node" "/usr/bin/npm" "install" "--save"
20254 error node v6.11.4
20255 error npm  v3.5.2
20256 error code EREADFILE
20257 error Error extracting /home/sorriso/.npm/jest-expo/22.0.0/package.tgz archive: ENOENT: no such file or directory, open '/home/sorriso/.npm/jest-expo/22.0.0/package.tgz'
```

**Comment by Butterfly** [comment]
Can you actually find that `/home/sorriso/.npm/jest-expo/22.0.0/package.tgz` location? `npm` is saying it doesn't exist. That `ENOENT` part can stand for something like "error no entry" and/or "error no entity".

If you can't find that package hierarchy, specifically the `/home/sorriso/.npm/jest-expo` part of it for starters, you'll need to find out why `npm` thinks that should be found in that spot in your directories.

**Comment by arju88nair** [comment]
I am also facing the same issue here. Any workabouts?

**Comment by whocen** [comment]
Note the "../22.0.0/.." while running npm install but its actually "../22.0.1/.." when you navigate to that location. Maybe change 22.0.0 back to 22.0.1 in the package.json then run npm install again it should work but, do it at your own risk, update on result please.

BTW "expo is at 22.0.2"
