### ISSUE TITLE
npm  error on executing @angular/cli

### ISSUE THREAD

**Issue by arunnmkl** [npm/npm#19085]
#### I'm opening this issue because:

  - [x] npm not installing angular/cli.

#### What's going wrong?

While executing 'npm install -g @angular/cli' command I'm getting the following error,

2506 verbose stack Error: shasum check failed for C:\Users\user\AppData\Local\Temp\npm-8508-fa24f526\registry.npmjs.org\typescript\-\typescript-2.6.1.tgz
2506 verbose stack Expected: ef39cdea27abac0b500242d6726ab90e0c846631
2506 verbose stack Actual:   c6a782bad1539fd3c9b2ec3e226e4f8fccb3bdf3
2506 verbose stack From:     https://registry.npmjs.org/typescript/-/typescript-2.6.1.tgz
2506 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\sha\index.js:25:8
2506 verbose stack     at ReadStream.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\sha\index.js:72:7)
2506 verbose stack     at emitNone (events.js:91:20)
2506 verbose stack     at ReadStream.emit (events.js:185:7)
2506 verbose stack     at endReadableNT (_stream_readable.js:974:12)
2506 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:74:11)
2506 verbose stack     at process._tickCallback (internal/process/next_tick.js:98:9)
2507 verbose cwd c:\Users\arun.kumar
2508 error Windows_NT 6.3.9600
2509 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@angular/cli"
2510 error node v6.9.1
2511 error npm  v3.10.8
2512 error shasum check failed for C:\Users\user\AppData\Local\Temp\npm-8508-fa24f526\registry.npmjs.org\typescript\-\typescript-2.6.1.tgz
2512 error Expected: ef39cdea27abac0b500242d6726ab90e0c846631
2512 error Actual:   c6a782bad1539fd3c9b2ec3e226e4f8fccb3bdf3
2512 error From:     https://registry.npmjs.org/typescript/-/typescript-2.6.1.tgz

**Comment by Butterfly** [comment]
Issue #19087 received similar. Posting in case it helps diagnose your issue:

> npm ERR! code EINTEGRITY
npm ERR! sha1-mLMWW+jVkkccsMqt3iwNH4MvEz4= integrity checksum failed when using
sha1: wanted sha1-mLMWW+jVkkccsMqt3iwNH4MvEz4= but got sha1-InFCBYTpWFahYj1qLB3j
kKJh7fc=. (2341 bytes)

Most important to me was that this was suggested at the bottom of their feedback:

> npm ERR! Please try running this command again as root/Administrator.

I started to add a disclaimer that these two issues could easily be unrelated, but they still might be because yours says this:

> 2512 error shasum check failed for C:\Users\user\AppData\Local\Temp\npm-8508-fa24f526\registry.npmjs.org\typescript-\typescript-2.6.1.tgz
2512 error Expected: ef39cdea27abac0b500242d6726ab90e0c846631
2512 error Actual: c6a782bad1539fd3c9b2ec3e226e4f8fccb3bdf3
