### ISSUE TITLE
i dont know what to do 

### ISSUE THREAD

**Issue by tahmi123** [npm/npm#19081]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   'binary-charts',
1 verbose cli   '--save' ]
2 info using npm@3.5.2
3 info using node@v4.2.6
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData binary-charts
8 silly fetchNamedPackageData binary-charts
9 silly mapToRegistry name binary-charts
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry uri https://registry.npmjs.org/binary-charts
13 verbose request uri https://registry.npmjs.org/binary-charts
14 verbose request no auth needed
15 info attempt registry request try #1 at 11:45:35 AM
16 verbose request id e68082ee18151012
17 verbose etag W/"59ed8ff2-15119d"
18 verbose lastModified Mon, 23 Oct 2017 06:45:06 GMT
19 http request GET https://registry.npmjs.org/binary-charts
20 http 304 https://registry.npmjs.org/binary-charts
21 verbose headers { date: 'Tue, 07 Nov 2017 10:45:36 GMT',
21 verbose headers   via: '1.1 varnish',
21 verbose headers   'cache-control': 'max-age=300',
21 verbose headers   etag: 'W/"59ed8ff2-15119d"',
21 verbose headers   age: '57',
21 verbose headers   connection: 'keep-alive',
21 verbose headers   'x-served-by': 'cache-lcy19228-LCY',
21 verbose headers   'x-cache': 'HIT',
21 verbose headers   'x-cache-hits': '1',
21 verbose headers   'x-timer': 'S1510051537.957714,VS0,VE1',
21 verbose headers   vary: 'Accept-Encoding, Accept' }
22 silly get cb [ 304,
22 silly get   { date: 'Tue, 07 Nov 2017 10:45:36 GMT',
22 silly get     via: '1.1 varnish',
22 silly get     'cache-control': 'max-age=300',
22 silly get     etag: 'W/"59ed8ff2-15119d"',
22 silly get     age: '57',
22 silly get     connection: 'keep-alive',
22 silly get     'x-served-by': 'cache-lcy19228-LCY',
22 silly get     'x-cache': 'HIT',
22 silly get     'x-cache-hits': '1',
22 silly get     'x-timer': 'S1510051537.957714,VS0,VE1',
22 silly get     vary: 'Accept-Encoding, Accept' } ]
23 verbose etag https://registry.npmjs.org/binary-charts from cache
24 verbose get saving binary-charts to /home/tahmi/.npm/registry.npmjs.org/binary-charts/.cache.json
25 silly install normalizeTree
26 silly loadCurrentTree Finishing
27 silly loadIdealTree Starting
28 silly install loadIdealTree
29 silly cloneCurrentTree Starting
30 silly install cloneCurrentTreeToIdealTree
31 silly cloneCurrentTree Finishing
32 silly loadShrinkwrap Starting
33 silly install loadShrinkwrap
34 silly loadShrinkwrap Finishing
35 silly loadAllDepsIntoIdealTree Starting
36 silly install loadAllDepsIntoIdealTree
37 silly rollbackFailedOptional Starting
38 silly rollbackFailedOptional Finishing
39 silly runTopLevelLifecycles Starting
40 silly runTopLevelLifecycles Finishing
41 silly install printInstalled
42 verbose stack Error: Refusing to install binary-charts as a dependency of itself
42 verbose stack     at checkSelf (/usr/share/npm/lib/install/validate-args.js:40:14)
42 verbose stack     at Array.<anonymous> (/usr/share/npm/node_modules/slide/lib/bind-actor.js:15:8)
42 verbose stack     at LOOP (/usr/share/npm/node_modules/slide/lib/chain.js:15:14)
42 verbose stack     at chain (/usr/share/npm/node_modules/slide/lib/chain.js:20:5)
42 verbose stack     at /usr/share/npm/lib/install/validate-args.js:15:5
42 verbose stack     at /usr/share/npm/node_modules/slide/lib/async-map.js:52:35
42 verbose stack     at Array.forEach (native)
42 verbose stack     at /usr/share/npm/node_modules/slide/lib/async-map.js:52:11
42 verbose stack     at Array.forEach (native)
42 verbose stack     at asyncMap (/usr/share/npm/node_modules/slide/lib/async-map.js:51:8)
43 verbose cwd /home/tahmi/Downloads/binary-charts-master
44 error Linux 4.10.0-28-generic
45 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "binary-charts" "--save"
46 error node v4.2.6
47 error npm  v3.5.2
48 error code ENOSELF
49 error Refusing to install binary-charts as a dependency of itself
50 error If you need help, you may report this error at:
50 error     <https://github.com/npm/npm/issues>
51 verbose exit [ 1, true ]

**Comment by marudhupandiyang** [comment]
What is the `name` in your `package.json` ??

**Comment by tahmi123** [comment]
"name": "binary-charts"

**Comment by Butterfly** [comment]
@tahmi123 Try changing that "name" to something else that you'll still remember easily. For example, add something like "project" or "draft" or even something like your "123" there to that name. Disclaimer is I've never done that part so I don't know if anything else needs changed besides a directory (folder) or related. Changing that name slightly is what Line 42, "Refusing to install binary-charts as a dependency of itself", is saying.

**Comment by marudhupandiyang** [comment]
@tahmi123, The name you use should not be the same as any of the dependencies you use. There is already a package named `binary-charts` and one should not use the same for the project. Use a different name in your `package.json` would solve this.

Also, please raise the future issues like this on sites like `stackoverflow` and if you confirm its an issue with `npm` itself, then raise an issue on `github`. That would help maintainers to look into valid issues and spend time on them.
