### ISSUE TITLE
npm i -g create-react-app > Missing package name

### ISSUE THREAD

**Issue by barbalex** [npm/npm#19086]
#### I'm opening this issue because:

  - [x] npm is producing an incorrect install.

#### What's going wrong?

Using npm v4.6.1:
```bash
npm i -g create-react-app
npm ERR! addLocal Could not install C:\Users\alex\create-react-app
npm ERR! No name provided in package.json
```

Using npm v5.5.1:
```bash
npm i -g create-react-app
npm ERR! Can't install C:\Users\alex\create-react-app: Missing package name
```

Any other module installs perfectly o.k. globally.

#### How can the CLI team reproduce the problem?

No idea :-(

### supporting information:

 - `npm -v` prints: 4.6.1 / 5.5.1
 - `node -v` prints: 8.9.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows 10
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

This is the log:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\alex\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'create-react-app' ]
2 info using npm@5.5.1
3 info using node@v8.9.0
4 verbose npm-session cdb59e727f0b9fc4
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 info lifecycle @~prepack: @
8 info lifecycle @~postpack: @
9 silly pacote directory manifest for undefined@file:create-react-app fetched in 93ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 silly install loadShrinkwrap
13 silly install loadAllDepsIntoIdealTree
14 verbose stack Error: Can't install C:\Users\alex\create-react-app: Missing package name
14 verbose stack     at hasMinimumFields (C:\Users\alex\AppData\Roaming\npm\node_modules\npm\lib\install\validate-args.js:26:15)
14 verbose stack     at Array.<anonymous> (C:\Users\alex\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
14 verbose stack     at LOOP (C:\Users\alex\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
14 verbose stack     at chain (C:\Users\alex\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
14 verbose stack     at C:\Users\alex\AppData\Roaming\npm\node_modules\npm\lib\install\validate-args.js:16:5
14 verbose stack     at C:\Users\alex\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:52:35
14 verbose stack     at Array.forEach (<anonymous>)
14 verbose stack     at C:\Users\alex\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:52:11
14 verbose stack     at Array.forEach (<anonymous>)
14 verbose stack     at asyncMap (C:\Users\alex\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\async-map.js:51:8)
14 verbose stack     at module.exports (C:\Users\alex\AppData\Roaming\npm\node_modules\npm\lib\install\validate-args.js:15:3)
14 verbose stack     at Array.<anonymous> (C:\Users\alex\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
14 verbose stack     at LOOP (C:\Users\alex\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
14 verbose stack     at chain (C:\Users\alex\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
14 verbose stack     at Installer.loadAllDepsIntoIdealTree (C:\Users\alex\AppData\Roaming\npm\node_modules\npm\lib\install.js:450:3)
14 verbose stack     at Array.<anonymous> (C:\Users\alex\AppData\Roaming\npm\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
15 verbose cwd C:\Users\alex
16 verbose Windows_NT 10.0.16299
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\alex\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "create-react-app"
18 verbose node v8.9.0
19 verbose npm  v5.5.1
20 error Can't install C:\Users\alex\create-react-app: Missing package name
21 verbose exit [ 1, true ]
```

**Comment by kenany** [comment]
Is `C:\Users\alex\create-react-app` a directory that exists?

**Comment by barbalex** [comment]
Yesssssssss

...and deleting that solved the problem  :-)

Feel free to close the issue. Though maybe the fact that an existing folder prevents global installation can be regarded as a bug. That's why I am not closing myself.

**Comment by kenany** [comment]
Nah, `npm` sees that the folder (of the same name as what you're trying to install) and assumes that you want to install _it_ locally. Since this is intentional behavior (to allow users to globally install packages which they have locally on their machines) I'm gonna close this.

**Comment by barbalex** [comment]
Thanks, so I learned something
