### ISSUE TITLE
request to https://registry.npmjs.org/bitly failed

### ISSUE THREAD

**Issue by shiyasjxt** [npm/npm#19098]
node version = v8.9.1
npm version = 5.5.1
trying to install >npm install bitly --save
Machine: windows

but throwing error.
log as below:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\SHIYAS\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'bitly',
1 verbose cli   '--save' ]
2 info using npm@5.5.1
3 info using node@v8.9.1
4 verbose npm-session 7ca07852ed359e0f
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData error for bitly@^5.0.11 request to https://registry.npmjs.org/bitly failed, reason: write EPROTO 101057795:error:14077460:SSL routines:SSL23_GET_SERVER_HELLO:reason(1120):openssl\ssl\s23_clnt.c:800:
8 verbose type system
9 verbose stack FetchError: request to https://registry.npmjs.org/bitly failed, reason: write EPROTO 101057795:error:14077460:SSL routines:SSL23_GET_SERVER_HELLO:reason(1120):openssl\ssl\s23_clnt.c:800:
9 verbose stack
9 verbose stack     at ClientRequest.req.on.err (C:\Users\SHIYAS\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\node-fetch-npm\src\index.js:68:14)
9 verbose stack     at emitOne (events.js:116:13)
9 verbose stack     at ClientRequest.emit (events.js:211:7)
9 verbose stack     at onerror (C:\Users\SHIYAS\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\https-proxy-agent\node_modules\agent-base\index.js:106:9)
9 verbose stack     at callbackError (C:\Users\SHIYAS\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\https-proxy-agent\node_modules\agent-base\index.js:126:5)
9 verbose stack     at <anonymous>
10 verbose cwd E:\NodeJS\burstsmsapi-master
11 verbose Windows_NT 10.0.15063
12 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\SHIYAS\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "bitly" "--save"
13 verbose node v8.9.1
14 verbose npm  v5.5.1
15 error code EPROTO
16 error errno EPROTO
17 error request to https://registry.npmjs.org/bitly failed, reason: write EPROTO 101057795:error:14077460:SSL routines:SSL23_GET_SERVER_HELLO:reason(1120):openssl\ssl\s23_clnt.c:800:
18 verbose exit [ 1, true ]

**Comment by cmshiyas** [comment]
@KenanY any help on this issue?

**Comment by cmshiyas** [comment]
I found the solution myself...

removed the highlighted line(proxy) from .npmrc file under C:\Users\SHIYAS and it works

registry=https://registry.npmjs.org/
**proxy=https://registry.npmjs.org/**
strict-ssl=false
python=C:\Users\SHIYAS\AppData\Local\Programs\Python\Python37\python.exe
strict_ssl=false

**Comment by natedehorn** [comment]
Experienced a similar issue.

Was able to resolve by removing proxy variables from the .npmrc (as @cmshiyas suggested) and then ensuring proxy environment variables were set properly (some were https instead of http).
