### ISSUE TITLE
npm ERR! Windows_NT 10.0.15063

### ISSUE THREAD

**Issue by abhibhowmick** [npm/npm#19095]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [. ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
$ npm start
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\                                                                             node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.11.4
npm ERR! npm  v3.10.10

npm ERR! missing script: start
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     F:\Programming Project\project1\npm-debug.log

### supporting information:

 - `npm -v` prints: 3.10.10
 - `node -v` prints: v6.11.4
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: win 10 
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by abhibhowmick** [comment]
npm-debug.log is given below::

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.10.10
3 info using node@v6.11.4
4 verbose stack Error: missing script: start
4 verbose stack     at run (C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:151:19)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:61:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:356:5
4 verbose stack     at checkBinReferences_ (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:320:45)
4 verbose stack     at final (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:354:3)
4 verbose stack     at then (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:124:5)
4 verbose stack     at ReadFileContext.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:295:20)
4 verbose stack     at ReadFileContext.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16)
4 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:367:13)
5 verbose cwd F:\Programming Project\project1
6 error Windows_NT 10.0.15063
7 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
8 error node v6.11.4
9 error npm  v3.10.10
10 error missing script: start
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

**Comment by kenany** [comment]
Hello! So, the way `npm start` works is that it looks in your current `package.json` for a defined `"start"` [script](https://docs.npmjs.com/misc/scripts), and then runs that. The error message you're seeing is trying to tell you that you have not defined a `"start"` script in your `package.json`, hence `npm start` has no idea what you want it to do.

To solve this issue, all you have to do is add a new script to your `package.json`. It might look something like this, for example:

``` json
{
  "name": "package-name",
  "version": "1.0.0",
  "description": "package description",
  "scripts": {
    "start": "node --version",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "dependencies": {},
  "devDependencies": {}
}
```

Note how this `package.json` has a `"start"` script that runs `node --version`. You'll definitely want to change the command to whatever is most appropriate for your project.

Let me know if you run into any further `npm` issues :)

**Comment by bhadmus** [comment]
I have a similar issue and I have done as instructed but the problem persists please advice.

```
"scripts": {
    "start": "node --7.10.1",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "dependencies": {},
  "devDependencies": {},``

**Comment by bhadmus** [comment]
this is the whole content of my package.json file. I had to uninstall to lower version having gone through so many suggested solutions

```
{
  {
  "version": "4.2.0",
  "name": "npm",
  "description": "a package manager for JavaScript",
  "keywords": [
    "install",
    "modules",
    "package manager",
    "package.json"
  ],
  "preferGlobal": true,
  "config": {
    "publishtest": false
  },
  "homepage": "https://docs.npmjs.com/",
  "author": "Isaac Z. Schlueter <i@izs.me> (http://blog.izs.me)",
  "repository": {
    "type": "git",
    "url": "https://github.com/npm/npm"
  },
  "bugs": {
    "url": "https://github.com/npm/npm/issues"
  },
  "directories": {
    "bin": "./bin",
    "doc": "./doc",
    "lib": "./lib",
    "man": "./man"
  },
  "main": "./lib/npm.js",
  "bin": "./bin/npm-cli.js",
  "dependencies": {
    "JSONStream": "~1.3.0",
    "abbrev": "~1.0.9",
    "ansi-regex": "~2.1.1",
    "ansicolors": "~0.3.2",
    "ansistyles": "~0.1.3",
    "aproba": "~1.0.4",
    "archy": "~1.0.0",
    "asap": "~2.0.5",
    "chownr": "~1.0.1",
    "cmd-shim": "~2.0.2",
    "columnify": "~1.5.4",
    "config-chain": "~1.1.11",
    "dezalgo": "~1.0.3",
    "editor": "~1.0.0",
    "fs-vacuum": "~1.2.9",
    "fs-write-stream-atomic": "~1.0.8",
    "fstream": "~1.0.10",
    "fstream-npm": "~1.2.0",
    "glob": "~7.1.1",
    "graceful-fs": "~4.1.11",
    "has-unicode": "~2.0.1",
    "hosted-git-info": "~2.1.5",
    "iferr": "~0.1.5",
    "inflight": "~1.0.6",
    "inherits": "~2.0.3",
    "ini": "~1.3.4",
    "init-package-json": "~1.9.4",
    "lockfile": "~1.0.3",
    "lodash._baseuniq": "~4.6.0",
    "lodash.clonedeep": "~4.5.0",
    "lodash.union": "~4.6.0",
    "lodash.uniq": "~4.5.0",
    "lodash.without": "~4.4.0",
    "mississippi": "~1.3.0",
    "mkdirp": "~0.5.1",
    "node-gyp": "~3.5.0",
    "nopt": "~4.0.1",
    "normalize-git-url": "~3.0.2",
    "normalize-package-data": "~2.3.5",
    "npm-cache-filename": "~1.0.2",
    "npm-install-checks": "~3.0.0",
    "npm-package-arg": "~4.2.0",
    "npm-registry-client": "~7.4.5",
    "npm-user-validate": "~0.1.5",
    "npmlog": "~4.0.2",
    "once": "~1.4.0",
    "opener": "~1.4.2",
    "osenv": "~0.1.4",
    "path-is-inside": "~1.0.2",
    "read": "~1.0.7",
    "read-cmd-shim": "~1.0.1",
    "read-installed": "~4.0.3",
    "read-package-json": "~2.0.4",
    "read-package-tree": "~5.1.5",
    "readable-stream": "~2.2.2",
    "realize-package-specifier": "~3.0.3",
    "request": "~2.79.0",
    "retry": "~0.10.1",
    "rimraf": "~2.5.4",
    "semver": "~5.3.0",
    "sha": "~2.0.1",
    "slide": "~1.1.6",
    "sorted-object": "~2.0.1",
    "sorted-union-stream": "~2.1.3",
    "strip-ansi": "~3.0.1",
    "tar": "~2.2.1",
    "text-table": "~0.2.0",
    "uid-number": "0.0.6",
    "umask": "~1.1.0",
    "unique-filename": "~1.1.0",
    "unpipe": "~1.0.0",
    "uuid": "~3.0.1",
    "validate-npm-package-name": "~2.2.2",
    "which": "~1.2.12",
    "wrappy": "~1.0.2",
    "write-file-atomic": "~1.3.1"
  },
  "bundleDependencies": [
    "abbrev",
    "ansi-regex",
    "ansicolors",
    "ansistyles",
    "aproba",
    "archy",
    "asap",
    "chownr",
    "cmd-shim",
    "columnify",
    "config-chain",
    "debuglog",
    "dezalgo",
    "editor",
    "fs-vacuum",
    "fs-write-stream-atomic",
    "fstream",
    "fstream-npm",
    "glob",
    "graceful-fs",
    "has-unicode",
    "hosted-git-info",
    "iferr",
    "imurmurhash",
    "inflight",
    "inherits",
    "ini",
    "init-package-json",
    "JSONStream",
    "lockfile",
    "lodash._baseindexof",
    "lodash._baseuniq",
    "lodash._bindcallback",
    "lodash._cacheindexof",
    "lodash._createcache",
    "lodash._getnative",
    "lodash.clonedeep",
    "lodash.restparam",
    "lodash.union",
    "lodash.uniq",
    "lodash.without",
    "mkdirp",
    "node-gyp",
    "nopt",
    "normalize-git-url",
    "normalize-package-data",
    "npm-cache-filename",
    "npm-install-checks",
    "npm-package-arg",
    "npm-registry-client",
    "npm-user-validate",
    "npmlog",
    "once",
    "opener",
    "osenv",
    "path-is-inside",
    "read",
    "read-cmd-shim",
    "read-installed",
    "read-package-json",
    "read-package-tree",
    "readable-stream",
    "readdir-scoped-modules",
    "realize-package-specifier",
    "request",
    "retry",
    "rimraf",
    "semver",
    "sha",
    "slide",
    "sorted-object",
    "sorted-union-stream",
    "strip-ansi",
    "tar",
    "text-table",
    "uid-number",
    "umask",
    "unique-filename",
    "unpipe",
    "validate-npm-package-license",
    "validate-npm-package-name",
    "which",
    "wrappy",
    "write-file-atomic",
    "mississippi",
    "uuid"
  ],
  "devDependencies": {
    "deep-equal": "~1.0.1",
    "marked": "~0.3.6",
    "marked-man": "~0.2.0",
    "npm-registry-couchapp": "~2.6.12",
    "npm-registry-mock": "~1.0.1",
    "require-inject": "~1.4.0",
    "sprintf-js": "~1.0.3",
    "standard": "~6.0.8",
    "tacks": "~1.2.2",
    "tap": "~9.0.3"
  },
  "scripts": {
    "start": "node --7.10.1",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  
  "license": "Artistic-2.0"
}

```
