### ISSUE TITLE
NPM unknown protocol Ask Question

### ISSUE THREAD

**Issue by zhengbucuo** [npm/npm#19094]
#### When I run

 - `npm install -g cnpm --registry=https://registry.npm.taobao.org` :

#### I get following error. It seems it can't download any package. 
I use node v8.9.0 and npm 5.5.1
Do you have any idea what is wrong?
  npm set proxy，and proxy no problem.

#### cmd err：

npm ERR! code EPROTO
npm ERR! errno EPROTO
npm ERR! request to https://registry.npm.taobao.org/cnpm failed, reason: write EPROTO 140242302625600:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:797:
npm ERR!
npm ERR! A complete log of this run can be found in:
npm ERR! /root/.npm/_logs/2017-11-07T16_07_52_825Z-debug.log

#### npm logs:
 0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli '/usr/bin/npm',
1 verbose cli 'install',
1 verbose cli '-g',
1 verbose cli 'cnpm',
1 verbose cli '--registry=https://registry.npm.taobao.org' ]
2 info using npm@5.5.1
3 info using node@v8.9.0
4 verbose npm-session a21ec046ea2435c7
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData error for cnpm@latest request to https://registry.npm.taobao.org/cnpm failed, reason: write EPROTO 140242302625600:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:797:
8 verbose type system
9 verbose stack FetchError: request to https://registry.npm.taobao.org/cnpm failed, reason: write EPROTO 140242302625600:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:797:
9 verbose stack
9 verbose stack at ClientRequest.req.on.err (/usr/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/src/index.js:68:14)
9 verbose stack at emitOne (events.js:116:13)
9 verbose stack at ClientRequest.emit (events.js:211:7)
9 verbose stack at onerror (/usr/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/https-proxy-agent/node_modules/agent-base/index.js:106:9)
9 verbose stack at callbackError (/usr/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/https-proxy-agent/node_modules/agent-base/index.js:126:5)
9 verbose stack at 
10 verbose cwd /root
11 verbose Linux 3.10.0-514.26.2.el7.x86_64
12 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "cnpm" "--registry=https://registry.npm.taobao.org"
13 verbose node v8.9.0
14 verbose npm v5.5.1
15 error code EPROTO
16 error errno EPROTO
17 error request to https://registry.npm.taobao.org/cnpm failed, reason: write EPROTO 140242302625600:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:797:

#### npm config list -l:
; cli configs
long = true
metrics-registry = "https://registry.npm.taobao.org/"
scope = ""
user-agent = "npm/5.5.1 node/v8.9.0 linux x64"

; userconfig /root/.npmrc
https-proxy = "https://10.79.1.161:3128/"
proxy = "http://10.79.1.161:3128/"
registry = "https://registry.npm.taobao.org/"

; default values
access = null
allow-same-version = false
also = null
always-auth = false
auth-type = "legacy"
bin-links = true
browser = null
ca = null
cache = "/root/.npm"
cache-lock-retries = 10
cache-lock-stale = 60000
cache-lock-wait = 10000
cache-max = null
cache-min = 10
cafile = undefined
cert = null
cidr = null
color = true
commit-hooks = true
depth = null
description = true
dev = false
dry-run = false
editor = "vi"
engine-strict = false
fetch-retries = 2
fetch-retry-factor = 10
fetch-retry-maxtimeout = 60000
fetch-retry-mintimeout = 10000
force = false
git = "git"
git-tag-version = true
global = false
global-style = false
globalconfig = "/usr/etc/npmrc"
globalignorefile = "/usr/etc/npmignore"
group = 0
ham-it-up = false
heading = "npm"
; https-proxy = null (overridden)
if-present = false
ignore-prepublish = false
ignore-scripts = false
init-author-email = ""
init-author-name = ""
init-author-url = ""
init-license = "ISC"
init-module = "/root/.npm-init.js"
init-version = "1.0.0"
json = false
key = null
legacy-bundling = false
link = false
local-address = undefined
loglevel = "notice"
logs-max = 10
; long = false (overridden)
maxsockets = 50
message = "%s"
; metrics-registry = null (overridden)
node-version = "8.9.0"
offline = false
onload-script = null
only = null
optional = true
otp = 0
package-lock = true
parseable = false
prefer-offline = false
prefer-online = false
prefix = "/usr"
production = false
progress = true
; proxy = null (overridden)
read-only = false
rebuild-bundle = true
; registry = "https://registry.npmjs.org/" (overridden)
rollback = true
save = true
save-bundle = false
save-dev = false
save-exact = false
save-optional = false
save-prefix = "^"
save-prod = false
scope = ""
script-shell = null
scripts-prepend-node-path = "warn-only"
searchexclude = null
searchlimit = 20
searchopts = ""
searchstaleness = 900
send-metrics = false
shell = "/bin/bash"
shrinkwrap = true
sign-git-tag = false
sso-poll-frequency = 500
sso-type = "oauth"
strict-ssl = true
tag = "latest"
tag-version-prefix = "v"
timing = false
tmp = "/tmp"
umask = 18
unicode = true
unsafe-perm = false
usage = false
user = 0
; user-agent = "npm/{npm-version} node/{node-version} {platform} {arch}" (overridden)
userconfig = "/root/.npmrc"
version = false
versions = false
viewer = "man"

**Comment by zhengbucuo** [comment]
Has been resolved
