### ISSUE TITLE
The install.sh script is broken in a variety of ways

### ISSUE THREAD

**Issue by dracos** [npm/npm#19105]
[I include other issues about the install script in the interests of completeness, but this ticket is also about new issues with the script, both on master and as available on npmjs.com]

#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

Doing as it says in `Fancy Install (Unix)` in the README breaks for a number of reasons:
1. First, it can't find `bin/read-package-json.js` – this is recorded in #18748 and #18524, with a PR to reinstate it at #18909. However the master branch of install.sh has removed the use of this file, so I don't think it necessarily needs to be reinstated;
2. If you try `curl -L https://www.npmjs.com/install.sh | npm_install=5.3.0 sh` instead (last version before that was removed), the installation "succeeds" but `lib/node_modules/npm` is only a symlink to the temporary directory it was unpackaged in (now removed). This is recorded in #17875;
3. If master's `install.sh` is used instead, the script errors at the new `pack` line with `rimraf: not found`. But you can't/shouldn't have to install rimraf before installing npm, which seems a bit of a chicken-and-egg. This was mentioned in #8148 but didn't appear to be resolved – if you have a system with node, but not npm, how do you install rimraf in order to install npm?
4. In commit https://github.com/npm/npm/commit/3603372b4a4016f0a399860ea57192387d6d0f61 entitled "Add Stephen to AUTHORS" back in 2011, the install script was modified to disable make (incidentally the reason it builds the docs "every time" is presumably because it is building in a new temporary checkout of the code each time?). None of the make-based code has run since this point via this install script, so presumably could be removed by now.

A working installation if you don't have rimraf installed, on Linux, is e.g.:
```
curl -O https://registry.npmjs.org/npm/-/npm-5.5.1.tgz
tar xzf npm-5.5.1.tgz 
cd package
node bin/npm-cli.js install -gf [--prefix=~/.npm-prefix] ../npm-5.5.1.tgz
```

The master install.sh uses `$(node bin/npm-cli.js pack | tail -1)` rather than sourcing the .tgz file it has already downloaded, I'm not sure if there's a reason for that or not, it appears to be fine using the tgz file directly.

#### How can the CLI team reproduce the problem?

Try and install the code using the install script on the website.

**Comment by benpptung** [comment]
+1
In FreeBSD,

It thrown the following error:

```
Error: Cannot find module '/tmp/npm.64653/package/bin/read-package-json.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
    at node.js:1043:3
```

It seems link `/usr/local/bin/npm` to `/usr/local/lib/node_modules/npm/bin/npx-cli.js`,
and `/usr/local/lib/node_modeules/npm` link to `../../../../tmp/npm.64653/package`, which is not exist.

**Comment by kweij** [comment]
Cannot install NPM now, I get this:

    $ curl -L https://www.npmjs.org/install.sh | sh
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
    100   185  100   185    0     0    227      0 --:--:-- --:--:-- --:--:--   227
    100  6255  100  6255    0     0   3820      0  0:00:01  0:00:01 --:--:-- 6108k
    tar=/usr/bin/tar
    version:
    bsdtar 2.8.3 - libarchive 2.8.3
    install npm@latest
    fetching: https://registry.npmjs.org/npm/-/npm-5.5.1.tgz
    module.js:538
        throw err;
        ^

    Error: Cannot find module 
    '/private/var/folders/dc/5z60zsj56r325gryt_t_4h140000gn/T/npm.17246/package/bin/read-package-json.js'
        at Function.Module._resolveFilename (module.js:536:15)
        at Function.Module._load (module.js:466:25)
        at Function.Module.runMain (module.js:676:10)
        at startup (bootstrap_node.js:187:16)
        at bootstrap_node.js:608:3
    up to date in 0.044s

**Comment by vivekimsit** [comment]
I am getting exact error on my mac

**Comment by pgraham** [comment]
@dracos can you elaborate a little bit on your work around? What does the npm-cli use the `[--prefix=~/.npm-prefix]` value for?

**Comment by dracos** [comment]
@pgraham It's not really a workaround, just a manual installation :) npm uses the prefix to decide where to install, so you would use that option if you want to install npm somewhere other than the default. https://stackoverflow.com/questions/14469515/how-to-npm-install-to-a-specified-directory has some more explanation. The brackets are to show that I meant that to be an optional part, if you decided you wanted to use it (I did).

**Comment by pgraham** [comment]
Thanks @dracos!

However, when I try that command I'm getting the following error:

```
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/%5B--prefix%3D~/.npm-prefix%5D.git
npm ERR!
npm ERR! fatal: remote error:
npm ERR!    is not a valid repository name
npm ERR!   Email support@github.com for help
```
Looks like the parameters aren't being parsed properly. I'm trying to debug what npm is doing but any ideas would be appreciated.

**Comment by dracos** [comment]
@pgraham As I said, the brackets are to show that it is an optional part, you're not meant to type them.  See e.g. "Optional arguments in usage statements" on http://courses.cms.caltech.edu/cs11/material/general/usage.html

Also, you should decide where you want to install NPM yourself, unless you really want to install it at `~/.npm-prefix`. So if you don't want to install in its default place (which you might!), you'd run `node bin/npm-cli.js install -gf --prefix=~/.npm-prefix ../npm-5.5.1.tgz` (replacing ~/.npm-prefix with wherever you do want to install it).

**Comment by dracos** [comment]
@pgraham Also, you should decide where you want to install NPM yourself, unless you really want to install it at `~/.npm-prefix`. So if you don't want to install in its default place (which you might!), you'd run `node bin/npm-cli.js install -gf --prefix=~/.npm-prefix ../npm-5.5.1.tgz` (replacing ~/.npm-prefix with wherever you do want to install it).

**Comment by pgraham** [comment]
Thanks @dracos , I got it working. Yes, I did want to install to the default, which in my case was the same prefix as where node was installed.

However, I was running into some bash weirdness where the `npm` command was giving me an error:

```
$ npm --version
-bash: /usr/local/bin/npm: No such file or directory
```
Which is not where I had installed npm. But running `which npm` reported the following:

```
$ which npm
/home/pgraham/local/bin/npm
```

I can get this to work by adding a link from /usr/local/bin to the proper location, but I'm not totally happy with that so am investigating further.

Thanks for your help!

---

Update: `hash -r` fixed my problem

**Comment by martincarlin87** [comment]
I'm getting the same error, trying the workaround and getting to the last step:

`node bin/npm-cli.js install -gf [--prefix=~/.npm-prefix] ../npm-5.5.1.tgz`

and getting an error:

```
npm WARN using --force I sure hope you know what you are doing.
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/%5B--prefix%3D~/.npm-prefix%5D.git
npm ERR!
npm ERR! Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR! exited with error code: 128
```

I see the updates above from @pgraham and @dracos but not sure what to actually do to make the install work 😬

Can anyone point me in the right direction?

If I run `node bin/npm-cli.js install -gf  ../npm-5.5.1.tgz` the error message changes to:

```
npm WARN using --force I sure hope you know what you are doing.
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm
npm ERR! path /usr/lib/node_modules/npm
npm ERR! code EEXIST
npm ERR! errno -17
npm ERR! syscall mkdir
npm ERR! EEXIST: file already exists, mkdir '/usr/lib/node_modules/npm'
npm ERR! File exists: /usr/lib/node_modules/npm
npm ERR! Move it away, and try again.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-01-24T16_45_12_352Z-debug.log
```

but the `/usr/lib/node_modules/npm` belongs to root, however it appears that I have a mangled symlink pointing to `../../../tmp/npm.4005/package` which is probably the damage I did yesterday trying to fix my node js installation.

Sorry, it seems to work after doing `unlink /usr/lib/node_modules/npm`. Thanks for posting this @dracos :)

Thanks,
Martin

**Comment by dracos** [comment]
@martincarlin87 As I wrote in the comment above, you don't actually put the square brackets, they are there to tell you that the option is, well, optional (if you had write access to the default location). Just remove the square brackets `[` and `]` (as I gave exactly at the end of my last comment) if you want to use ~/.npm-prefix as your prefix directory, or change it to somewhere else if you want it somewhere else.

**Comment by ozdemirburak** [comment]
If you followed one of the methods mentioned in [node and npm install in 30 seconds](https://gist.github.com/isaacs/579814) and failed, then this is the place where you should look.

For npm 6.0.0, here is the updated code block of what dracos provided in the first place.

```
curl -O https://registry.npmjs.org/npm/-/npm-6.0.0.tgz
tar xzf npm-6.0.0.tgz 
cd package
node bin/npm-cli.js install -gf --prefix=~/local ../npm-6.0.0.tgz
```

The output will look like below.

```
~/local/bin/npm -> ~/local/lib/node_modules/npm/bin/npm-cli.js
~/local/bin/npx -> ~/local/lib/node_modules/npm/bin/npx-cli.js
```

To see if it is working as expected.

```
npm -v
```

**Comment by TimvdLippe** [comment]
@ozdemirburak Thanks, that worked! I had to make one update though, as my install scripts were in `/usr/local/bin/` instead. The install command then becomes:

```
node bin/npm-cli.js install -gf --prefix=/usr/local ../npm-6.0.0.tgz
```

**Comment by aminukano585** [comment]
Thanks to everyone for generating this thread! 
Thanks @pgraham, that `hash -r` fixed my problem. Can you explain further pls?
