### ISSUE TITLE
Error: EPERM: operation not permitted, mkdir 'C:\Users\Owners'

### ISSUE THREAD

**Issue by jrmcdona** [npm/npm#19132]
#### I'm opening this issue because:

  - [x ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
All NPM commands are failling.  

### supporting information:
This happens with v8.9.0 and also after installing v8.9.1.  

Here is what happens with any NPM command.   UNable to perform "npm install webpack -g".

Unable to run "npm -v".

Example
```
C:\Users\Owner>npm install webpack -g
Error: EPERM: operation not permitted, mkdir 'C:\Users\Owners'
TypeError: Cannot read property 'get' of undefined
    at errorHandler (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:205:18)
    at C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js:83:20
    at cb (C:\Program Files\nodejs\node_modules\npm\lib\npm.js:214:22)
    at C:\Program Files\nodejs\node_modules\npm\lib\npm.js:252:24
    at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:81:7
    at Array.forEach (<anonymous>)
    at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:80:13
    at f (C:\Program Files\nodejs\node_modules\npm\node_modules\once\once.js:25:25)
    at afterExtras (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:178:20)
    at C:\Program Files\nodejs\node_modules\npm\node_modules\mkdirp\index.js:35:29
C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:205
  if (npm.config.get('json')) {
                 ^

TypeError: Cannot read property 'get' of undefined
    at process.errorHandler (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:205:18)
    at emitOne (events.js:116:13)
    at process.emit (events.js:211:7)
    at process._fatalException (bootstrap_node.js:374:26)
Error: EPERM: operation not permitted, mkdir 'C:\Users\Owners'
TypeError: Cannot read property 'get' of undefined
    at errorHandler (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:205:18)
    at C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js:83:20
    at cb (C:\Program Files\nodejs\node_modules\npm\lib\npm.js:214:22)
    at C:\Program Files\nodejs\node_modules\npm\lib\npm.js:252:24
    at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:81:7
    at Array.forEach (<anonymous>)
    at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:80:13
    at f (C:\Program Files\nodejs\node_modules\npm\node_modules\once\once.js:25:25)
    at afterExtras (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:178:20)
    at C:\Program Files\nodejs\node_modules\npm\node_modules\mkdirp\index.js:35:29
C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:205
  if (npm.config.get('json')) {
                 ^

TypeError: Cannot read property 'get' of undefined
    at process.errorHandler (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:205:18)
    at emitOne (events.js:116:13)
    at process.emit (events.js:211:7)
    at process._fatalException (bootstrap_node.js:374:26)

C:\Users\Owner>
```
 - `npm -v` prints:
5.5.1  (but this command also fails)
 - `node -v` prints:
This happens with v8.9.0 and also after installing v8.9.1

 - `npm config get registry` prints:
This command fails.
 - Windows, OS X/macOS, or Linux?:
Windows 10
 - Network issues:

None.

**Comment by jrmcdona** [comment]
This started working after I:

1. Open up a command Window in Administator mode.
2. Type npm config edit
3. Didn't make any changes to config file.  
4. Tried to run npm start but it failed (npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\Owners\AppData\Roaming\npm\package.json')
5.  Opened up a non-admin command console 
6.  Ran "npm -v" and no failures now

Not really sure what just kicked this into gear.

**Comment by sebastianwindeck** [comment]
I got the same problem, but your solution does not work for me

**Comment by fightingljm** [comment]
@jrmcdona I have the same problem. Have you solved the problem
And it was the same mistake that I unloaded

**Comment by brandonmp** [comment]
@jrmcdona fix worked for me. almost no info on this error on the web, glad i found this issue.

**Comment by MUDev1994** [comment]
**Solved**
Similar to @jrmcdona , I followed what he wrote, but changed a little bit. (see the steps below)
Thanks!

I was having problem when I was trying to use npm, 
I was trying to do npm install.

I kept getting this error:
``Error: EPERM: operation not permitted, mkdir 'C:\Program Files\Git\usr\local'`

So I opened Cmd as administrator then typed `npm config edit` then closed the filed without doing anything, then typed `npm -v` and it showed me the version there in cmd.  then opened git bash then typed `npm -v` and it showed me the version as well, then typed `npm install` and it worked :)

**Comment by EBMike** [comment]
I tried the same thing and npm install still fails for me... It's definitely a permission issue. If you give the node_modules folder full permissions (ie. Add "Everyone" and check all the permission boxes) then run npm install, it will work.

I just updated npm from 4.3 to 5.6 and this started happening for me.

**Comment by creton13** [comment]
Worked through the windows command prompt, Thanks,   still mind-boggled by not working on my GIT command.

**Comment by SharmaBiswadev** [comment]
i got the same issue when i updated to latest v8.11.2 ,the above solved the issue..but still not clear about the cause of this issue
