### ISSUE TITLE
Cannot npm link

### ISSUE THREAD

**Issue by hueniverse** [npm/npm#19154]
#### I'm opening this issue because:

  - npm is crashing.

#### What's going wrong?

Cannot link to another module. The module is private.

#### How can the CLI team reproduce the problem?

Not sure.

### supporting information:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'link',
1 verbose cli   'private/x-private' ]
2 info using npm@5.5.1
3 info using node@v8.9.0
4 verbose npm-session ecb3352bace432d0
5 verbose stack Error: Argument #2: Expected array but got string
5 verbose stack     at EventEmitter.install (/usr/local/lib/node_modules/npm/lib/install.js:184:3)
5 verbose stack     at Object.commandCache.(anonymous function) (/usr/local/lib/node_modules/npm/lib/npm.js:149:13)
5 verbose stack     at /usr/local/lib/node_modules/npm/lib/link.js:93:24
5 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:284:29
5 verbose stack     at FSReqWrap.oncomplete (fs.js:152:21)
6 verbose cwd /home/eran/code/private/y-private
7 verbose Linux 4.4.0-98-generic
8 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "link" "private/x-private"
9 verbose node v8.9.0
10 verbose npm  v5.5.1
11 error code EINVALIDTYPE
12 error typeerror Error: Argument #2: Expected array but got string
12 error typeerror     at EventEmitter.install (/usr/local/lib/node_modules/npm/lib/install.js:184:3)
12 error typeerror     at Object.commandCache.(anonymous function) (/usr/local/lib/node_modules/npm/lib/npm.js:149:13)
12 error typeerror     at /usr/local/lib/node_modules/npm/lib/link.js:93:24
12 error typeerror     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:284:29
12 error typeerror     at FSReqWrap.oncomplete (fs.js:152:21)
13 error typeerror This is an error with npm itself. Please report this error at:
13 error typeerror     <https://github.com/npm/npm/issues>
14 verbose exit [ 1, true ]
```

**Comment by Magneticmagnum** [comment]
Do you have replication steps on how you're linking to your private module?

**Comment by hueniverse** [comment]
In the source `sudo npm link` and in the target `npm link module_name`

**Comment by Magneticmagnum** [comment]
Not too helpful since the replication is very vague. 

I'm assuming your issue is that the path or name isn't correct.

Best of luck on your issue.

**Comment by hueniverse** [comment]
It went away when I installed node 8.9.1. I don't have the time to look into it. If this is useful to someone, great.
