### ISSUE TITLE
Error: Failed to replace env in config: ${NPM_TOKEN}

### ISSUE THREAD

**Issue by sugerpocket** [npm/npm#19169]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints: 5.5.1
 - `node -v` prints: v8.7.0
 - `npm config get registry` prints:
 ````shell
 Error: Failed to replace env in config: ${NPM_TOKEN}
    at /usr/local/lib/node_modules/npm/lib/config/core.js:418:13
    at String.replace (<anonymous>)
    at envReplace (/usr/local/lib/node_modules/npm/lib/config/core.js:414:12)
    at parseField (/usr/local/lib/node_modules/npm/lib/config/core.js:392:7)
    at /usr/local/lib/node_modules/npm/lib/config/core.js:335:17
    at Array.forEach (<anonymous>)
    at Conf.add (/usr/local/lib/node_modules/npm/lib/config/core.js:334:23)
    at ConfigChain.addString (/usr/local/lib/node_modules/npm/node_modules/config-chain/index.js:244:8)
    at Conf.<anonymous> (/usr/local/lib/node_modules/npm/lib/config/core.js:322:10)
    at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
TypeError: Cannot read property 'get' of undefined
    at errorHandler (/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:205:18)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:83:20
    at cb (/usr/local/lib/node_modules/npm/lib/npm.js:214:22)
    at /usr/local/lib/node_modules/npm/lib/npm.js:252:24
    at /usr/local/lib/node_modules/npm/lib/config/core.js:81:7
    at Array.forEach (<anonymous>)
    at Conf.<anonymous> (/usr/local/lib/node_modules/npm/lib/config/core.js:80:13)
    at Conf.f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:25:25)
    at Object.onceWrapper (events.js:316:30)
    at emitOne (events.js:115:13)
/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:205
  if (npm.config.get('json')) {
                 ^

TypeError: Cannot read property 'get' of undefined
    at process.errorHandler (/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:205:18)
    at emitOne (events.js:115:13)
    at process.emit (events.js:210:7)
    at process._fatalException (bootstrap_node.js:374:26)
ERROR: Build failed: exit status 1
 ````
 - Windows, OS X/macOS, or Linux?: Linux
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

I used gitlab-runner to build this web client app, and got a failed pipelines
````shell
$ npm install
Error: Failed to replace env in config: ${NPM_TOKEN}
    at /usr/local/lib/node_modules/npm/lib/config/core.js:418:13
    at String.replace (<anonymous>)
    at envReplace (/usr/local/lib/node_modules/npm/lib/config/core.js:414:12)
    at parseField (/usr/local/lib/node_modules/npm/lib/config/core.js:392:7)
    at /usr/local/lib/node_modules/npm/lib/config/core.js:335:17
    at Array.forEach (<anonymous>)
    at Conf.add (/usr/local/lib/node_modules/npm/lib/config/core.js:334:23)
    at ConfigChain.addString (/usr/local/lib/node_modules/npm/node_modules/config-chain/index.js:244:8)
    at Conf.<anonymous> (/usr/local/lib/node_modules/npm/lib/config/core.js:322:10)
    at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
TypeError: Cannot read property 'get' of undefined
    at errorHandler (/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:205:18)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:83:20
    at cb (/usr/local/lib/node_modules/npm/lib/npm.js:214:22)
    at /usr/local/lib/node_modules/npm/lib/npm.js:252:24
    at /usr/local/lib/node_modules/npm/lib/config/core.js:81:7
    at Array.forEach (<anonymous>)
    at Conf.<anonymous> (/usr/local/lib/node_modules/npm/lib/config/core.js:80:13)
    at Conf.f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:25:25)
    at Object.onceWrapper (events.js:316:30)
    at emitOne (events.js:115:13)
/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:205
  if (npm.config.get('json')) {
                 ^

TypeError: Cannot read property 'get' of undefined
    at process.errorHandler (/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:205:18)
    at emitOne (events.js:115:13)
    at process.emit (events.js:210:7)
    at process._fatalException (bootstrap_node.js:374:26)
ERROR: Build failed: exit status 1
````
how can I get a correct `npm install`?

**Comment by sugerpocket** [comment]
The output of `cat /var/lib/gitlab-runner/.npmrc`:
````shell
//registry.npmjs.org/:_authToken=${NPM_TOKEN}
````

**Comment by gabrielavoll** [comment]
I'm also having this same issue 😒 

Except with node v8.2.1

**Comment by gabrielavoll** [comment]
Ahhh, well I was able to fix my issue by just setting the NPM_TOKEN  in my: 
.bash_profile 
and .bashrc 

Because in my case, I've been utilizing a npm package that is private, and so requires a username and password to access. 

And my /MY-REPO/.npmrc also looks like this 
```  
//registry.npmjs.org/:_authToken=${NPM_TOKEN} 
```

I'm back and up 
``` 
node v9.2.0 
npm v5.5.1
 ```
( i upgraded my node and npm version, since I thought that might be causing the issue, i was mistaken but saq no reason to step back )
I'd don't know if this is of any help  ¯\_(ツ)_/¯

**Comment by ekryski** [comment]
I'm also seeing this issue when trying to run inside a Docker container. Passing the `NPM_TOKEN` as described here: https://docs.npmjs.com/private-modules/docker-and-private-modules doesn't work.

@sugerpocket can you re-open?

**Comment by julesGoullee** [comment]
Just remove .npmrc at the end of dockerfile

**Comment by ekryski** [comment]
@julesGoullee just be aware that unless you use the beta `--squash` flag during your docker build the file will still be available in the docker history.

We've hacked around it by adding it as a build `ARG` in our docker file:

```
FROM node:8.11.1-alpine

# Bring in our build arg so that we can pull from our private registry
ARG NPM_TOKEN

# Install deps to build natively
RUN apk update && apk upgrade && \
  apk add --no-cache --virtual .gyp \
  bash \
  python \
  make \
  g++

# Create our node user direction and bundle the app source
# This takes into account our .dockerignore file
RUN mkdir -p /home/node/my-app
WORKDIR /home/node/my-app
COPY . /home/node/my-app

# We do this so NPM doesn't try to use it outside the Docker container messing with our dev envs
# https://github.com/npm/npm/issues/8356
RUN mv sample.npmrc .npmrc

# Set ENV vars
ENV NPM_TOKEN="${NPM_TOKEN}" \
  NODE_ENV="production" \
  PORT=8080

# Install dependencies and clean up
RUN npm install
```

**Comment by cymen** [comment]
I was in a rush on a new computer and put just:

```sh
NPM_TOKEN="xyz"
```

In my `~/.profile` file. I finally noticed I left the `export` off the front of it. So changing it to:

```sh
export NPM_TOKEN="xyz"
```

Solved the problem. It was confusing as `echo $NPM_TOKEN` output what I expected all along but I still got the same error until I made the above change.

**Comment by msageryd** [comment]
I tried every advice I found on this issue, nothing worked. Then I tried to generate a new NPM token,  and everything started to work again.

Do the NPM tokens expire?
I can't think of anything else that could have happened. My docker builds has worked flawlessly with private NPM packages until today. After generating a new token it works again.

**Comment by odGit** [comment]
I am using ConEmu on Windows 10. 
I have the same issue in _CMD_ and _BASH_ .

```
λ npm login
Error: Failed to replace env in config: ${NPM_TOKEN}
    at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:417:13
    at String.replace (<anonymous>)
    at envReplace (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:413:12)
    at parseField (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:391:7)
    at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:334:17
    at Array.forEach (<anonymous>)
    at Conf.add (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:333:23)
    at ConfigChain.addString (C:\Program Files\nodejs\node_modules\npm\node_modules\config-chain\index.js:244:8)
    at Conf.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:321:10)
    at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
C:\Program Files\nodejs\node_modules\npm\lib\npm.js:61
      throw new Error('npm.load() required')
      ^

Error: npm.load() required
    at Object.get (C:\Program Files\nodejs\node_modules\npm\lib\npm.js:61:13)
    at process.errorHandler (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:205:18)
    at emitOne (events.js:116:13)
    at process.emit (events.js:211:7)
    at process._fatalException (bootstrap_node.js:375:26)
```
If I remove `//registry.npmjs.org/:_authToken=${NPM_TOKEN}` from ` .npmrc`  all works. But this solution will result in my CI integration not able to authenticate.  Is there a better solution to this problem?
