### ISSUE TITLE
NPM 5.5.1 missing module, can't do anything

### ISSUE THREAD

**Issue by bystronerik** [npm/npm#19191]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):
  - [x] NPM doesn't work

#### What's going wrong?
  NPM doesn't work !
#### How can the CLI team reproduce the problem?
  Install NPM 5.5.1 and run some npm command

### supporting information:

 - `npm -v` prints: Throw error
 - `node -v` prints: v9.2.0
 - `npm config get registry` prints: Throw error
 - Windows, OS X/macOS, or Linux?: Windows 10 
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

Errors:
`PS C:\> npm -v
module.js:544
    throw err;
    ^

Error: Cannot find module 'npmlog'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at C:\Users\Erik\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js:22:13
    at Object.<anonymous> (C:\Users\Erik\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js:92:3)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
PS C:\> npm config get registry
module.js:544
    throw err;
    ^

Error: Cannot find module 'npmlog'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at C:\Users\Erik\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js:22:13
    at Object.<anonymous> (C:\Users\Erik\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js:92:3)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)`

**Comment by bystronerik** [comment]
**Can anybody help me, please ?**

**Comment by pfeigl** [comment]
Flayovec, I had the same problem recently. Turned out, that the PATH's in my environment somehow got mixed up in ordering and there was a path into the NPM node_modules installation folder before the entry which pointed into the main installation folder.

My advice: Uninstall Node, remove all PATH entries which point to anything NPM / NODE related and reinstall.

That fixed it for me atleast.

**Comment by bystronerik** [comment]
I uninstall it all, delete all caches, data and remove patches and now it works! Thank you!
