### ISSUE TITLE
Can't run npm server (Angular Starter Kit), error 3221225477

### ISSUE THREAD

**Issue by ongubsy** [npm/npm#19203]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I cloned an Angular Starter Kit repo (https://github.com/gdi2290/angular-starter), followed all the steps of installation/configuration, and can't execute the `npm run server` command:

```
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'server' ]
2 info using npm@5.5.1
3 info using node@v8.9.1
4 verbose run-script [ 'preserver', 'server', 'postserver' ]
5 info lifecycle angular-starter@7.0.0~preserver: angular-starter@7.0.0
6 info lifecycle angular-starter@7.0.0~server: angular-starter@7.0.0
7 verbose lifecycle angular-starter@7.0.0~server: unsafe-perm in lifecycle true
8 verbose lifecycle angular-starter@7.0.0~server: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\IEUser\angular-starter\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Users\IEUser\AppData\Roaming\npm
9 verbose lifecycle angular-starter@7.0.0~server: CWD: C:\Users\IEUser\angular-starter
10 silly lifecycle angular-starter@7.0.0~server: Args: [ '/d /s /c', 'npm run server:dev' ]
11 silly lifecycle angular-starter@7.0.0~server: Returned: code: 3221225477  signal: null
12 info lifecycle angular-starter@7.0.0~server: Failed to exec server script
13 verbose stack Error: angular-starter@7.0.0 server: `npm run server:dev`
13 verbose stack Exit status 3221225477
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:280:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid angular-starter@7.0.0
15 verbose cwd C:\Users\IEUser\angular-starter
16 verbose Windows_NT 6.1.7601
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "server"
18 verbose node v8.9.1
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 3221225477
22 error angular-starter@7.0.0 server: `npm run server:dev`
22 error Exit status 3221225477
23 error Failed at the angular-starter@7.0.0 server script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 3221225477, true ]
```

#### How can the CLI team reproduce the problem?

- Using IE11Win7 32-bit VM image from Microsoft (Free);
- Following all the install steps provided by the starter kit.

### supporting information:

 - `npm -v` prints:
5.5.1
 - `node -v` prints:
v8.9.1
 - `npm config get registry` prints:
https://registry.npmjs.org
 - Windows, OS X/macOS, or Linux?:
Windows 7 32bit Enterprise (free VM distribution)

**Comment by antonnovopashin** [comment]
i have exactly same problem with same npm version same node version and same registry. Os - windows 7 64bit. Help please

**Comment by akghosh1232003** [comment]
Facing same issue while executing npm install
npm -v prints:
5.5.1
node -v prints:
v8.9.1
npm config get registry prints:
https://registry.npmjs.org
Windows, OS X/macOS, or Linux?:
Windows 7 64 bit
