### ISSUE TITLE
script from 'script' section failed on windows

### ISSUE THREAD

**Issue by XaveScor** [npm/npm#19234]
#### I'm opening this issue because:
 npm is crashing.
 #### What's going wrong?
if I run `npm test` script failed.
output on windows
```
PS C:\Users\andrey.vassilyev\projects\node-semver> npm test

> semver@5.4.1 test C:\Users\andrey.vassilyev\projects\node-semver
> tap test/*.js --cov -J

module.js:538
    throw err;
    ^

Error: Cannot find module 'C:\Users\andrey.vassilyev\.node-spawn-wrap-10348-2a2c0e331b6c\node.EXE'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
module.js:538
    throw err;
    ^

Error: Cannot find module 'C:\Users\andrey.vassilyev\.node-spawn-wrap-10348-2a2c0e331b6c\node.EXE'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
test/big-numbers.js ................................... 0/1
  not ok test/big-numbers.js
    timeout: 240000
    file: test/big-numbers.js
    command: 'C:\Program Files\nodejs\node.EXE'
    args:
      - test/big-numbers.js
    cwd: 'C:\Users\andrey.vassilyev\projects\node-semver'
    exitCode: 1

module.js:538
    throw err;
    ^
...
```
If I run script directly all ok:
```
PS C:\Users\andrey.vassilyev\projects\node-semver> tap test/*.js --cov -J
test/big-numbers.js ................................. 11/11
test/clean.js ....................................... 12/12
test/gtr.js ....................................... 141/141
test/index.js ................................... 1626/1626
test/ltr.js ....................................... 149/149
test/major-minor-patch.js ........................... 27/27
test/prerelease.js .................................... 9/9
total ........................................... 1975/1975

  1975 passing (2s)

  ok
-----------|----------|----------|----------|----------|----------------|
File       |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
-----------|----------|----------|----------|----------|----------------|
All files  |    97.46 |    95.39 |    96.55 |    98.02 |                |
 semver.js |    97.46 |    95.39 |    96.55 |    98.02 |... 487,488,546 |
-----------|----------|----------|----------|----------|----------------|
```
If I run `npm test` via WSL all ok
#### How can the CLI team reproduce the problem?
```
git clone https://github.com/npm/node-semver.git
cd node-semver
npm install
npm test
```
### supporting information:

 - `npm -v` prints: 5.5.1
 - `node -v` prints: v8.9.1
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows 10.14393.1770

**Comment by alanxwill** [comment]
I have the same problem when I type npm and whatever in terminal, It will show me 538 err.

```
➜  ~ npm
module.js:538
    throw err;
    ^

Error: Cannot find module '../lib/utils/unsupported.js'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:19:21
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:92:3)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
```
