### ISSUE TITLE
npm ERR! Windows_NT 10.0.14393

### ISSUE THREAD

**Issue by VenkatJandhyam** [npm/npm#19256]
#### I'm opening this issue because:

  - [ ] npm is crashing.
 
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Users\\cc21\\.webclipse\\nodejs\\7.10.1\\node.exe" "C:\\Users\\cc21\\.webclipse\\npm\\3.10.10\\bin\\npm-cli.js" "install" "@angular/cli@1.
4.9"
npm ERR! node v7.10.1
npm ERR! npm  v3.10.10
npm ERR! file C:\WINDOWS\system32\cmd.exe;C:\WINDOWS\SysWOW64\cmd.exe
npm ERR! path C:\WINDOWS\system32\cmd.exe;C:\WINDOWS\SysWOW64\cmd.exe
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn C:\WINDOWS\system32\cmd.exe;C:\WINDOWS\SysWOW64\cmd.exe

npm ERR! uglifyjs-webpack-plugin@0.4.6 postinstall: `node lib/post_install.js`
npm ERR! spawn C:\WINDOWS\system32\cmd.exe;C:\WINDOWS\SysWOW64\cmd.exe ENOENT
npm ERR!
npm ERR! Failed at the uglifyjs-webpack-plugin@0.4.6 postinstall script 'node lib/post_install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the uglifyjs-webpack-plugin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lib/post_install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs uglifyjs-webpack-plugin
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls uglifyjs-webpack-plugin
npm ERR! There is likely additional logging output above.

Not able to create the angularjs application. Can you please help me to resolve the issue. 

Eclipse: Oxygen

Trying to create a new angularjs project facing this issue.

**Comment by VenkatJandhyam** [comment]
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Users\\cc21\\.webclipse\\nodejs\\7.10.1\\node.exe" "C:\\Users\\cc21\\.webclipse\\npm\\3.10.10\\bin\\npm-cli.js" "install" "@angular/cli@1.
4.9"
npm ERR! node v7.10.1
npm ERR! npm  v3.10.10
npm ERR! file C:\WINDOWS\system32\cmd.exe;C:\WINDOWS\SysWOW64\cmd.exe
npm ERR! path C:\WINDOWS\system32\cmd.exe;C:\WINDOWS\SysWOW64\cmd.exe
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn C:\WINDOWS\system32\cmd.exe;C:\WINDOWS\SysWOW64\cmd.exe

npm ERR! uglifyjs-webpack-plugin@0.4.6 postinstall: `node lib/post_install.js`
npm ERR! spawn C:\WINDOWS\system32\cmd.exe;C:\WINDOWS\SysWOW64\cmd.exe ENOENT
npm ERR!
npm ERR! Failed at the uglifyjs-webpack-plugin@0.4.6 postinstall script 'node lib/post_install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the uglifyjs-webpack-plugin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lib/post_install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs uglifyjs-webpack-plugin
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls uglifyjs-webpack-plugin
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Workspacelatesteclipse\vlrclient\npm-debug.log

**Comment by VenkatJandhyam** [comment]
97413 silly rollbackFailedOptional Finishing
97414 silly runTopLevelLifecycles Finishing
97415 silly install printInstalled
97416 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
97417 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
97418 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
97418 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
97418 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
97418 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
97419 warn enoent ENOENT: no such file or directory, open 'C:\Workspacelatesteclipse\vlrclient\package.json'
97420 verbose enoent ENOENT: no such file or directory, open 'C:\Workspacelatesteclipse\vlrclient\package.json'
97420 verbose enoent This is most likely not a problem with npm itself
97420 verbose enoent and is related to npm not being able to find a file.
97421 warn @schematics/angular@0.0.49 requires a peer of @angular-devkit/schematics@0.0.34 but none was installed.
97422 verbose If you need help, you may report this error at:
97422 verbose     <https://github.com/npm/npm/issues>
97423 warn vlrclient No description
97424 verbose If you need help, you may report this error at:
97424 verbose     <https://github.com/npm/npm/issues>
97425 warn vlrclient No repository field.
97426 verbose If you need help, you may report this error at:
97426 verbose     <https://github.com/npm/npm/issues>
97427 warn vlrclient No README data
97428 verbose If you need help, you may report this error at:
97428 verbose     <https://github.com/npm/npm/issues>
97429 warn vlrclient No license field.
97430 verbose If you need help, you may report this error at:
97430 verbose     <https://github.com/npm/npm/issues>
97431 warn optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.7.2 (node_modules\node-sass):
97432 warn optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.7.2 install: `node scripts/install.js`
97432 warn optional SKIPPING OPTIONAL DEPENDENCY: spawn C:\WINDOWS\system32\cmd.exe;C:\WINDOWS\SysWOW64\cmd.exe ENOENT
97433 verbose optional SKIPPING OPTIONAL DEPENDENCY:
97433 verbose optional Failed at the node-sass@4.7.2 install script 'node scripts/install.js'.
97433 verbose optional SKIPPING OPTIONAL DEPENDENCY: Make sure you have the latest version of node.js and npm installed.
97433 verbose optional SKIPPING OPTIONAL DEPENDENCY: If you do, this is most likely a problem with the node-sass package,
97433 verbose optional SKIPPING OPTIONAL DEPENDENCY: not with npm itself.
97433 verbose optional SKIPPING OPTIONAL DEPENDENCY: Tell the author that this fails on your system:
97433 verbose optional SKIPPING OPTIONAL DEPENDENCY:     node scripts/install.js
97433 verbose optional SKIPPING OPTIONAL DEPENDENCY: You can get information on how to open an issue for this project with:
97433 verbose optional SKIPPING OPTIONAL DEPENDENCY:     npm bugs node-sass
97433 verbose optional SKIPPING OPTIONAL DEPENDENCY: Or if that isn't available, you can get their info via:
97433 verbose optional SKIPPING OPTIONAL DEPENDENCY:     npm owner ls node-sass
97433 verbose optional SKIPPING OPTIONAL DEPENDENCY: There is likely additional logging output above.
97434 warn optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.7.2 (node_modules\node-sass):
97435 warn optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.7.2 install: `node scripts/install.js`
97435 warn optional SKIPPING OPTIONAL DEPENDENCY: Exit status -4058
97436 verbose optional SKIPPING OPTIONAL DEPENDENCY:
97436 verbose optional Failed at the node-sass@4.7.2 install script 'node scripts/install.js'.
97436 verbose optional SKIPPING OPTIONAL DEPENDENCY: Make sure you have the latest version of node.js and npm installed.
97436 verbose optional SKIPPING OPTIONAL DEPENDENCY: If you do, this is most likely a problem with the node-sass package,
97436 verbose optional SKIPPING OPTIONAL DEPENDENCY: not with npm itself.
97436 verbose optional SKIPPING OPTIONAL DEPENDENCY: Tell the author that this fails on your system:
97436 verbose optional SKIPPING OPTIONAL DEPENDENCY:     node scripts/install.js
97436 verbose optional SKIPPING OPTIONAL DEPENDENCY: You can get information on how to open an issue for this project with:
97436 verbose optional SKIPPING OPTIONAL DEPENDENCY:     npm bugs node-sass
97436 verbose optional SKIPPING OPTIONAL DEPENDENCY: Or if that isn't available, you can get their info via:
97436 verbose optional SKIPPING OPTIONAL DEPENDENCY:     npm owner ls node-sass
97436 verbose optional SKIPPING OPTIONAL DEPENDENCY: There is likely additional logging output above.
97437 warn optional SKIPPING OPTIONAL DEPENDENCY: uglifyjs-webpack-plugin@0.4.6 (node_modules\uglifyjs-webpack-plugin):
97438 warn optional SKIPPING OPTIONAL DEPENDENCY: uglifyjs-webpack-plugin@0.4.6 postinstall: `node lib/post_install.js`
97438 warn optional SKIPPING OPTIONAL DEPENDENCY: Exit status -4058
97439 verbose optional SKIPPING OPTIONAL DEPENDENCY:
97439 verbose optional Failed at the uglifyjs-webpack-plugin@0.4.6 postinstall script 'node lib/post_install.js'.
97439 verbose optional SKIPPING OPTIONAL DEPENDENCY: Make sure you have the latest version of node.js and npm installed.
97439 verbose optional SKIPPING OPTIONAL DEPENDENCY: If you do, this is most likely a problem with the uglifyjs-webpack-plugin package,
97439 verbose optional SKIPPING OPTIONAL DEPENDENCY: not with npm itself.
97439 verbose optional SKIPPING OPTIONAL DEPENDENCY: Tell the author that this fails on your system:
97439 verbose optional SKIPPING OPTIONAL DEPENDENCY:     node lib/post_install.js
97439 verbose optional SKIPPING OPTIONAL DEPENDENCY: You can get information on how to open an issue for this project with:
97439 verbose optional SKIPPING OPTIONAL DEPENDENCY:     npm bugs uglifyjs-webpack-plugin
97439 verbose optional SKIPPING OPTIONAL DEPENDENCY: Or if that isn't available, you can get their info via:
97439 verbose optional SKIPPING OPTIONAL DEPENDENCY:     npm owner ls uglifyjs-webpack-plugin
97439 verbose optional SKIPPING OPTIONAL DEPENDENCY: There is likely additional logging output above.
97440 warn optional SKIPPING OPTIONAL DEPENDENCY: uglifyjs-webpack-plugin@0.4.6 (node_modules\uglifyjs-webpack-plugin):
97441 warn optional SKIPPING OPTIONAL DEPENDENCY: uglifyjs-webpack-plugin@0.4.6 postinstall: `node lib/post_install.js`
97441 warn optional SKIPPING OPTIONAL DEPENDENCY: spawn C:\WINDOWS\system32\cmd.exe;C:\WINDOWS\SysWOW64\cmd.exe ENOENT
97442 verbose optional SKIPPING OPTIONAL DEPENDENCY:
97442 verbose optional Failed at the uglifyjs-webpack-plugin@0.4.6 postinstall script 'node lib/post_install.js'.
97442 verbose optional SKIPPING OPTIONAL DEPENDENCY: Make sure you have the latest version of node.js and npm installed.
97442 verbose optional SKIPPING OPTIONAL DEPENDENCY: If you do, this is most likely a problem with the uglifyjs-webpack-plugin package,
97442 verbose optional SKIPPING OPTIONAL DEPENDENCY: not with npm itself.
97442 verbose optional SKIPPING OPTIONAL DEPENDENCY: Tell the author that this fails on your system:
97442 verbose optional SKIPPING OPTIONAL DEPENDENCY:     node lib/post_install.js
97442 verbose optional SKIPPING OPTIONAL DEPENDENCY: You can get information on how to open an issue for this project with:
97442 verbose optional SKIPPING OPTIONAL DEPENDENCY:     npm bugs uglifyjs-webpack-plugin
97442 verbose optional SKIPPING OPTIONAL DEPENDENCY: Or if that isn't available, you can get their info via:
97442 verbose optional SKIPPING OPTIONAL DEPENDENCY:     npm owner ls uglifyjs-webpack-plugin
97442 verbose optional SKIPPING OPTIONAL DEPENDENCY: There is likely additional logging output above.
97443 warn optional SKIPPING OPTIONAL DEPENDENCY: uglifyjs-webpack-plugin@0.4.6 (node_modules\uglifyjs-webpack-plugin):
97444 warn optional SKIPPING OPTIONAL DEPENDENCY: uglifyjs-webpack-plugin@0.4.6 postinstall: `node lib/post_install.js`
97444 warn optional SKIPPING OPTIONAL DEPENDENCY: Exit status -4058
97445 verbose optional SKIPPING OPTIONAL DEPENDENCY:
97445 verbose optional Failed at the uglifyjs-webpack-plugin@0.4.6 postinstall script 'node lib/post_install.js'.
97445 verbose optional SKIPPING OPTIONAL DEPENDENCY: Make sure you have the latest version of node.js and npm installed.
97445 verbose optional SKIPPING OPTIONAL DEPENDENCY: If you do, this is most likely a problem with the uglifyjs-webpack-plugin package,
97445 verbose optional SKIPPING OPTIONAL DEPENDENCY: not with npm itself.
97445 verbose optional SKIPPING OPTIONAL DEPENDENCY: Tell the author that this fails on your system:
97445 verbose optional SKIPPING OPTIONAL DEPENDENCY:     node lib/post_install.js
97445 verbose optional SKIPPING OPTIONAL DEPENDENCY: You can get information on how to open an issue for this project with:
97445 verbose optional SKIPPING OPTIONAL DEPENDENCY:     npm bugs uglifyjs-webpack-plugin
97445 verbose optional SKIPPING OPTIONAL DEPENDENCY: Or if that isn't available, you can get their info via:
97445 verbose optional SKIPPING OPTIONAL DEPENDENCY:     npm owner ls uglifyjs-webpack-plugin
97445 verbose optional SKIPPING OPTIONAL DEPENDENCY: There is likely additional logging output above.
97446 verbose stack Error: Callback called more than once.
97446 verbose stack     at errorHandler (C:\Users\cc21\.webclipse\npm\3.10.10\lib\utils\error-handler.js:112:16)
97446 verbose stack     at C:\Users\cc21\.webclipse\npm\3.10.10\lib\install.js:312:7
97446 verbose stack     at LOOP (C:\Users\cc21\.webclipse\npm\3.10.10\node_modules\slide\lib\chain.js:7:26)
97446 verbose stack     at C:\Users\cc21\.webclipse\npm\3.10.10\node_modules\slide\lib\chain.js:18:7
97446 verbose stack     at C:\Users\cc21\.webclipse\npm\3.10.10\lib\install\and-ignore-errors.js:7:15
97446 verbose stack     at Function.ls.fromTree (C:\Users\cc21\.webclipse\npm\3.10.10\lib\ls.js:112:3)
97446 verbose stack     at C:\Users\cc21\.webclipse\npm\3.10.10\lib\install.js:707:8
97446 verbose stack     at C:\Users\cc21\.webclipse\npm\3.10.10\node_modules\iferr\index.js:13:50
97446 verbose stack     at C:\Users\cc21\.webclipse\npm\3.10.10\lib\install\deps.js:175:5
97446 verbose stack     at LOOP (C:\Users\cc21\.webclipse\npm\3.10.10\node_modules\slide\lib\chain.js:7:26)
97447 verbose cwd C:\Workspacelatesteclipse\vlrclient
97448 error Windows_NT 10.0.14393
97449 error argv "C:\\Users\\cc21\\.webclipse\\nodejs\\7.10.1\\node.exe" "C:\\Users\\cc21\\.webclipse\\npm\\3.10.10\\bin\\npm-cli.js" "install" "@angular/cli@1.4.9"
97450 error node v7.10.1
97451 error npm  v3.10.10
97452 error Callback called more than once.
97453 error If you need help, you may report this error at:
97453 error     <https://github.com/npm/npm/issues>
97454 verbose exit [ 1, true ]

**Comment by VenkatJandhyam** [comment]
[npm-debug.log](https://github.com/npm/npm/files/1508202/npm-debug.log)
