### ISSUE TITLE
Tried to set npm config for "strict-ssl = false", but It was overridden with true value.

### ISSUE THREAD

**Issue by prozanne** [npm/npm#19268]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?
I just wanted to install grunt module globally.
But It threw below errors.
I answered at "#### How can the CLI team reproduce the problem?"

#### How can the CLI team reproduce the problem?
When I just typed "npm install -g grunt" via cli.
It threw those errors. (Sorry for that I can't upload the file)
npm ERR! registry error parsing json
npm ERR! SyntaxError: Unexpected token <
npm ERR! <HTML><HEAD>
npm ERR! <TITLE>Access Denied</TITLE>
npm ERR! </HEAD>
npm ERR! <BODY>
npm ERR! <FONT face="Helvetica">
npm ERR! <big><strong></strong></big><BR>
npm ERR! </FONT>
npm ERR! <blockquote>
npm ERR! <TABLE border=0 cellPadding=1 width="80%">
npm ERR! <TR><TD>
npm ERR! <FONT face="Helvetica">
npm ERR! <big>Access Denied (policy_denied)</big>
npm ERR! <BR>
npm ERR! <BR>
npm ERR! </FONT>
npm ERR! </TD></TR>
npm ERR! <TR><TD>
npm ERR! <FONT face="Helvetica">
npm ERR! Your system policy has denied access to the requested URL.
npm ERR! </FONT>
npm ERR! </TD></TR>
npm ERR! <TR><TD>
npm ERR! <FONT face="Helvetica">
npm ERR! 
npm ERR! </FONT>
npm ERR! </TD></TR>
npm ERR! <TR><TD>
npm ERR! <FONT face="Helvetica" SIZE=2>
npm ERR! <BR>
npm ERR! For assistance, contact below.<BR>
npm ERR! </FONT>
npm ERR! </TD></TR>
npm ERR! </TABLE>
npm ERR! </blockquote>
npm ERR! </FONT>
npm ERR! </BODY></HTML>
npm ERR! 
npm ERR!     at Object.parse (native)
npm ERR!     at RegClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:266:23)
npm ERR!     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:238:65)
npm ERR!     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:123:22)
npm ERR!     at Request.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:893:14)
npm ERR!     at Request.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:844:12)
npm ERR!     at IncomingMessage.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:938:16
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 2.6.32-358.el6.x86_64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "grunt"
npm ERR! cwd /var/lib/jenkins/jobs/MeerCATT/workspace
npm ERR! node -v v0.10.30
npm ERR! npm -v 1.4.21
npm ERR! type unexpected_token
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /var/lib/jenkins/jobs/MeerCATT/workspace/npm-debug.log
npm ERR! not ok code 0

*For reference, I am under the proxy.

### supporting information:

 - `npm -v` prints: 1.4.21
 - `node -v` prints: v0.10.30
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux (CentOS 6.4)
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by prozanne** [comment]
When I typed "npm config list -g",
Eventhough I set strict-ssl to false, But It overriden by true.

; strict-ssl = true (overridden)

**Comment by kenany** [comment]
Does this also occur with newer versions of Node.js and `npm`? Your current versions are years old, and are no longer supported.

**Comment by kratipantjoshi** [comment]
My npm version is 5.6.0 and the strict-ssl value is overridden to 'true'.
How can I set it to false?
 When i am trying to install gulp, I am getting this error:

$ npm install -g gulp
npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR! network request to https://registry.npmjs.org/gulp failed, reason: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
