### ISSUE TITLE
pacote using git does not respect --unsafe-perm

### ISSUE THREAD

**Issue by bradjc** [npm/npm#19299]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

When running `npm` as root with `--unsafe-perm` and trying to install a node package from github, `git` seems to be invoked not as `root` causing the install to fail.

Error message:

```
$ sudo npm i https://github.com/stevemao/left-pad --unsafe-perm
npm ERR! code 1
npm ERR! Command failed: /usr/bin/git clone --depth=1 -q -b master https://github.com/stevemao/left-pad.git /home/bradjc/.npm/_cacache/tmp/git-clone-275f5b60
npm ERR! /home/bradjc/.npm/_cacache/tmp/git-clone-275f5b60/.git: Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/bradjc/.npm/_logs/2017-12-01T22_51_51_400Z-debug.log
```

```
$ cat /home/bradjc/.npm/_logs/2017-12-01T22_51_51_400Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'i',
1 verbose cli   'https://github.com/stevemao/left-pad',
1 verbose cli   '--unsafe-perm' ]
2 info using npm@5.5.1
3 info using node@v8.6.0
4 verbose npm-session b7a0adb3118be2a9
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData error for git+https://github.com/stevemao/left-pad.git Command failed: /usr/bin/git clone --depth=1 -q -b master https://github.com/stevemao/left-pad.git /home/bradjc/.npm/_cacache/tmp/git-clone-275f5b60
7 silly fetchPackageMetaData /home/bradjc/.npm/_cacache/tmp/git-clone-275f5b60/.git: Permission denied
8 verbose stack Error: Command failed: /usr/bin/git clone --depth=1 -q -b master https://github.com/stevemao/left-pad.git /home/bradjc/.npm/_cacache/tmp/git-clone-275f5b60
8 verbose stack /home/bradjc/.npm/_cacache/tmp/git-clone-275f5b60/.git: Permission denied
8 verbose stack
8 verbose stack     at ChildProcess.exithandler (child_process.js:271:12)
8 verbose stack     at emitTwo (events.js:125:13)
8 verbose stack     at ChildProcess.emit (events.js:213:7)
8 verbose stack     at maybeClose (internal/child_process.js:927:16)
8 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
9 verbose cwd /home/bradjc/temp/rootest
10 verbose Linux 4.10.0-40-generic
11 verbose argv "/usr/bin/node" "/usr/bin/npm" "i" "https://github.com/stevemao/left-pad" "--unsafe-perm"
12 verbose node v8.6.0
13 verbose npm  v5.5.1
14 error code 1
15 error Command failed: /usr/bin/git clone --depth=1 -q -b master https://github.com/stevemao/left-pad.git /home/bradjc/.npm/_cacache/tmp/git-clone-275f5b60
15 error /home/bradjc/.npm/_cacache/tmp/git-clone-275f5b60/.git: Permission denied
16 verbose exit [ 1, true ]
```

#### How can the CLI team reproduce the problem?

```
$ sudo mkdir node_modules
$ sudo npm i https://github.com/stevemao/left-pad --unsafe-perm
```

It is important this module isn't cached anywhere.

A quick hack that allows the package to install is to force git to run as user 0.

```diff
diff --git a/node_modules/pacote/lib/util/git.js b/node_modules/pacote/lib/util/git.js
index a6162ceeb..9e234409e 100644
--- a/node_modules/pacote/lib/util/git.js
+++ b/node_modules/pacote/lib/util/git.js
@@ -194,6 +194,8 @@ function mkOpts (_gitOpts, opts) {
   if (+opts.gid && !isNaN(opts.gid)) {
     gitOpts.gid = +opts.gid
   }
+       gitOpts.uid = 0;
+       gitOpts.gid = 0;
   Object.assign(gitOpts, _gitOpts)
   return gitOpts
 }
```

### supporting information:

 - `npm -v` prints: 5.5.1
 - `node -v` prints: v8.6.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by zkat** [comment]
This does seem like something that could be submitted to [pacote](https://npm.im/pacote)!

**Comment by bradjc** [comment]
It seems related to https://github.com/zkat/pacote/issues/105 but I'm not sure if npm is calling pacote correctly and it is not calling `git` correctly or if npm is passing the wrong arguments to pacote somehow.
