### ISSUE TITLE
Cannot find module 'realize-package-specifier'

### ISSUE THREAD

**Issue by rethinkautismdev** [npm/npm#19295]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
[npm-debug.log](https://github.com/npm/npm/files/1522491/npm-debug.log)
trying to install angular from cli on mac
#### How can the CLI team reproduce the problem?
npm install -g @angular/cli
node -v6.2.0
npm -v 3.8.9

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by rethinkautismdev** [comment]
npm install -g @angupar/cli

**Comment by mdo5004** [comment]
I'm getting the same error message when I try to re-install node packages.

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'install' ]
2 info using npm@3.10.10
3 info using node@v6.11.1
4 verbose stack Error: Cannot find module 'realize-package-specifier'
4 verbose stack     at Function.Module._resolveFilename (module.js:469:15)
4 verbose stack     at Function.Module._load (module.js:417:25)
4 verbose stack     at Module.require (module.js:497:17)
4 verbose stack     at require (internal/module.js:20:19)
4 verbose stack     at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/install/deps.js:11:31)
4 verbose stack     at Module._compile (module.js:570:32)
4 verbose stack     at Object.Module._extensions..js (module.js:579:10)
4 verbose stack     at Module.load (module.js:487:32)
4 verbose stack     at tryModuleLoad (module.js:446:12)
4 verbose stack     at Function.Module._load (module.js:438:3)
5 verbose cwd /Users/mdo5004/Development/code/react-firebase-app
6 error Darwin 16.7.0
7 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
8 error node v6.11.1
9 error npm  v3.10.10
10 error code MODULE_NOT_FOUND
11 error Cannot find module 'realize-package-specifier'
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]

```

**Comment by JeffML** [comment]
Why is this going to my user folder, instead of package.json where I am running?

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/opt/local/bin/npm', 'run', 'dev' ]
2 info using npm@3.10.10
3 info using node@v6.11.2
4 verbose config Skipping project config: /Users/jeff.l/.npmrc. (matches userconfig)
5 verbose stack Error: ENOENT: no such file or directory, open '/Users/jeff.l/package.json'
5 verbose stack     at Error (native)
6 verbose cwd /Users/jeff.l/Documents/workspace/responsive-web-design
7 error Darwin 16.7.0
8 error argv "/usr/local/bin/node" "/opt/local/bin/npm" "run" "dev"
9 error node v6.11.2
10 error npm  v3.10.10
11 error path /Users/jeff.l/package.json
12 error code ENOENT
13 error errno -2
14 error syscall open
15 error enoent ENOENT: no such file or directory, open '/Users/jeff.l/package.json'
16 error enoent ENOENT: no such file or directory, open '/Users/jeff.l/package.json'
16 error enoent This is most likely not a problem with npm itself
16 error enoent and is related to npm not being able to find a file.
17 verbose exit [ -2, true ]

**Comment by JeffML** [comment]
more info:

jeff.l@Jeffs-MacBook-Pro:~/responsive/RWD (jml_moreAddressBook *=)$ npm run testServer

> responsive_web_server@1.0.0 testServer /Users/jeff.l/Documents/workspace/responsive-web-design/RWD
> babel-node ./responsive.js nocluster

environment is: test
info: couchdb host=http://test.mavericklabel.com:5984
info: nano-wrapper: setting global DB: {"config":{"url":"http://test.mavericklabel.com:5984","db":"cms"},"multipart":{},"attachment":{},"server":{"config":{"url":"http://test.mavericklabel.com:5984","requestDefaults":{"jar":false}},"db":{"replication":{}}},"replication":{}}
info: couchdb=http://test.mavericklabel.com:5984
info: ---------------------------------
info: running node version: v6.11.2
info: ---------------------------------
info: primary dbms host=172.31.59.99
info: primary db=maverick
info: primary couchdb=http://test.mavericklabel.com:5984
{ __dirname: '/Users/jeff.l/Documents/workspace/responsive-web-design/RWD/routes/GraphQL/client' }
initializing dinkus
initializing doofus
info: isClustered: false; isCompressed: true
minify temp dir is /var/folders/gg/9vr56c292yqg53lb2567zq280009sk/T
(node:3203) DeprecationWarning: sys is deprecated. Use util instead.
info: Apache port # is (by guess or by golly)8180
info: minify completed
res.locals.domain is '', protocol is http, hostname is [::1], url is /json/version
info: NOT FOUND /json/version?
res.locals.domain is '', protocol is http, hostname is [::1], url is /json
info: NOT FOUND /json?

**Comment by JeffML** [comment]
npm cache clean
npm ERR! Darwin 16.7.0
npm ERR! argv "/usr/local/bin/node" "/opt/local/bin/npm" "cache" "clean"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'fstream'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jeff.l/Documents/workspace/responsive-web-design/RWD/npm-debug.log

**Comment by JacobJT** [comment]
Was this ever solved?

**Comment by DanielRuf** [comment]
> Was this ever solved?

This was an old thread. Probably not directly related or was another technical incident.
