### ISSUE TITLE
"npm install" Failed with newtork connectivity

### ISSUE THREAD

**Issue by EngSayed** [npm/npm#19310]
#### I'm opening this issue because:

  - [x] npm is failing while installing with network connectivity error while I do not have any proxy.

#### What's going wrong?
Every time I run command "npm install -g @angular/cli" It fails with the following error:

npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! network request to https://registry.npmjs.org/parseuri failed, reason: read ECONNRESET
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

I do not have proxy.
#### How can the CLI team reproduce the problem?
 Here is the end of the debug log:

13599 silly pacote core-js@https://registry.npmjs.org/core-js/-/core-js-2.5.1.tgz extracted to C:\Users\...\AppData\Roaming\npm\node_modules\.staging\core-js-57b4c381 by content address 2360ms
13600 silly pacote fsevents@https://registry.npmjs.org/fsevents/-/fsevents-1.1.3.tgz extracted to C:\Users\...\AppData\Roaming\npm\node_modules\.staging\fsevents-3b8272c9 by content address 3805ms
13601 silly pacote rxjs@https://registry.npmjs.org/rxjs/-/rxjs-5.5.3.tgz extracted to C:\Users\***\AppData\Roaming\npm\node_modules\.staging\rxjs-74286f31 by content address 5788ms
13602 verbose unlock done using C:\Users\...\AppData\Roaming\npm-cache\_locks\staging-cf339285c26ef046.lock for C:\Users\...\AppData\Roaming\npm\node_modules\.staging
13603 verbose type system
13604 verbose stack FetchError: request to https://registry.npmjs.org/send/-/send-0.16.1.tgz failed, reason: read ECONNRESET
13604 verbose stack     at ClientRequest.req.on.err (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\node-fetch-npm\src\index.js:68:14)
13604 verbose stack     at emitOne (events.js:116:13)
13604 verbose stack     at ClientRequest.emit (events.js:211:7)
13604 verbose stack     at TLSSocket.socketErrorListener (_http_client.js:387:9)
13604 verbose stack     at emitOne (events.js:116:13)
13604 verbose stack     at TLSSocket.emit (events.js:211:7)
13604 verbose stack     at emitErrorNT (internal/streams/destroy.js:64:8)
13604 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:138:11)
13604 verbose stack     at process._tickCallback (internal/process/next_tick.js:180:9)
13605 verbose cwd C:\Users\...
13606 verbose Windows_NT 10.0.16299
13607 verbose argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@angular/cli"
13608 verbose node v8.9.1
13609 verbose npm  v5.5.1
13610 error code ECONNRESET
13611 error errno ECONNRESET
13612 error network request to https://registry.npmjs.org/send/-/send-0.16.1.tgz failed, reason: read ECONNRESET
13613 error network This is a problem related to network connectivity.
13613 error network In most cases you are behind a proxy or have bad network settings.
13613 error network
13613 error network If you are behind a proxy, please make sure that the
13613 error network 'proxy' config is set properly.  See: 'npm help config'
13614 verbose exit [ 1, true ]

### supporting information:

 - Windows 10
 - Network issues:
   - [x] I don't use a proxy, and my internet is 120 Mb/s.
 - Container:
   - [x] I develop using Visual Studio Code on Windows.

**Comment by hkoelewijn** [comment]
I am having exactly the same issue. It just started popping up the last couple of days. My network setup did not change. Windows 10, npm install from powershell window

**Comment by JerryDoubleU** [comment]
I have the same problem - clean project, no firewall. I can download the specified url in the browser without a smallest problem. Node v9.2.0, Npm 5.5.1.
Regular windows 10 command line. The download hangs for quite a while (maybe around a minute) and then it prints similar output.

**Comment by EngSayed** [comment]
I uninstalled **Node.js** (Version 8.9.1) then downloaded and installed **Node.js** version **7.10.1** and installed Angular CLI successfully.
Looks like Node.js v 8.9.1 has a problem.

**Comment by JerryDoubleU** [comment]
I wouldn’t close this issue - rolling back to previous version isn’t a solution in my opinion.

**Comment by JerryDoubleU** [comment]
Thanks a lot ;)

**Comment by rflw** [comment]
I noticed that changing **registry** from [https://registry.npmjs.org/](https://registry.npmjs.org/) to [http://registry.npmjs.org/](http://registry.npmjs.org/) using 

`npm config set registry http://registry.npmjs.org/` 

solves the problem but that's not safe for production. 
Today I updated node & npm to the latest version and noticed the same problem with proxy but I'm not behind proxy.
I checked ping to both http/https registry url and both work so there is something wrong with npm itself.

**Comment by JerryDoubleU** [comment]
Actually, when I changed to http some other packages failed. The solution was switching to yarn ;).
