### ISSUE TITLE
error code ELIFECYCLE

### ISSUE THREAD

**Issue by kaoshen** [npm/npm#19326]
I'm opening this issue because:
  - [+ ] npm is doing something I don't understand.

What's going wrong?
I create a demo follow create-react-app.
When npm start  the project:

npm ERR! code ELIFECYCLE
npm ERR! errno 3221225477
npm ERR! myapp@0.1.0 start: `react-scripts start`
npm ERR! Exit status 3221225477
npm ERR!
npm ERR! Failed at the myapp@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

### supporting information:

 - `npm -v` prints:  v5.0.3
 - `node -v` prints: v8.1.4
 - `npm config get registry` prints:
 - Windows: Win10

#### The error log

   info it worked if it ends with ok
 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
 verbose cli   'start' ]
 info using npm@5.0.3
 info using node@v8.1.4
 verbose run-script [ 'prestart', 'start', 'poststart' ]
 info lifecycle myappspace@0.1.0~prestart: myappspace@0.1.0
 silly lifecycle myappspace@0.1.0~prestart: no script for prestart, continuing
 info lifecycle myappspace@0.1.0~start: myappspace@0.1.0
 verbose lifecycle myappspace@0.1.0~start: unsafe-perm in lifecycle true
 verbose lifecycle myappspace@0.1.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;D:\myappspace\node_modules\.bin;"C:\Program Files\Java\jdk1.8.0_45\bin;";C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;D:\Program Files\TortoiseSVN\bin;d:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;C:\Users\Administrator\AppData\Roaming\npm
 verbose lifecycle myappspace@0.1.0~start: CWD: D:\myappspace
 silly lifecycle myappspace@0.1.0~start: Args: [ '/d /s /c', 'react-scripts start' ]
 silly lifecycle myappspace@0.1.0~start: Returned: code: 3221225477  signal: null
 info lifecycle myappspace@0.1.0~start: Failed to exec start script
 verbose stack Error: myappspace@0.1.0 start: `react-scripts start`
 verbose stack Exit status 3221225477
verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:283:16)
verbose stack     at emitTwo (events.js:125:13)
verbose stack     at EventEmitter.emit (events.js:213:7)
 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
verbose stack     at emitTwo (events.js:125:13)
 verbose stack     at ChildProcess.emit (events.js:213:7)
 verbose stack     at maybeClose (internal/child_process.js:897:16)
 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
 verbose pkgid myappspace@0.1.0
 verbose cwd D:\myappspace
 verbose Windows_NT 10.0.15063
 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
 verbose node v8.1.4
 verbose npm  v5.0.3
 error code ELIFECYCLE
 error errno 3221225477
 error myappspace@0.1.0 start: `react-scripts start`
 error Exit status 3221225477
 error Failed at the myappspace@0.1.0 start script.
 error This is probably not a problem with npm. There is likely additional logging output above.
 verbose exit [ 3221225477, true ]

# Help

**Comment by BusbyActual** [comment]
This may be a windows related permissions issue.

Try running this and let me know if you get a node prompt.
> cmd /d /s /c node

Also,

I'm running these versions and don't experience the issue on windows try updating and or running your command prompt as administrator.
npm:  5.2.0
node: v8.2.1

**Comment by SonGokuSSGSS5** [comment]
@BusbyActual 

 I tried out what you said and Yes i did get a node prompt 

my npm is running on version -> 6.0.1
my node is running on version -> 8.11.2

I tried it using both node.js and cmd seperately but of no avail.
