### ISSUE TITLE
npm 5.5.1 fails for node 8.9.2 on OSX 10.3.1

### ISSUE THREAD

**Issue by cookie-ag** [npm/npm#19342]
#### I'm opening this issue because:

  - [X ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ X] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I am using nvm 0.33.6, my latest npm is failing to throw the error: 

```
TypeError: Cannot read property '0' of undefined
```

Here is a detailed log:

```
3000 verbose unlock done using /Users/system/.npm/_locks/staging-e2c6a70cd09d4dd4.lock for /Users/system/Library/app/node_modules/.staging
3001 warn grunt-mongo-backup@0.0.2 requires a peer of grunt@~0.4.5 but none is installed. You must install peer dependencies yourself.
3002 warn grunt-mongoimport@0.1.7 requires a peer of grunt@~0.4.1 but none is installed. You must install peer dependencies yourself.
3003 verbose stack TypeError: Cannot read property '0' of undefined
3003 verbose stack     at rmStuff (/Users/system/.nvm/versions/node/v8.9.2/lib/node_modules/npm/lib/unbuild.js:61:24)
3003 verbose stack     at tryCatcher (/Users/system/.nvm/versions/node/v8.9.2/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
3003 verbose stack     at ret (eval at makeNodePromisifiedEval (/Users/system/.nvm/versions/node/v8.9.2/lib/node_modules/npm/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:13:39)
3003 verbose stack     at lifecycle.then.then (/Users/system/.nvm/versions/node/v8.9.2/lib/node_modules/npm/lib/install/action/unbuild.js:12:12)
3003 verbose stack     at tryCatcher (/Users/system/.nvm/versions/node/v8.9.2/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
3003 verbose stack     at Promise._settlePromiseFromHandler (/Users/system/.nvm/versions/node/v8.9.2/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
3003 verbose stack     at Promise._settlePromise (/Users/system/.nvm/versions/node/v8.9.2/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
3003 verbose stack     at Promise._settlePromise0 (/Users/system/.nvm/versions/node/v8.9.2/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
3003 verbose stack     at Promise._settlePromises (/Users/system/.nvm/versions/node/v8.9.2/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
3003 verbose stack     at Promise._fulfill (/Users/system/.nvm/versions/node/v8.9.2/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:638:18)
3003 verbose stack     at /Users/system/.nvm/versions/node/v8.9.2/lib/node_modules/npm/node_modules/bluebird/js/release/nodeback.js:42:21
3003 verbose stack     at <anonymous>
3004 verbose cwd /Users/system/Library/app
3005 verbose Darwin 17.2.0
3006 verbose argv "/Users/system/.nvm/versions/node/v8.9.2/bin/node" "/Users/system/.nvm/versions/node/v8.9.2/bin/npm" "install" "synchronize-iterate" "--save"
3007 verbose node v8.9.2
3008 verbose npm  v5.5.1
3009 error Cannot read property '0' of undefined
```

#### How can the CLI team reproduce the problem?

Simply install nvm v 0.33.6 on a OSX 10.3.1 (XCode 9.2) and do `npm use lts/*`

### supporting information:

 - `npm -v` prints: 5.5.1
 - `node -v` prints: 8.9.2
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: OSX 10.3.1 (XCode 9.2
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by pdesmarais** [comment]
Fell upon this issue (won't be able to help you but...)

Are you sure you specified the right Mac OS X version?

10.3.1 was released in 2003 and has been unsupported since 2007.

Also, XCode 9.2 requires AT LEAST Mac OX X 10.12.6...

**Comment by cookie-ag** [comment]
@pdesmarais Apologies, its MacOS High Sierra 10.13.1

**Comment by nsantini** [comment]
had the same issue, upgrading npm to latest fixed it:
[sudo] npm install -g npm@latest

**Comment by andreicioban** [comment]
Running `npm cache verify` fixed this for me.
