### ISSUE TITLE
NPN Crashing - Error: write EPIPE

### ISSUE THREAD

**Issue by mercenaruss** [npm/npm#19350]
#### I'm opening this issue because:

  - [# ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [# ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
App is keeping on rebooting
#### How can the CLI team reproduce the problem?

0 info it worked if it ends with ok
1 verbose cli [ '/home/nodeproxy/.nvm/versions/node/v6.9.2/bin/node',
1 verbose cli   '/home/nodeproxy/.nvm/versions/node/v6.9.2/bin/npm',
1 verbose cli   'ls',
1 verbose cli   '--json',
1 verbose cli   '--production' ]
2 info using npm@3.10.9
3 info using node@v6.9.2
4 verbose exit [ 0, true ]
5 verbose stack Error: write EPIPE
5 verbose stack     at exports._errnoException (util.js:1022:11)
5 verbose stack     at WriteWrap.afterWrite (net.js:801:14)
6 verbose cwd /home/nodeproxy/xmr-node-proxy
7 error Linux 4.10.0-40-generic
8 error argv "/home/nodeproxy/.nvm/versions/node/v6.9.2/bin/node" "/home/nodeproxy/.nvm/versions/node/v6.9.2/bin/npm" "ls" "--json" "--production"
9 error node v6.9.2
10 error npm  v3.10.9
11 error code EPIPE
12 error errno EPIPE
13 error syscall write
14 error write EPIPE
15 error If you need help, you may report this error at:
15 error     <https://github.com/npm/npm/issues>
16 verbose exit [ 1, true ]

### supporting information:

 - `npm -v` prints: 3.10.9
 - `node -v` prints: v6.9.2
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux, Ubuntu 16.04 
 - Network issues:
   - Geographic location where npm was run: Africa,Nigeria,Abuja

**Comment by jamesbond000007** [comment]
Can confirm, have same issue, it don't looks like something goes wrong, but service that i start provide huge amount of generated issues in format like "npm-debug.log.1009036045" and generated them every half minutes.

ubuntu:~/nodejs-pool$ cat npm-debug.log.1009036045 
0 info it worked if it ends with ok
1 verbose cli [ '/home/gw/.nvm/versions/node/v6.9.2/bin/node',
1 verbose cli   '/home/gw/.nvm/versions/node/v6.9.2/bin/npm',
1 verbose cli   'ls',
1 verbose cli   '--json',
1 verbose cli   '--production' ]
2 info using npm@3.10.9
3 info using node@v6.9.2
4 verbose exit [ 0, true ]
5 verbose stack Error: write EPIPE
5 verbose stack     at exports._errnoException (util.js:1022:11)
5 verbose stack     at WriteWrap.afterWrite (net.js:801:14)
6 verbose cwd /home/gw/nodejs-pool
7 error Linux 4.4.0-101-generic
8 error argv "/home/gw/.nvm/versions/node/v6.9.2/bin/node" "/home/gw/.nvm/versions/node/v6.9.2/bin/npm" "ls" "--json" "--production"
9 error node v6.9.2
10 error npm  v3.10.9
11 error code EPIPE
12 error errno EPIPE
13 error syscall write
14 error write EPIPE
15 error If you need help, you may report this error at:
15 error     <https://github.com/npm/npm/issues>
16 verbose exit [ 1, true ]

Yes, this also on ubuntu 16.04 ! I am not affiliated with topic starter, but also interested in: 
ubuntu:~/nodejs-pool$ npm -v
3.10.9
ubuntu:~/nodejs-pool$ node -v
v6.9.2
ubuntu:~/nodejs-pool$ npm config get registry
https://registry.npmjs.org/
ubuntu:~/nodejs-pool$

Tried understand what caused exception by this lines
5 verbose stack     at exports._errnoException (util.js:1022:11)
5 verbose stack     at WriteWrap.afterWrite (net.js:801:14)

but found at:
~/.nvm/versions/node/v6.9.2/lib/node_modules/npm/node_modules/npm-registry-client/node_modules/concat-stream/node_modules/readable-stream/node_modules/core-util-is/

float.patch from 06/23/2016

where function was cut'ed by patch
-var uv;
-exports._errnoException = function(err, syscall) {
-  if (isUndefined(uv)) uv = process.binding('uv');
-  var errname = uv.errname(err);
-  var e = new Error(syscall + ' ' + errname);
-  e.code = errname;
-  e.errno = errname;
-  e.syscall = syscall;
-  return e;
-};

May be it mean that code from xmr-node-proxy not properly designed or i mistaken?
