### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by liuyepiaoxiang** [npm/npm#19365]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### How can the CLI team reproduce the problem?

```
Unhandled rejection RangeError: Maximum call stack size exceeded
    at exports.create (C:\Users\TUTUZHU\AppData\Roaming\nvm\v8.1.0\node_modules\                        npm\lib\install\node.js:33:25)
    at C:\Users\TUTUZHU\AppData\Roaming\nvm\v8.1.0\node_modules\npm\lib\install\                        node.js:36:14
    at Array.forEach (native)
    at exports.create (C:\Users\TUTUZHU\AppData\Roaming\nvm\v8.1.0\node_modules\                        npm\lib\install\node.js:33:25)
    at C:\Users\TUTUZHU\AppData\Roaming\nvm\v8.1.0\node_modules\npm\lib\install\                        node.js:36:14
    at Array.forEach (native)
    at exports.create (C:\Users\TUTUZHU\AppData\Roaming\nvm\v8.1.0\node_modules\                        npm\lib\install\node.js:33:25)
    at normalizeTree (C:\Users\TUTUZHU\AppData\Roaming\nvm\v8.1.0\node_modules\n                        pm\lib\install.js:377:5)
    at Array.forEach (native)
    at normalizeTree (C:\Users\TUTUZHU\AppData\Roaming\nvm\v8.1.0\node_modules\n                        pm\lib\install.js:379:19)
    at Array.forEach (native)
    at normalizeTree (C:\Users\TUTUZHU\AppData\Roaming\nvm\v8.1.0\node_modules\n                        pm\lib\install.js:379:19)
    at Array.forEach (native)
    at normalizeTree (C:\Users\TUTUZHU\AppData\Roaming\nvm\v8.1.0\node_modules\n                        pm\lib\install.js:379:19)
    at Array.forEach (native)
    at normalizeTree (C:\Users\TUTUZHU\AppData\Roaming\nvm\v8.1.0\node_modules\n                        pm\lib\install.js:379:19)
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\TUTUZHU\AppData\Roaming\npm-cache\_logs\2017-12-10T14_32_5                        8_207Z-debug.log
```
### supporting information:

 - `npm -v` prints: 5.0.3
 - `node -v` prints: 8.1.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?:  Windows
 - Network issues:
   - Geographic location where npm was run:
   - [ x] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [x ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by Maxitk** [comment]
the same issue,and i turned to use yarn

**Comment by setur52** [comment]
Get the same problem
- npm -v prints: 5.6.0
- node -v prints: 8.9.1

I downgrade to 5.5.1 version  and it works now. 5.6.0 version need to be fixed.
