### ISSUE TITLE
Publish failing with 'User not found: <package-name>'

### ISSUE THREAD

**Issue by rickbsgu** [npm/npm#19387]
Trying to publish a package, I get this set of errors:

```
npm ERR! publish Failed PUT 404
npm ERR! code E404
npm ERR! 404 User not found : fsm-manager
...
```
'fsm-manager' is the package I'm trying to publish, but it seems to see the package
name as the username?

Here's my package.json:
```
{
  "name": "fsm-manager",
  "version": "0.1.0",
  "description": "Allows composing FSM's.  Also provides a built-in 'timeout' transition",
  "directories": {
    "test": "test"
  },
  "main": "./dist/fsm_manager.js",
  "scripts": {
    "build": "babel src/fsm_manager.js --nobabelrc --presets=env,stage-3 --out-file dist/fsm_manager.js",
    "test": "echo \"Error: no test specified\" && exit 1",
    "prepublishOnly": "npm run build"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/Aphorica/fsm-manager.git"
  },
  "keywords": [
    "Vue.js",
    "Finite State Machine",
    "FSM",
    "Composition",
    "Javascript"
  ],
  "author": {
    "name": "Rick Berger",
    "email": "rickb@aphorica.com"
  },
  "maintainers": [
    {
      "name": "Rick Berger",
      "email": "rickb@aphorica.com"
    }
  ],
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/aphorica/fsm-manager/issues"
  },
  "homepage": "https://github.com/aphorica/fsm-manager#readme",
  "devDependencies": {
    "babel-cli": "^6.26.0",
    "babel-preset-env": "^1.3.2",
    "babel-preset-stage-3": "^6.24.1"
  }
}

```

And here is my .npmrc  (password cleared):
```
init.author.name=Rick Berger
init.author.email=rickb@aphorica.com
init.author.url=http://aphorica.com
//registry.npmjs.org/:_password="(cleared)"
//registry.npmjs.org/:username=rickbsgu
//registry.npmjs.org/:email=rickb@aphorica.com
//registry.npmjs.org/:always-auth=false
```

What's up?

**Comment by rickbsgu** [comment]
Attached is the log output from the 'publish' attempt:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/8.5.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'publish' ]
2 info using npm@5.6.0
3 info using node@v8.5.0
4 verbose npm-session d5ddc18269764b72
5 verbose publish [ '.' ]
6 info lifecycle fsm-manager@0.1.0~prepublish: fsm-manager@0.1.0
7 info lifecycle fsm-manager@0.1.0~prepare: fsm-manager@0.1.0
8 info lifecycle fsm-manager@0.1.0~prepublishOnly: fsm-manager@0.1.0
9 verbose lifecycle fsm-manager@0.1.0~prepublishOnly: unsafe-perm in lifecycle true
10 verbose lifecycle fsm-manager@0.1.0~prepublishOnly: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/Shared/dev/web/fsm-manager/node_modules/.bin:/usr/local/sbin:/Users/rickb/bin:/Users/Shared/devtools/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/git/bin:/Users/Shared/devtools/dart-sdk/bin:~/.pub-cache/bin:/Users/Shared/devtools/dartium/Chromium.app/Contents/MacOS:/Applications/Google Chrome.app/Contents/MacOS
11 verbose lifecycle fsm-manager@0.1.0~prepublishOnly: CWD: .
12 silly lifecycle fsm-manager@0.1.0~prepublishOnly: Args: [ '-c', 'npm run build' ]
13 silly lifecycle fsm-manager@0.1.0~prepublishOnly: Returned: code: 0  signal: null
14 info lifecycle fsm-manager@0.1.0~prepack: fsm-manager@0.1.0
15 info lifecycle fsm-manager@0.1.0~postpack: fsm-manager@0.1.0
16 verbose getPublishConfig undefined
17 silly mapToRegistry name fsm-manager
18 silly mapToRegistry using default registry
19 silly mapToRegistry registry https://registry.npmjs.org/
20 silly mapToRegistry data { type: 'tag',
20 silly mapToRegistry   registry: true,
20 silly mapToRegistry   where: undefined,
20 silly mapToRegistry   raw: 'fsm-manager',
20 silly mapToRegistry   name: 'fsm-manager',
20 silly mapToRegistry   escapedName: 'fsm-manager',
20 silly mapToRegistry   scope: undefined,
20 silly mapToRegistry   rawSpec: '',
20 silly mapToRegistry   saveSpec: null,
20 silly mapToRegistry   fetchSpec: 'latest',
20 silly mapToRegistry   gitRange: undefined,
20 silly mapToRegistry   gitCommittish: undefined,
20 silly mapToRegistry   hosted: undefined }
21 silly mapToRegistry uri https://registry.npmjs.org/fsm-manager
22 verbose publish registryBase https://registry.npmjs.org/
23 silly publish uploading /var/folders/_j/x4dzd5bn0cj8kvpp2_qqqft80000gn/T/npm-21706-7e3e57b6/tmp/fromDir-5096be9a/package.tgz
15 info lifecycle fsm-manager@0.1.0~postpack: fsm-manager@0.1.0
16 verbose getPublishConfig undefined
17 silly mapToRegistry name fsm-manager
18 silly mapToRegistry using default registry
19 silly mapToRegistry registry https://registry.npmjs.org/
20 silly mapToRegistry data { type: 'tag',
20 silly mapToRegistry   registry: true,
20 silly mapToRegistry   where: undefined,
20 silly mapToRegistry   raw: 'fsm-manager',
20 silly mapToRegistry   name: 'fsm-manager',
20 silly mapToRegistry   escapedName: 'fsm-manager',
20 silly mapToRegistry   scope: undefined,
20 silly mapToRegistry   rawSpec: '',
20 silly mapToRegistry   saveSpec: null,
20 silly mapToRegistry   fetchSpec: 'latest',
20 silly mapToRegistry   gitRange: undefined,
20 silly mapToRegistry   gitCommittish: undefined,
20 silly mapToRegistry   hosted: undefined }
21 silly mapToRegistry uri https://registry.npmjs.org/fsm-manager
22 verbose publish registryBase https://registry.npmjs.org/
23 silly publish uploading /var/folders/_j/x4dzd5bn0cj8kvpp2_qqqft80000gn/T/npm-
21706-7e3e57b6/tmp/fromDir-5096be9a/package.tgz
24 verbose request uri https://registry.npmjs.org/fsm-manager
25 verbose request sending authorization for write operation
26 info attempt registry request try #1 at 10:28:08 AM
27 verbose request id 591253646b6b355d
28 http request PUT https://registry.npmjs.org/fsm-manager
29 http 404 https://registry.npmjs.org/fsm-manager
30 verbose headers { 'content-type': 'application/json',
30 verbose headers   'cache-control': 'max-age=0',
30 verbose headers   'content-length': '26',
30 verbose headers   'accept-ranges': 'bytes',
30 verbose headers   date: 'Thu, 14 Dec 2017 17:28:09 GMT',
30 verbose headers   via: '1.1 varnish',
30 verbose headers   connection: 'keep-alive',
30 verbose headers   'x-served-by': 'cache-bur17524-BUR',
30 verbose headers   'x-cache': 'MISS',
30 verbose headers   'x-cache-hits': '0',
30 verbose headers   'x-timer': 'S1513272488.455313,VS0,VE640' }
31 error publish Failed PUT 404
32 verbose stack Error: User not found : fsm-manager
32 verbose stack     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:314:12)
32 verbose stack     at RegClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:302:14)
32 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:216:14)
32 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:186:22)
32 verbose stack     at emitTwo (events.js:125:13)
32 verbose stack     at Request.emit (events.js:213:7)
32 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1163:10)
32 verbose stack     at emitOne (events.js:115:13)
32 verbose stack     at Request.emit (events.js:210:7)
32 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1085:12)
32 verbose stack     at Object.onceWrapper (events.js:314:30)
32 verbose stack     at emitNone (events.js:110:20)
32 verbose stack     at IncomingMessage.emit (events.js:207:7)
32 verbose stack     at endReadableNT (_stream_readable.js:1059:12)
32 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:138:11)
32 verbose stack     at process._tickCallback (internal/process/next_tick.js:180:9)
33 verbose statusCode 404
34 verbose pkgid fsm-manager
35 verbose cwd /Users/Shared/dev/web/fsm-manager
36 verbose Darwin 16.7.0
37 verbose argv "/usr/local/Cellar/node/8.5.0/bin/node" "/usr/local/bin/npm" "publish"
38 verbose node v8.5.0
39 verbose npm  v5.6.0
40 error code E404
41 error 404 User not found : fsm-manager
42 error 404
43 error 404 'fsm-manager' is not in the npm registry.
44 error 404 You should bug the author to publish it (or use the name yourself!)
45 error 404 Note that you can also install from a
46 error 404 tarball, folder, http url, or git url.
47 verbose exit [ 1, true ]
```

**Comment by rickbsgu** [comment]
Per Ibis Liven issue #19404, I did the same thing - created an account on the website and then logged in via the command line.  I was then able to publish.

Suggest you either fix the command line, or provide instructions to go to the website and scotch the 'adduser' command altogether.

**Comment by tbjgod** [comment]
I have an account on the 'https://www.npmjs.org' and logged in via the command line.
but still unable to publish. 

> 0 info it worked if it ends with ok
1 verbose cli [ 'C:\\tool\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\GOD\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'publish' ]
2 info using npm@5.6.0
3 info using node@v9.3.0
4 verbose npm-session ef1a743a49739165
5 verbose publish [ '.' ]
6 info lifecycle god_test@1.0.0~prepublish: god_test@1.0.0
7 info lifecycle god_test@1.0.0~prepare: god_test@1.0.0
8 info lifecycle god_test@1.0.0~prepublishOnly: god_test@1.0.0
9 info lifecycle god_test@1.0.0~prepack: god_test@1.0.0
10 info lifecycle god_test@1.0.0~postpack: god_test@1.0.0
11 verbose getPublishConfig undefined
12 silly mapToRegistry name god_test
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry http://registry.npmjs.org/
15 silly mapToRegistry data { type: 'tag',
15 silly mapToRegistry   registry: true,
15 silly mapToRegistry   where: undefined,
15 silly mapToRegistry   raw: 'god_test',
15 silly mapToRegistry   name: 'god_test',
15 silly mapToRegistry   escapedName: 'god_test',
15 silly mapToRegistry   scope: undefined,
15 silly mapToRegistry   rawSpec: '',
15 silly mapToRegistry   saveSpec: null,
15 silly mapToRegistry   fetchSpec: 'latest',
15 silly mapToRegistry   gitRange: undefined,
15 silly mapToRegistry   gitCommittish: undefined,
15 silly mapToRegistry   hosted: undefined }
16 silly mapToRegistry uri http://registry.npmjs.org/god_test
17 verbose publish registryBase http://registry.npmjs.org/
18 silly publish uploading C:\Users\GOD\AppData\Local\Temp\npm-5004-95256db4\tmp\fromDir-fd31fc7e\package.tgz
19 verbose request uri http://registry.npmjs.org/god_test
20 verbose request sending authorization for write operation
21 info attempt registry request try #1 at 17:29:59
22 verbose request id e74d1a53ee5993f9
23 http request PUT http://registry.npmjs.org/god_test
24 http 404 http://registry.npmjs.org/god_test
25 verbose headers { 'content-type': 'application/json',
25 verbose headers   'cache-control': 'max-age=0',
25 verbose headers   'content-length': '26',
25 verbose headers   'accept-ranges': 'bytes',
25 verbose headers   date: 'Tue, 19 Dec 2017 09:30:01 GMT',
25 verbose headers   via: '1.1 varnish',
25 verbose headers   connection: 'keep-alive',
25 verbose headers   'x-served-by': 'cache-hnd18726-HND',
25 verbose headers   'x-cache': 'MISS',
25 verbose headers   'x-cache-hits': '0',
25 verbose headers   'x-timer': 'S1513675801.740972,VS0,VE657' }
26 error publish Failed PUT 404
27 verbose stack Error: User not found : god_test
27 verbose stack     at makeError (C:\Users\GOD\AppData\Roaming\npm\node_modules\npm\node_modules\npm-registry-client\lib\request.js:314:12)
27 verbose stack     at RegClient.<anonymous> (C:\Users\GOD\AppData\Roaming\npm\node_modules\npm\node_modules\npm-registry-client\lib\request.js:302:14)
27 verbose stack     at Request._callback (C:\Users\GOD\AppData\Roaming\npm\node_modules\npm\node_modules\npm-registry-client\lib\request.js:216:14)
27 verbose stack     at Request.self.callback (C:\Users\GOD\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.js:186:22)
27 verbose stack     at Request.emit (events.js:159:13)
27 verbose stack     at Request.<anonymous> (C:\Users\GOD\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.js:1163:10)
27 verbose stack     at Request.emit (events.js:159:13)
27 verbose stack     at IncomingMessage.<anonymous> (C:\Users\GOD\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.js:1085:12)
27 verbose stack     at Object.onceWrapper (events.js:254:19)
27 verbose stack     at IncomingMessage.emit (events.js:164:20)
27 verbose stack     at endReadableNT (_stream_readable.js:1062:12)
27 verbose stack     at process._tickCallback (internal/process/next_tick.js:152:19)
28 verbose statusCode 404
29 verbose pkgid god_test
30 verbose cwd c:\xampp\htdocs\test\20171219\npm_publish_test
31 verbose Windows_NT 6.1.7601
32 verbose argv "C:\\tool\\nodejs\\node.exe" "C:\\Users\\GOD\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "publish"
33 verbose node v9.3.0
34 verbose npm  v5.6.0
35 error code E404
36 error 404 User not found : god_test
37 error 404
38 error 404 'god_test' is not in the npm registry.
39 error 404 You should bug the author to publish it (or use the name yourself!)
40 error 404 Note that you can also install from a
41 error 404 tarball, folder, http url, or git url.
42 verbose exit [ 1, true ]

**Comment by fisharebest** [comment]
It seems to me that the problem is caused by email verification.

The server won't accept `npm publish` from an unverified email address, and registering using `npm adduser` does not create/send a verfication email.

**Comment by marwahaha** [comment]
I think this should be fixed in npm-registry-client@8.5.1
