### ISSUE TITLE
I rebuilt reinstall node.js several times but can't resolve "npm ERR! Cannot find module 'internal/util/types'"..

### ISSUE THREAD

**Issue by ghost** [npm/npm#19431]
I rebuilt reinstall node.js several times, but i can't fix as following issue like as
" npm ERR! Cannot find module 'internal/util/types'"

D:\vuejs-md>npm install
npm ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Users\\RyanWolfe\\node.exe" "C:\\Users\\RyanWolfe\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v8.9.3
npm ERR! npm  v3.3.7
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'internal/util/types'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\vuejs-md\npm-debug.log

**Comment by zuborawka** [comment]
I have a same problem.

```
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'D:\\Program Files (x86)\\Nodist\\bin\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'update',
1 verbose cli   '-g',
1 verbose cli   'npm' ]
2 info using npm@3.5.3
3 info using node@v8.9.3
4 verbose stack Error: Cannot find module 'internal/util/types'
4 verbose stack     at Function.Module._resolveFilename (module.js:536:15)
4 verbose stack     at Function.Module._load (module.js:466:25)
4 verbose stack     at Module.require (module.js:579:17)
4 verbose stack     at require (internal/module.js:11:18)
4 verbose stack     at evalmachine.<anonymous>:31:26
4 verbose stack     at Object.<anonymous> (D:\Program Files (x86)\Nodist\bin\node_modules\npm\node_modules\cmd-shim\node_modules\graceful-fs\fs.js:11:1)
4 verbose stack     at Module._compile (module.js:635:30)
4 verbose stack     at Object.Module._extensions..js (module.js:646:10)
4 verbose stack     at Module.load (module.js:554:32)
4 verbose stack     at tryModuleLoad (module.js:497:12)
5 verbose cwd C:\Users\Satoshi
6 error Windows_NT 10.0.15063
7 error argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files (x86)\\Nodist\\bin\\node_modules\\npm\\bin\\npm-cli.js" "update" "-g" "npm"
8 error node v8.9.3
9 error npm  v3.5.3
10 error code MODULE_NOT_FOUND
11 error Cannot find module 'internal/util/types'
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]
```
