### ISSUE TITLE
Install only development dependencies results in missing nested dependencies

### ISSUE THREAD

**Issue by Siilwyn** [npm/npm#19443]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I would like to run some linting tasks in a CI environment and to speed up the job only install development dependencies. Expected `npm install --only=development` to do the job but it seems to be recursive, resulting in missing nested dependencies.

Not sure what is going on but to reproduce the problem at least one normal dependency needs to be listed in `package.json` and there also needs to be a `package-lock.json` present.

#### How can the CLI team reproduce the problem?
```
git clone git@github.com:Siilwyn/npm-dev-install-missing.git
cd npm-dev-install-missing
npm install --only=development
npm run lint
```

Will result in a dependency missing, in the example it returns: `Error: Cannot find module 'chalk'`.

### supporting information:
- `npm -v` prints: 5.5.1
- `node -v` prints: 8.9.3
- Linux

**Comment by maxpain** [comment]
Same problem

**Comment by Siilwyn** [comment]
Understand that installing only development dependencies is uncommon, still would appreciate feedback on this from the npm team so I know it's on the radar. @zkat

**Comment by nmschulte** [comment]
`npm -v` => `5.6.0`

I'm running into this issue as well.  In a project where non-program run-time dependencies are managed via `devDependencies` (and program run-time dependencies via `dependencies`), with `package-lock.json` (created via `npm install`), running `npm --only=development install` and then a script using these dependencies, the script fails due to missing modules.

In my particular case, dev-dependency `"fs-extra": "^5.0.0"` is unusable after `npm --only=development install`, but only if certain dependencies exist.  In this case `"ogr2ogr": "^1.2.1"` exposes the funk.

I've captured a minimal test case here: https://github.com/nmschulte/npm-hork

`$ ./go.sh`
```
npm notice created a lockfile as package-lock.json. You should commit this file.
added 57 packages in 1.154s
added 3 packages in 0.22s
module.js:549
    throw err;
    ^

Error: Cannot find module 'graceful-fs'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/tmp/npm-hork/node_modules/fs-extra/lib/fs/index.js:4:12)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```
