### ISSUE TITLE
verbose stack Error: Refusing to install dgraph-js as a dependency of itself

### ISSUE THREAD

**Issue by rajendrapathi** [npm/npm#19460]
#### I'm opening this issue because:
When I'm running the below command:
npm install dgraph-js

I can see the below error:

43 verbose stack     Error: Refusing to install dgraph-js as a dependency of itself
43 verbose stack     at checkSelf (/usr/lib/node_modules/npm/lib/install/validate-args.js:53:14)
43 verbose stack     at Array.<anonymous> (/usr/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
43 verbose stack     at LOOP (/usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
43 verbose stack     at chain (/usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
43 verbose stack     at /usr/lib/node_modules/npm/lib/install/validate-args.js:16:5
43 verbose stack     at /usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
43 verbose stack     at Array.forEach (native)
43 verbose stack     at /usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
43 verbose stack     at Array.forEach (native)
43 verbose stack     at asyncMap (/usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)

Can you please help on fixing this issue....

**Comment by kenany** [comment]
Ensure that the `"name"` field in your `package.json` is not set to `"dgraph-js"`. Try setting it to something more unique :)
