### ISSUE TITLE
npm install fails with ENOTFOUND -- not behind a proxy

### ISSUE THREAD

**Issue by LefterisJP** [npm/npm#19461]
#### I'm opening this issue because:

npm install is not working for my computer

#### What's going wrong?

`npm install -g solium` returns

```
npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR! network request to https://registry.npmjs.org/commander failed, reason: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lefteris/.npm/_logs/2017-12-26T09_30_35_700Z-debug.log
```

The debug log is [here](https://gist.github.com/LefterisJP/182e34d2d4a0db94db153b51693bf6d9).

I also tried to set the registry to the non-https version but still had the same problem.

#### How can the CLI team reproduce the problem?

I am afraid this is an issue on my end but all of the similar issues googling has lead me to are talking about a proxy. In my case I use no proxy to connect to the internet. No VPN either. 

Visiting https://registry.npmjs.org/ via the browser works fine.

### supporting information:

 - `npm -v` prints: 5.6.0
 - `node -v` prints: v9.3.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Archlinux 4.14.8-1-ARCH #1 SMP PREEMPT Wed Dec 20 21:27:44 UTC 2017 x86_64 GNU/Linu

**Comment by LefterisJP** [comment]
Addtional information. I tried to call `getaddrinfo` directly via the python CLI and it works fine:

```
python -c "import socket; print(socket.getaddrinfo('registry.npmjs.org', 443))"
[(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('151.101.12.162', 443)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_DGRAM: 2>, 17, '', ('151.101.12.162', 443)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_RAW: 3>, 0, '', ('151.101.12.162', 443))]
```

**Comment by LefterisJP** [comment]
I believe it has to do with IPV6 as my network configuration uses it.


Using a different registry which can be resolved with IPV6 as per [this SO ](https://stackoverflow.com/questions/47062223/how-to-install-node-packages-in-ubuntu-server-with-ipv6-only) question worked.

`sudo npm --registry http://registry.node-modules.io/ install -g solium`

The nslookup output for both addresses is below:

```
nslookup registry.npmjs.org

Server:         192.168.1.1
Address:        192.168.1.1#53

Non-authoritative answer:
registry.npmjs.org      canonical name = a.sni.fastly.net.
Name:   a.sni.fastly.net
Address: 151.101.12.162
```

and

```
nslookup registry.node-modules.io                                                                                                                                                                        

Server:         192.168.1.1
Address:        192.168.1.1#53

Non-authoritative answer:
Name:   registry.node-modules.io
Address: 104.28.22.172
Name:   registry.node-modules.io
Address: 104.28.23.172
Name:   registry.node-modules.io
Address: 2400:cb00:2048:1::681c:17ac
Name:   registry.node-modules.io
Address: 2400:cb00:2048:1::681c:16ac
```

**Comment by Kcorab** [comment]
Probably same issue.

`npm install -g @angular/cli`

```
npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR! network request to https://registry.npmjs.org/@angular-devkit%2fcore failed, reason: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/anonym/.npm/_logs/2018-03-08T14_06_01_732Z-debug.log
```
I don't use a proxy!

My logfile.

**Comment by Kcorab** [comment]
Probably same issue.

`npm install -g @angular/cli`

```
npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR! network request to https://registry.npmjs.org/@angular-devkit%2fcore failed, reason: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/anonym/.npm/_logs/2018-03-08T14_06_01_732Z-debug.log
```
I don't use a proxy!

My logfile:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   '@angular/cli' ]
2 info using npm@5.7.1
3 info using node@v9.7.1
4 verbose npm-session f3c037994fd4b582
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 200 https://registry.npmjs.org/@angular%2fcli 1220ms
8 silly pacote tag manifest for @angular/cli@latest fetched in 1282ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 silly install loadShrinkwrap
12 silly install loadAllDepsIntoIdealTree
13 silly resolveWithNewModule @angular/cli@1.7.3 checking installable status
14 silly fetchPackageMetaData error for @angular-devkit/core@0.3.2 request to https://registry.npmjs.org/@angular-devkit%2fcore failed, reason: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
15 http fetch GET 200 https://registry.npmjs.org/@angular-devkit%2fbuild-optimizer 30397ms
16 http fetch GET 200 https://registry.npmjs.org/ajv 30415ms
17 http fetch GET 200 https://registry.npmjs.org/chalk 372ms
18 silly pacote version manifest for @angular-devkit/build-optimizer@0.3.2 fetched in 30471ms
19 silly resolveWithNewModule @angular-devkit/build-optimizer@0.3.2 checking installable status
20 http fetch GET 200 https://registry.npmjs.org/autoprefixer 30463ms
21 silly pacote range manifest for ajv@^6.1.1 fetched in 30475ms
22 silly resolveWithNewModule ajv@6.2.1 checking installable status
23 http fetch GET 200 https://registry.npmjs.org/cache-loader 30475ms
24 silly pacote range manifest for chalk@~2.2.0 fetched in 397ms
25 silly resolveWithNewModule chalk@2.2.2 checking installable status
26 silly pacote range manifest for autoprefixer@^7.2.3 fetched in 30483ms
27 silly resolveWithNewModule autoprefixer@7.2.6 checking installable status
28 silly pacote range manifest for cache-loader@^1.2.0 fetched in 30531ms
29 silly resolveWithNewModule cache-loader@1.2.2 checking installable status
30 http fetch GET 200 https://registry.npmjs.org/circular-dependency-plugin 77ms
31 http fetch GET 200 https://registry.npmjs.org/common-tags 60ms
32 http fetch GET 200 https://registry.npmjs.org/clean-css 68ms
33 silly pacote range manifest for circular-dependency-plugin@^4.2.1 fetched in 92ms
34 silly resolveWithNewModule circular-dependency-plugin@4.4.0 checking installable status
35 silly pacote range manifest for common-tags@^1.3.1 fetched in 76ms
36 silly resolveWithNewModule common-tags@1.7.2 checking installable status
37 silly pacote range manifest for clean-css@^4.1.11 fetched in 84ms
38 silly resolveWithNewModule clean-css@4.1.11 checking installable status
39 http fetch GET 200 https://registry.npmjs.org/core-object 87ms
40 http fetch GET 200 https://registry.npmjs.org/denodeify 68ms
41 http fetch GET 200 https://registry.npmjs.org/ember-cli-string-utils 67ms
42 http fetch GET 200 https://registry.npmjs.org/copy-webpack-plugin 145ms
43 silly pacote range manifest for core-object@^3.1.0 fetched in 104ms
44 silly resolveWithNewModule core-object@3.1.5 checking installable status
45 silly pacote range manifest for denodeify@^1.2.1 fetched in 86ms
46 silly resolveWithNewModule denodeify@1.2.1 checking installable status
47 silly pacote range manifest for ember-cli-string-utils@^1.0.0 fetched in 88ms
48 silly resolveWithNewModule ember-cli-string-utils@1.1.0 checking installable status
49 silly pacote range manifest for copy-webpack-plugin@~4.4.1 fetched in 166ms
50 silly resolveWithNewModule copy-webpack-plugin@4.4.3 checking installable status
51 http fetch GET 200 https://registry.npmjs.org/file-loader 49ms
52 http fetch GET 200 https://registry.npmjs.org/fs-extra 54ms
53 http fetch GET 200 https://registry.npmjs.org/glob 53ms
54 http fetch GET 200 https://registry.npmjs.org/html-webpack-plugin 56ms
55 silly pacote range manifest for file-loader@^1.1.5 fetched in 72ms
56 silly resolveWithNewModule file-loader@1.1.11 checking installable status
57 http fetch GET 200 https://registry.npmjs.org/extract-text-webpack-plugin 158ms
58 silly pacote range manifest for fs-extra@^4.0.0 fetched in 83ms
59 silly resolveWithNewModule fs-extra@4.0.3 checking installable status
60 silly pacote range manifest for glob@^7.0.3 fetched in 82ms
61 silly resolveWithNewModule glob@7.1.2 checking installable status
62 silly pacote range manifest for html-webpack-plugin@^2.29.0 fetched in 83ms
63 silly resolveWithNewModule html-webpack-plugin@2.30.1 checking installable status
64 silly pacote range manifest for extract-text-webpack-plugin@^3.0.2 fetched in 178ms
65 silly resolveWithNewModule extract-text-webpack-plugin@3.0.2 checking installable status
66 http fetch GET 200 https://registry.npmjs.org/karma-source-map-support 34ms
67 silly pacote range manifest for karma-source-map-support@^1.2.0 fetched in 38ms
68 silly resolveWithNewModule karma-source-map-support@1.2.0 checking installable status
69 http fetch GET 200 https://registry.npmjs.org/loader-utils 61ms
70 http fetch GET 200 https://registry.npmjs.org/less-loader 83ms
71 http fetch GET 200 https://registry.npmjs.org/license-webpack-plugin 81ms
72 http fetch GET 200 https://registry.npmjs.org/lodash 77ms
73 http fetch GET 200 https://registry.npmjs.org/less 91ms
74 silly pacote version manifest for loader-utils@1.1.0 fetched in 76ms
75 silly resolveWithNewModule loader-utils@1.1.0 checking installable status
76 silly pacote range manifest for less-loader@^4.0.5 fetched in 99ms
77 silly resolveWithNewModule less-loader@4.0.6 checking installable status
78 silly pacote range manifest for license-webpack-plugin@^1.0.0 fetched in 95ms
79 silly resolveWithNewModule license-webpack-plugin@1.2.3 checking installable status
80 silly pacote range manifest for lodash@^4.11.1 fetched in 95ms
81 silly resolveWithNewModule lodash@4.17.5 checking installable status
82 silly pacote range manifest for less@^2.7.2 fetched in 109ms
83 silly resolveWithNewModule less@2.7.3 checking installable status
84 http fetch GET 200 https://registry.npmjs.org/memory-fs 34ms
85 silly pacote range manifest for memory-fs@^0.4.1 fetched in 46ms
86 silly resolveWithNewModule memory-fs@0.4.1 checking installable status
87 http fetch GET 200 https://registry.npmjs.org/node-modules-path 46ms
88 http fetch GET 200 https://registry.npmjs.org/opn 43ms
89 http fetch GET 200 https://registry.npmjs.org/nopt 44ms
90 http fetch GET 200 https://registry.npmjs.org/minimatch 50ms
91 silly pacote range manifest for node-modules-path@^1.0.0 fetched in 54ms
92 silly resolveWithNewModule node-modules-path@1.0.1 checking installable status
93 silly pacote range manifest for nopt@^4.0.1 fetched in 52ms
94 silly resolveWithNewModule nopt@4.0.1 checking installable status
95 silly pacote range manifest for opn@~5.1.0 fetched in 54ms
96 silly resolveWithNewModule opn@5.1.0 checking installable status
97 silly pacote range manifest for minimatch@^3.0.4 fetched in 63ms
98 silly resolveWithNewModule minimatch@3.0.4 checking installable status
99 http fetch GET 200 https://registry.npmjs.org/portfinder 31ms
100 silly pacote range manifest for portfinder@~1.0.12 fetched in 36ms
101 silly resolveWithNewModule portfinder@1.0.13 checking installable status
102 http fetch GET 200 https://registry.npmjs.org/postcss-import 47ms
103 http fetch GET 200 https://registry.npmjs.org/postcss 50ms
104 http fetch GET 200 https://registry.npmjs.org/postcss-loader 51ms
105 http fetch GET 200 https://registry.npmjs.org/postcss-url 51ms
106 silly pacote range manifest for postcss-import@^11.0.0 fetched in 67ms
107 silly resolveWithNewModule postcss-import@11.1.0 checking installable status
108 silly pacote range manifest for postcss@^6.0.16 fetched in 71ms
109 silly resolveWithNewModule postcss@6.0.19 checking installable status
110 silly pacote range manifest for postcss-loader@^2.0.10 fetched in 69ms
111 silly resolveWithNewModule postcss-loader@2.1.1 checking installable status
112 silly pacote range manifest for postcss-url@^7.1.2 fetched in 66ms
113 silly resolveWithNewModule postcss-url@7.3.1 checking installable status
114 http fetch GET 200 https://registry.npmjs.org/raw-loader 54ms
115 silly pacote range manifest for raw-loader@^0.5.1 fetched in 57ms
116 silly resolveWithNewModule raw-loader@0.5.1 checking installable status
117 http fetch GET 200 https://registry.npmjs.org/resolve 50ms
118 http fetch GET 200 https://registry.npmjs.org/silent-error 45ms
119 http fetch GET 200 https://registry.npmjs.org/sass-loader 54ms
120 http fetch GET 200 https://registry.npmjs.org/rxjs 59ms
121 http fetch GET 200 https://registry.npmjs.org/semver 57ms
122 silly pacote range manifest for resolve@^1.1.7 fetched in 69ms
123 silly resolveWithNewModule resolve@1.5.0 checking installable status
124 http fetch GET 200 https://registry.npmjs.org/@schematics%2fangular 31036ms
125 silly pacote range manifest for silent-error@^1.0.0 fetched in 67ms
126 silly resolveWithNewModule silent-error@1.1.0 checking installable status
127 silly pacote range manifest for sass-loader@^6.0.6 fetched in 78ms
128 silly resolveWithNewModule sass-loader@6.0.7 checking installable status
129 silly pacote range manifest for rxjs@^5.5.6 fetched in 84ms
130 silly resolveWithNewModule rxjs@5.5.6 checking installable status
131 silly pacote range manifest for semver@^5.1.0 fetched in 80ms
132 silly resolveWithNewModule semver@5.5.0 checking installable status
133 silly pacote version manifest for @schematics/angular@0.3.2 fetched in 31057ms
134 silly resolveWithNewModule @schematics/angular@0.3.2 checking installable status
135 http fetch GET 200 https://registry.npmjs.org/source-map-support 47ms
136 http fetch GET 200 https://registry.npmjs.org/@schematics%2fpackage-update 31083ms
137 http fetch GET 200 https://registry.npmjs.org/istanbul-instrumenter-loader 48ms
138 http fetch GET 200 https://registry.npmjs.org/style-loader 52ms
139 silly pacote range manifest for source-map-support@^0.4.1 fetched in 68ms
140 silly resolveWithNewModule source-map-support@0.4.18 checking installable status
141 silly pacote version manifest for @schematics/package-update@0.3.2 fetched in 31100ms
142 silly resolveWithNewModule @schematics/package-update@0.3.2 checking installable status
143 silly pacote range manifest for istanbul-instrumenter-loader@^3.0.0 fetched in 65ms
144 silly resolveWithNewModule istanbul-instrumenter-loader@3.0.0 checking installable status
145 http fetch GET 200 https://registry.npmjs.org/stylus-loader 58ms
146 http fetch GET 200 https://registry.npmjs.org/stylus 63ms
147 http fetch GET 200 https://registry.npmjs.org/uglifyjs-webpack-plugin 58ms
148 silly pacote range manifest for style-loader@^0.19.1 fetched in 75ms
149 silly resolveWithNewModule style-loader@0.19.1 checking installable status
150 silly pacote range manifest for stylus-loader@^3.0.1 fetched in 75ms
151 silly resolveWithNewModule stylus-loader@3.0.2 checking installable status
152 silly pacote range manifest for stylus@^0.54.5 fetched in 78ms
153 silly resolveWithNewModule stylus@0.54.5 checking installable status
154 silly pacote range manifest for uglifyjs-webpack-plugin@^1.1.8 fetched in 80ms
155 silly resolveWithNewModule uglifyjs-webpack-plugin@1.2.2 checking installable status
156 http fetch GET 200 https://registry.npmjs.org/url-loader 63ms
157 http fetch GET 200 https://registry.npmjs.org/webpack-dev-middleware 60ms
158 http fetch GET 200 https://registry.npmjs.org/webpack-merge 90ms
159 http fetch GET 200 https://registry.npmjs.org/webpack-sources 91ms
160 silly pacote range manifest for url-loader@^0.6.2 fetched in 119ms
161 silly resolveWithNewModule url-loader@0.6.2 checking installable status
162 http fetch GET 200 https://registry.npmjs.org/webpack-dev-server 99ms
163 silly pacote range manifest for webpack-dev-middleware@~1.12.0 fetched in 123ms
164 silly resolveWithNewModule webpack-dev-middleware@1.12.2 checking installable status
165 http fetch GET 200 https://registry.npmjs.org/webpack-subresource-integrity 94ms
166 silly pacote range manifest for webpack-merge@^4.1.0 fetched in 115ms
167 silly resolveWithNewModule webpack-merge@4.1.2 checking installable status
168 silly pacote range manifest for webpack-sources@^1.0.0 fetched in 114ms
169 silly resolveWithNewModule webpack-sources@1.1.0 checking installable status
170 silly pacote range manifest for webpack-dev-server@~2.11.0 fetched in 121ms
171 silly resolveWithNewModule webpack-dev-server@2.11.2 checking installable status
172 silly pacote range manifest for webpack-subresource-integrity@^1.0.1 fetched in 106ms
173 silly resolveWithNewModule webpack-subresource-integrity@1.0.4 checking installable status
174 http fetch GET 200 https://registry.npmjs.org/webpack 144ms
175 silly pacote range manifest for webpack@~3.11.0 fetched in 169ms
176 silly resolveWithNewModule webpack@3.11.0 checking installable status
177 http fetch GET 200 https://registry.npmjs.org/node-sass 48ms
178 silly pacote range manifest for node-sass@^4.7.2 fetched in 53ms
179 silly resolveWithNewModule node-sass@4.7.2 checking installable status
180 silly fetchPackageMetaData error for @ngtools/json-schema@1.2.0 request to https://registry.npmjs.org/@ngtools%2fjson-schema failed, reason: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
181 silly fetchPackageMetaData error for @angular-devkit/schematics@0.3.2 request to https://registry.npmjs.org/@angular-devkit%2fschematics failed, reason: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
182 silly fetchPackageMetaData error for @ngtools/webpack@1.10.2 request to https://registry.npmjs.org/@ngtools%2fwebpack failed, reason: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
183 verbose type system
184 verbose stack FetchError: request to https://registry.npmjs.org/@angular-devkit%2fcore failed, reason: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
184 verbose stack     at ClientRequest.req.on.err (/usr/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/src/index.js:68:14)
184 verbose stack     at ClientRequest.emit (events.js:127:13)
184 verbose stack     at TLSSocket.socketErrorListener (_http_client.js:394:9)
184 verbose stack     at TLSSocket.emit (events.js:127:13)
184 verbose stack     at emitErrorNT (internal/streams/destroy.js:64:8)
184 verbose stack     at process._tickCallback (internal/process/next_tick.js:114:19)
185 verbose cwd /home/anonym
186 verbose Linux 4.15.7-1-ARCH
187 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "@angular/cli"
188 verbose node v9.7.1
189 verbose npm  v5.7.1
190 error code ENOTFOUND
191 error errno ENOTFOUND
192 error network request to https://registry.npmjs.org/@angular-devkit%2fcore failed, reason: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
193 error network This is a problem related to network connectivity.
193 error network In most cases you are behind a proxy or have bad network settings.
193 error network
193 error network If you are behind a proxy, please make sure that the
193 error network 'proxy' config is set properly.  See: 'npm help config'
194 verbose exit [ 1, true ]
```

No, I am not behind a proxy and thus my proxy isn't set.

**Comment by changemenemo** [comment]
same problem on freeBSD 11.1 for different package.
```
 verbose node v9.3.0
14 verbose npm  v5.6.0
```
for different package actually and it seems sporadic. Here it was for fs-extra

5 minutes later it worked. So I don't think it's on our end. Actually I think it something in the code who doesn't allow a big timeout or backup routes to get the information, here the IP address. There should maybe a timeout or retry implemented....

**Comment by blocka** [comment]
I had this issue [here](https://github.com/npm/npm/issues/18243). See my "solution" there.

**Comment by kaplanbora** [comment]
@blocka I tried your solutions. Neither host file nor cloudflare dns solved this issue for me.
