### ISSUE TITLE
npm installation fails

### ISSUE THREAD

**Issue by likith217** [npm/npm#19471]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ X] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I am trying to install npm and facing the following error 

npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EPROTO: request to https://registry.npmjs.org/grunt-cli failed, reason: write EPROTO 139876327438112:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:\n
npm WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
npm WARN locking Error: Unknown system error -122: Unknown system error -122, open '/home/lxxxar/.npm/_locks/staging-a072192f34a17023.lock'
npm WARN locking  /home/lxxxar/.npm/_locks/staging-a072192f34a17023.lock failed { Error: Unknown system error -122: Unknown system error -122, open '/home/lxxxar/.npm/_locks/staging-a072192f34a17023.lock'
npm WARN locking   stack: 'Error: Unknown system error -122: Unknown system error -122, open \'/home/lxxxar/.npm/_locks/staging-a072192f34a17023.lock\'',

### supporting information:

 - `npm -v` prints:
5.5.1
 - `node -v` prints:
  v8.9.3
 - `npm config get registry` prints:
https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?:
Linux
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by Youngestdev** [comment]
Try reinstalling NodeJs by building it.. (Don't install from package manager if youre on Linux ) . hope it works

**Comment by likith217** [comment]
Thanks for the update . 

This is the steps I followed 
  sudo mkdir /usr/lib/nodejs
  curl -LO https://nodejs.org/dist/v8.9.3/node-v8.9.3-linux-x64.tar.xz
  sudo tar -xJvf node-v8.9.3-linux-x64.tar.xz -C /usr/lib/nodejs
  sudo mv /usr/lib/nodejs/node-v8.9.3-linux-x64 /usr/lib/nodejs/node-v8.9.3
  touch ~/.profile
  chmod 777 ~/.profile
  echo "# Nodejs
  export NODEJS_HOME=/usr/lib/nodejs/node-v8.9.3
  export PATH=\$NODEJS_HOME/bin:\$PATH"  > ~/.profile
  . ~/.profile

NodeJs is installed .
But when I try to install any package of npm it fails say grunt , it faile with below error.

 info it worked if it ends with ok
1 verbose cli [ '/usr/lib/nodejs/node-v8.9.3/bin/node',
1 verbose cli   '/usr/lib/nodejs/node-v8.9.3/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'grunt-cli' ]
2 info using npm@5.5.1
3 info using node@v8.9.3
4 verbose npm-session d62a557c61505d16
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData error for grunt-cli@latest request to https://registry.npmjs.org/grunt-cli failed, reason: write EPROTO 139909042079520:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:
8 verbose type system
9 verbose stack FetchError: request to https://registry.npmjs.org/grunt-cli failed, reason: write EPROTO 139909042079520:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:
9 verbose stack
9 verbose stack     at ClientRequest.req.on.err (/usr/lib/nodejs/node-v8.9.3/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/src/index.js:68:14)
9 verbose stack     at emitOne (events.js:116:13)
9 verbose stack     at ClientRequest.emit (events.js:211:7)
9 verbose stack     at onerror (/usr/lib/nodejs/node-v8.9.3/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/https-proxy-agent/node_modules/agent-base/index.js:106:9)
9 verbose stack     at callbackError (/usr/lib/nodejs/node-v8.9.3/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/https-proxy-agent/node_modules/agent-base/index.js:126:5)
9 verbose stack     at <anonymous>
10 verbose cwd /home/lshekar
11 verbose Linux 2.6.39-400.286.3.el6uek.x86_64
12 verbose argv "/usr/lib/nodejs/node-v8.9.3/bin/node" "/usr/lib/nodejs/node-v8.9.3/bin/npm" "install" "-g" "grunt-cli"
13 verbose node v8.9.3
14 verbose npm  v5.5.1
15 error code EPROTO
16 error errno EPROTO
17 error request to https://registry.npmjs.org/grunt-cli failed, reason: write EPROTO 139909042079520:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

Really appreciate any suggestion or pointers to resolve this issue.

**Comment by divyanshumehta** [comment]
Still facing this issue
```
12:07:17 : ~ $ sudo npm install prop-types@15.6.0
[sudo] password for mehta: 
npm ERR! code EPROTO
npm ERR! errno EPROTO
npm ERR! request to https://registry.npmjs.org/prop-types failed, reason: write EPROTO 140061322028864:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mehta/.npm/_logs/2018-02-08T06_42_11_211Z-debug.log
12:12:11 : ~ $ 
```
