### ISSUE TITLE
npm breaks on npm ls depth:1

### ISSUE THREAD

**Issue by SGP57** [npm/npm#19491]
#### I'm opening this issue because:

  - [ y] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Unhandled rejection Error: Unsupported URL Type "depth:": depth:1
    at unsupportedURLType (/usr/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:197:15)
    at fromURL (/usr/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:250:13)
    at resolve (/usr/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:71:12)
    at npa (/usr/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:48:10)
    at /usr/lib/node_modules/npm/lib/ls.js:65:17
    at Array.map (<anonymous>)
    at ls.fromTree (/usr/lib/node_modules/npm/lib/ls.js:61:17)
    at /usr/lib/node_modules/npm/lib/ls.js:42:7
    at inflateShrinkwrap.then (/usr/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:33:11)
    at tryCatcher (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

#### How can the CLI team reproduce the problem?
npm ls depth:1

### supporting information:

- run from command line

- I tried the command; I assume I have the wrong syntax but didn't expect this output.

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by itsAnuga** [comment]
Are you using it correctly?

`npm ls depth=1`
`npm list depth=1`

**Comment by SGP57** [comment]
No! I am not using it correctly. It was a first attempt. However I would
expect my request to be rejected rather than causing the program to fail.

Thanks.
