### ISSUE TITLE
how to recover node_modules of my ionic 3 project 

### ISSUE THREAD

**Issue by hamendrasingh200** [npm/npm#19498]
#### I'm opening this issue because:

I have run ' npm i @ionic/app-scripts ' and I got some node_modules but I think some are missing so I am facing this error, anybody can help me in resolving this error. 

{ Error: A watch configured to watch the following paths failed to start. It likely that a file referenced does not exist: F:\Ionic-Test_project\pulakiosk\pulakiosk\src\assets\**\*, F:\Ionic-Test_project\pulakiosk\pulakiosk\src\index.html, F:\Ionic-Test_project\pulakiosk\pulakiosk\src\manifest.json, F:\Ionic-Test_project\pulakiosk\pulakiosk\src\service-worker.js, F:\Ionic-Test_project\pulakiosk\pulakiosk\node_modules\ionicons\dist\fonts\**\*, F:\Ionic-Test_project\pulakiosk\pulakiosk\node_modules\ionic-angular\fonts\**\*, F:\Ionic-Test_project\pulakiosk\pulakiosk\node_modules\ionic-angular\polyfills\polyfills.js, F:\Ionic-Test_project\pulakiosk\pulakiosk\node_modules\sw-toolbox\sw-toolbox.js
    at BuildError.Error (native)
    at new BuildError (F:\Ionic-Test_project\pulakiosk\pulakiosk\node_modules\@ionic\app-scripts\dist\util\errors.js:16:28)
    at Timeout._onTimeout (F:\Ionic-Test_project\pulakiosk\pulakiosk\node_modules\@ionic\app-scripts\dist\watch.js:71:20)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5) hasBeenLogged: false, isFatal: false }

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment]
Which files are missing, specifically?

**Comment by hamendrasingh200** [comment]
actually, I want to recover my node_modules folder of my existing ionic 3 projects. because I lost my node_modules folder by mistake otherwise I have all files of my projects. so how to recover my all node_modules folder of my ionic 3 project.

**Comment by kenany** [comment]
Perhaps you could re-install your dependencies with `npm install`?
