### ISSUE TITLE
npm not working on window 10 plz tell me how to solve it?

### ISSUE THREAD

**Issue by anup6191** [npm/npm#19503]
module.js:540
    throw err;
    ^

Error: Cannot find module 'inherits'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\anup\AppData\Roaming\npm\node_modules\npm\node_modules\readable-stream\lib\_stream_readable.js:68:17)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)

**Comment by kenany** [comment]
Does this also occur after reinstalling `npm`?

**Comment by dwale** [comment]
same happens to me and yes after reinstalling###  npm, i also tried to update it but it till gave the same error

**Comment by dwale** [comment]
@KenanY

**Comment by anup6191** [comment]
1st i have uninstall nodejs and also delete (C:\Users\username\AppData\Roaming\npm) npm folder from user directory.
After reinstalling nodejs working now and also npm working too.

**Comment by SaintPeter** [comment]
Deleting the `%AppData%\npm` folder and reinstalling node.js fixed this for me as well.

**Comment by AndreaCole1340** [comment]
still having problems with npm on windows 10 after uninstall and reinstall and after deleting \AppData\Roaming\npm . Anyone have any other solutions but highly appreciated.
