### ISSUE TITLE
Cannot read property 'length' of undefined on FreeBSD/aarch64

### ISSUE THREAD

**Issue by gczuczy** [npm/npm#19514]
Hello,

I'm using npm on FreeBSD/aarch64, and apparently there's an issue with the cpu detection. Here's the debug log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'install' ]
2 info using npm@5.6.0
3 info using node@v8.9.3
4 verbose npm-session f78f9ae50462c0fb
5 verbose stack TypeError: Cannot read property 'length' of undefined
5 verbose stack     at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/worker-farm/lib/farm.js:5:61)
5 verbose stack     at Module._compile (module.js:635:30)
5 verbose stack     at Object.Module._extensions..js (module.js:646:10)
5 verbose stack     at Module.load (module.js:554:32)
5 verbose stack     at tryModuleLoad (module.js:497:12)
5 verbose stack     at Function.Module._load (module.js:489:3)
5 verbose stack     at Module.require (module.js:579:17)
5 verbose stack     at require (internal/module.js:11:18)
5 verbose stack     at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/worker-farm/lib/index.js:3:14)
5 verbose stack     at Module._compile (module.js:635:30)
5 verbose stack     at Object.Module._extensions..js (module.js:646:10)
5 verbose stack     at Module.load (module.js:554:32)
5 verbose stack     at tryModuleLoad (module.js:497:12)
5 verbose stack     at Function.Module._load (module.js:489:3)
5 verbose stack     at Module.require (module.js:579:17)
5 verbose stack     at require (internal/module.js:11:18)
6 verbose cwd /usr/home/aegir/aegir/aegir-ui
7 verbose FreeBSD 12.0-CURRENT
8 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
9 verbose node v8.9.3
10 verbose npm  v5.6.0
11 error Cannot read property 'length' of undefined
```

That's the following line:

`        , maxConcurrentWorkers        : require('os').cpus().length
`

Could this be fixed please?

**Comment by kenany** [comment]
What's the output of?:

```console
$ node -e "console.log(require('os').cpus().length)"
```

**Comment by gczuczy** [comment]
I see, it's nodejs, not npm:

```
$ node -e "console.log(require('os').cpus().length)"
[eval]:1
console.log(require('os').cpus().length)
                                ^

TypeError: Cannot read property 'length' of undefined
    at [eval]:1:33
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at Object.runInThisContext (vm.js:139:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:635:30)
    at evalScript (bootstrap_node.js:462:27)
    at startup (bootstrap_node.js:163:9)
    at bootstrap_node.js:608:3
```

Thanks, I will let the nodejs folk know, please close this ticket, and sorry for the noise.

**Comment by gczuczy** [comment]
FYI: https://github.com/nodejs/node/issues/17995
