### ISSUE TITLE
missing script: start at gulp while working with react

### ISSUE THREAD

**Issue by yuvaKishoreDommaraju** [npm/npm#19513]
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@3.10.10
3 info using node@v6.11.2
4 verbose stack Error: missing script: start
4 verbose stack     at run (/usr/local/lib/node_modules/npm/lib/run-script.js:151:19)
4 verbose stack     at /usr/local/lib/node_modules/npm/lib/run-script.js:61:5
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:356:5
4 verbose stack     at checkBinReferences_ (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:320:45)
4 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:354:3)
4 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:124:5)
4 verbose stack     at ReadFileContext.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:295:20)
4 verbose stack     at ReadFileContext.callback (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16)
4 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:366:13)
5 verbose cwd /Users/mac/ReactJS/todo
6 error Darwin 17.3.0
7 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
8 error node v6.11.2
9 error npm  v3.10.10
10 error missing script: start
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
```

Here is my gulp js file as follows 

```js
"use strict"

// import the modules we need
var gulp = require('gulp');
var conn = require('gulp-connect');
var open = require('gulp-open');
var browserify = require('browserify');
var reactify = require('reactify');
var source = require('vinyl-source-stream');
var concat = require('gulp-concat');
var lint   = require('gulp-eslint');
// configuration values
var config = {
	port	 : 5500,
	baseUrl  : 'http://localhost',
	paths	 : {
		html	: '.src/*.html',
		js		: './src/**/*.js',
		indexJs	: './src/index.js',
		css		: [
			'./node_modules/bootstrap/dist/css/bootstrap.min.css',
			'./node_modules/bootstrap/dist/css/bootstrap-theme.min.css'
		],
		dist 	: './dist'
	}
}

// launch local server for development
gulp.task('conn', function() {
	conn.server({
		root  		: ['dist'],
		port  		: config.port,
		base  		: config.baseUrl,
		livereload  : true
	});
});

// gulp open the browser url on the server
gulp.task('open', ['conn'], function(){
	gulp.src('dist/index.html')
		.pipe(open({uri: config.baseUrl + ':' + config.port + '/' }));
});

// copy html to dist
gulp.task('html', function() {
	gulp.src(config.paths.html)
		.pipe(gulp.dest(config.paths.dist))
		.pipe(conn.reload());
});

gulp.task('js', function() {
	browserify(config.paths.indexJs)
		.transform(reactify)
		.bundle()
		.on('error', console.error.bind(console))
		.pipe(source('bundle.js'))
		.pipe(gulp.dest(config.paths.dist + '/js'))
		.pipe(conn.reload());
});

gulp.task('css', function(){
	gulp.src(config.paths.css)
		.pipe(concat('bundle.css'))
		.pipe(gulp.dest(config.paths.dist + '/css'))
});

gulp.task('lint', function(){
	return gulp.src(config.paths.js)
				.pipe(lint({config : '.eslintrc.json'}))
				.pipe(lint.format());
});

gulp.task('watch', function() {
	gulp.watch(config.paths.html, ['html']);
	gulp.watch(config.paths.js, ['js']);
});

// default task
gulp.task('default', ['html', 'js', 'css', 'lint', 'open', 'watch']);
```

here is the package.json 

```json
{
  "name": "todomyreact",
  "version": "1.0.0",
  "description": "started with react framework",
  "main": "index.js",
  "script": {
    "start" : "npm run build"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/Uvii/todoReact.git"
  },
  "author": "yuvakishore",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/Uvii/todoReact/issues"
  },
  "homepage": "https://github.com/Uvii/todoReact#readme",
  "dependencies": {
    "bootstrap": "^3.3.7",
    "browserify": "^14.5.0",
    "flux": "^3.1.3",
    "gulp": "^3.9.1",
    "gulp-concat": "^2.6.1",
    "gulp-connect": "^5.0.0",
    "gulp-eslint": "^4.0.0",
    "gulp-open": "^2.1.0",
    "jQuery": "^1.7.4",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-router": "^4.2.0",
    "reactify": "^1.1.1",
    "vinyl-source-stream": "^2.0.0"
  }
}
```

**Comment by kenany** [comment]
I edited your comment to make it more readable. I hope you don't mind.

Could you try changing `"script"` in your `package.json` to `"scripts"` (plural)? Also make sure to define a `"build"` script as well, as that is what your `"start"` script is running.

**Comment by yuvaKishoreDommaraju** [comment]
Thanks in advance Kenna for your time

I was having an error when i mentioned as "scripts" that's the reason I was changed it to "script"
here is the error once after changing "script" to "scripts"

```
// error

> todomyreact@1.0.0 start /Users/mac/ReactJS/todo
> npm run build

npm ERR! Darwin 17.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10

npm ERR! missing script: build
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mac/ReactJS/todo/npm-debug.log

npm ERR! Darwin 17.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! todomyreact@1.0.0 start: `npm run build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the todomyreact@1.0.0 start script 'npm run build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the todomyreact package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs todomyreact
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls todomyreact
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     

- /Users/mac/ReactJS/todo/npm-debug.log
```

// package.json file as follows
```json

{
  "name": "todomyreact",
  "version": "1.0.0",
  "description": "started with react framework",
  "main": "index.js",
  "scripts": {
    "start" : "npm run build"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/Uvii/todoReact.git"
  },
  "author": "yuvakishore",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/Uvii/todoReact/issues"
  },
  "homepage": "https://github.com/Uvii/todoReact#readme",
  "dependencies": {
    "bootstrap": "^3.3.7",
    "browserify": "^14.5.0",
    "flux": "^3.1.3",
    "gulp": "^3.9.1",
    "gulp-concat": "^2.6.1",
    "gulp-connect": "^5.0.0",
    "gulp-eslint": "^4.0.0",
    "gulp-open": "^2.1.0",
    "jQuery": "^1.7.4",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-router": "^4.2.0",
    "reactify": "^1.1.1",
    "vinyl-source-stream": "^2.0.0"
  }
}
```

**Comment by kenany** [comment]
From my last comment:

> Also make sure to define a `"build"` script as well, as that is what your `"start"` script is running.

**Comment by yuvaKishoreDommaraju** [comment]
How to use "build" script in gulp I'm not familiar will you able to put it down here.. 

you can find my gulp.js && package .json files as mentioned above.
  
I had recently worked with web pack there i seen build script, whereas in gulp I had configured everything as gulp.task, will you help me out how to use build script with gulp.

**Comment by kenany** [comment]
Okay, how about:

```json
  "scripts": {
    "build" : "gulp",
    "start" : "npm run build"
  },
```

**Comment by yuvaKishoreDommaraju** [comment]
My gulp file .js is available on top this page

```
events.js:160
      throw er; // Unhandled 'error' event
      ^
SyntaxError: Cannot read config file: /Users/mac/ReactJS/todo/.eslintrc.json
Error: Unexpected token m in JSON at position 0
    at Object.parse (native)
    at loadJSONConfigFile (/Users/mac/ReactJS/todo/node_modules/eslint/lib/config/config-file.js:114:21)
    at loadConfigFile (/Users/mac/ReactJS/todo/node_modules/eslint/lib/config/config-file.js:225:26)
    at loadFromDisk (/Users/mac/ReactJS/todo/node_modules/eslint/lib/config/config-file.js:486:18)
    at Object.load (/Users/mac/ReactJS/todo/node_modules/eslint/lib/config/config-file.js:550:20)
    at Config.getLocalConfigHierarchy (/Users/mac/ReactJS/todo/node_modules/eslint/lib/config.js:228:44)
    at Config.getConfigHierarchy (/Users/mac/ReactJS/todo/node_modules/eslint/lib/config.js:180:43)
    at Config.getConfigVector (/Users/mac/ReactJS/todo/node_modules/eslint/lib/config.js:287:21)
    at Config.getConfig (/Users/mac/ReactJS/todo/node_modules/eslint/lib/config.js:330:29)
    at processText (/Users/mac/ReactJS/todo/node_modules/eslint/lib/cli-engine.js:162:33)
```
Here is my eslintrc.json

```.json
{
	"parseOptions" :{
		"ecmaFeatures" : {
			"jsx" : true
		}
	},
	"env" : {
		"browser" : true,
		"node" : true,
		"jquery" : true
	},
	"rules" : {
		"quotes" : 1,
		"no-trailing-spaces" : 0,
		"eol-last" : 0,
		"no-unused-vars" : 2,
		"no-underscore-dangle" : 0,
		"no-alerts" : 0,
		"no-lone-blocks" : 0
	},
	"globals" : {
		"jQuery" : true,
		"$" : true
	}
}
```

**Comment by kenany** [comment]
Stack trace indicates that the error is coming from `eslint`, not `npm`. Might want to take this up with the authors of that package instead.
