### ISSUE TITLE
npm ERR! Cannot read property '0' of undefined - npm 5.6.0 packages don't install

### ISSUE THREAD

**Issue by cresharper** [npm/npm#19523]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I can't `npm install` anything on OSX El Captiain with npm 5.6.0. I get:

`npm ERR! Cannot read property '0' of undefined`

I had to downgrade to npm 5.2.0 to fix it...

See: https://stackoverflow.com/questions/48102598/npm-install-throws-npm-err-cannot-read-property-0-of-undefined

#### How can the CLI team reproduce the problem?

run an `npm install` with version 5.6.0

### supporting information:

 - `npm -v` prints:
pre-fix: 5.6.0 - but I fixed it by downgrading to 5.2.0
 - `node -v` prints:
8.6.0
 - `npm config get registry` prints:
n/a
 - Windows, OS X/macOS, or Linux?:
El Captian
 - Network issues:
   - Geographic location where npm was run:
   - [] I use a proxy to connect to the npm registry.
   - [] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
(I tried both with and without proxy, with same results)
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by shadowmint** [comment]
I would just like to add that we're seeing this with npm 5.6 as well; it is definitely not 'resolved' for 5.6.

For us it was triggered by this strange behaviour:

    del node_modules
    npm install <-- works
    npm install <-- second time raises the error
    del package-lock.json
    del node_modules
    npm install <-- works
    npm install <-- still works

I know this is a frustrating bug to try to fix, but there is definitely something to do with the package-lock parsing that isn't happy in some cases.

We solved it by re-generating package-lock.json from scratch, not by downgrading to 5.2 (although, to be fair, downgrading to 5.2 *also* fixed the issue for us when we tried it)

**Comment by mjaczynski** [comment]
I have the same issue:
```
3519 verbose stack TypeError: Cannot read property '0' of undefined
3519 verbose stack     at rmStuff (/var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/NodeJS_8/lib/node_modules/npm/lib/unbuild.js:61:24)
3519 verbose stack     at tryCatcher (/var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/NodeJS_8/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
3519 verbose stack     at ret (eval at makeNodePromisifiedEval (/var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/NodeJS_8/lib/node_modules/npm/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:13:39)
3519 verbose stack     at lifecycle.then.then (/var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/NodeJS_8/lib/node_modules/npm/lib/install/action/unbuild.js:12:12)
3519 verbose stack     at tryCatcher (/var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/NodeJS_8/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
3519 verbose stack     at Promise._settlePromiseFromHandler (/var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/NodeJS_8/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
3519 verbose stack     at Promise._settlePromise (/var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/NodeJS_8/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
3519 verbose stack     at Promise._settlePromise0 (/var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/NodeJS_8/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
3519 verbose stack     at Promise._settlePromises (/var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/NodeJS_8/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
3519 verbose stack     at Promise._fulfill (/var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/NodeJS_8/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:638:18)
3519 verbose stack     at /var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/NodeJS_8/lib/node_modules/npm/node_modules/bluebird/js/release/nodeback.js:42:21
3519 verbose stack     at <anonymous>
3521 verbose Linux 4.4.0-97-generic
3522 verbose argv "/var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/NodeJS_8/bin/node" "/var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/NodeJS_8/bin/npm" "install"
3523 verbose node v8.9.4
3524 verbose npm  v5.6.0
3525 error Cannot read property '0' of undefined
3526 verbose exit [ 1, true ]

```
