### ISSUE TITLE
npm -v error on win10

### ISSUE THREAD

**Issue by chugf** [npm/npm#19549]
C:\Users\Administrator>npm -v
Error: spawn C:\nodejs\node.exe ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:678:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
C:\nodejs\node_modules\npm\lib\npm.js:51
      throw new Error('npm.load() required')
      ^

Error: npm.load() required
    at Object.get (C:\nodejs\node_modules\npm\lib\npm.js:51:13)
    at process.errorHandler (C:\nodejs\node_modules\npm\lib\utils\error-handler.js:205:18)
    at emitOne (events.js:116:13)
    at process.emit (events.js:211:7)
    at process._fatalException (bootstrap_node.js:374:26)
5.5.1

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\nodejs\node.exe ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:678:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

**Comment by SimonBrazell** [comment]
I was experiencing this same issue on Windows 7, rolled back to npm v5.5.0 and it no longer occurred.
