### ISSUE TITLE
Cannot install npm from install.sh

### ISSUE THREAD

**Issue by ajayindfw** [npm/npm#19550]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

I am getting following error when trying to install npm:
Ajay-SWRX-MBP:~ ajgupta$ curl -L https://www.npmjs.org/install.sh | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   185  100   185    0     0    507      0 --:--:-- --:--:-- --:--:--   508
100  6255  100  6255    0     0   6087      0  0:00:01  0:00:01 --:--:-- 14822
tar=/usr/bin/tar
version:
bsdtar 2.8.3 - libarchive 2.8.3
install npm@latest
fetching: https://registry.npmjs.org/npm/-/npm-5.6.0.tgz

module.js:557
    throw err;
    ^

Error: Cannot find module '/private/var/folders/0x/hw4b4vn574b02fp2d3__qgs00000gn/T/npm.92806/package/bin/read-package-json.js'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:618:3
up to date in 0.05s
/Users/ajgupta/.npm-global-packages/bin/npx -> /Users/ajgupta/.npm-global-packages/lib/node_modules/npm/bin/npx-cli.js
/Users/ajgupta/.npm-global-packages/bin/npm -> /Users/ajgupta/.npm-global-packages/lib/node_modules/npm/bin/npm-cli.js
+ npm@5.6.0
added 1 package in 1.357s
It worked
Ajay-SWRX-MBP:~ ajgupta$ 
Ajay-SWRX-MBP:~ ajgupta$ npm --version
-bash: npm: command not found

**Comment by kwohlfahrt** [comment]
Same happens to me. Note The following links exist after install:

```
> ls ~/.npm/bin/ -l
total 0
lrwxrwxrwx 1 kjw53 kjw53 38 Jan 18 13:10 npm -> ../lib/node_modules/npm/bin/npm-cli.js
lrwxrwxrwx 1 kjw53 kjw53 38 Jan 18 13:10 npx -> ../lib/node_modules/npm/bin/npx-cli.js
> ls ~/.npm/lib/node_modules/ -l
total 0
lrwxrwxrwx 1 kjw53 kjw53 36 Jan 18 13:10 npm -> ../../../../../tmp/npm.24930/package
```

The last one doesn't exist, but since it's in `/tmp` it would be wiped on reboot at the latest anyway.

**Comment by passiomatic** [comment]
Same error here on macOS Sierra.  I was following https://gist.github.com/DanHerbert/9520689. Homebrew correctly installed Node 9.5.0 without npm.   

```
Moby:~ Andrea$ node -v
v9.5.0
```

When I try to install npm via shell script I hit that error. 
```Moby:~ Andrea$ curl -L https://www.npmjs.com/install.sh | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6255  100  6255    0     0  15982      0 --:--:-- --:--:-- --:--:-- 15997
tar=/usr/bin/tar
version:
bsdtar 2.8.3 - libarchive 2.8.3
install npm@latest
fetching: https://registry.npmjs.org/npm/-/npm-5.6.0.tgz
module.js:557
    throw err;
    ^

Error: Cannot find module '/private/var/folders/dn/601_zv3973x_v_5vllldlsg80000gn/T/npm.908/package/bin/read-package-json.js'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:190:16)
    at bootstrap_node.js:662:3
added 1 package in 0.748s
/Users/Andrea/.npm-packages/bin/npm -> /Users/Andrea/.npm-packages/lib/node_modules/npm/bin/npm-cli.js
/Users/Andrea/.npm-packages/bin/npx -> /Users/Andrea/.npm-packages/lib/node_modules/npm/bin/npx-cli.js
+ npm@5.6.0
updated 1 package in 1.779s
It worked
```

👆 No, unfortunately it didn't work.  ;( 

```
Moby:~ Andrea$ ls /Users/Andrea/.npm-packages/lib/node_modules/npm/bin/npm-cli.js
ls: /Users/Andrea/.npm-packages/lib/node_modules/npm/bin/npm-cli.js: No such file or directory
```

I also tried to run install script with `sudo` but didn't change a thing.

**Comment by snowghost24** [comment]
I'm having the same error and haven't found a solution.

**Comment by eliot-akira** [comment]
I had to deal with the same situation yesterday, so here's how I was able to solve it. Apparently the default install script from [https://www.npmjs.com/install.sh](https://www.npmjs.com/install.sh) is broken in some way - I was getting the same error, cannot find module `read-package-json.js` .

---

1. Create a temporary folder

```sh
mkdir tmp
cd tmp
```

2. Download and unpack `npm`

```sh
curl https://registry.npmjs.org/npm/-/npm-6.0.1.tgz > npm.tgz
tar xzf npm.tgz
```

3. Run the install script

```sh
cd package
./scripts/install.sh
```

---

You may need to remove the symlinks to `npm` and `npx` in /usr/local/bin (or elsewhere) before running  the install script.
