### ISSUE TITLE
npm ERR! cb() never called!Unhandled rejection RangeError: Maximum call stack size exceeded myProject

### ISSUE THREAD

**Issue by FE-xiaoJiang** [npm/npm#19567]
#### I'm opening this issue because:

  - [ ] npm is producing an incorrect install.

#### What's going wrong?
Unhandled rejection RangeError: Maximum call stack size exceeded myProject
    at RegExp.test (<anonymous>)
    at /usr/local/lib/node_modules/npm/node_modules/aproba/index.js:38:16
    at Array.forEach (native)
    at module.exports (/usr/local/lib/node_modules/npm/node_modules/aproba/index.js:33:11)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:37:3)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
    at flatNameFromTree (/usr/local/lib/node_modules/npm/lib/install/flatten-tree.js:39:14)
npm ERR! cb() never called!

#### How can the CLI team reproduce the problem?
npm i,then throw error

### supporting information:

 - `npm -v` prints:5.3.0
 - `node -v` prints:v8.1.3
 - `npm config get registry` prints:https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?:macOS
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on OS X or Linux.

**Comment by wind-hx** [comment]
Like you, I met the same problem. How do you solve it?

**Comment by jinjinwa** [comment]
+1

**Comment by johnny1952** [comment]
+1
