### ISSUE TITLE
node-gyp error

### ISSUE THREAD

**Issue by Macifier** [npm/npm#19568]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/utkarsh/workspace/server/node_modules/node-expat/build'
gyp ERR! System Linux 4.10.0-42-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/utkarsh/workspace/server/node_modules/node-expat
gyp ERR! node -v v9.3.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN Jova_CRM@0.0.3 No repository field.
npm WARN Jova_CRM@0.0.3 license should be a valid SPDX license expression

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-expat@2.3.15 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-expat@2.3.15 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by aflansburg** [comment]
I'm having a similar/same issue, but I'm not convinced it is an npm issue. Still trying to dig.

127 verbose stack Error: node-expat@2.3.16 install: `node-gyp rebuild`
127 verbose stack Exit status 1
127 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
127 verbose stack     at EventEmitter.emit (events.js:160:13)
127 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
127 verbose stack     at ChildProcess.emit (events.js:160:13)
127 verbose stack     at maybeClose (internal/child_process.js:943:16)
127 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
128 verbose pkgid node-expat@2.3.16
130 verbose Darwin 17.3.0
131 verbose argv "/usr/local/Cellar/node/9.4.0/bin/node" "/usr/local/bin/npm" "install"
132 verbose node v9.4.0
133 verbose npm  v5.6.0
134 error code ELIFECYCLE
135 error errno 1
136 error node-expat@2.3.16 install: `node-gyp rebuild`
136 error Exit status 1
137 error Failed at the node-expat@2.3.16 install script.
137 error This is probably not a problem with npm. There is likely additional logging output above.
138 verbose exit [ 1, true ]
