### ISSUE TITLE
Error: Cannot find module 'realize-package-specifier'

### ISSUE THREAD

**Issue by StepanxXx** [npm/npm#19570]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'i' ]
2 info using npm@3.10.10
3 info using node@v8.9.3
4 verbose stack Error: Cannot find module 'realize-package-specifier'
4 verbose stack     at Function.Module._resolveFilename (module.js:536:15)
4 verbose stack     at Function.Module._load (module.js:466:25)
4 verbose stack     at Module.require (module.js:579:17)
4 verbose stack     at require (internal/module.js:11:18)
4 verbose stack     at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/install/deps.js:11:31)
4 verbose stack     at Module._compile (module.js:635:30)
4 verbose stack     at Object.Module._extensions..js (module.js:646:10)
4 verbose stack     at Module.load (module.js:554:32)
4 verbose stack     at tryModuleLoad (module.js:497:12)
4 verbose stack     at Function.Module._load (module.js:489:3)
5 verbose cwd /home/stepan/Документы/npmTest
6 error Linux 4.10.0-42-generic
7 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "i"
8 error node v8.9.3
9 error npm  v3.10.10
10 error code MODULE_NOT_FOUND
11 error Cannot find module 'realize-package-specifier'
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]

**Comment by JeffML** [comment]
This just happened to me, out of nowhere. node v6.11.2, npm 3.10.10

**Comment by LeoWang1991** [comment]
i encounter this issue, any solution? npm 4.2.0/node 6.5.0

**Comment by alexandervalencia** [comment]
One minute everything is working fine... the next, this error shows up

```
npm install
npm ERR! Darwin 16.7.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.12.0
npm ERR! npm  v3.10.10
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'realize-package-specifier'
```

node v6.12.0 npm v3.10.10

**Comment by jackvial** [comment]
+1

**Comment by juzhen21510** [comment]
+1

**Comment by nihsmik** [comment]
Same issue. node v6.10.3 npm 3.10.10

**Comment by mdo5004** [comment]
+1 

node v.6.11.5, npm 3.10.10

**Comment by nvms** [comment]
+1

node v6.12.3, npm 3.10.10

**Comment by ShumRain** [comment]
+1
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10

**Comment by legodude17** [comment]
It appears your `npm` installation has been broken somehow. Try reinstalling `node` (and `npm`, by extension).
