### ISSUE TITLE
ionic cordova run android not workingg !!!

### ISSUE THREAD

**Issue by Perolanegra** [npm/npm#19597]
until now it was working, and suddenly this happens: 

`Error: Failed to transpile program
    at new BuildError (C:\Users\ozie\Documents\workspace\ionic\node_modules\@ionic\app-scripts\dist\util\errors.js:16:28)
    at C:\Users\ozie\Documents\workspace\ionic\node_modules\@ionic\app-scripts\dist\transpile.js:159:20
    at new Promise (<anonymous>)
    at transpileWorker (C:\Users\ozie\Documents\workspace\ionic\node_modules\@ionic\app-scripts\dist\transpile.js:107:12)
    at Object.transpile (C:\Users\ozie\Documents\workspace\ionic\node_modules\@ionic\app-scripts\dist\transpile.js:64:12)
    at C:\Users\ozie\Documents\workspace\ionic\node_modules\@ionic\app-scripts\dist\build.js:109:82
    at <anonymous>`

**Comment by Perolanegra** [comment]
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@5.5.1
3 info using node@v8.9.2
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle myApp@0.0.1~prebuild: myApp@0.0.1
6 info lifecycle myApp@0.0.1~build: myApp@0.0.1
7 verbose lifecycle myApp@0.0.1~build: unsafe-perm in lifecycle true
8 verbose lifecycle myApp@0.0.1~build: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\ozie\Documents\workspace\ionic\node_modules\.bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\ozie\bin;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files\nodejs;C:\Program Files\Git\cmd;C:\Program Files\dotnet;C:\Program Files\Microsoft SQL Server\130\Tools\Binn;C:\Users\ozie\AppData\Local\Microsoft\WindowsApps;C:\Users\ozie\AppData\Roaming\npm;C:\Program Files\Microsoft VS Code\bin
9 verbose lifecycle myApp@0.0.1~build: CWD: C:\Users\ozie\Documents\workspace\ionic
10 silly lifecycle myApp@0.0.1~build: Args: [ '/d /s /c', 'ionic-app-scripts build' ]
11 silly lifecycle myApp@0.0.1~build: Returned: code: 1  signal: null
12 info lifecycle myApp@0.0.1~build: Failed to exec build script
13 verbose stack Error: myApp@0.0.1 build: `ionic-app-scripts build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:280:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid myApp@0.0.1
15 verbose cwd C:\Users\ozie\Documents\workspace\ionic
16 verbose Windows_NT 10.0.15063
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v8.9.2
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 1
22 error myApp@0.0.1 build: `ionic-app-scripts build`
22 error Exit status 1
23 error Failed at the myApp@0.0.1 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```
