### ISSUE TITLE
Unhandled error in event

### ISSUE THREAD

**Issue by TrayserCassa** [npm/npm#19634]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

Well I try 'sudo npm install -g ionic' and I get this Error:

> sudo npm install -g ionic
Error: read ENOTCONN
    at _errnoException (util.js:1003:13)
    at Socket._read (net.js:495:20)
    at Socket.Readable.read (_stream_readable.js:449:10)
    at Socket.read (net.js:376:43)
    at new Socket (net.js:259:12)
    at createSocket (internal/child_process.js:241:11)
    at ChildProcess.spawn (internal/child_process.js:357:23)
    at exports.spawn (child_process.js:499:9)
    at Object.exports.execFile (child_process.js:209:15)
    at uidNumber (/usr/lib/node_modules/npm/node_modules/uid-number/uid-number.js:33:17)
    at Conf.loadUid (/usr/lib/node_modules/npm/lib/config/load-uid.js:11:5)
    at Conf.<anonymous> (/usr/lib/node_modules/npm/lib/config/core.js:235:10)
    at Conf.setUser (/usr/lib/node_modules/npm/lib/config/set-user.js:15:34)
    at Conf.loadExtras (/usr/lib/node_modules/npm/lib/config/core.js:233:8)
    at Conf.<anonymous> (/usr/lib/node_modules/npm/lib/config/core.js:173:12)
    at Object.onceWrapper (events.js:255:19)
/usr/lib/node_modules/npm/lib/npm.js:61
      throw new Error('npm.load() required')
      ^

> Error: npm.load() required
    at Object.get (/usr/lib/node_modules/npm/lib/npm.js:61:13)
    at process.errorHandler (/usr/lib/node_modules/npm/lib/utils/error-handler.js:205:18)
    at process.emit (events.js:160:13)
    at process._fatalException (bootstrap_node.js:386:26)

npm install ionic works fine... 
Because Ionic crashed too, I think node change something in event.js. 
Or I am stupid.

### supporting information:

 - `npm -v` prints:  5.6.0
 - `node -v` prints: v9.4.0
 - `npm config get registry` prints:   https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Arch Linux
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by sanderkoenders** [comment]
Same configuration here, same problem, since today.

**Edit:** I downgraded to node version v8.9.4 and it works for now, seems to affect node v9.4.0 only.

**Comment by BillGR17** [comment]
I am having the same problem when i am using npm on anything! installing updating  or starting  apps.
I am using Arch Linux with all the latest updates.
I am not working any proxy!
node v9.4.0
npm 5.6.0

**Comment by crazykay** [comment]
same problem, since today
Error: read ENOTCONN
    at _errnoException (util.js:1003:13)
    at Socket._read (net.js:495:20)
    at Socket.Readable.read (_stream_readable.js:449:10)
    at Socket.read (net.js:376:43)
    at new Socket (net.js:259:12)
    at createSocket (internal/child_process.js:241:11)
    at ChildProcess.spawn (internal/child_process.js:357:23)
    at exports.spawn (child_process.js:499:9)
    at Object.exports.execFile (child_process.js:209:15)
...

**Comment by TrayserCassa** [comment]
So maybe my updatelogs will help, since it is a problem with the new Version. 

>[2018-01-18 08:18] [PACMAN] Running 'pacman -Syu'
[2018-01-18 08:18] [PACMAN] synchronizing package lists
[2018-01-18 08:18] [PACMAN] starting full system upgrade
[2018-01-18 08:18] [ALPM] transaction started
[2018-01-18 08:18] [ALPM] upgraded libuv (1.18.0-1 -> 1.19.0-1)
[2018-01-18 08:18] [ALPM] upgraded telegram-desktop (1.2.6-4 -> 1.2.6-5)
[2018-01-18 08:18] [ALPM] transaction completed
[2018-01-18 08:18] [ALPM] running 'gtk-update-icon-cache.hook'...
[2018-01-18 08:18] [ALPM] running 'systemd-update.hook'...
[2018-01-18 08:18] [ALPM] running 'update-desktop-database.hook'...
[2018-01-18 09:27] [PACMAN] Running 'pacman -R pmn'
[2018-01-18 09:27] [PACMAN] Running 'pacman -R npm'
[2018-01-18 09:28] [ALPM] transaction started
[2018-01-18 09:28] [ALPM] removed npm (5.6.0-1)
[2018-01-18 09:28] [ALPM] transaction completed
[2018-01-18 09:28] [ALPM] running 'systemd-update.hook'...
[2018-01-18 09:28] [PACMAN] Running 'pacman -R semver'
[2018-01-18 09:28] [ALPM] transaction started
[2018-01-18 09:28] [ALPM] removed semver (5.5.0-1)
[2018-01-18 09:28] [ALPM] transaction completed
[2018-01-18 09:28] [ALPM] running 'systemd-update.hook'...
[2018-01-18 09:28] [PACMAN] Running 'pacman -S npm'
[2018-01-18 09:28] [ALPM] transaction started
[2018-01-18 09:28] [ALPM] installed semver (5.5.0-1)
[2018-01-18 09:28] [ALPM] installed npm (5.6.0-1)
[2018-01-18 09:28] [ALPM] transaction completed
[2018-01-18 09:28] [ALPM] running 'systemd-update.hook'...
[2018-01-18 09:53] [PACMAN] Running 'pacman -Syu'
[2018-01-18 09:53] [PACMAN] synchronizing package lists
[2018-01-18 09:53] [PACMAN] starting full system upgrade


node update:
> [2017-12-22 13:34] [ALPM] installed nodejs (9.3.0-1)
[2018-01-11 09:37] [ALPM] upgraded nodejs (9.3.0-1 -> 9.4.0-1)

**Comment by TrayserCassa** [comment]
Same Error with node v9.3.0

**Comment by sanderkoenders** [comment]
For ArchLinux repositories:

**Npm** was last updated: 2017-12-02 (version 5.6.0-1)
**NodeJS** was last updated: 2018-01-10 (version 9.4.0-1)

**Comment by TrayserCassa** [comment]
Ok I found the dependency problem:

[2018-01-18 08:18] [ALPM] upgraded libuv (1.18.0-1 -> 1.19.0-1)

I Downgrade only libuv and i can install ionic globally

To downgrade for ArchLinux:
sudo pacman -U /var/cache/pacman/pkg/libuv-1.18.0-1-x86_64.pkg.tar.xz

**Comment by danbruegge** [comment]
Same problem here with archlinux.
```
$ npm -v
5.6.0
$ node -v
v8.9.4
```
Downgrade to libuv 1.18.0-1 solved the problem for the moment.

**Comment by sanderkoenders** [comment]
Response on the issue @ libuv: https://github.com/libuv/libuv/issues/1716#issuecomment-358591265

>Oh, and to be clear, the real bug is most likely on the node.js side, the newest libuv release merely exposes it. But we'll be reverting the libuv change for now until things get fixed in node.js.

**Comment by aksel** [comment]
Why was the issue closed?
Downgrading libuv fixes it, but surely the actual cause of the bug is still there, no?

**Comment by mgian** [comment]
It seems that downgrading libuv expose another problem:

```
gian@valkyrie ~ >su -c 'pacman -U libuv-1.8.0-1-x86_64.pkg.tar.xz'
Password: 
loading packages...
warning: downgrading package libuv (1.19.0-1 => 1.8.0-1)
resolving dependencies...
looking for conflicting packages...

Packages (1) libuv-1.8.0-1

Total Installed Size:   0.34 MiB
Net Upgrade Size:      -0.10 MiB

:: Proceed with installation? [Y/n] 
(1/1) checking keys in keyring                                                                                 [##################################################################] 100%
(1/1) checking package integrity                                                                               [##################################################################] 100%
(1/1) loading package files                                                                                    [##################################################################] 100%
(1/1) checking for file conflicts                                                                              [##################################################################] 100%
(1/1) checking available disk space                                                                            [##################################################################] 100%
:: Processing package changes...
(1/1) downgrading libuv                                                                                        [##################################################################] 100%
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
gian@valkyrie ~ >npm 
node: symbol lookup error: node: undefined symbol: uv_os_free_passwd
gian@valkyrie ~ >

```

**Comment by sanderkoenders** [comment]
> Why was the issue closed?
Downgrading libuv fixes it, but surely the actual cause of the bug is still there, no?

Because it's not an issue with npm, see https://github.com/nodejs/node/issues/18225 and https://github.com/libuv/libuv/pull/1717

**EDIT:** The actual issue seems to be caused by Node and triggerd by a change in libuv. Libuv is reverting the last change untill node is patched. Everything should work properly when a new version of libuv is published and picked up by your distribution (in my case Archlinux).

**Comment by aksel** [comment]
Ah okay 😄

**Comment by hg8** [comment]
Downgrade for those who don't have the `libuv` package in cache (Arch Linux) : 

```
$ wget https://archive.archlinux.org/packages/l/libuv/libuv-1.18.0-1-x86_64.pkg.tar.xz
$ sudo pacman -U libuv-1.18.0-1-x86_64.pkg.tar.xz 
```

@FrozenDroid Fixed thanks!

**Comment by FrozenDroid** [comment]
@hg8 This should be `libuv-1.18.0-1` instead.

**Comment by hg8** [comment]
@mgian It's `libuv-1.18.0-1` and not `libuv-1.8.0-1`

**Comment by sanderkoenders** [comment]
It seems like installing a node version with nvm resolves the problem because it will also download the bundled version of libuv that is working just fine (it's another version).
