### ISSUE TITLE
Error: Unknown type | in argument #4

### ISSUE THREAD

**Issue by gavinwyf** [npm/npm#19656]
npm info it worked if it ends with ok
npm verb cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'install' ]
npm info using npm@5.6.0
npm info using node@v9.4.0
npm verb npm-session 03d785315a45fc19
npm verb stack Error: Unknown type | in argument #4
npm verb stack     at new Installer (/usr/local/lib/node_modules/npm/lib/install.js:206:3)
npm verb stack     at EventEmitter.install (/usr/local/lib/node_modules/npm/lib/install.js:202:3)
npm verb stack     at Object.commandCache.(anonymous function) (/usr/local/lib/node_modules/npm/lib/npm.js:159:13)
npm verb stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:84:30)
npm verb stack     at process._tickCallback (internal/process/next_tick.js:150:11)
npm verb cwd /Users/qitmac000524/Documents/workspace/Bitcoin/tenWeb
npm verb Darwin 17.3.0
npm verb argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm verb node v9.4.0
npm verb npm  v5.6.0
npm ERR! code EUNKNOWNTYPE
npm ERR! typeerror Error: Unknown type | in argument #4
npm ERR! typeerror     at new Installer (/usr/local/lib/node_modules/npm/lib/install.js:206:3)
npm ERR! typeerror     at EventEmitter.install (/usr/local/lib/node_modules/npm/lib/install.js:202:3)
npm ERR! typeerror     at Object.commandCache.(anonymous function) (/usr/local/lib/node_modules/npm/lib/npm.js:159:13)
npm ERR! typeerror     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:84:30)
npm ERR! typeerror     at process._tickCallback (internal/process/next_tick.js:150:11)
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <https://github.com/npm/npm/issues>
npm verb exit [ 1, true ]
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/qitmac000524/.npm/_logs/2018-01-21T15_27_47_615Z-debug.log

**Comment by danieldafoe** [comment]
Getting this as well. This happened to me after installing Xcode (after I already had the command line tools installed.)

**Comment by floer32** [comment]
@danieldafoe seems to be same cause for me as well

**Comment by floer32** [comment]
BTW what worked as a workaround for me... macOS Sierra

* `brew` uninstall existing node installation that was broken. It partly worked, partly choked on some files. 
* Got those files out of the way (I like to use `trash-cli` but that was borked too, so I did `mv` to `/tmp`; I **avoid** ~`rm`~ for experimental changes like this.) 
* Then `brew uninstall` which only removed like 64B (not even kb) since was just unregistering, since I'd moved the the files out of the way.

then clean `brew install` then remember to trash/reinstall any `npm install --global` things you need to do. For me that was `sudo npm install -g n trash-cli`, that's about all I keep global.

Maybe there's a cleaner way but I bet that workaround will work for most macOS users who are comfortable messing with `brew`'s files 😉 

----

To the maintainers, IMHO: If indeed we think this is from Xcode, and this workaround works for others... Then I'd say it's not worth the effort to address directly in npm. Since this should only affect older version(s) of npm and probably not _all_ Xcode users, judging based on not many issue reports. 

Mac/`brew` have their little quirks, the onus is on us as Mac users I think
