### ISSUE TITLE
NPM on Windows 10 cannot find babel-core@^7.0.0-bridge.0 when requesting babel-core@^7.0.0-0

### ISSUE THREAD

**Issue by denizdogan** [npm/npm#19653]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I'm trying to install `babel-core@7.0.0-bridge.0` by requesting `babel-core@^7.0.0-0`, as such:

    $ npm i -D babel-core@^7.0.0-0

NPM cannot find any package, but I expect it to find `babel-core@7.0.0-bridge.0`, because it works for another user with a different OS. See the discussion here: https://github.com/facebook/jest/issues/5352#event-1433702044

#### How can the CLI team reproduce the problem?

On Windows 10, run:

    $ npm cache clear --force
    $ npm i -D babel-core@^7.0.0-0

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\E\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'i',
1 verbose cli   '-D',
1 verbose cli   'babel-core@7.0.0-0' ]
2 info using npm@5.6.0
3 info using node@v9.4.0
4 verbose config Skipping project config: C:\Users\E/.npmrc. (matches userconfig)
5 verbose npm-session e1774827a4edf442
6 silly install loadCurrentTree
7 silly install readLocalPackageData
8 http fetch GET 200 https://registry.npmjs.org/babel-core 113ms
9 silly registry:manifest no matching version for babel-core@7.0.0-0 in the cache. Forcing revalidation
10 http fetch GET 304 https://registry.npmjs.org/babel-core 45ms (from cache)
11 silly fetchPackageMetaData error for babel-core@7.0.0-0 No matching version found for babel-core@7.0.0-0
12 verbose type version
13 verbose stack babel-core: No matching version found for babel-core@7.0.0-0
13 verbose stack     at pickManifest (C:\Users\E\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\node_modules\npm-pick-manifest\index.js:65:11)
13 verbose stack     at fetchPackument.then.packument (C:\Users\E\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\lib\fetchers\registry\manifest.js:52:18)
13 verbose stack     at tryCatcher (C:\Users\E\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
13 verbose stack     at Promise._settlePromiseFromHandler (C:\Users\E\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
13 verbose stack     at Promise._settlePromise (C:\Users\E\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
13 verbose stack     at Promise._settlePromise0 (C:\Users\E\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
13 verbose stack     at Promise._settlePromises (C:\Users\E\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
13 verbose stack     at Async._drainQueue (C:\Users\E\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
13 verbose stack     at Async._drainQueues (C:\Users\E\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
13 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\E\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
13 verbose stack     at runCallback (timers.js:756:18)
13 verbose stack     at tryOnImmediate (timers.js:717:5)
13 verbose stack     at processImmediate [as _immediateCallback] (timers.js:697:5)
14 verbose cwd C:\Users\E\Documents\GitHub\temp
15 verbose Windows_NT 10.0.15063
16 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\E\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "i" "-D" "babel-core@7.0.0-0"
17 verbose node v9.4.0
18 verbose npm  v5.6.0
19 error code ETARGET
20 error notarget No matching version found for babel-core@7.0.0-0
21 error notarget In most cases you or one of your dependencies are requesting
21 error notarget a package version that doesn't exist.
22 verbose exit [ 1, true ]
```

### supporting information:

 - `npm -v` prints: 5.6.0
 - `node -v` prints: 9.4.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows 10 (64-bit)
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by AleksOrl** [comment]
Same error with 
`npm i -D babel-core@^7.0.0-0`
but works fine with
`npm i -D babel-core@^7.0.0-bridge.0`

**Comment by xlijun** [comment]
Same error, use npm i -D babel-core@^7.0.0-bridge.0 to byPass this issue
