### ISSUE TITLE
MODULE_NOT_FOUND error when trying to install CLI via npm

### ISSUE THREAD

**Issue by tfierens** [npm/npm#19679]
Hi,
I've installed node.js 8.9.4 (LTS) and when running the following command from Powershell (Running as Admin):

``npm install -g @angular/cli

I get the following error:

npm ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Me\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\np``m-cli.js" "install" "-g" "@angular/cli"
npm ERR! node v8.9.4
npm ERR! npm  v3.6.0
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'internal/util/types'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\WINDOWS\system32\npm-debug.log

The npm.debug.log contains the following:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Me\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   '@angular/cli' ]
2 info using npm@3.6.0
3 info using node@v8.9.4
4 verbose stack Error: Cannot find module 'internal/util/types'
4 verbose stack     at Function.Module._resolveFilename (module.js:538:15)
4 verbose stack     at Function.Module._load (module.js:468:25)
4 verbose stack     at Module.require (module.js:587:17)
4 verbose stack     at require (internal/module.js:11:18)
4 verbose stack     at evalmachine.<anonymous>:31:26
4 verbose stack     at Object.<anonymous> (C:\Users\Me\AppData\Roaming\npm\node_modules\npm\node_modules\cmd-shim\node_modules\graceful-fs\fs.js:11:1)
4 verbose stack     at Module._compile (module.js:643:30)
4 verbose stack     at Object.Module._extensions..js (module.js:654:10)
4 verbose stack     at Module.load (module.js:556:32)
4 verbose stack     at tryModuleLoad (module.js:499:12)
5 verbose cwd C:\WINDOWS\system32
6 error Windows_NT 10.0.16299
7 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Me\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@angular/cli"
8 error node v8.9.4
9 error npm  v3.6.0
10 error code MODULE_NOT_FOUND
11 error Cannot find module 'internal/util/types'
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]

Does anyone have any ideas how I can resolve this?

Thanks.

**Comment by jwverzijden** [comment]
1 verbose cli [ 'C:\Program Files\nodejs\node.exe',
1 verbose cli 'C:\Users\Me\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js',
1 verbose cli 'install',
1 verbose cli '-g',
1 verbose cli **_''_** ]

You can not install a package without a name. 
or are you attempting to globally install all your dependencies?

**Comment by tfierens** [comment]
The name of the package was definitely provided but I ended up finding a resolution on a other thread. In short,

1. I uninstalled nodejs
2. Removed environment variables for npm. 
3. Deleted npm and np_cache in %appdata%. Pretty sure that the one step that did the trick.
4. Reinstalled nodjs

That's it. After doing the above and I reinstalled  tools for Windows and angular and everything installed as expected.
