### ISSUE TITLE
Cannot associate a scope with a registry using npm config in Powershell

### ISSUE THREAD

**Issue by Ionaru** [npm/npm#19693]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
After I enter the command to [associate a scope with a registry using npm config](https://docs.npmjs.com/misc/scope#associating-a-scope-with-a-registry), the package I want to install fails with `E404`.
This happens for me when attempting to install a FontAwesome 5 Pro package.
```
PS C:\Users\Jeroen> npm config --verbose set @fortawesome:registry https://npm.fontawesome.com/PRIVATE_KEY
npm info it worked if it ends with ok
npm verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Users\\Jeroen\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'config',
npm verb cli   '--verbose',
npm verb cli   'set',
npm verb cli   'https://npm.fontawesome.com/PRIVATE_KEY' ]
npm info using npm@5.6.0
npm info using node@v9.4.0
npm verb config Skipping project config: C:\Users\Jeroen/.npmrc. (matches userconfig)
npm info config set "https://npm.fontawesome.com/PRIVATE_KEY" ""
npm verb exit [ 0, true ]
npm info
```

```
PS C:\Users\Jeroen> npm install --save @fortawesome/fontawesome-pro-solid
npm ERR! code E404
npm ERR! 404 Not Found: @fortawesome/fontawesome-pro-solid@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Jeroen\AppData\Roaming\npm-cache\_logs\2018-01-26T01_10_15_214Z-debug.log
```

Contents of debug file:
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Jeroen\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '--save',
1 verbose cli   '@fortawesome/fontawesome-pro-solid' ]
2 info using npm@5.6.0
3 info using node@v9.4.0
4 verbose config Skipping project config: C:\Users\Jeroen/.npmrc. (matches userconfig)
5 verbose npm-session 8bce67008d1e14e5
6 silly install loadCurrentTree
7 silly install readLocalPackageData
8 http fetch GET 404 https://registry.npmjs.org/@fortawesome%2ffontawesome-pro-solid 915ms
9 silly fetchPackageMetaData error for @fortawesome/fontawesome-pro-solid@latest 404 Not Found: @fortawesome/fontawesome-pro-solid@latest
10 verbose stack Error: 404 Not Found: @fortawesome/fontawesome-pro-solid@latest
10 verbose stack     at fetch.then.res (C:\Users\Jeroen\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\lib\fetchers\registry\fetch.js:42:19)
10 verbose stack     at tryCatcher (C:\Users\Jeroen\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
10 verbose stack     at Promise._settlePromiseFromHandler (C:\Users\Jeroen\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
10 verbose stack     at Promise._settlePromise (C:\Users\Jeroen\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
10 verbose stack     at Promise._settlePromise0 (C:\Users\Jeroen\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
10 verbose stack     at Promise._settlePromises (C:\Users\Jeroen\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
10 verbose stack     at Async._drainQueue (C:\Users\Jeroen\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
10 verbose stack     at Async._drainQueues (C:\Users\Jeroen\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
10 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\Jeroen\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
10 verbose stack     at runCallback (timers.js:756:18)
10 verbose stack     at tryOnImmediate (timers.js:717:5)
10 verbose stack     at processImmediate [as _immediateCallback] (timers.js:697:5)
11 verbose cwd C:\Users\Jeroen
12 verbose Windows_NT 10.0.16299
13 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Jeroen\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "@fortawesome/fontawesome-pro-solid"
14 verbose node v9.4.0
15 verbose npm  v5.6.0
16 error code E404
17 error 404 Not Found: @fortawesome/fontawesome-pro-solid@latest
18 verbose exit [ 1, true ]
```

Contents of `.npmrc`:
```
https://npm.fontawesome.com/PRIVATE_KEY=
(The "=" is not part of the private key)
```

#### How can the CLI team reproduce the problem?
In Powershell:
```
npm config set @fortawesome:registry https://npm.fontawesome.com/PRIVATE_KEY
npm install @fortawesome/fontawesome-pro-solid
```

#### Supporting information:

 - `npm -v` prints: 5.6.0
 - `node -v` prints: v9.4.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows 10
 - Shell: Windows Powershell
 - Network issues: N/A

#### Sidenote:
I get a different result with this command:
```
npm config set registry https://npm.fontawesome.com/PRIVATE_KEY --scope=@fortawesome
```
After running the above command, my `.npmrc` file looks like this:
```
registry=https://npm.fontawesome.com/PRIVATE_KEY
```
And I am able to install the `@fortawesome/fontawesome-pro-solid` package without issue.

**Comment by abhishekdev** [comment]
Failed for me as well. But then figured that I needed to escape the `@` in powershell to make it work fine.

```diff
--- npm config --verbose set @fortawesome:registry https://npm.fontawesome.com/PRIVATE_KEY
+++ npm config --verbose set `@fortawesome:registry https://npm.fontawesome.com/PRIVATE_KEY
```

> NOTE: I do not need to escape the '@' for the install command. Seems we might have an opportunity to fix this in npm code.

Hope this helps.
