### ISSUE TITLE
npm help

### ISSUE THREAD

**Issue by D3M3NTOS** [npm/npm#19710]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@2.15.11
3 info using node@v0.12.18
4 verbose node symlink /usr/bin/node
5 verbose stack Error: missing script: start
5 verbose stack     at run (/usr/lib/node_modules/npm/lib/run-script.js:142:19)
5 verbose stack     at /usr/lib/node_modules/npm/lib/run-script.js:58:5
5 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:356:5
5 verbose stack     at checkBinReferences_ (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:320:45)
5 verbose stack     at final (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:354:3)
5 verbose stack     at then (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:124:5)
5 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:295:20
5 verbose stack     at /usr/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
5 verbose stack     at fs.js:263:20
5 verbose stack     at /usr/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:232:16
6 verbose cwd /home/bot
7 error Linux 3.2.0-4-amd64
8 error argv "/usr/bin/node" "/usr/bin/npm" "start"
9 error node v0.12.18
10 error npm  v2.15.11
11 error missing script: start
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]

**Comment by D3M3NTOS** [comment]
i use previus commans
cd /home/bot
-npm install mysql
-npm install log4js
-npm install socket.io
-npm install request
-npm install fs
-npm install md5
-npm install sha256
-npm install mathjs
-npm install forever-monitor
-npm install forever -g
-npm install steamcommunity
-npm install steam-totp
-npm install steam-tradeoffers
-npm install async
-npm install engine.io



npm isntal expess or i dont know , 
and package.json



{
  "name": "npm",
  "version": "1.0.0",
  "main": "site.js",
  "dependencies": {
    "async": "^2.6.0",
    "engine.io": "^3.1.4",
    "forever-monitor": "^1.7.1",
    "fs": "^0.0.1-security",
    "log4js": "^2.5.2",
    "mathjs": "^3.20.1",
    "md5": "^2.2.1",
    "mysql": "^2.15.0",
    "request": "^2.83.0",
    "sha256": "^0.2.0",
    "socket.io": "^2.0.4",
    "steam-totp": "^2.0.1",
    "steam-tradeoffers": "^3.1.0",
    "steamcommunity": "^3.34.1"
  },
  "devDependencies": {},
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "description": ""
}

**Comment by rjoonas** [comment]
`Error: missing script: start` means you haven't defined a start script in your package.json. Looks like you only have the `test` script there.

You've declared site.js as your module's entry point (`main` field). If this is the file you're trying to run, add `"scripts": { "start": "node site.js" }` to package.json.

You should upgrade your node as well – support for node 0.12 ended in 2016.
