### ISSUE TITLE
Module.js:540 throw err; npm not starting up

### ISSUE THREAD

**Issue by misfityudi** [npm/npm#19741]
Vikass-MacBook-Pro:vstv-frontend vikaschahar$ npm start

> vstv-frontend@0.0.0 start /Users/vikaschahar/vstv-frontend
> node ./bin/www

module.js:540
    throw err;
    ^

Error: Cannot find module '/Users/vikaschahar/vstv-frontend/bin/www'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vstv-frontend@0.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vstv-frontend@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/vikaschahar/.npm/_logs/2018-02-05T09_32_13_259Z-debug.log

**Comment by kenany** [comment]
Does `./bin/www` exist?

**Comment by deTrust** [comment]
I am getting the same error please help

**Comment by samliebl** [comment]
Same error on my end. Just ran repair with Node 8.9.4 and restarted. This error again. On my Win10 machine only; no problems on macOS. Has anyone found a solution?

**Comment by deTrust** [comment]
I got it fixed by doing fresh install of npm and avoid using git bash use
the windows command line

On 02 Mar 2018 12:08 PM, "Sam Liebl" <notifications@github.com> wrote:

Same error on my end. Just ran repair with Node 8.9.4 and restarted. This
error again. On my Win10 machine only; no problems on macOS. Has anyone
found a solution?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/npm/npm/issues/19741#issuecomment-369879630>, or mute
the thread

**Comment by sachinhd517** [comment]
PS C:\Users\Sachinhd517> ng new AngularCrud --skip-tests true
installing ng
  create .editorconfig
  create README.md
  create src\app\app.component.css
  create src\app\app.component.html
  create src\app\app.component.ts
  create src\app\app.module.ts
  create src\assets\.gitkeep
  create src\environments\environment.prod.ts
  create src\environments\environment.ts
  create src\favicon.ico
  create src\index.html
  create src\main.ts
  create src\polyfills.ts
  create src\styles.css
  create src\test.ts
  create src\tsconfig.app.json
  create src\tsconfig.spec.json
  create src\typings.d.ts
  create .angular-cli.json
  create e2e\app.e2e-spec.ts
  create e2e\app.po.ts
  create e2e\tsconfig.e2e.json
  create .gitignore
  create karma.conf.js
  create package.json
  create protractor.conf.js
  create tsconfig.json
  create tslint.json
Installing packages for tooling via npm.
module.js:540
    throw err;
    ^

Error: Cannot find module 'ini'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Sachinhd517\AppData\Roaming\npm\node_modules\npm\node_modules\config-chain\index.js:4:11)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)

Package install failed, see above.
Package install failed, see above.

I am going to same error

**Comment by allenbrooks55** [comment]
Same here. I'm on Windows 10 v1709. Any update on this?

**Comment by ayazzali** [comment]
do you have 'menu' element in your package?
Сause i had the same error and fixed here https://github.com/peter-ahr/jsonPrototypeJS/pull/2/commits/f77d12ac7db0358ee5a1008c1514691776f04d7a
