### ISSUE TITLE
npm ERR! cb() never called!

### ISSUE THREAD

**Issue by spekulatius** [npm/npm#19759]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:

    vagrant@ubuntu-xenial:~$ npm -v 
    5.0.0

 - `node -v` prints:

    vagrant@ubuntu-xenial:~$ node -v
    v8.0.0

 - `npm config get registry` prints:

    vagrant@ubuntu-xenial:~$ npm config get registry
    https://registry.npmjs.org/

 - Windows, OS X/macOS, or Linux?:

    Linux: Ubuntu Xenial in a Vagrant box, fresh install

 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [x] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by spekulatius** [comment]
Command:

    vagrant@ubuntu-xenial:~$ npm install
    Unhandled rejection Error: Argument #2: Expected string but got nullealTree
        at addDependency (/home/vagrant/.nvm/versions/node/v8.0.0/lib/node_modules/npm/lib/install/deps.js:515:3)
        at /home/vagrant/.nvm/versions/node/v8.0.0/lib/node_modules/npm/lib/install/deps.js:463:5
        at /home/vagrant/.nvm/versions/node/v8.0.0/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
        at Array.forEach (native)
        at /home/vagrant/.nvm/versions/node/v8.0.0/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
        at Array.forEach (native)
        at asyncMap (/home/vagrant/.nvm/versions/node/v8.0.0/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
        at loadDeps (/home/vagrant/.nvm/versions/node/v8.0.0/lib/node_modules/npm/lib/install/deps.js:455:3)
        at Array.<anonymous> (/home/vagrant/.nvm/versions/node/v8.0.0/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
        at LOOP (/home/vagrant/.nvm/versions/node/v8.0.0/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
        at /home/vagrant/.nvm/versions/node/v8.0.0/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
        at /home/vagrant/.nvm/versions/node/v8.0.0/lib/node_modules/npm/lib/install/and-finish-tracker.js:8:8
        at resolveBranchDeps.then (/home/vagrant/.nvm/versions/node/v8.0.0/lib/node_modules/npm/lib/install/deps.js:419:11)
        at tryCatcher (/home/vagrant/.nvm/versions/node/v8.0.0/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
        at Promise._settlePromiseFromHandler (/home/vagrant/.nvm/versions/node/v8.0.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
        at Promise._settlePromise (/home/vagrant/.nvm/versions/node/v8.0.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
    
    npm ERR! cb() never called!
    
    npm ERR! This is an error with npm itself. Please report this error at:
    npm ERR!     <https://github.com/npm/npm/issues>
    
    npm ERR! A complete log of this run can be found in:
    npm ERR!     /home/vagrant/.npm/_logs/2018-02-06T12_03_06_963Z-debug.log

**Comment by spekulatius** [comment]
package.json:

    {
      "name": "removed",
      "version": "1.0.0",
      "description": "",
      "main": "index.js",
      "dependencies": {
        "chrome-remote-interface": "^0.25.5",
        "minimist": "^1.2.0",
        "mysql": "^2.15.0"
      },
      "devDependencies": {},
      "scripts": {
        "test": "echo \"Error: no test specified\" && exit 1"
      },
      "repository": {
        "type": "git",
        "url": "git+ssh://git@removed"
      },
      "author": "Peter Thaleikis",
      "license": "UNLICENSED",
      "homepage": "https://removed.com"
    }
