### ISSUE TITLE
npm fails when trying to pipe to a dynamically downloaded shell script

### ISSUE THREAD

**Issue by tobilg** [npm/npm#19752]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I'm trying to pipe lcov coverage info to a dynamically downloaded shell script. npm fails with

```bash
...
10 silly lifecycle ci-tests@0.1.0~coverage: Args: [ '-c',
10 silly lifecycle   'nyc report --reporter=text-lcov | bash <(curl -s -o- -L https://gist.githubusercontent.com/tobilg/99a65039536341dc8ca839ec570f3bc1/raw/219cea550d4bd5012ad83fa87a43d87a279f128d/test.sh)' ]
11 silly lifecycle ci-tests@0.1.0~coverage: Returned: code: 2  signal: null
12 info lifecycle ci-tests@0.1.0~coverage: Failed to exec coverage script
13 verbose stack Error: ci-tests@0.1.0 coverage: `nyc report --reporter=text-lcov | bash <(curl -s -o- -L https://gist.githubusercontent.com/tobilg/99a65039536341dc8ca839ec570f3bc1/raw/219cea550d4bd5012ad83fa87a43d87a279f128d/test.sh)`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:927:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid ci-tests@0.1.0
15 verbose cwd /Users/tobilg/Development/ci-tests
16 verbose Darwin 17.3.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "coverage"
18 verbose node v8.6.0
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 2
22 error ci-tests@0.1.0 coverage: `nyc report --reporter=text-lcov | bash <(curl -s -o- -L https://gist.githubusercontent.com/tobilg/99a65039536341dc8ca839ec570f3bc1/raw/219cea550d4bd5012ad83fa87a43d87a279f128d/test.sh)`
22 error Exit status 2
23 error Failed at the ci-tests@0.1.0 coverage script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]
```

#### How can the CLI team reproduce the problem?

When run manually in the terminal, the command

```bash
$ node_modules/.bin/nyc report --reporter=text-lcov | bash <(curl -s -o- -L https://gist.githubusercontent.com/tobilg/99a65039536341dc8ca839ec570f3bc1/raw/219cea550d4bd5012ad83fa87a43d87a279f128d/test.sh)
```

succeeds. When using the same via package.json, it fails with the above error message.

```javascript
{
  "scripts": {
    "coverage": "nyc report --reporter=text-lcov | bash <(curl -s -o- -L https://gist.githubusercontent.com/tobilg/99a65039536341dc8ca839ec570f3bc1/raw/219cea550d4bd5012ad83fa87a43d87a279f128d/test.sh)"
  }
}
```

### supporting information:

 - `npm -v` prints: 5.6.0
 - `node -v` prints: v8.6.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Mac OS
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by tobilg** [comment]
I found the solution myself in a [Stackoverflow answer](https://stackoverflow.com/a/40791249/1603357):

```javascript
{
  "scripts": {
    "coverage": "bash -c 'nyc report --reporter=text-lcov | bash <(curl -s -o- -L https://gist.githubusercontent.com/tobilg/99a65039536341dc8ca839ec570f3bc1/raw/219cea550d4bd5012ad83fa87a43d87a279f128d/test.sh) || exit 0'"
  }
}
```
