### ISSUE TITLE
403 errors when installing from private repository

### ISSUE THREAD

**Issue by gumallett** [npm/npm#19765]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

We use a private Nexus repository to connect to the npm registry.  Installing a package fails with a 403 error, e.g:
$ npm install webpack-merge --loglevel http
npm http fetch GET 403 http://nexus.mycompany.com/nexus/content/groups/npm-all/webpack-merge 145ms
npm ERR! code E403
npm ERR! 403 Forbidden: webpack-merge@^4.1.1

This works on npm@3 and npm@5.0.4.  Fails with 403 on 5.5.1.  We are using a _auth property in our npmrc file for publishing to Nexus, and installs start working in 5.5.1 after removing the _auth.  

### supporting information:

 - `npm -v` prints: 5.5.1
 - `node -v` prints: 6.11.5
 - `npm config get registry` prints: private Nexus repository
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by KerriDevine** [comment]
I think this is the same issue as #18567 - The title is a bit of a misnomer, since I don't think it's related to a proxy

**Comment by jrtitus** [comment]
I'm actually trying to set up a Nexus server also, however, I'm noticing that NPM itself is failing with a `403 Forbidden`, even when it's referencing https://registry.npmjs.org. I'm unable to make progress, and it doesn't seem like the private repository is the issue.

`npm config get proxy` returns a reference to the corporate proxy server.

`npm -v` -- `5.6.0`
`node -v` -- `v8.9.4`
```
$ npm i npm@latest -g
npm ERR! code E403
npm ERR! 403 Forbidden: npm@latest
```
Log File:
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\jrtitus\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'i',
1 verbose cli   'npm@latest',
1 verbose cli   '-g',
1 verbose cli   '--verbose' ]
2 info using npm@5.6.0
3 info using node@v8.9.4
4 verbose npm-session 55317ee6de3cadeb
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 403 https://registry.npmjs.org/npm 253ms
8 silly fetchPackageMetaData error for npm@latest 403 Forbidden: npm@latest
9 verbose stack Error: 403 Forbidden: npm@latest
9 verbose stack     at fetch.then.res (C:\Users\jrtitus\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\lib\fetchers\registry\fetch.js:42:19)
9 verbose stack     at tryCatcher (C:\Users\jrtitus\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
9 verbose stack     at Promise._settlePromiseFromHandler (C:\Users\jrtitus\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
9 verbose stack     at Promise._settlePromise (C:\Users\jrtitus\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
9 verbose stack     at Promise._settlePromise0 (C:\Users\jrtitus\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
9 verbose stack     at Promise._settlePromises (C:\Users\jrtitus\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
9 verbose stack     at Async._drainQueue (C:\Users\jrtitus\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
9 verbose stack     at Async._drainQueues (C:\Users\jrtitus\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
9 verbose stack     at Immediate.Async.drainQueues (C:\Users\jrtitus\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
9 verbose stack     at runCallback (timers.js:789:20)
9 verbose stack     at tryOnImmediate (timers.js:751:5)
9 verbose stack     at processImmediate [as _immediateCallback] (timers.js:722:5)
10 verbose cwd Y:\
11 verbose Windows_NT 10.0.14393
12 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\jrtitus\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "i" "npm@latest" "-g" "--verbose"
13 verbose node v8.9.4
14 verbose npm  v5.6.0
15 error code E403
16 error 403 Forbidden: npm@latest
17 verbose exit [ 1, true ]
```

The same occurs with any package. For example:
```
$ npm i -g chalk
npm ERR! code E403
npm ERR! 403 Forbidden: chalk@latest
```
