### ISSUE TITLE
Npm publish returned with error, still published

### ISSUE THREAD

**Issue by gergelybodor** [npm/npm#19763]
#### I'm opening this issue because:
  - npm is doing something I don't understand.

#### What's going wrong?
Tried publishing, publish command returned with error, still published to registry.

I have this log:

```$ cat /home/bgolyoo/.npm/_logs/2018-02-06T21_35_43_624Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/home/bgolyoo/.nvm/versions/node/v8.9.4/bin/node',
1 verbose cli   '/home/bgolyoo/.nvm/versions/node/v8.9.4/bin/npm',
1 verbose cli   'publish' ]
2 info using npm@5.6.0
3 info using node@v8.9.4
4 verbose npm-session 55ce17496e97f6fe
5 verbose publish [ '.' ]
6 info lifecycle ngx-height-toggle@1.0.3~prepublish: ngx-height-toggle@1.0.3
7 info lifecycle ngx-height-toggle@1.0.3~prepare: ngx-height-toggle@1.0.3
8 info lifecycle ngx-height-toggle@1.0.3~prepublishOnly: ngx-height-toggle@1.0.3
9 info lifecycle ngx-height-toggle@1.0.3~prepack: ngx-height-toggle@1.0.3
10 info lifecycle ngx-height-toggle@1.0.3~postpack: ngx-height-toggle@1.0.3
11 verbose getPublishConfig undefined
12 silly mapToRegistry name ngx-height-toggle
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry data { type: 'tag',
15 silly mapToRegistry   registry: true,
15 silly mapToRegistry   where: undefined,
15 silly mapToRegistry   raw: 'ngx-height-toggle',
15 silly mapToRegistry   name: 'ngx-height-toggle',
15 silly mapToRegistry   escapedName: 'ngx-height-toggle',
15 silly mapToRegistry   scope: undefined,
15 silly mapToRegistry   rawSpec: '',
15 silly mapToRegistry   saveSpec: null,
15 silly mapToRegistry   fetchSpec: 'latest',
15 silly mapToRegistry   gitRange: undefined,
15 silly mapToRegistry   gitCommittish: undefined,
15 silly mapToRegistry   hosted: undefined }
16 silly mapToRegistry uri https://registry.npmjs.org/ngx-height-toggle
17 verbose publish registryBase https://registry.npmjs.org/
18 silly publish uploading /tmp/npm-14534-19b757f3/tmp/fromDir-8aa8f983/package.tgz
19 verbose request uri https://registry.npmjs.org/ngx-height-toggle
20 verbose request sending authorization for write operation
21 info attempt registry request try #1 at 22:33:02
22 verbose request using bearer token for auth
23 verbose request id b1d49fa096d0725c
24 http request PUT https://registry.npmjs.org/ngx-height-toggle
25 http 503 https://registry.npmjs.org/ngx-height-toggle
26 verbose bad json <?xml version="1.0" encoding="utf-8"?>
26 verbose bad json <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
26 verbose bad json  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
26 verbose bad json <html>
26 verbose bad json   <head>
26 verbose bad json     <title>503 first byte timeout</title>
26 verbose bad json   </head>
26 verbose bad json   <body>
26 verbose bad json     <h1>Error 503 first byte timeout</h1>
26 verbose bad json     <p>first byte timeout</p>
26 verbose bad json     <h3>Guru Mediation:</h3>
26 verbose bad json     <p>Details: cache-hhn1523-HHN 1517952814 1039658159</p>
26 verbose bad json     <hr>
26 verbose bad json     <p>Varnish cache server</p>
26 verbose bad json   </body>
26 verbose bad json </html>
27 error registry error parsing json
28 verbose headers { server: 'Varnish',
28 verbose headers   'retry-after': '0',
28 verbose headers   'content-type': 'text/html; charset=utf-8',
28 verbose headers   'content-length': '448',
28 verbose headers   'accept-ranges': 'bytes',
28 verbose headers   date: 'Tue, 06 Feb 2018 21:33:33 GMT',
28 verbose headers   via: '1.1 varnish',
28 verbose headers   connection: 'close',
28 verbose headers   'x-served-by': 'cache-hhn1523-HHN',
28 verbose headers   'x-cache': 'MISS',
28 verbose headers   'x-cache-hits': '0',
28 verbose headers   'x-timer': 'S1517952783.818876,VS0,VE31148' }
29 info retry will retry, error on last attempt: SyntaxError: Unexpected token < in JSON at position 1
29 info retry
29 info retry <?xml version="1.0" encoding="utf-8"?>
29 info retry <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
29 info retry  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
29 info retry <html>
29 info retry   <head>
29 info retry     <title>503 first byte timeout</title>
29 info retry   </head>
29 info retry   <body>
29 info retry     <h1>Error 503 first byte timeout</h1>
29 info retry     <p>first byte timeout</p>
29 info retry     <h3>Guru Mediation:</h3>
29 info retry     <p>Details: cache-hhn1523-HHN 1517952814 1039658159</p>
29 info retry     <hr>
29 info retry     <p>Varnish cache server</p>
29 info retry   </body>
29 info retry </html>
30 info attempt registry request try #2 at 22:33:43
31 verbose request using bearer token for auth
32 http request PUT https://registry.npmjs.org/ngx-height-toggle
33 http 503 https://registry.npmjs.org/ngx-height-toggle
34 verbose bad json <?xml version="1.0" encoding="utf-8"?>
34 verbose bad json <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
34 verbose bad json  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
34 verbose bad json <html>
34 verbose bad json   <head>
34 verbose bad json     <title>503 first byte timeout</title>
34 verbose bad json   </head>
34 verbose bad json   <body>
34 verbose bad json     <h1>Error 503 first byte timeout</h1>
34 verbose bad json     <p>first byte timeout</p>
34 verbose bad json     <h3>Guru Mediation:</h3>
34 verbose bad json     <p>Details: cache-hhn1524-HHN 1517952856 4091369717</p>
34 verbose bad json     <hr>
34 verbose bad json     <p>Varnish cache server</p>
34 verbose bad json   </body>
34 verbose bad json </html>
35 error registry error parsing json
36 verbose headers { server: 'Varnish',
36 verbose headers   'retry-after': '0',
36 verbose headers   'content-type': 'text/html; charset=utf-8',
36 verbose headers   'content-length': '448',
36 verbose headers   'accept-ranges': 'bytes',
36 verbose headers   date: 'Tue, 06 Feb 2018 21:34:16 GMT',
36 verbose headers   via: '1.1 varnish',
36 verbose headers   connection: 'close',
36 verbose headers   'x-served-by': 'cache-hhn1524-HHN',
36 verbose headers   'x-cache': 'MISS',
36 verbose headers   'x-cache-hits': '0',
36 verbose headers   'x-timer': 'S1517952824.134499,VS0,VE32327' }
37 info retry will retry, error on last attempt: SyntaxError: Unexpected token < in JSON at position 1
37 info retry
37 info retry <?xml version="1.0" encoding="utf-8"?>
37 info retry <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
37 info retry  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
37 info retry <html>
37 info retry   <head>
37 info retry     <title>503 first byte timeout</title>
37 info retry   </head>
37 info retry   <body>
37 info retry     <h1>Error 503 first byte timeout</h1>
37 info retry     <p>first byte timeout</p>
37 info retry     <h3>Guru Mediation:</h3>
37 info retry     <p>Details: cache-hhn1524-HHN 1517952856 4091369717</p>
37 info retry     <hr>
37 info retry     <p>Varnish cache server</p>
37 info retry   </body>
37 info retry </html>
38 info attempt registry request try #3 at 22:35:16
39 verbose request using bearer token for auth
40 http request PUT https://registry.npmjs.org/ngx-height-toggle
41 http 403 https://registry.npmjs.org/ngx-height-toggle
42 verbose headers { 'content-type': 'application/json',
42 verbose headers   'cache-control': 'max-age=300',
42 verbose headers   'content-length': '91',
42 verbose headers   'accept-ranges': 'bytes',
42 verbose headers   date: 'Tue, 06 Feb 2018 21:35:43 GMT',
42 verbose headers   via: '1.1 varnish',
42 verbose headers   connection: 'keep-alive',
42 verbose headers   'x-served-by': 'cache-hhn1542-HHN',
42 verbose headers   'x-cache': 'MISS',
42 verbose headers   'x-cache-hits': '0',
42 verbose headers   'x-timer': 'S1517952917.618737,VS0,VE26974',
42 verbose headers   vary: 'Accept-Encoding, Accept' }
43 error publish Failed PUT 403
44 verbose stack Error: You cannot publish over the previously published version 1.0.3. : ngx-height-toggle
44 verbose stack     at makeError (/home/bgolyoo/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:314:12)
44 verbose stack     at RegClient.<anonymous> (/home/bgolyoo/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:302:14)
44 verbose stack     at Request._callback (/home/bgolyoo/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:216:14)
44 verbose stack     at Request.self.callback (/home/bgolyoo/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/request/request.js:186:22)
44 verbose stack     at emitTwo (events.js:126:13)
44 verbose stack     at Request.emit (events.js:214:7)
44 verbose stack     at Request.<anonymous> (/home/bgolyoo/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/request/request.js:1163:10)
44 verbose stack     at emitOne (events.js:116:13)
44 verbose stack     at Request.emit (events.js:211:7)
44 verbose stack     at IncomingMessage.<anonymous> (/home/bgolyoo/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/request/request.js:1085:12)
44 verbose stack     at Object.onceWrapper (events.js:313:30)
44 verbose stack     at emitNone (events.js:111:20)
44 verbose stack     at IncomingMessage.emit (events.js:208:7)
44 verbose stack     at endReadableNT (_stream_readable.js:1055:12)
44 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:138:11)
44 verbose stack     at process._tickCallback (internal/process/next_tick.js:180:9)
45 verbose statusCode 403
46 verbose pkgid ngx-height-toggle
47 verbose cwd /home/bgolyoo/work/hub-repo/ngx-height-toggle/dist/lib
48 verbose Linux 4.4.0-112-generic
49 verbose argv "/home/bgolyoo/.nvm/versions/node/v8.9.4/bin/node" "/home/bgolyoo/.nvm/versions/node/v8.9.4/bin/npm" "publish"
50 verbose node v8.9.4
51 verbose npm  v5.6.0
52 error code E403
53 error You cannot publish over the previously published version 1.0.3. : ngx-height-toggle
54 verbose exit [ 1, true ]
```

### supporting information:

 - `npm -v` prints: 5.6.0
 - `node -v` prints: v8.9.4
 - `npm config get registry` prints: https://registry.npmjs.org/

**Comment by GermainBergeron** [comment]
We currently have a very similar problem with npm 3.10.10 and node 6.10.0 running on our CI. The first publish returns a 503 and the retry returns a 403 since the package is already deployed. Sometimes the backend returns a `504 Gateway Time-out` first, then a `403`.

Is there any way to increase the timeout on the backend?

**Comment by KyleApfel** [comment]
My group is running into similar problems, and has been since February 26th. We handle our publishing through a standard CI/CD pipeline. The project will still publish successfully, but will report an error on every run -- which when everything is an error nothing is which reduces our visibility. Open to suggestions on a resolution.

**Comment by jourdain** [comment]
Noticed the same error from time to time on my CI. Which break semantic-release publication phase which skip the tagging/change-log on github.

Thanks for looking into it.
