### ISSUE TITLE
This is an error with npm itself. Please report this error at:    <https://github.com/npm/npm/issues>

### ISSUE THREAD

**Issue by SathishkumarThangavel** [npm/npm#19774]
npm info using npm@5.6.0
npm info using node@v8.9.4

EUNKNOWNTYPE

Error: Unknown type | in argument #4
npm ERR! typeerror     at new Installer (/usr/local/lib/node_modules/npm/lib/install.js:206:3)
npm ERR! typeerror     at EventEmitter.install (/usr/local/lib/node_modules/npm/lib/install.js:202:3)
npm ERR! typeerror     at Object.commandCache.(anonymous function) (/usr/local/lib/node_modules/npm/lib/npm.js:159:13)
npm ERR! typeerror     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:84:30)
npm ERR! typeerror     at _combinedTickCallback (internal/process/next_tick.js:131:7)
npm ERR! typeerror     at process._tickCallback (internal/process/next_tick.js:180:9)
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <https://github.com/npm/npm/issues>

**Comment by floer32** [comment]
duplicate of #19656
