### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by JanakarM** [npm/npm#19773]
>npm install

module.js:327
    throw err;
    ^

Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\janakar-pt1585\AppData\Roaming\npm\node_modules\npm\lib\utils\unsupported.js:2:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

**Comment by apptaro** [comment]
You use Windows, right? Maybe you can try [enabling long paths](https://superuser.com/a/1119948) for Windows 10, then remove and reinstall npm.

If it doesn't work, then you can check if the contents of C:\Users\janakar-pt1585\AppData\Roaming\npm\node_modules\npm is the same as the contents of node_modules/npm of downloaded zip. If they are not the same, copy the contents from the zip.
