### ISSUE TITLE
EINTEGRITY: sha1-UWbihkV/AzBgZL5Ul+jbsMPTIIM= integrity checksum failed when using sha1: wanted sha1-UWbihkV/AzBgZL5Ul+jbsMPTIIM= but got sha512-yJHVQEhyqPLUTgt9B83PXu6W3rx4MvvHvSUvToogpwoGDOUQ+yDrR0HRot+yOCdCO7u4hX3pWft6kWBBcqh0UA==. (11423 bytes)

### ISSUE THREAD

**Issue by techie-92** [npm/npm#19802]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints: 5.6.0
 - `node -v` prints: 8.9.4
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows 7
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [x ] I access the npm registry via a VPN
   - [x ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

I got this error while installing angular cli using

"npm install -g angular/cli"
[2018-02-12T09_54_39_864Z-debug.log](https://github.com/npm/npm/files/1715919/2018-02-12T09_54_39_864Z-debug.log)

as well as installing dependencies for existing project using "npm install".

I have tried removing app data files and clearing npm cache but no luck.

**Comment by techie-92** [comment]
While installing angular cli, npm is creating a .staging folder inside node_modules folder, adding packages and reverting them again due to checksum error.

**Comment by strugee** [comment]
You should fill out the issue template.

**Comment by techie-92** [comment]
Sorry strugee, I didn't get that.

**Comment by strugee** [comment]
@techie-92 in the issue description there's a bunch of fields you didn't fill out. Stuff like your Node version, npm version, etc. You should edit your description and fill them out :-)

**Comment by Awpatterson217** [comment]
I am also getting this error.

I get this error using NPM version 5.6.0, with Node.js version 8.9.4 or 9.5.0. Furthermore, I get this error on both Ubuntu 16.04 and Windows 10 pro.

I **do not** get this error when using Node.js version 6.12.3.

I have tried uninstalling NPM, Node.js, and everything associated with NPM, and then used NVM to to reinstall. The issue persists.

Thanks for any assistance in advance.

**Comment by techie-92** [comment]
Apologies for the mistake. I have added the required details.

**Comment by techie-92** [comment]
I got below steps  to resolve the issue but it didn't help much.

Open the command prompt with admin privileges and follow the below steps:
1) Clear the cache: npm cache clean --force. You can also run npm cache verify.
2) Remove the node_modules directory.
3) Remove the .npm directory.
4) Remove the C:\Users\<username>\AppData\Roaming\npm\ and C:\Users\<username>\AppData\Roaming\npm-cache directories.
5) Remove the package-lock.json file if any.
6) Now try by installing the package: npm install @angular/cli --verbose.

After these steps I have re-installed node js and tried but still got same issue. Attaching log file.

![image](https://user-images.githubusercontent.com/28696697/36137828-e9fa16a8-10bc-11e8-8348-1744842702bf.png)

[2018-02-13T07_13_33_880Z-debug.log](https://github.com/npm/npm/files/1719002/2018-02-13T07_13_33_880Z-debug.log)

**Comment by techie-92** [comment]
Hi, Any update on this.

**Comment by joshyu** [comment]
Is there any new updates on this issue?

**Comment by techie-92** [comment]
It worked fine when I use dongle to install Node Js. Should be an issue with network.

**Comment by benjamin-wilson** [comment]
This started happening to us today on our Windows build server. 

```
17993 verbose stack Error: sha512-Gr4p6nFNaoufRIY4NMdpQRNmgxVIGMs4Fcu/ujdYk3nAZqk7supzBE9idmvfZIlH/Cuj//dvi+019qEue9lV0w== integrity checksum failed when using sha512: wanted sha512-Gr4p6nFNaoufRIY4NMdpQRNmgxVIGMs4Fcu/ujdYk3nAZqk7supzBE9idmvfZIlH/Cuj//dvi+019qEue9lV0w== but got sha512-aDXBa0jmFo5Jh+aBqmGB+BQrLXVqll1vClhVl6+f4EurWt/tL1dhqK4/vsj+163Ef14SDN/CazEHWdHzMmOs1Q==. (294282 bytes)
17993 verbose stack     at Transform.on (C:\Program Files\nodejs\node_modules\npm\node_modules\ssri\index.js:275:19)
17993 verbose stack     at emitNone (events.js:111:20)
17993 verbose stack     at Transform.emit (events.js:208:7)
17993 verbose stack     at endReadableNT (_stream_readable.js:1064:12)
17993 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:138:11)
17993 verbose stack     at process._tickCallback (internal/process/next_tick.js:180:9)
```
We have a work around where we removed `@angular-devkit/build-angular` and install `@angular-devkit/build-optimizer` before running `npm install` for the production build. This seems to work. @techie-92 were you able to fix the root of the problem?
