### ISSUE TITLE
npm publish put 400 error 'This package contains unacceptable content'

### ISSUE THREAD

**Issue by uznam8x** [npm/npm#19813]
0 info it worked if it ends with ok
1 verbose cli [ '/Users/uznam8x/.nvm/versions/node/v6.11.4/bin/node',
1 verbose cli   '/Users/uznam8x/.nvm/versions/node/v6.11.4/bin/npm',
1 verbose cli   'publish' ]
2 info using npm@5.6.0
3 info using node@v6.11.4
4 verbose npm-session c6765056910ca46a
5 verbose publish [ '.' ]
6 warn prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
7 warn prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
8 warn prepublish-on-install See the deprecation note in `npm help scripts` for more information.
9 info lifecycle generator-codenut@0.2.25~prepublish: generator-codenut@0.2.25
10 verbose lifecycle generator-codenut@0.2.25~prepublish: unsafe-perm in lifecycle true
11 verbose lifecycle generator-codenut@0.2.25~prepublish: PATH: /Users/uznam8x/.nvm/versions/node/v6.11.4/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Applications/MAMP/htdocs/web/generator-codenut/node_modules/.bin:/Users/uznam8x/.nvm/versions/node/v6.11.4/bin:/usr/local/php5/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Wireshark.app/Contents/MacOS:/Users/uznam8x/.composer/vendor/bin
12 verbose lifecycle generator-codenut@0.2.25~prepublish: CWD: .
13 silly lifecycle generator-codenut@0.2.25~prepublish: Args: [ '-c', 'nsp check' ]
14 silly lifecycle generator-codenut@0.2.25~prepublish: Returned: code: 0  signal: null
15 info lifecycle generator-codenut@0.2.25~prepare: generator-codenut@0.2.25
16 info lifecycle generator-codenut@0.2.25~prepublishOnly: generator-codenut@0.2.25
17 info lifecycle generator-codenut@0.2.25~prepack: generator-codenut@0.2.25
18 info lifecycle generator-codenut@0.2.25~postpack: generator-codenut@0.2.25
19 verbose getPublishConfig undefined
20 silly mapToRegistry name generator-codenut
21 silly mapToRegistry using default registry
22 silly mapToRegistry registry https://registry.npmjs.org/
23 silly mapToRegistry data { type: 'tag',
23 silly mapToRegistry   registry: true,
23 silly mapToRegistry   where: undefined,
23 silly mapToRegistry   raw: 'generator-codenut',
23 silly mapToRegistry   name: 'generator-codenut',
23 silly mapToRegistry   escapedName: 'generator-codenut',
23 silly mapToRegistry   scope: undefined,
23 silly mapToRegistry   rawSpec: '',
23 silly mapToRegistry   saveSpec: null,
23 silly mapToRegistry   fetchSpec: 'latest',
23 silly mapToRegistry   gitRange: undefined,
23 silly mapToRegistry   gitCommittish: undefined,
23 silly mapToRegistry   hosted: undefined }
24 silly mapToRegistry uri https://registry.npmjs.org/generator-codenut
25 verbose publish registryBase https://registry.npmjs.org/
26 silly publish uploading /var/folders/ly/mwrdrx5547g77l3mvzytbks80000gn/T/npm-40900-9e6db3a0/tmp/fromDir-c9f220e6/package.tgz
27 verbose request uri https://registry.npmjs.org/generator-codenut
28 verbose request sending authorization for write operation
29 info attempt registry request try #1 at 8:09:42 PM
30 verbose request using bearer token for auth
31 verbose request id 3b10a7125f5e013b
32 http request PUT https://registry.npmjs.org/generator-codenut
33 http 400 https://registry.npmjs.org/generator-codenut
34 verbose headers { 'content-type': 'application/json',
34 verbose headers   'cache-control': 'max-age=300',
34 verbose headers   'content-length': '98',
34 verbose headers   'accept-ranges': 'bytes',
34 verbose headers   date: 'Tue, 13 Feb 2018 11:09:44 GMT',
34 verbose headers   via: '1.1 varnish',
34 verbose headers   connection: 'keep-alive',
34 verbose headers   'x-served-by': 'cache-itm18825-ITM',
34 verbose headers   'x-cache': 'MISS',
34 verbose headers   'x-cache-hits': '0',
34 verbose headers   'x-timer': 'S1518520183.941807,VS0,VE1757',
34 verbose headers   vary: 'Accept-Encoding, Accept' }
35 error publish Failed PUT 400
36 verbose stack Error: This package contains unacceptable content. Contact support@npmjs.com. : generator-codenut
36 verbose stack     at makeError (/Users/uznam8x/.nvm/versions/node/v6.11.4/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:314:12)
36 verbose stack     at RegClient.<anonymous> (/Users/uznam8x/.nvm/versions/node/v6.11.4/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:302:14)
36 verbose stack     at Request._callback (/Users/uznam8x/.nvm/versions/node/v6.11.4/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:216:14)
36 verbose stack     at Request.self.callback (/Users/uznam8x/.nvm/versions/node/v6.11.4/lib/node_modules/npm/node_modules/request/request.js:186:22)
36 verbose stack     at emitTwo (events.js:106:13)
36 verbose stack     at Request.emit (events.js:191:7)
36 verbose stack     at Request.<anonymous> (/Users/uznam8x/.nvm/versions/node/v6.11.4/lib/node_modules/npm/node_modules/request/request.js:1163:10)
36 verbose stack     at emitOne (events.js:96:13)
36 verbose stack     at Request.emit (events.js:188:7)
36 verbose stack     at IncomingMessage.<anonymous> (/Users/uznam8x/.nvm/versions/node/v6.11.4/lib/node_modules/npm/node_modules/request/request.js:1085:12)
36 verbose stack     at IncomingMessage.g (events.js:292:16)
36 verbose stack     at emitNone (events.js:91:20)
36 verbose stack     at IncomingMessage.emit (events.js:185:7)
36 verbose stack     at endReadableNT (_stream_readable.js:974:12)
36 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:80:11)
36 verbose stack     at process._tickCallback (internal/process/next_tick.js:104:9)
37 verbose statusCode 400
38 verbose pkgid generator-codenut
39 verbose cwd /Applications/MAMP/htdocs/web/generator-codenut
40 verbose Darwin 16.7.0
41 verbose argv "/Users/uznam8x/.nvm/versions/node/v6.11.4/bin/node" "/Users/uznam8x/.nvm/versions/node/v6.11.4/bin/npm" "publish"
42 verbose node v6.11.4
43 verbose npm  v5.6.0
44 error code E400
45 error This package contains unacceptable content. Contact support@npmjs.com. : generator-codenut
46 verbose exit [ 1, true ]

**Comment by ghost** [comment]
I got the same problem and it's been resolved.

 `This package contains unacceptable content.` _likely_ means that your package's name is not allowed to be used. If you think there's no problem with your package name, it's _likely_ the case where their spam filter is making a false positive on your package name, or, your package name is not satisfying [the naming rules](https://docs.npmjs.com/files/package.json#name), which would be not _your_ case.

 As it states, the best way to resolve this problem is to contact `support@npmjs.com`.

**Comment by justinchou** [comment]
i got the same problem and it's not solved.

here is the error:

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/justinchow/.nvm/versions/node/v6.11.4/bin/node',
1 verbose cli   '/Users/justinchow/.nvm/versions/node/v6.11.4/bin/npm',
1 verbose cli   'publish' ]
2 info using npm@3.10.10
3 info using node@v6.11.4
4 verbose publish [ '.' ]
5 silly cache add args [ '.', null ]
6 verbose cache add spec .
7 silly cache add parsed spec Result {
7 silly cache add   raw: '.',
7 silly cache add   scope: null,
7 silly cache add   escapedName: null,
7 silly cache add   name: null,
7 silly cache add   rawSpec: '.',
7 silly cache add   spec: '/Users/justinchow/Documents/Projects/bearcat-cli',
7 silly cache add   type: 'directory' }
8 verbose addLocalDirectory /Users/justinchow/.npm/bearcat-cli/1.0.5/package.tgz not in flight; packing
9 verbose correctMkdir /Users/justinchow/.npm correctMkdir not in flight; initializing
10 info lifecycle bearcat-cli@1.0.5~prepublish: bearcat-cli@1.0.5
11 silly lifecycle bearcat-cli@1.0.5~prepublish: no script for prepublish, continuing
12 verbose tar pack [ '/Users/justinchow/.npm/bearcat-cli/1.0.5/package.tgz',
12 verbose tar pack   '/Users/justinchow/Documents/Projects/bearcat-cli' ]
13 verbose tarball /Users/justinchow/.npm/bearcat-cli/1.0.5/package.tgz
14 verbose folder /Users/justinchow/Documents/Projects/bearcat-cli
15 verbose addLocalTarball adding from inside cache /Users/justinchow/.npm/bearcat-cli/1.0.5/package.tgz
16 verbose correctMkdir /Users/justinchow/.npm correctMkdir not in flight; initializing
17 silly cache afterAdd bearcat-cli@1.0.5
18 verbose afterAdd /Users/justinchow/.npm/bearcat-cli/1.0.5/package/package.json not in flight; writing
19 verbose correctMkdir /Users/justinchow/.npm correctMkdir not in flight; initializing
20 verbose afterAdd /Users/justinchow/.npm/bearcat-cli/1.0.5/package/package.json written
21 silly publish { name: 'bearcat-cli',
21 silly publish   version: '1.0.5',
21 silly publish   description: 'using bearcat as shell command to handle a list of problems just as express-generator :)',
21 silly publish   main: 'bin/bearcat-cli.js',
21 silly publish   bin:
21 silly publish    { bearcat: './bin/bearcat-cli.js',
21 silly publish      'bearcat-cli': './bin/bearcat-cli.js' },
21 silly publish   repository:
21 silly publish    { type: 'git',
21 silly publish      url: 'git+https://github.com/justinchowchou/bearcat-cli.git' },
21 silly publish   author: { name: 'JustinChou', email: 'zhou78620051@126.com' },
21 silly publish   contributors: [],
21 silly publish   license: 'MIT',
21 silly publish   dependencies: { chalk: '^2.3.1', commander: '^2.14.1', mkdirp: '^0.5.1' },
21 silly publish   readme: 'Bearcat Cli 命令行工具\n===\n\n[![BearCat Logo][express-logo]](http://bearcatjs.cn/)\n\n[Bearcat Cli](https://www.npmjs.com/package/bearcat-cli) 是用于自动化生成基于 [Bearcat](https://www.npmjs.com/package/bearcat) 框架的初始化代码的工具.\n\n[![BEARCAT Version][bearcat-cli-image]][bearcat-cli-url]\n[![NPM Version][npm-image]][npm-url]\n[![NPM Downloads][downloads-image]][downloads-url]\n\n## 安装\n\n通过npm管理\n\n```bash\nnpm install -g bearcat-cli\n```\n\n如果你习惯了yarn, 那么:\n\n```bash\nyarn global add bearcat-cli\n```\n\n\n## 快速开始\n\n最快速的开始Bearcat的方式, 就是执行 `bearcat-cli` 命令行工具, 生成一个可以运行的程序:\n\n创建Demo应用:\n\n```bash\nbearcat-cli init demo-app  && cd demo-app\n```\n\n使用npm安装依赖:\n\n```bash\nnpm install\n```\n\n启动程序:\n\n```bash\n$ npm start\n```\n\n## 命令行选项\n\n工具还可以根据其他选项生成更自定义化的工程:\n\n    Usage: bearcat-cli [command] [options]\n    \n    Options:\n  \n          --version  输出版本号\n      -h, --help     输出帮助信息\n\n    Commands:\n  \n      init|i [options]     初始化项目\n      debug|dbg [options]  输出本模块测试数据\n\n根据不同项目类型生成项目\n\n    Usage: init|i [options] [path]\n  \n    初始化项目\n    \n    Options:\n  \n      -n, --name [value]  模板名称, 默认为 demo 默认模板, 支持 demo, express\n      -H, --hot           使用热加载模式, 默认为false\n      -s, --silent        使用静默模式, 尽量减少日志\n          --git           增加 .gitignore 文件\n      -f, --force         强制在非空目录下创建工程\n      -h, --help          output usage information\n\n## License\n\n[MIT](LICENSE)\n\n[express-logo]: https://bearcatjs.cn/images/logo.png\n\n[bearcat-cli-image]: https://img.shields.io/badge/bearcat--cli-v0.0.5-brightgreen.svg\n[bearcat-cli-url]: https://npmjs.org/package/bearcat-cli\n\n[npm-image]: https://img.shields.io/npm/v/bearcat-cli.svg\n[npm-url]: https://npmjs.org/package/bearcat-cli\n\n[downloads-image]: https://img.shields.io/npm/dm/bearcat-cli.svg\n[downloads-url]: https://npmjs.org/package/bearcat-cli\n',
21 silly publish   readmeFilename: 'README.md',
21 silly publish   gitHead: '8567c71bcaff51489390694d550f2daa6c16adc9',
21 silly publish   bugs: { url: 'https://github.com/justinchowchou/bearcat-cli/issues' },
21 silly publish   homepage: 'https://github.com/justinchowchou/bearcat-cli#readme',
21 silly publish   _id: 'bearcat-cli@1.0.5',
21 silly publish   scripts: {},
21 silly publish   _shasum: '1085752df4a66488ef1cca3df72cf5a94a036f50',
21 silly publish   _from: '.' }
22 verbose getPublishConfig undefined
23 silly mapToRegistry name bearcat-cli
24 silly mapToRegistry using default registry
25 silly mapToRegistry registry https://registry.npmjs.org/
26 silly mapToRegistry data Result {
26 silly mapToRegistry   raw: 'bearcat-cli',
26 silly mapToRegistry   scope: null,
26 silly mapToRegistry   escapedName: 'bearcat-cli',
26 silly mapToRegistry   name: 'bearcat-cli',
26 silly mapToRegistry   rawSpec: '',
26 silly mapToRegistry   spec: 'latest',
26 silly mapToRegistry   type: 'tag' }
27 silly mapToRegistry uri https://registry.npmjs.org/bearcat-cli
28 verbose publish registryBase https://registry.npmjs.org/
29 silly publish uploading /Users/justinchow/.npm/bearcat-cli/1.0.5/package.tgz
30 verbose request uri https://registry.npmjs.org/bearcat-cli
31 verbose request sending authorization for write operation
32 info attempt registry request try #1 at 11:35:15 PM
33 verbose request using bearer token for auth
34 verbose request id ae6795d38f737298
35 http request PUT https://registry.npmjs.org/bearcat-cli
36 http 400 https://registry.npmjs.org/bearcat-cli
37 verbose headers { 'content-type': 'application/json',
37 verbose headers   'cache-control': 'max-age=300',
37 verbose headers   'content-length': '98',
37 verbose headers   'accept-ranges': 'bytes',
37 verbose headers   date: 'Mon, 26 Feb 2018 15:35:17 GMT',
37 verbose headers   via: '1.1 varnish',
37 verbose headers   connection: 'keep-alive',
37 verbose headers   'x-served-by': 'cache-hnd18734-HND',
37 verbose headers   'x-cache': 'MISS',
37 verbose headers   'x-cache-hits': '0',
37 verbose headers   'x-timer': 'S1519659316.397766,VS0,VE1168',
37 verbose headers   vary: 'Accept-Encoding, Accept' }
38 verbose request invalidating /Users/justinchow/.npm/registry.npmjs.org/bearcat-cli on PUT
39 error publish Failed PUT 400
40 verbose stack Error: This package contains unacceptable content. Contact support@npmjs.com. : bearcat-cli
40 verbose stack     at makeError (/Users/justinchow/.nvm/versions/node/v6.11.4/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:302:12)
40 verbose stack     at CachingRegistryClient.<anonymous> (/Users/justinchow/.nvm/versions/node/v6.11.4/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:290:14)
40 verbose stack     at Request._callback (/Users/justinchow/.nvm/versions/node/v6.11.4/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:210:14)
40 verbose stack     at Request.self.callback (/Users/justinchow/.nvm/versions/node/v6.11.4/lib/node_modules/npm/node_modules/request/request.js:187:22)
40 verbose stack     at emitTwo (events.js:106:13)
40 verbose stack     at Request.emit (events.js:191:7)
40 verbose stack     at Request.<anonymous> (/Users/justinchow/.nvm/versions/node/v6.11.4/lib/node_modules/npm/node_modules/request/request.js:1048:10)
40 verbose stack     at emitOne (events.js:96:13)
40 verbose stack     at Request.emit (events.js:188:7)
40 verbose stack     at IncomingMessage.<anonymous> (/Users/justinchow/.nvm/versions/node/v6.11.4/lib/node_modules/npm/node_modules/request/request.js:969:12)
41 verbose statusCode 400
42 verbose pkgid bearcat-cli
43 verbose cwd /Users/justinchow/Documents/Projects/bearcat-cli
44 error Darwin 17.2.0
45 error argv "/Users/justinchow/.nvm/versions/node/v6.11.4/bin/node" "/Users/justinchow/.nvm/versions/node/v6.11.4/bin/npm" "publish"
46 error node v6.11.4
47 error npm  v3.10.10
48 error code E400
49 error This package contains unacceptable content. Contact support@npmjs.com. : bearcat-cli
50 error If you need help, you may report this error at:
50 error     <https://github.com/npm/npm/issues>
51 verbose exit [ 1, true ]
```

this is on my mac computer, and it's my second publish today. Earlier today i pushed the v1.0.3 and succeed, this is the next version v1.0.5, push failed :(

**Comment by yutingzhao1991** [comment]
I have the same problem, it's strange. I try to make a simple package to test `npm publish` and it failed!!!

![image](https://user-images.githubusercontent.com/1061968/37032047-14da7186-217c-11e8-9869-3eccc09b00c9.png)

the `package.json`:

```
{
  "name": "yu-test-npm",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}

```

logs:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'publish' ]
2 info using npm@5.7.1
3 info using node@v8.3.0
4 verbose npm-session 0ac8d836a93e5ac7
5 verbose publish [ '.' ]
6 info lifecycle yu-test-npm@1.0.0~prepublish: yu-test-npm@1.0.0
7 info lifecycle yu-test-npm@1.0.0~prepare: yu-test-npm@1.0.0
8 info lifecycle yu-test-npm@1.0.0~prepublishOnly: yu-test-npm@1.0.0
9 info lifecycle yu-test-npm@1.0.0~prepack: yu-test-npm@1.0.0
10 info lifecycle yu-test-npm@1.0.0~postpack: yu-test-npm@1.0.0
11 verbose getPublishConfig undefined
12 silly mapToRegistry name yu-test-npm
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry http://registry.npmjs.org/
15 silly mapToRegistry data { type: 'tag',
15 silly mapToRegistry   registry: true,
15 silly mapToRegistry   where: undefined,
15 silly mapToRegistry   raw: 'yu-test-npm',
15 silly mapToRegistry   name: 'yu-test-npm',
15 silly mapToRegistry   escapedName: 'yu-test-npm',
15 silly mapToRegistry   scope: undefined,
15 silly mapToRegistry   rawSpec: '',
15 silly mapToRegistry   saveSpec: null,
15 silly mapToRegistry   fetchSpec: 'latest',
15 silly mapToRegistry   gitRange: undefined,
15 silly mapToRegistry   gitCommittish: undefined,
15 silly mapToRegistry   hosted: undefined }
16 silly mapToRegistry uri http://registry.npmjs.org/yu-test-npm
17 verbose publish registryBase http://registry.npmjs.org/
18 silly publish uploading /var/folders/qd/4z7g8jvs647ddhbllghmv59r0000gn/T/npm-3594-fa0aa746/tmp/fromDir-998cd381/package.tgz
19 verbose request uri http://registry.npmjs.org/yu-test-npm
20 verbose request sending authorization for write operation
21 info attempt registry request try #1 at 20:21:57
22 verbose request using bearer token for auth
23 verbose request id c955e923b0dca953
24 http request PUT http://registry.npmjs.org/yu-test-npm
25 http 400 http://registry.npmjs.org/yu-test-npm
26 verbose headers { 'content-type': 'application/json',
26 verbose headers   'cache-control': 'max-age=300',
26 verbose headers   'content-length': '98',
26 verbose headers   'accept-ranges': 'bytes',
26 verbose headers   date: 'Tue, 06 Mar 2018 12:22:02 GMT',
26 verbose headers   via: '1.1 varnish',
26 verbose headers   connection: 'keep-alive',
26 verbose headers   'x-served-by': 'cache-hnd18730-HND',
26 verbose headers   'x-cache': 'MISS',
26 verbose headers   'x-cache-hits': '0',
26 verbose headers   'x-timer': 'S1520338921.171838,VS0,VE1351',
26 verbose headers   vary: 'Accept-Encoding, Accept' }
27 error publish Failed PUT 400
28 verbose stack Error: This package contains unacceptable content. Contact support@npmjs.com. : yu-test-npm
28 verbose stack     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:314:12)
28 verbose stack     at RegClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:302:14)
28 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:216:14)
28 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:186:22)
28 verbose stack     at emitTwo (events.js:125:13)
28 verbose stack     at Request.emit (events.js:213:7)
28 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1163:10)
28 verbose stack     at emitOne (events.js:115:13)
28 verbose stack     at Request.emit (events.js:210:7)
28 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1085:12)
28 verbose stack     at Object.onceWrapper (events.js:314:30)
28 verbose stack     at emitNone (events.js:110:20)
28 verbose stack     at IncomingMessage.emit (events.js:207:7)
28 verbose stack     at endReadableNT (_stream_readable.js:1045:12)
28 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:138:11)
28 verbose stack     at process._tickCallback (internal/process/next_tick.js:180:9)
29 verbose statusCode 400
30 verbose pkgid yu-test-npm
31 verbose cwd /Users/yutingzhao/code/github/yutingzhao1991-test-npm
32 verbose Darwin 17.4.0
33 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "publish"
34 verbose node v8.3.0
35 verbose npm  v5.7.1
36 error code E400
37 error This package contains unacceptable content. Contact support@npmjs.com. : yu-test-npm
38 verbose exit [ 1, true ]

```

So simple demo, it confusing!~

![image](https://user-images.githubusercontent.com/1061968/37032177-822ed2f4-217c-11e8-9f6a-2bd689963ffc.png)

**Comment by ghost** [comment]
@yutingzhao1991 Try it again without `npm` (or even `test` as well) within your package name.

**Comment by justinchou** [comment]
several days ago，i got the same problem，and it confused me as well. with no solution，i have to just wait for several hours，and then i published it with success without any change of my code.

**Comment by yutingzhao1991** [comment]
@justinchou same solution! just wait for several hours!~ 

I guess it's the problem of npm register server!

**Comment by clark-t** [comment]
@justinchou I've been waiting for nealy A WHOLE DAY...nothing change...

**Comment by ghost** [comment]
@clark-t Another option for you: `support@npmjs.com`.

**Comment by piranna** [comment]
I got the same problem with [buho](https://github.com/piranna/buho):

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'publish' ]
2 info using npm@5.6.0
3 info using node@v9.8.0
4 verbose npm-session 1b390d4181fb1b75
5 verbose publish [ '.' ]
6 info lifecycle buho@0.3.4~prepublish: buho@0.3.4
7 info lifecycle buho@0.3.4~prepare: buho@0.3.4
8 info lifecycle buho@0.3.4~prepublishOnly: buho@0.3.4
9 info lifecycle buho@0.3.4~prepack: buho@0.3.4
10 info lifecycle buho@0.3.4~postpack: buho@0.3.4
11 verbose getPublishConfig undefined
12 silly mapToRegistry name buho
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry data { type: 'tag',
15 silly mapToRegistry   registry: true,
15 silly mapToRegistry   where: undefined,
15 silly mapToRegistry   raw: 'buho',
15 silly mapToRegistry   name: 'buho',
15 silly mapToRegistry   escapedName: 'buho',
15 silly mapToRegistry   scope: undefined,
15 silly mapToRegistry   rawSpec: '',
15 silly mapToRegistry   saveSpec: null,
15 silly mapToRegistry   fetchSpec: 'latest',
15 silly mapToRegistry   gitRange: undefined,
15 silly mapToRegistry   gitCommittish: undefined,
15 silly mapToRegistry   hosted: undefined }
16 silly mapToRegistry uri https://registry.npmjs.org/buho
17 verbose publish registryBase https://registry.npmjs.org/
18 silly publish uploading /tmp/npm-2236-6315b328/tmp/fromDir-aa8b460b/package.tgz
19 verbose request uri https://registry.npmjs.org/buho
20 verbose request sending authorization for write operation
21 info attempt registry request try #1 at 13:50:23
22 verbose request using bearer token for auth
23 verbose request id 220a376c3297851f
24 http request PUT https://registry.npmjs.org/buho
25 http 400 https://registry.npmjs.org/buho
26 verbose headers { 'content-type': 'application/json',
26 verbose headers   'cache-control': 'max-age=300',
26 verbose headers   'content-length': '98',
26 verbose headers   'accept-ranges': 'bytes',
26 verbose headers   date: 'Sat, 17 Mar 2018 12:50:26 GMT',
26 verbose headers   via: '1.1 varnish',
26 verbose headers   connection: 'keep-alive',
26 verbose headers   'x-served-by': 'cache-mad9422-MAD',
26 verbose headers   'x-cache': 'MISS',
26 verbose headers   'x-cache-hits': '0',
26 verbose headers   'x-timer': 'S1521291024.742292,VS0,VE2477',
26 verbose headers   vary: 'Accept-Encoding, Accept' }
27 error publish Failed PUT 400
28 verbose stack Error: This package contains unacceptable content. Contact support@npmjs.com. : buho
28 verbose stack     at makeError (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:314:12)
28 verbose stack     at RegClient.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:302:14)
28 verbose stack     at Request._callback (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:216:14)
28 verbose stack     at Request.self.callback (/usr/lib/node_modules/npm/node_modules/request/request.js:186:22)
28 verbose stack     at Request.emit (events.js:180:13)
28 verbose stack     at Request.<anonymous> (/usr/lib/node_modules/npm/node_modules/request/request.js:1163:10)
28 verbose stack     at Request.emit (events.js:180:13)
28 verbose stack     at IncomingMessage.<anonymous> (/usr/lib/node_modules/npm/node_modules/request/request.js:1085:12)
28 verbose stack     at Object.onceWrapper (events.js:272:13)
28 verbose stack     at IncomingMessage.emit (events.js:185:15)
28 verbose stack     at endReadableNT (_stream_readable.js:1101:12)
28 verbose stack     at process._tickCallback (internal/process/next_tick.js:114:19)
29 verbose statusCode 400
30 verbose pkgid buho
31 verbose cwd /home/piranna/github/buho
32 verbose Linux 4.13.0-37-generic
33 verbose argv "/usr/bin/node" "/usr/bin/npm" "publish"
34 verbose node v9.8.0
35 verbose npm  v5.6.0
36 error code E400
37 error This package contains unacceptable content. Contact support@npmjs.com. : buho
38 verbose exit [ 1, true ]
```

**Comment by ghost** [comment]
@piranna For you: `support@npmjs.com`.

**Comment by piranna** [comment]
> @piranna For you: support@npmjs.com.

Yeah, I've written to them, but it's a bit annoying anyway, specially if I was able to publish a version of this same package less than a week ago...

**Comment by bahmutov** [comment]
Same for cypress-hyperapp-unit-test https://travis-ci.org/bahmutov/cypress-hyperapp-unit-test/builds/355383802 all of the sudden, and the package only has trivial files (code plus readme)

Update: it did publish 10 minutes later after retrying

**Comment by hopperhuang** [comment]
have you resolve this problem? i have encounter the same problem when i want to publish some new feature to muy package

**Comment by piranna** [comment]
> have you resolve this problem? i have encounter the same problem when i want to publish some new feature to muy package

Yes, just wrote to npm team and got solved the next laborable day.

**Comment by johndatserakis** [comment]
I had a similar issue - I shortened the `description` text in the package.json and all was well.
