### ISSUE TITLE
error 407 Proxy Authentication Required: @ng-idle/core@latest

### ISSUE THREAD

**Issue by praveenchabrolu** [npm/npm#19820]
#### I'm opening this issue because: npm not letting me install any new packages

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
When I am doing the npm install --save @ng-idle/core @ng-idle/keepalive angular2-moment
Its just giving me the following error:
npm ERR! code E407
npm ERR! 407 Proxy Authentication Required: npm@latest

I tried npm install on different package and they all resulted in same error

I use proxy settings 
proxy=http://mycompany.com:<portNumber>/
https-proxy=http://mycompany.com:<portNumber>/
unsafe-perm=true
http-proxy=http://mycompany.com:<portNumber>
strict-ssl=false
registry=https://registry.npmjs.org/

#### How can the CLI team reproduce the problem?

Just run npm install <any-package>
Following is the npm-debug.log file:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '--save',
1 verbose cli   '@ng-idle/core',
1 verbose cli   '@ng-idle/keepalive',
1 verbose cli   'angular2-moment' ]
2 info using npm@5.3.0
3 info using node@v8.2.0
4 verbose npm-session 7a1d7f316a4f3543
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 407 https://registry.npmjs.org/@ng-idle%2fcore 105ms
8 silly fetchPackageMetaData error for @ng-idle/core@latest 407 Proxy Authentication Required: @ng-idle/core@latest
9 http fetch GET 407 https://registry.npmjs.org/angular2-moment 100ms
10 http fetch GET 407 https://registry.npmjs.org/@ng-idle%2fkeepalive 100ms
11 silly fetchPackageMetaData error for angular2-moment@latest 407 Proxy Authentication Required: angular2-moment@latest
12 silly fetchPackageMetaData error for @ng-idle/keepalive@latest 407 Proxy Authentication Required: @ng-idle/keepalive@latest
13 verbose stack Error: 407 Proxy Authentication Required: @ng-idle/core@latest
13 verbose stack     at fetch.then.res (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\fetchers\registry\fetch.js:41:19)
13 verbose stack     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
13 verbose stack     at Promise._settlePromiseFromHandler (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
13 verbose stack     at Promise._settlePromise (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
13 verbose stack     at Promise._settlePromise0 (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
13 verbose stack     at Promise._settlePromises (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
13 verbose stack     at Async._drainQueue (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
13 verbose stack     at Async._drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
13 verbose stack     at Immediate.Async.drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
13 verbose stack     at runCallback (timers.js:781:20)
13 verbose stack     at tryOnImmediate (timers.js:743:5)
13 verbose stack     at processImmediate [as _immediateCallback] (timers.js:714:5)
14 verbose cwd C:\Work\Application\ASL_NewWorkspace\aslprojects\AslWeb\src\main\ui
15 verbose Windows_NT 6.1.7601
16 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "@ng-idle/core" "@ng-idle/keepalive" "angular2-moment"
17 verbose node v8.2.0
18 verbose npm  v5.3.0
19 error code E407
20 error 407 Proxy Authentication Required: @ng-idle/core@latest
21 verbose exit [ 1, true ]

### supporting information:

 - `npm -v` prints: 5.3.0
 - `node -v` prints: v8.2.0
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?: Windows 7
 - Network issues: Using Proxy to download and install npm packages and git
   - Geographic location where npm was run:
   - [.] I use a proxy to connect to the npm registry.
   - [.] I use a proxy to connect to the web.
   - [.] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by praveenchabrolu** [comment]
Also my proxy connection doesn't require or have any username and password to connect

**Comment by praveenchabrolu** [comment]
My local npm config list below

npm config list:

; cli configs
metrics-registry = "https://registry.npmjs.org/"
scope = ""
user-agent = "npm/5.3.0 node/v8.2.0 win32 x64"

; userconfig C:\Users\myuser\.npmrc
http-proxy = "http://mycompany.com:portNumber"
https-proxy = "http://mycompany.com:portNumber/"
proxy = "http://mycompany.com:portNumber/"
registry = "https://registry.npmjs.org/"
strict-ssl = false
unsafe-perm = true

; globalconfig C:\Users\myuser\AppData\Roaming\npm\etc\npmrc
http-proxy = "http://mycompany.com:portNumber"
https-proxy = "http://mycompany.com:portNumber/"
proxy = "http://mycompany.com:portNumber/"

; builtin config undefined
prefix = "C:\\Users\\myuser\\AppData\\Roaming\\npm"

; node bin location = C:\Program Files\nodejs\node.exe
; HOME = C:\Users\myuser
; "npm config ls -l" to show all defaults.

**Comment by praveenchabrolu** [comment]
Sorry please ignore my issue, I got a different proxy url from my system administrator
