### ISSUE TITLE
npm install silently missing dependencies

### ISSUE THREAD

**Issue by hisuwh** [npm/npm#19839]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

My team and I have had ongoing issues with npm either failing to install, or incorrectly installing packages over the last few weeks.  Sometimes it does not copy scripts to the .bin folder sometimes it seems to just miss packages completely.  In the latter case it doesn't error but then things are missing when we come to build our application

This is an intermittent issue so I am unable to provide clear steps to reproduce and we have also seen this issue across a number of node/npm versions:
 - v8.0.0 / 5.5.1
 - v8.9.3 / 5.5.1
 - v8.9.4 / 5.6.0
(to name a but a few).

The only way we have found to work around this issue is to: 
 - rimraf node_modules
 - rimraf package-lock.json
 - npm install
 - repeat n times until it works

This has cost us hours of development time across several projects.

Initially this was only affecting individual developers machines but it is now presenting on our build server which is major issue.

_Edit:_ this also adds a lot of pain as we are having to constantly update our package-lock.json files which means a lot of merge conflicts

### supporting information:

 - `npm -v` prints: **see above**
 - `node -v` prints: **see above**
 - `npm config get registry` prints: **http://registry.npmjs.org/**
 - Windows, OS X/macOS, or Linux?: **Windows**
 - Network issues:
   - Geographic location where npm was run: **UK**
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by Jameskmonger** [comment]
Do you have an error log available? I imagine it would help @iarna / @isaacs / whoever look into it

**Comment by hisuwh** [comment]
Here's a run I just did:

```
npm i
npm WARN registry Unexpected warning for http://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha1-6exflJi57JEOeuOsYmqAXE0J7Kw= integrity checksum failed when using sha1: wanted sha1-6exflJi57JEOeuOsYmqAXE0J7Kw= but got sha512-uRdSdu1oA1rncCQL7sCj8vSyZkgtL7faaw9Tc9rZ3mGgraQ7+Pdx7w5mnOSF3gw9ZNG6oc+KXfkon3bKuROm0g==. (39780 bytes)
npm WARN registry Using stale package data from http://registry.npmjs.org/ due to a request error during revalidation.

> node-sass@4.7.2 install D:\code\Project\src\Project.People.App\node_modules\node-sass
> node scripts/install.js

Cached binary found at C:\Users\HenryIng-Simmons\AppData\Roaming\npm-cache\node-sass\4.7.2\win32-x64-57_binding.node

> uglifyjs-webpack-plugin@0.4.6 postinstall D:\code\Project\src\Project.People.App\node_modules\uglifyjs-webpack-plugin
> node lib/post_install.js


> node-sass@4.7.2 postinstall D:\code\Project\src\Project.People.App\node_modules\node-sass
> node scripts/build.js

Binary found at D:\code\Project\src\Project.People.App\node_modules\node-sass\vendor\win32-x64-57\binding.node
Testing binary
Binary is fine
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ansi-styles@3.2.0 (node_modules\@Project\shared\node_modules\postcss\node_modules\ansi-styles):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'D:\code\Project\src\Project.People.App\node_modules\.staging\ansi-styles-3e7c2aa1' -> 'D:\code\Project\src\App.Common\node_modules\postcss\node_modules\ansi-styles'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: source-map@0.6.1 (node_modules\@Project\shared\node_modules\postcss\node_modules\source-map):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'D:\code\Project\src\Project.People.App\node_modules\.staging\source-map-34c297c2' -> 'D:\code\Project\src\App.Common\node_modules\postcss\node_modules\source-map'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: supports-color@5.2.0 (node_modules\@Project\shared\node_modules\postcss\node_modules\supports-color):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename 'D:\code\Project\src\Project.People.App\node_modules\.staging\supports-color-6dbd2f7b' -> 'D:\code\Project\src\App.Common\node_modules\postcss\node_modules\supports-color'

added 1240 packages in 190.757s

------------------------------------------------------------------------------

npm run build

> @neworbit/Project.people.app@0.1.0 build D:\code\Project\src\Project.People.App
> webpack


D:\code\Project\src\App.Common\node_modules\postcss\node_modules\chalk\index.js:72
ansiStyles.color.closeRe = new RegExp(escapeStringRegexp(ansiStyles.color.close), 'g');
                                                                          ^
TypeError: Cannot read property 'close' of undefined
    at Object.<anonymous> (D:\code\Project\src\App.Common\node_modules\postcss\node_modules\chalk\index.js:72:75)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\code\Project\src\App.Common\node_modules\postcss\lib\css-syntax-error.es6:2:1)
    at Module._compile (module.js:635:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @neworbit/Project.people.app@0.1.0 build: `webpack`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @neworbit/Project.people.app@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\HenryIng-Simmons\AppData\Roaming\npm-cache\_logs\2018-02-16T14_25_09_077Z-debug.log

------------------------------------------------------------------------------

rimraf node_modules\

------------------------------------------------------------------------------

rimraf package-lock.json

------------------------------------------------------------------------------

npm i
npm WARN registry Unexpected warning for http://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha1-6exflJi57JEOeuOsYmqAXE0J7Kw= integrity checksum failed when using sha1: wanted sha1-6exflJi57JEOeuOsYmqAXE0J7Kw= but got sha512-uRdSdu1oA1rncCQL7sCj8vSyZkgtL7faaw9Tc9rZ3mGgraQ7+Pdx7w5mnOSF3gw9ZNG6oc+KXfkon3bKuROm0g==. (39780 bytes)
npm WARN registry Using stale package data from http://registry.npmjs.org/ due to a request error during revalidation.
npm ERR! path D:\code\Project\src\Project.People.App\node_modules\semantic-ui-react\package.json.3901396336
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename
npm ERR! Error: EPERM: operation not permitted, rename 'D:\code\Project\src\Project.People.App\node_modules\semantic-ui-react\package.json.3901396336' -> 'D:\code\Project\src\Project.People.App\node_modules\semantic-ui-react\package.json'
npm ERR!  { Error: EPERM: operation not permitted, rename 'D:\code\Project\src\Project.People.App\node_modules\semantic-ui-react\package.json.3901396336' -> 'D:\code\Project\src\Project.People.App\node_modules\semantic-ui-react\package.json'
npm ERR!   cause:
npm ERR!    { Error: EPERM: operation not permitted, rename 'D:\code\Project\src\Project.People.App\node_modules\semantic-ui-react\package.json.3901396336' -> 'D:\code\Project\src\Project.People.App\node_modules\semantic-ui-react\package.json'
npm ERR!      errno: -4048,
npm ERR!      code: 'EPERM',
npm ERR!      syscall: 'rename',
npm ERR!      path: 'D:\\code\\Project\\src\\Project.People.App\\node_modules\\semantic-ui-react\\package.json.3901396336',
npm ERR!      dest: 'D:\\code\\Project\\src\\Project.People.App\\node_modules\\semantic-ui-react\\package.json' },
npm ERR!   stack: 'Error: EPERM: operation not permitted, rename \'D:\\code\\Project\\src\\Project.People.App\\node_modules\\semantic-ui-react\\package.json.3901396336\' -> \'D:\\code\\Project\\src\\Project.People.App\\node_modules\\semantic-ui-react\\package.json\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'rename',
npm ERR!   path: 'D:\\code\\Project\\src\\Project.People.App\\node_modules\\semantic-ui-react\\package.json.3901396336',
npm ERR!   dest: 'D:\\code\\Project\\src\\Project.People.App\\node_modules\\semantic-ui-react\\package.json',
npm ERR!   parent: '@neworbit/Project.people.app' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\HenryIng-Simmons\AppData\Roaming\npm-cache\_logs\2018-02-16T14_29_24_026Z-debug.log

------------------------------------------------------------------------------

npm i
npm WARN registry Unexpected warning for http://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha1-6exflJi57JEOeuOsYmqAXE0J7Kw= integrity checksum failed when using sha1: wanted sha1-6exflJi57JEOeuOsYmqAXE0J7Kw= but got sha512-uRdSdu1oA1rncCQL7sCj8vSyZkgtL7faaw9Tc9rZ3mGgraQ7+Pdx7w5mnOSF3gw9ZNG6oc+KXfkon3bKuROm0g==. (39780 bytes)
npm WARN registry Using stale package data from http://registry.npmjs.org/ due to a request error during revalidation.

> uglifyjs-webpack-plugin@0.4.6 postinstall D:\code\Project\src\Project.People.App\node_modules\uglifyjs-webpack-plugin
> node lib/post_install.js

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 48 packages, removed 9 packages and updated 1093 packages in 213.995s

------------------------------------------------------------------------------

npm run build

> @neworbit/Project.people.app@0.1.0 build D:\code\Project\src\Project.People.App
> webpack


D:\code\Project\src\App.Common\node_modules\postcss\node_modules\chalk\index.js:72
ansiStyles.color.closeRe = new RegExp(escapeStringRegexp(ansiStyles.color.close), 'g');
                                                                          ^
TypeError: Cannot read property 'close' of undefined
    at Object.<anonymous> (D:\code\Project\src\App.Common\node_modules\postcss\node_modules\chalk\index.js:72:75)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\code\Project\src\App.Common\node_modules\postcss\lib\css-syntax-error.es6:2:1)
    at Module._compile (module.js:635:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @neworbit/Project.people.app@0.1.0 build: `webpack`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @neworbit/Project.people.app@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\HenryIng-Simmons\AppData\Roaming\npm-cache\_logs\2018-02-16T14_36_56_906Z-debug.log

------------------------------------------------------------------------------

cd ..\App.Common

------------------------------------------------------------------------------

rimraf node_modules

------------------------------------------------------------------------------

rimraf package-lock.json

------------------------------------------------------------------------------

npm i
npm WARN deprecated redux-mock-store@1.5.1: breaking changes in minor version
npm WARN registry Unexpected warning for http://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha1-6exflJi57JEOeuOsYmqAXE0J7Kw= integrity checksum failed when using sha1: wanted sha1-6exflJi57JEOeuOsYmqAXE0J7Kw= but got sha512-uRdSdu1oA1rncCQL7sCj8vSyZkgtL7faaw9Tc9rZ3mGgraQ7+Pdx7w5mnOSF3gw9ZNG6oc+KXfkon3bKuROm0g==. (39780 bytes)
npm WARN registry Using stale package data from http://registry.npmjs.org/ due to a request error during revalidation.

> uglifyjs-webpack-plugin@0.4.6 postinstall D:\code\Project\src\App.Common\node_modules\uglifyjs-webpack-plugin
> node lib/post_install.js

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN @Project/shared@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 822 packages in 160.184s

------------------------------------------------------------------------------

npm run build

> @Project/shared@1.0.0 build D:\code\Project\src\App.Common
> tsc -p ./tsconfig.json --outDir dist

------------------------------------------------------------------------------

cd ..\Project.People.App

------------------------------------------------------------------------------

rimraf node_modules

------------------------------------------------------------------------------

rimraf packge-lock.json

------------------------------------------------------------------------------

 npm i
npm WARN registry Unexpected warning for http://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha1-6exflJi57JEOeuOsYmqAXE0J7Kw= integrity checksum failed when using sha1: wanted sha1-6exflJi57JEOeuOsYmqAXE0J7Kw= but got sha512-uRdSdu1oA1rncCQL7sCj8vSyZkgtL7faaw9Tc9rZ3mGgraQ7+Pdx7w5mnOSF3gw9ZNG6oc+KXfkon3bKuROm0g==. (39780 bytes)
npm WARN registry Using stale package data from http://registry.npmjs.org/ due to a request error during revalidation.

> node-sass@4.7.2 install D:\code\Project\src\Project.People.App\node_modules\node-sass
> node scripts/install.js

Cached binary found at C:\Users\HenryIng-Simmons\AppData\Roaming\npm-cache\node-sass\4.7.2\win32-x64-57_binding.node

> uglifyjs-webpack-plugin@0.4.6 postinstall D:\code\Project\src\Project.People.App\node_modules\uglifyjs-webpack-plugin
> node lib/post_install.js


> node-sass@4.7.2 postinstall D:\code\Project\src\Project.People.App\node_modules\node-sass
> node scripts/build.js

Binary found at D:\code\Project\src\Project.People.App\node_modules\node-sass\vendor\win32-x64-57\binding.node
Testing binary
Binary is fine
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 1351 packages in 242.814s

------------------------------------------------------------------------------

npm run build

> @neworbit/Project.people.app@0.1.0 build D:\code\Project\src\Project.People.App
> webpack


[at-loader] Using typescript@2.7.2 from typescript and "tsconfig.json" from D:\code\Project\src\Project.People.App/tsconfig.json.


[at-loader] Checking started in a separate process...

[at-loader] Ok, 0.975 sec.
Hash: 6e1a16b06948ebce53fb
Version: webpack 3.11.0
Time: 62578ms
          Asset      Size  Chunks                    Chunk Names
  css/icons.eot    166 kB          [emitted]
  css/icons.ttf    166 kB          [emitted]
  css/icons.svg    444 kB          [emitted]  [big]
      js/app.js   7.54 MB       0  [emitted]  [big]  app
    css/app.css    968 kB       0  [emitted]  [big]  app
  js/app.js.map   7.34 MB       0  [emitted]         app
css/app.css.map  88 bytes       0  [emitted]         app
 [125] ./src/crud/project/index.ts 860 bytes {0} [built]
[1218] ./src/index.tsx 2.22 kB {0} [built]
[1290] ./src/app.tsx 6.54 kB {0} [built]
[1309] ./src/MenuWrapper.tsx 5.61 kB {0} [built]
[1609] ./src/Breadcrumbs.tsx 3.56 kB {0} [built]
[1610] ./src/LoadingBar.tsx 679 bytes {0} [built]
[2175] ./src/search/Search.tsx 10.6 kB {0} [built]
[2264] ./src/vetting/VettingGrid.tsx 1.15 kB {0} [built]
[2265] ./src/routes.ts 1 kB {0} [built]
[2266] ./src/resourcing/routes.ts 1.12 kB {0} [built]
[2268] ./src/search/routes.ts 216 bytes {0} [built]
[2269] ./src/reducers.ts 877 bytes {0} [built]
[2272] ./src/history/index.ts 158 bytes {0} [built]
[2274] ./src/style/index.scss 41 bytes {0} [built]
[2275] ./node_modules/css-loader!./node_modules/resolve-url-loader!./node_modules/sass-loader/lib/loader.js?sourceMap!./src/style/index.scss 735 kB [built]
    + 2271 hidden modules
Child extract-text-webpack-plugin ../App.Common/node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js!node_modules/resolve-url-loader/index.js!node_modules/sass-loader/lib/loader.js?sourceMap!src/style/index.scss:
     3 assets
       [1] ./node_modules/css-loader!./node_modules/resolve-url-loader!./node_modules/sass-loader/lib/loader.js?sourceMap!./src/style/index.scss 735 kB {0} [built]
        + 8 hidden modules
```

[2018-02-16T14_36_56_906Z-debug.log](https://github.com/npm/npm/files/1731705/2018-02-16T14_36_56_906Z-debug.log)

[2018-02-16T14_29_24_026Z-debug.log](https://github.com/npm/npm/files/1731706/2018-02-16T14_29_24_026Z-debug.log)

**Comment by hisuwh** [comment]
After running all of the above and committing the new package-lock.json this still failed on our build server with the same issue

**Comment by hisuwh** [comment]
I've updated the node version on our build server to 6.13.0 and it is now building
