### ISSUE TITLE
issue while installing npm

### ISSUE THREAD

**Issue by Yash13490** [npm/npm#19854]
#### I'm opening this issue because:
  - [ ] npm is producing an incorrect install.
 
#### What's going wrong?
Issues coming while installing npm...

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\TCS\\nodejs\\node.exe',
1 verbose cli   'C:\\TCS\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'npm' ]
2 info using npm@4.0.5
3 info using node@v7.4.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData npm
8 silly fetchNamedPackageData npm
9 silly mapToRegistry name npm
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://artifactoryprod.es.ad.adp.com/artifactory/api/npm/adp-ui-framework-npm
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'npm',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'npm',
12 silly mapToRegistry   name: 'npm',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://artifactoryprod.es.ad.adp.com/artifactory/api/npm/adp-ui-framework-npm/npm
14 verbose request uri https://artifactoryprod.es.ad.adp.com/artifactory/api/npm/adp-ui-framework-npm/npm
15 verbose request no auth needed
16 info attempt registry request try #1 at 5:59:00 PM
17 verbose request id 486290566c6e533c
18 http request GET https://artifactoryprod.es.ad.adp.com/artifactory/api/npm/adp-ui-framework-npm/npm
19 info retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND artifactoryprod.es.ad.adp.com artifactoryprod.es.ad.adp.com:443
20 info attempt registry request try #2 at 5:59:12 PM
21 http request GET https://artifactoryprod.es.ad.adp.com/artifactory/api/npm/adp-ui-framework-npm/npm
22 info retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND artifactoryprod.es.ad.adp.com artifactoryprod.es.ad.adp.com:443
23 info attempt registry request try #3 at 6:00:12 PM
24 http request GET https://artifactoryprod.es.ad.adp.com/artifactory/api/npm/adp-ui-framework-npm/npm
25 silly fetchPackageMetaData Error: getaddrinfo ENOTFOUND artifactoryprod.es.ad.adp.com artifactoryprod.es.ad.adp.com:443
25 silly fetchPackageMetaData     at errnoException (dns.js:28:10)
25 silly fetchPackageMetaData     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
25 silly fetchPackageMetaData  error for npm { Error: getaddrinfo ENOTFOUND artifactoryprod.es.ad.adp.com artifactoryprod.es.ad.adp.com:443
25 silly fetchPackageMetaData     at errnoException (dns.js:28:10)
25 silly fetchPackageMetaData     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
25 silly fetchPackageMetaData   code: 'ENOTFOUND',
25 silly fetchPackageMetaData   errno: 'ENOTFOUND',
25 silly fetchPackageMetaData   syscall: 'getaddrinfo',
25 silly fetchPackageMetaData   hostname: 'artifactoryprod.es.ad.adp.com',
25 silly fetchPackageMetaData   host: 'artifactoryprod.es.ad.adp.com',
25 silly fetchPackageMetaData   port: 443 }
26 silly rollbackFailedOptional Starting
27 verbose stack TypeError: Cannot read property 'path' of null
27 verbose stack     at Installer.rollbackFailedOptional (C:\TCS\nodejs\node_modules\npm\lib\install.js:505:29)
27 verbose stack     at Array.<anonymous> (C:\TCS\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
27 verbose stack     at LOOP (C:\TCS\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
27 verbose stack     at C:\TCS\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:18:7
27 verbose stack     at C:\TCS\nodejs\node_modules\npm\lib\install.js:331:5
27 verbose stack     at Array.<anonymous> (C:\TCS\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
27 verbose stack     at LOOP (C:\TCS\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
27 verbose stack     at chain (C:\TCS\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
27 verbose stack     at C:\TCS\nodejs\node_modules\npm\lib\install.js:288:5
27 verbose stack     at C:\TCS\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:16:22
28 verbose cwd C:\Users\daveyas1
29 error Windows_NT 6.1.7601
30 error argv "C:\\TCS\\nodejs\\node.exe" "C:\\TCS\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "npm"
31 error node v7.4.0
32 error npm  v4.0.5
33 error Cannot read property 'path' of null
34 error If you need help, you may report this error at:
34 error     <https://github.com/npm/npm/issues>
35 verbose exit [ 1, true ]

**Comment by hiteshsahu** [comment]
Possible duplicate https://github.com/npm/npm/issues/15348
