### ISSUE TITLE
NPM breaks EVERY TIME I install a package

### ISSUE THREAD

**Issue by joshuao3** [npm/npm#19867]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Every time I run "npm -install" on ANY PACKAGE the node_modules/npm folder is deleted. There is nothing in the messages during the package install that suggests an error. So, when I try to run npm at a later date I get the following message:

```
module.js:540
    throw err;
    ^

Error: Cannot find module 'C:\www\nodejs\node_modules\npm\bin\npm-cli.js'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
module.js:540
    throw err;
    ^

Error: Cannot find module 'C:\www\nodejs\node_modules\npm\bin\npm-cli.js'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

This has been happening on EVERY Windows platform on which I've been installed any recent version of Node for the last few months. The "solution" is to run a repair of Node from the msi after every npm install. 

### supporting information:

 - `npm -v` prints: 5.6.0
 - `node -v` prints: v8.9.4
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows 64-bit

**Comment by legodude17** [comment]
Try running `npm install` instead of `npm -install`

**Comment by joshuao3** [comment]
`npm install` is the tested command line.  I'm not sure why I added the hyphen to this bug report.

**Comment by kenany** [comment]
Are you running `npm install` from within the `C:\www\nodejs` directory by any chance?

**Comment by joshuao3** [comment]
Yes, every time. The www\nodejs folder is actually the location of node.js and npm.cmd. I've been doing this for a number of years and didn't have a problem until recently.

**Comment by kenany** [comment]
`npm@5` auto-prunes, hence the behavior you're seeing. See https://github.com/npm/npm/issues/16853 and https://github.com/npm/npm/pull/18921.

**Comment by joshuao3** [comment]
Kenan, I'm not sure I understand how this is "as designed" behavior. 

As a test I did this:
1. created c:\www\nodejs\demo
2. changed to that new folder
3. executed "npm install aws-sdk"

The aws-sdk installed, but now the c:\www\nodejs\node_modules\npm folder is deleted and npm no longer works. How is this even remotely what is supposed to happen? I may be missing something, but executing npm should not render it dead after, right?

**Comment by kenany** [comment]
Sorry, you said that you were running `npm install` from within `C:\www\nodejs`, not `C:\www\nodejs\demo`, so I misinterpreted the issue.

**Comment by bensontrent** [comment]
If there's not already a package.json at `C:\www\nodejs\demo`, then npm will go up the directory tree to the nearest package.json location, or directory containing a `node_modules` folder, hence npm is installing `aws-sdk` at `C:\www\nodejs` and auto-pruning npm (itself) out of the directory tree.  You must first do an `npm init` to install `aws-sdk` at the `C:\www\nodejs\demo`, location.  

`npm init && npm -i aws-sdk` as a command will work at the `C:\www\nodejs\demo` directory.  Alternatively, you _possibly_ could also add a `package.json` file with `npm` as a dependency of the project at `C:\www\nodejs\` to continue your preferred practices.

**Comment by joshuao3** [comment]
Ok, thank you for the response! Your solution is spot-on and I'll adjust my practices going forward.

I have a semi-rhetorical question that I'm directing toward the developers who can speak to this. Would it make sense to add a bit of code to npm that protects itself against self-mutilation? Or at least displays a message that says why it's about to self-destruct?
