### ISSUE TITLE
error with npm itself

### ISSUE THREAD

**Issue by dbezhani** [npm/npm#19868]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [X ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
C:\Program Files (x86)\Microsoft Visual Studio 2017\Web\External\npm.CMD" install
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files (x86)\\Microsoft Visual Studio 2017\\Web\\External\\Node.exe" "C:\\Program Files (x86)\\Microsoft Visual Studio 2017\\Web\\External\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v5.4.1
npm ERR! npm  v3.3.4
npm ERR! code EMISSINGARG
npm ERR! typeerror Error: Missing required argument #2
npm ERR! typeerror     at exports.findRequirement (C:\Program Files (x86)\Microsoft Visual Studio 2017\Web\External\node_modules\npm\lib\install\deps.js:475:3)
npm ERR! typeerror     at C:\Program Files (x86)\Microsoft Visual Studio 2017\Web\External\node_modules\npm\lib\install\deps.js:90:19
npm ERR! typeerror     at zalgoSafe (C:\Program Files (x86)\Microsoft Visual Studio 2017\Web\External\node_modules\dezalgo\dezalgo.js:20:10)
npm ERR! typeerror     at finalize (C:\Program Files (x86)\Microsoft Visual Studio 2017\Web\External\node_modules\realize-package-specifier\index.js:37:5)
npm ERR! typeerror     at C:\Program Files (x86)\Microsoft Visual Studio 2017\Web\External\node_modules\realize-package-specifier\index.js:22:20
npm ERR! typeerror     at FSReqWrap.oncomplete (fs.js:82:15)
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>
npm ERR! Please include the following file with any support request:
npm ERR!     D:\TFS\EmployerPortal_Core\EmployerPortal\MSRA.EPR.Portal\npm-debug.log

#### How can the CLI team reproduce the problem?

Just tried to run Restore packages

### supporting information:

 npm-debug.log:

npm-debug.log0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\Microsoft Visual Studio 2017\\Web\\External\\Node.exe',
1 verbose cli   'C:\\Program Files (x86)\\Microsoft Visual Studio 2017\\Web\\External\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@3.3.4
3 info using node@v5.4.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly install normalizeTree
8 verbose stack Error: Missing required argument #2
8 verbose stack     at exports.findRequirement (C:\Program Files (x86)\Microsoft Visual Studio 2017\Web\External\node_modules\npm\lib\install\deps.js:475:3)
8 verbose stack     at C:\Program Files (x86)\Microsoft Visual Studio 2017\Web\External\node_modules\npm\lib\install\deps.js:90:19
8 verbose stack     at zalgoSafe (C:\Program Files (x86)\Microsoft Visual Studio 2017\Web\External\node_modules\dezalgo\dezalgo.js:20:10)
8 verbose stack     at finalize (C:\Program Files (x86)\Microsoft Visual Studio 2017\Web\External\node_modules\realize-package-specifier\index.js:37:5)
8 verbose stack     at C:\Program Files (x86)\Microsoft Visual Studio 2017\Web\External\node_modules\realize-package-specifier\index.js:22:20
8 verbose stack     at FSReqWrap.oncomplete (fs.js:82:15)
9 verbose cwd D:\TFS\EmployerPortal_Core\EmployerPortal\MSRA.EPR.Portal
10 error Windows_NT 10.0.15063
11 error argv "C:\\Program Files (x86)\\Microsoft Visual Studio 2017\\Web\\External\\Node.exe" "C:\\Program Files (x86)\\Microsoft Visual Studio 2017\\Web\\External\\node_modules\\npm\\bin\\npm-cli.js" "install"
12 error node v5.4.1
13 error npm  v3.3.4
14 error code EMISSINGARG
15 error typeerror Error: Missing required argument #2
15 error typeerror     at exports.findRequirement (C:\Program Files (x86)\Microsoft Visual Studio 2017\Web\External\node_modules\npm\lib\install\deps.js:475:3)
15 error typeerror     at C:\Program Files (x86)\Microsoft Visual Studio 2017\Web\External\node_modules\npm\lib\install\deps.js:90:19
15 error typeerror     at zalgoSafe (C:\Program Files (x86)\Microsoft Visual Studio 2017\Web\External\node_modules\dezalgo\dezalgo.js:20:10)
15 error typeerror     at finalize (C:\Program Files (x86)\Microsoft Visual Studio 2017\Web\External\node_modules\realize-package-specifier\index.js:37:5)
15 error typeerror     at C:\Program Files (x86)\Microsoft Visual Studio 2017\Web\External\node_modules\realize-package-specifier\index.js:22:20
15 error typeerror     at FSReqWrap.oncomplete (fs.js:82:15)
15 error typeerror This is an error with npm itself. Please report this error at:
15 error typeerror     <http://github.com/npm/npm/issues>
16 verbose exit [ 1, true ]

**Comment by kenany** [comment]
Does this also occur with a stable version of Node.js and the latest version of `npm`?

**Comment by dbezhani** [comment]
I only try stable version.
________________________________

**Comment by kenany** [comment]
Node.js v5 is not stable. In fact, it isn't even being worked on anymore. Node.js v5 became v6 a long time ago.

**Comment by dbezhani** [comment]
I'm using 8.9

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by kenany** [comment]
Can I see an error log with that version?

**Comment by dbezhani** [comment]
I did include in when I open the issue.
________________________________

**Comment by kenany** [comment]
The original log shows:

```
12 error node v5.4.1
```

Which is contrary to:

> I'm using 8.9

**Comment by dbezhani** [comment]
I do not know why it's said that version in error log,
but when I type node -v, it's showing me v8.9.4
________________________________

**Comment by kenany** [comment]
Sounds like you may have multiple versions of Node.js installed.

**Comment by dbezhani** [comment]
Visual Studio 2017 has old version, but I can't update it is giving me errors and do not creating log file as it states here
---------------------------------------------------------------------------------------------
npm ERR! Cannot find module 'internal/util/types'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Program Files (x86)\Microsoft Visual Studio 2017\Web\External\npm-debug.log

C:\Program Files (x86)\Microsoft Visual Studio 2017\Web\External>
--------------------------------------------------------------------------------------------

I manually copy the node.exe 8.9.4 but it did not help.

Thanks
________________________________

**Comment by mmunchandersen** [comment]
@dbezhani I have the exact same issue. Did you fix it? Or figured a work-a-round?
In a Visual Studio 2017 asp.net mvc 4.6.1 solution npm works. However, in a VS2017 asp.net core 2.1 solution I'm getting the error.

If I create a new asp.net core 2.1 solution/project and add a package.json file I can install packages just fine.

I think that me having a comment in my package.json file caused the problem. After removing the comment (see below) packages update and installs again.

**I had this:**
  "devDependencies": {
    "gulp": "3.9.1",
    "//": "Gulp-sass 4 requires Node 6 or greater, https://github.com/dlmanning/gulp-sass/issues/684", 
    "gulp-sass": "3.2.1",
    "gulp-cssmin": "0.2.0",
    "gulp-concat": "2.6.1",
    ...

**I changed to this**
  "devDependencies": {
    "gulp": "3.9.1",
    "gulp-sass": "3.2.1",
    "gulp-cssmin": "0.2.0",
    "gulp-concat": "2.6.1",
    ...

### Error
PATH=.\node_modules\.bin;C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Web\External;%PATH%;C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Git\cmd;C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Git\mingw32\bin
"C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Web\External\npm.CMD" install
npm ERR! Windows_NT 10.0.17134
npm ERR! argv "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\Web\\External\\Node.exe" "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\Web\\External\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v5.4.1
npm ERR! npm  v3.3.4
npm ERR! code EMISSINGARG
npm ERR! typeerror Error: Missing required argument #2
npm ERR! typeerror     at exports.findRequirement (C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Web\External\node_modules\npm\lib\install\deps.js:475:3)
npm ERR! typeerror     at C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Web\External\node_modules\npm\lib\install\deps.js:90:19
npm ERR! typeerror     at zalgoSafe (C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Web\External\node_modules\dezalgo\dezalgo.js:20:10)
npm ERR! typeerror     at finalize (C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Web\External\node_modules\realize-package-specifier\index.js:37:5)
npm ERR! typeerror     at C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Web\External\node_modules\realize-package-specifier\index.js:22:20
npm ERR! typeerror     at FSReqWrap.oncomplete (fs.js:82:15)
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>
npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Morten\Documents\GitHub\MyProject\src\MyProject\MyProject.Web\npm-debug.log

### node.exe
I can find node.exe here:
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\JavaScript\Node.JS\v6.4.0_x86\node.exe
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Web\External\x86\Node.exe
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Web\External\Node.exe
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\JavaScript\Node.JS\v6.4.0_x86\node.exe
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Web\External\x86\Node.exe
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Web\External\Node.exe

### npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\Web\\External\\Node.exe',
1 verbose cli   'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\Web\\External\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@3.3.4
3 info using node@v5.4.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly install normalizeTree
8 verbose stack Error: Missing required argument #2
8 verbose stack     at exports.findRequirement (C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Web\External\node_modules\npm\lib\install\deps.js:475:3)
8 verbose stack     at C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Web\External\node_modules\npm\lib\install\deps.js:90:19
8 verbose stack     at zalgoSafe (C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Web\External\node_modules\dezalgo\dezalgo.js:20:10)
8 verbose stack     at finalize (C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Web\External\node_modules\realize-package-specifier\index.js:37:5)
8 verbose stack     at C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Web\External\node_modules\realize-package-specifier\index.js:22:20
8 verbose stack     at FSReqWrap.oncomplete (fs.js:82:15)
9 verbose cwd C:\Users\Morten\Documents\GitHub\MyProject\src\MyProject\MyProject.Web
10 error Windows_NT 10.0.17134
11 error argv "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\Web\\External\\Node.exe" "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\Web\\External\\node_modules\\npm\\bin\\npm-cli.js" "install"
12 error node v5.4.1
13 error npm  v3.3.4
14 error code EMISSINGARG
15 error typeerror Error: Missing required argument #2
15 error typeerror     at exports.findRequirement (C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Web\External\node_modules\npm\lib\install\deps.js:475:3)
15 error typeerror     at C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Web\External\node_modules\npm\lib\install\deps.js:90:19
15 error typeerror     at zalgoSafe (C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Web\External\node_modules\dezalgo\dezalgo.js:20:10)
15 error typeerror     at finalize (C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Web\External\node_modules\realize-package-specifier\index.js:37:5)
15 error typeerror     at C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Web\External\node_modules\realize-package-specifier\index.js:22:20
15 error typeerror     at FSReqWrap.oncomplete (fs.js:82:15)
15 error typeerror This is an error with npm itself. Please report this error at:
15 error typeerror     <http://github.com/npm/npm/issues>
16 verbose exit [ 1, true ]
