### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by joyerf** [npm/npm#19863]
npm install

16970 verbose stack RangeError: Maximum call stack size exceeded
16970 verbose stack     at String.trim (native)
16970 verbose stack     at moduleName (/usr/local/lib/node_modules/npm/lib/utils/module-name.js:25:77)
16970 verbose stack     at failedDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:396:41)
16970 verbose stack     at failedDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:396:9)
16970 verbose stack     at failedDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:396:9)
16970 verbose stack     at failedDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:396:9)
16970 verbose stack     at failedDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:396:9)
16970 verbose stack     at failedDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:396:9)
16970 verbose stack     at failedDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:396:9)
16970 verbose stack     at failedDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:396:9)
16970 verbose stack     at failedDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:396:9)
16970 verbose stack     at failedDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:396:9)
16970 verbose stack     at failedDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:396:9)
16970 verbose stack     at failedDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:396:9)
16970 verbose stack     at failedDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:396:9)
16970 verbose stack     at failedDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:396:9)
16972 verbose Darwin 16.7.0
16973 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
16974 verbose node v6.10.1
16975 verbose npm  v5.6.0
16976 error Maximum call stack size exceeded
16977 verbose exit [ 1, true ]

**Comment by andrei-tofan** [comment]
+1

**Comment by jtiscione** [comment]
What version of npm is doing this? I was forced to install the latest version (5.6.0) because node installs always get corrupted at least once per month. I'm getting the same error.

**Comment by csvwolf** [comment]
The same in npm 5.7.1

**Comment by jameswilddev** [comment]
I've started seeing this since upgrading to npm 5.7.1 on Windows 64, but not reliably.

**Comment by jsjoeio** [comment]
I'm getting this exact same error. Using npm 5.7.1. on macOS

**Comment by moneymikeMD** [comment]
I'm seeing this too and I can't get around it.

5.6.0 on Mac

**Comment by wfairclough** [comment]
I saw this error when I copied a project and changed many of the fields in the `package.json`  file.
The issue was resolved after removing my node_modules and package-lock.json: `rm -fr node_modules/ package-lock.json`

**Comment by RyanCavanaugh** [comment]
Saw this as an intermittent failure during a fresh install - retrying worked.

Log and package.json:

https://gist.github.com/RyanCavanaugh/c6ee95014c488a4846e3e15d9fc6fe4d

**Comment by mAiNiNfEcTiOn** [comment]
We were getting this same error in our CI/CD, the solution so far seemed to be to remove the `package-lock.json` from our git repos and add it to the `.gitignore` list.

If we get the error again, I'll notify here.

(EDIT: And this was with npm 5.8.0)

**Comment by MadLittleMods** [comment]
We were also seeing this with `npm@5.6.0` and `npm@5.8.0` with a `package-lock.json` generated in `npm@5.6.0`.

 - Windows 10, https://gist.github.com/MadLittleMods/e4726cc7c6e19144ba8a8341f41986fa
 - macOS, https://gist.github.com/MadLittleMods/391aa2a9cc8b86314bbbc5fb19da26a6
 - GitLab CI, https://gitlab.com/gitlab-org/gitter/webapp/-/jobs/60299944

---

After removing `node_modules/` and `package-lock.json` and regenerating `package-lock.json` with `npm@5.8.0` via `npm i`, things install correctly.
