### ISSUE TITLE
none of npm commands working and they were previously working

### ISSUE THREAD

**Issue by AndreaCole1340** [npm/npm#19881]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
nothing is running
#### How can the CLI team reproduce the problem?
I have tried fresh install but still receving this error when running any npm command
npm -v
Error: EISDIR: illegal operation on a directory, read
TypeError: Cannot read property 'get' of undefined
    at errorHandler (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:205:18)
    at C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js:83:20
    at cb (C:\Program Files\nodejs\node_modules\npm\lib\npm.js:224:22)
    at C:\Program Files\nodejs\node_modules\npm\lib\npm.js:262:24
    at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:81:7
    at Array.forEach (<anonymous>)
    at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:80:13
    at f (C:\Program Files\nodejs\node_modules\npm\node_modules\once\once.js:25:25)
    at finalize (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:194:14)
    at Conf.afterCARead (C:\Program Files\nodejs\node_modules\npm\lib\config\load-cafile.js:14:14)
    at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:495:12)
C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:205
  if (npm.config.get('json')) {
                 ^

TypeError: Cannot read property 'get' of undefined
    at process.errorHandler (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:205:18)
    at emitOne (events.js:116:13)
    at process.emit (events.js:211:7)
    at process._fatalException (bootstrap_node.js:374:26)
5.6.0

**Comment by zixuan75** [comment]
[ ] Did you mean npm is crashing?

**Comment by stevinus73** [comment]
The version is outputted after the error is displayed.

**Comment by stevinus73** [comment]
I have a issue with installing in npm whcih I have opened an issue that is #19882.

**Comment by AndreaCole1340** [comment]
yes I see the version but how can I get rid of the error and what is the cause of this error

**Comment by stevinus73** [comment]
@AndreaCole1340 Can you tell me by installing something like angular-cli?

**Comment by stevinus73** [comment]
Is it installed after the error displaying? Or is cause errors with installing? If it you don't solve this problem, try reinstalling your NPM.

# Your problems
If you tried with installing and it is installed, it is done and receiving this error is not possible when you running any NPM command.
## Problem 1: try reinstalling your NPM
If you haven't tried reinstalling your NPM with fresh install? Are you saying you are running an fresh installation:
`npm install angular-cli`?
## Problem 2: try fresh reinstalling
If you haven't tried fresh uninstall and fresh install, please try it.

**Comment by stevinus73** [comment]
Not nothing is running
