### ISSUE TITLE
Can't install @angular/cli

### ISSUE THREAD

**Issue by buddyackerman** [npm/npm#19901]
### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

### What's going wrong?
It won't install @angular/cli

### How can the CLI team reproduce the problem?

running `npm install -g @angular/cli` produces the following result

    npm ERR! code E404
    npm ERR! 404 Not Found: @angular/cli@latest

#### He's the log file generated after the error

    0 info it worked if it ends with ok
    1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
    1 verbose cli   'C:\\Users\\some_dude\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
    1 verbose cli   'install',
    1 verbose cli   '-g',
    1 verbose cli   '@angular/cli' ]
    2 info using npm@5.6.0
    3 info using node@v9.5.0
    4 verbose npm-session 5f2f241b20dec430
    5 silly install loadCurrentTree
    6 silly install readGlobalPackageData
    7 http fetch GET 404 http://registry.npmjs.org/@angular%2fcli 558ms
    8 silly fetchPackageMetaData error for @angular/cli@latest 404 Not Found: @angular/cli@latest
    9 verbose stack Error: 404 Not Found: @angular/cli@latest
    9 verbose stack     at fetch.then.res (C:\Users\some_dude\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\lib\fetchers\registry\fetch.js:42:19)
    9 verbose stack     at tryCatcher (C:\Users\some_dude\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
    9 verbose stack     at Promise._settlePromiseFromHandler (C:\Users\some_dude\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
    9 verbose stack     at Promise._settlePromise (C:\Users\some_dude\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
    9 verbose stack     at Promise._settlePromise0 (C:\Users\some_dude\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
    9 verbose stack     at Promise._settlePromises (C:\Users\some_dude\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
    9 verbose stack     at Async._drainQueue (C:\Users\some_dude\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
    9 verbose stack     at Async._drainQueues (C:\Users\some_dude\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
    9 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\some_dude\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
    9 verbose stack     at runCallback (timers.js:756:18)
    9 verbose stack     at tryOnImmediate (timers.js:717:5)
    9 verbose stack     at processImmediate [as _immediateCallback] (timers.js:697:5)
    10 verbose cwd C:\Projects\myproject\app
    11 verbose Windows_NT 10.0.14393
    12 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\some_dude\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@angular/cli"
    13 verbose node v9.5.0
    14 verbose npm  v5.6.0
    15 error code E404
    16 error 404 Not Found: @angular/cli@latest
    17 verbose exit [ 1, true ]

#### Here's my .npmrc file

    _auth = "blahblahblah"
    proxy=http://me:mypassword@proxy/
    https-proxy=http://me:mypassword@proxy/
    email = myemail@company.com
    always-auth = true
    strict-ssl=false
    ca=null
    registry=http://registry.npmjs.org/
    @mycompany:registry=http://dcsartifacts.mycompany.com/artifactory/api/npm/npm
    ENV=localiis

**Comment by buddyackerman** [comment]
Relatively simple fix, I removed the auth information from the .npmrc file.  Not sure why that was a problem with this one package but it fixed the problem.
