### ISSUE TITLE
Cannot find module 'ansi'  

### ISSUE THREAD

**Issue by moulichandu** [npm/npm#19912]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by moulichandu** [comment]
while install cordova in my machine with below command 
"npm install cordova -g" I have received the following error
MODULE_NOT_FOUND
Cannot find module 'ansi'

This is my npm-debug.log file 
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/n/versions/node/9.6.1/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   'cordova',
1 verbose cli   '-g' ]
2 info using npm@3.5.2
3 info using node@v9.6.1
4 verbose stack Error: Cannot find module 'ansi'
4 verbose stack     at Function.Module._resolveFilename (module.js:557:15)
4 verbose stack     at Function.Module._load (module.js:484:25)
4 verbose stack     at Module.require (module.js:606:17)
4 verbose stack     at require (internal/module.js:11:18)
4 verbose stack     at Object.<anonymous> (/usr/share/npm/lib/ls.js:15:13)
4 verbose stack     at Module._compile (module.js:662:30)
4 verbose stack     at Object.Module._extensions..js (module.js:673:10)
4 verbose stack     at Module.load (module.js:575:32)
4 verbose stack     at tryModuleLoad (module.js:515:12)
4 verbose stack     at Function.Module._load (module.js:507:3)
5 verbose cwd /home/chandu
6 error Linux 4.13.0-32-generic
7 error argv "/usr/local/n/versions/node/9.6.1/bin/node" "/usr/bin/npm" "install" "cordova" "-g"
8 error node v9.6.1
9 error npm  v3.5.2
10 error code MODULE_NOT_FOUND
11 error Cannot find module 'ansi'
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]

**Comment by zhangqunshi** [comment]
I got the same error:
```
npm ERR! Linux 4.13.0-36-generic
npm ERR! argv "/usr/local/n/versions/node/9.6.1/bin/node" "/usr/bin/npm" "install"
npm ERR! node v9.6.1
npm ERR! npm  v3.5.2
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'ansi'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/buaa/elasticsearch-head/npm-debug.log

```

**Comment by zhangqunshi** [comment]
I found the reason, because the npm version is old, my is 3.5.2, and please upgrade to 5.7.1 use the following command:
```
npm install -g npm
```
BTW, you need run npm install with sudo, otherwise the npm still is old version. 

Good luck,
Kris
