### ISSUE TITLE
CERT_HAS_EXPIRED

### ISSUE THREAD

**Issue by camarasidi12** [npm/npm#19917]
#### I'm opening this issue because:

  - [ ] npm is crashing.

#### What's going wrong?
After doing 
 npm config set registry https://nexus.afadevtool.net/repository/npmjs-gro
and 
λ npm install -g browser-sync

i get error saying that de certificate has expired
#### How can the CLI team reproduce the problem?
do: 
 npm config set registry https://nexus.afadevtool.net/repository/npmjs-gro
and 
λ npm install -g browser-sync

   
THE LOG FILE CONTENT
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'browser-sync' ]
2 info using npm@3.10.10
3 info using node@v6.11.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData browser-sync
8 silly fetchNamedPackageData browser-sync
9 silly mapToRegistry name browser-sync
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://nexus.afadevtool.net/repository/npmjs-group/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'browser-sync',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'browser-sync',
12 silly mapToRegistry   name: 'browser-sync',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://nexus.afadevtool.net/repository/npmjs-group/browser-sync
14 verbose request uri https://nexus.afadevtool.net/repository/npmjs-group/browser-sync
15 verbose request no auth needed
16 info attempt registry request try #1 at 09:34:04
17 verbose request id 91224f614526ed0d
18 http request GET https://nexus.afadevtool.net/repository/npmjs-group/browser-sync
19 info retry will retry, error on last attempt: Error: certificate has expired
20 info attempt registry request try #2 at 09:34:15
21 http request GET https://nexus.afadevtool.net/repository/npmjs-group/browser-sync
22 info retry will retry, error on last attempt: Error: certificate has expired
23 info attempt registry request try #3 at 09:35:17
24 http request GET https://nexus.afadevtool.net/repository/npmjs-group/browser-sync
25 silly fetchPackageMetaData Error: certificate has expired
25 silly fetchPackageMetaData     at Error (native)
25 silly fetchPackageMetaData     at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
25 silly fetchPackageMetaData     at emitNone (events.js:86:13)
25 silly fetchPackageMetaData     at TLSSocket.emit (events.js:185:7)
25 silly fetchPackageMetaData     at TLSSocket._finishInit (_tls_wrap.js:610:8)
25 silly fetchPackageMetaData     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)
25 silly fetchPackageMetaData  error for browser-sync { Error: certificate has expired
25 silly fetchPackageMetaData     at Error (native)
25 silly fetchPackageMetaData     at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
25 silly fetchPackageMetaData     at emitNone (events.js:86:13)
25 silly fetchPackageMetaData     at TLSSocket.emit (events.js:185:7)
25 silly fetchPackageMetaData     at TLSSocket._finishInit (_tls_wrap.js:610:8)
25 silly fetchPackageMetaData     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38) code: 'CERT_HAS_EXPIRED' }
26 silly rollbackFailedOptional Starting
27 silly rollbackFailedOptional Finishing
28 silly runTopLevelLifecycles Finishing
29 silly install printInstalled
30 verbose stack Error: certificate has expired
30 verbose stack     at Error (native)
30 verbose stack     at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
30 verbose stack     at emitNone (events.js:86:13)
30 verbose stack     at TLSSocket.emit (events.js:185:7)
30 verbose stack     at TLSSocket._finishInit (_tls_wrap.js:610:8)
30 verbose stack     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)
31 verbose cwd C:\Users\S641732
32 error Windows_NT 6.1.7601
33 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "browser-sync"
34 error node v6.11.0
35 error npm  v3.10.10
36 error code CERT_HAS_EXPIRED
37 error certificate has expired
38 error If you need help, you may report this error at:
38 error     <https://github.com/npm/npm/issues>
39 verbose exit [ 1, true ]
-->

-->

**Comment by wvanderdeijl** [comment]
I guess you have to talk to the admins of afadevtool.net. Their https certificate has expired almost three months ago: https://www.ssllabs.com/ssltest/analyze.html?d=nexus.afadevtool.net&latest
That’s not something you can blame NPM for
