### ISSUE TITLE
All NPM Commands Failed

### ISSUE THREAD

**Issue by jeffreytanuwidjaja** [npm/npm#19926]
#### I'm opening this issue because:

  - [x ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### How can the CLI team reproduce the problem?

any npm commands won't work, 
even npm-v can't
try version 8.9.4 and try version 9.6.1 also can't

### supporting information:

 - `npm -v` prints:

> PS C:\Users\styx green> npm -v
> Error: EPERM: operation not permitted, mkdir 'C:\Program Files\Git'
> TypeError: Cannot read property 'get' of undefined
>     at errorHandler (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:205:18)
>     at C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js:83:20
>     at cb (C:\Program Files\nodejs\node_modules\npm\lib\npm.js:224:22)
>     at C:\Program Files\nodejs\node_modules\npm\lib\npm.js:262:24
>     at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:81:7
>     at Array.forEach (<anonymous>)
>     at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:80:13
>     at f (C:\Program Files\nodejs\node_modules\npm\node_modules\once\once.js:25:25)
>     at afterExtras (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:178:20)
>     at C:\Program Files\nodejs\node_modules\npm\node_modules\mkdirp\index.js:35:29
>     at C:\Program Files\nodejs\node_modules\npm\node_modules\mkdirp\index.js:35:29
>     at C:\Program Files\nodejs\node_modules\npm\node_modules\mkdirp\index.js:35:29
>     at C:\Program Files\nodejs\node_modules\npm\node_modules\mkdirp\index.js:35:29
>     at C:\Program Files\nodejs\node_modules\npm\node_modules\mkdirp\index.js:35:29
>     at C:\Program Files\nodejs\node_modules\npm\node_modules\mkdirp\index.js:35:29
>     at C:\Program Files\nodejs\node_modules\npm\node_modules\mkdirp\index.js:47:53
> C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:205
>   if (npm.config.get('json')) {
>                  ^
> 
> TypeError: Cannot read property 'get' of undefined
>     at process.errorHandler (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:205:18)
>     at process.emit (events.js:127:13)
>     at process._fatalException (bootstrap_node.js:434:26)
> 5.6.0

 - `node -v` prints:

> 
> PS C:\Users\styx green> node -v
> v9.6.1

 - `npm config get registry` prints:

> PS C:\Users\styx green> npm config get registry
> Error: EPERM: operation not permitted, mkdir 'C:\Program Files\Git'
> TypeError: Cannot read property 'get' of undefined
>     at errorHandler (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:205:18)
>     at C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js:83:20
>     at cb (C:\Program Files\nodejs\node_modules\npm\lib\npm.js:224:22)
>     at C:\Program Files\nodejs\node_modules\npm\lib\npm.js:262:24
>     at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:81:7
>     at Array.forEach (<anonymous>)
>     at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:80:13
>     at f (C:\Program Files\nodejs\node_modules\npm\node_modules\once\once.js:25:25)
>     at afterExtras (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:178:20)
>     at C:\Program Files\nodejs\node_modules\npm\node_modules\mkdirp\index.js:35:29
>     at C:\Program Files\nodejs\node_modules\npm\node_modules\mkdirp\index.js:35:29
>     at C:\Program Files\nodejs\node_modules\npm\node_modules\mkdirp\index.js:35:29
>     at C:\Program Files\nodejs\node_modules\npm\node_modules\mkdirp\index.js:35:29
>     at C:\Program Files\nodejs\node_modules\npm\node_modules\mkdirp\index.js:35:29
>     at C:\Program Files\nodejs\node_modules\npm\node_modules\mkdirp\index.js:35:29
>     at C:\Program Files\nodejs\node_modules\npm\node_modules\mkdirp\index.js:47:53
> C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:205
>   if (npm.config.get('json')) {
>                  ^
> 
> TypeError: Cannot read property 'get' of undefined
>     at process.errorHandler (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:205:18)
>     at process.emit (events.js:127:13)
>     at process._fatalException (bootstrap_node.js:434:26)
> Error: EPERM: operation not permitted, mkdir 'C:\Program Files\Git'
> TypeError: Cannot read property 'get' of undefined
>     at errorHandler (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:205:18)
>     at C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js:83:20
>     at cb (C:\Program Files\nodejs\node_modules\npm\lib\npm.js:224:22)
>     at C:\Program Files\nodejs\node_modules\npm\lib\npm.js:262:24
>     at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:81:7
>     at Array.forEach (<anonymous>)
>     at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:80:13
>     at f (C:\Program Files\nodejs\node_modules\npm\node_modules\once\once.js:25:25)
>     at afterExtras (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:178:20)
>     at Conf.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:234:20)
>     at C:\Program Files\nodejs\node_modules\npm\lib\config\set-user.js:23:20
>     at C:\Program Files\nodejs\node_modules\npm\node_modules\mkdirp\index.js:35:29
>     at C:\Program Files\nodejs\node_modules\npm\node_modules\mkdirp\index.js:35:29
>     at C:\Program Files\nodejs\node_modules\npm\node_modules\mkdirp\index.js:35:29
>     at C:\Program Files\nodejs\node_modules\npm\node_modules\mkdirp\index.js:35:29
>     at C:\Program Files\nodejs\node_modules\npm\node_modules\mkdirp\index.js:35:29
> C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:205
>   if (npm.config.get('json')) {
>                  ^
> 
> TypeError: Cannot read property 'get' of undefined
>     at process.errorHandler (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:205:18)
>     at process.emit (events.js:127:13)
>     at process._fatalException (bootstrap_node.js:434:26)

 - Windows, OS X/macOS, or Linux?: 

> windows 10 64bit

 - Network issues:
   - Geographic location where npm was run: indonesia
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by dmilet** [comment]
(Almost) reproduced described behavior by defining a prefix folder that does not exist in %USERPROFILE%\.npmrc
prefix="C:\Program Files\Git"
(And this prefix directory does not exist on my system)

The error message I got is not 100% the same as reported. I got this behaviour on a clean installation.
Maybe the submitter had other things that came into the picture.

C:\Users\David>npm -v
Error: Failed parsing JSON config key prefix: "C:\Program Files\Git"
    at parseField (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:378:13)
    at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:334:17
    at Array.forEach (<anonymous>)
    at Conf.add (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:333:23)
    at ConfigChain.addString (C:\Program Files\nodejs\node_modules\npm\node_modules\config-chain\index.js:244:8)
    at Conf.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:321:10)
    at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:532:3)
TypeError: Cannot read property 'get' of undefined
    at errorHandler (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:205:18)
    at C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js:83:20
    at cb (C:\Program Files\nodejs\node_modules\npm\lib\npm.js:224:22)
    at C:\Program Files\nodejs\node_modules\npm\lib\npm.js:262:24
    at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:81:7
    at Array.forEach (<anonymous>)
    at Conf.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:80:13)
    at Conf.f (C:\Program Files\nodejs\node_modules\npm\node_modules\once\once.js:25:25)
    at Object.onceWrapper (events.js:219:13)
    at Conf.emit (events.js:127:13)
    at Conf.add (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:337:10)
    at ConfigChain.addString (C:\Program Files\nodejs\node_modules\npm\node_modules\config-chain\index.js:244:8)
    at Conf.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:321:10)
    at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:532:3)
C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:205
  if (npm.config.get('json')) {
                 ^

TypeError: Cannot read property 'get' of undefined
    at process.errorHandler (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:205:18)
    at process.emit (events.js:127:13)
    at process._fatalException (bootstrap_node.js:434:26)
5.6.0

C:\Users\David>npm get config registry
Error: Failed parsing JSON config key prefix: "C:\Program Files\Git"
    at parseField (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:378:13)
    at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:334:17
    at Array.forEach (<anonymous>)
    at Conf.add (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:333:23)
    at ConfigChain.addString (C:\Program Files\nodejs\node_modules\npm\node_modules\config-chain\index.js:244:8)
    at Conf.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:321:10)
    at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:532:3)
TypeError: Cannot read property 'get' of undefined
    at errorHandler (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:205:18)
    at C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js:83:20
    at cb (C:\Program Files\nodejs\node_modules\npm\lib\npm.js:224:22)
    at C:\Program Files\nodejs\node_modules\npm\lib\npm.js:262:24
    at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:81:7
    at Array.forEach (<anonymous>)
    at Conf.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:80:13)
    at Conf.f (C:\Program Files\nodejs\node_modules\npm\node_modules\once\once.js:25:25)
    at Object.onceWrapper (events.js:219:13)
    at Conf.emit (events.js:127:13)
    at Conf.add (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:337:10)
    at ConfigChain.addString (C:\Program Files\nodejs\node_modules\npm\node_modules\config-chain\index.js:244:8)
    at Conf.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:321:10)
    at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:532:3)
C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:205
  if (npm.config.get('json')) {
                 ^

TypeError: Cannot read property 'get' of undefined
    at process.errorHandler (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:205:18)
    at process.emit (events.js:127:13)
    at process._fatalException (bootstrap_node.js:434:26)
Error: Failed parsing JSON config key prefix: "C:\Program Files\Git"
    at parseField (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:378:13)
    at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:334:17
    at Array.forEach (<anonymous>)
    at Conf.add (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:333:23)
    at ConfigChain.addString (C:\Program Files\nodejs\node_modules\npm\node_modules\config-chain\index.js:244:8)
    at Conf.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:321:10)
    at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:532:3)
TypeError: Cannot read property 'get' of undefined
    at errorHandler (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:205:18)
    at C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js:83:20
    at cb (C:\Program Files\nodejs\node_modules\npm\lib\npm.js:224:22)
    at C:\Program Files\nodejs\node_modules\npm\lib\npm.js:262:24
    at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:81:7
    at Array.forEach (<anonymous>)
    at Conf.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:80:13)
    at Conf.f (C:\Program Files\nodejs\node_modules\npm\node_modules\once\once.js:25:25)
    at Object.onceWrapper (events.js:219:13)
    at Conf.emit (events.js:127:13)
    at Conf.add (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:337:10)
    at ConfigChain.addString (C:\Program Files\nodejs\node_modules\npm\node_modules\config-chain\index.js:244:8)
    at Conf.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:321:10)
    at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:532:3)
C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:205
  if (npm.config.get('json')) {
                 ^

TypeError: Cannot read property 'get' of undefined
    at process.errorHandler (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:205:18)
    at process.emit (events.js:127:13)
    at process._fatalException (bootstrap_node.js:434:26)


Ideally, the code should check if the prefix directory exists before trying to use it, and report error message if directory does not exist. Not sure if npm validates the contents of npmrc files.
