### ISSUE TITLE
I am always getting npm publish unexpected error 500 on `npm publish`!!! Please help me, I am really stuck!!!

### ISSUE THREAD

**Issue by BeepLoveKarki** [npm/npm#19924]
```
C:\Users\User\Downloads\rfid-hack>npm publish
npm ERR! publish Failed PUT 500
npm ERR! code E500
npm ERR! Unexpected error (5aa09e99-f92b-40c3-93c8-f535bcfd5ca3). : rfid-hack

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2018-02-27T02_30_49_133Z-debug.log
```
This is the error shown.
The npm version is 5.6.0 and node version is 8.9.4.

The log file says:
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'publish' ]
2 info using npm@5.6.0
3 info using node@v8.9.4
4 verbose npm-session 8302596c763c05e1
5 verbose publish [ '.' ]
6 info lifecycle rfid-hack@1.0.2~prepublish: rfid-hack@1.0.2
7 info lifecycle rfid-hack@1.0.2~prepare: rfid-hack@1.0.2
8 info lifecycle rfid-hack@1.0.2~prepublishOnly: rfid-hack@1.0.2
9 info lifecycle rfid-hack@1.0.2~prepack: rfid-hack@1.0.2
10 info lifecycle rfid-hack@1.0.2~postpack: rfid-hack@1.0.2
11 verbose getPublishConfig undefined
12 silly mapToRegistry name rfid-hack
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry data { type: 'tag',
15 silly mapToRegistry   registry: true,
15 silly mapToRegistry   where: undefined,
15 silly mapToRegistry   raw: 'rfid-hack',
15 silly mapToRegistry   name: 'rfid-hack',
15 silly mapToRegistry   escapedName: 'rfid-hack',
15 silly mapToRegistry   scope: undefined,
15 silly mapToRegistry   rawSpec: '',
15 silly mapToRegistry   saveSpec: null,
15 silly mapToRegistry   fetchSpec: 'latest',
15 silly mapToRegistry   gitRange: undefined,
15 silly mapToRegistry   gitCommittish: undefined,
15 silly mapToRegistry   hosted: undefined }
16 silly mapToRegistry uri https://registry.npmjs.org/rfid-hack
17 verbose publish registryBase https://registry.npmjs.org/
18 silly publish uploading C:\Users\User\AppData\Local\Temp\npm-952-aef8ab27\tmp\fromDir-f2761a28\package.tgz
19 verbose request uri https://registry.npmjs.org/rfid-hack
20 verbose request sending authorization for write operation
21 info attempt registry request try #1 at 08:14:34
22 verbose request using bearer token for auth
23 verbose request id b17ea4acc52ff15d
24 http request PUT https://registry.npmjs.org/rfid-hack
25 http 500 https://registry.npmjs.org/rfid-hack
26 verbose headers { 'content-type': 'application/json',
26 verbose headers   'cache-control': 'max-age=0',
26 verbose headers   'content-length': '68',
26 verbose headers   'accept-ranges': 'bytes',
26 verbose headers   date: 'Tue, 27 Feb 2018 02:29:35 GMT',
26 verbose headers   via: '1.1 varnish',
26 verbose headers   connection: 'keep-alive',
26 verbose headers   'x-served-by': 'cache-ams4123-AMS',
26 verbose headers   'x-cache': 'MISS',
26 verbose headers   'x-cache-hits': '0',
26 verbose headers   'x-timer': 'S1519698574.320498,VS0,VE1028' }
27 info retry will retry, error on last attempt: Error: Unexpected error (3338737c-d7a2-4c88-a03c-f7b65eb90f43). : rfid-hack
28 info attempt registry request try #2 at 08:14:46
29 verbose request using bearer token for auth
30 http request PUT https://registry.npmjs.org/rfid-hack
31 http 500 https://registry.npmjs.org/rfid-hack
32 verbose headers { 'content-type': 'application/json',
32 verbose headers   'cache-control': 'max-age=0',
32 verbose headers   'content-length': '68',
32 verbose headers   'accept-ranges': 'bytes',
32 verbose headers   date: 'Tue, 27 Feb 2018 02:29:46 GMT',
32 verbose headers   via: '1.1 varnish',
32 verbose headers   connection: 'keep-alive',
32 verbose headers   'x-served-by': 'cache-ams4123-AMS',
32 verbose headers   'x-cache': 'MISS',
32 verbose headers   'x-cache-hits': '0',
32 verbose headers   'x-timer': 'S1519698586.567325,VS0,VE1023' }
33 info retry will retry, error on last attempt: Error: Unexpected error (9126c018-e7fd-4cde-b228-53e7da8903ad). : rfid-hack
34 info attempt registry request try #3 at 08:15:47
35 verbose request using bearer token for auth
36 http request PUT https://registry.npmjs.org/rfid-hack
37 http 500 https://registry.npmjs.org/rfid-hack
38 verbose headers { 'content-type': 'application/json',
38 verbose headers   'cache-control': 'max-age=0',
38 verbose headers   'content-length': '68',
38 verbose headers   'accept-ranges': 'bytes',
38 verbose headers   date: 'Tue, 27 Feb 2018 02:30:47 GMT',
38 verbose headers   via: '1.1 varnish',
38 verbose headers   connection: 'keep-alive',
38 verbose headers   'x-served-by': 'cache-ams4123-AMS',
38 verbose headers   'x-cache': 'MISS',
38 verbose headers   'x-cache-hits': '0',
38 verbose headers   'x-timer': 'S1519698647.777298,VS0,VE1007' }
39 error publish Failed PUT 500
40 verbose stack Error: Unexpected error (5aa09e99-f92b-40c3-93c8-f535bcfd5ca3). : rfid-hack
40 verbose stack     at makeError (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:314:12)
40 verbose stack     at RegClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:302:14)
40 verbose stack     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:216:14)
40 verbose stack     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:186:22)
40 verbose stack     at emitTwo (events.js:126:13)
40 verbose stack     at Request.emit (events.js:214:7)
40 verbose stack     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1163:10)
40 verbose stack     at emitOne (events.js:116:13)
40 verbose stack     at Request.emit (events.js:211:7)
40 verbose stack     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1085:12)
40 verbose stack     at Object.onceWrapper (events.js:313:30)
40 verbose stack     at emitNone (events.js:111:20)
40 verbose stack     at IncomingMessage.emit (events.js:208:7)
40 verbose stack     at endReadableNT (_stream_readable.js:1055:12)
40 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:138:11)
40 verbose stack     at process._tickCallback (internal/process/next_tick.js:180:9)
41 verbose statusCode 500
42 verbose pkgid rfid-hack
43 verbose cwd C:\Users\User\Downloads\rfid-hack
44 verbose Windows_NT 10.0.15063
45 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "publish"
46 verbose node v8.9.4
47 verbose npm  v5.6.0
48 error code E500
49 error Unexpected error (5aa09e99-f92b-40c3-93c8-f535bcfd5ca3). : rfid-hack
50 verbose exit [ 1, true ]
```

**Comment by zkat** [comment]
Send an email to support@npmjs.com about this.
