### ISSUE TITLE
scoped package not being installed/found

### ISSUE THREAD

**Issue by pbalan** [npm/npm#19941]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?
When trying to install a scoped package, I receive the following error:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'install' ]
2 info using npm@5.3.0
3 info using node@v8.9.4
4 verbose npm-session 13addf517d0a8cc2
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall @weflex/studio-web@1.32.1
7 info lifecycle @weflex/studio-web@1.32.1~preinstall: @weflex/studio-web@1.32.1
8 silly install loadCurrentTree
9 silly install readLocalPackageData
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 silly install loadShrinkwrap
13 silly install loadAllDepsIntoIdealTree
14 http fetch GET 404 https://registry.npmjs.org/@weflex%2fhourminute 1583ms
15 silly fetchPackageMetaData error for @weflex/hourminute@^1.3.0 404 Not Found: @weflex/hourminute@^1.3.0
16 http fetch GET 404 https://registry.npmjs.org/@weflex%2fgian 1770ms
17 silly fetchPackageMetaData error for @weflex/gian@^1.37.0 404 Not Found: @weflex/gian@^1.37.0
18 http fetch GET 404 https://registry.npmjs.org/@weflex%2fhourminute 421ms
19 silly fetchPackageMetaData error for @weflex/hourminute@^1.3.0 404 Not Found: @weflex/hourminute@^1.3.0
20 http fetch GET 404 https://registry.npmjs.org/@weflex%2fgian 996ms
21 silly fetchPackageMetaData error for @weflex/gian@^1.37.0 404 Not Found: @weflex/gian@^1.37.0
22 verbose stack Error: 404 Not Found: @weflex/hourminute@^1.3.0
22 verbose stack     at fetch.then.res (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:41:19)
22 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
22 verbose stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
22 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
22 verbose stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
22 verbose stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
22 verbose stack     at Async._drainQueue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
22 verbose stack     at Async._drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
22 verbose stack     at Immediate.Async.drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
22 verbose stack     at runCallback (timers.js:789:20)
22 verbose stack     at tryOnImmediate (timers.js:751:5)
22 verbose stack     at processImmediate [as _immediateCallback] (timers.js:722:5)
23 verbose cwd /Users/pbalan/Sites/weflex/retest/studio-web
24 verbose Darwin 17.4.0
25 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
26 verbose node v8.9.4
27 verbose npm  v5.3.0
28 error code E404
29 error 404 Not Found: @weflex/hourminute@^1.3.0
"~/.npm/_logs/2018-02-28T11_01_08_794Z-debug.log" 43L, 3020C
```
I tried the following:

1. accessing the URL through browser, but I get the following response: [https://registry.npmjs.com/@weflex%2fgian](https://registry.npmjs.com/@weflex%2fgian)
```
{"error":"Not found"}
```
2. tried mirror: [https://skimdb.npmjs.com/registry/@weflex%2fgian](https://skimdb.npmjs.com/registry/@weflex%2fgian)
```
{"error":"not_found","reason":"missing"}
```
3. bumped up versions and republished with 
<img width="759" alt="screen shot 2018-02-28 at 19 16 05" src="https://user-images.githubusercontent.com/3174988/36784865-e7e89b4a-1cbb-11e8-8737-fa2bae3efc2b.png">

> NOTE: This is happening with all our private packages.

4. downgraded npm version from 5.6.0 to 5.3.0
5. tried upgrading node to version 9 and again downgraded to LTS version

#### How can the CLI team reproduce the problem?

Added npm debug log and package.json to [gist](https://gist.github.com/pbalan/fd8b5570171762fd745060546364ee86).

### supporting information:

 - `npm -v` prints: 5.3.0
 - `node -v` prints: v8.9.4
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: OSX/macOS
 - Network issues:
   - Geographic location where npm was run: **Asia/China/Shanghai**
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [x] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
   - [x] Tried without VPN too.
 - Container: **Not Applicable**
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by pbalan** [comment]
Any updates on this? Seems like a private registry issue.
