### ISSUE TITLE
Error: Argument #2: Expected array but got string on npm link (v9.3.0)

### ISSUE THREAD

**Issue by gfmio** [npm/npm#19977]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I tried to link a library I'm building in a sample project using `npm link` producing the following error message:

```
0 info it worked if it ends with ok
1 verbose cli [ '/home/<USER>/.nvm/versions/node/v9.3.0/bin/node',
1 verbose cli   '/home/<USER>/.nvm/versions/node/v9.3.0/bin/npm',
1 verbose cli   'link',
1 verbose cli   '../../libs/core' ]
2 info using npm@5.7.1
3 info using node@v9.3.0
4 verbose npm-session d4e931b77ef1aa05
5 verbose stack Error: Argument #2: Expected array but got string
5 verbose stack     at EventEmitter.install (/home/<USER>/.nvm/versions/node/v9.3.0/lib/node_modules/npm/lib/install.js:187:3)
5 verbose stack     at Object.commandCache.(anonymous function) (/home/<USER>/.nvm/versions/node/v9.3.0/lib/node_modules/npm/lib/npm.js:159:13)
5 verbose stack     at /home/<USER>/.nvm/versions/node/v9.3.0/lib/node_modules/npm/lib/link.js:93:24
5 verbose stack     at /home/<USER>/.nvm/versions/node/v9.3.0/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:284:29
5 verbose stack     at FSReqWrap.oncomplete (fs.js:166:21)
6 verbose cwd <PATH_TO_CWD>
7 verbose Linux 4.15.2-2-ARCH
8 verbose argv "/home/<USER>/.nvm/versions/node/v9.3.0/bin/node" "/home/<USER>/.nvm/versions/node/v9.3.0/bin/npm" "link" "../../libs/core"
9 verbose node v9.3.0
10 verbose npm  v5.7.1
11 error code EINVALIDTYPE
12 error typeerror Error: Argument #2: Expected array but got string
12 error typeerror     at EventEmitter.install (/home/<USER>/.nvm/versions/node/v9.3.0/lib/node_modules/npm/lib/install.js:187:3)
12 error typeerror     at Object.commandCache.(anonymous function) (/home/<USER>/.nvm/versions/node/v9.3.0/lib/node_modules/npm/lib/npm.js:159:13)
12 error typeerror     at /home/<USER>/.nvm/versions/node/v9.3.0/lib/node_modules/npm/lib/link.js:93:24
12 error typeerror     at /home/<USER>/.nvm/versions/node/v9.3.0/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:284:29
12 error typeerror     at FSReqWrap.oncomplete (fs.js:166:21)
13 error typeerror This is an error with npm itself. Please report this error at:
13 error typeerror     <https://github.com/npm/npm/issues>
14 verbose exit [ 1, true ]
```

#### How can the CLI team reproduce the problem?

Run `npm link`. As a side note: The library I tried to link is written in TypeScript and has a `main`, `module` and `types` field in the `package.json`, but I don't think this has anything to do with it.

### supporting information:

 - `npm -v` prints: `5.7.1`
 - `node -v` prints: `v9.3.0`
 - `npm config get registry` prints: `https://registry.npmjs.org/`
 - Windows, OS X/macOS, or Linux?: Linux (ArchLinux)
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by feinimoshu753** [comment]
same issue
try use **npm unlink** your product

**Comment by legodude17** [comment]
Does this occur on the latest version of npm?

**Comment by feinimoshu753** [comment]
no, **npm 5.6.0**

**Comment by legodude17** [comment]
Can you try it with npm 6.0.1?

**Comment by feinimoshu753** [comment]
thanks,I have solved this problem by **npm link**

**Comment by gfmio** [comment]
I'll test and report to back later today

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by tomers** [comment]
[2018-05-29T08_00_59_451Z-debug.log](https://github.com/npm/npm/files/2047271/2018-05-29T08_00_59_451Z-debug.log)

I get the same error when trying to line to an inexistent directory (due to a typo). I would expect some better error message.

```
$ npm link ../vue-form-generator
npm ERR! code EINVALIDTYPE
npm ERR! typeerror Error: Argument #2: Expected array but got string
npm ERR! typeerror     at EventEmitter.install (/usr/local/lib/node_modules/npm/lib/install.js:190:3)
npm ERR! typeerror     at Object.commandCache.(anonymous function) (/usr/local/lib/node_modules/npm/lib/npm.js:159:13)
npm ERR! typeerror     at /usr/local/lib/node_modules/npm/lib/link.js:93:24
npm ERR! typeerror     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:284:29
npm ERR! typeerror     at FSReqWrap.oncomplete (fs.js:170:21)
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/toshalev/.npm/_logs/2018-05-29T08_00_59_451Z-debug.log
```
