### ISSUE TITLE
Npm broken after self-update from 5.6.0 to 5.6.1

### ISSUE THREAD

**Issue by Lambdac0re** [npm/npm#19974]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### How can the CLI team reproduce the problem?

```
PS C:\> npm -v
5.6.0
PS C:\> npm up -g npm
C:\Users\R\AppData\Roaming\npm\npx -> C:\Users\R\AppData\Roaming\npm\node_modules\npm\bin\npx-cli.js
C:\Users\R\AppData\Roaming\npm\npm -> C:\Users\R\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
+ npm@5.7.1
added 63 packages, removed 6 packages and updated 49 packages in 33.105s
PS C:\> npm -v
module.js:538
    throw err;
    ^

Error: Cannot find module 'npmlog'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at C:\Users\R\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js:22:13
    at Object.<anonymous> (C:\Users\R\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js:92:3)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
```

### supporting information:

 - `npm -v` prints: Error
 - `node -v` prints: v8.9.1
 - `npm config get registry` prints: Error
 - Windows, OS X/macOS, or Linux?: Win7
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by metasansana** [comment]
@Lambdac0re did you try `5.7.1`?

**Comment by Lambdac0re** [comment]
Already reinstalled from the nodejs website because I have to work.

**Comment by Lambdac0re** [comment]
Same thing with 5.7.1 → 6.1.0
