### ISSUE TITLE
"Unhandled 'error' event" when running `npm ci` on npm 5.7.1

### ISSUE THREAD

**Issue by bwhitty** [npm/npm#19986]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I'm seeing a weird error emitted to my log when running `npm ci`

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at writeAfterEnd (_stream_writable.js:195:12)
    at PassThrough.Writable.write (_stream_writable.js:242:5)
    at PassThrough.Writable.end (_stream_writable.js:480:10)
    at ReadEntry.entry.on (/usr/lib/node_modules/npm/node_modules/pacote/lib/extract-stream.js:19:41)
    at emitOne (events.js:101:20)
    at ReadEntry.emit (events.js:188:7)
    at ReadEntry.emit (/usr/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:287:25)
    at ReadEntry.[maybeEmitEnd] (/usr/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:240:12)
    at ReadEntry.end (/usr/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:153:27)
    at Unpack.[consumeBody] (/usr/lib/node_modules/npm/node_modules/tar/lib/parse.js:210:13)
    at Unpack.[consumeChunkSub] (/usr/lib/node_modules/npm/node_modules/tar/lib/parse.js:391:40)
    at Unpack.[consumeChunk] (/usr/lib/node_modules/npm/node_modules/tar/lib/parse.js:362:30)
    at Unzip.(anonymous function).on.chunk (/usr/lib/node_modules/npm/node_modules/tar/lib/parse.js:291:59)
    at emitOne (events.js:96:13)
    at Unzip.emit (events.js:188:7)
    at Unzip.emit (/usr/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:287:25)
```

Installation appears to continue to run fine.

#### How can the CLI team reproduce the problem?

There is no NPM debug log for this, as it appears to continue to run just fine.

### supporting information:

 - `npm -v` prints:
```
5.7.1
```
 - `node -v` prints:
```
6.13.0
```
 - `npm config get registry` prints:
```
https://registry.npmjs.org/
```

 - Windows, OS X/macOS, or Linux?:
Alpine Linux
```
uname -m
Linux

ls /etc/*release
/etc/alpine-release  /etc/os-release
```
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [x] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by rosslavery** [comment]
Seeing the same thing using GitLab's CI system when running `npm ci`. Identical stacktrace.

Except my CI build actually fails and does not continue. I can't access the npm debug logs because they are trapped inside the gitlab docker container.

**Comment by deployable** [comment]
This looks similar to npm install in #19989

**Comment by moisadoru** [comment]
I also see this happening with the latest npm (6.1.0). It appears #19989 did not completely fix the isue. `npm ci` is unusable for us for CI builds :crying_cat_face:

**Comment by humphd** [comment]
I'm seeing what I think is potentially the same problem when [building on Travis](https://travis-ci.com/humphd/next/jobs/131015857#L467):

```bash
$ npm ci 
Unhandled rejection Error: stream was destroyed
    at /home/travis/.nvm/versions/node/v10.5.0/lib/node_modules/npm/node_modules/pump/index.js:47:21
    at call (/home/travis/.nvm/versions/node/v10.5.0/lib/node_modules/npm/node_modules/pump/index.js:52:3)
    at Array.forEach (<anonymous>)
    at /home/travis/.nvm/versions/node/v10.5.0/lib/node_modules/npm/node_modules/pump/index.js:74:16
    at f (/home/travis/.nvm/versions/node/v10.5.0/lib/node_modules/npm/node_modules/once/once.js:25:25)
    at PassThrough.<anonymous> (/home/travis/.nvm/versions/node/v10.5.0/lib/node_modules/npm/node_modules/pump/index.js:33:5)
    at PassThrough.f (/home/travis/.nvm/versions/node/v10.5.0/lib/node_modules/npm/node_modules/once/once.js:25:25)
    at PassThrough.onfinish (/home/travis/.nvm/versions/node/v10.5.0/lib/node_modules/npm/node_modules/end-of-stream/index.js:30:27)
    at PassThrough.emit (events.js:187:15)
    at finishMaybe (_stream_writable.js:641:14)
    at endWritable (_stream_writable.js:649:3)
    at PassThrough.Writable.end (_stream_writable.js:589:5)
    at Yallist.pipes.forEach.p (/home/travis/.nvm/versions/node/v10.5.0/lib/node_modules/npm/node_modules/minipass/index.js:290:18)
    at Yallist.forEach (/home/travis/.nvm/versions/node/v10.5.0/lib/node_modules/npm/node_modules/minipass/node_modules/yallist/yallist.js:154:8)
    at Object.emit (/home/travis/.nvm/versions/node/v10.5.0/lib/node_modules/npm/node_modules/minipass/index.js:287:18)
    at Object.[maybeEmitEnd] (/home/travis/.nvm/versions/node/v10.5.0/lib/node_modules/npm/node_modules/minipass/index.js:257:12)
```
