### ISSUE TITLE
npm ERR! tarball.destroy is not a function #13537 on mac os high sierra

### ISSUE THREAD

**Issue by anilgautamm** [npm/npm#20009]
When I am trying to install npm modules ,

COMMAND npm install 
 I am getting following error:
`
npm ERR! code ENAMETOOLONG
npm ERR! errno -63
npm ERR! syscall open

npm ERR! ENAMETOOLONG: name too long, open '/var/folders/f0/ybfmgk6j21b9fdbcc8mqbr040000gn/T/npm-19707-3fe9117d/modernizr.com/download/_3Fapplicationcache-backgroundsize-borderimage-borderradius-boxshadow-cors-cssanimations-csscolumns-cssgradients-cssreflections-cssremunit-cssscrollbar-csstransforms-csstransforms3d-csstransitions-devicemotion_deviceorientation-fileinput-filereader-filesystem-flexbox-flexboxlegacy-fontface-formattribute-formvalidation-fullscreen-generatedcontent-hashchange-history-hsla-ie8compat-input-inputtypes-json-localstorage-multiplebgs-opacity-overflowscrolling-placeholder-postmessage-rgba-sessionstorage-strictmode-textshadow-domprefixes-hasevent-prefixed-prefixedcss-prefixedcssvalue-prefixes-setclasses-shiv-testallprops-testprop-teststyles.1211504487'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/anilgautam/nova/npm-debug.log
`

LOG File 
`
1031 verbose afterAdd /Users/anilgautam/.npm/masonry-layout/4.2.1/package/package.json written
1032 http fetch 200 https://modernizr.com/download/?applicationcache-backgroundsize-borderimage-borderradius-boxshadow-cors-cssanimations-csscolumns-cssgradients-cssreflections-cssremunit-cssscrollbar-csstransforms-csstransforms3d-csstransitions-devicemotion_deviceorientation-fileinput-filereader-filesystem-flexbox-flexboxlegacy-fontface-formattribute-formvalidation-fullscreen-generatedcontent-hashchange-history-hsla-ie8compat-input-inputtypes-json-localstorage-multiplebgs-opacity-overflowscrolling-placeholder-postmessage-rgba-sessionstorage-strictmode-textshadow-domprefixes-hasevent-prefixed-prefixedcss-prefixedcssvalue-prefixes-setclasses-shiv-testallprops-testprop-teststyles
1033 warn retry will retry, error on last attempt: Error: ENAMETOOLONG: name too long, open '/var/folders/f0/ybfmgk6j21b9fdbcc8mqbr040000gn/T/npm-19707-3fe9117d/modernizr.com/download/_3Fapplicationcache-backgroundsize-borderimage-borderradius-boxshadow-cors-cssanimations-csscolumns-cssgradients-cssreflections-cssremunit-cssscrollbar-csstransforms-csstransforms3d-csstransitions-devicemotion_deviceorientation-fileinput-filereader-filesystem-flexbox-flexboxlegacy-fontface-formattribute-formvalidation-fullscreen-generatedcontent-hashchange-history-hsla-ie8compat-input-inputtypes-json-localstorage-multiplebgs-opacity-overflowscrolling-placeholder-postmessage-rgba-sessionstorage-strictmode-textshadow-domprefixes-hasevent-prefixed-prefixedcss-prefixedcssvalue-prefixes-setclasses-shiv-testallprops-testprop-teststyles.2413536204'
1034 verbose stack TypeError: tarball.destroy is not a function
1034 verbose stack     at WriteStreamAtomic.<anonymous> (/Users/anilgautam/.nvm/versions/node/v4.4.0/lib/node_modules/npm/lib/cache/add-remote-tarball.js:85:15)
1034 verbose stack     at emitOne (events.js:82:20)
1034 verbose stack     at WriteStreamAtomic.emit (events.js:169:7)
1034 verbose stack     at WriteStreamAtomic.emit (/Users/anilgautam/.nvm/versions/node/v4.4.0/lib/node_modules/npm/node_modules/fs-write-stream-atomic/index.js:60:34)
1034 verbose stack     at WriteStream.<anonymous> (/Users/anilgautam/.nvm/versions/node/v4.4.0/lib/node_modules/npm/node_modules/fs-write-stream-atomic/index.js:113:17)
1034 verbose stack     at WriteStream.g (events.js:260:16)
1034 verbose stack     at emitOne (events.js:77:13)
1034 verbose stack     at WriteStream.emit (events.js:169:7)
1034 verbose stack     at /Users/anilgautam/.nvm/versions/node/v4.4.0/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:202:14
1034 verbose stack     at /Users/anilgautam/.nvm/versions/node/v4.4.0/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:232:16
1035 verbose cwd /Users/anilgautam/nova
1036 error Darwin 17.4.0
1037 error argv "/Users/anilgautam/.nvm/versions/node/v4.4.0/bin/node" "/Users/anilgautam/.nvm/versions/node/v4.4.0/bin/npm" "-g" "install"
1038 error node v4.4.0
1039 error npm  v2.14.20
1040 error tarball.destroy is not a function
1041 error If you need help, you may report this error at:
1041 error     <https://github.com/npm/npm/issues>
1042 verbose exit [ 1, true ]`

**Comment by circa10a** [comment]
@anilgautamm Can you provide a link to your repo or post your package.json as well as the output of the following commands on your mac:
 - `node v && npm -v`
 - `system_profiler SPSoftwareDataType`

**Comment by kenany** [comment]
From the log:

```
node v4.4.0 1039 error npm v2.14.20
```

Does this also occur with newer versions of `npm`?

**Comment by anilgautamm** [comment]
Yes, I am using mac os high sierra OS
ERROR: npm is known not to run on Node.js v4.4.0
Node.js 4 is supported but the specific version you're running has
a bug known to break npm. Please update to at least 4.7.0 to use this
version of npm. You can find the latest release of Node.js at
https://nodejs.org/
nvm is not compatible with the npm config "prefix" option: currently set to
""
Run `npm config delete prefix` or `nvm use --delete-prefix v4.4.0 --silent`
to unset it.

Now I am getting this error.

*Regards:*
*Anil Gautam*
*Founder*
<http://techmarbles.com>
techmarbles.com

**Comment by altanai** [comment]
Still getting the tarball.destroy error on installation of almost any npm . Tried purging and installing node, nodejs, nvm and npm yet nothing seems to be fixing this . Any other approaches ?

**Comment by anilgautamm** [comment]
@altanai  

Finally, I get everything to be working. Try these steps
1) try nvm ls to see all the installed node versions 
2) then make the latest version usable using nvm use VERSION number
3) If you do not have all the versions installed Try   nvm ls-remote                             List remote versions available for install
  nvm alias default 0.10.32             Set default node version on a shell
