### ISSUE TITLE
Can't install new frameworks -command not found

### ISSUE THREAD

**Issue by Vanals** [npm/npm#20010]
#### I'm opening this issue because:
  -[] After installing new framework as Angular or Vue (npm install --global vue-cli) when I try to create a new project I get the error "zsh: command not found: vue" 

#### What's going wrong?
Yestarday for the first time I was installing Angular  running "npm install -g @ angular/cli" (without space after @)
In my laptop I had always to use sudo for general installation and with sudo the angular installation didn't work. Then i changed the permissions following the point 2 on this guide https://docs.npmjs.com/getting-started/fixing-npm-permissions.

After that the Installation went through, and I started playing with Angular. This morning, I don't know why, when trying to launch the project "ng serve --open" I got the message "zsh: command not found: ng".

After some research I haven't been able to fix the isssue, so I decide to play with VUE  but now I get this error when trying to install vue
```
➜  desktop npm install --global vue-cli
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
events.js:183░░░░░░⸩ ⠼ extract:thunkify-wrap: sill extract esprima@4.0.0
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at writeAfterEnd (_stream_writable.js:236:12)
    at PassThrough.Writable.write (_stream_writable.js:287:5)
    at PassThrough.Writable.end (_stream_writable.js:553:10)
    at ReadEntry.entry.on (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/extract-stream.js:19:41)
    at emitOne (events.js:121:20)
    at ReadEntry.emit (events.js:211:7)
    at ReadEntry.emit (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:287:25)
    at ReadEntry.[maybeEmitEnd] (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:240:12)
    at ReadEntry.end (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:153:27)
    at Unpack.[consumeBody] (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:210:13)
    at Unpack.[consumeChunkSub] (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:391:40)
    at Unpack.[consumeChunk] (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:362:30)
    at Unzip.(anonymous function).on.chunk (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:291:59)
    at emitOne (events.js:116:13)
    at Unzip.emit (events.js:211:7)
    at Unzip.emit (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:287:25)
/Users/marcovanali/.npm-global/bin/vue -> /Users/marcovanali/.npm-global/lib/node_modules/vue-cli/bin/vue
/Users/marcovanali/.npm-global/bin/vue-init -> /Users/marcovanali/.npm-global/lib/node_modules/vue-cli/bin/vue-init
/Users/marcovanali/.npm-global/bin/vue-list -> /Users/marcovanali/.npm-global/lib/node_modules/vue-cli/bin/vue-list
+ vue-cli@2.9.3
added 253 packages from 219 contributors in 10.781s
➜  desktop vue init webpack my-project
zsh: command not found: vue
```
So I suppose is an NPM issue.

### supporting information:

 - `npm -v` prints: 5.7.1
 - `node -v` prints: 8.9.4
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: MAC OS

**Comment by deployable** [comment]
This also looks like #19989
