### ISSUE TITLE
Can't publish new package version: New package version must have dist with {shasum, tarball}

### ISSUE THREAD

**Issue by lukasoppermann** [npm/npm#20011]
#### I'm opening this issue because: 
I can not publish new versions for my package

#### What's going wrong?
I get an error when trying to publish a new version of my package to npm.

When running `npm publish`:
> NPM Can't Publish E400 New package version must have dist with {shasum, tarball}

This file does not exist, but is referenced in the logs:
```
/var/folders/b1/qwvr4ldn1_375rkwn7yhyk4m0000gn/T/npm-6060-1b2f34a9/tmp/fromDir-157455b2/package.tgz
```

Error Log:
<details>

```
    0 info it worked if it ends with ok
    1 verbose cli [ '/usr/local/Cellar/node/9.8.0/bin/node',
    1 verbose cli   '/usr/local/bin/npm',
    1 verbose cli   'publish' ]
    2 info using npm@5.6.0
    3 info using node@v9.8.0
    4 verbose npm-session 009a09b3734b2310
    5 verbose publish [ '.' ]
    6 info lifecycle html5sortable@0.8.0~prepublish: html5sortable@0.8.0
    7 info lifecycle html5sortable@0.8.0~prepare: html5sortable@0.8.0
    8 info lifecycle html5sortable@0.8.0~prepublishOnly: html5sortable@0.8.0
    9 info lifecycle html5sortable@0.8.0~prepack: html5sortable@0.8.0
    10 info lifecycle html5sortable@0.8.0~postpack: html5sortable@0.8.0
    11 verbose getPublishConfig undefined
    12 silly mapToRegistry name html5sortable
    13 silly mapToRegistry using default registry
    14 silly mapToRegistry registry https://registry.npmjs.org/
    15 silly mapToRegistry data { type: 'tag',
    15 silly mapToRegistry   registry: true,
    15 silly mapToRegistry   where: undefined,
    15 silly mapToRegistry   raw: 'html5sortable',
    15 silly mapToRegistry   name: 'html5sortable',
    15 silly mapToRegistry   escapedName: 'html5sortable',
    15 silly mapToRegistry   scope: undefined,
    15 silly mapToRegistry   rawSpec: '',
    15 silly mapToRegistry   saveSpec: null,
    15 silly mapToRegistry   fetchSpec: 'latest',
    15 silly mapToRegistry   gitRange: undefined,
    15 silly mapToRegistry   gitCommittish: undefined,
    15 silly mapToRegistry   hosted: undefined }
    16 silly mapToRegistry uri https://registry.npmjs.org/html5sortable
    17 verbose publish registryBase https://registry.npmjs.org/
    18 silly publish uploading /var/folders/b1/qwvr4ldn1_375rkwn7yhyk4m0000gn/T/npm-6060-1b2f34a9/tmp/fromDir-157455b2/package.tgz
    19 verbose request uri https://registry.npmjs.org/html5sortable
    20 verbose request sending authorization for write operation
    21 info attempt registry request try #1 at 1:09:12 PM
    22 verbose request using bearer token for auth
    23 verbose request id gda9f5bf7619f2e
    24 http request PUT https://registry.npmjs.org/html5sortable
    25 http 400 https://registry.npmjs.org/html5sortable
    26 verbose headers { 'content-type': 'application/json',
    26 verbose headers   'cache-control': 'max-age=300',
    26 verbose headers   'content-length': '86',
    26 verbose headers   'accept-ranges': 'bytes',
    26 verbose headers   date: 'Sat, 10 Mar 2018 12:09:12 GMT',
    26 verbose headers   via: '1.1 varnish',
    26 verbose headers   connection: 'keep-alive',
    26 verbose headers   'x-served-by': 'cache-hhn1520-HHN',
    26 verbose headers   'x-cache': 'MISS',
    26 verbose headers   'x-cache-hits': '0',
    26 verbose headers   'x-timer': 'S1520683750.327475,VS0,VE1855',
    26 verbose headers   vary: 'Accept-Encoding, Accept' }
    27 error publish Failed PUT 400
    28 verbose stack Error: New package version must have dist with {shasum, tarball}. : html5sortable
    28 verbose stack     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:314:12)
    28 verbose stack     at RegClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:302:14)
    28 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:216:14)
    28 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:186:22)
    28 verbose stack     at Request.emit (events.js:180:13)
    28 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1163:10)
    28 verbose stack     at Request.emit (events.js:180:13)
    28 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1085:12)
    28 verbose stack     at Object.onceWrapper (events.js:272:13)
    28 verbose stack     at IncomingMessage.emit (events.js:185:15)
    28 verbose stack     at endReadableNT (_stream_readable.js:1101:12)
    28 verbose stack     at process._tickCallback (internal/process/next_tick.js:114:19)
    29 verbose statusCode 400
    30 verbose pkgid html5sortable
    31 verbose cwd /Users/lukasoppermann/Code/html5sortable
    32 verbose Darwin 16.7.0
    33 verbose argv "/usr/local/Cellar/node/9.8.0/bin/node" "/usr/local/bin/npm" "publish"
    34 verbose node v9.8.0
    35 verbose npm  v5.6.0
    36 error code E400
    37 error New package version must have dist with {shasum, tarball}. : html5sortable
    38 verbose exit [ 1, true ]
```
</details>

#### How can the CLI team reproduce the problem?
1. I did `npm version minor` on another mac this was pushed to github (but I forgot to do `npm publish`). I have never done `npm login` on this mac or published to the package before.
2. I ran `npm publish` from my other mac from her I had done `npm login` before and also published to the package.
3. The error occured.

##### I tried:
1. Delete the tag and the commit
2. Run `npm version minor` and `npm publish` from the mac where I published before
3. Same error

I had `package-lock.json` in in `.gitignore` and `package-lock=false` in `.npmrc` so I removed that and tried the above again with the same error.

I tried a patch (I am trying to publish 0.8.0 so I tried 0.8.1) same error.

Thanks.

### supporting information:

 - `npm -v` prints: 5.7.1
 - `node -v` prints: v9.8.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: OS X 10.12.6 (16G1212)
 - Network issues:
   - Geographic location where npm was run: Berlin, Germany, good internet
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by lukasoppermann** [comment]
FYI: I tried on the Mac I did the npm version minor on, but I get the same error. I have also tried downgrading to 5.6 but same result.

**Comment by zkat** [comment]
update: user had a `dist` field in their `package.json` which was messing with the publish process. Closing this. :)

**Comment by lukasoppermann** [comment]
It is solved thanks to @zkat perfect diagnosis. I stupidly (not know this was a problem), had added a dist field to to the package.json
