### ISSUE TITLE
sudo npm install ERROR

### ISSUE THREAD

**Issue by bhumin3i** [npm/npm#20038]
rtidev Directory have full access
> ls 
OUTPUT
`drwxr-xr-x+ 18 bhumin  staff   612 Mar 13 15:33 rtidev`

> sudo npm install
OUTPUT
```
Password:
npm WARN saveError ENOENT: no such file or directory, open '/Users/bhumin/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/bhumin/package.json'
npm WARN bhumin No description
npm WARN bhumin No repository field.
npm WARN bhumin No README data
npm WARN bhumin No license field.

added 1 package from 1 contributor in 9.175s
Bhumins-Mac-mini:gitREPO bhumin$ sudo npm uninstall
npm ERR! npm uninstall [<@scope>/]<pkg>[@<version>]... [--save-prod|--save-dev|--save-optional] [--no-save]
npm ERR! 
npm ERR! aliases: un, unlink, remove, rm, r
Bhumins-Mac-mini:gitREPO bhumin$ sudo npm rm
npm ERR! npm uninstall [<@scope>/]<pkg>[@<version>]... [--save-prod|--save-dev|--save-optional] [--no-save]
npm ERR! 
npm ERR! aliases: un, unlink, remove, rm, r
Bhumins-Mac-mini:gitREPO bhumin$ sudo npm rm uninstall
npm WARN saveError ENOENT: no such file or directory, open '/Users/bhumin/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/bhumin/package.json'
npm WARN bhumin No description
npm WARN bhumin No repository field.
npm WARN bhumin No README data
npm WARN bhumin No license field.

up to date in 3.463s
Bhumins-Mac-mini:gitREPO bhumin$ cd rtidev/
Bhumins-Mac-mini:rtidev bhumin$ sudo npm install

> node-sass@4.7.2 install /Users/bhumin/Desktop/gitREPO/rtidev/node_modules/node-sass
> node scripts/install.js

Unable to save binary /Users/bhumin/Desktop/gitREPO/rtidev/node_modules/node-sass/vendor/darwin-x64-57 : { Error: EACCES: permission denied, mkdir '/Users/bhumin/Desktop/gitREPO/rtidev/node_modules/node-sass/vendor'
    at Object.fs.mkdirSync (fs.js:885:18)
    at sync (/Users/bhumin/Desktop/gitREPO/rtidev/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/Users/bhumin/Desktop/gitREPO/rtidev/node_modules/mkdirp/index.js:77:24)
    at checkAndDownloadBinary (/Users/bhumin/Desktop/gitREPO/rtidev/node_modules/node-sass/scripts/install.js:111:11)
    at Object.<anonymous> (/Users/bhumin/Desktop/gitREPO/rtidev/node_modules/node-sass/scripts/install.js:154:1)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/Users/bhumin/Desktop/gitREPO/rtidev/node_modules/node-sass/vendor' }

> node-sass@4.7.2 postinstall /Users/bhumin/Desktop/gitREPO/rtidev/node_modules/node-sass
> node scripts/build.js

Building: /usr/local/bin/node /Users/bhumin/Desktop/gitREPO/rtidev/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/bin/node',
gyp verb cli   '/Users/bhumin/Desktop/gitREPO/rtidev/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@8.9.4 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/Users/bhumin/Desktop/gitREPO/rtidev/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/Users/bhumin/Desktop/gitREPO/rtidev/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/Users/bhumin/Desktop/gitREPO/rtidev/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /Users/bhumin/Desktop/gitREPO/rtidev/node_modules/which/which.js:89:16
gyp verb `which` failed     at /Users/bhumin/Desktop/gitREPO/rtidev/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /Users/bhumin/Desktop/gitREPO/rtidev/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/Users/bhumin/Desktop/gitREPO/rtidev/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/Users/bhumin/Desktop/gitREPO/rtidev/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/Users/bhumin/Desktop/gitREPO/rtidev/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /Users/bhumin/Desktop/gitREPO/rtidev/node_modules/which/which.js:89:16
gyp verb `which` failed     at /Users/bhumin/Desktop/gitREPO/rtidev/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /Users/bhumin/Desktop/gitREPO/rtidev/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError (/Users/bhumin/Desktop/gitREPO/rtidev/node_modules/which/which.js:13:12)\n    at F (/Users/bhumin/Desktop/gitREPO/rtidev/node_modules/which/which.js:68:19)\n    at E (/Users/bhumin/Desktop/gitREPO/rtidev/node_modules/which/which.js:80:29)\n    at /Users/bhumin/Desktop/gitREPO/rtidev/node_modules/which/which.js:89:16\n    at /Users/bhumin/Desktop/gitREPO/rtidev/node_modules/isexe/index.js:42:5\n    at /Users/bhumin/Desktop/gitREPO/rtidev/node_modules/isexe/mode.js:8:5\n    at FSReqWrap.oncomplete (fs.js:152:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python /usr/bin/python
gyp verb check python version `/usr/bin/python -c "import platform; print(platform.python_version());"` returned: "2.7.10\n"
gyp verb get node dir no --target version specified, falling back to host node version: 8.9.4
gyp verb command install [ '8.9.4' ]
gyp verb install input version string "8.9.4"
gyp verb install installing version: 8.9.4
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 8.9.4
gyp verb build dir attempting to create "build" dir: /Users/bhumin/Desktop/gitREPO/rtidev/node_modules/node-sass/build
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/Users/bhumin/Desktop/gitREPO/rtidev/node_modules/node-sass/build'
gyp ERR! System Darwin 17.4.0
gyp ERR! command "/usr/local/bin/node" "/Users/bhumin/Desktop/gitREPO/rtidev/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/bhumin/Desktop/gitREPO/rtidev/node_modules/node-sass
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
Build failed with error code: 1
npm WARN @angular/animations@5.2.7 requires a peer of @angular/core@5.2.7 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.7.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.7.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/bhumin/.npm/_logs/2018-03-13T10_11_38_708Z-debug.log
```

**Comment by bhumin3i** [comment]
sorry solve using install **python**
