### ISSUE TITLE
When I use npm install command it give me this error  npm ERR! code EINVALIDTYPE npm ERR! typeerror Error: Argument #5: Expected object but got string

### ISSUE THREAD

**Issue by ankits47b** [npm/npm#20035]
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@0. I'll try to do my best with it!
npm ERR! code EINVALIDTYPE
npm ERR! typeerror Error: Argument #5: Expected object but got string
npm ERR! typeerror     at inflatableChild (/usr/local/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:70:3)
npm ERR! typeerror     at BB.each (/usr/local/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:52:12)
npm ERR! typeerror     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
npm ERR! typeerror     at Object.gotValue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/reduce.js:155:18)
npm ERR! typeerror     at Object.gotAccum (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/reduce.js:144:25)
npm ERR! typeerror     at Object.tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
npm ERR! typeerror     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
npm ERR! typeerror     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
npm ERR! typeerror     at Promise._settlePromiseCtx (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:606:10)
npm ERR! typeerror     at Async._drainQueue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:138:12)
npm ERR! typeerror     at Async._drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
npm ERR! typeerror     at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
npm ERR! typeerror     at runCallback (timers.js:757:18)
npm ERR! typeerror     at tryOnImmediate (timers.js:718:5)
npm ERR! typeerror     at processImmediate [as _immediateCallback] (timers.js:698:5)
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <https://github.com/npm/npm/issues>

**Comment by ankits47b** [comment]
Solve my issue actually my package-lock.json has been changed by mistake and its code is misplaced.. so I paste this file from my backup and build it again it works...
