### ISSUE TITLE
npm run dev

### ISSUE THREAD

**Issue by PankajJenisha** [npm/npm#20039]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@5.6.0
3 info using node@v8.9.4
4 verbose stack Error: missing script: dev
4 verbose stack     at run (C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:151:19)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:61:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:115:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:402:5
4 verbose stack     at checkBinReferences_ (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:357:45)
4 verbose stack     at final (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:400:3)
4 verbose stack     at then (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:160:5)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:280:12
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
5 verbose cwd C:\Users\admin\Downloads\eth-lightwallet-master\eth-lightwallet-master
6 verbose Windows_NT 6.1.7601
7 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
8 verbose node v8.9.4
9 verbose npm  v5.6.0
10 error missing script: dev
11 verbose exit [ 1, true ]

**Comment by PankajJenisha** [comment]
Please let me know about this issue i just run my application using npm run dev on cmd prompt and i am getting this issue.

**Comment by kenany** [comment]
```
4 verbose stack Error: missing script: dev
```

Do you have a `"dev"` script defined in your `package.json`?

**Comment by angelmy** [comment]
hello  i met the same problem ,and i don't have a "dev" script in my package.json ,how to create this ?  thanks

**Comment by kenany** [comment]
@angelmy Here is an example `package.json` which contains a `"dev"` script:

```json
{
  "scripts": {
    "dev": "whatever command you want goes here"
  }
}
```

**Comment by angelmy** [comment]
@KenanY   i want to run my vue project on browser,and it told me missing dev ,how to do ?
