### ISSUE TITLE
403 Forbidden 

### ISSUE THREAD

**Issue by camicamcam** [npm/npm#20030]
#### I'm opening this issue because:

  - [ x] npm is crashing.
  - [x ] npm is producing an incorrect install.
  - [x ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Doing an `npm install @sinonjs/formatio@2.0.0 --verbose` in an empty folder produces 
```
npm info it worked if it ends with ok
npm verb cli [ '/Users/cmarini/.nvm/versions/node/v6.13.1/bin/node',
npm verb cli   '/Users/cmarini/.nvm/versions/node/v6.13.1/bin/npm',
npm verb cli   'install',
npm verb cli   '@sinonjs/formatio@2.0.0',
npm verb cli   '--verbose' ]
npm info using npm@5.7.1
npm info using node@v6.13.1
npm verb config Skipping project config: /Users/cmarini/.npmrc. (matches userconfig)
npm verb npm-session aed47cfb123b9b27
npm http fetch GET 403 http://npm.rmn.io/@sinonjs%2fformatio 362ms
npm verb stack Error: 403 Forbidden: @sinonjs/formatio@2.0.0
npm verb stack     at fetch.then.res (/Users/cmarini/.nvm/versions/node/v6.13.1/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:42:19)
npm verb stack     at tryCatcher (/Users/cmarini/.nvm/versions/node/v6.13.1/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
npm verb stack     at Promise._settlePromiseFromHandler (/Users/cmarini/.nvm/versions/node/v6.13.1/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
npm verb stack     at Promise._settlePromise (/Users/cmarini/.nvm/versions/node/v6.13.1/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
npm verb stack     at Promise._settlePromise0 (/Users/cmarini/.nvm/versions/node/v6.13.1/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
npm verb stack     at Promise._settlePromises (/Users/cmarini/.nvm/versions/node/v6.13.1/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
npm verb stack     at Async._drainQueue (/Users/cmarini/.nvm/versions/node/v6.13.1/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
npm verb stack     at Async._drainQueues (/Users/cmarini/.nvm/versions/node/v6.13.1/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
npm verb stack     at Immediate.Async.drainQueues (/Users/cmarini/.nvm/versions/node/v6.13.1/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
npm verb stack     at runCallback (timers.js:672:20)
npm verb stack     at tryOnImmediate (timers.js:645:5)
npm verb stack     at processImmediate [as _immediateCallback] (timers.js:617:5)
npm verb cwd /Users/cmarini/Projects/test
npm verb Darwin 17.4.0
npm verb argv "/Users/cmarini/.nvm/versions/node/v6.13.1/bin/node" "/Users/cmarini/.nvm/versions/node/v6.13.1/bin/npm" "install" "@sinonjs/formatio@2.0.0" "--verbose"
npm verb node v6.13.1
npm verb npm  v5.7.1
npm ERR! code E403
npm ERR! 403 Forbidden: @sinonjs/formatio@2.0.0
npm verb exit [ 1, true ]

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/cmarini/.npm/_logs/2018-03-12T21_49_41_401Z-debug.log
```

I've tried this with npm 5.6.0 and 5.7.1 with the same result. I've also attempted `npm cache clear -f` and retried an npm install with the same error. 

#### How can the CLI team reproduce the problem?
1. `mkdir test`
1. `cd test`
1. `npm install @sinonjs/formatio@2.0.0 --verbose`

### supporting information:

 - `npm -v` prints:5.7.1
 - `node -v` prints: v6.13.1
 - `npm config get registry` prints: http://npm.rmn.io/
 - Windows, OS X/macOS, or Linux?: macOS 10.13.3
 - Network issues:
   - Geographic location where npm was run: Austin, Texas 
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ x] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by camicamcam** [comment]
Found a solution by removing `registry=http://npm.rmn.io/` from `~/.npmrc`
