### ISSUE TITLE
`npm publish` succeeded but recent version seems to be missing in the registry 😞

### ISSUE THREAD

**Issue by michael-ciniawsky** [npm/npm#20077]
#### I'm opening this issue because:

  - [x] npm is doing something I don't understand.

#### What's going wrong?

`npm publish` 'succeeded' locally, but the recent 'published' version is missing in the registry 😭 

I waited a few minutes and tried `npm publish` again giving me the 'correct'  `ERROR`

<details>

```
npm ERR! publish Failed PUT 403
npm ERR! code E403
npm ERR! You cannot publish over the previously published versions: 1.2.4. : uglifyjs-webpack-plugin

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Cini/.npm/_logs/2018-03-16T12_16_17_704Z-debug.log
```

</details>

<br>

But `v1.2.4`  doesn't seemed to have been published and `npm i -S uglifyjs-webpack-plugin` is still `@1.2.3`

#### `$USER/.npm/_logs`

<details>

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'publish' ]
2 info using npm@5.7.1
3 info using node@v9.8.0
4 verbose npm-session 1b1c970f4418e0b8
5 verbose publish [ '.' ]
6 info lifecycle uglifyjs-webpack-plugin@1.2.4~prepublish: uglifyjs-webpack-plugin@1.2.4
7 info lifecycle uglifyjs-webpack-plugin@1.2.4~prepare: uglifyjs-webpack-plugin@1.2.4
8 verbose lifecycle uglifyjs-webpack-plugin@1.2.4~prepare: unsafe-perm in lifecycle true
9 verbose lifecycle uglifyjs-webpack-plugin@1.2.4~prepare: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/Cini/Github/Webpack/plugins/uglifyjs-webpack-plugin/node_modules/.bin:/usr/local/opt/php71/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
10 verbose lifecycle uglifyjs-webpack-plugin@1.2.4~prepare: CWD: .
11 silly lifecycle uglifyjs-webpack-plugin@1.2.4~prepare: Args: [ '-c', 'npm run build' ]
12 silly lifecycle uglifyjs-webpack-plugin@1.2.4~prepare: Returned: code: 0  signal: null
13 info lifecycle uglifyjs-webpack-plugin@1.2.4~prepublishOnly: uglifyjs-webpack-plugin@1.2.4
14 info lifecycle uglifyjs-webpack-plugin@1.2.4~prepack: uglifyjs-webpack-plugin@1.2.4
15 info lifecycle uglifyjs-webpack-plugin@1.2.4~postpack: uglifyjs-webpack-plugin@1.2.4
16 verbose getPublishConfig undefined
17 silly mapToRegistry name uglifyjs-webpack-plugin
18 silly mapToRegistry using default registry
19 silly mapToRegistry registry https://registry.npmjs.org/
20 silly mapToRegistry data { type: 'tag',
20 silly mapToRegistry   registry: true,
20 silly mapToRegistry   where: undefined,
20 silly mapToRegistry   raw: 'uglifyjs-webpack-plugin',
20 silly mapToRegistry   name: 'uglifyjs-webpack-plugin',
20 silly mapToRegistry   escapedName: 'uglifyjs-webpack-plugin',
20 silly mapToRegistry   scope: undefined,
20 silly mapToRegistry   rawSpec: '',
20 silly mapToRegistry   saveSpec: null,
20 silly mapToRegistry   fetchSpec: 'latest',
20 silly mapToRegistry   gitRange: undefined,
20 silly mapToRegistry   gitCommittish: undefined,
20 silly mapToRegistry   hosted: undefined }
21 silly mapToRegistry uri https://registry.npmjs.org/uglifyjs-webpack-plugin
22 verbose publish registryBase https://registry.npmjs.org/
23 silly publish uploading /var/folders/4y/226nb89100bgsbkxbcbpft5m0000gn/T/npm-56789-dc2cb879/tmp/fromDir-a73e62c7/package.tgz
24 verbose request uri https://registry.npmjs.org/uglifyjs-webpack-plugin
25 verbose request sending authorization for write operation
26 info attempt registry request try #1 at 13:00:10
27 verbose request using bearer token for auth
28 verbose request id ab785a6f9e9c4efe
29 http request PUT https://registry.npmjs.org/uglifyjs-webpack-plugin
30 http 403 https://registry.npmjs.org/uglifyjs-webpack-plugin
31 verbose headers { 'content-type': 'application/json',
31 verbose headers   'cache-control': 'max-age=300',
31 verbose headers   'content-length': '93',
31 verbose headers   'accept-ranges': 'bytes',
31 verbose headers   date: 'Fri, 16 Mar 2018 12:00:11 GMT',
31 verbose headers   via: '1.1 varnish',
31 verbose headers   connection: 'keep-alive',
31 verbose headers   'x-served-by': 'cache-hhn1525-HHN',
31 verbose headers   'x-cache': 'MISS',
31 verbose headers   'x-cache-hits': '0',
31 verbose headers   'x-timer': 'S1521201611.571318,VS0,VE917',
31 verbose headers   vary: 'Accept-Encoding, Accept' }
32 error publish Failed PUT 403
33 verbose stack Error: You cannot publish over the previously published versions: 1.2.4. : uglifyjs-webpack-plugin
33 verbose stack     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:314:12)
33 verbose stack     at RegClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:302:14)
33 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:216:14)
33 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:186:22)
33 verbose stack     at Request.emit (events.js:180:13)
33 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1163:10)
33 verbose stack     at Request.emit (events.js:180:13)
33 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1085:12)
33 verbose stack     at Object.onceWrapper (events.js:272:13)
33 verbose stack     at IncomingMessage.emit (events.js:185:15)
33 verbose stack     at endReadableNT (_stream_readable.js:1101:12)
33 verbose stack     at process._tickCallback (internal/process/next_tick.js:114:19)
34 verbose statusCode 403
35 verbose pkgid uglifyjs-webpack-plugin
36 verbose cwd /Users/Cini/Github/Webpack/plugins/uglifyjs-webpack-plugin
37 verbose Darwin 16.7.0
38 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "publish"
39 verbose node v9.8.0
40 verbose npm  v5.7.1
41 error code E403
42 error You cannot publish over the previously published versions: 1.2.4. : uglifyjs-webpack-plugin
43 verbose exit [ 1, true ]
```

</details>

#### How can the CLI team reproduce the problem?

**package.json**

<details>

```
{
  "name": "uglifyjs-webpack-plugin",
  "version": "1.2.4",
  "description": "UglifyJS plugin for webpack",
  "author": "webpack Contrib Team",
  "license": "MIT",
  "engines": {
    "node": ">= 4.8 < 5.0.0 || >= 5.10"
  },
  "main": "dist/cjs.js",
  "files": [
    "dist"
  ],
  "scripts": {
    "start": "npm run build -- -w",
    "build": "cross-env NODE_ENV=production babel src -d dist --ignore 'src/**/*.test.js' --copy-files",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:coverage": "jest --collectCoverageFrom='src/**/*.js' --coverage",
    "prebuild": "npm run clean",
    "clean": "del-cli dist",
    "lint": "eslint --cache src test",
    "lint-staged": "lint-staged",
    "prepare": "npm run build",
    "release": "standard-version",
    "security": "nsp check",
    "travis:lint": "npm run lint && npm run security",
    "travis:test": "npm run test -- --runInBand",
    "travis:coverage": "npm run test:coverage -- --runInBand",
    "appveyor:test": "npm run test",
    "webpack-defaults": "webpack-defaults"
  },
```

</details>

<br>

**`npm view uglifyjs-webpack-plugin`**

<br>

<details>

```
{ name: 'uglifyjs-webpack-plugin',
  description: 'UglifyJS plugin for webpack',
  'dist-tags': { latest: '1.2.3', beta: '1.0.0-rc.0' },
  versions:
   [ '0.1.0',
     '0.1.1',
     '0.1.2',
     '0.1.3',
     '0.1.4',
     '0.1.5',
     '0.2.0',
     '0.2.1',
     '0.2.2',
     '0.3.0',
     '0.3.1',
     '0.4.0',
     '0.4.1',
     '0.4.2',
     '0.4.3',
     '0.4.4',
     '0.4.5',
     '0.4.6',
     '1.0.0-beta.0',
     '1.0.0-beta.1',
     '1.0.0-beta.2',
     '1.0.0-beta.3',
     '1.0.0-rc.0',
     '1.0.0',
     '1.0.1',
     '1.1.0',
     '1.1.1',
     '1.1.2',
     '1.1.3',
     '1.1.4',
     '1.1.5',
     '1.1.6',
     '1.1.7',
     '1.1.8',
     '1.2.0',
     '1.2.1',
     '1.2.2',
     '1.2.3' ],
  maintainers:
   [ 'bebraw <bebraw@gmail.com>',
     'd3viant0ne <wiens.joshua@gmail.com>',
     'michael-ciniawsky <michael.ciniawsky@gmail.com>',
     'sokra <tobias.koppers@googlemail.com>',
     'thelarkinn <sean.larkin@cuw.edu>' ],
  time:
   { modified: '2018-03-13T19:30:52.846Z',
     created: '2017-01-24T09:00:10.767Z',
     '0.1.0': '2017-01-24T09:00:10.767Z',
     '0.1.1': '2017-01-25T09:52:06.005Z',
     '0.1.2': '2017-01-25T12:58:32.369Z',
     '0.1.3': '2017-02-02T20:00:46.975Z',
     '0.1.4': '2017-02-06T06:52:08.933Z',
     '0.1.5': '2017-02-15T15:56:51.952Z',
     '0.2.0': '2017-02-19T13:11:27.566Z',
     '0.2.1': '2017-02-20T06:13:44.311Z',
     '0.2.2': '2017-03-02T15:17:03.605Z',
     '0.3.0': '2017-03-04T05:08:54.882Z',
     '0.3.1': '2017-03-22T12:25:04.431Z',
     '0.4.0': '2017-03-30T13:42:05.050Z',
     '0.4.1': '2017-04-05T09:31:56.739Z',
     '0.4.2': '2017-04-12T17:20:08.132Z',
     '0.4.3': '2017-04-15T19:21:22.731Z',
     '0.4.4': '2017-06-18T18:14:43.567Z',
     '0.4.5': '2017-06-19T21:43:37.511Z',
     '0.4.6': '2017-06-19T21:51:37.721Z',
     '1.0.0-beta.0': '2017-06-29T19:37:39.804Z',
     '1.0.0-beta.1': '2017-07-06T03:04:38.639Z',
     '1.0.0-beta.2': '2017-07-21T20:05:04.481Z',
     '1.0.0-beta.3': '2017-10-10T03:24:44.584Z',
     '1.0.0-rc.0': '2017-10-23T00:05:03.415Z',
     '1.0.0': '2017-10-23T20:07:04.454Z',
     '1.0.1': '2017-10-24T02:38:17.765Z',
     '1.1.0': '2017-11-19T03:23:29.230Z',
     '1.1.1': '2017-11-23T19:29:19.020Z',
     '1.1.2': '2017-11-30T13:22:09.327Z',
     '1.1.3': '2017-12-14T02:52:42.767Z',
     '1.1.4': '2017-12-14T11:33:28.963Z',
     '1.1.5': '2017-12-27T10:32:08.419Z',
     '1.1.6': '2018-01-05T06:49:09.390Z',
     '1.1.7': '2018-01-29T18:44:59.134Z',
     '1.1.8': '2018-01-29T20:45:55.833Z',
     '1.2.0': '2018-02-16T22:29:32.822Z',
     '1.2.1': '2018-02-23T19:04:32.919Z',
     '1.2.2': '2018-02-24T01:27:16.889Z',
     '1.2.3': '2018-03-10T22:41:18.595Z' },
  homepage: 'https://github.com/webpack-contrib/uglifyjs-webpack-plugin',
  keywords: [ 'uglify', 'uglify-js', 'uglify-es', 'webpack', 'webpack-plugin' ],
  repository:
   { type: 'git',
     url: 'git+https://github.com/webpack-contrib/uglifyjs-webpack-plugin.git' },
  bugs:
   { url: 'https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues' },
  license: 'MIT',
  readmeFilename: 'README.md',
  users:
   { alimaster: true,
     denji: true,
     shoonia: true,
     'serge-nikitin': true,
     sunzhixun: true,
     yeming: true,
     ibio: true,
     luffy84217: true,
     akabeko: true,
     mskjp: true,
     jger: true,
     dengyongchao: true,
     akicho8: true,
     nickgogan: true,
     adamduehansen: true,
     ycjcl868: true,
     tcrowe: true },
  author: 'webpack Contrib Team',
  version: '1.2.3',
  engines: { node: '>= 4.8 < 5.0.0 || >= 5.10' },
  main: 'dist/cjs.js',
  files: [ 'dist' ],
  scripts:
   { start: 'npm run build -- -w',
     build: 'cross-env NODE_ENV=production babel src -d dist --ignore \'src/**/*.test.js\' --copy-files',
     test: 'jest',
     'test:watch': 'jest --watch',
     'test:coverage': 'jest --collectCoverageFrom=\'src/**/*.js\' --coverage',
     prebuild: 'npm run clean',
     clean: 'del-cli dist',
     lint: 'eslint --cache src test',
     'lint-staged': 'lint-staged',
     prepare: 'npm run build',
     release: 'standard-version',
     security: 'nsp check',
     'travis:lint': 'npm run lint && npm run security',
     'travis:test': 'npm run test -- --runInBand',
     'travis:coverage': 'npm run test:coverage -- --runInBand',
     'appveyor:test': 'npm run test',
     'webpack-defaults': 'webpack-defaults' },
  dependencies:
   { cacache: '^10.0.4',
     'find-cache-dir': '^1.0.0',
     'serialize-javascript': '^1.4.0',
     'schema-utils': '^0.4.5',
     'source-map': '^0.6.1',
     'uglify-es': '^3.3.4',
     'webpack-sources': '^1.1.0',
     'worker-farm': '^1.5.2' },
  devDependencies:
   { 'babel-cli': '^6.26.0',
     'babel-jest': '^21.2.0',
     'babel-plugin-transform-object-rest-spread': '^6.26.0',
     'babel-polyfill': '^6.26.0',
     'babel-preset-env': '^1.6.1',
     'cross-env': '^5.1.3',
     'del-cli': '^1.1.0',
     eslint: '^4.14.0',
     'eslint-config-webpack': '^1.2.5',
     'eslint-plugin-import': '^2.8.0',
     jest: '^21.2.1',
     'lint-staged': '^6.0.0',
     'memory-fs': '^0.4.1',
     nsp: '^3.1.0',
     'pre-commit': '^1.2.2',
     'standard-version': '^4.3.0',
     webpack: '^3.10.0',
     'webpack-defaults': '^1.6.0' },
  peerDependencies: { webpack: '^2.0.0 || ^3.0.0 || ^4.0.0' },
  'pre-commit': 'lint-staged',
  'lint-staged': { '*.js': [ 'eslint --fix', 'git add' ] },
  gitHead: '45a6cdfb451cc24bf341384457181a50909c9f54',
  dist:
   { integrity: 'sha512-as/50351uuJGiQbhVvE510SCqM/YOWghCzIFJeEOu5oVE0QOZ3/vu2QcnVvu0Lz+vNd0rKsiCFAlbcw0i/YH2w==',
     shasum: 'bf23197b37a8fc953fecfbcbab66e506f9a0ae72',
     tarball: 'https://registry.npmjs.org/uglifyjs-webpack-plugin/-/uglifyjs-webpack-plugin-1.2.3.tgz',
     fileCount: 11,
     unpackedSize: 51659 },
  directories: {} }
```

</details>

### supporting information:

 - `npm -v` prints: `5.7.1`
 - `node -v` prints: `9.8.0`
 - `npm config get registry` prints: `https://registry.npmjs.org/`
 - OS: `macOS`
 - Network issues: None
 - Container: None

**Comment by botre** [comment]
https://status.npmjs.org/incidents/gbk5bjx1169j

**Comment by michael-ciniawsky** [comment]
@Botre Thx for the link :)

**Comment by michael-ciniawsky** [comment]
Please let me know if there are any e.g local changes etc required to resolve this after the server(s) are up again :)

**Comment by michael-ciniawsky** [comment]
Resolved :)

**Comment by minasmart** [comment]
It looks like this is happening at least in private orgs again. 

Specifically, [this package](https://www.npmjs.com/package/@shopify/buy-button-js) is 3 patch versions behind what we've published.
