### ISSUE TITLE
npm publish 404 

### ISSUE THREAD

**Issue by stephenmcd** [npm/npm#20098]
I've published a dozen or so releases previously to the scoped package `@google/maps` and now `npm publish` is giving a 404 error on the package URL.

- I've ensured that the version number has been incremented
- I've scoured the documentation for `publish` and `scope` to look for anything that has changed since I last published but nothing sticks out
- I've verified my username via `npm whoami`
- I've run `npm logout` and `npm login` successfuly
- I've updated both `npm` and `nodejs` to the latest versions
- I've visited the URL given in the logs with a 404 error via a web browser, and can see the JSON for the package: https://registry.npmjs.org/@google%2fmaps

Here are the logs:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/9.8.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'publish' ]
2 info using npm@5.6.0
3 info using node@v9.8.0
4 verbose npm-session 72aa54dcbeb2ab64
5 verbose publish [ '.' ]
6 info lifecycle @google/maps@0.4.6~prepublish: @google/maps@0.4.6
7 info lifecycle @google/maps@0.4.6~prepare: @google/maps@0.4.6
8 info lifecycle @google/maps@0.4.6~prepublishOnly: @google/maps@0.4.6
9 info lifecycle @google/maps@0.4.6~prepack: @google/maps@0.4.6
10 info lifecycle @google/maps@0.4.6~postpack: @google/maps@0.4.6
11 verbose getPublishConfig undefined
12 silly mapToRegistry name @google/maps
13 silly mapToRegistry scope (from package name) @google
14 verbose mapToRegistry no registry URL found in name for scope @google
15 silly mapToRegistry using default registry
16 silly mapToRegistry registry https://registry.npmjs.org/
17 silly mapToRegistry data { type: 'tag',
17 silly mapToRegistry   registry: true,
17 silly mapToRegistry   where: undefined,
17 silly mapToRegistry   raw: '@google/maps',
17 silly mapToRegistry   name: '@google/maps',
17 silly mapToRegistry   escapedName: '@google%2fmaps',
17 silly mapToRegistry   scope: '@google',
17 silly mapToRegistry   rawSpec: '',
17 silly mapToRegistry   saveSpec: null,
17 silly mapToRegistry   fetchSpec: 'latest',
17 silly mapToRegistry   gitRange: undefined,
17 silly mapToRegistry   gitCommittish: undefined,
17 silly mapToRegistry   hosted: undefined }
18 silly mapToRegistry uri https://registry.npmjs.org/@google%2fmaps
19 verbose publish registryBase https://registry.npmjs.org/
20 silly publish uploading /var/folders/js/pvkw8njs3s33slsyg4zwhn4h009d9p/T/npm-94650-4df06a5f/tmp/fromDir-7412981f/package.tgz
21 verbose request uri https://registry.npmjs.org/@google%2fmaps
22 verbose request sending authorization for write operation
23 info attempt registry request try #1 at 11:40:53 AM
24 verbose request using bearer token for auth
25 verbose request id 9399536ba0d93545
26 http request PUT https://registry.npmjs.org/@google%2fmaps
27 http 404 https://registry.npmjs.org/@google%2fmaps
28 verbose headers { 'content-type': 'application/json',
28 verbose headers   'cache-control': 'max-age=0',
28 verbose headers   'content-length': '21',
28 verbose headers   'accept-ranges': 'bytes',
28 verbose headers   date: 'Mon, 19 Mar 2018 00:40:55 GMT',
28 verbose headers   via: '1.1 varnish',
28 verbose headers   connection: 'keep-alive',
28 verbose headers   'x-served-by': 'cache-syd18927-SYD',
28 verbose headers   'x-cache': 'MISS',
28 verbose headers   'x-cache-hits': '0',
28 verbose headers   'x-timer': 'S1521420055.593016,VS0,VE532' }
29 error publish Failed PUT 404
30 verbose stack Error: Not found : @google/maps
30 verbose stack     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:314:12)
30 verbose stack     at RegClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:302:14)
30 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:216:14)
30 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:186:22)
30 verbose stack     at Request.emit (events.js:180:13)
30 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1163:10)
30 verbose stack     at Request.emit (events.js:180:13)
30 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1085:12)
30 verbose stack     at Object.onceWrapper (events.js:272:13)
30 verbose stack     at IncomingMessage.emit (events.js:185:15)
30 verbose stack     at endReadableNT (_stream_readable.js:1101:12)
30 verbose stack     at process._tickCallback (internal/process/next_tick.js:114:19)
31 verbose statusCode 404
32 verbose pkgid @google/maps
33 verbose cwd /Users/stephenmcd/dev/google-maps-services-js
34 verbose Darwin 17.4.0
35 verbose argv "/usr/local/Cellar/node/9.8.0/bin/node" "/usr/local/bin/npm" "publish"
36 verbose node v9.8.0
37 verbose npm  v5.6.0
38 error code E404
39 error 404 Not found : @google/maps
40 error 404
41 error 404 '@google/maps' is not in the npm registry.
42 error 404 You should bug the author to publish it (or use the name yourself!)
43 error 404 Note that you can also install from a
44 error 404 tarball, folder, http url, or git url.
45 verbose exit [ 1, true ]
```

**Comment by stephenmcd** [comment]
I discovered the cause of this - the package did not belong to any of the teams under the org on npm, adding it to the default developers team resolved the error.
