### ISSUE TITLE
npm publish --access public failed with 403

### ISSUE THREAD

**Issue by divyamrastogi** [npm/npm#20123]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/divyam.r/.nvm/versions/node/v9.5.0/bin/node',
1 verbose cli   '/Users/divyam.r/.nvm/versions/node/v9.5.0/bin/npm',
1 verbose cli   'publish',
1 verbose cli   '--access',
1 verbose cli   'public' ]
2 info using npm@5.7.1
3 info using node@v9.5.0
4 verbose npm-session f6d2a4e4aaa66be7
5 verbose publish [ '.' ]
6 info lifecycle @flockos/vue-components@0.1.11~prepublish: @flockos/vue-components@0.1.11
7 info lifecycle @flockos/vue-components@0.1.11~prepare: @flockos/vue-components@0.1.11
8 info lifecycle @flockos/vue-components@0.1.11~prepublishOnly: @flockos/vue-components@0.1.11
9 info lifecycle @flockos/vue-components@0.1.11~prepack: @flockos/vue-components@0.1.11
10 info lifecycle @flockos/vue-components@0.1.11~postpack: @flockos/vue-components@0.1.11
11 verbose getPublishConfig undefined
12 silly mapToRegistry name @flockos/vue-components
13 silly mapToRegistry scope (from package name) @flockos
14 verbose mapToRegistry no registry URL found in name for scope @flockos
15 silly mapToRegistry using default registry
16 silly mapToRegistry registry https://registry.npmjs.org/
17 silly mapToRegistry data { type: 'tag',
17 silly mapToRegistry   registry: true,
17 silly mapToRegistry   where: undefined,
17 silly mapToRegistry   raw: '@flockos/vue-components',
17 silly mapToRegistry   name: '@flockos/vue-components',
17 silly mapToRegistry   escapedName: '@flockos%2fvue-components',
17 silly mapToRegistry   scope: '@flockos',
17 silly mapToRegistry   rawSpec: '',
17 silly mapToRegistry   saveSpec: null,
17 silly mapToRegistry   fetchSpec: 'latest',
17 silly mapToRegistry   gitRange: undefined,
17 silly mapToRegistry   gitCommittish: undefined,
17 silly mapToRegistry   hosted: undefined }
18 silly mapToRegistry uri https://registry.npmjs.org/@flockos%2fvue-components
19 verbose publish registryBase https://registry.npmjs.org/
20 silly publish uploading /var/folders/dt/b86lv31j1r12dgb_kqystzm1q9d0tg/T/npm-63062-c757d8ef/tmp/fromDir-57e0ec83/package.tgz
21 verbose request uri https://registry.npmjs.org/@flockos%2fvue-components
22 verbose request sending authorization for write operation
23 info attempt registry request try #1 at 17:06:15
24 verbose request using bearer token for auth
25 verbose request id dc135552091943ad
26 http request PUT https://registry.npmjs.org/@flockos%2fvue-components
27 http 403 https://registry.npmjs.org/@flockos%2fvue-components
28 verbose headers { 'content-type': 'application/json',
28 verbose headers   'cache-control': 'max-age=0',
28 verbose headers   'content-length': '21',
28 verbose headers   'accept-ranges': 'bytes',
28 verbose headers   date: 'Wed, 21 Mar 2018 11:36:18 GMT',
28 verbose headers   via: '1.1 varnish',
28 verbose headers   connection: 'keep-alive',
28 verbose headers   'x-served-by': 'cache-lcy19248-LCY',
28 verbose headers   'x-cache': 'MISS',
28 verbose headers   'x-cache-hits': '0',
28 verbose headers   'x-timer': 'S1521632176.450959,VS0,VE2526' }
29 error publish Failed PUT 403
30 verbose stack Error: Forbidden : @flockos/vue-components
30 verbose stack     at makeError (/Users/divyam.r/.nvm/versions/node/v9.5.0/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:314:12)
30 verbose stack     at RegClient.<anonymous> (/Users/divyam.r/.nvm/versions/node/v9.5.0/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:302:14)
30 verbose stack     at Request._callback (/Users/divyam.r/.nvm/versions/node/v9.5.0/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:216:14)
30 verbose stack     at Request.self.callback (/Users/divyam.r/.nvm/versions/node/v9.5.0/lib/node_modules/npm/node_modules/request/request.js:186:22)
30 verbose stack     at Request.emit (events.js:160:13)
30 verbose stack     at Request.<anonymous> (/Users/divyam.r/.nvm/versions/node/v9.5.0/lib/node_modules/npm/node_modules/request/request.js:1163:10)
30 verbose stack     at Request.emit (events.js:160:13)
30 verbose stack     at IncomingMessage.<anonymous> (/Users/divyam.r/.nvm/versions/node/v9.5.0/lib/node_modules/npm/node_modules/request/request.js:1085:12)
30 verbose stack     at Object.onceWrapper (events.js:255:19)
30 verbose stack     at IncomingMessage.emit (events.js:165:20)
30 verbose stack     at endReadableNT (_stream_readable.js:1101:12)
30 verbose stack     at process._tickCallback (internal/process/next_tick.js:152:19)
31 verbose statusCode 403
32 verbose pkgid @flockos/vue-components
33 verbose cwd /Users/divyam.r/projects/vue-components
34 verbose Darwin 17.4.0
35 verbose argv "/Users/divyam.r/.nvm/versions/node/v9.5.0/bin/node" "/Users/divyam.r/.nvm/versions/node/v9.5.0/bin/npm" "publish" "--access" "public"
36 verbose node v9.5.0
37 verbose npm  v5.7.1
38 error code E403
39 error Forbidden : @flockos/vue-components
40 verbose exit [ 1, true ]
```

#### How can the CLI team reproduce the problem?
While trying to publish the package in a scope, I encounter this error.

### supporting information:

 - `npm -v` prints: 5.7.1
 - `node -v` prints: v9.5.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: macOS
 - Network issues:
   - Geographic location where npm was run: India

**Comment by divyamrastogi** [comment]
It worked after I did two things:

1. Verified my email address.
2. Logged out of the npm cli by `npm logout` and then logging in by `npm login`
