### ISSUE TITLE
npm install occurs error

### ISSUE THREAD

**Issue by juzhen21510** [npm/npm#20132]
when I npm install base on the package.json, Error occured, the log is below

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'install' ]
2 info using npm@4.2.0
3 info using node@v7.10.0
4 verbose stack Error: Cannot find module 'realize-package-specifier'
4 verbose stack     at Function.Module._resolveFilename (module.js:470:15)
4 verbose stack     at Function.Module._load (module.js:418:25)
4 verbose stack     at Module.require (module.js:498:17)
4 verbose stack     at require (internal/module.js:20:19)
4 verbose stack     at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/install/deps.js:11:31)
4 verbose stack     at Module._compile (module.js:571:32)
4 verbose stack     at Object.Module._extensions..js (module.js:580:10)
4 verbose stack     at Module.load (module.js:488:32)
4 verbose stack     at tryModuleLoad (module.js:447:12)
4 verbose stack     at Function.Module._load (module.js:439:3)
5 verbose cwd /data/study/node
6 error Darwin 17.3.0
7 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
8 error node v7.10.0
9 error npm  v4.2.0
10 error code MODULE_NOT_FOUND
11 error Cannot find module 'realize-package-specifier'
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]

**Comment by waleiwalei** [comment]
Did you solve this problem?I ran into the same problem
