### ISSUE TITLE
"Cannot read property 'match' of undefined" When Installing git+ssh With No SSH Keys Available

### ISSUE THREAD

**Issue by jthomerson** [npm/npm#20143]
#### I'm opening this issue because:

  - [x] npm is crashing.

#### What's going wrong?

`npm ci` is crashing when it's trying to install a package via `git+ssh` when there are no SSH keys available to it.

#### How can the CLI team reproduce the problem?

The problem depends on needing an SSH dependency and not having SSH keys available. We hit this on our CI server when a developer added a dependency on another library we have (pointing to its repo by `git+ssh` and a commit hash, rather than a package name / version) and the CI server did not have SSH keys available to access that git repo. I've put together a test case that I can reproduce on my workstation *after I get rid of my SSH keys by doing `mv ~/.ssh ~/.ssh.bak && unset SSH_AUTH_SOCK`*.

```
mkdir /tmp/bar
pushd /tmp/bar
npm init
# accept all defaults
npm install --save-exact git+ssh://git@github.com/jashkenas/underscore.git#1bfc9f1fb811060c745e7025ec55e35f87c1d43b
# Okay, now get rid of your SSH keys so that you don't have them
# available for the install step.
mv ~/.ssh ~/.ssh.bak
unset SSH_AUTH_SOCK
npm ci --verbose
```

You should end up with a `package.json` like this:

```json
{
  "name": "bar",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "underscore": "git+ssh://git@github.com/jashkenas/underscore.git#1bfc9f1fb811060c745e7025ec55e35f87c1d43b"
  }
}
```

And you should see an error like this:

```
$ npm ci --verbose                                                                                                                                                                                    
npm info it worked if it ends with ok
npm verb cli [ '/Users/jrthomer/.nvm/versions/node/v6.10.3/bin/node',
npm verb cli   '/Users/jrthomer/.nvm/versions/node/v6.10.3/bin/npm',
npm verb cli   'ci',
npm verb cli   '--verbose' ]
npm info using npm@5.7.1
npm info using node@v6.10.3
npm verb npm-session 9034bd78d714dbe8
npm WARN init removing existing node_modules/ before installation
npm verb stack TypeError: Cannot read property 'match' of undefined
npm verb stack     at extractByManifest.catch.err (/Users/jrthomer/.nvm/versions/node/v6.10.3/lib/node_modules/npm/node_modules/pacote/extract.js:52:36)
npm verb stack     at tryCatcher (/Users/jrthomer/.nvm/versions/node/v6.10.3/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
npm verb stack     at Promise._settlePromiseFromHandler (/Users/jrthomer/.nvm/versions/node/v6.10.3/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
npm verb stack     at Promise._settlePromise (/Users/jrthomer/.nvm/versions/node/v6.10.3/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
npm verb stack     at Promise._settlePromise0 (/Users/jrthomer/.nvm/versions/node/v6.10.3/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
npm verb stack     at Promise._settlePromises (/Users/jrthomer/.nvm/versions/node/v6.10.3/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:689:18)
npm verb stack     at Async._drainQueue (/Users/jrthomer/.nvm/versions/node/v6.10.3/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
npm verb stack     at Async._drainQueues (/Users/jrthomer/.nvm/versions/node/v6.10.3/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
npm verb stack     at Immediate.Async.drainQueues (/Users/jrthomer/.nvm/versions/node/v6.10.3/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
npm verb stack     at runCallback (timers.js:672:20)
npm verb stack     at tryOnImmediate (timers.js:645:5)
npm verb stack     at processImmediate [as _immediateCallback] (timers.js:617:5)
npm verb cwd /private/tmp/bar
npm verb Darwin 16.7.0
npm verb argv "/Users/jrthomer/.nvm/versions/node/v6.10.3/bin/node" "/Users/jrthomer/.nvm/versions/node/v6.10.3/bin/npm" "ci" "--verbose"
npm verb node v6.10.3
npm verb npm  v5.7.1
npm ERR! Cannot read property 'match' of undefined
npm verb exit [ 1, true ]

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jrthomer/.npm/_logs/2018-03-23T00_20_51_358Z-debug.log
```

### supporting information:

 - `npm -v` prints: 5.7.1
 - `node -v` prints: v6.10.3
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Mac
 - Network issues: None
   - Geographic location where npm was run: United States
 - Container: N/A

**Comment by jthomerson** [comment]
I guess it's worth noting that obviously there _should_ be an error in a case where you don't have permission to access the dependency. The reason I'm reporting this as a bug is because the error that's being output is absolutely no help in actually seeing what the real issue is.

**Comment by Alexander3** [comment]
I have similar problem, not related to ssh, after installing `jest-cli` I was unable to uninstall it or install different version. `npm@6.1.0` `node@v9.11.1` on Ubuntu 18.04 LTS  (I've had same error with `npm@6.0.1`)
```
$ npm uninstall jest-cli --verbose
npm info it worked if it ends with ok
npm verb cli [ '/home/bond/.nvm/versions/node/v9.11.1/bin/node',
npm verb cli   '/home/bond/.nvm/versions/node/v9.11.1/bin/npm',
npm verb cli   'uninstall',
npm verb cli   'jest-cli',
npm verb cli   '--verbose' ]
npm info using npm@6.1.0
npm info using node@v9.11.1
npm verb npm-session 36e3b0cb334bfec7
npm timing stage:loadCurrentTree Completed in 755ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 5ms
npm http fetch GET 200 https://registry.npmjs.org/babel-loader 8ms (from cache)
npm timing stage:rollbackFailedOptional Completed in 0ms
npm timing stage:runTopLevelLifecycles Completed in 879ms
npm verb stack TypeError: Cannot read property 'match' of undefined
npm verb stack     at tarballToVersion (/home/bond/.nvm/versions/node/v9.11.1/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:87:20)
npm verb stack     at inflatableChild (/home/bond/.nvm/versions/node/v9.11.1/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:99:22)
npm verb stack     at BB.each (/home/bond/.nvm/versions/node/v9.11.1/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:55:12)
npm verb stack     at tryCatcher (/home/bond/.nvm/versions/node/v9.11.1/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
npm verb stack     at Object.gotValue (/home/bond/.nvm/versions/node/v9.11.1/lib/node_modules/npm/node_modules/bluebird/js/release/reduce.js:155:18)
npm verb stack     at Object.gotAccum (/home/bond/.nvm/versions/node/v9.11.1/lib/node_modules/npm/node_modules/bluebird/js/release/reduce.js:144:25)
npm verb stack     at Object.tryCatcher (/home/bond/.nvm/versions/node/v9.11.1/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
npm verb stack     at Promise._settlePromiseFromHandler (/home/bond/.nvm/versions/node/v9.11.1/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
npm verb stack     at Promise._settlePromise (/home/bond/.nvm/versions/node/v9.11.1/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
npm verb stack     at Promise._settlePromiseCtx (/home/bond/.nvm/versions/node/v9.11.1/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:606:10)
npm verb stack     at Async._drainQueue (/home/bond/.nvm/versions/node/v9.11.1/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:138:12)
npm verb stack     at Async._drainQueues (/home/bond/.nvm/versions/node/v9.11.1/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
npm verb stack     at Immediate.Async.drainQueues [as _onImmediate] (/home/bond/.nvm/versions/node/v9.11.1/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
npm verb stack     at runCallback (timers.js:763:18)
npm verb stack     at tryOnImmediate (timers.js:734:5)
npm verb stack     at processImmediate (timers.js:716:5)
npm verb cwd /home/bond/work/sunscrapers/verve/root/customer_ui
npm verb Linux 4.15.0-22-generic
npm verb argv "/home/bond/.nvm/versions/node/v9.11.1/bin/node" "/home/bond/.nvm/versions/node/v9.11.1/bin/npm" "uninstall" "jest-cli" "--verbose"
npm verb node v9.11.1
npm verb npm  v6.1.0
npm ERR! Cannot read property 'match' of undefined
npm verb exit [ 1, true ]
npm timing npm Completed in 1127ms
```

**Comment by legodude17** [comment]
Does the same thing occur with `npm install` or is it just `npm ci`?

**Comment by jthomerson** [comment]
@legodude17 I'm not in a position to test today. I provided a testcase that should make it easy to reproduce. Are you able to check?

**Comment by pawlufelice** [comment]
Same issue, even on `npm i`. I'm replicating it without installing `git+ssh`. Trying `CRNA` and still getting same issue

UPDATE: removed `package-lock.json` and error is mitigated. But still not sure what goes on.

**Comment by nfantone** [comment]
Same here. For me, it's `npm audit fix` triggering the problem.

```sh
❯ npm i
npm ERR! Cannot read property 'match' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user/.npm/_logs/2018-06-01T14_22_06_261Z-debug.log
```

Can confirm that `rm package-lock.json` resolves the issue - but comes back after running `audit fix`.

```sh
❯ rm package-lock.json

❯ npm i  # install now works correctly
npm notice created a lockfile as package-lock.json. You should commit this file.
audited 27793 packages in 10.934s
found 6 vulnerabilities (5 moderate, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details

❯ npm audit fix
npm ERR! Cannot read property 'match' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user/.npm/_logs/2018-06-01T14_24_03_541Z-debug.log

❯ npm i  # install broken again
npm ERR! Cannot read property 'match' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user/.npm/_logs/2018-06-01T14_24_11_702Z-debug.log
```

**Comment by ValeryDubrava** [comment]
I've the same issue after chai package installed on my environment:
```
6297 silly saveTree ├── bignumber.js@7.0.1
6297 silly saveTree ├─┬ chai-as-promised@7.1.1
6297 silly saveTree │ └── check-error@1.0.2
6297 silly saveTree ├── chai-bignumber@2.0.2
6297 silly saveTree └─┬ chai@4.1.2
6297 silly saveTree   ├── assertion-error@1.1.0
6297 silly saveTree   ├── pathval@1.1.0
6297 silly saveTree   └── type-detect@4.0.8
6298 verbose stack TypeError: Cannot read property 'match' of undefined
6298 verbose stack     at tarballToVersion (/usr/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:87:19)
6298 verbose stack     at inflatableChild (/usr/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:99:22)
6298 verbose stack     at BB.each (/usr/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:55:12)
6298 verbose stack     at tryCatcher (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
6298 verbose stack     at Object.gotValue (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/reduce.js:155:18)
6298 verbose stack     at Object.gotAccum (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/reduce.js:144:25)
6298 verbose stack     at Object.tryCatcher (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
6298 verbose stack     at Promise._settlePromiseFromHandler (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
6298 verbose stack     at Promise._settlePromise (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
6298 verbose stack     at Promise._settlePromiseCtx (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:606:10)
6298 verbose stack     at Async._drainQueue (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:138:12)
6298 verbose stack     at Async._drainQueues (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
6298 verbose stack     at Immediate.Async.drainQueues (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
6298 verbose stack     at runCallback (timers.js:781:20)
6298 verbose stack     at tryOnImmediate (timers.js:743:5)
6298 verbose stack     at processImmediate [as _immediateCallback] (timers.js:714:5)
6299 verbose cwd /home/dev/code/solidity/cryptocredit
6300 verbose Linux 4.4.0-87-generic
6301 verbose argv "/usr/bin/nodejs" "/usr/bin/npm" "update"
6302 verbose node v8.2.1
6303 verbose npm  v6.0.1
6304 error Cannot read property 'match' of undefined
6305 verbose exit [ 1, true ]
```

**Comment by ludobit** [comment]
`npm ERR! Cannot read property 'match' of undefined`

When i try to run `npm i`. If I delete package-lock.json works, but (i'm in a Ionic Project) when run the application the scripts generate the lock file, so i've got the same error again!

**Comment by The-Peanut** [comment]
Can reproduce still in koel install. Can this be fixed?

**Comment by kevinjcoleman** [comment]
I'm also experiencing this issue with `npm audit fix`. 
`npm -v -> 6.1.0`
```
21 verbose stack TypeError: Cannot read property 'match' of undefined
21 verbose stack     at tarballToVersion (/usr/local/nvm/versions/node/v8.11.2/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:87:20)
21 verbose stack     at inflatableChild (/usr/local/nvm/versions/node/v8.11.2/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:99:22)
21 verbose stack     at BB.each (/usr/local/nvm/versions/node/v8.11.2/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:55:12)
21 verbose stack     at tryCatcher (/usr/local/nvm/versions/node/v8.11.2/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
21 verbose stack     at Object.gotValue (/usr/local/nvm/versions/node/v8.11.2/lib/node_modules/npm/node_modules/bluebird/js/release/reduce.js:155:18)
21 verbose stack     at Object.gotAccum (/usr/local/nvm/versions/node/v8.11.2/lib/node_modules/npm/node_modules/bluebird/js/release/reduce.js:144:25)
21 verbose stack     at Object.tryCatcher (/usr/local/nvm/versions/node/v8.11.2/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
21 verbose stack     at Promise._settlePromiseFromHandler (/usr/local/nvm/versions/node/v8.11.2/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
21 verbose stack     at Promise._settlePromise (/usr/local/nvm/versions/node/v8.11.2/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
21 verbose stack     at Promise._settlePromise0 (/usr/local/nvm/versions/node/v8.11.2/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
21 verbose stack     at Promise._settlePromises (/usr/local/nvm/versions/node/v8.11.2/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
21 verbose stack     at Async._drainQueue (/usr/local/nvm/versions/node/v8.11.2/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
21 verbose stack     at Async._drainQueues (/usr/local/nvm/versions/node/v8.11.2/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
21 verbose stack     at Immediate.Async.drainQueues (/usr/local/nvm/versions/node/v8.11.2/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
21 verbose stack     at runCallback (timers.js:810:20)
21 verbose stack     at tryOnImmediate (timers.js:768:5)
22 verbose cwd /app
23 verbose Linux 4.9.93-linuxkit-aufs
24 verbose argv "/usr/local/nvm/versions/node/v8.11.2/bin/node" "/usr/local/nvm/versions/node/v8.11.2/bin/npm" "audit" "fix"
25 verbose node v8.11.2
26 verbose npm  v6.1.0
27 error Cannot read property 'match' of undefined
28 verbose exit [ 1, true ]
````

**Comment by mkovatsc** [comment]
I consistently receive the `Cannot read property 'match' of undefined` error when a local module is linked into node_modules (`npm link <local_module_name>`).
