### ISSUE TITLE
error cannot find module 'gulp-imagemin'

### ISSUE THREAD

**Issue by ihor-kritsak** [npm/npm#20156]
I'm runing 'gulp-imagemin'

module.js:549

    throw err;
    ^

Error: Cannot find module 'gulp-imagemin'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\Project\Crm\gulpfile.js:10:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

**Comment by kenany** [comment]
What `npm` command can I run to reproduce this?
