### ISSUE TITLE
SSL Error: CERT_UNTRUSTED

### ISSUE THREAD

**Issue by SheetJSDev** [npm/npm#20191]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

```
npm http GET https://registry.npmjs.org/npm/4.3.0
npm ERR! Error: SSL Error: CERT_UNTRUSTED
npm ERR!     at Request.onResponse (/usr/local/lib/node_modules/npm/node_modules/request/index.js:655:24)
npm ERR!     at ClientRequest.g (events.js:192:14)
npm ERR!     at ClientRequest.EventEmitter.emit (events.js:96:17)
npm ERR!     at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1588:7)
npm ERR!     at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:111:23)
npm ERR!     at CleartextStream.socketOnData [as ondata] (http.js:1491:20)
npm ERR!     at CleartextStream.CryptoStream._push (tls.js:547:27)
npm ERR!     at SecurePair.cycle (tls.js:901:20)
npm ERR!     at EncryptedStream.CryptoStream.write (tls.js:285:13)
npm ERR!     at Socket.ondata (stream.js:38:26)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 17.4.0
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "npm@4.3.0"
npm ERR! cwd /tmp
npm ERR! node -v v0.8.28
npm ERR! npm -v 1.2.30
npm ERR! code ESSL
npm ERR! 
```

A CI run from 9 days ago had no problem with the cert: https://travis-ci.org/SheetJS/js-xlsx/jobs/355594401

But the same configuration failed today: https://travis-ci.org/SheetJS/js-xlsx/jobs/359682879

**Comment by sabag** [comment]
The same happens to our internal build (exactly the same).
any response from anyone ?

**Comment by juno-visualsquares** [comment]
we are experiencing this too, last build succeeded was 2 day ago

**Comment by amir-mehler-via** [comment]
we are experiencing this three.

Working around for now with: `npm config set strict-ssl false`

**Comment by sabag** [comment]
any way to work around it the meantime ? we have a dead line to meet today ?

**Comment by nexorianus** [comment]
an update of Node to v. 9.x solved this problem for me.

node -v  ->  v9.10.0
npm -v -> 5.6.0

**Comment by sabag** [comment]
hi, i found an already documented workaround:
"npm config set strict-ssl false"
and only then running the npm install will be ok.

reference: https://github.com/LightTable/LightTable/issues/2212

**Comment by erikselin** [comment]
Started seeing `Error: UNABLE_TO_GET_ISSUER_CERT_LOCALLY` on node v0.10.48 which is fixed by `npm config set strict-ssl false`. However, doesn't setting `strict-ssl` to `false` seems like a fairly dangerous thing to do given that we do not know what's wrong?

**Comment by filex** [comment]
we have nightly builds with a couple of distros. stock `nodejs` (0.10.25) and `npm`  (1.3.10) in ubuntu 14.04 LTS are broken since today. this is a simple reproducer with docker:

```
$ docker run --rm -i ubuntu:14.04 bash -c 'apt-get update; apt-get upgrade -y && apt-get install -y npm && npm install npm || cat /npm-debug.log'
```

it works fine in the newer ubuntu 17.10 LTS:

```
$ docker run --rm  ubuntu:17.10 bash -c 'apt-get update; apt-get upgrade -y && apt-get install -y npm && npm install npm'
```

**Comment by SheetJSDev** [comment]
Thanks @amir-mehler-via !  [`npm config set strict-ssl false`](https://travis-ci.org/SheetJS/js-xlsx/jobs/359916170#L457) worked in travis against node 0.8.28 npm 1.2.30

@filex check the node/npm version -- Ubuntu 17.10 might be using a newer release.

**Comment by filex** [comment]
@SheetJSDev, yes, ubuntu 17.10 has fresher versions. However, `npm` on 14.04 shouldn't stop working out of a sudden :)

---

The ssl certificates for `registry.npmjs.org` are quite new (valid from 2018-03-15) and have possibly just been rolled out. The system CA store for ubuntu 14.04 has no problem validating the new certificate (e.g. using `curl -v https://registry.npmjs.org/`). Does node ship its own CA store? Are intermediate certificates missing in the new setup?

**Comment by EeroV** [comment]
Is there any way to fix issue without disabling security features of ssl?

**Comment by SheetJSDev** [comment]
@EeroV brass tacks: this issue seems to affect older versions of node/npm and there's a reasonable argument to be made that npm should only care about the latest version.  They say it in the README:

> To install an old and **unsupported** version of npm that works on node v0.12 and prior, clone the git repo and dig through the old tags and branches.

There's one other workaround, but it arguably is even less sane: use a tool like `nvm` to install a new version of node, install the modules you need under the new version of `npm`, then roll back to the older version of node.  That's how the [semaphore-ci](https://semaphoreci.com/sheetjs/js-xlsx/branches/master/builds/64) tests are run: start from node 8.9.4, install necessary modules, then switch the node version to the appropriate one and test.

The culture of rapid deprecation is unfortunate but it exists.  No one likes these workarounds

**Comment by daharon** [comment]
NPM in EPEL for CentOS 6 is also suffering from this issue:  
http://fedora.westmancom.com/epel/6/x86_64/Packages/n/

    npm.noarch                           1.3.6-5.el6                       @epel

I have opened a ticket on the RedHat bugzilla:  https://bugzilla.redhat.com/show_bug.cgi?id=1562592

**Comment by EeroV** [comment]
yes and amazon linux (v1) also as it's based on centos+epel.

So sad.

Eero

su 1. huhtik. 2018 klo 11.15 Daniel Aharon <notifications@github.com>
kirjoitti:

**Comment by EeroV** [comment]
In fact I noticed issue when our automatic cloudformation stack failed for
this reason.

I think that lots of "customers" are affected by this issue.

Eero

su 1. huhtik. 2018 klo 11.15 Daniel Aharon <notifications@github.com>
kirjoitti:

**Comment by EeroV** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1562592

(In reply to Tom Hughes from comment #2
<https://bugzilla.redhat.com/show_bug.cgi?id=1562592#c2>)> I suspect
this is really an issue with ca-certificates in el6 not trusting
> whatever root is not issuing the certificate for npm?

Unfortunately, it's a problem with the CA certificates bundled as
strings within the code of
NPM:https://github.com/npm/npm/blob/43dc430d97d6bc459c4873fbb55397af0994dbad/node_modules/npmconf/config-defs.js#L119-L205

<insert disparaging remark about Node.js>

**Comment by EeroV** [comment]
to fix issue on older npm you need to update config-defs.js with newer
certificaticates

see: https://bugzilla.redhat.com/attachment.cgi?id=1416575

**Comment by EeroV** [comment]
https://bugs.launchpad.net/bugs/1760840 ubuntu bug tracking url. it
contains same issue.

ti 3. huhtik. 2018 klo 8.42 Eero Volotinen <eero.volotinen@iki.fi>
kirjoitti:

**Comment by dougwilson** [comment]
For those using Travis CI, at least, I made a PR https://github.com/travis-ci/travis-build/pull/1350 to disable the ssl check by default for Node.js 0.8 builds (which already happens in Travis CI for Node.js 0.6 builds).

**Comment by krassowski** [comment]
Rapid deprecation? Ok, I can deal with that. But, I cannot even easily upgrade npm to the latest version! Seriously? (Just saying that the developer experience here is quite discouraging)

```javascript
$ sudo npm install -g npm@latest
npm http GET https://registry.npmjs.org/npm
npm http GET https://registry.npmjs.org/npm
npm http GET https://registry.npmjs.org/npm
npm ERR! Error: CERT_UNTRUSTED
npm ERR!     at SecurePair.<anonymous> (tls.js:1370:32)
npm ERR!     at SecurePair.EventEmitter.emit (events.js:92:17)
npm ERR!     at SecurePair.maybeInitFinished (tls.js:982:10)
npm ERR!     at CleartextStream.read [as _read] (tls.js:469:13)
npm ERR!     at CleartextStream.Readable.read (_stream_readable.js:320:10)
npm ERR!     at EncryptedStream.write [as _write] (tls.js:366:25)
npm ERR!     at doWrite (_stream_writable.js:223:10)
npm ERR!     at writeOrBuffer (_stream_writable.js:213:5)
npm ERR!     at EncryptedStream.Writable.write (_stream_writable.js:180:11)
npm ERR!     at write (_stream_readable.js:583:24)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 4.4.0-101-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "npm@latest"
npm ERR! cwd /home/travis/build/reimandlab/ActiveDriverDB
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/travis/build/reimandlab/ActiveDriverDB/npm-debug.log
npm ERR! not ok code 0
```

@dougwilson, do you think that Node v0.10 should have the SSL checks disabled by default too?

**Comment by EeroV** [comment]
Well,

redhat/centos/clones 6.* are still supported and ubuntu. they should at
least apply patch to fix the issue.

Looks like they don't care. .

Eero

pe 20. huhtik. 2018 klo 15.40 krassowski <notifications@github.com>
kirjoitti:

**Comment by dougwilson** [comment]
I haven't had issues with Node.js 0.10 in Travis CI myself, but if you are, you can always PR to Travis a copy of the PR I made.

**Comment by EeroV** [comment]
sad. No fix from redhat/epel or ubuntu?

Eero

**Comment by filex** [comment]
looks like the certificates for registry.npmjs.org have changed once again. now they are using a `COMODO ECC Domain Validation Secure Server CA 2`. (When this bug arose they changed to `GlobalSign Extended Validation`, sad to see that such an important service has dropped EV…).

I have had followed the proposed workaround patching `npm-config-defs.js`. However, I didn't use the whole huge list auf CAs, but only the needed ones. This stopped working today. I had to add 

```
  // # COMODO ECC Certification Authority
  "-----BEGIN CERTIFICATE-----\n" +
  "MIICiTCCAg+gAwIBAgIQH0evqmIAcFBUTAGem2OZKjAKBggqhkjOPQQDAzCBhTEL\n" +
  "MAkGA1UEBhMCR0IxGzAZBgNVBAgTEkdyZWF0ZXIgTWFuY2hlc3RlcjEQMA4GA1UE\n" +
  "BxMHU2FsZm9yZDEaMBgGA1UEChMRQ09NT0RPIENBIExpbWl0ZWQxKzApBgNVBAMT\n" +
  "IkNPTU9ETyBFQ0MgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkwHhcNMDgwMzA2MDAw\n" +
  "MDAwWhcNMzgwMTE4MjM1OTU5WjCBhTELMAkGA1UEBhMCR0IxGzAZBgNVBAgTEkdy\n" +
  "ZWF0ZXIgTWFuY2hlc3RlcjEQMA4GA1UEBxMHU2FsZm9yZDEaMBgGA1UEChMRQ09N\n" +
  "T0RPIENBIExpbWl0ZWQxKzApBgNVBAMTIkNPTU9ETyBFQ0MgQ2VydGlmaWNhdGlv\n" +
  "biBBdXRob3JpdHkwdjAQBgcqhkjOPQIBBgUrgQQAIgNiAAQDR3svdcmCFYX7deSR\n" +
  "FtSrYpn1PlILBs5BAH+X4QokPB0BBO490o0JlwzgdeT6+3eKKvUDYEs2ixYjFq0J\n" +
  "cfRK9ChQtP6IHG4/bC8vCVlbpVsLM5niwz2J+Wos77LTBumjQjBAMB0GA1UdDgQW\n" +
  "BBR1cacZSBm8nZ3qQUfflMRId5nTeTAOBgNVHQ8BAf8EBAMCAQYwDwYDVR0TAQH/\n" +
  "BAUwAwEB/zAKBggqhkjOPQQDAwNoADBlAjEA7wNbeqy3eApyt4jf/7VGFAkK+qDm\n" +
  "fQjGGoe9GKhzvSbKYAydzpmfz1wPMOG+FDHqAjAU9JM8SaczepBGR7NjfRObTrdv\n" +
  "GDeAU/7dIOA1mjbRxwG55tzd8/8dLDoWV9mSOdY=\n" +
  "-----END CERTIFICATE-----\n"
````

to the patch.

**Comment by EeroV** [comment]
main issue is that this is not fixed in el6 and clones..

su 27. toukok. 2018 klo 16.26 Felix Hassert <notifications@github.com>
kirjoitti:
