### ISSUE TITLE
npm installation broken

### ISSUE THREAD

**Issue by eliyastein** [npm/npm#20206]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

I'm not sure when this fell apart, but I'm experiencing this:

````$ npm -v
module.js:545
    throw err;
    ^

Error: Cannot find module '../lib/utils/unsupported.js'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:19:21
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:92:3)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
````
I tried updating, then uninstalling, then re-installing node with homebrew.

````$ uname -a
Darwin Ricos-MacBook-Pro.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jan 11 22:59:40 PST 2018; root:xnu-3789.73.8~1/RELEASE_X86_64 x86_64
````

**Comment by vsemozhetbyt** [comment]
Seems fixed: https://github.com/nodejs/node/issues/19702

**Comment by eliyastein** [comment]
Yes, thanks @vsemozhetbyt
