### ISSUE TITLE
npm ERR! missing script: debug

### ISSUE THREAD

**Issue by velraj0110** [npm/npm#20200]
Im new to Node.js. when i try to debug the existing project in visual studio in Windows, Im getting the below error:
npm
 
ERR! Windows_NT 6.1.7601
npm 
ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run-script" "debug"
npm ERR! node
 v6.10.0
npm
 ERR! npm  v3.10.10
npm ERR! missing script: debug
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

Log:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run-script',
1 verbose cli   'debug' ]
2 info using npm@3.10.10
3 info using node@v6.10.0
4 verbose stack Error: missing script: debug
4 verbose stack     at run (C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:151:19)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:61:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:356:5
4 verbose stack     at checkBinReferences_ (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:320:45)
4 verbose stack     at final (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:354:3)
4 verbose stack     at then (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:124:5)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:311:12
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16
4 verbose stack     at tryToString (fs.js:455:3)
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)
5 verbose cwd c:\m64312\2018\Registration\Bff\develop\web-gateway-chcp-identity-service-v1
6 error Windows_NT 6.1.7601
7 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run-script" "debug"
8 error node v6.10.0
9 error npm  v3.10.10
10 error missing script: debug
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

Could you please help to solve this issue

**Comment by kenany** [comment]
Ensure that you have a `"debug"` script defined in your `package.json`. The error log is saying that you do not, hence `npm run debug` has no idea what you want it to do.
