### ISSUE TITLE
npm ERR! Error: CERT_UNTRUSTED

### ISSUE THREAD

**Issue by duxuebing** [npm/npm#20203]
npm ERR! Error: CERT_UNTRUSTED
npm ERR!     at SecurePair.<anonymous> (tls.js:1430:32)
npm ERR!     at SecurePair.emit (events.js:92:17)
npm ERR!     at SecurePair.maybeInitFinished (tls.js:1029:10)
npm ERR!     at CleartextStream.read [as _read] (tls.js:521:13)
npm ERR!     at CleartextStream.Readable.read (_stream_readable.js:341:10)
npm ERR!     at EncryptedStream.write [as _write] (tls.js:418:25)
npm ERR!     at doWrite (_stream_writable.js:226:10)
npm ERR!     at writeOrBuffer (_stream_writable.js:216:5)
npm ERR!     at EncryptedStream.Writable.write (_stream_writable.js:183:11)
npm ERR!     at write (_stream_readable.js:602:24)

**Comment by jbleyel** [comment]
me too
https://api.travis-ci.org/v3/job/360176512/log.txt

**Comment by RomanSurface** [comment]
me too 


**node v** : 
nodejs -v
v0.10.25

**log :** 
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'create-react-native-app' ]
2 info using npm@1.3.10
3 info using node@v0.10.25
4 verbose cache add [ 'create-react-native-app', null ]
5 verbose cache add name=undefined spec="create-react-native-app" args=["create-react-native-app",null]
6 verbose parsed url { protocol: null,
6 verbose parsed url   slashes: null,
6 verbose parsed url   auth: null,
6 verbose parsed url   host: null,
6 verbose parsed url   port: null,
6 verbose parsed url   hostname: null,
6 verbose parsed url   hash: null,
6 verbose parsed url   search: null,
6 verbose parsed url   query: null,
6 verbose parsed url   pathname: 'create-react-native-app',
6 verbose parsed url   path: 'create-react-native-app',
6 verbose parsed url   href: 'create-react-native-app' }
7 silly lockFile dc00d570-create-react-native-app create-react-native-app
8 verbose lock create-react-native-app /home/pietro/.npm/dc00d570-create-react-native-app.lock
9 silly lockFile dc00d570-create-react-native-app create-react-native-app
10 silly lockFile dc00d570-create-react-native-app create-react-native-app
11 verbose addNamed [ 'create-react-native-app', '' ]
12 verbose addNamed [ null, '*' ]
13 silly lockFile 7106dfe8-create-react-native-app create-react-native-app@
14 verbose lock create-react-native-app@ /home/pietro/.npm/7106dfe8-create-react-native-app.lock
15 silly addNameRange { name: 'create-react-native-app', range: '*', hasData: false }
16 verbose url raw create-react-native-app
17 verbose url resolving [ 'https://registry.npmjs.org/', './create-react-native-app' ]
18 verbose url resolved https://registry.npmjs.org/create-react-native-app
19 info trying registry request attempt 1 at 11:55:03
20 http GET https://registry.npmjs.org/create-react-native-app
21 info retry will retry, error on last attempt: Error: CERT_UNTRUSTED
22 info trying registry request attempt 2 at 11:55:13
23 http GET https://registry.npmjs.org/create-react-native-app
24 info retry will retry, error on last attempt: Error: CERT_UNTRUSTED
25 info trying registry request attempt 3 at 11:56:14
26 http GET https://registry.npmjs.org/create-react-native-app
27 silly lockFile 7106dfe8-create-react-native-app create-react-native-app@
28 silly lockFile 7106dfe8-create-react-native-app create-react-native-app@
29 error Error: CERT_UNTRUSTED
29 error     at SecurePair.<anonymous> (tls.js:1370:32)
29 error     at SecurePair.EventEmitter.emit (events.js:92:17)
29 error     at SecurePair.maybeInitFinished (tls.js:982:10)
29 error     at CleartextStream.read [as _read] (tls.js:469:13)
29 error     at CleartextStream.Readable.read (_stream_readable.js:320:10)
29 error     at EncryptedStream.write [as _write] (tls.js:366:25)
29 error     at doWrite (_stream_writable.js:223:10)
29 error     at writeOrBuffer (_stream_writable.js:213:5)
29 error     at EncryptedStream.Writable.write (_stream_writable.js:180:11)
29 error     at write (_stream_readable.js:583:24)
30 error If you need help, you may report this log at:
30 error     <http://github.com/isaacs/npm/issues>
30 error or email it to:
30 error     <npm-@googlegroups.com>
31 error System Linux 4.4.0-116-generic
32 error command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "create-react-native-app"
33 error cwd /home/pietro/Documents/REACT
34 error node -v v0.10.25
35 error npm -v 1.3.10
36 verbose exit [ 1, true ]

**Comment by albert-carreras** [comment]
Also happens here!

**Comment by SheetJSDev** [comment]
Same issue as https://github.com/npm/npm/issues/20191 .  This is affecting older versions of node/npm.  `npm config set strict-ssl false` is a dirty workaround.

@jbleyel for travis, [you can add the workaround in the `before_install` hook:](https://github.com/SheetJS/js-xlsx/blob/master/.travis.yml#L37-L38)

```yaml
before_install:
  - "npm config set strict-ssl false"
```
