### ISSUE TITLE
npm ERR! Cannot find module 'fs-minipass'

### ISSUE THREAD

**Issue by ghost** [npm/npm#20224]
Hi when i try to install anything with npm i get this error :

npm ERR! code MODULE_NOT_FOUND
npm ERR! Cannot find module 'fs-minipass'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\samar\AppData\Roaming\npm-cache\_logs\2018-04-01T16_42_29_011Z-debug.log

I tried to uninstall and reinstall node, restart computer, install fs-minipass manually.

nothing worked

Worked fine before so i dont know how does it happened and also haven't find this problem elsewhere so no idea.

also fs-minipass is already there 
![image](https://user-images.githubusercontent.com/31006418/38175569-d926576e-35de-11e8-9e9b-03fbb5407c82.png)

Edit: not wait its not there when i install, added manually but still not work

Logs : 
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\samar\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'latest' ]
2 info using npm@5.8.0
3 info using node@v9.10.1
4 verbose config Skipping project config: C:\Users\samar/.npmrc. (matches userconfig)
5 verbose stack Error: Cannot find module 'fs-minipass'
5 verbose stack     at Function.Module._resolveFilename (module.js:543:15)
5 verbose stack     at Function.Module._load (module.js:470:25)
5 verbose stack     at Module.require (module.js:593:17)
5 verbose stack     at require (internal/module.js:11:18)
5 verbose stack     at Object.<anonymous> (C:\Users\samar\AppData\Roaming\npm\node_modules\npm\node_modules\tar\lib\create.js:8:13)
5 verbose stack     at Module._compile (module.js:649:30)
5 verbose stack     at Object.Module._extensions..js (module.js:660:10)
5 verbose stack     at Module.load (module.js:561:32)
5 verbose stack     at tryModuleLoad (module.js:501:12)
5 verbose stack     at Function.Module._load (module.js:493:3)
5 verbose stack     at Module.require (module.js:593:17)
5 verbose stack     at require (internal/module.js:11:18)
5 verbose stack     at Object.<anonymous> (C:\Users\samar\AppData\Roaming\npm\node_modules\npm\node_modules\tar\index.js:4:30)
5 verbose stack     at Module._compile (module.js:649:30)
5 verbose stack     at Object.Module._extensions..js (module.js:660:10)
5 verbose stack     at Module.load (module.js:561:32)
6 verbose cwd C:\Users\samar
7 verbose Windows_NT 10.0.16299
8 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\samar\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "latest"
9 verbose node v9.10.1
10 verbose npm  v5.8.0
11 error code MODULE_NOT_FOUND
12 error Cannot find module 'fs-minipass'
13 verbose exit [ 1, true ]

### supporting information:

 - `npm -v` prints: 5.8.0
 - `node -v` prints: v9.10.1
 - Windows, OS X/macOS, or Linux?: Windows 10

**Comment by ghost** [comment]
k fixed sorry, deleted the path file and things for some reason was redirecting to roaming or idk unsure but problem was from me lol

**Comment by ulivz** [comment]
Same problem when upgrading from `3.10.10` to `6.0.1`:

1. `sudo npm install npm -g` 

2. `npm install`

then I got following error:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'install' ]
2 info using npm@6.1.0
3 info using node@v6.11.3
4 verbose stack Error: Cannot find module 'fs-minipass'
4 verbose stack     at Function.Module._resolveFilename (module.js:469:15)
4 verbose stack     at Function.Module._load (module.js:417:25)
4 verbose stack     at Module.require (module.js:497:17)
4 verbose stack     at require (internal/module.js:20:19)
4 verbose stack     at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/tar/lib/create.js:8:13)
4 verbose stack     at Module._compile (module.js:570:32)
4 verbose stack     at Object.Module._extensions..js (module.js:579:10)
4 verbose stack     at Module.load (module.js:487:32)
4 verbose stack     at tryModuleLoad (module.js:446:12)
4 verbose stack     at Function.Module._load (module.js:438:3)
4 verbose stack     at Module.require (module.js:497:17)
4 verbose stack     at require (internal/module.js:20:19)
4 verbose stack     at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/tar/index.js:4:30)
4 verbose stack     at Module._compile (module.js:570:32)
4 verbose stack     at Object.Module._extensions..js (module.js:579:10)
4 verbose stack     at Module.load (module.js:487:32)
5 verbose cwd /Users/haolchen/Documents/__ebay__/bolt-2dot0-frontend
6 verbose Darwin 16.7.0
7 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
8 verbose node v6.11.3
9 verbose npm  v6.1.0
10 error code MODULE_NOT_FOUND
11 error Cannot find module 'fs-minipass'
12 verbose exit [ 1, true ]
```

**Comment by legodude17** [comment]
Have you tried fully reinstalling node and npm?
