### ISSUE TITLE
npm ERR! code ECONNREFUSED

### ISSUE THREAD

**Issue by neyamii** [npm/npm#20247]
#### I'm opening this issue because:

  - [1] npm is crashing.
  - [1] npm is producing an incorrect install.
  - [ ] npm is producing incorrect or undesirable behavior.
- [ ] npm is doing something I don't understand.
    - [ ] Other (_see below for feature requests_):

#### What's going wrong?
i wanted to install create-react-native-app and create-react-app

i can do nothing with npm 
please help

#### How can the CLI team reproduce the problem?

npm ERR! code ECONNREFUSED
npm ERR! errno ECONNREFUSED
npm ERR! FetchError: request to https://registry.npmjs.org/create-react-native-app failed, reason: connect ECONNREFUSED 127.0.0.1:8580
npm ERR!     at ClientRequest.req.on.err (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\node-fetch-npm\src\index.js:68:14)
npm ERR!     at emitOne (events.js:116:13)
npm ERR!     at ClientRequest.emit (events.js:211:7)
npm ERR!     at onerror (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\https-proxy-agent\node_modules\agent-base\index.js:106:9)
npm ERR!     at callbackError (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\https-proxy-agent\node_modules\agent-base\index.js:126:5)
npm ERR!     at <anonymous>
npm ERR!     at process._tickCallback (internal/process/next_tick.js:188:7)
npm ERR!  { FetchError: request to https://registry.npmjs.org/create-react-native-app failed, reason: connect ECONNREFUSED 127.0.0.1:8580
npm ERR!     at ClientRequest.req.on.err (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\node-fetch-npm\src\index.js:68:14)
npm ERR!     at emitOne (events.js:116:13)
npm ERR!     at ClientRequest.emit (events.js:211:7)
npm ERR!     at onerror (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\https-proxy-agent\node_modules\agent-base\index.js:106:9)
npm ERR!     at callbackError (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\https-proxy-agent\node_modules\agent-base\index.js:126:5)
npm ERR!     at <anonymous>
npm ERR!     at process._tickCallback (internal/process/next_tick.js:188:7)
npm ERR!   message: 'request to https://registry.npmjs.org/create-react-native-app failed, reason: connect ECONNREFUSED 127.0.0.1:8580',
npm ERR!   type: 'system',
npm ERR!   errno: 'ECONNREFUSED',
npm ERR!   code: 'ECONNREFUSED',
npm ERR!   stack: 'FetchError: request to https://registry.npmjs.org/create-react-native-app failed, reason: connect ECONNREFUSED 127.0.0.1:8580\n    at ClientRequest.req.on.err (C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\pacote\\node_modules\\make-fetch-happen\\node_modules\\node-fetch-npm\\src\\index.js:68:14)\n    at emitOne (events.js:116:13)\n    at ClientRequest.emit (events.js:211:7)\n    at onerror (C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\pacote\\node_modules\\make-fetch-happen\\node_modules\\https-proxy-agent\\node_modules\\agent-base\\index.js:106:9)\n    at callbackError (C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\pacote\\node_modules\\make-fetch-happen\\node_modules\\https-proxy-agent\\node_modules\\agent-base\\index.js:126:5)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)' }
npm ERR!
npm ERR! If you are behind a proxy, please make sure that the
npm ERR! 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\XXX\AppData\Roaming\npm-cache\_logs\2018-04-03T14_51_01_407Z-debug.log
### supporting information:

 - `npm -v` prints: 5.6.0
 - `node -v` prints: 8.11.1
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows 10
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by neyamii** [comment]
i don't use any vpn or proxy
i have another windows 10 on vmware , and npm works fine there

on my main pc it is not working
its weird
