### ISSUE TITLE
Private registry immediate E500 on `npm login`

### ISSUE THREAD

**Issue by nicholascapo** [npm/npm#20251]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

Using a private registry and a recent node/npm, `npm login` immediately returns an error.

We are using `npme` as our registry:
Version: bf817ac (441)
Date Released: Nov 13, 2017 1:22 PM

##### Command line error
```bash
$ npm login
npm ERR! code E500
npm ERR! Registry returned 500 for POST on http://npm.example.com:8080/-/v1/login: Error retrieving user data, try logging in again

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-04-03T20_29_30_662Z-debug.log
```

##### Error Log
```bash
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'login' ]
2 info using npm@5.8.0
3 info using node@v8.11.0
4 verbose npm-session c533e6e189762161
5 verbose web login before first POST
6 http request → POST http://npm.example.com:8080/-/v1/login
7 http 500 ← Internal Server Error (http://npm.example.com:8080/-/v1/login)
8 verbose stack Error: Registry returned 500 for POST on http://npm.example.com:8080/-/v1/login: Error retrieving user data, try logging in again
8 verbose stack     at fetch.defaults.catch.then.then.result (/usr/local/lib/node_modules/npm/node_modules/npm-profile/index.js:376:13)
8 verbose stack     at <anonymous>
8 verbose stack     at process._tickCallback (internal/process/next_tick.js:188:7)
9 verbose statusCode 500
10 verbose cwd /
11 verbose Linux 4.15.0-2-amd64
12 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "login"
13 verbose node v8.11.0
14 verbose npm  v5.8.0
15 error code E500
16 error Registry returned 500 for POST on http://npm.example.com:8080/-/v1/login: Error retrieving user data, try logging in again
17 verbose exit [ 1, true ]
```

Note that the error appears *before* a username prompt.

The bug can be reproduced using `node > 8.11.0` OR `npm > 5.7.1` so might actually be in a core/dependent package.

###### node 8.11.0 and npm 5.8.0

```bash
docker run -it node:8.11.0 /bin/bash -c 'echo "registry=http://npm.example.com:8080/" > ~/.npmrc && npm i -g npm@5.8.0 && npm login'
```

###### node 9.10.1 and npm 5.8.0
```bash
docker run -it node:9.10.1 /bin/bash -c 'echo "registry=http://npm.example.com:8080/" > ~/.npmrc && npm i -g npm@5.8.0 && npm login'
```

###### node 8.11.0 and npm 5.7.1:
```bash
docker run -it node:8.11.0 /bin/bash -c 'echo "registry=http://npm.example.com:8080/" > ~/.npmrc && npm i -g npm@5.6.0 && npm login'
```

###### public registry:
```bash
docker run -it node:8.11.0 /bin/bash -c 'npm i -g npm@5.8.0 && npm config list && npm login'
``` 

### supporting information:

 - `npm -v` prints: `>5.6.0` seems to be affected (see above test cases)
 - `node -v` prints: `>8.11.0` seems to be affected (see above test cases)
 - `npm config get registry` prints: `http://npm.example.com:8080/`
 - Windows, OS X/macOS, or Linux?: Linux and OSX
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by loganx510** [comment]
same for me

**Comment by bencodezen** [comment]
running into the same problem here
