### ISSUE TITLE
npm ERR! cb() never called!

### ISSUE THREAD

**Issue by luojianet** [npm/npm#20255]
```
$ npm uninstall -g vue-cli
Unhandled rejection RangeError: Maximum call stack size exceeded
    at RegExp.test (<anonymous>)
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\aproba\index.js:38:16
    at Array.forEach (<anonymous>)
    at module.exports (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\aproba\index.js:33:11)
    at flatNameFromTree (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\lib\install\flatten-tree.js:37:3)
    at flatNameFromTree (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\lib\install\flatten-tree.js:39:14)
    at flatNameFromTree (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\lib\install\flatten-tree.js:39:14)
    at flatNameFromTree (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\lib\install\flatten-tree.js:39:14)
    at flatNameFromTree (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\lib\install\flatten-tree.js:39:14)
    at flatNameFromTree (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\lib\install\flatten-tree.js:39:14)
    at flatNameFromTree (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\lib\install\flatten-tree.js:39:14)
    at flatNameFromTree (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\lib\install\flatten-tree.js:39:14)
    at flatNameFromTree (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\lib\install\flatten-tree.js:39:14)
    at flatNameFromTree (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\lib\install\flatten-tree.js:39:14)
    at flatNameFromTree (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\lib\install\flatten-tree.js:39:14)
    at flatNameFromTree (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\lib\install\flatten-tree.js:39:14)
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2018-04-04T08_05_12_276Z-debug.log
```

**Comment by luojianet** [comment]
C:\Users\Administrator\AppData\Roaming\npm\node_modules
进入这个路径，手动删除对应的文件可以解决问题。
