### ISSUE TITLE
Shasum Check Fail

### ISSUE THREAD

**Issue by Rithesh17** [npm/npm#20267]
Please help me with this:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--save',
1 verbose cli   'express' ]
2 info using npm@3.5.2
3 info using node@v4.2.6
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData express
8 silly fetchNamedPackageData express
9 silly mapToRegistry name express
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry uri https://registry.npmjs.org/express
13 verbose request uri https://registry.npmjs.org/express
14 verbose request no auth needed
15 info attempt registry request try #1 at 8:56:31 PM
16 verbose request id 44fd05370bac1ef5
17 verbose etag "5ab21ea0-94efb"
18 verbose lastModified Wed, 21 Mar 2018 8:58:08 GMT
19 http request GET https://registry.npmjs.org/express
20 http 304 https://registry.npmjs.org/express
21 verbose headers { date: 'Thu, 05 Apr 2018 15:26:33 GMT',
21 verbose headers   via: '1.1 varnish',
21 verbose headers   'cache-control': 'max-age=300',
21 verbose headers   etag: '"5ab21ea0-94efb"',
21 verbose headers   age: '9097',
21 verbose headers   connection: 'keep-alive',
21 verbose headers   'x-served-by': 'cache-lhr6335-LHR',
21 verbose headers   'x-cache': 'HIT',
21 verbose headers   'x-cache-hits': '92',
21 verbose headers   'x-timer': 'S1522941993.486401,VS0,VE0',
21 verbose headers   vary: 'Accept-Encoding, Accept' }
22 silly get cb [ 304,
22 silly get   { date: 'Thu, 05 Apr 2018 15:26:33 GMT',
22 silly get     via: '1.1 varnish',
22 silly get     'cache-control': 'max-age=300',
22 silly get     etag: '"5ab21ea0-94efb"',
22 silly get     age: '9097',
22 silly get     connection: 'keep-alive',
22 silly get     'x-served-by': 'cache-lhr6335-LHR',
22 silly get     'x-cache': 'HIT',
22 silly get     'x-cache-hits': '92',
22 silly get     'x-timer': 'S1522941993.486401,VS0,VE0',
22 silly get     vary: 'Accept-Encoding, Accept' } ]
23 verbose etag https://registry.npmjs.org/express from cache
24 verbose get saving express to /home/Rithesh/.npm/registry.npmjs.org/express/.cache.json
25 silly install normalizeTree
26 silly loadCurrentTree Finishing
27 silly loadIdealTree Starting
28 silly install loadIdealTree
29 silly cloneCurrentTree Starting
30 silly install cloneCurrentTreeToIdealTree
31 silly cloneCurrentTree Finishing
32 silly loadShrinkwrap Starting
33 silly install loadShrinkwrap
34 silly loadShrinkwrap Finishing
35 silly loadAllDepsIntoIdealTree Starting
36 silly install loadAllDepsIntoIdealTree
37 silly resolveWithNewModule express@4.16.3 checking installable status
38 silly cache add args [ 'express', null ]
39 verbose cache add spec express
40 silly cache add parsed spec Result {
40 silly cache add   raw: 'express',
40 silly cache add   scope: null,
40 silly cache add   name: 'express',
40 silly cache add   rawSpec: '',
40 silly cache add   spec: 'latest',
40 silly cache add   type: 'tag' }
41 silly addNamed express@latest
42 verbose addNamed "latest" is being treated as a dist-tag for express
43 info addNameTag [ 'express', 'latest' ]
44 silly mapToRegistry name express
45 silly mapToRegistry using default registry
46 silly mapToRegistry registry https://registry.npmjs.org/
47 silly mapToRegistry uri https://registry.npmjs.org/express
48 verbose addNameTag registry:https://registry.npmjs.org/express not in flight; fetching
49 verbose get https://registry.npmjs.org/express not expired, no request
50 silly addNameTag next cb for express with tag latest
51 silly addNamed express@4.16.3
52 verbose addNamed "4.16.3" is a plain semver version for express
53 silly mapToRegistry name express
54 silly mapToRegistry using default registry
55 silly mapToRegistry registry https://registry.npmjs.org/
56 silly mapToRegistry uri https://registry.npmjs.org/express
57 verbose addRemoteTarball https://registry.npmjs.org/express/-/express-4.16.3.tgz not in flight; adding
58 verbose addRemoteTarball [ 'https://registry.npmjs.org/express/-/express-4.16.3.tgz',
58 verbose addRemoteTarball   '6af8a502350db3246ecc4becf6b5a34d22f7ed53' ]
59 info retry fetch attempt 1 at 8:56:33 PM
60 info attempt registry request try #1 at 8:56:33 PM
61 http fetch GET https://registry.npmjs.org/express/-/express-4.16.3.tgz
62 info retry will retry, error on last attempt: Error: socket hang up
63 info attempt registry request try #2 at 8:56:44 PM
64 http fetch GET https://registry.npmjs.org/express/-/express-4.16.3.tgz
65 info retry will retry, error on last attempt: Error: socket hang up
66 info attempt registry request try #3 at 8:57:44 PM
67 http fetch GET https://registry.npmjs.org/express/-/express-4.16.3.tgz
68 http fetch 200 https://registry.npmjs.org/express/-/express-4.16.3.tgz
69 silly fetchAndShaCheck shasum 6af8a502350db3246ecc4becf6b5a34d22f7ed53
70 silly rollbackFailedOptional Starting
71 silly rollbackFailedOptional Finishing
72 silly runTopLevelLifecycles Starting
73 silly runTopLevelLifecycles Finishing
74 silly install printInstalled
75 verbose stack Error: shasum check failed for /tmp/npm-8069-cca80a13/registry.npmjs.org/express/-/express-4.16.3.tgz
75 verbose stack Expected: 6af8a502350db3246ecc4becf6b5a34d22f7ed53
75 verbose stack Actual:   87bde052a954d0c14be914e8e93c3563cf9e1066
75 verbose stack From:     https://registry.npmjs.org/express/-/express-4.16.3.tgz
75 verbose stack     at /usr/share/npm/node_modules/sha/index.js:25:8
75 verbose stack     at ReadStream.<anonymous> (/usr/share/npm/node_modules/sha/index.js:72:7)
75 verbose stack     at emitNone (events.js:72:20)
75 verbose stack     at ReadStream.emit (events.js:166:7)
75 verbose stack     at endReadableNT (_stream_readable.js:905:12)
75 verbose stack     at nextTickCallbackWith2Args (node.js:441:9)
75 verbose stack     at process._tickCallback (node.js:355:17)
76 verbose cwd /home/Rithesh/Chatbox
77 error Linux 4.4.0-116-generic
78 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "--save" "express"
79 error node v4.2.6
80 error npm  v3.5.2
81 error shasum check failed for /tmp/npm-8069-cca80a13/registry.npmjs.org/express/-/express-4.16.3.tgz
81 error Expected: 6af8a502350db3246ecc4becf6b5a34d22f7ed53
81 error Actual:   87bde052a954d0c14be914e8e93c3563cf9e1066
81 error From:     https://registry.npmjs.org/express/-/express-4.16.3.tgz
82 error If you need help, you may report this error at:
82 error     <https://github.com/npm/npm/issues>
83 verbose exit [ 1, true ]

**Comment by marvin-SL** [comment]
Suddently happened to me yesterday with another package. Did you tried to do another npm install today ? this morning everything was fine for me, maybe a network issue caused the shasum error while downloading the package
