### ISSUE TITLE
Can't run npm install due to permission problems

### ISSUE THREAD

**Issue by arnoldbird** [npm/npm#20277]
#### I'm opening this issue because:

  - [ x] npm is doing something I don't understand.

#### What's going wrong?

When I try to install a module, npm suggests there is a permissions problem in the cache...

```
npm ERR! Command failed: /usr/local/bin/git clone -q https://github.com/react-native-material-design/react-native-material-design-styles.git /var/root/.npm/_cacache/tmp/git-clone-86071250
npm ERR! fatal: could not create leading directories of '/var/root/.npm/_cacache/tmp/git-clone-86071250': Permission denied
```

I have tried the following solutions to no avail:

- npm cache clear --force
- npm cache verify
- Recursively setting 777 perms in /var/root/.npm.
- Recursively changing ownership of /var/root/.npm

#### How can the CLI team reproduce the problem?

Not sure.

### supporting information:

 - `npm -v` prints: 5.6.0
 - `node -v` prints: v9.11.1
 - `npm config get registry` prints: https://registry.npmjs.org/
 -  macOS

**Comment by Saibamen** [comment]
Could you update NPM and your GIT?

**Comment by KayDee** [comment]
Tried using sudo ?

**Comment by arnoldbird** [comment]
I am actually not using the react-native-material-design library anymore.  So I'm not having the issue.  I don't otherwise have any issue.  I did just try installing react-native-material-design just now, just to see if there's still an issue, and got an error.  The debug log is huge but here is the end of it, in case it's of interest...

12 silly saveTree │ │ └── uuid@3.0.1
12 silly saveTree │ ├─┬ xmldoc@0.4.0
12 silly saveTree │ │ └── sax@1.1.6
12 silly saveTree │ └── yargs@9.0.1
12 silly saveTree ├─┬ react-navigation@1.5.2
12 silly saveTree │ ├── clamp@1.0.1
12 silly saveTree │ ├─┬ path-to-regexp@1.7.0
12 silly saveTree │ │ └── isarray@0.0.1
12 silly saveTree │ ├─┬ react-native-drawer-layout-polyfill@1.3.2
12 silly saveTree │ │ └─┬ react-native-drawer-layout@1.3.2
12 silly saveTree │ │   └── react-native-dismiss-keyboard@1.0.0
12 silly saveTree │ ├── react-native-safe-area-view@0.7.0
12 silly saveTree │ └── react-native-tab-view@0.0.74
12 silly saveTree ├── react-test-renderer@16.2.0
12 silly saveTree ├── react@16.3.1
12 silly saveTree └─┬ tcomb-form-native@0.6.11
12 silly saveTree   └─┬ tcomb-validation@3.4.1
12 silly saveTree     └── tcomb@3.2.25
13 verbose stack SyntaxError: Unexpected token a in JSON at position 0
13 verbose stack     at JSON.parse (<anonymous>)
13 verbose stack     at module.exports (/usr/local/lib/node_modules/npm/lib/utils/parse-json.js:3:15)
13 verbose stack     at BB.join (/usr/local/lib/node_modules/npm/lib/install/read-shrinkwrap.js:31:20)
13 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
13 verbose stack     at Holder$3._callFunction (eval at generateHolderClass (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/join.js:92:16), <anonymous>:14:44)
13 verbose stack     at Holder$3.checkFulfillment (eval at generateHolderClass (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/join.js:92:16), <anonymous>:29:30)
13 verbose stack     at Promise.eval (eval at thenCallback (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/join.js:14:16), <anonymous>:6:20)
13 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:566:21)
13 verbose stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
13 verbose stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
13 verbose stack     at Promise._fulfill (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:638:18)
13 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:582:21)
13 verbose stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
13 verbose stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
13 verbose stack     at Promise._fulfill (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:638:18)
13 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/nodeback.js:42:21
14 verbose cwd /Users/me/at/app/src/components
15 verbose Darwin 17.5.0
16 verbose argv "/usr/local/Cellar/node/9.11.1/bin/node" "/usr/local/bin/npm" "i" "react-native-material-design" "--save"
17 verbose node v9.11.1
18 verbose npm  v5.6.0
19 error Unexpected token a in JSON at position 0
20 verbose exit [ 1, true ]
