### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by rupesh2017** [npm/npm#20286]
npm start
(there is no striked text)
I am not able to run any more command after this.( I had run npm run build ,but could not)

```
> victor-hugo@1.0.0 start /home/greenseek/Desktop/hugo-restaurant-tutorial
> gulp server

[13:08:52] Failed to load external module @babel/register
[13:08:52] Requiring external module babel-register
[13:08:53] Using gulpfile /home/greenseek/Desktop/hugo-restaurant-tutorial/gulpfile.babel.js
[13:08:53] Starting 'hugo'...
[13:08:53] Starting 'css'...
INFO 2018/04/08 13:08:53 Using config file: 
INFO 2018/04/08 13:08:53 /home/greenseek/Desktop/hugo-restaurant-tutorial/site/static/ is the only static directory available to sync from
INFO 2018/04/08 13:08:53 syncing static files to /home/greenseek/Desktop/hugo-restaurant-tutorial/dist/
WARN 2018/04/08 13:08:53 No translation bundle found for default language "en"
WARN 2018/04/08 13:08:53 Translation func for language en not found, use default.
WARN 2018/04/08 13:08:53 i18n not initialized, check that you have language file (in i18n) that matches the site language or the default language.
[13:08:53] Starting 'js'...
Started building sites ...
INFO 2018/04/08 13:08:53 found taxonomies: map[string]string{"category":"categories", "tag":"tags"}
WARN 2018/04/08 13:08:53 [en] Unable to locate layout for "taxonomyTerm": [taxonomy/category.terms.en.html.html taxonomy/category.terms.html.html taxonomy/category.terms.en.html taxonomy/category.terms.html _default/terms.en.html.html _default/terms.html.html _default/terms.en.html _default/terms.html indexes/indexes.en.html.html indexes/indexes.html.html indexes/indexes.en.html indexes/indexes.html theme/taxonomy/category.terms.en.html.html theme/taxonomy/category.terms.html.html theme/taxonomy/category.terms.en.html theme/taxonomy/category.terms.html theme/_default/terms.en.html.html theme/_default/terms.html.html theme/_default/terms.en.html theme/_default/terms.html theme/indexes/indexes.en.html.html theme/indexes/indexes.html.html theme/indexes/indexes.en.html theme/indexes/indexes.html]
WARN 2018/04/08 13:08:53 [en] Unable to locate layout for "taxonomyTerm": [taxonomy/tag.terms.en.html.html taxonomy/tag.terms.html.html taxonomy/tag.terms.en.html taxonomy/tag.terms.html _default/terms.en.html.html _default/terms.html.html _default/terms.en.html _default/terms.html indexes/indexes.en.html.html indexes/indexes.html.html indexes/indexes.en.html indexes/indexes.html theme/taxonomy/tag.terms.en.html.html theme/taxonomy/tag.terms.html.html theme/taxonomy/tag.terms.en.html theme/taxonomy/tag.terms.html theme/_default/terms.en.html.html theme/_default/terms.html.html theme/_default/terms.en.html theme/_default/terms.html theme/indexes/indexes.en.html.html theme/indexes/indexes.html.html theme/indexes/indexes.en.html theme/indexes/indexes.html]
Built site for language en:
0 draft content
0 future content
0 expired content
1 regular pages created
8 other pages created
0 non-page files copied
0 paginator pages created
0 tags created
0 categories created
total in 6 ms
[13:08:53] Starting 'videos'...
[13:08:53] Starting 'images'...
[13:08:53] Finished 'hugo' after 104 ms
[13:08:53] Finished 'css' after 213 ms
[13:08:55] Finished 'videos' after 2.36 s
[13:08:55] Finished 'images' after 2.62 s
[13:08:55] [webpack] Hash: 4a59a05dbac487af6ab6
Version: webpack 1.15.0
Time: 2634ms
 Asset     Size  Chunks             Chunk Names
app.js  1.95 kB       0  [emitted]  app
cms.js  3.61 MB       1  [emitted]  cms
chunk    {0} app.js (app) 455 bytes [rendered]
    [0] multi app 28 bytes {0} [built]
    [1] ./src/js/app.js 427 bytes {0} [built]
chunk    {1} cms.js (cms) 3.59 MB [rendered]
    [0] multi cms 28 bytes {1} [built]
    [2] ./src/js/cms.js 859 bytes {1} [built]
    [3] ./~/netlify-cms/dist/cms.js 3.39 MB {1} [built]
    [4] ./~/timers-browserify/main.js 1.9 kB {1} [built]
    [5] ./~/setimmediate/setImmediate.js 6.47 kB {1} [built]
    [6] ./~/process/browser.js 5.42 kB {1} [built]
    [7] ./src/js/cms/food-preview.js 3.82 kB {1} [built]
    [8] ./~/react/react.js 56 bytes {1} [built]
    [9] ./~/react/lib/React.js 4.96 kB {1} [built]
   [10] ./~/object-assign/index.js 2.11 kB {1} [built]
   [11] ./~/react/lib/ReactBaseClasses.js 5.31 kB {1} [built]
   [12] ./~/react/lib/reactProdInvariant.js 1.11 kB {1} [built]
   [13] ./~/react/lib/ReactNoopUpdateQueue.js 3.24 kB {1} [built]
   [14] ./~/fbjs/lib/warning.js 1.9 kB {1} [built]
   [15] ./~/fbjs/lib/emptyFunction.js 959 bytes {1} [built]
   [16] ./~/react/lib/canDefineProperty.js 539 bytes {1} [built]
   [17] ./~/fbjs/lib/emptyObject.js 332 bytes {1} [built]
   [18] ./~/fbjs/lib/invariant.js 1.51 kB {1} [built]
   [19] ./~/react/lib/lowPriorityWarning.js 2.04 kB {1} [built]
   [20] ./~/react/lib/ReactChildren.js 6.07 kB {1} [built]
   [21] ./~/react/lib/PooledClass.js 3.23 kB {1} [built]
   [22] ./~/react/lib/ReactElement.js 11.1 kB {1} [built]
   [23] ./~/react/lib/ReactCurrentOwner.js 499 bytes {1} [built]
   [24] ./~/react/lib/ReactElementSymbol.js 500 bytes {1} [built]
   [25] ./~/react/lib/traverseAllChildren.js 6.91 kB {1} [built]
   [26] ./~/react/lib/getIteratorFn.js 997 bytes {1} [built]
   [27] ./~/react/lib/KeyEscapeUtils.js 1.17 kB {1} [built]
   [28] ./~/react/lib/ReactDOMFactories.js 5.36 kB {1} [built]
   [29] ./~/react/lib/ReactElementValidator.js 9.08 kB {1} [built]
   [30] ./~/react/lib/ReactComponentTreeHook.js 11.7 kB {1} [built]
   [31] ./~/react/lib/checkReactTypeSpec.js 4.07 kB {1} [built]
   [32] ./~/react/lib/ReactPropTypeLocationNames.js 450 bytes {1} [built]
   [33] ./~/react/lib/ReactPropTypesSecret.js 320 bytes {1} [built]
   [34] ./~/react/lib/ReactPropTypes.js 378 bytes {1} [built]
   [35] ./~/prop-types/factory.js 768 bytes {1} [built]
   [36] ./~/prop-types/factoryWithTypeCheckers.js 19.8 kB {1} [built]
   [37] ./~/prop-types/lib/ReactPropTypesSecret.js 314 bytes {1} [built]
   [38] ./~/prop-types/checkPropTypes.js 2.87 kB {1} [built]
   [39] ./~/react/lib/ReactVersion.js 228 bytes {1} [built]
   [40] ./~/react/lib/createClass.js 566 bytes {1} [built]
   [41] ./~/create-react-class/factory.js 29.8 kB {1} [built]
   [42] ./~/react/lib/onlyChild.js 1.22 kB {1} [built]
   [43] ./~/date-fns/format/index.js 10.1 kB {1} [built]
   [44] ./~/date-fns/get_day_of_year/index.js 755 bytes {1} [built]
   [45] ./~/date-fns/parse/index.js 8.31 kB {1} [built]
   [46] ./~/date-fns/is_date/index.js 456 bytes {1} [built]
   [47] ./~/date-fns/start_of_year/index.js 733 bytes {1} [built]
   [48] ./~/date-fns/difference_in_calendar_days/index.js 1.43 kB {1} [built]
   [49] ./~/date-fns/start_of_day/index.js 644 bytes {1} [built]
   [50] ./~/date-fns/get_iso_week/index.js 1.08 kB {1} [built]
   [51] ./~/date-fns/start_of_iso_week/index.js 752 bytes {1} [built]
   [52] ./~/date-fns/start_of_week/index.js 1.25 kB {1} [built]
   [53] ./~/date-fns/start_of_iso_year/index.js 1.05 kB {1} [built]
   [54] ./~/date-fns/get_iso_year/index.js 1.41 kB {1} [built]
   [55] ./~/date-fns/is_valid/index.js 865 bytes {1} [built]
   [56] ./~/date-fns/locale/en/index.js 310 bytes {1} [built]
   [57] ./~/date-fns/locale/en/build_distance_in_words_locale/index.js 1.88 kB {1} [built]
   [58] ./~/date-fns/locale/en/build_format_locale/index.js 2.88 kB {1} [built]
   [59] ./~/date-fns/locale/_lib/build_formatting_tokens_reg_exp/index.js 711 bytes {1} [built]
   [60] ./src/js/cms/drink-preview.js 3.65 kB {1} [built]
   [61] ./src/js/cms/gallery-preview.js 2.96 kB {1} [built]
[13:08:55] Finished 'js' after 2.66 s
[13:08:55] Starting 'server'...
[13:08:55] Finished 'server' after 42 ms
[Browsersync] Access URLs:
 --------------------------------------
       Local: http://localhost:3000
    External: http://192.168.1.100:3000
 --------------------------------------
          UI: http://localhost:3001
 UI External: http://192.168.1.100:3001
 --------------------------------------
[Browsersync] Serving files from: ./dist
[Browsersync] Couldn't open browser (if you are using BrowserSync in a headless environment, you might want to set the open option to false)
npm run build       

```

**Comment by rupesh2017** [comment]
I don't know what change i made but now

```
npm start

> victor-hugo@1.0.0 start /home/greenseek/Desktop/hugo-restaurant-tutorial
> gulp server

[20:59:02] Failed to load external module @babel/register
[20:59:02] Requiring external module babel-register
assert.js:42
  throw new errors.AssertionError({
  ^

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (/home/greenseek/Desktop/hugo-restaurant-tutorial/node_modules/undertaker/lib/set-task.js:10:3)
    at Gulp.task (/home/greenseek/Desktop/hugo-restaurant-tutorial/node_modules/undertaker/lib/task.js:13:8)
    at Object.<anonymous> (/home/greenseek/Desktop/hugo-restaurant-tutorial/gulpfile.babel.js:22:6)
    at Module._compile (module.js:652:30)
    at loader (/home/greenseek/Desktop/hugo-restaurant-tutorial/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/greenseek/Desktop/hugo-restaurant-tutorial/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at execute (/home/greenseek/Desktop/hugo-restaurant-tutorial/node_modules/gulp/node_modules/gulp-cli/lib/versioned/^4.0.0/index.js:36:18)
    at Liftoff.handleArguments (/home/greenseek/Desktop/hugo-restaurant-tutorial/node_modules/gulp/node_modules/gulp-cli/index.js:175:63)
    at Liftoff.execute (/home/greenseek/Desktop/hugo-restaurant-tutorial/node_modules/liftoff/index.js:203:12)
    at module.exports (/home/greenseek/Desktop/hugo-restaurant-tutorial/node_modules/flagged-respawn/index.js:51:3)
    at Liftoff.<anonymous> (/home/greenseek/Desktop/hugo-restaurant-tutorial/node_modules/liftoff/index.js:195:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! victor-hugo@1.0.0 start: `gulp server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the victor-hugo@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```
