### ISSUE TITLE
During npm start i am facing this error

### ISSUE THREAD

**Issue by BhanuSingamsetty** [npm/npm#20280]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\myProject\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\myProject\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.10.10
3 info using node@v6.11.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle react_app@1.0.0~prestart: react_app@1.0.0
6 silly lifecycle react_app@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle react_app@1.0.0~start: react_app@1.0.0
8 verbose lifecycle react_app@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle react_app@1.0.0~start: PATH: C:\Program Files\nodejs\myProject\node_modules\npm\bin\node-gyp-bin;C:\Users\Bhanu\react_app\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x86;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x64;C:\Program Files (x86)\Brackets\command;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\nodejs\myProject\;C:\Program Files\Git\cmd;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Users\Bhanu\AppData\Roaming\npm;C:\Program Files\Microsoft VS Code\bin
10 verbose lifecycle react_app@1.0.0~start: CWD: C:\Users\Bhanu\react_app
11 silly lifecycle react_app@1.0.0~start: Args: [ '/d /s /c', 'webpack-dev-server --hot' ]
12 silly lifecycle react_app@1.0.0~start: Returned: code: 1  signal: null
13 info lifecycle react_app@1.0.0~start: Failed to exec start script
14 verbose stack Error: react_app@1.0.0 start: `webpack-dev-server --hot`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\myProject\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\myProject\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:891:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid react_app@1.0.0
16 verbose cwd C:\Users\Bhanu\react_app
17 error Windows_NT 6.1.7601
18 error argv "C:\\Program Files\\nodejs\\myProject\\node.exe" "C:\\Program Files\\nodejs\\myProject\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v6.11.2
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error react_app@1.0.0 start: `webpack-dev-server --hot`
22 error Exit status 1
23 error Failed at the react_app@1.0.0 start script 'webpack-dev-server --hot'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the react_app package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     webpack-dev-server --hot
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs react_app
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls react_app
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by Saibamen** [comment]
Please update NPM and NodeJS
