### ISSUE TITLE
npm ERR! const Hoek = require('hoek');

### ISSUE THREAD

**Issue by lowrisk75** [npm/npm#20310]
I ran sudo npm i -g npm, but since I keep having this error

sudo npm install -g node-dht-sensor
ERROR: npm is known not to run on Node.js v4.0.0
Node.js 4 is supported but the specific version you're running has
a bug known to break npm. Please update to at least 4.7.0 to use this
version of npm. You can find the latest release of Node.js at https://nodejs.org/
I tried curl

 -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
sudo apt-get -y install nodejs
sudo apt-get -y install libicu-dev
but still the same issue

I did a system update / upgrade / reboot, I have now this error :

sudo npm install -g node-dht-sensor
/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/node_modules/cryptiles/node_modules/boom/lib/index.js:5
const Hoek = require('hoek');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/node_modules/cryptiles/lib/index.js:4:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
npm ERR! Linux 4.14.30-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "node-dht-sensor"
npm ERR! node v0.12.6
npm ERR! npm  v2.11.2

npm ERR! /usr/local/lib/node_modules/npm/node_modules/request/node_modules/hawk/node_modules/cryptiles/node_modules/boom/lib/index.js:5
npm ERR! const Hoek = require('hoek');
npm ERR! ^^^^^
npm ERR! Use of const in strict mode.
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by kenany** [comment]
```
npm ERR! node v0.12.6
npm ERR! npm v2.11.2
```
These are very old, I suggest you retry updating Node.js and `npm`, because apparently you somehow went backwards 😆

**Comment by lowrisk75** [comment]
I try many thing but still stuck : 

pi@raspberrypi:~ $ apt list -a nodejs
Listing... Done
nodejs/unknown,now 9.11.1-1nodesource1 armhf [installed]
nodejs/stable 4.8.2~dfsg-1 armhf


--
curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -

## Installing the NodeSource Node.js v9.x repo...


## Populating apt-get cache...

+ apt-get update
Hit:1 http://archive.raspberrypi.org/debian stretch InRelease
Get:2 http://raspbian.raspberrypi.org/raspbian stretch InRelease [15.0 kB]
Hit:3 https://deb.nodesource.com/node_9.x stretch InRelease
Get:4 https://download.docker.com/linux/raspbian stretch InRelease [15.3 kB]
Fetched 30.3 kB in 4s (6,648 B/s)                  
Reading package lists... Done

## Confirming "stretch" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_9.x/dists/stretch/Release'

## Adding the NodeSource signing key to your keyring...

+ curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
OK

## Creating apt sources list file for the NodeSource Node.js v9.x repo...

+ echo 'deb https://deb.nodesource.com/node_9.x stretch main' > /etc/apt/sources.list.d/nodesource.list
+ echo 'deb-src https://deb.nodesource.com/node_9.x stretch main' >> /etc/apt/sources.list.d/nodesource.list

## Running `apt-get update` for you...

+ apt-get update
Hit:1 http://raspbian.raspberrypi.org/raspbian stretch InRelease
Hit:2 http://archive.raspberrypi.org/debian stretch InRelease
Hit:3 https://deb.nodesource.com/node_9.x stretch InRelease
Hit:4 https://download.docker.com/linux/raspbian stretch InRelease
Reading package lists... Done

## Run `apt-get install nodejs` (as root) to install Node.js v9.x and npm

```
sudo apt-get install nodejs
Reading package lists... Done
Building dependency tree       
Reading state information... Done
nodejs is already the newest version (9.11.1-1nodesource1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
pi@raspberrypi:~ $ node -v
v0.12.6

```
