### ISSUE TITLE
npm ERR! code EPROTO

### ISSUE THREAD

**Issue by WebKieth** [npm/npm#20321]
after npm install (globally, locally - no matter) the same error
npm ERR! code EPROTO
npm ERR! errno EPROTO
npm ERR! request to https://registry.npmjs.org/npm failed, reason: write EPROTO 140381372901184:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/casper/.npm/_logs/2018-04-12T16_17_14_376Z-debug.log

logfile:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'i', 'npm', '-g' ]
2 info using npm@5.6.0
3 info using node@v8.11.1
4 verbose npm-session 2310848b4ab312ae
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData error for npm@latest request to https://registry.npmjs.org/npm failed, reason: write EPROTO 140381372901184:error:140770FC:SSL routines:SSL23_GET_SERVER_H$
8 verbose type system
9 verbose stack FetchError: request to https://registry.npmjs.org/npm failed, reason: write EPROTO 140381372901184:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:$
9 verbose stack
9 verbose stack     at ClientRequest.req.on.err (/usr/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/src/index.js:68:14)
9 verbose stack     at emitOne (events.js:116:13)
9 verbose stack     at ClientRequest.emit (events.js:211:7)
9 verbose stack     at onerror (/usr/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/https-proxy-agent/node_modules/agent-base/index.js:106:9)
9 verbose stack     at callbackError (/usr/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/https-proxy-agent/node_modules/agent-base/index.js:126:$
9 verbose stack     at <anonymous>
10 verbose cwd /home/casper
11 verbose Linux 4.13.0-38-generic
12 verbose argv "/usr/bin/node" "/usr/bin/npm" "i" "npm" "-g"
13 verbose node v8.11.1
14 verbose npm  v5.6.0
15 error code EPROTO
16 error errno EPROTO
17 error request to https://registry.npmjs.org/npm failed, reason: write EPROTO 140381372901184:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/ope$
18 verbose exit [ 1, true ]

Try to purge, reinstall, update - it didnt help

**Comment by WebKieth** [comment]
Ok, l solve it. GUI ubuntu havent got data about proxy, but /etc/environmens has

**Comment by ziagithub2018** [comment]
dear @WebKieth I have the same problem while running 'npm install -g ionic@latest', I couldn't understand your solution
I'm using windows 10 in the network which server running ubuntu 16
can you please explain
thank you

**Comment by ghost** [comment]
Dear @WebKieth I have the same problem while installing ionic 'npm install -g ionic@latest'
I couldn't get your solution, can you please explain it
in my desktop running windows 10,  I'm in a network which ubuntu 16 running on the server
I'm behind proxy, and set proxy setting like:

$ npm config set proxy http://<username>:<password>@<proxy-server-url>:<port>
$ npm config set https-proxy http://<username>:<password>@<proxy-server-url>:<port>

please tell me what to do
thanks,
zia

**Comment by WebKieth** [comment]
@ziagithub2018 hi.
I could set your same as npm config proxy address into your /etc/environments file (sudo nano /etc/environments/)
This is an examples from ubuntu wiki docs:
```
https_proxy="https://user:pass@proxy:port/" 
http_proxy="http://user:pass@proxy:port/"
ftp_proxy="ftp://user:pass@proxy:port/"
socks_proxy="socks://user:pass@proxy:port/"
```
It can helps.
But i, conversely, didnt need proxy for npm, but setted it on some time for ubuntu, so npm without synchronic proxy config returned errors for me
