### ISSUE TITLE
npm install fails on Windows, because of Python

### ISSUE THREAD

**Issue by Nefcanto** [npm/npm#20335]
Hi

This is my environment:

[Windows 10 version 1709 Version 1709 (Fall Creators Update)](https://en.wikipedia.org/wiki/Windows_10_version_history)
x64 OS and Software
Node.js v.8.9.4
npm 5.6.0

I cloned [Foundation template](https://github.com/zurb/foundation-sites-template), and ran `npm install`. An error occurred:

`gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Users\saeed\AppData\Local\Programs\Python\Python36\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Temp\projectname\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Temp\projectname\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Temp\projectname\node_modules\node-gyp\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Temp\\projectname\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Temp\projectname\node_modules\node-sass
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok`

I downloaded [Python for windows](https://www.python.org/ftp/python/3.7.0/python-3.7.0b3-amd64.exe) manually, and installed it. Then I created these Environment Variables:

**PYTHON_HOME**  **C:\Users\saeed\AppData\Local\Programs\Python\Python36**
**PYTHON**  **C:\Users\saeed\AppData\Local\Programs\Python\Python36\python.exe**

Then extended `Path` to include `%PYTHON_HOME%` too. And made sure that python is truly recognized in `Path` environment variable by launching a command line terminal and executing `python`. It worked.

Then again I tried `npm install` and again that ugly error is showing. I also tried `npm start` and it complained that `Error: Cannot find module 'node-sass'`.

Any ideas?

PS: I have Angular applications that work just fine. They have SASS and they're working just fine.

**Comment by David-OConnor** [comment]
Same. #1: Not sure why I need Python. #2: I have Python 3.6 in my system path and use it regularly.
