### ISSUE TITLE
Error throwing when setting up RAML documentation

### ISSUE THREAD

**Issue by senthilps** [npm/npm#20376]
#### I'm opening this issue because:

  
  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [x] npm is producing incorrect or undesirable behavior.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?

I tried to setup a RAML documentation in my local machine.  When building, it is throwing the error. 

#### How can the CLI team reproduce the problem?

This is an error that occurred in my local installation.  I am attaching the error log.

[2018-04-13T06_23_10_858Z-debug.log](https://github.com/npm/npm/files/1927900/2018-04-13T06_23_10_858Z-debug.log)

**Comment by senthilps** [comment]
This is the error i got at command line.

```

> api-doc@1.0.0 build-html:admin-ui C:\Users\Lakky69\raml\dev-tools\api-doc
> npm-run raml2html admin-ui/index.raml -o  dist/admin-ui.html

Error: spawn raml2html ENOENT
    at exports._errnoException (util.js:1020:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:197:32)
    at onErrorNT (internal/child_process.js:376:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:502:3
npm ERR! code ELIFECYCLE
npm ERR! errno 4294963238
npm ERR! api-doc@1.0.0 build-html:admin-ui: `npm-run raml2html admin-ui/index.raml -o  dist/admin-ui.html`
npm ERR! Exit status 4294963238
npm ERR!
npm ERR! Failed at the api-doc@1.0.0 build-html:admin-ui script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Lakky69\AppData\Roaming\npm-cache\_logs\2018-04-19T11_18_35_139Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 4294963238
npm ERR! api-doc@1.0.0 build:admin-ui: `npm run build-html:admin-ui && npm run build-md:admin-ui`
npm ERR! Exit status 4294963238
npm ERR!
npm ERR! Failed at the api-doc@1.0.0 build:admin-ui script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Lakky69\AppData\Roaming\npm-cache\_logs\2018-04-19T11_18_35_208Z-debug.log
```

**Comment by kenany** [comment]
Can you try running:

```
npm install raml2html
```

and then try your command again?

**Comment by senthilps** [comment]
I installed raml2html and ran the script.  I am still getting the error.

I feel the problem is with npm-run .   
npm-run raml2html ecart-static-ui/index.raml -o  dist/ecart-static-ui.html

If i run above without npm-run, it works fine.

raml2html ecart-static-ui/index.raml -o  dist/ecart-static-ui.html

---------------


```
> api-doc@1.0.0 build-html:ecart-static-ui C:\Users\Lakky69\ecart\dev-tools\api-doc
> npm-run raml2html ecart-static-ui/index.raml -o  dist/ecart-static-ui.html
Error: spawn raml2html ENOENT
    at exports._errnoException (util.js:1020:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:197:32)
    at onErrorNT (internal/child_process.js:376:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:502:3
npm ERR! code ELIFECYCLE
npm ERR! errno 4294963238
npm ERR! api-doc@1.0.0 build-html:ecart-static-ui: `npm-run raml2html ecart-static-ui/index.raml -o  dist/ecart-static-ui.html`
npm ERR! Exit status 4294963238
npm ERR!
npm ERR! Failed at the api-doc@1.0.0 build-html:ecart-static-ui script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Lakky69\AppData\Roaming\npm-cache\_logs\2018-04-20T09_43_34_743Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 4294963238
npm ERR! api-doc@1.0.0 build:ecart-static-ui: `npm run build-html:ecart-static-ui && npm run build-md:ecart-static-ui`
npm ERR! Exit status 4294963238
npm ERR!
npm ERR! Failed at the api-doc@1.0.0 build:ecart-static-ui script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Lakky69\AppData\Roaming\npm-cache\_logs\2018-04-20T09_43_34_806Z-debug.log
```

**Comment by kenany** [comment]
Perhaps you should bring this up with the [npm-run](https://github.com/timoxley/npm-run) developers.

**Comment by senthilps** [comment]
Thanks.  I will post this issue there.
