### ISSUE TITLE
npm install produces errors (npm-debug.log file and package-json attached)

### ISSUE THREAD

**Issue by ashwinkodialbail** [npm/npm#20393]
#### I'm opening this issue because:

  - [X] npm is crashing.
  - [X] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

I tried to do npm install and I get a few error messages (as listed in npm-debug.log file). I have also attached the error message when I tried to deploy the software on AWS Elastic Beanstalk‎. Could you please assist me? I have been trying to solve this problem for over 48 hours now. Any help is greatly appreciated.  

Supporting information:

 - `npm -v` prints: 5.6.0
 - `node -v` prints: v6.9.4
 - `npm config get registry` prints: https://registry.npmjs.org/
 -  Windows, OS X/macOS, or Linux?: OS X/macOS

npm-debug.log file

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@3.10.10
3 info using node@v6.9.4
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle Elastic-Beanstalk-Sample-App@0.0.1~prestart: Elastic-Beanstalk-Sample-App@0.0.1
6 silly lifecycle Elastic-Beanstalk-Sample-App@0.0.1~prestart: no script for prestart, continuing
7 info lifecycle Elastic-Beanstalk-Sample-App@0.0.1~start: Elastic-Beanstalk-Sample-App@0.0.1
8 verbose lifecycle Elastic-Beanstalk-Sample-App@0.0.1~start: unsafe-perm in lifecycle true
9 verbose lifecycle Elastic-Beanstalk-Sample-App@0.0.1~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/ashwinkodialbail/Desktop/Fundpnb/fundpnb-server/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
10 verbose lifecycle Elastic-Beanstalk-Sample-App@0.0.1~start: CWD: /Users/ashwinkodialbail/Desktop/Fundpnb/fundpnb-server
11 silly lifecycle Elastic-Beanstalk-Sample-App@0.0.1~start: Args: [ '-c', 'NODE_ENV=development node app.js' ]
12 silly lifecycle Elastic-Beanstalk-Sample-App@0.0.1~start: Returned: code: 1  signal: null
13 info lifecycle Elastic-Beanstalk-Sample-App@0.0.1~start: Failed to exec start script
14 verbose stack Error: Elastic-Beanstalk-Sample-App@0.0.1 start: `NODE_ENV=development node app.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid Elastic-Beanstalk-Sample-App@0.0.1
16 verbose cwd /Users/ashwinkodialbail/Desktop/Fundpnb/fundpnb-server
17 error Darwin 16.7.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
19 error node v6.9.4
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error Elastic-Beanstalk-Sample-App@0.0.1 start: `NODE_ENV=development node app.js`
22 error Exit status 1
23 error Failed at the Elastic-Beanstalk-Sample-App@0.0.1 start script 'NODE_ENV=development node app.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the Elastic-Beanstalk-Sample-App package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     NODE_ENV=development node app.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs Elastic-Beanstalk-Sample-App
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls Elastic-Beanstalk-Sample-App
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

Error message when I tried to deploy to AWS Elastic Beanstalk‎:

Ashwins-MacBook-Pro:fundpnb-server ashwinkodialbail$ eb deploy
Creating application version archive "app-17b28-180420_170800".
Uploading iFund-Server/app-17b28-180420_170800.zip to S3. This may take a while.
Upload Complete.
INFO: Environment update is starting.                               
INFO: Deploying new version to instance(s).                         
ERROR: Failed to run npm install. Snapshot logs for more details.   
ERROR: [Instance: i-09076b2a6ab8970b6] Command failed on instance. Return code: 1 Output: (TRUNCATED).../opt/elasticbeanstalk/containerfiles/ebnode.py", line 180, in npm_install
    raise e
subprocess.CalledProcessError: Command '['/opt/elasticbeanstalk/node-install/node-v6.11.5-linux-x64/bin/npm', '--production', 'install']' returned non-zero exit status 1. 
Hook /opt/elasticbeanstalk/hooks/appdeploy/pre/50npm.sh failed. For more detail, check /var/log/eb-activity.log using console or EB CLI.
INFO: Command execution completed on all instances. Summary: [Successful: 0, Failed: 1].
ERROR: Unsuccessful command execution on instance id(s) 'i-09076b2a6ab8970b6'. Aborting the operation.
ERROR: Failed to deploy application.      
                          
Package-Json:
{
  "name": "Elastic-Beanstalk-Sample-App",
  "version": "0.0.1",
  "private": true,
  "dependencies": {
    "apiai": "^4.0.3",
    "apn": "^2.1.4",
    "aws-sdk": "^2.43.0",
    "body-parser": "^1.16.0",
    "compromise": "^11.2.3",
    "crypto": "0.0.3",
    "express": "^4.14.1",
    "fs": "0.0.2",
    "json2csv": "^3.11.5",
    "json2xls": "^0.1.2",
    "jsonwebtoken": "^7.2.1",
    "jwk-to-pem": "^1.2.6",
    "mailgun-js": "^0.13.1",
    "moment": "^2.18.1",
    "moment-range": "^3.0.3", 
    "mongodb": "^2.2.22",
    "mongodb_s3_backup": "0.0.8",
    "natural": "^0.5.6",
    "node-quickbooks": "^2.0.16",
    "node-schedule": "^1.2.1",
    "numeral": "^2.0.6",
    "phantom-html-to-pdf": "^0.5.0",
    "phantomjs-prebuilt": "^2.1.14",
    "plaid": "^2.0.4",
    "pug": "^2.0.3",
    "pug-pdf": "^0.1.1",
    "ramda": "^0.24.1",
    "request": "^2.79.0",
    "sjcl": "^1.0.6",
    "stripe": "^4.15.0",
    "twilio": "^2.11.1",
    "xero-node": "^2.4.0",
    "xlsx": "^0.12.2",
    "zip-folder": "^1.0.0"
  },
  "scripts": {
    "start": "NODE_ENV=development node app.js"
  }
}

**Comment by the-spyke** [comment]
You've specified `npm@5.6.0`, but the log says `2 info using npm@3.10.10`

**Comment by ashwinkodialbail** [comment]
Yeah. That’s right. When I did a npm -v I get 5.6.0. The npm-debug file says otherwise(3.10.10). 
*It’s early days for me in this, and I’m still not quite at ease with npm.
