### ISSUE TITLE
network request to http://registry.npmjs.org/@angular%2fanimations failed, reason: connect ETIMEDOUT 151.101.44.162:80

### ISSUE THREAD

**Issue by infact** [npm/npm#20414]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [x] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
When I gave npm install  I'm getting the following error

**

> \source\repos\WebApplication3\WebApplication3>npm install
> npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but npm-shrinkwrap.json was generated for lockfileVersion@0. I'll try to do my best with it!
> npm ERR! code ETIMEDOUT
> npm ERR! errno ETIMEDOUT
> npm ERR! network request to http://registry.npmjs.org/@angular%2fanimations failed, reason: connect ETIMEDOUT 151.101.44.162:80
> npm ERR! network This is a problem related to network connectivity.
> npm ERR! network In most cases you are behind a proxy or have bad network settings.
> npm ERR! network
> npm ERR! network If you are behind a proxy, please make sure that the
> npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\xyz\AppData\Roaming\npm-cache\_logs\2018-04-23T19_43_14_806Z-debug.log

**
_

> As per the error message ,its due to proxy server.But I am not using any proxy.I am in a corporate network.But if I check the internet settings >>Lan Settings  but I dont see any proxy server mentioned.So I believe I am not behind any proxy server.

_

**Here is the error message from  debug-log pasted below:**

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@5.6.0
3 info using node@v8.11.1
4 verbose npm-session 17fd27c5cd0be499
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall WebApplication3@0.0.0
7 info lifecycle WebApplication3@0.0.0~preinstall: WebApplication3@0.0.0
8 silly install loadCurrentTree
9 silly install readLocalPackageData
10 warn read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but npm-shrinkwrap.json was generated for lockfileVersion@0. I'll try to do my best with it!
11 silly install loadIdealTree
12 silly install cloneCurrentTreeToIdealTree
13 silly install loadShrinkwrap
14 silly fetchPackageMetaData error for @angular/animations@4.2.5 request to http://registry.npmjs.org/@angular%2fanimations failed, reason: connect ETIMEDOUT 151.101.44.162:80
15 silly saveTree WebApplication3@0.0.0
16 verbose type system
17 verbose stack FetchError: request to http://registry.npmjs.org/@angular%2fanimations failed, reason: connect ETIMEDOUT 151.101.44.162:80
17 verbose stack     at ClientRequest.req.on.err (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\node-fetch-npm\src\index.js:68:14)
17 verbose stack     at emitOne (events.js:116:13)
17 verbose stack     at ClientRequest.emit (events.js:211:7)
17 verbose stack     at Socket.socketErrorListener (_http_client.js:387:9)
17 verbose stack     at emitOne (events.js:116:13)
17 verbose stack     at Socket.emit (events.js:211:7)
17 verbose stack     at emitErrorNT (internal/streams/destroy.js:64:8)
17 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:138:11)
17 verbose stack     at process._tickCallback (internal/process/next_tick.js:180:9)
18 verbose cwd C:\Users\karunam\source\repos\WebApplication3\WebApplication3
19 verbose Windows_NT 10.0.16299
20 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
21 verbose node v8.11.1
22 verbose npm  v5.6.0
23 error code ETIMEDOUT
24 error errno ETIMEDOUT
25 error network request to http://registry.npmjs.org/@angular%2fanimations failed, reason: connect ETIMEDOUT 151.101.44.162:80
26 error network This is a problem related to network connectivity.
26 error network In most cases you are behind a proxy or have bad network settings.
26 error network
26 error network If you are behind a proxy, please make sure that the
26 error network 'proxy' config is set properly.  See: 'npm help config'
27 verbose exit [ 1, true ]

### supporting information:

 - `npm -v` prints: _5.6.0_
 - `node -v` prints: _v8.11.1_
 - `npm config get registry` prints: _http://registry.npmjs.org/_
 - Windows, OS X/macOS, or Linux?: Windows 10 Pro
 - Network issues:
   - Geographic location where npm was run:
   - [ ] use a proxy to connect to the npm registry.
   - [ ] use a proxy to connect to the web. 
   - [ ]  use a proxy when downloading Git repos. 
   - [x]  access the npm registry via a VPN. 
   - [x]  don't use a proxy,
   - [ ] but have limited or unreliable internet access. 
 - Container:
   - [ ] develop using Vagrant on Windows.
   - [ ] develop using Vagrant on OS X or Linux.
   - [ ] develop / deploy using Docker.
   - [ ] deploy to a PaaS (Triton, Heroku).

**Comment by infact** [comment]
- **I tried npm cache verify**   
npm cache verify  Prints
Cache verified and compressed (~\AppData\Roaming\npm-cache\_cacache):
Content verified: 0 (0 bytes)
Index entries: 0
Finished in 0.026s

- npm  config list  prints
; cli configs
metrics-registry = "http://registry.npmjs.org/"
scope = ""
user-agent = "npm/5.6.0 node/v8.11.1 win32 x64"

; userconfig C:\Users\abcuser\.npmrc
http-proxy = "http://username:password@ip:port"
registry = "http://registry.npmjs.org/"
strict-ssl = false

; builtin config undefined
prefix = "C:\\Users\\abcuser\\AppData\\Roaming\\npm"

; node bin location = C:\Program Files\nodejs\node.exe
; cwd = C:\Users\abcuser\source\repos\WebApplication3\WebApplication3
; HOME = C:\Users\abcuser
; "npm config ls -l" to show all defaults.

**Comment by infact** [comment]
Deleted .npmrc file  from location C:\users\abcuser\
Now I tried with -d  option and now it got stuck  for too long with message  **...loadIdealTree:loadAllDepsIntoIdealTree: sill install loadIdealTree**


> npm install -d

npm info it worked if it ends with ok
npm info using npm@5.6.0
npm info using node@v8.11.1
npm info lifecycle WebApplication3@0.0.0~preinstall: WebApplication3@0.0.0
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but npm-shrinkwrap.json was generated for lockfileVersion@0. I'll try to do my best with it!
[ .................] | loadIdealTree:loadAllDepsIntoIdealTree: sill install loadIdealTree


**Please help.Any Suggestions ?**

**Comment by infact** [comment]
tried  this command and getting another error "npm WARN enoent ENOENT: no such file or directory, open ...package.json"

> npm config ls -l

npm install
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\abcuser\source\repos\WebApplication3\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\abcuser\source\repos\WebApplication3\package.json'
npm WARN WebApplication3 No description
npm WARN WebApplication3 No repository field.
npm WARN WebApplication3 No README data
npm WARN WebApplication3 No license field.

up to date in 0.078s

**Comment by infact** [comment]
Then I tried  
`npm Install -g express -generator`  

and getting  errors (pasted below)

npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! network request to https://registry.npmjs.org/express-generator failed, reason: connect ETIMEDOUT 151.101.48.162:443
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\abcuser\AppData\Roaming\npm-cache\_logs\2018-04-24T13_25_17_069Z-debug.log


Please not that I am not behind any proxy, then why I am getting this error ?

Please help . Any suggestions to resolve this?

**Comment by infact** [comment]
Next I tried with  

> npm init -y

Wrote to C:\Users\abcuser\source\repos\WebApplication4\package.json:

{
  "name": "WebApplication4",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}

**Comment by infact** [comment]
Again trying with 

> npm install -d


npm info it worked if it ends with ok
npm info using npm@5.6.0
npm info using node@v8.11.1
npm info lifecycle WebApplication4@0.0.0~preinstall: WebApplication4@0.0.0
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but npm-shrinkwrap.json was generated for lockfileVersion@0. I'll try to do my best with it!
[ .................] | loadIdealTree:loadAllDepsIntoIdealTree: sill install loadIdealTree


**and it got frozen for several minutes... then ended up throwing these errors:**

npm info it worked if it ends with ok
npm info using npm@5.6.0
npm info using node@v8.11.1
npm info lifecycle WebApplication4@0.0.0~preinstall: WebApplication4@0.0.0
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but npm-shrinkwrap.json was generated for lockfileVersion@0. I'll try to do my best with it!
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! network request to https://registry.npmjs.org/@angular%2fanimations failed, reason: connect ETIMEDOUT 151.101.48.162:443
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\abcuser\AppData\Roaming\npm-cache\_logs\2018-04-24T13_53_56_881Z-debug.log

**Any suggestions to resolve this ?**

**Comment by infact** [comment]
I am in a corporate office.But it looks like I am not using any proxy.See screen shot below.

<img width="304" alt="capture" src="https://user-images.githubusercontent.com/9020432/39194482-7abbbefe-47a3-11e8-92a7-df45dd29226a.PNG">


**What should I do next? Any pointers ?**

**Comment by infact** [comment]
> npm config list    prints 

; cli configs
metrics-registry = "https://registry.npmjs.org/"
scope = ""
user-agent = "npm/5.6.0 node/v8.11.1 win32 x64"

; builtin config undefined
prefix = "C:\\Users\\abcuser\\AppData\\Roaming\\npm"

; node bin location = C:\Program Files\nodejs\node.exe
; cwd = C:\Users\abcuser\source\repos\WebApplication4\WebApplication4
; HOME = C:\Users\abcuser
; "npm config ls -l" to show all defaults.


**

> npm install -verbose             prints

**
npm info it worked if it ends with ok
npm verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'install',
npm verb cli   '-verbose' ]
npm info using npm@5.6.0
npm info using node@v8.11.1
npm verb npm-session a185e5e43bb1bec9
npm info lifecycle WebApplication4@0.0.0~preinstall: WebApplication4@0.0.0
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@0. I'll try to do my best with it!
npm verb type system
npm verb stack FetchError: request to https://registry.npmjs.org/@angular%2fanimations failed, reason: connect ETIMEDOUT 151.101.44.162:443
npm verb stack     at ClientRequest.req.on.err (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\node-fetch-npm\src\index.js:68:14)
npm verb stack     at emitOne (events.js:116:13)
npm verb stack     at ClientRequest.emit (events.js:211:7)
npm verb stack     at TLSSocket.socketErrorListener (_http_client.js:387:9)
npm verb stack     at emitOne (events.js:116:13)
npm verb stack     at TLSSocket.emit (events.js:211:7)
npm verb stack     at emitErrorNT (internal/streams/destroy.js:64:8)
npm verb stack     at _combinedTickCallback (internal/process/next_tick.js:138:11)
npm verb stack     at process._tickCallback (internal/process/next_tick.js:180:9)
npm verb cwd C:\Users\abcuser\source\repos\WebApplication4\WebApplication4
npm verb Windows_NT 10.0.16299
npm verb argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-verbose"
npm verb node v8.11.1
npm verb npm  v5.6.0
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! network request to https://registry.npmjs.org/@angular%2fanimations failed, reason: connect ETIMEDOUT 151.101.44.162:443
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
npm verb exit [ 1, true ]

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\abcuser\AppData\Roaming\npm-cache\_logs\2018-04-24T14_59_46_141Z-debug.log

**I tried ping to the IP address above.Here is the result below**

ping 151.101.44.162:443
**Ping request could not find host 151.101.44.162:443. Please check the name and try again.**

**Any suggestions ?**

**Comment by infact** [comment]
This issue was due to our corporate network /some connectivity issues.When I switched to a different Wifi network it worked as expected.
