### ISSUE TITLE
npm upgrade prompt should show warning when current node version is not supported in newer version

### ISSUE THREAD

**Issue by maptile** [npm/npm#20431]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] npm is producing incorrect or undesirable behavior.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?
I currently have node 4.8.7 and npm 5.8. When I run npm today, it show an upgrade notice of npm 6.0

```
   ╭─────────────────────────────────────╮
   │                                     │
   │   Update available 5.8.0 → 6.0.0    │
   │     Run npm i -g npm to update      │
   │                                     │
   ╰─────────────────────────────────────╯
```

As usual, I will install the newer version. But after install, I found npm 6 is no longer support node 4.

I can not downgrade to npm 5.8 anymore unless reinstall node 4.

#### Expectation

If new version have such break change, it should warn the user about it.

**Comment by bsyk** [comment]
I've also encountered an error upgrading to npm 6.  Here's some additional error messages:
```
Semaphore: ~/proj $ npm -v
2.15.11
Semaphore: ~/proj $ npm install npm@latest -g
/home/runner/.nvm/versions/node/v4.8.4/bin/npx -> /home/runner/.nvm/versions/node/v4.8.4/lib/node_modules/npm/bin/npx-cli.js
/home/runner/.nvm/versions/node/v4.8.4/bin/npm -> /home/runner/.nvm/versions/node/v4.8.4/lib/node_modules/npm/bin/npm-cli.js
npm@6.0.0 /home/runner/.nvm/versions/node/v4.8.4/lib/node_modules/npm
Semaphore: ~/proj $ npm -v
/home/runner/.nvm/versions/node/v4.8.4/lib/node_modules/npm/bin/npm-cli.js:79
      let notifier = require('update-notifier')({pkg})
      ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
    at node.js:1043:3
```

**Comment by maptile** [comment]
@bsyk You can uninstall node 4.8.4, and reinstall it to solve this problem temporarily.

**Comment by AyushG3112** [comment]
Node.js 4 has reached end of maintenance phase, and now is End-Of-Life, it might be worth considering switching to a newer version of Node.js.

**Comment by Synchro** [comment]
# How to recover from broken old npm.

Old npm won't work with new node:

```
npm -v

/Users/marcus/.nvm/v0.10.48/lib/node_modules/npm/bin/npm-cli.js:79
      let notifier = require('update-notifier')({pkg})
          ^^^^^^^^
SyntaxError: Unexpected identifier
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3
```

Install old node:
```
nvm install 4.8.4
npm i -g npm
/Users/marcus/.nvm/versions/node/v4.8.4/bin/npm -> /Users/marcus/.nvm/versions/node/v4.8.4/lib/node_modules/npm/bin/npm-cli.js
/Users/marcus/.nvm/versions/node/v4.8.4/bin/npx -> /Users/marcus/.nvm/versions/node/v4.8.4/lib/node_modules/npm/bin/npx-cli.js
npm@6.0.1 /Users/marcus/.nvm/versions/node/v4.8.4/lib/node_modules/npm
```

Now new npm won't work with old node:

```
npm -v
/Users/marcus/.nvm/versions/node/v4.8.4/lib/node_modules/npm/bin/npm-cli.js:79
      let notifier = require('update-notifier')({pkg})
      ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
    at node.js:1043:3
```

Reinstall node 10:
```
nvm install 10
Now using node v10.1.0 (npm v5.6.0)
```

I don't know why npm somehow went to 5.6.0 there, but now update it:
```
npm install -g npm
/Users/marcus/.nvm/versions/node/v10.1.0/bin/npx -> /Users/marcus/.nvm/versions/node/v10.1.0/lib/node_modules/npm/bin/npx-cli.js
/Users/marcus/.nvm/versions/node/v10.1.0/bin/npm -> /Users/marcus/.nvm/versions/node/v10.1.0/lib/node_modules/npm/bin/npm-cli.js
+ npm@6.0.1
added 246 packages, removed 40 packages and updated 125 packages in 22.342s
```

And now it's happy:
```
npm -v
6.0.1
```

You might want to remove old node versions now.

**Comment by dineshnagar** [comment]
nvm install 10 
its working for upgrading node version... :)
