### ISSUE TITLE
npm install fails in directory encrypted with Dell Encryption software on Windows 10

### ISSUE THREAD

**Issue by kerbs17** [npm/npm#20468]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
My company requires the use of Dell Encryption software.

Recently, remnants of Dell Encryption tracker files that are placed in directories has caused issues with `npm install`.

Dell Encryption has `CredDB2.CEF` files that get created in directories that track the state of each encrypted file.  When I `npm install request`, I end up getting errors in a dependency that is creating/modifying the bin files of its install:

    npm ERR! path C:\project\node_modules\sshpk\bin\CredDB2.CEF
    npm ERR! code ENOENT
    npm ERR! errno -4058
    npm ERR! syscall chmod
    npm ERR! enoent ENOENT: no such file or directory, chmod 'C:\project\node_modules\sshpk\bin\CredDB2.CEF'npm ERR! enoent This is related to npm not being able to find a file.
    npm ERR! enoent

The relevant verbose log output is:

    1254 silly build sshpk@1.13.1
    1255 info linkStuff sshpk@1.13.1
    1256 silly linkStuff sshpk@1.13.1 has C:\project\node_modules as its parent node_modules
    1257 verbose linkBins sshpk@1.13.1
    1258 verbose linkBins [ { 'CredDB2.CEF': 'bin/CredDB2.CEF',
    1258 verbose linkBins     'sshpk-conv': 'bin/sshpk-conv',
    1258 verbose linkBins     'sshpk-sign': 'bin/sshpk-sign',
    1258 verbose linkBins     'sshpk-verify': 'bin/sshpk-verify' },
    1258 verbose linkBins   'C:\\project\\node_modules\\.bin',
    1258 verbose linkBins   false ]

Dell Encryption creates the `CredDB2.CEF` file as metadata about the encryption state, however, the file created in such a matter that is is hidden from the typical file explorer (even when show hidden files is enabled) and can't be opened by applications using the full path of the file.  

#### How can the CLI team reproduce the problem?

* Requires Dell Encryption, not sure how easily this will be to reproduce without it.
* `npm install request`

### supporting information:

 - `npm -v` prints: `5.6.0`
 - `node -v` prints: `v8.11.1`
 - `npm config get registry` prints: `https://registry.npmjs.org/`
 - Windows, OS X/macOS, or Linux?: Windows
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by Gullfaxi171** [comment]
it also breaks Atom, @angular/cli and a bunch of common libraries:

```
Fetching featured packages failed.Hide output…
fs.js:987
  return binding.stat(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, stat 'C:\Users\user\AppData\Local\atom\app-1.23.2\resources\app\apm\node_modules\npm-registry-client\lib\CredDB2.CEF'
    at Error (native)
    at Object.fs.statSync (fs.js:987:18)
    at Object.<anonymous> (C:\Users\user\AppData\Local\atom\app-1.23.2\resources\app\apm\node_modules\npm\node_modules\graceful-fs\polyfills.js:277:22)
    at Object.statSync (C:\Users\user\AppData\Local\atom\app-1.23.2\resources\app\apm\node_modules\graceful-fs\polyfills.js:297:22)
    at C:\Users\user\AppData\Local\atom\app-1.23.2\resources\app\apm\node_modules\npm-registry-client\index.js:55:19
    at Array.forEach (native)
    at CachingRegistryClient.RegClient (C:\Users\user\AppData\Local\atom\app-1.23.2\resources\app\apm\node_modules\npm-registry-client\index.js:51:42)
    at new CachingRegistryClient (C:\Users\user\AppData\Local\atom\app-1.23.2\resources\app\apm\node_modules\npm\lib\cache\caching-client.js:21:18)
    at C:\Users\user\AppData\Local\atom\app-1.23.2\resources\app\apm\node_modules\npm\lib\npm.js:289:24
    at C:\Users\user\AppData\Local\atom\app-1.23.2\resources\app\apm\node_modules\npm\lib\config\core.js:81:7
```
