### ISSUE TITLE
Warning: a promise was created in a handler ... but was not returned from it

### ISSUE THREAD

**Issue by bricss** [npm/npm#20460]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] npm is producing incorrect or undesirable behavior.
  - [x] Other (_see below for feature requests_):

Version: Node.js v10.0.0 + npm 6.0.0
Platform: Windows 10, possibly - All
Subsystem: Promise

Steps to reproduce:
1. `npm install -g npm`
2. `npm update`

Right after:
```shell
node:6684) Warning: a promise was created in a handler at C:\Users\<Username>\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\lib\fetchers\registry\tarball.js:39:25 b
ut was not returned from it, see http://goo.gl/rRqMUw
    at ret (eval at makeNodePromisifiedEval (C:\Users\<Username>\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promisify.js:184:12), <anonymous>:8:21)
(node:6684) Warning: a promise was created in a handler at C:\Users\<Username>\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\lib\fetchers\registry\tarball.js:39:25 b
ut was not returned from it, see http://goo.gl/rRqMUw
    at ret (eval at makeNodePromisifiedEval (C:\Users\<Username>\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promisify.js:184:12), <anonymous>:8:21)
```
Then just stuck.

**Comment by bricss** [comment]
It seems that it can be simply fixed by setting: `npm config set registry http://registry.npmjs.org/`
