### ISSUE TITLE
npm ERR! write after end

### ISSUE THREAD

**Issue by slim-hmidi** [npm/npm#20462]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### How can the CLI team reproduce the problem?

I run `npm i mocha chai --save-dev` and I got this error:
```
npm ERR! write after end
```

### supporting information:

 - `npm -v` prints: 6.0.0
 - `node -v` prints: 8.6.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Ubuntu 16.04LTS
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by cronvel** [comment]
Same here, I got regularly this error, with npm v6.0.1 and node v8.11.1, in various context.
Sometime just `npm install` after cloning a repo crash.
When re-trying, it may succeed, or may crash again.
Downgrading to npm 5 solve the issue.

**Comment by cronvel** [comment]
The stack trace:
```
2034 verbose stack Error: write after end
2034 verbose stack     at writeAfterEnd (_stream_writable.js:236:12)
2034 verbose stack     at PassThrough.Writable.write (_stream_writable.js:287:5)
2034 verbose stack     at PassThrough.Writable.end (_stream_writable.js:563:10)
2034 verbose stack     at ReadEntry.entry.on (/opt/node.js-v8.11.1/lib/node_modules/npm/node_modules/pacote/lib/extract-stream.js:19:41)
2034 verbose stack     at emitOne (events.js:121:20)
2034 verbose stack     at ReadEntry.emit (events.js:211:7)
2034 verbose stack     at ReadEntry.emit (/opt/node.js-v8.11.1/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:296:25)
2034 verbose stack     at ReadEntry.[maybeEmitEnd] (/opt/node.js-v8.11.1/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:
2034 verbose stack     at ReadEntry.end (/opt/node.js-v8.11.1/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:162:27)
2034 verbose stack     at Unpack.[consumeBody] (/opt/node.js-v8.11.1/lib/node_modules/npm/node_modules/tar/lib/parse.js:210:13)
2034 verbose stack     at Unpack.[consumeChunkSub] (/opt/node.js-v8.11.1/lib/node_modules/npm/node_modules/tar/lib/parse.js:391:40)
2034 verbose stack     at Unpack.[consumeChunk] (/opt/node.js-v8.11.1/lib/node_modules/npm/node_modules/tar/lib/parse.js:362:30)
2034 verbose stack     at Unzip.(anonymous function).on.chunk (/opt/node.js-v8.11.1/lib/node_modules/npm/node_modules/tar/lib/parse.js:291:59)
2034 verbose stack     at emitOne (events.js:116:13)
2034 verbose stack     at Unzip.emit (events.js:211:7)
2034 verbose stack     at Unzip.emit (/opt/node.js-v8.11.1/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:296:25)
```

**Comment by cronvel** [comment]
It looks like `npm install --save-dev mocha` crash 100% of time.

**Comment by warmans** [comment]
This is apparently fixed via #19989 in 6.1.0 but actually it is still broken for me so I'm not sure if there is something else going wrong.
