### ISSUE TITLE
npm install - Invalid or unexpected token

### ISSUE THREAD

**Issue by iamdevlinph** [npm/npm#20461]
#### I'm opening this issue because:

  - [x] npm is producing incorrect or undesirable behavior.

#### What's going wrong?
```
➜  react-kit git:(master) npm install
npm ERR! Invalid or unexpected token

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/devlin/.npm/_logs/2018-04-29T17_03_42_253Z-debug.log
```

#### How can the CLI team reproduce the problem?

```
git clone git@github.com:codesandcoffees/react-kit.git
```
**OR**
```
"dependencies": {
    "@codes-and-coffees/react-pkg": "1.1.0"
},
```

then `npm install`
### supporting information:

 - `npm -v` prints: 6.0.0
 - `node -v` prints: v8.11.1
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: WSL 
```
➜  react-kit git:(master) ✗ NODE_DEBUG=net npm install --verbose
npm info it worked if it ends with ok
npm verb cli [ '/usr/bin/node', '/usr/bin/npm', 'install', '--verbose' ]
npm info using npm@6.0.0
npm info using node@v8.11.1
npm verb npm-session 180a630739dec1cd
npm info lifecycle react-kit@1.0.0~preinstall: react-kit@1.0.0
npm timing stage:loadCurrentTree Completed in 9ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 1ms
npm timing stage:rollbackFailedOptional Completed in 0ms
npm timing stage:runTopLevelLifecycles Completed in 222ms
npm verb stack /usr/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/index.js:1
npm verb stack (function (exports, require, module, __filename, __dirname) { �r~�X��ωPDJ�wi♂'►��ML��♥�s�¶☺
npm verb stack                                                               ^
npm verb stack
npm verb stack SyntaxError: Invalid or unexpected token
npm verb stack     at createScript (vm.js:80:10)
npm verb stack     at Object.runInThisContext (vm.js:139:10)
npm verb stack     at Module._compile (module.js:616:28)
npm verb stack     at Object.Module._extensions..js (module.js:663:10)
npm verb stack     at Module.load (module.js:565:32)
npm verb stack     at tryModuleLoad (module.js:505:12)
npm verb stack     at Function.Module._load (module.js:497:3)
npm verb stack     at Module.require (module.js:596:17)
npm verb stack     at require (internal/module.js:11:18)
npm verb stack     at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:7:15)
npm verb stack     at Module._compile (module.js:652:30)
npm verb stack     at Object.Module._extensions..js (module.js:663:10)
npm verb stack     at Module.load (module.js:565:32)
npm verb stack     at tryModuleLoad (module.js:505:12)
npm verb stack     at Function.Module._load (module.js:497:3)
npm verb stack     at Module.require (module.js:596:17)
npm verb cwd /mnt/f/react-kit
npm verb Linux 4.4.0-43-Microsoft
npm verb argv "/usr/bin/node" "/usr/bin/npm" "install" "--verbose"
npm verb node v8.11.1
npm verb npm  v6.0.0
npm ERR! Invalid or unexpected token
npm verb exit [ 1, true ]
npm timing npm Completed in 760ms

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/devlin/.npm/_logs/2018-04-29T16_57_55_794Z-debug.log
```

And I can't downgrade `npm` by `npm install -g npm@5.3.0` cause it also gives the the error
```
➜  react-kit git:(master) npm install -g npm@5.6.0
npm ERR! Invalid or unexpected token

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/devlin/.npm/_logs/2018-04-29T17_05_22_060Z-debug.log
```

Reinstalling `node` would be my last resort and I hope it won't come to that.

**Comment by iamdevlinph** [comment]
Reinstalled `node` and everything was fine. Reverted back to `5.6.0`

I have 2 possible things to look in to.

1. `npm-check-updates`
I just remembered that I ran `npm i -g npm-check-updates` and it failed and I think my succeeding `npm installs` fail after that.

2. Updating to `6.0.0`
On this issue I directly updated `npm`  to `6.0.0` then installed `npm-check-updates`
