### ISSUE TITLE
Can't create new project using angular cli

### ISSUE THREAD

**Issue by cap-of-SAM** [npm/npm#20507]
I am trying to create a new project using angular cli. It shows an error saying 

```
npm ERR! missing script: ng

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\soumya\AppData\Roaming\npm-cache\_logs\2018-05-04T07_37_09
_794Z-debug.log
```

Log:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\soumya\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'ng',
1 verbose cli   'new',
1 verbose cli   'proj' ]
2 info using npm@6.0.0
3 info using node@v8.9.3
4 verbose stack Error: missing script: ng
4 verbose stack     at run (C:\Users\soumya\AppData\Roaming\npm\node_modules\npm\lib\run-script.js:151:19)
4 verbose stack     at C:\Users\soumya\AppData\Roaming\npm\node_modules\npm\lib\run-script.js:61:5
4 verbose stack     at C:\Users\soumya\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:115:5
4 verbose stack     at C:\Users\soumya\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:418:5
4 verbose stack     at checkBinReferences_ (C:\Users\soumya\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:373:45)
4 verbose stack     at final (C:\Users\soumya\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:416:3)
4 verbose stack     at then (C:\Users\soumya\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:160:5)
4 verbose stack     at ReadFileContext.<anonymous> (C:\Users\soumya\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:332:20)
4 verbose stack     at ReadFileContext.callback (C:\Users\soumya\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16)
4 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)
5 verbose cwd D:\ang
6 verbose Windows_NT 6.3.9600
7 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\soumya\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "ng" "new" "proj"
8 verbose node v8.9.3
9 verbose npm  v6.0.0
10 error missing script: ng
11 verbose exit [ 1, true ]

```

Help me solve this. Thank you

**Comment by kenany** [comment]
Can you try this instead?:

```
npm install -g @angular/cli
ng new proj
```

**Comment by kenany** [comment]
Closing due to no reply after a month.
