### ISSUE TITLE
 Package name triggered spam detection

### ISSUE THREAD

**Issue by zhuzhuppx** [npm/npm#20501]
After I deleted a package, I posted it again
.Error: http://registry.npmjs.org/cpmsui: Package name triggered spam detection; if you believe this is in error, please contact support@npmjs.comat Request.params.callback [as _callback] (/usr/local/Cellar/yarn/1.3.2/libexec/lib/cli.js:62098:18)at Request.self.callback (/usr/local/Cellar/yarn/1.3.2/libexec/lib/cli.js:123085:22)at emitTwo (events.js:125:13)at Request.emit (events.js:213:7)at Request.<anonymous> (/usr/local/Cellar/yarn/1.3.2/libexec/lib/cli.js:124068:10)at emitOne (events.js:115:13)at Request.emit (events.js:210:7)at IncomingMessage.<anonymous> (/usr/local/Cellar/yarn/1.3.2/libexec/lib/cli.js:123988:12)at Object.onceWrapper (events.js:314:30)at emitNone (events.js:110:20)
--

**Comment by paulplayer** [comment]
meet the same problem. don't know what to do.
