### ISSUE TITLE
npm install issues as git fails

### ISSUE THREAD

**Issue by srinivas-yesp** [npm/npm#20535]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by srinivas-yesp** [comment]
Hi, not creating node modules on npm install but throwing below error which I don't understand. any help would be appreciated.

1. got nodejs installed
2. got git downloaded and installed.
3. got proxy and registry configured and created .npmrc file as below.
        http_proxy=http://<user>:<pwd>@http-proxy.mycompany.net:8080
       https_proxy=http://502003212:Srini111@http-proxy.mycompany.net:8080
       no_proxy=localhost,127.0.0.0/8,*.local,usmi-nexus.mycompany.net,migit.mycompany.net
       strict-ssl=false
      registry=<registry url>

4. Then run "npm install" and results as below

**$ npm install**
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config -                                                                                                                                                                                               -get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:204:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:886:16)
npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:342:1                                                                                                                                                                                               1)
npm WARN addRemoteGit     at emitOne (events.js:96:13)
npm WARN addRemoteGit     at Socket.emit (events.js:188:7)
npm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:497:12)
npm WARN addRemoteGit  git+https://github.com/goutamsm/ng1-protractor.git resett                                                                                                                                                                                               ing remote C:\Users\502003212\AppData\Roaming\npm-cache\_git-remotes\git-https-g                                                                                                                                                                                               ithub-com-goutamsm-ng1-protractor-git-8bb1045c because of error: { Error: Comman                                                                                                                                                                                               d failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:204:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:886:16)
npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:342:1                                                                                                                                                                                               1)
npm WARN addRemoteGit     at emitOne (events.js:96:13)
npm WARN addRemoteGit     at Socket.emit (events.js:188:7)
npm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:497:12)
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.ori                                                                                                                                                                                               gin.url' }
npm ERR! git clone --template=C:\Users\502003212\AppData\Roaming\npm-cache\_git-                                                                                                                                                                                               remotes\_templates --mirror https://github.com/goutamsm/ng1-protractor.git C:\Us                                                                                                                                                                                               ers\502003212\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-goutam                                                                                                                                                                                               sm-ng1-protractor-git-8bb1045c: Cloning into bare repository 'C:\Users\502003212                                                                                                                                                                                               \AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-goutamsm-ng1-protra                                                                                                                                                                                               ctor-git-8bb1045c'...
npm ERR! git clone --template=C:\Users\502003212\AppData\Roaming\npm-cache\_git-                                                                                                                                                                                               remotes\_templates --mirror https://github.com/goutamsm/ng1-protractor.git C:\Us                                                                                                                                                                                               ers\502003212\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-goutam                                                                                                                                                                                               sm-ng1-protractor-git-8bb1045c: fatal: unable to access 'https://github.com/gout                                                                                                                                                                                               amsm/ng1-protractor.git/': SSL certificate problem: unable to get local issuer c                                                                                                                                                                                               ertificate
npm ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\                                                                                                                                                                                               node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\50                                                                                                                                                                                               2003212\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://githu                                                                                                                                                                                               b.com/goutamsm/ng1-protractor.git C:\Users\502003212\AppData\Roaming\npm-cache\_                                                                                                                                                                                               git-remotes\git-https-github-com-goutamsm-ng1-protractor-git-8bb1045c
npm ERR! Cloning into bare repository 'C:\Users\502003212\AppData\Roaming\npm-ca                                                                                                                                                                                               che\_git-remotes\git-https-github-com-goutamsm-ng1-protractor-git-8bb1045c'...
npm ERR! fatal: unable to access 'https://github.com/goutamsm/ng1-protractor.git                                                                                                                                                                                               /': SSL certificate problem: unable to get local issuer certificate
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\misite2\gnw-b2b-ui\npm-debug.log


Thanks
yesp

**Comment by legodude17** [comment]
Try running `git --version` in your terminal and paste the output here.

**Comment by srinivas-yesp** [comment]
git version 2.17.0.windows.1
