### ISSUE TITLE
NPM issues

### ISSUE THREAD

**Issue by ashu00120** [npm/npm#20557]
#### I'm following step for resolved dependencies in vs codes by command prompt 👍 
 D:\>cd \Projects\NOI UI\front

D:\Projects\NOI UI\front>npm config set registry http://registry.npmjs.org/

D:\Projects\NOI UI\front>npm config set proxy http://lill.proxy.corp.sopra:8080

D:\Projects\NOI UI\front>
D:\Projects\NOI UI\front>npm config set https-proxy http://lill.proxy.corp.sopra:8080

D:\Projects\NOI UI\front>npm install

and faced problem 👍 
npm ERR! error:0906D06C:PEM routines:PEM_read_bio:no start line
npm ERR! error:0906D06C:PEM routines:PEM_read_bio:no start line
npm ERR! error:0906D06C:PEM routines:PEM_read_bio:no start line
npm ERR! error:0906D06C:PEM routines:PEM_read_bio:no start line
npm ERR! error:0906D06C:PEM routines:PEM_read_bio:no start line
npm ERR! error:0906D06C:PEM routines:PEM_read_bio:no start line
npm ERR! error:0906D06C:PEM routines:PEM_read_bio:no start line
npm ERR! error:0906D06C:PEM routines:PEM_read_bio:no start line
npm ERR! error:0906D06C:PEM routines:PEM_read_bio:no start line
npm ERR! error:0906D06C:PEM routines:PEM_read_bio:no start line

Log here 👍 
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@5.6.0
3 info using node@v8.11.1
4 verbose npm-session 646e512f6e5476c3
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall noe@2.1.0
7 info lifecycle noe@2.1.0~preinstall: noe@2.1.0
8 silly install loadCurrentTree
9 silly install readLocalPackageData
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 silly install loadShrinkwrap
13 silly install loadAllDepsIntoIdealTree
14 verbose stack Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
14 verbose stack     at Object.createSecureContext (_tls_common.js:104:17)
14 verbose stack     at Object.exports.connect (_tls_wrap.js:1049:48)
14 verbose stack     at ondata (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\https-proxy-agent\index.js:153:20)
14 verbose stack     at Socket.read (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\https-proxy-agent\index.js:88:12)
14 verbose stack     at Object.onceWrapper (events.js:313:30)
14 verbose stack     at emitNone (events.js:106:13)
14 verbose stack     at Socket.emit (events.js:208:7)
14 verbose stack     at emitReadable_ (_stream_readable.js:513:10)
14 verbose stack     at emitReadable (_stream_readable.js:507:7)
14 verbose stack     at addChunk (_stream_readable.js:274:7)
14 verbose stack     at readableAddChunk (_stream_readable.js:250:11)
14 verbose stack     at Socket.Readable.push (_stream_readable.js:208:10)
14 verbose stack     at TCP.onread (net.js:607:20)
15 verbose cwd D:\Projects\NOI UI\front
16 verbose Windows_NT 10.0.15063
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
18 verbose node v8.11.1
19 verbose npm  v5.6.0
20 error error:0906D06C:PEM routines:PEM_read_bio:no start line
21 verbose exit [ 1, true ]
and i used another approach from YARN software then also i faced same problem like:
PS D:\Projects\NOI UI\front> yarn install
yarn install v1.6.0
[1/4] Resolving packages...
[2/4] Fetching packages...
[-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------] 0/1538_tls_common.js:104
      c.context.setKey(options.key, options.passphrase);
                ^

Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
    at Object.createSecureContext (_tls_common.js:104:17)
    at Object.exports.connect (_tls_wrap.js:1049:48)
    at C:\Program Files (x86)\Yarn\lib\cli.js:147070:28
    at ClientRequest.onConnect (C:\Program Files (x86)\Yarn\lib\cli.js:147031:7)
    at Object.onceWrapper (events.js:319:30)
    at emitThree (events.js:136:13)
    at ClientRequest.emit (events.js:217:7)
    at Socket.socketOnData (_http_client.js:472:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
PS D:\Projects\NOI UI\front>
anypone please help me for solved issues.

**Comment by ashu00120** [comment]
please help me for this issues i am stuck in development mode.

**Comment by legodude17** [comment]
Hello! This is a duplicate of #10897. Please try `npm config set registry http://registry.npmjs.org`. Also, make sure your proxy supports https.
