### ISSUE TITLE
lerna bootstrap → npm audit crash on "invalid" trees

### ISSUE THREAD

**Issue by garthk** [npm/npm#20566]
#### I'm opening this issue because:

  - [x] npm is crashing.

#### What's going wrong?

The root cause seems to be treating the results of `lerna bootstrap` as an invalid tree. Maybe it's the symlinks out of `node_folders` it doesn't like. ¯\_(ツ)_/¯

In any case, not all resolutions have a path. This one, for example:

```json
{"id":-1,"dev":false,"optional":false,"bundled":false}
```

So, this code crashes:

```js
            const table = new Table(tableOptions)

            table.push(
              {[Utils.severityLabel(advisory.severity, config.withColor)]: advisory.title},
              {'Package': advisory.module_name},
              {'Dependency of': `${resolution.path.split('>')[0]} ${resolution.dev ? '[dev]' : ''}`},
```

… so it can't print out this notification, the `resolution` of which I set `path: "FAKE"` to figure out what was going on:

```
┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ critical      │ Invalid package tree, run  npm install  to rebuild your      │
│               │ package-lock.json                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │                                                              │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ FAKE                                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ FAKE                                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/-1                        │
└───────────────┴──────────────────────────────────────────────────────────────┘
```

```
$ npm audit
npm ERR! Cannot read property 'split' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/self/.npm/_logs/2018-05-09T23_10_15_515Z-debug.log
```

```
$ cat /Users/self/.npm/_logs/2018-05-09T23_10_15_515Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node@8/8.11.1/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'audit' ]
2 info using npm@6.0.0
3 info using node@v8.11.1
4 timing audit compress Completed in 8ms
5 info audit Submitting payload of 36922 bytes
6 timing audit submit Completed in 31836ms
7 http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits 31836ms
8 timing audit body Completed in 1ms
9 verbose stack TypeError: Cannot read property 'split' of undefined
9 verbose stack     at action.resolves.forEach (/usr/local/lib/node_modules/npm/node_modules/npm-audit-report/reporters/detail.js:152:52)
9 verbose stack     at Array.forEach (<anonymous>)
9 verbose stack     at data.actions.forEach (/usr/local/lib/node_modules/npm/node_modules/npm-audit-report/reporters/detail.js:138:27)
9 verbose stack     at Array.forEach (<anonymous>)
9 verbose stack     at actions (/usr/local/lib/node_modules/npm/node_modules/npm-audit-report/reporters/detail.js:88:20)
9 verbose stack     at Object.report [as detail] (/usr/local/lib/node_modules/npm/node_modules/npm-audit-report/reporters/detail.js:163:3)
9 verbose stack     at Promise (/usr/local/lib/node_modules/npm/node_modules/npm-audit-report/index.js:18:46)
9 verbose stack     at new Promise (<anonymous>)
9 verbose stack     at report (/usr/local/lib/node_modules/npm/node_modules/npm-audit-report/index.js:17:10)
9 verbose stack     at Object.printFullReport (/usr/local/lib/node_modules/npm/lib/install/audit.js:95:10)
9 verbose stack     at Bluebird.all.spread.then.catch.then (/usr/local/lib/node_modules/npm/lib/audit.js:81:18)
9 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
9 verbose stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
9 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
9 verbose stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
9 verbose stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
10 verbose cwd /Users/self/src/mononode/pkg/geonames
11 verbose Darwin 17.5.0
12 verbose argv "/usr/local/Cellar/node@8/8.11.1/bin/node" "/usr/local/bin/npm" "audit"
13 verbose node v8.11.1
14 verbose npm  v6.0.0
15 error Cannot read property 'split' of undefined
16 verbose exit [ 1, true ]
```

#### How can the CLI team reproduce the problem?

On macOS:

```
brew install node@8
npm install npm -g
cd path/to/my/closed/source/project
npm audit
```

### supporting information:

 - `npm -v` prints: 6.0.0
 - `node -v` prints: v8.11.1
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: macOS
 - Network issues: none
 - Container: none

**Comment by evocateur** [comment]
`lerna bootstrap` is munging package.json to remove sibling packages before a subdirectory `npm install`, and then creating the symlinks. So the lockfile is indeed out of sync with the file system.

I recommend folks start using lerna@3 with relative `file:` specifiers for sibling dependencies, it completely obviates any need for `lerna bootstrap` and its hacks.

**Comment by garthk** [comment]
How does that affect `npm publish`, @evocateur? Or does it force use of `lerna publish`, which presumably fixes the `package.json` before passing control to `npm`?
