### ISSUE TITLE
npm audit should ignore `github:` versions instead of erroring

### ISSUE THREAD

**Issue by geek** [npm/npm#20578]
#### I'm opening this issue because:

  - [X] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
```
5 verbose stack TypeError: Invalid Version: github:googleapis/nodejs-compute#dcb...
5 verbose stack     at new SemVer (.../node/v8.11.1/lib/node_modules/npm/node_modules/semver/semver.js:305:11)
5 verbose stack     at Range.test (/.../node/v8.11.1/lib/node_modules/npm/node_modules/semver/semver.js:1112:15)
5 verbose stack     at Function.satisfies (/.../node/v8.11.1/lib/node_modules/npm/node_modules/semver/semver.js:1161:16)
5 verbose stack     at Object.keys.forEach.name (/.../node/v8.11.1/lib/node_modules/npm/node_modules/lock-verify/index.js:39:23)
5 verbose stack     at Array.forEach (<anonymous>)
5 verbose stack     at Promise.all.then.result (.../node/v8.11.1/lib/node_modules/npm/node_modules/lock-verify/index.js:25:25)
5 verbose stack     at <anonymous>
```

```
$ npm -v
6.0.1
```

**Comment by JMTK** [comment]
I got it on another one as well that ISN'T from github URI, not sure what exactly is causing it for this package.

```
npm ERR! Invalid Version: https://registry.npmjs.org/cleverbot.io/-/cleverbot.io-1.0.4.tgz

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-06-04T15_15_49_821Z-debug.log
```

And the log:
```
0 info it worked if it ends with ok
1 verbose cli [ '(REDACTED)/.nvm/versions/node/v8.1.3/bin/node',
1 verbose cli   '(REDACTED)/.nvm/versions/node/v8.1.3/bin/npm',
1 verbose cli   'audit' ]
2 info using npm@6.1.0
3 info using node@v8.1.3
4 verbose npm-session f263bdac741af851
5 verbose stack TypeError: Invalid Version: https://registry.npmjs.org/cleverbot.io/-/cleverbot.io-1.0.4.tgz
5 verbose stack     at new SemVer ((REDACTED)/.nvm/versions/node/v8.1.3/lib/node_modules/npm/node_modules/semver/semver.js:305:11)
5 verbose stack     at Range.test ((REDACTED)/.nvm/versions/node/v8.1.3/lib/node_modules/npm/node_modules/semver/semver.js:1112:15)
5 verbose stack     at Function.satisfies ((REDACTED)/.nvm/versions/node/v8.1.3/lib/node_modules/npm/node_modules/semver/semver.js:1161:16)
5 verbose stack     at Object.keys.forEach.name ((REDACTED)/.nvm/versions/node/v8.1.3/lib/node_modules/npm/node_modules/lock-verify/index.js:39:23)
5 verbose stack     at Array.forEach (native)
5 verbose stack     at Promise.all.then.result ((REDACTED)/.nvm/versions/node/v8.1.3/lib/node_modules/npm/node_modules/lock-verify/index.js:25:25)
5 verbose stack     at <anonymous>
6 verbose cwd (REDACTED)/discordbot
7 verbose Linux 3.16.0-4-amd64
8 verbose argv "(REDACTED)/.nvm/versions/node/v8.1.3/bin/node" "(REDACTED)/.nvm/versions/node/v8.1.3/bin/npm" "audit"
9 verbose node v8.1.3
10 verbose npm  v6.1.0
11 error Invalid Version: https://registry.npmjs.org/cleverbot.io/-/cleverbot.io-1.0.4.tgz
12 verbose exit [ 1, true ]
```

**Comment by JMTK** [comment]
Small update, looks like updating node to 8.11 fixed my issue. One of my repos is a github one so I'm not sure if that helps you at all
