### ISSUE TITLE
error 400 Bad Request on npm install

### ISSUE THREAD

**Issue by Daviey** [npm/npm#20589]
Hi,

I'm seeing an error, and i'm struggling to determine the cause.

#### I'm opening this issue because:

  - [X] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [X] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
1930 silly cache afterAdd ts-node@5.0.1
1931 verbose afterAdd /var/rapp/.npm/ts-node/5.0.1/package/package.json not in flight; writing
1932 verbose correctMkdir /var/rapp/.npm correctMkdir not in flight; initializing
1933 verbose afterAdd /var/rapp/.npm/ts-node/5.0.1/package/package.json written
1934 verbose stack Error: 400 Bad Request
1934 verbose stack     at makeError (/usr/local/nvm/versions/node/v4.4.7/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
1934 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/nvm/versions/node/v4.4.7/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:215:9)
1934 verbose stack     at Request._callback (/usr/local/nvm/versions/node/v4.4.7/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
1934 verbose stack     at Request.self.callback (/usr/local/nvm/versions/node/v4.4.7/lib/node_modules/npm/node_modules/request/request.js:200:22)
1934 verbose stack     at emitTwo (events.js:87:13)
1934 verbose stack     at Request.emit (events.js:172:7)
1934 verbose stack     at Request.<anonymous> (/usr/local/nvm/versions/node/v4.4.7/lib/node_modules/npm/node_modules/request/request.js:1067:10)
1934 verbose stack     at emitOne (events.js:82:20)
1934 verbose stack     at Request.emit (events.js:169:7)
1934 verbose stack     at IncomingMessage.<anonymous> (/usr/local/nvm/versions/node/v4.4.7/lib/node_modules/npm/node_modules/request/request.js:988:12)
1935 verbose statusCode 400
1936 verbose cwd /var/jenkins/workspace/Application Dev
1937 error Linux 2.6.32-504.16.2.el6.x86_64
1938 error argv "/usr/local/nvm/versions/node/v4.4.7/bin/node" "/usr/local/nvm/versions/node/v4.4.7/bin/npm" "install"
1939 error node v4.4.7
1940 error npm  v2.15.8
1941 error code E400
1942 error 400 Bad Request
1943 error If you need help, you may report this error at:
1943 error     <https://github.com/npm/npm/issues>
1944 verbose exit [ 1, true ]

#### How can the CLI team reproduce the problem?
node npm install

### supporting information:

 - `npm -v` prints: 2.15.8
 - `node -v` prints: v4.4.7
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux

**Comment by legodude17** [comment]
Your `npm` version is years old and no longer supported. Please update using `npm i -g npm@latest`.
