### ISSUE TITLE
npm ERR! cb() never called! 

### ISSUE THREAD

**Issue by stefanrusso** [npm/npm#20599]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
When I run `sudo npm install -g learnyounode`, I get the following error:
```
npm WARN deprecated boganipsum@0.1.0: no longer maintained
npm WARN deprecated colors-tmpl@1.0.0: no longer maintained
Unhandled rejection Error: Command failed: /usr/bin/git submodule update -q --init --recursiveode_modul
fatal: failed to stat '/root/.npm/_cacache/tmp/git-clone-7115df01': Permission denied

    at ChildProcess.exithandler (child_process.js:282:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:957:16)
    at Socket.stream.socket.on (internal/child_process.js:378:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close [as _onclose] (net.js:598:12)

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-05-12T02_28_49_914Z-debug.log
```

#### How can the CLI team reproduce the problem?
* `sudo npm install -g learnyounode`

[2018-05-12T01_29_21_515Z-debug.log](https://github.com/npm/npm/files/1997208/2018-05-12T01_29_21_515Z-debug.log)

### supporting information:

 - `npm -v` prints: 6.0.1
 - `node -v` prints: 10.1.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?:  Arch Linux
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by stefanrusso** [comment]
I managed to workaround the problem by downgrading npm to v5.10.

**Comment by asarantos78** [comment]
Run test

**Comment by legodude17** [comment]
@stefanrusso have you tried running it without `sudo`?
