### ISSUE TITLE
Help- error installing yeoman

### ISSUE THREAD

**Issue by snagul11** [npm/npm#20600]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [X ] npm is doing something I don't understand.
  - [X ] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Attempt to install yeoman using "npm install -g yo" failed with the following npm_debug.log.
#### How can the CLI team reproduce the problem?
Running command to install yeoman using "npm install -g yo" failed with the following npm_debug.log.

18833 verbose stack Error: shasum check failed for /tmp/npm-7940-f4516adc/registry.npmjs.org/twig/-/twig-0.8.9.tgz
18833 verbose stack Expected: b1594f002b684e5f029de3e54e87bec4f084b6c2
18833 verbose stack Actual:   52df0f0302d805359f626a902f2ae642e3c9421d
18833 verbose stack From:     https://registry.npmjs.org/twig/-/twig-0.8.9.tgz
18833 verbose stack     at /opt/developer/node-v6.5.0-linux-x64/lib/node_modules/npm/node_modules/sha/index.js:25:8
18833 verbose stack     at ReadStream.<anonymous> (/opt/developer/node-v6.5.0-linux-x64/lib/node_modules/npm/node_modules/sha/index.js:72:7)
18833 verbose stack     at emitNone (events.js:91:20)
18833 verbose stack     at ReadStream.emit (events.js:185:7)
18833 verbose stack     at endReadableNT (_stream_readable.js:974:12)
18833 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:74:11)
18833 verbose stack     at process._tickCallback (internal/process/next_tick.js:98:9)
18834 verbose cwd /home/vagrant/try/angular
18835 error Linux 3.8.13-44.1.1.el6uek.x86_64
18836 error argv "/opt/developer/node-v6.5.0-linux-x64/bin/node" "/opt/developer/node-v6.5.0-linux-x64/bin/npm" "install" "-g" "yo"
18837 error node v6.5.0
18838 error npm  v3.10.3
18839 error shasum check failed for /tmp/npm-7940-f4516adc/registry.npmjs.org/twig/-/twig-0.8.9.tgz
18839 error Expected: b1594f002b684e5f029de3e54e87bec4f084b6c2
18839 error Actual:   52df0f0302d805359f626a902f2ae642e3c9421d
18839 error From:     https://registry.npmjs.org/twig/-/twig-0.8.9.tgz
18840 error If you need help, you may report this error at:
18840 error     <https://github.com/npm/npm/issues>
18841 verbose exit [ 1, true ]

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ X] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ X] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
Hello! This is a duplicate of #14626. Try updating to the latest version of `npm`, as it was fixed there.
