### ISSUE TITLE
npm ERR! cb() never called!

### ISSUE THREAD

**Issue by mrpatel15** [npm/npm#20627]
#### I'm opening this issue because:

  - [ x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

^C░░░░░░░░░░░░░░░░░⸩ ⠧ rollbackFailedOptional: verb npm-session a23325ff18a07160
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mqs618/.npm/_logs/2018-05-15T13_50_35_327Z-debug.log
784f43846ad4:fs-app mqs618$ 
784f43846ad4:fs-app mqs618$ 
784f43846ad4:fs-app mqs618$ npm install
⸨  ░░░░░░░░░░░░░░░░⸩ ⠙ fetchMetadata: sill fetchPackageMetaData error for @angular/forms@^6.0.0 503 Service Unavailable: @angular/forms@^6.0

**Comment by mrpatel15** [comment]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--ignore-scripts',
1 verbose cli   'types-registry' ]
2 info using npm@6.0.0
3 info using node@v8.11.1
4 verbose npm-session d59050bebae30bca
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 **http fetch GET 503 https://registry.npmjs.org/types-registry 70210ms attempt #3
8 silly fetchPackageMetaData error for types-registry@^0.1.386 503 Service Unavailable: types-registry@^0.1.386**
9 timing stage:rollbackFailedOptional Completed in 1ms
10 timing stage:runTopLevelLifecycles Completed in 70415ms
11 verbose stack Error: 503 Service Unavailable: types-registry@^0.1.386
11 verbose stack     at fetch.then.res (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:42:19)
11 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
11 verbose stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
11 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
11 verbose stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
11 verbose stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
11 verbose stack     at Async._drainQueue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
11 verbose stack     at Async._drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
11 verbose stack     at Immediate.Async.drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
11 verbose stack     at runCallback (timers.js:794:20)
11 verbose stack     at tryOnImmediate (timers.js:752:5)
11 verbose stack     at processImmediate [as _immediateCallback] (timers.js:729:5)
12 verbose cwd /Users/mqs618/Library/Caches/typescript/2.7
13 verbose Darwin 17.5.0
14 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--ignore-scripts" "types-registry"
15 verbose node v8.11.1
16 verbose npm  v6.0.0
17 error code E503
18 error 503 Service Unavailable: types-registry@^0.1.386
19 verbose exit [ 1, true ]

**Comment by legodude17** [comment]
Does it work if you try again? Or is this consistent?

**Comment by gbougakov** [comment]
Please, use `code` tags
