### ISSUE TITLE
NPM crashes if `NODE_OPTIONS` env contains `--experimental-modules`

### ISSUE THREAD

**Issue by Alhadis** [npm/npm#20623]
#### I'm opening this issue because:

  - [X] `npm` is crashing, and it's crashing hard.
  - [ ] ~~npm is producing an incorrect install.~~
  - [ ] ~~npm is doing something I don't understand.~~
  - [ ] ~~npm is producing incorrect or undesirable behaviour.~~

#### What's going wrong?

NPM carks it if I have this set in my environment:

~~~shell
export NODE_OPTIONS='--no-warnings  --experimental-modules --experimental-repl-await --experimental-vm-modules'
~~~

It crashes when running `npm lint`, `npm -g doctor`, `npm -g update`, and several other commands that generate the same error:

~~~console
λ Accordion (master): npm run --verbose lint
npm info it worked if it ends with ok
npm verb cli [ '/usr/local/Cellar/node/10.1.0/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'run',
npm verb cli   '--verbose',
npm verb cli   'lint' ]
npm info using npm@6.0.1
npm info using node@v10.1.0
npm verb run-script [ 'prelint', 'lint', 'postlint' ]
npm info lifecycle accordion@2.1.1~prelint: accordion@2.1.1
npm info lifecycle accordion@2.1.1~lint: accordion@2.1.1
npm verb stack TypeError: Cannot read property 'filename' of undefined
npm verb stack     at /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:64:39
npm verb stack     at /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:184:12
npm verb stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:287:18
npm verb stack     at FSReqWrap.oncomplete (fs.js:166:5)
npm verb cwd /Users/johngardner/Labs/Accordion
npm verb Darwin 17.5.0
npm verb argv "/usr/local/Cellar/node/10.1.0/bin/node" "/usr/local/bin/npm" "run" "--verbose" "lint"
npm verb node v10.1.0
npm verb npm  v6.0.1
npm ERR! Cannot read property 'filename' of undefined
npm verb exit [ 1, true ]
npm timing npm Completed in 111ms

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/johngardner/.npm/_logs/2018-05-15T07_08_34_042Z-debug.log
~~~

The "complete" log doesn't really say much that the `--verbose` output already describes above:

~~~
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/10.1.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   '--verbose',
1 verbose cli   'lint' ]
2 info using npm@6.0.1
3 info using node@v10.1.0
4 verbose run-script [ 'prelint', 'lint', 'postlint' ]
5 info lifecycle accordion@2.1.1~prelint: accordion@2.1.1
6 info lifecycle accordion@2.1.1~lint: accordion@2.1.1
7 verbose stack TypeError: Cannot read property 'filename' of undefined
7 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:64:39
7 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:184:12
7 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:287:18
7 verbose stack     at FSReqWrap.oncomplete (fs.js:166:5)
8 verbose cwd /Users/johngardner/Labs/Accordion
9 verbose Darwin 17.5.0
10 verbose argv "/usr/local/Cellar/node/10.1.0/bin/node" "/usr/local/bin/npm" "run" "--verbose" "lint"
11 verbose node v10.1.0
12 verbose npm  v6.0.1
13 error Cannot read property 'filename' of undefined
14 verbose exit [ 1, true ]
~~~

I've confirmed that it's `--experimental-modules` specifically that's triggering the error, because commands operate as normal if that switch is unset from the `node_options` variable:

~~~diff
-export NODE_OPTIONS='--no-warnings --experimental-modules --experimental-repl-await --experimental-vm-modules'
+export NODE_OPTIONS='--no-warnings --experimental-repl-await --experimental-vm-modules'
~~~

#### How can the CLI team reproduce the problem?
Stick this in your shell's `.profile` or equivalent:

~~~shell
NODE_OPTIONS='--no-warnings'
NODE_OPTIONS="$NODE_OPTIONS --experimental-modules"
NODE_OPTIONS="$NODE_OPTIONS --experimental-repl-await"
NODE_OPTIONS="$NODE_OPTIONS --experimental-vm-modules"
export NODE_OPTIONS
~~~

Then run `npm run lint` on a repository with the `NODE_OPTIONS` variable set in your environment.

### supporting information:

~~~console
λ npm --version
6.0.1

λ node --version
v10.1.0

λ uname -v
Darwin Kernel Version 17.5.0: Fri Apr 13 19:32:32 PDT 2018; root:xnu-4570.51.2~1/RELEASE_X86_64

λ npm config list
; cli configs
metrics-registry = "https://registry.npmjs.org/"
scope = ""
user-agent = "npm/6.0.1 node/v10.1.0 darwin x64"

; userconfig /Users/johngardner/.npmrc
package-lock = false
save = false

; builtin config undefined
prefix = "/usr/local"

; node bin location = /usr/local/Cellar/node/10.1.0/bin/node
; cwd = /Users/johngardner/Labs/Accordion
; HOME = /Users/johngardner
~~~

No proxies or unusual network conditions present.

**Comment by cambecc** [comment]
Encountering this issue too. Only requires install of `fsevents`. Here's a smaller repro:

In a new directory, create this `package.json`:
```
{
  "name": "bug1",
  "version": "1.0.0",
  "dependencies": {
    "fsevents": "1.2.4"
  }
}
```
Then run:
```
NODE_OPTIONS="--experimental-modules" && npm install --verbose
```
Result:
```
(node:41097) ExperimentalWarning: The ESM module loader is experimental.
npm info it worked if it ends with ok
npm verb cli [ '/usr/local/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'install',
npm verb cli   '--verbose' ]
npm info using npm@5.6.0
npm info using node@v10.2.1
... [elided]
npm info lifecycle fsevents@1.2.4~install: fsevents@1.2.4
npm verb stack TypeError: Cannot read property 'filename' of undefined
npm verb stack     at /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:66:39
npm verb stack     at /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:186:12
npm verb stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:287:18
npm verb stack     at FSReqWrap.oncomplete (fs.js:183:5)
npm verb cwd /Users/cambecc/code/bug1
npm verb Darwin 17.5.0
npm verb argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--verbose"
npm verb node v10.2.1
npm verb npm  v5.6.0
npm ERR! Cannot read property 'filename' of undefined
npm verb exit [ 1, true ]

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/cambecc/.npm/_logs/2018-06-09T06_08_51_621Z-debug.log
```
When ES module support is not enabled, installation works fine:
```
NODE_OPTIONS="" && npm install --verbose
```

**Comment by Alhadis** [comment]
FWIW, the standalone [`electron`](https://www.npmjs.com/package/electron) binary was crashing too (macOS lit up with a full-on fatal error), and it too was solved by unsetting this variable. :thinking:
