### ISSUE TITLE
Can't download angular

### ISSUE THREAD

**Issue by CamiloPinzon** [npm/npm#20630]
#### I'm opening this issue because:

Can't download Angular

#### What's going wrong?

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\andres.pinzon\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   '@angular/cli' ]
2 info using npm@2.15.11
3 info using node@v8.11.1
4 verbose install initial load of C:\Users\andres.pinzon\AppData\Roaming\npm\package.json
5 verbose readDependencies loading dependencies from C:\Users\andres.pinzon\AppData\Roaming\npm\package.json
6 silly cache add args [ '@angular/cli', null ]
7 verbose cache add spec @angular/cli
8 silly cache add parsed spec Result {
8 silly cache add   raw: '@angular/cli',
8 silly cache add   scope: '@angular',
8 silly cache add   name: '@angular/cli',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: 'latest',
8 silly cache add   type: 'tag' }
9 silly addNamed @angular/cli@latest
10 verbose addNamed "latest" is being treated as a dist-tag for @angular/cli
11 info addNameTag [ '@angular/cli', 'latest' ]
12 silly mapToRegistry name @angular/cli
13 silly mapToRegistry scope (from package name) @angular
14 verbose mapToRegistry no registry URL found in name for scope @angular
15 silly mapToRegistry using default registry
16 silly mapToRegistry registry http://npm.cloud.corp.dig.com/
17 silly mapToRegistry data Result {
17 silly mapToRegistry   raw: '@angular/cli',
17 silly mapToRegistry   scope: '@angular',
17 silly mapToRegistry   name: '@angular/cli',
17 silly mapToRegistry   rawSpec: '',
17 silly mapToRegistry   spec: 'latest',
17 silly mapToRegistry   type: 'tag' }
18 silly mapToRegistry uri http://npm.cloud.corp.dig.com/@angular%2fcli
19 verbose addNameTag registry:http://npm.cloud.corp.dig.com/@angular%2fcli not in flight; fetching
20 verbose request uri http://npm.cloud.corp.dig.com/@angular%2fcli
21 verbose request no auth needed
22 info attempt registry request try #1 at 11:20:14
23 verbose request id 4cf074fbcb2bd5b7
24 http request GET http://npm.cloud.corp.dig.com/@angular%2fcli
25 info retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN npm.cloud.corp.dig.com:80
26 info attempt registry request try #2 at 11:20:24
27 http request GET http://npm.cloud.corp.dig.com/@angular%2fcli
28 info retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN npm.cloud.corp.dig.com:80
29 info attempt registry request try #3 at 11:21:24
30 http request GET http://npm.cloud.corp.dig.com/@angular%2fcli
31 verbose stack Error: getaddrinfo EAI_AGAIN npm.cloud.corp.dig.com:80
31 verbose stack     at Object._errnoException (util.js:1022:11)
31 verbose stack     at errnoException (dns.js:55:15)
31 verbose stack     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
32 verbose cwd C:\Users\andres.pinzon
33 error Windows_NT 10.0.16299
34 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\andres.pinzon\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@angular/cli"
35 error node v8.11.1
36 error npm  v2.15.11
37 error code EAI_AGAIN
38 error errno EAI_AGAIN
39 error syscall getaddrinfo
40 error getaddrinfo EAI_AGAIN npm.cloud.corp.dig.com:80
41 error If you need help, you may report this error at:
41 error     <https://github.com/npm/npm/issues>
42 verbose exit [ 1, true ]

![image](https://user-images.githubusercontent.com/10146203/40070078-b973ac2a-5832-11e8-90be-377e07bd8a6e.png)

**Comment by legodude17** [comment]
Do you have an unstable internet connection or proxy?

**Comment by nerumo** [comment]
I'm having the same issue, tried from azure west europe and switzerland, constantly dies, since yesterday

**Comment by jotatoledo** [comment]
Related to https://github.com/angular/angular/issues/23931

**Comment by RobPierce** [comment]
I'm getting issues not just with Angular but also with @ng-bootstrap and @uirouter so not sure if it is just angular related (or if they are having issues as they reference angular)?

**Comment by legodude17** [comment]
Do you have an unstable internet connection or proxy?
