### ISSUE TITLE
Registry returned 405 for GET with npm ping

### ISSUE THREAD

**Issue by mansona** [npm/npm#20655]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] npm is producing incorrect or undesirable behavior.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?
I'm using a package called [np](https://www.npmjs.com/package/np) to help me publish packages, and as part of its process it runs `npm ping` to see if the npm registry is accessible. I am able to install things from npm so there isn't anything wrong with my network but when I run `npm ping` it gives the following error: 

```
Ping error: Error: Registry returned 405 for GET on https://registry.npmjs.org/-/ping?write=true
npm ERR! code E405
npm ERR! Registry returned 405 for GET on https://registry.npmjs.org/-/ping?write=true

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mansona/.npm/_logs/2018-05-17T09_30_47_592Z-debug.log
```

The contents of that debug log are as follows:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'ping' ]
2 info using npm@6.0.1
3 info using node@v10.0.0
4 verbose request uri https://registry.npmjs.org/-/ping?write=true
5 verbose request no auth needed
6 info attempt registry request try #1 at 10:21:13
7 verbose request using bearer token for auth
8 verbose request id bf00ef164a8e0e54
9 http request GET https://registry.npmjs.org/-/ping?write=true
10 http 405 https://registry.npmjs.org/-/ping?write=true
11 verbose headers { allow: 'PUT',
11 verbose headers   'content-type': 'application/json',
11 verbose headers   'cache-control': 'max-age=0',
11 verbose headers   'content-length': '63',
11 verbose headers   'accept-ranges': 'bytes',
11 verbose headers   date: 'Thu, 17 May 2018 09:21:13 GMT',
11 verbose headers   via: '1.1 varnish',
11 verbose headers   connection: 'keep-alive',
11 verbose headers   'x-served-by': 'cache-lhr6348-LHR',
11 verbose headers   'x-cache': 'MISS',
11 verbose headers   'x-cache-hits': '0',
11 verbose headers   'x-timer': 'S1526548874.536217,VS0,VE158' }
12 verbose stack Error: Registry returned 405 for GET on https://registry.npmjs.org/-/ping?write=true
12 verbose stack     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:316:12)
12 verbose stack     at RegClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:292:14)
12 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:216:14)
12 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:186:22)
12 verbose stack     at Request.emit (events.js:182:13)
12 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1163:10)
12 verbose stack     at Request.emit (events.js:182:13)
12 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1085:12)
12 verbose stack     at Object.onceWrapper (events.js:275:13)
12 verbose stack     at IncomingMessage.emit (events.js:187:15)
13 verbose statusCode 405
14 verbose cwd /Users/mansona/git/stonecircle/opensource/ember-casper-template
15 verbose Darwin 17.5.0
16 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "ping"
17 verbose node v10.0.0
18 verbose npm  v6.0.1
19 error code E405
20 error Registry returned 405 for GET on https://registry.npmjs.org/-/ping?write=true
21 verbose exit [ 1, true ]
```

I thought it might have something to do with npm@6 so I used the npx trick to try npm@5: `npx npm@5 ping` which gave this debug output: 

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/Users/mansona/.npm/_npx/52262/bin/npm',
1 verbose cli   'ping' ]
2 info using npm@5.10.0
3 info using node@v10.0.0
4 verbose request uri https://registry.npmjs.org/-/ping?write=true
5 verbose request no auth needed
6 info attempt registry request try #1 at 10:31:55
7 verbose request using bearer token for auth
8 verbose request id cfc532893cde7793
9 http request GET https://registry.npmjs.org/-/ping?write=true
10 http 405 https://registry.npmjs.org/-/ping?write=true
11 verbose headers { allow: 'PUT',
11 verbose headers   'content-type': 'application/json',
11 verbose headers   'cache-control': 'max-age=0',
11 verbose headers   'content-length': '63',
11 verbose headers   'accept-ranges': 'bytes',
11 verbose headers   date: 'Thu, 17 May 2018 09:32:00 GMT',
11 verbose headers   via: '1.1 varnish',
11 verbose headers   connection: 'keep-alive',
11 verbose headers   'x-served-by': 'cache-hhn1527-HHN',
11 verbose headers   'x-cache': 'MISS',
11 verbose headers   'x-cache-hits': '0',
11 verbose headers   'x-timer': 'S1526549520.090610,VS0,VE693' }
12 verbose stack Error: Registry returned 405 for GET on https://registry.npmjs.org/-/ping?write=true
12 verbose stack     at makeError (/Users/mansona/.npm/_npx/52262/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:316:12)
12 verbose stack     at RegClient.<anonymous> (/Users/mansona/.npm/_npx/52262/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:292:14)
12 verbose stack     at Request._callback (/Users/mansona/.npm/_npx/52262/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:216:14)
12 verbose stack     at Request.self.callback (/Users/mansona/.npm/_npx/52262/lib/node_modules/npm/node_modules/request/request.js:186:22)
12 verbose stack     at Request.emit (events.js:182:13)
12 verbose stack     at Request.<anonymous> (/Users/mansona/.npm/_npx/52262/lib/node_modules/npm/node_modules/request/request.js:1163:10)
12 verbose stack     at Request.emit (events.js:182:13)
12 verbose stack     at IncomingMessage.<anonymous> (/Users/mansona/.npm/_npx/52262/lib/node_modules/npm/node_modules/request/request.js:1085:12)
12 verbose stack     at Object.onceWrapper (events.js:275:13)
12 verbose stack     at IncomingMessage.emit (events.js:187:15)
13 verbose statusCode 405
14 verbose cwd /Users/mansona/git/stonecircle/opensource/ember-casper-template
15 verbose Darwin 17.5.0
16 verbose argv "/usr/local/bin/node" "/Users/mansona/.npm/_npx/52262/bin/npm" "ping"
17 verbose node v10.0.0
18 verbose npm  v5.10.0
19 error code E405
20 error Registry returned 405 for GET on https://registry.npmjs.org/-/ping?write=true
21 verbose exit [ 1, true ]
```

#### How can the CLI team reproduce the problem?
I can't really tell what the problem is... I have tried it on multiple networks (and a VPN) so I doubt it's a proxy issue.

### supporting information:

 - `npm -v` prints: 6.0.1
 - `node -v` prints: v10.0.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: macOS
 - Network issues:
   - Geographic location where npm was run: Ireland
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by mansona** [comment]
I've just been able to publish a package but `npm ping` is still not working

**Comment by yetithefoot** [comment]
Same for me, using `np`, but also tried `npm publish`. Getting 405 on publish private package to organisation:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'ping' ]
2 info using npm@5.6.0
3 info using node@v8.9.1
4 verbose request uri https://registry.npmjs.org/-/ping?write=true
5 verbose request no auth needed
6 info attempt registry request try #1 at 16:40:32
7 verbose request using bearer token for auth
8 verbose request id 1163b42c3aa719d6
9 http request GET https://registry.npmjs.org/-/ping?write=true
10 http 405 https://registry.npmjs.org/-/ping?write=true
11 verbose headers { allow: 'PUT',
11 verbose headers   'content-type': 'application/json',
11 verbose headers   'cache-control': 'max-age=0',
11 verbose headers   'content-length': '63',
11 verbose headers   'accept-ranges': 'bytes',
11 verbose headers   date: 'Thu, 17 May 2018 13:40:33 GMT',
11 verbose headers   via: '1.1 varnish',
11 verbose headers   connection: 'keep-alive',
11 verbose headers   'x-served-by': 'cache-bma7026-BMA',
11 verbose headers   'x-cache': 'MISS',
11 verbose headers   'x-cache-hits': '0',
11 verbose headers   'x-timer': 'S1526564433.392647,VS0,VE195' }
12 verbose stack Error: Registry returned 405 for GET on https://registry.npmjs.org/-/ping?write=true
12 verbose stack     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:314:12)
12 verbose stack     at RegClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:292:14)
12 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:216:14)
12 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:186:22)
12 verbose stack     at emitTwo (events.js:126:13)
12 verbose stack     at Request.emit (events.js:214:7)
12 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1163:10)
12 verbose stack     at emitOne (events.js:116:13)
12 verbose stack     at Request.emit (events.js:211:7)
12 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1085:12)
12 verbose stack     at Object.onceWrapper (events.js:313:30)
12 verbose stack     at emitNone (events.js:111:20)
12 verbose stack     at IncomingMessage.emit (events.js:208:7)
12 verbose stack     at endReadableNT (_stream_readable.js:1056:12)
12 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:138:11)
12 verbose stack     at process._tickCallback (internal/process/next_tick.js:180:9)
13 verbose statusCode 405
14 verbose cwd /Users/username/Developer/Projects/projectname
15 verbose Darwin 17.3.0
16 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "ping"
17 verbose node v8.9.1
18 verbose npm  v5.6.0
19 error code E405
20 error Registry returned 405 for GET on https://registry.npmjs.org/-/ping?write=true
21 verbose exit [ 1, true ]
```

**Comment by legodude17** [comment]
This probably means you aren't logged in correctly. Try `npm logout && npm login`.

**Comment by gmcdev** [comment]
`npm ping` produces
`Ping success: {}`

Tried `npm logout && npm login`, no dice.

**Comment by legodude17** [comment]
@gmcdev your `npm ping` appears to be working correctly. What is the issue?

**Comment by gmcdev** [comment]
The issue is at hand is that using [np](https://github.com/sindresorhus/np) to publish to NPM was (since last night) failing.

As for `npm ping` the docs say it should return:
Ping success: {*Details about registry*}

So, those two things together, led me to believe that an empty response object was perhaps a clue or further evidence.

All that aside, publish with `np` appears to be working again, and `npm ping` still returns an empty object. So I guess that's expected behavior. Disregard.

To the others, give it another shot. I did notice last night they were working on something https://status.npmjs.org/
