### ISSUE TITLE
npm  publish  to nexus 401 Unauthorized

### ISSUE THREAD

**Issue by VladCherniavsky** [npm/npm#20695]
#### I'm opening this issue because:

  - npm is doing something I don't understand.

#### What's going wrong?

npm  package not published to nexus

I nave Nexus OSS with configured host repository for my modules.
User is added to npm.
After `npm  publish` there is error in console: `npm ERR! 401 Unauthorized`

.npmrc
```
registry=https://172.32.29.226/nexus/repository/internal/
_auth=QJX01vYfmlsZV9smdWxsOfjEyM3ZWFzZHp4Yw==
```

log:
```
34 http request PUT https://172.32.29.226/nexus/repository/internal/ajax-queue
35 http 401 https://172.32.29.226/nexus/repository/internal/ajax-queue
36 verbose headers { server: 'nginx/1.10.3',
36 verbose headers   date: 'Mon, 21 May 2018 11:56:35 GMT',
36 verbose headers   'content-length': '0',
36 verbose headers   connection: 'keep-alive',
36 verbose headers   'x-frame-options': 'SAMEORIGIN',
36 verbose headers   'x-content-type-options': 'nosniff',
36 verbose headers   'www-authenticate': 'BASIC realm="Sonatype Nexus Repository Manager"' }
37 verbose request invalidating C:\Users\my_name\AppData\Roaming\npm-cache\172.32.29.226\nexus\repository\internal\ajax-queue on PUT
38 error publish Failed PUT 401
39 verbose stack Error: 401 Unauthorized
39 verbose stack     at makeError (C:\Users\my_name\AppData\Roaming\nvm\v6.11.2\node_modules\npm\node_modules\npm-registry-client\lib\request.js:302:12)
39 verbose stack     at CachingRegistryClient.<anonymous> (C:\Users\my_name\AppData\Roaming\nvm\v6.11.2\node_modules\npm\node_modules\npm-registry-client\lib\request.js:253:9)
39 verbose stack     at Request._callback (C:\Users\my_name\AppData\Roaming\nvm\v6.11.2\node_modules\npm\node_modules\npm-registry-client\lib\request.js:210:14)
39 verbose stack     at Request.self.callback (C:\Users\my_name\AppData\Roaming\nvm\v6.11.2\node_modules\npm\node_modules\request\request.js:187:22)
39 verbose stack     at emitTwo (events.js:106:13)
```
node version: `6.11.2` & `9.5.0`

**Comment by adamatti** [comment]
The solution described [here](https://stackoverflow.com/questions/39460074/unable-to-publish-to-an-npm-registry-local) worked for me (add the npm realm)
