### ISSUE TITLE
npm6 doesn't work with node 4 anymore.

### ISSUE THREAD

**Issue by nicolasnoble** [npm/npm#20716]
#### I'm opening this issue because:

  - [X] npm is crashing.

#### What's going wrong?
Starting with npm6, npm doesn't work with node 4 anymore. This would be fine if the README of npm wouldn't say that it's in fact working with node 4. One simple resolution would be to update the README accordingly to the reality of things, if we really want to drop node 4 support.

#### How can the CLI team reproduce the problem?
```
$ nvm install 4
Downloading https://nodejs.org/dist/v4.9.1/node-v4.9.1-linux-x64.tar.xz...
############################################################################################################################################ 100.0%
Now using node v4.9.1 (npm v2.15.11)
$ npm install -g npm
/home/pixel/.nvm/versions/node/v4.9.1/bin/npm -> /home/pixel/.nvm/versions/node/v4.9.1/lib/node_modules/npm/bin/npm-cli.js
/home/pixel/.nvm/versions/node/v4.9.1/bin/npx -> /home/pixel/.nvm/versions/node/v4.9.1/lib/node_modules/npm/bin/npx-cli.js
npm@6.0.1 /home/pixel/.nvm/versions/node/v4.9.1/lib/node_modules/npm
$ npm
/home/pixel/.nvm/versions/node/v4.9.1/lib/node_modules/npm/bin/npm-cli.js:79
      let notifier = require('update-notifier')({pkg})
      ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
    at node.js:1043:3
```

**Comment by legodude17** [comment]
The README is being updated in the next release, see https://github.com/npm/npm/blob/release-next/CHANGELOG.md#documentation

**Comment by nicolasnoble** [comment]
Cool, didn't see this. Thanks :)
