### ISSUE TITLE
socket.io-client install problem

### ISSUE THREAD

**Issue by nedol** [npm/npm#20725]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ +] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
npm ERR! code EINVALIDTYPE
npm ERR! typeerror Error: Argument #5: Expected object but got string
npm ERR! typeerror     at inflatableChild (C:\Users\android\AppData\Roaming\npm\node_modules\npm\lib\install\inflate-shrinkwrap.js:73:3)
npm ERR! typeerror     at BB.each (C:\Users\android\AppData\Roaming\npm\node_modules\npm\lib\install\inflate-shrinkwrap.js:55:12)
npm ERR! typeerror     at tryCatcher (C:\Users\android\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
npm ERR! typeerror     at Object.gotValue (C:\Users\android\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\reduce.js:155:18)
npm ERR! typeerror     at Object.gotAccum (C:\Users\android\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\reduce.js:144:25)
npm ERR! typeerror     at Object.tryCatcher (C:\Users\android\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
npm ERR! typeerror     at Promise._settlePromiseFromHandler (C:\Users\android\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:
512:31)
npm ERR! typeerror     at Promise._settlePromise (C:\Users\android\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
npm ERR! typeerror     at Promise._settlePromise0 (C:\Users\android\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
npm ERR! typeerror     at Promise._settlePromises (C:\Users\android\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
npm ERR! typeerror     at Async._drainQueue (C:\Users\android\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
npm ERR! typeerror     at Async._drainQueues (C:\Users\android\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
npm ERR! typeerror     at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\android\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release
\async.js:17:14)
npm ERR! typeerror     at runCallback (timers.js:763:18)
npm ERR! typeerror     at tryOnImmediate (timers.js:734:5)
npm ERR! typeerror     at processImmediate (timers.js:716:5)
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <https://github.com/npm/npm/issues>

#### How can the CLI team reproduce the problem?
npm i socket.io-client

### supporting information:

 - `npm -v` prints: 6.0.1
 - `node -v` prints:v9.7.0
 - `npm config get registry` prints:https://registry.npmjs.org/
 - Windows 10:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
Could you upload the npm-debug.log as a plaintext file to https://gist.github.com/ and post a link to it here?

**Comment by nedol** [comment]
https://gist.github.com/nedol/8245c771df6d168afd298e4a7595fab6#file-gistfile1-txt

**Comment by cwadrupldijjit** [comment]
My guess (based off of the stack trace and working with somebody with the same problem) is that there is an inconsistency of some kind inside of the `package-lock.json` where it isn't as expected.

I'm guessing that there could've been a merge conflict that was resolved funny or the lockfile wasn't generated correctly.  I'm not sure what to do about it, but in their particular case, deleting the lockfile and then re-installing worked (though it's not really ideal).

**Comment by legodude17** [comment]
@nedol What does your `package-lock.json` look like?
