### ISSUE TITLE
npm cannot install

### ISSUE THREAD

**Issue by samtob** [npm/npm#20746]
This is the error npm is showing me wheever i want to install 
npm ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\user\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "i"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.4
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'internal/util/types'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\npm-debug.log

this is what is inside npm-debug.log

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\user\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'i' ]
2 info using npm@3.5.4
3 info using node@v8.10.0
4 verbose stack Error: Cannot find module 'internal/util/types'
4 verbose stack     at Function.Module._resolveFilename (module.js:547:15)
4 verbose stack     at Function.Module._load (module.js:474:25)
4 verbose stack     at Module.require (module.js:596:17)
4 verbose stack     at require (internal/module.js:11:18)
4 verbose stack     at evalmachine.<anonymous>:31:26
4 verbose stack     at Object.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\npm\node_modules\cmd-shim\node_modules\graceful-fs\fs.js:11:1)
4 verbose stack     at Module._compile (module.js:652:30)
4 verbose stack     at Object.Module._extensions..js (module.js:663:10)
4 verbose stack     at Module.load (module.js:565:32)
4 verbose stack     at tryModuleLoad (module.js:505:12)
5 verbose cwd C:\
6 error Windows_NT 10.0.16299
7 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\user\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "i"
8 error node v8.10.0
9 error npm  v3.5.4
10 error code MODULE_NOT_FOUND
11 error Cannot find module 'internal/util/types'
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]

**Comment by legodude17** [comment]
My best guess is that your npm installation got broken somehow. Unfortunately you will probably have to reinstall node to get a working version of npm.

**Comment by samtob** [comment]
All right. Thanks

**Comment by samtob** [comment]
I have uninstalled and installed it again, it's still giving me the same error.

**Comment by legodude17** [comment]
What is the result of `npm -v`?

**Comment by samtob** [comment]
the result is 3.5.4

**Comment by vamshi9666** [comment]
thats too outdated . could you update it to 6.x and try to reproduce same err ?

**Comment by mayouchen123** [comment]
I also encountered the same problem. Reinstallation is useless.

```
D:\Program Files\项目\goverment\weixin-platform-frontend>npm install -g n
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\Program Files\\软件\\node\\node.exe" "D:\\Users\\MAYOUCHEN346
\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "n"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.4
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'internal/util/types'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Program Files\项目\goverment\weixin-platform-frontend\npm-debug.
log
```

**Comment by samtob** [comment]
It's been solved. I tried upgrading but did not work using npm i/install update npm@latest. What I actually did is that I searched for this "c:/user/user/Appdata/roaming/npm" and deleted it and all it dependencies. I also deleted it from the environment variables and reinstalled node and that solve the problem
