### ISSUE TITLE
Firebase Deploy failed

### ISSUE THREAD

**Issue by lu6ljy** [npm/npm#20754]
#### I'm opening this issue because:

   - [x] npm is doing something I don't understand.
 
#### What's going wrong?
When I tried to deploy a web app by using command "firebase deploy", the errors occurred:
=== Deploying to 'friendlypix-fa643'...

i  deploying database, storage, functions, hosting
Running command: npm --prefix functions install
npm ERR! addLocal Could not install C:\Users\friendlypix-web
npm ERR! Windows_NT 10.0.17134
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "--prefix" "functions" "install"
npm ERR! node v6.11.5
npm ERR! npm  v3.10.10

npm ERR! No name provided in package.json
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\friendlypix-web\npm-debug.log

Error: functions predeploy error: Command terminated with non-zero exit code1

Having trouble? Try firebase deploy --help

###The npm-debug.log is:
    0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   '--prefix',
1 verbose cli   './functions/',
1 verbose cli   'run',
1 verbose cli   'lint' ]
2 info using npm@3.10.10
3 info using node@v6.11.5
4 verbose stack Error: missing script: lint
4 verbose stack     at run (C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:151:19)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:61:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:356:5
4 verbose stack     at checkBinReferences_ (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:320:45)
4 verbose stack     at final (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:354:3)
4 verbose stack     at then (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:124:5)
4 verbose stack     at ReadFileContext.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:295:20)
4 verbose stack     at ReadFileContext.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16)
4 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:367:13)
5 verbose cwd C:\Users\friendlypix-web
6 error Windows_NT 10.0.17134
7 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "--prefix" "./functions/" "run" "lint"
8 error node v6.11.5
9 error npm  v3.10.10
10 error missing script: lint
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

### supporting information:

 - `npm -v` prints: 3.10.10
 - `node -v` prints: v6.11.5
 - `npm config get registry` prints:https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows 10

**Comment by legodude17** [comment]
What does your `package.json` look like?

**Comment by lu6ljy** [comment]
Here is my `package.json`:

 {

  "scripts": {
    "build": "npm install && babel public/scripts -s --minified --compact true -d public/scripts-es5 && bower install && echo 'Done. Ready to deploy.'",
    "serve": "npm install && bower install && concurrently \"firebase serve\" \"babel -w public/scripts -s --retain-lines -d public/scripts-es5\""
  },
  "devDependencies": {
    "babel-cli": "^6.26.0",
    "babel-preset-es2015": "^6.6.0",
    "bower": "^1.8.2",
    "concurrently": "^3.5.1",
    "firebase-tools": "^3.18.0"
  },
  "private": true,
  "dependencies": {
    "eslint": "^4.19.1",
    "eslint-config-google": "^0.9.1"
  }
}

**Comment by legodude17** [comment]
Then, the problem is that you don't have a `lint` script defined. `npm run lint` needs you to have a `lint` script in your `package.json`.

**Comment by lu6ljy** [comment]
Thank you for the help! Would you mind to tell me how to modify the `package.json?`

**Comment by kenany** [comment]
How about something like this?:

```json
{
  "name": "my-package",
  "scripts": {
    "build": "npm install && babel public/scripts -s --minified --compact true -d public/scripts-es5 && bower install && echo 'Done. Ready to deploy.'",
    "serve": "npm install && bower install && concurrently 'firebase serve' 'babel -w public/scripts -s --retain-lines -d public/scripts-es5'",
    "lint": "eslint ."
  },
  "devDependencies": {
    "babel-cli": "^6.26.0",
    "babel-preset-es2015": "^6.6.0",
    "bower": "^1.8.2",
    "concurrently": "^3.5.1",
    "firebase-tools": "^3.18.0"
  },
  "private": true,
  "dependencies": {
    "eslint": "^4.19.1",
    "eslint-config-google": "^0.9.1"
  }
}
```

**Comment by lu6ljy** [comment]
Thank you for the help! But I still got the same error. 
I'm trying to make the demo code https://github.com/firebase/friendlypix-web to work on firebase cloud platform.

**Comment by legodude17** [comment]
What is the output of `npm run lint`?

**Comment by lu6ljy** [comment]
The output is `
> my-package@ lint C:\Users\friendlypix-web
> eslint .`

**Comment by legodude17** [comment]
Is that it? It appears to have worked then.

**Comment by lu6ljy** [comment]
I just found some errors after few minutes:

> Cannot find module '@ljharb/eslint-config'
Referenced from: C:\Users\friendlypix-web\functions\node_modules\body-parser\node_modules\qs\.eslintrc
Error: Cannot find module '@ljharb/eslint-config'
Referenced from: C:\Users\friendlypix-web\functions\node_modules\body-parser\node_modules\qs\.eslintrc
    at ModuleResolver.resolve (C:\Users\friendlypix-web\node_modules\eslint\lib\util\module-resolver.js:74:19)
    at resolve (C:\Users\friendlypix-web\node_modules\eslint\lib\config\config-file.js:479:28)
    at load (C:\Users\friendlypix-web\node_modules\eslint\lib\config\config-file.js:551:26)
    at configExtends.reduceRight.e (C:\Users\friendlypix-web\node_modules\eslint\lib\config\config-file.js:425:36)    at Array.reduceRight (native)
    at applyExtends (C:\Users\friendlypix-web\node_modules\eslint\lib\config\config-file.js:403:26)
    at loadFromDisk (C:\Users\friendlypix-web\node_modules\eslint\lib\config\config-file.js:523:22)
    at Object.load (C:\Users\friendlypix-web\node_modules\eslint\lib\config\config-file.js:559:20)
    at Config.getLocalConfigHierarchy (C:\Users\friendlypix-web\node_modules\eslint\lib\config.js:227:44)
    at Config.getConfigHierarchy (C:\Users\friendlypix-web\node_modules\eslint\lib\config.js:179:43)

npm ERR! Windows_NT 10.0.17134
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "lint"
npm ERR! node v6.11.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! my-package@ lint: `eslint .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my-package@ lint script 'eslint .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the my-package package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     eslint .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs my-package
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls my-package
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\friendlypix-web\npm-debug.log
