### ISSUE TITLE
Error: Cannot find module './auctionsoftware'

### ISSUE THREAD

**Issue by rajanbatra** [npm/npm#20777]
I need help with how to remove the above-mentioned error, auctionsoftware is the name of the folder in which my .js files are present. The complete error I am getting is as follows : 
Error: Cannot find module './auctionsoftware'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\batra\Desktop\auctionsoftware\app.js:8:23)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

Any help would be appreciated
Thank You

**Comment by mattcreta** [comment]
@rajanbatra could you please provide your folder structure for this project?

**Comment by rajanbatra** [comment]
@mattcreta sure.
C:\Users\batra\Desktop\auctionsoftware - this is where the folder auctionsoftware is present and it has all the below-mentioned files.
node_modules
routes (which has login.js)
app.js
login.html
package.json
register.html

Hope that helps you a bit.
