### ISSUE TITLE
error when try "Npm install -g react-native-cli"

### ISSUE THREAD

**Issue by mcandrak** [npm/npm#20782]
can someone help me ?

npm ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "react-native-cli"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10

npm ERR! error:0906D06C:PEM routines:PEM_read_bio:no start line
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     E:\Go Go\fifth\npm-debug.log

**Comment by simonyouth** [comment]
And as long as I use 'npm install module name' ,the same error will occur. How to fix?

**Comment by simonyouth** [comment]
```
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'react-native-cli' ]
2 info using npm@5.6.0
3 info using node@v8.11.2
4 verbose npm-session f1abbfd0ff68cee4
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData error for react-native-cli@latest error:0906D06C:PEM routines:PEM_read_bio:no start line
8 verbose stack Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
8 verbose stack     at Object.createSecureContext (_tls_common.js:104:17)
8 verbose stack     at Object.exports.connect (_tls_wrap.js:1049:48)
8 verbose stack     at HttpsAgent.createConnection (https.js:111:22)
8 verbose stack     at HttpsAgent.createSocket (D:\Program Files\nodejs\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\agentkeepalive\lib\_http_agent.js:271:26)
8 verbose stack     at HttpsAgent.createSocket (D:\Program Files\nodejs\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\agentkeepalive\lib\agent.js:77:11)
8 verbose stack     at HttpsAgent.addRequest (D:\Program Files\nodejs\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\agentkeepalive\lib\_http_agent.js:240:10)
8 verbose stack     at new ClientRequest (_http_client.js:258:16)
8 verbose stack     at Object.request (http.js:38:10)
8 verbose stack     at request (https.js:239:15)
8 verbose stack     at fetch.Promise (D:\Program Files\nodejs\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\node-fetch-npm\src\index.js:54:17)
8 verbose stack     at new Promise (<anonymous>)
8 verbose stack     at fetch (D:\Program Files\nodejs\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\node-fetch-npm\src\index.js:41:10)
8 verbose stack     at retry (D:\Program Files\nodejs\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\index.js:332:14)
8 verbose stack     at D:\Program Files\nodejs\node_modules\npm\node_modules\pacote\node_modules\promise-retry\index.js:29:24
8 verbose stack     at <anonymous>
9 verbose cwd C:\Users\Administrator
10 verbose Windows_NT 10.0.17134
11 verbose argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "react-native-cli"
12 verbose node v8.11.2
13 verbose npm  v5.6.0
14 error error:0906D06C:PEM routines:PEM_read_bio:no start line
15 verbose exit [ 1, true ]
```

**Comment by simonyouth** [comment]
I solved this problem via reconfiging the npm
