### ISSUE TITLE
npm doesn't let me adduser

### ISSUE THREAD

**Issue by davidalencia** [npm/npm#20790]
npm adduser 
 |
V
npm ERR! code EAUTHIP
npm ERR! Unable to authenticate, need: Basic

the same but with verbose 
Username: davidalencia
Password:
Email: (this IS public) davidalencia@gmail.com
npm verb login before first PUT { _id: 'org.couchdb.user:davidalencia',
npm verb login   name: 'davidalencia',
npm verb login   password: 'XXXXX',
npm verb login   type: 'user',
npm verb login   roles: [],
npm verb login   date: '2018-05-28T21:38:36.234Z' }
npm http request → PUT https://registry.npmjs.org/-/user/org.couchdb.user:davidalencia
npm http 401 ← Unauthorized (https://registry.npmjs.org/-/user/org.couchdb.user:davidalencia)
npm verb adduser before first PUT { _id: 'org.couchdb.user:davidalencia',
npm verb adduser   name: 'davidalencia',
npm verb adduser   password: 'XXXXX',
npm verb adduser   email: 'davidalencia@gmail.com',
npm verb adduser   type: 'user',
npm verb adduser   roles: [],
npm verb adduser   date: '2018-05-28T21:38:37.629Z' }
npm http request → PUT https://registry.npmjs.org/-/user/org.couchdb.user:davidalencia
npm http 401 ← Unauthorized (https://registry.npmjs.org/-/user/org.couchdb.user:davidalencia)
npm verb stack Error: Unable to authenticate, need: Basic
npm verb stack     at fetch.defaults.catch.then.then.result (/usr/lib/node_modules/npm/node_modules/npm-profile/index.js:373:15)
npm verb stack     at <anonymous>
npm verb stack     at process._tickCallback (internal/process/next_tick.js:188:7)
npm verb statusCode 401
npm verb cwd /home/valencia/Documents/node/timer
npm verb Linux 4.13.0-41-generic
npm verb argv "/usr/bin/node" "/usr/bin/npm" "adduser" "-verbose"
npm verb node v8.11.1
npm verb npm  v6.1.0
npm ERR! code EAUTHIP
npm ERR! Unable to authenticate, need: Basic
npm verb exit [ 1, true ]
npm timing npm Completed in 21075

**Comment by dthree** [comment]
See this issue:

https://github.com/npm/npm/issues/19088
