### ISSUE TITLE
Adding owner fails

### ISSUE THREAD

**Issue by vmx** [npm/npm#20801]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

Can't add a new owner to a package.

#### How can the CLI team reproduce the problem?

run `npm owner add user package`.

```
$ npm owner add victorbjelkholm ipld-bitcoin 
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! owner mutate Error getting user data for victorbjelkholm
npm ERR! Unexpected token N in JSON at position 0
npm ERR! No frontdoor hosts available

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vmx/.npm/_logs/2018-05-29T11_51_33_291Z-debug.log
```

I can also reproduce the `No frontdoor hosts available` error via curl:

```
$ curl -X GET 'https://registry.npmjs.org/-/user/org.couchdb.user:vmx' --verbose
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying 2400:cb00:2048:1::6812:6060...
* TCP_NODELAY set
* Connected to registry.npmjs.org (2400:cb00:2048:1::6812:6060) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-ECDSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: OU=Domain Control Validated; OU=PositiveSSL Multi-Domain; CN=ssl891738.cloudflaressl.com
*  start date: May  3 00:00:00 2018 GMT
*  expire date: May  1 23:59:59 2019 GMT
*  subjectAltName: host "registry.npmjs.org" matched cert's "*.npmjs.org"
*  issuer: C=GB; ST=Greater Manchester; L=Salford; O=COMODO CA Limited; CN=COMODO ECC Domain Validation Secure Server CA 2
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x560ffbf39ca0)
> GET /-/user/org.couchdb.user:vmx HTTP/2
> Host: registry.npmjs.org
> User-Agent: curl/7.58.0
> Accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 503 
< date: Tue, 29 May 2018 12:04:24 GMT
< content-type: text/plain;charset=UTF-8
< content-length: 28
< set-cookie: __cfduid=d89c3ab34333239b4537aba8f23e1404e1527595451; expires=Wed, 29-May-19 12:04:11 GMT; path=/; domain=.registry.npmjs.org; HttpOnly; Secure
< expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< server: cloudflare
< cf-ray: 4228d272fc207cd2-MUC
< 
* Connection #0 to host registry.npmjs.org left intact
No frontdoor hosts available
```

### supporting information:

 - `npm -v` prints:
  6.1.0
 - `node -v` prints:
  v8.11.1
 - `npm config get registry` prints:
  https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?:
  `Linux frea 4.16.0-1-amd64 #1 SMP Debian 4.16.5-1 (2018-04-29) x86_64 GNU/Linux`
 - Network issues:
   - Geographic location where npm was run:
    South Germany

### Logs

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/home/vmx/npm/bin/npm',
1 verbose cli   'owner',
1 verbose cli   'add',
1 verbose cli   'victorbjelkholm',
1 verbose cli   'ipld-bitcoin' ]
2 info using npm@6.1.0
3 info using node@v8.11.1
4 verbose owner add victorbjelkholm to ipld-bitcoin
5 silly mapToRegistry name -/user/org.couchdb.user:victorbjelkholm
6 silly mapToRegistry using default registry
7 silly mapToRegistry registry https://registry.npmjs.org/
8 silly mapToRegistry data { type: 'directory',
8 silly mapToRegistry   registry: undefined,
8 silly mapToRegistry   where: '/tmp',
8 silly mapToRegistry   raw: '-/user/org.couchdb.user:victorbjelkholm',
8 silly mapToRegistry   name: undefined,
8 silly mapToRegistry   escapedName: undefined,
8 silly mapToRegistry   scope: undefined,
8 silly mapToRegistry   rawSpec: '-/user/org.couchdb.user:victorbjelkholm',
8 silly mapToRegistry   saveSpec: 'file:-/user/org.couchdb.user:victorbjelkholm',
8 silly mapToRegistry   fetchSpec: '/tmp/-/user/org.couchdb.user:victorbjelkholm',
8 silly mapToRegistry   gitRange: undefined,
8 silly mapToRegistry   gitCommittish: undefined,
8 silly mapToRegistry   hosted: undefined }
9 silly mapToRegistry uri https://registry.npmjs.org/-/user/org.couchdb.user:victorbjelkholm
10 verbose request uri https://registry.npmjs.org/-/user/org.couchdb.user:victorbjelkholm
11 verbose request new user, so can't send auth
12 info attempt registry request try #1 at 1:49:43 PM
13 verbose request using bearer token for auth
14 verbose request id 3f4a6f094dd5122c
15 http request GET https://registry.npmjs.org/-/user/org.couchdb.user:victorbjelkholm
16 http 503 https://registry.npmjs.org/-/user/org.couchdb.user:victorbjelkholm
17 verbose bad json No frontdoor hosts available
18 error registry error parsing json
19 verbose headers { date: 'Tue, 29 May 2018 11:49:58 GMT',
19 verbose headers   'content-type': 'text/plain;charset=UTF-8',
19 verbose headers   'content-length': '28',
19 verbose headers   connection: 'keep-alive',
19 verbose headers   'set-cookie':
19 verbose headers    [ '__cfduid=d89e5d0cbb2e8486c4f58cba925829de21527594585; expires=Wed, 29-May-19 11:49:45 GMT; path=/; domain=.registry.npmjs.org; HttpOnly; Secure' ],
19 verbose headers   'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
19 verbose headers   server: 'cloudflare',
19 verbose headers   'cf-ray': '4228bd4f8fe57d0e-MUC' }
20 info retry will retry, error on last attempt: SyntaxError: Unexpected token N in JSON at position 0
20 info retry No frontdoor hosts available
21 info attempt registry request try #2 at 1:50:07 PM
22 verbose request using bearer token for auth
23 http request GET https://registry.npmjs.org/-/user/org.couchdb.user:victorbjelkholm
24 http 503 https://registry.npmjs.org/-/user/org.couchdb.user:victorbjelkholm
25 verbose bad json No frontdoor hosts available
26 error registry error parsing json
27 verbose headers { date: 'Tue, 29 May 2018 11:50:21 GMT',
27 verbose headers   'content-type': 'text/plain;charset=UTF-8',
27 verbose headers   'content-length': '28',
27 verbose headers   connection: 'keep-alive',
27 verbose headers   'set-cookie':
27 verbose headers    [ '__cfduid=d6211317dd686d34d3812e7a84ff6a9171527594608; expires=Wed, 29-May-19 11:50:08 GMT; path=/; domain=.registry.npmjs.org; HttpOnly; Secure' ],
27 verbose headers   'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
27 verbose headers   server: 'cloudflare',
27 verbose headers   'cf-ray': '4228bde00c377cb4-MUC' }
28 info retry will retry, error on last attempt: SyntaxError: Unexpected token N in JSON at position 0
28 info retry No frontdoor hosts available
29 info attempt registry request try #3 at 1:51:20 PM
30 verbose request using bearer token for auth
31 http request GET https://registry.npmjs.org/-/user/org.couchdb.user:victorbjelkholm
32 http 503 https://registry.npmjs.org/-/user/org.couchdb.user:victorbjelkholm
33 verbose bad json No frontdoor hosts available
34 error registry error parsing json
35 verbose headers { date: 'Tue, 29 May 2018 11:51:34 GMT',
35 verbose headers   'content-type': 'text/plain;charset=UTF-8',
35 verbose headers   'content-length': '28',
35 verbose headers   connection: 'keep-alive',
35 verbose headers   'set-cookie':
35 verbose headers    [ '__cfduid=d813d01191a65502fdf896c8c79bc32ec1527594681; expires=Wed, 29-May-19 11:51:21 GMT; path=/; domain=.registry.npmjs.org; HttpOnly; Secure' ],
35 verbose headers   'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
35 verbose headers   server: 'cloudflare',
35 verbose headers   'cf-ray': '4228bfa93bef7cd8-MUC' }
36 error owner mutate Error getting user data for victorbjelkholm
37 verbose stack SyntaxError: Unexpected token N in JSON at position 0
37 verbose stack No frontdoor hosts available
37 verbose stack     at JSON.parse (<anonymous>)
37 verbose stack     at RegClient.<anonymous> (/home/vmx/npm/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:243:23)
37 verbose stack     at Request._callback (/home/vmx/npm/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:216:14)
37 verbose stack     at Request.self.callback (/home/vmx/npm/lib/node_modules/npm/node_modules/request/request.js:185:22)
37 verbose stack     at emitTwo (events.js:126:13)
37 verbose stack     at Request.emit (events.js:214:7)
37 verbose stack     at Request.<anonymous> (/home/vmx/npm/lib/node_modules/npm/node_modules/request/request.js:1157:10)
37 verbose stack     at emitOne (events.js:116:13)
37 verbose stack     at Request.emit (events.js:211:7)
37 verbose stack     at IncomingMessage.<anonymous> (/home/vmx/npm/lib/node_modules/npm/node_modules/request/request.js:1079:12)
38 verbose cwd /tmp
39 verbose Linux 4.16.0-1-amd64
40 verbose argv "/usr/bin/node" "/home/vmx/npm/bin/npm" "owner" "add" "victorbjelkholm" "ipld-bitcoin"
41 verbose node v8.11.1
42 verbose npm  v6.1.0
43 error Unexpected token N in JSON at position 0
43 error No frontdoor hosts available
44 verbose exit [ 1, true ]
```

**Comment by jsteel** [comment]
This is similar to https://github.com/npm/npm/issues/20787

**Comment by brianneisler** [comment]
Seems that this issue has been resolved https://twitter.com/ceejbot/status/1001507441878515713

**Comment by vmx** [comment]
A few hours ago it worked. But now it doesn't work again. Although adding an owner seems to be successful (there isn't an error anymore), it doesn't list the owner when doing a `npm owner ls`.

**Comment by vmx** [comment]
Another update. The owner of the package `ipfs-block-service` tried to add me. I didn't show up in `owner ls`. But I discovered that I could add another person. After having that one added, I could neither remove it, or add another one.

There seems to be a serious issue when it comes to the package owner management. Should I open a new issue?

**Comment by vmx** [comment]
After adding me once more, it seems that it worked. Hence I'm closing this issue for now.

**Comment by vmx** [comment]
It happened again. This time with the `eth-hash-to-cid` package. It was tried to add me as owner but it didn't work.
