### ISSUE TITLE
fatal: 'submodule' appears to be a git command, but we were not able to execute it. Maybe git-submodule is broken?

### ISSUE THREAD

**Issue by Aqours** [npm/npm#20815]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
fatal: 'submodule' appears to be a git command, but we were not
able to execute it. Maybe git-submodule is broken?

#### How can the CLI team reproduce the problem?
```js
// package.json
{
  "name": "x",
  "version": "0.10.0",
  "scripts": {
    "prefetch": "git submodule update --init --recursive"
  }
}
```
run `npm run prefetch`. (It works fine in node v10.1.0)

### supporting information:

 - `npm -v` prints: 6.1.0
 - `node -v` prints: v10.3.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows 10 1803
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

### debug log
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'prefetch' ]
2 info using npm@6.1.0
3 info using node@v10.3.0
4 verbose run-script [ 'prefetch' ]
5 info lifecycle x@0.10.0~prefetch: x@0.10.0
6 verbose lifecycle x@0.10.0~prefetch: unsafe-perm in lifecycle true
7 verbose lifecycle x@0.10.0~prefetch: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\git\bili.corp\x-next\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\OpenVPN\bin;C:\Program Files\Git\cmd;C:\WINDOWS\System32\OpenSSH\焠䩟㟼<沀Ɍ;C:\Program Files\nodejs\;C:\Ruby25-x64\bin;C:\Users\Hellcom\AppData\Local\Programs\Python\Python36-32\Scripts\;C:\Users\Hellcom\AppData\Local\Programs\Python\Python36-32\;C:\Users\Hellcom\AppData\Local\Programs\Python\Python35-32\Scripts\;C:\Users\Hellcom\AppData\Local\Programs\Python\Python35-32\;C:\Ruby22-x64\bin;C:\Users\Hellcom\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Java\jdk-9.0.1\bin;C:\Program Files\Java\jdk-9.0.1\jre\bin;C:\Program Files\Microsoft VS Code\bin;C:\Users\Hellcom\AppData\Local\Microsoft\WindowsApps;C:\Users\Hellcom\AppData\Roaming\npm
8 verbose lifecycle x@0.10.0~prefetch: CWD: D:\git\bili.corp\x-next
9 silly lifecycle x@0.10.0~prefetch: Args: [ '/d /s /c', 'git submodule update --init --recursive' ]
10 silly lifecycle x@0.10.0~prefetch: Returned: code: 128  signal: null
11 info lifecycle x@0.10.0~prefetch: Failed to exec prefetch script
12 verbose stack Error: x@0.10.0 prefetch: `git submodule update --init --recursive`
12 verbose stack Exit status 128
12 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:304:16)
12 verbose stack     at EventEmitter.emit (events.js:182:13)
12 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
12 verbose stack     at ChildProcess.emit (events.js:182:13)
12 verbose stack     at maybeClose (internal/child_process.js:961:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
13 verbose pkgid x@0.10.0
14 verbose cwd D:\git\bili.corp\x-next
15 verbose Windows_NT 10.0.17134
16 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "prefetch"
17 verbose node v10.3.0
18 verbose npm  v6.1.0
19 error code ELIFECYCLE
20 error errno 128
21 error x@0.10.0 prefetch: `git submodule update --init --recursive`
21 error Exit status 128
22 error Failed at the x@0.10.0 prefetch script.
22 error This is probably not a problem with npm. There is likely additional logging output above.
23 verbose exit [ 128, true ]
```

**Comment by legodude17** [comment]
Does `git submodule update --init --recursive` work?

**Comment by Aqours** [comment]
Of course, it works

**Comment by JimiC** [comment]
Same issue with every node version and `npm 6.1.0`.

**Comment by JimiC** [comment]
I had some time to investigate this further. Turns out this is a `Windows` issue with `git submodule` as I tested `npm 6.1.0` on a `Linux Ubuntu Mate 16.04` and worked flawlessly. Strange though that `npm 5.10.0` works on `Windows` with the same `git` installation.

**Comment by lbottoni** [comment]
i have the same problem, if i use the command "git submodule update --init --recursive" nothing change.

npm: 6.1.0
window:10
git: version 2.17.1.windows.2


> 3273 verbose stack Error: Command failed: C:\Program Files\Git\cmd\git.EXE submodule update -q --init --recursive
> 3273 verbose stack fatal: 'submodule' appears to be a git command, but we were not
> 3273 verbose stack able to execute it. Maybe git-submodule is broken?
> 3273 verbose stack
> 3273 verbose stack     at ChildProcess.exithandler (child_process.js:273:12)
> 3273 verbose stack     at ChildProcess.emit (events.js:180:13)
> 3273 verbose stack     at maybeClose (internal/child_process.js:936:16)
3273 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
> 3274 verbose cwd C:\xampp\htdocs\next-wui\packages\ghibli-core
> 3275 verbose Windows_NT 10.0.17134
> 3276 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\luca.bottoni\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "--no-package-lock"
> 3277 verbose node v9.11.1
> 3278 verbose npm  v6.1.0
> 3279 error code 128
> 3280 error Command failed: C:\Program Files\Git\cmd\git.EXE submodule update -q --init --recursive
> 3280 error fatal: 'submodule' appears to be a git command, but we were not
> 3280 error able to execute it. Maybe git-submodule is broken?
> 3281 verbose exit [ 1, true ]

**Comment by lbottoni** [comment]
work with node 5.1

npm install -g npm@5.1

thanks

**Comment by JimiC** [comment]
Strangely enough `v6.0.1` works too.

**Comment by JimiC** [comment]
Finally, I found the blame. The issue is caused by https://github.com/npm/npm-lifecycle/commit/e4ecc5482f765ed6d103196b1cd3973eebc607f0

/cc @zkat @laggingreflex
