### ISSUE TITLE
"npm install xyz" produces "asyncWrite is not a function"

### ISSUE THREAD

**Issue by lukepighetti** [npm/npm#20822]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [x] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

```
Lukes-iMac:test lukepighetti$ npm install firebase
npm ERR! asyncWrite is not a function
npm ERR! pna.nextTick is not a function

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lukepighetti/.npm/_logs/2018-05-30T11_19_01_969Z-debug.log


Lukes-iMac:test lukepighetti$ npm install axios
npm ERR! asyncWrite is not a function
npm ERR! pna.nextTick is not a function

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lukepighetti/.npm/_logs/2018-05-30T11_19_15_278Z-debug.log


Lukes-iMac:test lukepighetti$ npm install express
npm ERR! asyncWrite is not a function
npm ERR! pna.nextTick is not a function

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lukepighetti/.npm/_logs/2018-05-30T11_19_37_037Z-debug.log
```
#### How can the CLI team reproduce the problem?

install Node on macOS via package, npm install -g n, n stable, then try to install anything

**Comment by lukepighetti** [comment]
```
Lukes-iMac:test lukepighetti$ cat /Users/lukepighetti/.npm/_logs/2018-05-30T11_19_37_037Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'express' ]
2 info using npm@6.1.0
3 info using node@v10.2.1
4 verbose npm-session 02ab45f998b12151
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 verbose stack TypeError: asyncWrite is not a function
7 verbose stack     at onwrite (/usr/local/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_writable.js:480:7)
7 verbose stack     at WritableState.onwrite (/usr/local/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_writable.js:180:5)
7 verbose stack     at WriteStream.to [as _worker] (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/cache.js:154:13)
7 verbose stack     at WriteStream._write (/usr/local/lib/node_modules/npm/node_modules/mississippi/node_modules/flush-write-stream/index.js:35:13)
7 verbose stack     at doWrite (/usr/local/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_writable.js:428:64)
7 verbose stack     at writeOrBuffer (/usr/local/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_writable.js:417:5)
7 verbose stack     at WriteStream.Writable.write (/usr/local/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_writable.js:334:11)
7 verbose stack     at WriteStream.to [as _worker] (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/cache.js:171:25)
7 verbose stack     at WriteStream._write (/usr/local/lib/node_modules/npm/node_modules/mississippi/node_modules/flush-write-stream/index.js:35:13)
7 verbose stack     at doWrite (/usr/local/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_writable.js:428:64)
7 verbose stack     at writeOrBuffer (/usr/local/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_writable.js:417:5)
7 verbose stack     at WriteStream.Writable.write (/usr/local/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_writable.js:334:11)
7 verbose stack     at WriteStream.to [as _worker] (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/cache.js:182:19)
7 verbose stack     at WriteStream._write (/usr/local/lib/node_modules/npm/node_modules/mississippi/node_modules/flush-write-stream/index.js:35:13)
7 verbose stack     at doWrite (/usr/local/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_writable.js:428:64)
7 verbose stack     at writeOrBuffer (/usr/local/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_writable.js:417:5)
8 verbose cwd /Users/lukepighetti/code/test
9 verbose Darwin 17.5.0
10 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "express"
11 verbose node v10.2.1
12 verbose npm  v6.1.0
13 error asyncWrite is not a function
14 verbose exit [ 1, true ]
```

**Comment by lukepighetti** [comment]
This is on a brand new iMac with a fresh install of Node and `n latest`

**Comment by vv314** [comment]
I encountered the same error after updating node with `n latest` on mac

**Comment by changjunhao** [comment]
I encountered the same error after updating node with n latest on CentOS

**Comment by zkat** [comment]
could you please re-file the issue over here: https://npm.community/c/bugs and make sure you repro steps still work? This is very strange.
