### ISSUE TITLE
npm -v is not working

### ISSUE THREAD

**Issue by flik** [npm/npm#20838]
#### I'm opening this issue because:

  - [x ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
 npm -v
internal/modules/cjs/loader.js:596
    throw err;
    ^

Error: Cannot find module 'graceful-fs'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/share/npm/lib/utils/ini.js:32:10)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)

### supporting information:

 - `npm -v` prints:
 npm -v
internal/modules/cjs/loader.js:596
    throw err;
    ^

Error: Cannot find module 'graceful-fs'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/share/npm/lib/utils/ini.js:32:10)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)

 - `node -v` prints:
 node -v
v0.8.19

 - `npm config get registry` prints:
 -   Linux?: ubuntu 16
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by iplanetcn** [comment]
same error

**Comment by kenany** [comment]
> node -v
> v0.8.19

That version of Node.js has not been supported for a few years now.

**Comment by iplanetcn** [comment]
I solved this error by deleting all NPM global packages include NPM its self. Reinstall the NodeJS. 
(OS Version: macOS 10.13.4)

1. delete command:
`npm ls -gp --depth=0 | awk -F/ '/node_modules/ && !/\/npm$/ {print $NF}' | xargs npm -g rm`
2. reinstall with brew:
`brew reinstall node`

**Comment by DinoChiesa** [comment]
```
npm ls -gp --depth=0 
```
...gives me 
```
internal/modules/cjs/loader.js:596
    throw err;
    ^
```
In other words, it's not possible for me to fix it by using npm to list its global modules. 
I had to do this: 
```
sudo rm -fr /usr/local/lib/node_modules/npm
```
MacOS 10.13.5

**Comment by remisb** [comment]
`sudo rm -fr /usr/local/lib/node_modules/npm`

Worked for me too. That was only solution which worked. 

Thanks Dino
