### ISSUE TITLE
my bp's project was created using 10.11.1 how to change it to use bp 10.11.2?

### ISSUE THREAD

**Issue by Primtek** [npm/npm#20839]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
my bp's project was created using 10.11.1 how to change it to use bp 10.11.2?

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by Primtek** [comment]
after I ran npm -g install botpress@beta 
I run npm install..
but when I start the project .. I found this problem:

[root@ai bp01]# bp start
14:20:52 - info: Starting botpress version 10.11.2
14:20:57 - info: [Ghost Content Manager] (transparent) Initialized
14:20:57 - info: [Skills] Initiated
14:20:57 - warn: DEPRECATION NOTICE â bp.umm is deprecated and will be removed in `botpress@3.0` â Please see bp.renderers instead.
14:20:57 - info: Loaded @botpress/audience, version 10.11.2
14:20:58 - info: Loaded @botpress/channel-web, version 10.11.2
14:20:58 - info: Loaded @botpress/hitl, version 10.11.2
14:20:58 - warn: Error during module initialization:  TypeError: Cannot read property 'type' of undefined
    at /home/primtek/botpress/bp01/node_modules/botpress/lib/webpack:/src/config-manager/index.js:124:15
    at /home/primtek/botpress/bp01/node_modules/lodash/lodash.js:13400:38
    at /home/primtek/botpress/bp01/node_modules/lodash/lodash.js:4925:15
    at baseForOwn (/home/primtek/botpress/bp01/node_modules/lodash/lodash.js:3010:24)
    at Function.mapValues (/home/primtek/botpress/bp01/node_modules/lodash/lodash.js:13399:7)
    at e.value (/home/primtek/botpress/bp01/node_modules/botpress/lib/webpack:/src/config-manager/index.js:123:16)
    at memoized (/home/primtek/botpress/bp01/node_modules/lodash/lodash.js:10551:27)
    at e.<anonymous> (/home/primtek/botpress/bp01/node_modules/botpress/lib/webpack:/src/config-manager/index.js:159:12)
    at tryCatch (/usr/lib/node_modules/botpress/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/usr/lib/node_modules/botpress/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/usr/lib/node_modules/botpress/node_modules/regenerator-runtime/runtime.js:117:21)
    at n (/home/primtek/botpress/bp01/node_modules/botpress/lib/webpack:/src/config-manager/index.js:16:1)
    at /home/primtek/botpress/bp01/node_modules/botpress/lib/webpack:/src/config-manager/index.js:16:1
    at new Promise (<anonymous>)
    at e.<anonymous> (/home/primtek/botpress/bp01/node_modules/botpress/lib/webpack:/src/config-manager/index.js:16:1)
    at e.n.value (/home/primtek/botpress/bp01/node_modules/botpress/lib/webpack:/src/config-manager/index.js:159:25)
    at e.<anonymous> (/home/primtek/botpress/bp01/node_modules/botpress/lib/webpack:/src/config-manager/module.js:37:39)
    at tryCatch (/usr/lib/node_modules/botpress/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/usr/lib/node_modules/botpress/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/usr/lib/node_modules/botpress/node_modules/regenerator-runtime/runtime.js:117:21)
    at n (/home/primtek/botpress/bp01/node_modules/botpress/lib/webpack:/src/config-manager/module.js:3:1)
    at /home/primtek/botpress/bp01/node_modules/botpress/lib/webpack:/src/config-manager/module.js:3:1
14:20:58 - info: Loaded @botpress/nlu, version 10.11.2
14:20:58 - info: Loaded @botpress/skill-choice, version 10.11.2
14:20:58 - info: Loaded 5 modules
14:20:58 - info: [Skills] Loaded 1 skills
14:20:58 - info: Read 33 item(s) from builtin_text.json
14:20:58 - info: Bot launched. Visit: http://localhost:3000
14:20:58 - info: Read 1 item(s) from builtin_single-choice.json
14:20:58 - info: ------------
14:20:58 - info: Webchat available at http://localhost:3000/s/chat
14:20:58 - info: ------------

**Comment by kenany** [comment]
I think this belongs in <https://github.com/botpress/botpress/issues>.
