### ISSUE TITLE
Cannot install package. SSL routines:ssl3_get_record:wrong version number

### ISSUE THREAD

**Issue by Freeongoo** [npm/npm#20847]
#### I'm opening this issue because:

  - [x] npm is crashing.

#### What's going wrong?

Try install jquery from package
`npm install jquery`

Output:
```
npm ERR! code EPROTO
npm ERR! errno EPROTO
npm ERR! request to http://registry.npmjs.org/jquery failed, reason: write EPROTO 140069586700096:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:252:
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dorofeev/.npm/_logs/2018-05-31T11_30_06_867Z-debug.log
```

Log file:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'install', 'jquery' ]
2 info using npm@6.1.0
3 info using node@v10.3.0
4 verbose npm-session dcac86e44747467c
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData error for jquery@^3.2.1 request to http://registry.npmjs.org/jquery failed, reason: write EPROTO 140069586700096:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:252:
8 timing stage:rollbackFailedOptional Completed in 0ms
9 timing stage:runTopLevelLifecycles Completed in 239ms
10 verbose type system
11 verbose stack FetchError: request to http://registry.npmjs.org/jquery failed, reason: write EPROTO 140069586700096:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:252:
11 verbose stack
11 verbose stack     at ClientRequest.req.on.err (/usr/lib/node_modules/npm/node_modules/node-fetch-npm/src/index.js:68:14)
11 verbose stack     at ClientRequest.emit (events.js:182:13)
11 verbose stack     at TLSSocket.socketErrorListener (_http_client.js:382:9)
11 verbose stack     at TLSSocket.emit (events.js:182:13)
11 verbose stack     at onwriteError (_stream_writable.js:431:12)
11 verbose stack     at onwrite (_stream_writable.js:456:5)
11 verbose stack     at _destroy (internal/streams/destroy.js:40:7)
11 verbose stack     at TLSSocket.Socket._destroy (net.js:603:3)
11 verbose stack     at TLSSocket.destroy (internal/streams/destroy.js:32:8)
11 verbose stack     at WriteWrap.afterWrite [as oncomplete] (net.js:835:10)
12 verbose cwd /home/dorofeev/Загрузки/deb/npm
13 verbose Linux 4.4.0-59-generic
14 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "jquery"
15 verbose node v10.3.0
16 verbose npm  v6.1.0
17 error code EPROTO
18 error errno EPROTO
19 error request to http://registry.npmjs.org/jquery failed, reason: write EPROTO 140069586700096:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:252:
20 verbose exit [ 1, true ]

```

### supporting information:

 - `npm -v` prints: 6.1.0
 - `node -v` prints: v10.3.0
 - `npm config get registry` prints: http://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: ubuntu 16.04
 - Network issues:
   not use proxy
- openssl: OpenSSL 1.0.2l  25 May 2017

**Comment by legodude17** [comment]
Does this occur if you set your registry to https://registry.npmjs.org?

**Comment by Freeongoo** [comment]
https://registry.npmjs.org not helped

**Comment by zkat** [comment]
See https://npm.community/t/common-proxy-and-networking-problems/151/2

**Comment by zkat** [comment]
Also, please open a new support issue on npm.community if the troubleshooting guide does not help.
