### ISSUE TITLE
write after end issue still happens for me

### ISSUE THREAD

**Issue by timlesallen** [npm/npm#20860]
I believe that https://github.com/npm/npm/issues/19989 has not been correctly resolved with `6.1.0` for `npm ci`.  This seems to be because the version of `libcipm` that shipped with it still depends on `pacote@7.x`?

```bash
root@904bf43f3e8a:/usr/local/lib/node_modules/npm# npm ls pacote
npm@6.1.0 /usr/local/lib/node_modules/npm
+-- libcipm@1.6.2
| `-- pacote@7.6.1
`-- pacote@8.1.6
```
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [x] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
When I run `npm ci` on my project it's crashing with:
```
events.js:183......] \ extractTree: sill extractTree mime-db@1.33.0 -> /code/node_modules/mime-db
      throw er; // Unhandled 'error' event
      ^
Error: write after end
    at writeAfterEnd (_stream_writable.js:236:12)
    at PassThrough.Writable.write (_stream_writable.js:287:5)
    at PassThrough.Writable.end (_stream_writable.js:563:10)
    at ReadEntry.entry.on (/usr/local/lib/node_modules/npm/node_modules/libcipm/node_modules/pacote/lib/extract-stream.js:19:41)
    at emitOne (events.js:121:20)
    at ReadEntry.emit (events.js:211:7)
    at ReadEntry.emit (/usr/local/lib/node_modules/npm/node_modules/minipass/index.js:309:30)
    at ReadEntry.[maybeEmitEnd] (/usr/local/lib/node_modules/npm/node_modules/minipass/index.js:257:12)
    at ReadEntry.end (/usr/local/lib/node_modules/npm/node_modules/minipass/index.js:167:27)
    at Unpack.[consumeBody] (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:210:13)
    at Unpack.[consumeChunkSub] (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:391:40)
    at Unpack.[consumeChunk] (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:362:30)
    at Unzip.(anonymous function).on.chunk (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:291:59)
    at emitOne (events.js:116:13)
    at Unzip.emit (events.js:211:7)
    at Unzip.emit (/usr/local/lib/node_modules/npm/node_modules/minipass/index.js:309:30)
``` 
#### How can the CLI team reproduce the problem?

https://gist.github.com/timlesallen/8389d7f807c11a9717a98f26acf64ab4

### supporting information:

 - `npm -v` prints: `6.1.0`
 - `node -v` prints: `v8.11.2`
 - `npm config get registry` prints: `https://registry.npmjs.org/`
 - Windows, OS X/macOS, or Linux?: Linux
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ X ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by b-johnse** [comment]
Same, in fact it happens more frequently for my with 6.1.0 than it was with 6.0.1.

Same environment as described except using a proxy

**Comment by jimmycann** [comment]
Looks like this would be fixed by upgrading `libcipm` (https://github.com/zkat/cipm) to `^2.0.0` as it bumps `pacote` to > 8. 

`libcipm` 1.6.3 also bumps pacote to > 8, but has been deprecated with warning 
```
npm WARN deprecated libcipm@1.6.3: This version mistakenly dropped node@4 compatibility in a semver-patch release. Please stay on 1.6.2 or update to 2 or latest
```

I forked and upgraded to 2.0.0 but got some local failures. Unsure if they're just flaky tests, or if there's work that needs to be carried out to make it compatible.

**Comment by ds82** [comment]
thanks for the hint @yjimk 
This works for me until this issue is fixed:

```
rm -rf $(npm root -g)/npm/node_modules/libcipm/node_modules/pacote
```

**Comment by moisadoru** [comment]
I also had success by monkey patching the local npm install, inspired by @ds82 and @yjimk:
```
cd $(npm root -g)/npm
npm i libcipm@2 || rm -rf node_modules/libcipm/node_modules/pacote || true
cd -
```

**Comment by timlesallen** [comment]
@zkat Not sure if you've seen this one? :)
