### ISSUE TITLE
error Unexpected end of JSON input while parsing near '..."karma-chai":"^0.1.0"'

### ISSUE THREAD

**Issue by easywudi** [npm/npm#20870]
#### I'm opening this issue because:

first of all . i am not good at english.. forgive me 
i am use homebrew install nodejs on mac , 
i not know this problem ,maybe JSON error .
i wanna know this error from mirrors or itself(npm).  can everybody give me some advance,thanks

  - [ ] npm is crashing.
  - [√ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

<pre>
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/10.3.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'cnpm',
1 verbose cli   '--registry=https://registry.npm.taobao.org' ]
2 info using npm@6.1.0
3 info using node@v10.3.0
4 verbose npm-session e411a43d841d1619
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 304 https://registry.npm.taobao.org/cnpm 229ms (from cache)
8 silly pacote tag manifest for cnpm@latest fetched in 253ms
9 timing stage:loadCurrentTree Completed in 418ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 2ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule cnpm@6.0.0 checking installable status
17 http fetch GET 304 https://registry.npm.taobao.org/auto-correct 70ms (from cache)
18 silly pacote range manifest for auto-correct@^1.0.0 fetched in 73ms
19 silly resolveWithNewModule auto-correct@1.0.0 checking installable status
20 http fetch GET 304 https://registry.npm.taobao.org/npm-request 176ms (from cache)
21 http fetch GET 304 https://registry.npm.taobao.org/giturl 182ms (from cache)
22 silly pacote range manifest for npm-request@^1.0.0 fetched in 181ms
23 silly resolveWithNewModule npm-request@1.0.0 checking installable status
24 silly pacote range manifest for giturl@^1.0.0 fetched in 187ms
25 silly resolveWithNewModule giturl@1.0.0 checking installable status
26 http fetch GET 304 https://registry.npm.taobao.org/colors 195ms (from cache)
27 http fetch GET 304 https://registry.npm.taobao.org/bagpipe 197ms (from cache)
28 http fetch GET 304 https://registry.npm.taobao.org/cross-spawn 197ms (from cache)
29 http fetch GET 304 https://registry.npm.taobao.org/ini 195ms (from cache)
30 silly pacote range manifest for colors@^1.1.2 fetched in 201ms
31 silly resolveWithNewModule colors@1.3.0 checking installable status
32 silly pacote range manifest for bagpipe@^0.3.5 fetched in 203ms
33 silly resolveWithNewModule bagpipe@0.3.5 checking installable status
34 silly pacote range manifest for cross-spawn@~0.2.8 fetched in 202ms
35 silly resolveWithNewModule cross-spawn@0.2.9 checking installable status
36 http fetch GET 304 https://registry.npm.taobao.org/debug 202ms (from cache)
37 silly pacote range manifest for ini@^1.3.4 fetched in 200ms
38 silly resolveWithNewModule ini@1.3.5 checking installable status
39 silly fetchPackageMetaData error for debug@^2.2.0 Unexpected end of JSON input while parsing near '..."karma-chai":"^0.1.0"'
40 http fetch GET 304 https://registry.npm.taobao.org/commander 206ms (from cache)
41 silly pacote range manifest for commander@~2.10.0 fetched in 209ms
42 silly resolveWithNewModule commander@2.10.0 checking installable status
43 http fetch GET 304 https://registry.npm.taobao.org/npminstall 138ms (from cache)
44 silly pacote range manifest for npminstall@^3.0.0 fetched in 142ms
45 silly resolveWithNewModule npminstall@3.6.2 checking installable status
46 http fetch GET 304 https://registry.npm.taobao.org/npm 237ms (from cache)
47 silly pacote range manifest for npm@^6.1.0 fetched in 255ms
48 silly resolveWithNewModule npm@6.1.0 checking installable status
49 silly tarball trying http://registry.npm.taobao.org/npm/download/npm-6.1.0.tgz by hash: sha1-1oXN/BqBL7Bj8DGvCb7XpaaO7fE=
50 http fetch GET 304 https://registry.npm.taobao.org/urllib 99ms (from cache)
51 silly pacote range manifest for urllib@^2.17.0 fetched in 104ms
52 silly resolveWithNewModule urllib@2.28.1 checking installable status
53 http fetch GET 304 https://registry.npm.taobao.org/open 220ms (from cache)
54 silly pacote range manifest for open@^0.0.5 fetched in 221ms
55 silly resolveWithNewModule open@0.0.5 checking installable status
56 silly extract http://registry.npm.taobao.org/npm/download/npm-6.1.0.tgz extracted to /var/folders/bw/ps8ccgw51131p689dtpy_vp00000gn/T/npm-2031-80145fbe/unpack-2164c53b (2667ms)
57 silly addBundled read tarball
58 silly cleanup remove extracted module
59 timing stage:rollbackFailedOptional Completed in 0ms
60 timing stage:runTopLevelLifecycles Completed in 5887ms
61 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '..."karma-chai":"^0.1.0"'
61 verbose stack     at JSON.parse (<anonymous>)
61 verbose stack     at parseJson (/usr/local/lib/node_modules/npm/node_modules/json-parse-better-errors/index.js:7:17)
61 verbose stack     at consumeBody.call.then.buffer (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/src/body.js:96:50)
61 verbose stack     at process._tickCallback (internal/process/next_tick.js:68:7)
62 verbose cwd /Users/raymond/vueProjects
63 verbose Darwin 17.5.0
64 verbose argv "/usr/local/Cellar/node/10.3.0/bin/node" "/usr/local/bin/npm" "install" "-g" "cnpm" "--registry=https://registry.npm.taobao.org"
65 verbose node v10.3.0
66 verbose npm  v6.1.0
67 error Unexpected end of JSON input while parsing near '..."karma-chai":"^0.1.0"'
68 verbose exit [ 1, true ]
</pre>

### supporting information:

 - `npm -v` prints: <b> 6.1.0 </b>
 - `node -v` prints: <b> v10.3.0 </b>
 - `npm config get registry` prints: <b> https://registry.npmjs.org/ </b>
 - Windows, OS X/macOS, or Linux?:<b>  OS X/macOS </b>
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [√ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by easywudi** [comment]
i try other code then solve my question. see code below
<b> npm install cnpm -g </b>
