### ISSUE TITLE
cb() never called!

### ISSUE THREAD

**Issue by daviedave12** [npm/npm#20885]
#### I'm opening this issue because:

  - [X] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
I get a `cb() never called!` Error when I use "npm i" in my project folder.
#### How can the CLI team reproduce the problem?
Use a existing project, use "npm i" or "npm install":

https://gist.github.com/daviedave12/d032cdc1818b6aa4f33e46d2aed914b3
### supporting information:

 - `npm -v` prints: 6.1.0
 - `node -v` prints: v8.11.2
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: OpenSuse Tumbleweed
 - Network issues:
   - Geographic location where npm was run: Germany
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by boutell** [comment]
I don't get this all the time on every project. I get it on some projects. I haven't found a simple reproducible case based on open source / code I can share yet. I've been downgrading and upgrading again to get npm audit support and downgrading again...

I was downgrading to 5.7.0, unfortunately, which meant I was the last person on Earth to get hit by the permissions-smashing bug. 😢

**Comment by Simwenya** [comment]
npm cache clean --force this worked for me

**Comment by daviedave12** [comment]
This did not work for me. But I tried a few other things, now I am getting this error:
```
Unhandled rejection Error: invalid config key requested: singleular/core@6.0.3
    at pudGet (/usr/local/lib/node_modules/npm/node_modules/figgy-pudding/index.js:31:11)
    at FiggyPudding.get (/usr/local/lib/node_modules/npm/node_modules/figgy-pudding/index.js:13:12)
    at Object.get (/usr/local/lib/node_modules/npm/node_modules/figgy-pudding/index.js:71:16)
    at _parse (/usr/local/lib/node_modules/npm/node_modules/ssri/index.js:138:12)
    at parse (/usr/local/lib/node_modules/npm/node_modules/ssri/index.js:125:12)
    at Object.checkData (/usr/local/lib/node_modules/npm/node_modules/ssri/index.js:216:9)
    at write (/usr/local/lib/node_modules/npm/node_modules/cacache/lib/content/write.js:34:31)
    at putData (/usr/local/lib/node_modules/npm/node_modules/cacache/put.js:25:10)
    at Object.x.put (/usr/local/lib/node_modules/npm/node_modules/cacache/locales/en.js:28:37)
    at readFileAsync.then.data (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/file.js:38:28)
    at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:638:18)

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-06-06T07_33_44_084Z-debug.log

```

**Comment by degardinn** [comment]
The relevant part of your error is **Unhandled rejection Error: invalid config key requested: singleular/core@6.0.3**
This is related to [https://github.com/npm/npm/issues/20424](url)
