### ISSUE TITLE
npm ERR! Error: CERT_UNTRUSTED

### ISSUE THREAD

**Issue by zhanyong001** [npm/npm#20898]
zhanyong@zhanyong-ThinkPad-E450:~$ npm install -g yarn react-native-cli

found error

npm ERR! Error: CERT_UNTRUSTED
npm ERR!     at SecurePair.<anonymous> (tls.js:1370:32)
npm ERR!     at SecurePair.EventEmitter.emit (events.js:92:17)
npm ERR!     at SecurePair.maybeInitFinished (tls.js:982:10)
npm ERR!     at CleartextStream.read [as _read] (tls.js:469:13)
npm ERR!     at CleartextStream.Readable.read (_stream_readable.js:320:10)
npm ERR!     at EncryptedStream.write [as _write] (tls.js:366:25)
npm ERR!     at doWrite (_stream_writable.js:223:10)
npm ERR!     at writeOrBuffer (_stream_writable.js:213:5)
npm ERR!     at EncryptedStream.Writable.write (_stream_writable.js:180:11)
npm ERR!     at write (_stream_readable.js:583:24)
npm ERR!     at flow (_stream_readable.js:592:7)
npm ERR!     at Socket.pipeOnReadable (_stream_readable.js:624:5)

**Comment by legodude17** [comment]
What is the result of `npm --versions`?

**Comment by AaronSezar** [comment]
I Have This Problem Too.

**Comment by legodude17** [comment]
@SezarMoein What is the result of npm --versions?

**Comment by tiepviet** [comment]
```
sudo npm install -g coffeescript
npm http GET https://registry.npmjs.org/coffeescript
npm http GET https://registry.npmjs.org/coffeescript
npm http GET https://registry.npmjs.org/coffeescript
npm ERR! Error: UNABLE_TO_GET_ISSUER_CERT_LOCALLY
npm ERR!     at SecurePair.<anonymous> (tls.js:1430:32)
npm ERR!     at SecurePair.emit (events.js:92:17)
npm ERR!     at SecurePair.maybeInitFinished (tls.js:1029:10)
npm ERR!     at CleartextStream.read [as _read] (tls.js:521:13)
npm ERR!     at CleartextStream.Readable.read (_stream_readable.js:341:10)
npm ERR!     at EncryptedStream.write [as _write] (tls.js:418:25)
npm ERR!     at doWrite (_stream_writable.js:226:10)
npm ERR!     at writeOrBuffer (_stream_writable.js:216:5)
npm ERR!     at EncryptedStream.Writable.write (_stream_writable.js:183:11)
npm ERR!     at write (_stream_readable.js:602:24)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 4.4.5-15.26.amzn1.x86_64
npm ERR! command "node" "/usr/bin/npm" "install" "-g" "coffeescript"
npm ERR! cwd /home/ec2-user
npm ERR! node -v v0.10.48
npm ERR! npm -v 1.3.6
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/ec2-user/npm-debug.log
npm ERR! not ok code 0
```
npm version: 1.3.6
OS: Cent OS

**Comment by legodude17** [comment]
@tiepviet Your versions of node and npm are years old and no longer supported. Please update.

**Comment by jcrben** [comment]
@KenanY close this like you did with https://github.com/npm/npm/issues/20999?

**Comment by kenany** [comment]
@jcrben I'm waiting for @zhanyong001's reply before closing, but this issue is indeed almost certainly caused by an extremely old `npm` installation. I'll give this a few more days and then close as abandoned if need be.

**Comment by jcrben** [comment]
@KenanY there's a lot of discussion on how to address it at https://github.com/npm/npm/issues/20191

perhaps TROUBLESHOOTING.md could be updated with that advice?
