### ISSUE TITLE
Issue with NPM registry for oclif package

### ISSUE THREAD

**Issue by sujaygarlanka** [npm/npm#20907]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
Incorrect JSON file being returned from the npm registry.

#### How can the CLI team reproduce the problem?

run _npx oclif multi mynewcli_

### Debug log
  
0 info it worked if it ends with ok
1 verbose cli [ '/Users/sgarlanka/.nvm/versions/node/v8.11.2/bin/node',
1 verbose cli   '/Users/sgarlanka/.nvm/versions/node/v8.11.2/lib/node_modules/npx/node_modules/npm/bin/npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'oclif@latest',
1 verbose cli   '--global',
1 verbose cli   '--prefix',
1 verbose cli   '/Users/sgarlanka/.npm/_npx/1819',
1 verbose cli   '--loglevel',
1 verbose cli   'error',
1 verbose cli   '--json' ]
2 info using npm@5.1.0
3 info using node@v8.11.2
4 verbose npm-session fb16a751bdeb323a
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 304 https://registry.npmjs.org/oclif 627ms (from cache)
8 silly pacote tag manifest for oclif@latest fetched in 648ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 silly install loadShrinkwrap
12 silly install loadAllDepsIntoIdealTree
13 silly resolveWithNewModule oclif@1.8.0 checking installable status
14 http fetch GET 200 https://registry.npmjs.org/@oclif%2fcommand 28ms (from cache)
15 http fetch GET 200 https://registry.npmjs.org/@oclif%2fconfig 29ms (from cache)
16 http fetch GET 200 https://registry.npmjs.org/@oclif%2ferrors 29ms (from cache)
17 http fetch GET 200 https://registry.npmjs.org/@oclif%2fplugin-help 29ms (from cache)
18 http fetch GET 200 https://registry.npmjs.org/@oclif%2fplugin-not-found 31ms (from cache)
19 http fetch GET 200 https://registry.npmjs.org/@oclif%2fplugin-warn-if-update-available 31ms (from cache)
20 silly pacote range manifest for @oclif/command@^1.4.32 fetched in 36ms
21 silly resolveWithNewModule @oclif/command@1.4.32 checking installable status
22 silly pacote range manifest for @oclif/errors@^1.1.2 fetched in 35ms
23 silly resolveWithNewModule @oclif/errors@1.1.2 checking installable status
24 silly pacote range manifest for @oclif/config@^1.6.27 fetched in 37ms
25 silly resolveWithNewModule @oclif/config@1.6.27 checking installable status
26 silly pacote range manifest for @oclif/plugin-help@^2.0.4 fetched in 36ms
27 silly resolveWithNewModule @oclif/plugin-help@2.0.4 checking installable status
28 silly pacote range manifest for @oclif/plugin-not-found@^1.0.9 fetched in 37ms
29 silly resolveWithNewModule @oclif/plugin-not-found@1.0.9 checking installable status
30 silly pacote range manifest for @oclif/plugin-warn-if-update-available@^1.3.9 fetched in 38ms
31 silly resolveWithNewModule @oclif/plugin-warn-if-update-available@1.3.9 checking installable status
32 http fetch GET 304 https://registry.npmjs.org/debug 67ms (from cache)
33 silly fetchPackageMetaData error for debug@^3.1.0 Unexpected end of input at 1:6202
33 silly fetchPackageMetaData ectories":{},"dist":{"shasum":"33ab915659d8c2cc8a41443d94d6ebd37697ed
33 silly fetchPackageMetaData                                                                      ^
34 http fetch GET 304 https://registry.npmjs.org/lodash 134ms (from cache)
35 silly pacote range manifest for lodash@^4.17.10 fetched in 135ms
36 silly resolveWithNewModule lodash@4.17.10 checking installable status
37 http fetch GET 304 https://registry.npmjs.org/tslib 130ms (from cache)
38 silly pacote range manifest for tslib@^1.9.2 fetched in 131ms
39 silly resolveWithNewModule tslib@1.9.2 checking installable status
40 http fetch GET 304 https://registry.npmjs.org/yosay 140ms (from cache)
41 http fetch GET 304 https://registry.npmjs.org/yeoman-environment 142ms (from cache)
42 silly pacote range manifest for yosay@^2.0.2 fetched in 142ms
43 silly resolveWithNewModule yosay@2.0.2 checking installable status
44 silly pacote range manifest for yeoman-environment@^2.2.0 fetched in 145ms
45 silly resolveWithNewModule yeoman-environment@2.2.0 checking installable status
46 http fetch GET 304 https://registry.npmjs.org/yeoman-generator 161ms (from cache)
47 silly pacote range manifest for yeoman-generator@^2.0.5 fetched in 185ms
48 silly resolveWithNewModule yeoman-generator@2.0.5 checking installable status
49 http fetch GET 304 https://registry.npmjs.org/nps-utils 276ms (from cache)
50 silly pacote range manifest for nps-utils@^1.5.0 fetched in 278ms
51 silly resolveWithNewModule nps-utils@1.5.0 checking installable status
52 http fetch GET 304 https://registry.npmjs.org/fixpack 281ms (from cache)
53 silly pacote range manifest for fixpack@^2.3.1 fetched in 281ms
54 silly resolveWithNewModule fixpack@2.3.1 checking installable status
55 http fetch GET 304 https://registry.npmjs.org/sort-pjson 1254ms (from cache)
56 silly pacote range manifest for sort-pjson@^1.0.2 fetched in 1255ms
57 silly resolveWithNewModule sort-pjson@1.0.2 checking installable status
58 verbose stack SyntaxError: Unexpected end of input at 1:6202
58 verbose stack ectories":{},"dist":{"shasum":"33ab915659d8c2cc8a41443d94d6ebd37697ed
58 verbose stack                                                                      ^
58 verbose stack     at Object.parseJSON (/Users/sgarlanka/.nvm/versions/node/v8.11.2/lib/node_modules/npx/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/node_modules/json-parse-helpfulerror/node_modules/jju/lib/parse.js:745:13)
58 verbose stack     at parse (/Users/sgarlanka/.nvm/versions/node/v8.11.2/lib/node_modules/npx/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/node_modules/json-parse-helpfulerror/index.js:10:13)
58 verbose stack     at consumeBody.call.then.buffer (/Users/sgarlanka/.nvm/versions/node/v8.11.2/lib/node_modules/npx/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/src/body.js:96:50)
58 verbose stack     at <anonymous>
58 verbose stack     at process._tickCallback (internal/process/next_tick.js:188:7)
59 verbose cwd /Users/sgarlanka/Documents/CLI_Research/oclif
60 verbose Darwin 16.7.0
61 verbose argv "/Users/sgarlanka/.nvm/versions/node/v8.11.2/bin/node" "/Users/sgarlanka/.nvm/versions/node/v8.11.2/lib/node_modules/npx/node_modules/npm/bin/npm-cli.js" "install" "oclif@latest" "--global" "--prefix" "/Users/sgarlanka/.npm/_npx/1819" "--loglevel" "error" "--json"
62 verbose node v8.11.2
63 verbose npm  v5.1.0
64 error Unexpected end of input at 1:6202
64 error ectories":{},"dist":{"shasum":"33ab915659d8c2cc8a41443d94d6ebd37697ed
64 error                                                                      ^
65 verbose exit [ 1, true ]

### supporting information:

 - `npm -v` prints:
5.6.0
 - `node -v` prints:
v8.11.2
 - `npm config get registry` prints:
https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?:
macOS
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by kenany** [comment]
@sujaygarlanka Can you post an error or debug log as well? Thanks!
