### ISSUE TITLE
package-lock.json changes from one `npm install` to the next

### ISSUE THREAD

**Issue by danepowell** [npm/npm#20926]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
When I run `npm install` multiple times _on the same machine_, the contents of package-lock.json change depending on the state of the machine.

On a clean install with no existing node_modules folder, a lot of the packages contain the key `"optional": true`

Subsequently, when node_modules already exists and I run `npm install`, the `"optional": true` keys get removed.

This generates a ton of noise and commit diffs.

#### How can the CLI team reproduce the problem?

I can't post npm-debug.log without some sanitization first, but this was the only thing of note:

```
14 verbose stack Error: bs4@0.1.0 build: `gulp`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:920:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
15 verbose pkgid bs4@0.1.0
```

### supporting information:

 - `npm -v` prints: 6.1.0
 - `node -v` prints: v8.11.2
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Ubuntu 16.04
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [x] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by PeterBenko** [comment]
The same is happening in my project. 
One further observation I made is that after running install with node_modules already present (and with it removing all 'optional': true flags) it takes _several_ 'clean' installs before all optional flags are re-added.

**Comment by kevinburkeomg** [comment]
I'm observing the same issue, and set up the following repository to reproduce the issue: https://github.com/kevinburkeomg/npm-inconsistency

Follow these steps:

1) Clone the repository
2) Run "npm install" to populate `node_modules`. Nothing should change in the git diff
3) Run "npm install" again and observe that the package-lock.json file changes, the reverse of the diff shown here: https://github.com/kevinburkeomg/npm-inconsistency/commit/18b1a21f689610e0242b2298f3f1fc74bdd7b63b

We're currently working around this issue by always running "npm install" twice.

This was sponsored by One Medical.

**Comment by kevinburkeomg** [comment]
I can't reproduce the issue running "npm ci".

**Comment by papandreou** [comment]
This constantly happens to me with npm 6.1.0, causing a lot of `package-lock.json` churn.

The deciding factor seems to be whether I run `npm install` without a package name (removes `optional: true` from `package-lock.json`) or `npm install some-package` (adds it).
