### ISSUE TITLE
Not able to download npm dependency. getting 503 fetch failed error 

### ISSUE THREAD

**Issue by Rohit-chauda** [npm/npm#20928]
#### I'm opening this issue because:  
I am not able to download npm dependencies. I am getting 503 fetch failed error

#### What's going wrong?
Whenever I try to install npm or suppose gulp through npm, dependency fetch getting failed all the time.

As I am not able to attach the log file, just copying and paste the whole file below

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--global',
1 verbose cli   'gulp-cli' ]
2 info using npm@2.15.9
3 info using node@v4.6.0
4 verbose install initial load of /usr/local/lib/package.json
5 verbose readDependencies loading dependencies from /usr/local/lib/package.json
6 silly cache add args [ 'gulp-cli', null ]
7 verbose cache add spec gulp-cli
8 silly cache add parsed spec Result {
8 silly cache add   raw: 'gulp-cli',
8 silly cache add   scope: null,
8 silly cache add   name: 'gulp-cli',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: 'latest',
8 silly cache add   type: 'tag' }
9 silly addNamed gulp-cli@latest
10 verbose addNamed "latest" is being treated as a dist-tag for gulp-cli
11 info addNameTag [ 'gulp-cli', 'latest' ]
12 silly mapToRegistry name gulp-cli
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.com/
15 silly mapToRegistry data Result {
15 silly mapToRegistry   raw: 'gulp-cli',
15 silly mapToRegistry   scope: null,
15 silly mapToRegistry   name: 'gulp-cli',
15 silly mapToRegistry   rawSpec: '',
15 silly mapToRegistry   spec: 'latest',
15 silly mapToRegistry   type: 'tag' }
16 silly mapToRegistry uri https://registry.npmjs.com/gulp-cli
17 verbose addNameTag registry:https://registry.npmjs.com/gulp-cli not in flight; fetching
18 verbose request uri https://registry.npmjs.com/gulp-cli
19 verbose request no auth needed
20 info attempt registry request try #1 at 3:35:51 PM
21 verbose request id 5c8711f32ca0efcd
22 http request GET https://registry.npmjs.com/gulp-cli
23 http 200 https://registry.npmjs.com/gulp-cli
24 verbose headers { date: 'Fri, 08 Jun 2018 10:05:46 GMT',
24 verbose headers   'content-type': 'application/json; charset=UTF-8',
24 verbose headers   'transfer-encoding': 'chunked',
24 verbose headers   connection: 'close',
24 verbose headers   'set-cookie': [ '__cfduid=d90750d770e2eb691888dab07d5f29b7b1528452346; expires=Sat, 08-Jun-19 10:05:46 GMT; path=/; domain=.registry.npmjs.com; HttpOnly' ],
24 verbose headers   'cache-control': 'max-age=300',
24 verbose headers   'cf-cache-status': 'HIT',
24 verbose headers   'cf-ray': '427a8abf6ccd8a4f-BOM',
24 verbose headers   etag: 'W/"efbb70d736d9932650ef1321cbe70c82"',
24 verbose headers   'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
24 verbose headers   'last-modified': 'Sat, 26 May 2018 11:01:41 GMT',
24 verbose headers   vary: 'accept-encoding, accept',
24 verbose headers   server: 'cloudflare',
24 verbose headers   'content-encoding': 'gzip' }
25 silly get cb [ 200,
25 silly get   { date: 'Fri, 08 Jun 2018 10:05:46 GMT',
25 silly get     'content-type': 'application/json; charset=UTF-8',
25 silly get     'transfer-encoding': 'chunked',
25 silly get     connection: 'close',
25 silly get     'set-cookie': [ '__cfduid=d90750d770e2eb691888dab07d5f29b7b1528452346; expires=Sat, 08-Jun-19 10:05:46 GMT; path=/; domain=.registry.npmjs.com; HttpOnly' ],
25 silly get     'cache-control': 'max-age=300',
25 silly get     'cf-cache-status': 'HIT',
25 silly get     'cf-ray': '427a8abf6ccd8a4f-BOM',
25 silly get     etag: 'W/"efbb70d736d9932650ef1321cbe70c82"',
25 silly get     'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
25 silly get     'last-modified': 'Sat, 26 May 2018 11:01:41 GMT',
25 silly get     vary: 'accept-encoding, accept',
25 silly get     server: 'cloudflare',
25 silly get     'content-encoding': 'gzip' } ]
26 verbose get saving gulp-cli to /Users/e052024/.npm/registry.npmjs.com/gulp-cli/.cache.json
27 verbose correctMkdir /Users/e052024/.npm correctMkdir not in flight; initializing
28 silly addNameTag next cb for gulp-cli with tag latest
29 silly addNamed gulp-cli@2.0.1
30 verbose addNamed "2.0.1" is a plain semver version for gulp-cli
31 silly mapToRegistry name gulp-cli
32 silly mapToRegistry using default registry
33 silly mapToRegistry registry https://registry.npmjs.com/
34 silly mapToRegistry data Result {
34 silly mapToRegistry   raw: 'gulp-cli',
34 silly mapToRegistry   scope: null,
34 silly mapToRegistry   name: 'gulp-cli',
34 silly mapToRegistry   rawSpec: '',
34 silly mapToRegistry   spec: 'latest',
34 silly mapToRegistry   type: 'tag' }
35 silly mapToRegistry uri https://registry.npmjs.com/gulp-cli
36 verbose addRemoteTarball https://registry.npmjs.org/gulp-cli/-/gulp-cli-2.0.1.tgz not in flight; adding
37 verbose addRemoteTarball [ 'https://registry.npmjs.org/gulp-cli/-/gulp-cli-2.0.1.tgz',
37 verbose addRemoteTarball   '7847e220cb3662f2be8a6d572bf14e17be5a994b' ]
38 info retry fetch attempt 1 at 3:35:52 PM
39 info attempt registry request try #1 at 3:35:52 PM
40 http fetch GET https://registry.npmjs.org/gulp-cli/-/gulp-cli-2.0.1.tgz
41 http fetch 503 https://registry.npmjs.org/gulp-cli/-/gulp-cli-2.0.1.tgz
42 info retry will retry, error on last attempt: Error: server error 503
43 info attempt registry request try #2 at 3:36:02 PM
44 http fetch GET https://registry.npmjs.org/gulp-cli/-/gulp-cli-2.0.1.tgz
45 http fetch 503 https://registry.npmjs.org/gulp-cli/-/gulp-cli-2.0.1.tgz
46 info retry will retry, error on last attempt: Error: server error 503
47 info attempt registry request try #3 at 3:37:02 PM
48 http fetch GET https://registry.npmjs.org/gulp-cli/-/gulp-cli-2.0.1.tgz
49 http fetch 503 https://registry.npmjs.org/gulp-cli/-/gulp-cli-2.0.1.tgz
50 error fetch failed https://registry.npmjs.org/gulp-cli/-/gulp-cli-2.0.1.tgz
51 warn retry will retry, error on last attempt: Error: fetch failed with status code 503
52 info retry fetch attempt 2 at 3:37:12 PM
53 info attempt registry request try #1 at 3:37:12 PM
54 http fetch GET https://registry.npmjs.org/gulp-cli/-/gulp-cli-2.0.1.tgz
55 http fetch 503 https://registry.npmjs.org/gulp-cli/-/gulp-cli-2.0.1.tgz
56 info retry will retry, error on last attempt: Error: server error 503
57 info attempt registry request try #2 at 3:37:22 PM
58 http fetch GET https://registry.npmjs.org/gulp-cli/-/gulp-cli-2.0.1.tgz
59 http fetch 503 https://registry.npmjs.org/gulp-cli/-/gulp-cli-2.0.1.tgz
60 info retry will retry, error on last attempt: Error: server error 503
61 info attempt registry request try #3 at 3:38:22 PM
62 http fetch GET https://registry.npmjs.org/gulp-cli/-/gulp-cli-2.0.1.tgz
63 http fetch 503 https://registry.npmjs.org/gulp-cli/-/gulp-cli-2.0.1.tgz
64 error fetch failed https://registry.npmjs.org/gulp-cli/-/gulp-cli-2.0.1.tgz
65 warn retry will retry, error on last attempt: Error: fetch failed with status code 503
66 info retry fetch attempt 3 at 3:39:22 PM
67 info attempt registry request try #1 at 3:39:22 PM
68 http fetch GET https://registry.npmjs.org/gulp-cli/-/gulp-cli-2.0.1.tgz
69 http fetch 503 https://registry.npmjs.org/gulp-cli/-/gulp-cli-2.0.1.tgz
70 info retry will retry, error on last attempt: Error: server error 503
71 info attempt registry request try #2 at 3:39:32 PM
72 http fetch GET https://registry.npmjs.org/gulp-cli/-/gulp-cli-2.0.1.tgz
73 http fetch 503 https://registry.npmjs.org/gulp-cli/-/gulp-cli-2.0.1.tgz
74 info retry will retry, error on last attempt: Error: server error 503
75 info attempt registry request try #3 at 3:40:35 PM
76 http fetch GET https://registry.npmjs.org/gulp-cli/-/gulp-cli-2.0.1.tgz
77 http fetch 503 https://registry.npmjs.org/gulp-cli/-/gulp-cli-2.0.1.tgz
78 error fetch failed https://registry.npmjs.org/gulp-cli/-/gulp-cli-2.0.1.tgz
79 verbose stack Error: fetch failed with status code 503
79 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/fetch.js:51:14)
79 verbose stack     at emitOne (events.js:77:13)
79 verbose stack     at Request.emit (events.js:169:7)
79 verbose stack     at Request.onRequestResponse (/usr/local/lib/node_modules/npm/node_modules/request/request.js:977:10)
79 verbose stack     at emitOne (events.js:77:13)
79 verbose stack     at ClientRequest.emit (events.js:169:7)
79 verbose stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:433:21)
79 verbose stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:103:23)
79 verbose stack     at TLSSocket.socketOnData (_http_client.js:322:20)
79 verbose stack     at emitOne (events.js:77:13)
80 verbose cwd /Users/e052024
81 error Darwin 16.7.0
82 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--global" "gulp-cli"
83 error node v4.6.0
84 error npm  v2.15.9
85 error fetch failed with status code 503
86 error If you need help, you may report this error at:
86 error     <https://github.com/npm/npm/issues>
87 verbose exit [ 1, true ]

**Comment by legodude17** [comment]
Your versions of node and npm are old and unsupported. Please update.
