### ISSUE TITLE
Error "Cannot find module './lib'" trying to install a global module

### ISSUE THREAD

**Issue by uluhonolulu** [npm/npm#20970]
#### I'm opening this issue because:

  - [*] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
When I run `npm install -g yo generator-code` it produces the following output:
```
npm ERR! code MODULE_NOT_FOUND
npm ERR! Cannot find module './lib'
```
And the log is:
```
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'yo',
1 verbose cli   'generator-code' ]
2 info using npm@6.1.0
3 info using node@v10.4.0
4 verbose npm-session 17b157ad21313615
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 verbose stack Error: Cannot find module './lib'
7 verbose stack     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
7 verbose stack     at Function.Module._load (internal/modules/cjs/loader.js:520:25)
7 verbose stack     at Module.require (internal/modules/cjs/loader.js:650:17)
7 verbose stack     at require (internal/modules/cjs/helpers.js:20:18)
7 verbose stack     at Object.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\node_modules\hawk\index.js:1:80)
7 verbose stack     at Module._compile (internal/modules/cjs/loader.js:702:30)
7 verbose stack     at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
7 verbose stack     at Module.load (internal/modules/cjs/loader.js:612:32)
7 verbose stack     at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
7 verbose stack     at Function.Module._load (internal/modules/cjs/loader.js:543:3)
7 verbose stack     at Module.require (internal/modules/cjs/loader.js:650:17)
7 verbose stack     at require (internal/modules/cjs/helpers.js:20:18)
7 verbose stack     at Object.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:9:12)
7 verbose stack     at Module._compile (internal/modules/cjs/loader.js:702:30)
7 verbose stack     at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
7 verbose stack     at Module.load (internal/modules/cjs/loader.js:612:32)
8 verbose cwd D:\Projects
9 verbose Windows_NT 6.1.7601
10 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "yo" "generator-code"
11 verbose node v10.4.0
12 verbose npm  v6.1.0
13 error code MODULE_NOT_FOUND
14 error Cannot find module './lib'
15 verbose exit [ 1, true ]
```

When I open the folder `C:\Program Files\nodejs\node_modules\npm\node_modules\request\node_modules\hawk`, I don't see the /lib folder indeed. What I see is `index.js` and `Makefile`, so I guess it needs to be built or something. 

### supporting information:

 - `npm -v` prints: 6.1.0
 - `node -v` prints: v10.4.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows 7

**Comment by legodude17** [comment]
Do you use a version manager for node?

**Comment by uluhonolulu** [comment]
> Do you use a version manager for node?

@legodude17 no

**Comment by uluhonolulu** [comment]
Fixed by uninstalling Node and installing v8. Not sure if I should close it.

**Comment by kenany** [comment]
This kinda looks like a broken install to me, hence why reinstalling Node.js (and by extension `npm`) fixed it. If this makes sense then feel free to close.
