### ISSUE TITLE
`npm add` fails with message about missing version of a dependency

### ISSUE THREAD

**Issue by Ky6uk** [npm/npm#20971]
#### I'm opening this issue because:

  - [x] npm is doing something I don't understand.
  - [x] npm is producing incorrect or undesirable behavior.

#### What's going wrong?

NPM rejects to install package because some of dependencies' version are not available. But requested version of the dependency just available as expected and can be installed separately without problems.

After one hour NPM finally installs that package with dependencies.

I have no idea what was happening. 

#### How can the CLI team reproduce the problem?

I tried to execute the `npm add @babel/core`.

<details>
<summary>Console Output</summary>

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @babel/helper-function-name@7.0.0-beta.50
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of '@babel/traverse'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ky6uk/.npm/_logs/2018-06-12T20_46_05_048Z-debug.log
```
</details>
<br />

When really it is:

```
$ npm info @babel/helper-function-name version
7.0.0-beta.50
```

<details>
<summary>Debug Log</summary>

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/10.4.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'add',
1 verbose cli   '@babel/core' ]
2 info using npm@6.1.0
3 info using node@v10.4.0
4 verbose npm-session d03885a83363639a
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://registry.npmjs.org/@babel%2fcore 28ms (from cache)
8 silly pacote tag manifest for @babel/core@latest fetched in 98ms
9 timing stage:loadCurrentTree Completed in 299ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 1ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 1ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule @babel/core@7.0.0-beta.50 checking installable status
17 http fetch GET 200 https://registry.npmjs.org/@babel%2fparser 81ms (from cache)
18 http fetch GET 200 https://registry.npmjs.org/@babel%2fcode-frame 85ms (from cache)
19 http fetch GET 200 https://registry.npmjs.org/@babel%2ftemplate 83ms (from cache)
20 http fetch GET 200 https://registry.npmjs.org/@babel%2fhelpers 86ms (from cache)
21 http fetch GET 200 https://registry.npmjs.org/@babel%2fgenerator 86ms (from cache)
22 http fetch GET 200 https://registry.npmjs.org/@babel%2ftraverse 82ms (from cache)
23 http fetch GET 200 https://registry.npmjs.org/@babel%2ftypes 82ms (from cache)
24 silly pacote version manifest for @babel/parser@7.0.0-beta.50 fetched in 89ms
25 silly resolveWithNewModule @babel/parser@7.0.0-beta.50 checking installable status
26 silly pacote version manifest for @babel/code-frame@7.0.0-beta.50 fetched in 97ms
27 silly resolveWithNewModule @babel/code-frame@7.0.0-beta.50 checking installable status
28 silly pacote version manifest for @babel/generator@7.0.0-beta.50 fetched in 96ms
29 silly resolveWithNewModule @babel/generator@7.0.0-beta.50 checking installable status
30 silly pacote version manifest for @babel/helpers@7.0.0-beta.50 fetched in 98ms
31 silly resolveWithNewModule @babel/helpers@7.0.0-beta.50 checking installable status
32 silly pacote version manifest for @babel/template@7.0.0-beta.50 fetched in 97ms
33 silly resolveWithNewModule @babel/template@7.0.0-beta.50 checking installable status
34 silly pacote version manifest for @babel/traverse@7.0.0-beta.50 fetched in 99ms
35 silly resolveWithNewModule @babel/traverse@7.0.0-beta.50 checking installable status
36 silly pacote version manifest for @babel/types@7.0.0-beta.50 fetched in 98ms
37 silly resolveWithNewModule @babel/types@7.0.0-beta.50 checking installable status
38 http fetch GET 304 https://registry.npmjs.org/debug 287ms (from cache)
39 http fetch GET 304 https://registry.npmjs.org/json5 287ms (from cache)
40 http fetch GET 304 https://registry.npmjs.org/convert-source-map 291ms (from cache)
41 silly pacote range manifest for json5@^0.5.0 fetched in 293ms
42 silly resolveWithNewModule json5@0.5.1 checking installable status
43 silly pacote range manifest for debug@^3.1.0 fetched in 295ms
44 silly resolveWithNewModule debug@3.1.0 checking installable status
45 silly pacote range manifest for convert-source-map@^1.1.0 fetched in 298ms
46 silly resolveWithNewModule convert-source-map@1.5.1 checking installable status
47 http fetch GET 304 https://registry.npmjs.org/semver 206ms (from cache)
48 http fetch GET 304 https://registry.npmjs.org/lodash 215ms (from cache)
49 silly pacote range manifest for semver@^5.4.1 fetched in 211ms
50 silly resolveWithNewModule semver@5.5.0 checking installable status
51 silly pacote range manifest for lodash@^4.17.5 fetched in 219ms
52 silly resolveWithNewModule lodash@4.17.10 checking installable status
53 http fetch GET 304 https://registry.npmjs.org/resolve 214ms (from cache)
54 silly pacote range manifest for resolve@^1.3.2 fetched in 218ms
55 silly resolveWithNewModule resolve@1.7.1 checking installable status
56 http fetch GET 304 https://registry.npmjs.org/micromatch 246ms (from cache)
57 silly pacote range manifest for micromatch@^3.1.10 fetched in 250ms
58 silly resolveWithNewModule micromatch@3.1.10 checking installable status
59 http fetch GET 304 https://registry.npmjs.org/source-map 698ms (from cache)
60 silly pacote range manifest for source-map@^0.5.0 fetched in 702ms
61 silly resolveWithNewModule source-map@0.5.7 checking installable status
62 http fetch GET 200 https://registry.npmjs.org/@babel%2fhighlight 6ms (from cache)
63 silly pacote version manifest for @babel/highlight@7.0.0-beta.50 fetched in 8ms
64 silly resolveWithNewModule @babel/highlight@7.0.0-beta.50 checking installable status
65 http fetch GET 304 https://registry.npmjs.org/js-tokens 59ms (from cache)
66 http fetch GET 304 https://registry.npmjs.org/chalk 61ms (from cache)
67 silly pacote range manifest for js-tokens@^3.0.0 fetched in 62ms
68 silly resolveWithNewModule js-tokens@3.0.2 checking installable status
69 silly pacote range manifest for chalk@^2.0.0 fetched in 64ms
70 silly resolveWithNewModule chalk@2.4.1 checking installable status
71 http fetch GET 304 https://registry.npmjs.org/esutils 2771ms (from cache)
72 silly pacote range manifest for esutils@^2.0.2 fetched in 2773ms
73 silly resolveWithNewModule esutils@2.0.2 checking installable status
74 http fetch GET 304 https://registry.npmjs.org/escape-string-regexp 60ms (from cache)
75 http fetch GET 304 https://registry.npmjs.org/supports-color 60ms (from cache)
76 silly pacote range manifest for escape-string-regexp@^1.0.5 fetched in 62ms
77 silly resolveWithNewModule escape-string-regexp@1.0.5 checking installable status
78 silly pacote range manifest for supports-color@^5.3.0 fetched in 63ms
79 silly resolveWithNewModule supports-color@5.4.0 checking installable status
80 http fetch GET 304 https://registry.npmjs.org/ansi-styles 65ms (from cache)
81 silly pacote range manifest for ansi-styles@^3.2.1 fetched in 68ms
82 silly resolveWithNewModule ansi-styles@3.2.1 checking installable status
83 http fetch GET 304 https://registry.npmjs.org/color-convert 190ms (from cache)
84 silly pacote range manifest for color-convert@^1.9.0 fetched in 193ms
85 silly resolveWithNewModule color-convert@1.9.2 checking installable status
86 http fetch GET 304 https://registry.npmjs.org/color-name 70ms (from cache)
87 silly pacote version manifest for color-name@1.1.1 fetched in 72ms
88 silly resolveWithNewModule color-name@1.1.1 checking installable status
89 http fetch GET 304 https://registry.npmjs.org/has-flag 60ms (from cache)
90 silly pacote range manifest for has-flag@^3.0.0 fetched in 62ms
91 silly resolveWithNewModule has-flag@3.0.0 checking installable status
92 http fetch GET 304 https://registry.npmjs.org/trim-right 52ms (from cache)
93 silly pacote range manifest for trim-right@^1.0.1 fetched in 54ms
94 silly resolveWithNewModule trim-right@1.0.1 checking installable status
95 http fetch GET 304 https://registry.npmjs.org/jsesc 72ms (from cache)
96 silly pacote range manifest for jsesc@^2.5.1 fetched in 75ms
97 silly resolveWithNewModule jsesc@2.5.1 checking installable status
98 http fetch GET 304 https://registry.npmjs.org/to-fast-properties 174ms (from cache)
99 silly pacote range manifest for to-fast-properties@^2.0.0 fetched in 176ms
100 silly resolveWithNewModule to-fast-properties@2.0.0 checking installable status
101 http fetch GET 200 https://registry.npmjs.org/@babel%2fhelper-split-export-declaration 14ms (from cache)
102 http fetch GET 200 https://registry.npmjs.org/@babel%2fhelper-function-name 18ms (from cache)
103 silly registry:manifest no matching version for @babel/helper-function-name@7.0.0-beta.50 in the cache. Forcing revalidation
104 silly pacote version manifest for @babel/helper-split-export-declaration@7.0.0-beta.50 fetched in 18ms
105 silly resolveWithNewModule @babel/helper-split-export-declaration@7.0.0-beta.50 checking installable status
106 http fetch GET 304 https://registry.npmjs.org/globals 59ms (from cache)
107 silly pacote range manifest for globals@^11.1.0 fetched in 63ms
108 silly resolveWithNewModule globals@11.5.0 checking installable status
109 http fetch GET 304 https://registry.npmjs.org/invariant 66ms (from cache)
110 silly pacote range manifest for invariant@^2.2.0 fetched in 68ms
111 silly resolveWithNewModule invariant@2.2.4 checking installable status
112 http fetch GET 304 https://registry.npmjs.org/@babel%2fhelper-function-name 91ms (from cache)
113 silly fetchPackageMetaData error for @babel/helper-function-name@7.0.0-beta.50 No matching version found for @babel/helper-function-name@7.0.0-beta.50
114 timing stage:rollbackFailedOptional Completed in 1ms
115 timing stage:runTopLevelLifecycles Completed in 4724ms
116 silly saveTree t@1.0.0
116 silly saveTree └─┬ @babel/core@7.0.0-beta.50
116 silly saveTree   ├─┬ @babel/code-frame@7.0.0-beta.50
116 silly saveTree   │ └─┬ @babel/highlight@7.0.0-beta.50
116 silly saveTree   │   ├─┬ chalk@2.4.1
116 silly saveTree   │   │ ├─┬ ansi-styles@3.2.1
116 silly saveTree   │   │ │ └─┬ color-convert@1.9.2
116 silly saveTree   │   │ │   └── color-name@1.1.1
116 silly saveTree   │   │ ├── escape-string-regexp@1.0.5
116 silly saveTree   │   │ └─┬ supports-color@5.4.0
116 silly saveTree   │   │   └── has-flag@3.0.0
116 silly saveTree   │   ├── esutils@2.0.2
116 silly saveTree   │   └── js-tokens@3.0.2
116 silly saveTree   ├─┬ @babel/generator@7.0.0-beta.50
116 silly saveTree   │ ├─┬ @babel/types@7.0.0-beta.50
116 silly saveTree   │ │ ├── lodash@4.17.10
116 silly saveTree   │ │ └── to-fast-properties@2.0.0
116 silly saveTree   │ ├── jsesc@2.5.1
116 silly saveTree   │ ├── lodash@4.17.10
116 silly saveTree   │ ├── source-map@0.5.7
116 silly saveTree   │ └── trim-right@1.0.1
116 silly saveTree   ├─┬ @babel/helpers@7.0.0-beta.50
116 silly saveTree   │ ├─┬ @babel/template@7.0.0-beta.50
116 silly saveTree   │ │ └── @babel/parser@7.0.0-beta.50
116 silly saveTree   │ └─┬ @babel/traverse@7.0.0-beta.50
116 silly saveTree   │   ├── @babel/helper-split-export-declaration@7.0.0-beta.50
116 silly saveTree   │   ├── debug@3.1.0
116 silly saveTree   │   ├── globals@11.5.0
116 silly saveTree   │   └── invariant@2.2.4
116 silly saveTree   ├── @babel/parser@7.0.0-beta.50
116 silly saveTree   ├── @babel/template@7.0.0-beta.50
116 silly saveTree   ├── @babel/traverse@7.0.0-beta.50
116 silly saveTree   ├── @babel/types@7.0.0-beta.50
116 silly saveTree   ├── convert-source-map@1.5.1
116 silly saveTree   ├── debug@3.1.0
116 silly saveTree   ├── json5@0.5.1
116 silly saveTree   ├── lodash@4.17.10
116 silly saveTree   ├── micromatch@3.1.10
116 silly saveTree   ├── resolve@1.7.1
116 silly saveTree   ├── semver@5.5.0
116 silly saveTree   └── source-map@0.5.7
117 verbose type version
118 verbose stack @babel/helper-function-name: No matching version found for @babel/helper-function-name@7.0.0-beta.50
118 verbose stack     at pickManifest (/usr/local/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:65:11)
118 verbose stack     at fetchPackument.then.packument (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/manifest.js:52:18)
118 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
118 verbose stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
118 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
118 verbose stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
118 verbose stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
118 verbose stack     at Async._drainQueue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
118 verbose stack     at Async._drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
118 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
118 verbose stack     at runCallback (timers.js:696:18)
118 verbose stack     at tryOnImmediate (timers.js:667:5)
118 verbose stack     at processImmediate (timers.js:649:5)
119 verbose cwd /private/tmp/t
120 verbose Darwin 17.6.0
121 verbose argv "/usr/local/Cellar/node/10.4.0/bin/node" "/usr/local/bin/npm" "add" "@babel/core"
122 verbose node v10.4.0
123 verbose npm  v6.1.0
124 error code ETARGET
125 error notarget No matching version found for @babel/helper-function-name@7.0.0-beta.50
126 error notarget In most cases you or one of your dependencies are requesting
126 error notarget a package version that doesn't exist.
126 error notarget
126 error notarget It was specified as a dependency of '@babel/traverse'
127 verbose exit [ 1, true ]
```
</details>

### supporting information:

 - `npm -v` prints: `6.1.0`
 - `node -v` prints: `10.4.0`
 - `npm config get registry` prints: `https://registry.npmjs.org/`
 - Windows, OS X/macOS, or Linux?: `OS X`

**Comment by Ky6uk** [comment]
Also strange:

```
$ npm outdated stylelint
Package    Current  Wanted  Latest  Location
stylelint    9.2.1   9.2.1   9.3.0  project
```

```
$ npm install
npm ERR! code ETARGET
npm ERR! notarget No matching version found for stylelint@9.3.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'project'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ky6uk/.npm/_logs/2018-06-15T14_23_49_146Z-debug.log
```
