### ISSUE TITLE
I can't run npm install anymore

### ISSUE THREAD

**Issue by rishirajshukla** [npm/npm#20975]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by rishirajshukla** [comment]
I can't install npm anymore. 

npm ERR! addLocal Could not install /frontend/node_modules/angular
npm ERR! Linux 4.13.0-43-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v6.14.2
npm ERR! npm  v3.10.10
npm ERR! path /frontend/node_modules/angular
npm ERR! code ELOOP
npm ERR! errno -40
npm ERR! syscall open

npm ERR! ELOOP: too many symbolic links encountered, open '/frontend/node_modules/angular'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!    /frontend/npm-debug.log

**Comment by rideordieGTi** [comment]
install npm@latest
fetching: https://registry.npmjs.org/npm/-/npm-6.1.0.tgz
module.js:549
    throw err;
    ^

Error: Cannot find module '/tmp/npm.25835/package/bin/read-package-json.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
up to date in 0.062s
npm ERR! path ../../../tmp/npm.25835/package
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall symlink
npm ERR! enoent ENOENT: no such file or directory, symlink '../../../tmp/npm.25835/package' -> '/usr/lib/node_modules/npm'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/gtiuser/.npm/_logs/2018-06-16T14_11_50_735Z-debug.log
It failed


got also problems installing.. wasn't installed with node.js and I'm not able to install manually...
