### ISSUE TITLE
Error after running npm in windows 7 64bit

### ISSUE THREAD

**Issue by ggsgowtham** [npm/npm#21008]
Hi,

   I have installed node js 8.11.3 for windows 7 64-bit and after running the npm i am getting the following error : 

**CALL "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\\node_modules
\npm\bin\npm-cli.js" prefix -g' is not recognized as an internal or external com
mand,
operable program or batch file.** 
I am not able to proceed or install anything(angular cli etc..) because of this error. Please, reply t the issue with a solution ASAP.

Thank you.

**Comment by rneha725** [comment]
Can you please check your environmental variables, if in 'PATH' node is there or not.

**Comment by ggsgowtham** [comment]
I have node in my path variable

**Comment by ggsgowtham** [comment]
I have reinstalled it, then also it is showing the same issue.

**Comment by rneha725** [comment]
Can you check the following:
[https://github.com/npm/npm/wiki/Troubleshooting#a-brief-note-on-the-built-in-windows-configuration](https://github.com/npm/npm/wiki/Troubleshooting#a-brief-note-on-the-built-in-windows-configuration)

**Comment by ggsgowtham** [comment]
I have checked and worked on all the issues that are related to my problem but still the problem exists.

**Comment by qfox** [comment]
Just installed nodejs 8.11.3 on windows from nodejs.org and got this:
```
$ npm -v
module.js:549
    throw err;
    ^

Error: Cannot find module 'internal/util/types'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at evalmachine.<anonymous>:31:26
    at Object.<anonymous> (C:\Users\alex\AppData\Roaming\npm\
```

**Comment by ggsgowtham** [comment]
install the modules using "npm install" command.

**Comment by qfox** [comment]
> install the modules using "npm install" command.

`npm` doesnt work at all after switching from 4.x to 8.x+

I've fixed this locally via removing `AppData/Roaming/{npm,npm-cache}` directories and repairing node.js installation. Not sure it's critical but frustrating
