### ISSUE TITLE
Not able to install private package.

### ISSUE THREAD

**Issue by ghost** [npm/npm#21024]
HI,
I am able to push new version, but not able to install it. I have tried copy and pasting command from npm website. still it doesn't work. Other npm packages are getting installed fine.

D:\github\project>npm i @thblib/bg-correct-updated-date-of-patients
npm WARN notice this endpoint is deprecated
npm ERR! code E404
npm ERR! 404 Not Found: @thblib/bg-correct-updated-date-of-patients@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2018-06-20T06_42_15_613Z-debug.log

**Comment by ghost** [comment]
here is debug log:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Users\\rajesh\\AppData\\Roaming\\nvm\\v8.11.1\\node.exe',
1 verbose cli   'C:\\Users\\rajesh\\AppData\\Roaming\\nvm\\v8.11.1\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'i',
1 verbose cli   '@thblib/bg-correct-updated-date-of-patients' ]
2 info using npm@5.6.0
3 info using node@v8.11.1
4 verbose npm-session 9929a931a3f7b3f7
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 warn notice this endpoint is deprecated
8 http fetch GET 404 https://registry.npmjs.org/@thblib%2fbg-correct-updated-date-of-patients 1379ms
9 silly fetchPackageMetaData error for @thblib/bg-correct-updated-date-of-patients@0.0.18 404 Not Found: @thblib/bg-correct-updated-date-of-patients@0.0.18
10 verbose stack Error: 404 Not Found: @thblib/bg-correct-updated-date-of-patients@0.0.18
10 verbose stack     at fetch.then.res (C:\Users\rajesh\AppData\Roaming\nvm\v8.11.1\node_modules\npm\node_modules\pacote\lib\fetchers\registry\fetch.js:42:19)
10 verbose stack     at tryCatcher (C:\Users\rajesh\AppData\Roaming\nvm\v8.11.1\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
10 verbose stack     at Promise._settlePromiseFromHandler (C:\Users\rajesh\AppData\Roaming\nvm\v8.11.1\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
10 verbose stack     at Promise._settlePromise (C:\Users\rajesh\AppData\Roaming\nvm\v8.11.1\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
10 verbose stack     at Promise._settlePromise0 (C:\Users\rajesh\AppData\Roaming\nvm\v8.11.1\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
10 verbose stack     at Promise._settlePromises (C:\Users\rajesh\AppData\Roaming\nvm\v8.11.1\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
10 verbose stack     at Async._drainQueue (C:\Users\rajesh\AppData\Roaming\nvm\v8.11.1\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
10 verbose stack     at Async._drainQueues (C:\Users\rajesh\AppData\Roaming\nvm\v8.11.1\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
10 verbose stack     at Immediate.Async.drainQueues (C:\Users\rajesh\AppData\Roaming\nvm\v8.11.1\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
10 verbose stack     at runCallback (timers.js:794:20)
10 verbose stack     at tryOnImmediate (timers.js:752:5)
10 verbose stack     at processImmediate [as _immediateCallback] (timers.js:729:5)
11 verbose cwd C:\Users\rajesh\Documents\GitHub\thb-backgroundtasks
12 verbose Windows_NT 10.0.14393
13 verbose argv "C:\\Users\\rajesh\\AppData\\Roaming\\nvm\\v8.11.1\\node.exe" "C:\\Users\\rajesh\\AppData\\Roaming\\nvm\\v8.11.1\\node_modules\\npm\\bin\\npm-cli.js" "i" "@thblib/bg-correct-updated-date-of-patients"
14 verbose node v8.11.1
15 verbose npm  v5.6.0
16 error code E404
17 error 404 Not Found: @thblib/bg-correct-updated-date-of-patients@0.0.18
18 verbose exit [ 1, true ]

**Comment by rajeshpachar** [comment]
here is install output in aws linux machine:

[ec2-user@ip-172-31-xx-xx thb-backgroundtasks]$ npm i @thblib/bg-correct-updated-date-of-patients@0.0.15
npm WARN notice this endpoint is deprecated
npm ERR! code E404
npm ERR! 404 Not Found: @thblib/bg-correct-updated-date-of-patients@0.0.15

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ec2-user/.npm/_logs/2018-06-22T07_50_09_576Z-debug.log


here is dump of debug log

```
0 info it worked if it ends with ok
1 verbose cli [ '/home/ec2-user/.nvm/versions/node/v8.8.1/bin/node',
1 verbose cli   '/home/ec2-user/.nvm/versions/node/v8.8.1/bin/npm',
1 verbose cli   'i',
1 verbose cli   '@thblib/bg-correct-updated-date-of-patients@0.0.15' ]
2 info using npm@5.4.2
3 info using node@v8.8.1
4 verbose npm-session a63145dc2fdc78a1
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 warn notice this endpoint is deprecated
8 http fetch GET 404 https://registry.npmjs.org/@thblib%2fbg-correct-updated-date-of-patients 2239ms
9 silly fetchPackageMetaData error for @thblib/bg-correct-updated-date-of-patients@0.0.15 404 Not Found: @thblib/bg-correct-updated-date-of-patients@0.0.15
10 verbose stack Error: 404 Not Found: @thblib/bg-correct-updated-date-of-patients@0.0.15
10 verbose stack     at fetch.then.res (/home/ec2-user/.nvm/versions/node/v8.8.1/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:42:19)
10 verbose stack     at tryCatcher (/home/ec2-user/.nvm/versions/node/v8.8.1/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
10 verbose stack     at Promise._settlePromiseFromHandler (/home/ec2-user/.nvm/versions/node/v8.8.1/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
10 verbose stack     at Promise._settlePromise (/home/ec2-user/.nvm/versions/node/v8.8.1/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
10 verbose stack     at Promise._settlePromise0 (/home/ec2-user/.nvm/versions/node/v8.8.1/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
10 verbose stack     at Promise._settlePromises (/home/ec2-user/.nvm/versions/node/v8.8.1/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
10 verbose stack     at Async._drainQueue (/home/ec2-user/.nvm/versions/node/v8.8.1/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
10 verbose stack     at Async._drainQueues (/home/ec2-user/.nvm/versions/node/v8.8.1/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
10 verbose stack     at Immediate.Async.drainQueues (/home/ec2-user/.nvm/versions/node/v8.8.1/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
10 verbose stack     at runCallback (timers.js:785:20)
10 verbose stack     at tryOnImmediate (timers.js:747:5)
10 verbose stack     at processImmediate [as _immediateCallback] (timers.js:718:5)
11 verbose cwd /home/ec2-user/src/background-em3/thb-backgroundtasks
12 verbose Linux 4.9.75-25.55.amzn1.x86_64
13 verbose argv "/home/ec2-user/.nvm/versions/node/v8.8.1/bin/node" "/home/ec2-user/.nvm/versions/node/v8.8.1/bin/npm" "i" "@thblib/bg-correct-updated-date-of-patients@0.0.15"
14 verbose node v8.8.1
15 verbose npm  v5.4.2
16 error code E404
17 error 404 Not Found: @thblib/bg-correct-updated-date-of-patients@0.0.15
18 verbose exit [ 1, true ]
```

**Comment by rajeshpachar** [comment]
even the latest command does't work

npm i @thblib/bg-correct-updated-date-of-patients
npm WARN notice this endpoint is deprecated
npm ERR! code E404
npm ERR! 404 Not Found: @thblib/bg-correct-updated-date-of-patients@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ec2-user/.npm/_logs/2018-06-22T09_17_15_855Z-debug.log

same issues is seen with npm view command

[ec2-user@ip-172-31-xx-xx tmp]$ npm view @thblib/bg-correct-updated-date-of-patients
npm WARN notice this endpoint is deprecated
npm ERR! code E404
npm ERR! 404 Not Found


   ╭─────────────────────────────────────╮
   │                                     │
   │   Update available 5.4.2 → 6.1.0    │
   │     Run npm i -g npm to update      │
   │                                     │
   ╰─────────────────────────────────────╯


npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ec2-user/.npm/_logs/2018-06-22T09_18_09_647Z-debug.log
