### ISSUE TITLE
npm ERR! code ENOENT

### ISSUE THREAD

**Issue by thisVioletHydra** [npm/npm#21039]
Microsoft Windows [Version 10.0.17134.112]
(c) Корпорация Майкрософт (Microsoft Corporation), 2018. Все права защищены.

C:\Users\Admin>%CMDER_ROOT%\vendor\init.bat
Системе не удается найти указанный путь.

C:\Users\Admin>npm i npm@latest -g
``` npm ERR! path C:\Program Files\nodejs\node.exe
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm ERR! syscall spawn C:\Program Files\nodejs\node.exe
npm ERR! enoent spawn C:\Program Files\nodejs\node.exe ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
npm ERR! Callback called more than once.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2018-06-21T15_51_16_400Z-debug.log
npm ERR! path C:\Program Files\nodejs\node.exe
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm ERR! syscall spawn C:\Program Files\nodejs\node.exe
npm ERR! enoent spawn C:\Program Files\nodejs\node.exe ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
C:\Users\Admin>npm -v
npm ERR! path C:\Program Files\nodejs\node.exe
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm ERR! syscall spawn C:\Program Files\nodejs\node.exe
npm ERR! enoent spawn C:\Program Files\nodejs\node.exe ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
npm ERR! Callback called more than once.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2018-06-21T15_53_19_441Z-debug.log
6.1.0
C:\Users\Admin>node -v
v10.5.0
C:\Users\Admin>
```

## logs:
``` 0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'prefix',
1 verbose cli   '-g' ]
2 info using npm@6.1.0
3 info using node@v10.5.0
4 verbose stack Error: spawn C:\Program Files\nodejs\node.exe ENOENT
4 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
4 verbose stack     at onErrorNT (internal/child_process.js:406:16)
4 verbose stack     at process._tickCallback (internal/process/next_tick.js:63:19)
5 verbose cwd C:\Users\Admin
6 verbose Windows_NT 10.0.17134
7 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "prefix" "-g"
8 verbose node v10.5.0
9 verbose npm  v6.1.0
10 error path C:\Program Files\nodejs\node.exe
11 error code ENOENT
12 error errno ENOENT
13 error syscall spawn C:\Program Files\nodejs\node.exe
14 error enoent spawn C:\Program Files\nodejs\node.exe ENOENT
15 error enoent This is related to npm not being able to find a file.
16 verbose exit [ 1, true ]

**Comment by legodude17** [comment]
Is node of your path in the correct place?

**Comment by thisVioletHydra** [comment]
@legodude17 default place

**Comment by thisVioletHydra** [comment]
Answer:
https://stackoverflow.com/a/43795421/8488993
