### ISSUE TITLE
Cannot find module 'internal/util/types' for node 8.9.4

### ISSUE THREAD

**Issue by momoryoma4488** [npm/npm#21057]
#### I'm opening this issue because:

  - I cannot proceed in fetch the themes on the current tools that I am using

#### What's going wrong?
- I tried to run gulp theme:fetch but is encountering the following error:
C:\...\node_modules\node-sass\lib\binding.js:15
      throw new Error(errors.missingBinary());
      ^
Error: Missing binding C:\...\node_modules\node-sass\vendor\win32-ia32-57\binding.node
Node Sass could not find a binding for your current environment: Windows 32-bit with Node.js 8.x

Found bindings for the following environments:
  - Windows 32-bit with Node.js 4.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass --force` to build the binding for your current environment.
    at module.exports (C:\...\node_modules\node-sass\lib\binding.js:15:13)
    at Object.<anonymous> (C:\...\node_modules\node-sass\lib\i
ndex.js:14:35)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\...\node_modules\gulp-sass\index
.js:187:21)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\...\gulp\tasks\sass.js:8:10)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)

#### How can the CLI team reproduce the problem?
- I have first install nodist 8.9.4 version.
- After this perform gulp theme:fetch
- When I try to perform the suggested solution "Run `npm rebuild node-sass --force` to build the binding for your current environment.", I have encountered the following error:

C:\...>npm rebuild node-sass --force
npm WARN using --force I sure hope you know what you are doing.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\Nodist\\v\\nodev8.9.4\\node.exe" "C:\\Program Files (x86)\\Nodist\\bin\\node_modules\\npm\\bin\\npm-cli.js" "rebuild" "node-sass" "--force"
npm ERR! node v8.9.4
npm ERR! npm  v3.5.2
npm ERR! code MODULE_NOT_FOUND
npm ERR! Cannot find module 'internal/util/types'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Please include the following file with any support request:
npm ERR! C:\...\npm-debug.log

### supporting information:

 - `npm -v` prints: 3.5.2
 - `node -v` prints: 8.9.4
 - Windows 7 x86

**Comment by legodude17** [comment]
Does this occur on the latest version of npm?

**Comment by momoryoma4488** [comment]
Hi legodude17,
I unfortunately unsure how install the latest npm. The npm version that is showing is 3.5.2.
