### ISSUE TITLE
npm causes broken and unreproducible builds with error "Invalid Version"

### ISSUE THREAD

**Issue by sim642** [npm/npm#21068]
#### I'm opening this issue because:

  - [x] npm is doing something I don't understand.
  - [x] npm is producing incorrect or undesirable behavior.

#### What's going wrong?

Four months ago my CI builds worked fine: https://travis-ci.org/sim642/einstein-js/builds/336699670. Now, these four months later, the same **unchanged** build completely fails to even install the dependencies: https://travis-ci.org/sim642/einstein-js/builds/396387519. The error is
```
npm ERR! Invalid Version: https://registry.npmjs.org/classnames/-/classnames-2.2.5.tgz
```

There's _zero_ difference in `package.json` and `package-lock.json` between the two. Breaking the build is bad and it's especially worse if it's the fault of a major JS ecosystem tool, not the developer.

Locally running `npm ci` has the same issue and the log looks like
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'ci' ]
2 info using npm@6.1.0
3 info using node@v8.11.3
4 verbose npm-session 64effdd5d59a3ea0
5 info prepare initializing installer
6 verbose prepare starting workers
7 verbose prepare installation prefix: /home/simmo/Desktop/einstein-js
8 verbose prepare using package-lock.json
9 verbose checkLock verifying package-lock data
10 verbose teardown shutting down workers.
11 info teardown Done in 0s
12 verbose stack TypeError: Invalid Version: https://registry.npmjs.org/classnames/-/classnames-2.2.5.tgz
12 verbose stack     at new SemVer (/usr/lib/node_modules/npm/node_modules/semver/semver.js:305:11)
12 verbose stack     at Range.test (/usr/lib/node_modules/npm/node_modules/semver/semver.js:1112:15)
12 verbose stack     at Function.satisfies (/usr/lib/node_modules/npm/node_modules/semver/semver.js:1161:16)
12 verbose stack     at Object.keys.forEach.name (/usr/lib/node_modules/npm/node_modules/lock-verify/index.js:39:23)
12 verbose stack     at Array.forEach (<anonymous>)
12 verbose stack     at Promise.all.then.result (/usr/lib/node_modules/npm/node_modules/lock-verify/index.js:25:25)
12 verbose stack     at <anonymous>
13 verbose cwd /home/simmo/Desktop/einstein-js
14 verbose Linux 4.4.0-128-generic
15 verbose argv "/usr/bin/node" "/usr/bin/npm" "ci"
16 verbose node v8.11.3
17 verbose npm  v6.1.0
18 error Invalid Version: https://registry.npmjs.org/classnames/-/classnames-2.2.5.tgz
19 verbose exit [ 1, true ]
```

### Supporting information:

 - `npm -v` prints: 6.1.0
 - `node -v` prints: v10.5.0

#### Related issues
There's very little information about the error but I've managed a couple of very unhelpful issues: https://github.com/gulpjs/gulp/issues/1972, https://github.com/gulpjs/gulp/issues/1967, https://github.com/istanbuljs/nyc/issues/687, https://github.com/npm/npm/issues/7506.

#### Build reproducibility
It's appalling how in the timespan of a couple of months an unmodified project becomes completely unbuildable by npm. npm is supposed to handle dependencies and thus make builds easily reproducible but in this case that's just thrown out of the window as it fails to perform it's main task. As of now, it's unclear how anyone besides me is supposed to be able to build the project at all since npm doesn't seem to be able to do that in a clean CI environment.

#### Package locking
The linked issues above suggest a solution: delete `node_modules` and `package-lock.json`. I want to make it very clear that it's not a _solution_. The whole point of package locking is to perfectly reproduce the entire package tree. Deleting the lockfile makes that pointless as a completely new tree gets initialized with new versions. The reason anyone would have a lockfile in the first place is to avoid exactly that. So deleting it can't be considered a solution at all because without the lockfile I can't guarantee that my project works correctly, I've only done it for the locked versions of packages. Updating them is a separate task which I shouldn't be inadvertently forced to do by npm's bugs.

#### npm 6
As a difference between the four months, there's now npm 6, which could be the issue. Its (childishly written) changelog (https://github.com/npm/npm/releases/tag/v6.0.1) speaks of **"SHRONKWRAPS AND LACKFILES"** (sic!):
> When encountering a https:// URL in our lockfiles that point at our default registry, extract the version and use them as registry dependencies.

_(To be honest, I don't really understand the need to use childish jokes in a major JS ecosystem tool's changelogs. It screams of non-professionalism and makes these things very difficult to search because nobody expects an official report to intentionally contain typos.)_

According to the chongelag npm 6 is supposed to be fixing the very issue I'm having, yet I'm still having the issue and it was introduced by npm 6. So clearly whatever fix is in place isn't doing its job and a lockfile that used to work isn't working at all. So much about lockfile versioning etc, that's supposed to maintain compatibilities.

**Comment by sim642** [comment]
Apparently running `npm install` just to get it to recreate the lockfile and commiting that fixes the issue. Although still, I don't see why the intended automatic process doesn't work to extract versions from URLs to keep compatibility.
