### ISSUE TITLE
This is an error with npm itself. Please report this error at: 

### ISSUE THREAD

**Issue by azizsallam** [npm/npm#21074]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by azizsallam** [comment]
npm ERR! code EINVALIDTYPE                                                                                                                          
npm ERR! typeerror Error: Argument #5: Expected object but got boolean                                                                              
npm ERR! typeerror     at inflatableChild (C:\Program Files\nodejs\node_modules\npm\lib\install\inflate-shrinkwrap.js:70:3)                         
npm ERR! typeerror     at BB.each (C:\Program Files\nodejs\node_modules\npm\lib\install\inflate-shrinkwrap.js:52:12)                                
npm ERR! typeerror     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)                      
npm ERR! typeerror     at Object.gotValue (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\reduce.js:155:18)              
npm ERR! typeerror     at Object.gotAccum (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\reduce.js:144:25)              
npm ERR! typeerror     at Object.tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)               
npm ERR! typeerror     at Promise._settlePromiseFromHandler (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:51
2:31)                                                                                                                                               
npm ERR! typeerror     at Promise._settlePromise (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)      
npm ERR! typeerror     at Promise._settlePromiseCtx (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:606:10)   
npm ERR! typeerror     at Async._drainQueue (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:138:12)             
npm ERR! typeerror     at Async._drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)            
npm ERR! typeerror     at Immediate.Async.drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)    
npm ERR! typeerror     at runCallback (timers.js:810:20)                                                                                            
npm ERR! typeerror     at tryOnImmediate (timers.js:768:5)                                                                                          
npm ERR! typeerror     at processImmediate [as _immediateCallback] (timers.js:745:5)                                                                
npm ERR! typeerror This is an error with npm itself. Please report this error at:                                                                   
npm ERR! typeerror     <https://github.com/npm/npm/issues>                                                                                          
                                                                                                                                                    
npm ERR! A complete log of this run can be found in:                                                                                                
npm ERR!     C:\Users\azizs\AppData\Roaming\npm-cache\_logs\2018-06-26T15_35_17_499Z-debug.log
