### ISSUE TITLE
Unhandled rejection Error: Cannot find module 'stringstream'psIntoIdealTree

### ISSUE THREAD

**Issue by sujxia** [npm/npm#21166]
C:\Users\17910\WebstormProjects\PMP-frontend-master>npm install
Unhandled rejection Error: Cannot find module 'stringstream'psIntoIdealTree
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\17910\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.js:14:20)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\17910\AppData\Roaming\npm\node_modules\npm\node_modules\request\index.js:143:19)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\17910\AppData\Roaming\npm-cache\_logs\2018-07-07T06_37_11_392Z-debug.log

### supporting information:
 - `npm -v` prints:6.1.0
 - `node -v` prints:10.5.0
 - Windows: 17704
[2018-07-07T06_37_11_392Z-debug.log](https://github.com/npm/npm/files/2172508/2018-07-07T06_37_11_392Z-debug.log)

Thank You For Answering.

**Comment by DanielRuf** [comment]
Please try `npm cache clean --force` and `npm i` multiple times.

**Comment by sujxia** [comment]
@DanielRuf But it is also doesn't work and have the same question above, do you have any other solutions? Thank you.
[2018-07-09T01_24_22_094Z-debug.log](https://github.com/npm/npm/files/2174331/2018-07-09T01_24_22_094Z-debug.log)
