### ISSUE TITLE
npm is not working properly how to fix problem

### ISSUE THREAD

**Issue by bhavin333** [npm/npm#21169]
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "bugs" "slacky-" "slack"
npm ERR! node v10.6.0
npm ERR! npm  v3.10.10

npm ERR! error:0906D06C:PEM routines:PEM_read_bio:no start line
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\User\Desktop\mac-chat-api-master\npm-debug.log

**Comment by DanielRuf** [comment]
This seems to be an OpenSSL issue. Can you post the generated logfile?

**Comment by bhavin333** [comment]
when i start npm but mongodb is waiting for connection

**Comment by DanielRuf** [comment]
> C:\Users\User\Desktop\mac-chat-api-master\npm-debug.log

We need this one.

**Comment by bhavin333** [comment]
there is no any npm-debug.log file

**Comment by bhavin333** [comment]
sorry i was find npm-debug.log file

**Comment by bhavin333** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'windows-build-tools' ]
2 info using npm@3.10.10
3 info using node@v10.6.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData windows-build-tools
8 silly fetchNamedPackageData windows-build-tools
9 silly mapToRegistry name windows-build-tools
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'windows-build-tools',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'windows-build-tools',
12 silly mapToRegistry   name: 'windows-build-tools',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/windows-build-tools
14 verbose request uri https://registry.npmjs.org/windows-build-tools
15 verbose request no auth needed
16 info attempt registry request try #1 at 12:36:47 PM
17 verbose request id e80c5ee262b86af5
18 http request GET https://registry.npmjs.org/windows-build-tools
19 info retry will retry, error on last attempt: Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
20 info attempt registry request try #2 at 12:36:57 PM
21 http request GET https://registry.npmjs.org/windows-build-tools
22 info retry will retry, error on last attempt: Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
23 info attempt registry request try #3 at 12:37:57 PM
24 http request GET https://registry.npmjs.org/windows-build-tools
25 silly fetchPackageMetaData Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
25 silly fetchPackageMetaData     at Object.createSecureContext (_tls_common.js:144:17)
25 silly fetchPackageMetaData     at Object.exports.connect (_tls_wrap.js:1119:48)
25 silly fetchPackageMetaData     at Agent.createConnection (https.js:119:22)
25 silly fetchPackageMetaData     at Agent.createSocket (_http_agent.js:226:26)
25 silly fetchPackageMetaData     at Agent.addRequest (_http_agent.js:184:10)
25 silly fetchPackageMetaData     at new ClientRequest (_http_client.js:239:16)
25 silly fetchPackageMetaData     at Object.request (https.js:272:10)
25 silly fetchPackageMetaData     at Request.start (C:\Users\User\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.js:740:32)
25 silly fetchPackageMetaData     at Request.end (C:\Users\User\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.js:1398:10)
25 silly fetchPackageMetaData     at end (C:\Users\User\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.js:567:14)
25 silly fetchPackageMetaData  error for windows-build-tools Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
25 silly fetchPackageMetaData     at Object.createSecureContext (_tls_common.js:144:17)
25 silly fetchPackageMetaData     at Object.exports.connect (_tls_wrap.js:1119:48)
25 silly fetchPackageMetaData     at Agent.createConnection (https.js:119:22)
25 silly fetchPackageMetaData     at Agent.createSocket (_http_agent.js:226:26)
25 silly fetchPackageMetaData     at Agent.addRequest (_http_agent.js:184:10)
25 silly fetchPackageMetaData     at new ClientRequest (_http_client.js:239:16)
25 silly fetchPackageMetaData     at Object.request (https.js:272:10)
25 silly fetchPackageMetaData     at Request.start (C:\Users\User\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.js:740:32)
25 silly fetchPackageMetaData     at Request.end (C:\Users\User\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.js:1398:10)
25 silly fetchPackageMetaData     at end (C:\Users\User\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.js:567:14)
26 silly rollbackFailedOptional Starting
27 silly rollbackFailedOptional Finishing
28 silly runTopLevelLifecycles Finishing
29 silly install printInstalled
30 verbose stack Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
30 verbose stack     at Object.createSecureContext (_tls_common.js:144:17)
30 verbose stack     at Object.exports.connect (_tls_wrap.js:1119:48)
30 verbose stack     at Agent.createConnection (https.js:119:22)
30 verbose stack     at Agent.createSocket (_http_agent.js:226:26)
30 verbose stack     at Agent.addRequest (_http_agent.js:184:10)
30 verbose stack     at new ClientRequest (_http_client.js:239:16)
30 verbose stack     at Object.request (https.js:272:10)
30 verbose stack     at Request.start (C:\Users\User\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.js:740:32)
30 verbose stack     at Request.end (C:\Users\User\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.js:1398:10)
30 verbose stack     at end (C:\Users\User\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.js:567:14)
31 verbose cwd C:\Users\User\Desktop\mac-chat-api-master
32 error Windows_NT 10.0.15063
33 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "windows-build-tools"
34 error node v10.6.0
35 error npm  v3.10.10
36 error error:0906D06C:PEM routines:PEM_read_bio:no start line
37 error If you need help, you may report this error at:
37 error     <https://github.com/npm/npm/issues>
38 verbose exit [ 1, true ]

**Comment by DanielRuf** [comment]
> error npm v3.10.10

Please first try upgrading npm to npm 6 with `npm i -g npm@latest` and test it again.

**Comment by bhavin333** [comment]
there is already updated version of npm

**Comment by bhavin333** [comment]
still there is a same error
