### ISSUE TITLE
Npm install not working via Jenkins - cb() never called 2018

### ISSUE THREAD

**Issue by NxRoot** [npm/npm#21174]
#### I'm opening this issue because:
  - [x] npm is producing incorrect or undesirable behavior.

### THIS ONLY PRODUCES AN ERROR VIA JENKINS (I NEED A FIX)
npm install working on root folder but not on jenkins.
if i delete **node_modules** and **package-lock.json** and try to run npm install command manually in the project folder it works with no problem, but im trying to make it automatic through jenkins and it doesnt seem to be working if i try the same thing.
**WHY? PLEASE HELP!**

### Jenkins Shell Script:
```
#!/bin/sh
node --version
npm --version
npm get registry
echo
echo "Installing Node Modules"
npm install --verbose
```

### Jenkins Output:
```
v10.6.0
6.1.0
https://registry.npmjs.org

Installing Node Modules
npm info it worked if it ends with ok
npm verb cli [ '/var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/oldNode/bin/node',
npm verb cli   '/var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodeInstall/bin/npm',
npm verb cli   'install',
npm verb cli   '--verbose',
npm verb cli   '/var/lib/jenkins/workspace/ClinicSite/default' ]
npm info using npm@6.1.0
npm info using node@v9.2.0
npm verb npm-session 1d6cc049a7891acf
npm info lifecycle clinic-site@0.0.0~preinstall: clinic-site@0.0.0
npm timing stage:loadCurrentTree Completed in 69ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 1ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 2196ms
npm timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 4369ms
npm timing stage:loadIdealTree Completed in 7951ms
npm timing stage:generateActionsToTake Completed in 2516ms
npm verb correctMkdir /var/lib/jenkins/.npm/_locks correctMkdir not in flight; initializing
npm verb lock using /var/lib/jenkins/.npm/_locks/staging-9d6307feb590e326.lock for /var/lib/jenkins/workspace/ClinicSite/default/node_modules/.staging
npm timing audit compress Completed in 39ms
npm info audit Submitting payload of 68494bytes
npm timing audit submit Completed in 20722ms
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 20350ms
npm timing audit body Completed in 2ms
Unhandled rejection Error: invalid config key requested: single
    at pudGet (/var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodeInstall/lib/node_modules/npm/node_modules/figgy-pudding/index.js:31:11)
    at FiggyPudding.get (/var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodeInstall/lib/node_modules/npm/node_modules/figgy-pudding/index.js:13:12)
    at Object.get (/var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodeInstall/lib/node_modules/npm/node_modules/figgy-pudding/index.js:71:16)
    at _parse (/var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodeInstall/lib/node_modules/npm/node_modules/ssri/index.js:138:12)
    at parse (/var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodeInstall/lib/node_modules/npm/node_modules/ssri/index.js:125:12)
    at Object.checkData (/var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodeInstall/lib/node_modules/npm/node_modules/ssri/index.js:216:9)
    at write (/var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodeInstall/lib/node_modules/npm/node_modules/cacache/lib/content/write.js:34:31)
    at putData (/var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodeInstall/lib/node_modules/npm/node_modules/cacache/put.js:25:10)
    at Object.x.put (/var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodeInstall/lib/node_modules/npm/node_modules/cacache/locales/en.js:28:37)
    at readFileAsync.then.data (/var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodeInstall/lib/node_modules/npm/node_modules/pacote/lib/fetchers/file.js:38:28)
    at tryCatcher (/var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodeInstall/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodeInstall/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodeInstall/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodeInstall/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodeInstall/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodeInstall/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:638:18)
npm timing npm Completed in 140915ms
npm ERR! cb() never called!
```

**Comment by NxRoot** [comment]
Downgraded NPM to v5.5.1, now it's working nice to know Npm leaves a bug for a few years and dont care

**Comment by DanielRuf** [comment]
Does 5.7.1 also work or just 5.5.1?
Would be helpful to now in which release it was introduced.

**Comment by NxRoot** [comment]
Ive seen this issue all over the internet nowadays the only fix seems to be  downgrading. I believe this bug is related to npm paths misconfigurations.
Didn't test any other version, but im pretty sure any version below 6.x.x should work.

Notes:
JENKINS WILL NOT USE THE DEFAULT NPM FROM NODEJS JENKINS PLUGIN AUTOMATIC INSTALLATION! IF YOU HAVE ANY OTHER NPM VERSION INSTALLED MANUALLY IT WILL USE THAT ONE.
Specify the path if you want to use the default one. 
Ex:
/var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/myNode/npm install

**Comment by DanielRuf** [comment]
> invalid config key requested: single

This is the issue in your case, the error message at the end is very general.

**Comment by NxRoot** [comment]
Thats also a generic response error, its not in my case specific, everything i have configured is default the error shouldnt show up at all, if you search this npm issue in this github it has been a known bug for a few years, its a fresh and clean jenkins installation and its using default NodeJs and Npm that comes with it, so it cant be my case specific thats for sure.

**Comment by DanielRuf** [comment]
This one comes from figgy-pudding unlike the others.

**Comment by NxRoot** [comment]
Bro, i dont even know what figgy-pudding is, that camed with NPM itself by default, THIS IS NOT A SPECIFIC ERROR! so stop saying its figgy-pudding please, im trying to help, ur only messing peoples head, UR NOT HELPING! If you dont know what ur saying please dont comment about it, thats bad information, thank you

**Comment by DanielRuf** [comment]
Please see https://github.com/npm/npm/issues/21095 and other older issues, the error message is very general, the exact error is still `Unhandled rejection Error: invalid config key requested: single`.

**Comment by DanielRuf** [comment]
Any exception does immediately return and break the further execution and so the callback `cb` is never called (timeout).

**Comment by DanielRuf** [comment]
Please change your title to something like `Unhandled rejection Error: invalid config key requested: single`.

**Comment by NxRoot** [comment]
Thats why im saying IT IS NOT IN MY CASE SPECIFIC! I DID NOT INSTALLED FIGGY-PUDDING I DONT KNOW WHAT THAT IS BUT IT IS NOT ONE OF MY DEPENDENCIES, IT CAMED WITH NPM INSIDE JENKINS FRESH INSTALL, SO IF YOU WISH TO KEEP SAYING THAT JUST INSTALL JENKINS AND NODEJS PLUGIN AND TRY IT FOR YOURSELF, nothing else to say if u cant help, thank you

**Comment by DanielRuf** [comment]
> IT IS NOT IN MY CASE SPECIFIC

It is =)

**Comment by DanielRuf** [comment]
> I DID NOT INSTALLED FIGGY-PUDDING

I just meant that the bug is probably in there, it is part of npm.
Still, the error which causes this is totally different than the others =)

**Comment by NxRoot** [comment]
Bro ur just retarded, i didnt ask for figgy-pudding to be installed, if it is there it shouldnt be, so its general because i didnt installed anything else and it should not happen, so its not a specific thing that i have done, every jenkins instalation with npm breaks the same way, so its not specific, if it was downgrading wouldnt help, get smart bro

**Comment by DanielRuf** [comment]
It is part of npm. I just noticed that there might be the issue / bug.
https://github.com/zkat/figgy-pudding

The error message is still specific as the other issues with the same cb error do not point to figgy-pudding but other causes.

I just try to get down to the rootcause and share the findings.
Everything is ok =)

**Comment by DanielRuf** [comment]
Also it is good to know which release of npm introduced this bug / issue to pinpoint the problematic files (do some diffs and bisecting).

I hope this is understandable.
