### ISSUE TITLE
error:0906D06C:PEM routines:PEM_read_bio:no start line

### ISSUE THREAD

**Issue by RavindraChavan** [npm/npm#21178]
Below npm-debug issue generated. Kinldy help

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'ejs' ]
2 info using npm@3.10.9
3 info using node@v6.9.2
4 verbose config Skipping project config: C:\Users\ravindrac.ttl/.npmrc. (matches userconfig)
5 silly loadCurrentTree Starting
6 silly install loadCurrentTree
7 silly install readLocalPackageData
8 silly fetchPackageMetaData ejs
9 silly fetchNamedPackageData ejs
10 silly mapToRegistry name ejs
11 silly mapToRegistry using default registry
12 silly mapToRegistry registry https://registry.npmjs.org/
13 silly mapToRegistry data Result {
13 silly mapToRegistry   raw: 'ejs',
13 silly mapToRegistry   scope: null,
13 silly mapToRegistry   escapedName: 'ejs',
13 silly mapToRegistry   name: 'ejs',
13 silly mapToRegistry   rawSpec: '',
13 silly mapToRegistry   spec: 'latest',
13 silly mapToRegistry   type: 'tag' }
14 silly mapToRegistry uri https://registry.npmjs.org/ejs
15 verbose request uri https://registry.npmjs.org/ejs
16 verbose request no auth needed
17 info attempt registry request try #1 at 12:10:59 PM
18 verbose request id 13ecb05c074e8e77
19 http request GET https://registry.npmjs.org/ejs
20 info retry will retry, error on last attempt: Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
21 info attempt registry request try #2 at 12:11:10 PM
22 http request GET https://registry.npmjs.org/ejs
23 info retry will retry, error on last attempt: Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
24 info attempt registry request try #3 at 12:12:10 PM
25 http request GET https://registry.npmjs.org/ejs
26 silly fetchPackageMetaData Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
26 silly fetchPackageMetaData     at Error (native)
26 silly fetchPackageMetaData     at Object.createSecureContext (_tls_common.js:90:19)
26 silly fetchPackageMetaData     at Object.exports.connect (_tls_wrap.js:1020:48)
26 silly fetchPackageMetaData     at Agent.createConnection (https.js:82:22)
26 silly fetchPackageMetaData     at Agent.createSocket (_http_agent.js:195:26)
26 silly fetchPackageMetaData     at Agent.addRequest (_http_agent.js:157:10)
26 silly fetchPackageMetaData     at new ClientRequest (_http_client.js:160:16)
26 silly fetchPackageMetaData     at Object.exports.request (http.js:31:10)
26 silly fetchPackageMetaData     at Object.exports.request (https.js:199:15)
26 silly fetchPackageMetaData     at Request.start (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:740:32)
26 silly fetchPackageMetaData  error for ejs Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
26 silly fetchPackageMetaData     at Error (native)
26 silly fetchPackageMetaData     at Object.createSecureContext (_tls_common.js:90:19)
26 silly fetchPackageMetaData     at Object.exports.connect (_tls_wrap.js:1020:48)
26 silly fetchPackageMetaData     at Agent.createConnection (https.js:82:22)
26 silly fetchPackageMetaData     at Agent.createSocket (_http_agent.js:195:26)
26 silly fetchPackageMetaData     at Agent.addRequest (_http_agent.js:157:10)
26 silly fetchPackageMetaData     at new ClientRequest (_http_client.js:160:16)
26 silly fetchPackageMetaData     at Object.exports.request (http.js:31:10)
26 silly fetchPackageMetaData     at Object.exports.request (https.js:199:15)
26 silly fetchPackageMetaData     at Request.start (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:740:32)
27 silly rollbackFailedOptional Starting
28 silly rollbackFailedOptional Finishing
29 silly runTopLevelLifecycles Finishing
30 silly install printInstalled
31 verbose stack Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
31 verbose stack     at Error (native)
31 verbose stack     at Object.createSecureContext (_tls_common.js:90:19)
31 verbose stack     at Object.exports.connect (_tls_wrap.js:1020:48)
31 verbose stack     at Agent.createConnection (https.js:82:22)
31 verbose stack     at Agent.createSocket (_http_agent.js:195:26)
31 verbose stack     at Agent.addRequest (_http_agent.js:157:10)
31 verbose stack     at new ClientRequest (_http_client.js:160:16)
31 verbose stack     at Object.exports.request (http.js:31:10)
31 verbose stack     at Object.exports.request (https.js:199:15)
31 verbose stack     at Request.start (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:740:32)
32 verbose cwd C:\Users\ravindrac.ttl
33 error Windows_NT 10.0.10240
34 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "ejs"
35 error node v6.9.2
36 error npm  v3.10.9
37 error error:0906D06C:PEM routines:PEM_read_bio:no start line
38 error If you need help, you may report this error at:
38 error     <https://github.com/npm/npm/issues>
39 verbose exit [ 1, true ]

**Comment by DanielRuf** [comment]
Please try upgrading node and npm to see if this solves your issue.
npm 3 is not supported anymore.
