### ISSUE TITLE
npm start not working Angular

### ISSUE THREAD

**Issue by hiyamgh** [npm/npm#21189]
When I am putting npm start in VSCode, I get the following error:

`> mean@1.0.0 start C:\Users\User\Desktop\MontHolding\mean
> app.js

npm ERR! file C:\Windows\system32\cmd;C:\Python27.exe
npm ERR! path C:\Windows\system32\cmd;C:\Python27.exe
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn C:\Windows\system32\cmd;C:\Python27.exe
npm ERR! mean@1.0.0 start: `app.js`
npm ERR! spawn C:\Windows\system32\cmd;C:\Python27.exe ENOENT
npm ERR!
npm ERR! Failed at the mean@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2018-07-11T07_06_42_053Z-debug.log`

**This is the log file:**

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@6.1.0
3 info using node@v8.11.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle mean@1.0.0~prestart: mean@1.0.0
6 info lifecycle mean@1.0.0~start: mean@1.0.0
7 verbose lifecycle mean@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle mean@1.0.0~start: PATH: C:\Users\User\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\User\Desktop\MontHolding\mean\node_modules\.bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\User\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Python27\Lib\site-packages\PyQt4;C:\Python33;C:\Python33\Lib\site-packages\PyQt4\pyuic4.bat;C:\Python35\Lib\site-packages\PyQt5;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files\Java\jdk1.8.0_60\bin;C:\Program Files (x86)\Brackets\command;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files\PuTTY;C:\Python27;C:\Program Files\dotnet;C:\Program Files\Microsoft SQL Server\130\Tools\Binn;C:\Program Files\nodejs;C:\Program Files\Git\cmd;C:\Users\User\AppData\Local\.meteor;C:\Python27\C;C:\Program Files\Git\Python33\Lib\site-packages\PyQt4;C:\Program Files\Microsoft VS Code\bin;C:\Users\User\AppData\Roaming\npm
9 verbose lifecycle mean@1.0.0~start: CWD: C:\Users\User\Desktop\MontHolding\mean
10 silly lifecycle mean@1.0.0~start: Args: [ '/d /s /c', 'app.js' ]
11 info lifecycle mean@1.0.0~start: Failed to exec start script
12 silly lifecycle mean@1.0.0~start: Returned: code: -4058  signal: null
13 info lifecycle mean@1.0.0~start: Failed to exec start script
14 verbose stack Error: mean@1.0.0 start: `app.js`
14 verbose stack spawn C:\Windows\system32\cmd;C:\Python27.exe ENOENT
14 verbose stack     at _errnoException (util.js:992:11)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
14 verbose stack     at onErrorNT (internal/child_process.js:372:16)
14 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:138:11)
14 verbose stack     at process._tickCallback (internal/process/next_tick.js:180:9)
15 verbose pkgid mean@1.0.0
16 verbose cwd C:\Users\User\Desktop\MontHolding\mean
17 verbose Windows_NT 6.3.9600
18 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 verbose node v8.11.3
20 verbose npm  v6.1.0
21 error file C:\Windows\system32\cmd;C:\Python27.exe
22 error path C:\Windows\system32\cmd;C:\Python27.exe
23 error code ELIFECYCLE
24 error errno ENOENT
25 error syscall spawn C:\Windows\system32\cmd;C:\Python27.exe
26 error mean@1.0.0 start: `app.js`
26 error spawn C:\Windows\system32\cmd;C:\Python27.exe ENOENT
27 error Failed at the mean@1.0.0 start script.
27 error This is probably not a problem with npm. There is likely additional logging output above.
28 verbose exit [ 1, true ]

Please any help is highly appreciated <3

**Comment by DanielRuf** [comment]
This does not seem to be related to npm. Please try installing `windows-build-tools`.

**Comment by hiyamgh** [comment]
@DanielRuf  Thank you for your reply, but the same error appeared again when I was installing `windows build tools` :/

**Comment by DanielRuf** [comment]
Can you try reinstalling Node.js and npm?
At least it seems your Python setup is broken and the binary can not be found (C:\Python27.exe).

**Comment by hiyamgh** [comment]
I will try to reinstall, but I don't understand why Python is related to this  !!

**Comment by hiyamgh** [comment]
@DanielRuf  I did this, I also added the node.js to `PATH` in `Environment Variables` and rebooted the system, but again I'm still getting the same error

**Comment by kenany** [comment]
Can you try changing your `"start"` script (in your `package.json`) to:

```json
"start": "node app.js"
```

**Comment by hiyamgh** [comment]
@KenanY I did this, but still getting the error.

**Comment by kenany** [comment]
@hiyam97 Can I see the error log after making my suggested change?
