### ISSUE TITLE
Unhandled rejection Error: Command failed: /usr/local/bin/git clone --mirror -q 

### ISSUE THREAD

**Issue by paliwalgaurav** [npm/npm#21192]
Unhandled rejection Error: Command failed: /usr/local/bin/git clone --mirror -q ssh://git@repo_path.git /Users/itstandby/.npm/_cacache/tmp/git-clone-ec4ec630/.git
warning: templates not found /var/folders/bc/j2pcm9kx47v1nn2qn3xsm1_00000gp/T/pacote-git-template-tmp/git-clone-e12f30ab
fatal: unable to open /Users/itstandby/.npm/_cacache/tmp/git-clone-ec4ec630/.git/objects/pack/tmp_pack_YKhaBa: Interrupted system call
fatal: index-pack failed

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:557:12)

Unhandled rejection Error: Command failed: /usr/local/bin/git submodule update -q --init --recursiveryTech/repo_path.git extracted to /Users/itstandby/Documents/client-pane
warning: unable to access '/usr/local/git/etc/gitconfig': Interrupted system call
warning: unable to access '/Users/itstandby/.gitconfig': Interrupted system call
fatal: cannot exec 'git-submodule': Permission denied

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:557:12)

`npm ERR! cb() never called!`

**Comment by DanielRuf** [comment]
Please try `npm cache clean --force`.
