### ISSUE TITLE
Using a foreign character at password borks things up

### ISSUE THREAD

**Issue by bebraw** [npm/npm#2311]
I just noticed that if you put a foreign character to your password (ie. ä or ö) at "adduser", it breaks the login (gives "Error: unauthorized Name or password is incorrect.", full trace below). I had to reset my account, get rid of .npmrc and user "regular" chars at my pw to make my account work. Just thought to let you know.

```
npm WARN Incorrect username or password
npm WARN You can reset your account by visiting:
npm WARN 
npm WARN     http://admin.npmjs.org/reset
npm WARN 

npm ERR! Error: unauthorized Name or password is incorrect.: -/user/org.couchdb.user:<censored>/-rev/1-6bff94ae505c5ec3893476504ca0001f
npm ERR!     at Request._callback (/opt/local/lib/node_modules/npm/lib/utils/npm-registry-client/request.js:181:12)
npm ERR!     at Request.callback (/opt/local/lib/node_modules/npm/node_modules/request/main.js:119:22)
npm ERR!     at Request.<anonymous> (/opt/local/lib/node_modules/npm/node_modules/request/main.js:525:16)
npm ERR!     at Request.emit (events.js:67:17)
npm ERR!     at IncomingMessage.<anonymous> (/opt/local/lib/node_modules/npm/node_modules/request/main.js:484:14)
npm ERR!     at IncomingMessage.emit (events.js:88:20)
npm ERR!     at HTTPParser.onMessageComplete (http.js:137:23)
npm ERR!     at CleartextStream.ondata (http.js:1150:24)
npm ERR!     at CleartextStream._push (tls.js:375:27)
npm ERR!     at SecurePair.cycle (tls.js:734:20)
npm ERR! You may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>
npm ERR! 
npm ERR! System Darwin 11.3.0
npm ERR! command "node" "/opt/local/bin/npm" "adduser"
npm ERR! cwd <censored path>
npm ERR! node -v v0.6.12
npm ERR! npm -v 1.1.4
npm ERR! message unauthorized Name or password is incorrect.: -/user/org.couchdb.user:<censored>/-rev/1-6bff94ae505c5ec3893476504ca0001f
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     <censored path>/npm-debug.log
npm not ok
```

**Comment by smikes** [comment]
I think this should be marked as "bug" and not "support" and possibly a corresponding issue should be created in `npm-registry-client` /cc @iarna (more github weirdage)

**Comment by othiym23** [comment]
I just tested this, and with both the web site and the CLI, I was able to use `äääööö` as a password without problems, both to create new users and to log in. :tada:

Closing as resolved.
