### ISSUE TITLE
Error: tunneling socket could not be established, cause=Parse Error (testacular)

### ISSUE THREAD

**Issue by avgalon** [npm/npm#3039]
Hi,
I just installed node.js and trying to install testacular with no luck.
My company is behind proxy so i set environment variables (HTTP_PROXY & HTTPS_PROXY) on my x64 windows 7.
```
I run the command  'npm install -g testacular' and get this on the log file:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'testacular' ]
2 info using npm@1.1.69
3 info using node@v0.8.16
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 verbose read json C:\Users\310090759\AppData\Roaming\npm\package.json
6 verbose read json C:\Users\310090759\AppData\Roaming\npm\package.json
7 verbose cache add [ 'testacular', null ]
8 silly cache add name=undefined spec="testacular" args=["testacular",null]
9 verbose parsed url { pathname: 'testacular',
9 verbose parsed url   path: 'testacular',
9 verbose parsed url   href: 'testacular' }
10 silly lockFile 88a8e36a-testacular testacular
11 verbose lock testacular C:\Users\310090759\AppData\Roaming\npm-cache\88a8e36a-testacular.lock
12 silly lockFile 88a8e36a-testacular testacular
13 verbose addNamed [ 'testacular', '' ]
14 verbose addNamed [ null, '' ]
15 silly lockFile d1a2783a-testacular testacular@
16 verbose lock testacular@ C:\Users\310090759\AppData\Roaming\npm-cache\d1a2783a-testacular.lock
17 silly addNameRange { name: 'testacular', range: '', hasData: false }
18 verbose url raw testacular
19 verbose url resolving [ 'https://registry.npmjs.org/', './testacular' ]
20 verbose url resolved https://registry.npmjs.org/testacular
21 info trying registry request attempt 1 at 18:41:11
22 http GET https://registry.npmjs.org/testacular
23 info retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=Parse Error
24 info trying registry request attempt 2 at 18:41:21
25 http GET https://registry.npmjs.org/testacular
26 info retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=Parse Error
27 info trying registry request attempt 3 at 18:42:22
28 http GET https://registry.npmjs.org/testacular
29 silly lockFile d1a2783a-testacular testacular@
30 error Error: tunneling socket could not be established, cause=Parse Error
30 error     at ClientRequest.onError (C:\Program Files\nodejs\node_modules\npm\node_modules\request\tunnel.js:161:17)
30 error     at ClientRequest.g (events.js:192:14)
30 error     at ClientRequest.EventEmitter.emit (events.js:96:17)
30 error     at Socket.socketErrorListener (http.js:1331:9)
30 error     at Socket.EventEmitter.emit (events.js:96:17)
30 error     at Socket._destroy.self.errorEmitted (net.js:329:14)
30 error     at process.startup.processNextTick.process._tickCallback (node.js:244:9)
31 error If you need help, you may report this log at:
31 error     <http://github.com/isaacs/npm/issues>
31 error or email it to:
31 error     <npm-@googlegroups.com>
32 error System Windows_NT 6.1.7601
33 error command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "testacular"
34 error cwd C:\Users\310090759
35 error node -v v0.8.16
36 error npm -v 1.1.69
37 error code ECONNRESET
38 verbose exit [ 1, true ]
```
Please help...
I could not find an answer by googling

Thanks

**Comment by smikes** [comment]
Is this still a problem for you?

If so, can you try updating `node` and `npm` to the latest versions and then exporting your Windows proxy settings as described here: https://github.com/npm/npm/issues/7156

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.1.69. Can you try updating your npm installation?

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as abandoned.
