### ISSUE TITLE
Shrinkwrap with private repo fails to install

### ISSUE THREAD

**Issue by davidcl64** [npm/npm#3522]
When attempting to install based off a shrinkwrapped package that has dependencies on a private repo, I'm consistently getting: ERROR: 404 Not Found

package.json:

```
"dependencies": {
  ...,
  "project": "git+https://un:pw@github.com/company/project.git#v0.2.5",
  ...
}
```

npm-shrinkwrap.json (note: commander is also coming from the public side of the company repo...):

```
"project": {
  "version": "0.2.5",
  "from": "project@git+https://un:pw@github.com/company/project.git#v0.2.5",
  "resolved": "https://un:pw@github.com/company/project.git#9681542bd8673be6873fffb435835e556c994f7b",
  "dependencies": {
    "restler": {
      "version": "2.0.1",
      "from": "restler@~2.0.1"
    },
    "commander": {
      "version": "1.1.1",
      "from": "commander@git://github.com/company/commander.js.git",
      "resolved": "git://github.com/company/commander.js.git#db2c69e353cd80a15f385184572061ad126db43f",
      "dependencies": {
        "keypress": {
          "version": "0.1.0",
          "from": "keypress@0.1.x"
        }
      }
    }
  }
},
```

Output:

```
....
npm http GET https://un:pw@github.com/company/project.git#9681542bd8673be6873fffb435835e556c994f7b
....
npm http 404 https://un:pw@github.com/company/project.git#9681542bd8673be6873fffb435835e556c994f7b
npm ERR! fetch failed https://un:pw@github.com/company/project.git#9681542bd8673be6873fffb435835e556c994f7b
npm ERR! Error: 404 Not Found
npm ERR!     at WriteStream.<anonymous> (/opt/boxen/nodenv/versions/v0.10.10/lib/node_modules/npm/lib/utils/fetch.js:57:12)
npm ERR!     at WriteStream.EventEmitter.emit (events.js:117:20)
npm ERR!     at fs.js:1596:14
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 12.3.0
npm ERR! command "/opt/boxen/nodenv/versions/v0.10.10/bin/node" "/opt/boxen/nodenv/versions/v0.10.10/bin/npm" "install" "."
npm ERR! cwd /Users/dave/test
npm ERR! node -v v0.10.10
npm ERR! npm -v 1.2.25
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/dave/test/npm-debug.log
npm ERR! not ok code 0
```

Looking through the detailed logs the url is referenced as:

```
37 verbose cache add [ 'project@https://un:pw@github.com/company/project.git#9681542bd8673be6873fffb435835e556c994f7b',
37 verbose cache add   null ]
38 verbose cache add name=undefined spec="project@https://un:pw@github.com/company/project.git#9681542bd8673be6873fffb435835e556c994f7b" args=["project@https://un:pw@github.com/company/project.git#9681542bd8673be6873fffb435835e556c994f7b",null]
```

without `git+` at the front of the url - perhaps related?

**Comment by hayesmaker** [comment]
wow 3 years now... good work

**Comment by carols10cents** [comment]
That's unnecessary, @hayesmaker .
