### ISSUE TITLE
 Error: tunneling socket could not be established, cause=Parse Error

### ISSUE THREAD

**Issue by WaseemCake** [npm/npm#3601]
Hi Issac,

Am unable to resolve this issue can you please hell me on this ?
```
C:\Users\mwaseem\Documents\codeNode\sample login>npm install jade
npm WARN package.json LoginSystem@0.0.1 No README.md file found!
npm http GET https://registry.npmjs.org/jade
npm http GET https://registry.npmjs.org/jade
npm http GET https://registry.npmjs.org/jade
npm ERR! Error: tunneling socket could not be established, cause=Parse Error
npm ERR!     at ClientRequest.onError (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\tunnel.js:161:17)
npm ERR!     at ClientRequest.g (events.js:193:14)
npm ERR!     at ClientRequest.EventEmitter.emit (events.js:93:17)
npm ERR!     at Socket.socketErrorListener (http.js:1331:9)
npm ERR!     at Socket.EventEmitter.emit (events.js:93:17)
npm ERR!     at Socket._destroy.self.errorEmitted (net.js:328:14)
npm ERR!     at process.startup.processNextTick.process._tickCallback (node.js:244:9)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>
```

**Comment by smikes** [comment]
Is this still a problem for you?

Config settings can be in several places: both in a local file and in the global config.  To see the full configuration including all the sources for various settings and their overrides, run

```
npm config ls -l
```

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since June 2013. Can you try updating your npm installation?

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as resovled / abandoned.

**Comment by thelonglqd** [comment]
I can not install electron with the lgo verbose of npm below:
```
> electron-prebuilt@1.1.0 postinstall /home/101LongNTP/.nvm/versions/node/v5.10.1/lib/node_modules/electron-prebuilt
> node install.js
Downloading electron-v1.1.0-linux-x64.zip
Error: tunneling socket could not be established, cause=Parse Error
/home/101LongNTP/.nvm/versions/node/v5.10.1/lib/node_modules/electron-prebuilt/install.js:22
  throw err
  ^

Error: tunneling socket could not be established, cause=Parse Error
    at ClientRequest.onError (/home/101LongNTP/.nvm/versions/node/v5.10.1/lib/node_modules/electron-prebuilt/node_modules/tunnel-agent/index.js:176:17)
    at ClientRequest.g (events.js:273:16)
    at emitOne (events.js:90:13)
    at ClientRequest.emit (events.js:182:7)
    at Socket.socketOnData (_http_client.js:364:9)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:529:20)
```

I did configure the proxy, here my configuration in .npmrc file

```
http-proxy=http://username:password@proxy:8080
https-proxy=http://username:password@proxy:8080
registry=https://registry.npmjs.org/
```

I took some research but the solution is just configuration of proxy but I did that.
Please help if you know any other cause of this issue.

Many thanks in advance.
