### ISSUE TITLE
NPM install may fail silently on OS/X if XCode is updated

### ISSUE THREAD

**Issue by tikonen** [npm/npm#3932]
Not sure if this is bug in the package.json, npm or gyp but here goes.

I updated OS/X Xcode to latest version and tried to install mongodb driver with native option

```
$ npm install mongodb --native
```

This seems to be success

```
...
npm http GET https://registry.npmjs.org/bson/0.2.2
npm http GET https://registry.npmjs.org/kerberos/0.0.3
npm http 304 https://registry.npmjs.org/bson/0.2.2
npm http 304 https://registry.npmjs.org/kerberos/0.0.3

> kerberos@0.0.3 install /Users/teemuikonen/node_modules/mongodb/node_modules/kerberos
> (node-gyp rebuild 2> builderror.log) || (exit 0)

> bson@0.2.2 install /Users/teemuikonen/node_modules/mongodb/node_modules/bson
> (node-gyp rebuild 2> builderror.log) || (exit 0)

mongodb@1.3.19 node_modules/mongodb
├── kerberos@0.0.3
└── bson@0.2.2
```

However, when checking builderror.log for bson, it says

```
Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.

gyp: Error 69 running xcodebuild
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:424:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Darwin 12.5.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/teemuikonen/node_modules/mongodb/node_modules/bson
gyp ERR! node -v v0.10.18
gyp ERR! node-gyp -v v0.10.9
gyp ERR! not ok
```

So my problem was that OS/X xcodebuild has to be run as sudo by user from command line before it can be used. 

Generally speaking build failures should be reported to the user somehow when he executes npm install.

**Comment by OmgImAlexis** [comment]
Since `npm v3` this has been displaying the error correctly and now exits instead of silently failing.
