### ISSUE TITLE
Trying to install Node.js module ldapauth on Windows 7 64 bit

### ISSUE THREAD

**Issue by osenz** [npm/npm#4025]
I have tried in vane trying to install the ldapauth module on my machine. I have played with several different versions of Python both 32 bit and 64 bit with versions being below 3.0. I installed/uninstalled the Windows 7 SDK both 32 and 64 bit version. I have several fully installed versions of Visual Studio 2008, 2010, and 2013 residing on my machine at the time. I have read all the posts and cannot figure out why I am unable to install this module or any module that requires node-gyp and Python for installation. 

Here is my screen dump:
```
C:\EPC>npm install ldapauth
npm WARN package.json webapp@0.0.1 No description
npm WARN package.json webapp@0.0.1 No repository field.
npm WARN package.json webapp@0.0.1 No README data
npm http GET https://registry.npmjs.org/ldapauth
npm http 304 https://registry.npmjs.org/ldapauth
npm http GET https://registry.npmjs.org/ldapjs/0.6.3
npm http GET https://registry.npmjs.org/lru-cache/2.0.4
npm http GET https://registry.npmjs.org/bcrypt/0.7.5
npm http 304 https://registry.npmjs.org/ldapjs/0.6.3
npm http 304 https://registry.npmjs.org/lru-cache/2.0.4
npm http 304 https://registry.npmjs.org/bcrypt/0.7.5
npm http GET https://registry.npmjs.org/bindings/1.0.0
npm http GET https://registry.npmjs.org/asn1/0.1.11
npm http GET https://registry.npmjs.org/assert-plus/0.1.2
npm http GET https://registry.npmjs.org/buffertools/1.1.0
npm http GET https://registry.npmjs.org/dtrace-provider/0.2.8
npm http GET https://registry.npmjs.org/bunyan/0.21.1
npm http GET https://registry.npmjs.org/nopt/2.1.1
npm http GET https://registry.npmjs.org/pooling/0.4.4
npm http 304 https://registry.npmjs.org/bindings/1.0.0
npm http 304 https://registry.npmjs.org/bunyan/0.21.1

> bcrypt@0.7.5 install C:\EPC\node_modules\ldapauth\node_modules\bcrypt> node-gyp rebuild

npm http 304 https://registry.npmjs.org/nopt/2.1.1

C:\EPC\node_modules\ldapauth\node_modules\bcrypt>node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
npm http 304 https://registry.npmjs.org/assert-plus/0.1.2
npm http 304 https://registry.npmjs.org/asn1/0.1.11
npm http 304 https://registry.npmjs.org/buffertools/1.1.0
npm http 304 https://registry.npmjs.org/pooling/0.4.4
npm http 304 https://registry.npmjs.org/dtrace-provider/0.2.8
npm http GET https://registry.npmjs.org/once/1.1.1
npm http GET https://registry.npmjs.org/vasync/1.3.3
npm http GET https://registry.npmjs.org/abbrev

> buffertools@1.1.0 install C:\EPC\node_modules\ldapauth\node_modules\ldapjs\node_modules\buffertools> node-gyp rebuild


C:\EPC\node_modules\ldapauth\node_modules\ldapjs\node_modules\buffertools>node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
npm http 304 https://registry.npmjs.org/once/1.1.1
npm http 304 https://registry.npmjs.org/abbrev
npm http 304 https://registry.npmjs.org/vasync/1.3.3

> dtrace-provider@0.2.8 install C:\Users\OSenz000\Documents\Comcast\EPC APP\tacoe\EPC\node_modules\ldapauth\node_modules\ldapjs\node_modules\dtrace-provider> node-gyp rebuild


C:\EPC\node_modules\ldapauth\node_modules\ldapjs\node_modules\dtrace-provider>node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
npm http GET https://registry.npmjs.org/mv/0.0.5
npm http GET https://registry.npmjs.org/jsprim/0.3.0
npm http GET https://registry.npmjs.org/verror/1.1.0
npm http 304 https://registry.npmjs.org/verror/1.1.0
npm http 304 https://registry.npmjs.org/mv/0.0.5
npm http 304 https://registry.npmjs.org/jsprim/0.3.0
Traceback (most recent call last):
  File "C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\gyp\gyp", line 15, in <module>    import gyp
  File "C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 8, in <module>    import gyp.input
  File "C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 15, in <module>    import multiprocessing
  File "C:\Python27\lib\multiprocessing\__init__.py", line 84, in <module>    import _multiprocessing
ImportError: DLL load failed: The specified module could not be found.
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:424:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\EPC\node_modules\ldapauth\node_modules\bcrypt
gyp ERR! node -v v0.10.21
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok
Traceback (most recent call last):
  File "C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\gyp\gyp", line 15, in <module>    import gyp
  File "C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 8, in <module>    import gyp.input
  File "C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 15, in <module>    import multiprocessing
  File "C:\Python27\lib\multiprocessing\__init__.py", line 84, in <module>    import _multiprocessing
ImportError: DLL load failed: The specified module could not be found.
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:424:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\EPC\node_modules\ldapauth\node_modules\ldapjs\node_modules\buffertools
gyp ERR! node -v v0.10.21
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok
npm ERR! Error: ENOENT, lstat 'C:\Users\OSenz000\Documents\Comcast\EPC APP\tacoe\EPC\node_modules\ldapauth\node_modules\ldapjs\node_modules\pooling\node_modules\vasync\node_modules\jsprim\test\validate.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "ldapauth"
npm ERR! cwd C:\EPC
npm ERR! node -v v0.10.21
npm ERR! npm -v 1.3.11
npm ERR! path C:\EPC\node_modules\ldapauth\node_modules\ldapjs\node_modules\pooling\node_modules\vasync\node_modules\jsprim\test\validate.js
npm ERR! fstream_path C:\EPC\node_modules\ldapauth\node_modules\ldapjs\node_modules\pooling\node_modules\vasync\node_modules\jsprim\test\validate.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\fstream\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! error rolling back Error: ENOTEMPTY, rmdir 'C:\Users\OSenz000\Documents\Comcast\EPC APP\tacoe\EPC\node_modules\ldapauth\node_modules\ldapjs\node_modules\pooling\node_modules\vasync\node_modules\verror'
npm ERR! error rolling back  ldapauth@2.2.4 { [Error: ENOTEMPTY, rmdir 'C:\Users\OSenz000\Documents\Comcast\EPC APP\tacoe\EPC\node_modules\ldapauth\node_modules\ldapjs\node_modules\pooling\node_modules\vasync\node_modules\verror']
npm ERR! error rolling back   errno: 53,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   path: 'C:\\Users\\OSenz000\\Documents\\Comcast\\EPC APP\\tacoe\\EPC\\node_modules\\ldapauth\\node_modules\\ldapjs\\node_modules\\pooling\\node_modules\\vasync\\node_modules\\verror' }
npm ERR! weird error 1
Traceback (most recent call last):
  File "C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\gyp\gyp", line 15, in <module>    import gyp
  File "C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 8, in <module>    import gyp.input
  File "C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 15, in <module>    import multiprocessing
  File "C:\Python27\lib\multiprocessing\__init__.py", line 84, in <module>    import _multiprocessingImportError: DLL load failed: The specified module could not be found.
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:424:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\EPC\node_modules\ldapauth\node_modules\ldapjs\node_modules\dtrace-provider
gyp ERR! node -v v0.10.21
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\EPC\npm-debug.log

npm ERR! not ok code 0

C:\EPC>
```

**Comment by othiym23** [comment]
Closing as abandoned.
