### ISSUE TITLE
npm install socket.io fails

### ISSUE THREAD

**Issue by azinyama** [npm/npm#4070]
Good day!!! I'm trying to install socket.io on my beagleboard using GateOne...
I'm getting the error message below. Any help resolving this would be greatly appreciated.

```
info it worked if ends with ok
verbose cli [ 'user/bin/node', '/usr/bin/npm', 'install', 'socket.io' ]
info using npm@1.2.14
info using node@v0.8.22
verbose read json /var/lib/cloud9/package.json
verbose read json /var/lib/cloud9/package.json
verbose cache add [ 'socket.io', null ]
verbose cache add name=undefined spec="socket.io" args=["socket.io",null]
verbose parsed url { pathname: 'socket.io', path: 'socket.io', href: 'socket.io' }
silly lockFile 71475bfd-socket-io socket.io
verbose lock socket.io /home/root/.npm/71475bfd-socket-io.lock
silly lockFile 71475bfd-socket-io socket.io
silly lockFile 71475bfd-socket-io socket.io
verbose addNamed [ 'socket.io', '' ]
verbose addNamed [ null, '' ]
silly lockfile c03de861-socket-io socket.io@
verbose lock socket.io@ /home/root/.npm/c03de861-socket-io.lock
silly addNameRange { name: 'socket.io', range: '', hasData: false }
verbose url raw socket.io
verbose url resolving [ 'https://registry.npmjs.org/', './socket.io' ]
verbose url resolved https://registry.npmjs.org/socket.io
info trying registry request attempt 1 at 03:47:20
http GET https://registry.npmjs.org/socket.io
info retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND
info trying registry request attempt 2 at 03:47:31
http GET https://registry.npmjs.org/socket.io
info retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND
info trying registry request attempt 3 at 03:48:31
http GET https://registry.npmjs.org/socket.io
silly lockFile c03de861-socket-io socket.io@
silly lockFile c03de861-socket-io socket.io@
error Error: getaddrinfo ENTFOUND
error 	at errnoException (dns.js:37:11)
error 	at Object.onanswer [as oncomplete] (dns.js:124:16)
error If you need help, you may report this log at:
error 	<http://github.com/isaacs/npm/issues>;
error or email it to:
error 	<npm-@googlegroups.com>
error System Linux 3.8.13
error command "/usr/bin/node" "/usr/bin/npm" "install" "socket.io"
error cwd /var/lib/cloud9
error node -v v0.8.22
error npm -v 1.2.14
error syscall getaddrinfo
error code ENOTFOUND
error errno ENFOUND
verbose exit [ 1, true ]
```

**Comment by smikes** [comment]
Is this still a problem for you?

If it's a DNS problem, you will need to make sure your beagleboard has an appropriate `resolv.conf` file -- see https://groups.google.com/forum/#!topic/beagleboard/6VCaDabyowk

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as resolved / abandoned.
