### ISSUE TITLE
code E404

### ISSUE THREAD

**Issue by xoxotw** [npm/npm#4072]
Hi !  Im trying to run:    npm install http

I get follow Terminal Output,  and Log file... : 

Whats my problem ?

```
npm http GET http://85.10.209.91/http
npm http 404 http://85.10.209.91/http
npm ERR! registry error parsing json
npm ERR! SyntaxError: Unexpected token <
npm ERR!     at Object.parse (native)
npm ERR!     at RegClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:238:23)
npm ERR!     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:129:22)
npm ERR!     at Request.EventEmitter.emit (events.js:106:17)
npm ERR!     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:873:14)
npm ERR!     at Request.EventEmitter.emit (events.js:125:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:824:12)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:125:20)
npm ERR!     at _stream_readable.js:896:16
npm ERR!     at process._tickCallback (node.js:316:11)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.2.0-23-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "http"
npm ERR! cwd /home/xoxotw/Programming/nodeJS/webServer
npm ERR! node -v v0.11.8-pre
npm ERR! npm -v 1.3.13
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/xoxotw/Programming/nodeJS/webServer/npm-debug.log
npm ERR! not ok code 0


0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'install', 'http' ]
2 info using npm@1.3.13
3 info using node@v0.11.8-pre
4 verbose cache add [ 'http', null ]
5 verbose cache add name=undefined spec="http" args=["http",null]
6 verbose parsed url { protocol: null,
6 verbose parsed url   slashes: null,
6 verbose parsed url   auth: null,
6 verbose parsed url   host: null,
6 verbose parsed url   port: null,
6 verbose parsed url   hostname: null,
6 verbose parsed url   hash: null,
6 verbose parsed url   search: null,
6 verbose parsed url   query: null,
6 verbose parsed url   pathname: 'http',
6 verbose parsed url   path: 'http',
6 verbose parsed url   href: 'http' }
7 silly lockFile 77b5f8e3-http http
8 verbose lock http /home/xoxotw/.npm/77b5f8e3-http.lock
9 silly lockFile 77b5f8e3-http http
10 silly lockFile 77b5f8e3-http http
11 verbose addNamed [ 'http', '' ]
12 verbose addNamed [ null, '*' ]
13 silly lockFile c1086ff9-http http@
14 verbose lock http@ /home/xoxotw/.npm/c1086ff9-http.lock
15 silly addNameRange { name: 'http', range: '*', hasData: false }
16 verbose url raw http
17 verbose url resolving [ 'http://85.10.209.91/', './http' ]
18 verbose url resolved http://85.10.209.91/http
19 info trying registry request attempt 1 at 17:31:24
20 http GET http://85.10.209.91/http
21 http 404 http://85.10.209.91/http
22 verbose bad json <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
22 verbose bad json <html><head>
22 verbose bad json <title>404 Not Found</title>
22 verbose bad json </head><body>
22 verbose bad json <h1>Not Found</h1>
22 verbose bad json <p>The requested URL /http was not found on this server.</p>
22 verbose bad json <hr>
22 verbose bad json <address>Apache/2.2.14 (Ubuntu) Server at 85.10.209.91 Port 80</address>
22 verbose bad json </body></html>
23 error registry error parsing json
24 silly registry.get cb [ 404,
24 silly registry.get   { date: 'Fri, 01 Nov 2013 16:31:24 GMT',
24 silly registry.get     server: 'Apache/2.2.14 (Ubuntu)',
24 silly registry.get     vary: 'Accept-Encoding',
24 silly registry.get     'content-length': '280',
24 silly registry.get     connection: 'close',
24 silly registry.get     'content-type': 'text/html; charset=iso-8859-1' } ]
25 silly lockFile c1086ff9-http http@
26 silly lockFile c1086ff9-http http@
27 error SyntaxError: Unexpected token <
27 error     at Object.parse (native)
27 error     at RegClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:238:23)
27 error     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:129:22)
27 error     at Request.EventEmitter.emit (events.js:106:17)
27 error     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:873:14)
27 error     at Request.EventEmitter.emit (events.js:125:20)
27 error     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:824:12)
27 error     at IncomingMessage.EventEmitter.emit (events.js:125:20)
27 error     at _stream_readable.js:896:16
27 error     at process._tickCallback (node.js:316:11)
28 error If you need help, you may report this log at:
28 error     <http://github.com/isaacs/npm/issues>
28 error or email it to:
28 error     <npm-@googlegroups.com>
29 error System Linux 3.2.0-23-generic
30 error command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "http"
31 error cwd /home/xoxotw/Programming/nodeJS/webServer
32 error node -v v0.11.8-pre
33 error npm -v 1.3.13
34 verbose exit [ 1, true ]

```

**Comment by othiym23** [comment]
Closing as abandoned.
