### ISSUE TITLE
npm adduser: Error: conflict Document update conflict

### ISSUE THREAD

**Issue by johnhunter** [npm/npm#4092]
### Steps to reproduce

- on a  windows machine I have not published from
- `npm adduser` with incorrect password
- reset password on admin site
- `npm adduser` with new password

### Actual result

Error with the following response

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'adduser' ]
2 info using npm@1.3.11
3 info using node@v0.10.20
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 verbose adduser before first PUT { name: 'johnhunter',
5 verbose adduser   salt: 'XXXXX',
5 verbose adduser   password_sha: 'XXXXX',
5 verbose adduser   email: '<email>',
5 verbose adduser   _id: 'org.couchdb.user:johnhunter',
5 verbose adduser   type: 'user',
5 verbose adduser   roles: [],
5 verbose adduser   date: '2013-11-05T13:35:06.986Z' }
6 verbose url raw /-/user/org.couchdb.user:johnhunter
7 verbose url resolving [ 'https://registry.npmjs.org/',
7 verbose url resolving   './-/user/org.couchdb.user:johnhunter' ]
8 verbose url resolved https://registry.npmjs.org/-/user/org.couchdb.user:johnhunter
9 info trying registry request attempt 1 at 13:35:06
10 http PUT https://registry.npmjs.org/-/user/org.couchdb.user:johnhunter
11 http 409 https://registry.npmjs.org/-/user/org.couchdb.user:johnhunter
12 verbose adduser update existing user
13 verbose url raw /-/user/org.couchdb.user:johnhunter
14 verbose url resolving [ 'https://registry.npmjs.org/',
14 verbose url resolving   './-/user/org.couchdb.user:johnhunter' ]
15 verbose url resolved https://registry.npmjs.org/-/user/org.couchdb.user:johnhunter
16 info trying registry request attempt 1 at 13:35:08
17 http GET https://registry.npmjs.org/-/user/org.couchdb.user:johnhunter
18 http 200 https://registry.npmjs.org/-/user/org.couchdb.user:johnhunter
19 verbose adduser userobj { name: 'johnhunter',
19 verbose adduser   salt: 'XXXXX',
19 verbose adduser   password_sha: 'XXXXX',
19 verbose adduser   email: '<email>',
19 verbose adduser   _id: 'org.couchdb.user:johnhunter',
19 verbose adduser   type: 'user',
19 verbose adduser   roles: [],
19 verbose adduser   date: '2013-11-05T13:35:06.986Z' }
20 verbose url raw /-/user/org.couchdb.user:johnhunter/-rev/2-66d2703248590980b2fcd732e560af70
21 verbose url resolving [ 'https://registry.npmjs.org/',
21 verbose url resolving   './-/user/org.couchdb.user:johnhunter/-rev/2-66d2703248590980b2fcd732e560af70' ]
22 verbose url resolved https://registry.npmjs.org/-/user/org.couchdb.user:johnhunter/-rev/2-66d2703248590980b2fcd732e560af70
23 info trying registry request attempt 1 at 13:35:09
24 http PUT https://registry.npmjs.org/-/user/org.couchdb.user:johnhunter/-rev/2-66d2703248590980b2fcd732e560af70
25 http 409 https://registry.npmjs.org/-/user/org.couchdb.user:johnhunter/-rev/2-66d2703248590980b2fcd732e560af70
26 verbose adduser back [ [Error: conflict Document update conflict.: -/user/org.couchdb.user:johnhunter/-rev/2-66d2703248590980b2fcd732e560af70],
26 verbose adduser   { error: 'conflict', reason: 'Document update conflict.' },
26 verbose adduser   '{"error":"conflict","reason":"Document update conflict."}' ]
27 error Error: conflict Document update conflict.: -/user/org.couchdb.user:johnhunter/-rev/2-66d2703248590980b2fcd732e560af70
27 error     at RegClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:272:14)
27 error     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:129:22)
27 error     at Request.EventEmitter.emit (events.js:98:17)
27 error     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:873:14)
27 error     at Request.EventEmitter.emit (events.js:117:20)
27 error     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:824:12)
27 error     at IncomingMessage.EventEmitter.emit (events.js:117:20)
27 error     at _stream_readable.js:920:16
27 error     at process._tickCallback (node.js:415:13)
```

**Comment by othiym23** [comment]
Closing as abandoned / resolved.
