### ISSUE TITLE
NPM login document update conflict

### ISSUE THREAD

**Issue by toddself** [npm/npm#4093]
Trying to login:

```
npm http PUT https://registry.npmjs.org/-/user/org.couchdb.user:toddself
npm http 409 https://registry.npmjs.org/-/user/org.couchdb.user:toddself
npm http GET https://registry.npmjs.org/-/user/org.couchdb.user:toddself
npm http 200 https://registry.npmjs.org/-/user/org.couchdb.user:toddself
npm http PUT https://registry.npmjs.org/-/user/org.couchdb.user:toddself/-rev/12-3bb9d772447d12aae5223425144341f6
npm http 409 https://registry.npmjs.org/-/user/org.couchdb.user:toddself/-rev/12-3bb9d772447d12aae5223425144341f6
npm ERR! Error: conflict Document update conflict.: -/user/org.couchdb.user:toddself/-rev/12-3bb9d772447d12aae5223425144341f6
npm ERR!     at RegClient.<anonymous> (/usr/local/Cellar/node/0.10.21/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:272:14)
npm ERR!     at Request.self.callback (/usr/local/Cellar/node/0.10.21/lib/node_modules/npm/node_modules/request/request.js:129:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/local/Cellar/node/0.10.21/lib/node_modules/npm/node_modules/request/request.js:873:14)
npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/local/Cellar/node/0.10.21/lib/node_modules/npm/node_modules/request/request.js:824:12)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 13.0.0
npm ERR! command "/usr/local/Cellar/node/0.10.21/bin/node" "/usr/local/bin/npm" "login"
npm ERR! cwd /Users/todd/src/conde/cn-cookie
npm ERR! node -v v0.10.21
npm ERR! npm -v 1.3.11
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/todd/src/conde/cn-cookie/npm-debug.log
npm ERR! not ok code 0
```

**Comment by smikes** [comment]
Is this still a problem for you?

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by toddself** [comment]
No this has been totally resolved for like a year now ;)
