### ISSUE TITLE
Module 'restify' available version is inconsistent (v2.6.0 vs v2.6.1 claimed)

### ISSUE THREAD

**Issue by crgmrgn** [npm/npm#4125]
Did an npm update after upgrading to node v0.10.22 (npm v1.3.14) on OSX and npm threw a chunk of errors and stopped, seems to be due to inconsistency of available versus actual releases of the restify module, see below …

```
[~] > npm update restify
npm http GET https://registry.npmjs.org/restify/latest
npm http 304 https://registry.npmjs.org/restify/latest
npm http GET https://registry.npmjs.org/restify/2.6.1
npm http 404 https://registry.npmjs.org/restify/2.6.1
npm ERR! Error: version not found: 2.6.1 : restify/2.6.1
npm ERR!     at RegClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:272:14)
npm ERR!     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:129:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:873:14)
npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:824:12)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 13.0.0
npm ERR! command "node" "/usr/local/bin/npm" "update" "restify"
npm ERR! cwd /Users/craig
npm ERR! node -v v0.10.22
npm ERR! npm -v 1.3.14
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/craig/npm-debug.log
npm ERR! not ok code 0
```

`npm info` reports v2.6.0 as latest release, so looks like inconsistency somewhere in the npm db.

**Comment by smikes** [comment]
Is this still a problem for you?

It looks like this might have been a bad replication in the registry, possibly related to non-atomic publishing.  Both have since been addressed: the registry runs better and `npm publish` is atomic.

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as abandoned.
