### ISSUE TITLE
Notice: /Stage[main]/Grunt/Exec[grunt-htmlcompressor]/returns: npm ERR! fetch failed https://registry.npmjs.org/grunt-htmlcompressor/-/grunt-htmlcompressor-0.1.9.tgz

### ISSUE THREAD

**Issue by kamal2222ahmed** [npm/npm#4127]
```
Debug: Exec[grunt-htmlcompressor](provider=posix): Executing 'npm install grunt-htmlcompressor'
Debug: Executing 'npm install grunt-htmlcompressor'
Notice: /Stage[main]/Grunt/Exec[grunt-htmlcompressor]/returns: npm http GET https://registry.npmjs.org/grunt-htmlcompressor
Notice: /Stage[main]/Grunt/Exec[grunt-htmlcompressor]/returns: npm http 200 https://registry.npmjs.org/grunt-htmlcompressor
Notice: /Stage[main]/Grunt/Exec[grunt-htmlcompressor]/returns: npm http GET https://registry.npmjs.org/grunt-htmlcompressor/-/grunt-htmlcompressor-0.1.9.tgz
Notice: /Stage[main]/Grunt/Exec[grunt-htmlcompressor]/returns: npm http 404 https://registry.npmjs.org/grunt-htmlcompressor/-/grunt-htmlcompressor-0.1.9.tgz
Notice: /Stage[main]/Grunt/Exec[grunt-htmlcompressor]/returns: npm ERR! fetch failed https://registry.npmjs.org/grunt-htmlcompressor/-/grunt-htmlcompressor-0.1.9.tgz
Notice: /Stage[main]/Grunt/Exec[grunt-htmlcompressor]/returns: npm ERR! Error: 404 Not Found
Notice: /Stage[main]/Grunt/Exec[grunt-htmlcompressor]/returns: npm ERR!     at WriteStream.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/fetch.js:57:12)
Notice: /Stage[main]/Grunt/Exec[grunt-htmlcompressor]/returns: npm ERR!     at WriteStream.EventEmitter.emit (events.js:117:20)
Notice: /Stage[main]/Grunt/Exec[grunt-htmlcompressor]/returns: npm ERR!     at fs.js:1596:14
Notice: /Stage[main]/Grunt/Exec[grunt-htmlcompressor]/returns: npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:103:5
Notice: /Stage[main]/Grunt/Exec[grunt-htmlcompressor]/returns: npm ERR!     at Object.oncomplete (fs.js:107:15)
Notice: /Stage[main]/Grunt/Exec[grunt-htmlcompressor]/returns: npm ERR! If you need help, you may report this log at:
Notice: /Stage[main]/Grunt/Exec[grunt-htmlcompressor]/returns: npm ERR!     <http://github.com/isaacs/npm/issues>
Notice: /Stage[main]/Grunt/Exec[grunt-htmlcompressor]/returns: npm ERR! or email it to:
Notice: /Stage[main]/Grunt/Exec[grunt-htmlcompressor]/returns: npm ERR!     <npm-@googlegroups.com>
Notice: /Stage[main]/Grunt/Exec[grunt-htmlcompressor]/returns: 
Notice: /Stage[main]/Grunt/Exec[grunt-htmlcompressor]/returns: npm ERR! System Linux 2.6.32-358.14.1.el6.x86_64
Notice: /Stage[main]/Grunt/Exec[grunt-htmlcompressor]/returns: npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "grunt-htmlcompressor"
Notice: /Stage[main]/Grunt/Exec[grunt-htmlcompressor]/returns: npm ERR! cwd /home/kahmed/qa/puppet_qa/modules/grunt/manifests
Notice: /Stage[main]/Grunt/Exec[grunt-htmlcompressor]/returns: npm ERR! node -v v0.10.21
Notice: /Stage[main]/Grunt/Exec[grunt-htmlcompressor]/returns: npm ERR! npm -v 1.3.11
Notice: /Stage[main]/Grunt/Exec[grunt-htmlcompressor]/returns: npm ERR! 
Notice: /Stage[main]/Grunt/Exec[grunt-htmlcompressor]/returns: npm ERR! Additional logging details can be found in:
Notice: /Stage[main]/Grunt/Exec[grunt-htmlcompressor]/returns: npm ERR!     /home/kahmed/qa/puppet_qa/modules/grunt/manifests/npm-debug.log
Notice: /Stage[main]/Grunt/Exec[grunt-htmlcompressor]/returns: npm ERR! not ok code 0
Error: npm install grunt-htmlcompressor returned 1 instead of one of [0]
Error: /Stage[main]/Grunt/Exec[grunt-htmlcompressor]/returns: change from notrun to 0 failed: npm install grunt-htmlcompressor returned 1 instead of one of [0]
Debug: Class[Grunt]: The container Stage[main] will propagate my refresh event
Debug: Finishing transaction 35543240
Debug: Storing state
Debug: Stored state in 0.71 seconds
Notice: Finished catalog run in 57.05 seconds
Debug: Using settings: adding file resource 'rrddir': 'File[/var/opt/lib/pe-puppet/rrd]{:path=>"/var/opt/lib/pe-puppet/rrd", :mode=>"750", :owner=>"pe-puppet", :group=>"pe-puppet", :ensure=>:directory, :loglevel=>:debug, :links=>:follow, :backup=>false}'
Debug: Finishing transaction 34948400
```

**Comment by othiym23** [comment]
Closing as abandoned.
