### ISSUE TITLE
publish,  Error uploading package: forbidden Non-string script field

### ISSUE THREAD

**Issue by bitliner** [npm/npm#4156]
I'm publishing a new version of my module, but it throws the following error:

```
npm ERR! Error: forbidden Non-string script field: travis-cov: restful-mongo/0.3.5/-tag/latest
npm ERR!     at RegClient.<anonymous> (/usr/lib/nodejs/npm/node_modules/npm-registry-client/lib/request.js:268:14)
npm ERR!     at Request.init.self.callback (/usr/lib/nodejs/npm/node_modules/request/main.js:120:22)
npm ERR!     at Request.EventEmitter.emit (events.js:99:17)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/npm/node_modules/request/main.js:648:16)
npm ERR!     at Request.EventEmitter.emit (events.js:126:20)
npm ERR!     at IncomingMessage.Request.start.self.req.self.httpModule.request.buffer (/usr/lib/nodejs/npm/node_modules/request/main.js:610:14)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:126:20)
npm ERR!     at IncomingMessage._emitEnd (http.js:366:10)
npm ERR!     at HTTPParser.parserOnMessageComplete [as onMessageComplete] (http.js:149:23)
npm ERR!     at CleartextStream.socketOnData [as ondata] (http.js:1485:20)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.2.0-56-generic
npm ERR! command "nodejs" "/usr/bin/npm" "publish"
npm ERR! cwd /home/my-home/...
npm ERR! node -v v0.8.22
npm ERR! npm -v 1.2.14

```

**Comment by smikes** [comment]
Can this issue now be closed?

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!
