### ISSUE TITLE
Error: Callback called more than once.

### ISSUE THREAD

**Issue by bjornstar** [npm/npm#4169]
I'm pretty sure it's because of multiple optionalDependencies failing to compile. I am on OS X 10.9. It happens on npm v1.3.14, v1.3.11, & v1.2.30

Here is the error message:
```
npm ERR! Error: Callback called more than once.
npm ERR!     at errorHandler (/Users/bjornstromberg/.nvm/v0.10.22/lib/node_modules/npm/lib/utils/error-handler.js:80:16)
npm ERR!     at save (/Users/bjornstromberg/.nvm/v0.10.22/lib/node_modules/npm/lib/install.js:330:12)
npm ERR!     at /Users/bjornstromberg/.nvm/v0.10.22/lib/node_modules/npm/lib/install.js:98:7
npm ERR!     at /Users/bjornstromberg/.nvm/v0.10.22/lib/node_modules/npm/lib/install.js:188:5
npm ERR!     at /Users/bjornstromberg/.nvm/v0.10.22/lib/node_modules/npm/node_modules/read-installed/read-installed.js:119:5
npm ERR!     at /Users/bjornstromberg/.nvm/v0.10.22/lib/node_modules/npm/node_modules/read-installed/read-installed.js:233:14
npm ERR!     at cb (/Users/bjornstromberg/.nvm/v0.10.22/lib/node_modules/npm/node_modules/slide/lib/async-map.js:48:11)
npm ERR!     at /Users/bjornstromberg/.nvm/v0.10.22/lib/node_modules/npm/node_modules/read-installed/read-installed.js:233:14
npm ERR!     at cb (/Users/bjornstromberg/.nvm/v0.10.22/lib/node_modules/npm/node_modules/slide/lib/async-map.js:48:11)
npm ERR!     at /Users/bjornstromberg/.nvm/v0.10.22/lib/node_modules/npm/node_modules/read-installed/read-installed.js:233:14
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 13.0.0
npm ERR! command "/Users/bjornstromberg/.nvm/v0.10.22/bin/node" "/Users/bjornstromberg/.nvm/v0.10.22/bin/npm" "install"
npm ERR! cwd /Users/bjornstromberg/myapp
npm ERR! node -v v0.10.22
npm ERR! npm -v 1.3.14
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/bjornstromberg/myapp/npm-debug.log
npm ERR! not ok code 0
```

**Comment by smikes** [comment]
Is this still a problem for you?

There may still be race conditions around `optionalDependencies` or dependencies that require compilation, but overall the install has become much more reliable since 1.3.4.  Can you try updating your npm installation?

To update npm, run `npm -g install npm@latest`

Then, if the problem persists, could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as resolved.
