### ISSUE TITLE
Unable to register user

### ISSUE THREAD

**Issue by gprasant** [npm/npm#4170]
I am unable to register as a user on npmjs.org/signup. ie. When I fill up the form and then click on 'Make it so', the page just refreshes and I am not given any info as to whether it passed or failed. Looking at the network panel in dev-tools I see it failed with a 400.

I had no luck trying to register with npm adduser too.

``` bash 
 npm adduser
Username: gprasant
Password: 
Email: nagu89[at]gmail[dot]com #(I entered the valid form though)
npm http PUT https://registry.npmjs.org/-/user/org.couchdb.user:gprasant
npm http 409 https://registry.npmjs.org/-/user/org.couchdb.user:gprasant
npm http GET https://registry.npmjs.org/-/user/org.couchdb.user:gprasant
npm http 401 https://registry.npmjs.org/-/user/org.couchdb.user:gprasant
npm WARN adduser Incorrect username or password
npm WARN adduser You can reset your account by visiting:
npm WARN adduser 
npm WARN adduser     http://admin.npmjs.org/reset
npm WARN adduser 
npm ERR! Error: unauthorized Name or password is incorrect.: -/user/org.couchdb.user:gprasant
npm ERR!     at RegClient.<anonymous> (/usr/local/Cellar/node08/0.8.24/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:272:14)
npm ERR!     at Request.self.callback (/usr/local/Cellar/node08/0.8.24/lib/node_modules/npm/node_modules/request/request.js:129:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/local/Cellar/node08/0.8.24/lib/node_modules/npm/node_modules/request/request.js:873:14)
npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/local/Cellar/node08/0.8.24/lib/node_modules/npm/node_modules/request/request.js:824:12)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 12.5.0
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "adduser"
npm ERR! cwd /Users/pguruprasad/Projects/express-sextant
npm ERR! node -v v0.10.22
npm ERR! npm -v 1.3.14
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/pguruprasad/Projects/express-sextant/npm-debug.log
npm ERR! not ok code 0

```

Even when I try to reset my account (assuming it was created in the first place) with http://admin.npmjs.org/reset , I get no email from npmjs.org.

**Comment by smikes** [comment]
Did this ever get addressed? /cc @othiym23 for user account issues

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by smikes** [comment]
@gprasant , have you tried sending e-mail to support@npmjs.com per https://docs.npmjs.com/misc/disputes ?

**Comment by othiym23** [comment]
I'm closing this as abandoned because it's been 15 months since the last update from the OP. @gprasant, feel free to leave a note here if you come back to this later and you're still having issues with login, and we can help you with next steps.

**Comment by gprasant** [comment]
no problem! Good to be closed out !
