### ISSUE TITLE
packages that have dependencies that depend on $self make npm implode

### ISSUE THREAD

**Issue by mcavage** [npm/npm#4171]
I found this pathology when trying to add a patch to `lru-cache`:

```
i'm patching node-lru-cache: npm install ->
8:05
npm http 304 https://registry.npmjs.org/lru-cache
npm ERR! cycle Unresolvable cycle detected
npm ERR! cycle While installing: lru-cache@2.3.1
npm ERR! cycle Found a pathological dependency case that npm cannot solve.
npm ERR! cycle Please report this to the package author.

npm ERR! System Darwin 12.5.0
npm ERR! command "/Users/mcavage/.nvm/v0.10.21/bin/node" "/Users/mcavage/.nvm/v0.10.21/bin/npm" "install"
npm ERR! cwd /Users/mcavage/work/node-lru-cache
npm ERR! node -v v0.10.21
npm ERR! npm -v 1.3.11
npm ERR! code ECYCLE
npm http 304 https://registry.npmjs.org/uglify-js
```

Worked around:

```
npm i tap
and then npm i
```

Which results in:

```
$ npm test

> lru-cache@2.3.1 test /Users/mcavage/work/node-lru-cache
> tap test --gc


module.js:340
   throw err;
         ^
Error: Cannot find module 'lru-cache'
   at Function.Module._resolveFilename (module.js:338:15)
   at Function.Module._load (module.js:280:25)
   at Module.require (module.js:364:17)
   at require (module.js:380:17)
   at /Users/mcavage/work/node-lru-cache/node_modules/tap/node_modules/glob/node_modules/minimatch/minimatch.js:35:11
   at Object.<anonymous> (/Users/mcavage/work/node-lru-cache/node_modules/tap/node_modules/glob/node_modules/minimatch/minimatch.js:1075:3)
   at Module._compile (module.js:456:26)
   at Object.Module._extensions..js (module.js:474:10)
   at Module.load (module.js:356:32)
   at Function.Module._load (module.js:312:12)
npm ERR! weird error 8
npm ERR! not ok code 0
Marks-MacBook-Pro:node-lru-cache mcavage$
```

Which can be worked around with:

```
cd ~/; ln -s work node_modules; mv ~/work/node-lru-cache ~/work/lru-cache; cd ~/work/lru-cache; npm test
```

From @isaacs:

```
basically, it looks like the root package should not be included in teh "ancestors" at all
8:14
because it’s assuming that the top-level package is in a place where it can be require()’d
note that that IS true in a global install.  but NOT in a local install.
```

**Comment by OmgImAlexis** [comment]
Is this still an issues in `npm v3`? If it's no longer an issue this should be closed.
