### ISSUE TITLE
TypeError: Property 'onIncoming' of object #<HTTPParser> is not a function

### ISSUE THREAD

**Issue by 8mccm8** [npm/npm#4267]
```
1569 error TypeError: Property 'onIncoming' of object #<HTTPParser> is not a function
1569 error     at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
1569 error     at TLSSocket.socketOnData (_http_client.js:272:20)
1569 error     at TLSSocket.EventEmitter.emit (events.js:98:17)
1569 error     at readableAddChunk (_stream_readable.js:156:16)
1569 error     at TLSSocket.Readable.push (_stream_readable.js:123:10)
1569 error     at TCP.onread (net.js:509:20)
1570 error If you need help, you may report this log at:
1570 error     <http://github.com/isaacs/npm/issues>
1570 error or email it to:
1570 error     <npm-@googlegroups.com>
1571 error System Linux 3.6.11+
1572 error command "/home/pi/node-v0.11.9-linux-arm-pi/bin/node" "/home/pi/node-v0.11.9-linux-arm-pi/bin/npm" "install"
1573 error cwd /home/pi/test/PiFX
1574 error node -v v0.11.9
1575 error npm -v 1.3.15
1576 verbose exit [ 1, true ]
```

**Comment by smikes** [comment]
Is this still a problem for you with current node >= 0.11.10?

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as abandoned.
