### ISSUE TITLE
New package publish failed with messages like an install of plugin that doesn't exist

### ISSUE THREAD

**Issue by lazd** [npm/npm#4278]
I tried to publish a shiny new package and things went arwy.

## What I typed at the command line

```
$ npm publish
npm http PUT https://registry.npmjs.org/gulp-handlebars
npm http 201 https://registry.npmjs.org/gulp-handlebars
npm http GET https://registry.npmjs.org/gulp-handlebars
npm http 404 https://registry.npmjs.org/gulp-handlebars
npm ERR! 404 'gulp-handlebars' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.
npm ERR! System Darwin 12.4.0
npm ERR! command "node" "/usr/local/bin/npm" "publish"
npm ERR! cwd /Users/lazd/repos/gulp-handlebars
npm ERR! node -v v0.10.17
npm ERR! npm -v 1.3.8
npm ERR! code E404
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/lazd/repos/gulp-handlebars/npm-debug.log
npm ERR! not ok code 0
```

What? That's confusing, I should get *that* error when I try to **install** a package that doesn't exist...

## I tried again

Because the best kind of troubleshooting is hitting it with a stick until something changes:

```
$ npm publish
npm http PUT https://registry.npmjs.org/gulp-handlebars
npm http 409 https://registry.npmjs.org/gulp-handlebars
npm http GET https://registry.npmjs.org/gulp-handlebars
npm http 200 https://registry.npmjs.org/gulp-handlebars
npm http PUT https://registry.npmjs.org/gulp-handlebars/-/gulp-handlebars-0.1.0.tgz/-rev/1-92521f86600eacc10b8e4331fb7bd35c
npm http 201 https://registry.npmjs.org/gulp-handlebars/-/gulp-handlebars-0.1.0.tgz/-rev/1-92521f86600eacc10b8e4331fb7bd35c
npm http PUT https://registry.npmjs.org/gulp-handlebars/0.1.0/-tag/latest
npm http 201 https://registry.npmjs.org/gulp-handlebars/0.1.0/-tag/latest
```

## Success (or so it seems)...

However, I visited the page for the package and got an error:
https://npmjs.org/package/gulp-handlebars

Stack:
```
Error: invalid package: gulp-handlebars
    at ServerResponse.error (/home/node/npm-www/node_modules/error-page/error-page.js:108:20)
    at MC.ondone (/home/node/npm-www/routes/package-page.js:26:24)
    at MC.next (/home/node/npm-www/node_modules/emcee/emcee.js:45:12)
    at /home/node/npm-www/models/package.js:60:16
    at RegClient.get_ (/home/node/npm-www/node_modules/npm-registry-client/lib/get.js:101:14)
    at RegClient.<anonymous> (/home/node/npm-www/node_modules/npm-registry-client/lib/get.js:37:12)
    at fs.js:266:14
    at Object.oncomplete (fs.js:107:15)
```

Headers:
```
{
  "host": "npmjs.org",
  "connection": "keep-alive",
  "cache-control": "max-age=0",
  "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
  "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.63 Safari/537.36",
  "referer": "https://npmjs.org/~",
  "accept-encoding": "gzip,deflate,sdch",
  "accept-language": "en-US,en;q=0.8"
}
```

Error:
```
{}
```

Message:
```
invalid package: gulp-handlebars
```

User: lazd
Stamp: pid=33116 worker=4 6d7550eac58486fd0fb1ef75860a357230285f44 https://npmjs.org:10004

## And the 500 fixes itself

12 minutes later, the 500 error is gone. However, I'm still wondering about the odd response to the initial `npm publish` attempt.

## Additional details

Here's my `package.json`:

```
{
  "name": "gulp-handlebars",
  "version": "0.1.0",
  "description": "Handlebars plugin for Gulp",
  "main": "index.js",
  "dependencies": {
    "gulp-util": "~1.2.0",
    "event-stream": "~3.0.18",
    "handlebars": "~1.1.2"
  },
  "devDependencies": {
    "should": "~2.1.1",
    "mocha": "~1.15.1"
  },
  "scripts": {
    "test": "./node_modules/.bin/mocha"
  },
  "repository": {
    "type": "git",
    "url": "git://github.com/lazd/gulp-handlebars.git"
  },
  "keywords": [
    "gulpplugin",
    "gulp",
    "handlebars"
  ],
  "author": "Larry Davis <lazdnet@gmail.com>",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/lazd/gulp-handlebars/issues"
  }
}
```

--

This was formerly https://github.com/isaacs/npm-www/issues/491, but as the initial error was very odd, I'm filing it here.

**Comment by smikes** [comment]
Can this issue now be closed?

The registry backend and replication setup have been changed since December 2013.  Has anyone been seeing these issues recently?

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by andrey-p** [comment]
Everything's been fine with publishing modules as far as I'm concerned.

**Comment by othiym23** [comment]
Closing as resolved.
