### ISSUE TITLE
If install dir is on nfs mount with unsynced date npm builds fail

### ISSUE THREAD

**Issue by gauthierm** [npm/npm#4319]
On my system, my home directory is mounted over nfs and hosted on another server. When I try to install node packages it fails because the timestamps are out of sync between the servers.

```
[gauthierm@blood ~]$ npm install ember-precompile
npm http GET https://registry.npmjs.org/ember-precompile
npm http 304 https://registry.npmjs.org/ember-precompile
npm http GET https://registry.npmjs.org/optimist/0.3.4
npm http GET https://registry.npmjs.org/jquery
npm http 304 https://registry.npmjs.org/optimist/0.3.4
npm http 304 https://registry.npmjs.org/jquery
npm http GET https://registry.npmjs.org/jsdom
npm http GET https://registry.npmjs.org/htmlparser/1.7.6
npm http GET https://registry.npmjs.org/xmlhttprequest
npm http GET https://registry.npmjs.org/location/0.0.1
npm http GET https://registry.npmjs.org/navigator
npm http GET https://registry.npmjs.org/contextify
npm http GET https://registry.npmjs.org/wordwrap
npm http 304 https://registry.npmjs.org/location/0.0.1
npm http 304 https://registry.npmjs.org/navigator
npm http 304 https://registry.npmjs.org/jsdom
npm http 304 https://registry.npmjs.org/htmlparser/1.7.6
npm http 304 https://registry.npmjs.org/wordwrap
npm http 304 https://registry.npmjs.org/contextify
npm http 304 https://registry.npmjs.org/xmlhttprequest
npm http GET https://registry.npmjs.org/bindings
npm http GET https://registry.npmjs.org/request
npm http GET https://registry.npmjs.org/cssom
npm http GET https://registry.npmjs.org/cssstyle
npm http 304 https://registry.npmjs.org/bindings

> contextify@0.1.6 install /home/gauthierm/node_modules/ember-precompile/node_modules/jquery/node_modules/contextify
> node-gyp rebuild

npm http 304 https://registry.npmjs.org/cssom
npm http 304 https://registry.npmjs.org/cssstyle
npm http 304 https://registry.npmjs.org/request
npm http GET https://registry.npmjs.org/cssstyle/-/cssstyle-0.2.7.tgz
npm http GET https://registry.npmjs.org/request/-/request-2.30.0.tgz
make: Entering directory `/home/gauthierm/node_modules/ember-precompile/node_modules/jquery/node_modules/contextify/build'
make: Warning: File `contextify.target.mk' has modification time 8.9 s in the future
  CXX(target) Release/obj.target/contextify/src/contextify.o
npm http 200 https://registry.npmjs.org/request/-/request-2.30.0.tgz
npm http 200 https://registry.npmjs.org/cssstyle/-/cssstyle-0.2.7.tgz
  SOLINK_MODULE(target) Release/obj.target/contextify.node
flock: ./Release/linker.lock: Bad file descriptor
make: *** [Release/obj.target/contextify.node] Error 65
make: Leaving directory `/home/gauthierm/node_modules/ember-precompile/node_modules/jquery/node_modules/contextify/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Linux 2.6.32-358.18.1.el6.x86_64
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/gauthierm/node_modules/ember-precompile/node_modules/jquery/node_modules/contextify
gyp ERR! node -v v0.10.21
gyp ERR! node-gyp -v v0.10.6
gyp ERR! not ok
npm ERR! weird error 1
npm ERR! not ok code 0
```

**Comment by busches** [comment]
@KenanY no updates in over two years.
