### ISSUE TITLE
Error: conflict Document update conflict

### ISSUE THREAD

**Issue by howardabrams** [npm/npm#4366]
Attempting to log in, I get the errors below. I try following the solution suggested on [#4093](https://github.com/isaacs/npm/issues/4093), but this doesn't seem to solve my problem.

```
$ npm adduser
Username: (your_username) howardabrams
Password: 
Email: (howard@howardabrams.com) 
npm http PUT https://registry.npmjs.org/-/user/org.couchdb.user:howardabrams
npm http 409 https://registry.npmjs.org/-/user/org.couchdb.user:howardabrams
npm http GET https://registry.npmjs.org/-/user/org.couchdb.user:howardabrams
npm http 200 https://registry.npmjs.org/-/user/org.couchdb.user:howardabrams
npm http PUT https://registry.npmjs.org/-/user/org.couchdb.user:howardabrams/-rev/9-d85ba589e89f5abc15874e29c08ab2fe
npm http 409 https://registry.npmjs.org/-/user/org.couchdb.user:howardabrams/-rev/9-d85ba589e89f5abc15874e29c08ab2fe
npm ERR! Error: conflict Document update conflict.: -/user/org.couchdb.user:howardabrams/-rev/9-d85ba589e89f5abc15874e29c08ab2fe
npm ERR!     at RegClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:275:14)
npm ERR!     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:123:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:893:14)
npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:844:12)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/isaacs/npm/issues>

npm ERR! System Darwin 13.0.0
npm ERR! command "node" "/usr/local/bin/npm" "adduser"
npm ERR! cwd /Users/howard/Documents/Work/Node/node-mocks-http
npm ERR! node -v v0.10.24
npm ERR! npm -v 1.3.21
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/howard/Documents/Work/Node/node-mocks-http/npm-debug.log
npm ERR! not ok code 0
```

**Comment by smikes** [comment]
Is this still a problem for you?

This looks like it might have been related to the registry as implemented at the time (February 2014).  Now, almost a year later, the registry implementation has changed substantially.  Are you still seeing errors of this type?

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by howardabrams** [comment]
This bug can be closed. Thanks.

**Comment by othiym23** [comment]
Closing as resolved.
