### ISSUE TITLE
shrinkwrap error

### ISSUE THREAD

**Issue by mgol** [npm/npm#4435]
`npm shrinkwrap` errors for me. IMO it should always work if `npm install` succeeded and yet it doesn't here:

```
$ npm shrinkwrap --dev
npm ERR! Error: Problems were encountered
npm ERR! Please correct and try again.
npm ERR! extraneous: fsevents@0.1.6 /Users/mgol/Documents/projects/bn/cbn/repo/polona-gui/node_modules/karma/node_modules/chokidar/node_modules/fsevents
npm ERR! extraneous: recursive-readdir@0.0.2 /Users/mgol/Documents/projects/bn/cbn/repo/polona-gui/node_modules/karma/node_modules/chokidar/node_modules/recursive-readdir
npm ERR!     at shrinkwrap_ (/usr/local/lib/node_modules/npm/lib/shrinkwrap.js:29:15)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/shrinkwrap.js:23:5
npm ERR!     at /usr/local/lib/node_modules/npm/lib/ls.js:43:30
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js:119:5
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js:240:14
npm ERR!     at cb (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:48:11)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js:240:14
npm ERR!     at cb (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:48:11)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js:240:14
npm ERR!     at cb (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:48:11)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/isaacs/npm/issues>

npm ERR! System Darwin 13.0.0
npm ERR! command "node" "/usr/local/bin/npm" "shrinkwrap" "--dev"
npm ERR! cwd /Users/mgol/Documents/projects/bn/cbn/repo/polona-gui
npm ERR! node -v v0.10.24
npm ERR! npm -v 1.3.23
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/mgol/Documents/projects/bn/cbn/repo/polona-gui/npm-debug.log
npm ERR! not ok code 0
```

My package.json:
```json
{
    "name": "polona-gui",
    "version": "2.1.0-pre",
    "devDependencies": {
        "connect-modrewrite": "0.5.11",
        "findup-sync": "0.1.2",
        "grunt": "0.4.2",
        "grunt-angular-templates": "0.5.1",
        "grunt-check-dependencies": "0.3.0",
        "grunt-contrib-clean": "0.5.0",
        "grunt-contrib-compass": "0.7.0",
        "grunt-contrib-concat": "0.3.0",
        "grunt-contrib-connect": "0.6.0",
        "grunt-contrib-copy": "0.5.0",
        "grunt-contrib-htmlmin": "0.1.3",
        "grunt-contrib-jshint": "0.8.0",
        "grunt-contrib-uglify": "0.2.7",
        "grunt-contrib-watch": "0.5.3",
        "grunt-csso": "0.5.2",
        "grunt-ddescribe-iit": "EE/grunt-ddescribe-iit#better-parsing",
        "grunt-defs": "0.6.1",
        "grunt-jsonlint": "1.0.4",
        "grunt-karma": "0.6.2",
        "grunt-merge-conflict": "0.0.2",
        "grunt-newer": "0.6.0",
        "grunt-ng-annotate": "0.0.4",
        "grunt-notify": "0.2.17",
        "grunt-rev": "0.1.0",
        "grunt-shell": "0.6.1",
        "grunt-usemin": "2.0.2",
        "karma-coverage": "0.1.4",
        "karma-junit-reporter": "0.2.1",
        "karma-ng-json2js-preprocessor": "0.0.4",
        "karma-opera-launcher": "0.1.0",
        "load-grunt-tasks": "0.2.1"
    }
}
```

**Comment by fresheneesz** [comment]
I tried `npm prune` - doesn't help. I still get the same unmet dependency problems when shrinkwrapping.

**Comment by kud** [comment]
If you want to make shrinkwrap work, you have to have only modules installed via (dev)Dependencies in package.json.

If you use solutions like `napa` or if you manually installed some modules in node_modules, it won't work.

`npm prune` removes these extra modules and it should work juster after that.

**Comment by lukeapage** [comment]
as-of npm@3.5.0 this is no longer a problem for me. It might be fixed!

**Comment by ajsharp** [comment]
I'm on 3.5.2 and it's still an issue here.

**Comment by gajus** [comment]
@ajsharp try:

```sh
npm install
npm prune
npm dedupe
npm install
npm shrinkwrap --dev
```

**Comment by lukeapage** [comment]
or for me on 3.5.2 just
```
rm -rf node_modules
npm i
npm shrinkwrap --dev
```

**Comment by mnpenner** [comment]
Fails on 2.14.15 too.

```
npm shrinkwrap --dev                            
npm ERR! Linux 3.16.0-44-generic
npm ERR! argv "/home/me/Programs/node-v4.2.3-linux-x64/bin/node" "/usr/local/bin/npm" "shrinkwrap" "--dev"
npm ERR! node v4.2.3
npm ERR! npm  v2.14.15

npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! extraneous: pretty-hrtime@1.0.0 /home/me/Projects/myproj/node_modules/pretty-hrtime
npm ERR! extraneous: rsync@0.4.0 /home/me/Projects/myproj/node_modules/rsync
npm ERR! extraneous: gulp-print@1.1.0 /home/me/Projects/myproj/node_modules/gulp-print
npm ERR! extraneous: watchree@0.1.4 /home/me/Projects/myproj/node_modules/watchree
npm ERR! extraneous: tiny-lr@0.1.5 /home/me/Projects/myproj/node_modules/tiny-lr
npm ERR! extraneous: gulp-expect-file@0.0.7 /home/me/Projects/myproj/node_modules/gulp-expect-file
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/me/Projects/myproj/npm-debug.log
```

@gajus 's solution didn't work.

@lukeapage 's solution *does* work but `npm i` takes 3 min, and I have to do this quite frequently, so this is pretty painful.

**Comment by andyearnshaw** [comment]
@gajus' solution was almost right for me, just ignore the second `npm install`:

```
npm install
npm prune
npm dedupe
npm shrinkwrap --dev
```

**Comment by busches** [comment]
@KenanY the bug with most reports is extraneous packages being found, which isn't an error. It looks like their may have been a problem two years ago, but it's since been fixed.

**Comment by KenanY** [comment]
@busches Hmm alright, can reopen if this is still an issue.

**Comment by Olgagr** [comment]
I still have this issue: npm 3.10.8, node 6.6.0. I did:

```
npm install
npm prune
npm dedupe
npm shrinkwrap --dev
```

```
npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! extraneous: acorn-jsx@3.0.1 /Users/apple/Projects/er-app-sdk/node_modules/acorn-jsx
npm ERR! extraneous: acorn@3.3.0 /Users/apple/Projects/er-app-sdk/node_modules/acorn-jsx/node_modules/acorn
npm ERR! extraneous: ajv@4.7.6 /Users/apple/Projects/er-app-sdk/node_modules/ajv
npm ERR! extraneous: ajv-keywords@1.1.1 /Users/apple/Projects/er-app-sdk/node_modules/ajv-keywords
npm ERR! extraneous: ansi-escapes@1.4.0 /Users/apple/Projects/er-app-sdk/node_modules/ansi-escapes
npm ERR! extraneous: array-union@1.0.2 /Users/apple/Projects/er-app-sdk/node_modules/array-union
npm ERR! extraneous: babel-plugin-tcomb@0.3.16 /Users/apple/Projects/er-app-sdk/node_modules/babel-plugin-tcomb
npm ERR! extraneous: caller-path@0.1.0 /Users/apple/Projects/er-app-sdk/node_modules/caller-path
npm ERR! extraneous: callsites@0.2.0 /Users/apple/Projects/er-app-sdk/node_modules/callsites
npm ERR! extraneous: circular-json@0.3.1 /Users/apple/Projects/er-app-sdk/node_modules/circular-json
npm ERR! extraneous: cli-cursor@1.0.2 /Users/apple/Projects/er-app-sdk/node_modules/cli-cursor
npm ERR! extraneous: cli-width@2.1.0 /Users/apple/Projects/er-app-sdk/node_modules/cli-width
npm ERR! extraneous: co@4.6.0 /Users/apple/Projects/er-app-sdk/node_modules/co
npm ERR! extraneous: concat-stream@1.5.2 /Users/apple/Projects/er-app-sdk/node_modules/concat-stream
npm ERR! extraneous: isarray@1.0.0 /Users/apple/Projects/er-app-sdk/node_modules/concat-stream/node_modules/isarray
npm ERR! extraneous: readable-stream@2.0.6 /Users/apple/Projects/er-app-sdk/node_modules/concat-stream/node_modules/readable-stream
npm ERR! extraneous: del@2.2.2 /Users/apple/Projects/er-app-sdk/node_modules/del
npm ERR! extraneous: es6-weak-map@2.0.1 /Users/apple/Projects/er-app-sdk/node_modules/es6-weak-map
npm ERR! extraneous: escope@3.6.0 /Users/apple/Projects/er-app-sdk/node_modules/escope
npm ERR! extraneous: estraverse@4.2.0 /Users/apple/Projects/er-app-sdk/node_modules/escope/node_modules/estraverse
npm ERR! extraneous: eslint@3.7.0 /Users/apple/Projects/er-app-sdk/node_modules/eslint
npm ERR! extraneous: estraverse@4.2.0 /Users/apple/Projects/er-app-sdk/node_modules/eslint/node_modules/estraverse
npm ERR! extraneous: fast-levenshtein@2.0.5 /Users/apple/Projects/er-app-sdk/node_modules/eslint/node_modules/fast-levenshtein
npm ERR! extraneous: globals@9.10.0 /Users/apple/Projects/er-app-sdk/node_modules/eslint/node_modules/globals
npm ERR! extraneous: levn@0.3.0 /Users/apple/Projects/er-app-sdk/node_modules/eslint/node_modules/levn
npm ERR! extraneous: optionator@0.8.2 /Users/apple/Projects/er-app-sdk/node_modules/eslint/node_modules/optionator
npm ERR! extraneous: user-home@2.0.0 /Users/apple/Projects/er-app-sdk/node_modules/eslint/node_modules/user-home
npm ERR! extraneous: wordwrap@1.0.0 /Users/apple/Projects/er-app-sdk/node_modules/eslint/node_modules/wordwrap
npm ERR! extraneous: espree@3.3.2 /Users/apple/Projects/er-app-sdk/node_modules/espree
npm ERR! extraneous: acorn@4.0.3 /Users/apple/Projects/er-app-sdk/node_modules/espree/node_modules/acorn
npm ERR! extraneous: esrecurse@4.1.0 /Users/apple/Projects/er-app-sdk/node_modules/esrecurse
npm ERR! extraneous: exit-hook@1.1.1 /Users/apple/Projects/er-app-sdk/node_modules/exit-hook
npm ERR! extraneous: figures@1.7.0 /Users/apple/Projects/er-app-sdk/node_modules/figures
npm ERR! extraneous: file-entry-cache@2.0.0 /Users/apple/Projects/er-app-sdk/node_modules/file-entry-cache
npm ERR! extraneous: flat-cache@1.2.1 /Users/apple/Projects/er-app-sdk/node_modules/flat-cache
npm ERR! extraneous: globby@5.0.0 /Users/apple/Projects/er-app-sdk/node_modules/globby
npm ERR! extraneous: ignore@3.1.5 /Users/apple/Projects/er-app-sdk/node_modules/ignore
npm ERR! extraneous: imurmurhash@0.1.4 /Users/apple/Projects/er-app-sdk/node_modules/imurmurhash
npm ERR! extraneous: inquirer@0.12.0 /Users/apple/Projects/er-app-sdk/node_modules/inquirer
npm ERR! extraneous: is-path-cwd@1.0.0 /Users/apple/Projects/er-app-sdk/node_modules/is-path-cwd
npm ERR! extraneous: is-path-in-cwd@1.0.0 /Users/apple/Projects/er-app-sdk/node_modules/is-path-in-cwd
npm ERR! extraneous: is-path-inside@1.0.0 /Users/apple/Projects/er-app-sdk/node_modules/is-path-inside
npm ERR! extraneous: is-resolvable@1.0.0 /Users/apple/Projects/er-app-sdk/node_modules/is-resolvable
npm ERR! extraneous: json-stable-stringify@1.0.1 /Users/apple/Projects/er-app-sdk/node_modules/json-stable-stringify
npm ERR! extraneous: jsonify@0.0.0 /Users/apple/Projects/er-app-sdk/node_modules/jsonify
npm ERR! extraneous: mute-stream@0.0.5 /Users/apple/Projects/er-app-sdk/node_modules/mute-stream
npm ERR! extraneous: natural-compare@1.4.0 /Users/apple/Projects/er-app-sdk/node_modules/natural-compare
npm ERR! extraneous: onetime@1.1.0 /Users/apple/Projects/er-app-sdk/node_modules/onetime
npm ERR! extraneous: path-is-inside@1.0.2 /Users/apple/Projects/er-app-sdk/node_modules/path-is-inside
npm ERR! extraneous: pluralize@1.2.1 /Users/apple/Projects/er-app-sdk/node_modules/pluralize
npm ERR! extraneous: readline2@1.0.1 /Users/apple/Projects/er-app-sdk/node_modules/readline2
npm ERR! extraneous: require-uncached@1.0.2 /Users/apple/Projects/er-app-sdk/node_modules/require-uncached
npm ERR! extraneous: resolve-from@1.0.1 /Users/apple/Projects/er-app-sdk/node_modules/resolve-from
npm ERR! extraneous: restore-cursor@1.0.1 /Users/apple/Projects/er-app-sdk/node_modules/restore-cursor
npm ERR! extraneous: run-async@0.1.0 /Users/apple/Projects/er-app-sdk/node_modules/run-async
npm ERR! extraneous: rx-lite@3.1.2 /Users/apple/Projects/er-app-sdk/node_modules/rx-lite
npm ERR! extraneous: shelljs@0.6.1 /Users/apple/Projects/er-app-sdk/node_modules/shelljs
npm ERR! extraneous: slice-ansi@0.0.4 /Users/apple/Projects/er-app-sdk/node_modules/slice-ansi
npm ERR! extraneous: strip-bom@3.0.0 /Users/apple/Projects/er-app-sdk/node_modules/strip-bom
npm ERR! extraneous: table@3.8.0 /Users/apple/Projects/er-app-sdk/node_modules/table
npm ERR! extraneous: text-table@0.2.0 /Users/apple/Projects/er-app-sdk/node_modules/text-table
npm ERR! extraneous: tryit@1.0.2 /Users/apple/Projects/er-app-sdk/node_modules/tryit
npm ERR! extraneous: write@0.2.1 /Users/apple/Projects/er-app-sdk/node_modules/write
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/apple/Projects/er-app-sdk/npm-debug.log
```

**Comment by busches** [comment]
@Olgagr can you attach your `package.json` file for the developers to reproduce?

**Comment by Olgagr** [comment]
@busches sure.

```
{
  "name": "er-sdk",
  "appname": "ER SDK",
  "version": "1.2.1-0",
  "description": "",
  "main": "src/index.js",
  "private": true,
  "engines": {
    "node": ">=6.0.0"
  },
  "author": "",
  "devDependencies": {
    "autoprefixer": "6.5.0",
    "babel-core": "6.17.0",
    "babel-eslint": "7.0.0",
    "babel-loader": "6.2.5",
    "babel-plugin-add-module-exports": "0.2.1",
    "babel-plugin-lodash": "3.2.9",
    "babel-plugin-system-import-transformer": "2.4.0",
    "babel-plugin-tcomb": "0.3.17",
    "babel-plugin-transform-class-properties": "6.16.0",
    "babel-plugin-transform-flow-strip-types": "6.14.0",
    "babel-plugin-transform-object-rest-spread": "6.16.0",
    "babel-preset-es2015": "6.16.0",
    "babel-preset-es2015-loose": "8.0.0",
    "babel-preset-react": "6.16.0",
    "casperjs": "1.1.3",
    "cross-env": "3.0.0",
    "css-loader": "0.25.0",
    "esdoc": "0.4.8",
    "esdoc-es7-plugin": "0.0.3",
    "eslint": "3.7.1",
    "eslint-config-airbnb": "12.0.0",
    "eslint-plugin-flowtype": "2.19.0",
    "eslint-plugin-import": "1.16.0",
    "eslint-plugin-jsx-a11y": "2.2.2",
    "eslint-plugin-react": "6.3.0",
    "extract-text-webpack-plugin": "1.0.1",
    "file-loader": "0.9.0",
    "http-server": "0.9.0",
    "istanbul": "0.4.5",
    "jasmine-core": "2.5.2",
    "json-loader": "0.5.4",
    "karma": "1.3.0",
    "karma-babel-preprocessor": "6.0.1",
    "karma-browserstack-launcher": "1.1.1",
    "karma-chrome-launcher": "2.0.0",
    "karma-coverage": "1.1.1",
    "karma-jasmine": "1.0.2",
    "karma-phantomjs-launcher": "1.0.2",
    "karma-sourcemap-loader": "0.3.7",
    "karma-sourcemap-writer": "0.1.2",
    "karma-webpack": "1.8.0",
    "lodash-webpack-plugin": "0.10.1",
    "offline-plugin": "3.4.2",
    "phantomjs-prebuilt": "2.1.12",
    "postcss-browser-reporter": "0.5.0",
    "postcss-cssnext": "2.8.0",
    "postcss-flexbugs-fixes": "2.0.0",
    "postcss-import": "8.1.2",
    "postcss-loader": "0.13.0",
    "postcss-reporter": "1.4.1",
    "postcss-url": "5.1.2",
    "react-hot-loader": "1.3.0",
    "redbox-react": "1.3.1",
    "remap-istanbul": "0.6.4",
    "style-loader": "0.13.1",
    "webpack": "1.13.2",
    "webpack-dashboard": "0.2.0",
    "webpack-dev-server": "1.16.1",
    "why-did-you-update": "0.0.8"
  },
  "dependencies": {
    "aws-sdk": "2.6.7",
    "es6-promise": "4.0.5",
    "localforage": "1.4.2",
    "lodash": "4.16.3",
    "moment": "2.15.1",
    "normalize.css": "5.0.0",
    "react": "15.3.2",
    "react-addons-pure-render-mixin": "15.3.2",
    "react-dom": "15.3.2",
    "react-redux": "4.4.5",
    "redux": "3.6.0",
    "superagent": "2.3.0",
    "tcomb": "3.2.15"
  }
}
```

**Comment by busches** [comment]
I was not able to recreate your issue with a clean install on npm `3.10.8` and node `6.7.0`. 

Can you blow away your `node_modules` folder and see if you can recreate? There may be a problem with `npm prune` or `npm dedupe`, but `npm shrinkwrap` appears to be functioning correctly, those extra packages should NOT be installed.

**Comment by Olgagr** [comment]
Ok, I did fresh install on v6.6.0 and npm 3.10.3. I did:

```
npm install
npm  prune
npm dedupe
npm shrinkwrap --dev
```

This time I got less errors:

```
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "shrinkwrap" "--dev"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3

npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! extraneous: fstream@1.0.10 /Users/apple/Projects/test/node_modules/fsevents/node_modules/fstream
npm ERR! extraneous: json-schema@0.2.2 /Users/apple/Projects/test/node_modules/fsevents/node_modules/json-schema
npm ERR! extraneous: jsonpointer@2.0.0 /Users/apple/Projects/test/node_modules/fsevents/node_modules/jsonpointer
npm ERR! extraneous: mime-db@1.23.0 /Users/apple/Projects/test/node_modules/fsevents/node_modules/mime-db
npm ERR! extraneous: minimist@0.0.8 /Users/apple/Projects/test/node_modules/fsevents/node_modules/minimist
npm ERR! extraneous: readable-stream@2.1.4 /Users/apple/Projects/test/node_modules/fsevents/node_modules/readable-stream
npm ERR! extraneous: semver@5.2.0 /Users/apple/Projects/test/node_modules/fsevents/node_modules/semver
npm ERR! extraneous: supports-color@2.0.0 /Users/apple/Projects/test/node_modules/fsevents/node_modules/supports-color
npm ERR! extraneous: tough-cookie@2.2.2 /Users/apple/Projects/test/node_modules/fsevents/node_modules/tough-cookie
npm ERR! extraneous: tweetnacl@0.13.3 /Users/apple/Projects/test/node_modules/fsevents/node_modules/tweetnacl
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/apple/Projects/test/npm-debug.log
```

So I removed all node_modules and try one more time but without running ```prune``` and ```dedupe```. This time ```npm shrinkwrap --dev``` worked.

**Comment by fresheneesz** [comment]
"Can you blow away your node_modules folder and see if you can recreate?"

That's a problem right there. If you have to blow away your node modules folder, that's a problem that should be fixed.

**Comment by busches** [comment]
@fresheneesz but that would indicate a problem with `npm prune` or `npm dedupe` NOT `npm shrinkwrap` which is what this issue is about. Please open a new issue with a reproducible test case with the issue you're seeing.

**Comment by idautocfator** [comment]
I tried:
npm install
npm  prune
npm dedupe
npm shrinkwrap --dev

It removed everything on my development drive!

**Comment by msafi** [comment]
In my case, I had a dependency in my `package.json` that didn't have `^`. i.e.

```
"minimist": "1.2.0",
```

Putting the `^` back fixed `npm shrinkwrap`.

**Comment by outdooricon** [comment]
I'm also experiencing these extraneous errors, even after following through the prune/dedupe steps. This is new, as I didn't have this the last time i tried to install a new package (about a month ago). This is using node v5.11.1 & npm v3.10.8

**Comment by ngokli** [comment]
It took me a while to figure out what was going on in a project that I'm just joining today...  So perhaps this explanation will help others.  Here's what seems to have happened (before the initial repo commit, so I can't tell for sure):

1. `npm install`
2. `npm shrinkwrap`
3. remove a dependency from `package.json`
4. commit to repo
5. At this point, I came along and did a clean checkout
6. `npm install` <-- This will install the stuff in your `npm-shrinkwrap.json`, even though it's no longer in `package.json`.  No warnings or errors, with `npm v3.10.10`.  I read somewhere this is the expected behavior, because that is how it is being used in the wild (but there may be a more sensible tool coming up).
7. `npm ls` and `npm ls --depth=0` complain of extraneous modules.
8. `npm shrinkwrap` errors out
9. I scratch my head

**Comment by legodude17** [comment]
@ngokli, this is the expected behavior, because `npm-shrinkwrap.json` basically overrides `package.json`. This should be documented though, if it isn't already.

**Comment by fresheneesz** [comment]
@legodude17 We should *change* that expected behavior. Having that be the case is surprising and weird. Your npm shrinkwrap should be an extension of  your package.json, not a replacement.

**Comment by outdooricon** [comment]
You would need some kind of tool to be monitoring your changes to package.json of you want to edit it directly. If you use `npm un` to remove your packages, it also updates your shrinkwrap.

**Comment by fresheneesz** [comment]
@outdooricon Yes. The tool that does that should be "npm shrinkwrap"...

**Comment by ngokli** [comment]
I think it would be helpful if 'npm shrinkwrap` at least gave a warning, if it's not going to do anything fancier.

**Comment by Darkside73** [comment]
1. Delete ```node_nodules``` and ```npm-shrinkwrap.json```
2. ```npm i```
3. ```npm shrinkwrap --dev```

**Comment by maxatbrs** [comment]
Hey everyone - know this is kind of an old thread but wanted to let people know that one issue that i had on my current project. We are using _shonkwrap_ and I was experiencing issues even after running `npm prune`. 

My version of `npm` was 4.1.1 and it was breaking. I downgraded to `npm` v 3.10.7 and this resolved my issue.

This may be related to shonkwrap in my case but I am posting this because other may have this issue. Check your version of npm :octocat:

**Comment by loretoparisi** [comment]
In my case I had this error and just solved with

```
rm -rf node_modules/
npm install --production
npm shrinkwrap
```

you can do simply `npm install` without `--production` option by the way.
This successfully created the `npm-shrinkwrap.json` file.
