### ISSUE TITLE
lineman install issues

### ISSUE THREAD

**Issue by ConorHiggins** [npm/npm#4456]
Hi I've just tried to install lineman via npm:

sudo npm install -g lineman

but it results in the following output:
```
npm http GET https://registry.npmjs.org/lineman
npm http 304 https://registry.npmjs.org/lineman
npm http GET https://registry.npmjs.org/grunt/0.4.1
npm http GET https://registry.npmjs.org/grunt-contrib-clean/0.5.0
npm http GET https://registry.npmjs.org/grunt-contrib-concat/0.3.0
npm http GET https://registry.npmjs.org/grunt-contrib-coffee/0.7.0
npm http GET https://registry.npmjs.org/grunt-contrib-copy/0.4.1
npm http GET https://registry.npmjs.org/grunt-contrib-handlebars/0.5.10
npm http GET https://registry.npmjs.org/grunt-contrib-jshint/0.6.4
npm http GET https://registry.npmjs.org/grunt-contrib-jst/0.5.1
npm http GET https://registry.npmjs.org/grunt-contrib-less/0.7.0
npm http GET https://registry.npmjs.org/grunt-contrib-sass/0.5.0
npm http GET https://registry.npmjs.org/grunt-contrib-uglify/0.2.4
npm http GET https://registry.npmjs.org/grunt-contrib-cssmin/0.6.1
npm http GET https://registry.npmjs.org/grunt-watch-nospawn/0.0.4
npm http GET https://registry.npmjs.org/grunt-asset-fingerprint/0.0.2
npm http GET https://registry.npmjs.org/config-extend/0.0.6
npm http GET https://registry.npmjs.org/commander/1.3.2
npm http GET https://registry.npmjs.org/express/3.4.0
npm http GET https://registry.npmjs.org/http-proxy/0.10.3
npm http GET https://registry.npmjs.org/coffee-script/1.6.3
npm http GET https://registry.npmjs.org/watch_r-structr-lock/0.0.1
npm http GET https://registry.npmjs.org/semver/2.1.0
npm http GET https://registry.npmjs.org/resolve
npm http GET https://registry.npmjs.org/testem
npm http 304 https://registry.npmjs.org/grunt-contrib-clean/0.5.0
npm http 304 https://registry.npmjs.org/grunt/0.4.1
npm http 304 https://registry.npmjs.org/grunt-contrib-concat/0.3.0
npm http 304 https://registry.npmjs.org/grunt-contrib-copy/0.4.1
npm http 304 https://registry.npmjs.org/grunt-contrib-coffee/0.7.0
npm http 304 https://registry.npmjs.org/grunt-contrib-jshint/0.6.4
npm http 304 https://registry.npmjs.org/grunt-contrib-sass/0.5.0
npm http 304 https://registry.npmjs.org/grunt-contrib-handlebars/0.5.10
npm http 304 https://registry.npmjs.org/grunt-contrib-less/0.7.0
npm http 304 https://registry.npmjs.org/grunt-contrib-jst/0.5.1
npm http 304 https://registry.npmjs.org/grunt-contrib-cssmin/0.6.1
npm http 304 https://registry.npmjs.org/grunt-watch-nospawn/0.0.4
npm http 304 https://registry.npmjs.org/grunt-asset-fingerprint/0.0.2
npm http 304 https://registry.npmjs.org/config-extend/0.0.6
npm http GET https://registry.npmjs.org/config-extend/-/config-extend-0.0.6.tgz
npm http 304 https://registry.npmjs.org/grunt-contrib-uglify/0.2.4
npm http 304 https://registry.npmjs.org/commander/1.3.2
npm http 304 https://registry.npmjs.org/express/3.4.0
npm http GET https://registry.npmjs.org/express/-/express-3.4.0.tgz
npm http 304 https://registry.npmjs.org/coffee-script/1.6.3
npm http 304 https://registry.npmjs.org/watch_r-structr-lock/0.0.1
npm http 304 https://registry.npmjs.org/semver/2.1.0
npm http 304 https://registry.npmjs.org/resolve
npm http 304 https://registry.npmjs.org/http-proxy/0.10.3
npm http 304 https://registry.npmjs.org/testem
npm http 404 https://registry.npmjs.org/config-extend/-/config-extend-0.0.6.tgz
npm ERR! fetch failed https://registry.npmjs.org/config-extend/-/config-extend-0.0.6.tgz
npm ERR! Error: 404 Not Found
npm ERR!     at WriteStream.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/fetch.js:57:12)
npm ERR!     at WriteStream.EventEmitter.emit (events.js:117:20)
npm ERR!     at fs.js:1596:14
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:103:5
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/isaacs/npm/issues>

npm ERR! System Darwin 12.5.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "lineman"
npm ERR! cwd /Users/conor/Documents/venus-front-end
npm ERR! node -v v0.10.24
npm ERR! npm -v 1.3.21
npm http 404 https://registry.npmjs.org/express/-/express-3.4.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/express/-/express-3.4.0.tgz
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/conor/Documents/venus-front-end/npm-debug.log
npm ERR! not ok code 0
```

**Comment by smikes** [comment]
@ConorHiggins , Is this still a problem for you?

This looks like it was a temporary problem with the `npm` registry; it should be fixed now.

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.3.21. Can you try updating your npm installation?

To update npm, run `npm -g install npm@latest`

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as resolved / abandoned.
