### ISSUE TITLE
Cannot find module 'github-url-from-git'

### ISSUE THREAD

**Issue by pelargir** [npm/npm#4623]
I've been trying to install Bower via NPM and keep getting this error:

```bash
$ npm install bower
npm ERR! Error: Cannot find module 'github-url-from-git'
npm ERR!     at Function.Module._resolveFilename (module.js:338:15)
npm ERR!     at Function.Module._load (module.js:280:25)
npm ERR!     at Module.require (module.js:364:17)
npm ERR!     at require (module.js:380:17)
npm ERR!     at Object.<anonymous> (/usr/local/Cellar/node/0.8.14/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/fixer.js:2:22)
npm ERR!     at Module._compile (module.js:456:26)
npm ERR!     at Object.Module._extensions..js (module.js:474:10)
npm ERR!     at Module.load (module.js:356:32)
npm ERR!     at Function.Module._load (module.js:312:12)
npm ERR!     at Module.require (module.js:364:17)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/isaacs/npm/issues>

npm ERR! System Darwin 13.0.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "bower"
npm ERR! cwd /Users/pelargir
npm ERR! node -v v0.10.24
npm ERR! npm -v 1.3.21
npm ERR! code MODULE_NOT_FOUND
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/pelargir/npm-debug.log
npm ERR! not ok code 0
```

I'm using NPM version 1.3.21 and Node version 0.10.24

**Comment by smikes** [comment]
@pelargir , Is this still a problem for you?

@timoxley gave a good suggestion above -- it looks like two different installations of `node` are conflicting.

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.3.21. Can you try updating your npm installation?

To update npm, run `npm -g install npm@latest`

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as resolved / abandoned.
