### ISSUE TITLE
issues installing topoJSON with npm

### ISSUE THREAD

**Issue by ekimed** [npm/npm#4633]
I'm a beginner programmer. I'm trying to install topoJSON. However I'm getting a lot of errors. After some research, there seems to be an issue with the platform.py file in python. But I am not sure and the solutions I've tried are not working.

```
gyp ERR! configure error 
gyp ERR! stack Error: Command failed: Traceback (most recent call last):
gyp ERR! stack   File "<string>", line 1, in <module>
gyp ERR! stack   File "/Users/EuniceKim/anaconda/lib/python2.7/platform.py", line 1510, in python_version
gyp ERR! stack     return _sys_version()[1]
gyp ERR! stack   File "/Users/EuniceKim/anaconda/lib/python2.7/platform.py", line 1465, in _sys_version
gyp ERR! stack     repr(sys_version))
gyp ERR! stack ValueError: failed to parse CPython sys.version: '2.7.5 (default, Aug 25 2013, 00:04:04) \n[GCC 4.2.1 Compatible Apple LLVM 5.0 (clang-500.0.68)]'
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:637:15)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at maybeClose (child_process.js:735:16)
gyp ERR! stack     at Socket.<anonymous> (child_process.js:948:11)
gyp ERR! stack     at Socket.EventEmitter.emit (events.js:95:17)
gyp ERR! stack     at Pipe.close (net.js:466:12)
gyp ERR! System Darwin 13.0.0
gyp ERR! command "node" "/usr/local/Cellar/node/0.10.20/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/topojson/node_modules/d3/node_modules/jsdom/node_modules/contextify
gyp ERR! node -v v0.10.20
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok 
npm ERR! Error: ENOENT, utime '/usr/local/lib/node_modules/topojson/node_modules/d3/node_modules/jsdom/node_modules/request/node_modules/mime/package.json'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 13.0.0
npm ERR! command "/usr/local/Cellar/node/0.10.20/bin/node" "/usr/local/bin/npm" "install" "-g" "topojson"
npm ERR! cwd /Users/EuniceKim
npm ERR! node -v v0.10.20
npm ERR! npm -v 1.3.11
npm ERR! path /usr/local/lib/node_modules/topojson/node_modules/d3/node_modules/jsdom/node_modules/request/node_modules/mime/package.json
npm ERR! fstream_path /usr/local/lib/node_modules/topojson/node_modules/d3/node_modules/jsdom/node_modules/request/node_modules/mime/package.json
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! fstream_finish_call utimes
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/local/Cellar/node/0.10.20/lib/node_modules/npm/node_modules/fstream/lib/writer.js:305:19
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, utime '/usr/local/lib/node_modules/topojson/node_modules/d3/node_modules/jsdom/node_modules/request/node_modules/tough-cookie/package.json'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 13.0.0
npm ERR! command "/usr/local/Cellar/node/0.10.20/bin/node" "/usr/local/bin/npm" "install" "-g" "topojson"
npm ERR! cwd /Users/EuniceKim
npm ERR! node -v v0.10.20
npm ERR! npm -v 1.3.11
npm ERR! path /usr/local/lib/node_modules/topojson/node_modules/d3/node_modules/jsdom/node_modules/request/node_modules/tough-cookie/package.json
npm ERR! fstream_path /usr/local/lib/node_modules/topojson/node_modules/d3/node_modules/jsdom/node_modules/request/node_modules/tough-cookie/package.json
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! fstream_finish_call utimes
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/local/Cellar/node/0.10.20/lib/node_modules/npm/node_modules/fstream/lib/writer.js:305:19
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, utime '/usr/local/lib/node_modules/topojson/node_modules/d3/node_modules/jsdom/node_modules/request/node_modules/http-signature/package.json'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 13.0.0
npm ERR! command "/usr/local/Cellar/node/0.10.20/bin/node" "/usr/local/bin/npm" "install" "-g" "topojson"
npm ERR! cwd /Users/EuniceKim
npm ERR! node -v v0.10.20
npm ERR! npm -v 1.3.11
npm ERR! path /usr/local/lib/node_modules/topojson/node_modules/d3/node_modules/jsdom/node_modules/request/node_modules/http-signature/package.json
npm ERR! fstream_path /usr/local/lib/node_modules/topojson/node_modules/d3/node_modules/jsdom/node_modules/request/node_modules/http-signature/package.json
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! fstream_finish_call utimes
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/local/Cellar/node/0.10.20/lib/node_modules/npm/node_modules/fstream/lib/writer.js:305:19
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat '/usr/local/lib/node_modules/topojson/node_modules/d3/node_modules/jsdom/node_modules/request/node_modules/hawk/package.json'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 13.0.0
npm ERR! command "/usr/local/Cellar/node/0.10.20/bin/node" "/usr/local/bin/npm" "install" "-g" "topojson"
npm ERR! cwd /Users/EuniceKim
npm ERR! node -v v0.10.20
npm ERR! npm -v 1.3.11
npm ERR! path /usr/local/lib/node_modules/topojson/node_modules/d3/node_modules/jsdom/node_modules/request/node_modules/hawk/package.json
npm ERR! fstream_path /usr/local/lib/node_modules/topojson/node_modules/d3/node_modules/jsdom/node_modules/request/node_modules/hawk/package.json
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/local/Cellar/node/0.10.20/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! error rolling back Error: ENOTEMPTY, rmdir '/usr/local/lib/node_modules/topojson/node_modules/d3/node_modules/jsdom/node_modules/request/node_modules/forever-agent'
npm ERR! error rolling back  jsdom@0.5.7 { [Error: ENOTEMPTY, rmdir '/usr/local/lib/node_modules/topojson/node_modules/d3/node_modules/jsdom/node_modules/request/node_modules/forever-agent']
npm ERR! error rolling back   errno: 53,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   path: '/usr/local/lib/node_modules/topojson/node_modules/d3/node_modules/jsdom/node_modules/request/node_modules/forever-agent' }
npm ERR! Error: ENOENT, open '/usr/local/lib/node_modules/topojson/node_modules/d3/node_modules/jsdom/node_modules/request/node_modules/form-data/License'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 13.0.0
npm ERR! command "/usr/local/Cellar/node/0.10.20/bin/node" "/usr/local/bin/npm" "install" "-g" "topojson"
npm ERR! cwd /Users/EuniceKim
npm ERR! node -v v0.10.20
npm ERR! npm -v 1.3.11
npm ERR! path /usr/local/lib/node_modules/topojson/node_modules/d3/node_modules/jsdom/node_modules/request/node_modules/form-data/License
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! EEXIST, mkdir '/usr/local/lib/node_modules/topojson/node_modules/d3/node_modules/jsdom/node_modules/cssstyle/lib/properties'
File exists: /usr/local/lib/node_modules/topojson/node_modules/d3/node_modules/jsdom/node_modules/cssstyle/lib/properties
Move it away, and try again. 

npm ERR! System Darwin 13.0.0
npm ERR! command "/usr/local/Cellar/node/0.10.20/bin/node" "/usr/local/bin/npm" "install" "-g" "topojson"
npm ERR! cwd /Users/EuniceKim
npm ERR! node -v v0.10.20
npm ERR! npm -v 1.3.11
npm ERR! path /usr/local/lib/node_modules/topojson/node_modules/d3/node_modules/jsdom/node_modules/cssstyle/lib/properties
npm ERR! fstream_path /usr/local/lib/node_modules/topojson/node_modules/d3/node_modules/jsdom/node_modules/cssstyle/lib/properties/elevation.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code EEXIST
npm ERR! errno 47
npm ERR! fstream_stack /usr/local/Cellar/node/0.10.20/lib/node_modules/npm/node_modules/fstream/lib/writer.js:171:23
npm ERR! fstream_stack /usr/local/Cellar/node/0.10.20/lib/node_modules/npm/node_modules/mkdirp/index.js:37:53
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, open '/usr/local/lib/node_modules/topojson/node_modules/d3/node_modules/jsdom/node_modules/request/node_modules/aws-sign2/README.md'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 13.0.0
npm ERR! command "/usr/local/Cellar/node/0.10.20/bin/node" "/usr/local/bin/npm" "install" "-g" "topojson"
npm ERR! cwd /Users/EuniceKim
npm ERR! node -v v0.10.20
npm ERR! npm -v 1.3.11
npm ERR! path /usr/local/lib/node_modules/topojson/node_modules/d3/node_modules/jsdom/node_modules/request/node_modules/aws-sign2/README.md
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! Error: ENOENT, lstat '/usr/local/lib/node_modules/topojson/node_modules/d3/node_modules/jsdom/node_modules/request/node_modules/qs/.npmignore'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 13.0.0
npm ERR! command "/usr/local/Cellar/node/0.10.20/bin/node" "/usr/local/bin/npm" "install" "-g" "topojson"
npm ERR! cwd /Users/EuniceKim
npm ERR! node -v v0.10.20
npm ERR! npm -v 1.3.11
npm ERR! path /usr/local/lib/node_modules/topojson/node_modules/d3/node_modules/jsdom/node_modules/request/node_modules/qs/.npmignore
npm ERR! fstream_path /usr/local/lib/node_modules/topojson/node_modules/d3/node_modules/jsdom/node_modules/request/node_modules/qs/.npmignore
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/local/Cellar/node/0.10.20/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, utime '/usr/local/lib/node_modules/topojson/node_modules/d3/node_modules/jsdom/node_modules/request/node_modules/forever-agent/LICENSE'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 13.0.0
npm ERR! command "/usr/local/Cellar/node/0.10.20/bin/node" "/usr/local/bin/npm" "install" "-g" "topojson"
npm ERR! cwd /Users/EuniceKim
npm ERR! node -v v0.10.20
npm ERR! npm -v 1.3.11
npm ERR! path /usr/local/lib/node_modules/topojson/node_modules/d3/node_modules/jsdom/node_modules/request/node_modules/forever-agent/LICENSE
npm ERR! fstream_path /usr/local/lib/node_modules/topojson/node_modules/d3/node_modules/jsdom/node_modules/request/node_modules/forever-agent/LICENSE
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! fstream_finish_call utimes
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/local/Cellar/node/0.10.20/lib/node_modules/npm/node_modules/fstream/lib/writer.js:305:19
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, utime '/usr/local/lib/node_modules/topojson/node_modules/d3/node_modules/jsdom/node_modules/request/node_modules/tunnel-agent/LICENSE'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 13.0.0
npm ERR! command "/usr/local/Cellar/node/0.10.20/bin/node" "/usr/local/bin/npm" "install" "-g" "topojson"
npm ERR! cwd /Users/EuniceKim
npm ERR! node -v v0.10.20
npm ERR! npm -v 1.3.11
npm ERR! path /usr/local/lib/node_modules/topojson/node_modules/d3/node_modules/jsdom/node_modules/request/node_modules/tunnel-agent/LICENSE
npm ERR! fstream_path /usr/local/lib/node_modules/topojson/node_modules/d3/node_modules/jsdom/node_modules/request/node_modules/tunnel-agent/LICENSE
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! fstream_finish_call utimes
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/local/Cellar/node/0.10.20/lib/node_modules/npm/node_modules/fstream/lib/writer.js:305:19
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, utime '/usr/local/lib/node_modules/topojson/node_modules/d3/node_modules/jsdom/node_modules/request/node_modules/oauth-sign/LICENSE'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 13.0.0
npm ERR! command "/usr/local/Cellar/node/0.10.20/bin/node" "/usr/local/bin/npm" "install" "-g" "topojson"
npm ERR! cwd /Users/EuniceKim
npm ERR! node -v v0.10.20
npm ERR! npm -v 1.3.11
npm ERR! path /usr/local/lib/node_modules/topojson/node_modules/d3/node_modules/jsdom/node_modules/request/node_modules/oauth-sign/LICENSE
npm ERR! fstream_path /usr/local/lib/node_modules/topojson/node_modules/d3/node_modules/jsdom/node_modules/request/node_modules/oauth-sign/LICENSE
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! fstream_finish_call utimes
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/local/Cellar/node/0.10.20/lib/node_modules/npm/node_modules/fstream/lib/writer.js:305:19
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! error rolling back Error: ENOTEMPTY, rmdir '/usr/local/lib/node_modules/topojson/node_modules/d3/node_modules/jsdom/node_modules/request/node_modules/json-stringify-safe'
npm ERR! error rolling back  d3@3.4.1 { [Error: ENOTEMPTY, rmdir '/usr/local/lib/node_modules/topojson/node_modules/d3/node_modules/jsdom/node_modules/request/node_modules/json-stringify-safe']
npm ERR! error rolling back   errno: 53,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   path: '/usr/local/lib/node_modules/topojson/node_modules/d3/node_modules/jsdom/node_modules/request/node_modules/json-stringify-safe' }
npm ERR! EEXIST, mkdir '/usr/local/lib/node_modules/topojson/node_modules/d3/node_modules/jsdom/node_modules/request/node_modules/node-uuid/benchmark'
File exists: /usr/local/lib/node_modules/topojson/node_modules/d3/node_modules/jsdom/node_modules/request/node_modules/node-uuid/benchmark
Move it away, and try again. 

npm ERR! System Darwin 13.0.0
npm ERR! command "/usr/local/Cellar/node/0.10.20/bin/node" "/usr/local/bin/npm" "install" "-g" "topojson"
npm ERR! cwd /Users/EuniceKim
npm ERR! node -v v0.10.20
npm ERR! npm -v 1.3.11
npm ERR! path /usr/local/lib/node_modules/topojson/node_modules/d3/node_modules/jsdom/node_modules/request/node_modules/node-uuid/benchmark
npm ERR! fstream_path /usr/local/lib/node_modules/topojson/node_modules/d3/node_modules/jsdom/node_modules/request/node_modules/node-uuid/benchmark/benchmark.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code EEXIST
npm ERR! errno 47
npm ERR! fstream_stack /usr/local/Cellar/node/0.10.20/lib/node_modules/npm/node_modules/fstream/lib/writer.js:171:23
npm ERR! fstream_stack /usr/local/Cellar/node/0.10.20/lib/node_modules/npm/node_modules/mkdirp/index.js:37:53
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! weird error 1
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/EuniceKim/npm-debug.log
npm ERR! not ok code 0
```

**Comment by smikes** [comment]
@ekimed , Is this still a problem for you?

Could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.3.11. Can you try updating your npm installation?

To update npm, run `npm -g install npm@latest`

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as abandoned!
