### ISSUE TITLE
Error: Cannot insert data into the registry without auth

### ISSUE THREAD

**Issue by gbs09288** [npm/npm#4681]
```
npm ERR! Error: Cannot insert data into the registry without auth
npm ERR!     at RegClient.regRequest [as request] (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:96:15)
npm ERR!     at RegClient.get_ (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:116:8)
npm ERR!     at RegClient.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:43:15)
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/isaacs/npm/issues>

npm ERR! System Linux 3.8.0-35-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "jitsu" "-g"
npm ERR! cwd /home/ischools-laptop79
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.24
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/ischools-laptop79/npm-debug.log
npm ERR! not ok code 0
```

**Comment by InfiniteStyles** [comment]
Is this still an issue?

**Comment by legodude17** [comment]
I don't think so but we should check with @gbs09288.
