### ISSUE TITLE
`npm init` and invalid version

### ISSUE THREAD

**Issue by utkarshkukreti** [npm/npm#4700]
If I run `npm init` and enter an invalid version, I get an error after I've entered all other fields, and I lose all the data. (Other can copying it manually from the log above.)

It should probably show the error as soon as I press return after filling an invalid version, and allow me to fill it again.

```
➜  lol  npm init
This utility will walk you through creating a package.json file.
It only covers the most common items, and tries to guess sane defaults.

See `npm help json` for definitive documentation on these fields
and exactly what they do.

Use `npm install <pkg> --save` afterwards to install a package and
save it as a dependency in the package.json file.

Press ^C at any time to quit.
name: (lol)
version: (0.0.0) 0.1
description:
entry point: (index.js)
test command:
git repository:
keywords:
author:
license: (ISC)
npm ERR! Error: Invalid version: "0.1"
npm ERR!     at Object.module.exports.fixVersionField (/Users/.../.nvm/v0.10.25/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/fixer.js:185:13)
npm ERR!     at /Users/.../.nvm/v0.10.25/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/normalize.js:29:38
npm ERR!     at Array.forEach (native)
npm ERR!     at normalize (/Users/.../.nvm/v0.10.25/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/normalize.js:28:15)
npm ERR!     at final (/Users/.../.nvm/v0.10.25/lib/node_modules/npm/node_modules/read-package-json/read-json.js:328:33)
npm ERR!     at then (/Users/.../.nvm/v0.10.25/lib/node_modules/npm/node_modules/read-package-json/read-json.js:126:33)
npm ERR!     at /Users/.../.nvm/v0.10.25/lib/node_modules/npm/node_modules/read-package-json/read-json.js:302:48
npm ERR!     at fs.js:207:20
npm ERR!     at OpenReq.Req.done (/Users/.../.nvm/v0.10.25/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:144:5)
npm ERR!     at OpenReq.done (/Users/.../.nvm/v0.10.25/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:64:22)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 13.0.0
npm ERR! command "node" "/Users/.../.nvm/v0.10.25/bin/npm" "init"
npm ERR! cwd /Users/.../lol
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.3
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/.../lol
npm ERR! not ok code 0
```

**Comment by watilde** [comment]
I tried to make the patch and [create a pull request](https://github.com/isaacs/promzard/pull/13) for `promzard ` cuz I thought this idea is nice. I hope this change make `npm init` more useful.
