### ISSUE TITLE
Unpublish package fails all the time

### ISSUE THREAD

**Issue by hyspace** [npm/npm#4701]
I mispublished a package which haven't being finished, so I tried to unpublish it. 

But error occurs when I tried to unpublish:

`npm unpublish --force lixian-xunlei.coffee@0.0.1`

```
npm WARN using --force I sure hope you know what you are doing.
npm http GET https://registry.npmjs.org/lixian-xunlei.coffee?write=true
npm http 200 https://registry.npmjs.org/lixian-xunlei.coffee?write=true
npm http DELETE https://registry.npmjs.org/lixian-xunlei.coffee/-rev/6-f4adb04467b0d252c67afe81184115fa
npm http 403 https://registry.npmjs.org/lixian-xunlei.coffee/-rev/6-f4adb04467b0d252c67afe81184115fa
npm ERR! Error: forbidden deleting docs directly not allowed.
npm ERR! Use the _update/delete method.: lixian-xunlei.coffee/-rev/6-f4adb04467b0d252c67afe81184115fa
npm ERR!     at RegClient.<anonymous> (/usr/local/share/npm/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:237:14)
npm ERR!     at Request.self.callback (/usr/local/share/npm/lib/node_modules/npm/node_modules/request/request.js:123:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/local/share/npm/lib/node_modules/npm/node_modules/request/request.js:893:14)
npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/local/share/npm/lib/node_modules/npm/node_modules/request/request.js:844:12)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 13.0.0
npm ERR! command "node" "/usr/local/bin/npm" "unpublish" "--force" "lixian-xunlei.coffee@0.0.1"
npm ERR! cwd /Users/hyspace/Projects/lixian-xunlei.coffee
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.3
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/hyspace/Projects/lixian-xunlei.coffee/npm-debug.log
npm ERR! not ok code 0
```

I tried many times and it still fails.

I'm wondering how can I unpublish it.

extra info:

Then I tried to re publish it by `npm publish --force` with version unchanged, this command works.

**Comment by smikes** [comment]
@hyspace your issue was that

```
npm unpublish --force lixian-xunlei.coffee@0.0.1
```

did not succeed but 

```
npm unpublish --force lixian-xunlei.coffee 
```

did.  From your point of view, can this issue now be closed?

@joaoafrmartins I have created a new issue to discuss your feature-request: https://github.com/npm/npm/issues/7428

**Comment by othiym23** [comment]
Closing as resolved, because this bug was reported against a completely different version of the registry architecture. If you encounter new problems with unpublishing, please open a new issue.

@joaoafrmartins Do see #7428 so you can see my explanation for why your (reasonable) request is something that the npm team will not be fulfilling, and why.
