### ISSUE TITLE
Unpublished module keeps appearing in search results (1 week after)

### ISSUE THREAD

**Issue by dpecos** [npm/npm#4848]
Hi

I unpublished a module I created, but it kept appearing in search results. Now, one week after, it still appears in search results and I can't force to unpublish it again:

```
npm search node-sermepa
npm http GET https://registry.npmjs.org/-/all/since?stale=update_after&startkey=1394205272157
npm http 200 https://registry.npmjs.org/-/all/since?stale=update_after&startkey=1394205272157
NAME         DESCRIPTION AUTHOR DATE       VERSION KEYWORDS
node-sermepa                    2014-02-24    
```

```
npm unpublish node-sermepa --force                                                                           
npm WARN using --force I sure hope you know what you are doing.
npm http GET https://registry.npmjs.org/node-sermepa?write=true
npm http 404 https://registry.npmjs.org/node-sermepa?write=true
npm http DELETE https://registry.npmjs.org/node-sermepa/-rev/7-69eee8459ff797e9948ff812ce15c876
npm http 403 https://registry.npmjs.org/node-sermepa/-rev/7-69eee8459ff797e9948ff812ce15c876
npm ERR! Error: forbidden already unpublished: node-sermepa/-rev/7-69eee8459ff797e9948ff812ce15c876
npm ERR!     at RegClient.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:237:14)
npm ERR!     at Request.self.callback (/usr/lib/node_modules/npm/node_modules/request/request.js:123:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/lib/node_modules/npm/node_modules/request/request.js:893:14)
npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/lib/node_modules/npm/node_modules/request/request.js:844:12)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.11.0-18-generic
npm ERR! command "node" "/usr/bin/npm" "unpublish" "node-sermepa" "--force"
npm ERR! cwd /devel/projects/redsys
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.4
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /devel/projects/redsys/npm-debug.log
npm ERR! not ok code 0
```

Thank you!

**Comment by JohnMcLear** [comment]
+1

**Comment by Gared** [comment]
You also get unpublished plugins with this command:
npm.commands.search
This is really a big problem!

**Comment by smikes** [comment]
This is an interesting bug.  The `node-sermepa` module is still present in the `/-/all` data, but is not found by an `npm view`:

```
$ npm-kludge-search node-sermepa
NAME         DESCRIPTION AUTHOR DATE       VERSION KEYWORDS
node-sermepa                    2014-03-13                 
Found packages: 1
$ npm view node-sermepa
npm http request GET https://registry.npmjs.org/node-sermepa
npm http 404 https://registry.npmjs.org/node-sermepa
```

I was able to publish to the name `node-sermepa` and subsequently unpublish as well.  So now that package is listed as unpublished by me.

I think this ties in with another feature request, that certain modules should be excluded by default from `npm search` results, and only included if a flag such as --all or --no-hide is given.  Modules with no installable tarballs should qualify.

Ref #6016, the general search improvement case.  Also relevant to npm-registry-couchapp which is where the `listAll` view is implemented.

**Comment by smikes** [comment]
The search case I was thinking of with the "hide by default" flag was #6107

**Comment by unframework** [comment]
+1

**Comment by julmot** [comment]
:+1: I hate npm :bowtie:
