### ISSUE TITLE
publish error

### ISSUE THREAD

**Issue by choiks14** [npm/npm#4972]
npm publish 

but i get errors.
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'publish' ]
2 info using npm@1.3.17
3 info using node@v0.10.23
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 verbose publish [ '.' ]
6 verbose cache add [ '.', null ]
7 verbose cache add name=undefined spec="." args=[".",null]
8 verbose parsed url { protocol: null,
8 verbose parsed url   slashes: null,
8 verbose parsed url   auth: null,
8 verbose parsed url   host: null,
8 verbose parsed url   port: null,
8 verbose parsed url   hostname: null,
8 verbose parsed url   hash: null,
8 verbose parsed url   search: null,
8 verbose parsed url   query: null,
8 verbose parsed url   pathname: '.',
8 verbose parsed url   path: '.',
8 verbose parsed url   href: '.' }
9 silly lockFile 3a52ce78- .
10 verbose lock . C:\Users\choiks14\AppData\Roaming\npm-cache\3a52ce78-.lock
11 silly lockFile 3a52ce78- .
12 silly lockFile 3a52ce78- .
13 error addLocal Could not install .
14 error Error: Adding a cache directory to the cache will make the world implode.
14 error     at addLocalDirectory (C:\Program Files\nodejs\node_modules\npm\lib\cache.js:1120:45)
14 error     at C:\Program Files\nodejs\node_modules\npm\lib\cache.js:837:28
14 error     at Object.oncomplete (fs.js:107:15)
15 error If you need help, you may report this *entire* log,
15 error including the npm and node versions, at:
15 error     <http://github.com/isaacs/npm/issues>
16 error System Windows_NT 6.1.7601
17 error command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "publish"
18 error cwd D:\workspace\template\generator-webapp-assemble
19 error node -v v0.10.23
20 error npm -v 1.3.17
21 verbose exit [ 1, true ]
```

**Comment by smikes** [comment]
Is this still a problem for you?

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.3.17. Can you try updating your npm installation?

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as resolved / abandoned.
