### ISSUE TITLE
"npm adduser" fails.

### ISSUE THREAD

**Issue by crocket** [npm/npm#4998]
I can log in https://www.npmjs.org as "crocket", but "npm adduser" exits with errors as below.

```bash
$ npm adduser
Username: (cornfuse) crocket
Password: 
Email: (this IS public) (crockabiscuit@gmail.com) crockabiscuit@gmail.com
npm http PUT https://registry.npmjs.org/-/user/org.couchdb.user:crocket
npm http 409 https://registry.npmjs.org/-/user/org.couchdb.user:crocket
npm http GET https://registry.npmjs.org/-/user/org.couchdb.user:crocket?write=true
npm http 200 https://registry.npmjs.org/-/user/org.couchdb.user:crocket?write=true
npm http PUT https://registry.npmjs.org/-/user/org.couchdb.user:crocket/-rev/7-89b7b516e596015c03d050537dc4562c
npm http 401 https://registry.npmjs.org/-/user/org.couchdb.user:crocket/-rev/7-89b7b516e596015c03d050537dc4562c
npm WARN adduser Incorrect username or password
npm WARN adduser You can reset your account by visiting:
npm WARN adduser 
npm WARN adduser     https://npmjs.org/forgot
npm WARN adduser 
npm ERR! Error: unauthorized Name or password is incorrect.: -/user/org.couchdb.user:crocket/-rev/7-89b7b516e596015c03d050537dc4562c
npm ERR!     at RegClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:254:14)
npm ERR!     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:192:65)
npm ERR!     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:123:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:893:14)
npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:844:12)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:910:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.11.0-19-generic
npm ERR! command "node" "/usr/local/bin/npm" "adduser"
npm ERR! cwd /home/crocket
npm ERR! node -v v0.10.15
npm ERR! npm -v 1.4.6
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/crocket/npm-debug.log
npm ERR! not ok code 0
```

**Comment by othiym23** [comment]
Closing as resolved.
