### ISSUE TITLE
error registry error parsing json. see npm-debug.log

### ISSUE THREAD

**Issue by wyattbiker** [npm/npm#5004]
I get this error when I try to npm install anypackage. I have setup the proxy and registry and all the other stuff. It is behind  proxy. The only way I can install packages is to run the installer on an a workstation not behind proxy and then copy the folder.

Here is the debug. Any ideas?
!!!
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'ws' ]
2 info using npm@1.4.3
3 info using node@v0.10.26
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 verbose cache add [ 'ws', null ]
6 verbose cache add name=undefined spec="ws" args=["ws",null]
7 verbose parsed url { protocol: null,
7 verbose parsed url   slashes: null,
7 verbose parsed url   auth: null,
7 verbose parsed url   host: null,
7 verbose parsed url   port: null,
7 verbose parsed url   hostname: null,
7 verbose parsed url   hash: null,
7 verbose parsed url   search: null,
7 verbose parsed url   query: null,
7 verbose parsed url   pathname: 'ws',
7 verbose parsed url   path: 'ws',
7 verbose parsed url   href: 'ws' }
8 silly lockFile 1457b75d-ws ws
9 verbose lock ws C:\Users\myuser1\AppData\Roaming\npm-cache\1457b75d-ws.lock
10 silly lockFile 1457b75d-ws ws
11 silly lockFile 1457b75d-ws ws
12 verbose addNamed [ 'ws', '' ]
13 verbose addNamed [ null, '*' ]
14 silly lockFile e88fe629-ws ws@
15 verbose lock ws@ C:\Users\myuser1\AppData\Roaming\npm-cache\e88fe629-ws.lock
16 silly addNameRange { name: 'ws', range: '*', hasData: false }
17 verbose url raw ws
18 verbose url resolving [ 'http://registry.npmjs.org/', './ws' ]
19 verbose url resolved http://registry.npmjs.org/ws
20 info trying registry request attempt 1 at 14:20:13
21 http GET http://registry.npmjs.org/ws
22 http 404 http://registry.npmjs.org/ws
23 verbose bad json <html>
23 verbose bad json <head>
23 verbose bad json <title>Error 404 - Object Not Found</title>
23 verbose bad json </head>
23 verbose bad json
23 verbose bad json <body>
23 verbose bad json
23 verbose bad json <img src="/error/images/someimg.gif" alt="IMG Banner" border="0">
23 verbose bad json
23 verbose bad json <hr size="10%" width="100%" color="red">
23 verbose bad json <h1>Object Not Found!</h1>
23 verbose bad json
23 verbose bad json <p> The requested URL was not found on this server. If you entered the URL manually please check your spelling and try again. </p>
23 verbose bad json
23 verbose bad json <p>If you think this is unusual, please try later or contact the <b>HELPDESK</b> @ 1-888-123-4567 to the helpdesk representative to open a ticket.
23 verbose bad json <h2>Error (404)</h2>
23 verbose bad json
23 verbose bad json <hr size="10%" width="100%" color="red">
23 verbose bad json </body>
23 verbose bad json </html>
24 error registry error parsing json
25 silly registry.get cb [ 404,
25 silly registry.get   { date: 'Thu, 03 Apr 2014 18:20:13 GMT',
25 silly registry.get     server: 'Apache/2.0.46 (Red Hat)',
25 silly registry.get     'last-modified': 'Thu, 06 Jan 2005 21:26:03 GMT',
25 silly registry.get     etag: '"cfdf2e-278-bfc4d0c0"',
25 silly registry.get     'accept-ranges': 'bytes',
25 silly registry.get     'content-length': '632',
25 silly registry.get     connection: 'close',
25 silly registry.get     'content-type': 'text/html; charset=UTF-8' } ]
26 silly lockFile e88fe629-ws ws@
27 silly lockFile e88fe629-ws ws@
28 error SyntaxError: Unexpected token <
28 error <html>
28 error <head>
28 error <title>Error 404 - Object Not Found</title>
28 error </head>
28 error
28 error <body>
28 error
28 error <img src="/error/images/myimg.gif" alt="img Banner" border="0">
28 error
28 error <hr size="10%" width="100%" color="red">
28 error <h1>Object Not Found!</h1>
28 error
28 error <p> The requested URL was not found on this server. If you entered the URL manually please check your spelling and try again. </p>
28 error
28 error <p>If you think this is unusual, please try later or contact the <b>HELPDESK</b> @ to the helpdesk representative to open a ticket.
28 error <h2>Error (404)</h2>
28 error
28 error <hr size="10%" width="100%" color="red">
28 error </body>
28 error </html>
28 error
28 error     at Object.parse (native)
28 error     at RegClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:203:23)
28 error     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:123:22)
28 error     at Request.EventEmitter.emit (events.js:98:17)
28 error     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:893:14)
28 error     at Request.EventEmitter.emit (events.js:117:20)
28 error     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:844:12)
28 error     at IncomingMessage.EventEmitter.emit (events.js:117:20)
28 error     at _stream_readable.js:920:16
28 error     at process._tickCallback (node.js:415:13)
29 error If you need help, you may report this *entire* log,
29 error including the npm and node versions, at:
29 error     <http://github.com/npm/npm/issues>
30 error System Windows_NT 6.1.7601
31 error command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "ws"
32 error cwd C:\Users\myuser1\myapp\octest
33 error node -v v0.10.26
34 error npm -v 1.4.3
35 error type unexpected_token
36 verbose exit [ 1, true ]
```

**Comment by smikes** [comment]
Is this still a problem for you?

It looks like your proxy settings are not working.  In any case, you are getting an HTML document instead of the data `npm` is expecting from the registry.

When your `http_proxy` environment variable is set, can you use `curl` to fetch a result from the npm registry?

```
$ echo $http_proxy    # this should output something like http://user:pass@proxy.host:port
$ curl https://registry.npmjs.org/npm | wc  # wc should output something like 0   19334 1905108
$ npm view npm | wc
npm http request GET https://registry.npmjs.org/npm
npm http 304 https://registry.npmjs.org/npm
     752    1459   2736
```

Those should all work if you have a correct `http_proxy` variable.

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.4.3. Can you try updating your npm installation?

To update npm, run `npm -g install npm@latest`

For some Linux distributions (Debian/Ubuntu and RedHat/CentOS), the latest node version provided by the distribution may lag behind the stable version. [Here are instructions from NodeSource](https://github.com/nodesource/distributions) on getting the latest node.

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as resolved / abandoned.
