### ISSUE TITLE
Reset password works once

### ISSUE THREAD

**Issue by Mulkave** [npm/npm#5022]
After resetting my password twice, every time i log out it never lets me in again with the new password, neither from the terminal using ```npm login`` or ```npm adduser```

```
Username: vinelab
Password: 
Email:
npm http PUT https://registry.npmjs.org/-/user/org.couchdb.user:vinelab
npm http 409 https://registry.npmjs.org/-/user/org.couchdb.user:vinelab
npm http GET https://registry.npmjs.org/-/user/org.couchdb.user:vinelab
npm http 401 https://registry.npmjs.org/-/user/org.couchdb.user:vinelab
npm WARN adduser Incorrect username or password
npm WARN adduser You can reset your account by visiting:
npm WARN adduser 
npm WARN adduser     http://admin.npmjs.org/reset
npm WARN adduser 
npm ERR! Error: unauthorized Name or password is incorrect.: -/user/org.couchdb.user:vinelab
npm ERR!     at RegClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:272:14)
npm ERR!     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/index.js:148:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/index.js:876:14)
npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/index.js:827:12)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:910:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 13.1.0
npm ERR! command "node" "/usr/local/bin/npm" "login"
npm ERR! cwd /Users/Mulkave/Developer/Vinelab/Library/generator-tom
npm ERR! node -v v0.10.15
npm ERR! npm -v 1.3.5
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/Mulkave/Developer/Vinelab/Library/generator-tom/npm-debug.log
npm ERR! not ok code 0
```

**Comment by smikes** [comment]
@Mulkave , Is this still a problem for you?

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.3.5. Can you try updating your npm installation?

To update npm, run `npm -g install npm@latest`

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by Mulkave** [comment]
Seems to have been solved, I can now login after resetting my password. Thanks!
