### ISSUE TITLE
npm install websockify returns meta data but file failed to fetch

### ISSUE THREAD

**Issue by davidje** [npm/npm#5120]
Looks like there is a missing package file for the node version of websockify:

```
$ npm install websockify
npm http GET https://registry.npmjs.org/websockify
npm http 304 https://registry.npmjs.org/websockify
npm http GET https://registry.npmjs.org/websockify/-/websockify-0.6.0.tgz
npm http 404 https://registry.npmjs.org/websockify/-/websockify-0.6.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/websockify/-/websockify-0.6.0.tgz
npm ERR! Error: 404 Not Found
npm ERR!     at WriteStream.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/fetch.js:57:12)
npm ERR!     at WriteStream.EventEmitter.emit (events.js:117:20)
npm ERR!     at fs.js:1596:14
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:103:5
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/isaacs/npm/issues>

npm ERR! System Linux 3.11.0-18-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "websockify"
npm ERR! cwd /home/david/dev
npm ERR! node -v v0.10.24
npm ERR! npm -v 1.3.21
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/david/dev/npm-debug.log
npm ERR! not ok code 0
```

```
 wget https://registry.npmjs.org/websockify/-/websockify-0.6.0.tgz
--2014-04-21 09:49:52--  https://registry.npmjs.org/websockify/-/websockify-0.6.0.tgz
Resolving registry.npmjs.org (registry.npmjs.org)... 199.27.79.162
Connecting to registry.npmjs.org (registry.npmjs.org)|199.27.79.162|:443... connected.
HTTP request sent, awaiting response... 404 Object Not Found
2014-04-21 09:49:53 ERROR 404: Object Not Found.
```

**Comment by busches** [comment]
@othiym23 any updates on what happened with this issue? `websockify` has since published a new version.
