### ISSUE TITLE
spawn ENOENT error for some modules when running npm install

### ISSUE THREAD

**Issue by mahatmawilley** [npm/npm#5165]
When running npm install on my project (on Win7 64bit) I am getting the errors below. Any idea what could be causing this?
```
phantomjs@1.9.7-5 install c:\Users\mark.willey\stashcheckouts\ui-core\node_modules\karma-phantomjs-launcher\node_modules\phantomjs
> node install.js

npm ERR! Error: spawn ENOENT
npm ERR!     at errnoException (child_process.js:980:11)
npm ERR!     at Process.ChildProcess._handle.onexit (child_process.js:771:34)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd c:\Users\mark.willey\stashcheckouts\ui-core
npm ERR! node -v v0.10.21
npm ERR! npm -v 1.3.11
npm ERR! syscall spawn
npm ERR! code ENOENT
npm ERR! errno ENOENT

closurecompiler@1.3.0 install c:\Users\mark.willey\stashcheckouts\ui-core\node_modules\gulp-closure-compiler\node_modules\closurecompiler
> npm run-script configure

npm ERR! Error: spawn ENOENT
npm ERR!     at errnoException (child_process.js:980:11)
npm ERR!     at Process.ChildProcess._handle.onexit (child_process.js:771:34)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd c:\Users\mark.willey\stashcheckouts\ui-core
npm ERR! node -v v0.10.21
npm ERR! npm -v 1.3.11
npm ERR! syscall spawn
npm ERR! code ENOENT
npm ERR! errno ENOENT

 ws@0.4.31 install c:\Users\mark.willey\stashcheckouts\ui-core\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

npm ERR! Error: spawn ENOENT
npm ERR!     at errnoException (child_process.js:980:11)
npm ERR!     at Process.ChildProcess._handle.onexit (child_process.js:771:34)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd c:\Users\mark.willey\stashcheckouts\ui-core
npm ERR! node -v v0.10.21
npm ERR! npm -v 1.3.11
npm ERR! syscall spawn
npm ERR! code ENOENT
npm ERR! errno ENOENT
```

**Comment by smikes** [comment]
@mahatmawilley Is this still a problem for you?

It looks like building native binaries was failing on your windows system -- did you have both Python 2.x and Visual Studio 2012 or higher installed?

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.3.11. Can you try updating your npm installation?

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as resolved / abandoned.
