### ISSUE TITLE
Could not install from non-lowercase git+ssh url

### ISSUE THREAD

**Issue by dmitrig01** [npm/npm#5193]
I have an ssh config set so that a the host 'Kindred-ORM' uses user: git, host: github.com, and a specific private key.

```
$ npm install --verbose
npm info it worked if it ends with ok
npm verb cli [ 'node', '/usr/local/bin/npm', 'install', '--verbose' ]
npm info using npm@1.4.9
npm info using node@v0.10.26
npm verb readDependencies using package.json deps
...
npm verb cache add [ 'Kindred-ORM@git+ssh://Kindred-ORM:KindredPrints/Kindred-ORM.git#master',
npm verb cache add   null ]
npm verb cache add name=undefined spec="Kindred-ORM@git+ssh://Kindred-ORM:KindredPrints/Kindred-ORM.git#master" args=["Kindred-ORM@git+ssh://Kindred-ORM:KindredPrints/Kindred-ORM.git#master",null]
npm verb parsed url { protocol: null,
npm verb parsed url   slashes: null,
npm verb parsed url   auth: null,
npm verb parsed url   host: null,
npm verb parsed url   port: null,
npm verb parsed url   hostname: null,
npm verb parsed url   hash: '#master',
npm verb parsed url   search: null,
npm verb parsed url   query: null,
npm verb parsed url   pathname: 'Kindred-ORM@git+ssh://Kindred-ORM:KindredPrints/Kindred-ORM.git',
npm verb parsed url   path: 'Kindred-ORM@git+ssh://Kindred-ORM:KindredPrints/Kindred-ORM.git',
npm verb parsed url   href: 'Kindred-ORM@git+ssh://Kindred-ORM:KindredPrints/Kindred-ORM.git#master' }
...
npm verb cache add name="Kindred-ORM" spec="git+ssh://Kindred-ORM:KindredPrints/Kindred-ORM.git#master" args=["Kindred-ORM","git+ssh://Kindred-ORM:KindredPrints/Kindred-ORM.git#master"]
npm verb parsed url { protocol: 'git+ssh:',
npm verb parsed url   slashes: true,
npm verb parsed url   auth: null,
npm verb parsed url   host: 'kindred-orm',
npm verb parsed url   port: null,
npm verb parsed url   hostname: 'kindred-orm',
npm verb parsed url   hash: '#master',
npm verb parsed url   search: null,
npm verb parsed url   query: null,
npm verb parsed url   pathname: '/:KindredPrints/Kindred-ORM.git',
npm verb parsed url   path: '/:KindredPrints/Kindred-ORM.git',
npm verb parsed url   href: 'git+ssh://kindred-orm/:KindredPrints/Kindred-ORM.git#master' }
npm verb lock Kindred-ORM:KindredPrints/Kindred-ORM.git /home/ubuntu/.npm/6d75177c-RM-KindredPrints-Kindred-ORM-git.lock
...
npm verb addRemoteGit [ 'Kindred-ORM:KindredPrints/Kindred-ORM.git', 'master' ]
npm verb git remote.origin.url Kindred-ORM:KindredPrints/Kindred-ORM.git
npm verb git fetch -a origin (Kindred-ORM:KindredPrints/Kindred-ORM.git) 
npm verb git rev-list -n1 master b6ff3cecd5a6c5d36a5cc20759da23d0fd40d389
npm ERR! TypeError: Cannot call method 'charAt' of undefined
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:612:18
npm ERR!     at ChildProcess.exithandler (child_process.js:635:7)
npm ERR!     at ChildProcess.EventEmitter.emit (events.js:98:17)
npm ERR!     at maybeClose (child_process.js:743:16)
npm ERR!     at Process.ChildProcess._handle.onexit (child_process.js:810:5)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.2.0-58-virtual
npm ERR! command "node" "/usr/local/bin/npm" "install" "--verbose"
npm ERR! cwd /var/kindred/Kindred-API
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.9
npm ERR! type non_object_property_call
npm verb exit [ 1, true ]
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /var/kindred/Kindred-API/npm-debug.log
npm ERR! not ok code 0
```

**Comment by busches** [comment]
@dmitrig01 are you still seeing this issue in the latest version of `npm@2` or `npm@3`?
