### ISSUE TITLE
Can not install coffeescript using npm on Windows XP

### ISSUE THREAD

**Issue by hatsevich** [npm/npm#5205]
I installed Node.js (using windows intaller from http://nodejs.org) with npm. Then I typed
```
npm install -g coffee-script
```

Here is npm-debug.log
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\nodejs\\\\node.exe',
1 verbose cli   'C:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'coffee-script' ]
2 info using npm@1.4.9
3 info using node@v0.10.28
4 verbose node symlink C:\nodejs\\node.exe
5 verbose cache add [ 'coffee-script', null ]
6 verbose cache add name=undefined spec="coffee-script" args=["coffee-script",null]
7 verbose parsed url { protocol: null,
7 verbose parsed url   slashes: null,
7 verbose parsed url   auth: null,
7 verbose parsed url   host: null,
7 verbose parsed url   port: null,
7 verbose parsed url   hostname: null,
7 verbose parsed url   hash: null,
7 verbose parsed url   search: null,
7 verbose parsed url   query: null,
7 verbose parsed url   pathname: 'coffee-script',
7 verbose parsed url   path: 'coffee-script',
7 verbose parsed url   href: 'coffee-script' }
8 silly lockFile ab358269-coffee-script coffee-script
9 verbose lock coffee-script C:\Documents and Settings\Администратор\Application Data\npm-cache\ab358269-coffee-script.lock
10 silly lockFile ab358269-coffee-script coffee-script
11 silly lockFile ab358269-coffee-script coffee-script
12 verbose addNamed [ 'coffee-script', '' ]
13 verbose addNamed [ null, '*' ]
14 silly lockFile 53951495-coffee-script coffee-script@
15 verbose lock coffee-script@ C:\Documents and Settings\Администратор\Application Data\npm-cache\53951495-coffee-script.lock
16 silly addNameRange { name: 'coffee-script', range: '*', hasData: false }
17 verbose url raw coffee-script
18 verbose url resolving [ 'https://registry.npmjs.org/', './coffee-script' ]
19 verbose url resolved https://registry.npmjs.org/coffee-script
20 info trying registry request attempt 1 at 18:08:29
21 http GET https://registry.npmjs.org/coffee-script
22 info retry will retry, error on last attempt: Error: connect EAFNOSUPPORT
23 info trying registry request attempt 2 at 18:08:39
24 http GET https://registry.npmjs.org/coffee-script
25 info retry will retry, error on last attempt: Error: connect EAFNOSUPPORT
26 info trying registry request attempt 3 at 18:09:39
27 http GET https://registry.npmjs.org/coffee-script
28 silly lockFile 53951495-coffee-script coffee-script@
29 silly lockFile 53951495-coffee-script coffee-script@
30 error Error: connect EAFNOSUPPORT
30 error     at errnoException (net.js:904:11)
30 error     at connect (net.js:766:19)
30 error     at net.js:845:9
30 error     at asyncCallback (dns.js:68:16)
30 error     at Object.onanswer [as oncomplete] (dns.js:121:9)
31 error If you need help, you may report this *entire* log,
31 error including the npm and node versions, at:
31 error     <http://github.com/npm/npm/issues>
32 error System Windows_NT 5.1.2600
33 error command "C:\\nodejs\\\\node.exe" "C:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "coffee-script"
34 error cwd C:\Documents and Settings\Администратор
35 error node -v v0.10.28
36 error npm -v 1.4.9
37 error syscall connect
38 error code EAFNOSUPPORT
39 error errno EAFNOSUPPORT
40 verbose exit [ 1, true ]
```
What is the problem and what should I do?

**Comment by smikes** [comment]
@hatsevich , Is this still a problem for you?

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.4.9. Can you try updating your npm installation?

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as abandoned.
