### ISSUE TITLE
npm install issue

### ISSUE THREAD

**Issue by nathansabo** [npm/npm#5211]
Here is the error message I get:

```
Last login: Tue May  6 10:00:09 on ttys000
Design-1:~ Nathan.Sabo$ cd /Users/Nathan.Sabo/Work/Web\ site\ stuff/PAT\ with\ Grunt 
Design-1:PAT with Grunt Nathan.Sabo$ npm install
npm WARN package.json PAT-with-Grunt@0.1.0 No description
npm WARN package.json PAT-with-Grunt@0.1.0 No repository field.
npm WARN package.json PAT-with-Grunt@0.1.0 No README data
npm ERR! Error: Attempt to unlock grunt@~0.4.1, which hasn't been locked
npm ERR!     at unlock (/usr/local/lib/node_modules/npm/lib/cache.js:1434:11)
npm ERR!     at cb (/usr/local/lib/node_modules/npm/lib/cache.js:675:5)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:684:20
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:1412:20
npm ERR!     at afterMkdir (/usr/local/lib/node_modules/npm/lib/cache.js:1085:14)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:37:53
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 13.1.0
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/Nathan.Sabo/Work/Web site stuff/PAT with Grunt
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/Nathan.Sabo/Work/Web site stuff/PAT with Grunt/npm-debug.log
npm ERR! not ok code 0
```

**Comment by smikes** [comment]
Is this still a problem for you?

Can you try installing a new `node` distribution (0.10.36 is now available) and then updating the `npm` with `sudo npm install -g npm@latest`?

Again, if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as abandoned.
