### ISSUE TITLE
"npm update" fails with a git connection error; but "git clone" works fine?

### ISSUE THREAD

**Issue by DanTup** [npm/npm#5244]
When running "npm update" in a project, I get the following error:

```
9521 info install active-x-obfuscator@0.0.1
9522 info postinstall active-x-obfuscator@0.0.1
9523 error git clone git://github.com/michaelficarra/cscodegen.git Cloning into bare repository 'C:\Users\DTuppeny\AppData\Roaming\npm-cache\_git-remotes\git-github-com-michaelficarra-cscodegen-git-c4b567f3'...
9523 error git clone git://github.com/michaelficarra/cscodegen.git fatal: unable to connect to github.com:
9523 error git clone git://github.com/michaelficarra/cscodegen.git github.com[0: 192.30.252.131]: errno=No error
9524 silly lockFile c4b567f3-com-michaelficarra-cscodegen-git git://github.com/michaelficarra/cscodegen.git
9525 silly lockFile c4b567f3-com-michaelficarra-cscodegen-git git://github.com/michaelficarra/cscodegen.git
9526 error Error: Command failed: Cloning into bare repository 'C:\Users\DTuppeny\AppData\Roaming\npm-cache\_git-remotes\git-github-com-michaelficarra-cscodegen-git-c4b567f3'...
9526 error fatal: unable to connect to github.com:
9526 error github.com[0: 192.30.252.131]: errno=No error
9526 error
9526 error
9526 error     at ChildProcess.exithandler (child_process.js:637:15)
9526 error     at ChildProcess.EventEmitter.emit (events.js:98:17)
9526 error     at maybeClose (child_process.js:743:16)
9526 error     at Socket.<anonymous> (child_process.js:956:11)
9526 error     at Socket.EventEmitter.emit (events.js:95:17)
9526 error     at Pipe.close (net.js:465:12)
```

(GH won't let me attach the full log; but it's 1.8MB, so I don't want to paste it in here - I don't think anything else in there is relevant?)

I think it's a connection/proxy issue; however when I execute:

```> git clone git://github.com/michaelficarra/cscodegen.git```

It clones fine:

```
Cloning into 'cscodegen'...
remote: Reusing existing pack: 261, done.
remote: Total 261 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (261/261), 59.38 KiB | 0 bytes/s, done.
Resolving deltas: 100% (111/111), done.
Checking connectivity... done.
```

How can I debug this further? It's not clear what npm is doing differently to my clone; it would be useful if the error included an exact command I could run that shows the problem outside of npm.

**Comment by othiym23** [comment]
@smikes I will do this if you file the feature request bits as a separate issue, so we don't conflate support issues and feature requests and cause my brain to explode.

**Comment by smikes** [comment]
It shall be done!

**Comment by othiym23** [comment]
Closing as resolved.
