### ISSUE TITLE
npm 1.4.9 error (node 0.10.28)

### ISSUE THREAD

**Issue by mnrendra** [npm/npm#5296]
```
npm ERR! Error: shasum check failed for C:\Users\MYNAME~1\AppData\Local\Temp\npm-3484-jAfbaBV7\1400401519820-0.5568854345474392\tmp.tgz
npm ERR! Expected: a567c2af000ad22dc8f2a653d91978ae1f5316f4
npm ERR! Actual:   f4b6876b75397b048de86039981d9110da737007
npm ERR! From:     https://registry.npmjs.org/multiparty/-/multiparty-2.2.0.tgz
npm ERR!     at C:\Program Files\nodejs\node_modules\npm\node_modules\sha\index.js:38:8
npm ERR!     at ReadStream.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\sha\index.js:85:7)
npm ERR!     at ReadStream.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:919:16
npm ERR!     at process._tickCallback (node.js:419:13)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "connect"
npm ERR! cwd C:\connect
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\connect\npm-debug.log
npm ERR! not ok code 0
```

**Comment by smikes** [comment]
Is this still a problem for you?

Could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.4.9. Can you try updating your npm installation?

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as abandoned.
