### ISSUE TITLE
Unpublish error: forbidden _npmUser.name must match user.name

### ISSUE THREAD

**Issue by afc163** [npm/npm#5317]
```
$  npm unpublish spm@3.0.0                           
npm ERR! unpublish Failed to update data
npm ERR! Error: forbidden _npmUser.name must match user.name: 2.0.0-b1: spm/-rev/422-699b2b5612f3e06ad098df49f82ea84a
npm ERR!     at RegClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:274:14)
npm ERR!     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:212:65)
npm ERR!     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:123:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:893:14)
npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:844:12)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:919:16
npm ERR!     at process._tickCallback (node.js:419:13)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 13.1.0
npm ERR! command "node" "/usr/local/bin/npm" "unpublish" "spm@3.0.0"
npm ERR! cwd /Users/afc163/Projects/test
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.11
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/afc163/Projects/test/npm-debug.log
npm ERR! not ok code 0
```

npm-debug.log:

```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'unpublish', 'spm@3.0.0' ]
2 info using npm@1.4.11
3 info using node@v0.10.28
4 verbose url raw spm?write=true
5 verbose url resolving [ 'https://registry.npmjs.org/', './spm?write=true' ]
6 verbose url resolved https://registry.npmjs.org/spm?write=true
7 info trying registry request attempt 1 at 14:30:08
8 http GET https://registry.npmjs.org/spm?write=true
9 http 200 https://registry.npmjs.org/spm?write=true
10 silly registry.get cb [ 200,
10 silly registry.get   { date: 'Fri, 23 May 2014 06:30:09 GMT',
10 silly registry.get     server: 'CouchDB/1.5.0 (Erlang OTP/R14B04)',
10 silly registry.get     etag: '"A042PCQR37B96UYB0EYN4PW1R"',
10 silly registry.get     'content-type': 'application/json',
10 silly registry.get     'cache-control': 'max-age=0',
10 silly registry.get     'content-length': '146907',
10 silly registry.get     'accept-ranges': 'bytes',
10 silly registry.get     via: '1.1 varnish',
10 silly registry.get     age: '0',
10 silly registry.get     'x-served-by': 'cache-ty67-TYO',
10 silly registry.get     'x-cache': 'MISS',
10 silly registry.get     'x-cache-hits': '0',
10 silly registry.get     'x-timer': 'S1400826609.342106,VS0,VE534',
10 silly registry.get     vary: 'Accept',
10 silly registry.get     'keep-alive': 'timeout=10, max=50',
10 silly registry.get     connection: 'Keep-Alive' } ]
11 verbose unpublish removing attachments { shasum: '6b10f0a3f4da62dea8c907798faf6e66fbd34701',
11 verbose unpublish   tarball: 'http://registry.npmjs.org/spm/-/spm-3.0.0.tgz' }
12 verbose url raw spm/-rev/422-699b2b5612f3e06ad098df49f82ea84a
13 verbose url resolving [ 'https://registry.npmjs.org/',
13 verbose url resolving   './spm/-rev/422-699b2b5612f3e06ad098df49f82ea84a' ]
14 verbose url resolved https://registry.npmjs.org/spm/-rev/422-699b2b5612f3e06ad098df49f82ea84a
15 info trying registry request attempt 1 at 14:30:11
16 http PUT https://registry.npmjs.org/spm/-rev/422-699b2b5612f3e06ad098df49f82ea84a
17 http 403 https://registry.npmjs.org/spm/-rev/422-699b2b5612f3e06ad098df49f82ea84a
18 verbose headers { date: 'Fri, 23 May 2014 06:30:13 GMT',
18 verbose headers   server: 'CouchDB/1.5.0 (Erlang OTP/R14B04)',
18 verbose headers   'content-type': 'application/json',
18 verbose headers   'cache-control': 'max-age=1',
18 verbose headers   'content-length': '78',
18 verbose headers   'accept-ranges': 'bytes',
18 verbose headers   via: '1.1 varnish',
18 verbose headers   'x-served-by': 'cache-ty67-TYO',
18 verbose headers   'x-cache': 'MISS',
18 verbose headers   'x-cache-hits': '0',
18 verbose headers   'x-timer': 'S1400826612.180736,VS0,VE1108',
18 verbose headers   'keep-alive': 'timeout=10, max=50',
18 verbose headers   connection: 'Keep-Alive' }
19 error unpublish Failed to update data
20 error Error: forbidden _npmUser.name must match user.name: 2.0.0-b1: spm/-rev/422-699b2b5612f3e06ad098df49f82ea84a
20 error     at RegClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:274:14)
20 error     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:212:65)
20 error     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:123:22)
20 error     at Request.EventEmitter.emit (events.js:98:17)
20 error     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:893:14)
20 error     at Request.EventEmitter.emit (events.js:117:20)
20 error     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:844:12)
20 error     at IncomingMessage.EventEmitter.emit (events.js:117:20)
20 error     at _stream_readable.js:919:16
20 error     at process._tickCallback (node.js:419:13)
21 error If you need help, you may report this *entire* log,
21 error including the npm and node versions, at:
21 error     <http://github.com/npm/npm/issues>
22 error System Darwin 13.1.0
23 error command "node" "/usr/local/bin/npm" "unpublish" "spm@3.0.0"
24 error cwd /Users/afc163/Projects/test
25 error node -v v0.10.28
26 error npm -v 1.4.11
27 verbose exit [ 1, true ]
```

I can't understand why it check npmUser with 2.0.0-b1 rather than 3.0.0.

**Comment by smikes** [comment]
Is this still a problem for you?

I notice that the package `spm` is now on a much later version (3.3.4) and of course `npm` is too.  There have also been registry changes since July 2014.

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as resolved / abandoned.
