### ISSUE TITLE
Error installing forever on Centos

### ISSUE THREAD

**Issue by khurramijazm** [npm/npm#5456]
```
npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"v0.10.2                                                                                        8","npm":"1.3.6"})
npm http GET https://registry.npmjs.org/combined-stream
npm http 304 https://registry.npmjs.org/combined-stream
npm http GET https://registry.npmjs.org/delayed-stream/0.0.5
npm http 200 https://registry.npmjs.org/delayed-stream/0.0.5
npm ERR! registry error parsing json
npm ERR! Error: ENOENT, lstat '/usr/lib/node_modules/forever/node_modules/foreve                                                                                        r-monitor/node_modules/broadway/node_modules/winston/test/logger-test.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 2.6.32-431.11.2.el6.x86_64
npm ERR! command "node" "/usr/bin/npm" "-g" "install" "forever"
npm ERR! cwd /var/www/lanalytics
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.3.6
npm ERR! path /usr/lib/node_modules/forever/node_modules/forever-monitor/node_mo                                                                                        dules/broadway/node_modules/winston/test/logger-test.js
npm ERR! fstream_path /usr/lib/node_modules/forever/node_modules/forever-monitor                                                                                        /node_modules/broadway/node_modules/winston/test/logger-test.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat '/usr/lib/node_modules/forever/node_modules/flatir                                                                                        on/node_modules/prompt/node_modules/winston/node_modules/request/tests/test-time                                                                                        out.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 2.6.32-431.11.2.el6.x86_64
npm ERR! command "node" "/usr/bin/npm" "-g" "install" "forever"
npm ERR! cwd /var/www/lanalytics
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.3.6
npm ERR! path /usr/lib/node_modules/forever/node_modules/flatiron/node_modules/p                                                                                        rompt/node_modules/winston/node_modules/request/tests/test-timeout.js
npm ERR! fstream_path /usr/lib/node_modules/forever/node_modules/flatiron/node_m                                                                                        odules/prompt/node_modules/winston/node_modules/request/tests/test-timeout.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! SyntaxError: Unexpected token <
npm ERR!
npm ERR! <?xml version="1.0" encoding="utf-8"?>
npm ERR! <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
npm ERR!  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
npm ERR! <html>
npm ERR!   <head>
npm ERR!     <title>200 OK</title>
npm ERR!   </head>
npm ERR!   <body>
npm ERR!     <h1>Error 200 OK</h1>
npm ERR!     <p>OK</p>
npm ERR!     <h3>Guru Meditation:</h3>
npm ERR!     <p>XID: 724797158</p>
npm ERR!     <hr>
npm ERR!     <p>Varnish cache server</p>
npm ERR!   </body>
npm ERR! </html>
npm ERR!
npm ERR!     at Object.parse (native)
npm ERR!     at RegClient.<anonymous> (/usr/lib/node_modules/npm-registry-client                                                                                        /lib/request.js:238:23)
npm ERR!     at Request.self.callback (/usr/lib/node_modules/request/index.js:14                                                                                        8:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/lib/node_modules/request/index.js:891:                                                                                        14)
npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/lib/node_modules/request/index                                                                                        .js:842:12)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:919:16
npm ERR!     at process._tickCallback (node.js:419:13)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 2.6.32-431.11.2.el6.x86_64
npm ERR! command "node" "/usr/bin/npm" "-g" "install" "forever"
npm ERR! cwd /var/www/lanalytics
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.3.6
npm ERR! type unexpected_token
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /var/www/lanalytics/npm-debug.log
npm ERR! not ok code 0
```

**Comment by othiym23** [comment]
Closing as resolved / abandoned.
