### ISSUE TITLE
Karma - Error: shasum check failed for 

### ISSUE THREAD

**Issue by michaelsync** [npm/npm#5488]
As I don't have VS 2010, I am using this command to install Karma

  $ npm -g install karma --msvs_version=2013

But got the following error.
```
validation.vcxproj -> C:\Users\Michael\AppData\Roaming\npm\node_modules\karma
 \node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\build\R
 elease\\validation.node
pm http 304 https://registry.npmjs.org/zeparser
pm ERR! Error: shasum check failed for C:\Users\Michael\AppData\Local\Temp\npm-
996-C5h2Qtm7\1402827077020-0.64778290130198\tmp.tgz
pm ERR! Expected: a567c2af000ad22dc8f2a653d91978ae1f5316f4
pm ERR! Actual:   4a5c9ff38c379a4fa3dee9c12e7ee222e7d15eb6
pm ERR! From:     https://registry.npmjs.org/multiparty/-/multiparty-2.2.0.tgz
pm ERR!     at c:\Program Files (x86)\nodejs\node_modules\npm\node_modules\sha\
ndex.js:38:8
pm ERR!     at ReadStream.<anonymous> (c:\Program Files (x86)\nodejs\node_modul
s\npm\node_modules\sha\index.js:85:7)
pm ERR!     at ReadStream.EventEmitter.emit (events.js:117:20)
pm ERR!     at _stream_readable.js:919:16
pm ERR!     at process._tickCallback (node.js:419:13)
pm ERR! If you need help, you may report this *entire* log,
pm ERR! including the npm and node versions, at:
pm ERR!     <http://github.com/npm/npm/issues>

pm ERR! System Windows_NT 6.2.9200
pm ERR! command "c:\\Program Files (x86)\\nodejs\\node.exe" "c:\\Program Files
x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "-g" "install" "karma" "--msv
_version=2013"
pm ERR! cwd c:\Users\Michael\Documents\GitHub\MyProject
pm ERR! node -v v0.10.28
pm ERR! npm -v 1.4.9
pm ERR!
pm ERR! Additional logging details can be found in:
```
Additional Information.

Window 8
VS 2012 and VS 2013
npm -v 1.4.9
node -v v0.10.28

Any help would be appreciated.

**Comment by othiym23** [comment]
Closing as resolved / abandoned.
