### ISSUE TITLE
UNABLE_TO_VERIFY_LEAF_SIGNATURE

### ISSUE THREAD

**Issue by ronapelbaum** [npm/npm#5510]
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'bower' ]
2 info using npm@1.4.14
3 info using node@v0.10.29
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 verbose cache add [ 'bower', null ]
6 verbose cache add name=undefined spec="bower" args=["bower",null]
7 verbose parsed url { protocol: null,
7 verbose parsed url   slashes: null,
7 verbose parsed url   auth: null,
7 verbose parsed url   host: null,
7 verbose parsed url   port: null,
7 verbose parsed url   hostname: null,
7 verbose parsed url   hash: null,
7 verbose parsed url   search: null,
7 verbose parsed url   query: null,
7 verbose parsed url   pathname: 'bower',
7 verbose parsed url   path: 'bower',
7 verbose parsed url   href: 'bower' }
8 silly lockFile 206e3ce5-bower bower
9 verbose lock bower C:\Users\MIZRAHI\AppData\Roaming\npm-cache\206e3ce5-bower.lock
10 silly lockFile 206e3ce5-bower bower
11 silly lockFile 206e3ce5-bower bower
12 verbose addNamed [ 'bower', '' ]
13 verbose addNamed [ null, '*' ]
14 silly lockFile 1240aab1-bower bower@
15 verbose lock bower@ C:\Users\MIZRAHI\AppData\Roaming\npm-cache\1240aab1-bower.lock
16 silly addNameRange { name: 'bower', range: '*', hasData: false }
17 verbose url raw bower
18 verbose url resolving [ 'https://registry.npmjs.org/', './bower' ]
19 verbose url resolved https://registry.npmjs.org/bower
20 info trying registry request attempt 1 at 20:41:52
21 http GET https://registry.npmjs.org/bower
22 info retry will retry, error on last attempt: Error: UNABLE_TO_VERIFY_LEAF_SIGNATURE
23 info trying registry request attempt 2 at 20:42:02
24 http GET https://registry.npmjs.org/bower
25 info retry will retry, error on last attempt: Error: UNABLE_TO_VERIFY_LEAF_SIGNATURE
26 info trying registry request attempt 3 at 20:43:02
27 http GET https://registry.npmjs.org/bower
28 silly lockFile 1240aab1-bower bower@
29 silly lockFile 1240aab1-bower bower@
30 error Error: UNABLE_TO_VERIFY_LEAF_SIGNATURE
30 error     at SecurePair.<anonymous> (tls.js:1365:32)
30 error     at SecurePair.emit (events.js:92:17)
30 error     at SecurePair.maybeInitFinished (tls.js:977:10)
30 error     at CleartextStream.read [as _read] (tls.js:469:13)
30 error     at CleartextStream.Readable.read (_stream_readable.js:323:10)
30 error     at EncryptedStream.write [as _write] (tls.js:366:25)
30 error     at doWrite (_stream_writable.js:226:10)
30 error     at writeOrBuffer (_stream_writable.js:216:5)
30 error     at EncryptedStream.Writable.write (_stream_writable.js:183:11)
30 error     at write (_stream_readable.js:585:24)
30 error     at flow (_stream_readable.js:594:7)
31 error If you need help, you may report this *entire* log,
31 error including the npm and node versions, at:
31 error     <http://github.com/npm/npm/issues>
32 error System Windows_NT 6.1.7601
33 error command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "bower"
34 error cwd C:\git
35 error node -v v0.10.29
36 error npm -v 1.4.14
37 verbose exit [ 1, true ]
```

**Comment by othiym23** [comment]
Closing as abandoned.
