### ISSUE TITLE
npm home + 4 packages: Error LSOpenURLsWithRole()  -1712

### ISSUE THREAD

**Issue by timoxley** [npm/npm#5521]
Not life threatening but mildly annoying.

With 3 arguments, `npm home` works correctly without complaint:
```
> npm home inherits tape tap 

>
```
But add 1 more argument and you have a high likelihood of seeing errors (not exactly every time though)
```
> npm home inherits tape tap faucet
npm ERR! Error: Command failed: LSOpenURLsWithRole() failed with error -1712 for the URL https://github.com/isaacs/node-tap.
npm ERR!
npm ERR!     at ChildProcess.exithandler (child_process.js:647:15)
npm ERR!     at ChildProcess.emit (events.js:98:17)
npm ERR!     at maybeClose (child_process.js:755:16)
npm ERR!     at Process.ChildProcess._handle.onexit (child_process.js:822:5)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 14.0.0
npm ERR! command "node" "/usr/local/bin/npm" "home" "inherits" "tape" "tap" "faucet"
npm ERR! cwd /Users/timoxley/Projects/npm-workshop
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.16
npm ERR! code 1
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/timoxley/Projects/npm-workshop/npm-debug.log
npm ERR! not ok code 0
```

Reproduced on `npm@1.4.14`, `npm@1.4.16` and latest master.

[According to this old Apple documentation](http://support.apple.com/kb/HT2237?viewlocale=en_US) error code `-1712` is	`errAETimeout	Apple event timed out`, which could be a good hint given this works for 3 urls but not 4.

Note: I'm running the preview release of OSX 10.10 (Yosemite, update 2), on a so it could also be an issue with this operating system (I'd love to be able to blame the new, ghastly system font :/). Would be interested if anyone can reproduce, perhaps different systems need more arguments. My machine is a MacBook Pro (Retina, 13-inch, Early 2013), 3 GHz Intel Core i7.

**Comment by timoxley** [comment]
Can no longer reproduce on my machine either, though I'm on a new machine and updated OS X.

It may have been something specific to the config on that machine or that version of Yosemite.

Tested on Yosemite 10.10.4 (14E46) with npm v2.9.0, npm v2.14.0 and npm v3.3.0.

I suggest reopening if/when symptoms resurface.
