### ISSUE TITLE
Failed install npm

### ISSUE THREAD

**Issue by Yabo0815** [npm/npm#5538]
Here's the error log, what can I do for this issue?

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/tmp/npm.3674/package/cli.js',
1 verbose cli   'install',
1 verbose cli   '-gf' ]
2 info using npm@1.4.16
3 info using node@v0.10.29
4 warn using --force I sure hope you know what you are doing.
5 verbose cache add [ '.', null ]
6 verbose cache add name=undefined spec="." args=[".",null]
7 verbose parsed url { protocol: null,
7 verbose parsed url   slashes: null,
7 verbose parsed url   auth: null,
7 verbose parsed url   host: null,
7 verbose parsed url   port: null,
7 verbose parsed url   hostname: null,
7 verbose parsed url   hash: null,
7 verbose parsed url   search: null,
7 verbose parsed url   query: null,
7 verbose parsed url   pathname: '.',
7 verbose parsed url   path: '.',
7 verbose parsed url   href: '.' }
8 silly lockFile 3a52ce78- .
9 verbose lock . /home/yabo/.npm/3a52ce78-.lock
10 silly lockFile 3a52ce78- .
11 error Error: Attempt to unlock ., which hasn't been locked
11 error     at unlock (/tmp/npm.3674/package/lib/utils/locker.js:44:11)
11 error     at cb (/tmp/npm.3674/package/lib/cache/add-local.js:30:5)
11 error     at /tmp/npm.3674/package/lib/cache/add-local.js:47:20
11 error     at /tmp/npm.3674/package/lib/utils/locker.js:30:7
11 error     at /tmp/npm.3674/package/node_modules/lockfile/lockfile.js:167:38
11 error     at Object.oncomplete (fs.js:107:15)
12 error If you need help, you may report this *entire* log,
12 error including the npm and node versions, at:
12 error     <http://github.com/npm/npm/issues>
13 error System Linux 3.11.0-23-generic
14 error command "/usr/local/bin/node" "/tmp/npm.3674/package/cli.js" "install" "-gf"
15 error cwd /tmp/npm.3674/package
16 error node -v v0.10.29
17 error npm -v 1.4.16
18 verbose exit [ 1, true ]
```

**Comment by othiym23** [comment]
Closing as abandoned.
