### ISSUE TITLE
Azure deployment error

### ISSUE THREAD

**Issue by codeuniquely** [npm/npm#5556]
When attempting to deploy this minimal site to azure  

    var http = require('http');
    var express = require('express');

    var app = express();

    var port = process.env.PORT || 3001;
    http.createServer(app).listen(port, function () 
    {
        console.log('site is listening on port ' + port);
    });

The following error is reported and the deployment fails:

 Error: SSL Error: SELF_SIGNED_CERT_IN_CHAIN
     at ClientRequest.<anonymous> (D:\Program Files (x86)\npm\1.1.37\node_modules\npm\node_modules\request\main.js:440:26)
     at ClientRequest.g (events.js:156:14)
     at ClientRequest.emit (events.js:67:17)
     at HTTPParser.parserOnIncomingClient (http.js:1256:7)
     at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:91:29)
     at CleartextStream.socketOnData (http.js:1288:20)
     at CleartextStream._push (tls.js:375:27)
     at SecurePair.cycle (tls.js:734:20)
     at EncryptedStream.write (tls.js:130:13)
     at Socket.ondata (stream.js:38:26)
  [Error: SSL Error: SELF_SIGNED_CERT_IN_CHAIN]
 You may report this log at:
     <http://github.com/isaacs/npm/issues>
 or email it to:
     <npm-@googlegroups.com>

**Comment by smikes** [comment]
Is this still a problem for you?

The `npm` registry used to use a self-signed certificate and now does not.  There were numerous issues involving this at the time, but it should all be sorted out by now.  If nothing else, I expect that Azure is now on a newer version of `npm`.

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as resolved / abandoned.
