### ISSUE TITLE
Can't publish (or login) after update to 1.5.0-alpha-1

### ISSUE THREAD

**Issue by DavidSouther** [npm/npm#5607]
I ran `npm up -g npm` this morning, and ended up with 1.5.0 alpha 1. Now, I cannot adduser/login, or publish packages.

```
% npm publish
npm ERR! need auth auth and email required for publishing
npm ERR! need auth You need to authorize this machine using `npm adduser`

npm ERR! System Darwin 13.2.0
npm ERR! command "node" "/Users/southerd/.nvm/v0.10.28/bin/npm" "publish"
npm ERR! cwd /Users/southerd/devel/southerd/libraries/stassets
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.5.0-alpha-1
npm ERR! code ENEEDAUTH
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/southerd/devel/southerd/libraries/stassets/npm-debug.log
npm ERR! not ok code 0

% npm adduser
Username: davidsouther
Password:
Email: (this IS public) davidsouther@gmail.com
npm ERR! Error: No credentials to set.
npm ERR!     at Conf.setCredentialsByURI (/Users/southerd/.nvm/v0.10.28/lib/node_modules/npm/node_modules/npmconf/lib/set-credentials-by-uri.js:32:11)
npm ERR!     at RegClient.<anonymous> (/Users/southerd/.nvm/v0.10.28/lib/node_modules/npm/node_modules/npm-registry-client/lib/adduser.js:112:17)
npm ERR!     at cb (/Users/southerd/.nvm/v0.10.28/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:57:9)
npm ERR!     at RegClient.<anonymous> (/Users/southerd/.nvm/v0.10.28/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:158:10)
npm ERR!     at cb (/Users/southerd/.nvm/v0.10.28/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:168:9)
npm ERR!     at RegClient.<anonymous> (/Users/southerd/.nvm/v0.10.28/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:325:12)
npm ERR!     at Request._callback (/Users/southerd/.nvm/v0.10.28/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:251:65)
npm ERR!     at Request.self.callback (/Users/southerd/.nvm/v0.10.28/lib/node_modules/npm/node_modules/request/request.js:123:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/Users/southerd/.nvm/v0.10.28/lib/node_modules/npm/node_modules/request/request.js:893:14)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 13.2.0
npm ERR! command "node" "/Users/southerd/.nvm/v0.10.28/bin/npm" "adduser"
npm ERR! cwd /Users/southerd/devel/southerd/libraries/stassets
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.5.0-alpha-1
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/southerd/devel/southerd/libraries/stassets/npm-debug.log
npm ERR! not ok code 0

% npm whoami
npm ERR! Error: credentials without username or token
npm ERR!     at EventEmitter.whoami (/Users/southerd/.nvm/v0.10.28/lib/node_modules/npm/lib/whoami.js:32:38)
npm ERR!     at Object.commandCache.(anonymous function) (/Users/southerd/.nvm/v0.10.28/lib/node_modules/npm/lib/npm.js:219:11)
npm ERR!     at EventEmitter.<anonymous> (/Users/southerd/.nvm/v0.10.28/lib/node_modules/npm/bin/npm-cli.js:83:28)
npm ERR!     at process._tickCallback (node.js:419:13)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 13.2.0
npm ERR! command "node" "/Users/southerd/.nvm/v0.10.28/bin/npm" "whoami"
npm ERR! cwd /Users/southerd/devel/southerd/libraries/stassets
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.5.0-alpha-1
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/southerd/devel/southerd/libraries/stassets/npm-debug.log
npm ERR! not ok code 0
```

**Comment by smikes** [comment]
Is this still a problem for you?

I know that several people have had auth issues due to changes in the npm registry and `npm` client.  The following procedure usually fixes them:

```
log in at http://npmjs.com/
reset password at https://www.npmjs.com/password 
remove login credentials from ~/.npmrc
npm login (with new password)
```

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by DavidSouther** [comment]
I thought I'd closed this ages ago! Apologies for leaving it open.
