### ISSUE TITLE
Seeing "npm ERR! Failed to parse json" / "Varnish cache server" errors again while running "npm install".

### ISSUE THREAD

**Issue by yzapuchlak** [npm/npm#5636]
I'm once again seeing "npm ERR! Failed to parse json" / "Varnish cache server" errors for seemingly random packages when I do a npm-install. 

I've cleaned my npm cache and deleted my node_modules directory many times now and I still have not been able to successfully complete an "npm install" all day.

Looks like one of the npm Varnish cache servers is returning junk data again? :-/

```
npm info preuninstall request@2.21.0
npm info uninstall request@2.21.0
npm verb false,/Users/yuri/dev/myapp/node_modules,/Users/yuri/dev/myapp/node_modules/yui/node_modules unbuild request@2.21.0
npm info postuninstall request@2.21.0
npm ERR! Error: ENOENT, lstat '/Users/yuri/dev/myapp/node_modules/yui/node_modules/request/node_modules/http-signature/node_modules/ctype/ctio.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 13.2.0
npm ERR! command "/Users/yuri/.nvm/v0.10.26/bin/node" "/Users/yuri/.nvm/v0.10.26/bin/npm" "--loglevel" "verbose" "install"
npm ERR! cwd /Users/yuri/dev/myapp
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! path /Users/yuri/dev/myapp/node_modules/yui/node_modules/request/node_modules/http-signature/node_modules/ctype/ctio.js
npm ERR! fstream_path /Users/yuri/dev/myapp/node_modules/yui/node_modules/request/node_modules/http-signature/node_modules/ctype/ctio.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /Users/yuri/.nvm/v0.10.26/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm verb exit [ 34, true ]
npm ERR! error rolling back Error: ENOTEMPTY, rmdir '/Users/yuri/dev/myapp/node_modules/yui/node_modules/request/node_modules/http-signature/node_modules/asn1'
npm ERR! error rolling back  request@2.21.0 { [Error: ENOTEMPTY, rmdir '/Users/yuri/dev/myapp/node_modules/yui/node_modules/request/node_modules/http-signature/node_modules/asn1']
npm ERR! error rolling back   errno: 53,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   path: '/Users/yuri/dev/myapp/node_modules/yui/node_modules/request/node_modules/http-signature/node_modules/asn1' }
npm verb about to build /Users/yuri/dev/myapp/node_modules/yui
npm info /Users/yuri/dev/myapp/node_modules/yui unbuild
npm info preuninstall yui@3.17.1
npm info uninstall yui@3.17.1
npm verb true,/Users/yuri/dev/myapp/node_modules,/Users/yuri/dev/myapp/node_modules unbuild yui@3.17.1
npm info postuninstall yui@3.17.1
npm info /Users/yuri/dev/myapp/node_modules/yui/node_modules/request/node_modules/http-signature/node_modules/asn1 unbuild
npm verb about to build /Users/yuri/dev/myapp/node_modules/yui/node_modules/request/node_modules/http-signature
npm info /Users/yuri/dev/myapp/node_modules/yui/node_modules/request/node_modules/http-signature unbuild
npm info preuninstall http-signature@0.9.11
npm info uninstall http-signature@0.9.11
npm ERR! SyntaxError: Unexpected token <
npm ERR!
npm ERR! <?xml version="1.0" encoding="utf-8"?>
npm ERR! <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
npm ERR!  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
npm ERR! <html>
npm ERR!   <head>
npm ERR!     <title>200 OK</title>
npm ERR!   </head>
npm ERR!   <body>
npm ERR!     <h1>Error 200 OK</h1>
npm ERR!     <p>OK</p>
npm ERR!     <h3>Guru Meditation:</h3>
npm ERR!     <p>XID: 724797158</p>
npm ERR!     <hr>
npm ERR!     <p>Varnish cache server</p>
npm ERR!   </body>
npm ERR! </html>
npm ERR!
npm ERR!     at Object.parse (native)
npm ERR!     at RegClient.<anonymous> (/Users/yuri/.nvm/v0.10.26/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:203:23)
npm ERR!     at Request.self.callback (/Users/yuri/.nvm/v0.10.26/lib/node_modules/npm/node_modules/request/request.js:123:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/Users/yuri/.nvm/v0.10.26/lib/node_modules/npm/node_modules/request/request.js:893:14)
npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/Users/yuri/.nvm/v0.10.26/lib/node_modules/npm/node_modules/request/request.js:844:12)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 13.2.0
npm ERR! command "/Users/yuri/.nvm/v0.10.26/bin/node" "/Users/yuri/.nvm/v0.10.26/bin/npm" "--loglevel" "verbose" "install"
npm ERR! cwd /Users/yuri/dev/myapp
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! type unexpected_token
npm verb exit [ 1, true ]
npm verb false,/Users/yuri/dev/myapp/node_modules,/Users/yuri/dev/myapp/node_modules/yui/node_modules/request/node_modules unbuild http-signature@0.9.11
npm info postuninstall http-signature@0.9.11
npm http 200 https://registry.npmjs.org/hoek/-/hoek-0.9.1.tgz
```

**Comment by smikes** [comment]
Is this still a problem for you?

I am not even sure whether Varnish is used anymore for caching, as it's been six months since this issue resurfaced.  /cc @ceejbot for comments (if any) regarding dev ops

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by eheikes** [comment]
I haven't seen the issue in the past few months, so I'm okay with closing it for now.

**Comment by othiym23** [comment]
Closing as resolved.
