### ISSUE TITLE
issue with "npm install" in MAC OS X

### ISSUE THREAD

**Issue by kamalelan** [npm/npm#5639]
Hi,

I am getting error during install npm.

My log as below:
Can you help me to install it?

```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'install' ]
2 info using npm@1.4.14
3 info using node@v0.10.29
4 verbose readDependencies using package.json deps
5 verbose install where, deps [ '/Users/mac39/Desktop/easyrtc',
5 verbose install   [ 'easyrtc', 'express', 'socket.io' ] ]
6 info preinstall easyrtc_server_example@0.1.6
7 verbose readDependencies using package.json deps
8 verbose cache add [ 'socket.io@0.9.x', null ]
9 verbose cache add name=undefined spec="socket.io@0.9.x" args=["socket.io@0.9.x",null]
10 verbose parsed url { protocol: null,
10 verbose parsed url   slashes: null,
10 verbose parsed url   auth: null,
10 verbose parsed url   host: null,
10 verbose parsed url   port: null,
10 verbose parsed url   hostname: null,
10 verbose parsed url   hash: null,
10 verbose parsed url   search: null,
10 verbose parsed url   query: null,
10 verbose parsed url   pathname: 'socket.io@0.9.x',
10 verbose parsed url   path: 'socket.io@0.9.x',
10 verbose parsed url   href: 'socket.io@0.9.x' }
11 verbose cache add [ 'easyrtc@*', null ]
12 verbose cache add name=undefined spec="easyrtc@*" args=["easyrtc@*",null]
13 verbose parsed url { protocol: null,
13 verbose parsed url   slashes: null,
13 verbose parsed url   auth: null,
13 verbose parsed url   host: null,
13 verbose parsed url   port: null,
13 verbose parsed url   hostname: null,
13 verbose parsed url   hash: null,
13 verbose parsed url   search: null,
13 verbose parsed url   query: null,
13 verbose parsed url   pathname: 'easyrtc@*',
13 verbose parsed url   path: 'easyrtc@*',
13 verbose parsed url   href: 'easyrtc@*' }
14 verbose cache add [ 'express@*', null ]
15 verbose cache add name=undefined spec="express@*" args=["express@*",null]
16 verbose parsed url { protocol: null,
16 verbose parsed url   slashes: null,
16 verbose parsed url   auth: null,
16 verbose parsed url   host: null,
16 verbose parsed url   port: null,
16 verbose parsed url   hostname: null,
16 verbose parsed url   hash: null,
16 verbose parsed url   search: null,
16 verbose parsed url   query: null,
16 verbose parsed url   pathname: 'express@*',
16 verbose parsed url   path: 'express@*',
16 verbose parsed url   href: 'express@*' }
17 verbose cache add name="socket.io" spec="0.9.x" args=["socket.io","0.9.x"]
18 verbose parsed url { protocol: null,
18 verbose parsed url   slashes: null,
18 verbose parsed url   auth: null,
18 verbose parsed url   host: null,
18 verbose parsed url   port: null,
18 verbose parsed url   hostname: null,
18 verbose parsed url   hash: null,
18 verbose parsed url   search: null,
18 verbose parsed url   query: null,
18 verbose parsed url   pathname: '0.9.x',
18 verbose parsed url   path: '0.9.x',
18 verbose parsed url   href: '0.9.x' }
19 verbose addNamed [ 'socket.io', '0.9.x' ]
20 verbose addNamed [ null, '>=0.9.0-0 <0.10.0-0' ]
21 verbose cache add name="easyrtc" spec="*" args=["easyrtc","*"]
22 verbose parsed url { protocol: null,
22 verbose parsed url   slashes: null,
22 verbose parsed url   auth: null,
22 verbose parsed url   host: null,
22 verbose parsed url   port: null,
22 verbose parsed url   hostname: null,
22 verbose parsed url   hash: null,
22 verbose parsed url   search: null,
22 verbose parsed url   query: null,
22 verbose parsed url   pathname: '*',
22 verbose parsed url   path: '*',
22 verbose parsed url   href: '*' }
23 verbose addNamed [ 'easyrtc', '*' ]
24 verbose addNamed [ null, '*' ]
25 verbose cache add name="express" spec="*" args=["express","*"]
26 verbose parsed url { protocol: null,
26 verbose parsed url   slashes: null,
26 verbose parsed url   auth: null,
26 verbose parsed url   host: null,
26 verbose parsed url   port: null,
26 verbose parsed url   hostname: null,
26 verbose parsed url   hash: null,
26 verbose parsed url   search: null,
26 verbose parsed url   query: null,
26 verbose parsed url   pathname: '*',
26 verbose parsed url   path: '*',
26 verbose parsed url   href: '*' }
27 verbose addNamed [ 'express', '*' ]
28 verbose addNamed [ null, '*' ]
29 silly lockFile 4eb97b2b-socket-io-0-9-x socket.io@0.9.x
30 verbose lock socket.io@0.9.x /Users/mac39/.npm/4eb97b2b-socket-io-0-9-x.lock
31 silly lockFile 351e2561-easyrtc easyrtc@*
32 verbose lock easyrtc@* /Users/mac39/.npm/351e2561-easyrtc.lock
33 silly lockFile 8ad1ad64-express express@*
34 verbose lock express@* /Users/mac39/.npm/8ad1ad64-express.lock
35 silly lockFile 4eb97b2b-socket-io-0-9-x socket.io@0.9.x
36 error Error: Attempt to unlock socket.io@0.9.x, which hasn't been locked
36 error     at unlock (/usr/local/lib/node_modules/npm/lib/utils/locker.js:44:11)
36 error     at cb (/usr/local/lib/node_modules/npm/lib/cache/add-named.js:32:5)
36 error     at /usr/local/lib/node_modules/npm/lib/cache/add-named.js:41:20
36 error     at /usr/local/lib/node_modules/npm/lib/utils/locker.js:30:7
36 error     at /usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:167:38
36 error     at OpenReq.Req.done (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:144:5)
36 error     at OpenReq.done (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:64:22)
36 error     at Object.oncomplete (fs.js:107:15)
37 error If you need help, you may report this *entire* log,
37 error including the npm and node versions, at:
37 error     <http://github.com/npm/npm/issues>
38 error System Darwin 12.4.0
39 error command "node" "/usr/local/bin/npm" "install"
40 error cwd /Users/mac39/Desktop/easyrtc
41 error node -v v0.10.29
42 error npm -v 1.4.14
43 verbose exit [ 1, true ]
```

Thanks

**Comment by othiym23** [comment]
Closing as abandoned.
