### ISSUE TITLE
Running into error while installing bootstrap grunt

### ISSUE THREAD

**Issue by Airswoop1** [npm/npm#5647]
Already ran npm cache clear and ran the npm install using sudo, no luck. Any help or guidance would be appreciated! 
```
1495 verbose addRemoteTarball [ 'https://registry.npmjs.org/rimraf/-/rimraf-2.2.8.tgz',
1495 verbose addRemoteTarball   'e439be2aaee327321952730f99a8929e4fc50582' ]
1496 info retry fetch attempt 1 at 12:11:55
1497 verbose fetch to= /Users/airswoop1/tmp/npm-3066/1404749515468-0.7687517555896193/tmp.tgz
1498 http GET https://registry.npmjs.org/rimraf/-/rimraf-2.2.8.tgz
1499 verbose about to build /Users/airswoop1/Downloads/bootstrap-3.1.1/node_modules/grunt-contrib-qunit
1500 info /Users/airswoop1/Downloads/bootstrap-3.1.1/node_modules/grunt-contrib-qunit unbuild
1501 verbose from cache /Users/airswoop1/Downloads/bootstrap-3.1.1/node_modules/grunt-contrib-qunit/package.json
1502 info preuninstall grunt-contrib-qunit@0.4.0
1503 info uninstall grunt-contrib-qunit@0.4.0
1504 verbose true,/Users/airswoop1/Downloads/bootstrap-3.1.1/node_modules,/Users/airswoop1/Downloads/bootstrap-3.1.1/node_modules unbuild grunt-contrib-qunit@0.4.0
1505 info postuninstall grunt-contrib-qunit@0.4.0
1506 error Error: No compatible version found: progress@'^1.1.5'
1506 error Valid install targets:
1506 error ["0.0.1","0.0.2","0.0.3","0.0.4","0.0.5","0.1.0","1.0.0","1.0.1","1.1.0","1.1.2","1.1.3","1.1.4","1.1.5","1.1.6","1.1.7"]
1506 error     at installTargetsError (/usr/local/Cellar/node/0.10.12/lib/node_modules/npm/lib/cache.js:719:10)
1506 error     at /usr/local/Cellar/node/0.10.12/lib/node_modules/npm/lib/cache.js:641:10
1506 error     at saved (/usr/local/Cellar/node/0.10.12/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
1506 error     at Object.oncomplete (fs.js:107:15)
1507 error If you need help, you may report this log at:
1507 error     <http://github.com/isaacs/npm/issues>
1507 error or email it to:
1507 error     <npm-@googlegroups.com>
1508 error System Darwin 13.2.0
1509 error command "/usr/local/Cellar/node/0.10.12/bin/node" "/usr/local/bin/npm" "install"
1510 error cwd /Users/airswoop1/Downloads/bootstrap-3.1.1
1511 error node -v v0.10.12
1512 error npm -v 1.2.32
```

**Comment by smikes** [comment]
Is this still a problem for you?

This looks like the problem where old versions of `npm` did not understand the semver `^` operator.  I second @faiq 's suggestion of updating to a newer `node` and `nvm`.  Either get the latest official package from Joyent <https://nodejs.org/download> or io.js <https://iojs.org/> and then update `npm` to the latest version with `npm install -g npm@latest`

Like @miel187, I use `nvm`, which also lets you quickly switch between installed `node` versions.

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as resolved / abandoned.

**Comment by HerneWyldwood** [comment]
Issue still exists after update of node (5.9.1) and npm (3.8.2)

**Comment by KenanY** [comment]
@HerneWyldwood Can you upload your `npm-debug.log` as a [gist](https://gist.github.com/) and post the link here (or in a new issue)?
