### ISSUE TITLE
brew install node Type Error: 'uid must be an unsigned int'

### ISSUE THREAD

**Issue by melancholyfleur** [npm/npm#5654]
I'm on OS X 10.9, with node v0.10.29. When I try to do a simple 'brew install node' from here, it gives the following error:

```
brew install node
==> Downloading https://downloads.sf.net/project/machomebrew/Bottles/node-0.10.29.mavericks.bottle.tar.gz
Already downloaded: /Library/Caches/Homebrew/node-0.10.29.mavericks.bottle.tar.gz
==> Pouring node-0.10.29.mavericks.bottle.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> make install
npm ERR! Additional logging details can be found in:
npm ERR!     /usr/local/lib/node_modules/npm/npm-debug.log
npm ERR! not ok code 0
make[1]: *** [node_modules/.bin/ronn] Error 1
make: *** [man/man3/npm-bin.3] Error 2
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall node`
==> Summary
🍺  /usr/local/Cellar/node/0.10.29: 1547 files, 18M
```

then when i go to said log file, this is the log:
```
0 info it worked if it ends with ok
1 verbose cli [ 'node',
1 verbose cli   '/usr/local/lib/node_modules/npm/cli.js',
1 verbose cli   'install',
1 verbose cli   'ronn',
1 verbose cli   '--no-global' ]
2 info using npm@1.4.9
3 info using node@v0.10.29
4 verbose node symlink /usr/local/bin/node
5 warn package.json github-url-from-git@1.1.1 No repository field.
6 verbose readDependencies using package.json deps
7 verbose cache add [ 'ronn', null ]
8 verbose cache add name=undefined spec="ronn" args=["ronn",null]
9 verbose parsed url { protocol: null,
9 verbose parsed url   slashes: null,
9 verbose parsed url   auth: null,
9 verbose parsed url   host: null,
9 verbose parsed url   port: null,
9 verbose parsed url   hostname: null,
9 verbose parsed url   hash: null,
9 verbose parsed url   search: null,
9 verbose parsed url   query: null,
9 verbose parsed url   pathname: 'ronn',
9 verbose parsed url   path: 'ronn',
9 verbose parsed url   href: 'ronn' }
10 silly lockFile 806e3618-ronn ronn
11 verbose lock ronn /Users/maryloulenhart/.npm/806e3618-ronn.lock
12 silly lockFile 806e3618-ronn ronn
13 silly lockFile 806e3618-ronn ronn
14 verbose addNamed [ 'ronn', '' ]
15 verbose addNamed [ null, '*' ]
16 silly lockFile 6e289111-ronn ronn@
17 verbose lock ronn@ /Users/maryloulenhart/.npm/6e289111-ronn.lock
18 silly addNameRange { name: 'ronn', range: '*', hasData: false }
19 verbose url raw ronn
20 verbose url resolving [ 'https://registry.npmjs.org/', './ronn' ]
21 verbose url resolved https://registry.npmjs.org/ronn
22 info trying registry request attempt 1 at 16:31:42
23 http GET https://registry.npmjs.org/ronn
24 http 200 https://registry.npmjs.org/ronn
25 silly registry.get cb [ 200,
25 silly registry.get   { date: 'Tue, 08 Jul 2014 23:31:43 GMT',
25 silly registry.get     server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
25 silly registry.get     etag: '"CLWNPKO2YUMMVU9CLN5MD63AU"',
25 silly registry.get     'content-type': 'application/json',
25 silly registry.get     'cache-control': 'max-age=30',
25 silly registry.get     'content-length': '7429',
25 silly registry.get     'accept-ranges': 'bytes',
25 silly registry.get     via: '1.1 varnish',
25 silly registry.get     age: '2047',
25 silly registry.get     'x-served-by': 'cache-sjc3125-SJC',
25 silly registry.get     'x-cache': 'HIT',
25 silly registry.get     'x-cache-hits': '1',
25 silly registry.get     'x-timer': 'S1404862303.478452,VS0,VE81',
25 silly registry.get     vary: 'Accept',
25 silly registry.get     'keep-alive': 'timeout=10, max=50',
25 silly registry.get     connection: 'Keep-Alive' } ]
26 error TypeError: uid must be an unsigned int
26 error     at Object.fs.chown (fs.js:858:11)
26 error     at Object.chown (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:131:17)
26 error     at /usr/local/lib/node_modules/npm/node_modules/chownr/chownr.js:12:43
26 error     at ReaddirReq.Req.done (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:144:5)
26 error     at ReaddirReq.done (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:91:22)
26 error     at Object.oncomplete (fs.js:107:15)
27 error If you need help, you may report this *entire* log,
27 error including the npm and node versions, at:
27 error     <http://github.com/npm/npm/issues>
28 error System Darwin 13.3.0
29 error command "node" "/usr/local/lib/node_modules/npm/cli.js" "install" "ronn" "--no-global"
30 error cwd /usr/local/lib/node_modules/npm
31 error node -v v0.10.29
32 error npm -v 1.4.9
33 verbose exit [ 1, true ]
```

Looking up this error in the past (i.e. this was an error that occurred a lot before 0.10.15: https://github.com/npm/npm/issues/4080), it seems there is an issue with npm creating files with no owner, and then on certain operating systems, this becomes a problem. I'm not sure if it has to do with how brew does things, or how npm does things.

**Comment by smikes** [comment]
Is this still a problem for you?

Sometimes this issue is caused by incorrect data in the `.npmrc` file.  Try this:

```
npm config get user
npm config del user
```

The `user` config parameter is only needed when `npm` is dropping root permissions, so it should be safe to delete whatever "user" is in your `.npmrc`.

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.4.20. Can you try updating your npm installation?

To update npm, run `npm -g install npm@latest`

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by melancholyfleur** [comment]
I believe this ended up being the cause of bad imaging, so I will close this issue. Thanks for your response!
