### ISSUE TITLE
failed to install socket.io

### ISSUE THREAD

**Issue by superbull** [npm/npm#5718]
os: windows 7 64bit
node.js: v0.11.13
behind company proxy, set proxy like this:
```
npm config set proxy http://username:abcd1\!@proxy.company.com:81
npm config set https-proxy http://username:abcd11\!@proxy.company.com:81
```
can successfully install socket.io@0.9.14:
```
npm install socket.io@0.9.14
```
but failed to install the latest version 1.0.6:
```
npm install socket.io
```
part of the error log:
```
880 silly lockFile 9cb95944--npmjs-org-json3-json3-3-2-6-tgz http://registry.npmjs.org/json3/-/json3-3.2.6.tgz
881 verbose lock http://registry.npmjs.org/json3/-/json3-3.2.6.tgz C:\Users\dengzhl9\AppData\Roaming\npm-cache\9cb95944--npmjs-org-json3-json3-3-2-6-tgz.lock
882 verbose addRemoteTarball [ 'http://registry.npmjs.org/json3/-/json3-3.2.6.tgz',
882 verbose addRemoteTarball   'f6efc93c06a04de9aec53053df2559bb19e2038b' ]
883 info retry fetch attempt 1 at 12:16:52
884 verbose fetch to= c:\temp\npm-35944-RT6xEBbm\1405570612244-0.050692107528448105\tmp.tgz
885 http GET http://registry.npmjs.org/json3/-/json3-3.2.6.tgz
886 error TypeError: Request path contains unescaped characters.
886 error     at new ClientRequest (_http_client.js:73:11)
886 error     at TunnelingAgent.exports.request (http.js:52:10)
886 error     at TunnelingAgent.createSocket (d:\software\install\nodejs\node_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:117:25)
886 error     at TunnelingAgent.createSecureSocket [as createSocket] (d:\software\install\nodejs\node_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:184:41)
886 error     at TunnelingAgent.addRequest (d:\software\install\nodejs\node_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:80:8)
886 error     at new ClientRequest (_http_client.js:153:16)
886 error     at Object.exports.request (http.js:52:10)
886 error     at Object.exports.request (https.js:136:15)
886 error     at Request.start (d:\software\install\nodejs\node_modules\npm\node_modules\request\request.js:583:30)
886 error     at Request.end (d:\software\install\nodejs\node_modules\npm\node_modules\request\request.js:1237:28)
887 error If you need help, you may report this *entire* log,
887 error including the npm and node versions, at:
887 error     <http://github.com/npm/npm/issues>
888 error System Windows_NT 6.1.7601
889 error command "d:\\software\\install\\nodejs\\node.exe" "d:\\software\\install\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "socket.io"
890 error cwd d:\temp\koa
891 error node -v v0.11.13
892 error npm -v 1.4.9
893 verbose exit [ 1, true ]
```

**Comment by smikes** [comment]
Can this issue be closed?

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as resolved / abandoned.
