### ISSUE TITLE
install -g learnyounode

### ISSUE THREAD

**Issue by cesenergy** [npm/npm#5907]
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'learnyounode' ]
2 info using npm@1.4.21
3 info using node@v0.10.30
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 verbose cache add [ 'learnyounode', null ]
6 verbose cache add name=undefined spec="learnyounode" args=["learnyounode",null]
7 verbose parsed url { protocol: null,
7 verbose parsed url   slashes: null,
7 verbose parsed url   auth: null,
7 verbose parsed url   host: null,
7 verbose parsed url   port: null,
7 verbose parsed url   hostname: null,
7 verbose parsed url   hash: null,
7 verbose parsed url   search: null,
7 verbose parsed url   query: null,
7 verbose parsed url   pathname: 'learnyounode',
7 verbose parsed url   path: 'learnyounode',
7 verbose parsed url   href: 'learnyounode' }
8 silly lockFile 8d456d9f-learnyounode learnyounode
9 verbose lock learnyounode C:\Users\puskurus\AppData\Roaming\npm-cache\8d456d9f-learnyounode.lock
10 silly lockFile 8d456d9f-learnyounode learnyounode
11 silly lockFile 8d456d9f-learnyounode learnyounode
12 verbose addNamed [ 'learnyounode', '' ]
13 verbose addNamed [ null, '*' ]
14 silly lockFile a353de34-learnyounode learnyounode@
15 verbose lock learnyounode@ C:\Users\puskurus\AppData\Roaming\npm-cache\a353de34-learnyounode.lock
16 silly addNameRange { name: 'learnyounode', range: '*', hasData: false }
17 verbose request where is /learnyounode
18 verbose request registry https://registry.npmjs.org/
19 verbose request id dfa9b5fcf2cd8760
20 verbose url raw /learnyounode
21 verbose url resolving [ 'https://registry.npmjs.org/', './learnyounode' ]
22 verbose url resolved https://registry.npmjs.org/learnyounode
23 verbose request where is https://registry.npmjs.org/learnyounode
24 info trying registry request attempt 1 at 07:29:25
25 http GET https://registry.npmjs.org/learnyounode
26 info retry will retry, error on last attempt: Error: 4496:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:openssl\ssl\s23_clnt.c:787:
27 info trying registry request attempt 2 at 07:29:36
28 http GET https://registry.npmjs.org/learnyounode
29 info retry will retry, error on last attempt: Error: 4496:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:openssl\ssl\s23_clnt.c:787:
30 info trying registry request attempt 3 at 07:30:37
31 http GET https://registry.npmjs.org/learnyounode
32 silly lockFile a353de34-learnyounode learnyounode@
33 silly lockFile a353de34-learnyounode learnyounode@
34 error Error: 4496:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:openssl\ssl\s23_clnt.c:787:
34 error
34 error     at SlabBuffer.use (tls.js:234:18)
34 error     at CleartextStream.read [as _read] (tls.js:454:29)
34 error     at CleartextStream.Readable.read (_stream_readable.js:340:10)
34 error     at EncryptedStream.write [as _write] (tls.js:368:25)
34 error     at doWrite (_stream_writable.js:225:10)
34 error     at writeOrBuffer (_stream_writable.js:215:5)
34 error     at EncryptedStream.Writable.write (_stream_writable.js:182:11)
34 error     at write (_stream_readable.js:601:24)
34 error     at flow (_stream_readable.js:610:7)
34 error     at Socket.pipeOnReadable (_stream_readable.js:642:5)
34 error     at Socket.emit (events.js:92:17)
34 error     at emitReadable_ (_stream_readable.js:426:10)
35 error If you need help, you may report this *entire* log,
35 error including the npm and node versions, at:
35 error     <http://github.com/npm/npm/issues>
36 error System Windows_NT 6.1.7601
37 error command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "learnyounode"
38 error cwd C:\Apps\NodeJS
39 error node -v v0.10.30
40 error npm -v 1.4.21
41 verbose exit [ 1, true ]
```

**Comment by smikes** [comment]
Is this still a problem for you?

This looks like a problem with SSL in `node` -- you might need to update to a newer `node` (latest stable is 0.10.36)

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.4.21. Can you try updating your npm installation?

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as resolved / abandoned. Frequently SSL errors like this are also a consequence of npm not being configured properly for use with proxies, so those who search their way to this issue might want to start there in their troubleshooting efforts.
