### ISSUE TITLE
Learning module install failure

### ISSUE THREAD

**Issue by TechDreamer** [npm/npm#5931]
I'm having issues installing the learning modules located at http://nodeschool.io/#learn-you-node using the command "npm install -g learnyounode". Everything fails. I did a fresh, first-time install of node.js using node-v0.10.30-x64.msi, restarted, typed the command into the native windows command prompt.

Not sure how to find out what version of npm I have. I'm using a new laptop with Windows7 but found this in the npm-shrinkwrap.connonical.json file: npmconf@0.0.24","version":"0.0.24".

Here is the complete log file:

```
8 silly lockFile 8d456d9f-learnyounode learnyounode
9 verbose lock learnyounode C:\Users\dd0c43220\AppData\Roaming\npm-cache\8d456d9f-learnyounode.lock
10 silly lockFile 8d456d9f-learnyounode learnyounode
11 silly lockFile 8d456d9f-learnyounode learnyounode
12 verbose addNamed [ 'learnyounode', '' ]
13 verbose addNamed [ null, '*' ]
14 silly lockFile a353de34-learnyounode learnyounode@
15 verbose lock learnyounode@ C:\Users\dd0c43220\AppData\Roaming\npm-cache\a353de34-learnyounode.lock
16 silly addNameRange { name: 'learnyounode', range: '*', hasData: false }
17 verbose request where is /learnyounode
18 verbose request registry https://registry.npmjs.org/
19 verbose request id 78c7a6a91fca75aa
20 verbose url raw /learnyounode
21 verbose url resolving [ 'https://registry.npmjs.org/', './learnyounode' ]
22 verbose url resolved https://registry.npmjs.org/learnyounode
23 verbose request where is https://registry.npmjs.org/learnyounode
24 info trying registry request attempt 1 at 15:35:00
25 http GET https://registry.npmjs.org/learnyounode
26 info retry will retry, error on last attempt: Error: DEPTH_ZERO_SELF_SIGNED_CERT
27 info trying registry request attempt 2 at 15:35:10
28 http GET https://registry.npmjs.org/learnyounode
29 info retry will retry, error on last attempt: Error: DEPTH_ZERO_SELF_SIGNED_CERT
30 info trying registry request attempt 3 at 15:36:11
31 http GET https://registry.npmjs.org/learnyounode
32 silly lockFile a353de34-learnyounode learnyounode@
33 silly lockFile a353de34-learnyounode learnyounode@
34 error Error: DEPTH_ZERO_SELF_SIGNED_CERT
34 error     at SecurePair.<anonymous> (tls.js:1367:32)
34 error     at SecurePair.emit (events.js:92:17)
34 error     at SecurePair.maybeInitFinished (tls.js:979:10)
34 error     at CleartextStream.read [as _read] (tls.js:471:13)
34 error     at CleartextStream.Readable.read (_stream_readable.js:340:10)
34 error     at EncryptedStream.write [as _write] (tls.js:368:25)
34 error     at doWrite (_stream_writable.js:225:10)
34 error     at writeOrBuffer (_stream_writable.js:215:5)
34 error     at EncryptedStream.Writable.write (_stream_writable.js:182:11)
34 error     at write (_stream_readable.js:601:24)
34 error     at flow (_stream_readable.js:610:7)
34 error     at Socket.pipeOnReadable (_stream_readable.js:642:5)
35 error If you need help, you may report this *entire* log,
35 error including the npm and node versions, at:
35 error     <http://github.com/npm/npm/issues>
36 error System Windows_NT 6.1.7601
37 error command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "learnyounode"
38 error cwd C:\Users\dd0c43220
39 error node -v v0.10.30
40 error npm -v 1.4.21
41 verbose exit [ 1, true ]
```

**Comment by smikes** [comment]
Is this still a problem for you?

Could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.4.21. Can you try updating your npm installation?

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as abandoned.
