### ISSUE TITLE
Grunt Throwing this error am I missing something?

### ISSUE THREAD

**Issue by hubbcap** [npm/npm#5939]
```
module.js:340
    throw err;
          ^
Error: Cannot find module 'coffee-script'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Volumes/responsivetechdevelopment.com/public_html/site/node_modules/grunt/lib/grunt.js:16:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by othiym23** [comment]
Closing as abandoned.
