### ISSUE TITLE
Error: 1073880192:error:0407006A

### ISSUE THREAD

**Issue by femarschall** [npm/npm#5983]
Everytime I try to install anything I get this error and I have no clue on what's the cause.
Should I install something that is missing?
I cannot find rsa_pk1.c file.
This is what happens:

```
DiskStation> npm install grunt
npm http GET https://registry.npmjs.org/grunt
npm http GET https://registry.npmjs.org/grunt
npm http GET https://registry.npmjs.org/grunt
npm ERR! Error: 1073880192:error:0407006A:rsa routines:RSA_padding_check_PKCS1_type_1:block type is not 01:../deps/openssl/openssl/crypto/rsa/rsa_pk1.c:100:
npm ERR! 1073880192:error:04067072:rsa routines:RSA_EAY_PUBLIC_DECRYPT:padding check failed:../deps/openssl/openssl/crypto/rsa/rsa_eay.c:721:
npm ERR! 1073880192:error:1408D07B:SSL routines:SSL3_GET_KEY_EXCHANGE:bad signature:../deps/openssl/openssl/ssl/s3_clnt.c:1813:
npm ERR!
npm ERR!     at SlabBuffer.use (tls.js:232:18)
npm ERR!     at CleartextStream.read [as _read] (tls.js:417:29)
npm ERR!     at CleartextStream.Readable.read (_stream_readable.js:320:10)
npm ERR!     at EncryptedStream.write [as _write] (tls.js:344:25)
npm ERR!     at doWrite (_stream_writable.js:219:10)
npm ERR!     at writeOrBuffer (_stream_writable.js:209:5)
npm ERR!     at EncryptedStream.Writable.write (_stream_writable.js:180:11)
npm ERR!     at write (_stream_readable.js:573:24)
npm ERR!     at flow (_stream_readable.js:582:7)
npm ERR!     at Socket.pipeOnReadable (_stream_readable.js:614:5)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 2.6.32.12
npm ERR! command "/usr/local/node/bin/node" "/volume1/@appstore/node/bin/npm" "install" "grunt"
npm ERR! cwd /volume1/web
npm ERR! node -v v0.10.6
npm ERR! npm -v 1.2.18
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /volume1/web/npm-debug.log
npm ERR! not ok code 0
```

**Comment by othiym23** [comment]
It turns out that I actually have a Synology NAS now, so I can take a look a this. Looks like I have a bunch to learn about running Node on Intel Atom, though. For now, though, I'm going to close this one as abandoned, since nobody got back to @smikes over the last month. I'll report back what I learn.
