### ISSUE TITLE
Error: UNABLE_TO_VERIFY_LEAF_SIGNATURE installing karma

### ISSUE THREAD

**Issue by alvipeo** [npm/npm#6017]
Have a fresh node install, trying to install karma (npm install -g karma) and getting this :( :

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'karma' ]
2 info using npm@1.4.23
3 info using node@v0.10.31
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 verbose cache add [ 'karma', null ]
6 verbose cache add name=undefined spec="karma" args=["karma",null]
7 verbose parsed url { protocol: null,
7 verbose parsed url   slashes: null,
7 verbose parsed url   auth: null,
7 verbose parsed url   host: null,
7 verbose parsed url   port: null,
7 verbose parsed url   hostname: null,
7 verbose parsed url   hash: null,
7 verbose parsed url   search: null,
7 verbose parsed url   query: null,
7 verbose parsed url   pathname: 'karma',
7 verbose parsed url   path: 'karma',
7 verbose parsed url   href: 'karma' }
8 silly lockFile 512423cb-karma karma
9 verbose lock karma C:\Users\bachinskiy\AppData\Roaming\npm-cache\512423cb-karma.lock
10 silly lockFile 512423cb-karma karma
11 silly lockFile 512423cb-karma karma
12 verbose addNamed [ 'karma', '' ]
13 verbose addNamed [ null, '*' ]
14 silly lockFile cd7961bb-karma karma@
15 verbose lock karma@ C:\Users\bachinskiy\AppData\Roaming\npm-cache\cd7961bb-karma.lock
16 silly addNameRange { name: 'karma', range: '*', hasData: false }
17 verbose request where is /karma
18 verbose request registry https://registry.npmjs.org/
19 verbose request id f03253721b4efc61
20 verbose url raw /karma
21 verbose url resolving [ 'https://registry.npmjs.org/', './karma' ]
22 verbose url resolved https://registry.npmjs.org/karma
23 verbose request where is https://registry.npmjs.org/karma
24 info trying registry request attempt 1 at 15:01:09
25 http GET https://registry.npmjs.org/karma
26 info retry will retry, error on last attempt: Error: UNABLE_TO_VERIFY_LEAF_SIGNATURE
27 info trying registry request attempt 2 at 15:01:20
28 http GET https://registry.npmjs.org/karma
29 info retry will retry, error on last attempt: Error: UNABLE_TO_VERIFY_LEAF_SIGNATURE
30 info trying registry request attempt 3 at 15:02:20
31 http GET https://registry.npmjs.org/karma
32 silly lockFile cd7961bb-karma karma@
33 silly lockFile cd7961bb-karma karma@
34 error Error: UNABLE_TO_VERIFY_LEAF_SIGNATURE
34 error     at SecurePair.<anonymous> (tls.js:1367:32)
34 error     at SecurePair.emit (events.js:92:17)
34 error     at SecurePair.maybeInitFinished (tls.js:979:10)
34 error     at CleartextStream.read [as _read] (tls.js:471:13)
34 error     at CleartextStream.Readable.read (_stream_readable.js:340:10)
34 error     at EncryptedStream.write [as _write] (tls.js:368:25)
34 error     at doWrite (_stream_writable.js:225:10)
34 error     at writeOrBuffer (_stream_writable.js:215:5)
34 error     at EncryptedStream.Writable.write (_stream_writable.js:182:11)
34 error     at write (_stream_readable.js:601:24)
34 error     at flow (_stream_readable.js:610:7)
34 error     at Socket.pipeOnReadable (_stream_readable.js:642:5)
35 error If you need help, you may report this *entire* log,
35 error including the npm and node versions, at:
35 error     <http://github.com/npm/npm/issues>
36 error System Windows_NT 6.2.9200
37 error command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "karma"
38 error cwd D:\Source\Tests\TypeaheadTestsRun
39 error node -v v0.10.31
40 error npm -v 1.4.23
41 verbose exit [ 1, true ]
```

**Comment by othiym23** [comment]
Closing as resolved / abandoned.
