### ISSUE TITLE
ERR! TypeERROR: Cannot call method 'replace' of null

### ISSUE THREAD

**Issue by jasonarcala-nliven** [npm/npm#6041]
getting this error while trying to make a build 
```
$ make                                                                                                                                                   [13:22:54]
#
# NPM Update needed.
#
npm update
npm ERR! TypeError: Cannot call method 'replace' of null
npm ERR!     at cf (/Users/jason.arcala/local/lib/node_modules/npm/node_modules/npm-cache-filename/index.js:14:22)
npm ERR!     at RegClient.get (/Users/jason.arcala/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:28:20)
npm ERR!     at shouldUpdate (/Users/jason.arcala/local/lib/node_modules/npm/lib/outdated.js:272:16)
npm ERR!     at /Users/jason.arcala/local/lib/node_modules/npm/lib/outdated.js:236:7
npm ERR!     at /Users/jason.arcala/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:54:35
npm ERR!     at Array.forEach (native)
npm ERR!     at /Users/jason.arcala/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:54:11
npm ERR!     at Array.forEach (native)
npm ERR!     at asyncMap (/Users/jason.arcala/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:53:8)
npm ERR!     at next (/Users/jason.arcala/local/lib/node_modules/npm/lib/outdated.js:235:5)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 13.3.0
npm ERR! command "node" "/Users/jason.arcala/local/bin/npm" "update"
npm ERR! cwd /Users/jason.arcala/Documents/js-sequence-diagrams
npm ERR! node -v v0.10.31
npm ERR! npm -v 1.4.24
npm ERR! type non_object_property_call
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/jason.arcala/Documents/js-sequence-diagrams/npm-debug.log
npm ERR! not ok code 0
make: *** [node_modules] Error 1
FAIL
```

**Comment by kmanion** [comment]
Hi @jasonarcala-nliven, we're trying to close out some of the older support issues. Please don't hesitate to reopen if you are still running into this or email us at support@npmjs.com
