### ISSUE TITLE
Installation fails openssh password request

### ISSUE THREAD

**Issue by fanelmar** [npm/npm#6228]
I try to install Oracle Linux 6.5 on steroids, the prerequisites are good but in the installation asks openssh password and then fails.

```
[xxxx@xxxx]$ npm install steroids -g
> steroids@3.5.8 preinstall /home/fanelmar/.nvm/v0.10.32/lib/node_modules/steroids
> node ./bin/check-node-version && node ./bin/preinstall

Checking for compatibility with Node.js version v0.10.32 ...

... Node version OK



AppGyver Steroids 3.5.8 installation

If have any problems, please visit our forums at http://forums.appgyver.com
        
We are now trying to detect required dependencies and problems. Some dependencies (like dtrace-provider and node-sass) will print ugly warnings to the screen, but everything will be fine.

  - The AppGyver team (contact@appgyver.com)

 
Starting installation in 3 seconds.


Checking for required components ...

  Found gcc, good.
  Found make, good.
  Found git, good.

Dependencies ok!
npm ERR! git clone https://git@github.com/AppGyver/incubator-ripple.git Initialized empty Git repository in /home/fanelmar/.npm/_git-remotes/https-git-github-com-AppGyver-incubator-ripple-git-2c417fa2/
npm ERR! Error: Command failed: 
npm ERR!     at ChildProcess.exithandler (child_process.js:648:15)
npm ERR!     at ChildProcess.emit (events.js:98:17)
npm ERR!     at maybeClose (child_process.js:756:16)
npm ERR!     at Process.ChildProcess._handle.onexit (child_process.js:823:5)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.8.13-16.2.1.el6uek.x86_64
npm ERR! command "/home/fanelmar/.nvm/v0.10.32/bin/node" "/home/fanelmar/.nvm/v0.10.32/bin/npm" "install" "steroids" "-g"
npm ERR! cwd /home/fanelmar
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! code 128
npm ERR! not ok code 0
```

**Comment by othiym23** [comment]
Closing as resolved / abandoned.
