### ISSUE TITLE
`npm shrinkwrap --dev` failed on npm 2.1.3 

### ISSUE THREAD

**Issue by vvakame** [npm/npm#6506]
I want to create npm-shrinkwrap.json with npm 2.x.
but I can't it.
`npm shrinkwrap --dev` works fine in npm 1.4.24.

```
$ node -v
v0.10.32
$ npm -v
1.4.24
$ npm shrinkwrap --dev
wrote npm-shrinkwrap.json
$ npm -v
2.1.3
$ npm shrinkwrap --dev
...error message...
```

```
$ cat npm-debug.log                                                                                                                                                           
0 info it worked if it ends with ok
1 verbose cli [ 'node',
1 verbose cli   '/Users/vvakame/.nodebrew/current/bin/npm',
1 verbose cli   'shrinkwrap',
1 verbose cli   '--dev' ]
2 info using npm@2.1.3
3 info using node@v0.10.32
4 verbose node symlink /Users/vvakame/.nodebrew/current/bin/node
5 warn unmet dependency /private/tmp/foobar/node_modules/karma-coverage/node_modules/ibrik/node_modules/coffee-script-redux/node_modules/esmangle requires estraverse@'~ 1.3.2' but will load
5 warn unmet dependency /private/tmp/foobar/node_modules/karma-coverage/node_modules/ibrik/node_modules/estraverse,
5 warn unmet dependency which is version 1.5.1
6 warn unmet dependency /private/tmp/foobar/node_modules/karma-coverage/node_modules/ibrik/node_modules/coffee-script-redux/node_modules/escodegen requires estraverse@'~1.3.0' but will load
6 warn unmet dependency /private/tmp/foobar/node_modules/karma-coverage/node_modules/ibrik/node_modules/estraverse,
6 warn unmet dependency which is version 1.5.1
7 warn unmet dependency /private/tmp/foobar/node_modules/karma-coverage/node_modules/ibrik/node_modules/istanbul/node_modules/escodegen requires esprima@'~1.1.1' but will load
7 warn unmet dependency /private/tmp/foobar/node_modules/karma-coverage/node_modules/ibrik/node_modules/istanbul/node_modules/esprima,
7 warn unmet dependency which is version 1.2.2
8 warn unmet dependency /private/tmp/foobar/node_modules/karma-coverage/node_modules/ibrik/node_modules/istanbul/node_modules/handlebars requires optimist@'~0.3' but will load
8 warn unmet dependency /private/tmp/foobar/node_modules/karma-coverage/node_modules/ibrik/node_modules/optimist,
8 warn unmet dependency which is version 0.6.1
9 warn unmet dependency /private/tmp/foobar/node_modules/karma-coverage/node_modules/ibrik/node_modules/istanbul/node_modules/fileset requires glob@'3.x' but will load
9 warn unmet dependency /private/tmp/foobar/node_modules/glob,
9 warn unmet dependency which is version 4.0.6
10 warn unmet dependency /private/tmp/foobar/node_modules/karma-coverage/node_modules/ibrik/node_modules/istanbul/node_modules/js-yaml requires esprima@'~ 1.0.2' but will load
10 warn unmet dependency /private/tmp/foobar/node_modules/karma-coverage/node_modules/ibrik/node_modules/istanbul/node_modules/esprima,
10 warn unmet dependency which is version 1.2.2
11 verbose stack Error: Problems were encountered
11 verbose stack Please correct and try again.
11 verbose stack invalid: glob@4.0.6 /private/tmp/foobar/node_modules/glob
11 verbose stack missing: inherits@2, required by glob@3.2.11
11 verbose stack missing: minimatch@0.3, required by glob@3.2.11
11 verbose stack missing: array-uniq@^0.1.0, required by array-union@0.1.0
11 verbose stack missing: lru-cache@2, required by minimatch@0.3.0
11 verbose stack missing: sigmund@~1.0.0, required by minimatch@0.3.0
11 verbose stack missing: lru-cache@2, required by minimatch@0.2.14
11 verbose stack missing: sigmund@~1.0.0, required by minimatch@0.2.14
11 verbose stack missing: deep-equal@~0.2.1, required by escallmatch@0.3.1
11 verbose stack missing: esprima@~1.2.2, required by escallmatch@0.3.1
11 verbose stack missing: espurify@~0.1.3, required by escallmatch@0.3.1
11 verbose stack missing: estraverse@~1.5.1, required by escallmatch@0.3.1
11 verbose stack missing: traverse@~0.6.6, required by stringifier@0.1.1
11 verbose stack missing: ansi-regex@^0.2.0, required by has-ansi@0.1.0
11 verbose stack missing: ansi-regex@^0.2.1, required by strip-ansi@0.3.0
11 verbose stack missing: commander@~2.1.0, required by ws@0.4.32
11 verbose stack missing: nan@~1.0.0, required by ws@0.4.32
11 verbose stack missing: tinycolor@0.x, required by ws@0.4.32
11 verbose stack missing: options@>=0.0.5, required by ws@0.4.32
11 verbose stack missing: zeparser@0.0.5, required by active-x-obfuscator@0.0.1
11 verbose stack missing: minimist@0.0.8, required by mkdirp@0.5.0
11 verbose stack missing: core-util-is@~1.0.0, required by readable-stream@1.1.13
11 verbose stack missing: isarray@0.0.1, required by readable-stream@1.1.13
11 verbose stack missing: string_decoder@~0.10.x, required by readable-stream@1.1.13
11 verbose stack missing: inherits@~2.0.1, required by readable-stream@1.1.13
11 verbose stack missing: abbrev@1, required by nopt@2.1.2
11 verbose stack missing: esprima@~ 1.0.2, required by esmangle@0.0.17
11 verbose stack missing: escope@~ 1.0.0, required by esmangle@0.0.17
11 verbose stack missing: esshorten@~ 0.0.2, required by esmangle@0.0.17
11 verbose stack missing: amdefine@>=0.0.4, required by source-map@0.1.11
11 verbose stack missing: esprima@~1.0.2, required by escodegen@0.0.28
11 verbose stack invalid: esprima@1.2.2 /private/tmp/foobar/node_modules/karma-coverage/node_modules/ibrik/node_modules/istanbul/node_modules/esprima
11 verbose stack missing: esutils@~1.0.0, required by escodegen@1.3.3
11 verbose stack missing: minimist@0.0.8, required by mkdirp@0.5.0
11 verbose stack missing: argparse@~ 0.1.11, required by js-yaml@3.2.2
11 verbose stack invalid: estraverse@1.5.1 /private/tmp/foobar/node_modules/karma-coverage/node_modules/ibrik/node_modules/estraverse
11 verbose stack missing: amdefine@>=0.0.4, required by source-map@0.1.40
11 verbose stack invalid: optimist@0.6.1 /private/tmp/foobar/node_modules/karma-coverage/node_modules/ibrik/node_modules/optimist
11 verbose stack missing: config-chain@~1.1.8, required by npmconf@2.0.9
11 verbose stack missing: inherits@~2.0.0, required by npmconf@2.0.9
11 verbose stack missing: ini@^1.2.0, required by npmconf@2.0.9
11 verbose stack missing: nopt@~3.0.1, required by npmconf@2.0.9
11 verbose stack missing: once@~1.3.0, required by npmconf@2.0.9
11 verbose stack missing: osenv@^0.1.0, required by npmconf@2.0.9
11 verbose stack missing: semver@2 || 3 || 4, required by npmconf@2.0.9
11 verbose stack missing: uid-number@0.0.5, required by npmconf@2.0.9
11 verbose stack missing: bl@~0.9.0, required by request@2.42.0
11 verbose stack missing: caseless@~0.6.0, required by request@2.42.0
11 verbose stack missing: forever-agent@~0.5.0, required by request@2.42.0
11 verbose stack missing: qs@~1.2.0, required by request@2.42.0
11 verbose stack missing: json-stringify-safe@~5.0.0, required by request@2.42.0
11 verbose stack missing: mime-types@~1.0.1, required by request@2.42.0
11 verbose stack missing: node-uuid@~1.4.0, required by request@2.42.0
11 verbose stack missing: tunnel-agent@~0.4.0, required by request@2.42.0
11 verbose stack missing: throttleit@~0.0.2, required by request-progress@0.3.1
11 verbose stack missing: amdefine@>=0.0.4, required by source-map@0.1.40
11 verbose stack extraneous: minichain@0.0.1 /private/tmp/foobar/node_modules/grunt-tsd/node_modules/tsd/node_modules/minichain
11 verbose stack     at shrinkwrap_ (/Users/vvakame/.nodebrew/node/v0.10.32/lib/node_modules/npm/lib/shrinkwrap.js:31:15)
11 verbose stack     at /Users/vvakame/.nodebrew/node/v0.10.32/lib/node_modules/npm/lib/shrinkwrap.js:25:5
11 verbose stack     at /Users/vvakame/.nodebrew/node/v0.10.32/lib/node_modules/npm/lib/ls.js:46:30
11 verbose stack     at /Users/vvakame/.nodebrew/node/v0.10.32/lib/node_modules/npm/node_modules/read-installed/read-installed.js:138:5
11 verbose stack     at /Users/vvakame/.nodebrew/node/v0.10.32/lib/node_modules/npm/node_modules/read-installed/read-installed.js:251:14
11 verbose stack     at cb (/Users/vvakame/.nodebrew/node/v0.10.32/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
11 verbose stack     at /Users/vvakame/.nodebrew/node/v0.10.32/lib/node_modules/npm/node_modules/read-installed/read-installed.js:251:14
11 verbose stack     at cb (/Users/vvakame/.nodebrew/node/v0.10.32/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
11 verbose stack     at /Users/vvakame/.nodebrew/node/v0.10.32/lib/node_modules/npm/node_modules/read-installed/read-installed.js:251:14
11 verbose stack     at cb (/Users/vvakame/.nodebrew/node/v0.10.32/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
12 verbose cwd /private/tmp/foobar
13 error Darwin 13.4.0
14 error argv "node" "/Users/vvakame/.nodebrew/current/bin/npm" "shrinkwrap" "--dev"
15 error node v0.10.32
16 error npm  v2.1.3
17 error Problems were encountered
17 error Please correct and try again.
17 error invalid: glob@4.0.6 /private/tmp/foobar/node_modules/glob
17 error missing: inherits@2, required by glob@3.2.11
17 error missing: minimatch@0.3, required by glob@3.2.11
17 error missing: array-uniq@^0.1.0, required by array-union@0.1.0
17 error missing: lru-cache@2, required by minimatch@0.3.0
17 error missing: sigmund@~1.0.0, required by minimatch@0.3.0
17 error missing: lru-cache@2, required by minimatch@0.2.14
17 error missing: sigmund@~1.0.0, required by minimatch@0.2.14
17 error missing: deep-equal@~0.2.1, required by escallmatch@0.3.1
17 error missing: esprima@~1.2.2, required by escallmatch@0.3.1
17 error missing: espurify@~0.1.3, required by escallmatch@0.3.1
17 error missing: estraverse@~1.5.1, required by escallmatch@0.3.1
17 error missing: traverse@~0.6.6, required by stringifier@0.1.1
17 error missing: ansi-regex@^0.2.0, required by has-ansi@0.1.0
17 error missing: ansi-regex@^0.2.1, required by strip-ansi@0.3.0
17 error missing: commander@~2.1.0, required by ws@0.4.32
17 error missing: nan@~1.0.0, required by ws@0.4.32
17 error missing: tinycolor@0.x, required by ws@0.4.32
17 error missing: options@>=0.0.5, required by ws@0.4.32
17 error missing: zeparser@0.0.5, required by active-x-obfuscator@0.0.1
17 error missing: minimist@0.0.8, required by mkdirp@0.5.0
17 error missing: core-util-is@~1.0.0, required by readable-stream@1.1.13
17 error missing: isarray@0.0.1, required by readable-stream@1.1.13
17 error missing: string_decoder@~0.10.x, required by readable-stream@1.1.13
17 error missing: inherits@~2.0.1, required by readable-stream@1.1.13
17 error missing: abbrev@1, required by nopt@2.1.2
17 error missing: esprima@~ 1.0.2, required by esmangle@0.0.17
17 error missing: escope@~ 1.0.0, required by esmangle@0.0.17
17 error missing: esshorten@~ 0.0.2, required by esmangle@0.0.17
17 error missing: amdefine@>=0.0.4, required by source-map@0.1.11
17 error missing: esprima@~1.0.2, required by escodegen@0.0.28
17 error invalid: esprima@1.2.2 /private/tmp/foobar/node_modules/karma-coverage/node_modules/ibrik/node_modules/istanbul/node_modules/esprima
17 error missing: esutils@~1.0.0, required by escodegen@1.3.3
17 error missing: minimist@0.0.8, required by mkdirp@0.5.0
17 error missing: argparse@~ 0.1.11, required by js-yaml@3.2.2
17 error invalid: estraverse@1.5.1 /private/tmp/foobar/node_modules/karma-coverage/node_modules/ibrik/node_modules/estraverse
17 error missing: amdefine@>=0.0.4, required by source-map@0.1.40
17 error invalid: optimist@0.6.1 /private/tmp/foobar/node_modules/karma-coverage/node_modules/ibrik/node_modules/optimist
17 error missing: config-chain@~1.1.8, required by npmconf@2.0.9
17 error missing: inherits@~2.0.0, required by npmconf@2.0.9
17 error missing: ini@^1.2.0, required by npmconf@2.0.9
17 error missing: nopt@~3.0.1, required by npmconf@2.0.9
17 error missing: once@~1.3.0, required by npmconf@2.0.9
17 error missing: osenv@^0.1.0, required by npmconf@2.0.9
17 error missing: semver@2 || 3 || 4, required by npmconf@2.0.9
17 error missing: uid-number@0.0.5, required by npmconf@2.0.9
17 error missing: bl@~0.9.0, required by request@2.42.0
17 error missing: caseless@~0.6.0, required by request@2.42.0
17 error missing: forever-agent@~0.5.0, required by request@2.42.0
17 error missing: qs@~1.2.0, required by request@2.42.0
17 error missing: json-stringify-safe@~5.0.0, required by request@2.42.0
17 error missing: mime-types@~1.0.1, required by request@2.42.0
17 error missing: node-uuid@~1.4.0, required by request@2.42.0
17 error missing: tunnel-agent@~0.4.0, required by request@2.42.0
17 error missing: throttleit@~0.0.2, required by request-progress@0.3.1
17 error missing: amdefine@>=0.0.4, required by source-map@0.1.40
17 error extraneous: minichain@0.0.1 /private/tmp/foobar/node_modules/grunt-tsd/node_modules/tsd/node_modules/minichain
18 error If you need help, you may report this error at:
18 error     <http://github.com/npm/npm/issues>
19 verbose exit [ 1, true ]
```

this is my package.json.
I'm sorry, I can not make the short reproduction code.

```
$ cat package.json
{
  "name": "sample",
  "version": "0.0.0",
  "private": true,
  "devDependencies": {
    "grunt": "0.4.5",

    "grunt-bower-task": "0.4.0",
    "grunt-wiredep": "1.9.0",

    "grunt-ts": "1.12.1",
    "typescript": "1.1.0-1",
    "grunt-tslint": "0.4.4",
    "grunt-tsd": "0.1.0",
    "grunt-typedoc": "0.2.1",

    "grunt-contrib-clean": "0.6.0",
    "grunt-contrib-less": "0.11.4",
    "grunt-contrib-connect": "0.8.0",
    "grunt-angular-templates": "0.5.7",

    "karma": "0.12.24",
    "grunt-karma": "0.9.0",
    "karma-mocha": "0.1.9",
    "karma-phantomjs-launcher": "0.1.4",
    "karma-chrome-launcher": "0.1.5",
    "karma-ie-launcher": "0.1.5",
    "karma-junit-reporter": "0.2.2",
    "karma-mocha-reporter": "0.3.1",
    "karma-sourcemap-loader": "0.2.0",
    "karma-coverage": "0.2.6",
    "grunt-espower": "0.9.1",
    "power-assert": "0.9.1",

    "glob": "4.0.6",
    "grunt-protractor-runner": "1.1.4",

    "grunt-contrib-watch": "0.6.1",
    "grunt-exec": "0.4.6",
    "load-grunt-tasks": "0.6.0",

    "grunt-notify": "0.3.1",
    "time-grunt": "1.0.0"
  }
}
```

**Comment by smikes** [comment]
Can this issue now be closed? 

It looks like the underlying `npm` bugs have been fixed as of 2.2.0, and the issues in non-`npm` repositories have been reported.

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Yeah, I think this issue can now be closed as resolved.

**Comment by jgacuca567** [comment]
@othiym23 What was the solution because I also got the following error?

**Comment by smikes** [comment]
@jgacuca567 could you please create a new issue describing the error that you see?
