### ISSUE TITLE
Trying to install a workshop tutorial npm install -g learnyoucode but FAILS

### ISSUE THREAD

**Issue by Ziggy23810** [npm/npm#6558]
I install a new SSH Key but still get the same error message:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'learnyounode' ]
2 info using npm@1.4.28
3 info using node@v0.10.32
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 verbose cache add [ 'learnyounode', null ]
6 verbose cache add name=undefined spec="learnyounode" args=["learnyounode",null]
7 verbose parsed url { protocol: null,
7 verbose parsed url   slashes: null,
7 verbose parsed url   auth: null,
7 verbose parsed url   host: null,
7 verbose parsed url   port: null,
7 verbose parsed url   hostname: null,
7 verbose parsed url   hash: null,
7 verbose parsed url   search: null,
7 verbose parsed url   query: null,
7 verbose parsed url   pathname: 'learnyounode',
7 verbose parsed url   path: 'learnyounode',
7 verbose parsed url   href: 'learnyounode' }
8 silly lockFile 8d456d9f-learnyounode learnyounode
9 verbose lock learnyounode C:\Users\walter.luna\AppData\Roaming\npm-cache\8d456d9f-learnyounode.lock
10 silly lockFile 8d456d9f-learnyounode learnyounode
11 silly lockFile 8d456d9f-learnyounode learnyounode
12 verbose addNamed [ 'learnyounode', '' ]
13 verbose addNamed [ null, '*' ]
14 silly lockFile a353de34-learnyounode learnyounode@
15 verbose lock learnyounode@ C:\Users\walter.luna\AppData\Roaming\npm-cache\a353de34-learnyounode.lock
16 silly addNameRange { name: 'learnyounode', range: '*', hasData: false }
17 verbose request where is /learnyounode
18 verbose request registry https://registry.npmjs.org/
19 verbose request id a2b23dc67872f4b7
20 verbose url raw /learnyounode
21 verbose url resolving [ 'https://registry.npmjs.org/', './learnyounode' ]
22 verbose url resolved https://registry.npmjs.org/learnyounode
23 verbose request where is https://registry.npmjs.org/learnyounode
24 info trying registry request attempt 1 at 11:01:27
25 http GET https://registry.npmjs.org/learnyounode
26 info retry will retry, error on last attempt: Error: SELF_SIGNED_CERT_IN_CHAIN
27 info trying registry request attempt 2 at 11:01:37
28 http GET https://registry.npmjs.org/learnyounode
29 info retry will retry, error on last attempt: Error: SELF_SIGNED_CERT_IN_CHAIN
30 info trying registry request attempt 3 at 11:02:38
31 http GET https://registry.npmjs.org/learnyounode
32 silly lockFile a353de34-learnyounode learnyounode@
33 silly lockFile a353de34-learnyounode learnyounode@
34 error Error: SELF_SIGNED_CERT_IN_CHAIN
34 error     at SecurePair.<anonymous> (tls.js:1367:32)
34 error     at SecurePair.emit (events.js:92:17)
34 error     at SecurePair.maybeInitFinished (tls.js:979:10)
34 error     at CleartextStream.read [as _read] (tls.js:471:13)
34 error     at CleartextStream.Readable.read (_stream_readable.js:340:10)
34 error     at EncryptedStream.write [as _write] (tls.js:368:25)
34 error     at doWrite (_stream_writable.js:225:10)
34 error     at writeOrBuffer (_stream_writable.js:215:5)
34 error     at EncryptedStream.Writable.write (_stream_writable.js:182:11)
34 error     at write (_stream_readable.js:601:24)
34 error     at flow (_stream_readable.js:610:7)
34 error     at Socket.pipeOnReadable (_stream_readable.js:642:5)
35 error If you need help, you may report this *entire* log,
35 error including the npm and node versions, at:
35 error     <http://github.com/npm/npm/issues>
36 error System Windows_NT 6.1.7601
37 error command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "learnyounode"
38 error cwd C:\Users\[username-here]
39 error node -v v0.10.32
40 error npm -v 1.4.28
41 verbose exit [ 1, true ]
```

**Comment by othiym23** [comment]
Closing as resolved / abandoned.
