### ISSUE TITLE
`npm install --production` with peerDependencies fails

### ISSUE THREAD

**Issue by ThisIsMissEm** [npm/npm#6581]
I've got a module with `peerDependencies`, when trying to install it where a parent directory has an `node_modules` which satisfies the peerDep, I'm getting the following error:

```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'install', '--color=always' ]
2 info using npm@2.1.5
3 info using node@v0.10.33
4 warn package.json nts-api@0.0.0 No repository field.
5 verbose install where, deps [ '/Users/micheil/Work/NTS/repos/api-server/lib/apps/api', [] ]
6 verbose type non_object_property_load
7 verbose stack TypeError: Cannot read property 'hapi' of undefined
7 verbose stack     at /usr/local/lib/node_modules/npm/lib/install.js:157:33
7 verbose stack     at Array.forEach (native)
7 verbose stack     at /usr/local/lib/node_modules/npm/lib/install.js:156:50
7 verbose stack     at /usr/local/lib/node_modules/npm/lib/install.js:324:22
7 verbose stack     at evalmachine.<anonymous>:207:20
7 verbose stack     at OpenReq.Req.done (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:141:5)
7 verbose stack     at OpenReq.done (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:61:22)
7 verbose stack     at Object.oncomplete (evalmachine.<anonymous>:107:15)
8 verbose cwd /Users/micheil/Work/NTS/repos/api-server/lib/apps/api
9 error Darwin 13.2.0
10 error argv "node" "/usr/local/bin/npm" "install" "--color=always"
11 error node v0.10.33
12 error npm  v2.1.5
13 error Cannot read property 'hapi' of undefined
14 error If you need help, you may report this error at:
14 error     <http://github.com/npm/npm/issues>
15 verbose exit [ 1, true ]
```

The package.json is:

```
{
  "name": "nts-api",
  "version": "0.0.0",
  "description": "The API Plugin for the NTS API Server",
  "main": "index.js",
  "scripts": {
    "test": "lab -Cv",
    "test-cov": "lab -Cv -t 100 -c",
    "test-cov-report": "lab -v -r html -o coverage.html && open coverage.html",
    "audit": "npm shrinkwrap --dev && nsp audit-shrinkwrap && rm npm-shrinkwrap.json",
    "outdated": "npm outdated --depth 0"
  },
  "peerDependencies": {
    "hapi": "^7.1.1"
  },
  "devDependencies": {
    "code": "^1.2.0",
    "lab": "^5.0.1"
  }
}
```

I'm using a setup similar to that which npm/newww uses. Installing without `--production` succeeds.

**Comment by zpao** [comment]
We're a long time out from updates to this but I think I have a repro. The important piece is that this appears to be an issue iff if the `"dependencies"` field is missing from `package.json`. I traced through using npm 2 in https://github.com/facebook/react/issues/5918#issuecomment-174710988. This was different than the original report here about peerDeps being installed somewhere that would be found but I actually think that's a red herring.

Simplest repo:
```sh
echo '{"peerDependencies": { "npm": "*" } }' > package.json
npm install --production
```

**Comment by marcelklehr** [comment]
Just stumbled upon this, too: https://wzrd.in/standalone/vdom-virtualize@latest `dependencies` is [missing as well](https://github.com/marcelklehr/vdom-virtualize/blob/master/package.json), I'll try adding it.
