### ISSUE TITLE
 Error: SELF_SIGNED_CERT_IN_CHAIN behind corporate firewall

### ISSUE THREAD

**Issue by wealthychef1** [npm/npm#6677]
Hi, in my environment, there is a self-signed CA in my chain.  So npm "doesn't work" at all.  I have tried updating npm using the installer from the npm website, but I still get the below error.  
```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'install', '-g', 'javascripting' ]
2 info using npm@1.4.28
3 info using node@v0.10.33
4 verbose cache add [ 'javascripting', null ]
5 verbose cache add name=undefined spec="javascripting" args=["javascripting",null]
6 verbose parsed url { protocol: null,
6 verbose parsed url   slashes: null,
6 verbose parsed url   auth: null,
6 verbose parsed url   host: null,
6 verbose parsed url   port: null,
6 verbose parsed url   hostname: null,
6 verbose parsed url   hash: null,
6 verbose parsed url   search: null,
6 verbose parsed url   query: null,
6 verbose parsed url   pathname: 'javascripting',
6 verbose parsed url   path: 'javascripting',
6 verbose parsed url   href: 'javascripting' }
7 silly lockFile ae6d31f2-javascripting javascripting
8 verbose lock javascripting /Users/cook47/.npm/ae6d31f2-javascripting.lock
9 silly lockFile ae6d31f2-javascripting javascripting
10 silly lockFile ae6d31f2-javascripting javascripting
11 verbose addNamed [ 'javascripting', '' ]
12 verbose addNamed [ null, '*' ]
13 silly lockFile 9ef866d8-javascripting javascripting@
14 verbose lock javascripting@ /Users/cook47/.npm/9ef866d8-javascripting.lock
15 silly addNameRange { name: 'javascripting', range: '*', hasData: false }
16 verbose request where is /javascripting
17 verbose request registry https://registry.npmjs.org/
18 verbose request id 4763b8d2714386d2
19 verbose url raw /javascripting
20 verbose url resolving [ 'https://registry.npmjs.org/', './javascripting' ]
21 verbose url resolved https://registry.npmjs.org/javascripting
22 verbose request where is https://registry.npmjs.org/javascripting
23 info trying registry request attempt 1 at 13:47:06
24 http GET https://registry.npmjs.org/javascripting
25 info retry will retry, error on last attempt: Error: SELF_SIGNED_CERT_IN_CHAIN
26 info trying registry request attempt 2 at 13:47:16
27 http GET https://registry.npmjs.org/javascripting
28 info retry will retry, error on last attempt: Error: SELF_SIGNED_CERT_IN_CHAIN
29 info trying registry request attempt 3 at 13:48:17
30 http GET https://registry.npmjs.org/javascripting
31 silly lockFile 9ef866d8-javascripting javascripting@
32 silly lockFile 9ef866d8-javascripting javascripting@
33 error Error: SELF_SIGNED_CERT_IN_CHAIN
33 error     at SecurePair.<anonymous> (tls.js:1380:32)
33 error     at SecurePair.emit (events.js:92:17)
33 error     at SecurePair.maybeInitFinished (tls.js:979:10)
33 error     at CleartextStream.read [as _read] (tls.js:471:13)
33 error     at CleartextStream.Readable.read (_stream_readable.js:340:10)
33 error     at EncryptedStream.write [as _write] (tls.js:368:25)
33 error     at doWrite (_stream_writable.js:225:10)
33 error     at writeOrBuffer (_stream_writable.js:215:5)
33 error     at EncryptedStream.Writable.write (_stream_writable.js:182:11)
33 error     at write (_stream_readable.js:601:24)
33 error     at flow (_stream_readable.js:610:7)
33 error     at Socket.pipeOnReadable (_stream_readable.js:642:5)
34 error If you need help, you may report this *entire* log,
34 error including the npm and node versions, at:
34 error     <http://github.com/npm/npm/issues>
35 error System Darwin 13.4.0
36 error command "node" "/usr/local/bin/npm" "install" "-g" "javascripting"
37 error cwd /Users/cook47/Downloads
38 error node -v v0.10.33
39 error npm -v 1.4.28
40 verbose exit [ 1, true ]
```

Thanks for any help

**Comment by smikes** [comment]
Is this still a problem for you?

Could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since November 2014. Can you try updating your npm installation?

The easiest way to start with an updated `npm` is to install the latest node version, then update npm, by running `npm -g install npm@latest`

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as abandoned.
