### ISSUE TITLE
npm issue when installing greenbean

### ISSUE THREAD

**Issue by AlishaVarkey** [npm/npm#6722]
```
C:\Windows\system32>npm install green-bean
npm ERR! registry error parsing json
npm ERR! SyntaxError: Unexpected token <
npm ERR! <html><head><title>Apache Tomcat/5.5.28 - Error report</title><style><!
--H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;f
ont-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-c
olor:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:whit
e;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-
serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-seri
f;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;
background:white;color:black;font-size:12px;}A {color : black;}A.name {color : b
lack;}HR {color : #525D76;}--></style> </head><body><h1>HTTP Status 404 - /green
-bean</h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>m
essage</b> <u>/green-bean</u></p><p><b>description</b> <u>The requested resource
 (/green-bean) is not available.</u></p><HR size="1" noshade="noshade"><h3>Apach
e Tomcat/5.5.28</h3></body></html>
npm ERR!     at Object.parse (native)
npm ERR!     at RegClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\
node_modules\npm-registry-client\lib\request.js:274:23)
npm ERR!     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node
_modules\npm-registry-client\lib\request.js:246:65)
npm ERR!     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\
node_modules\request\request.js:236:22)
npm ERR!     at Request.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\no
de_modules\request\request.js:1142:14)
npm ERR!     at Request.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_module
s\npm\node_modules\request\request.js:1096:12)
npm ERR!     at IncomingMessage.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:943:16
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "green-bean"
npm ERR! cwd C:\Windows\system32
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! type unexpected_token
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Windows\system32\npm-debug.log
npm ERR! not ok code 0
```
Is this an issue related to network/proxies etc?

**Comment by smikes** [comment]
Did you ever find a solution to this proxy problem?

Although this may not help with the proxy, I also recommend that you update your `npm` to the latest version.  There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.4.28. Can you try updating your npm installation?

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as abandoned.
