### ISSUE TITLE
Proxy Authentication Required??

### ISSUE THREAD

**Issue by WhiskyLiu** [npm/npm#6727]
```
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\ProgramFiles\\NodeJS\\\\node.exe',


1 verbose cli   'D:\\ProgramFiles\\NodeJS\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'phonegap' ]
2 info using npm@1.4.28
3 info using node@v0.10.33
4 verbose node symlink D:\ProgramFiles\NodeJS\\node.exe
5 verbose cache add [ 'phonegap', null ]
6 verbose cache add name=undefined spec="phonegap" args=["phonegap",null]
7 verbose parsed url { protocol: null,
7 verbose parsed url   slashes: null,
7 verbose parsed url   auth: null,
7 verbose parsed url   host: null,
7 verbose parsed url   port: null,
7 verbose parsed url   hostname: null,
7 verbose parsed url   hash: null,
7 verbose parsed url   search: null,
7 verbose parsed url   query: null,
7 verbose parsed url   pathname: 'phonegap',
7 verbose parsed url   path: 'phonegap',
7 verbose parsed url   href: 'phonegap' }
8 silly lockFile 10db903f-phonegap phonegap
9 verbose lock phonegap C:\Users\z10070043\AppData\Roaming\npm-cache\10db903f-phonegap.lock
10 silly lockFile 10db903f-phonegap phonegap
11 silly lockFile 10db903f-phonegap phonegap
12 verbose addNamed [ 'phonegap', '' ]
13 verbose addNamed [ null, '*' ]
14 silly lockFile 3a6257f3-phonegap phonegap@
15 verbose lock phonegap@ C:\Users\z10070043\AppData\Roaming\npm-cache\3a6257f3-phonegap.lock
16 silly addNameRange { name: 'phonegap', range: '*', hasData: false }
17 verbose request where is /phonegap
18 verbose request registry http://registry.npmjs.org/
19 verbose request id b6f25af96892aa74
20 verbose url raw /phonegap
21 verbose url resolving [ 'http://registry.npmjs.org/', './phonegap' ]
22 verbose url resolved http://registry.npmjs.org/phonegap
23 verbose request where is http://registry.npmjs.org/phonegap
24 info trying registry request attempt 1 at 11:32:33
25 http GET http://registry.npmjs.org/phonegap
26 http 407 http://registry.npmjs.org/phonegap
27 verbose bad json <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
27 verbose bad json <HTML><HEAD><TITLE>Error Message</TITLE>
27 verbose bad json <META http-equiv=Content-Type content="text/html; charset=UTF-8">
27 verbose bad json <STYLE id=L_default_1>A {
27 verbose bad json 	FONT-WEIGHT: bold; FONT-SIZE: 10pt; COLOR: #005a80; FONT-FAMILY: tahoma
27 verbose bad json }
27 verbose bad json A:hover {
27 verbose bad json 	FONT-WEIGHT: bold; FONT-SIZE: 10pt; COLOR: #0d3372; FONT-FAMILY: tahoma
27 verbose bad json }
27 verbose bad json TD {
27 verbose bad json 	FONT-SIZE: 8pt; FONT-FAMILY: tahoma
27 verbose bad json }
27 verbose bad json TD.titleBorder {
27 verbose bad json 	BORDER-RIGHT: #955319 1px solid; BORDER-TOP: #955319 1px solid; PADDING-LEFT: 8px; FONT-WEIGHT: bold; FONT-SIZE: 12pt; VERTICAL-ALIGN: middle; BORDER-LEFT: #955319 0px solid; COLOR: #955319; BORDER-BOTTOM: #955319 1px solid; FONT-FAMILY: tahoma; HEIGHT: 35px; BACKGROUND-COLOR: #d2b87a; TEXT-ALIGN: left
27 verbose bad json }
27 verbose bad json TD.titleBorderx {
27 verbose bad json 	BORDER-RIGHT: #955319 0px solid; BORDER-TOP: #955319 1px solid; PADDING-LEFT: 8px; FONT-WEIGHT: bold; FONT-SIZE: 12pt; VERTICAL-ALIGN: middle; BORDER-LEFT: #955319 1px solid; COLOR: #978c79; BORDER-BOTTOM: #955319 1px solid; FONT-FAMILY: tahoma; HEIGHT: 35px; BACKGROUND-COLOR: #d2b87a; TEXT-ALIGN: left
27 verbose bad json }
27 verbose bad json .TitleDescription {
27 verbose bad json 	FONT-WEIGHT: bold; FONT-SIZE: 12pt; COLOR: black; FONT-FAMILY: tahoma
27 verbose bad json }
27 verbose bad json SPAN.explain {
27 verbose bad json 	FONT-WEIGHT: normal; FONT-SIZE: 10pt; COLOR: #934225
27 verbose bad json }
27 verbose bad json SPAN.TryThings {
27 verbose bad json 	FONT-WEIGHT: normal; FONT-SIZE: 10pt; COLOR: #934225
27 verbose bad json }
27 verbose bad json .TryList {
27 verbose bad json 	MARGIN-TOP: 5px; FONT-WEIGHT: normal; FONT-SIZE: 8pt; COLOR: black; FONT-FAMILY: tahoma
27 verbose bad json }
27 verbose bad json .X {
27 verbose bad json 	BORDER-RIGHT: #955319 1px solid; BORDER-TOP: #955319 1px solid; FONT-WEIGHT: normal; FONT-SIZE: 12pt; BORDER-LEFT: #955319 1px solid; COLOR: #7b3807; BORDER-BOTTOM: #955319 1px solid; FONT-FAMILY: verdana; BACKGROUND-COLOR: #d1c2b4
27 verbose bad json }
27 verbose bad json .adminList {
27 verbose bad json 	MARGIN-TOP: 2px
27 verbose bad json }
27 verbose bad json </STYLE>
27 verbose bad json <META content="MSHTML 6.00.2800.1170" name=GENERATOR></HEAD>
27 verbose bad json <BODY bgColor=#f3f3ed>
27 verbose bad json <TABLE cellSpacing=0 cellPadding=0 width="100%">
27 verbose bad json   <TBODY>
27 verbose bad json   <TR>
27 verbose bad json     <TD class=titleBorderx width=30>
27 verbose bad json       <TABLE height=25 cellSpacing=2 cellPadding=0 width=25 bgColor=black>
27 verbose bad json         <TBODY>
27 verbose bad json         <TR>
27 verbose bad json           <TD id=L_default_x class=x valign=middle align=center>X</TD>
27 verbose bad json         </TR>
27 verbose bad json         </TBODY>
27 verbose bad json       </TABLE>
27 verbose bad json     </TD>
27 verbose bad json     <TD class=titleBorder id=L_default_2>Network Access Message:<SPAN class=TitleDescription> The page cannot be displayed</SPAN> </TD>
27 verbose bad json   </TR>
27 verbose bad json   </TBODY>
27 verbose bad json </TABLE>
27 verbose bad json
27 verbose bad json <TABLE id=spacer>
27 verbose bad json   <TBODY>
27 verbose bad json   <TR>
27 verbose bad json     <TD height=10></TD></TR></TBODY></TABLE>
27 verbose bad json <TABLE width=400>
27 verbose bad json   <TBODY>
27 verbose bad json   <TR>
27 verbose bad json     <TD noWrap width=25></TD>
27 verbose bad json     <TD width=400><SPAN class=explain><ID id=L_default_3><B>Explanation:</B></ID></SPAN><ID id=L_default_4> There is a problem with the page you are trying to reach and it cannot be displayed. </ID><BR><BR>
27 verbose bad json     <B><SPAN class=tryThings><ID id=L_default_5><B>Try the following:</B></ID></SPAN></B>
27 verbose bad json       <UL class=TryList>
27 verbose bad json         <LI id=L_default_6><B>Refresh page:</B> Search for the page again by clicking the Refresh button. The timeout may have occurred due to Internet congestion.
27 verbose bad json <LI id=L_default_7><B>Check spelling:</B> Check that you typed the Web page address correctly. The address may have been mistyped.
27 verbose bad json <LI id=L_default_8><B>Access from a link:</B> If there is a link to the page you are looking for, try accessing the page from that link.
27 verbose bad json
27 verbose bad json       </UL>
27 verbose bad json <ID id=L_default_9>If you are still not able to view the requested page, try contacting your administrator or Helpdesk.</ID> <BR><BR>
27 verbose bad json     </TD>
27 verbose bad json   </TR>
27 verbose bad json   </TBODY>
27 verbose bad json </TABLE>
27 verbose bad json
27 verbose bad json <TABLE id=spacer><TBODY><TR><TD height=15></TD></TR></TBODY></TABLE>
27 verbose bad json
27 verbose bad json <TABLE width=400>
27 verbose bad json   <TBODY>
27 verbose bad json   <TR>
27 verbose bad json     <TD noWrap width=25></TD>
27 verbose bad json     <TD width=400 id=L_default_10><B>Technical Information (for support personnel)</B>
27 verbose bad json       <UL class=adminList>
27 verbose bad json         <LI id=L_default_11>Error Code: 407 Proxy Authentication Required. Forefront TMG requires authorization to fulfill the request. Access to the Web Proxy filter is denied. (12209)
27 verbose bad json <LI id=L_default_12>IP Address: 10.41.24.27
27 verbose bad json <LI id=L_default_13>Date: 11/18/2014 3:32:33 AM [GMT]
27 verbose bad json <LI id=L_default_14>Server: CNZHSTISA.wzs.wistron
27 verbose bad json <LI id=L_default_15>Source: proxy
27 verbose bad json
27 verbose bad json       </UL>
27 verbose bad json     </TD>
27 verbose bad json   </TR>
27 verbose bad json   </TBODY>
27 verbose bad json </TABLE>
27 verbose bad json
27 verbose bad json </BODY>
27 verbose bad json </HTML>
28 error registry error parsing json
29 verbose headers { via: '1.1 CNZHSTISA',
29 verbose headers   'proxy-authenticate': 'Negotiate, Kerberos, NTLM',
29 verbose headers   connection: 'Keep-Alive',
29 verbose headers   'proxy-connection': 'Keep-Alive',
29 verbose headers   pragma: 'no-cache',
29 verbose headers   'cache-control': 'no-cache',
29 verbose headers   'content-type': 'text/html',
29 verbose headers   'content-length': '4126  ' }
30 silly registry.get cb [ 407,
30 silly registry.get   { via: '1.1 CNZHSTISA',
30 silly registry.get     'proxy-authenticate': 'Negotiate, Kerberos, NTLM',
30 silly registry.get     connection: 'Keep-Alive',
30 silly registry.get     'proxy-connection': 'Keep-Alive',
30 silly registry.get     pragma: 'no-cache',
30 silly registry.get     'cache-control': 'no-cache',
30 silly registry.get     'content-type': 'text/html',
30 silly registry.get     'content-length': '4126  ' } ]
31 silly lockFile 3a6257f3-phonegap phonegap@
32 silly lockFile 3a6257f3-phonegap phonegap@
33 error SyntaxError: Unexpected token <
33 error <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
33 error <HTML><HEAD><TITLE>Error Message</TITLE>
33 error <META http-equiv=Content-Type content="text/html; charset=UTF-8">
33 error <STYLE id=L_default_1>A {
33 error 	FONT-WEIGHT: bold; FONT-SIZE: 10pt; COLOR: #005a80; FONT-FAMILY: tahoma
33 error }
33 error A:hover {
33 error 	FONT-WEIGHT: bold; FONT-SIZE: 10pt; COLOR: #0d3372; FONT-FAMILY: tahoma
33 error }
33 error TD {
33 error 	FONT-SIZE: 8pt; FONT-FAMILY: tahoma
33 error }
33 error TD.titleBorder {
33 error 	BORDER-RIGHT: #955319 1px solid; BORDER-TOP: #955319 1px solid; PADDING-LEFT: 8px; FONT-WEIGHT: bold; FONT-SIZE: 12pt; VERTICAL-ALIGN: middle; BORDER-LEFT: #955319 0px solid; COLOR: #955319; BORDER-BOTTOM: #955319 1px solid; FONT-FAMILY: tahoma; HEIGHT: 35px; BACKGROUND-COLOR: #d2b87a; TEXT-ALIGN: left
33 error }
33 error TD.titleBorderx {
33 error 	BORDER-RIGHT: #955319 0px solid; BORDER-TOP: #955319 1px solid; PADDING-LEFT: 8px; FONT-WEIGHT: bold; FONT-SIZE: 12pt; VERTICAL-ALIGN: middle; BORDER-LEFT: #955319 1px solid; COLOR: #978c79; BORDER-BOTTOM: #955319 1px solid; FONT-FAMILY: tahoma; HEIGHT: 35px; BACKGROUND-COLOR: #d2b87a; TEXT-ALIGN: left
33 error }
33 error .TitleDescription {
33 error 	FONT-WEIGHT: bold; FONT-SIZE: 12pt; COLOR: black; FONT-FAMILY: tahoma
33 error }
33 error SPAN.explain {
33 error 	FONT-WEIGHT: normal; FONT-SIZE: 10pt; COLOR: #934225
33 error }
33 error SPAN.TryThings {
33 error 	FONT-WEIGHT: normal; FONT-SIZE: 10pt; COLOR: #934225
33 error }
33 error .TryList {
33 error 	MARGIN-TOP: 5px; FONT-WEIGHT: normal; FONT-SIZE: 8pt; COLOR: black; FONT-FAMILY: tahoma
33 error }
33 error .X {
33 error 	BORDER-RIGHT: #955319 1px solid; BORDER-TOP: #955319 1px solid; FONT-WEIGHT: normal; FONT-SIZE: 12pt; BORDER-LEFT: #955319 1px solid; COLOR: #7b3807; BORDER-BOTTOM: #955319 1px solid; FONT-FAMILY: verdana; BACKGROUND-COLOR: #d1c2b4
33 error }
33 error .adminList {
33 error 	MARGIN-TOP: 2px
33 error }
33 error </STYLE>
33 error <META content="MSHTML 6.00.2800.1170" name=GENERATOR></HEAD>
33 error <BODY bgColor=#f3f3ed>
33 error <TABLE cellSpacing=0 cellPadding=0 width="100%">
33 error   <TBODY>
33 error   <TR>
33 error     <TD class=titleBorderx width=30>
33 error       <TABLE height=25 cellSpacing=2 cellPadding=0 width=25 bgColor=black>
33 error         <TBODY>
33 error         <TR>
33 error           <TD id=L_default_x class=x valign=middle align=center>X</TD>
33 error         </TR>
33 error         </TBODY>
33 error       </TABLE>
33 error     </TD>
33 error     <TD class=titleBorder id=L_default_2>Network Access Message:<SPAN class=TitleDescription> The page cannot be displayed</SPAN> </TD>
33 error   </TR>
33 error   </TBODY>
33 error </TABLE>
33 error
33 error <TABLE id=spacer>
33 error   <TBODY>
33 error   <TR>
33 error     <TD height=10></TD></TR></TBODY></TABLE>
33 error <TABLE width=400>
33 error   <TBODY>
33 error   <TR>
33 error     <TD noWrap width=25></TD>
33 error     <TD width=400><SPAN class=explain><ID id=L_default_3><B>Explanation:</B></ID></SPAN><ID id=L_default_4> There is a problem with the page you are trying to reach and it cannot be displayed. </ID><BR><BR>
33 error     <B><SPAN class=tryThings><ID id=L_default_5><B>Try the following:</B></ID></SPAN></B>
33 error       <UL class=TryList>
33 error         <LI id=L_default_6><B>Refresh page:</B> Search for the page again by clicking the Refresh button. The timeout may have occurred due to Internet congestion.
33 error <LI id=L_default_7><B>Check spelling:</B> Check that you typed the Web page address correctly. The address may have been mistyped.
33 error <LI id=L_default_8><B>Access from a link:</B> If there is a link to the page you are looking for, try accessing the page from that link.
33 error
33 error       </UL>
33 error <ID id=L_default_9>If you are still not able to view the requested page, try contacting your administrator or Helpdesk.</ID> <BR><BR>
33 error     </TD>
33 error   </TR>
33 error   </TBODY>
33 error </TABLE>
33 error
33 error <TABLE id=spacer><TBODY><TR><TD height=15></TD></TR></TBODY></TABLE>
33 error
33 error <TABLE width=400>
33 error   <TBODY>
33 error   <TR>
33 error     <TD noWrap width=25></TD>
33 error     <TD width=400 id=L_default_10><B>Technical Information (for support personnel)</B>
33 error       <UL class=adminList>
33 error         <LI id=L_default_11>Error Code: 407 Proxy Authentication Required. Forefront TMG requires authorization to fulfill the request. Access to the Web Proxy filter is denied. (12209)
33 error <LI id=L_default_12>IP Address: 10.41.24.27
33 error <LI id=L_default_13>Date: 11/18/2014 3:32:33 AM [GMT]
33 error <LI id=L_default_14>Server: CNZHSTISA.wzs.wistron
33 error <LI id=L_default_15>Source: proxy
33 error
33 error       </UL>
33 error     </TD>
33 error   </TR>
33 error   </TBODY>
33 error </TABLE>
33 error
33 error </BODY>
33 error </HTML>
33 error
33 error
33 error     at Object.parse (native)
33 error     at RegClient.<anonymous> (D:\ProgramFiles\NodeJS\node_modules\npm\node_modules\npm-registry-client\lib\request.js:274:23)
33 error     at Request._callback (D:\ProgramFiles\NodeJS\node_modules\npm\node_modules\npm-registry-client\lib\request.js:246:65)
33 error     at Request.self.callback (D:\ProgramFiles\NodeJS\node_modules\npm\node_modules\request\request.js:236:22)
33 error     at Request.emit (events.js:98:17)
33 error     at Request.<anonymous> (D:\ProgramFiles\NodeJS\node_modules\npm\node_modules\request\request.js:1142:14)
33 error     at Request.emit (events.js:117:20)
33 error     at IncomingMessage.<anonymous> (D:\ProgramFiles\NodeJS\node_modules\npm\node_modules\request\request.js:1096:12)
33 error     at IncomingMessage.emit (events.js:117:20)
33 error     at _stream_readable.js:943:16
34 error If you need help, you may report this *entire* log,
34 error including the npm and node versions, at:
34 error     <http://github.com/npm/npm/issues>
35 error System Windows_NT 6.1.7601
36 error command "D:\\ProgramFiles\\NodeJS\\\\node.exe" "D:\\ProgramFiles\\NodeJS\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "phonegap"
37 error cwd C:\Users\z10070043
38 error node -v v0.10.33
39 error npm -v 1.4.28
40 error type unexpected_token
41 verbose exit [ 1, true ]
```

**Comment by smikes** [comment]
Is this still a problem for you?

It looks like the problem here is a proxy: you need to tell `npm` about your proxy configuration.

> 27 verbose bad json         <LI id=L_default_11>Error Code: 407 Proxy Authentication Required. Forefront TMG requires authorization to fulfill the request. Access to the Web Proxy filter is denied. (12209)
27 verbose bad json <LI id=L_default_12>IP Address: 10.41.24.27
27 verbose bad json <LI id=L_default_13>Date: 11/18/2014 3:32:33 AM [GMT]
27 verbose bad json <LI id=L_default_14>Server: CNZHSTISA.wzs.wistron
27 verbose bad json <LI id=L_default_15>Source: proxy

See <https://docs.npmjs.com/misc/config#https-proxy> for proxy documentation.

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.4.28. Can you try updating your npm installation?

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as resolved / abandoned.
