### ISSUE TITLE
Do I have to sudo to install atom packages?

### ISSUE THREAD

**Issue by bhalliburton** [npm/npm#6747]
```
apm install minimap@3.3.12
Installing minimap@3.3.12 to /Users/brent/.atom/packages ✗

npm http GET https://registry.npmjs.org/delegato
npm http GET https://registry.npmjs.org/semver
npm http GET https://registry.npmjs.org/event-kit
npm http GET https://registry.npmjs.org/grim
npm http GET https://registry.npmjs.org/fs-plus
npm http GET https://registry.npmjs.org/temp/0.5.0
npm http GET https://registry.npmjs.org/underscore-plus
npm http GET https://registry.npmjs.org/emissary
npm http GET https://registry.npmjs.org/mixto
npm http 304 https://registry.npmjs.org/delegato
npm http 304 https://registry.npmjs.org/grim
npm http 304 https://registry.npmjs.org/event-kit
npm http 304 https://registry.npmjs.org/fs-plus
npm http 304 https://registry.npmjs.org/temp/0.5.0
npm http 304 https://registry.npmjs.org/mixto
npm http 304 https://registry.npmjs.org/underscore-plus
npm http 304 https://registry.npmjs.org/semver
npm http 304 https://registry.npmjs.org/emissary
npm http GET https://registry.npmjs.org/underscore
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/property-accessors
npm http 304 https://registry.npmjs.org/underscore
npm WARN `git config --get remote.origin.url` returned wrong result (https://github.com/Benvie/harmony-collections.git) Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.
npm http 304 https://registry.npmjs.org/mkdirp
npm http 304 https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/property-accessors
npm ERR! git clone https://github.com/Benvie/harmony-collections.git Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.
npm ERR! Error: Command failed: 
npm ERR! 
npm ERR! Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.
npm ERR! 
npm ERR! 
npm ERR! 
npm ERR!     at ChildProcess.exithandler (child_process.js:648:15)
npm ERR!     at ChildProcess.emit (events.js:98:17)
npm ERR!     at maybeClose (child_process.js:756:16)
npm ERR!     at Socket.<anonymous> (child_process.js:969:11)
npm ERR!     at Socket.emit (events.js:95:17)
npm ERR!     at Pipe.close (net.js:465:12)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 14.0.0
npm ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/.apmrc" "--userconfig" "/Users/brent/.atom/.apmrc" "install" "/Users/brent/.atom/.node-gyp/.atom/.apm/minimap/3.3.12/package.tgz" "--target=0.18.0" "--arch=x64"
npm ERR! cwd /private/var/folders/5t/gkd87tp53db6mbyg3x1h48w40000gn/T/apm-install-dir-1141019-32616-xp832s
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.4
npm ERR! code 69
npm http 304 https://registry.npmjs.org/rimraf
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /private/var/folders/5t/gkd87tp53db6mbyg3x1h48w40000gn/T/apm-install-dir-1141019-32616-xp832s/npm-debug.log
npm ERR! not ok code 0
```

**Comment by smikes** [comment]
Is this still a problem for you?

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by bhalliburton** [comment]
close it! Thanks.

On Wed, Jan 21, 2015 at 7:41 AM, Sam Mikes <notifications@github.com> wrote:

> Is this still a problem for you?
>
> We are trying to clean up older npm issues, so if we don't hear back from
> you within a week, we will close this issue. (Don't worry -- you can always
> come back again and open a new issue!)
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/npm/npm/issues/6747#issuecomment-70829856>.
>



-- 
Brent W. Halliburton
215.439.0163
@bhalliburton

**Comment by othiym23** [comment]
Closed as resolved.
