### ISSUE TITLE
Error on running 'npm install -g cordova'

### ISSUE THREAD

**Issue by rash56** [npm/npm#6748]
```
C:\>npm install -g cordova
npm ERR! Error: version not found: cordova : cordova/cordova
npm ERR!     at RegClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm
node_modules\npm-registry-client\lib\request.js:308:14)
npm ERR!     at Request._callback (C:\Program Files\nodejs\node_modules\npm\nod
_modules\npm-registry-client\lib\request.js:246:65)
npm ERR!     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm
node_modules\request\request.js:236:22)
npm ERR!     at Request.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\n
de_modules\request\request.js:1142:14)
npm ERR!     at Request.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modul
s\npm\node_modules\request\request.js:1096:12)
npm ERR!     at IncomingMessage.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:943:16
npm ERR!     at process._tickCallback (node.js:419:13)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\no
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova"
npm ERR! cwd C:\
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! Error: EPERM, open 'C:\npm-debug.log'
npm ERR!  { [Error: EPERM, open 'C:\npm-debug.log'] errno: 50, code: 'EPERM', p
th: 'C:\\npm-debug.log' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\no
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova"
npm ERR! cwd C:\
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! path C:\npm-debug.log
npm ERR! code EPERM
npm ERR! errno 50
npm ERR! stack Error: EPERM, open 'C:\npm-debug.log'
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\npm-debug.log
npm ERR! not ok code 0
```

Please help me to resolve it.

**Comment by smikes** [comment]
Is this still a problem for you?

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.4.28. Can you try updating your npm installation?

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as abandoned.
