### ISSUE TITLE
I found an error, about shasum check. when i want to install cordova with npm.

### ISSUE THREAD

**Issue by lightworx** [npm/npm#6769]
I found an error, about shasum check. when i want to install cordova with npm.
The install command like the following:
```
sudo npm install -g ionic cordova ios-sim

npm ERR! Error: shasum check failed for /tmp/npm-83574-a7QrAcof/registry.npmjs.org/npm/-/npm-1.3.4.tgz
npm ERR! Expected: 1dacc91458f2197c362d774d2cbf111680f86ec2
npm ERR! Actual:   61522a9bb35580c4d293526cf7d63ed6e5947360
npm ERR! From:     https://registry.npmjs.org/npm/-/npm-1.3.4.tgz
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/sha/index.js:38:8
npm ERR!     at ReadStream.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/sha/index.js:85:7)
npm ERR!     at ReadStream.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:943:16
npm ERR!     at process._tickCallback (node.js:419:13)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 14.0.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "-g" "ionic" "cordova" "ios-sim"
npm ERR! cwd /Users/stephen/Projects/mobile/moyan
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! not ok code 0
```

**Comment by smikes** [comment]
Is this still a problem for you?

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as resolved / abandoned.

**Comment by rakeshramteke** [comment]
Run cmd as administrator then run your command. Worked for me.
