### ISSUE TITLE
bundled optional dependencies?

### ISSUE THREAD

**Issue by rlidwka** [npm/npm#6801]
This works:

```
ubuntu@test:/tmp$ npm i http://kocharin.ru/foo-normal.tgz
npm http GET http://kocharin.ru/foo-normal.tgz
npm http 200 http://kocharin.ru/foo-normal.tgz
npm http GET https://registry.npmjs.org/crypt3
npm http 304 https://registry.npmjs.org/crypt3
npm http GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/nan

> crypt3@0.1.6 install /tmp/node_modules/foo/node_modules/crypt3
> node-gyp rebuild

make: Entering directory `/tmp/node_modules/foo/node_modules/crypt3/build'
  CXX(target) Release/obj.target/crypt3/crypt3.o
make: g++: Command not found
make: *** [Release/obj.target/crypt3/crypt3.o] Error 127
make: Leaving directory `/tmp/node_modules/foo/node_modules/crypt3/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.16.0-24-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /tmp/node_modules/foo/node_modules/crypt3
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm WARN optional dep failed, continuing crypt3@0.1.6
foo@0.0.0 node_modules/foo

ubuntu@test:/tmp$ echo $?
0

ubuntu@test:/tmp$ ls node_modules/
foo

```

This doesn't:

```
ubuntu@test:/tmp$ npm i http://kocharin.ru/foo-bundled.tgz
npm WARN package.json foo@0.0.0 No repository field.
npm http GET http://kocharin.ru/foo-bundled.tgz
npm http 200 http://kocharin.ru/foo-bundled.tgz

> crypt3@0.1.6 install /tmp/node_modules/foo/node_modules/crypt3
> node-gyp rebuild

make: Entering directory `/tmp/node_modules/foo/node_modules/crypt3/build'
  CXX(target) Release/obj.target/crypt3/crypt3.o
make: g++: Command not found
make: *** [Release/obj.target/crypt3/crypt3.o] Error 127
make: Leaving directory `/tmp/node_modules/foo/node_modules/crypt3/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.16.0-24-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /tmp/node_modules/foo/node_modules/crypt3
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! weird error 1
npm ERR! not ok code 0

ubuntu@test:/tmp$ echo $?
1

ubuntu@test:/tmp$ ls node_modules/

```

Both are valid npm packages that were packed with `npm pack`, and only difference - the binary dependency is specified as "bundled" in the second one, like this:

``` json
{
  "name": "foo",
  "version": "0.0.0",
  "optionalDependencies": {"crypt3": "*"},
  "bundleDependencies": ["crypt3"]
}
```

So, how can I pack a binary dependency into a tarball while still keeping it optional (i.e. people can use package even if they can't build it)?

**Comment by othiym23** [comment]
This has been moved to the [npm roadmap](https://github.com/npm/npm/wiki/Roadmap), which we're using instead of the confusing `next-*` labels now.
