### ISSUE TITLE
Getting EHOSTUNREACH error from npm install

### ISSUE THREAD

**Issue by arundaya** [npm/npm#6820]
I am getting an error EHOSTUNREACH while trying to install the ws package from npm. The debug log is:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'ws' ]
2 info using npm@1.4.28
3 info using node@v0.10.33
4 verbose cache add [ 'ws', null ]
5 verbose cache add name=undefined spec="ws" args=["ws",null]
6 verbose parsed url { protocol: null,
6 verbose parsed url   slashes: null,
6 verbose parsed url   auth: null,
6 verbose parsed url   host: null,
6 verbose parsed url   port: null,
6 verbose parsed url   hostname: null,
6 verbose parsed url   hash: null,
6 verbose parsed url   search: null,
6 verbose parsed url   query: null,
6 verbose parsed url   pathname: 'ws',
6 verbose parsed url   path: 'ws',
6 verbose parsed url   href: 'ws' }
7 silly lockFile 1457b75d-ws ws
8 verbose lock ws /root/.npm/1457b75d-ws.lock
9 silly lockFile 1457b75d-ws ws
10 silly lockFile 1457b75d-ws ws
11 verbose addNamed [ 'ws', '' ]
12 verbose addNamed [ null, '*' ]
13 silly lockFile e88fe629-ws ws@
14 verbose lock ws@ /root/.npm/e88fe629-ws.lock
15 silly addNameRange { name: 'ws', range: '*', hasData: false }
16 verbose request where is /ws
17 verbose request registry https://registry.npmjs.org/
18 verbose request id 79439ea54ea2f596
19 verbose url raw /ws
20 verbose url resolving [ 'https://registry.npmjs.org/', './ws' ]
21 verbose url resolved https://registry.npmjs.org/ws
22 verbose request where is https://registry.npmjs.org/ws
23 info trying registry request attempt 1 at 05:36:25
24 http GET https://registry.npmjs.org/ws
25 info retry will retry, error on last attempt: Error: connect EHOSTUNREACH
26 info trying registry request attempt 2 at 05:36:36
27 http GET https://registry.npmjs.org/ws
28 info retry will retry, error on last attempt: Error: connect EHOSTUNREACH
29 info trying registry request attempt 3 at 05:37:36
30 http GET https://registry.npmjs.org/ws
31 silly lockFile e88fe629-ws ws@
32 silly lockFile e88fe629-ws ws@
33 error Error: connect EHOSTUNREACH
33 error     at errnoException (net.js:904:11)
33 error     at Object.afterConnect [as oncomplete] (net.js:895:19)
34 error If you need help, you may report this *entire* log,
34 error including the npm and node versions, at:
34 error     <http://github.com/npm/npm/issues>
35 error System Linux 2.6.32-400.34.1.el5uek
36 error command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "ws"
37 error cwd /otd/otduser/BalancerTest/ws
38 error node -v v0.10.33
39 error npm -v 1.4.28
40 error syscall connect
41 error code EHOSTUNREACH
42 error errno EHOSTUNREACH
43 verbose exit [ 1, true ]
```
I have set the http_proxy and git config has been set to url.http://.insteadof=git://
http.proxy=http://www-proxy....:80. But still facing above issue. Am i missing any further config?

**Comment by smikes** [comment]
Is this still a problem for you?

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as resolved.
