### ISSUE TITLE
karma not getting installed.

### ISSUE THREAD

**Issue by sahil3190** [npm/npm#6852]
i am trying to installl karma on my machine and i am getting below error-
node.js version is - v0.10.33
npm version is - 1.4.28

i am using the below command in command prompt-
npm install -g karma

Error-
```
c:\>npm install -g karma
npm ERR! Error: getaddrinfo EAGAIN
npm ERR!     at errnoException (dns.js:37:11)
npm ERR!     at Object.onanswer [as oncomplete] (dns.js:124:16)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7600
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "karma"
npm ERR! cwd c:\
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! syscall getaddrinfo
npm ERR! code EAGAIN
npm ERR! errno EAGAIN
npm ERR! Error: EPERM, open 'c:\npm-debug.log'
npm ERR!  { [Error: EPERM, open 'c:\npm-debug.log'] errno: 50, code: 'EPERM', pa
th: 'c:\\npm-debug.log' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Windows_NT 6.1.7600
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "karma"
npm ERR! cwd c:\
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! path c:\npm-debug.log
npm ERR! code EPERM
npm ERR! errno 50
npm ERR! stack Error: EPERM, open 'c:\npm-debug.log'
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     c:\npm-debug.log
npm ERR! not ok code 0
```

**Comment by othiym23** [comment]
Closing as resolved / abandoned.
