### ISSUE TITLE
npm ERR! Invalid name: "Hello World"

### ISSUE THREAD

**Issue by kuyoonjo** [npm/npm#6860]
```
$ npm install exec-sync
npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "exec-sync"
npm ERR! node v0.10.33
npm ERR! npm  v2.1.11

npm ERR! Invalid name: "Hello World"
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/yuchen/IdeaProjects/Comparator/npm-debug.log

----------------------------------------------------------------------------------------------
$ cat npm-debug.log 
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'install' ]
2 info using npm@2.1.11
3 info using node@v0.10.33
4 error install Couldn't read dependencies
5 verbose stack Error: Invalid name: "Hello World"
5 verbose stack     at ensureValidName (/usr/local/lib/node_modules/npm/node_modules/normalize-package-data/lib/fixer.js:322:15)
5 verbose stack     at Object.module.exports.fixNameField (/usr/local/lib/node_modules/npm/node_modules/normalize-package-data/lib/fixer.js:211:5)
5 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/normalize-package-data/lib/normalize.js:30:38
5 verbose stack     at Array.forEach (native)
5 verbose stack     at normalize (/usr/local/lib/node_modules/npm/node_modules/normalize-package-data/lib/normalize.js:29:15)
5 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:342:33)
5 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:126:33)
5 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:316:48
5 verbose stack     at evalmachine.<anonymous>:207:20
5 verbose stack     at OpenReq.Req.done (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:141:5)
6 verbose cwd /Users/yuchen/IdeaProjects/Comparator
7 error Darwin 14.0.0
8 error argv "node" "/usr/local/bin/npm" "install"
9 error node v0.10.33
10 error npm  v2.1.11
11 error Invalid name: "Hello World"
12 error If you need help, you may report this error at:
12 error     <http://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]
```

**Comment by smikes** [comment]
Is this still a problem for you?

This looks like you lack the necessary permissions to write to your `npm` cache.  You can fix this like this:

```
chown -R yuchen ~/.npm
```

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as resolved.
