### ISSUE TITLE
npm install -g strange error message: *Attempt to unlock 'what you install with -g', which hasn' t been locked

### ISSUE THREAD

**Issue by HansS** [npm/npm#6927]
is there anywhere a lock which npm has set! i might have done some changes on npm while having problems with yeoman, which do cause this 'lock' message!
can you give me a hint?

npm-debug.log:
```
0 info it worked if it ends with ok
1 verbose cli [ 'node',
1 verbose cli   'C:\\Users\\Hans\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'strata' ]
2 info using npm@2.1.1
3 info using node@v0.10.29
4 verbose cache add [ 'strata', null ]
5 verbose cache add spec="strata" args=["strata",null]
6 verbose parsed spec { raw: 'strata',
6 verbose parsed spec   scope: null,
6 verbose parsed spec   name: 'strata',
6 verbose parsed spec   rawSpec: '',
6 verbose parsed spec   spec: '*',
6 verbose parsed spec   type: 'range' }
7 verbose parsed spec { raw: 'strata',
7 verbose parsed spec   scope: null,
7 verbose parsed spec   name: 'strata',
7 verbose parsed spec   rawSpec: '',
7 verbose parsed spec   spec: '*',
7 verbose parsed spec   type: 'range' }
8 verbose addNamed [ 'strata', '*' ]
9 verbose addNamed [ null, '*' ]
10 silly addNameRange { name: 'strata', range: '*', hasData: false }
11 verbose mapToRegistry name strata
12 verbose mapToRegistry uri http://registry.npmjs.org/strata
13 verbose request on initialization, where is /strata
14 verbose request after pass 1, where is /strata
15 verbose request url raw /strata
16 verbose request resolving registry [ 'http://registry.npmjs.org/', './strata' ]
17 verbose request after pass 2, where is http://registry.npmjs.org/strata
18 verbose request no auth needed
19 info attempt registry request try #1 at 10:41:17
20 verbose request id a71889b8416f0eac
21 http request GET http://registry.npmjs.org/strata
22 http 200 http://registry.npmjs.org/strata
23 silly registry.get cb [ 200,
23 silly registry.get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
23 silly registry.get     etag: '"6I3NY9F47E31X0B6UI7GMLZVH"',
23 silly registry.get     'content-type': 'application/json',
23 silly registry.get     'cache-control': 'max-age=60',
23 silly registry.get     'content-length': '65562',
23 silly registry.get     'accept-ranges': 'bytes',
23 silly registry.get     date: 'Mon, 15 Dec 2014 09:41:17 GMT',
23 silly registry.get     via: '1.1 varnish',
23 silly registry.get     age: '0',
23 silly registry.get     connection: 'keep-alive',
23 silly registry.get     'x-served-by': 'cache-fra1227-FRA',
23 silly registry.get     'x-cache': 'MISS',
23 silly registry.get     'x-cache-hits': '0',
23 silly registry.get     'x-timer': 'S1418636477.081332,VS0,VE629',
23 silly registry.get     vary: 'Accept' } ]
24 silly addNameRange number 2 { name: 'strata', range: '*', hasData: true }
25 silly addNameRange versions [ 'strata',
25 silly addNameRange   [ '0.0.0',
25 silly addNameRange     '0.4.0',
25 silly addNameRange     '0.4.1',
25 silly addNameRange     '0.4.2',
25 silly addNameRange     '0.4.3',
25 silly addNameRange     '0.4.4',
25 silly addNameRange     '0.4.5',
25 silly addNameRange     '0.5.0',
25 silly addNameRange     '0.5.1',
25 silly addNameRange     '0.5.2',
25 silly addNameRange     '0.5.3',
25 silly addNameRange     '0.5.4',
25 silly addNameRange     '0.5.5',
25 silly addNameRange     '0.5.6',
25 silly addNameRange     '0.5.7',
25 silly addNameRange     '0.5.8',
25 silly addNameRange     '0.5.9',
25 silly addNameRange     '0.5.10',
25 silly addNameRange     '0.5.11',
25 silly addNameRange     '0.5.12',
25 silly addNameRange     '0.5.13',
25 silly addNameRange     '0.5.14',
25 silly addNameRange     '0.6.0',
25 silly addNameRange     '0.6.1',
25 silly addNameRange     '0.7.0',
25 silly addNameRange     '0.8.0',
25 silly addNameRange     '0.8.1',
25 silly addNameRange     '0.8.2',
25 silly addNameRange     '0.9.0',
25 silly addNameRange     '0.9.1',
25 silly addNameRange     '0.10.0',
25 silly addNameRange     '0.10.1',
25 silly addNameRange     '0.11.0',
25 silly addNameRange     '0.12.0',
25 silly addNameRange     '0.12.1',
25 silly addNameRange     '0.12.2',
25 silly addNameRange     '0.12.3',
25 silly addNameRange     '0.12.4',
25 silly addNameRange     '0.12.5',
25 silly addNameRange     '0.13.0',
25 silly addNameRange     '0.14.0',
25 silly addNameRange     '0.15.0',
25 silly addNameRange     '0.15.1',
25 silly addNameRange     '0.16.0',
25 silly addNameRange     '0.16.1',
25 silly addNameRange     '0.17.0',
25 silly addNameRange     '0.18.0',
25 silly addNameRange     '0.18.1',
25 silly addNameRange     '0.19.0',
25 silly addNameRange     '0.19.1',
25 silly addNameRange     '0.19.2',
25 silly addNameRange     '0.19.3',
25 silly addNameRange     '0.20.0',
25 silly addNameRange     '0.20.1' ] ]
26 verbose addNamed [ 'strata', '0.20.1' ]
27 verbose addNamed [ '0.20.1', '0.20.1' ]
28 verbose addRemoteTarball [ 'http://registry.npmjs.org/strata/-/strata-0.20.1.tgz',
28 verbose addRemoteTarball   'abc30e57f04e648086fe4c264a5fa55b2386577e' ]
29 info retry fetch attempt 1 at 10:41:18
30 info attempt registry request try #1 at 10:41:18
31 http fetch GET http://registry.npmjs.org/strata/-/strata-0.20.1.tgz
32 http fetch 200 http://registry.npmjs.org/strata/-/strata-0.20.1.tgz
33 silly fetchAndShaCheck shasum abc30e57f04e648086fe4c264a5fa55b2386577e
34 verbose tar unpack C:\Users\Hans\AppData\Local\Temp\npm-7840-2gOMXTUa\registry.npmjs.org\strata\-\strata-0.20.1.tgz
35 verbose gentlyRm vacuuming C:\Users\Hans\AppData\Local\Temp\npm-7840-2gOMXTUa\registry.npmjs.org\strata\-\strata-0.20.1.tgz-unpack
36 silly gunzTarPerm modes [ '777', '666' ]
37 silly gunzTarPerm extractEntry package.json
38 silly gunzTarPerm modified mode [ 'package.json', 420, 438 ]
39 silly gunzTarPerm extractEntry .npmignore
40 silly gunzTarPerm modified mode [ '.npmignore', 420, 438 ]
41 silly gunzTarPerm extractEntry README.md
42 silly gunzTarPerm modified mode [ 'README.md', 420, 438 ]
43 silly gunzTarPerm extractEntry .travis.yml
44 silly gunzTarPerm modified mode [ '.travis.yml', 420, 438 ]
45 silly gunzTarPerm extractEntry CHANGES
46 silly gunzTarPerm modified mode [ 'CHANGES', 420, 438 ]
47 silly resolved [ { name: 'strata',
47 silly resolved     version: '0.20.1',
47 silly resolved     author: { name: 'Michael Jackson', email: 'mjijackson@gmail.com' },
47 silly resolved     description: 'A modular, streaming HTTP server',
47 silly resolved     keywords:
47 silly resolved      [ 'web',
47 silly resolved        'http',
47 silly resolved        'server',
47 silly resolved        'framework',
47 silly resolved        'middleware',
47 silly resolved        'rack',
47 silly resolved        'jsgi',
47 silly resolved        'wsgi' ],
47 silly resolved     homepage: 'http://stratajs.org',
47 silly resolved     engines: { node: '>= 0.8.0' },
47 silly resolved     repository: { type: 'git', url: 'git://github.com/mjijackson/strata.git' },
47 silly resolved     dependencies:
47 silly resolved      { bufferedstream: '1.6.x',
47 silly resolved        mime: '1.2.3',
47 silly resolved        strftime: '0.4.6',
47 silly resolved        markdown: '~0.3.1' },
47 silly resolved     devDependencies: { mocha: '1.5.0', mustache: '0.3.1-dev' },
47 silly resolved     main: './lib',
47 silly resolved     bin: { strata: './bin/strata' },
47 silly resolved     scripts: { test: 'mocha test/*-test.js' },
47 silly resolved     _id: 'strata@0.20.1',
47 silly resolved     dist:
47 silly resolved      { shasum: 'abc30e57f04e648086fe4c264a5fa55b2386577e',
47 silly resolved        tarball: 'http://registry.npmjs.org/strata/-/strata-0.20.1.tgz' },
47 silly resolved     _from: 'strata@*',
47 silly resolved     _npmVersion: '1.2.15',
47 silly resolved     _npmUser: { name: 'mjackson', email: 'mjijackson@gmail.com' },
47 silly resolved     maintainers: [ [Object] ],
47 silly resolved     directories: {},
47 silly resolved     _shasum: 'abc30e57f04e648086fe4c264a5fa55b2386577e',
47 silly resolved     _resolved: 'http://registry.npmjs.org/strata/-/strata-0.20.1.tgz' } ]
48 info install strata@0.20.1 into C:\Program Files\nodejs
49 info installOne strata@0.20.1
50 silly lockFile .baf691ef-strata strata
51 verbose lock strata C:\Program Files\nodejs\node_modules\.baf691ef-strata.lock
52 silly lockFile .baf691ef-strata strata
53 verbose stack Error: Attempt to unlock strata, which hasn't been locked
53 verbose stack     at unlock (C:\Users\Hans\AppData\Roaming\npm\node_modules\npm\lib\utils\locker.js:45:11)
53 verbose stack     at cb (C:\Users\Hans\AppData\Roaming\npm\node_modules\npm\lib\install.js:910:5)
53 verbose stack     at C:\Users\Hans\AppData\Roaming\npm\node_modules\npm\lib\install.js:914:20
53 verbose stack     at C:\Users\Hans\AppData\Roaming\npm\node_modules\npm\lib\utils\locker.js:29:7
53 verbose stack     at cb (C:\Users\Hans\AppData\Roaming\npm\node_modules\npm\node_modules\lockfile\lockfile.js:149:38)
53 verbose stack     at C:\Users\Hans\AppData\Roaming\npm\node_modules\npm\node_modules\lockfile\lockfile.js:177:38
53 verbose stack     at Object.oncomplete (fs.js:107:15)
54 verbose cwd C:\Users\Hans\web\mean\airpair
55 error Windows_NT 6.2.9200
56 error argv "node" "C:\\Users\\Hans\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "strata"
57 error node v0.10.29
58 error npm  v2.1.1
59 error Attempt to unlock strata, which hasn't been locked
60 error If you need help, you may report this error at:
60 error     <http://github.com/npm/npm/issues>
61 verbose exit [ 1, true ]
```

kind regards
hans

**Comment by othiym23** [comment]
Closing as resolved / abandoned.
