### ISSUE TITLE
registry error parsing json

### ISSUE THREAD

**Issue by susantabehera32** [npm/npm#7003]
```
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! SyntaxError: Unexpected token <
npm ERR! <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
npm ERR! <html xmlns="http://www.w3.org/1999/xhtml">
npm ERR! <head>
npm ERR! <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
npm ERR! <title>404 - File or directory not found.</title>
npm ERR! <style type="text/css">
npm ERR! <!--
npm ERR! body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
npm ERR! fieldset{padding:0 15px 10px 15px;}
npm ERR! h1{font-size:2.4em;margin:0;color:#FFF;}
npm ERR! h2{font-size:1.7em;margin:0;color:#CC0000;}
npm ERR! h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;}
npm ERR! #header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
npm ERR! background-color:#555555;}
npm ERR! #content{margin:0 0 0 2%;position:relative;}
npm ERR! .content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
npm ERR! -->
npm ERR! </style>
npm ERR! </head>
npm ERR! <body>
npm ERR! <div id="header"><h1>Server Error</h1></div>
npm ERR! <div id="content">
npm ERR!  <div class="content-container"><fieldset>
npm ERR!   <h2>404 - File or directory not found.</h2>
npm ERR!   <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
npm ERR!  </fieldset></div>
npm ERR! </div>
npm ERR! </body>
npm ERR! </html>
npm ERR!
npm ERR!     at Object.parse (native)
npm ERR!     at RegClient.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:274:23)
npm ERR!     at Request._callback (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:246:65)
npm ERR!     at Request.self.callback (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\request.js:236:22)
npm ERR!     at Request.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\request.js:1142:14)
npm ERR!     at Request.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\request.js:1096:12)
npm ERR!     at IncomingMessage.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:944:16
```

**Comment by smikes** [comment]
Is this still a problem for you?

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as resolved / abandoned.
