### ISSUE TITLE
Unable to publish package

### ISSUE THREAD

**Issue by odino** [npm/npm#7035]
Hey guys,

long story short :)

```
npm ERR! publish Failed PUT 500
npm ERR! Linux 3.8.0-26-generic
npm ERR! argv "node" "/home/odino/local/bin/npm" "publish"
npm ERR! node v0.10.33
npm ERR! npm  v2.1.5
npm ERR! code E500

npm ERR! pound_internal_server_error : mockserver
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/odino/projects/namshi/mockserver/npm-debug.log
```

and the debug log:

```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/home/odino/local/bin/npm', 'publish' ]
2 info using npm@2.1.5
3 info using node@v0.10.33
4 verbose publish [ '.' ]
5 silly cache add args [ '.', null ]
6 verbose cache add spec .
7 silly cache add parsed spec { raw: '.',
7 silly cache add   scope: null,
7 silly cache add   name: null,
7 silly cache add   rawSpec: '.',
7 silly cache add   spec: '/home/odino/projects/namshi/mockserver',
7 silly cache add   type: 'directory' }
8 verbose tar pack [ '/home/odino/.npm/mockserver/1.1.0/package.tgz',
8 verbose tar pack   '/home/odino/projects/namshi/mockserver' ]
9 verbose tarball /home/odino/.npm/mockserver/1.1.0/package.tgz
10 verbose folder /home/odino/projects/namshi/mockserver
11 info prepublish mockserver@1.1.0
12 verbose addLocalTarball adding from inside cache /home/odino/.npm/mockserver/1.1.0/package.tgz
13 silly cache afterAdd mockserver@1.1.0
14 verbose afterAdd /home/odino/.npm/mockserver/1.1.0/package/package.json not in flight; writing
15 verbose afterAdd /home/odino/.npm/mockserver/1.1.0/package/package.json written
16 silly publish { name: 'mockserver',
16 silly publish   version: '1.1.0',
16 silly publish   description: 'Easily mock your webservices while testing frontends.',
16 silly publish   main: 'mockserver.js',
16 silly publish   scripts: { test: 'mocha' },
16 silly publish   bin: { mockserver: 'bin/mockserver.js' },
16 silly publish   repository: { type: 'git', url: 'https://github.com/namshi/mockserver' },
16 silly publish   keywords: [ 'test', 'mock', 'api', 'webservice', 'rest', 'namshi' ],
16 silly publish   author: { name: 'Mohammad Hallal', email: 'mohd.hallal@gmail.com' },
16 silly publish   license: 'MIT',
16 silly publish   bugs: { url: 'https://github.com/namshi/mockserver/issues' },
16 silly publish   homepage: 'https://github.com/namshi/mockserver',
16 silly publish   dependencies:
16 silly publish    { colors: '^1.0.3',
16 silly publish      'js-combinatorics': '^0.4.0',
16 silly publish      yargs: '^1.3.3' },
16 silly publish   devDependencies: { mocha: '^2.0.1' },
16 silly publish   readme: '# mockserver\n\n[![Build Status](https://travis-ci.org/namshi/mockserver.svg?branch=master)](https://travis-ci.org/namshi/mockserver)\n\n**mockserver** is a library that will help you mocking your APIs\nin **a matter of seconds**: you simply organize your mocked\nHTTP responses in a bunch of mock files and it will serve them\nlike they were coming from a real API; in this way you can\nwrite your frontends without caring too much whether your\nbackend is really ready or not.\n\n## Installation\n\nMockserver can be installed globally if you need\nto run it as a command:\n\n```\n$ npm install -g mockserver\n\n$ mockserver.js -p 9001 -m test/mocks\nMockserver serving mocks under "test/mocks" at http://localhost:8080\n```\n\nor as a regular NPM module if you need to use it as\na library within your code:\n\n``` bash\nnpm install mockserver\n```\n\nthen in your test file:\n\n``` javascript\nvar http    =  require(\'http\');\nvar mockserver  =  require(\'mockserver\');\n\nhttp.createServer(mockserver(\'path/to/your/mocks\')).listen(9001);\n```\n\nThis will run a simple HTTP webserver, handled by mockserver, on port\n9001.\n\nAt this point you can simply define your first mock: create a file in\n`path/to/your/mocks/example-response` called `GET.mock`:\n\n```\nHTTP/1.1 200 OK\nContent-Type: application/json; charset=utf-8\n\n{\n   "Random": "content"\n}\n```\n\nIf you open your browser at `http://localhost:9001/example-response`\nyou will see something like this:\n\n![example output](https://raw.githubusercontent.com/namshi/mockserver/readme/bin/images/example-response.png)\n\nAnd it\'s over: now you can start writing your frontends without\nhaving to wait for your APIs to be ready, or without having to spend\ntoo much time mocking them, as mockserver lets you do it in seconds.\n\n## Mock files\n\nAs you probably understood, mock files\' naming conventions are based\non the response that they are going to serve:\n\n```\n$REQUEST-PATH/$HTTP-METHOD.mock\n```\n\nFor example, let\'s say that you wanna mock the response of a POST request\nto `/users`, you would simply need to create a file named `POST.mock` under `users/`.\n\nThe content of the mock files needs to be a valid HTTP response, for example:\n\n```\nHTTP/1.1 200 OK\nContent-Type: text/xml; charset=utf-8\n\n{\n   "Accept-Language": "en-US,en;q=0.8",\n   "Host": "headers.jsontest.com",\n   "Accept-Charset": "ISO-8859-1,utf-8;q=0.7,*;q=0.3",\n   "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"\n}\n```\n\nCheck [our own mocks](https://github.com/namshi/mockserver/tree/master/test/mocks) as a reference.\n\n## Custom Headers\n\nYou can specify request headers to include, which allows you to change the response based on what headers are\nprovided.  To do this, you need to let mockserver know which headers matter, by setting the\n`headers` array on the mockserver object, like so:\n\n```js\nvar mockserver = require(\'mockserver\');\nmockserver.headers = [\'Authorization\', \'X-My-Header\'];\n```\n\nAny headers that are set and occur within the array will now be appended to the filename, immediately after the\nHTTP method, like so:\n\n```\nGET /hello\nAuthorization: 12345\n\nhello/GET_Authorization=12345.mock\n```\n\n```\nGET /hello\nX-My-Header: cow\nAuthorization: 12345\n\nhello/GET_Authorization=12345_X-My-Header=cow.mock\n```\n\n**Note:** The order of the headers within the `headers` array determines the order of the values within the filename.\n\nThe server will always attempt to match the file with the most tracked headers, then it will try permutations of\nheaders until it finds one that matches.  This means that, in the previous example, the server will look for files\nin this order:\n\n```\nhello/GET_Authorization=12345_X-My-Header=cow.mock\nhello/GET_X-My-Header_Authorization=12345=cow.mock\nhello/GET_Authorization=12345.mock\nhello/GET_X-My-Header=cow.mock\nhello/GET.mock\n```\n\nThe first one matched is the one returned, favoring more matches and headers earlier in the array.\n\nThe `headers` array can be set or modified at any time.\n\n## Query String Parameters\n\nIn order to support query string parameters in the mocked files, replace all occurrences of `?` with `--`, then\nappend the entire string to the end of the file.\n\n```\nGET /hello?a=b\n\nhello/GET--a=b.mock\n```\n\n```\nGET /test?a=b&c=d?\n\ntest/GET--a=b&c=d--.mock\n```\n\n(This has been introduced to overcome issues in file naming on windows)\n\nTo combine custom headers and query parameters, simply add the headers *then* add the parameters:\n\n```\nGET /hello?a=b\nAuthorization: 12345\n\nhello/GET_Authorization=12345--a=b.mock\n```\n\n## Tests\n\nTests run on travis, but if you wanna run them locally you simply\nhave to run `mocha` or its verbose cousin `./node_modules/mocha/bin/mocha`\n(if you don\'t have mocha installed globally).',
16 silly publish   readmeFilename: 'README.md',
16 silly publish   gitHead: '6b2cae7ce5d871a5e895f326dc0517c1e9244902',
16 silly publish   _id: 'mockserver@1.1.0',
16 silly publish   _shasum: 'e99c470a0f1b442a926306f0141820ae1b86d7fe',
16 silly publish   _from: '.' }
17 verbose mapToRegistry name mockserver
18 verbose mapToRegistry uri https://registry.npmjs.org/mockserver
19 verbose publish registryBase https://registry.npmjs.org/
20 verbose request on initialization, where is /mockserver
21 verbose request after pass 1, where is /mockserver
22 verbose request url raw /mockserver
23 verbose request resolving registry [ 'https://registry.npmjs.org/', './mockserver' ]
24 verbose request after pass 2, where is https://registry.npmjs.org/mockserver
25 verbose request sending authorization for write operation
26 info attempt registry request try #1 at 18:57:25
27 verbose request id 253a889bc51d1157
28 http request PUT https://registry.npmjs.org/mockserver
29 http 500 https://registry.npmjs.org/mockserver
30 info retry will retry, error on last attempt: Error: pound_internal_server_error : mockserver
31 info attempt registry request try #2 at 18:57:38
32 http request PUT https://registry.npmjs.org/mockserver
33 http 500 https://registry.npmjs.org/mockserver
34 info retry will retry, error on last attempt: Error: pound_internal_server_error : mockserver
35 info attempt registry request try #3 at 18:58:47
36 http request PUT https://registry.npmjs.org/mockserver
37 http 500 https://registry.npmjs.org/mockserver
38 verbose headers { date: 'Wed, 31 Dec 2014 14:58:50 GMT',
38 verbose headers   server: 'Apache',
38 verbose headers   'content-type': 'text/html',
38 verbose headers   expires: 'now',
38 verbose headers   pragma: 'no-cache',
38 verbose headers   'cache-control': 'max-age=0',
38 verbose headers   'content-length': '111',
38 verbose headers   'accept-ranges': 'bytes',
38 verbose headers   via: '1.1 varnish',
38 verbose headers   'x-served-by': 'cache-sn86-SIN',
38 verbose headers   'x-cache': 'MISS',
38 verbose headers   'x-cache-hits': '0',
38 verbose headers   'x-timer': 'S1420037929.609114,VS0,VE776',
38 verbose headers   connection: 'close' }
39 error publish Failed PUT 500
40 verbose stack Error: pound_internal_server_error : mockserver
40 verbose stack     at RegClient.<anonymous> (/home/odino/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:260:14)
40 verbose stack     at Request._callback (/home/odino/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:197:65)
40 verbose stack     at Request.self.callback (/home/odino/local/lib/node_modules/npm/node_modules/request/request.js:199:22)
40 verbose stack     at Request.emit (events.js:98:17)
40 verbose stack     at Request.<anonymous> (/home/odino/local/lib/node_modules/npm/node_modules/request/request.js:1160:14)
40 verbose stack     at Request.emit (events.js:117:20)
40 verbose stack     at IncomingMessage.<anonymous> (/home/odino/local/lib/node_modules/npm/node_modules/request/request.js:1111:12)
40 verbose stack     at IncomingMessage.emit (events.js:117:20)
40 verbose stack     at _stream_readable.js:943:16
40 verbose stack     at process._tickCallback (node.js:419:13)
41 verbose statusCode 500
42 verbose pkgid mockserver
43 verbose cwd /home/odino/projects/namshi/mockserver
44 error Linux 3.8.0-26-generic
45 error argv "node" "/home/odino/local/bin/npm" "publish"
46 error node v0.10.33
47 error npm  v2.1.5
48 error code E500
49 error pound_internal_server_error : mockserver
50 error If you need help, you may report this error at:
50 error     <http://github.com/npm/npm/issues>
51 verbose exit [ 1, true ]
```

any idea?

**Comment by odino** [comment]
"Fixed" by upgrading to the latest `2.1.6`. Is this somehow expected? :) I guess something broke BC or sth like that

closing for now but...scary :)
