### ISSUE TITLE
npm clobbers its own log files

### ISSUE THREAD

**Issue by timoxley** [npm/npm#7041]
1. npm preinstall script calls `make`
2. `make` calls`npm rebuild`
3. `npm rebuild fails`, produces useful error log
4. useful error log is clobbered by parent npm script creating a log file telling me my `make` failed

### repo case
```json
{
  "name": "npm-issue-clobber-log",
  "version": "1.0.0",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "preinstall": "npm test"
  }
}
```

Produces an error log that does not contain the words "no test specified":

```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'install' ]
2 info using npm@2.1.17
3 info using node@v0.10.35
4 warn package.json npm-issue-clobber-log@1.0.0 No description
5 warn package.json npm-issue-clobber-log@1.0.0 No repository field.
6 warn package.json npm-issue-clobber-log@1.0.0 No README data
7 verbose install where, deps [ '/Users/timoxley/Projects/tests/npm-issue-clobber-log', [] ]
8 verbose install where, peers [ '/Users/timoxley/Projects/tests/npm-issue-clobber-log', [] ]
9 info preinstall npm-issue-clobber-log@1.0.0
10 verbose unsafe-perm in lifecycle true
11 info npm-issue-clobber-log@1.0.0 Failed to exec preinstall script
12 verbose stack Error: npm-issue-clobber-log@1.0.0 preinstall: `npm test`
12 verbose stack Exit status 1
12 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:212:16)
12 verbose stack     at EventEmitter.emit (events.js:98:17)
12 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:14:12)
12 verbose stack     at ChildProcess.emit (events.js:98:17)
12 verbose stack     at maybeClose (child_process.js:766:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
13 verbose pkgid npm-issue-clobber-log@1.0.0
14 verbose cwd /Users/timoxley/Projects/tests/npm-issue-clobber-log
15 error Darwin 14.1.0
16 error argv "node" "/usr/local/bin/npm" "install"
17 error node v0.10.35
18 error npm  v2.1.17
19 error code ELIFECYCLE
20 error npm-issue-clobber-log@1.0.0 preinstall: `npm test`
20 error Exit status 1
21 error Failed at the npm-issue-clobber-log@1.0.0 preinstall script 'npm test'.
21 error This is most likely a problem with the npm-issue-clobber-log package,
21 error not with npm itself.
21 error Tell the author that this fails on your system:
21 error     npm test
21 error You can get their info via:
21 error     npm owner ls npm-issue-clobber-log
21 error There is likely additional logging output above.
22 verbose exit [ 1, true ]
```

I know work is being done towards moving the location of these files. Perhaps a timestamp or some random bytes could be appended to the filename so they can avoid clobbering each other through being unique.

**Comment by timoxley** [comment]
Closing as duplicate. Looks like case is covered by https://github.com/npm/npm/pull/6744
In future, you should search for existing issues before creating new ones, thanks.
