### ISSUE TITLE
Error when updating with "-g"

### ISSUE THREAD

**Issue by DaAwesomeP** [npm/npm#7052]
Before I made issue #7000 for an error when *installing* globally. Now I have an error when updating.

CMD:
```bash
$ sudo npm update upb-cli
npm ERR! Object.keys called on non-object        # It repeats this block about 30 times
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>
npm ERR! Linux 3.13.0-39-generic
npm ERR! argv "node" "/usr/bin/npm" "update" "upb-cli" "-g"
npm ERR! node v0.10.34
npm ERR! npm  v2.1.14

npm ERR! Object.keys called on non-object
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/media/npm-debug.log
```
`npm-debug.log`:
```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/bin/npm', 'update', 'upb-cli', '-g' ]
2 info using npm@2.1.14
3 info using node@v0.10.34
4 verbose node symlink /usr/bin/node
5 silly mapToRegistry name upb-cli
6 silly mapToRegistry using default registry
7 silly mapToRegistry registry https://registry.npmjs.org/
8 silly mapToRegistry uri https://registry.npmjs.org/upb-cli
9 verbose request uri https://registry.npmjs.org/upb-cli
10 verbose request no auth needed
11 info attempt registry request try #1 at 13:50:02
12 verbose request id c796a4eefcfd6af6
13 verbose etag "CX6XFPQOAB6JCCH1XQKI8ZQWC"
14 http request GET https://registry.npmjs.org/upb-cli
15 verbose type called_on_non_object
16 verbose stack TypeError: Object.keys called on non-object
16 verbose stack     at Function.keys (native)
16 verbose stack     at unmarkExtraneous (/usr/lib/node_modules/npm/node_modules/read-installed/read-installed.js:362:10)
16 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-installed/read-installed.js:137:5
16 verbose stack     at next (/usr/lib/node_modules/npm/node_modules/read-installed/read-installed.js:185:14)
16 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-installed/read-installed.js:169:14
16 verbose stack     at Object.oncomplete (evalmachine.<anonymous>:108:15)
17 verbose cwd /home/media
18 error Linux 3.13.0-39-generic
19 error argv "node" "/usr/bin/npm" "update" "upb-cli" "-g"
20 error node v0.10.34
21 error npm  v2.1.14
22 error Object.keys called on non-object
23 error If you need help, you may report this error at:
23 error     <http://github.com/npm/npm/issues>
24 verbose exit [ 1, true ]
```
I had `upb-cli` v1.0.3 installed globally. The `man` error (#7000) was fixed in version 1.0.2. I tried removing it and re-intsalling the package, but it would always install v1.0.3 instead of v1.1.0 (the current version). This command works fine locally (without `-g`). Also, it works fine on Windows.

**Comment by DaAwesomeP** [comment]
Updating to NPM 2.1.17 would appear to have fixed it.
