### ISSUE TITLE
Can't publish module jquery.mb.miniAudioPlayer (ERROR parsing json)

### ISSUE THREAD

**Issue by pupunzi** [npm/npm#7063]
```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'publish' ]
2 info using npm@2.1.17
3 info using node@v0.10.33
4 verbose publish [ '.' ]
5 silly cache add args [ '.', null ]
6 verbose cache add spec .
7 silly cache add parsed spec { raw: '.',
7 silly cache add   scope: null,
7 silly cache add   name: null,
7 silly cache add   rawSpec: '.',
7 silly cache add   spec: '/Users/pupunzi/development/mb.components/jquery.mb.miniAudioPlayer',
7 silly cache add   type: 'directory' }
8 verbose addLocalDirectory /Users/pupunzi/.npm/jquery.mb.miniaudioplayer/1.8.2/package.tgz not in flight; packing
9 verbose tar pack [ '/Users/pupunzi/.npm/jquery.mb.miniaudioplayer/1.8.2/package.tgz',
9 verbose tar pack   '/Users/pupunzi/development/mb.components/jquery.mb.miniAudioPlayer' ]
10 verbose tarball /Users/pupunzi/.npm/jquery.mb.miniaudioplayer/1.8.2/package.tgz
11 verbose folder /Users/pupunzi/development/mb.components/jquery.mb.miniAudioPlayer
12 info prepublish jquery.mb.miniaudioplayer@1.8.2
13 verbose addLocalTarball adding from inside cache /Users/pupunzi/.npm/jquery.mb.miniaudioplayer/1.8.2/package.tgz
14 silly cache afterAdd jquery.mb.miniaudioplayer@1.8.2
15 verbose afterAdd /Users/pupunzi/.npm/jquery.mb.miniaudioplayer/1.8.2/package/package.json not in flight; writing
16 verbose afterAdd /Users/pupunzi/.npm/jquery.mb.miniaudioplayer/1.8.2/package/package.json written
17 silly publish { name: 'jquery.mb.miniaudioplayer',
17 silly publish   title: 'jQuery mb.miniAudioPlayer',
17 silly publish   description: 'This plugin let you add a minimal full featured player that takes advantage of the new HTML5 AUDIO tag with a flash fallback for browsers that don\'t support it. It is built on the jPlayer library',
17 silly publish   keywords: [ 'jquery-plugin', 'audio', 'HTML5', 'player', 'jPlayer' ],
17 silly publish   version: '1.8.2',
17 silly publish   author:
17 silly publish    { name: 'Pupunzi',
17 silly publish      email: 'matteo@open-lab.com',
17 silly publish      url: 'Matteo Bicocchi' },
17 silly publish   maintainers:
17 silly publish    [ { name: 'Pupunzi',
17 silly publish        email: 'matteo@open-lab.com',
17 silly publish        url: 'Matteo Bicocchi' } ],
17 silly publish   licenses:
17 silly publish    [ { type: 'MIT',
17 silly publish        url: 'https://github.com/pupunzi/jquery.mb.miniAudioPlayer/blob/master/licenses/GPL-LICENSE.txt' },
17 silly publish      { type: 'GPL',
17 silly publish        url: 'https://github.com/pupunzi/jquery.mb.miniAudioPlayer/blob/master/licenses/GPL-LICENSE.txt' } ],
17 silly publish   bugs: { url: 'https://github.com/pupunzi/jquery.mb.miniAudioPlayer/issues' },
17 silly publish   homepage: 'http://pupunzi.open-lab.com/mb-jquery-components/jquery-mb-miniaudioplayer/',
17 silly publish   demo: 'http://pupunzi.com/#mb.components/mb.miniAudioPlayer/miniAudioPlayer.html',
17 silly publish   docs: 'https://github.com/pupunzi/jquery.mb.miniAudioPlayer/wiki',
17 silly publish   download: 'http://pupunzi.open-lab.com/mb-jquery-components/jquery-mb-miniaudioplayer/',
17 silly publish   dependencies: { jquery: '>=1.8' },
17 silly publish   main: 'inc/jquery.mb.miniPlayer.js',
17 silly publish   scripts: { test: 'echo "Error: no test specified" && exit 1' },
17 silly publish   repository:
17 silly publish    { type: 'git',
17 silly publish      url: 'https://github.com/pupunzi/jquery.mb.miniAudioPlayer' },
17 silly publish   license: 'MIT',
17 silly publish   readme: '# mb.miniAudioPlayer\n\n__An open source jQuery component to build a mini audio player for your mp3 or ogg files.__\n\n<b>jquery.mb.miniPlayer</b> is a GUI implementation of the <a href="http://www.happyworm.com/jquery/jplayer/" target="_blank">jquery.jPlayer</a> plug-in realized by © Happyworm LTD. (many thanks to <a href="http://happyworm.com/blog/" target="_blank">Mark Boas</a>)\n\n![mb.menu](http://pupunzi.open-lab.com/wp-content/uploads/2011/05/DSC03757.jpg)\n\n[jquery.mb.components](http://pupunzi.com/), another way of thinking the web\n',
17 silly publish   readmeFilename: 'README.md',
17 silly publish   gitHead: 'dc810eb720e57b48642805deb94d914887f94afb',
17 silly publish   _id: 'jquery.mb.miniaudioplayer@1.8.2',
17 silly publish   _shasum: '2f8cea9131134dae51fbf2d4545dabca79f7329c',
17 silly publish   _from: '.' }
18 silly mapToRegistry name jquery.mb.miniaudioplayer
19 silly mapToRegistry using default registry
20 silly mapToRegistry registry https://registry.npmjs.org/
21 silly mapToRegistry uri https://registry.npmjs.org/jquery.mb.miniaudioplayer
22 verbose publish registryBase https://registry.npmjs.org/
23 silly publish uploading /Users/pupunzi/.npm/jquery.mb.miniaudioplayer/1.8.2/package.tgz
24 verbose request uri https://registry.npmjs.org/jquery.mb.miniaudioplayer
25 verbose request sending authorization for write operation
26 info attempt registry request try #1 at 17:01:13
27 verbose request id 0a677d1921a4915c
28 http request PUT https://registry.npmjs.org/jquery.mb.miniaudioplayer
29 http 502 https://registry.npmjs.org/jquery.mb.miniaudioplayer
30 verbose bad json <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
30 verbose bad json <html><head>
30 verbose bad json <title>502 Bad Gateway</title>
30 verbose bad json </head><body>
30 verbose bad json <h1>Bad Gateway</h1>
30 verbose bad json <p>The proxy server received an invalid
30 verbose bad json response from an upstream server.<br />
30 verbose bad json </p>
30 verbose bad json </body></html>
31 error registry error parsing json
32 info retry will retry, error on last attempt: SyntaxError: Unexpected token <
32 info retry <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
32 info retry <html><head>
32 info retry <title>502 Bad Gateway</title>
32 info retry </head><body>
32 info retry <h1>Bad Gateway</h1>
32 info retry <p>The proxy server received an invalid
32 info retry response from an upstream server.<br />
32 info retry </p>
32 info retry </body></html>
33 info attempt registry request try #2 at 17:01:31
34 http request PUT https://registry.npmjs.org/jquery.mb.miniaudioplayer
35 http 502 https://registry.npmjs.org/jquery.mb.miniaudioplayer
36 verbose bad json <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
36 verbose bad json <html><head>
36 verbose bad json <title>502 Bad Gateway</title>
36 verbose bad json </head><body>
36 verbose bad json <h1>Bad Gateway</h1>
36 verbose bad json <p>The proxy server received an invalid
36 verbose bad json response from an upstream server.<br />
36 verbose bad json </p>
36 verbose bad json </body></html>
37 error registry error parsing json
38 info retry will retry, error on last attempt: SyntaxError: Unexpected token <
38 info retry <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
38 info retry <html><head>
38 info retry <title>502 Bad Gateway</title>
38 info retry </head><body>
38 info retry <h1>Bad Gateway</h1>
38 info retry <p>The proxy server received an invalid
38 info retry response from an upstream server.<br />
38 info retry </p>
38 info retry </body></html>
39 info attempt registry request try #3 at 17:02:41
40 http request PUT https://registry.npmjs.org/jquery.mb.miniaudioplayer
41 http 502 https://registry.npmjs.org/jquery.mb.miniaudioplayer
42 verbose bad json <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
42 verbose bad json <html><head>
42 verbose bad json <title>502 Bad Gateway</title>
42 verbose bad json </head><body>
42 verbose bad json <h1>Bad Gateway</h1>
42 verbose bad json <p>The proxy server received an invalid
42 verbose bad json response from an upstream server.<br />
42 verbose bad json </p>
42 verbose bad json </body></html>
43 error registry error parsing json
44 verbose headers { date: 'Mon, 05 Jan 2015 16:02:40 GMT',
44 verbose headers   server: 'Apache',
44 verbose headers   'content-length': '232',
44 verbose headers   'keep-alive': 'timeout=10, max=50',
44 verbose headers   connection: 'Keep-Alive',
44 verbose headers   'content-type': 'text/html; charset=iso-8859-1' }
45 verbose request invalidating /Users/pupunzi/.npm/registry.npmjs.org/jquery.mb.miniaudioplayer on PUT
46 error publish Failed PUT 502
47 verbose type unexpected_token
48 verbose stack SyntaxError: Unexpected token <
48 verbose stack <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
48 verbose stack <html><head>
48 verbose stack <title>502 Bad Gateway</title>
48 verbose stack </head><body>
48 verbose stack <h1>Bad Gateway</h1>
48 verbose stack <p>The proxy server received an invalid
48 verbose stack response from an upstream server.<br />
48 verbose stack </p>
48 verbose stack </body></html>
48 verbose stack
48 verbose stack     at Object.parse (native)
48 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:199:23)
48 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
48 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:373:22)
48 verbose stack     at Request.emit (events.js:98:17)
48 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1318:14)
48 verbose stack     at Request.emit (events.js:117:20)
48 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1266:12)
48 verbose stack     at IncomingMessage.emit (events.js:117:20)
48 verbose stack     at _stream_readable.js:943:16
49 verbose cwd /Users/pupunzi/development/mb.components/jquery.mb.miniAudioPlayer
50 error Darwin 14.0.0
51 error argv "node" "/usr/local/bin/npm" "publish"
52 error node v0.10.33
53 error npm  v2.1.17
54 error Unexpected token <
54 error <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
54 error <html><head>
54 error <title>502 Bad Gateway</title>
54 error </head><body>
54 error <h1>Bad Gateway</h1>
54 error <p>The proxy server received an invalid
54 error response from an upstream server.<br />
54 error </p>
54 error </body></html>
55 error If you need help, you may report this error at:
55 error     <http://github.com/npm/npm/issues>
56 verbose exit [ 1, true ]
```

**Comment by pupunzi** [comment]
Thnx Smikes, it worked!

**Comment by othiym23** [comment]
Closing as resolved.
