### ISSUE TITLE
npm ERR! registry error parsing json

### ISSUE THREAD

**Issue by kimpetersend1** [npm/npm#7092]
Hi guys.

I am trying to install gulp (npm install --global gulp) and all of a sudden I am getting a huge string or errors. See below:
```
λ npm install --global gulp
npm ERR! registry error parsing json
npm ERR! SyntaxError: Unexpected token <
npm ERR! <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
npm ERR! <HTML><HEAD><TITLE>Error Message</TITLE>
npm ERR! <META http-equiv=Content-Type content="text/html; charset=UTF-8">
npm ERR! <STYLE id=L_default_1>A {
npm ERR!        FONT-WEIGHT: bold; FONT-SIZE: 10pt; COLOR: #005a80; FONT-FAMILY: tahoma
npm ERR! }
npm ERR! A:hover {
npm ERR!        FONT-WEIGHT: bold; FONT-SIZE: 10pt; COLOR: #0d3372; FONT-FAMILY: tahoma
npm ERR! }
npm ERR! TD {
npm ERR!        FONT-SIZE: 8pt; FONT-FAMILY: tahoma
npm ERR! }
npm ERR! TD.titleBorder {
npm ERR!        BORDER-RIGHT: #955319 1px solid; BORDER-TOP: #955319 1px solid; PADDING-LEFT: 8px; FONT-WEIGHT: bold; FONT-SIZE: 12pt; VERTICAL-ALIGN: middle; BORDER-LEFT: #955319 0px solid; COLOR: #955319; BORDER-BOTTOM: #955319 1px solid; FONT-FAMILY: tahoma; HEIGHT: 35px; BACKGROUND-COLOR: #d2b87a; TEXT-ALIGN: left
npm ERR! }
npm ERR! TD.titleBorderx {
npm ERR!        BORDER-RIGHT: #955319 0px solid; BORDER-TOP: #955319 1px solid; PADDING-LEFT: 8px; FONT-WEIGHT: bold; FONT-SIZE: 12pt; VERTICAL-ALIGN: middle; BORDER-LEFT: #955319 1px solid; COLOR: #978c79; BORDER-BOTTOM: #955319 1px solid; FONT-FAMILY: tahoma; HEIGHT: 35px; BACKGROUND-COLOR: #d2b87a; TEXT-ALIGN: left
npm ERR! }
npm ERR! .TitleDescription {
npm ERR!        FONT-WEIGHT: bold; FONT-SIZE: 12pt; COLOR: black; FONT-FAMILY: tahoma
npm ERR! }
npm ERR! SPAN.explain {
npm ERR!        FONT-WEIGHT: normal; FONT-SIZE: 10pt; COLOR: #934225
npm ERR! }
npm ERR! SPAN.TryThings {
npm ERR!        FONT-WEIGHT: normal; FONT-SIZE: 10pt; COLOR: #934225
npm ERR! }
npm ERR! .TryList {
npm ERR!        MARGIN-TOP: 5px; FONT-WEIGHT: normal; FONT-SIZE: 8pt; COLOR: black; FONT-FAMILY: tahoma
npm ERR! }
npm ERR! .X {
npm ERR!        BORDER-RIGHT: #955319 1px solid; BORDER-TOP: #955319 1px solid; FONT-WEIGHT: normal; FONT-SIZE: 12pt; BORDER-LEFT: #955319 1px solid; COLOR: #7b3807; BORDER-BOTTOM: #955319 1px solid; FONT-FAMILY: verdana; BACKGROUND-COLOR: #d1c2b4
npm ERR! }
npm ERR! .adminList {
npm ERR!        MARGIN-TOP: 2px
npm ERR! }
npm ERR! </STYLE>
npm ERR! <META content="MSHTML 6.00.2800.1170" name=GENERATOR></HEAD>
npm ERR! <BODY bgColor=#f3f3ed>
npm ERR! <TABLE cellSpacing=0 cellPadding=0 width="100%">
npm ERR!   <TBODY>
npm ERR!   <TR>
npm ERR!     <TD class=titleBorderx width=30>
npm ERR!       <TABLE height=25 cellSpacing=2 cellPadding=0 width=25 bgColor=black>
npm ERR!         <TBODY>
npm ERR!         <TR>
npm ERR!           <TD id=L_default_x class=x valign=middle align=center>X</TD>
npm ERR!         </TR>
npm ERR!         </TBODY>
npm ERR!       </TABLE>
npm ERR!     </TD>
npm ERR!     <TD class=titleBorder id=L_default_2>Network Access Message:<SPAN class=TitleDescription> The page cannot be displayed</SPAN> </TD>
npm ERR!   </TR>
npm ERR!   </TBODY>
npm ERR! </TABLE>
npm ERR!
npm ERR! <TABLE id=spacer>
npm ERR!   <TBODY>
npm ERR!   <TR>
npm ERR!     <TD height=10></TD></TR></TBODY></TABLE>
npm ERR! <TABLE width=400>
npm ERR!   <TBODY>
npm ERR!   <TR>
npm ERR!     <TD noWrap width=25></TD>
npm ERR!     <TD width=400><SPAN class=explain><ID id=L_default_3><B>Explanation:</B></ID></SPAN><ID id=L_default_4> There is a problem with the page you are trying to reach and it cannot be displayed. </ID><BR><BR>
npm ERR!     <B><SPAN class=tryThings><ID id=L_default_5><B>Try the following:</B></ID></SPAN></B>
npm ERR!       <UL class=TryList>
npm ERR!         <LI id=L_default_6><B>Refresh page:</B> Search for the page again by clicking the Refresh button. The timeout may have occurred due to Internet congestion.
npm ERR! <LI id=L_default_7><B>Check spelling:</B> Check that you typed the Web page address correctly. The address may have been mistyped.
npm ERR! <LI id=L_default_8><B>Access from a link:</B> If there is a link to the page you are looking for, try accessing the page from that link.
npm ERR!
npm ERR!       </UL>
npm ERR! <ID id=L_default_9>If you are still not able to view the requested page, try contacting your administrator or Helpdesk.</ID> <BR><BR>
npm ERR!     </TD>
npm ERR!   </TR>
npm ERR!   </TBODY>
npm ERR! </TABLE>
npm ERR!
npm ERR! <TABLE id=spacer><TBODY><TR><TD height=15></TD></TR></TBODY></TABLE>
npm ERR!
npm ERR! <TABLE width=400>
npm ERR!   <TBODY>
npm ERR!   <TR>
npm ERR!     <TD noWrap width=25></TD>
npm ERR!     <TD width=400 id=L_default_10><B>Technical Information (for support personnel)</B>
npm ERR!       <UL class=adminList>
npm ERR!         <LI id=L_default_11>Error Code: 407 Proxy Authentication Required. Forefront TMG requires authorization to fulfill the request. Access to the Web Proxy filter is denied. (12209)
npm ERR! <LI id=L_default_12>IP Address: 192.168.3.128
npm ERR! <LI id=L_default_13>Date: 2015/01/08 12:31:50 PM [GMT]
npm ERR! <LI id=L_default_14>Server: vpbrctnptmg02.corp.primedia.co.za
npm ERR! <LI id=L_default_15>Source: proxy
npm ERR!
npm ERR!       </UL>
npm ERR!     </TD>
npm ERR!   </TR>
npm ERR!   </TBODY>
npm ERR! </TABLE>
npm ERR!
npm ERR! </BODY>
npm ERR! </HTML>
npm ERR!
npm ERR!
npm ERR!     at Object.parse (native)
npm ERR!     at RegClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:274:23)
npm ERR!     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:246:65)
npm ERR!     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:236:22)
npm ERR!     at Request.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1142:14)
npm ERR!     at Request.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1096:12)
npm ERR!     at IncomingMessage.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:944:16
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--global" "gulp"
npm ERR! cwd C:\
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! type unexpected_token
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\npm-debug.log
npm ERR! not ok code 0
```
I can't install anything via npm, I have tried re-installing node as well but still no luck.

I am not sure how to go about fixing this issue, can anyone offer some help? Anyone experience this problem as well?

**Comment by brianjmiller** [comment]
I've been getting similar issue since yesterday afternoon trying to publish a module update. I can provide an npm-debug.log if necessary. AFAICT my package.json is good, the only thing that changed recently is the version property.

**Comment by KenanY** [comment]
```
Error Code: 407 Proxy Authentication Required. Forefront TMG requires authorization to fulfill the request. Access to the Web Proxy filter is denied. (12209)
```

@kimpetersend1 Are you behind a proxy? The error message is saying that you have to authenticate yourself with said proxy before using it.

**Comment by kimpetersend1** [comment]
@KenanY Yes I am behind a work proxy, what is the correct way to go about setting it up so that it bypasses the proxy?

**Comment by othiym23** [comment]
See the [proxy settings](https://docs.npmjs.com/misc/config#proxy) and [https-proxy](https://docs.npmjs.com/misc/config#https-proxy) information in the configuration documentation.

**Comment by KenanY** [comment]
@kimpetersend1 Are you still having this issue? I hope that the config docs that @othiym23 linked to were sufficient enough to get you up and running with your proxy :)

**Comment by smikes** [comment]
Can this issue now be closed?

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by kimpetersend1** [comment]
The issue can be closed :) thank you so much

On Thu, Feb 19, 2015 at 3:40 PM, Sam Mikes <notifications@github.com> wrote:

> Can this issue now be closed?
>
> We are trying to clean up older npm issues, so if we don't hear back from
> you within a week, we will close this issue. (Don't worry -- you can always
> come back again and open a new issue!)
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/npm/npm/issues/7092#issuecomment-75052972>.
>



-- 
Kim Petersen
*kimpetersend1.com <http://kimpetersend1.com/>*

<https://www.facebook.com/SektorDesigns> <https://twitter.com/KimD1Petersen>
<http://www.behance.net/sektorDesigns> <http://slayerd1.deviantart.com>

**Comment by othiym23** [comment]
Closing as resolved.

**Comment by calidion** [comment]
I have this problem too.
when publish npm modules.
but modules can be successfully published.

```sh
npm publish
npm ERR! registry error parsing json
+ node-weixin-oauth@0.2.0
```

**Comment by smikes** [comment]
@calidion can you please open a new issue?

**Comment by calidion** [comment]
@smikes 
after updated to the newest version, this error disappeared.
