### ISSUE TITLE
Installing under Windows 7 Enterprise in GitBash fails with errors.

### ISSUE THREAD

**Issue by Spirit328** [npm/npm#7093]
Hi there!

First let me thank you for the effort of writing a asciidoc preview for atom
When I wanted to install it on my Windows 7 Enterprise I have some issues.

First of all. Here is the log, when I ran in it in GitBash.

```
$ apm install asciidoc-preview
Installing asciidoc-preview to C:\Users\tmichels\.atom\packages failed

npm http GET https://registry.npmjs.org/asciidoctor.js/1.5.2
npm http GET https://registry.npmjs.org/opal-npm-wrapper
npm http GET https://registry.npmjs.org/cheerio
npm http GET https://registry.npmjs.org/fs-plus
npm http GET https://registry.npmjs.org/temp
npm http GET https://registry.npmjs.org/wrench
npm http GET https://registry.npmjs.org/underscore-plus
npm http GET https://registry.npmjs.org/mustache/0.8.2
npm http GET https://registry.npmjs.org/fuzzaldrin
npm WARN `git config --get remote.origin.url` returned wrong result (git://githu
b.com/saschagehlich/autocomplete-plus.git)
npm http 304 https://registry.npmjs.org/fs-plus
npm http 304 https://registry.npmjs.org/cheerio
npm http 304 https://registry.npmjs.org/underscore-plus
npm http 304 https://registry.npmjs.org/temp
npm http 304 https://registry.npmjs.org/wrench
npm http 304 https://registry.npmjs.org/fuzzaldrin
npm http 304 https://registry.npmjs.org/asciidoctor.js/1.5.2
npm http 304 https://registry.npmjs.org/opal-npm-wrapper
npm http 304 https://registry.npmjs.org/mustache/0.8.2
npm http GET https://registry.npmjs.org/underscore
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/osenv/0.0.3
npm http 200 https://registry.npmjs.org/mkdirp
npm http 200 https://registry.npmjs.org/underscore
npm http 200 https://registry.npmjs.org/osenv/0.0.3
npm http 200 https://registry.npmjs.org/rimraf
npm http 200 https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/mkdirp/-/mkdirp-0.3.5.tgz
npm http 200 https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/underscore/-/underscore-1.6.0.tgz
npm http GET https://registry.npmjs.org/rimraf/-/rimraf-2.2.8.tgz
npm http GET https://registry.npmjs.org/osenv/-/osenv-0.0.3.tgz
npm http GET https://registry.npmjs.org/async/-/async-0.2.10.tgz
npm http GET https://registry.npmjs.org/rimraf/-/rimraf-2.1.4.tgz
npm http 200 https://registry.npmjs.org/underscore/-/underscore-1.6.0.tgz
npm http 200 https://registry.npmjs.org/rimraf/-/rimraf-2.2.8.tgz
npm http 200 https://registry.npmjs.org/mkdirp/-/mkdirp-0.3.5.tgz
npm http 200 https://registry.npmjs.org/osenv/-/osenv-0.0.3.tgz
npm http 200 https://registry.npmjs.org/rimraf/-/rimraf-2.1.4.tgz
npm http 200 https://registry.npmjs.org/async/-/async-0.2.10.tgz
npm http GET https://registry.npmjs.org/event-kit
npm http GET https://registry.npmjs.org/grim
npm http GET https://registry.npmjs.org/minimatch
npm http GET https://registry.npmjs.org/async/-/async-0.9.0.tgz
npm http GET https://registry.npmjs.org/temp/-/temp-0.8.1.tgz
npm http 200 https://registry.npmjs.org/event-kit
npm http 200 https://registry.npmjs.org/grim
npm http 200 https://registry.npmjs.org/minimatch
npm http 200 https://registry.npmjs.org/async/-/async-0.9.0.tgz
npm http 200 https://registry.npmjs.org/temp/-/temp-0.8.1.tgz
npm http GET https://registry.npmjs.org/minimatch/-/minimatch-2.0.1.tgz
npm http GET https://registry.npmjs.org/grim/-/grim-1.0.0.tgz
npm http GET https://registry.npmjs.org/event-kit/-/event-kit-1.0.1.tgz
npm http 200 https://registry.npmjs.org/minimatch/-/minimatch-2.0.1.tgz
npm http 200 https://registry.npmjs.org/grim/-/grim-1.0.0.tgz
npm http 200 https://registry.npmjs.org/event-kit/-/event-kit-1.0.1.tgz
npm http GET https://registry.npmjs.org/CSSselect
npm http GET https://registry.npmjs.org/lodash
npm http GET https://registry.npmjs.org/htmlparser2
npm http GET https://registry.npmjs.org/entities
npm http GET https://registry.npmjs.org/graceful-fs
npm http 200 https://registry.npmjs.org/entities
npm http GET https://registry.npmjs.org/entities/-/entities-1.0.0.tgz
npm http 200 https://registry.npmjs.org/lodash
npm http 200 https://registry.npmjs.org/htmlparser2
npm http 200 https://registry.npmjs.org/graceful-fs
npm http GET https://registry.npmjs.org/lodash/-/lodash-2.4.1.tgz
npm http GET https://registry.npmjs.org/graceful-fs/-/graceful-fs-1.2.3.tgz
npm http GET https://registry.npmjs.org/htmlparser2/-/htmlparser2-3.7.3.tgz
npm http 200 https://registry.npmjs.org/entities/-/entities-1.0.0.tgz
npm http 200 https://registry.npmjs.org/lodash/-/lodash-2.4.1.tgz
npm http 200 https://registry.npmjs.org/graceful-fs/-/graceful-fs-1.2.3.tgz
npm http 200 https://registry.npmjs.org/htmlparser2/-/htmlparser2-3.7.3.tgz
npm http 200 https://registry.npmjs.org/CSSselect
npm http GET https://registry.npmjs.org/CSSselect/-/CSSselect-0.4.1.tgz
npm http 200 https://registry.npmjs.org/CSSselect/-/CSSselect-0.4.1.tgz
npm http GET https://registry.npmjs.org/emissary
npm http GET https://registry.npmjs.org/coffeestack
npm http 200 https://registry.npmjs.org/coffeestack
npm http 200 https://registry.npmjs.org/emissary
npm http GET https://registry.npmjs.org/coffeestack/-/coffeestack-0.7.0.tgz
npm http GET https://registry.npmjs.org/emissary/-/emissary-1.3.1.tgz
npm http 200 https://registry.npmjs.org/coffeestack/-/coffeestack-0.7.0.tgz
npm http 200 https://registry.npmjs.org/emissary/-/emissary-1.3.1.tgz
npm http GET https://registry.npmjs.org/brace-expansion
npm http 200 https://registry.npmjs.org/brace-expansion
npm http GET https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.0.tgz
npm http 200 https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.0.tgz
npm http GET https://registry.npmjs.org/xmlhttprequest
npm http 200 https://registry.npmjs.org/xmlhttprequest
npm http GET https://registry.npmjs.org/xmlhttprequest/-/xmlhttprequest-1.6.0.tgz
npm http 200 https://registry.npmjs.org/xmlhttprequest/-/xmlhttprequest-1.6.0.tgz
npm http GET https://registry.npmjs.org/coffee-script
npm http GET https://registry.npmjs.org/source-map
npm http 200 https://registry.npmjs.org/coffee-script
npm http GET https://registry.npmjs.org/mixto
npm http GET https://registry.npmjs.org/property-accessors
npm http GET https://registry.npmjs.org/coffee-script/-/coffee-script-1.7.1.tgz
npm http 200 https://registry.npmjs.org/source-map
npm http GET https://registry.npmjs.org/source-map/-/source-map-0.1.43.tgz
npm http 200 https://registry.npmjs.org/property-accessors
npm http 200 https://registry.npmjs.org/mixto
npm http 200 https://registry.npmjs.org/coffee-script/-/coffee-script-1.7.1.tgz
npm http GET https://registry.npmjs.org/property-accessors/-/property-accessors-1.1.0.tgz
npm http 200 https://registry.npmjs.org/source-map/-/source-map-0.1.43.tgz
npm http GET https://registry.npmjs.org/mixto/-/mixto-1.0.0.tgz
npm http 200 https://registry.npmjs.org/property-accessors/-/property-accessors-1.1.0.tgz
npm ERR! git clone https://github.com/Benvie/harmony-collections.git Cloning into bare repository 'C:\Users\tmichels\.atom\.node-gyp\.atom\.apm\_git-remotes\https-github-com-Benvie-harmony-collections-git-df214100'...
npm ERR! git clone https://github.com/Benvie/harmony-collections.git fatal: Unable to find remote helper for 'https'
npm http 200 https://registry.npmjs.org/mixto/-/mixto-1.0.0.tgz
npm ERR! Error: ENOENT, lstat 'C:\Users\tmichels\AppData\Local\Temp\apm-install-dir-11508-556-x96dhp\node_modules\asciidoc-preview\node_modules\autocomplete-plus\node_modules\minimatch\node_modules\brace-expansion\test\bash-comparison.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "c:\\Users\\tmichels\\AppData\\Local\\atom\\app-0.166.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\bin\\node.exe" "c:\\Users\\tmichels\\AppData\\Local\\atom\\app-0.166.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "c:\\Users\\tmichels\\AppData\\Local\\atom\\app-0.166.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\.apmrc" "--userconfig" "C:\\Users\\tmichels\\.atom\\.apmrc" "install" "C:\\Users\\tmichels\\.atom\\.node-gyp\\.atom\\.apm\\asciidoc-preview\\0.4.1\\package.tgz" "--target=0.18.0" "--arch=ia32"
npm ERR! cwd C:\Users\tmichels\AppData\Local\Temp\apm-install-dir-11508-556-x96dhp
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.4
npm ERR! path C:\Users\tmichels\AppData\Local\Temp\apm-install-dir-11508-556-x96dhp\node_modules\asciidoc-preview\node_modules\autocomplete-plus\node_modules\minimatch\node_modules\brace-expansion\test\bash-comparison.js
npm ERR! fstream_path C:\Users\tmichels\AppData\Local\Temp\apm-install-dir-11508-556-x96dhp\node_modules\asciidoc-preview\node_modules\autocomplete-plus\node_modules\minimatch\node_modules\brace-expansion\test\bash-comparison.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack c:\Users\tmichels\AppData\Local\atom\app-0.166.0\resources\app\apm\node_modules\atom-package-manager\node_modules\npm\node_modules\fstream\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: Command failed: Cloning into bare repository 'C:\Users\tmichels\.atom\.node-gyp\.atom\.apm\_git-remotes\https-github-com-Benvie-harmony-collections-git-df214100'...
npm ERR! fatal: Unable to find remote helper for 'https'
npm ERR!
npm ERR!     at ChildProcess.exithandler (child_process.js:648:15)
npm ERR!     at ChildProcess.emit (events.js:98:17)
npm ERR!     at maybeClose (child_process.js:756:16)
npm ERR!     at Process.ChildProcess._handle.onexit (child_process.js:823:5)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "c:\\Users\\tmichels\\AppData\\Local\\atom\\app-0.166.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\bin\\node.exe" "c:\\Users\\tmichels\\AppData\\Local\\atom\\app-0.166.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "c:\\Users\\tmichels\\AppData\\Local\\atom\\app-0.166.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\.apmrc" "--userconfig" "C:\\Users\\tmichels\\.atom\\.apmrc" "install" "C:\\Users\\tmichels\\.atom\\.node-gyp\\.atom\\.apm\\asciidoc-preview\\0.4.1\\package.tgz" "--target=0.18.0" "--arch=ia32"
npm ERR! cwd C:\Users\tmichels\AppData\Local\Temp\apm-install-dir-11508-556-x96dhp
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.4
npm ERR! code 128
npm http GET https://registry.npmjs.org/CSSwhat
npm http GET https://registry.npmjs.org/domutils
npm http GET https://registry.npmjs.org/domhandler
npm http GET https://registry.npmjs.org/domutils
npm http GET https://registry.npmjs.org/domelementtype
npm http GET https://registry.npmjs.org/readable-stream
npm http 200 https://registry.npmjs.org/domutils
npm http 200 https://registry.npmjs.org/CSSwhat
npm http GET https://registry.npmjs.org/amdefine
npm http GET https://registry.npmjs.org/domutils/-/domutils-1.4.3.tgz
npm http GET https://registry.npmjs.org/CSSwhat/-/CSSwhat-0.4.7.tgz
npm http 200 https://registry.npmjs.org/domelementtype
npm http 200 https://registry.npmjs.org/domhandler
npm http GET https://registry.npmjs.org/domelementtype/-/domelementtype-1.1.3.tgz
npm http 200 https://registry.npmjs.org/readable-stream
npm http GET https://registry.npmjs.org/domhandler/-/domhandler-2.2.1.tgz
npm http 200 https://registry.npmjs.org/domutils
npm http 200 https://registry.npmjs.org/domutils/-/domutils-1.4.3.tgz
npm http GET https://registry.npmjs.org/readable-stream/-/readable-stream-1.1.13.tgz
npm http 200 https://registry.npmjs.org/CSSwhat/-/CSSwhat-0.4.7.tgz
npm http GET https://registry.npmjs.org/domutils/-/domutils-1.5.0.tgz
npm http 200 https://registry.npmjs.org/domelementtype/-/domelementtype-1.1.3.tgz
npm http 200 https://registry.npmjs.org/domhandler/-/domhandler-2.2.1.tgz
npm http 200 https://registry.npmjs.org/amdefine
npm http GET https://registry.npmjs.org/amdefine/-/amdefine-0.1.0.tgz
npm http 200 https://registry.npmjs.org/domutils/-/domutils-1.5.0.tgz
npm http 200 https://registry.npmjs.org/readable-stream/-/readable-stream-1.1.13.tgz
npm http 200 https://registry.npmjs.org/amdefine/-/amdefine-0.1.0.tgz
npm http GET https://registry.npmjs.org/isarray/0.0.1
npm http GET https://registry.npmjs.org/core-util-is
npm http GET https://registry.npmjs.org/string_decoder
npm http GET https://registry.npmjs.org/inherits
npm http 200 https://registry.npmjs.org/inherits
npm http 200 https://registry.npmjs.org/isarray/0.0.1
npm http 200 https://registry.npmjs.org/string_decoder
npm http 200 https://registry.npmjs.org/core-util-is
npm http GET https://registry.npmjs.org/isarray/-/isarray-0.0.1.tgz
npm http GET https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.1.tgz
npm http GET https://registry.npmjs.org/string_decoder/-/string_decoder-0.10.31.tgz
npm http 200 https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.1.tgz
npm http 200 https://registry.npmjs.org/isarray/-/isarray-0.0.1.tgz
npm http 200 https://registry.npmjs.org/string_decoder/-/string_decoder-0.10.31.tgz
npm http GET https://registry.npmjs.org/inherits/-/inherits-2.0.1.tgz
npm http 200 https://registry.npmjs.org/inherits/-/inherits-2.0.1.tgz
npm
```

Then I tried to download the whole package and just push it into the package directory of my atom installation. - DO NOT WORK either.

It would be so GREAT if you have any hints, because I need the preview for writing some documentation and markdown is not appropiate.

Thank you very much in advance and keep on rooking.

Cheers
Thorsten

**Comment by KenanY** [comment]
```
$ apm install asciidoc-preview
```

Sorry, but we can't really offer any support for `apm`, especially because of the very old version of `npm` they are bundling (log shows `npm@1.4.4` but latest is `npm@2.1.17`).

**Comment by Spirit328** [comment]
Hi  Kenan,

some times it is hard to see the forest because of all the trees, 
I should have checked this myself and I appologize for bothering you.

Although I just downloaded the newest version, but this is obviously wrong.

I will try with the newest version of apm and will provide feedback, if you like,

Kind Regards
Thorsten

**Comment by KenanY** [comment]
@Spirit328 You may indeed have the latest version of `apm`, but unfortunately even then the `npm` version [being used](https://github.com/atom/apm/blob/v0.117.0/package.json#L34) is still `1.4.4`, which is way too old to realistically support anymore. There have been _a lot_ of fixes since `1.4.4`.

**Comment by othiym23** [comment]
@KenanY Well, I don't know that I'd go _that_ far. We'll support you if you're running 1.4.x, by gently encouraging you to upgrade to `npm@1.4.28`, and from there to `npm@latest` if 1.4.28 doesn't fix your problem. It would be a major improvement to `apm` were they to make it auto-update the bundled version of npm (or just use the system npm, if one's there).

@Spirit328 You should probably help us out by pestering the Atom maintainers to update apm to use a newer version of npm. As @KenanY mentions, there are a whole host of race conditions and other concurrency and caching issues that have been fixed since 1.4.4, and the 1.4.x release series is in fact finished as of 1.4.28. You could always try upgrading the version of npm in place inside apm, but if you're not pretty comfortable with running npm from the command line, that might be more risky than you're comfortable with.

**Comment by KenanY** [comment]
@othiym23 Of course I won't abandon `1.4` support just yet, but if one is "stuck" on `1.4.4` like in this issue, well....

**Comment by kevinsawicki** [comment]
> You should probably help us out by pestering the Atom maintainers to update apm to use a newer version of npm.

Thanks for this nudge, I'll upgrade apm soon to 1.4.28 and then look into a 2.0 upgrade.

**Comment by othiym23** [comment]
I'm going to call this resolved for now. apm is on the track to using a newish version of `npm@2`, and this wasn't really an npm version to begin with. Good luck, @Spirit328!

**Comment by Spirit328** [comment]
I just double checked. It works fine for me.
Great job! Thanks a lot!
You guys rock!
