### ISSUE TITLE
xml error when trying to publish module

### ISSUE THREAD

**Issue by leon** [npm/npm#7103]
Hi!

I'm getting a xml response from the server when I'm trying to publish a package
the package in question was recently unpublished by it's author, and I would now like to publish it back.
Is that why the server doesn't like it?

```
npm info retry <?xml version="1.0" encoding="utf-8"?>
npm info retry <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
npm info retry  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
npm info retry <html>
npm info retry   <head>
npm info retry     <title>503 backend write error</title>
npm info retry   </head>
npm info retry   <body>
npm info retry     <h1>Error 503 backend write error</h1>
npm info retry     <p>backend write error</p>
npm info retry     <h3>Guru Mediation:</h3>
npm info retry     <p>Details: cache-fra1220-FRA 1420815740 1503835210</p>
npm info retry     <hr>
npm info retry     <p>Varnish cache server</p>
npm info retry   </body>
npm info retry </html>
```

**Comment by smikes** [comment]
You cannot republish a version that has been unpublished, so you may need to increase the version number.  However I am not sure what's going wrong - could you please upload your full `npm-debug.log` as a gist <https://gist.github.com> and post the link here?

**Comment by zswang** [comment]
me too.

```
169 info trying registry request attempt 3 at 11:55:53
170 http PUT http://registry.npmjs.org/jdists
171 http 503 http://registry.npmjs.org/jdists
172 verbose bad json <?xml version="1.0" encoding="utf-8"?>
172 verbose bad json <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
172 verbose bad json  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
172 verbose bad json <html>
172 verbose bad json   <head>
172 verbose bad json     <title>503 backend write error</title>
172 verbose bad json   </head>
172 verbose bad json   <body>
172 verbose bad json     <h1>Error 503 backend write error</h1>
172 verbose bad json     <p>backend write error</p>
172 verbose bad json     <h3>Guru Mediation:</h3>
172 verbose bad json     <p>Details: cache-ty68-TYO 1421034952 91931586</p>
172 verbose bad json     <hr>
172 verbose bad json     <p>Varnish cache server</p>
172 verbose bad json   </body>
172 verbose bad json </html>
173 error registry error parsing json
174 verbose headers { server: 'Varnish',
174 verbose headers   'retry-after': '0',
174 verbose headers   'content-type': 'text/html; charset=utf-8',
174 verbose headers   'content-length': '446',
174 verbose headers   'accept-ranges': 'bytes',
174 verbose headers   date: 'Mon, 12 Jan 2015 03:55:52 GMT',
174 verbose headers   via: '1.1 varnish',
174 verbose headers   connection: 'close',
174 verbose headers   'x-served-by': 'cache-ty68-TYO',
174 verbose headers   'x-cache': 'MISS',
174 verbose headers   'x-cache-hits': '0',
174 verbose headers   'x-timer': 'S1421034951.743732,VS0,VE566' }
175 error publish Failed PUT 503
176 error SyntaxError: Unexpected token <
176 error
176 error <?xml version="1.0" encoding="utf-8"?>
176 error <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
176 error  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
176 error <html>
176 error   <head>
176 error     <title>503 backend write error</title>
176 error   </head>
176 error   <body>
176 error     <h1>Error 503 backend write error</h1>
176 error     <p>backend write error</p>
176 error     <h3>Guru Mediation:</h3>
176 error     <p>Details: cache-ty68-TYO 1421034952 91931586</p>
176 error     <hr>
176 error     <p>Varnish cache server</p>
176 error   </body>
176 error </html>
176 error
176 error     at Object.parse (native)
176 error     at RegClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:239:23)
176 error     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:211:65)
176 error     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:123:22)
176 error     at Request.EventEmitter.emit (events.js:98:17)
176 error     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:893:14)
176 error     at Request.EventEmitter.emit (events.js:117:20)
176 error     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:844:12)
176 error     at IncomingMessage.EventEmitter.emit (events.js:117:20)
176 error     at _stream_readable.js:919:16
177 error If you need help, you may report this *entire* log,
177 error including the npm and node versions, at:
177 error     <http://github.com/npm/npm/issues>
178 error System Darwin 14.0.0
179 error command "node" "/usr/local/bin/npm" "publish"
180 error cwd /Users/zswang/Documents/github/jdists
181 error node -v v0.10.28
182 error npm -v 1.4.9
183 error type unexpected_token
184 verbose exit [ 1, true ]
```

File contains unicode charset.

**Comment by zswang** [comment]
Problem has been resolved.

Because I changed the password.

This tip is not friendly.

**Comment by smikes** [comment]
Can this issue now be closed?

It looks like there's a feature request here, for more descriptive error messages when writes to the registry fail.  Is that what you mean, @zswang , when you say "This tip is not friendly"?

If so, I think that issue probably belongs on <https://github.com/npm/npm-registry-couchapp> instead of here.

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by zswang** [comment]
I know, go ahead.
Thanks.

**Comment by othiym23** [comment]
Closing as resolved / abandoned.
