### ISSUE TITLE
spawn ENOENT - cannot push to git

### ISSUE THREAD

**Issue by dibeesh** [npm/npm#7134]
Hi,
When i try to push in to git am getting following error. Could you please help me to find a solution. 

```
-----> Node.js app detected

       Node engine:         0.10.x
       Npm engine:          1.1.x
       Start mechanism:     Procfile
       node_modules source: prebuilt
       node_modules cached: true

       NPM_CONFIG_PRODUCTION=true
       NODE_MODULES_CACHE=true

-----> Installing binaries
       Resolving node version 0.10.x via semver.io...
       Downloading and installing node 0.10.35...
       Resolving npm version 1.1.x via semver.io...
       Downloading and installing npm 1.1.71 (replacing version 1.4.28)...

-----> Building dependencies
       Rebuilding any native modules for this architecture
       npm WARN package.json OutboxProApi@0.0.1 No README.md file found!
       npm ERR! Error: spawn ENOENT
       npm ERR!     at errnoException (child_process.js:1011:11)
       npm ERR!     at Process.ChildProcess._handle.onexit (child_process.js:802:34)
       npm ERR! If you need help, you may report this log at:
       npm ERR!     <http://github.com/isaacs/npm/issues>
       npm ERR! or email it to:
       npm ERR!     <npm-@googlegroups.com>
       
       npm ERR! System Linux 3.8.11-ec2
       npm ERR! command "node" "/tmp/build_fc3e8717fd7f68f9f6a9e93833388643/.heroku/node/bin/npm" "rebuild"
       npm ERR! cwd /tmp/build_fc3e8717fd7f68f9f6a9e93833388643
       npm ERR! node -v v0.10.35
       npm ERR! npm -v 1.1.71
       npm ERR! syscall spawn
       npm ERR! code ENOENT
       npm ERR! errno ENOENT
       npm ERR! 
       npm ERR! Additional logging details can be found in:
       npm ERR!     /tmp/build_fc3e8717fd7f68f9f6a9e93833388643/npm-debug.log
       npm ERR! not ok code 0

-----> Build failed

       WARNING: Avoid checking node_modules into source control
       https://www.npmjs.org/doc/misc/npm-faq.html#should-i-check-my-node_modules-folder-into-git-
       
       WARNING: This version of npm (1.1.71) has several known issues - consider upgrading to the latest release (2.1.18)
       https://devcenter.heroku.com/articles/nodejs-support#specifying-an-npm-version
       
       We're sorry this build is failing! If you can't find the issue in application code,
       please submit a ticket so we can help: https://help.heroku.com/
       You can also try reverting to our legacy Node.js buildpack:
       heroku config:set BUILDPACK_URL=https://github.com/heroku/heroku-buildpack-nodejs#v63
       
       Love,
       Heroku

 !     Push rejected, failed to compile Node.js app

My packager.json file 
{
  "name": "test",
  "description": "testPro api",
  "version": "0.0.1",
  "private": true,
  "main": "app.js",
  "dependencies": {
    "aws-sdk": "~2.0.0-rc9",
    "bitly": "~1.2.5",
    "connect-redis": "~1.4.6",
    "cookie-signature": "~1.0.3",
    "crypto": "0.0.3",
    "elasticsearch": "~1.5.5",
    "embedly": "~1.0.2",
    "express": ">= 3.4.7",
    "forky": ">= 0.0.2",
    "http": "0.0.0",
    "image-size": "^0.3.3",
    "mmm": "~0.2.2",
    "moment": "~2.5.1",
    "moment-timezone": "0.0.3",
    "nimble": "0.0.2",
    "node-uuid": "^1.4.1",
    "nodetime": "^0.8.15",
    "redis": "^0.12.1",
    "request": "~2.33.0",
    "sanitizer": "~0.1.1",
    "url": "~0.7.9",
    "validator": "~3.2.1"
  },
  "engines": {
    "node": "0.10.x",
    "npm": "1.1.x"
  },
  "scripts": {
    "test": "node_modules/.bin/mocha tests -R spec"
  },
  "devDependencies": {
    "assert": "^1.1.2",
    "chai": "^1.10.0",
    "mocha": ">= 1.17.1",
    "precommit-hook": "",
    "should": "^4.3.0",
    "sinon": "^1.12.1",
    "sinon-chai": "^2.6.0",
    "supertest": "^0.15.0"
  }
}
```

**Comment by KenanY** [comment]
```
WARNING: This version of npm (1.1.71) has several known issues - consider upgrading to the latest release (2.1.18)
https://devcenter.heroku.com/articles/nodejs-support#specifying-an-npm-version
```

Could you please update your `npm` first? Even Heroku recommends it:

> We recommend specifying a version greater than or equal to 2.1.x since that branch fixes many common `npm` issues.

**Comment by dibeesh** [comment]
@KenanY Thank you for your comment. Let me know how to update npm 1.1.x to higher version without updating other modules.

**Comment by KenanY** [comment]
@dibeesh Did you read the article that Heroku links to in the error message?: https://devcenter.heroku.com/articles/nodejs-support#specifying-an-npm-version

**Comment by dibeesh** [comment]
@KenanY Thank you so much, you are awesome, npm update fixed my issue.

**Comment by othiym23** [comment]
Closing as resolved.
