### ISSUE TITLE
Installing modules directly from the cache fails

### ISSUE THREAD

**Issue by kevinsawicki** [npm/npm#7140]
Installing a file using a `.tgz` path from the cache appears to fail in npm 2.x, this worked in 1.4.

Please close this out if this isn't supported anymore.
### Reproduction

```
> npm install rimraf
rimraf@2.2.8 node_modules/rimraf

> npm install ~/.npm/rimraf/2.2.8/package.tgz 
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/Users/kevin/github/npm-test/node_modules/.bin/npm" "install" "/Users/kevin/.npm/rimraf/2.2.8/package.tgz"
npm ERR! node v0.10.21
npm ERR! npm  v2.1.18

npm ERR! package metadata must include name
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kevin/github/npm-test/npm-debug.log
```
### Log  File

```
0 info it worked if it ends with ok
1 verbose cli [ 'node',
1 verbose cli   '/Users/kevin/github/npm-test/node_modules/.bin/npm',
1 verbose cli   'install',
1 verbose cli   '/Users/kevin/.npm/rimraf/2.2.8/package.tgz' ]
2 info using npm@2.1.18
3 info using node@v0.10.21
4 verbose node symlink /opt/boxen/nodenv/versions/v0.10/bin/node
5 warn package.json test@1.0.0 No description
6 warn package.json test@1.0.0 No repository field.
7 warn package.json test@1.0.0 No README data
8 silly cache add args [ '/Users/kevin/.npm/rimraf/2.2.8/package.tgz', null ]
9 verbose cache add spec /Users/kevin/.npm/rimraf/2.2.8/package.tgz
10 silly cache add parsed spec { raw: '/Users/kevin/.npm/rimraf/2.2.8/package.tgz',
10 silly cache add   scope: null,
10 silly cache add   name: null,
10 silly cache add   rawSpec: '/Users/kevin/.npm/rimraf/2.2.8/package.tgz',
10 silly cache add   spec: '/Users/kevin/.npm/rimraf/2.2.8/package.tgz',
10 silly cache add   type: 'local' }
11 silly addLocalTarball shasum (computed) 1bdfdedc567a40638a15deb9d1e7151055f3214f
12 verbose addLocalTarball adding from inside cache /Users/kevin/.npm/rimraf/2.2.8/package.tgz
13 verbose stack AssertionError: package metadata must include name
13 verbose stack     at getCacheRoot (/Users/kevin/github/npm-test/node_modules/npm/lib/cache/cached-package-root.js:10:3)
13 verbose stack     at addPlacedTarball_ (/Users/kevin/github/npm-test/node_modules/npm/lib/cache/add-local-tarball.js:64:26)
13 verbose stack     at /Users/kevin/github/npm-test/node_modules/npm/lib/cache/add-local-tarball.js:59:12
13 verbose stack     at /Users/kevin/github/npm-test/node_modules/npm/lib/cache/get-stat.js:19:12
13 verbose stack     at Object.oncomplete (evalmachine.<anonymous>:107:15)
14 verbose cwd /Users/kevin/github/npm-test
15 error Darwin 13.4.0
16 error argv "node" "/Users/kevin/github/npm-test/node_modules/.bin/npm" "install" "/Users/kevin/.npm/rimraf/2.2.8/package.tgz"
17 error node v0.10.21
18 error npm  v2.1.18
19 error package metadata must include name
20 error If you need help, you may report this error at:
20 error     <http://github.com/npm/npm/issues>
21 verbose exit [ 1, true ]
```
### package.json from inside package.tgz file

``` json
{
  "name": "rimraf",
  "version": "2.2.8",
  "main": "rimraf.js",
  "description": "A deep deletion module for node (like `rm -rf`)",
  "author": "Isaac Z. Schlueter <i@izs.me> (http://blog.izs.me/)",
  "license": {
    "type": "MIT",
    "url": "https://github.com/isaacs/rimraf/raw/master/LICENSE"
  },
  "repository": "git://github.com/isaacs/rimraf.git",
  "scripts": {
    "test": "cd test && bash run.sh"
  },
  "bin": "./bin.js"
}
```

**Comment by othiym23** [comment]
It doesn't appear to be supported anymore, but we didn't actually choose to stop supporting it. There are a bunch of changes we've (I've) made to how interacting with the cache works, and those assumptions don't hold when you're trying to install from a cached tarball. It's not _hard_ to fix (and it should be fixed -- the code is still there to support it), but it's also enough of an edge case that it may take a while to get to.

(The fix, put briefly, is to go ahead and load the tarball's package metadata from the cached `package.json` before continuing, and to skip trying to put the tarball into place and instead jump straight back to the install once that metadata is in hand.)
