### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by virologicbridge** [npm/npm#7152]
I'm unable to install anything with npm, but I've been using it for weeks. It is up to date, on a ubuntu 12.04 LTS box using vagrant. 
Here below is are my errors and log file, any help is really appreciated!

```
npm http GET https://registry.npmjs.org/learnyounode

npm ERR! Error: failed to fetch from registry: learnyounode
npm ERR!     at /usr/share/npm/lib/utils/npm-registry-client/get.js:139:12
npm ERR!     at cb (/usr/share/npm/lib/utils/npm-registry-client/request.js:31:9      )
npm ERR!     at Request._callback (/usr/share/npm/lib/utils/npm-registry-client/      request.js:136:18)
npm ERR!     at Request.callback (/usr/lib/nodejs/request/main.js:119:22)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/main.js:212:58)
npm ERR!     at Request.emit (events.js:88:20)
npm ERR!     at ClientRequest.<anonymous> (/usr/lib/nodejs/request/main.js:412:1      2)
npm ERR!     at ClientRequest.emit (events.js:67:17)
npm ERR!     at HTTPParser.onIncoming (http.js:1261:11)
npm ERR!     at HTTPParser.onHeadersComplete (http.js:102:31)
npm ERR! You may report this log at:
npm ERR!     <http://bugs.debian.org/npm>
npm ERR! or use
npm ERR!     reportbug --attach /home/vagrant/vagrant1/learnyounode/npm-debug.lo      g npm
npm ERR!
npm ERR! System Linux 3.2.0-23-generic-pae
npm ERR! command "node" "/usr/bin/npm" "install" "learnyounode"
npm ERR! cwd /home/vagrant/vagrant1/learnyounode
npm ERR! node -v v0.6.12
npm ERR! npm -v 1.1.4
npm ERR! message failed to fetch from registry: learnyounode
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/vagrant/vagrant1/learnyounode/npm-debug.log
npm not ok
```

```
info it worked if it ends with ok
verbose cli [ 'node', '/usr/bin/npm', 'install', 'learnyounode' ]
info using npm@1.1.4
info using node@v0.6.12
verbose config file /home/vagrant/.npmrc
verbose config file /usr/etc/npmrc
verbose config file /usr/share/npm/npmrc
verbose cache add [ 'learnyounode', null ]
silly cache add: name, spec, args [ undefined, 'learnyounode', [ 'learnyounode', null ] ]
verbose parsed url { pathname: 'learnyounode',
verbose parsed url   path: 'learnyounode',
verbose parsed url   href: 'learnyounode' }
verbose addNamed [ 'learnyounode', '' ]
verbose addNamed [ null, '' ]
silly name, range, hasData [ 'learnyounode', '', false ]
verbose raw, before any munging learnyounode
verbose url resolving [ 'https://registry.npmjs.org/', './learnyounode' ]
verbose url resolved https://registry.npmjs.org/learnyounode
http GET https://registry.npmjs.org/learnyounode
ERR! Error: failed to fetch from registry: learnyounode
ERR!     at /usr/share/npm/lib/utils/npm-registry-client/get.js:139:12
ERR!     at cb (/usr/share/npm/lib/utils/npm-registry-client/request.js:31:9)
ERR!     at Request._callback (/usr/share/npm/lib/utils/npm-registry-client/request.js:136:18)
ERR!     at Request.callback (/usr/lib/nodejs/request/main.js:119:22)
ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/main.js:212:58)
ERR!     at Request.emit (events.js:88:20)
ERR!     at ClientRequest.<anonymous> (/usr/lib/nodejs/request/main.js:412:12)
ERR!     at ClientRequest.emit (events.js:67:17)
ERR!     at HTTPParser.onIncoming (http.js:1261:11)
ERR!     at HTTPParser.onHeadersComplete (http.js:102:31)
ERR! You may report this log at:
ERR!     <http://bugs.debian.org/npm>
ERR! or use
ERR!     reportbug --attach /home/vagrant/vagrant1/learnyounode/npm-debug.log npm
ERR! 
ERR! System Linux 3.2.0-23-generic-pae
ERR! command "node" "/usr/bin/npm" "install" "learnyounode"
ERR! cwd /home/vagrant/vagrant1/learnyounode
ERR! node -v v0.6.12
ERR! npm -v 1.1.4
ERR! message failed to fetch from registry: learnyounode
verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
@virologicbridge Node.js v0.6 is several years old and no longer supported. You should definitely upgrade to the latest stable release from http://nodejs.org/

**Comment by virologicbridge** [comment]
Thanks Kenan, Good Point. I think I need to run a shell script on boot to keep everything up to date since these are VMs.  Gonna try that soon.

**Comment by virologicbridge** [comment]
sudo apt-get install nodejs - tells me its already the newest version, it def see that it's not?! rrrr

**Comment by othiym23** [comment]
@virologicbridge Ubuntu and Debian have a completely different attitude towards packaging and distribution (especially when it comes to versioning) than Node's user community and developers. You should probably use [NodeSource's PPA](https://github.com/nodesource/distributions) if you want the latest stable versions of Node (you'll still need to upgrade npm after installing that, but that's a whole other issue beyond the scope of this one).

**Comment by virologicbridge** [comment]
I hate trusting unknown, third-party, repositories, but this did make it work. Thanks folks, and a huge thank you goes out to the rtCamp team for this article. https://rtcamp.com/tutorials/nodejs/node-js-npm-install-ubuntu/
