### ISSUE TITLE
Error attempting make install on Ubuntu

### ISSUE THREAD

**Issue by plane007** [npm/npm#7154]
Install fails!!!

Comment on Github suggests: You need to be on Node >= 0.10

Error:
```
/var/npm/node_modules/osenv/osenv.js:49
  return os.tmpDir()
            ^
TypeError: Object #<Object> has no method 'tmpDir'
    at /var/npm/node_modules/osenv/osenv.js:49:13
    at Object.tmpdir (/var/npm/node_modules/osenv/osenv.js:14:15)
    at Object.<anonymous> (/var/npm/lib/config/defaults.js:97:18)
    at Module._compile (module.js:446:26)
    at Object..js (module.js:464:10)
    at Module.load (module.js:353:31)
    at Function._load (module.js:311:12)
    at Module.require (module.js:359:17)
    at require (module.js:375:17)
    at Object.<anonymous> (/var/npm/lib/config/core.js:4:18)
make[1]: *** [node_modules/.bin/marked-man] Error 1
make[1]: Leaving directory `/var/npm'
make: *** [man/man3/npm-version.3] Error 2
```

**Comment by othiym23** [comment]
`os.tmpDir` was added in [Node 0.7.11](https://github.com/joyent/node/commit/a11bf99ce0dae4d8f4de8a9c0c32159c1a9ecfbf), which means that if you're seeing this error, you're running a version of Node too old to support npm. Please [upgrade](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-node) and try again!
