### ISSUE TITLE
Error on install app

### ISSUE THREAD

**Issue by DaEsdert** [npm/npm#7155]
i get this error when installing something with npm
```
ERR! Error: SSL Error: SELF_SIGNED_CERT_IN_CHAIN
ERR!     at ClientRequest.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/main.js:483:26)
ERR!     at ClientRequest.g (events.js:156:14)
ERR!     at ClientRequest.emit (events.js:67:17)
ERR!     at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1256:7)
ERR!     at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:91:29)
ERR!     at CleartextStream.socketOnData [as ondata] (http.js:1288:20)
ERR!     at CleartextStream._push (tls.js:375:27)
ERR!     at SecurePair.cycle (tls.js:734:20)
ERR!     at EncryptedStream.write (tls.js:130:13)
ERR!     at Socket.ondata (stream.js:38:26)
ERR! You may report this log at:
ERR!     <http://github.com/isaacs/npm/issues>
ERR! or email it to:
ERR!     <npm-@googlegroups.com>
ERR! 
ERR! System Linux 3.2.0-4-686-pae
ERR! command "node" "/usr/local/bin/npm" "install"
ERR! cwd /root/KiwiIRC
ERR! node -v v0.6.18
ERR! npm -v 1.1.21
ERR! message SSL Error: SELF_SIGNED_CERT_IN_CHAIN
```

**Comment by KenanY** [comment]
@DaEsdert Node.js v0.6 is many years old and no longer supported by `npm`. You should update to the latest stable release from http://nodejs.org/ in order to catch up on several years of bug fixes, improvements, and security patches.

**Comment by DaEsdert** [comment]
installing the new version lol sorry for abusing.

**Comment by othiym23** [comment]
Closing as resolved.
