### ISSUE TITLE
Shrinkwrap Err: Missing normalize-package-data in npm 1.3.26

### ISSUE THREAD

**Issue by kevinohara80** [npm/npm#7167]
Currently running: 

* node 0.10.33
* npm 2.2.0

When trying to run `npm shrinkwrap --dev` I get the following error.

```
npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/Users/kevinohara/.nvm/v0.10.33/bin/npm" "shrinkwrap" "--dev"
npm ERR! node v0.10.33
npm ERR! npm  v2.2.0

npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! missing: normalize-package-data@*, required by npm@1.3.26
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kevinohara/dev/l11/contest-builder/npm-debug.log
```

I'm have no idea what is causing this error. I'm especially confused by the the message referencing version `1.3.26` when I am on `2.2.0`.

And the npm debug log:

```
0 info it worked if it ends with ok
1 verbose cli [ 'node',
1 verbose cli   '/Users/kevinohara/.nvm/v0.10.33/bin/npm',
1 verbose cli   'shrinkwrap',
1 verbose cli   '--dev' ]
2 info using npm@2.2.0
3 info using node@v0.10.33
4 verbose stack Error: Problems were encountered
4 verbose stack Please correct and try again.
4 verbose stack missing: normalize-package-data@*, required by npm@1.3.26
4 verbose stack     at shrinkwrap_ (/Users/kevinohara/.nvm/v0.10.33/lib/node_modules/npm/lib/shrinkwrap.js:31:15)
4 verbose stack     at /Users/kevinohara/.nvm/v0.10.33/lib/node_modules/npm/lib/shrinkwrap.js:25:5
4 verbose stack     at /Users/kevinohara/.nvm/v0.10.33/lib/node_modules/npm/lib/ls.js:46:30
4 verbose stack     at /Users/kevinohara/.nvm/v0.10.33/lib/node_modules/npm/node_modules/read-installed/read-installed.js:138:5
4 verbose stack     at /Users/kevinohara/.nvm/v0.10.33/lib/node_modules/npm/node_modules/read-installed/read-installed.js:251:14
4 verbose stack     at cb (/Users/kevinohara/.nvm/v0.10.33/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
4 verbose stack     at /Users/kevinohara/.nvm/v0.10.33/lib/node_modules/npm/node_modules/read-installed/read-installed.js:251:14
4 verbose stack     at cb (/Users/kevinohara/.nvm/v0.10.33/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
4 verbose stack     at /Users/kevinohara/.nvm/v0.10.33/lib/node_modules/npm/node_modules/read-installed/read-installed.js:251:14
4 verbose stack     at cb (/Users/kevinohara/.nvm/v0.10.33/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
5 verbose cwd /Users/kevinohara/dev/l11/contest-builder
6 error Darwin 14.0.0
7 error argv "node" "/Users/kevinohara/.nvm/v0.10.33/bin/npm" "shrinkwrap" "--dev"
8 error node v0.10.33
9 error npm  v2.2.0
10 error Problems were encountered
10 error Please correct and try again.
10 error missing: normalize-package-data@*, required by npm@1.3.26
11 error If you need help, you may report this error at:
11 error     <http://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
```

**Comment by othiym23** [comment]
Is npm a `devDependency` (or `dependency`) in the application you're trying to shrinkwrap? What does `npm ls` return in `/Users/kevinohara/dev/l11/contest-builder`? What about `npm ls npm`?

**Comment by kevinohara80** [comment]
Oh man, it's a stupid grunt plugin. Thanks for the reply. This is on us to fix.
