### ISSUE TITLE
npm install npm failing.

### ISSUE THREAD

**Issue by VynceMontgomery** [npm/npm#7173]
I'm trying to get up to the most recent npm, mostly because i'm still on a version so old i have the CA problem -- but, trying the solution as per http://blog.npmjs.org/post/78165272245/more-help-with-self-signed-cert-in-chain-and-npm I get this result: 

(there's nothing that looks useful in the mentioned debug log)

. 
Vynce
. 

```shell
ticket:~ vynce$ npm install npm -g --ca=null
npm http GET https://registry.npmjs.org/npm
npm http 304 https://registry.npmjs.org/npm
npm http GET https://registry.npmjs.org/npm/-/npm-2.2.0.tgz
npm http 200 https://registry.npmjs.org/npm/-/npm-2.2.0.tgz

npm ERR! SyntaxError: Unexpected end of input
npm ERR!     at Object.parse (native)
npm ERR!     at Packer.readRules (/usr/local/lib/node_modules/npm/node_modules/fstream-npm/fstream-npm.js:174:31)
npm ERR!     at Packer.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/fstream-npm/node_modules/fstream-ignore/ignore.js:132:22)
npm ERR!     at [object Object].<anonymous> (fs.js:123:5)
npm ERR!     at [object Object].emit (events.js:64:17)
npm ERR!     at fs.js:1181:12
npm ERR!     at Object.oncomplete (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:94:5)
npm ERR! You may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>
npm ERR! 
npm ERR! System Darwin 11.4.2
npm ERR! command "node" "/usr/local/bin/npm" "install" "npm" "-g" "--ca=null"
npm ERR! cwd /Users/vynce
npm ERR! node -v v0.6.15
npm ERR! npm -v 1.1.16
npm ERR! type unexpected_eos
npm ERR! arguments []
npm ERR! message Unexpected end of input
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/vynce/npm-debug.log
npm not ok
ticket:~ vynce$ 
```

**Comment by KenanY** [comment]
Node.js v0.6 is __several years old__ and no longer supported by the `npm` team. You would have a much easier time upgrading `npm` by simply updating to the latest stable release of Node.js from http://nodejs.org/

**Comment by VynceMontgomery** [comment]
alright, cool, thanks. 
.
