### ISSUE TITLE
I do not know what went wrong here (INSTALL)

### ISSUE THREAD

**Issue by csturtevant** [npm/npm#7179]
This is on a reasonably new mac.

I will take any help possible, I am sorry if I am unsure what is going on. I was just trying to use ruby with homebrew using a tutorial, however this is the message I received instead of the right one.

```
User-MacBook-Pro:~ user$ npm version
npm ERR! version Bad package.json data undefined
npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "version"
npm ERR! node v0.10.35
npm ERR! npm  v2.1.18

npm ERR! Unexpected token u
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/user/npm-debug.log
```
**Below is the contents of the npm-debug.log**

**Thank you very much for your time and help.**

```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'version' ]
2 info using npm@2.1.18
3 info using node@v0.10.35
4 verbose node symlink /usr/local/bin/node
5 verbose config Skipping project config: /Users/chrissturtevant0/.npmrc. (matches userconfig)
6 error version Bad package.json data undefined
7 verbose type unexpected_token
8 verbose stack SyntaxError: Unexpected token u
8 verbose stack     at Object.parse (native)
8 verbose stack     at /usr/local/lib/node_modules/npm/lib/version.js:36:19
8 verbose stack     at evalmachine.<anonymous>:208:20
8 verbose stack     at OpenReq.Req.done (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:141:5)
8 verbose stack     at OpenReq.done (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:61:22)
8 verbose stack     at Object.oncomplete (evalmachine.<anonymous>:108:15)
9 verbose cwd /Users/chrissturtevant0
10 error Darwin 14.0.0
11 error argv "node" "/usr/local/bin/npm" "version"
12 error node v0.10.35
13 error npm  v2.1.18
14 error Unexpected token u
15 error If you need help, you may report this error at:
15 error     <http://github.com/npm/npm/issues>
16 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
This was fixed in `npm@2.2.0`. #7056

**Comment by smikes** [comment]
As KenanY says, this was a bug in `npm@2.1.18`, fixed in later versions.  `npm` is trying to read your `package.json` file and failing.

To update npm, run `sudo npm -g install npm@latest`

**Comment by smikes** [comment]
Is this still a problem for you?

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by csturtevant** [comment]
This is no longer a problem for me thanks to your solution. Thank you!

**Comment by othiym23** [comment]
Closing as resolved.
