### ISSUE TITLE
LazoJs install

### ISSUE THREAD

**Issue by thebrandonhoward** [npm/npm#7187]
```
C:\Program Files\nodejs>npm install -g --production lazo
npm WARN `git config --get remote.origin.url` returned wrong result (git://github.com/requirejs/text.git)
npm WARN `git config --get remote.origin.url` returned wrong result (git://github.com/amdjs/backbone.git)
npm WARN `git config --get remote.origin.url` returned wrong result (git://github.com/amdjs/underscore.git)
npm WARN `git config --get remote.origin.url` returned wrong result (git://github.com/jstrimpel/jquery-cookie.git)
npm WARN `git config --get remote.origin.url` returned wrong result (git://github.com/jstrimpel/requirejs-plugins.git)
npm ERR! git clone git://github.com/amdjs/backbone.git Cloning into bare repository 'C:\Documents and Settings\behowar\Application Data\npm-cache\_git-remotes\git-github-com-amdjs-backbone-git-586d37a9'...
npm ERR! git clone git://github.com/amdjs/backbone.git fatal: Unable to look up github.com (port 9418) (No such host is known. )
npm ERR! git clone git://github.com/amdjs/underscore.git Cloning into bare repository 'C:\Documents and Settings\behowar\Application Data\npm-cache\_git-remotes\git-github-com-amdjs-underscore-git-e36fc557'...
npm ERR! git clone git://github.com/amdjs/underscore.git fatal: Unable to look up github.com (port 9418) (No such host is known. )
npm ERR! git clone git://github.com/requirejs/text.git Cloning into bare repository 'C:\Documents and Settings\behowar\Application Data\npm-cache\_git-remotes\git-github-com-requirejs-text-git-a4388600'...
npm ERR! git clone git://github.com/requirejs/text.git fatal: Unable to look up github.com (port 9418) (No such host is known. )
npm ERR! git clone git://github.com/jstrimpel/requirejs-plugins.git Cloning into bare repository 'C:\Documents and Settings\behowar\Application Data\npm-cache\_git-remotes\git-github-com-jstrimpel-requirejs-plugins-git-173ab38d'...
npm ERR! git clone git://github.com/jstrimpel/requirejs-plugins.git fatal: Unable to look up github.com (port 9418) (No such host is known. )
npm ERR! git clone git://github.com/jstrimpel/jquery-cookie.git Cloning into bare repository 'C:\Documents and Settings\behowar\Application Data\npm-cache\_git-remotes\git-github-com-jstrimpel-jquery-cookie-git-7f91dafe'...
npm ERR! git clone git://github.com/jstrimpel/jquery-cookie.git fatal: Unable to look up github.com (port 9418) (No such host is known. )
npm ERR! Error: Command failed: Cloning into bare repository 'C:\Documents and Settings\behowar\Application Data\npm-cache\_git-remotes\git-github-com-amdjs-backbone-git-586d37a9'...
npm ERR! fatal: Unable to look up github.com (port 9418) (No such host is known. )
npm ERR!
npm ERR!     at ChildProcess.exithandler (child_process.js:648:15)
npm ERR!     at ChildProcess.emit (events.js:98:17)
npm ERR!     at maybeClose (child_process.js:756:16)
npm ERR!     at Process.ChildProcess._handle.onexit (child_process.js:823:5)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 5.1.2600
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "--production" "lazo"
npm ERR! cwd C:\Program Files\nodejs
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code 128
npm ERR! not ok code 0

C:\Program Files\nodejs>
```

**Comment by leukhin** [comment]
I think you have some issues with your ISP. Something wrong with resolving github.com. But how did you get here? Or this is remote host?

**Comment by thebrandonhoward** [comment]
I sent this over to the LazoJs group, so they may be able to pinpoint it.
I am trying to install LazoJs using npm. I got an initial error, then i updated my settings for proxy.
That got me a little furthur, but now I am here.....scanning log info now.

**Comment by smikes** [comment]
Is this still a problem for you?

Could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since VERSION. Can you try updating your npm installation?

To update npm, run `npm -g install npm@latest`

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

For some Linux distributions (Debian/Ubuntu and RedHat/CentOS), the latest node version provided by the distribution may lag behind the stable version. [Here are instructions from NodeSource](https://github.com/nodesource/distributions) on getting the latest node.

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as abandoned.
