### ISSUE TITLE
npm not working

### ISSUE THREAD

**Issue by djsharma** [npm/npm#7225]
Ubuntu 14.04, npm version 1.3.10
Iam trying to install mongoose and facing such errors. Machine is behind proxy firewall. I serched for it and followed many solutions but still its not working. I did proxy set in .npmrc file also.

.npmrc file 

ca = null
strict-ssl = false

 Error while "sudo npm install -g mongoose"  is as follows
```
npm http GET https://registry.npmjs.org/mongoose
npm http 401 https://registry.npmjs.org/mongoose
npm ERR! registry error parsing json
npm ERR! SyntaxError: Unexpected token <
npm ERR! <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
npm ERR! "http://www.w3.org/TR/html4/loose.dtd">
npm ERR! <html>
npm ERR! <head>
npm ERR! <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
npm ERR! <title>Notification: WWW Authorization Required</title>
npm ERR! <style type="text/css">
npm ERR! body {
npm ERR!   font-family: Arial, Helvetica, sans-serif;
npm ERR!   font-size: 14px;
npm ERR!   color:#333333;
npm ERR!   background-color: #ffffff;
npm ERR! }
npm ERR! h1 {
npm ERR!   font-size: 18px;
npm ERR!   font-weight: bold;
npm ERR!   text-decoration: none;
npm ERR!   padding-top: 0px;
npm ERR!   color: #2970A6;
npm ERR! }
npm ERR! a:link {
npm ERR!     color: #2970A6;
npm ERR!   text-decoration: none;
npm ERR! }
npm ERR! a:hover {
npm ERR!     color: #2970A6;
npm ERR!   text-decoration: underline;
npm ERR! }
npm ERR! p.buttonlink {
npm ERR!   margin-bottom: 24px;
npm ERR! }
npm ERR! .copyright {
npm ERR!   font-size: 12px;
npm ERR!   color: #666666;
npm ERR!   margin: 5px 5px 0px 30px;
npm ERR! 
npm ERR! }
npm ERR! .details {
npm ERR!   font-size: 14px;
npm ERR!   color: #969696;
npm ERR!   border: none;
npm ERR!   padding: 20px 20px 20px 20px;
npm ERR!   margin: 0px 10px 10px 35px;
npm ERR! }
npm ERR! 
npm ERR! .shadow {
npm ERR!   border: 3px solid #9f9f9f;
npm ERR!   padding: 10px 25px 10px 25px;
npm ERR!   margin: 10px 35px 0px 30px;
npm ERR!   background-color: #ffffff;
npm ERR!   width: 600px;
npm ERR! 
npm ERR!   -moz-box-shadow: 3px 3px 3px #cccccc;
npm ERR!   -webkit-box-shadow: 3px 3px 3px #cccccc;
npm ERR!   box-shadow: 3px 3px 3px #cccccc;
npm ERR!   /* For IE 8 */
npm ERR!   -ms-filter: "progid:DXImageTransform.Microsoft.Shadow(Strength=5, Direction=135, Color='cccccc')";
npm ERR!   /* For IE 5.5 - 7 */
npm ERR!   filter: progid:DXImageTransform.Microsoft.Shadow(Strength=5, Direction=135, Color='cccccc');
npm ERR! }
npm ERR! .logo {
npm ERR!   border: none;
npm ERR!   margin: 5px 5px 0px 30px;
npm ERR! }
npm ERR! </style>
npm ERR! </head>
npm ERR! 
npm ERR! <body>
npm ERR! <div class="logo"></div><p>&nbsp;</p>
npm ERR! <div class="shadow">
npm ERR! 
npm ERR! <h1>This Page Cannot Be Displayed</h1>
npm ERR! 
npm ERR! 
npm ERR! <p>
npm ERR! Authentication is required to access the requested web site (&nbsp;ironport1.iitk.ac.in&nbsp;).
npm ERR! A valid user ID and password must be entered when prompted.
npm ERR! </p>
npm ERR! 
npm ERR! 
npm ERR! 
npm ERR! <p>
npm ERR! If you have questions, please contact
npm ERR! your corporate network administrator 
npm ERR! and provide the codes shown below.
npm ERR! </p>
npm ERR! 
npm ERR! </div>
npm ERR! 
npm ERR! <div class="details"><p>
npm ERR! Date: Tue, 27 Jan 2015 20:41:26 IST<br />
npm ERR! Username: <br />
npm ERR! Source IP: 172.27.22.13<br />
npm ERR! URL: GET https://ironport1.iitk.ac.in/B0001D0000N0000F0000S0000R0004/https://registry.npmjs.org/mongoose<br />
npm ERR! Category: <br />
npm ERR! Reason: UNKNOWN<br />
npm ERR! Notification: WWW_AUTH_REQUIRED
npm ERR! </p></div>
npm ERR! </body>
npm ERR! </html>
npm ERR! 
npm ERR!     at Object.parse (native)
npm ERR!     at RegClient.<anonymous> (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:238:23)
npm ERR!     at Request.self.callback (/usr/lib/nodejs/request/index.js:148:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/index.js:896:14)
npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/lib/nodejs/request/index.js:847:12)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-32-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "mongoose"
npm ERR! cwd /home/djsharma
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! type unexpected_token
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/djsharma/npm-debug.log
npm ERR! not ok code 0
```

**Comment by djsharma** [comment]
earlier the error was SELF SIGN CERT. while solving that i struck on this error

**Comment by djsharma** [comment]
just changed .npmrc file 

registry from "http://registry.npms.org/"
to 
"http://registry.npmjs.org/"
and it worked.

**Comment by KenanY** [comment]
```
npm ERR! URL: GET https://ironport1.iitk.ac.in/B0001D0000N0000F0000S0000R0004/https://registry.npmjs.org/mongoose
```

@djsharma It looks like you are behind a proxy, which is trying to tell you that you need to authorize yourself with said proxy:

```
Authentication is required to access the requested web site ( ironport1.iitk.ac.in ).
A valid user ID and password must be entered when prompted.

If you have questions, please contact
your corporate network administrator
```

As such, this isn't an `npm` issue. It would be better to complete the authentication rather than disable HTTPS (for security purposes).

Also, somewhat off-topic, is your one-year-old version of `npm`. You should [update](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-nix-osx-linux-etc) for literally hundreds of bug fixes :)

**Comment by smikes** [comment]
+1 for upgrading to latest `npm`, since you will likely encounter race conditions during `npm install` in `npm@1.3` that have been fixed in latest.  If you follow the guide that @KenanY pointed out, you will also get an updated version of `node` with additional bugfixes.

**Comment by smikes** [comment]
Is this still a problem for you?

If so, could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as resolved / abandoned.
