### ISSUE TITLE
Error installing mean on OSX 10.10.1

### ISSUE THREAD

**Issue by ulikunkel** [npm/npm#7227]
I ran the following command:
```
sudo npm install -g mean-cli
```
and got the following error:
```
npm ERR! Error: UNABLE_TO_VERIFY_LEAF_SIGNATURE
npm ERR!     at SecurePair.<anonymous> (tls.js:1381:32)
npm ERR!     at SecurePair.emit (events.js:92:17)
npm ERR!     at SecurePair.maybeInitFinished (tls.js:980:10)
npm ERR!     at CleartextStream.read [as _read] (tls.js:472:13)
npm ERR!     at CleartextStream.Readable.read (_stream_readable.js:341:10)
npm ERR!     at EncryptedStream.write [as _write] (tls.js:369:25)
npm ERR!     at doWrite (_stream_writable.js:226:10)
npm ERR!     at writeOrBuffer (_stream_writable.js:216:5)
npm ERR!     at EncryptedStream.Writable.write (_stream_writable.js:183:11)
npm ERR!     at write (_stream_readable.js:602:24)
npm ERR!     at flow (_stream_readable.js:611:7)
npm ERR!     at Socket.pipeOnReadable (_stream_readable.js:643:5)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 14.0.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "-g" "mean-cli"
npm ERR! cwd /Users/jkendall1
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
```

**Comment by smikes** [comment]
Hi!  It looks like you have a quite old version of `npm`.  Can you try updating `npm`:

```
npm install -g npm@latest
```

You may need to run that with `sudo`.  That should get you the latest version of `npm`.  If it fails, you may be seeing a bug in `node@0.10.35` -- see #7226 for a possible workaround:

```
NODE_TLS_REJECT_UNAUTHORIZED=0 npm install -g npm@latest --strict-ssl false
```

**Comment by smikes** [comment]
Is this still a problem for you?

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as abandoned.
