### ISSUE TITLE
Cannot publish postcss-custom-media 2.0.0

### ISSUE THREAD

**Issue by MoOx** [npm/npm#7235]
So weird. npm is telling me that 2.0.0 has been pushed already.
But only 1.3.0 is out: https://www.npmjs.com/package/postcss-custom-media

```
❯❯ npm publish
npm ERR! publish Failed PUT 403
npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "publish"
npm ERR! node v0.10.35
npm ERR! npm  v2.1.18
npm ERR! code E403

npm ERR! forbidden Attempting to modify version 2.0.0,
npm ERR! which was previously published on 2014-08-12T12:53:35.932Z.
npm ERR! This is forbidden, to maintain package integrity.
npm ERR! Please update the version number and try again.: postcss-custom-media
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/MoOx/Sync/Development/postcss/custom-media/npm-debug.lo
```

```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'publish' ]
2 info using npm@2.1.18
3 info using node@v0.10.35
4 verbose node symlink /usr/local/bin/node
5 verbose publish [ '.' ]
6 silly cache add args [ '.', null ]
7 verbose cache add spec .
8 silly cache add parsed spec { raw: '.',
8 silly cache add   scope: null,
8 silly cache add   name: null,
8 silly cache add   rawSpec: '.',
8 silly cache add   spec: '/Users/MoOx/Sync/Development/postcss/custom-media',
8 silly cache add   type: 'directory' }
9 verbose addLocalDirectory /Users/MoOx/.npm/postcss-custom-media/2.0.0/package.tgz not in flight; packing
10 verbose tar pack [ '/Users/MoOx/.npm/postcss-custom-media/2.0.0/package.tgz',
10 verbose tar pack   '/Users/MoOx/Sync/Development/postcss/custom-media' ]
11 verbose tarball /Users/MoOx/.npm/postcss-custom-media/2.0.0/package.tgz
12 verbose folder /Users/MoOx/Sync/Development/postcss/custom-media
13 info prepublish postcss-custom-media@2.0.0
14 verbose addLocalTarball adding from inside cache /Users/MoOx/.npm/postcss-custom-media/2.0.0/package.tgz
15 silly cache afterAdd postcss-custom-media@2.0.0
16 verbose afterAdd /Users/MoOx/.npm/postcss-custom-media/2.0.0/package/package.json not in flight; writing
17 verbose afterAdd /Users/MoOx/.npm/postcss-custom-media/2.0.0/package/package.json written
18 silly publish { name: 'postcss-custom-media',
18 silly publish   version: '2.0.0',
18 silly publish   description: ' PostCSS plugin to transform W3C CSS Custom Media Queries to more compatible CSS',
18 silly publish   keywords:
18 silly publish    [ 'css',
18 silly publish      'postcss',
18 silly publish      'postcss-plugins',
18 silly publish      'media queries',
18 silly publish      'custom-media' ],
18 silly publish   author: { name: 'Maxime Thirouin' },
18 silly publish   license: 'MIT',
18 silly publish   repository:
18 silly publish    { type: 'git',
18 silly publish      url: 'https://github.com/postcss/postcss-custom-media.git' },
18 silly publish   files: [ 'CHANGELOG.md', 'LICENSE', 'index.js' ],
18 silly publish   dependencies: { 'postcss-message-helpers': '^2.0.0' },
18 silly publish   devDependencies:
18 silly publish    { jscs: '^1.6.2',
18 silly publish      jshint: '^2.5.6',
18 silly publish      postcss: '^4.0.2',
18 silly publish      tape: '^3.0.0' },
18 silly publish   scripts:
18 silly publish    { lint: 'jscs *.js **/*.js && jshint . --exclude-path .gitignore',
18 silly publish      test: 'npm run lint && tape test' },
18 silly publish   readme: '# postcss-custom-media [![Build Status](https://travis-ci.org/postcss/postcss-custom-media.png)](https://travis-ci.org/postcss/postcss-custom-media)\n\n> [PostCSS](https://github.com/postcss/postcss) plugin to transform [W3C CSS Custom Media Queries](http://dev.w3.org/csswg/mediaqueries/#custom-mq) syntax to more compatible CSS.\n\n## Installation\n\n    $ npm install postcss-custom-media\n\n## Usage\n\n```js\n// dependencies\nvar postcss = require("postcss")\nvar customMedia = require("postcss-custom-media")\n\n// css to be processed\nvar css = fs.readFileSync("input.css", "utf8")\n\n// process css using postcss-custom-media\nvar out = postcss()\n  .use(customMedia())\n  .process(css)\n  .css\n```\n\nUsing this `input.css`:\n\n```css\n@custom-media --small-viewport (max-width: 30em);\n\n@media (--small-viewport) {\n  /* styles for small viewport */\n}\n```\n\nyou will get:\n\n```css\n@media (max-width: 30em) {\n  /* styles for small viewport */\n}\n```\n\nCheckout [tests](test) for more examples.\n\n### Options\n\n#### `extensions` (default: `{}`)\n\nAllows you to pass an object to define the `<media-query-list>` for each `<extension-name>`. These definitions will override any that exist in the CSS.\n\n---\n\n## Contributing\n\nWork on a branch, install dev-dependencies, respect coding style & run tests before submitting a bug fix or a feature.\n\n    $ git clone https://github.com/postcss/postcss-custom-media.git\n    $ git checkout -b patch-1\n    $ npm install\n    $ npm test\n\n## [Changelog](CHANGELOG.md)\n\n## [License](LICENSE)\n',
18 silly publish   readmeFilename: 'README.md',
18 silly publish   gitHead: '01c277848c48a60bf1f96ca117ce063d2f849ef7',
18 silly publish   bugs: { url: 'https://github.com/postcss/postcss-custom-media/issues' },
18 silly publish   homepage: 'https://github.com/postcss/postcss-custom-media',
18 silly publish   _id: 'postcss-custom-media@2.0.0',
18 silly publish   _shasum: '907ac2c262cb19f039bba1234254c1809d5cefa6',
18 silly publish   _from: '.' }
19 silly mapToRegistry name postcss-custom-media
20 silly mapToRegistry using default registry
21 silly mapToRegistry registry https://registry.npmjs.org/
22 silly mapToRegistry uri https://registry.npmjs.org/postcss-custom-media
23 verbose publish registryBase https://registry.npmjs.org/
24 silly publish uploading /Users/MoOx/.npm/postcss-custom-media/2.0.0/package.tgz
25 verbose request uri https://registry.npmjs.org/postcss-custom-media
26 verbose request sending authorization for write operation
27 info attempt registry request try #1 at 21:32:54
28 verbose request id b854e21ed5317a26
29 http request PUT https://registry.npmjs.org/postcss-custom-media
30 http 403 https://registry.npmjs.org/postcss-custom-media
31 verbose headers { date: 'Wed, 28 Jan 2015 20:32:55 GMT',
31 verbose headers   server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
31 verbose headers   'content-type': 'application/json',
31 verbose headers   'cache-control': 'max-age=60',
31 verbose headers   'content-length': '230',
31 verbose headers   'accept-ranges': 'bytes',
31 verbose headers   via: '1.1 varnish',
31 verbose headers   'x-served-by': 'cache-ams4131-AMS',
31 verbose headers   'x-cache': 'MISS',
31 verbose headers   'x-cache-hits': '0',
31 verbose headers   'x-timer': 'S1422477174.648848,VS0,VE815',
31 verbose headers   'keep-alive': 'timeout=10, max=50',
31 verbose headers   connection: 'Keep-Alive' }
32 verbose request invalidating /Users/MoOx/.npm/registry.npmjs.org/postcss-custom-media on PUT
33 error publish Failed PUT 403
34 verbose stack Error: forbidden Attempting to modify version 2.0.0,
34 verbose stack which was previously published on 2014-08-12T12:53:35.932Z.
34 verbose stack This is forbidden, to maintain package integrity.
34 verbose stack Please update the version number and try again.: postcss-custom-media
34 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:244:14)
34 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
34 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:373:22)
34 verbose stack     at Request.emit (events.js:98:17)
34 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1318:14)
34 verbose stack     at Request.emit (events.js:117:20)
34 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1266:12)
34 verbose stack     at IncomingMessage.emit (events.js:117:20)
34 verbose stack     at _stream_readable.js:944:16
34 verbose stack     at process._tickCallback (node.js:442:13)
35 verbose statusCode 403
36 verbose pkgid postcss-custom-media
37 verbose cwd /Users/MoOx/Sync/Development/postcss/custom-media
38 error Darwin 14.0.0
39 error argv "node" "/usr/local/bin/npm" "publish"
40 error node v0.10.35
41 error npm  v2.1.18
42 error code E403
43 error forbidden Attempting to modify version 2.0.0,
43 error which was previously published on 2014-08-12T12:53:35.932Z.
43 error This is forbidden, to maintain package integrity.
43 error Please update the version number and try again.: postcss-custom-media
44 error If you need help, you may report this error at:
44 error     <http://github.com/npm/npm/issues>
45 verbose exit [ 1, true ]
```

**Comment by smikes** [comment]
There is a `2.0.0` version recorded in the npm registry: 

```
$ npm view postcss-custom-media | grep 2.0.0
'2.0.0': '2014-08-12T12:53:35.932Z',
```

You can download it with 
```
wget 'http://registry.npmjs.org/postcss-custom-media/-/postcss-custom-media-2.0.0.tgz'
```

Since you can't republish a different version of the package at a previously published version, I think you will have to jump to 3.0.0.  Sorry about that.

**Comment by MoOx** [comment]
Ok so I probably make some shit when I created the package. Will go for 3.0. Thanks.
