### ISSUE TITLE
unable to publish my code using npm publish command

### ISSUE THREAD

**Issue by MrVinitBansal** [npm/npm#7254]
```
E:\NodeProjects\nodejs\math_example>npm publish
npm ERR! publish Failed PUT 403
npm ERR! Error: forbidden user: vinitbansal not authorized to modify math_exampl
e
npm ERR! Deleted: description
npm ERR! Changed: dist-tags.latest "0.0.15" -> "1.0.0"
npm ERR! Added: versions.1.0.0
npm ERR! Changed: readme "math_example package\u000d\u000a====================\u
000d\u000a\u000d\u000aThe following functions are available in the math_example
package.  \u000d\u000a- **addition** Adds two numbers and returns the result.  \
u000d\u000a- **subtraction** Subtracts the second number from the first and retu
rns the result.  \u000d\u000a- **multiplication** Multiplies two numbers and ret
urns the result.  \u000d\u000a- **division** Divides the first number by the sec
ond number and returns the result.  \u000d\u000a- **fibonacci** Applies the fibo
nacci sequence count times and returnts the result.  \u000d\u000a" -> "ERROR: No
 README data found!"
npm ERR! Changed: time.modified "2014-07-29T18:38:04.951Z" -> "2015-02-01T15:10:
22.008Z"
npm ERR! Added: time.1.0.0
npm ERR! Changed: author.name "Glenn Johnson" -> "\"Glenn Johnson\""
npm ERR! Deleted: keywords
npm ERR! Changed: license "BSD" -> "\"BSD\""
npm ERR! Added: _attachments: math_example
npm ERR!     at RegClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\
node_modules\npm-registry-client\lib\request.js:308:14)
npm ERR!     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node
_modules\npm-registry-client\lib\request.js:246:65)
npm ERR!     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\
node_modules\request\request.js:236:22)
npm ERR!     at Request.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\no
de_modules\request\request.js:1142:14)
npm ERR!     at Request.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_module
s\npm\node_modules\request\request.js:1096:12)
npm ERR!     at IncomingMessage.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:944:16
npm ERR!     at process._tickCallback (node.js:442:13)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "publish"
npm ERR! cwd E:\NodeProjects\nodejs\math_example
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     E:\NodeProjects\nodejs\math_example\npm-debug.log
npm ERR! not ok code 0
```

**Comment by KenanY** [comment]
```
npm ERR! Error: forbidden user: vinitbansal not authorized to modify math_example
```

@MrVinitBansal There is already a module called `math_example`, so unless you are given permission by the owner of that module, you cannot publish a new version of it.

**Comment by MrVinitBansal** [comment]
So, if I change my application name from math_example to some other name, will it work then?

**Comment by KenanY** [comment]
@MrVinitBansal I believe it should; you just have to pick a name that has not been used on the registry yet. If you still get an error, feel free to post it here.

**Comment by MrVinitBansal** [comment]
Ok I'll try it. Thanks for the support and will let you know if I get error after that

ThanksVinit BansalAsst. ProgrammerNational Informatics CentreMinistry of Finance,North BlockCallSend SMSAdd to SkypeYou'll need Skype CreditFree via SkypeCallSend SMSAdd to SkypeYou'll need Skype CreditFree via SkypeCallSend SMSAdd to SkypeYou'll need Skype CreditFree via Skype

Date: Mon, 2 Feb 2015 04:00:13 -0800

**Comment by smikes** [comment]
Is this still a problem for you?

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.

**Comment by MrVinitBansal** [comment]
You can close this.

ThanksVinit BansalProgrammerNational Informatics CentreMinistry of Finance,North BlockCallSend SMSAdd to SkypeYou'll need Skype CreditFree via SkypeCallSend SMSAdd to SkypeYou'll need Skype CreditFree via SkypeCallSend SMSAdd to SkypeYou'll need Skype CreditFree via Skype

Date: Tue, 11 Aug 2015 14:02:03 -0700
