### ISSUE TITLE
Can't login/publish using CLI

### ISSUE THREAD

**Issue by piranna** [npm/npm#7257]
I've recently changed of machine, so yesterday when trying to publish a package it requested my login credentials (ok). Problem is that it didn't worked. The same user & password worked on the web interface (https://www.npmjs.com/~piranna), but on the command line both ```npm publish``` & ```npm login``` returns a 404 error, both when using directly the main npm registry or through my company http mirror proxy.

npm-debug.log output:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'login', '--verbose' ]
2 info using npm@2.1.6
3 info using node@v0.11.15
4 verbose node symlink /usr/bin/node
5 verbose adduser before first PUT { name: 'piranna',
5 verbose adduser   password: 'XXXXX',
5 verbose adduser   email: 'piranna@gmail.com',
5 verbose adduser   _id: 'org.couchdb.user:piranna',
5 verbose adduser   type: 'user',
5 verbose adduser   roles: [],
5 verbose adduser   date: '2015-02-02T07:52:01.188Z' }
6 verbose request on initialization, where is /-/user/org.couchdb.user:piranna
7 verbose request after pass 1, where is /-/user/org.couchdb.user:piranna
8 verbose request url raw /-/user/org.couchdb.user:piranna
9 verbose request resolving registry [ 'https://registry.npmjs.org/-/user/org.couchdb.user:piranna',
9 verbose request   './-/user/org.couchdb.user:piranna' ]
10 verbose request after pass 2, where is https://registry.npmjs.org/-/user/-/user/org.couchdb.user:piranna
11 verbose request new user, so can't send auth
12 info attempt registry request try #1 at 08:52:01
13 verbose request id 2cefda0b5d1bff46
14 http request PUT https://registry.npmjs.org/-/user/-/user/org.couchdb.user:piranna
15 http 404 https://registry.npmjs.org/-/user/-/user/org.couchdb.user:piranna
16 verbose headers { date: 'Mon, 02 Feb 2015 07:52:03 GMT',
16 verbose headers   server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
16 verbose headers   'content-type': 'application/json',
16 verbose headers   'cache-control': 'max-age=0',
16 verbose headers   'content-length': '41',
16 verbose headers   'accept-ranges': 'bytes',
16 verbose headers   via: '1.1 varnish',
16 verbose headers   'x-served-by': 'cache-lhr6332-LHR',
16 verbose headers   'x-cache': 'MISS',
16 verbose headers   'x-cache-hits': '0',
16 verbose headers   'x-timer': 'S1422863523.787553,VS0,VE148',
16 verbose headers   connection: 'close' }
17 verbose adduser back [ { [Error: not_found missing: -/user/-/user/org.couchdb.user:piranna] statusCode: 404, code: 'E404' },
17 verbose adduser   { error: 'not_found', reason: 'missing' },
17 verbose adduser   '{"error":"not_found","reason":"missing"}' ]
18 verbose stack Error: not_found missing: -/user/-/user/org.couchdb.user:piranna
18 verbose stack     at RegClient.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:260:14)
18 verbose stack     at Request._callback (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:197:65)
18 verbose stack     at Request.self.callback (/usr/lib/node_modules/npm/node_modules/request/request.js:364:22)
18 verbose stack     at Request.emit (events.js:110:17)
18 verbose stack     at Request.<anonymous> (/usr/lib/node_modules/npm/node_modules/request/request.js:1318:14)
18 verbose stack     at Request.emit (events.js:129:20)
18 verbose stack     at IncomingMessage.<anonymous> (/usr/lib/node_modules/npm/node_modules/request/request.js:1266:12)
18 verbose stack     at IncomingMessage.emit (events.js:129:20)
18 verbose stack     at _stream_readable.js:908:16
18 verbose stack     at process._tickCallback (node.js:355:11)
19 verbose statusCode 404
20 verbose cwd /home/piranna/Proyectos/qunit-reporter-lcov
21 error Linux 3.16.0-30-generic
22 error argv "/usr/bin/node" "/usr/bin/npm" "login" "--verbose"
23 error node v0.11.15
24 error npm  v2.1.6
25 error code E404
26 error 404 not_found missing: -/user/-/user/org.couchdb.user:piranna
27 verbose exit [ 1, true ]
```

**Comment by smikes** [comment]
It looks like you're running into a bug in that version of `npm` where it's generating an incorrect URL: `https://registry.npmjs.org/-/user/-/user/org.couchdb.user:piranna` (note the doubled `/-/user`).

Can you try updating to `npm@latest` (2.4.1) to see if the problem persists?

```
sudo npm i -g npm@latest
```

**Comment by piranna** [comment]
I've updated to npm 2.4.1 and the bug got fixed, now I've been able to
login and publish the package. Thank you! :-)

2015-02-03 3:27 GMT+01:00 Sam Mikes <notifications@github.com>:

> It looks like you're running into a bug in that version of npm where it's
> generating an incorrect URL:
> https://registry.npmjs.org/-/user/-/user/org.couchdb.user:piranna (note
> the doubled /-/user).
>
> Can you try updating to npm@latest (2.4.1) to see if the problem persists?
>
> sudo npm i -g npm@latest
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/npm/npm/issues/7257#issuecomment-72581121>.
>



-- 
"Si quieres viajar alrededor del mundo y ser invitado a hablar en un monton
de sitios diferentes, simplemente escribe un sistema operativo Unix."
– Linus Tordvals, creador del sistema operativo Linux

**Comment by othiym23** [comment]
Closing as resolved.
