### ISSUE TITLE
create_fiori_client@3.5.0 No repository field

### ISSUE THREAD

**Issue by rmiddelburg** [npm/npm#7288]
Hello,

I get error when using npm. I have the following error log

```
0 info it worked if it ends with ok
1 verbose cli [ 'node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'node',
1 verbose cli   'create_fiori_client.js' ]
2 info using npm@1.4.28
3 info using node@v0.10.36
4 warn package.json create_fiori_client@3.5.0 No repository field.
5 verbose readDependencies using package.json deps
6 verbose cache add [ 'node', null ]
7 verbose cache add name=undefined spec="node" args=["node",null]
8 verbose parsed url { protocol: null,
8 verbose parsed url   slashes: null,
8 verbose parsed url   auth: null,
8 verbose parsed url   host: null,
8 verbose parsed url   port: null,
8 verbose parsed url   hostname: null,
8 verbose parsed url   hash: null,
8 verbose parsed url   search: null,
8 verbose parsed url   query: null,
8 verbose parsed url   pathname: 'node',
8 verbose parsed url   path: 'node',
8 verbose parsed url   href: 'node' }
9 verbose cache add [ 'create_fiori_client.js', null ]
10 verbose cache add name=undefined spec="create_fiori_client.js" args=["create_fiori_client.js",null]
11 verbose parsed url { protocol: null,
11 verbose parsed url   slashes: null,
11 verbose parsed url   auth: null,
11 verbose parsed url   host: null,
11 verbose parsed url   port: null,
11 verbose parsed url   hostname: null,
11 verbose parsed url   hash: null,
11 verbose parsed url   search: null,
11 verbose parsed url   query: null,
11 verbose parsed url   pathname: 'create_fiori_client.js',
11 verbose parsed url   path: 'create_fiori_client.js',
11 verbose parsed url   href: 'create_fiori_client.js' }
12 silly lockFile f8e966d1-node node
13 verbose lock node /Users/rmiddelburg/.npm/f8e966d1-node.lock
14 silly lockFile c48afe50-create-fiori-client-js create_fiori_client.js
15 verbose lock create_fiori_client.js /Users/rmiddelburg/.npm/c48afe50-create-fiori-client-js.lock
16 silly lockFile f8e966d1-node node
17 error Error: Attempt to unlock node, which hasn't been locked
17 error     at unlock (/usr/local/lib/node_modules/npm/lib/utils/locker.js:44:11)
17 error     at cb (/usr/local/lib/node_modules/npm/lib/cache/add-local.js:30:5)
17 error     at /usr/local/lib/node_modules/npm/lib/cache/add-local.js:47:20
17 error     at /usr/local/lib/node_modules/npm/lib/utils/locker.js:30:7
17 error     at cb (/usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:149:38)
17 error     at /usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:177:38
17 error     at Object.oncomplete (fs.js:108:15)
18 error If you need help, you may report this *entire* log,
18 error including the npm and node versions, at:
18 error     <http://github.com/npm/npm/issues>
19 error System Darwin 14.0.0
20 error command "node" "/usr/local/bin/npm" "install" "node" "create_fiori_client.js"
21 error cwd /Users/rmiddelburg/Documents/SMP_35/modules/KapselFramework/smp-plugins-dist/apps/fiori_client
22 error node -v v0.10.36
23 error npm -v 1.4.28
24 verbose exit [ 1, true ]
 ```
How has a solution for this error!

Kind regards,

**Comment by KenanY** [comment]
> ```
> 4 warn package.json create_fiori_client@3.5.0 No repository field.
> ```

This is just a warning; it's not the source of your error. Could you try [updating your version of `npm`](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-nix-osx-linux-etc)? You have `1.4.28` but the latest is `2.5.0`

**Comment by KenanY** [comment]
@rmiddelburg ping

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
