### ISSUE TITLE
Updating NPM when using io.js breaks node-gyp

### ISSUE THREAD

**Issue by toddself** [npm/npm#7290]
Fresh install of io.js 1.1.0 with npm 2.4.0 that comes bundled correctly downloads the iojs tarball from iojs.org

If you do `npm install -g npm` it will then try to download the tarball from nodejs.org which results in a 404.

```
↳ npm --version
2.5.1
↳ npm install level 
...truncated....
gyp http GET http://nodejs.org/dist/v1.1.0/node-v1.1.0.tar.gz
gyp http 404 http://nodejs.org/dist/v1.1.0/node-v1.1.0.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: 404 status code downloading tarball
gyp ERR! stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:246:14)
gyp ERR! stack     at Request.emit (events.js:119:20)
gyp ERR! stack     at Request.onRequestResponse (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1255:10)
gyp ERR! stack     at ClientRequest.emit (events.js:97:17)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:395:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:286:20)
gyp ERR! stack     at Socket.emit (events.js:97:17)
gyp ERR! stack     at readableAddChunk (_stream_readable.js:143:16)
gyp ERR! stack     at Socket.Readable.push (_stream_readable.js:106:10)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/todd/src/t/node_modules/level/node_modules/leveldown
gyp ERR! node -v v1.1.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
```

**Comment by othiym23** [comment]
This is a problem with `node-gyp`, and requires a resolution of TooTallNate/node-gyp#564 before npm will be able to solve it. So apply peer pressure there – I'm as eager to not have to keep landing the floating patch in the io.js source tree every week as anybody. ;)
