### ISSUE TITLE
Error with npm@1.4.28 / node@v0.10.35

### ISSUE THREAD

**Issue by codeguru007** [npm/npm#7301]
Hi geeks,

 Titanium doesn't run . Tryin to debug and a lot of errors in the debug-log. Did You have an idea what went wrong?

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   '-g',
1 verbose cli   'install',
1 verbose cli   'alloy',
1 verbose cli   '--color',
1 verbose cli   'false' ]
2 info using npm@1.4.28
3 info using node@v0.10.35
4 verbose cache add [ 'alloy', null ]
5 verbose cache add name=undefined spec="alloy" args=["alloy",null]
6 verbose parsed url { protocol: null,
6 verbose parsed url   slashes: null,
6 verbose parsed url   auth: null,
6 verbose parsed url   host: null,
6 verbose parsed url   port: null,
6 verbose parsed url   hostname: null,
6 verbose parsed url   hash: null,
6 verbose parsed url   search: null,
6 verbose parsed url   query: null,
6 verbose parsed url   pathname: 'alloy',
6 verbose parsed url   path: 'alloy',
6 verbose parsed url   href: 'alloy' }
7 silly lockFile 8d809cba-alloy alloy
8 verbose lock alloy C:\Users\WOTAN\AppData\Roaming\npm-cache\8d809cba-alloy.lock
9 silly lockFile 8d809cba-alloy alloy
10 silly lockFile 8d809cba-alloy alloy
11 verbose addNamed [ 'alloy', '' ]
12 verbose addNamed [ null, '*' ]
13 silly lockFile b2f8915b-alloy alloy@
14 verbose lock alloy@ C:\Users\WOTAN\AppData\Roaming\npm-cache\b2f8915b-alloy.lock
15 silly addNameRange { name: 'alloy', range: '*', hasData: false }
16 verbose request where is /alloy
17 verbose request registry https://registry.npmjs.org/
18 verbose request id 5a0095165f5a62e5
19 verbose url raw /alloy
20 verbose url resolving [ 'https://registry.npmjs.org/', './alloy' ]
21 verbose url resolved https://registry.npmjs.org/alloy
22 verbose request where is https://registry.npmjs.org/alloy
23 info trying registry request attempt 1 at 22:48:48
24 http GET https://registry.npmjs.org/alloy
25 http 200 https://registry.npmjs.org/alloy
26 silly registry.get cb [ 200,
26 silly registry.get   { date: 'Thu, 05 Feb 2015 21:48:41 GMT',
26 silly registry.get     server: 'CouchDB/1.6.1 (Erlang OTP/R14B04)',
26 silly registry.get     etag: '"ET18LJ1OGS2UR5TV6ANVHSMAA"',
26 silly registry.get     'content-type': 'application/json',
26 silly registry.get     'cache-control': 'max-age=60',
26 silly registry.get     'content-length': '223116',
26 silly registry.get     'accept-ranges': 'bytes',
26 silly registry.get     via: '1.1 varnish',
26 silly registry.get     age: '0',
26 silly registry.get     'x-served-by': 'cache-ams4120-AMS',
26 silly registry.get     'x-cache': 'HIT',
26 silly registry.get     'x-cache-hits': '1',
26 silly registry.get     'x-timer': 'S1423172920.769498,VS0,VE615',
26 silly registry.get     vary: 'Accept',
26 silly registry.get     'keep-alive': 'timeout=10, max=50',
26 silly registry.get     connection: 'Keep-Alive' } ]
27 silly addNameRange number 2 { name: 'alloy', range: '*', hasData: true }
28 silly addNameRange versions [ 'alloy',
28 silly addNameRange   [ '0.1.0',
28 silly addNameRange     '0.1.1',
28 silly addNameRange     '0.1.2',
28 silly addNameRange     '0.1.3',
28 silly addNameRange     '0.1.4',
28 silly addNameRange     '0.1.5',
28 silly addNameRange     '0.1.6',
28 silly addNameRange     '0.1.7',
28 silly addNameRange     '0.1.8',
28 silly addNameRange     '0.1.10',
28 silly addNameRange     '0.1.11',
28 silly addNameRange     '0.1.12',
28 silly addNameRange     '0.1.13',
28 silly addNameRange     '0.1.14',
28 silly addNameRange     '0.1.15',
28 silly addNameRange     '0.1.16',
28 silly addNameRange     '0.1.17',
28 silly addNameRange     '0.1.19',
28 silly addNameRange     '0.1.20',
28 silly addNameRange     '0.1.21',
28 silly addNameRange     '0.1.22',
28 silly addNameRange     '0.1.23',
28 silly addNameRange     '0.1.24',
28 silly addNameRange     '0.1.25',
28 silly addNameRange     '0.1.26',
28 silly addNameRange     '0.1.27',
28 silly addNameRange     '0.1.28',
28 silly addNameRange     '0.1.29',
28 silly addNameRange     '0.2.0',
28 silly addNameRange     '0.2.2',
28 silly addNameRange     '0.2.3',
28 silly addNameRange     '0.2.4',
28 silly addNameRange     '0.2.5',
28 silly addNameRange     '0.2.6',
28 silly addNameRange     '0.2.7',
28 silly addNameRange     '0.2.8',
28 silly addNameRange     '0.2.9',
28 silly addNameRange     '0.2.10',
28 silly addNameRange     '0.2.11',
28 silly addNameRange     '0.2.12',
28 silly addNameRange     '0.2.13',
28 silly addNameRange     '0.2.14',
28 silly addNameRange     '0.2.15',
28 silly addNameRange     '0.2.16',
28 silly addNameRange     '0.2.17',
28 silly addNameRange     '0.2.18',
28 silly addNameRange     '0.2.19',
28 silly addNameRange     '0.2.20',
28 silly addNameRange     '0.2.21',
28 silly addNameRange     '0.2.22',
28 silly addNameRange     '0.2.23',
28 silly addNameRange     '0.2.24',
28 silly addNameRange     '0.2.25',
28 silly addNameRange     '0.2.26',
28 silly addNameRange     '0.2.27',
28 silly addNameRange     '0.2.28',
28 silly addNameRange     '0.2.29',
28 silly addNameRange     '0.2.30',
28 silly addNameRange     '0.2.31',
28 silly addNameRange     '0.2.32',
28 silly addNameRange     '0.2.33',
28 silly addNameRange     '0.2.34',
28 silly addNameRange     '0.2.35',
28 silly addNameRange     '0.2.35-1',
28 silly addNameRange     '0.2.35-2',
28 silly addNameRange     '0.2.36',
28 silly addNameRange     '0.2.37',
28 silly addNameRange     '0.2.37-1',
28 silly addNameRange     '0.2.38',
28 silly addNameRange     '0.2.39',
28 silly addNameRange     '0.2.39-1',
28 silly addNameRange     '0.2.40',
28 silly addNameRange     '0.2.41',
28 silly addNameRange     '0.2.42',
28 silly addNameRange     '0.3.0',
28 silly addNameRange     '0.3.1',
28 silly addNameRange     '0.3.2',
28 silly addNameRange     '0.3.3',
28 silly addNameRange     '0.3.4',
28 silly addNameRange     '0.3.5',
28 silly addNameRange     '0.3.6',
28 silly addNameRange     '1.0.0-cr',
28 silly addNameRange     '1.0.0',
28 silly addNameRange     '1.1.0-alpha',
28 silly addNameRange     '1.1.0-beta',
28 silly addNameRange     '1.1.0-cr',
28 silly addNameRange     '1.1.0',
28 silly addNameRange     '1.1.1-alpha',
28 silly addNameRange     '1.1.1-cr',
28 silly addNameRange     '1.1.1',
28 silly addNameRange     '1.1.2-alpha',
28 silly addNameRange     '1.1.2',
28 silly addNameRange     '1.1.3-alpha',
28 silly addNameRange     '1.1.3-cr',
28 silly addNameRange     '1.1.3',
28 silly addNameRange     '1.2.0-alpha',
28 silly addNameRange     '1.2.0-alpha2',
28 silly addNameRange     '1.2.0-alpha3',
28 silly addNameRange     '1.2.0-alpha4',
28 silly addNameRange     '1.2.0-alpha5',
28 silly addNameRange     '1.2.0-alpha6',
28 silly addNameRange     '1.2.0-beta',
28 silly addNameRange     '1.2.1-cr',
28 silly addNameRange     '1.2.0',
28 silly addNameRange     '1.2.1-cr2',
28 silly addNameRange     '1.2.1',
28 silly addNameRange     '1.2.2-beta',
28 silly addNameRange     '1.2.2-cr',
28 silly addNameRange     '1.2.2',
28 silly addNameRange     '1.3.0-alpha',
28 silly addNameRange     '1.3.0-alpha6',
28 silly addNameRange     '1.3.0-alpha7',
28 silly addNameRange     '1.3.0-beta',
28 silly addNameRange     '1.3.0-cr',
28 silly addNameRange     '1.3.0-cr2',
28 silly addNameRange     '1.3.0',
28 silly addNameRange     '1.3.1-alpha',
28 silly addNameRange     '1.3.1-beta',
28 silly addNameRange     '1.3.1-beta2',
28 silly addNameRange     '1.3.1-beta3',
28 silly addNameRange     '1.3.1-beta4',
28 silly addNameRange     '1.3.1-cr',
28 silly addNameRange     '1.3.1-cr2',
28 silly addNameRange     '1.3.1-cr3',
28 silly addNameRange     '1.3.1',
28 silly addNameRange     '1.4.0-alpha',
28 silly addNameRange     '1.4.0-alpha2',
28 silly addNameRange     '1.4.0-alpha3',
28 silly addNameRange     '1.4.0-alpha4',
28 silly addNameRange     '1.4.0-beta',
28 silly addNameRange     '1.4.0-beta2',
28 silly addNameRange     '1.4.0-rc',
28 silly addNameRange     '1.4.0-rc2',
28 silly addNameRange     '1.4.0-rc3',
28 silly addNameRange     '1.4.0-rc4',
28 silly addNameRange     '1.4.0-rc5',
28 silly addNameRange     '1.4.0',
28 silly addNameRange     '1.4.1-rc',
28 silly addNameRange     '1.4.1',
28 silly addNameRange     '1.5.0-beta',
28 silly addNameRange     '1.5.0-beta2',
28 silly addNameRange     '1.5.0-rc',
28 silly addNameRange     '1.5.0-rc2',
28 silly addNameRange     '1.5.0-rc3',
28 silly addNameRange     '1.5.0-rc5',
28 silly addNameRange     '1.5.0',
28 silly addNameRange     '1.5.1-rc',
28 silly addNameRange     '1.5.1' ] ]
29 verbose addNamed [ 'alloy', '1.5.1' ]
30 verbose addNamed [ '1.5.1', '1.5.1' ]
31 silly lockFile 44c72771-alloy-1-5-1 alloy@1.5.1
32 verbose lock alloy@1.5.1 C:\Users\WOTAN\AppData\Roaming\npm-cache\44c72771-alloy-1-5-1.lock
33 silly lockFile bde2a834--npmjs-org-alloy-alloy-1-5-1-tgz https://registry.npmjs.org/alloy/-/alloy-1.5.1.tgz
34 verbose lock https://registry.npmjs.org/alloy/-/alloy-1.5.1.tgz C:\Users\WOTAN\AppData\Roaming\npm-cache\bde2a834--npmjs-org-alloy-alloy-1-5-1-tgz.lock
35 verbose addRemoteTarball [ 'https://registry.npmjs.org/alloy/-/alloy-1.5.1.tgz',
35 verbose addRemoteTarball   'cecc1d5ec6a73a13487642fb324ab05981b67f7d' ]
36 info retry fetch attempt 1 at 22:48:56
37 verbose fetch to= C:\Users\WOTAN\AppData\Local\Temp\npm-7648-_n-J2ogU\registry.npmjs.org\alloy\-\alloy-1.5.1.tgz
38 http GET https://registry.npmjs.org/alloy/-/alloy-1.5.1.tgz
39 http 200 https://registry.npmjs.org/alloy/-/alloy-1.5.1.tgz
40 silly lockFile bde2a834--npmjs-org-alloy-alloy-1-5-1-tgz https://registry.npmjs.org/alloy/-/alloy-1.5.1.tgz
41 silly lockFile bde2a834--npmjs-org-alloy-alloy-1-5-1-tgz https://registry.npmjs.org/alloy/-/alloy-1.5.1.tgz
42 silly lockFile 44c72771-alloy-1-5-1 alloy@1.5.1
43 silly lockFile 44c72771-alloy-1-5-1 alloy@1.5.1
44 silly lockFile b2f8915b-alloy alloy@
45 silly lockFile b2f8915b-alloy alloy@
46 error Error: shasum check failed for C:\Users\WOTAN\AppData\Local\Temp\npm-7648-_n-J2ogU\registry.npmjs.org\alloy\-\alloy-1.5.1.tgz
46 error Expected: cecc1d5ec6a73a13487642fb324ab05981b67f7d
46 error Actual:   b9a74dfb93f8e191064a7c36d3571a2f4f49c62f
46 error From:     https://registry.npmjs.org/alloy/-/alloy-1.5.1.tgz
46 error     at C:\Program Files\nodejs\node_modules\npm\node_modules\sha\index.js:38:8
46 error     at ReadStream.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\sha\index.js:85:7)
46 error     at ReadStream.emit (events.js:117:20)
46 error     at _stream_readable.js:944:16
46 error     at process._tickCallback (node.js:442:13)
47 error If you need help, you may report this *entire* log,
47 error including the npm and node versions, at:
47 error     <http://github.com/npm/npm/issues>
48 error System Windows_NT 6.1.7601
49 error command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "-g" "install" "alloy" "--color" "false"
50 error cwd C:\Users\WOTAN\Desktop
51 error node -v v0.10.35
52 error npm -v 1.4.28
53 verbose exit [ 1, true ]
```

cheers,

codeguru007

**Comment by KenanY** [comment]
@codeguru007 Could you first try [upgrading](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows) `npm` to the latest stable release? You have `1.4.28` but the latest is [`2.5.0`](https://github.com/npm/npm/releases/tag/v2.5.0).

**Comment by smikes** [comment]
It looks like you are running into a race condition of the sort that was found in older `npm` versions.  (Symptoms include: error 34 ENOENT; shasum errors in cache; general failure to install.)

Next time could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.4.28. Can you try updating your npm installation?

To update npm, run `npm -g install npm@latest`.  If you update to the latest `node` (0.12.0) or io.js (1.1.0), you will get an up-to-date `npm`.

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

Thanks!

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
