### ISSUE TITLE
npm install plugman

### ISSUE THREAD

**Issue by xidandan** [npm/npm#7305]
```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'install', '-g' ]
2 info using npm@2.5.1
3 info using node@v0.10.36
4 silly cache add args [ '.', null ]
5 verbose cache add spec .
6 silly cache add parsed spec { raw: '.',
6 silly cache add   scope: null,
6 silly cache add   name: null,
6 silly cache add   rawSpec: '.',
6 silly cache add   spec: '/Users/dandnan/cordova-plugman/cordova-plugman/npm/cordova-plugman/cordova-plugman',
6 silly cache add   type: 'directory' }
7 verbose addLocalDirectory /Users/dandnan/.npm/plugman/0.22.18-dev/package.tgz not in flight; packing
8 verbose tar pack [ '/Users/dandnan/.npm/plugman/0.22.18-dev/package.tgz',
8 verbose tar pack   '/Users/dandnan/cordova-plugman/cordova-plugman/npm/cordova-plugman/cordova-plugman' ]
9 verbose tarball /Users/dandnan/.npm/plugman/0.22.18-dev/package.tgz
10 verbose folder /Users/dandnan/cordova-plugman/cordova-plugman/npm/cordova-plugman/cordova-plugman
11 info prepublish plugman@0.22.18-dev
12 verbose addLocalTarball adding from inside cache /Users/dandnan/.npm/plugman/0.22.18-dev/package.tgz
13 silly cache afterAdd plugman@0.22.18-dev
14 verbose afterAdd /Users/dandnan/.npm/plugman/0.22.18-dev/package/package.json not in flight; writing
15 verbose afterAdd /Users/dandnan/.npm/plugman/0.22.18-dev/package/package.json written
16 silly install resolved [ { author: { name: 'Andrew Lunny', email: 'alunny@gmail.com' },
16 silly install resolved     name: 'plugman',
16 silly install resolved     description: 'install/uninstall Cordova plugins',
16 silly install resolved     version: '0.22.18-dev',
16 silly install resolved     repository:
16 silly install resolved      { type: 'git',
16 silly install resolved        url: 'git://git-wip-us.apache.org/repos/asf/cordova-plugman.git' },
16 silly install resolved     bugs:
16 silly install resolved      { url: 'https://issues.apache.org/jira/browse/CB',
16 silly install resolved        email: 'dev@cordova.apache.org' },
16 silly install resolved     main: 'plugman.js',
16 silly install resolved     engines: { node: '>=0.9.9' },
16 silly install resolved     engineStrict: true,
16 silly install resolved     dependencies:
16 silly install resolved      { 'cordova-lib': '4.2.0',
16 silly install resolved        nopt: '1.0.9',
16 silly install resolved        underscore: '1.7.0',
16 silly install resolved        q: '1.0.1',
16 silly install resolved        npm: '1.3.4',
16 silly install resolved        rc: '0.5.2' },
16 silly install resolved     devDependencies: { jshint: '2.5.8', 'jasmine-node': '1.14.5' },
16 silly install resolved     bin: { plugman: './main.js' },
16 silly install resolved     scripts:
16 silly install resolved      { test: 'npm run jasmine && npm run jshint',
16 silly install resolved        jshint: 'node node_modules/jshint/bin/jshint src',
16 silly install resolved        jasmine: 'jasmine-node --captureExceptions --color spec' },
16 silly install resolved     contributors:
16 silly install resolved      [ [Object],
16 silly install resolved        [Object],
16 silly install resolved        [Object],
16 silly install resolved        [Object],
16 silly install resolved        [Object],
16 silly install resolved        [Object],
16 silly install resolved        [Object],
16 silly install resolved        [Object],
16 silly install resolved        [Object],
16 silly install resolved        [Object],
16 silly install resolved        [Object] ],
16 silly install resolved     readme: '<!--\n#\n# Licensed to the Apache Software Foundation (ASF) under one\n# or more contributor license agreements.  See the NOTICE file\n# distributed with this work for additional information\n# regarding copyright ownership.  The ASF licenses this file\n# to you under the Apache License, Version 2.0 (the\n# "License"); you may not use this file except in compliance\n# with the License.  You may obtain a copy of the License at\n#\n# http://www.apache.org/licenses/LICENSE-2.0\n#\n# Unless required by applicable law or agreed to in writing,\n# software distributed under the License is distributed on an\n# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY\n#  KIND, either express or implied.  See the License for the\n# specific language governing permissions and limitations\n# under the License.\n#\n-->\n\n# plugman\n\nA command line tool to install and uninstall plugins for use with [Apache Cordova](http://cordova.io) projects.\n\nThis document defines tool usage.\n\n## Requirements\n\nYou must have `git` on your PATH to be able to install plugins directly from remote git URLs.\n\n## Plugin Specification\n\n--&gt; [Available on docs.cordova.io](http://cordova.apache.org/docs/en/3.0.0/plugin_ref_spec.md) &lt;--\n\n## Quickstart\n\n    npm install -g plugman\n\n## Design Goals\n\n* Facilitate programmatic installation and manipulation of plugins\n* Detail the dependencies and components of individual plugins\n* Allow code reuse between different target platforms\n\n## Supported Platforms\n\n* Amazon Fire OS\n* Android\n* BlackBerry 10\n* iOS\n* Tizen\n* Windows Phone 8\n* Windows 8\n\n## Command Line Usage\nDisplay all available plugman commands:\n\n    plugman help\n\n### Plugin Management\n\nInstall a plugin into a Cordova project: \n\n    plugman install --platform <ios|amazon-fireos|android|blackberry10|wp8> --project <directory> --plugin <name|url|path> [--plugins_dir <directory>] [--www <directory>] [--variable <name>=<value> [--variable <name>=<value> ...]]\n\nUninstall a Plugin from a Cordova project:\n\n\tplugman uninstall --platform <ios|amazon-fireos|android|blackberry10|wp8> --project <directory> --plugin <id> [--www <directory>] [--plugins_dir <directory>]\n\nFor each command (install and uninstall), you must specify a platform and Cordova project location for that platform. You also must specify a plugin, with the different `--plugin` parameter forms being:\n\n  * `name`: The directory name where the plugin contents exist. This must be an existing directory under the `--plugins_dir` path (see below for more info) or a plugin in the Cordova registry.\n  * `url`: A URL starting with https:// or git://, pointing to a valid git repository that is clonable and contains a `plugin.xml` file. The contents of this repository would be copied into the `--plugins_dir`.\n  * `path`: A path to a directory containing a valid plugin which includes a `plugin.xml` file. This path\'s contents will be copied into the `--plugins_dir`.\n\nOther parameters:\n\n* `--plugins_dir` defaults to `<project>/cordova/plugins`, but can be any directory containing a subdirectory for each fetched plugin.\n* `--www` defaults to the project\'s `www` folder location, but can be any directory that is to be used as cordova project application web assets.\n* `--variable` allows to specify certain variables at install time, necessary for certain plugins requiring API keys or other custom, user-defined parameters. Please see the [plugin specification](plugin_spec.md) for more information.\n\n### Registry Search\n\nSearch the [Plugin registry](http://plugins.cordova.io) for plugin id\'s that match the given space separated list of keywords.\n\n    plugman search <plugin keywords>\n\n### Configuration Management:\n\nDisplay the current list of configuration settings:\n\n\tplugman config ls\n\nDisplay the current repository endpoint:\n\n    plugman config get registry\n\nSet the registry endpoint:\n\n    plugman config set registry <url-to-registry>\n\nYou should leave this set to http://registry.cordova.io, unless you want to use a third party plugin registry.\n\n## Node Module Usage\nThis section details how to consume Plugman as a node module and is only for Cordova tool authors and other hackers. You should not need to read this section if you are just using Plugman to manage a Cordova project.\n\n    node\n    > require(\'plugman\')\n    { install: [Function: installPlugin],\n      uninstall: [Function: uninstallPlugin],\n      fetch: [Function: fetchPlugin],\n      search: [Function: search],\n      publish: [Function: publish],\n      unpublish: [Function: unpublish],\n      adduser: [Function: adduser],\n      prepare: [Function: handlePrepare],\n      create: [Function: create],\n      platform: [Function: platform] }\n\n### `install` method\n\n    module.exports = function installPlugin(platform, project_dir, id, plugins_dir, subdir, cli_variables, www_dir, callback) {\n\nInstalls a plugin into a specified cordova project of a specified platform.\n\n * `platform`: one of `amazon-fireos`, `android`, `ios`, `blackberry10`, or `wp8`\n * `project_dir`: path to an instance of the above specified platform\'s cordova project\n * `id`: a string representing the `id` of the plugin, a path to a cordova plugin with a valid `plugin.xml` file, or an `https://` or `git://` url to a git repository of a valid cordova plugin or a plugin published to the Cordova registry\n * `plugins_dir`: path to directory where plugins will be stored, defaults to `<project_dir>/cordova/plugins`\n * `subdir`: subdirectory within the plugin directory to consider as plugin directory root, defaults to `.`\n * `cli_variables`: an object mapping cordova plugin specification variable names (see [plugin specification](plugin_spec.md)) to values\n * `www_dir`: path to directory where web assets are to be copied to, defaults to the specified project directory\'s `www` dir (dependent on platform)\n * `callback`: callback to invoke once complete. If specified, will pass in an error object as a first parameter if the action failed. If not and an error occurs, `plugman` will throw the error\n\n### `uninstall` method\n\n    module.exports = function uninstallPlugin(platform, project_dir, id, plugins_dir, cli_variables, www_dir, callback) {\n\nUninstalls a previously-installed cordova plugin from a specified cordova project of a specified platform.\n\n * `platform`: one of `amazon-fireos`, `android`, `ios`, `blackberry10`, or `wp8`\n * `project_dir`: path to an instance of the above specified platform\'s cordova project\n * `id`: a string representing the `id` of the plugin\n * `plugins_dir`: path to directory where plugins are stored, defaults to `<project_dir>/cordova/plugins`\n * `subdir`: subdirectory within the plugin directory to consider as plugin directory root, defaults to `.`\n * `cli_variables`: an object mapping cordova plugin specification variable names (see [plugin specification](plugin_spec.md)) to values\n * `www_dir`: path to directory where web assets are to be copied to, defaults to the specified project directory\'s `www` dir (dependent on platform)\n * `callback`: callback to invoke once complete. If specified, will pass in an error object as a first parameter if the action failed. If not and an error occurs, `plugman` will throw the error\n\n### `fetch` method\n\nCopies a cordova plugin into a single location that plugman uses to track which plugins are installed into a project.\n\n    module.exports = function fetchPlugin(plugin_dir, plugins_dir, link, subdir, git_ref, callback) {\n\n * `plugin_dir`: path, URL to a plugin directory/repository or name of a plugin published to the Cordova registry.\n * `plugins_dir`: path housing all plugins used in this project\n * `link`: if `plugin_dir` points to a local path, will create a symbolic link to that folder instead of copying into `plugins_dir`, defaults to `false`\n * `subdir`: subdirectory within the plugin directory to consider as plugin directory root, defaults to `.`\n * `gitref`: if `plugin_dir` points to a URL, this value will be used to pass into `git checkout` after the repository is cloned, defaults to `HEAD`\n * `callback`: callback to invoke once complete. If specified, will pass in an error object as a first parameter if the action failed. If not and an error occurs, `plugman` will throw the error\n\n### `prepare` method\n\nFinalizes plugin installation by making configuration file changes and setting up a JavaScript loader for js-module support.\n\n    module.exports = function handlePrepare(project_dir, platform, plugins_dir) {\n\n * `project_dir`: path to an instance of the above specified platform\'s cordova project\n * `platform`: one of `amazon-fireos`, `android`, `ios`, `blackberry10`, or `wp8`\n * `plugins_dir`: path housing all plugins used in this project\n\n## Registry related actions\n\n### `adduser` method\n\nAdds a user account to the registry. Function takes no arguments other than a an optional callback\n\n    module.exports = function(callback) {\n\n### `publish` method\n\nPublishes plugins to the registry. `plugin_paths` is an array of plugin paths to publish to the registry.\n\n    module.exports = function(plugin_paths, callback) {\n\n### `unpublish` method\n\nunpublishes plugins from the registry. Can unpublish a version by specifying `plugin@version` or the whole plugin by just specifying `plugin`. `plugins` is an array of `plugin[@version]` elements.\n\n    module.exports = function(plugins, callback) {\n\n### `search` method\n\nSearches plugins in the registry. `search_opts` is an array of keywords\n\n    module.exports = function(search_opts, callback) {\n\n### `config` method\n\nConfigures registry settings. `params` is an array that describes the action\n    /*\n    * var params = [\'get\', \'registry\'];\n    * var params = [\'set\', \'registry\', \'http://registry.cordova.io\'];\n    * module.exports = function(params, callback) {\n    */\n\n## Create plugin related actions\n\n### `create` method\n\nCreates basic scaffolding for a new plugin\n\n  module.exports = function create( name, id, version, pluginPath, options, callback ) {...}\n\n* `name` : a name for the plugin\n* `id` : an id for the plugin\n* `version` : a version for the plugin\n* `pluginPath` : a path to create the plugin in\n* `options` : an array of options\n* `callback` : callback to invoke once complete. If specified, will pass in an error object as a first parameter if the action failed. If not and an error occurs, `plugman` will throw the error\n\n### `platform` method\n\nAdd/Remove a platform from a newly created plugin\n\n  module.exports = function platform( { operation: operation, platform_name: cli_opts.platform_name } );\n\n* `operation` : "add or remove"\n* `platform_name` : ios, android\n\n## Example Plugins\n\n- Google has a [bunch of plugins](https://github.com/MobileChromeApps/mobile-chrome-apps/tree/master/chrome-cordova/plugins) which are maintained actively by a contributor to plugman\n- Adobe maintains plugins for its Build cloud service, which are open sourced and [available on GitHub](https://github.com/phonegap-build)\n- BlackBerry has a [bunch of plugins](https://github.com/blackberry/cordova-blackberry/tree/master/blackberry10/plugins) offering deep platform integration\n- Core and 3rd party plugins can be found on the [Cordova Registry](http://plugins.cordova.io).\n\n## Development\n\nBasic installation:\n\n    git clone https://git-wip-us.apache.org/repos/asf/cordova-plugman.git\n    cd cordova-plugman\n    npm install -g\n\nLinking the global executable to the git repo:\n\n    git clone https://git-wip-us.apache.org/repos/asf/cordova-plugman.git\n    cd cordova-plugman\n    npm install\n    sudo npm link\n\n### Running Tests\n\n    npm test\n\n## Plugin Directory Structure\n\nA plugin is typically a combination of some web/www code, and some native code.\nHowever, plugins may have only one of these things - a plugin could be a single\nJavaScript file, or some native code with no corresponding JavaScript.\n\nHere is a sample plugin named foo with android and ios platforms support, and 2 www assets.\n\n```\nfoo-plugin/\n|- plugin.xml     # xml-based manifest\n|- src/           # native source for each platform\n|  |- android/\n|  |  `- Foo.java\n|  `- ios/\n|     |- CDVFoo.h\n|     `- CDVFoo.m\n|- README.md\n`- www/\n   |- foo.js\n   `- foo.png\n```\n\nThis structure is suggested, but not required.\n\n## Contributors\n\nSee the [package.json](package.json) file for attribution notes.\n\n## License\n\nApache License 2.0\n',
16 silly install resolved     readmeFilename: 'README.md',
16 silly install resolved     gitHead: 'cc0ec04d0209f26b10f14f6fa91296fe529f4af0',
16 silly install resolved     _id: 'plugman@0.22.18-dev',
16 silly install resolved     _shasum: 'ced2d44d087ac7a6c6232832c37416468596db92',
16 silly install resolved     _from: '../../Users/dandnan/cordova-plugman/cordova-plugman/npm/cordova-plugman/cordova-plugman',
16 silly install resolved     _resolved: 'file:../../Users/dandnan/cordova-plugman/cordova-plugman/npm/cordova-plugman/cordova-plugman' } ]
17 info install plugman@0.22.18-dev into /usr/local/lib
18 info installOne plugman@0.22.18-dev
19 verbose installOne of plugman to /usr/local/lib not in flight; installing
20 warn locking Error: EACCES, open '/Users/dandnan/.npm/_locks/plugman-36ae8474b10e3e50.lock'
20 warn locking  /Users/dandnan/.npm/_locks/plugman-36ae8474b10e3e50.lock failed { [Error: EACCES, open '/Users/dandnan/.npm/_locks/plugman-36ae8474b10e3e50.lock']
20 warn locking   errno: 3,
20 warn locking   code: 'EACCES',
20 warn locking   path: '/Users/dandnan/.npm/_locks/plugman-36ae8474b10e3e50.lock' }
21 verbose stack Error: Attempt to unlock /usr/local/lib/node_modules/plugman, which hasn't been locked
21 verbose stack     at unlock (/usr/local/lib/node_modules/npm/lib/utils/locker.js:66:11)
21 verbose stack     at cb (/usr/local/lib/node_modules/npm/lib/install.js:929:5)
21 verbose stack     at /usr/local/lib/node_modules/npm/lib/install.js:933:20
21 verbose stack     at /usr/local/lib/node_modules/npm/lib/utils/locker.js:40:9
21 verbose stack     at cb (/usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:149:38)
21 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:177:38
21 verbose stack     at Object.oncomplete (fs.js:108:15)
22 verbose cwd /Users/dandnan/cordova-plugman/cordova-plugman/npm/cordova-plugman/cordova-plugman
23 error Darwin 13.4.0
24 error argv "node" "/usr/local/bin/npm" "install" "-g"
25 error node v0.10.36
26 error npm  v2.5.1
27 error Attempt to unlock /usr/local/lib/node_modules/plugman, which hasn't been locked
28 error If you need help, you may report this error at:
28 error     <http://github.com/npm/npm/issues>
29 verbose exit [ 1, true ]
 ```

**Comment by smikes** [comment]
Thanks for the bug report.  This looks like an old error ("Error: Attempt to unlock /usr/local/lib/node_modules/plugman, which hasn't been locked") but I can see that you are running with `npm@next`, the very latest version.

Could you please upload your package.json as a gist <https://gist.github.com> -- if there is any proprietary information in there, please delete it, of course -- and also tell us what situation you see this bug in?  At present I don't know enough to be able to reproduce it on my own machine.

/cc @othiym23 bug , possible regression , need repro

**Comment by othiym23** [comment]
Not a regression -- a permissions problem:

```
20 warn locking Error: EACCES, open '/Users/dandnan/.npm/_locks/plugman-36ae8474b10e3e50.lock'
20 warn locking  /Users/dandnan/.npm/_locks/plugman-36ae8474b10e3e50.lock failed { [Error: EACCES, open '/Users/dandnan/.npm/_locks/plugman-36ae8474b10e3e50.lock']
20 warn locking   errno: 3,
20 warn locking   code: 'EACCES',
20 warn locking   path: '/Users/dandnan/.npm/_locks/plugman-36ae8474b10e3e50.lock' }
```

`$ sudo chown -R $(whoami) "$HOME/.npm"` should fix it for you. See also #7309.

**Comment by fdambrosio** [comment]
thanks othiym23! I've problem with .plugman directory, so 
sudo chown -R $(whoami) "$HOME/.plugman"
