### ISSUE TITLE
npm install ecrud

### ISSUE THREAD

**Issue by cherukurik** [npm/npm#7319]
I am not able to install ecrud using npm install in mac os X. Below is the error .
```
LV-KCHERUKURI:~ LV-KCHERUKURI$ npm install ecrud
npm ERR! Darwin 13.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "ecrud"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1

npm ERR! Cannot read property 'latest' of undefined
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/LV-KCHERUKURI/npm-debug.log
```

```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'install', 'ecrud' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 verbose config Skipping project config: /Users/LV-KCHERUKURI/.npmrc. (matches userconfig)
5 silly cache add args [ 'ecrud', null ]
6 verbose cache add spec ecrud
7 silly cache add parsed spec { raw: 'ecrud',
7 silly cache add   scope: null,
7 silly cache add   name: 'ecrud',
7 silly cache add   rawSpec: '',
7 silly cache add   spec: '*',
7 silly cache add   type: 'range' }
8 verbose addNamed ecrud@*
9 silly addNamed semver.valid null
10 silly addNamed semver.validRange *
11 silly addNameRange { name: 'ecrud', range: '*', hasData: false }
12 silly mapToRegistry name ecrud
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/ecrud
16 verbose addNameRange registry:https://registry.npmjs.org/ecrud not in flight; fetching
17 verbose request uri https://registry.npmjs.org/ecrud
18 verbose request no auth needed
19 info attempt registry request try #1 at 4:05:34 PM
20 verbose request id 84f0046e30d620b8
21 verbose etag "5H9SO2V07Y4XJ9CHOK9NAGLXC"
22 http request GET https://registry.npmjs.org/ecrud
23 http 404 https://registry.npmjs.org/ecrud
24 verbose headers { date: 'Mon, 09 Feb 2015 21:05:34 GMT',
24 verbose headers   server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
24 verbose headers   etag: '"5H9SO2V07Y4XJ9CHOK9NAGLXC"',
24 verbose headers   'content-type': 'application/json',
24 verbose headers   'cache-control': 'max-age=0',
24 verbose headers   'content-length': '763',
24 verbose headers   'accept-ranges': 'bytes',
24 verbose headers   via: '1.1 varnish',
24 verbose headers   age: '0',
24 verbose headers   'x-served-by': 'cache-dfw1831-DFW',
24 verbose headers   'x-cache': 'MISS',
24 verbose headers   'x-cache-hits': '0',
24 verbose headers   'x-timer': 'S1423515934.057215,VS0,VE45',
24 verbose headers   vary: 'Accept',
24 verbose headers   'keep-alive': 'timeout=10, max=50',
24 verbose headers   connection: 'Keep-Alive' }
25 silly get cb [ 304, undefined ]
26 verbose etag https://registry.npmjs.org/ecrud from cache
27 verbose get saving ecrud to /Users/LV-KCHERUKURI/.npm/registry.npmjs.org/ecrud/.cache.json
28 silly addNameRange number 2 { name: 'ecrud', range: '*', hasData: true }
29 silly addNameRange versions [ 'ecrud', [] ]
30 verbose stack TypeError: Cannot read property 'latest' of undefined
30 verbose stack     at next (/usr/local/lib/node_modules/npm/lib/cache/add-named.js:227:35)
30 verbose stack     at setData (/usr/local/lib/node_modules/npm/lib/cache/add-named.js:215:5)
30 verbose stack     at RES (/usr/local/lib/node_modules/npm/node_modules/inflight/inflight.js:23:14)
30 verbose stack     at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:17:25)
30 verbose stack     at saved (/usr/local/lib/node_modules/npm/lib/cache/caching-client.js:173:7)
30 verbose stack     at FSReqWrap.oncomplete (fs.js:99:15)
31 verbose cwd /Users/LV-KCHERUKURI
32 error Darwin 13.3.0
33 error argv "node" "/usr/local/bin/npm" "install" "ecrud"
34 error node v0.12.0
35 error npm  v2.5.1
36 error Cannot read property 'latest' of undefined
37 error If you need help, you may report this error at:
37 error     <http://github.com/npm/npm/issues>
38 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
The `ecrud` package you are trying to installed has been [unpublished](https://www.npmjs.com/package/ecrud). As such, you can no longer install it from the registry.

**Comment by cherukurik** [comment]
ooooo.Thanks !!!! Is there any way to install eCRUD?

**Comment by KenanY** [comment]
Sorry, I can only help with `npm` issues here on the `npm` issue tracker. Maybe you could contact [the author](https://www.npmjs.com/~julianjewel) of the unpublished package?

**Comment by othiym23** [comment]
Closing as resolved.
