### ISSUE TITLE
why...fetch failed 

### ISSUE THREAD

**Issue by Ohen** [npm/npm#7326]
```
npm ERR! fetch failed http://addrs
npm ERR! Error: 404 Not Found
npm ERR!     at WriteStream.<anonymous> (/home/.nvm/v0.10.32/lib/node_modules/npm/lib/utils/fetch.js:58:12)
npm ERR!     at WriteStream.emit (events.js:117:20)
npm ERR!     at evalmachine.<anonymous>:1609:14
npm ERR!     at /home/.nvm/v0.10.32/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:102:5
npm ERR!     at Object.oncomplete (evalmachine.<anonymous>:107:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.13.0-37-generic
npm ERR! command "/home/.nvm/v0.10.32/bin/node" "/home/.nvm/v0.10.32/bin/npm" "install"
npm ERR! cwd /home/tmp/connectionutil
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/fodler/npm-debug.log
npm ERR! not ok code 0
```

npm-debug.log
```
985 error Error: 404 Not Found
985 error     at WriteStream.<anonymous> (/home/.nvm/v0.10.32/lib/node_modules/npm/lib/utils/fetch.js:58:12)
985 error     at WriteStream.emit (events.js:117:20)
985 error     at evalmachine.<anonymous>:1609:14
985 error     at /home/.nvm/v0.10.32/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:102:5
985 error     at Object.oncomplete (evalmachine.<anonymous>:107:15)
986 error If you need help, you may report this *entire* log,
986 error including the npm and node versions, at:
986 error     <http://github.com/npm/npm/issues>
987 error System Linux 3.13.0-37-generic
988 error command "/home/.nvm/v0.10.32/bin/node" "/home/.nvm/v0.10.32/bin/npm" "install"
989 error cwd /home/folder/tmp/
990 error node -v v0.10.32
991 error npm -v 1.4.28
```

why this err generate???

how to do

**Comment by smikes** [comment]
Can you please upload your entire npm-debug.log file as a gist <https://gist.github.com> ?
