### ISSUE TITLE
Ember with Yo

### ISSUE THREAD

**Issue by shadhanu** [npm/npm#7328]
While running this command "yo ember"

I get below error. Can someone help
```
806 warn locking Error: EACCES, open '/Users/dhanushka/.npm/_locks/grunt-contrib-compass-43671b3acb255f25.lock'
806 warn locking  /Users/dhanushka/.npm/_locks/grunt-contrib-compass-43671b3acb255f25.lock failed { [Error: EACCES, open '/Users/dhanushka/.npm/_locks/grunt-contrib-compass-43671b3acb255f25.lock']
806 warn locking   errno: 3,
806 warn locking   code: 'EACCES',
806 warn locking   path: '/Users/dhanushka/.npm/_locks/grunt-contrib-compass-43671b3acb255f25.lock' }
807 verbose stack Error: Attempt to unlock /Users/dhanushka/Projects/Node/yo/getbookmarks/node_modules/grunt-contrib-compass, which hasn't been locked
807 verbose stack     at unlock (/usr/local/lib/node_modules/npm/lib/utils/locker.js:66:11)
807 verbose stack     at cb (/usr/local/lib/node_modules/npm/lib/install.js:929:5)
807 verbose stack     at /usr/local/lib/node_modules/npm/lib/install.js:933:20
807 verbose stack     at /usr/local/lib/node_modules/npm/lib/utils/locker.js:40:9
807 verbose stack     at cb (/usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:149:38)
807 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:177:38
807 verbose stack     at Object.oncomplete (fs.js:107:15)
808 verbose cwd /Users/dhanushka/Projects/Node/yo/getbookmarks
809 error Darwin 13.4.0
810 error argv "node" "/usr/local/bin/npm" "install"
811 error node v0.10.30
812 error npm  v2.5.0
813 error Attempt to unlock /Users/dhanushka/Projects/Node/yo/getbookmarks/node_modules/grunt-contrib-compass, which hasn't been locked
814 error If you need help, you may report this error at:
814 error     <http://github.com/npm/npm/issues>
815 verbose exit [ 1, true ]
```

**Comment by othiym23** [comment]
Try running

```
sudo chown -R $(whoami) $HOME/.npm
```

The permissions inside your npm cache got messed up with an older version of npm.

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
