### ISSUE TITLE
Error: Cannot find module 'express' in mac

### ISSUE THREAD

**Issue by cherukurik** [npm/npm#7329]
I got the below error when I start the server.

```
module.js:338
    throw err;
          ^
Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/eCrud/bin/server.js:8:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
```
I installed express using npm ...but I still see the issue.

Can someone please help on fixing this issue?

**Comment by smikes** [comment]
Did you run "npm install" in the current directory?

**Comment by cherukurik** [comment]
I did sudo npm install on root folder.

can you please tell me what this current directory mean?

**Comment by cherukurik** [comment]
Let me explain what I did..

I downloaded the eCRUD package and then tried running the server.js which is available in eCrud/bin folder...It gave me the below express error. In this case what should be the current directory?

in my command terminal...i executed the below commands ..still I see the same issue when I start the eCrud server.js

cd ~
sudo npm install express


module.js:338
throw err;
^
Error: Cannot find module 'express'
at Function.Module._resolveFilename (module.js:336:15)
at Function.Module._load (module.js:278:25)
at Module.require (module.js:365:17)
at require (module.js:384:17)
at Object. (/usr/local/eCrud/bin/server.js:8:15)
at Module._compile (module.js:460:26)
at Object.Module._extensions..js (module.js:478:10)
at Module.load (module.js:355:32)
at Function.Module._load (module.js:310:12)
at Function.Module.runMain (module.js:501:10)

**Comment by smikes** [comment]
> cd ~
sudo npm install express

This will install `npm` into your `~/node_modules` directory, which is not where eCrud needs it to be.

You need to cd into whatever directory you unpacked `eCrud` in and run `npm install` there.  No `sudo` and no `express`, just `npm install`.

**Comment by Bezaleli** [comment]
run npm install

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
