### ISSUE TITLE
npm not installing...throws following error in windows 7

### ISSUE THREAD

**Issue by saravana91** [npm/npm#7348]
```
C:\node>npm install -g cordova
npm http GET https://registry.npmjs.org/cordova
npm http GET https://registry.npmjs.org/cordova
npm http GET https://registry.npmjs.org/cordova
npm ERR! Error: getaddrinfo EAI_AGAIN
npm ERR!     at Object.exports._errnoException (util.js:746:11)
npm ERR!     at errnoException (dns.js:49:15)
npm ERR!     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:94:26)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7600
npm ERR! command "C:\\node\\\\node.exe" "C:\\node\\node_modules\\npm\\bin\\npm-c
li.js" "install" "-g" "cordova"
npm ERR! cwd C:\node
npm ERR! node -v v0.12.0
npm ERR! npm -v 1.4.9
npm ERR! syscall getaddrinfo
npm ERR! code EAI_AGAIN
npm ERR! errno EAI_AGAIN
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\node\npm-debug.log
npm ERR! not ok code 0
```
Log File Content:
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\node\\\\node.exe',
1 verbose cli   'C:\\node\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'cordova' ]
2 info using npm@1.4.9
3 info using node@v0.12.0
4 verbose node symlink C:\node\\node.exe
5 verbose cache add [ 'cordova', null ]
6 verbose cache add name=undefined spec="cordova" args=["cordova",null]
7 verbose parsed url { protocol: null,
7 verbose parsed url   slashes: null,
7 verbose parsed url   auth: null,
7 verbose parsed url   host: null,
7 verbose parsed url   port: null,
7 verbose parsed url   hostname: null,
7 verbose parsed url   hash: null,
7 verbose parsed url   search: null,
7 verbose parsed url   query: null,
7 verbose parsed url   pathname: 'cordova',
7 verbose parsed url   path: 'cordova',
7 verbose parsed url   href: 'cordova' }
8 silly lockFile a98f2055-cordova cordova
9 verbose lock cordova C:\Users\admin\AppData\Roaming\npm-cache\a98f2055-cordova.lock
10 silly lockFile a98f2055-cordova cordova
11 silly lockFile a98f2055-cordova cordova
12 verbose addNamed [ 'cordova', '' ]
13 verbose addNamed [ null, '*' ]
14 silly lockFile de8d9fad-cordova cordova@
15 verbose lock cordova@ C:\Users\admin\AppData\Roaming\npm-cache\de8d9fad-cordova.lock
16 silly addNameRange { name: 'cordova', range: '*', hasData: false }
17 verbose url raw cordova
18 verbose url resolving [ 'https://registry.npmjs.org/', './cordova' ]
19 verbose url resolved https://registry.npmjs.org/cordova
20 info trying registry request attempt 1 at 6:39:31 PM
21 http GET https://registry.npmjs.org/cordova
22 info retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN
23 info trying registry request attempt 2 at 6:39:53 PM
24 http GET https://registry.npmjs.org/cordova
25 info retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN
26 info trying registry request attempt 3 at 6:41:05 PM
27 http GET https://registry.npmjs.org/cordova
28 silly lockFile de8d9fad-cordova cordova@
29 silly lockFile de8d9fad-cordova cordova@
30 error Error: getaddrinfo EAI_AGAIN
30 error     at Object.exports._errnoException (util.js:746:11)
30 error     at errnoException (dns.js:49:15)
30 error     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:94:26)
31 error If you need help, you may report this *entire* log,
31 error including the npm and node versions, at:
31 error     <http://github.com/npm/npm/issues>
32 error System Windows_NT 6.1.7600
33 error command "C:\\node\\\\node.exe" "C:\\node\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova"
34 error cwd C:\node
35 error node -v v0.12.0
36 error npm -v 1.4.9
37 error syscall getaddrinfo
38 error code EAI_AGAIN
39 error errno EAI_AGAIN
40 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
@saravana91 Hmm, I don't think I've seen `EAI_AGAIN` before, but from the manpage of `getaddrinfo`:

```
EAI_AGAIN
        The name server returned a temporary failure indication.  Try again later.
```

So this seems like a DNS lookup timed out. I don't think this is a `npm` issue rather than some issue with your internet connection. Manpage recommends trying again later.

As an aside, your version of `npm` is really old, despite the fact that you have Node.js v0.12 installed! You should [update](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows) for many bug fixes :)

**Comment by saravana91** [comment]
My current version :
npm@1.4.9 C:\node\node_modules\npm
C:\node>node -v
v0.12.0
is it oaky?.am newbie to this.How could install cordova.Please solve my issue

**Comment by saravana91** [comment]
npm comes with nodejs currently,right?...i downloaded node.js v 0.12.0

**Comment by KenanY** [comment]
@saravana91 `npm` does come with Node.js but despite installing v0.12 you still have an old version of `npm` (you have `1.4.9` whilst the latest at this moment is `2.5.0`). I've already linked you to [a guide](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows) on how to update `npm` on Windows.

> Please solve my issue

Like I said in my previous comment, this does not look like an `npm` issue. Instead, this appears to be an issue with your internet connection making a DNS lookup. The documentation on the error simply says to try again later :/

**Comment by smikes** [comment]
@saravana91 Is this still a problem for you?

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as resolved:

1. `EAGAIN` is a transient name service failure, so keep retrying your request and it should eventually make it through.
2. Follow the upgrade guide that @KenanY linked to, and you should end up with a new, better npm on Windows.
