### ISSUE TITLE
Getting EACCESS error while running npm install sails-mongo

### ISSUE THREAD

**Issue by echorohit** [npm/npm#7359]
Hi I am getting 
```
npm WARN locking Error: EACCES, open '/home/echorohit/.npm/_locks/sails-mongo-851c37437689533a.lock.STALE'
npm WARN locking     at Error (native)
npm WARN locking  /home/echorohit/.npm/_locks/sails-mongo-851c37437689533a.lock failed { [Error: EACCES, open '/home/echorohit/.npm/_locks/sails-mongo-851c37437689533a.lock.STALE']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/home/echorohit/.npm/_locks/sails-mongo-851c37437689533a.lock.STALE' }
npm ERR! Linux 3.13.0-45-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "sails-mongo"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1

npm ERR! Attempt to unlock /home/echorohit/rediwala/node_modules/sails-mongo, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/echorohit/rediwala/npm-debug.log
```
While running  npm install sails-mongo

Npm debug log file ---
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'sails-mongo' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 silly cache add args [ 'sails-mongo', null ]
5 verbose cache add spec sails-mongo
6 silly cache add parsed spec { raw: 'sails-mongo',
6 silly cache add   scope: null,
6 silly cache add   name: 'sails-mongo',
6 silly cache add   rawSpec: '',
6 silly cache add   spec: '*',
6 silly cache add   type: 'range' }
7 verbose addNamed sails-mongo@*
8 silly addNamed semver.valid null
9 silly addNamed semver.validRange *
10 silly addNameRange { name: 'sails-mongo', range: '*', hasData: false }
11 silly mapToRegistry name sails-mongo
12 silly mapToRegistry using default registry
13 silly mapToRegistry registry https://registry.npmjs.org/
14 silly mapToRegistry uri https://registry.npmjs.org/sails-mongo
15 verbose addNameRange registry:https://registry.npmjs.org/sails-mongo not in flight; fetching
16 verbose request uri https://registry.npmjs.org/sails-mongo
17 verbose request no auth needed
18 info attempt registry request try #1 at 3:44:50 AM
19 verbose request id 3825bd980d57bf28
20 verbose etag "6MBOB9V7EJ301Q92A18DZFB4Z"
21 http request GET https://registry.npmjs.org/sails-mongo
22 http 304 https://registry.npmjs.org/sails-mongo
23 silly get cb [ 304,
23 silly get   { date: 'Sat, 14 Feb 2015 22:14:52 GMT',
23 silly get     server: 'Apache',
23 silly get     via: '1.1 varnish',
23 silly get     'last-modified': 'Sat, 14 Feb 2015 22:14:53 GMT',
23 silly get     'cache-control': 'max-age=60',
23 silly get     etag: '"6MBOB9V7EJ301Q92A18DZFB4Z"',
23 silly get     age: '0',
23 silly get     'x-served-by': 'cache-fra1241-FRA',
23 silly get     'x-cache': 'HIT',
23 silly get     'x-cache-hits': '1',
23 silly get     'x-timer': 'S1423952092.889863,VS0,VE419',
23 silly get     vary: 'Accept',
23 silly get     'content-length': '0',
23 silly get     'keep-alive': 'timeout=10, max=50',
23 silly get     connection: 'Keep-Alive' } ]
24 verbose etag https://registry.npmjs.org/sails-mongo from cache
25 verbose get saving sails-mongo to /home/echorohit/.npm/registry.npmjs.org/sails-mongo/.cache.json
26 silly addNameRange number 2 { name: 'sails-mongo', range: '*', hasData: true }
27 silly addNameRange versions [ 'sails-mongo',
27 silly addNameRange   [ '0.0.1',
27 silly addNameRange     '0.0.2',
27 silly addNameRange     '0.0.3',
27 silly addNameRange     '0.9.0',
27 silly addNameRange     '0.9.1',
27 silly addNameRange     '0.9.2',
27 silly addNameRange     '0.9.3',
27 silly addNameRange     '0.9.4',
27 silly addNameRange     '0.9.5',
27 silly addNameRange     '0.9.6',
27 silly addNameRange     '0.9.7',
27 silly addNameRange     '0.10.0-rc1',
27 silly addNameRange     '0.10.0-rc2',
27 silly addNameRange     '0.10.0-rc3',
27 silly addNameRange     '0.9.8',
27 silly addNameRange     '0.10.0-rc4',
27 silly addNameRange     '0.10.0-rc5',
27 silly addNameRange     '0.10.1',
27 silly addNameRange     '0.10.2',
27 silly addNameRange     '0.10.3',
27 silly addNameRange     '0.10.4',
27 silly addNameRange     '0.10.5' ] ]
28 verbose addNamed sails-mongo@0.10.5
29 silly addNamed semver.valid 0.10.5
30 silly addNamed semver.validRange 0.10.5
31 silly cache afterAdd sails-mongo@0.10.5
32 verbose afterAdd /home/echorohit/.npm/sails-mongo/0.10.5/package/package.json not in flight; writing
33 verbose afterAdd /home/echorohit/.npm/sails-mongo/0.10.5/package/package.json written
34 silly install resolved [ { name: 'sails-mongo',
34 silly install resolved     version: '0.10.5',
34 silly install resolved     description: 'Mongo DB adapter for Sails.js',
34 silly install resolved     main: './lib/adapter.js',
34 silly install resolved     scripts: { test: 'make test' },
34 silly install resolved     keywords: [ 'mongo', 'orm', 'waterline', 'sails' ],
34 silly install resolved     contributors: [ [Object], [Object], [Object], [Object] ],
34 silly install resolved     license: 'MIT',
34 silly install resolved     repository:
34 silly install resolved      { type: 'git',
34 silly install resolved        url: 'git://github.com/balderdashy/sails-mongo.git' },
34 silly install resolved     dependencies:
34 silly install resolved      { async: '~0.8.0',
34 silly install resolved        lodash: '~2.4.1',
34 silly install resolved        mongodb: '1.4.26',
34 silly install resolved        'waterline-errors': '~0.10.0',
34 silly install resolved        'waterline-cursor': '~0.0.5' },
34 silly install resolved     devDependencies:
34 silly install resolved      { mocha: '*',
34 silly install resolved        'waterline-adapter-tests': '~0.10.0',
34 silly install resolved        'captains-log': '~0.11.1' },
34 silly install resolved     waterlineAdapter: { waterlineVersion: '~0.10.0', interfaces: [Object] },
34 silly install resolved     gitHead: '310ebc2870fe26f6084973c66bc63e9154273237',
34 silly install resolved     bugs: { url: 'https://github.com/balderdashy/sails-mongo/issues' },
34 silly install resolved     homepage: 'https://github.com/balderdashy/sails-mongo',
34 silly install resolved     _id: 'sails-mongo@0.10.5',
34 silly install resolved     _shasum: 'c605e6d8153ba16587692c70df4c2fa8ef2a006a',
34 silly install resolved     _from: 'sails-mongo@*',
34 silly install resolved     _npmVersion: '1.4.28',
34 silly install resolved     _npmUser: { name: 'particlebanana', email: 'particlebanana@gmail.com' },
34 silly install resolved     maintainers: [ [Object], [Object], [Object], [Object] ],
34 silly install resolved     dist:
34 silly install resolved      { shasum: 'c605e6d8153ba16587692c70df4c2fa8ef2a006a',
34 silly install resolved        tarball: 'http://registry.npmjs.org/sails-mongo/-/sails-mongo-0.10.5.tgz' },
34 silly install resolved     directories: {},
34 silly install resolved     _resolved: 'https://registry.npmjs.org/sails-mongo/-/sails-mongo-0.10.5.tgz',
34 silly install resolved     readme: 'ERROR: No README data found!' } ]
35 info install sails-mongo@0.10.5 into /home/echorohit/rediwala
36 info installOne sails-mongo@0.10.5
37 verbose installOne of sails-mongo to /home/echorohit/rediwala not in flight; installing
38 warn locking Error: EACCES, open '/home/echorohit/.npm/_locks/sails-mongo-851c37437689533a.lock.STALE'
38 warn locking     at Error (native)
38 warn locking  /home/echorohit/.npm/_locks/sails-mongo-851c37437689533a.lock failed { [Error: EACCES, open '/home/echorohit/.npm/_locks/sails-mongo-851c37437689533a.lock.STALE']
38 warn locking   errno: -13,
38 warn locking   code: 'EACCES',
38 warn locking   path: '/home/echorohit/.npm/_locks/sails-mongo-851c37437689533a.lock.STALE' }
39 verbose stack Error: Attempt to unlock /home/echorohit/rediwala/node_modules/sails-mongo, which hasn't been locked
39 verbose stack     at unlock (/usr/local/lib/node_modules/npm/lib/utils/locker.js:66:11)
39 verbose stack     at cb (/usr/local/lib/node_modules/npm/lib/install.js:929:5)
39 verbose stack     at /usr/local/lib/node_modules/npm/lib/install.js:933:20
39 verbose stack     at /usr/local/lib/node_modules/npm/lib/utils/locker.js:40:9
39 verbose stack     at cb (/usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:149:38)
39 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:227:24
39 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:177:38
39 verbose stack     at FSReqWrap.oncomplete (fs.js:99:15)
40 verbose cwd /home/echorohit/rediwala
41 error Linux 3.13.0-45-generic
42 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "sails-mongo"
43 error node v0.12.0
44 error npm  v2.5.1
45 error Attempt to unlock /home/echorohit/rediwala/node_modules/sails-mongo, which hasn't been locked
46 error If you need help, you may report this error at:
46 error     <http://github.com/npm/npm/issues>
47 verbose exit [ 1, true ]
```

**Comment by smikes** [comment]
We've been seeing a few instances of this error and it seems to be that there are files in your `~/.npm/_locks` directory that your user doesn't have permission to delete.

Can you try this:
```
sudo chown -R $(whoami) ~/.npm/_locks
```

to restore your permissions over the lock directory and its contents?

Thanks!

**Comment by huphtur** [comment]
@smikes I experienced a similar _locks error which prevented me from running `npm update`. The command you provided fixed that. 

Thank you.

**Comment by echorohit** [comment]
@smikes  Thank you. Its working now.

**Comment by othiym23** [comment]
Closing as resolved.
