### ISSUE TITLE
npm install problem with webshot / cross-spawn

### ISSUE THREAD

**Issue by heyimlance** [npm/npm#7398]
npm WARN package.json screenshot@0.1.0 'repositories' (plural) Not supported.
npm WARN package.json Please pick one as the 'repository' field
npm http GET https://registry.npmjs.org/webshot
npm http 200 https://registry.npmjs.org/webshot
npm http GET https://registry.npmjs.org/graceful-fs
npm http GET https://registry.npmjs.org/cross-spawn
npm http GET https://registry.npmjs.org/phantomjs
npm http GET https://registry.npmjs.org/tmp
npm http 304 https://registry.npmjs.org/cross-spawn
npm http 304 https://registry.npmjs.org/graceful-fs
npm http 304 https://registry.npmjs.org/phantomjs
npm http 304 https://registry.npmjs.org/tmp
npm ERR! Error: No compatible version found: cross-spawn@'^0.2.3'
npm ERR! Valid install targets:
npm ERR! ["0.1.0","0.1.1","0.1.2","0.1.3","0.1.4","0.1.5","0.1.6","0.1.7","0.2.0","0.2.1","0.2.2","0.2.3","0.2.4","0.2.5","0.2.6"]
npm ERR!     at installTargetsError (/service/app/node_modules/npm/lib/cache.js:719:10)
npm ERR!     at /service/app/node_modules/npm/lib/cache.js:641:10
npm ERR!     at saved (/service/app/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 2.6.32-358.6.2.el6.x86_64
npm ERR! command "/service/app/node-v0.10.12/bin/node" "/usr/local/bin/npm" "install" "webshot"
npm ERR! cwd /home/lance
npm ERR! node -v v0.10.12
npm ERR! npm -v 1.2.32
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/lance/npm-debug.log
npm ERR! not ok code 0

**Comment by heyimlance** [comment]
This seems to be a problem with my environment, thanks!
