### ISSUE TITLE
npm error on every action

### ISSUE THREAD

**Issue by merinodesign** [npm/npm#7399]
Hi,

I got the following error, whatever I used to install. This is the log-file:
```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'install', '-g', 'bower' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 verbose stack Error: Cannot find module '../utils/fetch.js'
4 verbose stack     at Function.Module._resolveFilename (module.js:336:15)
4 verbose stack     at Function.Module._load (module.js:278:25)
4 verbose stack     at Module.require (module.js:365:17)
4 verbose stack     at require (module.js:384:17)
4 verbose stack     at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/cache/add-remote-tarball.js:8:13)
4 verbose stack     at Module._compile (module.js:460:26)
4 verbose stack     at Object.Module._extensions..js (module.js:478:10)
4 verbose stack     at Module.load (module.js:355:32)
4 verbose stack     at Function.Module._load (module.js:310:12)
4 verbose stack     at Module.require (module.js:365:17)
4 verbose stack     at require (module.js:384:17)
5 verbose cwd /Users/sebastiansimon
6 error Darwin 14.0.0
7 error argv "node" "/usr/local/bin/npm" "install" "-g" "bower"
8 error node v0.12.0
9 error npm  v2.5.1
10 error code MODULE_NOT_FOUND
11 error Cannot find module '../utils/fetch.js'
12 error If you need help, you may report this error at:
12 error     <http://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]
 ```
Any ideas?

**Comment by smikes** [comment]
It looks like somehow your installation of `npm` was damaged.  Can you try fixing it -- either by reinstalling `node` or with this command:

```
curl -L http://npmjs.org/install.sh | sudo sh
```

**Comment by aryPutradi** [comment]
Hi smike
I was upgrade the latest version of node but still error.
here's the screenshot
![npm](https://cloud.githubusercontent.com/assets/11155785/6324381/f9f5e202-bb6b-11e4-985a-1dd9620f3752.JPG)

**Comment by KenanY** [comment]
@aryPutradi That looks like an issue with your internet connection (as the error message states). Are you behind a proxy?

**Comment by smikes** [comment]
Are you running on Windows or OSX?  The first log is from OSX Darwin, the screenshot is from Windows.

**Comment by aryPutradi** [comment]
@KenanY I didn't know if i am behind proxy, how did i fix it?
@smikes I am running on windows 7

**Comment by smikes** [comment]
Sorry, I didn't notice that OP and @aryPutradi were different.

**Comment by aryPutradi** [comment]
how did i fix it?

**Comment by merinodesign** [comment]
@smikes: I reinstalled node and now it works perfect - Thank you.
