### ISSUE TITLE
Node Error in Cryptography

### ISSUE THREAD

**Issue by ArcanaMagus** [npm/npm#7401]
A particular error may arise when i call 

npm [options/features] (arguments) {conditions}

in any context the global options seem defunct: i will paste code below:
```
info it worked if it ends with ok
verbose cli [ 'node', '/usr/local/bin/npm', 'install', '-g', 'javascripting' ]
info using npm@1.1.24
info using node@v0.6.19
verbose config file /root/.npmrc
verbose config file /usr/local/etc/npmrc
verbose config file /usr/local/lib/node_modules/npm/npmrc
ERR! Error: node.js not compiled with openssl crypto support.
ERR!     at tls.js:50:9
ERR!     at NativeModule.compile (node.js:542:5)
ERR!     at Function.require (node.js:510:18)
ERR!     at Function._load (module.js:296:25)
ERR!     at Module.require (module.js:359:17)
ERR!     at require (module.js:375:17)
ERR!     at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/re$
ERR!     at Module._compile (module.js:446:26)
ERR!     at Object..js (module.js:464:10)
ERR!     at Module.load (module.js:353:31)
ERR! You may report this log at:
ERR!     at Module.load (module.js:353:31)
ERR! You may report this log at:
ERR!     <http://github.com/isaacs/npm/issues>
ERR! or email it to:
ERR!     <npm-@googlegroups.com>
ERR!
ERR! System Linux 3.14-kali1-amd64
ERR! command "node" "/usr/local/bin/npm" "install" "-g" "javascripting"
ERR! cwd /root/node
ERR! node -v v0.6.19
ERR! npm -v 1.1.24
ERR! message node.js not compiled with openssl crypto support.
verbose exit [ 1, true ]
```

**Comment by othiym23** [comment]
```
ERR! node -v v0.6.19
ERR! npm -v 1.1.24
```

Your versions of Node and npm are heartbreakingly old, and completely unsupported. The latest version of Node is 0.12.0, and the latest version of npm (packaged with it) is `npm@2.5.1`. [Here's how](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-node) to upgrade.
