### ISSUE TITLE
Error: Invalid version: "0,0.1"

### ISSUE THREAD

**Issue by SoloChris14** [npm/npm#7412]
```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'install' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 error install Couldn't read dependencies
5 verbose stack Error: Invalid version: "0,0.1"
5 verbose stack     at Object.module.exports.fixVersionField (/usr/local/lib/node_modules/npm/node_modules/normalize-package-data/lib/fixer.js:190:13)
5 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/normalize-package-data/lib/normalize.js:30:38
5 verbose stack     at Array.forEach (native)
5 verbose stack     at normalize (/usr/local/lib/node_modules/npm/node_modules/normalize-package-data/lib/normalize.js:29:15)
5 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:342:33)
5 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:126:33)
5 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:331:40
5 verbose stack     at evalmachine.<anonymous>:336:14
5 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:102:5
5 verbose stack     at FSReqWrap.oncomplete (evalmachine.<anonymous>:99:15)
6 verbose cwd /Users/Chris/Desktop/sassycompass
7 error Darwin 14.1.0
8 error argv "node" "/usr/local/bin/npm" "install"
9 error node v0.12.0
10 error npm  v2.5.1
11 error Invalid version: "0,0.1"
12 error If you need help, you may report this error at:
12 error     <http://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
@SoloChris14 

```
5 verbose stack Error: Invalid version: "0,0.1"
```

Commas aren't allowed in Semantic Versioning. Perhaps you meant to have `"0.0.1"` in your `"version"` field of your `package.json`?

**Comment by othiym23** [comment]
What @KenanY said – `npm help semver` will help you figure out what is and isn't a valid version number in npm. But maybe this is a simple typo? Either way, closing this issue as resolved.
