### ISSUE TITLE
npm error ENOENT when installing github dependency

### ISSUE THREAD

**Issue by chrisdarroch** [npm/npm#7431]
I've got a `package.json` that lists the following dependencies:

```
  "dependencies": {
    "jsdoc": "3.3.0-beta1",
    "jsdoc-baseline": "git://github.com/hegemonic/baseline.git"
  },
  "devDependencies": {
    "eslint": "~0.11.0"
  },
  "engines": {
    "node": ">=0.10"
  },
```

On my CI server, I run `npm cache clean`, then `npm install --production`.

Every run has resulted in some NPM error, seemingly when it attempts to install the `jsdoc-baseline` module from github.

Here's an example:

```
npm http GET https://registry.npmjs.org/jsdoc/3.3.0-beta1
npm http 200 https://registry.npmjs.org/jsdoc/3.3.0-beta1
npm http GET https://registry.npmjs.org/jsdoc/-/jsdoc-3.3.0-beta1.tgz
npm http 200 https://registry.npmjs.org/jsdoc/-/jsdoc-3.3.0-beta1.tgz
npm http GET https://registry.npmjs.org/deep-extend
npm http GET https://registry.npmjs.org/escape-string-regexp
npm http GET https://registry.npmjs.org/gulp-eslint
npm http GET https://registry.npmjs.org/handlebars
npm http GET https://registry.npmjs.org/handlebars-layouts
npm http GET https://registry.npmjs.org/intl
npm http GET https://registry.npmjs.org/intl-messageformat
npm http GET https://registry.npmjs.org/js-beautify
npm http GET https://registry.npmjs.org/js-yaml
npm http GET https://registry.npmjs.org/spdx-license-list
npm http GET https://registry.npmjs.org/underscore-contrib
npm http 200 https://registry.npmjs.org/escape-string-regexp
npm http GET https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.3.tgz
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/catharsis
npm http 200 https://registry.npmjs.org/deep-extend
npm http GET https://registry.npmjs.org/js2xmlparser
npm http GET https://registry.npmjs.org/marked
npm http GET https://registry.npmjs.org/requizzle
npm http GET https://registry.npmjs.org/strip-json-comments
npm http GET https://registry.npmjs.org/underscore
npm http GET https://registry.npmjs.org/wrench
npm http GET https://github.com/ariya/esprima/tarball/49a2eccb243f29bd653b11e9419241a9d726af7c
npm http GET https://github.com/hegemonic/taffydb/tarball/7d100bcee0e997ee4977e273cdce60bd8933050e
npm http GET https://registry.npmjs.org/deep-extend/-/deep-extend-0.3.2.tgz
npm http 200 https://registry.npmjs.org/handlebars
npm http GET https://registry.npmjs.org/handlebars/-/handlebars-2.0.0.tgz
npm http 200 https://registry.npmjs.org/handlebars-layouts
npm http GET https://registry.npmjs.org/handlebars-layouts/-/handlebars-layouts-1.0.0.tgz
npm http 200 https://registry.npmjs.org/js-yaml
npm http GET https://registry.npmjs.org/js-yaml/-/js-yaml-3.2.7.tgz
npm http 200 https://registry.npmjs.org/spdx-license-list
npm http GET https://registry.npmjs.org/spdx-license-list/-/spdx-license-list-1.1.0.tgz
npm http 200 https://github.com/hegemonic/taffydb/tarball/7d100bcee0e997ee4977e273cdce60bd8933050e
npm http 200 https://github.com/ariya/esprima/tarball/49a2eccb243f29bd653b11e9419241a9d726af7c
npm http 200 https://registry.npmjs.org/js-beautify
npm http GET https://registry.npmjs.org/js-beautify/-/js-beautify-1.5.4.tgz
npm http 200 https://registry.npmjs.org/intl
npm http 200 https://registry.npmjs.org/gulp-eslint
npm http 200 https://registry.npmjs.org/underscore-contrib
npm http 200 https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.3.tgz
npm http GET https://registry.npmjs.org/intl/-/intl-0.1.4.tgz
npm http GET https://registry.npmjs.org/gulp-eslint/-/gulp-eslint-0.2.2.tgz
npm http GET https://registry.npmjs.org/underscore-contrib/-/underscore-contrib-0.3.0.tgz
npm http 200 https://registry.npmjs.org/intl-messageformat
npm http GET https://registry.npmjs.org/intl-messageformat/-/intl-messageformat-1.0.4.tgz
npm http 200 https://registry.npmjs.org/requizzle
npm http 200 https://registry.npmjs.org/js2xmlparser
npm http GET https://registry.npmjs.org/requizzle/-/requizzle-0.2.1.tgz
npm http GET https://registry.npmjs.org/js2xmlparser/-/js2xmlparser-0.1.7.tgz
npm http 200 https://registry.npmjs.org/strip-json-comments
npm http GET https://registry.npmjs.org/strip-json-comments/-/strip-json-comments-1.0.2.tgz
npm http 200 https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/async/-/async-0.9.0.tgz
npm http 200 https://registry.npmjs.org/underscore
npm http 200 https://registry.npmjs.org/marked
npm http 200 https://registry.npmjs.org/catharsis
npm http GET https://registry.npmjs.org/underscore/-/underscore-1.7.0.tgz
npm http 200 https://registry.npmjs.org/deep-extend/-/deep-extend-0.3.2.tgz
npm http GET https://registry.npmjs.org/marked/-/marked-0.3.3.tgz
npm http GET https://registry.npmjs.org/catharsis/-/catharsis-0.8.6.tgz
npm http 200 https://registry.npmjs.org/wrench
npm http 200 https://registry.npmjs.org/handlebars/-/handlebars-2.0.0.tgz
npm http GET https://registry.npmjs.org/wrench/-/wrench-1.5.8.tgz
npm http 200 https://registry.npmjs.org/handlebars-layouts/-/handlebars-layouts-1.0.0.tgz
npm http 200 https://registry.npmjs.org/gulp-eslint/-/gulp-eslint-0.2.2.tgz
npm http 200 https://registry.npmjs.org/js-yaml/-/js-yaml-3.2.7.tgz
npm http 200 https://registry.npmjs.org/spdx-license-list/-/spdx-license-list-1.1.0.tgz
npm http 200 https://registry.npmjs.org/intl/-/intl-0.1.4.tgz
npm http 200 https://registry.npmjs.org/js-beautify/-/js-beautify-1.5.4.tgz
npm http 200 https://registry.npmjs.org/intl-messageformat/-/intl-messageformat-1.0.4.tgz
npm http 200 https://registry.npmjs.org/requizzle/-/requizzle-0.2.1.tgz
npm http 200 https://registry.npmjs.org/underscore-contrib/-/underscore-contrib-0.3.0.tgz
npm http 200 https://registry.npmjs.org/js2xmlparser/-/js2xmlparser-0.1.7.tgz
npm http 200 https://registry.npmjs.org/strip-json-comments/-/strip-json-comments-1.0.2.tgz
npm http 200 https://registry.npmjs.org/async/-/async-0.9.0.tgz
npm http 200 https://registry.npmjs.org/underscore/-/underscore-1.7.0.tgz
npm http 200 https://registry.npmjs.org/marked/-/marked-0.3.3.tgz
npm http 200 https://registry.npmjs.org/catharsis/-/catharsis-0.8.6.tgz
npm http 200 https://registry.npmjs.org/wrench/-/wrench-1.5.8.tgz
npm http GET https://registry.npmjs.org/underscore/-/underscore-1.6.0.tgz
npm http 200 https://registry.npmjs.org/underscore/-/underscore-1.6.0.tgz
npm http GET https://registry.npmjs.org/underscore/1.6.0
npm http 200 https://registry.npmjs.org/underscore/1.6.0
npm http GET https://registry.npmjs.org/underscore/-/underscore-1.6.0.tgz
npm http 200 https://registry.npmjs.org/underscore/-/underscore-1.6.0.tgz
npm http GET https://registry.npmjs.org/map-stream
npm http GET https://registry.npmjs.org/through
npm http GET https://registry.npmjs.org/eslint
npm http GET https://registry.npmjs.org/gulp-util
npm http 200 https://registry.npmjs.org/map-stream
npm http 200 https://registry.npmjs.org/through
npm ERR! Error: ENOENT, lstat '/<<build_dir>>/node_modules/jsdoc-baseline/node_modules/spdx-license-list/licenses/BSD-2-Clause.txt'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.2.0-48-virtual
npm ERR! command "/opt/nodejs/node-v0.10.3-linux-x64/bin/node" "/opt/nodejs/node-v0.10.3-linux-x64/bin/npm" "install" "--production"
npm ERR! cwd /<<build_dir>>
npm ERR! node -v v0.10.3
npm ERR! npm -v 1.2.17
npm ERR! path /<<build_dir>>/node_modules/jsdoc-baseline/node_modules/spdx-license-list/licenses/BSD-2-Clause.txt
npm ERR! fstream_path /<<build_dir>>/node_modules/jsdoc-baseline/node_modules/spdx-license-list/licenses/BSD-2-Clause.txt
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /opt/nodejs/node-v0.10.3-linux-x64/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm http 200 https://registry.npmjs.org/gulp-util
npm ERR! error rolling back Error: ENOTEMPTY, rmdir '/<<build_dir>>/node_modules/jsdoc-baseline/node_modules/js-beautify'
npm ERR! error rolling back  jsdoc-baseline@0.0.1-dev { [Error: ENOTEMPTY, rmdir '/<<build_dir>>/node_modules/jsdoc-baseline/node_modules/js-beautify']
npm ERR! error rolling back   errno: 53,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   path: '/<<build_dir>>/node_modules/jsdoc-baseline/node_modules/js-beautify' }
npm ERR! Error: No compatible version found: map-stream@'^0.1.0'
npm ERR! Valid install targets:
npm ERR! ["0.0.1","0.0.2","0.0.3","0.0.4","0.1.0","0.0.5"]
npm ERR!     at installTargetsError (/opt/nodejs/node-v0.10.3-linux-x64/lib/node_modules/npm/lib/cache.js:685:10)
npm ERR!     at /opt/nodejs/node-v0.10.3-linux-x64/lib/node_modules/npm/lib/cache.js:607:10
npm ERR!     at saved (/opt/nodejs/node-v0.10.3-linux-x64/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.2.0-48-virtual
npm ERR! command "/opt/nodejs/node-v0.10.3-linux-x64/bin/node" "/opt/nodejs/node-v0.10.3-linux-x64/bin/npm" "install" "--production"
npm ERR! cwd /<<build_dir>>
npm ERR! node -v v0.10.3
npm ERR! npm -v 1.2.17
npm ERR! Error: ENOENT, lstat '/<<build_dir>>/node_modules/jsdoc-baseline/node_modules/handlebars/coverage/lcov-report/dist/cjs/handlebars/compiler/compiler.js.html'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.2.0-48-virtual
npm ERR! command "/opt/nodejs/node-v0.10.3-linux-x64/bin/node" "/opt/nodejs/node-v0.10.3-linux-x64/bin/npm" "install" "--production"
npm ERR! cwd /<<build_dir>>
npm ERR! node -v v0.10.3
npm ERR! npm -v 1.2.17
npm ERR! path /<<build_dir>>/node_modules/jsdoc-baseline/node_modules/handlebars/coverage/lcov-report/dist/cjs/handlebars/compiler/compiler.js.html
npm ERR! fstream_path /<<build_dir>>/node_modules/jsdoc-baseline/node_modules/handlebars/coverage/lcov-report/dist/cjs/handlebars/compiler/compiler.js.html
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /opt/nodejs/node-v0.10.3-linux-x64/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat '/<<build_dir>>/node_modules/jsdoc-baseline/node_modules/intl-messageformat/dist/intl-messageformat-with-locales.js.map'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.2.0-48-virtual
npm ERR! command "/opt/nodejs/node-v0.10.3-linux-x64/bin/node" "/opt/nodejs/node-v0.10.3-linux-x64/bin/npm" "install" "--production"
npm ERR! cwd /<<build_dir>>
npm ERR! node -v v0.10.3
npm ERR! npm -v 1.2.17
npm ERR! path /<<build_dir>>/node_modules/jsdoc-baseline/node_modules/intl-messageformat/dist/intl-messageformat-with-locales.js.map
npm ERR! fstream_path /<<build_dir>>/node_modules/jsdoc-baseline/node_modules/intl-messageformat/dist/intl-messageformat-with-locales.js.map
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /opt/nodejs/node-v0.10.3-linux-x64/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat '/<<build_dir>>/node_modules/jsdoc-baseline/node_modules/underscore-contrib/test/vendor/jquery.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.2.0-48-virtual
npm ERR! command "/opt/nodejs/node-v0.10.3-linux-x64/bin/node" "/opt/nodejs/node-v0.10.3-linux-x64/bin/npm" "install" "--production"
npm ERR! cwd /<<build_dir>>
npm ERR! node -v v0.10.3
npm ERR! npm -v 1.2.17
npm ERR! path /<<build_dir>>/node_modules/jsdoc-baseline/node_modules/underscore-contrib/test/vendor/jquery.js
npm ERR! fstream_path /<<build_dir>>/node_modules/jsdoc-baseline/node_modules/underscore-contrib/test/vendor/jquery.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /opt/nodejs/node-v0.10.3-linux-x64/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat '/<<build_dir>>/node_modules/jsdoc-baseline/node_modules/intl/Intl.complete.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.2.0-48-virtual
npm ERR! command "/opt/nodejs/node-v0.10.3-linux-x64/bin/node" "/opt/nodejs/node-v0.10.3-linux-x64/bin/npm" "install" "--production"
npm ERR! cwd /<<build_dir>>
npm ERR! node -v v0.10.3
npm ERR! npm -v 1.2.17
npm ERR! path /<<build_dir>>/node_modules/jsdoc-baseline/node_modules/intl/Intl.complete.js
npm ERR! fstream_path /<<build_dir>>/node_modules/jsdoc-baseline/node_modules/intl/Intl.complete.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /opt/nodejs/node-v0.10.3-linux-x64/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm http 200 https://registry.npmjs.org/eslint
npm http GET https://registry.npmjs.org/argparse
npm http GET https://registry.npmjs.org/esprima
npm http 200 https://registry.npmjs.org/esprima
npm http 200 https://registry.npmjs.org/argparse
npm http GET https://registry.npmjs.org/esprima/-/esprima-2.0.0.tgz
npm http GET https://registry.npmjs.org/argparse/-/argparse-1.0.1.tgz
npm http 200 https://registry.npmjs.org/esprima/-/esprima-2.0.0.tgz
npm http 200 https://registry.npmjs.org/argparse/-/argparse-1.0.1.tgz
npm http GET https://registry.npmjs.org/lodash
npm http GET https://registry.npmjs.org/sprintf-js
npm http 200 https://registry.npmjs.org/sprintf-js
npm http GET https://registry.npmjs.org/sprintf-js/-/sprintf-js-1.0.2.tgz
npm http 200 https://registry.npmjs.org/sprintf-js/-/sprintf-js-1.0.2.tgz
npm http 200 https://registry.npmjs.org/lodash
npm http GET https://registry.npmjs.org/lodash/-/lodash-3.2.0.tgz
npm http 200 https://registry.npmjs.org/lodash/-/lodash-3.2.0.tgz
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /<<build_dir>>/npm-debug.log
npm ERR! not ok code 0
```

Each run fails at a comparable spot, I'm just not sure what's going wrong.

**Comment by KenanY** [comment]
@chrisdarroch `npm@1.2.17` is incredibly old and no longer supported. We're on `2.6.0` right now :) You should [update](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm).

**Comment by othiym23** [comment]
As Kenan said, once you upgrade to `npm@2`, the race conditions causing the bugs you're seeing should go away.

Closing as resolved.
