### ISSUE TITLE
SELF_SIGNED_CERT_IN_CHAIN error

### ISSUE THREAD

**Issue by bakumastah** [npm/npm#7439]
I tried everything I could find on the internet. Reinstalling node, updating brew, setting ca=null. I have node v0.12.0 and npm v2.6.0. Any other possible solutions? 

EDIT: Aaaand I just fixed that somehow. I did "npm config set registry http://registry.npmjs.org/" and it's working. Can someone confirm that it's a good solution?

This is my debug log:

```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'install', 'strftime' ]
2 info using npm@2.6.0
3 info using node@v0.12.0
4 verbose node symlink /usr/local/bin/node
5 silly cache add args [ 'strftime', null ]
6 verbose cache add spec strftime
7 silly cache add parsed spec { raw: 'strftime',
7 silly cache add	scope: null,
7 silly cache add	name: 'strftime',
7 silly cache add	rawSpec: '',
7 silly cache add	spec: '*',
7 silly cache add	type: 'range' }
8 verbose addNamed strftime@*
9 silly addNamed semver.valid null
10 silly addNamed semver.validRange *
11 silly addNameRange { name: 'strftime', range: '*', hasData: false }
12 silly mapToRegistry name strftime
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/strftime
16 verbose addNameRange registry:https://registry.npmjs.org/strftime not in flight; fetching
17 verbose request uri https://registry.npmjs.org/strftime
18 verbose request no auth needed
19 info attempt registry request try #1 at 12:28:14
20 verbose request id a56433341ca4c096
21 http request GET https://registry.npmjs.org/strftime
22 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
23 info attempt registry request try #2 at 12:28:25
24 http request GET https://registry.npmjs.org/strftime
25 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
26 info attempt registry request try #3 at 12:29:25
27 http request GET https://registry.npmjs.org/strftime
28 verbose stack Error: self signed certificate in certificate chain
28 verbose stack	 at Error (native)
28 verbose stack	 at TLSSocket.<anonymous> (_tls_wrap.js:927:36)
28 verbose stack	 at TLSSocket.emit (events.js:104:17)
28 verbose stack	 at TLSSocket._finishInit (_tls_wrap.js:458:8)
29 verbose cwd /Users/baku/Daftcode/nodeschool
30 error Darwin 14.1.0
31 error argv "node" "/usr/local/bin/npm" "install" "strftime"
32 error node v0.12.0
33 error npm  v2.6.0
34 error code SELF_SIGNED_CERT_IN_CHAIN
35 error self signed certificate in certificate chain
36 error If you need help, you may report this error at:
36 error	 <http://github.com/npm/npm/issues>
37 verbose exit [ 1, true ]
```

**Comment by smikes** [comment]
It's an .. adequate solution.  It leaves you vulnerable to in-the-middle attacks against the software you are downloading, which some people consider a theoretical threat, and others a practical one.

Is it possible that you have installed a self-signed certificate on your machine, or are behind an SSL-intercepting proxy?

**Comment by bakumastah** [comment]
It turned out to be a Kaspersky Antivirus HTTPS protection issue. I turned it off and it's fine now. Thanks for the answer smikes!
