### ISSUE TITLE
error install Couldn't read dependencies

### ISSUE THREAD

**Issue by amartamtech** [npm/npm#7449]
I am getting this error when doing npm install.
My npm-debug.log file is 
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'install' ]
2 info using npm@1.4.21
3 info using node@v0.10.25
4 error install Couldn't read dependencies
5 error Error: Invalid name: "Get Card"
5 error     at ensureValidName (/usr/lib/nodejs/normalize-package-data/lib/fixer.js:284:15)
5 error     at Object.module.exports.fixNameField (/usr/lib/nodejs/normalize-package-data/lib/fixer.js:199:5)
5 error     at /usr/lib/nodejs/normalize-package-data/lib/normalize.js:29:38
5 error     at Array.forEach (native)
5 error     at normalize (/usr/lib/nodejs/normalize-package-data/lib/normalize.js:28:15)
5 error     at final (/usr/lib/nodejs/read-package-json/read-json.js:342:33)
5 error     at then (/usr/lib/nodejs/read-package-json/read-json.js:126:33)
5 error     at /usr/lib/nodejs/read-package-json/read-json.js:266:40
5 error     at evalmachine.<anonymous>:268:14
5 error     at /usr/lib/nodejs/graceful-fs/graceful-fs.js:102:5
6 error If you need help, you may report this *entire* log,
6 error including the npm and node versions, at:
6 error     <http://github.com/npm/npm/issues>
7 error System Linux 3.16.0-23-generic
8 error command "/usr/bin/nodejs" "/usr/bin/npm" "install"
9 error cwd /home/arvind/Projects/MEAN/get-card
10 error node -v v0.10.25
11 error npm -v 1.4.21
12 verbose exit [ 1, true ]
```

Please guide me, How can I resolve it

**Comment by KenanY** [comment]
@amartamtech 

```
5 error Error: Invalid name: "Get Card"
```

Your `"name"` field can't have capital letters nor spaces. Changing it to "get-card" should suffice to fix the issue.

**Comment by othiym23** [comment]
Closing as resolved.
