### ISSUE TITLE
cannot publish package to npm

### ISSUE THREAD

**Issue by jherdman** [npm/npm#7453]
For the past two days I've seen the following error when trying to `npm publish` an updated version of my [ember-cli-trackjs](https://github.com/jherdman/ember-cli-trackjs) package:

```
ember-cli-trackjs [master] % npm publish
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! publish Failed PUT 502
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "publish"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1

npm ERR! Unexpected token <
npm ERR! <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
npm ERR! <html><head>
npm ERR! <title>502 Bad Gateway</title>
npm ERR! </head><body>
npm ERR! <h1>Bad Gateway</h1>
npm ERR! <p>The proxy server received an invalid
npm ERR! response from an upstream server.<br />
npm ERR! </p>
npm ERR! </body></html>
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/james/Projects/ember-cli-trackjs/npm-debug.log
```

Where npm-debug.log is as follows:

```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'publish' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 verbose node symlink /usr/local/bin/node
5 verbose publish [ '.' ]
6 silly cache add args [ '.', null ]
7 verbose cache add spec .
8 silly cache add parsed spec { raw: '.',
8 silly cache add   scope: null,
8 silly cache add   name: null,
8 silly cache add   rawSpec: '.',
8 silly cache add   spec: '/Users/james/Projects/ember-cli-trackjs',
8 silly cache add   type: 'directory' }
9 verbose addLocalDirectory /Users/james/.npm/ember-cli-trackjs/0.1.1/package.tgz not in flight; packing
10 verbose tar pack [ '/Users/james/.npm/ember-cli-trackjs/0.1.1/package.tgz',
10 verbose tar pack   '/Users/james/Projects/ember-cli-trackjs' ]
11 verbose tarball /Users/james/.npm/ember-cli-trackjs/0.1.1/package.tgz
12 verbose folder /Users/james/Projects/ember-cli-trackjs
13 info prepublish ember-cli-trackjs@0.1.1
14 verbose addLocalTarball adding from inside cache /Users/james/.npm/ember-cli-trackjs/0.1.1/package.tgz
15 silly cache afterAdd ember-cli-trackjs@0.1.1
16 verbose afterAdd /Users/james/.npm/ember-cli-trackjs/0.1.1/package/package.json not in flight; writing
17 verbose afterAdd /Users/james/.npm/ember-cli-trackjs/0.1.1/package/package.json written
18 silly publish { name: 'ember-cli-trackjs',
18 silly publish   version: '0.1.1',
18 silly publish   description: 'Use TrackJS with your fancy Ember CLI powered application',
18 silly publish   directories: { doc: 'doc', test: 'tests' },
18 silly publish   scripts:
18 silly publish    { start: 'ember server',
18 silly publish      build: 'ember build',
18 silly publish      test: 'ember test' },
18 silly publish   repository:
18 silly publish    { type: 'git',
18 silly publish      url: 'https://github.com/jherdman/ember-cli-trackjs' },
18 silly publish   bugs: { url: 'https://github.com/jherdman/ember-cli-trackjs/issues' },
18 silly publish   engines: { node: '>= 0.10.0' },
18 silly publish   author: { name: 'James F. Herdman', email: 'james.herdman@gmail.com' },
18 silly publish   license: 'MIT',
18 silly publish   devDependencies:
18 silly publish    { 'broccoli-asset-rev': '^2.0.0',
18 silly publish      'broccoli-ember-hbs-template-compiler': '^1.6.1',
18 silly publish      'ember-cli': '0.1.15',
18 silly publish      'ember-cli-6to5': '^3.0.0',
18 silly publish      'ember-cli-app-version': '0.3.1',
18 silly publish      'ember-cli-content-security-policy': '0.3.0',
18 silly publish      'ember-cli-dependency-checker': '0.0.7',
18 silly publish      'ember-cli-ic-ajax': '0.1.1',
18 silly publish      'ember-cli-inject-live-reload': '^1.3.0',
18 silly publish      'ember-cli-qunit': '0.3.7',
18 silly publish      'ember-cli-uglify': '1.0.1',
18 silly publish      'ember-data': '1.0.0-beta.14.1',
18 silly publish      'ember-export-application-global': '^1.0.2',
18 silly publish      express: '^4.8.5',
18 silly publish      glob: '^4.0.5' },
18 silly publish   keywords: [ 'ember-addon', 'trackjs' ],
18 silly publish   'ember-addon': { configPath: 'tests/dummy/config' },
18 silly publish   readme: '# ember-cli-trackjs [![Build Status](https://travis-ci.org/jherdman/ember-cli-trackjs.svg)](https://travis-ci.org/jherdman/ember-cli-trackjs)\n\nHandles all of the boilerplate shit you need to use TrackJS in your fancy Ember\napplication.\n\n## Settings\n\nConfigure TrackJS in your application\'s `config/environment.js` file. Please\nsee the [TrackJS documentation](http://docs.trackjs.com/Examples/Developing_Locally)\nfor specific configuration options.\n\n### Example\n\n```javascript\nvar ENV = {\n  trackJs: {\n    addon: {\n      url: "path/to/trackjs.js" // provided by TrackJS\n    },\n    config: {\n      token: "1234567890"\n    }\n  }\n};\n\nif (environment === \'test\') {\n  ENV.trackJs.config.enabled = false;\n}\n```\n\nSee? Pretty much like you\'d expect.\n\n## Usage\n\nA service is exposed on your routes and controllers that you can use to report\nerrors instead of having to use the global `window.trackJs` object.\n\n### Example in a Route\n\n```javascript\nexport default {\n  beforeModel: function () {\n    this.trackjs.track(\'oh, snap. something bad happened\');\n  }\n};\n```\n\n### Example in a Controller\n\n```javascript\nexport default Ember.Controller.extend({\n  reportSomethingForSomeReason: function () {\n    this.trackjs.track(\'oh, snap. something bad happened\');\n  }.on(\'init\')\n});\n```\n\n## Installation\n\n```\nnpm install --save-dev ember-cli-content-security-policy\n```\n\n## Running Tests\n\n* `ember test`\n* `ember test --server`\n\n## Building\n\n* `ember build`\n',
18 silly publish   readmeFilename: 'README.md',
18 silly publish   gitHead: 'a30d3358f946ccb2520baa6d6c5db209f2881f7e',
18 silly publish   homepage: 'https://github.com/jherdman/ember-cli-trackjs',
18 silly publish   _id: 'ember-cli-trackjs@0.1.1',
18 silly publish   _shasum: 'b51eef6c50c89c7ad0d6b9163357cb4727294353',
18 silly publish   _from: '.' }
19 silly mapToRegistry name ember-cli-trackjs
20 silly mapToRegistry using default registry
21 silly mapToRegistry registry https://registry.npmjs.org/
22 silly mapToRegistry uri https://registry.npmjs.org/ember-cli-trackjs
23 verbose publish registryBase https://registry.npmjs.org/
24 silly publish uploading /Users/james/.npm/ember-cli-trackjs/0.1.1/package.tgz
25 verbose request uri https://registry.npmjs.org/ember-cli-trackjs
26 verbose request sending authorization for write operation
27 info attempt registry request try #1 at 9:03:57 AM
28 verbose request id b3f810e43084f423
29 http request PUT https://registry.npmjs.org/ember-cli-trackjs
30 http 502 https://registry.npmjs.org/ember-cli-trackjs
31 verbose bad json <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
31 verbose bad json <html><head>
31 verbose bad json <title>502 Bad Gateway</title>
31 verbose bad json </head><body>
31 verbose bad json <h1>Bad Gateway</h1>
31 verbose bad json <p>The proxy server received an invalid
31 verbose bad json response from an upstream server.<br />
31 verbose bad json </p>
31 verbose bad json </body></html>
32 error registry error parsing json
33 info retry will retry, error on last attempt: SyntaxError: Unexpected token <
33 info retry <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
33 info retry <html><head>
33 info retry <title>502 Bad Gateway</title>
33 info retry </head><body>
33 info retry <h1>Bad Gateway</h1>
33 info retry <p>The proxy server received an invalid
33 info retry response from an upstream server.<br />
33 info retry </p>
33 info retry </body></html>
34 info attempt registry request try #2 at 9:04:58 AM
35 http request PUT https://registry.npmjs.org/ember-cli-trackjs
36 http 502 https://registry.npmjs.org/ember-cli-trackjs
37 verbose bad json <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
37 verbose bad json <html><head>
37 verbose bad json <title>502 Bad Gateway</title>
37 verbose bad json </head><body>
37 verbose bad json <h1>Bad Gateway</h1>
37 verbose bad json <p>The proxy server received an invalid
37 verbose bad json response from an upstream server.<br />
37 verbose bad json </p>
37 verbose bad json </body></html>
38 error registry error parsing json
39 info retry will retry, error on last attempt: SyntaxError: Unexpected token <
39 info retry <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
39 info retry <html><head>
39 info retry <title>502 Bad Gateway</title>
39 info retry </head><body>
39 info retry <h1>Bad Gateway</h1>
39 info retry <p>The proxy server received an invalid
39 info retry response from an upstream server.<br />
39 info retry </p>
39 info retry </body></html>
40 info attempt registry request try #3 at 9:06:49 AM
41 http request PUT https://registry.npmjs.org/ember-cli-trackjs
42 http 502 https://registry.npmjs.org/ember-cli-trackjs
43 verbose bad json <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
43 verbose bad json <html><head>
43 verbose bad json <title>502 Bad Gateway</title>
43 verbose bad json </head><body>
43 verbose bad json <h1>Bad Gateway</h1>
43 verbose bad json <p>The proxy server received an invalid
43 verbose bad json response from an upstream server.<br />
43 verbose bad json </p>
43 verbose bad json </body></html>
44 error registry error parsing json
45 verbose headers { date: 'Wed, 25 Feb 2015 14:06:49 GMT',
45 verbose headers   server: 'Apache',
45 verbose headers   'content-length': '232',
45 verbose headers   'keep-alive': 'timeout=10, max=50',
45 verbose headers   connection: 'Keep-Alive',
45 verbose headers   'content-type': 'text/html; charset=iso-8859-1' }
46 verbose request invalidating /Users/james/.npm/registry.npmjs.org/ember-cli-trackjs on PUT
47 error publish Failed PUT 502
48 verbose stack SyntaxError: Unexpected token <
48 verbose stack <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
48 verbose stack <html><head>
48 verbose stack <title>502 Bad Gateway</title>
48 verbose stack </head><body>
48 verbose stack <h1>Bad Gateway</h1>
48 verbose stack <p>The proxy server received an invalid
48 verbose stack response from an upstream server.<br />
48 verbose stack </p>
48 verbose stack </body></html>
48 verbose stack
48 verbose stack     at Object.parse (native)
48 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:205:23)
48 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:178:14)
48 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:344:22)
48 verbose stack     at Request.emit (events.js:110:17)
48 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1239:14)
48 verbose stack     at Request.emit (events.js:129:20)
48 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1187:12)
48 verbose stack     at IncomingMessage.emit (events.js:129:20)
48 verbose stack     at _stream_readable.js:908:16
49 verbose cwd /Users/james/Projects/ember-cli-trackjs
50 error Darwin 14.1.0
51 error argv "node" "/usr/local/bin/npm" "publish"
52 error node v0.12.0
53 error npm  v2.5.1
54 error Unexpected token <
54 error <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
54 error <html><head>
54 error <title>502 Bad Gateway</title>
54 error </head><body>
54 error <h1>Bad Gateway</h1>
54 error <p>The proxy server received an invalid
54 error response from an upstream server.<br />
54 error </p>
54 error </body></html>
55 error If you need help, you may report this error at:
55 error     <http://github.com/npm/npm/issues>
56 verbose exit [ 1, true ]
```

As near as I can tell I'm not doing anything wrong. I've validated my package.json using [Package.json validator](http://package-json-validator.com/), and everything appears to be okay. I'm stuck.

**Comment by smikes** [comment]
Thanks for the bug report.  

Have you try publishing from a different networks (eg a cafe wifi, home, work) to rule out a network problem?

That's all I can think of for further troubleshooting, so I will ask someone who is more familiar with the registry side to look at this.

**Comment by othiym23** [comment]
The fix for this is as simple as it is stupid (on our part, not yours): run `npm login` again. Due to a fairly convoluted set of circumstances, a 401 response is getting turned into a 50x response, so the code that the npm CLI has to tell you that you're not logged in isn't getting the response it needs. Sorry about that. It's my hope that we'll fix this permanently in the next month or so.

**Comment by jherdman** [comment]
Thank you! That worked like a charm.
