### ISSUE TITLE
Trouble installing bower with command "npm install -g bower" on OSX 10.9.5

### ISSUE THREAD

**Issue by gtick** [npm/npm#7462]
trying to run add platform android to an ionic project and system stated that I needed to install bower.  went to install bower and got errors.

errors were as follows:
```
npm WARN locking Error: EACCES, open '/Users/Gabriel/.npm/_locks/bower-e8debc5417026b57.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/Gabriel/.npm/_locks/bower-e8debc5417026b57.lock failed { [Error: EACCES, open '/Users/Gabriel/.npm/_locks/bower-e8debc5417026b57.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/Gabriel/.npm/_locks/bower-e8debc5417026b57.lock' }
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "bower"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1

npm ERR! Attempt to unlock /usr/local/lib/node_modules/bower, which hasn't been locked
npm ERR! 
```

From the log:
```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'install', '-g', 'bower' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 silly cache add args [ 'bower', null ]
5 verbose cache add spec bower
6 silly cache add parsed spec { raw: 'bower',
6 silly cache add   scope: null,
6 silly cache add   name: 'bower',
6 silly cache add   rawSpec: '',
6 silly cache add   spec: '*',
6 silly cache add   type: 'range' }
7 verbose addNamed bower@*
8 silly addNamed semver.valid null
9 silly addNamed semver.validRange *
10 silly addNameRange { name: 'bower', range: '*', hasData: false }
11 silly mapToRegistry name bower
12 silly mapToRegistry using default registry
13 silly mapToRegistry registry https://registry.npmjs.org/
14 silly mapToRegistry uri https://registry.npmjs.org/bower
15 verbose addNameRange registry:https://registry.npmjs.org/bower not in flight; fetching
16 verbose request uri https://registry.npmjs.org/bower
17 verbose request no auth needed
18 info attempt registry request try #1 at 11:37:36 PM
19 verbose request id 3eb8cb588290a7dd
20 verbose etag "543XPT4YVWJ5F0MDALFWP9WTG"
21 http request GET https://registry.npmjs.org/bower
22 http 304 https://registry.npmjs.org/bower
23 silly get cb [ 304,
23 silly get   { date: 'Thu, 26 Feb 2015 04:37:40 GMT',
23 silly get     server: 'Apache',
23 silly get     via: '1.1 varnish',
23 silly get     'last-modified': 'Thu, 26 Feb 2015 04:37:40 GMT',
23 silly get     'cache-control': 'max-age=60',
23 silly get     etag: '"543XPT4YVWJ5F0MDALFWP9WTG"',
23 silly get     age: '18',
23 silly get     'x-served-by': 'cache-dfw1831-DFW',
23 silly get     'x-cache': 'HIT',
23 silly get     'x-cache-hits': '1',
23 silly get     'x-timer': 'S1424925460.271548,VS0,VE0',
23 silly get     vary: 'Accept',
23 silly get     'content-length': '0',
23 silly get     'keep-alive': 'timeout=10, max=50',
23 silly get     connection: 'Keep-Alive' } ]
24 verbose etag https://registry.npmjs.org/bower from cache
25 verbose get saving bower to /Users/Gabriel/.npm/registry.npmjs.org/bower/.cache.json
26 silly addNameRange number 2 { name: 'bower', range: '*', hasData: true }
27 silly addNameRange versions [ 'bower',
27 silly addNameRange   [ '0.1.0',
27 silly addNameRange     '0.1.2',
27 silly addNameRange     '0.1.3',
27 silly addNameRange     '0.2.0',
27 silly addNameRange     '0.3.0',
27 silly addNameRange     '0.3.1',
27 silly addNameRange     '0.3.2',
27 silly addNameRange     '0.4.0',
27 silly addNameRange     '0.5.0',
27 silly addNameRange     '0.5.1',
27 silly addNameRange     '0.6.0',
27 silly addNameRange     '0.6.1',
27 silly addNameRange     '0.6.2',
27 silly addNameRange     '0.6.3',
27 silly addNameRange     '0.6.4',
27 silly addNameRange     '0.6.5',
27 silly addNameRange     '0.6.6',
27 silly addNameRange     '0.6.7',
27 silly addNameRange     '0.6.8',
27 silly addNameRange     '0.7.0',
27 silly addNameRange     '0.7.1',
27 silly addNameRange     '0.8.0',
27 silly addNameRange     '0.8.1',
27 silly addNameRange     '0.8.2',
27 silly addNameRange     '0.8.3',
27 silly addNameRange     '0.8.4',
27 silly addNameRange     '0.8.5',
27 silly addNameRange     '0.8.6',
27 silly addNameRange     '0.9.0',
27 silly addNameRange     '0.9.1',
27 silly addNameRange     '0.9.2',
27 silly addNameRange     '0.10.0',
27 silly addNameRange     '1.0.0',
27 silly addNameRange     '1.0.1',
27 silly addNameRange     '1.0.2',
27 silly addNameRange     '1.0.3',
27 silly addNameRange     '1.1.0',
27 silly addNameRange     '1.1.1',
27 silly addNameRange     '1.1.2',
27 silly addNameRange     '1.2.0',
27 silly addNameRange     '1.2.1',
27 silly addNameRange     '1.2.2',
27 silly addNameRange     '1.2.3',
27 silly addNameRange     '1.2.4',
27 silly addNameRange     '1.2.5',
27 silly addNameRange     '1.2.6',
27 silly addNameRange     '1.2.7',
27 silly addNameRange     '1.2.8',
27 silly addNameRange     '1.3.0',
27 silly addNameRange     '1.3.1',
27 silly addNameRange     '1.3.2',
27 silly addNameRange     '1.3.3',
27 silly addNameRange     '1.3.4',
27 silly addNameRange     '1.3.5',
27 silly addNameRange     '1.3.6',
27 silly addNameRange     '1.3.7',
27 silly addNameRange     '1.3.8',
27 silly addNameRange     '1.3.9',
27 silly addNameRange     '1.3.10',
27 silly addNameRange     '1.3.11',
27 silly addNameRange     '1.3.12' ] ]
28 verbose addNamed bower@1.3.12
29 silly addNamed semver.valid 1.3.12
30 silly addNamed semver.validRange 1.3.12
31 silly cache afterAdd bower@1.3.12
32 verbose afterAdd /Users/Gabriel/.npm/bower/1.3.12/package/package.json not in flight; writing
33 verbose afterAdd /Users/Gabriel/.npm/bower/1.3.12/package/package.json written
34 silly install resolved [ { name: 'bower',
34 silly install resolved     version: '1.3.12',
34 silly install resolved     description: 'The browser package manager',
34 silly install resolved     author: { name: 'Twitter' },
34 silly install resolved     licenses: [ [Object] ],
34 silly install resolved     repository: { type: 'git', url: 'https://github.com/bower/bower' },
34 silly install resolved     main: 'lib',
34 silly install resolved     homepage: 'http://bower.io',
34 silly install resolved     engines: { node: '>=0.10.0' },
34 silly install resolved     dependencies:
34 silly install resolved      { abbrev: '~1.0.4',
34 silly install resolved        archy: '0.0.2',
34 silly install resolved        'bower-config': '~0.5.2',
34 silly install resolved        'bower-endpoint-parser': '~0.2.2',
34 silly install resolved        'bower-json': '~0.4.0',
34 silly install resolved        'bower-logger': '~0.2.2',
34 silly install resolved        'bower-registry-client': '~0.2.0',
34 silly install resolved        cardinal: '0.4.0',
34 silly install resolved        chalk: '0.5.0',
34 silly install resolved        chmodr: '0.1.0',
34 silly install resolved        'decompress-zip': '0.0.8',
34 silly install resolved        fstream: '~1.0.2',
34 silly install resolved        'fstream-ignore': '~1.0.1',
34 silly install resolved        glob: '~4.0.2',
34 silly install resolved        'graceful-fs': '~3.0.1',
34 silly install resolved        handlebars: '~2.0.0',
34 silly install resolved        inquirer: '0.7.1',
34 silly install resolved        insight: '0.4.3',
34 silly install resolved        'is-root': '~1.0.0',
34 silly install resolved        junk: '~1.0.0',
34 silly install resolved        lockfile: '~1.0.0',
34 silly install resolved        'lru-cache': '~2.5.0',
34 silly install resolved        mkdirp: '0.5.0',
34 silly install resolved        mout: '~0.9.0',
34 silly install resolved        nopt: '~3.0.0',
34 silly install resolved        opn: '~1.0.0',
34 silly install resolved        osenv: '0.1.0',
34 silly install resolved        'p-throttler': '0.1.0',
34 silly install resolved        promptly: '0.2.0',
34 silly install resolved        q: '~1.0.1',
34 silly install resolved        request: '~2.42.0',
34 silly install resolved        'request-progress': '0.3.0',
34 silly install resolved        retry: '0.6.0',
34 silly install resolved        rimraf: '~2.2.0',
34 silly install resolved        semver: '~2.3.0',
34 silly install resolved        'shell-quote': '~1.4.1',
34 silly install resolved        'stringify-object': '~1.0.0',
34 silly install resolved        'tar-fs': '0.5.2',
34 silly install resolved        tmp: '0.0.23',
34 silly install resolved        'update-notifier': '0.2.0',
34 silly install resolved        which: '~1.0.5' },
34 silly install resolved     devDependencies:
34 silly install resolved      { coveralls: '~2.11.0',
34 silly install resolved        'expect.js': '~0.3.1',
34 silly install resolved        grunt: '~0.4.4',
34 silly install resolved        'grunt-cli': '^0.1.13',
34 silly install resolved        'grunt-contrib-jshint': '~0.10.0',
34 silly install resolved        'grunt-contrib-watch': '~0.6.1',
34 silly install resolved        'grunt-exec': '~0.4.2',
34 silly install resolved        'grunt-simple-mocha': '~0.4.0',
34 silly install resolved        istanbul: '~0.3.2',
34 silly install resolved        'load-grunt-tasks': '~0.6.0',
34 silly install resolved        mocha: '~1.21.4',
34 silly install resolved        nock: '~0.46.0',
34 silly install resolved        'node-uuid': '~1.4.1',
34 silly install resolved        proxyquire: '~1.0.1' },
34 silly install resolved     scripts: { test: 'grunt test' },
34 silly install resolved     bin: { bower: 'bin/bower' },
34 silly install resolved     preferGlobal: true,
34 silly install resolved     gitHead: 'b26c072f0db054a1902ec4d2e3726dbf8a1c799a',
34 silly install resolved     bugs: { url: 'https://github.com/bower/bower/issues' },
34 silly install resolved     _id: 'bower@1.3.12',
34 silly install resolved     _shasum: '37de0edb3904baf90aee13384a1a379a05ee214c',
34 silly install resolved     _from: 'bower@*',
34 silly install resolved     _npmVersion: '2.0.0',
34 silly install resolved     _npmUser: { name: 'sheerun', email: 'sheerun@sher.pl' },
34 silly install resolved     maintainers: [ [Object], [Object], [Object], [Object], [Object], [Object] ],
34 silly install resolved     dist:
34 silly install resolved      { shasum: '37de0edb3904baf90aee13384a1a379a05ee214c',
34 silly install resolved        tarball: 'http://registry.npmjs.org/bower/-/bower-1.3.12.tgz' },
34 silly install resolved     directories: {},
34 silly install resolved     _resolved: 'https://registry.npmjs.org/bower/-/bower-1.3.12.tgz',
34 silly install resolved     readme: 'ERROR: No README data found!' } ]
35 info install bower@1.3.12 into /usr/local/lib
36 info installOne bower@1.3.12
37 verbose installOne of bower to /usr/local/lib not in flight; installing
38 warn locking Error: EACCES, open '/Users/Gabriel/.npm/_locks/bower-e8debc5417026b57.lock'
38 warn locking     at Error (native)
38 warn locking  /Users/Gabriel/.npm/_locks/bower-e8debc5417026b57.lock failed { [Error: EACCES, open '/Users/Gabriel/.npm/_locks/bower-e8debc5417026b57.lock']
38 warn locking   errno: -13,
38 warn locking   code: 'EACCES',
38 warn locking   path: '/Users/Gabriel/.npm/_locks/bower-e8debc5417026b57.lock' }
39 verbose stack Error: Attempt to unlock /usr/local/lib/node_modules/bower, which hasn't been locked
39 verbose stack     at unlock (/usr/local/lib/node_modules/npm/lib/utils/locker.js:66:11)
39 verbose stack     at cb (/usr/local/lib/node_modules/npm/lib/install.js:929:5)
39 verbose stack     at /usr/local/lib/node_modules/npm/lib/install.js:933:20
39 verbose stack     at /usr/local/lib/node_modules/npm/lib/utils/locker.js:40:9
39 verbose stack     at cb (/usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:149:38)
39 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:177:38
39 verbose stack     at FSReqWrap.oncomplete (fs.js:99:15)
40 verbose cwd /Users/Gabriel/Downloads/hepMDapp6
41 error Darwin 13.4.0
42 error argv "node" "/usr/local/bin/npm" "install" "-g" "bower"
43 error node v0.12.0
44 error npm  v2.5.1
45 error Attempt to unlock /usr/local/lib/node_modules/bower, which hasn't been locked
46 error If you need help, you may report this error at:
46 error     <http://github.com/npm/npm/issues>
47 verbose exit [ 1, true ]
```

**Comment by othiym23** [comment]
This is pretty easy to fix – at some point, your `_locks` directory ended up being owned by root, and so now when you go to install, npm can't create new lockfiles in that directory. We've since fixed the underlying permissions issues, but you'll have to fix it by hand once before things work properly again:

```
$ sudo chown -R $(whoami) "$HOME/.npm"
```

Do that, and everything should work.

**Comment by sm0king** [comment]
$ sudo chown -R $(whoami) "$HOME/.npm"
but
command not found: $

**Comment by KenanY** [comment]
@sm0king `$` is an indicator that the command should be executed in a bash prompt. You don't actually prefix the command with it.

**Comment by sm0king** [comment]
but  i can‘t find the file  $HOME/.npm 
only have /.npmc and /.npmrc

**Comment by KenanY** [comment]
@sm0king If the directory does not exist, then you shouldn't have to `chown` it, no?

**Comment by sm0king** [comment]
@KenanY  yes , I can find it . the   /.npm 
only find /.npmc and /.npmrc
