### ISSUE TITLE
npm link "fails" (but it doesn't)

### ISSUE THREAD

**Issue by bevacqua** [npm/npm#7475]
![screen shot 2015-02-26 at 12 19 41](https://cloud.githubusercontent.com/assets/934293/6394674/c8da66be-bdb1-11e4-88a7-df5dde83e524.png)

Full `npm-debug.log`:

``` txt
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/Users/nico/.nvm/v0.10.26/bin/npm', 'link' ]
2 info using npm@2.6.0
3 info using node@v0.10.26
4 verbose linkPkg /Users/nico/dev/taunus
5 verbose gentlyRm vacuuming /Users/nico/.nvm/v0.10.26/lib/node_modules/taunus
6 silly gentlyRm purging /Users/nico/.nvm/v0.10.26/lib/node_modules/taunus
7 silly gentlyRm quitting because other entries in /Users/nico/.nvm/v0.10.26/lib/node_modules
8 verbose gentlyRm vacuuming /Users/nico/.nvm/v0.10.26/lib/node_modules/taunus
9 verbose link build target /Users/nico/.nvm/v0.10.26/lib/node_modules/taunus
10 verbose install where, what [ '/Users/nico/dev/taunus', [] ]
11 verbose install where, deps [ '/Users/nico/dev/taunus',
11 verbose install   [ 'accepts',
11 verbose install     'aliasify',
11 verbose install     'browserify',
11 verbose install     'chalk',
11 verbose install     'chokidar',
11 verbose install     'contra',
11 verbose install     'contra.emitter',
11 verbose install     'fast-url-parser',
11 verbose install     'glob',
11 verbose install     'hget',
11 verbose install     'lodash',
11 verbose install     'minimist',
11 verbose install     'mkdirp',
11 verbose install     'raf',
11 verbose install     'ruta3',
11 verbose install     'uglify-js',
11 verbose install     'xhr',
11 verbose install     'disc',
11 verbose install     'emoji-random',
11 verbose install     'es5-shim',
11 verbose install     'gzip-size',
11 verbose install     'jshint',
11 verbose install     'jshint-stylish',
11 verbose install     'pretty-bytes',
11 verbose install     'proxyquire',
11 verbose install     'proxyquire-universal',
11 verbose install     'sinon',
11 verbose install     'tape',
11 verbose install     'testling',
11 verbose install     'zuul' ] ]
12 verbose install where, peers [ '/Users/nico/dev/taunus', [] ]
13 info preinstall taunus@4.1.8
14 warn package.json emoji-random@0.1.2 No repository field.
15 verbose already installed skipping contra.emitter@^1.0.0 /Users/nico/dev/taunus
16 verbose already installed skipping contra@^1.7.0 /Users/nico/dev/taunus
17 verbose already installed skipping fast-url-parser@^1.0.6-0 /Users/nico/dev/taunus
18 verbose already installed skipping glob@^4.0.6 /Users/nico/dev/taunus
19 verbose already installed skipping hget@^1.1.0 /Users/nico/dev/taunus
20 verbose already installed skipping minimist@^0.1.0 /Users/nico/dev/taunus
21 verbose already installed skipping lodash@^2.4.1 /Users/nico/dev/taunus
22 verbose already installed skipping mkdirp@^0.5.0 /Users/nico/dev/taunus
23 verbose already installed skipping raf@^2.0.3 /Users/nico/dev/taunus
24 verbose already installed skipping ruta3@^1.1.0 /Users/nico/dev/taunus
25 verbose already installed skipping uglify-js@^2.4.15 /Users/nico/dev/taunus
26 verbose already installed skipping xhr@^1.14.1 /Users/nico/dev/taunus
27 verbose already installed skipping disc@^1.3.0 /Users/nico/dev/taunus
28 verbose already installed skipping emoji-random@^0.1.2 /Users/nico/dev/taunus
29 verbose already installed skipping es5-shim@^4.0.3 /Users/nico/dev/taunus
30 verbose already installed skipping gzip-size@^1.0.0 /Users/nico/dev/taunus
31 verbose already installed skipping jshint@^2.5.0 /Users/nico/dev/taunus
32 verbose already installed skipping jshint-stylish@^0.2.0 /Users/nico/dev/taunus
33 verbose already installed skipping pretty-bytes@^1.0.1 /Users/nico/dev/taunus
34 verbose already installed skipping proxyquire@^1.1.0 /Users/nico/dev/taunus
35 verbose already installed skipping proxyquire-universal@^1.0.2 /Users/nico/dev/taunus
36 verbose already installed skipping sinon@^1.12.1 /Users/nico/dev/taunus
37 verbose already installed skipping tape@^3.0.3 /Users/nico/dev/taunus
38 verbose already installed skipping testling@^1.7.1 /Users/nico/dev/taunus
39 verbose already installed skipping zuul@^1.16.3 /Users/nico/dev/taunus
40 verbose already installed skipping browserify@^6.3.2 /Users/nico/dev/taunus
41 verbose already installed skipping accepts@^1.1.1 /Users/nico/dev/taunus
42 verbose already installed skipping aliasify@^1.5.1 /Users/nico/dev/taunus
43 verbose already installed skipping chalk@^0.4.0 /Users/nico/dev/taunus
44 verbose already installed skipping chokidar@^0.8.2 /Users/nico/dev/taunus
45 silly install resolved []
46 info build /Users/nico/dev/taunus
47 verbose linkStuff [ false, false, false, '/Users/nico/dev' ]
48 info linkStuff taunus@4.1.8
49 verbose linkBins taunus@4.1.8
50 verbose linkMans taunus@4.1.8
51 verbose rebuildBundles taunus@4.1.8
52 verbose rebuildBundles [ '.bin',
52 verbose rebuildBundles   'accepts',
52 verbose rebuildBundles   'aliasify',
52 verbose rebuildBundles   'browserify',
52 verbose rebuildBundles   'bundle-collapser',
52 verbose rebuildBundles   'chalk',
52 verbose rebuildBundles   'chokidar',
52 verbose rebuildBundles   'concat-stream',
52 verbose rebuildBundles   'contra',
52 verbose rebuildBundles   'contra.emitter',
52 verbose rebuildBundles   'convert-source-map',
52 verbose rebuildBundles   'disc',
52 verbose rebuildBundles   'emoji-random',
52 verbose rebuildBundles   'es5-shim',
52 verbose rebuildBundles   'fast-url-parser',
52 verbose rebuildBundles   'glob',
52 verbose rebuildBundles   'gzip-size',
52 verbose rebuildBundles   'hget',
52 verbose rebuildBundles   'i40',
52 verbose rebuildBundles   'jshint',
52 verbose rebuildBundles   'jshint-stylish',
52 verbose rebuildBundles   'lodash',
52 verbose rebuildBundles   'minimist',
52 verbose rebuildBundles   'mkdirp',
52 verbose rebuildBundles   'pretty-bytes',
52 verbose rebuildBundles   'proxyquire',
52 verbose rebuildBundles   'proxyquire-universal',
52 verbose rebuildBundles   'proxyquireify',
52 verbose rebuildBundles   'raf',
52 verbose rebuildBundles   'routes',
52 verbose rebuildBundles   'ruta3',
52 verbose rebuildBundles   'sinon',
52 verbose rebuildBundles   'tape',
52 verbose rebuildBundles   'testling',
52 verbose rebuildBundles   'through2',
52 verbose rebuildBundles   'uglify-js',
52 verbose rebuildBundles   'xhr',
52 verbose rebuildBundles   'zuul' ]
53 verbose rebuild bundle /Users/nico/dev/taunus/node_modules/bundle-collapser
54 info build /Users/nico/dev/taunus/node_modules/bundle-collapser
55 info preinstall bundle-collapser@1.1.1
56 verbose linkStuff [ false, false, false, '/Users/nico/dev/taunus/node_modules' ]
57 info linkStuff bundle-collapser@1.1.1
58 verbose linkBins bundle-collapser@1.1.1
59 verbose link bins [ { 'bundle-collapser': 'bin/cmd.js' },
59 verbose link bins   '/Users/nico/dev/taunus/node_modules/.bin',
59 verbose link bins   false ]
60 verbose linkMans bundle-collapser@1.1.1
61 verbose rebuildBundles bundle-collapser@1.1.1
62 verbose rebuildBundles [ '.bin',
62 verbose rebuildBundles   'browser-pack',
62 verbose rebuildBundles   'browser-unpack',
62 verbose rebuildBundles   'falafel',
62 verbose rebuildBundles   'minimist',
62 verbose rebuildBundles   'through2' ]
63 verbose gentlyRm vacuuming /Users/nico/dev/taunus/node_modules/.bin/bundle-collapser
64 silly gentlyRm purging /Users/nico/dev/taunus/node_modules/.bin/bundle-collapser
65 silly gentlyRm quitting because other entries in /Users/nico/dev/taunus/node_modules/.bin
66 info install bundle-collapser@1.1.1
67 info postinstall bundle-collapser@1.1.1
68 verbose rebuild bundle /Users/nico/dev/taunus/node_modules/concat-stream
69 info build /Users/nico/dev/taunus/node_modules/concat-stream
70 info preinstall concat-stream@1.4.7
71 verbose linkStuff [ false, false, false, '/Users/nico/dev/taunus/node_modules' ]
72 info linkStuff concat-stream@1.4.7
73 verbose linkBins concat-stream@1.4.7
74 verbose linkMans concat-stream@1.4.7
75 verbose rebuildBundles concat-stream@1.4.7
76 verbose rebuildBundles [ 'inherits', 'readable-stream', 'typedarray' ]
77 info install concat-stream@1.4.7
78 info postinstall concat-stream@1.4.7
79 verbose rebuild bundle /Users/nico/dev/taunus/node_modules/convert-source-map
80 info build /Users/nico/dev/taunus/node_modules/convert-source-map
81 info preinstall convert-source-map@0.4.1
82 verbose linkStuff [ false, false, false, '/Users/nico/dev/taunus/node_modules' ]
83 info linkStuff convert-source-map@0.4.1
84 verbose linkBins convert-source-map@0.4.1
85 verbose linkMans convert-source-map@0.4.1
86 verbose rebuildBundles convert-source-map@0.4.1
87 info install convert-source-map@0.4.1
88 info postinstall convert-source-map@0.4.1
89 verbose rebuild bundle /Users/nico/dev/taunus/node_modules/i40
90 info build /Users/nico/dev/taunus/node_modules/i40
91 info preinstall i40@1.3.1
92 verbose linkStuff [ false, false, false, '/Users/nico/dev/taunus/node_modules' ]
93 info linkStuff i40@1.3.1
94 verbose linkBins i40@1.3.1
95 verbose linkMans i40@1.3.1
96 verbose rebuildBundles i40@1.3.1
97 info install i40@1.3.1
98 info postinstall i40@1.3.1
99 verbose rebuild bundle /Users/nico/dev/taunus/node_modules/proxyquireify
100 info build /Users/nico/dev/taunus/node_modules/proxyquireify
101 info preinstall proxyquireify@1.1.0
102 verbose linkStuff [ false, false, false, '/Users/nico/dev/taunus/node_modules' ]
103 info linkStuff proxyquireify@1.1.0
104 verbose linkBins proxyquireify@1.1.0
105 verbose linkMans proxyquireify@1.1.0
106 verbose rebuildBundles proxyquireify@1.1.0
107 verbose rebuildBundles [ '.bin', 'browser-pack', 'detective', 'through', 'xtend' ]
108 info install proxyquireify@1.1.0
109 info postinstall proxyquireify@1.1.0
110 verbose rebuild bundle /Users/nico/dev/taunus/node_modules/routes
111 info build /Users/nico/dev/taunus/node_modules/routes
112 info preinstall routes@1.2.0
113 verbose linkStuff [ false, false, false, '/Users/nico/dev/taunus/node_modules' ]
114 info linkStuff routes@1.2.0
115 verbose linkBins routes@1.2.0
116 verbose linkMans routes@1.2.0
117 verbose rebuildBundles routes@1.2.0
118 info install routes@1.2.0
119 info postinstall routes@1.2.0
120 verbose rebuild bundle /Users/nico/dev/taunus/node_modules/through2
121 info build /Users/nico/dev/taunus/node_modules/through2
122 info preinstall through2@0.6.3
123 verbose linkStuff [ false, false, false, '/Users/nico/dev/taunus/node_modules' ]
124 info linkStuff through2@0.6.3
125 verbose linkBins through2@0.6.3
126 verbose linkMans through2@0.6.3
127 verbose rebuildBundles through2@0.6.3
128 verbose rebuildBundles [ 'readable-stream', 'xtend' ]
129 info install through2@0.6.3
130 info postinstall through2@0.6.3
131 info install taunus@4.1.8
132 info postinstall taunus@4.1.8
133 info prepublish taunus@4.1.8
134 info build /Users/nico/.nvm/v0.10.26/lib/node_modules/taunus
135 verbose linkStuff [ true,
135 verbose linkStuff   '/Users/nico/.nvm/v0.10.26/lib/node_modules',
135 verbose linkStuff   true,
135 verbose linkStuff   '/Users/nico/.nvm/v0.10.26/lib/node_modules' ]
136 info linkStuff taunus@4.1.8
137 verbose linkBins taunus@4.1.8
138 verbose link bins [ { taunus: 'bin/taunus' },
138 verbose link bins   '/Users/nico/.nvm/v0.10.26/bin',
138 verbose link bins   true ]
139 verbose linkMans taunus@4.1.8
140 verbose gentlyRm verifying that /Users/nico/dev/taunus is managed by npm
141 silly isManaged /Users/nico/dev/taunus is not inside /Users/nico/dev/taunus/node_modules
142 silly isManaged /Users/nico/dev/taunus is not inside /Users/nico/dev/taunus/node_modules
143 silly isManaged /Users/nico/dev/taunus/node_modules/.bin is inside /Users/nico/dev/taunus
144 silly gentlyRm /Users/nico/dev/taunus is managed by npm
145 silly gentlyRm /Users/nico/.nvm/v0.10.26/bin/taunus is not under /Users/nico/dev/taunus
146 silly gentlyRm checking to see if /Users/nico/.nvm/v0.10.26/bin/taunus is a link
147 silly gentlyRm /Users/nico/.nvm/v0.10.26/bin/taunus is a link
148 silly gentlyRm checking to see if /Users/nico/.nvm/v0.10.26/lib/node_modules/taunus/bin/taunus is managed by npm
149 silly isManaged /Users/nico/.nvm/v0.10.26/lib/node_modules/taunus/bin/taunus is not inside /Users/nico/dev/taunus/node_modules
150 silly isManaged /Users/nico/.nvm/v0.10.26/lib/node_modules/taunus/bin/taunus is not inside /Users/nico/dev/taunus/node_modules
151 silly isManaged /Users/nico/.nvm/v0.10.26/lib/node_modules/taunus/bin/taunus is not inside /Users/nico/dev/taunus/node_modules/.bin
152 silly isManaged /Users/nico/.nvm/v0.10.26/lib/node_modules/taunus/bin/taunus is not inside /Users/nico/dev/taunus
153 silly isManaged /Users/nico/.nvm/v0.10.26/lib/node_modules is not inside /Users/nico/.nvm/v0.10.26/lib/node_modules/taunus/bin/taunus
154 verbose isManaged no path
155 silly isManaged /Users/nico/.nvm/v0.10.26/bin is not inside /Users/nico/.nvm/v0.10.26/lib/node_modules/taunus/bin/taunus
156 silly isManaged /Users/nico/.nvm/v0.10.26 is not inside /Users/nico/.nvm/v0.10.26/lib/node_modules/taunus/bin/taunus
157 verbose gentlyRm /Users/nico/.nvm/v0.10.26/lib/node_modules/taunus/bin/taunus is not managed by npm
158 verbose stack Error: Refusing to delete: /Users/nico/.nvm/v0.10.26/bin/taunus not in /Users/nico/dev/taunus
158 verbose stack     at clobberFail (/Users/nico/.nvm/v0.10.26/lib/node_modules/npm/lib/utils/gently-rm.js:168:12)
158 verbose stack     at /Users/nico/.nvm/v0.10.26/lib/node_modules/npm/lib/utils/gently-rm.js:107:18
158 verbose stack     at zalgoSafe (/Users/nico/.nvm/v0.10.26/lib/node_modules/npm/node_modules/dezalgo/dezalgo.js:20:10)
158 verbose stack     at map (/Users/nico/.nvm/v0.10.26/lib/node_modules/npm/node_modules/async-some/some.js:28:33)
158 verbose stack     at reduce (/Users/nico/.nvm/v0.10.26/lib/node_modules/npm/node_modules/async-some/some.js:38:5)
158 verbose stack     at /Users/nico/.nvm/v0.10.26/lib/node_modules/npm/lib/utils/gently-rm.js:134:14
158 verbose stack     at cb (/Users/nico/.nvm/v0.10.26/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
158 verbose stack     at /Users/nico/.nvm/v0.10.26/lib/node_modules/npm/lib/utils/gently-rm.js:152:16
158 verbose stack     at Object.oncomplete (evalmachine.<anonymous>:107:15)
159 verbose cwd /Users/nico/dev/taunus
160 error Darwin 14.0.0
161 error argv "node" "/Users/nico/.nvm/v0.10.26/bin/npm" "link"
162 error node v0.10.26
163 error npm  v2.6.0
164 error path /Users/nico/.nvm/v0.10.26/bin/taunus
165 error code EEXIST
166 error Refusing to delete: /Users/nico/.nvm/v0.10.26/bin/taunus not in /Users/nico/dev/taunus
File exists: /Users/nico/.nvm/v0.10.26/bin/taunus
Move it away, and try again.
167 verbose exit [ 1, true ]
```

Thing is `npm link` ultimately did it's job in linking `taunus`, but it throws this error almost every time. Can you spot what I did wrong on `taunus` or how it reached that state?

If it's just a matter of "`taunus` already linked" the message should reflect that, as it's curently confusing and unclear that the command actually succeeded.

**Comment by smikes** [comment]
Yes, this is a bug in the way globally linked packages work.  I have seen this myself a few times but I never got to the point of opening an issue -- thanks.  I will try to set up a simple test to reproduce the behavior.
