### ISSUE TITLE
npm login - No credentials to set

### ISSUE THREAD

**Issue by SamVerschueren** [npm/npm#7483]
I created my account and tried to sign in with ```npm login```. This is what I received.

```
npm ERR! Linux 3.16.0-31-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "login"
npm ERR! node v0.11.15
npm ERR! npm  v2.1.6

npm ERR! No credentials to set.
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>
\
npm ERR! Please include the following file with any support request:
npm ERR!     /home/sam/Documents/Projects/node-mongoose-validator/npm-debug.log
```

And this is my npm-debug.log

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'adduser' ]
2 info using npm@2.1.6
3 info using node@v0.11.15
4 verbose node symlink /usr/bin/node
5 verbose adduser before first PUT { name: 'samverschueren',
5 verbose adduser   password: 'XXXXX',
5 verbose adduser   email: 'sam.verschueren@gmail.com',
5 verbose adduser   _id: 'org.couchdb.user:samverschueren',
5 verbose adduser   type: 'user',
5 verbose adduser   roles: [],
5 verbose adduser   date: '2015-02-27T13:33:48.905Z' }
6 verbose request on initialization, where is /-/user/org.couchdb.user:samverschueren
7 verbose request after pass 1, where is /-/user/org.couchdb.user:samverschueren
8 verbose request url raw /-/user/org.couchdb.user:samverschueren
9 verbose request resolving registry [ 'https://registry.npmjs.org/-/user/org.couchdb.user:samverschueren',
9 verbose request   './-/user/org.couchdb.user:samverschueren' ]
10 verbose request after pass 2, where is https://registry.npmjs.org/-/user/-/user/org.couchdb.user:samverschueren
11 verbose request new user, so can't send auth
12 info attempt registry request try #1 at 14:33:48
13 verbose request id 11d6ca1f48399f05
14 http request PUT https://registry.npmjs.org/-/user/-/user/org.couchdb.user:samverschueren
15 http 404 https://registry.npmjs.org/-/user/-/user/org.couchdb.user:samverschueren
16 verbose headers { date: 'Fri, 27 Feb 2015 13:33:51 GMT',
16 verbose headers   server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
16 verbose headers   'content-type': 'application/json',
16 verbose headers   'cache-control': 'max-age=0',
16 verbose headers   'content-length': '41',
16 verbose headers   'accept-ranges': 'bytes',
16 verbose headers   via: '1.1 varnish',
16 verbose headers   'x-served-by': 'cache-ams4134-AMS',
16 verbose headers   'x-cache': 'MISS',
16 verbose headers   'x-cache-hits': '0',
16 verbose headers   'x-timer': 'S1425044031.274546,VS0,VE620',
16 verbose headers   connection: 'close' }
17 verbose stack Error: No credentials to set.
17 verbose stack     at Conf.setCredentialsByURI (/usr/lib/node_modules/npm/lib/config/set-credentials-by-uri.js:40:11)
17 verbose stack     at RegClient.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/adduser.js:112:17)
17 verbose stack     at RegClient.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/adduser.js:74:18)
17 verbose stack     at f (/usr/lib/node_modules/npm/node_modules/once/once.js:17:25)
17 verbose stack     at /usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:125:10
17 verbose stack     at f (/usr/lib/node_modules/npm/node_modules/once/once.js:17:25)
17 verbose stack     at RegClient.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:276:12)
17 verbose stack     at Request._callback (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:197:65)
17 verbose stack     at Request.self.callback (/usr/lib/node_modules/npm/node_modules/request/request.js:364:22)
17 verbose stack     at Request.emit (events.js:110:17)
18 verbose cwd /home/sam/Documents/Projects/node-mongoose-validator
19 error Linux 3.16.0-31-generic
20 error argv "/usr/bin/node" "/usr/bin/npm" "adduser"
21 error node v0.11.15
22 error npm  v2.1.6
23 error No credentials to set.
24 error If you need help, you may report this error at:
24 error     <http://github.com/npm/npm/issues>
25 verbose exit [ 1, true ]
```

Am I missing something here? Already tried to change my password but dit not work.

**Comment by SamVerschueren** [comment]
Updating npm did the trick.
