### ISSUE TITLE
Error: No compatible version found: init-package-json@'^1.2.0'

### ISSUE THREAD

**Issue by DarianSS** [npm/npm#7524]
Hello,

I am trying to initialize a university project, but I can't install Cordova. I have node.js and git installed as instructed. Any help would be appreciated. Thank you.

```
npm ERR! Error: No compatible version found: init-package-json@'^1.2.0'
npm ERR! Valid install targets:
npm ERR! ["0.0.1","0.0.2","0.0.3","0.0.4","0.0.5","0.0.6","0.0.7","0.0.8","0.0.9","0.0.10","0.0.11","0.0.13","0.0.14","0.0.15","0.0.16","0.0.17","0.1.0","0.1.1","0.1.2","1.0.0","1.0.1","1.1.0","1.1.1","1.1.2","1.1.3","1.2.0","1.3.0"]
npm ERR!     at installTargetsError (/Users/darian/.homebrew/Cellar/node/0.10.3/lib/node_modules/npm/lib/cache.js:685:10)
npm ERR!     at /Users/darian/.homebrew/Cellar/node/0.10.3/lib/node_modules/npm/lib/cache.js:607:10
npm ERR!     at saved (/Users/darian/.homebrew/Cellar/node/0.10.3/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:107:15)
```

**Comment by KenanY** [comment]
@DarianSS Your version of `npm` is so old that it doesn't support the `^` semver operator you see here:

```
npm ERR! Error: No compatible version found: init-package-json@'^1.2.0'
```

As such, `npm` fails to find a valid version to install; a valid "target". The solution here is to [upgrade](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-nix-osx-linux-etc).

**Comment by DarianSS** [comment]
Thank you so very much!
