### ISSUE TITLE
"fetch failed" while trying to build Atom.

### ISSUE THREAD

**Issue by robru** [npm/npm#7572]
Hello,

I was following these instructions:

https://discuss.atom.io/t/validating-atoms-installation-and-build-instructions-for-ubuntu/13014

And when I got to the `script/build` step, I got this output:

```
$ script/build
Node: v0.10.25
npm: v1.4.21
Installing build modules...
npm ERR! fetch failed https://registry.npmjs.org/chainit/-/chainit-2.1.1.tgz
npm ERR! Error: 400 Bad Request
npm ERR!     at WriteStream.<anonymous> (/usr/share/npm/lib/utils/fetch.js:58:12)
npm ERR!     at WriteStream.EventEmitter.emit (events.js:117:20)
npm ERR!     at evalmachine.<anonymous>:1601:14
npm ERR!     at /usr/lib/nodejs/graceful-fs/graceful-fs.js:102:5
npm ERR!     at Object.oncomplete (evalmachine.<anonymous>:107:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.19.0-7-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "--userconfig=/home/robru/src/atom/.npmrc" "install" "--loglevel" "error"
npm ERR! cwd /home/robru/src/atom/build
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/robru/src/atom/build/npm-debug.log
npm ERR! not ok code 0
```

This is on Ubuntu Vivid, 64bit. Any help is appreciated.

**Comment by robru** [comment]
Hm, ran the command a second time, and it worked. Go figure.
