### ISSUE TITLE
Can't publish -- Error 503 backend write error

### ISSUE THREAD

**Issue by cymen** [npm/npm#7589]
I'm trying to publish a package and it is failing:

```sh
~/dev/font-face-observer cvig (master)$ npm publish --verbose .
npm info it worked if it ends with ok
npm verb cli [ 'node', '/usr/local/bin/npm', 'publish', '--verbose', '.' ]
npm info using npm@2.7.0
npm info using node@v0.10.33
npm verb node symlink /usr/local/bin/node
npm verb publish [ '.' ]
npm verb cache add spec .
npm verb addLocalDirectory /Users/cvig/.npm/font-face-observer/0.0.1/package.tgz not in flight; packing
npm verb tar pack [ '/Users/cvig/.npm/font-face-observer/0.0.1/package.tgz',
npm verb tar pack   '/Users/cvig/dev/font-face-observer' ]
npm verb tarball /Users/cvig/.npm/font-face-observer/0.0.1/package.tgz
npm verb folder /Users/cvig/dev/font-face-observer
npm info prepublish font-face-observer@0.0.1
npm verb addLocalTarball adding from inside cache /Users/cvig/.npm/font-face-observer/0.0.1/package.tgz
npm verb afterAdd /Users/cvig/.npm/font-face-observer/0.0.1/package/package.json not in flight; writing
npm verb afterAdd /Users/cvig/.npm/font-face-observer/0.0.1/package/package.json written
npm verb publish registryBase https://registry.npmjs.org/
npm verb request uri https://registry.npmjs.org/font-face-observer
npm verb request sending authorization for write operation
npm info attempt registry request try #1 at 14:21:22
npm verb request id c8440d9390dd5afe
npm http request PUT https://registry.npmjs.org/font-face-observer
npm http 503 https://registry.npmjs.org/font-face-observer
npm verb bad json
npm verb bad json <?xml version="1.0" encoding="utf-8"?>
npm verb bad json <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
npm verb bad json  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
npm verb bad json <html>
npm verb bad json   <head>
npm verb bad json     <title>503 backend write error</title>
npm verb bad json   </head>
npm verb bad json   <body>
npm verb bad json     <h1>Error 503 backend write error</h1>
npm verb bad json     <p>backend write error</p>
npm verb bad json     <h3>Guru Mediation:</h3>
npm verb bad json     <p>Details: cache-iad2139-IAD 1426022483 3499992069</p>
npm verb bad json     <hr>
npm verb bad json     <p>Varnish cache server</p>
npm verb bad json   </body>
npm verb bad json </html>
npm verb bad json
npm ERR! registry error parsing json
npm info retry will retry, error on last attempt: SyntaxError: Unexpected token <
npm info retry
npm info retry <?xml version="1.0" encoding="utf-8"?>
npm info retry <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
npm info retry  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
npm info retry <html>
npm info retry   <head>
npm info retry     <title>503 backend write error</title>
npm info retry   </head>
npm info retry   <body>
npm info retry     <h1>Error 503 backend write error</h1>
npm info retry     <p>backend write error</p>
npm info retry     <h3>Guru Mediation:</h3>
npm info retry     <p>Details: cache-iad2139-IAD 1426022483 3499992069</p>
npm info retry     <hr>
npm info retry     <p>Varnish cache server</p>
npm info retry   </body>
npm info retry </html>
npm info retry
npm info attempt registry request try #2 at 14:21:33
npm http request PUT https://registry.npmjs.org/font-face-observer
npm http 503 https://registry.npmjs.org/font-face-observer
npm verb bad json
npm verb bad json <?xml version="1.0" encoding="utf-8"?>
npm verb bad json <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
npm verb bad json  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
npm verb bad json <html>
npm verb bad json   <head>
npm verb bad json     <title>503 backend write error</title>
npm verb bad json   </head>
npm verb bad json   <body>
npm verb bad json     <h1>Error 503 backend write error</h1>
npm verb bad json     <p>backend write error</p>
npm verb bad json     <h3>Guru Mediation:</h3>
npm verb bad json     <p>Details: cache-iad2125-IAD 1426022495 4092069036</p>
npm verb bad json     <hr>
npm verb bad json     <p>Varnish cache server</p>
npm verb bad json   </body>
npm verb bad json </html>
npm verb bad json
npm ERR! registry error parsing json
npm info retry will retry, error on last attempt: SyntaxError: Unexpected token <
npm info retry
npm info retry <?xml version="1.0" encoding="utf-8"?>
npm info retry <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
npm info retry  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
npm info retry <html>
npm info retry   <head>
npm info retry     <title>503 backend write error</title>
npm info retry   </head>
npm info retry   <body>
npm info retry     <h1>Error 503 backend write error</h1>
npm info retry     <p>backend write error</p>
npm info retry     <h3>Guru Mediation:</h3>
npm info retry     <p>Details: cache-iad2125-IAD 1426022495 4092069036</p>
npm info retry     <hr>
npm info retry     <p>Varnish cache server</p>
npm info retry   </body>
npm info retry </html>
npm info retry
npm info attempt registry request try #3 at 14:22:34
npm http request PUT https://registry.npmjs.org/font-face-observer
npm http 503 https://registry.npmjs.org/font-face-observer
npm verb bad json
npm verb bad json <?xml version="1.0" encoding="utf-8"?>
npm verb bad json <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
npm verb bad json  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
npm verb bad json <html>
npm verb bad json   <head>
npm verb bad json     <title>503 backend write error</title>
npm verb bad json   </head>
npm verb bad json   <body>
npm verb bad json     <h1>Error 503 backend write error</h1>
npm verb bad json     <p>backend write error</p>
npm verb bad json     <h3>Guru Mediation:</h3>
npm verb bad json     <p>Details: cache-atl6222-ATL 1426022556 2568005123</p>
npm verb bad json     <hr>
npm verb bad json     <p>Varnish cache server</p>
npm verb bad json   </body>
npm verb bad json </html>
npm verb bad json
npm ERR! registry error parsing json
npm verb headers { date: 'Tue, 10 Mar 2015 21:22:36 GMT',
npm verb headers   server: 'Varnish',
npm verb headers   'retry-after': '0',
npm verb headers   'content-type': 'text/html; charset=utf-8',
npm verb headers   'content-length': '451',
npm verb headers   'accept-ranges': 'bytes',
npm verb headers   via: '1.1 varnish',
npm verb headers   'x-served-by': 'cache-atl6222-ATL',
npm verb headers   'x-cache': 'MISS',
npm verb headers   'x-cache-hits': '0',
npm verb headers   'x-timer': 'S1426022555.639523,VS0,VE430',
npm verb headers   connection: 'close' }
npm verb request invalidating /Users/cvig/.npm/registry.npmjs.org/font-face-observer on PUT
npm ERR! publish Failed PUT 503
npm verb type unexpected_token
npm verb stack SyntaxError: Unexpected token <
npm verb stack
npm verb stack <?xml version="1.0" encoding="utf-8"?>
npm verb stack <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
npm verb stack  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
npm verb stack <html>
npm verb stack   <head>
npm verb stack     <title>503 backend write error</title>
npm verb stack   </head>
npm verb stack   <body>
npm verb stack     <h1>Error 503 backend write error</h1>
npm verb stack     <p>backend write error</p>
npm verb stack     <h3>Guru Mediation:</h3>
npm verb stack     <p>Details: cache-atl6222-ATL 1426022556 2568005123</p>
npm verb stack     <hr>
npm verb stack     <p>Varnish cache server</p>
npm verb stack   </body>
npm verb stack </html>
npm verb stack
npm verb stack     at Object.parse (native)
npm verb stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:205:23)
npm verb stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:178:14)
npm verb stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:344:22)
npm verb stack     at Request.emit (events.js:98:17)
npm verb stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1239:14)
npm verb stack     at Request.emit (events.js:117:20)
npm verb stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1187:12)
npm verb stack     at IncomingMessage.emit (events.js:117:20)
npm verb stack     at _stream_readable.js:943:16
npm verb cwd /Users/cvig/dev/font-face-observer
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "publish" "--verbose" "."
npm ERR! node v0.10.33
npm ERR! npm  v2.7.0

npm ERR! Unexpected token <
npm ERR!
npm ERR! <?xml version="1.0" encoding="utf-8"?>
npm ERR! <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
npm ERR!  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
npm ERR! <html>
npm ERR!   <head>
npm ERR!     <title>503 backend write error</title>
npm ERR!   </head>
npm ERR!   <body>
npm ERR!     <h1>Error 503 backend write error</h1>
npm ERR!     <p>backend write error</p>
npm ERR!     <h3>Guru Mediation:</h3>
npm ERR!     <p>Details: cache-atl6222-ATL 1426022556 2568005123</p>
npm ERR!     <hr>
npm ERR!     <p>Varnish cache server</p>
npm ERR!   </body>
npm ERR! </html>
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>
npm verb exit [ 1, true ]

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/cvig/dev/font-face-observer/npm-debug.log
```

**Comment by cymen** [comment]
And [npm-debug.log](https://gist.github.com/cymen/c70c57a6c3a0dd453f55).

**Comment by cymen** [comment]
Doh! An `npm login` fixed this. I think I changed my password on the website and it hadn't been updated in my local config file. Thanks.
