### ISSUE TITLE
Issue using 'adduser'

### ISSUE THREAD

**Issue by matadoer** [npm/npm#7615]
```
npm http PUT https://registry.npmjs.org/-/user/org.couchdb.user:matadoer
npm http 409 https://registry.npmjs.org/-/user/org.couchdb.user:matadoer
npm http GET https://registry.npmjs.org/-/user/org.couchdb.user:matadoer
npm http 200 https://registry.npmjs.org/-/user/org.couchdb.user:matadoer
npm http PUT https://registry.npmjs.org/-/user/org.couchdb.user:matadoer/-rev/undefined
npm http 400 https://registry.npmjs.org/-/user/org.couchdb.user:matadoer/-rev/undefined
npm ERR! Error: bad_request Invalid rev format: -/user/org.couchdb.user:matadoer/-rev/undefined
npm ERR!     at RegClient.<anonymous> (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:272:14)
npm ERR!     at Request.self.callback (/usr/lib/nodejs/request/index.js:148:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/index.js:896:14)
npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/lib/nodejs/request/index.js:847:12)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>
```

**Comment by matadoer** [comment]
@isaacs

**Comment by othiym23** [comment]
You're using a very old and out of date version of npm (and probably node, if you're using an Ubuntu / Debian-packaged nodejs). [Try upgrading](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) to the latest version of Node and a newer version of npm, and see if that helps. (If you want to stick with the Debian / Ubuntu packages, you'll need to file this issue on their bug trackers, as the npm team doesn't handle packaging for npm for those projects, and can't do much to fix issues with those packages.)
