### ISSUE TITLE
nmp fails to install selenium-webdriver.

### ISSUE THREAD

**Issue by joeydolan** [npm/npm#7621]
Looking at previous error messages on this site I tried doing a global install in C:\temp

*** Pasted at the end  IS MY npm-debug.log

c:\temp>npm install --global selenium-webdriver
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodej
\\node_modules\\npm\\bin\\npm-cli.js" "install" "--global" "selenium-webdriver"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code SELF_SIGNED_CERT_IN_CHAIN

npm ERR! self signed certificate in certificate chain
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     c:\temp\npm-debug.log
====================  End of Cmd stream  ================================

Log:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '--global',
1 verbose cli   'selenium-webdriver' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 silly cache add args [ 'selenium-webdriver', null ]
6 verbose cache add spec selenium-webdriver
7 silly cache add parsed spec { raw: 'selenium-webdriver',
7 silly cache add   scope: null,
7 silly cache add   name: 'selenium-webdriver',
7 silly cache add   rawSpec: '',
7 silly cache add   spec: '*',
7 silly cache add   type: 'range' }
8 verbose addNamed selenium-webdriver@*
9 silly addNamed semver.valid null
10 silly addNamed semver.validRange *
11 silly addNameRange { name: 'selenium-webdriver', range: '*', hasData: false }
12 silly mapToRegistry name selenium-webdriver
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/selenium-webdriver
16 verbose addNameRange registry:https://registry.npmjs.org/selenium-webdriver not in flight; fetching
17 verbose request uri https://registry.npmjs.org/selenium-webdriver
18 verbose request no auth needed
19 info attempt registry request try #1 at 1:23:11 PM
20 verbose request id 41ecbfa3a0b6684f
21 http request GET https://registry.npmjs.org/selenium-webdriver
22 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
23 info attempt registry request try #2 at 1:23:21 PM
24 http request GET https://registry.npmjs.org/selenium-webdriver
25 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
26 info attempt registry request try #3 at 1:24:21 PM
27 http request GET https://registry.npmjs.org/selenium-webdriver
28 verbose stack Error: self signed certificate in certificate chain
28 verbose stack     at Error (native)
28 verbose stack     at TLSSocket.<anonymous> (_tls_wrap.js:927:36)
28 verbose stack     at TLSSocket.emit (events.js:104:17)
28 verbose stack     at TLSSocket._finishInit (_tls_wrap.js:458:8)
29 verbose cwd c:\temp
30 error Windows_NT 6.1.7601
31 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--global" "selenium-webdriver"
32 error node v0.12.0
33 error npm  v2.5.1
34 error code SELF_SIGNED_CERT_IN_CHAIN
35 error self signed certificate in certificate chain
36 error If you need help, you may report this error at:
36 error     <http://github.com/npm/npm/issues>
37 verbose exit [ 1, true ]

**Comment by joeydolan** [comment]
I work for a state government agency and am behind a proxy.
