### ISSUE TITLE
Unable to install from github repo when specified in package.json, err 406

### ISSUE THREAD

**Issue by bitinn** [npm/npm#7630]
I am seeing this generic 406 error consistently on a particular iMac in our network. Other machines in the same network with the same io.js (v1.5.1) doesn't appear to be affected by this problem.

But where does ERR 406 comes from, that iMac can access https://github.com/bitinn/onchange#gaze just fine. And it can install other npm package just fine.

I tried to reinstall io.js with .pkg but issue persists. What could have cause this?

```
npm info retry fetch attempt 3 at 00:11:57
npm info attempt registry request try #1 at 00:11:57
npm http fetch GET https://github.com/bitinn/onchange#gaze
npm http fetch 406 https://github.com/bitinn/onchange#gaze
npm ERR! fetch failed https://github.com/bitinn/onchange#gaze
npm verb stack Error: fetch failed with status code 406
npm verb stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/fetch.js:55:14)
npm verb stack     at emitOne (events.js:77:13)
npm verb stack     at Request.emit (events.js:166:7)
npm verb stack     at Request.onRequestResponse (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1176:10)
npm verb stack     at emitOne (events.js:77:13)
npm verb stack     at ClientRequest.emit (events.js:166:7)
npm verb stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:410:21)
npm verb stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
npm verb stack     at TLSSocket.socketOnData (_http_client.js:300:20)
npm verb stack     at emitOne (events.js:77:13)
npm verb cwd /Users/teambegin/git/dudao
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "--node-gyp=pangyp" "--verbose"
npm ERR! node v1.5.1
npm ERR! npm  v2.7.0

npm ERR! fetch failed with status code 406
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>
npm verb exit [ 1, true ]

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/teambegin/git/dudao/npm-debug.log
```

**Comment by dman777** [comment]
I seem to also be having this issue on my cloud server(gentoo) for https://github.com/dman777/gulp-newy.git.

```
one@public-node ~/github/gulp-newy $ cat /home/one/github/gulp-newy/npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ 'node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   'https://github.com/dman777/gulp-newy.git' ]
2 info using npm@2.7.0
3 info using node@v0.12.0
4 silly cache add args [ 'https://github.com/dman777/gulp-newy.git', null ]
5 verbose cache add spec https://github.com/dman777/gulp-newy.git
6 silly cache add parsed spec { raw: 'https://github.com/dman777/gulp-newy.git',
6 silly cache add   scope: null,
6 silly cache add   name: null,
6 silly cache add   rawSpec: 'https://github.com/dman777/gulp-newy.git',
6 silly cache add   spec: 'https://github.com/dman777/gulp-newy.git',
6 silly cache add   type: 'remote' }
7 silly mapToRegistry name https://github.com/dman777/gulp-newy.git
8 silly mapToRegistry using default registry
9 silly mapToRegistry registry https://registry.npmjs.org/
10 silly mapToRegistry uri https://github.com/dman777/gulp-newy.git
11 verbose addRemoteTarball https://github.com/dman777/gulp-newy.git not in flight; adding
12 verbose addRemoteTarball [ 'https://github.com/dman777/gulp-newy.git', null ]
13 info retry fetch attempt 1 at 9:18:07 PM
14 info attempt registry request try #1 at 9:18:07 PM
15 http fetch GET https://github.com/dman777/gulp-newy.git
16 verbose request id d2c58b8ac132095a
17 http fetch 406 https://github.com/dman777/gulp-newy.git
18 error fetch failed https://github.com/dman777/gulp-newy.git
19 warn retry will retry, error on last attempt: Error: fetch failed with status code 406
20 info retry fetch attempt 2 at 9:18:17 PM
21 info attempt registry request try #1 at 9:18:17 PM
22 http fetch GET https://github.com/dman777/gulp-newy.git
23 http fetch 406 https://github.com/dman777/gulp-newy.git
24 error fetch failed https://github.com/dman777/gulp-newy.git
25 warn retry will retry, error on last attempt: Error: fetch failed with status code 406
26 info retry fetch attempt 3 at 9:19:18 PM
27 info attempt registry request try #1 at 9:19:18 PM
28 http fetch GET https://github.com/dman777/gulp-newy.git
29 http fetch 406 https://github.com/dman777/gulp-newy.git
30 error fetch failed https://github.com/dman777/gulp-newy.git
31 verbose stack Error: fetch failed with status code 406
31 verbose stack     at Request.<anonymous> (/usr/lib64/node_modules/npm/node_modules/npm-registry-client/lib/fetch.js:55:14)
31 verbose stack     at Request.emit (events.js:107:17)
31 verbose stack     at Request.onRequestResponse (/usr/lib64/node_modules/npm/node_modules/request/request.js:1176:10)
31 verbose stack     at ClientRequest.emit (events.js:107:17)
31 verbose stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:419:21)
31 verbose stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
31 verbose stack     at TLSSocket.socketOnData (_http_client.js:310:20)
31 verbose stack     at TLSSocket.emit (events.js:107:17)
31 verbose stack     at readableAddChunk (_stream_readable.js:163:16)
31 verbose stack     at TLSSocket.Readable.push (_stream_readable.js:126:10)
32 verbose cwd /home/one/github/gulp-newy
33 error Linux 3.14.14-gentoo
34 error argv "node" "/usr/bin/npm" "install" "https://github.com/dman777/gulp-newy.git"
35 error node v0.12.0
36 error npm  v2.7.0
37 error fetch failed with status code 406
38 error If you need help, you may report this error at:
38 error     <http://github.com/npm/npm/issues>
39 verbose exit [ 1, true ]
```

**Comment by bitinn** [comment]
@othiym23 is there ways to know what exactly is npm doing and on which request did it get 406 result from github?

**Comment by bitinn** [comment]
It looks like I can `npm install bitinn/onchange` and `npm install bitinn/onchange#gaze` without issue

It's only when read from package.json, the request fail. weird.

sample package.json (generated from `npm init`, so I don't know a format issue)

```
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "onchange": "bitinn/onchange"
  },
  "dependencies": {
    "onchange": "bitinn/onchange"
  }
}
```

**Comment by bitinn** [comment]
Alright I have made some progress in understanding the problem:

This doesn't work

```
  "dependencies": {
    "onchange": "https://github.com/bitinn/onchange#gaze"
  }
```

But this does

```
  "dependencies": {
    "onchange": "git://github.com/bitinn/onchange.git#gaze"
  }
```

by default the shorthand resolve to https when specified in package.json (but in command line it resolves to git), so it only fails when in package.json.

but i still need to figure out why fetching over https failed on this imac.

**Comment by bitinn** [comment]
@othiym23

my test result on two different Mac, with npm 2.7.0, all of these format works:

```
git://github.com/user/project.git#commit-ish
git+ssh://user@hostname:project.git#commit-ish
git+ssh://user@hostname/project.git#commit-ish
git+http://user@hostname/project/blah.git#commit-ish
git+https://user@hostname/project/blah.git#commit-ish
```

but not this

```
user/project#commit-ish
```

And it only fail when listed as a dependency. I have not had this issue with previous releases.

To be honest I am surprised `user/project#commit-ish` is treated any differently from `git://github.com/user/project.git#commit-ish`

**Comment by othiym23** [comment]
@bitinn 
The 406 is coming from GitHub. You probably have an invalid `github.config` in `$HOME/.gitconfig` on that particular box, and so GitHub is complaining when get tries to use it for HTTPS auth.

The bigger question is why it's trying to use HTTPS for GitHub shortcuts in the first place, and the answer is that you've exposed a fairly convoluted bug. The key clue is that things work differently when you run `npm install bitinn/onchange#gaze` from the command line from than when `npm install` is run with the same shortcut in `package.json`.

In the former case, the shortcut is being passed directly to npm's caching logic, which [has one way of resolving GitHub shortcuts to git URLs](https://github.com/npm/npm/blob/e013d3156a465f86ac378b2f3898322a530a4f38/lib/cache/maybe-github.js#L9-L14). First it tries to expand them to `git://` URLs, and falls back to `git+ssh://` URLs if that doesn't work.

In the latter case, `read-package-json` is used to get a predigested version of `package.json`'s data that can be fed into the installer. As part of that process, it "normalizes" the package metadata through `normalize-package-data`, which in turn [runs potential GitHub shortcuts through `github-url-from-username-repo`](https://github.com/npm/normalize-package-data/blob/master/lib/fixer.js#L147-L150). That last bit is what's causing this error, which hasn't been exposed before now because I think it's fairly rare that `git:` or `ssh:` URLs work but `https:` don't.

Because `read-package-json` munges the URLs before the npm install / cache code sees them, to resolve this inconsistency would require making breaking changes to both `read-package-json` and `normalize-package-data` – other users of those packages (and there are a few) might be expecting to get back GitHub URLs already expanded from shortcuts. That's probably what I'll do, but it's kind of a risky change, so I'll have to look at it a bit first.

Thanks for bringing this to our attention, and sorry for letting you get bitten by it in the first place!

**Comment by bitinn** [comment]
@othiym23 Thx for confirming this!

As for the error 406, my `.gitconfig` doesn't have a token entry, i assume that can also cause issue with github? (but why?)

**Comment by othiym23** [comment]
I'm not 100% sure how you got to the point on that particular machine, but I'd look at `$HOME/.gitconfig` on that machine and compare it to other machines, because the repo is public and if just accessed normally, it shouldn't return an auth failure.

**Comment by bitinn** [comment]
@othiym23 

I think what happen here is npm request the repo page using incorrect headers, i used a MITM proxy to capture that error 406 request, and this is what i got:

```
GET https://github.com/bitinn/onchange HTTP/1.1
version: 2.7.0
accept: application/x-tar, application/vnd.github+json; q=0.1
referer: install [REDACTED]
npm-session: 104096a1e025a1b4
user-agent: npm/2.7.0 node/v1.5.1 darwin x64
host: github.com
Connection: close
```

```
HTTP/1.1 406 Not Acceptable
Server: GitHub.com
Date: Wed, 18 Mar 2015 18:52:58 GMT
Content-Type: text/html; charset=utf-8
Transfer-Encoding: chunked
Connection: close
Status: 406 Not Acceptable
Content-Security-Policy: default-src *; script-src assets-cdn.github.com collector-cdn.github.com; object-src assets-cdn.github.com; style-src 'self' 'unsafe-inline' 'unsafe-eval' assets-cdn.github.com; img-src 'self' data: assets-cdn.github.com identicons.github.com www.google-analytics.com collector.githubapp.com *.githubusercontent.com *.gravatar.com *.wp.com; media-src 'none'; frame-src 'self' render.githubusercontent.com gist.github.com www.youtube.com player.vimeo.com checkout.paypal.com; font-src assets-cdn.github.com; connect-src 'self' ghconduit.com:25035 live.github.com wss://live.github.com uploads.github.com www.google-analytics.com s3.amazonaws.com
Cache-Control: no-cache
Vary: X-PJAX
X-UA-Compatible: IE=Edge,chrome=1
Set-Cookie: [removed]
Set-Cookie: [removed]
X-Request-Id: e01c8d4236459d386b11960c3b52bb64
X-Runtime: 0.008242
X-Rack-Cache: miss
X-GitHub-Request-Id: 7922F19A:51F6:FB3C2BA:5509C989
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-Frame-Options: deny

1
 
0
```

**Comment by othiym23** [comment]
```
GET https://github.com/bitinn/onchange HTTP/1.1
version: 2.7.0
accept: application/x-tar, application/vnd.github+json; q=0.1
referer: install [REDACTED]
npm-session: 104096a1e025a1b4
user-agent: npm/2.7.0 node/v1.5.1 darwin x64
host: github.com
Connection: close
```

So the only weird thing I see there is that for some reason npm is trying to request the package repo page, instead of hanging that URL off to GitHub to clone as a repo, and I don't know why one machine would do that and not others. Is `registry` set to a non-default value on that machine?

**Comment by bitinn** [comment]
@othiym23 Nope, use default registry. I will look into it more tomorrow, but my rough guess is:

1. bitinn/onchange#gaze is converted into https://github.com/bitinn/onchange#gaze due to the bug you mention.
2. npm believe it's either requesting a json or a tarball (otherwise why use them as accept headers), while https://github.com/bitinn/onchange#gaze accepts neither, so 406 error is thrown.

If this is the case, I think this will happen on all machines.

**Comment by othiym23** [comment]
@bitinn That `accept` header is the one used by `npm-registry-client`'s `.fetch()` method, which is what it uses to download package tarballs from remote servers. The scenario you describe should _always_ cause the install to fail when using a GitHub shortcut in `package.json`, and when I use the `package.json` you provided up the page, everything installs fine. So there is definitely something strange going on on the affected machine. Have you tried running `npm cache clean` and trying again on that machine? It's possible the metadata in the cache has gotten confused somehow.

**Comment by bitinn** [comment]
@othiym23 I tried my test with another mac, and you are right, it's able to install with the same package.json, I can see a successful install adds `_git-remotes` to my npm cache folder.

`npm cache clean` doesn't fix the issue on the affected mac, unfortunately, but at least i know this bug doesn't trigger if i don't use shorthand.

In other news, this might be related to #7302

**Comment by bitinn** [comment]
As a sidenote, from my MITM proxy capture, I can see a successful install goes to `registry.npmjs.org` for dependencies, and the request to github doesn't go through HTTPS (probably git over ssh).

The affected mac goes straight to github url through HTTPS, and got the error 406 instead.

affected install:

```
npm install --verbose
npm info it worked if it ends with ok
npm verb cli [ 'node', '/usr/local/bin/npm', 'install', '--verbose' ]
npm info using npm@2.7.0
npm info using node@v1.5.1
npm verb node symlink /usr/local/bin/node
npm WARN package.json test@1.0.0 No description
npm WARN package.json test@1.0.0 No repository field.
npm WARN package.json test@1.0.0 No README data
npm verb install where, deps [ '/Users/teambegin/git/test', [ 'onchange' ] ]
npm verb install where, peers [ '/Users/teambegin/git/test', [] ]
npm info preinstall test@1.0.0
npm verb cache add spec onchange@https://github.com/bitinn/onchange#gaze
npm verb addRemoteTarball https://github.com/bitinn/onchange#gaze not in flight; adding
npm verb addRemoteTarball [ 'https://github.com/bitinn/onchange#gaze', null ]
npm info retry fetch attempt 1 at 13:49:12
npm info attempt registry request try #1 at 13:49:12
npm http fetch GET https://github.com/bitinn/onchange#gaze
npm verb request id 3f70c024c8972cb1
```

normal install:

```
npm install --verbose
npm info it worked if it ends with ok
npm verb cli [ '/usr/local/bin/iojs',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'install',
npm verb cli   '--verbose' ]
npm info using npm@2.7.0
npm info using node@v1.5.1
npm WARN package.json test@1.0.0 No description
npm WARN package.json test@1.0.0 No repository field.
npm WARN package.json test@1.0.0 No README data
npm verb install where, deps [ '/Users/df/git/test', [ 'onchange' ] ]
npm verb install where, peers [ '/Users/df/git/test', [] ]
npm info preinstall test@1.0.0
npm verb cache add spec onchange@git+https://github.com/bitinn/onchange#gaze
npm verb addRemoteGit u="https://github.com/bitinn/onchange#gaze" silent=false
npm verb addRemoteGit /Users/df/.npm/_git-remotes/https-github-com-bitinn-onchange-2c8c0b7f not in flight; cloning
npm info git [ 'config', '--get', 'remote.origin.url' ]
npm verb git remote.origin.url https://github.com/bitinn/onchange
npm info git [ 'fetch', '-a', 'origin' ]
```

**Comment by othiym23** [comment]
What does `npm ls -g read-package-json` show on the broken machine? What does `npm ls -g normalize-package-data` show?

**Comment by bitinn** [comment]
The broken one:

```
$ npm ls -g read-package-json
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/npmconf requires mkdirp@'~0.3.3' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/mkdirp,
npm WARN unmet dependency which is version 0.5.0
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/npmconf requires osenv@'0.0.3' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/osenv,
npm WARN unmet dependency which is version 0.1.0
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/npmconf requires nopt@'2' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/nopt,
npm WARN unmet dependency which is version 3.0.1
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/npmconf requires semver@'2' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/semver,
npm WARN unmet dependency which is version 4.3.1
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/npmconf requires ini@'~1.1.0' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/ini,
npm WARN unmet dependency which is version 1.3.3
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data requires github-url-from-username-repo@'^0.1.0' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/github-url-from-username-repo,
npm WARN unmet dependency which is version 1.0.2
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data requires semver@'2' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/semver,
npm WARN unmet dependency which is version 4.3.1
/usr/local/lib
└─┬ npm@2.7.0
  └── read-package-json@1.3.1 
```

```
$ npm ls -g normalize-package-data
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/npmconf requires mkdirp@'~0.3.3' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/mkdirp,
npm WARN unmet dependency which is version 0.5.0
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/npmconf requires osenv@'0.0.3' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/osenv,
npm WARN unmet dependency which is version 0.1.0
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/npmconf requires nopt@'2' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/nopt,
npm WARN unmet dependency which is version 3.0.1
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/npmconf requires semver@'2' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/semver,
npm WARN unmet dependency which is version 4.3.1
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/npmconf requires ini@'~1.1.0' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/ini,
npm WARN unmet dependency which is version 1.3.3
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data requires github-url-from-username-repo@'^0.1.0' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/github-url-from-username-repo,
npm WARN unmet dependency which is version 1.0.2
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data requires semver@'2' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/semver,
npm WARN unmet dependency which is version 4.3.1
/usr/local/lib
└─┬ npm@2.7.0
  ├── normalize-package-data@1.0.3 
  └─┬ read-package-json@1.3.1
    └── normalize-package-data@0.2.13  invalid

npm ERR! invalid: normalize-package-data@0.2.13 /usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data
```

The normal one:

```
$ npm ls -g normalize-package-data
/usr/local/lib
├─┬ npm@2.7.0
│ └── normalize-package-data@1.0.3 
└─┬ npm-check-updates@1.5.1
  ├─┬ npm@2.1.18
  │ └── normalize-package-data@1.0.3 
  └─┬ read-package-json@1.2.7
    └── normalize-package-data@1.0.3 

$ npm ls -g read-package-json
/usr/local/lib
├─┬ npm@2.7.0
│ └── read-package-json@1.3.1 
└─┬ npm-check-updates@1.5.1
  ├─┬ npm@2.1.18
  │ └── read-package-json@1.2.7 
  └── read-package-json@1.2.7 
```

**Comment by othiym23** [comment]
Wow. I should have had you do that at the start. The npm installation on the broken machine is indeed way broken. It looks like you ran `npm update -g` with a version where that command was broken. If you reinstall npm (`npm -g install npm`) on the broken machine, that should make it behave like all your other machines. I'm not going to say it fixes the bug, because I'm still working on [making it so that npm behaves more consistently](https://github.com/npm/normalize-package-data/pull/56) with GitHub shortcuts in the first place.

**Comment by bitinn** [comment]
@othiym23 yep that worked, thx! didn't know reinstalling io.js doesn't update old dependencies.

**Comment by othiym23** [comment]
It took a little bit of work, but npm has now been changed to always run GitHub URLs (regardless of how they're specified on the command-line or in `package.json`) run through the same process of trying `git:` first, and then falling back to `ssh:` to clone. There are probably some further documentation tweaks that need to happen to make this consistent with the documentation, but the inconsistency @bitinn saw between using `org/repo` on the command line and in `package.json` has been resolved.

**Comment by bitinn** [comment]
:+1:
