### ISSUE TITLE
Error: No version provided

### ISSUE THREAD

**Issue by icalderond** [npm/npm#7645]
```
Error: No version provided
npm ERR!     at needVersion (/usr/lib/node_modules/npm/lib/cache/add-local.js:144:40)
npm ERR!     at /usr/lib/node_modules/npm/lib/cache/add-local.js:77:10
npm ERR!     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:51:40
npm ERR!     at final (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:349:17)
npm ERR!     at then (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:126:33)
npm ERR!     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:316:48
npm ERR!     at evalmachine.<anonymous>:207:20
npm ERR!     at OpenReq.Req.done (/usr/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:141:5)
npm ERR!     at OpenReq.done (/usr/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:61:22)
npm ERR!     at Object.oncomplete (evalmachine.<anonymous>:107:15)
```

**Comment by KenanY** [comment]
@icalderond Do you have a `package.json` in your current working directory? Could you upload the entire `npm-debug.log` as a [gist](https://gist.github.com/) instead of only posting a portion of it?

**Comment by KenanY** [comment]
@icalderond ping? :)

**Comment by icalderond** [comment]
Thanks. This problem a resolved creating a new proyect. :+1:  Thanks
