### ISSUE TITLE
can't login

### ISSUE THREAD

**Issue by iccicci** [npm/npm#7658]
```
cicci@ubuntu /media/cicci/73faec83-b365-4edc-bb19-1a249579c675/home/cicci/workspace/pgo (master) $ npm adduser --always-auth
Username: cicci
Password:
Email: daniele.icc@gmail.com
npm http PUT https://registry.npmjs.org/-/user/org.couchdb.user:cicci
npm http 409 https://registry.npmjs.org/-/user/org.couchdb.user:cicci
npm http GET https://registry.npmjs.org/-/user/org.couchdb.user:cicci
npm http 200 https://registry.npmjs.org/-/user/org.couchdb.user:cicci
npm http PUT https://registry.npmjs.org/-/user/org.couchdb.user:cicci/-rev/undefined
npm http 400 https://registry.npmjs.org/-/user/org.couchdb.user:cicci/-rev/undefined
npm ERR! Error: bad_request Invalid rev format: -/user/org.couchdb.user:cicci/-rev/undefined
npm ERR!     at RegClient.<anonymous> (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:272:14)
npm ERR!     at Request.self.callback (/usr/lib/nodejs/request/index.js:148:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/index.js:896:14)
npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/lib/nodejs/request/index.js:847:12)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-46-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "adduser" "--always-auth"
npm ERR! cwd /media/cicci/73faec83-b365-4edc-bb19-1a249579c675/home/cicci/workspace/pgo
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /media/cicci/73faec83-b365-4edc-bb19-1a249579c675/home/cicci/workspace/pgo/npm-debug.log
npm ERR! not ok code 0
```

even if

```
root@ubuntu:~# npm install -g npm@latest
npm http GET https://registry.npmjs.org/npm
npm http 304 https://registry.npmjs.org/npm
/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
npm@2.7.1 /usr/local/lib/node_modules/npm
```

please help me login

**Comment by KenanY** [comment]
@iccicci So you get the same error when you use `npm@2.7.1` (the log shows `npm@1.3.10`)?

**Comment by iccicci** [comment]
Thank you for your quick reply,

maybe the npm I have in my PATH is 1.3.10.
How can I know where npm install -g npm installs the new version?

Thank you,
iCC

**Comment by KenanY** [comment]
@iccicci It is displayed at the end of a successful installation. From your original post:

```
/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
npm@2.7.1 /usr/local/lib/node_modules/npm
```

**Comment by iccicci** [comment]
What to say?

It's now clear I'm drunk :)

Thank you very much.

**Comment by othiym23** [comment]
Closing as resolved.
