### ISSUE TITLE
for help:install grunt error

### ISSUE THREAD

**Issue by limerickgds** [npm/npm#7676]
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'grunt',
1 verbose cli   '-g' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 silly cache add args [ 'grunt', null ]
6 verbose cache add spec grunt
7 silly cache add parsed spec { raw: 'grunt',
7 silly cache add   scope: null,
7 silly cache add   name: 'grunt',
7 silly cache add   rawSpec: '',
7 silly cache add   spec: '*',
7 silly cache add   type: 'range' }
8 verbose addNamed grunt@*
9 silly addNamed semver.valid null
10 silly addNamed semver.validRange *
11 silly addNameRange { name: 'grunt', range: '*', hasData: false }
12 silly mapToRegistry name grunt
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/grunt
16 verbose addNameRange registry:https://registry.npmjs.org/grunt not in flight; fetching
17 verbose request uri https://registry.npmjs.org/grunt
18 verbose request no auth needed
19 info attempt registry request try #1 at 11:25:29
20 verbose request id 84619e6daf9124c7
21 http request GET https://registry.npmjs.org/grunt
22 info retry will retry, error on last attempt: Error: read ECONNRESET
23 info attempt registry request try #2 at 11:28:10
24 http request GET https://registry.npmjs.org/grunt
25 info retry will retry, error on last attempt: Error: read ECONNRESET
26 info attempt registry request try #3 at 11:31:22
27 http request GET https://registry.npmjs.org/grunt
28 verbose stack Error: read ECONNRESET
28 verbose stack     at exports._errnoException (util.js:746:11)
28 verbose stack     at TCP.onread (net.js:550:26)
29 verbose cwd C:\Users\guods
30 error Windows_NT 6.1.7601
31 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "grunt" "-g"
32 error node v0.12.0
33 error npm  v2.5.1
34 error code ECONNRESET
35 error errno ECONNRESET
36 error syscall read
37 error network read ECONNRESET
37 error network This is most likely not a problem with npm itself
37 error network and is related to network connectivity.
37 error network In most cases you are behind a proxy or have bad network settings.
37 error network
37 error network If you are behind a proxy, please make sure that the
37 error network 'proxy' config is set properly.  See: 'npm help config'
38 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
@limerickgds As the error message states, this is most likely an issue with your network connection. Are you behind a proxy by any chance?

**Comment by limerickgds** [comment]
@KenanY   proxy of our company has  some problems, proxy was back to normal today, thank you for your reply.

**Comment by ehsalazar** [comment]
Good to hear.  I'll close this for now as we’re trying to clean up some old issues. We’ll be happy to reopen if necessary.
