### ISSUE TITLE
bower || grunt installation problem, waiting for you help

### ISSUE THREAD

**Issue by JIBIN009** [npm/npm#7677]
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@1.2.14
3 info using node@v0.8.22
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 verbose read json C:\Users\pc\git\ng-boilerplate\package.json
6 verbose readDependencies using package.json deps
7 verbose install where, deps [ 'C:\\Users\\pc\\git\\ng-boilerplate',
7 verbose install   [ 'grunt',
7 verbose install     'grunt-bump',
7 verbose install     'grunt-coffeelint',
7 verbose install     'grunt-contrib-clean',
7 verbose install     'grunt-contrib-coffee',
7 verbose install     'grunt-contrib-concat',
7 verbose install     'grunt-contrib-copy',
7 verbose install     'grunt-contrib-jshint',
7 verbose install     'grunt-contrib-less',
7 verbose install     'grunt-contrib-uglify',
7 verbose install     'grunt-contrib-watch',
7 verbose install     'grunt-conventional-changelog',
7 verbose install     'grunt-html2js',
7 verbose install     'grunt-karma',
7 verbose install     'grunt-ng-annotate',
7 verbose install     'karma',
7 verbose install     'karma-coffee-preprocessor',
7 verbose install     'karma-firefox-launcher',
7 verbose install     'karma-jasmine' ] ]
8 verbose from cache C:\Users\pc\git\ng-boilerplate\package.json
9 info preinstall ngbp@0.3.2
10 verbose read json C:\Users\pc\git\ng-boilerplate\node_modules\bower\package.json
11 verbose read json C:\Users\pc\git\ng-boilerplate\node_modules\cli\package.json
12 verbose read json C:\Users\pc\git\ng-boilerplate\node_modules\coffeelint\package.json
13 verbose read json C:\Users\pc\git\ng-boilerplate\node_modules\grunt\package.json
14 verbose read json C:\Users\pc\git\ng-boilerplate\node_modules\grunt-bump\package.json
15 verbose read json C:\Users\pc\git\ng-boilerplate\node_modules\grunt-coffeelint\package.json
16 verbose read json C:\Users\pc\git\ng-boilerplate\node_modules\grunt-contrib-clean\package.json
17 verbose read json C:\Users\pc\git\ng-boilerplate\node_modules\grunt-contrib-coffee\package.json
18 verbose read json C:\Users\pc\git\ng-boilerplate\node_modules\grunt-contrib-concat\package.json
19 verbose read json C:\Users\pc\git\ng-boilerplate\node_modules\grunt-contrib-copy\package.json
20 verbose read json C:\Users\pc\git\ng-boilerplate\node_modules\grunt-contrib-jshint\package.json
21 verbose read json C:\Users\pc\git\ng-boilerplate\node_modules\grunt-contrib-less\package.json
22 verbose read json C:\Users\pc\git\ng-boilerplate\node_modules\grunt-contrib-uglify\package.json
23 verbose read json C:\Users\pc\git\ng-boilerplate\node_modules\grunt-contrib-watch\package.json
24 verbose read json C:\Users\pc\git\ng-boilerplate\node_modules\grunt-conventional-changelog\package.json
25 verbose read json C:\Users\pc\git\ng-boilerplate\node_modules\grunt-html2js\package.json
26 verbose read json C:\Users\pc\git\ng-boilerplate\node_modules\grunt-karma\package.json
27 verbose read json C:\Users\pc\git\ng-boilerplate\node_modules\grunt-ng-annotate\package.json
28 verbose read json C:\Users\pc\git\ng-boilerplate\node_modules\karma\package.json
29 verbose read json C:\Users\pc\git\ng-boilerplate\node_modules\karma-coffee-preprocessor\package.json
30 verbose read json C:\Users\pc\git\ng-boilerplate\node_modules\karma-firefox-launcher\package.json
31 verbose read json C:\Users\pc\git\ng-boilerplate\node_modules\karma-jasmine\package.json
32 verbose from cache C:\Users\pc\git\ng-boilerplate\package.json
33 verbose readDependencies using package.json deps
34 verbose read json C:\Users\pc\git\ng-boilerplate\node_modules\bower\package.json
35 verbose from cache C:\Users\pc\git\ng-boilerplate\node_modules\cli\package.json
36 verbose from cache C:\Users\pc\git\ng-boilerplate\node_modules\coffeelint\package.json
37 verbose from cache C:\Users\pc\git\ng-boilerplate\node_modules\grunt\package.json
38 verbose from cache C:\Users\pc\git\ng-boilerplate\node_modules\grunt-bump\package.json
39 verbose from cache C:\Users\pc\git\ng-boilerplate\node_modules\grunt-coffeelint\package.json
40 verbose from cache C:\Users\pc\git\ng-boilerplate\node_modules\grunt-contrib-clean\package.json
41 verbose from cache C:\Users\pc\git\ng-boilerplate\node_modules\grunt-contrib-coffee\package.json
42 verbose from cache C:\Users\pc\git\ng-boilerplate\node_modules\grunt-contrib-concat\package.json
43 verbose from cache C:\Users\pc\git\ng-boilerplate\node_modules\grunt-contrib-copy\package.json
44 verbose from cache C:\Users\pc\git\ng-boilerplate\node_modules\grunt-contrib-jshint\package.json
45 verbose from cache C:\Users\pc\git\ng-boilerplate\node_modules\grunt-contrib-less\package.json
46 verbose from cache C:\Users\pc\git\ng-boilerplate\node_modules\grunt-contrib-uglify\package.json
47 verbose from cache C:\Users\pc\git\ng-boilerplate\node_modules\grunt-contrib-watch\package.json
48 verbose from cache C:\Users\pc\git\ng-boilerplate\node_modules\grunt-conventional-changelog\package.json
49 verbose from cache C:\Users\pc\git\ng-boilerplate\node_modules\grunt-html2js\package.json
50 verbose from cache C:\Users\pc\git\ng-boilerplate\node_modules\grunt-karma\package.json
51 verbose from cache C:\Users\pc\git\ng-boilerplate\node_modules\grunt-ng-annotate\package.json
52 verbose read json C:\Users\pc\git\ng-boilerplate\node_modules\karma\package.json
53 verbose from cache C:\Users\pc\git\ng-boilerplate\node_modules\karma-coffee-preprocessor\package.json
54 verbose from cache C:\Users\pc\git\ng-boilerplate\node_modules\karma-firefox-launcher\package.json
55 verbose from cache C:\Users\pc\git\ng-boilerplate\node_modules\karma-jasmine\package.json
56 verbose cache add [ 'karma-firefox-launcher@^0.1.3', null ]
57 verbose cache add name=undefined spec="karma-firefox-launcher@^0.1.3" args=["karma-firefox-launcher@^0.1.3",null]
58 verbose parsed url { pathname: 'karma-firefox-launcher@^0.1.3',
58 verbose parsed url   path: 'karma-firefox-launcher@^0.1.3',
58 verbose parsed url   href: 'karma-firefox-launcher@^0.1.3' }
59 verbose cache add name="karma-firefox-launcher" spec="^0.1.3" args=["karma-firefox-launcher","^0.1.3"]
60 verbose parsed url { pathname: '^0.1.3', path: '^0.1.3', href: '^0.1.3' }
61 verbose addNamed [ 'karma-firefox-launcher', '^0.1.3' ]
62 verbose addNamed [ null, null ]
63 verbose cache add [ 'karma-jasmine@^0.1.5', null ]
64 verbose cache add name=undefined spec="karma-jasmine@^0.1.5" args=["karma-jasmine@^0.1.5",null]
65 verbose parsed url { pathname: 'karma-jasmine@^0.1.5',
65 verbose parsed url   path: 'karma-jasmine@^0.1.5',
65 verbose parsed url   href: 'karma-jasmine@^0.1.5' }
66 verbose cache add name="karma-jasmine" spec="^0.1.5" args=["karma-jasmine","^0.1.5"]
67 verbose parsed url { pathname: '^0.1.5', path: '^0.1.5', href: '^0.1.5' }
68 verbose addNamed [ 'karma-jasmine', '^0.1.5' ]
69 verbose addNamed [ null, null ]
70 silly lockFile d6cf90b9-karma-firefox-launcher-0-1-3 karma-firefox-launcher@^0.1.3
71 verbose lock karma-firefox-launcher@^0.1.3 C:\Users\pc\AppData\Roaming\npm-cache\d6cf90b9-karma-firefox-launcher-0-1-3.lock
72 silly lockFile 36fc1519-karma-jasmine-0-1-5 karma-jasmine@^0.1.5
73 verbose lock karma-jasmine@^0.1.5 C:\Users\pc\AppData\Roaming\npm-cache\36fc1519-karma-jasmine-0-1-5.lock
74 info addNameTag [ 'karma-firefox-launcher', '^0.1.3' ]
75 verbose url raw karma-firefox-launcher
76 verbose url resolving [ 'https://registry.npmjs.org/', './karma-firefox-launcher' ]
77 verbose url resolved https://registry.npmjs.org/karma-firefox-launcher
78 info trying registry request attempt 1 at 12:06:06
79 http GET https://registry.npmjs.org/karma-firefox-launcher
80 verbose already installed skipping grunt@~0.4.1 C:\Users\pc\git\ng-boilerplate
81 verbose already installed skipping grunt-bump@0.0.6 C:\Users\pc\git\ng-boilerplate
82 verbose already installed skipping grunt-coffeelint@~0.0.10 C:\Users\pc\git\ng-boilerplate
83 verbose cache add [ 'grunt-contrib-clean@^0.4.1', null ]
84 verbose cache add name=undefined spec="grunt-contrib-clean@^0.4.1" args=["grunt-contrib-clean@^0.4.1",null]
85 verbose parsed url { pathname: 'grunt-contrib-clean@^0.4.1',
85 verbose parsed url   path: 'grunt-contrib-clean@^0.4.1',
85 verbose parsed url   href: 'grunt-contrib-clean@^0.4.1' }
86 verbose cache add name="grunt-contrib-clean" spec="^0.4.1" args=["grunt-contrib-clean","^0.4.1"]
87 verbose parsed url { pathname: '^0.4.1', path: '^0.4.1', href: '^0.4.1' }
88 verbose addNamed [ 'grunt-contrib-clean', '^0.4.1' ]
89 verbose addNamed [ null, null ]
90 silly lockFile 5c2500b1-grunt-contrib-clean-0-4-1 grunt-contrib-clean@^0.4.1
91 verbose lock grunt-contrib-clean@^0.4.1 C:\Users\pc\AppData\Roaming\npm-cache\5c2500b1-grunt-contrib-clean-0-4-1.lock
92 verbose cache add [ 'grunt-contrib-coffee@^0.7.0', null ]
93 verbose cache add name=undefined spec="grunt-contrib-coffee@^0.7.0" args=["grunt-contrib-coffee@^0.7.0",null]
94 verbose parsed url { pathname: 'grunt-contrib-coffee@^0.7.0',
94 verbose parsed url   path: 'grunt-contrib-coffee@^0.7.0',
94 verbose parsed url   href: 'grunt-contrib-coffee@^0.7.0' }
95 verbose cache add name="grunt-contrib-coffee" spec="^0.7.0" args=["grunt-contrib-coffee","^0.7.0"]
96 verbose parsed url { pathname: '^0.7.0', path: '^0.7.0', href: '^0.7.0' }
97 verbose addNamed [ 'grunt-contrib-coffee', '^0.7.0' ]
98 verbose addNamed [ null, null ]
99 silly lockFile b1f05967-grunt-contrib-coffee-0-7-0 grunt-contrib-coffee@^0.7.0
100 verbose lock grunt-contrib-coffee@^0.7.0 C:\Users\pc\AppData\Roaming\npm-cache\b1f05967-grunt-contrib-coffee-0-7-0.lock
101 verbose cache add [ 'grunt-contrib-concat@^0.3.0', null ]
102 verbose cache add name=undefined spec="grunt-contrib-concat@^0.3.0" args=["grunt-contrib-concat@^0.3.0",null]
103 verbose parsed url { pathname: 'grunt-contrib-concat@^0.3.0',
103 verbose parsed url   path: 'grunt-contrib-concat@^0.3.0',
103 verbose parsed url   href: 'grunt-contrib-concat@^0.3.0' }
104 verbose cache add name="grunt-contrib-concat" spec="^0.3.0" args=["grunt-contrib-concat","^0.3.0"]
105 verbose parsed url { pathname: '^0.3.0', path: '^0.3.0', href: '^0.3.0' }
106 verbose addNamed [ 'grunt-contrib-concat', '^0.3.0' ]
107 verbose addNamed [ null, null ]
108 silly lockFile fd04becf-grunt-contrib-concat-0-3-0 grunt-contrib-concat@^0.3.0
109 verbose lock grunt-contrib-concat@^0.3.0 C:\Users\pc\AppData\Roaming\npm-cache\fd04becf-grunt-contrib-concat-0-3-0.lock
110 verbose cache add [ 'grunt-contrib-copy@^0.4.1', null ]
111 verbose cache add name=undefined spec="grunt-contrib-copy@^0.4.1" args=["grunt-contrib-copy@^0.4.1",null]
112 verbose parsed url { pathname: 'grunt-contrib-copy@^0.4.1',
112 verbose parsed url   path: 'grunt-contrib-copy@^0.4.1',
112 verbose parsed url   href: 'grunt-contrib-copy@^0.4.1' }
113 verbose cache add name="grunt-contrib-copy" spec="^0.4.1" args=["grunt-contrib-copy","^0.4.1"]
114 verbose parsed url { pathname: '^0.4.1', path: '^0.4.1', href: '^0.4.1' }
115 verbose addNamed [ 'grunt-contrib-copy', '^0.4.1' ]
116 verbose addNamed [ null, null ]
117 silly lockFile ae6ba2b9-grunt-contrib-copy-0-4-1 grunt-contrib-copy@^0.4.1
118 verbose lock grunt-contrib-copy@^0.4.1 C:\Users\pc\AppData\Roaming\npm-cache\ae6ba2b9-grunt-contrib-copy-0-4-1.lock
119 verbose cache add [ 'grunt-contrib-jshint@^0.4.3', null ]
120 verbose cache add name=undefined spec="grunt-contrib-jshint@^0.4.3" args=["grunt-contrib-jshint@^0.4.3",null]
121 verbose parsed url { pathname: 'grunt-contrib-jshint@^0.4.3',
121 verbose parsed url   path: 'grunt-contrib-jshint@^0.4.3',
121 verbose parsed url   href: 'grunt-contrib-jshint@^0.4.3' }
122 verbose cache add name="grunt-contrib-jshint" spec="^0.4.3" args=["grunt-contrib-jshint","^0.4.3"]
123 verbose parsed url { pathname: '^0.4.3', path: '^0.4.3', href: '^0.4.3' }
124 verbose addNamed [ 'grunt-contrib-jshint', '^0.4.3' ]
125 verbose addNamed [ null, null ]
126 silly lockFile ddc007ae-grunt-contrib-jshint-0-4-3 grunt-contrib-jshint@^0.4.3
127 verbose lock grunt-contrib-jshint@^0.4.3 C:\Users\pc\AppData\Roaming\npm-cache\ddc007ae-grunt-contrib-jshint-0-4-3.lock
128 verbose already installed skipping grunt-contrib-less@~0.11.0 C:\Users\pc\git\ng-boilerplate
129 verbose cache add [ 'grunt-contrib-uglify@^0.2.7', null ]
130 verbose cache add name=undefined spec="grunt-contrib-uglify@^0.2.7" args=["grunt-contrib-uglify@^0.2.7",null]
131 verbose parsed url { pathname: 'grunt-contrib-uglify@^0.2.7',
131 verbose parsed url   path: 'grunt-contrib-uglify@^0.2.7',
131 verbose parsed url   href: 'grunt-contrib-uglify@^0.2.7' }
132 verbose cache add name="grunt-contrib-uglify" spec="^0.2.7" args=["grunt-contrib-uglify","^0.2.7"]
133 verbose parsed url { pathname: '^0.2.7', path: '^0.2.7', href: '^0.2.7' }
134 verbose addNamed [ 'grunt-contrib-uglify', '^0.2.7' ]
135 verbose addNamed [ null, null ]
136 silly lockFile fcf54ddd-grunt-contrib-uglify-0-2-7 grunt-contrib-uglify@^0.2.7
137 verbose lock grunt-contrib-uglify@^0.2.7 C:\Users\pc\AppData\Roaming\npm-cache\fcf54ddd-grunt-contrib-uglify-0-2-7.lock
138 verbose cache add [ 'grunt-contrib-watch@^0.4.4', null ]
139 verbose cache add name=undefined spec="grunt-contrib-watch@^0.4.4" args=["grunt-contrib-watch@^0.4.4",null]
140 verbose parsed url { pathname: 'grunt-contrib-watch@^0.4.4',
140 verbose parsed url   path: 'grunt-contrib-watch@^0.4.4',
140 verbose parsed url   href: 'grunt-contrib-watch@^0.4.4' }
141 verbose cache add name="grunt-contrib-watch" spec="^0.4.4" args=["grunt-contrib-watch","^0.4.4"]
142 verbose parsed url { pathname: '^0.4.4', path: '^0.4.4', href: '^0.4.4' }
143 verbose addNamed [ 'grunt-contrib-watch', '^0.4.4' ]
144 verbose addNamed [ null, null ]
145 silly lockFile 51612dac-grunt-contrib-watch-0-4-4 grunt-contrib-watch@^0.4.4
146 verbose lock grunt-contrib-watch@^0.4.4 C:\Users\pc\AppData\Roaming\npm-cache\51612dac-grunt-contrib-watch-0-4-4.lock
147 verbose cache add [ 'grunt-conventional-changelog@^0.1.2', null ]
148 verbose cache add name=undefined spec="grunt-conventional-changelog@^0.1.2" args=["grunt-conventional-changelog@^0.1.2",null]
149 verbose parsed url { pathname: 'grunt-conventional-changelog@^0.1.2',
149 verbose parsed url   path: 'grunt-conventional-changelog@^0.1.2',
149 verbose parsed url   href: 'grunt-conventional-changelog@^0.1.2' }
150 verbose cache add name="grunt-conventional-changelog" spec="^0.1.2" args=["grunt-conventional-changelog","^0.1.2"]
151 verbose parsed url { pathname: '^0.1.2', path: '^0.1.2', href: '^0.1.2' }
152 verbose addNamed [ 'grunt-conventional-changelog', '^0.1.2' ]
153 verbose addNamed [ null, null ]
154 silly lockFile 6f1f130b-unt-conventional-changelog-0-1-2 grunt-conventional-changelog@^0.1.2
155 verbose lock grunt-conventional-changelog@^0.1.2 C:\Users\pc\AppData\Roaming\npm-cache\6f1f130b-unt-conventional-changelog-0-1-2.lock
156 verbose cache add [ 'grunt-html2js@^0.1.9', null ]
157 verbose cache add name=undefined spec="grunt-html2js@^0.1.9" args=["grunt-html2js@^0.1.9",null]
158 verbose parsed url { pathname: 'grunt-html2js@^0.1.9',
158 verbose parsed url   path: 'grunt-html2js@^0.1.9',
158 verbose parsed url   href: 'grunt-html2js@^0.1.9' }
159 verbose cache add name="grunt-html2js" spec="^0.1.9" args=["grunt-html2js","^0.1.9"]
160 verbose parsed url { pathname: '^0.1.9', path: '^0.1.9', href: '^0.1.9' }
161 verbose addNamed [ 'grunt-html2js', '^0.1.9' ]
162 verbose addNamed [ null, null ]
163 silly lockFile b987d3ea-grunt-html2js-0-1-9 grunt-html2js@^0.1.9
164 verbose lock grunt-html2js@^0.1.9 C:\Users\pc\AppData\Roaming\npm-cache\b987d3ea-grunt-html2js-0-1-9.lock
165 verbose cache add [ 'grunt-karma@^0.8.2', null ]
166 verbose cache add name=undefined spec="grunt-karma@^0.8.2" args=["grunt-karma@^0.8.2",null]
167 verbose parsed url { pathname: 'grunt-karma@^0.8.2',
167 verbose parsed url   path: 'grunt-karma@^0.8.2',
167 verbose parsed url   href: 'grunt-karma@^0.8.2' }
168 verbose cache add name="grunt-karma" spec="^0.8.2" args=["grunt-karma","^0.8.2"]
169 verbose parsed url { pathname: '^0.8.2', path: '^0.8.2', href: '^0.8.2' }
170 verbose addNamed [ 'grunt-karma', '^0.8.2' ]
171 verbose addNamed [ null, null ]
172 silly lockFile d1a0ac00-grunt-karma-0-8-2 grunt-karma@^0.8.2
173 verbose lock grunt-karma@^0.8.2 C:\Users\pc\AppData\Roaming\npm-cache\d1a0ac00-grunt-karma-0-8-2.lock
174 verbose cache add [ 'grunt-ng-annotate@^0.8.0', null ]
175 verbose cache add name=undefined spec="grunt-ng-annotate@^0.8.0" args=["grunt-ng-annotate@^0.8.0",null]
176 verbose parsed url { pathname: 'grunt-ng-annotate@^0.8.0',
176 verbose parsed url   path: 'grunt-ng-annotate@^0.8.0',
176 verbose parsed url   href: 'grunt-ng-annotate@^0.8.0' }
177 verbose cache add name="grunt-ng-annotate" spec="^0.8.0" args=["grunt-ng-annotate","^0.8.0"]
178 verbose parsed url { pathname: '^0.8.0', path: '^0.8.0', href: '^0.8.0' }
179 verbose addNamed [ 'grunt-ng-annotate', '^0.8.0' ]
180 verbose addNamed [ null, null ]
181 silly lockFile 92ea19d7-grunt-ng-annotate-0-8-0 grunt-ng-annotate@^0.8.0
182 verbose lock grunt-ng-annotate@^0.8.0 C:\Users\pc\AppData\Roaming\npm-cache\92ea19d7-grunt-ng-annotate-0-8-0.lock
183 verbose cache add [ 'karma@^0.12.9', null ]
184 verbose cache add name=undefined spec="karma@^0.12.9" args=["karma@^0.12.9",null]
185 verbose parsed url { pathname: 'karma@^0.12.9',
185 verbose parsed url   path: 'karma@^0.12.9',
185 verbose parsed url   href: 'karma@^0.12.9' }
186 verbose cache add name="karma" spec="^0.12.9" args=["karma","^0.12.9"]
187 verbose parsed url { pathname: '^0.12.9', path: '^0.12.9', href: '^0.12.9' }
188 verbose addNamed [ 'karma', '^0.12.9' ]
189 verbose addNamed [ null, null ]
190 silly lockFile 5f69ed86-karma-0-12-9 karma@^0.12.9
191 verbose lock karma@^0.12.9 C:\Users\pc\AppData\Roaming\npm-cache\5f69ed86-karma-0-12-9.lock
192 verbose cache add [ 'karma-coffee-preprocessor@^0.2.1', null ]
193 verbose cache add name=undefined spec="karma-coffee-preprocessor@^0.2.1" args=["karma-coffee-preprocessor@^0.2.1",null]
194 verbose parsed url { pathname: 'karma-coffee-preprocessor@^0.2.1',
194 verbose parsed url   path: 'karma-coffee-preprocessor@^0.2.1',
194 verbose parsed url   href: 'karma-coffee-preprocessor@^0.2.1' }
195 verbose cache add name="karma-coffee-preprocessor" spec="^0.2.1" args=["karma-coffee-preprocessor","^0.2.1"]
196 verbose parsed url { pathname: '^0.2.1', path: '^0.2.1', href: '^0.2.1' }
197 verbose addNamed [ 'karma-coffee-preprocessor', '^0.2.1' ]
198 verbose addNamed [ null, null ]
199 silly lockFile 190b9078-karma-coffee-preprocessor-0-2-1 karma-coffee-preprocessor@^0.2.1
200 verbose lock karma-coffee-preprocessor@^0.2.1 C:\Users\pc\AppData\Roaming\npm-cache\190b9078-karma-coffee-preprocessor-0-2-1.lock
201 info addNameTag [ 'karma-jasmine', '^0.1.5' ]
202 info addNameTag [ 'grunt-contrib-coffee', '^0.7.0' ]
203 info addNameTag [ 'grunt-contrib-clean', '^0.4.1' ]
204 info addNameTag [ 'grunt-contrib-concat', '^0.3.0' ]
205 info addNameTag [ 'grunt-contrib-jshint', '^0.4.3' ]
206 info addNameTag [ 'grunt-contrib-copy', '^0.4.1' ]
207 info addNameTag [ 'grunt-contrib-uglify', '^0.2.7' ]
208 info addNameTag [ 'grunt-contrib-watch', '^0.4.4' ]
209 info addNameTag [ 'grunt-conventional-changelog', '^0.1.2' ]
210 info addNameTag [ 'grunt-html2js', '^0.1.9' ]
211 info addNameTag [ 'grunt-karma', '^0.8.2' ]
212 info addNameTag [ 'grunt-ng-annotate', '^0.8.0' ]
213 verbose url raw karma-jasmine
214 verbose url resolving [ 'https://registry.npmjs.org/', './karma-jasmine' ]
215 verbose url resolved https://registry.npmjs.org/karma-jasmine
216 info trying registry request attempt 1 at 12:06:06
217 http GET https://registry.npmjs.org/karma-jasmine
218 verbose url raw grunt-contrib-coffee
219 verbose url resolving [ 'https://registry.npmjs.org/', './grunt-contrib-coffee' ]
220 verbose url resolved https://registry.npmjs.org/grunt-contrib-coffee
221 info trying registry request attempt 1 at 12:06:06
222 http GET https://registry.npmjs.org/grunt-contrib-coffee
223 verbose url raw grunt-contrib-clean
224 verbose url resolving [ 'https://registry.npmjs.org/', './grunt-contrib-clean' ]
225 verbose url resolved https://registry.npmjs.org/grunt-contrib-clean
226 info trying registry request attempt 1 at 12:06:06
227 http GET https://registry.npmjs.org/grunt-contrib-clean
228 info addNameTag [ 'karma', '^0.12.9' ]
229 verbose url raw grunt-contrib-concat
230 verbose url resolving [ 'https://registry.npmjs.org/', './grunt-contrib-concat' ]
231 verbose url resolved https://registry.npmjs.org/grunt-contrib-concat
232 info trying registry request attempt 1 at 12:06:06
233 http GET https://registry.npmjs.org/grunt-contrib-concat
234 verbose url raw grunt-contrib-jshint
235 verbose url resolving [ 'https://registry.npmjs.org/', './grunt-contrib-jshint' ]
236 verbose url resolved https://registry.npmjs.org/grunt-contrib-jshint
237 info trying registry request attempt 1 at 12:06:06
238 http GET https://registry.npmjs.org/grunt-contrib-jshint
239 verbose url raw grunt-contrib-copy
240 verbose url resolving [ 'https://registry.npmjs.org/', './grunt-contrib-copy' ]
241 verbose url resolved https://registry.npmjs.org/grunt-contrib-copy
242 info trying registry request attempt 1 at 12:06:06
243 http GET https://registry.npmjs.org/grunt-contrib-copy
244 verbose url raw grunt-contrib-uglify
245 verbose url resolving [ 'https://registry.npmjs.org/', './grunt-contrib-uglify' ]
246 verbose url resolved https://registry.npmjs.org/grunt-contrib-uglify
247 info trying registry request attempt 1 at 12:06:06
248 http GET https://registry.npmjs.org/grunt-contrib-uglify
249 verbose url raw grunt-contrib-watch
250 verbose url resolving [ 'https://registry.npmjs.org/', './grunt-contrib-watch' ]
251 verbose url resolved https://registry.npmjs.org/grunt-contrib-watch
252 info trying registry request attempt 1 at 12:06:06
253 http GET https://registry.npmjs.org/grunt-contrib-watch
254 verbose url raw grunt-conventional-changelog
255 verbose url resolving [ 'https://registry.npmjs.org/',
255 verbose url resolving   './grunt-conventional-changelog' ]
256 verbose url resolved https://registry.npmjs.org/grunt-conventional-changelog
257 info trying registry request attempt 1 at 12:06:06
258 http GET https://registry.npmjs.org/grunt-conventional-changelog
259 verbose url raw grunt-html2js
260 verbose url resolving [ 'https://registry.npmjs.org/', './grunt-html2js' ]
261 verbose url resolved https://registry.npmjs.org/grunt-html2js
262 info trying registry request attempt 1 at 12:06:06
263 http GET https://registry.npmjs.org/grunt-html2js
264 verbose url raw grunt-karma
265 verbose url resolving [ 'https://registry.npmjs.org/', './grunt-karma' ]
266 verbose url resolved https://registry.npmjs.org/grunt-karma
267 info trying registry request attempt 1 at 12:06:06
268 http GET https://registry.npmjs.org/grunt-karma
269 verbose url raw grunt-ng-annotate
270 verbose url resolving [ 'https://registry.npmjs.org/', './grunt-ng-annotate' ]
271 verbose url resolved https://registry.npmjs.org/grunt-ng-annotate
272 info trying registry request attempt 1 at 12:06:06
273 http GET https://registry.npmjs.org/grunt-ng-annotate
274 info addNameTag [ 'karma-coffee-preprocessor', '^0.2.1' ]
275 verbose url raw karma-coffee-preprocessor
276 verbose url resolving [ 'https://registry.npmjs.org/', './karma-coffee-preprocessor' ]
277 verbose url resolved https://registry.npmjs.org/karma-coffee-preprocessor
278 info trying registry request attempt 1 at 12:06:06
279 http GET https://registry.npmjs.org/karma-coffee-preprocessor
280 verbose url raw karma
281 verbose url resolving [ 'https://registry.npmjs.org/', './karma' ]
282 verbose url resolved https://registry.npmjs.org/karma
283 info trying registry request attempt 1 at 12:06:07
284 verbose etag "4PPE2KP2IBTC4Q5ZE8YX3B3U5"
285 http GET https://registry.npmjs.org/karma
286 http 200 https://registry.npmjs.org/karma-firefox-launcher
287 silly registry.get cb [ 200,
287 silly registry.get   { date: 'Thu, 19 Mar 2015 06:36:05 GMT',
287 silly registry.get     server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
287 silly registry.get     etag: '"EMGF88GTL8LGEVEXY38TWCBP7"',
287 silly registry.get     'content-type': 'application/json',
287 silly registry.get     'cache-control': 'max-age=60',
287 silly registry.get     'content-length': '12127',
287 silly registry.get     'accept-ranges': 'bytes',
287 silly registry.get     via: '1.1 varnish',
287 silly registry.get     age: '3',
287 silly registry.get     'x-served-by': 'cache-lax1422-LAX',
287 silly registry.get     'x-cache': 'HIT',
287 silly registry.get     'x-cache-hits': '1',
287 silly registry.get     'x-timer': 'S1426746965.863703,VS0,VE0',
287 silly registry.get     vary: 'Accept',
287 silly registry.get     'keep-alive': 'timeout=10, max=50',
287 silly registry.get     connection: 'Keep-Alive' } ]
288 silly lockFile d6cf90b9-karma-firefox-launcher-0-1-3 karma-firefox-launcher@^0.1.3
289 silly lockFile d6cf90b9-karma-firefox-launcher-0-1-3 karma-firefox-launcher@^0.1.3
290 error Error: No compatible version found: karma-firefox-launcher@'^0.1.3'
290 error Valid install targets:
290 error ["0.0.1","0.0.2","0.0.3","0.1.0","0.1.1","0.1.2","0.1.3","0.1.4"]
290 error     at installTargetsError (C:\Program Files\nodejs\node_modules\npm\lib\cache.js:682:10)
290 error     at C:\Program Files\nodejs\node_modules\npm\lib\cache.js:597:10
290 error     at saved (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\get.js:138:7)
290 error     at Object.oncomplete (fs.js:297:15)
291 error If you need help, you may report this log at:
291 error     <http://github.com/isaacs/npm/issues>
291 error or email it to:
291 error     <npm-@googlegroups.com>
292 error System Windows_NT 6.2.9200
293 error command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
294 error cwd C:\Users\pc\git\ng-boilerplate
295 error node -v v0.8.22
296 error npm -v 1.2.14
297 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
@JIBIN009 Your version of `npm` is **several years old** and no longer supported. You are running `1.2` but we're on like `2.7` right now.

Because of your old version of `npm`, the `^` semver operator is not being recognized here:

```
290 error Error: No compatible version found: karma-firefox-launcher@'^0.1.3'
```

As such, `npm` fails to find a valid version to install. I would recommend you first [upgrade Node.js](https://github.com/npm/npm/wiki/Troubleshooting#updating-node-on-windows) and then [upgrade `npm`](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows) so that you can have the latest and greatest stable versions of each.

**Comment by othiym23** [comment]
What @KenanY said. Closing as resolved.

**Comment by JIBIN009** [comment]
Thank You :+1:
