### ISSUE TITLE
Error executing: npm i -p nativescript

### ISSUE THREAD

**Issue by pleivac** [npm/npm#7704]
Hi, I'm trying to install nts on my Mac Yosemite, but this error happens when I execute the command: npm i -p nativescript. 

The output is as follow:
```
npm WARN locking Error: EACCES, open '/Users/pleiva/.npm/_locks/nativescript-4b1523c0de537afa.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/pleiva/.npm/_locks/nativescript-4b1523c0de537afa.lock failed { [Error: EACCES, open '/Users/pleiva/.npm/_locks/nativescript-4b1523c0de537afa.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/pleiva/.npm/_locks/nativescript-4b1523c0de537afa.lock' }
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "i" "-p" "nativescript"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1

npm ERR! Attempt to unlock /Users/pleiva/node_modules/nativescript, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/pleiva/npm-debug.log
```
Thanks for the support!
Cheers, 
Pedro. 

Attachments: my npm-debug.log
```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'i', '-p', 'nativescript' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 verbose config Skipping project config: /Users/pleiva/.npmrc. (matches userconfig)
5 silly cache add args [ 'nativescript', null ]
6 verbose cache add spec nativescript
7 silly cache add parsed spec { raw: 'nativescript',
7 silly cache add   scope: null,
7 silly cache add   name: 'nativescript',
7 silly cache add   rawSpec: '',
7 silly cache add   spec: '*',
7 silly cache add   type: 'range' }
8 verbose addNamed nativescript@*
9 silly addNamed semver.valid null
10 silly addNamed semver.validRange *
11 silly addNameRange { name: 'nativescript', range: '*', hasData: false }
12 silly mapToRegistry name nativescript
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/nativescript
16 verbose addNameRange registry:https://registry.npmjs.org/nativescript not in flight; fetching
17 verbose request uri https://registry.npmjs.org/nativescript
18 verbose request no auth needed
19 info attempt registry request try #1 at 9:33:07 PM
20 verbose request id b686064a584cc6ae
21 verbose etag "BN5K87VISVS9R5MFU00AP9MLJ"
22 http request GET https://registry.npmjs.org/nativescript
23 http 304 https://registry.npmjs.org/nativescript
24 silly get cb [ 304,
24 silly get   { date: 'Sun, 22 Mar 2015 03:33:14 GMT',
24 silly get     server: 'Apache',
24 silly get     via: '1.1 varnish',
24 silly get     'last-modified': 'Sun, 22 Mar 2015 03:33:14 GMT',
24 silly get     'cache-control': 'max-age=60',
24 silly get     etag: '"BN5K87VISVS9R5MFU00AP9MLJ"',
24 silly get     age: '0',
24 silly get     'x-served-by': 'cache-dfw1832-DFW',
24 silly get     'x-cache': 'MISS',
24 silly get     'x-cache-hits': '0',
24 silly get     'x-timer': 'S1426995194.330757,VS0,VE245',
24 silly get     vary: 'Accept',
24 silly get     'content-length': '0',
24 silly get     'keep-alive': 'timeout=10, max=50',
24 silly get     connection: 'Keep-Alive' } ]
25 verbose etag https://registry.npmjs.org/nativescript from cache
26 verbose get saving nativescript to /Users/pleiva/.npm/registry.npmjs.org/nativescript/.cache.json
27 silly addNameRange number 2 { name: 'nativescript', range: '*', hasData: true }
28 silly addNameRange versions [ 'nativescript',
28 silly addNameRange   [ '0.2.0-471',
28 silly addNameRange     '0.3.0',
28 silly addNameRange     '0.3.1-18',
28 silly addNameRange     '0.3.1',
28 silly addNameRange     '0.3.2',
28 silly addNameRange     '0.4.0',
28 silly addNameRange     '0.4.2',
28 silly addNameRange     '0.9.0',
28 silly addNameRange     '0.9.1',
28 silly addNameRange     '0.9.2',
28 silly addNameRange     '0.9.3',
28 silly addNameRange     '0.9.4' ] ]
29 verbose addNamed nativescript@0.9.4
30 silly addNamed semver.valid 0.9.4
31 silly addNamed semver.validRange 0.9.4
32 silly cache afterAdd nativescript@0.9.4
33 verbose afterAdd /Users/pleiva/.npm/nativescript/0.9.4/package/package.json not in flight; writing
34 verbose afterAdd /Users/pleiva/.npm/nativescript/0.9.4/package/package.json written
35 silly install resolved [ { name: 'nativescript',
35 silly install resolved     preferGlobal: true,
35 silly install resolved     version: '0.9.4',
35 silly install resolved     author: { name: 'Telerik', email: 'support@telerik.com' },
35 silly install resolved     description: 'Command-line interface for building NativeScript projects',
35 silly install resolved     bin:
35 silly install resolved      { tns: './bin/nativescript.js',
35 silly install resolved        nativescript: './bin/nativescript.js' },
35 silly install resolved     main: './lib/nativescript-cli.js',
35 silly install resolved     repository:
35 silly install resolved      { type: 'git',
35 silly install resolved        url: 'https://github.com/NativeScript/nativescript-cli.git' },
35 silly install resolved     keywords: [ 'nativescript', 'telerik', 'mobile' ],
35 silly install resolved     dependencies:
35 silly install resolved      { 'bplist-parser': '0.0.6',
35 silly install resolved        bufferpack: '0.0.6',
35 silly install resolved        byline: '4.1.1',
35 silly install resolved        'cli-table': '0.3.1',
35 silly install resolved        colors: '0.6.2',
35 silly install resolved        ffi: 'https://github.com/icenium/node-ffi/tarball/master',
35 silly install resolved        fibers: 'https://github.com/icenium/node-fibers/tarball/v1.0.5.1',
35 silly install resolved        filesize: '2.0.3',
35 silly install resolved        gaze: '0.5.1',
35 silly install resolved        'iconv-lite': '0.4.4',
35 silly install resolved        'ios-sim-portable': '1.0.4',
35 silly install resolved        lockfile: '1.0.0',
35 silly install resolved        lodash: '3.2.0',
35 silly install resolved        log4js: '0.6.9',
35 silly install resolved        mkdirp: '0.3.5',
35 silly install resolved        'mute-stream': '0.0.4',
35 silly install resolved        'node-uuid': '1.4.1',
35 silly install resolved        npm: '2.6.1',
35 silly install resolved        osenv: '0.1.0',
35 silly install resolved        open: '0.0.4',
35 silly install resolved        plist: '1.1.0',
35 silly install resolved        plistlib: '0.2.1',
35 silly install resolved        'progress-stream': '0.5.0',
35 silly install resolved        prompt: 'https://github.com/Icenium/prompt/tarball/master',
35 silly install resolved        'properties-parser': '0.2.3',
35 silly install resolved        ref: 'https://github.com/icenium/ref/tarball/master',
35 silly install resolved        'ref-struct': 'https://github.com/telerik/ref-struct/tarball/master',
35 silly install resolved        rimraf: '2.2.6',
35 silly install resolved        semver: '3.0.1',
35 silly install resolved        shelljs: '0.3.0',
35 silly install resolved        tabtab: 'https://github.com/Icenium/node-tabtab/tarball/master',
35 silly install resolved        temp: '0.8.1',
35 silly install resolved        unzip: '0.1.9',
35 silly install resolved        xmlhttprequest: 'https://github.com/telerik/node-XMLHttpRequest/tarball/master',
35 silly install resolved        yargs: '1.2.2',
35 silly install resolved        'node-inspector': '0.7.4',
35 silly install resolved        xcode: 'https://github.com/NativeScript/node-xcode/archive/NativeScript-0.9.tar.gz' },
35 silly install resolved     analyze: true,
35 silly install resolved     devDependencies:
35 silly install resolved      { chai: '1.8.x',
35 silly install resolved        grunt: '0.4.2',
35 silly install resolved        'grunt-contrib-clean': '0.5.0',
35 silly install resolved        'grunt-contrib-copy': '0.5.0',
35 silly install resolved        'grunt-contrib-watch': '0.5.3',
35 silly install resolved        'grunt-shell': '0.6.4',
35 silly install resolved        'grunt-ts': '2.0.1',
35 silly install resolved        mocha: '1.21.4',
35 silly install resolved        'mocha-fibers': 'https://github.com/Icenium/mocha-fibers/tarball/master',
35 silly install resolved        should: '4.0.4',
35 silly install resolved        typescript: '1.4.1' },
35 silly install resolved     license: 'Apache-2.0',
35 silly install resolved     engines: { node: '>=0.10.26 <0.10.34 || >=0.10.35' },
35 silly install resolved     scripts:
35 silly install resolved      { test: '_mocha --ui mocha-fibers --recursive --reporter spec --require test/test-bootstrap.js --timeout 15000 test/',
35 silly install resolved        postinstall: 'node postinstall.js' },
35 silly install resolved     bugs: { url: 'https://github.com/NativeScript/nativescript-cli/issues' },
35 silly install resolved     homepage: 'https://github.com/NativeScript/nativescript-cli',
35 silly install resolved     _id: 'nativescript@0.9.4',
35 silly install resolved     _shasum: 'a381084eb39451f9e2ab149111c94ea788fc89ef',
35 silly install resolved     _resolved: 'https://registry.npmjs.org/nativescript/-/nativescript-0.9.4.tgz',
35 silly install resolved     _from: 'nativescript@*',
35 silly install resolved     _npmVersion: '2.5.1',
35 silly install resolved     _nodeVersion: '0.12.0',
35 silly install resolved     _npmUser: { name: 'erjangavalji', email: 'erjan.gavalji@gmail.com' },
35 silly install resolved     maintainers: [ [Object], [Object], [Object], [Object], [Object], [Object] ],
35 silly install resolved     dist:
35 silly install resolved      { shasum: 'a381084eb39451f9e2ab149111c94ea788fc89ef',
35 silly install resolved        tarball: 'http://registry.npmjs.org/nativescript/-/nativescript-0.9.4.tgz' },
35 silly install resolved     directories: {},
35 silly install resolved     readme: 'ERROR: No README data found!' } ]
36 info install nativescript@0.9.4 into /Users/pleiva
37 info installOne nativescript@0.9.4
38 verbose installOne of nativescript to /Users/pleiva not in flight; installing
39 warn locking Error: EACCES, open '/Users/pleiva/.npm/_locks/nativescript-4b1523c0de537afa.lock'
39 warn locking     at Error (native)
39 warn locking  /Users/pleiva/.npm/_locks/nativescript-4b1523c0de537afa.lock failed { [Error: EACCES, open '/Users/pleiva/.npm/_locks/nativescript-4b1523c0de537afa.lock']
39 warn locking   errno: -13,
39 warn locking   code: 'EACCES',
39 warn locking   path: '/Users/pleiva/.npm/_locks/nativescript-4b1523c0de537afa.lock' }
40 verbose stack Error: Attempt to unlock /Users/pleiva/node_modules/nativescript, which hasn't been locked
40 verbose stack     at unlock (/usr/local/lib/node_modules/npm/lib/utils/locker.js:66:11)
40 verbose stack     at cb (/usr/local/lib/node_modules/npm/lib/install.js:929:5)
40 verbose stack     at /usr/local/lib/node_modules/npm/lib/install.js:933:20
40 verbose stack     at /usr/local/lib/node_modules/npm/lib/utils/locker.js:40:9
40 verbose stack     at cb (/usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:149:38)
40 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:177:38
40 verbose stack     at FSReqWrap.oncomplete (fs.js:99:15)
41 verbose cwd /Users/pleiva
42 error Darwin 14.1.0
43 error argv "node" "/usr/local/bin/npm" "i" "-p" "nativescript"
44 error node v0.12.0
45 error npm  v2.5.1
46 error Attempt to unlock /Users/pleiva/node_modules/nativescript, which hasn't been locked
47 error If you need help, you may report this error at:
47 error     <http://github.com/npm/npm/issues>
48 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
@pleivac It looks like you don't have the necessary permissions to write to `npm`'s cache directory. Could you try the following command?:

``` sh
$ sudo chown -R $(whoami) "$HOME/.npm"
```

**Comment by pleivac** [comment]
That's right! It works like a charm. Thank you @KenanY

**Comment by ralphtheninja** [comment]
Is `-p` the same as `--production`?

**Comment by othiym23** [comment]
[Nope.](https://docs.npmjs.com/misc/config#shorthands-and-other-cli-niceties) @pleivac, why were you using `-p`?

**Comment by pleivac** [comment]
@othiym23 sorry, was a mistake. The correct flag is -g. cc @ralphtheninja

**Comment by othiym23** [comment]
It's not a problem! I was just curious what you were trying to do.

**Comment by ralphtheninja** [comment]
@othiym23 Thanks for link. Very useful!
