### ISSUE TITLE
Problems installing phonegap (npm err rolling back ENOTEMPTY)

### ISSUE THREAD

**Issue by steelhayr** [npm/npm#7707]
Hello everybody

I am trying to install PhoneGap on Windows 7, but no matter the Node.js (and npm) which I choose, it fails.

Since I have had several errors before about http-proxy, I typed this firstly:
```
C:\>npm config set http_proxy=http://registry.npmjs.org/:8080
```
(And it works)

This is output when I type npm install -g phonegap :
```
C:\>npm install -g phonegap
npm http GET https://registry.npmjs.org/phonegap
npm http 200 https://registry.npmjs.org/phonegap
npm http GET https://registry.npmjs.org/cordova/4.2.0
npm http GET https://registry.npmjs.org/colors/0.6.0-1
npm http GET https://registry.npmjs.org/minimist/0.1.0
npm http GET https://registry.npmjs.org/connect-phonegap/0.14.8
npm http GET https://registry.npmjs.org/phonegap-build/0.9.1
npm http GET https://registry.npmjs.org/qrcode-terminal/0.9.4
npm http GET https://registry.npmjs.org/prompt/0.2.11
npm http GET https://registry.npmjs.org/semver/1.1.0
npm http GET https://registry.npmjs.org/pluralize/0.0.4
npm http GET https://registry.npmjs.org/shelljs/0.1.4
npm http 200 https://registry.npmjs.org/minimist/0.1.0
npm http GET https://registry.npmjs.org/minimist/-/minimist-0.1.0.tgz
npm http 200 https://registry.npmjs.org/qrcode-terminal/0.9.4
npm http 200 https://registry.npmjs.org/cordova/4.2.0
npm http GET https://registry.npmjs.org/qrcode-terminal/-/qrcode-terminal-0.9.4.tgz
npm http 200 https://registry.npmjs.org/colors/0.6.0-1
npm http 200 https://registry.npmjs.org/connect-phonegap/0.14.8
npm http GET https://registry.npmjs.org/cordova/-/cordova-4.2.0.tgz
npm http GET https://registry.npmjs.org/connect-phonegap/-/connect-phonegap-0.14.8.tgz
npm http GET https://registry.npmjs.org/colors/-/colors-0.6.0-1.tgz
npm http 200 https://registry.npmjs.org/phonegap-build/0.9.1
npm http GET https://registry.npmjs.org/phonegap-build/-/phonegap-build-0.9.1.tgz
npm http 200 https://registry.npmjs.org/minimist/-/minimist-0.1.0.tgz
npm http 200 https://registry.npmjs.org/qrcode-terminal/-/qrcode-terminal-0.9.4.tgz
npm http 200 https://registry.npmjs.org/semver/1.1.0
npm http 200 https://registry.npmjs.org/pluralize/0.0.4
npm http GET https://registry.npmjs.org/semver/-/semver-1.1.0.tgz
npm http GET https://registry.npmjs.org/pluralize/-/pluralize-0.0.4.tgz
npm http 200 https://registry.npmjs.org/cordova/-/cordova-4.2.0.tgz
npm http 200 https://registry.npmjs.org/connect-phonegap/-/connect-phonegap-0.14.8.tgz
npm http 200 https://registry.npmjs.org/colors/-/colors-0.6.0-1.tgz
npm http 200 https://registry.npmjs.org/phonegap-build/-/phonegap-build-0.9.1.tgz
npm http 200 https://registry.npmjs.org/shelljs/0.1.4
npm http GET https://registry.npmjs.org/shelljs/-/shelljs-0.1.4.tgz
npm http 200 https://registry.npmjs.org/semver/-/semver-1.1.0.tgz
npm http 200 https://registry.npmjs.org/prompt/0.2.11
npm http GET https://registry.npmjs.org/prompt/-/prompt-0.2.11.tgz
npm http 200 https://registry.npmjs.org/pluralize/-/pluralize-0.0.4.tgz
npm http 200 https://registry.npmjs.org/shelljs/-/shelljs-0.1.4.tgz
npm http 200 https://registry.npmjs.org/prompt/-/prompt-0.2.11.tgz
npm http GET https://registry.npmjs.org/pkginfo
npm http GET https://registry.npmjs.org/read
npm http GET https://registry.npmjs.org/revalidator
npm http GET https://registry.npmjs.org/utile
npm http GET https://registry.npmjs.org/winston
npm http GET https://registry.npmjs.org/cordova-lib/4.2.0
npm http GET https://registry.npmjs.org/q/1.0.1
npm http GET https://registry.npmjs.org/nopt/3.0.1
npm http GET https://registry.npmjs.org/underscore/1.7.0
npm http 200 https://registry.npmjs.org/pkginfo
npm http 200 https://registry.npmjs.org/read
npm http 200 https://registry.npmjs.org/winston
npm http 200 https://registry.npmjs.org/nopt/3.0.1
npm http GET https://registry.npmjs.org/nopt/-/nopt-3.0.1.tgz
npm http 200 https://registry.npmjs.org/q/1.0.1
npm http GET https://registry.npmjs.org/shelljs
npm http GET https://registry.npmjs.org/optimist
npm http GET https://registry.npmjs.org/qrcode-terminal
npm http GET https://registry.npmjs.org/phonegap-build-api/0.3.3
npm http 200 https://registry.npmjs.org/utile
npm http GET https://registry.npmjs.org/q/-/q-1.0.1.tgz
npm http 200 https://registry.npmjs.org/nopt/-/nopt-3.0.1.tgz
npm http 200 https://registry.npmjs.org/cordova-lib/4.2.0
npm http GET https://registry.npmjs.org/cordova-lib/-/cordova-lib-4.2.0.tgz
npm http 200 https://registry.npmjs.org/revalidator
npm http 200 https://registry.npmjs.org/optimist
npm http 200 https://registry.npmjs.org/q/-/q-1.0.1.tgz
npm http GET https://registry.npmjs.org/mute-stream
npm http 200 https://registry.npmjs.org/cordova-lib/-/cordova-lib-4.2.0.tgz
npm http 200 https://registry.npmjs.org/qrcode-terminal
npm http 200 https://registry.npmjs.org/mute-stream
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/deep-equal
npm http GET https://registry.npmjs.org/i
npm http GET https://registry.npmjs.org/ncp
npm http GET https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/mkdirp
npm http 200 https://registry.npmjs.org/underscore/1.7.0
npm http GET https://registry.npmjs.org/underscore/-/underscore-1.7.0.tgz
npm http 200 https://registry.npmjs.org/deep-equal
npm http 200 https://registry.npmjs.org/i
npm http 200 https://registry.npmjs.org/ncp
npm http 200 https://registry.npmjs.org/shelljs
npm http 200 https://registry.npmjs.org/underscore/-/underscore-1.7.0.tgz
npm http 200 https://registry.npmjs.org/phonegap-build-api/0.3.3
npm http 200 https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/phonegap-build-api/-/phonegap-build-api-0.3.3.tgz
npm http 200 https://registry.npmjs.org/rimraf
npm http 200 https://registry.npmjs.org/async
npm http 200 https://registry.npmjs.org/phonegap-build-api/-/phonegap-build-api-0.3.3.tgz
npm http GET https://registry.npmjs.org/eyes
npm http GET https://registry.npmjs.org/stack-trace
npm http GET https://registry.npmjs.org/cycle
npm http GET https://registry.npmjs.org/request
npm http 200 https://registry.npmjs.org/stack-trace
npm http 200 https://registry.npmjs.org/request
npm http 200 https://registry.npmjs.org/eyes
npm http 200 https://registry.npmjs.org/cycle
npm http GET https://registry.npmjs.org/glob
npm http GET https://registry.npmjs.org/minimist/0.0.8
npm http 200 https://registry.npmjs.org/minimist/0.0.8
npm http GET https://registry.npmjs.org/minimist/-/minimist-0.0.8.tgz
npm http GET https://registry.npmjs.org/wordwrap
npm http 200 https://registry.npmjs.org/minimist/-/minimist-0.0.8.tgz
npm http 200 https://registry.npmjs.org/glob
npm http 200 https://registry.npmjs.org/wordwrap
npm http GET https://registry.npmjs.org/abbrev
npm http 200 https://registry.npmjs.org/abbrev
npm ERR! error rolling back Error: ENOTEMPTY, rmdir 'C:\Users\rafa\AppData\Roaming\npm\node_modules\phonegap\node_modules\prompt\node_modules'
npm ERR! error rolling back  prompt@0.2.11 { [Error: ENOTEMPTY, rmdir 'C:\Users\rafa\AppData\Roaming\npm\node_modules\phonegap\node_modules\prompt\node_modules']
npm ERR! error rolling back   errno: 53,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   path: 'C:\\Users\\rafa\\AppData\\Roaming\\npm\\node_modules\\phonegap\\node_modules\\prompt\\node_modules' }
npm ERR! Erro: ENOENT, chmod 'C:\Users\rafa\AppData\Roaming\npm\node_modules\phonegap\node_modules\cordova\node_modules\cordova-lib\src\cordova\metadata\firefoxos_parser.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "phonegap"
npm ERR! cwd C:\
npm ERR! node -v v0.10.0
npm ERR! npm -v 1.2.14
npm ERR! path C:\Users\rafa\AppData\Roaming\npm\node_modules\phonegap\node_modules\cordova\node_modules\cordova-lib\src\cordova\metadata\firefoxos_parser.js
npm ERR! fstream_path C:\Users\rafa\AppData\Roaming\npm\node_modules\phonegap\node_modules\cordova\node_modules\cordova-lib\src\cordova\metadata\firefoxos_parser.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! fstream_finish_call chmod
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack C:\Program Files\nodejs\node_modules\npm\node_modules\fstream\lib\writer.js:305:19
npm ERR! fstream_stack Object.oncomplete (fs.js:93:15)
npm ERR! error rolling back Error: ENOTEMPTY, rmdir 'C:\Users\rafa\AppData\Roaming\npm\node_modules\phonegap\node_modules\cordova\node_modules'
npm ERR! error rolling back  phonegap@4.2.0-0.24.2 { [Error: ENOTEMPTY, rmdir 'C:\Users\rafa\AppData\Roaming\npm\node_modules\phonegap\node_modules\cordova\node_modules']
npm ERR! error rolling back   errno: 53,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   path: 'C:\\Users\\rafa\\AppData\\Roaming\\npm\\node_modules\\phonegap\\node_modules\\cordova\\node_modules' }
npm ERR! Error: No compatible version found: glob@'^4.4.2'
npm ERR! Valid install targets:
npm ERR! ["1.1.0","2.0.9","2.0.8","2.0.7","2.1.0","3.0.0","3.0.1","3.1.0","3.1.1","3.1.2","3.1.3","3.1.4","3.1.5","3.1.6","3.1.7","3.1.9","3.1.10","3.1.11","3.1
.12","3.1.13","3.1.14","3.1.15","3.1.16","3.1.17","3.1.18","3.1.19","3.1.20","3.1.21","3.2.0","3.2.1","3.2.3","3.2.4","3.2.5","3.2.6","3.2.7","3.2.8","3.2.9","3
.2.10","3.2.11","4.0.0","4.0.1","4.0.2","4.0.3","4.0.4","4.0.5","4.0.6","4.1.2-beta","4.1.2","4.1.3","4.1.4","4.1.5","4.1.6","4.2.0","4.2.1","4.2.2","4.3.0","4.
3.1","4.3.2","4.3.3","4.3.4","4.3.5","4.4.0","4.4.2","4.5.0","5.0.0","4.5.1","5.0.1","4.5.2","5.0.2","4.5.3","5.0.3"]
npm ERR!     at installTargetsError (C:\Program Files\nodejs\node_modules\npm\lib\cache.js:682:10)
npm ERR!     at C:\Program Files\nodejs\node_modules\npm\lib\cache.js:597:10
npm ERR!     at saved (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:93:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "phonegap"
npm ERR! cwd C:\
npm ERR! node -v v0.10.0
npm ERR! npm -v 1.2.14
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\npm-debug.log
npm ERR! not ok code 0

C:\>
```
I would be pleased for any help that anyone could give me
Thanks beforehand
Please let me know if you need more information

**Comment by KenanY** [comment]
@steelhayr Your version of `npm` is several years old and no longer supported. The reason you are getting the issue is because your version of `npm` does not know how to parse the `^` semver operator you see here:

```
npm ERR! Error: No compatible version found: glob@'^4.4.2'
```

The solution is simply to [upgrade](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows).

**Comment by steelhayr** [comment]
@KenanY Thanks you very much for clarifying me!
I will try a newer version.

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
