### ISSUE TITLE
Can't istall nor publish latest version of module on npm

### ISSUE THREAD

**Issue by cmpsoares91** [npm/npm#7709]
Hi I managed to publish the first version without any problems but after that it has been problem after problem. I'm getting this error and can't figura out why:

<pre>
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'git://github.com/cmpsoares91/nmae.git' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 silly cache add args [ 'git://github.com/cmpsoares91/nmae.git', null ]
6 verbose cache add spec git://github.com/cmpsoares91/nmae.git
7 silly cache add parsed spec { raw: 'git://github.com/cmpsoares91/nmae.git',
7 silly cache add   scope: null,
7 silly cache add   name: null,
7 silly cache add   rawSpec: 'git://github.com/cmpsoares91/nmae.git',
7 silly cache add   spec: 'git://github.com/cmpsoares91/nmae.git',
7 silly cache add   type: 'git' }
8 verbose addRemoteGit u="git://github.com/cmpsoares91/nmae.git" silent=false
9 silly addRemoteGit normalized { url: 'git://github.com/cmpsoares91/nmae.git',
9 silly addRemoteGit   branch: 'master' }
10 silly addRemoteGit v git-github-com-cmpsoares91-nmae-git-c25f1029
11 verbose addRemoteGit C:\Users\Utilizador\AppData\Roaming\npm-cache\_git-remotes\git-github-com-cmpsoares91-nmae-git-c25f1029 not in flight; cloning
12 info git [ 'config', '--get', 'remote.origin.url' ]
13 verbose git remote.origin.url git://github.com/cmpsoares91/nmae.git
14 info git [ 'fetch', '-a', 'origin' ]
15 verbose git fetch -a origin (git://github.com/cmpsoares91/nmae.git)
16 silly verifyOwnership skipping for windows
17 info git [ 'rev-list', '-n1', 'master' ]
18 verbose git rev-list -n1 master 33303b0d30c0d83e04c5d3f303ea1c27e360568c
19 verbose resolved git url git://github.com/cmpsoares91/nmae.git#33303b0d30c0d83e04c5d3f303ea1c27e360568c
20 info git [ 'clone',
20 info git   'C:\\Users\\Utilizador\\AppData\\Roaming\\npm-cache\\_git-remotes\\git-github-com-cmpsoares91-nmae-git-c25f1029',
20 info git   'C:\\Users\\UTILIZ~1\\AppData\\Local\\Temp\\npm-892-d7d3b05c\\git-cache-65a992964b89\\33303b0d30c0d83e04c5d3f303ea1c27e360568c' ]
21 error Failed to clone git://github.com/cmpsoares91/nmae.git#33303b0d30c0d83e04c5d3f303ea1c27e360568c from git://github.com/cmpsoares91/nmae.git cygwin warning:
21 error Failed to clone git://github.com/cmpsoares91/nmae.git#33303b0d30c0d83e04c5d3f303ea1c27e360568c from git://github.com/cmpsoares91/nmae.git   MS-DOS style path detected: C:\Users\Utilizador\AppData\Roaming\npm-cache\_git-remotes\git-github-com-cmpsoares91-nmae-git-c25f1029/.git
21 error Failed to clone git://github.com/cmpsoares91/nmae.git#33303b0d30c0d83e04c5d3f303ea1c27e360568c from git://github.com/cmpsoares91/nmae.git   Preferred POSIX equivalent is: /cygdrive/c/Users/Utilizador/AppData/Roaming/npm-cache/_git-remotes/git-github-com-cmpsoares91-nmae-git-c25f1029/.git
21 error Failed to clone git://github.com/cmpsoares91/nmae.git#33303b0d30c0d83e04c5d3f303ea1c27e360568c from git://github.com/cmpsoares91/nmae.git   CYGWIN environment variable option "nodosfilewarning" turns off this warning.
21 error Failed to clone git://github.com/cmpsoares91/nmae.git#33303b0d30c0d83e04c5d3f303ea1c27e360568c from git://github.com/cmpsoares91/nmae.git   Consult the user's guide for more details about POSIX paths:
21 error Failed to clone git://github.com/cmpsoares91/nmae.git#33303b0d30c0d83e04c5d3f303ea1c27e360568c from git://github.com/cmpsoares91/nmae.git     http://cygwin.com/cygwin-ug-net/using.html#using-pathnames
21 error Failed to clone git://github.com/cmpsoares91/nmae.git#33303b0d30c0d83e04c5d3f303ea1c27e360568c from git://github.com/cmpsoares91/nmae.git fatal: failed to open '/cygdrive/c/Users/Utilizador/AppData/Roaming/npm-cache/_git-remotes/git-github-com-cmpsoares91-nmae-git-c25f1029/C:\Users\Utilizador\AppData\Roaming\npm-cache\_git-remotes\git-github-com-cmpsoares91-nmae-git-c25f1029/objects': No such file or directory
22 verbose stack Error: Command failed: git -c core.longpaths=true clone C:\Users\Utilizador\AppData\Roaming\npm-cache\_git-remotes\git-github-com-cmpsoares91-nmae-git-c25f1029 C:\Users\UTILIZ~1\AppData\Local\Temp\npm-892-d7d3b05c\git-cache-65a992964b89\33303b0d30c0d83e04c5d3f303ea1c27e360568c
22 verbose stack cygwin warning:
22 verbose stack   MS-DOS style path detected: C:\Users\Utilizador\AppData\Roaming\npm-cache\_git-remotes\git-github-com-cmpsoares91-nmae-git-c25f1029/.git
22 verbose stack   Preferred POSIX equivalent is: /cygdrive/c/Users/Utilizador/AppData/Roaming/npm-cache/_git-remotes/git-github-com-cmpsoares91-nmae-git-c25f1029/.git
22 verbose stack   CYGWIN environment variable option "nodosfilewarning" turns off this warning.
22 verbose stack   Consult the user's guide for more details about POSIX paths:
22 verbose stack     http://cygwin.com/cygwin-ug-net/using.html#using-pathnames
22 verbose stack fatal: failed to open '/cygdrive/c/Users/Utilizador/AppData/Roaming/npm-cache/_git-remotes/git-github-com-cmpsoares91-nmae-git-c25f1029/C:\Users\Utilizador\AppData\Roaming\npm-cache\_git-remotes\git-github-com-cmpsoares91-nmae-git-c25f1029/objects': No such file or directory
22 verbose stack
22 verbose stack     at ChildProcess.exithandler (child_process.js:744:12)
22 verbose stack     at ChildProcess.emit (events.js:110:17)
22 verbose stack     at maybeClose (child_process.js:1008:16)
22 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
23 verbose cwd D:\Dropbox\ISCTE-IUL\MEI-SIGC\2º Semestre\Tecnologias para Sistema de Informação Operacionais\Trabalho
24 error Windows_NT 6.3.9600
25 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "git://github.com/cmpsoares91/nmae.git"
26 error node v0.12.0
27 error npm  v2.5.1
28 error code 128
29 error Command failed: git -c core.longpaths=true clone C:\Users\Utilizador\AppData\Roaming\npm-cache\_git-remotes\git-github-com-cmpsoares91-nmae-git-c25f1029 C:\Users\UTILIZ~1\AppData\Local\Temp\npm-892-d7d3b05c\git-cache-65a992964b89\33303b0d30c0d83e04c5d3f303ea1c27e360568c
29 error cygwin warning:
29 error   MS-DOS style path detected: C:\Users\Utilizador\AppData\Roaming\npm-cache\_git-remotes\git-github-com-cmpsoares91-nmae-git-c25f1029/.git
29 error   Preferred POSIX equivalent is: /cygdrive/c/Users/Utilizador/AppData/Roaming/npm-cache/_git-remotes/git-github-com-cmpsoares91-nmae-git-c25f1029/.git
29 error   CYGWIN environment variable option "nodosfilewarning" turns off this warning.
29 error   Consult the user's guide for more details about POSIX paths:
29 error     http://cygwin.com/cygwin-ug-net/using.html#using-pathnames
29 error fatal: failed to open '/cygdrive/c/Users/Utilizador/AppData/Roaming/npm-cache/_git-remotes/git-github-com-cmpsoares91-nmae-git-c25f1029/C:\Users\Utilizador\AppData\Roaming\npm-cache\_git-remotes\git-github-com-cmpsoares91-nmae-git-c25f1029/objects': No such file or directory
30 error If you need help, you may report this error at:
30 error     <http://github.com/npm/npm/issues>
31 verbose exit [ 1, true ]
</pre>

<pre>
D:\Dropbox\ISCTE-IUL\MEI-SIGC\2º Semestre\Tecnologias para Sistema de Informação
 Operacionais\Trabalho\NMAE>npm ls
nmae@0.1.2 D:\Dropbox\ISCTE-IUL\MEI-SIGC\2º Semestre\Tecnologias para Sistema de
 Informação Operacionais\Trabalho\NMAE
├─┬ chai@2.1.2
│ ├── assertion-error@1.0.0
│ └─┬ deep-eql@0.1.3
│   └── type-detect@0.1.1
└─┬ mocha@2.2.1
  ├── commander@2.3.0
  ├─┬ debug@2.0.0
  │ └── ms@0.6.2
  ├── diff@1.0.8
  ├── escape-string-regexp@1.0.2
  ├─┬ glob@3.2.3
  │ ├── graceful-fs@2.0.3
  │ ├── inherits@2.0.1
  │ └─┬ minimatch@0.2.14
  │   ├── lru-cache@2.5.0
  │   └── sigmund@1.0.0
  ├── growl@1.8.1
  ├─┬ jade@0.26.3
  │ ├── commander@0.6.1
  │ └── mkdirp@0.3.0
  ├─┬ mkdirp@0.5.0
  │ └── minimist@0.0.8
  └── supports-color@1.2.1

D:\Dropbox\ISCTE-IUL\MEI-SIGC\2º Semestre\Tecnologias para Sistema de Informação
 Operacionais\Trabalho>npm show nmae

{ name: 'nmae',
  description: 'Academic example of a Node.JS Module implementation.',
  'dist-tags': { latest: '0.1.1', '0.1.1': '0.1.1' },
  versions: [ '0.1.0', '0.1.1' ],
  maintainers: 'cmpsoares91 <cmpsoares91@gmail.com>',
  time:
   { modified: '2015-03-23T02:09:54.567Z',
     created: '2015-03-22T20:20:48.015Z',
     '0.1.0': '2015-03-22T20:20:48.015Z',
     '0.1.1': '2015-03-23T01:50:38.502Z' },
  homepage: 'https://github.com/cmpsoares91/NMAE',
  keywords: [ 'Node.js', 'Module', 'example' ],
  repository: { type: 'git', url: 'https://github.com/cmpsoares91/NMAE.git' },
  contributors:
   [ 'José Vaz (https://github.com/JoseVaz)',
     'Nuno Salgado (https://github.com/ncsalgado)' ],
  author: 'Carlos Soares <cmpsoares91@gmail.com> (https://github.com/cmpsoares91
)',
  bugs: { url: 'https://github.com/cmpsoares91/NMAE/issues' },
  license:
   { type: 'MIT',
     url: 'https://github.com/cmpsoares91/NMAE/blob/master/LICENSE.md' },
  readmeFilename: 'README.md',
  users: { cmpsoares91: true },
  version: '0.1.1',
  main: 'index.js',
  scripts: { test: 'make test' },
  devDependencies: { chai: '^2.1.2', mocha: '^2.2.1' },
  gitHead: '370f8d2b13b8966f36758cd40fc6ca1e663f4d55',
  dist:
   { shasum: '61e4bcae010a110e846434c7b80de93b8427504c',
     tarball: 'http://registry.npmjs.org/nmae/-/nmae-0.1.1.tgz' },
  directories: {} }

</pre>
The purpose of this is to create a tutorial/mini-framework to create modules for Node.JS and NPM.
The repo: https://github.com/cmpsoares91/nmae

Thank you, in advance, for any help!
Carlos Soares.

**Comment by cmpsoares91** [comment]
`npm login` fixed it.
