### ISSUE TITLE
I'm having trouble publishing

### ISSUE THREAD

**Issue by cha0s** [npm/npm#7720]
I tried publishing my project and I got this:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/nvm/v0.10.29/bin/node',
1 verbose cli   '/usr/local/nvm/v0.10.29/bin/npm',
1 verbose cli   'publish' ]
2 info using npm@1.4.14
3 info using node@v0.10.29
4 verbose publish [ '.' ]
5 verbose cache add [ '.', null ]
6 verbose cache add name=undefined spec="." args=[".",null]
7 verbose parsed url { protocol: null,
7 verbose parsed url   slashes: null,
7 verbose parsed url   auth: null,
7 verbose parsed url   host: null,
7 verbose parsed url   port: null,
7 verbose parsed url   hostname: null,
7 verbose parsed url   hash: null,
7 verbose parsed url   search: null,
7 verbose parsed url   query: null,
7 verbose parsed url   pathname: '.',
7 verbose parsed url   path: '.',
7 verbose parsed url   href: '.' }
8 silly lockFile 3a52ce78- .
9 verbose lock . /home/mylocaluser/.npm/3a52ce78-.lock
10 verbose tar pack [ '/home/mylocaluser/.npm/clidom/0.1.3/package.tgz', '.' ]
11 verbose tarball /home/mylocaluser/.npm/clidom/0.1.3/package.tgz
12 verbose folder .
13 info prepublish clidom@0.1.3
14 silly lockFile 1f1177db-tar tar://.
15 verbose lock tar://. /home/mylocaluser/.npm/1f1177db-tar.lock
16 silly lockFile 39bfa54c-983-npm-clidom-0-1-3-package-tgz tar:///home/mylocaluser/.npm/clidom/0.1.3/package.tgz
17 verbose lock tar:///home/mylocaluser/.npm/clidom/0.1.3/package.tgz /home/mylocaluser/.npm/39bfa54c-983-npm-clidom-0-1-3-package-tgz.lock
18 silly lockFile 1f1177db-tar tar://.
19 silly lockFile 1f1177db-tar tar://.
20 silly lockFile 39bfa54c-983-npm-clidom-0-1-3-package-tgz tar:///home/mylocaluser/.npm/clidom/0.1.3/package.tgz
21 silly lockFile 39bfa54c-983-npm-clidom-0-1-3-package-tgz tar:///home/mylocaluser/.npm/clidom/0.1.3/package.tgz
22 silly lockFile 7d1a8588-a0s6983-npm-clidom-0-1-3-package /home/mylocaluser/.npm/clidom/0.1.3/package
23 verbose lock /home/mylocaluser/.npm/clidom/0.1.3/package /home/mylocaluser/.npm/7d1a8588-a0s6983-npm-clidom-0-1-3-package.lock
24 silly lockFile 7d1a8588-a0s6983-npm-clidom-0-1-3-package /home/mylocaluser/.npm/clidom/0.1.3/package
25 silly lockFile 7d1a8588-a0s6983-npm-clidom-0-1-3-package /home/mylocaluser/.npm/clidom/0.1.3/package
26 silly lockFile 3a52ce78- .
27 silly lockFile 3a52ce78- .
28 silly publish { name: 'clidom',
28 silly publish   version: '0.1.3',
28 silly publish   description: 'Parse a DOM from the command line',
28 silly publish   main: 'index.js',
28 silly publish   scripts: { test: 'echo "Error: no test specified" && exit 1' },
28 silly publish   bin: { clidom: 'bin/clidom' },
28 silly publish   author: { name: 'cha0s' },
28 silly publish   license: 'MIT',
28 silly publish   dependencies:
28 silly publish    { cheerio: '^0.19.0',
28 silly publish      'css-what': '^2.0.2',
28 silly publish      request: '^2.53.0',
28 silly publish      yargs: '^3.5.4' },
28 silly publish   readme: '# Parse a DOM from the command line\n\nEver wanted to do a one-off scrape of a web page? Tired of writing scraping\nboilerplate for applications and wish you had a nice UNIX-style command to call\nto do it for you? Enter clidom!\n\n## Installation\n\n```bash\nnpm install -g clidom\n```\n\n## Usage\n\n```bash\nclidom selector [URL] [options]\n```\n\n## Selector specification:\n\nselector[::subselector]\n\nclidom extends selector syntax to allow you to not only select elements, but\nmutate the elements as needed. clidom provides the following syntax for\nsubselectors:\n\n- `innerHtml` - Returns the element\'s inner HTML (default)\n- `outerHtml` - Returns the element\'s outer HTML\n- `text` - Returns the text inside the element, stripping tags\n- `[attribute]` - Returns the value of the specified attribute\n\n## Options\n\n```bash\n-o, --out-file  File to write JSON output              [default: \'-\' (stdout)]\n-p, --pretty    Pretty JSON output                             [default: true]\n-t, --trim      Trim empty results                             [default: true]\n-h, --help      Show help\n```\n\n## Examples\n\nOutput a pretty JSON object of button labels on http://www.google.com:\n\n```bash\nclidom input[type="submit"]::[value] https://www.google.com\n```\n\nOutput:\n\n```bash\n{\n  "input[type=submit]::[value]": [\n    {\n      "value": "Google Search"\n    },\n    {\n      "value": "I\'m Feeling Lucky"\n    }\n  ]\n}\n```\n\nOutput a pretty JSON object of Twitter usernames talking about node.js:\n\n```bash\nclidom \'span.username b\' \'https://twitter.com/search?f=realtime&q=node.js\'\n```\n\nOutput: (will vary over time)\n\n```bash\n{\n  "span.username b": [\n    "hashedrock",\n    "mashupaward",\n    "orangesuzuki",\n    "RJ_Hsiao",\n    "mongodbExpert",\n    "JanilsonPy",\n    "npm_tweets",\n    "nodenpm",\n    "npm_tweets",\n    "StrongLoop",\n    "DevelopersDojo",\n    "adstweetbot",\n    "Johnny_Rehab",\n    "jramonleon",\n    "questionjs",\n    "AsadNomanMS",\n    "amit_intelli",\n    "rekkuuzadx",\n    "npm_tweets",\n    "adstweetbot"\n  ]\n}\n```\n',
28 silly publish   readmeFilename: 'README.md',
28 silly publish   gitHead: '3b84d70276244bfe46ac044a377e7c46bc0b9816',
28 silly publish   _id: 'clidom@0.1.3',
28 silly publish   _shasum: '59b9b95528f6b2718d0a4bfcdab6b4cd3e0c3adf',
28 silly publish   _from: '.' }
29 verbose url raw clidom
30 verbose url resolving [ 'https://registry.npmjs.org/', './clidom' ]
31 verbose url resolved https://registry.npmjs.org/clidom
32 info trying registry request attempt 1 at 13:04:39
33 http PUT https://registry.npmjs.org/clidom
34 http 401 https://registry.npmjs.org/clidom
35 verbose headers { date: 'Mon, 23 Mar 2015 18:04:39 GMT',
35 verbose headers   server: 'Apache',
35 verbose headers   'content-type': 'application/json',
35 verbose headers   'cache-control': 'max-age=60',
35 verbose headers   'content-length': '38',
35 verbose headers   'accept-ranges': 'bytes',
35 verbose headers   via: '1.1 varnish',
35 verbose headers   'x-served-by': 'cache-dfw1831-DFW',
35 verbose headers   'x-cache': 'MISS',
35 verbose headers   'x-cache-hits': '0',
35 verbose headers   'x-timer': 'S1427133879.728960,VS0,VE231',
35 verbose headers   'keep-alive': 'timeout=10, max=50',
35 verbose headers   connection: 'Keep-Alive' }
36 error publish Failed PUT 401
37 error Error: Request was not authorized : clidom
37 error     at RegClient.<anonymous> (/usr/local/nvm/v0.10.29/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:274:14)
37 error     at Request._callback (/usr/local/nvm/v0.10.29/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:212:65)
37 error     at Request.self.callback (/usr/local/nvm/v0.10.29/lib/node_modules/npm/node_modules/request/request.js:123:22)
37 error     at Request.emit (events.js:98:17)
37 error     at Request.<anonymous> (/usr/local/nvm/v0.10.29/lib/node_modules/npm/node_modules/request/request.js:893:14)
37 error     at Request.emit (events.js:117:20)
37 error     at IncomingMessage.<anonymous> (/usr/local/nvm/v0.10.29/lib/node_modules/npm/node_modules/request/request.js:844:12)
37 error     at IncomingMessage.emit (events.js:117:20)
37 error     at _stream_readable.js:929:16
37 error     at process._tickCallback (node.js:419:13)
38 error If you need help, you may report this *entire* log,
38 error including the npm and node versions, at:
38 error     <http://github.com/npm/npm/issues>
39 error System Linux 3.13.0-46-generic
40 error command "/usr/local/nvm/v0.10.29/bin/node" "/usr/local/nvm/v0.10.29/bin/npm" "publish"
41 error cwd /media/ext/mnt/home/mylocaluser/dev/code/js/clidom
42 error node -v v0.10.29
43 error npm -v 1.4.14
44 verbose exit [ 1, true ]
```

I thought maybe it was because I got logged out, so I tried logging in and got another error:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/nvm/v0.10.29/bin/node',
1 verbose cli   '/usr/local/nvm/v0.10.29/bin/npm',
1 verbose cli   'login' ]
2 info using npm@1.4.14
3 info using node@v0.10.29
4 verbose adduser before first PUT { name: 'cha0s',
4 verbose adduser   password: 'XXXXX',
4 verbose adduser   email: 'npm@cha0s.io',
4 verbose adduser   _id: 'org.couchdb.user:cha0s',
4 verbose adduser   type: 'user',
4 verbose adduser   roles: [],
4 verbose adduser   date: '2015-03-23T18:05:27.194Z' }
5 verbose url raw /-/user/org.couchdb.user:cha0s
6 verbose url resolving [ 'https://registry.npmjs.org/',
6 verbose url resolving   './-/user/org.couchdb.user:cha0s' ]
7 verbose url resolved https://registry.npmjs.org/-/user/org.couchdb.user:cha0s
8 info trying registry request attempt 1 at 13:05:27
9 http PUT https://registry.npmjs.org/-/user/org.couchdb.user:cha0s
10 http 400 https://registry.npmjs.org/-/user/org.couchdb.user:cha0s
11 verbose headers { date: 'Mon, 23 Mar 2015 18:05:27 GMT',
11 verbose headers   server: 'Apache',
11 verbose headers   'content-type': 'application/json',
11 verbose headers   'cache-control': 'max-age=60',
11 verbose headers   'content-length': '57',
11 verbose headers   'accept-ranges': 'bytes',
11 verbose headers   via: '1.1 varnish',
11 verbose headers   'x-served-by': 'cache-jfk1030-JFK',
11 verbose headers   'x-cache': 'MISS',
11 verbose headers   'x-cache-hits': '0',
11 verbose headers   'x-timer': 'S1427133927.443973,VS0,VE335',
11 verbose headers   connection: 'close' }
12 verbose adduser back [ [Error: Unknown error while authenticating : -/user/org.couchdb.user:cha0s],
12 verbose adduser   { ok: false, error: 'Unknown error while authenticating' },
12 verbose adduser   '{"ok":false,"error":"Unknown error while authenticating"}' ]
13 error Error: Unknown error while authenticating : -/user/org.couchdb.user:cha0s
13 error     at RegClient.<anonymous> (/usr/local/nvm/v0.10.29/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:274:14)
13 error     at Request._callback (/usr/local/nvm/v0.10.29/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:212:65)
13 error     at Request.self.callback (/usr/local/nvm/v0.10.29/lib/node_modules/npm/node_modules/request/request.js:123:22)
13 error     at Request.emit (events.js:98:17)
13 error     at Request.<anonymous> (/usr/local/nvm/v0.10.29/lib/node_modules/npm/node_modules/request/request.js:893:14)
13 error     at Request.emit (events.js:117:20)
13 error     at IncomingMessage.<anonymous> (/usr/local/nvm/v0.10.29/lib/node_modules/npm/node_modules/request/request.js:844:12)
13 error     at IncomingMessage.emit (events.js:117:20)
13 error     at _stream_readable.js:929:16
13 error     at process._tickCallback (node.js:419:13)
14 error If you need help, you may report this *entire* log,
14 error including the npm and node versions, at:
14 error     <http://github.com/npm/npm/issues>
15 error System Linux 3.13.0-46-generic
16 error command "/usr/local/nvm/v0.10.29/bin/node" "/usr/local/nvm/v0.10.29/bin/npm" "login"
17 error cwd /media/ext/mnt/home/cha0s6983/dev/code/js/clidom
18 error node -v v0.10.29
19 error npm -v 1.4.14
20 verbose exit [ 1, true ]
```

**Comment by bcoe** [comment]
Hey @cha0s, could you do me a favor and try updating your npm client and republishing:

`sudo npm install npm -g`

**Comment by cha0s** [comment]
Did so (sans sudo), still getting 401, latest npm-debug.log:

```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/nvm/v0.10.29/bin/npm', 'publish' ]
2 info using npm@2.7.3
3 info using node@v0.10.29
4 verbose publish [ '.' ]
5 silly cache add args [ '.', null ]
6 verbose cache add spec .
7 silly cache add parsed spec { raw: '.',
7 silly cache add   scope: null,
7 silly cache add   name: null,
7 silly cache add   rawSpec: '.',
7 silly cache add   spec: '/media/ext/mnt/home/mylocaluser/dev/code/js/clidom',
7 silly cache add   type: 'directory' }
8 verbose addLocalDirectory /home/mylocaluser/.npm/clidom/0.1.3/package.tgz not in flight; packing
9 verbose tar pack [ '/home/mylocaluser/.npm/clidom/0.1.3/package.tgz',
9 verbose tar pack   '/media/ext/mnt/home/mylocaluser/dev/code/js/clidom' ]
10 verbose tarball /home/mylocaluser/.npm/clidom/0.1.3/package.tgz
11 verbose folder /media/ext/mnt/home/mylocaluser/dev/code/js/clidom
12 info prepublish clidom@0.1.3
13 verbose addLocalTarball adding from inside cache /home/mylocaluser/.npm/clidom/0.1.3/package.tgz
14 silly cache afterAdd clidom@0.1.3
15 verbose afterAdd /home/mylocaluser/.npm/clidom/0.1.3/package/package.json not in flight; writing
16 verbose afterAdd /home/mylocaluser/.npm/clidom/0.1.3/package/package.json written
17 silly publish { name: 'clidom',
17 silly publish   version: '0.1.3',
17 silly publish   description: 'Parse a DOM from the command line',
17 silly publish   main: 'index.js',
17 silly publish   repository: { type: 'git', url: 'https://github.com/cha0s/clidom' },
17 silly publish   scripts: { test: 'echo "Error: no test specified" && exit 1' },
17 silly publish   bin: { clidom: 'bin/clidom' },
17 silly publish   author: { name: 'cha0s' },
17 silly publish   license: 'MIT',
17 silly publish   dependencies:
17 silly publish    { cheerio: '^0.19.0',
17 silly publish      'css-what': '^2.0.2',
17 silly publish      request: '^2.53.0',
17 silly publish      yargs: '^3.5.4' },
17 silly publish   readme: '# Parse a DOM from the command line\n\nEver wanted to do a one-off scrape of a web page? Tired of writing scraping\nboilerplate for applications and wish you had a nice UNIX-style command to call\nto do it for you? Enter clidom!\n\n## Installation\n\n```bash\nnpm install -g clidom\n```\n\n## Usage\n\n```bash\nclidom selector [URL] [options]\n```\n\n## Selector specification:\n\nselector[::subselector]\n\nclidom extends selector syntax to allow you to not only select elements, but\nmutate the elements as needed. clidom provides the following syntax for\nsubselectors:\n\n- `innerHtml` - Returns the element\'s inner HTML (default)\n- `outerHtml` - Returns the element\'s outer HTML\n- `text` - Returns the text inside the element, stripping tags\n- `[attribute]` - Returns the value of the specified attribute\n\n## Options\n\n```bash\n-o, --out-file  File to write JSON output              [default: \'-\' (stdout)]\n-p, --pretty    Pretty JSON output                             [default: true]\n-t, --trim      Trim empty results                             [default: true]\n-h, --help      Show help\n```\n\n## Examples\n\nOutput a pretty JSON object of button labels on http://www.google.com:\n\n```bash\nclidom input[type="submit"]::[value] https://www.google.com\n```\n\nOutput:\n\n```bash\n{\n  "input[type=submit]::[value]": [\n    {\n      "value": "Google Search"\n    },\n    {\n      "value": "I\'m Feeling Lucky"\n    }\n  ]\n}\n```\n\nOutput a pretty JSON object of Twitter usernames talking about node.js:\n\n```bash\nclidom \'span.username b\' \'https://twitter.com/search?f=realtime&q=node.js\'\n```\n\nOutput: (will vary over time)\n\n```bash\n{\n  "span.username b": [\n    "hashedrock",\n    "mashupaward",\n    "orangesuzuki",\n    "RJ_Hsiao",\n    "mongodbExpert",\n    "JanilsonPy",\n    "npm_tweets",\n    "nodenpm",\n    "npm_tweets",\n    "StrongLoop",\n    "DevelopersDojo",\n    "adstweetbot",\n    "Johnny_Rehab",\n    "jramonleon",\n    "questionjs",\n    "AsadNomanMS",\n    "amit_intelli",\n    "rekkuuzadx",\n    "npm_tweets",\n    "adstweetbot"\n  ]\n}\n```\n',
17 silly publish   readmeFilename: 'README.md',
17 silly publish   gitHead: 'd95bc01579198bc43893384c60d8739137cc4752',
17 silly publish   bugs: { url: 'https://github.com/cha0s/clidom/issues' },
17 silly publish   homepage: 'https://github.com/cha0s/clidom',
17 silly publish   _id: 'clidom@0.1.3',
17 silly publish   _shasum: 'c17ce5d467fe37a77fc42d0d3a575d029da626f3',
17 silly publish   _from: '.' }
18 silly mapToRegistry name clidom
19 silly mapToRegistry using default registry
20 silly mapToRegistry registry https://registry.npmjs.org/
21 silly mapToRegistry uri https://registry.npmjs.org/clidom
22 verbose publish registryBase https://registry.npmjs.org/
23 silly publish uploading /home/mylocaluser/.npm/clidom/0.1.3/package.tgz
24 verbose request uri https://registry.npmjs.org/clidom
25 verbose request sending authorization for write operation
26 info attempt registry request try #1 at 13:36:15
27 verbose request id 56c90711fe136ec6
28 http request PUT https://registry.npmjs.org/clidom
29 http 401 https://registry.npmjs.org/clidom
30 verbose headers { date: 'Mon, 23 Mar 2015 18:36:15 GMT',
30 verbose headers   server: 'Apache',
30 verbose headers   'content-type': 'application/json',
30 verbose headers   'cache-control': 'max-age=60',
30 verbose headers   'content-length': '38',
30 verbose headers   'accept-ranges': 'bytes',
30 verbose headers   via: '1.1 varnish',
30 verbose headers   'x-served-by': 'cache-ord1735-ORD',
30 verbose headers   'x-cache': 'MISS',
30 verbose headers   'x-cache-hits': '0',
30 verbose headers   'x-timer': 'S1427135775.319369,VS0,VE456',
30 verbose headers   'keep-alive': 'timeout=10, max=50',
30 verbose headers   connection: 'Keep-Alive' }
31 verbose request invalidating /home/mylocaluser/.npm/registry.npmjs.org/clidom on PUT
32 error publish Failed PUT 401
33 verbose stack Error: Request was not authorized : clidom
33 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/nvm/v0.10.29/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:254:14)
33 verbose stack     at Request._callback (/usr/local/nvm/v0.10.29/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:178:14)
33 verbose stack     at Request.self.callback (/usr/local/nvm/v0.10.29/lib/node_modules/npm/node_modules/request/request.js:344:22)
33 verbose stack     at Request.emit (events.js:98:17)
33 verbose stack     at Request.<anonymous> (/usr/local/nvm/v0.10.29/lib/node_modules/npm/node_modules/request/request.js:1239:14)
33 verbose stack     at Request.emit (events.js:117:20)
33 verbose stack     at IncomingMessage.<anonymous> (/usr/local/nvm/v0.10.29/lib/node_modules/npm/node_modules/request/request.js:1187:12)
33 verbose stack     at IncomingMessage.emit (events.js:117:20)
33 verbose stack     at _stream_readable.js:929:16
33 verbose stack     at process._tickCallback (node.js:419:13)
34 verbose statusCode 401
35 verbose pkgid clidom
36 verbose cwd /media/ext/mnt/home/mylocaluser/dev/code/js/clidom
37 error Linux 3.13.0-46-generic
38 error argv "node" "/usr/local/nvm/v0.10.29/bin/npm" "publish"
39 error node v0.10.29
40 error npm  v2.7.3
41 error code E401
42 error Request was not authorized : clidom
43 error If you need help, you may report this error at:
43 error     <https://github.com/npm/npm/issues>
44 verbose exit [ 1, true ]
```

**Comment by bcoe** [comment]
@cha0s can you login with your client at `2.7.3`, or does that fail too?

**Comment by rwwagner90** [comment]
My publish was giving me a 401, so I deleted .npmrc, now I cannot log back in with adduser.

**Comment by cha0s** [comment]
Nope, same 'unknown error'. That part really makes me think it's some problem on npm's server(s).

**Comment by cha0s** [comment]
Also possibly relevant information: publish worked fine even last night. It's just been broken today so something seems to have happened recently.

**Comment by bcoe** [comment]
@rwwagner90 what version of Node.js and npm are you on? @cha0s, @rwwagner90 please try re-logging in now.

**Comment by cha0s** [comment]
Whatever you just did worked. Login and publish just went through. Thanks!

What was it if you don't mind me asking? In case someone searches for this in the future...

**Comment by rwwagner90** [comment]
Login and published worked for me as well. What was the issue?

**Comment by bcoe** [comment]
@rwwagner90 we're in the process of upgrading some of our server infrastructure, mind sharing what version of Node and npm you're on?

**Comment by rwwagner90** [comment]
npm: 2.7.3, node: 0.10.30

**Comment by rwwagner90** [comment]
@bcoe I'm now getting this:

```
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
```

**Comment by bcoe** [comment]
@rwwagner90 I think this should be a separate ticket, and is a bug we've seen occasionally with the CLI., what operation are you performing when this occurs?

**Comment by rwwagner90** [comment]
@bcoe It's when publishing. I made a new issue: https://github.com/npm/npm/issues/7721

**Comment by bcoe** [comment]
@cha0s, @rwwagner90 could you do me a favor and try logging in again? I've made an attempt to patch the problem that you were seeing and have rolled out the new server again.

**Comment by cha0s** [comment]
Seems to be all good now :)

**Comment by hash-bang** [comment]
Getting the same errors while trying to publish. I got the same 401 as @rwwagner90 I also tried using `adduser` to relog hoping that would fix it. Turns out now I cannot also login.

Dump:

```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/bin/npm', 'adduser' ]
2 info using npm@2.7.3
3 info using node@v0.10.25
4 verbose node symlink /usr/bin/node
5 verbose adduser before first PUT { _id: 'org.couchdb.user:hash-bang',
5 verbose adduser   name: 'hash-bang',
5 verbose adduser   password: 'XXXXX',
5 verbose adduser   email: 'm@ttcarter.com',
5 verbose adduser   type: 'user',
5 verbose adduser   roles: [],
5 verbose adduser   date: '2015-03-24T05:34:19.675Z' }
6 verbose request uri https://registry.npmjs.org/-/user/org.couchdb.user:hash-bang
7 verbose request new user, so can't send auth
8 info attempt registry request try #1 at 15:34:19
9 verbose request id 5cd524d5d718b773
10 http request PUT https://registry.npmjs.org/-/user/org.couchdb.user:hash-bang
11 http 400 https://registry.npmjs.org/-/user/org.couchdb.user:hash-bang
12 verbose headers { date: 'Tue, 24 Mar 2015 05:34:20 GMT',
12 verbose headers   server: 'Apache',
12 verbose headers   'content-type': 'application/json',
12 verbose headers   'cache-control': 'max-age=60',
12 verbose headers   'content-length': '57',
12 verbose headers   'accept-ranges': 'bytes',
12 verbose headers   via: '1.1 varnish',
12 verbose headers   'x-served-by': 'cache-syd1625-SYD',
12 verbose headers   'x-cache': 'MISS',
12 verbose headers   'x-cache-hits': '0',
12 verbose headers   'x-timer': 'S1427175260.042639,VS0,VE746',
12 verbose headers   connection: 'close' }
13 verbose request invalidating /home/mc/.npm/registry.npmjs.org/-/user/org.couchdb.user_3Ahash-bang on PUT
14 verbose adduser back [ { [Error: Unknown error while authenticating : -/user/org.couchdb.user:hash-bang] statusCode: 400, code: 'E400' },
14 verbose adduser   { ok: false, error: 'Unknown error while authenticating' },
14 verbose adduser   '{"ok":false,"error":"Unknown error while authenticating"}' ]
15 verbose stack Error: Unknown error while authenticating : -/user/org.couchdb.user:hash-bang
15 verbose stack     at CachingRegistryClient.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:254:14)
15 verbose stack     at Request._callback (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:178:14)
15 verbose stack     at Request.self.callback (/usr/lib/node_modules/npm/node_modules/request/request.js:344:22)
15 verbose stack     at Request.EventEmitter.emit (events.js:98:17)
15 verbose stack     at Request.<anonymous> (/usr/lib/node_modules/npm/node_modules/request/request.js:1239:14)
15 verbose stack     at Request.EventEmitter.emit (events.js:117:20)
15 verbose stack     at IncomingMessage.<anonymous> (/usr/lib/node_modules/npm/node_modules/request/request.js:1187:12)
15 verbose stack     at IncomingMessage.EventEmitter.emit (events.js:117:20)
15 verbose stack     at _stream_readable.js:920:16
15 verbose stack     at process._tickCallback (node.js:415:13)
16 verbose statusCode 400
17 verbose cwd /home/mc/Papers/Dropbox/Projects/Node/async-chainable
18 error Linux 3.13.0-37-generic
19 error argv "node" "/usr/bin/npm" "adduser"
20 error node v0.10.25
21 error npm  v2.7.3
22 error code E400
23 error Unknown error while authenticating : -/user/org.couchdb.user:hash-bang
24 error If you need help, you may report this error at:
24 error     <https://github.com/npm/npm/issues>
25 verbose exit [ 1, true ]
```

**Comment by bcoe** [comment]
@hash-bang, it looks like you have one of our old-style passwords, before we debug further., could you try:

* logging in at https://www.npmjs.com/
* changing you password, by clicking on your profile, followed by `Change Password`.
* logging in again from the CLI.

Any luck?

**Comment by hash-bang** [comment]
Yey. That fixed it.

Thanks for your help.

**Comment by adamdry** [comment]
I was also getting the E400 error - changing my password through the website and trying npm adduser again fixed the issue!
