### ISSUE TITLE
 running install [-g] appium@1.3.6 in cmd giving issues

### ISSUE THREAD

**Issue by vir513** [npm/npm#7726]
Below is the log:

```
C:\>npm install [-g] appium@1.3.6
npm ERR! Error: failed to fetch from registry: https://registry.npmjs.org/[-g]
npm ERR!     at RegClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\
node_modules\npm-registry-client\lib\get.js:159:18)
npm ERR!     at cb (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-re
gistry-client\lib\request.js:57:9)
npm ERR!     at RegClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\
node_modules\npm-registry-client\lib\request.js:156:10)
npm ERR!     at cb (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-re
gistry-client\lib\request.js:166:9)
npm ERR!     at RegClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\
node_modules\npm-registry-client\lib\request.js:259:20)
npm ERR!     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node
_modules\npm-registry-client\lib\request.js:238:20)
npm ERR!     at self.callback (C:\Program Files\nodejs\node_modules\npm\node_mod
ules\request\request.js:236:22)
npm ERR!     at Request.emit (events.js:117:20)
npm ERR!     at ClientRequest.self.clientErrorHandler (C:\Program Files\nodejs\n
ode_modules\npm\node_modules\request\request.js:341:10)
npm ERR!     at ClientRequest.emit (events.js:95:17)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "[-g]" "appium@1.3.6"
npm ERR! cwd C:\
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\npm-debug.log
npm ERR! not ok code 0
```

**Comment by KenanY** [comment]
@vir513 I think you mean to execute `npm install -g appium@1.3.6` (that is, without the brackets)? It depends on whether you want to install `appium` globally or locally.

**Comment by cdewangan** [comment]
its failing for me also, not able to install in mac:

npm ERR! Command failed: git clone --template=/Users/<user>/.npm/_git-remotes/_templates --mirror git://github.com/vojtajina/traceur-compiler /Users/<user>/.npm/_git-remotes/git-github-com-vojtajina-traceur-compiler-f4c43c65
npm ERR! Cloning into bare repository '/Users/<user>/.npm/_git-remotes/git-github-com-vojtajina-traceur-compiler-f4c43c65'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 198.241.217.15]: errno=Connection refused

Any help please....

**Comment by KenanY** [comment]
@cdewangan Your issue appears to be with your internet connection. The connection to `github.com` is failing. Are you behind a proxy by any chance?

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
