### ISSUE TITLE
Adding Platform / TypeError: Request path contains unescaped characters.

### ISSUE THREAD

**Issue by juppwerner** [npm/npm#7727]
I am using ionic to add the Android platform.

> ionic platform add android

I get this error:

npm http GET https://registry.npmjs.org/cordova-android/3.7.1
TypeError: Request path contains unescaped characters.
    at new ClientRequest (_http_client.js:73:11)
    at TunnelingAgent.exports.request (http.js:49:10)
    at TunnelingAgent.createSocket (C:\Users\xzndzw\AppData\Roaming\npm\node_mod
ules\cordova\node_modules\cordova-lib\node_modules\npm\node_modules\request\node
_modules\tunnel-agent\index.js:117:25)
    at TunnelingAgent.createSecureSocket [as createSocket] (C:\Users\xzndzw\AppD
ata\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\npm\n
ode_modules\request\node_modules\tunnel-agent\index.js:184:41)
    at TunnelingAgent.addRequest (C:\Users\xzndzw\AppData\Roaming\npm\node_modul
es\cordova\node_modules\cordova-lib\node_modules\npm\node_modules\request\node_m
odules\tunnel-agent\index.js:80:8)
    at new ClientRequest (_http_client.js:154:16)
    at Object.exports.request (http.js:49:10)
    at Object.exports.request (https.js:136:15)
    at Request.start (C:\Users\xzndzw\AppData\Roaming\npm\node_modules\cordova\n
ode_modules\cordova-lib\node_modules\npm\node_modules\request\index.js:594:30)
    at Request.end (C:\Users\xzndzw\AppData\Roaming\npm\node_modules\cordova\nod
e_modules\cordova-lib\node_modules\npm\node_modules\request\index.js:1186:28)

I have seen similar related bugs being closed but there is no clear solution.

node -v: v0.12.0
npm -v: 2.7.3
cordova -v: 4.3.0

Why is codova-cli supplied with the whole npm dependency where I have npm already in my AppData\Roaming?

Thanks

**Comment by juppwerner** [comment]
Sorry I should have posted this to the cordova bugtracker...

**Comment by enriqueyt** [comment]
hello, I have been the same error and I can't found any solution. I saw a post that it someone wrote That  We need degrade node.js to version 0.10. You can help wiht it, thanks
