### ISSUE TITLE
Registry returned 500 for PUT while add owner

### ISSUE THREAD

**Issue by huang47** [npm/npm#7729]
```shell
0 info it worked if it ends with ok
1 verbose cli [ 'node',
1 verbose cli   '/Users/hhuang/.nvm/v0.10.35/bin/npm',
1 verbose cli   'owner',
1 verbose cli   'add',
1 verbose cli   'jasoneriksen@yahoo.com',
1 verbose cli   'html-truncate' ]
2 info using npm@2.3.0
3 info using node@v0.10.35
4 verbose owner add jasoneriksen@yahoo.com to html-truncate
5 silly mapToRegistry name -/user/org.couchdb.user:jasoneriksen@yahoo.com
6 silly mapToRegistry using default registry
7 silly mapToRegistry registry https://registry.npmjs.org/
8 silly mapToRegistry uri https://registry.npmjs.org/-/user/org.couchdb.user:jasoneriksen@yahoo.com
9 verbose request uri https://registry.npmjs.org/-/user/org.couchdb.user:jasoneriksen@yahoo.com
10 verbose request new user, so can't send auth
11 info attempt registry request try #1 at 22:36:34
12 verbose request using bearer token for auth
13 verbose request id 259bac778abc6dd0
14 http request GET https://registry.npmjs.org/-/user/org.couchdb.user:jasoneriksen@yahoo.com
15 http 200 https://registry.npmjs.org/-/user/org.couchdb.user:jasoneriksen@yahoo.com
16 silly get cb [ 200,
16 silly get   { date: 'Tue, 24 Mar 2015 14:36:36 GMT',
16 silly get     server: 'Apache',
16 silly get     'content-type': 'application/json',
16 silly get     'cache-control': 'max-age=60',
16 silly get     'content-length': '49',
16 silly get     'accept-ranges': 'bytes',
16 silly get     via: '1.1 varnish',
16 silly get     'x-served-by': 'cache-hkg6822-HKG',
16 silly get     'x-cache': 'MISS',
16 silly get     'x-cache-hits': '0',
16 silly get     'x-timer': 'S1427207796.084285,VS0,VE539',
16 silly get     'keep-alive': 'timeout=10, max=50',
16 silly get     connection: 'Keep-Alive' } ]
17 silly mapToRegistry name html-truncate
18 silly mapToRegistry using default registry
19 silly mapToRegistry registry https://registry.npmjs.org/
20 silly mapToRegistry uri https://registry.npmjs.org/html-truncate
21 verbose request uri https://registry.npmjs.org/html-truncate
22 verbose request no auth needed
23 info attempt registry request try #1 at 22:36:36
24 verbose request using bearer token for auth
25 verbose etag "71KSTOUHS0EOOUVUGSRXQNNNJ"
26 http request GET https://registry.npmjs.org/html-truncate
27 http 304 https://registry.npmjs.org/html-truncate
28 silly get cb [ 304,
28 silly get   { date: 'Tue, 24 Mar 2015 14:36:37 GMT',
28 silly get     server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
28 silly get     etag: '"71KSTOUHS0EOOUVUGSRXQNNNJ"',
28 silly get     'cache-control': 'max-age=60',
28 silly get     'accept-ranges': 'bytes',
28 silly get     via: '1.1 varnish',
28 silly get     'x-served-by': 'cache-hkg6825-HKG',
28 silly get     'x-cache': 'MISS',
28 silly get     'x-cache-hits': '0',
28 silly get     'x-timer': 'S1427207796.927211,VS0,VE595',
28 silly get     'content-length': '0',
28 silly get     'keep-alive': 'timeout=10, max=50',
28 silly get     connection: 'Keep-Alive' } ]
29 verbose etag https://registry.npmjs.org/html-truncate from cache
30 silly mapToRegistry name html-truncate/-rev/25-f13e86ef877b963a59d16b554949cc53
31 silly mapToRegistry using default registry
32 silly mapToRegistry registry https://registry.npmjs.org/
33 silly mapToRegistry uri https://registry.npmjs.org/html-truncate/-rev/25-f13e86ef877b963a59d16b554949cc53
34 verbose request uri https://registry.npmjs.org/html-truncate/-rev/25-f13e86ef877b963a59d16b554949cc53
35 verbose request sending authorization for write operation
36 info attempt registry request try #1 at 22:36:37
37 verbose request using bearer token for auth
38 http request PUT https://registry.npmjs.org/html-truncate/-rev/25-f13e86ef877b963a59d16b554949cc53
39 http 500 https://registry.npmjs.org/html-truncate/-rev/25-f13e86ef877b963a59d16b554949cc53
40 info retry will retry, error on last attempt: Error: Registry returned 500 for PUT on https://registry.npmjs.org/html-truncate/-rev/25-f13e86ef877b963a59d16b554949cc53
41 info attempt registry request try #2 at 22:36:49
42 verbose request using bearer token for auth
43 http request PUT https://registry.npmjs.org/html-truncate/-rev/25-f13e86ef877b963a59d16b554949cc53
44 http 500 https://registry.npmjs.org/html-truncate/-rev/25-f13e86ef877b963a59d16b554949cc53
45 info retry will retry, error on last attempt: Error: Registry returned 500 for PUT on https://registry.npmjs.org/html-truncate/-rev/25-f13e86ef877b963a59d16b554949cc53
46 info attempt registry request try #3 at 22:37:51
47 verbose request using bearer token for auth
48 http request PUT https://registry.npmjs.org/html-truncate/-rev/25-f13e86ef877b963a59d16b554949cc53
49 http 500 https://registry.npmjs.org/html-truncate/-rev/25-f13e86ef877b963a59d16b554949cc53
50 verbose headers { date: 'Tue, 24 Mar 2015 14:37:54 GMT',
50 verbose headers   server: 'Apache',
50 verbose headers   'content-type': 'application/json',
50 verbose headers   'cache-control': 'max-age=0',
50 verbose headers   'content-length': '17',
50 verbose headers   'accept-ranges': 'bytes',
50 verbose headers   via: '1.1 varnish',
50 verbose headers   'x-served-by': 'cache-hkg6822-HKG',
50 verbose headers   'x-cache': 'MISS',
50 verbose headers   'x-cache-hits': '0',
50 verbose headers   'x-timer': 'S1427207873.524374,VS0,VE773',
50 verbose headers   connection: 'close' }
51 verbose request invalidating /Users/hhuang/.npm/registry.npmjs.org/html-truncate on PUT
52 error owner mutate Failed to update package metadata
53 verbose stack Error: Registry returned 500 for PUT on https://registry.npmjs.org/html-truncate/-rev/25-f13e86ef877b963a59d16b554949cc53
53 verbose stack     at CachingRegistryClient.<anonymous> (/Users/hhuang/.nvm/v0.10.35/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:244:14)
53 verbose stack     at Request._callback (/Users/hhuang/.nvm/v0.10.35/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:178:14)
53 verbose stack     at Request.self.callback (/Users/hhuang/.nvm/v0.10.35/lib/node_modules/npm/node_modules/request/request.js:373:22)
53 verbose stack     at Request.emit (events.js:98:17)
53 verbose stack     at Request.<anonymous> (/Users/hhuang/.nvm/v0.10.35/lib/node_modules/npm/node_modules/request/request.js:1318:14)
53 verbose stack     at Request.emit (events.js:117:20)
53 verbose stack     at IncomingMessage.<anonymous> (/Users/hhuang/.nvm/v0.10.35/lib/node_modules/npm/node_modules/request/request.js:1266:12)
53 verbose stack     at IncomingMessage.emit (events.js:117:20)
53 verbose stack     at _stream_readable.js:944:16
53 verbose stack     at process._tickCallback (node.js:442:13)
54 verbose statusCode 500
55 verbose pkgid html-truncate
56 verbose cwd /Users/hhuang/proj/nodejs-html-truncate
57 error Darwin 14.3.0
58 error argv "node" "/Users/hhuang/.nvm/v0.10.35/bin/npm" "owner" "add" "jasoneriksen@yahoo.com" "html-truncate"
59 error node v0.10.35
60 error npm  v2.3.0
61 error code E500
62 error Registry returned 500 for PUT on https://registry.npmjs.org/html-truncate/-rev/25-f13e86ef877b963a59d16b554949cc53
63 error If you need help, you may report this error at:
63 error     <http://github.com/npm/npm/issues>
64 verbose exit [ 1, true ]
```

**Comment by bcoe** [comment]
@huang47 chalk this one up to bad error messages. An owner needs to be added using their npm user name, rather than their email address.

Does jasoneriksen@yahoo.com have an npm account?

**Comment by othiym23** [comment]
Also...

```
24 verbose request using bearer token for auth
```

`registry.npmjs.org` doesn't support token-based auth (yet), so it looks like you probably need to clear out all the auth stuff for `registry.npmjs.org` from `$HOME/.npmrc` and run `npm login` again.

**Comment by carsonwright** [comment]
I'm having trouble authing with npm adduser as well

**Comment by carsonwright** [comment]
p PUT https://registry.npmjs.org/-/user/org.couchdb.user:carsonnwright
npm http 400 https://registry.npmjs.org/-/user/org.couchdb.user:carsonnwright
npm ERR! Error: Unknown error while authenticating : -/user/org.couchdb.user:carsonnwright
npm ERR!     at RegClient.<anonymous> (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:272:14)
npm ERR!     at Request.self.callback (/usr/lib/nodejs/request/index.js:148:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/index.js:896:14)
npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/lib/nodejs/request/index.js:847:12)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)

**Comment by bcoe** [comment]
Hey @carsonwright, could you share the whole npm debug log as a gist?

**Comment by carsonwright** [comment]
Where is the error log again?
It's technically working for me now but if you tell me where it is I'll still post the gist so that if someone else comes across the issue there's either a fix or an explanation

**Comment by bcoe** [comment]
@carsonwright if npm fails, you should see an `npm-debug.log` -- if one is still present could you share.

Adding a user the second time worked? did you do anything else different?

**Comment by huang47** [comment]
Thanks everyone, by using npm account it's working

**Comment by carsonwright** [comment]
I didn't change anything and I don't see an npm-debug.log anymore. Must have deleted it. Its odd how it just suddenly started working.

**Comment by bcoe** [comment]
@carsonwright agreed, please don't hesitate to open an issue if you see any similar behavior.
