### ISSUE TITLE
error parsing json

### ISSUE THREAD

**Issue by webDevelp** [npm/npm#7731]
Good afternoon!
since i installed visual studio i have this problem, i do not know why.
![image](https://cloud.githubusercontent.com/assets/10865147/6807977/e9cce5fe-d251-11e4-8591-284f8cf18850.png)

here is the report:
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'yo' ]
2 info using npm@2.5.1
3 info using node@v0.12.1
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 silly cache add args [ 'yo', null ]
6 verbose cache add spec yo
7 silly cache add parsed spec { raw: 'yo',
7 silly cache add   scope: null,
7 silly cache add   name: 'yo',
7 silly cache add   rawSpec: '',
7 silly cache add   spec: '*',
7 silly cache add   type: 'range' }
8 verbose addNamed yo@*
9 silly addNamed semver.valid null
10 silly addNamed semver.validRange *
11 silly addNameRange { name: 'yo', range: '*', hasData: false }
12 silly mapToRegistry name yo
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry http://registry.npmjs.org/
15 silly mapToRegistry uri http://registry.npmjs.org/yo
16 verbose addNameRange registry:http://registry.npmjs.org/yo not in flight; fetching
17 verbose request uri http://registry.npmjs.org/yo
18 verbose request no auth needed
19 info attempt registry request try #1 at 18:13:54
20 verbose request id 672fecf63c19e693
21 http request GET http://registry.npmjs.org/yo
22 http 404 http://registry.npmjs.org/yo
23 verbose bad json <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
23 verbose bad json <html xmlns="http://www.w3.org/1999/xhtml">
23 verbose bad json <head>
23 verbose bad json <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
23 verbose bad json <title>404 - File or directory not found.</title>
23 verbose bad json <style type="text/css">
23 verbose bad json <!--
23 verbose bad json body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
23 verbose bad json fieldset{padding:0 15px 10px 15px;}
23 verbose bad json h1{font-size:2.4em;margin:0;color:#FFF;}
23 verbose bad json h2{font-size:1.7em;margin:0;color:#CC0000;}
23 verbose bad json h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;}
23 verbose bad json #header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
23 verbose bad json background-color:#555555;}
23 verbose bad json #content{margin:0 0 0 2%;position:relative;}
23 verbose bad json .content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
23 verbose bad json -->
23 verbose bad json </style>
23 verbose bad json </head>
23 verbose bad json <body>
23 verbose bad json <div id="header"><h1>Server Error</h1></div>
23 verbose bad json <div id="content">
23 verbose bad json  <div class="content-container"><fieldset>
23 verbose bad json   <h2>404 - File or directory not found.</h2>
23 verbose bad json   <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
23 verbose bad json  </fieldset></div>
23 verbose bad json </div>
23 verbose bad json </body>
23 verbose bad json </html>
24 error registry error parsing json
25 verbose headers { 'content-type': 'text/html',
25 verbose headers   server: 'Microsoft-IIS/8.5',
25 verbose headers   'x-powered-by': 'ASP.NET',
25 verbose headers   date: 'Tue, 24 Mar 2015 17:13:51 GMT',
25 verbose headers   'content-length': '1245' }
26 silly get cb [ 404,
26 silly get   { 'content-type': 'text/html',
26 silly get     server: 'Microsoft-IIS/8.5',
26 silly get     'x-powered-by': 'ASP.NET',
26 silly get     date: 'Tue, 24 Mar 2015 17:13:51 GMT',
26 silly get     'content-length': '1245' } ]
27 verbose stack SyntaxError: Unexpected token <
27 verbose stack <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
27 verbose stack <html xmlns="http://www.w3.org/1999/xhtml">
27 verbose stack <head>
27 verbose stack <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
27 verbose stack <title>404 - File or directory not found.</title>
27 verbose stack <style type="text/css">
27 verbose stack <!--
27 verbose stack body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
27 verbose stack fieldset{padding:0 15px 10px 15px;}
27 verbose stack h1{font-size:2.4em;margin:0;color:#FFF;}
27 verbose stack h2{font-size:1.7em;margin:0;color:#CC0000;}
27 verbose stack h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;}
27 verbose stack #header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
27 verbose stack background-color:#555555;}
27 verbose stack #content{margin:0 0 0 2%;position:relative;}
27 verbose stack .content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
27 verbose stack -->
27 verbose stack </style>
27 verbose stack </head>
27 verbose stack <body>
27 verbose stack <div id="header"><h1>Server Error</h1></div>
27 verbose stack <div id="content">
27 verbose stack  <div class="content-container"><fieldset>
27 verbose stack   <h2>404 - File or directory not found.</h2>
27 verbose stack   <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
27 verbose stack  </fieldset></div>
27 verbose stack </div>
27 verbose stack </body>
27 verbose stack </html>
27 verbose stack
27 verbose stack     at Object.parse (native)
27 verbose stack     at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:205:23)
27 verbose stack     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:178:14)
27 verbose stack     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:344:22)
27 verbose stack     at Request.emit (events.js:110:17)
27 verbose stack     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1239:14)
27 verbose stack     at Request.emit (events.js:129:20)
27 verbose stack     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1187:12)
27 verbose stack     at IncomingMessage.emit (events.js:129:20)
27 verbose stack     at _stream_readable.js:908:16
28 verbose cwd C:\Users\victorr
29 error Windows_NT 6.3.9600
30 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "yo"
31 error node v0.12.1
32 error npm  v2.5.1
33 error Unexpected token <
33 error <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
33 error <html xmlns="http://www.w3.org/1999/xhtml">
33 error <head>
33 error <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
33 error <title>404 - File or directory not found.</title>
33 error <style type="text/css">
33 error <!--
33 error body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
33 error fieldset{padding:0 15px 10px 15px;}
33 error h1{font-size:2.4em;margin:0;color:#FFF;}
33 error h2{font-size:1.7em;margin:0;color:#CC0000;}
33 error h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;}
33 error #header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
33 error background-color:#555555;}
33 error #content{margin:0 0 0 2%;position:relative;}
33 error .content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
33 error -->
33 error </style>
33 error </head>
33 error <body>
33 error <div id="header"><h1>Server Error</h1></div>
33 error <div id="content">
33 error  <div class="content-container"><fieldset>
33 error   <h2>404 - File or directory not found.</h2>
33 error   <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
33 error  </fieldset></div>
33 error </div>
33 error </body>
33 error </html>
34 error If you need help, you may report this error at:
34 error     <http://github.com/npm/npm/issues>
35 verbose exit [ 1, true ]
```

i cant use yeoman, grunt ..., i tryed to uninstall everything. i installed again node, and now i dont have folder of node. 
please help me.
thanks you!

**Comment by KenanY** [comment]
```
26 silly get { 'content-type': 'text/html',
26 silly get server: 'Microsoft-IIS/8.5',
26 silly get 'x-powered-by': 'ASP.NET',
26 silly get date: 'Tue, 24 Mar 2015 17:13:51 GMT',
26 silly get 'content-length': '1245' } ]
```

Is this a sign that there's a proxy in the way here? I don't think the registry is powered by ASP.NET, right?

**Comment by webDevelp** [comment]
I don't know, i'm so lost at this moment.
I only use node and npm to install yeoman, grunt and bower, So i have no idea about proxy...
since I installed visual studio 2015 all stopped to work

**Comment by pradeepippagunta** [comment]
Plese help me out,how you resolved it

**Comment by smikes** [comment]
Is this still a problem for you?

Could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

There have been a lot of improvements to npm -- especially involving git dependencies -- since 2.5. Can you try updating your npm installation?

There is a bad interaction between two known bugs — one in `node@>0.11` and `iojs` and the other in `npm@<2.8.2`.  This can cause ECONNRESET and ETIMEDOUT errors.  The full writeup is here: https://github.com/npm/npm/issues/7699  You can fix this problem by updating your `npm` to the latest (see below).

To update npm, run `sudo npm -g install npm@latest`.

If you are using `npm` in a Travis CI environment, you can tell Travis to always run with the latest `npm`.  See here for an example .travis.yml file that runs with the latest npm: https://github.com/reid/node-jslint/blob/master/.travis.yml

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

For some Linux distributions (Debian/Ubuntu and RedHat/CentOS), the latest node version provided by the distribution may lag behind the stable version. [Here are instructions from NodeSource](https://github.com/nodesource/distributions) on getting the latest node.

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as resolved / abandoned.
