### ISSUE TITLE
Error while authenticating

### ISSUE THREAD

**Issue by dmelo** [npm/npm#7732]
I was trying to login at registry.npmjs.org when I've got the following error:
```
npm http PUT https://registry.npmjs.org/-/user/org.couchdb.user:dmelo
npm http 400 https://registry.npmjs.org/-/user/org.couchdb.user:dmelo
npm ERR! Error: Unknown error while authenticating : -/user/org.couchdb.user:dmelo
npm ERR!     at RegClient.<anonymous> (/usr/lib/node_modules/npm-registry-client/lib/request.js:272:14)
npm ERR!     at Request.self.callback (/usr/lib/node_modules/request/index.js:148:22)
npm ERR!     at Request.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/lib/node_modules/request/index.js:891:14)
npm ERR!     at Request.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/lib/node_modules/request/index.js:842:12)
npm ERR!     at IncomingMessage.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:944:16
npm ERR!     at process._tickCallback (node.js:442:13)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.19.1-201.fc21.x86_64+debug
npm ERR! command "node" "/usr/bin/npm" "login"
npm ERR! cwd /home/dmelo/proj2/node-vsmvc
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.3.6
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/dmelo/proj2/node-vsmvc/npm-debug.log
npm ERR! not ok code 0
```

**Comment by bcoe** [comment]
@dmelo `npm@1.3.6` is a fairly old client version., could you do me a favor and try the following:

`sudo npm install npm -g`
`npm login`

**Comment by dmelo** [comment]
@bcoe . It worked. Thank you. Btw, version 1.3.6 is the current version on fedora 21.

```
nodejs-fstream-npm.noarch               0.1.5-3.fc21                   installed
nodejs-npm-registry-client.noarch       0.2.28-2.fc21                  installed
nodejs-npm-user-validate.noarch         0.0.3-3.fc21                   installed
nodejs-npmconf.noarch                   0.1.3-2.fc21                   installed
nodejs-npmlog.noarch                    0.0.4-3.fc21                   installed
npm.noarch                              1.3.6-6.fc21                   installed
```

**Comment by junjianwjj** [comment]
I got the same problem,  @bcoe, your suggest is worked! version 1.4.3 to version 2.7.5 on mac os x

**Comment by prust** [comment]
Windows users: after updating check `npm --version` to make sure the updated version is the one being used. Older versions of node pre-installed npm to `Program Files (x86)\node`, which can supercede the install in `AppData\Roaming\npm`.
