### ISSUE TITLE
SPAWN ENOENT error

### ISSUE THREAD

**Issue by RTC1** [npm/npm#7734]
The logs on my Elastic Beanstalk server (EC2) running the Amazon Linux AMI show the following:

```
> node-sass@2.0.1 install /var/app/ondeck/node_modules/laravel-elixir/node_modules/gulp-sass/node_modules/node-sass
> node scripts/install.js

npm ERR! Error: spawn ENOENT
npm ERR!     at errnoException (child_process.js:1001:11)
npm ERR!     at Process.ChildProcess._handle.onexit (child_process.js:792:34)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.14.20-20.44.amzn1.x86_64
npm ERR! command "node" "/usr/bin/npm" "install"
npm ERR! cwd /var/app/ondeck
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.3.6
npm ERR! syscall spawn
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /var/app/ondeck/npm-debug.log
npm ERR! not ok code 0
```

/var/app/ondeck/npm-debug.log doesn't exist, and I can't recreate this by running it manually outside of the build process.

Any help appreciated.

**Comment by KenanY** [comment]
@RTC1 `npm@1.3.6` is almost two years old. Could you at least [upgrade](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-nix-osx-linux-etc) first?

**Comment by RTC1** [comment]
I upgraded NPM and got some more detailed messages:

```
> node-sass@2.0.1 install /var/app/ondeck/node_modules/laravel-elixir/node_modules/gulp-sass/node_modules/node-sass
> node scripts/install.js

npm ERR! Linux 3.14.20-20.44.amzn1.x86_64
npm ERR! argv "node" "/usr/bin/npm" "install"
npm ERR! node v0.10.33
npm ERR! npm  v2.7.3
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! node-sass@2.0.1 install: `node scripts/install.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the node-sass@2.0.1 install script 'node scripts/install.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/app/ondeck/npm-debug.log
```

https://gist.github.com/RTC1/62438cb9157e52f8b59a/raw/gistfile1.txt
