### ISSUE TITLE
npm login doesn't work

### ISSUE THREAD

**Issue by surdu** [npm/npm#7735]
When I run `npm login` or `npm adduser` neither of them adds the user to the config, even if I run them with `sudo`. I'm trying the following on an Ubuntu 14.04 TS:

```
$ node --version
v0.12.0

$ npm --version
2.7.3

$ sudo npm login
Username: surdu
Password: 
Email: (this IS public) .....@gmail.com

$ npm config ls
; cli configs
user-agent = "npm/2.7.3 node/v0.12.0 linux x64"

; node bin location = /usr/local/bin/node
; cwd = /home/postal/github/utils.js
; HOME = /home/postal
; 'npm config ls -l' to show all defaults.

```

As you can see, the user is not set in the cofig. Am I missing something ?

**Comment by bcoe** [comment]
@surdu could you run:

`npm login --verbose`

and share the output with me?

**Comment by surdu** [comment]
```
$ sudo npm login --verbose
npm info it worked if it ends with ok
npm verb cli [ 'node', '/usr/local/bin/npm', 'login', '--verbose' ]
npm info using npm@2.7.3
npm info using node@v0.12.0
npm verb config Skipping project config: /home/postal/.npmrc. (matches userconfig)
Username: surdu
Password: 
Email: (this IS public) <obfuscated>@gmail.com
npm verb adduser before first PUT { _id: 'org.couchdb.user:surdu',
npm verb adduser   name: 'surdu',
npm verb adduser   password: 'XXXXX',
npm verb adduser   email: '<obfuscated>@gmail.com',
npm verb adduser   type: 'user',
npm verb adduser   roles: [],
npm verb adduser   date: '2015-03-25T00:03:25.302Z' }
npm verb request uri https://registry.npmjs.org/-/user/org.couchdb.user:surdu
npm verb request new user, so can't send auth
npm info attempt registry request try #1 at 2:03:25 AM
npm verb request id 94115d32c37e462f
npm http request PUT https://registry.npmjs.org/-/user/org.couchdb.user:surdu
npm http 201 https://registry.npmjs.org/-/user/org.couchdb.user:surdu
npm verb request invalidating /home/postal/.npm/registry.npmjs.org/-/user/org.couchdb.user_3Asurdu on PUT
npm info adduser Authorized user surdu
npm verb exit [ 0, true ]
npm info ok 
```

**Comment by bcoe** [comment]
@surdu the user information will be stored in a `.npmrc` file., in this case it looks like in:

`/home/postal/.npmrc`

If you type `npm whoami`, do you see the appropriate user name?

**Comment by surdu** [comment]
```
$ npm whoami
surdu
```
and the contents of the .npmrc

```
//registry.npmjs.org/:_authToken=09270276-f265-4989-aa20-03d273509726
```

**Comment by bcoe** [comment]
@surdu everything seems in order, npm login is what's populating your `.npmrc`. Are you unable to publish, or seeing any other problems once you have logged in?

**Comment by surdu** [comment]
Mmmyeah... The problem was that there was another package with the same name already published by someone else. This was unfortunately not clear from the output of the `npm publish`:

```
$ npm publish --verbose
npm info it worked if it ends with ok
npm verb cli [ 'node', '/usr/local/bin/npm', 'publish', '--verbose' ]
npm info using npm@2.7.3
npm info using node@v0.12.0
npm verb publish [ '.' ]
npm verb cache add spec .
npm verb addLocalDirectory /home/postal/.npm/utils.js/0.0.0/package.tgz not in flight; packing
npm verb tar pack [ '/home/postal/.npm/utils.js/0.0.0/package.tgz',
npm verb tar pack   '/home/postal/github/utils.js' ]
npm verb tarball /home/postal/.npm/utils.js/0.0.0/package.tgz
npm verb folder /home/postal/github/utils.js
npm info prepublish utils.js@0.0.0
npm verb addLocalTarball adding from inside cache /home/postal/.npm/utils.js/0.0.0/package.tgz
npm verb afterAdd /home/postal/.npm/utils.js/0.0.0/package/package.json not in flight; writing
npm verb afterAdd /home/postal/.npm/utils.js/0.0.0/package/package.json written
npm verb publish registryBase https://registry.npmjs.org/
npm verb request uri https://registry.npmjs.org/utils.js
npm verb request sending authorization for write operation
npm info attempt registry request try #1 at 9:58:23 PM
npm verb request using bearer token for auth
npm verb request id 95a26488380bedc8
npm http request PUT https://registry.npmjs.org/utils.js
npm http 401 https://registry.npmjs.org/utils.js
npm verb headers { date: 'Wed, 25 Mar 2015 19:58:24 GMT',
npm verb headers   server: 'Apache',
npm verb headers   'content-type': 'application/json',
npm verb headers   'cache-control': 'max-age=60',
npm verb headers   'content-length': '38',
npm verb headers   'accept-ranges': 'bytes',
npm verb headers   via: '1.1 varnish',
npm verb headers   'x-served-by': 'cache-fra1241-FRA',
npm verb headers   'x-cache': 'MISS',
npm verb headers   'x-cache-hits': '0',
npm verb headers   'x-timer': 'S1427313503.559711,VS0,VE986',
npm verb headers   'keep-alive': 'timeout=10, max=50',
npm verb headers   connection: 'Keep-Alive' }
npm verb request invalidating /home/postal/.npm/registry.npmjs.org/utils.js on PUT
npm ERR! publish Failed PUT 401
npm verb stack Error: Request was not authorized : utils.js
npm verb stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:254:14)
npm verb stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:178:14)
npm verb stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:344:22)
npm verb stack     at Request.emit (events.js:110:17)
npm verb stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1239:14)
npm verb stack     at Request.emit (events.js:129:20)
npm verb stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1187:12)
npm verb stack     at IncomingMessage.emit (events.js:129:20)
npm verb stack     at _stream_readable.js:908:16
npm verb stack     at process._tickCallback (node.js:355:11)
npm verb statusCode 401
npm verb pkgid utils.js
npm verb cwd /home/postal/github/utils.js
npm ERR! Linux 3.13.0-48-generic
npm ERR! argv "node" "/usr/local/bin/npm" "publish" "--verbose"
npm ERR! node v0.12.0
npm ERR! npm  v2.7.3
npm ERR! code E401

npm ERR! Request was not authorized : utils.js
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm verb exit [ 1, true ]

npm ERR! Please include the following file with any support request:
npm ERR!     /home/postal/github/utils.js/npm-debug.log
```
Anyway, thank you very much for your help !

**Comment by shubhamkes** [comment]
Hi, am trying to install npm install -g firebase-tools 
and getting some pem error
I have run npm publish --verbose and getting following stack trace


npm info it worked if it ends with ok
npm verb cli [ '/usr/local/Cellar/node/6.2.0/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'publish',
npm verb cli   '--verbose' ]
npm info using npm@4.1.2
npm info using node@v6.2.0
npm verb config Skipping project config: /Users/shubham/.npmrc. (matches userconfig)
npm verb publish [ '.' ]
npm verb cache add spec .
npm ERR! addLocal Could not install /Users/shubham/jr/firebase
npm verb stack Error: EISDIR: illegal operation on a directory, read
npm verb stack     at Error (native)
npm verb cwd /Users/shubham/jr/firebase
npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/Cellar/node/6.2.0/bin/node" "/usr/local/bin/npm" "publish" "--verbose"
npm ERR! node v6.2.0
npm ERR! npm  v4.1.2
npm ERR! code EISDIR
npm ERR! errno -21
npm ERR! syscall read

npm ERR! eisdir EISDIR: illegal operation on a directory, read
npm ERR! eisdir This is most likely not a problem with npm itself
npm ERR! eisdir and is related to npm not being able to find a package.json in
npm ERR! eisdir a package you are trying to install.
npm verb exit [ -21, true ]

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/shubham/jr/firebase/npm-debug.log

**Comment by KenanY** [comment]
@shubhamkes Please open a new issue.

**Comment by leduong** [comment]
i'm not login
![screenshot from 2017-08-20 09-15-56](https://user-images.githubusercontent.com/1042749/29491509-319267e2-8588-11e7-938c-ec238f1930c5.png)
