### ISSUE TITLE
Issue using `npm login` and `npm adduser`

### ISSUE THREAD

**Issue by bvaughn** [npm/npm#7737]
Trying to publish an update of my [`angular-form-for` package](https://www.npmjs.com/package/angular-form-for) this evening.

```shell
$ npm login
Username: brianvaughn
Password: 
Email: (briandavidvaughn@gmail.com) 
npm http PUT https://registry.npmjs.org/-/user/org.couchdb.user:brianvaughn
npm http 409 https://registry.npmjs.org/-/user/org.couchdb.user:brianvaughn
npm http GET https://registry.npmjs.org/-/user/org.couchdb.user:brianvaughn
npm http 200 https://registry.npmjs.org/-/user/org.couchdb.user:brianvaughn
npm http PUT https://registry.npmjs.org/-/user/org.couchdb.user:brianvaughn/-rev/undefined
npm http 400 https://registry.npmjs.org/-/user/org.couchdb.user:brianvaughn/-rev/undefined
npm ERR! Error: bad_request Invalid rev format: -/user/org.couchdb.user:brianvaughn/-rev/undefined
npm ERR!     at RegClient.<anonymous> (/usr/local/Cellar/node/0.10.24/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:275:14)
npm ERR!     at Request.self.callback (/usr/local/Cellar/node/0.10.24/lib/node_modules/npm/node_modules/request/request.js:123:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/local/Cellar/node/0.10.24/lib/node_modules/npm/node_modules/request/request.js:893:14)
npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/local/Cellar/node/0.10.24/lib/node_modules/npm/node_modules/request/request.js:844:12)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/isaacs/npm/issues>

npm ERR! System Darwin 13.4.0
npm ERR! command "/usr/local/Cellar/node/0.10.24/bin/node" "/usr/local/bin/npm" "login"
npm ERR! cwd /Users/bvaughn/Documents/git/angular-form-for
npm ERR! node -v v0.10.24
npm ERR! npm -v 1.3.21
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/bvaughn/Documents/git/angular-form-for/npm-debug.log
npm ERR! not ok code 0
```

```shell
$ npm adduser
Username: brianvaughn
Password: 
Email: (briandavidvaughn@gmail.com) 
npm http PUT https://registry.npmjs.org/-/user/org.couchdb.user:brianvaughn
npm http 409 https://registry.npmjs.org/-/user/org.couchdb.user:brianvaughn
npm http GET https://registry.npmjs.org/-/user/org.couchdb.user:brianvaughn
npm http 200 https://registry.npmjs.org/-/user/org.couchdb.user:brianvaughn
npm http PUT https://registry.npmjs.org/-/user/org.couchdb.user:brianvaughn/-rev/undefined
npm http 400 https://registry.npmjs.org/-/user/org.couchdb.user:brianvaughn/-rev/undefined
npm ERR! Error: bad_request Invalid rev format: -/user/org.couchdb.user:brianvaughn/-rev/undefined
npm ERR!     at RegClient.<anonymous> (/usr/local/Cellar/node/0.10.24/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:275:14)
npm ERR!     at Request.self.callback (/usr/local/Cellar/node/0.10.24/lib/node_modules/npm/node_modules/request/request.js:123:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/local/Cellar/node/0.10.24/lib/node_modules/npm/node_modules/request/request.js:893:14)
npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/local/Cellar/node/0.10.24/lib/node_modules/npm/node_modules/request/request.js:844:12)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/isaacs/npm/issues>

npm ERR! System Darwin 13.4.0
npm ERR! command "/usr/local/Cellar/node/0.10.24/bin/node" "/usr/local/bin/npm" "adduser"
npm ERR! cwd /Users/bvaughn/Documents/git/angular-form-for
npm ERR! node -v v0.10.24
npm ERR! npm -v 1.3.21
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/bvaughn/Documents/git/angular-form-for/npm-debug.log
npm ERR! not ok code 0
```

**Comment by bvaughn** [comment]
Poking a bit further, it seems that using a newer version of NPM resolved this issue.
