### ISSUE TITLE
npm login breaks with a Invalid rev format error

### ISSUE THREAD

**Issue by automata** [npm/npm#7739]
When running `npm login --verbose`:

```bash
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'login', '--verbose' ]
2 info using npm@1.3.24
3 info using node@v0.10.25
4 verbose adduser before first PUT { name: 'automata',
4 verbose adduser   salt: 'XXXXX',
4 verbose adduser   password_sha: 'XXXXX',
4 verbose adduser   email: '...@....cc',
4 verbose adduser   _id: 'org.couchdb.user:automata',
4 verbose adduser   type: 'user',
4 verbose adduser   roles: [],
4 verbose adduser   date: '2015-03-25T05:39:23.723Z' }
5 verbose url raw /-/user/org.couchdb.user:automata
6 verbose url resolving [ 'https://registry.npmjs.org/',
6 verbose url resolving   './-/user/org.couchdb.user:automata' ]
7 verbose url resolved https://registry.npmjs.org/-/user/org.couchdb.user:automata
8 info trying registry request attempt 1 at 02:39:23
9 http PUT https://registry.npmjs.org/-/user/org.couchdb.user:automata
10 http 409 https://registry.npmjs.org/-/user/org.couchdb.user:automata
11 verbose adduser update existing user
12 verbose url raw /-/user/org.couchdb.user:automata
13 verbose url resolving [ 'https://registry.npmjs.org/',
13 verbose url resolving   './-/user/org.couchdb.user:automata' ]
14 verbose url resolved https://registry.npmjs.org/-/user/org.couchdb.user:automata
15 info trying registry request attempt 1 at 02:39:24
16 http GET https://registry.npmjs.org/-/user/org.couchdb.user:automata
17 http 200 https://registry.npmjs.org/-/user/org.couchdb.user:automata
18 verbose adduser userobj { name: 'automata',
18 verbose adduser   salt: 'XXXXX',
18 verbose adduser   password_sha: 'XXXXX',
18 verbose adduser   email: '...@....cc',
18 verbose adduser   _id: 'org.couchdb.user:automata',
18 verbose adduser   type: 'user',
18 verbose adduser   roles: [],
18 verbose adduser   date: '2015-03-25T05:39:23.723Z' }
19 verbose url raw /-/user/org.couchdb.user:automata/-rev/undefined
20 verbose url resolving [ 'https://registry.npmjs.org/',
20 verbose url resolving   './-/user/org.couchdb.user:automata/-rev/undefined' ]
21 verbose url resolved https://registry.npmjs.org/-/user/org.couchdb.user:automata/-rev/undefined
22 info trying registry request attempt 1 at 02:39:25
23 http PUT https://registry.npmjs.org/-/user/org.couchdb.user:automata/-rev/undefined
24 http 400 https://registry.npmjs.org/-/user/org.couchdb.user:automata/-rev/undefined
25 verbose adduser back [ [Error: bad_request Invalid rev format: -/user/org.couchdb.user:automata/-rev/undefined],
25 verbose adduser   { error: 'bad_request', reason: 'Invalid rev format' },
25 verbose adduser   '{"error":"bad_request","reason":"Invalid rev format"}' ]
26 error Error: bad_request Invalid rev format: -/user/org.couchdb.user:automata/-rev/undefined
26 error     at RegClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:275:14)
26 error     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:123:22)
26 error     at Request.EventEmitter.emit (events.js:98:17)
26 error     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:893:14)
26 error     at Request.EventEmitter.emit (events.js:117:20)
26 error     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:844:12)
26 error     at IncomingMessage.EventEmitter.emit (events.js:117:20)
26 error     at _stream_readable.js:920:16
26 error     at process._tickCallback (node.js:415:13)
27 error If you need help, you may report this *entire* log,
27 error including the npm and node versions, at:
27 error     <http://github.com/isaacs/npm/issues>
28 error System Darwin 14.1.0
29 error command "node" "/usr/local/bin/npm" "login" "--verbose"
30 error cwd /Users/vilson/src/noflo/noflo-sharp
31 error node -v v0.10.25
32 error npm -v 1.3.24
33 verbose exit [ 1, true ]
```

**Comment by bcoe** [comment]
@automata `npm@1.3.24` is a fairly old version of the client, if you upload npm you should be able to login:

`npm install npm -g`
`npm login`

**Comment by bcoe** [comment]
in case you're reading this in email. npm install npm should be run with `sudo`

**Comment by fergiemcdowall** [comment]
Im getting this as well when trying to publish a new module. Updated npm to no avail

**Comment by fergiemcdowall** [comment]
```
ERR! Error: bad_request Invalid rev format: -/user/org.couchdb.user:fergie/-rev/undefined
npm ERR!     at RegClient.<anonymous> (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:272:14)
npm ERR!     at Request.self.callback (/usr/lib/nodejs/request/index.js:148:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/index.js:896:14)
npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/lib/nodejs/request/index.js:847:12)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>
```

**Comment by fergiemcdowall** [comment]
Seemed to work from another computer (OSX). Didnt work on Ubuntu

**Comment by fergiemcdowall** [comment]
This fixed the problem on my Ubuntu:

https://github.com/npm/npm/issues/6892

**Comment by automata** [comment]
Changing the password on npmjs.com also fixed my issue (OSX). Thanks @bcoe & @fergiemcdowall

**Comment by lukeapage** [comment]
Same error, upgraded npm, same error. Changed password. Fixed.

**Comment by ensonic** [comment]
I changed my password on npmjs.com but it does not help :/

**Comment by ensonic** [comment]
With newer npm it works, the distro npm was shadowing the new version.
