### ISSUE TITLE
npm install jquery-ui@1.11.4 failed

### ISSUE THREAD

**Issue by radision** [npm/npm#7753]
Command like this:

```
npm install jquery-ui@1.11.4

Errors like:
npm ERR! Error: version not found: jquery-ui@1.11.4
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache/add-named.js:125:12
npm ERR!     at saved (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:167:7)
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>
```

**Comment by KenanY** [comment]
@radision No such version of `jquery-ui` exists:

``` sh
$ npm info jquery-ui versions
[ '1.10.4', '1.10.5' ]
```

**Comment by radision** [comment]
@KenanY When will you add jquery-ui@1.11.4 support in npm? Maybe someone need the new features in that version too. Thanks!

**Comment by KenanY** [comment]
@radision Publishing new versions of a package is not `npm`'s responsibility. It is the responsibility of the authors of the packages. Maybe you should contact the authors of `jquery-ui`.

**Comment by radision** [comment]
Ok, Thanks!

**Comment by iarna** [comment]
Closing this as resolved.
