### ISSUE TITLE
Unable to install this package (from registry)

### ISSUE THREAD

**Issue by smikes** [npm/npm#7763]
```
npm install ifyouwanttogetthesumoftwonumberswherethosetwonumbersarechosenbyfindingthelargestoftwooutofthreenumbersandsquaringthemwhichismultiplyingthembyitselfthenyoushouldinputthreenumbersintothisfunctionanditwilldothatforyou@0.0.1
npm WARN package.json @ No description
npm WARN package.json @ No repository field.
npm WARN package.json @ No README data
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/Users/smikes/.nvm/versions/io.js/v1.4.2/bin/npm" "install" "ifyouwanttogetthesumoftwonumberswherethosetwonumbersarechosenbyfindingthelargestoftwooutofthreenumbersandsquaringthemwhichismultiplyingthembyitselfthenyoushouldinputthreenumbersintothisfunctionanditwilldothatforyou@0.0.1"
npm ERR! node v1.4.2
npm ERR! npm  v2.7.3

npm ERR! Uncaught, unspecified "error" event.
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/smikes/src/github/foo/npm-debug.log
```

Partial npm-debug.log
```
26 info retry fetch attempt 1 at 13:55:12
27 info attempt registry request try #1 at 13:55:12
28 http fetch GET https://registry.npmjs.org/ifyouwanttogetthesumoftwonumberswherethosetwonumbersarechosenbyfindingthelargestoftwooutofthreenumbersandsquaringthemwhichismultiplyingthembyitselfthenyoushouldinputthreenumbersintothisfunctionanditwilldothatforyou/-/ifyouwanttogetthesumoftwonumberswherethosetwonumbersarechosenbyfindingthelargestoftwooutofthreenumbersandsquaringthemwhichismultiplyingthembyitselfthenyoushouldinputthreenumbersintothisfunctionanditwilldothatforyou-0.0.0.tgz
29 verbose request id 1c0874ec91bff175
30 http fetch 200 https://registry.npmjs.org/ifyouwanttogetthesumoftwonumberswherethosetwonumbersarechosenbyfindingthelargestoftwooutofthreenumbersandsquaringthemwhichismultiplyingthembyitselfthenyoushouldinputthreenumbersintothisfunctionanditwilldothatforyou/-/ifyouwanttogetthesumoftwonumberswherethosetwonumbersarechosenbyfindingthelargestoftwooutofthreenumbersandsquaringthemwhichismultiplyingthembyitselfthenyoushouldinputthreenumbersintothisfunctionanditwilldothatforyou-0.0.0.tgz
31 verbose stack Error: Uncaught, unspecified "error" event.
31 verbose stack     at Error (native)
31 verbose stack     at emit (events.js:143:13)
31 verbose stack     at cleanupSync (/Users/smikes/.nvm/versions/io.js/v1.4.2/lib/node_modules/npm/node_modules/fs-write-stream-atomic/index.js:46:42)
31 verbose stack     at WriteStream.emit (/Users/smikes/.nvm/versions/io.js/v1.4.2/lib/node_modules/npm/node_modules/fs-write-stream-atomic/index.js:53:12)
31 verbose stack     at WriteStream.<anonymous> (evalmachine.<anonymous>:1817:12)
31 verbose stack     at OpenReq.Req.done (/Users/smikes/.nvm/versions/io.js/v1.4.2/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:141:5)
31 verbose stack     at OpenReq.done (/Users/smikes/.nvm/versions/io.js/v1.4.2/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:61:22)
31 verbose stack     at FSReqWrap.oncomplete (evalmachine.<anonymous>:77:15)
32 verbose cwd /Users/smikes/src/github/foo
33 error Darwin 14.1.0
34 error argv "node" "/Users/smikes/.nvm/versions/io.js/v1.4.2/bin/npm" "install" "ifyouwanttogetthesumoftwonumberswherethosetwonumbersarechosenbyfindingthelargestoftwooutofthreenumbersandsquaringthemwhichismultiplyingthembyitselfthenyoushouldinputthreenumbersintothisfunctionanditwilldothatforyou@0.0.0"
35 error node v1.4.2
36 error npm  v2.7.3
37 error Uncaught, unspecified "error" event.
38 error If you need help, you may report this error at:
38 error     <https://github.com/npm/npm/issues>
39 verbose exit [ 1, true ]
```

Full npm-debug.log here - https://gist.github.com/smikes/a187dc2d21636ae9be28

**Comment by bcoe** [comment]
For what it's worth, I see the tarball and JSON:



```curl
curl -XGET https://registry.npmjs.com/ifyouwanttogetthesumoftwonumberswherethosetwonumbersarechosenbyfindingthelargestoftwooutofthreenumbersandsquaringthemwhichismultiplyingthembyitselfthenyoushouldinputthreenumbersintothisfunctionanditwilldothatforyou/-/ifyouwanttogetthesumoftwonumberswherethosetwonumbersarechosenbyfindingthelargestoftwooutofthreenumbersandsquaringthemwhichismultiplyingthembyitselfthenyoushouldinputthreenumbersintothisfunctionanditwilldothatforyou-0.0.1.tgz
```

```curl
curl -XGET https://registry.npmjs.com/ifyouwanttogetthesumoftwonumberswherethosetwonumbersarechosenbyfindingthelargestoftwooutofthreenumbersandsquaringthemwhichismultiplyingthembyitselfthenyoushouldinputthreenumbersintothisfunctionanditwilldothatforyou
```

**Comment by smikes** [comment]
Thanks.  I have changed the title.  I can download from registry using wget and install as a separate step.  This means that I am now able to get the sum of two numbers, etc.

But `npm install <pkg>` still fails

**Comment by iarna** [comment]
Adding some debugging I see:
```
 { [Error: ENAMETOOLONG: name too long, open '/var/folders/56/cm7r6x9n3h78yb6k6md53k940000gn/T/npm-65999-c6a9c69f/registry.npmjs.org/ifyouwanttogetthesumoftwonumberswherethosetwonumbersarechosenbyfindingthelargestoftwooutofthreenumbersandsquaringthemwhichismultiplyingthembyitselfthenyoushouldinputthreenumbersintothisfunctionanditwilldothatforyou/-/ifyouwanttogetthesumoftwonumberswherethosetwonumbersarechosenbyfindingthelargestoftwooutofthreenumbersandsquaringthemwhichismultiplyingthembyitselfthenyoushouldinputthreenumbersintothisfunctionanditwilldothatforyou-0.0.1.tgz.86d39a4b70f9fab78e47eda0426690ce']
  errno: -63,
  code: 'ENAMETOOLONG',
  syscall: 'open',
```

**Comment by smikes** [comment]
Thanks!  I am OK with closing this bug, since no further action seems necessary.

Do you want me to open a bug on fs-write-stream-atomic?

**Comment by iarna** [comment]
Nah, thanks, I've got that handled.

**Comment by iarna** [comment]
But I would note that the name _wouldn't_ be too long if the cache was laid out differently. 😉
