### ISSUE TITLE
Express is not installing

### ISSUE THREAD

**Issue by atulforever** [npm/npm#7777]
In local windows machine. I have downloaded Node V0.8.0 with NPM V1.1.32.
Now i am trying to install express using npm command it gives errors as below.

```
npm http GET https://registry.npmjs.org/express
npm ERR! Error: SSL Error: CERT_UNTRUSTED
npm ERR!     at ClientRequest.<anonymous> (C:\Program Files\nodejs\node_modules\
npm\node_modules\request\main.js:409:26)
npm ERR!     at ClientRequest.g (events.js:185:14)
npm ERR!     at ClientRequest.EventEmitter.emit (events.js:88:17)
npm ERR!     at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1445:
7)
npm ERR!     at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.
js:111:23)
npm ERR!     at CleartextStream.socketOnData [as ondata] (http.js:1356:20)
npm ERR!     at CleartextStream.CryptoStream._push (tls.js:396:27)
npm ERR!     at SecurePair.cycle (tls.js:751:20)
npm ERR!     at EncryptedStream.CryptoStream.write (tls.js:131:13)
npm ERR!     at Socket.ondata (stream.js:38:26)
npm ERR!  [Error: SSL Error: CERT_UNTRUSTED]
npm ERR! You may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Windows_NT 5.1.2600
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "express"
npm ERR! cwd C:\node
npm ERR! node -v v0.8.0
npm ERR! npm -v 1.1.32
npm ERR! message SSL Error: CERT_UNTRUSTED
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\node\npm-debug.log
npm ERR! not ok code 0
```

**Comment by KenanY** [comment]
``` sh
$ git show v1.1.32
tag v1.1.32
Tagger: isaacs <i@izs.me>
Date:   Fri Jun 22 15:10:22 2012 -0700
```

@atulforever `npm@1.1.32` is almost **three years old**, and no longer supported by the `npm` team. _Please_ try [upgrading node](https://github.com/npm/npm/wiki/Troubleshooting#updating-node-on-windows) and [upgrading `npm`](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows) first!

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
