### ISSUE TITLE
401 when attempting to publish new package

### ISSUE THREAD

**Issue by ainsleychong** [npm/npm#7788]
I realize there have been a few tickets similar this in the past week:

https://github.com/npm/npm/issues/7720
https://github.com/npm/npm/issues/7744

I tried several suggestions I found there, but with no luck:

* Update npm (at v2.7.4, node v0.12.1)
* Deleted .npmrc and did "npm adduser", which worked fine but didn't fix the publish issue
* Reset password from web UI

I don't know if the fact that it's a new package makes any difference. npm-debug:

```
0 info it worked if it ends with ok
1 verbose cli [ 'node',
1 verbose cli   '/Users/ainsleychong/.nvm/versions/v0.12.1/bin/npm',
1 verbose cli   'publish',
1 verbose cli   './' ]
2 info using npm@2.7.4
3 info using node@v0.12.1
4 verbose publish [ './' ]
5 silly cache add args [ './', null ]
6 verbose cache add spec ./
7 silly cache add parsed spec { raw: './',
7 silly cache add   scope: null,
7 silly cache add   name: null,
7 silly cache add   rawSpec: './',
7 silly cache add   spec: '/Users/ainsleychong/Projects/jsonresume-theme-compact',
7 silly cache add   type: 'directory' }
8 verbose addLocalDirectory /Users/ainsleychong/.npm/jsonresume-theme-compact/0.0.1/package.tgz not in flight; packing
9 verbose tar pack [ '/Users/ainsleychong/.npm/jsonresume-theme-compact/0.0.1/package.tgz',
9 verbose tar pack   '/Users/ainsleychong/Projects/jsonresume-theme-compact' ]
10 verbose tarball /Users/ainsleychong/.npm/jsonresume-theme-compact/0.0.1/package.tgz
11 verbose folder /Users/ainsleychong/Projects/jsonresume-theme-compact
12 info prepublish jsonresume-theme-compact@0.0.1
13 verbose addLocalTarball adding from inside cache /Users/ainsleychong/.npm/jsonresume-theme-compact/0.0.1/package.tgz
14 silly cache afterAdd jsonresume-theme-compact@0.0.1
15 verbose afterAdd /Users/ainsleychong/.npm/jsonresume-theme-compact/0.0.1/package/package.json not in flight; writing
16 verbose afterAdd /Users/ainsleychong/.npm/jsonresume-theme-compact/0.0.1/package/package.json written
17 silly publish { name: 'jsonresume-theme-compact',
17 silly publish   version: '0.0.1',
17 silly publish   description: 'Compact, printable theme for JSON Resume',
17 silly publish   author: { name: 'Ainsley Chong' },
17 silly publish   repository:
17 silly publish    { type: 'git',
17 silly publish      url: 'https://github.com/ainsleychong/jsonresume-theme-compact.git' },
17 silly publish   license: 'MIT',
17 silly publish   dependencies: { handlebars: '^2.0.0-alpha.4', css: '2.2.x' },
17 silly publish   bugs: { url: 'https://github.com/ainsleychong/jsonresume-theme-compact/issues' },
17 silly publish   homepage: 'https://github.com/ainsleychong/jsonresume-theme-compact',
17 silly publish   main: 'index.js',
17 silly publish   devDependencies: {},
17 silly publish   readme: '# jsonresume-theme-compact\n\nA compact theme for JSON Resume, designed for printing. \n\nTries to fit as much information as possible onto a single page without making sections look cluttered.\n',
17 silly publish   readmeFilename: 'README.md',
17 silly publish   gitHead: 'c8d5e6007b4ba443c23534f0662fb55513731690',
17 silly publish   _id: 'jsonresume-theme-compact@0.0.1',
17 silly publish   scripts: {},
17 silly publish   _shasum: '0769d9e8f149b97c67cad58c2aca7d6ebaa3fdfa',
17 silly publish   _from: '.' }
18 silly mapToRegistry name jsonresume-theme-compact
19 silly mapToRegistry using default registry
20 silly mapToRegistry registry https://registry.npmjs.org/
21 silly mapToRegistry uri https://registry.npmjs.org/jsonresume-theme-compact
22 verbose publish registryBase https://registry.npmjs.org/
23 silly publish uploading /Users/ainsleychong/.npm/jsonresume-theme-compact/0.0.1/package.tgz
24 verbose request uri https://registry.npmjs.org/jsonresume-theme-compact
25 verbose request sending authorization for write operation
26 info attempt registry request try #1 at 10:30:34
27 verbose request id 6cd10c945070eebf
28 http request PUT https://registry.npmjs.org/jsonresume-theme-compact
29 http 401 https://registry.npmjs.org/jsonresume-theme-compact
30 verbose headers { date: 'Sun, 29 Mar 2015 17:29:30 GMT',
30 verbose headers   server: 'Apache',
30 verbose headers   'content-type': 'application/json',
30 verbose headers   'cache-control': 'max-age=60',
30 verbose headers   'content-length': '38',
30 verbose headers   'accept-ranges': 'bytes',
30 verbose headers   via: '1.1 varnish',
30 verbose headers   'x-served-by': 'cache-sjc3132-SJC',
30 verbose headers   'x-cache': 'MISS',
30 verbose headers   'x-cache-hits': '0',
30 verbose headers   'x-timer': 'S1427650169.958203,VS0,VE134',
30 verbose headers   'keep-alive': 'timeout=10, max=50',
30 verbose headers   connection: 'Keep-Alive' }
31 verbose request invalidating /Users/ainsleychong/.npm/registry.npmjs.org/jsonresume-theme-compact on PUT
32 error publish Failed PUT 401
33 verbose stack Error: Request was not authorized : jsonresume-theme-compact
33 verbose stack     at CachingRegistryClient.<anonymous> (/Users/ainsleychong/.nvm/versions/v0.12.1/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:247:14)
33 verbose stack     at Request._callback (/Users/ainsleychong/.nvm/versions/v0.12.1/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:170:14)
33 verbose stack     at Request.self.callback (/Users/ainsleychong/.nvm/versions/v0.12.1/lib/node_modules/npm/node_modules/request/request.js:344:22)
33 verbose stack     at Request.emit (events.js:110:17)
33 verbose stack     at Request.<anonymous> (/Users/ainsleychong/.nvm/versions/v0.12.1/lib/node_modules/npm/node_modules/request/request.js:1239:14)
33 verbose stack     at Request.emit (events.js:129:20)
33 verbose stack     at IncomingMessage.<anonymous> (/Users/ainsleychong/.nvm/versions/v0.12.1/lib/node_modules/npm/node_modules/request/request.js:1187:12)
33 verbose stack     at IncomingMessage.emit (events.js:129:20)
33 verbose stack     at _stream_readable.js:908:16
33 verbose stack     at process._tickCallback (node.js:355:11)
34 verbose statusCode 401
35 verbose pkgid jsonresume-theme-compact
36 verbose cwd /Users/ainsleychong/Projects/jsonresume-theme-compact
37 error Darwin 13.3.0
38 error argv "node" "/Users/ainsleychong/.nvm/versions/v0.12.1/bin/npm" "publish" "./"
39 error node v0.12.1
40 error npm  v2.7.4
41 error code E401
42 error Request was not authorized : jsonresume-theme-compact
43 error If you need help, you may report this error at:
43 error     <https://github.com/npm/npm/issues>
44 verbose exit [ 1, true ]
```

**Comment by ainsleychong** [comment]
Oh sorry. I didn't realize the package name is already taken on npm.
