### ISSUE TITLE
"npm install -g cordova " goes wrong on window7

### ISSUE THREAD

**Issue by lin-xi** [npm/npm#7797]
```
npm http 200 http://registry.cnpmjs.org/object-keys/download/object-keys-0.4.0.tgz
npm ERR! Error: ENOENT, chmod 'C:\Users\linxi01\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\cordova-js\node_modules\browserify\node_modules\umd\node_modules\ruglify\node_modules\uglify-js\node_modules\source-map\Makefile.dryice.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova"
npm ERR! cwd D:\work\workspace\javascript\github\zdhApp
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! path C:\Users\linxi01\AppData\Roaming\npm\node_modules\cordova\node_mod
ules\cordova-lib\node_modules\cordova-js\node_modules\browserify\node_modules\um
d\node_modules\ruglify\node_modules\uglify-js\node_modules\source-map\Makefile.d
ryice.js
npm ERR! fstream_path C:\Users\linxi01\AppData\Roaming\npm\node_modules\cordova\
node_modules\cordova-lib\node_modules\cordova-js\node_modules\browserify\node_mo
dules\umd\node_modules\ruglify\node_modules\uglify-js\node_modules\source-map\Ma
kefile.dryice.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! fstream_finish_call chmod
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack C:\Program Files\nodejs\node_modules\npm\node_modules\fst
ream\lib\writer.js:305:19
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! EEXIST, mkdir 'C:\Users\linxi01\AppData\Roaming\npm\node_modules\cordov
a\node_modules\cordova-lib\node_modules\cordova-js\node_modules\browserify\node_
modules\umd\node_modules\ruglify\node_modules\uglify-js\node_modules\optimist\ex
ample'
File exists: C:\Users\linxi01\AppData\Roaming\npm\node_modules\cordova\node_modu
les\cordova-lib\node_modules\cordova-js\node_modules\browserify\node_modules\umd
\node_modules\ruglify\node_modules\uglify-js\node_modules\optimist\example
Move it away, and try again.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova"
npm ERR! cwd D:\work\workspace\javascript\github\zdhApp
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! path C:\Users\linxi01\AppData\Roaming\npm\node_modules\cordova\node_mod
ules\cordova-lib\node_modules\cordova-js\node_modules\browserify\node_modules\um
d\node_modules\ruglify\node_modules\uglify-js\node_modules\optimist\example
npm ERR! fstream_path C:\Users\linxi01\AppData\Roaming\npm\node_modules\cordova\
node_modules\cordova-lib\node_modules\cordova-js\node_modules\browserify\node_mo
dules\umd\node_modules\ruglify\node_modules\uglify-js\node_modules\optimist\exam
ple\divide.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code EEXIST
npm ERR! errno 47
npm ERR! fstream_stack C:\Program Files\nodejs\node_modules\npm\node_modules\fst
ream\lib\writer.js:171:23
npm ERR! fstream_stack C:\Program Files\nodejs\node_modules\npm\node_modules\mkd
irp\index.js:37:53
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat 'C:\Users\linxi01\AppData\Roaming\npm\node_modules
\cordova\node_modules\cordova-lib\node_modules\cordova-js\node_modules\browserif
y\node_modules\module-deps\node_modules\subarg\node_modules\minimist\test\short.
js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova"
npm ERR! cwd D:\work\workspace\javascript\github\zdhApp
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! path C:\Users\linxi01\AppData\Roaming\npm\node_modules\cordova\node_mod
ules\cordova-lib\node_modules\cordova-js\node_modules\browserify\node_modules\mo
dule-deps\node_modules\subarg\node_modules\minimist\test\short.js
npm ERR! fstream_path C:\Users\linxi01\AppData\Roaming\npm\node_modules\cordova\
node_modules\cordova-lib\node_modules\cordova-js\node_modules\browserify\node_mo
dules\module-deps\node_modules\subarg\node_modules\minimist\test\short.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack C:\Program Files\nodejs\node_modules\npm\node_modules\fst
ream\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, chmod 'C:\Users\linxi01\AppData\Roaming\npm\node_modules
\cordova\node_modules\cordova-lib\node_modules\cordova-js\node_modules\browserif
y\node_modules\module-deps\node_modules\through2\node_modules\xtend\node_modules
\object-keys\test\shim.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova"
npm ERR! cwd D:\work\workspace\javascript\github\zdhApp
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! path C:\Users\linxi01\AppData\Roaming\npm\node_modules\cordova\node_mod
ules\cordova-lib\node_modules\cordova-js\node_modules\browserify\node_modules\mo
dule-deps\node_modules\through2\node_modules\xtend\node_modules\object-keys\test
\shim.js
npm ERR! fstream_path C:\Users\linxi01\AppData\Roaming\npm\node_modules\cordova\
node_modules\cordova-lib\node_modules\cordova-js\node_modules\browserify\node_mo
dules\module-deps\node_modules\through2\node_modules\xtend\node_modules\object-k
eys\test\shim.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! fstream_finish_call chmod
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack C:\Program Files\nodejs\node_modules\npm\node_modules\fst
ream\lib\writer.js:305:19
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: 404 Not Found
npm ERR!     at WriteStream.<anonymous> (C:\Program Files\nodejs\node_modules\np
m\lib\utils\fetch.js:57:12)
npm ERR!     at WriteStream.EventEmitter.emit (events.js:117:20)
npm ERR!     at fs.js:1598:14
npm ERR!     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-f
s\graceful-fs.js:105:5
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova"
npm ERR! cwd D:\work\workspace\javascript\github\zdhApp
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     D:\work\workspace\javascript\github\zdhApp\npm-debug.log
npm ERR! not ok code 0
```

**Comment by KenanY** [comment]
@lin-xi `npm@1.4.3` is quite old. Could you first try [upgrading node](https://github.com/npm/npm/wiki/Troubleshooting#updating-node-on-windows) and [upgrading `npm`](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows)?

**Comment by lin-xi** [comment]
@KenanY  thank you very much, I updated my node to 0.12.2 and npm to 2.7.4, but there are still some errors.

the install logs list as below:
-------------------------------------
C:\Users\linxi01>npm install -g cordova
npm WARN engine cordova-js@3.8.0: wanted: {"node":"~0.10.x"} (current: {"node":"
0.12.2","npm":"2.7.4"})
npm WARN engine npm@1.3.4: wanted: {"node":">=0.6","npm":"1"} (current: {"node":
"0.12.2","npm":"2.7.4"})
npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {
"node":"0.12.2","npm":"2.7.4"})
npm WARN installMany normalize-package-data was bundled with npm@1.3.4, but bund
led package wasn't found in unpacked tree
npm ERR! fetch failed http://registry.cnpmjs.org/esprima-fb/download/esprima-fb-
3001.1.0-dev-harmony-fb.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with statu
s code 404
npm ERR! fetch failed http://registry.cnpmjs.org/esprima-fb/download/esprima-fb-
3001.1.0-dev-harmony-fb.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with statu
s code 404
npm ERR! fetch failed http://registry.cnpmjs.org/esprima-fb/download/esprima-fb-
3001.1.0-dev-harmony-fb.tgz
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4

npm ERR! fetch failed with status code 404
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\linxi01\npm-debug.log
------------------------------------------

The fail reason is some package is missing.
fetch failed http://registry.cnpmjs.org/esprima-fb/download/esprima-fb-
3001.1.0-dev-harmony-fb.tgz

When I visited this url, I got
 {
error: "Document not found"
}

Is this something wrong with my network?
I’m in China, some websites are blocking by The GWF.
How can I fix this and continue to install cordova？

Thanks.

**Comment by JJLindsay** [comment]
You may want to try an older version on Node.js. I found Node.js v0.10.36 (released Jan 26, 2015) to work fine with Cordova.

http://blog.nodejs.org/2015/01/26/node-v0-10-36-stable/

**Comment by smikes** [comment]
Is this still a problem for you?

There have been a lot of improvements to npm -- especially involving git dependencies -- since 2.7. Can you try updating your npm installation?

There is a bad interaction between two known bugs — one in `node@>0.11` and `iojs` and the other in `npm@<2.8.2`.  This can cause ECONNRESET and ETIMEDOUT errors.  The full writeup is here: https://github.com/npm/npm/issues/7699  You can fix this problem by updating your `npm` to the latest (see below).

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as resolved.
