### ISSUE TITLE
npm adduser failing

### ISSUE THREAD

**Issue by jdarling** [npm/npm#7802]
Setting up a new machine with latest version of NPM on it according to npm install -g npm (1.3.10) I get the following error back out.  Using the same creds I use to login to the npmjs website with no issues.

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'adduser' ]
2 info using npm@1.3.10
3 info using node@v0.10.25
4 verbose adduser before first PUT { name: 'jdarling',
4 verbose adduser   salt: 'XXXXX',
4 verbose adduser   password_sha: 'XXXXX',
4 verbose adduser   email: 'jeremy.darling@gmail.com',
4 verbose adduser   _id: 'org.couchdb.user:jdarling',
4 verbose adduser   type: 'user',
4 verbose adduser   roles: [],
4 verbose adduser   date: '2015-03-31T02:26:02.296Z' }
5 verbose url raw /-/user/org.couchdb.user:jdarling
6 verbose url resolving [ 'https://registry.npmjs.org/',
6 verbose url resolving   './-/user/org.couchdb.user:jdarling' ]
7 verbose url resolved https://registry.npmjs.org/-/user/org.couchdb.user:jdarling
8 info trying registry request attempt 1 at 21:26:02
9 http PUT https://registry.npmjs.org/-/user/org.couchdb.user:jdarling
10 http 409 https://registry.npmjs.org/-/user/org.couchdb.user:jdarling
11 verbose adduser update existing user
12 verbose url raw /-/user/org.couchdb.user:jdarling
13 verbose url resolving [ 'https://registry.npmjs.org/',
13 verbose url resolving   './-/user/org.couchdb.user:jdarling' ]
14 verbose url resolved https://registry.npmjs.org/-/user/org.couchdb.user:jdarling
15 info trying registry request attempt 1 at 21:26:02
16 http GET https://registry.npmjs.org/-/user/org.couchdb.user:jdarling
17 http 200 https://registry.npmjs.org/-/user/org.couchdb.user:jdarling
18 verbose adduser userobj { name: 'jdarling',
18 verbose adduser   salt: 'XXXXX',
18 verbose adduser   password_sha: 'XXXXX',
18 verbose adduser   email: 'jeremy.darling@gmail.com',
18 verbose adduser   _id: 'org.couchdb.user:jdarling',
18 verbose adduser   type: 'user',
18 verbose adduser   roles: [],
18 verbose adduser   date: '2015-03-31T02:26:02.296Z' }
19 verbose url raw /-/user/org.couchdb.user:jdarling/-rev/undefined
20 verbose url resolving [ 'https://registry.npmjs.org/',
20 verbose url resolving   './-/user/org.couchdb.user:jdarling/-rev/undefined' ]
21 verbose url resolved https://registry.npmjs.org/-/user/org.couchdb.user:jdarling/-rev/undefined
22 info trying registry request attempt 1 at 21:26:02
23 http PUT https://registry.npmjs.org/-/user/org.couchdb.user:jdarling/-rev/undefined
24 http 400 https://registry.npmjs.org/-/user/org.couchdb.user:jdarling/-rev/undefined
25 verbose adduser back [ [Error: bad_request Invalid rev format: -/user/org.couchdb.user:jdarling/-rev/undefined],
25 verbose adduser   { error: 'bad_request', reason: 'Invalid rev format' },
25 verbose adduser   '{"error":"bad_request","reason":"Invalid rev format"}' ]
26 error Error: bad_request Invalid rev format: -/user/org.couchdb.user:jdarling/-rev/undefined
26 error     at RegClient.<anonymous> (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:272:14)
26 error     at Request.self.callback (/usr/lib/nodejs/request/index.js:148:22)
26 error     at Request.EventEmitter.emit (events.js:98:17)
26 error     at Request.<anonymous> (/usr/lib/nodejs/request/index.js:896:14)
26 error     at Request.EventEmitter.emit (events.js:117:20)
26 error     at IncomingMessage.<anonymous> (/usr/lib/nodejs/request/index.js:847:12)
26 error     at IncomingMessage.EventEmitter.emit (events.js:117:20)
26 error     at _stream_readable.js:920:16
26 error     at process._tickCallback (node.js:415:13)
27 error If you need help, you may report this log at:
27 error     <http://github.com/isaacs/npm/issues>
27 error or email it to:
27 error     <npm-@googlegroups.com>
28 error System Linux 3.13.0-48-generic
29 error command "/usr/bin/nodejs" "/usr/bin/npm" "adduser"
30 error cwd /home/jdarling/ingredient
31 error node -v v0.10.25
32 error npm -v 1.3.10
33 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
@jdarling `npm@1.3.10` is not the latest... it is over a year old:

```
$ git show v1.3.10
tag v1.3.10
Tagger: isaacs <i@izs.me>
Date:   Wed Sep 4 22:34:18 2013 -0700
```

I cannot imagine why `npm install -g npm` would not install the `latest`.... how about `npm install -g npm@2`?

**Comment by jdarling** [comment]
Well.. I feel sheepish.  npm install -g npm@2 worked!  No clue why it didn't install the latest version :(

Thanks.
