### ISSUE TITLE
Sails - waterlock- npm

### ISSUE THREAD

**Issue by OnlyRefat** [npm/npm#7805]
Hi i am new to sails and waterlock. i Can not install waterlock-local-auth. but i have installed waterlock. the log says:

```
> bcrypt@0.7.8 install /home/developer/Desktop/Sails/AuthTest/node_modules/waterlock-local-auth/node_modules/bcrypt
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.

make: Entering directory `/home/developer/Desktop/Sails/AuthTest/node_modules/waterlock-local-auth/node_modules/bcrypt/build'
 
 CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
../src/bcrypt_node.cc: In destructor ‘virtual {anonymous}::baton_base::~baton_base()’:
../src/bcrypt_node.cc:54:18: error: ‘class v8::Persistent<v8::Function>’ has no member named ‘Dispose’
         callback.Dispose();
                  ^
../src/bcrypt_node.cc: At global scope:
../src/bcrypt_node.cc:128:19: error: variable or field ‘GenSaltAsync’ declared void
 void GenSaltAsync(uv_work_t* req) {
                   ^
../src/bcrypt_node.cc:128:19: error: ‘uv_work_t’ was not declared in this scope
../src/bcrypt_node.cc:128:30: error: ‘req’ was not declared in this scope
 void GenSaltAsync(uv_work_t* req) {
                              ^
../src/bcrypt_node.cc:137:24: error: variable or field ‘GenSaltAsyncAfter’ declared void
 void GenSaltAsyncAfter(uv_work_t* req) {
                        ^
../src/bcrypt_node.cc:137:24: error: ‘uv_work_t’ was not declared in this scope
../src/bcrypt_node.cc:137:35: error: ‘req’ was not declared in this scope
 void GenSaltAsyncAfter(uv_work_t* req) {
                                   ^
../src/bcrypt_node.cc:429:30: error: expected ‘}’ at end of input
 NODE_MODULE(bcrypt_lib, init);
                              ^
make: *** [Release/obj.target/bcrypt_lib/src/bcrypt_node.o] Error 1
make: Leaving directory `/home/developer/Desktop/Sails/AuthTest/node_modules/waterlock-local-auth/node_modules/bcrypt/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Linux 3.13.0-34-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/developer/Desktop/Sails/AuthTest/node_modules/waterlock-local-auth/node_modules/bcrypt
gyp ERR! node -v v0.12.1
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Linux 3.13.0-34-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "waterlock-local-auth"
npm ERR! node v0.12.1
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! bcrypt@0.7.8 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@0.7.8 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/developer/Desktop/Sails/AuthTest/npm-debug.log
```

**Comment by timoxley** [comment]
This doesn't seem to be an issue with npm:

> npm ERR! This is most likely a problem with the bcrypt package,
> npm ERR! not with npm itself.

The version of `bcrypt` you're installing doesn't appear compatible with this version of node. 
You can either downgrade to node 0.10.x or specify a newer version of `bcrypt` in whatever is requiring `bcrypt`, probably `AuthTest`. If it's a 3rd party module requiring `bcrypt` you should try update that tool and if that doesn't work submit a PR to the tool with an updated `bcrypt` (after testing that it works).

**Comment by kmanion** [comment]
Hi @OnlyRefat, it looks like you've gotten some help with this issue, per the most recent comment.

We’re working on cleaning up some older issues. If you have any follow-up questions, please reply and let us know. We'll be happy to answer them and re-open this issue if needed.

Also, feel free to reach out to support@npmjs.com if you need anything else.

-Kiera, npm tech support
