### ISSUE TITLE
npm ERR! invalid for shrinkwrap

### ISSUE THREAD

**Issue by fetis** [npm/npm#7813]
I have shrinkwrapped package with underscore 1.6. I wan to update it to version 1.8.2

```
C:\work\git> npm install underscore@1.8.2 --save
npm WARN unmet dependency C:\work\git\node_modules\ampersand-sync requires underscore@'~1.6.0' but will load
npm WARN unmet dependency C:\work\git\node_modules\underscore,
npm WARN unmet dependency which is version 1.8.2
underscore@1.8.2 node_modules\underscore
```

Looks like ok

Now I'm trying to make new `npm-shrinkwrap.json`

```
C:\work\git> npm shrinkwrap --dev
npm WARN unmet dependency C:\work\git\node_modules\ampersand-sync requires underscore@'~1.6.0' but will load
npm WARN unmet dependency C:\work\git\node_modules\underscore,
npm WARN unmet dependency which is version 1.8.2
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "shrinkwrap" "--dev"
npm ERR! node v0.10.29
npm ERR! npm  v2.3.0

npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! invalid: underscore@1.8.2 C:\work\git\node_modules\underscore
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\work\git\npm-debug.log
```

And my debug log is 

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'shrinkwrap',
1 verbose cli   '--dev' ]
2 info using npm@2.3.0
3 info using node@v0.10.29
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 warn unmet dependency C:\work\git\node_modules\ampersand-sync requires underscore@'~1.6.0' but will load
5 warn unmet dependency C:\work\git\node_modules\underscore,
5 warn unmet dependency which is version 1.8.2
6 verbose stack Error: Problems were encountered
6 verbose stack Please correct and try again.
6 verbose stack invalid: underscore@1.8.2 C:\work\git\node_modules\underscore
6 verbose stack     at shrinkwrap_ (C:\Program Files\nodejs\node_modules\npm\lib\shrinkwrap.js:31:15)
6 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\shrinkwrap.js:25:5
6 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\ls.js:46:30
6 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-installed\read-installed.js:138:5
6 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-installed\read-installed.js:251:14
6 verbose stack     at cb (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:47:24)
6 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-installed\read-installed.js:251:14
6 verbose stack     at cb (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:47:24)
6 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-installed\read-installed.js:251:14
6 verbose stack     at cb (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:47:24)
7 verbose cwd C:\work\git
8 error Windows_NT 6.1.7601
9 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "shrinkwrap" "--dev"
10 error node v0.10.29
11 error npm  v2.3.0
12 error Problems were encountered
12 error Please correct and try again.
12 error invalid: underscore@1.8.2 C:\work\git\node_modules\underscore
13 error If you need help, you may report this error at:
13 error     <http://github.com/npm/npm/issues>
14 verbose exit [ 1, true ]
```

I have no any idea why shrinkwrap fails to create new map file. Can you help?

**Comment by smikes** [comment]
It looks like by upgrading underscore, you have set off a conflict between what `ampersand` wants (underscore 1.6) and what your app wants (underscore 1.8).  You will need to resolve this conflict before the `npm shrinkwrap` command will succeed.

Can you try updating `ampersand` to a newer version?

**Comment by fetis** [comment]
I don't think so, my `npm ls underscore` shows next picture
```
├─┬ ampersand-model@4.0.3
│ └── underscore@1.8.2
├─┬ ampersand-rest-collection@2.0.4
│ └─┬ ampersand-collection-underscore-mixin@1.0.3
│   └── underscore@1.8.2
├─┬ ampersand-state@4.4.4
│ └── underscore@1.8.2
├─┬ backbone@1.1.2
│ └── underscore@1.8.2
├─┬ backbone-filtered-collection@0.4.0
│ └── underscore@1.8.2
├─┬ gulp-svgmin@0.4.8
│ └─┬ svgo@0.5.0
│   └─┬ js-yaml@3.2.6
│     └─┬ argparse@0.1.16
│       └── underscore@1.7.0
├─┬ jshint@2.6.0
│ └── underscore@1.6.0
└── underscore@1.6.0
```

It looks like "bad guy" is jshint. But I don't understand why if affects on npm shrinkwrap when it has its own underscore version.

**Comment by smikes** [comment]
I believe if you try

`npm install ampersand-sync@3.0.4`

it will work, because as of 3.0.4, ampersand-sync uses lodash instead of underscore.

**Comment by monolithed** [comment]
+1,

{code}
➜ npm shrinkwrap --dev
npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "shrinkwrap" "--production"
npm ERR! node v0.12.1
npm ERR! npm  v2.5.1

npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! extraneous: cheerio@0.19.0 /usr/local/www/node_modules/cheerio
npm ERR! extraneous: request@2.58.0 /usr/local/www/node_modules/request
npm ERR! extraneous: x-ray@2.0.2 /usr/local/www/node_modules/x-ray
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/www/npm-debug.log
{code}
