### ISSUE TITLE
install grunt-cli gone wrong 

### ISSUE THREAD

**Issue by HarolDeuh** [npm/npm#7815]
They told me to report errors here, so here I am.

I don't understand the issues. When I try to install npm package (grunt-cli, express), I got the same errors. I already search solutions here but I'm completely lost. So please help me 

This is a debug file I got when I try to install grunt-cli globally. 

````
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'grunt-cli' ]
2 info using npm@2.5.1
3 info using node@v0.12.1
4 silly cache add args [ 'grunt-cli', null ]
5 verbose cache add spec grunt-cli
6 silly cache add parsed spec { raw: 'grunt-cli',
6 silly cache add   scope: null,
6 silly cache add   name: 'grunt-cli',
6 silly cache add   rawSpec: '',
6 silly cache add   spec: '*',
6 silly cache add   type: 'range' }
7 verbose addNamed grunt-cli@*
8 silly addNamed semver.valid null
9 silly addNamed semver.validRange *
10 silly addNameRange { name: 'grunt-cli', range: '*', hasData: false }
11 silly mapToRegistry name grunt-cli
12 silly mapToRegistry using default registry
13 silly mapToRegistry registry https://registry.npmjs.org/
14 silly mapToRegistry uri https://registry.npmjs.org/grunt-cli
15 verbose addNameRange registry:https://registry.npmjs.org/grunt-cli not in flight; fetching
16 verbose request uri https://registry.npmjs.org/grunt-cli
17 verbose request no auth needed
18 info attempt registry request try #1 at 00:23:59
19 verbose request id 13091d25c46efe07
20 verbose etag "7XIL8LLF4UT0FTQYZBA8QKUJ4"
21 http request GET https://registry.npmjs.org/grunt-cli
22 http 304 https://registry.npmjs.org/grunt-cli
23 silly get cb [ 304,
23 silly get   { date: 'Tue, 31 Mar 2015 22:23:59 GMT',
23 silly get     server: 'Apache',
23 silly get     via: '1.1 varnish',
23 silly get     'last-modified': 'Tue, 31 Mar 2015 22:23:28 GMT',
23 silly get     'cache-control': 'max-age=60',
23 silly get     etag: '"7XIL8LLF4UT0FTQYZBA8QKUJ4"',
23 silly get     age: '31',
23 silly get     'x-served-by': 'cache-lcy1126-LCY',
23 silly get     'x-cache': 'HIT',
23 silly get     'x-cache-hits': '2',
23 silly get     'x-timer': 'S1427840639.333605,VS0,VE0',
23 silly get     vary: 'Accept',
23 silly get     'content-length': '0',
23 silly get     'keep-alive': 'timeout=10, max=50',
23 silly get     connection: 'Keep-Alive' } ]
24 verbose etag https://registry.npmjs.org/grunt-cli from cache
25 verbose get saving grunt-cli to /Users/Harol_Deuh/.npm/registry.npmjs.org/grunt-cli/.cache.json
26 silly addNameRange number 2 { name: 'grunt-cli', range: '*', hasData: true }
27 silly addNameRange versions [ 'grunt-cli',
27 silly addNameRange   [ '0.1.0',
27 silly addNameRange     '0.1.1',
27 silly addNameRange     '0.1.2',
27 silly addNameRange     '0.1.3',
27 silly addNameRange     '0.1.4',
27 silly addNameRange     '0.1.5',
27 silly addNameRange     '0.1.6',
27 silly addNameRange     '0.1.7',
27 silly addNameRange     '0.1.8',
27 silly addNameRange     '0.1.9',
27 silly addNameRange     '0.1.10',
27 silly addNameRange     '0.1.11',
27 silly addNameRange     '0.1.12',
27 silly addNameRange     '0.1.13' ] ]
28 verbose addNamed grunt-cli@0.1.13
29 silly addNamed semver.valid 0.1.13
30 silly addNamed semver.validRange 0.1.13
31 silly cache afterAdd grunt-cli@0.1.13
32 verbose afterAdd /Users/Harol_Deuh/.npm/grunt-cli/0.1.13/package/package.json not in flight; writing
33 verbose afterAdd /Users/Harol_Deuh/.npm/grunt-cli/0.1.13/package/package.json written
34 silly install resolved [ { name: 'grunt-cli',
34 silly install resolved     description: 'The grunt command line interface.',
34 silly install resolved     version: '0.1.13',
34 silly install resolved     author: { name: 'Grunt Team' },
34 silly install resolved     homepage: 'http://gruntjs.com/',
34 silly install resolved     repository: { type: 'git', url: 'git://github.com/gruntjs/grunt-cli.git' },
34 silly install resolved     bugs: { url: 'http://github.com/gruntjs/grunt-cli/issues' },
34 silly install resolved     licenses: [ [Object] ],
34 silly install resolved     bin: { grunt: 'bin/grunt' },
34 silly install resolved     engines: { node: '>= 0.8.0' },
34 silly install resolved     scripts: { test: 'node bin/grunt test' },
34 silly install resolved     preferGlobal: true,
34 silly install resolved     dependencies: { nopt: '~1.0.10', 'findup-sync': '~0.1.0', resolve: '~0.3.1' },
34 silly install resolved     devDependencies: { grunt: '~0.4.0', 'grunt-contrib-jshint': '~0.2.0' },
34 silly install resolved     contributors: [ [Object], [Object], [Object], [Object] ],
34 silly install resolved     _id: 'grunt-cli@0.1.13',
34 silly install resolved     dist:
34 silly install resolved      { shasum: 'e9ebc4047631f5012d922770c39378133cad10f4',
34 silly install resolved        tarball: 'http://registry.npmjs.org/grunt-cli/-/grunt-cli-0.1.13.tgz' },
34 silly install resolved     _from: 'grunt-cli@*',
34 silly install resolved     _npmVersion: '1.3.24',
34 silly install resolved     _npmUser: { name: 'tkellen', email: 'tyler@sleekcode.net' },
34 silly install resolved     maintainers: [ [Object] ],
34 silly install resolved     directories: {},
34 silly install resolved     _shasum: 'e9ebc4047631f5012d922770c39378133cad10f4',
34 silly install resolved     _resolved: 'https://registry.npmjs.org/grunt-cli/-/grunt-cli-0.1.13.tgz',
34 silly install resolved     readme: 'ERROR: No README data found!' } ]
35 info install grunt-cli@0.1.13 into /usr/local/lib
36 info installOne grunt-cli@0.1.13
37 verbose installOne of grunt-cli to /usr/local/lib not in flight; installing
38 warn locking Error: EACCES, open '/Users/Harol_Deuh/.npm/_locks/grunt-cli-58f484dab06f0a30.lock'
38 warn locking     at Error (native)
38 warn locking  /Users/Harol_Deuh/.npm/_locks/grunt-cli-58f484dab06f0a30.lock failed { [Error: EACCES, open '/Users/Harol_Deuh/.npm/_locks/grunt-cli-58f484dab06f0a30.lock']
38 warn locking   errno: -13,
38 warn locking   code: 'EACCES',
38 warn locking   path: '/Users/Harol_Deuh/.npm/_locks/grunt-cli-58f484dab06f0a30.lock' }
39 verbose stack Error: Attempt to unlock /usr/local/lib/node_modules/grunt-cli, which hasn't been locked
39 verbose stack     at unlock (/usr/local/lib/node_modules/npm/lib/utils/locker.js:66:11)
39 verbose stack     at cb (/usr/local/lib/node_modules/npm/lib/install.js:929:5)
39 verbose stack     at /usr/local/lib/node_modules/npm/lib/install.js:933:20
39 verbose stack     at /usr/local/lib/node_modules/npm/lib/utils/locker.js:40:9
39 verbose stack     at cb (/usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:149:38)
39 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:177:38
39 verbose stack     at FSReqWrap.oncomplete (fs.js:99:15)
40 verbose cwd /Users/Harol_Deuh/Documents/[coding]
41 error Darwin 14.1.0
42 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "grunt-cli"
43 error node v0.12.1
44 error npm  v2.5.1
45 error Attempt to unlock /usr/local/lib/node_modules/grunt-cli, which hasn't been locked
46 error If you need help, you may report this error at:
46 error     <http://github.com/npm/npm/issues>
47 verbose exit [ 1, true ]


````

**Comment by ralphtheninja** [comment]
@HarolDeuh Are you doing `npm i grunt-cli -g` ?

**Comment by ralphtheninja** [comment]
Oh nevermind.

**Comment by KenanY** [comment]
@HarolDeuh Could you try `sudo chown -R $(whoami) "$HOME/.npm"`?

**Comment by HarolDeuh** [comment]
@KenanY I tried what you said then I try again to install grunt and it didn't work

**Comment by othiym23** [comment]
@HarolDeuh Are you still getting the same error? `sudo chown -R $(whoami) "$HOME/.npm"` is meant to fix this error in your initial report:

```
38 warn locking Error: EACCES, open '/Users/Harol_Deuh/.npm/_locks/grunt-cli-58f484dab06f0a30.lock'
38 warn locking     at Error (native)
38 warn locking  /Users/Harol_Deuh/.npm/_locks/grunt-cli-58f484dab06f0a30.lock failed { [Error: EACCES, open '/Users/Harol_Deuh/.npm/_locks/grunt-cli-58f484dab06f0a30.lock']
38 warn locking   errno: -13,
38 warn locking   code: 'EACCES',
38 warn locking   path: '/Users/Harol_Deuh/.npm/_locks/grunt-cli-58f484dab06f0a30.lock' }
39 verbose stack Error: Attempt to unlock /usr/local/lib/node_modules/grunt-cli, which hasn't been locked
39 verbose stack     at unlock (/usr/local/lib/node_modules/npm/lib/utils/locker.js:66:11)
39 verbose stack     at cb (/usr/local/lib/node_modules/npm/lib/install.js:929:5)
39 verbose stack     at /usr/local/lib/node_modules/npm/lib/install.js:933:20
39 verbose stack     at /usr/local/lib/node_modules/npm/lib/utils/locker.js:40:9
39 verbose stack     at cb (/usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:149:38)
39 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:177:38
39 verbose stack     at FSReqWrap.oncomplete (fs.js:99:15)
```

**Comment by HarolDeuh** [comment]
@othiym23 Everything works fine now. I've used ` sudo chown -R $(whoami) "$HOME/.npm" ` and I'm able to use all the packages I need now. Thank you a lot !!
