### ISSUE TITLE
npm#multi-stage issue

### ISSUE THREAD

**Issue by stefanpenner** [npm/npm#7816]
I realize this is pre-alpha, but I figured I would report this as an early test case, just to be sure it didn't slip through the cracks.

`npm install` fails to install all dependencies

```js
± % npm version                                                                                                                                                                                             !10027
{ 'my-cool-app': '0.0.0',
  npm: '3.0.0-pre.0',
  ares: '1.10.0-DEV',
  http_parser: '2.3.0',
  modules: '43',
  node: '1.6.2',
  openssl: '1.0.1m',
  uv: '1.4.2',
  v8: '4.1.0.25',
  zlib: '1.2.8' }
```

npm sha: cde2c46

---

given:

```sh
git clone https://github.com/stefanpenner/___my-cool-app
cd ___my-cool-app
npm install
```

install appears to complete fine, attempting to boot the app results in:

```js
± % ember s                                                                                                                                                                                                 !10002
version: 0.2.2
Cannot find module 'fast-sourcemap-concat'
Error: Cannot find module 'fast-sourcemap-concat'
    at Function.Module._resolveFilename (module.js:316:15)
    at Function.Module._load (module.js:258:25)
    at Module.require (module.js:345:17)
    at require (module.js:364:17)
    at Object.<anonymous> (/Users/stefanpenner/tmp/my-cool-app/node_modules/broccoli-sourcemap-concat/concat-with-maps.js:5:27)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:428:10)
    at Module.load (module.js:335:32)
    at Function.Module._load (module.js:290:12)
    at Module.require (module.js:345:17)
    at require (module.js:364:17)
```

Some further investigation yields, `broccoli-sourcemap-concat` depends on `fast-sourcemap-concat` (as expected)

```json
cat node_modules/broccoli-sourcemap-concat/package.json | jq '.dependencies'
{
  "broccoli-caching-writer": "0.5.3",
  "broccoli-kitchen-sink-helpers": "^0.2.5",
  "broccoli-writer": "^0.1.1",
  "combined-stream": "0.0.7",
  "fast-sourcemap-concat": " ^0.2.0",
  "lodash-node": "^2.4.1",
  "mkdirp": "^0.5.0",
  "rsvp": "^3.0.14"
}
```

but `fast-sourcemap-concat` does not appear to be installed anywhere.
```js
find node_modules -name fast-sourcemap-concat # nothing
find node_modules -name package.json | xargs cat  | jq '.name' | grep fast-sourcemap-concat # nothing
```

**Comment by stefanpenner** [comment]
@othiym23 let me know if I can provide further information.

**Comment by othiym23** [comment]
@iarna is the person you want to be prodding here, @stefanpenner, because multistage is her baby. ;) She's been down for the count with the flu for the last few days, so that's probably why she hasn't put anything here yet.

**Comment by stefanpenner** [comment]
sounds good, @iarna let me know :)

**Comment by stefanpenner** [comment]
@iarna friendly prod

**Comment by iarna** [comment]
This is not happening any more so I'm guessing the bug was fixed:
```
___my-cool-app$ [master] node ~/code/npm ls fast-sourcemap-concat
my-cool-app@0.0.0 /Users/rebecca/code/npmtest/foo/___my-cool-app
└─┬ ember-cli@0.2.2
  └─┬ broccoli-sourcemap-concat@0.4.3
    └── fast-sourcemap-concat@0.2.4
```

I do see some reports of `invalid` modules, but spot checking shows that's a bug in the npm ls display (relating to bundled git dependencies, I think.) Anyway, I'm going to close this as the missing module problem seems to be solved.

**Comment by stefanpenner** [comment]
awwesome

**Comment by stefanpenner** [comment]
@iarna i just attempted to verify this, unfortunately the multi-stage branch doesn't appear to be in a working state. Is there another branch I should be looking to to verify?

```
± % npm i                                                                                                                                              !10021
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "i"
npm ERR! node v0.12.2
npm ERR! npm  v3.0.0-pre.3
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module '../utils/pulse-till-done.js'
```

a quick search lead to noticing this file is referenced in several places:

```
lib/cache/add-named.js
15:  , pulseTillDone = require("../utils/pulse-till-done.js")

lib/cache/add-remote-tarball.js
13:  , pulseTillDone = require("../utils/pulse-till-done.js")

lib/cache/update-index.js
13:var pulseTillDone = require('../utils/pulse-till-done.js')

lib/fetch-package-metadata.js
24:var pulseTillDone = require('./utils/pulse-till-done.js')
```

but it does not appear to be present any longer.
```
find . -iname pulse-till-done.js
>
```

**Comment by stefanpenner** [comment]
ping @iarna still unable to reproduce your success

**Comment by stefanpenner** [comment]
I was able to confirm a successful app boot on #b2dd728 (latest multi-stage)
