### ISSUE TITLE
npm installations file

### ISSUE THREAD

**Issue by Silve2611** [npm/npm#7826]
Hi, 
I'm getting an installationg error, while running following command. 
```
npm install node-gyp -g
```
the log looks like this:
```
npm http GET http://registry.npmjs.org/node-gyp
npm http 200 http://registry.npmjs.org/node-gyp
npm http GET http://registry.npmjs.org/node-gyp/-/node-gyp-0.9.6.tgz
npm http 200 http://registry.npmjs.org/node-gyp/-/node-gyp-0.9.6.tgz
npm http GET http://registry.npmjs.org/graceful-fs
npm http GET http://registry.npmjs.org/glob
npm http GET http://registry.npmjs.org/fstream
npm http GET http://registry.npmjs.org/minimatch
npm http GET http://registry.npmjs.org/mkdirp
npm http GET http://registry.npmjs.org/nopt
npm http GET http://registry.npmjs.org/npmlog
npm http GET http://registry.npmjs.org/osenv
npm http GET http://registry.npmjs.org/rimraf
npm http GET http://registry.npmjs.org/tar
npm http GET http://registry.npmjs.org/which
npm http GET http://registry.npmjs.org/request
npm http GET http://registry.npmjs.org/semver
npm http 304 http://registry.npmjs.org/minimatch
npm http GET http://registry.npmjs.org/minimatch/-/minimatch-0.4.0.tgz
npm http 304 http://registry.npmjs.org/glob
npm http 304 http://registry.npmjs.org/graceful-fs
npm http 304 http://registry.npmjs.org/fstream
npm http 304 http://registry.npmjs.org/nopt
npm http 304 http://registry.npmjs.org/mkdirp
npm http GET http://registry.npmjs.org/mkdirp/-/mkdirp-0.5.0.tgz
npm http 304 http://registry.npmjs.org/rimraf
npm http 304 http://registry.npmjs.org/npmlog
npm http 304 http://registry.npmjs.org/osenv
npm http 304 http://registry.npmjs.org/tar
npm http 304 http://registry.npmjs.org/which
npm http 304 http://registry.npmjs.org/request
npm http 200 http://registry.npmjs.org/minimatch/-/minimatch-0.4.0.tgz
npm http 304 http://registry.npmjs.org/semver
npm http 200 http://registry.npmjs.org/mkdirp/-/mkdirp-0.5.0.tgz
npm http GET http://registry.npmjs.org/request/-/request-2.12.0.tgz
npm http 200 http://registry.npmjs.org/request/-/request-2.12.0.tgz
npm http GET http://registry.npmjs.org/glob
npm http GET http://registry.npmjs.org/ansi
npm http GET http://registry.npmjs.org/abbrev
npm http 304 http://registry.npmjs.org/glob
npm ERR! error installing rimraf@2.3.2
npm ERR! error installing node-gyp@0.9.6
npm http 304 http://registry.npmjs.org/ansi
npm http 304 http://registry.npmjs.org/abbrev
npm http GET http://registry.npmjs.org/lru-cache
npm http GET http://registry.npmjs.org/sigmund
npm ERR! Error: ENOENT, no such file or directory '/usr/local/lib/node_modules/node-gyp/node_modules/___glob.npm/package/test/cwd-test.js'
npm ERR! Report this *entire* log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>
npm ERR! 
npm ERR! System Darwin 14.0.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "node-gyp" "-g"
npm ERR! cwd /Users/proslav
npm ERR! node -v v0.6.7
npm ERR! npm -v 1.1.0-beta-10
npm ERR! path /usr/local/lib/node_modules/node-gyp/node_modules/___glob.npm/package/test/cwd-test.js
npm ERR! fstream_path /usr/local/lib/node_modules/node-gyp/node_modules/___glob.npm/package/test/cwd-test.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! message ENOENT, no such file or directory '/usr/local/lib/node_modules/node-gyp/node_modules/___glob.npm/package/test/cwd-test.js'
npm ERR! fstream_stack Object.oncomplete (/usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:204:26)
npm ERR! error rolling back node-gyp@0.9.6 Error: UNKNOWN, unknown error '/usr/local/lib/node_modules/node-gyp/node_modules/___mkdirp.npm/package/test'
npm ERR! Error: No compatible version found: glob@'^4.4.2'
npm ERR! Valid install targets:
npm ERR! ["1.1.0","2.1.0","3.0.0","3.0.1","3.1.0","3.1.1","3.1.2","3.1.3","3.1.4","3.1.5","3.1.6","3.1.7","3.1.9","3.1.10","3.1.11","3.1.12","3.1.13","3.1.14","3.1.15","3.1.16","3.1.17","3.1.18","3.1.19","3.1.20","3.1.21","3.2.0","3.2.1","3.2.3","3.2.4","3.2.5","3.2.6","3.2.7","3.2.8","3.2.9","3.2.10","3.2.11","4.0.0","4.0.1","4.0.2","4.0.3","4.0.4","4.0.5","4.0.6","4.1.2-beta","4.1.2","4.1.3","4.1.4","4.1.5","4.1.6","4.2.0","4.2.1","4.2.2","4.3.0","4.3.1","4.3.2","4.3.3","4.3.4","4.3.5","4.4.0","4.4.2","4.5.0","5.0.0","4.5.1","5.0.1","4.5.2","5.0.2","4.5.3","5.0.3"]
npm ERR!     at installTargetsError (/usr/local/lib/node_modules/npm/lib/cache.js:488:10)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:375:15
npm ERR!     at Object.saved [as oncomplete] (/usr/local/lib/node_modules/npm/lib/utils/npm-registry-client/get.js:147:7)
npm ERR! Report this *entire* log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>
npm ERR! 
npm ERR! System Darwin 14.0.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "node-gyp" "-g"
npm ERR! cwd /Users/proslav
npm ERR! node -v v0.6.7
npm ERR! npm -v 1.1.0-beta-10
npm ERR! message No compatible version found: glob@'^4.4.2'
npm ERR! message Valid install targets:
npm ERR! message ["1.1.0","2.1.0","3.0.0","3.0.1","3.1.0","3.1.1","3.1.2","3.1.3","3.1.4","3.1.5","3.1.6","3.1.7","3.1.9","3.1.10","3.1.11","3.1.12","3.1.13","3.1.14","3.1.15","3.1.16","3.1.17","3.1.18","3.1.19","3.1.20","3.1.21","3.2.0","3.2.1","3.2.3","3.2.4","3.2.5","3.2.6","3.2.7","3.2.8","3.2.9","3.2.10","3.2.11","4.0.0","4.0.1","4.0.2","4.0.3","4.0.4","4.0.5","4.0.6","4.1.2-beta","4.1.2","4.1.3","4.1.4","4.1.5","4.1.6","4.2.0","4.2.1","4.2.2","4.3.0","4.3.1","4.3.2","4.3.3","4.3.4","4.3.5","4.4.0","4.4.2","4.5.0","5.0.0","4.5.1","5.0.1","4.5.2","5.0.2","4.5.3","5.0.3"]
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/proslav/npm-debug.log
npm not ok
```

I want to install sqlite3 but it will not work directly. So i tried a source install as described inhttps://www.npmjs.com/package/sqlite3 

Can somebody tell me where the problem is?

**Comment by KenanY** [comment]
@Silve2611 Yikes, Node.js v0.6 is **many years old** and no longer supported by just about anyone in the world, considering how we have had v0.8, v0.10, and v0.12 in the meantime. I highly recommend you first [upgrade](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-node) before asking for any help :)

**Comment by Silve2611** [comment]
I just realized my error. I don't know why such an old version was installed. I'll keep it in mind next time. 

Thx for the helpt

**Comment by iarna** [comment]
Closing this as resolved.
