### ISSUE TITLE
Null reference bug

### ISSUE THREAD

**Issue by leopoldfreeman** [npm/npm#7829]
I just added the check in add-remote-git.js to bypass it.
``` javascript
function (er, stdout, stderr)
  if (er) {
   return resetRemote(cb);
  }
 ...
}
```

Here is the log:
```
691 verbose stack TypeError: Cannot read property 'trim' of undefined
691 verbose stack     at /data/tools/repository/node-v0.12.2/lib/node_modules/npm/lib/cache/add-remote-git.js:98:31
691 verbose stack     at /data/tools/repository/node-v0.12.2/lib/node_modules/npm/lib/utils/git.js:50:14
691 verbose stack     at F (/data/tools/repository/node-v0.12.2/lib/node_modules/npm/node_modules/which/which.js:40:25)
691 verbose stack     at E (/data/tools/repository/node-v0.12.2/lib/node_modules/npm/node_modules/which/which.js:43:29)
691 verbose stack     at /data/tools/repository/node-v0.12.2/lib/node_modules/npm/node_modules/which/which.js:54:16
691 verbose stack     at FSReqWrap.oncomplete (fs.js:95:15)
692 verbose cwd /data/tools/repository
693 error Linux 3.13.0-46-generic
694 error argv "/data/tools/repository/node-v0.12.2/bin/node" "/data/tools/repository/node/bin/npm" "install" "-g" "pm2"
695 error node v0.12.2
696 error npm  v2.7.4
697 error Cannot read property 'trim' of undefined
698 error If you need help, you may report this error at:
698 error     <https://github.com/npm/npm/issues>
```

**Comment by othiym23** [comment]
Thanks! There were a bunch of tiny new edge cases in the git code that people have been finding, and this report was as a result very timely!

**Comment by leopoldfreeman** [comment]
You forgot to check stderr, it can be undefined too.

**Comment by othiym23** [comment]
Thanks again! I added a guard in 637c7d1411fe07f409cf91f2e65fd70685cb253c, which should take care of that case.
