### ISSUE TITLE
Error while updating bower to 1.4.1

### ISSUE THREAD

**Issue by chitru** [npm/npm#7831]
I tried command npm update -g bower and got following error. I've no idea what's the issue so can anyone help me out:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'update',
1 verbose cli   '-g',
1 verbose cli   'bower' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 silly mapToRegistry name bower
6 silly mapToRegistry using default registry
7 silly mapToRegistry registry https://registry.npmjs.org/
8 silly mapToRegistry uri https://registry.npmjs.org/bower
9 verbose request uri https://registry.npmjs.org/bower
10 verbose request no auth needed
11 info attempt registry request try #1 at 12:47:55 PM
12 verbose request id c96358c8955c8bd5
13 verbose etag "BMCU4GRACS4DVWRXI9X6MBE16"
14 http request GET https://registry.npmjs.org/bower
15 http 200 https://registry.npmjs.org/bower
16 silly get cb [ 200,
16 silly get   { date: 'Thu, 02 Apr 2015 07:03:06 GMT',
16 silly get     server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
16 silly get     etag: '"2BIIT5DX6N9ID6S7HVO0AFNTS"',
16 silly get     'content-type': 'application/json',
16 silly get     'cache-control': 'max-age=60',
16 silly get     'content-length': '111515',
16 silly get     'accept-ranges': 'bytes',
16 silly get     via: '1.1 varnish',
16 silly get     age: '28',
16 silly get     'x-served-by': 'cache-lcy1133-LCY',
16 silly get     'x-cache': 'HIT',
16 silly get     'x-cache-hits': '1',
16 silly get     'x-timer': 'S1427958186.488895,VS0,VE0',
16 silly get     vary: 'Accept',
16 silly get     'keep-alive': 'timeout=10, max=50',
16 silly get     connection: 'Keep-Alive' } ]
17 verbose get saving bower to C:\Users\samsung\AppData\Roaming\npm-cache\registry.npmjs.org\bower\.cache.json
18 info outdated updating [ [ 'C:\\Users\\samsung\\AppData\\Roaming\\npm',
18 info outdated     'bower',
18 info outdated     '1.4.0',
18 info outdated     '1.4.1',
18 info outdated     '1.4.1',
18 info outdated     'latest' ] ]
19 verbose install where, what [ 'C:\\Users\\samsung\\AppData\\Roaming\\npm',
19 verbose install   [ 'bower@1.4.1' ] ]
20 silly cache add args [ 'bower@1.4.1', null ]
21 verbose cache add spec bower@1.4.1
22 silly cache add parsed spec { raw: 'bower@1.4.1',
22 silly cache add   scope: null,
22 silly cache add   name: 'bower',
22 silly cache add   rawSpec: '1.4.1',
22 silly cache add   spec: '1.4.1',
22 silly cache add   type: 'version' }
23 verbose addNamed bower@1.4.1
24 silly addNamed semver.valid 1.4.1
25 silly addNamed semver.validRange 1.4.1
26 silly mapToRegistry name bower
27 silly mapToRegistry using default registry
28 silly mapToRegistry registry https://registry.npmjs.org/
29 silly mapToRegistry uri https://registry.npmjs.org/bower
30 verbose addNameVersion registry:https://registry.npmjs.org/bower not in flight; fetching
31 verbose get https://registry.npmjs.org/bower not expired, no request
32 silly mapToRegistry name bower
33 silly mapToRegistry using default registry
34 silly mapToRegistry registry https://registry.npmjs.org/
35 silly mapToRegistry uri https://registry.npmjs.org/bower
36 verbose addRemoteTarball https://registry.npmjs.org/bower/-/bower-1.4.1.tgz not in flight; adding
37 verbose addRemoteTarball [ 'https://registry.npmjs.org/bower/-/bower-1.4.1.tgz',
37 verbose addRemoteTarball   'a18be39d030792754f30f1c5b32d37b0156ba8dd' ]
38 info retry fetch attempt 1 at 12:48:17 PM
39 info attempt registry request try #1 at 12:48:17 PM
40 http fetch GET https://registry.npmjs.org/bower/-/bower-1.4.1.tgz
41 http fetch 200 https://registry.npmjs.org/bower/-/bower-1.4.1.tgz
42 silly fetchAndShaCheck shasum a18be39d030792754f30f1c5b32d37b0156ba8dd
43 verbose stack Error: shasum check failed for C:\Users\samsung\AppData\Local\Temp\npm-4820-14fa8556\registry.npmjs.org\bower\-\bower-1.4.1.tgz
43 verbose stack Expected: a18be39d030792754f30f1c5b32d37b0156ba8dd
43 verbose stack Actual:   f84c502a6470743bd52472c4b1e9f5d65fa0da7c
43 verbose stack From:     https://registry.npmjs.org/bower/-/bower-1.4.1.tgz
43 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\sha\index.js:38:8
43 verbose stack     at ReadStream.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\sha\index.js:85:7)
43 verbose stack     at ReadStream.emit (events.js:129:20)
43 verbose stack     at _stream_readable.js:908:16
43 verbose stack     at process._tickCallback (node.js:355:11)
44 verbose cwd C:\xampp\htdocs\summit
45 error Windows_NT 6.2.9200
46 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "update" "-g" "bower"
47 error node v0.12.0
48 error npm  v2.5.1
49 error shasum check failed for C:\Users\samsung\AppData\Local\Temp\npm-4820-14fa8556\registry.npmjs.org\bower\-\bower-1.4.1.tgz
49 error Expected: a18be39d030792754f30f1c5b32d37b0156ba8dd
49 error Actual:   f84c502a6470743bd52472c4b1e9f5d65fa0da7c
49 error From:     https://registry.npmjs.org/bower/-/bower-1.4.1.tgz
50 error If you need help, you may report this error at:
50 error     <http://github.com/npm/npm/issues>
51 verbose exit [ 1, true ]
```

**Comment by snopeks** [comment]
Hello @chitru We’re trying to clean up some issues. If this is still a problem, can you please reply and let us know? We’ll be happy to reopen if necessary. Thanks! 
-Stephanie, npm Tech Support.
