### ISSUE TITLE
npm install karma --save-dev npm ERR! shasum check failed for

### ISSUE THREAD

**Issue by himanshu-a-rana** [npm/npm#7833]
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'karma',
1 verbose cli   '--save-dev' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 silly cache add args [ 'karma', null ]
6 verbose cache add spec karma
7 silly cache add parsed spec { raw: 'karma',
7 silly cache add   scope: null,
7 silly cache add   name: 'karma',
7 silly cache add   rawSpec: '',
7 silly cache add   spec: '*',
7 silly cache add   type: 'range' }
8 verbose addNamed karma@*
9 silly addNamed semver.valid null
10 silly addNamed semver.validRange *
11 silly addNameRange { name: 'karma', range: '*', hasData: false }
12 silly mapToRegistry name karma
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry http://registry.npmjs.org/
15 silly mapToRegistry uri http://registry.npmjs.org/karma
16 verbose addNameRange registry:http://registry.npmjs.org/karma not in flight; fetching
17 verbose request uri http://registry.npmjs.org/karma
18 verbose request no auth needed
19 info attempt registry request try #1 at 2:34:53 PM
20 verbose request id e5313d85d9726994
21 verbose etag "5QCU801RM1T6HIGHOHT3DGU7A"
22 http request GET http://registry.npmjs.org/karma
23 http 304 http://registry.npmjs.org/karma
24 silly get cb [ 304,
24 silly get   { date: 'Thu, 02 Apr 2015 09:04:51 GMT',
24 silly get     etag: '"5QCU801RM1T6HIGHOHT3DGU7A"',
24 silly get     'cache-control': 'max-age=60',
24 silly get     vary: 'Accept',
24 silly get     connection: 'close',
24 silly get     via: '1.1 localhost.localdomain, 1.1 varnish' } ]
25 verbose etag http://registry.npmjs.org/karma from cache
26 verbose get saving karma to C:\Users\458135\AppData\Roaming\npm-cache\registry.npmjs.org\karma\.cache.json
27 silly addNameRange number 2 { name: 'karma', range: '*', hasData: true }
28 silly addNameRange versions [ 'karma',
28 silly addNameRange   [ '0.8.0',
28 silly addNameRange     '0.9.0-dart',
28 silly addNameRange     '0.8.1',
28 silly addNameRange     '0.8.2',
28 silly addNameRange     '0.8.3',
28 silly addNameRange     '0.9.0',
28 silly addNameRange     '0.8.4',
28 silly addNameRange     '0.9.1',
28 silly addNameRange     '0.8.5',
28 silly addNameRange     '0.9.2',
28 silly addNameRange     '0.9.2-dart',
28 silly addNameRange     '0.9.3',
28 silly addNameRange     '0.8.6',
28 silly addNameRange     '0.9.4',
28 silly addNameRange     '0.8.7',
28 silly addNameRange     '0.9.5',
28 silly addNameRange     '0.9.6',
28 silly addNameRange     '0.8.8',
28 silly addNameRange     '0.9.7',
28 silly addNameRange     '0.9.8',
28 silly addNameRange     '0.10.0',
28 silly addNameRange     '0.10.1',
28 silly addNameRange     '0.10.2',
28 silly addNameRange     '0.11.0',
28 silly addNameRange     '0.11.1',
28 silly addNameRange     '0.10.3',
28 silly addNameRange     '0.10.4',
28 silly addNameRange     '0.11.2',
28 silly addNameRange     '0.11.3',
28 silly addNameRange     '0.10.5',
28 silly addNameRange     '0.11.4',
28 silly addNameRange     '0.11.5',
28 silly addNameRange     '0.10.6',
28 silly addNameRange     '0.11.6',
28 silly addNameRange     '0.10.7',
28 silly addNameRange     '0.11.7',
28 silly addNameRange     '0.11.8',
28 silly addNameRange     '0.11.9',
28 silly addNameRange     '0.10.8',
28 silly addNameRange     '0.11.10',
28 silly addNameRange     '0.11.11',
28 silly addNameRange     '0.11.12',
28 silly addNameRange     '0.11.11-dev',
28 silly addNameRange     '0.10.9',
28 silly addNameRange     '0.11.12-dev',
28 silly addNameRange     '0.11.12-dev2',
28 silly addNameRange     '0.11.13',
28 silly addNameRange     '0.11.14',
28 silly addNameRange     '0.12.0',
28 silly addNameRange     '0.10.10',
28 silly addNameRange     '0.12.1',
28 silly addNameRange     '0.12.2',
28 silly addNameRange     '0.12.3',
28 silly addNameRange     '0.12.4',
28 silly addNameRange     '0.12.5',
28 silly addNameRange     '0.12.6',
28 silly addNameRange     '0.12.6-beta-43e6e28',
28 silly addNameRange     '0.12.7',
28 silly addNameRange     '0.12.8',
28 silly addNameRange     '0.12.9',
28 silly addNameRange     '0.12.10',
28 silly addNameRange     '0.12.11',
28 silly addNameRange     '0.12.12',
28 silly addNameRange     '0.12.11-beta-3029418',
28 silly addNameRange     '0.12.13',
28 silly addNameRange     '0.12.14',
28 silly addNameRange     '0.12.15',
28 silly addNameRange     '0.12.16',
28 silly addNameRange     '0.12.16-beta-905422d',
28 silly addNameRange     '0.12.17',
28 silly addNameRange     '0.12.18',
28 silly addNameRange     '0.12.19',
28 silly addNameRange     '0.12.20',
28 silly addNameRange     '0.12.21',
28 silly addNameRange     '0.12.22',
28 silly addNameRange     '0.12.23',
28 silly addNameRange     '0.12.24',
28 silly addNameRange     '0.12.24-beta-6cf7955',
28 silly addNameRange     '0.12.25',
28 silly addNameRange     '0.12.25-beta-37a7958',
28 silly addNameRange     '0.12.25-beta-ad5bc24',
28 silly addNameRange     '0.12.26',
28 silly addNameRange     '0.12.27',
28 silly addNameRange     '0.12.28',
28 silly addNameRange     '0.12.28-beta-b9be580',
28 silly addNameRange     '0.12.29',
28 silly addNameRange     '0.12.30',
28 silly addNameRange     '0.12.31',
28 silly addNameRange     '0.12.28-beta-f65c864',
28 silly addNameRange     '0.12.24-dev-test',
28 silly addNameRange     '0.12.24-dev-socketio10',
28 silly addNameRange     '0.12.24-dev-socketio10-2',
28 silly addNameRange     '0.12.32-beta.0',
28 silly addNameRange     '0.12.32' ] ]
29 verbose addNamed karma@0.12.31
30 silly addNamed semver.valid 0.12.31
31 silly addNamed semver.validRange 0.12.31
32 silly mapToRegistry name karma
33 silly mapToRegistry using default registry
34 silly mapToRegistry registry http://registry.npmjs.org/
35 silly mapToRegistry uri http://registry.npmjs.org/karma
36 verbose addRemoteTarball http://registry.npmjs.org/karma/-/karma-0.12.31.tgz not in flight; adding
37 verbose addRemoteTarball [ 'http://registry.npmjs.org/karma/-/karma-0.12.31.tgz',
37 verbose addRemoteTarball   '806aa7c2acb13a39edb9374a7a477e643a5e94c9' ]
38 info retry fetch attempt 1 at 2:34:54 PM
39 info attempt registry request try #1 at 2:34:54 PM
40 http fetch GET http://registry.npmjs.org/karma/-/karma-0.12.31.tgz
41 http fetch 200 http://registry.npmjs.org/karma/-/karma-0.12.31.tgz
42 silly fetchAndShaCheck shasum 806aa7c2acb13a39edb9374a7a477e643a5e94c9
43 verbose stack Error: shasum check failed for C:\Users\458135\AppData\Local\Temp\npm-6472-5556a726\registry.npmjs.org\karma\-\karma-0.12.31.tgz
43 verbose stack Expected: 806aa7c2acb13a39edb9374a7a477e643a5e94c9
43 verbose stack Actual:   2f682bb5fc90714651808383b88722ac78c9885d
43 verbose stack From:     http://registry.npmjs.org/karma/-/karma-0.12.31.tgz
43 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\sha\index.js:38:8
43 verbose stack     at ReadStream.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\sha\index.js:85:7)
43 verbose stack     at ReadStream.emit (events.js:129:20)
43 verbose stack     at _stream_readable.js:908:16
43 verbose stack     at process._tickCallback (node.js:355:11)
44 verbose cwd C:\AngularJS\angular-seed-master
45 error Windows_NT 6.1.7601
46 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "karma" "--save-dev"
47 error node v0.12.0
48 error npm  v2.5.1
49 error shasum check failed for C:\Users\458135\AppData\Local\Temp\npm-6472-5556a726\registry.npmjs.org\karma\-\karma-0.12.31.tgz
49 error Expected: 806aa7c2acb13a39edb9374a7a477e643a5e94c9
49 error Actual:   2f682bb5fc90714651808383b88722ac78c9885d
49 error From:     http://registry.npmjs.org/karma/-/karma-0.12.31.tgz
50 error If you need help, you may report this error at:
50 error     <http://github.com/npm/npm/issues>
51 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
@himanshu-a-rana Is this still an issue for you?

**Comment by KenanY** [comment]
Closing as abandoned.
