### ISSUE TITLE
npm deprecate errors out

### ISSUE THREAD

**Issue by kentcdodds** [npm/npm#7839]
```
~/Developer/angular-formly (master)
👽  $ npm deprecate angular-formly@">=5.0.0 <5.0.3" "critical bug fix. Please upgrade to at least 5.0.3"
npm ERR! Darwin 14.1.0
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "deprecate" "angular-formly@>=5.0.0 <5.0.3" "critical bug fix. Please upgrade to at least 5.0.3"
npm ERR! node v1.5.1
npm ERR! npm  v2.7.0
npm ERR! code E500

npm ERR! Registry returned 500 for PUT on https://registry.npmjs.org/angular-formly
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kentcdodds/Developer/angular-formly/npm-debug.log
```

Am I doing anything wrong here?

**Comment by othiym23** [comment]
Probably not, assuming you're logged in as kentcdodds. Can you check that, and maybe log in again? We're making some changes to the registry infrastructure right now, so there are a few things that could be happening here (including some not very helpful error messages ;).

Did you hang on to that `npm-debug.log`?

**Comment by kentcdodds** [comment]
I'm able to publish the library, so I think I'm good there. Here's the `npm-debug.log`:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/iojs',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'deprecate',
1 verbose cli   'angular-formly@>=5.0.0 <5.0.3',
1 verbose cli   'critical bug fix. Please upgrade to at least 5.0.3' ]
2 info using npm@2.7.0
3 info using node@v1.5.1
4 silly mapToRegistry name angular-formly
5 silly mapToRegistry using default registry
6 silly mapToRegistry registry https://registry.npmjs.org/
7 silly mapToRegistry uri https://registry.npmjs.org/angular-formly
8 verbose get GET as part of write; not caching result
9 verbose request uri https://registry.npmjs.org/angular-formly?write=true
10 verbose request no auth needed
11 info attempt registry request try #1 at 10:54:40
12 verbose request id a944f823fd4a96ea
13 http request GET https://registry.npmjs.org/angular-formly?write=true
14 http 200 https://registry.npmjs.org/angular-formly?write=true
15 silly get cb [ 200,
15 silly get   { date: 'Thu, 02 Apr 2015 16:54:40 GMT',
15 silly get     server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
15 silly get     etag: '"394CJ6IILW4AONJNNDYAU0UP9"',
15 silly get     'content-type': 'application/json',
15 silly get     'cache-control': 'max-age=0',
15 silly get     'content-length': '156622',
15 silly get     'accept-ranges': 'bytes',
15 silly get     via: '1.1 varnish',
15 silly get     age: '0',
15 silly get     'x-served-by': 'cache-lax1430-LAX',
15 silly get     'x-cache': 'MISS',
15 silly get     'x-cache-hits': '0',
15 silly get     'x-timer': 'S1427993680.549652,VS0,VE244',
15 silly get     vary: 'Accept',
15 silly get     'keep-alive': 'timeout=10, max=50',
15 silly get     connection: 'Keep-Alive' } ]
16 verbose get saving angular-formly to /Users/kentcdodds/.npm/registry.npmjs.org/angular-formly_3Fwrite_3Dtrue/.cache.json
17 verbose request uri https://registry.npmjs.org/angular-formly
18 verbose request sending authorization for write operation
19 info attempt registry request try #1 at 10:54:40
20 http request PUT https://registry.npmjs.org/angular-formly
21 http 500 https://registry.npmjs.org/angular-formly
22 info retry will retry, error on last attempt: Error: Registry returned 500 for PUT on https://registry.npmjs.org/angular-formly
23 info attempt registry request try #2 at 10:54:53
24 http request PUT https://registry.npmjs.org/angular-formly
25 http 500 https://registry.npmjs.org/angular-formly
26 info retry will retry, error on last attempt: Error: Registry returned 500 for PUT on https://registry.npmjs.org/angular-formly
27 info attempt registry request try #3 at 10:55:54
28 http request PUT https://registry.npmjs.org/angular-formly
29 http 500 https://registry.npmjs.org/angular-formly
30 verbose headers { date: 'Thu, 02 Apr 2015 16:55:54 GMT',
30 verbose headers   server: 'Apache',
30 verbose headers   'content-type': 'application/json',
30 verbose headers   'cache-control': 'max-age=0',
30 verbose headers   'content-length': '17',
30 verbose headers   'accept-ranges': 'bytes',
30 verbose headers   via: '1.1 varnish',
30 verbose headers   'x-served-by': 'cache-lax1425-LAX',
30 verbose headers   'x-cache': 'MISS',
30 verbose headers   'x-cache-hits': '0',
30 verbose headers   'x-timer': 'S1427993754.342062,VS0,VE391',
30 verbose headers   connection: 'close' }
31 verbose request invalidating /Users/kentcdodds/.npm/registry.npmjs.org/angular-formly on PUT
32 verbose stack Error: Registry returned 500 for PUT on https://registry.npmjs.org/angular-formly
32 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:244:14)
32 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:178:14)
32 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:344:22)
32 verbose stack     at emitTwo (events.js:87:13)
32 verbose stack     at Request.emit (events.js:169:7)
32 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1239:14)
32 verbose stack     at emitOne (events.js:82:20)
32 verbose stack     at Request.emit (events.js:166:7)
32 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1187:12)
32 verbose stack     at emitNone (events.js:72:20)
33 verbose statusCode 500
34 verbose pkgid angular-formly
35 verbose cwd /Users/kentcdodds/Developer/angular-formly
36 error Darwin 14.1.0
37 error argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "deprecate" "angular-formly@>=5.0.0 <5.0.3" "critical bug fix. Please upgrade to at least 5.0.3"
38 error node v1.5.1
39 error npm  v2.7.0
40 error code E500
41 error Registry returned 500 for PUT on https://registry.npmjs.org/angular-formly
42 error If you need help, you may report this error at:
42 error     <http://github.com/npm/npm/issues>
43 verbose exit [ 1, true ]
```

**Comment by bcoe** [comment]
@kentcdodds I see the failed deprecation in the logs and am digging into it, might ask you to republish in a few minutes -- are you in IRC?

**Comment by kentcdodds** [comment]
@bcoe, yes: kentcdodds

**Comment by bcoe** [comment]
@kentcdodds I have deployed a fix to your bug, and the deprecation command now works for me:

`npm deprecate angular-formly@">=5.0.0 <5.0.3" "critical bug fix. Please upgrade to at least 5.0.3"`

I've removed myself as an owner already, let me know if you run into any more issues :+1:  thanks for all your help debugging.

**Comment by kentcdodds** [comment]
Thanks for fixing! Did you already deprecate then?

**Comment by bcoe** [comment]
@kentcdodds yep, ran the command once and confirmed it had worked -- give it a shot though, and make sure you don't get a 500.
