### ISSUE TITLE
can't install cordova on my Mac OS X 10.10

### ISSUE THREAD

**Issue by wenmark** [npm/npm#7840]
Was able to install cordova on my PC, but now trying on my mac fails with the attached messages in the debug file.

using npg install -g cordova
```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'install', '-g', 'cordova' ]
2 info using npm@2.5.1
3 info using node@v0.12.1
4 silly cache add args [ 'cordova', null ]
5 verbose cache add spec cordova
6 silly cache add parsed spec { raw: 'cordova',
6 silly cache add   scope: null,
6 silly cache add   name: 'cordova',
6 silly cache add   rawSpec: '',
6 silly cache add   spec: '*',
6 silly cache add   type: 'range' }
7 verbose addNamed cordova@*
8 silly addNamed semver.valid null
9 silly addNamed semver.validRange *
10 silly addNameRange { name: 'cordova', range: '*', hasData: false }
11 silly mapToRegistry name cordova
12 silly mapToRegistry using default registry
13 silly mapToRegistry registry https://registry.npmjs.org/
14 silly mapToRegistry uri https://registry.npmjs.org/cordova
15 verbose addNameRange registry:https://registry.npmjs.org/cordova not in flight; fetching
16 verbose request uri https://registry.npmjs.org/cordova
17 verbose request no auth needed
18 info attempt registry request try #1 at 2:24:00 PM
19 verbose request id d426d1ade712a427
20 verbose etag "3UVZR202KYXYJF62ELH8JYIUQ"
21 http request GET https://registry.npmjs.org/cordova
22 http 200 https://registry.npmjs.org/cordova
23 silly get cb [ 200,
23 silly get   { date: 'Thu, 02 Apr 2015 20:23:59 GMT',
23 silly get     server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
23 silly get     etag: '"7FD7GZ6N40D0M2QWZZ34G2X7L"',
23 silly get     'content-type': 'application/json',
23 silly get     'cache-control': 'max-age=60',
23 silly get     'content-length': '340541',
23 silly get     'accept-ranges': 'bytes',
23 silly get     via: '1.1 varnish',
23 silly get     age: '0',
23 silly get     'x-served-by': 'cache-sjc3129-SJC',
23 silly get     'x-cache': 'HIT',
23 silly get     'x-cache-hits': '1',
23 silly get     'x-timer': 'S1428006239.251277,VS0,VE86',
23 silly get     vary: 'Accept',
23 silly get     'keep-alive': 'timeout=10, max=50',
23 silly get     connection: 'Keep-Alive' } ]
24 verbose get saving cordova to /Users/markschnegg/.npm/registry.npmjs.org/cordova/.cache.json
25 silly addNameRange number 2 { name: 'cordova', range: '*', hasData: true }
26 silly addNameRange versions [ 'cordova',
26 silly addNameRange   [ '0.0.1',
26 silly addNameRange     '0.0.2',
26 silly addNameRange     '0.0.3',
26 silly addNameRange     '0.0.4',
26 silly addNameRange     '0.0.5',
26 silly addNameRange     '0.0.6',
26 silly addNameRange     '0.0.7',
26 silly addNameRange     '0.0.8',
26 silly addNameRange     '0.0.9',
26 silly addNameRange     '0.1.0',
26 silly addNameRange     '0.1.1',
26 silly addNameRange     '0.1.2',
26 silly addNameRange     '0.1.3',
26 silly addNameRange     '0.1.4',
26 silly addNameRange     '0.1.5',
26 silly addNameRange     '0.1.6',
26 silly addNameRange     '0.1.7',
26 silly addNameRange     '0.1.8',
26 silly addNameRange     '0.1.9',
26 silly addNameRange     '0.1.10',
26 silly addNameRange     '0.1.11',
26 silly addNameRange     '0.1.12',
26 silly addNameRange     '0.1.13',
26 silly addNameRange     '0.1.14',
26 silly addNameRange     '2.2.0',
26 silly addNameRange     '2.3.0',
26 silly addNameRange     '2.3.1',
26 silly addNameRange     '2.3.2',
26 silly addNameRange     '2.3.3',
26 silly addNameRange     '2.3.5',
26 silly addNameRange     '2.3.6',
26 silly addNameRange     '2.4.0',
26 silly addNameRange     '2.4.1',
26 silly addNameRange     '2.4.2',
26 silly addNameRange     '2.4.3',
26 silly addNameRange     '2.4.4',
26 silly addNameRange     '2.4.5',
26 silly addNameRange     '2.4.6',
26 silly addNameRange     '2.4.7',
26 silly addNameRange     '2.4.8',
26 silly addNameRange     '2.4.9',
26 silly addNameRange     '2.4.10',
26 silly addNameRange     '2.5.0',
26 silly addNameRange     '2.5.2',
26 silly addNameRange     '2.5.3',
26 silly addNameRange     '2.5.4',
26 silly addNameRange     '2.5.5',
26 silly addNameRange     '2.6.0',
26 silly addNameRange     '2.6.1',
26 silly addNameRange     '2.6.2',
26 silly addNameRange     '2.7.0-rc.1',
26 silly addNameRange     '2.7.1-rc.1',
26 silly addNameRange     '2.7.2',
26 silly addNameRange     '2.7.3',
26 silly addNameRange     '2.7.4',
26 silly addNameRange     '2.8.0',
26 silly addNameRange     '2.8.1',
26 silly addNameRange     '2.8.2',
26 silly addNameRange     '2.8.3',
26 silly addNameRange     '2.8.4',
26 silly addNameRange     '2.8.5',
26 silly addNameRange     '2.8.6',
26 silly addNameRange     '2.8.7',
26 silly addNameRange     '2.8.8',
26 silly addNameRange     '2.8.9',
26 silly addNameRange     '2.8.10',
26 silly addNameRange     '2.8.11',
26 silly addNameRange     '2.8.12',
26 silly addNameRange     '2.8.13',
26 silly addNameRange     '2.8.14',
26 silly addNameRange     '2.8.15',
26 silly addNameRange     '2.8.16',
26 silly addNameRange     '2.8.17',
26 silly addNameRange     '2.8.18',
26 silly addNameRange     '2.8.19',
26 silly addNameRange     '2.8.20',
26 silly addNameRange     '2.8.21',
26 silly addNameRange     '2.8.22',
26 silly addNameRange     '2.8.23',
26 silly addNameRange     '2.8.24',
26 silly addNameRange     '2.8.25',
26 silly addNameRange     '2.9.0',
26 silly addNameRange     '2.9.1',
26 silly addNameRange     '2.9.2',
26 silly addNameRange     '2.9.3',
26 silly addNameRange     '2.9.4',
26 silly addNameRange     '2.9.5',
26 silly addNameRange     '2.9.6',
26 silly addNameRange     '2.9.7',
26 silly addNameRange     '3.0.0-rc1',
26 silly addNameRange     '3.0.0-rc1-1',
26 silly addNameRange     '3.0.0-rc1-3',
26 silly addNameRange     '3.0.0',
26 silly addNameRange     '3.0.1',
26 silly addNameRange     '3.0.2',
26 silly addNameRange     '3.0.3',
26 silly addNameRange     '3.0.4',
26 silly addNameRange     '3.0.5',
26 silly addNameRange     '3.0.6',
26 silly addNameRange     '3.0.7',
26 silly addNameRange     '3.0.8',
26 silly addNameRange     '3.0.9',
26 silly addNameRange     '3.0.10',
26 silly addNameRange     '3.1.0-0.1.0',
26 silly addNameRange     '3.1.0-0.2.0',
26 silly addNameRange     '3.2.0-rc.1',
26 silly addNameRange     '3.2.0-0.1.0',
26 silly addNameRange     '3.2.0-0.2.0',
26 silly addNameRange     '3.2.0-0.3.0',
26 silly addNameRange     '3.2.0-0.4.0',
26 silly addNameRange     '3.3.0-rc.1',
26 silly addNameRange     '3.3.0-0.1.1',
26 silly addNameRange     '3.3.1-0.1.2',
26 silly addNameRange     '2.9.0-rc1',
26 silly addNameRange     '3.3.1-0.3.0',
26 silly addNameRange     '3.3.1-0.3.1',
26 silly addNameRange     '3.3.1-0.4.1',
26 silly addNameRange     '3.3.1-0.4.2',
26 silly addNameRange     '3.4.0-0.1.0',
26 silly addNameRange     '3.4.0-0.1.1',
26 silly addNameRange     '3.4.0-0.1.2',
26 silly addNameRange     '3.4.0-0.1.3',
26 silly addNameRange     '0.0.0-fake',
26 silly addNameRange     '3.4.1-0.1.0',
26 silly addNameRange     '3.5.0-0.2.0',
26 silly addNameRange     '3.5.0-0.2.1',
26 silly addNameRange     '3.5.0-0.2.2',
26 silly addNameRange     '3.5.0-0.2.3',
26 silly addNameRange     '3.5.0-0.2.4',
26 silly addNameRange     '3.5.0-0.2.6',
26 silly addNameRange     '3.5.0-0.2.7',
26 silly addNameRange     '3.6.0-0.2.8',
26 silly addNameRange     '3.6.0-0.2.9',
26 silly addNameRange     '3.6.1-0.2.10',
26 silly addNameRange     '3.6.3-0.2.11',
26 silly addNameRange     '3.6.3-0.2.12',
26 silly addNameRange     '3.6.3-0.2.13',
26 silly addNameRange     '4.0.0',
26 silly addNameRange     '4.0.1',
26 silly addNameRange     '4.1.0',
26 silly addNameRange     '4.1.1',
26 silly addNameRange     '4.1.2',
26 silly addNameRange     '4.1.3-nightly.2014.10.21',
26 silly addNameRange     '4.2.0',
26 silly addNameRange     '4.3.0' ] ]
27 verbose addNamed cordova@4.3.0
28 silly addNamed semver.valid 4.3.0
29 silly addNamed semver.validRange 4.3.0
30 silly cache afterAdd cordova@4.3.0
31 verbose afterAdd /Users/markschnegg/.npm/cordova/4.3.0/package/package.json not in flight; writing
32 verbose afterAdd /Users/markschnegg/.npm/cordova/4.3.0/package/package.json written
33 silly install resolved [ { name: 'cordova',
33 silly install resolved     version: '4.3.0',
33 silly install resolved     preferGlobal: 'true',
33 silly install resolved     description: 'Cordova command line interface tool',
33 silly install resolved     main: 'cordova',
33 silly install resolved     engines: { node: '>=0.9.9' },
33 silly install resolved     engineStrict: true,
33 silly install resolved     bin: { cordova: './bin/cordova' },
33 silly install resolved     scripts:
33 silly install resolved      { test: 'node node_modules/jasmine-node/bin/jasmine-node --captureExceptions --color spec',
33 silly install resolved        cover: 'node node_modules/istanbul/lib/cli.js cover --root src --print detail node_modules/jasmine-node/bin/jasmine-node -- spec' },
33 silly install resolved     repository:
33 silly install resolved      { type: 'git',
33 silly install resolved        url: 'https://git-wip-us.apache.org/repos/asf/cordova-cli.git' },
33 silly install resolved     bugs:
33 silly install resolved      { url: 'https://issues.apache.org/jira/browse/CB',
33 silly install resolved        email: 'dev@cordova.apache.org' },
33 silly install resolved     keywords: [ 'cordova', 'client', 'cli' ],
33 silly install resolved     dependencies:
33 silly install resolved      { 'cordova-lib': '4.3.0',
33 silly install resolved        q: '1.0.1',
33 silly install resolved        nopt: '3.0.1',
33 silly install resolved        underscore: '1.7.0' },
33 silly install resolved     devDependencies:
33 silly install resolved      { istanbul: '^0.3.4',
33 silly install resolved        grunt: '0.4.5',
33 silly install resolved        'grunt-retire': '0.3.7',
33 silly install resolved        'jasmine-node': '1.14.5' },
33 silly install resolved     author: { name: 'Anis Kadri' },
33 silly install resolved     contributors:
33 silly install resolved      [ [Object],
33 silly install resolved        [Object],
33 silly install resolved        [Object],
33 silly install resolved        [Object],
33 silly install resolved        [Object],
33 silly install resolved        [Object],
33 silly install resolved        [Object],
33 silly install resolved        [Object],
33 silly install resolved        [Object],
33 silly install resolved        [Object],
33 silly install resolved        [Object],
33 silly install resolved        [Object],
33 silly install resolved        [Object],
33 silly install resolved        [Object],
33 silly install resolved        [Object],
33 silly install resolved        [Object],
33 silly install resolved        [Object],
33 silly install resolved        [Object],
33 silly install resolved        [Object],
33 silly install resolved        [Object],
33 silly install resolved        [Object],
33 silly install resolved        [Object],
33 silly install resolved        [Object],
33 silly install resolved        [Object] ],
33 silly install resolved     license: 'Apache version 2.0',
33 silly install resolved     _id: 'cordova@4.3.0',
33 silly install resolved     _shasum: '3386c35f454591eee58458584a6006f7bfcb3f0c',
33 silly install resolved     _resolved: 'https://registry.npmjs.org/cordova/-/cordova-4.3.0.tgz',
33 silly install resolved     _from: 'cordova@*',
33 silly install resolved     _npmVersion: '2.5.1',
33 silly install resolved     _nodeVersion: '0.10.36',
33 silly install resolved     _npmUser: { name: 'stevegill', email: 'stevengill97@gmail.com' },
33 silly install resolved     maintainers:
33 silly install resolved      [ [Object],
33 silly install resolved        [Object],
33 silly install resolved        [Object],
33 silly install resolved        [Object],
33 silly install resolved        [Object],
33 silly install resolved        [Object],
33 silly install resolved        [Object],
33 silly install resolved        [Object],
33 silly install resolved        [Object],
33 silly install resolved        [Object],
33 silly install resolved        [Object],
33 silly install resolved        [Object],
33 silly install resolved        [Object],
33 silly install resolved        [Object],
33 silly install resolved        [Object],
33 silly install resolved        [Object] ],
33 silly install resolved     dist:
33 silly install resolved      { shasum: '3386c35f454591eee58458584a6006f7bfcb3f0c',
33 silly install resolved        tarball: 'http://registry.npmjs.org/cordova/-/cordova-4.3.0.tgz' },
33 silly install resolved     directories: {},
33 silly install resolved     readme: 'ERROR: No README data found!' } ]
34 info install cordova@4.3.0 into /usr/local/lib
35 info installOne cordova@4.3.0
36 verbose installOne of cordova to /usr/local/lib not in flight; installing
37 warn locking Error: EACCES, open '/Users/markschnegg/.npm/_locks/cordova-fa12e2e096426a32.lock'
37 warn locking     at Error (native)
37 warn locking  /Users/markschnegg/.npm/_locks/cordova-fa12e2e096426a32.lock failed { [Error: EACCES, open '/Users/markschnegg/.npm/_locks/cordova-fa12e2e096426a32.lock']
37 warn locking   errno: -13,
37 warn locking   code: 'EACCES',
37 warn locking   path: '/Users/markschnegg/.npm/_locks/cordova-fa12e2e096426a32.lock' }
38 verbose stack Error: Attempt to unlock /usr/local/lib/node_modules/cordova, which hasn't been locked
38 verbose stack     at unlock (/usr/local/lib/node_modules/npm/lib/utils/locker.js:66:11)
38 verbose stack     at cb (/usr/local/lib/node_modules/npm/lib/install.js:929:5)
38 verbose stack     at /usr/local/lib/node_modules/npm/lib/install.js:933:20
38 verbose stack     at /usr/local/lib/node_modules/npm/lib/utils/locker.js:40:9
38 verbose stack     at cb (/usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:149:38)
38 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:177:38
38 verbose stack     at FSReqWrap.oncomplete (fs.js:99:15)
39 verbose cwd /Users/markschnegg
40 error Darwin 14.1.0
41 error argv "node" "/usr/local/bin/npm" "install" "-g" "cordova"
42 error node v0.12.1
43 error npm  v2.5.1
44 error Attempt to unlock /usr/local/lib/node_modules/cordova, which hasn't been locked
45 error If you need help, you may report this error at:
45 error     <http://github.com/npm/npm/issues>
46 verbose exit [ 1, true ]
```
Any help would be greatly appreciated
Thank You

Mark

**Comment by KenanY** [comment]
@wenmark Looks like this might be a permissions issue. Can you try the following?:

``` sh
$ sudo chown -R $(whoami) "$HOME/.npm"
```

**Comment by wenmark** [comment]
This worked great! Thanks!

From:  Kenan Yildirim <notifications@github.com>
Reply-To:  npm/npm 
<reply+00aa539e56799618e505cb10f4e626b7e5a5e963c4bc8d2e92cf0000000111356fb79
2a169ce03ef2ace@reply.github.com>
Date:  Thu, 02 Apr 2015 13:59:35 -0700
To:  npm/npm <npm@noreply.github.com>
Cc:  Mark Schnegg <mms@wenmark.com>
Subject:  {Spam?} {Disarmed} Re: [npm] can't install cordova on my Mac OS X
10.10 (#7840)

sudo chown -R $(whoami) "$HOME/.npm"

**Comment by ehsalazar** [comment]
Good to hear. I'll close this for now as we’re trying to clean up some old issues. We’ll be happy to reopen if necessary.
