### ISSUE TITLE
npm tries to install old version

### ISSUE THREAD

**Issue by raulggonzalez** [npm/npm#7846]
When I try to install the last version of the `justo-assert` package, I receive:
```
PS C:\Users\me> npm install -g justo-assert
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "justo-assert"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code EBADPLATFORM

npm ERR! notsup Unsupported
npm ERR! notsup Not compatible with your operating system or architecture: justo-assert@0.1.0
npm ERR! notsup Valid OS:    Linux,Mac,Windows
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\me\npm-debug.log
PS C:\Users\me>
```

The current version is `0.3.0`, but npm tries to install `0.1.0`. Why?
Right now, the `package.json` doesn't contain the `os` field, that I incorrectly configured in the `0.1.0` version.

```
PS C:\Users\me> cat C:\Users\me\npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'justo-assert' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 silly cache add args [ 'justo-assert', null ]
6 verbose cache add spec justo-assert
7 silly cache add parsed spec { raw: 'justo-assert',
7 silly cache add   scope: null,
7 silly cache add   name: null,
7 silly cache add   rawSpec: 'justo-assert',
7 silly cache add   spec: 'C:\\Users\\me\\justo-assert',
7 silly cache add   type: 'directory' }
8 verbose addLocalDirectory C:\Users\me\AppData\Roaming\npm-cache\justo-assert\0.1.0\package.tgz not in flight; packing
9 verbose tar pack [ 'C:\\Users\\me\\AppData\\Roaming\\npm-cache\\justo-assert\\0.1.0\\package.tgz',
9 verbose tar pack   'C:\\Users\\me\\justo-assert' ]
10 verbose tarball C:\Users\me\AppData\Roaming\npm-cache\justo-assert\0.1.0\package.tgz
11 verbose folder C:\Users\me\justo-assert
12 info prepublish justo-assert@0.1.0
13 verbose addLocalTarball adding from inside cache C:\Users\me\AppData\Roaming\npm-cache\justo-assert\0.1.0\package.tgz
14 silly cache afterAdd justo-assert@0.1.0
15 verbose afterAdd C:\Users\me\AppData\Roaming\npm-cache\justo-assert\0.1.0\package\package.json not in flight; writing
16 verbose afterAdd C:\Users\me\AppData\Roaming\npm-cache\justo-assert\0.1.0\package\package.json written
17 silly install resolved [ { name: 'justo-assert',
17 silly install resolved     version: '0.1.0',
17 silly install resolved     description: 'An assertion framework.',
17 silly install resolved     homepage: 'http://www.justojs.org',
17 silly install resolved     private: 'false',
17 silly install resolved     author:
17 silly install resolved      { name: 'Justo.js Development Group',
17 silly install resolved        email: 'justojs.org@outlook.com',
17 silly install resolved        url: 'www.justojs.org' },
17 silly install resolved     contributors: [ [Object] ],
17 silly install resolved     keywords: [ 'justo', 'justo.js', 'assert', 'test', 'unit test' ],
17 silly install resolved     os: [ 'Linux', 'Mac', 'Windows' ],
17 silly install resolved     bugs:
17 silly install resolved      { url: 'https://github.com/justojs/justo-assert/issues',
17 silly install resolved        email: 'justojs.org@outlook.com' },
17 silly install resolved     repository:
17 silly install resolved      { type: 'git',
17 silly install resolved        url: 'https://github.com/justojs/justo-assert.git' },
17 silly install resolved     preferGlobal: false,
17 silly install resolved     main: 'lib/index.js',
17 silly install resolved     files: [ 'lib', 'test' ],
17 silly install resolved     bin: {},
17 silly install resolved     engines: { node: '>= 0.12.0' },
17 silly install resolved     dependencies: {},
17 silly install resolved     peerDependencies: {},
17 silly install resolved     devDependencies:
17 silly install resolved      { grunt: '^0.4.5',
17 silly install resolved        'grunt-babel': '*',
17 silly install resolved        'grunt-contrib-clean': '*',
17 silly install resolved        'grunt-contrib-compress': '*',
17 silly install resolved        'grunt-contrib-concat': '*',
17 silly install resolved        'grunt-contrib-copy': '*',
17 silly install resolved        'grunt-contrib-jshint': '*',
17 silly install resolved        'grunt-contrib-uglify': '*',
17 silly install resolved        'grunt-mocha-test': '*',
17 silly install resolved        mocha: '*',
17 silly install resolved        should: '^5.2.0' },
17 silly install resolved     readme: '# justo-assert\r\n\r\nAn assertion framework.\r\n\r\nProudly developed in JavaScript (ES6) from Valencia, Spain.\r\n\r\n
## Install\r\n\r\n`npm install justo-assert` ',
17 silly install resolved     readmeFilename: 'README.md',
17 silly install resolved     _id: 'justo-assert@0.1.0',
17 silly install resolved     scripts: {},
17 silly install resolved     _shasum: '584db789b847dda128bd62e2ac2238fd75185f9d',
17 silly install resolved     _from: '..\\..\\..\\justo-assert',
17 silly install resolved     _resolved: 'file:..\\..\\..\\justo-assert' } ]
18 info install justo-assert@0.1.0 into C:\Users\me\AppData\Roaming\npm
19 info installOne justo-assert@0.1.0
20 verbose installOne of justo-assert to C:\Users\me\AppData\Roaming\npm not in flight; installing
21 verbose lock using C:\Users\me\AppData\Roaming\npm-cache\_locks\justo-assert-8122d28b6a55ebd1.lock for C:\Users\me\AppData\Roaming\npm\node_modules\justo-as
sert
22 verbose unlock done using C:\Users\me\AppData\Roaming\npm-cache\_locks\justo-assert-8122d28b6a55ebd1.lock for C:\Users\me\AppData\Roaming\npm\node_modules\j
usto-assert
23 verbose stack Error: Unsupported
23 verbose stack     at checkPlatform (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-install-checks\index.js:47:14)
23 verbose stack     at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
23 verbose stack     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
23 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:18:7
23 verbose stack     at checkEngine (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-install-checks\index.js:26:10)
23 verbose stack     at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
23 verbose stack     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
23 verbose stack     at chain (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
23 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install.js:1024:5
23 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\utils\locker.js:40:9
24 verbose pkgid justo-assert@0.1.0
25 verbose cwd C:\Users\me
26 error Windows_NT 6.1.7601
27 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "justo-assert"
28 error node v0.12.2
29 error npm  v2.7.4
30 error code EBADPLATFORM
31 error notsup Unsupported
31 error notsup Not compatible with your operating system or architecture: justo-assert@0.1.0
31 error notsup Valid OS:    Linux,Mac,Windows
31 error notsup Valid Arch:  any
31 error notsup Actual OS:   win32
31 error notsup Actual Arch: x64
32 verbose exit [ 1, true ]
PS C:\Users\me>
```

**Comment by KenanY** [comment]
@raulggonzalez 

```
7 silly cache add   spec: 'C:\\Users\\me\\justo-assert',
```

Is there a `justo-assert/` directory? Looks like `npm` is trying to install that. Perhaps this would work:

``` sh
$ npm install -g justo-assert@latest
```

**Comment by raulggonzalez** [comment]
@KenanY 

Yes, I do. I don't know why I have this directory there. I think that I first, by mistake, did install it locally. I uninstalled it and cleaned the cache, but I didn't see this. A good lesson learned for next time.

Sorry and thank you for replying as soon.
