### ISSUE TITLE
npm install error - generic error - linux

### ISSUE THREAD

**Issue by ezgcmr** [npm/npm#7854]
Please advise. thank you

```
ezgi@ubuntu:~$ sudo npm install -g appium
npm ERR! registry error parsing json
npm ERR! SyntaxError: Unexpected token <
npm ERR! <html>
npm ERR! <head><title>404 Not Found</title></head>
npm ERR! <body bgcolor="white">
npm ERR! <center><h1>404 Not Found</h1></center>
npm ERR! <hr><center>nginx</center>
npm ERR! </body>
npm ERR! </html>
npm ERR! 
npm ERR!     at Object.parse (native)
npm ERR!     at RegClient.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:274:23)
npm ERR!     at Request._callback (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:246:65)
npm ERR!     at Request.self.callback (/usr/lib/node_modules/npm/node_modules/request/request.js:236:22)
npm ERR!     at Request.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/lib/node_modules/npm/node_modules/request/request.js:1142:14)
npm ERR!     at Request.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/lib/node_modules/npm/node_modules/request/request.js:1096:12)
npm ERR!     at IncomingMessage.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:944:16
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.2.0-57-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "-g" "appium"
npm ERR! cwd /home/ezgi
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
npm ERR! type unexpected_token
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/ezgi/npm-debug.log
npm ERR! not ok code 0
```

**Comment by othiym23** [comment]
It looks like you've got a proxy between you and the primary registry:

```
npm ERR! <html>
npm ERR! <head><title>404 Not Found</title></head>
npm ERR! <body bgcolor="white">
npm ERR! <center><h1>404 Not Found</h1></center>
npm ERR! <hr><center>nginx</center>
npm ERR! </body>
npm ERR! </html>
```

Do you need to configure your proxy settings?

<https://docs.npmjs.com/misc/config#proxy>
<https://docs.npmjs.com/misc/config#https-proxy>

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
