### ISSUE TITLE
error with npm install -g ember-cli

### ISSUE THREAD

**Issue by ericsonluciano** [npm/npm#7861]
I just try to install the ember-cli in global but this give me an error. please see the log. Thank you
```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'install', '-g', 'ember-cli' ]
2 info using npm@2.6.1
3 info using node@v0.10.22
4 silly cache add args [ 'ember-cli', null ]
5 verbose cache add spec ember-cli
6 silly cache add parsed spec { raw: 'ember-cli',
6 silly cache add   scope: null,
6 silly cache add   name: 'ember-cli',
6 silly cache add   rawSpec: '',
6 silly cache add   spec: '*',
6 silly cache add   type: 'range' }
7 verbose addNamed ember-cli@*
8 silly addNamed semver.valid null
9 silly addNamed semver.validRange *
10 silly addNameRange { name: 'ember-cli', range: '*', hasData: false }
11 silly mapToRegistry name ember-cli
12 silly mapToRegistry using default registry
13 silly mapToRegistry registry https://registry.npmjs.org/
14 silly mapToRegistry uri https://registry.npmjs.org/ember-cli
15 verbose addNameRange registry:https://registry.npmjs.org/ember-cli not in flight; fetching
16 verbose request uri https://registry.npmjs.org/ember-cli
17 verbose request no auth needed
18 info attempt registry request try #1 at 16:42:15
19 verbose request id 5072ad7ceee6a6ee
20 verbose etag "3XJA107EN8CQ97UI9UGWT6MO2"
21 http request GET https://registry.npmjs.org/ember-cli
22 http 200 https://registry.npmjs.org/ember-cli
23 silly get cb [ 200,
23 silly get   { date: 'Mon, 06 Apr 2015 08:42:18 GMT',
23 silly get     server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
23 silly get     etag: '"F252KQROE5E1Q3P5CFZ7BWQMB"',
23 silly get     'content-type': 'application/json',
23 silly get     'cache-control': 'max-age=60',
23 silly get     'content-length': '190070',
23 silly get     'accept-ranges': 'bytes',
23 silly get     via: '1.1 varnish',
23 silly get     age: '0',
23 silly get     'x-served-by': 'cache-sjc3125-SJC',
23 silly get     'x-cache': 'HIT',
23 silly get     'x-cache-hits': '1',
23 silly get     'x-timer': 'S1428309738.099480,VS0,VE37',
23 silly get     vary: 'Accept',
23 silly get     'keep-alive': 'timeout=10, max=50',
23 silly get     connection: 'Keep-Alive' } ]
24 verbose get saving ember-cli to /Users/sharlonbalbalosa/.npm/registry.npmjs.org/ember-cli/.cache.json
25 silly addNameRange number 2 { name: 'ember-cli', range: '*', hasData: true }
26 silly addNameRange versions [ 'ember-cli',
26 silly addNameRange   [ '0.0.0',
26 silly addNameRange     '0.0.1',
26 silly addNameRange     '0.0.2',
26 silly addNameRange     '0.0.3',
26 silly addNameRange     '0.0.4',
26 silly addNameRange     '0.0.5',
26 silly addNameRange     '0.0.6',
26 silly addNameRange     '0.0.7',
26 silly addNameRange     '0.0.8',
26 silly addNameRange     '0.0.9',
26 silly addNameRange     '0.0.10',
26 silly addNameRange     '0.0.11',
26 silly addNameRange     '0.0.12',
26 silly addNameRange     '0.0.13',
26 silly addNameRange     '0.0.14',
26 silly addNameRange     '0.0.15',
26 silly addNameRange     '0.0.16',
26 silly addNameRange     '0.0.18',
26 silly addNameRange     '0.0.19',
26 silly addNameRange     '0.0.20',
26 silly addNameRange     '0.0.21',
26 silly addNameRange     '0.0.22',
26 silly addNameRange     '0.0.23',
26 silly addNameRange     '0.0.24',
26 silly addNameRange     '0.0.25',
26 silly addNameRange     '0.0.27',
26 silly addNameRange     '0.0.28',
26 silly addNameRange     '0.0.29',
26 silly addNameRange     '0.0.32',
26 silly addNameRange     '0.0.33',
26 silly addNameRange     '0.0.34',
26 silly addNameRange     '0.0.35',
26 silly addNameRange     '0.0.36',
26 silly addNameRange     '0.0.37',
26 silly addNameRange     '0.0.38',
26 silly addNameRange     '0.0.39',
26 silly addNameRange     '0.0.40',
26 silly addNameRange     '0.0.41',
26 silly addNameRange     '0.0.42',
26 silly addNameRange     '0.0.43',
26 silly addNameRange     '0.0.44',
26 silly addNameRange     '0.0.45',
26 silly addNameRange     '0.0.46',
26 silly addNameRange     '0.0.47',
26 silly addNameRange     '0.1.0',
26 silly addNameRange     '0.1.1',
26 silly addNameRange     '0.1.2',
26 silly addNameRange     '0.1.3',
26 silly addNameRange     '0.1.4',
26 silly addNameRange     '0.1.5',
26 silly addNameRange     '0.1.6',
26 silly addNameRange     '0.1.7',
26 silly addNameRange     '0.1.8',
26 silly addNameRange     '0.1.9',
26 silly addNameRange     '0.1.10',
26 silly addNameRange     '0.1.11',
26 silly addNameRange     '0.1.12',
26 silly addNameRange     '0.1.13',
26 silly addNameRange     '0.1.14',
26 silly addNameRange     '0.1.15',
26 silly addNameRange     '0.2.0-beta.1',
26 silly addNameRange     '0.2.0',
26 silly addNameRange     '0.2.1',
26 silly addNameRange     '0.2.2' ] ]
27 verbose addNamed ember-cli@0.2.2
28 silly addNamed semver.valid 0.2.2
29 silly addNamed semver.validRange 0.2.2
30 silly mapToRegistry name ember-cli
31 silly mapToRegistry using default registry
32 silly mapToRegistry registry https://registry.npmjs.org/
33 silly mapToRegistry uri https://registry.npmjs.org/ember-cli
34 verbose addRemoteTarball https://registry.npmjs.org/ember-cli/-/ember-cli-0.2.2.tgz not in flight; adding
35 verbose addRemoteTarball [ 'https://registry.npmjs.org/ember-cli/-/ember-cli-0.2.2.tgz',
35 verbose addRemoteTarball   '4234ed4a8c6cc17e7432c652a704841787cd3944' ]
36 info retry fetch attempt 1 at 16:42:22
37 info attempt registry request try #1 at 16:42:22
38 http fetch GET https://registry.npmjs.org/ember-cli/-/ember-cli-0.2.2.tgz
39 http fetch 200 https://registry.npmjs.org/ember-cli/-/ember-cli-0.2.2.tgz
40 silly fetchAndShaCheck shasum 4234ed4a8c6cc17e7432c652a704841787cd3944
41 verbose stack Error: shasum check failed for /var/folders/cl/x3f7zrrd32123hmkj7mygmgh0000gp/T/npm-12893-cc5f475c/registry.npmjs.org/ember-cli/-/ember-cli-0.2.2.tgz
41 verbose stack Expected: 4234ed4a8c6cc17e7432c652a704841787cd3944
41 verbose stack Actual:   6bbee74c5af5004f90a766626db6908f75e0fecc
41 verbose stack From:     https://registry.npmjs.org/ember-cli/-/ember-cli-0.2.2.tgz
41 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/sha/index.js:38:8
41 verbose stack     at ReadStream.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/sha/index.js:85:7)
41 verbose stack     at ReadStream.EventEmitter.emit (events.js:117:20)
41 verbose stack     at _stream_readable.js:920:16
41 verbose stack     at process._tickCallback (node.js:415:13)
42 verbose cwd /Users/sharlonbalbalosa
43 error Darwin 14.1.0
44 error argv "node" "/usr/local/bin/npm" "install" "-g" "ember-cli"
45 error node v0.10.22
46 error npm  v2.6.1
47 error shasum check failed for /var/folders/cl/x3f7zrrd32123hmkj7mygmgh0000gp/T/npm-12893-cc5f475c/registry.npmjs.org/ember-cli/-/ember-cli-0.2.2.tgz
47 error Expected: 4234ed4a8c6cc17e7432c652a704841787cd3944
47 error Actual:   6bbee74c5af5004f90a766626db6908f75e0fecc
47 error From:     https://registry.npmjs.org/ember-cli/-/ember-cli-0.2.2.tgz
48 error If you need help, you may report this error at:
48 error     <http://github.com/npm/npm/issues>
49 verbose exit [ 1, true ]
```

**Comment by aalasolutions** [comment]
I confirm, using MAC Yosemite, got the same issue

**Comment by othiym23** [comment]
Hmm... I'm not sure what's happening here. I just ran a check against our CDN, and all of the CDN nodes (including the one that @ericsonluciano hit) have the correct shasum for the `ember-cli@0.2.2` package tarball. Do either of you connect to the internet via a proxy?

@aalasolutions, what versions of npm and Node are you running?

@ericsonluciano you might try upgrading npm (latest is `npm@2.7.6`), and you should definitely try upgrading Node to at least the latest version of 0.10; there have been a number of important fixes to Node since 0.10.22 was released.

**Comment by aalasolutions** [comment]
@othiym23 Hmm, I was on older version, so I updated the NPM using `npm install -g npm` and it changed the version, after that I tried to download and ember-cli downloaded properly.

Later I executed command `ember new em` and it didnt end smoothly gave me error something related to packages.json file, i tried `bower install` and got the same message.

I removed the ember and installed it again, now it downloaded properly and also when I created the project it did created. BUT..

        $ ember serve
        version: 0.2.3
        Livereload failed on port 35729.  It is either in use or you do not have permission.

So Now I am trying to fix the live reload issue, as far as I remember; last time when I tried I didnt faced such issues.

**Comment by aalasolutions** [comment]
That got fixed

I executed

    $ lsof -iTCP:35729

to find which process is using the port

    COMMAND     PID  USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
    node       3128 aamir   22u  IPv6 0x9b88b34de8648a4d      0t0  TCP *:35729 (LISTEN)
    node       3128 aamir   45u  IPv6 0x9b88b34dfea6a04d      0t0  TCP localhost:35729->localhost:55083 (ESTABLISHED)
    Google    22660 aamir   94u  IPv6 0x9b88b34dfea6734d      0t0  TCP localhost:55083->localhost:35729 (ESTABLISHED)

Killed the process

    $ kill 3128;
    $ ember serve

Now it worked fine;

Thank you

**Comment by othiym23** [comment]
Closing as resolved / abandoned.
