### ISSUE TITLE
Trying to Install Gulp

### ISSUE THREAD

**Issue by KyleJayMaxwell** [npm/npm#7877]
38 warn locking Error: EACCES, open '/Users/KyleJMaxwell/.npm/_locks/gulp-709d00e5d169ceb3.lock'
38 warn locking     at Error (native)
38 warn locking  /Users/KyleJMaxwell/.npm/_locks/gulp-709d00e5d169ceb3.lock failed { [Error: EACCES, open '/Users/KyleJMaxwell/.npm/_locks/gulp-709d00e5d169ceb3.lock']
38 warn locking   errno: -13,
38 warn locking   code: 'EACCES',
38 warn locking   path: '/Users/KyleJMaxwell/.npm/_locks/gulp-709d00e5d169ceb3.lock' }
39 verbose stack Error: Attempt to unlock /usr/local/lib/node_modules/gulp, which hasn't been locked
39 verbose stack     at unlock (/usr/local/lib/node_modules/npm/lib/utils/locker.js:66:11)
39 verbose stack     at cb (/usr/local/lib/node_modules/npm/lib/install.js:1004:5)
39 verbose stack     at /usr/local/lib/node_modules/npm/lib/install.js:1008:20
39 verbose stack     at /usr/local/lib/node_modules/npm/lib/utils/locker.js:40:9
39 verbose stack     at cb (/usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:149:38)
39 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:177:38
39 verbose stack     at FSReqWrap.oncomplete (fs.js:95:15)
40 verbose cwd /Users/KyleJMaxwell/Sites/ymc
41 error Darwin 13.4.0
42 error argv "node" "/usr/local/bin/npm" "install" "--global" "gulp"
43 error node v0.12.2
44 error npm  v2.7.4
45 error Attempt to unlock /usr/local/lib/node_modules/gulp, which hasn't been locked

**Comment by KyleJayMaxwell** [comment]
Dont know how to fix it, i was having trouble with using gulp on a file earlier, i was reading and thought it might be out of date so I uninstalled it all and now am trying to reinstall what i need.
