### ISSUE TITLE
TypeError: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by kadamsa21** [npm/npm#7894]
```
Santoshs-MacBook-Pro:bin santoshkadam$ which node
/Users/santoshkadam/.nvm/v0.8.18/bin/node
Santoshs-MacBook-Pro:bin santoshkadam$ which npm
/Users/santoshkadam/.nvm/v0.8.18/bin/npm
Santoshs-MacBook-Pro:bin santoshkadam$ node --version
v0.8.18
Santoshs-MacBook-Pro:bin santoshkadam$ npm --version

util.js:538
  ctor.prototype = Object.create(superCtor.prototype, {
                                          ^
TypeError: Cannot read property 'prototype' of undefined
    at Object.exports.inherits (util.js:538:43)
    at Object.<anonymous> (/Users/santoshkadam/.nvm/v0.8.18/lib/node_modules/npm/node_modules/npmlog/node_modules/are-we-there-yet/index.js:115:6)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/Users/santoshkadam/.nvm/v0.8.18/lib/node_modules/npm/node_modules/npmlog/log.js:2:16)
    at Module._compile (module.js:449:26)
Santoshs-MacBook-Pro:bin santoshkadam$ curl -L https://www.npmjs.org/install.sh | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    51  100    51    0     0     99      0 --:--:-- --:--:-- --:--:--    99
100  6239  100  6239    0     0   3395      0  0:00:01  0:00:01 --:--:-- 3046k
tar=/usr/bin/tar
version:
bsdtar 2.8.3 - libarchive 2.8.3
install npm@latest
fetching: http://registry.npmjs.org/npm/-/npm-2.7.5.tgz

util.js:538
  ctor.prototype = Object.create(superCtor.prototype, {
                                          ^
TypeError: Cannot read property 'prototype' of undefined
    at Object.exports.inherits (util.js:538:43)
    at Object.<anonymous> (/private/var/folders/rd/cgsxrd214wxbp4t52cc8_b900000gn/T/npm.8948/package/node_modules/npmlog/node_modules/are-we-there-yet/index.js:115:6)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/private/var/folders/rd/cgsxrd214wxbp4t52cc8_b900000gn/T/npm.8948/package/node_modules/npmlog/log.js:2:16)
    at Module._compile (module.js:449:26)

util.js:538
  ctor.prototype = Object.create(superCtor.prototype, {
                                          ^
TypeError: Cannot read property 'prototype' of undefined
    at Object.exports.inherits (util.js:538:43)
    at Object.<anonymous> (/private/var/folders/rd/cgsxrd214wxbp4t52cc8_b900000gn/T/npm.8948/package/node_modules/npmlog/node_modules/are-we-there-yet/index.js:115:6)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/private/var/folders/rd/cgsxrd214wxbp4t52cc8_b900000gn/T/npm.8948/package/node_modules/npmlog/log.js:2:16)
    at Module._compile (module.js:449:26)
It failed
Santoshs-MacBook-Pro:bin santoshkadam$ sudo curl -L https://www.npmjs.org/install.sh | sh
Password:
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    51  100    51    0     0     94      0 --:--:-- --:--:-- --:--:--    94
100  6239  100  6239    0     0   3499      0  0:00:01  0:00:01 --:--:-- 6092k
tar=/usr/bin/tar
version:
bsdtar 2.8.3 - libarchive 2.8.3
install npm@latest
fetching: http://registry.npmjs.org/npm/-/npm-2.7.5.tgz

util.js:538
  ctor.prototype = Object.create(superCtor.prototype, {
                                          ^
TypeError: Cannot read property 'prototype' of undefined
    at Object.exports.inherits (util.js:538:43)
    at Object.<anonymous> (/private/var/folders/rd/cgsxrd214wxbp4t52cc8_b900000gn/T/npm.8988/package/node_modules/npmlog/node_modules/are-we-there-yet/index.js:115:6)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/private/var/folders/rd/cgsxrd214wxbp4t52cc8_b900000gn/T/npm.8988/package/node_modules/npmlog/log.js:2:16)
    at Module._compile (module.js:449:26)

util.js:538
  ctor.prototype = Object.create(superCtor.prototype, {
                                          ^
TypeError: Cannot read property 'prototype' of undefined
    at Object.exports.inherits (util.js:538:43)
    at Object.<anonymous> (/private/var/folders/rd/cgsxrd214wxbp4t52cc8_b900000gn/T/npm.8988/package/node_modules/npmlog/node_modules/are-we-there-yet/index.js:115:6)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/private/var/folders/rd/cgsxrd214wxbp4t52cc8_b900000gn/T/npm.8988/package/node_modules/npmlog/log.js:2:16)
    at Module._compile (module.js:449:26)
It failed
Santoshs-MacBook-Pro:bin santoshkadam$ 
```

**Comment by dileephell** [comment]
Update the Node version !!!

**Comment by kadamsa21** [comment]
That is not an option as of today. Since the production version runs on the node v0.8.18. I am trying to setup my work environment same as production to debug the dropped MongoDB connection issue that the application is facing.

**Comment by KenanY** [comment]
Looks like https://github.com/iarna/are-we-there-yet/issues/1, which is in `npm@2.7.6`.

**Comment by iarna** [comment]
Closing this as its fixed in `2.7.6`, which is now the latest version of npm.

**Comment by kadamsa21** [comment]
Santoshs-MacBook-Pro:bin santoshkadam$ sudo npm install -g npm@2.7.6

util.js:538
  ctor.prototype = Object.create(superCtor.prototype, {
                                          ^
TypeError: Cannot read property 'prototype' of undefined
    at Object.exports.inherits (util.js:538:43)
    at Object.<anonymous> (/Users/santoshkadam/.nvm/v0.8.18/lib/node_modules/npm/node_modules/npmlog/node_modules/are-we-there-yet/index.js:115:6)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/Users/santoshkadam/.nvm/v0.8.18/lib/node_modules/npm/node_modules/npmlog/log.js:2:16)
    at Module._compile (module.js:449:26)
Santoshs-MacBook-Pro:bin santoshkadam$ npm install -g npm@2.7.6

util.js:538
  ctor.prototype = Object.create(superCtor.prototype, {
                                          ^
TypeError: Cannot read property 'prototype' of undefined
    at Object.exports.inherits (util.js:538:43)
    at Object.<anonymous> (/Users/santoshkadam/.nvm/v0.8.18/lib/node_modules/npm/node_modules/npmlog/node_modules/are-we-there-yet/index.js:115:6)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/Users/santoshkadam/.nvm/v0.8.18/lib/node_modules/npm/node_modules/npmlog/log.js:2:16)
    at Module._compile (module.js:449:26)
Santoshs-MacBook-Pro:bin santoshkadam$

**Comment by martco** [comment]
I'm having the exact same error

**Comment by KenanY** [comment]
@martco `npm --version`?

**Comment by martco** [comment]
@KenanY 2.7.6

**Comment by skilbjo** [comment]
node -v
v0.12.1
npm -v
2.9.1

Same issue when running node-foreman, I get this error bubbling up from the http-proxy library

**Comment by hamzawaqas-10p** [comment]
node: `v0.12.2`
npm: `2.7.5`

Same issue..

```
TypeError: Cannot read property 'prototype' of undefined
    at Object.exports.inherits (util.js:634:43)
    at /private/var/www/pebble-acl/lib/builder.js:88:7
    at Object.<anonymous> (/private/var/www/pebble-acl/lib/builder.js:91:2)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/private/var/www/pebble-acl/tests/lib/builder.js:3:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /usr/local/lib/node_modules/mocha/lib/mocha.js:192:27
    at Array.forEach (native)
    at Mocha.loadFiles (/usr/local/lib/node_modules/mocha/lib/mocha.js:189:14)
    at Mocha.run (/usr/local/lib/node_modules/mocha/lib/mocha.js:422:31)
    at Object.<anonymous> (/usr/local/lib/node_modules/mocha/bin/_mocha:398:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

```

**Comment by KenanY** [comment]
@hamzawaqas-10p Your error does not appear to be coming from `npm`:

```
    at /private/var/www/pebble-acl/lib/builder.js:88:7
```

**Comment by notbrain** [comment]
Anyone figure this out? I am seeing this on an older project on running `gulp` . Used to work out of the box and now this pops up.

node 0.12.4 
npm 2.11.1 
gulp 3.8.8 or 3.9.0

**Comment by notbrain** [comment]
Found this place because running `gulp` was giving this error on an older project that needed dep updates - updating old browser-sync from 1.5.2 to 2.7.7 solved it.
