### ISSUE TITLE
"npm view" command throws error "Invalid package.json"

### ISSUE THREAD

**Issue by oacostamo** [npm/npm#7902]
Just updated to new node 0.12.2 When running command "npm view", I returns the following error:

```
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "view"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4

npm ERR! Invalid package.json

On W7 x64

Full log:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'view' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 verbose stack Error: Invalid package.json
5 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\view.js:77:30
5 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:52:40
5 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:98:49
5 verbose stack     at evalmachine.<anonymous>:263:20
5 verbose stack     at OpenReq.Req.done (C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:141:5)
5 verbose stack     at OpenReq.done (C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:61:22)
5 verbose stack     at FSReqWrap.oncomplete (evalmachine.<anonymous>:95:15)
6 verbose cwd C:\Windows\System32
7 error Windows_NT 6.1.7601
8 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "view"
9 error node v0.12.2
10 error npm  v2.7.4
11 error Invalid package.json
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
@oacostamo Does `C:\Windows\System32\package.json` exist?

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.

**Comment by oacostamo** [comment]
Hello.
I haven't used vs2015 node tools anymore because of this failure. Just switched back to vs2013, because the lack of support, so I can't confirm,  neither deny if it still occurs.
