### ISSUE TITLE
Cannot install from GitHub npm 2.7.4

### ISSUE THREAD

**Issue by SimenB** [npm/npm#7915]
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'i', 'jquery/jquery' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 verbose node symlink /usr/bin/node
5 silly cache add args [ 'jquery/jquery', null ]
6 verbose cache add spec jquery/jquery
7 silly cache add parsed spec { raw: 'jquery/jquery',
7 silly cache add   scope: null,
7 silly cache add   name: null,
7 silly cache add   rawSpec: 'jquery/jquery',
7 silly cache add   spec: 'git+ssh://git@github.com/jquery/jquery.git',
7 silly cache add   type: 'hosted',
7 silly cache add   hosted:
7 silly cache add    { type: 'github',
7 silly cache add      ssh: 'git@github.com:jquery/jquery.git',
7 silly cache add      sshUrl: 'git+ssh://git@github.com/jquery/jquery.git',
7 silly cache add      httpsUrl: 'https://github.com/jquery/jquery.git',
7 silly cache add      directUrl: 'https://raw.githubusercontent.com/jquery/jquery/master/package.json' } }
8 info maybeGithub Attempting jquery/jquery from git://github.com/jquery/jquery.git
9 verbose addRemoteGit git-github-com-jquery-jquery-git-69af2d72 not in flight; caching
10 info git [ 'clone',
10 info git   '--template=/home/testyo/.npm/_git-remotes/_templates',
10 info git   '--mirror',
10 info git   'git://github.com/jquery/jquery.git',
10 info git   '/home/testyo/.npm/_git-remotes/git-github-com-jquery-jquery-git-69af2d72' ]
11 error git clone --template=/home/testyo/.npm/_git-remotes/_templates --mirror git://github.com/jquery/jquery.git /home/testyo/.npm/_git-remotes/git-github-com-jquery-jquery-git-69af2d72
12 verbose git clone --template=/home/testyo/.npm/_git-remotes/_templates --mirror git://github.com/jquery/jquery.git /home/testyo/.npm/_git-remotes/git-github-com-jquery-jquery-git-69af2d72: Cloning into bare repository '/home/testyo/.npm/_git-remotes/git-github-com-jquery-jquery-git-69af2d72'...
12 verbose git clone --template=/home/testyo/.npm/_git-remotes/_templates --mirror git://github.com/jquery/jquery.git /home/testyo/.npm/_git-remotes/git-github-com-jquery-jquery-git-69af2d72: fatal: unable to connect to github.com:
12 verbose git clone --template=/home/testyo/.npm/_git-remotes/_templates --mirror git://github.com/jquery/jquery.git /home/testyo/.npm/_git-remotes/git-github-com-jquery-jquery-git-69af2d72: github.com[0: 192.30.252.131]: errno=Connection refused
13 info maybeGithub Couldn't clone git://github.com/jquery/jquery.git
14 info maybeGithub Now attempting jquery/jquery from git@github.com:jquery/jquery.git
15 verbose addRemoteGit git-github-com-jquery-jquery-git-680e22b0 not in flight; caching
16 info git [ 'clone',
16 info git   '--template=/home/testyo/.npm/_git-remotes/_templates',
16 info git   '--mirror',
16 info git   'git@github.com:jquery/jquery.git',
16 info git   '/home/testyo/.npm/_git-remotes/git-github-com-jquery-jquery-git-680e22b0' ]
17 verbose addRemoteGit git clone git@github.com:jquery/jquery.git
18 verbose addRemoteGit set permissions on /home/testyo/.npm/_git-remotes/git-github-com-jquery-jquery-git-680e22b0
19 verbose addRemoteGit original treeish: master
20 info git [ 'rev-list', '-n1', 'master' ]
21 silly addRemoteGit resolved treeish: 062b5267d0a3538f1f6dee3df16da536b73061ea
22 verbose stack TypeError: Cannot read property 'charAt' of undefined
22 verbose stack     at getResolved (/usr/lib/node_modules/npm/lib/cache/add-remote-git.js:357:13)
22 verbose stack     at /usr/lib/node_modules/npm/lib/cache/add-remote-git.js:220:23
22 verbose stack     at /usr/lib/node_modules/npm/lib/utils/git.js:26:8
22 verbose stack     at ChildProcess.exithandler (child_process.js:742:7)
22 verbose stack     at ChildProcess.emit (events.js:110:17)
22 verbose stack     at maybeClose (child_process.js:1015:16)
22 verbose stack     at Socket.<anonymous> (child_process.js:1183:11)
22 verbose stack     at Socket.emit (events.js:107:17)
22 verbose stack     at Pipe.close (net.js:485:12)
23 verbose cwd /home/testyo/repos/frontend-repo/code
24 error Linux 3.16.0-34-generic
25 error argv "/usr/bin/node" "/usr/bin/npm" "i" "jquery/jquery"
26 error node v0.12.2
27 error npm  v2.7.4
28 error Cannot read property 'charAt' of undefined
29 error If you need help, you may report this error at:
29 error     <https://github.com/npm/npm/issues>
30 verbose exit [ 1, true ]
```

**Comment by othiym23** [comment]
[Update](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) to the latest version of npm! It has a fix for this exact problem. Or, if you want to help verify that the new testing release of npm also fixes the problem, try `sudo npm -g install npm@next` to install the testing release.

It may be a little while until a new version of Node.js is released with a newer version of npm bundled, so you'll have to do that update independently of your Linux distribution's package management, unfortunately.

**Comment by SimenB** [comment]
@othiym23 Ah, sorry. Maybe add that to the message printed on failure? All it says is 

```
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

**Comment by othiym23** [comment]
No need for apologies! The fault is ours for letting the bug in there in the first place.

> Maybe add that to the message printed on failure?

Well, that error happens almost entirely on the client side, so we'd have to go back in time and put that error message in the version that's broken. It's a lot easier and less ontologically confusing to fix the bug and put out a new version. :bowling:

**Comment by SimenB** [comment]
I meant in general. On failure (if it's possible, only if stacktrace from within `npm` itself?), print something along "Try upgrading `npm`"
