### ISSUE TITLE
TypeError: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by kadamsa21** [npm/npm#7921]
Santoshs-MacBook-Pro:bin santoshkadam$ sudo npm install -g npm@2.7.6

util.js:538
ctor.prototype = Object.create(superCtor.prototype, {
^
TypeError: Cannot read property 'prototype' of undefined
at Object.exports.inherits (util.js:538:43)
at Object. (/Users/santoshkadam/.nvm/v0.8.18/lib/node_modules/npm/node_modules/npmlog/node_modules/are-we-there-yet/index.js:115:6)
at Module._compile (module.js:449:26)
at Object.Module._extensions..js (module.js:467:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:362:17)
at require (module.js:378:17)
at Object. (/Users/santoshkadam/.nvm/v0.8.18/lib/node_modules/npm/node_modules/npmlog/log.js:2:16)
at Module._compile (module.js:449:26)
Santoshs-MacBook-Pro:bin santoshkadam$ npm install -g npm@2.7.6

util.js:538
ctor.prototype = Object.create(superCtor.prototype, {
^
TypeError: Cannot read property 'prototype' of undefined
at Object.exports.inherits (util.js:538:43)
at Object. (/Users/santoshkadam/.nvm/v0.8.18/lib/node_modules/npm/node_modules/npmlog/node_modules/are-we-there-yet/index.js:115:6)
at Module._compile (module.js:449:26)
at Object.Module._extensions..js (module.js:467:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:362:17)
at require (module.js:378:17)
at Object. (/Users/santoshkadam/.nvm/v0.8.18/lib/node_modules/npm/node_modules/npmlog/log.js:2:16)
at Module._compile (module.js:449:26)
Santoshs-MacBook-Pro:bin santoshkadam$

**Comment by othiym23** [comment]
A couple versions of npm included a dependency that didn't work with Node 0.8. You'll want to either [upgrade Node](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-node) (which is a good idea, as 0.8.18 is well over two years old at this point, and npm is only going to support 0.8 for a limited time now that 0.12 is out), or reinstall Node using `curl -L https://www.npmjs.com/install.sh | bash` (assuming that you're going to stick with nvm, which doesn't require `sudo` for npm installs). Sorry about the confusion!

**Comment by kadamsa21** [comment]
Santoshs-MacBook-Pro:lib santoshkadam$ curl -L https://www.npmjs.com/install.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6239  100  6239    0     0   3889      0  0:00:01  0:00:01 --:--:--  3889
tar=/usr/bin/tar
version:
bsdtar 2.8.3 - libarchive 2.8.3
install npm@latest
fetching: http://registry.npmjs.org/npm/-/npm-2.7.6.tgz
unbuild npm@2.7.5
 
> npm@2.7.6 prepublish /private/var/folders/rd/cgsxrd214wxbp4t52cc8_b900000gn/T/npm.9956/package
> node bin/npm-cli.js prune --prefix=. --no-global && rimraf test/*/*/node_modules && make -j8 doc

sh: rimraf: command not found
/Users/santoshkadam/.nvm/v0.8.18/bin/npm -> /Users/santoshkadam/.nvm/v0.8.18/lib/node_modules/npm/bin/npm-cli.js
npm@2.7.6 /Users/santoshkadam/.nvm/v0.8.18/lib/node_modules/npm
It worked
Santoshs-MacBook-Pro:lib santoshkadam$ which node
/Users/santoshkadam/.nvm/v0.8.18/bin/node
Santoshs-MacBook-Pro:lib santoshkadam$ which npm
/Users/santoshkadam/.nvm/v0.8.18/bin/npm
Santoshs-MacBook-Pro:lib santoshkadam$ node --version
v0.8.18
Santoshs-MacBook-Pro:lib santoshkadam$ npm -v
2.7.6
Santoshs-MacBook-Pro:lib santoshkadam$ npm --version
2.7.6
Santoshs-MacBook-Pro:lib santoshkadam$

**Comment by othiym23** [comment]
Looks like you're set! `npm@2.7.6` is the latest stable version, and has no known issues with 0.8 aside from some [persistent, but inconsistent, test failures](https://github.com/npm/npm/issues/7842).
