### ISSUE TITLE
npm tunneling socket could not be established cause = etimedout

### ISSUE THREAD

**Issue by raheel12** [npm/npm#7925]
Hi guys I am trying to install npm with nodejs, but I am keep getting the above message. I am not using any proxy as well. 
![npm error](https://cloud.githubusercontent.com/assets/11905062/7103500/b80fea82-e05e-11e4-84d4-9dd1305dcd37.png)

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@2.5.1
3 info using node@v0.12.1
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 verbose config Skipping project config: C:\Users\Raheel/.npmrc. (matches userconfig)
6 verbose install where, deps [ 'C:\\Users\\Raheel', [ 'express', 'jade', 'pluralize' ] ]
7 verbose install where, peers [ 'C:\\Users\\Raheel', [] ]
8 info preinstall application-name@0.0.1
9 silly cache add args [ 'express@3.5.1', null ]
10 verbose cache add spec express@3.5.1
11 silly cache add args [ 'jade@*', null ]
12 verbose cache add spec jade@*
13 silly cache add parsed spec { raw: 'express@3.5.1',
13 silly cache add   scope: null,
13 silly cache add   name: 'express',
13 silly cache add   rawSpec: '3.5.1',
13 silly cache add   spec: '3.5.1',
13 silly cache add   type: 'version' }
14 verbose addNamed express@3.5.1
15 silly addNamed semver.valid 3.5.1
16 silly addNamed semver.validRange 3.5.1
17 silly mapToRegistry name express
18 silly mapToRegistry using default registry
19 silly mapToRegistry registry https://registry.npmjs.org/
20 silly mapToRegistry uri https://registry.npmjs.org/express
21 verbose addNameVersion registry:https://registry.npmjs.org/express not in flight; fetching
22 silly cache add parsed spec { raw: 'jade@*',
22 silly cache add   scope: null,
22 silly cache add   name: 'jade',
22 silly cache add   rawSpec: '*',
22 silly cache add   spec: '*',
22 silly cache add   type: 'range' }
23 verbose addNamed jade@*
24 silly addNamed semver.valid null
25 silly addNamed semver.validRange *
26 silly addNameRange { name: 'jade', range: '*', hasData: false }
27 silly mapToRegistry name jade
28 silly mapToRegistry using default registry
29 silly mapToRegistry registry https://registry.npmjs.org/
30 silly mapToRegistry uri https://registry.npmjs.org/jade
31 verbose addNameRange registry:https://registry.npmjs.org/jade not in flight; fetching
32 silly cache add args [ 'pluralize@^1.1.2', null ]
33 verbose cache add spec pluralize@^1.1.2
34 silly cache add parsed spec { raw: 'pluralize@^1.1.2',
34 silly cache add   scope: null,
34 silly cache add   name: 'pluralize',
34 silly cache add   rawSpec: '^1.1.2',
34 silly cache add   spec: '>=1.1.2 <2.0.0',
34 silly cache add   type: 'range' }
35 verbose addNamed pluralize@>=1.1.2 <2.0.0
36 silly addNamed semver.valid null
37 silly addNamed semver.validRange >=1.1.2 <2.0.0
38 silly addNameRange { name: 'pluralize', range: '>=1.1.2 <2.0.0', hasData: false }
39 silly mapToRegistry name pluralize
40 silly mapToRegistry using default registry
41 silly mapToRegistry registry https://registry.npmjs.org/
42 silly mapToRegistry uri https://registry.npmjs.org/pluralize
43 verbose addNameRange registry:https://registry.npmjs.org/pluralize not in flight; fetching
44 verbose request uri https://registry.npmjs.org/express
45 verbose request no auth needed
46 info attempt registry request try #1 at 2:40:15 PM
47 verbose request id 42d72b65b708ab7f
48 http request GET https://registry.npmjs.org/express
49 verbose request uri https://registry.npmjs.org/jade
50 verbose request no auth needed
51 info attempt registry request try #1 at 2:40:15 PM
52 http request GET https://registry.npmjs.org/jade
53 verbose request uri https://registry.npmjs.org/pluralize
54 verbose request no auth needed
55 info attempt registry request try #1 at 2:40:15 PM
56 http request GET https://registry.npmjs.org/pluralize
57 info retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=connect ETIMEDOUT
58 info retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=connect ETIMEDOUT
59 info retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=connect ETIMEDOUT
60 info attempt registry request try #2 at 2:40:47 PM
61 http request GET https://registry.npmjs.org/express
62 info attempt registry request try #2 at 2:40:47 PM
63 http request GET https://registry.npmjs.org/jade
64 info attempt registry request try #2 at 2:40:47 PM
65 http request GET https://registry.npmjs.org/pluralize
66 info retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=connect ETIMEDOUT
67 info retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=connect ETIMEDOUT
68 info retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=connect ETIMEDOUT
69 info attempt registry request try #3 at 2:42:08 PM
70 http request GET https://registry.npmjs.org/express
71 info attempt registry request try #3 at 2:42:08 PM
72 http request GET https://registry.npmjs.org/jade
73 info attempt registry request try #3 at 2:42:08 PM
74 http request GET https://registry.npmjs.org/pluralize
75 verbose stack Error: tunneling socket could not be established, cause=connect ETIMEDOUT
75 verbose stack     at ClientRequest.onError (C:\Program Files\nodejs\node_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:168:17)
75 verbose stack     at ClientRequest.g (events.js:199:16)
75 verbose stack     at ClientRequest.emit (events.js:107:17)
75 verbose stack     at Socket.socketErrorListener (_http_client.js:272:9)
75 verbose stack     at Socket.emit (events.js:107:17)
75 verbose stack     at net.js:451:14
75 verbose stack     at process._tickCallback (node.js:355:11)
76 verbose cwd C:\Users\Raheel\Documents\ali
77 error Windows_NT 6.1.7601
78 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
79 error node v0.12.1
80 error npm  v2.5.1
81 error code ECONNRESET
82 error network tunneling socket could not be established, cause=connect ETIMEDOUT
82 error network This is most likely not a problem with npm itself
82 error network and is related to network connectivity.
82 error network In most cases you are behind a proxy or have bad network settings.
82 error network
82 error network If you are behind a proxy, please make sure that the
82 error network 'proxy' config is set properly.  See: 'npm help config'
83 verbose exit [ 1, true ]
```

**Comment by raheel12** [comment]
Is there anybody who could guide me what to do please with my issue?

**Comment by smikes** [comment]
Is this still a problem for you?

There is a bad interaction between two known bugs — one in `node@>0.11` and `iojs` and the other in `npm@<2.8.2`.  This can cause ECONNRESET and ETIMEDOUT errors.  The full writeup is here: https://github.com/npm/npm/issues/7699  You can fix this problem by updating your `npm` to the latest (see below).

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
