### ISSUE TITLE
npm publish resulting in 401

### ISSUE THREAD

**Issue by sourcebits-robertbiggs** [npm/npm#7931]
I'm trying to update my npm module by publishing, however when I use `npm publish` I get the following error message:

```
$: npm publish
npm ERR! publish Failed PUT 500
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "publish" "chui-ios"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code E500

npm ERR! unexpected status code: 401 : chui-ios
```

And here's the npm-debug-log:

```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'publish' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 verbose publish [ '.' ]
5 silly cache add args [ '.', null ]
6 verbose cache add spec .
7 silly cache add parsed spec { raw: '.',
7 silly cache add   scope: null,
7 silly cache add   name: null,
7 silly cache add   rawSpec: '.',
7 silly cache add   spec: '/Users/wobba/Git/chui-ios',
7 silly cache add   type: 'directory' }
8 verbose addLocalDirectory /Users/wobba/.npm/chui-ios/1.0.1/package.tgz not in flight; packing
9 verbose tar pack [ '/Users/wobba/.npm/chui-ios/1.0.1/package.tgz',
9 verbose tar pack   '/Users/wobba/Git/chui-ios' ]
10 verbose tarball /Users/wobba/.npm/chui-ios/1.0.1/package.tgz
11 verbose folder /Users/wobba/Git/chui-ios
12 info prepublish chui-ios@1.0.1
13 verbose addLocalTarball adding from inside cache /Users/wobba/.npm/chui-ios/1.0.1/package.tgz
14 silly cache afterAdd chui-ios@1.0.1
15 verbose afterAdd /Users/wobba/.npm/chui-ios/1.0.1/package/package.json not in flight; writing
16 verbose afterAdd /Users/wobba/.npm/chui-ios/1.0.1/package/package.json written
17 silly publish { name: 'chui-ios',
17 silly publish   version: '1.0.1',
17 silly publish   description: 'A module for creating Web apps with ChocolateChip-UI',
17 silly publish   main: './index.js',
17 silly publish   bin: { 'chui-ios': './index.js' },
17 silly publish   repository: { url: 'git://github.sourcebitsllc.com/sourcebits-robertbiggs/chui-ios.git' },
17 silly publish   scripts: { test: 'echo "Error: no test specified" && exit 1' },
17 silly publish   author: { name: 'Robert Biggs' },
17 silly publish   license: 'MIT',
17 silly publish   dependencies:
17 silly publish    { cpr: '^0.4.0',
17 silly publish      mkdirp: '^0.5.0',
17 silly publish      ncp: '^2.0.0',
17 silly publish      writefile: '^0.2.8',
17 silly publish      yargs: '^3.0.4' },
17 silly publish   readme: '# chui-ios\n\nThis is a node command-line tool that enables you to create a hybrid app container for your ChocolateChip-UI app that opens in Xcode and runs on iOS. It will wrap your Web app in a <a href="https://developer.apple.com/swift/" target="_blank">Swift</a> Web view. It expects the following parameters:\n\n##Installation\n\nTo install on Mac OS X, open your terminal and type:\n\n```\nsudo npm install -g chui-ios\n```\n\nThis will make this a global command-line tool, making it available regardless of where you are.\n\n##Usage\n\nIt expects the following parameters:\n\n- proj (the name of your project)\n- username (your username on your computer)\n- chuiapp (path to an existing ChUI Web app, otherwise it will create a default html page)\n- appicons (path of icons for the hybrid path)\n\nBoth `--chuiapp` and `--appicons` are optional arguments. If you do not provide a path to a ChocolateChip-UI Web app for the `--chuiapp` argument, the Xcode project will be created with a default Web page. You can always drag and drop your ChococolateChip-UI app\'s resources to the project\'s Website folder later. Just make sure you app\'s file name is `index.html`. You will be replacing the default index.html file in the project.\n\nThe command is used as follows:\n\n    chui-ios --proj "Hamburger" --username "BongoBaby" --chuiapp /Users/bongobaby/Documents/hamburger --appicons /Users/bongobaby/Desktop/hambuger-icons\n\n\nBy default it outputs the resulting Xcode project to your desktop. If there is already a folder with the same name, the script will abort with a warning asking you to either delete the existing folder on the desktop, or change the name of the project you are trying to create. \n\nYou can add the path for the ChocolateChip-UI Web app you wish to convert into a hybrid app by dragging its folder onto the terminal with a space after the argument `--chuiapp`. This will put its contents into the `Website` folder of the hybrid app. Similarly, if you have icons, iTunes artwork and launch screens ready, you can drag the folder with them after the argument with a space: `--appicons`. If you do not provide a path for app icons, the command will create an Xcode project where the icons are missing. Xcode will alert you with warning messages about the missing icons, however this will not impede the ability to build the app and deloy to an iOS capable device for testing. \n\nIf you want to add icons through the script, make sure they are named as follows and have these resolutions/dimensions:\n\n- `AppIcon-60@2x.png` (Resolution: 120x120)\n- `AppIcon-60@3x.png` (Resolution: 180x180)\n- `AppIcon-76.png` (Resolution: 76x76)\n- `AppIcon-76@2x.png` (Resolution: 152x152)\n- `AppIcon-Small-40.png` (Resolution: 40x40)\n- `AppIcon-Small-40@2x.png` (Resolution: 80x80)\n- `AppIcon-Small-40@3x.png` (Resolution: 120x120)\n- `AppIcon.png` (Resolution: 57x57)\n- `iTunesArtwork.png` (Resolution: 512x512)\n- `iTunesArtwork@2x.png` (Resolution: 1024x1024)\n- `LaunchImage-568h@2x~iphone.png` (Resolution: 640x1136)\n- `LaunchImage-667h@2x~iphone.png` (Resolution: 750x1334)\n- `LaunchImagep-736h@3h~iphone.png` (Resolution: 1242x2208)\n- `LaunchImage@2x~iphone.png` (Resolution: 640x960)\n\nOr, if you just want to create the hybrid app immediately without the icons, you can always add them later by draging them into the Images.xcassets folder. Be aware that each icon type needs to be put into its own sub folder. It\'s a lot easier to just create the project with the requried icons so that they are in the right place, otherwise you will need to make them available inside Xcode. Please search online for tutorials about how to add icons to an existing Xcode project.\n\n\n\n',
17 silly publish   readmeFilename: 'README.md',
17 silly publish   gitHead: 'ecc584d666234a61acd68f7979fe5962bcd03f8b',
17 silly publish   _id: 'chui-ios@1.0.1',
17 silly publish   _shasum: '7d719c6aac1fa3da1a1eebce018ec45cdf3257cb',
17 silly publish   _from: '.' }
18 silly mapToRegistry name chui-ios
19 silly mapToRegistry using default registry
20 silly mapToRegistry registry https://registry.npmjs.org/
21 silly mapToRegistry uri https://registry.npmjs.org/chui-ios
22 verbose publish registryBase https://registry.npmjs.org/
23 silly publish uploading /Users/wobba/.npm/chui-ios/1.0.1/package.tgz
24 verbose request uri https://registry.npmjs.org/chui-ios
25 verbose request sending authorization for write operation
26 info attempt registry request try #1 at 5:36:41 PM
27 verbose request id e3bf1b1ceb2ec13d
28 http request PUT https://registry.npmjs.org/chui-ios
29 http 500 https://registry.npmjs.org/chui-ios
30 info retry will retry, error on last attempt: Error: unexpected status code: 401 : chui-ios
31 info attempt registry request try #2 at 5:36:52 PM
32 http request PUT https://registry.npmjs.org/chui-ios
33 http 500 https://registry.npmjs.org/chui-ios
34 info retry will retry, error on last attempt: Error: unexpected status code: 401 : chui-ios
35 info attempt registry request try #3 at 5:37:53 PM
36 http request PUT https://registry.npmjs.org/chui-ios
37 http 500 https://registry.npmjs.org/chui-ios
38 verbose headers { date: 'Mon, 13 Apr 2015 00:37:55 GMT',
38 verbose headers   server: 'Apache',
38 verbose headers   'content-type': 'application/json',
38 verbose headers   'cache-control': 'max-age=0',
38 verbose headers   'content-length': '39',
38 verbose headers   'accept-ranges': 'bytes',
38 verbose headers   via: '1.1 varnish',
38 verbose headers   'x-served-by': 'cache-lax1425-LAX',
38 verbose headers   'x-cache': 'MISS',
38 verbose headers   'x-cache-hits': '0',
38 verbose headers   'x-timer': 'S1428885473.671003,VS0,VE2285',
38 verbose headers   connection: 'close' }
39 verbose request invalidating /Users/wobba/.npm/registry.npmjs.org/chui-ios on PUT
40 error publish Failed PUT 500
41 verbose stack Error: unexpected status code: 401 : chui-ios
41 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:247:14)
41 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:170:14)
41 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:344:22)
41 verbose stack     at Request.emit (events.js:110:17)
41 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1239:14)
41 verbose stack     at Request.emit (events.js:129:20)
41 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1187:12)
41 verbose stack     at IncomingMessage.emit (events.js:129:20)
41 verbose stack     at _stream_readable.js:908:16
41 verbose stack     at process._tickCallback (node.js:355:11)
42 verbose statusCode 500
43 verbose pkgid chui-ios
44 verbose cwd /Users/wobba/Git/chui-ios
45 error Darwin 14.3.0
46 error argv "node" "/usr/local/bin/npm" "publish"
47 error node v0.12.2
48 error npm  v2.7.4
49 error code E500
50 error unexpected status code: 401 : chui-ios
51 error If you need help, you may report this error at:
51 error     <https://github.com/npm/npm/issues>
52 verbose exit [ 1, true ]
```

**Comment by othiym23** [comment]
We're working on improving the messaging coming back from the registry so that it's clearer what's going on, but:

```
npm ERR! code E500

npm ERR! unexpected status code: 401 : chui-ios
```

It looks like the registry doesn't recognize your credentials. Try running `npm login` again, and if that doesn't work, try going to www.npmjs.com, changing your password there, and then logging in again from the CLI.

**Comment by sourcebits-robertbiggs** [comment]
Thanks. Yup, that was the problem. I needed to use the npm login command first.

Just a one up. There is no info on your documentation page about `npm login`. Getting a 401, I assumed it was a login issue, but your site mentions no where that you can or need to login before using `npm publish`. Your site also fails to mention how to update an existing published module. All I could find was the basic tutorial about adding a user and then publishing. Luckily Stackoverflow had the answer about updating a module after its creation using `npm publish`, but, that was not easy to find.

My suggestion:

1. Update your docs about how to properly update an NPM module after creation.
2. Put some mention about the `npm login` command on your site, and its relation to the update process.

Hopefully you’ll never get another issue about status code 401 again.

And thank you a ton for responding in a timely manner. 

Cheers

**Comment by Pudhiyavan05** [comment]
@othiym23 Thank you much... you saving my time and make it easier...
Great one....
