### ISSUE TITLE
Inconsistent SSL expiry notification with nmpjs?

### ISSUE THREAD

**Issue by vacri** [npm/npm#7941]
My build system is getting inconsistent 'certificate expired' errors when accessing the npmjs registry. Some things download, some do not, and it's different each time. I also get the same SSL error when pulling the packages with wget or curl - most attempts work, but somewhere between 1/4 to 1/6 of attempts give the cert expired error.

This is inside a debian jessie docker container with node 0.10.36 preinstalled. Unfortunately I can't replicate this on my workstation, which suggests it's my docker environment, but I can't figure what it could be.

Buildscript error with 'npm install':
```
npm ERR! fetch failed https://registry.npmjs.org/csv-parse/-/csv-parse-0.1.0.tgz
npm ERR! Error: CERT_HAS_EXPIRED
npm ERR!     at SecurePair.<anonymous> (tls.js:1381:32)
npm ERR!     at SecurePair.emit (events.js:92:17)
npm ERR!     at SecurePair.maybeInitFinished (tls.js:980:10)
npm ERR!     at CleartextStream.read [as _read] (tls.js:472:13)
npm ERR!     at CleartextStream.Readable.read (_stream_readable.js:341:10)
npm ERR!     at EncryptedStream.write [as _write] (tls.js:369:25)
npm ERR!     at doWrite (_stream_writable.js:226:10)
npm ERR!     at writeOrBuffer (_stream_writable.js:216:5)
npm ERR!     at EncryptedStream.Writable.write (_stream_writable.js:183:11)
npm ERR!     at write (_stream_readable.js:602:24)
npm ERR!     at flow (_stream_readable.js:611:7)
npm ERR!     at Socket.pipeOnReadable (_stream_readable.js:643:5)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>
 
npm ERR! System Linux 3.13.0-48-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /app
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
```

wget inside the build container, three times in quick succession, middle one has the error
```
root@7bf069e2aeb8:~# wget https://registry.npmjs.org/readable-stream/-/readable-stream-1.0.33.tgz
converted 'https://registry.npmjs.org/readable-stream/-/readable-stream-1.0.33.tgz' (ANSI_X3.4-1968) -> 'https://registry.npmjs.org/readable-stream/-/readable-stream-1.0.33.tgz' (UTF-8)
--2015-04-14 04:00:42--  https://registry.npmjs.org/readable-stream/-/readable-stream-1.0.33.tgz
Resolving registry.npmjs.org (registry.npmjs.org)... 103.245.222.162
Connecting to registry.npmjs.org (registry.npmjs.org)|103.245.222.162|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 15414 (15K) [application/octet-stream]
Saving to: 'readable-stream-1.0.33.tgz.11'

readable-stream-1.0 100%[=====================>]  15.05K  --.-KB/s   in 0.001s 

2015-04-14 04:00:42 (21.4 MB/s) - 'readable-stream-1.0.33.tgz.11' saved [15414/15414]

root@7bf069e2aeb8:~# wget https://registry.npmjs.org/readable-stream/-/readable-stream-1.0.33.tgz
converted 'https://registry.npmjs.org/readable-stream/-/readable-stream-1.0.33.tgz' (ANSI_X3.4-1968) -> 'https://registry.npmjs.org/readable-stream/-/readable-stream-1.0.33.tgz' (UTF-8)
--2015-04-14 04:00:43--  https://registry.npmjs.org/readable-stream/-/readable-stream-1.0.33.tgz
Resolving registry.npmjs.org (registry.npmjs.org)... 103.245.222.162
Connecting to registry.npmjs.org (registry.npmjs.org)|103.245.222.162|:443... connected.
ERROR: The certificate of 'registry.npmjs.org' is not trusted.
ERROR: The certificate of 'registry.npmjs.org' has expired.
The certificate has expired

root@7bf069e2aeb8:~# wget https://registry.npmjs.org/readable-stream/-/readable-stream-1.0.33.tgz
converted 'https://registry.npmjs.org/readable-stream/-/readable-stream-1.0.33.tgz' (ANSI_X3.4-1968) -> 'https://registry.npmjs.org/readable-stream/-/readable-stream-1.0.33.tgz' (UTF-8)
--2015-04-14 04:00:44--  https://registry.npmjs.org/readable-stream/-/readable-stream-1.0.33.tgz
Resolving registry.npmjs.org (registry.npmjs.org)... 103.245.222.162
Connecting to registry.npmjs.org (registry.npmjs.org)|103.245.222.162|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 15414 (15K) [application/octet-stream]
Saving to: 'readable-stream-1.0.33.tgz.12'

readable-stream-1.0 100%[=====================>]  15.05K  --.-KB/s   in 0.001s 

2015-04-14 04:00:44 (18.5 MB/s) - 'readable-stream-1.0.33.tgz.12' saved [15414/15414]
```

curl also shows the error (not so informative, just showing another tool...)
```
root@7bf069e2aeb8:~# curl -o foo https://registry.npmjs.org/readable-stream/-/readable-stream-1.0.33.tgz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (60) SSL certificate problem: certificate has expired
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
```

The system has been fully updated, and I also updated npm (npm install -g npm) to v2.76 with no change in behaviour. I imagine that the issue is in my environment since I can't replicate it on my workstation, but for the life of me I can't figure out what it might be. Pulling files from third-party https locations doesn't trigger the problem.

Most probably there's  a race condition in my build environment, but I'm wondering if perhaps an old  cert made it's way back onto one of the NPM SSL terminators?

**Comment by othiym23** [comment]
It would be helpful in trying to track down where the problem lies if you could capture the full headers of one of these verification failures (`curl -kv` should do it). As it is, there isn't enough to go on there – we haven't made any changes to our SSL certificates recently, so I don't know why you would have started seeing this recently.

**Comment by vacri** [comment]
Sorry, othiym23, forgot about the headers, where are my manners :) I'm juggling a couple of problems at the moment. Looking at the headers in curl, there are two different certs.

unsuccessful curl:
```
root@7bf069e2aeb8:~# curl -kv -o foo https://registry.npmjs.org/readable-stream/-/readable-stream-1.0.33.tgz
* Hostname was NOT found in DNS cache
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 103.245.222.162...
* Connected to registry.npmjs.org (103.245.222.162) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
} [data not shown]
* SSLv3, TLS handshake, Server hello (2):
{ [data not shown]
* SSLv3, TLS handshake, CERT (11):
{ [data not shown]
* SSLv3, TLS handshake, Server key exchange (12):
{ [data not shown]
* SSLv3, TLS handshake, Server finished (14):
{ [data not shown]
* SSLv3, TLS handshake, Client key exchange (16):
} [data not shown]
* SSLv3, TLS change cipher, Client hello (1):
} [data not shown]
* SSLv3, TLS handshake, Finished (20):
} [data not shown]
* SSLv3, TLS change cipher, Client hello (1):
{ [data not shown]
* SSLv3, TLS handshake, Finished (20):
{ [data not shown]
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* Server certificate:
* 	 subject: C=US; ST=CA; L=San Francisco; O=Joyent, Inc.; CN=nodejs.org
* 	 start date: 2012-08-24 19:33:10 GMT
* 	 expire date: 2014-08-25 19:33:10 GMT
* 	 issuer: C=BE; O=GlobalSign nv-sa; CN=GlobalSign Organization Validation CA - G2
* 	 SSL certificate verify result: certificate has expired (10), continuing anyway.
> GET /readable-stream/-/readable-stream-1.0.33.tgz HTTP/1.1
> User-Agent: curl/7.38.0
> Host: registry.npmjs.org
> Accept: */*
> 
< HTTP/1.1 200 OK
< content-type: application/octet-stream
* Server nginx/1.4.6 (Ubuntu) is not blacklisted
< server: nginx/1.4.6 (Ubuntu)
< last-modified: Sat, 25 Oct 2014 10:14:16 GMT
< etag: "544b77f8-3c36"
< expires: Mon, 30 Mar 2015 07:24:27 GMT
< access-control-allow-origin: *
< access-control-allow-methods: GET
< Cache-Control: max-age=21600
< Content-Length: 15414
< Accept-Ranges: bytes
< Date: Tue, 14 Apr 2015 05:22:18 GMT
< Via: 1.1 varnish
< Age: 19237
< Connection: keep-alive
< X-Served-By: cache-syd1620-SYD
< X-Cache: HIT
< X-Cache-Hits: 2
< X-Timer: S1428988938.234714,VS0,VE0
< 
{ [data not shown]
100 15414  100 15414    0     0   427k      0 --:--:-- --:--:-- --:--:--  442k
* Connection #0 to host registry.npmjs.org left intact
```

successful curl:
```
root@7bf069e2aeb8:~# curl -kv -o foo https://registry.npmjs.org/readable-stream/-/readable-stream-1.0.33.tgz
* Hostname was NOT found in DNS cache
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 103.245.222.162...
* Connected to registry.npmjs.org (103.245.222.162) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
} [data not shown]
* SSLv3, TLS handshake, Server hello (2):
{ [data not shown]
* SSLv3, TLS handshake, CERT (11):
{ [data not shown]
* SSLv3, TLS handshake, Server key exchange (12):
{ [data not shown]
* SSLv3, TLS handshake, Server finished (14):
{ [data not shown]
* SSLv3, TLS handshake, Client key exchange (16):
} [data not shown]
* SSLv3, TLS change cipher, Client hello (1):
} [data not shown]
* SSLv3, TLS handshake, Finished (20):
} [data not shown]
* SSLv3, TLS change cipher, Client hello (1):
{ [data not shown]
* SSLv3, TLS handshake, Finished (20):
{ [data not shown]
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* Server certificate:
* 	 subject: businessCategory=Private Organization; serialNumber=5452409; 1.3.6.1.4.1.311.60.2.1.3=US; 1.3.6.1.4.1.311.60.2.1.2=Delaware; C=US; ST=California; L=Oakland; street=200 Frank H Ogawa Plz; O=npm, Inc.; CN=npmjs.org
* 	 start date: 2015-01-15 19:45:11 GMT
* 	 expire date: 2016-04-13 19:06:17 GMT
* 	 issuer: C=BE; O=GlobalSign nv-sa; CN=GlobalSign Extended Validation CA - SHA256 - G2
* 	 SSL certificate verify ok.
> GET /readable-stream/-/readable-stream-1.0.33.tgz HTTP/1.1
> User-Agent: curl/7.38.0
> Host: registry.npmjs.org
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Tue, 14 Apr 2015 05:22:17 GMT
* Server nginx/1.4.6 (Ubuntu) is not blacklisted
< Server: nginx/1.4.6 (Ubuntu)
< content-type: application/octet-stream
< last-modified: Sat, 25 Oct 2014 10:14:16 GMT
< etag: "544b77f8-3c36"
< expires: Mon, 30 Mar 2015 07:24:27 GMT
< access-control-allow-origin: *
< access-control-allow-methods: GET
< Cache-Control: max-age=21600
< Content-Length: 15414
< Accept-Ranges: bytes
< Via: 1.1 varnish
< Age: 19236
< X-Served-By: cache-syd1623-SYD
< X-Cache: HIT
< X-Cache-Hits: 200
< X-Timer: S1428988937.374028,VS0,VE0
< 
{ [data not shown]
100 15414  100 15414    0     0   443k      0 --:--:-- --:--:-- --:--:--  456k
* Connection #0 to host registry.npmjs.org left intact
```

**Comment by othiym23** [comment]
```
* Server certificate:
*    subject: C=US; ST=CA; L=San Francisco; O=Joyent, Inc.; CN=nodejs.org
*    start date: 2012-08-24 19:33:10 GMT
*    expire date: 2014-08-25 19:33:10 GMT
*    issuer: C=BE; O=GlobalSign nv-sa; CN=GlobalSign Organization Validation CA - G2
*    SSL certificate verify result: certificate has expired (10), continuing anyway.
```

That is definitely not npm's certificate. We're going to look into this further and see if we can figure out where in our infrastructure this problem is coming from. Are you using any kind of proxying between your CI host and the registry?

**Comment by vacri** [comment]
All of the above is done within the debian jessie docker container, running on a vanilla ubuntu docker host in an AWS VPC. No special networking done on my behalf, should be straight through to the AWS gateway

Damncabbage is having the same problem - responding confirming the issue in an IRC channel we share (but I don't know damncabbage's setup).
https://twitter.com/damncabbage/status/587854497084411905

Has perhaps an old server been reawakened and added to the load balancer?

**Comment by othiym23** [comment]
I saw @damncabbage's tweet – are you both in Australia, or at least hosting your instances in Australasia? We're checking whether this is a problem with our CDN, and if you're both in the same region, it narrows things down considerably.

**Comment by vacri** [comment]
My server is in AWS Sydney. I'm not sure of @damncabbage's server location, but Australia wouldn't be unexpected

**Comment by vacri** [comment]
Just to rule out some chaff I've mentioned above: I've run the request from some other servers in my AWS system (debian/ubuntu) and get the same error.

**Comment by damncabbage** [comment]
Confirmed; connecting from Australia (local Mac and hosted VM). Can't reproduce when connecting from a US-based VM.

**Comment by othiym23** [comment]
Thanks for the followup, @damncabbage and @vacri. We're probably going to escalate with our CDN provider now; it looks like one of their servers in Sydney might be confused.

**Comment by vacri** [comment]
@othiym23 damncabbage's confirmations are seen in Sydney, same as my AWS sources. 

My workstation in Melbourne can't replicate the issue. I have no locations elsewhere in-country to try, sorry.

**Comment by seldo** [comment]
We can reproduce in an instance spun up in Sydney. It looks like a single broken node in that POP. Escalating to CDN.

**Comment by seldo** [comment]
This issue is not visible anywhere else, e.g. SIN, Tokyo, Amsterdam, etc.. Treating as a minor (if very annoying) partial outage right now.

**Comment by seldo** [comment]
Looks like Fastly have resolved this issue; I can no longer reproduce. Feel free to reopen if you see this again.
