### ISSUE TITLE
Unable to install the npm using Netbeans 8 in Mac with Yosamite OS

### ISSUE THREAD

**Issue by pradeepippagunta** [npm/npm#7942]
```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'install' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 verbose install where, deps [ '/Users/subex/Desktop/ROCInsights',
4 verbose install   [ 'karma',
4 verbose install     'protractor',
4 verbose install     'http-server',
4 verbose install     'bower',
4 verbose install     'shelljs',
4 verbose install     'karma-junit-reporter' ] ]
5 verbose install where, peers [ '/Users/subex/Desktop/ROCInsights', [] ]
6 info preinstall angular-seed@0.0.0
7 silly cache add args [ 'http-server@^0.6.1', null ]
8 verbose cache add spec http-server@^0.6.1
9 silly cache add parsed spec { raw: 'http-server@^0.6.1',
9 silly cache add   scope: null,
9 silly cache add   name: 'http-server',
9 silly cache add   rawSpec: '^0.6.1',
9 silly cache add   spec: '>=0.6.1 <0.7.0',
9 silly cache add   type: 'range' }
10 verbose addNamed http-server@>=0.6.1 <0.7.0
11 silly addNamed semver.valid null
12 silly addNamed semver.validRange >=0.6.1 <0.7.0
13 silly addNameRange { name: 'http-server', range: '>=0.6.1 <0.7.0', hasData: false }
14 silly mapToRegistry name http-server
15 silly mapToRegistry using default registry
16 silly mapToRegistry registry http://registry.npmjs.org/
17 silly mapToRegistry uri http://registry.npmjs.org/http-server
18 verbose addNameRange registry:http://registry.npmjs.org/http-server not in flight; fetching
19 silly cache add args [ 'bower@^1.3.1', null ]
20 verbose cache add spec bower@^1.3.1
21 silly cache add parsed spec { raw: 'bower@^1.3.1',
21 silly cache add   scope: null,
21 silly cache add   name: 'bower',
21 silly cache add   rawSpec: '^1.3.1',
21 silly cache add   spec: '>=1.3.1 <2.0.0',
21 silly cache add   type: 'range' }
22 verbose addNamed bower@>=1.3.1 <2.0.0
23 silly addNamed semver.valid null
24 silly addNamed semver.validRange >=1.3.1 <2.0.0
25 silly addNameRange { name: 'bower', range: '>=1.3.1 <2.0.0', hasData: false }
26 silly mapToRegistry name bower
27 silly mapToRegistry using default registry
28 silly mapToRegistry registry http://registry.npmjs.org/
29 silly mapToRegistry uri http://registry.npmjs.org/bower
30 verbose addNameRange registry:http://registry.npmjs.org/bower not in flight; fetching
31 silly cache add args [ 'shelljs@^0.2.6', null ]
32 verbose cache add spec shelljs@^0.2.6
33 silly cache add parsed spec { raw: 'shelljs@^0.2.6',
33 silly cache add   scope: null,
33 silly cache add   name: 'shelljs',
33 silly cache add   rawSpec: '^0.2.6',
33 silly cache add   spec: '>=0.2.6 <0.3.0',
33 silly cache add   type: 'range' }
34 verbose addNamed shelljs@>=0.2.6 <0.3.0
35 silly addNamed semver.valid null
36 silly addNamed semver.validRange >=0.2.6 <0.3.0
37 silly addNameRange { name: 'shelljs', range: '>=0.2.6 <0.3.0', hasData: false }
38 silly mapToRegistry name shelljs
39 silly mapToRegistry using default registry
40 silly mapToRegistry registry http://registry.npmjs.org/
41 silly mapToRegistry uri http://registry.npmjs.org/shelljs
42 verbose addNameRange registry:http://registry.npmjs.org/shelljs not in flight; fetching
43 silly cache add args [ 'karma-junit-reporter@^0.2.2', null ]
44 verbose cache add spec karma-junit-reporter@^0.2.2
45 silly cache add parsed spec { raw: 'karma-junit-reporter@^0.2.2',
45 silly cache add   scope: null,
45 silly cache add   name: 'karma-junit-reporter',
45 silly cache add   rawSpec: '^0.2.2',
45 silly cache add   spec: '>=0.2.2 <0.3.0',
45 silly cache add   type: 'range' }
46 verbose addNamed karma-junit-reporter@>=0.2.2 <0.3.0
47 silly addNamed semver.valid null
48 silly addNamed semver.validRange >=0.2.2 <0.3.0
49 silly addNameRange { name: 'karma-junit-reporter',
49 silly addNameRange   range: '>=0.2.2 <0.3.0',
49 silly addNameRange   hasData: false }
50 silly mapToRegistry name karma-junit-reporter
51 silly mapToRegistry using default registry
52 silly mapToRegistry registry http://registry.npmjs.org/
53 silly mapToRegistry uri http://registry.npmjs.org/karma-junit-reporter
54 verbose addNameRange registry:http://registry.npmjs.org/karma-junit-reporter not in flight; fetching
55 silly cache add args [ 'karma@~0.10', null ]
56 verbose cache add spec karma@~0.10
57 silly cache add parsed spec { raw: 'karma@~0.10',
57 silly cache add   scope: null,
57 silly cache add   name: 'karma',
57 silly cache add   rawSpec: '~0.10',
57 silly cache add   spec: '>=0.10.0 <0.11.0',
57 silly cache add   type: 'range' }
58 verbose addNamed karma@>=0.10.0 <0.11.0
59 silly addNamed semver.valid null
60 silly addNamed semver.validRange >=0.10.0 <0.11.0
61 silly addNameRange { name: 'karma', range: '>=0.10.0 <0.11.0', hasData: false }
62 silly mapToRegistry name karma
63 silly mapToRegistry using default registry
64 silly mapToRegistry registry http://registry.npmjs.org/
65 silly mapToRegistry uri http://registry.npmjs.org/karma
66 verbose addNameRange registry:http://registry.npmjs.org/karma not in flight; fetching
67 silly cache add args [ 'protractor@^1.1.1', null ]
68 verbose cache add spec protractor@^1.1.1
69 silly cache add parsed spec { raw: 'protractor@^1.1.1',
69 silly cache add   scope: null,
69 silly cache add   name: 'protractor',
69 silly cache add   rawSpec: '^1.1.1',
69 silly cache add   spec: '>=1.1.1 <2.0.0',
69 silly cache add   type: 'range' }
70 verbose addNamed protractor@>=1.1.1 <2.0.0
71 silly addNamed semver.valid null
72 silly addNamed semver.validRange >=1.1.1 <2.0.0
73 silly addNameRange { name: 'protractor', range: '>=1.1.1 <2.0.0', hasData: false }
74 silly mapToRegistry name protractor
75 silly mapToRegistry using default registry
76 silly mapToRegistry registry http://registry.npmjs.org/
77 silly mapToRegistry uri http://registry.npmjs.org/protractor
78 verbose addNameRange registry:http://registry.npmjs.org/protractor not in flight; fetching
79 verbose request uri http://registry.npmjs.org/http-server
80 verbose request no auth needed
81 info attempt registry request try #1 at 1:03:01 PM
82 verbose request id 9bb4a1bd7b56d6aa
83 http request GET http://registry.npmjs.org/http-server
84 verbose request uri http://registry.npmjs.org/bower
85 verbose request no auth needed
86 info attempt registry request try #1 at 1:03:01 PM
87 http request GET http://registry.npmjs.org/bower
88 verbose request uri http://registry.npmjs.org/shelljs
89 verbose request no auth needed
90 info attempt registry request try #1 at 1:03:01 PM
91 http request GET http://registry.npmjs.org/shelljs
92 verbose request uri http://registry.npmjs.org/karma-junit-reporter
93 verbose request no auth needed
94 info attempt registry request try #1 at 1:03:01 PM
95 http request GET http://registry.npmjs.org/karma-junit-reporter
96 verbose request uri http://registry.npmjs.org/karma
97 verbose request no auth needed
98 info attempt registry request try #1 at 1:03:01 PM
99 http request GET http://registry.npmjs.org/karma
100 verbose request uri http://registry.npmjs.org/protractor
101 verbose request no auth needed
102 info attempt registry request try #1 at 1:03:01 PM
103 http request GET http://registry.npmjs.org/protractor
104 http 404 http://registry.npmjs.org/karma
105 verbose bad json <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
105 verbose bad json <html xmlns="http://www.w3.org/1999/xhtml">
105 verbose bad json <head>
105 verbose bad json <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
105 verbose bad json <title>404 - File or directory not found.</title>
105 verbose bad json <style type="text/css">
105 verbose bad json <!--
105 verbose bad json body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
105 verbose bad json fieldset{padding:0 15px 10px 15px;}
105 verbose bad json h1{font-size:2.4em;margin:0;color:#FFF;}
105 verbose bad json h2{font-size:1.7em;margin:0;color:#CC0000;}
105 verbose bad json h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;}
105 verbose bad json #header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
105 verbose bad json background-color:#555555;}
105 verbose bad json #content{margin:0 0 0 2%;position:relative;}
105 verbose bad json .content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
105 verbose bad json -->
105 verbose bad json </style>
105 verbose bad json </head>
105 verbose bad json <body>
105 verbose bad json <div id="header"><h1>Server Error</h1></div>
105 verbose bad json <div id="content">
105 verbose bad json  <div class="content-container"><fieldset>
105 verbose bad json   <h2>404 - File or directory not found.</h2>
105 verbose bad json   <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
105 verbose bad json  </fieldset></div>
105 verbose bad json </div>
105 verbose bad json </body>
105 verbose bad json </html>
106 error registry error parsing json
107 verbose headers { 'content-type': 'text/html',
107 verbose headers   server: 'Microsoft-IIS/8.5',
107 verbose headers   'x-powered-by': 'ASP.NET',
107 verbose headers   date: 'Tue, 14 Apr 2015 07:32:58 GMT',
107 verbose headers   'content-length': '1245' }
108 silly get cb [ 404,
108 silly get   { 'content-type': 'text/html',
108 silly get     server: 'Microsoft-IIS/8.5',
108 silly get     'x-powered-by': 'ASP.NET',
108 silly get     date: 'Tue, 14 Apr 2015 07:32:58 GMT',
108 silly get     'content-length': '1245' } ]
109 http 404 http://registry.npmjs.org/http-server
110 verbose bad json <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
110 verbose bad json <html xmlns="http://www.w3.org/1999/xhtml">
110 verbose bad json <head>
110 verbose bad json <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
110 verbose bad json <title>404 - File or directory not found.</title>
110 verbose bad json <style type="text/css">
110 verbose bad json <!--
110 verbose bad json body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
110 verbose bad json fieldset{padding:0 15px 10px 15px;}
110 verbose bad json h1{font-size:2.4em;margin:0;color:#FFF;}
110 verbose bad json h2{font-size:1.7em;margin:0;color:#CC0000;}
110 verbose bad json h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;}
110 verbose bad json #header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
110 verbose bad json background-color:#555555;}
110 verbose bad json #content{margin:0 0 0 2%;position:relative;}
110 verbose bad json .content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
110 verbose bad json -->
110 verbose bad json </style>
110 verbose bad json </head>
110 verbose bad json <body>
110 verbose bad json <div id="header"><h1>Server Error</h1></div>
110 verbose bad json <div id="content">
110 verbose bad json  <div class="content-container"><fieldset>
110 verbose bad json   <h2>404 - File or directory not found.</h2>
110 verbose bad json   <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
110 verbose bad json  </fieldset></div>
110 verbose bad json </div>
110 verbose bad json </body>
110 verbose bad json </html>
111 error registry error parsing json
112 verbose headers { 'content-type': 'text/html',
112 verbose headers   server: 'Microsoft-IIS/8.5',
112 verbose headers   'x-powered-by': 'ASP.NET',
112 verbose headers   date: 'Tue, 14 Apr 2015 07:32:58 GMT',
112 verbose headers   'content-length': '1245' }
113 silly get cb [ 404,
113 silly get   { 'content-type': 'text/html',
113 silly get     server: 'Microsoft-IIS/8.5',
113 silly get     'x-powered-by': 'ASP.NET',
113 silly get     date: 'Tue, 14 Apr 2015 07:32:58 GMT',
113 silly get     'content-length': '1245' } ]
114 http 404 http://registry.npmjs.org/shelljs
115 verbose bad json <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
115 verbose bad json <html xmlns="http://www.w3.org/1999/xhtml">
115 verbose bad json <head>
115 verbose bad json <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
115 verbose bad json <title>404 - File or directory not found.</title>
115 verbose bad json <style type="text/css">
115 verbose bad json <!--
115 verbose bad json body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
115 verbose bad json fieldset{padding:0 15px 10px 15px;}
115 verbose bad json h1{font-size:2.4em;margin:0;color:#FFF;}
115 verbose bad json h2{font-size:1.7em;margin:0;color:#CC0000;}
115 verbose bad json h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;}
115 verbose bad json #header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
115 verbose bad json background-color:#555555;}
115 verbose bad json #content{margin:0 0 0 2%;position:relative;}
115 verbose bad json .content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
115 verbose bad json -->
115 verbose bad json </style>
115 verbose bad json </head>
115 verbose bad json <body>
115 verbose bad json <div id="header"><h1>Server Error</h1></div>
115 verbose bad json <div id="content">
115 verbose bad json  <div class="content-container"><fieldset>
115 verbose bad json   <h2>404 - File or directory not found.</h2>
115 verbose bad json   <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
115 verbose bad json  </fieldset></div>
115 verbose bad json </div>
115 verbose bad json </body>
115 verbose bad json </html>
116 error registry error parsing json
117 verbose headers { 'content-type': 'text/html',
117 verbose headers   server: 'Microsoft-IIS/8.5',
117 verbose headers   'x-powered-by': 'ASP.NET',
117 verbose headers   date: 'Tue, 14 Apr 2015 07:32:58 GMT',
117 verbose headers   'content-length': '1245' }
118 silly get cb [ 404,
118 silly get   { 'content-type': 'text/html',
118 silly get     server: 'Microsoft-IIS/8.5',
118 silly get     'x-powered-by': 'ASP.NET',
118 silly get     date: 'Tue, 14 Apr 2015 07:32:58 GMT',
118 silly get     'content-length': '1245' } ]
119 http 404 http://registry.npmjs.org/protractor
120 verbose bad json <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
120 verbose bad json <html xmlns="http://www.w3.org/1999/xhtml">
120 verbose bad json <head>
120 verbose bad json <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
120 verbose bad json <title>404 - File or directory not found.</title>
120 verbose bad json <style type="text/css">
120 verbose bad json <!--
120 verbose bad json body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
120 verbose bad json fieldset{padding:0 15px 10px 15px;}
120 verbose bad json h1{font-size:2.4em;margin:0;color:#FFF;}
120 verbose bad json h2{font-size:1.7em;margin:0;color:#CC0000;}
120 verbose bad json h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;}
120 verbose bad json #header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
120 verbose bad json background-color:#555555;}
120 verbose bad json #content{margin:0 0 0 2%;position:relative;}
120 verbose bad json .content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
120 verbose bad json -->
120 verbose bad json </style>
120 verbose bad json </head>
120 verbose bad json <body>
120 verbose bad json <div id="header"><h1>Server Error</h1></div>
120 verbose bad json <div id="content">
120 verbose bad json  <div class="content-container"><fieldset>
120 verbose bad json   <h2>404 - File or directory not found.</h2>
120 verbose bad json   <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
120 verbose bad json  </fieldset></div>
120 verbose bad json </div>
120 verbose bad json </body>
120 verbose bad json </html>
121 error registry error parsing json
122 verbose headers { 'content-type': 'text/html',
122 verbose headers   server: 'Microsoft-IIS/8.5',
122 verbose headers   'x-powered-by': 'ASP.NET',
122 verbose headers   date: 'Tue, 14 Apr 2015 07:32:58 GMT',
122 verbose headers   'content-length': '1245' }
123 silly get cb [ 404,
123 silly get   { 'content-type': 'text/html',
123 silly get     server: 'Microsoft-IIS/8.5',
123 silly get     'x-powered-by': 'ASP.NET',
123 silly get     date: 'Tue, 14 Apr 2015 07:32:58 GMT',
123 silly get     'content-length': '1245' } ]
124 http 404 http://registry.npmjs.org/bower
125 verbose bad json <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
125 verbose bad json <html xmlns="http://www.w3.org/1999/xhtml">
125 verbose bad json <head>
125 verbose bad json <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
125 verbose bad json <title>404 - File or directory not found.</title>
125 verbose bad json <style type="text/css">
125 verbose bad json <!--
125 verbose bad json body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
125 verbose bad json fieldset{padding:0 15px 10px 15px;}
125 verbose bad json h1{font-size:2.4em;margin:0;color:#FFF;}
125 verbose bad json h2{font-size:1.7em;margin:0;color:#CC0000;}
125 verbose bad json h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;}
125 verbose bad json #header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
125 verbose bad json background-color:#555555;}
125 verbose bad json #content{margin:0 0 0 2%;position:relative;}
125 verbose bad json .content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
125 verbose bad json -->
125 verbose bad json </style>
125 verbose bad json </head>
125 verbose bad json <body>
125 verbose bad json <div id="header"><h1>Server Error</h1></div>
125 verbose bad json <div id="content">
125 verbose bad json  <div class="content-container"><fieldset>
125 verbose bad json   <h2>404 - File or directory not found.</h2>
125 verbose bad json   <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
125 verbose bad json  </fieldset></div>
125 verbose bad json </div>
125 verbose bad json </body>
125 verbose bad json </html>
126 error registry error parsing json
127 verbose headers { 'content-type': 'text/html',
127 verbose headers   server: 'Microsoft-IIS/8.5',
127 verbose headers   'x-powered-by': 'ASP.NET',
127 verbose headers   date: 'Tue, 14 Apr 2015 07:32:58 GMT',
127 verbose headers   'content-length': '1245' }
128 silly get cb [ 404,
128 silly get   { 'content-type': 'text/html',
128 silly get     server: 'Microsoft-IIS/8.5',
128 silly get     'x-powered-by': 'ASP.NET',
128 silly get     date: 'Tue, 14 Apr 2015 07:32:58 GMT',
128 silly get     'content-length': '1245' } ]
129 http 404 http://registry.npmjs.org/karma-junit-reporter
130 verbose bad json <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
130 verbose bad json <html xmlns="http://www.w3.org/1999/xhtml">
130 verbose bad json <head>
130 verbose bad json <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
130 verbose bad json <title>404 - File or directory not found.</title>
130 verbose bad json <style type="text/css">
130 verbose bad json <!--
130 verbose bad json body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
130 verbose bad json fieldset{padding:0 15px 10px 15px;}
130 verbose bad json h1{font-size:2.4em;margin:0;color:#FFF;}
130 verbose bad json h2{font-size:1.7em;margin:0;color:#CC0000;}
130 verbose bad json h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;}
130 verbose bad json #header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
130 verbose bad json background-color:#555555;}
130 verbose bad json #content{margin:0 0 0 2%;position:relative;}
130 verbose bad json .content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
130 verbose bad json -->
130 verbose bad json </style>
130 verbose bad json </head>
130 verbose bad json <body>
130 verbose bad json <div id="header"><h1>Server Error</h1></div>
130 verbose bad json <div id="content">
130 verbose bad json  <div class="content-container"><fieldset>
130 verbose bad json   <h2>404 - File or directory not found.</h2>
130 verbose bad json   <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
130 verbose bad json  </fieldset></div>
130 verbose bad json </div>
130 verbose bad json </body>
130 verbose bad json </html>
131 error registry error parsing json
132 verbose headers { 'content-type': 'text/html',
132 verbose headers   server: 'Microsoft-IIS/8.5',
132 verbose headers   'x-powered-by': 'ASP.NET',
132 verbose headers   date: 'Tue, 14 Apr 2015 07:32:58 GMT',
132 verbose headers   'content-length': '1245' }
133 silly get cb [ 404,
133 silly get   { 'content-type': 'text/html',
133 silly get     server: 'Microsoft-IIS/8.5',
133 silly get     'x-powered-by': 'ASP.NET',
133 silly get     date: 'Tue, 14 Apr 2015 07:32:58 GMT',
133 silly get     'content-length': '1245' } ]
134 verbose stack SyntaxError: Unexpected token <
134 verbose stack <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
134 verbose stack <html xmlns="http://www.w3.org/1999/xhtml">
134 verbose stack <head>
134 verbose stack <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
134 verbose stack <title>404 - File or directory not found.</title>
134 verbose stack <style type="text/css">
134 verbose stack <!--
134 verbose stack body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
134 verbose stack fieldset{padding:0 15px 10px 15px;}
134 verbose stack h1{font-size:2.4em;margin:0;color:#FFF;}
134 verbose stack h2{font-size:1.7em;margin:0;color:#CC0000;}
134 verbose stack h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;}
134 verbose stack #header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
134 verbose stack background-color:#555555;}
134 verbose stack #content{margin:0 0 0 2%;position:relative;}
134 verbose stack .content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
134 verbose stack -->
134 verbose stack </style>
134 verbose stack </head>
134 verbose stack <body>
134 verbose stack <div id="header"><h1>Server Error</h1></div>
134 verbose stack <div id="content">
134 verbose stack  <div class="content-container"><fieldset>
134 verbose stack   <h2>404 - File or directory not found.</h2>
134 verbose stack   <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
134 verbose stack  </fieldset></div>
134 verbose stack </div>
134 verbose stack </body>
134 verbose stack </html>
134 verbose stack
134 verbose stack     at Object.parse (native)
134 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:197:23)
134 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:170:14)
134 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:344:22)
134 verbose stack     at Request.emit (events.js:110:17)
134 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1239:14)
134 verbose stack     at Request.emit (events.js:129:20)
134 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1187:12)
134 verbose stack     at IncomingMessage.emit (events.js:129:20)
134 verbose stack     at _stream_readable.js:908:16
135 verbose cwd /Users/subex/Desktop/ROCInsights
136 error Darwin 14.1.0
137 error argv "node" "/usr/local/bin/npm" "install"
138 error node v0.12.2
139 error npm  v2.7.4
140 error Unexpected token <
140 error <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
140 error <html xmlns="http://www.w3.org/1999/xhtml">
140 error <head>
140 error <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
140 error <title>404 - File or directory not found.</title>
140 error <style type="text/css">
140 error <!--
140 error body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
140 error fieldset{padding:0 15px 10px 15px;}
140 error h1{font-size:2.4em;margin:0;color:#FFF;}
140 error h2{font-size:1.7em;margin:0;color:#CC0000;}
140 error h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;}
140 error #header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
140 error background-color:#555555;}
140 error #content{margin:0 0 0 2%;position:relative;}
140 error .content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
140 error -->
140 error </style>
140 error </head>
140 error <body>
140 error <div id="header"><h1>Server Error</h1></div>
140 error <div id="content">
140 error  <div class="content-container"><fieldset>
140 error   <h2>404 - File or directory not found.</h2>
140 error   <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
140 error  </fieldset></div>
140 error </div>
140 error </body>
140 error </html>
141 error If you need help, you may report this error at:
141 error     <https://github.com/npm/npm/issues>
142 verbose exit [ 1, true ]
 ```

**Comment by KenanY** [comment]
Hmm, reminds me of https://github.com/npm/npm/issues/7731.

**Comment by iarna** [comment]
@KenanY It does, both seem to be proxy issues, as that's not our 404 page.

**Comment by pradeepippagunta** [comment]
Please help me out how to resolve this issue.
The project is showing as "This project uses Node.JS modules, but they are not installed."
but node.js and npm was installed you can see the versions in above log also.

Please check the log for related info.

npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4

npm ERR! Unexpected token <
npm ERR! <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
npm ERR! <html xmlns="http://www.w3.org/1999/xhtml">
npm ERR! <head>
npm ERR! <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
npm ERR! <title>404 - File or directory not found.</title>
npm ERR! <style type="text/css">
npm ERR! 
npm ERR! </style>
npm ERR! </head>
npm ERR! <body>
npm ERR! <div id="header"><h1>Server Error</h1></div>
npm ERR! <div id="content">
npm ERR!  <div class="content-container"><fieldset>
npm ERR!   <h2>404 - File or directory not found.</h2>
npm ERR!   <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
npm ERR!  </fieldset></div>
npm ERR! </div>
npm ERR! </body>
npm ERR! </html>
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/subex/Desktop/ROCInsights/npm-debug.log

**Comment by smikes** [comment]
Is this still a problem for you?

Could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

There have been a lot of improvements to npm -- especially involving git dependencies -- since 2.7. Can you try updating your npm installation?

There is a bad interaction between two known bugs — one in `node@>0.11` and `iojs` and the other in `npm@<2.8.2`.  This can cause ECONNRESET and ETIMEDOUT errors.  The full writeup is here: https://github.com/npm/npm/issues/7699  You can fix this problem by updating your `npm` to the latest (see below).

To update npm, run `sudo npm -g install npm@latest`.

If you are using `npm` in a Travis CI environment, you can tell Travis to always run with the latest `npm`.  See here for an example .travis.yml file that runs with the latest npm: https://github.com/reid/node-jslint/blob/master/.travis.yml

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
