### ISSUE TITLE
problems installing ember-cli on windows 

### ISSUE THREAD

**Issue by iamalex2** [npm/npm#7960]
cannot get 'ember serve' to work
had to download previous version of node just to get it to load properly V0.10.38
loaded ok , then loaded bower install, npm install which loaded ok.
But 'ember serve'

```
$ ember serve
version: 0.1.12
Cannot find module './data/c:\code\frontend\server\mocks\attachment'
Error: Cannot find module './data/c:\code\frontend\server\mocks\attachment'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at module.exports (c:\code\frontend\server\defaultMock.js:6:20)
    at Object.<anonymous> (c:\code\frontend\server\mocks\attachment.js:4:43)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
```

can someone help on getting installed on windows.

thanks.

**Comment by KenanY** [comment]
@iamalex2 Is this an issue with the `npm` CLI? Is `c:\code\frontend\` your own codebase? Looks to me like the error is there, not with `npm`.

**Comment by iamalex2** [comment]
frontend is our codebase, yes.  Any suggestions?

**Comment by iamalex2** [comment]
I'm new to ember-cli and just trying to get it set up on windows machine, most others have mac setup.

**Comment by KenanY** [comment]
@iamalex2 

```
Cannot find module './data/c:\code\frontend\server\mocks\attachment'
```

There's no `c:\` drive in any `data/` folder, of course :), it's at the root of your hard drive, so looks like there's some bad path concatenation going on in `c:\code\frontend\server\defaultMock.js` I think.

**Comment by iamalex2** [comment]
thanks for your help

**Comment by emanuellimeira** [comment]
My problem is diferent I want to install in my machine but ember always got error. Someone can help me?

<code><pre>
elc@EMANUELLIMEIRA ~/emberteste
$ ember new app
module.js:338
    throw err;
          ^
Error: Cannot find module 'resolve'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (c:\Users\elc\AppData\Roaming\npm\node_modules\ember-c
li\bin\ember:7:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)

</pre></code>

**Comment by KenanY** [comment]
@emanuellimeira Looks like `ember-cli` is missing a dependency? Maybe try reinstalling it? Your issue seems unrelated to OP's.

**Comment by smikes** [comment]
@iamalex2  Can this issue now be closed?

@emanuellimeira Could you please create a new issue so we can keep them separate?  I think that what you are seeing springs from a different cause than OP's issue.

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by othiym23** [comment]
Closing as resolved.
