### ISSUE TITLE
Object.keys called on non-object still not fixed

### ISSUE THREAD

**Issue by yahyaKacem** [npm/npm#7964]
I keep getting this error when trying to install with npm, command tried:

```
npm install -g gulp
npm install -g bower
npm install -g karma-cli
```

Or just `npm install` for project local dependencies I get the same error npm_debug.log file:

```
0 info it worked if it ends with ok
1 verbose cli [ '/home/yahya/.nvm/versions/node/v0.12.2/bin/node',
1 verbose cli   '/home/yahya/.nvm/versions/node/v0.12.2/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'karma-cli' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 silly cache add args [ 'karma-cli', null ]
5 verbose cache add spec karma-cli
6 silly cache add parsed spec { raw: 'karma-cli',
6 silly cache add   scope: null,
6 silly cache add   name: 'karma-cli',
6 silly cache add   rawSpec: '',
6 silly cache add   spec: '*',
6 silly cache add   type: 'range' }
7 verbose addNamed karma-cli@*
8 silly addNamed semver.valid null
9 silly addNamed semver.validRange *
10 silly addNameRange { name: 'karma-cli', range: '*', hasData: false }
11 silly mapToRegistry name karma-cli
12 silly mapToRegistry using default registry
13 silly mapToRegistry registry https://registry.npmjs.org/
14 silly mapToRegistry uri https://registry.npmjs.org/karma-cli
15 verbose addNameRange registry:https://registry.npmjs.org/karma-cli not in flight; fetching
16 verbose request uri https://registry.npmjs.org/karma-cli
17 verbose request no auth needed
18 info attempt registry request try #1 at 4:24:18 PM
19 verbose request id 037332f249131ebc
20 http request GET https://registry.npmjs.org/karma-cli
21 http 200 https://registry.npmjs.org/karma-cli
22 silly get cb [ 200,
22 silly get   { date: 'Wed, 15 Apr 2015 15:24:18 GMT',
22 silly get     server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
22 silly get     etag: '"2MUL3QTCNLCIC861L5ENX5IQI"',
22 silly get     'content-type': 'application/json',
22 silly get     'cache-control': 'max-age=60',
22 silly get     'content-length': '5965',
22 silly get     'accept-ranges': 'bytes',
22 silly get     via: '1.1 varnish',
22 silly get     age: '54',
22 silly get     'x-served-by': 'cache-fra1244-FRA',
22 silly get     'x-cache': 'HIT',
22 silly get     'x-cache-hits': '2',
22 silly get     'x-timer': 'S1429111458.791934,VS0,VE0',
22 silly get     vary: 'Accept',
22 silly get     'keep-alive': 'timeout=10, max=50',
22 silly get     connection: 'Keep-Alive' } ]
23 verbose get saving karma-cli to /home/yahya/.npm/registry.npmjs.org/karma-cli/.cache.json
24 silly addNameRange number 2 { name: 'karma-cli', range: '*', hasData: true }
25 silly addNameRange versions [ 'karma-cli', [ '0.0.1', '0.0.2', '0.0.3', '0.0.4' ] ]
26 verbose addNamed karma-cli@0.0.4
27 silly addNamed semver.valid 0.0.4
28 silly addNamed semver.validRange 0.0.4
29 silly mapToRegistry name karma-cli
30 silly mapToRegistry using default registry
31 silly mapToRegistry registry https://registry.npmjs.org/
32 silly mapToRegistry uri https://registry.npmjs.org/karma-cli
33 verbose addRemoteTarball https://registry.npmjs.org/karma-cli/-/karma-cli-0.0.4.tgz not in flight; adding
34 verbose addRemoteTarball [ 'https://registry.npmjs.org/karma-cli/-/karma-cli-0.0.4.tgz',
34 verbose addRemoteTarball   '1840a6a2545754bb02100f09229cdd9963a6cf68' ]
35 info retry fetch attempt 1 at 4:24:18 PM
36 info attempt registry request try #1 at 4:24:18 PM
37 http fetch GET https://registry.npmjs.org/karma-cli/-/karma-cli-0.0.4.tgz
38 http fetch 200 https://registry.npmjs.org/karma-cli/-/karma-cli-0.0.4.tgz
39 silly fetchAndShaCheck shasum 1840a6a2545754bb02100f09229cdd9963a6cf68
40 verbose addTmpTarball /tmp/npm-30036-a6ca6966/registry.npmjs.org/karma-cli/-/karma-cli-0.0.4.tgz not in flight; adding
41 verbose addTmpTarball already have metadata; skipping unpack for karma-cli@0.0.4
42 silly cache afterAdd karma-cli@0.0.4
43 verbose afterAdd /home/yahya/.npm/karma-cli/0.0.4/package/package.json not in flight; writing
44 verbose afterAdd /home/yahya/.npm/karma-cli/0.0.4/package/package.json written
45 silly install resolved [ { name: 'karma-cli',
45 silly install resolved     description: 'The Karma command line interface.',
45 silly install resolved     homepage: 'http://karma-runner.github.io/',
45 silly install resolved     repository:
45 silly install resolved      { type: 'git',
45 silly install resolved        url: 'git://github.com/karma-runner/karma-cli.git' },
45 silly install resolved     bugs: { url: 'https://github.com/karma-runner/karma-cli/issues' },
45 silly install resolved     keywords:
45 silly install resolved      [ 'karma',
45 silly install resolved        'spectacular',
45 silly install resolved        'runner',
45 silly install resolved        'karma',
45 silly install resolved        'js',
45 silly install resolved        'javascript',
45 silly install resolved        'testing',
45 silly install resolved        'test',
45 silly install resolved        'remote',
45 silly install resolved        'execution' ],
45 silly install resolved     author: { name: 'Vojta Jína', email: 'vojta.jina@gmail.com' },
45 silly install resolved     contributors: [ [Object] ],
45 silly install resolved     dependencies: { resolve: '~0.5.1' },
45 silly install resolved     peerDependencies: {},
45 silly install resolved     devDependencies:
45 silly install resolved      { grunt: '~0.4.1',
45 silly install resolved        'grunt-contrib-jshint': '~0.7.2',
45 silly install resolved        'grunt-coffeelint': '0.0.7',
45 silly install resolved        'grunt-bump': '0.0.11',
45 silly install resolved        'grunt-npm': '0.0.2',
45 silly install resolved        'grunt-auto-release': '0.0.4',
45 silly install resolved        'grunt-conventional-changelog': '~1.0.0' },
45 silly install resolved     preferGlobal: true,
45 silly install resolved     bin: { karma: './bin/karma' },
45 silly install resolved     engines: { node: '~0.8 || ~0.10' },
45 silly install resolved     version: '0.0.4',
45 silly install resolved     _id: 'karma-cli@0.0.4',
45 silly install resolved     dist:
45 silly install resolved      { shasum: '1840a6a2545754bb02100f09229cdd9963a6cf68',
45 silly install resolved        tarball: 'http://registry.npmjs.org/karma-cli/-/karma-cli-0.0.4.tgz' },
45 silly install resolved     _from: 'karma-cli@*',
45 silly install resolved     _npmVersion: '1.3.21',
45 silly install resolved     _npmUser: { name: 'vojtajina', email: 'vojta.jina@gmail.com' },
45 silly install resolved     maintainers: [ [Object] ],
45 silly install resolved     directories: {},
45 silly install resolved     _shasum: '1840a6a2545754bb02100f09229cdd9963a6cf68',
45 silly install resolved     _resolved: 'https://registry.npmjs.org/karma-cli/-/karma-cli-0.0.4.tgz' } ]
46 info install karma-cli@0.0.4 into /home/yahya/.nvm/versions/node/v0.12.2/lib
47 info installOne karma-cli@0.0.4
48 verbose installOne of karma-cli to /home/yahya/.nvm/versions/node/v0.12.2/lib not in flight; installing
49 verbose lock using /home/yahya/.npm/_locks/karma-cli-bf51ed31758d06f5.lock for /home/yahya/.nvm/versions/node/v0.12.2/lib/node_modules/karma-cli
50 warn engine karma-cli@0.0.4: wanted: {"node":"~0.8 || ~0.10"} (current: {"node":"0.12.2","npm":"2.7.4"})
51 silly install write writing karma-cli 0.0.4 to /home/yahya/.nvm/versions/node/v0.12.2/lib/node_modules/karma-cli
52 silly cache addNamed cb karma-cli@0.0.4
53 verbose unbuild lib/node_modules/karma-cli
54 info preuninstall karma-cli@0.0.4
55 info uninstall karma-cli@0.0.4
56 verbose unbuild rmStuff karma-cli@0.0.4 from /home/yahya/.nvm/versions/node/v0.12.2/lib/node_modules
57 silly gentlyRm /home/yahya/.nvm/versions/node/v0.12.2/bin/karma is being gently removed
58 silly gentlyRm verifying /home/yahya/.nvm/versions/node/v0.12.2 is an npm working directory
59 silly gentlyRm containing path /home/yahya/.nvm/versions/node/v0.12.2 is under npm's control, in /home/yahya/.nvm/versions/node/v0.12.2
60 silly gentlyRm deletion target /home/yahya/.nvm/versions/node/v0.12.2/bin/karma is under /home/yahya/.nvm/versions/node/v0.12.2
61 verbose gentlyRm vacuuming from /home/yahya/.nvm/versions/node/v0.12.2/bin/karma up to /home/yahya/.nvm/versions/node/v0.12.2
62 info postuninstall karma-cli@0.0.4
63 silly gentlyRm /home/yahya/.nvm/versions/node/v0.12.2/lib/node_modules/karma-cli is being purged from base /home/yahya/.nvm/versions/node/v0.12.2
64 verbose gentlyRm don't care about contents; nuking /home/yahya/.nvm/versions/node/v0.12.2/lib/node_modules/karma-cli
65 silly vacuum-fs purging /home/yahya/.nvm/versions/node/v0.12.2/lib/node_modules/karma-cli
66 silly vacuum-fs quitting because other entries in /home/yahya/.nvm/versions/node/v0.12.2/lib/node_modules
67 verbose tar unpack /home/yahya/.npm/karma-cli/0.0.4/package.tgz
68 verbose tar unpacking to /home/yahya/.nvm/versions/node/v0.12.2/lib/node_modules/karma-cli
69 silly gentlyRm /home/yahya/.nvm/versions/node/v0.12.2/lib/node_modules/karma-cli is being purged
70 verbose gentlyRm don't care about contents; nuking /home/yahya/.nvm/versions/node/v0.12.2/lib/node_modules/karma-cli
71 silly gunzTarPerm modes [ '775', '664' ]
72 silly gunzTarPerm extractEntry package.json
73 silly gunzTarPerm modified mode [ 'package.json', 420, 436 ]
74 silly gunzTarPerm extractEntry README.md
75 silly gunzTarPerm modified mode [ 'README.md', 420, 436 ]
76 silly gunzTarPerm extractEntry LICENSE
77 silly gunzTarPerm modified mode [ 'LICENSE', 420, 436 ]
78 silly gunzTarPerm extractEntry CHANGELOG.md
79 silly gunzTarPerm modified mode [ 'CHANGELOG.md', 420, 436 ]
80 silly gunzTarPerm extractEntry bin/karma
81 silly gunzTarPerm modified mode [ 'bin/karma', 493, 509 ]
82 info preinstall karma-cli@0.0.4
83 silly prepareForInstallMany adding resolve@~0.5.1 from karma-cli dependencies
84 silly cache add args [ 'resolve@~0.5.1', null ]
85 verbose cache add spec resolve@~0.5.1
86 silly cache add parsed spec { raw: 'resolve@~0.5.1',
86 silly cache add   scope: null,
86 silly cache add   name: 'resolve',
86 silly cache add   rawSpec: '~0.5.1',
86 silly cache add   spec: '>=0.5.1 <0.6.0',
86 silly cache add   type: 'range' }
87 verbose addNamed resolve@>=0.5.1 <0.6.0
88 silly addNamed semver.valid null
89 silly addNamed semver.validRange >=0.5.1 <0.6.0
90 silly addNameRange { name: 'resolve', range: '>=0.5.1 <0.6.0', hasData: false }
91 silly mapToRegistry name resolve
92 silly mapToRegistry using default registry
93 silly mapToRegistry registry https://registry.npmjs.org/
94 silly mapToRegistry uri https://registry.npmjs.org/resolve
95 verbose addNameRange registry:https://registry.npmjs.org/resolve not in flight; fetching
96 verbose request uri https://registry.npmjs.org/resolve
97 verbose request no auth needed
98 info attempt registry request try #1 at 4:24:19 PM
99 http request GET https://registry.npmjs.org/resolve
100 http 200 https://registry.npmjs.org/resolve
101 silly get cb [ 200,
101 silly get   { date: 'Wed, 15 Apr 2015 15:24:20 GMT',
101 silly get     server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
101 silly get     etag: '"BGPGHHY69TMGRK3Y5TSKIMIFD"',
101 silly get     'content-type': 'application/json',
101 silly get     'cache-control': 'max-age=60',
101 silly get     'content-length': '43162',
101 silly get     'accept-ranges': 'bytes',
101 silly get     via: '1.1 varnish',
101 silly get     age: '37',
101 silly get     'x-served-by': 'cache-ams4125-AMS',
101 silly get     'x-cache': 'HIT',
101 silly get     'x-cache-hits': '2',
101 silly get     'x-timer': 'S1429111460.820948,VS0,VE0',
101 silly get     vary: 'Accept',
101 silly get     'keep-alive': 'timeout=10, max=50',
101 silly get     connection: 'Keep-Alive' } ]
102 verbose get saving resolve to /home/yahya/.npm/registry.npmjs.org/resolve/.cache.json
103 silly addNameRange number 2 { name: 'resolve', range: '>=0.5.1 <0.6.0', hasData: true }
104 silly addNameRange versions [ 'resolve',
104 silly addNameRange   [ '0.0.0',
104 silly addNameRange     '0.0.1',
104 silly addNameRange     '0.0.2',
104 silly addNameRange     '0.0.3',
104 silly addNameRange     '0.0.4',
104 silly addNameRange     '0.1.0',
104 silly addNameRange     '0.1.2',
104 silly addNameRange     '0.1.3',
104 silly addNameRange     '0.2.0',
104 silly addNameRange     '0.2.1',
104 silly addNameRange     '0.2.2',
104 silly addNameRange     '0.2.3',
104 silly addNameRange     '0.2.4',
104 silly addNameRange     '0.2.5',
104 silly addNameRange     '0.2.6',
104 silly addNameRange     '0.2.7',
104 silly addNameRange     '0.2.8',
104 silly addNameRange     '0.3.0',
104 silly addNameRange     '0.3.1',
104 silly addNameRange     '0.4.0',
104 silly addNameRange     '0.4.1',
104 silly addNameRange     '0.4.2',
104 silly addNameRange     '0.4.3',
104 silly addNameRange     '0.5.0',
104 silly addNameRange     '0.5.1',
104 silly addNameRange     '0.6.0',
104 silly addNameRange     '0.6.1',
104 silly addNameRange     '0.6.2',
104 silly addNameRange     '0.6.3',
104 silly addNameRange     '0.7.0',
104 silly addNameRange     '0.7.1',
104 silly addNameRange     '0.7.2',
104 silly addNameRange     '0.7.3',
104 silly addNameRange     '0.7.4',
104 silly addNameRange     '1.0.0',
104 silly addNameRange     '1.1.0',
104 silly addNameRange     '1.1.2',
104 silly addNameRange     '1.1.3',
104 silly addNameRange     '1.1.4',
104 silly addNameRange     '1.1.5',
104 silly addNameRange     '1.1.6' ] ]
105 verbose addNamed resolve@0.5.1
106 silly addNamed semver.valid 0.5.1
107 silly addNamed semver.validRange 0.5.1
108 silly mapToRegistry name resolve
109 silly mapToRegistry using default registry
110 silly mapToRegistry registry https://registry.npmjs.org/
111 silly mapToRegistry uri https://registry.npmjs.org/resolve
112 verbose addRemoteTarball https://registry.npmjs.org/resolve/-/resolve-0.5.1.tgz not in flight; adding
113 verbose addRemoteTarball [ 'https://registry.npmjs.org/resolve/-/resolve-0.5.1.tgz',
113 verbose addRemoteTarball   '15e4a222c4236bcd4cf85454412c2d0fb6524576' ]
114 info retry fetch attempt 1 at 4:24:22 PM
115 info attempt registry request try #1 at 4:24:22 PM
116 http fetch GET https://registry.npmjs.org/resolve/-/resolve-0.5.1.tgz
117 http fetch 200 https://registry.npmjs.org/resolve/-/resolve-0.5.1.tgz
118 silly fetchAndShaCheck shasum 15e4a222c4236bcd4cf85454412c2d0fb6524576
119 verbose addTmpTarball /tmp/npm-30036-a6ca6966/registry.npmjs.org/resolve/-/resolve-0.5.1.tgz not in flight; adding
120 verbose addTmpTarball already have metadata; skipping unpack for resolve@0.5.1
121 silly cache afterAdd resolve@0.5.1
122 verbose afterAdd /home/yahya/.npm/resolve/0.5.1/package/package.json not in flight; writing
123 verbose afterAdd /home/yahya/.npm/resolve/0.5.1/package/package.json written
124 silly install resolved [ { name: 'resolve',
124 silly install resolved     description: 'resolve like require.resolve() on behalf of files asynchronously and synchronously',
124 silly install resolved     version: '0.5.1',
124 silly install resolved     repository:
124 silly install resolved      { type: 'git',
124 silly install resolved        url: 'git://github.com/substack/node-resolve.git' },
124 silly install resolved     main: 'index.js',
124 silly install resolved     keywords: [ 'resolve', 'require', 'node', 'module' ],
124 silly install resolved     scripts: { test: 'tap test/*.js' },
124 silly install resolved     devDependencies: { tap: '~0.4.0' },
124 silly install resolved     license: 'MIT',
124 silly install resolved     author:
124 silly install resolved      { name: 'James Halliday',
124 silly install resolved        email: 'mail@substack.net',
124 silly install resolved        url: 'http://substack.net' },
124 silly install resolved     bugs: { url: 'https://github.com/substack/node-resolve/issues' },
124 silly install resolved     _id: 'resolve@0.5.1',
124 silly install resolved     dist:
124 silly install resolved      { shasum: '15e4a222c4236bcd4cf85454412c2d0fb6524576',
124 silly install resolved        tarball: 'http://registry.npmjs.org/resolve/-/resolve-0.5.1.tgz' },
124 silly install resolved     _from: 'resolve@>=0.5.1 <0.6.0',
124 silly install resolved     _npmVersion: '1.3.7',
124 silly install resolved     _npmUser: { name: 'substack', email: 'mail@substack.net' },
124 silly install resolved     maintainers: [ [Object] ],
124 silly install resolved     directories: {},
124 silly install resolved     _shasum: '15e4a222c4236bcd4cf85454412c2d0fb6524576',
124 silly install resolved     _resolved: 'https://registry.npmjs.org/resolve/-/resolve-0.5.1.tgz' } ]
125 info install resolve@0.5.1 into /home/yahya/.nvm/versions/node/v0.12.2/lib/node_modules/karma-cli
126 info installOne resolve@0.5.1
127 verbose installOne of resolve to /home/yahya/.nvm/versions/node/v0.12.2/lib/node_modules/karma-cli not in flight; installing
128 verbose lock using /home/yahya/.npm/_locks/resolve-a6c466f204e1b9af.lock for /home/yahya/.nvm/versions/node/v0.12.2/lib/node_modules/karma-cli/node_modules/resolve
129 silly install write writing resolve 0.5.1 to /home/yahya/.nvm/versions/node/v0.12.2/lib/node_modules/karma-cli/node_modules/resolve
130 silly cache addNamed cb resolve@0.5.1
131 verbose unbuild lib/node_modules/karma-cli/node_modules/resolve
132 silly gentlyRm /home/yahya/.nvm/versions/node/v0.12.2/lib/node_modules/karma-cli/node_modules/resolve is being purged from base /home/yahya/.nvm/versions/node/v0.12.2
133 verbose gentlyRm don't care about contents; nuking /home/yahya/.nvm/versions/node/v0.12.2/lib/node_modules/karma-cli/node_modules/resolve
134 verbose tar unpack /home/yahya/.npm/resolve/0.5.1/package.tgz
135 verbose tar unpacking to /home/yahya/.nvm/versions/node/v0.12.2/lib/node_modules/karma-cli/node_modules/resolve
136 silly gentlyRm /home/yahya/.nvm/versions/node/v0.12.2/lib/node_modules/karma-cli/node_modules/resolve is being purged
137 verbose gentlyRm don't care about contents; nuking /home/yahya/.nvm/versions/node/v0.12.2/lib/node_modules/karma-cli/node_modules/resolve
138 silly gunzTarPerm modes [ '775', '664' ]
139 silly gunzTarPerm extractEntry package.json
140 silly gunzTarPerm modified mode [ 'package.json', 420, 436 ]
141 silly gunzTarPerm extractEntry LICENSE
142 silly gunzTarPerm modified mode [ 'LICENSE', 420, 436 ]
143 silly gunzTarPerm extractEntry index.js
144 silly gunzTarPerm modified mode [ 'index.js', 420, 436 ]
145 silly gunzTarPerm extractEntry .travis.yml
146 silly gunzTarPerm modified mode [ '.travis.yml', 420, 436 ]
147 silly gunzTarPerm extractEntry example/async.js
148 silly gunzTarPerm modified mode [ 'example/async.js', 420, 436 ]
149 silly gunzTarPerm extractEntry example/sync.js
150 silly gunzTarPerm modified mode [ 'example/sync.js', 420, 436 ]
151 silly gunzTarPerm extractEntry lib/async.js
152 silly gunzTarPerm modified mode [ 'lib/async.js', 420, 436 ]
153 silly gunzTarPerm extractEntry lib/caller.js
154 silly gunzTarPerm modified mode [ 'lib/caller.js', 420, 436 ]
155 silly gunzTarPerm extractEntry lib/core.js
156 silly gunzTarPerm modified mode [ 'lib/core.js', 420, 436 ]
157 silly gunzTarPerm extractEntry lib/node-modules-paths.js
158 silly gunzTarPerm modified mode [ 'lib/node-modules-paths.js', 420, 436 ]
159 silly gunzTarPerm extractEntry lib/sync.js
160 silly gunzTarPerm modified mode [ 'lib/sync.js', 420, 436 ]
161 silly gunzTarPerm extractEntry lib/core.json
162 silly gunzTarPerm modified mode [ 'lib/core.json', 420, 436 ]
163 silly gunzTarPerm extractEntry readme.markdown
164 silly gunzTarPerm modified mode [ 'readme.markdown', 420, 436 ]
165 silly gunzTarPerm extractEntry test/core.js
166 silly gunzTarPerm modified mode [ 'test/core.js', 420, 436 ]
167 silly gunzTarPerm extractEntry test/filter.js
168 silly gunzTarPerm modified mode [ 'test/filter.js', 420, 436 ]
169 silly gunzTarPerm extractEntry test/filter_sync.js
170 silly gunzTarPerm modified mode [ 'test/filter_sync.js', 420, 436 ]
171 silly gunzTarPerm extractEntry test/mock.js
172 silly gunzTarPerm modified mode [ 'test/mock.js', 420, 436 ]
173 silly gunzTarPerm extractEntry test/mock_sync.js
174 silly gunzTarPerm modified mode [ 'test/mock_sync.js', 420, 436 ]
175 silly gunzTarPerm extractEntry test/resolver.js
176 silly gunzTarPerm modified mode [ 'test/resolver.js', 420, 436 ]
177 silly gunzTarPerm extractEntry test/resolver_sync.js
178 silly gunzTarPerm modified mode [ 'test/resolver_sync.js', 420, 436 ]
179 silly gunzTarPerm extractEntry test/resolver/foo.js
180 silly gunzTarPerm modified mode [ 'test/resolver/foo.js', 420, 436 ]
181 silly gunzTarPerm extractEntry test/resolver/mug.js
182 silly gunzTarPerm modified mode [ 'test/resolver/mug.js', 420, 436 ]
183 silly gunzTarPerm extractEntry test/resolver/incorrect_main/package.json
184 silly gunzTarPerm modified mode [ 'test/resolver/incorrect_main/package.json', 420, 436 ]
185 silly gunzTarPerm extractEntry test/resolver/incorrect_main/index.js
186 silly gunzTarPerm modified mode [ 'test/resolver/incorrect_main/index.js', 420, 436 ]
187 silly gunzTarPerm extractEntry test/resolver/cup.coffee
188 silly gunzTarPerm modified mode [ 'test/resolver/cup.coffee', 420, 436 ]
189 silly gunzTarPerm extractEntry test/resolver/bar/node_modules/foo/index.js
190 silly gunzTarPerm modified mode [ 'test/resolver/bar/node_modules/foo/index.js', 420, 436 ]
191 silly gunzTarPerm extractEntry test/resolver/baz/package.json
192 silly gunzTarPerm modified mode [ 'test/resolver/baz/package.json', 420, 436 ]
193 silly gunzTarPerm extractEntry test/resolver/baz/doom.js
194 silly gunzTarPerm modified mode [ 'test/resolver/baz/doom.js', 420, 436 ]
195 silly gunzTarPerm extractEntry test/resolver/baz/quux.js
196 silly gunzTarPerm modified mode [ 'test/resolver/baz/quux.js', 420, 436 ]
197 silly gunzTarPerm extractEntry test/resolver/mug.coffee
198 silly gunzTarPerm modified mode [ 'test/resolver/mug.coffee', 420, 436 ]
199 silly gunzTarPerm extractEntry test/resolver/biz/node_modules/garply/package.json
200 silly gunzTarPerm modified mode [ 'test/resolver/biz/node_modules/garply/package.json',
200 silly gunzTarPerm   420,
200 silly gunzTarPerm   436 ]
201 silly gunzTarPerm extractEntry test/resolver/biz/node_modules/garply/lib/index.js
202 silly gunzTarPerm modified mode [ 'test/resolver/biz/node_modules/garply/lib/index.js',
202 silly gunzTarPerm   420,
202 silly gunzTarPerm   436 ]
203 silly gunzTarPerm extractEntry test/resolver/biz/node_modules/grux/index.js
204 silly gunzTarPerm modified mode [ 'test/resolver/biz/node_modules/grux/index.js', 420, 436 ]
205 silly gunzTarPerm extractEntry test/resolver/biz/node_modules/tiv/index.js
206 silly gunzTarPerm modified mode [ 'test/resolver/biz/node_modules/tiv/index.js', 420, 436 ]
207 silly gunzTarPerm extractEntry test/resolver/other_path/root.js
208 silly gunzTarPerm modified mode [ 'test/resolver/other_path/root.js', 420, 436 ]
209 silly gunzTarPerm extractEntry test/resolver/other_path/lib/other-lib.js
210 silly gunzTarPerm modified mode [ 'test/resolver/other_path/lib/other-lib.js', 420, 436 ]
211 silly gunzTarPerm extractEntry test/resolver/quux/foo/index.js
212 silly gunzTarPerm modified mode [ 'test/resolver/quux/foo/index.js', 420, 436 ]
213 silly gunzTarPerm extractEntry test/resolver/without_basedir/main.js
214 silly gunzTarPerm modified mode [ 'test/resolver/without_basedir/main.js', 420, 436 ]
215 silly gunzTarPerm extractEntry test/resolver/without_basedir/node_modules/mymodule.js
216 silly gunzTarPerm modified mode [ 'test/resolver/without_basedir/node_modules/mymodule.js',
216 silly gunzTarPerm   420,
216 silly gunzTarPerm   436 ]
217 info preinstall resolve@0.5.1
218 silly install resolved []
219 verbose about to build /home/yahya/.nvm/versions/node/v0.12.2/lib/node_modules/karma-cli/node_modules/resolve
220 info build /home/yahya/.nvm/versions/node/v0.12.2/lib/node_modules/karma-cli/node_modules/resolve
221 verbose linkStuff [ true,
221 verbose linkStuff   '/home/yahya/.nvm/versions/node/v0.12.2/lib/node_modules',
221 verbose linkStuff   false,
221 verbose linkStuff   '/home/yahya/.nvm/versions/node/v0.12.2/lib/node_modules/karma-cli/node_modules' ]
222 info linkStuff resolve@0.5.1
223 verbose stack TypeError: Object.keys called on non-object
223 verbose stack     at Function.keys (native)
223 verbose stack     at scriptpath (/home/yahya/.nvm/versions/node/v0.12.2/lib/node_modules/npm/node_modules/read-package-json/read-json.js:133:32)
223 verbose stack     at /home/yahya/.nvm/versions/node/v0.12.2/lib/node_modules/npm/node_modules/read-package-json/read-json.js:121:33
223 verbose stack     at Array.forEach (native)
223 verbose stack     at extras (/home/yahya/.nvm/versions/node/v0.12.2/lib/node_modules/npm/node_modules/read-package-json/read-json.js:120:21)
223 verbose stack     at parseJson (/home/yahya/.nvm/versions/node/v0.12.2/lib/node_modules/npm/node_modules/read-package-json/read-json.js:88:17)
223 verbose stack     at /home/yahya/.nvm/versions/node/v0.12.2/lib/node_modules/npm/node_modules/read-package-json/read-json.js:60:33
223 verbose stack     at evalmachine.<anonymous>:334:14
223 verbose stack     at /home/yahya/.nvm/versions/node/v0.12.2/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:102:5
223 verbose stack     at FSReqWrap.oncomplete (evalmachine.<anonymous>:95:15)
224 verbose cwd /var/www/tests/authentication_with_satellizer-plunk-P5KPum
225 error Linux 3.16.0-34-generic
226 error argv "/home/yahya/.nvm/versions/node/v0.12.2/bin/node" "/home/yahya/.nvm/versions/node/v0.12.2/bin/npm" "install" "-g" "karma-cli"
227 error node v0.12.2
228 error npm  v2.7.4
229 error Object.keys called on non-object
230 error If you need help, you may report this error at:
230 error     <https://github.com/npm/npm/issues>
231 verbose exit [ 1, true ]
```

I'm on Ubuntu 14.04 and using nvm to install node and I tried this with this versions of node: 
- v0.12.2
- v0.12.1
- v0.12.0
- v0.11.16
- v0.11.14
- v0.10.26

And I get the same error!!!  
What's going on here what I'm doing wrong?

**Comment by yahyaKacem** [comment]
OK, I did this:

    rm -r /tmp/npm-* npm_debug.log ~/.npm/* 

Then re-install node v0.12.2 with nvm now it works!!!
I don't know what was wrong.
I also did 2 small changes to the package.json file and bower.json although I think this is irrelevant:

package.json git diff:

![package](https://cloud.githubusercontent.com/assets/844900/7164320/65a0bbbe-e397-11e4-8e39-6e669d3d0600.png)

bower.json git diff:

![bower](https://cloud.githubusercontent.com/assets/844900/7164321/66d49d48-e397-11e4-838e-2bf34a1dde9d.png)


Does anyone know what's happening here?
