### ISSUE TITLE
Protocol relative URLs returned from registry break install

### ISSUE THREAD

**Issue by moll** [npm/npm#7971]
Hey,

I was just trying out Sinopia and set its URL prefix to a protocol relative URL (<//registry.example.com>):

Took me a while to understand why it broke install, but the `dist.tarball` property returned from the registry will then contain that same protocol relative URL, e.g: <//registry.example.com/pkg/-/pkg-0.1.337.tgz>. That URL will eventually be passed to **npm-cache-filename** which will parse it with `Url.parse` and expect to find a `host` property on it. It doesn't, and blows up.

```
npm verb stack TypeError: Cannot read property 'replace' of null
npm verb stack     at cf (/usr/local/lib/node_modules/npm/node_modules/npm-cache-filename/index.js:13:17)
npm verb stack     at addRemoteTarball (/usr/local/lib/node_modules/npm/lib/cache/add-remote-tarball.js:34:13)
npm verb stack     at /usr/local/lib/node_modules/npm/lib/cache/add-named.js:194:9
npm verb stack     at mapToRegistry (/usr/local/lib/node_modules/npm/lib/utils/map-to-registry.js:55:3)
npm verb stack     at fetchit (/usr/local/lib/node_modules/npm/lib/cache/add-named.js:174:7)
npm verb stack     at /usr/local/lib/node_modules/npm/lib/cache/add-named.js:170:21
npm verb stack     at FSReqWrap.oncomplete (evalmachine.<anonymous>:95:15)
```

I'm not 100% sure if protocol relative URLs should be supported, but blowing up is probably not a good outcome in any case. A descriptive error would've saved me some time at least.

Cheers

**Comment by smikes** [comment]
Thanks for the bug report!

**Comment by leth** [comment]
We've been seeing this a **lot**. Thanks for putting in the time to chase the error!

**Comment by leth** [comment]
I've prodded our proxy, and the couple of rewrites looks sane.
Here's the logs we see:

```
...
npm verb correctMkdir /root/.npm correctMkdir not in flight; initializing
npm http 200 http://npm-mirror/ansi-styles
npm verb headers { server: 'nginx/1.4.6 (Ubuntu)',
npm verb headers   date: 'Mon, 23 May 2016 08:21:57 GMT',
npm verb headers   'content-type': 'application/json',
npm verb headers   'transfer-encoding': 'chunked',
npm verb headers   connection: 'keep-alive',
npm verb headers   'cache-control': 'max-age=300',
npm verb headers   'accept-ranges': 'bytes',
npm verb headers   via: '1.1 varnish',
npm verb headers   age: '211',
npm verb headers   'x-served-by': 'cache-ams4130-AMS',
npm verb headers   'x-cache': 'HIT, EXPIRED',
npm verb headers   'x-cache-hits': '2',
npm verb headers   'x-timer': 'S1463991697.254230,VS0,VE0',
npm verb headers   vary: 'Accept-Encoding' }
npm verb get saving ansi-styles to /root/.npm/npm-mirror/ansi-styles/.cache.json
npm verb correctMkdir /root/.npm correctMkdir not in flight; initializing
npm info retry fetch attempt 1 at 08:21:37
npm info attempt registry request try #1 at 08:21:37
npm http fetch GET http://npm-mirror/has-ansi/-/has-ansi-2.0.0.tgz
npm info retry fetch attempt 1 at 08:21:37
npm info attempt registry request try #1 at 08:21:37
npm http fetch GET http://npm-mirror/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz
npm http 200 http://npm-mirror/supports-color
npm verb headers { server: 'nginx/1.4.6 (Ubuntu)',
npm verb headers   date: 'Mon, 23 May 2016 08:21:57 GMT',
npm verb headers   'content-type': 'application/json',
npm verb headers   'transfer-encoding': 'chunked',
npm verb headers   connection: 'keep-alive',
npm verb headers   'cache-control': 'max-age=300',
npm verb headers   'accept-ranges': 'bytes',
npm verb headers   via: '1.1 varnish',
npm verb headers   age: '31',
npm verb headers   'x-served-by': 'cache-ams4126-AMS',
npm verb headers   'x-cache': 'HIT, EXPIRED',
npm verb headers   'x-cache-hits': '2',
npm verb headers   'x-timer': 'S1463991697.254214,VS0,VE0',
npm verb headers   vary: 'Accept-Encoding' }
npm verb get saving supports-color to /root/.npm/npm-mirror/supports-color/.cache.json
npm verb correctMkdir /root/.npm correctMkdir not in flight; initializing
npm verb cache add spec strip-ansi@^3.0.0
npm verb addNamed ">=3.0.0 <4.0.0" is a valid semver range for strip-ansi
npm verb addNameRange registry:http://npm-mirror/strip-ansi not in flight; fetching
npm verb cache add spec ansi-styles@^2.2.1
npm verb addNamed ">=2.2.1 <3.0.0" is a valid semver range for ansi-styles
npm verb addNameRange registry:http://npm-mirror/ansi-styles not in flight; fetching
npm verb cache add spec supports-color@^2.0.0
npm verb addNamed ">=2.0.0 <3.0.0" is a valid semver range for supports-color
npm verb addNameRange registry:http://npm-mirror/supports-color not in flight; fetching
npm verb get http://npm-mirror/strip-ansi not expired, no request
npm verb addNamed "3.0.1" is a plain semver version for strip-ansi
npm verb get http://npm-mirror/ansi-styles not expired, no request
npm verb addNamed "2.2.1" is a plain semver version for ansi-styles
npm verb addRemoteTarball http://npm-mirror/strip-ansi/-/strip-ansi-3.0.1.tgz not in flight; adding
npm verb addRemoteTarball [ 'http://npm-mirror/strip-ansi/-/strip-ansi-3.0.1.tgz',
npm verb addRemoteTarball   '6a385fb8853d952d5ff05d0e8aaf94278dc63dcf' ]
npm verb get http://npm-mirror/supports-color not expired, no request
npm verb addNamed "2.0.0" is a plain semver version for supports-color
npm verb addRemoteTarball https:/npm-mirror/ansi-styles/-/ansi-styles-2.2.1.tgz not in flight; adding
npm verb stack TypeError: Cannot read property 'replace' of null
npm verb stack     at cf (/usr/lib/node_modules/npm/node_modules/npm-cache-filename/index.js:11:17)
npm verb stack     at addRemoteTarball (/usr/lib/node_modules/npm/lib/cache/add-remote-tarball.js:37:13)
npm verb stack     at /usr/lib/node_modules/npm/lib/cache/add-named.js:216:9
npm verb stack     at mapToRegistry (/usr/lib/node_modules/npm/lib/utils/map-to-registry.js:62:3)
npm verb stack     at fetchit (/usr/lib/node_modules/npm/lib/cache/add-named.js:190:7)
npm verb stack     at /usr/lib/node_modules/npm/lib/cache/add-named.js:186:21
npm verb stack     at FSReqWrap.oncomplete (fs.js:82:15)
```

**Comment by kessler** [comment]
Hi, any updates on this?

**Comment by kessler** [comment]
Another update, scary one actually, the problem just disappeared from my AWS machine. Might have something to do with cleaning npm cache there but I'm not certain, as I'm unable to recreate this now.

/cc @vweevers
