### ISSUE TITLE
Error when Installing Dgeni into Project: Invalid version: "1.9"

### ISSUE THREAD

**Issue by phongmedia** [npm/npm#8001]
I'm able to install Dgeni globally on my machine no problems, although I'd like to have it as part of my project's node modules, so everybody who is developing on the project doesn't need to install Dgeni globally.

So I attempt to install Dgeni into my project folder, which already has `node_modules/jsdoc`.

I run this command: `npm install dgeni`

When installing Dgeni into my project directory (not globally) I keep getting this error:

```
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "dgeni"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.5

npm ERR! Invalid version: "1.9"
```

On inspecting the log file, this is the output.

```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'install', 'dgeni' ]
2 info using npm@2.7.5
3 info using node@v0.12.2
4 verbose node symlink /usr/local/bin/node
5 verbose stack Error: Invalid version: "1.9"
5 verbose stack     at Object.module.exports.fixVersionField (/usr/local/lib/node_modules/npm/node_modules/normalize-package-data/lib/fixer.js:190:13)
5 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/normalize-package-data/lib/normalize.js:30:38
5 verbose stack     at Array.forEach (native)
5 verbose stack     at normalize (/usr/local/lib/node_modules/npm/node_modules/normalize-package-data/lib/normalize.js:29:15)
5 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:368:33)
5 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:127:33)
5 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:267:40
5 verbose stack     at evalmachine.<anonymous>:334:14
5 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:102:5
5 verbose stack     at FSReqWrap.oncomplete (evalmachine.<anonymous>:95:15)
6 verbose cwd /Users/phong/Project/
7 error Darwin 14.1.0
8 error argv "node" "/usr/local/bin/npm" "install" "dgeni"
9 error node v0.12.2
10 error npm  v2.7.5
11 error Invalid version: "1.9"
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]
```

Any ideas? Thanks.

EDIT : I also receive this error installing other packages locally into the project, but not globally, for instance:

```
npm install nunjucks
```
^ Throws [the same] error.

```
npm install -g nunjucks
```
^ Installs globally without a problem.

**Comment by phongmedia** [comment]
Closed this issue - found the issue was an error in my `packages.json` file. The version of my project was at 1.9. If I omit the version line, then it seems to work alright.
