### ISSUE TITLE
503 Backend read error

### ISSUE THREAD

**Issue by WickedSik** [npm/npm#8006]
I found out today that I can not search for packages. (installing doesn't seem a problem)

~~~
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'search', 'grunt' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 silly mapToRegistry name -/all
5 silly mapToRegistry using default registry
6 silly mapToRegistry registry https://registry.npmjs.org/
7 silly mapToRegistry uri https://registry.npmjs.org/-/all
8 info updateIndex /Users/jpdokter/.npm/registry.npmjs.org/-/all/.cache.json
9 verbose request uri https://registry.npmjs.org/-/all/since?stale=update_after&startkey=1407429013258
10 verbose request no auth needed
11 info attempt registry request try #1 at 12:21:32 PM
12 verbose request id 7a6f636c74f7c848
13 http request GET https://registry.npmjs.org/-/all/since?stale=update_after&startkey=1407429013258
14 http 503 https://registry.npmjs.org/-/all/since?stale=update_after&startkey=1407429013258
15 verbose bad json <?xml version="1.0" encoding="utf-8"?>
15 verbose bad json <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
15 verbose bad json  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
15 verbose bad json <html>
15 verbose bad json   <head>
15 verbose bad json     <title>503 backend read error</title>
15 verbose bad json   </head>
15 verbose bad json   <body>
15 verbose bad json     <h1>Error 503 backend read error</h1>
15 verbose bad json     <p>backend read error</p>
15 verbose bad json     <h3>Guru Mediation:</h3>
15 verbose bad json     <p>Details: cache-ams4131-AMS 1429438952 1639850347</p>
15 verbose bad json     <hr>
15 verbose bad json     <p>Varnish cache server</p>
15 verbose bad json   </body>
15 verbose bad json </html>
16 error registry error parsing json
17 info retry will retry, error on last attempt: SyntaxError: Unexpected token <
17 info retry
17 info retry <?xml version="1.0" encoding="utf-8"?>
17 info retry <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
17 info retry  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
17 info retry <html>
17 info retry   <head>
17 info retry     <title>503 backend read error</title>
17 info retry   </head>
17 info retry   <body>
17 info retry     <h1>Error 503 backend read error</h1>
17 info retry     <p>backend read error</p>
17 info retry     <h3>Guru Mediation:</h3>
17 info retry     <p>Details: cache-ams4131-AMS 1429438952 1639850347</p>
17 info retry     <hr>
17 info retry     <p>Varnish cache server</p>
17 info retry   </body>
17 info retry </html>
18 info attempt registry request try #2 at 12:22:42 PM
19 http request GET https://registry.npmjs.org/-/all/since?stale=update_after&startkey=1407429013258
20 http 503 https://registry.npmjs.org/-/all/since?stale=update_after&startkey=1407429013258
21 verbose bad json <?xml version="1.0" encoding="utf-8"?>
21 verbose bad json <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
21 verbose bad json  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
21 verbose bad json <html>
21 verbose bad json   <head>
21 verbose bad json     <title>503 backend read error</title>
21 verbose bad json   </head>
21 verbose bad json   <body>
21 verbose bad json     <h1>Error 503 backend read error</h1>
21 verbose bad json     <p>backend read error</p>
21 verbose bad json     <h3>Guru Mediation:</h3>
21 verbose bad json     <p>Details: cache-ams4128-AMS 1429439022 2719522608</p>
21 verbose bad json     <hr>
21 verbose bad json     <p>Varnish cache server</p>
21 verbose bad json   </body>
21 verbose bad json </html>
22 error registry error parsing json
23 info retry will retry, error on last attempt: SyntaxError: Unexpected token <
23 info retry
23 info retry <?xml version="1.0" encoding="utf-8"?>
23 info retry <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
23 info retry  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
23 info retry <html>
23 info retry   <head>
23 info retry     <title>503 backend read error</title>
23 info retry   </head>
23 info retry   <body>
23 info retry     <h1>Error 503 backend read error</h1>
23 info retry     <p>backend read error</p>
23 info retry     <h3>Guru Mediation:</h3>
23 info retry     <p>Details: cache-ams4128-AMS 1429439022 2719522608</p>
23 info retry     <hr>
23 info retry     <p>Varnish cache server</p>
23 info retry   </body>
23 info retry </html>
24 info attempt registry request try #3 at 12:24:42 PM
25 http request GET https://registry.npmjs.org/-/all/since?stale=update_after&startkey=1407429013258
26 http 503 https://registry.npmjs.org/-/all/since?stale=update_after&startkey=1407429013258
27 verbose bad json <?xml version="1.0" encoding="utf-8"?>
27 verbose bad json <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
27 verbose bad json  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
27 verbose bad json <html>
27 verbose bad json   <head>
27 verbose bad json     <title>503 backend read error</title>
27 verbose bad json   </head>
27 verbose bad json   <body>
27 verbose bad json     <h1>Error 503 backend read error</h1>
27 verbose bad json     <p>backend read error</p>
27 verbose bad json     <h3>Guru Mediation:</h3>
27 verbose bad json     <p>Details: cache-ams4146-AMS 1429439142 1607322513</p>
27 verbose bad json     <hr>
27 verbose bad json     <p>Varnish cache server</p>
27 verbose bad json   </body>
27 verbose bad json </html>
28 error registry error parsing json
29 verbose headers { date: 'Sun, 19 Apr 2015 10:25:42 GMT',
29 verbose headers   server: 'Varnish',
29 verbose headers   'retry-after': '0',
29 verbose headers   'content-type': 'text/html; charset=utf-8',
29 verbose headers   'content-length': '448',
29 verbose headers   'accept-ranges': 'bytes',
29 verbose headers   via: '1.1 varnish',
29 verbose headers   'x-served-by': 'cache-ams4146-AMS',
29 verbose headers   'x-cache': 'MISS',
29 verbose headers   'x-cache-hits': '0',
29 verbose headers   'x-timer': 'S1429439082.426396,VS0,VE59997',
29 verbose headers   connection: 'close' }
30 verbose stack SyntaxError: Unexpected token <
30 verbose stack
30 verbose stack <?xml version="1.0" encoding="utf-8"?>
30 verbose stack <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
30 verbose stack  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
30 verbose stack <html>
30 verbose stack   <head>
30 verbose stack     <title>503 backend read error</title>
30 verbose stack   </head>
30 verbose stack   <body>
30 verbose stack     <h1>Error 503 backend read error</h1>
30 verbose stack     <p>backend read error</p>
30 verbose stack     <h3>Guru Mediation:</h3>
30 verbose stack     <p>Details: cache-ams4146-AMS 1429439142 1607322513</p>
30 verbose stack     <hr>
30 verbose stack     <p>Varnish cache server</p>
30 verbose stack   </body>
30 verbose stack </html>
30 verbose stack
30 verbose stack     at Object.parse (native)
30 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:197:23)
30 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:170:14)
30 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:344:22)
30 verbose stack     at Request.emit (events.js:110:17)
30 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1239:14)
30 verbose stack     at Request.emit (events.js:129:20)
30 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1187:12)
30 verbose stack     at IncomingMessage.emit (events.js:129:20)
30 verbose stack     at _stream_readable.js:908:16
31 verbose cwd /Users/jpdokter/Development/node/ImvuClient
32 error Darwin 14.3.0
33 error argv "node" "/usr/local/bin/npm" "search" "grunt"
34 error node v0.12.2
35 error npm  v2.7.4
36 error Unexpected token <
36 error
36 error <?xml version="1.0" encoding="utf-8"?>
36 error <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
36 error  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
36 error <html>
36 error   <head>
36 error     <title>503 backend read error</title>
36 error   </head>
36 error   <body>
36 error     <h1>Error 503 backend read error</h1>
36 error     <p>backend read error</p>
36 error     <h3>Guru Mediation:</h3>
36 error     <p>Details: cache-ams4146-AMS 1429439142 1607322513</p>
36 error     <hr>
36 error     <p>Varnish cache server</p>
36 error   </body>
36 error </html>
37 error If you need help, you may report this error at:
37 error     <https://github.com/npm/npm/issues>
38 verbose exit [ 1, true ]
~~~

**Comment by smikes** [comment]
`npm search` attempts to build a local index of packages.  This worked well when there were about 1,000 packages, but now there are over 130,000 -- so to build this index, `npm search` first has to download a 90MB file and parse it.

Worse, the backend has to generate this file from scratch, which sometimes fails -- the errors you are reporting here are symptoms of backend failure.

The recommended workaround is to use the website search at https://www.npmjs.com/ .  Eventually, `npm search` will be fixed either by making a better semi-offline search, or by having `npm search` go to the same endpoint as the website.  However, fixing this has not yet made it onto the npm cli roadmap ( https://github.com/npm/npm/wiki/Roadmap ) because there are other scaling problems that are harder to workaround.

**Comment by WickedSik** [comment]
I don't think this is completely true, as it actually pulls an update since 1407429013258, but I understand the problem. If there is already an issue made adressing this problem, then I would suggest this issue is to be closed.

**Comment by smikes** [comment]
There are several open issues around fixing npm search; here are two:

https://github.com/npm/npm/issues/6016
https://github.com/npm/npm/issues/4360

**Comment by othiym23** [comment]
Closing as resolved – search is still not in the greatest shape, but we've addressed the underlying issue with this in the registry by leaning harder on npm's CDN and caching the results of the search endpoint.
