### ISSUE TITLE
npm publish error "503 backend read error"

### ISSUE THREAD

**Issue by jasonswearingen** [npm/npm#8015]
Hi, unable to publish.  not doing anything fancy (i think, but this is my first package).

EDIT: npm version is 2.8.3

here is my npm-debug.log file
```
0 info it worked if it ends with ok
1 verbose cli [ 'node',
1 verbose cli   'C:\\Users\\Jason\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'publish' ]
2 info using npm@2.8.3
3 info using node@v0.12.2
4 verbose publish [ '.' ]
5 silly cache add args [ '.', null ]
6 verbose cache add spec .
7 silly cache add parsed spec { raw: '.',
7 silly cache add   scope: null,
7 silly cache add   name: null,
7 silly cache add   rawSpec: '.',
7 silly cache add   spec: 'C:\\repos\\xlib',
7 silly cache add   type: 'directory' }
8 verbose addLocalDirectory C:\Users\Jason\AppData\Roaming\npm-cache\xlib\0.0.2\package.tgz not in flight; packing
9 verbose tar pack [ 'C:\\Users\\Jason\\AppData\\Roaming\\npm-cache\\xlib\\0.0.2\\package.tgz',
9 verbose tar pack   'C:\\repos\\xlib' ]
10 verbose tarball C:\Users\Jason\AppData\Roaming\npm-cache\xlib\0.0.2\package.tgz
11 verbose folder C:\repos\xlib
12 info prepublish xlib@0.0.2
13 verbose addLocalTarball adding from inside cache C:\Users\Jason\AppData\Roaming\npm-cache\xlib\0.0.2\package.tgz
14 silly cache afterAdd xlib@0.0.2
15 verbose afterAdd C:\Users\Jason\AppData\Roaming\npm-cache\xlib\0.0.2\package\package.json not in flight; writing
16 verbose afterAdd C:\Users\Jason\AppData\Roaming\npm-cache\xlib\0.0.2\package\package.json written
17 silly publish { name: 'xlib',
17 silly publish   version: '0.0.2',
17 silly publish   description: 'A Cross Platform, Monolithic Core Library for Typescript.',
17 silly publish   main: 'index.js',
17 silly publish   private: false,
17 silly publish   author: { name: 'jason swearingen', email: 'jasons@novaleaf.com' },
17 silly publish   dependencies:
17 silly publish    { async: '^0.9.0',
17 silly publish      bluebird: '^2.9.8',
17 silly publish      bunyan: '^1.2.3',
17 silly publish      'bunyan-prettystream': '^0.1.3',
17 silly publish      commander: '^2.6.0',
17 silly publish      d3: '^3.5.5',
17 silly publish      dsv: '0.0.4',
17 silly publish      'form-data': '^0.2.0',
17 silly publish      moment: '^2.9.0',
17 silly publish      'moment-timezone': '^0.3.0',
17 silly publish      paralleljs: '^0.2.1',
17 silly publish      request: '^2.53.0',
17 silly publish      'request-promise': '^0.4.0',
17 silly publish      rx: '^2.3.25',
17 silly publish      'source-map-support': '^0.2.9',
17 silly publish      'sprintf-js': '^1.0.2',
17 silly publish      validator: '^3.28.0',
17 silly publish      commondir: '0.0.1',
17 silly publish      json5: '^0.4.0',
17 silly publish      lodash: '^2.4.1' },
17 silly publish   devDependencies:
17 silly publish    { browserify: '^7.0.3',
17 silly publish      'convert-source-map': '^0.4.1',
17 silly publish      grunt: '^0.4.5',
17 silly publish      'grunt-babel': '^4.0.0',
17 silly publish      'grunt-browserify': '^3.2.1',
17 silly publish      'grunt-contrib-clean': '^0.6.0',
17 silly publish      'grunt-contrib-uglify': '^0.7.0',
17 silly publish      'grunt-contrib-watch': '^0.6.1',
17 silly publish      'grunt-dts-bundle': '^0.2.0',
17 silly publish      'grunt-dts-concat': '^0.1.6',
17 silly publish      'grunt-ts': '^2.0.1',
17 silly publish      'grunt-tsd': '^0.1.0',
17 silly publish      'grunt-tslint': '^1.0.1',
17 silly publish      'grunt-typedoc': '^0.2.1',
17 silly publish      'load-grunt-tasks': '^3.1.0',
17 silly publish      mocha: '^2.1.0',
17 silly publish      tsify: '^0.7.0',
17 silly publish      typescript: '^1.4.0' },
17 silly publish   scripts: { test: 'mocha' },
17 silly publish   repository:
17 silly publish    { type: 'git',
17 silly publish      url: 'git+https://jasonswearingen@github.com/jasonswearingen/xlib.git' },
17 silly publish   keywords: [ 'monolithic', 'corelib', 'typescript' ],
17 silly publish   license: 'MIT',
17 silly publish   bugs: { url: 'https://github.com/jasonswearingen/xlib/issues' },
17 silly publish   homepage: 'https://github.com/jasonswearingen/xlib',
17 silly publish   readme: '﻿# A monolithic, cross-platform library.  (Browser+Node)\r\n*Kitchen sink included.*\r\n\r\n-----\r\n# Status: UNSTABLE, Active Development\r\n**Do not** use this library for the time being.  It is under active development and the structure will change as I figure out how to publish reusable typescript libraries.\r\n\r\n\r\n#Usage Requirements\r\n\r\n##Node.JS:\r\n1. Can be used as is.  Tested with Node v0.12 on Ubuntu and Win8.1\r\n\r\n##Browser:\r\n1. Requires Browserify, or similar node core module conversions to use some components.  may mostly work without browserify, but not tested.\r\n2. Modern Browser is assumed.  No back-compat testing has been done.\r\n\r\n##Typescript:\r\n1. This is coded in Typescript so should be able to use without extra tsd definitions.  will provide more details when optimal workflow is figured out.\r\n\r\n#Development:\r\n\r\n##Windows\r\n1. Developed using VS2013+NTVS.  see VS project file in root dir.\r\n\r\n##Linux\r\nlinux dev grunt scripts have been tested but not currently functional.  you can find the scripts in ```./dev/graveyard/gruntfile.ts```\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n',
17 silly publish   readmeFilename: 'README.md',
17 silly publish   gitHead: 'deafd0f83ad0ea1d2740d74e083f56a17fd03315',
17 silly publish   _id: 'xlib@0.0.2',
17 silly publish   _shasum: '3be3f82addc4ada83e9ef817cc1fb1b19823697b',
17 silly publish   _from: '.' }
18 silly mapToRegistry name xlib
19 silly mapToRegistry using default registry
20 silly mapToRegistry registry https://registry.npmjs.org/
21 silly mapToRegistry uri https://registry.npmjs.org/xlib
22 verbose publish registryBase https://registry.npmjs.org/
23 silly publish uploading C:\Users\Jason\AppData\Roaming\npm-cache\xlib\0.0.2\package.tgz
24 verbose request uri https://registry.npmjs.org/xlib
25 verbose request sending authorization for write operation
26 info attempt registry request try #1 at 5:02:20 PM
27 verbose request using bearer token for auth
28 verbose request id 6db442a727f61ddf
29 http request PUT https://registry.npmjs.org/xlib
30 http 503 https://registry.npmjs.org/xlib
31 verbose bad json <?xml version="1.0" encoding="utf-8"?>
31 verbose bad json <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
31 verbose bad json  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
31 verbose bad json <html>
31 verbose bad json   <head>
31 verbose bad json     <title>503 backend read error</title>
31 verbose bad json   </head>
31 verbose bad json   <body>
31 verbose bad json     <h1>Error 503 backend read error</h1>
31 verbose bad json     <p>backend read error</p>
31 verbose bad json     <h3>Guru Mediation:</h3>
31 verbose bad json     <p>Details: cache-sjc3132-SJC 1429574716 1171039701</p>
31 verbose bad json     <hr>
31 verbose bad json     <p>Varnish cache server</p>
31 verbose bad json   </body>
31 verbose bad json </html>
32 error registry error parsing json
33 info retry will retry, error on last attempt: SyntaxError: Unexpected token <
33 info retry
33 info retry <?xml version="1.0" encoding="utf-8"?>
33 info retry <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
33 info retry  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
33 info retry <html>
33 info retry   <head>
33 info retry     <title>503 backend read error</title>
33 info retry   </head>
33 info retry   <body>
33 info retry     <h1>Error 503 backend read error</h1>
33 info retry     <p>backend read error</p>
33 info retry     <h3>Guru Mediation:</h3>
33 info retry     <p>Details: cache-sjc3132-SJC 1429574716 1171039701</p>
33 info retry     <hr>
33 info retry     <p>Varnish cache server</p>
33 info retry   </body>
33 info retry </html>
34 info attempt registry request try #2 at 5:05:26 PM
35 verbose request using bearer token for auth
36 http request PUT https://registry.npmjs.org/xlib
37 http 503 https://registry.npmjs.org/xlib
38 verbose bad json <?xml version="1.0" encoding="utf-8"?>
38 verbose bad json <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
38 verbose bad json  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
38 verbose bad json <html>
38 verbose bad json   <head>
38 verbose bad json     <title>503 backend read error</title>
38 verbose bad json   </head>
38 verbose bad json   <body>
38 verbose bad json     <h1>Error 503 backend read error</h1>
38 verbose bad json     <p>backend read error</p>
38 verbose bad json     <h3>Guru Mediation:</h3>
38 verbose bad json     <p>Details: cache-sjc3129-SJC 1429574903 2944905424</p>
38 verbose bad json     <hr>
38 verbose bad json     <p>Varnish cache server</p>
38 verbose bad json   </body>
38 verbose bad json </html>
39 error registry error parsing json
40 info retry will retry, error on last attempt: SyntaxError: Unexpected token <
40 info retry
40 info retry <?xml version="1.0" encoding="utf-8"?>
40 info retry <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
40 info retry  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
40 info retry <html>
40 info retry   <head>
40 info retry     <title>503 backend read error</title>
40 info retry   </head>
40 info retry   <body>
40 info retry     <h1>Error 503 backend read error</h1>
40 info retry     <p>backend read error</p>
40 info retry     <h3>Guru Mediation:</h3>
40 info retry     <p>Details: cache-sjc3129-SJC 1429574903 2944905424</p>
40 info retry     <hr>
40 info retry     <p>Varnish cache server</p>
40 info retry   </body>
40 info retry </html>
41 info attempt registry request try #3 at 5:09:23 PM
42 verbose request using bearer token for auth
43 http request PUT https://registry.npmjs.org/xlib
44 http 503 https://registry.npmjs.org/xlib
45 verbose bad json <?xml version="1.0" encoding="utf-8"?>
45 verbose bad json <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
45 verbose bad json  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
45 verbose bad json <html>
45 verbose bad json   <head>
45 verbose bad json     <title>503 backend read error</title>
45 verbose bad json   </head>
45 verbose bad json   <body>
45 verbose bad json     <h1>Error 503 backend read error</h1>
45 verbose bad json     <p>backend read error</p>
45 verbose bad json     <h3>Guru Mediation:</h3>
45 verbose bad json     <p>Details: cache-lax1430-LAX 1429575140 815904340</p>
45 verbose bad json     <hr>
45 verbose bad json     <p>Varnish cache server</p>
45 verbose bad json   </body>
45 verbose bad json </html>
46 error registry error parsing json
47 verbose headers { date: 'Tue, 21 Apr 2015 00:12:20 GMT',
47 verbose headers   server: 'Varnish',
47 verbose headers   'retry-after': '0',
47 verbose headers   'content-type': 'text/html; charset=utf-8',
47 verbose headers   'content-length': '447',
47 verbose headers   'accept-ranges': 'bytes',
47 verbose headers   via: '1.1 varnish',
47 verbose headers   'x-served-by': 'cache-lax1430-LAX',
47 verbose headers   'x-cache': 'MISS',
47 verbose headers   'x-cache-hits': '0',
47 verbose headers   'x-timer': 'S1429574966.765639,VS0,VE173798',
47 verbose headers   connection: 'close' }
48 verbose request invalidating C:\Users\Jason\AppData\Roaming\npm-cache\registry.npmjs.org\xlib on PUT
49 error publish Failed PUT 503
50 verbose stack SyntaxError: Unexpected token <
50 verbose stack
50 verbose stack <?xml version="1.0" encoding="utf-8"?>
50 verbose stack <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
50 verbose stack  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
50 verbose stack <html>
50 verbose stack   <head>
50 verbose stack     <title>503 backend read error</title>
50 verbose stack   </head>
50 verbose stack   <body>
50 verbose stack     <h1>Error 503 backend read error</h1>
50 verbose stack     <p>backend read error</p>
50 verbose stack     <h3>Guru Mediation:</h3>
50 verbose stack     <p>Details: cache-lax1430-LAX 1429575140 815904340</p>
50 verbose stack     <hr>
50 verbose stack     <p>Varnish cache server</p>
50 verbose stack   </body>
50 verbose stack </html>
50 verbose stack
50 verbose stack     at Object.parse (native)
50 verbose stack     at CachingRegistryClient.<anonymous> (C:\Users\Jason\AppData\Roaming\npm\node_modules\npm\node_modules\npm-registry-client\lib\request.js:197:23)
50 verbose stack     at Request._callback (C:\Users\Jason\AppData\Roaming\npm\node_modules\npm\node_modules\npm-registry-client\lib\request.js:170:14)
50 verbose stack     at Request.self.callback (C:\Users\Jason\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.js:368:22)
50 verbose stack     at Request.emit (events.js:110:17)
50 verbose stack     at Request.<anonymous> (C:\Users\Jason\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.js:1219:14)
50 verbose stack     at Request.emit (events.js:129:20)
50 verbose stack     at IncomingMessage.<anonymous> (C:\Users\Jason\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.js:1167:12)
50 verbose stack     at IncomingMessage.emit (events.js:129:20)
50 verbose stack     at _stream_readable.js:908:16
51 verbose cwd C:\repos\xlib
52 error Windows_NT 6.3.9600
53 error argv "node" "C:\\Users\\Jason\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "publish"
54 error node v0.12.2
55 error npm  v2.8.3
56 error Unexpected token <
56 error
56 error <?xml version="1.0" encoding="utf-8"?>
56 error <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
56 error  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
56 error <html>
56 error   <head>
56 error     <title>503 backend read error</title>
56 error   </head>
56 error   <body>
56 error     <h1>Error 503 backend read error</h1>
56 error     <p>backend read error</p>
56 error     <h3>Guru Mediation:</h3>
56 error     <p>Details: cache-lax1430-LAX 1429575140 815904340</p>
56 error     <hr>
56 error     <p>Varnish cache server</p>
56 error   </body>
56 error </html>
57 error If you need help, you may report this error at:
57 error     <https://github.com/npm/npm/issues>
58 verbose exit [ 1, true ]

```

**Comment by jasonswearingen** [comment]
i tried bumping the version and no luck

**Comment by jasonswearingen** [comment]
so, found out it's because i had a big binary file in global ignore, causing my publish to be about 500mb.   so added that to local .gitignore and now publishes fine.
