### ISSUE TITLE
Error When I Try to Install Express Generator

### ISSUE THREAD

**Issue by nbalcom** [npm/npm#8026]
I've been trying to get Node up and running to build my first application and have been following several tutorials, but I seem to be getting the same type error. 

Here's my npm-debug.log file
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'expression-generator' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 silly cache add args [ 'expression-generator', null ]
6 verbose cache add spec expression-generator
7 silly cache add parsed spec { raw: 'expression-generator',
7 silly cache add   scope: null,
7 silly cache add   name: 'expression-generator',
7 silly cache add   rawSpec: '',
7 silly cache add   spec: '*',
7 silly cache add   type: 'range' }
8 verbose addNamed expression-generator@*
9 silly addNamed semver.valid null
10 silly addNamed semver.validRange *
11 silly addNameRange { name: 'expression-generator', range: '*', hasData: false }
12 silly mapToRegistry name expression-generator
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/expression-generator
16 verbose addNameRange registry:https://registry.npmjs.org/expression-generator not in flight; fetching
17 verbose request uri https://registry.npmjs.org/expression-generator
18 verbose request no auth needed
19 info attempt registry request try #1 at 9:31:13 AM
20 verbose request id 7983b5331e2ed528
21 http request GET https://registry.npmjs.org/expression-generator
22 verbose stack Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
22 verbose stack     at Error (native)
22 verbose stack     at Object.createSecureContext (_tls_common.js:108:19)
22 verbose stack     at Object.exports.connect (_tls_wrap.js:852:21)
22 verbose stack     at Agent.createConnection (https.js:82:14)
22 verbose stack     at Agent.createSocket (_http_agent.js:194:16)
22 verbose stack     at Agent.addRequest (_http_agent.js:166:23)
22 verbose stack     at new ClientRequest (_http_client.js:154:16)
22 verbose stack     at Object.exports.request (http.js:49:10)
22 verbose stack     at Object.exports.request (https.js:136:15)
22 verbose stack     at Request.start (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:904:30)
23 verbose cwd C:\Users\T1777NB
24 error Windows_NT 6.1.7601
25 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "expression-generator"
26 error node v0.12.2
27 error npm  v2.7.4
28 error error:0906D06C:PEM routines:PEM_read_bio:no start line
29 error If you need help, you may report this error at:
29 error     <https://github.com/npm/npm/issues>
30 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
@nbalcom Hmm, looks like an SSL issue. Are you behind a proxy by any chance?

**Comment by nbalcom** [comment]
Yes I am. I didn't even think of that. Is there a way around that?

**Comment by KenanY** [comment]
@nbalcom You should configure `npm` to use the proxy:

  - [`proxy`](https://docs.npmjs.com/misc/config#proxy)
  - [`https-proxy`](https://docs.npmjs.com/misc/config#https-proxy)
  - [`cafile`](https://docs.npmjs.com/misc/config#cafile)

**Comment by nbalcom** [comment]
I have started down the road of changing my environment variables and am now getting an error that looks like this. 

![error](https://cloud.githubusercontent.com/assets/5503973/7259306/69fb44b6-e830-11e4-98e9-d9e3418862db.jpg)

It looks like I have some sort of formatting issue, but at least it's trying to run. So I think I'm getting closer. Does this mean anything to anybody?

**Comment by ehsalazar** [comment]
We hope you've been able to get beyond the connection issues. We haven’t heard back in a while and we’re trying to clean up some old issues. If this is still a problem, can you please reply and let us know? We’ll be happy to reopen if necessary.

**Comment by nbalcom** [comment]
Sorry ehsalazar yes I did. Been so busy as of late. Thanks for closing.
