### ISSUE TITLE
"npm ERR! missing:" and "UNMET DEPENDENCY" errors when updating globally

### ISSUE THREAD

**Issue by DJviolin** [npm/npm#8038]
Installation times incredibly slow.

Probably the error is on my own end, because npm server status looks healthy:
http://status.npmjs.org/

When I try to install a package with "$ npm install -g ...", I got this error log:

npm-debug.log

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'bower' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 silly cache add args [ 'bower', null ]
6 verbose cache add spec bower
7 silly cache add parsed spec { raw: 'bower',
7 silly cache add   scope: null,
7 silly cache add   name: 'bower',
7 silly cache add   rawSpec: '',
7 silly cache add   spec: '*',
7 silly cache add   type: 'range' }
8 verbose addNamed bower@*
9 silly addNamed semver.valid null
10 silly addNamed semver.validRange *
11 silly addNameRange { name: 'bower', range: '*', hasData: false }
12 silly mapToRegistry name bower
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/bower
16 verbose addNameRange registry:https://registry.npmjs.org/bower not in flight; fetching
17 verbose request uri https://registry.npmjs.org/bower
18 verbose request no auth needed
19 info attempt registry request try #1 at 20:46:06
20 verbose request id c1f93a16783d7885
21 http request GET https://registry.npmjs.org/bower
22 http 200 https://registry.npmjs.org/bower
23 silly get cb [ 200,
23 silly get   { date: 'Wed, 22 Apr 2015 18:46:14 GMT',
23 silly get     server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
23 silly get     etag: '"98DLCRQ07FTPJ7UQTSIEM7GS"',
23 silly get     'content-type': 'application/json',
23 silly get     'cache-control': 'max-age=60',
23 silly get     'content-length': '111782',
23 silly get     'accept-ranges': 'bytes',
23 silly get     via: '1.1 varnish',
23 silly get     age: '1',
23 silly get     'x-served-by': 'cache-fra1223-FRA',
23 silly get     'x-cache': 'HIT',
23 silly get     'x-cache-hits': '1',
23 silly get     'x-timer': 'S1429728374.214320,VS0,VE0',
23 silly get     vary: 'Accept',
23 silly get     'keep-alive': 'timeout=10, max=50',
23 silly get     connection: 'Keep-Alive' } ]
24 verbose get saving bower to C:\Users\Lanti\AppData\Roaming\npm-cache\registry.npmjs.org\bower\.cache.json
25 verbose getCacheStat cache creation not in flight; initializing
26 verbose makeCacheDir UID & GID are irrelevant on win32
27 silly addNameRange number 2 { name: 'bower', range: '*', hasData: true }
28 silly addNameRange versions [ 'bower',
28 silly addNameRange   [ '0.1.0',
28 silly addNameRange     '0.1.2',
28 silly addNameRange     '0.1.3',
28 silly addNameRange     '0.2.0',
28 silly addNameRange     '0.3.0',
28 silly addNameRange     '0.3.1',
28 silly addNameRange     '0.3.2',
28 silly addNameRange     '0.4.0',
28 silly addNameRange     '0.5.0',
28 silly addNameRange     '0.5.1',
28 silly addNameRange     '0.6.0',
28 silly addNameRange     '0.6.1',
28 silly addNameRange     '0.6.2',
28 silly addNameRange     '0.6.3',
28 silly addNameRange     '0.6.4',
28 silly addNameRange     '0.6.5',
28 silly addNameRange     '0.6.6',
28 silly addNameRange     '0.6.7',
28 silly addNameRange     '0.6.8',
28 silly addNameRange     '0.7.0',
28 silly addNameRange     '0.7.1',
28 silly addNameRange     '0.8.0',
28 silly addNameRange     '0.8.1',
28 silly addNameRange     '0.8.2',
28 silly addNameRange     '0.8.3',
28 silly addNameRange     '0.8.4',
28 silly addNameRange     '0.8.5',
28 silly addNameRange     '0.8.6',
28 silly addNameRange     '0.9.0',
28 silly addNameRange     '0.9.1',
28 silly addNameRange     '0.9.2',
28 silly addNameRange     '0.10.0',
28 silly addNameRange     '1.0.0',
28 silly addNameRange     '1.0.1',
28 silly addNameRange     '1.0.2',
28 silly addNameRange     '1.0.3',
28 silly addNameRange     '1.1.0',
28 silly addNameRange     '1.1.1',
28 silly addNameRange     '1.1.2',
28 silly addNameRange     '1.2.0',
28 silly addNameRange     '1.2.1',
28 silly addNameRange     '1.2.2',
28 silly addNameRange     '1.2.3',
28 silly addNameRange     '1.2.4',
28 silly addNameRange     '1.2.5',
28 silly addNameRange     '1.2.6',
28 silly addNameRange     '1.2.7',
28 silly addNameRange     '1.2.8',
28 silly addNameRange     '1.3.0',
28 silly addNameRange     '1.3.1',
28 silly addNameRange     '1.3.2',
28 silly addNameRange     '1.3.3',
28 silly addNameRange     '1.3.4',
28 silly addNameRange     '1.3.5',
28 silly addNameRange     '1.3.6',
28 silly addNameRange     '1.3.7',
28 silly addNameRange     '1.3.8',
28 silly addNameRange     '1.3.9',
28 silly addNameRange     '1.3.10',
28 silly addNameRange     '1.3.11',
28 silly addNameRange     '1.3.12',
28 silly addNameRange     '1.4.0',
28 silly addNameRange     '1.4.1' ] ]
29 verbose addNamed bower@1.4.1
30 silly addNamed semver.valid 1.4.1
31 silly addNamed semver.validRange 1.4.1
32 silly mapToRegistry name bower
33 silly mapToRegistry using default registry
34 silly mapToRegistry registry https://registry.npmjs.org/
35 silly mapToRegistry uri https://registry.npmjs.org/bower
36 verbose addRemoteTarball https://registry.npmjs.org/bower/-/bower-1.4.1.tgz not in flight; adding
37 verbose addRemoteTarball [ 'https://registry.npmjs.org/bower/-/bower-1.4.1.tgz',
37 verbose addRemoteTarball   'a18be39d030792754f30f1c5b32d37b0156ba8dd' ]
38 info retry fetch attempt 1 at 20:46:24
39 info attempt registry request try #1 at 20:46:24
40 http fetch GET https://registry.npmjs.org/bower/-/bower-1.4.1.tgz
41 http fetch 200 https://registry.npmjs.org/bower/-/bower-1.4.1.tgz
42 silly fetchAndShaCheck shasum a18be39d030792754f30f1c5b32d37b0156ba8dd
43 verbose stack Error: shasum check failed for C:\Users\Lanti\AppData\Local\Temp\npm-8060-e84e3e40\registry.npmjs.org\bower\-\bower-1.4.1.tgz
43 verbose stack Expected: a18be39d030792754f30f1c5b32d37b0156ba8dd
43 verbose stack Actual:   b4e378513fe60f1bd041848479c797e6550324ce
43 verbose stack From:     https://registry.npmjs.org/bower/-/bower-1.4.1.tgz
43 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\sha\index.js:38:8
43 verbose stack     at ReadStream.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\sha\index.js:85:7)
43 verbose stack     at ReadStream.emit (events.js:129:20)
43 verbose stack     at _stream_readable.js:908:16
43 verbose stack     at process._tickCallback (node.js:355:11)
44 verbose cwd C:\www
45 error Windows_NT 6.1.7601
46 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "bower"
47 error node v0.12.2
48 error npm  v2.7.4
49 error shasum check failed for C:\Users\Lanti\AppData\Local\Temp\npm-8060-e84e3e40\registry.npmjs.org\bower\-\bower-1.4.1.tgz
49 error Expected: a18be39d030792754f30f1c5b32d37b0156ba8dd
49 error Actual:   b4e378513fe60f1bd041848479c797e6550324ce
49 error From:     https://registry.npmjs.org/bower/-/bower-1.4.1.tgz
50 error If you need help, you may report this error at:
50 error     <https://github.com/npm/npm/issues>
51 verbose exit [ 1, true ]

Opening the files in browser to download is fast, then download speed is slow, even in browser. Torrent, video download speed is 2mb/s.

**Comment by DJviolin** [comment]
Solved. It was ISP, ipconfig, wifi problem. Switching to LAN cable solved it.
