### ISSUE TITLE
The requested URL returned error: 502

### ISSUE THREAD

**Issue by alexandarp** [npm/npm#8041]
Hi,

Throughout the day, I will randomly get 502 errors when doing an ```npm install```. I am not sure if this is a problem with bitbucket or npm, I would like to find out for sure. I am using ```npm v2.8.3``` and ```node v0.10.36``` 

Here is the output from Jenkins:

```
npm ERR! Linux 3.17.2+
npm ERR! argv "node" "/home/jenkins/.nvm/v0.10.36/bin/npm" "install"
npm ERR! node v0.10.36
npm ERR! npm  v2.8.3
npm ERR! code 128

npm ERR! Command failed: Cloning into bare repository '/home/jenkins/.npm/repo
npm ERR! fatal: unable to access 'https:/user:pass@bitbucket.org/repo.git/': The requested URL returned error: 502
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

Usually it isn't a problem, but I noticed that it occurs more often in the morning. Any help would be appreciated.

**Comment by alexandarp** [comment]
I am going to try ```npm install --loglevel silly``` to see if I can narrow down the problem.

**Comment by alexandarp** [comment]
With --loglevel silly:

```
npm verb stack Error: Command failed: Cloning into bare repository '/home/jenkins/.npm/_git-remotes/https-repo-git'
npm verb stack fatal: unable to access 'https://user:pass@bitbucket.org/user/repo.git/': The requested URL returned error: 502
npm verb stack 
npm verb stack     at ChildProcess.exithandler (child_process.js:658:15)
npm verb stack     at ChildProcess.emit (events.js:98:17)
npm verb stack     at maybeClose (child_process.js:766:16)
npm verb stack     at Socket.<anonymous> (child_process.js:979:11)
npm verb stack     at Socket.emit (events.js:95:17)
npm verb stack     at Pipe.close (net.js:466:12)
npm verb cwd /home/jenkins/workspace/repo
npm ERR! Linux 3.17.2+
npm ERR! argv "node" "/home/jenkins/.nvm/v0.10.36/bin/npm" "install" "--loglevel" "silly"
npm ERR! node v0.10.36
npm ERR! npm  v2.8.3
npm ERR! code 128

npm ERR! Command failed: Cloning into bare repository '/home/jenkins/.npm/_git-remotes/https-user-pass-bitbucket-org-repo-git'
npm ERR! fatal: unable to access 'https://user:pass@bitbucket.org/user/repo.git/': The requested URL returned error: 502
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm verb exit [ 1, true ]
```

It's starting to occur again this morning.

**Comment by othiym23** [comment]
```
npm ERR! fatal: unable to access 'https://user:pass@bitbucket.org/user/repo.git/': The requested URL returned error: 502
```

That indicates pretty conclusively that one of BitBucket's web servers is returning a 502 when git tries to fetch the repository. This isn't something that npm can do anything about, unfortunately.

**Comment by alexandarp** [comment]
Thanks, I actually spoke with Bitbucket support and they are currently having some capacity issues. I've been having the error on and off for the past month, hopefully they fix it soon.
