### ISSUE TITLE
errors aren't being handled from all of the readPackageTree callbacks

### ISSUE THREAD

**Issue by othiym23** [npm/npm#8043]
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/iojs', '/usr/local/bin/npm', 'outdated', '-g' ]
2 info using npm@3.0.0-pre.6
3 info using node@v1.7.1
4 verbose stack TypeError: Cannot read property '_requiredBy' of null
4 verbose stack     at /Users/ogd/Documents/projects/npm/npm/lib/install/logical-tree.js:17:34
4 verbose stack     at Array.forEach (native)
4 verbose stack     at module.exports (/Users/ogd/Documents/projects/npm/npm/lib/install/logical-tree.js:15:28)
4 verbose stack     at /Users/ogd/Documents/projects/npm/npm/lib/outdated.js:67:16
4 verbose stack     at /Users/ogd/Documents/projects/npm/npm/node_modules/read-package-tree/rpt.js:175:9
4 verbose stack     at f (/Users/ogd/Documents/projects/npm/npm/node_modules/once/once.js:17:25)
4 verbose stack     at then (/Users/ogd/Documents/projects/npm/npm/node_modules/read-package-tree/rpt.js:161:22)
4 verbose stack     at f (/Users/ogd/Documents/projects/npm/npm/node_modules/once/once.js:17:25)
4 verbose stack     at then (/Users/ogd/Documents/projects/npm/npm/node_modules/read-package-tree/rpt.js:161:22)
4 verbose stack     at f (/Users/ogd/Documents/projects/npm/npm/node_modules/once/once.js:17:25)
5 verbose cwd /Users/ogd/Documents/projects/npm/npm
6 error Darwin 14.3.0
7 error argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "outdated" "-g"
8 error node v1.7.1
9 error npm  v3.0.0-pre.6
10 error Cannot read property '_requiredBy' of null
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
```

**Comment by iarna** [comment]
Well, just any global tree created by `npm@2`... read-package-tree returned a tree with some missing package entries. It can do that at the top level, but children are supposed to trigger an abort. And either way it's supposed produce an error and oh hi, the readPackageTree call in outdated ignores its error argument.

TODO: Verify that errors are being handled from all of the readPackageTree callbacks.

**Comment by thefourtheye** [comment]
How can I reproduce this problem?

**Comment by othiym23** [comment]
@iarna I've retitled the issue to reflect the underlying problem

@thefourtheye when I figure out which packages are causing this problem, I'll let you know if there's an easy repro case you can play with

**Comment by iarna** [comment]
thefourtheye: I've got issue in hand– fixing it uncovered yet further things, this time a subtle bug in shrinkwrap loading. But! Once that's fixed, then `test/run.js` will be fully passing!

**Comment by iarna** [comment]
Closing as fixed as of... a bunch of commits– 6844b5c anyway.
