### ISSUE TITLE
Publish failed PUT 500  + Unexpected status code : 400

### ISSUE THREAD

**Issue by alvarotrigo** [npm/npm#8047]
Having troubles publishing a package:

```
npm ERR! publish Failed PUT 500
npm ERR! Error: unexpected status code: 400 : fullPage.js
npm ERR!     at RegClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\
node_modules\npm-registry-client\lib\request.js:274:14)
npm ERR!     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node
_modules\npm-registry-client\lib\request.js:212:65)
npm ERR!     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\
node_modules\request\request.js:123:22)
npm ERR!     at Request.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\no
de_modules\request\request.js:893:14)
npm ERR!     at Request.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_module
s\npm\node_modules\request\request.js:844:12)
npm ERR!     at IncomingMessage.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:929:16
npm ERR!     at process._tickCallback (node.js:419:13)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "publish"
npm ERR! cwd C:\Users\xxxxx\Desktop\jquery.fullPage\trunk
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\xxxxx\Desktop\jquery.fullPage\trunk\npm-debug.log
npm ERR! not ok code 0
```

**Comment by othiym23** [comment]
Package names can't include upper-case letters. Also, you're running a pretty old version of npm, and should probably [upgrade](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm).

**Comment by RoberMac** [comment]
@othiym23 thx!

**Comment by alvarotrigo** [comment]
Thanks!
