### ISSUE TITLE
Can't publish new module to my scope

### ISSUE THREAD

**Issue by corbinu** [npm/npm#8059]
I am trying to commit this repo to my scope https://github.com/corbinu/agenda-persistence-mongoskin

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/iojs',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'publish',
1 verbose cli   '--access=public' ]
2 info using npm@2.8.3
3 info using node@v1.8.1
4 verbose publish [ '.' ]
5 silly cache add args [ '.', null ]
6 verbose cache add spec .
7 silly cache add parsed spec { raw: '.',
7 silly cache add   scope: null,
7 silly cache add   name: null,
7 silly cache add   rawSpec: '.',
7 silly cache add   spec: '/Users/corbinu/Developer/git/agenda-persistence-mongoskin',
7 silly cache add   type: 'directory' }
8 verbose addLocalDirectory /Users/corbinu/.npm/@corbin/agenda-persistence-mongoskin/0.1.0/package.tgz not in flight; packing
9 verbose tar pack [ '/Users/corbinu/.npm/@corbin/agenda-persistence-mongoskin/0.1.0/package.tgz',
9 verbose tar pack   '/Users/corbinu/Developer/git/agenda-persistence-mongoskin' ]
10 verbose tarball /Users/corbinu/.npm/@corbin/agenda-persistence-mongoskin/0.1.0/package.tgz
11 verbose folder /Users/corbinu/Developer/git/agenda-persistence-mongoskin
12 info prepublish @corbin/agenda-persistence-mongoskin@0.1.0
13 verbose addLocalTarball adding from inside cache /Users/corbinu/.npm/@corbin/agenda-persistence-mongoskin/0.1.0/package.tgz
14 silly cache afterAdd @corbin/agenda-persistence-mongoskin@0.1.0
15 verbose afterAdd /Users/corbinu/.npm/@corbin/agenda-persistence-mongoskin/0.1.0/package/package.json not in flight; writing
16 verbose afterAdd /Users/corbinu/.npm/@corbin/agenda-persistence-mongoskin/0.1.0/package/package.json written
17 silly publish { name: '@corbin/agenda-persistence-mongoskin',
17 silly publish   version: '0.1.0',
17 silly publish   description: 'Mongoskin persistence for Agenda Light weight job scheduler',
17 silly publish   main: 'index.js',
17 silly publish   scripts:
17 silly publish    { lab: 'lab --coverage --threshold 80 --leaks',
17 silly publish      eslint: 'eslint .',
17 silly publish      test: 'npm run eslint && npm run lab' },
17 silly publish   repository:
17 silly publish    { type: 'git',
17 silly publish      url: 'git://github.com/corbinu/agenda-persistence-mongoskin.git' },
17 silly publish   keywords: [ 'agenda', 'persistence' ],
17 silly publish   author: { name: 'Corbin Uselton', email: 'corbinu@decimal.io' },
17 silly publish   license: 'MIT',
17 silly publish   bugs: { url: 'https://github.com/corbinu/agenda-persistence-mongoskin' },
17 silly publish   dependencies: { mongoskin: '^1.4.1' },
17 silly publish   devDependencies: { eslint: '^0.19.0', lab: '^5.6.0', code: '^1.4.0' },
17 silly publish   readme: '# Agenda Persistence Mongoskin\n[Agenda](https://github.com/rschmukler/agenda) persistence layer using Mongoskin\n\n# Installation\n\nInstall via NPM\n\n    npm install agenda agenda-persistence-mongoskin\n\nYou will also need a working [mongo](http://www.mongodb.org/) database (2.4+) to point it to.\n\n# Example Usage\n\n```js\n\nvar Agenda = require(\'agenda\');\n\nvar Persistence = require(\'agenda-persistence-mongoskin\');\n\nvar agenda = new Agenda(new Persistence({ address: \'localhost:27017/agenda-example\'}));\n\nagenda.define(\'delete old users\', function(job, done) {\n  User.remove({lastLogIn: { $lt: twoDaysAgo }}, done);\n});\n\nagenda.every(\'3 minutes\', \'delete old users\');\n\n// Alternatively, you could also do:\n\nagenda.every(\'*/3 * * * *\', \'delete old users\');\n\nagenda.start();\n```\n\n# License\nMIT\n\nCopyright (c) 2015 Corbin Uselton\n\nPermission is hereby granted, free of charge, to any person obtaining a copy of\nthis software and associated documentation files (the \'Software\'), to deal in\nthe Software without restriction, including without limitation the rights to\nuse, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of\nthe Software, and to permit persons to whom the Software is furnished to do so,\nsubject to the following conditions:\n\nThe above copyright notice and this permission notice shall be included in all\ncopies or substantial portions of the Software.\n\nTHE SOFTWARE IS PROVIDED \'AS IS\', WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\nIMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS\nFOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR\nCOPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER\nIN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN\nCONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.\n',
17 silly publish   readmeFilename: 'README.md',
17 silly publish   gitHead: '83586e61e1cf4fe78b8a24dfc44694af0dc122f5',
17 silly publish   homepage: 'https://github.com/corbinu/agenda-persistence-mongoskin#readme',
17 silly publish   _id: '@corbin/agenda-persistence-mongoskin@0.1.0',
17 silly publish   _shasum: '6b439073526d5cc7a6a12db83e21f546d99d33e1',
17 silly publish   _from: '.' }
18 silly mapToRegistry name @corbin/agenda-persistence-mongoskin
19 silly mapToRegistry scope (from package name) @corbin
20 verbose mapToRegistry no registry URL found in name for scope @corbin
21 silly mapToRegistry using default registry
22 silly mapToRegistry registry https://registry.npmjs.org/
23 silly mapToRegistry uri https://registry.npmjs.org/@corbin%2fagenda-persistence-mongoskin
24 verbose publish registryBase https://registry.npmjs.org/
25 silly publish uploading /Users/corbinu/.npm/@corbin/agenda-persistence-mongoskin/0.1.0/package.tgz
26 verbose request uri https://registry.npmjs.org/@corbin%2fagenda-persistence-mongoskin
27 verbose request sending authorization for write operation
28 info attempt registry request try #1 at 01:13:25
29 verbose request using bearer token for auth
30 verbose request id 40e696ea90f72098
31 http request PUT https://registry.npmjs.org/@corbin%2fagenda-persistence-mongoskin
32 http 500 https://registry.npmjs.org/@corbin%2fagenda-persistence-mongoskin
33 info retry will retry, error on last attempt: Error: unexpected status code: 404 : @corbin%2fagenda-persistence-mongoskin
34 info attempt registry request try #2 at 01:13:35
35 verbose request using bearer token for auth
36 http request PUT https://registry.npmjs.org/@corbin%2fagenda-persistence-mongoskin
37 http 500 https://registry.npmjs.org/@corbin%2fagenda-persistence-mongoskin
38 info retry will retry, error on last attempt: Error: unexpected status code: 404 : @corbin%2fagenda-persistence-mongoskin
39 info attempt registry request try #3 at 01:14:36
40 verbose request using bearer token for auth
41 http request PUT https://registry.npmjs.org/@corbin%2fagenda-persistence-mongoskin
42 http 500 https://registry.npmjs.org/@corbin%2fagenda-persistence-mongoskin
43 verbose headers { date: 'Fri, 24 Apr 2015 08:14:37 GMT',
43 verbose headers   server: 'Apache',
43 verbose headers   'content-type': 'application/json',
43 verbose headers   'cache-control': 'max-age=0',
43 verbose headers   'content-length': '39',
43 verbose headers   'accept-ranges': 'bytes',
43 verbose headers   via: '1.1 varnish',
43 verbose headers   'x-served-by': 'cache-lax1435-LAX',
43 verbose headers   'x-cache': 'MISS',
43 verbose headers   'x-cache-hits': '0',
43 verbose headers   'x-timer': 'S1429863276.636467,VS0,VE974',
43 verbose headers   connection: 'close' }
44 verbose request invalidating /Users/corbinu/.npm/registry.npmjs.org/_40corbin_252fagenda-persistence-mongoskin on PUT
45 error publish Failed PUT 500
46 verbose stack Error: unexpected status code: 404 : @corbin%2fagenda-persistence-mongoskin
46 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:247:14)
46 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:170:14)
46 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:368:22)
46 verbose stack     at emitTwo (events.js:87:13)
46 verbose stack     at Request.emit (events.js:169:7)
46 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1219:14)
46 verbose stack     at emitOne (events.js:82:20)
46 verbose stack     at Request.emit (events.js:166:7)
46 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1167:12)
46 verbose stack     at emitNone (events.js:72:20)
47 verbose statusCode 500
48 verbose pkgid @corbin%2fagenda-persistence-mongoskin
49 verbose cwd /Users/corbinu/Developer/git/agenda-persistence-mongoskin
50 error Darwin 14.3.0
51 error argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "publish" "--access=public"
52 error node v1.8.1
53 error npm  v2.8.3
54 error code E500
55 error unexpected status code: 404 : @corbin%2fagenda-persistence-mongoskin
56 error If you need help, you may report this error at:
56 error     <https://github.com/npm/npm/issues>
57 verbose exit [ 1, true ]
```

**Comment by wojciak** [comment]
+1

**Comment by epsitec** [comment]
Did you somehow change your credentials (user name or password) on npmjs.com?

**Comment by corbinu** [comment]
Yes I changed my password at while back but since and relogged in via the npm client

**Comment by corbinu** [comment]
So I can do other publishes. Just did @corbinu/couchbase

Not sure what is up just rechecked and still not working with iojs 2.0.1

**Comment by corbinu** [comment]
Solved

**Comment by cwharris** [comment]
Mind sharing how you solved this?
