### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by sebastianmusial** [npm/npm#8073]
Hi,
When I run the command "npm install" I have this problem:

```
0 info it worked if it ends with ok
1 verbose cli [ 'c:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 verbose install where, deps [ 'd:\\Websites\\tombar\\web\\wp-content\\themes\\roots',
4 verbose install   [ 'bower',
4 verbose install     'grunt',
4 verbose install     'grunt-autoprefixer',
4 verbose install     'grunt-contrib-concat',
4 verbose install     'grunt-contrib-jshint',
4 verbose install     'grunt-contrib-sass',
4 verbose install     'grunt-contrib-uglify',
4 verbose install     'grunt-contrib-watch',
4 verbose install     'grunt-modernizr',
4 verbose install     'grunt-wp-assets',
4 verbose install     'load-grunt-tasks',
4 verbose install     'time-grunt' ] ]
5 verbose install where, peers [ 'd:\\Websites\\tombar\\web\\wp-content\\themes\\roots', [] ]
6 info preinstall roots@7.0.1
7 verbose already installed skipping grunt-modernizr@~0.5.2 d:\Websites\tombar\web\wp-content\themes\roots
8 verbose already installed skipping grunt-wp-assets@~0.2.6 d:\Websites\tombar\web\wp-content\themes\roots
9 verbose already installed skipping load-grunt-tasks@~0.6.0 d:\Websites\tombar\web\wp-content\themes\roots
10 verbose already installed skipping time-grunt@~0.4.0 d:\Websites\tombar\web\wp-content\themes\roots
11 verbose already installed skipping bower@>=1.3.9 d:\Websites\tombar\web\wp-content\themes\roots
12 verbose already installed skipping grunt@~0.4.5 d:\Websites\tombar\web\wp-content\themes\roots
13 verbose already installed skipping grunt-autoprefixer@~1.0.0 d:\Websites\tombar\web\wp-content\themes\roots
14 verbose already installed skipping grunt-contrib-concat@~0.5.0 d:\Websites\tombar\web\wp-content\themes\roots
15 verbose already installed skipping grunt-contrib-jshint@~0.10.0 d:\Websites\tombar\web\wp-content\themes\roots
16 verbose already installed skipping grunt-contrib-sass@~0.7.3 d:\Websites\tombar\web\wp-content\themes\roots
17 verbose already installed skipping grunt-contrib-uglify@~0.5.0 d:\Websites\tombar\web\wp-content\themes\roots
18 verbose already installed skipping grunt-contrib-watch@~0.6.1 d:\Websites\tombar\web\wp-content\themes\roots
19 silly install resolved []
20 info build d:\Websites\tombar\web\wp-content\themes\roots
21 verbose linkStuff [ false,
21 verbose linkStuff   false,
21 verbose linkStuff   false,
21 verbose linkStuff   'd:\\Websites\\tombar\\web\\wp-content\\themes' ]
22 info linkStuff roots@7.0.1
23 verbose linkBins roots@7.0.1
24 verbose linkMans roots@7.0.1
25 verbose rebuildBundles roots@7.0.1
26 verbose rebuildBundles [ '.bin',
26 verbose rebuildBundles   'bower',
26 verbose rebuildBundles   'grunt',
26 verbose rebuildBundles   'grunt-autoprefixer',
26 verbose rebuildBundles   'grunt-contrib-concat',
26 verbose rebuildBundles   'grunt-contrib-jshint',
26 verbose rebuildBundles   'grunt-contrib-sass',
26 verbose rebuildBundles   'grunt-contrib-uglify',
26 verbose rebuildBundles   'grunt-contrib-watch',
26 verbose rebuildBundles   'grunt-modernizr',
26 verbose rebuildBundles   'grunt-wp-assets',
26 verbose rebuildBundles   'load-grunt-tasks',
26 verbose rebuildBundles   'time-grunt' ]
27 info install roots@7.0.1
28 info postinstall roots@7.0.1
29 verbose unsafe-perm in lifecycle true
30 info roots@7.0.1 Failed to exec postinstall script
31 verbose stack Error: roots@7.0.1 postinstall: `node node_modules/bower/bin/bower install && grunt dev`
31 verbose stack Exit status 1
31 verbose stack     at EventEmitter.<anonymous> (c:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
31 verbose stack     at EventEmitter.emit (events.js:110:17)
31 verbose stack     at ChildProcess.<anonymous> (c:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:14:12)
31 verbose stack     at ChildProcess.emit (events.js:110:17)
31 verbose stack     at maybeClose (child_process.js:1015:16)
31 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
32 verbose pkgid roots@7.0.1
33 verbose cwd d:\Websites\tombar\web\wp-content\themes\roots
34 error Windows_NT 6.3.9600
35 error argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
36 error node v0.12.2
37 error npm  v2.7.4
38 error code ELIFECYCLE
39 error roots@7.0.1 postinstall: `node node_modules/bower/bin/bower install && grunt dev`
39 error Exit status 1
40 error Failed at the roots@7.0.1 postinstall script 'node node_modules/bower/bin/bower install && grunt dev'.
40 error This is most likely a problem with the roots package,
40 error not with npm itself.
40 error Tell the author that this fails on your system:
40 error     node node_modules/bower/bin/bower install && grunt dev
40 error You can get their info via:
40 error     npm owner ls roots
40 error There is likely additional logging output above.
41 verbose exit [ 1, true ]
```

**Comment by smikes** [comment]
It looks like the package.json contains a Unix-like postinstall command:

```
node node_modules/bower/bin/bower install && grunt dev
```

But you are trying to install on Windows, which does not support the `&&` operator in its default terminal program, cmd.exe.

**Comment by iarna** [comment]
@smikes `&&` and `||` are actually valid in `cmd.exe` too. I was surprised too!

That said, I'd definitely rewrite that postinstall as:

```
bower install && grunt dev
```

When you list bower as a dependency, npm will (on windows) make sure a `bower.cmd` stub is installed in your path when you run any lifecycle script like postinstall. You shouldn't ever be directly using paths into node_modules.

It's hard to tell what's going wrong here, as there wasn't any command output. (The relevant part of the log is:)

```
28 info postinstall roots@7.0.1
29 verbose unsafe-perm in lifecycle true
30 info roots@7.0.1 Failed to exec postinstall script
31 verbose stack Error: roots@7.0.1 postinstall: `node node_modules/bower/bin/bower install && grunt dev`
31 verbose stack Exit status 1
```

But I wouldn't be all that surprised if you find that changing your post install to:

```
bower install && grunt dev
```

fixes the problem.

**Comment by smikes** [comment]
Thanks for correcting me!  Sebastian, can you let us know if the change @iarna suggested helps?

**Comment by sebastianmusial** [comment]
Thank for answers but this change not fixes the problem.

**Comment by othiym23** [comment]
```
30 info roots@7.0.1 Failed to exec postinstall script
31 verbose stack Error: roots@7.0.1 postinstall: `node node_modules/bower/bin/bower install && grunt dev`
31 verbose stack Exit status 1
```

Unfortunately, it looks like one of those two scripts is failing, and without more details, it's impossible to say which. Try running the two scripts on their own 

```
node node_modules\bower\bin\bower install
grunt dev
```
and see if one of them fails?

**Comment by smikes** [comment]
Is this still a problem for you?

Have you been able to run the two parts of the script separately, as @othiym23 suggested above?

Could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
