### ISSUE TITLE
Node.js error when update phonegap 

### ISSUE THREAD

**Issue by duongcuong96** [npm/npm#8085]
< Sorry my bad English >
Hi! im update phonegap via command : " npm update -g phonegap " but npm throught error :
here is my npm-debug.log : 
 Please help me ! Thanks ! 
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'update',
1 verbose cli   '-g',
1 verbose cli   'phonegap' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 silly mapToRegistry name phonegap
5 silly mapToRegistry using default registry
6 silly mapToRegistry registry http://registry.npmjs.org/
7 silly mapToRegistry uri http://registry.npmjs.org/phonegap
8 verbose request uri http://registry.npmjs.org/phonegap
9 verbose request no auth needed
10 info attempt registry request try #1 at 1:25:14 PM
11 verbose request id 69ccbb40f0069daf
12 verbose etag "5ZVC93V20YIPWZK089YGFECW7"
13 http request GET http://registry.npmjs.org/phonegap
14 http 200 http://registry.npmjs.org/phonegap
15 silly get cb [ 200,
15 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
15 silly get     etag: '"3TNJ5QHHV7ITOPNJ0BS8GLJN6"',
15 silly get     'content-type': 'application/json',
15 silly get     'cache-control': 'max-age=60',
15 silly get     'content-length': '208951',
15 silly get     'accept-ranges': 'bytes',
15 silly get     date: 'Mon, 27 Apr 2015 06:25:14 GMT',
15 silly get     via: '1.1 varnish',
15 silly get     age: '3',
15 silly get     connection: 'keep-alive',
15 silly get     'x-served-by': 'cache-lax1427-LAX',
15 silly get     'x-cache': 'HIT',
15 silly get     'x-cache-hits': '1',
15 silly get     'x-timer': 'S1430115914.704649,VS0,VE1',
15 silly get     vary: 'Accept' } ]
16 verbose get saving phonegap to /home/cuong/.npm/registry.npmjs.org/phonegap/.cache.json
17 info outdated updating [ [ '/usr/local/lib',
17 info outdated     'phonegap',
17 info outdated     '4.2.0-0.25.0',
17 info outdated     '4.2.0-0.26.0',
17 info outdated     '4.2.0-0.26.0',
17 info outdated     'latest' ] ]
18 verbose install where, what [ '/usr/local/lib', [ 'phonegap@4.2.0-0.26.0' ] ]
19 silly cache add args [ 'phonegap@4.2.0-0.26.0', null ]
20 verbose cache add spec phonegap@4.2.0-0.26.0
21 silly cache add parsed spec { raw: 'phonegap@4.2.0-0.26.0',
21 silly cache add   scope: null,
21 silly cache add   name: 'phonegap',
21 silly cache add   rawSpec: '4.2.0-0.26.0',
21 silly cache add   spec: '4.2.0-0.26.0',
21 silly cache add   type: 'version' }
22 verbose addNamed phonegap@4.2.0-0.26.0
23 silly addNamed semver.valid 4.2.0-0.26.0
24 silly addNamed semver.validRange 4.2.0-0.26.0
25 silly mapToRegistry name phonegap
26 silly mapToRegistry using default registry
27 silly mapToRegistry registry http://registry.npmjs.org/
28 silly mapToRegistry uri http://registry.npmjs.org/phonegap
29 verbose addNameVersion registry:http://registry.npmjs.org/phonegap not in flight; fetching
30 verbose get http://registry.npmjs.org/phonegap not expired, no request
31 silly mapToRegistry name phonegap
32 silly mapToRegistry using default registry
33 silly mapToRegistry registry http://registry.npmjs.org/
34 silly mapToRegistry uri http://registry.npmjs.org/phonegap
35 verbose addRemoteTarball http://registry.npmjs.org/phonegap/-/phonegap-4.2.0-0.26.0.tgz not in flight; adding
36 verbose addRemoteTarball [ 'http://registry.npmjs.org/phonegap/-/phonegap-4.2.0-0.26.0.tgz',
36 verbose addRemoteTarball   'ae86de17ade06fb695ea17a8c2d32fe44b18e7d1' ]
37 info retry fetch attempt 1 at 1:25:17 PM
38 info attempt registry request try #1 at 1:25:17 PM
39 http fetch GET http://registry.npmjs.org/phonegap/-/phonegap-4.2.0-0.26.0.tgz
40 http fetch 200 http://registry.npmjs.org/phonegap/-/phonegap-4.2.0-0.26.0.tgz
41 silly fetchAndShaCheck shasum ae86de17ade06fb695ea17a8c2d32fe44b18e7d1
42 verbose addTmpTarball /tmp/npm-6863-6cd4aba6/registry.npmjs.org/phonegap/-/phonegap-4.2.0-0.26.0.tgz not in flight; adding
43 verbose addTmpTarball already have metadata; skipping unpack for phonegap@4.2.0-0.26.0
44 silly cache afterAdd phonegap@4.2.0-0.26.0
45 verbose afterAdd /home/cuong/.npm/phonegap/4.2.0-0.26.0/package/package.json not in flight; writing
46 verbose afterAdd /home/cuong/.npm/phonegap/4.2.0-0.26.0/package/package.json written
47 silly install resolved [ { name: 'phonegap',
47 silly install resolved     description: 'PhoneGap command-line interface and node.js library.',
47 silly install resolved     version: '4.2.0-0.26.0',
47 silly install resolved     homepage: 'http://github.com/phonegap/phonegap-cli',
47 silly install resolved     repository:
47 silly install resolved      { type: 'git',
47 silly install resolved        url: 'git://github.com/phonegap/phonegap-cli.git' },
47 silly install resolved     keywords:
47 silly install resolved      [ 'cli',
47 silly install resolved        'cordova',
47 silly install resolved        'phonegap',
47 silly install resolved        'phonegap build',
47 silly install resolved        'phonegap/build' ],
47 silly install resolved     preferGlobal: 'true',
47 silly install resolved     main: './lib/main.js',
47 silly install resolved     bin: { phonegap: './bin/phonegap.js' },
47 silly install resolved     scripts: { test: 'jasmine-node --color spec' },
47 silly install resolved     engineStrict: 'true',
47 silly install resolved     engines: { node: '>=0.10.0' },
47 silly install resolved     dependencies:
47 silly install resolved      { colors: '0.6.0-1',
47 silly install resolved        'connect-phonegap': '0.15.0',
47 silly install resolved        cordova: '4.2.0',
47 silly install resolved        minimist: '0.1.0',
47 silly install resolved        'phonegap-build': '0.9.1',
47 silly install resolved        pluralize: '0.0.4',
47 silly install resolved        prompt: '0.2.11',
47 silly install resolved        'qrcode-terminal': '0.9.4',
47 silly install resolved        semver: '1.1.0',
47 silly install resolved        shelljs: '0.1.4' },
47 silly install resolved     devDependencies: { 'jasmine-node': '1.14.5', chdir: '0.0.x' },
47 silly install resolved     optionalDependencies: {},
47 silly install resolved     contributors: [ [Object], [Object], [Object], [Object], [Object] ],
47 silly install resolved     templates:
47 silly install resolved      { blank: [Object],
47 silly install resolved        'hello-world': [Object],
47 silly install resolved        'hello-cordova': [Object],
47 silly install resolved        'jquery-mobile-starter': [Object] },
47 silly install resolved     gitHead: '4988753e19395fc89e9941d3affe6569b05985de',
47 silly install resolved     bugs: { url: 'https://github.com/phonegap/phonegap-cli/issues' },
47 silly install resolved     _id: 'phonegap@4.2.0-0.26.0',
47 silly install resolved     _shasum: 'ae86de17ade06fb695ea17a8c2d32fe44b18e7d1',
47 silly install resolved     _from: 'phonegap@4.2.0-0.26.0',
47 silly install resolved     _npmVersion: '2.5.1',
47 silly install resolved     _nodeVersion: '0.12.0',
47 silly install resolved     _npmUser: { name: 'mwbrooks', email: 'michael@michaelbrooks.ca' },
47 silly install resolved     maintainers: [ [Object], [Object], [Object], [Object] ],
47 silly install resolved     dist:
47 silly install resolved      { shasum: 'ae86de17ade06fb695ea17a8c2d32fe44b18e7d1',
47 silly install resolved        tarball: 'http://registry.npmjs.org/phonegap/-/phonegap-4.2.0-0.26.0.tgz' },
47 silly install resolved     directories: {},
47 silly install resolved     _resolved: 'http://registry.npmjs.org/phonegap/-/phonegap-4.2.0-0.26.0.tgz' } ]
48 info install phonegap@4.2.0-0.26.0 into /usr/local/lib
49 info installOne phonegap@4.2.0-0.26.0
50 verbose installOne of phonegap to /usr/local/lib not in flight; installing
51 warn locking Error: EACCES, open '/home/cuong/.npm/_locks/phonegap-e2bb9ce47409f16e.lock.STALE'
51 warn locking     at Error (native)
51 warn locking  /home/cuong/.npm/_locks/phonegap-e2bb9ce47409f16e.lock failed { [Error: EACCES, open '/home/cuong/.npm/_locks/phonegap-e2bb9ce47409f16e.lock.STALE']
51 warn locking   errno: -13,
51 warn locking   code: 'EACCES',
51 warn locking   path: '/home/cuong/.npm/_locks/phonegap-e2bb9ce47409f16e.lock.STALE' }
52 verbose stack Error: Attempt to unlock /usr/local/lib/node_modules/phonegap, which hasn't been locked
52 verbose stack     at unlock (/usr/local/lib/node_modules/npm/lib/utils/locker.js:66:11)
52 verbose stack     at cb (/usr/local/lib/node_modules/npm/lib/install.js:1004:5)
52 verbose stack     at /usr/local/lib/node_modules/npm/lib/install.js:1008:20
52 verbose stack     at /usr/local/lib/node_modules/npm/lib/utils/locker.js:40:9
52 verbose stack     at cb (/usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:149:38)
52 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:227:24
52 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:177:38
52 verbose stack     at FSReqWrap.oncomplete (fs.js:95:15)
53 verbose cwd /home/cuong/Light
54 error Linux 3.2.0-80-generic-pae
55 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "update" "-g" "phonegap"
56 error node v0.12.2
57 error npm  v2.7.4
58 error Attempt to unlock /usr/local/lib/node_modules/phonegap, which hasn't been locked
59 error If you need help, you may report this error at:
59 error     <https://github.com/npm/npm/issues>
60 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
@duongcuong96 Looks like you do not have the necessary permissions to write to `npm`'s cache directory. You can change that with:

``` sh
$ sudo chown -R $(whoami) "$HOME/.npm"
```

Also you may need to prefix your update command with `sudo`, like so:

``` sh
$ sudo npm update -g phonegap
```

**Comment by othiym23** [comment]
Closing as resolved – @KenanY's explanation should take care of things for you – good luck!

**Comment by duongcuong96** [comment]
Thank you  ! that's sloved my problem!
