### ISSUE TITLE
.npmrc problem using env vars

### ISSUE THREAD

**Issue by josiahsprague** [npm/npm#8092]
I'm trying to create the following `.npmrc` file;
```
//registry.npmjs.org/:_authToken=${NPM_TOKEN}
```
I've set the `NPM_TOKEN` in my shell (and double checked that it's set correctly), but when I run `npm install` I get the following error;

```
Error: Failed to replace env in config: ${NPM_TOKEN}
    at /Users/Josiah/.nvm-fish/v0.10.32/lib/node_modules/npm/lib/config/core.js:429:13
    at String.replace (native)
    at envReplace (/Users/Josiah/.nvm-fish/v0.10.32/lib/node_modules/npm/lib/config/core.js:424:12)
    at parseField (/Users/Josiah/.nvm-fish/v0.10.32/lib/node_modules/npm/lib/config/core.js:400:7)
    at /Users/Josiah/.nvm-fish/v0.10.32/lib/node_modules/npm/lib/config/core.js:338:17
    at Array.forEach (native)
    at Conf.add (/Users/Josiah/.nvm-fish/v0.10.32/lib/node_modules/npm/lib/config/core.js:337:23)
    at ConfigChain.addString (/Users/Josiah/.nvm-fish/v0.10.32/lib/node_modules/npm/node_modules/config-chain/index.js:244:8)
    at Conf.<anonymous> (/Users/Josiah/.nvm-fish/v0.10.32/lib/node_modules/npm/lib/config/core.js:325:10)
    at fs.js:271:14


/Users/Josiah/.nvm-fish/v0.10.32/lib/node_modules/npm/lib/npm.js:28
    throw new Error('npm.load() required')
          ^
Error: npm.load() required
    at Object.npm.config.get (/Users/Josiah/.nvm-fish/v0.10.32/lib/node_modules/npm/lib/npm.js:28:11)
    at exit (/Users/Josiah/.nvm-fish/v0.10.32/lib/node_modules/npm/lib/utils/error-handler.js:57:40)
    at process.errorHandler (/Users/Josiah/.nvm-fish/v0.10.32/lib/node_modules/npm/lib/utils/error-handler.js:363:3)
    at process.emit (events.js:95:17)
    at process._fatalException (node.js:272:26)
```
I'm not sure if this problem is related to fish shell or not, I'm still debugging, but I would appreciate any insight that you might be able to give.

**Comment by josiahsprague** [comment]
Looks like the issue is that `npm` is checking for the environmental vars in `bash` even if I run the command from `fish`. Setting the var in `bash` resolves my issue, it would be nice if I didn't have to do that, since I never use `bash` for anything else. I guess this should be classified as a feature request, and I'm probably an outlier using `fish`. :-P

**Comment by smikes** [comment]
Thanks for reporting this.  It sounds like a bug to me, but I don't use `fish` - is there something unusual about the way it exposes environment variables to its child processes?

**Comment by josiahsprague** [comment]
Turns out that the problem was how I had set the environmental variable. I had set a universal environment variable, that I could `echo $NPM_TOKEN` and see the variable, but it wasn't being exported to child processes. http://fishshell.com/docs/current/index.html#variables

PEBKAC :)

**Comment by smikes** [comment]
Thanks for following up and closing the issue!  This will be useful if we ever run into it again with another `fish` user.

**Comment by thehydroimpulse** [comment]
I've been getting the same error on with Heroku environment variables.

**Comment by jasonkarns** [comment]
Is it possible to simply set the token itself as an env var, rather than setting a var that the npmrc file reads?

All other config values can be set as env vars as `NPM_CONFIG_VARNAME`, but I have no idea what the format would be for an env var that represents `//registry.npmjs.org/:_authToken` Replace all non alpha chars with underscores? Collapse?

`NPM_CONFIG__REGISTRY_NPMJS_ORG___AUTHTOKEN` is quite a var if it indeed worked.

**Comment by kevinSuttle** [comment]
I think this is the real culprit: https://github.com/npm/npm/issues/10782

**Comment by udnisap** [comment]
I had a similar problem on zsh with nvm at https://github.com/creationix/nvm/issues/855#issuecomment-270804617

try `NPM_TOKEN=sdsd npm config get prefix` on fish shell

**Comment by ljharb** [comment]
@udnisap on `zsh`, or on `fish`? `fish` isn't posix compliant, so it wouldn't work with `nvm` anyways.

**Comment by udnisap** [comment]
the problem i had was with the npm. none of the commands work with npm due to this. if fish is not posix this wouldnt work. my bad. try exporting NPM_TOKEN as an global variable

**Comment by ababushkin** [comment]
If you run into this issue and like me couldn't really work out the fix by the comments in this thread, this will work for you: `set -x NPM_AUTH_TOKEN xxx`

`npm i` will work as expected moving forward

Documented in http://fishshell.com/docs/current/index.html#variables under 'Exporting variables'

I too made the clumsy mistake of setting it as a Universal variable :)

**Comment by odGit** [comment]
This issue is not only for fish or zsh users. I an using ConEmu on Windows 10. 
I have the same issue in _CMD_ and _BASH_ .

```
λ npm login
Error: Failed to replace env in config: ${NPM_TOKEN}
    at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:417:13
    at String.replace (<anonymous>)
    at envReplace (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:413:12)
    at parseField (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:391:7)
    at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:334:17
    at Array.forEach (<anonymous>)
    at Conf.add (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:333:23)
    at ConfigChain.addString (C:\Program Files\nodejs\node_modules\npm\node_modules\config-chain\index.js:244:8)
    at Conf.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:321:10)
    at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
C:\Program Files\nodejs\node_modules\npm\lib\npm.js:61
      throw new Error('npm.load() required')
      ^

Error: npm.load() required
    at Object.get (C:\Program Files\nodejs\node_modules\npm\lib\npm.js:61:13)
    at process.errorHandler (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:205:18)
    at emitOne (events.js:116:13)
    at process.emit (events.js:211:7)
    at process._fatalException (bootstrap_node.js:375:26)
```
UPDATED:
If I remove `//registry.npmjs.org/:_authToken=${NPM_TOKEN}` from ` .npmrc`  which will brake my CI integration. 
Is there a better solution to this problem ?
