### ISSUE TITLE
Cordova Install error 

### ISSUE THREAD

**Issue by dilanWijerathne** [npm/npm#8123]
I am using windows 8.1 and trying to install cordova, but I get this error and cannot install properly, how can I solve this and what is this proper way to do this ? what is the suitable Node.js version ?
```
C:\Users\fmfuser>npm install -g cordova
npm http GET https://registry.npmjs.org/cordova
npm http 304 https://registry.npmjs.org/cordova
npm http GET https://registry.npmjs.org/cordova-lib/5.0.0
npm http GET https://registry.npmjs.org/q/1.0.1
npm http GET https://registry.npmjs.org/nopt/3.0.1
npm http GET https://registry.npmjs.org/underscore/1.7.0
npm http 304 https://registry.npmjs.org/cordova-lib/5.0.0
npm http 304 https://registry.npmjs.org/q/1.0.1
npm http 304 https://registry.npmjs.org/nopt/3.0.1
npm http 304 https://registry.npmjs.org/underscore/1.7.0
npm http GET https://registry.npmjs.org/abbrev
npm http GET https://registry.npmjs.org/bplist-parser/0.0.6
npm http GET https://registry.npmjs.org/cordova-js/3.9.0
npm http GET https://registry.npmjs.org/cordova-app-hello-world/3.9.0
npm http GET https://registry.npmjs.org/cordova-registry-mapper
npm http GET https://registry.npmjs.org/d8/0.4.4
npm http GET https://registry.npmjs.org/dep-graph/1.1.0
npm http GET https://registry.npmjs.org/elementtree/0.1.5
npm http GET https://registry.npmjs.org/glob/4.0.6
npm http GET https://registry.npmjs.org/init-package-json
npm http GET https://registry.npmjs.org/mime/1.2.11
npm http GET https://registry.npmjs.org/npm/1.3.4
npm http GET https://registry.npmjs.org/npmconf/0.1.16
npm http GET https://registry.npmjs.org/osenv/0.1.0
npm http GET https://registry.npmjs.org/plist/1.1.0
npm http GET https://registry.npmjs.org/properties-parser/0.2.3
npm http GET https://registry.npmjs.org/rc/0.5.2
npm http GET https://registry.npmjs.org/request/2.47.0
npm http GET https://registry.npmjs.org/shelljs/0.3.0
npm http GET https://registry.npmjs.org/semver/2.1.0
npm http GET https://registry.npmjs.org/tar/1.0.2
npm http GET https://registry.npmjs.org/through2/0.6.3
npm http GET https://registry.npmjs.org/valid-identifier/0.0.1
npm http GET https://registry.npmjs.org/unorm/1.3.3
npm http GET https://registry.npmjs.org/xcode/0.6.7
npm http 304 https://registry.npmjs.org/abbrev
npm http 304 https://registry.npmjs.org/d8/0.4.4
npm http 304 https://registry.npmjs.org/dep-graph/1.1.0
npm http 304 https://registry.npmjs.org/cordova-js/3.9.0
npm http 304 https://registry.npmjs.org/bplist-parser/0.0.6
npm http 304 https://registry.npmjs.org/cordova-app-hello-world/3.9.0
npm http 304 https://registry.npmjs.org/cordova-registry-mapper
npm http 304 https://registry.npmjs.org/elementtree/0.1.5
npm http 304 https://registry.npmjs.org/glob/4.0.6
npm http 304 https://registry.npmjs.org/init-package-json
npm http 304 https://registry.npmjs.org/npm/1.3.4
npm ERR! Error: No compatible version found: init-package-json@'^1.2.0'
npm ERR! Valid install targets:
npm ERR! ["0.0.1","0.0.2","0.0.3","0.0.4","0.0.5","0.0.6","0.0.7","0.0.8","0.0.9
","0.0.10","0.0.11","0.0.13","0.0.14","0.0.15","0.0.16","0.0.17","0.1.0","0.1.1"
,"0.1.2","1.0.0","1.0.1","1.1.0","1.1.1","1.1.2","1.1.3","1.2.0","1.3.0","1.3.1"
,"1.3.2","1.4.0","1.4.1","1.4.2"]
npm ERR!     at installTargetsError (C:\Program Files (x86)\nodejs\node_modules\
npm\lib\cache.js:682:10)
npm ERR!     at C:\Program Files (x86)\nodejs\node_modules\npm\lib\cache.js:597:
10
npm ERR!     at saved (C:\Program Files (x86)\nodejs\node_modules\npm\node_modul
es\npm-registry-client\lib\get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:93:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program File
s (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova"
npm ERR! cwd C:\Users\fmfuser
npm ERR! node -v v0.10.0
npm ERR! npm -v 1.2.14
npm http 304 https://registry.npmjs.org/npmconf/0.1.16
npm http 304 https://registry.npmjs.org/mime/1.2.11
npm http 304 https://registry.npmjs.org/plist/1.1.0
npm http 304 https://registry.npmjs.org/properties-parser/0.2.3
npm http 304 https://registry.npmjs.org/rc/0.5.2
npm http 304 https://registry.npmjs.org/request/2.47.0
npm http 304 https://registry.npmjs.org/osenv/0.1.0
npm http 304 https://registry.npmjs.org/semver/2.1.0
npm http 304 https://registry.npmjs.org/tar/1.0.2
npm http 304 https://registry.npmjs.org/through2/0.6.3
npm http 304 https://registry.npmjs.org/valid-identifier/0.0.1
npm http 304 https://registry.npmjs.org/shelljs/0.3.0
npm http 304 https://registry.npmjs.org/unorm/1.3.3
npm http 304 https://registry.npmjs.org/xcode/0.6.7
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\fmfuser\npm-debug.log
npm ERR! not ok code 0

C:\Users\fmfuser>npm update cordova

C:\Users\fmfuser>npm install -g cordova
npm http GET https://registry.npmjs.org/cordova
npm http 304 https://registry.npmjs.org/cordova
npm http GET https://registry.npmjs.org/cordova-lib/5.0.0
npm http GET https://registry.npmjs.org/q/1.0.1
npm http GET https://registry.npmjs.org/nopt/3.0.1
npm http GET https://registry.npmjs.org/underscore/1.7.0
npm http 304 https://registry.npmjs.org/underscore/1.7.0
npm http 304 https://registry.npmjs.org/nopt/3.0.1
npm http 304 https://registry.npmjs.org/cordova-lib/5.0.0
npm http 304 https://registry.npmjs.org/q/1.0.1
npm http GET https://registry.npmjs.org/abbrev
npm http GET https://registry.npmjs.org/cordova-app-hello-world/3.9.0
npm http GET https://registry.npmjs.org/cordova-js/3.9.0
npm http GET https://registry.npmjs.org/bplist-parser/0.0.6
npm http GET https://registry.npmjs.org/cordova-registry-mapper
npm http GET https://registry.npmjs.org/d8/0.4.4
npm http GET https://registry.npmjs.org/dep-graph/1.1.0
npm http GET https://registry.npmjs.org/elementtree/0.1.5
npm http GET https://registry.npmjs.org/glob/4.0.6
npm http GET https://registry.npmjs.org/semver/2.1.0
npm http GET https://registry.npmjs.org/init-package-json
npm http GET https://registry.npmjs.org/tar/1.0.2
npm http GET https://registry.npmjs.org/mime/1.2.11
npm http GET https://registry.npmjs.org/through2/0.6.3
npm http GET https://registry.npmjs.org/shelljs/0.3.0
npm http GET https://registry.npmjs.org/npm/1.3.4
npm http GET https://registry.npmjs.org/unorm/1.3.3
npm http GET https://registry.npmjs.org/npmconf/0.1.16
npm http GET https://registry.npmjs.org/valid-identifier/0.0.1
npm http GET https://registry.npmjs.org/osenv/0.1.0
npm http GET https://registry.npmjs.org/xcode/0.6.7
npm http GET https://registry.npmjs.org/plist/1.1.0
npm http GET https://registry.npmjs.org/properties-parser/0.2.3
npm http GET https://registry.npmjs.org/rc/0.5.2
npm http GET https://registry.npmjs.org/request/2.47.0
npm http 304 https://registry.npmjs.org/abbrev
npm http 304 https://registry.npmjs.org/cordova-registry-mapper
npm http 304 https://registry.npmjs.org/cordova-app-hello-world/3.9.0
npm http 304 https://registry.npmjs.org/bplist-parser/0.0.6
npm http 304 https://registry.npmjs.org/cordova-js/3.9.0
npm http 304 https://registry.npmjs.org/d8/0.4.4
npm http 304 https://registry.npmjs.org/elementtree/0.1.5
npm http 304 https://registry.npmjs.org/glob/4.0.6
npm http 304 https://registry.npmjs.org/init-package-json
npm http 304 https://registry.npmjs.org/mime/1.2.11
npm ERR! Error: No compatible version found: init-package-json@'^1.2.0'
npm ERR! Valid install targets:
npm ERR! ["0.0.1","0.0.2","0.0.3","0.0.4","0.0.5","0.0.6","0.0.7","0.0.8","0.0.9
","0.0.10","0.0.11","0.0.13","0.0.14","0.0.15","0.0.16","0.0.17","0.1.0","0.1.1"
,"0.1.2","1.0.0","1.0.1","1.1.0","1.1.1","1.1.2","1.1.3","1.2.0","1.3.0","1.3.1"
,"1.3.2","1.4.0","1.4.1","1.4.2"]
npm ERR!     at installTargetsError (C:\Program Files (x86)\nodejs\node_modules\
npm\lib\cache.js:682:10)
npm ERR!     at C:\Program Files (x86)\nodejs\node_modules\npm\lib\cache.js:597:
10
npm ERR!     at saved (C:\Program Files (x86)\nodejs\node_modules\npm\node_modul
es\npm-registry-client\lib\get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:93:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program File
s (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova"
npm ERR! cwd C:\Users\fmfuser
npm ERR! node -v v0.10.0
npm ERR! npm -v 1.2.14
npm http 304 https://registry.npmjs.org/semver/2.1.0
npm http 304 https://registry.npmjs.org/dep-graph/1.1.0
npm http 304 https://registry.npmjs.org/tar/1.0.2
npm http 304 https://registry.npmjs.org/shelljs/0.3.0
npm http 304 https://registry.npmjs.org/npm/1.3.4
npm http 304 https://registry.npmjs.org/npmconf/0.1.16
npm http 304 https://registry.npmjs.org/through2/0.6.3
npm http 304 https://registry.npmjs.org/osenv/0.1.0
npm http 304 https://registry.npmjs.org/unorm/1.3.3
npm http 304 https://registry.npmjs.org/valid-identifier/0.0.1
npm http 304 https://registry.npmjs.org/xcode/0.6.7
npm http 304 https://registry.npmjs.org/properties-parser/0.2.3
npm http 304 https://registry.npmjs.org/rc/0.5.2
npm http 304 https://registry.npmjs.org/request/2.47.0
npm http 304 https://registry.npmjs.org/plist/1.1.0
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\fmfuser\npm-debug.log
npm ERR! not ok code 0
```

**Comment by smikes** [comment]
It looks like the version of `node` that you have is quite old, and has a version of `npm` that does not understand the "new" kind of semantic version syntax "^1.2.0".

Can you try updating your `node` to 0.10.38 and your `npm` to the latest version (currently 2.8.4) by installing the msi here: https://nodejs.org/dist/v0.10.38/node-v0.10.38-x86.msi and then following our guide here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows

Thanks!

**Comment by dilanWijerathne** [comment]
Can I uninstall cordova and re-install ?, seems you are correct and your method is working :)
Thanks

**Comment by smikes** [comment]
Yes, you can either just remove `cordova` from your global `node_modules` folder or you can try

`npm rm -g cordova`

Once you have a newer `npm` that supports the `^1.2.0` syntax, you should be able to install.

A note about node versions -- although 0.12.2 is nominally the "latest stable" version, I recommend using 0.10.38 unless you absolutely need something from 0.12, as we seem to be seeing some hard-to-track-down errors in 0.12.0 and 0.12.2.

Of course 0.12 will be the future of node, but especially if you are just getting started, I think you will find 0.10.38 to be a bit easier to work with.

**Comment by dilanWijerathne** [comment]
it's ok now, but I cannot run emulator, I'm confusing what can I do now ? 
C:\Users\fmfuser\hello\hello\hello> cordova build
Running command: C:\Users\fmfuser\hello\hello\hello\platforms\android\cordova\bu
ild.bat
[Error: Please install Android target: "android-22".

Hint: Open the SDK manager by running: C:\Users\fmfuser\AppData\Local\Android\sd
k\tools\android.BAT
You will require:
1. "SDK Platform" for android-22
2. "Android SDK Platform-tools (latest)
3. "Android SDK Build-tools" (latest)]
ERROR building one of the platforms: Error: C:\Users\fmfuser\hello\hello\hello\p
latforms\android\cordova\build.bat: Command failed with exit code 2
You may not have the required environment or OS to build this project
Error: C:\Users\fmfuser\hello\hello\hello\platforms\android\cordova\build.bat: C
ommand failed with exit code 2
    at ChildProcess.whenDone (C:\Users\fmfuser\AppData\Roaming\npm\node_modules\
cordova\node_modules\cordova-lib\src\cordova\superspawn.js:131:23)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5)

C:\Users\fmfuser\hello\hello\hello>

**Comment by smikes** [comment]
It looks like you need to install one or more emulators in order to test your app.

Try running the suggested script:

Windows-R (to open the Run... dialog)
C:\Users\fmfuser\AppData\Local\Android\sdk\tools\android.BAT

then choose

1. "SDK Platform" for android-22
2. "Android SDK Platform-tools (latest)
3. "Android SDK Build-tools" (latest)]

**Comment by dilanWijerathne** [comment]
There is no ""C:\Users\fmfuser\AppData\Local\Android\sdk\tools\android.BAT", how can I set android home or set android to this ?

**Comment by smikes** [comment]
I'm sorry I can't help you more, but I don't know much about Cordova. It looks like, in order to install the Android SDK, you can follow the instructions here: http://evothings.com/doc/build/cordova-install-windows.html#InstallAndroidSDKTools

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
