### ISSUE TITLE
npm search error.

### ISSUE THREAD

**Issue by achun** [npm/npm#8153]
Hey. Got this error message when trying to search for html.

```
$ npm search html
npm WARN Building the local index for the first time, please be patient
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "search" "html"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.5
npm ERR! code E200

npm ERR! true true: -/all
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/achun/npm-debug.log
```

npm-debug.log
```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'search', 'html' ]
2 info using npm@2.7.5
3 info using node@v0.12.2
4 verbose node symlink /usr/local/bin/node
5 verbose config Skipping project config: /Users/achun/.npmrc. (matches userconfig)
6 silly mapToRegistry name -/all
7 silly mapToRegistry using default registry
8 silly mapToRegistry registry https://registry.npm.taobao.org/
9 silly mapToRegistry uri https://registry.npm.taobao.org/-/all
10 info updateIndex /Users/achun/.npm/registry.npm.taobao.org/-/all/.cache.json
11 warn Building the local index for the first time, please be patient
12 silly update-index fetching https://registry.npm.taobao.org/-/all
13 verbose request uri https://registry.npm.taobao.org/-/all
14 verbose request no auth needed
15 info attempt registry request try #1 at 00:37:53
16 verbose request id 5e9eb9b751619a0c
17 http request GET https://registry.npm.taobao.org/-/all
18 http 200 https://registry.npm.taobao.org/-/all
19 verbose headers { server: 'nginx/1.1.19',
19 verbose headers   date: 'Fri, 01 May 2015 16:37:55 GMT',
19 verbose headers   'content-type': 'application/json; charset=utf-8',
19 verbose headers   'transfer-encoding': 'chunked',
19 verbose headers   connection: 'keep-alive',
19 verbose headers   etag: '"RB2qvxBMa8LkeFws9W1Tdg=="',
19 verbose headers   'x-readtime': '1612',
19 verbose headers   'content-encoding': 'gzip' }
20 verbose stack Error: true true: -/all
20 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:247:14)
20 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:176:7
20 verbose stack     at Gunzip.onEnd (zlib.js:227:5)
20 verbose stack     at Gunzip.emit (events.js:129:20)
20 verbose stack     at _stream_readable.js:908:16
20 verbose stack     at process._tickCallback (node.js:355:11)
21 verbose statusCode 200
22 verbose cwd /Users/achun
23 error Darwin 14.3.0
24 error argv "node" "/usr/local/bin/npm" "search" "html"
25 error node v0.12.2
26 error npm  v2.7.5
27 error code E200
28 error true true: -/all
29 error If you need help, you may report this error at:
29 error     <https://github.com/npm/npm/issues>
30 verbose exit [ 1, true ]
```

**Comment by smikes** [comment]
Hi!

The `npm search` command was written when there were only a few hundred to a few thousand `npm` modules.  It has not handled the scale up to >140,000 modules well.  It is known to be broken -- the main case is #6016 .

As a workaround, please use the website search function at https://npmjs.com until the command-line search is fixed.

**Comment by achun** [comment]
thanks @smikes .
I switch registry to https://registry.npmjs.org/ , npm search is working okay.

**Comment by othiym23** [comment]
Closing as resolved.
