### ISSUE TITLE
Is this a proxy issue?

### ISSUE THREAD

**Issue by rahul-desai3** [npm/npm#8167]
I am following this tutorial to learn about M.E.A.N. stack development: https://www.youtube.com/watch?v=OhPFgqHz68o. I have setup and coded the backend with Node.js which had no problem.

I have a directory where in I have given all rights to all users as of now.

When I started with the frontend, all I tried to do was:

```
mkdir client
cd client
npm install -g yo
npm install -g generator-angular
yo angular
```

I answered all of the questions asked and then it began its process. Somewhere in between it said that there is a conflict and asked if it should overwrite `package.json`. I agreed to it by hitting `Enter` key since I did not see any other option. 

I could see a lot of errors in the process.

Here is the `npm-debug.log`: https://gist.githubusercontent.com/rahul-desai3/9f1d1d0a1ddeec2a4ad0/raw/npm-debug.log

I had posted this issue on the Yeoman repo earlier: https://github.com/yeoman/yo/issues/322

Is it a proxy issue or something?  
What am I doing wrong here?

**Comment by smikes** [comment]
I don't believe it's a proxy issue.  Can you try updating npm?

There is a bad interaction between two known bugs — one in `node@>0.11` and `iojs` and the other in `npm@<2.8.2`.  This can cause ECONNRESET and ETIMEDOUT errors.  The full writeup is here: https://github.com/npm/npm/issues/7699  You can fix this problem by updating your `npm` to the latest (see below).

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

Thanks!

**Comment by rahul-desai3** [comment]
I update npm to the version 2.9.0 and it still didnt help. I even tried it after formatting my Windows machine.

Here are the errors that I got in the command prompt:
```
   invoke       angular:route
   invoke           angular:controller:C:\Users\Rahul\AppData\Roaming\npm\node_m
odules\generator-angular\route\index.js
   create             app\scripts\controllers\about.js
   create             test\spec\controllers\about.js
   invoke           angular:view:C:\Users\Rahul\AppData\Roaming\npm\node_modules
\generator-angular\route\index.js
   create             app\views\about.html
   create     test\karma.conf.js
 conflict     package.json
? Overwrite package.json? do not overwrite
     skip     package.json
   create     .travis.yml
 conflict     package.json
? Overwrite package.json? do not overwrite
     skip     package.json
bower EAI_AGAIN     Request to https://bower.herokuapp.com/packages/angular fail
ed: getaddrinfo EAI_AGAIN
module.js:338
    throw err;
          ^
Error: Cannot find module 'coffee-script'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (E:\mean-skeleton\myclient\node_modules\grunt\lib\grun
t.js:16:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
npm ERR! tar.unpack untar error C:\Users\Rahul\AppData\Roaming\npm-cache\argpars
e\0.1.16\package.tgz
npm ERR! tar.unpack untar error C:\Users\Rahul\AppData\Roaming\npm-cache\brace-e
xpansion\1.1.0\package.tgz
npm ERR! tar.unpack untar error C:\Users\Rahul\AppData\Roaming\npm-cache\optimis
t\0.6.1\package.tgz
npm ERR! tar.unpack untar error C:\Users\Rahul\AppData\Roaming\npm-cache\ms\0.7.
0\package.tgz
npm ERR! tar.unpack untar error C:\Users\Rahul\AppData\Roaming\npm-cache\brace-e
xpansion\1.1.0\package.tgz
npm ERR! tar.unpack untar error C:\Users\Rahul\AppData\Roaming\npm-cache\core-ut
il-is\1.0.1\package.tgz
npm ERR! tar.unpack untar error C:\Users\Rahul\AppData\Roaming\npm-cache\qs\2.4.
1\package.tgz
npm ERR! tar.unpack untar error C:\Users\Rahul\AppData\Roaming\npm-cache\caniuse
-db\1.0.30000156\package.tgz
npm ERR! tar.unpack untar error C:\Users\Rahul\AppData\Roaming\npm-cache\browser
slist\0.2.0\package.tgz
npm ERR! tar.unpack untar error C:\Users\Rahul\AppData\Roaming\npm-cache\string_
decoder\0.10.31\package.tgz
npm ERR! tar.unpack untar error C:\Users\Rahul\AppData\Roaming\npm-cache\isarray
\0.0.1\package.tgz
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "node" "C:\\Users\\Rahul\\AppData\\Roaming\\npm\\node_modules\\npm
\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.9.0
npm ERR! path E:\mean-skeleton\myclient\node_modules\grunt-contrib-connect\node_
modules\connect\node_modules\serve-favicon\node_modules\etag\package.json
npm ERR! code ENOENT
npm ERR! errno -4058

npm ERR! enoent ENOENT, open 'E:\mean-skeleton\myclient\node_modules\grunt-contr
ib-connect\node_modules\connect\node_modules\serve-favicon\node_modules\etag\pac
kage.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "node" "C:\\Users\\Rahul\\AppData\\Roaming\\npm\\node_modules\\npm
\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.9.0
npm ERR! path E:\mean-skeleton\myclient\node_modules\grunt-contrib-connect\node_
modules\connect\node_modules\finalhandler\node_modules\escape-html\package.json
npm ERR! code ENOENT
npm ERR! errno -4058

npm ERR! enoent ENOENT, open 'E:\mean-skeleton\myclient\node_modules\grunt-contr
ib-connect\node_modules\connect\node_modules\finalhandler\node_modules\escape-ht
ml\package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent
npm ERR! tar.unpack untar error C:\Users\Rahul\AppData\Roaming\npm-cache\body-pa
rser\1.12.3\package.tgz
npm ERR! tar.unpack untar error C:\Users\Rahul\AppData\Roaming\npm-cache\clean-c
ss\3.2.7\package.tgz
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "node" "C:\\Users\\Rahul\\AppData\\Roaming\\npm\\node_modules\\npm
\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.9.0
npm ERR! path E:\mean-skeleton\myclient\node_modules\grunt-contrib-connect\node_
modules\connect\node_modules\http-errors\node_modules\statuses\package.json
npm ERR! code ENOENT
npm ERR! errno -4058

npm ERR! enoent ENOENT, open 'E:\mean-skeleton\myclient\node_modules\grunt-contr
ib-connect\node_modules\connect\node_modules\http-errors\node_modules\statuses\p
ackage.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "node" "C:\\Users\\Rahul\\AppData\\Roaming\\npm\\node_modules\\npm
\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.9.0
npm ERR! path E:\mean-skeleton\myclient\node_modules\grunt-contrib-connect\node_
modules\connect\node_modules\type-is\node_modules\mime-types\package.json
npm ERR! code ENOENT
npm ERR! errno -4058

npm ERR! enoent ENOENT, open 'E:\mean-skeleton\myclient\node_modules\grunt-contr
ib-connect\node_modules\connect\node_modules\type-is\node_modules\mime-types\pac
kage.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "node" "C:\\Users\\Rahul\\AppData\\Roaming\\npm\\node_modules\\npm
\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.9.0
npm ERR! path E:\mean-skeleton\myclient\node_modules\grunt-contrib-imagemin\node
_modules\imagemin\node_modules\imagemin-optipng\node_modules\exec-buffer\node_mo
dules\tempfile\node_modules\uuid\benchmark\benchmark-native.c
npm ERR! code ENOENT
npm ERR! errno -4058

npm ERR! enoent ENOENT, open 'E:\mean-skeleton\myclient\node_modules\grunt-contr
ib-imagemin\node_modules\imagemin\node_modules\imagemin-optipng\node_modules\exe
c-buffer\node_modules\tempfile\node_modules\uuid\benchmark\benchmark-native.c'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent
npm ERR! tar.unpack untar error C:\Users\Rahul\AppData\Roaming\npm-cache\find-in
dex\0.1.1\package.tgz
npm ERR! tar.unpack untar error C:\Users\Rahul\AppData\Roaming\npm-cache\coffee-
script\1.3.3\package.tgz
npm ERR! tar.unpack untar error C:\Users\Rahul\AppData\Roaming\npm-cache\inherit
s\2.0.1\package.tgz
npm ERR! tar.unpack untar error C:\Users\Rahul\AppData\Roaming\npm-cache\ms\0.7.
0\package.tgz
npm ERR! tar.unpack untar error C:\Users\Rahul\AppData\Roaming\npm-cache\lodash\
2.4.2\package.tgz
npm ERR! tar.unpack untar error C:\Users\Rahul\AppData\Roaming\npm-cache\on-fini
shed\2.2.1\package.tgz
npm ERR! tar.unpack untar error C:\Users\Rahul\AppData\Roaming\npm-cache\media-t
yper\0.3.0\package.tgz
npm ERR! tar.unpack untar error C:\Users\Rahul\AppData\Roaming\npm-cache\uuid\2.
0.1\package.tgz
npm ERR! tar.unpack untar error C:\Users\Rahul\AppData\Roaming\npm-cache\uuid\2.
0.1\package.tgz
npm ERR! tar.unpack untar error C:\Users\Rahul\AppData\Roaming\npm-cache\uuid\2.
0.1\package.tgz
npm ERR! tar.unpack untar error C:\Users\Rahul\AppData\Roaming\npm-cache\uuid\2.
0.1\package.tgz
npm ERR! tar.unpack untar error C:\Users\Rahul\AppData\Roaming\npm-cache\minimat
ch\0.3.0\package.tgz
npm ERR! tar.unpack untar error C:\Users\Rahul\AppData\Roaming\npm-cache\bower\1
.3.12\package.tgz
npm ERR! tar.unpack untar error C:\Users\Rahul\AppData\Roaming\npm-cache\svgo\0.
5.1\package.tgz
npm ERR! tar.unpack untar error C:\Users\Rahul\AppData\Roaming\npm-cache\lodash\
2.4.2\package.tgz
npm ERR! tar.unpack untar error C:\Users\Rahul\AppData\Roaming\npm-cache\svgo\0.
5.1\package.tgz
npm ERR! tar.unpack untar error C:\Users\Rahul\AppData\Roaming\npm-cache\postcss
\4.0.6\package.tgz
npm WARN optional dep failed, continuing imagemin-svgo@4.1.2
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "node" "C:\\Users\\Rahul\\AppData\\Roaming\\npm\\node_modules\\npm
\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.9.0
npm ERR! path E:\mean-skeleton\myclient\node_modules\grunt-autoprefixer\node_mod
ules\autoprefixer-core\node_modules\num2fraction\package.json
npm ERR! code ENOENT
npm ERR! errno -4058

npm ERR! enoent ENOENT, open 'E:\mean-skeleton\myclient\node_modules\grunt-autop
refixer\node_modules\autoprefixer-core\node_modules\num2fraction\package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent
npm ERR! tar.unpack untar error C:\Users\Rahul\AppData\Roaming\npm-cache\glob\3.
1.21\package.tgz
npm ERR! tar.unpack untar error C:\Users\Rahul\AppData\Roaming\npm-cache\bower\1
.4.1\package.tgz
npm ERR! tar.unpack untar error C:\Users\Rahul\AppData\Roaming\npm-cache\glob\4.
5.3\package.tgz
npm ERR! tar.unpack untar error C:\Users\Rahul\AppData\Roaming\npm-cache\browser
ify-zlib\0.1.4\package.tgz
npm ERR! tar.unpack untar error C:\Users\Rahul\AppData\Roaming\npm-cache\browser
ify-zlib\0.1.4\package.tgz
npm ERR! tar.unpack untar error C:\Users\Rahul\AppData\Roaming\npm-cache\uglify-
js\2.4.20\package.tgz
npm ERR! tar.unpack untar error C:\Users\Rahul\AppData\Roaming\npm-cache\clean-c
ss\3.1.9\package.tgz
npm ERR! tar.unpack untar error C:\Users\Rahul\AppData\Roaming\npm-cache\readabl
e-stream\1.1.13\package.tgz
npm ERR! tar.unpack untar error C:\Users\Rahul\AppData\Roaming\npm-cache\readabl
e-stream\1.1.13\package.tgz
npm ERR! tar.unpack untar error C:\Users\Rahul\AppData\Roaming\npm-cache\lodash\
2.4.2\package.tgz
npm ERR! tar.unpack untar error C:\Users\Rahul\AppData\Roaming\npm-cache\ng-anno
tate\0.15.4\package.tgz
npm ERR! tar.unpack untar error C:\Users\Rahul\AppData\Roaming\npm-cache\undersc
ore.string\2.3.3\package.tgz
npm ERR! tar.unpack untar error C:\Users\Rahul\AppData\Roaming\npm-cache\readabl
e-stream\1.1.13\package.tgz
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "node" "C:\\Users\\Rahul\\AppData\\Roaming\\npm\\node_modules\\npm
\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.9.0
npm ERR! path E:\mean-skeleton\myclient\node_modules\load-grunt-tasks\node_modul
es\multimatch\node_modules\minimatch\node_modules\brace-expansion\node_modules\c
oncat-map\package.json
npm ERR! code ENOENT
npm ERR! errno -4058

npm ERR! enoent ENOENT, open 'E:\mean-skeleton\myclient\node_modules\load-grunt-
tasks\node_modules\multimatch\node_modules\minimatch\node_modules\brace-expansio
n\node_modules\concat-map\package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent
npm ERR! tar.unpack untar error C:\Users\Rahul\AppData\Roaming\npm-cache\uglify-
js\2.4.20\package.tgz
npm ERR! tar.unpack untar error C:\Users\Rahul\AppData\Roaming\npm-cache\undersc
ore.string\2.2.1\package.tgz
npm ERR! tar.unpack untar error C:\Users\Rahul\AppData\Roaming\npm-cache\lodash\
1.0.2\package.tgz
npm ERR! tar.unpack untar error C:\Users\Rahul\AppData\Roaming\npm-cache\esprima
\1.0.4\package.tgz
npm ERR! tar.unpack untar error C:\Users\Rahul\AppData\Roaming\npm-cache\lodash\
2.4.2\package.tgz
npm ERR! tar.unpack untar error C:\Users\Rahul\AppData\Roaming\npm-cache\lodash\
2.4.2\package.tgz
npm ERR! tar.unpack untar error C:\Users\Rahul\AppData\Roaming\npm-cache\lodash\
2.4.2\package.tgz
npm ERR! tar.unpack untar error C:\Users\Rahul\AppData\Roaming\npm-cache\lodash\
2.4.2\package.tgz
npm ERR! tar.unpack untar error C:\Users\Rahul\AppData\Roaming\npm-cache\qs\0.5.
6\package.tgz
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "node" "C:\\Users\\Rahul\\AppData\\Roaming\\npm\\node_modules\\npm
\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.9.0
npm ERR! path E:\mean-skeleton\myclient\node_modules\grunt-contrib-watch\node_mo
dules\lodash\dist\lodash.compat.js
npm ERR! code EPERM
npm ERR! errno -4048

npm ERR! Error: EPERM, unlink 'E:\mean-skeleton\myclient\node_modules\grunt-cont
rib-watch\node_modules\lodash\dist\lodash.compat.js'
npm ERR!     at Error (native)
npm ERR!  { [Error: EPERM, unlink 'E:\mean-skeleton\myclient\node_modules\grunt-
contrib-watch\node_modules\lodash\dist\lodash.compat.js']
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   path: 'E:\\mean-skeleton\\myclient\\node_modules\\grunt-contrib-watch
\\node_modules\\lodash\\dist\\lodash.compat.js' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.
npm ERR! error rolling back Error: EPERM, unlink 'E:\mean-skeleton\myclient\node
_modules\grunt\node_modules\iconv-lite\encodings\table\gbk.js'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  { [Error: EPERM, unlink 'E:\mean-skeleton\myclient\
node_modules\grunt\node_modules\iconv-lite\encodings\table\gbk.js']
npm ERR! error rolling back   errno: -4048,
npm ERR! error rolling back   code: 'EPERM',
npm ERR! error rolling back   path: 'E:\\mean-skeleton\\myclient\\node_modules\\
grunt\\node_modules\\iconv-lite\\encodings\\table\\gbk.js' }

npm ERR! Please include the following file with any support request:
npm ERR!     E:\mean-skeleton\myclient\npm-debug.log
npm ERR! tar.unpack untar error C:\Users\Rahul\AppData\Roaming\npm-cache\iconv-l
ite\0.2.11\package.tgz
npm ERR! tar.unpack untar error C:\Users\Rahul\AppData\Roaming\npm-cache\jshint\
2.7.0\package.tgz
npm ERR! tar.unpack untar error C:\Users\Rahul\AppData\Roaming\npm-cache\cdnjs-c
dn-data\0.1.1\package.tgz
npm WARN optional dep failed, continuing imagemin-gifsicle@4.1.0
npm WARN optional dep failed, continuing imagemin-jpegtran@4.1.0
npm WARN optional dep failed, continuing imagemin-pngquant@4.1.0

npm ERR! Please include the following file with any support request:
npm ERR!     E:\mean-skeleton\myclient\npm-debug.log

E:\mean-skeleton\myclient>
```

Here is the fresh `npm-debug.log`:  https://gist.githubusercontent.com/rahul-desai3/1b24e6ff6f948dbef558/raw/npm-debug.log

**Comment by smikes** [comment]
It looks like there are problems with the filesystem - files are missing, and other files cannot be deleted due to permissions errors.  Can you try changing the permissions of the `E:\mean-skeleton` directory to be more permissive?

**Comment by thegurukl83** [comment]
I had this same issue. Its because during the install when it breaks for user input at the package.json conflict, if the user enters ANYTHING the install process throws errors and fails. 

Let it proceed without typing anything at this stage. Problem solved.

**Comment by rahul-desai3** [comment]
I installed ruby gems - sass and compass, and it worked. Looks like these are the prerequisites for Yeoman.
