### ISSUE TITLE
Error: Unknown error while authenticating

### ISSUE THREAD

**Issue by sarciszewski** [npm/npm#8171]
```
test random-js # npm adduser
Username: censored
Password: 
Email: censored
npm http PUT https://registry.npmjs.org/-/user/org.couchdb.user:censored
npm http 400 https://registry.npmjs.org/-/user/org.couchdb.user:censored
npm ERR! Error: Unknown error while authenticating : -/user/org.couchdb.user:censored
npm ERR!     at RegClient.<anonymous> (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:272:14)
npm ERR!     at Request.self.callback (/usr/lib/nodejs/request/index.js:148:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/index.js:896:14)
npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/lib/nodejs/request/index.js:847:12)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-37-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "adduser"
npm ERR! cwd /mnt/share/random-js
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /mnt/share/random-js/npm-debug.log
npm ERR! not ok code 0
```

**Comment by sarciszewski** [comment]
```sh
test random-js # uname -a;uname -r; cat /etc/lsb-release
Linux test 3.13.0-37-generic #64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
3.13.0-37-generic
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=17.1
DISTRIB_CODENAME=rebecca
DISTRIB_DESCRIPTION="Linux Mint 17.1 Rebecca"
```

**Comment by KenanY** [comment]
@sarciszewski 

```
npm ERR! npm -v 1.3.10
```

`npm@1.3` is very old and no longer supported. Could you first try [upgrading](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm)?

**Comment by sarciszewski** [comment]
Oh, that was a fresh Linux Mint install through which I had ran `apt-get update && apt-get dist-upgrade` until it reported 0 packages remaining, then installed nodejs and npm. I figured they would at least be somewhat up-to-date.

**Comment by KenanY** [comment]
@sarciszewski 

> installed nodejs and npm

With `apt-get`? Many distributions lag behind the stable releases (in this case, you have Node.js v0.10.25, which was released 2014-01-23, over a year ago). I would suggest using [NodeSource's distribution](https://github.com/nodesource/distributions) if you wish to use `apt-get`.

**Comment by sarciszewski** [comment]
Yeah, that fixes the issue. I should complain to the repository maintainers.
