### ISSUE TITLE
npm does not find module 'cmd-shm'

### ISSUE THREAD

**Issue by pandyah** [npm/npm#8175]
```
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd E:\test\
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! code MODULE_NOT_FOUND
npm ERR! Error: Cannot find module 'cmd-shim'
npm ERR!     at Function.Module._resolveFilename (module.js:338:15)
npm ERR!     at Function.Module._load (module.js:280:25)
npm ERR!     at Module.require (module.js:364:17)
npm ERR!     at require (module.js:380:17)
npm ERR!     at Object.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\build.js:19:15)
npm ERR!     at Module._compile (module.js:456:26)
npm ERR!     at Object.Module._extensions..js (module.js:474:10)
npm ERR!     at Module.load (module.js:356:32)
npm ERR!     at Function.Module._load (module.js:312:12)
npm ERR!     at Module.require (module.js:364:17)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>
```

**Comment by smikes** [comment]
It looks like your installation of `node` and `npm` may be damaged.  Can you try the following:

1. update to the latest 0.10 version of node using this MSI - http://nodejs.org/dist/v0.10.38/node-v0.10.38-x86.msi

2. update `npm` to 2.9.0, by following the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.

**Comment by pandyah** [comment]
Apologies for the delayed reply. It was installation issue. Did not observe
it after re-installing.
Thanks & Regards,
Hitesh
