### ISSUE TITLE
"ERR! Error: Unknown error while authenticating" when logging in

### ISSUE THREAD

**Issue by Daniel15** [npm/npm#8180]
```
npm login
Username: daniel15
Password:
Email: (npm@dan.cx)
npm http PUT https://registry.npmjs.org/-/user/org.couchdb.user:daniel15
npm http 400 https://registry.npmjs.org/-/user/org.couchdb.user:daniel15
npm ERR! Error: Unknown error while authenticating : -/user/org.couchdb.user:daniel15
npm ERR!     at RegClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:272:14)
npm ERR!     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:129:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:873:14)
npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:824:12)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 14.3.0
npm ERR! command "node" "/usr/local/bin/npm" "login"
npm ERR! cwd /usr/local/var/www/react-magic
npm ERR! node -v v0.10.22
npm ERR! npm -v 1.3.14
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /usr/local/var/www/react-magic/npm-debug.log
npm ERR! not ok code 0
```

**Comment by Daniel15** [comment]
Now it's working so I guess there was some transient server error. In any case, "ERR! Error: Unknown error" is now my favourite error message.
