### ISSUE TITLE
When trying to install missing packages in npm, it shows error like this.

### ISSUE THREAD

**Issue by BrindhaE** [npm/npm#8183]
```
module.js:340
    throw err;
          ^
Error: Cannot find module 'thrift'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/indix/Desktop/repo/firestar/lib/bootstrapper.js:3:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
indix@D30:~/Desktop/repo/firestar$ npm install thrift
npm WARN package.json npm@2.9.0 No README data
npm WARN package.json npm@2.9.0 No bin file found at ./bin/npm-cli.js
npm ERR! git clone --template=/home/indix/.npm/_git-remotes/_templates --mirror git://github.com/ind9/node-thrift.git /home/indix/.npm/_git-remotes/git-github-com-ind9-node-thrift-git-0ecdb34d: Cloning into bare repository '/home/indix/.npm/_git-remotes/git-github-com-ind9-node-thrift-git-0ecdb34d'...
npm ERR! git clone --template=/home/indix/.npm/_git-remotes/_templates --mirror git://github.com/ind9/node-thrift.git /home/indix/.npm/_git-remotes/git-github-com-ind9-node-thrift-git-0ecdb34d: fatal: unable to connect to github.com:
npm ERR! git clone --template=/home/indix/.npm/_git-remotes/_templates --mirror git://github.com/ind9/node-thrift.git /home/indix/.npm/_git-remotes/git-github-com-ind9-node-thrift-git-0ecdb34d: github.com[0: 192.30.252.130]: errno=Connection timed out
npm ERR! Linux 3.16.0-36-generic
npm ERR! argv "node" "/usr/local/bin/npm" "install" "thrift"
npm ERR! node v0.10.25
npm ERR! npm  v2.9.0
npm ERR! code 128

npm ERR! Command failed: Cloning into bare repository '/home/indix/.npm/_git-remotes/git-github-com-ind9-node-thrift-git-0ecdb34d'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.252.130]: errno=Connection timed out
npm ERR! 
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/xxxxx/Desktop/repo/firestar/npm-debug.log
```

**Comment by adius** [comment]
+1

**Comment by BrindhaE** [comment]
any ways to resolve this issue?

**Comment by othiym23** [comment]
This doesn't look like an issue with npm – it looks like you have `thrift` specified as a GitHub dependency in `package.json`, and for whatever reason, git was unable to connect to GitHub:

```
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.252.130]: errno=Connection timed out
```

Do you need to set up proxy configuration for git to connect to GitHub?

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
