### ISSUE TITLE
Cordova install issue. PEM routines

### ISSUE THREAD

**Issue by bryanta0585** [npm/npm#8188]
I can't install cordova properly. Here's the debug log:

0 info it worked if it ends with ok
1 verbose cli [ 'c:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'cordova' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 silly cache add args [ 'cordova', null ]
5 verbose cache add spec cordova
6 silly cache add parsed spec { raw: 'cordova',
6 silly cache add   scope: null,
6 silly cache add   name: 'cordova',
6 silly cache add   rawSpec: '',
6 silly cache add   spec: '*',
6 silly cache add   type: 'range' }
7 verbose addNamed cordova@*
8 silly addNamed semver.valid null
9 silly addNamed semver.validRange *
10 silly addNameRange { name: 'cordova', range: '*', hasData: false }
11 silly mapToRegistry name cordova
12 silly mapToRegistry using default registry
13 silly mapToRegistry registry https://registry.npmjs.org/
14 silly mapToRegistry uri https://registry.npmjs.org/cordova
15 verbose addNameRange registry:https://registry.npmjs.org/cordova not in flight; fetching
16 verbose request uri https://registry.npmjs.org/cordova
17 verbose request no auth needed
18 info attempt registry request try #1 at 1:40:53 AM
19 verbose request id 5ba6595b554bc80f
20 verbose etag "97Q28Z01OSER0MUYY8ICG57JC"
21 http request GET https://registry.npmjs.org/cordova
22 verbose stack Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
22 verbose stack     at Error (native)
22 verbose stack     at Object.createSecureContext (_tls_common.js:108:19)
22 verbose stack     at Object.exports.connect (_tls_wrap.js:852:21)
22 verbose stack     at Agent.createConnection (https.js:82:14)
22 verbose stack     at Agent.createSocket (_http_agent.js:194:16)
22 verbose stack     at Agent.addRequest (_http_agent.js:166:23)
22 verbose stack     at new ClientRequest (_http_client.js:154:16)
22 verbose stack     at Object.exports.request (http.js:49:10)
22 verbose stack     at Object.exports.request (https.js:136:15)
22 verbose stack     at Request.start (c:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:904:30)
23 verbose cwd C:\Users\Bryant
24 error Windows_NT 6.3.9600
25 error argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova"
26 error node v0.12.2
27 error npm  v2.7.4
28 error error:0906D06C:PEM routines:PEM_read_bio:no start line
29 error If you need help, you may report this error at:
29 error     <https://github.com/npm/npm/issues>
30 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@bryanta0585 Usually these SSL errors are due to a proxy or firewall. Are you behind a proxy by any chance? The following command may help (but won't completely fix the problem if there is something intercepting your SSL connections):

``` sh
$ npm config set ca ""
```

**Comment by bryanta0585** [comment]
I don't personally have a proxy set up, and I disabled my firewall to see if that was the issue but it wasn't. I'm still getting the same error. I'm going to check the modem/router settings next.

**Comment by smikes** [comment]
There is a bad interaction between two known bugs — one in `node@>0.11` and `iojs` and the other in `npm@<2.8.2`.  This can cause ECONNRESET and ETIMEDOUT errors.  The full writeup is here: https://github.com/npm/npm/issues/7699  You can fix this problem by updating your `npm` to the latest (see below).

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

Thanks!

**Comment by bryanta0585** [comment]
I couldn't update npm with the troubleshooting guide you provided but I did go ahead and update it manually by downloading the zip file from here: 
https://github.com/npm/npm
