### ISSUE TITLE
npm -g install ios-sim

### ISSUE THREAD

**Issue by xin99xin** [npm/npm#8192]
i get a log file <npm-debug.log>:
```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', '-g', 'install', 'ios-sim' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 silly cache add args [ 'ios-sim', null ]
5 verbose cache add spec ios-sim
6 silly cache add parsed spec { raw: 'ios-sim',
6 silly cache add   scope: null,
6 silly cache add   name: 'ios-sim',
6 silly cache add   rawSpec: '',
6 silly cache add   spec: '*',
6 silly cache add   type: 'range' }
7 verbose addNamed ios-sim@*
8 silly addNamed semver.valid null
9 silly addNamed semver.validRange *
10 silly addNameRange { name: 'ios-sim', range: '*', hasData: false }
11 silly mapToRegistry name ios-sim
12 silly mapToRegistry using default registry
13 silly mapToRegistry registry https://registry.npmjs.org/
14 silly mapToRegistry uri https://registry.npmjs.org/ios-sim
15 verbose addNameRange registry:https://registry.npmjs.org/ios-sim not in flight; fetching
16 verbose request uri https://registry.npmjs.org/ios-sim
17 verbose request no auth needed
18 info attempt registry request try #1 at 00:35:02
19 verbose request id ee24f6ec3b10f3bc
20 verbose etag "LZQ64UFJSCLICI2NUYOLIGEP"
21 http request GET https://registry.npmjs.org/ios-sim
22 http 304 https://registry.npmjs.org/ios-sim
23 silly get cb [ 304,
23 silly get   { date: 'Wed, 06 May 2015 16:35:03 GMT',
23 silly get     via: '1.1 varnish',
23 silly get     'cache-control': 'max-age=60',
23 silly get     etag: '"LZQ64UFJSCLICI2NUYOLIGEP"',
23 silly get     age: '0',
23 silly get     connection: 'keep-alive',
23 silly get     'x-served-by': 'cache-hkg6825-HKG',
23 silly get     'x-cache': 'MISS',
23 silly get     'x-cache-hits': '0',
23 silly get     'x-timer': 'S1430930103.429651,VS0,VE622',
23 silly get     vary: 'Accept' } ]
24 verbose etag https://registry.npmjs.org/ios-sim from cache
25 verbose get saving ios-sim to /Users/zodiac1/.npm/registry.npmjs.org/ios-sim/.cache.json
26 silly addNameRange number 2 { name: 'ios-sim', range: '*', hasData: true }
27 silly addNameRange versions [ 'ios-sim',
27 silly addNameRange   [ '1.8.0',
27 silly addNameRange     '1.8.1',
27 silly addNameRange     '1.8.2',
27 silly addNameRange     '1.9.0',
27 silly addNameRange     '2.0.0',
27 silly addNameRange     '2.0.1',
27 silly addNameRange     '3.0.0',
27 silly addNameRange     '3.1.0',
27 silly addNameRange     '3.1.1',
27 silly addNameRange     '4.0.0',
27 silly addNameRange     '4.0.1' ] ]
28 verbose addNamed ios-sim@3.1.1
29 silly addNamed semver.valid 3.1.1
30 silly addNamed semver.validRange 3.1.1
31 silly cache afterAdd ios-sim@3.1.1
32 verbose afterAdd /Users/zodiac1/.npm/ios-sim/3.1.1/package/package.json not in flight; writing
33 verbose afterAdd /Users/zodiac1/.npm/ios-sim/3.1.1/package/package.json written
34 silly install resolved [ { name: 'ios-sim',
34 silly install resolved     version: '3.1.1',
34 silly install resolved     description: 'launch iOS apps into the iOS Simulator from the command line (Xcode 6.0)',
34 silly install resolved     main: 'ios-sim',
34 silly install resolved     scripts: { preinstall: 'rake build' },
34 silly install resolved     bin: { 'ios-sim': 'build/Release/ios-sim' },
34 silly install resolved     repository: { type: 'git', url: 'https://github.com/phonegap/ios-sim' },
34 silly install resolved     keywords: [ 'ios-sim', 'iOS Simulator' ],
34 silly install resolved     author: { name: 'Landon Fuller, Jeff Haynie, Eloy Duran, Shazron Abdullah' },
34 silly install resolved     license: 'MIT',
34 silly install resolved     gitHead: 'c6ec64397e5fa462f1ea2d4e4fdc123a856618f9',
34 silly install resolved     bugs: { url: 'https://github.com/phonegap/ios-sim/issues' },
34 silly install resolved     homepage: 'https://github.com/phonegap/ios-sim',
34 silly install resolved     _id: 'ios-sim@3.1.1',
34 silly install resolved     _shasum: '1129c3fda31b917ef656b8c53fd276392b51c6e8',
34 silly install resolved     _from: 'ios-sim@*',
34 silly install resolved     _npmVersion: '1.4.14',
34 silly install resolved     _npmUser: { name: 'shazron', email: 'shazron@gmail.com' },
34 silly install resolved     maintainers: [ [Object] ],
34 silly install resolved     dist:
34 silly install resolved      { shasum: '1129c3fda31b917ef656b8c53fd276392b51c6e8',
34 silly install resolved        tarball: 'http://registry.npmjs.org/ios-sim/-/ios-sim-3.1.1.tgz' },
34 silly install resolved     directories: {},
34 silly install resolved     _resolved: 'https://registry.npmjs.org/ios-sim/-/ios-sim-3.1.1.tgz',
34 silly install resolved     readme: 'ERROR: No README data found!' } ]
35 info install ios-sim@3.1.1 into /usr/local/lib
36 info installOne ios-sim@3.1.1
37 verbose installOne of ios-sim to /usr/local/lib not in flight; installing
38 warn locking Error: EACCES, open '/Users/zodiac1/.npm/_locks/ios-sim-3bb56db538048d2f.lock'
38 warn locking     at Error (native)
38 warn locking  /Users/zodiac1/.npm/_locks/ios-sim-3bb56db538048d2f.lock failed { [Error: EACCES, open '/Users/zodiac1/.npm/_locks/ios-sim-3bb56db538048d2f.lock']
38 warn locking   errno: -13,
38 warn locking   code: 'EACCES',
38 warn locking   path: '/Users/zodiac1/.npm/_locks/ios-sim-3bb56db538048d2f.lock' }
39 verbose stack Error: Attempt to unlock /usr/local/lib/node_modules/ios-sim, which hasn't been locked
39 verbose stack     at unlock (/usr/local/lib/node_modules/npm/lib/utils/locker.js:66:11)
39 verbose stack     at cb (/usr/local/lib/node_modules/npm/lib/install.js:1004:5)
39 verbose stack     at /usr/local/lib/node_modules/npm/lib/install.js:1008:20
39 verbose stack     at /usr/local/lib/node_modules/npm/lib/utils/locker.js:40:9
39 verbose stack     at cb (/usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:149:38)
39 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:177:38
39 verbose stack     at FSReqWrap.oncomplete (fs.js:95:15)
40 verbose cwd /Users/zodiac1
41 error Darwin 14.3.0
42 error argv "node" "/usr/local/bin/npm" "-g" "install" "ios-sim"
43 error node v0.12.2
44 error npm  v2.7.4
45 error Attempt to unlock /usr/local/lib/node_modules/ios-sim, which hasn't been locked
46 error If you need help, you may report this error at:
46 error     <https://github.com/npm/npm/issues>
47 verbose exit [ 1, true ]
 ```

**Comment by aredridel** [comment]
Looks like npm can't write to something in ~/.npm -- try chowning it to your user. The permissions were probably wrong after using an early npm as root.

**Comment by xin99xin** [comment]
thx!!

**Comment by xin99xin** [comment]
sudo npm ......
done!

**Comment by othiym23** [comment]
Closing as resolved.
