### ISSUE TITLE
error missing script:build

### ISSUE THREAD

**Issue by daleylife** [npm/npm#8193]
I am having trouble running this package.json file
```json
{
  "name": "my-project-name",
  "version": "0.1.0",
  "devDependencies": {
    "autoprefixer": "latest",
    "cssmin": "latest"
  },
  "scripts": {
  "build:css": "autoprefixer -b 'last 2 versions' < css/main.css | cssmin > dist/main.css"
}
}
```
I get this error in consol
```
C:\Users\Dale\Documents\My Web Sites\npm\public_html>npm run build
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4

npm ERR! missing script: build
npm ERR!
```
here is the npm-debug.log
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 verbose stack Error: missing script: build
5 verbose stack     at run (C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:165:19)
5 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:81:5
5 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:52:40
5 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:376:33
5 verbose stack     at checkBinReferences_ (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:341:59)
5 verbose stack     at final (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:373:17)
5 verbose stack     at then (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:127:33)
5 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:317:48
5 verbose stack     at evalmachine.<anonymous>:263:20
5 verbose stack     at OpenReq.Req.done (C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:141:5)
6 verbose cwd C:\Users\Dale\Documents\My Web Sites\npm\public_html
7 error Windows_NT 6.1.7601
8 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
9 error node v0.12.2
10 error npm  v2.7.4
11 error missing script: build
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]
```
Any help would be great as this is stopping me using it
I am using netbeans on windows7

**Comment by smikes** [comment]
It looks like you are have the script "build:css" defined, but not the script "build".

You can change your `package.json` by renaming "build:css" to "build";

Or add "build": "npm run build:css"

Or change the command NetBeans is running to "npm run build:css"

**Comment by othiym23** [comment]
What @smikes said – you should probably just create a script that looks like `"css": "autoprefixer -b \"last 2 versions\" < css/main.css | cssmin > dist/main.css"`, and change the task run by Netbeans to be `npm run css`, because `build` is [actually an npm (plumbing) command](https://docs.npmjs.com/cli/build), and it could get confusing understanding what's going on if you also have a script with the same name.

Closing as resolved.

**Comment by paul-landaeta-tierconnect-com** [comment]
I solved with "npm run ionic:build"
