### ISSUE TITLE
cann't create user

### ISSUE THREAD

**Issue by BarathG** [npm/npm#8198]
npm adduser throwing below error,

```
F:\checking>npm adduser
Username: barath
Password:
Email: (this IS public) barath@skava.com
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\Progs\\nodejs\\\\node.exe" "D:\\Progs\\nodejs\\node_modules\\
npm\\bin\\npm-cli.js" "adduser"
npm ERR! node v0.12.2
npm ERR! npm  v2.9.1
npm ERR! code E400

npm ERR! Unknown error while authenticating : -/user/org.couchdb.user:barath
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     F:\checking\npm-debug.log
```

**Comment by smikes** [comment]
Is this still a problem for you?  This looks like it might have been a transient problem with the registry.

If you're still seeing the problem, could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

Thanks!

**Comment by BarathG** [comment]
hi smikes   i having same problem now also have run the cmd with -d have pasted the cmd log here

C:\Users\barath\AppData\Roaming\npm>npm adduser -d
npm info it worked if it ends with ok
npm info using npm@2.9.1
npm info using node@v0.12.2
Username: barath
Password:
Email: (this IS public) barath@skava.com
npm info attempt registry request try #1 at 10:46:20 AM
npm http request PUT https://registry.npmjs.org/-/user/org.couchdb.user:barath
npm http 400 https://registry.npmjs.org/-/user/org.couchdb.user:barath
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\Progs\\nodejs\\\\node.exe" "D:\\Progs\\nodejs\\node_modules
npm\\bin\\npm-cli.js" "adduser" "-d"
npm ERR! node v0.12.2
npm ERR! npm  v2.9.1
npm ERR! code E400

npm ERR! Unknown error while authenticating : -/user/org.couchdb.user:barath
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\barath\AppData\Roaming\npm\npm-debug.log

and also have created a gist with my npm-debug.log link is added below
https://gist.github.com/BarathG/794cc0c74baaa9b1c0fc

**Comment by chrisdevereux** [comment]
I got this error when I tried to add an account with a username that is already taken.

**Comment by gauthierm** [comment]
I got this error today:

https://gist.github.com/gauthierm/0c034972f99a731bab84

I created my account on the website. Something (either the website, or the command line tool) messed up my password and I had to reset my password. After resetting the password, I was able to use `npm login` to log in.

**Comment by smikes** [comment]
@BarathG it looks like the username `barath` is taken by somebody else -- https://www.npmjs.com/~barath -- unless that's your account.

**Comment by benmccormick** [comment]
I'm seeing this issue today after registering through the web client.  Resetting my password has not resolved the issue.  

```
Username: benmccormick
Password:
Email: (this IS public) ben.mccormick@alumni.duke.edu
npm http PUT https://registry.npmjs.org/-/user/org.couchdb.user:benmccormick
npm http 400 https://registry.npmjs.org/-/user/org.couchdb.user:benmccormick
npm ERR! Error: Unknown error while authenticating : -/user/org.couchdb.user:benmccormick
npm ERR!     at RegClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:237:14)
npm ERR!     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:123:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:893:14)
npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:844:12)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 14.3.0
npm ERR! command "node" "/usr/local/bin/npm" "login"
npm ERR! cwd /Users/ben/Code/projects/marionette-service
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/ben/Code/projects/marionette-service/npm-debug.log
npm ERR! not ok code 0
```

I'm able to login through the web client with no problems.

**Comment by smikes** [comment]
Ben— npm v1.4.3 is quite old and may have problems with the new version of the registry code. 

Can you try updating npm with 'sudo npm i -g npm@latest' ?

**Comment by benmccormick** [comment]
@smikes sorry, forgot to update.  That fixed the issue, thank you.

**Comment by PMA12** [comment]
Hi, i am facing below issue while adding user using command npm adduser. However, after creating a new user explicitly at npmjs.com and then trying to add user here at node command prompt allowed me to verify my code.
My question is why i was unable to create a new account from here?

npm ERR! node v0.12.4
npm ERR! npm  v2.12.0
npm ERR! code E400

npm ERR! Unknown error while authenticating : -/user/org.couchdb.user:pooh
npm ERR!

**Comment by avifoxi** [comment]
I'm seeing this as well, using login information that works fine in the web UI

```shell
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/6.2.1/bin/node" "/usr/local/bin/npm" "login"
npm ERR! node v6.2.1
npm ERR! npm  v3.9.3

npm ERR! 200 Could not create user
npm ERR! {"code":401,"message":"{\"message\":\"Bad credentials\",\"documentation_url\":\"https://developer.github.com/v3\"}","_etag":"\"217c25a17c5525789caddb63ef1d214a\""}
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

my debug log from the session:

```shell
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/6.2.1/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'login' ]
2 info using npm@3.9.3
3 info using node@v6.2.1
4 verbose adduser before first PUT { _id: 'org.couchdb.user:avi_ies',
4 verbose adduser   name: 'avi_ies',
4 verbose adduser   password: 'XXXXX',
4 verbose adduser   email: 'avi@chegg.com',
4 verbose adduser   type: 'user',
4 verbose adduser   roles: [],
4 verbose adduser   date: '2016-12-20T16:59:13.298Z' }
5 verbose request uri http://npm-proxy.ezbib.com/-/user/org.couchdb.user:avi_ies
6 verbose request new user, so can't send auth
7 info attempt registry request try #1 at 11:59:13 AM
8 verbose request id e6a3d1d184cdc18b
9 http request PUT http://npm-proxy.ezbib.com/-/user/org.couchdb.user:avi_ies
10 http 200 http://npm-proxy.ezbib.com/-/user/org.couchdb.user:avi_ies
11 verbose headers { server: 'nginx/1.10.1',
11 verbose headers   date: 'Tue, 20 Dec 2016 16:59:13 GMT',
11 verbose headers   'content-type': 'application/json; charset=utf-8',
11 verbose headers   'content-length': '126',
11 verbose headers   connection: 'keep-alive',
11 verbose headers   'x-powered-by': 'Sinopia/1.4.0',
11 verbose headers   etag: '"217c25a17c5525789caddb63ef1d214a"',
11 verbose headers   vary: 'Accept-Encoding',
11 verbose headers   'x-status-cat': 'http://flic.kr/p/aVuVsF' }
12 verbose request invalidating /Users/AviFox-Rosen/.npm/npm-proxy.ezbib.com/-/user/org.couchdb.user_3Aavi_ies on PUT
13 verbose adduser back [ null,
13 verbose adduser   { code: 401,
13 verbose adduser     message: '{"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}',
13 verbose adduser     _etag: '"217c25a17c5525789caddb63ef1d214a"' },
13 verbose adduser   '{"code":401,"message":"{\\"message\\":\\"Bad credentials\\",\\"documentation_url\\":\\"https://developer.github.com/v3\\"}"}' ]
14 verbose stack Error: 200 Could not create user
14 verbose stack {"code":401,"message":"{\"message\":\"Bad credentials\",\"documentation_url\":\"https://developer.github.com/v3\"}","_etag":"\"217c25a17c5525789caddb63ef1d214a\""}
14 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/adduser.js:112:17
14 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/adduser.js:73:16
14 verbose stack     at /usr/local/lib/node_modules/npm/lib/cache/caching-client.js:49:12
14 verbose stack     at next (/usr/local/lib/node_modules/npm/node_modules/rimraf/rimraf.js:74:7)
14 verbose stack     at CB (/usr/local/lib/node_modules/npm/node_modules/rimraf/rimraf.js:110:9)
14 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/rimraf/rimraf.js:136:14
14 verbose stack     at FSReqWrap.oncomplete (fs.js:117:15)
15 verbose cwd /Users/AviFox-Rosen/dev/__playground__/webcomponents/polymer-demo/polymer-first-elements
16 error Darwin 15.6.0
17 error argv "/usr/local/Cellar/node/6.2.1/bin/node" "/usr/local/bin/npm" "login"
18 error node v6.2.1
19 error npm  v3.9.3
20 error 200 Could not create user
20 error {"code":401,"message":"{\"message\":\"Bad credentials\",\"documentation_url\":\"https://developer.github.com/v3\"}","_etag":"\"217c25a17c5525789caddb63ef1d214a\""}
21 error If you need help, you may report this error at:
21 error     <https://github.com/npm/npm/issues>
22 verbose exit [ 1, true ]
```

**Comment by legodude17** [comment]
@avifoxi the error message looks like one from the `github` api, which makes no sense.

**Comment by avifoxi** [comment]
@legodude17 - thanks for checking in - I'm not sure exactly why, but this is resolved. See my edited comment above

**Comment by legodude17** [comment]
That is really odd. 😖  Glad it is fixed though.
