### ISSUE TITLE
Registry response to invalid package name (new, has caps)

### ISSUE THREAD

**Issue by smikes** [npm/npm#8206]
This issue exists to document the current status of a registry reponse to `npm publish` with an illegal package name (in this case, the package name contains a capital letter, and the package does not yet exist in the registry).

This was harvested with a modified version of `npm` that does not prevent publishing a package with caps in its name.

```
npm verb request invalidating /Users/smikes/.npm/registry.npmjs.org/Bogus on PUT
npm ERR! publish Failed PUT 500
npm verb stack Error: unexpected status code: 400 : Bogus
npm verb stack     at CachingRegistryClient.<anonymous> (/Users/smikes/src/github/npm-registry-client/lib/request.js:247:14)
npm verb stack     at Request._callback (/Users/smikes/src/github/npm-registry-client/lib/request.js:170:14)
npm verb stack     at Request.self.callback (/Users/smikes/src/github/npm-registry-client/node_modules/request/request.js:368:22)
npm verb stack     at emitTwo (events.js:87:13)
npm verb stack     at Request.emit (events.js:169:7)
npm verb stack     at Request.<anonymous> (/Users/smikes/src/github/npm-registry-client/node_modules/request/request.js:1219:14)
npm verb stack     at emitOne (events.js:82:20)
npm verb stack     at Request.emit (events.js:166:7)
npm verb stack     at IncomingMessage.<anonymous> (/Users/smikes/src/github/npm-registry-client/node_modules/request/request.js:1167:12)
npm verb stack     at emitNone (events.js:72:20)
npm verb statusCode 500
npm verb pkgid Bogus
npm verb cwd /Users/smikes/src/github/foo
npm ERR! Darwin 14.3.0
npm ERR! argv "/Users/smikes/.nvm/versions/io.js/v1.7.1/bin/iojs" "/Users/smikes/src/github/npm/cli.js" "-ddd" "publish"
npm ERR! node v1.7.1
npm ERR! npm  v2.9.0
npm ERR! code E500

npm ERR! unexpected status code: 400 : Bogus
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm verb exit [ 1, true ]

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/smikes/src/github/foo/npm-debug.log
```

**Comment by smikes** [comment]
Full log of current `npm`@`2.9.1` error (does not try to touch registry) - https://gist.github.com/smikes/d4e3c1f82a1301cb4dff

Full log of patched (no version assigned) npm log (does go to registry) - https://gist.github.com/smikes/594090a0056224c69d7f

**Comment by smikes** [comment]
Closing this.
