### ISSUE TITLE
Appcelerator installation Error - Win7 32 bit

### ISSUE THREAD

**Issue by lorod** [npm/npm#8211]
I tried to install AppCelerator Studio.
The installation finishes well but when I start the Studio I get this an error.
These are the full logs.
Any ideas?
Thanks Diego
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   '-g',
1 verbose cli   'install',
1 verbose cli   'appcelerator',
1 verbose cli   '--color',
1 verbose cli   'false' ]
2 info using npm@1.4.28
3 info using node@v0.10.37
4 verbose cache add [ 'appcelerator', null ]
5 verbose cache add name=undefined spec="appcelerator" args=["appcelerator",null]
6 verbose parsed url { protocol: null,
6 verbose parsed url   slashes: null,
6 verbose parsed url   auth: null,
6 verbose parsed url   host: null,
6 verbose parsed url   port: null,
6 verbose parsed url   hostname: null,
6 verbose parsed url   hash: null,
6 verbose parsed url   search: null,
6 verbose parsed url   query: null,
6 verbose parsed url   pathname: 'appcelerator',
6 verbose parsed url   path: 'appcelerator',
6 verbose parsed url   href: 'appcelerator' }
7 silly lockFile 3832f4a2-appcelerator appcelerator
8 verbose lock appcelerator C:\Users\lorod\AppData\Roaming\npm-cache\3832f4a2-appcelerator.lock
9 silly lockFile 3832f4a2-appcelerator appcelerator
10 silly lockFile 3832f4a2-appcelerator appcelerator
11 verbose addNamed [ 'appcelerator', '' ]
12 verbose addNamed [ null, '*' ]
13 silly lockFile 4f33e3e2-appcelerator appcelerator@
14 verbose lock appcelerator@ C:\Users\lorod\AppData\Roaming\npm-cache\4f33e3e2-appcelerator.lock
15 silly addNameRange { name: 'appcelerator', range: '*', hasData: false }
16 verbose request where is /appcelerator
17 verbose request registry http://registry.npmjs.org/
18 verbose request id 16dd9998586007f9
19 verbose url raw /appcelerator
20 verbose url resolving [ 'http://registry.npmjs.org/', './appcelerator' ]
21 verbose url resolved http://registry.npmjs.org/appcelerator
22 verbose request where is http://registry.npmjs.org/appcelerator
23 info trying registry request attempt 1 at 13:25:49
24 http GET http://registry.npmjs.org/appcelerator
25 http 200 http://registry.npmjs.org/appcelerator
26 silly registry.get cb [ 200,
26 silly registry.get   { date: 'Fri, 08 May 2015 11:25:49 GMT',
26 silly registry.get     server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
26 silly registry.get     'content-type': 'application/json',
26 silly registry.get     'cache-control': 'max-age=60',
26 silly registry.get     'content-length': '444656',
26 silly registry.get     'accept-ranges': 'none',
26 silly registry.get     via: '1.1 varnish',
26 silly registry.get     age: '0',
26 silly registry.get     'x-served-by': 'cache-ams4144-AMS',
26 silly registry.get     'x-cache': 'HIT',
26 silly registry.get     'x-cache-hits': '1',
26 silly registry.get     'x-timer': 'S1431084349.497568,VS0,VE384',
26 silly registry.get     vary: 'Accept',
26 silly registry.get     'keep-alive': 'timeout=5, max=100',
26 silly registry.get     connection: 'Keep-Alive' } ]
27 silly addNameRange number 2 { name: 'appcelerator', range: '*', hasData: true }
28 silly addNameRange versions [ 'appcelerator',
28 silly addNameRange   [ '0.0.1',
28 silly addNameRange     '0.0.2',
28 silly addNameRange     '0.0.3',
28 silly addNameRange     '0.0.4',
28 silly addNameRange     '0.0.5',
28 silly addNameRange     '0.0.6',
28 silly addNameRange     '0.0.7',
28 silly addNameRange     '0.0.8',
28 silly addNameRange     '0.0.9',
28 silly addNameRange     '0.0.10',
28 silly addNameRange     '0.0.11',
28 silly addNameRange     '0.0.12',
28 silly addNameRange     '0.0.13',
28 silly addNameRange     '0.0.14',
28 silly addNameRange     '0.0.15',
28 silly addNameRange     '0.0.16',
28 silly addNameRange     '0.0.17',
28 silly addNameRange     '0.0.18',
28 silly addNameRange     '0.0.19',
28 silly addNameRange     '0.0.20',
28 silly addNameRange     '0.0.21',
28 silly addNameRange     '0.0.22',
28 silly addNameRange     '0.0.23',
28 silly addNameRange     '0.0.24',
28 silly addNameRange     '0.0.25',
28 silly addNameRange     '0.0.26',
28 silly addNameRange     '0.0.28',
28 silly addNameRange     '0.0.29',
28 silly addNameRange     '0.0.30',
28 silly addNameRange     '0.0.31',
28 silly addNameRange     '0.0.32',
28 silly addNameRange     '0.0.33',
28 silly addNameRange     '0.0.34',
28 silly addNameRange     '0.0.35',
28 silly addNameRange     '0.0.36',
28 silly addNameRange     '0.0.37',
28 silly addNameRange     '0.0.38',
28 silly addNameRange     '0.0.40',
28 silly addNameRange     '0.0.41',
28 silly addNameRange     '0.0.42',
28 silly addNameRange     '0.0.43',
28 silly addNameRange     '0.0.44',
28 silly addNameRange     '0.0.45',
28 silly addNameRange     '0.0.46',
28 silly addNameRange     '0.0.47',
28 silly addNameRange     '0.0.48',
28 silly addNameRange     '0.0.49',
28 silly addNameRange     '0.0.50',
28 silly addNameRange     '0.0.51',
28 silly addNameRange     '0.0.52',
28 silly addNameRange     '0.0.53',
28 silly addNameRange     '0.0.54',
28 silly addNameRange     '0.0.55',
28 silly addNameRange     '0.0.56',
28 silly addNameRange     '0.0.57',
28 silly addNameRange     '0.0.58',
28 silly addNameRange     '0.0.59',
28 silly addNameRange     '0.0.60',
28 silly addNameRange     '0.0.61',
28 silly addNameRange     '0.0.62',
28 silly addNameRange     '0.0.63',
28 silly addNameRange     '0.0.64',
28 silly addNameRange     '0.0.65',
28 silly addNameRange     '0.0.66',
28 silly addNameRange     '0.0.67',
28 silly addNameRange     '0.0.68',
28 silly addNameRange     '0.0.69',
28 silly addNameRange     '0.0.70',
28 silly addNameRange     '0.0.71',
28 silly addNameRange     '0.0.72',
28 silly addNameRange     '0.0.73',
28 silly addNameRange     '0.0.74',
28 silly addNameRange     '0.0.75',
28 silly addNameRange     '0.0.76',
28 silly addNameRange     '0.0.77',
28 silly addNameRange     '0.0.78',
28 silly addNameRange     '0.0.79',
28 silly addNameRange     '0.0.80',
28 silly addNameRange     '0.0.81',
28 silly addNameRange     '0.0.82',
28 silly addNameRange     '0.0.83',
28 silly addNameRange     '0.0.84',
28 silly addNameRange     '0.0.85',
28 silly addNameRange     '0.0.86',
28 silly addNameRange     '0.0.87',
28 silly addNameRange     '0.0.88',
28 silly addNameRange     '0.0.89',
28 silly addNameRange     '0.0.90',
28 silly addNameRange     '0.0.91',
28 silly addNameRange     '0.0.92',
28 silly addNameRange     '0.0.93',
28 silly addNameRange     '0.0.94',
28 silly addNameRange     '0.0.95',
28 silly addNameRange     '0.0.96',
28 silly addNameRange     '0.0.97',
28 silly addNameRange     '0.0.98',
28 silly addNameRange     '0.0.99',
28 silly addNameRange     '0.0.100',
28 silly addNameRange     '0.0.101',
28 silly addNameRange     '0.0.102',
28 silly addNameRange     '0.0.103',
28 silly addNameRange     '0.0.104',
28 silly addNameRange     '0.0.105',
28 silly addNameRange     '0.0.106',
28 silly addNameRange     '0.0.107',
28 silly addNameRange     '0.0.108',
28 silly addNameRange     '0.0.109',
28 silly addNameRange     '0.0.110',
28 silly addNameRange     '0.0.111',
28 silly addNameRange     '0.0.112',
28 silly addNameRange     '0.0.113',
28 silly addNameRange     '0.0.114',
28 silly addNameRange     '0.0.115',
28 silly addNameRange     '0.0.116',
28 silly addNameRange     '0.0.117',
28 silly addNameRange     '0.0.118',
28 silly addNameRange     '0.0.119',
28 silly addNameRange     '0.1.0',
28 silly addNameRange     '0.1.1',
28 silly addNameRange     '0.1.2',
28 silly addNameRange     '0.1.3',
28 silly addNameRange     '0.1.4',
28 silly addNameRange     '0.1.5',
28 silly addNameRange     '0.1.6',
28 silly addNameRange     '0.1.7',
28 silly addNameRange     '0.1.8',
28 silly addNameRange     '0.1.9',
28 silly addNameRange     '0.1.10',
28 silly addNameRange     '0.1.11',
28 silly addNameRange     '0.1.12',
28 silly addNameRange     '0.1.13',
28 silly addNameRange     '0.1.14',
28 silly addNameRange     '0.1.15',
28 silly addNameRange     '0.1.16',
28 silly addNameRange     '0.1.17',
28 silly addNameRange     '0.1.18',
28 silly addNameRange     '0.1.19',
28 silly addNameRange     '0.1.20',
28 silly addNameRange     '0.1.22',
28 silly addNameRange     '0.1.23',
28 silly addNameRange     '0.3.0',
28 silly addNameRange     '0.3.1',
28 silly addNameRange     '0.3.2',
28 silly addNameRange     '0.3.3',
28 silly addNameRange     '0.3.4',
28 silly addNameRange     '0.3.5',
28 silly addNameRange     '0.3.6',
28 silly addNameRange     '0.3.7',
28 silly addNameRange     '0.3.8',
28 silly addNameRange     '0.3.9',
28 silly addNameRange     '0.3.10',
28 silly addNameRange     '0.3.11',
28 silly addNameRange     '0.3.12',
28 silly addNameRange     '0.3.13',
28 silly addNameRange     '0.3.14',
28 silly addNameRange     '0.3.15',
28 silly addNameRange     '0.3.16',
28 silly addNameRange     '0.3.17',
28 silly addNameRange     '0.3.18',
28 silly addNameRange     '0.3.19',
28 silly addNameRange     '0.3.21',
28 silly addNameRange     '0.3.22',
28 silly addNameRange     '0.3.23',
28 silly addNameRange     '0.3.24',
28 silly addNameRange     '0.3.25',
28 silly addNameRange     '0.3.26',
28 silly addNameRange     '0.3.27',
28 silly addNameRange     '0.3.28',
28 silly addNameRange     '0.3.29',
28 silly addNameRange     '0.3.30',
28 silly addNameRange     '0.3.31',
28 silly addNameRange     '0.3.32',
28 silly addNameRange     '0.3.33',
28 silly addNameRange     '0.3.34',
28 silly addNameRange     '0.3.35',
28 silly addNameRange     '0.3.36',
28 silly addNameRange     '0.3.37',
28 silly addNameRange     '0.3.38',
28 silly addNameRange     '0.3.39',
28 silly addNameRange     '0.3.40',
28 silly addNameRange     '0.3.41',
28 silly addNameRange     '0.3.42',
28 silly addNameRange     '0.3.43',
28 silly addNameRange     '0.3.44',
28 silly addNameRange     '0.3.45',
28 silly addNameRange     '0.3.46',
28 silly addNameRange     '0.3.47',
28 silly addNameRange     '0.3.48',
28 silly addNameRange     '0.3.49',
28 silly addNameRange     '0.3.50',
28 silly addNameRange     '0.3.51',
28 silly addNameRange     '0.3.52',
28 silly addNameRange     '0.3.53',
28 silly addNameRange     '0.3.54',
28 silly addNameRange     '0.3.55' ] ]
29 verbose addNamed [ 'appcelerator', '0.3.55' ]
30 verbose addNamed [ '0.3.55', '0.3.55' ]
31 silly lockFile 69e2597e-appcelerator-0-3-55 appcelerator@0.3.55
32 verbose lock appcelerator@0.3.55 C:\Users\lorod\AppData\Roaming\npm-cache\69e2597e-appcelerator-0-3-55.lock
33 silly lockFile 200b2765-elerator-appcelerator-0-3-55-tgz http://registry.npmjs.org/appcelerator/-/appcelerator-0.3.55.tgz
34 verbose lock http://registry.npmjs.org/appcelerator/-/appcelerator-0.3.55.tgz C:\Users\lorod\AppData\Roaming\npm-cache\200b2765-elerator-appcelerator-0-3-55-tgz.lock
35 verbose addRemoteTarball [ 'http://registry.npmjs.org/appcelerator/-/appcelerator-0.3.55.tgz',
35 verbose addRemoteTarball   'd310b51748bbc379b63a2b144809b64c077300ab' ]
36 info retry fetch attempt 1 at 13:25:50
37 verbose fetch to= C:\Users\lorod\AppData\Local\Temp\npm-6968-DKFSdwXX\registry.npmjs.org\appcelerator\-\appcelerator-0.3.55.tgz
38 http GET http://registry.npmjs.org/appcelerator/-/appcelerator-0.3.55.tgz
39 http 403 http://registry.npmjs.org/appcelerator/-/appcelerator-0.3.55.tgz
40 error fetch failed http://registry.npmjs.org/appcelerator/-/appcelerator-0.3.55.tgz
41 silly lockFile 200b2765-elerator-appcelerator-0-3-55-tgz http://registry.npmjs.org/appcelerator/-/appcelerator-0.3.55.tgz
42 silly lockFile 200b2765-elerator-appcelerator-0-3-55-tgz http://registry.npmjs.org/appcelerator/-/appcelerator-0.3.55.tgz
43 silly lockFile 69e2597e-appcelerator-0-3-55 appcelerator@0.3.55
44 silly lockFile 69e2597e-appcelerator-0-3-55 appcelerator@0.3.55
45 silly lockFile 4f33e3e2-appcelerator appcelerator@
46 silly lockFile 4f33e3e2-appcelerator appcelerator@
47 error Error: 403 Forbidden
47 error     at WriteStream.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\fetch.js:58:12)
47 error     at WriteStream.emit (events.js:117:20)
47 error     at evalmachine.<anonymous>:1610:14
47 error     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:102:5
47 error     at Object.oncomplete (evalmachine.<anonymous>:108:15)
48 error If you need help, you may report this *entire* log,
48 error including the npm and node versions, at:
48 error     <http://github.com/npm/npm/issues>
49 error System Windows_NT 6.1.7601
50 error command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "-g" "install" "appcelerator" "--color" "false"
51 error cwd C:\
52 error node -v v0.10.37
53 error npm -v 1.4.28
54 verbose exit [ 1, true ]
```

**Comment by smikes** [comment]
There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.4. Can you try updating your npm installation?

To update npm on Windows, follow the instructions here: https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows 

After you update `npm`, if you still see this problem, could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

Thanks!

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
