### ISSUE TITLE
Can't launch the first search

### ISSUE THREAD

**Issue by JimArchiviste** [npm/npm#8218]
I tried to launch my first npm research but I get the file npm-debug.log  :
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'search',
1 verbose cli   'postgresql',
1 verbose cli   '--verbose' ]
2 info using npm@1.4.28
3 info using node@v0.10.38
4 verbose node symlink /usr/bin/node
5 verbose config Skipping project config: /home/jimkabatard/.npmrc. (matches userconfig)
6 info get /home/jimkabatard/.npm/registry.npmjs.org/-/all/.cache.json
7 warn Building the local index for the first time, please be patient
8 verbose request where is /-/all
9 verbose request registry https://registry.npmjs.org/
10 verbose request id dfad077371f000e8
11 verbose url raw /-/all
12 verbose url resolving [ 'https://registry.npmjs.org/', './-/all' ]
13 verbose url resolved https://registry.npmjs.org/-/all
14 verbose request where is https://registry.npmjs.org/-/all
15 info trying registry request attempt 1 at 05:11:28
16 http GET https://registry.npmjs.org/-/all
17 http 503 https://registry.npmjs.org/-/all
18 verbose bad json <?xml version="1.0" encoding="utf-8"?>
18 verbose bad json <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
18 verbose bad json  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
18 verbose bad json <html>
18 verbose bad json   <head>
18 verbose bad json     <title>503 backend read error</title>
18 verbose bad json   </head>
18 verbose bad json   <body>
18 verbose bad json     <h1>Error 503 backend read error</h1>
18 verbose bad json     <p>backend read error</p>
18 verbose bad json     <h3>Guru Mediation:</h3>
18 verbose bad json     <p>Details: cache-lcy1124-LCY 1431162748 1805070941</p>
18 verbose bad json     <hr>
18 verbose bad json     <p>Varnish cache server</p>
18 verbose bad json   </body>
18 verbose bad json </html>
19 error registry error parsing json
20 info retry will retry, error on last attempt: SyntaxError: Unexpected token <
20 info retry
20 info retry <?xml version="1.0" encoding="utf-8"?>
20 info retry <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
20 info retry  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
20 info retry <html>
20 info retry   <head>
20 info retry     <title>503 backend read error</title>
20 info retry   </head>
20 info retry   <body>
20 info retry     <h1>Error 503 backend read error</h1>
20 info retry     <p>backend read error</p>
20 info retry     <h3>Guru Mediation:</h3>
20 info retry     <p>Details: cache-lcy1124-LCY 1431162748 1805070941</p>
20 info retry     <hr>
20 info retry     <p>Varnish cache server</p>
20 info retry   </body>
20 info retry </html>
21 info trying registry request attempt 2 at 05:12:38
22 http GET https://registry.npmjs.org/-/all
23 http 503 https://registry.npmjs.org/-/all
24 verbose bad json <?xml version="1.0" encoding="utf-8"?>
24 verbose bad json <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
24 verbose bad json  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
24 verbose bad json <html>
24 verbose bad json   <head>
24 verbose bad json     <title>503 backend read error</title>
24 verbose bad json   </head>
24 verbose bad json   <body>
24 verbose bad json     <h1>Error 503 backend read error</h1>
24 verbose bad json     <p>backend read error</p>
24 verbose bad json     <h3>Guru Mediation:</h3>
24 verbose bad json     <p>Details: cache-lcy1132-LCY 1431162818 1638291956</p>
24 verbose bad json     <hr>
24 verbose bad json     <p>Varnish cache server</p>
24 verbose bad json   </body>
24 verbose bad json </html>
25 error registry error parsing json
26 info retry will retry, error on last attempt: SyntaxError: Unexpected token <
26 info retry
26 info retry <?xml version="1.0" encoding="utf-8"?>
26 info retry <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
26 info retry  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
26 info retry <html>
26 info retry   <head>
26 info retry     <title>503 backend read error</title>
26 info retry   </head>
26 info retry   <body>
26 info retry     <h1>Error 503 backend read error</h1>
26 info retry     <p>backend read error</p>
26 info retry     <h3>Guru Mediation:</h3>
26 info retry     <p>Details: cache-lcy1132-LCY 1431162818 1638291956</p>
26 info retry     <hr>
26 info retry     <p>Varnish cache server</p>
26 info retry   </body>
26 info retry </html>
27 info trying registry request attempt 3 at 05:14:38
28 http GET https://registry.npmjs.org/-/all
29 http 503 https://registry.npmjs.org/-/all
30 verbose bad json <?xml version="1.0" encoding="utf-8"?>
30 verbose bad json <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
30 verbose bad json  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
30 verbose bad json <html>
30 verbose bad json   <head>
30 verbose bad json     <title>503 backend read error</title>
30 verbose bad json   </head>
30 verbose bad json   <body>
30 verbose bad json     <h1>Error 503 backend read error</h1>
30 verbose bad json     <p>backend read error</p>
30 verbose bad json     <h3>Guru Mediation:</h3>
30 verbose bad json     <p>Details: cache-lcy1120-LCY 1431162938 1880255771</p>
30 verbose bad json     <hr>
30 verbose bad json     <p>Varnish cache server</p>
30 verbose bad json   </body>
30 verbose bad json </html>
31 error registry error parsing json
32 verbose headers { server: 'Varnish',
32 verbose headers   'retry-after': '0',
32 verbose headers   'content-type': 'text/html; charset=utf-8',
32 verbose headers   'content-length': '448',
32 verbose headers   'accept-ranges': 'bytes',
32 verbose headers   date: 'Sat, 09 May 2015 09:15:38 GMT',
32 verbose headers   via: '1.1 varnish',
32 verbose headers   connection: 'close',
32 verbose headers   'x-served-by': 'cache-lcy1120-LCY',
32 verbose headers   'x-cache': 'MISS',
32 verbose headers   'x-cache-hits': '0',
32 verbose headers   'x-timer': 'S1431162878.869862,VS0,VE59996' }
33 error SyntaxError: Unexpected token <
33 error
33 error <?xml version="1.0" encoding="utf-8"?>
33 error <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
33 error  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
33 error <html>
33 error   <head>
33 error     <title>503 backend read error</title>
33 error   </head>
33 error   <body>
33 error     <h1>Error 503 backend read error</h1>
33 error     <p>backend read error</p>
33 error     <h3>Guru Mediation:</h3>
33 error     <p>Details: cache-lcy1120-LCY 1431162938 1880255771</p>
33 error     <hr>
33 error     <p>Varnish cache server</p>
33 error   </body>
33 error </html>
33 error
33 error     at Object.parse (native)
33 error     at RegClient.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:274:23)
33 error     at Request._callback (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:246:65)
33 error     at Request.self.callback (/usr/lib/node_modules/npm/node_modules/request/request.js:236:22)
33 error     at Request.emit (events.js:98:17)
33 error     at Request.<anonymous> (/usr/lib/node_modules/npm/node_modules/request/request.js:1142:14)
33 error     at Request.emit (events.js:117:20)
33 error     at IncomingMessage.<anonymous> (/usr/lib/node_modules/npm/node_modules/request/request.js:1096:12)
33 error     at IncomingMessage.emit (events.js:117:20)
33 error     at _stream_readable.js:944:16
34 error If you need help, you may report this *entire* log,
34 error including the npm and node versions, at:
34 error     <http://github.com/npm/npm/issues>
35 error System Linux 2.6.32-042stab094.8
36 error command "/usr/bin/node" "/usr/bin/npm" "search" "postgresql" "--verbose"
37 error cwd /home/jimkabatard
38 error node -v v0.10.38
39 error npm -v 1.4.28
40 error type unexpected_token
41 verbose exit [ 1, true ]
```
Can you help me please ?

**Comment by smikes** [comment]
It looks like you are getting an error page -- possibly from a proxy? --- instead of the package index.  You may need to configure npm to use your local proxy --

```
npm config set proxy http://host:port
```



There have been a lot of improvements to npm -- especially around conflicts and race conditions during install -- since 1.4. Can you try updating your npm installation?

To update npm, run `sudo npm -g install npm@latest`.

For some Linux distributions (Debian/Ubuntu and RedHat/CentOS), the latest node version provided by the distribution may lag behind the stable version. [Here are instructions from NodeSource](https://github.com/nodesource/distributions) on getting the latest node.

Thanks!

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
