### ISSUE TITLE
Can't install: Error: Invalid version: ";"

### ISSUE THREAD

**Issue by togakangaroo** [npm/npm#8224]
I just published an [npm package](https://www.npmjs.com/package/thee) but installing it doesn't work. Tells me to ask here. What's going on?

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'init' ]
2 info using npm@1.4.28
3 info using node@v0.10.32
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 silly package data undefined
6 info init written successfully
7 error Error: Invalid version: ";"
7 error     at Object.module.exports.fixVersionField (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\node_modules\normalize-package-data\lib\fixer.js:183:13)
7 error     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\node_modules\normalize-package-data\lib\normalize.js:30:38
7 error     at Array.forEach (native)
7 error     at normalize (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\node_modules\normalize-package-data\lib\normalize.js:29:15)
7 error     at final (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:342:33)
7 error     at then (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:126:33)
7 error     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:316:48
7 error     at evalmachine.<anonymous>:207:20
7 error     at OpenReq.Req.done (C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:141:5)
7 error     at OpenReq.done (C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:61:22)
8 error If you need help, you may report this *entire* log,
8 error including the npm and node versions, at:
8 error     <http://github.com/npm/npm/issues>
9 error System Windows_NT 6.2.9200
10 error command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "init"
11 error cwd W:\temp\foo
12 error node -v v0.10.32
13 error npm -v 1.4.28
14 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
@togakangaroo 

> but installing it doesn't work

That log says you are running `npm init` though.

**Comment by aredridel** [comment]
Indeed. Also, that's a really old npm.

**Comment by togakangaroo** [comment]
hmm....good point. Thanks!
