### ISSUE TITLE
problems with npm shrinkwrap + fibers

### ISSUE THREAD

**Issue by eaortiz** [npm/npm#8246]
Can anyone help me with this?

```
npm ERR! Error: Problems were encountered
npm ERR! Please correct and try again.
npm ERR! extraneous: fibers@1.0.1 /Users/eaortiz/Documents/GITHUB/dina/node_modules/fibers
npm ERR!     at shrinkwrap_ (/usr/local/lib/node_modules/npm/lib/shrinkwrap.js:30:15)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/shrinkwrap.js:24:5
npm ERR!     at /usr/local/lib/node_modules/npm/lib/ls.js:45:30
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js:130:5
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js:244:14
npm ERR!     at cb (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js:244:14
npm ERR!     at cb (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js:244:14
npm ERR!     at cb (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 14.3.0
npm ERR! command "node" "/usr/local/bin/npm" "shrinkwrap"
npm ERR! cwd /Users/eaortiz/Documents/GITHUB/dina
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/eaortiz/Documents/GITHUB/dina/npm-debug.log
npm ERR! not ok code 0
```

**Comment by KenanY** [comment]
```
npm ERR! extraneous: fibers@1.0.1 /Users/eaortiz/Documents/GITHUB/dina/node_modules/fibers
```

@eaortiz I'm guessing that `fibers` is not listed as a dependency in your `package.json`?

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
