### ISSUE TITLE
problems with  npm start

### ISSUE THREAD

**Issue by aby913** [npm/npm#8247]
the envoirment is win8.1
```
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4

npm ERR! missing script: start
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\test\npm-debug.log
```

the npm-dubug.log  is:
-------------------------------------
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 verbose stack Error: missing script: start
5 verbose stack     at run (C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:165:19)
5 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:81:5
5 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:52:40
5 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:376:33
5 verbose stack     at checkBinReferences_ (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:341:59)
5 verbose stack     at final (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:373:17)
5 verbose stack     at then (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:127:33)
5 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:267:40
5 verbose stack     at evalmachine.<anonymous>:334:14
5 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:102:5
6 verbose cwd C:\test
7 error Windows_NT 6.3.9600
8 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
9 error node v0.12.2
10 error npm  v2.7.4
11 error missing script: start
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
````
npm ERR! missing script: start
```

@aby913 Have you [defined](https://docs.npmjs.com/misc/scripts) a start script in your `package.json`? Otherwise, what are you _expecting_ to happen when you run [`npm start`](https://docs.npmjs.com/cli/start)?

**Comment by othiym23** [comment]
@KenanY has pointed you in the right direction – you must have a `package.json` file containing  a `scripts` object with a `start` property. Closing as resolved.

**Comment by msarabia** [comment]
Hi, I was having this problem. The problem was in node_modules/.bin directory, some files are no reference correctly. 

If you have windows 10, not install npm dependencies in bash mode.

I hope that helps.
