### ISSUE TITLE
When I use meteor up's "mup deploy" command, I get the following error

### ISSUE THREAD

**Issue by psoares** [npm/npm#8258]
I'm trying to deploy a meteor app to a CentOS 6.6 server using meteor up. It works fine up to the point where I install the mongodb_aggregation package to my app. After that point, when I run mup deploy, I get an error at the last step requesting that I send you the stacktrace, that's why I'm posting this here... so here it is :
 
```
x Invoking deployment process: FAILED
	
	-----------------------------------STDERR-----------------------------------
	nable to connect a socket (Connection refused)
	npm ERR! Error: Command failed: github.com[0: 192.30.252.128]: errno=Connection refused
	npm ERR! fatal: unable to connect a socket (Connection refused)
	npm ERR! 
	npm ERR!     at ChildProcess.exithandler (child_process.js:658:15)
	npm ERR!     at ChildProcess.emit (events.js:98:17)
	npm ERR!     at maybeClose (child_process.js:766:16)
	npm ERR!     at Socket.<anonymous> (child_process.js:979:11)
	npm ERR!     at Socket.emit (events.js:95:17)
	npm ERR!     at Pipe.close (net.js:466:12)
	npm ERR! If you need help, you may report this *entire* log,
	npm ERR! including the npm and node versions, at:
	npm ERR!     <http://github.com/npm/npm/issues>
	
	npm ERR! System Linux 2.6.32-504.8.1.el6.x86_64
	npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
	npm ERR! cwd /opt/LQDB/tmp/bundle/programs/server/npm/mrt_mongodb-aggregation/node_modules/mongodb
	npm ERR! node -v v0.10.38
	npm ERR! npm -v 1.4.28
	npm ERR! code 128
	npm ERR! not ok code 0
	-----------------------------------STDOUT-----------------------------------
	os/build'
	  SOLINK_MODULE(target) Release/obj.target/kerberos.node
	  SOLINK_MODULE(target) Release/obj.target/kerberos.node: Finished
	  COPY Release/kerberos.node
	make: Leaving directory `/opt/LQDB/tmp/bundle/programs/server/npm/mrt_mongodb-aggregation/node_modules/mongodb/node_modules/kerberos/build'
	
	> bson@0.2.2 install /opt/LQDB/tmp/bundle/programs/server/npm/mrt_mongodb-aggregation/node_modules/mongodb/node_modules/bson
	> (node-gyp rebuild 2> builderror.log) || (exit 0)
	
	make: Entering directory `/opt/LQDB/tmp/bundle/programs/server/npm/mrt_mongodb-aggregation/node_modules/mongodb/node_modules/bson/build'
	  CXX(target) Release/obj.target/bson/ext/bson.o
	  SOLINK_MODULE(target) Release/obj.target/bson.node
	  SOLINK_MODULE(target) Release/obj.target/bson.node: Finished
	  COPY Release/bson.node
	make: Leaving directory `/opt/LQDB/tmp/bundle/programs/server/npm/mrt_mongodb-aggregation/node_modules/mongodb/node_modules/bson/build'
```

I'm able to connect to github.com through elinks on the server I'm deploying the application to.

Thanks in advance for your help.

**Comment by KenanY** [comment]
@psoares Are you still seeing this issue?

**Comment by KenanY** [comment]
Closing as abandoned.
