### ISSUE TITLE
npm install | looks like dustjs-linkedin

### ISSUE THREAD

**Issue by baljeety** [npm/npm#8266]
```
{"name":"dustjs-linkedin","version":"2.2.10","author":{"name":"Aleksander Williams"},"description":"Asynchronous templates for the browser and node.js ( L
     [exec] npm ERR!     at Object.parse (native)
     [exec] npm ERR!     at RegClient.<anonymous> (Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:274:23)
     [exec] npm ERR!     at Request._callback (Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:246:65)
     [exec] npm ERR!     at Request.self.callback (Program Files\nodejs\node_modules\npm\node_modules\request\request.js:236:22)
     [exec] npm ERR!     at Request.emit (events.js:98:17)
     [exec] npm ERR!     at Request.<anonymous> (Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1142:14)
     [exec] npm ERR!     at Request.emit (events.js:117:20)
     [exec] npm ERR!     at IncomingMessage.<anonymous> (Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1096:12)
     [exec] npm ERR!     at IncomingMessage.emit (events.js:117:20)
     [exec] npm ERR!     at _stream_readable.js:944:16
     [exec] npm ERR! If you need help, you may report this *entire* log,
     [exec] npm ERR! including the npm and node versions, at:
     [exec] npm ERR!     <http://github.com/npm/npm/issues>
     [exec]
     [exec] npm ERR! System Windows_NT 6.2.9200
     [exec] npm ERR! command "Program Files\\nodejs\\\\node.exe" "Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "-p" "install"
     [exec] npm ERR! cwd srccode
     [exec] npm ERR! node -v v0.10.35
     [exec] npm ERR! npm -v 1.4.28
     [exec] npm ERR! type unexpected_eos
     [exec] npm
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

**Comment by othiym23** [comment]
There's not enough output here for us to say what's going wrong. Is there an `npm-debug.log` file being created in the build direcotry? It looks like something might be truncating the data returned by the registry (like a proxy or something else at the network level).

**Comment by baljeety** [comment]
Thanks for the update it was just a network issue @ that day only. May be from server slowness issue on git.
