### ISSUE TITLE
Misleading error when trying to register module name that already exists

### ISSUE THREAD

**Issue by oliversalzburg** [npm/npm#8269]
``` shell
Oliver@OLIVER-HOME /p/try-require (master)
$ npm publish
npm ERR! publish Failed PUT 404
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Users\\Oliver\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "publish"
npm ERR! node v0.10.38
npm ERR! npm  v2.9.1
npm ERR! code E404

npm ERR! 404 Not found : try-require
npm ERR! 404
npm ERR! 404 'try-require' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     p:\try-require\npm-debug.log
```
### `npm-debug.log`

```
0 info it worked if it ends with ok
1 verbose cli [ 'c:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'c:\\Users\\Oliver\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'publish' ]
2 info using npm@2.9.1
3 info using node@v0.10.38
4 verbose publish [ '.' ]
5 silly cache add args [ '.', null ]
6 verbose cache add spec .
7 silly cache add parsed spec { raw: '.',
7 silly cache add   scope: null,
7 silly cache add   name: null,
7 silly cache add   rawSpec: '.',
7 silly cache add   spec: 'p:\\try-require',
7 silly cache add   type: 'directory' }
8 verbose addLocalDirectory C:\Users\Oliver\AppData\Roaming\npm-cache\try-require\1.0.0\package.tgz not in flight; packing
9 verbose tar pack [ 'C:\\Users\\Oliver\\AppData\\Roaming\\npm-cache\\try-require\\1.0.0\\package.tgz',
9 verbose tar pack   'p:\\try-require' ]
10 verbose tarball C:\Users\Oliver\AppData\Roaming\npm-cache\try-require\1.0.0\package.tgz
11 verbose folder p:\try-require
12 info prepublish try-require@1.0.0
13 verbose addLocalTarball adding from inside cache C:\Users\Oliver\AppData\Roaming\npm-cache\try-require\1.0.0\package.tgz
14 silly cache afterAdd try-require@1.0.0
15 verbose afterAdd C:\Users\Oliver\AppData\Roaming\npm-cache\try-require\1.0.0\package\package.json not in flight; writing
16 verbose afterAdd C:\Users\Oliver\AppData\Roaming\npm-cache\try-require\1.0.0\package\package.json written
17 silly publish { name: 'try-require',
17 silly publish   version: '1.0.0',
17 silly publish   description: 'try-catch wrapper around require()',
17 silly publish   main: 'index.js',
17 silly publish   scripts: { test: 'echo "Error: no test specified" && exit 1' },
17 silly publish   repository:
17 silly publish    { type: 'git',
17 silly publish      url: 'git+https://github.com/oliversalzburg/try-require.git' },
17 silly publish   author: { name: 'Oliver Salzburg', email: 'oliver.salzburg@gmail.com' },
17 silly publish   license: 'MIT',
17 silly publish   bugs: { url: 'https://github.com/oliversalzburg/try-require/issues' },
17 silly publish   homepage: 'https://github.com/oliversalzburg/try-require#readme',
17 silly publish   readme: '# try-require\ntry-catch wrapper around require()\n',
17 silly publish   readmeFilename: 'README.md',
17 silly publish   gitHead: '16f46479587e306f7642691fdfb38ede546e622e',
17 silly publish   _id: 'try-require@1.0.0',
17 silly publish   _shasum: 'ca1e4b79df986b60beb3ab7e5ce3cbd00884c342',
17 silly publish   _from: '.' }
18 verbose getPublishConfig undefined
19 silly mapToRegistry name try-require
20 silly mapToRegistry using default registry
21 silly mapToRegistry registry https://registry.npmjs.org/
22 silly mapToRegistry uri https://registry.npmjs.org/try-require
23 verbose publish registryBase https://registry.npmjs.org/
24 silly publish uploading C:\Users\Oliver\AppData\Roaming\npm-cache\try-require\1.0.0\package.tgz
25 verbose request uri https://registry.npmjs.org/try-require
26 verbose request sending authorization for write operation
27 info attempt registry request try #1 at 16:08:26
28 verbose request using bearer token for auth
29 verbose request id 1fb9035f48366a8d
30 http request PUT https://registry.npmjs.org/try-require
31 http 404 https://registry.npmjs.org/try-require
32 verbose headers { 'content-type': 'application/json',
32 verbose headers   'cache-control': 'max-age=0',
32 verbose headers   'content-length': '21',
32 verbose headers   'accept-ranges': 'bytes',
32 verbose headers   date: 'Thu, 14 May 2015 14:08:20 GMT',
32 verbose headers   via: '1.1 varnish',
32 verbose headers   connection: 'keep-alive',
32 verbose headers   'x-served-by': 'cache-fra1247-FRA',
32 verbose headers   'x-cache': 'MISS',
32 verbose headers   'x-cache-hits': '0',
32 verbose headers   'x-timer': 'S1431612500.182396,VS0,VE678' }
33 verbose request invalidating C:\Users\Oliver\AppData\Roaming\npm-cache\registry.npmjs.org\try-require on PUT
34 error publish Failed PUT 404
35 verbose stack Error: Not found : try-require
35 verbose stack     at CachingRegistryClient.<anonymous> (c:\Users\Oliver\AppData\Roaming\npm\node_modules\npm\node_modules\npm-registry-client\lib\request.js:247:14)
35 verbose stack     at Request._callback (c:\Users\Oliver\AppData\Roaming\npm\node_modules\npm\node_modules\npm-registry-client\lib\request.js:170:14)
35 verbose stack     at Request.self.callback (c:\Users\Oliver\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.js:368:22)
35 verbose stack     at Request.emit (events.js:98:17)
35 verbose stack     at Request.<anonymous> (c:\Users\Oliver\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.js:1219:14)
35 verbose stack     at Request.emit (events.js:117:20)
35 verbose stack     at IncomingMessage.<anonymous> (c:\Users\Oliver\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.js:1167:12)
35 verbose stack     at IncomingMessage.emit (events.js:117:20)
35 verbose stack     at _stream_readable.js:944:16
35 verbose stack     at process._tickCallback (node.js:448:13)
36 verbose statusCode 404
37 verbose pkgid try-require
38 verbose cwd p:\try-require
39 error Windows_NT 6.1.7601
40 error argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Users\\Oliver\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "publish"
41 error node v0.10.38
42 error npm  v2.9.1
43 error code E404
44 error 404 Not found : try-require
44 error 404
44 error 404 'try-require' is not in the npm registry.
44 error 404 You should bug the author to publish it (or use the name yourself!)
44 error 404
44 error 404 Note that you can also install from a
44 error 404 tarball, folder, http url, or git url.
45 verbose exit [ 1, true ]
```

**Comment by sam-github** [comment]
I bumped into this, too. In my case, I'm publishing an update to a module that one of my co-workers has published, but didn't add me as owner to.
