### ISSUE TITLE
cannot login with NPM

### ISSUE THREAD

**Issue by cfsghost** [npm/npm#8273]
got this error message when i re-login.

```
$ npm login
Username: fredchien
Password: 
Email: (cfsghost@gmail.com) cfsghost@gmail.com
npm http PUT https://registry.npmjs.org/-/user/org.couchdb.user:fredchien
npm http 400 https://registry.npmjs.org/-/user/org.couchdb.user:fredchien
npm ERR! Error: Unknown error while authenticating : -/user/org.couchdb.user:fredchien
npm ERR!     at RegClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:275:14)
npm ERR!     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:123:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:893:14)
npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:844:12)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/isaacs/npm/issues>

npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "login"
npm ERR! cwd /home/fred/opensource-work/brig
npm ERR! node -v v0.10.24
npm ERR! npm -v 1.3.21
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/fred/opensource-work/brig/npm-debug.log
npm ERR! not ok code 0
```

**Comment by cfsghost** [comment]
Forget it. That's happened because I have old NPM.
