### ISSUE TITLE
Error publishing new npm package

### ISSUE THREAD

**Issue by marcosbasualdo** [npm/npm#8274]
NPM version: 2.9.1
Node version: v0.12.3
```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'publish' ]
2 info using npm@2.9.1
3 info using node@v0.12.3
4 verbose publish [ '.' ]
5 silly cache add args [ '.', null ]
6 verbose cache add spec .
7 silly cache add parsed spec { raw: '.',
7 silly cache add   scope: null,
7 silly cache add   name: null,
7 silly cache add   rawSpec: '.',
7 silly cache add   spec: '/Users/mbasualdo/Desktop/UnclosedHtmlTags',
7 silly cache add   type: 'directory' }
8 verbose addLocalDirectory /var/root/.npm/UnclosedHtmlTags/1.0.0/package.tgz not in flight; packing
9 verbose tar pack [ '/var/root/.npm/UnclosedHtmlTags/1.0.0/package.tgz',
9 verbose tar pack   '/Users/mbasualdo/Desktop/UnclosedHtmlTags' ]
10 verbose tarball /var/root/.npm/UnclosedHtmlTags/1.0.0/package.tgz
11 verbose folder /Users/mbasualdo/Desktop/UnclosedHtmlTags
12 info prepublish UnclosedHtmlTags@1.0.0
13 verbose addLocalTarball adding from inside cache /var/root/.npm/UnclosedHtmlTags/1.0.0/package.tgz
14 silly cache afterAdd UnclosedHtmlTags@1.0.0
15 verbose afterAdd /var/root/.npm/UnclosedHtmlTags/1.0.0/package/package.json not in flight; writing
16 verbose afterAdd /var/root/.npm/UnclosedHtmlTags/1.0.0/package/package.json written
17 silly publish { name: 'UnclosedHtmlTags',
17 silly publish   version: '1.0.0',
17 silly publish   description: 'Script to find unclosed html tags',
17 silly publish   main: 'index.js',
17 silly publish   author: { name: 'Marcos Basualdo' },
17 silly publish   license: 'MIT',
17 silly publish   repository:
17 silly publish    { type: 'git',
17 silly publish      url: 'git+https://github.com/marcosbasualdo/UnclosedHtmlTags.git' },
17 silly publish   bugs: { url: 'https://github.com/marcosbasualdo/UnclosedHtmlTags/issues' },
17 silly publish   homepage: 'https://github.com/marcosbasualdo/UnclosedHtmlTags',
17 silly publish   scripts: { test: 'echo "Error: no test specified" && exit 1' },
17 silly publish   keywords: [ 'unclosed', 'html', 'tags', 'htmllint', 'validator' ],
17 silly publish   readme: '# UnclosedHtmlTags\nnode module to analyze ever html in a given directory and reports a list of files with unclosed html tags.\n',
17 silly publish   readmeFilename: 'README.md',
17 silly publish   gitHead: '0cd496b11c5b612e43505711757cb30bee7632ec',
17 silly publish   _id: 'UnclosedHtmlTags@1.0.0',
17 silly publish   _shasum: '4a9ad058f68fa42e34f534220b3373a3929c208d',
17 silly publish   _from: '.' }
18 verbose getPublishConfig undefined
19 silly mapToRegistry name UnclosedHtmlTags
20 silly mapToRegistry using default registry
21 silly mapToRegistry registry https://registry.npmjs.org/
22 silly mapToRegistry uri https://registry.npmjs.org/UnclosedHtmlTags
23 verbose publish registryBase https://registry.npmjs.org/
24 silly publish uploading /var/root/.npm/UnclosedHtmlTags/1.0.0/package.tgz
25 verbose stack Error: Invalid name: "UnclosedHtmlTags"
25 verbose stack     at ensureValidName (/usr/local/lib/node_modules/npm/node_modules/normalize-package-data/lib/fixer.js:310:15)
25 verbose stack     at Object.module.exports.fixNameField (/usr/local/lib/node_modules/npm/node_modules/normalize-package-data/lib/fixer.js:205:5)
25 verbose stack     at CachingRegistryClient.publish (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/publish.js:41:11)
25 verbose stack     at /usr/local/lib/node_modules/npm/lib/publish.js:134:14
25 verbose stack     at mapToRegistry (/usr/local/lib/node_modules/npm/lib/utils/map-to-registry.js:55:3)
25 verbose stack     at publish_ (/usr/local/lib/node_modules/npm/lib/publish.js:104:3)
25 verbose stack     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
25 verbose stack     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
25 verbose stack     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:14:28)
25 verbose stack     at chain (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
26 verbose cwd /Users/mbasualdo/Desktop/UnclosedHtmlTags
27 error Darwin 14.0.0
28 error argv "node" "/usr/local/bin/npm" "publish"
29 error node v0.12.3
30 error npm  v2.9.1
31 error Invalid name: "UnclosedHtmlTags"
32 error If you need help, you may report this error at:
32 error     <https://github.com/npm/npm/issues>
33 verbose exit [ 1, true ]
```

**Comment by othiym23** [comment]
```
31 error Invalid name: "UnclosedHtmlTags"
32 error If you need help, you may report this error at:
```

npm packages can't have uppercase letters in their names. The current package name restrictions are [documented here](https://github.com/npm/npm/blob/master/doc/files/package.json.md#name). Fix that, and your package should publish without issue!

**Comment by marcosbasualdo** [comment]
Did'nt see that line! Package published. Thank you!
