### ISSUE TITLE
when  install togetherjs,npm install error

### ISSUE THREAD

**Issue by whynotAC** [npm/npm#8276]
```
npm http 404 https://registry.npmjs.org/websocket-server
npm ERR! TypeError: Object.keys called on non-object
npm ERR!     at Function.keys (native)
npm ERR!     at installTargetsError (/usr/share/npm/lib/cache.js:708:24)
npm ERR!     at /usr/share/npm/lib/cache.js:638:10
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-51-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/lwl/togetherjs
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! type called_on_non_object
```

but when webbrowser  link https://registry.npmjs.org/websocket-server show that:

```
{"_id":"websocket-server","_rev":"50-e8e6385fa0fc9d06f284505cc6bb0ed9","name":"websocket-server","time":{"modified":"2014-02-26T20:01:15.774Z","created":"2011-03-25T07:49:32.039Z","1.0.4":"2011-03-25T07:49:32.039Z","1.0.5":"2011-03-25T07:49:32.039Z","1.0.51":"2011-03-25T07:49:32.039Z","1.0.52":"2011-03-25T07:49:32.039Z","1.0.53":"2011-03-25T07:49:32.039Z","1.1.00":"2011-03-25T07:49:32.039Z","1.2.00":"2011-03-25T07:49:32.039Z","1.3.00":"2011-03-25T07:49:32.039Z","1.3.01":"2011-03-25T07:49:32.039Z","1.3.02":"2011-03-25T07:49:32.039Z","1.3.03":"2011-03-25T07:49:32.039Z","1.3.50":"2011-03-25T07:49:32.039Z","1.3.52":"2011-03-25T07:49:32.039Z","1.3.53":"2011-03-25T07:49:32.039Z","1.4.00":"2011-03-25T07:49:32.039Z","1.4.01":"2011-03-25T07:49:32.039Z","1.4.02":"2011-03-25T07:49:32.039Z","1.4.03":"2011-03-28T04:51:52.219Z","1.4.04":"2011-06-20T22:40:23.167Z","1.1.0":"2014-02-26T20:01:15.771Z","1.2.0":"2014-02-26T20:01:15.772Z","1.3.0":"2014-02-26T20:01:15.772Z","1.3.1":"2014-02-26T20:01:15.772Z","1.3.2":"2014-02-26T20:01:15.772Z","1.3.3":"2014-02-26T20:01:15.773Z","1.4.0":"2014-02-26T20:01:15.773Z","1.4.1":"2014-02-26T20:01:15.773Z","1.4.2":"2014-02-26T20:01:15.773Z","1.4.3":"2014-02-26T20:01:15.774Z","1.4.4":"2014-02-26T20:01:15.774Z","unpublished":{"name":"miksago","time":"2014-09-24T12:00:42.269Z","tags":{"latest":"1.4.4","stable":"1.4.4"},"maintainers":[{"name":"miksago","email":"micheil@brandedcode.com"}],"description":"A WebSocket Server for node.js, 90-100% spec compatible.","versions":["1.0.4","1.0.5","1.0.51","1.0.52","1.0.53","1.3.50","1.3.52","1.3.53","1.1.0","1.2.0","1.3.0","1.3.1","1.3.2","1.3.3","1.4.0","1.4.1","1.4.2","1.4.3","1.4.4"]}},"_attachments":{}}
```

**Comment by KenanY** [comment]
@whynotAC `npm@1.3.10` is extremely old and has not been supported for the last several months. Could you try [upgrading](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-nix-osx-linux-etc) first?

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
