### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by SFoster84** [npm/npm#8288]
Hello,

I'm seeing this error on our team city build server and I can't determine how to troubleshoot it.  Can anyone point me in the right direction?  Thanks!  -Scott

```
 npm WARN `git config --get remote.origin.url` returned wrong result (git://github.com/isaacs/js-yaml) fatal: failed to stat '.': No such file or directory
[19:41:29][Step 3/5] npm ERR! git clone git://github.com/isaacs/js-yaml fatal: Could not switch to 'C:\Windows\system32\config\systemprofile\AppData\Roaming\npm-cache\_git-remotes\': No such file or directory
[19:41:30][Step 3/5] npm ERR! Error: Command failed: fatal: Could not switch to 'C:\Windows\system32\config\systemprofile\AppData\Roaming\npm-cache\_git-remotes\': No such file or directory
[19:41:30][Step 3/5] npm ERR! 
[19:41:30][Step 3/5] npm ERR!     at ChildProcess.exithandler (child_process.js:637:15)
[19:41:30][Step 3/5] npm ERR!     at ChildProcess.EventEmitter.emit (events.js:98:17)
[19:41:30][Step 3/5] npm ERR!     at maybeClose (child_process.js:743:16)
[19:41:30][Step 3/5] npm ERR!     at Process.ChildProcess._handle.onexit (child_process.js:810:5)
[19:41:30][Step 3/5] npm ERR! If you need help, you may report this *entire* log,
[19:41:30][Step 3/5] npm ERR! including the npm and node versions, at:
[19:41:30][Step 3/5] npm ERR!     <http://github.com/isaacs/npm/issues
[19:41:30][Step 3/5] 
[19:41:30][Step 3/5] npm ERR! System Windows_NT 6.2.9200
[19:41:30][Step 3/5] npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
[19:41:30][Step 3/5] npm ERR! cwd C:\TeamCity\buildAgent\work\9bf9a10ecaad4b75\deploy\compress_html
[19:41:30][Step 3/5] npm ERR! node -v v0.10.25
[19:41:30][Step 3/5] npm ERR! npm -v 1.3.24
[19:41:30][Step 3/5] npm ERR! code 128
[19:41:30][Step 3/5] npm
[19:41:30][Step 3/5] Process exited with code 1
```

**Comment by KenanY** [comment]
@SFoster84 `npm@1.3.24` is very old, with support being terminated months ago. Could you first try [upgrading](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows)?

**Comment by SFoster84** [comment]
Thanks Kenan, I upgraded and then ran 'npm cache clean' and I'm seeing this error now:
[21:57:32][Step 3/5] npm WARN package.json HtmlCompress@0.1.0 No description
[21:57:32][Step 3/5] npm WARN package.json HtmlCompress@0.1.0 No repository field.
[21:57:32][Step 3/5] npm WARN package.json HtmlCompress@0.1.0 No README data
[21:57:32][Step 3/5] npm WARN package.json HtmlCompress@0.1.0 No license field.
[21:57:35][Step 3/5] npm WARN addRemoteGit git://github.com/isaacs/js-yaml.git resetting remote C:\Windows\system32\config\systemprofile\AppData\Roaming\npm-cache\_git-remotes\git-github-com-isaacs-js-yaml-git-dd3d7a8b because of error: fatal: failed to stat '.': No such file or directory
[21:57:35][Step 3/5] npm ERR! git clone --template=C:\Windows\system32\config\systemprofile\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/isaacs/js-yaml.git C:\Windows\system32\config\systemprofile\AppData\Roaming\npm-cache\_git-remotes\git-github-com-isaacs-js-yaml-git-dd3d7a8b: fatal: Could not switch to 'C:\Windows\system32\config\systemprofile\AppData\Roaming\npm-cache\_git-remotes\': No such file or directory
[21:57:35][Step 3/5] npm ERR! Windows_NT 6.2.9200
[21:57:35][Step 3/5] npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
[21:57:35][Step 3/5] npm ERR! node v0.10.25
[21:57:35][Step 3/5] npm ERR! npm  v2.10.0
[21:57:35][Step 3/5] npm ERR! code 128
[21:57:35][Step 3/5] 
[21:57:35][Step 3/5] npm ERR! Command failed: fatal: Could not switch to 'C:\Windows\system32\config\systemprofile\AppData\Roaming\npm-cache\_git-remotes\': No such file or directory
[21:57:35][Step 3/5] npm ERR! 
[21:57:35][Step 3/5] npm ERR! 
[21:57:35][Step 3/5] npm ERR! If you need help, you may report this error at:
[21:57:35][Step 3/5] npm ERR!     <https://github.com/npm/npm/issues>
[21:57:36][Step 3/5] Process exited with code 1

**Comment by stivyw** [comment]
I'm with this error!
https://github.com/npm/npm/issues/8285

**Comment by stivyw** [comment]
So, do you fixed your error?
If not, see my fixed issue.
https://github.com/npm/npm/issues/8285

**Comment by SFoster84** [comment]
Hi Stivyw, thanks for sharing your answer - I tried deleting C:\Windows\system32\config\systemprofile\AppData\Roaming\npm-cache_git-remotes and then re-running, I got the same error so I checked permissions and it seems ok. Not sure why I keep getting the same error.

**Comment by SFoster84** [comment]
How can I tell if the problem is with my config or with yaml?
The server does have this folder, but it's empty: C:\Windows\System32\config\systemprofile\AppData\Roaming\npm-cache\_git-remotes\git-github-com-isaacs-js-yaml-git-dd3d7a8b

**Comment by SFoster84** [comment]
When I run "git clone --template=C:\Windows\system32\config\systemprofile\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/isaacs/js-yaml.git"  it resolves and gives some feedback that it's getting objects.  Does that mean the yaml source is working properly?

**Comment by stivyw** [comment]
Hi @SFoster84 , I'm so sorry, I have not seen your messages. So, you solve your problem?

**Comment by kmanion** [comment]
Hi @SFoster84, 

We’re trying to clean up some issues. If this is still a problem, can you please reply and let us know? We’ll be happy to reopen if necessary.

-Kiera, npm technical support
