### ISSUE TITLE
Updated node through npm, now can't use npm install --save

### ISSUE THREAD

**Issue by tah20112** [npm/npm#8294]
I used npm to install node v0.12.3, then express package acted weird in node, and now npm won't install cookie-parser or morgan. I'm new to npm and node, so I don't know much more yet

Debug Log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--save',
1 verbose cli   'body-parser',
1 verbose cli   'cookie-parser',
1 verbose cli   'morgan' ]
2 info using npm@2.9.1
3 info using node@v0.12.3
4 verbose node symlink /usr/local/bin/node
5 verbose install initial load of /home/theale/Documents/+Olin/Freshman/Olin_JS/learnyounode/package.json
6 warn package.json learnyounode@1.0.0 No description
7 warn package.json learnyounode@1.0.0 No repository field.
8 warn package.json learnyounode@1.0.0 No README data
9 verbose installManyTop reading scoped package data from /home/theale/Documents/+Olin/Freshman/Olin_JS/learnyounode/node_modules/express/package.json
10 verbose installManyTop reading scoped package data from /home/theale/Documents/+Olin/Freshman/Olin_JS/learnyounode/node_modules/jade/package.json
11 verbose readDependencies loading dependencies from /home/theale/Documents/+Olin/Freshman/Olin_JS/learnyounode/package.json
12 silly cache add args [ 'body-parser', null ]
13 verbose cache add spec body-parser
14 silly cache add args [ 'cookie-parser', null ]
15 verbose cache add spec cookie-parser
16 silly cache add args [ 'morgan', null ]
17 verbose cache add spec morgan
18 silly cache add parsed spec { raw: 'body-parser',
18 silly cache add   scope: null,
18 silly cache add   name: 'body-parser',
18 silly cache add   rawSpec: '',
18 silly cache add   spec: '*',
18 silly cache add   type: 'range' }
19 silly addNamed body-parser@*
20 verbose addNamed "*" is a valid semver range for body-parser
21 silly addNameRange { name: 'body-parser', range: '*', hasData: false }
22 silly mapToRegistry name body-parser
23 silly mapToRegistry using default registry
24 silly mapToRegistry registry https://registry.npmjs.org/
25 silly mapToRegistry uri https://registry.npmjs.org/body-parser
26 verbose addNameRange registry:https://registry.npmjs.org/body-parser not in flight; fetching
27 silly cache add parsed spec { raw: 'cookie-parser',
27 silly cache add   scope: null,
27 silly cache add   name: 'cookie-parser',
27 silly cache add   rawSpec: '',
27 silly cache add   spec: '*',
27 silly cache add   type: 'range' }
28 silly addNamed cookie-parser@*
29 verbose addNamed "*" is a valid semver range for cookie-parser
30 silly addNameRange { name: 'cookie-parser', range: '*', hasData: false }
31 silly mapToRegistry name cookie-parser
32 silly mapToRegistry using default registry
33 silly mapToRegistry registry https://registry.npmjs.org/
34 silly mapToRegistry uri https://registry.npmjs.org/cookie-parser
35 verbose addNameRange registry:https://registry.npmjs.org/cookie-parser not in flight; fetching
36 silly cache add parsed spec { raw: 'morgan',
36 silly cache add   scope: null,
36 silly cache add   name: 'morgan',
36 silly cache add   rawSpec: '',
36 silly cache add   spec: '*',
36 silly cache add   type: 'range' }
37 silly addNamed morgan@*
38 verbose addNamed "*" is a valid semver range for morgan
39 silly addNameRange { name: 'morgan', range: '*', hasData: false }
40 silly mapToRegistry name morgan
41 silly mapToRegistry using default registry
42 silly mapToRegistry registry https://registry.npmjs.org/
43 silly mapToRegistry uri https://registry.npmjs.org/morgan
44 verbose addNameRange registry:https://registry.npmjs.org/morgan not in flight; fetching
45 verbose request uri https://registry.npmjs.org/cookie-parser
46 verbose request no auth needed
47 info attempt registry request try #1 at 12:41:32 AM
48 verbose request using bearer token for auth
49 verbose request id a8b6d2460b98edf8
50 verbose etag "CBZT5RU9MKCP8JNCW5PHKS8N2"
51 http request GET https://registry.npmjs.org/cookie-parser
52 verbose request uri https://registry.npmjs.org/morgan
53 verbose request no auth needed
54 info attempt registry request try #1 at 12:41:32 AM
55 verbose request using bearer token for auth
56 verbose etag "AFZGA0RMDLIIY9IF44OWSKIMP"
57 http request GET https://registry.npmjs.org/morgan
58 verbose request uri https://registry.npmjs.org/body-parser
59 verbose request no auth needed
60 info attempt registry request try #1 at 12:41:32 AM
61 verbose request using bearer token for auth
62 verbose etag "DEJO2OE5KEWH60QW33UZK5QEE"
63 http request GET https://registry.npmjs.org/body-parser
64 http 304 https://registry.npmjs.org/cookie-parser
65 silly get cb [ 304,
65 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
65 silly get     etag: '"CBZT5RU9MKCP8JNCW5PHKS8N2"',
65 silly get     'cache-control': 'max-age=60',
65 silly get     'accept-ranges': 'bytes',
65 silly get     date: 'Mon, 18 May 2015 04:41:19 GMT',
65 silly get     via: '1.1 varnish',
65 silly get     connection: 'keep-alive',
65 silly get     'x-served-by': 'cache-jfk1029-JFK',
65 silly get     'x-cache': 'MISS',
65 silly get     'x-cache-hits': '0',
65 silly get     'x-timer': 'S1431924079.403715,VS0,VE18' } ]
66 verbose etag https://registry.npmjs.org/cookie-parser from cache
67 verbose get saving cookie-parser to /home/theale/.npm/registry.npmjs.org/cookie-parser/.cache.json
68 silly addNameRange number 2 { name: 'cookie-parser', range: '*', hasData: true }
69 silly addNameRange versions [ 'cookie-parser',
69 silly addNameRange   [ '1.0.0',
69 silly addNameRange     '1.0.1',
69 silly addNameRange     '1.1.0',
69 silly addNameRange     '1.2.0',
69 silly addNameRange     '1.3.0',
69 silly addNameRange     '1.3.1',
69 silly addNameRange     '1.3.2',
69 silly addNameRange     '1.3.3',
69 silly addNameRange     '1.3.4' ] ]
70 silly addNamed cookie-parser@1.3.4
71 verbose addNamed "1.3.4" is a plain semver version for cookie-parser
72 silly cache afterAdd cookie-parser@1.3.4
73 verbose afterAdd /home/theale/.npm/cookie-parser/1.3.4/package/package.json not in flight; writing
74 verbose afterAdd /home/theale/.npm/cookie-parser/1.3.4/package/package.json written
75 http 304 https://registry.npmjs.org/morgan
76 silly get cb [ 304,
76 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
76 silly get     etag: '"AFZGA0RMDLIIY9IF44OWSKIMP"',
76 silly get     'cache-control': 'max-age=60',
76 silly get     'accept-ranges': 'bytes',
76 silly get     date: 'Mon, 18 May 2015 04:41:19 GMT',
76 silly get     via: '1.1 varnish',
76 silly get     connection: 'keep-alive',
76 silly get     'x-served-by': 'cache-jfk1022-JFK',
76 silly get     'x-cache': 'MISS',
76 silly get     'x-cache-hits': '0',
76 silly get     'x-timer': 'S1431924079.402629,VS0,VE77' } ]
77 verbose etag https://registry.npmjs.org/morgan from cache
78 verbose get saving morgan to /home/theale/.npm/registry.npmjs.org/morgan/.cache.json
79 silly addNameRange number 2 { name: 'morgan', range: '*', hasData: true }
80 silly addNameRange versions [ 'morgan',
80 silly addNameRange   [ '1.0.0',
80 silly addNameRange     '1.0.1',
80 silly addNameRange     '1.1.0',
80 silly addNameRange     '1.1.1',
80 silly addNameRange     '1.2.0',
80 silly addNameRange     '1.2.1',
80 silly addNameRange     '1.2.2',
80 silly addNameRange     '1.2.3',
80 silly addNameRange     '1.3.0',
80 silly addNameRange     '1.3.1',
80 silly addNameRange     '1.3.2',
80 silly addNameRange     '1.4.0',
80 silly addNameRange     '1.4.1',
80 silly addNameRange     '1.5.0',
80 silly addNameRange     '1.5.1',
80 silly addNameRange     '1.5.2',
80 silly addNameRange     '1.5.3' ] ]
81 silly addNamed morgan@1.5.3
82 verbose addNamed "1.5.3" is a plain semver version for morgan
83 http 304 https://registry.npmjs.org/body-parser
84 silly get cb [ 304,
84 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
84 silly get     etag: '"DEJO2OE5KEWH60QW33UZK5QEE"',
84 silly get     'cache-control': 'max-age=60',
84 silly get     'accept-ranges': 'bytes',
84 silly get     date: 'Mon, 18 May 2015 04:41:19 GMT',
84 silly get     via: '1.1 varnish',
84 silly get     connection: 'keep-alive',
84 silly get     'x-served-by': 'cache-jfk1034-JFK',
84 silly get     'x-cache': 'MISS',
84 silly get     'x-cache-hits': '0',
84 silly get     'x-timer': 'S1431924079.400747,VS0,VE84' } ]
85 verbose etag https://registry.npmjs.org/body-parser from cache
86 verbose get saving body-parser to /home/theale/.npm/registry.npmjs.org/body-parser/.cache.json
87 silly cache afterAdd morgan@1.5.3
88 verbose afterAdd /home/theale/.npm/morgan/1.5.3/package/package.json not in flight; writing
89 verbose afterAdd /home/theale/.npm/morgan/1.5.3/package/package.json written
90 silly addNameRange number 2 { name: 'body-parser', range: '*', hasData: true }
91 silly addNameRange versions [ 'body-parser',
91 silly addNameRange   [ '1.0.0',
91 silly addNameRange     '1.0.1',
91 silly addNameRange     '1.0.2',
91 silly addNameRange     '1.1.0',
91 silly addNameRange     '1.1.1',
91 silly addNameRange     '1.1.2',
91 silly addNameRange     '1.2.0',
91 silly addNameRange     '1.2.1',
91 silly addNameRange     '1.2.2',
91 silly addNameRange     '1.3.0',
91 silly addNameRange     '1.3.1',
91 silly addNameRange     '1.4.0',
91 silly addNameRange     '1.4.1',
91 silly addNameRange     '1.4.2',
91 silly addNameRange     '1.4.3',
91 silly addNameRange     '1.5.0',
91 silly addNameRange     '1.5.1',
91 silly addNameRange     '1.5.2',
91 silly addNameRange     '1.6.0',
91 silly addNameRange     '1.6.1',
91 silly addNameRange     '1.6.2',
91 silly addNameRange     '1.6.3',
91 silly addNameRange     '1.6.4',
91 silly addNameRange     '1.6.5',
91 silly addNameRange     '1.6.6',
91 silly addNameRange     '1.6.7',
91 silly addNameRange     '1.7.0',
91 silly addNameRange     '1.8.0',
91 silly addNameRange     '1.8.1',
91 silly addNameRange     '1.8.2',
91 silly addNameRange     '1.8.3',
91 silly addNameRange     '1.8.4',
91 silly addNameRange     '1.9.0',
91 silly addNameRange     '1.9.1',
91 silly addNameRange     '1.9.2',
91 silly addNameRange     '1.9.3',
91 silly addNameRange     '1.10.0',
91 silly addNameRange     '1.10.1',
91 silly addNameRange     '1.10.2',
91 silly addNameRange     '1.11.0',
91 silly addNameRange     '1.12.0',
91 silly addNameRange     '1.12.1',
91 silly addNameRange     '1.12.2',
91 silly addNameRange     '1.12.3',
91 silly addNameRange     '1.12.4' ] ]
92 silly addNamed body-parser@1.12.4
93 verbose addNamed "1.12.4" is a plain semver version for body-parser
94 silly cache afterAdd body-parser@1.12.4
95 verbose afterAdd /home/theale/.npm/body-parser/1.12.4/package/package.json not in flight; writing
96 verbose afterAdd /home/theale/.npm/body-parser/1.12.4/package/package.json written
97 silly install resolved [ { name: 'cookie-parser',
97 silly install resolved     description: 'cookie parsing with signatures',
97 silly install resolved     version: '1.3.4',
97 silly install resolved     author:
97 silly install resolved      { name: 'TJ Holowaychuk',
97 silly install resolved        email: 'tj@vision-media.ca',
97 silly install resolved        url: 'http://tjholowaychuk.com' },
97 silly install resolved     licenses: 'MIT',
97 silly install resolved     repository:
97 silly install resolved      { type: 'git',
97 silly install resolved        url: 'git+https://github.com/expressjs/cookie-parser.git' },
97 silly install resolved     keywords: [ 'cookie', 'middleware' ],
97 silly install resolved     dependencies: { cookie: '0.1.2', 'cookie-signature': '1.0.6' },
97 silly install resolved     devDependencies: { istanbul: '0.3.5', mocha: '~2.1.0', supertest: '0.15.0' },
97 silly install resolved     files: [ 'lib/', 'LICENSE', 'HISTORY.md', 'index.js' ],
97 silly install resolved     engines: { node: '>= 0.8.0' },
97 silly install resolved     scripts:
97 silly install resolved      { test: 'mocha --reporter spec --bail --check-leaks test/',
97 silly install resolved        'test-cov': 'istanbul cover node_modules/mocha/bin/_mocha -- --reporter dot --check-leaks test/',
97 silly install resolved        'test-travis': 'istanbul cover node_modules/mocha/bin/_mocha --report lcovonly -- --reporter spec --check-leaks test/' },
97 silly install resolved     gitHead: '94764a584c70f26049b14c6ad845c8b0ed0e478b',
97 silly install resolved     bugs: { url: 'https://github.com/expressjs/cookie-parser/issues' },
97 silly install resolved     homepage: 'https://github.com/expressjs/cookie-parser',
97 silly install resolved     _id: 'cookie-parser@1.3.4',
97 silly install resolved     _shasum: '193035a5be97117a21709b3aa737f6132717bda6',
97 silly install resolved     _from: 'cookie-parser@*',
97 silly install resolved     _npmVersion: '1.4.28',
97 silly install resolved     _npmUser: { name: 'dougwilson', email: 'doug@somethingdoug.com' },
97 silly install resolved     maintainers: [ [Object], [Object] ],
97 silly install resolved     dist:
97 silly install resolved      { shasum: '193035a5be97117a21709b3aa737f6132717bda6',
97 silly install resolved        tarball: 'http://registry.npmjs.org/cookie-parser/-/cookie-parser-1.3.4.tgz' },
97 silly install resolved     directories: {},
97 silly install resolved     _resolved: 'https://registry.npmjs.org/cookie-parser/-/cookie-parser-1.3.4.tgz',
97 silly install resolved     readme: 'ERROR: No README data found!' },
97 silly install resolved   { name: 'morgan',
97 silly install resolved     description: 'HTTP request logger middleware for node.js',
97 silly install resolved     version: '1.5.3',
97 silly install resolved     contributors: [ [Object], [Object] ],
97 silly install resolved     license: 'MIT',
97 silly install resolved     repository:
97 silly install resolved      { type: 'git',
97 silly install resolved        url: 'git+https://github.com/expressjs/morgan.git' },
97 silly install resolved     dependencies:
97 silly install resolved      { 'basic-auth': '~1.0.1',
97 silly install resolved        debug: '~2.2.0',
97 silly install resolved        depd: '~1.0.1',
97 silly install resolved        'on-finished': '~2.2.1' },
97 silly install resolved     devDependencies: { istanbul: '0.3.9', mocha: '~2.2.4', supertest: '~0.15.0' },
97 silly install resolved     files: [ 'LICENSE', 'HISTORY.md', 'README.md', 'index.js' ],
97 silly install resolved     engines: { node: '>= 0.8.0' },
97 silly install resolved     scripts:
97 silly install resolved      { test: 'mocha --check-leaks --reporter spec --bail',
97 silly install resolved        'test-cov': 'istanbul cover node_modules/mocha/bin/_mocha -- --check-leaks --reporter dot',
97 silly install resolved        'test-travis': 'istanbul cover node_modules/mocha/bin/_mocha --report lcovonly -- --check-leaks --reporter spec' },
97 silly install resolved     gitHead: '7d5a190e6e22c4871c15aff2143bf76b808052cf',
97 silly install resolved     bugs: { url: 'https://github.com/expressjs/morgan/issues' },
97 silly install resolved     homepage: 'https://github.com/expressjs/morgan',
97 silly install resolved     _id: 'morgan@1.5.3',
97 silly install resolved     _shasum: '8adb4e72f9e5c5436e5d93f42910835f79da9fdf',
97 silly install resolved     _from: 'morgan@*',
97 silly install resolved     _npmVersion: '1.4.28',
97 silly install resolved     _npmUser: { name: 'dougwilson', email: 'doug@somethingdoug.com' },
97 silly install resolved     maintainers: [ [Object], [Object], [Object], [Object], [Object], [Object] ],
97 silly install resolved     dist:
97 silly install resolved      { shasum: '8adb4e72f9e5c5436e5d93f42910835f79da9fdf',
97 silly install resolved        tarball: 'http://registry.npmjs.org/morgan/-/morgan-1.5.3.tgz' },
97 silly install resolved     directories: {},
97 silly install resolved     _resolved: 'https://registry.npmjs.org/morgan/-/morgan-1.5.3.tgz',
97 silly install resolved     readme: 'ERROR: No README data found!' },
97 silly install resolved   { name: 'body-parser',
97 silly install resolved     description: 'Node.js body parsing middleware',
97 silly install resolved     version: '1.12.4',
97 silly install resolved     contributors: [ [Object], [Object] ],
97 silly install resolved     license: 'MIT',
97 silly install resolved     repository:
97 silly install resolved      { type: 'git',
97 silly install resolved        url: 'git+https://github.com/expressjs/body-parser.git' },
97 silly install resolved     dependencies:
97 silly install resolved      { bytes: '1.0.0',
97 silly install resolved        'content-type': '~1.0.1',
97 silly install resolved        debug: '~2.2.0',
97 silly install resolved        depd: '~1.0.1',
97 silly install resolved        'iconv-lite': '0.4.8',
97 silly install resolved        'on-finished': '~2.2.1',
97 silly install resolved        qs: '2.4.2',
97 silly install resolved        'raw-body': '~2.0.1',
97 silly install resolved        'type-is': '~1.6.2' },
97 silly install resolved     devDependencies:
97 silly install resolved      { istanbul: '0.3.9',
97 silly install resolved        methods: '~1.1.1',
97 silly install resolved        mocha: '~2.2.4',
97 silly install resolved        supertest: '~0.15.0' },
97 silly install resolved     files: [ 'lib/', 'LICENSE', 'HISTORY.md', 'index.js' ],
97 silly install resolved     engines: { node: '>= 0.8' },
97 silly install resolved     scripts:
97 silly install resolved      { test: 'mocha --require test/support/env --reporter spec --check-leaks --bail test/',
97 silly install resolved        'test-cov': 'istanbul cover node_modules/mocha/bin/_mocha -- --require test/support/env --reporter dot --check-leaks test/',
97 silly install resolved        'test-travis': 'istanbul cover node_modules/mocha/bin/_mocha --report lcovonly -- --require test/support/env --reporter spec --check-leaks test/' },
97 silly install resolved     gitHead: 'faba6ae19686d82133e188707b9b77649f45d3b0',
97 silly install resolved     bugs: { url: 'https://github.com/expressjs/body-parser/issues' },
97 silly install resolved     homepage: 'https://github.com/expressjs/body-parser',
97 silly install resolved     _id: 'body-parser@1.12.4',
97 silly install resolved     _shasum: '090700c4ba28862a8520ef378395fdee5f61c229',
97 silly install resolved     _from: 'body-parser@*',
97 silly install resolved     _npmVersion: '1.4.28',
97 silly install resolved     _npmUser: { name: 'dougwilson', email: 'doug@somethingdoug.com' },
97 silly install resolved     maintainers: [ [Object], [Object], [Object], [Object], [Object], [Object] ],
97 silly install resolved     dist:
97 silly install resolved      { shasum: '090700c4ba28862a8520ef378395fdee5f61c229',
97 silly install resolved        tarball: 'http://registry.npmjs.org/body-parser/-/body-parser-1.12.4.tgz' },
97 silly install resolved     directories: {},
97 silly install resolved     _resolved: 'https://registry.npmjs.org/body-parser/-/body-parser-1.12.4.tgz',
97 silly install resolved     readme: 'ERROR: No README data found!' } ]
98 info install cookie-parser@1.3.4 into /home/theale/Documents/+Olin/Freshman/Olin_JS/learnyounode
99 info install morgan@1.5.3 into /home/theale/Documents/+Olin/Freshman/Olin_JS/learnyounode
100 info install body-parser@1.12.4 into /home/theale/Documents/+Olin/Freshman/Olin_JS/learnyounode
101 info installOne cookie-parser@1.3.4
102 verbose installOne of cookie-parser to /home/theale/Documents/+Olin/Freshman/Olin_JS/learnyounode not in flight; installing
103 info installOne morgan@1.5.3
104 verbose installOne of morgan to /home/theale/Documents/+Olin/Freshman/Olin_JS/learnyounode not in flight; installing
105 info installOne body-parser@1.12.4
106 verbose installOne of body-parser to /home/theale/Documents/+Olin/Freshman/Olin_JS/learnyounode not in flight; installing
107 warn locking Error: EACCES, open '/home/theale/.npm/_locks/cookie-parser-b8c96874f19b60e6.lock'
107 warn locking     at Error (native)
107 warn locking  /home/theale/.npm/_locks/cookie-parser-b8c96874f19b60e6.lock failed { [Error: EACCES, open '/home/theale/.npm/_locks/cookie-parser-b8c96874f19b60e6.lock']
107 warn locking   errno: -13,
107 warn locking   code: 'EACCES',
107 warn locking   path: '/home/theale/.npm/_locks/cookie-parser-b8c96874f19b60e6.lock' }
108 verbose stack Error: Attempt to unlock /home/theale/Documents/+Olin/Freshman/Olin_JS/learnyounode/node_modules/cookie-parser, which hasn't been locked
108 verbose stack     at unlock (/usr/local/lib/node_modules/npm/lib/utils/locker.js:66:11)
108 verbose stack     at cb (/usr/local/lib/node_modules/npm/lib/install.js:1015:5)
108 verbose stack     at /usr/local/lib/node_modules/npm/lib/install.js:1019:20
108 verbose stack     at /usr/local/lib/node_modules/npm/lib/utils/locker.js:40:9
108 verbose stack     at cb (/usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:149:38)
108 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:177:38
108 verbose stack     at FSReqWrap.oncomplete (fs.js:95:15)
109 verbose cwd /home/theale/Documents/+Olin/Freshman/Olin_JS/learnyounode
110 error Linux 3.13.0-52-generic
111 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "body-parser" "cookie-parser" "morgan"
112 error node v0.12.3
113 error npm  v2.9.1
114 error Attempt to unlock /home/theale/Documents/+Olin/Freshman/Olin_JS/learnyounode/node_modules/cookie-parser, which hasn't been locked
115 error If you need help, you may report this error at:
115 error     <https://github.com/npm/npm/issues>
116 verbose exit [ 1, true ]
```

**Comment by smikes** [comment]
It looks like your `npm` cache directory might have some files with incorrect permissions in them.  Can you try this command, which should fix the ownership issues:

```
$ sudo chown -R $(whoami) ~/.npm
```

PS are you at Olin?

**Comment by tah20112** [comment]
Hey Mike,

Yeah, I'm going into my second year at Olin. How do you know the school?
Most people I speak to don't. As far as my npm problem goes, I think I made
the most rookie of Linux mistakes. I think it was having permission
problems because I wasn't running as root. I ran the install --save
commands with sudo yesterday, and express started working.

**Comment by smikes** [comment]
I'm Harvey Mudd '97, so I knew Mike Moody as a math prof at Mudd; when he left to be part of the founding faculty at Olin, I started taking an interest in Olin. 

Sounds like you have it sorted out now -- feel free to open more issues here or ask on the irc channel - #npm at freenode (eg - https://www.irccloud.com/#!/ircs://irc.freenode.net:6697/%23npm )

**Comment by ehsalazar** [comment]
Good to hear. I'll close this for now as we’re trying to clean up some old issues. We’ll be happy to reopen if necessary.
