### ISSUE TITLE
serialPort install errors on raspberry pi

### ISSUE THREAD

**Issue by sensorware** [npm/npm#8295]
trying to install serialport on a raspberry pi 2.  this is the offending action: Error: No compatible version found: debug@'^2.1.1' 

any help would be appreciated. 

```
pi@mite1 ~ $ sudo npm install serialport
npm http GET https://registry.npmjs.org/serialport
npm http 304 https://registry.npmjs.org/serialport
npm http GET https://registry.npmjs.org/async/0.9.0
npm http GET https://registry.npmjs.org/bindings/1.2.1
npm http GET https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/nan
npm http GET https://registry.npmjs.org/optimist
npm http GET https://registry.npmjs.org/sf/0.1.7
npm http 304 https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/debug
npm http 304 https://registry.npmjs.org/optimist
npm http 304 https://registry.npmjs.org/async/0.9.0
npm http 304 https://registry.npmjs.org/sf/0.1.7
npm http 304 https://registry.npmjs.org/bindings/1.2.1
npm ERR! Error: No compatible version found: debug@'^2.1.1'
npm ERR! Valid install targets:
npm ERR! ["0.0.1","0.1.0","0.2.0","0.3.0","0.4.0","0.4.1","0.5.0","0.6.0","0.7.0","0.7.1","0.7.2","0.7.3","0.7.4","0.8.0","0.8.1","1.0.0","1.0.1","1.0.2","1.0.3","1.0.4","2.0.0","2.1.0","2.1.1","2.1.2","2.1.3","2.2.0"]
npm ERR!     at installTargetsError (/opt/node/lib/node_modules/npm/lib/cache.js:709:10)
npm ERR!     at /opt/node/lib/node_modules/npm/lib/cache.js:631:10
npm ERR!     at saved (/opt/node/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:94:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.18.13+
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "serialport"
npm ERR! cwd /home/pi
npm ERR! node -v v0.11.3
npm ERR! npm -v 1.2.25
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/npm-debug.log
npm ERR! not ok code 0
```

**Comment by KenanY** [comment]
@sensorware `npm@1.2.25` is very ancient. As a consequence, your version of `npm` does not support the `^` semver operator you see here:

```
npm ERR! Error: No compatible version found: debug@'^2.1.1'
```

The solution is to simply [upgrade](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-nix-osx-linux-etc).

I should also point out that Node.js v0.11 development has ended now that v0.12 has been released.

**Comment by othiym23** [comment]
You might also want to look at io.js, which has considerably improved support for ARM and Raspberry Pi. 

Closing as resolved.
