### ISSUE TITLE
Allow overwrite packages on forcing npm publish?

### ISSUE THREAD

**Issue by nmrony** [npm/npm#8305]
I just change a typo in `README` and I must bump my version to publish it on npm site. forcing is not working for me. still getting 403 error like below
```
npm WARN using --force I sure hope you know what you are doing.
npm ERR! publish Failed PUT 403
npm ERR! Error: "You cannot publish over the previously published version 1.0.1." : hlsdownloader
npm ERR!     at RegClient.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:308:14)
npm ERR!     at Request._callback (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:246:65)
npm ERR!     at Request.self.callback (/usr/lib/node_modules/npm/node_modules/request/request.js:236:22)
npm ERR!     at Request.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/lib/node_modules/npm/node_modules/request/request.js:1142:14)
npm ERR!     at Request.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/lib/node_modules/npm/node_modules/request/request.js:1096:12)
npm ERR!     at IncomingMessage.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:944:16
npm ERR!     at process._tickCallback (node.js:448:13)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.13.0-52-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "publish" "-f"
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.28
npm ERR! not ok code 0
```
also found this [here](https://docs.npmjs.com/cli/publish)
```
Once a package is published with a given name and version, that specific name and version combination can never be used again, even if it is removed with npm-unpublish
```
So I need to bump a version even I just update the README. Is it not insane? Or How to overwrite my published version?

**Comment by KenanY** [comment]
@nmrony You cannot overwrite previously-published packages anymore (since February 2014, if I recall correctly).

**Comment by othiym23** [comment]
As @KenanY said, packages can't be changed once they're published. Closing as resolved.

**Comment by nmrony** [comment]
Is there any possibility to rollback this so that people can overwrite their desired version already published on `npm`?

**Comment by KenanY** [comment]
@nmrony Maybe, but I highly doubt that will ever happen, especially for the use-case of fixing typos.

**Comment by jkomyno** [comment]
@othiym23 what about @c0b proposal? Or what about adding the possibility to overwrite a small range of description files, like README.*?
