### ISSUE TITLE
Issue with npm install -g javascripting

### ISSUE THREAD

**Issue by Yedoutie** [npm/npm#8318]
Hi, 
when I try 'npm install -g javascripting', I am getting the errors reported below. 
Thank you in advance for your help.

```
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config -
-get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:751:12)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:110:17)
npm WARN addRemoteGit     at maybeClose (child_process.js:1015:16)
npm WARN addRemoteGit     at Socket.<anonymous> (child_process.js:1183:11)
npm WARN addRemoteGit     at Socket.emit (events.js:107:17)
npm WARN addRemoteGit     at Pipe.close (net.js:485:12)
npm WARN addRemoteGit  git://github.com/martinheidegger/workshopper.git#adventur
e resetting remote C:\Users\kombate\AppData\Roaming\npm-cache\_git-remotes\git-g
ithub-com-martinheidegger-workshopper-git-52e025bb because of error: { [Error: C
ommand failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit ]
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.ori
gin.url' }
npm ERR! git clone --template=C:\Users\kombate\AppData\Roaming\npm-cache\_git-re
motes\_templates --mirror git://github.com/martinheidegger/workshopper.git C:\Us
ers\kombate\AppData\Roaming\npm-cache\_git-remotes\git-github-com-martinheidegge
r-workshopper-git-52e025bb: Cloning into bare repository 'C:\Users\kombate\AppDa
ta\Roaming\npm-cache\_git-remotes\git-github-com-martinheidegger-workshopper-git
-52e025bb'...
npm ERR! git clone --template=C:\Users\kombate\AppData\Roaming\npm-cache\_git-re
motes\_templates --mirror git://github.com/martinheidegger/workshopper.git C:\Us
ers\kombate\AppData\Roaming\npm-cache\_git-remotes\git-github-com-martinheidegge
r-workshopper-git-52e025bb: fatal: unable to access 'http://github.com/martinhei
degger/workshopper.git/': Failed to connect to github.com port 80: Timed out
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (
x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "javascripting"

npm ERR! node v0.12.2
npm ERR! npm  v2.10.0
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\ko
mbate\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.co
m/martinheidegger/workshopper.git C:\Users\kombate\AppData\Roaming\npm-cache\_gi
t-remotes\git-github-com-martinheidegger-workshopper-git-52e025bb
npm ERR! Cloning into bare repository 'C:\Users\kombate\AppData\Roaming\npm-cach
e\_git-remotes\git-github-com-martinheidegger-workshopper-git-52e025bb'...
npm ERR! fatal: unable to access 'http://github.com/martinheidegger/workshopper.
git/': Failed to connect to github.com port 80: Timed out
```

**Comment by KenanY** [comment]
```
Failed to connect to github.com port 80: Timed out
```

@Yedoutie Looks like an internet connection issue. Are you behind a proxy or firewall by any chance?

**Comment by Yedoutie** [comment]
Unfortunately yes, I am indeed behind an enterprise proxy. However I have set the proxy server in the LAN settings. Is there anything else I should configure?

**Comment by KenanY** [comment]
@Yedoutie Yes, you must configure `npm` to use the proxy.

  - [`proxy`](https://docs.npmjs.com/misc/config#proxy)
  - [`https-proxy`](https://docs.npmjs.com/misc/config#https-proxy)
  - [`cafile`](https://docs.npmjs.com/misc/config#cafile)

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
