### ISSUE TITLE
Can't download Cordova to Windows 8.1

### ISSUE THREAD

**Issue by rickacc** [npm/npm#8321]
I am not behind a proxy, and I've tried downloading after shutting down my firewall.  Get the same error.  I have successfully downloaded Cordova to a Linux machine on the same network, but would really like to get Cordova running in Windows (8.1) so I can attempt to use PhoneGap.  Here is my error log:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'Cordova' ]
2 info using npm@2.9.1
3 info using node@v0.12.3
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 verbose install initial load of C:\Users\Rick\AppData\Roaming\npm\package.json
6 verbose readDependencies loading dependencies from C:\Users\Rick\AppData\Roaming\npm\package.json
7 silly cache add args [ 'Cordova', null ]
8 verbose cache add spec Cordova
9 silly cache add parsed spec { raw: 'Cordova',
9 silly cache add   scope: null,
9 silly cache add   name: 'Cordova',
9 silly cache add   rawSpec: '',
9 silly cache add   spec: '*',
9 silly cache add   type: 'range' }
10 silly addNamed Cordova@*
11 verbose addNamed "*" is a valid semver range for Cordova
12 silly addNameRange { name: 'Cordova', range: '*', hasData: false }
13 silly mapToRegistry name Cordova
14 silly mapToRegistry using default registry
15 silly mapToRegistry registry https://registry.npmjs.org/
16 silly mapToRegistry uri https://registry.npmjs.org/Cordova
17 verbose addNameRange registry:https://registry.npmjs.org/Cordova not in flight; fetching
18 verbose request uri https://registry.npmjs.org/Cordova
19 verbose request no auth needed
20 info attempt registry request try #1 at 5:11:49 PM
21 verbose request id c907d428bb744a4c
22 http request GET https://registry.npmjs.org/Cordova
23 info retry will retry, error on last attempt: Error: connect EACCES
24 info attempt registry request try #2 at 5:11:59 PM
25 http request GET https://registry.npmjs.org/Cordova
26 info retry will retry, error on last attempt: Error: connect EACCES
27 info attempt registry request try #3 at 5:12:59 PM
28 http request GET https://registry.npmjs.org/Cordova
29 verbose stack Error: connect EACCES
29 verbose stack     at exports._errnoException (util.js:746:11)
29 verbose stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)
30 verbose cwd c:\Users\Rick\Development\Cordova
31 error Windows_NT 6.3.9600
32 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "Cordova"
33 error node v0.12.3
34 error npm  v2.9.1
35 error code EACCES
36 error errno EACCES
37 error syscall connect
38 error Error: connect EACCES
38 error     at exports._errnoException (util.js:746:11)
38 error     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)
38 error  { [Error: connect EACCES] code: 'EACCES', errno: 'EACCES', syscall: 'connect' }
39 error Please try running this command again as root/Administrator.
40 verbose exit [ 1, true ]

**Comment by rickacc** [comment]
PS....I have also tried downloading as Administrator with no success.  The install code I used was:

node-v0.12.3-x64.xmsi 
Git-1.9.5-preview20150319.exe

The command attempted: npm install -g cordova

**Comment by rickacc** [comment]
Turned out Norton 360 was controlling the Firewall behind the scenes.  Shutdown the firewall using Norton, and this permitted the load.
