### ISSUE TITLE
EPERM error when using -g on user-owned binaries

### ISSUE THREAD

**Issue by dmvianna** [npm/npm#8360]
I have compiled and installed node into an user-owned directory. Now, despite having properly set environment variables and compiled the source with a prefix argument, every time I try to do any operation with **-g** I get 

    Error: EPERM, Operation not permitted
    at /mypath/local/stow/node/lib/node_modules/npm/node_modules/uid-number/uid-number.js:49:16
    at ChildProcess.exithandler (child_process.js:742:7)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:485:12)

To reproduce, just run

    npm config edit --global

after installing node as user.

Naturally, I was expecting that, being the user and owner of all the binaries, I would be able to set up my own environment and run global operations without impediments.

The npm version I'm using is the bundled 2.10.1 that comes with node 0.12.4.

**Comment by dmvianna** [comment]
Deleting the ~/.npmrc file solved the issue.
