### ISSUE TITLE
npm scripts behave differntly on windows 8.1

### ISSUE THREAD

**Issue by ghost** [npm/npm#8366]
Hi npm scripts used in this project behave differnt on windows with no reason:
https://github.com/ericelliott/isomorphic-express-boilerplate/issues/9

Here's  my npm-debug.log:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'test' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 verbose run-script [ 'pretest', 'test', 'posttest' ]
6 info pretest isomorphic-express-boilerplate@1.2.3
7 info test isomorphic-express-boilerplate@1.2.3
8 verbose unsafe-perm in lifecycle true
9 info isomorphic-express-boilerplate@1.2.3 Failed to exec test script
10 verbose stack Error: isomorphic-express-boilerplate@1.2.3 test: `node app/test/unit/index.js | tap-bail`
10 verbose stack Exit status 1
10 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
10 verbose stack     at EventEmitter.emit (events.js:110:17)
10 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:14:12)
10 verbose stack     at ChildProcess.emit (events.js:110:17)
10 verbose stack     at maybeClose (child_process.js:1008:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
11 verbose pkgid isomorphic-express-boilerplate@1.2.3
12 verbose cwd C:\Users\Norbert\Documents\GitHub\new\isomorphic-express-boilerplate
13 error Windows_NT 6.3.9600
14 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "test"
15 error node v0.12.0
16 error npm  v2.5.1
17 error code ELIFECYCLE
18 error isomorphic-express-boilerplate@1.2.3 test: `node app/test/unit/index.js | tap-bail`
18 error Exit status 1
19 error Failed at the isomorphic-express-boilerplate@1.2.3 test script 'node app/test/unit/index.js | tap-bail'.
19 error This is most likely a problem with the isomorphic-express-boilerplate package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     node app/test/unit/index.js | tap-bail
19 error You can get their info via:
19 error     npm owner ls isomorphic-express-boilerplate
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]
```

It seems to be an npm issue..any thoughts or tips would be helpful

**Comment by chazzlabs** [comment]
I'm seeing exactly the same output that @hville mentioned in the thread you linked.  I have two scripts defined in package.json:

```
"lint": "eslint scripts/**",
"test": "eslint scripts/**"
```

Running 'npm test' shows the output of my eslint followed by "npm ERR! Test failed.  See above for more details." when eslint fails.

Running 'npm run lint' or even 'npm run test' shows the output of my eslint followed by an "npm ERR!" block containing the "code ELIFECYCLE" line.

I'm also on Windows 8.1 with Node v4.0.0 and npm v2.14.2.
