### ISSUE TITLE
404 Error publishing http-parser-js

### ISSUE THREAD

**Issue by Jimbly** [npm/npm#8367]
I went to publish a module, as I often do, and I'm getting a 404 error.  I am able to publish my other modules fine from the same systems, but this one is getting a 404.  Only difference I can think of is that I am not the creator of this module, but at some point in the past I was given ownership/publish permission.

The module does exist ( https://www.npmjs.com/package/http-parser-js ).  Am I doing something wrong, or is something wrong with the registry?

```
npm ERR! publish Failed PUT 404
npm ERR! Linux 3.2.0-79-generic
npm ERR! argv "node" "/usr/local/bin/npm" "publish"
npm ERR! node v0.10.36
npm ERR! npm  v2.10.1
npm ERR! code E404

npm ERR! 404 Not found : http-parser-js
npm ERR! 404
npm ERR! 404 'http-parser-js' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

npm-debug.log

``````
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'publish' ]
2 info using npm@2.10.1
3 info using node@v0.10.36
4 verbose publish [ '.' ]
5 silly cache add args [ '.', null ]
6 verbose cache add spec .
7 silly cache add parsed spec { raw: '.',
7 silly cache add   scope: null,
7 silly cache add   name: null,
7 silly cache add   rawSpec: '.',
7 silly cache add   spec: '/home/jimb/http-parser-js',
7 silly cache add   type: 'directory' }
8 verbose addLocalDirectory /home/jimb/.npm/http-parser-js/0.3.0/package.tgz not in flight; packing
9 verbose tar pack [ '/home/jimb/.npm/http-parser-js/0.3.0/package.tgz',
9 verbose tar pack   '/home/jimb/http-parser-js' ]
10 verbose tarball /home/jimb/.npm/http-parser-js/0.3.0/package.tgz
11 verbose folder /home/jimb/http-parser-js
12 info prepublish http-parser-js@0.3.0
13 verbose addLocalTarball adding from inside cache /home/jimb/.npm/http-parser-js/0.3.0/package.tgz
14 silly cache afterAdd http-parser-js@0.3.0
15 verbose afterAdd /home/jimb/.npm/http-parser-js/0.3.0/package/package.json not in flight; writing
16 verbose afterAdd /home/jimb/.npm/http-parser-js/0.3.0/package/package.json written
17 silly publish { name: 'http-parser-js',
17 silly publish   version: '0.3.0',
17 silly publish   description: 'A pure JS HTTP parser for node.',
17 silly publish   main: 'http-parser.js',
17 silly publish   scripts: { test: 'python tests/test.py && node tests/iojs/test-http-parser-durability.js' },
17 silly publish   repository:
17 silly publish    { type: 'git',
17 silly publish      url: 'git://github.com/creationix/http-parser-js.git' },
17 silly publish   keywords: [ 'http' ],
17 silly publish   author: { name: 'Tim Caswell', url: 'https://github.com/creationix' },
17 silly publish   contributors:
17 silly publish    [ { name: 'Jimb Esser', url: 'https://github.com/Jimbly' },
17 silly publish      { name: 'Lawrence Rowe', url: 'https://github.com/lrowe' },
17 silly publish      { name: 'Jan Schär', url: 'https://github.com/jscissr' } ],
17 silly publish   license: 'MIT',
17 silly publish   readme: '# HTTP Parser\n\nThis library parses HTTP protocol for requests and responses.  It was created to replace `http_parser.c` since calling C++ function from JS is really slow in V8.\n\nThis was further modified by Jimbly to be useable in parsing responses, specifically tested with the "request" module, and addresses issues such as corrupt HTTP headers, which would otherwise cause Node\'s parser to throw a fatal error (HPE_INVALID_HEADER_TOKEN).\n\nJan Schär (jscissr) made some bigger changes and added tests. This fixed some bugs and added many missing features.\n\nThis is packaged as a standalone npm module.  To use in node, monkeypatch HTTPParser.\n\n```js\n// Monkey patch before you require http for the first time.\nprocess.binding(\'http_parser\').HTTPParser = require(\'http-parser-js\').HTTPParser;\n\nvar http = require(\'http\');\n// ...\n```\n\n## Testing\n\nSimply do `npm test`. The tests are copied from node and mscedex/io.js, with some modifcations.\n\n## Status\n\nThis should now be usable in any node application, it now supports (nearly) everything `http_parser.c` does while still being tolerant with corrupted headers.\n\n## License\n\nMIT. See LICENSE.md\n',
17 silly publish   readmeFilename: 'README.md',
17 silly publish   gitHead: '87f6949402279deb84313baa08d0268fcaf25ff9',
17 silly publish   bugs: { url: 'https://github.com/creationix/http-parser-js/issues' },
17 silly publish   homepage: 'https://github.com/creationix/http-parser-js#readme',
17 silly publish   _id: 'http-parser-js@0.3.0',
17 silly publish   _shasum: '095afccb4648c5243ecfebce2cfc4b19bf399742',
17 silly publish   _from: '.' }
18 verbose getPublishConfig undefined
19 silly mapToRegistry name http-parser-js
20 silly mapToRegistry using default registry
21 silly mapToRegistry registry https://registry.npmjs.org/
22 silly mapToRegistry uri https://registry.npmjs.org/http-parser-js
23 verbose publish registryBase https://registry.npmjs.org/
24 silly publish uploading /home/jimb/.npm/http-parser-js/0.3.0/package.tgz
25 verbose request uri https://registry.npmjs.org/http-parser-js
26 verbose request sending authorization for write operation
27 info attempt registry request try #1 at 15:41:25
28 verbose request id 128b3e936a1f4064
29 http request PUT https://registry.npmjs.org/http-parser-js
30 http 404 https://registry.npmjs.org/http-parser-js
31 verbose headers { 'content-type': 'application/json',
31 verbose headers   'cache-control': 'max-age=0',
31 verbose headers   'content-length': '21',
31 verbose headers   'accept-ranges': 'bytes',
31 verbose headers   date: 'Tue, 26 May 2015 22:41:25 GMT',
31 verbose headers   via: '1.1 varnish',
31 verbose headers   connection: 'keep-alive',
31 verbose headers   'x-served-by': 'cache-sjc3121-SJC',
31 verbose headers   'x-cache': 'MISS',
31 verbose headers   'x-cache-hits': '0',
31 verbose headers   'x-timer': 'S1432680085.203505,VS0,VE222' }
32 verbose request invalidating /home/jimb/.npm/registry.npmjs.org/http-parser-js on PUT
33 error publish Failed PUT 404
34 verbose stack Error: Not found : http-parser-js
34 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:247:14)
34 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:170:14)
34 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:368:22)
34 verbose stack     at Request.emit (events.js:98:17)
34 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1219:14)
34 verbose stack     at Request.emit (events.js:117:20)
34 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1167:12)
34 verbose stack     at IncomingMessage.emit (events.js:117:20)
34 verbose stack     at _stream_readable.js:944:16
34 verbose stack     at process._tickCallback (node.js:442:13)
35 verbose statusCode 404
36 verbose pkgid http-parser-js
37 verbose cwd /home/jimb/http-parser-js
38 error Linux 3.2.0-79-generic
39 error argv "node" "/usr/local/bin/npm" "publish"
40 error node v0.10.36
41 error npm  v2.10.1
42 error code E404
43 error 404 Not found : http-parser-js
43 error 404
43 error 404 'http-parser-js' is not in the npm registry.
43 error 404 You should bug the author to publish it (or use the name yourself!)
43 error 404
43 error 404 Note that you can also install from a
43 error 404 tarball, folder, http url, or git url.
44 verbose exit [ 1, true ]
``````

**Comment by Jimbly** [comment]
As an update, it appears that the original author of the module is able to publish it, but I was no longer able to.  It looks like somehow my permissions were removed, unbeknownst to me or the original author, I was not listed on https://www.npmjs.com/package/http-parser-js/access.  After re-adding me there, everything seems to be good, so, really, the issue is that NPM is saying "404 not found" when it should be saying "access denied" (ideally with a link to the page where access can be granted, as it took me a while to find that).

The original author said It's possible he originally added me as "jimbly", and my NPM username is "Jimbly", and something changed regarding case-sensitivity or something like that.
