### ISSUE TITLE
Installing MongoDB - TypeError: Invalid Version: 3.5.0a4 in SemVer

### ISSUE THREAD

**Issue by ant-fx** [npm/npm#8386]
With a fresh node install going to a clean directory and running

    npm install mongodb

I get the following:

```
gyp ERR! stack TypeError: Invalid Version: 3.5.0a4
gyp ERR! stack     at new SemVer (C:\dev\nodejs\node_modules\npm\node_modules\semver\semver.js:295:11)
gyp ERR! stack     at Range.test (C:\dev\nodejs\node_modules\npm\node_modules\semver\semver.js:1049:15)
gyp ERR! stack     at C:\dev\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:94:17
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:742:7)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at maybeClose (child_process.js:1015:16)
gyp ERR! stack     at Socket.<anonymous> (child_process.js:1183:11)
gyp ERR! stack     at Socket.emit (events.js:107:17)
gyp ERR! stack     at Pipe.close (net.js:485:12)
```

System Info:

* Windows 8.1 x64
* Visual Studio 2010
* Visual Studio 2012
* Visual Studio 2015 RC
* Node v0.12.4
* NPM v2.10.1

Any ideas?
   
Full output:
    
```
C:\Study\MongoDB 101\Week1\homework_1_2\hw1-2\hw1-2>npm install mongodb  > error.log
npm WARN installMany nopt was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
npm WARN installMany npmlog was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
npm WARN installMany request was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
npm WARN installMany semver was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
npm WARN installMany tar was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
npm WARN installMany tar-pack was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
npm WARN installMany mkdirp was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
npm WARN installMany rc was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
npm WARN installMany rimraf was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack TypeError: Invalid Version: 3.5.0a4
gyp ERR! stack     at new SemVer (C:\dev\nodejs\node_modules\npm\node_modules\semver\semver.js:295:11)
gyp ERR! stack     at Range.test (C:\dev\nodejs\node_modules\npm\node_modules\semver\semver.js:1049:15)
gyp ERR! stack     at C:\dev\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:94:17
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:742:7)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at maybeClose (child_process.js:1015:16)
gyp ERR! stack     at Socket.<anonymous> (child_process.js:1183:11)
gyp ERR! stack     at Socket.emit (events.js:107:17)
gyp ERR! stack     at Pipe.close (net.js:485:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\dev\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Study\\MongoDB 101\\Week1\\homework_1_2\\hw1-2\\hw1-2\\node_modules\\mongodb\\node_modules\\mongodb-core\\node_modules\\bson\\node_modules\\bson-ext\
\build\\Release\\bson.node" "--module_name=bson" "--module_path=C:\\Study\\MongoDB 101\\Week1\\homework_1_2\\hw1-2\\hw1-2\\node_modules\\mongodb\\node_modules\\mongodb-core\\node_modules\\bson\\node_modules\\bson-ext\\build\\Release"
gyp ERR! cwd C:\Study\MongoDB 101\Week1\homework_1_2\hw1-2\hw1-2\node_modules\mongodb\node_modules\mongodb-core\node_modules\bson\node_modules\bson-ext
gyp ERR! node -v v0.12.4
gyp ERR! node-gyp -v v1.0.3
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/TooTallNate/node-gyp/issues>
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=C:\Study\MongoDB 101\Week1\homework_1_2\hw1-2\hw1-2\node_modules\mongodb\node_modules\mongodb-core\node_modules\bson\node_modules\bson-ext\build\Release\bson.node --module_name=bson --module_path=C:
\Study\MongoDB 101\Week1\homework_1_2\hw1-2\hw1-2\node_modules\mongodb\node_modules\mongodb-core\node_modules\bson\node_modules\bson-ext\build\Release' (7)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Study\MongoDB 101\Week1\homework_1_2\hw1-2\hw1-2\node_modules\mongodb\node_modules\mongodb-core\node_modules\bson\node_modules\bson-ext\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:1015:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
node-pre-gyp ERR! System Windows_NT 6.3.9600
node-pre-gyp ERR! command "node" "C:\\Study\\MongoDB 101\\Week1\\homework_1_2\\hw1-2\\hw1-2\\node_modules\\mongodb\\node_modules\\mongodb-core\\node_modules\\bson\\node_modules\\bson-ext\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp.js" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Study\MongoDB 101\Week1\homework_1_2\hw1-2\hw1-2\node_modules\mongodb\node_modules\mongodb-core\node_modules\bson\node_modules\bson-ext
node-pre-gyp ERR! node -v v0.12.4
node-pre-gyp ERR! node-pre-gyp -v v0.6.4
node-pre-gyp ERR! not ok
```

**Comment by ant-fx** [comment]
Found the issue, I had a pre-release version of Python installed (3.5.0a4) which was causing the problem.

Uninstalled that and all is well.
