### ISSUE TITLE
E402: npm license has expired

### ISSUE THREAD

**Issue by andreafdaf** [npm/npm#8387]
I'm having trouble publishing to npme, publishing to the public registry works fine. We are using the trial license but it is still inside the validity time.

**license.json** is inside /etc/npme:

```
ubuntu@host:/etc/npme$ la
bin  couchdb  .license.json  logs  node_modules  .npmrc  package.json  service.json  whitelist
```
#### license.json

```
{
  "details": {
    "id": ...,
    "created": "2015-05-20T16:59:57.923Z",
    "updated": "2015-05-20T16:59:57.923Z",
    "product_id": "b7e73bbc-ee47-45fa-b62d-4282a9e29f97",
    "customer_id": ...,
    "plan_id": 2,
    "license_key": "...",
    "seats": 50,
    "begins": "2015-05-20T16:57:53.348Z",
    "ends": "2015-06-19T16:57:53.348Z",
    "stripe_subscription_id": null,
    "expired": false
  },
  "signature": "..."
}
```
#### console output

```
npm ERR! publish Failed PUT 402
npm ERR! Linux 3.19.0-18-generic
npm ERR! argv "node" "/usr/local/bin/npm" "publish"
npm ERR! node v0.10.38
npm ERR! npm  v2.10.1
npm ERR! code E402

npm ERR! npm license has expired : @company/npme-test
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/user/workspace/npme-test/npm-debug.log
```
#### npm-debug.log

```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'publish' ]
2 info using npm@2.10.1
3 info using node@v0.10.38
4 verbose publish [ '.' ]
5 silly cache add args [ '.', null ]
6 verbose cache add spec .
7 silly cache add parsed spec { raw: '.',
7 silly cache add   scope: null,
7 silly cache add   name: null,
7 silly cache add   rawSpec: '.',
7 silly cache add   spec: '/home/user/workspace/npme-test',
7 silly cache add   type: 'directory' }
8 verbose addLocalDirectory /home/user/.npm/@company/npme-test/1.0.1/package.tgz not in flight; packing
9 verbose tar pack [ '/home/user/.npm/@company/npme-test/1.0.1/package.tgz',
9 verbose tar pack   '/home/user/workspace/npme-test' ]
10 verbose tarball /home/user/.npm/@company/npme-test/1.0.1/package.tgz
11 verbose folder /home/user/workspace/npme-test
12 info prepublish @company/npme-test@1.0.1
13 verbose addLocalTarball adding from inside cache /home/user/.npm/@company/npme-test/1.0.1/package.tgz
14 silly cache afterAdd @company/npme-test@1.0.1
15 verbose afterAdd /home/user/.npm/@company/npme-test/1.0.1/package/package.json not in flight; writing
16 verbose afterAdd /home/user/.npm/@company/npme-test/1.0.1/package/package.json written
17 silly publish { name: '@company/npme-test',
17 silly publish   version: '1.0.1',
17 silly publish   description: 'test',
17 silly publish   main: 'index.js',
17 silly publish   scripts: { test: 'echo "Error: no test specified" && exit 1' },
17 silly publish   author: { name: 'ADF' },
17 silly publish   license: 'ISC',
17 silly publish   dependencies: { languages: '^0.1.3' },
17 silly publish   gitHead: '072137633611992ea7cb15cc8f1e8e42f4c1b2d6',
17 silly publish   readme: 'ERROR: No README data found!',
17 silly publish   _id: '@company/npme-test@1.0.1',
17 silly publish   _shasum: '2e120a3e3f098d034beeb1c3788aad4a5228a83f',
17 silly publish   _from: '.' }
18 verbose getPublishConfig undefined
19 silly mapToRegistry name @company/npme-test
20 silly mapToRegistry scope (from package name) @company
21 silly mapToRegistry registry http://module-registry.company.com:8080/
22 silly mapToRegistry uri http://module-registry.company.com:8080/@company%2fnpme-test
23 verbose publish registryBase http://module-registry.company.com:8080/
24 silly publish uploading /home/user/.npm/@company/npme-test/1.0.1/package.tgz
25 verbose request uri http://module-registry.company.com:8080/@company%2fnpme-test
26 verbose request sending authorization for write operation
27 info attempt registry request try #1 at 16:42:12
28 verbose request using bearer token for auth
29 verbose request id bf9f0e66c79c00fd
30 http request PUT http://module-registry.company.com:8080/@company%2fnpme-test
31 http 402 http://module-registry.company.com:8080/@company%2fnpme-test
32 verbose headers { 'content-type': 'application/json',
32 verbose headers   'content-length': '35',
32 verbose headers   date: 'Thu, 28 May 2015 14:42:11 GMT',
32 verbose headers   connection: 'keep-alive' }
33 verbose request invalidating /home/user/.npm/module-registry.company.com_8080/_40company_252fnpme-test on PUT
34 error publish Failed PUT 402
35 verbose stack Error: npm license has expired : @company/npme-test
35 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:247:14)
35 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:170:14)
35 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:368:22)
35 verbose stack     at Request.emit (events.js:98:17)
35 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1219:14)
35 verbose stack     at Request.emit (events.js:117:20)
35 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1167:12)
35 verbose stack     at IncomingMessage.emit (events.js:117:20)
35 verbose stack     at _stream_readable.js:944:16
35 verbose stack     at process._tickCallback (node.js:448:13)
36 verbose statusCode 402
37 verbose pkgid @company/npme-test
38 verbose cwd /home/user/workspace/npme-test
39 error Linux 3.19.0-18-generic
40 error argv "node" "/usr/local/bin/npm" "publish"
41 error node v0.10.38
42 error npm  v2.10.1
43 error code E402
44 error npm license has expired : @company/npme-test
45 error If you need help, you may report this error at:
45 error     <https://github.com/npm/npm/issues>
46 verbose exit [ 1, true ]
```

**Comment by seldo** [comment]
Hi, can you send this stuff plus your full license key to support@npmjs.com? We can check what's up with your license that way.
