### ISSUE TITLE
'make install' fails on npm#multi-stage

### ISSUE THREAD

**Issue by Atrophius** [npm/npm#8397]
Trying to setup the npm#multi-stage branch for testing and discovered `make install` fails with the following error. I should note that `make link` works fine and can be used for testing. Also tested and verified that `make install` works properly on npm#master.

```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/home/vagrant/npm/cli.js', 'install', '-g', '-f' ]
2 info using npm@3.0.0-pre.9
3 info using node@v0.12.4
4 warn using --force I sure hope you know what you are doing.
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 error install Couldn't read dependencies
8 verbose stack Error: ENOENT, open '/home/vagrant/.nvm/versions/node/v0.12.4/li
b/package.json'
8 verbose stack     at /home/vagrant/npm/lib/install.js:422:18
8 verbose stack     at /home/vagrant/npm/node_modules/iferr/index.js:13:50
8 verbose stack     at /home/vagrant/npm/node_modules/read-package-tree/rpt.js:1
79:9
8 verbose stack     at f (/home/vagrant/npm/node_modules/once/once.js:17:25)
8 verbose stack     at then (/home/vagrant/npm/node_modules/read-package-tree/rpt.js:165:22)
8 verbose stack     at f (/home/vagrant/npm/node_modules/once/once.js:17:25)
8 verbose stack     at then (/home/vagrant/npm/node_modules/read-package-tree/rpt.js:165:22)
8 verbose stack     at f (/home/vagrant/npm/node_modules/once/once.js:17:25)
8 verbose stack     at then (/home/vagrant/npm/node_modules/read-package-tree/rpt.js:165:22)
8 verbose stack     at f (/home/vagrant/npm/node_modules/once/once.js:17:25)
9 verbose cwd /home/vagrant/npm
10 error Linux 3.13.0-52-generic
11 error argv "node" "/home/vagrant/npm/cli.js" "install" "-g" "-f"
12 error node v0.12.4
13 error npm  v3.0.0-pre.9
14 error code ENOPACKAGEJSON
15 error errno 34
16 error package.json ENOENT, open '/home/vagrant/.nvm/versions/node/v0.12.4/lib/package.json'
16 error package.json This is most likely not a problem with npm itself.
16 error package.json npm can't find a package.json file in your current directory.
17 verbose exit [ 34, true ]
```

**Comment by iarna** [comment]
Hey, thanks for pointing this out.  I've fixed this w/ 6fa09cdd9d5f40fa9f587fc60202a7168a649791 and 21fd09afd40aaa4ad212fa052167234819b5181e
