### ISSUE TITLE
Improvement: better error message when dependencies can't be read

### ISSUE THREAD

**Issue by fresheneesz** [npm/npm#8400]
I got very confused when I got his error: 

```
npm ERR! install Couldn't read dependencies
npm ERR! SyntaxError: Unexpected end of input
npm ERR!     at Object.parse (native)
npm ERR!     at /home/vagrant/.nvm/v0.10.31/lib/node_modules/npm/lib/install.js:295:24
npm ERR!     at evalmachine.<anonymous>:271:14
npm ERR!     at /home/vagrant/.nvm/v0.10.31/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:102:5
npm ERR!     at Object.oncomplete (evalmachine.<anonymous>:107:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 2.6.32-431.29.2.el6.x86_64
npm ERR! command "/home/vagrant/.nvm/v0.10.31/bin/node" "/home/vagrant/.nvm/v0.10.31/bin/npm" "install"
npm ERR! cwd /home/vagrant/backend
npm ERR! node -v v0.10.31
npm ERR! npm -v 1.4.23
npm ERR! type unexpected_eos
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/vagrant/backend/npm-debug.log
npm ERR! not ok code 0
```

My package.json was correctly formatted, but it ended up being that my shrinkwrap file existed but was empty. This error should definitely say what file can't be read - without that this error is incredibly obtuse.

**Comment by KenanY** [comment]
@fresheneesz I guess this is also an issue on the latest stable release of `npm`? `1.4.23` is quite old.

**Comment by fresheneesz** [comment]
I haven't tested the lastest stable release, but I looked at the code that prints the exception, and I didn't see anything better
