### ISSUE TITLE
Error When Running install -g

### ISSUE THREAD

**Issue by ZaneClark** [npm/npm#8405]
When trying to install particle-cli I get this huge block of errors. 

```
Sammet-2:~ Zane Clark$ sudo npm install -g particle-cli
npm http GET https://registry.npmjs.org/particle-cli
npm http 304 https://registry.npmjs.org/particle-cli
npm WARN engine particle-cli@1.5.11: wanted: {"node":"^0.10.0"} (current: {"node":"v0.10.0","npm":"1.2.14"})
npm http GET https://registry.npmjs.org/chalk
npm http GET https://registry.npmjs.org/cli-spinner
npm http GET https://registry.npmjs.org/hogan.js
npm http GET https://registry.npmjs.org/glob
npm http GET https://registry.npmjs.org/inquirer
npm http GET https://registry.npmjs.org/node-wifiscanner2
npm http GET https://registry.npmjs.org/request
npm http GET https://registry.npmjs.org/when
npm http GET https://registry.npmjs.org/xtend
npm http GET https://registry.npmjs.org/softap-setup
npm http GET https://registry.npmjs.org/serialport
npm http GET https://registry.npmjs.org/moment
npm http 200 https://registry.npmjs.org/hogan.js
npm http 200 https://registry.npmjs.org/chalk
npm ERR! Error: No compatible version found: hogan.js@'^2.0.0'
npm ERR! Valid install targets:
npm ERR! ["1.0.0","1.0.2","1.0.4-dev","1.0.5-dev","2.0.0","3.0.1","3.0.2"]
npm ERR!     at installTargetsError (/usr/local/lib/node_modules/npm/lib/cache.js:682:10)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:597:10
npm ERR!     at saved (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:93:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 14.1.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "-g" "particle-cli"
npm ERR! cwd /Users/Zane Clark
npm ERR! node -v v0.10.0
npm ERR! npm -v 1.2.14
npm http 200 https://registry.npmjs.org/cli-spinner
npm http 200 https://registry.npmjs.org/request
npm http 200 https://registry.npmjs.org/inquirer
npm http 200 https://registry.npmjs.org/xtend
npm http 200 https://registry.npmjs.org/when
npm http 200 https://registry.npmjs.org/moment
npm http 200 https://registry.npmjs.org/node-wifiscanner2
npm http 200 https://registry.npmjs.org/serialport
npm http 200 https://registry.npmjs.org/glob
npm http 200 https://registry.npmjs.org/softap-setup
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/Zane Clark/npm-debug.log
npm ERR! not ok code 0
```

**Comment by KenanY** [comment]
@ZaneClark This is definitely caused by your extremely old version of `npm`. You should [upgrade](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm).

**Comment by ZaneClark** [comment]
I upgraded npm (I had to download the node.js installer, as running npm install -g npm@latest returned a similar block of errors) and got this:
```
sudo npm install -g particle-cli
npm WARN engine particle-cli@1.5.11: wanted: {"node":"^0.10.0"} (current: {"node":"0.12.4","npm":"2.10.1"})
\
> serialport@1.7.1 install /usr/local/lib/node_modules/particle-cli/node_modules/serialport
> node-pre-gyp install --fallback-to-build

make: *** No rule to make target `../../../../../../../../Users/Zane', needed by `Makefile'.  Stop.
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/usr/local/lib/node_modules/particle-cli/node_modules/serialport/build/serialport/v1.7.1/Release/node-v14-darwin-x64/serialport.node" "--module_name=serialport" "--module_path=/usr/local/lib/node_modules/particle-cli/node_modules/serialport/build/serialport/v1.7.1/Release/node-v14-darwin-x64"
gyp ERR! cwd /usr/local/lib/node_modules/particle-cli/node_modules/serialport
gyp ERR! node -v v0.12.4
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/local/lib/node_modules/particle-cli/node_modules/serialport/build/serialport/v1.7.1/Release/node-v14-darwin-x64/serialport.node --module_name=serialport --module_path=/usr/local/lib/node_modules/particle-cli/node_modules/serialport/build/serialport/v1.7.1/Release/node-v14-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/particle-cli/node_modules/serialport/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:1015:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
node-pre-gyp ERR! System Darwin 14.1.0
node-pre-gyp ERR! command "node" "/usr/local/lib/node_modules/particle-cli/node_modules/serialport/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/particle-cli/node_modules/serialport
node-pre-gyp ERR! node -v v0.12.4
node-pre-gyp ERR! node-pre-gyp -v v0.6.7
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/local/lib/node_modules/particle-cli/node_modules/serialport/build/serialport/v1.7.1/Release/node-v14-darwin-x64/serialport.node --module_name=serialport --module_path=/usr/local/lib/node_modules/particle-cli/node_modules/serialport/build/serialport/v1.7.1/Release/node-v14-darwin-x64' (1)
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "particle-cli"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE

npm ERR! serialport@1.7.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the serialport@1.7.1 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the serialport package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls serialport
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Zane Clark/npm-debug.log
```

Leading me to think it's probably something else.

**Comment by KenanY** [comment]
@ZaneClark Looks like `make` is throwing an error now. I can't really tell why.

**Comment by snopeks** [comment]
Hello @ZaneClark  We haven’t heard back and we’re trying to clean up some issues. If this is still a problem, can you please reply and let us know? We’ll be happy to reopen if necessary.
