### ISSUE TITLE
trying to install serialport get "no compatible version found: debug..."

### ISSUE THREAD

**Issue by rempatterson** [npm/npm#8412]
I'm trying to  install node.js to work on a Raspberry Pi running Raspbian with an AlaMode shield.

The error messages concluded with a request to post here:

```
root@edison:~# npm install serialport
npm http GET https://registry.npmjs.org/serialport
npm http 200 https://registry.npmjs.org/serialport
npm http GET https://registry.npmjs.org/serialport/-/serialport-1.7.4.tgz
npm http 200 https://registry.npmjs.org/serialport/-/serialport-1.7.4.tgz
npm http GET https://registry.npmjs.org/nan
npm http GET https://registry.npmjs.org/optimist
npm http GET https://registry.npmjs.org/sf/0.1.7
npm http GET https://registry.npmjs.org/async/0.9.0
npm http GET https://registry.npmjs.org/bindings/1.2.1
npm http GET https://registry.npmjs.org/debug
npm http 200 https://registry.npmjs.org/nan
npm http 200 https://registry.npmjs.org/debug
npm http 200 https://registry.npmjs.org/async/0.9.0
npm http 200 https://registry.npmjs.org/sf/0.1.7
npm http 200 https://registry.npmjs.org/optimist
npm http 200 https://registry.npmjs.org/bindings/1.2.1
npm http GET https://registry.npmjs.org/nan/-/nan-1.8.4.tgz
npm http GET https://registry.npmjs.org/optimist/-/optimist-0.6.1.tgz
npm http GET https://registry.npmjs.org/async/-/async-0.9.0.tgz
npm http GET https://registry.npmjs.org/sf/-/sf-0.1.7.tgz
npm http GET https://registry.npmjs.org/bindings/-/bindings-1.2.1.tgz
npm http 200 https://registry.npmjs.org/nan/-/nan-1.8.4.tgz
npm http 200 https://registry.npmjs.org/optimist/-/optimist-0.6.1.tgz
npm http 200 https://registry.npmjs.org/async/-/async-0.9.0.tgz
npm http 200 https://registry.npmjs.org/bindings/-/bindings-1.2.1.tgz
npm http 200 https://registry.npmjs.org/sf/-/sf-0.1.7.tgz
npm ERR! Error: No compatible version found: debug@'^2.1.1'
npm ERR! Valid install targets:
npm ERR! ["0.0.1","0.1.0","0.2.0","0.3.0","0.4.0","0.4.1","0.5.0","0.6.0","0.7.0","0.7.1","0.7.2","0.7.3","0.7.4","0.8.0","0.8.1","1.0.0","1.0.1","1.0.2","1.0.3","1.0.4","2.0.0","2.1.0","2.1.1","2.1.2","2.1.3","2.2.0"]
npm ERR!     at installTargetsError (/opt/node/lib/node_modules/npm/lib/cache.js:719:10)
npm ERR!     at /opt/node/lib/node_modules/npm/lib/cache.js:641:10
npm ERR!     at saved (/opt/node/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.18.7+
npm ERR! command "/opt/node/bin/node" "/opt/node/bin/npm" "install" "serialport"
npm ERR! cwd /root
npm ERR! node -v v0.10.12
npm ERR! npm -v 1.2.32
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /root/npm-debug.log
npm ERR! not ok code 0
```

I am new  here so please be patient.  Does this say I did something wrong?

Bill

**Comment by KenanY** [comment]
@rempatterson `npm@1.2.32` over a year old, and does not support the `^` semver operator you see here:

```
npm ERR! Error: No compatible version found: debug@'^2.1.1'
```

hence, `npm` throws an error since it cannot find a suitable version of `debug`. The solution is to simply [upgrade](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm).

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
