### ISSUE TITLE
AIX error?

### ISSUE THREAD

**Issue by avuong** [npm/npm#8427]
Hello, I am attempting to install jasmine on AIX with
npm install -g jasmine

but I am running into this issue:

```
npm ERR! AIX 1
npm ERR! argv "/ibm/node/bin/node" "/ibm/node/bin/npm" "install" "-g" "jasmine"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code DEPTH_ZERO_SELF_SIGNED_CERT

npm ERR! self signed certificate
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /ibm/node/bin/npm-debug.log
```

Do you have any suggestions on how to fix this?

Thanks

**Comment by avuong** [comment]
This is the npm-debug.log file text:

0 info it worked if it ends with ok
1 verbose cli [ '/ibm/node/bin/node',
1 verbose cli   '/ibm/node/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'jasmine' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 silly cache add args [ 'jasmine', null ]
5 verbose cache add spec jasmine
6 silly cache add parsed spec { raw: 'jasmine',
6 silly cache add   scope: null,
6 silly cache add   name: 'jasmine',
6 silly cache add   rawSpec: '',
6 silly cache add   spec: '*',
6 silly cache add   type: 'range' }
7 verbose addNamed jasmine@*
8 silly addNamed semver.valid null
9 silly addNamed semver.validRange *
10 silly addNameRange { name: 'jasmine', range: '*', hasData: false }
11 silly mapToRegistry name jasmine
12 silly mapToRegistry using default registry
13 silly mapToRegistry registry https://registry.npmjs.org/
14 silly mapToRegistry uri https://registry.npmjs.org/jasmine
15 verbose addNameRange registry:https://registry.npmjs.org/jasmine not in flight; fetching
16 verbose request uri https://registry.npmjs.org/jasmine
17 verbose request no auth needed
18 info attempt registry request try #1 at 11:43:21 AM
19 verbose request id de3c51c0d2743fa2
20 http request GET https://registry.npmjs.org/jasmine
21 info retry will retry, error on last attempt: Error: self signed certificate
22 info attempt registry request try #2 at 11:43:31 AM
23 http request GET https://registry.npmjs.org/jasmine
24 info retry will retry, error on last attempt: Error: self signed certificate
25 info attempt registry request try #3 at 11:44:31 AM
26 http request GET https://registry.npmjs.org/jasmine
27 verbose stack Error: self signed certificate
27 verbose stack     at Error (native)
27 verbose stack     at TLSSocket.<anonymous> (_tls_wrap.js:929:36)
27 verbose stack     at TLSSocket.emit (events.js:104:17)
27 verbose stack     at TLSSocket._finishInit (_tls_wrap.js:460:8)
28 verbose cwd /ibm/node/bin
29 error AIX 1
30 error argv "/ibm/node/bin/node" "/ibm/node/bin/npm" "install" "-g" "jasmine"
31 error node v0.12.2
32 error npm  v2.7.4
33 error code DEPTH_ZERO_SELF_SIGNED_CERT
34 error self signed certificate
35 error If you need help, you may report this error at:
35 error     <https://github.com/npm/npm/issues>
36 verbose exit [ 1, true ]
