### ISSUE TITLE
npm publish 503 error

### ISSUE THREAD

**Issue by jtwebman** [npm/npm#8430]
I am getting the following error when running npm publish on a package.

```bash
npm publish
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! publish Failed PUT 503
npm ERR! Darwin 14.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "publish"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1

npm ERR! Unexpected token <
npm ERR! <!DOCTYPE html>
npm ERR!     <html>
npm ERR!     <head>
npm ERR!       <meta name="viewport" content="width=device-width, initial-scale=1">
npm ERR!       <style type="text/css">
npm ERR!         html, body, iframe { margin: 0; padding: 0; height: 100%; }
npm ERR!         iframe { display: block; width: 100%; border: none; }
npm ERR!       </style>
npm ERR!     <title>Application Error</title>
npm ERR!     </head>
npm ERR!     <body>
npm ERR!       <iframe src="//s3.amazonaws.com/heroku_pages/error.html">
npm ERR!         <p>Application Error</p>
npm ERR!       </iframe>
npm ERR!     </body>
npm ERR!     </html>
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/JT/src/bookshelf-scopes/npm-debug.log
```

Here is my log file:

```log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'publish' ]
2 info using npm@2.10.1
3 info using node@v0.12.4
4 verbose publish [ '.' ]
5 silly cache add args [ '.', null ]
6 verbose cache add spec .
7 silly cache add parsed spec { raw: '.',
7 silly cache add   scope: null,
7 silly cache add   name: null,
7 silly cache add   rawSpec: '.',
7 silly cache add   spec: '/Users/JT/src/bookshelf-scopes',
7 silly cache add   type: 'directory' }
8 verbose addLocalDirectory /Users/JT/.npm/bookshelf-scopes/1.2.0/package.tgz not in flight; packing
9 verbose tar pack [ '/Users/JT/.npm/bookshelf-scopes/1.2.0/package.tgz',
9 verbose tar pack   '/Users/JT/src/bookshelf-scopes' ]
10 verbose tarball /Users/JT/.npm/bookshelf-scopes/1.2.0/package.tgz
11 verbose folder /Users/JT/src/bookshelf-scopes
12 info prepublish bookshelf-scopes@1.2.0
13 verbose addLocalTarball adding from inside cache /Users/JT/.npm/bookshelf-scopes/1.2.0/package.tgz
14 silly cache afterAdd bookshelf-scopes@1.2.0
15 verbose afterAdd /Users/JT/.npm/bookshelf-scopes/1.2.0/package/package.json not in flight; writing
16 verbose afterAdd /Users/JT/.npm/bookshelf-scopes/1.2.0/package/package.json written
17 silly publish { name: 'bookshelf-scopes',
17 silly publish   version: '1.2.0',
17 silly publish   description: 'Giving you Rails like scopes in Bookshelf.js.',
17 silly publish   main: 'src/scopes.js',
17 silly publish   dependencies: { lodash: '^3.9.3' },
17 silly publish   devDependencies:
17 silly publish    { bluebird: '^2.9.27',
17 silly publish      bookshelf: '^0.8.1',
17 silly publish      chai: '^2.3.0',
17 silly publish      knex: '^0.8.6',
17 silly publish      mocha: '^2.2.5',
17 silly publish      sqlite3: '^3.0.8' },
17 silly publish   scripts: { test: 'mocha' },
17 silly publish   repository:
17 silly publish    { type: 'git',
17 silly publish      url: 'git+https://github.com/pk4media/bookshelf-scopes.git' },
17 silly publish   keywords: [ 'bookshelf', 'scopes', 'rails' ],
17 silly publish   author: { name: 'JT', url: 'https://github.com/jtwebman' },
17 silly publish   contributors: [ { name: 'David Negstad', url: 'https://github.com/dnegstad' } ],
17 silly publish   license: 'MIT',
17 silly publish   bugs: { url: 'https://github.com/pk4media/bookshelf-scopes/issues' },
17 silly publish   homepage: 'https://github.com/pk4media/bookshelf-scopes',
17 silly publish   readme: '# Bookshelf-Scopes\n\n[![Circle CI](https://circleci.com/gh/pk4media/bookshelf-scopes/tree/master.svg?style=svg&circle-token=4f67b03079c057b9ae20ef5485459f97215eebe7)](https://circleci.com/gh/pk4media/bookshelf-scopes/tree/master)\n\nGiving you Rails like scopes in Bookshelf.js.\n\nIf you add in the plugin like so:\n```javascript\nvar bookshelf = require(\'bookshelf\')(knex);\n\nbookshelf.plugin(require(\'bookshelf-scopes\'));\n```\n\nYou will then be able to add a scopes property on your models that will give you\na Knex query builder as the first argument and then followed by any additional\narguments. See examples below.\n\nAlso just like rails we can set a default. See examples below.\n\n## Examples\n\n### Simple\n\nYou can define a model with scopes and an active function like this:\n```javascript\nvar TestModel = bookshelf.Model.extend({\n  tableName: \'testmodel\',\n  scopes: {\n    active: function(qb) {\n      qb.where({status: \'Active\'});\n    },\n    nameContains: function(gb, text) {\n      qb.where(knex.raw(\'name LIKE ?\', \'%\' + name + \'%\'));\n    }\n  }\n});\n```\nYou can now run code like this to get all Active:\n```javascript\nTestModel.active().fetchAll().then(function(allActiveTests) {\n  ...\n});\n```\nYou can also get all active where name contains test as well:\n```javascript\nTestModel.active().nameContains(\'test\').fetchAll().then(function(allActiveTests) {\n  ...\n});\n```\n\n### Default\n\nYou can define a model with scopes and default like this:\n```javascript\nvar TestModel = bookshelf.Model.extend({\n  tableName: \'testmodel\',\n  scopes: {\n    default: function(qb) {\n      qb.where({archived: 0});\n    }\n  }\n});\n```\nNow if you call fetchAll or fetch on any of your queries you will only get items that have archive set to 0:\n```javascript\nTestModel.fetchAll().then(function(allUnArchived) {\n  ...\n});\n```\n\nIf you need to query without the default scope you can call unscoped like so:\n```javascript\nTestModel.unscoped().fetchAll().then(function(allModels) {\n  ...\n});\n```\n\n### Combine Methods In Scope\n\nYou can define a bunch of scope functions you can also combine them in another scope function.\n```javascript\nvar TestModel = bookshelf.Model.extend({\n  tableName: \'testmodel\',\n  scopes: {\n    running: function(qb) {\n      qb.where({running: 0});\n    },\n    byDate: function(qb, date) {\n      qb.where(\'created_date\', \'>=\', date);\n    },\n    runningByDate: function(qb, date) {\n      this.running(qb);\n      this.byDate(qb, date);\n    }\n  }\n});\n```\nNow you can use the combined scope method as well to make things more readable.\n```javascript\nTestModel.runningByDate(\'2015-01-01\').fetchAll().then(function(allUnArchived) {\n  ...\n});\n```\n\n### Override Initialize\n\nIf in your model you set an initialize you will need to call addScope() to add default scope if you want it\n\n```javascript\nvar TestModel = bookshelf.Model.extend({\n  tableName: \'testmodel\',\n  scopes: {\n    default: function(qb) {\n      qb.where({status: \'Active\'});\n    }\n  },\n  initialize: function() {\n    this.addScope(); //Now default scope is set, all other scopes work regardless.\n    this.newValue = 1;\n  }\n});\n```\n\nThen calls to fetchAll will include it.\n```javascript\nTestModel.fetchAll().then(function(allActive) {\n  ...\n});\n```\n',
17 silly publish   readmeFilename: 'README.md',
17 silly publish   gitHead: '46cfddc8af727f92519c76b906769c7cf159741e',
17 silly publish   _id: 'bookshelf-scopes@1.2.0',
17 silly publish   _shasum: '40b69f15888f7ea2341b48765cac0d991ca6e593',
17 silly publish   _from: '.' }
18 verbose getPublishConfig undefined
19 silly mapToRegistry name bookshelf-scopes
20 silly mapToRegistry using default registry
21 silly mapToRegistry registry https://npm-proxy.fury.io/vobCvTGDZhxjyvrfehmt/pk4media/
22 silly mapToRegistry uri https://npm-proxy.fury.io/vobCvTGDZhxjyvrfehmt/pk4media/bookshelf-scopes
23 verbose publish registryBase https://npm-proxy.fury.io/vobCvTGDZhxjyvrfehmt/pk4media/
24 silly publish uploading /Users/JT/.npm/bookshelf-scopes/1.2.0/package.tgz
25 verbose request uri https://npm-proxy.fury.io/vobCvTGDZhxjyvrfehmt/pk4media/bookshelf-scopes
26 verbose request sending authorization for write operation
27 info attempt registry request try #1 at 5:40:48 PM
28 verbose request using bearer token for auth
29 verbose request id ################ // Removed key to not let anyone take the token
30 http request PUT https://npm-proxy.fury.io/vobCvTGDZhxjyvrfehmt/pk4media/bookshelf-scopes
31 http 503 https://npm-proxy.fury.io/vobCvTGDZhxjyvrfehmt/pk4media/bookshelf-scopes
32 verbose bad json <!DOCTYPE html>
32 verbose bad json     <html>
32 verbose bad json     <head>
32 verbose bad json       <meta name="viewport" content="width=device-width, initial-scale=1">
32 verbose bad json       <style type="text/css">
32 verbose bad json         html, body, iframe { margin: 0; padding: 0; height: 100%; }
32 verbose bad json         iframe { display: block; width: 100%; border: none; }
32 verbose bad json       </style>
32 verbose bad json     <title>Application Error</title>
32 verbose bad json     </head>
32 verbose bad json     <body>
32 verbose bad json       <iframe src="//s3.amazonaws.com/heroku_pages/error.html">
32 verbose bad json         <p>Application Error</p>
32 verbose bad json       </iframe>
32 verbose bad json     </body>
32 verbose bad json     </html>
33 error registry error parsing json
34 info retry will retry, error on last attempt: SyntaxError: Unexpected token <
34 info retry <!DOCTYPE html>
34 info retry     <html>
34 info retry     <head>
34 info retry       <meta name="viewport" content="width=device-width, initial-scale=1">
34 info retry       <style type="text/css">
34 info retry         html, body, iframe { margin: 0; padding: 0; height: 100%; }
34 info retry         iframe { display: block; width: 100%; border: none; }
34 info retry       </style>
34 info retry     <title>Application Error</title>
34 info retry     </head>
34 info retry     <body>
34 info retry       <iframe src="//s3.amazonaws.com/heroku_pages/error.html">
34 info retry         <p>Application Error</p>
34 info retry       </iframe>
34 info retry     </body>
34 info retry     </html>
35 info attempt registry request try #2 at 5:41:28 PM
36 verbose request using bearer token for auth
37 http request PUT https://npm-proxy.fury.io/vobCvTGDZhxjyvrfehmt/pk4media/bookshelf-scopes
38 http 503 https://npm-proxy.fury.io/vobCvTGDZhxjyvrfehmt/pk4media/bookshelf-scopes
39 verbose bad json <!DOCTYPE html>
39 verbose bad json     <html>
39 verbose bad json     <head>
39 verbose bad json       <meta name="viewport" content="width=device-width, initial-scale=1">
39 verbose bad json       <style type="text/css">
39 verbose bad json         html, body, iframe { margin: 0; padding: 0; height: 100%; }
39 verbose bad json         iframe { display: block; width: 100%; border: none; }
39 verbose bad json       </style>
39 verbose bad json     <title>Application Error</title>
39 verbose bad json     </head>
39 verbose bad json     <body>
39 verbose bad json       <iframe src="//s3.amazonaws.com/heroku_pages/error.html">
39 verbose bad json         <p>Application Error</p>
39 verbose bad json       </iframe>
39 verbose bad json     </body>
39 verbose bad json     </html>
40 error registry error parsing json
41 info retry will retry, error on last attempt: SyntaxError: Unexpected token <
41 info retry <!DOCTYPE html>
41 info retry     <html>
41 info retry     <head>
41 info retry       <meta name="viewport" content="width=device-width, initial-scale=1">
41 info retry       <style type="text/css">
41 info retry         html, body, iframe { margin: 0; padding: 0; height: 100%; }
41 info retry         iframe { display: block; width: 100%; border: none; }
41 info retry       </style>
41 info retry     <title>Application Error</title>
41 info retry     </head>
41 info retry     <body>
41 info retry       <iframe src="//s3.amazonaws.com/heroku_pages/error.html">
41 info retry         <p>Application Error</p>
41 info retry       </iframe>
41 info retry     </body>
41 info retry     </html>
42 info attempt registry request try #3 at 5:42:59 PM
43 verbose request using bearer token for auth
44 http request PUT https://npm-proxy.fury.io/vobCvTGDZhxjyvrfehmt/pk4media/bookshelf-scopes
45 http 503 https://npm-proxy.fury.io/vobCvTGDZhxjyvrfehmt/pk4media/bookshelf-scopes
46 verbose bad json <!DOCTYPE html>
46 verbose bad json     <html>
46 verbose bad json     <head>
46 verbose bad json       <meta name="viewport" content="width=device-width, initial-scale=1">
46 verbose bad json       <style type="text/css">
46 verbose bad json         html, body, iframe { margin: 0; padding: 0; height: 100%; }
46 verbose bad json         iframe { display: block; width: 100%; border: none; }
46 verbose bad json       </style>
46 verbose bad json     <title>Application Error</title>
46 verbose bad json     </head>
46 verbose bad json     <body>
46 verbose bad json       <iframe src="//s3.amazonaws.com/heroku_pages/error.html">
46 verbose bad json         <p>Application Error</p>
46 verbose bad json       </iframe>
46 verbose bad json     </body>
46 verbose bad json     </html>
47 error registry error parsing json
48 verbose headers { connection: 'keep-alive',
48 verbose headers   server: 'Cowboy',
48 verbose headers   date: 'Tue, 02 Jun 2015 00:43:31 GMT',
48 verbose headers   'content-length': '484',
48 verbose headers   'content-type': 'text/html; charset=utf-8',
48 verbose headers   'cache-control': 'no-cache, no-store' }
49 verbose request invalidating /Users/JT/.npm/npm-proxy.fury.io/vobCvTGDZhxjyvrfehmt/pk4media/bookshelf-scopes on PUT
50 error publish Failed PUT 503
51 verbose stack SyntaxError: Unexpected token <
51 verbose stack <!DOCTYPE html>
51 verbose stack     <html>
51 verbose stack     <head>
51 verbose stack       <meta name="viewport" content="width=device-width, initial-scale=1">
51 verbose stack       <style type="text/css">
51 verbose stack         html, body, iframe { margin: 0; padding: 0; height: 100%; }
51 verbose stack         iframe { display: block; width: 100%; border: none; }
51 verbose stack       </style>
51 verbose stack     <title>Application Error</title>
51 verbose stack     </head>
51 verbose stack     <body>
51 verbose stack       <iframe src="//s3.amazonaws.com/heroku_pages/error.html">
51 verbose stack         <p>Application Error</p>
51 verbose stack       </iframe>
51 verbose stack     </body>
51 verbose stack     </html>
51 verbose stack     at Object.parse (native)
51 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:197:23)
51 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:170:14)
51 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:368:22)
51 verbose stack     at Request.emit (events.js:110:17)
51 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1219:14)
51 verbose stack     at Request.emit (events.js:129:20)
51 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1167:12)
51 verbose stack     at IncomingMessage.emit (events.js:129:20)
51 verbose stack     at _stream_readable.js:908:16
52 verbose cwd /Users/JT/src/bookshelf-scopes
53 error Darwin 14.3.0
54 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "publish"
55 error node v0.12.4
56 error npm  v2.10.1
57 error Unexpected token <
57 error <!DOCTYPE html>
57 error     <html>
57 error     <head>
57 error       <meta name="viewport" content="width=device-width, initial-scale=1">
57 error       <style type="text/css">
57 error         html, body, iframe { margin: 0; padding: 0; height: 100%; }
57 error         iframe { display: block; width: 100%; border: none; }
57 error       </style>
57 error     <title>Application Error</title>
57 error     </head>
57 error     <body>
57 error       <iframe src="//s3.amazonaws.com/heroku_pages/error.html">
57 error         <p>Application Error</p>
57 error       </iframe>
57 error     </body>
57 error     </html>
58 error If you need help, you may report this error at:
58 error     <https://github.com/npm/npm/issues>
59 verbose exit [ 1, true ]
```

**Comment by jtwebman** [comment]
This is a proxy issue
