### ISSUE TITLE
Not able to Install MongoDB NPM on Windows 8

### ISSUE THREAD

**Issue by Raj-esh** [npm/npm#8438]
The following is the complete installation procedure and errors:

```
D:\Mongo\homework_1_2\hw1-2\hw1-2>npm install mongodb

> kerberos@0.0.12 install D:\Mongo\homework_1_2\hw1-2\hw1-2\node_modules\mongodb\node_modules\mongodb-core\node_modules\kerberos
> (node-gyp rebuild 2> builderror.log) || (exit 0)

D:\Mongo\homework_1_2\hw1-2\hw1-2\node_modules\mongodb\node_modules\mongodb-core\node_modules\kerberos>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (rebuild)
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
D:\Mongo\homework_1_2\hw1-2\hw1-2\node_modules\mongodb\node_modules\mongodb-core\node_modules\kerberos\build\kerberos.vcxproj(18,3): error MSB4019: The imported project "D:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
npm WARN installMany nopt was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
npm WARN installMany npmlog was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
npm WARN installMany request was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
npm WARN installMany semver was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
npm WARN installMany tar was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
npm WARN installMany tar-pack was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
npm WARN installMany mkdirp was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
npm WARN installMany rc was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree
npm WARN installMany rimraf was bundled with node-pre-gyp@0.6.4, but bundled package wasn't found in unpacked tree

> bson-ext@0.1.7 install D:\Mongo\homework_1_2\hw1-2\hw1-2\node_modules\mongodb\node_modules\mongodb-core\node_modules\bson\node_modules\bson-ext
> (node-pre-gyp install --fallback-to-build) || (node-gyp rebuild 2> builderror.log) || (exit 0)


D:\Mongo\homework_1_2\hw1-2\hw1-2\node_modules\mongodb\node_modules\mongodb-core\node_modules\bson\node_modules\bson-ext>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean )  else (clean)

D:\Mongo\homework_1_2\hw1-2\hw1-2\node_modules\mongodb\node_modules\mongodb-core\node_modules\bson\node_modules\bson-ext>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure --fallback-to-build --module=D:\Mongo\homework_1_2\hw1-2\hw1-2\node_modules\mongodb\node_modules\mongodb-core\node_modules\bson\node_modules\bson-ext\build\Release\bson.node --module_name=bson --module_path=D:\Mongo\homework_1_2\hw1-2\hw1-2\node_modules\mongodb\node_modules\mongodb-core\node_modules\bson\node_modules\bson-ext\build\Release )  else (configure --fallback-to-build --module=D:\Mongo\homework_1_2\hw1-2\hw1-2\node_modules\mongodb\node_modules\mongodb-core\node_modules\bson\node_modules\bson-ext\build\Release\bson.node --module_name=bson --module_path=D:\Mongo\homework_1_2\hw1-2\hw1-2\node_modules\mongodb\node_modules\mongodb-core\node_modules\bson\node_modules\bso
n-ext\build\Release )

D:\Mongo\homework_1_2\hw1-2\hw1-2\node_modules\mongodb\node_modules\mongodb-core\node_modules\bson\node_modules\bson-ext>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" build --fallback-to-build --module=D:\Mongo\homework_1_2\hw1-2\hw1-2\node_modules\mongodb\node_modules\mongodb-core\node_modules\bson\node_modules\bson-ext\build\Release\bson.node --module_name=bson --module_path=D:\Mongo\homework_1_2\hw1-2\hw1-2\node_modules\mongodb\node_modules\mongodb-core\node_modules\bson\node_modules\bson-ext\build\Release )  else (build --fallback-to-build --module=D:\Mongo\homework_1_2\hw1-2\hw1-2\node_modules\mongodb\node_modules\mongodb-core\node_modules\bson\node_modules\bson-ext\build\Release\bson.node --module_name=bson --module_path=D:\Mongo\homework_1_2\hw1-2\hw1-2\node_modules\mongodb\node_modules\mongodb-core\node_modules\bson\node_modules\bson-ext\build\Release )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
D:\Mongo\homework_1_2\hw1-2\hw1-2\node_modules\mongodb\node_modules\mongodb-core\node_modules\bson\node_modules\bson-ext\build\bson.vcxproj(18,3): error MSB4019: The imported project "D:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=D:\\Mongo\\homework_1_2\\hw1-2\\hw1-2\\node_modules\\mongodb\\node_modules\\mongodb-core\\node_modules\\bson\\node_modules\\bson-ext\\build\\Release\\bson.node" "--module_name=bson" "--module_path=D:\\Mongo\\homework_1_2\\hw1-2\\hw1-2\\node_modules\\mongodb\\node_modules\\mongodb-core\\node_modules\\bson\\node_modules\\bson-ext\\build\\Release"
gyp ERR! cwd D:\Mongo\homework_1_2\hw1-2\hw1-2\node_modules\mongodb\node_modules\mongodb-core\node_modules\bson\node_modules\bson-ext
gyp ERR! node -v v0.12.4
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd build --fallback-to-build --module=D:\Mongo\homework_1_2\hw1-2\hw1-2\node_modules\mongodb\node_modules\mongodb-core\node_modules\bson\node_modules\bson-ext\build\Release\bson.node --module_name=bson --module_path=D:\Mongo\homework_1_2\hw1-2\hw1-2\node_modules\mongodb\node_modules\mongodb-core\node_modules\bson\node_modules\bson-ext\build\Release' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\Mongo\homework_1_2\hw1-2\hw1-2\node_modules\mongodb\node_modules\mongodb-core\node_modules\bson\node_modules\bson-ext\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:1015:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
node-pre-gyp ERR! System Windows_NT 6.2.9200
node-pre-gyp ERR! command "node" "D:\\Mongo\\homework_1_2\\hw1-2\\hw1-2\\node_modules\\mongodb\\node_modules\\mongodb-core\\node_modules\\bson\\node_modules\\bs
on-ext\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp.js" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd D:\Mongo\homework_1_2\hw1-2\hw1-2\node_modules\mongodb\node_modules\mongodb-core\node_modules\bson\node_modules\bson-ext
node-pre-gyp ERR! node -v v0.12.4
node-pre-gyp ERR! node-pre-gyp -v v0.6.4
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd build --fallback-to-build --module=D:\Mongo\homework_1_2\hw1-2\hw1-2\node_modules\mongodb\node_modules\mongodb-core\node_modules\bson\node_modules\bson-ext\build\Release\bson.node --module_name=bson --module_path=D:\Mongo\homework_1_2\hw1-2\hw1-2\node_modules\mongodb\node_modules\mongodb-core\node_modules\bson\node_modules\bson-ext\build\Release' (1)

D:\Mongo\homework_1_2\hw1-2\hw1-2\node_modules\mongodb\node_modules\mongodb-core\node_modules\bson\node_modules\bson-ext>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (rebuild)
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
D:\Mongo\homework_1_2\hw1-2\hw1-2\node_modules\mongodb\node_modules\mongodb-core\node_modules\bson\node_modules\bson-ext\build\bson.vcxproj(18,3): error MSB4019: The imported project "D:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
mongodb@2.0.33 node_modules\mongodb
├── readable-stream@1.0.31 (inherits@2.0.1, isarray@0.0.1, string_decoder@0.10.31, core-util-is@1.0.1)
└── mongodb-core@1.1.32 (kerberos@0.0.12, bson@0.3.2)

D:\Mongo\homework_1_2\hw1-2\hw1-2>node app.js
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }

js-bson: Failed to load c++ bson extension, using pure JS version
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }

js-bson: Failed to load c++ bson extension, using pure JS version
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }

js-bson: Failed to load c++ bson extension, using pure JS version
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }

js-bson: Failed to load c++ bson extension, using pure JS version
```

**Comment by othiym23** [comment]
It looks like there's either a problem with your Visual Studio installation, or you're using a version of Visual Studio that doesn't work with one or both of `node-gyp` or `node-pre-gyp`. If you're using Visual Studio Express, make sure it's VSE 2013 and not VSE 2010.

As these are issues with tools used by `mongodb`, and don't have anything to do with npm itself, I'm going to close this. Good luck getting this sorted out! Getting started with Node native modules on Windows is definitely harder than it needs to be!

**Comment by alexjose** [comment]
I am also having this issue.

**Comment by efkan** [comment]
+1
