### ISSUE TITLE
not able to install laravel elixir

### ISSUE THREAD

**Issue by simonfunk** [npm/npm#8439]
Hi

i get an EAI error. looks like a typo error cause it tries to get the package trought regitry subdomain instead registry.

Here is my debug log:
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@2.9.1
3 info using node@v0.12.3
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 verbose readDependencies loading dependencies from D:\Workplace\htdocs\projects\keevo\package.json
6 verbose install where, deps [ 'D:\\Workplace\\htdocs\\projects\\keevo',
6 verbose install   [ 'gulp', 'laravel-elixir' ] ]
7 verbose install where, peers [ 'D:\\Workplace\\htdocs\\projects\\keevo', [] ]
8 verbose installManyTop reading for lifecycle D:\Workplace\htdocs\projects\keevo\package.json
9 info preinstall @
10 verbose installManyTop reading scoped package data from D:\Workplace\htdocs\projects\keevo\node_modules\gulp\package.json
11 verbose readDependencies loading dependencies from D:\Workplace\htdocs\projects\keevo\package.json
12 verbose targetResolver reading package data from D:\Workplace\htdocs\projects\keevo\node_modules\gulp\package.json
13 verbose targetResolver reading package data from D:\Workplace\htdocs\projects\keevo\node_modules\.bin\gulp\package.json
14 verbose targetResolver reading package data from D:\Workplace\htdocs\projects\keevo\node_modules\.bin\gulp.cmd\package.json
15 verbose already installed skipping gulp@^3.8.8 D:\Workplace\htdocs\projects\keevo
16 silly cache add args [ 'laravel-elixir@*', null ]
17 verbose cache add spec laravel-elixir@*
18 silly cache add parsed spec { raw: 'laravel-elixir@*',
18 silly cache add   scope: null,
18 silly cache add   name: 'laravel-elixir',
18 silly cache add   rawSpec: '*',
18 silly cache add   spec: '*',
18 silly cache add   type: 'range' }
19 silly addNamed laravel-elixir@*
20 verbose addNamed "*" is a valid semver range for laravel-elixir
21 silly addNameRange { name: 'laravel-elixir', range: '*', hasData: false }
22 silly mapToRegistry name laravel-elixir
23 silly mapToRegistry using default registry
24 silly mapToRegistry registry http://regitry.npmjs.org/
25 silly mapToRegistry uri http://regitry.npmjs.org/laravel-elixir
26 verbose addNameRange registry:http://regitry.npmjs.org/laravel-elixir not in flight; fetching
27 verbose request uri http://regitry.npmjs.org/laravel-elixir
28 verbose request no auth needed
29 info attempt registry request try #1 at 19:46:03
30 verbose request id 96a0d0cc19ad72b4
31 http request GET http://regitry.npmjs.org/laravel-elixir
32 info retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN
33 info attempt registry request try #2 at 19:46:14
34 http request GET http://regitry.npmjs.org/laravel-elixir
35 info retry will retry, error on last attempt: Error: getaddrinfo EAI_AGAIN
36 info attempt registry request try #3 at 19:47:15
37 http request GET http://regitry.npmjs.org/laravel-elixir
38 verbose stack Error: getaddrinfo EAI_AGAIN
38 verbose stack     at Object.exports._errnoException (util.js:746:11)
38 verbose stack     at errnoException (dns.js:49:15)
38 verbose stack     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:94:26)
39 verbose cwd D:\Workplace\htdocs\projects\***
40 error Windows_NT 6.1.7601
41 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
42 error node v0.12.3
43 error npm  v2.9.1
44 error code EAI_AGAIN
45 error errno EAI_AGAIN
46 error syscall getaddrinfo
47 error getaddrinfo EAI_AGAIN
48 error If you need help, you may report this error at:
48 error     <https://github.com/npm/npm/issues>
49 verbose exit [ 1, true ]
```

**Comment by othiym23** [comment]
What does `npm config get registry` return? It seems that something in your environment or your `.npmrc` is pointing at `https://regitry.npmjs.org`:

```
23 silly mapToRegistry using default registry
24 silly mapToRegistry registry http://regitry.npmjs.org/
```

You're right that it's a typo, but the typo seems to be on the machine running npm, not in any of the packages.

**Comment by simonfunk** [comment]
oh you're totaly right, i setted now new with npm config set registry https://registry.npmjs.org/
no idea how this happened, but thank you very much!
