### ISSUE TITLE
add-remote-git-file test fails on Windows

### ISSUE THREAD

**Issue by zkat** [npm/npm#8441]
While running `npm test` on Windows, one of the `add-remote-git` tests fails, while all the others seem to complete successfully.

The clone in this case seems to be failing because `child.git` isn't a valid repository -- @othiym23 says the init itself probably didn't work. 

Relevant logging output:

```
test/tap/add-remote-git-file.js ....................... 2/4 1s
  cache from repo
  not ok cached via git
    found:
      stack: "Error: Command failed: git -c core.longpaths=true clone --template=C:\\Users\\kat\\Documents\\GitHub\\npm\
\test\\npm_cache\\_git-remotes\\_templates --mirror file://c/Users/kat/Documents/GitHub/npm/test/tap/add-remote-git-file
/child.git C:\\Users\\kat\\Documents\\GitHub\\npm\\test\\npm_cache\\_git-remotes\\file-c-Users-kat-Documents-GitHub-npm-
test-tap-add-remote-git-file-child-git-58527840\nCloning into bare repository 'C:\\Users\\kat\\Documents\\GitHub\\npm\\t
est\\npm_cache\\_git-remotes\\file-c-Users-kat-Documents-GitHub-npm-test-tap-add-remote-git-file-child-git-58527840'...\
nfatal: 'C:/Users/kat/AppData/Local/GitHub/PortableGit_c2ba306e536fdf878271f7fe636a147ff37326ad/Users/kat/Documents/GitH
ub/npm/test/tap/add-remote-git-file/child.git' does not appear to be a git repository\nfatal: Could not read from remote
 repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n\n    at ChildProcess.e
xithandler (child_process.js:751:12)\n    at ChildProcess.emit (events.js:110:17)\n    at maybeClose (child_process.js:1
015:16)\n    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)"
      message: "Command failed: git -c core.longpaths=true clone --template=C:\\Users\\kat\\Documents\\GitHub\\npm\\test
\\npm_cache\\_git-remotes\\_templates --mirror file://c/Users/kat/Documents/GitHub/npm/test/tap/add-remote-git-file/chil
d.git C:\\Users\\kat\\Documents\\GitHub\\npm\\test\\npm_cache\\_git-remotes\\file-c-Users-kat-Documents-GitHub-npm-test-
tap-add-remote-git-file-child-git-58527840\nCloning into bare repository 'C:\\Users\\kat\\Documents\\GitHub\\npm\\test\\
npm_cache\\_git-remotes\\file-c-Users-kat-Documents-GitHub-npm-test-tap-add-remote-git-file-child-git-58527840'...\nfata
l: 'C:/Users/kat/AppData/Local/GitHub/PortableGit_c2ba306e536fdf878271f7fe636a147ff37326ad/Users/kat/Documents/GitHub/np
m/test/tap/add-remote-git-file/child.git' does not appear to be a git repository\nfatal: Could not read from remote repo
sitory.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n"
      killed: false
      code: 128
      signal: null
      cmd: "git -c core.longpaths=true clone --template=C:\\Users\\kat\\Documents\\GitHub\\npm\\test\\npm_cache\\_git-re
motes\\_templates --mirror file://c/Users/kat/Documents/GitHub/npm/test/tap/add-remote-git-file/child.git C:\\Users\\kat
\\Documents\\GitHub\\npm\\test\\npm_cache\\_git-remotes\\file-c-Users-kat-Documents-GitHub-npm-test-tap-add-remote-git-f
ile-child-git-58527840"
    at:
      file: "test\\tap\\add-remote-git-file.js"
      line: 37
      column: 7
    stack: "test\\tap\\add-remote-git-file.js:37:7\nzalgoSafe (node_modules\\dezalgo\\dezalgo.js:20:10)\nRES (node_modul
es\\inflight\\inflight.js:23:14)\nf (node_modules\\once\\once.js:17:25)\nfinish (lib\\cache\\add-remote-git.js:140:22)\n
lib\\cache\\add-remote-git.js:214:18\nChildProcess.exithandler (child_process.js:758:5)\nmaybeClose (child_process.js:10
15:16)\nProcess.ChildProcess._handle.onexit (child_process.js:1087:5)\n"

  cache from repo
  not ok TypeError: Cannot read property '_resolved' of undefined
    at:
      file: "test\\tap\\add-remote-git-file.js"
      line: 39
      column: 21
    test: cache from repo
    message: "TypeError: Cannot read property '_resolved' of undefined"
    stack: "test\\tap\\add-remote-git-file.js:39:21\nzalgoSafe (node_modules\\dezalgo\\dezalgo.js:20:10)\nRES (node_modu
les\\inflight\\inflight.js:23:14)\nf (node_modules\\once\\once.js:17:25)\nfinish (lib\\cache\\add-remote-git.js:140:22)\
nlib\\cache\\add-remote-git.js:214:18\nChildProcess.exithandler (child_process.js:758:5)\nmaybeClose (child_process.js:1
015:16)\nProcess.ChildProcess._handle.onexit (child_process.js:1087:5)\n"
```

**Comment by jedmao** [comment]
I have the same problem.
