### ISSUE TITLE
Error running "npm update"

### ISSUE THREAD

**Issue by mcintosh101** [npm/npm#8444]
Hi,

I am getting this error when trying to update in my project:

```
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "update"
npm ERR! node v0.12.4
npm ERR! npm  v2.11.0

npm ERR! Invalid version: "0.1"
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

And it says to include the npm-debug.log which looks like this:

```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'update' ]
2 info using npm@2.11.0
3 info using node@v0.12.4
4 verbose node symlink /usr/local/bin/node
5 verbose stack Error: Invalid version: "0.1"
5 verbose stack     at Object.module.exports.fixVersionField (/usr/local/lib/node_modules/npm/node_modules/normalize-package-data/lib/fixer.js:185:13)
5 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/normalize-package-data/lib/normalize.js:32:38
5 verbose stack     at Array.forEach (native)
5 verbose stack     at normalize (/usr/local/lib/node_modules/npm/node_modules/normalize-package-data/lib/normalize.js:31:15)
5 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:338:5)
5 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:113:5)
5 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:284:20
5 verbose stack     at evalmachine.<anonymous>:263:20
5 verbose stack     at OpenReq.Req.done (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:141:5)
5 verbose stack     at OpenReq.done (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:61:22)
6 verbose cwd /Users/alexandermcintosh1/Sites/grmdaily/grmDaily
7 error Darwin 14.1.0
8 error argv "node" "/usr/local/bin/npm" "update"
9 error node v0.12.4
10 error npm  v2.11.0
11 error Invalid version: "0.1"
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]
```

Does anyone know why this is happening?

**Comment by KenanY** [comment]
@mcintosh101 Looks like the `"version"` property in your `package.json` is not valid [SemVer](http://semver.org/), as per the [documentation](https://docs.npmjs.com/files/package.json#version):

> Version must be parseable by [node-semver](https://github.com/isaacs/node-semver)

Perhaps you should change it to `"0.1.0"`?

**Comment by mcintosh101** [comment]
That appears to of fixed it. Thanks for the help @KenanY !
