### ISSUE TITLE
Unable to install Openfin

### ISSUE THREAD

**Issue by rahulljoshii** [npm/npm#8451]
Hello All,
I m trying to follow openfin link https://openfin.co/developers/openfin-runtime-introduction/
to install openfin and i m getting the below error messgaes.We are using a network proxy and even i have tried with npm config set proxy "http://xxxxxxxxxx.com:80".
Below is the error log file  i m running with command script
npm install -g openfin-cli

when an early response is appreciated.

```
0 info it worked if it ends with ok
1 verbose cli [ 'c:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'openfin-cli' ]
2 info using npm@2.10.1
3 info using node@v0.12.4
4 verbose install initial load of C:\Users\ZXXXXXX\AppData\Roaming\npm\package.json
5 verbose readDependencies loading dependencies from C:\Users\ZK3BPI1\AppData\Roaming\npm\package.json
6 silly cache add args [ 'openfin-cli', null ]
7 verbose cache add spec openfin-cli
8 silly cache add parsed spec { raw: 'openfin-cli',
8 silly cache add   scope: null,
8 silly cache add   name: 'openfin-cli',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: '*',
8 silly cache add   type: 'range' }
9 silly addNamed openfin-cli@*
10 verbose addNamed "*" is a valid semver range for openfin-cli
11 silly addNameRange { name: 'openfin-cli', range: '*', hasData: false }
12 silly mapToRegistry name openfin-cli
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry http://registry.npmjs.org/
15 silly mapToRegistry uri http://registry.npmjs.org/openfin-cli
16 verbose addNameRange registry:http://registry.npmjs.org/openfin-cli not in flight; fetching
17 verbose request uri http://registry.npmjs.org/openfin-cli
18 verbose request no auth needed
19 info attempt registry request try #1 at 5:26:13 PM
20 verbose request id 8337d6bf04562e4e
21 http request GET http://registry.npmjs.org/openfin-cli
22 info retry will retry, error on last attempt: Error: connect ETIMEDOUT
23 info attempt registry request try #2 at 5:26:44 PM
24 http request GET http://registry.npmjs.org/openfin-cli
25 info retry will retry, error on last attempt: Error: connect ETIMEDOUT
26 info attempt registry request try #3 at 5:28:05 PM
27 http request GET http://registry.npmjs.org/openfin-cli
28 verbose stack Error: connect ETIMEDOUT
28 verbose stack     at exports._errnoException (util.js:746:11)
28 verbose stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)
29 verbose cwd C:\Working\Openfin
30 error Windows_NT 6.1.7601
31 error argv "c:\\Program Files\\nodejs\\\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "openfin-cli"
32 error node v0.12.4
33 error npm  v2.10.1
34 error code ETIMEDOUT
35 error errno ETIMEDOUT
36 error syscall connect
37 error network connect ETIMEDOUT
37 error network This is most likely not a problem with npm itself
37 error network and is related to network connectivity.
37 error network In most cases you are behind a proxy or have bad network settings.
37 error network
37 error network If you are behind a proxy, please make sure that the
37 error network 'proxy' config is set properly.  See: 'npm help config'
38 verbose exit [ 1, true ]
```

**Comment by busches** [comment]
Given the error, it's not hitting the registry, so either the registry was down or your proxy was configured incorrectly. Were you able to resolve this issue or are you still having troubles?
