### ISSUE TITLE
npm install sails-mongo --save Windows 8.1

### ISSUE THREAD

**Issue by nmarsh92** [npm/npm#8454]
```
'MySQL' is not recognized as an internal or external command,
operable program or batch file.
'MySQL' is not recognized as an internal or external command,
operable program or batch file.
Your environment has been set up for using Node.js 0.12.4 (x64) and npm.

C:\Windows\System32>cd "c:\users\nathan\sailsProjects"

c:\Users\Nathan\sailsProjects>cd activityOverlord

c:\Users\Nathan\sailsProjects\activityOverlord>npm install sails-mongo --save
sails-mongo@0.11.2 node_modules\sails-mongo
├── waterline-errors@0.10.1
├── async@0.8.0
├── waterline-cursor@0.0.5 (async@0.9.2)
└── lodash@2.4.2

c:\Users\Nathan\sailsProjects\activityOverlord>mongod
'mongod' is not recognized as an internal or external command,
operable program or batch file.

c:\Users\Nathan\sailsProjects\activityOverlord>npm install sails-mongo --save
sails-mongo@0.11.2 node_modules\sails-mongo
├── waterline-errors@0.10.1
├── async@0.8.0
├── waterline-cursor@0.0.5 (async@0.9.2)
└── lodash@2.4.2

c:\Users\Nathan\sailsProjects\activityOverlord>cd node_modules

c:\Users\Nathan\sailsProjects\activityOverlord\node_modules>mongod
'mongod' is not recognized as an internal or external command,
operable program or batch file.

c:\Users\Nathan\sailsProjects\activityOverlord\node_modules>cd mongodb

c:\Users\Nathan\sailsProjects\activityOverlord\node_modules\mongodb>mongod
'mongod' is not recognized as an internal or external command,
operable program or batch file.

c:\Users\Nathan\sailsProjects\activityOverlord\node_modules\mongodb>cd ..

c:\Users\Nathan\sailsProjects\activityOverlord\node_modules>cd sails-disk

c:\Users\Nathan\sailsProjects\activityOverlord\node_modules\sails-disk>cd ..

c:\Users\Nathan\sailsProjects\activityOverlord\node_modules>cd sails-mongo

c:\Users\Nathan\sailsProjects\activityOverlord\node_modules\sails-mongo>mongod
'mongod' is not recognized as an internal or external command,
operable program or batch file.

c:\Users\Nathan\sailsProjects\activityOverlord\node_modules\sails-mongo>cd ..

c:\Users\Nathan\sailsProjects\activityOverlord\node_modules>cd ..

c:\Users\Nathan\sailsProjects\activityOverlord>npm rebuild sails-mongo
sails-mongo@0.11.2 c:\Users\Nathan\sailsProjects\activityOverlord\node_modules\s
ails-mongo

c:\Users\Nathan\sailsProjects\activityOverlord>mongod
'mongod' is not recognized as an internal or external command,
operable program or batch file.

c:\Users\Nathan\sailsProjects\activityOverlord>sails lift

info: Starting app...

{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }

js-bson: Failed to load c++ bson extension, using pure JS version
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }

js-bson: Failed to load c++ bson extension, using pure JS version
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }

js-bson: Failed to load c++ bson extension, using pure JS version
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }

js-bson: Failed to load c++ bson extension, using pure JS version

 Excuse my interruption, but it looks like this app
 does not have a project-wide "migrate" setting configured yet.
 (perhaps this is the first time you're lifting it with models?)

 In short, this setting controls whether/how Sails will attempt to automatically

 rebuild the tables/collections/sets/etc. in your database schema.
 You can read more about the "migrate" setting here:
 http://sailsjs.org/#/documentation/concepts/ORM/model-settings.html?q=migrate

 In a production environment (NODE_ENV==="production") Sails always uses
 migrate:"safe" to protect inadvertent deletion of your data.
 However during development, you have a few other options for convenience:

 1. safe  - never auto-migrate my database(s). I will do it myself (by hand)
 2. alter - auto-migrate, but attempt to keep my existing data (experimental)
 3. drop  - wipe/drop ALL my data and rebuild models every time I lift Sails

What would you like Sails to do?

info: To skip this prompt in the future, set `sails.config.models.migrate`.
info: (conventionally, this is done in `config/models.js`)

warn: ** DO NOT CHOOSE "2" or "3" IF YOU ARE WORKING WITH PRODUCTION DATA **

prompt: ?:  2

 Temporarily using `sails.config.models.migrate="alter"...
 (press CTRL+C to cancel-- continuing lift automatically in 0.5 seconds...)

error: A hook (`orm`) failed to load!
error: Error: Failed to connect to MongoDB.  Are you sure your configured Mongo
instance is running?
 Error details:
{ [MongoError: connect ECONNREFUSED] name: 'MongoError', message: 'connect ECONN
REFUSED' }
    at _createError (c:\Users\Nathan\sailsProjects\activityOverlord\node_modules
\sails-mongo\lib\adapter.js:102:23)
    at c:\Users\Nathan\sailsProjects\activityOverlord\node_modules\sails-mongo\l
ib\adapter.js:105:13
    at c:\Users\Nathan\sailsProjects\activityOverlord\node_modules\sails-mongo\l
ib\connection.js:25:20
    at c:\Users\Nathan\sailsProjects\activityOverlord\node_modules\mongodb\lib\m
ongo_client.js:236:20
    at c:\Users\Nathan\sailsProjects\activityOverlord\node_modules\mongodb\lib\d
b.js:203:14
    at null.<anonymous> (c:\Users\Nathan\sailsProjects\activityOverlord\node_mod
ules\mongodb\lib\server.js:226:9)
    at g (events.js:199:16)
    at emit (events.js:110:17)
    at null.<anonymous> (c:\Users\Nathan\sailsProjects\activityOverlord\node_mod
ules\mongodb\node_modules\mongodb-core\lib\topologies\server.js:255:68)
    at g (events.js:199:16)
    at emit (events.js:110:17)
    at null.<anonymous> (c:\Users\Nathan\sailsProjects\activityOverlord\node_mod
ules\mongodb\node_modules\mongodb-core\lib\connection\pool.js:77:12)
    at g (events.js:199:16)
    at emit (events.js:110:17)
    at Socket.<anonymous> (c:\Users\Nathan\sailsProjects\activityOverlord\node_m
odules\mongodb\node_modules\mongodb-core\lib\connection\connection.js:118:49)
    at Socket.g (events.js:199:16)

c:\Users\Nathan\sailsProjects\activityOverlord>npm rebuild sails-mongo
sails-mongo@0.11.2 c:\Users\Nathan\sailsProjects\activityOverlord\node_modules\s
ails-mongo

c:\Users\Nathan\sailsProjects\activityOverlord>npm install sails-mongo --save
sails-mongo@0.11.2 node_modules\sails-mongo
├── waterline-errors@0.10.1
├── async@0.8.0
├── waterline-cursor@0.0.5 (async@0.9.2)
└── lodash@2.4.2

c:\Users\Nathan\sailsProjects\activityOverlord>
```

I was getting a ton of errors when I was trying to install sails-mongo but when I restarted my node command prompt for the third or so time to clear it to post the error here it stopped popping up, but when I try to run "mongod" it doesn't recognize it, and when I try to start sails using sails-mongo it fails.

**Comment by nmarsh92** [comment]
Maybe I misunderstood, I'm noobish at Windows development, sails, and mongodb so sorry.

I managed to get a connection from sails to mongodb on a separate computer today. I installed mongodb from the mongodb website with the msi file and created a data path manually for it since I didn't see a Windows package manager.

When I set a empty sails project to use mongodb the mongodb terminal appears to have gained a connection when i started it. But it is a blank project, will have to wait til after work when I get home to test with my application that would actually make use of the db
