### ISSUE TITLE
npm ERR! Invalid protocol: null

### ISSUE THREAD

**Issue by sabarinathancs** [npm/npm#8456]
```
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova" "ionic"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1

npm ERR! Invalid protocol: null
npm ERR!
```

**Comment by sabarinathancs** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'cordova',
1 verbose cli   'ionic' ]
2 info using npm@2.10.1
3 info using node@v0.12.4
4 verbose install initial load of C:\Users\user\AppData\Roaming\npm\package.json
5 verbose readDependencies loading dependencies from C:\Users\user\AppData\Roaming\npm\package.json
6 silly cache add args [ 'cordova', null ]
7 verbose cache add spec cordova
8 silly cache add args [ 'ionic', null ]
9 verbose cache add spec ionic
10 silly cache add parsed spec { raw: 'cordova',
10 silly cache add   scope: null,
10 silly cache add   name: 'cordova',
10 silly cache add   rawSpec: '',
10 silly cache add   spec: '*',
10 silly cache add   type: 'range' }
11 silly addNamed cordova@*
12 verbose addNamed "*" is a valid semver range for cordova
13 silly addNameRange { name: 'cordova', range: '*', hasData: false }
14 silly mapToRegistry name cordova
15 silly mapToRegistry using default registry
16 silly mapToRegistry registry http://registry.npmjs.org/
17 silly mapToRegistry uri http://registry.npmjs.org/cordova
18 verbose addNameRange registry:http://registry.npmjs.org/cordova not in flight; fetching
19 silly cache add parsed spec { raw: 'ionic',
19 silly cache add   scope: null,
19 silly cache add   name: 'ionic',
19 silly cache add   rawSpec: '',
19 silly cache add   spec: '*',
19 silly cache add   type: 'range' }
20 silly addNamed ionic@*
21 verbose addNamed "*" is a valid semver range for ionic
22 silly addNameRange { name: 'ionic', range: '*', hasData: false }
23 silly mapToRegistry name ionic
24 silly mapToRegistry using default registry
25 silly mapToRegistry registry http://registry.npmjs.org/
26 silly mapToRegistry uri http://registry.npmjs.org/ionic
27 verbose addNameRange registry:http://registry.npmjs.org/ionic not in flight; fetching
28 verbose request uri http://registry.npmjs.org/cordova
29 verbose request no auth needed
30 info attempt registry request try #1 at 11:00:54 AM
31 verbose request id 56d60d4250f39551
32 http request GET http://registry.npmjs.org/cordova
33 info retry will retry, error on last attempt: Error: Invalid protocol: null
34 verbose request uri http://registry.npmjs.org/ionic
35 verbose request no auth needed
36 info attempt registry request try #1 at 11:00:54 AM
37 http request GET http://registry.npmjs.org/ionic
38 info retry will retry, error on last attempt: Error: Invalid protocol: null
39 info attempt registry request try #2 at 11:01:04 AM
40 http request GET http://registry.npmjs.org/cordova
41 info retry will retry, error on last attempt: Error: Invalid protocol: null
42 info attempt registry request try #2 at 11:01:04 AM
43 http request GET http://registry.npmjs.org/ionic
44 info retry will retry, error on last attempt: Error: Invalid protocol: null
45 info attempt registry request try #3 at 11:02:04 AM
46 http request GET http://registry.npmjs.org/cordova
47 info attempt registry request try #3 at 11:02:04 AM
48 http request GET http://registry.npmjs.org/ionic
49 verbose stack Error: Invalid protocol: null
49 verbose stack     at Request.init (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:640:31)
49 verbose stack     at new Request (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:272:8)
49 verbose stack     at request (C:\Program Files\nodejs\node_modules\npm\node_modules\request\index.js:56:10)
49 verbose stack     at CachingRegistryClient.makeRequest (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:147:13)
49 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:65:17
49 verbose stack     at RetryOperation._fn (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\attempt.js:18:5)
49 verbose stack     at null._onTimeout (C:\Program Files\nodejs\node_modules\npm\node_modules\retry\lib\retry_operation.js:32:10)
49 verbose stack     at Timer.listOnTimeout (timers.js:110:15)
50 verbose cwd C:\Users\user
51 error Windows_NT 6.1.7601
52 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova" "ionic"
53 error node v0.12.4
54 error npm  v2.10.1
55 error Invalid protocol: null
56 error If you need help, you may report this error at:
56 error     <https://github.com/npm/npm/issues>
57 verbose exit [ 1, true ]
