### ISSUE TITLE
Issues with Mongoose cannot find module code:MODULE_NOT_FOUND

### ISSUE THREAD

**Issue by genelim** [npm/npm#8473]
Trying to do as many has suggested the steps to solve this problem from Stackoverflow and Github. None of them are working. I am receiving the below as my error. I am not sure what have I done wrong or missed.

```
25799 verbose write writing to c:\Users\Gene\mm\awesome-test\node_modules\mongoose\node_modules\mongodb\node_modules\mongodb-core\node_modules\jsdoc\node_modules\esprima\package.json
25800 info preinstall esprima@1.1.0-dev-harmony
25801 verbose readDependencies loading dependencies from c:\Users\Gene\mm\awesome-test\node_modules\mongoose\node_modules\mongodb\node_modules\mongodb-core\node_modules\jsdoc\node_modules\esprima\package.json
25802 verbose readDependencies loading dependencies from c:\Users\Gene\mm\awesome-test\node_modules\mongoose\node_modules\mongodb\node_modules\mongodb-core\node_modules\jsdoc\node_modules\esprima\package.json
25803 silly install resolved []
25804 verbose about to build c:\Users\Gene\mm\awesome-test\node_modules\mongoose\node_modules\mongodb\node_modules\mongodb-core\node_modules\jsdoc\node_modules\esprima
25805 info build c:\Users\Gene\mm\awesome-test\node_modules\mongoose\node_modules\mongodb\node_modules\mongodb-core\node_modules\jsdoc\node_modules\esprima
25806 info linkStuff esprima@1.1.0-dev-harmony
25807 silly linkStuff esprima@1.1.0-dev-harmony has c:\Users\Gene\mm\awesome-test\node_modules\mongoose\node_modules\mongodb\node_modules\mongodb-core\node_modules\jsdoc\node_modules as its parent node_modules
25808 verbose linkBins esprima@1.1.0-dev-harmony
25809 verbose link bins [ { esparse: './bin/esparse.js',
25809 verbose link bins     esvalidate: './bin/esvalidate.js' },
25809 verbose link bins   'c:\\Users\\Gene\\mm\\awesome-test\\node_modules\\mongoose\\node_modules\\mongodb\\node_modules\\mongodb-core\\node_modules\\jsdoc\\node_modules\\.bin',
25809 verbose link bins   false ]
25810 verbose linkMans esprima@1.1.0-dev-harmony
25811 verbose rebuildBundles esprima@1.1.0-dev-harmony
25812 info install esprima@1.1.0-dev-harmony
25813 info postinstall esprima@1.1.0-dev-harmony
25814 verbose unlock done using C:\Users\Gene\AppData\Roaming\npm-cache\_locks\esprima-181301ee0ed062a1.lock for c:\Users\Gene\mm\awesome-test\node_modules\mongoose\node_modules\mongodb\node_modules\mongodb-core\node_modules\jsdoc\node_modules\esprima
25815 verbose stack Error: read ECONNRESET
25815 verbose stack     at exports._errnoException (util.js:746:11)
25815 verbose stack     at TCP.onread (net.js:559:26)
25816 verbose cwd c:\Users\Gene\mm\awesome-test\node_modules\mongoose\node_modules\mongodb\node_modules\mongodb-core\node_modules
25817 error Windows_NT 6.3.9600
25818 error argv "c:\\Program Files (x86)\\nodejs\\node.exe" "c:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
25819 error node v0.12.4
25820 error npm  v2.10.1
25821 error code ECONNRESET
25822 error errno ECONNRESET
25823 error syscall read
25824 error network read ECONNRESET
25824 error network This is most likely not a problem with npm itself
25824 error network and is related to network connectivity.
25824 error network In most cases you are behind a proxy or have bad network settings.
25824 error network
25824 error network If you are behind a proxy, please make sure that the
25824 error network 'proxy' config is set properly.  See: 'npm help config'
25825 verbose exit [ 1, true ]
```

Thanks

**Comment by KenanY** [comment]
@genelim Looks like an internet connection issue. Are you behind a proxy or firewall by any chance?

**Comment by genelim** [comment]
@KenanY Hi, sorry for the late reply. Actually I am running it locally on localhost. Meaning, I will not be needed the internet right? If ever, I did connect to my home or work network, it is still giving me the same error.

**Comment by S-ed** [comment]
@genelim Have You changed a npm repo to a proper one?
As example:
```npm config set registry http://registry.npmjs.org/```
Mind protocol: HTTP or HTTPS (if You are using ssl auth)
