### ISSUE TITLE
unable to install npm on mac machine

### ISSUE THREAD

**Issue by vermasagar49** [npm/npm#8487]
```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'install', '-g', 'slot-cli' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 silly cache add args [ 'slot-cli', null ]
5 verbose cache add spec slot-cli
6 silly cache add parsed spec { raw: 'slot-cli',
6 silly cache add   scope: null,
6 silly cache add   name: 'slot-cli',
6 silly cache add   rawSpec: '',
6 silly cache add   spec: '*',
6 silly cache add   type: 'range' }
7 verbose addNamed slot-cli@*
8 silly addNamed semver.valid null
9 silly addNamed semver.validRange *
10 silly addNameRange { name: 'slot-cli', range: '*', hasData: false }
11 silly mapToRegistry name slot-cli
12 silly mapToRegistry using default registry
13 silly mapToRegistry registry https://registry.npmjs.org/
14 silly mapToRegistry uri https://registry.npmjs.org/slot-cli
15 verbose addNameRange registry:https://registry.npmjs.org/slot-cli not in flight; fetching
16 verbose request uri https://registry.npmjs.org/slot-cli
17 verbose request no auth needed
18 info attempt registry request try #1 at 5:13:10 PM
19 verbose request id 2fb1f63b8c2f3102
20 verbose etag "1DZNU92COYQDWQI7RZV5MZJR1"
21 http request GET https://registry.npmjs.org/slot-cli
22 http 304 https://registry.npmjs.org/slot-cli
23 silly get cb [ 304,
23 silly get   { date: 'Sun, 07 Jun 2015 11:41:30 GMT',
23 silly get     via: '1.1 varnish',
23 silly get     'cache-control': 'max-age=60',
23 silly get     etag: '"1DZNU92COYQDWQI7RZV5MZJR1"',
23 silly get     age: '0',
23 silly get     connection: 'keep-alive',
23 silly get     'x-served-by': 'cache-sin6920-SIN',
23 silly get     'x-cache': 'MISS',
23 silly get     'x-cache-hits': '0',
23 silly get     'x-timer': 'S1433677290.271610,VS0,VE1006',
23 silly get     vary: 'Accept' } ]
24 verbose etag https://registry.npmjs.org/slot-cli from cache
25 verbose get saving slot-cli to /Users/sagarverma/.npm/registry.npmjs.org/slot-cli/.cache.json
26 silly addNameRange number 2 { name: 'slot-cli', range: '*', hasData: true }
27 silly addNameRange versions [ 'slot-cli',
27 silly addNameRange   [ '0.0.6',
27 silly addNameRange     '0.0.7',
27 silly addNameRange     '0.0.8',
27 silly addNameRange     '0.0.9',
27 silly addNameRange     '0.0.10',
27 silly addNameRange     '0.0.11',
27 silly addNameRange     '0.0.12',
27 silly addNameRange     '0.0.15',
27 silly addNameRange     '0.0.15-alpha.1',
27 silly addNameRange     '0.0.15-alpha.2',
27 silly addNameRange     '0.0.15-alpha.3',
27 silly addNameRange     '0.0.16-alpha.0',
27 silly addNameRange     '0.0.16-alpha.1',
27 silly addNameRange     '0.0.16-alpha.2',
27 silly addNameRange     '0.0.16-alpha.3',
27 silly addNameRange     '0.0.16-alpha.4',
27 silly addNameRange     '0.0.16-alpha.5',
27 silly addNameRange     '0.0.16-alpha.6',
27 silly addNameRange     '0.0.16-alpha.7',
27 silly addNameRange     '0.0.16-alpha.8',
27 silly addNameRange     '0.0.16-alpha.9',
27 silly addNameRange     '0.0.16',
27 silly addNameRange     '0.0.17-alpha.1',
27 silly addNameRange     '0.0.17-alpha.2' ] ]
28 verbose addNamed slot-cli@0.0.16
29 silly addNamed semver.valid 0.0.16
30 silly addNamed semver.validRange 0.0.16
31 silly cache afterAdd slot-cli@0.0.16
32 verbose afterAdd /Users/sagarverma/.npm/slot-cli/0.0.16/package/package.json not in flight; writing
33 verbose afterAdd /Users/sagarverma/.npm/slot-cli/0.0.16/package/package.json written
34 silly install resolved [ { name: 'slot-cli',
34 silly install resolved     version: '0.0.16',
34 silly install resolved     description: 'Command line, a friendly tool for easy handle Slot Framework projects (manage projects, fragments and REST services)',
34 silly install resolved     keywords:
34 silly install resolved      [ 'framework',
34 silly install resolved        'web',
34 silly install resolved        'development',
34 silly install resolved        'slot',
34 silly install resolved        'fragment',
34 silly install resolved        'bootstrap',
34 silly install resolved        'zurb',
34 silly install resolved        'jquery',
34 silly install resolved        'html',
34 silly install resolved        'html5',
34 silly install resolved        'css' ],
34 silly install resolved     author:
34 silly install resolved      { name: 'Carlos Echeverría',
34 silly install resolved        email: 'SlotFramework@gmail.com',
34 silly install resolved        url: 'https://github.com/cecheverria' },
34 silly install resolved     contributors: [],
34 silly install resolved     licenses: [ [Object] ],
34 silly install resolved     repository: { type: 'git', url: 'https://github.com/SlotTeam/slot-cli.git' },
34 silly install resolved     dependencies:
34 silly install resolved      { async: '^0.9.0',
34 silly install resolved        colors: '^0.6.2',
34 silly install resolved        commander: '>=1.0.0',
34 silly install resolved        mkdirp: '0.3.5',
34 silly install resolved        'slot-framework': '>= 0.0.16-alpha',
34 silly install resolved        'sort-object': '^0.3.2',
34 silly install resolved        string: '^2.0.0' },
34 silly install resolved     engines: { node: '>= 0.10.0' },
34 silly install resolved     main: 'index',
34 silly install resolved     homepage: 'http://www.slotframework.org/',
34 silly install resolved     bin: { slot: 'bin/slot-cli.js' },
34 silly install resolved     gitHead: 'c157d8bc4044c4151aa406315faa0330ba476493',
34 silly install resolved     bugs: { url: 'https://github.com/SlotTeam/slot-cli/issues' },
34 silly install resolved     _id: 'slot-cli@0.0.16',
34 silly install resolved     scripts: {},
34 silly install resolved     _shasum: 'ad51b2d7118bdec72e69648f6e76145aab0c2fc9',
34 silly install resolved     _from: 'slot-cli@*',
34 silly install resolved     _npmVersion: '2.5.1',
34 silly install resolved     _nodeVersion: '0.12.0',
34 silly install resolved     _npmUser: { name: 'cecheverria', email: 'carlosechev07@gmail.com' },
34 silly install resolved     maintainers: [ [Object] ],
34 silly install resolved     dist:
34 silly install resolved      { shasum: 'ad51b2d7118bdec72e69648f6e76145aab0c2fc9',
34 silly install resolved        tarball: 'http://registry.npmjs.org/slot-cli/-/slot-cli-0.0.16.tgz' },
34 silly install resolved     directories: {},
34 silly install resolved     _resolved: 'https://registry.npmjs.org/slot-cli/-/slot-cli-0.0.16.tgz',
34 silly install resolved     readme: 'ERROR: No README data found!' } ]
35 info install slot-cli@0.0.16 into /usr/local/lib
36 info installOne slot-cli@0.0.16
37 verbose installOne of slot-cli to /usr/local/lib not in flight; installing
38 warn locking Error: EACCES, open '/Users/sagarverma/.npm/_locks/slot-cli-bee2fac0a28b6721.lock'
38 warn locking     at Error (native)
38 warn locking  /Users/sagarverma/.npm/_locks/slot-cli-bee2fac0a28b6721.lock failed { [Error: EACCES, open '/Users/sagarverma/.npm/_locks/slot-cli-bee2fac0a28b6721.lock']
38 warn locking   errno: -13,
38 warn locking   code: 'EACCES',
38 warn locking   path: '/Users/sagarverma/.npm/_locks/slot-cli-bee2fac0a28b6721.lock' }
39 verbose stack Error: Attempt to unlock /usr/local/lib/node_modules/slot-cli, which hasn't been locked
39 verbose stack     at unlock (/usr/local/lib/node_modules/npm/lib/utils/locker.js:66:11)
39 verbose stack     at cb (/usr/local/lib/node_modules/npm/lib/install.js:929:5)
39 verbose stack     at /usr/local/lib/node_modules/npm/lib/install.js:933:20
39 verbose stack     at /usr/local/lib/node_modules/npm/lib/utils/locker.js:40:9
39 verbose stack     at cb (/usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:149:38)
39 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:177:38
39 verbose stack     at FSReqWrap.oncomplete (fs.js:99:15)
40 verbose cwd /Volumes/MOBILE CODE/MobileSamples/Our Product/slot
41 error Darwin 14.3.0
42 error argv "node" "/usr/local/bin/npm" "install" "-g" "slot-cli"
43 error node v0.12.0
44 error npm  v2.5.1
45 error Attempt to unlock /usr/local/lib/node_modules/slot-cli, which hasn't been locked
46 error If you need help, you may report this error at:
46 error     <http://github.com/npm/npm/issues>
47 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
@vermasagar49 Looks like you do not have the privileges necessary to read/write to `npm`'s cache directory. Maybe try `chown`ing that directory?:

``` sh
$ sudo chown -R $(whoami) "$HOME/.npm"
```

**Comment by smikes** [comment]
Is this still a problem for you?

This looks like a stale lockfile is blocking your installation.  Often this can be solved by cleaning up the lock directory permissions, and then running the install with `sudo` --

```
$ sudo chown -R $(whoami) ~/.npm
$ sudo npm install -g slot-cli
```

There have been a lot of improvements to npm -- especially involving git dependencies -- since 2.5. Can you try updating your npm installation?

There is a bad interaction between two known bugs — one in `node@>0.11` and `iojs` and the other in `npm@<2.8.2`.  This can cause ECONNRESET and ETIMEDOUT errors.  The full writeup is here: https://github.com/npm/npm/issues/7699  You can fix this problem by updating your `npm` to the latest (see below).

To update npm, run `sudo npm -g install npm@latest`.

Thanks!

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
