### ISSUE TITLE
git failure on npm install

### ISSUE THREAD

**Issue by rkevin99** [npm/npm#8494]
1) I ran the following command :  git clone https://github.com/basti1302/storra.git 
2) I then ran "npm install"
3) I get the foll. error:
```
E:\Kevin\RubyTutorial\audiobook-collection-manager-acceptance\features\storra>npm install
npm WARN package.json storra@0.0.1 No license field.
npm WARN package.json storra@0.0.1 Non-dependency in bundleDependencies: step
npm WARN package.json Dependency 'step' exists in both dependencies and devDependencies, using 'step@*' from dependencies
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:751:12)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:110:17)
npm WARN addRemoteGit     at maybeClose (child_process.js:1015:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
npm WARN addRemoteGit  git://github.com/magicmoose/grunt-jasmine-node.git resetting remote C:\Users\Rodrigues\AppData\Roaming\npm-cache\_git-remotes\git-github-com-magicmoose-grunt-jasmine-node-git-ec3e1bd7 because of error: { [Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit ]
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
npm ERR! git clone --template=C:\Users\Rodrigues\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/magicmoose/grunt-jasmine-node.git C:\Users\Rodrigues\AppData\Roaming\npm-cache\_git-remotes\git-github-com-magicmoose-grunt-jasmine-node-git-ec3e1bd7: Cloning into bare repository 'C:\Users\Rodrigues\AppData\Roaming\npm-cache\_git-remotes\git-github-com-magicmoose-grunt-jasmine-node-git-ec3e1bd7'...
npm ERR! git clone --template=C:\Users\Rodrigues\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/magicmoose/grunt-jasmine-node.git C:\Users\Rodrigues\AppData\Roaming\npm-cache\_git-remotes\git-github-com-magicmoose-grunt-jasmine-node-git-ec3e1bd7: fatal: unable to connect to github.com:
npm ERR! git clone --template=C:\Users\Rodrigues\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/magicmoose/grunt-jasmine-node.git C:\Users\Rodrigues\AppData\Roaming\npm-cache\_git-remotes\git-github-com-magicmoose-grunt-jasmine-node-git-ec3e1bd7: github.com[0: 192.30.252.128]: errno=No error
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "e:\\Tools\\NodeJS\\\\node.exe" "e:\\Tools\\NodeJS\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\Rodrigues\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/magicmoose/grunt-jasmine-node.git C:\Users\Rodrigues\AppData\Roaming\npm-cache\_git-remotes\git-github-com-magicmoose-grunt-jasmine-node-git-ec3e1bd7
npm ERR! Cloning into bare repository 'C:\Users\Rodrigues\AppData\Roaming\npm-cache\_git-remotes\git-github-com-magicmoose-grunt-jasmine-node-git-ec3e1bd7'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.252.128]: errno=No error
npm ERR!
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     E:\Kevin\RubyTutorial\audiobook-collection-manager-acceptance\features\storra\npm-debug.log
```

**Comment by smikes** [comment]
Thanks for reporting this.

This looks like a fun one, with "errno = No error" and "unable to connect to github.com".

Do you use a proxy to connect to the internet?  It may be that `npm` needs to be told about your proxy..

Can you try installing a module from the registry, just to see if the problem is with general network transfers or with `git` and `github.com` specifically: 

```
> npm install -g tap
```

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.

**Comment by ericjohnsonaz** [comment]
We are having this issue with npm 2.11.3 when doing a npm update or install.  We have this same error message.  We are behind a proxy and have all of our config files set with our proxy info and all packages seem to update from github correctly with the exception of Gulp 4.0 (Gulp 3.9 works fine).  The error is thrown on retrieving gulp-cli with a fatal "unable to connect to github.com".

**Comment by PBartrina** [comment]
I am having the very same problem. 
Installing a module from the registry works just fine, though:
 '> npm install -g tap' 

npm version 2.14.4
nodejs verison 4.1.1

**Comment by lukepuplett** [comment]
Also having this issue. I have to run npm via a proxy server on my local PC (cntlm) which routes to the corp proxy since I cannot get npm to work directly (auth).

This works except when it comes to sheerun which bombs trying to clone the repo.

The problem as I see it is that the sheerun Git command being ran during `npm install` is using SSH (port 22) instead of HTTP to clone from Github, which seems wrong.

**Comment by s-a** [comment]
Same error here if I try to install via build script on Windows TFS 2015 CI build
@ericjohnsonaz Do we have further infos about this error? 

```
******************************************************************************
Wird gestartet: Build
******************************************************************************
Die folgende Befehlszeile wird ausgeführt:
C:\Program Files\Microsoft Team Foundation Server 14.0\Build\agent\worker\vsoWorker.exe  /name:Worker-3250ff71-2fc8-4acd-a11d-c22ee932a248 /id:3250ff71-2fc8-4acd-a11d-c22ee932a248 /rootFolder:"C:\Program Files\Microsoft Team Foundation Server 14.0\Build" /logger:Forwarding,1.0.0;Verbosity=Verbose,Name=Agent1-6ee23b77bd64620ea1aa854abdc98797;JobId=3250ff71-2fc8-4acd-a11d-c22ee932a248
******************************************************************************
Wird gestartet: Quellen abrufen
******************************************************************************
Syncing repository: node-gicc-server (Git)
522b13518f0030f9b76557147ec8bdf1d0283178 bis C:\TfsData\Build\_work\715ac733\node-gicc-server wird ausgecheckt
Checked out branch refs/heads/master for repository node-gicc-server at commit 522b13518f0030f9b76557147ec8bdf1d0283178
******************************************************************************
Aktive Aufgaben
******************************************************************************
******************************************************************************
Aufgabe wird gestartet: npm install
******************************************************************************
Das PowerShell-Skript wird ausgeführt: C:\Program Files\Microsoft Team Foundation Server 14.0\Build\tasks\NpmInstall\0.1.2\NpmInstall.ps1
C:\Program Files\nodejs\npm.cmd  install
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit at ChildProcess.exithandler (child_process.js:207:12)
npm WARN addRemoteGit at emitTwo (events.js:106:13)
npm WARN addRemoteGit at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit at maybeClose (internal/child_process.js:852:16)
npm WARN addRemoteGit at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
npm WARN addRemoteGit git+http://sit-tfs:8080/tfs/DefaultCollection/_git/node-gicc resetting remote C:\Windows\ServiceProfiles\NetworkService\AppData\Roaming\npm-cache\_git-remotes\git-http-sit-tfs-8080-tfs-DefaultCollection-git-node-gicc-7b16dace because of error: { Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit at ChildProcess.exithandler (child_process.js:207:12)
npm WARN addRemoteGit at emitTwo (events.js:106:13)
npm WARN addRemoteGit at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit at maybeClose (internal/child_process.js:852:16)
npm WARN addRemoteGit at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
npm WARN addRemoteGit killed: false,
npm WARN addRemoteGit code: 1,
npm WARN addRemoteGit signal: null,
npm WARN addRemoteGit cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
```

**Comment by CyberNano** [comment]
I'm having this issue. I did a clean install and got this: 
git error command failed git-c core.longpaths=true config --get remote.origin.url

I tried running this:

npm install blockapps-bloc

**Comment by c0dr** [comment]
Had the same issue when installing packages that referenced other dependencies by 'github:xyz/z'

Running
>git -c core.longpaths=true config --get remote.origin.url

before the npm install solved it for me.

**Comment by akhileshcoer** [comment]
Just now run into same issue.
Tried running this command still issues.
> git -c core.longpaths=true config --get remote.origin.url

I'm simply doing 
> npm install --save-dev karma-jasmine-jquery
[Uploading log.txt…]()

**Comment by gautu15** [comment]
@akhileshcoer  Is there a solution to this? I am seeing this issue with npm 3.10.10 and node v8.9.4
