### ISSUE TITLE
Parse Error windows 7 behind proxy

### ISSUE THREAD

**Issue by asencio** [npm/npm#8496]
Hi I am trying to use npm on a windows machine behind a corporate proxy. It did work before but for some reason I can't go through the proxy anymore. Anyway, my colleagues can, with the same configuration.

Thanks for your help.

Here is my npm-debug.log:
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'grunt-cli' ]
2 info using npm@1.2.15
3 info using node@v0.10.1
4 verbose node symlink C:\Program Files (x86)\nodejs\\node.exe
5 verbose read json C:\Users\w19244\AppData\Roaming\npm\package.json
6 verbose read json C:\Users\w19244\AppData\Roaming\npm\package.json
7 verbose cache add [ 'grunt-cli', null ]
8 verbose cache add name=undefined spec="grunt-cli" args=["grunt-cli",null]
9 verbose parsed url { protocol: null,
9 verbose parsed url   slashes: null,
9 verbose parsed url   auth: null,
9 verbose parsed url   host: null,
9 verbose parsed url   port: null,
9 verbose parsed url   hostname: null,
9 verbose parsed url   hash: null,
9 verbose parsed url   search: null,
9 verbose parsed url   query: null,
9 verbose parsed url   pathname: 'grunt-cli',
9 verbose parsed url   path: 'grunt-cli',
9 verbose parsed url   href: 'grunt-cli' }
10 silly lockFile 671ef8ac-grunt-cli grunt-cli
11 verbose lock grunt-cli C:\Users\w19244\AppData\Roaming\npm-cache\671ef8ac-grunt-cli.lock
12 silly lockFile 671ef8ac-grunt-cli grunt-cli
13 silly lockFile 671ef8ac-grunt-cli grunt-cli
14 verbose addNamed [ 'grunt-cli', '' ]
15 verbose addNamed [ null, '' ]
16 silly lockFile d63f3d0b-grunt-cli grunt-cli@
17 verbose lock grunt-cli@ C:\Users\w19244\AppData\Roaming\npm-cache\d63f3d0b-grunt-cli.lock
18 silly addNameRange { name: 'grunt-cli', range: '', hasData: false }
19 verbose url raw grunt-cli
20 verbose url resolving [ 'https://registry.npmjs.org/', './grunt-cli' ]
21 verbose url resolved https://registry.npmjs.org/grunt-cli
22 info trying registry request attempt 1 at 12:47:28
23 http GET https://registry.npmjs.org/grunt-cli
24 info retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=Parse Error
25 info trying registry request attempt 2 at 12:47:38
26 http GET https://registry.npmjs.org/grunt-cli
27 info retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=Parse Error
28 info trying registry request attempt 3 at 12:48:38
29 http GET https://registry.npmjs.org/grunt-cli
30 silly lockFile d63f3d0b-grunt-cli grunt-cli@
31 silly lockFile d63f3d0b-grunt-cli grunt-cli@
32 error Error: tunneling socket could not be established, cause=Parse Error
32 error     at ClientRequest.onError (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\tunnel.js:161:17)
32 error     at ClientRequest.g (events.js:175:14)
32 error     at ClientRequest.EventEmitter.emit (events.js:95:17)
32 error     at Socket.socketOnData (http.js:1541:9)
32 error     at TCP.onread (net.js:510:27)
33 error If you need help, you may report this log at:
33 error     <http://github.com/isaacs/npm/issues>
33 error or email it to:
33 error     <npm-@googlegroups.com>
34 error System Windows_NT 6.1.7601
35 error command "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "grunt-cli"
36 error cwd C:\Dev\svn\skt-framework
37 error node -v v0.10.1
38 error npm -v 1.2.15
39 error code ECONNRESET
40 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
@asencio Does this also occur if you [upgrade to the latest stable release of `npm`](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows)?

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
