### ISSUE TITLE
npm shrinkwrap fails: node-pre-gyp

### ISSUE THREAD

**Issue by michaelBenin** [npm/npm#8523]
```
0 info it worked if it ends with ok
1 verbose cli [ 'node',
1 verbose cli   '/Users/mbenin/.nvm/versions/node/v0.12.4/bin/npm',
1 verbose cli   'shrinkwrap' ]
2 info using npm@2.11.0
3 info using node@v0.12.4
4 verbose stack Error: Problems were encountered
4 verbose stack Please correct and try again.
4 verbose stack invalid: node-pre-gyp@0.5.31 /Users/mbenin/node_modules/gulp-node-inspector/node_modules/node-inspector/node_modules/v8-debug/node_modules/node-pre-gyp
4 verbose stack     at shrinkwrap_ (/Users/mbenin/.nvm/versions/node/v0.12.4/lib/node_modules/npm/lib/shrinkwrap.js:37:15)
4 verbose stack     at /Users/mbenin/.nvm/versions/node/v0.12.4/lib/node_modules/npm/lib/shrinkwrap.js:31:5
4 verbose stack     at /Users/mbenin/.nvm/versions/node/v0.12.4/lib/node_modules/npm/lib/ls.js:47:30
4 verbose stack     at /Users/mbenin/.nvm/versions/node/v0.12.4/lib/node_modules/npm/node_modules/read-installed/read-installed.js:138:5
4 verbose stack     at /Users/mbenin/.nvm/versions/node/v0.12.4/lib/node_modules/npm/node_modules/read-installed/read-installed.js:251:14
4 verbose stack     at cb (/Users/mbenin/.nvm/versions/node/v0.12.4/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
4 verbose stack     at /Users/mbenin/.nvm/versions/node/v0.12.4/lib/node_modules/npm/node_modules/read-installed/read-installed.js:251:14
4 verbose stack     at cb (/Users/mbenin/.nvm/versions/node/v0.12.4/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
4 verbose stack     at /Users/mbenin/.nvm/versions/node/v0.12.4/lib/node_modules/npm/node_modules/read-installed/read-installed.js:251:14
4 verbose stack     at cb (/Users/mbenin/.nvm/versions/node/v0.12.4/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
5 verbose cwd /Users/mbenin/Projects/playground/fastcompany-sitemap-crawler
6 error Darwin 14.3.0
7 error argv "node" "/Users/mbenin/.nvm/versions/node/v0.12.4/bin/npm" "shrinkwrap"
8 error node v0.12.4
9 error npm  v2.11.0
10 error Problems were encountered
10 error Please correct and try again.
10 error invalid: node-pre-gyp@0.5.31 /Users/mbenin/node_modules/gulp-node-inspector/node_modules/node-inspector/node_modules/v8-debug/node_modules/node-pre-gyp
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
```

**Comment by michaelBenin** [comment]
@iarna lmk if you need me to provide the package.json or anything else. Thank you!

**Comment by busches** [comment]
Are you still able to reproduce this error or do you have the `package.json` to reproduce?
