### ISSUE TITLE
npm winston-kafka failed

### ISSUE THREAD

**Issue by hloc** [npm/npm#8524]
```
npm ERR! git clone git://github.com/nokk/kafka-node Cloning into bare repository 'C:\Users\LH123\AppData\Roaming\npm-
cache\_git-remotes\git-github-com-nokk-kafka-node-94545700'...
npm ERR! git clone git://github.com/nokk/kafka-node fatal: unable to connect to github.com:
npm ERR! git clone git://github.com/nokk/kafka-node github.com[0: 192.30.252.130]: errno=No error
npm ERR! Error: Command failed: Cloning into bare repository 'C:\Users\LH123\AppData\Roaming\npm-cache\_git-remotes\g
it-github-com-nokk-kafka-node-94545700'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.252.130]: errno=No error
npm ERR!
npm ERR!
npm ERR!     at ChildProcess.exithandler (child_process.js:648:15)
npm ERR!     at ChildProcess.emit (events.js:98:17)
npm ERR!     at maybeClose (child_process.js:756:16)
npm ERR!     at Process.ChildProcess._handle.onexit (child_process.js:823:5)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js"
 "install" "winston-kafka"
npm ERR! cwd C:\Users\LH123\Documents\Lochy\Repo
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! code 128
npm ERR! not ok code 0
PS C:\Users\LH123\Documents\Lochy\Repo> npm install -v winston-kafka
```

**Comment by johnrc** [comment]
First off, you should probably upgrade npm. (It can be tricky on Windows so follow the [wiki](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows) for complete steps.)

Are you sitting behind a proxy? If so, does it allow you to connect to and download from github.com? You may need to setup your `.gitconfig` to contain the proxy and/or rewrite protocols from git to http.

**Comment by lochycal** [comment]
Thanks John.  I've update to 2.10.1.  I am behind a proxy, but getting to github.com was not a problem.  I was able to clone the project using command line git.  But doing an npm install still failed for this module.

I've used winston-kafka-transport instead, which is similar to winston-kafka.  I was just curious why this particular module failed to install.
