### ISSUE TITLE
npm update -g is killing npm installation (v0.12.4, OS X 10.10.3)

### ISSUE THREAD

**Issue by christianhaller** [npm/npm#8549]
```
npm update -g

> fsevents@0.3.6 install /usr/local/lib/node_modules/browser-sync/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

gyp ERR! UNCAUGHT EXCEPTION 
gyp ERR! stack Error: Cannot find module 'request'
gyp ERR! stack     at Function.Module._resolveFilename (module.js:336:15)
gyp ERR! stack     at Function.Module._load (module.js:278:25)
gyp ERR! stack     at Module.require (module.js:365:17)
gyp ERR! stack     at require (module.js:384:17)
gyp ERR! stack     at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:20:15)
gyp ERR! stack     at Module._compile (module.js:460:26)
gyp ERR! stack     at Object.Module._extensions..js (module.js:478:10)
gyp ERR! stack     at Module.load (module.js:355:32)
gyp ERR! stack     at Function.Module._load (module.js:310:12)
gyp ERR! stack     at Module.require (module.js:365:17)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/browser-sync/node_modules/chokidar/node_modules/fsevents
gyp ERR! node -v v0.12.4
gyp ERR! node-gyp -v v1.0.3
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/TooTallNate/node-gyp/issues>
npm WARN optional dep failed, continuing fsevents@0.3.6

> ws@0.5.0 install /usr/local/lib/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)


> ws@0.4.31 install /usr/local/lib/node_modules/browser-sync/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

npm WARN engine cordova-js@4.0.0: wanted: {"node":"~0.10.x"} (current: {"node":"0.12.4","npm":"2.10.1"})
npm WARN engine npm@1.3.4: wanted: {"node":">=0.6","npm":"1"} (current: {"node":"0.12.4","npm":"2.10.1"})
npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"0.12.4","npm":"2.10.1"})
/usr/local/bin/browser-sync -> /usr/local/lib/node_modules/browser-sync/bin/browser-sync.js
npm WARN unmet dependency /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm requires semver@'~2.0.8' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/semver,
npm WARN unmet dependency which is version 2.1.0
npm WARN unmet dependency /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm requires nopt@'~2.1.1' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/cordova/node_modules/nopt,
npm WARN unmet dependency which is version 3.0.1
npm WARN unmet dependency /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm requires request@'~2.21.0' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/request,
npm WARN unmet dependency which is version 2.47.0
npm WARN unmet dependency /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm requires tar@'~0.1.17' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/tar,
npm WARN unmet dependency which is version 1.0.2
npm WARN unmet dependency /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm requires node-gyp@'~0.10.6' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/node-gyp,
npm WARN unmet dependency which is version 2.0.1
npm WARN unmet dependency /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm requires glob@'~3.2.3' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/glob,
npm WARN unmet dependency which is version 4.0.6
npm WARN unmet dependency /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm requires init-package-json@'0.0.10' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/init-package-json,
npm WARN unmet dependency which is version 1.6.0
npm WARN unmet dependency /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/cordova-js/node_modules/browserify requires through2@'^1.0.0' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/through2,
npm WARN unmet dependency which is version 0.6.3
npm WARN unmet dependency /usr/local/lib/node_modules/node-gyp/node_modules/glob requires minimatch@'^2.0.1' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/node-gyp/node_modules/minimatch,
npm WARN unmet dependency which is version 1.0.0
npm WARN unmet dependency /usr/local/lib/node_modules/generator-bookmarklet/node_modules/yeoman-generator/node_modules/inquirer requires lodash@'^3.3.1' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/generator-bookmarklet/node_modules/yeoman-generator/node_modules/lodash,
npm WARN unmet dependency which is version 2.4.2
npm WARN unmet dependency /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/cordova-lib/node_modules/cordova-js requires browserify@'7.1.0' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/browserify,
npm WARN unmet dependency which is version 10.2.4
npm WARN unmet dependency /usr/local/lib/node_modules/ionic/node_modules/prompt/node_modules/utile requires async@'~0.2.9' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/ionic/node_modules/async,
npm WARN unmet dependency which is version 0.9.2
npm WARN unmet dependency /usr/local/lib/node_modules/ionic/node_modules/request/node_modules/form-data requires mime-types@'~2.0.3' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/ionic/node_modules/request/node_modules/mime-types,
npm WARN unmet dependency which is version 1.0.2
browser-sync@2.7.9 /usr/local/lib/node_modules/browser-sync
├── async-each-series@0.1.1
├── longest@1.0.1
├── query-string@2.3.0
├── emitter-steward@0.0.1
├── ucfirst@0.0.1
├── opn@1.0.2
├── dev-ip@1.0.1
├── pad-left@1.0.2 (repeat-string@1.5.2)
├── ua-parser-js@0.7.7
├── browser-sync-client@2.0.3
├── meow@3.1.0 (object-assign@2.1.1, camelcase-keys@1.0.0, minimist@1.1.1, indent-string@1.2.1)
├── portscanner@1.0.0 (async@0.1.15)
├── immutable@3.7.3
├── resp-modifier@4.0.2 (minimatch@2.0.8)
├── foxy@11.0.2 (cookie@0.1.3, http-proxy@1.11.1, lodash.merge@3.3.1)
├── connect@3.3.5 (utils-merge@1.0.0, parseurl@1.3.0, debug@2.1.3, finalhandler@0.3.4)
├── serve-static@1.9.3 (utils-merge@1.0.0, escape-html@1.0.1, parseurl@1.3.0, send@0.12.3)
├── anymatch@1.3.0 (arrify@1.0.0, micromatch@2.1.6)
├── chokidar@1.0.3 (arrify@1.0.0, path-is-absolute@1.0.0, is-glob@1.1.3, glob-parent@1.2.0, async-each@0.1.6, is-binary-path@1.0.1, readdirp@1.3.0)
├── serve-index@1.6.4 (escape-html@1.0.1, parseurl@1.3.0, batch@0.5.2, debug@2.2.0, http-errors@1.3.1, mime-types@2.0.14, accepts@1.2.9)
├── easy-extender@2.3.1 (lodash@2.4.2)
├── eazy-logger@2.1.2 (tfunk@3.0.1, opt-merger@1.1.0)
├── localtunnel@1.5.1 (debug@0.7.4, optimist@0.3.4, request@2.11.4)
├── lodash@3.9.3
├── socket.io@1.3.5 (has-binary-data@0.1.3, debug@2.1.0, socket.io-adapter@0.3.1, socket.io-parser@2.2.4, engine.io@1.5.1, socket.io-client@1.3.5)
└── browser-sync-ui@0.5.9 (connect-history-api-fallback@0.0.5, angular-touch@1.3.16, angular-sanitize@1.3.16, angular-route@1.3.16, stream-throttle@0.1.3, angular@1.3.16, weinre@2.0.0-pre-I0Z7U9OV)
npm WARN installMany normalize-package-data was bundled with npm@1.3.4, but bundled package wasn't found in unpacked tree
/usr/local/bin/cordova -> /usr/local/lib/node_modules/cordova/bin/cordova
npm WARN unmet dependency /usr/local/lib/node_modules/generator-bookmarklet/node_modules/yeoman-generator/node_modules/inquirer requires lodash@'^3.3.1' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/generator-bookmarklet/node_modules/yeoman-generator/node_modules/lodash,
npm WARN unmet dependency which is version 2.4.2
npm WARN unmet dependency /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/cordova-lib/node_modules/cordova-js requires browserify@'7.1.0' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/browserify,
npm WARN unmet dependency which is version 10.2.4
npm WARN unmet dependency /usr/local/lib/node_modules/ionic/node_modules/prompt/node_modules/utile requires async@'~0.2.9' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/ionic/node_modules/async,
npm WARN unmet dependency which is version 0.9.2
npm WARN unmet dependency /usr/local/lib/node_modules/ionic/node_modules/request/node_modules/form-data requires mime-types@'~2.0.3' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/ionic/node_modules/request/node_modules/mime-types,
npm WARN unmet dependency which is version 1.0.2
npm WARN unmet dependency /usr/local/lib/node_modules/node-gyp/node_modules/glob requires minimatch@'^2.0.1' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/node-gyp/node_modules/minimatch,
npm WARN unmet dependency which is version 1.0.0
cordova@5.1.1 /usr/local/lib/node_modules/cordova
├── underscore@1.7.0
├── q@1.0.1
├── nopt@3.0.1 (abbrev@1.0.7)
└── cordova-lib@5.1.1 (valid-identifier@0.0.1, osenv@0.1.0, properties-parser@0.2.3, mime@1.2.11, bplist-parser@0.0.6, unorm@1.3.3, semver@2.1.0, shelljs@0.3.0, through2@0.6.3, rc@0.5.2, dep-graph@1.1.0, npmconf@0.1.16, xcode@0.6.7, init-package-json@1.6.0, elementtree@0.1.6, d8@0.4.4, request@2.47.0, tar@1.0.2, glob@4.0.6, cordova-registry-mapper@1.1.7, plist@1.1.0, cordova-js@4.0.0, cordova-app-hello-world@3.9.0, npm@1.3.4)
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "update" "-g"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! path /usr/local/lib/node_modules/npm/bin/node-gyp-bin
npm ERR! code EACCES
npm ERR! errno -13

npm ERR! Error: EACCES, rmdir '/usr/local/lib/node_modules/npm/bin/node-gyp-bin'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES, rmdir '/usr/local/lib/node_modules/npm/bin/node-gyp-bin']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/usr/local/lib/node_modules/npm/bin/node-gyp-bin' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.
npm ERR! error rolling back Error: EACCES, rmdir '/usr/local/lib/node_modules/npm/html/doc'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  { [Error: EACCES, rmdir '/usr/local/lib/node_modules/npm/html/doc']
npm ERR! error rolling back   errno: -13,
npm ERR! error rolling back   code: 'EACCES',
npm ERR! error rolling back   path: '/usr/local/lib/node_modules/npm/html/doc' }

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/halle3/g+j/youtubeResizer/npm-debug.log
➜  youtubeResizer git:(master) ✗ npm
zsh: command not found: npm
```

after that, zsh tells me: 

```
command not found: npm 
```

:cry:

**Comment by j13z** [comment]
Same thing here. `npm update -g` just killed my `npm`:

```
$  npm

node.js:720
    var cwd = process.cwd();
                      ^
Error: ENOENT, no such file or directory
    at Error (native)
    at Function.startup.resolveArgv0 (node.js:720:23)
    at startup (node.js:63:13)
    at node.js:814:3
```

**Comment by j13z** [comment]
Did you try running `npm` directly from your home directory after this?

**Comment by alundiak** [comment]
I have the same with `node v.0.12.5` and `npm v2.11.2`.
I did not expect such behavior, but yes, npm was broken.
And no `npm install` in project dir was not working, because npm was not accessible by terminal (zsh).

So I just re-run nodejs install pkg file. Work fine. But now - **I WILL NOT UPDATE GLOBAL** modules, untill this issue fixed.

PS. `npm update` in prj dir doesn't work as I understand from API.

**Comment by christianhaller** [comment]
@j13z When I update npm in my home directory, it's not fucked up. :+1:

**Comment by alundiak** [comment]
I just updated to node `v4.5.0` on my Mac OS `v10.11.6` with npm `v2.15.9`, and I remember to try this command again:

`npm update -g`

So I have this:

>
npm ERR! Cannot find module '/usr/local/lib/node_modules/npm/lib/build.js'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "update" "-g"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code MODULE_NOT_FOUND

And again - NPM is removed and I have to reinstall it again :) 

@christianhaller who would possibly be informed about such behavior of NPM? Maybe there is some issue published?
