### ISSUE TITLE
issues installing bower

### ISSUE THREAD

**Issue by ronchris** [npm/npm#8553]
```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'install', '-g', 'bower' ]
2 info using npm@2.10.1
3 info using node@v0.12.4
4 verbose install initial load of /usr/local/lib/package.json
5 verbose readDependencies loading dependencies from /usr/local/lib/package.json
6 silly cache add args [ 'bower', null ]
7 verbose cache add spec bower
8 silly cache add parsed spec { raw: 'bower',
8 silly cache add   scope: null,
8 silly cache add   name: 'bower',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: '*',
8 silly cache add   type: 'range' }
9 silly addNamed bower@*
10 verbose addNamed "*" is a valid semver range for bower
11 silly addNameRange { name: 'bower', range: '*', hasData: false }
12 silly mapToRegistry name bower
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/bower
16 verbose addNameRange registry:https://registry.npmjs.org/bower not in flight; fetching
17 verbose request uri https://registry.npmjs.org/bower
18 verbose request no auth needed
19 info attempt registry request try #1 at 2:10:23 PM
20 verbose request id 3a4183b3e7be5592
21 verbose etag "A1YCJ6PMQ6P9Z4133COPXWET8"
22 http request GET https://registry.npmjs.org/bower
23 http 304 https://registry.npmjs.org/bower
24 silly get cb [ 304,
24 silly get   { date: 'Fri, 12 Jun 2015 21:10:20 GMT',
24 silly get     via: '1.1 varnish',
24 silly get     'cache-control': 'max-age=60',
24 silly get     etag: '"A1YCJ6PMQ6P9Z4133COPXWET8"',
24 silly get     age: '17',
24 silly get     connection: 'keep-alive',
24 silly get     'x-served-by': 'cache-sjc3135-SJC',
24 silly get     'x-cache': 'HIT',
24 silly get     'x-cache-hits': '1',
24 silly get     'x-timer': 'S1434143420.933611,VS0,VE1',
24 silly get     vary: 'Accept' } ]
25 verbose etag https://registry.npmjs.org/bower from cache
26 verbose get saving bower to /Users/ronaldponferrada/.npm/registry.npmjs.org/bower/.cache.json
27 silly addNameRange number 2 { name: 'bower', range: '*', hasData: true }
28 silly addNameRange versions [ 'bower',
28 silly addNameRange   [ '0.1.0',
28 silly addNameRange     '0.1.2',
28 silly addNameRange     '0.1.3',
28 silly addNameRange     '0.2.0',
28 silly addNameRange     '0.3.0',
28 silly addNameRange     '0.3.1',
28 silly addNameRange     '0.3.2',
28 silly addNameRange     '0.4.0',
28 silly addNameRange     '0.5.0',
28 silly addNameRange     '0.5.1',
28 silly addNameRange     '0.6.0',
28 silly addNameRange     '0.6.1',
28 silly addNameRange     '0.6.2',
28 silly addNameRange     '0.6.3',
28 silly addNameRange     '0.6.4',
28 silly addNameRange     '0.6.5',
28 silly addNameRange     '0.6.6',
28 silly addNameRange     '0.6.7',
28 silly addNameRange     '0.6.8',
28 silly addNameRange     '0.7.0',
28 silly addNameRange     '0.7.1',
28 silly addNameRange     '0.8.0',
28 silly addNameRange     '0.8.1',
28 silly addNameRange     '0.8.2',
28 silly addNameRange     '0.8.3',
28 silly addNameRange     '0.8.4',
28 silly addNameRange     '0.8.5',
28 silly addNameRange     '0.8.6',
28 silly addNameRange     '0.9.0',
28 silly addNameRange     '0.9.1',
28 silly addNameRange     '0.9.2',
28 silly addNameRange     '0.10.0',
28 silly addNameRange     '1.0.0',
28 silly addNameRange     '1.0.1',
28 silly addNameRange     '1.0.2',
28 silly addNameRange     '1.0.3',
28 silly addNameRange     '1.1.0',
28 silly addNameRange     '1.1.1',
28 silly addNameRange     '1.1.2',
28 silly addNameRange     '1.2.0',
28 silly addNameRange     '1.2.1',
28 silly addNameRange     '1.2.2',
28 silly addNameRange     '1.2.3',
28 silly addNameRange     '1.2.4',
28 silly addNameRange     '1.2.5',
28 silly addNameRange     '1.2.6',
28 silly addNameRange     '1.2.7',
28 silly addNameRange     '1.2.8',
28 silly addNameRange     '1.3.0',
28 silly addNameRange     '1.3.1',
28 silly addNameRange     '1.3.2',
28 silly addNameRange     '1.3.3',
28 silly addNameRange     '1.3.4',
28 silly addNameRange     '1.3.5',
28 silly addNameRange     '1.3.6',
28 silly addNameRange     '1.3.7',
28 silly addNameRange     '1.3.8',
28 silly addNameRange     '1.3.9',
28 silly addNameRange     '1.3.10',
28 silly addNameRange     '1.3.11',
28 silly addNameRange     '1.3.12',
28 silly addNameRange     '1.4.0',
28 silly addNameRange     '1.4.1' ] ]
29 silly addNamed bower@1.4.1
30 verbose addNamed "1.4.1" is a plain semver version for bower
31 silly cache afterAdd bower@1.4.1
32 verbose afterAdd /Users/ronaldponferrada/.npm/bower/1.4.1/package/package.json not in flight; writing
33 verbose afterAdd /Users/ronaldponferrada/.npm/bower/1.4.1/package/package.json written
34 silly install resolved [ { name: 'bower',
34 silly install resolved     version: '1.4.1',
34 silly install resolved     description: 'The browser package manager',
34 silly install resolved     author: { name: 'Twitter' },
34 silly install resolved     licenses: [ [Object] ],
34 silly install resolved     repository: { type: 'git', url: 'git+https://github.com/bower/bower.git' },
34 silly install resolved     main: 'lib',
34 silly install resolved     homepage: 'http://bower.io',
34 silly install resolved     engines: { node: '>=0.10.0' },
34 silly install resolved     dependencies:
34 silly install resolved      { abbrev: '^1.0.5',
34 silly install resolved        archy: '1.0.0',
34 silly install resolved        'bower-config': '^0.6.1',
34 silly install resolved        'bower-endpoint-parser': '^0.2.2',
34 silly install resolved        'bower-json': '^0.4.0',
34 silly install resolved        'bower-logger': '^0.2.2',
34 silly install resolved        'bower-registry-client': '^0.3.0',
34 silly install resolved        cardinal: '0.4.4',
34 silly install resolved        chalk: '^1.0.0',
34 silly install resolved        chmodr: '0.1.0',
34 silly install resolved        configstore: '^0.3.2',
34 silly install resolved        'decompress-zip': '^0.1.0',
34 silly install resolved        fstream: '^1.0.3',
34 silly install resolved        'fstream-ignore': '^1.0.2',
34 silly install resolved        github: '^0.2.3',
34 silly install resolved        glob: '^4.3.2',
34 silly install resolved        'graceful-fs': '^3.0.5',
34 silly install resolved        handlebars: '^2.0.0',
34 silly install resolved        inquirer: '0.8.0',
34 silly install resolved        insight: '^0.5.0',
34 silly install resolved        'is-root': '^1.0.0',
34 silly install resolved        junk: '^1.0.0',
34 silly install resolved        lockfile: '^1.0.0',
34 silly install resolved        'lru-cache': '^2.5.0',
34 silly install resolved        mkdirp: '0.5.0',
34 silly install resolved        mout: '^0.11.0',
34 silly install resolved        nopt: '^3.0.1',
34 silly install resolved        opn: '^1.0.1',
34 silly install resolved        'p-throttler': '0.1.1',
34 silly install resolved        promptly: '0.2.0',
34 silly install resolved        q: '^1.1.2',
34 silly install resolved        request: '2.53.0',
34 silly install resolved        'request-progress': '0.3.1',
34 silly install resolved        retry: '0.6.1',
34 silly install resolved        rimraf: '^2.2.8',
34 silly install resolved        semver: '^2.3.0',
34 silly install resolved        'shell-quote': '^1.4.2',
34 silly install resolved        'stringify-object': '^1.0.0',
34 silly install resolved        'tar-fs': '^1.4.1',
34 silly install resolved        tmp: '0.0.24',
34 silly install resolved        'update-notifier': '^0.3.0',
34 silly install resolved        'user-home': '^1.1.0',
34 silly install resolved        which: '^1.0.8' },
34 silly install resolved     devDependencies:
34 silly install resolved      { chai: '^1.10.0',
34 silly install resolved        coveralls: '^2.11.2',
34 silly install resolved        'expect.js': '^0.3.1',
34 silly install resolved        grunt: '^0.4.5',
34 silly install resolved        'grunt-cli': '^0.1.13',
34 silly install resolved        'grunt-contrib-jshint': '^0.10.0',
34 silly install resolved        'grunt-contrib-watch': '^0.6.1',
34 silly install resolved        'grunt-exec': '^0.4.6',
34 silly install resolved        'grunt-simple-mocha': '^0.4.0',
34 silly install resolved        istanbul: '^0.3.5',
34 silly install resolved        'load-grunt-tasks': '^2.0.0',
34 silly install resolved        mocha: '^2.1.0',
34 silly install resolved        multiline: '^1.0.2',
34 silly install resolved        nock: '^0.56.0',
34 silly install resolved        'node-uuid': '^1.4.2',
34 silly install resolved        proxyquire: '^1.3.0',
34 silly install resolved        'spawn-sync': '^1.0.5' },
34 silly install resolved     scripts: { test: 'grunt test' },
34 silly install resolved     bin: { bower: 'bin/bower' },
34 silly install resolved     preferGlobal: true,
34 silly install resolved     gitHead: 'a1287416d40f944d58cb8f2e774e2076bfffd32f',
34 silly install resolved     bugs: { url: 'https://github.com/bower/bower/issues' },
34 silly install resolved     _id: 'bower@1.4.1',
34 silly install resolved     _shasum: 'a18be39d030792754f30f1c5b32d37b0156ba8dd',
34 silly install resolved     _from: 'bower@*',
34 silly install resolved     _npmVersion: '2.7.4',
34 silly install resolved     _nodeVersion: '0.12.0',
34 silly install resolved     _npmUser: { name: 'sheerun', email: 'sheerun@sher.pl' },
34 silly install resolved     maintainers: [ [Object], [Object], [Object], [Object], [Object], [Object] ],
34 silly install resolved     dist:
34 silly install resolved      { shasum: 'a18be39d030792754f30f1c5b32d37b0156ba8dd',
34 silly install resolved        tarball: 'http://registry.npmjs.org/bower/-/bower-1.4.1.tgz' },
34 silly install resolved     directories: {},
34 silly install resolved     _resolved: 'https://registry.npmjs.org/bower/-/bower-1.4.1.tgz',
34 silly install resolved     readme: 'ERROR: No README data found!' } ]
35 info install bower@1.4.1 into /usr/local/lib
36 info installOne bower@1.4.1
37 verbose installOne of bower to /usr/local/lib not in flight; installing
38 warn locking Error: EACCES, open '/Users/ronaldponferrada/.npm/_locks/bower-e8debc5417026b57.lock'
38 warn locking     at Error (native)
38 warn locking  /Users/ronaldponferrada/.npm/_locks/bower-e8debc5417026b57.lock failed { [Error: EACCES, open '/Users/ronaldponferrada/.npm/_locks/bower-e8debc5417026b57.lock']
38 warn locking   errno: -13,
38 warn locking   code: 'EACCES',
38 warn locking   path: '/Users/ronaldponferrada/.npm/_locks/bower-e8debc5417026b57.lock' }
39 verbose stack Error: Attempt to unlock /usr/local/lib/node_modules/bower, which hasn't been locked
39 verbose stack     at unlock (/usr/local/lib/node_modules/npm/lib/utils/locker.js:66:11)
39 verbose stack     at cb (/usr/local/lib/node_modules/npm/lib/install.js:1017:5)
39 verbose stack     at /usr/local/lib/node_modules/npm/lib/install.js:1021:20
39 verbose stack     at /usr/local/lib/node_modules/npm/lib/utils/locker.js:40:9
39 verbose stack     at cb (/usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:149:38)
39 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:177:38
39 verbose stack     at FSReqWrap.oncomplete (fs.js:95:15)
40 verbose cwd /Users/ronaldponferrada
41 error Darwin 14.0.0
42 error argv "node" "/usr/local/bin/npm" "install" "-g" "bower"
43 error node v0.12.4
44 error npm  v2.10.1
45 error Attempt to unlock /usr/local/lib/node_modules/bower, which hasn't been locked
46 error If you need help, you may report this error at:
46 error     <https://github.com/npm/npm/issues>
47 verbose exit [ 1, true ]
```

**Comment by AoJ** [comment]
"38 warn locking Error: EACCES, open '/Users/ronaldponferrada/.npm/_locks/bower-e8debc5417026b57.lock'"

You have a permission problem with creating file `/Users/ronaldponferrada/.npm/_locks/bower-e8debc5417026b57.lock`

**Comment by snopeks** [comment]
Hello @ronchris, it looks like you're running into a bug we've since fixed. If you upgrade your version of npm and run `sudo chown -R $(whoami) "$HOME/.npm"` that should solve the issue on your end.

**Comment by snopeks** [comment]
@ronchris Since we haven't heard back from you I'm going to close this issue. Let me know if you still need help.
