### ISSUE TITLE
Unable to install appium from source

### ISSUE THREAD

**Issue by amitjaincoer191** [npm/npm#8599]
I tried to install appium from source, but I got below error. Please help me to resolve it.

```
C:\>npm install -g appium
npm WARN optional dep failed, continuing udidetect@1.0.7
/


> utf-8-validate@1.1.0 install C:\Users\amit.ja\AppData\Roaming\npm\node_modules\appium\node_modules\ws\node_module
s\utf-8-validate
> node-gyp rebuild

|
C:\Users\amit.ja\AppData\Roaming\npm\node_modules\appium\node_modules\ws\node_modules\utf-8-validate>if not defined
 npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\
bin\node-gyp.js" rebuild )  else (rebuild)
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js
:103:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:64:11
gyp ERR! stack     at FSReqWrap.oncomplete (evalmachine.<anonymous>:95:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "r
ebuild"
gyp ERR! cwd C:\Users\amit.ja\AppData\Roaming\npm\node_modules\appium\node_modules\ws\node_modules\utf-8-validate
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok



> bufferutil@1.1.0 install C:\Users\amit.ja\AppData\Roaming\npm\node_modules\appium\node_modules\ws\node_modules\bu
fferutil
> node-gyp rebuild

|
C:\Users\amit.ja\AppData\Roaming\npm\node_modules\appium\node_modules\ws\node_modules\bufferutil>if not defined npm
_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\
node-gyp.js" rebuild )  else (rebuild)
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js
:103:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:64:11
gyp ERR! stack     at FSReqWrap.oncomplete (evalmachine.<anonymous>:95:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "r
ebuild"
gyp ERR! cwd C:\Users\amit.ja\AppData\Roaming\npm\node_modules\appium\node_modules\ws\node_modules\bufferutil
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
npm WARN optional dep failed, continuing utf-8-validate@1.1.0
npm WARN optional dep failed, continuing bufferutil@1.1.0
|


> ws@0.5.0 install C:\Users\amit.ja\AppData\Roaming\npm\node_modules\appium\node_modules\socket.io\node_modules\eng
ine.io\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

\
C:\Users\amit.ja\AppData\Roaming\npm\node_modules\appium\node_modules\socket.io\node_modules\engine.io\node_modules
\ws>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node
)  else (rebuild) bin\node-gyp.js" rebuild |
npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"0.12.2","npm":"2.7.4"})
-


> ws@0.4.31 install C:\Users\amit.ja\AppData\Roaming\npm\node_modules\appium\node_modules\socket.io\node_modules\so
cket.io-client\node_modules\engine.io-client\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

|
C:\Users\amit.ja\AppData\Roaming\npm\node_modules\appium\node_modules\socket.io\node_modules\socket.io-client\node_
modules\engine.io-client\node_modules\ws>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_mod
ules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (rebuild)
|


> appium-chromedriver@2.1.3 install C:\Users\amit.ja\AppData\Roaming\npm\node_modules\appium\node_modules\appium-ch
romedriver
> node install-npm.js

Error: Command failed: C:\Windows\system32\cmd.exe /s /c "uname -m"
'uname' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:751:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:485:12)
npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.j
s" "install" "-g" "appium"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! file C:\Users\amit.ja\AppData\Roaming\npm-cache\delayed-stream\0.0.5\package\package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Unexpected token '\u0000' at 1:1
npm ERR!
npm ERR! ^
npm ERR! File: C:\Users\amit.ja\AppData\Roaming\npm-cache\delayed-stream\0.0.5\package\package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.j
s" "install" "-g" "appium"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4

npm ERR! Uncaught, unspecified "error" event.
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\npm-debug.log

C:\>
```

**Comment by KenanY** [comment]
@amitjaincoer191 Do you have `python` installed?:

```
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
```

Be sure to have all of `node-gyp`'s [requirements](https://github.com/TooTallNate/node-gyp/tree/56b7f9cff21b74421830cf2324545c8420f28e53#installation) before trying to install stuff that uses it.

**Comment by mojjj** [comment]
i have a similar issue (my python is in place and happy working)

appium on windows, fails with calling "uname", a linux command (to my knowledge) not available at windows cmd

    > appium-chromedriver@2.1.3 install C:\mbahr\0_work\14-08_MBC\3\mbConnect\node_modules\appium\node_modules\appium-chromedriver
    > node install-npm.js

    'uname' is not recognized as an internal or external command,
    operable program or batch file.

**Comment by amitjaincoer191** [comment]
@mojjj  
I also tried again after installing python and setting environment variables but appium is not getting installed. Any other way to install, do we have any other perquisite for installing appium from source.

How can I clean the existing npm, I want to try install with fresh, what all folder needs to be deleted.
Kindly help ...

**Comment by mojjj** [comment]
i opened this issue at the ppium github tracker:  https://github.com/appium/appium/issues/5289

@amitjaincoer191 to clean npm cache call
    
    npm cache clean

or (on windows) navigate to the npm directories (usually in C:\Users\username\AppData\Roaming\)
delete there the "npm-cache" or both content of "npm" (not npm itself) and "npm-cache". but i doubt this will help your issue. looks to me like the appium install is not aware of being on windows and calls linux commands in the cromedriver dependency (at least for me).

**Comment by amitjaincoer191** [comment]
@mojj Thankyou very much ....

**Comment by mojjj** [comment]
@amitjaincoer191, there is [an exe installer](https://bitbucket.org/appium/appium.app/downloads/AppiumForWindows.zip) available which works for me. see appium/appium#5289

**Comment by hemano** [comment]
If you're getting this error on Windows 10 then try below command

npm --add-python-to-path='true' --debug install --global windows-build-tool
