### ISSUE TITLE
npm ERR! Error: UNABLE_TO_VERIFY_LEAF_SIGNATURE

### ISSUE THREAD

**Issue by Alxecs** [npm/npm#8601]
I try to install express but I get this errror and the following log:alexis@alexis-VirtualBox:~$ npm install express --save
```
npm http GET https://registry.npmjs.org/express
npm http GET https://registry.npmjs.org/express
npm http GET https://registry.npmjs.org/express
npm ERR! Error: UNABLE_TO_VERIFY_LEAF_SIGNATURE
npm ERR!     at SecurePair.<anonymous> (tls.js:1370:32)
npm ERR!     at SecurePair.EventEmitter.emit (events.js:92:17)
npm ERR!     at SecurePair.maybeInitFinished (tls.js:982:10)
npm ERR!     at CleartextStream.read [as _read] (tls.js:469:13)
npm ERR!     at CleartextStream.Readable.read (_stream_readable.js:320:10)
npm ERR!     at EncryptedStream.write [as _write] (tls.js:366:25)
npm ERR!     at doWrite (_stream_writable.js:223:10)
npm ERR!     at writeOrBuffer (_stream_writable.js:213:5)
npm ERR!     at EncryptedStream.Writable.write (_stream_writable.js:180:11)
npm ERR!     at write (_stream_readable.js:583:24)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.16.0-30-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "express" "--save"
npm ERR! cwd /home/alexis
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/alexis/npm-debug.log
npm ERR! not ok code 0
```
How do I fix it!?

::::::::::>Help please<:::::::::

**Comment by KenanY** [comment]
@Alxecs Could you try [upgrading](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) first?

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.

**Comment by nevercute** [comment]
I had a problem above installing the GULP. If you're not scared, type this in cmd before installing: npm config set registry http://registry.npmjs.org/ 

Profit

**Comment by nevercute** [comment]
npm config set registry http://registry.npmjs.org/
