### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by cesarob** [npm/npm#8606]
The same error has happend to me in two machines. I have a user already created in the website so why I am not being able to login? I double checked the password.
```
cesar@cesar-olaptop:~$ npm login
Username: cesarob
Password: 
Email: cesar.ortiz@gmail.com
npm http PUT https://registry.npmjs.org/-/user/org.couchdb.user:cesarob
npm http 400 https://registry.npmjs.org/-/user/org.couchdb.user:cesarob
npm ERR! Error: Unknown error while authenticating : -/user/org.couchdb.user:cesarob
npm ERR!     at RegClient.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:272:14)
npm ERR!     at Request.self.callback (/usr/lib/node_modules/npm/node_modules/request/request.js:123:22)
npm ERR!     at Request.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/lib/node_modules/npm/node_modules/request/request.js:877:14)
npm ERR!     at Request.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/lib/node_modules/npm/node_modules/request/request.js:828:12)
npm ERR!     at IncomingMessage.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:929:16
npm ERR!     at process._tickCallback (node.js:419:13)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/isaacs/npm/issues>

npm ERR! System Linux 3.2.0-4-486
npm ERR! command "node" "/usr/bin/npm" "login"
npm ERR! cwd /home/cesar
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.3.17
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/cesar/npm-debug.log
npm ERR! not ok code 0
```

Thanks,

**Comment by cesarob** [comment]
I updated the npm and it worked.
