### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by ribhudubey** [npm/npm#8612]
I am unable to install protractor . I have already install npm & its showing its version in cmd but while running this command - npm install -g protractor I am getting lots of errors  
- Invalid protocol :null
  -node gyp rebuild 
  Configuration error

---

This is the Cmd msg

```
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "protractor"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1

npm ERR! Invalid protocol: null
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
\
> bufferutil@1.1.0 install C:\Users\*******\AppData\Roaming\npm\node_modules\pr
otractor\node_modules\selenium-webdriver\node_modules\ws\node_modules\bufferutil

> node-gyp rebuild


C:\Users\*******\AppData\Roaming\npm\node_modules\protractor\node_modules\selen
ium-webdriver\node_modules\ws\node_modules\bufferutil>if not defined npm_config_
node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..
\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (rebuild)
gyp WARN download ignoring invalid "proxy" config setting: "http_proxy=http://
*******:password@*******"
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: Invalid protocol: null
gyp ERR! stack     at Request.init (C:\Program Files\nodejs\node_modules\npm\nod
e_modules\request\request.js:640:31)
gyp ERR! stack     at new Request (C:\Program Files\nodejs\node_modules\npm\node
_modules\request\request.js:272:8)
gyp ERR! stack     at request (C:\Program Files\nodejs\node_modules\npm\node_mod
ules\request\index.js:56:10)
gyp ERR! stack     at download (C:\Program Files\nodejs\node_modules\npm\node_mo
dules\node-gyp\lib\install.js:146:13)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node
-gyp\lib\install.js:228:17
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\mkdi
rp\index.js:48:26
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:95:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modu
les\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\*******\AppData\Roaming\npm\node_modules\protractor\node_
modules\selenium-webdriver\node_modules\ws\node_modules\bufferutil
gyp ERR! node -v v0.12.4
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok

> utf-8-validate@1.1.0 install C:\Users\*******\AppData\Roaming\npm\node_module
s\protractor\node_modules\selenium-webdriver\node_modules\ws\node_modules\utf-8-
validate
> node-gyp rebuild


C:\Users\*******\AppData\Roaming\npm\node_modules\protractor\node_modules\selen
ium-webdriver\node_modules\ws\node_modules\utf-8-validate>if not defined npm_con
fig_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\.
.\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (rebuild)
gyp WARN download ignoring invalid "proxy" config setting: "http_proxy=http://
*******:password@*******"
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: Invalid protocol: null
gyp ERR! stack     at Request.init (C:\Program Files\nodejs\node_modules\npm\nod
e_modules\request\request.js:640:31)
gyp ERR! stack     at new Request (C:\Program Files\nodejs\node_modules\npm\node
_modules\request\request.js:272:8)
gyp ERR! stack     at request (C:\Program Files\nodejs\node_modules\npm\node_mod
ules\request\index.js:56:10)
gyp ERR! stack     at download (C:\Program Files\nodejs\node_modules\npm\node_mo
dules\node-gyp\lib\install.js:146:13)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node
-gyp\lib\install.js:228:17
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\mkdi
rp\index.js:48:26
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:95:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modu
les\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\*******\AppData\Roaming\npm\node_modules\protractor\node_
modules\selenium-webdriver\node_modules\ws\node_modules\utf-8-validate
gyp ERR! node -v v0.12.4
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
npm WARN optional dep failed, continuing bufferutil@1.1.0
npm WARN optional dep failed, continuing utf-8-validate@1.1.0
```

![error](https://cloud.githubusercontent.com/assets/12965290/8251539/058b0f86-169b-11e5-8701-8e6f728098db.png)

**Comment by richard-martens** [comment]
I have the same issue:

> bcrypt@1.0.2 install C:\...\node_modules\bcrypt
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN download ignoring invalid "proxy" config setting: ""http://99.
999.999.99:9999""
node-pre-gyp ERR! Tried to download(undefined): https://github.com/kelektiv/node
.bcrypt.js/releases/download/v1.0.2/bcrypt_lib-v1.0.2-node-v51-win32-x64.tar.gz

node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.2 and node@7.7.2 (
node-v51 ABI) (falling back to source compile with node-gyp)

npm version 4.1.2
node version 7.7.2
