### ISSUE TITLE
npm adduser failure

### ISSUE THREAD

**Issue by birkanu** [npm/npm#8621]
Here is the log:
```
npm http PUT https://registry.npmjs.org/-/user/org.couchdb.user:birkanu
npm http 400 https://registry.npmjs.org/-/user/org.couchdb.user:birkanu
npm ERR! Error: Unknown error while authenticating : -/user/org.couchdb.user:birkanu
npm ERR!     at RegClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:275:14)
npm ERR!     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:123:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:893:14)
npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:844:12)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/isaacs/npm/issues>

npm ERR! System Darwin 14.3.0
npm ERR! command "node" "/usr/local/bin/npm" "adduser"
npm ERR! cwd /Users/birkanuzun93/Documents/bling
npm ERR! node -v v0.10.24
npm ERR! npm -v 1.3.21
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/birkanuzun93/Documents/bling/npm-debug.log
npm ERR! not ok code 0
```
Any recommendations?

**Comment by KenanY** [comment]
@birkanu 

> Any recommendations?

[Upgrade](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm)!

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
