### ISSUE TITLE
publish failed, I'm sure i logged in as right user.

### ISSUE THREAD

**Issue by zchen323** [npm/npm#8625]
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'publish' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 verbose publish [ '.' ]
6 silly cache add args [ '.', null ]
7 verbose cache add spec .
8 silly cache add parsed spec { raw: '.',
8 silly cache add   scope: null,
8 silly cache add   name: null,
8 silly cache add   rawSpec: '.',
8 silly cache add   spec: 'C:\\home\\myapp\\repo\\censorify',
8 silly cache add   type: 'directory' }
9 verbose addLocalDirectory C:\Users\charlie\AppData\Roaming\npm-cache\censorify\0.1.1\package.tgz not in flight; packing
10 verbose tar pack [ 'C:\\Users\\charlie\\AppData\\Roaming\\npm-cache\\censorify\\0.1.1\\package.tgz',
10 verbose tar pack   'C:\\home\\myapp\\repo\\censorify' ]
11 verbose tarball C:\Users\charlie\AppData\Roaming\npm-cache\censorify\0.1.1\package.tgz
12 verbose folder C:\home\myapp\repo\censorify
13 info prepublish censorify@0.1.1
14 verbose addLocalTarball adding from inside cache C:\Users\charlie\AppData\Roaming\npm-cache\censorify\0.1.1\package.tgz
15 silly cache afterAdd censorify@0.1.1
16 verbose afterAdd C:\Users\charlie\AppData\Roaming\npm-cache\censorify\0.1.1\package\package.json not in flight; writing
17 verbose afterAdd C:\Users\charlie\AppData\Roaming\npm-cache\censorify\0.1.1\package\package.json written
18 silly publish { author: { name: 'Brad Dayley' },
18 silly publish   name: 'censorify',
18 silly publish   version: '0.1.1',
18 silly publish   description: 'Censors words out of text',
18 silly publish   main: 'censortext',
18 silly publish   repository: { type: 'git', url: 'http://github.com/zhcen323/nodetest' },
18 silly publish   keywords: [ 'censor', 'words' ],
18 silly publish   dependencies: {},
18 silly publish   engines: { node: '*' },
18 silly publish   bugs: { url: 'https://github.com/zhcen323/nodetest/issues' },
18 silly publish   readme: 'ERROR: No README data found!',
18 silly publish   homepage: 'https://github.com/zhcen323/nodetest',
18 silly publish   _id: 'censorify@0.1.1',
18 silly publish   scripts: {},
18 silly publish   _shasum: 'e60dd12e544a416670fc9082bc40a68d913c4e57',
18 silly publish   _from: '.' }
19 silly mapToRegistry name censorify
20 silly mapToRegistry using default registry
21 silly mapToRegistry registry https://registry.npmjs.org/
22 silly mapToRegistry uri https://registry.npmjs.org/censorify
23 verbose publish registryBase https://registry.npmjs.org/
24 silly publish uploading C:\Users\charlie\AppData\Roaming\npm-cache\censorify\0.1.1\package.tgz
25 verbose request uri https://registry.npmjs.org/censorify
26 verbose request sending authorization for write operation
27 info attempt registry request try #1 at 2:42:37 PM
28 verbose request using bearer token for auth
29 verbose request id 739b154b97933a89
30 http request PUT https://registry.npmjs.org/censorify
31 http 403 https://registry.npmjs.org/censorify
32 verbose headers { 'content-type': 'application/json',
32 verbose headers   'cache-control': 'max-age=60',
32 verbose headers   'content-length': '101',
32 verbose headers   'accept-ranges': 'bytes',
32 verbose headers   date: 'Sat, 20 Jun 2015 19:42:17 GMT',
32 verbose headers   via: '1.1 varnish',
32 verbose headers   connection: 'keep-alive',
32 verbose headers   'x-served-by': 'cache-jfk1030-JFK',
32 verbose headers   'x-cache': 'MISS',
32 verbose headers   'x-cache-hits': '0',
32 verbose headers   'x-timer': 'S1434829337.583223,VS0,VE340' }
33 verbose request invalidating C:\Users\charlie\AppData\Roaming\npm-cache\registry.npmjs.org\censorify on PUT
34 error publish Failed PUT 403
35 verbose stack Error: You do not have permission to publish 'censorify'. Are you logged in as the correct user? : censorify
35 verbose stack     at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:247:14)
35 verbose stack     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:170:14)
35 verbose stack     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:344:22)
35 verbose stack     at Request.emit (events.js:110:17)
35 verbose stack     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1239:14)
35 verbose stack     at Request.emit (events.js:129:20)
35 verbose stack     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1187:12)
35 verbose stack     at IncomingMessage.emit (events.js:129:20)
35 verbose stack     at _stream_readable.js:908:16
35 verbose stack     at process._tickCallback (node.js:355:11)
36 verbose statusCode 403
37 verbose pkgid censorify
38 verbose cwd C:\home\myapp\repo\censorify
39 error Windows_NT 6.1.7601
40 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "publish"
41 error node v0.12.2
42 error npm  v2.7.4
43 error code E403
44 error You do not have permission to publish 'censorify'. Are you logged in as the correct user? : censorify
45 error If you need help, you may report this error at:
45 error     <https://github.com/npm/npm/issues>
46 verbose exit [ 1, true ]
```

**Comment by iarna** [comment]
@zchen323 You tried to publish the module "censorify" which is maintained by [sisingh](https://www.npmjs.com/~sisingh). As the message says, you do not have permission to publish 'censorify' as it's not owned by you.

**Comment by zchen323** [comment]
Can we have better error message say "you don't have permission to overwrite this module"?

**Comment by KenanY** [comment]
@zchen323 I don't know, "overwrite" seems like the wrong word to me. No one really has permissions to completely "overwrite" a module, especially since force-publishing was disabled last year. I like how the current message is explicit enough without making the user  consider what an "overwrite" means in terms of publishing a module:

```
44 error You do not have permission to publish 'censorify'
```

**Comment by iarna** [comment]
I'm going to close this as the original issue is resolved.

**Comment by shkesar** [comment]
Using npm version 5.0 and got the same utterly confusing message and found this thread.

Something like "This package name is already owned by a different user in the public scope. Please check if you are logged in with correct credentials to publish this." will be more friendly.
