### ISSUE TITLE
adduser couchdb issue

### ISSUE THREAD

**Issue by LeePorte** [npm/npm#8630]
Hi,

I have been trying to use npm adduser --registry <url> and am coming up against `internal server error : -/user/org.couchdb.user:<username>`

`lee@leeporte:~$ npm -v
2.10.1`
npm-debug.log is below looking at line 6 it's the - issue

```
0 info it worked if it ends with ok
1 verbose cli [ '/home/ubuntu/.nvm/versions/v0.12.4/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'adduser',
1 verbose cli   '--registry',
1 verbose cli   'http://sinopia.footballradar.net' ]
2 info using npm@2.10.1
3 info using node@v0.12.4
4 verbose config Skipping project config: /home/ubuntu/.npmrc. (matches userconfig)
5 verbose adduser before first PUT { _id: 'org.couchdb.user:lee',
5 verbose adduser   name: 'lee',
5 verbose adduser   password: 'XXXXX',
5 verbose adduser   email: 'lee.porte@footballradar.com',
5 verbose adduser   type: 'user',
5 verbose adduser   roles: [],
5 verbose adduser   date: '2015-06-21T14:05:04.570Z' }
6 verbose request uri http://sinopia.footballradar.net/-/user/org.couchdb.user:lee
7 verbose request new user, so can't send auth
8 info attempt registry request try #1 at 14:05:04
9 verbose request id cb8a5bb210d6fb18
10 http request PUT http://sinopia.footballradar.net/-/user/org.couchdb.user:lee
11 http 500 http://sinopia.footballradar.net/-/user/org.couchdb.user:lee
12 info retry will retry, error on last attempt: Error: internal server error : -/user/org.couchdb.user:lee
13 info attempt registry request try #2 at 14:05:14
14 http request PUT http://sinopia.footballradar.net/-/user/org.couchdb.user:lee
15 http 500 http://sinopia.footballradar.net/-/user/org.couchdb.user:lee
16 info retry will retry, error on last attempt: Error: internal server error : -/user/org.couchdb.user:lee
17 info attempt registry request try #3 at 14:06:14
18 http request PUT http://sinopia.footballradar.net/-/user/org.couchdb.user:lee
19 http 500 http://sinopia.footballradar.net/-/user/org.couchdb.user:lee
20 verbose headers { server: 'nginx/1.4.6 (Ubuntu)',
20 verbose headers   date: 'Sun, 21 Jun 2015 14:09:43 GMT',
20 verbose headers   'content-type': 'application/json; charset=utf-8',
20 verbose headers   'content-length': '39',
20 verbose headers   connection: 'keep-alive',
20 verbose headers   'x-powered-by': 'Sinopia/1.4.0',
20 verbose headers   vary: 'Accept-Encoding',
20 verbose headers   'x-status-cat': 'http://flic.kr/p/aVdo6e' }
21 verbose request invalidating /home/ubuntu/.npm/sinopia.footballradar.net/-/user/org.couchdb.user_3Alee on PUT
22 verbose adduser back [ { [Error: internal server error : -/user/org.couchdb.user:lee] statusCode: 500, code: 'E500' },
22 verbose adduser   { error: 'internal server error' },
22 verbose adduser   '{"error":"internal server error"}' ]
23 verbose stack Error: internal server error : -/user/org.couchdb.user:lee
23 verbose stack     at CachingRegistryClient.<anonymous> (/home/ubuntu/.nvm/versions/v0.12.4/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:247:14)
23 verbose stack     at Request._callback (/home/ubuntu/.nvm/versions/v0.12.4/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:170:14)
23 verbose stack     at Request.self.callback (/home/ubuntu/.nvm/versions/v0.12.4/lib/node_modules/npm/node_modules/request/request.js:368:22)
23 verbose stack     at Request.emit (events.js:110:17)
23 verbose stack     at Request.<anonymous> (/home/ubuntu/.nvm/versions/v0.12.4/lib/node_modules/npm/node_modules/request/request.js:1219:14)
23 verbose stack     at Request.emit (events.js:129:20)
23 verbose stack     at IncomingMessage.<anonymous> (/home/ubuntu/.nvm/versions/v0.12.4/lib/node_modules/npm/node_modules/request/request.js:1167:12)
23 verbose stack     at IncomingMessage.emit (events.js:129:20)
23 verbose stack     at _stream_readable.js:908:16
23 verbose stack     at process._tickCallback (node.js:355:11)
24 verbose statusCode 500
25 verbose cwd /home/ubuntu
26 error Linux 3.13.0-55-generic
27 error argv "/home/ubuntu/.nvm/versions/v0.12.4/bin/node" "/usr/bin/npm" "adduser" "--registry" "http://sinopia.footballradar.net"
28 error node v0.12.4
29 error npm  v2.10.1
30 error code E500
31 error internal server error : -/user/org.couchdb.user:lee
32 error If you need help, you may report this error at:
32 error     <https://github.com/npm/npm/issues>
33 verbose exit [ 1, true ]
```

Thanks

Lee

**Comment by LeePorte** [comment]
I'm also seeing the same issue with npm 2.11.3

**Comment by tzi** [comment]
I have the same issue.
Current configuration: ubuntu 14.04, node 0.10.25, npm 1.3.10

**Comment by KenanY** [comment]
@tzi Please [upgrade](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) first. `npm@1.3` is very old and no longer supported as of _months_ ago.

**Comment by tzi** [comment]
It works with npm 2.13.4.

Thanks.
