### ISSUE TITLE
Can't npm publish

### ISSUE THREAD

**Issue by hassankhan** [npm/npm#8661]
I get the following error:
```
npm ERR! publish Failed PUT 500
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "publish"
npm ERR! node v0.12.5
npm ERR! npm  v2.11.2
npm ERR! code E500

npm ERR! unexpected status code: 401 : emojify.js
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Volumes/Data HD/Projects/emojify.js/npm-debug.log
Hassan’s MacBook Pro:emojify.js hassankhan$
```

Attached npm-debug.log:
```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'publish' ]
2 info using npm@2.11.2
3 info using node@v0.12.5
4 verbose publish [ '.' ]
5 silly cache add args [ '.', null ]
6 verbose cache add spec .
7 silly cache add parsed spec { raw: '.',
7 silly cache add   scope: null,
7 silly cache add   name: null,
7 silly cache add   rawSpec: '.',
7 silly cache add   spec: '/Volumes/Data HD/Projects/emojify.js',
7 silly cache add   type: 'directory' }
8 verbose addLocalDirectory /Users/hassankhan/.npm/emojify.js/1.0.5/package.tgz not in flight; packing
9 verbose tar pack [ '/Users/hassankhan/.npm/emojify.js/1.0.5/package.tgz',
9 verbose tar pack   '/Volumes/Data HD/Projects/emojify.js' ]
10 verbose tarball /Users/hassankhan/.npm/emojify.js/1.0.5/package.tgz
11 verbose folder /Volumes/Data HD/Projects/emojify.js
12 info prepublish emojify.js@1.0.5
13 verbose addLocalTarball adding from inside cache /Users/hassankhan/.npm/emojify.js/1.0.5/package.tgz
14 silly cache afterAdd emojify.js@1.0.5
15 verbose afterAdd /Users/hassankhan/.npm/emojify.js/1.0.5/package/package.json not in flight; writing
16 verbose afterAdd /Users/hassankhan/.npm/emojify.js/1.0.5/package/package.json written
17 silly publish { name: 'emojify.js',
17 silly publish   version: '1.0.5',
17 silly publish   description: 'A Javascript module to convert emoji keywords to images.',
17 silly publish   main: 'dist/js/emojify.js',
17 silly publish   scripts: { test: 'phantomjs tests/phantom.js && node tests/node' },
17 silly publish   repository:
17 silly publish    { type: 'git',
17 silly publish      url: 'git+https://hassankhan@github.com/hassankhan/emojify.js.git' },
17 silly publish   keywords: [ 'emoji', 'emojify', 'javascript' ],
17 silly publish   author: { name: 'Hassan Khan' },
17 silly publish   license: 'MIT',
17 silly publish   bugs: { url: 'https://github.com/hassankhan/emojify.js/issues' },
17 silly publish   devDependencies:
17 silly publish    { jstest: '~1.0.4',
17 silly publish      q: '^1.0.1',
17 silly publish      gulp: '~3.8.9',
17 silly publish      'gulp-load-plugins': '~0.7.0',
17 silly publish      'gulp-jshint': '~1.8.5',
17 silly publish      'jshint-stylish': '~1.0.0',
17 silly publish      'gulp-insert': '~0.4.0',
17 silly publish      'gulp-uglify': '~1.0.1',
17 silly publish      'gulp-rename': '~1.2.0',
17 silly publish      'gulp-minify-css': '~0.3.11',
17 silly publish      'gulp-image-data-uri': '~1.0.0',
17 silly publish      'gulp-filter': '~1.0.2',
17 silly publish      'gulp-concat': '~2.4.1',
17 silly publish      jsdom: '^1.1.0',
17 silly publish      del: '~0.1.3',
17 silly publish      'css-sprite': '~0.9.0',
17 silly publish      'gulp-replace': '~0.5.0',
17 silly publish      inquirer: '~0.8.0',
17 silly publish      'gulp-bump': '~0.1.11',
17 silly publish      'gulp-download': '0.0.1',
17 silly publish      'gulp-unzip': '~0.1.2',
17 silly publish      minimatch: '~1.0.0',
17 silly publish      through2: '~0.6.3' },
17 silly publish   testling:
17 silly publish    { html: 'tests/browser/browser.html',
17 silly publish      browsers:
17 silly publish       [ 'ie/8..latest',
17 silly publish         'chrome/23..latest',
17 silly publish         'firefox/22..latest',
17 silly publish         'safari/latest',
17 silly publish         'opera/latest',
17 silly publish         'iphone/6..latest',
17 silly publish         'ipad/6..latest',
17 silly publish         'android-browser/latest' ] },
17 silly publish   dependencies: {},
17 silly publish   readme: '# emojify.js\n\n[![npm version][ico-npm]][package-npm]\n[![Bower version][ico-bower]][package-bower]\n[![MIT Licensed][ico-license]][license]\n[![Gitter chat][ico-gitter]][gitter]\n\n---\n\nMaster | Develop\n--- | ---\n[![Master branch build status][ico-build]][travis] | [![Develop branch build status][ico-build-dev]][travis]\n[![Master branch Windows build status][ico-windows-build]][appveyor] | [![Develop branch Windows build status][ico-windows-build-dev]][appveyor]\n\n[![Browser Results](https://ci.testling.com/hassankhan/emojify.js.png)](https://ci.testling.com/hassankhan/emojify.js)\n\nA swiss-army-knife for all emoji, in Javascript. Used by [Gitter](https://gitter.im/) and [Mapbox](https://www.mapbox.com/blog/emoji-map-markers/).\n\nThe emoji keywords are as described by [emoji-cheat-sheet.com](http://www.emoji-cheat-sheet.com).\n\nGo to this project\'s [GitHub pages](http://hassankhan.github.com/emojify.js) to see the code in action.\n\n## Features\n\n- Fast\n- Awesome\n- Converts emoticons like `:) :( :\'(`\n- Allows customisation of processed emoji\n- Multiple modes; `img`, sprites and data-URI\n- Available on a CDN **(gasp)**\n- Includes a [sample `.htaccess` file](.htaccess) for caching Javascript and CSS\n- Switchable emoji sets **(SOON!)**\n- Made from unicorn blood\n\n## Installation\n\nCare about old browsers compatibility? Use https://github.com/es-shims/es5-shim\n\n### Via cdnjs\n\nemojify.js is now available on cdnjs - https://cdnjs.com/libraries/emojify.js\n\nAdd this to the rest of your stylesheet imports:\n\n`<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/emojify.js/1.0.1/emojify.min.css" />`\n\nThen add this to your Javascript code:\n\n`<script src="//cdnjs.cloudflare.com/ajax/libs/emojify.js/1.0.1/emojify.min.js"></script>`\n\n### Via Bower\n\n`bower install emojify.js --save`\n\n### Via npm\n\n`npm install emojify.js  --save`\n\n## API\n\n### setConfig([object])\n\n*This works in the browser and on Node*\n\n#### Parameters\n\n- `object` - Optional JSON object with any of the following attributes:\n\nOption | Default | Description\n--- | --- | ---\n`blacklist.elements` | `[\'script\', \'textarea\', \'a\', \'pre\', \'code\']` | An array of elements you don\'t want emojified\n`blacklist.classes` | `[\'no-emojify\']` | An array of classes you don\'t want emojified\n`mode` | `img` | By default, emojify will output an `img` with a `src` attribute for each emoji found. But if `mode` is set to `sprite` or `data-uri`, then `span`s with classes are outputted. Don\'t forget to include the appropriate CSS for your choice though, see the `/dist` directory.\n`tag_type` | `null` | When set, emojify uses this element with the class `emoji emoji-#{emojiname}` instead of an `img` with a `src` attribute.  Example valid values: `div`, `span`. This takes precedence over the `mode` option. Note: if you\'re not using `img`s, `.emoji-+1` isn\'t a valid class, so `.emoji-plus1` is used instead.\n`only_crawl_id` | `null` | **[DEPRECATED]** Restricts searching for emojis to a specified element & it\'s children. If null, and no object is passed to `run()`, `document.body` is used\n`img_dir` | `\'images/emoji\'` | Defines the path to the emoji images\n`ignore_emoticons` | `false` | If `true`, only convert emoji like `:smile:` and ignore emoticons like `:)`\n\n#### Usage\n```js\nemojify.setConfig({tag_type : \'div\'});\n```\n\n---\n\n### run([element], [replacer])\n\n*This works in the browser and Node*\n\n#### Parameters\n- `element` - Optional HTML element to restrict the emojification to.\n- `replacer` - Optional Function to override emoji replacement behaviour with your own. The function will receive two arguments, the emoji pattern found (`emoji`), and the emoji name (`name`). In the case of emoticons, for example, `emoji = \':)\'` and `name = \'smile\'`. Your function must return a HTMLElement.\n\n\n##### Browser\n```js\nemojify.run();\n// OR\nemojify.run(document.getElementById(\'my-element\'))\n// OR\nemojify.run(null, function(emoji, emojiName){\n  var span = document.createElement(\'span\');\n  span.className = \'emoji emoji-\'  + emojiName;\n  span.innerHTML = emoji + \' replaced\';\n  return span;\n});\n```\n\n##### Node.js\nRequires you to have jsdom installed:\n`npm i jsdom --save`\n\n```js\nvar jsdom = require(\'jsdom\')\n\njsdom.env({\n    html: "<p><code>jhhh</code><em>:)</em></p>",\n    done: function(errors, window) {\n        emojify.run(window.document.body)\n    }\n});\n```\n---\n\n### replace(string, [callback])\n\n*This works in the browser and on Node*\n\n#### Parameters\n- `string` - String to emojify\n- `callback` - Optional callback function to output emoji with\n\n#### Usage\n\nBy default, emojify.js uses the internal function `defaultReplacer()` to replace emoji. You can override this behaviour by supplying your own callback function.\n\nYour callback function will receive two arguments, the emoji pattern found (`emoji`), and the emoji name (`name`). In the case of emoticons, for example, `emoji = \':)\'` and `name = \'smile\'`.\n\nThe context in which your replacer function is run will have the config available. So you can access properties such as `img_dir` at `this.config.img_dir`.\n\n```js\nemojify.replace(\'I am happy :)\');\n// OR\nreplacer = function(emoji, name) {\n    // Customise output here\n    return emojifiedString;\n}\n\nemojify.replace(\'I am happy :)\', replacer);\n```\n\n## Contributing changes\n\nPlease read [CONTRIBUTING.md](CONTRIBUTING.md).\n\n## Credits\n\n- [All Contributors](https://github.com/hassankhan/emojify.js/contributors)\n- [Hassan Khan](https://github.com/hassankhan)\n\n## License\n\nPlease read [LICENSE.md](LICENSE.md). For image attributions, please read [LICENSE-IMAGES.md](LICENSE-IMAGES.md)\n\n[travis]: https://travis-ci.org/hassankhan/emojify.js\n[appveyor]: https://ci.appveyor.com/project/hassankhan/emojify-js\n[package-bower]: http://bower.io/search/?q=emojify.js\n[package-npm]: https://www.npmjs.org/package/emojify.js\n[ico-build]: http://img.shields.io/travis/hassankhan/emojify.js.svg?style=flat-square\n[ico-build-dev]: http://img.shields.io/travis/hassankhan/emojify.js/develop.svg?style=flat-square\n[ico-windows-build]: https://ci.appveyor.com/api/projects/status/908bymld8nm3ykxm?svg=true\n[ico-windows-build-dev]: https://ci.appveyor.com/api/projects/status/908bymld8nm3ykxm/branch/develop?svg=true\n[ico-bower]: http://img.shields.io/bower/v/emojify.js.svg?style=flat-square\n[ico-npm]: http://img.shields.io/npm/v/emojify.js.svg?style=flat-square\n[ico-license]: http://img.shields.io/npm/l/emojify.js.svg?style=flat-square\n[ico-gitter]: https://badges.gitter.im/hassankhan/emojify.js.svg\n[license]: http://hassankhan.mit-license.org/\n[gitter]: https://gitter.im/hassankhan/emojify.js\n',
17 silly publish   readmeFilename: 'README.md',
17 silly publish   gitHead: 'fe0dd41a2d01df97da8bd8e70763715c6a28f738',
17 silly publish   homepage: 'https://github.com/hassankhan/emojify.js#readme',
17 silly publish   _id: 'emojify.js@1.0.5',
17 silly publish   _shasum: '000bfcc896e115e767600761ed42369cfb897be3',
17 silly publish   _from: '.' }
18 verbose getPublishConfig undefined
19 silly mapToRegistry name emojify.js
20 silly mapToRegistry using default registry
21 silly mapToRegistry registry https://registry.npmjs.org/
22 silly mapToRegistry uri https://registry.npmjs.org/emojify.js
23 verbose publish registryBase https://registry.npmjs.org/
24 silly publish uploading /Users/hassankhan/.npm/emojify.js/1.0.5/package.tgz
25 verbose request uri https://registry.npmjs.org/emojify.js
26 verbose request sending authorization for write operation
27 info attempt registry request try #1 at 12:46:04 PM
28 verbose request id 89dfa7877971cc49
29 http request PUT https://registry.npmjs.org/emojify.js
30 http 500 https://registry.npmjs.org/emojify.js
31 info retry will retry, error on last attempt: Error: unexpected status code: 401 : emojify.js
32 info attempt registry request try #2 at 12:52:29 PM
33 http request PUT https://registry.npmjs.org/emojify.js
34 http 500 https://registry.npmjs.org/emojify.js
35 info retry will retry, error on last attempt: Error: unexpected status code: 401 : emojify.js
36 info attempt registry request try #3 at 12:59:40 PM
37 http request PUT https://registry.npmjs.org/emojify.js
38 http 500 https://registry.npmjs.org/emojify.js
39 verbose headers { 'content-type': 'application/json',
39 verbose headers   'cache-control': 'max-age=0',
39 verbose headers   'content-length': '39',
39 verbose headers   'accept-ranges': 'bytes',
39 verbose headers   date: 'Wed, 24 Jun 2015 12:06:06 GMT',
39 verbose headers   via: '1.1 varnish',
39 verbose headers   connection: 'keep-alive',
39 verbose headers   'x-served-by': 'cache-lhr6332-LHR',
39 verbose headers   'x-cache': 'MISS',
39 verbose headers   'x-cache-hits': '0',
39 verbose headers   'x-timer': 'S1435147182.445065,VS0,VE383668' }
40 verbose request invalidating /Users/hassankhan/.npm/registry.npmjs.org/emojify.js on PUT
41 error publish Failed PUT 500
42 verbose stack Error: unexpected status code: 401 : emojify.js
42 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:247:14)
42 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:170:14)
42 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:354:22)
42 verbose stack     at Request.emit (events.js:110:17)
42 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1207:14)
42 verbose stack     at Request.emit (events.js:129:20)
42 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1153:12)
42 verbose stack     at IncomingMessage.emit (events.js:129:20)
42 verbose stack     at _stream_readable.js:908:16
42 verbose stack     at process._tickCallback (node.js:355:11)
43 verbose statusCode 500
44 verbose pkgid emojify.js
45 verbose cwd /Volumes/Data HD/Projects/emojify.js
46 error Darwin 13.4.0
47 error argv "node" "/usr/local/bin/npm" "publish"
48 error node v0.12.5
49 error npm  v2.11.2
50 error code E500
51 error unexpected status code: 401 : emojify.js
52 error If you need help, you may report this error at:
52 error     <https://github.com/npm/npm/issues>
53 verbose exit [ 1, true ]
```

**Comment by theopak** [comment]
Should this be closed? I assume that you solved the issue, since emojify.js is now published on npm: https://www.npmjs.com/package/emojify.js

**Comment by hassankhan** [comment]
Yep, sorry, I'm pretty sure it was my own fault now, although I can't remember exactly what the issue was.
