### ISSUE TITLE
aspnet generator won't install / isn't recognized

### ISSUE THREAD

**Issue by wayneeusa** [npm/npm#8664]
I just can't read any more or look anything more up until I get some sleep.
But it anyone could read this log and give constructive input, much appreciated:
```
0 info it worked if it ends with ok
1 verbose cli [ 'node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'generator-aspnet' ]
2 info using npm@2.11.3
3 info using node@v0.12.5
4 verbose install initial load of /usr/local/lib/package.json
5 verbose readDependencies loading dependencies from /usr/local/lib/package.json
6 silly cache add args [ 'generator-aspnet', null ]
7 verbose cache add spec generator-aspnet
8 silly cache add parsed spec { raw: 'generator-aspnet',
8 silly cache add   scope: null,
8 silly cache add   name: 'generator-aspnet',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: '*',
8 silly cache add   type: 'range' }
9 silly addNamed generator-aspnet@*
10 verbose addNamed "*" is a valid semver range for generator-aspnet
11 silly addNameRange { name: 'generator-aspnet', range: '*', hasData: false }
12 silly mapToRegistry name generator-aspnet
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/generator-aspnet
16 verbose addNameRange registry:https://registry.npmjs.org/generator-aspnet not in flight; fetching
17 verbose request uri https://registry.npmjs.org/generator-aspnet
18 verbose request no auth needed
19 info attempt registry request try #1 at 3:42:18 PM
20 verbose request id e4ff0cbf6a4ef09c
21 verbose etag "BND4LVULPVKI94H1LVA56XSCH"
22 http request GET https://registry.npmjs.org/generator-aspnet
23 http 304 https://registry.npmjs.org/generator-aspnet
24 silly get cb [ 304,
24 silly get   { date: 'Wed, 24 Jun 2015 20:42:19 GMT',
24 silly get     via: '1.1 varnish',
24 silly get     'cache-control': 'max-age=60',
24 silly get     etag: '"BND4LVULPVKI94H1LVA56XSCH"',
24 silly get     age: '22',
24 silly get     connection: 'keep-alive',
24 silly get     'x-served-by': 'cache-dfw1827-DFW',
24 silly get     'x-cache': 'HIT',
24 silly get     'x-cache-hits': '1',
24 silly get     'x-timer': 'S1435178539.572306,VS0,VE0',
24 silly get     vary: 'Accept' } ]
25 verbose etag https://registry.npmjs.org/generator-aspnet from cache
26 verbose get saving generator-aspnet to /home/wayne/.npm/registry.npmjs.org/generator-aspnet/.cache.json
27 silly addNameRange number 2 { name: 'generator-aspnet', range: '*', hasData: true }
28 silly addNameRange versions [ 'generator-aspnet',
28 silly addNameRange   [ '0.0.0',
28 silly addNameRange     '0.0.1',
28 silly addNameRange     '0.0.2',
28 silly addNameRange     '0.0.4',
28 silly addNameRange     '0.0.5',
28 silly addNameRange     '0.0.6',
28 silly addNameRange     '0.0.7',
28 silly addNameRange     '0.0.8',
28 silly addNameRange     '0.0.9',
28 silly addNameRange     '0.0.10',
28 silly addNameRange     '0.0.11',
28 silly addNameRange     '0.0.12',
28 silly addNameRange     '0.0.13',
28 silly addNameRange     '0.0.14',
28 silly addNameRange     '0.0.18',
28 silly addNameRange     '0.0.19',
28 silly addNameRange     '0.0.20',
28 silly addNameRange     '0.0.21',
28 silly addNameRange     '0.0.22',
28 silly addNameRange     '0.0.23',
28 silly addNameRange     '0.0.24',
28 silly addNameRange     '0.0.25',
28 silly addNameRange     '0.0.26',
28 silly addNameRange     '0.0.27',
28 silly addNameRange     '0.0.28',
28 silly addNameRange     '0.0.29',
28 silly addNameRange     '0.0.30',
28 silly addNameRange     '0.0.31',
28 silly addNameRange     '0.0.32',
28 silly addNameRange     '0.0.33',
28 silly addNameRange     '0.0.34',
28 silly addNameRange     '0.0.35' ] ]
29 silly addNamed generator-aspnet@0.0.35
30 verbose addNamed "0.0.35" is a plain semver version for generator-aspnet
31 silly cache afterAdd generator-aspnet@0.0.35
32 verbose afterAdd /home/wayne/.npm/generator-aspnet/0.0.35/package/package.json not in flight; writing
33 verbose afterAdd /home/wayne/.npm/generator-aspnet/0.0.35/package/package.json written
34 silly install resolved [ { name: 'generator-aspnet',
34 silly install resolved     version: '0.0.35',
34 silly install resolved     description: 'Yeoman generator for ASP.NET 5 apps',
34 silly install resolved     license: 'Apache License 2.0',
34 silly install resolved     main: 'app/index.js',
34 silly install resolved     repository:
34 silly install resolved      { type: 'git',
34 silly install resolved        url: 'git+https://github.com/OmniSharp/generator-aspnet.git' },
34 silly install resolved     contributors: [ [Object], [Object], [Object], [Object], [Object], [Object] ],
34 silly install resolved     engines: { node: '>=0.10.0' },
34 silly install resolved     keywords: [ 'yeoman-generator', 'ASP.NET', 'aspnet', 'ASP', 'net', 'vNext' ],
34 silly install resolved     dependencies:
34 silly install resolved      { chai: '^1.10.0',
34 silly install resolved        chalk: '^1.0.0',
34 silly install resolved        uuid: '^2.0.1',
34 silly install resolved        'yeoman-generator': '^0.19.0',
34 silly install resolved        yosay: '^1.0.0' },
34 silly install resolved     devDependencies: { mocha: '^2.2.1' },
34 silly install resolved     scripts: { test: 'mocha' },
34 silly install resolved     gitHead: 'e1b4cf7a35be6340df1a497634f936a2b0dec4ce',
34 silly install resolved     bugs: { url: 'https://github.com/OmniSharp/generator-aspnet/issues' },
34 silly install resolved     homepage: 'https://github.com/OmniSharp/generator-aspnet',
34 silly install resolved     _id: 'generator-aspnet@0.0.35',
34 silly install resolved     _shasum: '083f8155e7490b2c9e0c9981f2ed86428a968872',
34 silly install resolved     _from: 'generator-aspnet@*',
34 silly install resolved     _npmVersion: '1.4.28',
34 silly install resolved     _npmUser: { name: 'sayedha', email: 'sayed.hashimi@gmail.com' },
34 silly install resolved     maintainers: [ [Object], [Object] ],
34 silly install resolved     dist:
34 silly install resolved      { shasum: '083f8155e7490b2c9e0c9981f2ed86428a968872',
34 silly install resolved        tarball: 'http://registry.npmjs.org/generator-aspnet/-/generator-aspnet-0.0.35.tgz' },
34 silly install resolved     directories: {},
34 silly install resolved     _resolved: 'https://registry.npmjs.org/generator-aspnet/-/generator-aspnet-0.0.35.tgz',
34 silly install resolved     readme: 'ERROR: No README data found!' } ]
35 info install generator-aspnet@0.0.35 into /usr/local/lib
36 info installOne generator-aspnet@0.0.35
37 verbose installOne of generator-aspnet to /usr/local/lib not in flight; installing
38 warn locking Error: EACCES, open '/home/wayne/.npm/_locks/generator-aspnet-b9cbfe278f2983cc.lock'
38 warn locking     at Error (native)
38 warn locking  /home/wayne/.npm/_locks/generator-aspnet-b9cbfe278f2983cc.lock failed { [Error: EACCES, open '/home/wayne/.npm/_locks/generator-aspnet-b9cbfe278f2983cc.lock']
38 warn locking   errno: -13,
38 warn locking   code: 'EACCES',
38 warn locking   path: '/home/wayne/.npm/_locks/generator-aspnet-b9cbfe278f2983cc.lock' }
39 verbose stack Error: Attempt to unlock /usr/local/lib/node_modules/generator-aspnet, which hasn't been locked
39 verbose stack     at unlock (/usr/local/lib/node_modules/npm/lib/utils/locker.js:66:11)
39 verbose stack     at cb (/usr/local/lib/node_modules/npm/lib/install.js:1017:5)
39 verbose stack     at /usr/local/lib/node_modules/npm/lib/install.js:1021:20
39 verbose stack     at /usr/local/lib/node_modules/npm/lib/utils/locker.js:40:9
39 verbose stack     at cb (/usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:149:38)
39 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:177:38
39 verbose stack     at FSReqWrap.oncomplete (fs.js:95:15)
40 verbose cwd /home/wayne
41 error Linux 3.16.0-031600-generic
42 error argv "node" "/usr/local/bin/npm" "install" "-g" "generator-aspnet"
43 error node v0.12.5
44 error npm  v2.11.3
45 error Attempt to unlock /usr/local/lib/node_modules/generator-aspnet, which hasn't been locked
46 error If you need help, you may report this error at:
46 error     <https://github.com/npm/npm/issues>
47 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
@wayneeusa Have you tried?:

``` sh
$ sudo chown -R $(whoami) "$HOME/.npm"
```

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
