### ISSUE TITLE
npm search give errors. I cannot figure it out by myself.

### ISSUE THREAD

**Issue by hackrole** [npm/npm#8671]
the debug file is: 

``````
➜  ~  cat npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'search', 'angular' ]
2 info using npm@2.11.2
3 info using node@v0.12.2
4 verbose node symlink /usr/local/bin/node
5 verbose config Skipping project config: /Users/daipeng/.npmrc. (matches userconfig)
6 silly mapToRegistry name -/all
7 silly mapToRegistry using default registry
8 silly mapToRegistry registry https://registry.npm.taobao.org/
9 silly mapToRegistry uri https://registry.npm.taobao.org/-/all
10 info updateIndex /Users/daipeng/.npm/registry.npm.taobao.org/-/all/.cache.json
11 warn Building the local index for the first time, please be patient
12 silly update-index fetching https://registry.npm.taobao.org/-/all
13 verbose request uri https://registry.npm.taobao.org/-/all
14 verbose request no auth needed
15 info attempt registry request try #1 at 17:15:56
16 verbose request id 36f42d026882475f
17 http request GET https://registry.npm.taobao.org/-/all
18 http 200 https://registry.npm.taobao.org/-/all
19 verbose headers { server: 'nginx/1.1.19',
19 verbose headers   date: 'Thu, 25 Jun 2015 09:15:58 GMT',
19 verbose headers   'content-type': 'application/json; charset=utf-8',
19 verbose headers   'transfer-encoding': 'chunked',
19 verbose headers   connection: 'keep-alive',
19 verbose headers   etag: '"+5sGCUq9spw+DkieoiBylA=="',
19 verbose headers   'x-readtime': '2027',
19 verbose headers   'content-encoding': 'gzip' }
20 verbose stack Error: true true: -/all
20 verbose stack     at CachingRegistryClient.<anonymous> (/Users/daipeng/app/nodejs0.12.2/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:247:14)
20 verbose stack     at /Users/daipeng/app/nodejs0.12.2/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:176:7
20 verbose stack     at Gunzip.onEnd (zlib.js:227:5)
20 verbose stack     at Gunzip.emit (events.js:129:20)
20 verbose stack     at _stream_readable.js:908:16
20 verbose stack     at process._tickCallback (node.js:355:11)
21 verbose statusCode 200
22 verbose cwd /Users/daipeng
23 error Darwin 13.4.0
24 error argv "node" "/usr/local/bin/npm" "search" "angular"
25 error node v0.12.2
26 error npm  v2.11.2
27 error code E200
28 error true true: -/all
29 error If you need help, you may report this error at:
29 error     <https://github.com/npm/npm/issues>
30 verbose exit [ 1, true ]```
``````

**Comment by magic4u** [comment]
I got the same error msg when excuting the npm search command, while works well when excuting npm install

**Comment by hackrole** [comment]
the install is  too slow, I wait for hours, then cancel it for no paition any more.
