### ISSUE TITLE
unexpected error #function

### ISSUE THREAD

**Issue by Shirish2015** [npm/npm#8703]
tmp/a1578d40-1c27-11e5-b3b1-c7a4df3ab681/Node Application/app.js:62
function ReturnLabelsOfCheckboxes( index){
^^^^^^^^
SyntaxError: Unexpected token function
    at Module._compile (module.js:437:25)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.runMain (module.js:492:10)
    at process.startup.processNextTick.process._tickCallback (node.js:244:9)

Execution Time-214ms

**Comment by Shirish2015** [comment]
please help me...

**Comment by othiym23** [comment]
Like your other ticket, this isn't obviously an issue with npm, but is instead a general-purpose Node question. Good luck getting it figured out, but this issue tracker can't really help you out!
