### ISSUE TITLE
npm install fails for phatomjs, maybe others

### ISSUE THREAD

**Issue by davidbhoward** [npm/npm#8757]
We have a dockerfile that creates an image by downloading and installing nodejs then installs phantomjs via npm (npm install -g phantomjs).  npm started to fail this morning because I am getting a "This request requires auth credentials. Run `npm login` and repeat the request."  

Nothing has changed in my CI environment and this job just started to fail.  Is there something that changed or is this a new issue?

**Comment by davidbhoward** [comment]
Here is the debug log:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'install', '-g', 'phantomjs' ]
2 info using npm@2.11.2
3 info using node@v0.12.5
4 verbose node symlink /usr/bin/node
5 verbose install initial load of /usr/lib/package.json
6 verbose readDependencies loading dependencies from /usr/lib/package.json
7 silly cache add args [ 'phantomjs', null ]
8 verbose cache add spec phantomjs
9 silly cache add parsed spec { raw: 'phantomjs',
9 silly cache add   scope: null,
9 silly cache add   name: 'phantomjs',
9 silly cache add   rawSpec: '',
9 silly cache add   spec: '*',
9 silly cache add   type: 'range' }
10 silly addNamed phantomjs@*
11 verbose addNamed "*" is a valid semver range for phantomjs
12 silly addNameRange { name: 'phantomjs', range: '*', hasData: false }
13 silly mapToRegistry name phantomjs
14 silly mapToRegistry using default registry
15 silly mapToRegistry registry https://registry.npmjs.org/
16 silly mapToRegistry uri https://registry.npmjs.org/phantomjs
17 verbose addNameRange registry:https://registry.npmjs.org/phantomjs not in flight; fetching
18 verbose request uri https://registry.npmjs.org/phantomjs
19 verbose request always-auth set; sending authorization
20 info attempt registry request try #1 at 17:17:10
21 info retry will retry, error on last attempt: Error: This request requires auth credentials. Run `npm login` and repeat the request.
22 info attempt registry request try #2 at 17:17:20
23 info retry will retry, error on last attempt: Error: This request requires auth credentials. Run `npm login` and repeat the request.
24 info attempt registry request try #3 at 17:18:20
25 verbose stack Error: This request requires auth credentials. Run `npm login` and repeat the request.
25 verbose stack     at CachingRegistryClient.authify (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/authify.js:17:14)
25 verbose stack     at CachingRegistryClient.makeRequest (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:101:17)
25 verbose stack     at /usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:65:17
25 verbose stack     at RetryOperation._fn (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/attempt.js:18:5)
25 verbose stack     at null._onTimeout (/usr/lib/node_modules/npm/node_modules/retry/lib/retry_operation.js:32:10)
25 verbose stack     at Timer.listOnTimeout (timers.js:119:15)
26 verbose cwd /
27 error Linux 3.10.0-123.6.3.el7.x86_64
28 error argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "phantomjs"
29 error node v0.12.5
30 error npm  v2.11.2
31 error This request requires auth credentials. Run `npm login` and repeat the request.
32 error If you need help, you may report this error at:
32 error     <https://github.com/npm/npm/issues>
33 verbose exit [ 1, true ]

**Comment by davidbhoward** [comment]
I am pretty sure this is wrong: verbose request always-auth set; sending authorization

**Comment by davidbhoward** [comment]
This was my issue having set environment variable in my Dockerfile to "npm_config_always_auth=false".  Thanks.
