### ISSUE TITLE
npm link error using node v0.12.5 and npm v3.0.0

### ISSUE THREAD

**Issue by tjunghans** [npm/npm#8766]
When running `npm link` I receive the following error (npm-debug.log):

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\dev\\tools\\node\\node.exe',
1 verbose cli   'C:\\dev\\tools\\node\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'link',
1 verbose cli   'component-to-link' ]
2 info using npm@3.0.0
3 info using node@v0.12.5
4 verbose stack Error: Argument #2: Expected array but got string
4 verbose stack     at EventEmitter.install (C:\dev\tools\node\node_modules\npm\lib\install.js:167:3)
4 verbose stack     at Object.commandCache.(anonymous function) (C:\dev\tools\node\node_modules\npm\lib\npm.js:207:13)
4 verbose stack     at C:\dev\tools\node\node_modules\npm\lib\link.js:88:29
4 verbose stack     at FSReqWrap.oncomplete (evalmachine.<anonymous>:95:15)
5 verbose cwd C:\dev\projects\component-that-links
6 error Windows_NT 6.1.7601
7 error argv "C:\\dev\\tools\\node\\node.exe" "C:\\dev\\tools\\node\\node_modules\\npm\\bin\\npm-cli.js" "link" "component-to-link"
8 error node v0.12.5
9 error npm  v3.0.0
10 error code EINVALIDTYPE
11 error typeerror Error: Argument #2: Expected array but got string
11 error typeerror     at EventEmitter.install (C:\dev\tools\node\node_modules\npm\lib\install.js:167:3)
11 error typeerror     at Object.commandCache.(anonymous function) (C:\dev\tools\node\node_modules\npm\lib\npm.js:207:13)
11 error typeerror     at C:\dev\tools\node\node_modules\npm\lib\link.js:88:29
11 error typeerror     at FSReqWrap.oncomplete (evalmachine.<anonymous>:95:15)
11 error typeerror This is an error with npm itself. Please report this error at:
11 error typeerror     <http://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
```

**Comment by iarna** [comment]
This change is now in master and will be in the 3.1.0 release this week.

**Comment by tjunghans** [comment]
Pure awesomeness :+1:
