### ISSUE TITLE
`npm install --save` with invalid package.json exits with weird error

### ISSUE THREAD

**Issue by nathan7** [npm/npm#8769]
with no --save:
```
npm ERR! Linux 4.0.5-1-ARCH
npm ERR! argv "/home/nathan/.nave/installed/1.6.2/bin/iojs" "/home/nathan/npm/bin/npm" "i" "express"
npm ERR! node v1.6.2
npm ERR! npm  v3.0.0
npm ERR! file /home/nathan/work/lsq/api/package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Unexpected token 'd' at 4:4
npm ERR!   "dependencies": {
npm ERR!    ^
npm ERR! File: /home/nathan/work/lsq/api/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR! 
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     /home/nathan/work/lsq/api/npm-debug.log
```

with --save:
```
0 info it worked if it ends with ok
1 verbose cli [ '/home/nathan/.nave/installed/1.6.2/bin/iojs',
1 verbose cli   '/home/nathan/npm/bin/npm',
1 verbose cli   'i',
1 verbose cli   '-S',
1 verbose cli   'express' ]
2 info using npm@3.0.0
3 info using node@v1.6.2
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly rollbackFailedOptional Starting
8 silly rollbackFailedOptional Finishing
9 silly runTopLevelLifecycles Starting
10 silly runTopLevelLifecycles Finishing
11 silly install saveToDependencies
12 verbose stack Error: Missing required argument #2
12 verbose stack     at exports.saveRequested (/home/nathan/src/github.com/npm/npm/lib/install/save.js:18:3)
12 verbose stack     at Object.Installer.saveToDependencies (/home/nathan/src/github.com/npm/npm/lib/install.js:502:3)
12 verbose stack     at Array.<anonymous> (/home/nathan/src/github.com/npm/npm/node_modules/slide/lib/bind-actor.js:15:8)
12 verbose stack     at LOOP (/home/nathan/src/github.com/npm/npm/node_modules/slide/lib/chain.js:15:14)
12 verbose stack     at /home/nathan/src/github.com/npm/npm/node_modules/slide/lib/chain.js:18:7
12 verbose stack     at Object.Installer.finishTracker (/home/nathan/src/github.com/npm/npm/lib/install.js:279:3)
12 verbose stack     at Array.<anonymous> (/home/nathan/src/github.com/npm/npm/node_modules/slide/lib/bind-actor.js:15:8)
12 verbose stack     at LOOP (/home/nathan/src/github.com/npm/npm/node_modules/slide/lib/chain.js:15:14)
12 verbose stack     at /home/nathan/src/github.com/npm/npm/node_modules/slide/lib/chain.js:18:7
12 verbose stack     at Object.Installer.runTopLevelLifecycles (/home/nathan/src/github.com/npm/npm/lib/install.js:475:28)
13 verbose cwd /home/nathan/work/lsq/api
14 error Linux 4.0.5-1-ARCH
15 error argv "/home/nathan/.nave/installed/1.6.2/bin/iojs" "/home/nathan/npm/bin/npm" "i" "-S" "express"
16 error node v1.6.2
17 error npm  v3.0.0
18 error code EMISSINGARG
19 error typeerror Error: Missing required argument #2
19 error typeerror     at exports.saveRequested (/home/nathan/src/github.com/npm/npm/lib/install/save.js:18:3)
19 error typeerror     at Object.Installer.saveToDependencies (/home/nathan/src/github.com/npm/npm/lib/install.js:502:3)
19 error typeerror     at Array.<anonymous> (/home/nathan/src/github.com/npm/npm/node_modules/slide/lib/bind-actor.js:15:8)
19 error typeerror     at LOOP (/home/nathan/src/github.com/npm/npm/node_modules/slide/lib/chain.js:15:14)
19 error typeerror     at /home/nathan/src/github.com/npm/npm/node_modules/slide/lib/chain.js:18:7
19 error typeerror     at Object.Installer.finishTracker (/home/nathan/src/github.com/npm/npm/lib/install.js:279:3)
19 error typeerror     at Array.<anonymous> (/home/nathan/src/github.com/npm/npm/node_modules/slide/lib/bind-actor.js:15:8)
19 error typeerror     at LOOP (/home/nathan/src/github.com/npm/npm/node_modules/slide/lib/chain.js:15:14)
19 error typeerror     at /home/nathan/src/github.com/npm/npm/node_modules/slide/lib/chain.js:18:7
19 error typeerror     at Object.Installer.runTopLevelLifecycles (/home/nathan/src/github.com/npm/npm/lib/install.js:475:28)
19 error typeerror This is an error with npm itself. Please report this error at:
19 error typeerror     <http://github.com/npm/npm/issues>
20 verbose exit [ 1, true ]
```

**Comment by iarna** [comment]
Fixed in 8c9fe9c – this'll land in 3.1.0 this Thursday.
