### ISSUE TITLE
win7 32 NPM install ionic error :stack Error: unexpected eof

### ISSUE THREAD

**Issue by terry19850829** [npm/npm#8785]
```
830 verbose about to build C:\Users\zhujian\AppData\Roaming\npm\node_modules\ionic
50831 verbose unlock done using C:\Users\zhujian\AppData\Roaming\npm-cache\_locks\ionic-37158bbdf7f29156.lock for C:\Users\zhujian\AppData\Roaming\npm\node_modules\ionic
50832 verbose fstream_class Extract
50833 verbose stack Error: unexpected eof
50833 verbose stack     at decorate (F:\dev_Tools\nodejs\node_modules\npm\node_modules\fstream\lib\abstract.js:67:36)
50833 verbose stack     at Extract.Abstract.error (F:\dev_Tools\nodejs\node_modules\npm\node_modules\fstream\lib\abstract.js:61:12)
50833 verbose stack     at Extract._streamEnd (F:\dev_Tools\nodejs\node_modules\npm\node_modules\tar\lib\extract.js:91:35)
50833 verbose stack     at BlockStream.<anonymous> (F:\dev_Tools\nodejs\node_modules\npm\node_modules\tar\lib\parse.js:51:8)
50833 verbose stack     at BlockStream.emit (events.js:104:17)
50833 verbose stack     at BlockStream._emitChunk (F:\dev_Tools\nodejs\node_modules\npm\node_modules\block-stream\block-stream.js:203:10)
50833 verbose stack     at BlockStream.flush (F:\dev_Tools\nodejs\node_modules\npm\node_modules\block-stream\block-stream.js:70:8)
50833 verbose stack     at BlockStream.end (F:\dev_Tools\nodejs\node_modules\npm\node_modules\block-stream\block-stream.js:66:8)
50833 verbose stack     at Extract.Parse.end (F:\dev_Tools\nodejs\node_modules\npm\node_modules\tar\lib\parse.js:86:23)
50833 verbose stack     at Unzip.onend (_stream_readable.js:505:10)
50834 verbose fstream_stack Extract._streamEnd (F:\dev_Tools\nodejs\node_modules\npm\node_modules\tar\lib\extract.js:91:35)
50834 verbose fstream_stack BlockStream.<anonymous> (F:\dev_Tools\nodejs\node_modules\npm\node_modules\tar\lib\parse.js:51:8)
50834 verbose fstream_stack BlockStream.emit (events.js:104:17)
50834 verbose fstream_stack BlockStream._emitChunk (F:\dev_Tools\nodejs\node_modules\npm\node_modules\block-stream\block-stream.js:203:10)
50834 verbose fstream_stack BlockStream.flush (F:\dev_Tools\nodejs\node_modules\npm\node_modules\block-stream\block-stream.js:70:8)
50834 verbose fstream_stack BlockStream.end (F:\dev_Tools\nodejs\node_modules\npm\node_modules\block-stream\block-stream.js:66:8)
50834 verbose fstream_stack Extract.Parse.end (F:\dev_Tools\nodejs\node_modules\npm\node_modules\tar\lib\parse.js:86:23)
50834 verbose fstream_stack Unzip.onend (_stream_readable.js:505:10)
50835 verbose cwd C:\Windows\system32
```

**Comment by KenanY** [comment]
@terry19850829 Could you upload the _full_ log as a [gist](https://gist.github.com/)?

**Comment by terry19850829** [comment]
@KenanY I have resolved this issue.Because I work behind my company network proxy.I just config that.It worked .Thank you for your feedback.

**Comment by terry19850829** [comment]
@KenanY I have resolved this issue.Because I work behind my company network proxy.I just config that.It worked .Thank you for your feedback.
