### ISSUE TITLE
Unable to download brace-expansion from npm behind Nexus 2.11.3-01

### ISSUE THREAD

**Issue by ptitgraig** [npm/npm#8787]
Hello.

This is my current configuration;
Windows 7
Using Sonatype Nexus 2.11.3-01 with a corporate proxy.
Nexus is listening on 8081 port and served on my machine on localhost.
My `.npmrc` has the following settings:
`registry = http://localhost:8081/content/groups/npm-all/`

In cmd.exe, i type `npm install wrappy` and it works fine.
When i type `npm install brace-expansion` i get the following error:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\PBapps\\nodejs\\\\node.exe',
1 verbose cli   'C:\\PBapps\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'brace-expansion',
1 verbose cli   '--loglevel=verbose' ]
2 info using npm@2.7.5
3 info using node@v0.10.24
4 verbose node symlink C:\PBapps\nodejs\\node.exe
5 warn package.json ppeAgence-angular-version@1.0.0 No repository field.
6 silly cache add args [ 'brace-expansion', null ]
7 verbose cache add spec brace-expansion
8 silly cache add parsed spec { raw: 'brace-expansion',
8 silly cache add   scope: null,
8 silly cache add   name: 'brace-expansion',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: '*',
8 silly cache add   type: 'range' }
9 verbose addNamed brace-expansion@*
10 silly addNamed semver.valid null
11 silly addNamed semver.validRange *
12 silly addNameRange { name: 'brace-expansion', range: '*', hasData: false }
13 silly mapToRegistry name brace-expansion
14 silly mapToRegistry using default registry
15 silly mapToRegistry registry http://localhost:8081/content/groups/npm-all/
16 silly mapToRegistry uri http://localhost:8081/content/groups/npm-all/brace-expansion
17 verbose addNameRange registry:http://localhost:8081/content/groups/npm-all/brace-expansion not in flight; fetching
18 verbose request uri http://localhost:8081/content/groups/npm-all/brace-expansion
19 verbose request no auth needed
20 info attempt registry request try #1 at 17:06:05
21 verbose request id e6bb7df9d52bf776
22 http request GET http://localhost:8081/content/groups/npm-all/brace-expansion
23 http 200 http://localhost:8081/content/groups/npm-all/brace-expansion
24 silly get cb [ 200,
24 silly get   { date: 'Tue, 30 Jun 2015 15:06:05 GMT',
24 silly get     server: 'Nexus/2.11.2-06',
24 silly get     'x-frame-options': 'SAMEORIGIN',
24 silly get     'x-content-type-options': 'nosniff',
24 silly get     'accept-ranges': 'bytes',
24 silly get     'content-type': 'application/json',
24 silly get     'last-modified': 'Tue, 30 Jun 2015 15:06:05 GMT',
24 silly get     'content-length': '9745' } ]
25 verbose get saving brace-expansion to c:\PBapps\npm-cache\localhost_8081\content\groups\npm-all\brace-expansion\.cache.json
26 silly addNameRange number 2 { name: 'brace-expansion', range: '*', hasData: true }
27 silly addNameRange versions [ 'brace-expansion', [ '0.0.0', '1.0.0', '1.0.1', '1.1.0' ] ]
28 verbose addNamed brace-expansion@1.1.0
29 silly addNamed semver.valid 1.1.0
30 silly addNamed semver.validRange 1.1.0
31 silly mapToRegistry name brace-expansion
32 silly mapToRegistry using default registry
33 silly mapToRegistry registry http://localhost:8081/content/groups/npm-all/
34 silly mapToRegistry uri http://localhost:8081/content/groups/npm-all/brace-expansion
35 verbose addRemoteTarball http://localhost:8081/content/groups/npm-all/brace-expansion/-/brace-expansion-1.1.0.tgz not in flight; adding
36 verbose addRemoteTarball [ 'http://localhost:8081/content/groups/npm-all/brace-expansion/-/brace-expansion-1.1.0.tgz',
36 verbose addRemoteTarball   'c9b7d03c03f37bc704be100e522b40db8f6cfcd9' ]
37 info retry fetch attempt 1 at 17:06:05
38 info attempt registry request try #1 at 17:06:05
39 http fetch GET http://localhost:8081/content/groups/npm-all/brace-expansion/-/brace-expansion-1.1.0.tgz
40 http fetch 404 http://localhost:8081/content/groups/npm-all/brace-expansion/-/brace-expansion-1.1.0.tgz
41 error fetch failed http://localhost:8081/content/groups/npm-all/brace-expansion/-/brace-expansion-1.1.0.tgz
42 warn retry will retry, error on last attempt: Error: fetch failed with status code 404
43 info retry fetch attempt 2 at 17:06:15
44 info attempt registry request try #1 at 17:06:15
45 http fetch GET http://localhost:8081/content/groups/npm-all/brace-expansion/-/brace-expansion-1.1.0.tgz
46 http fetch 404 http://localhost:8081/content/groups/npm-all/brace-expansion/-/brace-expansion-1.1.0.tgz
47 error fetch failed http://localhost:8081/content/groups/npm-all/brace-expansion/-/brace-expansion-1.1.0.tgz
48 warn retry will retry, error on last attempt: Error: fetch failed with status code 404
49 info retry fetch attempt 3 at 17:07:15
50 info attempt registry request try #1 at 17:07:15
51 http fetch GET http://localhost:8081/content/groups/npm-all/brace-expansion/-/brace-expansion-1.1.0.tgz
52 http fetch 404 http://localhost:8081/content/groups/npm-all/brace-expansion/-/brace-expansion-1.1.0.tgz
53 error fetch failed http://localhost:8081/content/groups/npm-all/brace-expansion/-/brace-expansion-1.1.0.tgz
54 verbose stack Error: fetch failed with status code 404
54 verbose stack     at Request.<anonymous> (C:\PBapps\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\fetch.js:51:14)
54 verbose stack     at Request.EventEmitter.emit (events.js:95:17)
54 verbose stack     at Request.onRequestResponse (C:\PBapps\nodejs\node_modules\npm\node_modules\request\request.js:1139:10)
54 verbose stack     at ClientRequest.EventEmitter.emit (events.js:95:17)
54 verbose stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1688:21)
54 verbose stack     at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:121:23)
54 verbose stack     at Socket.socketOnData [as ondata] (http.js:1583:20)
54 verbose stack     at TCP.onread (net.js:525:27)
55 verbose cwd C:\dev\pfe\checkout\angular-version
56 error Windows_NT 6.1.7601
57 error argv "C:\\PBapps\\nodejs\\\\node.exe" "C:\\PBapps\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "brace-expansion" "--loglevel=verbose"
58 error node v0.10.24
59 error npm  v2.7.5
60 error fetch failed with status code 404
61 error If you need help, you may report this error at:
61 error     <https://github.com/npm/npm/issues>
62 verbose exit [ 1, true ]
```

Since I don't know much where it comes from, I've open an issue on SonaType:
https://support.sonatype.com/requests/9417
And on the node module repo itself:
https://github.com/juliangruber/brace-expansion/issues/5

This is working with other package (such as wrappy)

Any help is welcome.

Regards.

**Comment by ptitgraig** [comment]
Hello
After some investigation, the problems comes from my corporate proxy that blocks the `generate.sh` file. You can close the issue.

**Comment by KenanY** [comment]
@ptitgraig You should be able to close this issue since you are the author of it. If anything, this comment will serve as a ping to the `npm` team to close this :)

**Comment by ehsalazar** [comment]
Good to hear. I'll close this for now as we’re trying to clean up some old issues. We’ll be happy to reopen if necessary.
