### ISSUE TITLE
NPM not working. Object #<process> has no method 'getuid'

### ISSUE THREAD

**Issue by vspin** [npm/npm#8798]
Windows 8.1 Pro 64-bit

I installed node 64-bit (tried 32-bit as well) and I'm getting this:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\USERS\\COMPUTER\\APPDATA\\LOCAL\\MICROSOFT\\WEBMATRIX\\EXTENSIONS\\30\\TypeScript4WebMatrix\\node.exe',
1 verbose cli   'C:\\USERS\\COMPUTER\\APPDATA\\LOCAL\\MICROSOFT\\WEBMATRIX\\EXTENSIONS\\30\\TypeScript4WebMatrix\\node_modules\\npm\\cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'typescript' ]
2 info using npm@2.12.0
3 info using node@v0.8.11
4 verbose install initial load of C:\USERS\COMPUTER\APPDATA\LOCAL\MICROSOFT\WEBMATRIX\EXTENSIONS\30\TypeScript4WebMatrix\package.json
5 verbose readDependencies loading dependencies from C:\USERS\COMPUTER\APPDATA\LOCAL\MICROSOFT\WEBMATRIX\EXTENSIONS\30\TypeScript4WebMatrix\package.json
6 silly cache add args [ 'typescript', null ]
7 verbose cache add spec typescript
8 silly cache add parsed spec { raw: 'typescript',
8 silly cache add   scope: null,
8 silly cache add   name: 'typescript',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: '*',
8 silly cache add   type: 'range' }
9 silly addNamed typescript@*
10 verbose addNamed "*" is a valid semver range for typescript
11 silly addNameRange { name: 'typescript', range: '*', hasData: false }
12 silly mapToRegistry name typescript
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/typescript
16 verbose addNameRange registry:https://registry.npmjs.org/typescript not in flight; fetching
17 verbose request uri https://registry.npmjs.org/typescript
18 verbose request no auth needed
19 info attempt registry request try #1 at 19:32:22
20 verbose request id 672d0cec9644ba42
21 http request GET https://registry.npmjs.org/typescript
22 http 200 https://registry.npmjs.org/typescript
23 silly get cb [ 200,
23 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
23 silly get     etag: '"1FJRGLNQY31MIG83BVX3E16I7"',
23 silly get     'content-type': 'application/json',
23 silly get     'cache-control': 'max-age=60',
23 silly get     'content-length': '25258',
23 silly get     'accept-ranges': 'bytes',
23 silly get     date: 'Thu, 02 Jul 2015 02:32:19 GMT',
23 silly get     via: '1.1 varnish',
23 silly get     age: '30',
23 silly get     connection: 'keep-alive',
23 silly get     'x-served-by': 'cache-lax1426-LAX',
23 silly get     'x-cache': 'HIT',
23 silly get     'x-cache-hits': '1',
23 silly get     'x-timer': 'S1435804339.322041,VS0,VE0',
23 silly get     vary: 'Accept' } ]
24 verbose get saving typescript to C:\Users\Computer\AppData\Roaming\npm-cache\registry.npmjs.org\typescript\.cache.json
25 verbose type undefined_method
26 verbose stack TypeError: Object #<process> has no method 'getuid'
26 verbose stack     at calculateOwner (C:\USERS\COMPUTER\APPDATA\LOCAL\MICROSOFT\WEBMATRIX\EXTENSIONS\30\TypeScript4WebMatrix\node_modules\npm\lib\utils\correct-mkdir.js:37:24)
26 verbose stack     at module.exports (C:\USERS\COMPUTER\APPDATA\LOCAL\MICROSOFT\WEBMATRIX\EXTENSIONS\30\TypeScript4WebMatrix\node_modules\npm\lib\utils\correct-mkdir.js:23:22)
26 verbose stack     at Object.oncomplete (evalmachine.<anonymous>:297:15)
27 verbose cwd C:\Users\Computer
28 error Windows_NT 6.2.9200
29 error argv "C:\\USERS\\COMPUTER\\APPDATA\\LOCAL\\MICROSOFT\\WEBMATRIX\\EXTENSIONS\\30\\TypeScript4WebMatrix\\node.exe" "C:\\USERS\\COMPUTER\\APPDATA\\LOCAL\\MICROSOFT\\WEBMATRIX\\EXTENSIONS\\30\\TypeScript4WebMatrix\\node_modules\\npm\\cli.js" "install" "-g" "typescript"
30 error node v0.8.11
31 error npm  v2.12.0
32 error Object #<process> has no method 'getuid'
33 error If you need help, you may report this error at:
33 error     <https://github.com/npm/npm/issues>
34 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
@vspin I believe this was fixed in [`2.12.1`](https://github.com/npm/npm/releases/tag/v2.12.1).

**Comment by vspin** [comment]
Yeah, I think your right. I've got it upgraded to 2.12.1 and Sublime Text 2 now works with Package Control, however, WebMatrix is a mess and I can't get it repaired. It has its own node/npm extensions and I can't seem to get them removed or updated. Did a full uninstall and reinstall. Ugg.

I'm surprised node is still offering the old npm..

**Comment by vspin** [comment]
Anyone know how to update npm on Webmatrix? The latest version it updates to is 2.12.0..

**Comment by vspin** [comment]
Well, since the is no longer an npm issue, I'm closing it.
