### ISSUE TITLE
(node) warning: possible EventEmitter memory leak detected Trace

### ISSUE THREAD

**Issue by anthonyjoanes** [npm/npm#8804]
Once installed node.js I tried to do an install for bower but got the following

```
(node) warning: possible EventEmitter memory leak detected. 11 pipe listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Request.addListener (events.js:179:15)
    at Request.init (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\request.js:667:8)
    at Redirect.onResponse (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\lib\redirect.js:149:11)
    at Request.onRequestResponse (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\request.js:1108:22)
    at ClientRequest.emit (events.js:107:17)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:426:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
    at Socket.socketOnData (_http_client.js:317:20)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
```
It does this for anything that I try to install via NPM

**Comment by KenanY** [comment]
@anthonyjoanes `npm --version`?

**Comment by anthonyjoanes** [comment]
2.10.1

**Comment by markvincze** [comment]
Did you find the solution for this issue?

**Comment by KenanY** [comment]
Closing as abandoned. Can reopen if this is still an issue with the latest stable release of `npm` (besides with `npm@3.10.7`, which suffers from https://github.com/npm/npm/issues/13656).
