### ISSUE TITLE
npm install: git fetch failed to connect to github.com port 443: Timed out, while git clone works.

### ISSUE THREAD

**Issue by Moozz** [npm/npm#8809]
I'm configuring a Jenkins server for Node project on Windows Server 2012. The problem occured when I add `npm install` to the build step.

I call

```
npm install --production --msvs_version=2013
```

and this error occured.

```
npm WARN package.json AppServer@1.18.0 No repository field.
npm WARN package.json AppServer@1.18.0 No README data
npm WARN package.json AppServer@1.18.0 No license field.
npm ERR! git fetch -a origin (https://github.com/yaronn/xmldom.git) fatal: unable to access 'https://github.com/yaronn/xmldom.git/': Failed to connect to github.com port 443: Timed out
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--production" "--msvs_version=2013"
npm ERR! node v0.10.36
npm ERR! npm  v2.12.1
npm ERR! code 128

npm ERR! Command failed: fatal: unable to access 'https://github.com/yaronn/xmldom.git/': Failed to connect to github.com port 443: Timed out
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Jenkins\jobs\AppServer-NodeJS-Modules\workspace\npm-debug.log
```

Seems like git can't access to github server. But when I try adding

```
git clone https://github.com/yaronn/xmldom.git
```

to just the line before `npm install`, xmldom is cloned to my workspace fine while `npm install` still fails.

I've already set proxy and https-proxy for npm and git.

Do you have any suggestion?

**Comment by Moozz** [comment]
It still occurs after updating npm to the latest version

**Comment by Moozz** [comment]
More info, the problem occurred when npm tried to install xml-crypto@0.0.21. The xml-crypto defined "xmldom": "git+https://github.com/yaronn/xmldom.git" as its dependency.

Running
    
    git clone https://github.com/yaronn/xmldom.git

works perfectly fine.

![image 013](https://cloud.githubusercontent.com/assets/1546794/8518509/f7d5fe98-23f4-11e5-8eea-76ea6ab29a77.png)

But

    npm install xml-crypto@0.0.21

fails.

![image 012](https://cloud.githubusercontent.com/assets/1546794/8518502/d9b9c002-23f4-11e5-97ce-0e2f26dab8c5.png)

**Comment by Moozz** [comment]
More info, I set APPDATA and USERPROFILE to D:\JenkinsHome\AppData and D:\JenkinsHome for some reasons.

It's back to work if I remove APPDATA and USERPROFILE and use the default values, which are C:\Users\Cloud\AppData\Roaming and C:\Users\Cloud.

I will use this workaround so It's fixed for me now.

Could this be considered as a bug?

**Comment by jurajcik** [comment]
I have exactly the same problem. 

Also behind a corporate proxy, `git clone` works but the command `git ls-remote --tags --heads https://github.com/angular/bower-angular-mocks.git`, which is called as part of `bower install` (from `npm install`) fails.

**Comment by PBartrina** [comment]
I'm having just the same issues, with APPDATA and USERPROFILE set to the default values:

```npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:203:12)
npm WARN addRemoteGit     at emitTwo (events.js:87:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:172:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:817:16)
npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:319:11)
npm WARN addRemoteGit     at emitOne (events.js:77:13)
npm WARN addRemoteGit     at Socket.emit (events.js:169:7)
npm WARN addRemoteGit     at Pipe._onclose (net.js:469:12)
npm WARN addRemoteGit  git://github.com/facebook/react.git#b4e74e38e43ac53af8acd62c78c9213be0194245 resetting remote C:\
Users\***\AppData\Roaming\npm-cache\_git-remotes\git-github-com-facebook-react-git-baa2986b because of error: { [Error:
 Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit ]
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
npm ERR! git clone --template=C:\Users\***\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/
facebook/react.git C:\Users\***\AppData\Roaming\npm-cache\_git-remotes\git-github-com-facebook-react-git-baa2986b: Clon
ing into bare repository 'C:\Users\***\AppData\Roaming\npm-cache\_git-remotes\git-github-com-facebook-react-git-baa2986
b'...
npm ERR! git clone --template=C:\Users\***\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/
facebook/react.git C:\Users\***\AppData\Roaming\npm-cache\_git-remotes\git-github-com-facebook-react-git-baa2986b: fata
l: unable to connect to github.com:
npm ERR! git clone --template=C:\Users\***\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/
facebook/react.git C:\Users\***\AppData\Roaming\npm-cache\_git-remotes\git-github-com-facebook-react-git-baa2986b: gith
ub.com[0: 192.30.252.130]: errno=No error
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-
cli.js" "install"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\***\AppData\Roaming\npm-cache\_git-remote
s\_templates --mirror git://github.com/facebook/react.git C:\Users\***\AppData\Roaming\npm-cache\_git-remotes\git-githu
b-com-facebook-react-git-baa2986b
npm ERR! Cloning into bare repository 'C:\Users\***\AppData\Roaming\npm-cache\_git-remotes\git-github-com-facebook-reac
t-git-baa2986b'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.252.130]: errno=No error
npm ERR!
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\***\react-native\npm-debug.log ```

And the log:

```3616 error git clone --template=C:\Users\***\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/facebook/react.git C:\Users\***\AppData\Roaming\npm-cache\_git-remotes\git-github-com-facebook-react-git-baa2986b: Cloning into bare repository 'C:\Users\***\AppData\Roaming\npm-cache\_git-remotes\git-github-com-facebook-react-git-baa2986b'...
3616 error git clone --template=C:\Users\***\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/facebook/react.git C:\Users\***\AppData\Roaming\npm-cache\_git-remotes\git-github-com-facebook-react-git-baa2986b: fatal: unable to connect to github.com:
3616 error git clone --template=C:\Users\***\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/facebook/react.git C:\Users\***\AppData\Roaming\npm-cache\_git-remotes\git-github-com-facebook-react-git-baa2986b: github.com[0: 192.30.252.130]: errno=No error
3617 verbose stack Error: Command failed: git -c core.longpaths=true clone --template=C:\Users\***\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/facebook/react.git C:\Users\***\AppData\Roaming\npm-cache\_git-remotes\git-github-com-facebook-react-git-baa2986b
3617 verbose stack Cloning into bare repository 'C:\Users\***\AppData\Roaming\npm-cache\_git-remotes\git-github-com-facebook-react-git-baa2986b'...
3617 verbose stack fatal: unable to connect to github.com:
3617 verbose stack github.com[0: 192.30.252.130]: errno=No error
3617 verbose stack
3617 verbose stack
3617 verbose stack     at ChildProcess.exithandler (child_process.js:203:12)
3617 verbose stack     at emitTwo (events.js:87:13)
3617 verbose stack     at ChildProcess.emit (events.js:172:7)
3617 verbose stack     at maybeClose (internal/child_process.js:817:16)
3617 verbose stack     at Socket.<anonymous> (internal/child_process.js:319:11)
3617 verbose stack     at emitOne (events.js:77:13)
3617 verbose stack     at Socket.emit (events.js:169:7)
3617 verbose stack     at Pipe._onclose (net.js:469:12)
3618 verbose cwd C:\Users\***\react-native
3619 error Windows_NT 6.1.7601
3620 error argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
3621 error node v4.1.1
3622 error npm  v2.14.4
3623 error code 128
3624 error Command failed: git -c core.longpaths=true clone --template=C:\Users\***\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/facebook/react.git C:\Users\***\AppData\Roaming\npm-cache\_git-remotes\git-github-com-facebook-react-git-baa2986b
3624 error Cloning into bare repository 'C:\Users\***\AppData\Roaming\npm-cache\_git-remotes\git-github-com-facebook-react-git-baa2986b'...
3624 error fatal: unable to connect to github.com:
3624 error github.com[0: 192.30.252.130]: errno=No error
3625 error If you need help, you may report this error at:
3625 error     <https://github.com/npm/npm/issues>
3626 verbose exit [ 1, true ]```

**Comment by PBartrina** [comment]
I solved it by running
```
git config --global url."https://".insteadOf git://`
```

which forces all connections to be via https

**Comment by simon-p-r** [comment]
Thanks @PBartrina this worked for me when trying to npm install private repos from github :+1:

**Comment by erperejildo** [comment]
Worked for me as well

**Comment by legodude17** [comment]
Any one still having this issue?

**Comment by rangelife** [comment]
Yes. It's a total pain. What the heck does it mean "Failed to connect to github.com port 443: Operation timed out"? Github is just fine. Is there any way to make it aggresively retry / extend the timeout?

**Comment by rangelife** [comment]
@PBartrina that git tweak will come in very handy, unfortunately doesn't fix this problem for me in this case- the failing repos are using https... (which, as in above posts, with git clone, is fine)

**Comment by legodude17** [comment]
@rangelife are you using a proxy or VPN? How is your internet connection?

**Comment by SoumyaSpecialProject** [comment]
I am still having the issue even if I have tried all the suggested solutions. 
On giving the command:
git clone https://github.com/RMerl/asuswrt-merlin.git
I am getting an error
fatal: unable to access 'https://github.com/RMerl/asuswrt-merlin.git/': Failed to connect to github.com port 443: Connection refused
And my system is behind the institute proxy.
Please suggest.

**Comment by legodude17** [comment]
So the git command itself failed?

**Comment by elangoyuva** [comment]
I am also facing same issues

 Failed to connect to github.com port 443:TIme Out.

**Comment by legodude17** [comment]
Does `git clone` work?

**Comment by BTMPL** [comment]
@legodude17 I'm running into the same issue when trying to install `osprey-router` - it has a dependency on  a package from git. `git clone` works OK, but with `npm install` it times out.

I'm behind a corporate proxy, set up the authentication for both http.proxy and https.proxy and did the `"https://".insteadOf git://` config.

**Comment by BTMPL** [comment]
Just an update - I was able to get around the issue. Turns out (on Windows) `npm` will try to grab the `.gitconfig` file from user homedir (by default `c:\Users\[username]\.gitconfig`) and will ignore the global config / personal config if placed i na different location. Copying the global config file to above mentioned location fixed the issue for me.

**Comment by Rithesh-Alora** [comment]
Thank you very much BTML.. Finally that worked for me !!!

**Comment by Crazier-qi** [comment]
it does not worked.Although i had runing that command
![image](https://user-images.githubusercontent.com/16120478/28489401-058fa4dc-6ef6-11e7-9bc0-c5106e755290.png)

**Comment by Crazier-qi** [comment]
I have met this problem when i running the command"hexo init"
![image](https://user-images.githubusercontent.com/16120478/28489431-5fbf858a-6ef6-11e7-8c5c-60b7782e28f4.png)
so what should i do ?
please help

**Comment by kailashrdave** [comment]
@BTMPL
You saved my day.
Thank you guys
I got the same errors as you all.
After setting proxy and replacing .gitconfig file, it worked for me .
Cheers
