### ISSUE TITLE
"npm install" log error

### ISSUE THREAD

**Issue by Hitesh-Batra** [npm/npm#8823]
Below is the log, while npm install, Please let me know whats the error as i am new to this.

```
C:\Bitnami\meanstack-3.0.4-0\projects\sample>npm install
npm http GET https://registry.npmjs.org/morgan
npm ERR! TypeError: Request path contains unescaped characters.
npm ERR!     at new ClientRequest (_http_client.js:73:11)
npm ERR!     at TunnelingAgent.exports.request (http.js:49:10)
npm ERR!     at TunnelingAgent.createSocket (C:\Bitnami\meanstack-3.0.4-0\nodejs
\node_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:117:25
)
npm ERR!     at TunnelingAgent.createSecureSocket [as createSocket] (C:\Bitnami\
meanstack-3.0.4-0\nodejs\node_modules\npm\node_modules\request\node_modules\tunn
el-agent\index.js:184:41)
npm ERR!     at TunnelingAgent.addRequest (C:\Bitnami\meanstack-3.0.4-0\nodejs\n
ode_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:80:8)
npm ERR!     at new ClientRequest (_http_client.js:154:16)
npm ERR!     at Object.exports.request (http.js:49:10)
npm ERR!     at Object.exports.request (https.js:136:15)
npm ERR!     at Request.start (C:\Bitnami\meanstack-3.0.4-0\nodejs\node_modules\
npm\node_modules\request\request.js:583:30)
npm ERR!     at Request.end (C:\Bitnami\meanstack-3.0.4-0\nodejs\node_modules\np
m\node_modules\request\request.js:1237:28)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Bitnami\\meanstack-3.0.4-0\\nodejs\\\\node.exe" "C:\\Bitna
mi\\meanstack-3.0.4-0\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd C:\Bitnami\meanstack-3.0.4-0\projects\sample
npm ERR! node -v v0.12.4
npm ERR! npm -v 1.4.3
npm http GET https://registry.npmjs.org/body-parser
npm ERR! TypeError: Request path contains unescaped characters.
npm ERR!     at new ClientRequest (_http_client.js:73:11)
npm ERR!     at TunnelingAgent.exports.request (http.js:49:10)
npm ERR!     at TunnelingAgent.createSocket (C:\Bitnami\meanstack-3.0.4-0\nodejs
\node_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:117:25
)
npm ERR!     at TunnelingAgent.createSecureSocket [as createSocket] (C:\Bitnami\
meanstack-3.0.4-0\nodejs\node_modules\npm\node_modules\request\node_modules\tunn
el-agent\index.js:184:41)
npm ERR!     at TunnelingAgent.addRequest (C:\Bitnami\meanstack-3.0.4-0\nodejs\n
ode_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:80:8)
npm ERR!     at new ClientRequest (_http_client.js:154:16)
npm ERR!     at Object.exports.request (http.js:49:10)
npm ERR!     at Object.exports.request (https.js:136:15)
npm ERR!     at Request.start (C:\Bitnami\meanstack-3.0.4-0\nodejs\node_modules\
npm\node_modules\request\request.js:583:30)
npm ERR!     at Request.end (C:\Bitnami\meanstack-3.0.4-0\nodejs\node_modules\np
m\node_modules\request\request.js:1237:28)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Bitnami\\meanstack-3.0.4-0\\nodejs\\\\node.exe" "C:\\Bitna
mi\\meanstack-3.0.4-0\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd C:\Bitnami\meanstack-3.0.4-0\projects\sample
npm ERR! node -v v0.12.4
npm ERR! npm -v 1.4.3
npm http GET https://registry.npmjs.org/cookie-parser
npm ERR! TypeError: Request path contains unescaped characters.
npm ERR!     at new ClientRequest (_http_client.js:73:11)
npm ERR!     at TunnelingAgent.exports.request (http.js:49:10)
npm ERR!     at TunnelingAgent.createSocket (C:\Bitnami\meanstack-3.0.4-0\nodejs
\node_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:117:25
)
npm ERR!     at TunnelingAgent.createSecureSocket [as createSocket] (C:\Bitnami\
meanstack-3.0.4-0\nodejs\node_modules\npm\node_modules\request\node_modules\tunn
el-agent\index.js:184:41)
npm ERR!     at TunnelingAgent.addRequest (C:\Bitnami\meanstack-3.0.4-0\nodejs\n
ode_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:80:8)
npm ERR!     at new ClientRequest (_http_client.js:154:16)
npm ERR!     at Object.exports.request (http.js:49:10)
npm ERR!     at Object.exports.request (https.js:136:15)
npm ERR!     at Request.start (C:\Bitnami\meanstack-3.0.4-0\nodejs\node_modules\
npm\node_modules\request\request.js:583:30)
npm ERR!     at Request.end (C:\Bitnami\meanstack-3.0.4-0\nodejs\node_modules\np
m\node_modules\request\request.js:1237:28)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Bitnami\\meanstack-3.0.4-0\\nodejs\\\\node.exe" "C:\\Bitna
mi\\meanstack-3.0.4-0\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd C:\Bitnami\meanstack-3.0.4-0\projects\sample
npm ERR! node -v v0.12.4
npm ERR! npm -v 1.4.3
npm http GET https://registry.npmjs.org/serve-favicon
npm ERR! TypeError: Request path contains unescaped characters.
npm ERR!     at new ClientRequest (_http_client.js:73:11)
npm ERR!     at TunnelingAgent.exports.request (http.js:49:10)
npm ERR!     at TunnelingAgent.createSocket (C:\Bitnami\meanstack-3.0.4-0\nodejs
\node_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:117:25
)
npm ERR!     at TunnelingAgent.createSecureSocket [as createSocket] (C:\Bitnami\
meanstack-3.0.4-0\nodejs\node_modules\npm\node_modules\request\node_modules\tunn
el-agent\index.js:184:41)
npm ERR!     at TunnelingAgent.addRequest (C:\Bitnami\meanstack-3.0.4-0\nodejs\n
ode_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:80:8)
npm ERR!     at new ClientRequest (_http_client.js:154:16)
npm ERR!     at Object.exports.request (http.js:49:10)
npm ERR!     at Object.exports.request (https.js:136:15)
npm ERR!     at Request.start (C:\Bitnami\meanstack-3.0.4-0\nodejs\node_modules\
npm\node_modules\request\request.js:583:30)
npm ERR!     at Request.end (C:\Bitnami\meanstack-3.0.4-0\nodejs\node_modules\np
m\node_modules\request\request.js:1237:28)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Bitnami\\meanstack-3.0.4-0\\nodejs\\\\node.exe" "C:\\Bitna
mi\\meanstack-3.0.4-0\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd C:\Bitnami\meanstack-3.0.4-0\projects\sample
npm ERR! node -v v0.12.4
npm ERR! npm -v 1.4.3
npm http GET https://registry.npmjs.org/jade
npm ERR! TypeError: Request path contains unescaped characters.
npm ERR!     at new ClientRequest (_http_client.js:73:11)
npm ERR!     at TunnelingAgent.exports.request (http.js:49:10)
npm ERR!     at TunnelingAgent.createSocket (C:\Bitnami\meanstack-3.0.4-0\nodejs
\node_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:117:25
)
npm ERR!     at TunnelingAgent.createSecureSocket [as createSocket] (C:\Bitnami\
meanstack-3.0.4-0\nodejs\node_modules\npm\node_modules\request\node_modules\tunn
el-agent\index.js:184:41)
npm ERR!     at TunnelingAgent.addRequest (C:\Bitnami\meanstack-3.0.4-0\nodejs\n
ode_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:80:8)
npm ERR!     at new ClientRequest (_http_client.js:154:16)
npm ERR!     at Object.exports.request (http.js:49:10)
npm ERR!     at Object.exports.request (https.js:136:15)
npm ERR!     at Request.start (C:\Bitnami\meanstack-3.0.4-0\nodejs\node_modules\
npm\node_modules\request\request.js:583:30)
npm ERR!     at Request.end (C:\Bitnami\meanstack-3.0.4-0\nodejs\node_modules\np
m\node_modules\request\request.js:1237:28)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Bitnami\\meanstack-3.0.4-0\\nodejs\\\\node.exe" "C:\\Bitna
mi\\meanstack-3.0.4-0\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd C:\Bitnami\meanstack-3.0.4-0\projects\sample
npm ERR! node -v v0.12.4
npm ERR! npm -v 1.4.3
npm http GET https://registry.npmjs.org/express
npm ERR! TypeError: Request path contains unescaped characters.
npm ERR!     at new ClientRequest (_http_client.js:73:11)
npm ERR!     at TunnelingAgent.exports.request (http.js:49:10)
npm ERR!     at TunnelingAgent.createSocket (C:\Bitnami\meanstack-3.0.4-0\nodejs
\node_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:117:25
)
npm ERR!     at TunnelingAgent.createSecureSocket [as createSocket] (C:\Bitnami\
meanstack-3.0.4-0\nodejs\node_modules\npm\node_modules\request\node_modules\tunn
el-agent\index.js:184:41)
npm ERR!     at TunnelingAgent.addRequest (C:\Bitnami\meanstack-3.0.4-0\nodejs\n
ode_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:80:8)
npm ERR!     at new ClientRequest (_http_client.js:154:16)
npm ERR!     at Object.exports.request (http.js:49:10)
npm ERR!     at Object.exports.request (https.js:136:15)
npm ERR!     at Request.start (C:\Bitnami\meanstack-3.0.4-0\nodejs\node_modules\
npm\node_modules\request\request.js:583:30)
npm ERR!     at Request.end (C:\Bitnami\meanstack-3.0.4-0\nodejs\node_modules\np
m\node_modules\request\request.js:1237:28)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Bitnami\\meanstack-3.0.4-0\\nodejs\\\\node.exe" "C:\\Bitna
mi\\meanstack-3.0.4-0\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd C:\Bitnami\meanstack-3.0.4-0\projects\sample
npm ERR! node -v v0.12.4
npm ERR! npm -v 1.4.3
npm http GET https://registry.npmjs.org/debug
npm ERR! TypeError: Request path contains unescaped characters.
npm ERR!     at new ClientRequest (_http_client.js:73:11)
npm ERR!     at TunnelingAgent.exports.request (http.js:49:10)
npm ERR!     at TunnelingAgent.createSocket (C:\Bitnami\meanstack-3.0.4-0\nodejs
\node_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:117:25
)
npm ERR!     at TunnelingAgent.createSecureSocket [as createSocket] (C:\Bitnami\
meanstack-3.0.4-0\nodejs\node_modules\npm\node_modules\request\node_modules\tunn
el-agent\index.js:184:41)
npm ERR!     at TunnelingAgent.addRequest (C:\Bitnami\meanstack-3.0.4-0\nodejs\n
ode_modules\npm\node_modules\request\node_modules\tunnel-agent\index.js:80:8)
npm ERR!     at new ClientRequest (_http_client.js:154:16)
npm ERR!     at Object.exports.request (http.js:49:10)
npm ERR!     at Object.exports.request (https.js:136:15)
npm ERR!     at Request.start (C:\Bitnami\meanstack-3.0.4-0\nodejs\node_modules\
npm\node_modules\request\request.js:583:30)
npm ERR!     at Request.end (C:\Bitnami\meanstack-3.0.4-0\nodejs\node_modules\np
m\node_modules\request\request.js:1237:28)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Bitnami\\meanstack-3.0.4-0\\nodejs\\\\node.exe" "C:\\Bitna
mi\\meanstack-3.0.4-0\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd C:\Bitnami\meanstack-3.0.4-0\projects\sample
npm ERR! node -v v0.12.4
npm ERR! npm -v 1.4.3
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Bitnami\meanstack-3.0.4-0\projects\sample\npm-debug.log
npm ERR! not ok code 0
```

**Comment by KenanY** [comment]
@Hitesh-Batra Could you first try [upgrading](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows)?

**Comment by Hitesh-Batra** [comment]
Thanks for the help @KenanY  , version was fine, just use the command "npm cache clean" and everything seems fine.
