### ISSUE TITLE
error install express

### ISSUE THREAD

**Issue by luannx** [npm/npm#8830]
I can't install express: 
```
luan@LuanNX-0093:~$ npm install express
npm http GET https://registry.npmjs.org/express
npm http GET https://registry.npmjs.org/express
npm http GET https://registry.npmjs.org/express
npm ERR! Error: 139639507257216:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:s23_clnt.c:795:
npm ERR! 
npm ERR!     at SlabBuffer.use (tls.js:232:18)
npm ERR!     at CleartextStream.read [as _read] (tls.js:452:29)
npm ERR!     at CleartextStream.Readable.read (_stream_readable.js:320:10)
npm ERR!     at EncryptedStream.write [as _write] (tls.js:366:25)
npm ERR!     at doWrite (_stream_writable.js:223:10)
npm ERR!     at writeOrBuffer (_stream_writable.js:213:5)
npm ERR!     at EncryptedStream.Writable.write (_stream_writable.js:180:11)
npm ERR!     at write (_stream_readable.js:583:24)
npm ERR!     at flow (_stream_readable.js:592:7)
npm ERR!     at Socket.pipeOnReadable (_stream_readable.js:624:5)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.16.0-30-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "express"
npm ERR! cwd /home/luan
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/luan/npm-debug.log
npm ERR! not ok code 0
```

**Comment by KenanY** [comment]
@luannx Does this also occur if you [upgrade](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) to the latest stable release of `npm`? Supported for `1.3` ended a long time ago.

**Comment by luannx** [comment]
@KenanY
you can teach yourself how to fix

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
