### ISSUE TITLE
npm install -g less

### ISSUE THREAD

**Issue by maxdonetsk** [npm/npm#8835]
```
0 info it worked if it ends with ok
1 verbose cli [ 'd:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'c:\\Users\\Admin\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'less' ]
2 info using npm@2.12.0
3 info using node@v0.12.2
4 verbose install initial load of d:\Program Files\nodejs\package.json
5 verbose readDependencies loading dependencies from d:\Program Files\nodejs\package.json
6 silly cache add args [ 'less', null ]
7 verbose cache add spec less
8 silly cache add parsed spec { raw: 'less',
8 silly cache add   scope: null,
8 silly cache add   name: 'less',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: '*',
8 silly cache add   type: 'range' }
9 silly addNamed less@*
10 verbose addNamed "*" is a valid semver range for less
11 silly addNameRange { name: 'less', range: '*', hasData: false }
12 silly mapToRegistry name less
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/less
16 verbose addNameRange registry:https://registry.npmjs.org/less not in flight; fetching
17 verbose request uri https://registry.npmjs.org/less
18 verbose request no auth needed
19 info attempt registry request try #1 at 16:19:20
20 verbose request id 018bc14529ca706a
21 http request GET https://registry.npmjs.org/less
22 http 200 https://registry.npmjs.org/less
23 silly get cb [ 200,
23 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
23 silly get     etag: '"7GUN9VW84G6U68KIRR00YF3BU"',
23 silly get     'content-type': 'application/json',
23 silly get     'cache-control': 'max-age=60',
23 silly get     'content-length': '93550',
23 silly get     'accept-ranges': 'bytes',
23 silly get     date: 'Mon, 06 Jul 2015 13:19:20 GMT',
23 silly get     via: '1.1 varnish',
23 silly get     age: '52',
23 silly get     connection: 'keep-alive',
23 silly get     'x-served-by': 'cache-fra1246-FRA',
23 silly get     'x-cache': 'HIT',
23 silly get     'x-cache-hits': '1',
23 silly get     'x-timer': 'S1436188760.976233,VS0,VE0',
23 silly get     vary: 'Accept' } ]
24 verbose get saving less to C:\Users\Admin\AppData\Roaming\npm-cache\registry.npmjs.org\less\.cache.json
25 verbose stack TypeError: undefined is not a function
25 verbose stack     at calculateOwner (c:\Users\Admin\AppData\Roaming\npm\node_modules\npm\lib\utils\correct-mkdir.js:37:24)
25 verbose stack     at c:\Users\Admin\AppData\Roaming\npm\node_modules\npm\lib\utils\correct-mkdir.js:23:22
25 verbose stack     at FSReqWrap.oncomplete (evalmachine.<anonymous>:95:15)
26 verbose cwd c:\Ruby21
27 error Windows_NT 6.1.7601
28 error argv "d:\\Program Files\\nodejs\\node.exe" "c:\\Users\\Admin\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "less"
29 error node v0.12.2
30 error npm  v2.12.0
31 error undefined is not a function
32 error If you need help, you may report this error at:
32 error     <https://github.com/npm/npm/issues>
33 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
@maxdonetsk This is a known issue with `npm@2.12.0` on Windows. Try [upgrading](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows) :)

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
