### ISSUE TITLE
Build error with first mobile app with Visual Studio 2015 community RC

### ISSUE THREAD

**Issue by boykely** [npm/npm#8837]
Hi!! I try to build my first app with VS 2015 RC but it throws error on building. This is my log:
All packages are already installed and there is nothing to restore.
NuGet package restore finished.
```
1>------ Début de la génération : Projet : BlankCordovaApp1, Configuration : Debug Android ------
1>  Your environment has been set up for using Node.js 0.10.33 (ia32) and npm.
1>  ------ Vérification de l'installation globale du package à partir du répertoire du package source : B:\PROGRAM FILES\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\EXTENSIONS\APACHECORDOVATOOLS\packages\vs-tac
1>  ------ Nom du package.json source : vs-tac
1>  ------ Version du package.json source : 0.2.19
1>  ------ Le package n'est pas installé globalement actuellement.
1>  ------ Installation effectuée globalement à partir du package source. Cette opération peut prendre quelques minutes...
1>RUNMDAINSTALL : npm ERR! error : shasum check failed for B:\Users\VALIMO~1\AppData\Local\Temp\npm-5480-R2bjmfl4\registry.npmjs.org\npm\-\npm-1.3.4.tgz
1>  npm ERR! Expected: 1dacc91458f2197c362d774d2cbf111680f86ec2
1>  npm ERR! Actual:   fb089f39eee622fc5cff616fb471167f511f81fa
1>  npm ERR! From:     https://registry.npmjs.org/npm/-/npm-1.3.4.tgz
1>  npm ERR!     at B:\Program Files\nodejs\node_modules\npm\node_modules\sha\index.js:38:8
1>  npm ERR!     at ReadStream.<anonymous> (B:\Program Files\nodejs\node_modules\npm\node_modules\sha\index.js:85:7)
1>  npm ERR!     at ReadStream.emit (events.js:117:20)
1>  npm ERR!     at _stream_readable.js:943:16
1>  npm ERR!     at process._tickCallback (node.js:419:13)
1>  npm ERR! If you need help, you may report this *entire* log,
1>  npm ERR! including the npm and node versions, at:
1>  npm ERR!     <http://github.com/npm/npm/issues>
1>  npm ERR! System Windows_NT 6.2.9200
1>  npm ERR! command "B:\\Program Files\\nodejs\\\\node.exe" "B:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "-g" "install" "B:\\PROGRAM FILES\\MICROSOFT VISUAL STUDIO 14.0\\COMMON7\\IDE\\EXTENSIONS\\APACHECORDOVATOOLS\\packages\\vs-tac"
1>  npm ERR! cwd B:\Users\mel\Documents\Visual Studio 2015\Projects\BlankCordovaApp1\BlankCordovaApp1
1>  npm ERR! node -v v0.10.33
1>  npm ERR! npm -v 1.4.28
1>  npm------ Échec de l'installation npm. Code de sortie : 1
1>B:\Program Files\MSBuild\Microsoft\VisualStudio\v14.0\ApacheCordovaTools\vs-mda-targets\Microsoft.MDA.FileMirroring.targets(218,5): error : Error installing local npm package.
========== Génération : 0 a réussi, 1 a échoué, 0 mis à jour, 0 a été ignoré ==========
========== Déploiement : 0 a réussi, 0 a échoué, 0 a été ignoré ==========
And the erros corresponding to this log are: 
1) Error installing npm package
2) Erreur	shasum check failed for B:\Users\me~1\AppData\Local\Temp\npm-5480-R2bjmfl4\registry.npmjs.org\npm\-\npm-1.3.4.tgz	BlankCordovaApp1 B:\Users\me\documents\visual studio 2015\Projects\BlankCordovaApp1\BlankCordovaApp1\RUNMDAINSTALL	1
```
Thanks.any help is welcomed

**Comment by naveenbhatt189** [comment]
Hi,
I have also faced the same issue.Even I am looking for the  solution.
Any kind of solutions or help on that will be greatly appreciated.

**Comment by boykely** [comment]
It seems that the problem comes with my internet connection.
