### ISSUE TITLE
npm ERR! No name provided in package.json

### ISSUE THREAD

**Issue by mathiasbynens** [npm/npm#8840]
I am getting the “npm ERR! No name provided in package.json” error, although there is [definitely](https://registry.npmjs.org/tibia-maps) a name present for this particular package. 

```sh
$ node -v
v2.3.3

$ npm -v
3.0.0

$ npm i tibia-maps -g
npm ERR! addLocal Could not install /private/tmp/tibia-maps
npm ERR! Darwin 14.4.0
npm ERR! argv "/Users/mathias/.nvm/versions/io.js/v2.3.3/bin/iojs" "/Users/mathias/.nvm/versions/io.js/v2.3.3/bin/npm" "i" "tibia-maps" "-g"
npm ERR! node v2.3.3
npm ERR! npm  v3.0.0

npm ERR! No name provided in package.json
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /private/tmp/npm-debug.log
```

`npm-debug.log`:

```
0 info it worked if it ends with ok
1 verbose cli [ '~/.nvm/versions/io.js/v2.3.3/bin/iojs',
1 verbose cli   '~/.nvm/versions/io.js/v2.3.3/bin/npm',
1 verbose cli   'i',
1 verbose cli   'tibia-maps',
1 verbose cli   '-g' ]
2 info using npm@3.0.0
3 info using node@v2.3.3
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly install normalizeTree
8 silly loadCurrentTree Finishing
9 silly loadIdealTree Starting
10 silly install loadIdealTree
11 silly cloneCurrentTree Starting
12 silly install cloneCurrentTreeToIdealTree
13 silly cloneCurrentTree Finishing
14 silly loadShrinkwrap Starting
15 silly install loadShrinkwrap
16 silly loadShrinkwrap Finishing
17 silly loadAllDepsIntoIdealTree Starting
18 silly install loadAllDepsIntoIdealTree
19 silly fetchPackageMetaData tibia-maps
20 silly fetchOtherPackageData tibia-maps
21 silly cache add args [ 'tibia-maps', null ]
22 verbose cache add spec tibia-maps
23 silly cache add parsed spec { raw: 'tibia-maps',
23 silly cache add   scope: null,
23 silly cache add   name: null,
23 silly cache add   rawSpec: 'tibia-maps',
23 silly cache add   spec: '/private/tmp/tibia-maps',
23 silly cache add   type: 'directory' }
24 error addLocal Could not install /private/tmp/tibia-maps
25 silly fetchPackageMetaData Error: No name provided in package.json
25 silly fetchPackageMetaData     at ~/.nvm/versions/io.js/v2.3.3/lib/node_modules/npm/lib/cache/add-local.js:65:17
25 silly fetchPackageMetaData     at ~/.nvm/versions/io.js/v2.3.3/lib/node_modules/npm/node_modules/read-package-json/read-json.js:345:5
25 silly fetchPackageMetaData     at checkBinReferences_ (~/.nvm/versions/io.js/v2.3.3/lib/node_modules/npm/node_modules/read-package-json/read-json.js:309:45)
25 silly fetchPackageMetaData     at final (~/.nvm/versions/io.js/v2.3.3/lib/node_modules/npm/node_modules/read-package-json/read-json.js:343:3)
25 silly fetchPackageMetaData     at then (~/.nvm/versions/io.js/v2.3.3/lib/node_modules/npm/node_modules/read-package-json/read-json.js:113:5)
25 silly fetchPackageMetaData     at ~/.nvm/versions/io.js/v2.3.3/lib/node_modules/npm/node_modules/read-package-json/read-json.js:232:12
25 silly fetchPackageMetaData     at FSReqWrap.readFileAfterClose [as oncomplete] (evalmachine.<anonymous>:380:3)
25 silly fetchPackageMetaData  error for tibia-maps [Error: No name provided in package.json]
26 silly rollbackFailedOptional Starting
27 silly rollbackFailedOptional Finishing
28 silly runTopLevelLifecycles Starting
29 silly runTopLevelLifecycles Finishing
30 silly install printInstalled
31 verbose stack Error: No name provided in package.json
31 verbose stack     at ~/.nvm/versions/io.js/v2.3.3/lib/node_modules/npm/lib/cache/add-local.js:65:17
31 verbose stack     at ~/.nvm/versions/io.js/v2.3.3/lib/node_modules/npm/node_modules/read-package-json/read-json.js:345:5
31 verbose stack     at checkBinReferences_ (~/.nvm/versions/io.js/v2.3.3/lib/node_modules/npm/node_modules/read-package-json/read-json.js:309:45)
31 verbose stack     at final (~/.nvm/versions/io.js/v2.3.3/lib/node_modules/npm/node_modules/read-package-json/read-json.js:343:3)
31 verbose stack     at then (~/.nvm/versions/io.js/v2.3.3/lib/node_modules/npm/node_modules/read-package-json/read-json.js:113:5)
31 verbose stack     at ~/.nvm/versions/io.js/v2.3.3/lib/node_modules/npm/node_modules/read-package-json/read-json.js:232:12
31 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (evalmachine.<anonymous>:380:3)
32 verbose cwd /private/tmp
33 error Darwin 14.4.0
34 error argv "~/.nvm/versions/io.js/v2.3.3/bin/iojs" "~/.nvm/versions/io.js/v2.3.3/bin/npm" "i" "tibia-maps" "-g"
35 error node v2.3.3
36 error npm  v3.0.0
37 error No name provided in package.json
38 error If you need help, you may report this error at:
38 error     <https://github.com/npm/npm/issues>
39 verbose exit [ 1, true ]
```

**Comment by iarna** [comment]
@mathiasbynens So, you were trying to install a local folder containing a node module globally, correct?

Specifically `/private/tmp/tibia-maps`

Could you provide the `package.json` in that folder?

**Comment by mathiasbynens** [comment]
@iarna Aaah, your comment made me realize what was going on. I didn’t mean to install the local folder at all. `rm -rf tibia-maps && npm i tibia-maps -g` worked. My bad. Thanks so much!
