### ISSUE TITLE
npm installation issues - Proxy Authorization Required

### ISSUE THREAD

**Issue by KumaresanWDC** [npm/npm#8844]
Applciation config

```
npm config set proxy=http://user:pwd@proxy:port/
npm config set registry=http://registry.npmjs.org/
npm config set strict-ssl=false
```

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'cordova' ]
2 info using npm@2.11.2
3 info using node@v0.12.6
4 verbose install initial load of C:\Users\kumaresan_p\AppData\Roaming\npm\package.json
5 verbose readDependencies loading dependencies from C:\Users\kumaresan_p\AppData\Roaming\npm\package.json
6 silly cache add args [ 'cordova', null ]
7 verbose cache add spec cordova
8 silly cache add parsed spec { raw: 'cordova',
8 silly cache add   scope: null,
8 silly cache add   name: 'cordova',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: '*',
8 silly cache add   type: 'range' }
9 silly addNamed cordova@*
10 verbose addNamed "*" is a valid semver range for cordova
11 silly addNameRange { name: 'cordova', range: '*', hasData: false }
12 silly mapToRegistry name cordova
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry http://registry.npmjs.org/
15 silly mapToRegistry uri http://registry.npmjs.org/cordova
16 verbose addNameRange registry:http://registry.npmjs.org/cordova not in flight; fetching
17 verbose request uri http://registry.npmjs.org/cordova
18 verbose request no auth needed
19 info attempt registry request try #1 at 3:27:03 PM
20 verbose request id db68f7a1c9b88c84
21 http request GET http://registry.npmjs.org/cordova
22 http 407 http://registry.npmjs.org/cordova
23 verbose bad json <HEAD><TITLE>Proxy Authorization Required</TITLE></HEAD>
23 verbose bad json <BODY BGCOLOR="white" FGCOLOR="black"><H1>Proxy Authorization Required</H1><HR>
23 verbose bad json <FONT FACE="Helvetica,Arial"><B>
23 verbose bad json Description: Authorization is required for access to this proxy<BR><BR>
23 verbose bad json </B>Error Code: <BR>ER (null)<BR><BR>
23 verbose bad json User Agent: <BR>npm/2.11.2 node/v0.12.6 win32 x64<BR><BR>
23 verbose bad json Error Detail: <BR><PRE>[2015/07/07 15:26:56.157215,  3] utils/ntlm_auth.c:371(check_plaintext_auth)
23 verbose bad json   NT_STATUS_NO_SUCH_USER: No such user (0xc0000064)
23 verbose bad json </PRE><BR><BR></B></FONT>
23 verbose bad json <HR>
23 verbose bad json <!-- default "Proxy Authorization Required" response (407) -->
23 verbose bad json </BODY>
23 verbose bad json                                                                           
24 error registry error parsing json
25 verbose headers { date: 'Tue, 07 Jul 2015 07:26:55 GMT',
25 verbose headers   via: '1.1 localhost.localdomain',
25 verbose headers   'proxy-connection': 'keep-alive',
25 verbose headers   'cache-control': 'no-store',
25 verbose headers   'content-type': 'text/html',
25 verbose headers   'content-language': 'en',
25 verbose headers   'proxy-authenticate': 'Negotiate, NTLM',
25 verbose headers   'content-length': '666' }
26 silly get cb [ 407,
26 silly get   { date: 'Tue, 07 Jul 2015 07:26:55 GMT',
26 silly get     via: '1.1 localhost.localdomain',
26 silly get     'proxy-connection': 'keep-alive',
26 silly get     'cache-control': 'no-store',
26 silly get     'content-type': 'text/html',
26 silly get     'content-language': 'en',
26 silly get     'proxy-authenticate': 'Negotiate, NTLM',
26 silly get     'content-length': '666' } ]
27 verbose stack SyntaxError: Unexpected token <
27 verbose stack <HEAD><TITLE>Proxy Authorization Required</TITLE></HEAD>
27 verbose stack <BODY BGCOLOR="white" FGCOLOR="black"><H1>Proxy Authorization Required</H1><HR>
27 verbose stack <FONT FACE="Helvetica,Arial"><B>
27 verbose stack Description: Authorization is required for access to this proxy<BR><BR>
27 verbose stack </B>Error Code: <BR>ER (null)<BR><BR>
27 verbose stack User Agent: <BR>npm/2.11.2 node/v0.12.6 win32 x64<BR><BR>
27 verbose stack Error Detail: <BR><PRE>[2015/07/07 15:26:56.157215,  3] utils/ntlm_auth.c:371(check_plaintext_auth)
27 verbose stack   NT_STATUS_NO_SUCH_USER: No such user (0xc0000064)
27 verbose stack </PRE><BR><BR></B></FONT>
27 verbose stack <HR>
27 verbose stack <!-- default "Proxy Authorization Required" response (407) -->
27 verbose stack </BODY>
27 verbose stack                                                                           
27 verbose stack     at Object.parse (native)
27 verbose stack     at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:197:23)
27 verbose stack     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:170:14)
27 verbose stack     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:354:22)
27 verbose stack     at Request.emit (events.js:110:17)
27 verbose stack     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1207:14)
27 verbose stack     at Request.emit (events.js:129:20)
27 verbose stack     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1153:12)
27 verbose stack     at IncomingMessage.emit (events.js:129:20)
27 verbose stack     at _stream_readable.js:908:16
28 verbose cwd C:\Users\kumaresan_p
29 error Windows_NT 6.1.7601
30 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova"
31 error node v0.12.6
32 error npm  v2.11.2
33 error Unexpected token <
33 error <HEAD><TITLE>Proxy Authorization Required</TITLE></HEAD>
33 error <BODY BGCOLOR="white" FGCOLOR="black"><H1>Proxy Authorization Required</H1><HR>
33 error <FONT FACE="Helvetica,Arial"><B>
33 error Description: Authorization is required for access to this proxy<BR><BR>
33 error </B>Error Code: <BR>ER (null)<BR><BR>
33 error User Agent: <BR>npm/2.11.2 node/v0.12.6 win32 x64<BR><BR>
33 error Error Detail: <BR><PRE>[2015/07/07 15:26:56.157215,  3] utils/ntlm_auth.c:371(check_plaintext_auth)
33 error   NT_STATUS_NO_SUCH_USER: No such user (0xc0000064)
33 error </PRE><BR><BR></B></FONT>
33 error <HR>
33 error <!-- default "Proxy Authorization Required" response (407) -->
33 error </BODY>
33 error                                                                           
34 error If you need help, you may report this error at:
34 error     <https://github.com/npm/npm/issues>
35 verbose exit [ 1, true ]
```

**Comment by josephbagnes** [comment]
any news?
