### ISSUE TITLE
Etherpad install error

### ISSUE THREAD

**Issue by bobanmak** [npm/npm#8846]
I want to install Etherpad-lite. I'm running Debian 8, npm -v: 1.4.21 & nodejs -v: v0.10.29
After runing bin/installDeps.sh i am getting this message :
```
npm ERR! Error: Parse Error
npm ERR!     at Socket.socketOnData (http.js:1583:20)
npm ERR!     at TCP.onread (net.js:527:27)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "--loglevel" "warn"
npm ERR! cwd /root/etherpad-lite-develop/src
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code HPE_INVALID_CONSTANT
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /root/etherpad-lite-develop/src/npm-debug.log
npm ERR! not ok code 0
```

My debian server is also limited, because its behind proxy and it can be accessed just from our local network. Thatways ive used this commands but i am still getting that error message. 
```
$ npm config set proxy http://login:pass@host:port
$ npm config set https-proxy http://login:pass@host:port
```

**Comment by bobanmak** [comment]
solved. My proxy settings wasn't correct.
