### ISSUE TITLE
npm install -g bower error (osx 10.10.2)

### ISSUE THREAD

**Issue by elachere** [npm/npm#8847]
Hi,
I'm trying to install bower with npm, heres my .log : 

```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'install', '-g', 'bower' ]
2 info using npm@2.11.2
3 info using node@v0.12.6
4 verbose install initial load of /usr/local/lib/package.json
5 verbose readDependencies loading dependencies from /usr/local/lib/package.json
6 silly cache add args [ 'bower', null ]
7 verbose cache add spec bower
8 silly cache add parsed spec { raw: 'bower',
8 silly cache add   scope: null,
8 silly cache add   name: 'bower',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: '*',
8 silly cache add   type: 'range' }
9 silly addNamed bower@*
10 verbose addNamed "*" is a valid semver range for bower
11 silly addNameRange { name: 'bower', range: '*', hasData: false }
12 silly mapToRegistry name bower
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/bower
16 verbose addNameRange registry:https://registry.npmjs.org/bower not in flight; fetching
17 verbose request uri https://registry.npmjs.org/bower
18 verbose request no auth needed
19 info attempt registry request try #1 at 13:38:53
20 verbose request id 355f0a23f968633c
21 http request GET https://registry.npmjs.org/bower
22 http 200 https://registry.npmjs.org/bower
23 silly get cb [ 200,
23 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
23 silly get     etag: '"AAO6T055NQ700CZJYO7KWWFW"',
23 silly get     'content-type': 'application/json',
23 silly get     'cache-control': 'max-age=60',
23 silly get     'content-length': '112565',
23 silly get     'accept-ranges': 'bytes',
23 silly get     date: 'Tue, 07 Jul 2015 11:38:53 GMT',
23 silly get     via: '1.1 varnish',
23 silly get     age: '59',
23 silly get     connection: 'keep-alive',
23 silly get     'x-served-by': 'cache-ams4139-AMS',
23 silly get     'x-cache': 'HIT',
23 silly get     'x-cache-hits': '1',
23 silly get     'x-timer': 'S1436269133.719755,VS0,VE0',
23 silly get     vary: 'Accept' } ]
24 verbose get saving bower to /Users/LongDuZboub/.npm/registry.npmjs.org/bower/.cache.json
25 silly addNameRange number 2 { name: 'bower', range: '*', hasData: true }
26 silly addNameRange versions [ 'bower',
26 silly addNameRange   [ '0.1.0',
26 silly addNameRange     '0.1.2',
26 silly addNameRange     '0.1.3',
26 silly addNameRange     '0.2.0',
26 silly addNameRange     '0.3.0',
26 silly addNameRange     '0.3.1',
26 silly addNameRange     '0.3.2',
26 silly addNameRange     '0.4.0',
26 silly addNameRange     '0.5.0',
26 silly addNameRange     '0.5.1',
26 silly addNameRange     '0.6.0',
26 silly addNameRange     '0.6.1',
26 silly addNameRange     '0.6.2',
26 silly addNameRange     '0.6.3',
26 silly addNameRange     '0.6.4',
26 silly addNameRange     '0.6.5',
26 silly addNameRange     '0.6.6',
26 silly addNameRange     '0.6.7',
26 silly addNameRange     '0.6.8',
26 silly addNameRange     '0.7.0',
26 silly addNameRange     '0.7.1',
26 silly addNameRange     '0.8.0',
26 silly addNameRange     '0.8.1',
26 silly addNameRange     '0.8.2',
26 silly addNameRange     '0.8.3',
26 silly addNameRange     '0.8.4',
26 silly addNameRange     '0.8.5',
26 silly addNameRange     '0.8.6',
26 silly addNameRange     '0.9.0',
26 silly addNameRange     '0.9.1',
26 silly addNameRange     '0.9.2',
26 silly addNameRange     '0.10.0',
26 silly addNameRange     '1.0.0',
26 silly addNameRange     '1.0.1',
26 silly addNameRange     '1.0.2',
26 silly addNameRange     '1.0.3',
26 silly addNameRange     '1.1.0',
26 silly addNameRange     '1.1.1',
26 silly addNameRange     '1.1.2',
26 silly addNameRange     '1.2.0',
26 silly addNameRange     '1.2.1',
26 silly addNameRange     '1.2.2',
26 silly addNameRange     '1.2.3',
26 silly addNameRange     '1.2.4',
26 silly addNameRange     '1.2.5',
26 silly addNameRange     '1.2.6',
26 silly addNameRange     '1.2.7',
26 silly addNameRange     '1.2.8',
26 silly addNameRange     '1.3.0',
26 silly addNameRange     '1.3.1',
26 silly addNameRange     '1.3.2',
26 silly addNameRange     '1.3.3',
26 silly addNameRange     '1.3.4',
26 silly addNameRange     '1.3.5',
26 silly addNameRange     '1.3.6',
26 silly addNameRange     '1.3.7',
26 silly addNameRange     '1.3.8',
26 silly addNameRange     '1.3.9',
26 silly addNameRange     '1.3.10',
26 silly addNameRange     '1.3.11',
26 silly addNameRange     '1.3.12',
26 silly addNameRange     '1.4.0',
26 silly addNameRange     '1.4.1' ] ]
27 silly addNamed bower@1.4.1
28 verbose addNamed "1.4.1" is a plain semver version for bower
29 silly mapToRegistry name bower
30 silly mapToRegistry using default registry
31 silly mapToRegistry registry https://registry.npmjs.org/
32 silly mapToRegistry uri https://registry.npmjs.org/bower
33 verbose addRemoteTarball https://registry.npmjs.org/bower/-/bower-1.4.1.tgz not in flight; adding
34 verbose addRemoteTarball [ 'https://registry.npmjs.org/bower/-/bower-1.4.1.tgz',
34 verbose addRemoteTarball   'a18be39d030792754f30f1c5b32d37b0156ba8dd' ]
35 info retry fetch attempt 1 at 13:38:53
36 info attempt registry request try #1 at 13:38:53
37 http fetch GET https://registry.npmjs.org/bower/-/bower-1.4.1.tgz
38 http fetch 200 https://registry.npmjs.org/bower/-/bower-1.4.1.tgz
39 silly fetchAndShaCheck shasum a18be39d030792754f30f1c5b32d37b0156ba8dd
40 verbose addTmpTarball /var/folders/3m/m83mzld15nq0znfrqj8rrgq40000gn/T/npm-1662-82ca1f8e/registry.npmjs.org/bower/-/bower-1.4.1.tgz not in flight; adding
41 verbose addTmpTarball already have metadata; skipping unpack for bower@1.4.1
42 silly cache afterAdd bower@1.4.1
43 verbose afterAdd /Users/LongDuZboub/.npm/bower/1.4.1/package/package.json not in flight; writing
44 verbose afterAdd /Users/LongDuZboub/.npm/bower/1.4.1/package/package.json written
45 silly install resolved [ { name: 'bower',
45 silly install resolved     version: '1.4.1',
45 silly install resolved     description: 'The browser package manager',
45 silly install resolved     author: { name: 'Twitter' },
45 silly install resolved     licenses: [ [Object] ],
45 silly install resolved     repository: { type: 'git', url: 'https://github.com/bower/bower' },
45 silly install resolved     main: 'lib',
45 silly install resolved     homepage: 'http://bower.io',
45 silly install resolved     engines: { node: '>=0.10.0' },
45 silly install resolved     dependencies:
45 silly install resolved      { abbrev: '^1.0.5',
45 silly install resolved        archy: '1.0.0',
45 silly install resolved        'bower-config': '^0.6.1',
45 silly install resolved        'bower-endpoint-parser': '^0.2.2',
45 silly install resolved        'bower-json': '^0.4.0',
45 silly install resolved        'bower-logger': '^0.2.2',
45 silly install resolved        'bower-registry-client': '^0.3.0',
45 silly install resolved        cardinal: '0.4.4',
45 silly install resolved        chalk: '^1.0.0',
45 silly install resolved        chmodr: '0.1.0',
45 silly install resolved        configstore: '^0.3.2',
45 silly install resolved        'decompress-zip': '^0.1.0',
45 silly install resolved        fstream: '^1.0.3',
45 silly install resolved        'fstream-ignore': '^1.0.2',
45 silly install resolved        github: '^0.2.3',
45 silly install resolved        glob: '^4.3.2',
45 silly install resolved        'graceful-fs': '^3.0.5',
45 silly install resolved        handlebars: '^2.0.0',
45 silly install resolved        inquirer: '0.8.0',
45 silly install resolved        insight: '^0.5.0',
45 silly install resolved        'is-root': '^1.0.0',
45 silly install resolved        junk: '^1.0.0',
45 silly install resolved        lockfile: '^1.0.0',
45 silly install resolved        'lru-cache': '^2.5.0',
45 silly install resolved        mkdirp: '0.5.0',
45 silly install resolved        mout: '^0.11.0',
45 silly install resolved        nopt: '^3.0.1',
45 silly install resolved        opn: '^1.0.1',
45 silly install resolved        'p-throttler': '0.1.1',
45 silly install resolved        promptly: '0.2.0',
45 silly install resolved        q: '^1.1.2',
45 silly install resolved        request: '2.53.0',
45 silly install resolved        'request-progress': '0.3.1',
45 silly install resolved        retry: '0.6.1',
45 silly install resolved        rimraf: '^2.2.8',
45 silly install resolved        semver: '^2.3.0',
45 silly install resolved        'shell-quote': '^1.4.2',
45 silly install resolved        'stringify-object': '^1.0.0',
45 silly install resolved        'tar-fs': '^1.4.1',
45 silly install resolved        tmp: '0.0.24',
45 silly install resolved        'update-notifier': '^0.3.0',
45 silly install resolved        'user-home': '^1.1.0',
45 silly install resolved        which: '^1.0.8' },
45 silly install resolved     devDependencies:
45 silly install resolved      { chai: '^1.10.0',
45 silly install resolved        coveralls: '^2.11.2',
45 silly install resolved        'expect.js': '^0.3.1',
45 silly install resolved        grunt: '^0.4.5',
45 silly install resolved        'grunt-cli': '^0.1.13',
45 silly install resolved        'grunt-contrib-jshint': '^0.10.0',
45 silly install resolved        'grunt-contrib-watch': '^0.6.1',
45 silly install resolved        'grunt-exec': '^0.4.6',
45 silly install resolved        'grunt-simple-mocha': '^0.4.0',
45 silly install resolved        istanbul: '^0.3.5',
45 silly install resolved        'load-grunt-tasks': '^2.0.0',
45 silly install resolved        mocha: '^2.1.0',
45 silly install resolved        multiline: '^1.0.2',
45 silly install resolved        nock: '^0.56.0',
45 silly install resolved        'node-uuid': '^1.4.2',
45 silly install resolved        proxyquire: '^1.3.0',
45 silly install resolved        'spawn-sync': '^1.0.5' },
45 silly install resolved     scripts: { test: 'grunt test' },
45 silly install resolved     bin: { bower: 'bin/bower' },
45 silly install resolved     preferGlobal: true,
45 silly install resolved     gitHead: 'a1287416d40f944d58cb8f2e774e2076bfffd32f',
45 silly install resolved     bugs: { url: 'https://github.com/bower/bower/issues' },
45 silly install resolved     _id: 'bower@1.4.1',
45 silly install resolved     _shasum: 'a18be39d030792754f30f1c5b32d37b0156ba8dd',
45 silly install resolved     _from: 'bower@*',
45 silly install resolved     _npmVersion: '2.7.4',
45 silly install resolved     _nodeVersion: '0.12.0',
45 silly install resolved     _npmUser: { name: 'sheerun', email: 'sheerun@sher.pl' },
45 silly install resolved     maintainers: [ [Object], [Object], [Object], [Object], [Object], [Object] ],
45 silly install resolved     dist:
45 silly install resolved      { shasum: 'a18be39d030792754f30f1c5b32d37b0156ba8dd',
45 silly install resolved        tarball: 'http://registry.npmjs.org/bower/-/bower-1.4.1.tgz' },
45 silly install resolved     directories: {},
45 silly install resolved     _resolved: 'https://registry.npmjs.org/bower/-/bower-1.4.1.tgz' } ]
46 info install bower@1.4.1 into /usr/local/lib
47 info installOne bower@1.4.1
48 verbose installOne of bower to /usr/local/lib not in flight; installing
49 warn locking Error: EACCES, open '/Users/LongDuZboub/.npm/_locks/bower-e8debc5417026b57.lock'
49 warn locking     at Error (native)
49 warn locking  /Users/LongDuZboub/.npm/_locks/bower-e8debc5417026b57.lock failed { [Error: EACCES, open '/Users/LongDuZboub/.npm/_locks/bower-e8debc5417026b57.lock']
49 warn locking   errno: -13,
49 warn locking   code: 'EACCES',
49 warn locking   path: '/Users/LongDuZboub/.npm/_locks/bower-e8debc5417026b57.lock' }
50 verbose stack Error: Attempt to unlock /usr/local/lib/node_modules/bower, which hasn't been locked
50 verbose stack     at unlock (/usr/local/lib/node_modules/npm/lib/utils/locker.js:66:11)
50 verbose stack     at cb (/usr/local/lib/node_modules/npm/lib/install.js:1017:5)
50 verbose stack     at /usr/local/lib/node_modules/npm/lib/install.js:1021:20
50 verbose stack     at /usr/local/lib/node_modules/npm/lib/utils/locker.js:40:9
50 verbose stack     at cb (/usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:149:38)
50 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:177:38
50 verbose stack     at FSReqWrap.oncomplete (fs.js:95:15)
51 verbose cwd /Users/LongDuZboub
52 error Darwin 14.1.0
53 error argv "node" "/usr/local/bin/npm" "install" "-g" "bower"
54 error node v0.12.6
55 error npm  v2.11.2
56 error Attempt to unlock /usr/local/lib/node_modules/bower, which hasn't been locked
57 error If you need help, you may report this error at:
57 error     <https://github.com/npm/npm/issues>
58 verbose exit [ 1, true ]
```
Please help me <3

**Comment by williamboman** [comment]
Try this;

```
$ sudo chown -R $USER:$GROUP ~/.npm
$ npm cache clean
$ npm install -g bower
```

**Comment by elachere** [comment]
I tried, now i got this : 

npm ERR! tar.unpack untar error /Users/LongDuZboub/.npm/bower/1.4.1/package.tgz
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "bower"
npm ERR! node v0.12.6
npm ERR! npm  v2.11.2
npm ERR! path /usr/local/lib/node_modules/bower
npm ERR! code EACCES
npm ERR! errno -13

npm ERR! Error: EACCES, mkdir '/usr/local/lib/node_modules/bower'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES, mkdir '/usr/local/lib/node_modules/bower']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/usr/local/lib/node_modules/bower',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: '/usr/local/lib/node_modules/bower',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack:
npm ERR!    [ '/usr/local/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:35:25',
npm ERR!      '/usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:47:53',
npm ERR!      'FSReqWrap.oncomplete (fs.js:95:15)' ] }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/LongDuZboub/npm-debug.log

**Comment by williamboman** [comment]
```sh
$ sudo chown -R $USER:admin /usr/local
$ sudo chown -R $USER:admin /Library/Caches/Homebrew # assuming you installed Node via brew
```

**Comment by elachere** [comment]
And ... it worked !

Love U <3

**Comment by williamboman** [comment]
Nice! Feel free to close the issue :smile:

**Comment by powerocoos** [comment]
great article

**Comment by akashraom** [comment]
very nice article. worked well :+1:
