### ISSUE TITLE
npm error installing grunt-cli

### ISSUE THREAD

**Issue by nuander** [npm/npm#8849]
I am running the command prompt as Administrator on Windows 7
I keep getting this "Failed to fetch from registry" error.

```
verbose cli [ 'C:\\Program Files (x86)\\nodejs\\\\node.exe',
verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
verbose cli   'install',
verbose cli   'grunt-cli',
verbose cli   '-g' ]
info using npm@1.1.0-3
info using node@v0.6.10
verbose config file C:\Users\mgroseth\.npmrc
verbose config file C:\Program Files (x86)\nodejs\etc\npmrc
verbose config file C:\Program Files (x86)\nodejs\node_modules\npm\npmrc
verbose mkdir done: C:\Users\mgroseth\AppData\Roaming\npm 755
verbose cache add [ 'grunt-cli', null ]
silly cache add: name, spec, args [ undefined, 'grunt-cli', [ 'grunt-cli', null ] ]
verbose parsed url { pathname: 'grunt-cli', path: 'grunt-cli', href: 'grunt-cli' }
verbose addNamed [ 'grunt-cli', '' ]
verbose addNamed [ null, '' ]
silly name, range, hasData [ 'grunt-cli', '', false ]
verbose raw, before any munging grunt-cli
verbose url resolving [ 'https://registry.npmjs.org/', './grunt-cli' ]
verbose url resolved https://registry.npmjs.org/grunt-cli
http GET https://registry.npmjs.org/grunt-cli
ERR! Error: failed to fetch from registry: grunt-cli
ERR!     at C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\npm-registry-client\get.js:139:12
ERR!     at cb (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\npm-registry-client\request.js:32:9)
ERR!     at Request._callback (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\npm-registry-client\request.js:137:18)
ERR!     at Request.callback (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\main.js:109:22)
ERR!     at Request.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\main.js:198:58)
ERR!     at Request.emit (events.js:88:20)
ERR!     at ClientRequest.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\request\main.js:356:14)
ERR!     at ClientRequest.emit (events.js:67:17)
ERR!     at HTTPParser.onIncoming (http.js:1258:11)
ERR!     at HTTPParser.onHeadersComplete (http.js:102:31)
ERR! You may report this log at:
ERR!     <http://github.com/isaacs/npm/issues>
ERR! or email it to:
ERR!     <npm-@googlegroups.com>
ERR! 
ERR! System Windows_NT 6.1.7601
ERR! command "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "grunt-cli" "-g"
ERR! cwd D:\Projects\igniteui-angular
ERR! node -v v0.6.10
ERR! npm -v 1.1.0-3
ERR! message failed to fetch from registry: grunt-cli
```

**Comment by KenanY** [comment]
@nuander Your versions of Node.js and `npm` are the oldest I've seen around here in a long time. Node.js v0.6 support ended _years_ ago when v0.10 came out (we're on v0.12 now). `npm@1.1` support is... nonexistent. Could you first try upgrading both [Node.js](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-node) and [`npm`](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) to their respective latest, stable releases?

**Comment by nuander** [comment]
Thanks for you rapid response.  I will upgrade both and try again

**Comment by nuander** [comment]
Yes that fixed it, thx
