### ISSUE TITLE
postinstall script fails because of missing dependency

### ISSUE THREAD

**Issue by tarmolov** [npm/npm#8850]
I have a project with `vow-fs` and `git-hooks` dependencies. `git-hook` package has the same `vow-fs` dependency. Also `git-hooks` package has a [postinstall script](https://github.com/tarmolov/git-hooks-js/blob/master/package.json#L11).

This postinstall script fails with the following error:
```bash
$ npm install
npm WARN package.json @ No description
npm WARN package.json @ No repository field.
npm WARN package.json @ No README data
npm WARN package.json @ No license field.

> git-hooks@1.0.0-rc.1 postinstall /Users/hevil/npm-error/node_modules/git-hooks
> git-hooks --install

module.js:338
    throw err;
          ^
Error: Cannot find module 'brace-expansion'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/hevil/npm-error/node_modules/vow-fs/node_modules/glob/node_modules/minimatch/minimatch.js:10:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/Users/hevil/.nvm/versions/node/v0.12.1/bin/npm" "install"
npm ERR! node v0.12.1
npm ERR! npm  v2.12.1
npm ERR! code ELIFECYCLE

npm ERR! git-hooks@1.0.0-rc.1 postinstall: `git-hooks --install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the git-hooks@1.0.0-rc.1 postinstall script 'git-hooks --install'.
npm ERR! This is most likely a problem with the git-hooks package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     git-hooks --install
npm ERR! You can get their info via:
npm ERR!     npm owner ls git-hooks
npm ERR! There is likely additional logging output above.

> git-hooks@1.0.0-rc.1 preuninstall /Users/hevil/npm-error/node_modules/git-hooks
> git-hooks --uninstall

git-hooks is not installed

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/hevil/npm-error/npm-debug.log
```

It seems that this error occurred because postinstall script is executed before all dependencies are fulfilled.  If I repeat `npm install` command, it'll work without any error.

Also if I set different `vow-fs` versions in the project and `git-hooks`, it'll work fine, too.

My environment:
```
$ node --version
v0.12.1
$ npm --version
2.12.1
````

How to reproduce the bug:
```bash
$ git clone https://github.com/tarmolov/npm-error.git
$ cd npm-error
$ npm install
```

I couldn't reproduce error with `npm@3` but it seems that it won't be shipped in the nearest future.

**Comment by tarmolov** [comment]
See also #8152

**Comment by iarna** [comment]
npm@3 explicitly fixes this issue, which is why you weren't able to reproduce it there. =)

**Comment by tarmolov** [comment]
Cool! :)

Do you plan to ship this fix to npm@2.x? Or maybe node with npm@3 will be shipped soon? ;)

**Comment by iarna** [comment]
It took a pretty major architectural rewrite to get this change, so no, it's not going in npm@2.

**Comment by tarmolov** [comment]
Thank you for such fast responses!

Looking forward to nodejs with npm@3  :smile_cat:

**Comment by iarna** [comment]
I am too! 😁

Ok, I'm gonna close this, as we don't expect to fix this in npm@2.
