### ISSUE TITLE
Mystical "Missing required argument #2"

### ISSUE THREAD

**Issue by bevacqua** [npm/npm#8852]
<img width="1263" alt="screen shot 2015-07-07 at 13 42 51" src="https://cloud.githubusercontent.com/assets/934293/8551615/21801698-24ae-11e5-9013-9f0db6628ab1.png">

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/nico/.nvm/versions/io.js/v2.2.1/bin/iojs',
1 verbose cli   '/Users/nico/.nvm/versions/io.js/v2.2.1/bin/npm',
1 verbose cli   'i',
1 verbose cli   'taunus@7.1.0',
1 verbose cli   '-S' ]
2 info using npm@3.0.0
3 info using node@v2.2.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly rollbackFailedOptional Starting
8 silly rollbackFailedOptional Finishing
9 silly runTopLevelLifecycles Starting
10 silly runTopLevelLifecycles Finishing
11 silly install saveToDependencies
12 verbose stack Error: Missing required argument #2
12 verbose stack     at exports.saveRequested (/Users/nico/.nvm/versions/io.js/v2.2.1/lib/node_modules/npm/lib/install/save.js:18:3)
12 verbose stack     at Object.Installer.saveToDependencies (/Users/nico/.nvm/versions/io.js/v2.2.1/lib/node_modules/npm/lib/install.js:502:3)
12 verbose stack     at Array.<anonymous> (/Users/nico/.nvm/versions/io.js/v2.2.1/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
12 verbose stack     at LOOP (/Users/nico/.nvm/versions/io.js/v2.2.1/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
12 verbose stack     at /Users/nico/.nvm/versions/io.js/v2.2.1/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
12 verbose stack     at Object.Installer.finishTracker (/Users/nico/.nvm/versions/io.js/v2.2.1/lib/node_modules/npm/lib/install.js:279:3)
12 verbose stack     at Array.<anonymous> (/Users/nico/.nvm/versions/io.js/v2.2.1/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
12 verbose stack     at LOOP (/Users/nico/.nvm/versions/io.js/v2.2.1/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
12 verbose stack     at /Users/nico/.nvm/versions/io.js/v2.2.1/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
12 verbose stack     at Object.Installer.runTopLevelLifecycles (/Users/nico/.nvm/versions/io.js/v2.2.1/lib/node_modules/npm/lib/install.js:475:28)
13 verbose cwd /Users/nico/dev/stompflow
14 error Darwin 14.0.0
15 error argv "/Users/nico/.nvm/versions/io.js/v2.2.1/bin/iojs" "/Users/nico/.nvm/versions/io.js/v2.2.1/bin/npm" "i" "taunus@7.1.0" "-S"
16 error node v2.2.1
17 error npm  v3.0.0
18 error code EMISSINGARG
19 error typeerror Error: Missing required argument #2
19 error typeerror     at exports.saveRequested (/Users/nico/.nvm/versions/io.js/v2.2.1/lib/node_modules/npm/lib/install/save.js:18:3)
19 error typeerror     at Object.Installer.saveToDependencies (/Users/nico/.nvm/versions/io.js/v2.2.1/lib/node_modules/npm/lib/install.js:502:3)
19 error typeerror     at Array.<anonymous> (/Users/nico/.nvm/versions/io.js/v2.2.1/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
19 error typeerror     at LOOP (/Users/nico/.nvm/versions/io.js/v2.2.1/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
19 error typeerror     at /Users/nico/.nvm/versions/io.js/v2.2.1/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
19 error typeerror     at Object.Installer.finishTracker (/Users/nico/.nvm/versions/io.js/v2.2.1/lib/node_modules/npm/lib/install.js:279:3)
19 error typeerror     at Array.<anonymous> (/Users/nico/.nvm/versions/io.js/v2.2.1/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
19 error typeerror     at LOOP (/Users/nico/.nvm/versions/io.js/v2.2.1/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
19 error typeerror     at /Users/nico/.nvm/versions/io.js/v2.2.1/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
19 error typeerror     at Object.Installer.runTopLevelLifecycles (/Users/nico/.nvm/versions/io.js/v2.2.1/lib/node_modules/npm/lib/install.js:475:28)
19 error typeerror This is an error with npm itself. Please report this error at:
19 error typeerror     <http://github.com/npm/npm/issues>
20 verbose exit [ 1, true ]
```

**Comment by iarna** [comment]
As it says "This is an error with npm itself." ;)

Could you try again with npm@3.1.0 ? I fixed a bunch of bugs last week...

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues.  If this is still a problem, can you please reply and let us know?  We’ll be happy to reopen if necessary.
