### ISSUE TITLE
Error: unable to verify the first certificate

### ISSUE THREAD

**Issue by Aeliot-Tm** [npm/npm#8872]
I try to install YUI Compressor and tipe a command: npm install yuicompressor
But it fail with an arror. 
Log:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'yuicompressor' ]
2 info using npm@2.11.2
3 info using node@v0.12.5
4 verbose install initial load of Z:\package.json
5 verbose readDependencies loading dependencies from Z:\package.json
6 silly cache add args [ 'yuicompressor', null ]
7 verbose cache add spec yuicompressor
8 silly cache add parsed spec { raw: 'yuicompressor',
8 silly cache add   scope: null,
8 silly cache add   name: 'yuicompressor',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: '*',
8 silly cache add   type: 'range' }
9 silly addNamed yuicompressor@*
10 verbose addNamed "*" is a valid semver range for yuicompressor
11 silly addNameRange { name: 'yuicompressor', range: '*', hasData: false }
12 silly mapToRegistry name yuicompressor
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/yuicompressor
16 verbose addNameRange registry:https://registry.npmjs.org/yuicompressor not in flight; fetching
17 verbose request uri https://registry.npmjs.org/yuicompressor
18 verbose request no auth needed
19 info attempt registry request try #1 at 09:09:09
20 verbose request id 0599cc7aa1e781b4
21 http request GET https://registry.npmjs.org/yuicompressor
22 info retry will retry, error on last attempt: Error: unable to verify the first certificate
23 info attempt registry request try #2 at 09:09:19
24 http request GET https://registry.npmjs.org/yuicompressor
25 info retry will retry, error on last attempt: Error: unable to verify the first certificate
26 info attempt registry request try #3 at 09:10:19
27 http request GET https://registry.npmjs.org/yuicompressor
28 verbose stack Error: unable to verify the first certificate
28 verbose stack     at Error (native)
28 verbose stack     at TLSSocket.<anonymous> (_tls_wrap.js:929:36)
28 verbose stack     at TLSSocket.emit (events.js:104:17)
28 verbose stack     at TLSSocket._finishInit (_tls_wrap.js:460:8)
29 verbose cwd Z:\
30 error Windows_NT 6.1.7601
31 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "yuicompressor"
32 error node v0.12.5
33 error npm  v2.11.2
34 error code UNABLE_TO_VERIFY_LEAF_SIGNATURE
35 error unable to verify the first certificate
36 error If you need help, you may report this error at:
36 error     <https://github.com/npm/npm/issues>
37 verbose exit [ 1, true ]
```

On command: npm install yuicompressor -g
It fail with a same error.
Log:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'yuicompressor',
1 verbose cli   '-g' ]
2 info using npm@2.11.2
3 info using node@v0.12.5
4 verbose install initial load of C:\Users\a.melnikov\AppData\Roaming\npm\package.json
5 verbose readDependencies loading dependencies from C:\Users\a.melnikov\AppData\Roaming\npm\package.json
6 silly cache add args [ 'yuicompressor', null ]
7 verbose cache add spec yuicompressor
8 silly cache add parsed spec { raw: 'yuicompressor',
8 silly cache add   scope: null,
8 silly cache add   name: 'yuicompressor',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: '*',
8 silly cache add   type: 'range' }
9 silly addNamed yuicompressor@*
10 verbose addNamed "*" is a valid semver range for yuicompressor
11 silly addNameRange { name: 'yuicompressor', range: '*', hasData: false }
12 silly mapToRegistry name yuicompressor
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/yuicompressor
16 verbose addNameRange registry:https://registry.npmjs.org/yuicompressor not in flight; fetching
17 verbose request uri https://registry.npmjs.org/yuicompressor
18 verbose request no auth needed
19 info attempt registry request try #1 at 09:15:36
20 verbose request id 94e02031cb456e00
21 http request GET https://registry.npmjs.org/yuicompressor
22 info retry will retry, error on last attempt: Error: unable to verify the first certificate
23 info attempt registry request try #2 at 09:15:46
24 http request GET https://registry.npmjs.org/yuicompressor
25 info retry will retry, error on last attempt: Error: unable to verify the first certificate
26 info attempt registry request try #3 at 09:16:47
27 http request GET https://registry.npmjs.org/yuicompressor
28 verbose stack Error: unable to verify the first certificate
28 verbose stack     at Error (native)
28 verbose stack     at TLSSocket.<anonymous> (_tls_wrap.js:929:36)
28 verbose stack     at TLSSocket.emit (events.js:104:17)
28 verbose stack     at TLSSocket._finishInit (_tls_wrap.js:460:8)
29 verbose cwd Z:\
30 error Windows_NT 6.1.7601
31 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "yuicompressor" "-g"
32 error node v0.12.5
33 error npm  v2.11.2
34 error code UNABLE_TO_VERIFY_LEAF_SIGNATURE
35 error unable to verify the first certificate
36 error If you need help, you may report this error at:
36 error     <https://github.com/npm/npm/issues>
37 verbose exit [ 1, true ]
```

**Comment by othiym23** [comment]
It looks like you may be running into proxy issues. Do you know if your computer connects to the internet through a proxy?

**Comment by Aeliot-Tm** [comment]
yes i work throw proxy

**Comment by Mletter1** [comment]
I am also behind a proxy, and I ran into this with
 
proxy=http://www.someproxy.com:80
https-proxy=http://www.someProxy.com:80

set with npm config <key> <value> --global

worked fine with npm 1.4.28, just upgraded to 3.3.4

**Comment by Mletter1** [comment]
looks like https://registry.npmjs.org/ the certificate is not trusted behind the proxy

my solution for this was to set the registry to the http version in config


`npm config set registry http://registry.npmjs.org/ --global`

**Comment by nevercute** [comment]
Me too :) https://github.com/npm/npm/issues/8601

**Comment by creeperyang** [comment]
@Mletter1 this works for me. However, is there any way besides using http?

**Comment by eliezergu** [comment]
I'm using http as default registry and i have the same issuewhen itry to install any package or update npm

**Comment by Yochanan-Khoury** [comment]
"Node V5 has issues with installing behind proxies #395"
- Why is that?

**Comment by sonicning** [comment]
@Mletter1 The same here, I also used 
 npm config set strict-ssl false
 npm config set registry "http://registry.npmjs.org/"
