### ISSUE TITLE
issue while installing Bower

### ISSUE THREAD

**Issue by mohitit** [npm/npm#8882]
i am getting error while installing Bower..The contents of log file is below

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'bower' ]
2 info using npm@2.11.2
3 info using node@v0.12.6
4 verbose install initial load of C:\Documents and Settings\mohit\Application Data\npm\package.json
5 verbose readDependencies loading dependencies from C:\Documents and Settings\mohit\Application Data\npm\package.json
6 silly cache add args [ 'bower', null ]
7 verbose cache add spec bower
8 silly cache add parsed spec { raw: 'bower',
8 silly cache add   scope: null,
8 silly cache add   name: 'bower',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: '*',
8 silly cache add   type: 'range' }
9 silly addNamed bower@*
10 verbose addNamed "*" is a valid semver range for bower
11 silly addNameRange { name: 'bower', range: '*', hasData: false }
12 silly mapToRegistry name bower
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry http://registry.npmjs.org/
15 silly mapToRegistry uri http://registry.npmjs.org/bower
16 verbose addNameRange registry:http://registry.npmjs.org/bower not in flight; fetching
17 verbose request uri http://registry.npmjs.org/bower
18 verbose request no auth needed
19 info attempt registry request try #1 at 11:28:26 PM
20 verbose request id 448209f9c9c6541f
21 http request GET http://registry.npmjs.org/bower
22 http 404 http://registry.npmjs.org/bower
23 verbose bad json <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
23 verbose bad json <html dir=ltr>
23 verbose bad json
23 verbose bad json <head>
23 verbose bad json <style>
23 verbose bad json a:link			{font:8pt/11pt verdana; color:FF0000}
23 verbose bad json a:visited		{font:8pt/11pt verdana; color:#4e4e4e}
23 verbose bad json </style>
23 verbose bad json
23 verbose bad json <META NAME="ROBOTS" CONTENT="NOINDEX">
23 verbose bad json
23 verbose bad json <title>The page cannot be found</title>
23 verbose bad json
23 verbose bad json <META HTTP-EQUIV="Content-Type" Content="text-html; charset=Windows-1252">
23 verbose bad json </head>
23 verbose bad json
23 verbose bad json <script>
23 verbose bad json function Homepage(){
23 verbose bad json <!--
23 verbose bad json // in real bits, urls get returned to our script like this:
23 verbose bad json // res://shdocvw.dll/http_404.htm#http://www.DocURL.com/bar.htm
23 verbose bad json
23 verbose bad json 	//For testing use DocURL = "res://shdocvw.dll/http_404.htm#https://www.microsoft.com/bar.htm"
23 verbose bad json 	DocURL = document.URL;
23 verbose bad json
23 verbose bad json 	//this is where the http or https will be, as found by searching for :// but skipping the res://
23 verbose bad json 	protocolIndex=DocURL.indexOf("://",4);
23 verbose bad json
23 verbose bad json 	//this finds the ending slash for the domain server
23 verbose bad json 	serverIndex=DocURL.indexOf("/",protocolIndex + 3);
23 verbose bad json
23 verbose bad json 		//for the href, we need a valid URL to the domain. We search for the # symbol to find the begining
23 verbose bad json 	//of the true URL, and add 1 to skip it - this is the BeginURL value. We use serverIndex as the end marker.
23 verbose bad json 	//urlresult=DocURL.substring(protocolIndex - 4,serverIndex);
23 verbose bad json 	BeginURL=DocURL.indexOf("#",1) + 1;
23 verbose bad json
23 verbose bad json 	urlresult=DocURL.substring(BeginURL,serverIndex);
23 verbose bad json
23 verbose bad json 	//for display, we need to skip after http://, and go to the next slash
23 verbose bad json 	displayresult=DocURL.substring(protocolIndex + 3 ,serverIndex);
23 verbose bad json
23 verbose bad json 	InsertElementAnchor(urlresult, displayresult);
23 verbose bad json }
23 verbose bad json
23 verbose bad json function HtmlEncode(text)
23 verbose bad json {
23 verbose bad json     return text.replace(/&/g, '&amp').replace(/'/g, '&quot;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
23 verbose bad json }
23 verbose bad json
23 verbose bad json function TagAttrib(name, value)
23 verbose bad json {
23 verbose bad json     return ' '+name+'="'+HtmlEncode(value)+'"';
23 verbose bad json }
23 verbose bad json
23 verbose bad json function PrintTag(tagName, needCloseTag, attrib, inner){
23 verbose bad json     document.write( '<' + tagName + attrib + '>' + HtmlEncode(inner) );
23 verbose bad json     if (needCloseTag) document.write( '</' + tagName +'>' );
23 verbose bad json }
23 verbose bad json
23 verbose bad json function URI(href)
23 verbose bad json {
23 verbose bad json     IEVer = window.navigator.appVersion;
23 verbose bad json     IEVer = IEVer.substr( IEVer.indexOf('MSIE') + 5, 3 );
23 verbose bad json
23 verbose bad json     return (IEVer.charAt(1)=='.' && IEVer >= '5.5') ?
23 verbose bad json         encodeURI(href) :
23 verbose bad json         escape(href).replace(/%3A/g, ':').replace(/%3B/g, ';');
23 verbose bad json }
23 verbose bad json
23 verbose bad json function InsertElementAnchor(href, text)
23 verbose bad json {
23 verbose bad json     PrintTag('A', true, TagAttrib('HREF', URI(href)), text);
23 verbose bad json }
23 verbose bad json
23 verbose bad json //-->
23 verbose bad json </script>
23 verbose bad json
23 verbose bad json <body bgcolor="FFFFFF">
23 verbose bad json
23 verbose bad json <table width="410" cellpadding="3" cellspacing="5">
23 verbose bad json
23 verbose bad json   <tr>
23 verbose bad json     <td align="left" valign="middle" width="360">
23 verbose bad json 	<h1 style="COLOR:000000; FONT: 13pt/15pt verdana"><!--Problem-->The page cannot be found</h1>
23 verbose bad json     </td>
23 verbose bad json   </tr>
23 verbose bad json
23 verbose bad json   <tr>
23 verbose bad json     <td width="400" colspan="2">
23 verbose bad json 	<font style="COLOR:000000; FONT: 8pt/11pt verdana">The page you are looking for might have been removed, had its name changed, or is temporarily unavailable.</font></td>
23 verbose bad json   </tr>
23 verbose bad json
23 verbose bad json   <tr>
23 verbose bad json     <td width="400" colspan="2">
23 verbose bad json 	<font style="COLOR:000000; FONT: 8pt/11pt verdana">
23 verbose bad json
23 verbose bad json 	<hr color="#C0C0C0" noshade>
23 verbose bad json
23 verbose bad json     <p>Please try the following:</p>
23 verbose bad json
23 verbose bad json 	<ul>
23 verbose bad json       <li>If you typed the page address in the Address bar, make sure that it is spelled correctly.<br>
23 verbose bad json       </li>
23 verbose bad json
23 verbose bad json       <li>Open the
23 verbose bad json
23 verbose bad json 	  <script>
23 verbose bad json 	  <!--
23 verbose bad json 	  if (!((window.navigator.userAgent.indexOf("MSIE") > 0) && (window.navigator.appVersion.charAt(0) == "2")))
23 verbose bad json 	  {
23 verbose bad json 	  	Homepage();
23 verbose bad json 	  }
23 verbose bad json 	  //-->
23 verbose bad json 	   </script>
23 verbose bad json
23 verbose bad json 	   home page, and then look for links to the information you want.</li>
23 verbose bad json
23 verbose bad json       <li>Click the <a href="javascript:history.back(1)">Back</a> button to try another link.</li>
23 verbose bad json     </ul>
23 verbose bad json
23 verbose bad json     <h2 style="font:8pt/11pt verdana; color:000000">HTTP 404 - File not found<br>
23 verbose bad json     Internet Information Services<BR></h2>
23 verbose bad json
23 verbose bad json 	<hr color="#C0C0C0" noshade>
23 verbose bad json
23 verbose bad json 	<p>Technical Information (for support personnel)</p>
23 verbose bad json
23 verbose bad json <ul>
23 verbose bad json <li>More information:<br>
23 verbose bad json <a href="http://www.microsoft.com/ContentRedirect.asp?prd=iis&sbp=&pver=5.0&pid=&ID=404&cat=web&os=&over=&hrd=&Opt1=&Opt2=&Opt3=" target="_blank">Microsoft Support</a>
23 verbose bad json </li>
23 verbose bad json </ul>
23 verbose bad json
23 verbose bad json     </font></td>
23 verbose bad json   </tr>
23 verbose bad json
23 verbose bad json </table>
23 verbose bad json </body>
23 verbose bad json </html>
24 error registry error parsing json
25 verbose headers { server: 'Microsoft-IIS/5.1',
25 verbose headers   date: 'Thu, 09 Jul 2015 17:58:26 GMT',
25 verbose headers   connection: 'close',
25 verbose headers   'content-length': '4040',
25 verbose headers   'content-type': 'text/html' }
26 silly get cb [ 404,
26 silly get   { server: 'Microsoft-IIS/5.1',
26 silly get     date: 'Thu, 09 Jul 2015 17:58:26 GMT',
26 silly get     connection: 'close',
26 silly get     'content-length': '4040',
26 silly get     'content-type': 'text/html' } ]
27 verbose stack SyntaxError: Unexpected token <
27 verbose stack <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
27 verbose stack <html dir=ltr>
27 verbose stack
27 verbose stack <head>
27 verbose stack <style>
27 verbose stack a:link			{font:8pt/11pt verdana; color:FF0000}
27 verbose stack a:visited		{font:8pt/11pt verdana; color:#4e4e4e}
27 verbose stack </style>
27 verbose stack
27 verbose stack <META NAME="ROBOTS" CONTENT="NOINDEX">
27 verbose stack
27 verbose stack <title>The page cannot be found</title>
27 verbose stack
27 verbose stack <META HTTP-EQUIV="Content-Type" Content="text-html; charset=Windows-1252">
27 verbose stack </head>
27 verbose stack
27 verbose stack <script>
27 verbose stack function Homepage(){
27 verbose stack <!--
27 verbose stack // in real bits, urls get returned to our script like this:
27 verbose stack // res://shdocvw.dll/http_404.htm#http://www.DocURL.com/bar.htm
27 verbose stack
27 verbose stack 	//For testing use DocURL = "res://shdocvw.dll/http_404.htm#https://www.microsoft.com/bar.htm"
27 verbose stack 	DocURL = document.URL;
27 verbose stack
27 verbose stack 	//this is where the http or https will be, as found by searching for :// but skipping the res://
27 verbose stack 	protocolIndex=DocURL.indexOf("://",4);
27 verbose stack
27 verbose stack 	//this finds the ending slash for the domain server
27 verbose stack 	serverIndex=DocURL.indexOf("/",protocolIndex + 3);
27 verbose stack
27 verbose stack 		//for the href, we need a valid URL to the domain. We search for the # symbol to find the begining
27 verbose stack 	//of the true URL, and add 1 to skip it - this is the BeginURL value. We use serverIndex as the end marker.
27 verbose stack 	//urlresult=DocURL.substring(protocolIndex - 4,serverIndex);
27 verbose stack 	BeginURL=DocURL.indexOf("#",1) + 1;
27 verbose stack
27 verbose stack 	urlresult=DocURL.substring(BeginURL,serverIndex);
27 verbose stack
27 verbose stack 	//for display, we need to skip after http://, and go to the next slash
27 verbose stack 	displayresult=DocURL.substring(protocolIndex + 3 ,serverIndex);
27 verbose stack
27 verbose stack 	InsertElementAnchor(urlresult, displayresult);
27 verbose stack }
27 verbose stack
27 verbose stack function HtmlEncode(text)
27 verbose stack {
27 verbose stack     return text.replace(/&/g, '&amp').replace(/'/g, '&quot;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
27 verbose stack }
27 verbose stack
27 verbose stack function TagAttrib(name, value)
27 verbose stack {
27 verbose stack     return ' '+name+'="'+HtmlEncode(value)+'"';
27 verbose stack }
27 verbose stack
27 verbose stack function PrintTag(tagName, needCloseTag, attrib, inner){
27 verbose stack     document.write( '<' + tagName + attrib + '>' + HtmlEncode(inner) );
27 verbose stack     if (needCloseTag) document.write( '</' + tagName +'>' );
27 verbose stack }
27 verbose stack
27 verbose stack function URI(href)
27 verbose stack {
27 verbose stack     IEVer = window.navigator.appVersion;
27 verbose stack     IEVer = IEVer.substr( IEVer.indexOf('MSIE') + 5, 3 );
27 verbose stack
27 verbose stack     return (IEVer.charAt(1)=='.' && IEVer >= '5.5') ?
27 verbose stack         encodeURI(href) :
27 verbose stack         escape(href).replace(/%3A/g, ':').replace(/%3B/g, ';');
27 verbose stack }
27 verbose stack
27 verbose stack function InsertElementAnchor(href, text)
27 verbose stack {
27 verbose stack     PrintTag('A', true, TagAttrib('HREF', URI(href)), text);
27 verbose stack }
27 verbose stack
27 verbose stack //-->
27 verbose stack </script>
27 verbose stack
27 verbose stack <body bgcolor="FFFFFF">
27 verbose stack
27 verbose stack <table width="410" cellpadding="3" cellspacing="5">
27 verbose stack
27 verbose stack   <tr>
27 verbose stack     <td align="left" valign="middle" width="360">
27 verbose stack 	<h1 style="COLOR:000000; FONT: 13pt/15pt verdana"><!--Problem-->The page cannot be found</h1>
27 verbose stack     </td>
27 verbose stack   </tr>
27 verbose stack
27 verbose stack   <tr>
27 verbose stack     <td width="400" colspan="2">
27 verbose stack 	<font style="COLOR:000000; FONT: 8pt/11pt verdana">The page you are looking for might have been removed, had its name changed, or is temporarily unavailable.</font></td>
27 verbose stack   </tr>
27 verbose stack
27 verbose stack   <tr>
27 verbose stack     <td width="400" colspan="2">
27 verbose stack 	<font style="COLOR:000000; FONT: 8pt/11pt verdana">
27 verbose stack
27 verbose stack 	<hr color="#C0C0C0" noshade>
27 verbose stack
27 verbose stack     <p>Please try the following:</p>
27 verbose stack
27 verbose stack 	<ul>
27 verbose stack       <li>If you typed the page address in the Address bar, make sure that it is spelled correctly.<br>
27 verbose stack       </li>
27 verbose stack
27 verbose stack       <li>Open the
27 verbose stack
27 verbose stack 	  <script>
27 verbose stack 	  <!--
27 verbose stack 	  if (!((window.navigator.userAgent.indexOf("MSIE") > 0) && (window.navigator.appVersion.charAt(0) == "2")))
27 verbose stack 	  {
27 verbose stack 	  	Homepage();
27 verbose stack 	  }
27 verbose stack 	  //-->
27 verbose stack 	   </script>
27 verbose stack
27 verbose stack 	   home page, and then look for links to the information you want.</li>
27 verbose stack
27 verbose stack       <li>Click the <a href="javascript:history.back(1)">Back</a> button to try another link.</li>
27 verbose stack     </ul>
27 verbose stack
27 verbose stack     <h2 style="font:8pt/11pt verdana; color:000000">HTTP 404 - File not found<br>
27 verbose stack     Internet Information Services<BR></h2>
27 verbose stack
27 verbose stack 	<hr color="#C0C0C0" noshade>
27 verbose stack
27 verbose stack 	<p>Technical Information (for support personnel)</p>
27 verbose stack
27 verbose stack <ul>
27 verbose stack <li>More information:<br>
27 verbose stack <a href="http://www.microsoft.com/ContentRedirect.asp?prd=iis&sbp=&pver=5.0&pid=&ID=404&cat=web&os=&over=&hrd=&Opt1=&Opt2=&Opt3=" target="_blank">Microsoft Support</a>
27 verbose stack </li>
27 verbose stack </ul>
27 verbose stack
27 verbose stack     </font></td>
27 verbose stack   </tr>
27 verbose stack
27 verbose stack </table>
27 verbose stack </body>
27 verbose stack </html>
27 verbose stack
27 verbose stack     at Object.parse (native)
27 verbose stack     at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:197:23)
27 verbose stack     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:170:14)
27 verbose stack     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:354:22)
27 verbose stack     at Request.emit (events.js:110:17)
27 verbose stack     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1207:14)
27 verbose stack     at Request.emit (events.js:129:20)
27 verbose stack     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1153:12)
27 verbose stack     at IncomingMessage.emit (events.js:129:20)
27 verbose stack     at _stream_readable.js:908:16
28 verbose cwd C:\
29 error Windows_NT 5.1.2600
30 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "bower"
31 error node v0.12.6
32 error npm  v2.11.2
33 error Unexpected token <
33 error <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
33 error <html dir=ltr>
33 error
33 error <head>
33 error <style>
33 error a:link			{font:8pt/11pt verdana; color:FF0000}
33 error a:visited		{font:8pt/11pt verdana; color:#4e4e4e}
33 error </style>
33 error
33 error <META NAME="ROBOTS" CONTENT="NOINDEX">
33 error
33 error <title>The page cannot be found</title>
33 error
33 error <META HTTP-EQUIV="Content-Type" Content="text-html; charset=Windows-1252">
33 error </head>
33 error
33 error <script>
33 error function Homepage(){
33 error <!--
33 error // in real bits, urls get returned to our script like this:
33 error // res://shdocvw.dll/http_404.htm#http://www.DocURL.com/bar.htm
33 error
33 error 	//For testing use DocURL = "res://shdocvw.dll/http_404.htm#https://www.microsoft.com/bar.htm"
33 error 	DocURL = document.URL;
33 error
33 error 	//this is where the http or https will be, as found by searching for :// but skipping the res://
33 error 	protocolIndex=DocURL.indexOf("://",4);
33 error
33 error 	//this finds the ending slash for the domain server
33 error 	serverIndex=DocURL.indexOf("/",protocolIndex + 3);
33 error
33 error 		//for the href, we need a valid URL to the domain. We search for the # symbol to find the begining
33 error 	//of the true URL, and add 1 to skip it - this is the BeginURL value. We use serverIndex as the end marker.
33 error 	//urlresult=DocURL.substring(protocolIndex - 4,serverIndex);
33 error 	BeginURL=DocURL.indexOf("#",1) + 1;
33 error
33 error 	urlresult=DocURL.substring(BeginURL,serverIndex);
33 error
33 error 	//for display, we need to skip after http://, and go to the next slash
33 error 	displayresult=DocURL.substring(protocolIndex + 3 ,serverIndex);
33 error
33 error 	InsertElementAnchor(urlresult, displayresult);
33 error }
33 error
33 error function HtmlEncode(text)
33 error {
33 error     return text.replace(/&/g, '&amp').replace(/'/g, '&quot;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
33 error }
33 error
33 error function TagAttrib(name, value)
33 error {
33 error     return ' '+name+'="'+HtmlEncode(value)+'"';
33 error }
33 error
33 error function PrintTag(tagName, needCloseTag, attrib, inner){
33 error     document.write( '<' + tagName + attrib + '>' + HtmlEncode(inner) );
33 error     if (needCloseTag) document.write( '</' + tagName +'>' );
33 error }
33 error
33 error function URI(href)
33 error {
33 error     IEVer = window.navigator.appVersion;
33 error     IEVer = IEVer.substr( IEVer.indexOf('MSIE') + 5, 3 );
33 error
33 error     return (IEVer.charAt(1)=='.' && IEVer >= '5.5') ?
33 error         encodeURI(href) :
33 error         escape(href).replace(/%3A/g, ':').replace(/%3B/g, ';');
33 error }
33 error
33 error function InsertElementAnchor(href, text)
33 error {
33 error     PrintTag('A', true, TagAttrib('HREF', URI(href)), text);
33 error }
33 error
33 error //-->
33 error </script>
33 error
33 error <body bgcolor="FFFFFF">
33 error
33 error <table width="410" cellpadding="3" cellspacing="5">
33 error
33 error   <tr>
33 error     <td align="left" valign="middle" width="360">
33 error 	<h1 style="COLOR:000000; FONT: 13pt/15pt verdana"><!--Problem-->The page cannot be found</h1>
33 error     </td>
33 error   </tr>
33 error
33 error   <tr>
33 error     <td width="400" colspan="2">
33 error 	<font style="COLOR:000000; FONT: 8pt/11pt verdana">The page you are looking for might have been removed, had its name changed, or is temporarily unavailable.</font></td>
33 error   </tr>
33 error
33 error   <tr>
33 error     <td width="400" colspan="2">
33 error 	<font style="COLOR:000000; FONT: 8pt/11pt verdana">
33 error
33 error 	<hr color="#C0C0C0" noshade>
33 error
33 error     <p>Please try the following:</p>
33 error
33 error 	<ul>
33 error       <li>If you typed the page address in the Address bar, make sure that it is spelled correctly.<br>
33 error       </li>
33 error
33 error       <li>Open the
33 error
33 error 	  <script>
33 error 	  <!--
33 error 	  if (!((window.navigator.userAgent.indexOf("MSIE") > 0) && (window.navigator.appVersion.charAt(0) == "2")))
33 error 	  {
33 error 	  	Homepage();
33 error 	  }
33 error 	  //-->
33 error 	   </script>
33 error
33 error 	   home page, and then look for links to the information you want.</li>
33 error
33 error       <li>Click the <a href="javascript:history.back(1)">Back</a> button to try another link.</li>
33 error     </ul>
33 error
33 error     <h2 style="font:8pt/11pt verdana; color:000000">HTTP 404 - File not found<br>
33 error     Internet Information Services<BR></h2>
33 error
33 error 	<hr color="#C0C0C0" noshade>
33 error
33 error 	<p>Technical Information (for support personnel)</p>
33 error
33 error <ul>
33 error <li>More information:<br>
33 error <a href="http://www.microsoft.com/ContentRedirect.asp?prd=iis&sbp=&pver=5.0&pid=&ID=404&cat=web&os=&over=&hrd=&Opt1=&Opt2=&Opt3=" target="_blank">Microsoft Support</a>
33 error </li>
33 error </ul>
33 error
33 error     </font></td>
33 error   </tr>
33 error
33 error </table>
33 error </body>
33 error </html>
34 error If you need help, you may report this error at:
34 error     <https://github.com/npm/npm/issues>
35 verbose exit [ 1, true ]

```

**Comment by KenanY** [comment]
@mohitit Are you still experiencing this issue?

**Comment by KenanY** [comment]
Closing as abandoned.
