### ISSUE TITLE
Error FHC on  MAC OS 10.10.1

### ISSUE THREAD

**Issue by peeyushgoyal** [npm/npm#8889]
When i am running following  command from the MAC terminal, I am getting following error
sudo npm install fh-fhc    or  sudo npm install -g fh-fhc@1.1.4-49

```
npm http GET https://registry.npmjs.org/fh-fhc/fh-fhc
npm ERR! Error: failed to fetch from registry: fh-fhc
npm ERR!     at /usr/local/lib/node_modules/npm/lib/utils/npm-registry-client/get.js:139:12
npm ERR!     at cb (/usr/local/lib/node_modules/npm/lib/utils/npm-registry-client/request.js:32:9)
npm ERR!     at Request._callback (/usr/local/lib/node_modules/npm/lib/utils/npm-registry-client/request.js:137:18)
npm ERR!     at Request.callback (/usr/local/lib/node_modules/npm/node_modules/request/main.js:104:22)
npm ERR!     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/main.js:181:58)
npm ERR!     at Request.emit (events.js:88:20)
npm ERR!     at ClientRequest.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/main.js:329:14)
npm ERR!     at ClientRequest.emit (events.js:67:17)
npm ERR!     at HTTPParser.onIncoming (http.js:1225:11)
npm ERR!     at HTTPParser.onHeadersComplete (http.js:102:31)
npm ERR! Report this *entire* log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>
npm ERR! 
npm ERR! System Darwin 14.0.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "fh-fhc"
```

**Comment by othiym23** [comment]
A lot is missing from this error log, but from what I can see, it looks like the version of npm you're using is quite old. What happens if you install a newer version of Node and then upgrade npm with `sudo npm install -g npm`?

**Comment by peeyushgoyal** [comment]
Thanks Othlym

I am also trying with new version but getting the same error.
my New Node -v version is v0.12.6 and npm -v 2.11.2.

Please help it is very urgent for me.
