### ISSUE TITLE
[npm install] EINVALIDTYPE when installing new module

### ISSUE THREAD

**Issue by williamboman** [npm/npm#8893]
I can't install new modules at all with `npm@3.1.1`.

e.g. `$ npm i gulp-sourcemaps --save-dev` 

```
0 info it worked if it ends with ok
1 verbose cli [ 'node',
1 verbose cli   '/Users/MarkZuckerberg/.nvm/versions/node/v0.12.6/bin/npm',
1 verbose cli   'i',
1 verbose cli   'gulp-sourcemaps',
1 verbose cli   '--save-dev' ]
2 info using npm@3.1.1
3 info using node@v0.12.6
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly install normalizeTree
8 silly loadCurrentTree Finishing
9 silly loadIdealTree Starting
10 silly install loadIdealTree
11 silly cloneCurrentTree Starting
12 silly install cloneCurrentTreeToIdealTree
13 silly cloneCurrentTree Finishing
14 silly loadShrinkwrap Starting
15 silly install loadShrinkwrap
16 silly loadShrinkwrap Finishing
17 silly loadAllDepsIntoIdealTree Starting
18 silly install loadAllDepsIntoIdealTree
19 verbose stack Error: Argument #1: Expected object but got string
19 verbose stack     at resolveWithNewModule (/Users/MarkZuckerberg/.nvm/versions/node/v0.12.6/lib/node_modules/npm/lib/install/deps.js:375:3)
19 verbose stack     at /Users/MarkZuckerberg/.nvm/versions/node/v0.12.6/lib/node_modules/npm/lib/install/deps.js:163:5
19 verbose stack     at /Users/MarkZuckerberg/.nvm/versions/node/v0.12.6/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
19 verbose stack     at Array.forEach (native)
19 verbose stack     at /Users/MarkZuckerberg/.nvm/versions/node/v0.12.6/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
19 verbose stack     at Array.forEach (native)
19 verbose stack     at asyncMap (/Users/MarkZuckerberg/.nvm/versions/node/v0.12.6/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
19 verbose stack     at exports.loadRequestedDeps (/Users/MarkZuckerberg/.nvm/versions/node/v0.12.6/lib/node_modules/npm/lib/install/deps.js:158:3)
19 verbose stack     at Array.<anonymous> (/Users/MarkZuckerberg/.nvm/versions/node/v0.12.6/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
19 verbose stack     at LOOP (/Users/MarkZuckerberg/.nvm/versions/node/v0.12.6/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
20 verbose cwd /Users/MarkZuckerberg/Workspace/facebook
21 error Darwin 14.4.0
22 error argv "node" "/Users/MarkZuckerberg/.nvm/versions/node/v0.12.6/bin/npm" "i" "gulp-sourcemaps" "--save-dev"
23 error node v0.12.6
24 error npm  v3.1.1
25 error code EINVALIDTYPE
26 error typeerror Error: Argument #1: Expected object but got string
26 error typeerror     at resolveWithNewModule (/Users/MarkZuckerberg/.nvm/versions/node/v0.12.6/lib/node_modules/npm/lib/install/deps.js:375:3)
26 error typeerror     at /Users/MarkZuckerberg/.nvm/versions/node/v0.12.6/lib/node_modules/npm/lib/install/deps.js:163:5
26 error typeerror     at /Users/MarkZuckerberg/.nvm/versions/node/v0.12.6/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
26 error typeerror     at Array.forEach (native)
26 error typeerror     at /Users/MarkZuckerberg/.nvm/versions/node/v0.12.6/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
26 error typeerror     at Array.forEach (native)
26 error typeerror     at asyncMap (/Users/MarkZuckerberg/.nvm/versions/node/v0.12.6/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
26 error typeerror     at exports.loadRequestedDeps (/Users/MarkZuckerberg/.nvm/versions/node/v0.12.6/lib/node_modules/npm/lib/install/deps.js:158:3)
26 error typeerror     at Array.<anonymous> (/Users/MarkZuckerberg/.nvm/versions/node/v0.12.6/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
26 error typeerror     at LOOP (/Users/MarkZuckerberg/.nvm/versions/node/v0.12.6/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
26 error typeerror This is an error with npm itself. Please report this error at:
26 error typeerror     <http://github.com/npm/npm/issues>
27 verbose exit [ 1, true ]
```

Same command works just fine with `npm@3.1.0`.

**Comment by lukeapage** [comment]
I see this too. Simple test case

```
mkdir test
cd test
npm i npm@2
```

**Comment by williamboman** [comment]
Too lazy to try if global installation works. (assuming it does since I could downgrade to `3.1.0`)

**Comment by aredridel** [comment]
This happened to me too.

```
:; npm i --save-dev webpack
npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "i" "--save-dev" "webpack"
npm ERR! node v0.12.4
npm ERR! npm  v3.1.1
npm ERR! code EINVALIDTYPE

npm ERR! typeerror Error: Argument #1: Expected object but got string
npm ERR! typeerror     at resolveWithNewModule (/usr/local/lib/node_modules/npm/lib/install/deps.js:375:3)
npm ERR! typeerror     at /usr/local/lib/node_modules/npm/lib/install/deps.js:163:5
npm ERR! typeerror     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
npm ERR! typeerror     at Array.forEach (native)
npm ERR! typeerror     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
npm ERR! typeerror     at Array.forEach (native)
npm ERR! typeerror     at asyncMap (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
npm ERR! typeerror     at exports.loadRequestedDeps (/usr/local/lib/node_modules/npm/lib/install/deps.js:158:3)
npm ERR! typeerror     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
npm ERR! typeerror     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ariastewart/Projects/dust-makara-helpers/npm-debug.log
```

**Comment by iarna** [comment]
Well huh, looks like local package installs are broken, but global work. Now what's _really_ embarrassing more generally is that the test suite is green. I'm... not sure how that is the case.

I will likely put out a 3.1.2 before next thursday w/ a fix for this so that the other stuff in 3.1.1 can get fixed.

**Comment by therealklanni** [comment]
Should 3.1.1 be unpublished in the meantime?

**Comment by iarna** [comment]
@thereaklanni: Seeing as its `-next` on a non-stable tag, I don't see any reason to do so. You have to REALLY go out of your way to get it.

**Comment by iarna** [comment]
I'm not supposed to be working today but I actually do have a fix for it. That part is easy. The thing that concerns me is that such a simple scenario didn't trigger the test suite, so I want to spend some time figuring out why that's the case. I mean, one of the VERY FIRST tests is to install npm itself, with itself...

**Comment by cchamberlain** [comment]
This isn't by chance an easy one-liner to fix somewhere is it?  I have npm setup via make link so that I can work on msys2 easier and I can see that something is causing the global install to run fetchPackageMetadata.  I attempted to dig around install.js and deps.js and all I can really find is that my local packages just have a pkg as a package name where as global ones have a full metadata object.

**Comment by iarna** [comment]
Yeah, fortunately you CAN revert back as global installs were unaffected. Also shrinkwrapped installs, FWIW.
