### ISSUE TITLE
Error: malformed token : sockit-angular

### ISSUE THREAD

**Issue by Tzrlk** [npm/npm#8919]
I'm having trouble deploying one of my libraries, and can't figure out what's causing the issue. Any idea what I'm doing wrong? Also, a failed deploy doesn't cause the build to fail, which would be handy.

**npm-debug.log**

```
0 info it worked if it ends with ok
1 verbose cli [ '/home/travis/.nvm/v0.10.40/bin/node',
1 verbose cli   '/home/travis/.nvm/v0.10.40/bin/npm',
1 verbose cli   'publish' ]
2 info using npm@1.4.28
3 info using node@v0.10.40
4 verbose publish [ '.' ]
5 verbose cache add [ '.', null ]
6 verbose cache add name=undefined spec="." args=[".",null]
7 verbose parsed url { protocol: null,
7 verbose parsed url   slashes: null,
7 verbose parsed url   auth: null,
7 verbose parsed url   host: null,
7 verbose parsed url   port: null,
7 verbose parsed url   hostname: null,
7 verbose parsed url   hash: null,
7 verbose parsed url   search: null,
7 verbose parsed url   query: null,
7 verbose parsed url   pathname: '.',
7 verbose parsed url   path: '.',
7 verbose parsed url   href: '.' }
8 silly lockFile 3a52ce78- .
9 verbose lock . /home/travis/.npm/3a52ce78-.lock
10 verbose tar pack [ '/home/travis/.npm/sockit-angular/0.1.0-alpha.1/package.tgz',
10 verbose tar pack   '.' ]
11 verbose tarball /home/travis/.npm/sockit-angular/0.1.0-alpha.1/package.tgz
12 verbose folder .
13 info prepublish sockit-angular@0.1.0-alpha.1
14 silly lockFile 1f1177db-tar tar://.
15 verbose lock tar://. /home/travis/.npm/1f1177db-tar.lock
16 silly lockFile aa4db5ab-ngular-0-1-0-alpha-1-package-tgz tar:///home/travis/.npm/sockit-angular/0.1.0-alpha.1/package.tgz
17 verbose lock tar:///home/travis/.npm/sockit-angular/0.1.0-alpha.1/package.tgz /home/travis/.npm/aa4db5ab-ngular-0-1-0-alpha-1-package-tgz.lock
18 silly lockFile 1f1177db-tar tar://.
19 silly lockFile 1f1177db-tar tar://.
20 silly lockFile aa4db5ab-ngular-0-1-0-alpha-1-package-tgz tar:///home/travis/.npm/sockit-angular/0.1.0-alpha.1/package.tgz
21 silly lockFile aa4db5ab-ngular-0-1-0-alpha-1-package-tgz tar:///home/travis/.npm/sockit-angular/0.1.0-alpha.1/package.tgz
22 silly lockFile 429b3fe7-it-angular-0-1-0-alpha-1-package /home/travis/.npm/sockit-angular/0.1.0-alpha.1/package
23 verbose lock /home/travis/.npm/sockit-angular/0.1.0-alpha.1/package /home/travis/.npm/429b3fe7-it-angular-0-1-0-alpha-1-package.lock
24 silly lockFile 429b3fe7-it-angular-0-1-0-alpha-1-package /home/travis/.npm/sockit-angular/0.1.0-alpha.1/package
25 silly lockFile 429b3fe7-it-angular-0-1-0-alpha-1-package /home/travis/.npm/sockit-angular/0.1.0-alpha.1/package
26 silly lockFile 3a52ce78- .
27 silly lockFile 3a52ce78- .
28 silly publish { name: 'sockit-angular',
28 silly publish   version: '0.1.0-alpha.1',
28 silly publish   description: 'Angular directives and services for use with sockit.',
28 silly publish   homepage: 'https://github.com/aetheric/sockit-angular',
28 silly publish   author:
28 silly publish    { name: 'Peter Cummuskey',
28 silly publish      email: 'peterc@aetheric.co.nz',
28 silly publish      url: 'http://gplus.to/tzrlk/' },
28 silly publish   license: 'MIT',
28 silly publish   main: 'src/main/sockit-module.js',
28 silly publish   keywords: [ 'session', 'websocket', 'html5', 'sockit', 'angular' ],
28 silly publish   scripts: { build: 'gulp build', test: 'gulp test' },
28 silly publish   repository:
28 silly publish    { type: 'git',
28 silly publish      url: 'git@github.com:aetheric/sockit-angular.git' },
28 silly publish   bugs: { url: 'https://github.com/aetheric/sockit-angular/issues' },
28 silly publish   devDependencies:
28 silly publish    { angular: '^1.4.1',
28 silly publish      chai: '^3.0.0',
28 silly publish      gulp: '^3.8.11',
28 silly publish      'gulp-browserify': '^0.5.1',
28 silly publish      'gulp-istanbul': '^0.10.0',
28 silly publish      'gulp-mocha': '^2.0.1',
28 silly publish      'gulp-rename': '^1.2.2',
28 silly publish      'gulp-sourcemaps': '^1.5.2',
28 silly publish      'gulp-uglify': '^1.2.0',
28 silly publish      'gulp-util': '^3.0.4',
28 silly publish      karma: '^0.12.36',
28 silly publish      mocha: '^2.2.5',
28 silly publish      phantomjs: '^1.9.17',
28 silly publish      sinon: '^1.15.3',
28 silly publish      sockit: '^0.1.0',
28 silly publish      through2: '^2.0.0',
28 silly publish      'vinyl-buffer': '^1.0.0' },
28 silly publish   gitHead: '9eaf6b50d8d9b60a5f3c06e1b9e289e42b80c90f',
28 silly publish   readme: 'SOCKIT-ANGULAR\n==============\n\nimage:https://travis-ci.org/aetheric/sockit-angular.svg?branch=master["Build Status", link="https://travis-ci.org/aetheric/sockit-angular"]\n\nAngular directives and services for use with sockit.\n',
28 silly publish   readmeFilename: 'README.adoc',
28 silly publish   _id: 'sockit-angular@0.1.0-alpha.1',
28 silly publish   _shasum: 'a10a12e50691365ec566f1cf7d38fd2a5290337e',
28 silly publish   _from: '.' }
29 verbose request where is /sockit-angular
30 verbose request registry https://registry.npmjs.org/
31 verbose request id 133e8f69405c4573
32 verbose url raw /sockit-angular
33 verbose url resolving [ 'https://registry.npmjs.org/', './sockit-angular' ]
34 verbose url resolved https://registry.npmjs.org/sockit-angular
35 verbose request where is https://registry.npmjs.org/sockit-angular
36 info trying registry request attempt 1 at 23:10:12
37 http PUT https://registry.npmjs.org/sockit-angular
38 http 500 https://registry.npmjs.org/sockit-angular
39 info retry will retry, error on last attempt: Error: malformed token : sockit-angular
40 info trying registry request attempt 2 at 23:10:23
41 http PUT https://registry.npmjs.org/sockit-angular
42 http 500 https://registry.npmjs.org/sockit-angular
43 info retry will retry, error on last attempt: Error: malformed token : sockit-angular
44 info trying registry request attempt 3 at 23:11:23
45 http PUT https://registry.npmjs.org/sockit-angular
46 http 500 https://registry.npmjs.org/sockit-angular
47 verbose headers { 'content-type': 'application/json',
47 verbose headers   'cache-control': 'max-age=0',
47 verbose headers   'content-length': '27',
47 verbose headers   'accept-ranges': 'bytes',
47 verbose headers   date: 'Sun, 12 Jul 2015 23:11:23 GMT',
47 verbose headers   via: '1.1 varnish',
47 verbose headers   connection: 'keep-alive',
47 verbose headers   'x-served-by': 'cache-atl6221-ATL',
47 verbose headers   'x-cache': 'MISS',
47 verbose headers   'x-cache-hits': '0',
47 verbose headers   'x-timer': 'S1436742683.490905,VS0,VE64' }
48 error publish Failed PUT 500
49 error Error: malformed token : sockit-angular
49 error     at RegClient.<anonymous> (/home/travis/.nvm/v0.10.40/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:308:14)
49 error     at Request._callback (/home/travis/.nvm/v0.10.40/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:246:65)
49 error     at Request.self.callback (/home/travis/.nvm/v0.10.40/lib/node_modules/npm/node_modules/request/request.js:236:22)
49 error     at Request.emit (events.js:98:17)
49 error     at Request.<anonymous> (/home/travis/.nvm/v0.10.40/lib/node_modules/npm/node_modules/request/request.js:1142:14)
49 error     at Request.emit (events.js:117:20)
49 error     at IncomingMessage.<anonymous> (/home/travis/.nvm/v0.10.40/lib/node_modules/npm/node_modules/request/request.js:1096:12)
49 error     at IncomingMessage.emit (events.js:117:20)
49 error     at _stream_readable.js:944:16
49 error     at process._tickCallback (node.js:448:13)
50 error If you need help, you may report this *entire* log,
50 error including the npm and node versions, at:
50 error     <http://github.com/npm/npm/issues>
51 error System Linux 3.13.0-40-generic
52 error command "/home/travis/.nvm/v0.10.40/bin/node" "/home/travis/.nvm/v0.10.40/bin/npm" "publish"
53 error cwd /home/travis/build/aetheric/sockit-angular
54 error node -v v0.10.40
55 error npm -v 1.4.28
56 verbose exit [ 1, true ]
```

**Comment by othiym23** [comment]
This looks like an issue with an old version of npm (`npm@1.4.28` is about a year old at this point – the latest stable version is `npm@2.13.0`), but the registry shouldn't be failing here. @bcoe, do you have any idea what might cause this error to be returned?

**Comment by bcoe** [comment]
This is a new one for me, let's keep any eye on this; I believe this error is thrown by the auth-service if it fails to parse the basic auth header.
