### ISSUE TITLE
Npm run script doesn't work !!

### ISSUE THREAD

**Issue by shivekkhurana** [npm/npm#8925]
I have the following in my package.json file 
```
{
   ...
    "scripts": {
       "ujs": "uglifyjs assets/js/jquery.min.js assets/js/main.js assets/js/ie10-viewport-  bug-workaround.js -o dist/build.js",
       "ccss": "cleancss assets/css/style.css -o dist/build.css"
     },
   ...
}
```

but when I try to run the following command : 
```
$ npm run ujs
```
I get this error : 
```
npm ERR! Linux 3.19.0-21-generic
npm ERR! argv "node" "/usr/local/bin/npm" "run" "ujs"
npm ERR! node v0.12.0
npm ERR! npm  v2.7.0

npm ERR! missing script: ujs
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/shivekkhurana/D/projects/rewave/rewave.github.io/npm-debug.log

```

Here is the debug.log : 

```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'run', 'ujs' ]
2 info using npm@2.7.0
3 info using node@v0.12.0
4 verbose stack Error: missing script: ujs
4 verbose stack     at run (/usr/local/lib/node_modules/npm/lib/run-script.js:165:19)
4 verbose stack     at /usr/local/lib/node_modules/npm/lib/run-script.js:81:5
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:51:40
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:375:33
4 verbose stack     at checkBinReferences_ (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:340:59)
4 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:372:17)
4 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:126:33)
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:331:40
4 verbose stack     at evalmachine.<anonymous>:336:14
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:102:5
5 verbose cwd /home/shivekkhurana/D/projects/rewave/rewave.github.io
6 error Linux 3.19.0-21-generic
7 error argv "node" "/usr/local/bin/npm" "run" "ujs"
8 error node v0.12.0
9 error npm  v2.7.0
10 error missing script: ujs
11 error If you need help, you may report this error at:
11 error     <http://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

```

How to fix this ? Scripts were working for recent projects but stopped working when I created a new one. Please help.

**Comment by sinkingshriek** [comment]
Quick question. Where are you running `npm run ujs` from? It sounds obvious but can you try the same command from the root of your node project (the same dir where `package.json` is)?

**Comment by williamboman** [comment]
If [the live repo](https://github.com/rewave/rewave.github.io/blob/master/package.json) is the same you're working on, then you have a duplicate `"scripts"` key, the second one overrides your first.

**Comment by sinkingshriek** [comment]
@williamboman good find. :+1:

**Comment by shivekkhurana** [comment]
Thank you @williamboman.

**Comment by respectYourNeighbour** [comment]
@williamboman spot on!
