### ISSUE TITLE
Attempt to unlock /usr/local/lib/node_modules/anyproxy, which hasn't been locked

### ISSUE THREAD

**Issue by zhangxiaang** [npm/npm#8937]
```
39 verbose stack     at cb (/usr/local/lib/node_modules/npm/lib/install.js:1017:5)
39 verbose stack     at /usr/local/lib/node_modules/npm/lib/install.js:1021:20
39 verbose stack     at /usr/local/lib/node_modules/npm/lib/utils/locker.js:40:9
39 verbose stack     at cb (/usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:149:38)
39 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:227:24
39 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:177:38
39 verbose stack     at FSReqWrap.oncomplete (fs.js:95:15)
40 verbose cwd /Users/qiansheng
41 error Darwin 14.0.0
42 error argv "node" "/usr/local/bin/npm" "install" "-g" "anyproxy"
43 error node v0.12.7
44 error npm  v2.11.3
45 error Attempt to unlock /usr/local/lib/node_modules/anyproxy, which hasn't been locked
46 error If you need help, you may report this error at:
46 error     <https://github.com/npm/npm/issues>
47 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
@zhangxiaang Could you upload the _full_ `npm-debug.log` as a [gist](https://gist.github.com/)?

**Comment by zhangxiaang** [comment]
@KenanY  thank u!!!
this problem had resolved, becoz of the Permission problem

**Comment by ehsalazar** [comment]
Good to hear. I'll close this for now as we’re trying to clean up some old issues. We’ll be happy to reopen if necessary.
