### ISSUE TITLE
npm install -g newman

### ISSUE THREAD

**Issue by Raviadonis** [npm/npm#8949]
I'm getting the below error while installing newman tool with npm.

```
C:\Users\rsomusu>npm install -g newman
\


> contextify@0.1.14 install C:\Users\rsomusu\AppData\Roaming\npm\node_modules\ne
wman\node_modules\jsdom\node_modules\contextify
> node-gyp rebuild


C:\Users\rsomusu\AppData\Roaming\npm\node_modules\newman\node_modules\jsdom\node_modules\contextify>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.Cpp.Platform.targets(44,5): error MSB8020: The builds tools for v120 (Platform Toolset = 'v120') cannot be found. To build using the v120 build tools, either click the Project menu or right-click the solution, and then select "Update VC++ Projects...". Install v120 to build using the v120 build tools. [C:\Users\rsomusu\AppData\Roaming\npm\node_modules\newman\node_modules\jsdom\node_modules\contextify\build|\contextify.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\rsomusu\AppData\Roaming\npm\node_modules\newman\node_modules\jsdom\node_modules\contextify
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "newman"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! contextify@0.1.14 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the contextify@0.1.14 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the contextify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls contextify
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\rsomusu\npm-debug.log
```

**Comment by DENIELER** [comment]
Same issue.. before that it shows that PYTHON variable is not set in PATH

**Comment by cchamberlain** [comment]
It's executing node-gyp to build native module contextify and failing because it isn't finding it where it expects.  Ensure you have all the prerequisites required for your version of windows here- https://github.com/TooTallNate/node-gyp - I'd recommend using 32 bit node for development.  

@denieler, ensure you have Python 2.7 installed and set an environment variable PYTHON=2.7. Ensure it is in your path by typing Python in terminal. Python3.x will fail.

**Comment by DENIELER** [comment]
@cchamberlain I've isntalled Python 2.7, but now node-gyp had failed .. it is strange, because I didn't do any changes in code or in packages.config..

**Comment by yiweig** [comment]
+1

**Comment by luffykou** [comment]
**I have installed newman with npm:**

```
C:\Windows\system32>npm install newman -g
-
> newman@2.1.2 preinstall C:\Program Files\nodejs\node_global\node_modules\newma
n
> node ./scripts/preinstall.js

******************************************************************
*                           Notice                               *
******************************************************************
*  If you are using Node v0.12 or v0.10, you should install      *
*  Newman v1.x:                                                  *
*                                                                *
*                   npm install newman@1                         *
*                                                                *
*  Deprecation: Newman v3 onwards will deprecate the use of DOM  *
*  related libraries, such as JQuery and Backbone. For details,  *
*  check https://www.getpostman.com/docs/sandbox                 *
******************************************************************
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie h
ttps://nodesecurity.io/advisories/130
C:\Program Files\nodejs\node_global\newman -> C:\Program Files\nodejs\node_globa
l\node_modules\newman\bin\newman
newman@2.1.2 C:\Program Files\nodejs\node_global\node_modules\newman
├── underscore@1.8.3
├── backbone@1.3.3
├── atob@1.1.2
├── btoa@1.1.2
├── tv4@1.2.7
├── node-uuid@1.4.1
├── commander@2.9.0 (graceful-readlink@1.0.1)
├── dot@1.0.3
├── jsface@2.2.0
├── mkdirp@0.5.1 (minimist@0.0.8)
├── aws4@1.3.1 (lru-cache@4.0.1)
├── crypto-js@3.1.6
├── hawk@3.1.2 (cryptiles@2.0.5, boom@2.10.1, sntp@1.0.9, hoek@2.16.3)
├── sugar@1.3.9
├── jquery@2.1.1
├── json5@0.4.0
├── request@2.72.0 (aws-sign2@0.6.0, tunnel-agent@0.4.3, oauth-sign@0.8.2, fo
rever-agent@0.6.1, is-typedarray@1.0.0, caseless@0.11.0, stringstream@0.0.5, iss
tream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, tough-cookie@2.2.2, node-u
uid@1.4.7, qs@6.1.0, combined-stream@1.0.5, form-data@1.0.0-rc4, mime-types@2.1.
11, hawk@3.1.3, bl@1.1.2, http-signature@1.1.1, har-validator@2.0.6)
├── unirest@0.4.2 (mime@1.2.11, form-data@0.2.0, request@2.51.0)
├── postman_validator@0.0.4 (JSV@4.0.2)
├── cli-color@0.2.3 (memoizee@0.2.6, es5-ext@0.9.2)
├── lodash@3.10.1
├── jsdom@7.1.0 (webidl-conversions@2.0.1, acorn-globals@1.0.9, abab@1.0.3, x
ml-name-validator@2.0.1, symbol-tree@3.1.4, tough-cookie@2.3.1, nwmatcher@1.3.8,
 cssom@0.3.1, whatwg-url-compat@0.6.5, parse5@1.5.1, acorn@2.7.0, htmlparser2@3.
9.1, escodegen@1.8.0, cssstyle@0.2.36)
├── postman-collection-transformer@1.7.3 (strip-json-comments@1.0.2, semver@5
.1.0, commander@2.8.1, intel@1.0.2, lodash@3.10.0)
└── xml2js@0.4.17 (sax@1.2.1, xmlbuilder@4.2.1)
```

**but it doesn't work, why??**

C:\Windows\system32>`newman`
'newman' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
