### ISSUE TITLE
Nmp error in Newman "stream.js:94, throw er; // Unhandled stream error in pipe. Error: EISDIR, read"

### ISSUE THREAD

**Issue by spiroskgr** [npm/npm#8955]
I downloaded Newman in order to be able to download files using the collection runner. However, after trying to run a collection I always receive the following error:

```
Iteration 1 of 1
stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: EISDIR, read
    at Error (native)
spyros@spyros-SZ77:~/npm-global/lib/node_modules/newman/bin$ 
```

The  npm-debug.log file gives me the following results:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'show',
1 verbose cli   'newman',
1 verbose cli   'version' ]
2 info using npm@2.11.3
3 info using node@v0.12.7
4 silly mapToRegistry name newman
5 silly mapToRegistry using default registry
6 silly mapToRegistry registry https://registry.npmjs.org/
7 silly mapToRegistry uri https://registry.npmjs.org/newman
8 verbose request uri https://registry.npmjs.org/newman
9 verbose request no auth needed
10 info attempt registry request try #1 at 15:49:51
11 verbose request id 8c73dcb85fb118ca
12 verbose etag "1F6L5R7NSLRPHX2OBX4Z3T1OK"
13 http request GET https://registry.npmjs.org/newman
14 http 304 https://registry.npmjs.org/newman
15 silly get cb [ 304,
15 silly get   { date: 'Wed, 15 Jul 2015 14:49:50 GMT',
15 silly get     via: '1.1 varnish',
15 silly get     'cache-control': 'max-age=60',
15 silly get     etag: '"1F6L5R7NSLRPHX2OBX4Z3T1OK"',
15 silly get     age: '29',
15 silly get     connection: 'keep-alive',
15 silly get     'x-served-by': 'cache-lcy1120-LCY',
15 silly get     'x-cache': 'HIT',
15 silly get     'x-cache-hits': '1',
15 silly get     'x-timer': 'S1436971790.397512,VS0,VE0',
15 silly get     vary: 'Accept' } ]
16 verbose etag https://registry.npmjs.org/newman from cache
17 verbose get saving newman to /home/spyros/.npm/registry.npmjs.org/newman/.cache.json
18 verbose exit [ 0, true ]
19 verbose stack Error: write EPIPE
19 verbose stack     at exports._errnoException (util.js:746:11)
19 verbose stack     at WriteWrap.afterWrite (net.js:775:14)
20 verbose cwd /home/spyros/npm-global/lib/node_modules/newman/bin
21 error Linux 3.13.0-57-generic
22 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "show" "newman" "version"
23 error node v0.12.7
24 error npm  v2.11.3
25 error code EPIPE
26 error errno EPIPE
27 error syscall write
28 error write EPIPE
29 error If you need help, you may report this error at:
29 error     <https://github.com/npm/npm/issues>
30 verbose exit [ 1, true ]
```

Any ideas on what is going wrong?

**Comment by othiym23** [comment]
```
19 verbose stack Error: write EPIPE
19 verbose stack     at exports._errnoException (util.js:746:11)
19 verbose stack     at WriteWrap.afterWrite (net.js:775:14)
```

It looks like you encountered a transient network error. Does this happen repeatably?

**Comment by spiroskgr** [comment]
Yes, it happens repeatedly every time I try to run a collection.

**Comment by kevincennis** [comment]
I'm fairly sure I've fixed this in a PR:

https://github.com/kevincennis/newman/commit/43cedcf72c5c5bf793ba593eee4732197c63069a
