### ISSUE TITLE
ENOENT Error installing global module / Missing dep in state left afterward

### ISSUE THREAD

**Issue by aredridel** [npm/npm#8957]
This is perfectly installable with npm 2.

```
:; npm i generator-kraken -g --prefix=/usr/local
npm WARN install:readable-stream Couldn't install optional dependency: ENOENT, rename '/usr/local/lib/node_modules/generator-kraken/node_modules/yeoman-generator/node_modules/html-wiring/node_modules/cheerio/node_modules/htmlparser2/node_modules/readable-stream'

> spawn-sync@1.0.11 postinstall /usr/local/lib/node_modules/generator-kraken/node_modules/spawn-sync
> node postinstall

- htmlparser2@3.8.3 node_modules/generator-kraken/node_modules/yeoman-generator/node_modules/html-wiring/node_modules/cheerio/node_modules/htmlparser2
- indent-string@1.2.1 node_modules/generator-kraken/node_modules/yeoman-generator/node_modules/dateformat/node_modules/meow/node_modules/indent-string
- meow@3.3.0 node_modules/generator-kraken/node_modules/yeoman-generator/node_modules/dateformat/node_modules/meow
- inquirer@0.8.5 node_modules/generator-kraken/node_modules/yeoman-generator/node_modules/inquirer
readable-stream@1.1.13 node_modules/generator-kraken/node_modules/yeoman-generator/node_modules/html-wiring/node_modules/cheerio/node_modules/htmlparser2/node_modules/readable-stream -> node_modules/generator-kraken/node_modules/duplexer2/node_modules/readable-stream
readable-stream@1.0.33 node_modules/generator-kraken/node_modules/yeoman-generator/node_modules/through2/node_modules/readable-stream -> node_modules/generator-kraken/node_modules/stream-combiner2/node_modules/readable-stream
spawn-sync@1.0.11 node_modules/generator-kraken/node_modules/yeoman-generator/node_modules/cross-spawn/node_modules/spawn-sync -> node_modules/generator-kraken/node_modules/spawn-sync
cross-spawn@0.4.1 node_modules/generator-kraken/node_modules/yeoman-generator/node_modules/cross-spawn -> node_modules/generator-kraken/node_modules/cross-spawn
through2@0.6.5 node_modules/generator-kraken/node_modules/yeoman-generator/node_modules/through2 -> node_modules/generator-kraken/node_modules/through2
cheerio@0.19.0 node_modules/generator-kraken/node_modules/yeoman-generator/node_modules/html-wiring/node_modules/cheerio -> node_modules/generator-kraken/node_modules/cheerio
html-wiring@1.1.0 node_modules/generator-kraken/node_modules/yeoman-generator/node_modules/html-wiring -> node_modules/generator-kraken/node_modules/html-wiring
semver-diff@2.0.0 node_modules/generator-kraken/node_modules/update-notifier/node_modules/semver-diff -> node_modules/generator-kraken/node_modules/semver-diff
configstore@0.3.2 node_modules/generator-kraken/node_modules/update-notifier/node_modules/configstore -> node_modules/generator-kraken/node_modules/configstore
pretty-bytes@1.0.4 node_modules/generator-kraken/node_modules/yeoman-generator/node_modules/pretty-bytes -> node_modules/generator-kraken/node_modules/pretty-bytes
dateformat@1.0.11 node_modules/generator-kraken/node_modules/yeoman-generator/node_modules/dateformat -> node_modules/generator-kraken/node_modules/dateformat
glob@4.3.5 node_modules/generator-kraken/node_modules/yeoman-generator/node_modules/findup-sync/node_modules/glob -> node_modules/generator-kraken/node_modules/findup-sync/node_modules/glob
findup-sync@0.2.1 node_modules/generator-kraken/node_modules/yeoman-generator/node_modules/findup-sync -> node_modules/generator-kraken/node_modules/findup-sync
run-async@0.1.0 node_modules/generator-kraken/node_modules/yeoman-generator/node_modules/run-async -> node_modules/generator-kraken/node_modules/run-async
gh-got@1.1.0 node_modules/generator-kraken/node_modules/yeoman-generator/node_modules/github-username/node_modules/gh-got -> node_modules/generator-kraken/node_modules/gh-got
github-username@2.0.0 node_modules/generator-kraken/node_modules/yeoman-generator/node_modules/github-username -> node_modules/generator-kraken/node_modules/github-username
rc@1.0.3 node_modules/generator-kraken/node_modules/update-notifier/node_modules/latest-version/node_modules/package-json/node_modules/registry-url/node_modules/rc -> node_modules/generator-kraken/node_modules/rc
registry-url@3.0.3 node_modules/generator-kraken/node_modules/update-notifier/node_modules/latest-version/node_modules/package-json/node_modules/registry-url -> node_modules/generator-kraken/node_modules/registry-url
package-json@1.2.0 node_modules/generator-kraken/node_modules/update-notifier/node_modules/latest-version/node_modules/package-json -> node_modules/generator-kraken/node_modules/package-json
latest-version@1.0.1 node_modules/generator-kraken/node_modules/update-notifier/node_modules/latest-version -> node_modules/generator-kraken/node_modules/latest-version
/usr/local/lib
└── (empty)

npm WARN EPEERINVALID generator-kraken@2.0.0 requires a peer of yo@^1.4.7 but none was installed.
npm WARN EPACKAGEJSON /usr/local/lib No description
npm WARN EPACKAGEJSON /usr/local/lib No repository field.
npm WARN EPACKAGEJSON /usr/local/lib No README data
npm WARN EPACKAGEJSON /usr/local/lib No license field.
npm ERR! code 1```

Afterward, trying to use the module, the 'download' dependency is missing:

```
:; yo kraken:layout test
module.js:338
    throw err;
          ^
Error: Cannot find module 'download'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-kraken/node_modules/yeoman-generator/lib/actions/fetch.js:3:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

**Comment by iarna** [comment]
It looks like you're upgrading or reinstalling `generator-kraken` in /usr/local, or else I don't see how it'd be removing things...

```
- htmlparser2@3.8.3 node_modules/generator-kraken/node_modules/yeoman-generator/node_modules/html-wiring/node_modules/cheerio/node_modules/htmlparser2
- indent-string@1.2.1 node_modules/generator-kraken/node_modules/yeoman-generator/node_modules/dateformat/node_modules/meow/node_modules/indent-string
- meow@3.3.0 node_modules/generator-kraken/node_modules/yeoman-generator/node_modules/dateformat/node_modules/meow
- inquirer@0.8.5 node_modules/generator-kraken/node_modules/yeoman-generator/node_modules/inquirer
```

**Comment by iarna** [comment]
So, this doesn't reproduce as-is for me... I tried reproducing this no node v0.10.38 w/ npm v3.1.2 on Windows (for reasons) and I did get a yeoman error, but a very different one:

```
C:\foo>you kraken:layout test
Native thread-sleep not available.
This will result in much slower performance.
You should re-install spawn-sync if possible.
Check C:\Program Files (x86)\nodejs\node_modules\generator-kraken\node_modules\s
pawn-sync\error.log for more details

events.js:72
        throw er; // Unhandled 'error' event
              ^
ReferenceError: C:\Program Files (x86)\nodejs\node_modules\generator-kraken\layout\templates\layout.dust:6
    4|         <meta charset="utf-8" />
    5|         <title>{+title /}</title>
 >> 6|     <% if (cssModule) { %>
    7|         <link rel="stylesheet" href="/css/app.css">
    8|     <% } %>
    9|     </head>

cssModule is not defined
    at eval (eval at <anonymous> (C:\Program Files (x86)\nodejs\node_modules\generator-kraken\node_modules\ejs\lib\ejs.js:460:12), <anonymous>:10:12)
    at returnedFn (C:\Program Files (x86)\nodejs\node_modules\generator-kraken\node_modules\ejs\lib\ejs.js:489:17)
    at Object.exports.render (C:\Program Files (x86)\nodejs\node_modules\generator-kraken\node_modules\ejs\lib\ejs.js:315:37)
    at copy.process (C:\Program Files (x86)\nodejs\node_modules\generator-kraken\node_modules\mem-fs-editor\actions\copy-tpl.js:18:18)
    at applyProcessingFunc (C:\Program Files (x86)\nodejs\node_modules\generator-kraken\node_modules\mem-fs-editor\actions\copy.js:13:16)
    at EditionInterface.exports._copySingle (C:\Program Files (x86)\nodejs\node_modules\generator-kraken\node_modules\mem-fs-editor\actions\copy.js:56:24)
    at EditionInterface.exports.copy (C:\Program Files (x86)\nodejs\node_modules\generator-kraken\node_modules\mem-fs-editor\actions\copy.js:23:17)
    at EditionInterface.module.exports [as copyTpl] (C:\Program Files (x86)\nodejs\node_modules\generator-kraken\node_modules\mem-fs-editor\actions\copy-tpl.js: 16:8)
    at files (C:\Program Files (x86)\nodejs\node_modules\generator-kraken\layout\index.js:34:17)
    at C:\Program Files (x86)\nodejs\node_modules\generator-kraken\node_modules\yeoman-generator\lib\base.js:429:16
```

**Comment by mikemaccana** [comment]
Got the same thing too, trying to install node-inspector. Weirdly I just re-ran the same command with `-dd` to paste here and it worked a second time. Alas I no longer have console output from first time when it failed. Sorry, I wish this comment was more useful than 'me too'.

**Comment by aredridel** [comment]
Aha! I think I know what's going on.

```
:; npm i copy-browser-modules
- readable-stream@2.0.2 node_modules/through2-filter/node_modules/readable-stream
mkdirp@0.5.1 node_modules/vinyl-fs/node_modules/mkdirp -> node_modules/copy-browser-modules/node_modules/mkdirp
- readable-stream@2.0.2 node_modules/duplexify/node_modules/readable-stream
- through2@2.0.0 node_modules/through2-filter/node_modules/through2
- minimatch@2.0.10 node_modules/glob-stream/node_modules/minimatch
- graceful-fs@3.0.8 node_modules/vinyl-fs/node_modules/graceful-fs
- first-chunk-stream@1.0.0 node_modules/first-chunk-stream
minimist@0.0.8 node_modules/vinyl-fs/node_modules/minimist -> node_modules/fstream/node_modules/minimist
- glob@4.5.3 node_modules/glob-stream/node_modules/glob
- through2-filter@2.0.0 node_modules/through2-filter
- end-of-stream@1.0.0 node_modules/end-of-stream
- unique-stream@2.2.0 node_modules/unique-stream
- merge-stream@0.1.8 node_modules/merge-stream
- glob-stream@4.1.1 node_modules/glob-stream
- clone@0.2.0 node_modules/vinyl/node_modules/clone
- duplexify@3.4.2 node_modules/duplexify
- is-utf8@0.2.0 node_modules/is-utf8
- strip-bom@1.0.0 node_modules/strip-bom
- vinyl@0.4.6 node_modules/vinyl
- gaze@0.5.1 node_modules/gaze
- glob-watcher@0.0.8 node_modules/glob-watcher
- vinyl-fs@1.0.0 node_modules/vinyl-fs
upgradedsamplenodeweb@1.0.3 /Users/ariastewart/Projects/sample-app
├── fstream-npm@1.0.4  extraneous
├─┬ grunt-ci-suite@0.1.9
│ └─┬ istanbul@0.3.17
│   ├─┬ fileset@0.2.1
│   │ └── minimatch@2.0.10
│   └── mkdirp@0.5.1
├─┬ grunt-gulp@0.1.0
│ └─┬ gulp@3.2.5
│   └─┬ glob-stream@3.1.18
│     └── minimatch@2.0.10
├─┬ kraken-devtools@1.3.0
│ └─┬ rimraf@2.4.2
│   └─┬ glob@5.0.14
│     └── minimatch@2.0.10
├─┬ less@1.7.5
│ ├── graceful-fs@3.0.8
│ └── mkdirp@0.5.1
├─┬ makara-amdify@1.1.5
│ ├─┬ glob@4.5.3
│ │ └── minimatch@2.0.10
│ ├── mkdirp@0.5.1
│ └─┬ spundle@1.0.3
│   └─┬ glob@4.5.3
│     └── minimatch@2.0.10
└─┬ topos@0.3.5
  └─┬ curlnsave@0.1.5
    └─┬ fs-extra@0.16.5
      └── graceful-fs@3.0.8

npm WARN EPACKAGEJSON upgradedsamplenodeweb@1.0.3 No repository field.
npm WARN EPACKAGEJSON upgradedsamplenodeweb@1.0.3 No license field.
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "i" "copy-browser-modules"
npm ERR! node v0.12.7
npm ERR! npm  v3.2.0
npm ERR! path /Users/ariastewart/Projects/sample-app/node_modules/vinyl-fs/node_modules/mkdirp
npm ERR! code ENOENT
npm ERR! errno -2

npm ERR! enoent ENOENT, rename '/Users/ariastewart/Projects/sample-app/node_modules/vinyl-fs/node_modules/mkdirp'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ariastewart/Projects/sample-app/npm-debug.log
ariastewart@LM-BOS-00872654:sample-app (new-content:2fca520 Δ )
:; npm i copy-browser-modules
upgradedsamplenodeweb@1.0.3 /Users/ariastewart/Projects/sample-app
├─┬ grunt-ci-suite@0.1.9
│ └─┬ istanbul@0.3.17
│   ├─┬ fileset@0.2.1
│   │ └── minimatch@2.0.10
│   └─┬ mkdirp@0.5.1
│     └── minimist@0.0.8
├─┬ grunt-copy-browser-modules@2.0.1
│ └─┬ copy-browser-modules@1.1.3
│   ├─┬ fstream@1.0.7
│   │ ├── graceful-fs@3.0.8
│   │ └─┬ mkdirp@0.5.1
│   │   └── minimist@0.0.8
│   ├─┬ fstream-npm@1.0.4
│   │ └─┬ fstream-ignore@1.0.2
│   │   └── minimatch@2.0.10
│   ├─┬ mkdirp@0.5.1
│   │ └── minimist@0.0.8
│   └─┬ read-package-tree@4.1.0
│     ├─┬ read-package-json@2.0.0
│     │ └─┬ glob@5.0.14
│     │   └── minimatch@2.0.10
│     └─┬ readdir-scoped-modules@1.0.1
│       └── graceful-fs@3.0.8
├─┬ grunt-gulp@0.1.0
│ └─┬ gulp@3.2.5
│   └─┬ glob-stream@3.1.18
│     └── minimatch@2.0.10
├─┬ kraken-devtools@1.3.0
│ └─┬ rimraf@2.4.2
│   └─┬ glob@5.0.14
│     └── minimatch@2.0.10
├─┬ less@1.7.5
│ ├── graceful-fs@3.0.8
│ └─┬ mkdirp@0.5.1
│   └── minimist@0.0.8
├─┬ makara-amdify@1.1.5
│ ├─┬ glob@4.5.3
│ │ └── minimatch@2.0.10
│ ├─┬ mkdirp@0.5.1
│ │ └── minimist@0.0.8
│ └─┬ spundle@1.0.3
│   └─┬ glob@4.5.3
│     └── minimatch@2.0.10
├─┬ mocha@2.2.5
│ └─┬ mkdirp@0.5.0
│   └── minimist@0.0.8
└─┬ topos@0.3.5
  └─┬ curlnsave@0.1.5
    └─┬ fs-extra@0.16.5
      └── graceful-fs@3.0.8

npm WARN EPACKAGEJSON upgradedsamplenodeweb@1.0.3 No repository field.
npm WARN EPACKAGEJSON upgradedsamplenodeweb@1.0.3 No license field.
```

What's going on here is that I'm installing an updated version of a dependency, `copy-browser-modules`. The previously installed version has dependencies on things that themselves have dependencies on `mkdirp`. The new version directly depends on `mkdirp`, but it's scheduled for removal by the removal of the sub-dependency that's no longer needed.
