### ISSUE TITLE
Error when publishing new package version

### ISSUE THREAD

**Issue by 39dotyt** [npm/npm#8959]
I'm trying to update my package into npm registry to a new version and getting "Cannot read property 'fixNameField' of undefined" error. Operation system OS X. Node and npm versions are in the log below.

This is complete log.

```
0 info it worked if it ends with ok
1 verbose cli [ '/opt/local/bin/node', '/opt/local/bin/npm', 'publish' ]
2 info using npm@2.13.0
3 info using node@v0.12.7
4 verbose publish [ '.' ]
5 silly cache add args [ '.', null ]
6 verbose cache add spec .
7 silly cache add parsed spec { raw: '.',
7 silly cache add   scope: null,
7 silly cache add   name: null,
7 silly cache add   rawSpec: '.',
7 silly cache add   spec: '/Users/y/code/39/39f-socket.io',
7 silly cache add   type: 'directory' }
8 verbose addLocalDirectory /Users/y/.npm/39f-socket.io/1.3.6/package.tgz not in flight; packing
9 verbose tar pack [ '/Users/y/.npm/39f-socket.io/1.3.6/package.tgz',
9 verbose tar pack   '/Users/y/code/39/39f-socket.io' ]
10 verbose tarball /Users/y/.npm/39f-socket.io/1.3.6/package.tgz
11 verbose folder /Users/y/code/39/39f-socket.io
12 info prepublish 39f-socket.io@1.3.6
13 verbose addLocalTarball adding from inside cache /Users/y/.npm/39f-socket.io/1.3.6/package.tgz
14 silly cache afterAdd 39f-socket.io@1.3.6
15 verbose afterAdd /Users/y/.npm/39f-socket.io/1.3.6/package/package.json not in flight; writing
16 verbose afterAdd /Users/y/.npm/39f-socket.io/1.3.6/package/package.json written
17 silly publish { name: '39f-socket.io',
17 silly publish   version: '1.3.6',
17 silly publish   license: 'MIT',
17 silly publish   description: 'Handy socket.io wrapper, which adds to socket.io handlers\' chains and middlewares',
17 silly publish   author:
17 silly publish    { name: 'Yurij Mikhalevich',
17 silly publish      email: '0@39.yt',
17 silly publish      url: 'https://39.yt/' },
17 silly publish   repository:
17 silly publish    { type: 'git',
17 silly publish      url: 'git://github.com/39-framework/39f-socket.io.git' },
17 silly publish   keywords:
17 silly publish    [ 'socket.io',
17 silly publish      'websocket',
17 silly publish      '39f',
17 silly publish      '39-framework',
17 silly publish      'framework',
17 silly publish      'realtime',
17 silly publish      'socket',
17 silly publish      'io',
17 silly publish      'tcp',
17 silly publish      'events' ],
17 silly publish   main: 'index',
17 silly publish   readmeFilename: 'README.md',
17 silly publish   dependencies: { 'socket.io': '1.3.6' },
17 silly publish   readme: '# 39f-socket.io\n\nHandy socket.io wrapper, which adds to socket.io handlers\' chains and middlewares.\n\n\n## Motivation\n\n`tl;dr?`: To add to socket.io middlewares and handlers\' chains and to make\nevent handling more comfortable than in stock socket.io.\n\n[socket.io](https://github.com/Automattic/socket.io) is a genially perfect\ntool, but, for a lot of tasks, it is a bit low-level and complicated, event\nhandling is unpleasant, there is no way to specify handlers chain or mask-based\nhandler (middleware).\n\n__39f-socket.io__ solves all this problems for you. It\'s fully compatible with\nsocket.io-client. But, if you want to use features, provided by\n__39f-socket.io__, you shouldn\'t write server code in classic socket-io style.\n\n\n## Usage\n\nPlease, refer to [socket.io documentation](http://socket.io/docs/).\n\nTo prevent undefined behaviour you shouldn\'t call `on(\'connection\')` on\nnamespace and `on(\'disconnect\')` and `on(\'some event\')` on socket.\n\nInstead, you should call `Namespace#use`, `Namespace#route`, `Socket#use` and\n`Socket#route`.\n\n1. `use(handler:Function)` - adds handler to the middlewares chain.\n2. `use(eventNamePattern:RegExp, handler:Function)` - adds handler to the\nmiddlewares chain for events, which satisfies given pattern.\n3. `route(eventName:string, handler:Function|Object)` - adds handler for event\nwith event name. Handler may be an object, containing handler functions, if it\nis, `route` creates handlers for every function, and event names are constructed\nlike this: `eventName:functionField`.\n\nCalling this functions for Namespace, execute actions for every new connections,\ncalling them for Socket, affects only that socket.\n\nNote, that you should call `use` before any `route`.\n\nNote, that you can create chains of handlers calling `route` multiple times for\none event.\n\nEvent object is passed to handler as first argument. Here is it\'s structure:\n```javascript\n/**\n * @param {!Object} event\n * @param {*} event.data Received data\n * @param {!Object} event.socket Legacy socket.io object, associated with the event\n * @param {!string} event.name Event name\n * @param {!string} event.namePrefix Part of event name before \':\'\n * @param {!function(*)} event.respond Function to send ack response to client\n * @param {!Function} event.emit Just a shorthand for event.socket.emit\n */\n```\n\nWhen event received, first handler in chain called. To call next handler in\nchain, you should call `next()` function manually (passed to handler as second\nparameter, if here is next handler in chain).\n\n~~In addition, this module adds `Namespace#leave` and `Namespace#join` methods,\nwhich works perfectly similar to stock `Socket#leave` and `Socket#use`, but\nfor all sockets in the namespace. It may be used to add sockets in some room\ninto another room.~~ (Doesn\'t work with socket.io 1.0.x, needs patching)\n\n\n### Example\n\n```javacript\nvar io = require(\'39f-socket.io\');\n\nvar app = new io();\n\napp.sockets.use(function(signal, next) {\n  console.log(\'use\');\n  next();\n});\n\napp.sockets.use(function(signal, next) {\n  var authorized = checkAuth();\n  if (authorized) {\n    next();\n  } else {\n    signal.respond(\'Authorization required\');\n  }\n});\n\napp.sockets.route(\'123\', function(signal) {\n  console.log(signal);\n  signal.respond({1: 23});\n});\n\napp.of(\'/some\').use(function(signal, next) {\n  console.log(\'namespace some\');\n  next();\n});\n\napp.of(\'/some\').route(\'hi\', function(signal) {\n  signal.respond(\'you too\');\n});\n\napp.listen(8080);\n```\n\n\n### Notice about logger\n\nBy default logger uses console.error method to log errors and console.log to\nlog data, sent with response (the last logged only if node launched in\ndevelopment mode (`NODE_ENV=development`)).\n\nYou may specify logger (object with `warn` and `debug` methods\n([winston](https://github.com/flatiron/winston) perfectly fits)) by passing it\nas last argument to Server constructor.\n\n\n## Installation\n\n```bash\n$ npm install 39f-socket.io\n```\n\n\n#### Author: [Yurij Mikhalevich](https://39.yt/)\n',
17 silly publish   gitHead: 'c17c5812dfd2878fd6fbf39fa3ddd2fa176d72fe',
17 silly publish   bugs: { url: 'https://github.com/39-framework/39f-socket.io/issues' },
17 silly publish   homepage: 'https://github.com/39-framework/39f-socket.io#readme',
17 silly publish   _id: '39f-socket.io@1.3.6',
17 silly publish   scripts: {},
17 silly publish   _shasum: '3cc5a97481382fd4ddbaed8a4e1c5e665fcf2b28',
17 silly publish   _from: '.' }
18 verbose getPublishConfig undefined
19 silly mapToRegistry name 39f-socket.io
20 silly mapToRegistry using default registry
21 silly mapToRegistry registry https://registry.npmjs.org/
22 silly mapToRegistry uri https://registry.npmjs.org/39f-socket.io
23 verbose publish registryBase https://registry.npmjs.org/
24 silly publish uploading /Users/y/.npm/39f-socket.io/1.3.6/package.tgz
25 verbose stack TypeError: Cannot read property 'fixNameField' of undefined
25 verbose stack     at CachingRegistryClient.publish (/opt/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/publish.js:41:10)
25 verbose stack     at /opt/local/lib/node_modules/npm/lib/publish.js:134:14
25 verbose stack     at mapToRegistry (/opt/local/lib/node_modules/npm/lib/utils/map-to-registry.js:55:3)
25 verbose stack     at publish_ (/opt/local/lib/node_modules/npm/lib/publish.js:104:3)
25 verbose stack     at Array.<anonymous> (/opt/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
25 verbose stack     at LOOP (/opt/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
25 verbose stack     at LOOP (/opt/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:14:28)
25 verbose stack     at chain (/opt/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
25 verbose stack     at /opt/local/lib/node_modules/npm/lib/publish.js:73:5
25 verbose stack     at RES (/opt/local/lib/node_modules/npm/node_modules/inflight/inflight.js:23:14)
26 verbose cwd /Users/y/code/39/39f-socket.io
27 error Darwin 14.4.0
28 error argv "/opt/local/bin/node" "/opt/local/bin/npm" "publish"
29 error node v0.12.7
30 error npm  v2.13.0
31 error Cannot read property 'fixNameField' of undefined
32 error If you need help, you may report this error at:
32 error     <https://github.com/npm/npm/issues>
33 verbose exit [ 1, true ]
```

**Comment by othiym23** [comment]
This looks like an inconsistency between `npm-registry-client` and the version of `normalize-package-data` being used by `npm@2.13.0`. How did you get your version of npm installed? I'm trying to figure out if this is a bug that everybody is / should be encountering, or something specific to your particular install, because we haven't seen this error before, and that change has been around for a few months.

**Comment by 39dotyt** [comment]
@othiym23 I install node and npm via macports package manager. Will try reinstall them.

**Comment by 39dotyt** [comment]
@othiym23 nothing changed. Version of installed ```npm-registry-client``` (inside npm/node_modules) is 6.5.0.

**Comment by othiym23** [comment]
Hmm... I don't want to point fingers, but we've run into macports doing some fishy things with patches to npm in the past. Does this behavior repeat itself if you install npm directly instead of via macports?

**Comment by 39dotyt** [comment]
@othiym23 seems that it was a problem with macports installation. When macports uninstalls npm it leaves it's node_modules in the system. After I removed them manually and reinstalled npm (via macports) it works fine. Thank you for your help and excuse for troubling.

**Comment by othiym23** [comment]
No problem! I'm glad you got it worked out!
