### ISSUE TITLE
Flat dependencies not working on Windows

### ISSUE THREAD

**Issue by gussyboy** [npm/npm#8965]
Like most the inclusion of flat dependencies in NPM3 is excellent news, especially for Windows users. The functionality seems to works perfectly on OS X however it doesn't seem to work for me on Windows, unless I've done something completely wrong.

On both my mac and windows machine I've using nodejs v0.12.7 with npm 3.1.2. And on Windows my dependencies are still nested.

Anyone else having this issue?

Thanks

**Comment by othiym23** [comment]
Can you describe what behavior you're expecting to see, and what behavior you're actually seeing? There are a couple subtleties to the new installer that are confusing you, but I need more details to say for sure.

**Comment by gussyboy** [comment]
Sure, so using the following package.json dependencies, having installed them on both on a mac and pc using node 0.12.17 and npm 3.1.2 

```json
"dependencies": {
    "clamp-js": "^0.7.0",
    "jquery": "^1.11.3",
    "knockout": "^3.3.0",
    "knockout-mapping": "^2.5.0",
    "knockout.validation": "^2.0.3",
    "nanoscroller": "^0.8.7",
    "requirejs": "^2.1.19",
    "requirejs-text": "^2.0.12"
  },
  "devDependencies": {
    "autoprefixer-core": "^5.2.1",
    "del": "^1.2.0",
    "gulp": "^3.9.0",
    "gulp-autoprefixer": "^2.3.1",
    "gulp-chmod": "^1.2.0",
    "gulp-if": "^1.2.5",
    "gulp-jshint": "^1.11.2",
    "gulp-minify-css": "^1.2.0",
    "gulp-minify-html": "^1.0.3",
    "gulp-modernizr": "^1.0.0-alpha",
    "gulp-sass": "^2.0.3",
    "gulp-sourcemaps": "^1.5.2",
    "gulp-strip-line": "0.0.1",
    "gulp-uglify": "^1.2.0",
    "jshint-msbuild-reporter": "^1.0.0",
    "jshint-reporter-jscs": "^0.1.0",
    "run-sequence": "^1.1.1"
  },
```

On my mac all of the dependencies are all flat, as per image below.
![mac](https://cloud.githubusercontent.com/assets/2124400/8746444/30e72cea-2c81-11e5-8779-16ba7f74f9d7.png)

On Windows all of the dependencies are still nested just like they were when using npm 2, as per image below.
![pc](https://cloud.githubusercontent.com/assets/2124400/8746448/38fb80f2-2c81-11e5-9ce1-e004309a13fa.png)

I was expecting the dependencies on Windows to be flat just like they are on the Mac, hope that helps

**Comment by othiym23** [comment]
What does `npm -v` return on the Windows box? @iarna and I have a sneaking suspicion that even though you've upgraded to `npm@3`, your `%PATH%` is still finding `npm@2`.

**Comment by jokeyrhyme** [comment]
You need to use something like this to update NPM on Windows: https://www.npmjs.com/package/npm-windows-upgrade

**Comment by gussyboy** [comment]
So ```npm -v``` returns as 2.11.3 which i believe is the version shipped with nodejs v.0.12.7. My ```%PATH%``` has the following ```C:\Program Files (x86)\Git\cmd;C:\Program Files (x86)\nodejs\;C:\Users\adamwilson\AppData\Roaming\npm``` which seems correct to me to target the global version of npm.

```
PS C:\> npm -v
2.11.3
PS C:\> npm -g list --depth=0
C:\Users\adamwilson\AppData\Roaming\npm
|--- gulp@3.9.0
|--- karma-cli@0.1.0
|--- npm@3.1.3
|--- npm-windows-upgrade@0.2.6
```

Having attempted to use @jokeyrhyme upgrade package i get the following error. I'm not sure what that exactly means.

```
PS C:\> npm-windows-upgrade
npm-windows-upgrade 0.2.6
? This tool will upgrade npm. Do you want to continue? Yes
? Which version do you want to install? 3.1.3
Upgrading.. /Error:  npm WARN ENOENT ENOENT, open 'C:\Users\adamwilson\AppData\Roaming\npm\package.json'
npm
Error:   WARN EPACKAGEJSON C:\Users\adamwilson\AppData\Roaming\npm No description
npm WARN EPACKAGEJSON C:\Users\adamwilson\AppData\Roaming\npm No repository field.
npm WARN EPACKAGEJSON C:\Users\adamwilson\AppData\Roaming\npm No README data
npm WARN EPACKAGEJSON C:\Users\adamwilson\AppData\Roaming\npm No license field.

Upgrading.. -

You wanted to install npm 3.1.3, but the installed version is2.11.3.
Please consider reporting your trouble to http://aka.ms/npm-issues.
Here is the output from the upgrader script:
[ 'C:\\Users\\adamwilson\\AppData\\Roaming\\npm\n└── npm@3.1.3 \n\n',
  'All done!\r\n' ] [ 'npm WARN ENOENT ENOENT, open \'C:\\Users\\adamwilson\\AppData\\Roaming\\npm\\package.json\'\nnpm',
  ' WARN EPACKAGEJSON C:\\Users\\adamwilson\\AppData\\Roaming\\npm No description\nnpm WARN EPACKAGEJSON C:\\Users\\adamwilson\\AppData\\Roaming\\npm No repository field.\nnpm WARN EPACKAGEJSON C:\\Users\\adamwilson\\AppData\\Roaming\\npm No README data\nnpm WARN EPACKAGEJSON C:\\Users\\adamwilson\\AppData\\Roaming\\npm No license field.\n' ]
PS C:\>
```

Any suggestions how i can resolve this?

**Comment by iarna** [comment]
@gussyboy Well, you could try going over to the [npm-windows-upgrade issue tracker](https://github.com/felixrieseberg/npm-windows-upgrade/issues/new) and asking them there, but that looks suspiciously like your npm install got mangled somewhere along the line. 

I would try deleting `C:\Users\adamwilson\AppData\Roaming\npm` and seeing of doing so doesn't make `npm-windows-upgrade` work?

**Comment by gussyboy** [comment]
@iarna So i've finally got flat packages, thanks for the help. It seems to a be an issue with ```%PATH%```.

I'd firstly like to apologise, ```node```, ```npm``` and ```python``` aren't anything I really have much knowledge in, I just know how to use the packages with ```gulp```. Anyway having said that this has now led onto another issue that I never previously got with ```npm@2```.

When I install ```npm karma``` i get the error below. Now its worth pointing when I was using ```npm@2``` I didn't have ```python``` installed but i've since installed it as per the suggestions on http://stackoverflow.com/questions/21365714/nodejs-error-installing-with-npm. Having already got Visual Studio 2012 installed I didn't follow the step to install *Microsoft Visual Studio C++ 2012 Express version*, this might be the cause of the error below, however why did everything work ok with ```npm@2```?

```
PS C:\tfs\ASOS\Commerce\Checkout\Dev-NPM3\Checkout\Source\Asos.Commerce.Checkout.Web.JsUnitTests> npm i

> fsevents@0.3.6 install C:\tfs\ASOS\Commerce\Checkout\Dev-NPM3\Checkout\Source\Asos.Commerce.Checkout.Web.JsUnitTests\node_modules\fsevents
> node-gyp rebuild


C:\tfs\ASOS\Commerce\Checkout\Dev-NPM3\Checkout\Source\Asos.Commerce.Checkout.Web.JsUnitTests\node_modules\fsevents>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Traceback (most recent call last):
  File "C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 18, in <module>
    sys.exit(gyp.script_main())
  File "C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 533, in script_main
    return main(sys.argv[1:])
  File "C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 526, in main
    return gyp_main(args)
  File "C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 511, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 2000, in GenerateOutput
    sln_projects, project_objects, flat=msvs_version.FlatSolution())
  File "C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1759, in _GatherSolutionFolders
    return _DictsToFolders('', root, flat)
  File "C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1712, in _DictsToFolders
    for folder, contents in bucket.iteritems():
AttributeError: 'MSVSProject' object has no attribute 'iteritems'
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:357:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\tfs\ASOS\Commerce\Checkout\Dev-NPM3\Checkout\Source\Asos.Commerce.Checkout.Web.JsUnitTests\node_modules\fsevents
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
npm WARN install:fsevents Couldn't install optional dependency: fsevents@0.3.6 install: `node-gyp rebuild`
npm WARN install:fsevents Exit status 1
npm WARN prefer global jshint@2.8.0 should be installed with -g

> ws@0.4.32 install C:\tfs\ASOS\Commerce\Checkout\Dev-NPM3\Checkout\Source\Asos.Commerce.Checkout.Web.JsUnitTests\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)


C:\tfs\ASOS\Commerce\Checkout\Dev-NPM3\Checkout\Source\Asos.Commerce.Checkout.Web.JsUnitTests\node_modules\ws>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Platforms\Win32\Microsoft.Cpp.Win32.Targets(511,5): error MSB8008: Specified platform toolset (v120) is not installed or invalid. Please make sure that a supported PlatformToolset value is selected. [C:\tfs\ASOS\Commerce\Checkout\Dev-NPM3\Checkout\Source\Asos.Commerce .Checkout.Web.JsUnitTests\node_modules\ws\build\bufferutil.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Platforms\Win32\Microsoft.Cpp.Win32.Targets(511,5): error MSB8008: Specified platform toolset (v120) is not installed or invalid. Please make sure that a supported PlatformToolset value is selected. [C:\tfs\ASOS\Commerce\Checkout\Dev-NPM3\Checkout\Source\Asos.Commerce .Checkout.Web.JsUnitTests\node_modules\ws\build\validation.vcxproj]
npm WARN EPEERINVALID karma-requirejs@0.2.2 requires a peer of requirejs@~2.1 but none was installed.
PS C:\tfs\ASOS\Commerce\Checkout\Dev-NPM3\Checkout\Source\Asos.Commerce.Checkout.Web.JsUnitTests>```

**Comment by alexklibisz** [comment]
@gussyboy for upgrading to npm3, I've found the following to be the simplest way:

Open PowerShell as an Administrator. (Right click on powershell icon, click Run as Administrator), then enter the commands:  

> cd C:\Program Files\nodejs
> npm install npm@3.0-latest

Or you can do 
> npm install npm@3.1.3
(or any other 3.x.y) to get a specific version.

**Comment by iarna** [comment]
I'm closing this as the original issue is resolved. Further, `fsevents` is flagged as OSX only and recent versions of npm@3 now correctly stop themselves from trying to install it on Windows.
