### ISSUE TITLE
npm ERR! Error: Callback called more than once

### ISSUE THREAD

**Issue by VegaFromLyra** [npm/npm#8969]
Getting this error intermittently when I run `npm install` via TeamCity on a Windows server 2012 machine.

Here's a snippet of the log

```
[22:19:25][Step 2/7] npm ERR! Error: Callback called more than once.
[22:19:25][Step 2/7] grunt-contrib-concat@0.5.1 node_modules\grunt-contrib-concat
[22:19:25][Step 2/7] npm ERR!     at errorHandler (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:81:16)
[22:19:25][Step 2/7] â”œâ”€â”€ source-map@0.3.0 (amdefine@1.0.0)
[22:19:25][Step 2/7] npm ERR!     at save (C:\Program Files\nodejs\node_modules\npm\lib\install.js:338:12)
[22:19:25][Step 2/7] â””â”€â”€ chalk@0.5.1 (ansi-styles@1.1.0, escape-string-regexp@1.0.3, supports-color@0.2.0, strip-ansi@0.3.0, has-ansi@0.1.0)
[22:19:25][Step 2/7] npm ERR!     at C:\Program Files\nodejs\node_modules\npm\lib\install.js:103:7
[22:19:25][Step 2/7] 
[22:19:25][Step 2/7] grunt-contrib-copy@0.8.0 node_modules\grunt-contrib-copy
[22:19:25][Step 2/7] npm ERR!     at C:\Program Files\nodejs\node_modules\npm\lib\install.js:195:5
[22:19:25][Step 2/7] â”œâ”€â”€ file-sync-cmp@0.1.1
[22:19:25][Step 2/7] npm ERR!     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-installed\read-installed.js:130:5
[22:19:25][Step 2/7] npm ERR!     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-installed\read-installed.js:244:14
[22:19:25][Step 2/7] â””â”€â”€ chalk@0.5.1 (ansi-styles@1.1.0, escape-string-regexp@1.0.3, supports-color@0.2.0, strip-ansi@0.3.0, has-ansi@0.1.0)
[22:19:25][Step 2/7] npm ERR!     at cb (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:48:11)
[22:19:25][Step 2/7] 
[22:19:25][Step 2/7] npm ERR!     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-installed\read-installed.js:244:14
[22:19:25][Step 2/7] grunt-contrib-htmlmin@0.4.0 node_modules\grunt-contrib-htmlmin
[22:19:25][Step 2/7] npm ERR!     at cb (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:48:11)
[22:19:25][Step 2/7] â”œâ”€â”€ chalk@0.5.1 (ansi-styles@1.1.0, escape-string-regexp@1.0.3, supports-color@0.2.0, strip-ansi@0.3.0, has-ansi@0.1.0)
[22:19:25][Step 2/7] npm ERR!     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-installed\read-installed.js:244:14
[22:19:25][Step 2/7] â”œâ”€â”€ pretty-bytes@1.0.4 (get-stdin@4.0.1, meow@3.3.0)
[22:19:25][Step 2/7] npm ERR! If you need help, you may report this *entire* log,
[22:19:25][Step 2/7] â””â”€â”€ html-minifier@0.7.2 (relateurl@0.2.6, change-case@2.3.0, concat-stream@1.4.10, clean-css@3.1.9, uglify-js@2.4.23, cli@0.6.6)
[22:19:25][Step 2/7] npm ERR! including the npm and node versions, at:
[22:19:25][Step 2/7] 
[22:19:25][Step 2/7] npm ERR!     <http://github.com/npm/npm/issues>
[22:19:25][Step 2/7] grunt@0.4.5 node_modules\grunt
[22:19:25][Step 2/7] 
[22:19:25][Step 2/7] â”œâ”€â”€ async@0.1.22
[22:19:25][Step 2/7] npm ERR! System Windows_NT 6.2.9200
[22:19:25][Step 2/7] â”œâ”€â”€ grunt-legacy-util@0.2.0
[22:19:25][Step 2/7] npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
[22:19:25][Step 2/7] â”œâ”€â”€ exit@0.1.2
[22:19:25][Step 2/7] npm ERR! cwd C:\TeamCity\buildAgent\work\271b93e1281b98d3
[22:19:25][Step 2/7] â”œâ”€â”€ hooker@0.2.3
[22:19:25][Step 2/7] npm ERR! node -v v0.10.31
[22:19:25][Step 2/7] â”œâ”€â”€ eventemitter2@0.4.14
[22:19:25][Step 2/7] npm ERR! npm -v 1.4.23
[22:19:25][Step 2/7] â”œâ”€â”€ dateformat@1.0.2-1.2.3
[22:19:25][Step 2/7] â”œâ”€â”€ getobject@0.1.0
[22:19:25][Step 2/7] â”œâ”€â”€ lodash@0.9.2
[22:19:25][Step 2/7] â”œâ”€â”€ colors@0.6.2
[22:19:25][Step 2/7] â”œâ”€â”€ which@1.0.9
[22:19:25][Step 2/7] â”œâ”€â”€ rimraf@2.2.8
[22:19:25][Step 2/7] â”œâ”€â”€ underscore.string@2.2.1
[22:19:25][Step 2/7] â”œâ”€â”€ coffee-script@1.3.3
[22:19:25][Step 2/7] â”œâ”€â”€ iconv-lite@0.2.11
[22:19:25][Step 2/7] â”œâ”€â”€ glob@3.1.21 (inherits@1.0.0, graceful-fs@1.2.3)
[22:19:25][Step 2/7] â”œâ”€â”€ minimatch@0.2.14 (sigmund@1.0.1, lru-cache@2.6.5)
[22:19:25][Step 2/7] â”œâ”€â”€ nopt@1.0.10 (abbrev@1.0.7)
[22:19:25][Step 2/7] â”œâ”€â”€ js-yaml@2.0.5 (esprima@1.0.4, argparse@0.1.16)
[22:19:25][Step 2/7] â”œâ”€â”€ grunt-legacy-log@0.1.2 (grunt-legacy-log-utils@0.1.1, underscore.string@2.3.3, lodash@2.4.2)
[22:19:25][Step 2/7] â””â”€â”€ findup-sync@0.1.3 (glob@3.2.11, lodash@2.4.2)
[22:19:25][Step 2/7] 
[22:19:25][Step 2/7] grunt-ftp-deploy@0.1.10 node_modules\grunt-ftp-deploy
[22:19:25][Step 2/7] â”œâ”€â”€ async@0.9.2
[22:19:25][Step 2/7] â”œâ”€â”€ lodash@2.4.2
[22:19:25][Step 2/7] â”œâ”€â”€ jsftp@1.5.2 (once@1.3.0, unorm@1.3.3, parse-listing@1.1.2, debug@2.1.1, event-stream@3.1.7, ftp-response-parser@1.0.0)
[22:19:25][Step 2/7] â””â”€â”€ prompt@0.2.14 (revalidator@0.1.8, pkginfo@0.3.0, read@1.0.6, winston@0.8.3, utile@0.2.1)
[22:19:25][Step 2/7] 
[22:19:25][Step 2/7] grunt-contrib-cssmin@0.12.3 node_modules\grunt-contrib-cssmin
[22:19:25][Step 2/7] â”œâ”€â”€ chalk@1.1.0 (escape-string-regexp@1.0.3, supports-color@2.0.0, ansi-styles@2.1.0, has-ansi@2.0.0, strip-ansi@3.0.0)
[22:19:25][Step 2/7] â”œâ”€â”€ clean-css@3.3.6 (commander@2.8.1, source-map@0.4.4)
[22:19:25][Step 2/7] â””â”€â”€ maxmin@1.1.0 (figures@1.3.5, pretty-bytes@1.0.4, gzip-size@1.0.0)
[22:19:25][Step 2/7] 
[22:19:25][Step 2/7] grunt-contrib-uglify@0.9.1 node_modules\grunt-contrib-uglify
[22:19:25][Step 2/7] â”œâ”€â”€ uri-path@0.0.2
[22:19:25][Step 2/7] â”œâ”€â”€ chalk@1.1.0 (escape-string-regexp@1.0.3, supports-color@2.0.0, ansi-styles@2.1.0, strip-ansi@3.0.0, has-ansi@2.0.0)
[22:19:25][Step 2/7] â”œâ”€â”€ uglify-js@2.4.23 (uglify-to-browserify@1.0.2, async@0.2.10, source-map@0.1.34, yargs@3.5.4)
[22:19:25][Step 2/7] â”œâ”€â”€ lodash@3.10.0
[22:19:25][Step 2/7] â””â”€â”€ maxmin@1.1.0 (figures@1.3.5, pretty-bytes@1.0.4, gzip-size@1.0.0)
[22:19:25][Step 2/7] 
[22:19:25][Step 2/7] grunt-contrib-nodeunit@0.4.1 node_modules\grunt-contrib-nodeunit
[22:19:25][Step 2/7] â”œâ”€â”€ hooker@0.2.3
[22:19:25][Step 2/7] â””â”€â”€ nodeunit@0.9.1 (tap@0.7.1)
[22:19:25][Step 2/7] 
[22:19:25][Step 2/7] grunt-contrib-jshint@0.11.2 node_modules\grunt-contrib-jshint
[22:19:25][Step 2/7] â”œâ”€â”€ hooker@0.2.3
[22:19:25][Step 2/7] â””â”€â”€ jshint@2.8.0 (strip-json-comments@1.0.2, exit@0.1.2, console-browserify@1.1.0, shelljs@0.3.0, minimatch@2.0.8, cli@0.6.6, lodash@3.7.0, htmlparser2@3.8.3)
[22:19:25][Step 2/7] 
[22:19:25][Step 2/7] grunt-contrib-imagemin@0.9.4 node_modules\grunt-contrib-imagemin
[22:19:25][Step 2/7] â”œâ”€â”€ gulp-rename@1.2.2
[22:19:25][Step 2/7] â”œâ”€â”€ async@0.9.2
[22:19:25][Step 2/7] â”œâ”€â”€ chalk@1.1.0 (escape-string-regexp@1.0.3, supports-color@2.0.0, ansi-styles@2.1.0, has-ansi@2.0.0, strip-ansi@3.0.0)
[22:19:25][Step 2/7] â”œâ”€â”€ pretty-bytes@1.0.4 (get-stdin@4.0.1, meow@3.3.0)
[22:19:25][Step 2/7] â””â”€â”€ imagemin@3.2.0 (path-exists@1.0.0, optional@0.1.3, get-stdin@4.0.1, buffer-to-vinyl@1.0.0, through2@0.6.5, stream-combiner2@1.0.2, concat-stream@1.5.0, meow@3.3.0, imagemin-svgo@4.1.2, vinyl-fs@1.0.0, imagemin-optipng@4.3.0, imagemin-jpegtran@4.3.0)
[22:19:25][Step 2/7] 
[22:19:25][Step 2/7] grunt-protractor-runner@2.0.0 node_modules\grunt-protractor-runner
[22:19:25][Step 2/7] â”œâ”€â”€ split@0.3.3 (through@2.3.8)
[22:19:25][Step 2/7] â”œâ”€â”€ through2@0.5.1 (xtend@3.0.0, readable-stream@1.0.33)
[22:19:25][Step 2/7] â””â”€â”€ protractor@2.1.0 (jasminewd@1.1.0, jasminewd2@0.0.5, html-entities@1.1.2, saucelabs@0.1.1, q@1.0.0, minijasminenode@1.1.1, adm-zip@0.4.4, optimist@0.6.1, jasmine@2.3.1, accessibility-developer-tools@2.6.0, source-map-support@0.2.10, request@2.36.0, lodash@2.4.2, glob@3.2.11, selenium-webdriver@2.45.1)
[22:19:26][Step 2/7] npm
[22:19:26][Step 2/7] Process exited with code 34
[22:19:26][Step 2/7] Step npm install (Command Line) failed

```

Here's the full debug log - https://gist.github.com/VegaFromLyra/536387527d20f91a6a6d

Here's my package.json - https://gist.github.com/VegaFromLyra/90a7308c2d1d221a1012

**Comment by othiym23** [comment]
You (or, more probably, TeamCity) are running a very old version of npm, `npm@1.4.23`. I'd check to see if there's an update to TeamCity to get it to use a newer version of npm, or, barring that, see if you update TeamCity to use a new version of npm yourself. The current version is `npm@2.13.0`, and there have been many, many bug fixes since `npm@1.4.x`.

**Comment by VegaFromLyra** [comment]
Ah I see, I only checked npm and node on my local, should have checked it on TeamCity as well. Updated it now. Thanks for the quick reply! (I will let you close the issue)

**Comment by othiym23** [comment]
closing as resolved!
