### ISSUE TITLE
npm install failing to complete successfully

### ISSUE THREAD

**Issue by ardasgup** [npm/npm#8973]
When running sudo npm install from my project folder i am getting the below error.

```
npm http 304 https://registry.npmjs.org/jquery
npm http 404 https://registry.npmjs.org/bootstrap-growl
npm ERR! TypeError: Cannot read property 'latest' of undefined
npm ERR!     at next (/usr/lib/node_modules/npm/lib/cache.js:687:35)
npm ERR!     at /usr/lib/node_modules/npm/lib/cache.js:675:5
npm ERR!     at saved (/usr/lib/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/node_modules/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:108:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.11.10-301.fc20.x86_64
npm ERR! command "node" "/usr/bin/npm" "install"
npm ERR! cwd /home/ardasgup/workspace/unified/unified-ui
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.3.6
npm ERR! type non_object_property_load
npm http 304 https://registry.npmjs.org/imports-loader
npm http 304 https://registry.npmjs.org/file-loader
```

**Comment by sinkingshriek** [comment]
Is upgrading `npm` an option? If it is then I'd suggest you try with an upgrade. `1.3.6` is very behind than the latest one.

**Comment by KenanY** [comment]
@ardasgup While upgrading `npm` is highly recommended, your issue is:

```
npm http 404 https://registry.npmjs.org/bootstrap-growl
```

There is no module in the registry called `bootstrap-growl`, hence your 404 error.

**Comment by othiym23** [comment]
@KenanY hmmm...

```json
{
  "name": "bootstrap-growl",
  "time": {
    "modified": "2015-07-19T09:07:14.238Z",
    "created": "2014-09-20T12:51:05.066Z",
    "2.0.0": "2014-09-20T12:51:05.066Z",
    "3.1.3": "2015-07-19T08:36:31.594Z"
  },
  "maintainers": "pgilad <giladp007@gmail.com>",
  "dist-tags": {
    "latest": "3.1.3"
  },
  "description": "This is a simple plugin that turns standard Bootstrap alerts into \"Growl-like\" notifications.",
  "versions": "3.1.3",
  "homepage": "http://bootstrap-notify.remabledesigns.com/",
  "keywords": [
    "bootstrap",
    "jquery",
    "notify",
    "notification",
    "notifications",
    "growl",
    "message",
    "notice"
  ],
  "repository": {
    "type": "git",
    "url": "git+https://github.com/mouse0270/bootstrap-notify.git"
  },
  "author": "mouse0270 <rmcintosh@remabledesigns.com>",
  "bugs": {
    "url": "https://github.com/mouse0270/bootstrap-notify/issues"
  },
  "license": "MIT",
  "readmeFilename": "README.md",
  "version": "3.1.3",
  "main": "bootstrap-notify.js",
  "files": [
    "bootstrap-notify.js",
    "bootstrap-notify.min.js"
  ],
  "dependencies": {},
  "devDependencies": {
    "grunt": "^0.4.5",
    "grunt-cli": "^0.1.13",
    "grunt-contrib-jshint": "^0.10.0",
    "grunt-contrib-uglify": "^0.4.0",
    "grunt-exec": "^0.4.6",
    "spacejam": "^1.1.4"
  },
  "scripts": {
    "test": "grunt test"
  },
  "gitHead": "7cac42011523d8a81c2dd463eb9ddc6a2883c61b",
  "dist": {
    "shasum": "5c283a427f65c65437b002c8ded061b3d4170fc3",
    "tarball": "http://registry.npmjs.org/bootstrap-growl/-/bootstrap-growl-3.1.3.tgz"
  },
  "deprecated": "This project has been renamed to bootstrap-notify. Install using bootstrap-notify instead.",
  "directories": {}
}
```

I think this probably is due to having an old version of npm, and for whatever reason that error message is misleading.

**Comment by othiym23** [comment]
(either that or it temporarily got unpublished for some reason, which happens sometimes when packages are handed between maintainers)

**Comment by ardasgup** [comment]
@KenanY @sinkingshriek thanks guys, i upgraded my npm but that didnt help, i had to remove the bootstrap-growl dependency and try something else anyway.
