### ISSUE TITLE
sudo npm install -g ionic

### ISSUE THREAD

**Issue by cmy111246** [npm/npm#9025]
npm ERR! tar.unpack untar error /tmp/npm-835-88fc9953/registry.npmjs.org/npm/-/npm-2.1.3.tgz
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "ionic"
npm ERR! node v0.12.7
npm ERR! npm  v2.12.1

npm ERR! unexpected eof

**Comment by cmy111246** [comment]
error tar.unpack untar error /tmp/npm-1741-22cce720/registry.npmjs.org/npm/-/npm-2.1.3.tgz
2198 verbose about to build /usr/local/lib/node_modules/ionic
2199 verbose unlock done using /Users/sweety/.npm/_locks/ionic-61c0cd50dc7a1457.lock for /usr/local/lib/node_modules/ionic
2200 verbose stack Error: invalid tar file
2200 verbose stack     at Extract.Parse._startEntry (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:145:13)
2200 verbose stack     at Extract.Parse._process (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:127:12)
2200 verbose stack     at BlockStream.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:47:8)
2200 verbose stack     at BlockStream.emit (events.js:107:17)
2200 verbose stack     at BlockStream._emitChunk (/usr/local/lib/node_modules/npm/node_modules/block-stream/block-stream.js:145:10)
2200 verbose stack     at BlockStream.resume (/usr/local/lib/node_modules/npm/node_modules/block-stream/block-stream.js:58:15)
2200 verbose stack     at Extract.Reader.resume (/usr/local/lib/node_modules/npm/node_modules/fstream/lib/reader.js:249:34)
2200 verbose stack     at Entry.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:257:8)
2200 verbose stack     at Entry.emit (events.js:104:17)
2200 verbose stack     at Entry.resume (/usr/local/lib/node_modules/npm/node_modules/tar/lib/entry.js:92:8)
2201 verbose cwd /Users/sweety
2202 error Darwin 14.3.0
2203 error argv "node" "/usr/local/bin/npm" "install" "-g" "ionic"
2204 error node v0.12.7
2205 error npm  v2.13.1
2206 error invalid tar file
2207 error If you need help, you may report this error at:
2207 error     <https://github.com/npm/npm/issues>
2208 verbose exit [ 1, true ]
2209 verbose unbuild lib/node_modules/ionic
2210 info preuninstall ionic@1.6.1
2211 info uninstall ionic@1.6.1
2212 verbose unbuild rmStuff ionic@1.6.1 from /usr/local/lib/node_modules
2213 silly gentlyRm /usr/local/bin/ionic is being gently removed
2214 silly gentlyRm verifying /usr/local is an npm working directory
2215 silly gentlyRm containing path /usr/local is under npm's control, in /usr/local
2216 silly gentlyRm deletion target /usr/local/bin/ionic is under /usr/local
2217 verbose gentlyRm vacuuming from /usr/local/bin/ionic up to /usr/local
2218 info postuninstall ionic@1.6.1
2219 silly gentlyRm /usr/local/lib/node_modules/ionic is being purged from base /usr/local
2220 verbose gentlyRm don't care about contents; nuking /usr/local/lib/node_modules/ionic
2221 silly vacuum-fs purging /usr/local/lib/node_modules/ionic
2222 silly vacuum-fs quitting because other entries in /usr/local/lib/node_modules

**Comment by cmy111246** [comment]
vpn换了台湾就可以安装上了  日本的和国内的始终不行
