### ISSUE TITLE
Cannot login from command line

### ISSUE THREAD

**Issue by tminglei** [npm/npm#9027]
Here's the log:
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'login',
1 verbose cli   '--verbose' ]
2 info using npm@2.10.1
3 info using node@v0.12.4
4 verbose adduser before first PUT { _id: 'org.couchdb.user:tminglei',
4 verbose adduser   name: 'tminglei',
4 verbose adduser   password: 'XXXXX',
4 verbose adduser   email: 'tmlneu@gmail.com',
4 verbose adduser   type: 'user',
4 verbose adduser   roles: [],
4 verbose adduser   date: '2015-07-22T05:35:19.463Z' }
5 verbose request uri https://registry.npm.taobao.org/-/user/org.couchdb.user:tminglei
6 verbose request new user, so can't send auth
7 info attempt registry request try #1 at 13:35:19
8 verbose request id 4a4cc882635d5705
9 http request PUT https://registry.npm.taobao.org/-/user/org.couchdb.user:tminglei
10 http 409 https://registry.npm.taobao.org/-/user/org.couchdb.user:tminglei
11 verbose headers { server: 'nginx/1.1.19',
11 verbose headers   date: 'Wed, 22 Jul 2015 05:35:16 GMT',
11 verbose headers   'content-type': 'application/json; charset=utf-8',
11 verbose headers   'content-length': '61',
11 verbose headers   connection: 'keep-alive',
11 verbose headers   'x-readtime': '15' }
12 verbose request invalidating C:\Users\tuml\AppData\Roaming\npm-cache\registry.npm.taobao.org\-\user\org.couchdb.user_3Atminglei on PUT
13 verbose adduser update existing user
14 verbose request uri https://registry.npm.taobao.org/-/user/org.couchdb.user:tminglei?write=true
15 verbose request no auth needed
16 info attempt registry request try #1 at 13:35:20
17 http request GET https://registry.npm.taobao.org/-/user/org.couchdb.user:tminglei?write=true
18 http 200 https://registry.npm.taobao.org/-/user/org.couchdb.user:tminglei?write=true
19 verbose adduser userobj { _id: 'org.couchdb.user:tminglei',
19 verbose adduser   name: 'tminglei',
19 verbose adduser   password: 'XXXXX',
19 verbose adduser   email: 'tmlneu@gmail.com',
19 verbose adduser   type: 'user',
19 verbose adduser   roles: [],
19 verbose adduser   date: '2015-07-22T05:35:19.463Z' }
20 verbose request uri https://registry.npm.taobao.org/-/user/org.couchdb.user:tminglei/-rev/3-850bf9bb17647b3caecbc495373b23bc
21 verbose request updating existing user; sending authorization
22 info attempt registry request try #1 at 13:35:20
23 http request PUT https://registry.npm.taobao.org/-/user/org.couchdb.user:tminglei/-rev/3-850bf9bb17647b3caecbc495373b23bc
24 http 401 https://registry.npm.taobao.org/-/user/org.couchdb.user:tminglei/-rev/3-850bf9bb17647b3caecbc495373b23bc
25 verbose headers { server: 'nginx/1.1.19',
25 verbose headers   date: 'Wed, 22 Jul 2015 05:35:17 GMT',
25 verbose headers   'content-type': 'application/json; charset=utf-8',
25 verbose headers   'content-length': '47',
25 verbose headers   connection: 'keep-alive',
25 verbose headers   'x-readtime': '8' }
26 verbose request invalidating C:\Users\tuml\AppData\Roaming\npm-cache\registry.npm.taobao.org\-\user\org.couchdb.user_3Atminglei on PUT
27 verbose adduser back [ { [Error: unauthorized Login first: -/user/org.couchdb.user:tminglei/-rev/3-850bf9bb17647b3caecbc495373b23bc] statusCode: 401, code: 'E401' },
27 verbose adduser   { error: 'unauthorized', reason: 'Login first' },
27 verbose adduser   '{"error":"unauthorized","reason":"Login first"}' ]
28 warn adduser Incorrect username or password
28 warn adduser You can reset your account by visiting:
28 warn adduser
28 warn adduser     https://npmjs.org/forgot
29 verbose stack Error: unauthorized Login first: -/user/org.couchdb.user:tminglei/-rev/3-850bf9bb17647b3caecbc495373b23bc
29 verbose stack     at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:247:14)
29 verbose stack     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:170:14)
29 verbose stack     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:368:22)
29 verbose stack     at Request.emit (events.js:110:17)
29 verbose stack     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1219:14)
29 verbose stack     at Request.emit (events.js:129:20)
29 verbose stack     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1167:12)
29 verbose stack     at IncomingMessage.emit (events.js:129:20)
29 verbose stack     at _stream_readable.js:908:16
29 verbose stack     at process._tickCallback (node.js:355:11)
30 verbose statusCode 401
31 verbose cwd D:\Repos\browserify-bower
32 error Windows_NT 6.1.7601
33 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "login" "--verbose"
34 error node v0.12.4
35 error npm  v2.10.1
36 error code E401
37 error unauthorized Login first: -/user/org.couchdb.user:tminglei/-rev/3-850bf9bb17647b3caecbc495373b23bc
38 error If you need help, you may report this error at:
38 error     <https://github.com/npm/npm/issues>
39 verbose exit [ 1, true ]
```

_**p.s. same username/password can login npmjs.com.**_

**Comment by tminglei** [comment]
Well, the cause should be related to the mirror registry.npm.taobao.org.
I resolved it.
