### ISSUE TITLE
When install react-starter, npm install fails.

### ISSUE THREAD

**Issue by milhous** [npm/npm#9029]
react-starter git: https://github.com/webpack/react-starter

npm-debug.log is as following, can anyone take a look please, thx.
```
npm WARN package.json react-starter@0.0.0 No repository field.
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! Error: shasum check failed for /tmp/npm-4516-DHn7tL2E/registry.npmjs.org/less/-/less-2.5.1.tgz
npm ERR! Expected: 8b489cc01d021e49360fd5ae03581896e722b726
npm ERR! Actual:   b85b872b490a9e43142c257162d3545173410ef3
npm ERR! From:     https://registry.npmjs.org/less/-/less-2.5.1.tgz
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/sha/index.js:38:8
npm ERR!     at ReadStream.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/sha/index.js:85:7)
npm ERR!     at ReadStream.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:943:16
npm ERR!     at process._tickCallback (node.js:419:13)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 14.3.0
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/admin/Documents/github/react/react-starter
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/admin/Documents/github/react/react-starter/npm-debug.log
npm ERR! not ok code 0
```

**Comment by KenanY** [comment]
@milhous Have you tried `npm cache clean`?

**Comment by milhous** [comment]
Thanks @KenanY !
I didn't do anything change, but today i just found it complies!

**Comment by othiym23** [comment]
Closing as resolved!(?)
