### ISSUE TITLE
Error parsing json, unexpected token...

### ISSUE THREAD

**Issue by khackskjs** [npm/npm#9036]
I'm in intra network of my company, so I have to set proxy server.
I have faced the problem such as (just my thought) error parsing json, unexpected token.
please help me how to solve this.
I attached console and npm debug log.

Console
------------------------------------------------------------------------------------------------------------------------------------
```
C:\Windows\system32>npm install bower
npm ERR! registry error parsing json
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install
" "bower"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! Unexpected token <
npm ERR! <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
npm ERR! <html xmlns="http://www.w3.org/1999/xhtml">
npm ERR! <head>
npm ERR! <meta http-equiv="Content-Type" content="text/html; charset=ks_c_5601-1987"/>
npm ERR! <title>404 -       Ǵ       ͸    ã           ϴ .</title>
npm ERR! <style type="text/css">
npm ERR! <!--
npm ERR! body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
npm ERR! fieldset{padding:0 15px 10px 15px;}
npm ERR! h1{font-size:2.4em;margin:0;color:#FFF;}
npm ERR! h2{font-size:1.7em;margin:0;color:#CC0000;}
npm ERR! h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;}
npm ERR! #header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
npm ERR! background-color:#555555;}
npm ERR! #content{margin:0 0 0 2%;position:relative;}
npm ERR! .content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
npm ERR! -->
npm ERR! </style>
npm ERR! </head>
npm ERR! <body>
npm ERR! <div id="header"><h1>         </h1></div>
npm ERR! <div id="content">
npm ERR!  <div class="content-container"><fieldset>
npm ERR!   <h2>404 -       Ǵ       ͸    ã           ϴ .</h2>
npm ERR!   <h3>ã    ִ     ҽ       ŵǾ  ų   ̸         Ǿ  ų   Ͻ                       ϴ .</h3>
npm ERR!  </fieldset></div>
npm ERR! </div>
npm ERR! </body>
npm ERR! </html>
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Windows\system32\npm-debug.log

C:\Windows\system32>
```
---------------------------------------------------------------------------------------------------------------------------------------------------------------------

npm debug log
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'bower' ]
2 info using npm@2.11.3
3 info using node@v0.12.7
4 verbose install initial load of C:\Windows\system32\package.json
5 verbose readDependencies loading dependencies from C:\Windows\system32\package.json
6 silly cache add args [ 'bower', null ]
7 verbose cache add spec bower
8 silly cache add parsed spec { raw: 'bower',
8 silly cache add   scope: null,
8 silly cache add   name: 'bower',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: '*',
8 silly cache add   type: 'range' }
9 silly addNamed bower@*
10 verbose addNamed "*" is a valid semver range for bower
11 silly addNameRange { name: 'bower', range: '*', hasData: false }
12 silly mapToRegistry name bower
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry http://registry.npmjs.org/
15 silly mapToRegistry uri http://registry.npmjs.org/bower
16 verbose addNameRange registry:http://registry.npmjs.org/bower not in flight; fetching
17 verbose request uri http://registry.npmjs.org/bower
18 verbose request no auth needed
19 info attempt registry request try #1 at 16:56:56
20 verbose request id 89d91b9e739363fa
21 http request GET http://registry.npmjs.org/bower
22 http 404 http://registry.npmjs.org/bower
23 verbose bad json <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
23 verbose bad json <html xmlns="http://www.w3.org/1999/xhtml">
23 verbose bad json <head>
23 verbose bad json <meta http-equiv="Content-Type" content="text/html; charset=ks_c_5601-1987"/>
23 verbose bad json <title>404 - ???? ??? ????????? a?? ?? ???????.</title>
23 verbose bad json <style type="text/css">
23 verbose bad json <!--
23 verbose bad json body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
23 verbose bad json fieldset{padding:0 15px 10px 15px;}
23 verbose bad json h1{font-size:2.4em;margin:0;color:#FFF;}
23 verbose bad json h2{font-size:1.7em;margin:0;color:#CC0000;}
23 verbose bad json h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;}
23 verbose bad json #header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
23 verbose bad json background-color:#555555;}
23 verbose bad json #content{margin:0 0 0 2%;position:relative;}
23 verbose bad json .content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
23 verbose bad json -->
23 verbose bad json </style>
23 verbose bad json </head>
23 verbose bad json <body>
23 verbose bad json <div id="header"><h1>???? ????</h1></div>
23 verbose bad json <div id="content">
23 verbose bad json  <div class="content-container"><fieldset>
23 verbose bad json   <h2>404 - ???? ??? ????????? a?? ?? ???????.</h2>
23 verbose bad json   <h3>a?? ??? ??????? ????????? ????? ?????????? ????????? ?????? ?? ???????.</h3>
23 verbose bad json  </fieldset></div>
23 verbose bad json </div>
23 verbose bad json </body>
23 verbose bad json </html>
24 error registry error parsing json
25 verbose headers { 'content-type': 'text/html',
25 verbose headers   server: 'Microsoft-IIS/7.5',
25 verbose headers   date: 'Thu, 23 Jul 2015 07:56:56 GMT',
25 verbose headers   'content-length': '1238' }
26 silly get cb [ 404,
26 silly get   { 'content-type': 'text/html',
26 silly get     server: 'Microsoft-IIS/7.5',
26 silly get     date: 'Thu, 23 Jul 2015 07:56:56 GMT',
26 silly get     'content-length': '1238' } ]
27 verbose stack SyntaxError: Unexpected token <
27 verbose stack <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
27 verbose stack <html xmlns="http://www.w3.org/1999/xhtml">
27 verbose stack <head>
27 verbose stack <meta http-equiv="Content-Type" content="text/html; charset=ks_c_5601-1987"/>
27 verbose stack <title>404 - ???? ??? ????????? a?? ?? ???????.</title>
27 verbose stack <style type="text/css">
27 verbose stack <!--
27 verbose stack body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
27 verbose stack fieldset{padding:0 15px 10px 15px;}
27 verbose stack h1{font-size:2.4em;margin:0;color:#FFF;}
27 verbose stack h2{font-size:1.7em;margin:0;color:#CC0000;}
27 verbose stack h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;}
27 verbose stack #header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
27 verbose stack background-color:#555555;}
27 verbose stack #content{margin:0 0 0 2%;position:relative;}
27 verbose stack .content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
27 verbose stack -->
27 verbose stack </style>
27 verbose stack </head>
27 verbose stack <body>
27 verbose stack <div id="header"><h1>???? ????</h1></div>
27 verbose stack <div id="content">
27 verbose stack  <div class="content-container"><fieldset>
27 verbose stack   <h2>404 - ???? ??? ????????? a?? ?? ???????.</h2>
27 verbose stack   <h3>a?? ??? ??????? ????????? ????? ?????????? ????????? ?????? ?? ???????.</h3>
27 verbose stack  </fieldset></div>
27 verbose stack </div>
27 verbose stack </body>
27 verbose stack </html>
27 verbose stack
27 verbose stack     at Object.parse (native)
27 verbose stack     at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:197:23)
27 verbose stack     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:170:14)
27 verbose stack     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:354:22)
27 verbose stack     at Request.emit (events.js:110:17)
27 verbose stack     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1207:14)
27 verbose stack     at Request.emit (events.js:129:20)
27 verbose stack     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1153:12)
27 verbose stack     at IncomingMessage.emit (events.js:129:20)
27 verbose stack     at _stream_readable.js:908:16
28 verbose cwd C:\Windows\system32
29 error Windows_NT 6.1.7601
30 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "bower"
31 error node v0.12.7
32 error npm  v2.11.3
33 error Unexpected token <
33 error <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
33 error <html xmlns="http://www.w3.org/1999/xhtml">
33 error <head>
33 error <meta http-equiv="Content-Type" content="text/html; charset=ks_c_5601-1987"/>
33 error <title>404 - ???? ??? ????????? a?? ?? ???????.</title>
33 error <style type="text/css">
33 error <!--
33 error body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
33 error fieldset{padding:0 15px 10px 15px;}
33 error h1{font-size:2.4em;margin:0;color:#FFF;}
33 error h2{font-size:1.7em;margin:0;color:#CC0000;}
33 error h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;}
33 error #header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
33 error background-color:#555555;}
33 error #content{margin:0 0 0 2%;position:relative;}
33 error .content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
33 error -->
33 error </style>
33 error </head>
33 error <body>
33 error <div id="header"><h1>???? ????</h1></div>
33 error <div id="content">
33 error  <div class="content-container"><fieldset>
33 error   <h2>404 - ???? ??? ????????? a?? ?? ???????.</h2>
33 error   <h3>a?? ??? ??????? ????????? ????? ?????????? ????????? ?????? ?? ???????.</h3>
33 error  </fieldset></div>
33 error </div>
33 error </body>
33 error </html>
34 error If you need help, you may report this error at:
34 error     <https://github.com/npm/npm/issues>
35 verbose exit [ 1, true ]
```

**Comment by smikes** [comment]
It looks like your proxy requires you to log in.  You may need to set up a proxy that `npm` can use, which provides your login credentials to your company proxy.  Often people use `cntlm` for this -- http://cntlm.sourceforge.net/ is the project page, and you may find these instructions useful - https://stackoverflow.com/questions/18569054/npm-behind-ntlm-proxy

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues. If this is still a problem, can you please reply and let us know? We’ll be happy to reopen if necessary.
