### ISSUE TITLE
Error Globally installing selenium-standalone 

### ISSUE THREAD

**Issue by JMDHo** [npm/npm#9043]
Hi Team,
Trying to install selenium-standalone CLI with npm under RHEL6.5, i get the following error:
-bash-4.1$ sudo npm install selenium-standalone@latest -g
npm http GET https://registry.npmjs.org/selenium-standalone
npm http 304 https://registry.npmjs.org/selenium-standalone
npm http GET https://registry.npmjs.org/commander/2.6.0
npm http GET https://registry.npmjs.org/lodash/3.9.3
npm http GET https://registry.npmjs.org/minimist/1.1.0
npm http GET https://registry.npmjs.org/mkdirp/0.5.0
npm http GET https://registry.npmjs.org/progress/1.1.8
npm http GET https://registry.npmjs.org/request/2.51.0
npm http GET https://registry.npmjs.org/unzip/0.1.11
npm http GET https://registry.npmjs.org/which/1.1.1
npm http GET https://registry.npmjs.org/URIjs/1.15.0
npm http GET https://registry.npmjs.org/async/1.2.1
npm http 304 https://registry.npmjs.org/progress/1.1.8
npm http 304 https://registry.npmjs.org/mkdirp/0.5.0
npm http 304 https://registry.npmjs.org/minimist/1.1.0
npm http 304 https://registry.npmjs.org/commander/2.6.0
npm http 304 https://registry.npmjs.org/URIjs/1.15.0
npm http 304 https://registry.npmjs.org/async/1.2.1
npm http 304 https://registry.npmjs.org/lodash/3.9.3
npm http 304 https://registry.npmjs.org/request/2.51.0
npm http 304 https://registry.npmjs.org/unzip/0.1.11
npm http 304 https://registry.npmjs.org/which/1.1.1
npm http GET https://registry.npmjs.org/is-absolute
npm ERR! tar.unpack untar error /root/.npm/async/1.2.1/package.tgz
npm http 304 https://registry.npmjs.org/is-absolute
npm http GET https://registry.npmjs.org/minimist/0.0.8
npm ERR! Error: ENOENT, lstat '/usr/lib/node_modules/selenium-standalone/node_modules/async/coverage/base.css'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 2.6.32-504.30.3.el6.x86_64
npm ERR! command "node" "/usr/bin/npm" "install" "selenium-standalone@latest" "-g"
npm ERR! cwd /someWo

rkingDir
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.3.6
npm ERR! path /usr/lib/node_modules/selenium-standalone/node_modules/async/coverage/base.css
npm ERR! fstream_path /usr/lib/node_modules/selenium-standalone/node_modules/async/coverage/base.css
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:108:15)
npm ERR! error rolling back Error: ENOTEMPTY, rmdir '/usr/lib/node_modules/selenium-standalone/node_modules/which/node_modules'
npm ERR! error rolling back  selenium-standalone@4.5.3 { [Error: ENOTEMPTY, rmdir '/usr/lib/node_modules/selenium-standalone/node_modules/which/node_modules']
npm ERR! error rolling back   errno: 53,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   path: '/usr/lib/node_modules/selenium-standalone/node_modules/which/node_modules' }
npm ERR! Error: unexpected eof
npm ERR!     at decorate (/usr/lib/node_modules/fstream/lib/abstract.js:67:36)
npm ERR!     at Extract.Abstract.error (/usr/lib/node_modules/fstream/lib/abstract.js:61:12)
npm ERR!     at Extract._streamEnd (/usr/lib/node_modules/tar/lib/extract.js:75:22)
npm ERR!     at BlockStream.<anonymous> (/usr/lib/node_modules/tar/lib/parse.js:50:8)
npm ERR!     at BlockStream.emit (events.js:92:17)
npm ERR!     at BlockStream._emitChunk (/usr/lib/node_modules/block-stream/block-stream.js:203:10)
npm ERR!     at BlockStream.resume (/usr/lib/node_modules/block-stream/block-stream.js:58:15)
npm ERR!     at Extract.Reader.resume (/usr/lib/node_modules/fstream/lib/reader.js:252:34)
npm ERR!     at Entry.<anonymous> (/usr/lib/node_modules/tar/lib/parse.js:256:8)
npm ERR!     at Entry.emit (events.js:92:17)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 2.6.32-504.30.3.el6.x86_64
npm ERR! command "node" "/usr/bin/npm" "install" "selenium-standalone@latest" "-g"
npm ERR! cwd /someWorkingDir
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.3.6
npm ERR! fstream_class Extract
npm ERR! fstream_stack Extract._streamEnd (/usr/lib/node_modules/tar/lib/extract.js:75:22)
npm ERR! fstream_stack BlockStream.<anonymous> (/usr/lib/node_modules/tar/lib/parse.js:50:8)
npm ERR! fstream_stack BlockStream.emit (events.js:92:17)
npm ERR! fstream_stack BlockStream._emitChunk (/usr/lib/node_modules/block-stream/block-stream.js:203:10)
npm ERR! fstream_stack BlockStream.resume (/usr/lib/node_modules/block-stream/block-stream.js:58:15)
npm ERR! fstream_stack Extract.Reader.resume (/usr/lib/node_modules/fstream/lib/reader.js:252:34)
npm ERR! fstream_stack Entry.<anonymous> (/usr/lib/node_modules/tar/lib/parse.js:256:8)
npm ERR! fstream_stack Entry.emit (events.js:92:17)
npm ERR! Error: ENOENT, lstat '/usr/lib/node_modules/selenium-standalone/node_modules/URIjs/src/URI.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 2.6.32-504.30.3.el6.x86_64
npm ERR! command "node" "/usr/bin/npm" "install" "selenium-standalone@latest" "-g"
npm ERR! cwd /someWorkingDIr
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.3.6
npm ERR! path /usr/lib/node_modules/selenium-standalone/node_modules/URIjs/src/URI.js
npm ERR! fstream_path /usr/lib/node_modules/selenium-standalone/node_modules/URIjs/src/URI.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:108:15)
npm ERR! Error: ENOENT, lstat '/usr/lib/node_modules/selenium-standalone/node_modules/request/CHANGELOG.md'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 2.6.32-504.30.3.el6.x86_64
npm ERR! command "node" "/usr/bin/npm" "install" "selenium-standalone@latest" "-g"
npm ERR! cwd /someWorkingDir
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.3.6
npm ERR! path /usr/lib/node_modules/selenium-standalone/node_modules/request/CHANGELOG.md
npm ERR! fstream_path /usr/lib/node_modules/selenium-standalone/node_modules/request/CHANGELOG.md
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:108:15)
npm http 304 https://registry.npmjs.org/minimist/0.0.8
npm ERR! Error: ENOENT, lstat '/usr/lib/node_modules/selenium-standalone/node_modules/lodash/index.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 2.6.32-504.30.3.el6.x86_64
npm ERR! command "node" "/usr/bin/npm" "install" "selenium-standalone@latest" "-g"
npm ERR! cwd /someWorkingDir
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.3.6
npm ERR! path /usr/lib/node_modules/selenium-standalone/node_modules/lodash/index.js
npm ERR! fstream_path /usr/lib/node_modules/selenium-standalone/node_modules/lodash/index.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:108:15)
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /someWorkingDir/npm-debug.log
npm ERR! not ok code 0
-bash-4.1$ 

I can send you npm-debug.log file if you need.

Any idea on how to cure this issue ? Is it due to installed versions incompatibilities ?
Thanks in advance.

**Comment by JMDHo** [comment]
The faulty file was in the logs : 
> npm ERR! tar.unpack untar error /root/.npm/async/1.2.1/package.tgz
removing the /root/.npm/async/1.2.1/package.tgz solved the issue.
Sorry for the buzz...
