### ISSUE TITLE
Failure in trying to publish large module

### ISSUE THREAD

**Issue by keithamus** [npm/npm#9045]
I have a module which is mostly image assets, and its failing to publish to my private registry. Here's the log:

```
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! publish Failed PUT 503
npm ERR! Darwin 14.3.0
npm ERR! argv "~/.nvm/versions/io.js/v2.2.1/bin/iojs" "~/.nvm/versions/io.js/v2.2.1/bin/npm" "--userconfig=~/.npmrcs/<snip>" "pub"
npm ERR! node v2.2.1
npm ERR! npm  v2.12.1

npm ERR! Unexpected token <
npm ERR!
npm ERR! <?xml version="1.0" encoding="utf-8"?>
npm ERR! <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
npm ERR!  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
npm ERR! <html>
npm ERR!   <head>
npm ERR!     <title>503 backend read error</title>
npm ERR!   </head>
npm ERR!   <body>
npm ERR!     <h1>Error 503 backend read error</h1>
npm ERR!     <p>backend read error</p>
npm ERR!     <h3>Guru Mediation:</h3>
npm ERR!     <p>Details: cache-lhr6325-LHR 1437673745 1074376012</p>
npm ERR!     <hr>
npm ERR!     <p>Varnish cache server</p>
npm ERR!   </body>
npm ERR! </html>
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

**Comment by keithamus** [comment]
Longer logs:

```bash
$ npm pub --loglevel=silly
npm info it worked if it ends with ok
npm verb cli [ '~/.nvm/versions/io.js/v2.2.1/bin/iojs',
npm verb cli   '~/.nvm/versions/io.js/v2.2.1/bin/npm',
npm verb cli   '--userconfig=~/.npmrcs/<snip>',
npm verb cli   'pub',
npm verb cli   '--loglevel=silly' ]
npm info using npm@2.12.1
npm info using node@v2.2.1
npm verb publish [ '.' ]
npm sill cache add args [ '.', null ]
npm verb cache add spec .
npm sill cache add parsed spec { raw: '.',
npm sill cache add   scope: null,
npm sill cache add   name: null,
npm sill cache add   rawSpec: '.',
npm sill cache add   spec: '~/Projects/<snip>',
npm sill cache add   type: 'directory' }
npm verb addLocalDirectory ~/.npm/<snip>/0.0.2/package.tgz not in flight; packing
npm verb tar pack [ '~/.npm/<snip>/0.0.2/package.tgz',
npm verb tar pack   '~/Projects/<snip>' ]
npm verb tarball ~/.npm/<snip>/0.0.2/package.tgz
npm verb folder ~/Projects/<snip>
npm info prepublish <snip>@0.0.2
npm verb addLocalTarball adding from inside cache ~/.npm/<snip>/0.0.2/package.tgz
npm sill cache afterAdd <snip>@0.0.2
npm verb afterAdd ~/.npm/<snip>/0.0.2/package/package.json not in flight; writing
npm verb afterAdd ~/.npm/<snip>/0.0.2/package/package.json written
<--- snip --->
npm verb getPublishConfig undefined
npm sill mapToRegistry name <snip>
npm sill mapToRegistry scope (from package name) @<snip>
npm verb mapToRegistry no registry URL found in name for scope @<snip>
npm sill mapToRegistry using default registry
npm sill mapToRegistry registry https://registry.npmjs.org/
npm sill mapToRegistry uri https://registry.npmjs.org/@<snip>
npm verb publish registryBase https://registry.npmjs.org/
npm sill publish uploading ~/.npm/<snip>/0.0.2/package.tgz
npm verb request uri https://registry.npmjs.org/@<snip>
npm verb request sending authorization for write operation
npm info attempt registry request try #1 at 20:16:32
npm verb request using bearer token for auth
npm verb request id a2eeeb6a9b6b390e
npm http request PUT https://registry.npmjs.org/@<snip>
npm http 503 https://registry.npmjs.org/@<snip>
npm verb bad json
npm verb bad json <?xml version="1.0" encoding="utf-8"?>
npm verb bad json <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
npm verb bad json  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
npm verb bad json <html>
npm verb bad json   <head>
npm verb bad json     <title>503 backend read error</title>
npm verb bad json   </head>
npm verb bad json   <body>
npm verb bad json     <h1>Error 503 backend read error</h1>
npm verb bad json     <p>backend read error</p>
npm verb bad json     <h3>Guru Mediation:</h3>
npm verb bad json     <p>Details: cache-lhr6334-LHR 1437679125 3799294287</p>
npm verb bad json     <hr>
npm verb bad json     <p>Varnish cache server</p>
npm verb bad json   </body>
npm verb bad json </html>
npm verb bad json
npm ERR! registry error parsing json
npm info retry will retry, error on last attempt: SyntaxError: Unexpected token <
npm info retry
npm info retry <?xml version="1.0" encoding="utf-8"?>
npm info retry <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
npm info retry  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
npm info retry <html>
npm info retry   <head>
npm info retry     <title>503 backend read error</title>
npm info retry   </head>
npm info retry   <body>
npm info retry     <h1>Error 503 backend read error</h1>
npm info retry     <p>backend read error</p>
npm info retry     <h3>Guru Mediation:</h3>
npm info retry     <p>Details: cache-lhr6334-LHR 1437679125 3799294287</p>
npm info retry     <hr>
npm info retry     <p>Varnish cache server</p>
npm info retry   </body>
npm info retry </html>
npm info retry
npm info attempt registry request try #2 at 20:18:55
npm verb request using bearer token for auth
npm http request PUT https://registry.npmjs.org/@<snip>
npm http 503 https://registry.npmjs.org/@<snip>
npm verb bad json
npm verb bad json <?xml version="1.0" encoding="utf-8"?>
npm verb bad json <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
npm verb bad json  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
npm verb bad json <html>
npm verb bad json   <head>
npm verb bad json     <title>503 backend read error</title>
npm verb bad json   </head>
npm verb bad json   <body>
npm verb bad json     <h1>Error 503 backend read error</h1>
npm verb bad json     <p>backend read error</p>
npm verb bad json     <h3>Guru Mediation:</h3>
npm verb bad json     <p>Details: cache-lcy1133-LCY 1437679270 1266928562</p>
npm verb bad json     <hr>
npm verb bad json     <p>Varnish cache server</p>
npm verb bad json   </body>
npm verb bad json </html>
npm verb bad json
npm ERR! registry error parsing json
npm info retry will retry, error on last attempt: SyntaxError: Unexpected token <
npm info retry
npm info retry <?xml version="1.0" encoding="utf-8"?>
npm info retry <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
npm info retry  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
npm info retry <html>
npm info retry   <head>
npm info retry     <title>503 backend read error</title>
npm info retry   </head>
npm info retry   <body>
npm info retry     <h1>Error 503 backend read error</h1>
npm info retry     <p>backend read error</p>
npm info retry     <h3>Guru Mediation:</h3>
npm info retry     <p>Details: cache-lcy1133-LCY 1437679270 1266928562</p>
npm info retry     <hr>
npm info retry     <p>Varnish cache server</p>
npm info retry   </body>
npm info retry </html>
npm info retry
npm info attempt registry request try #3 at 20:22:10
npm verb request using bearer token for auth
npm http request PUT https://registry.npmjs.org/@<snip>
npm http 503 https://registry.npmjs.org/@<snip>
npm verb bad json
npm verb bad json <?xml version="1.0" encoding="utf-8"?>
npm verb bad json <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
npm verb bad json  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
npm verb bad json <html>
npm verb bad json   <head>
npm verb bad json     <title>503 backend read error</title>
npm verb bad json   </head>
npm verb bad json   <body>
npm verb bad json     <h1>Error 503 backend read error</h1>
npm verb bad json     <p>backend read error</p>
npm verb bad json     <h3>Guru Mediation:</h3>
npm verb bad json     <p>Details: cache-lhr6321-LHR 1437679466 824248851</p>
npm verb bad json     <hr>
npm verb bad json     <p>Varnish cache server</p>
npm verb bad json   </body>
npm verb bad json </html>
npm verb bad json
npm ERR! registry error parsing json
npm verb headers { server: 'Varnish',
npm verb headers   'retry-after': '0',
npm verb headers   'content-type': 'text/html; charset=utf-8',
npm verb headers   'content-length': '447',
npm verb headers   'accept-ranges': 'bytes',
npm verb headers   date: 'Thu, 23 Jul 2015 19:24:26 GMT',
npm verb headers   via: '1.1 varnish',
npm verb headers   connection: 'close',
npm verb headers   'x-served-by': 'cache-lhr6321-LHR',
npm verb headers   'x-cache': 'MISS',
npm verb headers   'x-cache-hits': '0',
npm verb headers   'x-timer': 'S1437679331.674755,VS0,VE134493' }
npm verb request invalidating ~/.npm/registry.npmjs.org/_40economist_252fworld-if-assets on PUT
npm ERR! publish Failed PUT 503
npm verb stack SyntaxError: Unexpected token <
npm verb stack
npm verb stack <?xml version="1.0" encoding="utf-8"?>
npm verb stack <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
npm verb stack  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
npm verb stack <html>
npm verb stack   <head>
npm verb stack     <title>503 backend read error</title>
npm verb stack   </head>
npm verb stack   <body>
npm verb stack     <h1>Error 503 backend read error</h1>
npm verb stack     <p>backend read error</p>
npm verb stack     <h3>Guru Mediation:</h3>
npm verb stack     <p>Details: cache-lhr6321-LHR 1437679466 824248851</p>
npm verb stack     <hr>
npm verb stack     <p>Varnish cache server</p>
npm verb stack   </body>
npm verb stack </html>
npm verb stack
npm verb stack     at Object.parse (native)
npm verb stack     at CachingRegistryClient.<anonymous> (~/.nvm/versions/io.js/v2.2.1/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:197:23)
npm verb stack     at Request._callback (~/.nvm/versions/io.js/v2.2.1/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:170:14)
npm verb stack     at Request.self.callback (~/.nvm/versions/io.js/v2.2.1/lib/node_modules/npm/node_modules/request/request.js:197:22)
npm verb stack     at emitTwo (events.js:87:13)
npm verb stack     at Request.emit (events.js:172:7)
npm verb stack     at Request.<anonymous> (~/.nvm/versions/io.js/v2.2.1/lib/node_modules/npm/node_modules/request/request.js:1050:14)
npm verb stack     at emitOne (events.js:82:20)
npm verb stack     at Request.emit (events.js:169:7)
npm verb stack     at IncomingMessage.<anonymous> (~/.nvm/versions/io.js/v2.2.1/lib/node_modules/npm/node_modules/request/request.js:996:12)
npm verb cwd ~/Projects/<snip>
npm ERR! Darwin 14.3.0
npm ERR! argv "~/.nvm/versions/io.js/v2.2.1/bin/iojs" "~/.nvm/versions/io.js/v2.2.1/bin/npm" "--userconfig=~/.npmrcs/<snip>" "pub" "--loglevel=silly"
npm ERR! node v2.2.1
npm ERR! npm  v2.12.1

npm ERR! Unexpected token <
npm ERR!
npm ERR! <?xml version="1.0" encoding="utf-8"?>
npm ERR! <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
npm ERR!  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
npm ERR! <html>
npm ERR!   <head>
npm ERR!     <title>503 backend read error</title>
npm ERR!   </head>
npm ERR!   <body>
npm ERR!     <h1>Error 503 backend read error</h1>
npm ERR!     <p>backend read error</p>
npm ERR!     <h3>Guru Mediation:</h3>
npm ERR!     <p>Details: cache-lhr6321-LHR 1437679466 824248851</p>
npm ERR!     <hr>
npm ERR!     <p>Varnish cache server</p>
npm ERR!   </body>
npm ERR! </html>
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm verb exit [ 1, true ]

npm ERR! Please include the following file with any support request:
npm ERR!     ~/Projects/<snip>/npm-debug.log
```

It is actually uploading though:

```bash
$ npm view @<snip>

{ name: '@<snip>',
  'dist-tags': { latest: '0.0.2' },
  versions: [ '0.0.0', '0.0.1', '0.0.2' ],
<--- snip --->
  dist:
   { shasum: '6f515a23561dec419f8af52f86b0c1d8f29f3d50',
     tarball: 'http://registry.npmjs.org/@<snip>/-/<snip>-0.0.2.tgz' },
  directories: {} }
```

**Comment by snopeks** [comment]
Hi @keithamus, it does look like your package published successfully, but because the package is so large the connection got cut off before npm could send you the nice confirmation message. Thanks for letting us know, we're working to fix this problem. In the meantime, you could work around this issue by splitting large packages into smaller packages. I'm going to close this issue, but if you run into further errors let us know, we'll be happy to reopen. Thanks!

**Comment by buhe** [comment]
I create a React Native repo include large native lib (file size is 117m) , I have same issue here.
