### ISSUE TITLE
local dependency error performing npm update for npm > 2.9.1 on Windows 7

### ISSUE THREAD

**Issue by yokai0** [npm/npm#9054]
A little bit of background: 

We have a node project that uses a hacked-about version of express-http-proxy. 
We store this in a sub-folder of the project: ./custom_node_modules/express-http-proxy

The project gets checked in to source control without a node_modules folder; developers are expected to perform an 'npm update' to pull in all of the necessary packages. 

The dependency section of our package.json looks like this:
```
 "dependencies": {
    "clone": "^1.0.0",
    "connect": "^3.3.4",
    "dateformat": "^1.0.11",
    "deep-copy": "^1.0.0",
    "deep-equal": "^1.0.0",
    "errorhandler": "^1.3.4",
    "express": "^4.12.0",
    "express-http-proxy": "file:./custom_node_modules/express-http-proxy",
    "extend": "^2.0.0",
    "highlight.js": "^8.4.0",
    "jade": "^1.9.2",
    "marked": "^0.3.3",
    "mkdirp": "^0.5.0",
    "morgan": "^1.5.1",
    "nodemon": "^1.3.7",
    "nomnom": "^1.8.1",
    "path-to-regexp": "^1.0.3",
    "pretty-print": "^1.0.0",
    "raw-body": "^1.3.3",
    "serve-static": "^1.9.1",
    "winston": "^0.9.0"
  },
```

With npm 2.7.4 (installed with Node 0.12.2 on Windows) this works just fine, the local module gets copied in to the node_modules folder. 

With npm 2.9.1 (installed with Node 0.12.3) we get an error:

```
npm ERR! node v0.12.3
npm ERR! npm  v2.9.1

npm ERR! Cannot read property 'version' of undefined
```

The npm-debug.log contains the following information:

```
 266 silly cache add args [ 'express-http-proxy',
 266 silly cache add   'file:./custom_node_modules/express-http-proxy' ]
 267 verbose cache add spec express-http-proxy@file:./custom_node_modules/express-http-proxy
 268 silly cache add parsed spec { raw: 'express-http-proxy@file:./custom_node_modules/express-http-proxy',
 268 silly cache add   scope: null,
 268 silly cache add   name: 'express-http-proxy',
 268 silly cache add   rawSpec: 'file:./custom_node_modules/express-http-proxy',
 268 silly cache add   spec: 'C:\\development\\project\\custom_node_modules\\express-http-proxy',
 268 silly cache add   type: 'directory' }
 269 verbose addLocalDirectory C:\Users\yokai0\AppData\Roaming\npm-cache\express-http-proxy\0.3.1\package.tgz not in flight; packing
 270 verbose tar pack [ 'C:\\Users\\yokai0\\AppData\\Roaming\\npm-cache\\express-http-proxy\\0.3.1\\package.tgz',
 270 verbose tar pack   'C:\\development\\project\\custom_node_modules\\express-http-proxy' ]
 271 verbose tarball C:\Users\yokai0\AppData\Roaming\npm-cache\express-http-proxy\0.3.1\package.tgz
 272 verbose folder C:\development\project\custom_node_modules\express-http-proxy
 273 info prepublish express-http-proxy@0.3.1
 274 verbose addLocalTarball adding from inside cache C:\Users\yokai0\AppData\Roaming\npm-cache\express-http-proxy\0.3.1\package.tgz
 275 silly cache afterAdd express-http-proxy@0.3.1
 276 verbose afterAdd C:\Users\yokai0\AppData\Roaming\npm-cache\express-http-proxy\0.3.1\package\package.json not in flight; writing
 277 verbose afterAdd C:\Users\yokai0\AppData\Roaming\npm-cache\express-http-proxy\0.3.1\package\package.json written
 278 verbose stack TypeError: Cannot read property 'version' of undefined
 278 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\outdated.js:337:15
 278 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:345:5
 278 verbose stack     at checkBinReferences_ (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:309:45)
 278 verbose stack     at final (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:343:3)
 278 verbose stack     at then (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:113:5)
 278 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:232:12
 278 verbose stack     at evalmachine.<anonymous>:334:14
 278 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:102:5
 278 verbose stack     at FSReqWrap.oncomplete (evalmachine.<anonymous>:95:15)
 279 verbose cwd C:\development\project
 280 error Windows_NT 6.1.7601
```

Performing 'npm link ./custom_node_modules/express-http-proxy' before npm update works, but I don't think that should be necessary.

Nothing I've seen in the docs makes me think we're doing anything wrong (?) but I'm happy to be corrected.

**Comment by smikes** [comment]
There's nothing *wrong* with what you're doing, but it might be easier if you used a git repository dependency instead of the local file dependency.

Is there any reason you don't run an `npm install` before the `npm update`? Or does it still fail in that case?  I think `npm install` should fetch the express-http-proxy from your custom file path..

**Comment by othiym23** [comment]
Is there any particular reason you're using `npm@2.9.1`? There was some churn in the code base around then having to do with `read-package-json` (a dependency that does what its name says) and `outdated` (which `npm update` uses to build its list of update targets), and upgrading to the latest stable version might fix that.

**Comment by yokai0** [comment]
@smikes - Ah, yes thank you, `npm install` before `npm update` does work (as does `npm link`, although, granted, there may be reasons you wouldn't want a symlink to a dependency). 
It still seems like a bit of a regression, resulting in a discrepancy of behaviour between local/non-local dependencies.

@othiym23 - I should have said, I initially tried with 2.11.2 (the version bundled with Node 0.12.7 for Windows) and went to the trouble of manually updating npm to 2.13.2 but the results were the same. 

I then tried each of the Node installers back to 0.12.2 and found it worked with `npm@2.7.4` (0.12.2) and not with `npm@2.9.1` (0.12.3). 

I'll admit I haven't checked every point release of npm between 2.7.4 and 2.9.1 to see when it stopped working, but the line that's erroring wasn't introduced until 2.9.0 in https://github.com/npm/npm/commit/279932298ce5b589c5eea9439ac40b88b99c6a4a. 


Looking at it, I think the line:
`if (curr.version !== wanted) {` 
Should probably read:

`if (!curr || curr.version !== wanted) {`

But I don't know enough about it to say if that's correct.

**Comment by yokai0** [comment]
Correction: `npm install` works initially, but a subsequent `npm update` results in the latest version of the package being pulled in from the remote repository rather than the local one.

**Comment by othiym23** [comment]
@yokai0 I think that patch is reasonable. If you wanted to put together a quick patch (including a test that fails with the current behavior), it would get included shortly after we get a chance to review and merge it. Thanks for digging into this!

**Comment by yokai0** [comment]
Sure, I can take a look at it. 

It seems that there are other places in outdated.js that need to take in to account that a dependency is local. I've only given it a cursory glance so far, I'll try and find some time to look in to it in a bit more detail.

**Comment by kentingxu** [comment]
I have the same problem with `npm@3.3.12`. `npm update` throws error "Cannot read property 'version' of undefined" for local dependencies. Run `npm install` before `npm update` solve the problem.
So it seems the problem is not only in `npm@2.x.x`.

**Comment by HairyJeremy** [comment]
I did some work to attempt to fix this for my own particular usage. It kind-of works for me (diff from master attached) [npm_update_localdep_partial_fix.txt](https://github.com/npm/npm/files/85200/npm_update_localdep_partial_fix.txt). 

I worked on the basis that:
- local dependencies always have the type 'directory' (and they are the only dependencies with this type)
- npm should always check for newer versions of local dependencies by reading the local package.json
- local dependencies should never be compared against/be replaced by the remote repository version, even if the remote version is 'newer'
- if the local dependency isn't present in node_modules it should be installed by npm update

The only problem seems to be that it's broken other functionality (private packages, linked git dependencies, scoped packages etc.) I think maybe my first assumption is wrong. I didn't have the time to delve in to it further; the deps/outdated logic seems to be full of caveats and I wasn't sure adding to it was the best plan. 


I don't change my local dependency often so I get by using ```npm install``` with the necessary clear node_modules, perform another ```npm install``` if I need to update it. 


I haven't tried it, but you might have better luck putting your 'local' package in to a local git repository and referencing it that way instead.

**Comment by Enteee** [comment]
same problem here with 3.10.8.
>  Run npm install before npm update solve the problem.

**Comment by maxm007** [comment]
Same pronlem with 3.10.10

**Comment by schmunk42** [comment]
Same problem in 3.10.10, fixed for me in 5.4.2
