### ISSUE TITLE
npm install --save git+ssh://host/foo.git results in crash

### ISSUE THREAD

**Issue by iarna** [npm/npm#9077]
```
53 verbose stack Error: Unsupported URL Type: ssh://host/foo.git
53 verbose stack     at parseUrl ($HOME/.nvm/versions/v0.12.2/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:168:13)
53 verbose stack     at npa ($HOME/.nvm/versions/v0.12.2/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:75:12)
53 verbose stack     at isProdDep ($HOME/.nvm/versions/v0.12.2/lib/node_modules/npm/lib/install/deps.js:55:10)
53 verbose stack     at isDep ($HOME/.nvm/versions/v0.12.2/lib/node_modules/npm/lib/install/deps.js:35:19)
53 verbose stack     at addRequiredDep ($HOME/.nvm/versions/v0.12.2/lib/node_modules/npm/lib/install/deps.js:112:8)
53 verbose stack     at $HOME/.nvm/versions/v0.12.2/lib/node_modules/npm/lib/install/deps.js:185:12
53 verbose stack     at $HOME/.nvm/versions/v0.12.2/lib/node_modules/npm/node_modules/iferr/index.js:13:50
53 verbose stack     at $HOME/.nvm/versions/v0.12.2/lib/node_modules/npm/lib/install/deps.js:426:7
53 verbose stack     at $HOME/.nvm/versions/v0.12.2/lib/node_modules/npm/node_modules/iferr/index.js:13:50
53 verbose stack     at addBundled ($HOME/.nvm/versions/v0.12.2/lib/node_modules/npm/lib/fetch-package-metadata.js:209:39)
```

**Comment by iarna** [comment]
Released in 3.2.2
