### ISSUE TITLE
Error on install bluetooth obd

### ISSUE THREAD

**Issue by nilmarpublio** [npm/npm#9094]
Hi all,

Can anybody explain how do I to correct this error below?
Trying to install node bluetooth-obd.

Thanks in advance.

Nilmar Castro.

```
iMac-de-Usuario:~ Usuario$ npm install bluetooth-obd
npm ERR! Error: Attempt to unlock bluetooth-obd, which hasn't been locked
npm ERR!     at unlock (/usr/local/lib/node_modules/npm/lib/utils/locker.js:44:11)
npm ERR!     at cb (/usr/local/lib/node_modules/npm/lib/cache/add-local.js:30:5)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache/add-local.js:47:20
npm ERR!     at /usr/local/lib/node_modules/npm/lib/utils/locker.js:30:7
npm ERR!     at cb (/usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:149:38)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:177:38
npm ERR!     at Object.oncomplete (fs.js:108:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 14.4.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "bluetooth-obd"
npm ERR! cwd /Users/Usuario
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/Usuario/npm-debug.log
npm ERR! not ok code 0
iMac-de-Usuario:~ Usuario$  Error: Attempt to unlock bluetooth-obd, which hasn't been locked
```

**Comment by othiym23** [comment]
Please [install the latest stable version of npm](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) and this problem should go away. (You might also need to run `npm cache clean`.)

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues. If this is still a problem, can you please reply and let us know? We’ll be happy to reopen if necessary.
