### ISSUE TITLE
register private repo

### ISSUE THREAD

**Issue by cyberua** [npm/npm#9116]
I want use local server for npm, configured npm and i want register new repo
````
npm publish ./npmp --scope=myco 
````
If i use ````npm i <package>````, he takes packeges from local repo
config:
````
registry=http://test:test@localhost:5984/registry
@myco:registry=http://test:test@localhost:5984/registry
````

But i have error   (password and login correct)
````
Error: unauthorized Name or password is incorrect.: registry/test2222

ublish Failed PUT 401
npm ERR! Error: unauthorized Name or password is incorrect.: test2222
npm ERR!     at RegClient.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:308:14)
npm ERR!     at Request._callback (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:246:65)
npm ERR!     at Request.self.callback (/usr/lib/node_modules/npm/node_modules/request/request.js:236:22)
npm ERR!     at Request.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/lib/node_modules/npm/node_modules/request/request.js:1142:14)
npm ERR!     at Request.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/lib/node_modules/npm/node_modules/request/request.js:1096:12)
npm ERR!     at IncomingMessage.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:944:16
npm ERR!     at process._tickCallback (node.js:448:13)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.13.0-59-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "publish" "./npmp"
npm ERR! cwd /home/name/test_modules
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/ash/test_modules/npm-debug.log
npm ERR! not ok code 0

````

**Comment by cyberua** [comment]
Why he sent PUT request on localhost:5984/registry/test2222 if for couchdb need sent to localhost:5984/registry and POST for added data ?

**Comment by KenanY** [comment]
@cyberua Does this also occur if you [upgrade](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) to the latest stable release of `npm`?

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some old issues. If this is still a problem, can you please reply and let us know? We’ll be happy to reopen if necessary.
