### ISSUE TITLE
npm error when trying to update-install ionic (npm install -g ionic)

### ISSUE THREAD

**Issue by gchristakis** [npm/npm#9123]
```
0 info it worked if it ends with ok
1 verbose cli [ 'node',
1 verbose cli   'C:\\Users\\gchristakis\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'ionic' ]
2 info using npm@2.12.0
3 info using node@v0.10.33
4 verbose install initial load of C:\Program\package.json
5 verbose readDependencies loading dependencies from C:\Program\package.json
6 silly cache add args [ 'ionic', null ]
7 verbose cache add spec ionic
8 silly cache add parsed spec { raw: 'ionic',
8 silly cache add   scope: null,
8 silly cache add   name: 'ionic',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: '*',
8 silly cache add   type: 'range' }
9 silly addNamed ionic@*
10 verbose addNamed "*" is a valid semver range for ionic
11 silly addNameRange { name: 'ionic', range: '*', hasData: false }
12 silly mapToRegistry name ionic
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/ionic
16 verbose addNameRange registry:https://registry.npmjs.org/ionic not in flight; fetching
17 verbose request uri https://registry.npmjs.org/ionic
18 verbose request no auth needed
19 info attempt registry request try #1 at 13:58:42
20 verbose request id 96c06cfc4e4a4e0c
21 http request GET https://registry.npmjs.org/ionic
22 http 200 https://registry.npmjs.org/ionic
23 silly get cb [ 200,
23 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
23 silly get     etag: '"2X7IJ1GV5B1G6UHT8DRQI867W"',
23 silly get     'content-type': 'application/json',
23 silly get     'cache-control': 'max-age=60',
23 silly get     'content-length': '468183',
23 silly get     'accept-ranges': 'bytes',
23 silly get     date: 'Fri, 31 Jul 2015 10:58:42 GMT',
23 silly get     via: '1.1 varnish',
23 silly get     age: '0',
23 silly get     connection: 'keep-alive',
23 silly get     'x-served-by': 'cache-lcy1134-LCY',
23 silly get     'x-cache': 'HIT',
23 silly get     'x-cache-hits': '1',
23 silly get     'x-timer': 'S1438340322.252523,VS0,VE154',
23 silly get     vary: 'Accept' } ]
24 verbose get saving ionic to C:\Users\gchristakis\AppData\Roaming\npm-cache\registry.npmjs.org\ionic\.cache.json
25 verbose type undefined_method
26 verbose stack TypeError: Object #<process> has no method 'getuid'
26 verbose stack     at calculateOwner (C:\Users\gchristakis\AppData\Roaming\npm\node_modules\npm\lib\utils\correct-mkdir.js:37:24)
26 verbose stack     at C:\Users\gchristakis\AppData\Roaming\npm\node_modules\npm\lib\utils\correct-mkdir.js:23:22
26 verbose stack     at Object.oncomplete (evalmachine.<anonymous>:107:15)
27 verbose cwd C:\Users\gchristakis\Documents\Visual Studio 2015\Projects\IonicCordovaProject1\IonicCordovaProject1
28 error Windows_NT 6.2.9200
29 error argv "node" "C:\\Users\\gchristakis\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "ionic"
30 error node v0.10.33
31 error npm  v2.12.0
32 error Object #<process> has no method 'getuid'
33 error If you need help, you may report this error at:
33 error     <https://github.com/npm/npm/issues>
34 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
@gchristakis This was a bug with `npm@2.12.0` that specifically affected Windows installations. `npm@2.12.1` contains the fix, so please try [upgrading](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows).

**Comment by othiym23** [comment]
@KenanY is right (as always) – `npm@2.12.0` was DOA on Windows (sorry!), so the fastest way to get everything fixed is to reinstall Node and then update the bundled npm to latest again. Closing as resolved!
