### ISSUE TITLE
npm install Cannot read property 'trim' of undefined

### ISSUE THREAD

**Issue by coreywitherow** [npm/npm#9136]
I pulled down the latest version of bootstrap from github and attempted to run the npm install command on the directory location where the Gruntfile.js is located and got an error "Cannot read property 'trim' of undefined.  Below is the log file I got.  Any ideas on how to resolve this?

```
0 info it worked if it ends with ok
1 verbose cli [ 'node',
1 verbose cli   'C:\\Users\\corey.witherow.WITHEROW\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@2.7.1
3 info using node@v0.12.7
4 verbose install where, deps [ 'C:\\_bootstrap\\Aim\\trunk',
4 verbose install   [ 'btoa',
4 verbose install     'glob',
4 verbose install     'grunt',
4 verbose install     'grunt-autoprefixer',
4 verbose install     'grunt-contrib-clean',
4 verbose install     'grunt-contrib-compress',
4 verbose install     'grunt-contrib-concat',
4 verbose install     'grunt-contrib-connect',
4 verbose install     'grunt-contrib-copy',
4 verbose install     'grunt-contrib-csslint',
4 verbose install     'grunt-contrib-cssmin',
4 verbose install     'grunt-contrib-htmlmin',
4 verbose install     'grunt-contrib-jade',
4 verbose install     'grunt-contrib-jshint',
4 verbose install     'grunt-contrib-less',
4 verbose install     'grunt-contrib-qunit',
4 verbose install     'grunt-contrib-uglify',
4 verbose install     'grunt-contrib-watch',
4 verbose install     'grunt-csscomb',
4 verbose install     'grunt-exec',
4 verbose install     'grunt-html',
4 verbose install     'grunt-jekyll',
4 verbose install     'grunt-jscs',
4 verbose install     'grunt-saucelabs',
4 verbose install     'grunt-sed',
4 verbose install     'load-grunt-tasks',
4 verbose install     'markdown-it',
4 verbose install     'npm-shrinkwrap',
4 verbose install     'time-grunt' ] ]
5 verbose install where, peers [ 'C:\\_bootstrap\\Aim\\trunk', [] ]
6 info preinstall bootstrap@3.3.5
7 verbose already installed skipping grunt-contrib-csslint@~0.5.0 C:\_bootstrap\Aim\trunk
8 verbose already installed skipping grunt-contrib-cssmin@~0.12.3 C:\_bootstrap\Aim\trunk
9 verbose already installed skipping grunt-contrib-htmlmin@~0.4.0 C:\_bootstrap\Aim\trunk
10 verbose already installed skipping grunt-contrib-jade@~0.15.0 C:\_bootstrap\Aim\trunk
11 verbose already installed skipping grunt-contrib-jshint@~0.11.2 C:\_bootstrap\Aim\trunk
12 verbose already installed skipping grunt-contrib-less@~1.0.1 C:\_bootstrap\Aim\trunk
13 verbose already installed skipping grunt-contrib-qunit@~0.7.0 C:\_bootstrap\Aim\trunk
14 verbose already installed skipping grunt-contrib-uglify@~0.9.1 C:\_bootstrap\Aim\trunk
15 verbose already installed skipping grunt-contrib-watch@~0.6.1 C:\_bootstrap\Aim\trunk
16 verbose already installed skipping grunt-csscomb@~3.0.1 C:\_bootstrap\Aim\trunk
17 verbose already installed skipping grunt-exec@~0.4.6 C:\_bootstrap\Aim\trunk
18 verbose already installed skipping grunt-html@~4.0.3 C:\_bootstrap\Aim\trunk
19 verbose already installed skipping grunt-jekyll@~0.4.2 C:\_bootstrap\Aim\trunk
20 verbose already installed skipping grunt-jscs@~1.8.0 C:\_bootstrap\Aim\trunk
21 verbose already installed skipping grunt-saucelabs@~8.6.1 C:\_bootstrap\Aim\trunk
22 silly cache add args [ 'grunt-sed@git+https://github.com/twbs/grunt-sed#v0.2.0',
22 silly cache add   null ]
23 verbose cache add spec grunt-sed@git+https://github.com/twbs/grunt-sed#v0.2.0
24 verbose already installed skipping load-grunt-tasks@~3.2.0 C:\_bootstrap\Aim\trunk
25 verbose already installed skipping markdown-it@^4.4.0 C:\_bootstrap\Aim\trunk
26 verbose already installed skipping npm-shrinkwrap@^200.4.0 C:\_bootstrap\Aim\trunk
27 verbose already installed skipping time-grunt@^1.2.1 C:\_bootstrap\Aim\trunk
28 verbose already installed skipping btoa@~1.1.2 C:\_bootstrap\Aim\trunk
29 verbose already installed skipping glob@~5.0.14 C:\_bootstrap\Aim\trunk
30 silly cache add parsed spec { raw: 'grunt-sed@git+https://github.com/twbs/grunt-sed#v0.2.0',
30 silly cache add   scope: null,
30 silly cache add   name: 'grunt-sed',
30 silly cache add   rawSpec: 'git+https://github.com/twbs/grunt-sed#v0.2.0',
30 silly cache add   spec: 'https://github.com/twbs/grunt-sed#v0.2.0',
30 silly cache add   type: 'git' }
31 verbose addRemoteGit https-github-com-twbs-grunt-sed-2b1a3998 not in flight; caching
32 verbose already installed skipping grunt@~0.4.5 C:\_bootstrap\Aim\trunk
33 verbose already installed skipping grunt-autoprefixer@~3.0.3 C:\_bootstrap\Aim\trunk
34 verbose already installed skipping grunt-contrib-clean@~0.6.0 C:\_bootstrap\Aim\trunk
35 verbose already installed skipping grunt-contrib-compress@~0.13.0 C:\_bootstrap\Aim\trunk
36 verbose already installed skipping grunt-contrib-concat@~0.5.1 C:\_bootstrap\Aim\trunk
37 verbose already installed skipping grunt-contrib-connect@~0.10.1 C:\_bootstrap\Aim\trunk
38 verbose already installed skipping grunt-contrib-copy@~0.8.0 C:\_bootstrap\Aim\trunk
39 verbose stack TypeError: Cannot read property 'trim' of undefined
39 verbose stack     at C:\Users\corey.witherow.WITHEROW\AppData\Roaming\npm\node_modules\npm\lib\cache\add-remote-git.js:98:31
39 verbose stack     at C:\Users\corey.witherow.WITHEROW\AppData\Roaming\npm\node_modules\npm\lib\utils\git.js:50:14
39 verbose stack     at F (C:\Users\corey.witherow.WITHEROW\AppData\Roaming\npm\node_modules\npm\node_modules\which\which.js:40:25)
39 verbose stack     at E (C:\Users\corey.witherow.WITHEROW\AppData\Roaming\npm\node_modules\npm\node_modules\which\which.js:43:29)
39 verbose stack     at C:\Users\corey.witherow.WITHEROW\AppData\Roaming\npm\node_modules\npm\node_modules\which\which.js:54:16
39 verbose stack     at FSReqWrap.oncomplete (fs.js:95:15)
40 verbose cwd C:\_bootstrap\Aim\trunk
41 error Windows_NT 6.3.9600
42 error argv "node" "C:\\Users\\corey.witherow.WITHEROW\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
43 error node v0.12.7
44 error npm  v2.7.1
45 error Cannot read property 'trim' of undefined
46 error If you need help, you may report this error at:
46 error     <https://github.com/npm/npm/issues>
47 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
@coreywitherow Does this also happen if you [upgrade](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows) to the latest stable release?

**Comment by coreywitherow** [comment]
Tried upgrading and still no luck.  I even uninstalled node and re-installed and still no luck.

**Comment by georgewhite5** [comment]
I'm experiencing exactly the same issue when I install Sails.js modules, but I get much more error messages of the same type:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/4.1.1/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install' ]
2 info using npm@3.3.5
3 info using node@v4.1.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly install normalizeTree
8 verbose stack TypeError: Cannot set property 'fs-extra' of undefined
8 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/deps.js:94:36
8 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/dezalgo/dezalgo.js:17:12
8 verbose stack     at RawTask.call (/usr/local/lib/node_modules/npm/node_modules/asap/asap.js:40:19)
8 verbose stack     at flush (/usr/local/lib/node_modules/npm/node_modules/asap/raw.js:50:29)
8 verbose stack     at doNTCallback0 (node.js:407:9)
8 verbose stack     at process._tickCallback (node.js:336:13)
9 verbose cwd /Users/georgewhite/Desktop/BSM
10 error Darwin 15.0.0
11 error argv "/usr/local/Cellar/node/4.1.1/bin/node" "/usr/local/bin/npm" "install"
12 error node v4.1.1
13 error npm  v3.3.5
14 error Cannot set property 'fs-extra' of undefined
15 error If you need help, you may report this error at:
15 error     <https://github.com/npm/npm/issues>
16 verbose exit [ 1, true ]
```

**Comment by georgewhite5** [comment]
I'm on Mac OS X though and I'm using the latest node and the latest npm stable.
