### ISSUE TITLE
Less installing issue

### ISSUE THREAD

**Issue by Prince-Chaudhary** [npm/npm#9139]
I am getting "npm ERR! code UNABLE_TO_VERIFY_LEAF_SIGNATURE" error while installing LESS.
Also I am getting "npm ERR! unable to verify the first certificate".
![capture](https://cloud.githubusercontent.com/assets/13215232/9032532/53b87d78-39dd-11e5-937d-c9b84dbf5ad1.PNG)

npm-debug.log  -  content

```
0 info it worked if it ends with ok
1 verbose cli [ 'c:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'less' ]
2 info using npm@2.11.2
3 info using node@v0.12.5
4 verbose install initial load of C:\Users\prince.chaudhary\AppData\Roaming\npm\package.json
5 verbose readDependencies loading dependencies from C:\Users\prince.chaudhary\AppData\Roaming\npm\package.json
6 silly cache add args [ 'less', null ]
7 verbose cache add spec less
8 silly cache add parsed spec { raw: 'less',
8 silly cache add   scope: null,
8 silly cache add   name: 'less',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: '*',
8 silly cache add   type: 'range' }
9 silly addNamed less@*
10 verbose addNamed "*" is a valid semver range for less
11 silly addNameRange { name: 'less', range: '*', hasData: false }
12 silly mapToRegistry name less
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/less
16 verbose addNameRange registry:https://registry.npmjs.org/less not in flight; fetching
17 verbose request uri https://registry.npmjs.org/less
18 verbose request no auth needed
19 info attempt registry request try #1 at 12:39:38 PM
20 verbose request id 825911d1e50f4943
21 http request GET https://registry.npmjs.org/less
22 info retry will retry, error on last attempt: Error: unable to verify the first certificate
23 info attempt registry request try #2 at 12:39:49 PM
24 http request GET https://registry.npmjs.org/less
25 info retry will retry, error on last attempt: Error: unable to verify the first certificate
26 info attempt registry request try #3 at 12:40:49 PM
27 http request GET https://registry.npmjs.org/less
28 verbose stack Error: unable to verify the first certificate
28 verbose stack     at Error (native)
28 verbose stack     at TLSSocket.<anonymous> (_tls_wrap.js:929:36)
28 verbose stack     at TLSSocket.emit (events.js:104:17)
28 verbose stack     at TLSSocket._finishInit (_tls_wrap.js:460:8)
29 verbose cwd C:\Users\prince.chaudhary
30 error Windows_NT 6.1.7601
31 error argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "less"
32 error node v0.12.5
33 error npm  v2.11.2
34 error code UNABLE_TO_VERIFY_LEAF_SIGNATURE
35 error unable to verify the first certificate
36 error If you need help, you may report this error at:
36 error     <https://github.com/npm/npm/issues>
37 verbose exit [ 1, true ]
```

**Comment by Mletter1** [comment]
see #8872 might fix your issue
