### ISSUE TITLE
"Bad Request - Invalid Hostname" error while installing protractor on Windows 7 machine.

### ISSUE THREAD

**Issue by RaviShankarPandey** [npm/npm#9155]
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'protractor' ]
2 info using npm@2.11.3
3 info using node@v0.12.7
4 verbose install initial load of D:\PROJECT\package.json
5 verbose readDependencies loading dependencies from D:\PROJECT\package.json
6 silly cache add args [ 'protractor', null ]
7 verbose cache add spec protractor
8 silly cache add parsed spec { raw: 'protractor',
8 silly cache add   scope: null,
8 silly cache add   name: 'protractor',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: '*',
8 silly cache add   type: 'range' }
9 silly addNamed protractor@*
10 verbose addNamed "*" is a valid semver range for protractor
11 silly addNameRange { name: 'protractor', range: '*', hasData: false }
12 silly mapToRegistry name protractor
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry http://registry.npmjs.org/
15 silly mapToRegistry uri http://registry.npmjs.org/protractor
16 verbose addNameRange registry:http://registry.npmjs.org/protractor not in flight; fetching
17 verbose request uri http://registry.npmjs.org/protractor
18 verbose request no auth needed
19 info attempt registry request try #1 at 3:35:47 PM
20 verbose request id 21b22bf25274febf
21 http request GET http://registry.npmjs.org/protractor
22 http 400 http://registry.npmjs.org/protractor
23 verbose bad json <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
23 verbose bad json <HTML><HEAD><TITLE>Bad Request</TITLE>
23 verbose bad json <META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
23 verbose bad json <BODY><h2>Bad Request - Invalid Hostname</h2>
23 verbose bad json <hr><p>HTTP Error 400. The request hostname is invalid.</p>
23 verbose bad json </BODY></HTML>
24 error registry error parsing json
25 verbose headers { 'content-type': 'text/html; charset=us-ascii',
25 verbose headers   server: 'Microsoft-HTTPAPI/2.0',
25 verbose headers   date: 'Tue, 04 Aug 2015 10:05:50 GMT',
25 verbose headers   connection: 'close',
25 verbose headers   'content-length': '334' }
26 silly get cb [ 400,
26 silly get   { 'content-type': 'text/html; charset=us-ascii',
26 silly get     server: 'Microsoft-HTTPAPI/2.0',
26 silly get     date: 'Tue, 04 Aug 2015 10:05:50 GMT',
26 silly get     connection: 'close',
26 silly get     'content-length': '334' } ]
27 verbose stack SyntaxError: Unexpected token <
27 verbose stack <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
27 verbose stack <HTML><HEAD><TITLE>Bad Request</TITLE>
27 verbose stack <META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
27 verbose stack <BODY><h2>Bad Request - Invalid Hostname</h2>
27 verbose stack <hr><p>HTTP Error 400. The request hostname is invalid.</p>
27 verbose stack </BODY></HTML>
27 verbose stack
27 verbose stack     at Object.parse (native)
27 verbose stack     at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:197:23)
27 verbose stack     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:170:14)
27 verbose stack     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:354:22)
27 verbose stack     at Request.emit (events.js:110:17)
27 verbose stack     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1207:14)
27 verbose stack     at Request.emit (events.js:129:20)
27 verbose stack     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1153:12)
27 verbose stack     at IncomingMessage.emit (events.js:129:20)
27 verbose stack     at _stream_readable.js:908:16
28 verbose cwd D:\PROJECT
29 error Windows_NT 6.1.7601
30 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "protractor"
31 error node v0.12.7
32 error npm  v2.11.3
33 error Unexpected token <
33 error <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
33 error <HTML><HEAD><TITLE>Bad Request</TITLE>
33 error <META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
33 error <BODY><h2>Bad Request - Invalid Hostname</h2>
33 error <hr><p>HTTP Error 400. The request hostname is invalid.</p>
33 error </BODY></HTML>
34 error If you need help, you may report this error at:
34 error     <https://github.com/npm/npm/issues>
35 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
@RaviShankarPandey Hmm, are you behind a proxy/firewall by any chance?

**Comment by RaviShankarPandey** [comment]
@KenanY Yes, I am. Fortunately, I was able to resolve this problem. But now am getting a different error. Please find the attachment.
![protractorinstallationerror](https://cloud.githubusercontent.com/assets/13620404/9079822/ba2992ec-3b6b-11e5-9b3b-7841b90592fa.PNG)

**Comment by RaviShankarPandey** [comment]
With online help, I was able to solve the above problem too. But now am getting gym configure error.
![protractorinstallationerror](https://cloud.githubusercontent.com/assets/13620404/9086461/310dbcf4-3ba2-11e5-9057-0f942dfbe20e.PNG)
I have Windows 7 x86. Please someone help me out here. It's been 3 days and I'm not able to install it.
