### ISSUE TITLE
NPM error - failed to fetch from registry: http://registry.npmjs.org/sass

### ISSUE THREAD

**Issue by crmpicco** [npm/npm#9178]
I deleted my project folder this morning due to some Git issue I was having and now I am unable to do a `npm install`.

Can anyone see why this is failing to fetch sass from the registry?
```
vagrant@localhost /var/www/current (crm-email)$npm install
npm ERR! Linux 3.10.0-123.4.4.el7.x86_64
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.10.30
npm ERR! npm  v2.13.3

npm ERR! failed to fetch from registry: http://registry.npmjs.org/sass
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/releases/20150805093500/npm-debug.log
```
My `package.json`:
```
{
  "name": "CRMPicco",
  "version": "1.0.0",
  "description": "CRMPicco Platform",
  "main": "gulpfile.js",
  "dependencies": {
    "backbone": "^1.1.2",
    "browser-sync": "^2.3.1",
    "browserify": "^10.1.0",
    "browserify-handlebars": "^1.0.0",
    "browserify-shim": "^3.8.6",
    "coffee-script": "^1.9.1",
    "coffeeify": "^1.1.0",
    "gulp": "^3.8.11",
    "gulp-changed": "^1.2.1",
    "gulp-clean": "^0.3.1",
    "gulp-coffee": "^2.3.1",
    "gulp-concat": "^2.5.2",
    "gulp-exec": "^2.1.1",
    "gulp-minify-css": "^1.0.0",
    "gulp-no-media-queries": "0.0.5",
    "gulp-plumber": "^1.0.0",
    "gulp-rename": "^1.2.2",
    "gulp-rev": "^3.0.1",
    "gulp-sass": "^1.3.3",
    "gulp-sourcemaps": "^1.5.2",
    "gulp-uglify": "^1.1.0",
    "gulp-usemin": "^0.3.11",
    "gulp-util": "^3.0.4",
    "handlebars": "^3.0.3",
    "hbsfy": "^2.2.1",
    "jquery": "^2.1.4",
    "jquery-lazyload": "^1.9.5",
    "jquery-ui": "^1.10.5",
    "lodash": "^3.8.0",
    "raf": "^2.0.4",
    "require-dir": "^0.3.0",
    "rework": "^1.0.1",
    "rework-rem2px": "0.0.1",
    "run-sequence": "^1.0.2",
    "slick-carousel": "1.5.5",
    "video.js": "^4.12.10",
    "vinyl-source-stream": "^1.1.0",
    "vinyl-buffer": "^1.0.0"
  },
  "devDependencies": {
    "gulp-kss": "^0.0.2",
    "gulp-rework": "^1.0.3",
    "kss": "^2.0.2",
    "rework-rem-fallback": "^1.0.0",
    "watchify": "^3.2.1"
  },
  "scripts": {
    "kss-node": "kss-node --config=kss-settings.json"
  },
  "repository": {
    "type": "git",
    "url": "git@bitbucket.org:crmpicco/crmpicco.git"
  },
  "author": "",
  "license": "ISC",
  "browserify": {
    "transform": [
      "browserify-shim",
      "hbsfy"
    ]
  },
  "browser": {
    "fixonscroll": "./ui/js/generated/modules/fixonscroll.js",
    "overlaymask": "./ui/js/generated/modules/overlayMask.js",
    "collapse": "./ui/bower_components/bootstrap-sass/assets/javascripts/bootstrap/collapse.js",
    "alert": "./ui/bower_components/bootstrap-sass/assets/javascripts/bootstrap/alert.js",
    "transition": "./ui/bower_components/bootstrap-sass/assets/javascripts/bootstrap/transition.js",
    "tabs": "./ui/bower_components/bootstrap-sass/assets/javascripts/bootstrap/tab.js",
    "jquery-validate": "./ui/bower_components/jquery-validate/build/release.js",
    "formactionPolyfill": "./ui/js/vendor/jquery.form.submission.polyfill.js",
    "fancybox": "./ui/bower_components/fancybox/source/jquery.fancybox.pack.js",
    "checkout_shipping": "./src/CRMPicco/WebBundle/Resources/public/js/checkout/shipping.js",
    "lazyimg": "./node_modules/jquery-lazyload/jquery.lazyload.js",
    "easyzoom": "./ui/bower_components/easyzoom/dist/easyzoom.js"
  },
  "browserify-shim": {
    "fixonscroll": {
      "exports": "fixonscroll",
      "depends": "jquery"
    },
    "jquery-validate": {
      "exports": "jquery-validate",
      "depends": "jquery"
    },
    "checkout_shipping": {
      "exports": "checkout_shipping",
      "depends": "jquery"
    },
    "fancybox": {
      "exports": "fancybox",
      "depends": "jquery"
    },
    "collapse": {
      "exports": "collapse",
      "depends": "jquery"
    },
    "easyzoom": {
      "exports": "easyzoom",
      "depends": "jquery"
    },
    "transition": {
      "exports": "transition",
      "depends": "jquery"
    },
    "tabs" :{
      "exports" : "tabs",
      "depends" : ["jquery", "transition"]
    },
    "lazyimg": {
      "exports": "lazyimg",
      "depends": "jquery"
    }
  }
}
```
Inside `npm-debug.log` there is this sort of stuff:
```
14282 verbose about to build /var/www/releases/20150805093500/node_modules/gulp-kss
14283 verbose unlock done using /home/vagrant/.npm/_locks/gulp-kss-84b665cc5e91af79.lock for /var/www/releases/20150805093500/node_modules/gulp-kss
14284 verbose stack Error: failed to fetch from registry: http://registry.npmjs.org/sass
14284 verbose stack     at /usr/local/lib/node_modules/npm/lib/cache/caching-client.js:163:27
14284 verbose stack     at /usr/local/lib/node_modules/npm/lib/cache/caching-client.js:52:8
14284 verbose stack     at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:17:25)
14284 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:68:16
14284 verbose stack     at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:17:25)
14284 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:255:12)
14284 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:170:14)
14284 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:198:22)
14284 verbose stack     at Request.emit (events.js:98:17)
14284 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1057:14)
14285 verbose cwd /var/www/releases/20150805093500
14286 error Linux 3.10.0-123.4.4.el7.x86_64
14287 error argv "node" "/usr/local/bin/npm" "install"
14288 error node v0.10.30
14289 error npm  v2.13.3
14290 error failed to fetch from registry: http://registry.npmjs.org/sass
14291 error If you need help, you may report this error at:
14291 error     <https://github.com/npm/npm/issues>
14292 verbose exit [ 1, true ]
14293 verbose unbuild node_modules/gulp-kss/node_modules/kss
14294 info preuninstall kss@0.3.7
14295 info uninstall kss@0.3.7
```

**Comment by Yvem** [comment]
Filed the same bug in the wrong place : https://github.com/npm/newww/issues/1127

We are a lot having this problem, not only on this package.

TJ npm packet "sass" https://www.npmjs.com/package/sass is no longer correctly served, it displays a virtual "Error" packet at this url. It is no longer installable via npm.

![sass error](https://cloud.githubusercontent.com/assets/481983/9085812/71c3fe7e-3b80-11e5-8879-f39d11891d44.png)

The package exists, it is listed here :
https://www.npmjs.com/~tjholowaychuk

This is breaking our production deployments.

**Comment by samccone** [comment]
:+1: same thing for me

**Comment by bstst** [comment]
:-1: same here :scream:

**Comment by crmpicco** [comment]
What can be done to work around this? Is it the `gulp-sass` dependency that is causing npm to look for `sass`? It's interesting that it is affecting others as I thought it may have been an issue with my local configuration.

**Comment by Yvem** [comment]
@crmpicco and not only the sass module, as reported by @linclark and @samccone :

Same issue with http://npmjs.com/package/strscan

https://twitter.com/samccone/status/628914963139141632

**Comment by Yvem** [comment]
related issues : https://github.com/npm/npm/issues/9177 https://github.com/npm/npm/issues/9172

**Comment by bstst** [comment]
This seems to be the first related issue https://github.com/npm/npm/issues/9168

**Comment by Yvem** [comment]
Well done @bstst let's +1 this issue

**Comment by crmpicco** [comment]
http://registry.npmjs.org/sass/ is now returning a JSON structure, whereas earlier it was not.
Does anyone know what happened? Someone, somewhere fixed it :)

**Comment by Yvem** [comment]
@crmpicco https://www.npmjs.com/package/sass is still displaying "error"

**Comment by bstst** [comment]
Yeah, that page is displaying an error, but at least the registry request for npm install is working.

**Comment by crmpicco** [comment]
@Yvem Yes. Thankfully `npm install` is now working. I hope it's fixed for everyone else too.

**Comment by Yvem** [comment]
pb apparently solved https://github.com/npm/npm/issues/9168#issuecomment-128034802
