### ISSUE TITLE
cache.js error

### ISSUE THREAD

**Issue by Alexis01** [npm/npm#9183]
I have this error when i execute > npm install.

```
TypeError: Cannot read property 'latest' of undefined
npm ERR!     at next (/usr/share/npm/lib/cache.js:687:35)
npm ERR!     at /usr/share/npm/lib/cache.js:675:5
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/share/npm/node_modules/read-installed/node_modules/graceful-fs/polyfills.js:133:7
npm ERR!     at /usr/share/npm/node_modules/read-package-json/node_modules/graceful-fs/polyfills.js:133:7
npm ERR!     at /usr/share/npm/node_modules/npm-registry-client/node_modules/graceful-fs/polyfills.js:133:7
npm ERR!     at /usr/share/npm/node_modules/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
```

How i could resolve it.

**Comment by KenanY** [comment]
@Alexis01 Could you upload the full `npm-debug.log` as a [gist](https://gist.github.com/)?

**Comment by othiym23** [comment]
Also, what version of npm are you running? This may have been fixed in another version of npm.

**Comment by Alexis01** [comment]
Thanks othiym23, i upgrade my npm and then it runs.

**Comment by othiym23** [comment]
Closing as resolved! You're welcome!

**Comment by ehsalazar** [comment]
Good to hear. I'll close this for now as we’re trying to clean up some solved issues. We’ll be happy to reopen if necessary.
