### ISSUE TITLE
I can't install coloured-log, it worked the last 9 months.

### ISSUE THREAD

**Issue by DimitriBeman** [npm/npm#9184]
I can't install coloured-log, it worked the last 9 months.

```
108 verbose afterAdd C:\Users\Dimitri\AppData\Roaming\npm-cache\log\1.4.0\package\package.json not in flight; writing
109 verbose afterAdd C:\Users\Dimitri\AppData\Roaming\npm-cache\log\1.4.0\package\package.json written
110 verbose about to build c:\Users\Dimitri\Desktop\node_modules\coloured-log
111 verbose unlock done using C:\Users\Dimitri\AppData\Roaming\npm-cache\_locks\coloured-log-267f973a1acebe15.lock for c:\Users\Dimitri\Desktop\node_modules\coloured-log
112 verbose stack Error: failed to fetch from registry: https://registry.npmjs.org/coloured
112 verbose stack     at c:\Program Files\nodejs\node_modules\npm\lib\cache\caching-client.js:163:27
112 verbose stack     at c:\Program Files\nodejs\node_modules\npm\lib\cache\caching-client.js:52:8
112 verbose stack     at f (c:\Program Files\nodejs\node_modules\npm\node_modules\once\once.js:17:25)
112 verbose stack     at c:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:68:16
112 verbose stack     at f (c:\Program Files\nodejs\node_modules\npm\node_modules\once\once.js:17:25)
112 verbose stack     at CachingRegistryClient.<anonymous> (c:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:255:12)
112 verbose stack     at Request._callback (c:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:170:14)
112 verbose stack     at Request.self.callback (c:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:344:22)
112 verbose stack     at Request.emit (events.js:110:17)
112 verbose stack     at Request.<anonymous> (c:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1239:14)
113 verbose cwd c:\Users\Dimitri\Desktop
114 error Windows_NT 6.3.9600
115 error argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "coloured-log"
116 error node v0.12.2
117 error npm  v2.7.4
118 error failed to fetch from registry: https://registry.npmjs.org/coloured
![screenshot_1](https://cloud.githubusercontent.com/assets/1154049/9086981/506cacb6-3b5e-11e5-9fdb-533c8b54e0d4.png)

119 error If you need help, you may report this error at:
119 error     <https://github.com/npm/npm/issues>
120 verbose exit [ 1, true ]
121 verbose unbuild node_modules\coloured-log
122 info preuninstall coloured-log@0.9.7
123 info uninstall coloured-log@0.9.7
124 verbose unbuild rmStuff coloured-log@0.9.7 from c:\Users\Dimitri\Desktop\node_modules
125 info postuninstall coloured-log@0.9.7
```

**Comment by bstst** [comment]
Looks like it's the same issue as https://github.com/npm/npm/issues/9178

**Comment by othiym23** [comment]
As with #9178, we made what we believed to be a small change to the registry that unfortunately broke a small number of packages for about a 12-hour window yesterday. I believe that if you try this install again now, this will have been fixed. Sorry for the trouble!
