### ISSUE TITLE
error parsing json while trying to install cordova/ionic or any other stuff

### ISSUE THREAD

**Issue by SuryaJD** [npm/npm#9185]
![screenshot 89](https://cloud.githubusercontent.com/assets/13571823/9088329/201576b6-3bad-11e5-9982-cdc05212a2b3.png)

here is my npm-debug.log

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'cordovo',
1 verbose cli   'ionic' ]
2 info using npm@2.11.3
3 info using node@v0.12.7
4 verbose install initial load of C:\Users\suraj jadhav\AppData\Roaming\npm\package.json
5 verbose readDependencies loading dependencies from C:\Users\suraj jadhav\AppData\Roaming\npm\package.json
6 silly cache add args [ 'cordovo', null ]
7 verbose cache add spec cordovo
8 silly cache add args [ 'ionic', null ]
9 verbose cache add spec ionic
10 silly cache add parsed spec { raw: 'cordovo',
10 silly cache add   scope: null,
10 silly cache add   name: 'cordovo',
10 silly cache add   rawSpec: '',
10 silly cache add   spec: '*',
10 silly cache add   type: 'range' }
11 silly addNamed cordovo@*
12 verbose addNamed "*" is a valid semver range for cordovo
13 silly addNameRange { name: 'cordovo', range: '*', hasData: false }
14 silly mapToRegistry name cordovo
15 silly mapToRegistry using default registry
16 silly mapToRegistry registry http://registry.npmjs.org/ionic
17 silly mapToRegistry uri http://registry.npmjs.org/ionic/cordovo
18 verbose addNameRange registry:http://registry.npmjs.org/ionic/cordovo not in flight; fetching
19 silly cache add parsed spec { raw: 'ionic',
19 silly cache add   scope: null,
19 silly cache add   name: 'ionic',
19 silly cache add   rawSpec: '',
19 silly cache add   spec: '*',
19 silly cache add   type: 'range' }
20 silly addNamed ionic@*
21 verbose addNamed "*" is a valid semver range for ionic
22 silly addNameRange { name: 'ionic', range: '*', hasData: false }
23 silly mapToRegistry name ionic
24 silly mapToRegistry using default registry
25 silly mapToRegistry registry http://registry.npmjs.org/ionic
26 silly mapToRegistry uri http://registry.npmjs.org/ionic/ionic
27 verbose addNameRange registry:http://registry.npmjs.org/ionic/ionic not in flight; fetching
28 verbose request uri http://registry.npmjs.org/ionic/cordovo
29 verbose request no auth needed
30 info attempt registry request try #1 at 7:59:48 PM
31 verbose request id caab6c56f8b45d45
32 http request GET http://registry.npmjs.org/ionic/cordovo
33 verbose request uri http://registry.npmjs.org/ionic/ionic
34 verbose request no auth needed
35 info attempt registry request try #1 at 7:59:48 PM
36 http request GET http://registry.npmjs.org/ionic/ionic
37 http 404 http://registry.npmjs.org/ionic/cordovo
38 verbose bad json <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
38 verbose bad json <html xmlns="http://www.w3.org/1999/xhtml">
38 verbose bad json <head>
38 verbose bad json <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
38 verbose bad json <title>404 - File or directory not found.</title>
38 verbose bad json <style type="text/css">
38 verbose bad json <!--
38 verbose bad json body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
38 verbose bad json fieldset{padding:0 15px 10px 15px;}
38 verbose bad json h1{font-size:2.4em;margin:0;color:#FFF;}
38 verbose bad json h2{font-size:1.7em;margin:0;color:#CC0000;}
38 verbose bad json h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;}
38 verbose bad json #header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
38 verbose bad json background-color:#555555;}
38 verbose bad json #content{margin:0 0 0 2%;position:relative;}
38 verbose bad json .content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
38 verbose bad json -->
38 verbose bad json </style>
38 verbose bad json </head>
38 verbose bad json <body>
38 verbose bad json <div id="header"><h1>Server Error</h1></div>
38 verbose bad json <div id="content">
38 verbose bad json  <div class="content-container"><fieldset>
38 verbose bad json   <h2>404 - File or directory not found.</h2>
38 verbose bad json   <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
38 verbose bad json  </fieldset></div>
38 verbose bad json </div>
38 verbose bad json </body>
38 verbose bad json </html>
39 error registry error parsing json
40 verbose headers { 'content-type': 'text/html',
40 verbose headers   server: 'Microsoft-IIS/8.5',
40 verbose headers   'x-powered-by': 'ASP.NET',
40 verbose headers   date: 'Wed, 05 Aug 2015 14:29:34 GMT',
40 verbose headers   'content-length': '1245' }
41 silly get cb [ 404,
41 silly get   { 'content-type': 'text/html',
41 silly get     server: 'Microsoft-IIS/8.5',
41 silly get     'x-powered-by': 'ASP.NET',
41 silly get     date: 'Wed, 05 Aug 2015 14:29:34 GMT',
41 silly get     'content-length': '1245' } ]
42 http 404 http://registry.npmjs.org/ionic/ionic
43 verbose bad json <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
43 verbose bad json <html xmlns="http://www.w3.org/1999/xhtml">
43 verbose bad json <head>
43 verbose bad json <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
43 verbose bad json <title>404 - File or directory not found.</title>
43 verbose bad json <style type="text/css">
43 verbose bad json <!--
43 verbose bad json body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
43 verbose bad json fieldset{padding:0 15px 10px 15px;}
43 verbose bad json h1{font-size:2.4em;margin:0;color:#FFF;}
43 verbose bad json h2{font-size:1.7em;margin:0;color:#CC0000;}
43 verbose bad json h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;}
43 verbose bad json #header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
43 verbose bad json background-color:#555555;}
43 verbose bad json #content{margin:0 0 0 2%;position:relative;}
43 verbose bad json .content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
43 verbose bad json -->
43 verbose bad json </style>
43 verbose bad json </head>
43 verbose bad json <body>
43 verbose bad json <div id="header"><h1>Server Error</h1></div>
43 verbose bad json <div id="content">
43 verbose bad json  <div class="content-container"><fieldset>
43 verbose bad json   <h2>404 - File or directory not found.</h2>
43 verbose bad json   <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
43 verbose bad json  </fieldset></div>
43 verbose bad json </div>
43 verbose bad json </body>
43 verbose bad json </html>
44 error registry error parsing json
45 verbose headers { 'content-type': 'text/html',
45 verbose headers   server: 'Microsoft-IIS/8.5',
45 verbose headers   'x-powered-by': 'ASP.NET',
45 verbose headers   date: 'Wed, 05 Aug 2015 14:29:34 GMT',
45 verbose headers   'content-length': '1245' }
46 silly get cb [ 404,
46 silly get   { 'content-type': 'text/html',
46 silly get     server: 'Microsoft-IIS/8.5',
46 silly get     'x-powered-by': 'ASP.NET',
46 silly get     date: 'Wed, 05 Aug 2015 14:29:34 GMT',
46 silly get     'content-length': '1245' } ]
47 verbose stack SyntaxError: Unexpected token <
47 verbose stack <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
47 verbose stack <html xmlns="http://www.w3.org/1999/xhtml">
47 verbose stack <head>
47 verbose stack <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
47 verbose stack <title>404 - File or directory not found.</title>
47 verbose stack <style type="text/css">
47 verbose stack <!--
47 verbose stack body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
47 verbose stack fieldset{padding:0 15px 10px 15px;}
47 verbose stack h1{font-size:2.4em;margin:0;color:#FFF;}
47 verbose stack h2{font-size:1.7em;margin:0;color:#CC0000;}
47 verbose stack h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;}
47 verbose stack #header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
47 verbose stack background-color:#555555;}
47 verbose stack #content{margin:0 0 0 2%;position:relative;}
47 verbose stack .content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
47 verbose stack -->
47 verbose stack </style>
47 verbose stack </head>
47 verbose stack <body>
47 verbose stack <div id="header"><h1>Server Error</h1></div>
47 verbose stack <div id="content">
47 verbose stack  <div class="content-container"><fieldset>
47 verbose stack   <h2>404 - File or directory not found.</h2>
47 verbose stack   <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
47 verbose stack  </fieldset></div>
47 verbose stack </div>
47 verbose stack </body>
47 verbose stack </html>
47 verbose stack
47 verbose stack     at Object.parse (native)
47 verbose stack     at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:197:23)
47 verbose stack     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:170:14)
47 verbose stack     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:354:22)
47 verbose stack     at Request.emit (events.js:110:17)
47 verbose stack     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1207:14)
47 verbose stack     at Request.emit (events.js:129:20)
47 verbose stack     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1153:12)
47 verbose stack     at IncomingMessage.emit (events.js:129:20)
47 verbose stack     at _stream_readable.js:908:16
48 verbose cwd C:\Users\suraj jadhav
49 error Windows_NT 6.3.9600
50 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordovo" "ionic"
51 error node v0.12.7
52 error npm  v2.11.3
53 error Unexpected token <
53 error <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
53 error <html xmlns="http://www.w3.org/1999/xhtml">
53 error <head>
53 error <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
53 error <title>404 - File or directory not found.</title>
53 error <style type="text/css">
53 error <!--
53 error body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
53 error fieldset{padding:0 15px 10px 15px;}
53 error h1{font-size:2.4em;margin:0;color:#FFF;}
53 error h2{font-size:1.7em;margin:0;color:#CC0000;}
53 error h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;}
53 error #header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
53 error background-color:#555555;}
53 error #content{margin:0 0 0 2%;position:relative;}
53 error .content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
53 error -->
53 error </style>
53 error </head>
53 error <body>
53 error <div id="header"><h1>Server Error</h1></div>
53 error <div id="content">
53 error  <div class="content-container"><fieldset>
53 error   <h2>404 - File or directory not found.</h2>
53 error   <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
53 error  </fieldset></div>
53 error </div>
53 error </body>
53 error </html>
54 error If you need help, you may report this error at:
54 error     <https://github.com/npm/npm/issues>
55 verbose exit [ 1, true ]
```

 sry for my english and stupidness (I am new to development github and every other technologies)

**Comment by bstst** [comment]
Your error description seems to be quite unambiguous, but this looks to be related to this: https://github.com/npm/npm/issues/9168

**Comment by KenanY** [comment]
@sssuryaJD Are you behind a proxy/firewall by any chance? That does not look like npm's 404 page.

Also in your text log you are installing "cordovo" instead of "cordova".

I am also very curious as to why requests are being made to URLs like `http://registry.npmjs.org/ionic/ionic` and `http://registry.npmjs.org/ionic/cordovo`. Can you let me know what this command returns?:

``` sh
$ npm config get registry
```

**Comment by sssuryaJD** [comment]
well I am newbie to this. I am first year comp sci student. I don't have any background regarding this.
I saw some youtube videos last week and tried to copy them. and all solutions i tried are suggested by some good folks like you on quora, fb group and other forum and Q and A sites.
