### ISSUE TITLE
I get an error for self signed certifcate when trying to use npm install jquery

### ISSUE THREAD

**Issue by bharad78** [npm/npm#9195]
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'jquery' ]
2 info using npm@2.11.3
3 info using node@v0.12.7
4 verbose install initial load of U:\RaviBharadwaj\APOD\package.json
5 warn package.json apod@1.0.0 No repository field.
6 warn package.json apod@1.0.0 No README data
7 verbose readDependencies loading dependencies from U:\RaviBharadwaj\APOD\package.json
8 silly cache add args [ 'jquery', null ]
9 verbose cache add spec jquery
10 silly cache add parsed spec { raw: 'jquery',
10 silly cache add   scope: null,
10 silly cache add   name: 'jquery',
10 silly cache add   rawSpec: '',
10 silly cache add   spec: '*',
10 silly cache add   type: 'range' }
11 silly addNamed jquery@*
12 verbose addNamed "*" is a valid semver range for jquery
13 silly addNameRange { name: 'jquery', range: '*', hasData: false }
14 silly mapToRegistry name jquery
15 silly mapToRegistry using default registry
16 silly mapToRegistry registry https://registry.npmjs.org/
17 silly mapToRegistry uri https://registry.npmjs.org/jquery
18 verbose addNameRange registry:https://registry.npmjs.org/jquery not in flight; fetching
19 verbose request uri https://registry.npmjs.org/jquery
20 verbose request no auth needed
21 info attempt registry request try #1 at 3:00:00 PM
22 verbose request id e7309569f4b73806
23 http request GET https://registry.npmjs.org/jquery
24 info retry will retry, error on last attempt: Error: self signed certificate
25 info attempt registry request try #2 at 3:00:10 PM
26 http request GET https://registry.npmjs.org/jquery
27 info retry will retry, error on last attempt: Error: self signed certificate
28 info attempt registry request try #3 at 3:01:10 PM
29 http request GET https://registry.npmjs.org/jquery
30 verbose stack Error: self signed certificate
30 verbose stack     at Error (native)
30 verbose stack     at TLSSocket.<anonymous> (_tls_wrap.js:929:36)
30 verbose stack     at TLSSocket.emit (events.js:104:17)
30 verbose stack     at TLSSocket._finishInit (_tls_wrap.js:460:8)
31 verbose cwd U:\RaviBharadwaj\APOD
32 error Windows_NT 6.1.7601
33 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "jquery"
34 error node v0.12.7
35 error npm  v2.11.3
36 error code DEPTH_ZERO_SELF_SIGNED_CERT
37 error self signed certificate
38 error If you need help, you may report this error at:
38 error     <https://github.com/npm/npm/issues>
39 verbose exit [ 1, true ]
```

**Comment by sinkingshriek** [comment]
@bharad78 This is more likely a proxy issue. Are you behind a corporate firewall?

**Comment by JerinJ** [comment]
Even i faced same issue while doing any `npm install -g XXX` command, it was resolved by `npm config set strict-ssl false`
