### ISSUE TITLE
getting error in pnm install and bundle exec rake canvas:compile_assets

### ISSUE THREAD

**Issue by sewakram** [npm/npm#9221]
please check the log file
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'compile-sass' ]
2 info using npm@2.11.3
3 info using node@v0.12.7
4 verbose node symlink /usr/bin/node
5 verbose run-script [ 'precompile-sass', 'compile-sass', 'postcompile-sass' ]
6 info precompile-sass canvas-lms@0.0.0
7 info compile-sass canvas-lms@0.0.0
8 verbose unsafe-perm in lifecycle true
9 info canvas-lms@0.0.0 Failed to exec compile-sass script
10 verbose stack Error: canvas-lms@0.0.0 compile-sass: `node script/compile-sass.js`
10 verbose stack Exit status 1
10 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
10 verbose stack     at EventEmitter.emit (events.js:110:17)
10 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
10 verbose stack     at ChildProcess.emit (events.js:110:17)
10 verbose stack     at maybeClose (child_process.js:1015:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
11 verbose pkgid canvas-lms@0.0.0
12 verbose cwd /var/canvas
13 error Linux 3.16.0-30-generic
14 error argv "/usr/bin/node" "/usr/bin/npm" "run" "compile-sass"
15 error node v0.12.7
16 error npm  v2.11.3
17 error code ELIFECYCLE
18 error canvas-lms@0.0.0 compile-sass: `node script/compile-sass.js`
18 error Exit status 1
19 error Failed at the canvas-lms@0.0.0 compile-sass script 'node script/compile-sass.js'.
19 error This is most likely a problem with the canvas-lms package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     node script/compile-sass.js
19 error You can get their info via:
19 error     npm owner ls canvas-lms
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
@sewakram Looks like `node script/compile-sass.js` is exiting with an error code. Probably not a `npm` issue... I can't really tell just from this log. I would check to ensure that `script/compile-sass.js` exists and debug through it if it does.

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some issues. If this is still a problem, can you please reply and let us know? We’ll be happy to reopen if necessary.
