### ISSUE TITLE
Deal with `call stack` issues

### ISSUE THREAD

**Issue by iarna** [npm/npm#9224]
This is related to the https://github.com/npm/npm/tree/iarna/safe branch, which instruments all of our loops with limiters to give us strack traces earlier. It also logs all `fs` calls.

Work with @isaacs has identified one source of these:

https://github.com/npm/npm/issues/9223 Symlink cycles in dependencies blows our stack or otherwise causes infinite loops

**Comment by sullenor** [comment]
Hi, I managed to reproduce my issue. Here is a simple `package.json` to reproduce it stably:
```json
{
  "name": "callstack",
  "version": "1.0.0",
  "dependencies": {
    "karma": "0.12.31",
    "karma-coverage": "0.2.4"
  }
}
```

My environment:
```bash
$ npm -v
3.3.3
$ node -v
v0.12.7
```

Hope that helps.

**Comment by iarna** [comment]
@sullenor That's fantastic! This is on just running `npm install` in a module w/ that `package.json`?

**Comment by sullenor** [comment]
@iarna Yes, simply put it somewhere and run `npm install`.
Unfortunately, I can reproduce it only on my laptop and I can't reproduce it on another computer :(
I don't know what is the difference, but I use nvm on my laptop and don't use it on another machine.

**Comment by mikeputnam** [comment]
With npm 3.3.3 we are seeing the below error:

```
149529 verbose type stack_overflow
149530 verbose cwd /var/www
149531 error Linux 3.13.0-63-generic
149532 error argv "node" "/usr/bin/npm" "install" "--dd" "--no-bin-links"
149533 error node v0.10.40
149534 error npm  v3.3.3
149535 error Maximum call stack size exceeded
149536 error If you need help, you may report this error at:
149536 error     <https://github.com/npm/npm/issues>
149537 verbose exit [ 1, true ]
```

Where the same command run on npm 2.14.3 does not error.

**Comment by MethodGrab** [comment]
I also get this error when trying to publish. I'm also using nvm (0.25.4) and it's a public scoped package that I'm trying to publish.
Publishing works ok with Node v0.12.7 / npm v2.13.0.

```sh
npm ERR! Maximum call stack size exceeded
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Darwin 14.4.0
npm ERR! argv "/Users/me/.nvm/versions/node/v4.1.1/bin/node" "/Users/me/.nvm/versions/node/v4.1.1/bin/npm" "publish"
npm ERR! node v4.1.1
npm ERR! npm  v3.3.3
```

**Comment by christianhuening** [comment]
Have the same issue with Node v0.10.40 and npm 3.3.3 inside a docker container:
```
npm ERR! Linux 4.0.9-boot2docker
npm ERR! argv "node" "/usr/bin/npm" "install" "--no-bin-links"
npm ERR! node v0.10.40
npm ERR! npm  v3.3.3
npm ERR! Maximum call stack size exceeded
```

**Comment by christianhuening** [comment]
@sullenor : Can't reproduce with your package.json though :(

**Comment by callumlocke** [comment]
I just had this error too.

- using npm 3.3.5 and node 4.0.0.
- I was trying to publish a new, very simple module. (I have previously published with npm 3; not sure what went wrong this time.)
- This is the module: https://github.com/exhibitjs/eslint-config-exhibit

I switched down to Node 0.12 and npm 2.14.2, ran `npm publish` again, and it worked fine.

**Comment by Andrew1503** [comment]
Started getting this error today in a centos7 box running with vagrant

new directory `/var/www/test` with just one file;

package.json:
```
{
  "private": true,
  "devDependencies": {
     "laravel-elixir": "3.2.6"
  }
}
```

```
npm ERR! Linux 3.10.0-123.4.2.el7.x86_64
npm ERR! argv "node" "/bin/npm" "install" "--no-bin-links"
npm ERR! node v0.10.33
npm ERR! npm  v3.3.5

npm ERR! Maximum call stack size exceeded
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Linux 3.10.0-123.4.2.el7.x86_64
npm ERR! argv "node" "/bin/npm" "install" "--no-bin-links"
npm ERR! node v0.10.33
npm ERR! npm  v3.3.5
npm ERR! path npm-debug.log.28b977c4b91c15919f65166dff3420bb
npm ERR! code ETXTBSY
npm ERR! errno 62
```

npm-debug.log
```
58284 silly build shelljs
58285 silly build shellwords
58286 silly build sigmund
58287 silly build minimatch
58288 verbose type stack_overflow
58289 verbose cwd /var/www/test
58290 error Linux 3.10.0-123.4.2.el7.x86_64
58291 error argv "node" "/bin/npm" "install" "--no-bin-links"
58292 error node v0.10.33
58293 error npm  v3.3.5
58294 error Maximum call stack size exceeded
58295 error If you need help, you may report this error at:
58295 error     <https://github.com/npm/npm/issues>
58296 verbose exit [ 1, true ]
```

**Comment by patrickloop** [comment]
Running into this issue on Homestead for a Laravel project.

**System**
OS X El Cap 10.11
VirtualBox 5.0.4
Vagrant 1.7.4

**Homestead**
Ubuntu 14.04.3 (Linux 3.19.0-25-generic)
node v4.1.1
npm v3.3.5

**package.json**
```
{
  "private": true,
  "devDependencies": {
    "gulp": "^3.9.0",
    "laravel-elixir": "^3.3.1"
  }
}
```

When I try
```
npm install
```
I get 
```
npm ERR! Linux 3.19.0-25-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.1.1
npm ERR! npm  v3.3.5
npm ERR! path ../acorn/bin/acorn
npm ERR! code EPROTO
npm ERR! errno -71
npm ERR! syscall symlink

npm ERR! EPROTO: protocol error, symlink '../acorn/bin/acorn' -> '/home/vagrant/Code/<PROJECT>/node_modules/.bin/acorn'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/Code/<PROJECT>/npm-debug.log
```

Then I try
```
npm install --no-bin-links
```

And I get 
```
npm WARN install Couldn't install optional dependency: Unsupported
npm ERR! Linux 3.19.0-25-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "--no-bin-links"
npm ERR! node v4.1.1
npm ERR! npm  v3.3.5

npm ERR! Maximum call stack size exceeded
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/Code/<PROJECT>/npm-debug.log
```

npm-debub.log is huge but it ends like this
```
84308 verbose stack RangeError: Maximum call stack size exceeded
84308 verbose stack     at Tracker.completed (/usr/lib/node_modules/npm/node_modules/are-we-there-yet/index.js:87:40)
84308 verbose stack     at /usr/lib/node_modules/npm/node_modules/are-we-there-yet/index.js:27:47
84308 verbose stack     at Array.forEach (native)
84308 verbose stack     at TrackerGroup.completed (/usr/lib/node_modules/npm/node_modules/are-we-there-yet/index.js:26:19)
84308 verbose stack     at /usr/lib/node_modules/npm/node_modules/are-we-there-yet/index.js:27:47
84308 verbose stack     at Array.forEach (native)
84308 verbose stack     at TrackerGroup.completed (/usr/lib/node_modules/npm/node_modules/are-we-there-yet/index.js:26:19)
84308 verbose stack     at /usr/lib/node_modules/npm/node_modules/are-we-there-yet/index.js:27:47
84308 verbose stack     at Array.forEach (native)
84308 verbose stack     at TrackerGroup.completed (/usr/lib/node_modules/npm/node_modules/are-we-there-yet/index.js:26:19)
84309 verbose cwd /home/vagrant/Code/<PROJECT>
84310 error Linux 3.19.0-25-generic
84311 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "--no-bin-links"
84312 error node v4.1.1
84313 error npm  v3.3.5
84314 error Maximum call stack size exceeded
84315 error If you need help, you may report this error at:
84315 error     <https://github.com/npm/npm/issues>
84316 verbose exit [ 1, true ]
```

**Comment by sullenor** [comment]
@christianhuening sad

**Comment by spescina** [comment]
As @sullenor I can reproduce the issue every time I run `npm install --no-bin-links` with this package.json and not with his own snippet.
```
{
  "name": "callstack",
  "version": "1.0.0",
  "dependencies": {
    "brfs": "^1.4.1",
    "browser-sync": "^2.9.8",
    "browserify": "^11.2.0",
    "browserify-istanbul": "^0.2.1",
    "browserify-ngannotate": "^1.0.1"
  }
}
```

I tried to install each package one at a time and everything was fine.

When omitting the `--no-bin-links` flag I have a protocol error for the symlink on this file `../acorn/bin/acorn`

node 4.1.1
npm 3.3.5

I'm on a window 8.1 host with an ubuntu 14.04 vagrant virtual machine.

**Comment by patrickloop** [comment]
I tried `npm install gulp --no-bin-links` and it worked fine. Tried the same with `laravel-elixir` and got the maximum call stack issue. Took a hint from @spescina and installed each of the packages on which `laravel-elixir` depends, but then I was getting `module not found` exceptions (because I was manually creating the dependency tree?). 

Anyway, I ended up destroying my homestead box (to get rid of all instances of node/npm/node_modules), rebuilt it and reverted back to npm@2.14.7 (stayed with node@4.1.1).

Was able to successfully run `npm install --no-bin-links` but got a different warning: `npm WARN optional dep failed, continuing fsevents@1.0.1`. 

Looks like it installs correctly and the packages (gulp, laravel-elixir) are usable.

**Comment by azat-co** [comment]
I got the same Maximum call stack size exceeded. package.json is trivial:

```
{
  "name": "you-dont-know-node",
  "version": "1.1.1",
  "description": "You Don't Know Node.js",
  "main": "cluster.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": "https://github.com/azat-co/you-dont-know-node",
  "author": "Azat Mardan",
  "license": "MIT",
  "dependencies": {
    "express": "^4.13.3"
  }
}
```
npm v3.3.3
node 0.12.7

**Comment by fastest963** [comment]
I posted in https://github.com/npm/npm/issues/9953 but I can reproduce the issue `Maximum call stack size exceeded` when installing with `--no-bin-links` but if I just do `npm install` without that option it works fine.

**Comment by markushausammann** [comment]
Having the same problem on a vagrant machine. Every install with the `--no-bin-links` flag leads to the maximum call stack size exceeded error.

**Comment by dhampik** [comment]
I have the same Max call stack exceeded issue in vagrant (centos guest, windows host) with `npm install --no-bin-links`
~~~
npm 3.3.12
node 4.2.2
~~~

It looks like only reverting to `2.x` helps. :disappointed: 

The following deps are in package.json:
~~~
  "devDependencies": {
    "angular": "1.4.7",
    "angular-animate": "1.4.7",
    "angular-messages": "1.4.7",
    "angular-mocks": "1.4.7",
    "angular-nvd3": "1.0.2",
    "angular-smart-table": "2.1.4",
    "angular-tree-control": "0.2.21",
    "angular-ui-bootstrap": "0.14.3",
    "angular-ui-router": "0.2.15",
    "angular-ui-sortable": "0.13.4",
    "babel-core": "5.8.25",
    "babel-loader": "5.3.2",
    "bootstrap-sass": "3.3.5",
    "bootstrap-sass-loader": "1.0.9",
    "bower": "1.5.3",
    "css-loader": "0.19.0",
    "d3": "3.5.6",
    "expose-loader": "0.7.0",
    "extract-text-webpack-plugin": "0.8.2",
    "file-loader": "0.8.4",
    "font-awesome": "4.4.0",
    "html-loader": "0.3.0",
    "html-webpack-plugin": "1.6.2",
    "isparta-instrumenter-loader": "0.2.1",
    "jasmine-core": "2.3.4",
    "jquery": "2.1.4",
    "jquery-ui": "1.10.5",
    "karma": "0.13.11",
    "karma-coverage": "0.5.2",
    "karma-jasmine": "0.3.6",
    "karma-phantomjs-launcher": "0.2.1",
    "karma-sourcemap-loader": "0.3.6",
    "karma-spec-reporter": "0.0.20",
    "karma-webpack": "1.7.0",
    "node-sass": "3.4.0",
    "null-loader": "0.1.1",
    "nvd3": "1.8.1",
    "phantomjs": "1.9.18",
    "pnotify": "git://github.com/sciactive/pnotify.git#2.1.0",
    "raw-loader": "0.5.1",
    "sass-loader": "3.1.1",
    "style-loader": "0.12.4",
    "url-loader": "0.5.6",
    "webpack": "1.12.2",
    "webpack-dev-server": "1.12.0"
  }
~~~

**Comment by withinboredom** [comment]
Looks like running `npm cache clear` before `npm install` seems to resolve it in 3.3.12 I haven't been able to reproduce it when doing this. Does this work for anyone else?

**Comment by markushausammann** [comment]
Any news on this. `npm install` still leads to errors about symlinks and `npm install --no-bin-links` leads to max call stack errors.

**Comment by jaypozo** [comment]
Running node v4.2.2 with quite an extensive package.json. Tried `npm cache clear` and then `npm install --no-bin-links` and I get "Maximum call stack size exceeded". 

Windows 10 host with Ubuntu 14.04 Virtualbox guest.

**Comment by spescina** [comment]
Could it be something concerning a low vm memory amount?

**Comment by jaypozo** [comment]
I don't think so - the vm has 12GB allocated on a host with 32gb total.

**Comment by sstawecki** [comment]
I have the same problem as @patrickloop , I'm running homestead on OS X and all my "npm installs" were in homestead box.
I read in other places --no-bin-links is only for windows users (related to follow linux symlinks) and also isn't necessary run npm install with sudo.
So I tried to do the same outside homestead box and it worked, but I'm not satisfied with the solution.
My steps were:
```
rm -Rf node_modules/*
npm cache clean
npm install
```
(I think isn't necessary npm cache clean but i'm not an expert doing this)

OS X (where I've executed the commands and it worked)
node v0.10.25
npm v1.3.24

Vagrant homestead:
node v5.0.0
npm v3.3.6

package.json:

```
{
  "devDependencies": {
    "gulp": "^3.8.8",
    "laravel-elixir": "*"
  }
}
```
I'll try to do it again upgrading node and npm on OS X to figure out if it also works.
PD: Sorry for my poor english.

**Comment by spazard1** [comment]
I had this problem today with npm install --no-bin-links on a OSX machine running a vagrant vm. I've had to use --no-bin-links in the past since the installs were failing to create symlinks with my host machine. Not sure if it is still needed or not.


[package.json.txt](https://github.com/npm/npm/files/80480/package.json.txt)

**Comment by ShahidH** [comment]
I managed to fix it by downgrading to npm v2

# npm install -g npm@latest-2
# npm install --no-bin-links

**Comment by agilgur5** [comment]
Also running an Ubuntu (Vagrant) environment on a Windows host with `--no-bin-links` and something interesting I've found with this is that when I manually install a package (e.g. `npm install --save-dev standard`), it works fine with no call stack bug, but when I install it as part of my `package.json`, I get a call stack bug.

This made it really confusing when another developer couldn't use the environment I provided as `npm install` on each individual package (what I did while I was creating the environment) and `npm install` on a `package.json` had two different results.

**Comment by web-jenezis** [comment]
Hi guys,
I got the same error with node v5.0.0 and npm v3.3.6

Any updates on the issue???

```
npm ERR! Linux 3.13.0-55-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--no-bin-links"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6

npm ERR! Maximum call stack size exceeded
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/project_name/npm-debug.log
```

**Comment by sstawecki** [comment]
Hi @web-jenezis  I "fixed" it by running npm install from the host machine, in my case, OS X El capitan 10.11.x So, seems to be an issue regarding to the virtual machine memory or something like that.

**Comment by JESii** [comment]
Here's a failure; adding npm-debug.log. No package.json as I just want to install Appium. here's the command line output.

[npm-debug.txt](https://github.com/npm/npm/files/180082/npm-debug.txt)
```
yc98js1@a4660809:[dev->]~/dev$ npm install wd
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/Cellar/node/5.9.0/bin/node" "/usr/local/bin/npm" "install" "wd"
npm ERR! node v5.9.0
npm ERR! npm  v3.7.3

npm ERR! Maximum call stack size exceeded
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/yc98js1/dev/npm-debug.log
```

**Comment by JSheils** [comment]
Following sstawecki 's suggestion, I also resolved the problem for now by running ipm install on the host machine in the shared folder.
I am running an Ubuntu VM on WIndows 8.1

**Comment by adiachenko** [comment]
Checked status of the issue. Running `npm install --no-bin-links` when trying to install laravel-elixir still leads to `Maximum call stack size exceeded`. **It has nothing to do with VM**. I even halted my Vagrant machine specifically to avoid any confusion with shared folders. I've ended up abandoning laravel-elixir in favor of webpack but it's not like I enjoy doing a few hours of extra work just because `npm install` is a mess. I hope this issue will be resolved.

**Comment by kwiniarski** [comment]
2 months and it will be one year as this is not resolved. I'm also experiencing `Maximum call stack size exceeded` when running `npm install` with `--no-bin-links` flag (npm v3.9.3, node v6.2.1). This is run in Vagrant VM (Ubuntu on Windows 10 host - which seems to be quite common pattern), however it is not related with VM itself like @adiachenko mentioned. `--no-bin-links` is required because otherwise npm fails on creating symlinks because project is inside shared folder. So generally this is checkmate situation. Only thing you can do is to use some workarounds like `sympm` or downgrade to npm 2.x which seems to be still more reliable then 3.x.

**Comment by TabCrazy** [comment]
I'm all done. Running npm install for you to install the required dependencies. If this fails, try running the command yourself.


npm WARN deprecated isparta-instrumenter-loader@1.0.1: isparta-instrumenter-loader is deprecated. Please use isparta-loader instead
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\TabTang\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.3

npm ERR! shasum check failed for C:\Users\TabTang\AppData\Local\Temp\npm-6292-9a581886\registry.npmjs.org\caniuse-db\-\caniuse-db-1.0.30000507.tgz
npm ERR! Expected: 5fc9137a6f5b7f4d3e7577cf24f1bac54b330b6d
npm ERR! Actual:   3e7b3e4af5e3668f6a625fa88c95f3965953c164
npm ERR! From:     https://registry.npmjs.org/caniuse-db/-/caniuse-db-1.0.30000507.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     E:\workspace\scrum\npm-debug.log

**Comment by aikrez** [comment]
When upgrading   "openlayers": "3.17.1" to 3.18.1
```
npm WARN deprecated wrench@1.5.9: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "G:\\Apps\\nodejs\\node.exe" "C:\\Users\\alex.demulder\\Application Data\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.4.0
npm ERR! npm  v3.9.2

npm ERR! Maximum call stack size exceeded
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     G:\Data\proj_ratten\ratten-ui-webcontent\npm-debug.log
```

**Comment by cindyli** [comment]
I'm providing a github branch and hoping it will help npm team to reproduce this issue and find a solution: https://github.com/cindyli/universal/tree/reproduce-npm-stack-size-exceeded-error

This branch contains a vagrant VM that runs `npm install --no-bin-links` within VitualBox shared folder.

This branch contains a vagrant VM that uses:
- Fedora 24
- npm 3.10.3
- node 6.7.0

System Requirements to use this branch:
- [VirtualBox](https://www.virtualbox.org/wiki/Download_Old_Builds_5_0)
- [Vagrant](https://www.vagrantup.com/downloads.html)
- OpenSSH client

Host machine we've tested on:
MacOS 10.11.6 and Fedora 24

Steps to reproduce:
1. Pull out the branch and go to its root directory;
2. Run `vagrant up`
3. `Maximum call stack size exceeded` throws at running `npm install --no-bin-links`. The option of `--no-bin-links` is set via [a config file](https://github.com/idi-ops/ansible-nodejs/blob/master/files/npmrc#L1)

The discovery shows this error is related to running `npm install --no-bin-links` within a VirtualBox shared directory, so our work around is to mount the /node_modules directory of the host machine to a different directory than the VirtualBox shared folder.

The attempt of this work around is documented [here](https://issues.gpii.net/browse/GPII-2060).

The implementation for this work around is [here](https://github.com/idi-ops/ansible-nodejs/compare/master...gtirloni:GPII-2060).

**Comment by ratakondarajesh** [comment]
Hi,

I am seeing below error when trying to install appium using npm. Can any one shower some light on this. What am i missing and what are the version of node and npm that should be used for OS X- 10.11.6

Command:

npm install appium   ---- (running this as local user), but npm was installed as root itself.

the versions of npm and node are - 
node v6.9.2
npm  v4.0.5

Log:
-------------------

npm install appium

> sqlite3@3.1.8 install /Users/ram/node_modules/appium/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

[sqlite3] Success: "/Users/ram/node_modules/appium/node_modules/sqlite3/lib/binding/node-v48-darwin-x64/node_sqlite3.node" is installed via remote

> appium-chromedriver@2.9.4 install /Users/ram/node_modules/appium/node_modules/appium-chromedriver
> node install-npm.js

info Chromedriver Install Installing Chromedriver version '2.25' for platform 'mac' and architecture '64'
info Chromedriver Install Opening temp file to write chromedriver_mac64 to...
info Chromedriver Install Downloading https://chromedriver.storage.googleapis.com/2.25/chromedriver_mac64.zip...
RequestError: Error: connect ETIMEDOUT 216.58.217.48:443
    at new RequestError (/Users/ram/node_modules/appium/node_modules/request-promise/lib/errors.js:11:15)
    at Request.RP$callback [as _callback] (/Users/ram/node_modules/appium/node_modules/request-promise/lib/rp.js:60:32)
    at self.callback (/Users/ram/node_modules/appium/node_modules/request/request.js:186:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/Users/ram/node_modules/appium/node_modules/request/request.js:845:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at emitErrorNT (net.js:1278:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
/Users/ram
└── (empty)

npm WARN enoent ENOENT: no such file or directory, open '/Users/ram/package.json'
npm WARN ram No description
npm WARN ram No repository field.
npm WARN ram No README data
npm WARN ram No license field.
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "appium"
npm ERR! node v6.9.2
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE

npm ERR! appium-chromedriver@2.9.4 install: `node install-npm.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the appium-chromedriver@2.9.4 install script 'node install-npm.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the appium-chromedriver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install-npm.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs appium-chromedriver
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls appium-chromedriver
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ram/npm-debug.log
ram-mac:~ ram$ tail -f /Users/ram/npm-debug.log
73067 error If you do, this is most likely a problem with the appium-chromedriver package,
73067 error not with npm itself.
73067 error Tell the author that this fails on your system:
73067 error     node install-npm.js
73067 error You can get information on how to open an issue for this project with:
73067 error     npm bugs appium-chromedriver
73067 error Or if that isn't available, you can get their info via:
73067 error     npm owner ls appium-chromedriver
73067 error There is likely additional logging output above.
73068 verbose exit [ 1, true ]

**Comment by legodude17** [comment]
That isn't the same error @ratakondarajesh. Please open a new issue.

**Comment by martinambrus** [comment]
If you guys still can't reproduce this, I'm just running npm install --no-bin-links and get the following stack trace:
`
generator.development |
 npm info lifecycle ts-node@2.1.0~preinstall: ts-node@2.1.0

generator.development | npm info lifecycle tslint@4.5.1~preinstall: tslint@4.5.1

generator.development |
 npm info lifecycle typescript@2.2.1~preinstall: typescript@2.2.1

generator.development | npm info lifecycle winston@2.3.1~preinstall: winston@2.3.1

generator.development | npm WARN lifecycle v8-debug@0.7.7~preinstall: cannot run in wd %s %s (wd=%s) v8-debug@0.7.7 node -e 'process.exit(0)' /app/node_modules/.staging/v8-debug-2aa7a66d

generator.development | npm WARN lifecycle v8-profiler@5.6.5~preinstall: cannot run in wd %s %s (wd=%s) v8-profiler@5.6.5 node -e 'process.exit(0)' /app/node_modules/.staging/v8-profiler-687e44fd

generator.development | npm ERR! Linux 4.4.0-66-generic

generator.development | npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--no-bin-links"
generator.development | npm ERR! node v6.10.0
generator.development | npm ERR! npm  v3.10.10

generator.development | 
generator.development |
 npm ERR! Maximum call stack size exceeded

generator.development | npm ERR! 

generator.development | npm ERR! If you need help, you may report this error at:

generator.development | npm ERR!     <https://github.com/npm/npm/issues>

generator.development | 

generator.development | npm ERR! Please include the following file with any support request:
generator.development | npm ERR!     /app/npm-debug.log
`

the end of the npm-debug.log (everything else above the end just repeats with different package names):

`
43758 silly build gulp-mocha@3.0.1
43759 silly build gulp-nodemon@2.2.1
43760 silly build gulp-sourcemaps@1.11.1
43761 silly build gulp-tslint@7.1.0
43762 silly build gulp-typescript@3.1.5
43763 silly build inversify@3.1.0
43764 silly build jsdoc@3.4.3
43765 silly build node-inspector@0.12.10
43766 silly build node-rdkafka@0.8.0
43767 verbose stack RangeError: Maximum call stack size exceeded
43767 verbose stack     at normalizeStringPosix (path.js:78:30)
43767 verbose stack     at Object.resolve (path.js:1161:20)
43767 verbose stack     at Conf.<anonymous> (/usr/local/lib/node_modules/npm/lib/config/load-prefix.js:28:21)
43767 verbose stack     at EventEmitter.get [as globalDir] (/usr/local/lib/node_modules/npm/lib/npm.js:353:32)
43767 verbose stack     at build.writeBuiltinConf (/usr/local/lib/node_modules/npm/lib/build.js:81:16)
43767 verbose stack     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
43767 verbose stack     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
43767 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
43767 verbose stack     at build.linkStuff (/usr/local/lib/node_modules/npm/lib/build.js:96:53)
43767 verbose stack     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
43768 verbose cwd /app
43769 error Linux 4.4.0-66-generic
43770 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--no-bin-links"
43771 error node v6.10.0
43772 error npm  v3.10.10
43773 error Maximum call stack size exceeded
43774 error If you need help, you may report this error at:
43774 error     <https://github.com/npm/npm/issues>
43775 verbose exit [ 1, true ]
`

**Comment by dilvane** [comment]
With vagrant this worked fine for me:
config.vm.synced_folder ".", "/app", type: "rsync", rsync__exclude: "./node_modules"

**Comment by xywai1993** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\yiper\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'npm' ]
2 info using npm@3.0.0
3 info using node@v5.9.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly install normalizeTree
8 verbose stack RangeError: Maximum call stack size exceeded
8 verbose stack     at Array.forEach (native)
8 verbose stack     at exports.create (C:\Users\yiper\AppData\Roaming\npm\node_modules\npm\lib\install\node.js:26:25)
8 verbose stack     at C:\Users\yiper\AppData\Roaming\npm\node_modules\npm\lib\install\node.js:29:14
8 verbose stack     at Array.forEach (native)
8 verbose stack     at exports.create (C:\Users\yiper\AppData\Roaming\npm\node_modules\npm\lib\install\node.js:26:25)
8 verbose stack     at C:\Users\yiper\AppData\Roaming\npm\node_modules\npm\lib\install\node.js:29:14
8 verbose stack     at Array.forEach (native)
8 verbose stack     at exports.create (C:\Users\yiper\AppData\Roaming\npm\node_modules\npm\lib\install\node.js:26:25)
8 verbose stack     at exports.reset (C:\Users\yiper\AppData\Roaming\npm\node_modules\npm\lib\install\node.js:40:15)
8 verbose stack     at Array.forEach (native)
9 verbose cwd C:\WINDOWS\system32
10 error Windows_NT 10.0.14393
11 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\yiper\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "npm"
12 error node v5.9.1
13 error npm  v3.0.0
14 error Maximum call stack size exceeded
15 error If you need help, you may report this error at:
15 error     <https://github.com/npm/npm/issues>
16 verbose exit [ 1, true ]




I need help，thanks

**Comment by Krinkle** [comment]
Got the same issue in Vagrant.

```
52786 silly build vow-queue@0.4.2
52787 silly build which@1.2.14
52788 silly build which-module@1.0.0
52789 silly build window-size@0.1.0
52790 verbose stack RangeError: Maximum call stack size exceeded
52790 verbose stack     at String.slice (native)
52790 verbose stack     at normalizeStringPosix (path.js:130:22)
52790 verbose stack     at Object.resolve (path.js:1161:20)
52790 verbose stack     at Conf.<anonymous> (/usr/lib/node_modules/npm/lib/config/load-prefix.js:28:21)
52790 verbose stack     at EventEmitter.get [as globalDir] (/usr/lib/node_modules/npm/lib/npm.js:353:32)
52790 verbose stack     at build.writeBuiltinConf (/usr/lib/node_modules/npm/lib/build.js:81:16)
52790 verbose stack     at Array.<anonymous> (/usr/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
52790 verbose stack     at LOOP (/usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
52790 verbose stack     at /usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
52790 verbose stack     at build.linkStuff (/usr/lib/node_modules/npm/lib/build.js:96:53)
52791 verbose cwd /vagrant/srv/restbase
52792 error Linux 3.16.0-4-amd64
52793 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "--no-bin-links"
52794 error node v6.10.2
52795 error npm  v3.10.10
52796 error Maximum call stack size exceeded
```

**Comment by brettscott** [comment]
This problem has been around for quite a long period of time.  

We would see the issue more on projects with loads of dependencies.  The solution we've found to work reliably is to use Facebook's Yarn instead of NPM.
https://yarnpkg.com/lang/en/

Yarn isn't too different to NPM and continues to use NPM's `package.json`.  We haven't seen the "Maximum call stack size exceeded" since.

**Comment by sstawecki** [comment]
I was thinking on the same thing yesterday as a workaround. Using yarn or running `npm install` outside the virtual machine might work, of course isn't a solution, but as @brettscott said, the problem has been around for quite a long time.

**Comment by adiachenko** [comment]
Yes, **Yarn** doesn't have this issue. Haven't seen `Maximum call stack size exceeded` even since I made the switch.

**Comment by zyy7259** [comment]
When there is no package.json, npm@5.0.4 will encounter the `Maximum call stack size exceeded` problem. After `npm init`, everything works fine.

**Comment by NikitaVlaznev** [comment]
Seems like it can be related with the network connection issues.
I'm getting this all the time when running npm install while connected to the internet through my cell phone in a place with a weak signal:

    npm ERR! Maximum call stack size exceeded

It works fine on the same machine when connected over a stable wifi.

ubuntu 16.04
node 8.9.4
npm 5.6.0
