### ISSUE TITLE
Error: failed to fetch from registry: express

### ISSUE THREAD

**Issue by kwangseng** [npm/npm#9237]
```
info it worked if it ends with ok
verbose cli [ 'node', '/usr/local/bin/npm', 'install', '-g', 'express' ]
info using npm@1.1.0-beta-10
info using node@v0.6.7
verbose config file /Users/user/.npmrc
verbose config file /usr/local/etc/npmrc
verbose config file /usr/local/lib/node_modules/npm/npmrc
silly exec /usr/local/bin/node "/usr/local/lib/node_modules/npm/bin/npm-get-uid-gid.js" "nobody" 20
silly spawning [ '/usr/local/bin/node',
silly spawning   [ '/usr/local/lib/node_modules/npm/bin/npm-get-uid-gid.js',
silly spawning     'nobody',
silly spawning     20 ],
silly spawning   null ]
silly output from getuid/gid {"uid":-2,"gid":20}
silly output from getuid/gid
verbose into /usr/local/lib [ 'express' ]
verbose cache add express
verbose cache add [ 'express', null ]
silly cache add: name, spec, args [ undefined, 'express', [ 'express', null ] ]
verbose parsed url { pathname: 'express', path: 'express', href: 'express' }
verbose addNamed [ 'express', '' ]
verbose addNamed [ null, '' ]
silly name, range, hasData [ 'express', '', false ]
verbose raw, before any munging express
verbose url resolving [ 'https://registry.npmjs.org/', './express' ]
verbose url resolved https://registry.npmjs.org/express
http GET https://registry.npmjs.org/express
ERR! Error: failed to fetch from registry: express
ERR!     at /usr/local/lib/node_modules/npm/lib/utils/npm-registry-client/get.js:139:12
ERR!     at cb (/usr/local/lib/node_modules/npm/lib/utils/npm-registry-client/request.js:32:9)
ERR!     at Request._callback (/usr/local/lib/node_modules/npm/lib/utils/npm-registry-client/request.js:137:18)
ERR!     at Request.callback (/usr/local/lib/node_modules/npm/node_modules/request/main.js:104:22)
ERR!     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/main.js:181:58)
ERR!     at Request.emit (events.js:88:20)
ERR!     at ClientRequest.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/main.js:329:14)
ERR!     at ClientRequest.emit (events.js:67:17)
ERR!     at HTTPParser.onIncoming (http.js:1238:11)
ERR!     at HTTPParser.onHeadersComplete (http.js:102:31)
ERR! Report this *entire* log at:
ERR!     <http://github.com/isaacs/npm/issues>
ERR! or email it to:
ERR!     <npm-@googlegroups.com>
ERR!
ERR! System Darwin 14.4.0
ERR! command "node" "/usr/local/bin/npm" "install" "-g" "express"
ERR! cwd /Volumes/countly-server/countly-server-master
ERR! node -v v0.6.7
ERR! npm -v 1.1.0-beta-10
ERR! message failed to fetch from registry: express
verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
@kwangseng Node.js v0.6 is **several years old** and no longer supported by most of the known universe. Please try upgrading both [Node.js](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-node) and [`npm`](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm).

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some issues. If this is still a problem, can you please reply and let us know? We’ll be happy to reopen if necessary.
