### ISSUE TITLE
Cannot run iOS emulator for PhoneGap after install via Terminal

### ISSUE THREAD

**Issue by Avakore** [npm/npm#9255]
Terminal messages says include '.log' file, but GitHub attachment verification says .log isn't a supported file? So here it is in all it's glory!

```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'install', '-g', 'ios-sim' ]
2 info using npm@2.11.3
3 info using node@v0.12.7
4 verbose install initial load of /usr/local/lib/package.json
5 verbose readDependencies loading dependencies from /usr/local/lib/package.json
6 silly cache add args [ 'ios-sim', null ]
7 verbose cache add spec ios-sim
8 silly cache add parsed spec { raw: 'ios-sim',
8 silly cache add   scope: null,
8 silly cache add   name: 'ios-sim',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: '*',
8 silly cache add   type: 'range' }
9 silly addNamed ios-sim@*
10 verbose addNamed "*" is a valid semver range for ios-sim
11 silly addNameRange { name: 'ios-sim', range: '*', hasData: false }
12 silly mapToRegistry name ios-sim
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/ios-sim
16 verbose addNameRange registry:https://registry.npmjs.org/ios-sim not in flight; fetching
17 verbose request uri https://registry.npmjs.org/ios-sim
18 verbose request no auth needed
19 info attempt registry request try #1 at 7:59:28 PM
20 verbose request id 76cd580adab5a856
21 verbose etag "91HIQ4PB1NF3ALRSM1TO8OLOF"
22 http request GET https://registry.npmjs.org/ios-sim
23 http 304 https://registry.npmjs.org/ios-sim
24 silly get cb [ 304,
24 silly get   { date: 'Wed, 12 Aug 2015 18:59:07 GMT',
24 silly get     via: '1.1 varnish',
24 silly get     'cache-control': 'max-age=60',
24 silly get     etag: '"91HIQ4PB1NF3ALRSM1TO8OLOF"',
24 silly get     age: '0',
24 silly get     connection: 'keep-alive',
24 silly get     'x-served-by': 'cache-ams4130-AMS',
24 silly get     'x-cache': 'HIT',
24 silly get     'x-cache-hits': '1',
24 silly get     'x-timer': 'S1439405947.582784,VS0,VE159',
24 silly get     vary: 'Accept' } ]
25 verbose etag https://registry.npmjs.org/ios-sim from cache
26 verbose get saving ios-sim to /Users/studio1/.npm/registry.npmjs.org/ios-sim/.cache.json
27 silly addNameRange number 2 { name: 'ios-sim', range: '*', hasData: true }
28 silly addNameRange versions [ 'ios-sim',
28 silly addNameRange   [ '1.8.0',
28 silly addNameRange     '1.8.1',
28 silly addNameRange     '1.8.2',
28 silly addNameRange     '1.9.0',
28 silly addNameRange     '2.0.0',
28 silly addNameRange     '2.0.1',
28 silly addNameRange     '3.0.0',
28 silly addNameRange     '3.1.0',
28 silly addNameRange     '3.1.1',
28 silly addNameRange     '4.1.0',
28 silly addNameRange     '4.1.1',
28 silly addNameRange     '3.2.0' ] ]
29 silly addNamed ios-sim@4.1.1
30 verbose addNamed "4.1.1" is a plain semver version for ios-sim
31 silly cache afterAdd ios-sim@4.1.1
32 verbose afterAdd /Users/studio1/.npm/ios-sim/4.1.1/package/package.json not in flight; writing
33 verbose afterAdd /Users/studio1/.npm/ios-sim/4.1.1/package/package.json written
34 silly install resolved [ { name: 'ios-sim',
34 silly install resolved     version: '4.1.1',
34 silly install resolved     os: [ 'darwin' ],
34 silly install resolved     preferGlobal: 'true',
34 silly install resolved     description: 'launch iOS apps into the iOS Simulator from the command line (Xcode 6.0+)',
34 silly install resolved     main: 'ios-sim',
34 silly install resolved     repository:
34 silly install resolved      { type: 'git',
34 silly install resolved        url: 'git+https://github.com/phonegap/ios-sim.git' },
34 silly install resolved     engines: { node: '>=0.10.0' },
34 silly install resolved     keywords: [ 'ios-sim', 'iOS Simulator' ],
34 silly install resolved     bin: { 'ios-sim': './bin/ios-sim' },
34 silly install resolved     bugs: { url: 'https://github.com/phonegap/ios-sim/issues' },
34 silly install resolved     author: { name: 'Shazron Abdullah' },
34 silly install resolved     license: 'MIT',
34 silly install resolved     dependencies: { simctl: '^0.0.6', nopt: '1.0.9', 'bplist-parser': '^0.0.6' },
34 silly install resolved     gitHead: 'a0f2e2d8e4deca377b70041f3cbb2a529f6fa5e5',
34 silly install resolved     homepage: 'https://github.com/phonegap/ios-sim',
34 silly install resolved     _id: 'ios-sim@4.1.1',
34 silly install resolved     scripts: {},
34 silly install resolved     _shasum: '3458eca5e5d5e97ae11f19e35f6768584dcbf7cd',
34 silly install resolved     _from: 'ios-sim@*',
34 silly install resolved     _npmVersion: '2.5.1',
34 silly install resolved     _nodeVersion: '0.12.0',
34 silly install resolved     _npmUser: { name: 'shazron', email: 'shazron@gmail.com' },
34 silly install resolved     maintainers: [ [Object], [Object], [Object] ],
34 silly install resolved     dist:
34 silly install resolved      { shasum: '3458eca5e5d5e97ae11f19e35f6768584dcbf7cd',
34 silly install resolved        tarball: 'http://registry.npmjs.org/ios-sim/-/ios-sim-4.1.1.tgz' },
34 silly install resolved     directories: {},
34 silly install resolved     _resolved: 'https://registry.npmjs.org/ios-sim/-/ios-sim-4.1.1.tgz',
34 silly install resolved     readme: 'ERROR: No README data found!' } ]
35 info install ios-sim@4.1.1 into /usr/local/lib
36 info installOne ios-sim@4.1.1
37 verbose installOne of ios-sim to /usr/local/lib not in flight; installing
38 warn locking Error: EACCES, open '/Users/studio1/.npm/_locks/ios-sim-3bb56db538048d2f.lock'
38 warn locking     at Error (native)
38 warn locking  /Users/studio1/.npm/_locks/ios-sim-3bb56db538048d2f.lock failed { [Error: EACCES, open '/Users/studio1/.npm/_locks/ios-sim-3bb56db538048d2f.lock']
38 warn locking   errno: -13,
38 warn locking   code: 'EACCES',
38 warn locking   path: '/Users/studio1/.npm/_locks/ios-sim-3bb56db538048d2f.lock' }
39 verbose stack Error: Attempt to unlock /usr/local/lib/node_modules/ios-sim, which hasn't been locked
39 verbose stack     at unlock (/usr/local/lib/node_modules/npm/lib/utils/locker.js:66:11)
39 verbose stack     at cb (/usr/local/lib/node_modules/npm/lib/install.js:1017:5)
39 verbose stack     at /usr/local/lib/node_modules/npm/lib/install.js:1021:20
39 verbose stack     at /usr/local/lib/node_modules/npm/lib/utils/locker.js:40:9
39 verbose stack     at cb (/usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:149:38)
39 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:177:38
39 verbose stack     at FSReqWrap.oncomplete (fs.js:95:15)
40 verbose cwd /Library/WebServer/PhoneGap/helloworld
41 error Darwin 14.1.0
42 error argv "node" "/usr/local/bin/npm" "install" "-g" "ios-sim"
43 error node v0.12.7
44 error npm  v2.11.3
45 error Attempt to unlock /usr/local/lib/node_modules/ios-sim, which hasn't been locked
46 error If you need help, you may report this error at:
46 error     <https://github.com/npm/npm/issues>
47 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
@Avakore Have you tried?:

``` sh
$ sudo chown -R $(whoami) "$HOME/.npm"
```

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some issues. If this is still a problem, can you please reply and let us know? We’ll be happy to reopen if necessary.
