### ISSUE TITLE
Need info about what requires the module that has an error building

### ISSUE THREAD

**Issue by aredridel** [npm/npm#9257]
When I install with npm3, I get errors like

```
make: *** [Release/obj.target/onig_scanner/src/onig-cache.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/aredridel/lib/node_modules/pangyp/lib/build.js:271:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/usr/local/Cellar/iojs/3.0.0/bin/iojs" "/Users/aredridel/bin/pangyp" "rebuild"
gyp ERR! cwd /Users/aredridel/Projects/npm/newww/node_modules/oniguruma
gyp ERR! node -v v3.0.0
gyp ERR! pangyp -v v2.1.0
gyp ERR! not ok
```

which in npm2, would have been more deeply nested -- something like `node_modules/othermodule/node_modules/oniguruma`. with npm3, I don't know what to look at to figure out what's requiring this, since the package hasn't installed (so nothing on disk to examine) and it's not listed in my package.json, and I haven't had the successful run output yet (no npm ls output that shows an error either)

**Comment by othiym23** [comment]
Improving the context here is definitely something that's more important now that the CLI is flattening the dependency tree, so this falls in the bucket of things that need to be made more stable for `npm@3` and will be part of what the team works on after it gets the tests more squared away.
