### ISSUE TITLE
TypeError: Cannot call method 'match' of undefined

### ISSUE THREAD

**Issue by Markkos89** [npm/npm#9273]
i dont know why im doing this but anyone can help me with this? thanks

```
C:\Users\pc1\Proyectos\Maresa>npm install promise @7.0.2 --save
npm http GET https://registry.npmjs.org/7.0.2
npm http GET https://registry.npmjs.org/promise
npm http 304 https://registry.npmjs.org/promise
npm http 404 https://registry.npmjs.org/7.0.2
npm ERR! TypeError: Cannot call method 'match' of undefined
npm ERR!     at RegClient.<anonymous> (C:\Program Files (x86)\nodejs\node_module
s\npm\node_modules\npm-registry-client\lib\request.js:119:29)
npm ERR!     at cb (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\
npm-registry-client\lib\request.js:158:9)
npm ERR!     at RegClient.<anonymous> (C:\Program Files (x86)\nodejs\node_module
s\npm\node_modules\npm-registry-client\lib\request.js:249:14)
npm ERR!     at Request.self.callback (C:\Program Files (x86)\nodejs\node_module
s\npm\node_modules\request\main.js:120:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\
npm\node_modules\request\main.js:648:16)
npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (C:\Program Files (x86)\nodejs\node_
modules\npm\node_modules\request\main.js:610:14)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:870:14
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program File
s (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "promise" "@7.0.2
" "--save"
npm ERR! cwd C:\Users\pc1\Proyectos\Maresa
npm ERR! node -v v0.10.0
npm ERR! npm -v 1.2.14
npm ERR! type non_object_property_call
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\pc1\Proyectos\Maresa\npm-debug.log
npm ERR! not ok code 0
```

**Comment by KenanY** [comment]
@Markkos89 Please try [upgrading](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows) first.

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some issues. If this is still a problem, can you please reply and let us know? We’ll be happy to reopen if necessary.
