### ISSUE TITLE
npm install -g cordova ionic ERR

### ISSUE THREAD

**Issue by danilodelfio** [npm/npm#9286]
After nodejs update (to the last version: v0.12.7), with npm  v.1.1.62, i got this errors:

```
npm http GET https://registry.npmjs.org/ionic
npm http GET https://registry.npmjs.org/cordova
npm http 304 https://registry.npmjs.org/ionic
npm http 304 https://registry.npmjs.org/cordova
npm ERR! TypeError: Arguments to path.resolve must be strings
npm ERR!     at Object.posix.resolve (path.js:439:13)
npm ERR!     at Object.posix.relative (path.js:505:16)
npm ERR!     at installOne_ (/usr/local/lib/node_modules/npm/lib/install.js:693:26)
npm ERR!     at installOne (/usr/local/lib/node_modules/npm/lib/install.js:621:3)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/install.js:508:9
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:54:35
npm ERR!     at Array.forEach (native)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:54:11
npm ERR!     at Array.forEach (native)
npm ERR!     at asyncMap (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:53:8)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 13.4.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "-g" "cordova" "ionic"
npm ERR! cwd /Users/karmakiller/projects
npm ERR! node -v v0.12.7
npm ERR! npm -v 1.1.62
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/karnakiller/projects/npm-debug.log
npm ERR! not ok code 0
```
What's the problem?
Thank you in advantage.

**Comment by KenanY** [comment]
@danilodelfio Yikes, despite your very new version of Node.js, your `npm` version is years old! Please try [upgrading](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm).

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some issues. If this is still a problem, can you please reply and let us know? We’ll be happy to reopen if necessary.
