### ISSUE TITLE
Cannot run NPM commands ('npm install' doesn't help)

### ISSUE THREAD

**Issue by osherdo** [npm/npm#9291]
I have Windows 8.1.

I am trying to run a command on my laravel project root folder:

`node socket.js`

in return the console returns the following error:

```
module.js:338
    throw err;
          ^
Error: Cannot find module 'ultron'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\Osherdo\Desktop\SportsApp\sportsapp\node_mod
ules\socket.io\node_modules\engine.io\node_modules\ws\lib\WebSocket.js:15:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

Next, when trying to fix it and running `npm install` it returns this:

```
npm WARN unmet dependency C:\Users\Osherdo\Desktop\SportsApp\sportsapp\node_modu
les\socket.io\node_modules\socket.io-client\node_modules\engine.io-client requir
es debug@'1.0.4' but will load
npm WARN unmet dependency C:\Users\Osherdo\Desktop\SportsApp\sportsapp\node_modu
les\socket.io\node_modules\socket.io-client\node_modules\debug,
npm WARN unmet dependency which is version 0.7.4
npm WARN unmet dependency C:\Users\Osherdo\Desktop\SportsApp\sportsapp\node_modu
les\socket.io\node_modules\socket.io-client\node_modules\engine.io-client requir
es parseuri@'0.0.4' but will load
npm WARN unmet dependency C:\Users\Osherdo\Desktop\SportsApp\sportsapp\node_modu
les\socket.io\node_modules\socket.io-client\node_modules\parseuri,
npm WARN unmet dependency which is version 0.0.2
npm WARN unmet dependency C:\Users\Osherdo\Desktop\SportsApp\sportsapp\node_modu
les\gulp\node_modules\liftoff requires findup-sync@'^0.2.1' but will load
npm WARN unmet dependency C:\Users\Osherdo\Desktop\SportsApp\sportsapp\node_modu
les\findup-sync,
npm WARN unmet dependency which is version 0.1.2
npm WARN unmet dependency C:\Users\Osherdo\Desktop\SportsApp\sportsapp\node_modu
les\laravel-elixir\node_modules\browserify requires glob@'^4.0.5' but will load
npm WARN unmet dependency C:\Users\Osherdo\Desktop\SportsApp\sportsapp\node_modu
les\laravel-elixir\node_modules\glob,
npm WARN unmet dependency which is version 5.0.14
npm WARN unmet dependency C:\Users\Osherdo\Desktop\SportsApp\sportsapp\node_modu
les\laravel-elixir\node_modules\gulp-less\node_modules\accord requires glob@'4.x
' but will load
npm WARN unmet dependency C:\Users\Osherdo\Desktop\SportsApp\sportsapp\node_modu
les\laravel-elixir\node_modules\glob,
npm WARN unmet dependency which is version 5.0.14
npm WARN unmet dependency C:\Users\Osherdo\Desktop\SportsApp\sportsapp\node_modu
les\laravel-elixir\node_modules\gulp-phpspec\node_modules\gulp-jshint requires g
ulp-util@'^3.0.0' but will load
npm WARN unmet dependency C:\Users\Osherdo\Desktop\SportsApp\sportsapp\node_modu
les\laravel-elixir\node_modules\gulp-phpspec\node_modules\gulp-util,
npm WARN unmet dependency which is version 2.2.20
npm WARN unmet dependency C:\Users\Osherdo\Desktop\SportsApp\sportsapp\node_modu
les\laravel-elixir\node_modules\gulp-phpspec\node_modules\gulp-logger requires c
halk@'^0.5.1' but will load
npm WARN unmet dependency C:\Users\Osherdo\Desktop\SportsApp\sportsapp\node_modu
les\laravel-elixir\node_modules\gulp-phpspec\node_modules\chalk,
npm WARN unmet dependency which is version 1.1.0
npm WARN unmet dependency C:\Users\Osherdo\Desktop\SportsApp\sportsapp\node_modu
les\laravel-elixir\node_modules\gulp-phpspec\node_modules\gulp-logger requires g
ulp-util@'^3.0.0' but will load
npm WARN unmet dependency C:\Users\Osherdo\Desktop\SportsApp\sportsapp\node_modu
les\laravel-elixir\node_modules\gulp-phpspec\node_modules\gulp-util,
npm WARN unmet dependency which is version 2.2.20
npm WARN unmet dependency C:\Users\Osherdo\Desktop\SportsApp\sportsapp\node_modu
les\laravel-elixir\node_modules\gulp-phpspec\node_modules\gulp-todo requires gul
p-util@'^3.0.1' but will load
npm WARN unmet dependency C:\Users\Osherdo\Desktop\SportsApp\sportsapp\node_modu
les\laravel-elixir\node_modules\gulp-phpspec\node_modules\gulp-util,
npm WARN unmet dependency which is version 2.2.20
npm WARN unmet dependency C:\Users\Osherdo\Desktop\SportsApp\sportsapp\node_modu
les\laravel-elixir\node_modules\gulp-phpspec\node_modules\gulp-util requires cha
lk@'^0.5.0' but will load
npm WARN unmet dependency C:\Users\Osherdo\Desktop\SportsApp\sportsapp\node_modu
les\laravel-elixir\node_modules\gulp-phpspec\node_modules\chalk,
npm WARN unmet dependency which is version 1.1.0
npm WARN unmet dependency C:\Users\Osherdo\Desktop\SportsApp\sportsapp\node_modu
les\laravel-elixir\node_modules\gulp-phpspec\node_modules\jshint requires lodash
@'3.7.x' but will load
npm WARN unmet dependency C:\Users\Osherdo\Desktop\SportsApp\sportsapp\node_modu
les\laravel-elixir\node_modules\gulp-phpspec\node_modules\lodash,
npm WARN unmet dependency which is version 3.10.1
npm WARN unmet dependency C:\Users\Osherdo\Desktop\SportsApp\sportsapp\node_modu
les\laravel-elixir\node_modules\gulp-sass\node_modules\node-sass\node_modules\pa
ngyp requires glob@'~4.3.5' but will load
npm WARN unmet dependency C:\Users\Osherdo\Desktop\SportsApp\sportsapp\node_modu
les\laravel-elixir\node_modules\glob,
npm WARN unmet dependency which is version 5.0.14
npm WARN unmet dependency C:\Users\Osherdo\Desktop\SportsApp\sportsapp\node_modu
les\laravel-elixir\node_modules\gulp-sass\node_modules\node-sass\node_modules\pa
ngyp requires request@'~2.51.0' but will load
npm WARN unmet dependency C:\Users\Osherdo\Desktop\SportsApp\sportsapp\node_modu
les\laravel-elixir\node_modules\gulp-sass\node_modules\node-sass\node_modules\re
quest,
npm WARN unmet dependency which is version 2.60.0
npm WARN unmet dependency C:\Users\Osherdo\Desktop\SportsApp\sportsapp\node_modu
les\laravel-elixir\node_modules\watchify\node_modules\browserify requires glob@'
^4.0.5' but will load
npm WARN unmet dependency C:\Users\Osherdo\Desktop\SportsApp\sportsapp\node_modu
les\laravel-elixir\node_modules\glob,
npm WARN unmet dependency which is version 5.0.14
npm WARN unmet dependency C:\Users\Osherdo\Desktop\SportsApp\sportsapp\node_modu
les\laravel-elixir\node_modules\watchify\node_modules\browserify requires throug
h2@'^1.0.0' but will load
npm WARN unmet dependency C:\Users\Osherdo\Desktop\SportsApp\sportsapp\node_modu
les\laravel-elixir\node_modules\watchify\node_modules\through2,
npm WARN unmet dependency which is version 0.6.5
```

How do I fix this? I googled it for a while and did not succeed so far.

Any suggested actions to make?

Thanks.

**Comment by osherdo** [comment]
anyone please?

**Comment by sinkingshriek** [comment]
Welcome to the npm's issue tracker, @osherdo. Unfortunately this doesn't look like it's npm issue at all. The messages that you posted are only `warn` messages and don't see any errors.

**Comment by osherdo** [comment]
but npm is preceding the warn. I tried to google that issue and the solutions there bring me back to npm. 

warn is like a warning in programming in this case?
