### ISSUE TITLE
mongoose-auto-increment in windows,maybe the package.json has problems.

### ISSUE THREAD

**Issue by AiFuYou** [npm/npm#9292]
```
G:\svn\server\web-server>npm install mongoose-auto-increment
npm WARN package.json server@0.0.1 No repository field.
npm WARN package.json server@0.0.1 No readme data.
npm http GET https://registry.npmjs.org/mongoose-auto-increment
npm http 304 https://registry.npmjs.org/mongoose-auto-increment
npm http GET https://registry.npmjs.org/extend
npm http 304 https://registry.npmjs.org/extend
npm ERR! Error: No compatible version found: extend@'^2.0.0'
npm ERR! Valid install targets:
npm ERR! ["1.0.0","1.1.0","1.1.1","1.1.3","1.2.0","1.2.1","1.3.0","2.0.0","2.0.1","3.0.0"]
npm ERR!     at installTargetsError (C:\Program Files\nodejs\node_modules\npm\lib\cache.js:709:10)
npm ERR!     at C:\Program Files\nodejs\node_modules\npm\lib\cache.js:631:10
npm ERR!     at saved (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>
```

**Comment by KenanY** [comment]
@AiFuYou You **must** be running an old version of `npm` to be getting an error like that. Please try [upgrading](https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows)!

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some issues. If this is still a problem, can you please reply and let us know? We’ll be happy to reopen if necessary.
