### ISSUE TITLE
npm not installing dependencies from package.json

### ISSUE THREAD

**Issue by jacka92** [npm/npm#9306]
![npm](https://cloud.githubusercontent.com/assets/8577075/9306596/343b87e6-44f1-11e5-9a63-8842b002f6e3.png)

npm is not installing the dependencies. It doesn't give any explanation as to why this is happening. 

Error log below:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'install' ]
2 info using npm@1.3.10
3 info using node@v0.10.25
4 verbose readDependencies using package.json deps
5 verbose install where, deps [ '/home/amnesia/Desktop/GPS',
5 verbose install   [ 'bcrypt',
5 verbose install     'body-parser',
5 verbose install     'connect-flash',
5 verbose install     'cookie-parser',
5 verbose install     'debug',
5 verbose install     'express',
5 verbose install     'hbs',
5 verbose install     'mongoose',
5 verbose install     'morgan',
5 verbose install     'node-xlsx',
5 verbose install     'passport',
5 verbose install     'passport-local',
5 verbose install     'xlsx',
5 verbose install     'express-sesion',
5 verbose install     'connect-mongo' ] ]
6 info preinstall workspace@0.0.0
7 verbose readDependencies using package.json deps
8 verbose already installed skipping cookie-parser@~1.3.3 /home/amnesia/Desktop/GPS
9 verbose already installed skipping bcrypt@~0.8.5 /home/amnesia/Desktop/GPS
10 verbose already installed skipping body-parser@~1.10.1 /home/amnesia/Desktop/GPS
11 verbose already installed skipping connect-flash@^0.1.1 /home/amnesia/Desktop/GPS
12 verbose already installed skipping debug@~2.1.1 /home/amnesia/Desktop/GPS
13 verbose already installed skipping express@~4.11.0 /home/amnesia/Desktop/GPS
14 verbose already installed skipping hbs@~2.8.0 /home/amnesia/Desktop/GPS
15 verbose cache add [ 'mongoose@~3.8.21', null ]
16 verbose cache add name=undefined spec="mongoose@~3.8.21" args=["mongoose@~3.8.21",null]
17 verbose parsed url { protocol: null,
17 verbose parsed url   slashes: null,
17 verbose parsed url   auth: null,
17 verbose parsed url   host: null,
17 verbose parsed url   port: null,
17 verbose parsed url   hostname: null,
17 verbose parsed url   hash: null,
17 verbose parsed url   search: null,
17 verbose parsed url   query: null,
17 verbose parsed url   pathname: 'mongoose@~3.8.21',
17 verbose parsed url   path: 'mongoose@~3.8.21',
17 verbose parsed url   href: 'mongoose@~3.8.21' }
18 verbose cache add name="mongoose" spec="~3.8.21" args=["mongoose","~3.8.21"]
19 verbose parsed url { protocol: null,
19 verbose parsed url   slashes: null,
19 verbose parsed url   auth: null,
19 verbose parsed url   host: null,
19 verbose parsed url   port: null,
19 verbose parsed url   hostname: null,
19 verbose parsed url   hash: null,
19 verbose parsed url   search: null,
19 verbose parsed url   query: null,
19 verbose parsed url   pathname: '~3.8.21',
19 verbose parsed url   path: '~3.8.21',
19 verbose parsed url   href: '~3.8.21' }
20 verbose addNamed [ 'mongoose', '~3.8.21' ]
21 verbose addNamed [ null, '>=3.8.21-0 <3.9.0-0' ]
22 silly lockFile 3ec00dd8-mongoose-3-8-21 mongoose@~3.8.21
23 verbose lock mongoose@~3.8.21 /home/amnesia/.npm/3ec00dd8-mongoose-3-8-21.lock
24 verbose already installed skipping node-xlsx@^0.5.1 /home/amnesia/Desktop/GPS
25 verbose already installed skipping morgan@~1.5.1 /home/amnesia/Desktop/GPS
26 verbose already installed skipping passport@^0.2.2 /home/amnesia/Desktop/GPS
27 silly addNameRange { name: 'mongoose',
27 silly addNameRange   range: '>=3.8.21-0 <3.9.0-0',
27 silly addNameRange   hasData: false }
28 verbose already installed skipping passport-local@^1.0.0 /home/amnesia/Desktop/GPS
29 verbose url raw mongoose
30 verbose url resolving [ 'https://registry.npmjs.org/', './mongoose' ]
31 verbose url resolved https://registry.npmjs.org/mongoose
32 info trying registry request attempt 1 at 14:54:12
33 verbose etag "57OQ7B5XD1IXTNMTZE906BUZN"
34 http GET https://registry.npmjs.org/mongoose
35 verbose cache add [ 'connect-mongo@~0.8.2', null ]
36 verbose cache add name=undefined spec="connect-mongo@~0.8.2" args=["connect-mongo@~0.8.2",null]
37 verbose parsed url { protocol: null,
37 verbose parsed url   slashes: null,
37 verbose parsed url   auth: null,
37 verbose parsed url   host: null,
37 verbose parsed url   port: null,
37 verbose parsed url   hostname: null,
37 verbose parsed url   hash: null,
37 verbose parsed url   search: null,
37 verbose parsed url   query: null,
37 verbose parsed url   pathname: 'connect-mongo@~0.8.2',
37 verbose parsed url   path: 'connect-mongo@~0.8.2',
37 verbose parsed url   href: 'connect-mongo@~0.8.2' }
38 verbose cache add name="connect-mongo" spec="~0.8.2" args=["connect-mongo","~0.8.2"]
39 verbose parsed url { protocol: null,
39 verbose parsed url   slashes: null,
39 verbose parsed url   auth: null,
39 verbose parsed url   host: null,
39 verbose parsed url   port: null,
39 verbose parsed url   hostname: null,
39 verbose parsed url   hash: null,
39 verbose parsed url   search: null,
39 verbose parsed url   query: null,
39 verbose parsed url   pathname: '~0.8.2',
39 verbose parsed url   path: '~0.8.2',
39 verbose parsed url   href: '~0.8.2' }
40 verbose addNamed [ 'connect-mongo', '~0.8.2' ]
41 verbose addNamed [ null, '>=0.8.2-0 <0.9.0-0' ]
42 silly lockFile 5ae97cad-connect-mongo-0-8-2 connect-mongo@~0.8.2
43 verbose lock connect-mongo@~0.8.2 /home/amnesia/.npm/5ae97cad-connect-mongo-0-8-2.lock
44 verbose already installed skipping xlsx@^0.8.0 /home/amnesia/Desktop/GPS
45 verbose cache add [ 'express-sesion@~1.11.3', null ]
46 verbose cache add name=undefined spec="express-sesion@~1.11.3" args=["express-sesion@~1.11.3",null]
47 verbose parsed url { protocol: null,
47 verbose parsed url   slashes: null,
47 verbose parsed url   auth: null,
47 verbose parsed url   host: null,
47 verbose parsed url   port: null,
47 verbose parsed url   hostname: null,
47 verbose parsed url   hash: null,
47 verbose parsed url   search: null,
47 verbose parsed url   query: null,
47 verbose parsed url   pathname: 'express-sesion@~1.11.3',
47 verbose parsed url   path: 'express-sesion@~1.11.3',
47 verbose parsed url   href: 'express-sesion@~1.11.3' }
48 verbose cache add name="express-sesion" spec="~1.11.3" args=["express-sesion","~1.11.3"]
49 verbose parsed url { protocol: null,
49 verbose parsed url   slashes: null,
49 verbose parsed url   auth: null,
49 verbose parsed url   host: null,
49 verbose parsed url   port: null,
49 verbose parsed url   hostname: null,
49 verbose parsed url   hash: null,
49 verbose parsed url   search: null,
49 verbose parsed url   query: null,
49 verbose parsed url   pathname: '~1.11.3',
49 verbose parsed url   path: '~1.11.3',
49 verbose parsed url   href: '~1.11.3' }
50 verbose addNamed [ 'express-sesion', '~1.11.3' ]
51 verbose addNamed [ null, '>=1.11.3-0 <1.12.0-0' ]
52 silly lockFile df851df2-express-sesion-1-11-3 express-sesion@~1.11.3
53 verbose lock express-sesion@~1.11.3 /home/amnesia/.npm/df851df2-express-sesion-1-11-3.lock
54 silly addNameRange { name: 'connect-mongo',
54 silly addNameRange   range: '>=0.8.2-0 <0.9.0-0',
54 silly addNameRange   hasData: false }
55 silly addNameRange { name: 'express-sesion',
55 silly addNameRange   range: '>=1.11.3-0 <1.12.0-0',
55 silly addNameRange   hasData: false }
56 verbose url raw express-sesion
57 verbose url resolving [ 'https://registry.npmjs.org/', './express-sesion' ]
58 verbose url resolved https://registry.npmjs.org/express-sesion
59 info trying registry request attempt 1 at 14:54:12
60 http GET https://registry.npmjs.org/express-sesion
61 verbose url raw connect-mongo
62 verbose url resolving [ 'https://registry.npmjs.org/', './connect-mongo' ]
63 verbose url resolved https://registry.npmjs.org/connect-mongo
64 info trying registry request attempt 1 at 14:54:12
65 verbose etag "67P9FHJJ9BQX6BJXIFYEFJ1KY"
66 http GET https://registry.npmjs.org/connect-mongo
67 http 304 https://registry.npmjs.org/mongoose
68 silly registry.get cb [ 304,
68 silly registry.get   { date: 'Mon, 17 Aug 2015 13:54:13 GMT',
68 silly registry.get     via: '1.1 varnish',
68 silly registry.get     'cache-control': 'max-age=60',
68 silly registry.get     etag: '"57OQ7B5XD1IXTNMTZE906BUZN"',
68 silly registry.get     age: '46',
68 silly registry.get     connection: 'keep-alive',
68 silly registry.get     'x-served-by': 'cache-lhr6329-LHR',
68 silly registry.get     'x-cache': 'HIT',
68 silly registry.get     'x-cache-hits': '2',
68 silly registry.get     'x-timer': 'S1439819653.968235,VS0,VE0',
68 silly registry.get     vary: 'Accept' } ]
69 verbose etag mongoose from cache
70 silly addNameRange number 2 { name: 'mongoose', range: '>=3.8.21-0 <3.9.0-0', hasData: true }
71 silly addNameRange versions [ 'mongoose',
71 silly addNameRange   [ '0.0.1',
71 silly addNameRange     '0.0.2',
71 silly addNameRange     '0.0.3',
71 silly addNameRange     '0.0.4',
71 silly addNameRange     '0.0.5',
71 silly addNameRange     '1.0.0',
71 silly addNameRange     '1.0.1',
71 silly addNameRange     '1.0.2',
71 silly addNameRange     '0.0.6',
71 silly addNameRange     '1.0.3',
71 silly addNameRange     '1.0.4',
71 silly addNameRange     '1.0.5',
71 silly addNameRange     '1.0.6',
71 silly addNameRange     '1.0.7',
71 silly addNameRange     '1.0.8',
71 silly addNameRange     '1.0.10',
71 silly addNameRange     '1.0.11',
71 silly addNameRange     '1.0.12',
71 silly addNameRange     '1.0.13',
71 silly addNameRange     '1.0.14',
71 silly addNameRange     '1.0.15',
71 silly addNameRange     '1.0.16',
71 silly addNameRange     '1.1.0',
71 silly addNameRange     '1.1.1',
71 silly addNameRange     '1.1.2',
71 silly addNameRange     '1.1.3',
71 silly addNameRange     '1.1.4',
71 silly addNameRange     '1.1.5',
71 silly addNameRange     '1.1.6',
71 silly addNameRange     '1.1.7',
71 silly addNameRange     '1.1.8',
71 silly addNameRange     '1.1.9',
71 silly addNameRange     '1.1.10',
71 silly addNameRange     '1.1.11',
71 silly addNameRange     '1.1.12',
71 silly addNameRange     '1.1.13',
71 silly addNameRange     '1.1.14',
71 silly addNameRange     '1.1.15',
71 silly addNameRange     '1.1.16',
71 silly addNameRange     '1.1.17',
71 silly addNameRange     '1.1.18',
71 silly addNameRange     '1.1.19',
71 silly addNameRange     '1.1.20',
71 silly addNameRange     '1.1.21',
71 silly addNameRange     '1.1.22',
71 silly addNameRange     '1.1.23',
71 silly addNameRange     '1.1.24',
71 silly addNameRange     '1.1.25',
71 silly addNameRange     '1.2.0',
71 silly addNameRange     '1.3.0',
71 silly addNameRange     '1.3.1',
71 silly addNameRange     '1.3.2',
71 silly addNameRange     '1.3.3',
71 silly addNameRange     '1.3.4',
71 silly addNameRange     '1.3.5',
71 silly addNameRange     '1.3.6',
71 silly addNameRange     '1.3.7',
71 silly addNameRange     '1.4.0',
71 silly addNameRange     '1.5.0',
71 silly addNameRange     '1.6.0',
71 silly addNameRange     '1.7.2',
71 silly addNameRange     '1.7.3',
71 silly addNameRange     '1.7.4',
71 silly addNameRange     '1.8.0',
71 silly addNameRange     '1.8.1',
71 silly addNameRange     '1.8.2',
71 silly addNameRange     '1.8.3',
71 silly addNameRange     '1.8.4',
71 silly addNameRange     '2.0.0',
71 silly addNameRange     '2.0.1',
71 silly addNameRange     '2.0.2',
71 silly addNameRange     '2.0.3',
71 silly addNameRange     '2.0.4',
71 silly addNameRange     '2.1.0',
71 silly addNameRange     '2.1.1',
71 silly addNameRange     '2.1.2',
71 silly addNameRange     '2.1.3',
71 silly addNameRange     '2.1.4',
71 silly addNameRange     '2.2.0',
71 silly addNameRange     '2.2.1',
71 silly addNameRange     '2.2.2',
71 silly addNameRange     '2.2.3',
71 silly addNameRange     '2.2.4',
71 silly addNameRange     '2.3.0',
71 silly addNameRange     '2.3.1',
71 silly addNameRange     '2.3.2',
71 silly addNameRange     '2.3.3',
71 silly addNameRange     '2.3.4',
71 silly addNameRange     '2.3.5',
71 silly addNameRange     '2.3.6',
71 silly addNameRange     '2.3.7',
71 silly addNameRange     '2.3.8',
71 silly addNameRange     '2.3.9',
71 silly addNameRange     '2.3.10',
71 silly addNameRange     '2.3.11',
71 silly addNameRange     '2.3.12',
71 silly addNameRange     '2.3.13',
71 silly addNameRange     '2.4.0',
71 silly addNameRange     '2.4.1',
71 silly addNameRange     '2.4.2',
71 silly addNameRange     '2.4.3',
71 silly addNameRange     '2.4.4',
71 silly addNameRange     '2.4.5',
71 silly addNameRange     '2.4.6',
71 silly addNameRange     '2.4.7',
71 silly addNameRange     '2.4.8',
71 silly addNameRange     '2.4.9',
71 silly addNameRange     '2.4.10',
71 silly addNameRange     '2.5.0',
71 silly addNameRange     '2.5.1',
71 silly addNameRange     '2.5.2',
71 silly addNameRange     '2.5.3',
71 silly addNameRange     '2.5.4',
71 silly addNameRange     '2.5.5',
71 silly addNameRange     '2.5.6',
71 silly addNameRange     '2.5.7',
71 silly addNameRange     '2.5.8',
71 silly addNameRange     '2.5.9',
71 silly addNameRange     '2.5.10',
71 silly addNameRange     '2.5.11',
71 silly addNameRange     '2.5.12',
71 silly addNameRange     '2.5.13',
71 silly addNameRange     '2.5.14',
71 silly addNameRange     '2.6.0',
71 silly addNameRange     '2.6.1',
71 silly addNameRange     '2.6.2',
71 silly addNameRange     '2.6.3',
71 silly addNameRange     '2.6.4',
71 silly addNameRange     '2.6.5',
71 silly addNameRange     '2.6.6',
71 silly addNameRange     '2.6.7',
71 silly addNameRange     '2.6.8',
71 silly addNameRange     '2.7.0',
71 silly addNameRange     '2.7.1',
71 silly addNameRange     '2.7.2',
71 silly addNameRange     '2.7.4',
71 silly addNameRange     '2.7.3',
71 silly addNameRange     '3.0.0',
71 silly addNameRange     '3.0.1',
71 silly addNameRange     '3.0.2',
71 silly addNameRange     '2.8.0',
71 silly addNameRange     '3.0.3',
71 silly addNameRange     '3.1.0',
71 silly addNameRange     '2.8.1',
71 silly addNameRange     '3.1.1',
71 silly addNameRange     '2.8.2',
71 silly addNameRange     '2.8.3',
71 silly addNameRange     '2.9.0',
71 silly addNameRange     '3.2.0',
71 silly addNameRange     '2.9.1',
71 silly addNameRange     '3.2.1',
71 silly addNameRange     '2.9.2',
71 silly addNameRange     '3.2.2',
71 silly addNameRange     '3.3.0',
71 silly addNameRange     '3.3.1',
71 silly addNameRange     '2.9.3',
71 silly addNameRange     '3.4.0',
71 silly addNameRange     '2.9.4',
71 silly addNameRange     '2.9.5',
71 silly addNameRange     '3.5.0',
71 silly addNameRange     '3.5.1',
71 silly addNameRange     '3.5.2',
71 silly addNameRange     '3.5.3',
71 silly addNameRange     '2.9.6',
71 silly addNameRange     '2.9.7',
71 silly addNameRange     '3.5.4',
71 silly addNameRange     '3.5.5',
71 silly addNameRange     '2.9.8',
71 silly addNameRange     '2.9.9',
71 silly addNameRange     '3.5.6',
71 silly addNameRange     '3.5.7',
71 silly addNameRange     '3.5.8',
71 silly addNameRange     '2.9.10',
71 silly addNameRange     '3.5.9',
71 silly addNameRange     '3.6.2',
71 silly addNameRange     '3.5.10',
71 silly addNameRange     '3.6.3',
71 silly addNameRange     '3.5.11',
71 silly addNameRange     '3.6.4',
71 silly addNameRange     '3.6.5',
71 silly addNameRange     '3.6.6',
71 silly addNameRange     '3.6.7',
71 silly addNameRange     '3.5.12',
71 silly addNameRange     '3.6.8',
71 silly addNameRange     '3.6.9',
71 silly addNameRange     '3.6.10',
71 silly addNameRange     '3.5.13',
71 silly addNameRange     '3.5.14',
71 silly addNameRange     '3.6.11',
71 silly addNameRange     '3.6.12',
71 silly addNameRange     '3.6.13',
71 silly addNameRange     '3.6.14',
71 silly addNameRange     '3.6.15',
71 silly addNameRange     '3.5.15',
71 silly addNameRange     '3.7.0',
71 silly addNameRange     '3.6.16',
71 silly addNameRange     '3.5.16',
71 silly addNameRange     '3.6.17',
71 silly addNameRange     '3.7.2',
71 silly addNameRange     '3.0.0-alpha1',
71 silly addNameRange     '3.0.0-alpha2',
71 silly addNameRange     '3.0.0-rc0',
71 silly addNameRange     '3.6.0-rc0',
71 silly addNameRange     '3.6.0-rc1',
71 silly addNameRange     '3.6.18',
71 silly addNameRange     '3.7.3',
71 silly addNameRange     '3.6.19',
71 silly addNameRange     '3.6.20',
71 silly addNameRange     '3.7.4',
71 silly addNameRange     '3.8.0',
71 silly addNameRange     '3.8.1',
71 silly addNameRange     '3.8.2',
71 silly addNameRange     '3.8.3',
71 silly addNameRange     '3.8.4',
71 silly addNameRange     '3.8.5',
71 silly addNameRange     '3.8.6',
71 silly addNameRange     '3.8.7',
71 silly addNameRange     '3.8.8',
71 silly addNameRange     '3.8.9',
71 silly addNameRange     '3.8.10',
71 silly addNameRange     '3.8.11',
71 silly addNameRange     '3.9.0',
71 silly addNameRange     '3.8.12',
71 silly addNameRange     '3.8.13',
71 silly addNameRange     '3.8.14',
71 silly addNameRange     '3.8.15',
71 silly addNameRange     '3.9.1',
71 silly addNameRange     '3.8.16',
71 silly addNameRange     '3.9.2',
71 silly addNameRange     '3.8.17',
71 silly addNameRange     '3.9.3',
71 silly addNameRange     '3.8.18',
71 silly addNameRange     '3.9.4',
71 silly addNameRange     '3.8.19',
71 silly addNameRange     '3.9.5',
71 silly addNameRange     '3.8.20',
71 silly addNameRange     '3.9.6',
71 silly addNameRange     '3.8.21',
71 silly addNameRange     '3.9.7',
71 silly addNameRange     '3.8.22',
71 silly addNameRange     '4.0.0-rc0',
71 silly addNameRange     '4.0.0-rc1',
71 silly addNameRange     '3.8.23',
71 silly addNameRange     '4.0.0-rc2',
71 silly addNameRange     '3.8.24',
71 silly addNameRange     '4.0.0-rc3',
71 silly addNameRange     '3.8.25',
71 silly addNameRange     '4.0.0-rc4',
71 silly addNameRange     '4.0.0',
71 silly addNameRange     '4.0.1',
71 silly addNameRange     '3.8.26',
71 silly addNameRange     '3.8.27',
71 silly addNameRange     '4.0.2',
71 silly addNameRange     '3.8.28',
71 silly addNameRange     '4.0.3',
71 silly addNameRange     '3.8.29',
71 silly addNameRange     '4.0.4',
71 silly addNameRange     '3.8.30',
71 silly addNameRange     '4.0.5',
71 silly addNameRange     '3.8.31',
71 silly addNameRange     '4.0.6',
71 silly addNameRange     '3.8.33',
71 silly addNameRange     '4.0.7',
71 silly addNameRange     '3.8.34',
71 silly addNameRange     '4.0.8',
71 silly addNameRange     '4.1.0',
71 silly addNameRange     '4.1.1',
71 silly addNameRange     '4.1.2',
71 silly addNameRange     '3.8.35',
71 silly addNameRange     '4.1.3' ] ]
72 verbose addNamed [ 'mongoose', '3.8.35' ]
73 verbose addNamed [ '3.8.35', '3.8.35' ]
74 silly lockFile 6477b44e-mongoose-3-8-35 mongoose@3.8.35
75 verbose lock mongoose@3.8.35 /home/amnesia/.npm/6477b44e-mongoose-3-8-35.lock
76 silly lockFile 6477b44e-mongoose-3-8-35 mongoose@3.8.35
77 silly lockFile 6477b44e-mongoose-3-8-35 mongoose@3.8.35
78 silly lockFile 3ec00dd8-mongoose-3-8-21 mongoose@~3.8.21
79 silly lockFile 3ec00dd8-mongoose-3-8-21 mongoose@~3.8.21
80 http 404 https://registry.npmjs.org/express-sesion
81 error TypeError: Cannot call method 'match' of undefined
81 error     at RegClient.<anonymous> (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:119:29)
81 error     at cb (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:158:9)
81 error     at RegClient.<anonymous> (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:252:14)
81 error     at Request.self.callback (/usr/lib/nodejs/request/index.js:148:22)
81 error     at Request.EventEmitter.emit (events.js:98:17)
81 error     at Request.<anonymous> (/usr/lib/nodejs/request/index.js:896:14)
81 error     at Request.EventEmitter.emit (events.js:117:20)
81 error     at IncomingMessage.<anonymous> (/usr/lib/nodejs/request/index.js:847:12)
81 error     at IncomingMessage.EventEmitter.emit (events.js:117:20)
81 error     at _stream_readable.js:920:16
82 error If you need help, you may report this log at:
82 error     <http://github.com/isaacs/npm/issues>
82 error or email it to:
82 error     <npm-@googlegroups.com>
83 error System Linux 3.16.0-30-generic
84 error command "/usr/bin/nodejs" "/usr/bin/npm" "install"
85 error cwd /home/amnesia/Desktop/GPS
86 error node -v v0.10.25
87 error npm -v 1.3.10
88 error type non_object_property_call
89 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
@jacka92 I believe your best first step would be to [upgrade `npm`](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm), since `npm@1.3` support ended months ago.

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some issues. If this is still a problem, can you please reply and let us know? We’ll be happy to reopen if necessary.
