### ISSUE TITLE
Shrinkwrap says same dependency is both missing and extraneous

### ISSUE THREAD

**Issue by triblondon** [npm/npm#9322]
Create package.json containing:

```json
{
  "dependencies": {
    "semverionizer-parser": "git://github.com/orangemug/semversionizer-parser.git#v0.2.0"
  }
}
```

Run `npm install` then `npm shrinkwrap`.  Shrinkwrap output contains:

```
npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! missing: semverionizer-parser@git://github.com/orangemug/semversionizer-parser.git#v0.2.0, required by @
npm ERR! extraneous: semversionizer-parser@0.2.0 /tmp/test/node_modules/semversionizer-parser
```

npm-debug:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'shrinkwrap' ]
2 info using npm@2.1.6
3 info using node@v0.12.2
4 verbose stack Error: Problems were encountered
4 verbose stack Please correct and try again.
4 verbose stack missing: semverionizer-parser@git://github.com/orangemug/semversionizer-parser.git#v0.2.0, required by @
4 verbose stack extraneous: semversionizer-parser@0.2.0 /Users/andrew.betts/sandboxes/local/polytest/node_modules/semversionizer-parser
4 verbose stack     at shrinkwrap_ (/usr/local/lib/node_modules/npm/lib/shrinkwrap.js:31:15)
4 verbose stack     at /usr/local/lib/node_modules/npm/lib/shrinkwrap.js:25:5
4 verbose stack     at /usr/local/lib/node_modules/npm/lib/ls.js:46:30
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js:138:5
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js:251:14
4 verbose stack     at cb (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js:251:14
4 verbose stack     at cb (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js:251:14
4 verbose stack     at asyncMap (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:27:18)
5 verbose cwd /Users/andrew.betts/sandboxes/local/polytest
6 error Darwin 14.5.0
7 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "shrinkwrap"
8 error node v0.12.2
9 error npm  v2.1.6
10 error Problems were encountered
10 error Please correct and try again.
10 error missing: semverionizer-parser@git://github.com/orangemug/semversionizer-parser.git#v0.2.0, required by @
10 error extraneous: semversionizer-parser@0.2.0 /Users/andrew.betts/sandboxes/local/polytest/node_modules/semversionizer-parser
11 error If you need help, you may report this error at:
11 error     <http://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
```

**Comment by othiym23** [comment]
There's a typo in `package.json` -- `semverionizer-parser` vs the dependency actually being named `semverSionizer-parser`. Correct that and all should be well. Good luck!

**Comment by triblondon** [comment]
Ah yes.

Ignore me.  Carry on.
