### ISSUE TITLE
Problems Downloading Gulp

### ISSUE THREAD

**Issue by mycra-craig** [npm/npm#9382]
/Users/craig/npm-debug.log

I am experiencing this error when trying to download gulp
```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'install', '-g', 'gulp' ]
2 info using npm@2.11.3
3 info using node@v0.12.7
4 verbose install initial load of /usr/local/lib/package.json
5 verbose readDependencies loading dependencies from /usr/local/lib/package.json
6 silly cache add args [ 'gulp', null ]
7 verbose cache add spec gulp
8 silly cache add parsed spec { raw: 'gulp',
8 silly cache add   scope: null,
8 silly cache add   name: 'gulp',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: '*',
8 silly cache add   type: 'range' }
9 silly addNamed gulp@*
10 verbose addNamed "*" is a valid semver range for gulp
11 silly addNameRange { name: 'gulp', range: '*', hasData: false }
12 silly mapToRegistry name gulp
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/gulp
16 verbose addNameRange registry:https://registry.npmjs.org/gulp not in flight; fetching
17 verbose request uri https://registry.npmjs.org/gulp
18 verbose request no auth needed
19 info attempt registry request try #1 at 6:14:19 PM
20 verbose request id a89247c60427060f
21 verbose etag "EIQ1K3KVWL2IWK1GWRMMTBABN"
22 http request GET https://registry.npmjs.org/gulp
23 http 304 https://registry.npmjs.org/gulp
24 silly get cb [ 304,
24 silly get   { date: 'Sun, 23 Aug 2015 23:14:19 GMT',
24 silly get     via: '1.1 varnish',
24 silly get     'cache-control': 'max-age=60',
24 silly get     etag: '"EIQ1K3KVWL2IWK1GWRMMTBABN"',
24 silly get     age: '52',
24 silly get     connection: 'keep-alive',
24 silly get     'x-served-by': 'cache-sjc3127-SJC',
24 silly get     'x-cache': 'HIT',
24 silly get     'x-cache-hits': '1',
24 silly get     'x-timer': 'S1440371659.845337,VS0,VE0',
24 silly get     vary: 'Accept' } ]
25 verbose etag https://registry.npmjs.org/gulp from cache
26 verbose get saving gulp to /Users/craig/.npm/registry.npmjs.org/gulp/.cache.json
27 silly addNameRange number 2 { name: 'gulp', range: '*', hasData: true }
28 silly addNameRange versions [ 'gulp',
28 silly addNameRange   [ '0.0.1',
28 silly addNameRange     '0.0.2',
28 silly addNameRange     '0.0.3',
28 silly addNameRange     '0.0.4',
28 silly addNameRange     '0.0.5',
28 silly addNameRange     '0.0.7',
28 silly addNameRange     '0.0.8',
28 silly addNameRange     '0.0.9',
28 silly addNameRange     '0.1.0',
28 silly addNameRange     '0.2.0',
28 silly addNameRange     '1.0.0',
28 silly addNameRange     '1.1.0',
28 silly addNameRange     '1.2.0',
28 silly addNameRange     '1.2.1',
28 silly addNameRange     '2.0.0',
28 silly addNameRange     '2.0.1',
28 silly addNameRange     '2.1.0',
28 silly addNameRange     '2.2.0',
28 silly addNameRange     '2.3.0',
28 silly addNameRange     '2.4.0',
28 silly addNameRange     '2.4.1',
28 silly addNameRange     '2.6.0',
28 silly addNameRange     '2.6.1',
28 silly addNameRange     '2.7.0',
28 silly addNameRange     '3.0.0',
28 silly addNameRange     '3.1.1',
28 silly addNameRange     '3.1.2',
28 silly addNameRange     '3.1.3',
28 silly addNameRange     '3.1.4',
28 silly addNameRange     '3.2.0',
28 silly addNameRange     '3.2.1',
28 silly addNameRange     '3.2.2',
28 silly addNameRange     '3.2.3',
28 silly addNameRange     '3.2.4',
28 silly addNameRange     '3.2.5',
28 silly addNameRange     '3.3.0',
28 silly addNameRange     '3.3.1',
28 silly addNameRange     '3.3.2',
28 silly addNameRange     '3.3.4',
28 silly addNameRange     '3.4.0',
28 silly addNameRange     '3.5.0',
28 silly addNameRange     '3.5.1',
28 silly addNameRange     '3.5.2',
28 silly addNameRange     '3.5.5',
28 silly addNameRange     '3.5.6',
28 silly addNameRange     '3.6.0',
28 silly addNameRange     '3.6.1',
28 silly addNameRange     '3.6.2',
28 silly addNameRange     '3.7.0',
28 silly addNameRange     '3.8.0',
28 silly addNameRange     '3.8.1',
28 silly addNameRange     '3.8.2',
28 silly addNameRange     '3.8.3',
28 silly addNameRange     '3.8.4',
28 silly addNameRange     '3.8.5',
28 silly addNameRange     '3.8.6',
28 silly addNameRange     '3.8.7',
28 silly addNameRange     '3.8.8',
28 silly addNameRange     '3.8.9',
28 silly addNameRange     '3.8.10',
28 silly addNameRange     '3.8.11',
28 silly addNameRange     '3.9.0' ] ]
29 silly addNamed gulp@3.9.0
30 verbose addNamed "3.9.0" is a plain semver version for gulp
31 silly cache afterAdd gulp@3.9.0
32 verbose afterAdd /Users/craig/.npm/gulp/3.9.0/package/package.json not in flight; writing
33 verbose afterAdd /Users/craig/.npm/gulp/3.9.0/package/package.json written
34 silly install resolved [ { name: 'gulp',
34 silly install resolved     description: 'The streaming build system',
34 silly install resolved     version: '3.9.0',
34 silly install resolved     homepage: 'http://gulpjs.com',
34 silly install resolved     repository: { type: 'git', url: 'git+https://github.com/gulpjs/gulp.git' },
34 silly install resolved     author:
34 silly install resolved      { name: 'Fractal',
34 silly install resolved        email: 'contact@wearefractal.com',
34 silly install resolved        url: 'http://wearefractal.com/' },
34 silly install resolved     tags: [ 'build', 'stream', 'system', 'make', 'tool', 'asset', 'pipeline' ],
34 silly install resolved     files: [ 'index.js', 'lib', 'bin', 'completion' ],
34 silly install resolved     bin: { gulp: './bin/gulp.js' },
34 silly install resolved     man: [ 'gulp.1' ],
34 silly install resolved     dependencies:
34 silly install resolved      { archy: '^1.0.0',
34 silly install resolved        chalk: '^1.0.0',
34 silly install resolved        deprecated: '^0.0.1',
34 silly install resolved        'gulp-util': '^3.0.0',
34 silly install resolved        interpret: '^0.6.2',
34 silly install resolved        liftoff: '^2.1.0',
34 silly install resolved        minimist: '^1.1.0',
34 silly install resolved        orchestrator: '^0.3.0',
34 silly install resolved        'pretty-hrtime': '^1.0.0',
34 silly install resolved        semver: '^4.1.0',
34 silly install resolved        tildify: '^1.0.0',
34 silly install resolved        v8flags: '^2.0.2',
34 silly install resolved        'vinyl-fs': '^0.3.0' },
34 silly install resolved     devDependencies:
34 silly install resolved      { coveralls: '^2.7.0',
34 silly install resolved        'graceful-fs': '^3.0.0',
34 silly install resolved        istanbul: '^0.3.0',
34 silly install resolved        jscs: '~1.12.0',
34 silly install resolved        jshint: '^2.5.0',
34 silly install resolved        'jshint-stylish': '^1.0.0',
34 silly install resolved        'marked-man': '^0.1.3',
34 silly install resolved        mkdirp: '^0.5.0',
34 silly install resolved        mocha: '^2.0.1',
34 silly install resolved        'mocha-lcov-reporter': '^0.0.1',
34 silly install resolved        q: '^1.0.0',
34 silly install resolved        rimraf: '^2.2.5',
34 silly install resolved        should: '^5.0.1' },
34 silly install resolved     scripts:
34 silly install resolved      { prepublish: 'marked-man --name gulp docs/CLI.md > gulp.1',
34 silly install resolved        lint: 'jshint lib bin test index.js --reporter node_modules/jshint-stylish/stylish.js --exclude node_modules && jscs lib bin test index.js',
34 silly install resolved        test: 'npm run-script lint && mocha --reporter spec',
34 silly install resolved        coveralls: 'istanbul cover _mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | coveralls && rm -rf ./coverage' },
34 silly install resolved     engines: { node: '>= 0.9' },
34 silly install resolved     license: 'MIT',
34 silly install resolved     gitHead: '657213a52d5e9c19b85df6a42f76341a98c08ae8',
34 silly install resolved     bugs: { url: 'https://github.com/gulpjs/gulp/issues' },
34 silly install resolved     _id: 'gulp@3.9.0',
34 silly install resolved     _shasum: 'cf1fba4cb558bb8c6ae6c9613f583ae2620d214a',
34 silly install resolved     _from: 'gulp@*',
34 silly install resolved     _npmVersion: '2.8.3',
34 silly install resolved     _nodeVersion: '0.10.36',
34 silly install resolved     _npmUser: { name: 'phated', email: 'blaine@iceddev.com' },
34 silly install resolved     maintainers: [ [Object], [Object] ],
34 silly install resolved     dist:
34 silly install resolved      { shasum: 'cf1fba4cb558bb8c6ae6c9613f583ae2620d214a',
34 silly install resolved        tarball: 'http://registry.npmjs.org/gulp/-/gulp-3.9.0.tgz' },
34 silly install resolved     directories: {},
34 silly install resolved     _resolved: 'https://registry.npmjs.org/gulp/-/gulp-3.9.0.tgz',
34 silly install resolved     readme: 'ERROR: No README data found!' } ]
35 info install gulp@3.9.0 into /usr/local/lib
36 info installOne gulp@3.9.0
37 verbose installOne of gulp to /usr/local/lib not in flight; installing
38 warn locking Error: EACCES, open '/Users/craig/.npm/_locks/gulp-709d00e5d169ceb3.lock'
38 warn locking     at Error (native)
38 warn locking  /Users/craig/.npm/_locks/gulp-709d00e5d169ceb3.lock failed { [Error: EACCES, open '/Users/craig/.npm/_locks/gulp-709d00e5d169ceb3.lock']
38 warn locking   errno: -13,
38 warn locking   code: 'EACCES',
38 warn locking   path: '/Users/craig/.npm/_locks/gulp-709d00e5d169ceb3.lock' }
39 verbose stack Error: Attempt to unlock /usr/local/lib/node_modules/gulp, which hasn't been locked
39 verbose stack     at unlock (/usr/local/lib/node_modules/npm/lib/utils/locker.js:66:11)
39 verbose stack     at cb (/usr/local/lib/node_modules/npm/lib/install.js:1017:5)
39 verbose stack     at /usr/local/lib/node_modules/npm/lib/install.js:1021:20
39 verbose stack     at /usr/local/lib/node_modules/npm/lib/utils/locker.js:40:9
39 verbose stack     at cb (/usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:149:38)
39 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:177:38
39 verbose stack     at FSReqWrap.oncomplete (fs.js:95:15)
40 verbose cwd /Users/craig
41 error Darwin 14.4.0
42 error argv "node" "/usr/local/bin/npm" "install" "-g" "gulp"
43 error node v0.12.7
44 error npm  v2.11.3
45 error Attempt to unlock /usr/local/lib/node_modules/gulp, which hasn't been locked
46 error If you need help, you may report this error at:
46 error     <https://github.com/npm/npm/issues>
47 verbose exit [ 1, true ]
```

I am wondering what I should do next

**Comment by KenanY** [comment]
@mycra-craig Looks like you don't have permission to modify `npm`'s cache directory, for whatever reason. Could you try running the following?:

``` sh
sudo chown -R $(whoami) "$HOME/.npm"
```

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some issues. If this is still a problem, can you please reply and let us know? We’ll be happy to reopen if necessary.
