### ISSUE TITLE
Cannot find module './permuteDomain'

### ISSUE THREAD

**Issue by saigequn** [npm/npm#9392]
```
Error: Cannot find module './permuteDomain'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/node_modules/tough-cookie/lib/memstore.js:33:21)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "cheerio"
npm ERR! node v0.12.7
npm ERR! npm  v2.7.4
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module './permuteDomain'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

**Comment by snopeks** [comment]
Hi @saigequn, it looks like your version of npm is broken, we recommend you completely remove and reinstall node.js (whichever way you previously installed it) to get npm back up and running. Could you give that a try and let me know what the results are? Thanks!

**Comment by snopeks** [comment]
@saigequn closing since we haven't heard back from you. Let me know if you're still running into this issue, we'll be happy to keep investigating.
