### ISSUE TITLE
npm error when trying to install ios-sim

### ISSUE THREAD

**Issue by charliebolland** [npm/npm#9393]
Hey,

Im trying to run an ios simulator on my mac.

i do this command - `cordova emulate ios`
I get the response in terminal: 
```
Running command: /Users/Charlie/techbay/platforms/ios/cordova/run --emulator
ios-sim was not found. Please download, build and install version 3.0.0 or greater from https://github.com/phonegap/ios-sim into your path, or do 'npm install -g ios-sim'
Error: /Users/Charlie/techbay/platforms/ios/cordova/run: Command failed with exit code 2
    at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:139:23)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
```

So i try and do - `npm install -g ios-sim`

ios-sim 
and then i get this error: 

```
npm WARN locking Error: EACCES, open '/Users/Charlie/.npm/_locks/ios-sim-4180156ee87e38f3.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/Charlie/.npm/_locks/ios-sim-4180156ee87e38f3.lock failed { [Error: EACCES, open '/Users/Charlie/.npm/_locks/ios-sim-4180156ee87e38f3.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/Charlie/.npm/_locks/ios-sim-4180156ee87e38f3.lock' }
npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "ios-sim"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! Attempt to unlock /Users/Charlie/techbay/node_modules/ios-sim, which hasn't been locked
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Charlie/techbay/npm-debug.log
```

Here is the contents of npm-debug.log :

```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'install', '-g', 'ios-sim' ]
2 info using npm@2.11.3
3 info using node@v0.12.7
4 verbose install initial load of /usr/local/lib/package.json
5 verbose readDependencies loading dependencies from /usr/local/lib/package.json
6 silly cache add args [ 'ios-sim', null ]
7 verbose cache add spec ios-sim
8 silly cache add parsed spec { raw: 'ios-sim',
8 silly cache add   scope: null,
8 silly cache add   name: 'ios-sim',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: '*',
8 silly cache add   type: 'range' }
9 silly addNamed ios-sim@*
10 verbose addNamed "*" is a valid semver range for ios-sim
11 silly addNameRange { name: 'ios-sim', range: '*', hasData: false }
12 silly mapToRegistry name ios-sim
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/ios-sim
16 verbose addNameRange registry:https://registry.npmjs.org/ios-sim not in flight; fetching
17 verbose request uri https://registry.npmjs.org/ios-sim
18 verbose request no auth needed
19 info attempt registry request try #1 at 2:25:29 PM
20 verbose request id 99bb8cff427fa975
21 verbose etag "A2RR1AGYM7090JA29QJV90SII"
22 http request GET https://registry.npmjs.org/ios-sim
23 http 304 https://registry.npmjs.org/ios-sim
24 silly get cb [ 304,
24 silly get   { date: 'Mon, 24 Aug 2015 13:25:30 GMT',
24 silly get     via: '1.1 varnish',
24 silly get     'cache-control': 'max-age=60',
24 silly get     etag: '"A2RR1AGYM7090JA29QJV90SII"',
24 silly get     age: '0',
24 silly get     connection: 'keep-alive',
24 silly get     'x-served-by': 'cache-ams4122-AMS',
24 silly get     'x-cache': 'HIT',
24 silly get     'x-cache-hits': '1',
24 silly get     'x-timer': 'S1440422730.132997,VS0,VE166',
24 silly get     vary: 'Accept' } ]
25 verbose etag https://registry.npmjs.org/ios-sim from cache
26 verbose get saving ios-sim to /Users/Charlie/.npm/registry.npmjs.org/ios-sim/.cache.json
27 silly addNameRange number 2 { name: 'ios-sim', range: '*', hasData: true }
28 silly addNameRange versions [ 'ios-sim',
28 silly addNameRange   [ '1.8.0',
28 silly addNameRange     '1.8.1',
28 silly addNameRange     '1.8.2',
28 silly addNameRange     '1.9.0',
28 silly addNameRange     '2.0.0',
28 silly addNameRange     '2.0.1',
28 silly addNameRange     '3.0.0',
28 silly addNameRange     '3.1.0',
28 silly addNameRange     '3.1.1',
28 silly addNameRange     '4.1.0',
28 silly addNameRange     '4.1.1',
28 silly addNameRange     '3.2.0' ] ]
29 silly addNamed ios-sim@4.1.1
30 verbose addNamed "4.1.1" is a plain semver version for ios-sim
31 silly cache afterAdd ios-sim@4.1.1
32 verbose afterAdd /Users/Charlie/.npm/ios-sim/4.1.1/package/package.json not in flight; writing
33 verbose afterAdd /Users/Charlie/.npm/ios-sim/4.1.1/package/package.json written
34 silly install resolved [ { name: 'ios-sim',
34 silly install resolved     version: '4.1.1',
34 silly install resolved     os: [ 'darwin' ],
34 silly install resolved     preferGlobal: 'true',
34 silly install resolved     description: 'launch iOS apps into the iOS Simulator from the command line (Xcode 6.0+)',
34 silly install resolved     main: 'ios-sim',
34 silly install resolved     repository:
34 silly install resolved      { type: 'git',
34 silly install resolved        url: 'git+https://github.com/phonegap/ios-sim.git' },
34 silly install resolved     engines: { node: '>=0.10.0' },
34 silly install resolved     keywords: [ 'ios-sim', 'iOS Simulator' ],
34 silly install resolved     bin: { 'ios-sim': './bin/ios-sim' },
34 silly install resolved     bugs: { url: 'https://github.com/phonegap/ios-sim/issues' },
34 silly install resolved     author: { name: 'Shazron Abdullah' },
34 silly install resolved     license: 'MIT',
34 silly install resolved     dependencies: { simctl: '^0.0.6', nopt: '1.0.9', 'bplist-parser': '^0.0.6' },
34 silly install resolved     gitHead: 'a0f2e2d8e4deca377b70041f3cbb2a529f6fa5e5',
34 silly install resolved     homepage: 'https://github.com/phonegap/ios-sim',
34 silly install resolved     _id: 'ios-sim@4.1.1',
34 silly install resolved     scripts: {},
34 silly install resolved     _shasum: '3458eca5e5d5e97ae11f19e35f6768584dcbf7cd',
34 silly install resolved     _from: 'ios-sim@*',
34 silly install resolved     _npmVersion: '2.5.1',
34 silly install resolved     _nodeVersion: '0.12.0',
34 silly install resolved     _npmUser: { name: 'shazron', email: 'shazron@gmail.com' },
34 silly install resolved     maintainers: [ [Object], [Object], [Object] ],
34 silly install resolved     dist:
34 silly install resolved      { shasum: '3458eca5e5d5e97ae11f19e35f6768584dcbf7cd',
34 silly install resolved        tarball: 'http://registry.npmjs.org/ios-sim/-/ios-sim-4.1.1.tgz' },
34 silly install resolved     directories: {},
34 silly install resolved     _resolved: 'https://registry.npmjs.org/ios-sim/-/ios-sim-4.1.1.tgz',
34 silly install resolved     readme: 'ERROR: No README data found!' } ]
35 info install ios-sim@4.1.1 into /usr/local/lib
36 info installOne ios-sim@4.1.1
37 verbose installOne of ios-sim to /usr/local/lib not in flight; installing
38 warn locking Error: EACCES, open '/Users/Charlie/.npm/_locks/ios-sim-3bb56db538048d2f.lock'
38 warn locking     at Error (native)
38 warn locking  /Users/Charlie/.npm/_locks/ios-sim-3bb56db538048d2f.lock failed { [Error: EACCES, open '/Users/Charlie/.npm/_locks/ios-sim-3bb56db538048d2f.lock']
38 warn locking   errno: -13,
38 warn locking   code: 'EACCES',
38 warn locking   path: '/Users/Charlie/.npm/_locks/ios-sim-3bb56db538048d2f.lock' }
39 verbose stack Error: Attempt to unlock /usr/local/lib/node_modules/ios-sim, which hasn't been locked
39 verbose stack     at unlock (/usr/local/lib/node_modules/npm/lib/utils/locker.js:66:11)
39 verbose stack     at cb (/usr/local/lib/node_modules/npm/lib/install.js:1017:5)
39 verbose stack     at /usr/local/lib/node_modules/npm/lib/install.js:1021:20
39 verbose stack     at /usr/local/lib/node_modules/npm/lib/utils/locker.js:40:9
39 verbose stack     at cb (/usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:149:38)
39 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/lockfile/lockfile.js:177:38
39 verbose stack     at FSReqWrap.oncomplete (fs.js:95:15)
40 verbose cwd /Users/Charlie/techbay
41 error Darwin 14.4.0
42 error argv "node" "/usr/local/bin/npm" "install" "-g" "ios-sim"
43 error node v0.12.7
44 error npm  v2.11.3
45 error Attempt to unlock /usr/local/lib/node_modules/ios-sim, which hasn't been locked
46 error If you need help, you may report this error at:
46 error     <https://github.com/npm/npm/issues>
47 verbose exit [ 1, true ]
 ```

Any help would be muchly appreciated!

Many Thanks, Charlie :)

**Comment by KenanY** [comment]
@charliebolland Looks like a permissions issue to me. For whatever reason, you do not have permission to modify `npm`'s cache directory. Could you try?:

``` sh
sudo chown -R $(whoami) "$HOME/.npm"
```

You will also need to use `sudo` when installing global modules because they are currently being installed to `/usr/local`, which by default (on most systems IIRC) is not modifiable by regular users.

**Comment by charliebolland** [comment]
Hey Kenan,

Thanks! It worked. 

Charlie :)

**Comment by othiym23** [comment]
Closing as resolved! Thanks for the assist, @KenanY!
