### ISSUE TITLE
Unable to completely unpublish a package I published

### ISSUE THREAD

**Issue by lloydwatkin** [npm/npm#9400]
```
[watkinll@watkinll-1a-i-ae6f5149]~% npm unpublish isizwe-wifi-chat --force
npm WARN using --force I sure hope you know what you are doing.
npm ERR! Error: You do not have permission to publish 'isizwe-wifi-chat'. Are you logged in as the correct user? : isizwe-wifi-chat/-rev/2-1afaf836b8d1000fa32f00ea3086412b
npm ERR!     at RegClient.<anonymous> (/local/apollo/package/local_1/Linux-2.6c2.5-x86_64/NodeJS/NodeJS-489.0-0/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:308:14)
npm ERR!     at Request._callback (/local/apollo/package/local_1/Linux-2.6c2.5-x86_64/NodeJS/NodeJS-489.0-0/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:246:65)
npm ERR!     at Request.self.callback (/local/apollo/package/local_1/Linux-2.6c2.5-x86_64/NodeJS/NodeJS-489.0-0/lib/node_modules/npm/node_modules/request/request.js:236:22)
npm ERR!     at Request.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/local/apollo/package/local_1/Linux-2.6c2.5-x86_64/NodeJS/NodeJS-489.0-0/lib/node_modules/npm/node_modules/request/request.js:1142:14)
npm ERR!     at Request.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/local/apollo/package/local_1/Linux-2.6c2.5-x86_64/NodeJS/NodeJS-489.0-0/lib/node_modules/npm/node_modules/request/request.js:1096:12)
npm ERR!     at IncomingMessage.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:944:16
npm ERR!     at process._tickCallback (node.js:448:13)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.2.45-0.6.acc.624.45.283.amzn1acc.x86_64
npm ERR! command "/apollo/env/WDETools/bin/node" "/apollo/env/WDETools/bin/npm" "unpublish" "isizwe-wifi-chat" "--force"
npm ERR! cwd /local/home/watkinll
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /local/home/watkinll/npm-debug.log
npm ERR! not ok code 0
```

Here's the package page https://www.npmjs.com/package/isizwe-wifi-chat

Could this be a caching issue on the website? I originally tried to remove the single version rather than excluding the version number so maybe its already removed?

**Comment by KenanY** [comment]
@lloydwatkin I'm getting 404's on both the registry and the website for this package, so problem solved?

**Comment by lloydwatkin** [comment]
@KenanY looks so, just caching. Thanks!
