### ISSUE TITLE
npm install -g gulp TypeError: undefined is not a function node v0.12.4 npm  v2.10.1

### ISSUE THREAD

**Issue by wKrawiec** [npm/npm#9406]
I get this error while doin anything npm based. I tried cache clean - it runs the same error. What shall I do. Thanks in advance

C:\Users\Wojtz\Desktop\treehouse-gulp-basics-master>npm install -g gulp
TypeError: undefined is not a function
    at new RequestJar (C:\Program Files\nodejs\node_modules\npm\node_modules\request\lib\cookies.js:22:15)
    at Object.exports.jar (C:\Program Files\nodejs\node_modules\npm\node_modules\request\lib\cookies.js:38:10)
    at Object.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:35:31)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\index.js:142:19)
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "gulp"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1

npm ERR! undefined is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

C:\Users\Wojtz\Desktop\treehouse-gulp-basics-master>

**Comment by joecue** [comment]
I'm also receiving a similiar error message while trying to install gulp.  I posted an issue at the gulp project, https://github.com/gulpjs/gulp/issues/1214 and all I got back was a reply that my npm is broken and I need to update.  Yet when I run npm update it doesn't do anything.  

I can run grunt just fine, but I can't install gulp.

**Comment by joecue** [comment]
I was finally able to run the gulp install, but I had to run "npm cache clean" then "npm update" then I was able to install gulp globally.  Interestingly I had to run "npm cache clean" before I could install gulp into my project.

**Comment by wKrawiec** [comment]
Thank you @joecue.. I've ended up with reinstaling whole node and npm as the cache clean and clear were not working. Fortunately there is nothing that good old wipe doesn't fix :)

**Comment by wKrawiec** [comment]
I am closing there issue with a three solutions for the future:
-"npm cache clear" 
-"npm cache clean"
-reinstalling node and npm 

Hope that will help someone in the future.
