### ISSUE TITLE
Failed PUT 413 on npm publish

### ISSUE THREAD

**Issue by bhelx** [npm/npm#9439]
Trying to publish a new library. I am logged in. I am seeing a (413 Request Entity Too Large) error from nginx. My repo doesn't seem too big (< 1 MB)

```
npm ERR! registry error parsing json
npm ERR! publish Failed PUT 413
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/Users/ben/.nvm/versions/node/v0.12.7/bin/npm" "publish"
npm ERR! node v0.12.7
npm ERR! npm  v2.14.1

npm ERR! Unexpected token <
npm ERR! <html>
npm ERR! <head><title>413 Request Entity Too Large</title></head>
npm ERR! <body bgcolor="white">
npm ERR! <center><h1>413 Request Entity Too Large</h1></center>
npm ERR! <hr><center>nginx/1.1.19</center>
npm ERR! </body>
npm ERR! </html>
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ben/code/mitie/npm-debug.log
```

My debug log:

```
0 info it worked if it ends with ok
1 verbose cli [ 'node',
1 verbose cli   '/Users/ben/.nvm/versions/node/v0.12.7/bin/npm',
1 verbose cli   'publish' ]
2 info using npm@2.14.1
3 info using node@v0.12.7
4 verbose publish [ '.' ]
5 silly cache add args [ '.', null ]
6 verbose cache add spec .
7 silly cache add parsed spec { raw: '.',
7 silly cache add   scope: null,
7 silly cache add   name: null,
7 silly cache add   rawSpec: '.',
7 silly cache add   spec: '/Users/ben/code/mitie',
7 silly cache add   type: 'directory' }
8 verbose addLocalDirectory /Users/ben/.npm/mitie/1.0.0/package.tgz not in flight; packing
9 verbose tar pack [ '/Users/ben/.npm/mitie/1.0.0/package.tgz',
9 verbose tar pack   '/Users/ben/code/mitie' ]
10 verbose tarball /Users/ben/.npm/mitie/1.0.0/package.tgz
11 verbose folder /Users/ben/code/mitie
12 info prepublish mitie@1.0.0
13 verbose addLocalTarball adding from inside cache /Users/ben/.npm/mitie/1.0.0/package.tgz
14 silly cache afterAdd mitie@1.0.0
15 verbose afterAdd /Users/ben/.npm/mitie/1.0.0/package/package.json not in flight; writing
16 verbose afterAdd /Users/ben/.npm/mitie/1.0.0/package/package.json written
17 silly publish { name: 'mitie',
17 silly publish   version: '1.0.0',
17 silly publish   description: 'Node bindings for MIT Information Extraction https://github.com/mit-nlp/MITIE',
17 silly publish   gypfile: true,
17 silly publish   main: 'index.js',
17 silly publish   repository: { type: 'git', url: 'git+ssh://git@github.com/bhelx/mitie.git' },
17 silly publish   keywords: [ 'mitie', 'nlp', 'ner' ],
17 silly publish   scripts:
17 silly publish    { test: 'node_modules/mocha/bin/mocha',
17 silly publish      install: 'node-gyp rebuild' },
17 silly publish   author: { name: 'bhelx' },
17 silly publish   license: 'MIT',
17 silly publish   dependencies: { bindings: '~1.2.1', nan: '^2.0.0' },
17 silly publish   devDependencies: { mocha: '~2.2.5' },
17 silly publish   readme: '## MITIE\n\nThis project is a node binding for the [MIT Information Extraction library](https://github.com/mit-nlp/MITIE). It\'s written in C++ and js.\n\nI was most interested in using the [Named Entity Recognition](https://en.wikipedia.org/wiki/Named-entity_recognition) extractor so that\'s all that\'s been implemented so far.\n\n## Using\n\nThe quickest way to get the mitie dependency is with homebrew:\n\n```\nbrew install mitie\n```\n\nYou can install with npm on the command line or in your `package.json`:\n\n```\nnpm install mitie --save\n```\n\nThe API looks something like this:\n\n```javascript\nvar mitie = require(\'mitie\');\n\n// Point it at a ner model .dat file\n// You can also find where to get these on the main MIT project repo\n\nvar nerFile = \'/usr/local/Cellar/mitie/0.4/share/MITIE-models/english/ner_model.dat\';\nvar extractor = new mitie.EntityExtractor(nerFile);\n\n// Feed in some data to the predict method\n\nvar data = "Barack Obama visited New Orleans today for the anniversary of Hurricane Katrina."\nvar results = extractor.predict(data);\n\n/**\n * results => {\n *  tags:\n *    [ { tagNumber: 0,\n *        score: 1.0957487452879051,\n *       tagType: \'PERSON\',\n *       tokens: \'Barack Obama\' },\n *      { tagNumber: 1,\n *        score: 0.8764343236070008,\n *        tagType: \'LOCATION\',\n *        tokens: \'New Orleans\' } ] }\n */\n```\n\n## Testing\n\nInstall with development deps:\n\n```\nnpm install --dev\n```\n\nRun mocha tests pointing to a ner model:\n\n```\nNER_MODEL=/usr/local/Cellar/mitie/0.4/share/MITIE-models/english/ner_model.dat npm test\n```\n\n## TODO\n\n* Would like to implement the rest of the library (implement binary relation detection)\n* API could be cleaner for ner extractor, should allow passing a file path for the data\n* Support other platforms, will probably not compile on anything other than OS X for now\n\n',
17 silly publish   readmeFilename: 'README.md',
17 silly publish   gitHead: '0df2546367ad611eecdc2723d32f24266d6c9f71',
17 silly publish   bugs: { url: 'https://github.com/bhelx/mitie/issues' },
17 silly publish   homepage: 'https://github.com/bhelx/mitie#readme',
17 silly publish   _id: 'mitie@1.0.0',
17 silly publish   _shasum: 'bb8e21b447abea62b6cb3cad30cae8abb6cc035c',
17 silly publish   _from: '.' }
18 verbose getPublishConfig undefined
19 silly mapToRegistry name mitie
20 silly mapToRegistry using default registry
21 silly mapToRegistry registry http://npm.recurly.net/
22 silly mapToRegistry uri http://npm.recurly.net/mitie
23 verbose publish registryBase http://npm.recurly.net/
24 silly publish uploading /Users/ben/.npm/mitie/1.0.0/package.tgz
25 verbose request uri http://npm.recurly.net/mitie
26 verbose request sending authorization for write operation
27 info attempt registry request try #1 at 3:15:42 AM
28 verbose request using bearer token for auth
29 verbose request id 9693bfe01fb391f9
30 http request PUT http://npm.recurly.net/mitie
31 http 413 http://npm.recurly.net/mitie
32 verbose bad json <html>
32 verbose bad json <head><title>413 Request Entity Too Large</title></head>
32 verbose bad json <body bgcolor="white">
32 verbose bad json <center><h1>413 Request Entity Too Large</h1></center>
32 verbose bad json <hr><center>nginx/1.1.19</center>
32 verbose bad json </body>
32 verbose bad json </html>
33 error registry error parsing json
34 verbose headers { server: 'nginx/1.1.19',
34 verbose headers   date: 'Sat, 29 Aug 2015 10:20:20 GMT',
34 verbose headers   'content-type': 'text/html',
34 verbose headers   'transfer-encoding': 'chunked',
34 verbose headers   connection: 'close' }
35 verbose request invalidating /Users/ben/.npm/npm.recurly.net/mitie on PUT
36 error publish Failed PUT 413
37 verbose stack SyntaxError: Unexpected token <
37 verbose stack <html>
37 verbose stack <head><title>413 Request Entity Too Large</title></head>
37 verbose stack <body bgcolor="white">
37 verbose stack <center><h1>413 Request Entity Too Large</h1></center>
37 verbose stack <hr><center>nginx/1.1.19</center>
37 verbose stack </body>
37 verbose stack </html>
37 verbose stack
37 verbose stack     at Object.parse (native)
37 verbose stack     at CachingRegistryClient.<anonymous> (/Users/ben/.nvm/versions/node/v0.12.7/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:198:23)
37 verbose stack     at Request._callback (/Users/ben/.nvm/versions/node/v0.12.7/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:171:14)
37 verbose stack     at Request.self.callback (/Users/ben/.nvm/versions/node/v0.12.7/lib/node_modules/npm/node_modules/request/request.js:198:22)
37 verbose stack     at Request.emit (events.js:110:17)
37 verbose stack     at Request.<anonymous> (/Users/ben/.nvm/versions/node/v0.12.7/lib/node_modules/npm/node_modules/request/request.js:1073:14)
37 verbose stack     at Request.emit (events.js:129:20)
37 verbose stack     at IncomingMessage.<anonymous> (/Users/ben/.nvm/versions/node/v0.12.7/lib/node_modules/npm/node_modules/request/request.js:1019:12)
37 verbose stack     at IncomingMessage.emit (events.js:129:20)
37 verbose stack     at _stream_readable.js:908:16
38 verbose cwd /Users/ben/code/mitie
39 error Darwin 14.5.0
40 error argv "node" "/Users/ben/.nvm/versions/node/v0.12.7/bin/npm" "publish"
41 error node v0.12.7
42 error npm  v2.14.1
43 error Unexpected token <
43 error <html>
43 error <head><title>413 Request Entity Too Large</title></head>
43 error <body bgcolor="white">
43 error <center><h1>413 Request Entity Too Large</h1></center>
43 error <hr><center>nginx/1.1.19</center>
43 error </body>
43 error </html>
44 error If you need help, you may report this error at:
44 error     <https://github.com/npm/npm/issues>
45 verbose exit [ 1, true ]
```

**Comment by bhelx** [comment]
Anyone have any ideas on this?

**Comment by othiym23** [comment]
```
npm ERR! Unexpected token <
npm ERR! <html>
npm ERR! <head><title>413 Request Entity Too Large</title></head>
npm ERR! <body bgcolor="white">
npm ERR! <center><h1>413 Request Entity Too Large</h1></center>
npm ERR! <hr><center>nginx/1.1.19</center>
npm ERR! </body>
npm ERR! </html>
```

This bit indicates that there seems to be some kind of proxy between you and the registry. npm does use nginx in the registry, but not for the pieces that you're interacting with. Do you know if there's a clear path between your host and the registry?

**Comment by bhelx** [comment]
@othiym23 Yeah now that I look at it, it appears to be an internal proxy. Sorry for the false alarm. I'm closing this issue.

Thank you!

**Comment by bhelx** [comment]
Just in case anyone runs across this, I was able to temporarily bypass our proxy like this:

```
npm --registry https://registry.npmjs.org/ login
npm --registry https://registry.npmjs.org/ publish
```
