### ISSUE TITLE
undefined 500 on npm publish 

### ISSUE THREAD

**Issue by baseman** [npm/npm#9442]
Trying to publish. The npm repository looks like it is created but will not upload any files. I get the following error...

```
"\"undefined\" == true" : <project-name>
```

and the following npm debug dump:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'publish' ]
2 info using npm@2.11.3
3 info using node@v0.12.7
4 verbose publish [ '.' ]
5 silly cache add args [ '.', null ]
6 verbose cache add spec .
7 silly cache add parsed spec { raw: '.',
7 silly cache add   scope: null,
7 silly cache add   name: null,
7 silly cache add   rawSpec: '.',
7 silly cache add   spec: '/home/steve/dev/javascript/event/event-player',
7 silly cache add   type: 'directory' }
8 verbose addLocalDirectory /home/steve/.npm/event-player/0.0.1/package.tgz not in flight; packing
9 verbose getCacheStat cache creation not in flight; initializing
10 verbose tar pack [ '/home/steve/.npm/event-player/0.0.1/package.tgz',
10 verbose tar pack   '/home/steve/dev/javascript/event/event-player' ]
11 verbose tarball /home/steve/.npm/event-player/0.0.1/package.tgz
12 verbose folder /home/steve/dev/javascript/event/event-player
13 info prepublish event-player@0.0.1
14 verbose addLocalTarball adding from inside cache /home/steve/.npm/event-player/0.0.1/package.tgz
15 silly cache afterAdd event-player@0.0.1
16 verbose afterAdd /home/steve/.npm/event-player/0.0.1/package/package.json not in flight; writing
17 verbose afterAdd /home/steve/.npm/event-player/0.0.1/package/package.json written
18 silly publish { author: { name: 'Steve Hammond' },
18 silly publish   name: 'event-player',
18 silly publish   description: 'Event Sourcing tool for creating commands and versioned events with libraries with ability to playback over events.',
18 silly publish   version: '0.0.1',
18 silly publish   repository: { url: 'git+ssh://git@github.com/baseman/eventPlayerJs.git' },
18 silly publish   keywords: [ 'event', 'sourcing' ],
18 silly publish   src: 'src',
18 silly publish   test: 'test',
18 silly publish   dist: 'dist',
18 silly publish   main: './eventPlayer.js',
18 silly publish   dependencies: {},
18 silly publish   devDependencies:
18 silly publish    { 'jasmine-node': '1.14.5',
18 silly publish      grunt: '~0.4.5',
18 silly publish      'load-grunt-tasks': '~0.6.0',
18 silly publish      'grunt-contrib-copy': '~0.5.0',
18 silly publish      'grunt-contrib-clean': '~0.6.0',
18 silly publish      'grunt-jasmine-node': '0.3.1' },
18 silly publish   scripts: { build: '' },
18 silly publish   engines: { node: '0.12' },
18 silly publish   readme: 'Event Player Library\n====================\n\nThis is a simple JS library for creating, applying and iterating through Events on Domain Driven Aggregates.\n\nThis library is not meant to be a replacement for events occurring between UI, the server, and database. It is rather meant to be a simplified utility belt to help you model your domain (and encourage immutibility through events), so that later you can easily move your domain logic to another technology (whether it be a UI lib, dispatcher, queue, etc.)\n\nMIT License (MIT)\n==================\n\nCopyright (c) 2014 Stephen Hammond\n\nPermission is hereby granted, free of charge, to any person obtaining a copy of\nthis software and associated documentation files (the "Software"), to deal in\nthe Software without restriction, including without limitation the rights to\nuse, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of\nthe Software, and to permit persons to whom the Software is furnished to do so,\nsubject to the following conditions:\n\nThe above copyright notice and this permission notice shall be included in all\ncopies or substantial portions of the Software.\n\nTHE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\nIMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS\nFOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR\nCOPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER\nIN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN\nCONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.',
18 silly publish   readmeFilename: 'README.md',
18 silly publish   gitHead: 'c1370ac57ae988dab5c4e8e24a9ddd55268726c8',
18 silly publish   bugs: { url: 'https://github.com/baseman/eventPlayerJs/issues' },
18 silly publish   homepage: 'https://github.com/baseman/eventPlayerJs#readme',
18 silly publish   _id: 'event-player@0.0.1',
18 silly publish   _shasum: 'a9834f591565c819496c8f719b1702f50a8d7e80',
18 silly publish   _from: '.' }
19 verbose getPublishConfig undefined
20 silly mapToRegistry name event-player
21 silly mapToRegistry using default registry
22 silly mapToRegistry registry https://registry.npmjs.org/
23 silly mapToRegistry uri https://registry.npmjs.org/event-player
24 verbose publish registryBase https://registry.npmjs.org/
25 silly publish uploading /home/steve/.npm/event-player/0.0.1/package.tgz
26 verbose request uri https://registry.npmjs.org/event-player
27 verbose request sending authorization for write operation
28 info attempt registry request try #1 at 16:10:35
29 verbose request using bearer token for auth
30 verbose request id 08823c7974998786
31 http request PUT https://registry.npmjs.org/event-player
32 http 500 https://registry.npmjs.org/event-player
33 info retry will retry, error on last attempt: Error: "\"undefined\" == true" : event-player
34 info attempt registry request try #2 at 16:10:46
35 verbose request using bearer token for auth
36 http request PUT https://registry.npmjs.org/event-player
37 http 500 https://registry.npmjs.org/event-player
38 info retry will retry, error on last attempt: Error: "\"undefined\" == true" : event-player
39 info attempt registry request try #3 at 16:11:48
40 verbose request using bearer token for auth
41 http request PUT https://registry.npmjs.org/event-player
42 http 500 https://registry.npmjs.org/event-player
43 verbose headers { 'content-type': 'application/json',
43 verbose headers   'cache-control': 'max-age=0',
43 verbose headers   'content-length': '57',
43 verbose headers   'accept-ranges': 'bytes',
43 verbose headers   date: 'Sat, 29 Aug 2015 20:11:49 GMT',
43 verbose headers   via: '1.1 varnish',
43 verbose headers   connection: 'keep-alive',
43 verbose headers   'x-served-by': 'cache-jfk1026-JFK',
43 verbose headers   'x-cache': 'MISS',
43 verbose headers   'x-cache-hits': '0',
43 verbose headers   'x-timer': 'S1440879108.611092,VS0,VE730' }
44 verbose request invalidating /home/steve/.npm/registry.npmjs.org/event-player on PUT
45 error publish Failed PUT 500
46 verbose stack Error: "\"undefined\" == true" : event-player
46 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:247:14)
46 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:170:14)
46 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:354:22)
46 verbose stack     at Request.emit (events.js:110:17)
46 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1207:14)
46 verbose stack     at Request.emit (events.js:129:20)
46 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1153:12)
46 verbose stack     at IncomingMessage.emit (events.js:129:20)
46 verbose stack     at _stream_readable.js:908:16
46 verbose stack     at process._tickCallback (node.js:355:11)
47 verbose statusCode 500
48 verbose pkgid event-player
49 verbose cwd /home/steve/dev/javascript/event/event-player
50 error Linux 3.13.0-62-generic
51 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "publish"
52 error node v0.12.7
53 error npm  v2.11.3
54 error code E500
55 error "\"undefined\" == true" : event-player
56 error If you need help, you may report this error at:
56 error     <https://github.com/npm/npm/issues>
57 verbose exit [ 1, true ]
```

**Comment by danii1** [comment]
I have the same issue, logs attached
```
0 info it worked if it ends with ok
1 verbose cli [ '/home/daniil/.nvm/versions/node/v0.12.7/bin/node',
1 verbose cli   '/home/daniil/.nvm/versions/node/v0.12.7/bin/npm',
1 verbose cli   'publish' ]
2 info using npm@2.11.3
3 info using node@v0.12.7
4 verbose publish [ '.' ]
5 silly cache add args [ '.', null ]
6 verbose cache add spec .
7 silly cache add parsed spec { raw: '.',
7 silly cache add   scope: null,
7 silly cache add   name: null,
7 silly cache add   rawSpec: '.',
7 silly cache add   spec: '/home/daniil/Documents/Projects/oss/react-boilerplate',
7 silly cache add   type: 'directory' }
8 verbose addLocalDirectory /home/daniil/.npm/react-beginner-boilerplate/0.0.1/package.tgz not in flight; packing
9 verbose tar pack [ '/home/daniil/.npm/react-beginner-boilerplate/0.0.1/package.tgz',
9 verbose tar pack   '/home/daniil/Documents/Projects/oss/react-boilerplate' ]
10 verbose tarball /home/daniil/.npm/react-beginner-boilerplate/0.0.1/package.tgz
11 verbose folder /home/daniil/Documents/Projects/oss/react-boilerplate
12 info prepublish react-beginner-boilerplate@0.0.1
13 verbose addLocalTarball adding from inside cache /home/daniil/.npm/react-beginner-boilerplate/0.0.1/package.tgz
14 silly cache afterAdd react-beginner-boilerplate@0.0.1
15 verbose afterAdd /home/daniil/.npm/react-beginner-boilerplate/0.0.1/package/package.json not in flight; writing
16 verbose afterAdd /home/daniil/.npm/react-beginner-boilerplate/0.0.1/package/package.json written
17 silly publish { name: 'react-beginner-boilerplate',
17 silly publish   version: '0.0.1',
17 silly publish   description: 'React boilerplate friendly for beginners and suitable for small, mid-sized apps. Can be hosted on Github Pages.',
17 silly publish   src: 'src',
17 silly publish   dist: 'dist',
17 silly publish   keywords:
17 silly publish    [ 'react',
17 silly publish      'react-router',
17 silly publish      'webpack',
17 silly publish      'boilerplate',
17 silly publish      'reflux',
17 silly publish      'es6',
17 silly publish      'postcss' ],
17 silly publish   scripts:
17 silly publish    { test: './node_modules/karma/bin/karma start karma.conf.js --single-run',
17 silly publish      'test:watch': './node_modules/karma/bin/karma start karma.conf.js --no-single-run --auto-watch',
17 silly publish      server: 'webpack-dev-server --config webpack.config.js --hot --progress --colors --inline --content-base ./build',
17 silly publish      browser: 'node ./openurl.js',
17 silly publish      launch: '(sleep 1 && npm run browser) & npm run server',
17 silly publish      clean: 'rm -rf ./dist',
17 silly publish      build: 'rm -rf ./dist && ./node_modules/.bin/webpack --config webpack.dist.config.js',
17 silly publish      deploy: 'rm -rf ./dist && npm run build && node ./publish.js' },
17 silly publish   homepage: 'https://github.com/danii1/react-beginner-boilerplate',
17 silly publish   repository:
17 silly publish    { type: 'git',
17 silly publish      url: 'git+https://github.com/danii1/react-beginner-boilerplate.git' },
17 silly publish   bugs: { url: 'https://github.com/danii1/react-beginner-boilerplate/issues' },
17 silly publish   author: { name: 'Daniil Pokrovsky', url: 'https://github.com/danii1' },
17 silly publish   license: 'MIT',
17 silly publish   engines: { node: '>=0.12.0' },
17 silly publish   dependencies:
17 silly publish    { jquery: '^2.1.4',
17 silly publish      'normalize.css': '~3.0.3',
17 silly publish      react: '0.13.x',
17 silly publish      'react-router': '^0.13.x',
17 silly publish      reflux: '^0.2.7' },
17 silly publish   devDependencies:
17 silly publish    { autoprefixer: '^6.0.3',
17 silly publish      babel: '^5.0.0',
17 silly publish      'babel-loader': '^5.0.0',
17 silly publish      'css-loader': '^0.9.0',
17 silly publish      eslint: '^0.21.2',
17 silly publish      'eslint-loader': '^0.11.2',
17 silly publish      'eslint-plugin-react': '^2.4.0',
17 silly publish      'extract-text-webpack-plugin': '^0.8.2',
17 silly publish      'file-loader': '^0.8.4',
17 silly publish      'gh-pages': '^0.4.0',
17 silly publish      'html-webpack-plugin': '^1.6.1',
17 silly publish      'jasmine-core': '^2.3.4',
17 silly publish      karma: '^0.13.9',
17 silly publish      'karma-jasmine': '^0.3.5',
17 silly publish      'karma-phantomjs-launcher': '^0.1.3',
17 silly publish      'karma-script-launcher': '^0.1.0',
17 silly publish      'karma-webpack': '^1.7.0',
17 silly publish      open: '0.0.5',
17 silly publish      'postcss-loader': '^0.6',
17 silly publish      precss: '^1.1.3',
17 silly publish      'react-hot-loader': '^1.0.7',
17 silly publish      'style-loader': '^0.8.0',
17 silly publish      'url-loader': '^0.5.5',
17 silly publish      webpack: '^1.10.0',
17 silly publish      'webpack-dev-server': '^1.10.0' },
17 silly publish   readme: '# React Beginner Boilerplate\nBeginner friendly boilerplate that is suitable for small and mid-sized apps. If you just want to experiment with React and Flux pattern or don\'t want spend too much time configuring development environment, you might find this template useful. If your project is open-source - you can easily deploy it to [GitHub Pages](http://danii1.github.io/react-beginner-boilerplate/). Boilerplate adds hashes to asset names, so you can leverage long term caching.\n\n## Whats inside\n- **React**\n- **Reflux** - one of the implementations of Flux pattern, you can swap it with any alternative you prefer\n- **React Router** - routing\n- **React Hot Loader** - for real-time component tweaking\n- **Babel** - use ES6 syntax today\n- **Webpack** - packaging resources and assets\n- **jQuery** - in case you need to use some third-party UI components, otherwise feel free to remove it\n- **PostCSS** - CSS autoprefixing\n- **PreCSS** - write either pure CSS or use Sass like syntax for variables, loops, etc\n- **ESLint** - rules that make your JS better\n- **Karma** - tests\n\n## Usage\nInstall\n```\nnpm install\n```\n\nRun\n```\nnpm run launch  - launch development server and open browser with your project\nnpm run server  - just launch development server\nnpm run browser - just open browser\n```\n\nRun tests\n```\nnpm test        - run tests\nnpm test watch  - run tests and watch for changes\n```\n\nBuild project for production\n```\nnpm run build   - build project in dist/ dir\n```\n\nDeploy project to Github\n```\nnpm run deploy  - build and push contents of the dist/ dir to the Github Pages\n```\n\nClean\n```\nnpm run clean   - remove dist/ dir\n```\n\n## Directory structure\n```\nsrc\n└── assets\n    ├── css\n    └── images\n├── components\n├── routes\n├── stores\n├── actions\n└── router.js\n```\n\n## Alternatives\nIf you need server-rendering and stuff, there are some good alternatives, so check them out:  https://github.com/gaearon/react-hot-loader/tree/master/docs#starter-kits\n',
17 silly publish   readmeFilename: 'README.md',
17 silly publish   gitHead: '85bd6c2f97b69dd2dc98a198fabac99b303e469f',
17 silly publish   _id: 'react-beginner-boilerplate@0.0.1',
17 silly publish   _shasum: '163de0168a1535e19199a700743d33cfd9ffd36c',
17 silly publish   _from: '.' }
18 verbose getPublishConfig undefined
19 silly mapToRegistry name react-beginner-boilerplate
20 silly mapToRegistry using default registry
21 silly mapToRegistry registry https://registry.npmjs.org/
22 silly mapToRegistry uri https://registry.npmjs.org/react-beginner-boilerplate
23 verbose publish registryBase https://registry.npmjs.org/
24 silly publish uploading /home/daniil/.npm/react-beginner-boilerplate/0.0.1/package.tgz
25 verbose request uri https://registry.npmjs.org/react-beginner-boilerplate
26 verbose request sending authorization for write operation
27 info attempt registry request try #1 at 10:57:56 PM
28 verbose request using bearer token for auth
29 verbose request id f1907b122bdba85c
30 http request PUT https://registry.npmjs.org/react-beginner-boilerplate
31 http 500 https://registry.npmjs.org/react-beginner-boilerplate
32 info retry will retry, error on last attempt: Error: "\"undefined\" == true" : react-beginner-boilerplate
33 info attempt registry request try #2 at 10:58:07 PM
34 verbose request using bearer token for auth
35 http request PUT https://registry.npmjs.org/react-beginner-boilerplate
36 http 500 https://registry.npmjs.org/react-beginner-boilerplate
37 info retry will retry, error on last attempt: Error: "\"undefined\" == true" : react-beginner-boilerplate
38 info attempt registry request try #3 at 10:59:09 PM
39 verbose request using bearer token for auth
40 http request PUT https://registry.npmjs.org/react-beginner-boilerplate
41 http 500 https://registry.npmjs.org/react-beginner-boilerplate
42 verbose headers { 'content-type': 'application/json',
42 verbose headers   'cache-control': 'max-age=0',
42 verbose headers   'content-length': '57',
42 verbose headers   'accept-ranges': 'bytes',
42 verbose headers   date: 'Tue, 22 Sep 2015 19:59:12 GMT',
42 verbose headers   via: '1.1 varnish',
42 verbose headers   connection: 'keep-alive',
42 verbose headers   'x-served-by': 'cache-lcy1125-LCY',
42 verbose headers   'x-cache': 'MISS',
42 verbose headers   'x-cache-hits': '0',
42 verbose headers   'x-timer': 'S1442951950.863953,VS0,VE1260' }
43 verbose request invalidating /home/daniil/.npm/registry.npmjs.org/react-beginner-boilerplate on PUT
44 error publish Failed PUT 500
45 verbose stack Error: "\"undefined\" == true" : react-beginner-boilerplate
45 verbose stack     at CachingRegistryClient.<anonymous> (/home/daniil/.nvm/versions/node/v0.12.7/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:247:14)
45 verbose stack     at Request._callback (/home/daniil/.nvm/versions/node/v0.12.7/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:170:14)
45 verbose stack     at Request.self.callback (/home/daniil/.nvm/versions/node/v0.12.7/lib/node_modules/npm/node_modules/request/request.js:354:22)
45 verbose stack     at Request.emit (events.js:110:17)
45 verbose stack     at Request.<anonymous> (/home/daniil/.nvm/versions/node/v0.12.7/lib/node_modules/npm/node_modules/request/request.js:1207:14)
45 verbose stack     at Request.emit (events.js:129:20)
45 verbose stack     at IncomingMessage.<anonymous> (/home/daniil/.nvm/versions/node/v0.12.7/lib/node_modules/npm/node_modules/request/request.js:1153:12)
45 verbose stack     at IncomingMessage.emit (events.js:129:20)
45 verbose stack     at _stream_readable.js:908:16
45 verbose stack     at process._tickCallback (node.js:355:11)
46 verbose statusCode 500
47 verbose pkgid react-beginner-boilerplate
48 verbose cwd /home/daniil/Documents/Projects/oss/react-boilerplate
49 error Linux 3.19.0-28-generic
50 error argv "/home/daniil/.nvm/versions/node/v0.12.7/bin/node" "/home/daniil/.nvm/versions/node/v0.12.7/bin/npm" "publish"
51 error node v0.12.7
52 error npm  v2.11.3
53 error code E500
54 error "\"undefined\" == true" : react-beginner-boilerplate
55 error If you need help, you may report this error at:
55 error     <https://github.com/npm/npm/issues>
56 verbose exit [ 1, true ]
```

**Comment by crooy** [comment]
me too 

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node4-lts/4.2.2/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'publish' ]
2 info using npm@2.14.7
3 info using node@v4.2.2
4 verbose publish [ '.' ]
5 silly cache add args [ '.', null ]
6 verbose cache add spec .
7 silly cache add parsed spec Result {
7 silly cache add   raw: '.',
7 silly cache add   scope: null,
7 silly cache add   name: null,
7 silly cache add   rawSpec: '.',
7 silly cache add   spec: '/Users/ronald/Development/withlocals-chemistry-set',
7 silly cache add   type: 'directory' }
8 verbose addLocalDirectory /Users/ronald/.npm/@withlocals/withlocals-chemistry-set/0.0.3/package.tgz not in flight; packing
9 verbose tar pack [ '/Users/ronald/.npm/@withlocals/withlocals-chemistry-set/0.0.3/package.tgz',
9 verbose tar pack   '/Users/ronald/Development/withlocals-chemistry-set' ]
10 verbose tarball /Users/ronald/.npm/@withlocals/withlocals-chemistry-set/0.0.3/package.tgz
11 verbose folder /Users/ronald/Development/withlocals-chemistry-set
12 info prepublish @withlocals/withlocals-chemistry-set@0.0.3
13 verbose unsafe-perm in lifecycle true
14 verbose addLocalTarball adding from inside cache /Users/ronald/.npm/@withlocals/withlocals-chemistry-set/0.0.3/package.tgz
15 silly cache afterAdd @withlocals/withlocals-chemistry-set@0.0.3
16 verbose afterAdd /Users/ronald/.npm/@withlocals/withlocals-chemistry-set/0.0.3/package/package.json not in flight; writing
17 verbose afterAdd /Users/ronald/.npm/@withlocals/withlocals-chemistry-set/0.0.3/package/package.json written
18 silly publish { name: '@withlocals/withlocals-chemistry-set',
18 silly publish   version: '0.0.3',
18 silly publish   description: 'a lot of small components that are easily reused. In our Atomic design analogy, these are atoms and molecules',
18 silly publish   engineStrict: false,
18 silly publish   engines: { node: '4.2.x' },
18 silly publish   author: { name: 'Withlocals', email: 'developers@withlocals.com' },
18 silly publish   keywords: [],
18 silly publish   src: 'src',
18 silly publish   dist: 'dist',
18 silly publish   main: 'dist/components/index.js',
18 silly publish   files: [ 'dist' ],
18 silly publish   scripts: { prepublish: 'gulp prepublish', test: 'gulp' },
18 silly publish   dependencies:
18 silly publish    { 'react-immutable-render-mixin': '^0.8.1',
18 silly publish      'tcomb-form': '^0.7.6' },
18 silly publish   peerDependencies:
18 silly publish    { react: '>=0.13.2',
18 silly publish      'react-bootstrap': '0.27.x',
18 silly publish      'react-dom': '>=0.14.0' },
18 silly publish   devDependencies:
18 silly publish    { 'babel-core': '^5.5.0',
18 silly publish      'babel-plugin-transform-react-jsx': '^6.1.4',
18 silly publish      gulp: '^3.6.0',
18 silly publish      'gulp-babel': '^5.1.0',
18 silly publish      'gulp-eslint': '^1.0.0',
18 silly publish      'gulp-exclude-gitignore': '^1.0.0',
18 silly publish      'gulp-istanbul': '^0.9.0',
18 silly publish      'gulp-mocha': '^2.0.0',
18 silly publish      'gulp-nsp': '^0.4.5',
18 silly publish      'gulp-plumber': '^1.0.0',
18 silly publish      isparta: '^3.5.3',
18 silly publish      react: '>=0.13.2',
18 silly publish      'react-bootstrap': '0.27.x',
18 silly publish      'react-dom': '>=0.14.0' },
18 silly publish   readme: '# withlocals-chemistry-set [![NPM version][npm-image]][npm-url] [![Build Status][travis-image]][travis-url] [![Dependency Status][daviddm-image]][daviddm-url]\n>\n\n\n## Install\n\n```sh\n$ npm install --save withlocals-chemistry-set\n```\n\n\n## Usage\n\n```js\nvar withlocalsAuthentication = require(\'withlocals-chemistry-set \');\n\n```\n\n## License\n\n © [Withlocals]()\n\n\n[npm-image]: https://badge.fury.io/js/withlocals-chemistry-set .svg\n[npm-url]: https://npmjs.org/package/withlocals-chemistry-set\n[travis-image]: https://travis-ci.org//withlocals-chemistry-set .svg?branch=master\n[travis-url]: https://travis-ci.org//withlocals-chemistry-set\n[daviddm-image]: https://david-dm.org//withlocals-chemistry-set .svg?theme=shields.io\n[daviddm-url]: https://david-dm.org//withlocals-chemistry-set\n',
18 silly publish   readmeFilename: 'README.md',
18 silly publish   gitHead: 'f27eadb12cb8de7f29ba9d8154a50fec490843bc',
18 silly publish   _id: '@withlocals/withlocals-chemistry-set@0.0.3',
18 silly publish   _shasum: 'a42d6833a291e93459f398e1eeba7c46c91f1aa0',
18 silly publish   _from: '.' }
19 verbose getPublishConfig undefined
20 silly mapToRegistry name @withlocals/withlocals-chemistry-set
21 silly mapToRegistry scope (from package name) @withlocals
22 silly mapToRegistry registry https://registry.npmjs.org/
23 silly mapToRegistry uri https://registry.npmjs.org/@withlocals%2fwithlocals-chemistry-set
24 verbose publish registryBase https://registry.npmjs.org/
25 silly publish uploading /Users/ronald/.npm/@withlocals/withlocals-chemistry-set/0.0.3/package.tgz
26 verbose request uri https://registry.npmjs.org/@withlocals%2fwithlocals-chemistry-set
27 verbose request sending authorization for write operation
28 info attempt registry request try #1 at 4:47:03 PM
29 verbose request using bearer token for auth
30 verbose request id 87cb22499d5ba08f
31 http request PUT https://registry.npmjs.org/@withlocals%2fwithlocals-chemistry-set
32 http 500 https://registry.npmjs.org/@withlocals%2fwithlocals-chemistry-set
33 verbose headers { 'content-type': 'application/json',
33 verbose headers   'cache-control': 'max-age=0',
33 verbose headers   'content-length': '57',
33 verbose headers   'accept-ranges': 'bytes',
33 verbose headers   date: 'Fri, 13 Nov 2015 15:47:04 GMT',
33 verbose headers   via: '1.1 varnish',
33 verbose headers   connection: 'keep-alive',
33 verbose headers   'x-served-by': 'cache-ams4127-AMS',
33 verbose headers   'x-cache': 'MISS',
33 verbose headers   'x-cache-hits': '0',
33 verbose headers   'x-timer': 'S1447429623.493386,VS0,VE1343' }
34 info retry will retry, error on last attempt: Error: "\"undefined\" == true" : @withlocals/withlocals-chemistry-set
35 info attempt registry request try #2 at 4:47:14 PM
36 verbose request using bearer token for auth
37 http request PUT https://registry.npmjs.org/@withlocals%2fwithlocals-chemistry-set
38 http 500 https://registry.npmjs.org/@withlocals%2fwithlocals-chemistry-set
39 verbose headers { 'content-type': 'application/json',
39 verbose headers   'cache-control': 'max-age=0',
39 verbose headers   'content-length': '57',
39 verbose headers   'accept-ranges': 'bytes',
39 verbose headers   date: 'Fri, 13 Nov 2015 15:47:16 GMT',
39 verbose headers   via: '1.1 varnish',
39 verbose headers   connection: 'keep-alive',
39 verbose headers   'x-served-by': 'cache-ams4134-AMS',
39 verbose headers   'x-cache': 'MISS',
39 verbose headers   'x-cache-hits': '0',
39 verbose headers   'x-timer': 'S1447429634.882637,VS0,VE1269' }
40 info retry will retry, error on last attempt: Error: "\"undefined\" == true" : @withlocals/withlocals-chemistry-set
41 info attempt registry request try #3 at 4:48:16 PM
42 verbose request using bearer token for auth
43 http request PUT https://registry.npmjs.org/@withlocals%2fwithlocals-chemistry-set
44 http 500 https://registry.npmjs.org/@withlocals%2fwithlocals-chemistry-set
45 verbose headers { 'content-type': 'application/json',
45 verbose headers   'cache-control': 'max-age=0',
45 verbose headers   'content-length': '57',
45 verbose headers   'accept-ranges': 'bytes',
45 verbose headers   date: 'Fri, 13 Nov 2015 15:48:17 GMT',
45 verbose headers   via: '1.1 varnish',
45 verbose headers   connection: 'keep-alive',
45 verbose headers   'x-served-by': 'cache-ams4127-AMS',
45 verbose headers   'x-cache': 'MISS',
45 verbose headers   'x-cache-hits': '0',
45 verbose headers   'x-timer': 'S1447429696.202084,VS0,VE1255' }
46 verbose request invalidating /Users/ronald/.npm/registry.npmjs.org/_40withlocals_252fwithlocals-chemistry-set on PUT
47 error publish Failed PUT 500
48 verbose stack Error: "\"undefined\" == true" : @withlocals/withlocals-chemistry-set
48 verbose stack     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
48 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:252:14)
48 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
48 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:198:22)
48 verbose stack     at emitTwo (events.js:87:13)
48 verbose stack     at Request.emit (events.js:172:7)
48 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1063:14)
48 verbose stack     at emitOne (events.js:82:20)
48 verbose stack     at Request.emit (events.js:169:7)
48 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1009:12)
49 verbose statusCode 500
50 verbose pkgid @withlocals/withlocals-chemistry-set
51 verbose cwd /Users/ronald/Development/withlocals-chemistry-set
52 error Darwin 14.5.0
53 error argv "/usr/local/Cellar/node4-lts/4.2.2/bin/node" "/usr/local/bin/npm" "publish"
54 error node v4.2.2
55 error npm  v2.14.7
56 error code E500
57 error "\"undefined\" == true" : @withlocals/withlocals-chemistry-set
58 error If you need help, you may report this error at:
58 error     <https://github.com/npm/npm/issues>
59 verbose exit [ 1, true ]
```

**Comment by crooy** [comment]
Aha I found the solution, my main file did not exist. When i added index.js it works!

**Comment by baseman** [comment]
Interesting. I know I have a ll the correct resources in place as I was able to resubmit the module via a travisCI webhook deploy.
