### ISSUE TITLE
Unable to publish

### ISSUE THREAD

**Issue by nihalsheik** [npm/npm#9444]
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\apps\\nodejs\\\\node.exe',
1 verbose cli   'C:\\apps\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'publish' ]
2 info using npm@2.11.3
3 info using node@v0.12.7
4 verbose publish [ '.' ]
5 silly cache add args [ '.', null ]
6 verbose cache add spec .
7 silly cache add parsed spec { raw: '.',
7 silly cache add   scope: null,
7 silly cache add   name: null,
7 silly cache add   rawSpec: '.',
7 silly cache add   spec: 'C:\\nihalsheik\\nodejs\\task-manager',
7 silly cache add   type: 'directory' }
8 verbose addLocalDirectory C:\Users\admin\AppData\Roaming\npm-cache\task-manager\1.0.0\package.tgz not in flight; packing
9 verbose tar pack [ 'C:\\Users\\admin\\AppData\\Roaming\\npm-cache\\task-manager\\1.0.0\\package.tgz',
9 verbose tar pack   'C:\\nihalsheik\\nodejs\\task-manager' ]
10 verbose tarball C:\Users\admin\AppData\Roaming\npm-cache\task-manager\1.0.0\package.tgz
11 verbose folder C:\nihalsheik\nodejs\task-manager
12 info prepublish task-manager@1.0.0
13 verbose addLocalTarball adding from inside cache C:\Users\admin\AppData\Roaming\npm-cache\task-manager\1.0.0\package.tgz
14 silly cache afterAdd task-manager@1.0.0
15 verbose afterAdd C:\Users\admin\AppData\Roaming\npm-cache\task-manager\1.0.0\package\package.json not in flight; writing
16 verbose afterAdd C:\Users\admin\AppData\Roaming\npm-cache\task-manager\1.0.0\package\package.json written
17 silly publish { name: 'task-manager',
17 silly publish   version: '1.0.0',
17 silly publish   description: '',
17 silly publish   main: 'index.js',
17 silly publish   scripts: { test: 'echo "Error: no test specified" && exit 1' },
17 silly publish   repository:
17 silly publish    { type: 'git',
17 silly publish      url: 'git+https://github.com/nihalsheik/task-manager.git' },
17 silly publish   keywords: [ 'task', 'async', 'runner', 'job' ],
17 silly publish   author: { name: 'Sheik Mohideen' },
17 silly publish   license: 'ISC',
17 silly publish   bugs: { url: 'https://github.com/nihalsheik/task-manager/issues' },
17 silly publish   homepage: 'https://github.com/nihalsheik/task-manager#readme',
17 silly publish   gitHead: 'c1167d2d72e0246b054e96c92be2435d9a0d2063',
17 silly publish   readme: 'ERROR: No README data found!',
17 silly publish   _id: 'task-manager@1.0.0',
17 silly publish   _shasum: '78b654cb165b64401b9ce9eaf47ed2fea16da8f9',
17 silly publish   _from: '.' }
18 verbose getPublishConfig undefined
19 silly mapToRegistry name task-manager
20 silly mapToRegistry using default registry
21 silly mapToRegistry registry https://registry.npmjs.org/
22 silly mapToRegistry uri https://registry.npmjs.org/task-manager
23 verbose publish registryBase https://registry.npmjs.org/
24 silly publish uploading C:\Users\admin\AppData\Roaming\npm-cache\task-manager\1.0.0\package.tgz
25 verbose request uri https://registry.npmjs.org/task-manager
26 verbose request sending authorization for write operation
27 info attempt registry request try #1 at 11:11:45 AM
28 verbose request using bearer token for auth
29 verbose request id 3c938261867211f5
30 http request PUT https://registry.npmjs.org/task-manager
31 http 403 https://registry.npmjs.org/task-manager
32 verbose headers { 'content-type': 'application/json',
32 verbose headers   'cache-control': 'max-age=60',
32 verbose headers   'content-length': '104',
32 verbose headers   'accept-ranges': 'bytes',
32 verbose headers   date: 'Sun, 30 Aug 2015 05:41:42 GMT',
32 verbose headers   via: '1.1 varnish',
32 verbose headers   connection: 'keep-alive',
32 verbose headers   'x-served-by': 'cache-sin6920-SIN',
32 verbose headers   'x-cache': 'MISS',
32 verbose headers   'x-cache-hits': '0',
32 verbose headers   'x-timer': 'S1440913302.038558,VS0,VE839' }
33 verbose request invalidating C:\Users\admin\AppData\Roaming\npm-cache\registry.npmjs.org\task-manager on PUT
34 error publish Failed PUT 403
35 verbose stack Error: You do not have permission to publish 'task-manager'. Are you logged in as the correct user? : task-manager
35 verbose stack     at CachingRegistryClient.<anonymous> (C:\apps\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:247:14)
35 verbose stack     at Request._callback (C:\apps\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:170:14)
35 verbose stack     at Request.self.callback (C:\apps\nodejs\node_modules\npm\node_modules\request\request.js:354:22)
35 verbose stack     at Request.emit (events.js:110:17)
35 verbose stack     at Request.<anonymous> (C:\apps\nodejs\node_modules\npm\node_modules\request\request.js:1207:14)
35 verbose stack     at Request.emit (events.js:129:20)
35 verbose stack     at IncomingMessage.<anonymous> (C:\apps\nodejs\node_modules\npm\node_modules\request\request.js:1153:12)
35 verbose stack     at IncomingMessage.emit (events.js:129:20)
35 verbose stack     at _stream_readable.js:908:16
35 verbose stack     at process._tickCallback (node.js:355:11)
36 verbose statusCode 403
37 verbose pkgid task-manager
38 verbose cwd C:\nihalsheik\nodejs\task-manager
39 error Windows_NT 6.3.9600
40 error argv "C:\\apps\\nodejs\\\\node.exe" "C:\\apps\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "publish"
41 error node v0.12.7
42 error npm  v2.11.3
43 error code E403
44 error You do not have permission to publish 'task-manager'. Are you logged in as the correct user? : task-manager
45 error If you need help, you may report this error at:
45 error     <https://github.com/npm/npm/issues>
46 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
@nihalsheik The name `task-manager` is already taken.

**Comment by ehsalazar** [comment]
@nihalsheik Hopefully you were able to use an alternative name for the package and publish successfully. I'll close this for now as we’re trying to clean up some solved issues.
