### ISSUE TITLE
Error: Cannot find module 'semver'

### ISSUE THREAD

**Issue by saru95** [npm/npm#9445]
Today I encountered this and not able to install a single package .

```
saru95:all-image sarthakmunshi$ npm install express

module.js:340
    throw err;
          ^
Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/config/defaults.js:7:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
saru95:all-image sarthakmunshi$ 
```

**Comment by Stiino0** [comment]
Hi, I've encountered almost the same issue... any resolutions?

> angular-seed@0.0.0 prestart c:\Sites\templatestore
> npm install

module.js:338
    throw err;
    ^

Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\stein\AppData\Roaming\npm\node_modules\npm\lib\config\defaults.js:7:14)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

npm ERR! Windows_NT 10.0.10240
npm ERR! argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE
npm ERR! angular-seed@0.0.0 prestart: `npm install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-seed@0.0.0 prestart script 'npm install'.
npm ERR! This is most likely a problem with the angular-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular-seed
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\Sites\templatestore\npm-debug.log

[Link to Pastebin npm-error.log](http://pastebin.com/M3HjumP3)

**Comment by saru95** [comment]
I just restarted my PC and the error vanished. However, the issue is why it occurs in the first place .

**Comment by Stiino0** [comment]
Gonna try right now, pc has restarted. Anything else you did when the error vanished? Remade the entire directory with npm install first?

**Comment by saru95** [comment]
Just reinstall npm , i think you should be good to go !

**Comment by Stiino0** [comment]
You mean 'npm install' again to the directory where I've cloned the app (angular seed) to? No luck :( I'll try again tomorrow morning

Enviado desde mi iPhone

**Comment by skbhati199** [comment]
D:\angularhack\angularattack2016-coderzz>
module.js:327
    throw err;
    ^

Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (
    at Function.Module._load (module.js:2
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\Deven
m\lib\config\defaults.js:6:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (mod
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:3
    at Module.require (module.js:353:17)

**Comment by techwooten** [comment]
I'm running Linux Arch.  Semver was a separate package that was not reinstalled when I tried reinstalling npm.  When I realized this I just reinstalled semver and this issue was resolved in my case.

**Comment by zhishengzhang** [comment]
1 cd ghost
2  rm -rf node_modules
3  npm install --production
4 npm start

**Comment by imPZH** [comment]
I am encountering this With windows10, and when I tried reinstalling node, doesn't work.
D:\>npm     -------  run npm
module.js:471
    throw err;
    ^

Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Pzh\AppData\Roaming\npm\node_modules\npm\lib\utils\unsupported.js:2:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by Charlotteis** [comment]
@imPZH could you try installing the Semver package like techwooten did here: https://github.com/npm/npm/issues/9445#issuecomment-219214242 ?

**Comment by imPZH** [comment]
@Charlotteis I tried. once I type 'npm', 
such as 
'npm'
'npm -v'
'npm install -g semver '

I got the error.

**Comment by imPZH** [comment]
I deleted  ‘npm’ and 'npm_cache' folder in  ‘ C:\Users\Pzh\AppData\Roaming’, and changed environment variables ‘PATH’. The error disappears.

**Comment by legodude17** [comment]
Any still having this issue after trying what @imPZH suggested?

**Comment by cadavre** [comment]
Similar error happens on simple `npm` command call. Take a look at this Docker image log:
https://hub.docker.com/r/jazzypro/ubuntu-node-electron/builds/bky5uoiqd4wsfkqkwphvgov/

**Comment by zkat** [comment]
This error means the npm installation itself is hosed. Remove npm from your local machine and reinstall it. Assuming you don't have any weird filesystem problems going on with files going suddenly missing.

@saru95 seems to have resolved their issue, so I'm going to close this one.

**Comment by Krisel1205** [comment]
Try this one[ ](https://stackoverflow.com/questions/33870520/npm-install-cannot-find-module-semver) it resolve my issues :)

**Comment by erperejildo** [comment]
<img width="663" alt="screen shot 2017-07-21 at 02 03 08" src="https://user-images.githubusercontent.com/5629919/28443804-cb72b3a4-6db8-11e7-9090-70e6ee24bc60.png">
