### ISSUE TITLE
Error: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by masonlin** [npm/npm#9449]
installing the express have as follow error:

```
28 verbose stack Error: self signed certificate in certificate chain
28 verbose stack     at Error (native)
28 verbose stack     at TLSSocket.<anonymous> (_tls_wrap.js:929:36)
28 verbose stack     at TLSSocket.emit (events.js:104:17)
28 verbose stack     at TLSSocket._finishInit (_tls_wrap.js:460:8)
29 verbose cwd C:\Users\XXXXXX
30 error Windows_NT 6.1.7601
31 error argv "C:\\nodejs\\\\node.exe" "C:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "express" "-g"
32 error node v0.12.7
33 error npm  v2.11.3
34 error code SELF_SIGNED_CERT_IN_CHAIN
35 error self signed certificate in certificate chain
36 error If you need help, you may report this error at:
36 error     <https://github.com/npm/npm/issues>
37 verbose exit [ 1, true ]
```

How can I do to?

Thank you.

**Comment by arnabkumarroy** [comment]
I have same issue. Anyone can help me??
