### ISSUE TITLE
Cannot add user

### ISSUE THREAD

**Issue by carlosbvz** [npm/npm#9452]
when I run npm adduser i get some npm errors. 

I am very new to this and dunno why this is happening. 
Here are the logs> 

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'adduser' ]
2 info using npm@1.3.10
3 info using node@v0.10.25
4 verbose adduser before first PUT { name: 'carlosbvz',
4 verbose adduser   salt: 'XXXXX',
4 verbose adduser   password_sha: 'XXXXX',
4 verbose adduser   email: 'carlosbvz@gmail.com',
4 verbose adduser   _id: 'org.couchdb.user:carlosbvz',
4 verbose adduser   type: 'user',
4 verbose adduser   roles: [],
4 verbose adduser   date: '2015-08-31T19:27:42.738Z' }
5 verbose url raw /-/user/org.couchdb.user:carlosbvz
6 verbose url resolving [ 'https://registry.npmjs.org/',
6 verbose url resolving   './-/user/org.couchdb.user:carlosbvz' ]
7 verbose url resolved https://registry.npmjs.org/-/user/org.couchdb.user:carlosbvz
8 info trying registry request attempt 1 at 13:27:42
9 http PUT https://registry.npmjs.org/-/user/org.couchdb.user:carlosbvz
10 http 400 https://registry.npmjs.org/-/user/org.couchdb.user:carlosbvz
11 verbose adduser back [ [Error: Unknown error while authenticating : -/user/org.couchdb.user:carlosbvz],
11 verbose adduser   { ok: false, error: 'Unknown error while authenticating' },
11 verbose adduser   '{"ok":false,"error":"Unknown error while authenticating"}' ]
12 error Error: Unknown error while authenticating : -/user/org.couchdb.user:carlosbvz
12 error     at RegClient.<anonymous> (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:272:14)
12 error     at Request.self.callback (/usr/lib/nodejs/request/index.js:148:22)
12 error     at Request.EventEmitter.emit (events.js:98:17)
12 error     at Request.<anonymous> (/usr/lib/nodejs/request/index.js:896:14)
12 error     at Request.EventEmitter.emit (events.js:117:20)
12 error     at IncomingMessage.<anonymous> (/usr/lib/nodejs/request/index.js:847:12)
12 error     at IncomingMessage.EventEmitter.emit (events.js:117:20)
12 error     at _stream_readable.js:920:16
12 error     at process._tickCallback (node.js:415:13)
13 error If you need help, you may report this log at:
13 error     <http://github.com/isaacs/npm/issues>
13 error or email it to:
13 error     <npm-@googlegroups.com>
14 error System Linux 3.16.0-46-generic
15 error command "/usr/bin/nodejs" "/usr/bin/npm" "adduser"
16 error cwd /home/charliepc/Desktop/censorify
17 error node -v v0.10.25
18 error npm -v 1.3.10
19 verbose exit [ 1, true ]
```

**Comment by othiym23** [comment]
`npm@1.3.10` is no longer supported (largely because it's not capable of logging in or publishing to the current registry architecture), and the version of Node you're running is pretty old. Try [upgrading Node](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-node) and [upgrading npm](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) and all should be well.

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some issues. If this is still a problem, can you please reply and let us know? We’ll be happy to reopen if necessary.
