### ISSUE TITLE
version not found while installing typescript@^1.5.0

### ISSUE THREAD

**Issue by kankan78** [npm/npm#9454]
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'typescript@1.5.0' ]
2 info using npm@1.4.28
3 info using node@v0.10.32
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 verbose cache add [ 'typescript@1.5.0', null ]
6 verbose cache add name=undefined spec="typescript@1.5.0" args=["typescript@1.5.0",null]
7 verbose parsed url { protocol: null,
7 verbose parsed url   slashes: null,
7 verbose parsed url   auth: null,
7 verbose parsed url   host: null,
7 verbose parsed url   port: null,
7 verbose parsed url   hostname: null,
7 verbose parsed url   hash: null,
7 verbose parsed url   search: null,
7 verbose parsed url   query: null,
7 verbose parsed url   pathname: 'typescript@1.5.0',
7 verbose parsed url   path: 'typescript@1.5.0',
7 verbose parsed url   href: 'typescript@1.5.0' }
8 verbose cache add name="typescript" spec="1.5.0" args=["typescript","1.5.0"]
9 verbose parsed url { protocol: null,
9 verbose parsed url   slashes: null,
9 verbose parsed url   auth: null,
9 verbose parsed url   host: null,
9 verbose parsed url   port: null,
9 verbose parsed url   hostname: null,
9 verbose parsed url   hash: null,
9 verbose parsed url   search: null,
9 verbose parsed url   query: null,
9 verbose parsed url   pathname: '1.5.0',
9 verbose parsed url   path: '1.5.0',
9 verbose parsed url   href: '1.5.0' }
10 verbose addNamed [ 'typescript', '1.5.0' ]
11 verbose addNamed [ '1.5.0', '1.5.0' ]
12 silly lockFile 6a8b19a0-typescript-1-5-0 typescript@1.5.0
13 verbose lock typescript@1.5.0 C:\Users\kdas4\AppData\Roaming\npm-cache\6a8b19a0-typescript-1-5-0.lock
14 verbose request where is /typescript
15 verbose request registry https://registry.npmjs.org/
16 verbose request id e94ff02a29b22412
17 verbose url raw /typescript
18 verbose url resolving [ 'https://registry.npmjs.org/', './typescript' ]
19 verbose url resolved https://registry.npmjs.org/typescript
20 verbose request where is https://registry.npmjs.org/typescript
21 info trying registry request attempt 1 at 09:28:00
22 http GET https://registry.npmjs.org/typescript
23 http 200 https://registry.npmjs.org/typescript
24 silly registry.get cb [ 200,
24 silly registry.get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
24 silly registry.get     etag: '"E9L4DRKC7Q5DNHRIKMC364TZM"',
24 silly registry.get     'content-type': 'application/json',
24 silly registry.get     'cache-control': 'max-age=60',
24 silly registry.get     'content-length': '87389',
24 silly registry.get     'accept-ranges': 'bytes',
24 silly registry.get     date: 'Tue, 01 Sep 2015 03:58:01 GMT',
24 silly registry.get     via: '1.1 varnish',
24 silly registry.get     age: '0',
24 silly registry.get     connection: 'keep-alive',
24 silly registry.get     'x-served-by': 'cache-sin6926-SIN',
24 silly registry.get     'x-cache': 'HIT',
24 silly registry.get     'x-cache-hits': '1',
24 silly registry.get     'x-timer': 'S1441079881.384473,VS0,VE254',
24 silly registry.get     vary: 'Accept' } ]
25 silly lockFile 6a8b19a0-typescript-1-5-0 typescript@1.5.0
26 silly lockFile 6a8b19a0-typescript-1-5-0 typescript@1.5.0
27 error Error: version not found: typescript@1.5.0
27 error     at C:\Program Files\nodejs\node_modules\npm\lib\cache\add-named.js:125:12
27 error     at saved (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\get.js:167:7)
27 error     at Object.oncomplete (fs.js:107:15)
28 error If you need help, you may report this *entire* log,
28 error including the npm and node versions, at:
28 error     <http://github.com/npm/npm/issues>
29 error System Windows_NT 6.1.7601
30 error command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "typescript@1.5.0"
31 error cwd D:\projects\workplace\Angular 2
32 error node -v v0.10.32
33 error npm -v 1.4.28
34 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
@kankan78 Looks like you are running `npm install -g typescript@1.5.0`

Are you sure you don't mean to run `npm install -g typescript@1.5.3`?

**Comment by vedangdate** [comment]
Thanks. This helped!

**Comment by ehsalazar** [comment]
@kankan78 We haven’t heard back and we’re trying to clean up some issues. If this is still a problem, can you please reply and let us know? We’ll be happy to reopen if necessary.
