### ISSUE TITLE
sudo npm install -g hexo-cli

### ISSUE THREAD

**Issue by henryhuang** [npm/npm#9469]
```
0 info it worked if it ends with ok
1 verbose cli [ 'node',
1 verbose cli   '/Users/huangyijie/nvm/v0.10.30/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'hexo-cli' ]
2 info using npm@2.13.1
3 info using node@v0.10.30
4 verbose install initial load of /Users/huangyijie/nvm/v0.10.30/lib/package.json
5 verbose readDependencies loading dependencies from /Users/huangyijie/nvm/v0.10.30/lib/package.json
6 silly cache add args [ 'hexo-cli', null ]
7 verbose cache add spec hexo-cli
8 silly cache add parsed spec { raw: 'hexo-cli',
8 silly cache add   scope: null,
8 silly cache add   name: 'hexo-cli',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: '*',
8 silly cache add   type: 'range' }
9 silly addNamed hexo-cli@*
10 verbose addNamed "*" is a valid semver range for hexo-cli
11 silly addNameRange { name: 'hexo-cli', range: '*', hasData: false }
12 silly mapToRegistry name hexo-cli
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/hexo-cli
16 verbose addNameRange registry:https://registry.npmjs.org/hexo-cli not in flight; fetching
17 verbose request uri https://registry.npmjs.org/hexo-cli
18 verbose request no auth needed
19 info attempt registry request try #1 at 22:47:39
20 verbose request using bearer token for auth
21 verbose request id 83112c21f556cad9
22 http request GET https://registry.npmjs.org/hexo-cli
23 http 200 https://registry.npmjs.org/hexo-cli
24 silly get cb [ 200,
24 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
24 silly get     etag: '"5CGU4M6EJQCMMS56JXQ5DH8CX"',
24 silly get     'content-type': 'application/json',
24 silly get     'cache-control': 'max-age=60',
24 silly get     'content-length': '15926',
24 silly get     'accept-ranges': 'bytes',
24 silly get     date: 'Wed, 02 Sep 2015 14:47:41 GMT',
24 silly get     via: '1.1 varnish',
24 silly get     connection: 'keep-alive',
24 silly get     'x-served-by': 'cache-sjc3122-SJC',
24 silly get     'x-cache': 'MISS',
24 silly get     'x-cache-hits': '0',
24 silly get     'x-timer': 'S1441205261.385913,VS0,VE167',
24 silly get     vary: 'Accept' } ]
25 verbose get saving hexo-cli to /Users/huangyijie/.npm/registry.npmjs.org/hexo-cli/.cache.json
26 silly addNameRange number 2 { name: 'hexo-cli', range: '*', hasData: true }
27 silly addNameRange versions [ 'hexo-cli',
27 silly addNameRange   [ '0.0.1',
27 silly addNameRange     '0.1.0',
27 silly addNameRange     '0.1.1',
27 silly addNameRange     '0.1.2',
27 silly addNameRange     '0.1.3',
27 silly addNameRange     '0.1.4',
27 silly addNameRange     '0.1.5',
27 silly addNameRange     '0.1.6',
27 silly addNameRange     '0.1.7',
27 silly addNameRange     '0.1.8' ] ]
28 silly addNamed hexo-cli@0.1.8
29 verbose addNamed "0.1.8" is a plain semver version for hexo-cli
30 silly mapToRegistry name hexo-cli
31 silly mapToRegistry using default registry
32 silly mapToRegistry registry https://registry.npmjs.org/
33 silly mapToRegistry uri https://registry.npmjs.org/hexo-cli
34 verbose addRemoteTarball https://registry.npmjs.org/hexo-cli/-/hexo-cli-0.1.8.tgz not in flight; adding
35 verbose addRemoteTarball [ 'https://registry.npmjs.org/hexo-cli/-/hexo-cli-0.1.8.tgz',
35 verbose addRemoteTarball   '17dcb7301f82f75568bb9125b2f79b2aca4b07b8' ]
36 info retry fetch attempt 1 at 22:47:41
37 info attempt registry request try #1 at 22:47:41
38 http fetch GET https://registry.npmjs.org/hexo-cli/-/hexo-cli-0.1.8.tgz
39 verbose request using bearer token for auth
40 http fetch 200 https://registry.npmjs.org/hexo-cli/-/hexo-cli-0.1.8.tgz
41 silly fetchAndShaCheck shasum 17dcb7301f82f75568bb9125b2f79b2aca4b07b8
42 verbose stack Error: shasum check failed for /var/folders/sq/yw017tgd6xl0kg187f8r923h0000gn/T/npm-3772-afa93a53/registry.npmjs.org/hexo-cli/-/hexo-cli-0.1.8.tgz
42 verbose stack Expected: 17dcb7301f82f75568bb9125b2f79b2aca4b07b8
42 verbose stack Actual:   01544bf78f15224042303bfed9bc575ab8346e64
42 verbose stack From:     https://registry.npmjs.org/hexo-cli/-/hexo-cli-0.1.8.tgz
42 verbose stack     at /Users/huangyijie/nvm/v0.10.30/lib/node_modules/npm/node_modules/sha/index.js:38:8
42 verbose stack     at ReadStream.<anonymous> (/Users/huangyijie/nvm/v0.10.30/lib/node_modules/npm/node_modules/sha/index.js:85:7)
42 verbose stack     at ReadStream.emit (events.js:117:20)
42 verbose stack     at _stream_readable.js:938:16
42 verbose stack     at process._tickCallback (node.js:419:13)
43 verbose cwd /Volumes/MacintoshHD/Users/huangyijie/dev/dev_workspaces/gitcafe
44 error Darwin 14.5.0
45 error argv "node" "/Users/huangyijie/nvm/v0.10.30/bin/npm" "install" "-g" "hexo-cli"
46 error node v0.10.30
47 error npm  v2.13.1
48 error shasum check failed for /var/folders/sq/yw017tgd6xl0kg187f8r923h0000gn/T/npm-3772-afa93a53/registry.npmjs.org/hexo-cli/-/hexo-cli-0.1.8.tgz
48 error Expected: 17dcb7301f82f75568bb9125b2f79b2aca4b07b8
48 error Actual:   01544bf78f15224042303bfed9bc575ab8346e64
48 error From:     https://registry.npmjs.org/hexo-cli/-/hexo-cli-0.1.8.tgz
49 error If you need help, you may report this error at:
49 error     <https://github.com/npm/npm/issues>
50 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
@henryhuang Have you tried `npm cache clear`?

**Comment by henryhuang** [comment]
@KenanY I resolved it, but I don't know the specific reason, I try this way:
1. npm cache clear, but it didn't work
2. I found hexo(lower than 3) command had installed in my system, so I uninstall hexo, and install hexo-cli, unfortunately, it didn't work
3. I think the network problem (in China, you know), and I use VPN, repeated 1 and 2, it work
