### ISSUE TITLE
Unable to register user on npm enterprise

### ISSUE THREAD

**Issue by brodrigu** [npm/npm#9482]
I'm just getting started with npm enterprise and trying to register my first user.

Here is the attempt from the client:

```
$ npm login --registry=http://frpd-npm9000.lab1.fanops.net:8080 --scope=@rubi
Username: brodriguez
Password:
Email: (this IS public) brodriguez@rubiconproject.com
npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "login" "--registry=http://frpd-npm9000.lab1.fanops.net:8080" "--scope=@rubi"
npm ERR! node v0.10.33
npm ERR! npm  v2.14.1
npm ERR! code E400

npm ERR! Unknown error while authenticating : -/user/org.couchdb.user:brodriguez
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     npm-debug.log
```

```
$ cat npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ 'node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'login',
1 verbose cli   '--registry=http://frpd-npm9000.lab1.fanops.net:8080',
1 verbose cli   '--scope=@rubi' ]
2 info using npm@2.14.1
3 info using node@v0.10.33
4 verbose node symlink /usr/local/bin/node
5 verbose adduser before first PUT { _id: 'org.couchdb.user:brodriguez',
5 verbose adduser   name: 'brodriguez',
5 verbose adduser   password: 'XXXXX',
5 verbose adduser   email: 'brodriguez@rubiconproject.com',
5 verbose adduser   type: 'user',
5 verbose adduser   roles: [],
5 verbose adduser   date: '2015-09-03T19:01:12.219Z' }
6 verbose request uri http://frpd-npm9000.lab1.fanops.net:8080/-/user/org.couchdb.user:brodriguez
7 verbose request new user, so can't send auth
8 info attempt registry request try #1 at 12:01:12
9 verbose request id ba9532a85915e79f
10 http request PUT http://frpd-npm9000.lab1.fanops.net:8080/-/user/org.couchdb.user:brodriguez
11 http 400 http://frpd-npm9000.lab1.fanops.net:8080/-/user/org.couchdb.user:brodriguez
12 verbose headers { 'content-type': 'application/json',
12 verbose headers   'content-length': '57',
12 verbose headers   date: 'Thu, 03 Sep 2015 19:01:11 GMT',
12 verbose headers   connection: 'keep-alive' }
13 verbose request invalidating /Users/brodriguez/.npm/frpd-npm9000.lab1.fanops.net_8080/-/user/org.couchdb.user_3Abrodriguez on PUT
14 verbose adduser back [ { [Error: Unknown error while authenticating : -/user/org.couchdb.user:brodriguez] statusCode: 400, code: 'E400' },
14 verbose adduser   { ok: false, error: 'Unknown error while authenticating' },
14 verbose adduser   '{"ok":false,"error":"Unknown error while authenticating"}' ]
15 verbose stack Error: Unknown error while authenticating : -/user/org.couchdb.user:brodriguez
15 verbose stack     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:263:12)
15 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:251:14)
15 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:171:14)
15 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:198:22)
15 verbose stack     at Request.emit (events.js:98:17)
15 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1073:14)
15 verbose stack     at Request.emit (events.js:117:20)
15 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1019:12)
15 verbose stack     at IncomingMessage.emit (events.js:117:20)
15 verbose stack     at _stream_readable.js:943:16
16 verbose statusCode 400
17 verbose cwd /Users/brodriguez/Code/Rubicon/49bc
18 error Darwin 14.4.0
19 error argv "node" "/usr/local/bin/npm" "login" "--registry=http://frpd-npm9000.lab1.fanops.net:8080" "--scope=@rubi"
20 error node v0.10.33
21 error npm  v2.14.1
22 error code E400
23 error Unknown error while authenticating : -/user/org.couchdb.user:brodriguez
24 error If you need help, you may report this error at:
24 error     <https://github.com/npm/npm/issues>
25 verbose exit [ 1, true ]
```

Here are the logs from the server:

```
==> npm-auth-ws.log <==
127.0.0.1 - - [03/Sep/2015:12:01:11 -0700] "POST /authenticate HTTP/1.1" 500 66 "-" "restify/2.8.5 (x64-linux; v8/3.28.71.19; OpenSSL/1.0.1p) node/0.12.7" "application/json" 56 ms

==> registry-frontdoor.log <==
{"time":"2015-09-03T19:01:11.202Z","hostname":"frpd-npm9000.lab1.fanops.net","pid":17869,"level":"info","name":"npme","message":"172.20.98.83 - - [03/Sep/2015:12:01:11 -0700] \"PUT /-/user/org.couchdb.user:brodriguez HTTP/1.1\" 400 57 \"adduser\" \"npm/2.14.1 node/v0.10.33 darwin x64\" \"application/json\" 67 ms"}
```

**Comment by brodrigu** [comment]
Benjamin Coe helped me out here. The solution was in my service.json file where I needed to add `"--reject-unauthorized": "0"` to the args.
