### ISSUE TITLE
npm search grunt-cli ERROR

### ISSUE THREAD

**Issue by simusco** [npm/npm#9488]
```
C:\Users\Administrator\AppData\Roaming\npm>npm search grunt-cli
npm WARN Building the local index for the first time, please be patient
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "s
earch" "grunt-cli"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code E200

npm ERR! true true: -/all
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm\npm-debug.log
```

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'search',
1 verbose cli   'grunt-cli' ]
2 info using npm@2.10.1
3 info using node@v0.12.4
4 silly mapToRegistry name -/all
5 silly mapToRegistry using default registry
6 silly mapToRegistry registry http://registry.cnpmjs.org/
7 silly mapToRegistry uri http://registry.cnpmjs.org/-/all
8 info updateIndex C:\Users\Administrator\AppData\Roaming\npm-cache\registry.cnpmjs.org\-\all\.cache.json
9 warn Building the local index for the first time, please be patient
10 silly update-index fetching http://registry.cnpmjs.org/-/all
11 verbose request uri http://registry.cnpmjs.org/-/all
12 verbose request no auth needed
13 info attempt registry request try #1 at 22:31:25
14 verbose request id f820ad7d5a473d78
15 http request GET http://registry.cnpmjs.org/-/all
16 http 200 http://registry.cnpmjs.org/-/all
17 verbose headers { server: 'nginx/1.4.6 (Ubuntu)',
17 verbose headers   date: 'Fri, 04 Sep 2015 14:31:29 GMT',
17 verbose headers   'content-type': 'application/json; charset=utf-8',
17 verbose headers   'transfer-encoding': 'chunked',
17 verbose headers   connection: 'keep-alive',
17 verbose headers   'x-readtime': '1685',
17 verbose headers   'content-encoding': 'gzip' }
18 verbose stack Error: true true: -/all
18 verbose stack     at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:247:14)
18 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:176:7
18 verbose stack     at Gunzip.onEnd (zlib.js:227:5)
18 verbose stack     at Gunzip.emit (events.js:129:20)
18 verbose stack     at _stream_readable.js:908:16
18 verbose stack     at process._tickCallback (node.js:355:11)
19 verbose statusCode 200
20 verbose cwd C:\Users\Administrator\AppData\Roaming\npm
21 error Windows_NT 6.1.7601
22 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "search" "grunt-cli"
23 error node v0.12.4
24 error npm  v2.10.1
25 error code E200
26 error true true: -/all
27 error If you need help, you may report this error at:
27 error     <https://github.com/npm/npm/issues>
28 verbose exit [ 1, true ]
```

npm install -g xxxx   running very slow, please help!!!

**Comment by othiym23** [comment]
```
25 error code E200
26 error true true: -/all
```

is a very unhelpful error message, so you should probably ask the folks running the cnpmjs registry what's up -- that shouldn't be getting returned as an error to the CLI. It's possible that their mirror isn't set up for search?

**Comment by ehsalazar** [comment]
We haven’t heard back and we’re trying to clean up some issues. Were you able to get it figured out with the help of the cnpmjs registry folks? If this is still a problem, can you please reply and let us know?
