### ISSUE TITLE
npm install failed on widows 7

### ISSUE THREAD

**Issue by makandiarra** [npm/npm#9493]
```
$ node -v
v0.12.7
```

```
$ npm -v
2.11.3
```

```
$ npm install
npm WARN package.json tamani@0.0.1 No repository field.
npm WARN package.json tamani@0.0.1 No license field.

> v8-profiler@5.2.12 preinstall C:\apps\tamani\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-profiler
>


> v8-debug@0.4.6 preinstall C:\apps\tamani\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-debug
>


> ws@0.4.32 install C:\apps\tamani\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)


C:\apps\tamani\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\ws>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
npm WARN optional dep failed, continuing default-browser-id@1.0.2
npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"0.12.7","npm":"2.11.3"})

> v8-profiler@5.2.12 install C:\apps\tamani\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-profiler
> node-pre-gyp install --fallback-to-build

[v8-profiler] Success: "C:\apps\tamani\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-profiler\build\profiler\v5.2.12\node-v14-win32-x64\profiler.node" is installed via remote

> v8-debug@0.4.6 install C:\apps\tamani\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-debug
> node-pre-gyp install --fallback-to-build

gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\apps\tamani\node_modules\npm\node_modules\node-gyp\lib\configure.js:114:14)
gyp ERR! stack     at C:\apps\tamani\node_modules\npm\node_modules\node-gyp\lib\configure.js:69:11
gyp ERR! stack     at FSReqWrap.oncomplete (evalmachine.<anonymous>:95:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\apps\\tamani\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\apps\\tamani\\node_modules\\grunt-node-inspector\\node_modules\\node-inspector\\node_modules\\v8-debug\\build\\debug\\v0.4.6\\node-v14-win32-x64\\debug.node" "--module_name=debug" "--module_path=C:\\apps\\tamani\\node_modules\\grunt-node-inspector\\node_modules\\node-inspector\\node_modules\\v8-debug\\build\\debug\\v0.4.6\\node-v14-win32-x64"
gyp ERR! cwd C:\apps\tamani\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-debug
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\apps\tamani\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\apps\tamani\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-debug\build\debug\v0.4.6\node-v14-win32-x64\debug.node --module_name=debug --module_path=C:\apps\tamani\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-debug\build\debug\v0.4.6\node-v14-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\apps\tamani\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-debug\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:1015:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
node-pre-gyp ERR! System Windows_NT 6.1.7601
node-pre-gyp ERR! command "node" "C:\\apps\\tamani\\node_modules\\grunt-node-inspector\\node_modules\\node-inspector\\node_modules\\v8-debug\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\apps\tamani\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-debug
node-pre-gyp ERR! node -v v0.12.7
node-pre-gyp ERR! node-pre-gyp -v v0.6.9
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\apps\tamani\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\apps\tamani\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-debug\build\debug\v0.4.6\node-v14-win32-x64\debug.node --module_name=debug --module_path=C:\apps\tamani\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-debug\build\debug\v0.4.6\node-v14-win32-x64' (1)
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! v8-debug@0.4.6 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the v8-debug@0.4.6 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the v8-debug package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls v8-debug
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\apps\tamani\npm-debug.log
```

**Comment by othiym23** [comment]
It looks like the `node-gyp` tool used by npm to build native modules can't find Python, which it needs to run. Take a look at the [`node-gyp` installation instructions for Windows](https://github.com/nodejs/node-gyp#installation) and see if that helps you get things working.

**Comment by capaj** [comment]
@makandiarra you should close this bug. This is not a bug with NPM. NPM requires python on your host system.

**Comment by makandiarra** [comment]
This issue was fixed by following
https://github.com/nodejs/node-gyp#installation guide you've send me..

Thank you.

**Comment by makandiarra** [comment]
This issue was fixed by following https://github.com/nodejs/node-gyp#installation guide.

Thank you.
