### ISSUE TITLE
npm publish failed with message: "npm ERR! network and is related to network connectivity."

### ISSUE THREAD

**Issue by easyfan** [npm/npm#9501]
In Windows 7, npm publish failed with messages as below:
npm ERR! publish Failed PUT undefined
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\nodejs\\\\node.exe" "D:\\nodejs\\node_modules\\npm\\bin\\npm-
cli.js" "publish"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! syscall read

npm ERR! network read ECONNRESET
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settin
gs.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\IBM_ADMIN\git\nodejs-persistable-scheduler\npm-debug.log

**Comment by easyfan** [comment]
The content of C:\Users\IBM_ADMIN\git\nodejs-persistable-scheduler\npm-debug.log:
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\nodejs\\\\node.exe',
1 verbose cli   'D:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'publish' ]
2 info using npm@2.11.3
3 info using node@v0.12.7
4 verbose publish [ '.' ]
5 silly cache add args [ '.', null ]
6 verbose cache add spec .
7 silly cache add parsed spec { raw: '.',
7 silly cache add   scope: null,
7 silly cache add   name: null,
7 silly cache add   rawSpec: '.',
7 silly cache add   spec: 'C:\\Users\\IBM_ADMIN\\git\\nodejs-persistable-scheduler',
7 silly cache add   type: 'directory' }
8 verbose addLocalDirectory C:\Users\IBM_ADMIN\AppData\Roaming\npm-cache\nodejs-persistable-scheduler\0.0.1\package.tgz not in flight; packing
9 verbose tar pack [ 'C:\\Users\\IBM_ADMIN\\AppData\\Roaming\\npm-cache\\nodejs-persistable-scheduler\\0.0.1\\package.tgz',
9 verbose tar pack   'C:\\Users\\IBM_ADMIN\\git\\nodejs-persistable-scheduler' ]
10 verbose tarball C:\Users\IBM_ADMIN\AppData\Roaming\npm-cache\nodejs-persistable-scheduler\0.0.1\package.tgz
11 verbose folder C:\Users\IBM_ADMIN\git\nodejs-persistable-scheduler
12 info prepublish nodejs-persistable-scheduler@0.0.1
13 verbose addLocalTarball adding from inside cache C:\Users\IBM_ADMIN\AppData\Roaming\npm-cache\nodejs-persistable-scheduler\0.0.1\package.tgz
14 silly cache afterAdd nodejs-persistable-scheduler@0.0.1
15 verbose afterAdd C:\Users\IBM_ADMIN\AppData\Roaming\npm-cache\nodejs-persistable-scheduler\0.0.1\package\package.json not in flight; writing
16 verbose afterAdd C:\Users\IBM_ADMIN\AppData\Roaming\npm-cache\nodejs-persistable-scheduler\0.0.1\package\package.json written
17 silly publish { name: 'nodejs-persistable-scheduler',
17 silly publish   version: '0.0.1',
17 silly publish   description: 'A nodejs based, persist by mysql, timely and repeatable task framework;',
17 silly publish   main: 'index.js',
17 silly publish   scripts: { test: 'echo \'Error: no test specified\' && exit 1' },
17 silly publish   repository:
17 silly publish    { type: 'git',
17 silly publish      url: 'git://github.com/easyfan/nodejs-persistable-scheduler.git' },
17 silly publish   keywords:
17 silly publish    [ 'scheduler',
17 silly publish      'task',
17 silly publish      'timer',
17 silly publish      'repeatable',
17 silly publish      'persistency',
17 silly publish      'mysql' ],
17 silly publish   author:
17 silly publish    { name: 'Easyfan Zheng',
17 silly publish      email: 'zheng.easyfan@gmail.com',
17 silly publish      url: 'http://zhengeasyfan.blogspot.com' },
17 silly publish   license: 'Apache License',
17 silly publish   bugs: { url: 'https://github.com/easyfan/nodejs-persistable-scheduler/issues' },
17 silly publish   homepage: 'https://github.com/easyfan/nodejs-persistable-scheduler#readme',
17 silly publish   dependencies: { mysql: '^2.9.0', q: '^1.4.1' },
17 silly publish   directories: { test: 'test' },
17 silly publish   readme: '# nodejs-persistable-scheduler\r\n==============================\r\n\r\n## Summary:\r\nA nodejs based, persist by mysql, timely task framework;\r\n\r\n## Installation:\r\n\r\n## Best Prectice:\r\n\r\n## Tests:\r\n\r\n## Contributing:\r\n\r\n## Release History:',
17 silly publish   readmeFilename: 'README.md',
17 silly publish   gitHead: 'd24f4d87fd9a0f4d2588a7191ac2a4db16daf443',
17 silly publish   _id: 'nodejs-persistable-scheduler@0.0.1',
17 silly publish   _shasum: 'a0f003ba4befc3d344579d05750704c815c56ddd',
17 silly publish   _from: '.' }
18 verbose getPublishConfig undefined
19 silly mapToRegistry name nodejs-persistable-scheduler
20 silly mapToRegistry using default registry
21 silly mapToRegistry registry https://registry.npmjs.org/
22 silly mapToRegistry uri https://registry.npmjs.org/nodejs-persistable-scheduler
23 verbose publish registryBase https://registry.npmjs.org/
24 silly publish uploading C:\Users\IBM_ADMIN\AppData\Roaming\npm-cache\nodejs-persistable-scheduler\0.0.1\package.tgz
25 verbose request uri https://registry.npmjs.org/nodejs-persistable-scheduler
26 verbose request sending authorization for write operation
27 info attempt registry request try #1 at 18:27:59
28 verbose request using bearer token for auth
29 verbose request id 8aa8f30cb4785189
30 http request PUT https://registry.npmjs.org/nodejs-persistable-scheduler
31 info retry will retry, error on last attempt: Error: read ECONNRESET
32 info attempt registry request try #2 at 18:29:00
33 verbose request using bearer token for auth
34 http request PUT https://registry.npmjs.org/nodejs-persistable-scheduler
35 info retry will retry, error on last attempt: Error: read ECONNRESET
36 info attempt registry request try #3 at 18:30:44
37 verbose request using bearer token for auth
38 http request PUT https://registry.npmjs.org/nodejs-persistable-scheduler
39 verbose request invalidating C:\Users\IBM_ADMIN\AppData\Roaming\npm-cache\registry.npmjs.org\nodejs-persistable-scheduler on PUT
40 error publish Failed PUT undefined
41 verbose stack Error: read ECONNRESET
41 verbose stack     at exports._errnoException (util.js:746:11)
41 verbose stack     at TCP.onread (net.js:559:26)
42 verbose cwd C:\Users\IBM_ADMIN\git\nodejs-persistable-scheduler
43 error Windows_NT 6.1.7601
44 error argv "D:\\nodejs\\\\node.exe" "D:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "publish"
45 error node v0.12.7
46 error npm  v2.11.3
47 error code ECONNRESET
48 error errno ECONNRESET
49 error syscall read
50 error network read ECONNRESET
50 error network This is most likely not a problem with npm itself
50 error network and is related to network connectivity.
50 error network In most cases you are behind a proxy or have bad network settings.
50 error network
50 error network If you are behind a proxy, please make sure that the
50 error network 'proxy' config is set properly.  See: 'npm help config'
51 verbose exit [ 1, true ]

**Comment by easyfan** [comment]
Seems a network connection issue. Can not reproduce it. Close it.
