### ISSUE TITLE
nodejs 4.0.0-rc.1on Windows: cannot npm link

### ISSUE THREAD

**Issue by jnfingerle** [npm/npm#9512]
Trying out the nodejs 4.0.0 RC.1 on a Windows machine unsing npm link I get

```
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "link"
npm ERR! node v4.0.0-rc.1
npm ERR! npm  v2.14.2
npm ERR! code ENOTSUP
npm ERR! errno 129

npm ERR! nospc npm link not supported on windows prior to node 0.7.9
npm ERR! nospc This is most likely not a problem with npm itself
npm ERR! nospc and is related to insufficient space on your system.
```

Log:
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'link' ]
2 info using npm@2.14.2
3 info using node@v4.0.0-rc.1
4 verbose stack Error: npm link not supported on windows prior to node 0.7.9
4 verbose stack     at EventEmitter.link (C:\Program Files\nodejs\node_modules\npm\lib\link.js:33:15)
4 verbose stack     at Object.commandCache.(anonymous function) (C:\Program Files\nodejs\node_modules\npm\lib\npm.js:220:11)
4 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js:72:28)
4 verbose stack     at doNTCallback0 (node.js:407:9)
4 verbose stack     at process._tickCallback (node.js:336:13)
5 verbose cwd C:\somewhere
6 error Windows_NT 6.1.7601
7 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "link"
8 error node v4.0.0-rc.1
9 error npm  v2.14.2
10 error code ENOTSUP
11 error errno 129
12 error nospc npm link not supported on windows prior to node 0.7.9
12 error nospc This is most likely not a problem with npm itself
12 error nospc and is related to insufficient space on your system.
13 verbose exit [ 129, true ]
```

According to https://github.com/nodejs/node/issues/2719 this is an npm problem.

**Comment by jnfingerle** [comment]
Ok, sorry, I'm blind an this is a duplicate of https://github.com/npm/npm/issues/9505 :-/
