### ISSUE TITLE
Getting "throw err"

### ISSUE THREAD

**Issue by cedon** [npm/npm#9525]
I just installed NodeJS 4.0 and when I run npm, trying to do anything, I get the following:

module.js:338
    throw err;
    ^

Error: Cannot find module 'npmlog'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at C:\Users\Cedon\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js:18:11
    at Object.<anonymous> (C:\Users\Cedon\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js:75:3)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

**Comment by cedon** [comment]
Forgot to mention, this is under Windows 10 x64

**Comment by KenanY** [comment]
This appears to have been resolved over at https://github.com/nodejs/node/issues/2814.

**Comment by cedon** [comment]
Yup. The suggestion I got over there fixed it. I thought I had swept everything out but missed that one location. After I nuked it I did npm -v and it worked just fine.
