### ISSUE TITLE
Fetch from https://github via digest proxy

### ISSUE THREAD

**Issue by MrEfrem** [npm/npm#9530]
```
28275 http fetch GET https://github.com/rase-/node-XMLHttpRequest/archive/a6b6f2.tar.gz
28276 info retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=Parse Error
28277 info attempt registry request try #3 at 10:19:28
```

.npmrc:

```
strict-ssl = false
proxy=http://username:pwd@proxy:3128/
https-proxy=http://username:pwd@proxy:3128/
```

**Comment by smikes** [comment]
Is this still a problem for you?

Could you please upload your **complete** npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

It looks like you are having some sort of proxy problem, but I can't diagnose it further without more of your npm-debug.log file.  If you are using the atom editor and its package manager `apm`, you may find this thread helpful: https://github.com/atom/apm/issues/322

Thanks!

**Comment by MrEfrem** [comment]
https://gist.github.com/MrEfrem/dd40139c98e3140febfe
Start from 184406 line.
But you won't see a problem there. I to you precisely designated it above. 
'http fetch GET' isn't able to work with DIGEST proxy probably

**Comment by smikes** [comment]
Downloads of packages hosted on the `npm` repository seem to be working for you.  Since all the requests are handled through the `request` module, which respects your proxy, it looks to me like the problem is related to the combination of (your proxy, github archive URL)

Can you download manually through your DIGEST proxy?

```
$ http_proxy=<whatever> wget https://github.com/rase-/node-XMLHttpRequest/archive/a6b6f2.tar.gz
```

```
184449 error Linux 3.14.14-gentoo_amd64
184450 error argv "/usr/bin/node" "/usr/bin/npm" "install" "-d"
184451 error node v0.12.7
184452 error npm  v2.11.3
184453 error code ELIFECYCLE
```

It looks like you're using a somewhat older `npm` - can you try updating?

```
$ sudo npm i -g npm@latest
```

**Comment by MrEfrem** [comment]
I updated npm to the latest version (2.14.3) and I receive the same error.

I try manually:
```
https_proxy=http://proxy:3128 http_proxy=http://proxy:3128 wget --proxy-user=user --proxy-password=pwd https://github.com/rase-/node-XMLHttpRequest/archive/a6b6f2.tar.gz
--2015-09-14 09:55:00--  https://github.com/rase-/node-XMLHttpRequest/archive/a6b6f2.tar.gz
Resolving proxy... xx:xx:xx:xx
Connecting to proxy|xx:xx:xx:xx|:3128... connected.
Proxy tunneling failed: Proxy Authentication RequiredUnable to establish SSL connection
```
Doesn't work because wget too isn't able to work with DIGEST proxy!

**Comment by martinheidegger** [comment]
This is still an issue for me with `npm 4.1.1`

**Comment by MrEfrem** [comment]
@smikes something will be undertaken to solve this problem? Or hammered on it?

**Comment by Barryrowe** [comment]
Is there another issue open on this anywhere? 

Pulling from the npm registry appears to respect the proxy set with either  the proxy set in npm config, or http_proxy environment variable, but when something requests tarball from github this is not respected, or SSL is rejected. Attached log below.

This is a major pain for us behind a corporate proxy (NTLM authenticated) I know npm generally behind a proxy has been discussed to much length in several locations, but this seems specific to whatever portion of the install pipeline where packages might pull other external resources. I've been assuming this was just an issue with individual postinstall scripts, but verbose logs seems to suggest this is something in the npm install pipeline that's failing to get through the proxy. 

```
npm info attempt registry request try #2 at 11:28:23 AM
npm http fetch GET https://github.com/hegemonic/taffydb/tarball/7d100bcee0e997ee4977e273cdce60bd8933050e
npm info retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=Parse Error
fetchMetadata -> network  | |####################################-----------------------------------------------------------------------------------|
npm info attempt registry request try #3 at 11:29:23 AM
npm http fetch GET https://github.com/hegemonic/taffydb/tarball/7d100bcee0e997ee4977e273cdce60bd8933050e
npm ERR! fetch failed https://github.com/hegemonic/taffydb/tarball/7d100bcee0e997ee4977e273cdce60bd8933050e
npm WARN retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=Parse Error
npm info retry fetch attempt 2 at 11:29:33 AM
npm info attempt registry request try #1 at 11:29:33 AM
npm http fetch GET https://github.com/hegemonic/taffydb/tarball/7d100bcee0e997ee4977e273cdce60bd8933050e
npm info retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=Parse Error
npm info attempt registry request try #2 at 11:29:43 AM
npm http fetch GET https://github.com/hegemonic/taffydb/tarball/7d100bcee0e997ee4977e273cdce60bd8933050e
npm info retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=Parse Error
npm info attempt registry request try #3 at 11:30:43 AM
npm http fetch GET https://github.com/hegemonic/taffydb/tarball/7d100bcee0e997ee4977e273cdce60bd8933050e
npm ERR! fetch failed https://github.com/hegemonic/taffydb/tarball/7d100bcee0e997ee4977e273cdce60bd8933050e
npm WARN retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=Parse Error
npm info retry fetch attempt 3 at 11:31:43 AM
npm info attempt registry request try #1 at 11:31:43 AM
npm http fetch GET https://github.com/hegemonic/taffydb/tarball/7d100bcee0e997ee4977e273cdce60bd8933050e
npm info retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=Parse Error
npm info attempt registry request try #2 at 11:31:55 AM
npm http fetch GET https://github.com/hegemonic/taffydb/tarball/7d100bcee0e997ee4977e273cdce60bd8933050e
npm info retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=Parse Error
npm info attempt registry request try #3 at 11:32:55 AM
npm http fetch GET https://github.com/hegemonic/taffydb/tarball/7d100bcee0e997ee4977e273cdce60bd8933050e
npm ERR! fetch failed https://github.com/hegemonic/taffydb/tarball/7d100bcee0e997ee4977e273cdce60bd8933050e
npm verb stack Error: tunneling socket could not be established, cause=Parse Error
npm verb stack     at ClientRequest.onError (C:\Users\E027694\AppData\Roaming\npm\node_modules\npm\node_modules\request\node_modules\tunnel-agent\inde
x.js:176:17)
npm verb stack     at ClientRequest.g (events.js:260:16)
npm verb stack     at emitOne (events.js:77:13)
npm verb stack     at ClientRequest.emit (events.js:169:7)
npm verb stack     at Socket.socketOnData (_http_client.js:316:9)
npm verb stack     at emitOne (events.js:77:13)
npm verb stack     at Socket.emit (events.js:169:7)
npm verb stack     at readableAddChunk (_stream_readable.js:146:16)
npm verb stack     at Socket.Readable.push (_stream_readable.js:110:10)
npm verb stack     at TCP.onread (net.js:523:20)
npm verb cwd D:\git-repos\armadilo\ArmadiloApp
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\E027694\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "--verbo
se"
npm ERR! node v5.0.0
npm ERR! npm  v3.8.8
npm ERR! code ECONNRESET
```



[npm-debug.log.txt](https://github.com/npm/npm/files/305124/npm-debug.log.txt)
