### ISSUE TITLE
Having issue install ioredis for Linux ubuntu

### ISSUE THREAD

**Issue by osherdo** [npm/npm#9536]
Hi.

I am having a problem with installing a package called 'ioredis' on Laravel project in Ubuntu 14.04.

it gives me the following error:

```
s-application$ npm install ioredis
npm http GET https://registry.npmjs.org/ioredis
npm http 304 https://registry.npmjs.org/ioredis
npm WARN engine ioredis@1.8.0: wanted: {"node":">= 0.10.16","iojs":">= 1.0.0"} (current: {"node":"v0.8.15","npm":"1.1.66"})
npm http GET https://registry.npmjs.org/bluebird
npm http GET https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/double-ended-queue
npm http GET https://registry.npmjs.org/flexbuffer/0.0.6
npm http GET https://registry.npmjs.org/lodash
npm http 304 https://registry.npmjs.org/bluebird
npm ERR! Error: No compatible version found: bluebird@'^2.9.21'
npm ERR! Valid install targets:
npm ERR! ["0.7.1-1","0.7.1-2","0.7.1-3","0.7.1-4","0.7.1-5","0.7.2-0","0.7.3-0","0.7.4-0","0.7.4-1","0.7.5-0","0.7.6-0","0.7.7-0","0.7.7-1","0.7.8-0","0.7.8-1","0.7.9-0","0.7.9-1","0.7.10-0","0.7.10-1","0.7.11-0","0.7.12-0","0.7.12-1","0.7.12-2","0.8.0-0","0.8.0-1","0.8.0-2","0.8.0-3","0.8.1-0","0.8.2-0","0.8.2-1","0.8.2-2","0.8.3-0","0.8.3-1","0.8.3-2","0.8.3-3","0.8.4-0","0.8.4-1","0.8.5-0","0.8.5-1","0.9.0-0","0.9.1-0","0.9.1-1","0.9.2-0","0.9.2-1","0.9.3-0","0.9.4-0","0.9.4-1","0.9.5-0","0.9.6-0","0.9.7-0","0.9.8-0","0.9.9-0","0.9.10-0","0.9.10-1","0.9.11-0","0.9.11-1","0.10.0-0","0.10.0-1","0.10.1-0","0.10.2-0","0.10.2-1","0.10.3-0","0.10.4-0","0.10.4-1","0.10.5-0","0.10.6-0","0.10.7-0","0.10.8-0","0.10.9-0","0.10.9-1","0.10.10-0","0.10.11-0","0.10.11-1","0.10.11-2","0.10.11-4","0.10.12-0","0.10.13-0","0.10.13-1","0.10.14-0","0.11.0-0","0.11.1-0","0.11.2-0","0.11.3-0","0.11.4-0","0.11.4-1","0.11.5-0","0.11.5-1","0.11.6-0","1.0.0","1.0.1","1.0.2","1.0.3","1.0.4","1.0.5","1.0.7","1.0.8","1.1.0","1.1.1","1.2.0","1.2.1","1.2.2","1.2.3","1.2.4","2.0.2","2.0.3","2.0.4","2.0.5","2.0.6","2.0.7","2.1.1","2.1.2","2.1.3","2.2.0","2.2.1","2.2.2","2.3.0","2.3.1","2.3.2","2.3.3","2.3.4","2.3.5","0.11.6","2.3.6","2.3.9","2.3.10","2.3.11","2.4.0","2.4.1","2.4.2","2.4.3","2.5.0","2.5.1","2.5.2","2.5.3","2.6.0","2.6.1","2.6.2","2.6.3","2.6.4","2.7.0","2.7.1","2.8.0","2.8.1","2.8.2","2.9.0","2.9.1","2.9.2","2.9.3","2.9.4","2.9.5","2.9.6","2.9.7","2.9.8","2.9.9","2.9.10","2.9.11","2.9.12","2.9.13","2.9.14","2.9.15","2.9.16","2.9.17","2.9.18","2.9.19","2.9.20","2.9.21","2.9.22","2.9.23","2.9.24","2.9.25","2.9.26","2.9.27","2.9.28","2.9.29","2.9.30","2.9.31","2.9.32","2.9.33","2.9.34","2.10.0"]
npm ERR!     at installTargetsError (/usr/local/lib/node_modules/npm/lib/cache.js:563:10)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:478:10
npm ERR!     at saved (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:218:7
npm ERR!     at Object.oncomplete (fs.js:297:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.19.0-25-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "ioredis"
npm ERR! cwd /opt/lampp/htdocs/laravel-projects/sports-application
npm ERR! node -v v0.8.15
npm ERR! npm -v 1.1.66
npm ERR! Error: EACCES, open 'npm-debug.log'
npm ERR!  { [Error: EACCES, open 'npm-debug.log'] errno: 3, code: 'EACCES', path: 'npm-debug.log' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Linux 3.19.0-25-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "ioredis"
npm ERR! cwd /opt/lampp/htdocs/laravel-projects/sports-application
npm ERR! node -v v0.8.15
npm ERR! npm -v 1.1.66
npm ERR! path npm-debug.log
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, open 'npm-debug.log'
npm http 304 https://registry.npmjs.org/debug
npm http 304 https://registry.npmjs.org/double-ended-queue
npm http 304 https://registry.npmjs.org/lodash
npm http 304 https://registry.npmjs.org/flexbuffer/0.0.6
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /opt/lampp/htdocs/laravel-projects/sports-application/npm-debug.log
npm ERR! not ok code 0
```

Eventually when I type 'npm list' - the package does not appear there.

What should I do next to install it?

**Comment by KenanY** [comment]
@osherdo `npm@1.1` is very old and has not been supported for years. It does not support the `^` SemVer operator you see here:

```
npm ERR! Error: No compatible version found: bluebird@'^2.9.21'
```

hence the error you are receiving. I would **highly** recommend you [upgrade Node.js](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-node) and [upgrade `npm`](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) because you are missing out on _years_ of new features and bug fixes.

**Comment by osherdo** [comment]
Thank you. That's what I did and it works just fine.

https://www.digitalocean.com/community/tutorials/how-to-install-node-js-with-nvm-node-version-manager-on-a-vps#installation 

That's a good way to solve the problem.

**Comment by KenanY** [comment]
Closing as resolved.
