### ISSUE TITLE
Error Installing Cordova Using Node js

### ISSUE THREAD

**Issue by joelmm1** [npm/npm#9541]
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'cordova' ]
2 info using npm@2.14.2
3 info using node@v4.0.0
4 verbose config Skipping project config: C:\Users\Joel/.npmrc. (matches userconfig)
5 verbose install initial load of C:\Users\Joel\package.json
6 verbose readDependencies loading dependencies from C:\Users\Joel\package.json
7 silly cache add args [ 'cordova', null ]
8 verbose cache add spec cordova
9 silly cache add parsed spec Result {
9 silly cache add   raw: 'cordova',
9 silly cache add   scope: null,
9 silly cache add   name: 'cordova',
9 silly cache add   rawSpec: '',
9 silly cache add   spec: '*',
9 silly cache add   type: 'range' }
10 silly addNamed cordova@*
11 verbose addNamed "*" is a valid semver range for cordova
12 silly addNameRange { name: 'cordova', range: '*', hasData: false }
13 silly mapToRegistry name cordova
14 silly mapToRegistry using default registry
15 silly mapToRegistry registry http://registry.npmjs.org/
16 silly mapToRegistry uri http://registry.npmjs.org/cordova
17 verbose addNameRange registry:http://registry.npmjs.org/cordova not in flight; fetching
18 verbose request uri http://registry.npmjs.org/cordova
19 verbose request no auth needed
20 info attempt registry request try #1 at 2:22:38 PM
21 verbose request id 7c5b0eecef92410f
22 http request GET http://registry.npmjs.org/cordova
23 http 200 http://registry.npmjs.org/cordova
24 verbose bad json Raw HTTP Request received by this server:
24 verbose bad json
24 verbose bad json GET http://registry.npmjs.org/cordova HTTP/1.1
24 verbose bad json accept-encoding: gzip
24 verbose bad json version: 2.14.2
24 verbose bad json accept: application/json
24 verbose bad json referer: install cordova
24 verbose bad json npm-session: 7c5b0eecef92410f
24 verbose bad json user-agent: npm/2.14.2 node/v4.0.0 win32 x64
24 verbose bad json host: registry.npmjs.org
24 verbose bad json Connection: keep-alive
25 error registry error parsing json
26 verbose headers { server: 'Apache',
26 verbose headers   connection: 'close',
26 verbose headers   'content-type': 'text/html' }
27 silly get cb [ 200,
27 silly get   { server: 'Apache',
27 silly get     connection: 'close',
27 silly get     'content-type': 'text/html' } ]
28 verbose stack SyntaxError: Unexpected token R
28 verbose stack
28 verbose stack Raw HTTP Request received by this server:
28 verbose stack
28 verbose stack GET http://registry.npmjs.org/cordova HTTP/1.1
28 verbose stack accept-encoding: gzip
28 verbose stack version: 2.14.2
28 verbose stack accept: application/json
28 verbose stack referer: install cordova
28 verbose stack npm-session: 7c5b0eecef92410f
28 verbose stack user-agent: npm/2.14.2 node/v4.0.0 win32 x64
28 verbose stack host: registry.npmjs.org
28 verbose stack Connection: keep-alive
28 verbose stack
28 verbose stack
28 verbose stack
28 verbose stack     at Object.parse (native)
28 verbose stack     at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:198:23)
28 verbose stack     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:171:14)
28 verbose stack     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:198:22)
28 verbose stack     at emitTwo (events.js:87:13)
28 verbose stack     at Request.emit (events.js:172:7)
28 verbose stack     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1073:14)
28 verbose stack     at emitOne (events.js:82:20)
28 verbose stack     at Request.emit (events.js:169:7)
28 verbose stack     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1019:12)
29 verbose cwd C:\Users\Joel
30 error Windows_NT 6.1.7600
31 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "cordova"
32 error node v4.0.0
33 error npm  v2.14.2
34 error Unexpected token R
34 error
34 error Raw HTTP Request received by this server:
34 error
34 error GET http://registry.npmjs.org/cordova HTTP/1.1
34 error accept-encoding: gzip
34 error version: 2.14.2
34 error accept: application/json
34 error referer: install cordova
34 error npm-session: 7c5b0eecef92410f
34 error user-agent: npm/2.14.2 node/v4.0.0 win32 x64
34 error host: registry.npmjs.org
34 error Connection: keep-alive
35 error If you need help, you may report this error at:
35 error     <https://github.com/npm/npm/issues>
36 verbose exit [ 1, true ]
```

I've tried 
1) npm clear cache
2) Installing Nodejs and restarting the computer 

I cannot figure out why it is not working. Please advice.

**Comment by smikes** [comment]
It looks like you may have a proxy server on your network that requires you to log in.  Do you have to do anything like that when you use your browser?

If so, you need to also tell `npm` about your proxy by setting the `http_proxy` config variable appropriately.

**Comment by joelmm1** [comment]
Hey. Thanks. However I am not prompted to log in when using the browser. Also, I tried to check my proxy here: whatismyproxy.com. I got the response, "No proxy detected". Any ideas on the way forward? :)

**Comment by smikes** [comment]
Can you load this page in your web browser:

http://registry.npmjs.com/cordova

?

That is the request npm is trying to make, but failing.  Since you are on Windows, I don't know what to recommend -- if you were on a Unix variant you could check your command-line connectivity with:

curl http://registry.npmjs.com/cordova | wc

**Comment by joelmm1** [comment]
Yes I can load the page: http://registry.npmjs.com/cordova in my browser.

**Comment by othiym23** [comment]
There is definitely a proxy, probably transparent, between the install host and npm's registry:

```
24 verbose bad json Raw HTTP Request received by this server:
24 verbose bad json
24 verbose bad json GET http://registry.npmjs.org/cordova HTTP/1.1
24 verbose bad json accept-encoding: gzip
24 verbose bad json version: 2.14.2
24 verbose bad json accept: application/json
24 verbose bad json referer: install cordova
24 verbose bad json npm-session: 7c5b0eecef92410f
24 verbose bad json user-agent: npm/2.14.2 node/v4.0.0 win32 x64
24 verbose bad json host: registry.npmjs.org
24 verbose bad json Connection: keep-alive
```

This is not a response that the npm registry (or the CDN in front of it) will ever return. That's a proxy looking for an HTTP `CONNECT` request.

Have you tried looking at your browser's proxy settings? And do you have a command-line tool like `curl` accessible on that machine? [Here's where you can download](http://curl.haxx.se/download.html) a version for Windows that you can use for testing. Sites like whatismyproxy.com often can't detect transparent proxies.

**Comment by busches** [comment]
@kenany no response in eight months

**Comment by KenanY** [comment]
Closing as abandoned.
