### ISSUE TITLE
verbose stack TypeError: Arguments to path.resolve must be strings error

### ISSUE THREAD

**Issue by bhaveshbhatkar** [npm/npm#9548]
i had a directory under .gitignore,  I removed it and pushed to git as i needed to. 
After that when i try to publish the package i am getting below error

```
verbose stack TypeError: Arguments to path.resolve must be strings
verbose stack TypeError: Arguments to path.resolve must be strings
14 verbose stack     at Object.posix.resolve (path.js:439:13)
14 verbose stack     at Packer.applyIgnores (/usr/local/lib/node_modules/npm/node_modules/fstream-npm/fstream-npm.js:109:59)
14 verbose stack     at Packer.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/fstream-npm/node_modules/fstream-ignore/ignore.js:181:17)
14 verbose stack     at Array.filter (native)
14 verbose stack     at Packer.IgnoreReader.filterEntries (/usr/local/lib/node_modules/npm/node_modules/fstream-npm/node_modules/fstream-ignore/ignore.js:179:31)
14 verbose stack     at Packer.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/fstream-npm/node_modules/fstream-ignore/ignore.js:92:12)
14 verbose stack     at Packer.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/fstream-npm/node_modules/fstream-ignore/ignore.js:134:5)
14 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:76:16
14 verbose stack     at fs.js:334:14
```

**Comment by othiym23** [comment]
What versions of Node and npm are you running? It's hard to say what you're encountering from this stacktrace alone.

**Comment by JONBRWN** [comment]
@othiym23 getting same error when trying to pack, here's the full debug log:

```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'pack' ]
2 info using npm@2.12.1
3 info using node@v0.12.7
4 verbose node symlink /usr/local/bin/node
5 silly cache add args [ '.', null ]
6 verbose cache add spec .
7 silly cache add parsed spec { raw: '.',
7 silly cache add   scope: null,
7 silly cache add   name: null,
7 silly cache add   rawSpec: '.',
7 silly cache add   spec: '/Users/jonbrwn/code/test/repo/server/client',
7 silly cache add   type: 'directory' }
8 verbose addLocalDirectory /Users/jonbrwn/.npm/my-client/0.0.0/package.tgz not in flight; packing
9 verbose tar pack [ '/Users/jonbrwn/.npm/my-client/0.0.0/package.tgz',
9 verbose tar pack   '/Users/jonbrwn/code/test/repo/server/client' ]
10 verbose tarball /Users/jonbrwn/.npm/my-client/0.0.0/package.tgz
11 verbose folder /Users/jonbrwn/code/test/repo/server/client
12 info prepublish my-client@0.0.0
13 verbose stack TypeError: Arguments to path.resolve must be strings
13 verbose stack     at Object.posix.resolve (path.js:439:13)
13 verbose stack     at Packer.applyIgnores (/usr/local/lib/node_modules/npm/node_modules/fstream-npm/fstream-npm.js:109:59)
13 verbose stack     at Packer.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/fstream-npm/node_modules/fstream-ignore/ignore.js:181:17)
13 verbose stack     at Array.filter (native)
13 verbose stack     at Packer.IgnoreReader.filterEntries (/usr/local/lib/node_modules/npm/node_modules/fstream-npm/node_modules/fstream-ignore/ignore.js:179:31)
13 verbose stack     at Packer.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/fstream-npm/node_modules/fstream-ignore/ignore.js:92:12)
13 verbose stack     at Packer.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/fstream-npm/node_modules/fstream-ignore/ignore.js:134:5)
13 verbose stack     at fs.js:334:14
13 verbose stack     at FSReqWrap.oncomplete (fs.js:95:15)
14 verbose cwd /Users/jonbrwn/code/test/repo/server/client
15 error Darwin 14.1.0
16 error argv "node" "/usr/local/bin/npm" "pack"
17 error node v0.12.7
18 error npm  v2.12.1
19 error Arguments to path.resolve must be strings
20 error If you need help, you may report this error at:
20 error     <https://github.com/npm/npm/issues>
21 verbose exit [ 1, true ]
```

**Comment by JONBRWN** [comment]
@othiym23 I was able to resolve this by downgrading angular-ui-grid where the main key was removed from the bower.json file.

The culprit was this: 
```
"main": [ './less',
  './ui-grid.css',
  './ui-grid.eot',
  './ui-grid.js',
  './ui-grid.svg',
  './ui-grid.ttf',
  './ui-grid.woff' ]
```

not sure if this is an issue with npm or the ui-grid. If I should move this issue over to them let me know

**Comment by bhaveshbhatkar** [comment]
here are  version as well as details for the error, i believe this is node version issue. 

npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "publish"
npm ERR! node v0.12.7
npm ERR! npm  v2.14.2

npm ERR! Arguments to path.resolve must be strings
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
|
npm ERR! Please include the following file with any support request

**Comment by imjuni** [comment]
I have a same error

npm ERR! Darwin 15.0.0
npm ERR! argv "node" "/Users/bjlee/.nvm/versions/node/v0.12.7/bin/npm" "pack"
npm ERR! node v0.12.7
npm ERR! npm  v2.14.14

npm ERR! Arguments to path.resolve must be strings
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/bjlee/Project/company/released/ex_galleon/npm-debug.log

And attach npm-debug.log file. And I use nvm. 

[npm-debug.log.txt](https://github.com/npm/npm/files/55245/npm-debug.log.txt)

**Comment by rpocklin** [comment]
I had this problem updating an already-published library.  I got this error using node `v0.12.7` with npm `v3.4.1` using nvm I switched to node version `v0.11.14` with npm `v2.0.0` and it worked flawlessly.
