### ISSUE TITLE
`npm publish` gets a cryptic error message "Error: toString failed" when uploading a package that is too big

### ISSUE THREAD

**Issue by ccheever** [npm/npm#9552]
(Using node 4.0.0 and npm 2.14.2)
It took me a little while to figure out what the problem was when I got this error:

```
19 silly mapToRegistry name xde
20 silly mapToRegistry using default registry
21 silly mapToRegistry registry https://registry.npmjs.org/
22 silly mapToRegistry uri https://registry.npmjs.org/xde
23 verbose publish registryBase https://registry.npmjs.org/
24 silly publish uploading /Users/ccheever/.npm/xde/0.2.0/package.tgz
25 verbose stack Error: toString failed
25 verbose stack     at Buffer.toString (buffer.js:359:11)
25 verbose stack     at CachingRegistryClient.putFirst (/Users/ccheever/.nvm/versions/node/v4.0.0/lib/node_modules/npm/node_modules/npm-registry-client/lib/publish.js:97:23)
25 verbose stack     at /Users/ccheever/.nvm/versions/node/v4.0.0/lib/node_modules/npm/node_modules/npm-registry-client/lib/publish.js:54:14
25 verbose stack     at ConcatStream.<anonymous> (/Users/ccheever/.nvm/versions/node/v4.0.0/lib/node_modules/npm/node_modules/npm-registry-client/node_modules/concat-stream/index.js:36:43)
25 verbose stack     at emitNone (events.js:72:20)
25 verbose stack     at ConcatStream.emit (events.js:166:7)
25 verbose stack     at finishMaybe (/Users/ccheever/.nvm/versions/node/v4.0.0/lib/node_modules/npm/node_modules/npm-registry-client/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:502:14)
25 verbose stack     at endWritable (/Users/ccheever/.nvm/versions/node/v4.0.0/lib/node_modules/npm/node_modules/npm-registry-client/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:512:3)
25 verbose stack     at ConcatStream.Writable.end (/Users/ccheever/.nvm/versions/node/v4.0.0/lib/node_modules/npm/node_modules/npm-registry-client/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:477:5)
25 verbose stack     at ReadStream.onend (_stream_readable.js:490:10)
26 verbose cwd /Users/ccheever/xde
27 error Darwin 14.5.0
28 error argv "/Users/ccheever/.nvm/versions/node/v4.0.0/bin/node" "/Users/ccheever/.nvm/versions/node/v4.0.0/bin/npm" "publish"
29 error node v4.0.0
30 error npm  v2.14.2
31 error toString failed
32 error If you need help, you may report this error at:
32 error     <https://github.com/npm/npm/issues>
33 verbose exit [ 1, true ]
```

When I realized that I had hundreds of MB of build artifacts in the root directory of the project that it was trying to upload, I deleted them and the package published fine.

Looks like the gzipped package's size was so large that converting it to a string to upload it was too much for Node (or something along those lines); it would be good to have a clearer error message about what went wrong and what the user needs to do to fix it!

**Comment by KenanY** [comment]
Sounds like https://github.com/npm/npm/issues/6252 / https://github.com/npm/npm/issues/8339.

**Comment by ccheever** [comment]
Sorry - didn't see this specific error message referenced. I'll close this one out as a duplicate. Thanks @KenanY

**Comment by trufae** [comment]
This happens when the directory of the module contains a lot of files (try to copy an iso in there). when the module is so big it fails in this way... it will be good to reopen this issue and fix it properly because the current error is not really obvious at all

**Comment by KenanY** [comment]
@trufae That sounds like both of the issues I have referenced above, both of which are still open issues.

**Comment by trufae** [comment]
Ok thanks :)

**Comment by dgaya** [comment]
This is an V8 String length limitation.

See:
[node #3175](https://github.com/nodejs/node/issues/3175)
Max String length can be queried with:
`process.binding('buffer').kStringMaxLength`
