### ISSUE TITLE
cannot install any of the packages like yo, live-server or npm

### ISSUE THREAD

**Issue by AbhayKD** [npm/npm#9571]
I'm trying to get the packages like yo, npm using the following way but it alwasy shows the same error.I'm using windows 8.1----

```
G:\>npm install -g live-server
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "live-server"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2

npm ERR! error:0906D06C:PEM routines:PEM_read_bio:no start line
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     G:\Interns Assignment\npm-debug.log
```

Following is the npm-debug.log file----

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'live-server' ]
2 info using npm@2.14.2
3 info using node@v4.0.0
4 verbose install initial load of C:\Users\Abhz\AppData\Roaming\npm\package.json
5 verbose readDependencies loading dependencies from C:\Users\Abhz\AppData\Roaming\npm\package.json
6 silly cache add args [ 'live-server', null ]
7 verbose cache add spec live-server
8 silly cache add parsed spec Result {
8 silly cache add   raw: 'live-server',
8 silly cache add   scope: null,
8 silly cache add   name: 'live-server',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: '*',
8 silly cache add   type: 'range' }
9 silly addNamed live-server@*
10 verbose addNamed "*" is a valid semver range for live-server
11 silly addNameRange { name: 'live-server', range: '*', hasData: false }
12 silly mapToRegistry name live-server
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/live-server
16 verbose addNameRange registry:https://registry.npmjs.org/live-server not in flight; fetching
17 verbose request uri https://registry.npmjs.org/live-server
18 verbose request no auth needed
19 info attempt registry request try #1 at 7:30:20 PM
20 verbose request id 06d9b61e24a4bd5b
21 http request GET https://registry.npmjs.org/live-server
22 verbose stack Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
22 verbose stack     at Error (native)
22 verbose stack     at Object.createSecureContext (_tls_common.js:87:19)
22 verbose stack     at Object.exports.connect (_tls_wrap.js:955:21)
22 verbose stack     at Agent.createConnection (https.js:73:22)
22 verbose stack     at Agent.createSocket (_http_agent.js:177:16)
22 verbose stack     at Agent.addRequest (_http_agent.js:146:23)
22 verbose stack     at new ClientRequest (_http_client.js:133:16)
22 verbose stack     at Object.exports.request (http.js:31:10)
22 verbose stack     at Object.exports.request (https.js:163:15)
22 verbose stack     at Request.start (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:803:30)
23 verbose cwd G:\Interns Assignment
24 error Windows_NT 6.3.9600
25 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "live-server"
26 error node v4.0.0
27 error npm  v2.14.2
28 error error:0906D06C:PEM routines:PEM_read_bio:no start line
29 error If you need help, you may report this error at:
29 error     <https://github.com/npm/npm/issues>
30 verbose exit [ 1, true ]
```

Please help me as i'm stuck in this like forever and can;t find a way out... Thanks in advance..

**Comment by KenanY** [comment]
@AbhayKD Hmm, are you behind a proxy?

**Comment by AbhayKD** [comment]
@KenanY  Not that i cant think of. Also i have my firewall and anti-virus turned off in any case those two are causing any problems.

**Comment by iam--nash** [comment]
Im also getting this error after updating my OS from windows 7 to windows 10 . I already followed other thoughts to reinstall and install my node and other stuff related. but still getting this error after I installed it again .

**Comment by skakkar** [comment]
I am also getting following error while trying to install **Yeoman**.

`C:\>npm install -g yo
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "yo"
npm ERR! node v4.4.0
npm ERR! npm  v2.14.20
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! syscall connect

npm ERR! network connect ETIMEDOUT 199.27.79.162:443
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settin
gs.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     C:\npm-debug.log`


I am also not running behind any firewall/proxy.
