### ISSUE TITLE
Confusing error opening homepage of modules

### ISSUE THREAD

**Issue by aredridel** [npm/npm#9573]
```
:; npm home vptree nns mddf
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/lib/node_modules/iojs-bin/node_modules/iojs-darwin-x64/iojs-v3.3.0-darwin-x64/bin/iojs" "/usr/local/bin/npm" "home" "vptree" "nns" "mddf"
npm ERR! node v3.3.0
npm ERR! npm  v3.3.3

npm ERR! Cannot convert undefined or null to object
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/aredridel/Projects/locator-app/locator-server/npm-debug.log
```

Debug log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/lib/node_modules/iojs-bin/node_modules/iojs-darwin-x64/iojs-v3.3.0-darwin-x64/bin/iojs',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'home',
1 verbose cli   'vptree',
1 verbose cli   'nns',
1 verbose cli   'mddf' ]
2 info using npm@3.3.3
3 info using node@v3.3.0
4 silly docs [ 'vptree', 'nns', 'mddf' ]
5 silly getDoc vptree
6 silly fetchPackageMetaData vptree
7 silly getDoc nns
8 silly fetchPackageMetaData nns
9 silly getDoc mddf
10 silly fetchPackageMetaData mddf
11 silly fetchNamedPackageData vptree
12 silly mapToRegistry name vptree
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/vptree
16 silly fetchNamedPackageData nns
17 silly mapToRegistry name nns
18 silly mapToRegistry using default registry
19 silly mapToRegistry registry https://registry.npmjs.org/
20 silly mapToRegistry uri https://registry.npmjs.org/nns
21 silly fetchNamedPackageData mddf
22 silly mapToRegistry name mddf
23 silly mapToRegistry using default registry
24 silly mapToRegistry registry https://registry.npmjs.org/
25 silly mapToRegistry uri https://registry.npmjs.org/mddf
26 verbose request uri https://registry.npmjs.org/vptree
27 verbose request no auth needed
28 info attempt registry request try #1 at 4:19:17 PM
29 verbose request using bearer token for auth
30 verbose request id f8eef29f441c74e9
31 http request GET https://registry.npmjs.org/vptree
32 verbose request uri https://registry.npmjs.org/nns
33 verbose request no auth needed
34 info attempt registry request try #1 at 4:19:17 PM
35 verbose request using bearer token for auth
36 http request GET https://registry.npmjs.org/nns
37 verbose request uri https://registry.npmjs.org/mddf
38 verbose request no auth needed
39 info attempt registry request try #1 at 4:19:17 PM
40 verbose request using bearer token for auth
41 http request GET https://registry.npmjs.org/mddf
42 http 200 https://registry.npmjs.org/vptree
43 silly get cb [ 200,
43 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
43 silly get     etag: '"602RVWD0A886GKUH3GZFTIG5E"',
43 silly get     'content-type': 'application/json',
43 silly get     'cache-control': 'max-age=60',
43 silly get     'content-length': '6157',
43 silly get     'accept-ranges': 'bytes',
43 silly get     date: 'Sun, 13 Sep 2015 20:19:16 GMT',
43 silly get     via: '1.1 varnish',
43 silly get     connection: 'keep-alive',
43 silly get     'x-served-by': 'cache-atl6234-ATL',
43 silly get     'x-cache': 'MISS',
43 silly get     'x-cache-hits': '0',
43 silly get     'x-timer': 'S1442175555.922243,VS0,VE116',
43 silly get     vary: 'Accept' } ]
44 verbose get saving vptree to /Users/aredridel/.npm/registry.npmjs.org/vptree/.cache.json
45 http 200 https://registry.npmjs.org/mddf
46 silly get cb [ 200,
46 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
46 silly get     etag: '"28O6PR5AA5YJXMW3GXNO1EVIY"',
46 silly get     'content-type': 'application/json',
46 silly get     'cache-control': 'max-age=60',
46 silly get     'content-length': '19185',
46 silly get     'accept-ranges': 'bytes',
46 silly get     date: 'Sun, 13 Sep 2015 20:19:16 GMT',
46 silly get     via: '1.1 varnish',
46 silly get     connection: 'keep-alive',
46 silly get     'x-served-by': 'cache-atl6234-ATL',
46 silly get     'x-cache': 'MISS',
46 silly get     'x-cache-hits': '0',
46 silly get     'x-timer': 'S1442175555.918130,VS0,VE134',
46 silly get     vary: 'Accept' } ]
47 verbose get saving mddf to /Users/aredridel/.npm/registry.npmjs.org/mddf/.cache.json
48 http 200 https://registry.npmjs.org/nns
49 silly get cb [ 200,
49 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
49 silly get     etag: '"ANZWZ6B55SC5UX0276UBXZ8YH"',
49 silly get     'content-type': 'application/json',
49 silly get     'cache-control': 'max-age=60',
49 silly get     'content-length': '662',
49 silly get     'accept-ranges': 'bytes',
49 silly get     date: 'Sun, 13 Sep 2015 20:19:16 GMT',
49 silly get     via: '1.1 varnish',
49 silly get     connection: 'keep-alive',
49 silly get     'x-served-by': 'cache-atl6226-ATL',
49 silly get     'x-cache': 'MISS',
49 silly get     'x-cache-hits': '0',
49 silly get     'x-timer': 'S1442175555.910357,VS0,VE337',
49 silly get     vary: 'Accept' } ]
50 verbose get saving nns to /Users/aredridel/.npm/registry.npmjs.org/nns/.cache.json
51 verbose stack TypeError: Cannot convert undefined or null to object
51 verbose stack     at returnAndAddMetadata (/usr/local/lib/node_modules/npm/lib/fetch-package-metadata.js:104:14)
51 verbose stack     at pickVersionFromRegistryDocument (/usr/local/lib/node_modules/npm/lib/fetch-package-metadata.js:138:18)
51 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/iferr/index.js:13:50
51 verbose stack     at /usr/local/lib/node_modules/npm/lib/utils/pulse-till-done.js:19:8
51 verbose stack     at saved (/usr/local/lib/node_modules/npm/lib/cache/caching-client.js:168:7)
51 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:210:7
51 verbose stack     at FSReqWrap.oncomplete (fs.js:82:15)
52 verbose cwd /Users/aredridel/Projects/locator-app/locator-server
53 error Darwin 15.0.0
54 error argv "/usr/local/lib/node_modules/iojs-bin/node_modules/iojs-darwin-x64/iojs-v3.3.0-darwin-x64/bin/iojs" "/usr/local/bin/npm" "home" "vptree" "nns" "mddf"
55 error node v3.3.0
56 error npm  v3.3.3
57 error Cannot convert undefined or null to object
58 error If you need help, you may report this error at:
58 error     <https://github.com/npm/npm/issues>
59 verbose exit [ 1, true ]
```

**Comment by zkat** [comment]
I can't reproduce this, even if I switch to the exact node/npm version pair, on OSX. Is it still happening for you on latest?

**Comment by DavidStreid** [comment]
I'm getting the same "Cannot convert undefined or null to object" TypeError with the fetch-package-metadata.js file. I'm currently running with npm v3.9.5 & node v6.2.2

**Comment by dynamite-ready** [comment]
I encounter the same issue on NPM 3.10.8, with Node 6.9.1 running on Windows 8.1 64 bit.
It undoubtedly worked in the recent past.

To try to fix the problem, I've reinstalled Node at least 6 times from the .msi file found on the official website. I get the same problem as above, when running the exact same command.

Further more, all npm install commands draw similar ```Cannot convert undefined or null to object``` errors.
If this happens after multiple attempts to reinstall Node and NPM, does that mean that the uninstallation process fails to clean up a key file? Or perhaps, you have a system/config blacklist on your end?

**Comment by dynamite-ready** [comment]
Ok. For me, I ran - ```npm config set registry https://registry.npmjs.org/``` and it now all finally works.
Why was the registry not set on installation?
