### ISSUE TITLE
error when trying to unpublish enterprise / scoped package

### ISSUE THREAD

**Issue by pkyeck** [npm/npm#9616]
getting this when trying to unpublish:

```
npm unpublish @<domain>/<package>@1.0.0
npm ERR! Linux 3.19.0-25-generic
npm ERR! argv "node" "/usr/bin/npm" "unpublish" "@<scope>/<package>@1.0.0"
npm ERR! node v0.12.7
npm ERR! npm  v2.14.1
npm ERR! code E500

npm ERR! Registry returned 500 for DELETE on http://<url>/@<scope>%2f<package>/-rev/1-<hash>
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
```

```
0 info it worked if it ends with ok
1 verbose cli [ 'node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'unpublish',
1 verbose cli   '@<scope>/<package>@1.0.0' ]
2 info using npm@2.14.1
3 info using node@v0.12.7
4 verbose node symlink /usr/bin/node
5 silly unpublish args[0] @<scope>/<package>@1.0.0
6 silly unpublish thing { raw: '@<scope>/<package>@1.0.0',
6 silly unpublish   scope: '@<scope>',
6 silly unpublish   name: '@<scope>/<package>',
6 silly unpublish   rawSpec: '1.0.0',
6 silly unpublish   spec: '1.0.0',
6 silly unpublish   type: 'version' }
7 verbose getPublishConfig null
8 silly ls normalized @<scope>/<package>/1.0.0
9 silly gentlyRm /<path>/.npm/@<scope>/<package>/1.0.0 is being purged
10 verbose gentlyRm don't care about contents; nuking /<path>/.npm/@<scope>/<package>/1.0.0
11 silly mapToRegistry name @<scope>/<package>
12 silly mapToRegistry scope (from package name) @<scope>
13 silly mapToRegistry registry http://<url>/
14 silly mapToRegistry uri http://<url>/@<scope>%2f<package>
15 verbose get GET as part of write; not caching result
16 verbose request uri http://<url>/@<scope>%2f<package>?write=true
17 verbose request no auth needed
18 info attempt registry request try #1 at 16:29:03
19 verbose request using bearer token for auth
20 verbose request id c95e1a45664a4ff6
21 http request GET http://<url>/@<scope>%2f<package>?write=true
22 http 200 http://<url>/@<scope>%2f<package>?write=true
23 silly get cb [ 200,
23 silly get   { vary: 'Accept',
23 silly get     server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
23 silly get     etag: '"ELECAA2A9SR1RFVKGN46ALTKJ"',
23 silly get     date: 'Wed, 16 Sep 2015 14:29:05 GMT',
23 silly get     'content-type': 'application/json',
23 silly get     'content-length': '1615',
23 silly get     connection: 'keep-alive' } ]
24 verbose get saving @<scope>/<package> to /<path>/.npm/<url>_8080/_40xxx_252f<package>_3Fwrite_3Dtrue/.cache.json
25 verbose unpublish removing attachments { shasum: 'b30d4e64cfb5721c80d4cc2d53be6496b0a89b7f',
25 verbose unpublish   tarball: 'http://<url>/@/@<scope>/<package>/_attachments/<package>-1.0.0.tgz' }
26 info unpublish No versions remain, removing entire package
27 verbose request uri http://<url>/@<scope>%2f<package>/-rev/1-<hash>
28 verbose request sending authorization for write operation
29 info attempt registry request try #1 at 16:29:04
30 verbose request using bearer token for auth
31 http request DELETE http://<url>/@<scope>%2f<package>/-rev/1-<hash>
32 http 500 http://<url>/@<scope>%2f<package>/-rev/1-<hash>
33 info retry will retry, error on last attempt: Error: Registry returned 500 for DELETE on http://<url>/@<scope>%2f<package>/-rev/1-<hash>
34 info attempt registry request try #2 at 16:29:15
35 verbose request using bearer token for auth
36 http request DELETE http://<url>/@<scope>%2f<package>/-rev/1-<hash>
37 http 500 http://<url>/@<scope>%2f<package>/-rev/1-<hash>
38 info retry will retry, error on last attempt: Error: Registry returned 500 for DELETE on http://<url>/@<scope>%2f<package>/-rev/1-<hash>
39 info attempt registry request try #3 at 16:30:16
40 verbose request using bearer token for auth
41 http request DELETE http://<url>/@<scope>%2f<package>/-rev/1-<hash>
42 http 500 http://<url>/@<scope>%2f<package>/-rev/1-<hash>
43 verbose headers { 'content-type': 'application/json',
43 verbose headers   'content-length': '17',
43 verbose headers   date: 'Wed, 16 Sep 2015 14:30:17 GMT',
43 verbose headers   connection: 'keep-alive' }
44 verbose request invalidating /<path>/.npm/<url>_8080/_40xxx_252f<package> on DELETE
45 verbose stack Error: Registry returned 500 for DELETE on http://<url>/@<scope>%2f<package>/-rev/1-<hash>
45 verbose stack     at makeError (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:263:12)
45 verbose stack     at CachingRegistryClient.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:241:14)
45 verbose stack     at Request._callback (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:171:14)
45 verbose stack     at Request.self.callback (/usr/lib/node_modules/npm/node_modules/request/request.js:198:22)
45 verbose stack     at Request.emit (events.js:110:17)
45 verbose stack     at Request.<anonymous> (/usr/lib/node_modules/npm/node_modules/request/request.js:1073:14)
45 verbose stack     at Request.emit (events.js:129:20)
45 verbose stack     at IncomingMessage.<anonymous> (/usr/lib/node_modules/npm/node_modules/request/request.js:1019:12)
45 verbose stack     at IncomingMessage.emit (events.js:129:20)
45 verbose stack     at _stream_readable.js:908:16
46 verbose statusCode 500
47 verbose pkgid @<scope>/<package>
48 verbose cwd /<path>/repos/bnow/<package>
49 error Linux 3.19.0-25-generic
50 error argv "node" "/usr/bin/npm" "unpublish" "@<scope>/<package>@1.0.0"
51 error node v0.12.7
52 error npm  v2.14.1
53 error code E500
54 error Registry returned 500 for DELETE on http://<url>/@<scope>%2f<package>/-rev/1-<hash>
55 error If you need help, you may report this error at:
55 error     <https://github.com/npm/npm/issues>
56 verbose exit [ 1, true ]

```

any idea how to fix this? or what could be causing this `500`?

**Comment by kcauchy** [comment]
It seems this bug only occurs in OS X, not Windows and Linux for me.

**Comment by kcauchy** [comment]
Correction: Not just OS X. And not only the `unpublish`, but also `publish`, `install`.
