### ISSUE TITLE
install error when install dependency of debug

### ISSUE THREAD

**Issue by swizardlv** [npm/npm#9628]
Dear, could you please help to look at this issue? seems debug@^2.1.1 exists. Thanks.
```````````````````````
swizard@swizarddeMacBook-Pro:~/Documents/dev/strongloop
> npm install loopback-connector-oracle --save
npm http GET https://registry.npmjs.org/loopback-connector-oracle
npm http 200 https://registry.npmjs.org/loopback-connector-oracle
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/loopback-connector
npm http GET https://registry.npmjs.org/loopback-oracle-installer
npm http GET https://registry.npmjs.org/strongloop-license
npm http GET http://blip.strongloop.com/loopback-connector-oracle@2.2.0
npm http 200 http://blip.strongloop.com/loopback-connector-oracle@2.2.0
npm http 200 https://registry.npmjs.org/loopback-oracle-installer
npm http 200 https://registry.npmjs.org/debug
npm ERR! Error: No compatible version found: debug@'^2.1.1'
npm ERR! Valid install targets:
npm ERR! ["0.0.1","0.1.0","0.2.0","0.3.0","0.4.0","0.4.1","0.5.0","0.6.0","0.7.0","0.7.1","0.7.2","0.7.3","0.7.4","0.8.0","0.8.1","1.0.0","1.0.1","1.0.2","1.0.3","1.0.4","2.0.0","2.1.0","2.1.1","2.1.2","2.1.3","2.2.0"]
npm ERR!     at installTargetsError (/Users/swizard/.nvm/v0.10.0/lib/node_modules/npm/lib/cache.js:682:10)
npm ERR!     at /Users/swizard/.nvm/v0.10.0/lib/node_modules/npm/lib/cache.js:597:10
npm ERR!     at saved (/Users/swizard/.nvm/v0.10.0/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:93:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 14.5.0
npm ERR! command "/Users/swizard/.nvm/v0.10.0/bin/node" "/Users/swizard/.nvm/v0.10.0/bin/npm" "install" "loopback-connector-oracle" "--save"
npm ERR! cwd /Users/swizard/Documents/dev/strongloop
npm ERR! node -v v0.10.0
npm ERR! npm -v 1.2.14
npm http 200 https://registry.npmjs.org/loopback-connector
npm http 200 https://registry.npmjs.org/async
npm http 200 https://registry.npmjs.org/strongloop-license
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/swizard/Documents/dev/strongloop/npm-debug.log
npm ERR! not ok code 0
```````````````````````````````

**Comment by KenanY** [comment]
@swizardlv It exists but your ancient `npm` version cannot begin to understand the `^` semver operator. Please try [upgrading](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm).

**Comment by othiym23** [comment]
Closing as resolved. For sure, you need a newer npm. Neither `npm@1.2` nor `npm@1.3` are supported anymore, in part because of issues like this one. The instructions @KenanY linked to should get you going.
