### ISSUE TITLE
Failing optional deps can fail an install sometimes

### ISSUE THREAD

**Issue by iarna** [npm/npm#9643]
An example of this is karma with node 4:
```
npm i -g karma
```
(Thanks to @jdalton)

```
make: *** [Release/obj.target/bufferutil/src/bufferutil.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/rebecca/code/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/Users/rebecca/.nvm/versions/node/v4.1.0/bin/node" "/Users/rebecca/code/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/rebecca/.nvm/versions/node/v4.1.0/lib/node_modules/karma/node_modules/bufferutil
gyp ERR! node -v v4.1.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
/Users/rebecca/.nvm/versions/node/v4.1.0/lib
└── (empty)

npm ERR! Darwin 14.5.0
npm ERR! argv "/Users/rebecca/.nvm/versions/node/v4.1.0/bin/node" "/Users/rebecca/code/npm" "install" "-g" "karma"
npm ERR! node v4.1.0
npm ERR! npm  v3.3.3
npm ERR! code ELIFECYCLE

npm ERR! bufferutil@1.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bufferutil@1.1.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the bufferutil package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bufferutil
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/rebecca/code/npmtest/npm-debug.log
npm ERR! code 1
```

https://gist.github.com/iarna/a6f32d5924c39ba70b8e

**Comment by jdalton** [comment]
As a priority note karma is a dev-dep of Angular, Underscore, Backbone which means all of those are borked on npm3 at the moment dev-deppy wise.

**Comment by othiym23** [comment]
Noted. Added to the `big-bug` list for a while, although that's starting to get a little long, so we may need to do a little load-balancing because we only have the one @iarna.

**Comment by donaldpipowitch** [comment]
Maybe we should start running `npm@next`/"npm nightly" tests against the most popular modules? I heard Rust does something with Cargo modules?

**Comment by iarna** [comment]
It's a good idea. The Perl community does this too w/ Perl releases (against the entire CPAN).

**Comment by iarna** [comment]
(This was a very short week for us at npm, due to all-staff-meeting days and so I ran out of time to get a fix for this into this weeks release. Bumping to next week!)

**Comment by jdalton** [comment]
Can dig.

**Comment by iarna** [comment]
Oh- oh-ho! So this _only_ happens when installing globally. This does not happen when installing locally.

**Comment by iarna** [comment]
We're bumping this out _another_ week, so that we can spend some time focusing on the performance issues in npm@3. These are similarly important issues!

**Comment by adouglas** [comment]
@iarna This does happen for me when installing karma locally.

**Comment by cyrilchaponeverysens** [comment]
Verified on windows

```
D:\nodejs\karma -> D:\nodejs\node_modules\karma\bin\karma

> bufferutil@1.2.1 install D:\nodejs\node_modules\karma\node_modules\bufferutil
> node-gyp rebuild


D:\nodejs\node_modules\karma\node_modules\bufferutil>if not defined npm_config_node_gyp (node "D:\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Génération des projets individuellement dans cette solution. Pour activer la génération en parallèle, ajoutez le commutateur "/m".
MSBUILD : error MSB3428: Impossible de charger le composant Visual C++ "VCBuild.exe". Pour corriger le problème, vou
s devez 1) installer le Kit de développement .NET Framework 2.0 SDK, 2) installer Microsoft Visual Studio 2005 ou 3)
 ajouter l'emplacement du composant au chemin d'accès système, s'il est installé ailleurs.  [D:\nodejs\node_modules\
karma\node_modules\bufferutil\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "D:\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\nodejs\node_modules\karma\node_modules\bufferutil
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
D:\nodejs
└── (empty)

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "D:\\nodejs\\\\node.exe" "D:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "karma"
npm ERR! node v0.12.7
npm ERR! npm  v3.3.5
npm ERR! code ELIFECYCLE

npm ERR! bufferutil@1.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bufferutil@1.2.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the bufferutil package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bufferutil
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Cyril\Desktop\folder\rtls-frontend\npm-debug.log
npm ERR! code 1
```

**Comment by Aourin** [comment]
Was having this issue before, i had to wade through things and into bufferutil. Finally, after trying to install bufferutil, noticed that g++ was missing for me. Installed g++ and now everything seems to install correctly.

**Comment by maxdow** [comment]
Same for me with latest npm version ( 3.3.8 ) on win7 . I downgraded to npm 2.14.8 and it works well.

**Comment by eddy14u** [comment]
This happens for me when installing a module that i already have, uninstalling it first worked for me.

globally too!

**Comment by wender** [comment]
Thanks @eddy14u it worked for me too

**Comment by Ken123777** [comment]
@eddy14u that did work for me too. Thanks.
