### ISSUE TITLE
unable to install npm packages inside fresh sails install

### ISSUE THREAD

**Issue by chrislewispac** [npm/npm#9676]
0 info it worked if it ends with ok
1 verbose cli [ 'node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'sails-permissions',
1 verbose cli   'sails-auth',
1 verbose cli   '--save' ]
2 info using npm@3.3.3
3 info using node@v0.10.36
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData sails-permissions
8 silly fetchPackageMetaData sails-auth
9 silly fetchNamedPackageData sails-permissions
10 silly mapToRegistry name sails-permissions
11 silly mapToRegistry using default registry
12 silly mapToRegistry registry https://registry.npmjs.org/
13 silly mapToRegistry uri https://registry.npmjs.org/sails-permissions
14 silly fetchNamedPackageData sails-auth
15 silly mapToRegistry name sails-auth
16 silly mapToRegistry using default registry
17 silly mapToRegistry registry https://registry.npmjs.org/
18 silly mapToRegistry uri https://registry.npmjs.org/sails-auth
19 verbose request uri https://registry.npmjs.org/sails-permissions
20 verbose request no auth needed
21 info attempt registry request try #1 at 15:39:52
22 verbose request id 0d695555be94c5bb
23 verbose etag "7VJ6LW73Z5F5DD37ZPXG8CIZB"
24 http request GET https://registry.npmjs.org/sails-permissions
25 verbose request uri https://registry.npmjs.org/sails-auth
26 verbose request no auth needed
27 info attempt registry request try #1 at 15:39:52
28 verbose etag "93H1U2W2WWM94BT30KMGSB7O7"
29 http request GET https://registry.npmjs.org/sails-auth
30 http 304 https://registry.npmjs.org/sails-permissions
31 silly get cb [ 304,
31 silly get   { date: 'Sat, 19 Sep 2015 19:39:52 GMT',
31 silly get     via: '1.1 varnish',
31 silly get     'cache-control': 'max-age=60',
31 silly get     etag: '"7VJ6LW73Z5F5DD37ZPXG8CIZB"',
31 silly get     age: '0',
31 silly get     connection: 'keep-alive',
31 silly get     'x-served-by': 'cache-iad2136-IAD',
31 silly get     'x-cache': 'MISS',
31 silly get     'x-cache-hits': '0',
31 silly get     'x-timer': 'S1442691592.863091,VS0,VE98',
31 silly get     vary: 'Accept' } ]
32 verbose etag https://registry.npmjs.org/sails-permissions from cache
33 verbose get saving sails-permissions to /Users/christopherlewis/.npm/registry.npmjs.org/sails-permissions/.cache.json
34 http 304 https://registry.npmjs.org/sails-auth
35 silly get cb [ 304,
35 silly get   { date: 'Sat, 19 Sep 2015 19:39:52 GMT',
35 silly get     via: '1.1 varnish',
35 silly get     'cache-control': 'max-age=60',
35 silly get     etag: '"93H1U2W2WWM94BT30KMGSB7O7"',
35 silly get     age: '0',
35 silly get     connection: 'keep-alive',
35 silly get     'x-served-by': 'cache-iad2146-IAD',
35 silly get     'x-cache': 'MISS',
35 silly get     'x-cache-hits': '0',
35 silly get     'x-timer': 'S1442691592.868802,VS0,VE265',
35 silly get     vary: 'Accept' } ]
36 verbose etag https://registry.npmjs.org/sails-auth from cache
37 verbose get saving sails-auth to /Users/christopherlewis/.npm/registry.npmjs.org/sails-auth/.cache.json
38 silly install normalizeTree
39 verbose type non_object_property_store
40 verbose stack TypeError: Cannot set property 'lodash' of undefined
40 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/deps.js:94:36
40 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/dezalgo/dezalgo.js:17:12
40 verbose stack     at RawTask.call (/usr/local/lib/node_modules/npm/node_modules/asap/asap.js:40:19)
40 verbose stack     at flush (/usr/local/lib/node_modules/npm/node_modules/asap/raw.js:50:29)
40 verbose stack     at process._tickCallback (node.js:442:13)
41 verbose cwd /Users/christopherlewis/Desktop/Projects/golfingbuddha
42 error Darwin 14.5.0
43 error argv "node" "/usr/local/bin/npm" "install" "sails-permissions" "sails-auth" "--save"
44 error node v0.10.36
45 error npm  v3.3.3
46 error Cannot set property 'lodash' of undefined
47 error If you need help, you may report this error at:
47 error     <https://github.com/npm/npm/issues>
48 verbose exit [ 1, true ]

**Comment by megakoresh** [comment]
Yeah I am getting the same thing after upgrading npm

**Comment by othiym23** [comment]
I just tried to reproduce this with `npm@3.5.2`, and didn't get the crash. Is this still a problem for anyone running `npm@latest` or `npm@next`?

**Comment by parkeragee** [comment]
I have npm v.3.3.6 and I'm getting this error inside a Sailsjs app.

**Comment by othiym23** [comment]
@parkeragee It's definitely a known issue with `npm@3.3.6` – what happens if you upgrade to `npm@3.5.2` / `npm@next`? Does the problem recur?

**Comment by parkeragee** [comment]
@othiym23 I kept 3.3.6 and just `rm -r node_modules` in my root and then just `npm install` again. That solved the problem.

**Comment by basilinjoe** [comment]
`npm ERR! Linux 3.16.0-61-generic
npm ERR! argv "node" "/home/basilin/.npm-global/bin/npm" "install"
npm ERR! node v0.10.37
npm ERR! npm  v3.7.1

npm ERR! Cannot set property 'lodash' of undefined
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Linux 3.16.0-61-generic
npm ERR! argv "node" "/home/basilin/.npm-global/bin/npm" "install"
npm ERR! node v0.10.37
npm ERR! npm  v3.7.1

npm ERR! Cannot set property 'fs-extra' of undefined
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/basilin/sails/passport_auth/npm-debug.log
`
Am getting this error .. on npm install ..

**Comment by jinglesthula** [comment]
@othiym23 that worked for me as well.  However, npm install didn't quite do everything.  I had to cd into express and npm install there, as well as manually install redis in socket.io.  Once I did that, I could lift sails w/o problem (at least I haven't run into anything else ;)

**Comment by BhavinIoT** [comment]
@parkeragee on npm v3.9.5 here and this worked for me. So thanks :+1:
Just an observation:
Earlier, `node_modules` had symbolic links to just the dependencies in package.json. After doing `rm -rf node_modules` and `npm install` it now has all the packages
