### ISSUE TITLE
Error while installing node js express

### ISSUE THREAD

**Issue by Anil06Kumamr** [npm/npm#9692]
Dear,

When i was running "C:\Node>npm install -g express-generator" command then error generated following is the error detail. 

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'express-generator' ]
2 info using npm@2.11.3
3 info using node@v0.12.7
4 verbose install initial load of C:\Users\Admin\AppData\Roaming\npm\package.json
5 verbose readDependencies loading dependencies from C:\Users\Admin\AppData\Roaming\npm\package.json
6 silly cache add args [ 'express-generator', null ]
7 verbose cache add spec express-generator
8 silly cache add parsed spec { raw: 'express-generator',
8 silly cache add   scope: null,
8 silly cache add   name: 'express-generator',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: '*',
8 silly cache add   type: 'range' }
9 silly addNamed express-generator@*
10 verbose addNamed "*" is a valid semver range for express-generator
11 silly addNameRange { name: 'express-generator', range: '*', hasData: false }
12 silly mapToRegistry name express-generator
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/express-generator
16 verbose addNameRange registry:https://registry.npmjs.org/express-generator not in flight; fetching
17 verbose request uri https://registry.npmjs.org/express-generator
18 verbose request no auth needed
19 info attempt registry request try #1 at 7:13:53 PM
20 verbose request id 13b352c835fddb7c
21 http request GET https://registry.npmjs.org/express-generator
22 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
23 info attempt registry request try #2 at 7:14:04 PM
24 http request GET https://registry.npmjs.org/express-generator
25 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
26 info attempt registry request try #3 at 7:15:04 PM
27 http request GET https://registry.npmjs.org/express-generator
28 verbose stack Error: self signed certificate in certificate chain
28 verbose stack     at Error (native)
28 verbose stack     at TLSSocket.<anonymous> (_tls_wrap.js:929:36)
28 verbose stack     at TLSSocket.emit (events.js:104:17)
28 verbose stack     at TLSSocket._finishInit (_tls_wrap.js:460:8)
29 verbose cwd E:\NodeJsProjects\nodetest1
30 error Windows_NT 6.1.7601
31 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "express-generator"
32 error node v0.12.7
33 error npm  v2.11.3
34 error code SELF_SIGNED_CERT_IN_CHAIN
35 error self signed certificate in certificate chain
36 error If you need help, you may report this error at:
36 error     <https://github.com/npm/npm/issues>
37 verbose exit [ 1, true ]
```

Please hep us.

Anil Bali.

**Comment by Anil06Kumamr** [comment]
Dear,

When i was running "C:\Node>npm install -g express-generator" command then error generated following is the error detail. 

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'express-generator' ]
2 info using npm@2.11.3
3 info using node@v0.12.7
4 verbose install initial load of C:\Users\Admin\AppData\Roaming\npm\package.json
5 verbose readDependencies loading dependencies from C:\Users\Admin\AppData\Roaming\npm\package.json
6 silly cache add args [ 'express-generator', null ]
7 verbose cache add spec express-generator
8 silly cache add parsed spec { raw: 'express-generator',
8 silly cache add   scope: null,
8 silly cache add   name: 'express-generator',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: '*',
8 silly cache add   type: 'range' }
9 silly addNamed express-generator@*
10 verbose addNamed "*" is a valid semver range for express-generator
11 silly addNameRange { name: 'express-generator', range: '*', hasData: false }
12 silly mapToRegistry name express-generator
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/express-generator
16 verbose addNameRange registry:https://registry.npmjs.org/express-generator not in flight; fetching
17 verbose request uri https://registry.npmjs.org/express-generator
18 verbose request no auth needed
19 info attempt registry request try #1 at 7:13:53 PM
20 verbose request id 13b352c835fddb7c
21 http request GET https://registry.npmjs.org/express-generator
22 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
23 info attempt registry request try #2 at 7:14:04 PM
24 http request GET https://registry.npmjs.org/express-generator
25 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
26 info attempt registry request try #3 at 7:15:04 PM
27 http request GET https://registry.npmjs.org/express-generator
28 verbose stack Error: self signed certificate in certificate chain
28 verbose stack     at Error (native)
28 verbose stack     at TLSSocket.<anonymous> (_tls_wrap.js:929:36)
28 verbose stack     at TLSSocket.emit (events.js:104:17)
28 verbose stack     at TLSSocket._finishInit (_tls_wrap.js:460:8)
29 verbose cwd E:\NodeJsProjects\nodetest1
30 error Windows_NT 6.1.7601
31 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "express-generator"
32 error node v0.12.7
33 error npm  v2.11.3
34 error code SELF_SIGNED_CERT_IN_CHAIN
35 error self signed certificate in certificate chain
36 error If you need help, you may report this error at:
36 error     <https://github.com/npm/npm/issues>
37 verbose exit [ 1, true ]

Please hep us.

Anil Bali.
