### ISSUE TITLE
Is npm@3 not handling version collisions very well?

### ISSUE THREAD

**Issue by m4n3z40** [npm/npm#9708]
I have a project that has eslint as a devDependency: 

```
...
"devDependencies": {
    "browser-sync": "^2.9.4",
    "eslint": "^1.5.0",
    "eslint-plugin-react": "^3.4.2",
    "gulp-eslint": "^1.0.0",
    "jasmine-core": "^2.3.4",
    "karma": "^0.13.9",
    "karma-browserify": "^4.3.0",
    "karma-chrome-launcher": "^0.2.0",
    "karma-jasmine": "^0.3.6",
    "run-sequence": "^1.1.3",
    "watchify": "^3.4.0"
  },
...
```

It all worked fine until I tried to update NPM from 2 to 3 and then run `npm update` in the project. After NPM did it's thing to re-arrange all `node_modules` structure to the newer, flatter and optimized structure, the `eslint` package stopped working, throwing the following error:

```
/Users/abaptista/projects/hu-site-mobile-next/node_modules/estraverse/estraverse.js:517
                        throw new Error('Unknown node type ' + nodeType + '.');
                        ^
...
```

As I thought was an issue with the `eslint` package, I went on it's repo trying to find a fix or open an issue to find out it's an error that has been fixed for a [long time](https://github.com/eslint/eslint/issues/1965).

Looking into the new `node_modules` structure I found out that the version that NPM installs of `estraverse` it's the `1.9.3`, but the version `eslint` requires it's `^4.1.0`, I guessing it's some kind of version collision that NPM3 is not handling well, could it be?

**Comment by KenanY** [comment]
@m4n3z40 Maybe try removing your `node_modules/` directory and running `npm install`? At least that way we would know if this is an issue with `npm update` or with `npm` in general.

**Comment by m4n3z40** [comment]
Did that a couple of times already, nothing changes, it only works when I downgrade to NPM ```2.14.5```.
Further investigations tell me it's some kind of collision with the ```escodegen``` package.
For some reason ```eslint``` is not being able to import the right version of ```estraverse```.

An excerpt of the ```packages.json``` in ```eslint```:

```
...
"dependencies": {
    "chalk": "^1.0.0",
    "concat-stream": "^1.4.6",
    "debug": "^2.1.1",
    "doctrine": "^0.6.2",
    "escape-string-regexp": "^1.0.2",
    "escope": "^3.2.0",
    "espree": "^2.2.4",
    "estraverse": "^4.1.0",
    "estraverse-fb": "^1.3.1",
    "file-entry-cache": "^1.1.1",
    "glob": "^5.0.14",
    "globals": "^8.6.0",
    "handlebars": "^4.0.0",
    "inquirer": "^0.9.0",
    "is-my-json-valid": "^2.10.0",
    "is-resolvable": "^1.0.0",
    "js-yaml": "^3.2.5",
    "lodash.clonedeep": "^3.0.1",
    "lodash.merge": "^3.3.2",
    "lodash.omit": "^3.1.0",
    "minimatch": "^2.0.1",
    "mkdirp": "^0.5.0",
    "object-assign": "^2.0.0",
    "optionator": "^0.5.0",
    "path-is-absolute": "^1.0.0",
    "path-is-inside": "^1.0.1",
    "shelljs": "^0.3.0",
    "strip-json-comments": "~1.0.1",
    "text-table": "~0.2.0",
    "to-double-quotes": "^1.0.1",
    "to-single-quotes": "^1.0.3",
    "user-home": "^1.0.0",
    "xml-escape": "~1.0.0"
  },
...
```

The ```estraverse``` at ```node_modules```:

```
...
"_args": [
    [
      "estraverse@^1.9.1",
      "/Users/abaptista/projects/hu-site-mobile-next/node_modules/escodegen"
    ]
  ],
  "_from": "estraverse@>=1.9.1 <2.0.0",
  "_id": "estraverse@1.9.3",
  "_inCache": true,
  "_location": "/estraverse",
  "_npmUser": {
    "email": "utatane.tea@gmail.com",
    "name": "constellation"
  },
  "_npmVersion": "1.4.28",
  "_phantomChildren": {},
  "_requested": {
    "name": "estraverse",
    "raw": "estraverse@^1.9.1",
    "rawSpec": "^1.9.1",
    "scope": null,
    "spec": ">=1.9.1 <2.0.0",
    "type": "range"
  },
  "_requiredBy": [
    "/escodegen"
  ],
  "_resolved": "https://registry.npmjs.org/estraverse/-/estraverse-1.9.3.tgz",
  "_shasum": "af67f2dc922582415950926091a4005d29c9bb44",
  "_shrinkwrap": null,
  "_spec": "estraverse@^1.9.1",
  "_where": "/Users/abaptista/projects/hu-site-mobile-next/node_modules/escodegen",
...
```

The ```estraverse``` at ```eslint/node_modules``` (the right on for eslint to load, i`m guessing):

```
...
"_args": [
    [
      "estraverse@^4.1.0",
      "/Users/abaptista/projects/hu-site-mobile-next/node_modules/eslint"
    ]
  ],
  "_from": "estraverse@>=4.1.0 <5.0.0",
  "_id": "estraverse@4.1.0",
  "_inCache": true,
  "_location": "/eslint/estraverse",
  "_nodeVersion": "1.8.1",
  "_npmUser": {
    "email": "utatane.tea@gmail.com",
    "name": "constellation"
  },
  "_npmVersion": "2.8.3",
  "_phantomChildren": {},
  "_requested": {
    "name": "estraverse",
    "raw": "estraverse@^4.1.0",
    "rawSpec": "^4.1.0",
    "scope": null,
    "spec": ">=4.1.0 <5.0.0",
    "type": "range"
  },
  "_requiredBy": [
    "/eslint"
  ],
  "_resolved": "https://registry.npmjs.org/estraverse/-/estraverse-4.1.0.tgz",
  "_shasum": "40f23a76092041be6467d7f235c933b670766e05",
  "_shrinkwrap": null,
  "_spec": "estraverse@^4.1.0",
  "_where": "/Users/abaptista/projects/hu-site-mobile-next/node_modules/eslint",
...
```

**Comment by necolas** [comment]
did you try clearing the npm cache too?

**Comment by targos** [comment]
Related: https://github.com/npm/npm/issues/9663

**Comment by m4n3z40** [comment]
Tried clearing the cache. Still nothing.

**Comment by damonmcminn** [comment]
I also have this issue and have had to downgrade to `2.14.5` to get `eslint` to work.

**Comment by ebdrup** [comment]
I have this same bug too

**Comment by ebdrup** [comment]
I solved by adding `"estraverse": "^4.1.0"` in `devDependencies` in my package.json

**Comment by zckrs** [comment]
Same case same issue :/

**Comment by othiym23** [comment]
I'm pretty sure this has been fixed in newer versions of npm. Is this behavior still an issue?

**Comment by mysticatea** [comment]
@othiym23 I checked with `npm@next` and [this way](https://github.com/eslint/eslint/pull/4307#issuecomment-153637580) but it still failed.

```
> .\node_modules\.bin\npm -v
v3.5.4
> .\node_modules\.bin\npm i escodegen eslint@1.8.0
....
> .\node_modules\.bin\eslint -v
v1.8.0
> .\node_modules\.bin\eslint test.js

C:\Users\t-nagashima.AD\Documents\GitHub\sand\node_modules\estraverse\estraverse.js:517
                        throw new Error('Unknown node type ' + nodeType + '.');
                        ^

Error: Unknown node type AssignmentPattern.
    at Controller.traverse (C:\Users\t-nagashima.AD\Documents\GitHub\sand\node_modules\estraverse\estraverse.js:517:31)
    at EventEmitter.module.exports.api.verify (C:\Users\t-nagashima.AD\Documents\GitHub\sand\node_modules\eslint\lib\eslint.js:779:24)
    at processText (C:\Users\t-nagashima.AD\Documents\GitHub\sand\node_modules\eslint\lib\cli-engine.js:225:27)
    at processFile (C:\Users\t-nagashima.AD\Documents\GitHub\sand\node_modules\eslint\lib\cli-engine.js:262:18)
    at executeOnFile (C:\Users\t-nagashima.AD\Documents\GitHub\sand\node_modules\eslint\lib\cli-engine.js:671:23)
    at C:\Users\t-nagashima.AD\Documents\GitHub\sand\node_modules\eslint\lib\cli-engine.js:695:17
    at Array.forEach (native)
    at CLIEngine.executeOnFiles (C:\Users\t-nagashima.AD\Documents\GitHub\sand\node_modules\eslint\lib\cli-engine.js:693:18)
    at Object.cli.execute (C:\Users\t-nagashima.AD\Documents\GitHub\sand\node_modules\eslint\lib\cli.js:161:95)
    at Object.<anonymous> (C:\Users\t-nagashima.AD\Documents\GitHub\sand\node_modules\eslint\bin\eslint.js:61:20)
