### ISSUE TITLE
npm shrinkwrap --dev : verbose stack extraneous: os-shim@0.1.3 

### ISSUE THREAD

**Issue by michaelBenin** [npm/npm#9749]
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/Users/mbenin/.nvm/v0.10.21/bin/npm" "shrinkwrap" "--dev"
npm ERR! node v0.10.21
npm ERR! npm  v3.3.3

```
npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! extraneous: os-shim@0.1.3 /Users/mbenin/Projects/redesign-slot-fastcompany/node_modules/os-shim
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mbenin/Projects/redesign-slot-fastcompany/npm-debug.log
Admins-MacBook-Pro:redesign-slot-fastcompany mbenin$
```

Here is the output from the npm-debug.log

```
0 info it worked if it ends with ok
1 verbose cli [ 'node',
1 verbose cli   '/Users/mbenin/.nvm/v0.10.21/bin/npm',
1 verbose cli   'shrinkwrap',
1 verbose cli   '--dev' ]
2 info using npm@3.3.3
3 info using node@v0.10.21
4 verbose stack Error: Problems were encountered
4 verbose stack Please correct and try again.
4 verbose stack extraneous: os-shim@0.1.3 /Users/mbenin/Projects/redesign-slot-fastcompany/node_modules/os-shim
4 verbose stack     at shrinkwrap_ (/Users/mbenin/.nvm/v0.10.21/lib/node_modules/npm/lib/shrinkwrap.js:100:15)
4 verbose stack     at /Users/mbenin/.nvm/v0.10.21/lib/node_modules/npm/lib/shrinkwrap.js:35:5
4 verbose stack     at /Users/mbenin/.nvm/v0.10.21/lib/node_modules/npm/node_modules/iferr/index.js:13:50
4 verbose stack     at /Users/mbenin/.nvm/v0.10.21/lib/node_modules/npm/lib/install/deps.js:119:5
4 verbose stack     at LOOP (/Users/mbenin/.nvm/v0.10.21/lib/node_modules/npm/node_modules/slide/lib/chain.js:7:26)
4 verbose stack     at /Users/mbenin/.nvm/v0.10.21/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
4 verbose stack     at cb (/Users/mbenin/.nvm/v0.10.21/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
4 verbose stack     at /Users/mbenin/.nvm/v0.10.21/lib/node_modules/npm/lib/install/deps.js:119:5
4 verbose stack     at LOOP (/Users/mbenin/.nvm/v0.10.21/lib/node_modules/npm/node_modules/slide/lib/chain.js:7:26)
4 verbose stack     at /Users/mbenin/.nvm/v0.10.21/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
5 verbose cwd /Users/mbenin/Projects/redesign-slot-fastcompany
6 error Darwin 14.5.0
7 error argv "node" "/Users/mbenin/.nvm/v0.10.21/bin/npm" "shrinkwrap" "--dev"
8 error node v0.10.21
9 error npm  v3.3.3
10 error Problems were encountered
10 error Please correct and try again.
10 error extraneous: os-shim@0.1.3 /Users/mbenin/Projects/redesign-slot-fastcompany/node_modules/os-shim
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
```

**Comment by michaelBenin** [comment]
After reading this stackoverflow answer: http://stackoverflow.com/questions/22620352/npm-windows-install-globally-results-in-npm-err-extraneous

I was able to solve this by installing the extraneous package.

```
npm i os-shim@0.1.3 --save --save-exact
```
Maybe a warning such as:

Please add <extraneous package> to package.json.
