### ISSUE TITLE
npm ERR! Windows_NT 6.1.7601

### ISSUE THREAD

**Issue by readergirltracey** [npm/npm#9778]
$ npm start

> foundation-apps-template@1.1.0 start C:\Users\Blair\Desktop\Programming\programs\toDoList
> gulp

module.js:338
    throw err;
    ^

Error: Cannot find module 'duplexer2'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\Blair\Desktop\Programming\programs\toDoList\node_modules\gulp\node_modules\gulp-util\node_modules\multipipe\index.js:6:16)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE
npm ERR! foundation-apps-template@1.1.0 start: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the foundation-apps-template@1.1.0 start script 'gulp'.
npm ERR! This is most likely a problem with the foundation-apps-template package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get their info via:
npm ERR!     npm owner ls foundation-apps-template
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Blair\Desktop\Programming\programs\toDoList\npm-debug.log

**Comment by KenanY** [comment]
@readergirltracey Is this still an issue for you?

**Comment by KenanY** [comment]
Closing due to no response.
