### ISSUE TITLE
404 when trying to npm install lucidtail

### ISSUE THREAD

**Issue by jonnolen** [npm/npm#9815]
npm install -g lucidtail

```
0 info it worked if it ends with ok
1 verbose cli [ 'node',
1 verbose cli   '/opt/boxen/nodenv/versions/v0.10/bin/npm',
1 verbose cli   'install',
1 verbose cli   'lucidtail',
1 verbose cli   '-g' ]
2 info using npm@2.7.6
3 info using node@v0.10.31
4 verbose node symlink /opt/boxen/nodenv/versions/v0.10/bin/node
5 verbose install initial load of /opt/boxen/nodenv/versions/v0.10/lib/package.json
6 verbose readDependencies loading dependencies from /opt/boxen/nodenv/versions/v0.10/lib/package.json
7 silly cache add args [ 'lucidtail', null ]
8 verbose cache add spec lucidtail
9 silly cache add parsed spec { raw: 'lucidtail',
9 silly cache add   scope: null,
9 silly cache add   name: 'lucidtail',
9 silly cache add   rawSpec: '',
9 silly cache add   spec: '*',
9 silly cache add   type: 'range' }
10 silly addNamed lucidtail@*
11 verbose addNamed "*" is a valid semver range for lucidtail
12 silly addNameRange { name: 'lucidtail', range: '*', hasData: false }
13 silly mapToRegistry name lucidtail
14 silly mapToRegistry using default registry
15 silly mapToRegistry registry https://registry.npmjs.org/
16 silly mapToRegistry uri https://registry.npmjs.org/lucidtail
17 verbose addNameRange registry:https://registry.npmjs.org/lucidtail not in flight; fetching
18 verbose request uri https://registry.npmjs.org/lucidtail
19 verbose request no auth needed
20 info attempt registry request try #1 at 11:58:33
21 verbose request id 6cade105eff25e41
22 verbose etag "DIIZ58RDX62O16EC9FVQJFB3J"
23 http request GET https://registry.npmjs.org/lucidtail
24 http 304 https://registry.npmjs.org/lucidtail
25 silly get cb [ 304,
25 silly get   { date: 'Thu, 01 Oct 2015 15:58:31 GMT',
25 silly get     via: '1.1 varnish',
25 silly get     'cache-control': 'max-age=60',
25 silly get     etag: '"DIIZ58RDX62O16EC9FVQJFB3J"',
25 silly get     age: '0',
25 silly get     connection: 'keep-alive',
25 silly get     'x-served-by': 'cache-ord1734-ORD',
25 silly get     'x-cache': 'MISS',
25 silly get     'x-cache-hits': '0',
25 silly get     'x-timer': 'S1443715111.151376,VS0,VE44',
25 silly get     vary: 'Accept' } ]
26 verbose etag https://registry.npmjs.org/lucidtail from cache
27 verbose get saving lucidtail to /Users/jon/.npm/registry.npmjs.org/lucidtail/.cache.json
28 silly addNameRange number 2 { name: 'lucidtail', range: '*', hasData: true }
29 silly addNameRange versions [ 'lucidtail',
29 silly addNameRange   [ '0.0.1',
29 silly addNameRange     '0.0.2',
29 silly addNameRange     '0.0.3',
29 silly addNameRange     '0.0.4',
29 silly addNameRange     '0.0.5',
29 silly addNameRange     '0.0.6',
29 silly addNameRange     '0.0.7',
29 silly addNameRange     '0.0.8',
29 silly addNameRange     '0.0.9',
29 silly addNameRange     '0.0.10',
29 silly addNameRange     '0.0.13',
29 silly addNameRange     '0.0.20' ] ]
30 silly addNamed lucidtail@0.0.20
31 verbose addNamed "0.0.20" is a plain semver version for lucidtail
32 silly mapToRegistry name lucidtail
33 silly mapToRegistry using default registry
34 silly mapToRegistry registry https://registry.npmjs.org/
35 silly mapToRegistry uri https://registry.npmjs.org/lucidtail
36 verbose addRemoteTarball https://registry.npmjs.org/lucidtail/-/lucidtail-0.0.20.tgz not in flight; adding
37 verbose addRemoteTarball [ 'https://registry.npmjs.org/lucidtail/-/lucidtail-0.0.20.tgz',
37 verbose addRemoteTarball   '1fd3675316754a1d13cd8e62e265dfe4ae6448aa' ]
38 info retry fetch attempt 1 at 11:58:33
39 info attempt registry request try #1 at 11:58:33
40 http fetch GET https://registry.npmjs.org/lucidtail/-/lucidtail-0.0.20.tgz
41 http fetch 404 https://registry.npmjs.org/lucidtail/-/lucidtail-0.0.20.tgz
42 error fetch failed https://registry.npmjs.org/lucidtail/-/lucidtail-0.0.20.tgz
43 warn retry will retry, error on last attempt: Error: fetch failed with status code 404
44 info retry fetch attempt 2 at 11:58:43
45 info attempt registry request try #1 at 11:58:43
46 http fetch GET https://registry.npmjs.org/lucidtail/-/lucidtail-0.0.20.tgz
47 http fetch 404 https://registry.npmjs.org/lucidtail/-/lucidtail-0.0.20.tgz
48 error fetch failed https://registry.npmjs.org/lucidtail/-/lucidtail-0.0.20.tgz
49 warn retry will retry, error on last attempt: Error: fetch failed with status code 404
50 info retry fetch attempt 3 at 11:59:44
51 info attempt registry request try #1 at 11:59:44
52 http fetch GET https://registry.npmjs.org/lucidtail/-/lucidtail-0.0.20.tgz
53 http fetch 404 https://registry.npmjs.org/lucidtail/-/lucidtail-0.0.20.tgz
54 error fetch failed https://registry.npmjs.org/lucidtail/-/lucidtail-0.0.20.tgz
55 verbose stack Error: fetch failed with status code 404
55 verbose stack     at Request.<anonymous> (/opt/boxen/nodenv/versions/v0.10.31/lib/node_modules/npm/node_modules/npm-registry-client/lib/fetch.js:51:14)
55 verbose stack     at Request.emit (events.js:95:17)
55 verbose stack     at Request.onRequestResponse (/opt/boxen/nodenv/versions/v0.10.31/lib/node_modules/npm/node_modules/request/request.js:1139:10)
55 verbose stack     at ClientRequest.emit (events.js:95:17)
55 verbose stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1688:21)
55 verbose stack     at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:121:23)
55 verbose stack     at CleartextStream.socketOnData [as ondata] (http.js:1583:20)
55 verbose stack     at CleartextStream.read [as _read] (tls.js:513:12)
55 verbose stack     at CleartextStream.Readable.read (_stream_readable.js:340:10)
55 verbose stack     at EncryptedStream.write [as _write] (tls.js:368:25)
56 verbose cwd /Users/jon/src/farmserver-cdc
57 error Darwin 14.5.0
58 error argv "node" "/opt/boxen/nodenv/versions/v0.10/bin/npm" "install" "lucidtail" "-g"
59 error node v0.10.31
60 error npm  v2.7.6
61 error fetch failed with status code 404
62 error If you need help, you may report this error at:
62 error     <https://github.com/npm/npm/issues>
63 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
Yeah, looks like the module might have been unpublished at some point so all the tarballs were lost. Maybe ask the author to publish a new version?

**Comment by KenanY** [comment]
@jonnolen is this still an issue?

**Comment by KenanY** [comment]
@jonnolen Second ping: are you still having this issue?

**Comment by KenanY** [comment]
Closing as abandoned.
