### ISSUE TITLE
npm install ERRs

### ISSUE THREAD

**Issue by AngelicaVanegas** [npm/npm#9843]
I am trying to install npm in MAC... but I had many ERRs. Somebody can help me? Thanks.

```
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/MacBookPro/Desktop/DFTech/cm-core-fe/node_modules/sass-loader/node_modules/node-sass/node_modules/pangyp/lib/configure.js:346:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/usr/local/bin/node" "/Users/MacBookPro/Desktop/DFTech/cm-core-fe/node_modules/sass-loader/node_modules/node-sass/node_modules/pangyp/bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/MacBookPro/Desktop/DFTech/cm-core-fe/node_modules/sass-loader/node_modules/node-sass
gyp ERR! node -v v4.1.1
gyp ERR! pangyp -v v2.3.2
gyp ERR! not ok 
Build failed
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE

npm ERR! contextify@0.1.14 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the contextify@0.1.14 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the contextify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls contextify
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/MacBookPro/Desktop/DFTech/cm-core-fe/npm-debug.log
```

**Comment by KenanY** [comment]
@AngelicaVanegas `contextify` does not support Node.js v4 yet.

**Comment by AngelicaVanegas** [comment]
@KenanY Thank you so much!

**Comment by othiym23** [comment]
Closing as resolved / not an issue with npm. You might try downgrading to an older version of Node and seeing if that helps!
