### ISSUE TITLE
Unable to install heroku core plugins, git

### ISSUE THREAD

**Issue by iam--nash** [npm/npm#9846]
After upgrading my OS to windows 10 , it seems that there's a problem installing git ?. not sure though but here is the error I got every time i try to run a heroku/ git command.

```
npm ERR! Windows_NT 10.0.10240
npm ERR! node v4.1.1
npm ERR! npm v2.14.4
npm ERR! error:0906D06C:PEM routines:PEM_read_bio:no start line
```

I have tried some ways , but was not able to fix it . 

here is the debug log

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Users\\Fernandez\\AppData\\Local\\heroku\\node-v4.1.1-windows-x86\\bin\\node.exe',
1 verbose cli   'C:\\Users\\Fernandez\\AppData\\Local\\heroku\\node-v4.1.1-windows-x86\\lib\\node_modules\\npm\\cli.js',
1 verbose cli   'install',
1 verbose cli   'heroku-cli-addons',
1 verbose cli   'heroku-apps',
1 verbose cli   'heroku-fork',
1 verbose cli   'heroku-git',
1 verbose cli   'heroku-local',
1 verbose cli   'heroku-run',
1 verbose cli   'heroku-status' ]
2 info using npm@2.14.4
3 info using node@v4.1.1
4 verbose install initial load of C:\Users\Fernandez\AppData\Local\heroku\package.json
5 verbose readDependencies loading dependencies from C:\Users\Fernandez\AppData\Local\heroku\package.json
6 silly cache add args [ 'heroku-cli-addons', null ]
7 verbose cache add spec heroku-cli-addons
8 silly cache add args [ 'heroku-apps', null ]
9 verbose cache add spec heroku-apps
10 silly cache add args [ 'heroku-fork', null ]
11 verbose cache add spec heroku-fork
12 silly cache add args [ 'heroku-git', null ]
13 verbose cache add spec heroku-git
14 silly cache add args [ 'heroku-local', null ]
15 verbose cache add spec heroku-local
16 silly cache add args [ 'heroku-run', null ]
17 verbose cache add spec heroku-run
18 silly cache add args [ 'heroku-status', null ]
19 verbose cache add spec heroku-status
20 silly cache add parsed spec Result {
20 silly cache add   raw: 'heroku-cli-addons',
20 silly cache add   scope: null,
20 silly cache add   name: 'heroku-cli-addons',
20 silly cache add   rawSpec: '',
20 silly cache add   spec: '*',
20 silly cache add   type: 'range' }
21 silly addNamed heroku-cli-addons@*
22 verbose addNamed "*" is a valid semver range for heroku-cli-addons
23 silly addNameRange { name: 'heroku-cli-addons', range: '*', hasData: false }
24 silly mapToRegistry name heroku-cli-addons
25 silly mapToRegistry using default registry
26 silly mapToRegistry registry https://cli-npm.heroku.com/
27 silly mapToRegistry uri https://cli-npm.heroku.com/heroku-cli-addons
28 verbose addNameRange registry:https://cli-npm.heroku.com/heroku-cli-addons not in flight; fetching
29 silly cache add parsed spec Result {
29 silly cache add   raw: 'heroku-apps',
29 silly cache add   scope: null,
29 silly cache add   name: 'heroku-apps',
29 silly cache add   rawSpec: '',
29 silly cache add   spec: '*',
29 silly cache add   type: 'range' }
30 silly addNamed heroku-apps@*
31 verbose addNamed "*" is a valid semver range for heroku-apps
32 silly addNameRange { name: 'heroku-apps', range: '*', hasData: false }
33 silly mapToRegistry name heroku-apps
34 silly mapToRegistry using default registry
35 silly mapToRegistry registry https://cli-npm.heroku.com/
36 silly mapToRegistry uri https://cli-npm.heroku.com/heroku-apps
37 verbose addNameRange registry:https://cli-npm.heroku.com/heroku-apps not in flight; fetching
38 silly cache add parsed spec Result {
38 silly cache add   raw: 'heroku-fork',
38 silly cache add   scope: null,
38 silly cache add   name: 'heroku-fork',
38 silly cache add   rawSpec: '',
38 silly cache add   spec: '*',
38 silly cache add   type: 'range' }
39 silly addNamed heroku-fork@*
40 verbose addNamed "*" is a valid semver range for heroku-fork
41 silly addNameRange { name: 'heroku-fork', range: '*', hasData: false }
42 silly mapToRegistry name heroku-fork
43 silly mapToRegistry using default registry
44 silly mapToRegistry registry https://cli-npm.heroku.com/
45 silly mapToRegistry uri https://cli-npm.heroku.com/heroku-fork
46 verbose addNameRange registry:https://cli-npm.heroku.com/heroku-fork not in flight; fetching
47 silly cache add parsed spec Result {
47 silly cache add   raw: 'heroku-git',
47 silly cache add   scope: null,
47 silly cache add   name: 'heroku-git',
47 silly cache add   rawSpec: '',
47 silly cache add   spec: '*',
47 silly cache add   type: 'range' }
48 silly addNamed heroku-git@*
49 verbose addNamed "*" is a valid semver range for heroku-git
50 silly addNameRange { name: 'heroku-git', range: '*', hasData: false }
51 silly mapToRegistry name heroku-git
52 silly mapToRegistry using default registry
53 silly mapToRegistry registry https://cli-npm.heroku.com/
54 silly mapToRegistry uri https://cli-npm.heroku.com/heroku-git
55 verbose addNameRange registry:https://cli-npm.heroku.com/heroku-git not in flight; fetching
56 silly cache add parsed spec Result {
56 silly cache add   raw: 'heroku-local',
56 silly cache add   scope: null,
56 silly cache add   name: 'heroku-local',
56 silly cache add   rawSpec: '',
56 silly cache add   spec: '*',
56 silly cache add   type: 'range' }
57 silly addNamed heroku-local@*
58 verbose addNamed "*" is a valid semver range for heroku-local
59 silly addNameRange { name: 'heroku-local', range: '*', hasData: false }
60 silly mapToRegistry name heroku-local
61 silly mapToRegistry using default registry
62 silly mapToRegistry registry https://cli-npm.heroku.com/
63 silly mapToRegistry uri https://cli-npm.heroku.com/heroku-local
64 verbose addNameRange registry:https://cli-npm.heroku.com/heroku-local not in flight; fetching
65 silly cache add parsed spec Result {
65 silly cache add   raw: 'heroku-run',
65 silly cache add   scope: null,
65 silly cache add   name: 'heroku-run',
65 silly cache add   rawSpec: '',
65 silly cache add   spec: '*',
65 silly cache add   type: 'range' }
66 silly addNamed heroku-run@*
67 verbose addNamed "*" is a valid semver range for heroku-run
68 silly addNameRange { name: 'heroku-run', range: '*', hasData: false }
69 silly mapToRegistry name heroku-run
70 silly mapToRegistry using default registry
71 silly mapToRegistry registry https://cli-npm.heroku.com/
72 silly mapToRegistry uri https://cli-npm.heroku.com/heroku-run
73 verbose addNameRange registry:https://cli-npm.heroku.com/heroku-run not in flight; fetching
74 silly cache add parsed spec Result {
74 silly cache add   raw: 'heroku-status',
74 silly cache add   scope: null,
74 silly cache add   name: 'heroku-status',
74 silly cache add   rawSpec: '',
74 silly cache add   spec: '*',
74 silly cache add   type: 'range' }
75 silly addNamed heroku-status@*
76 verbose addNamed "*" is a valid semver range for heroku-status
77 silly addNameRange { name: 'heroku-status', range: '*', hasData: false }
78 silly mapToRegistry name heroku-status
79 silly mapToRegistry using default registry
80 silly mapToRegistry registry https://cli-npm.heroku.com/
81 silly mapToRegistry uri https://cli-npm.heroku.com/heroku-status
82 verbose addNameRange registry:https://cli-npm.heroku.com/heroku-status not in flight; fetching
83 verbose request uri https://cli-npm.heroku.com/heroku-cli-addons
84 verbose request no auth needed
85 info attempt registry request try #1 at 12:04:07 AM
86 verbose request id 3c17d446aec9a8d8
87 http request GET https://cli-npm.heroku.com/heroku-cli-addons
88 verbose request uri https://cli-npm.heroku.com/heroku-apps
89 verbose request no auth needed
90 info attempt registry request try #1 at 12:04:07 AM
91 http request GET https://cli-npm.heroku.com/heroku-apps
92 verbose request uri https://cli-npm.heroku.com/heroku-fork
93 verbose request no auth needed
94 info attempt registry request try #1 at 12:04:07 AM
95 http request GET https://cli-npm.heroku.com/heroku-fork
96 verbose request uri https://cli-npm.heroku.com/heroku-git
97 verbose request no auth needed
98 info attempt registry request try #1 at 12:04:07 AM
99 http request GET https://cli-npm.heroku.com/heroku-git
100 verbose request uri https://cli-npm.heroku.com/heroku-local
101 verbose request no auth needed
102 info attempt registry request try #1 at 12:04:07 AM
103 http request GET https://cli-npm.heroku.com/heroku-local
104 verbose request uri https://cli-npm.heroku.com/heroku-run
105 verbose request no auth needed
106 info attempt registry request try #1 at 12:04:07 AM
107 http request GET https://cli-npm.heroku.com/heroku-run
108 verbose stack Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
108 verbose stack     at Error (native)
108 verbose stack     at Object.createSecureContext (_tls_common.js:87:19)
108 verbose stack     at Object.exports.connect (_tls_wrap.js:955:21)
108 verbose stack     at Agent.createConnection (https.js:73:22)
108 verbose stack     at Agent.createSocket (_http_agent.js:174:16)
108 verbose stack     at Agent.addRequest (_http_agent.js:143:23)
108 verbose stack     at new ClientRequest (_http_client.js:133:16)
108 verbose stack     at Object.exports.request (http.js:31:10)
108 verbose stack     at Object.exports.request (https.js:163:15)
108 verbose stack     at Request.start (C:\Users\Fernandez\AppData\Local\heroku\node-v4.1.1-windows-x86\lib\node_modules\npm\node_modules\request\request.js:803:30)
109 verbose cwd C:\Users\Fernandez\AppData\Local\heroku
110 error Windows_NT 10.0.10240
111 error argv "C:\\Users\\Fernandez\\AppData\\Local\\heroku\\node-v4.1.1-windows-x86\\bin\\node.exe" "C:\\Users\\Fernandez\\AppData\\Local\\heroku\\node-v4.1.1-windows-x86\\lib\\node_modules\\npm\\cli.js" "install" "heroku-cli-addons" "heroku-apps" "heroku-fork" "heroku-git" "heroku-local" "heroku-run" "heroku-status"
112 error node v4.1.1
113 error npm  v2.14.4
114 error error:0906D06C:PEM routines:PEM_read_bio:no start line
115 error If you need help, you may report this error at:
115 error     <https://github.com/npm/npm/issues>
116 verbose exit [ 1, true ]
```

**Comment by chavenor** [comment]
Upgraded my Windows 7 Machine and seem to be having the same issue.

**Comment by chavenor** [comment]
@iam--nash  Did you ever get this figured out?

**Comment by iam--nash** [comment]
@chavenor I'm sorry, for I my self havent figured out how to fix this aswell. I also tried lots of stuff to make it work . but nothing seems to work . I already send a ticket . hopefully things get better . :)

**Comment by iam--nash** [comment]
I conclude that there is something that is not being installed correctly. e.g nodejs, git, ruby or maybe heroku itself . but I am not certain, In case of installation process comparing to windows 8.1 installation I did not get any issues . but having installed this to windows 10 . its needs you to install the latest git 2.6.x where in windows 8.1 is fine with 1.9.x which is included in the heroku toolbelt .

**Comment by chavenor** [comment]
@iam--nash do you think I have a git issue -- here is what I have installed.
![git-image](https://cloud.githubusercontent.com/assets/1850981/10554317/f8c37c4e-7427-11e5-8f8b-ed22b5a08aa1.png)

**Comment by chavenor** [comment]
@iam--nash I'm thinking about the differences between Win 7 and Win 10 there are pretty large.  So I'm assuming that Git needed the update to handle the new stuff with Win 10.

**Comment by iam--nash** [comment]
@chavenor  that programs and feature window is Win7 right?
-
Btw, I checked again my systems variable. there is two declared path for git.
 **C:\Program Files\Git\cmd** & **C:\Program Files (x86)\git\cmd**
It looks suspicious to me since I have found out that there is no git folder in *Program Files (x86)* .

**Comment by chavenor** [comment]
@iam--nash I do have files for Git in the (x86) dir.   I do not have Git 64-bit installed.

**Comment by iam--nash** [comment]
@chavenor well if you are on 32 bit version of OS I guess that should really be on x86, In my case Im on 64bit os. Im wondering why would git create an environment variable that is not existing?

**Comment by chavenor** [comment]
@iam--nash I'm on 64-bit.  But heroku is shipping with 32-bit I belive.  The problem I'm having is that the heroku toolbelt upgrade isn't working and it seems to crash when trying to launch the part with npm.   I'm actually checking my Windows 2008 server and finding some interesting differences of the heroku install.

**Comment by chavenor** [comment]
@iam--nash 
These random crashes might be related to the maximum Windows default total path length.

**Comment by chavenor** [comment]
I'm going to be moving everything into this field.  https://github.com/heroku/heroku-cli/issues/91

**Comment by chavenor** [comment]
@dickeyxxx -- Here is the info.

@iam--nash I figured it out on my end with the help of the heroku staff.  Here is what we found. 

Any Windows 7 temp directory with more than one directory separated by a semi-colon will cause npm to hang when trying to move files to such directory.

Thus for installing/upgrading the heroku toolbelt would procedure as follows...

### Upgrading
In command prompt uninstall the heroku gem.
```gem uninstall heroku```
AND / OR 
Remove heroku toolbelt via Windows control panel --> Remove Programs --> Heroku --> Uninstall.

### Clean Installation
Make sure that your temp variables look like the below.
```
User Vars 
%USERPROFILE%\AppData\Local\Temp;C:\Program Files (x86)\Java\jdk1.6.0_25\bin
System Vars. 
%SystemRoot%\TEMP
```

Download the new installer from Heroku and product with the installation process.
