### ISSUE TITLE
Error when trying to install cordova and ionic - UNABLE_TO_VERIFY_LEAF_SIGNATURE

### ISSUE THREAD

**Issue by surajshaha17** [npm/npm#9877]
Getting following error when trying to install cordova and ionic, UNABLE_TO_VERIFY_LEAF_SIGNATURE
0 info it worked if it ends with ok
1 verbose cli [ 'D:\Programs\nodejs\node.exe',
1 verbose cli   'D:\Programs\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'cordova',
1 verbose cli   'ionic' ]
2 info using npm@2.14.4
3 info using node@v4.1.2
4 verbose install initial load of C:\Users\surajs\AppData\Roaming\npm\package.json
5 verbose readDependencies loading dependencies from C:\Users\surajs\AppData\Roaming\npm\package.json
6 silly cache add args [ 'cordova', null ]
7 verbose cache add spec cordova
8 silly cache add args [ 'ionic', null ]
9 verbose cache add spec ionic
10 silly cache add parsed spec Result {
10 silly cache add   raw: 'cordova',
10 silly cache add   scope: null,
10 silly cache add   name: 'cordova',
10 silly cache add   rawSpec: '',
10 silly cache add   spec: '_',
10 silly cache add   type: 'range' }
11 silly addNamed cordova@_
12 verbose addNamed "_" is a valid semver range for cordova
13 silly addNameRange { name: 'cordova', range: '_', hasData: false }
14 silly mapToRegistry name cordova
15 silly mapToRegistry using default registry
16 silly mapToRegistry registry https://registry.npmjs.org/
17 silly mapToRegistry uri https://registry.npmjs.org/cordova
18 verbose addNameRange registry:https://registry.npmjs.org/cordova not in flight; fetching
19 silly cache add parsed spec Result {
19 silly cache add   raw: 'ionic',
19 silly cache add   scope: null,
19 silly cache add   name: 'ionic',
19 silly cache add   rawSpec: '',
19 silly cache add   spec: '_',
19 silly cache add   type: 'range' }
20 silly addNamed ionic@_
21 verbose addNamed "_" is a valid semver range for ionic
22 silly addNameRange { name: 'ionic', range: '_', hasData: false }
23 silly mapToRegistry name ionic
24 silly mapToRegistry using default registry
25 silly mapToRegistry registry https://registry.npmjs.org/
26 silly mapToRegistry uri https://registry.npmjs.org/ionic
27 verbose addNameRange registry:https://registry.npmjs.org/ionic not in flight; fetching
28 verbose request uri https://registry.npmjs.org/cordova
29 verbose request no auth needed
30 info attempt registry request try #1 at 6:04:26 PM
31 verbose request id e541c08d02bd926e
32 http request GET https://registry.npmjs.org/cordova
33 verbose request uri https://registry.npmjs.org/ionic
34 verbose request no auth needed
35 info attempt registry request try #1 at 6:04:26 PM
36 http request GET https://registry.npmjs.org/ionic
37 info retry will retry, error on last attempt: Error: unable to verify the first certificate
38 info retry will retry, error on last attempt: Error: unable to verify the first certificate
39 info attempt registry request try #2 at 6:04:37 PM
40 http request GET https://registry.npmjs.org/ionic
41 info attempt registry request try #2 at 6:04:37 PM
42 http request GET https://registry.npmjs.org/cordova
43 info retry will retry, error on last attempt: Error: unable to verify the first certificate
44 info retry will retry, error on last attempt: Error: unable to verify the first certificate
45 info attempt registry request try #3 at 6:05:37 PM
46 http request GET https://registry.npmjs.org/ionic
47 info attempt registry request try #3 at 6:05:37 PM
48 http request GET https://registry.npmjs.org/cordova
49 verbose stack Error: unable to verify the first certificate
49 verbose stack     at Error (native)
49 verbose stack     at TLSSocket.<anonymous> (_tls_wrap.js:1000:38)
49 verbose stack     at emitNone (events.js:67:13)
49 verbose stack     at TLSSocket.emit (events.js:166:7)
49 verbose stack     at TLSSocket._finishInit (_tls_wrap.js:567:8)
50 verbose cwd C:\
51 error Windows_NT 6.1.7601
52 error argv "D:\Programs\nodejs\node.exe" "D:\Programs\nodejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "cordova" "ionic"
53 error node v4.1.2
54 error npm  v2.14.4
55 error code UNABLE_TO_VERIFY_LEAF_SIGNATURE
56 error unable to verify the first certificate
57 error If you need help, you may report this error at:
57 error     https://github.com/npm/npm/issues
58 verbose exit [ 1, true ]

**Comment by surajshaha17** [comment]
Can anybody help me to resolve this issue?
