### ISSUE TITLE
cannot convert undefined or null to object

### ISSUE THREAD

**Issue by aredridel** [npm/npm#9896]
```
:; npm i eslint-jsx
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/lib/node_modules/node-darwin-x64/bin/node" "/usr/local/bin/npm" "i" "eslint-jsx"
npm ERR! node v4.1.0
npm ERR! npm  v3.3.6

npm ERR! Cannot convert undefined or null to object
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/aredridel/Projects/webrtc_skype/npm-debug.log
```

debug log at https://gist.github.com/aredridel/c62cf9c5db0190883702

**Comment by mmiller42** [comment]
@aredridel Did you ever determine the cause of this issue? I just had the same thing when attempting to install dependencies on a Webpack/Angular 2 project.

**Comment by stadler** [comment]
What helped for me was to look deeper into npm-debug.log and determine the actual dependeny that was broken/missing. Then you can update the dependeny that actually caused the broken transitive dependency. Hope hat helps a bit.

**Comment by dynamite-ready** [comment]
I'm running into the exact same issue using NPM 2.15.9 and Node JS 4.6.1 on Windows 8.
Any NPM I try to install draws a - `Cannot convert undefined or null to object` - It's certainly not a code issue, because I can install the exact same projects and NPM packages on my OSX machine.

What's more, I've not made any recent changes to my Windows 8 box. What might cause this issue?

**Comment by avindra** [comment]
I'm noticing this error when trying to install a package that I've recently published. Could this be a distributed systems thing that isn't being error handled properly?

**Comment by legodude17** [comment]
What is `npm -v` and `node -v`?

**Comment by cmegown** [comment]
It sounds like @avindra and I are in the same boat right now. I just published a package for testing approx. 15 minutes ago and still receive this error when trying to download in another project.

For what it's worth I'm running node 6.9.1 and npm 3.10.8.

**Comment by legodude17** [comment]
Have you tried what @stadler suggested?

**Comment by avindra** [comment]
In my case, I was playing around with scoped modules and the problem kind of went away on its own after publishing and unpublishing a few times 🙃

**Comment by othiym23** [comment]
repro:

```console
ogd@bauchelain ~/D/projects> mkdir test-node-version
ogd@bauchelain ~/D/projects> cd test-node-version/
ogd@bauchelain ~/D/p/test-node-version> npm init -y
Wrote to /Users/ogd/Documents/projects/test-node-version/package.json:

{
  "name": "test-node-version",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "Forrest L Norvell <ogd@aoaioxxysz.net>",
  "license": "ISC"
}


ogd@bauchelain ~/D/p/test-node-version> npm i -S node-rfc
npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "-S" "node-rfc"
npm ERR! node v7.2.0
npm ERR! npm  v4.0.2

npm ERR! Cannot convert undefined or null to object
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ogd/Documents/projects/test-node-version/npm-debug.log
```

This happens when there are no version documents left on the package metadata object returned by the registry, and is indeed a big bug.

**Comment by othiym23** [comment]
This is actually two bugs in different parts of `fetchPackageMetadata`, not one. In both cases, there are no `version` documents on the associated registry metadata, but `eslint-jsx` has no versions under the `"time"` field, where `node-rfc` has versions there, but no versions attached to the document. See the stacktraces for more details.

**Comment by masiddiqui91** [comment]
so whats the resolution for this kind of error ?

**Comment by shamansir** [comment]
I get the similar error with `npm install linter-eslint`

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--save',
1 verbose cli   'linter-eslint' ]
2 info using npm@3.6.0
3 info using node@v5.7.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData linter-eslint
8 silly fetchNamedPackageData linter-eslint
9 silly mapToRegistry name linter-eslint
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry uri https://registry.npmjs.org/linter-eslint
13 verbose request uri https://registry.npmjs.org/linter-eslint
14 verbose request no auth needed
15 info attempt registry request try #1 at 12:14:13 AM
16 verbose request using bearer token for auth
17 verbose request id 9b6b7fe196fc85a8
18 verbose etag W/"54b03585-1cd"
19 verbose lastModified Fri, 09 Jan 2015 20:09:41 GMT
20 http request GET https://registry.npmjs.org/linter-eslint
21 http 304 https://registry.npmjs.org/linter-eslint
22 verbose headers { server: 'nginx/1.10.1',
22 verbose headers   'last-modified': 'Fri, 09 Jan 2015 20:09:41 GMT',
22 verbose headers   etag: '"54b03585-1cd"',
22 verbose headers   'cache-control': 'max-age=300',
22 verbose headers   'accept-ranges': 'bytes',
22 verbose headers   date: 'Thu, 15 Dec 2016 23:14:14 GMT',
22 verbose headers   via: '1.1 varnish',
22 verbose headers   connection: 'keep-alive',
22 verbose headers   'x-served-by': 'cache-fra1222-FRA',
22 verbose headers   'x-cache': 'MISS',
22 verbose headers   'x-cache-hits': '0',
22 verbose headers   'x-timer': 'S1481843654.745381,VS0,VE1',
22 verbose headers   vary: 'Accept-Encoding' }
23 silly get cb [ 304,
23 silly get   { server: 'nginx/1.10.1',
23 silly get     'last-modified': 'Fri, 09 Jan 2015 20:09:41 GMT',
23 silly get     etag: '"54b03585-1cd"',
23 silly get     'cache-control': 'max-age=300',
23 silly get     'accept-ranges': 'bytes',
23 silly get     date: 'Thu, 15 Dec 2016 23:14:14 GMT',
23 silly get     via: '1.1 varnish',
23 silly get     connection: 'keep-alive',
23 silly get     'x-served-by': 'cache-fra1222-FRA',
23 silly get     'x-cache': 'MISS',
23 silly get     'x-cache-hits': '0',
23 silly get     'x-timer': 'S1481843654.745381,VS0,VE1',
23 silly get     vary: 'Accept-Encoding' } ]
24 verbose etag https://registry.npmjs.org/linter-eslint from cache
25 verbose get saving linter-eslint to /Users/shamansir/.npm/registry.npmjs.org/linter-eslint/.cache.json
26 verbose correctMkdir /Users/shamansir/.npm correctMkdir not in flight; initializing
27 verbose stack TypeError: Cannot convert undefined or null to object
27 verbose stack     at Function.keys (native)
27 verbose stack     at pickVersionFromRegistryDocument (/usr/local/lib/node_modules/npm/lib/fetch-package-metadata.js:121:29)
27 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/iferr/index.js:13:50
27 verbose stack     at /usr/local/lib/node_modules/npm/lib/utils/pulse-till-done.js:19:8
27 verbose stack     at saved (/usr/local/lib/node_modules/npm/lib/cache/caching-client.js:168:7)
27 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:210:7
27 verbose stack     at FSReqWrap.oncomplete (fs.js:82:15)
28 verbose cwd /Users/...
29 error Darwin 16.1.0
30 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "linter-eslint"
31 error node v5.7.0
32 error npm  v3.6.0
33 error Cannot convert undefined or null to object
34 error If you need help, you may report this error at:
34 error     <https://github.com/npm/npm/issues>
35 verbose exit [ 1, true ]
```

**Comment by shamansir** [comment]
Relates to https://github.com/eslint/eslint/issues/6115 and https://github.com/wix/eslint-plugin-lodash/issues/76

**Comment by dlombardi** [comment]
I published a package on npm and cannot install is because of this error.  Any updates?

**Comment by kumavis** [comment]
I encountered this when cloning and npm installing this project https://github.com/anvaka/npmgraph
```
╭─kumavis@xyzs-MacBook-Pro  ~/dev/npmgraph ‹node-v6.3.1›  (master*) 
╰─$ node -v
v6.3.1
╭─kumavis@xyzs-MacBook-Pro  ~/dev/npmgraph ‹node-v6.3.1›  (master*) 
╰─$ npm -v
4.4.1
```

**Comment by EverettQuebral** [comment]
I'm also having the same issue.  Tried with a couple different version but still has the same error message

Versions tried
node v6.10.10
npm v3.10.10

node v5.0.0
npm v3.3.6

node v4.2.2
npm v2.14.7

**Comment by HamsterCoder** [comment]
For me this error occured when installing packages from a local registry and not having a `.npmrc` file with registry info in it.

**Comment by damianprzygodzki** [comment]
Good evening guys!

Ive encountered that error when `npm install` tried to install `"grunt-contrib-concat": "~0.1.2"`.

```
444 verbose stack TypeError: Cannot convert undefined or null to object
444 verbose stack     at Function.keys (<anonymous>)
444 verbose stack     at pickVersionFromRegistryDocument (/usr/local/lib/node_modules/npm/lib/fetch-package-metadata.js:126:29)
```

My stack is:

```
448 error node v7.9.0
449 error npm  v4.2.0
```

I've tried to make some update, nothing helped. I have created also issue that package 
https://github.com/gruntjs/grunt-contrib-concat/issues/179.

Cheers!

**Comment by kwlininger** [comment]
My case was similar to others:  my package.json didn't have a `"repository": ""` entry.  
That was harder to find than it should have been.

**Comment by beatgrabe** [comment]
I was also facing this issue and just deleted the entire `node_modules` directory by a following `npm i`

**Comment by monolithed** [comment]
The same problem

```
197 verbose node v7.10.0
198 verbose npm  v4.6.1
199 error Cannot convert undefined or null to object
200 verbose exit [ 1, true ]
```

> For me this error occured when installing packages from a local registry and not having a .npmrc file with registry info in it.

Nice one!

**Comment by kaguilarcamacho** [comment]
I'm also having this error. Any idea how to fix? or is there any workaround?

npm install

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10

npm ERR! Cannot convert undefined or null to object
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10

npm ERR! Cannot convert undefined or null to object
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10

npm ERR! Cannot convert undefined or null to object
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm -v  : 3.10.10
node -v : v6.11.0

**Comment by LarsLiden** [comment]
If the npm package is coming from a private registry you'll see this error if you don't have a .npmrc file that points to the private registry:

For VSO for example you'd need something like:
registry=https://xxxx.pkgs.visualstudio.com/....

**Comment by jonsalvas** [comment]
I still have the issue described on a EL-machine  with 
npm -v : 3.10.10
node -v : v6.11.0.

However, on a windows 10 machine with 
npm -v : 5.3.0 and
node -v : v6.11.0

and ubuntu machine with 
npm -v : 3.5.2 and
node -v : v4.8.4

with the same sources from the same repo everything works fine. I'am using a nexus repo.

is there any workaround or fix available?

**Comment by Stuk** [comment]
FYI I saw this error after changing my corp password and then using an internal Artifactory server with `npm install`. After configuring my password correctly in `~/.npmrc` the error disappeared.

**Comment by n4nagappan** [comment]
Running  ``` npm install ``` and then installing the module again worked for me

**Comment by alundiak** [comment]
Windows 7.

$ node -v
v6.12.0

$ npm -v
3.8.3

And I have this error after `npm update`.

My `package.json` is quite simple, no scoped dependencies.
But I use custom registry (based on Nexus hosted and proxy repos)

**Comment by krichey15** [comment]
This has been Open for a while now with no real solution....Has anyone actually found a fix to the original post????

**Comment by dfairaizl** [comment]
@krichey15  NPM might be having an issue https://status.npmjs.org/incidents/41zfb8qpvrdj Some packages are not available at the moment.

**Comment by DamnedScholar** [comment]
@dfairaizl Thank you. I was getting very frustrated and now I can go eat with peace of mind and come back to it when all of those ducks get sorted.

**Comment by cortezcristian** [comment]
this is happening again!!! Grrr...!

npm ERR! node v6.0.0
npm ERR! npm  v3.8.6

npm ERR! Cannot convert undefined or null to object

**Comment by Dzejms** [comment]
Hopefully the ducks won't get bogosorted.

**Comment by darmie** [comment]
Mahn.... When would https://status.npmjs.org/incidents/41zfb8qpvrdj be fully resolved??

**Comment by Monte9** [comment]
Yup, just started happening to me as well. I guess we will just have to wait until it's fixed and try again in a bit

**Comment by Monte9** [comment]
Yup, just started happening to me as well. I guess we will just have to wait until it's fixed and try again in a bit

**Comment by bobbylight** [comment]
Perhaps in addition to restoring the deleted packages, the npm team should work on making this error message more clear?

**Comment by neon-vortex** [comment]
same issue here

**Comment by jonathanasquier** [comment]
same

**Comment by itschrisabroad** [comment]
Apparently only 9 packages missing, but still getting "npm ERR! Cannot convert undefined or null to object". Weirder and weirder

**Comment by Abdul-Miraj** [comment]
save us

**Comment by fedeverdi** [comment]
same issue here

**Comment by atoporkov** [comment]
+1 :((

**Comment by karlmose** [comment]
Same issue here, when trying to install Cordova

**Comment by atoporkov** [comment]
It seems like everything is OK now!

**Comment by stefan-legacy-projects** [comment]
So did anyone know what really happened ?

**Comment by itschrisabroad** [comment]
New error now! npm ERR! fetch failed https://registry.npmjs.org/pinkie-promise/-/pinkie-promise-2.0.1.tgz Wonder if the gremlins are still being worked out

**Comment by Dzejms** [comment]
We're back! Thx!

**Comment by darmie** [comment]
@Dzejms like, for real??

**Comment by Dzejms** [comment]
Worked on my machine. Been trying to install windows-build-tools and got the null ref exception as described above. It now installs with 0 issues.

**Comment by darmie** [comment]
Working here now!

**Comment by fedeverdi** [comment]
Perfect +++

**Comment by dfairaizl** [comment]
Yep, looks like its working again. Thanks NPM folks!

**Comment by stefan-legacy-projects** [comment]
"The moment when you decide to test on production, and if it fails we will revert it to the old release."
And I just spent 1 hour testing with different versions of node and npm.

**Comment by thefourtheye** [comment]
@Stuk's suggestion worked for me. node v6.14.2 (npm v3.10.10) on Mac OS.
