### ISSUE TITLE
"Failed parsing JSON config key editor" when quotation marks in environment variable

### ISSUE THREAD

**Issue by jdoose** [npm/npm#9899]
npm throws an error "Failed parsing JSON config key editor" on "npm install" when quotation marks are used in environment variable:

Using quoation marks, will fail:

```
F:\Work\gitHub\electron-boilerplate>set EDITOR="C:\Program Files\Sublime Text 2\sublime_text.exe"

F:\Work\gitHub\electron-boilerplate>npm install
npm WARN package.json @ No repository field.
npm WARN package.json @ No license field.
npm WARN optional dep failed, continuing appdmg@0.3.4

> @ postinstall F:\Work\gitHub\electron-boilerplate
> node ./tasks/app_npm_install

Error: Failed parsing JSON config key editor: "C:\Program Files\Sublime Text 2\sublime_text.exe"
    at parseField (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:386:13)
    at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:338:17
    at Array.forEach (native)
    at Conf.add (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:337:23)
    at ConfigChain.addEnv (C:\Program Files\nodejs\node_modules\npm\node_modules\config-chain\index.js:207:15)
    at Conf.addEnv (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:364:30)
    at load_ (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:107:8)
    at Conf.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:96:5)
    at Conf.emit (events.js:107:17)
    at ConfigChain._resolve (C:\Program Files\nodejs\node_modules\npm\node_modules\config-chain\index.js:281:34)

C:\Program Files\nodejs\node_modules\npm\lib\npm.js:28
    throw new Error('npm.load() required')
          ^
Error: npm.load() required
    at Object.npm.config.get (C:\Program Files\nodejs\node_modules\npm\lib\npm.js:28:11)
    at exit (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:58:40)
    at process.errorHandler (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:377:3)
    at process.emit (events.js:107:17)
    at process._fatalException (node.js:236:26)
    at fs.js:334:14
    at FSReqWrap.oncomplete (fs.js:95:15)
```

Not using quoation marks, will succeed:

```
F:\Work\gitHub\electron-boilerplate>set EDITOR=C:\Program Files\Sublime Text 2\sublime_text.exe

F:\Work\gitHub\electron-boilerplate>npm install
npm WARN package.json @ No repository field.
npm WARN package.json @ No license field.
npm WARN optional dep failed, continuing appdmg@0.3.4

> @ postinstall F:\Work\gitHub\electron-boilerplate
> node ./tasks/app_npm_install

npm WARN package.json electron-boilerplate@0.1.0 No repository field.
npm WARN package.json electron-boilerplate@0.1.0 No README data
npm WARN package.json electron-boilerplate@0.1.0 No license field.
```

**Comment by KenanY** [comment]
@jdoose `npm --version`?

**Comment by jdoose** [comment]
Sorry, forgot to mention that.

It is 2.11.2

**Comment by jdoose** [comment]
Also happening in 3.3.5

**Comment by ramden** [comment]
Also happening on 3.10.10. Without quotation marks it works

**Comment by jdoose** [comment]
It is not happening on 'npm install' anymore but it still happens on ' npm start' in a react app (npm version 5.4.2), new issue for follow up: #18663
