### ISSUE TITLE
Cannot shrinkwrap this package.json w/ 3.3.7

### ISSUE THREAD

**Issue by aaronjensen** [npm/npm#9912]
https://gist.github.com/aaronjensen/8d3c7525655c707a83e3

``` bash
$ npm i
npm WARN prefer global js-beautify@1.5.10 should be installed with -g
npm WARN prefer global node-gyp@3.0.3 should be installed with -g

> bufferutil@1.2.1 install /Users/aaronjensen/Source/curadora/booking-site/node_modules/bufferutil
> node-gyp rebuild




$ npm shrinkwrap --dev
npm ERR! Darwin 15.0.0
npm ERR! argv "/Users/aaronjensen/.nvm/versions/node/v4.1.0/bin/node" "/Users/aaronjensen/.nvm/versions/node/v4.1.0/bin/npm" "shrinkwrap" "--dev"
npm ERR! node v4.1.0
npm ERR! npm  v3.3.7

npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! missing: globals@^8.5.0, required by eslint@1.3.1
npm ERR! missing: handlebars@^3.0.3, required by eslint@1.3.1
npm ERR! missing: inquirer@^0.9.0, required by eslint@1.3.1
npm ERR! missing: object-assign@^2.0.0, required by eslint@1.3.1
npm ERR! missing: strip-json-comments@~1.0.1, required by eslint@1.3.1
npm ERR! extraneous: node-pre-gyp@0.6.12 /Users/aaronjensen/Source/curadora/booking-site/node_modules/node-pre-gyp
npm ERR! extraneous: tar-pack@2.0.0 /Users/aaronjensen/Source/curadora/booking-site/node_modules/tar-pack
npm ERR! missing: async@^1.3.0, required by webpack@1.12.2
npm ERR! missing: supports-color@^3.1.0, required by webpack@1.12.2
npm ERR! missing: uglify-js@~2.4.24, required by webpack@1.12.2
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/aaronjensen/Source/curadora/booking-site/npm-debug.log
```

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/aaronjensen/.nvm/versions/node/v4.1.0/bin/node',
1 verbose cli   '/Users/aaronjensen/.nvm/versions/node/v4.1.0/bin/npm',
1 verbose cli   'shrinkwrap',
1 verbose cli   '--dev' ]
2 info using npm@3.3.7
3 info using node@v4.1.0
4 verbose stack Error: Problems were encountered
4 verbose stack Please correct and try again.
4 verbose stack missing: globals@^8.5.0, required by eslint@1.3.1
4 verbose stack missing: handlebars@^3.0.3, required by eslint@1.3.1
4 verbose stack missing: inquirer@^0.9.0, required by eslint@1.3.1
4 verbose stack missing: object-assign@^2.0.0, required by eslint@1.3.1
4 verbose stack missing: strip-json-comments@~1.0.1, required by eslint@1.3.1
4 verbose stack extraneous: node-pre-gyp@0.6.12 /Users/aaronjensen/Source/curadora/booking-site/node_modules/node-pre-gyp
4 verbose stack extraneous: tar-pack@2.0.0 /Users/aaronjensen/Source/curadora/booking-site/node_modules/tar-pack
4 verbose stack missing: async@^1.3.0, required by webpack@1.12.2
4 verbose stack missing: supports-color@^3.1.0, required by webpack@1.12.2
4 verbose stack missing: uglify-js@~2.4.24, required by webpack@1.12.2
4 verbose stack     at shrinkwrap_ (/Users/aaronjensen/.nvm/versions/node/v4.1.0/lib/node_modules/npm/lib/shrinkwrap.js:101:15)
4 verbose stack     at /Users/aaronjensen/.nvm/versions/node/v4.1.0/lib/node_modules/npm/lib/shrinkwrap.js:36:5
4 verbose stack     at /Users/aaronjensen/.nvm/versions/node/v4.1.0/lib/node_modules/npm/node_modules/iferr/index.js:13:50
4 verbose stack     at /Users/aaronjensen/.nvm/versions/node/v4.1.0/lib/node_modules/npm/lib/install/deps.js:121:5
4 verbose stack     at LOOP (/Users/aaronjensen/.nvm/versions/node/v4.1.0/lib/node_modules/npm/node_modules/slide/lib/chain.js:7:26)
4 verbose stack     at /Users/aaronjensen/.nvm/versions/node/v4.1.0/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
4 verbose stack     at cb (/Users/aaronjensen/.nvm/versions/node/v4.1.0/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
4 verbose stack     at /Users/aaronjensen/.nvm/versions/node/v4.1.0/lib/node_modules/npm/lib/install/deps.js:121:5
4 verbose stack     at LOOP (/Users/aaronjensen/.nvm/versions/node/v4.1.0/lib/node_modules/npm/node_modules/slide/lib/chain.js:7:26)
4 verbose stack     at /Users/aaronjensen/.nvm/versions/node/v4.1.0/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
5 verbose cwd /Users/aaronjensen/Source/curadora/booking-site
6 error Darwin 15.0.0
7 error argv "/Users/aaronjensen/.nvm/versions/node/v4.1.0/bin/node" "/Users/aaronjensen/.nvm/versions/node/v4.1.0/bin/npm" "shrinkwrap" "--dev"
8 error node v4.1.0
9 error npm  v3.3.7
10 error Problems were encountered
10 error Please correct and try again.
10 error missing: globals@^8.5.0, required by eslint@1.3.1
10 error missing: handlebars@^3.0.3, required by eslint@1.3.1
10 error missing: inquirer@^0.9.0, required by eslint@1.3.1
10 error missing: object-assign@^2.0.0, required by eslint@1.3.1
10 error missing: strip-json-comments@~1.0.1, required by eslint@1.3.1
10 error extraneous: node-pre-gyp@0.6.12 /Users/aaronjensen/Source/curadora/booking-site/node_modules/node-pre-gyp
10 error extraneous: tar-pack@2.0.0 /Users/aaronjensen/Source/curadora/booking-site/node_modules/tar-pack
10 error missing: async@^1.3.0, required by webpack@1.12.2
10 error missing: supports-color@^3.1.0, required by webpack@1.12.2
10 error missing: uglify-js@~2.4.24, required by webpack@1.12.2
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
```

**Comment by aaronjensen** [comment]
Any additional work on the package, like `npm i --save-dev webpack` also installs lots of extraneous packages.
