### ISSUE TITLE
npm pack: "Path must be a string. Received [ array ]"

### ISSUE THREAD

**Issue by Granjow** [npm/npm#9917]
When I run npm pack in a directory where angular-ui-grid is installed via bower, npm pack fails:

```
> npm pack
npm ERR! Linux 3.11-2-amd64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "pack"
npm ERR! node v4.1.2
npm ERR! npm  v2.14.4

npm ERR! Path must be a string. Received [ './less',
npm ERR!   './ui-grid.css',
npm ERR!   './ui-grid.eot',
npm ERR!   './ui-grid.js',
npm ERR!   './ui-grid.svg',
npm ERR!   './ui-grid.ttf',
npm ERR!   './ui-grid.woff' ]
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/b/npm-debug.log
```

Demo package [here](http://granjow.net/uploads/temp/npm-pack-fails.zip); you can also create it yourself with `bower.json` and `package.json` below. Run

```
bower install
npm pack
```

to reproduce.

`bower.json`

```
{
  "name": "foo",
  "version": "0.0.0",
  "dependencies": {
    "angular-ui-grid": "~3.0.0-rc.22"
  },
  "appPath": "app",
  "moduleName": "foo"
}
```

`package.json`

```
{
  "name": "npm-grid",
  "version": "0.0.1"
}
```

npm-debug.log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'pack' ]
2 info using npm@2.14.4
3 info using node@v4.1.2
4 silly cache add args [ '.', null ]
5 verbose cache add spec .
6 silly cache add parsed spec Result {
6 silly cache add   raw: '.',
6 silly cache add   scope: null,
6 silly cache add   name: null,
6 silly cache add   rawSpec: '.',
6 silly cache add   spec: '/tmp/b',
6 silly cache add   type: 'directory' }
7 verbose addLocalDirectory /home/sie/.npm/npm-grid/0.0.1/package.tgz not in flight; packing
8 verbose tar pack [ '/home/sie/.npm/npm-grid/0.0.1/package.tgz', '/tmp/b' ]
9 verbose tarball /home/sie/.npm/npm-grid/0.0.1/package.tgz
10 verbose folder /tmp/b
11 info prepublish npm-grid@0.0.1
12 verbose stack TypeError: Path must be a string. Received [ './less',
12 verbose stack   './ui-grid.css',
12 verbose stack   './ui-grid.eot',
12 verbose stack   './ui-grid.js',
12 verbose stack   './ui-grid.svg',
12 verbose stack   './ui-grid.ttf',
12 verbose stack   './ui-grid.woff' ]
12 verbose stack     at assertPath (path.js:8:11)
12 verbose stack     at Object.posix.resolve (path.js:426:5)
12 verbose stack     at Packer.applyIgnores (/usr/local/lib/node_modules/npm/node_modules/fstream-npm/fstream-npm.js:109:59)
12 verbose stack     at Packer.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/fstream-npm/node_modules/fstream-ignore/ignore.js:181:17)
12 verbose stack     at Array.filter (native)
12 verbose stack     at Packer.IgnoreReader.filterEntries (/usr/local/lib/node_modules/npm/node_modules/fstream-npm/node_modules/fstream-ignore/ignore.js:179:31)
12 verbose stack     at Packer.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/fstream-npm/node_modules/fstream-ignore/ignore.js:92:12)
12 verbose stack     at Packer.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/fstream-npm/node_modules/fstream-ignore/ignore.js:134:5)
12 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:76:16
12 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
13 verbose cwd /tmp/b
14 error Linux 3.11-2-amd64
15 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "pack"
16 error node v4.1.2
17 error npm  v2.14.4
18 error Path must be a string. Received [ './less',
18 error   './ui-grid.css',
18 error   './ui-grid.eot',
18 error   './ui-grid.js',
18 error   './ui-grid.svg',
18 error   './ui-grid.ttf',
18 error   './ui-grid.woff' ]
19 error If you need help, you may report this error at:
19 error     <https://github.com/npm/npm/issues>
20 verbose exit [ 1, true ]
```

**Comment by panuhorsmalahti** [comment]
I also got this:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'publish' ]
2 info using npm@3.3.9
3 info using node@v4.2.1
4 verbose publish [ '.' ]
5 silly cache add args [ '.', null ]
6 verbose cache add spec .
7 silly cache add parsed spec Result {
7 silly cache add   raw: '.',
7 silly cache add   scope: null,
7 silly cache add   name: null,
7 silly cache add   rawSpec: '.',
7 silly cache add   spec: '/tmp/build',
7 silly cache add   type: 'directory' }
8 verbose addLocalDirectory /home/builduser/.npm/my_application/2.10.0/package.tgz not in flight; packing
9 info lifecycle my_application@2.10.0~prepublish: my_application@2.10.0
10 silly lifecycle my_application@2.10.0~prepublish: no script for prepublish, continuing
11 verbose tar pack [ '/home/builduser/.npm/my_application/2.10.0/package.tgz',
11 verbose tar pack   '/tmp/build' ]
12 verbose tarball /home/builduser/.npm/my_application/2.10.0/package.tgz
13 verbose folder /tmp/build
14 verbose stack TypeError: Path must be a string. Received [ './less',
14 verbose stack   './ui-grid.css',
14 verbose stack   './ui-grid.eot',
14 verbose stack   './ui-grid.js',
14 verbose stack   './ui-grid.svg',
14 verbose stack   './ui-grid.ttf',
14 verbose stack   './ui-grid.woff' ]
14 verbose stack     at assertPath (path.js:8:11)
14 verbose stack     at Object.posix.resolve (path.js:426:5)
14 verbose stack     at InstancePacker.Packer.applyIgnores (/usr/local/lib/node_modules/npm/node_modules/fstream-npm/fstream-npm.js:109:59)
14 verbose stack     at InstancePacker.BundledPacker.applyIgnores (/usr/local/lib/node_modules/npm/lib/utils/tar.js:135:40)
14 verbose stack     at InstancePacker.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/fstream-npm/node_modules/fstream-ignore/ignore.js:181:17)
14 verbose stack     at Array.filter (native)
14 verbose stack     at InstancePacker.IgnoreReader.filterEntries (/usr/local/lib/node_modules/npm/node_modules/fstream-npm/node_modules/fstream-ignore/ignore.js:179:31)
14 verbose stack     at InstancePacker.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/fstream-npm/node_modules/fstream-ignore/ignore.js:92:12)
14 verbose stack     at InstancePacker.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/fstream-npm/node_modules/fstream-ignore/ignore.js:134:5)
14 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:76:16
15 verbose cwd /tmp/build
16 error Linux 3.13.0-24-generic
17 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "publish"
18 error node v4.2.1
19 error npm  v3.3.9
20 error Path must be a string. Received [ './less',
20 error   './ui-grid.css',
20 error   './ui-grid.eot',
20 error   './ui-grid.js',
20 error   './ui-grid.svg',
20 error   './ui-grid.ttf',
20 error   './ui-grid.woff' ]
21 error If you need help, you may report this error at:
21 error     <https://github.com/npm/npm/issues>
22 verbose exit [ 1, true ]
```

Seems to be related to angular-ui-grid.

**Comment by sbruno** [comment]
In fact it is an angular-ui-grid problem.
an array is allowed in bower.json https://github.com/bower/spec/blob/master/json.md
but not in package.json, but some ui-grid build process is copying the contents of bower.json to package.json.

I opened a bug for that:
https://github.com/angular-ui/ui-grid/issues/4743

**Comment by Granjow** [comment]
Thanks for opening the bug and figuring it out!
