### ISSUE TITLE
[Regression] npm 3.3.7 breaks on `npm install`

### ISSUE THREAD

**Issue by mzgol** [npm/npm#9922]
I have the following deps:
```js
  "devDependencies": {
    "autoprefixer": "6.0.3",
    "autoprefixer-cli": "1.0.0",
    "babel-core": "5.8.25",
    "beepbeep": "1.2.0",
    "check-dependencies": "0.10.3",
    "chokidar-cli": "1.0.1",
    "clean-css": "3.4.5",
    "eslint": "1.6.0",
    "eslint-config-mzgol": "0.0.6",
    "fs-extra": "0.24.0",
    "node-sass": "3.4.0-beta1",
    "npm-run-all": "1.2.11",
    "requirejs": "2.1.20",
    "semver": "5.0.3",
    "uglify-js": "2.4.24"
  },
```

`npm install` on that setup works fine with npm@3.3.6 (a.k.a. latest) but break with npm@3.3.7 (a.k.a. next):

```
$ npm i
npm WARN prefer global node-gyp@3.0.3 should be installed with -g

> fsevents@1.0.2 install /Users/mgol/Documents/projects/muzeum-slaskie-bilety/node_modules/fsevents
> node-pre-gyp install --fallback-to-build


$ echo $?
1
```
`npm-debug.log` ends with:
```
43192 verbose lifecycle fsevents@1.0.2~install: CWD: /Users/mgol/Documents/projects/muzeum-slaskie-bilety/node_modules/fsevents
43193 silly lifecycle fsevents@1.0.2~install: Args: [ '-c', 'node-pre-gyp install --fallback-to-build' ]
43194 verbose stack Error: spawn E2BIG
43194 verbose stack     at exports._errnoException (util.js:849:11)
43194 verbose stack     at ChildProcess.spawn (internal/child_process.js:298:11)
43194 verbose stack     at exports.spawn (child_process.js:339:9)
43194 verbose stack     at spawn (/Users/mgol/.nvm/versions/node/v4.1.2/lib/node_modules/npm/lib/utils/spawn.js:7:13)
43194 verbose stack     at runCmd_ (/Users/mgol/.nvm/versions/node/v4.1.2/lib/node_modules/npm/lib/utils/lifecycle.js:214:14)
43194 verbose stack     at runCmd (/Users/mgol/.nvm/versions/node/v4.1.2/lib/node_modules/npm/lib/utils/lifecycle.js:172:5)
43194 verbose stack     at runPackageLifecycle (/Users/mgol/.nvm/versions/node/v4.1.2/lib/node_modules/npm/lib/utils/lifecycle.js:136:3)
43194 verbose stack     at Array.<anonymous> (/Users/mgol/.nvm/versions/node/v4.1.2/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
43194 verbose stack     at LOOP (/Users/mgol/.nvm/versions/node/v4.1.2/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
43194 verbose stack     at chain (/Users/mgol/.nvm/versions/node/v4.1.2/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
43195 verbose cwd /Users/mgol/Documents/projects/muzeum-slaskie-bilety
43196 error Darwin 15.0.0
43197 error argv "/Users/mgol/.nvm/versions/node/v4.1.2/bin/node" "/Users/mgol/.nvm/versions/node/v4.1.2/bin/npm" "i"
43198 error node v4.1.2
43199 error npm  v3.3.7
43200 error code E2BIG
43201 error errno E2BIG
43202 error syscall spawn
43203 error spawn E2BIG
43204 error If you need help, you may report this error at:
43204 error     <https://github.com/npm/npm/issues>
43205 verbose exit [ 1, true ]
```

**Comment by adriaanthomas** [comment]
I guess `E2BIG` is caused by what is shown on the previous line, in my case a `PATH` that is set to a string with over 660k characters in it.

**Comment by mzgol** [comment]
I've checked that the first bad commit is 22a3af055f934f8de20ebd5f4a286447dda84f81.

**Comment by aredridel** [comment]
Goodness. What's your `$PATH` before you start npm?!

**Comment by mzgol** [comment]
@aredridel 
"/Users/mgol/.nvm/versions/node/v4.1.2/bin:/Users/mgol/Documents/projects/public/v8-tools/depot_tools:/Users/mgol/bin:/Users/mgol/.cabal/bin:/usr/local/heroku/bin:/usr/local/bin:/usr/local/sbin:/Applications/CrossOver.app/Contents/SharedSupport/CrossOver/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/TeX/texbin:./node_modules/.bin:/usr/local/opt/dart/libexec/bin"

**Comment by mzgol** [comment]
At the end of `npm-debug.log` I see that `PATH` grows to 327696 characters, though. O_o
You can see it in this gist, it was too long for a GitHub comment (it has a limit at 262144 characters):
https://gist.github.com/mzgol/aedc2834b01b96af4237

**Comment by iarna** [comment]
The PR that caused this has been reverted and 3.3.8 has been released. We'll revisit the issue w/ the module that was being added. Thank you for this this thorough report!
