### ISSUE TITLE
Unable to publish scoped packages

### ISSUE THREAD

**Issue by mstade** [npm/npm#9923]
Whenever I try to publish a package to a scope, I get an error (after some time.) I've scoured the issues and found #6446, #6669, and #8059. I've tried removing `~/.npmrc` and logging in multiple times, as well as random scope names to try and determine whether it's because someone else took the name I'd like. I can publish unscoped packages successfully, but every time I try to publish a scoped package, I get a 500 followed by a 404, according to the log. Here's the log in its entirety, when trying to publish a package to a random scope name (to rule out name collisions.)

```bash
0 info it worked if it ends with ok
1 verbose cli [ '/Users/mstade/.nvm/versions/node/v4.0.0/bin/node',
1 verbose cli   '/Users/mstade/.nvm/versions/node/v4.0.0/bin/npm',
1 verbose cli   'publish',
1 verbose cli   '--access=public' ]
2 info using npm@2.14.2
3 info using node@v4.0.0
4 verbose publish [ '.' ]
5 silly cache add args [ '.', null ]
6 verbose cache add spec .
7 silly cache add parsed spec Result {
7 silly cache add   raw: '.',
7 silly cache add   scope: null,
7 silly cache add   name: null,
7 silly cache add   rawSpec: '.',
7 silly cache add   spec: '/Users/mstade/dev/websdk/nap',
7 silly cache add   type: 'directory' }
8 verbose addLocalDirectory /Users/mstade/.npm/@ad23f8e4b36541d1ae3894e011545cfe/nap/0.9.1/package.tgz not in flight; packing
9 verbose tar pack [ '/Users/mstade/.npm/@ad23f8e4b36541d1ae3894e011545cfe/nap/0.9.1/package.tgz',
9 verbose tar pack   '/Users/mstade/dev/websdk/nap' ]
10 verbose tarball /Users/mstade/.npm/@ad23f8e4b36541d1ae3894e011545cfe/nap/0.9.1/package.tgz
11 verbose folder /Users/mstade/dev/websdk/nap
12 info prepublish @ad23f8e4b36541d1ae3894e011545cfe/nap@0.9.1
13 verbose addLocalTarball adding from inside cache /Users/mstade/.npm/@ad23f8e4b36541d1ae3894e011545cfe/nap/0.9.1/package.tgz
14 silly cache afterAdd @ad23f8e4b36541d1ae3894e011545cfe/nap@0.9.1
15 verbose afterAdd /Users/mstade/.npm/@ad23f8e4b36541d1ae3894e011545cfe/nap/0.9.1/package/package.json not in flight; writing
16 verbose afterAdd /Users/mstade/.npm/@ad23f8e4b36541d1ae3894e011545cfe/nap/0.9.1/package/package.json written
17 silly publish { name: '@ad23f8e4b36541d1ae3894e011545cfe/nap',
17 silly publish   version: '0.9.1',
17 silly publish   description: 'Organizing applications into resources',
17 silly publish   main: 'lib/nap.js',
17 silly publish   devDependencies:
17 silly publish    { babel: '^5.8.23',
17 silly publish      browserify: '^11.2.0',
17 silly publish      chai: '^1.9.1',
17 silly publish      d3: '^3.5.6',
17 silly publish      mocha: '^1.21.4',
17 silly publish      sinon: '^1.10.3',
17 silly publish      'sinon-chai': '^2.5.0',
17 silly publish      uglifyjs: '^2.4.10' },
17 silly publish   scripts: { test: 'make test', preversion: 'make all' },
17 silly publish   dependencies: { rhumb: '^0.3.1' },
17 silly publish   repository: { type: 'git', url: 'git+https://github.com/sammyt/nap.git' },
17 silly publish   author:
17 silly publish    { name: 'Samuel Williams',
17 silly publish      email: 'sam@ziazoo.co.uk',
17 silly publish      url: 'http://www.ziazoo.co.uk' },
17 silly publish   contributors:
17 silly publish    [ { name: 'Marcus Stade',
17 silly publish        email: 'marcus@stade.se',
17 silly publish        url: 'http://madebystade.se' } ],
17 silly publish   license: 'MIT',
17 silly publish   bugs: { url: 'https://github.com/sammyt/nap/issues' },
17 silly publish   homepage: 'https://github.com/sammyt/nap#readme',
17 silly publish   readme: 'nap\n===\n\nREST for the client\n\nDeveloping\n----------\n\n```\nbower install\nopen test/index.html\n```\n\n\nLicense\n-------\n\nLicense: http://sammyt.mit-license.org\n',
17 silly publish   readmeFilename: 'README.md',
17 silly publish   gitHead: 'fbde70185b4c413a401f78e9ef46b0dccf126e8e',
17 silly publish   _id: '@ad23f8e4b36541d1ae3894e011545cfe/nap@0.9.1',
17 silly publish   _shasum: 'f47c179109f1a4c9c2c92a6c2558208b6dac0d80',
17 silly publish   _from: '.' }
18 verbose getPublishConfig undefined
19 silly mapToRegistry name @ad23f8e4b36541d1ae3894e011545cfe/nap
20 silly mapToRegistry scope (from package name) @ad23f8e4b36541d1ae3894e011545cfe
21 verbose mapToRegistry no registry URL found in name for scope @ad23f8e4b36541d1ae3894e011545cfe
22 silly mapToRegistry using default registry
23 silly mapToRegistry registry https://registry.npmjs.org/
24 silly mapToRegistry uri https://registry.npmjs.org/@ad23f8e4b36541d1ae3894e011545cfe%2fnap
25 verbose publish registryBase https://registry.npmjs.org/
26 silly publish uploading /Users/mstade/.npm/@ad23f8e4b36541d1ae3894e011545cfe/nap/0.9.1/package.tgz
27 verbose request uri https://registry.npmjs.org/@ad23f8e4b36541d1ae3894e011545cfe%2fnap
28 verbose request sending authorization for write operation
29 info attempt registry request try #1 at 4:57:15 PM
30 verbose request using bearer token for auth
31 verbose request id f703a4b8f64fc529
32 http request PUT https://registry.npmjs.org/@ad23f8e4b36541d1ae3894e011545cfe%2fnap
33 http 500 https://registry.npmjs.org/@ad23f8e4b36541d1ae3894e011545cfe%2fnap
34 info retry will retry, error on last attempt: Error: unexpected status code: 404 : @ad23f8e4b36541d1ae3894e011545cfe/nap
35 info attempt registry request try #2 at 4:57:28 PM
36 verbose request using bearer token for auth
37 http request PUT https://registry.npmjs.org/@ad23f8e4b36541d1ae3894e011545cfe%2fnap
38 http 500 https://registry.npmjs.org/@ad23f8e4b36541d1ae3894e011545cfe%2fnap
39 info retry will retry, error on last attempt: Error: unexpected status code: 404 : @ad23f8e4b36541d1ae3894e011545cfe/nap
40 info attempt registry request try #3 at 4:58:29 PM
41 verbose request using bearer token for auth
42 http request PUT https://registry.npmjs.org/@ad23f8e4b36541d1ae3894e011545cfe%2fnap
43 http 500 https://registry.npmjs.org/@ad23f8e4b36541d1ae3894e011545cfe%2fnap
44 verbose headers { 'content-type': 'application/json',
44 verbose headers   'cache-control': 'max-age=0',
44 verbose headers   'content-length': '39',
44 verbose headers   'accept-ranges': 'bytes',
44 verbose headers   date: 'Fri, 09 Oct 2015 14:58:31 GMT',
44 verbose headers   via: '1.1 varnish',
44 verbose headers   connection: 'keep-alive',
44 verbose headers   'x-served-by': 'cache-fra1247-FRA',
44 verbose headers   'x-cache': 'MISS',
44 verbose headers   'x-cache-hits': '0',
44 verbose headers   'x-timer': 'S1444402710.595339,VS0,VE1087' }
45 verbose request invalidating /Users/mstade/.npm/registry.npmjs.org/_40ad23f8e4b36541d1ae3894e011545cfe_252fnap on PUT
46 error publish Failed PUT 500
47 verbose stack Error: unexpected status code: 404 : @ad23f8e4b36541d1ae3894e011545cfe/nap
47 verbose stack     at makeError (/Users/mstade/.nvm/versions/node/v4.0.0/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:263:12)
47 verbose stack     at CachingRegistryClient.<anonymous> (/Users/mstade/.nvm/versions/node/v4.0.0/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:251:14)
47 verbose stack     at Request._callback (/Users/mstade/.nvm/versions/node/v4.0.0/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:171:14)
47 verbose stack     at Request.self.callback (/Users/mstade/.nvm/versions/node/v4.0.0/lib/node_modules/npm/node_modules/request/request.js:198:22)
47 verbose stack     at emitTwo (events.js:87:13)
47 verbose stack     at Request.emit (events.js:172:7)
47 verbose stack     at Request.<anonymous> (/Users/mstade/.nvm/versions/node/v4.0.0/lib/node_modules/npm/node_modules/request/request.js:1073:14)
47 verbose stack     at emitOne (events.js:82:20)
47 verbose stack     at Request.emit (events.js:169:7)
47 verbose stack     at IncomingMessage.<anonymous> (/Users/mstade/.nvm/versions/node/v4.0.0/lib/node_modules/npm/node_modules/request/request.js:1019:12)
48 verbose statusCode 500
49 verbose pkgid @ad23f8e4b36541d1ae3894e011545cfe/nap
50 verbose cwd /Users/mstade/dev/websdk/nap
51 error Darwin 15.0.0
52 error argv "/Users/mstade/.nvm/versions/node/v4.0.0/bin/node" "/Users/mstade/.nvm/versions/node/v4.0.0/bin/npm" "publish" "--access=public"
53 error node v4.0.0
54 error npm  v2.14.2
55 error code E500
56 error unexpected status code: 404 : @ad23f8e4b36541d1ae3894e011545cfe/nap
57 error If you need help, you may report this error at:
57 error     <https://github.com/npm/npm/issues>
58 verbose exit [ 1, true ]
```

Any help is most appreciated!

**Comment by othiym23** [comment]
You can only publish to the scopes to which you have access, which by default is the scope that corresponds to your username. Do you still have problems if you publish to `@mstade/nap`?

**Comment by mstade** [comment]
Ah, that explains it – publishing to `@mstade/nap` works fine. How can I register a scope that isn't my username then?

**Comment by othiym23** [comment]
You can:

1. Create a new username for the desired scope (now) or
2. Create an organization with the desired scope name, or get the owner of an organization with the desired scope name to add you to one of its teams with publish privileges for the organization (the reasonably near future)

**Comment by mstade** [comment]
Right, so organizations aren't available now, but I can "squat" the name by registering a new user for it? Can I then, when orgs are available, convert that user into an organization?

**Comment by othiym23** [comment]
Yes, that's the plan!

**Comment by mstade** [comment]
Lovely, thanks @othiym23! :o)
