### ISSUE TITLE
Unable to login / publish

### ISSUE THREAD

**Issue by dysfunc** [npm/npm#9926]
Username: (dysfunc)
Email: (this IS public) (norcal.kieran@gmail.com)
npm http PUT http://registry.npmjs.org/-/user/org.couchdb.user:dysfunc
npm http 400 http://registry.npmjs.org/-/user/org.couchdb.user:dysfunc
npm ERR! Error: Unknown error while authenticating : -/user/org.couchdb.user:dysfunc
npm ERR!     at RegClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:237:14)
npm ERR!     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:123:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:893:14)
npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:844:12)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

**Comment by dysfunc** [comment]
I tried publishing several times and I receive a 500 error. I figured my login might have been stale so I tried auth'ing again and I receive the error above.

**Comment by KenanY** [comment]
@dysfunc `npm --version`?

**Comment by dysfunc** [comment]
1.4.3

**Comment by KenanY** [comment]
@dysfunc Does this also occur if you [upgrade](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) to the latest stable release of `npm`?

**Comment by dysfunc** [comment]
upgrading fixed the issue. thanks :+1:

**Comment by kevinSuttle** [comment]
```bash
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/4.2.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'login' ]
2 info using npm@3.3.6
3 info using node@v4.2.0
4 verbose config Skipping project config: /Users/kevinSuttle/.npmrc. (matches userconfig)
5 verbose adduser before first PUT { _id: 'org.couchdb.user:kevinsuttle',
5 verbose adduser   name: 'kevinsuttle',
5 verbose adduser   password: 'XXXXX',
5 verbose adduser   email: 'kevin@suttle.email',
5 verbose adduser   type: 'user',
5 verbose adduser   roles: [],
5 verbose adduser   date: '2015-10-14T19:57:01.197Z' }
6 verbose request uri https://registry.npmjs.org/-/user/org.couchdb.user:kevinsuttle
7 verbose request new user, so can't send auth
8 info attempt registry request try #1 at 3:57:01 PM
9 verbose request id 2467d1f4cd5bb743
10 http request PUT https://registry.npmjs.org/-/user/org.couchdb.user:kevinsuttle
11 http 400 https://registry.npmjs.org/-/user/org.couchdb.user:kevinsuttle
12 verbose headers { 'content-type': 'application/json',
12 verbose headers   'cache-control': 'max-age=60',
12 verbose headers   'content-length': '57',
12 verbose headers   'accept-ranges': 'bytes',
12 verbose headers   date: 'Wed, 14 Oct 2015 19:57:02 GMT',
12 verbose headers   via: '1.1 varnish',
12 verbose headers   connection: 'keep-alive',
12 verbose headers   'x-served-by': 'cache-ord1730-ORD',
12 verbose headers   'x-cache': 'MISS',
12 verbose headers   'x-cache-hits': '0',
12 verbose headers   'x-timer': 'S1444852621.606114,VS0,VE476' }
13 verbose request invalidating /Users/kevinSuttle/.npm/registry.npmjs.org/-/user/org.couchdb.user_3Akevinsuttle on PUT
14 verbose adduser back [ { [Error: Unknown error while authenticating : -/user/org.couchdb.user:kevinsuttle] statusCode: 400, code: 'E400' },
14 verbose adduser   { ok: false, error: 'Unknown error while authenticating' },
14 verbose adduser   '{"ok":false,"error":"Unknown error while authenticating"}' ]
15 verbose stack Error: Unknown error while authenticating : -/user/org.couchdb.user:kevinsuttle
15 verbose stack     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
15 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:252:14)
15 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
15 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:198:22)
15 verbose stack     at emitTwo (events.js:87:13)
15 verbose stack     at Request.emit (events.js:172:7)
15 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1063:14)
15 verbose stack     at emitOne (events.js:82:20)
15 verbose stack     at Request.emit (events.js:169:7)
15 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1009:12)
16 verbose statusCode 400
17 verbose cwd /Users/kevinSuttle
18 error Darwin 15.0.0
19 error argv "/usr/local/Cellar/node/4.2.0/bin/node" "/usr/local/bin/npm" "login"
20 error node v4.2.0
21 error npm  v3.3.6
22 error code E400
23 error Unknown error while authenticating : -/user/org.couchdb.user:kevinsuttle
24 error If you need help, you may report this error at:
24 error     <https://github.com/npm/npm/issues>
25 verbose exit [ 1, true ]
 ```

```bash
~
 ❯ npm -v
3.3.6

~
 ❯ node -v
v4.2.0
```

**Comment by kevinSuttle** [comment]
Also, strangely, I don't have an `~/.npmrc` file (just clean installed El Capitan).

**Comment by kevinSuttle** [comment]
```bash
❯ npm adduser
Username: kevinsuttle
Password:
Email: (this IS public) kevin@suttle.email
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/Cellar/node/4.2.0/bin/node" "/usr/local/bin/npm" "adduser"
npm ERR! node v4.2.0
npm ERR! npm  v3.3.6
npm ERR! code E400

npm ERR! Unknown error while authenticating : -/user/org.couchdb.user:kevinsuttle
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kevinSuttle/npm-debug.log

~
 ❯ cat ~/npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/4.2.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'adduser' ]
2 info using npm@3.3.6
3 info using node@v4.2.0
4 verbose config Skipping project config: /Users/kevinSuttle/.npmrc. (matches userconfig)
5 verbose adduser before first PUT { _id: 'org.couchdb.user:kevinsuttle',
5 verbose adduser   name: 'kevinsuttle',
5 verbose adduser   password: 'XXXXX',
5 verbose adduser   email: 'kevin@suttle.email',
5 verbose adduser   type: 'user',
5 verbose adduser   roles: [],
5 verbose adduser   date: '2015-10-14T20:49:50.240Z' }
6 verbose request uri https://registry.npmjs.org/-/user/org.couchdb.user:kevinsuttle
7 verbose request new user, so can't send auth
8 info attempt registry request try #1 at 4:49:50 PM
9 verbose request id d0feca3d027a04bf
10 http request PUT https://registry.npmjs.org/-/user/org.couchdb.user:kevinsuttle
11 http 400 https://registry.npmjs.org/-/user/org.couchdb.user:kevinsuttle
12 verbose headers { 'content-type': 'application/json',
12 verbose headers   'cache-control': 'max-age=60',
12 verbose headers   'content-length': '57',
12 verbose headers   'accept-ranges': 'bytes',
12 verbose headers   date: 'Wed, 14 Oct 2015 20:49:50 GMT',
12 verbose headers   via: '1.1 varnish',
12 verbose headers   connection: 'keep-alive',
12 verbose headers   'x-served-by': 'cache-ord1734-ORD',
12 verbose headers   'x-cache': 'MISS',
12 verbose headers   'x-cache-hits': '0',
12 verbose headers   'x-timer': 'S1444855790.370377,VS0,VE596' }
13 verbose request invalidating /Users/kevinSuttle/.npm/registry.npmjs.org/-/user/org.couchdb.user_3Akevinsuttle on PUT
14 verbose adduser back [ { [Error: Unknown error while authenticating : -/user/org.couchdb.user:kevinsuttle] statusCode: 400, code: 'E400' },
14 verbose adduser   { ok: false, error: 'Unknown error while authenticating' },
14 verbose adduser   '{"ok":false,"error":"Unknown error while authenticating"}' ]
15 verbose stack Error: Unknown error while authenticating : -/user/org.couchdb.user:kevinsuttle
15 verbose stack     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
15 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:252:14)
15 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
15 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:198:22)
15 verbose stack     at emitTwo (events.js:87:13)
15 verbose stack     at Request.emit (events.js:172:7)
15 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1063:14)
15 verbose stack     at emitOne (events.js:82:20)
15 verbose stack     at Request.emit (events.js:169:7)
15 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1009:12)
16 verbose statusCode 400
17 verbose cwd /Users/kevinSuttle
18 error Darwin 15.0.0
19 error argv "/usr/local/Cellar/node/4.2.0/bin/node" "/usr/local/bin/npm" "adduser"
20 error node v4.2.0
21 error npm  v3.3.6
22 error code E400
23 error Unknown error while authenticating : -/user/org.couchdb.user:kevinsuttle
24 error If you need help, you may report this error at:
24 error     <https://github.com/npm/npm/issues>
25 verbose exit [ 1, true ]
```

**Comment by kevinSuttle** [comment]
I wonder if it's my email address...

**Comment by kevinSuttle** [comment]
Nope. It's the fact that I entered my password as all lowercase. The UX around this could be better. Since username and email have to be lowercase, I assumed so did my password. I wouldn't have even guessed that the password was the issue unless @snopeks hadn't suggested it.

**Comment by snopeks** [comment]
@kevinSuttle Glad the issue has been resolved! It was a team effort on our end :) We appreciate your feedback on the user experience, & we'll be looking at ways to improve this in the future. Thanks!
