### ISSUE TITLE
E400 npm ERR! Unknown error while authenticating

### ISSUE THREAD

**Issue by jdorfman** [npm/npm#9931]
Can't authenticate even after `sudo npm install -g npm@latest`
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'adduser' ]
2 info using npm@3.3.6
3 info using node@v4.1.2
4 verbose adduser before first PUT { _id: 'org.couchdb.user:jdorfman',
4 verbose adduser   name: 'jdorfman',
4 verbose adduser   password: 'XXXXX',
4 verbose adduser   email: 'justindorfman@****.com',
4 verbose adduser   type: 'user',
4 verbose adduser   roles: [],
4 verbose adduser   date: '2015-10-10T04:49:39.698Z' }
5 verbose request uri https://registry.npmjs.org/-/user/org.couchdb.user:jdorfman
6 verbose request new user, so can't send auth
7 info attempt registry request try #1 at 9:49:39 PM
8 verbose request id 48202abfdcaaceac
9 http request PUT https://registry.npmjs.org/-/user/org.couchdb.user:jdorfman
10 http 400 https://registry.npmjs.org/-/user/org.couchdb.user:jdorfman
11 verbose headers { 'content-type': 'application/json',
11 verbose headers   'cache-control': 'max-age=60',
11 verbose headers   'content-length': '57',
11 verbose headers   'accept-ranges': 'bytes',
11 verbose headers   date: 'Sat, 10 Oct 2015 04:49:41 GMT',
11 verbose headers   via: '1.1 varnish',
11 verbose headers   connection: 'keep-alive',
11 verbose headers   'x-served-by': 'cache-sjc3127-SJC',
11 verbose headers   'x-cache': 'MISS',
11 verbose headers   'x-cache-hits': '0',
11 verbose headers   'x-timer': 'S1444452581.407828,VS0,VE171' }
12 verbose request invalidating /Users/jdorfman/.npm/registry.npmjs.org/-/user/org.couchdb.user_3Ajdorfman on PUT
13 verbose adduser back [ { [Error: Unknown error while authenticating : -/user/org.couchdb.user:jdorfman] statusCode: 400, code: 'E400' },
13 verbose adduser   { ok: false, error: 'Unknown error while authenticating' },
13 verbose adduser   '{"ok":false,"error":"Unknown error while authenticating"}' ]
14 verbose stack Error: Unknown error while authenticating : -/user/org.couchdb.user:jdorfman
14 verbose stack     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
14 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:252:14)
14 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
14 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:198:22)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at Request.emit (events.js:172:7)
14 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1063:14)
14 verbose stack     at emitOne (events.js:82:20)
14 verbose stack     at Request.emit (events.js:169:7)
14 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1009:12)
15 verbose statusCode 400
16 verbose cwd /Users/jdorfman/github/maxcdn/shml
17 error Darwin 14.5.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "adduser"
19 error node v4.1.2
20 error npm  v3.3.6
21 error code E400
22 error Unknown error while authenticating : -/user/org.couchdb.user:jdorfman
23 error If you need help, you may report this error at:
23 error     <https://github.com/npm/npm/issues>
24 verbose exit [ 1, true ]
```

**Comment by haf** [comment]
Same here when trying to publish a package:

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/h/.nvm/versions/node/v5.0.0/bin/node',
1 verbose cli   '/Users/h/.nvm/versions/node/v5.0.0/bin/npm',
1 verbose cli   'adduser' ]
2 info using npm@3.3.12
3 info using node@v5.0.0
4 verbose adduser before first PUT { _id: 'org.couchdb.user:haf',
4 verbose adduser   name: 'haf',
4 verbose adduser   password: 'XXXXX',
4 verbose adduser   email: 'henrik@XXXXX.se',
4 verbose adduser   type: 'user',
4 verbose adduser   roles: [],
4 verbose adduser   date: '2015-11-04T15:26:38.540Z' }
5 verbose request uri https://registry.npmjs.org/-/user/org.couchdb.user:haf
6 verbose request new user, so can't send auth
7 info attempt registry request try #1 at 4:26:38 PM
8 verbose request id b6fc1dd5804723b0
9 http request PUT https://registry.npmjs.org/-/user/org.couchdb.user:haf
10 http 400 https://registry.npmjs.org/-/user/org.couchdb.user:haf
11 verbose headers { 'content-type': 'application/json',
11 verbose headers   'cache-control': 'max-age=60',
11 verbose headers   'content-length': '57',
11 verbose headers   'accept-ranges': 'bytes',
11 verbose headers   date: 'Wed, 04 Nov 2015 15:26:40 GMT',
11 verbose headers   via: '1.1 varnish',
11 verbose headers   connection: 'keep-alive',
11 verbose headers   'x-served-by': 'cache-fra1242-FRA',
11 verbose headers   'x-cache': 'MISS',
11 verbose headers   'x-cache-hits': '0',
11 verbose headers   'x-timer': 'S1446650799.622465,VS0,VE764' }
12 verbose request invalidating /Users/h/.npm/registry.npmjs.org/-/user/org.couchdb.user_3Ahaf on PUT
13 verbose adduser back [ { [Error: Unknown error while authenticating : -/user/org.couchdb.user:haf] statusCode: 400, code: 'E400' },
13 verbose adduser   { ok: false, error: 'Unknown error while authenticating' },
13 verbose adduser   '{"ok":false,"error":"Unknown error while authenticating"}' ]
14 verbose stack Error: Unknown error while authenticating : -/user/org.couchdb.user:haf
14 verbose stack     at makeError (/Users/h/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
14 verbose stack     at CachingRegistryClient.<anonymous> (/Users/h/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:252:14)
14 verbose stack     at Request._callback (/Users/h/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
14 verbose stack     at Request.self.callback (/Users/h/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/request/request.js:198:22)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at Request.emit (events.js:172:7)
14 verbose stack     at Request.<anonymous> (/Users/h/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/request/request.js:1082:10)
14 verbose stack     at emitOne (events.js:82:20)
14 verbose stack     at Request.emit (events.js:169:7)
14 verbose stack     at IncomingMessage.<anonymous> (/Users/h/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/request/request.js:1009:12)
15 verbose statusCode 400
16 verbose cwd /Users/h/dev/haf/logary-js
17 error Darwin 14.5.0
18 error argv "/Users/h/.nvm/versions/node/v5.0.0/bin/node" "/Users/h/.nvm/versions/node/v5.0.0/bin/npm" "adduser"
19 error node v5.0.0
20 error npm  v3.3.12
21 error code E400
22 error Unknown error while authenticating : -/user/org.couchdb.user:haf
23 error If you need help, you may report this error at:
23 error     <https://github.com/npm/npm/issues>
24 verbose exit [ 1, true ]

```

**Comment by ehsalazar** [comment]
@jdorfman Is this an ongoing issue for you? If so, are you able to log into npmjs.com with your username and password?

**Comment by jdorfman** [comment]
@ehsalazar I haven't tried since.  I will (hopefully) try this weekend.  You can close this issue for now.

Thanks!

**Comment by ehsalazar** [comment]
@jdorfman Thanks. If you run into issues logging into the website, please don't hesitate to reach out to us.
- support@npmjs.com 

We'll be happy to help.

**Comment by jdorfman** [comment]
@ehsalazar  noted =)

**Comment by ehsalazar** [comment]
@haf I tried to reply to the ticket you sent into support but received:
```
Undelivered Mail Returned to Sender
I'm sorry to have to inform you that your message could not be delivered to one or more recipients.
```
If it did make it to you, could you reply back? Thanks!

**Comment by haf** [comment]
@ehsalazar I haven't received your reply, but I have verified my e-mail does work. Could please retry?

**Comment by kucherenkovova** [comment]
I'm facing the same issue. Are there any workarounds by this time?

**Comment by serbanghita** [comment]
I'm on Windows 10 too:

`user-agent = "npm/2.14.12 node/v4.3.1 win32 x64"`

```
$ npm login
Username: serbanghita
Password: *************
Email: (this IS public) serbanghita@gmail.com
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "login"
npm ERR! node v4.3.1
npm ERR! npm  v2.14.12
npm ERR! code E400

npm ERR! Unknown error while authenticating : -/user/org.couchdb.user:serbanghita
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```
