### ISSUE TITLE
error 'undefined' == 'string' and npm ERR! 404 Registry returned 404

### ISSUE THREAD

**Issue by Flauschie** [npm/npm#9936]
Updated nodejs from v0.12.2 to v4.1.2 because I always received the following error while trying to use npm 3.3.6 (sudo npm install -g n) with nodejs v0.12.2.

This error already shows v.4.1.2 because I forgot to snap the error with the old version.
```
sudo npm update
npm ERR! Linux 3.2.0-4-amd64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "update"
npm ERR! node v4.1.2
npm ERR! npm  v2.14.4
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/ep_etherpad-lite
npm ERR! 404
npm ERR! 404 'ep_etherpad-lite' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/share/nginx/www/etherpad-lite/node_modules/npm-debug.log
```

But the error still exists. After some googling without any results I decided to update nodejs, too. Now running nodejs 4.1.2 (sudo npm install npm -g)

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'update' ]
2 info using npm@3.3.6
3 info using node@v4.1.2
4 silly mapToRegistry name undefined
5 verbose stack AssertionError: 'undefined' == 'string'
5 verbose stack     at npa (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:40:10)
5 verbose stack     at mapToRegistry (/usr/local/lib/node_modules/npm/lib/utils/map-to-registry.js:13:14)
5 verbose stack     at shouldUpdate (/usr/local/lib/node_modules/npm/lib/outdated.js:340:3)
5 verbose stack     at /usr/local/lib/node_modules/npm/lib/outdated.js:301:23
5 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
5 verbose stack     at Array.forEach (native)
5 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
5 verbose stack     at Array.forEach (native)
5 verbose stack     at asyncMap (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
5 verbose stack     at outdated_ (/usr/local/lib/node_modules/npm/lib/outdated.js:294:3)
6 verbose cwd /usr/share/nginx/www/etherpad-lite/node_modules
7 error Linux 3.2.0-4-amd64
8 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "update"
9 error node v4.1.2
10 error npm  v3.3.6
11 error 'undefined' == 'string'
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]
```

**Comment by Flauschie** [comment]
Reverted back to npm 2.13.3 and node 0.12.7 ... I read that there are some compiling issues on debian wheezy. Update via node/npm itself isn't is a problem, but causes problems later on...
