### ISSUE TITLE
npm broken after interrupted "npm update -g"

### ISSUE THREAD

**Issue by rgh36167** [npm/npm#9940]
I had just one package - mozilla "jpm" which I wanted update. Because it was taking a long time it was interrupted.

Now npm errors out regradless of the command it is given, eg
``` npm update -g

module.js:340
    throw err;
          ^
Error: Cannot find module 'ansi'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/lib/node_modules/npmlog/log.js:5:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```
Originally it was npm-1.3.6-6.fc21 from Fedora.

**Comment by KenanY** [comment]
@rgh36167 You could try [repairing](https://github.com/npm/npm/wiki/Troubleshooting#if-your-npm-is-broken) it.

**Comment by paulath** [comment]
I had the same issue, I solved this by reinstalling npm and not updating to the nearest version, it seems for me version 3.3.6 doesn't run 

paul@paul-ubuntu:~/Documents$ sudo npm install npm -g
/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
npm@3.3.6 /usr/local/lib/node_modules/npm
paul@paul-ubuntu:~/Documents$ npm -v
module.js:339
    throw err;
*snip*

**Comment by rgh36167** [comment]
on Fedora I had to
 # yum remove nodejs
 # rm -rf rm -rf /usr/lib/node_modules/

and reinstall
 # yum install npm

**Comment by ehsalazar** [comment]
@rgh36167 It sounds like you were able to get up and running. I'll close this for now as we’re trying to clean up some solved issues. We’ll be happy to reopen if necessary.
