### ISSUE TITLE
npm shrinkwrap issue

### ISSUE THREAD

**Issue by zhdzmn** [npm/npm#9951]
```
npm shrinkwrap --deve
npm info it worked if it ends with ok
npm info using npm@1.4.28
npm info using node@v0.10.40
^Czahid@zahid-sys76:~/apps/marketingplatform$ npm shrinkwrap --dev
npm info it worked if it ends with ok
npm info using npm@1.4.28
npm info using node@v0.10.40
npm WARN unmet dependency /home/zahid/apps/marketingplatform/node_modules/express3-handlebars requires async@'~0.2' but will load
npm WARN unmet dependency /home/zahid/apps/marketingplatform/node_modules/async,
npm WARN unmet dependency which is version 1.4.2
npm WARN unmet dependency /home/zahid/apps/marketingplatform/node_modules/hipchatter requires async@'~0.2.9' but will load
npm WARN unmet dependency /home/zahid/apps/marketingplatform/node_modules/async,
npm WARN unmet dependency which is version 1.4.2
npm WARN unmet dependency /home/zahid/apps/marketingplatform/node_modules/winston requires async@'0.2.x' but will load
npm WARN unmet dependency /home/zahid/apps/marketingplatform/node_modules/async,
npm WARN unmet dependency which is version 1.4.2
npm WARN unmet dependency /home/zahid/apps/marketingplatform/node_modules/winston/node_modules/request/node_modules/form-data requires async@'~0.2.7' but will load
npm WARN unmet dependency /home/zahid/apps/marketingplatform/node_modules/async,
npm WARN unmet dependency which is version 1.4.2
npm WARN unmet dependency /home/zahid/apps/marketingplatform/node_modules/express3-handlebars/node_modules/handlebars/node_modules/uglify-js requires async@'~0.2.6' but will load
npm WARN unmet dependency /home/zahid/apps/marketingplatform/node_modules/async,
npm WARN unmet dependency which is version 1.4.2
npm WARN unmet dependency /home/zahid/apps/marketingplatform/node_modules/handlebars/node_modules/uglify-js requires async@'~0.2.6' but will load
npm WARN unmet dependency /home/zahid/apps/marketingplatform/node_modules/async,
npm WARN unmet dependency which is version 1.4.2
npm WARN unmet dependency /home/zahid/apps/marketingplatform/node_modules/kue/node_modules/jade/node_modules/with/node_modules/uglify-js requires async@'~0.2.6' but will load
npm WARN unmet dependency /home/zahid/apps/marketingplatform/node_modules/async,
npm WARN unmet dependency which is version 1.4.2
npm WARN unmet dependency /home/zahid/apps/marketingplatform/node_modules/kue/node_modules/jade/node_modules/constantinople/node_modules/uglify-js requires async@'~0.2.6' but will load
npm WARN unmet dependency /home/zahid/apps/marketingplatform/node_modules/async,
npm WARN unmet dependency which is version 1.4.2
npm WARN unmet dependency /home/zahid/apps/marketingplatform/node_modules/grunt-contrib-imagemin/node_modules/jpegtran-bin/node_modules/request/node_modules/form-data requires async@'~0.2.7' but will load
npm WARN unmet dependency /home/zahid/apps/marketingplatform/node_modules/async,
npm WARN unmet dependency which is version 1.4.2
npm WARN unmet dependency /home/zahid/apps/marketingplatform/node_modules/grunt-contrib-imagemin/node_modules/optipng-bin/node_modules/request/node_modules/form-data requires async@'~0.2.7' but will load
npm WARN unmet dependency /home/zahid/apps/marketingplatform/node_modules/async,
npm WARN unmet dependency which is version 1.4.2
npm WARN unmet dependency /home/zahid/apps/marketingplatform/node_modules/grunt-contrib-uglify/node_modules/uglify-js requires async@'~0.2.6' but will load
npm WARN unmet dependency /home/zahid/apps/marketingplatform/node_modules/async,
npm WARN unmet dependency which is version 1.4.2
npm WARN unmet dependency /home/zahid/apps/marketingplatform/node_modules/karma/node_modules/log4js requires async@'~0.2.0' but will load
npm WARN unmet dependency /home/zahid/apps/marketingplatform/node_modules/async,
npm WARN unmet dependency which is version 1.4.2
npm ERR! Error: Problems were encountered
npm ERR! Please correct and try again.
npm ERR! invalid: async@1.4.2 /home/zahid/apps/marketingplatform/node_modules/async
npm ERR!     at shrinkwrap_ (/home/zahid/.nvm/v0.10.40/lib/node_modules/npm/lib/shrinkwrap.js:30:15)
npm ERR!     at /home/zahid/.nvm/v0.10.40/lib/node_modules/npm/lib/shrinkwrap.js:24:5
npm ERR!     at /home/zahid/.nvm/v0.10.40/lib/node_modules/npm/lib/ls.js:45:30
npm ERR!     at /home/zahid/.nvm/v0.10.40/lib/node_modules/npm/node_modules/read-installed/read-installed.js:130:5
npm ERR!     at /home/zahid/.nvm/v0.10.40/lib/node_modules/npm/node_modules/read-installed/read-installed.js:244:14
npm ERR!     at cb (/home/zahid/.nvm/v0.10.40/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
npm ERR!     at /home/zahid/.nvm/v0.10.40/lib/node_modules/npm/node_modules/read-installed/read-installed.js:244:14
npm ERR!     at cb (/home/zahid/.nvm/v0.10.40/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
npm ERR!     at /home/zahid/.nvm/v0.10.40/lib/node_modules/npm/node_modules/read-installed/read-installed.js:244:14
npm ERR!     at cb (/home/zahid/.nvm/v0.10.40/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.19.0-30-generic
npm ERR! command "/home/zahid/.nvm/v0.10.40/bin/node" "/home/zahid/.nvm/v0.10.40/bin/npm" "shrinkwrap" "--dev"
npm ERR! cwd /home/zahid/apps/marketingplatform
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/zahid/apps/marketingplatform/npm-debug.log
npm ERR! not ok code 0
```

**Comment by zhdzmn** [comment]
any idea how to resolve the issue ? cannot do the `shrinwrap`

**Comment by markstos** [comment]
I recommend closing this issue, as no specific bug has been reported.

**Comment by snopeks** [comment]
Hi @zhdzmn can you try [upgrading](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm) your version of npm and see if that solves the issue?
