### ISSUE TITLE
`npm install` fails on mac os x

### ISSUE THREAD

**Issue by pathakNishant** [npm/npm#9985]
```
node-stringprep@0.7.2 install /Users/nishant.pathak/projects/chatclient-web/node_modules/stanza.io/node_modules/xmpp-jid/node_modules/node-stringprep
> node-gyp rebuild

  SOLINK_MODULE(target) Release/node_stringprep.node
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/node_stringprep.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/nishant.pathak/.nvm/versions/node/v4.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/Users/nishant.pathak/.nvm/versions/node/v4.0.0/bin/node" "/Users/nishant.pathak/.nvm/versions/node/v4.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/nishant.pathak/projects/chatclient-web/node_modules/stanza.io/node_modules/xmpp-jid/node_modules/node-stringprep
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok 
-
> iconv@2.1.11 install /Users/nishant.pathak/projects/chatclient-web/node_modules/jxt/node_modules/ltx/node_modules/node-expat/node_modules/iconv
> node-gyp rebuild

  CC(target) Release/obj.target/libiconv/deps/libiconv/lib/iconv.o
  LIBTOOL-STATIC Release/iconv.a
  CXX(target) Release/obj.target/iconv/src/binding.o
  SOLINK_MODULE(target) Release/iconv.node
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/iconv.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/nishant.pathak/.nvm/versions/node/v4.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/Users/nishant.pathak/.nvm/versions/node/v4.0.0/bin/node" "/Users/nishant.pathak/.nvm/versions/node/v4.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
```

**Comment by othiym23** [comment]
```
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Either `node-stringprep` is explicitly depending on a particular version of `libgcc`, or the development environment on the build host is only partially installed or misconfigured. I'm going to close this, as this isn't an issue with npm itself, but you might want to check how your developer tools are installed, and then follow up with the maintainers of `node-stringprep` (`npm bugs node-stringprep`) and see if they've seen this problem before.
